### ISSUE TITLE
Revised health apartment left nav

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#49253]
Revised health apartment left nav based on key decisions and IA changes 

Continue left nav discussions to identify future combined state for purposes of planning and technical requirement

**Comment by batemapf** [comment]
Converting this back into an issue. Was automatically changed into an Epic b/c ¯\_(ツ)_/¯.

**Comment by batemapf** [comment]
@MarciMcGuire @mnorthuis Can we define the acceptance criteria for this work? Is it the production of a left nav outline in a spreadsheet or text file? A Sketch prototype?

**Comment by MarciMcGuire** [comment]
@batemapf I fixed the workflow that converted this to an epic.  Re: Acceptance Criteria - we definitely should define the output.  @mnorthuis is it correct to assume this would be a Mural initially, and then it would go to design to be made into a Sketch prototype?

**Comment by mnorthuis** [comment]
@batemapf I would either close this for now,  or reframe it as "Define secondary navigation within the portal", and group it with the other tickets related to defining the landing page and the "scaffolding" of the portal experience.

**Comment by batemapf** [comment]
Closing in favor of https://github.com/department-of-veterans-affairs/va.gov-team/issues/52367
