### ISSUE TITLE
CT: Update display of caution flag information on the search results cards

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#4926]
As a user of the Comparison Tool, I need the caution flag information to be more obvious so that I am aware of potential problems with the schools that I am considering using my benefits at.

## Assumptions:
1. This work is completed behind a production / feature flag so that it is only available in the staging environments and below.

## Acceptance Criteria
1. The "School Closure" caution flag is displayed under the institution name.
2. The "School Closure" caution flag matches DSVA style guidelines.
3. The "Caution" caution flag is displayed under the institution name.
4. The "Caution" caution flag matches DSVA style guidelines.
5. AC 1 - 4 are applicable to:
     - The regular search results
     - The VET TEC search results
6. If an institution has both warnings, the "School Closure" is displayed first.
7. The updated user interface is 508 compliant (see #4919)

## Supporting Artifacts:
1. [Desktop Prototype](https://bahdigital.invisionapp.com/share/TUIACJ7A45W)
2. [Mobile Prototype](https://bahdigital.invisionapp.com/share/UEIACJJKR8T)

**Comment by hughes-dustin** [comment]
GIDS Branch: bah-4926
vets-website branch: bah-4926

GIDS PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/544
vets-website PR: https://github.com/department-of-veterans-affairs/vets-website/pull/11545

**Comment by delli-gatti-michael** [comment]
Local testing complete

![Screen Shot 2020-01-23 at 7.10.24 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/10f10b4d-f1aa-4ad2-8855-59bf11e41ee4)

---

![Screen Shot 2020-01-23 at 7.10.39 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/a8ed1f84-84b4-41e8-9656-b7f54c3a8836)

---

![Screen Shot 2020-01-23 at 7.10.47 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/562e1251-cdf2-41ae-a447-e42866a08aaf)

---

![Screen Shot 2020-01-23 at 7.12.41 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/42ff85cf-7a41-453d-8c46-afa393c43dd7)

**Comment by ccruzgra** [comment]
Hi @delli-gatti-michael I have a couple of recommendations:

The Caution/School Closure label should be an H4. 

The padding left of the icon could be brought in, about 4px to 8px so it's more equal the space right of the icon.

The right padding for the text fields (Caution/School Closure label and description) could have less padding to allow for more text to fit on one line. We're aiming for 12px of padding on the right side between the text and the perimeter of the white field. This is especially important for smaller displays like in the below screenshot where we're having wrapping on 3 lines for the Caution alert description:

![Screen Shot 2020-01-24 at 12.48.43 PM.png](https://images.zenhubusercontent.com/5b55212f6dabc3393a2dbe50/22ec7343-aad8-46ba-be7b-8c5434ff7638) 

Please let me know if you have any questions or concerns.

**Comment by delli-gatti-michael** [comment]
Thanks @ccruzgra 

@hughes-dustin Is going to create a new PR with the final touches which we can track in this same story

**Comment by hughes-dustin** [comment]
Changes are in branch: bah-4962-b (yes, I realize I made a mistake with naming the branch)
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/11570

**Comment by delli-gatti-michael** [comment]
Latest changes shown below:

#### Staging
![Screen Shot 2020-01-27 at 9.22.16 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/2143cec1-e8e2-4af7-b24e-9a8ea1914bec)

---

#### Local
![Screen Shot 2020-01-27 at 9.21.28 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/d1004165-d618-4af1-b113-12e40719946e)

**Comment by delli-gatti-michael** [comment]
The above changes are now live in Staging

**Comment by delli-gatti-michael** [comment]
Final adjustments are included in the following PR:
https://github.com/department-of-veterans-affairs/vets-website/pull/11595#pullrequestreview-350940406

**Comment by delli-gatti-michael** [comment]
Closing this Story
Final adjustments and production flag are covered here: #4929
