### ISSUE TITLE
[Datadog] Eval/Setup USE Monitoring for EKS:Clusters

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#49290]
# Description
As a platform engineer Datadog monitors and alerts need to be evaluated and/or setup for EKS:Clusters

# Acceptance Criteria
- [ ] EKS:Clusters is evaluated for monitoring needs
- [ ] Monitors are created, if appropriate
- [ ] Alerts are created, if appropriate

# Notes
- The USE method for systems:
  - **U**tilization: The average time that the resource was busy serving work. We usually represent utilization as a percentage over time.
  - **S**aturation: The amount of work that a resource is unable to serve. We usually represent this metric as a queue length.
  - **E**rrors: The number of error events. We usually represent errors as a total count.

**Comment by ph-One** [comment]
Verify whether or not this is already covered by EC2's USE monitors.

**Comment by it-harrison** [comment]
[utilization](https://vagov.ddog-gov.com/monitors/113892)

**Comment by jhouse-solvd** [comment]
Note: This issue will carry into the next sprint. We've made significant progress, but there are several refinements needed to ensure comprehensive monitoring for EKS ([Clusters](https://app.zenhub.com/workspaces/platform-tech-team-2-633efe4ca5a428e5294d7ade/issues/gh/department-of-veterans-affairs/va.gov-team/50179) & [Ingress](https://app.zenhub.com/workspaces/platform-tech-team-2-633efe4ca5a428e5294d7ade/issues/gh/department-of-veterans-affairs/va.gov-team/47545)). 

Also, we consulted w/ Platform Tech Team 1 today to inform them of the monitoring that's been put in place for EKS. They are migrating Vets-API to EKS and will be adding monitors for parts of the application that are not yet covered.

**Comment by ph-One** [comment]
https://vagov.ddog-gov.com/monitors/113892

Do not send out notifications for high CPU, that by itself can simply indicate a well utilized system. Instead take a look into if the CPU is throttled / performance is impacted

**Comment by ph-One** [comment]
https://vagov.ddog-gov.com/monitors/113897

You can delete this, it is strictly a component of Vets API. This will likely be covered by TT3

**Comment by jhouse-solvd** [comment]
https://vagov.ddog-gov.com/monitors/113892
- get rid of the cluster name 
- add the "why" to the description 
- include something like 'CPU throttling high' in the name or description 

https://vagov.ddog-gov.com/monitors/113896
- get rid of the cluster name 
- add the "why" to the description 
- what we would expect is: 'how much are we allocating, and what is our capacity'
- take a [look at this as an example ](https://vagov.ddog-gov.com/dash/integration/349/kubernetes-cluster-overview-dashboard?from_ts=1679844946757&to_ts=1679931346757&live=false&tile_focus=3000700704832776)
- we want to make sure we have enough overhead and avoid things like OOM

https://vagov.ddog-gov.com/monitors/113898
- get rid of the cluster name 
- add the "why" to the description 
- add cluster name and operation type to the metric

- for saturation, look at different pressures in Kubernetes, which means that it's running out of resources; ie the nodes are getting asked to do more than they are able to; node could crash, etc

**Comment by it-harrison** [comment]
added a utilization monitor that relates cluster capacity and allocatable memory: https://vagov.ddog-gov.com/monitors/116238

**Comment by jhouse-solvd** [comment]
This issue is nearly done but will stay open into the next sprint so that we can get it properly reviewed.

**Comment by jhouse-solvd** [comment]
Multiple team members have been out of the office recently, which has impacted our ability to complete this. 

But now that @ph-One is back, he should be able to review and provide feedback, and then we'll get this over the line.

**Comment by npeterson54** [comment]
Not quite complete, rolling into next sprint
