### ISSUE TITLE
CT: Deliver Search Results Caution Flag Update to Production

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#4929]
As a developer, I need to deliver the caution flag updates to production so that they are available for the users of the Comparison Tool

## Assumptions:
1. UX has reviewed and signed off on the change as of 2020-01-28.
2. EDU has reviewed and signed off on the change as of 2020-01-29.

## Acceptance Criteria
1. The work completed as part of #4926 is available in production.

**Comment by delli-gatti-michael** [comment]
PR:
https://github.com/department-of-veterans-affairs/vets-website/pull/11595

**Comment by delli-gatti-michael** [comment]
local testing complete

**Comment by delli-gatti-michael** [comment]
Changes are now in production. Closing this issue
