### ISSUE TITLE
[Datadog] Eval/Setup RED Monitoring for EKS:Ingress

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#49293]
# Description
As a platform engineer Datadog monitors and alerts need to be evaluated and/or setup for EKS:Ingress

# Acceptance Criteria
- [ ] EKS:Ingress is evaluated for monitoring needs
- [ ] Monitors are created, if appropriate
- [ ] Alerts are created, if appropriate

# Notes
- May involve synthetics for hitting endpoints
  - Traefik has a healthcheck at /ping
- The RED method for services
  - **R**ate: The number of requests the service is handling per second
  - **E**rror: The number of failed requests per second
  - **D**uration: The amount of time each request takes (latency)

**Comment by ph-One** [comment]
> Platform: EKS Ingress Request Duration (HTTP)

May need to break this up into separate monitors based on request method. Read methods will be pretty quick, while Write methods can take many tens of seconds.

**Comment by ph-One** [comment]
@it-harrison Please look into setting up a synthetic to check the `/ping` endpoint of traefik. This will let us know if the Ingress Controller itself is up and running

**Comment by jhouse-solvd** [comment]
Note: This issue will carry into the next sprint. We've made significant progress, but there are several refinements needed to ensure comprehensive monitoring for EKS ([Clusters](https://app.zenhub.com/workspaces/platform-tech-team-2-633efe4ca5a428e5294d7ade/issues/gh/department-of-veterans-affairs/va.gov-team/50179) & [Ingress](https://app.zenhub.com/workspaces/platform-tech-team-2-633efe4ca5a428e5294d7ade/issues/gh/department-of-veterans-affairs/va.gov-team/47545)). 

Also, we consulted w/ Platform Tech Team 1 today to inform them of the monitoring that's been put in place for EKS. They are migrating Vets-API to EKS and will be adding monitors for parts of the application that are not yet covered.

**Comment by jhouse-solvd** [comment]
https://vagov.ddog-gov.com/monitors/113153
- add the "why" to the description, ie if we have a high number of requests, what does that mean

https://vagov.ddog-gov.com/monitors/113154
- add the "why" to the description
- let's do this as more of a percentage because sometimes we might have a ton of traffic, and our volume will grow quite a bit (ie when we add production workloads) 

https://vagov.ddog-gov.com/monitors/113147
- add the "why" to the description
- see if there are additional duration metrics; let's see if any of those make sense to use alongside what we have already 

let's make sure that we have a synthetic for each environment; duplicate or look to see if they already exist

**Comment by it-harrison** [comment]
synthetics added:

- [dev](https://vagov.ddog-gov.com/synthetics/details/gqm-gv3-c7y?from_ts=1680016566576&to_ts=1680020166576&live=true)
- [staging](https://vagov.ddog-gov.com/synthetics/details/kak-275-jm6?from_ts=1680016769335&to_ts=1680020369335&live=true)

**Comment by it-harrison** [comment]
breaking up the duration monitor by http method:
* [get/head](https://vagov.ddog-gov.com/monitors/113147)
* [put/post/patch](https://vagov.ddog-gov.com/monitors/116254)

**Comment by jhouse-solvd** [comment]
This issue is nearly done but will stay open into the next sprint so that we can get it properly reviewed.

**Comment by jhouse-solvd** [comment]
Multiple team members have been out of the office recently, which has impacted our ability to complete this. 

But now that @ph-One is back, he should be able to review and provide feedback, and then we'll get this over the line.

**Comment by npeterson54** [comment]
Not quite complete, rolling into next sprint

**Comment by it-harrison** [comment]
created anomaly monitor for rate: https://vagov.ddog-gov.com/monitors/121966/edit
