### ISSUE TITLE
[COGNITION]: Facility and Provider Detail pages do not have a descriptive title

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#493]
## Issue
Facility Detail and Provider Detail views do not have a descriptive title that ideally matches the H1. This was noted as a SC 2.4.2 defect. Screenshot attached below.

## Audit Finding
* Note 3, Defect 1 of 1

## Acceptance Criteria
As a user, I would like the page title to match the H1, or include the H1 in the `<title>` tag. This is a best practice for all web applications and pages.

## Environment
* MacOS Mojave
* Chrome latest
* https://staging.va.gov/find-locations/provider/ccp_1851813299 (sample provider)
* https://staging.va.gov/find-locations/facility/vc_0703V (sample facility)

## WCAG or Vendor Guidance (optional)
* [Page Titled: Understanding SC 2.4.2](https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-title.html)

## Screenshots or Trace Logs
![Screen Shot 2019-07-05 at 8.57.50 AM.png](https://images.zenhubusercontent.com/5ac217b74b5806bc2bcd3fc8/27d6132b-6dd2-4b88-a540-65d7559d419e)

**Comment by ncksllvn** [comment]
Will be live today!

**Comment by 1Copenut** [comment]
Verified in staging for facilities and providers. Moving to close.
