### ISSUE TITLE
Enable custom messaging for DownTime Notifications.

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#49303]
## Description

We want to add the ability to pass custom messages to the DownTime Notifications component using Pager Duty.

## Dev Notes
In the v0/maintenance endpoint, if the description field is not empty, we can map the value from the description field to the notification body. If the description field is empty, we can continue showing the default message we already have set up.

## Acceptance Criteria
In pager Duty, custom message is passed using USER_MESSAGE' token/variable.

- [ ]  vaos displays custom message in maintenance window

**Comment by ldelacosta** [comment]
No issues reported. Closing out the ticket.
