### ISSUE TITLE
[Spike] Review FE logic for Choose a VA clinic page

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#49307]
## Background/Request
The product team is looking for assistance from the development to research on how the code is built on the frontend for scheduling flow. We would like to improve the code base in the near future. After the spike ticket is complete, our team will evaluate the next steps to improve the code by comparing the business rules to the current behavior.

### Goal
To understand the behavior of the FE code and update the VAOS documentation

### Requirements to Consider
N/A

---

## Tasks
- Answer the following questions:
  - Q1: How does VAOS display the clinics on the `Choose a VA clinic `page? (Displaying one or multiple clinics)
  - Q2: What are all the alerts for the page? 
  - Q3: What are the error/alert messages that display if a user selects `No, I need a different clinic/I need a different clinic`? 
  - Q4: The user's path after selecting `No, I need a different clinic/I need a different clinic` is to drop the user to the request flow. What are the frontend checks for this action? 
  - Q5: When user selects the clinic to direct schedule, does the code do any checks/calls to the endpoint(s)? Or does the application automatically move the user to the next page `When do you want to schedule this appointment?`
  - Q6: Where does the application pull the clinic name? 
 

For example one clinic, Tester = patient999@id.me, Type of care = Mental Health and Cheyenne VA facility: 
<img width="551" alt="Screen Shot 2022-11-03 at 8 15 07 PM" src="https://user-images.githubusercontent.com/90797205/199858583-41de10cf-55eb-4980-b4a1-0be9c667f538.png">

For example multiple clinics, Tester = judy.morrison@id.me, Type of care = Optometry and Cheyenne VA facility: 
<img width="544" alt="Screen Shot 2022-11-29 at 8 54 27 AM" src="https://user-images.githubusercontent.com/90797205/204547575-fd5d69b7-4d3a-4ef3-84c1-5b0cd4430b4e.png">

## Time Box
16 hours

## Definition of Done
- Tasks are complete
- Research and recommendations are documented in this ticket

---

**Comment by simiadebowale** [comment]
Q1: How does VAOS display the clinics on the Choose a VA clinic page? (Displaying one or multiple clinics)
A: After a patient selects a facility (Cheyenne VA Medical Center/Sidney VA Clinic etc), We perform a series of checks to determine what clinics to display to the user.
- We make 2 api calls, one to `/vaos/v2/eligibility?facility_id=983&clinical_service_id=audiology&type=direct` and the other to `/vaos/v2/eligibility?facility_id=983&clinical_service_id=audiology&type=request`. These api calls accept: **facilityId** (983), **type of care/clinical service ** (audiology) and **type of appointment** (request/direct) as parameters. The response we get back helps determine if the facility (983) supports **requests/direct schedule**
sample response:
```
{
    "data": {
        "attributes": {
            "type": "request/direct",
            "clinicalServiceId": "audiology",
            "eligible": true
        }
    }
}
```
- We make a final api call to `vaos/v2/locations/983/clinics?clinical_service=audiology`. This api call accepts **facilityId** (983) and **type of care/clinical service ** (audiology) as parameters. The response we get back returns the list of clinics under the `parent facility` (983) that support the selected **type of care** (audiology).
sample response:
```
{
    "data": [
        {
            "id": "308",
            "type": "clinics",
            "attributes": {
                "vistaSite": 983,
                "id": "308",
                "serviceName": "Green Team Clinic1",
                "physicalLocation": "Green Tower, 1st Floor",
                "phoneNumber": null,
                "stationId": "983",
                "stationName": "CHYSHR-Cheyenne VA Medical Center",
                "primaryStopCode": 323,
                "primaryStopCodeName": "PRIMARY CARE/MEDICINE",
                "secondaryStopCode": null,
                "secondaryStopCodeName": "*Missing*",
                "patientDirectScheduling": true,
                "patientDisplay": null,
                "char4": null
            }
        },
        {
            "id": "455",
            "type": "clinics",
            "attributes": {
                "vistaSite": 983,
                "id": "455",
                "serviceName": "CHY PC CASSIDY",
                "physicalLocation": "CASSIDY PAVILION",
                "phoneNumber": null,
                "stationId": "983",
                "stationName": "CHYSHR-Cheyenne VA Medical Center",
                "primaryStopCode": 323,
                "primaryStopCodeName": "PRIMARY CARE/MEDICINE",
                "secondaryStopCode": null,
                "secondaryStopCodeName": "*Missing*",
                "patientDirectScheduling": true,
                "patientDisplay": null,
                "char4": null
            }
        },
        {
            "id": "457",
            "type": "clinics",
            "attributes": {
                "vistaSite": 983,
                "id": "457",
                "serviceName": "Green Team Clinic2",
                "physicalLocation": "Green Tower, 2nd Floor",
                "phoneNumber": null,
                "stationId": "983",
                "stationName": "CHYSHR-Cheyenne VA Medical Center",
                "primaryStopCode": 323,
                "primaryStopCodeName": "PRIMARY CARE/MEDICINE",
                "secondaryStopCode": 117,
                "secondaryStopCodeName": "NURSING (2ND ONLY)",
                "patientDirectScheduling": true,
                "patientDisplay": null,
                "char4": null
            }
        },
        {
            "id": "848",
            "type": "clinics",
            "attributes": {
                "vistaSite": 983,
                "id": "848",
                "serviceName": "CHY PC VAR2",
                "physicalLocation": "ARROWHEAD WING, Suite A",
                "phoneNumber": null,
                "stationId": "983",
                "stationName": "CHYSHR-Cheyenne VA Medical Center",
                "primaryStopCode": 323,
                "primaryStopCodeName": "PRIMARY CARE/MEDICINE",
                "secondaryStopCode": null,
                "secondaryStopCodeName": "*Missing*",
                "patientDirectScheduling": true,
                "patientDisplay": null,
                "char4": null
            }
        }
    ]
}
```
<img width="1210" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekxGQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bfbc0fe9a4c621908e57f5d11becc35e51f5fb28/Screenshot%202024-09-10%20at%201.54.26%E2%80%AFPM.png" alt="Screenshot 2024-09-10 at 1.54.26 PM.png" />

**Comment by simiadebowale** [comment]
@ldelacosta - this is ready for validation

**Comment by ldelacosta** [comment]
No further action needed. @JRRoof and I will review. Closing out the spike ticket.
