### ISSUE TITLE
[Datadog] Eval/Setup Monitoring for Network: Reverse Proxy (RED)

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#49300]
# Description
As a platform engineer Datadog monitors and alerts need to be evaluated and/or setup for the Reverse Proxy

# Acceptance Criteria
- [x] Reverse Proxy is evaluated for monitoring needs
- [x] Monitors are created, if appropriate
- [ ] Alerts are created, if appropriate
- [ ] Monitor is in place to verify the reachability of the Reverse Proxy from the _Internet_

# Notes
- https://vfs.atlassian.net/wiki/spaces/OT/pages/1474594232/Reverse+Proxy 
- Reverse Proxies are EC2's that are running OpenResty (a fork/rebuild of Nginx)
  - Each EC2 runs a single proxy
- Use the USE method for systems:
  - **U**tilization: The average time that the resource was busy serving work. We usually represent utilization as a percentage over time.
  - **S**aturation: The amount of work that a resource is unable to serve. We usually represent this metric as a queue length.
  - **E**rrors: The number of error events. We usually represent errors as a total count.
- Use the RED method for services
  - **R**ate: The number of requests the service is handling per second
  - **E**rror: The number of failed requests per second
  - **D**uration: The amount of time each request takes (latency)

**Comment by alexandec** [comment]
RED monitors are created and widgets are added to the Reverse Proxy section of the Platform Monitors & Alerts dashboard. These are ready for review

**Comment by jhouse-solvd** [comment]
Platform - Reverse Proxy Requests/Second High [5m]
- We might want to add a message  
- `avg(last_5m):sum:nginx.net.request_per_s{deployment_env:*} by {deployment_env,host,name} > 300` - this is an absolute value; how did we determine that this is a good number? 

Platform - Reverse Proxy Connections High [5m]
- We might want to add a message 
- `avg(last_5m):sum:nginx.net.connections{deployment_env:*} by {deployment_env,host,name} > 600` - this is an absolute value; how did we determine that this is a good number? 

Platform - Reverse Proxy Connection Open Rate High [5m]
- We might want to add a message 
- `avg(last_5m):sum:nginx.net.conn_opened_per_s{deployment_env:*} by {deployment_env,host,name} > 15` - this is an absolute value; how did we determine that this is a good number? 

Platform - Reverse Proxy Keep-Alive (Waiting) Connections High [5m]
- We might want to add a message 
- `avg(last_5m):sum:nginx.net.waiting{deployment_env:*} by {deployment_env,host,name} > 300` - this is an absolute value; how did we determine that this is a good number? 

Reverse proxy error rate high
- not sure if `nginx_http_request_duration_seconds.count` is the right metric because it seems to refer to the request duration instead of the request count 
- we don't get the raw request count with the free version of openresty that we're using, which might be why we're using the metric above 
- `app:` - might be referring to the reverse proxy app itself? that's an assumption we should validate, or improve the query to be sure what it's referring to 

Platform - Reverse Proxy Not Servicing Requests [5m]
- We might want to add a message 

Platform - Reverse Proxy Not Servicing Requests [5m]
- `avg(last_5m):sum:nginx.net.request_per_s{deployment_env:*} by {deployment_env,host,name} <= 0` - should this be greater than 0? 
- We might want to set a warning threshold 

Platform - Reverse Proxy Dropping Connections [5m]
- We might want to add a message 
- `avg(last_5m):sum:nginx.net.conn_dropped_per_s{deployment_env:*} by {deployment_env,host,name} > 10` - this should not be an absolute value; make this a percentage, ie no more than 5% of the traffic should be dropped

**Comment by rsmithadhoc** [comment]
- [Platform - Reverse Proxy Requests/Second High \[5m\]](https://vagov.ddog-gov.com/monitors/101753)
    - Added message.
    - For the absolute value we are looking at to alert on, I believe the threshold was set based on the graph on the edit screen, but the evaluation graph is different. I reached out to the team on why Datadog shows different graphs, speculating that it might be a bug/weirdness.
        - I updated the thresholds to be based on the evaluation graph instead.
- [Platform - Reverse Proxy Connections High \[5m\]](https://vagov.ddog-gov.com/monitors/101836)
    - Added a basic message, I didn't find good information on what this being high might indicate.
    - I updated the thresholds to be based on the evaluation graph instead.
- [Platform - Reverse Proxy Connection Open Rate High \[5m\]](https://vagov.ddog-gov.com/monitors/102194)
    - Added a basic message, I didn't find good information on what this being high might indicate.
    - I updated the thresholds to be based on the evaluation graph instead.
- [Platform - Reverse Proxy Keep-Alive (Waiting) Connections High \[5m\]](https://vagov.ddog-gov.com/monitors/102167)
    - ...
    - I updated the thresholds to be based on the evaluation graph instead.
- [Reverse proxy error rate high](https://vagov.ddog-gov.com/monitors/97374)
    - I wasn't able to find any good sources for more on this metric,`openresty.nginx_http_request_duration_seconds.count`. The `nginx_http_request_duration_seconds` looks to be [HTTP request latency](https://github.com/knyar/nginx-lua-prometheus#quick-start-guide) but `count` is a part of the metric in the explorer. 
    - Because of that and this being not one of the monitors we created, I opted to remove it from our dashboard. I did not see a metric that had data that could replace this.
- [Platform - Reverse Proxy Not Servicing Requests \[5m\]](https://vagov.ddog-gov.com/monitors/101802)
    - Added message.
- [Platform - Reverse Proxy Dropping Connections \[5m\]](https://vagov.ddog-gov.com/monitors/101839)
    - Added message.
    - Updated this to be percentage based.
- Added alerting chain to all of these.

**Comment by rsmithadhoc** [comment]
Reviewed as a team, closing this one out.
