### ISSUE TITLE
GIDS: Update dashboard after completed Scorecard API request

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#4931]
As a EDU Team Member, I need the GIDS dashboard to accurately reflect the last time data was updated after using the Scorecard API request so that I know when the data was most recently updated.

## Assumptions:
1. A "Failed" request follows current table update behavior; which is to not display the failed information.  Updates to that process will be done in a new story if necessary.

## Acceptance Criteria:
1. The following columns are updated based on the results of the interaction with the Scorecard API request:
     - Status
     - File Name
     - Upload Date
     - Uploaded By
     - Comments
2. The "Status" column:
     - Displays "Succeeded" when successful
3. The File Name column displays url for Scorecard API
4. The "Upload Date" displays the Date and Time the API request was completed
5. The "Uploaded By" displays the username of the user that initiated the API request
6. The "Comments" column displays "Scorecard API Request"
7. The Fetch button is disabled if another user is currently fetching data

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/547

**Comment by delli-gatti-michael** [comment]
This functionality is now live in Staging. Closing this issue

![Screen Shot 2020-01-31 at 9.08.11 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/a1a5e45b-0be1-4745-a4d8-083cadd807b5)

---

#### All columns updated correctly
![Screen Shot 2020-01-31 at 9.08.34 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/c77dd584-b7ac-440c-8bce-b760ecb18b42)

---

#### Below screenshots were taken when another user was already "fetching"
![Screen Shot 2020-01-31 at 9.08.47 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/992c5031-5360-4134-a115-c9f54d12b4a7)

---

![Screen Shot 2020-01-31 at 9.09.02 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/d23a98e0-7749-44cd-8c84-c126dd7864eb)
