### ISSUE TITLE
Content and IA work for VALIfe insurance program launch

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#49316]
The VALife insurance program is launching on January 1, 2023 and the S-DVI program is closing for new enrollment on December 31, 2022. 

This epic is to track all of the content and IA work that needs to be done for this launch, including creating a new VALife tier 1 static page, making content changes to current life insurance pages, setting up the left nav and other IA work.

**Comment by heyjoni** [comment]
IA recommendations here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/valife.md

**Comment by RLHecht** [comment]
This work is complete. Can close this epic.
