### ISSUE TITLE
SOCKS access for Kevin Duensing

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#49325]
### Your Name

Kevin Duensing

### Your Email

kevin.duensing@adhocteam.us

### Your Role and Team

Fullstack Engineer - Benefits Team 1

### Product Manager (PM) name and email

Jacob Worell, jacob.worrell@adhocteam.us

### Product Owner (PO) name and email

Matthew Self - matthewself.dsva@gmail.com

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDJSF+tp91ZItgwV8wb4fv6gKn2hLU+QPwUzxZQmxn90qJvtgGjGe+u1j2fobn45osgwTlNHRK0CtIykVrY46rxYqEqHxKhTMQM4UeTbrjLUDdvcpRcQQjJUXCP0pzK0/EysQHCVARzhhb63gtFUyec7JiAvsqjbNC0ThkcOPsVhTNMCeaQamvyx9RAWB9LdkdSP0SHr+f01MvHWVRkCdbiUfREYdrVvKswIPKHYr4TqWjqJ6MZZTZ0POdAk5JbHds1lZGbE24zK5WL04yry2sbo30TDvgY3iS8xwNsTECm9vSqo2oNbkftEhmZ3Vj0IC/ynmup4U9m+r70IHSlHPD/PSwkZtNJWoV43b/j2Ghl5xve93t9tuy6ZyD7HVb913/ldJXpRXNL8/izGeySQpFTsv3Q1879U3smtTOySYqmpz2bN2q683C+Loe/BP6L3r3hHXnW88XjjV/o763EnifxOGqoDAJYQJ+8NnHemB0Ti80AxfQVc70r4JfnzwkEtXM= kevinduensing@kevin-macbook.lan

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by ianhundere** [comment]
@kjduensing  Access granted ✅ 

Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html 

Reach out in #vfs-platform-support if you have any trouble.
