### ISSUE TITLE
VA Request Flow - Add modality to comments field 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#49337]
## Description
Scheduling Manager is the service layer used to send the data for the VA request. There is a plan to sunset scheduling manager later this year. We need to send the appointment modality in the comments field to Acheron. 

On the `Choose a type of appointment` page, user selects one appointment modality. 

**Screenshot:** 
<img width="396" alt="Screen Shot 2022-11-04 at 4 37 19 PM" src="https://user-images.githubusercontent.com/90797205/200069650-b1216b8c-13a8-4ca1-b7a4-31e6d9fcc6a1.png">

There are no changes to how we send the modality information in `vaos service`. 

---

## Acceptance Criteria
Background: the `va_online_scheduling_acheron_service toggle is on

Given the user is in the VA request flow 
When the user selects `Office visit,` `Phone call,` or `Telehealth,` on the Choose a type of appointment page 
Then the VAOS app will pass the preferred Modality value to into the comments field.

## Suggested format: 

`preferred Modality: Office visit`
`preferred Modality: Phone call  `
`preferred Modality: Telehealth  `

## Suggested Order for the comment fields: 
1.  Preferred Modality 
2.  Contact Information (phone # and email) - #47730
3.  1st, 2nd and 3rd Preferred Dates #47660
4.  Reason Code abbreviation and comments  #47734

### Design Assets
No changes in the design 

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by ldelacosta** [comment]
There are no changes to how we send the modality information in vaos service.

**Comment by jenniemc** [comment]
When making a VA request in the review instance, it's returning a "400 Bad Request" because the `kind` (modality) field is missing in the POST body. Assuming that the Acheron service does not use the `kind` field, I'm thinking Backend needs to remove the required field for Acheron. 
@simiadebowale, @ldelacosta, @JRRoof 

```
[
    {
        "title": "Bad Request",
        "detail": "kind: field is required",
        "code": "VAOS_400",
        "source": {
            "vamfUrl": "https://internal-dsva-vagov-staging-fwdproxy-1821450725.us-gov-west-1.elb.amazonaws.com:4463/vaos/v1/patients/1013120830V747912/appointments",
            "vamfBody": "{\"message\":\"kind: field is required\"}",
            "vamfStatus": 400
        },
        "status": "400"
    }
]
```

**Comment by ldelacosta** [comment]
No issues reported. Closing out the ticket. 
```

{kind: "phone", status: "proposed", locationId: "984", serviceType: "optometry", reasonCode: {,…},…}
kind
: 
"phone"
locationId
: 
"984"
preferredTimesForPhoneCall
: 
[]
reasonCode
: 
{,…}
text
: 
"preferred modality: phone|phone number: 2011001000|email: test@id.me|preferred dates:12/29/2022 AM,12/29/2022 PM|reason code:OTHER_REASON|comments:This is a test 12/1 10:19 am - LD "
requestedPeriods
: 
[{start: "2022-12-29T00:00:00Z", end: "2022-12-29T11:59:00Z"}]
0
: 
{start: "2022-12-29T00:00:00Z", end: "2022-12-29T11:59:00Z"}
serviceType
: 
"optometry"
status
: 
"proposed"
```
