### ISSUE TITLE
AWS access for Sebastian Caso

### ISSUE THREAD

**Issue by s-caso** [department-of-veterans-affairs/va.gov-team#49333]
### COR Name

Doris Lin

### Vendor Onboarding Representative Name

Accenture Federal Services - Alexa Elliot

### Your Name

sebastian caso

### Your Email

sebastian.caso@accenturefederal.com

### Team, Role, and Company of the target individual

Education Benefits and application VFS Backend Engineer

### Product Manager (PM) name and email

cesar.santiago@accenturefederal.com

### Product Owner (PO) name and email

Tammy.Hurley1@va.gov, Eddie.Ricks@va.gov

### Desired AWS Access

Requesting access to dev/staging instances to be able to access data of users and logs 

### Access Expiration

ongoing

### Additional Notes

I'll be mostly debugging issues and will need the ability to access this environment during my employment

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by ianhundere** [comment]
VFS Team Roster

**Comment by td-usds** [comment]
Reached out to VOR

**Comment by td-usds** [comment]
Reached out to VOR

**Comment by td-usds** [comment]
Requested access in dev/staging approved
