### ISSUE TITLE
Access for Keith Adkins

### ISSUE THREAD

**Issue by keithdadkins** [department-of-veterans-affairs/va.gov-team#4933]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Dan Navarra ~Michael Domanski~
- Please provide your name.
   > Keith Adkins
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Pension Automation, Sr Engineer (infra), Ad Hoc
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Internal%20Tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC0M4bKUKjlUrUvWJzCW9Hxc2GKQmaIFLT6U8O9lpLsMeqlRXS76Vri/qvfnw+KhwaSCPW3+RE6Cco9ihxK+5ar3Ui9icpu8d2MNdQuDuP92kXn+lCcMHhttLVIVZE7lhI68YeTssAQZOSkoQxjE9N1DGnqHiDMZZjcwVPv+nlXcSHLLcQZNHbecmxc1fGoOAFnyxRvrXbe3/ZiLEvRwXjWiF79Cr8sLDbp4JJM5+sZg7paPUMpyX9SAttEfcfgg9YVjEyaUhKPgHtx3VjsgSZKdvNKQsuBo+GEGPKQptGAUghxxrPrgzWqmMJ8HB3e0hfeWvY9xgbDRO99EAbS7tuvcIlM82Zjk2TV73Fhx6am5vjDXuKaH5gGyMVId//5M3OxOiTZQbxZqOxurPNIU3inTUcl6j1zJm+shgnb0rLO0iTkTgZL3EDCtMOteq99IMvuBr78QXdgDUkqRqD0SkPqSxU60bLWT5BmHsSjWVsdK0u72ppJH3d2whImCArlgUM= keithadkins@Keith-Adkinss-MacBook-Pro.local
```

- [Grant AWS Console access?]
  > YES
  >  As an infra engineer, I will need access to AWS console to (at least non production environments initially) in order to assist my team with infrastructure related work such as creating/managing resources, logging, monitoring, debugging, etc.

**Comment by keithdadkins** [comment]
pinging @department-of-veterans-affairs/vsp-operations for visibility.

I have my PIV card and CAG access as of now if that is pertinent.

**Comment by ricetj** [comment]
@Jeff-Hayter 
User: Keith Adkins
COR: Michael Domanski

**Comment by keithdadkins** [comment]
@ricetj @Jeff-Hayter Is there anything else I could be doing to help expedite this?

**Comment by keithdadkins** [comment]
@ricetj @Jeff-Hayter Our current COR is Dan Navarro and not Michael Domanski.

**Comment by Jeff-Hayter** [comment]
@keithdadkins I'm not finding Dan's info in the Global.  Does he go by another name?

**Comment by keithdadkins** [comment]
Sorry, try Dan Navarra!

**Comment by keithdadkins** [comment]
@Jeff-Hayter curious if there has been any movement on this? I'm getting some pressure from my team and would like to be able to give a status update.

**Comment by Jeff-Hayter** [comment]
@keithdadkins I've not heard back from Dan.  What I need is a copy of your eQIP transmittal confirmation OR if you're a transfer there's a document called a COI (certificate of investigation).  If you have either of those we can expedite.

**Comment by keithdadkins** [comment]
@Jeff-Hayter I have the transmittal notices for Ben #4592 and myself. I can email them to you if you provide your address. Both Ben and I have our PIV cards as well.

**Comment by Jeff-Hayter** [comment]
@keithdadkins Okay, the one I need is from the security office saying it was accepted (without errors). My email; is jeffrey.hayter@va.gov

**Comment by keithdadkins** [comment]
@Jeff-Hayter I emailed what I had last week. Please let me know if there is anything else you need.

**Comment by Jeff-Hayter** [comment]
@ricetj Approved for SOCKS and AWS.

**Comment by tskinn** [comment]
@keithdadkins you should have access to aws and socks now. Reach out in slack if you have any questions or issues.
