### ISSUE TITLE
Add check status of COE link on the how to request a home loan COE page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#49348]
## Issue Description

Once the COE status tool is at 100% we need to add a link on the [How to request a VA home loan COE](https://www.va.gov/housing-assistance/home-loans/how-to-request-coe/) to point to the newly created Check the status of your VA home loan COE page. 

We need to create the link text and determine where on the page we should put it. This can't go live until the new Check the status of your VA home loan COE page has been published.

## Tasks
- [x] Add text and link to page How to request page
- [x] Review (Laura)
- [x] Copyedit (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] Link is live on the site

**Comment by laurwill** [comment]
@RLHecht I added the link and Megan copyedited and published. We can close this out.

**Comment by RLHecht** [comment]
Thanks! Closing!
