### ISSUE TITLE
DLD:  Switch to using typeDescription to parse different letter types

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#49359]
## Value Statement

**_As a_** veteran looking for their decision letter(s)
**_I want to_** be able to distinguish letters in the list view from each other by seeing clearly what each letter's type is
**_So that_** I don't have to click open each PDF to learn what document type it is

## Background Context
- We've addressed a similar user story in the past by relying on the subject line attribute. We've learned recently that the subject values were never intended to be veteran-facing and, for this reason, there is a risk that there will be subject lines that are potentially insensitive or confusing to the veteran. To limit risk, we are going to rely on the document type attribute, which pulls from a standardized list of values not open to individual editorial decisions. 

## Acceptance Criteria
- [ ] Values that show to the user are using the document type instead of the subject 

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jerekshoe** [comment]
@jacobworrell So are we wanting to just show "Notification Letter (e.g. VA 20-8993, VA 21-0290, PCGL)" if that is the value for the `typeDescription` field?
