### ISSUE TITLE
Contact Center Review for Profile Team - Updates to Account Security - Error Messaging

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#49352]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
We've recently made some updates to improve our error messaging in the Account security section of Profile and have updated them in the attached document.

### Launch Date
Nov 2022

### Version Number
v5.2.1.

### Product Guide

[Link to v5.2.1](https://app.zenhub.com/files/133843125/f8eda0e1-79c2-4ab9-95a2-f2ca6f329dbc/download)

### Product Video
*Please provide product video link*

### Product Video Transcript
*Please provide product video transcript link*

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by SKasimow** [comment]
Hi @starlow00 - here is the latest product guide with some updated error messages. LMK if you have any issues downloading or any questions about the update. Thanks!

**Comment by starlow00** [comment]
Thanks, @SKasimow. I will look it over and get back to you.

**Comment by starlow00** [comment]
@SKasimow, it looks good, no changes. I sent to VEO for review.

**Comment by SKasimow** [comment]
Thanks!

cc @ericasauv09

**Comment by starlow00** [comment]
No changes from VEO. Copy attached.
[VAgov Profile v5_2_1.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/10015356/VAgov.Profile.v5_2_1.docx)

**Comment by SKasimow** [comment]
Hi @starlow00 - did you make any tweaks to the version you sent back above? If so, I'll use this to start my next set of updates :)

**Comment by starlow00** [comment]
Yes, use the version posted here. Thanks, @SKasimow !
