### ISSUE TITLE
Deep linking to products

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#49370]

**Comment by batemapf** [comment]
@MarciMcGuire OK to either downgrade this to an issue and put it in `Backlog` or close altogether if no longer needed? Not clear on what the work is here.

**Comment by MarciMcGuire** [comment]
Some of these are Epics because issues cannot be displayed on the Road Map, but Lauren and I wanted to be able to capture these tasks in a way we could see them there.   https://app.zenhub.com/workspaces/mhv-to-vagov-top-level-view-62619a987d74510018ecc546/roadmap
