### ISSUE TITLE
Unable to connect Handle ID carlospmelendez 

### ISSUE THREAD

**Issue by carlospmelendez** [department-of-veterans-affairs/va.gov-team#49388]
### Description

Created Github handle ID carlospmelendez, Joe Niquette unable to find us in VA list. Once I can be added, I will need access to Grafana, Promethius and Jenkins monitoring tools.

**Comment by vbellissimo** [comment]
@carlospmelendez I'm routing this request to someone who may be able to help with this.

**Comment by vbellissimo** [comment]
@andreahewitt-odd @jwoodman5 Hello. Would either of you be able to help with this issue?

**Comment by little-oddball** [comment]
@vbellissimo I believe this needs to get escalated to our PO. I am working that process now and will reference that respective ticket here as that is the process the PO prefers.

**Comment by little-oddball** [comment]
Here is the reference to the ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/49391

**Comment by PHeb0220** [comment]
Carlos and I have access now.  Can you please add Devinder Rajput with the same access also... his handle is DevinderR  He has been in training this week.

**Comment by PHeb0220** [comment]
@vbellissimo

**Comment by little-oddball** [comment]
@vbellissimo - I have created a PO Escalation ticket for this and assigned it to @mchelen-gov who addressed the previous one referenced above.

**Comment by little-oddball** [comment]
@vbellissimo - @mchelen-gov added some information about GH access as well as the need to go through Platform Orientation to gain access.

For overall VA Github usage and access request info: https://department-of-veterans-affairs.github.io/github-handbook/guides/onboarding/getting-access

For Grafana access they can go through Platform orientation if needed, though I believe it is reachable from GFE w/o SOCKS.

**Comment by mchelen-gov** [comment]
> For overall VA Github usage and access request info: https://department-of-veterans-affairs.github.io/github-handbook/guides/onboarding/getting-access

This should be added as a reference on Platform Website https://depo-platform-documentation.scrollhelp.site/getting-started/request-access-to-tools#Requestaccesstotools-GettingaccesstotheVAGitHuborganization

This issue should only be used for Platform Website feedback, not any further support requests.
