### ISSUE TITLE
Design Intent - Accessibility Feedback - Public Websites, Find-a-form, PDF Certificate Alert initiative

### ISSUE THREAD

**Issue by briandeconinck** [department-of-veterans-affairs/va.gov-team#49389]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
- I have to miss today's Design Intent meeting, out on PTO this afternoon through Wednesday. I'll watch the recording on Thursday and may add/revise my feedback based on the discussion.

## Feedback
- Practice areas will document their feedback following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback).

**Must:**
- On the [Find a Form search page](https://user-images.githubusercontent.com/4054752/199585851-88dc2b79-bf4f-4fba-8051-2f92682285a1.png), there's an issue with where the alert is positioned on the page.
   
   When you enter a search term and press the search button, keyboard focus is moved from the search tool to the "Showing 1 - 10 of..." text, which is an h2 heading above the results. Since focus is managed programmatically in this way, that means screen readers will skip over anything placed between the search tool and the "Showing 1 - 10 of..." heading.
   
   I don't have a specific recommendation for where the alert should go. My hesitation here is that the alert has a heading in it, and moving the alert elsewhere on the page may result in a heading structure that doesn't make sense (content that comes after the alert not being described by that alert heading).

   My recommendation here is to work with an accessibility specialist between now and finalizing your designs for Midpoint Review to try out different scenarios and see what makes the most sense. 

**Should:**

**Consider:**

## Platform directions
- Remove the governance-team label
- Update "Issue Title"
- Link to collab cycle Request epic
- Add your feedback
- Remove the CC-Request label (only if you created the ticket using the New Issue link from the Collaboration Cycle Reviews board)
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review QA Only**: VFS PM, yourself (optional)

**Comment by wesrowe** [comment]
@laflannery, just tagging you here so we can look at this together. I'll schedule time.

**Comment by wesrowe** [comment]
@briandeconinck, we have a solution to your "must" feedback. The life cycle of feedback tickets like this one isn't clear to me. Do you want to review the changes now? Or will this ticket get closed at a later touchpoint?

**Comment by wesrowe** [comment]
"Must" feedback on alert placement was addressed with the help of @laflannery, and the work is now launched in Prod. Closing ticket.
