### ISSUE TITLE
Move Breadcrumbs to Higher Location

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#4938]
## Bug
Per #4756 - The current location of the `<breadcrumb>` component needs to be moved to another location so that it renders correctly and is better picked up by some screenreaders in some browsers.

## Task
It has been suggested we move the following block out to RatedDisabilityApp.jsx, just above the `<RequiredLoginView />` on line 17:

```javascript
<div className="medium-screen:vads-u-padding-left--1p5 large-screen:vads-u-padding-left--6">
  <Breadcrumbs>
    {[
      <a href="/" aria-label="back to VA Home page" key="1">
        Home
      </a>,
      <a
        href="/disability"
        aria-label="Back to the Disability Benefits page"
        key="2"
      >
        Disability Benefits
      </a>,
      <a
        href="/disability/view-disability-rating"
        aria-label="back to the view your VA disability rating page"
        key="3"
      >
        View your VA disability rating
      </a>,
      <a href="/disability/view-disability-rating/rating" key="4">
        Your VA disability rating
      </a>,
    ]}
  </Breadcrumbs>
</div>
```

## Acceptance Criteria
- [ ] The component has been moved and the PR merged.

**Comment by micahchiang** [comment]
PR - https://github.com/department-of-veterans-affairs/vets-website/pull/11596
