### ISSUE TITLE
Person attempting to get access but getting a handle error.

### ISSUE THREAD

**Issue by little-oddball** [department-of-veterans-affairs/va.gov-team#49391]
### What is the issue

Platform team member @joeniquette is working to help out some folks on DGIB w/ getting access to Grafana, etc. as indicated in this ticket.

https://github.com/department-of-veterans-affairs/va.gov-team/issues/49388

### Who is it effecting or who will be effected

There are several people the immediates we are aware of are:

Carlos Melendez
Devinder Rajput
Paul Hebner
Riley Ross

### What have you done to resolve this so far

One on one meetings.
Tried to look them up in VA list to add

### Dependencies

PO or other person who can grant the access

### What's at risk

DGIB not able to continue forward in their work

### Recommendation(s)

PO to get them access or get them in touch with the appropriate people to get access

### Additional Information

NOTE: I have added @joeniquette , @andreahewitt-odd, @vbellissimo and @little-oddball for visibility

https://github.com/department-of-veterans-affairs/va.gov-team/issues/49388

**Comment by mchelen-gov** [comment]
I'm unclear on the issue here, has the user gone through Platform Orientation?

**Comment by joeniquette** [comment]
They aren't onboarding like an app team that I am aware of, they aren't contractors, they are VA employees who have been assigned with the oversight of these apps after a VFS team has terminated support of the products in question. This is a unique request I haven't had to work through before. 

@mchelen-gov they are looking to access grafana, so they need to be added to the github org.

**Comment by mchelen-gov** [comment]
> They aren't onboarding like an app team that I am aware of, they aren't contractors, they are VA employees who have been assigned with the oversight of these apps after a VFS team has terminated support of the products in question. This is a unique request I haven't had to work through before.
> 
> @mchelen-gov they are looking to access grafana, so they need to be added to the github org.

For Github org follow the usual process: https://depo-platform-documentation.scrollhelp.site/getting-started/request-access-to-tools#Requestaccesstotools-GettingaccesstotheVAGitHuborganization

For Grafana access they can go through Platform orientation if needed, though I believe it is reachable from GFE w/o SOCKS. 

Please reopen if there are further issues.

**Comment by mchelen-gov** [comment]
For overall VA Github usage and access request info: https://department-of-veterans-affairs.github.io/github-handbook/guides/onboarding/getting-access

**Comment by joeniquette** [comment]
Ok so the missing piece here was within a VA network only accessible link, which is good to know for future purposes if VA employees who dont have a PM or COR can go to and request access:

**Step 3: Access to the Department of Veterans Affairs Organization**
Once you have your GitHub.com account and have set up 2FA, you will need to request access to the Department of Veterans Affairs organization. You or someone who has access to the site below will need to request your access to the VA organization. Please note that approvals of non-VA emails may take a little longer to process.

Inside the VA network
Visit [https://vaww.oit.va.gov/services/github/](https://vaww.oit.va.gov/services/github/ ) and request access
