### ISSUE TITLE
Notification Letter: DataDog Integration

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#49392]
In order to make sure the application behaving correctly and efficiently, we need to set up monitoring via DataDog. To date, the FedRAMP'd version of DataDog is exclusive to Platform teams. Being a VFS team, we would like write access to set up DD dashboards.

## Background Context
[The DataDog blockage is an access problem](https://dsva.slack.com/archives/CBU0KDSB1/p1667843683267589). Sounds like VFS teams have read-only access, even with an account.

There is an [infra epic to track who needs access and why](https://app.zenhub.com/workspaces/platform-infrastructure-team-6112bc325f570300140f7852/issues/department-of-veterans-affairs/va.gov-team/33081). We could create a separate ticket for datadog and link them.

Additional example: Kyle Soskin (previously on a platform team) [apparently no longer has write access since changing over to a VFS team](https://app.zenhub.com/workspaces/platform-infrastructure-team-6112bc325f570300140f7852/issues/department-of-veterans-affairs/va.gov-team/46872).

Part of: #33081

**Comment by kjduensing** [comment]
@jacobworrell @sortizsh Would y'all mind labeling this ticket correctly so it shows up on our board? Thanks!

**Comment by jerekshoe** [comment]
Update: We now have DataDog access, but we've only been given read-only access so far. We have been told that we will be getting write access at some point in the future as well though, so we should be able to pick this ticket up then. Until we get write access though, this ticket is not workable

**Comment by jerekshoe** [comment]
Update: We now have write access and are able to create DD dashboard/monitors.
