### ISSUE TITLE
STEM: Remove REAP production / feature flag.

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#4939]
As a developer, I need to remove the production / feature flag for removing the REAP option from the 1995 so that the update is available in production.

## Assumptions:
1. UX has reviewed and signed off on the change as of 2020-01-28.
2. EDU has reviewed and signed off on the change as of 2020-01-28.

## Acceptance Criteria
1. The production / feature flag used for story #4765 has been removed and the functionality is available in production.

**Comment by ksantiagomorgan6** [comment]
PR: 

https://github.com/department-of-veterans-affairs/vets-json-schema/pull/376

**Comment by delli-gatti-michael** [comment]
local testing complete

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
All PRs have been merged. This should be in production after the 2:00 deploy today

**Comment by delli-gatti-michael** [comment]
The feature is no longer present in production. Closing this issue
