### ISSUE TITLE
[FE] Ensure that pre-checkin messages are shown at the correct time

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#49394]
change the check-in window from 30 to 45 minutes.

**Comment by brianseek** [comment]
@acrollet & @wullaski there is no PR with this because I didn't see any necessary changes in pre-check-in. So for code review / validation, can one of you verify that?

**Comment by acrollet** [comment]
I took a look and I agree, we show the same message on the day of the appointment from midnight until the end of the check-in window, and the end of the check-in window is pulled from the appointment data in LoROTA. Closing this out.
