### ISSUE TITLE
BE | Profile | Direct Deposit Info Unmasked

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#49408]
### Background
The My-Education Benefits team needs to retrieve direct deposit information for one of their forms so it can be submitted for claims processing. 

Similar to how the Profile Comp & Pen page works:
- The user's DD info will need to masked on the FE form. 
- The user can change the DD info by entering new information.

When the form is submitted to the vets-api...
- If the user did not change the DD info, then an additional call will be made to the BGS service to retrieve the unmasked DD info and add it to the form payload before sending.
- If the user did change the DD info, then no BGS calls need to be made and the form can be sent as is.

This solution will ensure that unmasked data never leaves the vets-api servers.

Original discussion thread: https://dsva.slack.com/archives/CBU0KDSB1/p1667329286428609

### Tasks
- [x] Update/Add method to BGS service that returns DD information unmasked.

### Contacts

My Education Benefits team contacts:
- Bobby Truong
- Cesar Santiago
- Bradley Bergeron

**Comment by bradbergeron-us** [comment]
I have a [PR ready](https://github.com/department-of-veterans-affairs/vets-api/pull/11107) for review using the```
 `service = BGS::Service.new(@current_user)
response = service.get_ch33_dd_eft_info` in our controller. 
```
