### ISSUE TITLE
Modify "WCAG 2.1 success criteria and foundational testing" per new Accessibility Testing artifact

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#49403]
## User Story
_"As a (persona), I (want to), (so that)."_

Assignee:
Peer Reviewer:

## Description
The "[WCAG 2.1 success criteria and foundational testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/wcag-2-1-success-criteria-and-foundational-testing)" page on Platform Website needs to be updated to [address changes](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47916#issuecomment-1305960824) associated with the new Accessibility Testing artifact. 

## Tasks
- [ ] _Placeholder task_

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] _Placeholder AC_

### Refinement
- [ ] Ticket has user story, description, tasks, and acceptance criteria
- [ ] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [ ] Ticket has been sized 
- [ ] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [ ] Ticket has been assigned to appropriate initiative or quarterly epic
- [ ] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@briandeconinck This artifact was archived in ticket #47916. Can we close this ticket?

**Comment by briandeconinck** [comment]
Yep, closing!
