### ISSUE TITLE
GIBCT Accessibility: Firefox w/ JAWS When focused on the Estimate Your Benefits header, JAWS reads too much information

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#4940]
When using the JAWS screenreader combined with Firefox, JAWS continues to read the text after the Estimate Your Benefits header. This applies to both vettec and non-vettec institutions.

![Screen Shot 2020-01-17 at 9.22.31 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/8dc89295-9697-459e-83ba-470c19e936e1)

![Screen Shot 2020-01-17 at 9.23.35 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/edf7f6c4-4f77-43d1-beb0-45b0a1655535)

**Comment by ksantiagomorgan6** [comment]
Pul request
https://github.com/department-of-veterans-affairs/vets-website/pull/11578

**Comment by delli-gatti-michael** [comment]
Local Testing complete and PR approved

**Comment by delli-gatti-michael** [comment]
re-tested in staging. closing this issue
