### ISSUE TITLE
Review new Git Hub page

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#49424]
Tasks:

- [x] Review this new page created in the drafts space: https://vfs.atlassian.net/wiki/spaces/PWD/pages/2422046857/GitHub+Tips
- [x] Provide content editor (Naomi Marcussen) with any feedback, recommendations or questions you may have for them within this ticket.

Notes:

- This page is "targeted to researchers using GitHub for the first time when writing research documents."

- Reference to initial inquiry made by Naomi in the #platform-confluence Slack channel: https://dsva.slack.com/archives/C01AS05BQ79/p1667864791977169

**Comment by taylojill** [comment]
Hi @naomimarcussen I reviewed the page and added inline comments. Please review and let me know if you have any questions. Thank you!
cc @vbellissimo

**Comment by naomimarcussen** [comment]
Thank you @taylojill! I've updated the doc and sent it along to Shane Strassberg to get his thoughts. If he's good with it, then I'll move along to publish.
