### ISSUE TITLE
QA Orientation session - November 2022

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#49439]
## Issue Description
Hosted the QA Orientation Session for VA.gov Platform on 11/17/2022

---
## Tasks
- [ ] Host the session and answer any questions that come up.

## Acceptance Criteria
- [ ] We have provided a QA Orientation session for VA.gov Platform for November 2022.

**Comment by it-harrison** [comment]
@shiragoodman one thing I need to do before the next orientation is to get myself assigned as the host of the session's zoom meeting (last time Peter had to start the meeting and was unable to transfer the host designation to me). Do you know who I can talk to about switching this?

**Comment by shiragoodman** [comment]
@it-harrison unfortunately, we won't be able to get that done for the November session, but we could fix it for December. When the Orientation sessions are scheduled via Calendly, they use 1 person's Zoom. for QA, it's currently Peter. As soon as someone signs up for the session, that Zoom info is shared and there's no way to change it. If we did need to change the Zoom info, the only option is to cancel the meeting for everyone who signed up and then reschedule with the new Zoom. We'd have to ask everyone who previously signed up to sign up again. It's not ideal.

Is there a reason why you need to be assigned as host? We don't record the meeting, and you should be able to screen share when you're not host. Please let me know!

**Comment by it-harrison** [comment]
> @it-harrison unfortunately, we won't be able to get that done for the November session, but we could fix it for December. When the Orientation sessions are scheduled via Calendly, they use 1 person's Zoom. for QA, it's currently Peter. As soon as someone signs up for the session, that Zoom info is shared and there's no way to change it. If we did need to change the Zoom info, the only option is to cancel the meeting for everyone who signed up and then reschedule with the new Zoom. We'd have to ask everyone who previously signed up to sign up again. It's not ideal.
> 
> Is there a reason why you need to be assigned as host? We don't record the meeting, and you should be able to screen share when you're not host. Please let me know!

@shiragoodman no reason except that Peter wouldn't have to start the meeting

**Comment by shiragoodman** [comment]
Let me see if Peter can make me co-host (since I'm Oddball).
