### ISSUE TITLE
Collaboration Cycle for Modernized Check-In, Patient Check-In, Simplified Header & Footer and Progress Bar - Segmented

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#49438]
### If your product is already on VA.gov, please verify your product information in the Product Directory.

- [X] The product information in the Product Directory is accurate.

### VFS team name

Modernized Check-In

### Product name

Patient Check-In

### Feature name

Simplified Header & Footer and Progress Bar - Segmented

### GitHub label for product

HCE-Checkin

### When did/will you start working on this product/feature?

8/24/2022 (feature)

### Will your work result in visible changes to the user experience?

Yes

### Are you doing research with VA.gov users?

Unsure

### Will your work involve changes to...

Tools, applications and dynamic pages

### Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?

Yes

### Do you need to capture any additional analytics or metrics?

No

### Product outline

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/README.md

### Notify the Collaboration Cycle team of this ticket in the vfs-platform-support Slack channel.

- [X] I acknowledge that I must notify \#vfs-platform-support after submitting this issue.

**Comment by CherylEvans** [comment]
Duplicated in error.
