### ISSUE TITLE
KPI dashboards: Content suggestions

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#49443]
Support ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/49437

Tasks:

- [x] review the customer request/suggestion
- [x] document a recommendation
- [x] reach out to SME

**Comment by vbellissimo** [comment]
Hi @shiragoodman . We received a content suggestion related to the Collaboration Cycle content. The original request is here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/49437

On [this page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/collaboration-cycle-kickoff) and [this form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=collab-cycle-review%2Ccollaboration-cycle%2CCC-Request&template=collaboration-cycle-request.yml&title=Collaboration+Cycle+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D), there's a line that says: 

"4. Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?"

The recommendation from the customer is:

_consider to include a KPI dashboard in Google Analytics or other platforms? For example, our application has dashboards within Domo, Google Analytics and DataDog. There's probably a rationale for mentioning Domo explicitly, but I figured I would pose the question._

Do you have any thoughts on whether we should update this line? And if so, how it might be rephrased?

Thanks.

**Comment by shiragoodman** [comment]
Tagging @michelle-dooley for her input. 

@vbellissimo For reference, question # 4 above is a question we ask VFS teams to determine whether or not they should meet with the Analytics & Insights team via the Analytics Request Collab Cycle touchpoint. If they answer no to question # 4, we recommend the Analytics Request. If they answer yes, we then look at their response to question # 5, "Do you need to capture any additional analytics or metrics?" If they answer yes, then we recommend the Analytics Request. If they answer no, then we don't.

**Comment by michelle-dooley** [comment]
@vbellissimo - Domo is called out b/c that is the BI tool the Analytics teams uses and where we will build dashboards that include GA and other data sources for VFS teams.  If teams want to build their own dashboards somewhere else they are welcome to but that would be outside of our support services.  Does that help?

**Comment by shiragoodman** [comment]
@vbellissimo The sentence below question # 5 is meant to cover both 4 and 5. I like your suggestion, though. Can we change the text after 5 to, "We ask this questions to determine if Analytics will need to be involved in your Collaboration Cycle reviews, and if an Analytics Request is necessary." and then the exact same thing under question 4?

**Comment by vbellissimo** [comment]
@shiragoodman you're right, I didn't fully read that carefully. Sorry about that. And yes, I will make the changes based on your direction above. Thanks, Shira!

**Comment by shiragoodman** [comment]
sounds good - thanks @vbellissimo !
