### ISSUE TITLE
Update forms db field values spreadsheet with stakeholder change

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#4945]
## Update forms db field values spreadsheet with stakeholder change

This ticket is to update the spreadsheet with additional stakeholder requirement (related to #4339). 

2 new database fields are being added to the VA forms database. We need to provide Kevin Reid and other form owners the field values for the 2 new fields for the top forms we have identified.

**Task:**
Create a normalized controled list that maps to the **Related to** text field values.

**Comment by jenniferlee-dsva** [comment]
@lunascoop - per convo, and here is the spreadsheet to work off of. ETA Tuesday, so I can review and share with forms manager Wednesday. Thank you! 

(Will Slack you file - GitHub error msg that file type not allowed, even though it is. Sigh.)

**Comment by lunascoop** [comment]
@jenniferlee-dsva I slacked you the updated worksheet for review. https://dsva.slack.com/archives/C52CL1PKQ/p1579296184067700?thread_ts=1579280410.039200&cid=C52CL1PKQ

**Comment by jenniferlee-dsva** [comment]
Thank you @lunascoop. This has been shared with the forms DB manager.
