### ISSUE TITLE
Enhance VSF Team Task Completion Percentages

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#49454]
## Issue Description
_To engage multiple VSF teams and share relevant data regarding task completion percentages

---
## Tasks
- Identify 3 teams with the lowest task completion scores 
- Initiate short-term partnership with the teams and provide relevant data 
- Assist the teams with increasing task completion scores 

## Acceptance Criteria
- Identified teams are in receipt of relevant data 
- 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jkwontheso** [comment]
Hi, @ianMcCullough-ob @ATMiddleton I want to explain this task in my own words so we are all on the same page. Could you correct me if I'm misunderstanding this? 

VFS teams complete tasks that are documented and tracked on GH. The Contact Center Team has customer insight data (DOMO, Medallia, SF) that could help VFS make data driven decisions as they complete their tasks. 

The purpose of this task then is to identify 3 VFS teams with lowest levels of productivity, as seen on GH, and devise a plan of action, which outlines how we'd engage with them and together understand which of the data we own could help them increase their productivity.

**Comment by ATMiddleton** [comment]
That is indeed my understanding.

Best regards,

Anita
Product Manager
305-522-2306

**Comment by jkwontheso** [comment]
@ATMiddleton @ianMcCullough-ob I added a few screenshots to the doc that Ian created that show us the problem the users are seeing

https://docs.google.com/document/d/11V4gDyfOnXpkwaoynJXg5uvh-IaiEQvoRYlrS1FA_Jo/edit#

**Comment by ATMiddleton** [comment]
Combined with https://app.zenhub.com/workspaces/contact-center-62cdd9546ec1530018209672/issues/gh/department-of-veterans-affairs/va.gov-team/49434

**Comment by ATMiddleton** [comment]
Pilot demonstrated for Facility Locator team with positive results.   Met with Facility Locater team - Davin/Dawn - will provide data from 5 categories and documented recommendations- Dave will inform us of Facility Locator team prioritization.  They will let us know if/when they need data and at what frequency.
