### ISSUE TITLE
Request access to Google Analytics and/or Domo

### ISSUE THREAD

**Issue by BillChapmanUSDS** [department-of-veterans-affairs/va.gov-team#49467]
# Request Google Analytics and/or Domo access

## What this form is for
Use this template to request access to Google Analytics and/or Domo. Please complete steps 1 & 2 below. 

## 1. Access Requirements 
Please check the analytics tool(s) you need access to:
- [X] Google Analytics
- [X] Domo
- [X] (Platform Teams only) BigQuery

## 2. User Email Address to Receive Access 
**Due to privacy concerns, please do not put your email in this ticket.** Instead please use `/support` on the DSVA Slack channel [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support), select `Analytics` in the "I need help from" dropdown, and then add in the `Summary of request` section: 
 1. This issue's link 
 2. Emails that need access

_Please note: For Google Analytics, if the user has a VA.gov email address or does not yet have a Google account, they will need to create one by visiting [this link](https://accounts.google.com/signup/v2/webcreateaccount?continue=https%3A%2F%2Faccounts.google.com%2FManageAccount&gmb=exp&biz=false&flowName=GlifWebSignIn&flowEntry=SignUp). Once at that link, VA.gov users and external users with email accounts that are not Google based should select the option "Use my current email address instead"._

_Please list any additional requirements, if any (i.e. edit access). If you are requesting BigQuery access, please share if you will be hooking up an API._

_Once you receive access, you should receive a confirmation email directly from Google or Domo._

 
---

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by michelle-dooley** [comment]
@BillChapmanUSDS - Access to GA and Domo has been granted.  Are there specific tables in BQ you need access to?  We try to limit BQ access to only what users need and most people don't need it at all, its more for the Analytics and select Platform teams.

**Comment by BillChapmanUSDS** [comment]
Hey Michelle, Thank You!   I discussed Big Query with some of the Platform Crew ***@***.***, ***@***.***> and @Delrue, Thomas ***@***.***>) and we think that in my role as an SRE lead it would be valuable for me to have full (all tables) but read-only access. If this is a problem we can open it for further discussion, but I'm trying to ensure I have the access I need to take a wide view across the platform and look for insights.

Thanks,

From: Michelle Dooley ***@***.***>
Sent: Thursday, November 10, 2022 10:04 AM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Chapman, William W. II ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Request access to Google Analytics and/or Domo (Issue #49467)


@BillChapmanUSDS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBillChapmanUSDS&data=05%7C01%7C%7C346704bd11b343d535de08dac32cbee8%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C638036894191039183%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=HukWNTVF77d90Jrbn4S9uXLeY%2Bw9meXYixUDLU1avzE%3D&reserved=0> - Access to GA and Domo has been granted. Are there specific tables in BQ you need access to? We try to limit BQ access to only what users need and most people don't need it at all, its more for the Analytics and select Platform teams.

-

**Comment by BillChapmanUSDS** [comment]
I approve Bill's request: access to all tables but read-only.
He has a legitimate need-to-know that justifies his access.

________________________________________
Van: Chapman, William W. II ***@***.***>
Verzonden: donderdag 10 november 2022 11:22
Aan: department-of-veterans-affairs/va.gov-team; Wang, Ray; Delrue, Thomas (he/him/his)
Onderwerp: RE: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Request access to Google Analytics and/or Domo (Issue #49467)

Hey Michelle, Thank You!   I discussed Big Query with some of the Platform Crew ***@***.***, ***@***.***> and @Delrue, Thomas ***@***.***>) and we think that in my role as an SRE lead it would be valuable for me to have full (all tables) but read-only access. If this is a problem we can open it for further discussion, but I’m trying to ensure I have the access I need to take a wide view across the platform and look for insights.

Thanks,

From: Michelle Dooley ***@***.***>
Sent: Thursday, November 10, 2022 10:04 AM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Chapman, William W. II ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Request access to Google Analytics and/or Domo (Issue #49467)


@BillChapmanUSDS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBillChapmanUSDS&data=05%7C01%7C%7C309b565cad97419df1e308dac337c16f%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C638036941476007610%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=XotTJ%2BP69c8mQMqJezpliaO3ZFdJ5zv1i%2Bd6%2BPNBDmw%3D&reserved=0> - Access to GA and Domo has been granted. Are there specific tables in BQ you need access to? We try to limit BQ access to only what users need and most people don't need it at all, its more for the Analytics and select Platform teams.

**Comment by BillChapmanUSDS** [comment]
Michelle and I spoke about this request during our PO sync. She will move forward with granting the read-only access.

 
RAY WANG
PRODUCT MANAGEMENT LEAD
CONTRACTING OFFICER'S REPRESENTATIVE
VA.GOV PLATFORM
OFFICE OF THE VA CTO  
919-685-0067


-----Original Message-----

**Comment by michelle-dooley** [comment]
@BillChapmanUSDS - View access to BQ has been granted.
