### ISSUE TITLE
[Dev:] Update message for when users hit Appointment request limit 

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#4946]
## Story
When a user hits the appointment request limit, we need to show a message letting them know that and they have two options:

- Go to the appointment list view and cancel any outstanding requests that are older than X number of days
- Or call the medical facility to request appointment and cancel older appointments.

## AC
- [ ]  Below message is implemented into VAOS tool
- [ ]  @peggygannon validates content implementation on staging

-------

**You’ve reached the limit for appointment requests at this location**
We can’t process your appointment request because you’ve reached the request maximum for this facility. You’ll need to schedule or cancel your pending appointments in order to request this appointment. To schedule or cancel your pending appointments:

• Go to [your appointment list](link to Appointment card screen) and cancel pending appointments older than [[TK number]] days, **or**
• Call the medical facility to request your appointment

**Comment by jbalboni** [comment]
@peggygannon The current content for this alert is:

**You already have an appointment request at this location**
Our records show that you have an open appointment request at this location. We can’t schedule any more appointments at this facility until the open appointment requests are scheduled or canceled.

I believe this content came from you as well as the content in the issue description. Which one is the right one for us to use?

The one in the issue description above is technically more accurate, since the request limit isn't necessarily 1.

**Comment by peggygannon** [comment]
Hi, @jbalboni Ha! there must have been a duplicate issue for this somewhere along the way! I think we should with the first one (but with some additional tightening of the language). See below: 

**We can't process your appointment request**
You’ve reached the limit for appointment requests at this location. You’ll need to schedule or cancel any pending appointments in order to request this appointment. To schedule or cancel your pending appointments:

• Go to [your appointment list](link to Appointment card screen) and cancel pending appointments older than [[TK number]] days, or
• Call your medical facility(can we should their local facility info?)

**Comment by jbalboni** [comment]
@peggygannon The "We can't process your appointment request" language is a little odd to me, since we're not trying to create or process anything yet. We just can't proceed any further in the flow for this type of care and facility.

**Comment by peggygannon** [comment]
@jbalboni Please let me know if this message is more accurate? 


**You’ve reached the limit for appointment requests at this location**
Our records show that you have an open appointment request at this location. We can’t schedule any more appointments at this facility until your open requests are scheduled or canceled.
To schedule or cancel your open appointments:

• Go to [your appointment list](link to Appointment card screen) and cancel open requests older than [[TK number]] days, **or**
• Call your medical facility(can we show their local facility info?)

**Comment by jbalboni** [comment]
@peggygannon That looks mostly good to me. There's not a number of days requirement that I'm aware of, they would just need to cancel any open requests or wait for a scheduler.

We can show facility info there if we need to. The user will already be able to see the VAMC name in the radio button list, but we could show phone or address.

**Comment by peggygannon** [comment]
ok, @jbalboni  thanks. So would it be more accurate for the 2nd bullet to say something about "wait for a scheduler to get back to you to schedule your open request"? 

I got direction somewhere along the way that having user to call their VAMC was an action we should recommend, but I can revised this, if that is not the best option for this message.

**Comment by jbalboni** [comment]
@peggygannon I think calling is ok to recommend. I'm just saying that the first bullet shouldn't mention a number of days. It's just any open requests that need to scheduled or canceled before going any further.

**Comment by peggygannon** [comment]
Ok, here you go! 


**You’ve reached the limit for appointment requests at this location**
Our records show that you have an open appointment request at this location. We can’t schedule any more appointments at this facility until your open requests are scheduled or canceled.
To schedule or cancel your open appointments:

• Go to [your appointment list](link to Appointment card screen) and cancel open requests, **or**
• Call your medical facility(can we show their local facility info?)

**Comment by jbalboni** [comment]
@peggygannon How does this look?

![Screen Shot 2020-03-30 at 11.19.20 AM.png](https://images.zenhubusercontent.com/599c94608f62dc7798c3b2cd/f26be078-724c-4ad9-a4e5-30f029c34067)
