### ISSUE TITLE
HPA scaling on custom metrics for vets-api server and worker for dev

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#49462]
**PROBLEM STATEMENT**
Current scaling for vets-api server and worker is based on CPU metrics. This form of horizontal autoscaling is not completely accurate based on our current worker and server implementation. We want to scale on more accurate, custom metrics such as queue size and puma backlog so that the pods can autoscale without human intervention. Using a CRD, we can pull in existing Datadog metrics to scale server and worker pods.

**DEFINITION OF DONE**

**Comment by LindseySaari** [comment]
Puma is scaling on external DD metics, but we are waiting on a custom solution for sidekiq metric aggregation
