### ISSUE TITLE
[Spike] React Components in VAOS 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#49471]
## Background/Request
The Design System teams plans to deprecate the React components and will need to update any React components that is still active in VAOS to the web components. 

### Goal
To research which React components are still active in VAOS

### Requirements to Consider
Upgrading the React components to web components

---

## Tasks
- Answer the following questions:
  - Q1: We have updated some of the React components to web components but there may be some components not listed in the Epic #33308. Are there any other React components used in VAOS that is not listed below? If yes, please provide the component name. 

      - Accordion - n/a
      - Additional Info - #33739
      - Alert Box - #25890
      - Back to Top - n/a
      - Breadcrumb - #40139
      - Button Pair - #45517
      - Checkbox - tbd
      - Featured Content - n/a
      - File Input - n/a
      - Link - #47132
      - Loading Indicator - #33142
      - Modal - #38608
      - On this Page - n/a
      - Pagination - n/a
      - Process List - n/a
      - Progress Bar/Segmented Progress Bar - n/a
      - Promo Banner - n/a
      - Privacy Agreement - n/a
      - Published Card - n/a
      - Radio Buttons - #45792 - determined not used in VAOS.
      - Select - #29418
      - Tables - n/a
      - Telephone - #40034, #45155
      - Text Input - tbd

## Time Box
8 hours

## Definition of Done
- Tasks are complete
- Research and recommendations are documented in this ticket

---

**Comment by jenniemc** [comment]
Q1: Review the component names marked with 'tbd' to check if VAOS uses it and if they require conversion. 
A1: 
**Checkbox** - Determined not in use in VAOS. After performing a search for `@department-of-veterans-affairs/react-components/Checkbox`, it appears there is no import of the CheckBox react component in VAOS. The checkboxes are generated from the forms library using the HTML `<input>`

**Text Input** - Determined not in use in VAOS. After performing a search for `@department-of-veterans-affairs/react-components/TextInput`, it appears there is no import of the Text Input react component in VAOS. The Text input are generated from the uiSchema

---
Q2: Are there any other React components used in VAOS that are not converted or identified? If yes, please provide the component name. 
A2:
**ExpandingGroup** - The expanding group is the react component to be deprecated. Solution is to use the [Additional Info web component](https://design.va.gov/storybook/?path=/docs/components-va-additional-info--default) which achieves the same function as the expanding group. An example of current use case is found in `https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/vaos/appointment-list/components/ConfirmedAppointmentDetailsPage/VideoInstructionsLink.jsx#L19`

**Comment by ldelacosta** [comment]
Ticket [51131](https://app.zenhub.com/workspaces/vaos-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/51131) - we will work on updating expanding group component.
