### ISSUE TITLE
Fix vets-api docker build to handle new certs and encodings

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#49491]
## Description
On 11/7, it appears that that some new [VA certs were added](http://aia.pki.va.gov/PKI/AIA/VA/). The new certs have various encodings, which our current [docker build for EKS](https://github.com/department-of-veterans-affairs/vets-api/blob/k8s/Dockerfile#L33-L36) doesn't handle. [Example GHA failure for the docker build ](https://github.com/department-of-veterans-affairs/vets-api/actions/runs/3428465229/jobs/5712778877)

## Questions and Current Progress
- Why are we not notified upon cert changes?
- Kyle is working on updating the script to account for various encodings

**Comment by ph-One** [comment]
https://github.com/department-of-veterans-affairs/vets-api/actions/runs/3429371915
https://github.com/department-of-veterans-affairs/vets-api/actions/runs/3429371900
https://github.com/department-of-veterans-affairs/vets-api/actions/runs/3429371894

**Comment by ph-One** [comment]
![image.png](https://images.zenhubusercontent.com/622146ffd0422cdb4d9fdd52/7e4bb32e-1931-4030-b60a-27245fd374b8)
