### ISSUE TITLE
[FE] 10-10CG: Effort Estimate for Facility "Cards"

### ISSUE THREAD

**Issue by markfallows** [department-of-veterans-affairs/va.gov-team#49501]
For improving the 10-10CG facility selection, we'd like to potentially list facilities in a card-like format so we can include additional information about the facilities in the list, such as address and telephone number.

Some kind of blocked view of the information for the facilities so it's clear what information (address, telephone number, etc..) belongs to which facility, and a clear divide between facilities is visible.

**Comment by longmd** [comment]
Very straight forward on this one. We have the data and we have the design system to follow, so implementation will go quickly on this one. Should be no more than 10-12 hrs to complete.
