### ISSUE TITLE
[FE] 10-10CG: Effort Estimate for Additional Filtering (City)

### ISSUE THREAD

**Issue by markfallows** [department-of-veterans-affairs/va.gov-team#49500]
For the Facilities Redesign, we'd like to potentially take the facility information we receive from the Lighthouse API and do additional filtering based on the metadata that's provided with the call, specifically limiting by city, to help provide the most useful information.

Potential additional options:
- Dropdown that shows a list of valid cities based on state
- Type-ahead to fill in city names

Example: [VA Facility Locator](https://www.va.gov/find-locations/)
- Select `Community Providers` from the *Facility Type* dropdown to trigger type-ahead.

**Comment by longmd** [comment]
Based on us already have samples to work from within the facility-locator app and the data relevant to us on the initial API call. This would take no more than one sprint to complete. I reckon it would take around 40 hrs to implement and validate in testing.
