### ISSUE TITLE
[FE] My VA Audit UX Improvements: Update Copy in Claims Section from "View" to "Review"

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#49514]
## Background
As part of our midpoint review for the My VA Audit project we were asked to update all instances of the word "view" to "review" to avoid using sighted words. In the Claims and Appeals section we have a link that states "View details", we need to update this to "Review details." Sketch files can be found [here](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/25LlG1l) and FE documentation can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/claims-and-appeals-FE-documentation.md).

## Tasks
- [x] Update copy from "view" to "review" in Claims and Appeals section
- [ ] Validate

## Acceptance Criteria
- [ ] The Claims and Appeals link reads "View Details"

**Comment by tmitchellgcio** [comment]
Give this maybe 30 min before testing on staging

**Comment by ericasauv09** [comment]
verified with user 15: ![Screen Shot 2022-11-17 at 15.21.03.png](https://images.zenhubusercontent.com/62571b850845ac72a9917e8e/a290802f-2371-4bef-b33f-92e796450f58)
