### ISSUE TITLE
Design | Profile | Nametag | Update Documentation

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#49512]
## Background

We need to update any existing or create new documentation for the Nametag feature. Currently, this [documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/frontend/documentation/nametag.md) exists so we can review/edit this as needed. The need for documentation stemmed from [this question](https://dsva.slack.com/archives/C018V2JCWRJ/p1668018835059419) in slack. Currently we are updating sketch files and use cases so this would include any documentation outside of that.

## Tasks
- [ ] Update documentation for Nametag
- [ ] Determine where this documentation should live (as its a shared feature of Profile and My VA)

**Comment by SKasimow** [comment]
Closing...dupe to #49616
