### ISSUE TITLE
Analytics Internal - BQ initial cleanup

### ISSUE THREAD

**Issue by chloedotbrown** [department-of-veterans-affairs/va.gov-team#49559]
## Scope

Complete initial cleanup of `vsp_sites` and associated Analytics project folders in BigQuery to remove tables and views created by previous Data Engineer that are no longer necessary.

Tables and views for which current usage and downstream impact is unknown will be left and documented for future review.

## Action items
- [x] Identify tables/views to be deleted
- [x] Verify not currently being used
- [x] Document what's been deleted and what may be a candidate for deletion after further discussion

**Comment by chloedotbrown** [comment]
To make sure none of these supported current, active work, I searched Project History in the summary field for view or table names. Although this history only goes back several months, it seems reasonable to assume that if nothing came up from this query, it was not supporting an active process or Domo data source.

### Deletion record
Asset | Type | Description
------|------|------------
`projects/86772881199/locations/us/transferConfigs/62458ac5-0000-25c4-804a-089e083239cc` | Scheduled Query | Weekly job that replaces `CONTENT ENGAGEMENET` table
`vsp_sites.CONTENT_ENGAGEMENET` | Table | Weekly backfill of all content engagement data created 11/24/2021 by Julie
`vsp_sites.temp_34e797ce165944e7b9f4c7c8463e5c5b` | Table | Duplicate of one of forms datasets, created 7/15/22 by unknown
`vsp_sites.vw_engagement` | View | Seems to be time_on_page draft from April
`vsp_sites.vw_forms_funnels_backup` | View | Original version of forms_funnels not updated since May
`vsp_sites.vw_forms_funnels_last_week_test` | View | December 2021 draft, not updated since
`vsp_sites.vw_forms_funnels_testing` | View | Worked on (I think by Julie) May 11-14
`vsp_sites.vw_forms_funnels_last_week_time_on_step` | View | Created (I think by Julie) in December '21, last updated May
`vsp_sites.vw_forms_funnels_last_week_time_on_step_backup` | View | Created by Julie May 2022, not modified or used since
`vsp_sites.vw_forms_funnels_time_on_step_backup` | View | Created by Julie May 2022, not modified or used since
`analytics_testing.TEST_last_week_homepage` | View | No longer needed - for homepage content engagement edgecase QA
`analytics_testing.TEST_1010ez_v3` | View | No longer needed - for QA of 10-10EZ v3 logic
`analytics_testing.TEST_last_week_content` | View | No longer needed - for QA of alternate content logic from July '22
`analytics_testing.alt_content_last` | View | No longer needed - for QA of alternate content logic from July '22
`analytics_testing.forms_backup_20220819` | Table | No longer needed - created backups of all forms table before Pavan's 1st add
`analytics_testing.forms_definitions_backup_20220819` | Table | No longer needed - created backups of all forms table before Pavan's 1st add
`analytics_testing.forms_steps_backup_20220819` | Table | No longer needed - created backups of all forms table before Pavan's 1st add
`analytics_testing.vw_forms_engagement_backfill_20220327` | Table | No longer needed - TTC test for one day's data
`analytics_testing.vw_forms_engagement_backfill_202008` | View | No longer needed - TTC test for one month's data
`analytics_testing.vw_debt_portal_last_week` | View | No longer needed - from debt portal edge case QA
`analytics_testing.vw_forms_funnels_last_week_time_on_step_backup` | View | Created by Julie on her last day - dupe of version already moved into this folder


### Marginal cases
I did not delete the following, though they may be candidates for a second pass in the future. For now, I'm adding a record of actions taken below: 

- `vsp_sites.vw_forms_funnels_time_on_step` - Supports the dataset in Domo that supports old, in-progress Redshift workflows. Moved to `analytics_testing` folder, added note to description field in BQ, and updated Domo connector to reflect new location.
- `analytics_testing.vw_forms_engagement_last_week_newjoin` - Created Julie's last day - unsure whether still relevant, as Forms Engagement supports form versions. Added note to description field in BQ
- `analytics_testing.vw_forms_engagement_last_week_prev_page_path_test` - Created Julie's last day - unsure whether still relevant, don't know what problem this was supposed to solve. Added note to description field in BQ
- `analytics_testing.vw_forms_funnels_last_week_backup` - Created Julie's last day - unsure whether still relevant. Added note to description field in BQ
- `analytics_testing.vw_forms_funnels_last_week_test` - Created Julie's last day - unsure whether still relevant. Added note to description field in BQ
- `analytics_testing.vw_forms_funnels_last_week_time_on_step_backup` - Created Julie's last day - unsure whether still relevant. Added note to description field in BQ

@michelle-dooley - take a look and let me know if there's any other action you'd like me to take on this this sprint.
@dorseypa1 - CC'ing you here for situational awareness!

**Comment by michelle-dooley** [comment]
Thanks @chloedotbrown - interesting she created so many things on her last day?!?!  I'm good to keep them for now, we can take another look after @dorseypa1 gets up to speed.  I will go ahead and close unless you say otherwise...
