### ISSUE TITLE
SOCKS access for [Elizabeth Koch]

### ISSUE THREAD

**Issue by elizabethkochBT** [department-of-veterans-affairs/va.gov-team#49555]
### Your Name

Elizabeth Koch

### Your Email

elizabeth@bluetiger.digital

### Your Role and Team

Sr Product Manager - Identity Product Login.gov adoption Team

### Product Manager (PM) name and email

elizabeth@bluetiger.digital

### Product Owner (PO) name and email

john.rahaghi@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC6DDAk2oXxqiMTyrDliCuyCGcObY4wP8y6iayFNikWtSB092G8NtV7R67y50Fq/FD5u4tjdhvs1QCWr3trC/kfy0sIczzjddv0pkFy6H6d0eA3haoS6R8M1J/JVc+p/8xtCbepdJ9RnV6rQfTYLCySHvM6vWGM4NBqsxQ6iP63/BY/Cb9XZjamaT1+HLaldtHl0UctIjiVKbQ1gP0+pU7E5LCpThbVadUU18BfdYwOPrWZxe9zEGZahe+7a9tbwkvJSX/J9R/H3w/z7NAR8F6PdAXRa08zchYntGaUp/Agkz/UCrG43k71Mys0q5r/uoFS1ks6dxNTfSBf9+GICgTBelUdl98An0IwEBxniTv2lW04MOYfBsR6IGo5xeS+fACAPK+1Bnew/Em0fx4nienb1w/OT536hqR5WMu1gEWY9D2Pxfw8kzD+H734g1kGG1Sgvt1CuSeNJIsssFwJaZNVMcnOBx1Q/0yl6KsiGiZaXkefR8vGyhlkNNrDQBCYdTc= elizabeth@Elizabeths-MacBook-Pro-16.local

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by rmtolmach** [comment]
@elizabethkochBT Access granted ✅ 

Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html 

Reach out in #vfs-platform-support if you have any trouble.
