### ISSUE TITLE
[FE] My VA Audit UX Improvements: Updates to LOA1 State based on Midpoint Review feedback

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#49558]
## Background
During Midpoint review we received some feedback around our LOA1 state, the feedback was to use an em dash instead of a regular dash in the phrase "we need to make sure you're you - and not someone pretending to be you. - before we give you acces.."

Updated [sketch files](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/uuid/32BCF55D-35A5-4A17-9F37-3DCA903B7A50) and [FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/LOA1-state-FE-documentation.md) here.
## Tasks
- [x] Update regular dash to em dash
- [ ] Validate

## Acceptance Criteria
- [ ] Em dash is used in the LOA1 state copy

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)? Any team member_
- _How can this work be validated?_ need to find an LOA1 user to verify this with

**Comment by tmitchellgcio** [comment]
Just merged should be ready in an hour or so

**Comment by ericasauv09** [comment]
putting back to in progress - there should not be a space between the em dash and the words - ![Screen Shot 2022-11-28 at 15.19.13.png](https://images.zenhubusercontent.com/62571b850845ac72a9917e8e/0081d8ec-7169-418a-990c-a90db7addf27)

**Comment by ericasauv09** [comment]
There should be a gap between the Profile link and the LOA1 message, putting this back to In progress for @tmitchellgcio to update - ![Screen Shot 2022-11-30 at 09.38.53.png](https://images.zenhubusercontent.com/62571b850845ac72a9917e8e/ae8fc631-ec35-436f-853f-44832d266362)

**Comment by ericasauv09** [comment]
validated in staging:
![Screen Shot 2022-12-01 at 15.11.03.png](https://images.zenhubusercontent.com/62571b850845ac72a9917e8e/d865ee92-736e-496e-b823-f46936574fab)
