### ISSUE TITLE
New Account Education Page from Virtual Agent Chatbot Team

### ISSUE THREAD

**Issue by ianpsant** [department-of-veterans-affairs/va.gov-team#49575]
## What does your team need support for? Check all that apply.
- [X] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [ ] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
  - [X] Content support
  - [ ] IA support
  
  
*Please be specific about the content or IA support you need and provide any additional documents and/or links that will help us help you. If we need to add a react widget to a page, be sure to provide the code here.*

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [ ] Yes
  - [X] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
## When do you expect to launch your product to 100% of users?
  
January 16, 2023 or sooner.
  
## Supporting artifacts
*Please provide supporting artifacts as available.*

## Use Case
The Chatbot is building a workflow that will allow users to self-serve any of their sign-in related issues via content that we'll source from the four sign in providers (Login.gov, ID.me, MyHealthevet, and DS Logon) or links to actions they can take on those providers pages. One of the first questions we'll ask the user is which provider they need help with. If the user doesn't know which one to select, an "I don't know" option will be presented to them. This option will be used by people who perhaps don't have one of the four accounts, or need help understanding the differences between them.

The Chatbot will respond with a link to a page located on VA.gov that will educate on why they need a VA.gov sign in account via one of the four providers, or help them understand the differences between the four. The following use case describes the flow.

1. User navigates to Chatbot
2. User types in 'sign in support'
3. User selects "I don't know button" on the Chatbot response that asks them which Sign in account they need help with?
4. Chatbot responds with a message (provided by Content team) letting them know they can visit a VA.gov page to learn more about why they need a sign in account and the differences between them.
5. User clicks on link in response
6. Chatbot redirects user to Account Education page on VA.gov (created by Content Team)

In the mockup we have this in the form of a matrix that describes different functionalities and whether the Sign in provider supports it. This could also just come in the form of text describing the differences between accounts. Optionally, the mock up contains a link to each Sign in Accounts external Account Creation page. The Chatbot has created logic to alert us when the external Account Creation page is not available. We can share this logic. A link to the Account Creation page isn't strictly required but User Research indicated that users appreciated the link.

- Link to product outline:
  - https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/virtual-agent/Virtual_Agent_Product_Outline.pdf
  - https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/virtual-agent/Virtual_Agent_Product_Outline_Phase2.pdf
- Link to prototype or mockups:
  - https://www.sketch.com/s/b5a58a23-6128-421b-9869-50bad5b2686f/prototype/a/53B35A89-F2BA-4297-84BC-4E6239AC6975 (we can provide access) 
- Link to any epics/issues that may be helpful:
  - https://github.com/department-of-veterans-affairs/va-virtual-agent/issues/645

### Requests
1. Content Team to create a new Account Education page that talks about the importance of having a VA.gov login via one of the four Sign in account providers, as well as the differences between them, and perhaps a link to create an account.
2. Chatbot team needs the copy for the response within the Chatbot that describes the Account Education page that we are directing users to click on.
3. Information Architecture Team to suggest where this Account Education page will reside.

## Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [X] No

## When does this work need to be done?
- Estimated launch date: January 16, 2023 or sooner
- Estimated staging review date: You can see the current progress by going to https://dev.va.gov/contact-us/virtual-agent/ and following steps listed above in user flows
- Content and IA work needed by:  December 30, 2023

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [X] No, but I'd like to schedule time to talk about this request
- [ ] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name:  Virtual Agent Chatbot
-	OCTO-DE product owner: @LucianaAlexanderMorais 
-	Product manager: @agmurphy 
-	Designer: Matt Terwilliger
-	FE engineer:  @ksk385 
-	Product/team Slack channel: #va-virtual-agent-public

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by heyjoni** [comment]
Hi @ianpsant, I'm currently working on IA recommendations and have a few questions:
* Is the new page meant for people who don't know which login service to use specifically for va.gov?
* This page could also be discoverable outside the chatbot (people would navigate to it while browsing the site?) - that's what I'd recommend
* Once folks visit the new page, I'm  wondering if there's more value in bringing people to the login modal on va.gov they can log in using the service of their choice, rather than taking them away from va.gov to visit the different login service pages? What do you think?

Thanks,
Joni

**Comment by ianpsant** [comment]
Hi @heyjoni I updated our prototype which you can find here https://www.sketch.com/s/b5a58a23-6128-421b-9869-50bad5b2686f/prototype/a/53B35A89-F2BA-4297-84BC-4E6239AC6975 or you can access the Chatbot in the Dev environment here https://dev.va.gov/contact-us/virtual-agent/ and use the keyword of "sign in". Regarding your questions

- This is a new page mean for people who don't know which login service to use. It could also be a page that talks about the benefits of being able to log in to VA.gov using one of the four sign in providers which I know is another sign in initiative that we're trying to product content for.
- Yes that is the intention that it would be a non authenticated, discoverable page that anyone on VA.gov could discover and the Chatbot would just link to.
- I think that would make sense. Especially if you're pushing for people to create a Login.gov or ID.me account. Also, you'd be able to control the internal page rather than linking externally. My only question is if after visiting this Account Education page and seeing what each of the different Account Types gain you, what if you actually do need to create a MyHealthevet or DS Logon account? There's no link to create an account on the login modal. I know the Chatbot has an external link to MyHealthevet and DS Logon to their create account pages though. Perhaps linking to those two on the Account Education page would make sense so it's not a dead end? But at that point why not link to all four? I could be swayed either way and happy to talk through this some more if needed.

**Comment by heyjoni** [comment]
Since this will be a Resources and Support page, there won't be any IA work but please let me know if that changes.

**Comment by aliyahblackmore** [comment]
Hi @ianpsant !

The new **Creating an account for VA.gov page** was copy edited and we plan to publish by end of day tomorrow (12/16) or on Monday morning (12/19).

**Preview link:** http://preview-prod.vfs.va.gov/preview?nodeId=51915

Again, this page was created to meet the needs of the homepage team ("Why should I create an account?") and the chatbot team ("Which account should I create?"). 

Please feel free to ask us any questions! Additionally, if you all need us to publish any of the Q&As as single Q&As so that you all can link directly to a specific one, just let us know!

Thank you!

@DanielleThierryUSDSVA FYSA

**Comment by RLHecht** [comment]
Closing out this ticket as we completed this work. Please reopen if needed.
