### ISSUE TITLE
Central mail: Determine how much time using the Central Mail API saves Veterans

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/va.gov-team#49585]
We need to know definitively if using the [Central Mail API](https://depo-platform-documentation.scrollhelp.site/developer-docs/central-mail-api) will save Veterans significant burden time. To answer that we need to know exactly where the Central Mail API injects a piece of mail into the system. This could be:

* At any of many VA mail facilities where it then travels to another location to be processed thereby still taking 2.5 days to make the journey (could potentially be shorter by some inter-agency mail system)
* At a central facility where it is immediately processed same day or close to and thus does not take 2.5 days

If we believe that filling out a form online versus on paper is equal, then potential saved time would be printing and mailing the printed form. [USPS puts that delivery time average at 2.5 days](https://about.usps.com/newsroom/national-releases/2022/0811-usps-average-mail-delivery-time-consistent-at-2-5-days.htm). However, if the Central Mail API creates a piece of mail at some random place that still has to travel by mail to central processing then that savings goes away.

If we determine that no time is saved by using the Central Mail API versus a Veteran filling out the form by hand then one pivot we could make would be from burden hours to mean time to a confirmation of receipt. Given that we would use VA Notify we believe we can shorten the time it takes for the VA to acknowledge to the Veteran that we have received their form submission. That is something we could measure on average because, to my knowledge, it rarely happens today (some forms do elicit a letter response from VA, which we could measure, but many do not).

**Comment by tbaker1026** [comment]
- [ ] Set up a meeting with Melissa in Central Mail

**Comment by PSIEBENLIST** [comment]
all forms submitted to central mail - regardless of modality - go through an intake vendor before being transferred to centralized mail portal for processing. The intake vendor scans and indexes the documents within 6 hours of being received. 

**The following claim was validated by central mail team**:  the time between a form being submitted digitally and being forwarded to centralized mail processing is about 6 hours, whereas the time between a form being submitted physically and being forwarded to centralized mail processing is about 2 days and 6 hours (assuming it takes 2 days to reach the intake vendor by USPS) See attached image for specific steps in each journey. .
