### ISSUE TITLE
Adding Marilyn Lloyd, Tim Brown, Anami Chan, Jason Wolfe, Nic Cheneweth, Punit Lad to DSVA Slack

### ISSUE THREAD

**Issue by punitladtw** [department-of-veterans-affairs/va.gov-team#49601]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)
<describe the request>

Please add the following emails to DSVA slack: 
- Tim Brown: timothy.brown@thoughtworks.com 
- Marilyn Lloyd: mllloyd@thoughtworks.com 
- Anami Chan: anami.chan@thoughtworks.com 
- Punit Lad: plad@thoughtworks.com
- Jason Wolfe: jason.wolfe@thoughtworks.com
- Nic Cheneweth: nchenewe@thoughtworks.com 

Are you requesting to add an individual as a:

- Full member

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.
All members of this team are working within the VES portfolio. 

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add [_insert email_] as a single-channel guest to [_channel name_].
- Please add [_insert email_] as a multi-channel guest to these channels: [_channel names_].
- Please add [_insert email_] as a full member.
- Please change the status of [_slack username_] from [_current status_] to [_desired status_]

**Comment by eunicegar** [comment]
done
