### ISSUE TITLE
Filed issue with Central Mail

### ISSUE THREAD

**Issue by tbaker1026** [department-of-veterans-affairs/va.gov-team#49607]
From Matthew:
I filed this issue to investigate [Central](https://github.com/department-of-veterans-affairs/va.gov-team/issues/49585) Mail API in greater detail which contains an alternative way we might measure an experience improvement for Veterans.

**Comment by PSIEBENLIST** [comment]
![image.png](https://images.zenhubusercontent.com/62fa74837aa2ac25d23d39e0/bb3b36cf-34d8-4b6f-a429-d8dfa41790d6)
