### ISSUE TITLE
[high priority bug] Hearing aid form | Routing issue and MDOT service timeout

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#49600]
## What happened? 
- A page not found is shown when /introduction is included in the URL (not sure how to fix this routing issue)
- The save-in-progress uses mdot as the form ID, and is returning a 400 error
- If I reload the page a second time, the save-in-progress returns a token expired message

<details open>
<summary>Screen recording</summary>
<br>

https://user-images.githubusercontent.com/90406121/201701924-92084608-ff08-4a28-a30c-dcfd2a70e0f1.mov

</details>

Specs: (see recording)
- Device: (Macbook)
- Browser: (Chrome)
- Test User _(if applicable)_:

## Steps to Reproduce
- URL:
- Test User _(if applicable)_:

## Desired behavior
_When a user attempts to complete the form, the user experience does not break due to routing or timeouts._

## Acceptance Criteria
- [ ] User can submit the form without interruptions

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by saderagsdale** [comment]
@kylesoskin @Mottie Let me know the estimate to fix this after we identify the root cause.  🙏🏽

**Comment by saderagsdale** [comment]
Timebox through EoD today @kylesoskin.

**Comment by kylesoskin** [comment]
This is failing in prod because the users SSN is nil. However, I am not able to recreate this in local development (logged in with a staging user)


![Screen Shot 2022-11-16 at 3.05.53 PM.png](https://images.zenhubusercontent.com/62067253500f33af56810776/e13a3442-b234-4391-8acc-2464653b860e)![Screen Shot 2022-11-16 at 3.06.02 PM.png](https://images.zenhubusercontent.com/62067253500f33af56810776/d709c1b9-efc7-42f6-b27e-3042ca6e46e5)

**Comment by kylesoskin** [comment]
Moved to validate until we can "validate" that this is as far as we can take this at the moment with our current workload, and can offload to someone else.

**Comment by kylesoskin** [comment]
@saderagsdale can we close this or move it into the backlog? 
Once we determined this isn't as wide spread of an issue (as the MDOT people said orders from va.gov are still actively rolling in) I think we agreed to put this on pause.

**Comment by saderagsdale** [comment]
@kylesoskin Yes.

Closing since DLC confirmed that the service is up and running.
