### ISSUE TITLE
[FE] Display Online Check-in Not Available Message

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#49608]
## Blocking PCI/API work
[Ticket](https://github.com/department-of-veterans-affairs/chip/issues/1396)

## User Story
As a Veteran, when I see my appointments for today displayed in eCheck-in, if any are not eligible for check-in via the application, I would like to see a message telling me I can't check-in for the appointment so that I am not confused why check-in doesn't work for those appointments.

## Tasks
- [ ] [FE] Confirm the message displays after the PCI/API ticket is deployed

**Comment by sarahknoppA6** [comment]
this has not been addressed by API team yet
