### ISSUE TITLE
VEText | User Issue Escalation: ommunity Care GEC * clinics are sending out appointment reminders under COM CARE-OTHER despite being configured not to

### ISSUE THREAD

**Issue by chancetheoriginal** [department-of-veterans-affairs/va.gov-team#49629]
Station: 689
Issue Type: Functionality issue
Short Description: Community Care GEC * clinics are sending out appointment reminders under COM CARE-OTHER despite being configured not to
Description: Station 689 has a series of Community Care GEC * clinics configured to block appointment slots for at-home nursing services, but are not configured to send appointment reminders. These individual clinics are listed on the Excluded tab. Despite this, VEText is still pulling these clinics and sending appointment reminders for them under COM CARE-OTHER. COM CARE-OTHER is also Excluded. 

There are no other apparent stop or credit stop code configs that would be causing this functionality.

**Comment by shanemelliott** [comment]
Need patient Example.

**Comment by jwowk** [comment]
@chancetheoriginal @manalo-soco Consult titles must match clinic names. Need to verify with the sites to confirm.

**Comment by chancetheoriginal** [comment]
Directed affected sites to delete/re-add GEC clinics and to ensure their naming conventions match consult titles _**exactly**_, provided supporting documentation. 

Closing.
