### ISSUE TITLE
Redirect Request

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#49620]
### Instructions
- Requests must be submitted **AT LEAST** 2 weeks in advance.  Some requests take a significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.
- It is your responsibility to notify VA stakeholders as appropriate.  

Related ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/49612
Draft `devops` PR with redirects: https://github.com/department-of-veterans-affairs/devops/pull/12215

### Type of request
- [x] We are retiring or taking down a page and need to redirect the URL (complete redirect section)
- [ ] We are changing the URL of an existing page (complete redirect section)
- [ ] We need a custom vanity URL (complete vanity URL section)

### Implementation date
When does this request need to be live: **Sooner the better

### Redirects 
Current URL  |  Redirect Destination or New URL
---  |  ---
^/health-care/covid-19-vaccine/stay-informed/?$ | /health-care/covid-19-vaccine/
^/health-care/covid-19-vaccine/sign-up?$ | /health-care/covid-19-vaccine/

### Process, Roles and Responsibilities
- [x] Requesting team: Above information is provided
- [ ] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [ ] IA: Request is vetted and documented and implementation plan is clear 
- [ ] IA: Request is assigned to appropriate team for implementation 
- [ ] Implementation team: Work is complete
- [ ] Implementation team: Validated in production
- [ ] Requesting team: Validates everything is correct in production and closes ticket

**Comment by jilladams** [comment]
Related thread re: priority: https://dsva.slack.com/archives/C52CL1PKQ/p1668443871060109

@heyjoni @RLHecht is this ticket ready for Public Websites to implement?

**Comment by jilladams** [comment]
(May not be anything for us to do here but get Patrick's draft PR over the line ^)

**Comment by batemapf** [comment]
thanks @jilladams! i think if everything is good from an IA perspective, i would just need someone from public websites to review the PR. will flip it from draft to a "real" PR now.

**Comment by heyjoni** [comment]
Looks good to me from an IA perspective.
