### ISSUE TITLE
Contact Center Review for [Auth Experience My VA - Payment info v2]

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#49621]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
"Payment info v2" - we are releasing an updated version that creates two distinct sections on My VA for "Outstanding Debts" and "Benefit Payments." The first iteration of this feature had these sections combined as "Benefit Payments & Debts". More documentation [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/payment-history#v2-updating-payments-and-debts-to-address-usability-issues-may-2022---current-1).

### Launch Date
Phased launch ideally beginning (as early as) the week of 11/28

### Version Number
Version 5

### Product Guide
[My.VA.2.0.Product.Guide.Version.5.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/10006566/My.VA.2.0.Product.Guide.Version.5.docx)

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
Hi @ajakabcin. The additions look good. I added links to the diagrams in the new sections, but no other major changes. I will send to VEO for review.

**Comment by ajakabcin** [comment]
Thank you @starlow00 - can you send back the version with the updated links you referenced? We like to keep a copy of the final version for our records :)

**Comment by starlow00** [comment]
Hi @ajakabcin. I'll post as soon as it passes VEO review, so hopefully this week. Had a technical issue that prevented me from uploading it to their Sharepoint last week.

**Comment by ajakabcin** [comment]
hey @starlow00! sorry to bug you - any word from VEO?

**Comment by starlow00** [comment]
No changes from VEO. Copy attached. (@ajakabcin)
[MyVA_2_0_v5.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/10128111/MyVA_2_0_v5.docx)
