### ISSUE TITLE
Ingress traffic incident - Jan 17, 2020

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#4962]
## Problem description

This is a ticket to track work related to incident where all ingress traffic was not making it to api.va.gov and partially to www.va.gov on Jan 17, 2020.

Raised with GW Ops as INC9156670

Conversation / alarms started here: https://dsva.slack.com/archives/C30LCU8S3/p1579241593008900
Some additional distilling of info here: https://dsva.slack.com/archives/C0S6H6BQU/p1579251491003800

## AC
- [ ] Update the Error page in the F5s
- [ ] Sync up health check for www.va.gov and api.va.gov

**Comment by wyattwalter** [comment]
Even though these sites serve out the same gateway, there seems to be some discrepancy between the health checking and/or DNS configuration on api.va.gov vs www.va.gov

![Screen Shot 2020-01-17 at 2.50.03 PM.png](https://images.zenhubusercontent.com/59ca6a96b0222d5de4792f24/2b25d327-57c2-47f6-84b0-906b6f5fbe9c)

**Comment by ricetj** [comment]
@wyattwalter is this ticket for a PM as well or can this be closed?

**Comment by wyattwalter** [comment]
Hey @jbritt1 I put you on this as current on-call. I just sent an email again to prod on this two issues to see if what we want to do is possible and get an assessment of the situation. Can you follow-up whether or not they respond?

**Comment by jbritt1** [comment]
Not sure what you are asking of me on this

**Comment by jbritt1** [comment]
Did you just want me to be on the lookout for a reply or is this actionable or what?

**Comment by ricetj** [comment]
need to move to the other ticket and close this

**Comment by ricetj** [comment]
Work in another ticket
