### ISSUE TITLE
VEText | User Issue Escalation: Stop code 323 not sending grouped appointment reminders as configured

### ISSUE THREAD

**Issue by chancetheoriginal** [department-of-veterans-affairs/va.gov-team#49626]
Station: 656
Issue Type: Functionality issue
Short Description: Stop code 323/Primary Care 
Description: Station 656 reporting issues with stop code 323/Primary Care. Three clinics are grouped under STC PSM GROUP, but only Lab reminders are being sent
- Clinics: 
  - STC LAB DO NOT EAT(WATER-OKAY) <-- sending
  - STC P NURSING/INTAKE <-- not sending
  - STC P MD PACT 4 <-- not sending

None are on Excluded list by way of name or stop code, no credit stops applied.

**Comment by lindsay-insco** [comment]
Fixed
