### ISSUE TITLE
Reach out to other UX people who have digitized forms to see if there are any standards for naming etc. 

### ISSUE THREAD

**Issue by tbaker1026** [department-of-veterans-affairs/va.gov-team#49637]

**Comment by jeana-adhoc** [comment]
I met with two UX designers today to talk with them about digitizing forms. [Here are the notes from that meeting.](https://docs.google.com/document/d/16lSZBt9oPfBlljoBCkeHcQOaME8eB2YCb0OoIY3ApLE/edit?usp=sharing)

More questions have come to mind, and I'll be following up with them again soon.
