### ISSUE TITLE
AVS | User Issue Escalation: Changing 'Other Information' font size removes entire section

### ISSUE THREAD

**Issue by chancetheoriginal** [department-of-veterans-affairs/va.gov-team#49631]
Station: 459
Issue Type: Functionality issue
Short Description: Changing 'Other Information' font size removes entire section
Description: AVS: When changing the font size of the 'Other Information' section, the entire section is removed and not printed to the physical report, despite still being visible in the preview.

**Comment by lindsay-insco** [comment]
Fixed
