### ISSUE TITLE
Review OMB forms to document some of the changes requested

### ISSUE THREAD

**Issue by tbaker1026** [department-of-veterans-affairs/va.gov-team#49638]
### **Description**

- The goal is to determine the number of times a form has changed or new ones created to determine if we actually need a UI for Business Units to make their own changes to forms, without development work.  

### **Definition of Done**
- [x] Run a Report in OMB with Date parameter of 1/1/2018 - Present
- [x] Analyze the data
- [x] Present Findings
### **Supporting Documentation**
 [[Updated Documentation](https://docs.google.com/presentation/d/1r-XfPB1aqcz7TlcxLGJrxAFBgb0OiaQO29hXuBJNOIE/edit#slide=id.g1e78873df30_0_1)]

**Comment by humancompanion-usds** [comment]
I think doing a sample of 10 was captured here: https://docs.google.com/document/d/1RCyDHpettAodgbBP6QGcWqEn4oS4VzApXkWn8bON_xA/edit#heading=h.lregotxmkcna

Unfortunately, they didn't really answer the question of what types of changes are made and how often. We determined through other OMB data that we make on average ~10 changes per month. We need to characterize those changes some how.

**Comment by tbaker1026** [comment]
[Documented](https://docs.google.com/document/d/1RCyDHpettAodgbBP6QGcWqEn4oS4VzApXkWn8bON_xA/edit#heading=h.lregotxmkcna) Changes for the 10 sample forms

**Comment by tbaker1026** [comment]
@humancompanion-usds can you remind me again on how we found out there are around 10 changes per month?  I am going through the OMB data and looking at the audit to find forms that have changed recently.  Thank you

**Comment by tbaker1026** [comment]
[OMB Definition Guide](https://www.opm.gov/forms/pdfimage/omb83ins.pdf)

**Comment by tbaker1026** [comment]
@humancompanion-usds [Updated Documentation](https://docs.google.com/document/d/1MuEXTU-wz__gujhqfzs3io0HBC_yibfk0PcYZLHRyfg/edit#) on Auditing of Forms via OMB

Summary of Findings:
Report Ran Query in OMB:
01/01/2019 - 01/01/2023
Request Type:  Approved with Changes
Details of Report

Summary of Changes
76 Reports were returned for date range
48 of them had some sort of change (not all form updates related, see breakdown below)
13 were  requests for a new OMB Control Number
15 were Extensions of form without change

**Comment by tbaker1026** [comment]
Reached out to Find a Form team to see if they can run a report on form additions or updates to forms.  We will also validate these findings with form stakeholders and PRA owner

**Comment by humancompanion-usds** [comment]
Let's also be sure to ask Lauren on Thursday who our PRA officer is and if we can get a warm intro.

**Comment by tbaker1026** [comment]
Created a new issue to verify the findings - #51914

**Comment by tbaker1026** [comment]
@humancompanion-usds - I went through the new PRA site recommended by Rachel and audited all of the forms that had OMB #, the results are in the [attached presentation](https://docs.google.com/presentation/d/1r-XfPB1aqcz7TlcxLGJrxAFBgb0OiaQO29hXuBJNOIE/edit#slide=id.g1e78873df30_0_1). We can review more on Thursday.

**Comment by tbaker1026** [comment]
Also made a new linked table in [airtable](https://airtable.com/app8r8N52jBfzOkMb/tblT4wZ01rYwww7pH/viwZH4lFdWvpMLRnP?blocks=bipm6qt2c1E0tNiWd) with the PRA data findings
