### ISSUE TITLE
VEText | User Issue Escalation: User not able to select assigned (integrated sites) divisions from initial division selector prompt

### ISSUE THREAD

**Issue by chancetheoriginal** [department-of-veterans-affairs/va.gov-team#49633]
Station: Multiple
Issue Type: Functionality issue
Short Description: User not able to select assigned (integrated sites) divisions from initial division selector prompt
Description: User has VistA profiles at various integrated ###X# sites, yet they are not able to sign into them through the initial division selector prompt. Only the primary ### divisions display for selection. Possible SSOi functionality overlap and/or change. 
![MicrosoftTeams-image.png](https://images.zenhubusercontent.com/61547adde730b5670c3cd747/178c3f93-d122-4d9a-b7e9-701e3c8030a7)

**Comment by jwowk** [comment]
Workaround completed
