### ISSUE TITLE
AVS | User Issue Escalation: Discontinued meds are sometimes being registered as Renewed

### ISSUE THREAD

**Issue by chancetheoriginal** [department-of-veterans-affairs/va.gov-team#49632]
Station: 570
Issue Type: Functionality issue
Short Description: Discontinued meds are sometimes being registered as Renewed and causing confusion
Description: Meds that are being flagged as Discontinued are intermittently being set to Renewed. From user: 

We are having a few issues with AVS- for instance when we DC a med and it does populate under the new orders section but the summary of changes to meds it doesn’t show anything and states no change was made.

For one provider under the new orders section it shows “renewel” when generated for a DC med but when I tested it showed DC:

My test:
![sc1.png](https://images.zenhubusercontent.com/61547adde730b5670c3cd747/f9b788f7-ab97-4707-ba75-b7844b88d490)

Providers version: 
![sc2.png](https://images.zenhubusercontent.com/61547adde730b5670c3cd747/f581b6a8-366b-4099-b159-ef0f605c3a89)

Doesn’t show this in summary of changes to meds: Both
![sc3.png](https://images.zenhubusercontent.com/61547adde730b5670c3cd747/435f5083-c05b-4f74-b6ad-9741b7520975)

**Comment by lindsay-insco** [comment]
Resolved by Rob
