### ISSUE TITLE
VEText | User Issue Escalation: OSM overbooked appointment slot despite being configured not to

### ISSUE THREAD

**Issue by chancetheoriginal** [department-of-veterans-affairs/va.gov-team#49635]
Station: 646
Issue Type: Functionality issue
Short Description: OSM overbooked appointment slot despite being configured not to
Description: OSM overbooked an appointment into an existing slot that was already filled by a previously scheduled appointment. The existing appointment was not a reschedule nor up for reschedule. OSM inserted the second appointment as an overbook, despite being configured not to. ServiceNow ticket: INC23367495

**Comment by jwowk** [comment]
@chancetheoriginal follow up with site to see if issue is still ocurring.
