### ISSUE TITLE
Request design review for Medical Device (Ordering) Tool

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#4963]
## Product Name

Medical Device Tool

## Checkpoint Stage

[x] **Design Intent** (for early discussions about needs, priorities, concepts, research planning, and direction)

[ ] **Pre-usability testing Review** (for prototype and testing validation of best practices, alignment with va design system, and inclusive research best practices)

[ ] **Design Review** (for design work validation of best practices and alignment with the va design system)

### Where in the process is this? 

[x] Initial concept

[ ] Initial mockup

[ ] Final mockup

## Design links or mockups

Current write up: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/design/thumbnail-mapping/README.md

## Point of contact(s)

Rebecca Walsh
Riley Orr
Nicolaus Wygonik

## Preferred times

The week of 1/20

**Comment by rebeccawalsh** [comment]
@rileyorr Here is the issue for our design intent check in with VSP

**Comment by sshein** [comment]
Hi all! just leaving a couple of notes here from the meeting:

**Comment by sshein** [comment]
Hi all! just leaving a couple of notes here from the meeting-
- I'm wondering about the broader topic of where "ordering status" might live on logged in VA.gov, and if it makes sense to have it not directly tied to medical devices.  I'm going to take a todo to schedule a meeting with Samara/Tressa/Jim and Becca/Riley to talk about this topic. @emilywaggoner @KevinMHoffmanUSDS I'll add you as optional.  
- I liked Kevin's idea of confirming email address at the end of the flow, with context.  Like "we will send updates to your order status at this email address. If this isn't the correct address, change it here"

**Comment by jenstrickland** [comment]
_VSA Accessibility notes_

- have devs connect with Jennifer before building, in order to get the semantics right (especially for deafblind use case)

- confirmation screen - possibility of print styles? happy to help with this

- there is a known bug in the subway numbers color contrast

- great job of starting with mobile, and extending learning to the desktop view!  Thank you!

- if the info in the accordion items is short, consider not using the accordion.

- an anchor link can't open an accordion

- On this page component may be helpful vs the accordions for tracking clicks. Example: https://www.va.gov/pittsburgh-health-care/health-services/

**Comment by 1Copenut** [comment]
_VSP Accessibility Notes_

* Focus management for the inline edits will be important
  * When users press Edit, do they know what they're editing
  * Where does focus go when users press Edit? Is there a heading to hook into?
  * Where does focus go when users press Cancel? Probably back to Edit at that point.
  * Is there a confirmation message if the edit was successful? Does that receive focus?
* Print CSS for the order confirmation page
  * [CSS Design: Going to Print](https://alistapart.com/article/goingtoprint/)
  * [Print It Your Way](https://alistapart.com/article/printyourway/)

**Comment by wygonikGCIO** [comment]
Shawna can I also be included in the meeting. 

> schedule a meeting with Samara/Tressa/Jim and Becca/Riley to talk about this topic. @emilywaggoner @KevinMHoffmanUSDS I'll add you as optional.
