### ISSUE TITLE
Tree test: Launch test and monitor participation

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#49641]
Launching and running the tree test

- [ ] Optimal tests are both published and live
- [ ] Participant information is sent to Perigean daily
- [ ] Monitor participation to get to goal numbers of no less than 40 participants per test
- [ ] Work with Perigean to send reminders as necessary
- [ ] Monitor results for good responses
- [ ] Close test and notify Perigean

**Comment by rbsingleton** [comment]
Understanding this ticket as representing the scope of work related to research prep: 
- Creating research and recruitment plan
- Submitting tickets to research repo
- Navigating feedback process & coordination w/ Perigean

**Comment by mnorthuis** [comment]
@rbsingleton @Jenny-yw  moved these tasks over to #49639 for completing the research and recruiting plan.  This issue will be used while the test is running.

**Comment by mnorthuis** [comment]
Veteran test closed 1/9, caregiver test closed 1/17
