### ISSUE TITLE
Add dismissable functionality on global emergency banners?

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#4964]
**User story:** 
As a Veteran, I want to be able to dismiss and not see a natural disaster or other emergency message, after I've seen it. 

**Example screenshot:** 
![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/419f2ca1-49be-4bba-8b97-507f91de467d)

**Request:** 
Discuss as a team whether this is a good idea. Are emergency messages so important that it should always be displayed until the emergency is over or is it annoying to users to whom the message doesn't apply and may want the option to not see it anymore? 

Example: in the screenshot, the emergency message is about an earthquake effecting Puerto Rico VA health facilities. But I am not in PR and don't need to see this message for days on end. 

This is not urgent. Adding to icebox for now. FYSA @Karak888

**Comment by AkucherGCIO** [comment]
2020-26-02 PW Planning
1. Homepage banner - Dismissal functionality can be added by PW team.
2. Banners inside drupal - Functionality needs to be revisited to determine if it should be Drupal fix or FE fix.

@AkucherGCIO -  Implementation ticket needs to be created.  Dismissed homepage banner should persist after refresh.

**Comment by AkucherGCIO** [comment]
03/06/20 PW Standup
@ncksllvn - Might be a good demo ticket.

**Comment by AkucherGCIO** [comment]
@ncksllvn - There is another ticket created in the Epic to address an issue that came up in the demo.

 #6734 Update the uniqueID from the dismissed banners to be more specific

**Comment by ncksllvn** [comment]
Closing - we added a feature flag for this in https://github.com/department-of-veterans-affairs/va.gov-team/issues/6824
