### ISSUE TITLE
[Discovery] Understand how best to present SLO performance data in a stakeholder-friendly fashion

### ISSUE THREAD

**Issue by kfrz** [department-of-veterans-affairs/va.gov-team#4965]
## Background

We need to define how the final SLO report will be presented before we can create a report that can be consumed by those who are interested. 

## Acceptance Criteria

- [ ] Discuss/interview stakeholders and eventual users of tool for their desires
- [ ] Mockup based on data
- [ ] Analyze results and choose a path forward

**Comment by alexpappasoddball** [comment]
Closing this issue for now while we wait to see what tools become available that will be able to display this data for us.  This decision isn't going to be up to us, instead we will be responsible for the definition and enforcement aspect and not the display of this data in the long term.
