### ISSUE TITLE
Audit legacy Vet Center content to prepare for migration

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#49672]
## Story
As a VA.gov or Vet Center team member, I need to understand the legacy content to be able to discuss and make informed decisions about content migration.

## What's needed

- [x] Create content audit template for Vet Center site (Michelle)
- [x] Pull Google Analytics report for a year of data on Vet Center site (Michelle)
- [ ] Pull SEMRush report for Vet Center site 
- [x] Add page titles and URLs to audit (VA.gov content and IA team)
- [ ] Fill in information for orange columns in audit 
- [ ] Fill in information for blue columns in audit (VA.gov content and IA team)
- [ ] Review audit (Danielle)

## Files for reference

- [x] [Full shared folder for Vet Center content migration work](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/49680)
- [x] [WIP Vet Center content audit](https://dvagov-my.sharepoint.com/:x:/r/personal/suzanne_middaugh_va_gov/Documents/Shared%20folder%20for%20Vet%20Center%20content%20migration/Content%20audit/Vet%20Center%20content%20audit%20(WIP).xlsx?d=w5e3307124fa0436ea1b259b8b18df776&csf=1&web=1&e=4HMUOE)
- [x] [Vet Center Google Analytics report](https://dvagov-my.sharepoint.com/:x:/r/personal/suzanne_middaugh_va_gov/Documents/Shared%20folder%20for%20Vet%20Center%20content%20migration/Data%20and%20analytics/vet_center_4.22.21-04.22.22.xlsx?d=w603587384d9343d8ac38e359740e6f83&csf=1&web=1&e=QeYdXy)
- [ ] Vet Center SEMRush report on organic search

**Comment by jilladams** [comment]
Michelle working on this anew in a different context. Closing. https://github.com/department-of-veterans-affairs/va.gov-team/issues/59933
