### ISSUE TITLE
Someone audit analytics and insights section

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#49675]
Tasks:

- [x] Review each page under this section: https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/

- [x] Any pages with links to unpublished versions of the website (Confluence URLs, instead of the scroll viewport URL will be documented in the spreadsheet below:

Google spreadsheet: https://docs.google.com/spreadsheets/d/1h3Etep81sRK4_C88SOPZ2e0IeTFHE3KQp9qJJV53kMk/edit#gid=252229441

Instructions:

- Pages without any Confluence links should be documented in the "Analytics and Insights" tab
- Pages with Confluence links should be documented in the "docs that have confluence links" tab

**Comment by taylojill** [comment]
11/15/22 - Completed.
