### ISSUE TITLE
Attempt to conditionally support a nested form (10-7959c) for the applicants

### ISSUE THREAD

**Issue by ndsprinkle** [department-of-veterans-affairs/va.gov-team#49697]
### Description

In the 10-10d paper form, when specific checkboxes relating to healthcare are checked, a separate form (10-7959c) is required to be filled out. We should attempt to implement this nested form in our form by using conditional pages. Form 526 has an example of how to do this.

### Definition of done

- [ ] The 10-7959c form can be conditionally filled out inside the 10-10d form
- [ ] OR it is documented why this isn't possible

**Comment by tbaker1026** [comment]
Moving to backlog since we are not starting with 10-10d, but will look at it again later to see how we can handle nested forms

**Comment by tbaker1026** [comment]
Closing issue, will tackle this when we come to a form that has a nested form.
