### ISSUE TITLE
[QA] Verify Early Guardrail has been Changed from 30 to 45 Minutes

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#49691]
## Tasks
    - Ensure that pre-checkin messages are shown at the correct time after PCI/API work is complete 
    - Ensure that eCheck-in check-in times honor the new early guardrail

**Comment by brianseek** [comment]
change will be live 11/29 -> https://dsva.slack.com/archives/C022AC2STBM/p1667495040699149

**Comment by brianseek** [comment]
This was validated in stage today. @loripusey do you want to leave this open until it is validated in prod after the 29th, or is this good to close?

**Comment by loripusey** [comment]
I think it's good to close
