### ISSUE TITLE
Content support for Secure Messaging FAQs

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#49690]
## Issue Description

The MyHealth team opened an intake request for content support for their secure messaging app in ticket #42428. 

We'll use this ticket to communicate with the product team about the FAQs section and to provide final content. Sitewide Content and IA is working internally in a separate ticket.

**Comment by laurwill** [comment]
Hi @alexiawunder ,
@aliyahblackmore and I have been working on the FAQ content, and we have some questions we're hoping you can help with. 

First a more general one: What are the key changes happening from the old MHV secure messaging to the new tool that we want to make sure people understand? 

And here are a few more specific Qs we had:
- Will this FAQ page be visible to people who aren’t already using/set up to use SM, or only to people who are already in and using the tool?
- Can Veterans still do all these things in the new tool: Get test results, request prescription refills, schedule appointments, get links from providers to the Veterans Health Information Library
- What specifics should we include about file attachments? Are the file types, size limits, or instructions changing in the new tool?
- MHV FAQ talks about messages going to the general health care team, and then getting forwarded to the correct provider. Can Veterans send messages to specific providers, or only to a general inbox?
- How common is it for Veterans to get blocked from using SM? Is there any key guidance people should know about how to avoid being blocked? 
- The blocking questions on MHV also talk about messages to and from “Triage groups.” Do we need to include information about Triage groups in the FAQ? 

Thank you! And let me know if you want to chat about any of these or if we should direct any of these Qs elsewhere.

**Comment by laurwill** [comment]
Thanks so much @alexiawunder ! I think between these answers and the slack thread, we should be able to draft the FAQs for phase 0 — but we'll let you know if we have more questions.

**Comment by aliyahblackmore** [comment]
Just updating this thread:  @laurwill I passed a doc to you with the FAQs for phase 0 on Slack!

**Comment by laurwill** [comment]
Hi @alexiawunder , 
We have a few more specific questions for you about the FAQs content — could you take a look at the comments in this document and let us know what you think? Then we can update as needed before we send this through copyedit. 
[SM_FAQs_Phase 0.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/10240809/SM_FAQs_Phase.0.docx)

We're also planning to meet with the writers for MHV content early next week, to get their input on our approach here. 

(And also a general note here that we've kept "secure messaging" in the content for now — we know that the designs use "messages" to refer to the tool throughout, but we're waiting to make that change in the content until we're sure all the MHV partners are aware of and on board with that change.)

**Comment by alexiawunder** [comment]
Hi @laurwill! Here is the most current link we have for the [authenticated FAQ page](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/8yJWQDY#Version).

**Comment by alexiawunder** [comment]
Hello again @laurwill and @aliyahblackmore, I forwarded your questions to Patty Henry, Bhanu Goparaju, Thomas Rollins and here is the document with their responses along with other suggested changes. 
[SM_FAQs_Phase.0-PH Review_12_20.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/10282896/SM_FAQs_Phase.0-PH.Review_12_20.docx)

**Comment by laurwill** [comment]
Hi @alexiawunder ,

I realized we don't have a ticket yet for the landing page content, and there's lots of overlap with the FAQs in this ticket. So I'm posting our first working draft here. First some notes:
- This is a draft! I left some comments with questions in the document, and I expect we'll need to make more content changes to this page as it evolves. But we wanted to give you some working content since we'll be OOO next week. 
- We're meeting with MHV writers the first week of January. We'll want to get their input on the FAQs, and we still need to reconcile the feedback on the draft you posted back above. 
- And since the landing page involves change management messaging, we'll need to loop in the communication plan group as well. So all that to say, this is not final! But it's a start.

[SM auth landing page content (phase 0).docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/10297648/SM.auth.landing.page.content.phase.0.docx)

We'll check in and update as needed in January.

@DanielleThierryUSDSVA for awareness.

**Comment by laurwill** [comment]
Hi @alexiawunder ,
The changes from Patty, Bhanu, and Thomas on the FAQ page change all "messages" back to "secure messaging." Our content team wasn't involved in early conversations about dropping "secure. And my understanding after talking with Danielle is that, as far as we know, there hasn't been an explicit conversation or decision with all MHV partners about this naming shift. 

So I wanted to ask if you've had direct conversations with Patty, Bhanu, or other MHV partners about this, or if this decision is documented anywhere that you know of? Just want to make sure everyone is on the same page about what we're calling the tool. Thank you!

**Comment by alexiawunder** [comment]
Hi @laurwill, I don't have an answer to this. Let's connect on Slack to coordinate a discussion on this topic.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @laurwill. I took a final look at this after our collab session on it and left just a few edits and comments. Thanks to you and everyone for all you work on this!

[Here's the shared doc link ](https://dvagov-my.sharepoint.com/:w:/g/personal/danielle_thierry_va_gov/EbMvEJh0ywRKn_HLIrl8cHMBsebYFu1O1aU_5XkS54opzA?e=FVS0ZD)

**Comment by RLHecht** [comment]
Closing this ticket. If the team needs more support we can open a new ticket to track the work.
