### ISSUE TITLE
Implement SLO report generation logic

### ISSUE THREAD

**Issue by kfrz** [department-of-veterans-affairs/va.gov-team#4969]
## User Story or Problem Statement
As a user who is interested in SLOs, I need a convenient report that summarizes performance from an SLO perspective.

Problem description. How might we update the reported statistics on a continual basis?

## Goal
An SLO report is accessible and contains most recent information on product health

## Objectives or Key Results this is meant to further
O2: Qualitative/Quantitative User Data
O4: All of the Platform's KPIs are easily measured and shared openly.

## Acceptance Criteria
- [ ] Report output is defined
- [ ] Calculation logic is written and tested
- [ ] Reporting process is in place
- [ ] Report is properly generated

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by alexpappasoddball** [comment]
@kfrz I want to say that this is done and can now be closed.  Is that correct?
