### ISSUE TITLE
Figure out how to make the applicants array work on the review page

### ISSUE THREAD

**Issue by ndsprinkle** [department-of-veterans-affairs/va.gov-team#49695]
### Description

While we were able to successfully implement the array of applicant objects, it doesn't work properly on the review page. We need to address this as well as finalize the view component in the form.

### Definition of done

- [ ] The applicants array works properly on the review page
- [ ] The view component is adjusted to fit our needs

**Comment by jessecanderson** [comment]
Reviewing the code for the Review Page and this is a built in component found inside [the form-system src](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/forms-system/src/js/review/ReviewChapters.jsx) and one a custom component that we control. When the `review-and-submit` page is loaded, the chapters and the form data are passed into this component and each chapter is displayed as a "drop down" kind of menu/box. Clicking on the `+` button will expand the data found in that chapter and right now we are not seeing the `Applicant` information in our test 10-10D form. 

Inside the code each chapter is built out here: 

```
{chapters.map(chapter => (
            <ReviewCollapsibleChapter
              expandedPages={chapter.expandedPages}
              chapterFormConfig={chapter.formConfig}
              chapterKey={chapter.name}
              form={form}
              reviewErrors={formConfig?.reviewErrors}
              formContext={formContext}
              key={chapter.name}
              onEdit={this.handleEdit}
              open={chapter.open}
              pageKeys={chapter.pageKeys}
              pageList={pageList}
              setData={(...args) => this.handleSetData(...args)}
              setValid={setValid}
              hasUnviewedPages={chapter.hasUnviewedPages}
              toggleButtonClicked={() => this.handleToggleChapter(chapter)}
              uploadFile={this.props.uploadFile}
              viewedPages={viewedPages}
            />
          ))}
```

Inside the review page, it is expecting just the list of chapters and it runs a `map` on that to return a `ReviewCollapsibleChapter` component. When we get to this page, it looks like it would just be expecting a single chapter with multiple pages and not a list of other "users" to try and display them out under the review section. More research will be needed to see how best the review page could support a list of applicants with their own chapter and list of pages inside there.

**Comment by ndsprinkle** [comment]
Might make sense to pivot to this solution: https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-how-to-work-with-array-data-aka-l

After a conversation with Robin and consulting the Mock Form, it appears there is some issue with the "native" functionality of how the forms-library handles arrays of objects on the review page. Hopefully the above solution fixes this in addition to addressing the issue with having a super long page of fields.

**Comment by ndsprinkle** [comment]
I am going to close out this ticket despite not being satisfied with the review page. After using the "Array Data" method linked above, the form flow looks a lot better as we're able to split sections within each object in the array.

However, using this method still results in a malfunctioning review page for the array section. For this method, the first page does not show up. All the remaining pages using the array do show up. Just like before, you can use some hacky method with the `yesNo` widget or add another page in the front to get all the sections to appear, but this shouldn't be how this works. We'll need a follow up ticket to investigate in the (near) future to figure out what changed on the review page to break the functionality. Fortunately, I don't think any production forms are suffering from this issues because they all seem to have some other content before the array of objects that is tricking the review page into rendering everything. The mock form, however, does have this issues.

I don't really have anything to note about the array data implementation process. It worked pretty much exactly how it was shown in the documentation. The only difference I can think of is that I had to keep using the `viewField` widget despite the documentation not indicating that it needed to be there, but that was pretty quick to figure out when the errors started rolling in about a missing view state.

The MAJOR success that I had during this that I want to talk about is utilizing `lodash` functions. Leaning more into our `constants` approach (described in another ticket) I was able to lean into two `lodash` functions: `intersection` and `pick`. The code looks something like this for one of our pages in the applicants chapter (super simplified here):

```

import { applicantFields } from '../../definitions/constants';
import fullSchema from '../../10-10D-schema.json';
import { intersection, pick } from 'lodash';

...

const { required, properties } = fullSchema.properties.applicants.items;
const pageProperties = [
  applicantFields.fullName, 
  applicantFields.ssn, 
  applicantFields.gender,
  applicantFields.dob,
];

...

schema: {
  ...
  items: {
    type: 'object',
    required: intersection(required, pageProperties),
    properties: pick(properties, pageProperties),
  }
}
```

Again, super simplified here, but the main takeaway is that we can define the list of properties for the page in one location (pulled from the big pool in the `constants`) and then re-use this in a standardized way for the `schema`. This can probably be extended to the `uiSchema` as well, but it will take a more sophisticated function to do that and to make decisions about which UI elements to use. 

I'm definitely happy with the results here and I think utilizing `intersection` and `pick` will help us get closer to automating/standardizing the pages. My code could use some improvement and refining before the final product, but it's certainly a good start.
