### ISSUE TITLE
Add support for prefill

### ISSUE THREAD

**Issue by ndsprinkle** [department-of-veterans-affairs/va.gov-team#49700]
### Description

Because the forms library supports it, we should try to prefill sponsor data for the 10-10d form. This may required back end support, although I think the work required in vets-api is minor.

### Definition of done

- [x] The 10-10d form supports prefill data for the sponsor

**Comment by gmrabian** [comment]
update: Configured prefill in frontend and backend - need to resolve mappings

side note: may need to add schema to `vets-json-schema` repo to get tests to pass. 
ex: form 28-1900 has a pr for the json-schema repo before the api layer adds tests
https://github.com/department-of-veterans-affairs/vets-json-schema/commit/54420e9484592f6838bdf9a278bdd84502e8ef8a
https://github.com/department-of-veterans-affairs/vets-api/pull/5391/files
