### ISSUE TITLE
Wrap up the generated Introduction page

### ISSUE THREAD

**Issue by ndsprinkle** [department-of-veterans-affairs/va.gov-team#49701]
### Description

The Introduction page was generated when the form was created, but it is not finished. We should finish it. This may required assistance from UX.

### Definition of done

- [ ] The Introduction page is finished

**Comment by jeana-adhoc** [comment]
Documentation for the [form introduction page template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/content/form-introduction-page-template.md)

**Comment by jessecanderson** [comment]
I went through and played with the introduction page that was created and found that the `<va-process-list>` should contain all the steps that are needed to complete the form. This should include any information required, documentation required, or anything else the person preparing the form would need. Outside of this element, we can include other lists or HTML elements to add in things like definitions. I've also reviewed the documentation above and it contains a lot of good information on some other elements that are in the generated introduction page. The `Alert Boxes` stick out as a thing to use when drawing attention to information outside of the `<va-process-list>`. 

Changes are currently in the `vets-website` inside the branch labeled `form/1010d`. You can find the current intro page [on GitHub here.](https://github.com/department-of-veterans-affairs/vets-website/blob/form/1010d/src/applications/1010d/containers/IntroductionPage.jsx)
