### ISSUE TITLE
Wrap up the generated Confirmation page

### ISSUE THREAD

**Issue by ndsprinkle** [department-of-veterans-affairs/va.gov-team#49702]
### Description

The Confirmation page was generated when the form was created, but it is not finished. We should finish it. This may required assistance from UX.

### Definition of done

- [x] The Confirmation page is finished

**Comment by jeana-adhoc** [comment]
Documentation for the [forms confirmation page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/content/form-confirmation-page.md)

More documentation from the [design system for the confirmation page](https://design.va.gov/templates/forms/confirmation)
