### ISSUE TITLE
[SPIKE] [ANALYTICS] Investigate low pre-check-in completion percentages

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#49704]
## Background

Our pre-check-in completion percentage [tends to hover a bit above 35%](https://dsva.slack.com/archives/C02UP02HHGX/p1668474543479829?thread_ts=1668474531.635149&cid=C02UP02HHGX). We should investigate to determine why Veterans are not succeeding in completing pre-check-in and what's happening instead.

## ACs

- [ ] Investigate and report in Slack
- [ ] Create follow-on tickets for any issues surfaced

**Comment by acrollet** [comment]
Analysis is [here](https://dsva.slack.com/archives/C022AC2STBM/p1668804662541959). @loripusey @benbrasso-agile6 let me know if you have any questions or items you'd like to chase down further or if this this is good to close out. Thanks!

**Comment by loripusey** [comment]
I've created Epics or tickets from the 3 recommendations.
- [don’t send out pre-check-in links if all demographics are up to date for a patient within 7 days of the appointment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/49869)
- [consider prompting the user to close the browser tab once pre-check-in is complete](https://github.com/department-of-veterans-affairs/va.gov-team/issues/49871)
- [once the work to redirect from pre-check-in to check-in on the day of the appointment is complete, consider showing redirected users as a success path on the dashboard](https://github.com/department-of-veterans-affairs/va.gov-team/issues/49868)

**Comment by benbrasso-agile6** [comment]
This finding...

> The other large gap you may have noticed is between ~13k links clicked and 10k sessions - this is almost certainly due to large numbers of repeat visitors, whether due to re-opening the browser with a stale session, or clicking on the same link again. We do see [2650 sessions landing on the no-token error page](https://vagov.ddog-gov.com/rum/explorer?query=%40type%3Aview%20%40application.id%3Af61cc984-0ba6-4502-b4d0-fcae00cb8422%20%40view.url%3A%22https%3A%2F%2Fwww.va.gov%2Fhealth-care%2Fappointment-pre-check-in%2Ferror%3Ferror%3Dno-token%22&agg_m=%40session.id&agg_q=%40session.id&agg_t=cardinality&cols=&funnel=%5B%22%40view.name%3A%2Fhealth-care%2Fappointment-pre-check-in%2Fverify%22%2C%22%40view.name%3A%2Fhealth-care%2Fappointment-pre-check-in%2Fcomplete%22%5D&sort_m=&sort_t=&top_n=10&top_o=top&viz=toplist&x_missing=true&from_ts=1668402000000&to_ts=1668488400000&live=false), which generally will happen when someone visits a pre-check-in page with no current session.

... is an indicator that Veterans expect to begin the check in process via text, which further validates [sending a text message to Veterans before each appointment to start the eCheck-in process](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/44395).
