### ISSUE TITLE
Google tags approval request

### ISSUE THREAD

**Issue by ali-a6** [department-of-veterans-affairs/va.gov-team#49712]
# Google Analytics Implementation or QA Request

Google Analytics Implementation

## What this form is for: approval of Google tags created in Google tag manager

<details>

The reason for this request is to get approval for tags in these specific workspaces:

1. Cerner + MHV Appointments workspace [1. Go to VA Health ]

2. MHV Appointments workspace [1. Schedule an appointment button: (right from homepage), 2. Schedule or Cancel a VA Appointment from get care drop down, 3. Go to my appointments]

3. MHV homepage workspace [1. MHV logo / Home button, 2. VA Facility Locator button on the MHV home page]

4. MHV Secure Messaging workspace [Exact button, Next button, Previous button]

<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

</div>
</details>

### Required
- **Is this request for **Google Analytics implementation** or **QA**?**

     - [X] Google Analytics implementation
     

- **Who is this request for?**

    - UCD team

    
    
- **Provide the link(s) for Google Analytics implementation or QA**

     - None
    
- **When is the launch date?**
    - As soon as possible -the tags just need to be approved.

- **What interactions need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked_
    
    - None

### Optional
- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

 

- **Any additional comments**

   

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by michelle-dooley** [comment]
@ali-a6 - so are you saying you already created the tags in GTM?  Is so where are they and what are they called so I can locate them?

**Comment by michelle-dooley** [comment]
@ali-a6 - also can you send me specific urls for the page referenced above I am having trouble finding them.  And a test user.

**Comment by ali-a6** [comment]
@michelle-dooley

Yes, I’ve created all the tags, they just need to be approved. All the workspaces are under [VA.gov](http://va.gov/) -> [VA.gov](http://va.gov/) Brand Consolidation Legacy


1st workspace =[ Cerner + MHV Appointments](https://tagmanager.google.com/#/container/accounts/144676348/containers/9159499/workspaces/1000050/tags)

Tag needing approval = 

- Button Click Go to My VA Health




2nd workspace = [MHV Appointments](https://tagmanager.google.com/#/container/accounts/144676348/containers/9159499/workspaces/1000049/tags)

Tags needing approval = 
- Button Click Go to Your VA Appointments
- Button Click Schedule a VA Appointment [right from homepage]
- Button Click Schedule or Cancel a VA Appointment [from get care drop down]




3rd workspace = [MHV homepage](https://tagmanager.google.com/#/container/accounts/144676348/containers/9159499/workspaces/1000048/tags)

Tags needing approval =

- Button Click Myhealthevet
- Button Click VA Facility Locator

 




4th workspace = [MHV Secure Messaging](https://tagmanager.google.com/#/container/accounts/144676348/containers/9159499/workspaces/1000051/tags)

Tags needing approval =

- Button Click Exact Match Check Box [under secure messaging advanced search]
- Button Click Next [under secure messaging advanced search]
- Button Click Previous [under secure messaging advanced search]


Regarding a test user, I don't have test user credentials. I see you listed as an administrator in GTM. I think the workspace links above should come up, but let me know if they don't.

**Comment by michelle-dooley** [comment]
@ali-a6 - just approved.

**Comment by ali-a6** [comment]
@michelle-dooley 

I can't see any of the four workspaces now in GTM. 

Do I need to request access to view them, if so, how can I do so?

**Comment by michelle-dooley** [comment]
When they are approved they become available in the default workspace.  Can you test one of them and see if its working?

**Comment by ali-a6** [comment]
I don't see any of the tags in the default workspace. I can only see them in the activity tab.

8 of the 9 tags are working in Google Analytics. The only one I don't see is the Button Click Exact Match Check Box.

**Comment by michelle-dooley** [comment]
@ali-a6 - do you have everything you need?
