### ISSUE TITLE
Adding Erin Flaherty to DSVA Slack

### ISSUE THREAD

**Issue by dcloud** [department-of-veterans-affairs/va.gov-team#49714]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

Please add Erin Flaherty, erin.flaherty@adhocteam.us, as Full member to DSVA Slack.

Erin Flaherty is a Senior Software Engineer, QA on the PTEMS shared support team. She will work with multiple application teams, so she needs full access.

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add [_insert email_] as a single-channel guest to [_channel name_].
- Please add [_insert email_] as a multi-channel guest to these channels: [_channel names_].
- Please add [_insert email_] as a full member.
- Please change the status of [_slack username_] from [_current status_] to [_desired status_]

**Comment by eunicegar** [comment]
done
