### ISSUE TITLE
Bad facility info fetch on Community Care confirmation page

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#4971]
http://sentry.vfs.va.gov/vets-gov/website-production/issues/93799/?query=is%3Aunresolved%20source%3Avaos

Looks like we're trying to fetch VA facility info on the confirmation page for a CC request, which shouldn't be necessary, and we don't show VA facility info for CC requests.

This fetch might not show up locally due to the way we mock end points, but we should be able to track down why the `getFacilityInfo` function is being called.

**Comment by vbahinwillit** [comment]
Looks like the ConfirmationPage does calls 'fetchFacilityDetails' which calls 'getFacilityInfo'  in componentDidMount. The check for CC failed:  !faciltyDetails && !facilityType !== FACILITY_TYPES.COMMUNITY_CARE
