### ISSUE TITLE
[Request] Change Mail and Fax info on Pre-Need form.

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#49730]
Matt Self forwarded a high priority request to change the mail and fax content on the pre-need form. The below graphic captures the suggested changes. 

![Screen Shot 2022-11-15 at 10.59.54 AM (1).png](https://images.zenhubusercontent.com/6113fbb753613f267009ce32/bb5a6792-916d-405c-bda2-ec17dce8548d)

**Comment by jerekshoe** [comment]
There is a duplicate ticket here: #49723

**Comment by jerekshoe** [comment]
Screenshot of the current page:
![Screen Shot 2022-11-16 at 9 48 06 AM](https://user-images.githubusercontent.com/13838621/202253769-18c0e615-ec30-4d6f-ba3e-93b5f1ae8b8d.png)
