### ISSUE TITLE
Scope: Update the workflow for "Off-Cycle Deployment" to generate issue with the correct template

### ISSUE THREAD

**Issue by powellkerry** [department-of-veterans-affairs/va.gov-team#49739]
## Description
When an off-cycle deployment of vets-api or vets-website is requested in the support channel, there is some additional "paperwork" that needs to be completed in order for the deployment to be approved (or denied). [This OOB Deploy Request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=platform-sre%2C+operations%2C+Console-Services%2Cfrontend&template=OOB-Deploy-Request.md&title=OOB+Deploy+Request) needs to be filled out by the requester. (A revproxy deploy does not need this request filled out.)

This template is linked in the off-cycle deploy docs that are linked in the support request, but it would be helpful if it was more prominent. It would be helpful because the time to resolution could be quicker. 

### Ideas

1. The workflow in Slack could be updated to display additional fields in the pop-up when "Off-Cycle Deployment" is selected as a topic. The additional fields could be modeled after [this](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=platform-sre%2C+operations%2C+Console-Services%2Cfrontend&template=OOB-Deploy-Request.md&title=OOB+Deploy+Request) issue template. The inputs from the form could be used to generate a GitHub issue that can be used for the out of band deploy.
2. The [OOB Deploy Request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=platform-sre%2C+operations%2C+Console-Services%2Cfrontend&template=OOB-Deploy-Request.md&title=OOB+Deploy+Request) doc could be linked as some "documentation that may help" message. Screenshot for example: <img width="531" alt="Screenshot 2023-07-13 at 5 27 02 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/10993987/a93c99fd-9ee2-4bc0-9674-8aae196a7521">
3. An additional message could be sent by the bot that reminds them to fill out the OOB Deploy Request

## Definition of done
An off-cycle deploy doc is able to be created quickly by the requestor. 

## Tasks to complete
- [x] Choose how to implement this (chose from the **Ideas** section)
- [ ] implement it
- [ ] Test that it works

**Comment by rmtolmach** [comment]
@alyssagallion I updated the description 🎉 

My recommendation is the second idea described above. It will be the quickest to implement and fits all of the use cases. The first idea would be cool, but not every "Off-Cycle Deployment" request type ends up needing an [OOB Deploy Request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=platform-sre%2C+operations%2C+Console-Services%2Cfrontend&template=OOB-Deploy-Request.md&title=OOB+Deploy+Request) filled out. It would also be more work.

**Comment by bdech** [comment]
Talked with Joe Tice about implementing OOB Deploy GitHub request. Joe is looking at this bandwidth to see when he can fit this in.

**Comment by alyssagallion** [comment]
* @bdech  Send process loosely to Alyssa in Slack

**Comment by alyssagallion** [comment]
@bdech To reach out to Joe Tice's team.

**Comment by alyssagallion** [comment]
Work is being implemented in [this ticket](https://app.zenhub.com/workspaces/platform-tech-team-support-634ebbcc35e2bc0015b382fd/issues/gh/department-of-veterans-affairs/va.gov-team/66354), as a result we will close this one.
