### ISSUE TITLE
Support Slack-bot GitHub integration

### ISSUE THREAD

**Issue by powellkerry** [department-of-veterans-affairs/va.gov-team#49732]
## Problem Statement
The platform support slack-bot is a powerful tool to field support requests, but it has become challenging for support team members to keep track of support requests as they can get lost in slack threads. 

## High Level User Story/ies
As a user, I need my support requests tracked so I can see progress made.

As a Support Team Member, I need to see all of my assigned support requests so that I can keep track of the work the I need to do

As an Engineering Lead, I need to track and see reports for the issues that the support team receives and completes so that I can allocate resources to the team accordingly

## Hypothesis or Bet
- These changes will improve productivity of both support team members and support requesters by providing a way to track work and progress on support requests.
- Management will be able to see the work allocated to the support team and be able to provide the level of resources needed to the team based on issue metrics.

## OKR
_Which Objective / Key Result does this epic push forward?_

**Comment by jknipes** [comment]
User support requests are tracked in Slack channel #vfs-platform-support with :eyes: for acknowledgement and :support-complete: for completion. Progress is commented on in the Slack thread for that issue.

**Comment by alyssagallion** [comment]
We are working on all support bot changes in this EPIC: https://app.zenhub.com/workspaces/platform-tech-team-support-634ebbcc35e2bc0015b382fd/issues/gh/department-of-veterans-affairs/va.gov-team/61279
