### ISSUE TITLE
Identify how central mail PDFs handle "VA use only" sections

### ISSUE THREAD

**Issue by ndsprinkle** [department-of-veterans-affairs/va.gov-team#49742]
### Description

Some VA PDFs contain a section that contains text along the lines of "for VA use only" indicating that the section is to be filled out by a person at the VA. A paper example of this is form 26-8937: https://www.vba.va.gov/pubs/forms/VBA-26-8937-ARE.pdf

We should figure out how these sections are currently being handled by central mail created PDFs. 

### Definition of done

- [x] One or more forms are identified as being available to fill out digitally on VA.gov that contain a section that the VA must fill out
- [x] If forms like this are available to fill out digitally on VA.gov, then we have identified how they are handled by the PDF creator for central mail (does it include the "for VA use only section? does it auto-fill those values? does it exclude it altogether?)

**Comment by charleystran** [comment]
Forms from vets-api do not currently use the va only section of PDFS. A direct example of this is 21-22 form for power of attorney. Vets-api does not fill out the va-only section. However, in uploading to central mail, business line number and the date that vets-api sent to central mail are part of the meta-data that is in the central mail payload. I am not sure if business line is used to send the form as a copy to other teams (re VR&E, EDU, LGY, Insurance) but it is not something handle in our current codebase.
