### ISSUE TITLE
[SPIKE] Explore How we Might Surface Appointment Modality in GA

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#49746]
## Tasks
- Explore how we might expose GA metrics to differentiate between appointment modality (i.e. in-person vs. phone call) while noting that we may add modalities in the future
- Note: Appending the modality type to all events (as soon as we're able to recognize the type) might be the ideal solution, but not required

**Comment by brianseek** [comment]
Created phone appointment util and added event to pre-check-in start to record phone/in-person.

When a patient clicks the Answer Questions link a new nav event gets fired to record if there are phone appointments or just in-person. Event:  `nav-check-in-pre-check-in-started-phone` or  `nav-check-in-pre-check-in-started-in-person`

**Comment by brianseek** [comment]
@benbrasso-agile6 This is merged and ready to validate as soon as it hits prod

**Comment by benbrasso-agile6** [comment]
I see both, brian. I added it into our [events spreadsheet](https://docs.google.com/spreadsheets/d/1BPOlI6vzH-tMTswvUrci3Q0NkBmfIIfo8Cgj_nM10gk/edit#gid=0) and i'll create a new ticket for me to add it somewhere into our GA dashboards.
