### ISSUE TITLE
GIBCT: The VetTec logo on the profile page shows up twice on mobile

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#4974]
When viewing any Vet Tec provider profile page on mobile the Vet Tec logo shows up twice - once above and once below the institution name. The logo should only appear once above the institution's name. See attached screenshots. 

Original requirement for logo position located here:
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19184

## Current Behavior
![IMG_0078.PNG](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/e577f265-5437-44b7-9487-cdbb9eb1b448)

---

## Desired Behavior
![63110191-d6021a00-bf58-11e9-8ea2-012de7d293d3.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/d4c96861-c634-4599-89cf-26fef2d21844)

**Comment by ksantiagomorgan6** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/11531

**Comment by delli-gatti-michael** [comment]
The number of logos has been reduced to 1. Pr has been approved and is awaiting merge

![Screen Shot 2020-01-21 at 11.21.45 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/469875f8-aa53-4fcd-847b-2c34c50f4c47)

**Comment by delli-gatti-michael** [comment]
PR has been merged and changes are showing in Staging. This fix should be in production after today's 2:00 deploy

**Comment by delli-gatti-michael** [comment]
This bug fix is now in production. Closing this issue
