### ISSUE TITLE
Deprecate old vets-api dev worker and server

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#49741]
## Description
On 11/16, the dev worker and server parent helm charts were released successfully. [App here](https://argocd.vfs.va.gov/applications/vets-api-dev?view=tree&resource=). We will need to deprecate the "old" [worker](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps/sidekiq/dev) and [server](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps/vets-api-server/dev) 

## Todo items
- [x] Remove worker and server [config from vsp-infra-argocd](https://github.com/department-of-veterans-affairs/vsp-infra-argocd/blob/main/chart/values.yaml)
- [x] Remove server and worker

**Comment by considerable** [comment]
Done: (rm -rf apps/sidekiq/dev apps/vets-api-server/dev)
