### ISSUE TITLE
Change broken link on COVID vaccines page 

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#49769]
## Issue Description
We have a broken link on our [COVID-19 vaccines at VA](https://www.va.gov/health-care/covid-19-vaccine/) page that we need to fix. 

It's in the accordion section for "Before you get your vaccine" in the first accordion "Where we offer COVID-19 vaccines at VA." The broken link is the Download our pharmacy billing information card (PDF). 

The new PDF should be: https://www.va.gov/COMMUNITYCARE/docs/programs/OCC-Billing-Information-Card.pdf

We need to make this change on all three vaccine pages (English, Spanish, and Tagalog)

## Tasks
- [x] Update link on 3 pages (Aliyah)
- [x] Copyedit (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] Link is no longer broken on live pages

**Comment by aliyahblackmore** [comment]
Hi @megzehn these pages are ready for you!

English page: http://preview-prod.vfs.va.gov/preview?nodeId=11463

Spanish page: http://preview-prod.vfs.va.gov/preview?nodeId=16359 
Note: I added in (en ingles) here.

Tagalog page: http://preview-prod.vfs.va.gov/preview?nodeId=16413

**Comment by megzehn** [comment]
Thank you, @aliyahblackmore! 

Confirming these are published!

**Comment by megzehn** [comment]
CC @RLHecht

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
