### ISSUE TITLE
Clear Obfuscated Pre-Filled Bank Account Numbers When Updating

### ISSUE THREAD

**Issue by nathanielbuck** [department-of-veterans-affairs/va.gov-team#49768]
### User story

As a ToE (form 22-1990e) applicant, when I'm on the Direct Deposit page I want obfuscated, prefilled bank data to be cleared out when clicking the update button on the ReviewCardField (in view mode), so that I don't have to manually clear out the data before updating it.

### Additional details/notes/links

Slack conversation: https://dsva.slack.com/archives/CBU0KDSB1/p1668628110417759

We are using the `ReviewCardField` for direct deposit and have the bank account information prefilled with obfuscated data (leading asterisks with last four characters displayed). We added custom validation so this format is valid, as long as it matches the original values (in case they don't want to change them).

We have `volitileData` set to `true`, but the values aren't being cleared out when going from view to edit mode when the update button is clicked.

#### form.js config
https://github.com/department-of-veterans-affairs/vets-website/pull/22682/files#diff-15a75de7b86c9cc6be08d1eb0e7ff59255f2a0ea29de300f296ef65170b0e019L1208

#### Custom validation
https://github.com/department-of-veterans-affairs/vets-website/pull/22682/files#diff-05cc0ad735068d52d09193ce9080f096a51913f5a3b06fc88a40eaedc7c62dccR96

#### Direct deposit view
<img width="523" alt="direct-deposit-1" src="https://user-images.githubusercontent.com/112403/202485354-3cdf9d8e-b2ca-40e1-99b5-5285c981ba4e.png">

#### Direct deposit edit
<img width="531" alt="direct-deposit-2" src="https://user-images.githubusercontent.com/112403/202485508-be1b72e9-f581-414e-9011-a4cc677408f1.png">

### Acceptance criteria

Bank data gets cleared by the ReviewCardField when going from view to edit mode.

### Points of contact

@nathanielbuck
@cesaresantiago

### What type of issue is this? 
- [x] Bug
- [ ] Request new feature
- [ ] Request update to existing feature
- [ ] Documentation change
- [ ] Other (please describe)

### How to configure this issue
- [ ] When ticket is opened, assign to Epic [#12765 Forms library user feedback and requests to be triaged](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/12765)
- [ ] FE Tools team will triage and add to [Design System Governance Process Project Board](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/projects/3) as applicable

**Comment by bkjohnson** [comment]
At the moment there isn't a forms library team, and the Design System team doesn't have the bandwidth to do the development work on this. I've added the `platform-cop-frontend` label, so if you or anyone else from the frontend wants to work on this issue the DST would review and provide guidance.

**Comment by CBonade** [comment]
After discussing with the COP, we feel this would provide a subpar user experience and are considering closing the ticket. Wanted to put a comment out to give anyone a chance to chime in before closing at our next refinement meeting in ~2 weeks from today.
