### ISSUE TITLE
Adding Marcus Dietz to DSVA Slack

### ISSUE THREAD

**Issue by marcusdietz** [department-of-veterans-affairs/va.gov-team#49762]
# Description

Please add Marcus Dietz (dietz_marcus@bah.com / marcus.dietz@va.gov) to the DSVA Slack.

Requesting to add an individual as a:
- Full member

Marcus is an architect supporting the the VES Portfolio under Sophie Myers and needs to collaborate with ThoughtWorks.

We aim to complete slack requests within 24hrs.

**Comment by eunicegar** [comment]
done
