### ISSUE TITLE
Update timeframe on presidential memorial certificates page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#49764]
## Issue Description

NCA stakeholders asked us to update information on our [Presidential Memorial Certificates](https://www.va.gov/burials-memorials/memorial-items/presidential-memorial-certificates/) page. 

Under the H2 "Check the status of your request," we need to change 6 weeks to 16 weeks. We should think about if we want to say 4 months instead. 

We also need to check if this number appears on any other pages and will need to update it there as well. 

## Tasks
- [x] Update content 
- [x] Review (Laura)
- [x] Send to stakeholder if we made any other changes
- [x] Copyedit (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] New content is live on the site

**Comment by laurwill** [comment]
Hi @megzehn , this page is ready to publish today — just made a small change in the "Check the status" section at bottom. 

http://preview-prod.vfs.va.gov/preview?nodeId=860
