### ISSUE TITLE
Removal of Form 22-S900 (Veteran Rapid Retraining Assistance Program VRRAP)

### ISSUE THREAD

**Issue by jsimonVA** [department-of-veterans-affairs/va.gov-team#49776]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [ ] Making revisions to an existing online form, app, or tool on VA.gov
- [ x] Something else (please add details in the next question)

## What do you need help with?
  - [ x] Content support
  - [x] IA support
  
Form 22-S900 refers to "Veteran Rapid Retraining Assistance Program". This program will end taking new applicants starting 11 Dec 2022 (10 Dec 2022 is the last day for a veteran to apply for this program). There are several links and sections about this program I need to have scheduled to be removed on 11 Dec 2022. Please see below for the list.

Page URL (https://www.va.gov/education/other-va-education-benefits/) 
Within this page I need the link "Education and training benefits during the COVID-19 pandemic" under the On This Page section removed and the related section "Education and training benefits during the COVID-19 pandemic" removed at the bottom that page.

Page URL (https://www.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/)
Removal of this page. I have a ticket for the removal of the URL submitted as well https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11642

The side navigation, under Other VA education benefits, I need the Veteran Rapid Retraining Assistance Program (VRRAP) link removed

I am not sure if the following location is one that you support, if not please let me know, if it is I need the following changes made:
PAGE URL (https://www.va.gov/school-administrators/)
Under the "Key resources for SCOs" section, I need the VRRAP For Schools link removed

When visiting the URL (https://www.va.gov/OGC/) there is a side navigation menu, under "For Veterans", "Education", I need Veteran Rapid Retraining Assistance Program (VRRAP) removed. I am unsure who works on this nav menu so please let me know if it is not this office. 

All these links need to remain active until 11 Dec 2022, Veterans should be able to apply on the last day which is 10 Dec 2022.

Lastly, I need all the "best bets" removed from search results for VRRAP
  
*Please be specific about the content or IA support you need and provide any additional documents and/or links that will help us help you. If we need to add a react widget to a page, be sure to provide the code here.*

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [ ] Yes
  - [x ] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
## When do you expect to launch your product to 100% of users?
Form VRRAP needs to be removed (all links and search best bets) on 11 Dec 2022.
This program will no longer be accepting new applicants as of 11 Dec 2022  

*Please provide an estimated date so our team can create other relevant tickets.*
Removal to be completed on 11 Dec 2022
  
## Supporting artifacts
*Please provide supporting artifacts as available.*

- Link to product outline:
- Link to or attach user flows:
- Link to prototype or mockups:
- Link to any epics/issues that may be helpful:

## Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [ x] No

## When does this work need to be done?
- Estimated launch date: 11 Dec 2022
- Estimated staging review date:
- Content and IA work needed by: 11 Dec 2022

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [ x] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: Cinda Quattrini
-	Product manager: Kara Ciprich
-	Designer: 
-	FE engineer: Jarred Simon
-	Product/team Slack channel:

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by RLHecht** [comment]
@jsimonVA I created a ticket for our team to implement most of this work. We do not handle the school administrators page, but I will reach out to that stakeholder to let them know they need to remove the link.

We also don't have access to https://www.va.gov/OGC/ so that would need to be another team.

**Comment by jsimonVA** [comment]
@RLHecht Thank you for the update. On the https://www.va.gov/OGC/ page, it's not the actual page but the nav bar on the left side. I wasn't sure if that component itself was something your office has access to. The nav bar is located in several of those pages, I just used the OGC page as the example. Would you have any clue who does deal with that nav component?

**Comment by mnorthuis** [comment]
@jsimonVA I noticed there's no reference to taking down the actual online form in the [redirect ticket](https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-cms/issues/11642) (for some reason I can't tag you in that ticket).  The redirect request is for the static landing page, were you intending to also capture the online form in that redirect?

**Comment by RLHecht** [comment]
@jsimonVA Our team can't access that left nav and I'm not sure which office would be able to do that unfortunately. The person I reached out to in VBA doesn't handle that part of the site.

**Comment by jsimonVA** [comment]
@mnorthuis We are keeping the form in the code base for now, and eliminating anyway to access it. This way if a last minute extension is granted we can get the form back up rather quickly. 

@RLHecht thank you for the info, I will do some more research to see who can modify that nav component.

**Comment by mnorthuis** [comment]
@jsimonVA You can leave the form in the code base, but we can't leave the form URL live or visitors will be able to access it, so we have to do something for the UX side.  If you think that it may need to go back up, then we have 2 options:
1) put permanent 301 redirects on both the landing page and the form, which we can reverse if needed, but if indexing these pages for search will be critical again, this can really prove to be a challenge for search engines.  If that is the case, then option two is a better option
2) put a temporary 302 redirect on both the landing page and the form, this can be easily reversed and search engines should quickly pick back up on the page.  Once we know the program is officially retired, then we can switch this to a 301. 

In regards to the school administrators page, your education stakeholders own that page, so they should know who to contact to make modifications.   Any TeamSite pages, like the OGC page, that have left nav links, each of those offices will need to remove that from their left nav.   We do not have access to modify any Teamsite pages.

**Comment by jsimonVA** [comment]
@mnorthuis i'm following now. Yes I do need to capture (https://www.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/apply-for-vrrap-form-22-1990s/introduction) and (https://www.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/apply-for-vrrap-form-22-1990s/apply). 

As of 11 Dec 2022 the program will officially stop taking new applicants and there is no signs of there being an extension from what I understand. With that said, I feel like we should go the 301 route. I will add these two URLs to the other ticket as well. Thanks for catching that.

**Comment by mnorthuis** [comment]
@jsimonVA Excellent!  I think what we can actually do, is just use the redirect you have and indicate that it needs to capture all child "pages" from the form flow, since the form actually sits as a child of the content page.  I'll make a note in the ticket for it, so no action from you, thank you for confirming!

**Comment by jsimonVA** [comment]
Adding as an FYI in this issue as well. Previously added to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11642


@RLHecht @jilladams Cinda Quattrini has given the ok to make changes on the 12th as long as we are able to place a note of sorts on the page by end of day tomorrow, 9 Dec 2022, letting users know that no new applications will be accepted after 10 Dec 2022. She did say that she may need to verify this with someone else (don't have a name), but for now move forward with the 12th. Darla Van Nieukerk asked if we can get an early release on Monday 12 dec 2022, since this will be visible pass the program end date.

**Comment by RLHecht** [comment]
@jsimonVA Confirming that we can close this ticket.

**Comment by jsimonVA** [comment]
@RLHecht confirmed. do I need to close or will you?

**Comment by RLHecht** [comment]
I'll close. Thanks!
