### ISSUE TITLE
[FE] My VA Audit UX Improvements: Update the "Apply for Healthcare" Link

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#49774]
## Background
Based on recommendations from content we want to change the "Learn How to Apply for Healthcare" link in the Healthcare section to say "Apply for Healthcare" in order to be more consistent with where the link actually directs the users. 

Link to FE documentation is [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/health-care-FE-documentation.md)

## Tasks
- [x] Update the link copy to "Apply for Healthcare"
- [x] Validate

## Acceptance Criteria
- [x] The link in the Healthcare section reads "Apply for Healthcare" and is behind the Audit feature flag

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)? Any team member_
- _How can this work be validated?_ Log in with a staging user who does not have healthcare and confirm the link copy is correct

**Comment by ericasauv09** [comment]
validated with user 272, however when I clicked on the "Learn how to Apply for Health care" link I was taken to a "we can't find that page." I noticed the URL it took me to was - https://staging.va.gov/apply/application/introduction. Whereas the FE documentation says the URL should be - https://www.va.gov/health-care/apply/application/introduction. Does this URL need to be updated? @tmitchellgcio can you take a look?

**Comment by tmitchellgcio** [comment]
Originally it was /application, however the docs said application/introduction. I assumed I was wrong and changed it. Next time I will test it. Will get that fixed

**Comment by ericasauv09** [comment]
looks like the URL is just missing the /health-care/ part.

**Comment by tmitchellgcio** [comment]
oh you're right

**Comment by ericasauv09** [comment]
validated with user 272: ![Screen Shot 2022-12-09 at 15.11.11.png](https://images.zenhubusercontent.com/62571b850845ac72a9917e8e/4a59c76d-ded5-4f75-a80f-f9094d064fd1)
