### ISSUE TITLE
Research central mail PDF filler process and how data maps

### ISSUE THREAD

**Issue by ndsprinkle** [department-of-veterans-affairs/va.gov-team#49793]
### Description

Submitting digital forms via central mail seems to be, in terms of development time, the fastest way to digitize a form in vets-api. We should research this process to better understand how fields are mapped and how the original PDF is filled out in vets-api. This will also help us understand how vets-website should structure the data being sent to vets-api on submission.

### Definition of done

- [x] The PDF mapping/filling process is researched and documented to make it easier to implement for future forms
- [x] The central mail submission process is researched and documented to make it easier to implement for future forms
- [x] If possible, additional documentation is created to identify areas for automation in the PDF mapping/filling and central mail submission processes

**Comment by tbaker1026** [comment]
- [ ] Add additional document links that you used 
- [ ] Additional documentation on process - edge cases etc.

**Comment by charleystran** [comment]
uploading CM tutorial that can serve as the documentation in addition to the demo video
[https://app.zenhub.com/files/133843125/ee52871b-8ee6-4fe2-b9cf-ac00efd851bf/download](https://app.zenhub.com/files/133843125/ee52871b-8ee6-4fe2-b9cf-ac00efd851bf/download)
