### ISSUE TITLE
Adding Jordan Wood to DSVA Slack

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-team#49801]
# Description

- Please add jordan.wood@civicactions.com as a full member.
- What channel(s) do they need to be added to? (I can also do this once she's added)
 * #sitewide-public-websites
 * #sitewide-program
 * #vfs-all-teams
 * #vfs-change-announcemens
 * #design

Role: Designer
Team: Sitewide Public Websites
PO: Dave Conlon

**Comment by eunicegar** [comment]
done
