### ISSUE TITLE
Offboarding of [Travis Hoffmann]

### ISSUE THREAD

**Issue by mikeprusaitis** [department-of-veterans-affairs/va.gov-team#49813]
# Instructions
Fill out name of individual and *Description* section below.

*(Please add only one individual per form)*

# Description
Please provide the following information about the individual being offboarded:
- name:
  > Travis Hoffmann
- team name:
  > identity-product-team (login.gov adoption team)
- role on team:
  > PM
- expected last day: _(MM/DD/YYYY)_
  > 11/23/2022
- company they work for:
  > MO Studios
- email: _(Multiple emails listed in order of relevance to VA business, VA, Company, Personal, etc....)_
  > [travis@themostudio.com](mailto:travis@themostudio.com)
- GitHub username: _(Please include @ symbol)_
  > [@MOStudioTravis](https://github.com/MOStudioTravis)
- additional access they may have: _(First line formatted with access titles only. Additional notes may be added on second line after the list.)_
  > 
 
## Acceptance Criteria
*The following steps are performed by the Platform Support team. Detailed instructions found [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/2097545323/Offboard+Team+Member)*
 - [x] Requested removal from DSVA Slack (if applicable. Search for them in Slack)
   > A comment on this ticket prefixed with `/request` (i.e. `/request FirstName LastName`) will send a message to the Slack admins automatically!
 - [x] Requested removal from Confluence (if applicable. Check [confluence members](https://vfs.atlassian.net/wiki/people/search?q=))
 - [x] Remove from [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=0) (if applicable)
 - [x] Remove from global/config.yml / SOCKS Access removed (if applicable. Search their email in [config.yml](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/global/config.yml))
   > Use the [Remove SOCKS and AWS access Github Workflow](https://github.com/department-of-veterans-affairs/devops/actions/workflows/offboarding.yml) to create a PR to update the `global/config.yml` file and remove the public SSH key. You'll need the user's email address associated with their public key (found in `config.yml`).
 - [x] AWS Access removed  (if applicable. Search their name in [AWS IAM](https://console.amazonaws-us-gov.com/iamv2/home#/home))
   > Use the [Remove SOCKS and AWS access Github Workflow](https://github.com/department-of-veterans-affairs/devops/actions/workflows/offboarding.yml) to remove user's entry from DSVA AWS. You'll need the user's AWS username (typically `First.Last`).
 - [x] User removed from the VA GitHub Org (if applicable. Check [department-of-veterans-affairs/people](https://github.com/orgs/department-of-veterans-affairs/people))
   > Fill out request found [here](https://github.com/department-of-veterans-affairs/github-user-requests/issues/new?assignees=&labels=remove-user&template=user-remove.yml&title=Remove+User+from+Org%3A+%5Busername%5D). 
 - [x] Pagerduty access removed (if applicable. Check [pd users](https://dsva.pagerduty.com/users-new))
 - [x] Datadog account disabled (if applicable. Check [Datadog users](https://vagov.ddog-gov.com/organization-settings/users))
 - [x] Sentry access removed (if applicable. Check [Sentry members](http://sentry.vfs.va.gov/settings/vsp/members/))
 - [x] Google analytics and Domo access removed (if applicable. Make sure the `analytics-insights` label is on this Issue)
 - [x] Bot (`va-bot`, `va-vfs-bot`, and `va-vsp-bot`) user GitHub account(s) YubiKey(s) removed
   > This is rare. See [documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1908932642/Remove+YubiKeys+of+Offboarded+Operations+Team+Members) for current users and removal process.
 - [x] Sketch editor access removed (if applicable. Check [Sketch settings](https://www.sketch.com/workspace/c99d3e96-7c23-4210-b173-92a2b73a8788/settings/people))
 - [x] Removed from Monday Design Meeting invite

 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/platform-analytics-insights-team , @department-of-veterans-affairs/confluence-admins, @department-of-veterans-affairs/platform-design

**Comment by naomimarcussen** [comment]
- Does not have a Sketch account
- Is not on the Design meeting invite

**Comment by michelle-dooley** [comment]
No Domo or GA.

**Comment by holdenhinkle** [comment]
no confluence
no SOCKS
no AWS
removed GitHub - https://github.com/department-of-veterans-affairs/github-user-requests/issues/13695
no PG
no DD
no Sentry

**Comment by holdenhinkle** [comment]
Awaiting confirmation that user has been removed from Slack.
