### ISSUE TITLE
Graceful shutdown for Puma pod termination

### ISSUE THREAD

**Issue by considerable** [department-of-veterans-affairs/va.gov-team#49822]
**Graceful shutdown of pod** in [K8s documentation](https://github.com/puma/puma/blob/master/docs/kubernetes.md#graceful-shutdown-and-pod-termination) and in [K8s learning material](https://learnk8s.io/graceful-shutdown) suggest adding a sleep to the pre-stop hook of the same time as the `terminationGracePeriodSeconds` time.

**Comment by LindseySaari** [comment]
Gracefulshutdown is implemented :) 120s for Sidekiq pods
