### ISSUE TITLE
Improve FE Review Process

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#49831]
- Approval process work w/ Jhonny from a Frontend CoP to follow along w/ how BE and DevOps do it
- Look at CoP privs for GH and work to get those permissions in place for approval, etc.
- PR checklist, that sets the expectation for the reviewer

- [x] @jhonnyoddball to develop list of people to add to "Platform CoP Frontend approvers" github team. This team should have permission to approve vets-website changes which then would not force other teams listed in the approvers list to approve the code change
  - Check how vets-api does this with backend CoP

**Comment by joeniquette** [comment]
- [Current vets-api PR template](https://github.com/department-of-veterans-affairs/vets-api/blob/master/.github/PULL_REQUEST_TEMPLATE.md)
- [Current vets-website PR template](https://github.com/department-of-veterans-affairs/vets-website/blob/main/.github/PULL_REQUEST_TEMPLATE.md)
- [Current devops PR template](https://github.com/department-of-veterans-affairs/devops/blob/master/.github/PULL_REQUEST_TEMPLATE.md)

- [ ] There is no manifests repo (EKS infra repo) PR template, we need one

**Comment by joeniquette** [comment]
@jhonnyoddball Can you determine who should be on the list of frontend approvers who can approve on behalf of "vets-website". Thus not requiring other teams to also approve the PR. The mindset should be that if the frontend COP approvers dont feel comfortable with approving they change, they should indicate why and not approve it. Its ok to defer to other teams in those cases. However if the group selected does feel comfortable approving the changes they should. Then its up to the engineer who wrote the PR to decide if they are ready to merge it or want other teams to review it as well.

**Comment by joeniquette** [comment]
PR Template PR [started](https://github.com/department-of-veterans-affairs/vets-website/pull/22727). If this is accepted it will be applied to vets-api, devops, vets-website, and the manifests repo. It is expected that each CoP organizer will then mold it to fit their repos needs, this does not have to be the final product.

**Comment by alyssagallion** [comment]
Checking notes, will update when implemented feedback.

**Comment by joeniquette** [comment]
PR template merged for vets-website. Next steps are to create a similar one for the other major repos.

**Comment by joeniquette** [comment]
created PR templates for remaining repos

**Comment by joeniquette** [comment]
bumped the PR templates for devops and the manifests repo. Once I have those reviews compete then this ticket can close.

**Comment by joeniquette** [comment]
All PR templates merged and approvals completed
