### ISSUE TITLE
[FE] Military information: Update NoServiceHistoryAlert

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#49835]
### Background

While other military information alerts were updated in #47477, we did not update `NoServiceHistoryAlert` which provided a poor user experience for a Coast Guard veteran in a UAT session for My VA today (their information may not be in DEERS since old Coast Guard data may live with another department).

### Tasks

- [x] Update the `NoServiceHistoryAlert` with the copy [in this Sketch file](https://www.sketch.com/s/fc96664a-1c62-40ed-9fcd-90218c54e775/a/52vgV88). 

### Acceptance Critera

- [ ] Have Samara test, as she gets the `NoServiceHistoryAlert` instead of `NotAVeteranAlert` for some reason.

**Comment by SKasimow** [comment]
@cgednalske - can you update this message to show "711" for the TTY number?

**Comment by SKasimow** [comment]
@Samara-Strauss - question came up on whether this should be applied to all military alerts (with the exception of the non-veteran / non-DEERs scenario)

**Comment by Samara-Strauss** [comment]
> on today's grooming call we discussed whether we should expand the scope of this ticket to apply to all military alerts (rather than just what is defined for this ticket "NoServiceHistoryAlert").

What are the other alert codes we need to account for? That will help determine what is appropriate.

**Comment by jcatergovy** [comment]
@Samara-Strauss @SKasimow I updated the text on this one and it's ready for a PR and to go out today.  Normally I'd consolidate it with the other alert, but as we're planning to consolidate all the Military Information alerts soon I'd just end up undoing that work.  I just wanted to check with you two that consolidating those two alerts is on our near term roadmap before moving on.

**Comment by Samara-Strauss** [comment]
> as we're planning to consolidate all the Military Information alerts soon

Can someone let me know what military error codes need to be reviewed to determine if their error alerts need to be updated? 

> consolidating those two alerts

Which two alerts are you talking about here?

**Comment by cgednalske** [comment]
I'm not sure which two alerts are referred to above for consolidating, but if helpful here are all the military alerts I'm aware of. From [our thread](https://dsva.slack.com/archives/C909ZG2BB/p1668787488505049) on this the other week, we seemed to land on using the first, longer alert with more info for all other alerts except for the non-deers (blue) alert that John mentioned above.

<img width="507" alt="military info - 403" src="https://user-images.githubusercontent.com/79372956/204346653-1302ab28-ea53-40cf-a67a-321d6a9b4f7b.png">
<img width="502" alt="military info - non-veteran" src="https://user-images.githubusercontent.com/79372956/204346655-6dce9a34-73e7-4aae-a743-4930d246093c.png">
<img width="960" alt="military info - can't access information" src="https://user-images.githubusercontent.com/79372956/204346651-08cb0c35-09c7-4b1a-9116-4464eee71dd2.png">

**Comment by Samara-Strauss** [comment]
> From [our thread](https://dsva.slack.com/archives/C909ZG2BB/p1668787488505049) on this the other week, we seemed to land on using the first, longer alert with more info for all other alerts except for the non-deers (blue) alert that John mentioned above.

Yes, we landed on using this alert for the codes we talked about. But based on this comment...

> on today's grooming call we discussed whether we should expand the scope of this ticket to apply to all military alerts (rather than just what is defined for this ticket "NoServiceHistoryAlert").

It is unclear to me whether there are other error codes (or not) that we need to consider. So I need to know exactly which error codes we are talking about so I can make sure all errors are accounted for and updated accordingly.

**Comment by Samara-Strauss** [comment]
OK, so can someone confirm (1) these are all the military error states we need to account for, and (2) the errors we are showing for them? If so, what are the remaining questions that need to be answered?

`NotAVeteranAlert`

<img width="502" alt="military info - non-veteran" src="https://user-images.githubusercontent.com/79372956/204346655-6dce9a34-73e7-4aae-a743-4930d246093c.png">

`NotInDeersAlert`

<img width="507" alt="military info - 403" src="https://user-images.githubusercontent.com/79372956/204346653-1302ab28-ea53-40cf-a67a-321d6a9b4f7b.png">

`NoServiceHistoryAlert`

<img width="507" alt="military info - 403" src="https://user-images.githubusercontent.com/79372956/204346653-1302ab28-ea53-40cf-a67a-321d6a9b4f7b.png">

**Comment by cgednalske** [comment]
This looks right to me, but I think @jcatergovy can better confirm. Also, John do these cover/account for the alerts below as well? I'm not sure which code they fall under.
<img width="960" alt="military info - can't access information" src="https://user-images.githubusercontent.com/79372956/204379713-1a38c4a3-5aff-494e-b6a9-bfb1303f4bc6.png">

**Comment by jcatergovy** [comment]
@Samara-Strauss has it right.  @cgednalske this update only changes the No Service History Alert, I'm not familiar with those.

**Comment by Samara-Strauss** [comment]
@jcatergovy are there any other error codes associated with military information, and, if so, what messages do they show?

**Comment by jcatergovy** [comment]
@Samara-Strauss The DD214 link is "technically" an alert but it's always on and has no trigger.  Other than that it's just the three you mentioned.

**Comment by Samara-Strauss** [comment]
Great! So, to summarize:

- All alerts are accounted for and have been updated to function as I have outlined above.
- There is no other consolidating or work that needs to happen.

@jcatergovy -- did the `NoServiceHistoryAlert` update go to production yet? If so, let me know. If not, we should be good to go unless there is something I am missing.

**Comment by jcatergovy** [comment]
@Samara-Strauss This is in staging and ready for validation, @cgednalske @SKasimow

**Comment by cgednalske** [comment]
I'm seeing the following for a few users (86 and 111). Should I be seeing this view? I believe there is still in progress work with the top alert (and maybe the fact that they're both showing up?), but it looks like the bottom one is still an old version. 

<img width="861" alt="Screen Shot 2022-12-01 at 1 11 17 PM" src="https://user-images.githubusercontent.com/79372956/205150420-e3d54a57-0a03-4222-ab0e-9220a7e757bd.png">

**Comment by Samara-Strauss** [comment]
@jcatergovy can you look into this with @cgednalske to determine what is going on?

**Comment by Samara-Strauss** [comment]
**Note**: The issue Christina found above was due to some planned downtime for VA Profile's QA environment, which is what connects to our staging. This will likely not be an issue in a couple of hours, so please check back tomorrow morning.

**Comment by cgednalske** [comment]
Just checked the same user and the page looks good now! Only thing I noticed is that I think we're missing "office is open" in the second sentence of that first larger paragraph. The text should be: 

> The DMDC office is open Monday through Friday (except federal holidays), 8:00 a.m. to 8:00 p.m. ET.

Here's the image of what I'm seeing now. Everything else looks good!

<img width="818" alt="Screen Shot 2022-12-02 at 12 47 17 PM" src="https://user-images.githubusercontent.com/79372956/205374251-6bd4a234-216d-449f-b20d-59cf45201d8e.png">

**Comment by jcatergovy** [comment]
@cgednalske @SKasimow fixed and ready for review in staging

**Comment by SKasimow** [comment]
Thanks guys - will close this out

**Comment by jcatergovy** [comment]
@SKasimow Yes, this has gone to prod
