### ISSUE TITLE
FE | Profile | Updates to TTY 

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#49843]
## Background

There are several places within Profile where the TTY relay number needs to be updated to display "711" vs and 800# or "+711". This work is part of #46195.

Specifically we need to update the following:

- For the FAQ on the Personal info page, we need to change the TTY from "+711" to "711" (see comments for screenshot)
- For the FAQ on Military info page, we need to replace the TTY 800# with "711" and add a space between "call" and "TTY" (see comments for screenshot)
-  Check and notify PM/Design if any other alerts are found needing updates for TTY 

Tasks
- [x] Conduct Unit tests 
- [x] Run E2E tests covering current code and regression
- [ ] Notify PM if this needs to be deployed to Staging behind feature flag
  

## Acceptance Criteria
- [x] Complete all unit testing
- [x] End-to-end tests showing 0 violations
- [x] All axe checks pass
- [x] Notify Product Manager that the change is ready to be validated on Staging
- [ ] Incorporate any changes resulting from Staging review & re-test & have re-validated
- [ ] Confirm PM has opened a new ticket to deploy changes to Production using feature flag, if needed

## Validation
- Who can validate this ticket? (FE, BE, Design, PM)? PM or Design
- How can this work be validated? Staging
- What updates need to be made (e.g. product outline, use cases, contact center guide)

## Associated Tickets
-  #49845

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by SKasimow** [comment]
Personal info/FAQ:
![Screen Shot 2022-11-18 at 1.50.47 PM.png](https://images.zenhubusercontent.com/5fb57aafa11eae0592a15cb1/917d76b5-99bb-4520-a55a-7472e581489e)##

**Comment by SKasimow** [comment]
Screenshot for Military info/FAQ

![Screen Shot 2022-11-18 at 1.54.02 PM.png](https://images.zenhubusercontent.com/5fb57aafa11eae0592a15cb1/58bd880f-248f-4412-99a8-e5520da4504d)

**Comment by SKasimow** [comment]
@jcatergovy noted that you will also be working on #49843 as part of this ticket. LMK if we should bump on points.

**Comment by jcatergovy** [comment]
Updated the following TTY Links @cgednalske  @SKasimow :
Military Info FAQ
![image.png](https://images.zenhubusercontent.com/632e0024b571f3ae02607148/03910009-9d93-4a87-9949-8ceef6ab6c40)

Not In Deers Alert AND No Service History Alert
![image.png](https://images.zenhubusercontent.com/632e0024b571f3ae02607148/7a7c806b-ef21-4929-87ac-234214b755cf)

Personal Information FAQ
![image.png](https://images.zenhubusercontent.com/632e0024b571f3ae02607148/e79a7d13-4597-4201-9e2f-d6feb75eb9ae)

Direct Deposit - Fraud Victim Alert
![image.png](https://images.zenhubusercontent.com/632e0024b571f3ae02607148/cee031ec-ade9-4d82-aa48-3f9e3daa4f90)

**Comment by jcatergovy** [comment]
Forgot to screenshot the Not A Veteran Alert on Military Information Page
![image.png](https://images.zenhubusercontent.com/632e0024b571f3ae02607148/281dff84-b5ea-486e-8049-f54b2537af5a)

**Comment by jcatergovy** [comment]
Ignore the hanging sentence in the Military Info FAQ "If you have hearing..." that got fixed in a separate branch.

**Comment by cgednalske** [comment]
@jcatergovy thanks! The first DD214 sentence still uses sighted language with the mention of "seeing" and should be changed to the following instead:

> Some Veterans have reported that their military service information in their VA.gov profiles doesn’t seem right. 


For all our TTY: 711 links, we're supposed to include TTY in the link as well like below. Just double confirmed that with Danielle Thierry today. This is a relatively new update so there may be a lot of these TTY changes to make for us as well as other teams. @SKasimow not sure if we want to handle this now or turn it into a new ticket for all TTY use?
<img width="117" alt="Screen Shot 2022-12-01 at 1 24 17 PM" src="https://user-images.githubusercontent.com/79372956/205152272-8e91c7cd-838c-4488-b4c5-5d0d38bf501b.png">

**Comment by SKasimow** [comment]
@jcatergovy - is it easier to make the change to hyperlink all of TTY (per CG comment above) now across the board? 

Or if it means additional work we can change the 2 open tickets now (this and the #49385 Military FAQ update) and I'll open a backlog ticket.

**Comment by jcatergovy** [comment]
@cgednalske Good catch on the TTY link.  I made those changes and the sighted language and the ticket is ready for validation in staging.
@SKasimow

**Comment by SKasimow** [comment]
Looks good...closing
