### ISSUE TITLE
Skip Pre-Check-in Link if Demographics are Up-to-Date within 7 days of Appointment

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#49869]
## Background
See analysis of pre-check-in metrics [here](https://dsva.slack.com/archives/C022AC2STBM/p1668804662541959)

This ticket is to explore this recommendation from the analysis:
- Don’t send out pre-check-in links if all demographics are up to date for a patient within 7 days of the appointment

## Tasks
- Communicate and coordinate this effort with the PCI/API team
    - Prior to sending out a Pre-Check-in link, we should check the 3 demographics flags and if they are up-to-date and it is within 7 days of the appointment for which a Pre-Check-in link is being generated we should not generate the link

**Comment by acrollet** [comment]
I just want to highlight that this recommendation will change if and when we start doing things specific to individual appointments (like questionnaires) during pre-checkin.

**Comment by loripusey** [comment]
Got it. We can only make decisions based on what we know now and questionnaires is not something we know anything about at this point.
