### ISSUE TITLE
Load testing (authenticated endpoints) steps should be at parity with instructions

### ISSUE THREAD

**Issue by kfrz** [department-of-veterans-affairs/va.gov-team#4986]
## Background

These [directions](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/load-testing/auth-session-loadtest.md) instruct the reader to 

> Click "Build with Parameters" from the left side of the site"

However this does not appear on the linked Jenkins job page. 

This issue is for investigating and resolving this disparity.

cc @pjhill @kreek

**Comment by pjhill** [comment]
I suppose something must have shifted under our feet.  I admit that I'm a bit lost.  I'm not seeing any kind of on demand build options for any of the rake tasks including "Create load test sessions" in Jenkins.  Have we lost some kind of permission that allows a manual build to be triggered?

**Comment by kfrz** [comment]
That might be the case. I'll do some gumshoe work and see if there's a
trail of changes, also pinging @omgitsbillryan as he and Jenkins are pretty
good friends I think

**Comment by kreek** [comment]
Any update on this ticket?

**Comment by pjhill** [comment]
It seems that as part of GitHub Teams the [Jenkins permissions were tightened](https://github.com/department-of-veterans-affairs/va.gov-team/blob/697776c53c37d86dcf9603687d33c9c8d188c2f4/teams/vsp/teams/operations/product-outlines/github-team-automated-access.md#current-status) a bit.  Perhaps, that permissions tightening caused some changes user access to those build buttons.

**Comment by ricetj** [comment]
https://dsva.slack.com/archives/C0MQ281DJ/p1580333344021300
