### ISSUE TITLE
Add Product Definitions to Page

### ISSUE THREAD

**Issue by dmkosko** [department-of-veterans-affairs/va.gov-team#49879]
### I am a member of the Product Operations group and we recently put together some definitions related to a product, feature, and initiative. Ray Wang and Jason Woodward from Platform are also involved. We would like to know if the GitHub link to the definitions below can be added to the term glossary page of the VFS Directory?

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/octo/product/terms%20and%20definitions.md

**Comment by SSimmorins** [comment]
@dmkosko Thank you for submitting this ticket.  We are currently working on this request.

**Comment by dmkosko** [comment]
Thank you!

**Comment by SSimmorins** [comment]
@dmkosko A new page was created to combine both definition lists.  This ticket is now closed.  Here is the link to doc: https://vfs.atlassian.net/l/cp/7x2JWP79 
Thank you!

**Comment by vbellissimo** [comment]
@dmkosko Here is the published URL of the page @SSimmorins listed above: https://depo-platform-documentation.scrollhelp.site/getting-started/product-operations-terms-and-definition.

Thanks.

**Comment by dmkosko** [comment]
Thank you!

From: Vicky Bellissimo ***@***.***>
Sent: Tuesday, January 3, 2023 12:45 PM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Kosko, Daniel M. (GovernmentCIO) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Add Product Definitions to Page (Issue #49879)


@dmkosko<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdmkosko&data=05%7C01%7C%7C274c66cbb94e4eacd22008daedb23f5b%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C638083647067994654%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=PW2DGZ4S498JQaPXoIjS1MqshGPt%2FgJONvF4MixNQoE%3D&reserved=0> Here is the published URL of the page @SSimmorins<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSSimmorins&data=05%7C01%7C%7C274c66cbb94e4eacd22008daedb23f5b%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C638083647067994654%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=DnC2pu1J7lqmY5TtPgh6RP8E9EbBuItR4nFtwdZTf1w%3D&reserved=0> listed above: https://depo-platform-documentation.scrollhelp.site/getting-started/product-operations-terms-and-definition<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdepo-platform-documentation.scrollhelp.site%2Fgetting-started%2Fproduct-operations-terms-and-definition&data=05%7C01%7C%7C274c66cbb94e4eacd22008daedb23f5b%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C638083647067994654%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=O0MEwFUSJDbIoXudvL%2BWMIJo4Hh6AY6syjOf7ppmhHg%3D&reserved=0>.

Thanks.

-
