### ISSUE TITLE
Web content builds from the CMS get aborted when there is a pending commit

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#4988]
# User Story or Problem Statement
When there is a build happening on the vets-website master, the content build gets aborted.  

Ref: https://github.com/department-of-veterans-affairs/vets-website/blob/master/Jenkinsfile.content#L11

Ref(2): https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/Jenkinsfiles/deploys/warn-release-deploy#L39 (something we do for the daily deploy)
## Goal
_The build does not abort the content build_

## Acceptance Criteria
- [ ] _The build should not abort for non-red GH status_

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ricetj** [comment]
Original ticket / issue:
https://github.com/department-of-veterans-affairs/vets-website/issues/11487#issuecomment-574845750

**Comment by ricetj** [comment]
@ricetj add to epic

**Comment by ricetj** [comment]
@ElijahLynn Hey is this something that is still relevant? I know you made some changes this week.
