### ISSUE TITLE
[SPIKE] Determine feasibility of url shortener expansion 

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#49881]
## Use Case

Use our url shortener to handle the following scenario: 

- User submits travel claim via eCheck-in
- User gets text message to confirm their submission with a link to btsss
- The link in the text message is a shortened url. E.g., domain.gov/sub-directory/claim-number, or subdomain.domain.gov/claim-number which directs to https://dvagov-btsss.crm9.dynamics.com/ or a deep link (TBD by working with travel office). 

Text message will read: 

We received your travel claim for your VA appointment on MM/DD/YYYY. Your claim number is TC202207000011666.

You can check the status of your travel claim online 24/7 on the Beneficiary Travel Self Service System (BTSSS) through the AccessVA travel claim portal: https://xxx.

## Tasks

- [ ] Talk to Mikki Northuis to determine considerations and governance around what domain or subdirectories should be used for implementation. Specific concerns included linking .gov site to a .com site. 
- [ ] Identify decision, next steps and/or challenges. Route back to engineers and PO.

**Comment by benbrasso-agile6** [comment]
@loripusey we could pull this into next sprint

**Comment by benbrasso-agile6** [comment]
Messaged Mikki to set up meeting

**Comment by benbrasso-agile6** [comment]
Meeting scheduled

**Comment by benbrasso-agile6** [comment]
Determined that we want to take the vanity url approach, since we won't have unique information to pass through for each text message. @kellysmith1008  will go ahead and submit a request for a vanity url https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=RLHecht%2C+jilladams%2C+heyjoni&labels=Sitewide+IA&template=redirect-request.md&title=Redirect+Request

For example, we might use va.gov/accessva-travel-claim

We will need to link to the .gov domain here - https://eauth.va.gov/accessva/?cspSelectFor=oauth.BTSSS&targetPath508=cspSelectFor%3Dhttps%253A%252F%252Ffed.eauth.va.gov%252Fisam%252Fsaml20SPFed%252Fsaml20%26ForceAuthn%3Dfalse&foiaUrl=https%3A//www.va.gov/foia/&nonce=wAgV5olUxtVXF0HKzldSWFbceFooqprj

You can access that url from this page - https://www.va.gov/health-care/get-reimbursed-for-travel-pay/

**Comment by kellysmith1008** [comment]
Submitted request: https://github.com/department-of-veterans-affairs/va.gov-team/issues/50705
