### ISSUE TITLE
Staging: User stuck at a spinning load in VAOS UI when creating a new CC request 

### ISSUE THREAD

**Issue by aarathi-poldass** [department-of-veterans-affairs/va.gov-team#49888]
**Note: This issue is not related to VA Online Scheduling application code. This issue is related to HSRM, on the 11/21 HSRM technical call Anthony confirmed that there is an issue with the release 18.0 and 19.0 causing those errors. Anthony worked with the InterSystems HSRM team to get these issues resolved.**

## What happened?
Last week we had issues related to HSRM where we were seeing a 502 [VAOSR-4826](https://issues.mobilehealth.va.gov/browse/VAOSR-4826) error on the Devtools when creating a CC request this was due to not getting back appointment requests when we try to fetch them from HSRM. After Moshe fixed the issue, but when validated SQA encountrouded 2 new issues. Opened a JIRA ticket to track the progress [VAOSR-4887](https://issues.mobilehealth.va.gov/browse/VAOSR-4887)

After speaking to Thomas here is his analyzing - " I think the FE needs to investigate the other issues -
VetsApi is giving them a 404 on that facilities/create endpoint
Invalid provider NPI requests from mobile-ppms-service
 I do think we can fix mobile-ppms-service to handle the invalid NPIs more gracefully though. There is a bug that we should address with that. But the FE is sending a bad NPI for some reason and they should investigate why?"

## Specs:
- Browser: Chrome and Edge 
- Test User _(if applicable)_: patient999@id.me and grethel.g.petryniec@id.me

## Steps to Reproduce

- Login into VAOS as [grethel.g.petryniec@id.me](mailto:grethel.g.petryniec@id.me)
- Click on "Start Scheduling"
- Select any type of care supported by Community Care (ex:- Audiology – Routine hearing)
- Select a preferred provider/ preferred date and additional comments
- Fill in all the required data and create a request

**Expected Results:** System should create a new CC request 

**Actual Results:** System is a stuck at a spinning load and Devtools is displaying errors 

**404 error-**
**Request URL:** https://staging-api.va.gov/vaos/v2/facilities/create
**Response:** {"errors":[{"title":"Not Found","detail":"The resource could not be found","code":"VAOS_404","source":{"vamfUrl":"https://internal-dsva-vagov-staging-fwdproxy-1821450725.us-gov-west-1.elb.amazonaws.com:4463/facilities/v2/facilities/create","vamfBody":"{\n \"code\" : 404,\n \"message\" : \"HTTP 404 Not Found\",\n \"traceId\" : \"91d58bcdf28a38dbbbb0f1473ea1d278\"\n}","vamfStatus":404},"status":"404"}]}

**502 error-**
**Request URL:** https://staging-api.va.gov/vaos/v2/providers/00
**Response:** {"errors":[{"title":"Bad Gateway","detail":"Received an an invalid response from the upstream server","code":"VAOS_502","source":{"vamfUrl":"https://staff.apps-staging.va.gov/ppms/v1/providers/00","vamfBody":"{\"code\":500,\"message\":\"A server error occurred\",\"id\":\"6a611d55-0b9d-4a95-9075-4c6d690c35ba\",\"traceId\":\"280174c66e056ee959713e5ab0daebd0\"}","vamfStatus":500},"status":"502"}]}

![image](https://user-images.githubusercontent.com/69315717/203117153-d8fe6b9e-b3a4-4703-a195-34b6c36eb283.png)

**Note:** Even though VAOS is throwing errors the request is being transferred to HSRM successfully. Triage steps - tried the above steps with multiple test users, Multiple type of care, cleared cache tried and seeing the same issue across the board.

**Comment by marcynadeau** [comment]
On the HSRM integration call.  Anthony Pilozzi, Moshi and Thomas Joyner are saying there is an issue with the upgrade of InterSystems HSRM that most likely is impacting this error.  They are advising us to hold tight until InterSystems is able to resolve their issues.

**Comment by aarathi-poldass** [comment]
Follow up email from Grace - "Just wanted to follow up and see if you heard any feedback regarding how long HSRM vendor would take to fix the known bug?"

Reply from Anthony - "They are engaged and we’re hoping it will be resolved today/tomorrow. (Although we won’t be sure until its over.)"
