### ISSUE TITLE
Best bet request for Disability compensation rates

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#49897]
# Template Instructions
- You are here to creation or change a Best Bet on VA.gov pages.
 -  Select Request Type:
    - [x] NEW: You would like to create a new best bet
    - [ ] CHANGE: You would like to change an existing best bet
- Complete the corresponding section below to provide the relevant details  *(Section 1- New Request or Section 2-Change Request)*
- Post a link to this issue in Slack Channel #va-search with tag for  @Joni Chan

# Section 1: New Request

### Description
*Please provide a brief description of the initiative and supporting information for the creation of a best bet.*  
>During usability research for the VA.gov homepage, we discovered a few tasks which were challenging for Veterans and beneficiaries to complete from the homepage. Adding best bets will support discoverability and task completion. 

###  Completion Dates
 *Do you have any target  dates we should be aware of?*
> date/time: If the year should be included, the timing may depend on when 2023 rates become available.
 
 ### Please provide the following information:

 - [x] Specify the **Headline** for the Best Bet 
> `(year)` Veterans disability compensation rates

 - [x] Specify the **Text** for the Best Bet 
> Review  `(year)` Veterans disability compensation rates. Use our compensation benefits rate tables to find your monthly payment amount. 

 - [x] Specify the  **Keywords** that would generate the Best Bet 
> Open to guidance from content team. This task is relevant to Disability compensation. Suggest including common misspellings for "disability" such as "disibility" as we saw participants try to search for it this way during research sessions. 

 - [x] Specify the **URL** for the Best Bet 
> https://va.gov/disability/compensation-rates/veteran-rates/
      

***Note: These requests are handled by the Sitewide Content and IA team. Reach out via Slack #sitewide-content-ia with any questions.***

**Comment by mmiddaugh** [comment]
[Best bets export](https://app.zenhub.com/files/133843125/24eb3f2b-9b9e-47a6-8c8b-9d90471d1322/download)

**Comment by mnorthuis** [comment]
@mmiddaugh Can you please provide more detail on the research leading to this request? 
- Which specific research effort was this?  Please add link to the findings. 
- What was the task the participants were given? What language/terminology was used in the task?

There are a number of best bets in play around Disability and compensation, so they will need to be reviewed to ensure each one is getting at the right ultimate landing page.  A keyword like "disability" could lead to a number of critical pages within that benefit area, so we will need to be specific so we aren't driving everyone to rates when what they want is to know their personal rating or how to apply or what they're currently receiving.

**Comment by jennymayoco** [comment]
Hi @mmiddaugh, we reviewed a variation of terms (`compensation rates`, `disability rates`, `disability ratings`, `rating table`, `disability compensation rates`) and found that the current disability rates page shows up on the first page and within the top 5 results. When searching just `disability` on its own, the current disability rates page also shows up in the first page (6th result down). Based on these search results and additional analytics on page performance, I think this page is good to go without any additional best bets at this moment.Let me know if there any questions or other keywords we can explore.

#### Analytics over the last 6 months (3/1/23-9/12/23)
- Page views: 5,620,981
- Bounce rate: 0.87%
- Entrance rate: 37.77%
- Top previous pages:
    - [Compensation rates](https://www.va.gov/disability/compensation-rates/) - 35.76%
    - [Rates index page](https://benefits.va.gov/compensation/rates-index.asp) - 10.90%
    - [About disability ratings](https://www.va.gov/disability/about-disability-ratings/) - 7.54%
    - VA homepage - 5.93%
    - [2022 compensation past rates](https://www.va.gov/disability/compensation-rates/veteran-rates/past-rates-2022/) - 5.89%
- Top 5 VA.gov searches leading to the requested landing page
    - disability rates - 405 clicks
    - disability compensation rates - 281 clicks
    - disability ratings - 246 clicks
    - rating table - 241 clicks
    - compensation rates - 195 rates
