### ISSUE TITLE
Best bet request for "View your payment history"

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#49893]
# Template Instructions
- You are here to creation or change a Best Bet on VA.gov pages.
 -  Select Request Type:
    - [x] NEW: You would like to create a new best bet
    - [ ] CHANGE: You would like to change an existing best bet
- Complete the corresponding section below to provide the relevant details  *(Section 1- New Request or Section 2-Change Request)*
- Post a link to this issue in Slack Channel #va-search with tag for  @Joni Chan

# Section 1: New Request

### Description
*Please provide a brief description of the initiative and supporting information for the creation of a best bet.*  
>During usability research for the VA.gov homepage, we discovered a few tasks which were challenging for Veterans and beneficiaries to complete from the homepage. Because of the redesign, some links will no longer be displayed on the body of the homepage. Adding best bets will support discoverability and task completion. 

###  Completion Dates
 *Do you have any target  dates we should be aware of?*
> date/time: The redesigned homepage will be soft launched in December 2022 and should replace the current/existing homepage in January 2023. 
 
 ### Please provide the following information:

 - [x] Specify the **Headline** for the Best Bet 
> View your payment history

 - [x] Specify the **Text** for the Best Bet 
> Find out how to view your VA payment history online.

 - [x] Specify the  **Keywords** that would generate the Best Bet 
> Open to guidance from content team. This task is relevant to Disability compensation, Pension benefits, and Education benefits. 
> Suggest including common misspellings for "disability" such as "disibility" as we saw participants try to search for it this way during research sessions. 

 - [x] Specify the **URL** for the Best Bet 
> https://www.va.gov/va-payment-history/
      

***Note: These requests are handled by the Sitewide Content and IA team. Reach out via Slack #sitewide-content-ia with any questions.***

**Comment by mmiddaugh** [comment]
[Best bets export](https://app.zenhub.com/files/133843125/24eb3f2b-9b9e-47a6-8c8b-9d90471d1322/download)

**Comment by heyjoni** [comment]
Hi @mmiddaugh, the "View your payment history" page is already showing up first in searches for "payment history" and in the top 3 for "compensation history" and "benefits history," so I think it's good to go in search.

I was considering making it a best bet for "compensation history" and "benefits history", but people might also expect to see other results (benefit letters, etc.) rather than just payments. Let me know if you have other terms you'd like me to look into.

**Comment by mnorthuis** [comment]
@mmiddaugh Can you please provide specific research efforts and findings to this request as well? Would also like to know how much that link was clicked from the home page before it was removed as some indication that it was a primary entry point.
