### ISSUE TITLE
Update Standard Operating Procedures

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#499]
----

This issue tracks ideas for devops operational readiness with a focus on likely exceptional/bad situations, and how to mitigate them and prepare for them. Everybody should feel free to edit or comment with additional ideas. While we can sit around dreaming up scenarios all day, I think we can come up with a reasonable list based on our collective devops and application support experience.  The end result will spawn off separate issues to develop SOPs and associated tooling so that we are not caught short without any way of fixing issues that arise.

Some starter items:
- Critical bug found in OS-level package. Need ability to scan all environments for presence of problem package. Need ability to upgrade all environments.
- Critical bug found in app framework module (e.g. Ruby Gem). Need ability to scan all environments for presence of module. Need ability to upgrade all affected environments.
- Application bug in production requires rollback to known working version. Need ability to rollback to an identified working version. 
- Database corruption in application database. Need ability to restore application database to a previous snapshot. 
-  Trusted SSH private key compromised (e.g. laptop stolen). Need ability to revoke an individual key across all environments.
- Unknown application performance degradation. While no general purpose tooling will help with this overall problem, we need to at least have a reference topology/system diagram for each application so we know what kind of app it is, what it touches, etc. so that the early tiers of support know where to look.

**Comment by ricetj** [comment]
Further conversations are found here: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/1546

**Comment by rtluu** [comment]
hey @ricetj, I'm unfortunately going to need to pass this off. I've connected with @andreahewitt-odd about this, but I think this is still a bit of a question mark in terms of what work needs to be done by the `product-support` team. I'm going to lean on you two to discuss and coordinate how to best tackle these changes

**Comment by andreahewitt-odd** [comment]
@ricetj Let's chat about this when you come back from vacation.

**Comment by rroueche** [comment]
I think a lot of the bullets here have been incorporated into Operations tasks and are being worked on or in the backlog already, I don't really see anything that would fall under the Product Support team's scope,  but @ricetj and @andreahewitt-odd should discuss at some point and decide if there are things from this ticket that still warrant attention.

**Comment by ricetj** [comment]
@ricetj  to talk to @fowusu2 about these

**Comment by jbritt1** [comment]
Is this work still relevant? Have we achieved all we set out to accomplish in this body of work at this time? If so, can this be closed? If not, can we update with relevant, current data/info? CC @jhouse-solvd

**Comment by jhouse-solvd** [comment]
This issue can be closed. Many of these items are addressed by ongoing ATO tasks and/or platform documentation as a whole.
