### ISSUE TITLE
Design Intent - Design Feedback - Modernized Check-in Simplified VA Header/Footer

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#49909]
## VFS acceptance criteria
- [x] Let Platform know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [x] VFS team closes the ticket

## Thoughts/questions
- Great work!
- The header/footer was discussed at the DSC meeting on 11/18. Final decision: proceed with testing and report back to Patrick about having a conversation around legal requirements in footer. Patrick and Dave can have conversation.
- The progress bar was also discussed at the DSC meeting on 11/18. Since this will not be going into production for awhile, revaluate when we are closer to a launch date. Consider what USDS is currently using.
- [Full DSC meeting notes](https://docs.google.com/document/d/1_4iYiEi2jtuWBz5eVi6NVeokcX7h8R3Zqs2FKM63pk0/edit#)

## Feedback
- Practice areas will document their feedback following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback).

**Must:**
- Follow the [contributing to the design system](https://design.va.gov/about/contributing-to-the-design-system/) for new components.

**Should:**

**Consider:**

## Platform directions
- Remove the governance-team label
- Update "Issue Title"
- Link to collab cycle Request epic
- Add your feedback
- Remove the CC-Request label (only if you created the ticket using the New Issue link from the Collaboration Cycle Reviews board)
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review QA Only**: VFS PM, yourself (optional)

**Comment by benbrasso-agile6** [comment]
Added @acrollet to this ticket, as we may want to add code into the documentation, but we won't be there for a couple more sprints

**Comment by benbrasso-agile6** [comment]
Ben to start draft for ds component

**Comment by benbrasso-agile6** [comment]
@kristenmcconnell Drop that experimental ticket in here when done and close, please

**Comment by kristenmcconnell** [comment]
Here is the [header](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/1425) pull request.

**Comment by kristenmcconnell** [comment]
Here is the [footer](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/1431/commits/22f7b5c090a4138d9eb8af40615105531c5ddac0) pull request.

The header and footer pull request will be discussed at the 1/20 Design System Council meeting.
