### ISSUE TITLE
Redesign detail pages

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#49900]
## Task Description
* Improve the hierarchy, readability, and consistency of current details pages
   - Improve "Add to calendar" feature
* Work with sitewide content to standardize language
* Create a testable prototype

## Resources
[Link to Designs](https://www.figma.com/file/RcDljBwThbwVDkNrDH2xiA/Appointment-Details-Redesign?type=design&node-id=1634%3A61152&mode=design&t=Vuib6NulfUIVd67O-1)
[Link to Content Matrix](https://www.figma.com/file/RcDljBwThbwVDkNrDH2xiA/Appointment-Details-Redesign?type=design&node-id=1631%3A60572&mode=design&t=wJZ5XdUUQejQUYWS-1)

## Acceptance Criteria
- [ ] Testable prototype of detail pages
     - [ ] All appointment types are accounted for
     - [ ]

**Comment by Cieramaddox** [comment]
Working on [new alert patterns ](https://www.figma.com/file/RcDljBwThbwVDkNrDH2xiA/Appointment-Details-Redesign?node-id=1105%3A37331&t=2Wpg7q6017HyFrB3-1)

Exploring [Add to Calendar ](https://www.figma.com/file/RcDljBwThbwVDkNrDH2xiA/Appointment-Details-Redesign?node-id=1105%3A37352&t=2Wpg7q6017HyFrB3-1)

Reformatting[ old details pages](https://www.figma.com/file/RcDljBwThbwVDkNrDH2xiA/Appointment-Details-Redesign?node-id=1026%3A26769&t=2Wpg7q6017HyFrB3-1)

**Comment by outerpress** [comment]
Not prioritized for PI 8, moving to Icebox

**Comment by Cieramaddox** [comment]
Testing on hold as we explore adding pre check-in to appointments. [Ticket #67120](https://app.zenhub.com/workspaces/appointments---productdesign-5fff340c2d80a4000fb6f69c/issues/gh/department-of-veterans-affairs/va.gov-team/67120)

**Comment by outerpress** [comment]
[CAIA ticket for this work](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63219)
