### ISSUE TITLE
BE | Profile | Personal Information returning 400 Bad Request

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#49901]
## Background
For staging user 82, the Personal Information section is displaying "We can't load all your information" alert at the top of their profile.

The `v0/profile/personal_information` endpoint is returning the data, but with a status of `400 Bad Request` which is causing the FE to ignore the response and display the alert.

## Tasks
- [ ] Determine why the response status is `400 Bad Request`.

**Comment by tpharrison** [comment]
The response from VA Profile contains a 400 status code.  Here is the body...
```
{
  "messages": [
    {
      "code": "MVI201",
      "key": "MviNotFound",
      "text": "The person with the identifier requested was not found in MVI.",
      "severity": "ERROR",
      "potentiallySelfCorrectingOnRetry": false
    }
  ]
}
```

In discussion with VA Profile team...

**Comment by tpharrison** [comment]
Ian McEwan from VA Profile looked into this.  His response...
> _Its an identity issue, I cant tell you why MPI marked the user ID as "PCE" (potentially catastrophic edit).  I would be skeptical they will fix it.  You'll probably need them to tell you why they marked it as PCE and if they can undo that._

So the user record is invalid and we'll need to follow up with MPI to determine why. 

@Samara-Strauss do you want me to reach out to MPI?  If so, who is the best person to contact?

cc/ @SKasimow

**Comment by Samara-Strauss** [comment]
Thanks for digging into this, Tom. I messaged Danny Reed to ask who we should talk to.
