### ISSUE TITLE
Complete the sitewide content and IA intake request process

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#49918]
## Tasks
- Complete the sitewide content and IA intake request process

**Comment by benbrasso-agile6** [comment]
Closing this ticket. Will add notes from my conversation with Danielle to Zach's ticket https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/49891
