### ISSUE TITLE
Prod: VAOS v2 - Pending queue displaying an error in the UI 

### ISSUE THREAD

**Issue by aarathi-poldass** [department-of-veterans-affairs/va.gov-team#49914]
## What happened?
During the Production testing with Alaska on 11/16 we found that the after the user submits a request and navigated back to the VAOS home page and accessed the “Pending” queue the UI is displays an error "We're sorry. We've have run into a problem. Something went wrong on our end. Please try again later". 

When SQA brought this issue up with Simi he mentioned "(https://dsva.slack.com/archives/CMNQT72LX/p1668628497559829?thread_ts=1668628208.867159&cid=CMNQT72LX)
 - **We are working on resolving the issue with pending appointments**."

## Specs:
- Browser: Edge 
- Test User _(if applicable)_: Heather (Alaska Veteran/staff tester) 

## Steps to Reproduce
- Login to VAOS
- Click on “Start Scheduling”
- Select the type of care (Ex- Audiology, Optometry, Food and Nutrition, Primary care, Podiatry)
- Fill in the required fields and follow steps to create a CC request
- Create a CC request
- Then user navigates to VAOS Home page
- On the home, select the "Pending" queue

Expected Results - Newly created CC requests should display under the "Pending" queue

Actual Results - System is displaying an error in the UI "We're sorry. We've have run into a problem. Something went wrong on our end. Please try again later" and no errors displayed in devtools

**Comment by aarathi-poldass** [comment]
@ldelacosta @simiadebowale creating this ticket to track the prod issue.

**Comment by aarathi-poldass** [comment]
@simiadebowale Please let us know when we can expect the changes to be pushed to production? We can coordinate with Marcy and validate the fix once deployed. Thank you!

**Comment by ldelacosta** [comment]
@aarathi-poldass - This should be available in production as long as the feature toggle is turned on for `acheron_service`

**Comment by aarathi-poldass** [comment]
This ticket cannot be validated due to the 502 error in production. A user is encountering an error when creating a CC request in VAOS V2. Here is the ticket number [VAOSR-4889](https://issues.mobilehealth.va.gov/browse/VAOSR-4889). We have identified this issue is triggering from HSRM side and they are currently working with their intersystem team on a fix. Will resume testing once the HSRM issues is resolved.  @ldelacosta @simiadebowale

**Comment by aarathi-poldass** [comment]
Validation completed on 11/31 in production. This ticket has now been resolved, VAOS is incrementing the pending request count correctly when a new request is created and users are now able to access the pending queue without any errors.@ldelacosta Please close the ticket. Thank you!

**Comment by ldelacosta** [comment]
No issues reported. Closing out the ticket.
