### ISSUE TITLE
AWS access for Lucian Snare

### ISSUE THREAD

**Issue by lsnare** [department-of-veterans-affairs/va.gov-team#49934]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Lucian Snare

### Your Email

lucian.snare@adhocteam.us

### Team, Role, and Company of the target individual

Firefly on Lighthouse, Software Engineer, Ad Hoc LLC

### Product Manager (PM) name and email

Kayla Watanabe, kayla.watanabe@va.gov

### Product Owner (PO) name and email

Janet Coutinho, Janet.Coutinho@va.gov

### Desired AWS Access

Please copy same permissions as teammates Jennica Stiehl, Jeff Wallace.

### Access Expiration

Ongoing

### Additional Notes

I need this access for ongoing development work on the Benefits Claims API.

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by rmtolmach** [comment]
✅ Lucian is in the VFS roster

### For AWS ACCESS
User: Lucian Snare
COR: Cecila Lee
VOR: Liberty IT - Michael G. Lovejoy
Approval needed: @department-of-veterans-affairs/operations-aws-approvers 
AWS Admin Role: no

>Please copy same permissions as teammates Jennica Stiehl, Jeff Wallace.

Those permissions are: `["lighthouse-developers", "dvp-developers", "force-MFA"]`

@lsnare, an AWS approver will verify this information and comment on the ticket when you have been approved. Then, Platform Support will open a PR to grant you access. They will close this ticket when that is complete. In all, this can take a few weeks.

**Comment by td-usds** [comment]
Reached out to VOR
