### ISSUE TITLE
Vets-API Server with EKS to Dev: VFS Facing Documentation

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#49959]
**PROBLEM STATEMENT**
We need VFS facing documentation to account for 
(a) all the steps in the migration process
(b) necessary diagrams
(c) anticipated maintenance items, including any know timeframes

**DEFINITION OF DONE**
Documentation is complete for the following:
- [x] Manifest Files: All of the necessary files for the deployment will exist in the appropriate repo
- [x] Software Repositories:(1)Necessary infrastructure exists so app (vets-api server) can exist within EKS
(2)Vets-api server is packaged so the app can exist in the EKS environment (3)ECR repo exists (4)Docker file exists in the primary app repo
- [x] CI/CD tools and pipelines: (1)GHAs exist that will build the images and push to ECR (2)ArgoCD configuration that will auto-sync the app
- [x] Container registry: A registry exists for the specific images in ECR pertaining to the app
- [x] Container Orchestration: EKS works automatically by unifying the infrastructure components
- [x] Deployment Management: ArgoCD provides a UI for developers to see the application and manages the deployment by checking the desired state against the deployed state (auto-syncs when needed)

**Comment by LindseySaari** [comment]
[A VFS facing doc was created here](https://vfs.atlassian.net/wiki/spaces/TT1/pages/2444263592/Vets+API+EKS+in+the+dev+environment+External) in Confluence
