### ISSUE TITLE
DEV Testing Discovery

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#49950]
**PROBLEM STATEMENT**
In order to appropriately prepare for testing, some discovery work needs to be completed to better understand (a) limitations with testing in the dev environment, and (b) what data and users are available for testing.

**DEFINITION OF DONE**
- [x] Dev testing limitations are [documented in confluence](https://vfs.atlassian.net/wiki/spaces/TT1/pages/2441478145/Testing+Discovery+scoped+to+dev)
- [x] Potential data and users for dev testing are [documented in confluence](https://vfs.atlassian.net/wiki/spaces/TT1/pages/2441478145/Testing+Discovery+scoped+to+dev)

**Comment by laineymajor** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/platform-tech-team-1-633af4074573d06c3cda142a/issues/department-of-veterans-affairs/va.gov-team/49950?planning-poker) with Zenhub @LindseySaari @considerable @RachalCassity

**Comment by LindseySaari** [comment]
Update for 11/28: I started on [the discovery doc here](https://vfs.atlassian.net/wiki/spaces/TT1/pages/2441478145/Testing+Discovery). 

Next steps: Investigate faraday connection code that calls betamocks and research test users

**Comment by laineymajor** [comment]
Is it appropriate to add "Investigate faraday connection code that calls betamocks and research test users" to our next sprint? Or is this complete? Thanks @LindseySaari !!

**Comment by LindseySaari** [comment]
> Is it appropriate to add "Investigate faraday connection code that calls betamocks and research test users" to our next sprint? Or is this complete? Thanks @LindseySaari !!

I believe I investigated that to the best of my ability (without going too in depth for the initial discovery) The table at the bottom of the doc details the betamocks/faraday connection

**Comment by laineymajor** [comment]
closing as this discovery is complete
