### ISSUE TITLE
Documentation | Profile | Update CC guide for notification settings section

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#49962]
The call center guide still has the old screenshots with the input message for notification settings. Need to update the screenshots + content to reflect our latest change.

**Comment by andaleliz** [comment]
Complete

**Comment by SKasimow** [comment]
Liz - this notification settings page has an update we haven't put into production yet (the one for the mobile number we were talking about earlier today). We should wait until the changes are live before updating the documentation (I'll make a note that Notification settings was updated but not live yet in the Product Guide - just in case we need to send out before the change is implemented). Also, could you use the edit function when you add screens/text in the future - makes it much easier for us to see exactly what you changed...thanks!
