### ISSUE TITLE
Reasons why digital forms are superior to PDF Forms

### ISSUE THREAD

**Issue by tbaker1026** [department-of-veterans-affairs/va.gov-team#49970]
We probably do want to write up a similar list of reasons we find a digital form to be superior to a PDF form. We also need reasoning for why we believe that a VFS Team is not necessary for certain categories of forms. 

[Link to UK Findings](https://gds.blog.gov.uk/2021/11/17/why-we-think-online-html-forms-are-usually-better-than-document-based-forms-in-government/)

**Comment by tbaker1026** [comment]
- Most participants ignored instructions
- Forms opened in browsers that caused problems (and aren't fillable)
- Most participants couldn't sign the form without help from the moderator
- Screen reader users were unable to sign the PDF in acrobat
- Mobile device users could not fill out a form from their mobile device.

**Comment by jeana-adhoc** [comment]
[Working document](https://docs.google.com/document/d/1TnbABszhtzTzBW-OSNujtOkjU_4FAJSTqnfeBScPGSY/edit?usp=sharing) (Google Doc - You'll need to request access, but I'll give it)

**Comment by jeana-adhoc** [comment]
**Draft**

**Why VFS teams aren’t always required for form creation**
Dependent upon findings of the audit.

**Assumption:** A certain number of forms are considered “simple”, and could be generated with a script or with minimal development, and don’t need a VFS team (or business unit involvement).

**How is this possible?**
- (insert definition of simple forms)
- These forms have minimal fields
- These forms currently have solutions/components in forms library
- There are common/repeated fields across many forms
- The forms team has received pre-approval from content/collab cycle on these common/repeated fields.
- There is approval/agreement to lift/shift content from the PDF for fields that are not pre-approved. This means there is no change to content that the business unit needs to agree on and no content team to seek approval/guidance from.
- Forms are launched as MVPs—which means the form may not follow all of the established best practices and guidance published by OCTO/Platform.

**Guarantees**
- All forms developed in this way will submit via central mail reducing the delivery time to the business unit by 2 days.
- All digitized forms will meet 508/Accessibility Compliance

**Working in this way would remove the following aspects of form creation:**
- Veteran Testing
- Most Plain Language Improvements
- Most of the Collab cycle 
- Working with Stakeholder/business units to improve the language/User experience of the form
