### ISSUE TITLE
Rework content about SBP/DIC offset on DIC rates for spouses and dependents page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#49985]
## Issue Description
The SBP/DIC offset is being eliminated on January 1, 2023. We have content on our [DIC rates for spouses and dependents](https://www.va.gov/disability/survivor-dic-rates/) page that will need to be reworked so that the information is in the past tense after January 1. We might want to consider changing this content into a note about how the offset was phased out.

![Screen Shot 2022-11-23 at 8.36.00 AM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/3d09edcc-0898-4a48-a1f4-ab9f208bce82)

We will need to revise the content and share with stakeholders before publishing. 

## Tasks
- [x] Rework content
- [x] Review (Laura)
- [x] Send to stakeholder for approval
- [x] Copyedit (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] Reworked content is live on the site

**Comment by laurwill** [comment]
Hi @megzehn , this was a straightforward change so I went ahead and updated the Drupal node. 
Ready for your copyedit before we send to stakeholders for approval: http://preview-prod.vfs.va.gov/preview?nodeId=1012 
Only edits are to the last section at bottom under horizontal line.

**Comment by megzehn** [comment]
Thanks, @laurwill! Confirming that I copy edited the changes on this page, and it's ready for you and the stakeholders.

**Comment by laurwill** [comment]
Noting that Randi sent this to SME Angie for approval on Friday 12/16.

**Comment by laurwill** [comment]
Hi @megzehn , we made edits to this note after SME feedback. Can you plan to do a final edit and publish on January 3?
http://preview-prod.vfs.va.gov/preview?nodeId=1012

**Comment by megzehn** [comment]
Thanks, @laurwill! I looked over this again, and it's ready to go on Jan 3. I'll plan to publish it in the a.m.!

**Comment by megzehn** [comment]
Confirming that this page is now published. Thanks!

**Comment by megzehn** [comment]
@RLHecht, I think this is ready to close? 

CC @laurwill for awareness

**Comment by RLHecht** [comment]
These changes are live. Closing ticket!
