### ISSUE TITLE
VAOS::V2::CinicsController: GET clinics when paging is not passed in does not return all clinics

### ISSUE THREAD

**Issue by ajmagdub** [department-of-veterans-affairs/va.gov-team#49996]
Currently when getting clinics no paging information is being sent to VAOS Service. VAOS Service defaults to only sending the first page no paging information is being sent. We want the default to be to return all clinics. To set that as default we must pass a page size of zero to VAOS Service

**Comment by ldelacosta** [comment]
Per update from @cferris32 - the PR for the changes was merged this morning.

**Comment by ldelacosta** [comment]
Changes were pushed out to production as of 11/30/22

**Comment by ldelacosta** [comment]
[No issues reported in production](https://dsva.slack.com/archives/CMNQT72LX/p1669661245199619). Closing out the ticket.
