### ISSUE TITLE
OOB Deploy Request: vets-website

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-team#50009]
# Instructions
Fill out Details of need and the PRs related to OOB sections below.

## PRs Related to OOB
- Please provide the list of PRs related to the need for this OOB Deploy
   > [https://github.com/department-of-veterans-affairs/vets-website/pull/22769

Updated PR: https://github.com/department-of-veterans-affairs/vets-website/pull/22770

Related slack thread: https://dsva.slack.com/archives/CBU0KDSB1/p1669237881425029

## Active Daily Users Impacted
- How many active users are impacted at this time and day.
>   118,387 TOE (1990e) annual users,  4,173 FRY deps also used the 5490 annual users.  When added to the 167,567 ch35s, the total is 171,740 (5490).   
Several active reports of users sent to incorrect forms today as a result of the changes we would like to roll back.

## Has fix been confirmed in Staging?
- [ ] Yes
- [X] No - not yet, not merged as of time of cutting this ticket. Tested locally, PR is still in testing / code review / approvals.

## Description
- Please provide the details/reason for the OOB Deploy
   > Yesterday PW merged changes to reverse the order of questions in the Education How to Apply wizard (https://www.va.gov/education/how-to-apply/). We missed a link change, and users are being directed to incorrect forms as a result. We want to roll back yesterday's change and roll forward a fix after the holiday.
   
## Verify The following
 - [X] The OOB Deploy Requests is after the 2pm EST cutoff for regular deploy - [Deployment Policy](https://vfs.atlassian.net/wiki/spaces/SUP/pages/1279787009/Deployment+Policies) and [Deployment Schedules](https://depo-platform-documentation.scrollhelp.site/developer-docs/Deployments.1844641889.html)
 - [X] The OOB Deploy Requests is critical and must be resolved before the next automated deploy.

*Performed by Platform SRE team*
 - [x] PagerDuty OOB Deploy Incident Opened
 - [x] OCTO-DE staff acknowledgment of Request
 - [x] Notification is posted in the appropiate Slack support and team Channels
 - [x] Infrastructure/Operations has acknowledge the Requests
 - [x] Security Team has Reviewed the requests
 - [x] An Incident Post Mortem is created within two business days

 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-product-support

**Comment by jilladams** [comment]
Original PR hit some problems, so we're trying in a new PR: https://github.com/department-of-veterans-affairs/vets-website/pull/22770

**Comment by jilladams** [comment]
Merged! https://github.com/department-of-veterans-affairs/vets-website/pull/22770

Ready for deploy.

**Comment by powellkerry** [comment]
Link to postmortem pull request: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/645
