### ISSUE TITLE
AWS access for Raina Huerta

### ISSUE THREAD

**Issue by rd-huerta** [department-of-veterans-affairs/va.gov-team#50002]
### COR Name

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Raina Huerta

### Your Email

raina.huerta@thoughtworks.com

### Team, Role, and Company of the target individual

Virtual Agent Chatbot, developer, thoughtworks

### Product Manager (PM) name and email

Ian Santarinala ian.santarinala@thoughtworks.com

### Product Owner (PO) name and email

Luciana Morais Luciana.Morais@va.gov

### Desired AWS Access

- I would like to inspect secrets stored in Parameter Store in AWS. I may need to update secrets as we add new pipelines.
- I want to have access to vets-api-server log group so I can understand the identifiers that are being sent to EVSSClaims in order to build an integration with the Chatbot.
- I require terminal access to the development instance of vets-api
- Similar permissions as [kha.huynh@thoughtworks.com](mailto:kha.huynh@thoughtworks.com) && [justin.trieu@thoughtworks.com](mailto:justin.trieu@thoughtworks.com)

### Access Expiration

ongoing

### Additional Notes

COR: Patricia Pierre-Louis

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by rmtolmach** [comment]
✅ On the VFS Roster

### For AWS ACCESS
User: Raina Huerta
COR: Patricia Pierre-Louis
VOR: Liberty IT - Michael G. Lovejoy
Approval needed: @department-of-veterans-affairs/operations-aws-approvers 
AWS Admin Role: no

> Similar permissions as kha.huynh and justin.trieu 

`["dsva-vfs-developers", "vfs-virtual-agent-team", "force-MFA"]`

@rd-huerta Next step to to wait for approval! After approval, someone will grant your access. This can take a few weeks.

**Comment by td-usds** [comment]
Reached out to VOR

**Comment by td-usds** [comment]
Requested access (see https://github.com/department-of-veterans-affairs/va.gov-team/issues/50002#issuecomment-1325541697) approved
