### ISSUE TITLE
Staging: VistA Scheduling Service  Not Returning VA Appointments - Need Message to Vet that not all appts are displaying

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#50012]
Steps to recreate:  Not really sure we can recreate and as I happened to notice this and not sure how we would disable VistA Scheduling Service (VSS).  Need to talk to Brad to find out if there is any way in staging to temporarily disable VSS so we could test a fix on this.  

**Steps to recreate**
1.  Have VSS disabled. Video Visit Service (VVS) is working.  
2. Log into VAOS with patient that has upcoming VA and VCM appointments.  VA appts come from VSS and VCM appointments come from VVS.  cecil.morgan@id.me
3.  Home page displays
4.  Response Expected:  VA and Video appointments display
5.  Response  Seen:  Only Video appointments display.  Response body indicates  "Could not retrieve appointment slots from VistA Scheduling Service (dd34523f-cd16-4b91-b343-4e869f099e86)",  https://staging-api.va.gov/vaos/v2/appointments?_include=facilities,clinics&start=2022-10-24&end=2023-12-23&statuses[]=booked&statuses[]=arrived&statuses[]=fulfilled&statuses[]=cancelled

**End User Impact:** 
Veteran is not seeing complete list of appointments and could miss appointments.  

**Environments, users, and patients tested in:**
chyshr.  cecil.morgan@id.me

**Versions Tested:** 
vaos/acheron-service 1.2.0
vaos-service 1.24.4
[https://app.zenhub.com/files/133843125/76118769-cbf7-4c0a-aa7c-15137f583290/download](https://app.zenhub.com/files/133843125/76118769-cbf7-4c0a-aa7c-15137f583290/download)

**Comment by ldelacosta** [comment]
We will need to review what message we want to display to the Veteran if this use case happens. @outerpress @simiadebowale

**Comment by ldelacosta** [comment]
@simiadebowale - Can you let us know how the FE will implement an alert message when VSS is down. 

@outerpress - We can work on the message to alert the Veteran that the `in person appointments` may not be listed in VAOS.

**Comment by ldelacosta** [comment]
Working ticket #50362. @marcynadeau as discussed, since we cannot replicate the issue in staging, the dev team will do a unit test based on the response returned from when you tested the ticket.

**Comment by ldelacosta** [comment]
@marcynadeau - We handled the fix in #50362. Closing out the ticket. Thanks.
