### ISSUE TITLE
Questions about the 508 Accessibility link in the footer

### ISSUE THREAD

**Issue by eli-oat** [department-of-veterans-affairs/va.gov-team#50011]
## Issue Description

accessibility-ops is looking into the analytics around the “analytics” link in the footer of [VA.gov](http://va.gov/) page that links to the Section 508 page. We received the following data about that link from Google Analytics:

> This year (01/01 to 11/17) the Section 508 page had…
> - 56,290 page views
> - 51,230 unique page views
> - 1:17 average time on page
> - 69.28% bounce rate (nearly 70% of users did not interact with anything on this page)
> - 47.09% exit

# My Questions

Do you have a sense of how accurate this data is? Is there traffic through that footer that isn’t being captured, or that is captured someplace else? We want to make sure we have an as complete picture of the data as possible before going toooooo deep

Do you know what happens when someone navigates from a modernized [VA.gov](http://va.gov/) page to an old one, or back again? Is that recorded as a bounce, or maybe an exit?

For a bit of added context we also received this data:

> - When searching for “accessibility” on [VA.gov](http://va.gov/), the Section 508 page does not appear as a result on the first page nor does any word for word match exist for “accessibility.”
> When searching for [“Section 508”](https://www.va.gov/search/?page=1&query=section+508&t=true) or [“508”](https://www.va.gov/search/?page=1&query=508&t=true) no links are provided to the actual Section 508 page.
> - [When searching for “feedback,”](https://www.va.gov/search/?page=1&query=feedback&t=true) no actual mechanisms to provide feedback to [VA.gov](http://va.gov/) emerge.
> - This year there were 211 unique searches including the word “accessibility,” 83 unique searches for “508 office,” and 580 unique searches including the word “508.”

Is there someplace else that this search data is captured, or do you think this is pretty reflective of reality?

The last question: is there a way to determine the source page before clicking the accessibility link? E.g. 30 people clicked the accessibility link from the Benefits page and 15 people clicked the accessibility link from the Education page.

---
## Tasks
- [ ] Validate the above questions, and, if possible, provide guidance of best next steps

**Comment by michelle-dooley** [comment]
Hi @eli-oat - Here are some answers, hope this helps...

All footer traffic is being tracked, here is the event that is triggered when clicking on Accessibility in the footer.  You can see the source page in this [GA report](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20221201&_u.date01=20221212&_r.drilldown=analytics.eventCategory:Interactions&explorer-table.plotKeys=%5B%5D&explorer-table.filter=accessibility&explorer-table.secSegmentId=analytics.pagePath&explorer-table.advFilter=%5B%5B0,%22analytics.eventAction%22,%22RE%22,%22accessibility%22,0%5D%5D)

![image](https://user-images.githubusercontent.com/93597659/207406810-003e0143-5395-47e3-a76c-0fc187406bd4.png)


Can you confirm this is the 508 page you are referring to?  It should not be a bounce or exit it should just be another page view in the session, you can see it in this [GA report](  https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20221201&_u.date01=20221212&_r.drilldown=analytics.eventCategory:Interactions&explorer-table.plotKeys=%5B%5D&explorer-table.filter=accessibility&explorer-table.secSegmentId=analytics.exitPagePath&explorer-table.advFilter=%5B%5B0,%22analytics.eventAction%22,%22RE%22,%22accessibility%22,0%5D%5D)
![image](https://user-images.githubusercontent.com/93597659/207396729-1778c582-2ba2-424b-a637-2ade84eed9eb.png).  If you are looking at All VA.gov view and not just Modernized view.

We also have the [Search KPI Dashboard](https://va-gov.domo.com/page/1964748112) that provides search detail information, you would just need to filter to the search terms of interest.  

Not sure about the bounce and exit rates.  Bounce is a single page session so they would of started and ended with the 508 page so there wouldn't of been a previous page they searched on that got them there.

Hope this helps answer your questions.  If you have more let me know.  If so it would be helpful if you provided me the report you are getting the above stats from.

**Comment by eli-oat** [comment]
> Can you confirm this is the 508 page you are referring to? It should not be a bounce or exit it should just be another page view in the session, 

Yes, that is the correct page! 

> Hope this helps answer your questions. If you have more let me know. If so it would be helpful if you provided me the report you are getting the above stats from.

Thank you! I'm going to dive into this info and follow up if I have any further questions.

**Comment by michelle-dooley** [comment]
Per office hours I think you have what you need so closing this ticket.  Please reach out with any further questions.
