### ISSUE TITLE
[BUG] Link to VA Account Missing

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#50015]
## Description
The link to the VA account for Tagalog is missing.

![image](https://user-images.githubusercontent.com/86678742/204301314-6b2a852a-f871-4f76-843f-ad6f9bfb26e0.png)

## Tasks
- Add link to the VA account on text "mag-sign in" and add "(sa Ingles)" to the text

**Comment by loripusey** [comment]
@brianseek one bug for Tagalog; we are missing the link to the VA account

**Comment by brianseek** [comment]
@loripusey this is merged and should be ready to validate on stage soon. See screenshot below:![Pre-check-in--canceled-error-tagalog.png](https://images.zenhubusercontent.com/61523b5b9d354750f04823db/51887fe1-fece-4a4e-a6b8-fa618722f74f)

**Comment by loripusey** [comment]
validated
