### ISSUE TITLE
Fix Failing Tests When Bumping faraday from 0.17.5 to 0.17.6

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#50045]
## Issue Description
Fix failing tests when [bumping faraday from 0.17.5 to 0.17.6](https://github.com/department-of-veterans-affairs/vets-api/pull/11077).

There are 32 failing tests that need to be updated so we can update this gem.

---
## Tasks
- [ ] Fix the failing tests

## Acceptance Criteria
- [ ] The failing tests pass

**Comment by LindseySaari** [comment]
@ericboehs

**Comment by ericboehs** [comment]
Fixed this back in February via https://github.com/department-of-veterans-affairs/vets-api/pull/11815.
