### ISSUE TITLE
Vets API EKS cronjobs

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#50044]
## Description
Vets API currently uses the sidekiq_scheduler.yml to define jobs that need to run on a recurring basis, but there are some current issues with jobs being duplicated. Periodic Job, a feature of Sidekiq Enterprise was [implemented here](https://github.com/department-of-veterans-affairs/vets-api/pull/11076/files) to mitigate duplicate jobs possibly being caused from the current third party "recurring jobs". Instead of utilizing periodic job, we should investigate EKS cronjobs as an alternative. EKS cronjobs, would most likely mitigate the same issues we're seeing with duplicate jobs.

## Tasks
- [ ] Investigate EKS cronjobs
- [ ] Compare best practices for scheduled jobs (Cronjobs vs Periodic Job)

**Comment by laineymajor** [comment]
@LindseySaari is this something that needs to be prioritized soon?

**Comment by laineymajor** [comment]
Start with discovery to understand/answer if we need to make a change and what specific jobs could benefit from this potential change.

Cron jobs v periodic jobs

**Comment by laineymajor** [comment]
closing as we decided to go with periodic jobs
