### ISSUE TITLE
Adding Kristen Faiferlick to DSVA Slack

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/va.gov-team#50051]
Please add [kristen.faiferlick@adhocteam.us](mailto:kristen.faiferlick@adhocteam.us) as a full member.

Kristen is a UX designer who just joined the VES Event Bus project. We are working with Sophie Meyers and Steve Kovacs as our POs. Our main channel is `#ves-event-bus`, but the work is likely to interface with multiple OCTO-adjacent teams so it would be beneficial for her to be a full member.

**Comment by eunicegar** [comment]
Account was in Slack but was deactivated. Reactivated and closing this.
