### ISSUE TITLE
Midpoint Review - Content Feedback - 10-10 Health Apps, 10-10EZ, Household Information Optimization

### ISSUE THREAD

**Issue by CherylEvans** [department-of-veterans-affairs/va.gov-team#50060]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
- Great job with all of the content changes!  I am in complete agreement with all of the recommendations made by Sitewide Content/IA.  I look forward to seeing the final product.

## Feedback
- Practice areas will document their feedback following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback).

**Must:**

- **Your Annual Income and Spouse’s Annual Income**

In accordance with VA.gov Style Guide:
“This includes any income from Social Security, unemployment, retirement and pension, compensation benefits such as VA disability, and any interest or dividends including tax exempt earnings from Individual Retirement Accounts (IRAs) or annuities.”
- [x] I recommend using a comma after “including”
- [x] I recommend using a hyphen between tax and exempt. (tax-exempt)

**Should:**

- **Dependent’s support**

In accordance with VA.gov Style Guide Plain Language Standards, we use “active voice” when possible.
- [ ] I recommend re-writing this sentence in active voice (Bolded text denotes passive voice):

Please count all support contributions even if they **weren’t paid** in regular and set amounts. Support can include tuition or medical bill payments.

- **Your Annual Income**

In accordance with VA.gov Style Guide Plain Language Standards, we use “active voice” when possible.
- [ ] I recommend re-writing this sentence in active voice (Bolded text denotes passive voice):

Gross income is your income before any taxes and other deductions **are subtracted**. This includes any employment wages, bonuses, severance pay, and tips. Include your dependent’s income if **it could have been** used to pay household expenses.

- **Your Annual  Income**

- [x] I recommend using a comma after the word “taxes”.

**Consider:**
_An audience could find this difficult to read._

- **Financial Disclosure** 

Note: “You don’t have to provide your financial information. But if you don’t have a qualifying eligibility factor, this information is the only other way for us to see if you can get VA health care benefits, including added benefits like waived copays.”
- [ ] Consider breaking into smaller sentences. 
 
**Example:** “You don’t have to provide your financial information. But suppose you don’t have a qualifying eligibility factor. In that case, this information is the only other way for us to see if you can get VA health care benefits, including added benefits like waived copays.”
## Platform directions
- Remove the governance-team label
- Update "Issue Title"
- Link to collab cycle Request epic
- Add your feedback
- Remove the CC-Request label (only if you created the ticket using the New Issue link from the Collaboration Cycle Reviews board)
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review QA Only**: VFS PM, yourself (optional)

**Comment by hdjustice** [comment]
Closing ticket.  Ongoing Content feedback has been provided in tickets #61632 , #61038 and #57959 ,
