### ISSUE TITLE
Contact Center Review for the redesigned VA.gov Homepage

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#50075]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
Redesigned VA.gov homepage - an update to the task-based landing page which helps Veterans and beneficiaries
- explore VA benefits and services
- complete tasks to manage their benefits and services
- get the latest information
- log in for access to a personalized streamlined experience

### Launch Date
Anticipating soft launch in mid-December 2022 

> The redesign will be "soft launched" in Production as a parallel page which Veterans and beneficiaries can visit via "opt in" modal from the existing VA.gov homepage. A subset of metrics considered "critical" will be used to determine when/if the redesign can replace the existing homepage in Production by assessing
> - if enough users have used the redesign for analytics to be representative
> - if the new homepage sufficiently supports task completion

### Version Number
Version 1.0

### Product Guide
[VA.gov homepage Product Guide 122022.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/10107712/VA.gov.homepage.Product.Guide.122022.docx) is attached as a download. I will add this to the homepage Github space once approved (https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/public-websites)/home-page/)

### Product Video
I do not believe a video is needed for this single landing page

### Product Video Transcript
I do not believe a video or transcript is needed for this single landing page

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
Hi @mmiddaugh. This looks good. Before I send it for VEO review, however, it needs a higher-resolution screenshot of Figure 10, which is the mobile view of the redesigned homepage. If you can please attach that to this ticket as a JPG or PNG, I'll make sure it replaces the photo in the draft copy. Thanks :)

**Comment by mmiddaugh** [comment]
Thank you!! I would love some assistance with that image - it's so long! 
![Redesigned_homepage_mobile](https://user-images.githubusercontent.com/55411834/205173061-678b575e-e164-44bd-a71d-280f0a920d66.png)

**Comment by starlow00** [comment]
It is indeed. Might need to split it into two columns. I'll see what I can come up with. Thanks, @mmiddaugh!

**Comment by starlow00** [comment]
Sent to VEO for review. Will post copy after their review.

**Comment by starlow00** [comment]
No changes from VEO. Posting copy here.
[VA.gov homepage redesign 122022.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/10159277/VA.gov.homepage.redesign.122022.docx)
