### ISSUE TITLE
Midpoint Review - IA Feedback - 10-10 Health Apps, 10-10EZ, Household Information Optimization

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#50078]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Feedback
- Practice areas will document their feedback following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback).

**Must:**

**Should:**

**Consider:**
* Dependent Information page: there is a question pairing about the dependent's DOB + “when did they become your dependent” that will require biological parents to enter the same date field twice. I wonder if there might be a solution that would allow users to indicate that these answers are the same? 

* Language consistency: the term "last year" is used in a few places, but I'm not sure if it means the calendar year or the last 12 months? More specificity may be helpful there. I'd recommend syncing with sitewide content for additional advice on that.
 
## Platform directions
- Remove the governance-team label
- Update "Issue Title"
- Link to collab cycle Request epic
- Add your feedback
- Remove the CC-Request label (only if you created the ticket using the New Issue link from the Collaboration Cycle Reviews board)
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review QA Only**: VFS PM, yourself (optional)

**Comment by hdjustice** [comment]
We addressed the "last year" feedback - All questions will now refer to the previous year (2022 for example).  
We are still considering what we might do for the dependent DOB and date becoming a dependent.  We will address this in the future in ticket #61998
