### ISSUE TITLE
🥐🥐 Flaky E2E Test Detected! secure-messaging-messages-faq.cypress.spec.js

### ISSUE THREAD

**Issue by it-harrison** [department-of-veterans-affairs/va.gov-team#50103]
Your test spec `src/applications/mhv/secure-messaging/tests/e2e/secure-messaging-messages-faq.cypress.spec.js`
has been disallowed from running on vets-website due to flakiness since 10/28/2022. Please make corrections to the test spec and run it through CI to have it re-enabled.

**Comment by Asterix22** [comment]
fixed
