### ISSUE TITLE
Supplemental Claims | Evidence summary

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#50125]
## Value Statement
**_As a_** Veteran
**_I want to_** review the evidence that I am submitting for my claim
**_So that_** I can confirm that I've upload and given access to the correct evidence.

---
## Acceptance Criteria
- [x] User may edit or remove form fields in each section
- [x] User clicking edit takes them back to the page they filled
- [x] User clicking edit for uploads takes them back to the upload page
- [x] User may add more evidence - link to VA evidence request page
- [ ] Show an error message if all evidence is removed, and the user tries to continue
- [ ] Unit tests complete (90% coverage)
- [ ] E2E tests complete
- [ ] Accessibility testing complete
- [ ] Reviewed and approved by product and/or design

## Designs and Build Notes
[DESIGN](https://www.sketch.com/s/d2416db4-9a4f-4919-abe4-20ba4bdcfd89/a/09Dg1Me)
[ERROR MESSAGE](https://www.sketch.com/s/d2416db4-9a4f-4919-abe4-20ba4bdcfd89/a/nR1OPvz)
[CONTENT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Supplemental-Claims/design/sourceofcontenttruth.md#step-3-of-4-new-and-relevant-evidence-10)

- When veteran clicks **Edit**, it takes them back to the page where they entered the information
- After editing, veteran will step through the flow to get back to this page (MVP)
- When veteran clicks **Remove**, it removes the entry.
- When a veteran clicks **Add more evidence**, they will step through the beginning of the evidence flow again.

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by eileen-coforma** [comment]
@Mottie Error message triggers when the last piece of evidence is deleted. I believe we discussed triggering this only after they hit continue.

**Comment by eileen-coforma** [comment]
When I clicked 'edit' on 'Do you want to limit the information we can request?', it goes back to the beginning of the form, so the URL is wrong.
URL It's going to: https://staging.va.gov/decision-reviews/supplemental-claim/file-supplemental-claim-form-20-0995/supporting-evidence/add-private-record-limitations
Actual URL for the page: https://staging.va.gov/decision-reviews/supplemental-claim/file-supplemental-claim-form-20-0995/supporting-evidence/request-record-limitations

**Comment by saderagsdale** [comment]
Still needs link fix.

**Comment by Mottie** [comment]
Fixed in [#23074](https://github.com/department-of-veterans-affairs/vets-website/pull/23074). Available for testing in staging.

**Comment by saderagsdale** [comment]
@Mottie lookin good
