### ISSUE TITLE
🥐🥐 Flaky E2E Test Detected! validation.attempts.reset.cypress.spec.js

### ISSUE THREAD

**Issue by it-harrison** [department-of-veterans-affairs/va.gov-team#50120]
Your test spec `src/applications/check-in/pre-check-in/tests/e2e/validation-attempts/validation.attempts.reset.cypress.spec.js`
has been disallowed from running on vets-website due to flakiness since 9/29/2022. Please make corrections to the test spec and run it through CI to have it re-enabled.

**Comment by loripusey** [comment]
@brianseek @acrollet @wullaski Can you investigate?

**Comment by wullaski** [comment]
This test got removed with this commit https://github.com/department-of-veterans-affairs/vets-website/commit/acb8e26c172ecf6a8eba107e8b324729e82d5d7a
