### ISSUE TITLE
[SPIKE] [FE] How can we Opt Out of Using the VA Header/Footer

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#50139]
## Notes
NOTE: we would like to release this gradually over time (i.e. certain % initially and gradually increase it as we monitor the metrics)

NOTE: Matt Dingee needs to be kept in the loop know how we architect this

NOTE: We need to coordinate with Dave Conlon

## Questions to Answer
- [ ] How can we Opt Out of Using the VA Header/Footer?
- [ ] How do we need to architect it?
- [ ] Can we make this respect a feature flag?

**Comment by acrollet** [comment]
I've been digging in on this and also synced with @brianseek earlier today. Topline takeaways:

## Goals
We've stated two goals for this work, primarily improved Veteran experience and secondarily improved performance.

## Minimal approach
We can meet almost all of the requested UI changes by doing the following:
  1. opt out of showing the sign-in link and header menu by updating the [application registry](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/applications/registry.json) - see https://www.va.gov/sign-in/?oauth=false for an example of what this would look like
  2. submit a PR to `content-build` and `vets-website` to allow suppressing all except the legal links in the footer, to also be configured with the application registry

This would be the lowest effort and most maintainable approach available, but doesn't allow us to show the page title in the header area. (We had a question that @brianseek is going to bring up with the UX team on Monday, as to whether it's semantically correct to have the page `h1` within the html `<header>` element) This also would be "all or nothing" for each application, we would not be able to leverage a feature toggle to change the behavior for a percentage of users.

## Maximal approach
The second approach would be to ask platform for the ability to take over the entire `<body>` element. This would give us full control over the header and footer and the ability to use , but imply a much higher on-going maintenance burden, including:
- ensure that all required page elements (US site, veterans crisis line) are shown and updated when changes are made to platform-wide code
- ensure that all content (mostly footer links and text) and styling are kept up to date as changes are made to platform-wide code (we might be able to mitigate this work by displaying the platform footer component ourselves, but this could reduce performance gains if any are available to be had)

If we wish to pursue this second approach, we should first do work in a follow-on spike to validate the assumption that displaying our own header and footer will measurably affect site performance.

**Comment by benbrasso-agile6** [comment]
> This would be the lowest effort and most maintainable approach available, but doesn't allow us to show the page title in the header area. (We had a question that @brianseek is going to bring up with the UX team on Monday, as to whether it's semantically correct to have the page h1 within the html <header> element) This also would be "all or nothing" for each application, we would not be able to leverage a feature toggle to change the behavior for a percentage of users.

I believe that is correct, as it should take on a banner landmark.

**Comment by brianseek** [comment]
Had a sync up with Ben, Kelly, and Zach. We decided to try for the minimal approach. Some header changes will be needed to address Ben's comment above. We will try to move the h1 into the header from our app, but if there is a flicker or content jump, the UX team will come up with an alternative design. 

Next step will be to talk with Matt Dingee about our approach and where that all fits in with the design system's ideas for this.

**Comment by brianseek** [comment]
Met with Matt Dingee on the DS teams perspective. He would prefer that we make the changes as webcomponents. Their team is going to tackle header/footer as webcomponents next year.

In discussion with the team we are going to make contact with the team(s) that manage header and footer to get an idea of what is possible. From the PL in standup on 12/19 we determined that we want to take the fastest path of least resistance.

From chat:
From what I know from my discussions with Matt Dingee, we would need to talk to Public Websites and Matt Self.

08:50:39 From Ben Brasso to Everyone:
	Carol and Matt are the folks that we need to speak with about being part of the component conversation
08:51:31 From Kristen McConnell to Everyone:
	Carol and Matt are the platform group, but public websites controls that current component.
08:54:55 From Kristen McConnell to Everyone:
	Wait…not Matt Self. Dave Conlon on the sitewide crew is who Matt Dingee mentioned too.

**Comment by brianseek** [comment]
Closing this ticket. Updated build ticket with details: https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/49890
