### ISSUE TITLE
Create GA Events for the Various API Responses that are Returned from BTSSS

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#50140]
## Tasks
- Create GA Events for the Various API Responses that are Returned from BTSSS
- On the https://staging.va.gov/health-care/appointment-check-in/complete page, for the various travel messages in the yellow bg box, can we update the GA event to be more specific to the link text? For example, currently, the label is set as nav-check-in-request-travel-pay-reimbursement-from-travel-error-link-clicked. I would like to see some of the link text in that value vs. "link-clicked." We have 5 different complete pages, with only 3 variations of that link. So, I'd expect to see a total of 3 events. 

https://share.goabstract.com/6b69924f-904b-4d78-b5a1-4c40ed65e4d2?collectionLayerId=bbf2ae3b-a0fc-4ce5-a4bc-52c0fa60f0af&mode=design&sha=latest

https://share.goabstract.com/6b69924f-904b-4d78-b5a1-4c40ed65e4d2?collectionLayerId=fda84b41-9434-41b6-a2c4-7b6007737eb3&mode=design&sha=005790a0202eed0e984eb6e87c8d183d090d945f

https://share.goabstract.com/6b69924f-904b-4d78-b5a1-4c40ed65e4d2?collectionLayerId=e2274457-f20c-4460-b936-c7d51bae2f96&mode=design&sha=991446e80197aad415dc1c1e288f5709afaa3bef

**Comment by brianseek** [comment]
@benbrasso-agile6 let's chat tomorrow about how you would specifically like to see those events. As of right now, they are all unique based on where they are clicked from

**Comment by brianseek** [comment]
@benbrasso-agile6 this should be in stage soon to test.

**Comment by sarahknoppA6** [comment]
per standup update, we can close.
