### ISSUE TITLE
Fix issue with appeals routes for the metadata controller

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#50144]
## Issue Description
It appears there's an issue with the `appeals` routes for the `metadata` controller.  Support request - https://dsva.slack.com/archives/CBU0KDSB1/p1669743250248239

---
## Tasks
- [x] Research issue
- [x] Fix issue

## Acceptance Criteria
- [x] Issue is fixed

**Comment by laineymajor** [comment]
Sent message to check on progress from the gateway team.

**Comment by laineymajor** [comment]
At this point, we just need to wait on the team. This is not our code.

**Comment by laineymajor** [comment]
Update: Gateway work is currently underway!!

**Comment by laineymajor** [comment]
Updating to a 5 as this now involves significant communication with, and work from, additional teams. @holdenhinkle FYI...
