### ISSUE TITLE
Define approach to preview environment addresses

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#50149]
# Description
How might we dynamically create semantic URLs for preview environments?

Given that VFS team members will need to remember and pass to others the URL for their preview environments, we should dynamically generate URLs for each preview environment that have semantic meaning.

# Tasks
- [x] Determine how to dynamically create URLs for a preview environment

# Acceptance Criteria
- [ ] A system for creating preview environments with a URL that has semantic meaning, is defined in a document

**Comment by rmtolmach** [comment]
Writing up a discovery document with findings: https://vfs.atlassian.net/wiki/spaces/TT4/pages/2458845358/Preview+Environment+URLs

**Comment by rmtolmach** [comment]
@pjhill See "Final thoughts on addresses" section in the document linked above.

**Comment by pjhill** [comment]
A document including research and final thoughts with regards to the URL creation scheme are available here: https://vfs.atlassian.net/wiki/spaces/TT4/pages/2458845358/Preview+Environment+URLs#Final-thoughts-on-addresses%3A

**Comment by pjhill** [comment]
Thanks for working through this, I think we have a good plan!
