### ISSUE TITLE
Redesigned VA.gov homepage PTEMS-QA Test Plan

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#50147]
\[**Product Managers**: Open this ticket **at least 2 Sprints (4 weeks)** before you expect a Platform Staging Review of this Product/Feature.  Then:
- Replace title's **[Product/Feature]** with your actual product/feature name.
- Add yourself to Assignees
- Fill-out sections below.]

**See also**: Relevant [PTEMS-QA Manual-UI Testing process doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/engineering/qa/manual-ui-testing-process.md) for details.

## Product/Feature summary

\[Provide brief summary of product/feature to be tested on Staging by PTEMS-QA. Also, be sure to include links to the Product/Feature Outline, Epic, Pre-Launch Checklist, and Design tickets/artifacts.]

- [Initiative brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/home-page/home-page-redesign-initiative/initiative-brief.md)
- [Super Epic- VA.gov Homepage redesign#40845](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/40845)
- [CMS Epic: Harden Homepage design refresh for production launch department-of-veterans-affairs/va.gov-team#8877](https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/8877)
- [Round 3 Sketch file with copy and design](https://www.sketch.com/s/3aa40506-4be2-46cc-876b-93f1a9f3a857/p/EAD305BC-3082-4F81-ADEC-C2486F7B6BEF/canvas)
- [Staging implementation link](https://staging.va.gov/new-home-page/)

## Product-team SMEs

\[For any Practice-areas worked by 2+ team-member, clarify who specifically is assigned to this initiative/project.  Leave blank for other areas.\]

- Product: Michelle Middaugh
- Design/Research: Cindy Merrill
- Content/IA: Danielle Thierry
- Engineering: Public Websites
- QA: Tze-chiu Lei, Laura Flannery, Eli Mellen, and DK Kennedy

## Proposed use-cases and Staging test-accounts
- This is within the unauthenticated experience - no test users are needed
- [Use Cases](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/home-page/home-page-redesign-initiative/use-cases.md) 
-  [TestRail Test Runs]: 
  - [QA](https://dsvavsp.testrail.io/index.php?/plans/view/4309)
  - [A11y](https://dsvavsp.testrail.io/index.php?/runs/view/3824&group_by=cases:section_id&group_order=asc&group_id=4473)

## How to configure this issue

- [x] **Product Manager** added to Assignees
- [ ] Attached to a **Milestone** (when will this be completed?)
- [ ] Attached to **Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] Added product-specific label (if any)

## Definition of Done

- [x] Product references provided by Product Team.
- [x] Use Cases provided.
- [x] For authenticated products, Staging test-accounts and mock-data set up for Use Cases above.
- [x] Test Cases [in TestRail] finalized based on Use Cases above.
- [ ] Test Runs completed on Staging [or Drupal pre-prod environment].
- [ ] Test Reports generated.  These should be provided to Platform at least 4 workdays before [Staging Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html).

**Comment by mmiddaugh** [comment]
Hello! Staging review is planned for December 15. accessibility
The following is available on https://staging.va.gov/new-home-page/
- search
- other search tools
- top task links
- benefit promo
- benefit hub
- news promo
Updates to the following are expected by Monday, 12/5
- email signup
- "create an account" 
The opt-in modal will follow.

**Comment by mmiddaugh** [comment]
(WIP) Accessibility Testing for [Sitewide Homepage, Redesigned VA.gov homepage] #50360

**Comment by mmiddaugh** [comment]
Note: VA Departments will not appear until launch (adding it in the CMS system will cause it to appear on the existing homepage, which we'd like to avoid until release. FYI

**Comment by cindymerrill** [comment]
I just noticed a potential accessibility issue in the newly-updated [home page redesign](https://staging.va.gov/new-home-page/)...Near the bottom of the page, the email newsletter signup heading, email address field, and button are **_centered_ rather than left aligned** (as they were in the previous version). By not having them on the left margin, they may be invisible to people using a screen magnifier and only seeing the left third (or less) of the screen. @TiffanyPender @laflannery @mmiddaugh 

![image](https://user-images.githubusercontent.com/69914583/207179062-ea793f2f-ce62-43f9-ae89-5357cd923e3f.png)

**Comment by TiffanyPender** [comment]
> I just noticed a potential accessibility issue in the newly-updated [home page redesign](https://staging.va.gov/new-home-page/)...Near the bottom of the page, the email newsletter signup heading, email address field, and button are **_centered_ rather than left aligned** (as they were in the previous version). By not having them on the left margin, they may be invisible to people using a screen magnifier and only seeing the left third (or less) of the screen. 

That is good to note @cindymerrill. The version that I completed an accessibility audit on appeared differently - everything was on one line, left-aligned. It looks like this has changed since I completed my audit.

**Comment by cindymerrill** [comment]
Yes, the design apparently changed, @TiffanyPender . Could you please add this issue to your audit and/or get it into the team's backlog?

**Comment by mmiddaugh** [comment]
The style was updated, consistent with a change in Sketch and reuse of an existing component. It also made the link functional so form validation and error messaging are now in place

**Comment by tlei123** [comment]
Summary (Defects) report generation still erroring-out.  Just started a third one [see [Reports page](https://dsvavsp.testrail.io/index.php?/reports/overview/56) in TestRail].  :::fingers crossed:::

**Comment by tlei123** [comment]
@mmiddaugh , i just QA'ed Opt-in modal in RI at http://a109d22ff3eebd5144235d7057fb577f.review.vetsgov-internal/ against macOS Chrome & Firefox [the only two browsers that work thru SOCKS-proxy].

2 defects logged: #50833, #50834

cc @eflaherty

**Comment by jilladams** [comment]
PTEMS folks are on hiatus contractually. Homepage is launched, and modal has staging review tomorrow. Closing, as I don't think this team will re-engage on this project / test plan. Feel free to reopen if I'm wrong.
