### ISSUE TITLE
Content-build Github Action workflows on self-hosted runners intermittently fail

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-team#50148]
## What happened?
In the [content-build repo](https://github.com/department-of-veterans-affairs/content-build/), Github Action workflows that use self-hosted runners will sometimes fail with disk access issues. 

Error log example:
```
Run actions/checkout@v3
Syncing repository: department-of-veterans-affairs/content-build
Getting Git version info
Temporarily overriding HOME='/home/runner/runner2/_work/_temp/7b1cf1a6-269b-4bb2-9e31-ee13339c097d' before making global git config changes
Adding repository directory to the temporary git global config as a safe directory
/usr/bin/git config --global --add safe.directory /home/runner/runner2/_work/content-build/content-build
/usr/bin/git config --local --get remote.origin.url
https://github.com/department-of-veterans-affairs/content-build
Removing previously created refs, to avoid conflicts
  /usr/bin/git rev-parse --symbolic-full-name --verify --quiet HEAD
  refs/heads/main
  /usr/bin/git checkout --detach
  Error: fatal: Unable to create '/home/runner/runner2/_work/content-build/content-build/.git/index.lock': Permission denied
  Warning: Unable to prepare the existing repository. The repository will be recreated instead.
  Deleting the contents of '/home/runner/runner2/_work/content-build/content-build'
  Error: stderr maxBuffer length exceeded
```
This can be seen across multiple workflows:
https://github.com/department-of-veterans-affairs/content-build/actions/runs/3548464041/jobs/5960298357
https://github.com/department-of-veterans-affairs/content-build/actions/runs/3515820757/jobs/5891599252
https://github.com/department-of-veterans-affairs/content-build/actions/runs/3512196868/jobs/5883660184
https://github.com/department-of-veterans-affairs/content-build/actions/runs/3459246127/jobs/5774440563

## Steps to Reproduce
This happens only intermittently. However, it can be forced:
- Find a job within a Content Build workflow that uses @action/checkout or @action/setup-node; jobs that use the [custom install action](https://github.com/department-of-veterans-affairs/content-build/blob/main/.github/workflows/install/action.yml) also work for this
- That job will have `runs-on: self-hosted`. This should be modified to:
```
runs-on:
  - self-hosted
  - asg
```
- Run the workflow. 

## Desired behavior
All workflows on self-hosted runners should run without error.

## Acceptance Criteria
- [x] Workflows shall run without error.

## Potentially related issue
https://github.com/department-of-veterans-affairs/content-build/pull/1281

## Analysis
I avoided solutioning & specifics in the above ticket, but I do have suspcions as to the source of the problem.

Content-build has a rather large pool of runners available to it (separate issue we would like to fix). These can be seen in the [AWS Console](https://console.amazonaws-us-gov.com/ec2/home?region=us-gov-west-1#Instances:search=:content-build;v=3;$case=tags:true%5C,client:false;$regex=tags:false%5C,client:false).

Of these, a small number of runners are set up as part of an ASG: https://console.amazonaws-us-gov.com/ec2/home?region=us-gov-west-1#Instances:search=:content-build;tag:aws:autoscaling:groupName=dsva-vagov-content-build-gha-runners-asg;v=3;$case=tags:true%5C,client:false;$regex=tags:false%5C,client:false

Both ASG and non-ASG runners are part of the pool available to Content Build. If a job has the specification `runs-on: asg`, it will only run on a runner from the ASG. However, if the specification is limited to `runs-on: self-hosted`, it will pick from the entire pool of runners, which can include both ASG and non-ASG runners.

When we see failures of this sort, they are always on ASG-created instances. There may either be a configuration difference, or it is possible that how the ASG-created instances are used is causing trouble.

In Content Build, ASG runners are used for specific jobs. Of note is this job in the Continuous Integration workflow, which runs Cypress tests on a Docker container: https://github.com/department-of-veterans-affairs/content-build/blob/main/.github/workflows/continuous-integration.yml#L351

The container is instantiated using the root user:
```
    container:
      image: public.ecr.aws/cypress-io/cypress/browsers:node16.13.2-chrome100-ff98
      options: -u 0
      volumes:
        - /usr/local/share:/share
        - /etc/ssl/certs
```

I do not believe the container needs to be set up using the root user. vets-website contains very similar container usage which does not use the root user in its setup, for example: https://github.com/department-of-veterans-affairs/vets-website/blob/main/.github/workflows/e2e-tests.yml#L157

I am not 100% certain this is connected, but I think it bears investigating. 

https://github.com/department-of-veterans-affairs/content-build/pull/1281/files also investigated this issue in relation to failures on a11y workflows. However, that PR solved their issue by running the container as root. 

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by timcosgrove** [comment]
We saw an additional failure due to this issue: https://github.com/department-of-veterans-affairs/content-build/actions/runs/3695495474/jobs/6258650274

It did not interfere with content deployment; the failure happened during a notification stage once deployment was complete.

**Comment by timcosgrove** [comment]
More similar:

https://github.com/department-of-veterans-affairs/content-build/actions/runs/3704731051/jobs/6278378559#step:2:40
https://github.com/department-of-veterans-affairs/content-build/actions/runs/3704731051/jobs/6278903832#step:2:40
https://github.com/department-of-veterans-affairs/content-build/actions/runs/3704996312/jobs/6278970374#step:2:40
https://github.com/department-of-veterans-affairs/content-build/actions/runs/3704996312/jobs/6279544778#step:2:40

**Comment by olivereri** [comment]
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12435
and
https://github.com/department-of-veterans-affairs/content-build/pull/1500

Close this.
