### ISSUE TITLE
Adding [Matthew McCollum] to DSVA Slack

### ISSUE THREAD

**Issue by jjennings-va** [department-of-veterans-affairs/va.gov-team#50158]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

<describe the request>

Are you requesting to add an individual as a:

- Full member

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add McCollum_Matthew@bah.com as a full member. He is a lead engineer on the Lighthouse Facilities API and needs to have access to various channels within the DSVA space such as #vfs-platform-support #vfs-platform-builds #vfs-all-teams #sitewide-facilities #lighthouse-infrastructure #cms-lighthouse, etc.

**Comment by eunicegar** [comment]
done
