### ISSUE TITLE
Call Centers - Investigate Deploying Session Replay Tool

### ISSUE THREAD

**Issue by jchasia-adhoc** [department-of-veterans-affairs/va.gov-team#5015]
Goal:
To address pain points around call center reps replicating user issues, investigate tools for replaying user sessions.

What is session replay?
Session replay is a playback of a user’s journey on a website or within a web application.  The reconstruction consists of mouse and keyboard movements, scrolls, taps, and clicks. Gathered together, they show users’ paths on a site or app and let you feel as you were watching them live.

How does it work?
To start recording data about users action on your website, you need to subscribe to a session replay tool like LiveSession.  Then you need to add a JavaScript tracking code to the <head> section of your site’s code to enable the tool to monitor events in the user web browser

**Comment by jwoodman5** [comment]
@jchasia-adhoc I am working on some ticket clean-up for our team. Is this still a valid issue? Thanks.

**Comment by Kimberley2019** [comment]
No response.  Closing.  It can be reopened if needed.
