### ISSUE TITLE
Remove broken link from Board of Veterans' Appeals hearing page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#50157]
## Issue Description

We currently have a broken link on the [Board of Veterans' Appeals (BVA) hearing](https://www.va.gov/disability/file-an-appeal/board-of-veterans-appeals/) page that we need to remove. 

It's the link for Find out more about choosing a video hearing (PDF) under the H2 How do I request a Board hearing?

Once we get a new link, we can add it to the page. 

## Tasks
- [x] Remove broken link
- [x] Copyedit 
- [x] Publish

## Acceptance Criteria
- [x] The link is no longer showing on the live page

**Comment by RLHecht** [comment]
I took out this broken link. I also reworked the drupal components because if you look at the live page the header hierarchy was wonky. There were all H2s when they should be H2s and then H3s for the questions. I double checked that all the Q&As are there and in the right order but can you please triple check?

**Comment by laurwill** [comment]
Nice fix on the header levels! I reviewed the changes and published.

**Comment by RLHecht** [comment]
Changes are live. Closing!
