### ISSUE TITLE
Publish VSP prioritization rubric

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/va.gov-team#5016]
So that VSP teams have a client + leadership approved / supported methodology for narrowing prioritization, and reducing the volume of simultaneous initiatives.

- Goal for n super epics in NOW, or for n simultaneous initiatives / sprint objectives
- Here's the rubric for how to choose those -- maybe involve User Journey map

## Objective
O3: Stability and resiliency of the Platform's systems and teams continue to improve.

**Comment by rroueche** [comment]
Rubric so we can say "this looks like more than you can accomplish in a sprint, here's how we decide what to recommend you cut, looking at these super epics against the OKRs, we think these are more important than these".

Also do we want to practice a work in progress limit?

**Comment by KevinMHoffmanUSDS** [comment]
Collecting some documentation that might be relevant to this work:

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/platform-principles.md

https://department-of-veterans-affairs.github.io/va-digital-service-handbook/digital-standards

**Comment by rroueche** [comment]
Published guidelines on how to think about priorities, w/o telling people what to do: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/quarterly-planning/2020-Q2/priorities.md
