### ISSUE TITLE
AWS access for Peter Holyoke

### ISSUE THREAD

**Issue by pjholyoke** [department-of-veterans-affairs/va.gov-team#50180]
### COR Name

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Peter Holyoke

### Your Email

peter.holyoke@adhocteam.us

### Team, Role, and Company of the target individual

VSP, Software Engineer III, AdHoC

### Product Manager (PM) name and email

Clint Little

### Product Owner (PO) name and email

Clint Little

### Desired AWS Access

I'll need admin access.

### Access Expiration

ongoing (?)

### Additional Notes

Name CO/ COR: Ray Wang
CO/COR number: 661-544-6706
CO/COR email: gang.wang@va.gov 

### User must exist in a roster before AWS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [x] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by td-usds** [comment]
Requested access confirmed and approved

**Comment by td-usds** [comment]
Reached out to VOR

**Comment by td-usds** [comment]
Reached out to VOR

**Comment by little-oddball** [comment]
@pjholyoke - please verify the perms and close if complete.

**Comment by pjholyoke** [comment]
Looks like my permissions are all set. Thanks.
