### ISSUE TITLE
Update year on home loan limits page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#50181]
## Issue Description

We need to update the year to 2023 on our [VA home loan limits](https://www.va.gov/housing-assistance/home-loans/loan-limits/) page. This is toward the bottom of the page just above the subway map.

The link currently points to 2023 rates, so we can make this change now.

## Tasks
- [x] Change year to 2023
- [x] Copyedit (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] 2023 is current year on live page

**Comment by RLHecht** [comment]
I just made this change and since the link is already pointing to 2023 i think we can publish now.

**Comment by laurwill** [comment]
Checked and published!

**Comment by RLHecht** [comment]
This is live. Closing ticket.
