### ISSUE TITLE
Github Action in Vets-api to test helm charts

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#50191]
Helm charts need to be rendered locally before changes can be pushed to the parent-helm-charts branch. [Helm Test Workflow](https://github.com/department-of-veterans-affairs/vets-api/blob/parent-helm-charts/.github/workflows/helm_chart_prompt.yml)

**Comment by RachalCassity** [comment]
A github action needs to alert developers to update the chart version AND any new values in the vsp-manifest repo

**Comment by RachalCassity** [comment]
- [ ] Attach PRs
- [ ] Run helm template chart in vets-api to make sure parent helm charts work.

**Comment by laineymajor** [comment]
@RachalCassity is this specific to a certain environment?
