### ISSUE TITLE
[UX] Discovery Research Epic: Understanding VFS monitoring needs 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#50192]
## High Level User Story
As a VFS Developer, I need access to the Platform's Centralized Monitoring tool to monitor application health.
As a VFS Developer, I need access to the Platform's Centralized Monitoring tool to monitor application performance.
As a VFS Developer, I need access to the Platform's Centralized Monitoring tool to set up alerts for important events.

## Goals
_What outcome(s) do we want to see?_ 

## Issues to create within this Epic

```
- Create a research plan
- Recruit for research sessions/Schedule research sessions
- Create a conversation guide
- Conduct Discovery Research Sessions (at a minimum, the team lead, PM, designer, content person should join these sessions).
- Discovery Synthesis - should be conducted as a team, led by a designer.
- Discovery Research Readout (at minimum, it is expected that the designer should do a readout at design meetings & for their team. If stakeholder readouts are needed, the team lead/PM are responsible for scheduling those. Designers should also plan to do research readouts at the end-of-sprint demo.)
```

**Comment by jhouse-solvd** [comment]
The survey went live on 12/13. Link [here](https://dsva.slack.com/archives/CE4304QPK/p1670952923255379)

We are awaiting responses from VFS teams and have received a handful already. 

The survey will remain open through at least mid-January so that we can be sure to collect input from those interested.

**Comment by jhouse-solvd** [comment]
**Update 1/5**
- 8 overall participants that have completed the survey in full
- 7 participants indicated they are open to further conversations

We'd love to get 20-25 participants to have a good amount of data to work with.

**Comment by jhouse-solvd** [comment]
**Update 1/11**

- 11 participants that have completed the survey in full
- 8 participants indicated they are open to further conversations

High-level next steps: 
- Synthesize survey 
- Prepare conversations for interviews 
- Schedule interviews 
- Perform interviews 
- Document learnings gleaned from interviews 
- Write-up of research findings 
- Research readout (slide deck) that can be shared with stakeholders

**Comment by tayism** [comment]
@jhouse-solvd Tickets have been added!

**Comment by jhouse-solvd** [comment]
@tayism - thanks so much!! looking forward to the synthesis workshop later this week! :)

**Comment by jhouse-solvd** [comment]
This work is planned for multiple sprints. We will move into final tasks soon and work toward synthesis and readout.

**Comment by jhouse-solvd** [comment]
Taylor and I spoke last week. Interviews and synthesis have wrapped up. 

The next step is to prepare a presentation and read-out for leadership and stakeholders. 

This work will carry over into the next sprint. :)

**Comment by jhouse-solvd** [comment]
All of the tasks are complete. Please see [Research findings - Monitoring Tools for VFS Teams](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2542797074/Research+findings+-+Monitoring+Tools+for+VFS+Teams) (Note: For Platform team members; requires Confluence access). 

We'll be sharing findings with stakeholders and customers and working to develop plans for implementing recommendations based on the insights developed during the discovery research. 

A big thank you to all of the VFS teams that participated, and to @tayism and the entire Platform Service Design team for their assistance with this epic.

**Comment by jhouse-solvd** [comment]
Closing.
