### ISSUE TITLE
Complete Downtime Notification Work

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#502]

**Comment by annaswims** [comment]
Is this a duplicate epic? https://github.com/department-of-veterans-affairs/va.gov-team/issues/180

**Comment by ricetj** [comment]
@annaswims This was an epic on Vets.gov repo that I brought over. It could be a dup, so please close if needed.

**Comment by annaswims** [comment]
Ok, Thanks!  I think #180 covers it.
