### ISSUE TITLE
AWS access for Bentley Hensel

### ISSUE THREAD

**Issue by TheBoatyMcBoatFace** [department-of-veterans-affairs/va.gov-team#50204]
### COR Name

Eunice Garcia

### Vendor Onboarding Representative Name

Agile Six - Anthony M. Arashiro

### Your Name

Bentley Hensel

### Your Email

bentley.hensel@civicactions.com

### Team, Role, and Company of the target individual

Platform CMS DevOps | Product Manager | CivicActions

### Product Manager (PM) name and email

Bentley Hensel - bentley.hensel@civicactions.com

### Product Owner (PO) name and email

Mike Chelen - michael.chelen@va.gov

### Desired AWS Access

I need read-only access to the resources applicable to the Platform CMS team. Read only access to the resources these people have access to would be ideal: Tim Cosgrove, Elijah Lynn, & Eric Oliver. If possible, edit resource key/values would be helpful, but if not, I understand.

### Access Expiration

Ongoing - but 1 year also works. I can request again EOY 2023 if that is preferred

### Additional Notes

I need access in order to audit infrastructure and understand what resources are currently deployed. Right now, my team has to walk me through the infrastructure setup/changes every time we discuss it. I would like read only access so that my team can jump into infrastructure discussions without having to explain the current setup. If possible, the ability to edit infrastructure key/values would be helpful with regards to organizing resources, but understand if read-only is allocated now. If edit key/values is needed, we can always add it later. 

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [x] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by td-usds** [comment]
Reached out to VOR

**Comment by BillChapmanUSDS** [comment]
I see EQUIP date so I think I have leeway to approve but I'm still getting the lay of the land and the request is a little vague for me. Are we just talking about read only access to AWS Kinesis here? I have no issues approving that, are there other AWS resources we need to approve on this request?

**Comment by TheBoatyMcBoatFace** [comment]
@BillChapmanUSDS I picked up my PIV yesterday and have had my va.gov email for a few weeks now. I'll get that updated in Confluence tomorrow AM. 

I'm working to map the various systems and tools my team, Platform CMS, uses.

From what I've gathered thus far, my deal interacts with
- S3
- EC2
- EFS
- Associated Availability zones
- route 53
- RDS


There may be additional resource types. I don't think there are any Lambda functions, but the deeper I dig, the more AWS resource types I find. 

I have zero desire or need to spin up/down assets or export any logs. The only changes I can see myself making are modifications to Key|Value tags to better organize the AWS account, as it relates to my team.

Most assets I'm hoping to view have some variation of `cms` in the name or tag, but not all. I know for sure that the S3 buckets used to host the va.gov static site do not have CMS references. 

I hope the above helps. If you need additional info, I'm more than happy to provide whatever I can.

**Comment by BillChapmanUSDS** [comment]
I see the offboarding task and I'm assuming @TheBoatyMcBoatFace is moving on and no longer needing access? Or is this a matter of switching teams and this access is still necessary?

**Comment by TheBoatyMcBoatFace** [comment]
@BillChapmanUSDS there are some contract modifications and I'm transitioning off the VA project all together. Sorry about the change once the ball got rolling on this.
