### ISSUE TITLE
Request access to Google Analytics and/or Domo

### ISSUE THREAD

**Issue by TheBoatyMcBoatFace** [department-of-veterans-affairs/va.gov-team#50205]
# Request Google Analytics and/or Domo access

## What this form is for
Use this template to request access to Google Analytics and/or Domo. Please complete steps 1 & 2 below. 

## 1. Access Requirements 
Please check the analytics tool(s) you need access to:
- [x] Google Analytics
- [x] Domo
- [ ] (Platform Teams only) BigQuery

## 2. User Email Address to Receive Access 
**Due to privacy concerns, please do not put your email in this ticket.** Instead please use `/support` on the DSVA Slack channel [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support), select `Analytics` in the "I need help from" dropdown, and then add in the `Summary of request` section: 
 1. This issue's link 
 2. Emails that need access

_Please note: For Google Analytics, if the user has a VA.gov email address or does not yet have a Google account, they will need to create one by visiting [this link](https://accounts.google.com/signup/v2/webcreateaccount?continue=https%3A%2F%2Faccounts.google.com%2FManageAccount&gmb=exp&biz=false&flowName=GlifWebSignIn&flowEntry=SignUp). Once at that link, VA.gov users and external users with email accounts that are not Google based should select the option "Use my current email address instead"._

_Please list any additional requirements, if any (i.e. edit access). If you are requesting BigQuery access, please share if you will be hooking up an API._

I am the new Product Manager on Platform CMS. My team needs unified insight into their areas of responsibility. I've been a Domo Dojo in the past and would like to have the following domo access. 

Goal: One parent and two child pages. The parent page will contain hero/topline metrics and the child pages will act as drill downs into the Content Build and another into Infrastructure.

I would like the ability to edit those pages, create cards, and access datasets. Depending on the dataset structure, I may need access to create ETLs. My hope is that I can combine AWS, Datadog, Github, and basic Drupal stats into cards and create alert policies for my team. I would like for them to easily have access to the info they need so they can focus on engineering as opposed to finding metrics.

_Once you receive access, you should receive a confirmation email directly from Google or Domo._

 
---

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by michelle-dooley** [comment]
Access granted.

**Comment by TheBoatyMcBoatFace** [comment]
# Request to Change Access Level

I was a Domo Dojo in a former life and am more than happy to set up the pages, cards, and necessary ETLs/Transforms. If possible, could you grant me the following permissions?

- Create new cards/edit my cards
- Create Pages/Edit my pages
- Create/Edit my ETLs
- Create Notifications (for my team when certain card thresholds are passed)
- View Datasets (just so I can see what data is available to request access to)

My desired datasets are below. If they aren't available, I'm glad to set up those connectors. If so, I'll need app/connector access as well. 


## Datasets

**Google Analytics**
- Sitewide CMS - 314152370
- VA.gov - Production - 291016866
- VA.gov CMS Backend - UA-50123418-18
- VA.gov - Non-Production 277987410

**Github**
- Repo: [va.gov-cms](http://va.gov-cms/)
- Repo: content-build

**Datadog**
- If available. _I am happy to work on getting the connection setup if needed_

**Sentry**
- If available. _I am happy to work on getting the connection setup if needed_

**Below is a  overview of what I am planning in Domo**

## Proposed Domo Pages

- Platform Crew (Acts more as a placeholder page - other Platform teams can organize their pages under this)
	- CMS (Hero metric page with top-lines from child pages)
		- Infrastructure - (Provides a detailed overview and analysis of CMS DevOps managed infrastructure)
		- Workflows - (Metrics & status of current build processes/sub-processes)
		- Team - (Tracking of Github issues/backlog, team bandwidth, and overall productivity)

Let me know if you have any questions/concerns. I'm glad to walk through my plan/access requests.

**Comment by michelle-dooley** [comment]
@TheBoatyMcBoatFace - we can certainly give you edit rights so you can create and edit your own datasets/cards/dashboards but I think we need to discuss the data you are wanting access too.  While we technically can bring in anything there are security restrictions and cost/size limitations that do not allow us to.  I would like to spend some time to get a better understanding of your use case for all this data and determine what is or isn't accessible and how/why.

**Comment by TheBoatyMcBoatFace** [comment]
Thanks @michelle-dooley and I completely understand. I saw the Dataset meeting for Wednesday, but I'll also put together a plan for the cards/pages I'm looking to create and the associated datasets. That will give better insight into what questions I'm trying to answer with Domo and what data are needed to accomplish it.

**Comment by michelle-dooley** [comment]
Closing this ticket as we met and discussed.  Additional work will be their own ticket.
