### ISSUE TITLE
Gather information to submit ESECC form

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#50203]
# Description
This may not be necessary if we can append the scope of RFC 965 per this [ticket](https://app.zenhub.com/workspaces/platform-tech-team-4-633b069d2920b776613c93d8/issues/department-of-veterans-affairs/va.gov-team/50151).

# Tasks
TBD

# Acceptance Criteria
TBD

**Comment by JoeTice** [comment]
OBE
