### ISSUE TITLE
EKS secret syncing

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#50227]
## Description

After updating an existing parameter store secret for the dev environment, the new secret value **wasn't** picked up after syncing the secret object or the pod in argo. The only way to pick up the new secret value was to delete/restart the pod. We should find a more automated way to sync secrets and updates.

Ideas:
1. A pre-hook sync
2. Using versions for param store secrets (as we do for the session keys) - currently most of the values pull/reference the latest version
3. Discover other automated sync ideas

**Comment by LindseySaari** [comment]
PR created here: https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/1180#pullrequestreview-1201474262

**Comment by RachalCassity** [comment]
Currently monitoring during auto-sync

**Comment by laineymajor** [comment]
@RachalCassity is there a need to continue monitoring this? Asking as I'm doing a little ZH cleaning (while ZH is working LOL)
