### ISSUE TITLE
[bug] Certificate of Eligibility | Form logic errors

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#50226]
## What happened?
_Describe in detail what went wrong; screenshots, videos, or gifs are strongly encouraged_

LGY recently reported the following form logic errors:
1. If a veteran selects “A restoration of entitlement to purchase a new home” in step 4, the user should not be asked “Do you want to refinance this loan” in step 5
2. If a veteran selects “A restoration of entitlement to purchase a new home” in step 4 and Yes to still owning the property and No to Refinancing the loan Y is selected for entitlement inquiry only when asking for a restoration, Y is selected for one time restoration; however, Veteran did not ask for one time restoration.
3. If a veteran selects “A regular cash-out refinance of a current VA home loan” in step 4, the user should not be asked “Do you want to refinance this loan” in step 5
4. If a veteran selects “An Interest Rate Reduction Refinance Loan (IRRL) to refinance the balance of current VA home loan”, Should not let the user say no to refinance once the user indicates in step 4.  To sell home should be N.
5. If a veteran selects “An entitlement Inquiry Only”  and No to still owning the property and No to Refinancing the loan. To sell home should be N.

They also provided a doc with screenshots of each error. [See Doc.](https://github.com/department-of-veterans-affairs/va.gov-team/files/10134990/VA.Gov.defects.with.logic.for.Step4.and.5.docx)

**UPDATE (12/07/2022):** Today, we had a meeting to discuss the questions above, and to some extent, my responses below. There were a handful of action items coming away from that meeting, some of which supersede the suggestions presented above. Takeaways from that meeting:

- [x] The "Do you still own this property?" question should be **required**, no matter what.
- [x] The "A **restoration of entitlement** to purchase a new home" should be re-labeled as: "A **one-time restoration of entitlement**".
- [x] A new radio option should be created and labeled as: "A **regular restoration of entitlement**".
- [x] "A **regular restoration of entitlement**" should be the first radio option, and "A **one-time restoration of entitlement**" should be the fourth radio option.
- [x] The "An **entitlement inquiry** only" option should be the fifth radio option.

These are the first objectives of this ticket.

These are the questions yet to be answered (I will send these to LGY soon):

**Question 1: Are the following mappings correct?**

|What the vet sees|What we send to LGY|What LGY sees on its dashboard|
|---|---|---|
|A **regular restoration of entitlement**|[See Question 3 below]|[See Question 3 below]|
|A regular **cash-out refinance** of a current VA home loan|cashoutRefinaceRequested: true|Cash Out Refi|
|An **Interest Rate Reduction Refinance Loan** (IRRRL) to refinance the balance of a current VA home loan|irrrlRequested: true|IRRRL Ind|
|A **one-time restoration of entitlement**|oneTimeRestorationRequested: true †|One Time Resto|
|An **entitlement inquiry only**|noRestorationEntitlementIndicator: true|Entitlement Inquiry Only|

Are these mappings correct? Or, is there more nuance?

† **See Question 2**

**Question 2: Are all of the mappings above one-to-one mappings?**

Currently, `noRestorationEntitlementIndicator` is set to `true` if the vet indicates _either_ that the loan is a “one-time restoration of entitlement” or an “an entitlement inquiry only.” Meaning, when a vet selects "entitlement inquiry only", in LGY's dashboard, _both_ "One Time Resto" _and_ "Entitlement Inquiry Only" will be set to "Y". 

Is this correct? Or, should these mappings be strictly one-to-one.

**Question 3: If a user selects "A regular restoration of entitlement" what should we send to LGY?**

As indicated in Question 1, when a user selects one of the radio buttons on Step 4, we relay that information to LGY in our application submission request. See column 2 above. In this case, what should we send to LGY (if anything)?

**Question 4: Under what circumstances should "To Sell home" in the LGY dashboard be set to "Y"?**

Currently, when a user clicks "Yes" for the "Do you still own this property?" question, we convey that intent to LGY in our application submission request, as `propertyOwned: true`. I assume that, in turn, LGY displays "YES" for "Property Owned" in its dashboard. Does that sound right so far? If so, keep reading.

In our application submission request, we also send a `homeSellIndicator` parameter to LGY, which can either be `true` or `false`. I believe this translates to the "To Sell Home" column in LGY's dashboard. Is that right? If so, keep reading.

Currently, we set `homeSellIndicator` to the opposite of `propertyOwned`. In other words, the way we have things set up, "To Sell home" will always be the opposite of "Property Owned". Based on pages 3 through 5 of the doc that Jen sent over, It seems like our existing logic is wrong. So my question is: under what circumstances should “To Sell home” be “Y” or “N”?

**UPDATE (12/09/2022)**

Yesterday, I sent the email above to everyone currently on the `[EXTERNAL] Questions about 500 responses` thread. I am currently awaiting a response. We are likely to get a response sometime next week, after Kelli is back from PTO. In the meantime, we can begin work on the five checkboxed items above. 

Relatedly, today, Sade sent an email to Jen and Kelli asking whether they had any documentation for the business logic for the COE form.

## Specs:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)
- Test User _(if applicable)_:

## Steps to Reproduce
- URL: https://staging.va.gov/housing-assistance/home-loans/request-coe-form-26-1880/
- Test User _(if applicable)_: any user, but you can use User 228.
- See above.

## Desired behavior
- See above.

## Acceptance Criteria
- [ ] See above.

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by data-doge** [comment]
Created two draft PRs to begin addressing these issues.

Emailed the following to LGY and awaiting their response:

```
Thanks again for catching all this. A few questions on Point #1:
On our end, it looks like we currently set `noRestorationEntitlementIndicator` to `true` if the user indicates either that the loan is a “restoration of entitlement” or an “an entitlement inquiry only.” That might explain why “Entitlement Inquiry Only” is set to “Y” in your screenshot of the LGY dashboard. Just to make sure I’m understanding things correctly:
- Does `noRestorationEntitlementIndicator` map to “Entitlement Inquiry Only” on the LGY dashboard?
- And if so, should `noRestorationEntitlementIndicator` be `true` only if the user selects “An entitlement inquiry only” on Step 4?
```
```
A few questions on Point #2:
- On page 2 of the document you attached, you wrote “Y is selected for one time restoration; however, Veteran did not ask for one time restoration.” In that test case, your test user selected “A restoration of entitlement to purchase a new home.” Could you explain what you mean by: “Veteran did not ask for one time restoration” — I think I may be missing something.
- Based on the attached document, it sounds like a “one time restoration” can only be “Y” if the vet selected “A restoration of entitlement to purchase a new home” and they have a prior loan for a property that they still own. Is that right? Are there any additional requirements that I should be aware of?
```
```
A few questions on Points #3-#5:
- If a vet selects “A regular cash-out refinance …,” along with hiding the “Do you want to refinance this loan?” question, should we also assume that the answer to that question is “Yes”?
- In our code, we set “To Sell home” (aka `homeSellIndicator`) to the opposite of “Property Owned” (aka `propertyOwned`). It seems like our existing logic is wrong. Under what circumstances should “To Sell home” be “Y” or “N”?
```

**Comment by Mottie** [comment]
1. Mappings are correct
2. They are one-to-one mappings, except for "regular restoration of entitlement"
3. 'N' for all existing values when "regular restoration of entitlement" is picked
4. `homeSellIndicator` should be set to `null` upon submission

Additional:
- Downloads should open in a new tab

**Comment by Mottie** [comment]
Questions about the logic errors (sent via email as well):

1. If a veteran selects “A restoration of entitlement to purchase a new home” in step 4, the user should not be asked “Do you want to refinance this loan” in step 5
> What happens if the Veteran is adding more than one property? Do _all_ of them need to hide the refinance question?

2. If a veteran selects “A restoration of entitlement to purchase a new home” in step 4 and Yes to still owning the property and No to Refinancing the loan Y is selected for entitlement inquiry only when asking for a restoration, Y is selected for one time restoration; however, Veteran did not ask for one time restoration.
> Is this now the intended behavior? Asking because we have changed “A restoration of entitlement to purchase a new home” to "A one-time restoration of entitlement"

3. If a veteran selects “A regular cash-out refinance of a current VA home loan” in step 4, the user should not be asked “Do you want to refinance this loan” in step 5
> Same as question 1

4. If a veteran selects “An Interest Rate Reduction Refinance Loan (IRRL) to refinance the balance of current VA home loan”, Should not let the user say no to refinance once the user indicates in step 4. To sell home should be N.
> Should we just hide the “Do you want to refinance this loan” question? In this case, are we setting to sell home value to `N` or `null` (since there was a decision to always sent `null`)?

5. If a veteran selects “An entitlement Inquiry Only” and No to still owning the property and No to Refinancing the loan. To sell home should be N.
> In this case, are we setting to sell home value to `N` or `null` (since there was a decision to always sent `null`)?

**Comment by data-doge** [comment]
@saderagsdale Once LGY pushes a fix on their end, we will be able to test these changes on staging and mark this ticket as closed. Venkat will discuss this fix with his team today. To be specific, that fix requires LGY to relax validations on their end to allow Robin's work in https://github.com/department-of-veterans-affairs/vets-api/pull/11393https://github.com/department-of-veterans-affairs/vets-api/pull/11393 to work as intended.

**Comment by data-doge** [comment]
Venkat's team fixed the validation issue. Marking closed.

**Comment by saderagsdale** [comment]
@data-doge to send @saderagsdale the login for testing
