### ISSUE TITLE
Investigate the forms-library upload functionality

### ISSUE THREAD

**Issue by ndsprinkle** [department-of-veterans-affairs/va.gov-team#50233]
### Description

The forms-library supports uploading files that can ultimately be submitted to vets-api. We should investigate how complex this feature is to help the audit team weight forms based on complexity. Additionally, we should investigate using this upload functionality for forms that conditionally require other forms to be filled out. 

### Definition of done

- [ ] We have defined a level of complexity for forms that require additional documentation to be uploaded
- [ ] We have defined this level of complexity for multiple difference scenarios, including things like multiple uploads, large file sizes, uploads inside arrays of objects, etc.
- [ ] We have identified if it is practical to use the upload functionality for conditionally required additional forms in situations where the additional forms are rarely required

**Comment by tbaker1026** [comment]
@ndsprinkle found some [documentation](https://docs.google.com/document/d/1m94dAlyWe25pTFfceZpXWqY1LQf7D2uM/edit) on page 42, can only accept - .pdf, .jpg, .png, .jpeg

**Comment by ndsprinkle** [comment]
To summarize the complexity part of this ticket, I think our initial score of `2` in the airtable is perfectly fair. The front end configuration is more complex than most fields, but not remotely impossible to implement. The back end work is also minor and there seems to be plenty of configuration already in place to handle extracting the attachments from the forms data, validating the attachments, creating new attachment objects to send to Central Mail, and ultimately send to Central Mail.
