### ISSUE TITLE
OOB Deploy Request: vets-website, 988 fix

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-team#50251]
# Instructions

## PRs Related to OOB
- Please provide the list of PRs related to the need for this OOB Deploy
   > https://github.com/department-of-veterans-affairs/vets-website/pull/22834

## Active Daily Users Impacted
- How many active users are impacted at this time and day.
>  Not known.

## Has fix been confirmed in Staging?
- [ ] Yes
- [X] No - not possible til deploy. Was confirmed in an RI.

## Description
- Please provide the details/reason for the OOB Deploy
   > The Veterans Crisis Line 988 line is down. Public Websites needs to update the VCL modal with a different number til it's back up. Needs to deploy ASAP. Thread with authorization to make this change / request OOB: https://dsva.slack.com/archives/C52CL1PKQ/p1669932773949509

   
## Verify The following
 - [X] The OOB Deploy Requests is after the 2pm EST cutoff for regular deploy - [Deployment Policy](https://vfs.atlassian.net/wiki/spaces/SUP/pages/1279787009/Deployment+Policies) and [Deployment Schedules](https://depo-platform-documentation.scrollhelp.site/developer-docs/Deployments.1844641889.html)
 - [X] The OOB Deploy Requests is critial and must be resolved before the next automated deploy.

*Performed by Platform SRE team*
 - [x] PagerDuty OOB Deploy Incident Opened
 - [x] OCTO-DE staff acknowledgment of Request
 - [x] Notification is posted in the appropiate Slack support and team Channels
 - [x] Infrastructure/Operations has acknowledge the Requests
 - [x] Security Team has Reviewed the requests
 - [ ] An Incident Post Mortem is created within two business days

 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-product-support

**Comment by raywangoctova** [comment]
approved
