### ISSUE TITLE
AWS access for Cyril Atarah

### ISSUE THREAD

**Issue by cyriltech** [department-of-veterans-affairs/va.gov-team#50254]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Cyril Atarah

### Your Email

cyril.atarah@oddball.io

### Team, Role, and Company of the target individual

VA Platform, DevOps Engineer, Oddball

### Product Manager (PM) name and email

Joe Tice joe.tice@oddball.io

### Product Owner (PO) name and email

Ray Wang Gang.Wang@va.gov

### Desired AWS Access

New Platform DevOps resource
Configure EKS
Configure VPCs

### Access Expiration

N/A

### Additional Notes

new Platform DevOps resource

### User must exist in a roster before AWS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [x] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by td-usds** [comment]
Reached out to VOR

**Comment by cyriltech** [comment]
Hey @td-usds, any updates?

**Comment by rmtolmach** [comment]
Cyrli is DevOps on the Platform and is requesting access to the `"vsp-operations"` group (**admin access**).

**Comment by BillChapmanUSDS** [comment]
I've reached out to VOR as I'll be taking this process over now that Thomas as moved on.  @cyriltech is still missing an EQUIP date in our records.

**Comment by BillChapmanUSDS** [comment]
EQUIP date received and added. Access approved. Thanks.

**Comment by cyriltech** [comment]
Thank you for the update @BillChapmanUSDS

**Comment by rmtolmach** [comment]
Thanks @BillChapmanUSDS! Don't forget to remove the `Awaiting Approval` label so the Support team knows that they can now create the account.

**Comment by rmtolmach** [comment]
I DM'd the user his credentials.
