### ISSUE TITLE
Replace breadcrumb with "back" link on details pages

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#50272]
## Task Description
* Replace the breadcrumb with a back link on:
     * Appointments list sub-pages
     * Details pages
* Q: Will we make this change before the appointment list redesign?
 
## References
* [Finding 6: The back link was easy to find](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/research/2022-09-appts-list-usability/research-findings.md#6-the-back-link-was-easy-to-find-and-use) - from appointments list usability study.
* Dev ticket - #59814

## Acceptance Criteria
- [x] M/T/D specs in Figma

## Deliverables
- Figma Design 
   - [Design Spec](https://www.figma.com/file/rRC53gTEuva01EKfCdExeS/Appointment-list-navigation?node-id=808%3A9504&t=Qc2PMIDHfhrs6MAC-1)
   - [Desktop Prototype](https://www.figma.com/proto/rRC53gTEuva01EKfCdExeS/Appointment-list-navigation?page-id=13%3A33&node-id=808%3A9504&viewport=-111%2C467%2C0.05&scaling=min-zoom&starting-point-node-id=808%3A9504&show-proto-sidebar=1)
   - [Tablet Prototype](https://www.figma.com/proto/rRC53gTEuva01EKfCdExeS/Appointment-list-navigation?page-id=13%3A33&node-id=953%3A18903&viewport=-111%2C467%2C0.05&scaling=min-zoom&starting-point-node-id=953%3A18903&show-proto-sidebar=1)
   - [Mobile Prototype](https://www.figma.com/proto/rRC53gTEuva01EKfCdExeS/Appointment-list-navigation?page-id=13%3A33&node-id=953%3A18753&viewport=-111%2C467%2C0.05&scaling=min-zoom&starting-point-node-id=953%3A18753&show-proto-sidebar=1)

[Figma design for the confirmation page: Mobile](https://www.figma.com/file/g7bNlDUjuLY8TC9FVacium/Descriptive-back?type=design&node-id=1405%3A18707&mode=design&t=uOiYLJuL0nVRiSbM-1)

[Figma design for the confirmation page: Tablet](https://www.figma.com/file/g7bNlDUjuLY8TC9FVacium/Descriptive-back?type=design&node-id=1405%3A18708&mode=design&t=uOiYLJuL0nVRiSbM-1)

[Figma design for the confirmation page: Desktop](https://www.figma.com/file/g7bNlDUjuLY8TC9FVacium/Descriptive-back?type=design&node-id=1405%3A18709&mode=design&t=uOiYLJuL0nVRiSbM-1)

**Comment by outerpress** [comment]
@Cieramaddox will reach out to mobile and check-in to see how they're handling wording - back v. using the language of the last page.

**Comment by outerpress** [comment]
@Cieramaddox will:
- Add examples of details pages with links
- Hook up the mobile prototype

**Comment by Cieramaddox** [comment]
@JRRoof @ldelacosta cc: @outerpress 
This is ready for review

**Comment by outerpress** [comment]
Not prioritized for PI8, moving to Icebox.

**Comment by outerpress** [comment]
@melissa-lefevre do you have any guidance from mobile app on how they handle descriptive back buttons?

**Comment by melissa-lefevre** [comment]
Here is the documentation around IA
<https://department-of-veterans-affairs.github.io/va-mobile-app/docs/UX/Foundations/Information-Architecture>
from the Mobile App.

*Consistent sense of place:* The app uses multiple wayfinding approaches to
communicate where users are *now* in the app and *where they can go from
there.* Examples of this are displaying global navigation on every screen
in the hierarchy, screen names that are unique and descriptive, using
common screen transitions to communicate a screen's position in the
hierarchy, and including descriptive back labels on each screen

**Comment by outerpress** [comment]
Moving this to the backlog. Need a few changes:
- Scope should be only the details pages, all other breadcrumbs stay the same.
- Back link should use the format < Back to [H1 of previous page]
    - This is the descriptive back link format used by mobile and checkin

**Comment by melissa-lefevre** [comment]
[https://app.zenhub.com/files/133843125/240e5dbb-d1d4-4bc8-b3e3-481be82b0fa5/download](https://app.zenhub.com/files/133843125/240e5dbb-d1d4-4bc8-b3e3-481be82b0fa5/download)

**Comment by outerpress** [comment]
@melissa-lefevre [Design Council approved this](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1847), with a couple of accessibility notes. Could you annotate the design files with the accessibility note:

* Semantically it should be in a <nav> element with the aria-label "Breadcrumb"

**Comment by melissa-lefevre** [comment]
I added those annotations to the file. Closing this ticket.

**Comment by outerpress** [comment]
Reopening and moving to Dev column

**Comment by outerpress** [comment]
@melissa-lefevre could you add mockups to the design file that show the descriptive back link in the context of a:
- [Confirmed request details page](https://www.figma.com/file/twogqAIoOL9WAFRqvUbwiS/VAOS-Templates?type=design&node-id=867-27744&mode=design&t=icdp5UfjqbzLHJz6-4)
- [Confirmed upcoming appointment details page](https://www.figma.com/file/twogqAIoOL9WAFRqvUbwiS/VAOS-Templates?type=design&node-id=867-26448&mode=design&t=icdp5UfjqbzLHJz6-4)

**Comment by melissa-lefevre** [comment]
I added the confirmation pages to the deliverables, however it is detailed in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/61086)
