### ISSUE TITLE
Create a Shared Access Platform to support proxy access

### ISSUE THREAD

**Issue by elizabethmkoch** [department-of-veterans-affairs/va.gov-team#50279]
Give Veterans the ability to voluntarily grant full or partial access to their VA data and services to their loved ones and those who care for them. Veterans needs to be able to manage the level and duration of access.

## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/login.gov-adoption/products/nvur)

## High Level User Story/ies
As a Veteran, I want to be able to give others differing levels of access to my account, so I can empower them to provide greater care and support to me.

**Comment by lmorris3** [comment]
Closing this epic - no stories and outdated now.
