### ISSUE TITLE
[Due by 01/28] Add onboarding modal to new VAMC website

### ISSUE THREAD

**Issue by andrewlewandowski** [department-of-veterans-affairs/va.gov-team#5029]
**As a user on the new va.gov/pittsburgh-health-care website, I want an informational message about the new website the first time I access it so I know that it replaced the old website.**

**NOTE:** This must be in production by the end of day on Tuesday, Jan. 28, 2020

**Acceptance criteria:**
- Modal copy (title, body, and call to action) is published in the modal:
`Title:` Welcome to the new VA Pittsburgh health care website—built with Veterans, for Veterans
`Body:` You spoke, and we listened. We used feedback from Veterans, family members, and caregivers like you. Our new website focuses on helping you manage your VA health care journey, including the top tasks we heard were most important to you.
`CTA:` Continue to the website
- A user only gets the modal once; once the user dimisses it, it never shows again (unless they clear their browser cache)
- A user gets the modal no matter how they got to the new website (from and old pittsburgh.va.gov URL, from a Google search result, by typing in a new va.gov/pittsburgh-health-care URL, etc.)
- The user gets it the first time they visit the website, even if that’s a deep-linked page like https://www.va.gov/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/

**Other notes:**
- We can recycle the new VA.gov onboarding modal that is currently in production (see screenshot below in the comments)
- We will want to implement this same modal+copy each time we launch a new VAMC wensite (~143 over the next two years)

**Comment by andrewlewandowski** [comment]
![Screen Shot 2020-01-21 at 11.24.21 AM.png](https://images.zenhubusercontent.com/5abe69bc4b5806bc2bcd0ead/1c3763dd-38d4-4b10-91a5-7c2d9157a006)

**Comment by MickinSahni** [comment]
Added this to VSA sprint 13 and added 3 points! @Karak888 we'll need to drop into our sprint report :)

**Comment by Karak888** [comment]
modal exists but will need to update content it appears to be specific to Pittsburgh- https://dsva.slack.com/archives/C52CL1PKQ/p1579638417174000?thread_ts=1579636848.167000
to be implemented on every pittsburgh-health-care/.....

**Comment by ncksllvn** [comment]
@andrewlewandowski can this be merged sooner than 1/28? As in, is it okay for the Pittsburgh welcome modal to show on Monday?

**Comment by andrewlewandowski** [comment]
@ncksllvn - This can go live before the launch on Wednesday, no problem!

**Comment by MickinSahni** [comment]
Closing this issue out as pr's merged
https://github.com/department-of-veterans-affairs/vets-website/pull/11565
