### ISSUE TITLE
Va.gov Redirects - Establish Drupal as source of truth for redirects on www.va.gov

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#503]
## User Story or Problem Statement
As a content editor, I need to be able to change redirects as my site is being migrated to VA.gov so that Veterans can access the information they need.

### High Level User Story/ies or Description: 
We currently keep redirect information in vagov-content, but we should use the Drupal API as the source of truth for redirects going forward.

We'll need to get a schema for the structure of redirect data in Drupal as well as some test data in the dev Drupal instance to work on this.

## VSP Objective (Q1 & Q2 2020)
O1: Any volume of simultaneous customers have a delightful, self-service, end-to-end experience using the Platform to build on VA.gov.

## Measuring Success (KRs/KPIs)
- [ ] [VSP KR] Reduction in volume of “non-human-needed” support requests month over month
- [ ] [VSP KR] Increase in customer NPS

## Goals
Set Drupal as the source of truth for redirects.

**Comment by ricetj** [comment]
Connected PR: https://github.com/department-of-veterans-affairs/devops/pull/4282

**Comment by ricetj** [comment]
(03/20/2019)
This has been removed from the MVP. I'm going to drop from current sprint and put back to ready for now.

**Comment by ricetj** [comment]
https://dsva.slack.com/archives/CDJQ0JCE4/p1572633390094700?thread_ts=1572551914.087100&cid=CDJQ0JCE4

**Comment by meganhkelley** [comment]
Please keep VSP Content & IA posted as y'all begin working on this!

**Comment by ricetj** [comment]
Need to talk to Robbie and Jeff B @ricetj on the future of this.
