### ISSUE TITLE
Design content that tells a user where to get help throughout the Login.gov set up

### ISSUE THREAD

**Issue by elizabethkochBT** [department-of-veterans-affairs/va.gov-team#50303]
We should gather and then design content that shows where a Veteran can get help when they're setting up Login.gov. This might look like an easy to navigate contact or resource list, including the general VA helpline. We can custom VA targeted help pages from Login.gov.

Considerations:
- gathering and organizing contact list, designing flows and content, throughout different journeys
- collaboration with Login.gov
- touch-points like the current contact page and and Ask VA

**Comment by tygindraux** [comment]
Discussed today in refinement. We've captured this in other tickets and this is now duplicative. Closing this out.
