### ISSUE TITLE
Shareable materials about Login.gov for peer-to-peer interactions (and MHV coordinator, VSO, TAP)

### ISSUE THREAD

**Issue by elizabethkochBT** [department-of-veterans-affairs/va.gov-team#50336]
Leverage the dedicated, hands-on support that Veterans organically provide to fellow Veterans.

Create shareable content for Veteran use / sharing, eg.,:

- Step-by-step set-up instructions with pictures
- Troubleshooting content easily sharable
- Creating 'talking points' for Veterans who want to help a fellow Veteran

Secondary benefit of materials for VA employees who help Veterans more frequently.

**Comment by tygindraux** [comment]
Discussed at refinement on Apr 20. Captured this in other tickets. Closing this.
