### ISSUE TITLE
Remove (DS Logon) and deprioritize (MHV) less preferred sign in options for all VA services - Use the power of the default

### ISSUE THREAD

**Issue by elizabethkochBT** [department-of-veterans-affairs/va.gov-team#50330]
Craft a plan to eventually exclude non-preferred login methods
- Make Login.gov the default option with credential fields already present and other credential options only visible when actively selected
- A timeline to determine sequentiality of login option eliminations

Considerations:
- Review other services successfully using Login.gov
- Review other services with only 1-2 login options

**Comment by tygindraux** [comment]
This is a duplicate now. I'm going to close.
