### ISSUE TITLE
OOB Deploy Request

### ISSUE THREAD

**Issue by AGarcia-Clarity** [department-of-veterans-affairs/va.gov-team#50352]
# Instructions
Fill out Details of need and the PRs related to OOB sections below.

## PRs Related to OOB
- Please provide the list of PRs related to the need for this OOB Deploy
> [Scope headers to Save in Progress PR](https://github.com/department-of-veterans-affairs/vets-website/pull/22851)
> [Remove global headers from apiRequest](https://github.com/department-of-veterans-affairs/vets-website/pull/22849)

## Active Daily Users Impacted
- How many active users are impacted at this time and day.
>  ~1800
## Has fix been confirmed in Staging?
- [x] Yes (Alexander Garcia verified Save in Progress forms; Adrian Rollett verified Pre-Checkin is still working as expected)
- [ ] No

## Description
- Please provide the details/reason for the OOB Deploy
   > Removing the global headers (*Content-Type: application/json*) from the `apiRequest` fixed the issue with pre-checkin not working as expected ([more about why this is an issue here](https://dsva.slack.com/archives/CBU0KDSB1/p1670085444644439?thread_ts=1670033511.891859&cid=CBU0KDSB1)) which the Save in Progress expects these headers to update and delete a saved form.  This will add the expected headers back to the Save in Progress requests to re-enable it's functionality.
   
## Verify The following
 - [x] The OOB Deploy Requests is after the 2pm EST cutoff for regular deploy - [Deployment Policy](https://vfs.atlassian.net/wiki/spaces/SUP/pages/1279787009/Deployment+Policies) and [Deployment Schedules](https://depo-platform-documentation.scrollhelp.site/developer-docs/Deployments.1844641889.html)
 - [x] The OOB Deploy Requests is critial and must be resolved before the next automated deploy.

*Performed by Platform SRE team*
 - [x] PagerDuty OOB Deploy Incident Opened
 - [x] OCTO-DE staff acknowledgment of Request
 - [x] Notification is posted in the appropiate Slack support and team Channels
 - [x] Infrastructure/Operations has acknowledge the Requests
 - [x] Security Team has Reviewed the requests
 - [x] An Incident Post Mortem is created within two business days

 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-product-support

**Comment by raywangoctova** [comment]
approved

**Comment by powellkerry** [comment]
Postmortem: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/655
