### ISSUE TITLE
Access for Peter Hill

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#5037]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffrey Hayter
- Please provide your name.
   > Peter Hill
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VSP/Product Support - QA Engineer
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Internal%20Tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDVsUlqScUwCJy1s4Kr79mcGSybWsx3eyX9I6Fm+75r06SifdWzGPBAMUy8Jejd5/0glxy0yuHkOZ6Atl52G/VATqDvIsjkKwUQ1Lbp3qYiSqBLhPdBcKrGIbjFkrWWupbokgm4OKOZsIhS56XL7CQNNtMwNbnocbsQlJ6edVWkdddD9xpLbZ5T/9F6Vj0QLlH7IZ65GNOcbTb5g0MfNx3T9zR8w3tkP9zTBrCl+gazQm/X17iESh0DOYa6iwpgaV46OEgwaLwFUDZj7jIn4W4j6UfS9pMsFerQqYxbGPUSmPexrqPV96iOfFH+ulifmZVggAKHdlKhj+5z1ZAoSi3F root@THEFLOOD
```

- [Grant AWS Console access?]
  > YES
  >  I would like shell access to staging in order to be able to run various rake tasks there that will provide information relevant to testing.  I need to run the tasks on staging because they require integration with real services in order to provide useful information.

**Comment by pjhill** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by tskinn** [comment]
@Jeff-Hayter

**Comment by ricetj** [comment]
Jeff, Peter is using the new process for SOCKs Access, but he is still requesting AWS Access

**Comment by jbritt1** [comment]
First time login credentials provided to user via Slack.
