### ISSUE TITLE
[Refactor] Fix Sign in Service Refresh

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#50387]
## Description
This will fix the way the `/refresh` functionality works.

## Tasks
- [x] Implement `fetch-retry` for OAuth only when the Access token is expired
- [x] Use unit tests & manual tests to verify functionality

**Comment by alyssagallion** [comment]
Going through unit tests. On pause for OCC mobile.

**Comment by AGarcia-Clarity** [comment]
### *UPDATE:*
- Integrating `fetch-retry` into our `fetchAndUpdateSessionExpiration` function caused a lot of unit tests to break (385 unit tests) because they are mocking the implementation of `fetch`.

### Status as of 12/20/2022:
- 192 unit tests completed
- 193 unit tests still outstanding.

**Comment by AGarcia-Clarity** [comment]
### *UPDATE:*
- Fixed issues that caused 384 unit tests to fail

### Status as of 12/24/2022
- 6 unit tests that were failing are fixed
- Requested feedback from teams that requested changes
