### ISSUE TITLE
Suggested update to conversation guide template

### ISSUE THREAD

**Issue by rbsingleton** [department-of-veterans-affairs/va.gov-team#50386]
### Description
Currently in conversation guide template for moderated studies, participants are asked whether they are okay with having observers in their session before they have been explained what the interview will be about - including the types of things they will be asked or what they will be asked to do. Participants cannot give true informed consent to being observed if they are not informed on what the session will be about. 

I recommend moving the part in the template where observers are allowed into the session to after the researcher has described to the participant what they will be asked about, what they will be asked to do, and the fact that they can choose not to answer or to end the session whenever they want. 

<img width="1063" alt="image" src="https://user-images.githubusercontent.com/100814257/205741830-f4ece05d-042c-4320-b490-4bb0b984be60.png">

### Relevant URLs

[Conversation guide template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/conversation-guide-template.md)

**Comment by naomimarcussen** [comment]
The template has been edited with approval from Shane Strassberg.

**Comment by laucon** [comment]
@naomimarcussen Is there anything you need me to do?

**Comment by rbsingleton** [comment]
Thanks @naomimarcussen !

**Comment by naomimarcussen** [comment]
@laucon Nope, I think we're good. We can close.
