### ISSUE TITLE
Review 129 Additional forms 

### ISSUE THREAD

**Issue by tbaker1026** [department-of-veterans-affairs/va.gov-team#50381]
[Airtable Link](https://airtable.com/app8r8N52jBfzOkMb/tblYHPlW3Sv5bNBRq/viwD0kzKK6gcTeUji?blocks=hide)
Tricia 1-43
Jeana - 44 - 86
Pat - 87-129

- [x] Check to see if they are on find a form

- [x] If Veteran facing fill out the additional audit fields

**Comment by jeana-adhoc** [comment]
of the 129, only 6 were in find-a-form. Their fields were updated appropriately, and accessibility scan was done (all simple errors)
