### ISSUE TITLE
AWS access for Lucas Draney

### ISSUE THREAD

**Issue by ldraney** [department-of-veterans-affairs/va.gov-team#50409]
### COR Name

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Lucas Draney

### Your Email

lucas.draney@oddball.io

### Team, Role, and Company of the target individual

VA Notify, DevOps Engineer, Oddball

### Product Manager (PM) name and email

Em Allan, emily@oddball.io
Melanie Jones, melanie.jones@oddball.io

### Product Owner (PO) name and email

Beverly Nelson

### Desired AWS Access

As a DevOps Engineer, my work is primarily in the cloud.  Currently the services we use I'll list here, though I will likely have to request more permissions as my work continues.  Roles that include the following services may be sufficient:
VPC
ALB
ECR
ECS
Fargate
RDS
Pinpoint
Kinesis
Lambda
SQS
EC2
IAM (for these services to communicate with eachother)
SSM (for these services to communicate with eachother)

### Access Expiration

ongoing

### Additional Notes

My COR is Laurene Cook
As a DevOps Engineer, my SRE work is in the cloud, thus ongoing permissions are important to my daily work. 

It is very important I have access to the AWS CLI.  Once I have login credentials to the console, I should be able to set that up myself.  However, I have been warned that may not be true.  If there is additional security, please give me the relevant information I need for my ~/.aws/config file.  

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by jbritt1** [comment]
### AWS Access

User: Lucas Draney
COR: Laurene Cook
VOR: Amber Malcom
Approval needed: @department-of-veterans-affairs/operations-aws-approvers 
Admin level: no

**Comment by jbritt1** [comment]
**Please note** for whoever handles this access request once approved: Lucas is an attached DevOps Engineer for VA Notify team and will likely need a policy created for that role if one does not yet exist using the devops template: https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/base_devops_policy.tftpl

**Comment by td-usds** [comment]
Reached out to VOR

**Comment by td-usds** [comment]
Trying to validate some claims inside the request

**Comment by k-macmillan** [comment]
@td-usds 
Lucas just needs adfs-project-administrator access for the VA Notify account.

**Comment by k-macmillan** [comment]
If we can push advanced access to another ticket after he has our standard access, that would be preferable.

**Comment by jbritt1** [comment]
@k-macmillan, this ticket is used for the dsvagovcloud account. The VSP folks do not have access / maintain control of the va-notify AWS account. That will likely require a ticket with the VAEC.

**Comment by BillChapmanUSDS** [comment]
It appears that this request needed to be forwarded elsewhere.  Still getting up to speed on this process,  is there still something that is required in this request beyond the notify access that is handled elsewhere?

**Comment by ldraney** [comment]
I'm pretty sure this is resolved.

**Comment by little-oddball** [comment]
Close as resolved.
