### ISSUE TITLE
Adding Kelly Van Orden to DSVA Slack

### ISSUE THREAD

**Issue by regenauer-va** [department-of-veterans-affairs/va.gov-team#50414]
Good afternoon,

I am requesting Kelly Van Orden be added to the DSVA workspace as a multi channel user. 

Email: vanorden_kelly@bah.com
Channels:
team-of-teams-slide-collection
vfs-all-teams
vfs-platform-support

Thank you!

**Comment by eunicegar** [comment]
this is done.
