### ISSUE TITLE
AWS Access for Lee Warrick

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#50411]
### COR Name

Ray Wang 

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Lee Warrick

### Your Email

lee.warrick@oddball.io

### Team, Role, and Company of the target individual

Platform Tech Team 2, DevOps Engineer, Oddball

### Product Manager (PM) name and email

Jesse House, jesse.house@adhocteam.us

### Product Owner (PO) name and email

Mike Chelen, michael.chelen@va.gov

### Desired AWS Access

Platform DevOps engineer 

### Access Expiration

ongoing

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [x] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [x] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [x] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by jhouse-solvd** [comment]
cc: @ph-One for tracking

**Comment by mynar7** [comment]
Listed in both rosters.

**Comment by raywangoctova** [comment]
@jhouse-solvd approved, but please update the ticket COR to me. The user is approved for the contract award's annual period of performance while the person is in this role. If PoP ends, the role changes, or per VA direction, the approval is rescinded immediately.

**Comment by jhouse-solvd** [comment]
@raywangoctova - Thank you! I updated the ticket COR to your name. And sorry for the confusion! I'd not filled one out in a while, but I'll remember this going forward.

**Comment by jhouse-solvd** [comment]
@pjholyoke - OCTO approved this request. As time allows, please configure perms on @mynar7's behalf. 

Thank you! And let me know if you need anything from me.

**Comment by pjholyoke** [comment]
Should be all set now.
