### ISSUE TITLE
VA Request Flow - Add station id to comments field (Acheron)

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#50436]
## Description
The selected child Facility for VA appt requests are not getting properly populated in VS GUI. To account for this, VAOS FE will need to start sending the Station Id in the patient comments field.

---

## Acceptance Criteria
Background: the `va_online_scheduling_acheron_service` toggle is on

Given the user is in the VA request flow 
When the user selects a facility, the facility station Id should be passed in the `reasonCode.text` field.

## Suggested format: 

`Station id: 123`

## Suggested Order for the comment fields: 
1.  Station id
2.  Preferred Modality - #49337
3.  Contact Information (phone # and email) - #47730
4.  1st, 2nd and 3rd Preferred Dates #47660
5.  Reason Code abbreviation and comments  #47734

### Design Assets
No changes in the design 

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by ldelacosta** [comment]
@marcynadeau - Please validate and let us know if you have any issues. Thanks!

**Comment by ldelacosta** [comment]
This has been validated by SQA. No issues reported. Closing out the ticket. 
[Reference thread slack](https://dsva.slack.com/archives/CMNQT72LX/p1670531559949119)
