### ISSUE TITLE
Copyedit What your claim status means R&S article

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#50465]
## Issue Description

Beth made plain language edits to our [What your claim status means](https://www.va.gov/resources/what-your-claim-status-means/) article. We need to do a copyedit in drupal and confirm before publishing.

Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=8548

## Tasks
- [x] Copyedit (Megan)
- [x] Confirm with Beth and publish (Megan)

## Acceptance Criteria
- [x] Article is copyedited to meet VA plain language standards

**Comment by megzehn** [comment]
Confirming that this has been copy edited! The changes look good.

**Comment by megzehn** [comment]
Confirming that this has been published! CC @RLHecht

**Comment by RLHecht** [comment]
Closing ticket!
