### ISSUE TITLE
<Content Review> from <Voicebot>

### ISSUE THREAD

**Issue by goodenoughgraceVA** [department-of-veterans-affairs/va.gov-team#50472]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [ ] Making revisions to an existing online form, app, or tool on VA.gov
- [ X] Something else (please add details in the next question)

## What do you need help with?
  - [ X] Content support
  - [ ] IA support
  
*Please be specific about the content or IA support you need and provide any additional documents and/or links that will help us help you. If we need to add a react widget to a page, be sure to provide the code here.*

The Voicebot team would like content support from a copy editor to collaborate with for content review and editing, ensuring that we are following the VA.gov content style guide and plain language standards. Our content covers the following topics: claims status, general claims FAQs, PACT Act, error messaging and product introduction messaging. We conduct most of our content editing on MURAL; links are included below.

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [ ] Yes
  - [ ] No
  - [ X] N/A
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
## When do you expect to launch your product to 100% of users?
N/A. We are currently in the prototyping phase while we procure platform licenses. 
  
*Please provide an estimated date so our team can create other relevant tickets.*
  
## Supporting artifacts
*Please provide supporting artifacts as available.*

- Link to product outline:
- Link to or attach user flows: https://app.mural.co/t/bahdigitalexperience6902/m/bahdigitalexperience6902/1663170174646/6ef8ac6c93aacf1beeb0a505cc67578b7c78e5b1?sender=ub4ba85146c3e3e3585013902
- Link to prototype or mockups: 
- Link to content charts: https://app.mural.co/t/bahdigitalexperience6902/m/bahdigitalexperience6902/1665511952584/3ed911a5a4198f9c9c469abbe6d49bc146151b03?sender=ub4ba85146c3e3e3585013902
- Link to any epics/issues that may be helpful:

## Will this work be going through the Collaboration Cycle?
- [X ] Yes 
- [ ] No

## When does this work need to be done?
- Estimated launch date: N/A
- Estimated staging review date:
- Content and IA work needed by: 2/10/23

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [X ] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: Luciana Morais
-	Product manager: Gian Bustillo
-	Content designers: Grace Goodenough and Sunayna Goel
-	Lead engineer: Millie Mamedova
-	Product/team Slack channel: https://join.slack.com/share/enQtNDQ4MzE3Mzg1NDQzNS0wNGQ5ZmNlYzAyMTMxZmRiNGZmZGVkYzJmNmY2N2E3MTExMmFlZjQ1NDFhZTE2OGIzZGQwNWRkNmMyZDZhMTdi

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by goodenoughgraceVA** [comment]
Link to content excel sheet:
https://boozallen.sharepoint.com/:x:/t/VAOmnichannelPTEMS/EeBGy0Dg_Z5CjmZUKFONzQ8B6u9sCqYw45W_Glttq0ld8Q

**Comment by goodenoughgraceVA** [comment]
Link to content sheet: [https://dvagov.sharepoint.com/:x:/s/VoiceBot/EQFLqwokAOdIr0Y6q3sKayQBiuk3eRGaINnzzT_Cm658VA?e=yLaS4r](url)

Link to content schedule: [https://app.mural.co/t/bahdigitalexperience6902/m/bahdigitalexperience6902/1673466679915/942e7634bb9ca0913f231cf993a990df194e0020?sender=ub4ba85146c3e3e3585013902](url)

**Comment by megzehn** [comment]
Thanks, @goodenoughgraceVA! 

Confirming that the first batch of text is ready for you (intro, welcome, and goodbye).
