### ISSUE TITLE
Adding [Michelle Dieudonne Yenyo] to DSVA Slack

### ISSUE THREAD

**Issue by MichelleDieudonne** [department-of-veterans-affairs/va.gov-team#50476]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

<describe the request>

Are you requesting to add an individual as a:

- Full member
- Single guest
- Multi-channel
- Switching from single-channel to multi-channel?
- What channel(s) do they need to be added to?

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add [_insert email_] as a single-channel guest to [_channel name_].
- Please add [_insert email_] as a multi-channel guest to these channels: [_channel names_].
- Please add [_michelle.dieudonneyenyo@va.gov_] as a full member.
- Please change the status of [_slack username_] from [_current status_] to [_desired status_]

**Comment by eunicegar** [comment]
done

**Comment by MichelleDieudonne** [comment]
@eunicegar I am trying to get into this Slack space and I'm getting this message, "It looks like there isn’t an account on Digital Service @ VA tied to this email address."  

These are links I am trying to use to get there: 

http://dsva.slack.com/
https://app.slack.com/client/T03FECE8V/C681JK9NV/rimeto_profile/UBY0YS3QX

**Comment by MichelleDieudonne** [comment]
I just replied to this issue.  I am getting a message that there is not Slack account set up for this email address.

From: Eunice García ***@***.***>
Sent: Wednesday, December 7, 2022 8:09 PM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Dieudonne Yenyo, Michelle R. (Booz Allen Hamilton) ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Adding [Michelle Dieudonne Yenyo] to DSVA Slack (Issue #50476)


Closed #50476<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdepartment-of-veterans-affairs%2Fva.gov-team%2Fissues%2F50476&data=05%7C01%7C%7C12ae24c572494ac572c908dad8b8cf67%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C638060585516547333%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=PdxHWvrWtHH%2Bh637%2BoFWp%2Fd8q%2B6inuVBOqVqAXuY7ew%3D&reserved=0> as completed.

-

**Comment by eunicegar** [comment]
For some reason, when sending the invite again, your email showed as duplicate, but when searching for your first and last name, I couldn't find you. 

I corrected your name spelling and resent invitation.

**Comment by MichelleDieudonne** [comment]
Thank you, I was able to get in.

From: Eunice García ***@***.***>
Sent: Thursday, December 8, 2022 10:07 AM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Dieudonne Yenyo, Michelle R. (Booz Allen Hamilton) ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Adding [Michelle Dieudonne Yenyo] to DSVA Slack (Issue #50476)


For some reason, when sending the invite again, your email showed as duplicate, but when searching for your first and last name, I couldn't find you.

I corrected your name spelling and resent invitation.

-
