### ISSUE TITLE
Missing Breadcrumb link on mobile view 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#50487]
## Summary
When the user is on the VAOS app using a mobile device, the user cannot access the breadcrumb links if the size exceeds `482`. If it below `482`, the breadcrumb links are accessible. 

## Specs
- Device: Mobile view 
- Browser: Chrome (Version 108.0.5359.94 (Official Build) (x86_64)) 

## Steps to Reproduce

1. Go to: staging.va.gov on a mobile device 
2. Login as grethel.g.petryniec@id.me 
3. View the details for an upcoming appointment in VAOS  in the mobile view 
4. Change the width to 482

![staging_va_gov_health-care_schedule-view-va-appointments_appointments_cc_110168__2_.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/4e5fc9de-5898-4aa1-b730-b7976071c57a)

### Actual Result
The user does not see the breadcrumb links in the mobile view. 

### Desired Result
The user should be able to click on the breadcrumb to navigate between the pages in VAOS. 

## Definition of Done
- [ ] Desired result is achieved and/or document decisions made
- [ ] Relevant documentation is updated

**Comment by ldelacosta** [comment]
This was closed by accident. Re-opened the ticket.

**Comment by vbahinwillit** [comment]
Unable to reproduce in staging. Seems to be working. Please verify.

Thanks

**Comment by ldelacosta** [comment]
The issue cannot be reproduce again. Closing out the ticket.
