### ISSUE TITLE
AWS access for William (Bill) Chapman

### ISSUE THREAD

**Issue by td-usds** [department-of-veterans-affairs/va.gov-team#50498]
### COR Name

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative Name

Other - please specify in 'Additional Notes'

### Your Name

William Chapman

### Your Email

william.chapman7@va.gov

### Team, Role, and Company of the target individual

OCTO-DE SRE Lead

### Product Manager (PM) name and email

N/A

### Product Owner (PO) name and email

N/A

### Desired AWS Access

- Bill requires at the very least Global Read-Only access at this point in time

### Access Expiration

Ongoing

### Additional Notes

Bill is the Government OCTO-DE SRE Lead on Platform.
Bill will not be on the VFS Roster because he is part of OCTO-DE.

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [x] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by td-usds** [comment]
Approved

**Comment by rmtolmach** [comment]
I'm Tier 2 support and Peter asked me to do this a few days ago. Bill does not have access yet. I will have a PR up shortly.

**Comment by rmtolmach** [comment]
Access granted and credentials sent to user over Slack DM.
