### ISSUE TITLE
Create content templates for details pages

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#50508]
## Task Description
* Add a content template for details pages to the templates file.
* Update the global headers and footers in the design system to match staging.

## References
* [Figma Link](https://www.figma.com/file/RcDljBwThbwVDkNrDH2xiA/Appointment-Details-Redesign?type=design&node-id=1631%3A60572&mode=design&t=Vuib6NulfUIVd67O-1)

## Acceptance Criteria
- [ ] M/T/D content templates for details pages 
- [ ] Global headers and footers are updated

**Comment by outerpress** [comment]
Can't start until we decide to fully redesign the details pages

**Comment by Cieramaddox** [comment]
[Content template](https://www.figma.com/file/RcDljBwThbwVDkNrDH2xiA/Appointment-Details-Redesign?node-id=943%3A24476&t=2Wpg7q6017HyFrB3-1) in the works

**Comment by outerpress** [comment]
Not prioritized for PI 8, moving to Icebox
