### ISSUE TITLE
(Samara) Re-visit guidance for access to certain links

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#50509]
### Tasks

- [x] Add guidance on access-related explanations for certain websites, links, etc.) to the style guide checklist, in the hyperlink section: https://vfs.atlassian.net/wiki/spaces/AP/pages/2438856880/Style+Guide+Checklist

**Comment by laucon** [comment]
Ideas I've written: Create new client certificates issued by the VA by following instructions [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/1644625921/Obtain+or+Renew+Publicly+Signed+SSL+Certificates). (Some users may be unable to view these instructions, depending on their permissions.)

**Comment by laucon** [comment]
More ideas I've written: Major version upgrades should be tested in the daily accessibility scan as well. [This page](https://vfs.atlassian.net/wiki/spaces/TTT/pages/2306703395/How+to+Monitor+the+Daily+Accessibility+Scan#Updating-the-Scan) describes how to run the daily accessibility manually for testing purposes. (Users who aren’t on Platform teams may be unable to view this document.)

**Comment by laucon** [comment]
Even more ideas I've written: If you’re on a Platform team, you need to be listed on the [Platform Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623). (<-- This Confluence link is only accessible to Platform team members.)
