### ISSUE TITLE
BE | Profile | Update Swagger and Docs for MHV endpoint

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#50516]
## Background
Adam Whitlock pointed out that the `/v0/mhv_account` endpoint is missing from the swagger docs.  The account pages uses the _accepted terms and conditions_ field.  This endpoint is also missing from BE documentation.

## Tasks
- [x] Update Swagger documentation to include `/v0/mhv_account` endpoint.
- [x] Update BE docs to include `/v0/mhv_account` endpoint.

**Comment by tpharrison** [comment]
@SKasimow - just letting you know that this unplanned work came up.

**Comment by SKasimow** [comment]
YAY!! I got a notification !!
