### ISSUE TITLE
Supplemental Claims React Widget content from Benefits Team 1

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#50515]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [ ] Making revisions to an existing online form, app, or tool on VA.gov
- [x] Something else (please add details in the next question)

## What do you need help with?
  - [x] Content support
  - [ ] IA support
  
In order to prepare Supplemental Claim form for release, we've added a feature flag and will need to include a link to start the online form on the [Supplemental Claim info page](https://staging.va.gov/decision-reviews/supplemental-claim/)

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [x] Yes
  - [ ] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
## When do you expect to launch your product to 100% of users?
  
*Please provide an estimated date so our team can create other relevant tickets.*
  
## Supporting artifacts
*Please provide supporting artifacts as available.*

- Link to product outline: [Supplemental Claim product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/decision-reviews/Supplemental-Claims)
- Link to or attach user flows: [Supplemental Claim flow](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Supplemental-Claims/design/supplemental-claims-flow.md)
- Link to prototype or mockups: [Supplemental Claim design](https://www.sketch.com/s/d2416db4-9a4f-4919-abe4-20ba4bdcfd89#Version)
- Link to any epics/issues that may be helpful:
  - Epic: [Supplemental Claim | Build the form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/48138)
  - Related frontend work [#48808](https://github.com/department-of-veterans-affairs/va.gov-team/issues/48808)

## Will this work be going through the Collaboration Cycle?
- [x] Yes 
- [ ] No

## When does this work need to be done?
- Estimated launch date: TBD - we were aiming for late January, but may be pushed later
- Estimated staging review date: TBD
- Content and IA work needed by: mid-January

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: Benefits Team 1
-	OCTO-DE product owner: Matt Self
-	Product manager: Sade Ragsdale
-	Designer: Eileen Chi
-	FE engineer: Robin Garrison
-	Product/team Slack channel: \#benefits-team-1

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by megzehn** [comment]
Hello! Here are copy edited versions of the Supplemental Claims page widget. Let me know if there are any questions!

CC @RLHecht and @katherine-fung @Mottie 

[supplementalclaims_noonlinetool_copyedited.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/10449785/supplementalclaims_noonlinetool_copyedited.docx)
[supplementalclaim_copyedited.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/10449787/supplementalclaim_copyedited.docx)

**Comment by saderagsdale** [comment]
@eileen-coforma The links to the widget content for supplemental claims are above. Can you take a look and let me know if this aligns with the discussions you've had with @katherine-fung?

**Comment by Mottie** [comment]
The docs show _all_ the content in that section... what specifically will we need to change?

**Comment by katherine-fung** [comment]
The headers on the page with the online tool is different than the headers on the page without the tool.

On the page with the tool, there's an H3 "For all types of claims." 

The page without the tool doesn't have that H3. So the subsequent headers in that section have different styles than the headers on the page with the tool.

**Comment by katherine-fung** [comment]
@RLHecht - that's  correct.  cc @Mottie

**Comment by mnorthuis** [comment]
Connecting the IA ticket here for reference.  That will provide the info on entry points needing including the parent content page. 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/48796

**Comment by Mottie** [comment]
@RLHecht I think we can close this ticket too. Thanks!

**Comment by RLHecht** [comment]
Yep, this is good to close!
