### ISSUE TITLE
Salesforce Issues Triage

### ISSUE THREAD

**Issue by Kimberley2019** [department-of-veterans-affairs/va.gov-team#5052]
## User Story or Problem Statement
As a Call Center Lead, I need to document the steps taken to capture, track, and triage Salesforce issues so I can relay the information back to all teams in order for them to research and resolve. 

## Goal
Ensuring that the entire Salesforce process is documented to show issues, tracking, and any roadblocks that are experienced when attempting to triage.

## Objectives or Key Results this is meant to further
- _lorem ipsum_

## Acceptance Criteria
- [ ] _What needs to happen or be created?_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by joanneesteban** [comment]
### Grooming Follow Up

@Kimberley2019 whenever you get the chance, can you post the progress on the documentation?

**Comment by Kimberley2019** [comment]
The steps taken to capture and track SalesForce issues can be found here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/call-center/tier-3-escalation-process.md

Current State of SalesForce:

VEO Tier 1 agents currently capture information from the callers and notate the SalesForce issue with the following:

Callers name
Callers contact information (If the caller is willing to provide)
Brief description of the issue the caller is experiencing (case notes)
Subject
Status (this is usually going to be a closed status)

Challenges:
Agents can be very vague on the issue.
    Not enough information being provided in order to determine if this is an issue that needs to be handled by our team(s).
 Contact information can be incorrect or non existent.  
    In many instances the caller is notated as anonymous
      There are two generic phone numbers listed in these instances on all tickets marked as anonymous.
    In some cases the caller is notated, however, there is no contact information or incorrect contact information.
In some cases there is only a phone number listed, however, only one Contact Center team member has the ability to contact the caller in regards to the issue at hand.

The Way Forward:
The Call Center Team (@clantosswett and @Kimberley2019) will continue to work with the WHVAH/VEO Tier 1 Contact Center leadership team to advise on the information and details that are needed in order to successfully delegate the ticket issues to the appropriate teams to assist.
