### ISSUE TITLE
Adding Selene Mak to DSVA Slack

### ISSUE THREAD

**Issue by robbie1226** [department-of-veterans-affairs/va.gov-team#50538]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

Requesting to add Selene.Mak@va.gov as a full member to DSVA Slack. She is supporting the Digital Health Platform (DHP) team.

Please add to the channels
#digital-health-platform-public

**Comment by eunicegar** [comment]
done
