### ISSUE TITLE
Create Labs and Tests brief

### ISSUE THREAD

**Issue by rbsingleton** [department-of-veterans-affairs/va.gov-team#50546]
**What do we need to do?**
Create a Labs and Tests brief that describes: required data fields, Use cases, UX considerations, Questions to answer, and any additional notes that might be helpful @rbsingleton and ByLight designer

**Process**
- [x] Review data fields mapped in the [Medical Records Domains, Fields, Capabilities](https://docs.google.com/spreadsheets/d/13KE1WhN9c_uG_m-RDEeL3xT0Q50txcBJ_IMt8BxU5II/edit#gid=1602824280) sheet, identify and include relevant data fields as well as any confusion/ uncertainty related to data fields
- [x] Write use cases or user stories based on what we know so far
- [x] Write UX considerations, other strategic considerations, questions to answer, and any additional notes

**Next steps**
- [x] Review brief with @jonathanjnelson and other stakeholders for feedback, insights, to address any gaps in understanding 
- [ ] Translate into low-fi designs @jonathanjnelson 

**Deliverable**
- [x] [Labs and Tests brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/medical-records/data-domains/Labs-and-tests/labs-and-tests-brief.md)

**Comment by MarciMcGuire** [comment]
[Labs and Tests brief on GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/medical-records/data-domains/labs-and-tests/labs-and-tests-brief.md)
