### ISSUE TITLE
Change Frontend Github team for approvals

### ISSUE THREAD

**Issue by jhonnyoddball** [department-of-veterans-affairs/va.gov-team#50540]
## Frontend approvers

Currently the `platform-release-tools` Github team was in charge of approving all frontend related PRs, now, with the reorg, it needs to fall in the frontend CoP.

We need to replace all instances of `platform-release-tools` for the new Github team `va-platform-cop-frontend`

## Tasks
- [ ] Updated Github team in all FE repos

**Comment by it-harrison** [comment]
@jhonnyoddball here's an update. Basically just getting some more approvals now:

repos updated:
* [devops](https://github.com/department-of-veterans-affairs/devops/pull/12346)
* [va.gov-team](https://github.com/department-of-veterans-affairs/va.gov-team/pull/50571)
* [va.gov-team-sensitive](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/671)

repos with PRs needing approval:
* [vets-website](https://github.com/department-of-veterans-affairs/vets-website/pull/22896/files)
* [veteran-facing-services-tools](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/899)
* [vagov-content](https://github.com/department-of-veterans-affairs/vagov-content/pull/860)
* [content-build](https://github.com/department-of-veterans-affairs/content-build/pull/1394)

**Comment by it-harrison** [comment]
hi @powellkerry can you approve the PRs in the "needing approval" section above? Thanks!

**Comment by it-harrison** [comment]
all repos updated, closing.
