### ISSUE TITLE
Add `mhv_verified` as an approved auth event type

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#50557]
The frontend authentication logic looks for specific authentication values, if a value appears that it doesnt know about it throws an error. Currently we have an auth type called `mhv_verified` that is new to our logic on the backend and needs to be added to the frontend. Errors can be seen [here](http://sentry.vfs.va.gov/organizations/vsp/discover/results/?field=title&field=release&field=environment&field=user.display&field=timestamp&name=Unrecognized+auth+event+type&project=4&query=issue.id%3A532&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1) for reference.

To-do:
- add `mhv_verified` to approved auth event types
- Test to ensure errors no longer are present on the frontend
   - This is only being used by the OCC mobile team in prod, but a call to this auth type should work with any app

**Comment by alyssagallion** [comment]
Waiting on our team to review.

**Comment by alyssagallion** [comment]
Ready for review after unit tests pass.
