### ISSUE TITLE
Argo Read/Write Access - Joe Niquette, Trevor Bosaw, John Bramley, Alex Garcia, Afia Caruso

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#50565]
### COR Name

Ray Wang

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Joseph Niquette

### Your Email

joe.niquette@oddball.io

### Team, Role, and Company of the target individual

Identity, Team Lead, Oddball

### Product Manager (PM) name and email

Alyssa Gallion alyssa.gallion@oddball.io

### Product Owner (PO) name and email

John Rahaghi john.rahaghiva@gmail.com

### Desired AWS Access

I am asking for read/write argo access for staging and below for my entire time. We work on vets-api and vets-website Identity features on a daily basis. We need to have direct access to terminal into running pods on dev and staging on a continuous basis. Our team already has similar approved access to ssm into running instances on AWS, this is the same level of access we are requesting in this ticket.

I will open a separate request for prod, as its not yet needed and justification may require more work.

### Access Expiration

ongoing

### Additional Notes

We will need ongoing access because we are creating new features, debugging, and supporting all authentication on VA.gov. We are part of the Platform contract.

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by holdenhinkle** [comment]
Joseph Niquette is the Team Lead on the Identity team, which is not listed on the Platform Roster.

**Comment by raywangoctova** [comment]
You are approved for the contract award's annual period of performance while you are in this role. If PoP ends, your role changes, or per VA direction, the approval is rescinded immediately.

**Comment by holdenhinkle** [comment]
Thank you @raywangoctova

Joe would also like his teammates to have access too. They are Trevor Bosaw, John Bramley, Alex Garcia, Afia Caruso. Is it okay to give them access too? Thank you.

**Comment by holdenhinkle** [comment]
Confirming, I just added Joe to the following teams:

- https://github.com/orgs/department-of-veterans-affairs/teams/dsva-vagov-vets-api-staging-rw 
- https://github.com/orgs/department-of-veterans-affairs/teams/dsva-vagov-vets-api-dev-rw

Awaiting your response regarding Trevor Bosaw, John Bramley, Alex Garcia, and Afia Caruso. Thank you!

**Comment by BillChapmanUSDS** [comment]
Is this access operationally important in the next week?  As Ray has already been involved in this request and I am just taking over for Thomas and new to our process I'd prefer to wait until Ray returns from holiday but I'm sure I can make the call if necessary.  The access sounds reasonable to me but it looks like I don't have EQUIP Dates for Trevor, John and Alex. Is this the first AWS access they are being granted?

**Comment by joeniquette** [comment]
This isn't for AWS access but yes it can wait until after the holidays for
approval.

**Comment by holdenhinkle** [comment]
Bumping this...

**Comment by BillChapmanUSDS** [comment]
@raywangoctova  I have a couple of questions here. 

I see EQUIP dates for John Bramley and Afia Caruso but not for Alex Garcia and Trevor Bosaw so if this is a request and I don't know if this request falls under the pruview of AWS access.  Is Argo access under your purview or should I OK John and Afia and track down dates for Alex and Trevor? Given this is an AWS access request I assumed we have it running there but I don't know the specifics of our Argo installation and where it lives.

**Comment by raywangoctova** [comment]
@BillChapmanUSDS 

Amber Malcolm should provide the eQUIP date for the requestor to be included in the request. You can do it together.

@andreahewitt-odd @little-oddball @jwoodman5 

Can you guys make sure this information is included before the request is submitted? This has been a recurring issue before Bill, and it always resulted in additional follow-ups and delays.

**Comment by BillChapmanUSDS** [comment]
I'm ok with this access and we can go ahead and grant the request for John and Afia,  

I'm also OK with Alex and Trevor,  I know they have EQUIP dates, they already have AWS access that existed before the current process and I will ping this request as soon as I have updated the document on these two.

**Comment by BillChapmanUSDS** [comment]
Equip dates verified, sorry for the delay.

**Comment by ph-One** [comment]
@joeniquette if all you want is to be able to login to Argo and hop into a Pod's terminal or to r/w within the vets-api project, all you need is to be a part of the appropriate GitHub Team, https://github.com/orgs/department-of-veterans-affairs/teams?query=vets-api

**Comment by rmtolmach** [comment]
@ph-One There were some guardrails set up by `vets-api` folks in order to control access. Described here: https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-Access It currently involves opening one of these AWS access requests, but we have a ticket open to create a _new_ access request form (to avoid some of the confusion). That ticket's here:
* https://github.com/department-of-veterans-affairs/va.gov-team/issues/52644

**Comment by holdenhinkle** [comment]
I added Trevor, John, Alex, and Afia to:
- https://github.com/orgs/department-of-veterans-affairs/teams/dsva-vagov-vets-api-staging-rw
- https://github.com/orgs/department-of-veterans-affairs/teams/dsva-vagov-vets-api-dev-rw

Thanks everyone!
