### ISSUE TITLE
add vamobile and vaweb to client_id param of SiS

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#50585]
Add the params, accept both, wait for mobile to deploy changes required then remove the old values.

Frontend and backer work required

**Comment by bramleyjl** [comment]
confirmed `vaweb` & `vamobile` client_id parameters work properly in staging

**Comment by bramleyjl** [comment]
confirmed `vaweb` & `vamobile` client_id parameters work properly in staging
