### ISSUE TITLE
Template for Introduction and Confirmation Form Pages

### ISSUE THREAD

**Issue by jeana-adhoc** [department-of-veterans-affairs/va.gov-team#50587]
### **Description**
To expedite form creation we need to simplify the introduction and confirmation page creation process. We'd like to propose a template for each that is the same across all forms and at least provides some helpful guidance that future teams could build upon.

### **Definition of Done**
- [x] Create Template for [Introduction Form Page](https://docs.google.com/document/d/1cGlJcdnilLpzID-oe2R7u-EvGhvAoITn7L9iPFinKl8/edit?usp=sharing)
- [x] Create Template for [Confirmation Form Page](https://docs.google.com/document/d/19sBDi7Ifo8fOX5iUCiS_2aeecREcvtDkzsjXrn5i7Lw/edit?usp=sharing)
- [x] Review with Nick
- [x] Mockup in Sketch
- [x] Review with Content

### **Supporting Documentation**
[Sketch File](https://www.sketch.com/s/8d8d64a1-3c12-49db-b449-fa2800a3f953)

**Comment by jeana-adhoc** [comment]
After discussing this with Nick, we thought this might be very similar to what the forms generator creates on default. But after looking at the mock form, it appears that it actually adds more placeholders that we'd need to delete.  I'm moving forward with talking with the content folks to get some guidance/thoughts on this whole idea.

**Comment by jeana-adhoc** [comment]
@bethpottsVADEPO & @DanielleThierryUSDSVA 

Here's the sketch files for the Simple Introduction and Confirmation page that we'd like to propose as part of our simplified form process for rapid development.  Let me know if you have any content concerns.

https://www.sketch.com/s/8d8d64a1-3c12-49db-b449-fa2800a3f953

**Comment by humancompanion-usds** [comment]
@bethpottsVADEPO & @DanielleThierryUSDSVA - Reach out if you have questions about this project. It should get more "air time" within OCTO in the new year. If there are certain blocks of content that you feel must be there on these two pages it would be good for us to identify those sooner rather than later. 

@jeana-adhoc - I do think we could conditionally include a section for related forms (i.e. include if there are any and otherwise skip it) in the template as we do have that info via the audit and the forms DB.

**Comment by jeana-adhoc** [comment]
Thanks, @humancompanion-usds ! I think we're probably good here. Each form that's already in find-a-form, already has an about page where that information exists, (ie: [10-10d](https://www.va.gov/find-forms/about-form-10-10d/)) 

@bethpottsVADEPO & @DanielleThierryUSDSVA - Do we also list related forms on the form introduction page?

**Comment by DanielleThierryUSDSVA** [comment]
Hi @jeana-adhoc! I added notes to the sketch file. Just let me know if you have questions or want to jump on a call. We don't typically list related forms on the form intro page. But let me know if you want to discuss more. Thanks!

**Comment by jeana-adhoc** [comment]
@DanielleThierryUSDSVA - Thank you! Your edits were super helpful. I've made them and made an additional edit. It appears that the link to "Start your application without signing in" is typically within the greybox for the "authenticated" sign-in. So I moved that up.

Also - back in the Sketch file, if you scroll to the left, I have an example of using the template on the 10-10d form, and was hoping you could check that as well to make sure I understood the actual template variables as well.

Thank you!

**Comment by jeana-adhoc** [comment]
This was presented with the [design intent ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/53071)in the [wireframe ticket](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/issues/26).

We are also working on [annotating these layouts](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/issues/39) for the design system.

This ticket can be closed.
