### ISSUE TITLE
Staging:  Clinic Patient Friendly Names Not Displaying Confirmation Page & Upcoming Appts Queue

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#50597]
1.  Make an appt for a patient in any clinic that has both Clinic Name and Patient Friendly Name (see wiki page for list of these clinics)
2.  For example cecil morgan, 12/14 @0800 Amputation Appointment.  
PATIENT FRIENDLY NAME = FRIENDLY NAME FTC AMPUTATION – displays on Choose Clinic page
VISTA NAME = FTC AMPUTATION – displays on booking confirmation page and upcoming appointments page.   These pages should display the Friendly Name.    _***This is not the best example since the Friendly Name is a close match to Clinic Name.  Usually that is not the case.  ****_

![image.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/eadec16a-604d-44b2-a6d6-ab4ed2a4d297)
![image.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/821270ca-a66b-48de-8e67-945817a6486e)
![image.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/7e4db132-7909-40e3-9c0a-dccae03d879c)
![image.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/e51c2948-8ad8-4adf-8103-bb6658db2ccb)

**MFS call that shows friendly name being returned to Vets-AP.**  
https://veteran.apps-staging.va.gov/facilities/v2/facilities/983/clinics/1081

{
  "data" : {
    "vistaSite" : 983,
    "clinicId" : "1081",
    "serviceName" : "FTC AMPUTATION",
    "friendlyName" : "Friendly Name FTC Amputation",
    "stationId" : "983GC",
    "institutionId" : "983GC",
    "stationName" : "CHYSHR-Fort Collins VA Clinic",
    "primaryStopCode" : 211,
    "primaryStopCodeName" : "PM&RS AMP CLINIC",
    "patientDirectScheduling" : true,
    "patientDisplay" : true,
    "institutionName" : "CHYSHR-FORT COLLINS",
    "institutionIEN" : "421",
    "institutionSID" : "1400039292",
    "timezone" : {
      "timeZoneId" : "America/Denver"
    },
    "futureBookingMaximumDays" : 393
  }
}

**Endpoint in VAOS with Response Data.**  
https://staging-api.va.gov/vaos/v2/appointments?_include=facilities,clinics&start=2022-11-10&end=2024-01-09&statuses[]=booked&statuses[]=arrived&statuses[]=fulfilled&statuses[]=cancelled

{
  "id": "147685",
  "type": "appointments",
  "attributes": {
    "id": "147685",
    "identifier": [
      {
        "system": http://med.va.gov/fhir/urn/vaos/vista/983/appointment/id,
        "value": "1081;20221214.080000"
      }
    ],
    "kind": "clinic",
    "status": "booked",
    "service_type": "amputation",
    "reason_code": {
      "text": "test"
   },
    "patient_icn": "1012845943V900681",
    "location_id": "983GC",
    "clinic": "1081",
    "start": "2022-12-14T15:00:00Z",
    "end": "2022-12-14T15:30:00Z",
    "minutes_duration": 30,
    "slot": {
      "id": "3230323231323134313530303A323032323132313431353330",
      "start": "2022-12-14T15:00:00Z",
      "end": "2022-12-14T15:30:00Z"
    },
    "comment": "test",
    "cancellable": true,
    "extension": {
      "cc_location": {
        "address": {}
      },
      "vista_status": [
        "FUTURE"
      ]
    },
    "service_name": "FTC AMPUTATION",
    "location": {
      "id": "983GC",
      "type": "appointments",
      "attributes": {
        "id": "983GC",
        "vista_site": "983",
        "vast_parent": "983",
        "type": "va_facilities",
        "name": "Fort Collins VA Clinic",
        "classification": "Multi-Specialty CBOC",
        "timezone": {
          "time_zone_id": "America/Denver"
        },
        "lat": 40.553875,
        "long": -105.08795,
        "website": https://www.cheyenne.va.gov/locations/Fort_Collins_VA_CBOC.asp,
        "phone": {
          "main": "970-224-1550"
        },
        "physical_address": {
          "line": [
            "2509 Research Boulevard"
          ],
          "city": "Fort Collins",
          "state": "CO",
          "postal_code": "80526-8108"
        },
        "health_service": [
          "Audiology",
          "EmergencyCare",
          "MentalHealthCare",
          "PrimaryCare",
          "SpecialtyCare"
        ]
      }
    }
  }
}

**Comment by ajmagdub** [comment]
@ldelacosta @simiadebowale merged the Vets API portion of the clinics friendly name should be in staging shortly and will be in production by this afternoon.

**Comment by simiadebowale** [comment]
This is on hold till after Go-live. cc: @ldelacosta

**Comment by marcynadeau** [comment]
Discussed on Scrum of Scrums on 12/13.  Issues has been fixed.  Holding off deploying this to production until later.   F/E will enhance monitoring to determine how frequent this issue presents in production,.  If a spike in this issue is seen then will work on getting this to prod ASAP

**Comment by ldelacosta** [comment]
@marcynadeau - This ticket is ready to be validated in staging. Thanks! 

cc: @simiadebowale

**Comment by beth-wodzinski** [comment]
@ldelacosta @simiadebowale @marcynadeau This passes testing. I verified with different patients and 3 different clinics. 
FTC Amputation (Friendly Name FTC Amputation), CHY C&P KILPATRICK (Green Team Clin1) and WHT AUDIO VAR2 (Wheatland Audiology) and the friendly name showed everywhere.
