### ISSUE TITLE
COVID-19 Workflow - Not displaying the correct time on the Confirmation page 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#50594]
## Summary
When a user booked their COVID-19 appointment in VAOS, the app displays the incorrect time on the confirmation details page. When the user views the COVID-19 appointment details page, the time displays correctly. 

## Screenshots 
<img width="1063" alt="Screen Shot 2022-12-09 at 6 04 11 PM" src="https://user-images.githubusercontent.com/90797205/206809559-c818f8fd-0a9f-4e5e-8655-6c2758e8b6dc.png">
<img width="886" alt="Screen Shot 2022-12-09 at 6 04 20 PM" src="https://user-images.githubusercontent.com/90797205/206809560-f84bfd98-15c8-4494-9689-f0953b0c911a.png">
<img width="686" alt="Screen Shot 2022-12-09 at 6 04 27 PM" src="https://user-images.githubusercontent.com/90797205/206809562-f17852a4-33d3-4d72-9407-af90bb0277c4.png">

## Steps to Reproduce
Test user: Claudia 

1. VATS Cheyenne configured COVID Direct Scheduling = Yes
2. Tester on ET logs into VAOS. Selects COVID. Select Cheyenne (MT).
3. Select to schedule appointment @0800 from the appointment grid.  Continue through booking screen
4. Confirmation page displays 10:00 AM MT instead of 08:00 AM MT 

### Actual Result
Appointment confirmation screen shows appointment booked at 1000 MT

### Desired Result
Appointment confirmation screen shows appointment booked at 0800 MT – which is the time selected in the appointment grid. 

## Definition of Done
- [ ] Desired result is achieved and/or document decisions made
- [ ] Relevant documentation is updated

---

**Comment by ldelacosta** [comment]
@marcynadeau - Please validate on your end and let me know if you have any questions. Thanks.

**Comment by beth-wodzinski** [comment]
@ldelacosta this passes testing.
