### ISSUE TITLE
[Bug] Redesigned Homepage (R3) - Other search tools - Facility-Locator link text anomaly

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#50598]
## What happened?
In Staging Redesigned Homepage, Search box, Other search tools, Facility-Locator link text did not match design mockup.

### Screenshot
![image](https://user-images.githubusercontent.com/587583/206932692-af8fc699-5386-4451-ab8a-44734d1e8c45.png)

## Steps to Reproduce
- URL: https://staging.va.gov/new-home-page/

1. In **Search** section, **Other search tools** subsection, observe that **Find a VA facility** link-text does not match design mockup.

## Desired content
- [ ] Link text should be **Find a VA location**

### Screenshot
[Design mockup](https://www.sketch.com/s/3aa40506-4be2-46cc-876b-93f1a9f3a857/a/3Od7YAd): 
![image](https://user-images.githubusercontent.com/587583/206933028-02592230-6509-4200-a2d2-13abb331f395.png)

## Acceptance Criteria
- [ ] _Describe the desired working behavior_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by mmiddaugh** [comment]
This text has been updated in Drupal after confirming content with Content IA team.

**Comment by jilladams** [comment]
![Screen Shot 2022-12-21 at 2 17 59 PM](https://user-images.githubusercontent.com/85581471/209013119-9e14b593-bbc7-47a0-85e4-d84660d89bdc.png)
https://staging.va.gov/new-home-page/

Resolved, closing.
