### ISSUE TITLE
vets-api autoscaling tuning

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#50604]
## Description 

The current vets-api EKS autoscaling (HPA) is based on what was defined for BRD (threads + worker count). We should keep an eye on metrics to see if we are under or over utilizing pods. E.g. The min/max thresholds. [See Datadog]( https://vagov.ddog-gov.com/dash/integration/24/kubernetes-pods-overview?tpl_var_cluste[…]ets-api&from_ts=1670250756432&to_ts=1670855556432&live=true)

- [Staging PR](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/1293)
- [Sandbox PR](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/1294)
- [Prod PR](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/1295)

EKS Dashboards:
- [Puma Backlog Metrics](https://vagov.ddog-gov.com/dashboard/yk6-mrp-k96/eks-puma-backlog-metrics?from_ts=1671647612890&to_ts=1674239612890&live=true)
- [EKS CPU and Memory](https://vagov.ddog-gov.com/dashboard/ugi-r9m-ezp/eks-cpu-and-memory?from_ts=1674237311794&to_ts=1674240911794&live=true)

**Comment by laineymajor** [comment]
Currently have ported over what we see in BRD... but needs fine tuning for EKS.

**Comment by LindseySaari** [comment]
These are the current BRD CPU usage percentage rates for Prod, Staging and Sandbox. We will want to compare to EKS as we scale up the weighted deployments and compare to defined autoscaling defaults.

![Screen Shot 2023-01-03 at 10.38.36 AM.png](https://images.zenhubusercontent.com/5d4836dda95c51615db9bdc9/395c473e-54f1-4876-8c6c-71520a0501b4)

**Comment by rmtolmach** [comment]
Could [Goldilocks](https://github.com/FairwindsOps/goldilocks) be used for determining the limits? Here is a really old ticket where I was investigating deployment requests and limits in EKS for vets-api: https://github.com/department-of-veterans-affairs/va.gov-team/issues/39691

**Comment by laineymajor** [comment]
With 100% traffic going to dev, should be pretty accurate. Need to start working on load testing.

**Comment by laineymajor** [comment]
On hold until we turn up the dial on staging + higher environments.

**Comment by laineymajor** [comment]
Rachal going to make a PR for staging

**Comment by laineymajor** [comment]
Rachal created the PRs for SB and production (as draft currently)

**Comment by LindseySaari** [comment]
PRs still in draft mode and ready to go when we are.

**Comment by laineymajor** [comment]
Now that we have increased number of pods in staging, the pods are not _all_ cycling through. @RachalCassity to look at the config and pull in Kyle if needed. Percentages seem to be the way to go.

**Comment by LindseySaari** [comment]
@RachalCassity Do you want to update this ticket with the changes made + discussed in [this thread please](https://oddball.slack.com/archives/C045LCF8WU8/p1677193291217059)?

**Comment by LindseySaari** [comment]
@RachalCassity Do you want to update this ticket with the changes made + discussed in [this thread please](https://oddball.slack.com/archives/C045LCF8WU8/p1677193291217059)?

**Comment by LindseySaari** [comment]
Current BRD request rates: https://vagov.ddog-gov.com/dashboard/b8k-uy2-fkm?from_ts=1677259846726&to_ts=1677263446726&live=true
