### ISSUE TITLE
Remove use of ExpandingGroup component causing VAOS to fail in staging and production.

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#50602]
## Description

It's been determined that the ExpandingGroup component we are leveraging from the platform team is the root cause of the react errors we are seeing. I have commented out the component for now to temporarily fix staging & prod errors. We will likely need to wait for their component to get fixed before displaying the 'dropdown' style but the plan is to keep on displaying the exact info we have there but without the dropdown.

---

## Acceptance Criteria
The ''Why isn’t my facility listed?' section is displayed.
![Screen Shot 2022-12-11 at 10.04.49 PM.png](https://images.zenhubusercontent.com/62279c01c38e1718c9102bee/ad5b733f-dc3f-4b26-9628-86ed6d9a0af7)### Design Assets

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by ldelacosta** [comment]
Closing out the ticket. No new issues reported.
