### ISSUE TITLE
[Platform Tech Teams] Create onboarding checklist for new team members

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#50615]
## Description 
New platform team members need to know where to find essential tools, documentation, and communication channels. However, this information is not captured succinctly, leading to a confusing or disconnected experience. 

## Background/context 
- See the following examples:
  -  [Ops onboarding checklist](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=&template=ops_onboarding_checklist.md&title=VSP+Operations+Onboarding)  
  - #48755
  - #49772

## Acceptance criteria 
- [x] An onboarding template can be used to create a ticket that can be used for tracking onboarding steps for Platform developers/engineers

**Comment by jhouse-solvd** [comment]
Working on this now.

**Comment by jhouse-solvd** [comment]
And we could remove this old one called "Ops Onboarding checklist"

**Comment by rmtolmach** [comment]
Add this item to the checklist. Only needed for DevOps Engineers. 
  - [ ] [Venafi](https://vfs.atlassian.net/wiki/spaces/OT/pages/1719009302/Venafi+Gain+access+to+manage+internal+TLS+certificates) (Once PIV card has been obtained)

**Comment by oseasmoran73** [comment]
PR Created to remove Ops onboarding template once we get one for platform

**Comment by hgbarreto** [comment]
#55282
