### ISSUE TITLE
[Bug] Redesigned Homepage (R3) - Email sign-up - Content/styling anomalies

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#50618]
## What happened?
In Staging **Redesigned Homepage**, **Email sign-up** section, content/styling did not match design mockup.

### Screenshot
![image](https://user-images.githubusercontent.com/587583/207125411-d99f0ba0-d52a-4d1a-8b00-8bbead2d5fe3.png)

## Steps to Reproduce
- URL: https://staging.va.gov/new-home-page/
- Scroll down to **Email-signup** section.
- Observe that content/styling does not match design mockup [see screenshot below].

## Desired content/styling
- [ ] Email-signup section content/styling should match mockup.

### Screenshot
[Design mockup](https://www.sketch.com/s/3aa40506-4be2-46cc-876b-93f1a9f3a857/a/3Od7YAd): 
![image](https://user-images.githubusercontent.com/587583/207126059-e9a6f543-8b73-43ac-9c6b-b4b813be9672.png)

## Acceptance Criteria
[see **Desired content/styling** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by jilladams** [comment]
![Screen Shot 2022-12-21 at 2 22 07 PM](https://user-images.githubusercontent.com/85581471/209013698-2d1ee62a-12db-474f-bd82-921b8e5b6ffb.png)
https://www.va.gov/new-home-page/
