### ISSUE TITLE
[SPIKE] Evaluate VAOS/Appt redesign to know if we can to percentage rollout 

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#50617]
## Tasks

- [ ] Evaluate wireframes for VAOS/appt redesign to determine if we can use the percentage rollout too. The reason we want to know this is to understand how we should message our planned rollout and/or testing during collab cycle. 

## AC

- [ ] Determine if we can do percentage rollout for the VAOS/appt redesign. Update the UX team.

**Comment by brianseek** [comment]
We determined in our wireframe meeting that we will be adding this work to a feature toggle that will give the ability to do a percentage rollout. Closing this spike
