### ISSUE TITLE
Analytics Implementation or QA Support for [Benefits Team 1 - Supplemental Claim Form]

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#50625]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

</div>
</details>

### Required
- **Is this request for **Google Analytics implementation** or **QA**?**

     - [x] Google Analytics implementation
     - [ ] QA

- **Who is this request for?**

    - Benefits Team 1
    
    
- **Provide the link(s) for Google Analytics implementation or QA**
  
    - [Supplemental Claims Links](https://docs.google.com/spreadsheets/d/10bHV7JLABsJIHVnYoRqix6E4fK41pFvf_ie5FMAdFqw/edit#gid=0)
    
- **When is the launch date?**
    - Estimated: Late January 2023

- **What interactions need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked_
    
    - [Supplemental Claims Analytics](https://docs.google.com/document/d/1aPhHuGzlqRIf2WMc7FU2bBmPVWFfVsDnW0pTFMCdWIc/edit?usp=sharing)
    
    - [Insert other interactions - please review the [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) and [GA Data Dictionary](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Google-Analytics-Data-Dictionary.1810464912.html)  to make sure these interactions aren't already tracked]

### Optional
- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - [Insert test user]

- **Any additional comments**

    - [Insert comments]

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by michelle-dooley** [comment]
@saderagsdale - can you please provide details for this request as requested above.

**Comment by michelle-dooley** [comment]
@saderagsdale - yes I can open them.  I will review with the team and get back to you after holiday break.

**Comment by saderagsdale** [comment]
@michelle-dooley Hey Michelle, Happy New Year! When you've had time to review the documentation can you let us know if any of the UI behaviors we want to track need further clarification? A quick call may help to supplement the details in the documents.

**Comment by saderagsdale** [comment]
@michelle-dooley Hey Michelle, any update on this one yet?

**Comment by michelle-dooley** [comment]
@saderagsdale - it doesn't look like you are using the web components for event tracking. For example on the first one "Continue you application" button this is what 
![image](https://user-images.githubusercontent.com/93597659/211925686-a81fa9b2-5a3b-45f9-89e8-44b4361ecabc.png)

However when I look at other similar button click events on other pages I see this....
![image](https://user-images.githubusercontent.com/93597659/211925841-51b9416d-feb1-44db-9cfe-facf0c82b878.png)

I think what you need to add in the code, example of code from platform website... 

Event: ‘cta-button-click’,

![image](https://user-images.githubusercontent.com/93597659/211927235-e80a0213-60a2-4e6f-85af-5f254be32375.png)
https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/design-system-components

**Comment by saderagsdale** [comment]
@michelle-dooley Hey Michelle - thanks for the details. I'll have the team review this. 

@Mottie Hey Robin - Can you look at Michelle's comment above and let me know the level of effort to fix this code issue?

**Comment by Mottie** [comment]
@michelle-dooley We are using web components in most places. The form continue and restart buttons are being rendered by the platform save in progress intro component. It is being provided a `gaStartEventName` of `decision-reviews-va20-0996-start-form` (which should be 0995, so I will fix this immediately), but from looking at the internal code, using the continue button is only triggering a save-in-progress form loaded event and not the button click

<img width="559" alt="browser dev console showing the last GA entry of event 995-supplemental-claim-sip-form-loaded" src="https://user-images.githubusercontent.com/136959/212105544-a86e0de2-1036-4c29-8227-d7d09861343a.png">

Which is the same event I see for our Notice of Disagreement form continuation click:
<img width="566" alt="browser dev console showing the last GA entry of event 10182-board-appeal-sip-form-loaded" src="https://user-images.githubusercontent.com/136959/212106180-b210e9cd-d814-4bb9-be44-ceb247163f11.png">

The only start event I noted was from the new form action link click showing the form start event

<img width="558" alt="browser dev console showing that the last 2 events are event decision-reviews-va20-0995-start-form and event 995-supplemental-claim-sip-form-loaded" src="https://user-images.githubusercontent.com/136959/212107461-fa43b9a5-3ec0-4f47-a492-1fe14fcf9863.png">

So, I believe this might be a more global issue with all forms that will require platform code changes.

**Comment by saderagsdale** [comment]
@michelle-dooley @Mottie Since we think this is a global issue in lower environments, how can we confirm?

**Comment by michelle-dooley** [comment]
@Mottie and @saderagsdale - I'm not sure I understand the global issue?  What specific event is not being recorded as expected?  Can you give me an example I can test other places?

**Comment by saderagsdale** [comment]
@michelle-dooley are you free early next Monday, Tuesday, or Wednesday to meet with us? A quick huddle will be easier.

**Comment by Mottie** [comment]
From looking at the platform code for the save-in-progress:
- "Continue your application" button doesn't appear to trigger any analytics events.
- "Start a new application" button does trigger "login-successful-start-form" and "{tracking-prefix}-sip-form-start-over" events
- "Start your Claim" action link (no save-in-progress) triggers a "decision-reviews-va20-0995-start-form" event for our Supplemental Claim form

So, it seems that the "Continue your application" button not triggering any event is a global (all forms) issue. We can meet to discuss what event it should trigger since the "cta-button-click" doesn't seem to be form specific?

**Comment by michelle-dooley** [comment]
@Mottie - I think I resolved the 'continue your application' issue.  I do not believe it was universal but specific to this form needing additional configuration in GTM.  This is the event action that is firing ...
![image](https://user-images.githubusercontent.com/93597659/212740086-8bb59790-e9be-402d-81ff-6f740380eca3.png)

**Comment by saderagsdale** [comment]
@michelle-dooley Hey Michelle - checking to see if we address all of the issues you highlighted. Anything else you need from us on this one?

**Comment by michelle-dooley** [comment]
@saderagsdale - I added comments to the [google doc](https://docs.google.com/document/d/1aPhHuGzlqRIf2WMc7FU2bBmPVWFfVsDnW0pTFMCdWIc/edit#).  Some of these events are tracking and I included what I see.  Seems like most of the buttons and radio checkboxes are not tracking.  And there are a few pages I cannot get to to test.

**Comment by saderagsdale** [comment]
@Mottie @eileen-coforma let's review thee tomorrow internally. @michelle-dooley can we setup a working session with you if needed?

**Comment by michelle-dooley** [comment]
Yep!!

**Comment by saderagsdale** [comment]
@michelle-dooley cool beans. what's your availability this week/early next?

**Comment by michelle-dooley** [comment]
@saderagsdale - this week is not good but early next week works.

Monday: 1:00-5:00 ET
Tuesday: 2:00-3:30 ET
Wednesday: 11:00-1:00 or 3:30-5:00 ET
Thursday:  11:00-1:00 ET

**Comment by saderagsdale** [comment]
@michelle-dooley @Mottie @eileen-coforma Scheduled time for us next Monday.

**Comment by Mottie** [comment]
Analytics updates available in staging. Please review.

**Comment by michelle-dooley** [comment]
@Mottie - just tested, I think we are good, I updated the doc with the new events I see.  The only 2 I could not figure out how to get to again were these....
![image](https://user-images.githubusercontent.com/93597659/216674853-436be717-8557-4f16-add9-75848a9a0b28.png)

**Comment by Mottie** [comment]
To test the verify your identity, log into [user 233](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-HLR.md) in [Supplemetnal Claims on dev.va.gov](https://dev.va.gov/decision-reviews/supplemental-claim/file-supplemental-claim-form-20-0995/start) (not staging)

The missing info alert can be seen by creating a fake account via ID.me, but do not verify the account. Then log in to staging with that LOA1 (unverified) account and you should see that alert on the introduction page.

**Comment by saderagsdale** [comment]
@michelle-dooley Hey Michelle! Let me know if the login info Robin shared gave you the ability to check the last two. Otherwise, is there anything we should do to confirm we can see the funnels, or do we just wait until submissions start rolling in?

**Comment by michelle-dooley** [comment]
@saderagsdale and @Mottie I was able to complete those last 2 tests and they are working as expected.  All event details have been added to the [doc](https://docs.google.com/document/d/1aPhHuGzlqRIf2WMc7FU2bBmPVWFfVsDnW0pTFMCdWIc/edit#).  So I believe that should complete this ticket.

**Comment by michelle-dooley** [comment]
Closing this ticket as complete.  Please reach out if you have any further questions.
