### ISSUE TITLE
[Bug] Redesigned Homepage (R3) - Email sign-up - No invalid-input error-display

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#50624]
## What happened?
In Staging **Redesigned Homepage**, **Email sign-up** section, invalid-email input did not trigger any display/indication of User-error.

## Steps to Reproduce
- URL: https://staging.va.gov/new-home-page/
- Scroll down to **Email-signup** section, input a string _without_ **@** character, then click **Sign up** button.
- Observe that no indication of invalid-input is displayed.  [see Video below]

### Video

https://user-images.githubusercontent.com/587583/207133641-c4cc985a-c69a-411f-8ded-ac1bf2a46195.mp4

## Desired behavior
- [ ] Invalid input should trigger display of some form of error indicator/message.

## Acceptance Criteria
[see **Desired behavior** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by jilladams** [comment]
Fixed by previous PR, so this no longer reproduces in Staging.

**Comment by mmiddaugh** [comment]
An update to the style and behavior of the email component was merged yesterday (12/13). The observed behavior is no longer present. Appropriate error messaging is now in place. 
![image](https://user-images.githubusercontent.com/55411834/207425346-a63925f8-7d8e-4cc6-852e-8814988f01c8.png)
![image](https://user-images.githubusercontent.com/55411834/207425277-17c31482-8996-4feb-84e5-2d2509b1490e.png)

**Comment by tlei123** [comment]
Confirming here that I've also validated this fix in Staging.
