### ISSUE TITLE
[PM] Payment Info V2: Update Post Launch Success Metrics (2 - months)

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#50627]
## Background
The Payments V2 project was launched to 100% of users on 12/12/22. On or after 2/12/23 we need to update [this success metrics document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/README.md#measuring-success) with the proper metrics.

## Tasks
- [ ] Update [this document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/README.md#measuring-success) with post 2 month success metrics

**Comment by ajakabcin** [comment]
duplicate - closing
