### ISSUE TITLE
Analytics Implementation for [Auth Exp, My VA - My VA Audit]

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#50621]
# Google Analytics Implementation 

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

</div>
</details>

### Required
- **Is this request for **Google Analytics implementation** or **QA**?**

     - [X] Google Analytics implementation
     - [ ] QA

- **Who is this request for?**

    - [Authenticated Experience My VA]
    
    
- **Provide the link(s) for Google Analytics implementation or QA**
  
    - va.gov/my-va
    
- **When is the launch date?**
    - Q1 2023

- **What interactions need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked_
    
    - [Interactions to be tracked are documented here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/Product/audit-analytics-request.md)
    - Many links were renamed so we want to confirm how that impacts our metrics. I.e. will we have new events for these links?
    - Some new links were added but it seems they used design systems components and will automatically be tracked but we want to confirm that.
    
    - [Insert other interactions - please review the [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) and [GA Data Dictionary](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Google-Analytics-Data-Dictionary.1810464912.html)  to make sure these interactions aren't already tracked]

### Optional
- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - Test users are included in the documentation shared above.

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by ajakabcin** [comment]
hey @michelle-dooley I finished my review of that inventory doc and made some notes and updates. If you could give it a look and let me know your thoughts I would appreciate it. Thank you!

**Comment by michelle-dooley** [comment]
@ajakabcin and @ericasauv09 - what I see from my audit of those links. 

https://docs.google.com/document/d/1G6OjL1tnJ-goCiu-z3hsAq8KGRldcHCYuI1f0l5tx3s/edit

**Comment by michelle-dooley** [comment]
@ajakabcin - you should have everything you need so I am going to close this ticket.  Please reach out if you have any questions.

**Comment by ajakabcin** [comment]
Hey @michelle-dooley I'm going to reopen this so we can have @allisonlu's fixes double checked by you all. We'll ping you when we're done on them. For reference, these are the two tickets she's working on:

- #53744 
- #53765

**Comment by ajakabcin** [comment]
All set here - thanks again @michelle-dooley !
