### ISSUE TITLE
DR | Fix verify modal design

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#50637]
## Value Statement
**_As a_**  Benefits team 1 member
**_I want to_** design of the verify your identity modal to match the new design
**_So that_** we have consistent messages across all decision review forms 

---
## Acceptance Criteria
- [x] User sees verify your identity alert (LOA1-only) preventing them from starting Higher-Level Review form
- [x] User sees verify your identity alert (LOA1-only) preventing them from starting Notice of Disagreement form
- [x] User sees verify your identity alert (LOA1-only) preventing them from starting Supplemental Claim form
- [x] Update unit tests
- [ ] Update E2E tests
- [ ] Accessibility testing complete
- [ ] Reviewed and approved by product and/or design

## Designs and Build Notes
- [DESIGN](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/p/5E24F540-2558-488C-BD6D-823F4A2F5607/canvas)
<img width="776" alt="You’ll need to verify your identity to access more VA.gov tools and features with green alert and lock icon. We need to make sure you’re you — and not someone pretending to be you — before we can give you access to your personal and health-related information. This helps to keep your information safe, and to prevent fraud and identity theft. This one-time process takes about 5-10 minutes. Action link to verify your identity at the bottom" src="https://user-images.githubusercontent.com/136959/207163849-87968276-e74c-4b8f-8595-9e744fc01038.png">

<details><summary>Current verify alert</summary>

<img width="946" alt="Warning alert at the top of the page. Verify your identity to start your request. Before we give you access to your personal information, we need to make sure that you're you - and not someone pretending to be you. This helps us keep your information safe. Verify your identity to start your request non-action link at the bottom" src="https://user-images.githubusercontent.com/136959/207164441-ddc7885a-b231-4359-8a0c-6de55005d704.png"></details>

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design
---

**Comment by Mottie** [comment]
Changes merged in, [not yet available in staging for testing](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/).

**Comment by HeatherWidmont** [comment]
@saderagsdale @eileen-coforma this is ready to validate, thank you!

**Comment by eileen-coforma** [comment]
👍 looks good
