### ISSUE TITLE
[Bug] Redesigned Homepage (R3) - Benefit hubs - Sort-order anomaly

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#50638]
## What happened?
In Staging **Redesigned Homepage**, **Explore VA benefits and health care** section, benefit-hubs sort-order and content did not match design mockup.

## Steps to Reproduce
- URL: https://staging.va.gov/new-home-page/
- Scroll down to **Explore VA benefits and health care** section.
- Observe that benefit-hubs sort-order does not match design mockup.

**NOTE**: Most hubs' blurb-contents also don't match mockup &mdash; fix as needed.  Since they're more detailed in Staging, I'm assuming it's the mockup that's out of date.

### Screenshot
![image](https://user-images.githubusercontent.com/587583/207174769-9acfe453-cfcd-42ff-9637-5c00cdc99074.png)

## Desired content
- [ ] Benefit-hubs sort-order should match mockup.

### Screenshot
Design mockup: 
![image](https://user-images.githubusercontent.com/587583/207176257-9134c300-1966-4503-8a03-527a527d3661.png)

## Acceptance Criteria
- [ ] _Describe the desired working behavior_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by mmiddaugh** [comment]
Thanks for this observation, @tlei123 
The sort-order on the new homepage is intentionally different than the existing homepage (which is what was used in the mock-up). Apologies for not pointing this out.
