### ISSUE TITLE
Publish written position on the boundaries and responsibilities of VSP Support

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/va.gov-team#5063]
- VSP is *not* responsible for xyz behavior
- VSP will not be the default owner of this code if VFS team goes away
- VSP teammates don't have to worry about....
- We will know "support" is successful when...
- We will know we have implemented the right tools when...

---

Current state and desired future state.

Like: These are the tools that are the best bet for these code quality problems, the evidence of these problems is abC (ideally tied to KPIs). We see these kinds of repeat problems in these kinds of teams, and these automated tools re the best bet for addressing those kinds of problems.

---

## Objective
O3: Stability and resiliency of the Platform's systems and teams continue to improve.

**Comment by rroueche** [comment]
In progress: https://docs.google.com/document/d/1YFAPR6lGm9NOU2gIWJX3U1wguHey9vjaght_o1XjZYs/edit#

**Comment by gunsch** [comment]
assigning to @KevinMHoffmanUSDS , who's taken on the mantle of continuing forward the "roles & responsibilities" work
