### ISSUE TITLE
[FE] Onboarding Allison Lu

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#50643]
## Background

Welcome! We can use this ticket to track onboarding to the authenticated experience team.

### Intro to team members

Please schedule a short chat with each of these folks. You can schedule individual chats or talk to people in groups if you think that makes sense:

- [x] @Samara-Strauss (government Product Owner)
- [x] @ajakabcin (contractor Product Manager)
- [x] @andaleliz , @aagosto90 , @fmccaf1 (Researchers and Designers)
- [x] @tpharrison  (Backend developer)
- [x] @adamwhitlock1  (Profile team Frontend developer)

### Review documentation
Here are some helpful documents to review on My VA. It would also help if you log into staging and check it out for yourself to get a sense of the full page.

- [x] [My VA product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va)
- [x] [My VA roadmap](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/authenticated-experience/roadmap/my-va-roadmap.md)

### Current projects
_The general structure of our documentation is that we keep an overarching product outline and then individual project outlines within for initiatives or versions/phases of work on those larger products. Here are the projects we currently have going on the My VA team._

- [x] [My VA Audit Improvements](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/2022-audit)
- [x] [Payment Information V2](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/payment-history)
- [x] [Onsite Notifications](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/onsite-notifications)

### Additional resource documentation
- [My VA use case documentation](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/use-cases) (WIP)
- [Onsite notifications use case documentation](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/onsite-notifications/use-cases#onsite-notifications-use-cases)

### Log into staging and check out My VA
You can use the following info to get into staging:
1. Go to Staging.va.gov. and click sign in (upper right corner)
2. Select the ID.me option
3. Enter credentials for staging user 36 (Staging user info can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv) in the sensitive repo. Note that the user number refers to the number in the test user email, not the row number of the table.)
4. Click sign in
5. Accept terms
6. Click continue until you're signed in and automatically redirected to My VA

### Optional -- My VA demo

- [ ] If it would be helpful, one of the My VA team members can walk you through how each feature works

**Comment by BerniXiongA6** [comment]
Making a comment here to note that I'll share this ticket with Allison Lu in my official welcome email. @adamwhitlock1 has agreed to be her onboarding buddy. Email to be sent before or by Friday 1/13/2023 to Allison. Will keep all posted. cc: @Samara-Strauss

**Comment by BerniXiongA6** [comment]
I'm helping Allison as she onboards to our team, in the meantime here's her GitHub handle: allisonlu

**Comment by Samara-Strauss** [comment]
Thank you! I will fill out the Github access request today now that we know I need to do it! She should have access much faster as a result.

**Comment by Samara-Strauss** [comment]
@BerniXiongA6 what email address can I use for Allison? I need it for the Github request form.

**Comment by Samara-Strauss** [comment]
[Request submitted](https://github.com/department-of-veterans-affairs/github-user-requests/issues/14115)!

**Comment by allisonlu** [comment]
Jan. 19th update: 
- can confirm I can log onto staging.va.gov with user 36 credentials.
- I've read through the product outline and roadmap, skimmed through the project documentations (will dive deeper tomorrow)

I'm going to pair with Adam and Tom early next week and shadow them as they navigate current tickets. I think I'll get a good sense of how My VA works after that.

**Comment by allisonlu** [comment]
Jan. 25th update:
- 1:1s done ✅
- I have a high-level walkthrough scheduled with Samara this Friday

Closing ticket now!
