### ISSUE TITLE
Update TestRail access verbiage

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#50656]
### Tasks
On this page: https://depo-platform-documentation.scrollhelp.site/developer-docs/integrate-testrail-with-github there needs to be an update:

- The 2nd sentence under Before You Begin currently reads, "If you do not have a TestRail account, request help from the Testing Tools team in #vfs-platform-support."

- [x] It should read, "If you do not have a TestRail account, request help in #vfs-platform-support." (we would be removing request help from the Testing Tools team)

On this page: https://depo-platform-documentation.scrollhelp.site/developer-docs/create-a-project-in-testrail a similar update needs to made on this page as well.

- Under Before You Begin, it reads "Request access to the Platform TestRail instance from the QA standards team in #vfs-platform support.".

- [x] It should read, "Request access to the Platform TestRail instance in #vfs-platform support." (we would be removing from the QA standards team)

**Comment by laucon** [comment]
Done. I'll deploy these both today with the news edits.
