### ISSUE TITLE
Renewal of VA.gov Platform Authorization to Operate (ATO)

### ISSUE THREAD

**Issue by raywangoctova** [department-of-veterans-affairs/va.gov-team#50663]
## Problem Statement 
VA.gov is a cloud-based application developed for the U.S. Department of Veterans Affairs. It is a one-stop platform for veterans to access various benefits, health care, and services. VA.gov requires a renewal of its Federal Authorization to Operate (ATO) to continue its operations.

## User Impact
If this work is not completed, we cannot continue building. 

## Where was this problem reported?
This is a federal government requirement, and prior ATO approval is near expiration.

## What do we not know about the problem space?
A lot -- we've done this before. Faith has eMASS access and an ATO tracker that we need to convert into a roadmap. 

## What (if any) research or discovery has been done?
none

## What is the acceptance criteria?
ATO documentation is submitted before 9/2023
Approval is granted for another three years.
A plan is created to keep this up-to-date: continuous monitoring, ATO memo follow-ups, etc.

## How should we measure success?
Time before 9/29 that we are "finished" with all the work
The detail in the plan is moving forward to spread this work across the contract years.

# SCOPE
## Preparation:
Review the current ATO documentation, including the system security plan, contingency plan, and privacy impact assessment.
Determine any changes or updates to the application since the last ATO renewal.
Gather any relevant documentation to support the renewal of ATO.
Schedule a meeting with the system owner, stakeholders, and any applicable teams to discuss the renewal process.

## Assessment:
Conduct a thorough assessment of the application, including a review of the security controls, privacy impact, contingency plan, and any required artifacts.
Evaluate the application against VA ATO requirements, including the National Institute of Standards and Technology (NIST) security controls.
Identify any areas that require improvement or update to meet the ATO requirements.

## Update:
Update the security controls, privacy impact, and contingency plan as required.
Address any deficiencies identified during the assessment phase.
Ensure that all updates comply with ATO requirements.

## Testing:
Conduct thorough testing of the updated application to ensure it meets the ATO requirements.
Verify that all security controls, privacy impact, and contingency plans work as intended.
Test the application for any vulnerabilities or risks.

## Documentation:
Prepare a final ATO renewal package, including the updated system security plan, privacy impact assessment, contingency plan, and any required artifacts.
Provide relevant documentation to support the renewal of ATO.
Submit the ATO renewal package to VA ATO Approving Authority for review and approval.

## Approval:
Wait for VA ATO Approving Authority to review and approve the ATO renewal package.
Address any comments or feedback from VA ATO Approving Authority to ensure the application meets the requirements.
Obtain the renewal of ATO and continue the operation of VA.gov.

## Conclusion:
The renewal of ATO for VA.gov is a critical step to ensure the continued operation of the application and to provide veterans with access to their benefits, health care, and services. By following this plan, we can obtain the renewal of ATO and ensure that VA.gov is secure, compliant, and efficient.

**Comment by gary-fallon** [comment]
This is a duplicate.

**Comment by raywangoctova** [comment]
@alyssagallion Gary closed this as a duplicate. But duplicate to what ticket?

**Comment by gary-fallon** [comment]
@raywangoctova apologies. This is a duplicate in the sense that PSEC is already tracking, or will be tracking again soon, tasks necessary for the upkeep and renewal of the ATO.

There were also some gaps in this issue that I felt could cause confusion going forward. For example, the LOE required here is quite high in my opinion and approval is not necessarily granted for another three years -- they could grant a six-month provisional.

Of course, I'm happy to discuss the other gaps whenever it is convenient for you, or I could provide @alyssagallion with the details for you both to discuss at your next 1:1?

**Comment by EricaRobbins** [comment]
@raywangoctova - I believe you asked me to assist you with updating this card for our ATO Renewal. Can you confirm this is the correct card?

Also, do we still consider the ATO Renewal as a Backlog item? I feel it would be considered "In Progress". Thanks!

**Comment by annekerr49** [comment]
no match for roadmap-DMC label

**Comment by annekerr49** [comment]
Ray could you please add this ticket to the DE Products In Process column?  https://github.com/orgs/department-of-veterans-affairs/projects/940/views/2

**Comment by raywangoctova** [comment]
![Image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/103070192/eb57ade9-696f-419e-b360-958ee3e0f46e)

**Comment by jhouse-solvd** [comment]
Attaching a few recent Team of Teams (ToT) updates: 

**ToT 8/1/23**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa280IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3ae608be7c75500b1370bfad52dd6e193119cf23/Screenshot%202023-08-24%20at%2014.26.40.png)

**ToT 8/8/23**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa3c0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--deaaee5e1d917b474206cfa37325a91a8a69eeda/Screenshot%202023-08-24%20at%2014.27.20.png)

**ToT 8/15/23**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBazQ0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5ac1698bd6df8b9c6d6a178e93b0bff5b528057d/Screenshot%202023-08-24%20at%2014.28.53.png)

**ToT 8/22/23**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBazg0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3f56f1a1bc5ffafb1eb3130f56c75829fd325fc1/Screenshot%202023-08-24%20at%2014.29.47.png)

**Comment by jhouse-solvd** [comment]
Priorities:

1. Plans (IRP, PIA, DRP, CMP) must be completed before system categorization.
2. _System categorization and control set review (update control narratives and artifacts). <-- might not be possible by end of September_ 
3. SCCD > 90%
4. Findings (high findings remediated)
5. POA&Ms reviewed and milestones updated
6. Technical scans need to be current, including database scan.

If we’re not going to complete the system categorization by the end of September, we can focus on the other items to put us in a better position should we get a provisional ATO.

**Comment by raywangoctova** [comment]
2023 Q4 VA.GOV PLATFORM AUTHORIZATION TO OPERATE STATUS

![Image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/103070192/4d1ad3d6-bce8-4ada-b674-45caf2df1404)

**Comment by jhouse-solvd** [comment]
**Roadmap progress for major ATO items as of today, 9/22/23**
_Note: Compare the previous version [posted in a comment above](https://github.com/department-of-veterans-affairs/va.gov-team/issues/50663#issuecomment-1684389295) and you'll see various items now "Done" or "In Progress"._

![VA Gov Platform Security 100-Day Roadmap_2023-09-22_19-27-20](https://github.com/department-of-veterans-affairs/va.gov-team/assets/46828900/c91aa1df-2c9f-4fcd-8260-6060c71ae44f)

cc: @raywangoctova

**Comment by jhouse-solvd** [comment]
**Roadmap progress for major ATO items as of today, 9/22/23**
_Note: Compare the previous version [posted in a comment above](https://github.com/department-of-veterans-affairs/va.gov-team/issues/50663#issuecomment-1731942623) to see various items now "Done" or "In Progress"._

![VA Gov Platform Security Team 100-Day Roadmap_2023-11-22_00-39-08](https://github.com/department-of-veterans-affairs/va.gov-team/assets/46828900/9dc3fbed-c982-4656-80f1-9f7871bdc744)


cc: @raywangoctova

**Comment by jhouse-solvd** [comment]
**Team of Team Slide for 11/21:**

[Team of Teams - PSEC - 2023-11-21.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/13432294/Team.of.Teams.-.PSEC.-.2023-11-21.pdf)

**Comment by raywangoctova** [comment]
We are in RMF Step 4.2 Control Validation.

![Image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/103070192/a1f37158-c6df-4cf8-9f87-8dfa070ea402)

**Comment by raywangoctova** [comment]
RMF Step 4 Control Assessment was administrative advanced on 12/06/2023 and it is ready for the team to proceed to Step 5. 

![Image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/103070192/e1f63739-85a5-4a49-ac29-eedda95c2977)

**Comment by jhouse-solvd** [comment]
The ATO Package has been submitted to the AO for review (RMF Step 5.3). We're awaiting review and decision from the Authorizing Official (AO) and expect to have more news to share early in the new year. 

The roadmap (attached) shows other recently completed key activities and identifies the ongoing plan to assess, remediate, and monitor security controls. 

In the meantime, please reach out with any feedback, questions, or concerns. 

_p.s. Happy Holidays!_

<img width="643" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzZEQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1183f186bef33800a903effe69afe5ffa9fe69a9/VA.Gov-Platform-Security-ATO-Renewal-Roadmap.png" alt="VA.Gov-Platform-Security-ATO-Renewal-Roadmap.png" />

cc: @raywangoctova @JonathanKamensDVA @jwoodman5 @little-oddball @andreahewitt-odd @kenmayo

**Comment by raywangoctova** [comment]
The ATO renewal work was completed and the new ATO will be valid for 13 months.   

![Image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/103070192/387a614b-98b7-4638-ad1a-fd286c5d38e0)
