### ISSUE TITLE
[BE][SPIKE QUESTIONS] - Unified check-in experience

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#50683]
## Questions

1. [BE] How will we handle persistent LoRota user data if users can validate at any time from any device?
2. How will UUIDs work in this new model?
3. What changes to vetext will happen for day of and pre-check-in? (For example, can we suppress appointment reminders on days that Veterans have scheduled appointments at PCI-enabled clinics.) 
4. What is a unique way that we can identify the user for reporting? (datadog, sentry)
5. Do we want to incorporate full auth and profile?
6. How far into the future are we going to fetch appointments?
7. How are we going to show past appointments?
8. Do we need to still consider pre-check-in?

**Comment by loripusey** [comment]
closing and moving the questions to the epic
