### ISSUE TITLE
Contact Center Review for Profile - Misc Updates

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#50686]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
*Please provide the name(s) of your product and a high-level description of your product.*
The Profile team has made a number of small updates within some of the profile pages which are mostly around tweaks to alert messaging (changes are noted in the CC guide).
### Launch Date
*Please provide the launch or rollout date and details.*

November 2022 updates

### Version Number
*Please provide the version number of the guide and/or video.*

Profile Guide v5.2.2

### Product Guide
*Please provide product guide link*

See comment section below to download the product guide.

### Product Video
*Please provide product video link*

### Product Video Transcript
*Please provide product video transcript link*

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by SKasimow** [comment]
VAgov.profile.v5.2.2.  [https://app.zenhub.com/files/133843125/5b571df6-c1ec-44cc-826d-6e0934bd8cce/download](https://app.zenhub.com/files/133843125/5b571df6-c1ec-44cc-826d-6e0934bd8cce/download)

**Comment by SKasimow** [comment]
Hi @starlow00 - we've made some minor updates to the guide over the last month so wanted to collect a few before sending you this new update. Can you review when you have a chance?

**Comment by starlow00** [comment]
Hi @SKasimow. I will review it today!

**Comment by starlow00** [comment]
Updates look good, @SKasimow. Sent for VEO review.

**Comment by SKasimow** [comment]
Thanks @starlow00

**Comment by SKasimow** [comment]
Adding @Samara-Strauss for tracking purposes

**Comment by starlow00** [comment]
[My VA.gov Profile product guide v5.2.2.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/10261892/My.VA.gov.Profile.product.guide.v5.2.2.docx)
No updates from VEO. Attaching copy to the ticket.
