### ISSUE TITLE
Adding [michael antiporta] to DSVA Slack

### ISSUE THREAD

**Issue by elizabethkochBT** [department-of-veterans-affairs/va.gov-team#50691]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

Please add [porta@themostudio.com](mailto:porta@themostudio.com) as a full member.
Porta is the Product Director for the new identity product team (login.gov adoption).

**Comment by eunicegar** [comment]
Porta shows in Slack already.
