### ISSUE TITLE
Upgrade Ruby from 2.7 to 3.0 (Before it is EOL)

### ISSUE THREAD

**Issue by raywangoctova** [department-of-veterans-affairs/va.gov-team#50697]
Need to update #49669 to use this project template.

## LOE
Large
## Problem Statement 
We are currently on ruby 2.7, which is going to be end of life'd on March 31st 2023 [EOL schedule](https://endoflife.date/ruby).

After it is EOL'd we will not be able to get support and features we have implemented will no longer be supported potentially leading to a poor Veteran experience on VA.gov 

## User Impact
*How many users are being affected? What kind of user (VFS engineer vs. VFS designer)? What is this blocking those people from doing? What would fixing this problem allow the impacted users to do faster/better?*

## Where was this problem reported?
[EOL schedule](https://endoflife.date/ruby) and BE COP

## What do we not know about the problem space?
That we have to update 

## What (if any) research or discovery has been done?
None

## What is the acceptance criteria?

- [ ] Everything Ruby is updated to at least 3.0 (which is not EOL'd until March 31 2024)

## How should we measure success?
*What are the key performance indicators? What do we expect solving this problem to impact? How should we measure the impact (both where should we pull the data from and what should the calculation be)? Do we need to start the project by defining baselines or do they exist somewhere?* 

## TODOs
- [ ] Convert this issue to an epic

**Comment by andreahewitt-odd** [comment]
Previous issue: https://app.zenhub.com/workspaces/platform-project-planning-63211892d241f62032d8aa58/issues/gh/department-of-veterans-affairs/va.gov-team/49669

**Comment by annekerr49** [comment]
Upgraded to Ruby 3.2  Per team discussion to day we know this issue is closed and all epics are closed.
