### ISSUE TITLE
Update PR Expectations Documentation for VFS Teams

### ISSUE THREAD

**Issue by rtluu** [department-of-veterans-affairs/va.gov-team#507]
## User Story
As a VFS Developer, I need clear expectations for how to write PRs so that VSP devs aren't burdened during code reviews.

## Goal
Improved PR's from VFS teams and less time spent conducting reviews / going back and forth to get code in PR's reworked

## Acceptance Criteria
- [ ] PR/code review Expectations are updated with feedback based on our experiences
- [ ] The [Code Review Norms] lives in va.gov-teams
- [ ] documentation is distributed to VFS teams

## Definition of Done
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by andreahewitt-odd** [comment]
@accbjt is going to do some discovery to see if this work is still relevent

**Comment by accbjt** [comment]
@johnpaulashenfelter Code review guidelines:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/code_review_guidelines.md

**Comment by johnpaulashenfelter** [comment]
Its a little hard to deal with content in that repo right now :/

**Comment by johnpaulashenfelter** [comment]
Done. 

i also updated the onboarding PR section a bit https://docs.google.com/presentation/d/1qewAANeGvQSTfXK4m40lO2N0-S9IaCfl7JlZY_0EI6A/edit#slide=id.g5ce90f7698_0_94
