### ISSUE TITLE
SPIKE: Look into how we would link to VAOS and what info we would send them

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#50719]
## Questions 
- If we were to provide a link in pre-check-in for a Veteran to go over to VAOS to cancel their appointment, what could we send them (url params) to allow them go directly to that appointment and perhaps trigger the cancellation ?
- When an appointment is cancelled in VAOS, is there a confirmation message where they indicate if they really want to cancel the appointment?
- What technical hurdles does this scenario present?

**Comment by loripusey** [comment]
@brianseek @acrollet @randomsync  @wullaski @kanchanasuriya 
The new VAOS Service is now in production. Might be worth getting access to their service documentation to see what's out there that we would use for this effort.
[see Slack thread](https://dsva.slack.com/archives/C03R5SBELQM/p1671071185524079)

**Comment by kristenmcconnell** [comment]
@loripusey Based upon [the recommendations in this UX ticket](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/50751) (which aren't finalized), we might not need/want to send a Veteran over to VAOS to cancel. Therefore, should work continue on this ticket?

**Comment by acrollet** [comment]
Closing in favor of canceling via VEText or directly in pre-check-in.
