### ISSUE TITLE
Test and Validate Datadog Online Archive

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#50736]
- [x] Enable Datadog Online Archive feature
    - [more info](https://www.datadoghq.com/blog/online-archives-datadog/)
- [x] Check back in 32 days later to ensure data is retrievable 
- [x] report back to Platform leadership regarding the results - present at demo day

**Comment by ianhundere** [comment]
dd online archive feature has been enabled

**Comment by ianhundere** [comment]
recovering via online archive: https://vagov.ddog-gov.com/logs/pipelines/historical-views/dec-17-jan-17-service-vets-api
