### ISSUE TITLE
Qualitative Data Request

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#50745]
### Data Type Requested

User Surveys

### Date Range Start

12/1/22

### Date Range End

12/31/22

### Product Name(s)

Claim Status Tool (Benefits Team 1)

### Product Description

The Claims Status Tool is where Veteran can go to check on the status of their claims and appeals. On 12/6/22, we began rolling out a feature (to 1% of users) that allows them to view and download their claim decision letters within the CST. As of 12/14/22, we have rolled this out to 25% and will continue to a full 100% rollout in the coming weeks and into Jan 2023. 

### Product URL(s) and/or term(s)

**Terms**
We are looking for feedback related to the following terms: 
- "Claim letter"
- "Decision letter" 
- "Notification letter"
- "Claim status"
- "Download decision letter"
- "Download claim letter"

**CST overview page**
https://va.gov/track-claims/your-claims 

**Viewing a claim page**
https://va.gov/track-claims/your-claims/600308728/status

**Claim letters page**
https://staging.va.gov/track-claims/your-claim-letters

We are looking for feedback that could come from any of these URLs, or any other page that is part of the Claim Status Tool.

### File Delivery Format

One file, different tab for each term/URL

### VA Email Address(es)

skyler.schain@va.gov

### Add Assignee and Labels

If not already done so, please ensure @ianMcCullough-ob is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by ianMcCullough-ob** [comment]
Folder was shared with all relevant exports.
