### ISSUE TITLE
Improve MHV Inherited Proofing Errors

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#50740]
## Description
Add more actionable information to various MHV inherited proofing errors.

## Tasks
- `IdentityDocumentMissingError`: separate correlation id & identity doc missing errors
- `UserMissingAttributesError`: include which attrs missing
- `/callback` redirect in the same way as SiS on error

**Comment by bosawt** [comment]
Callback errors should redirect to va.gov frontend
