### ISSUE TITLE
Update Prod VIC App URL

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#50756]
VIC App team (Joe V. and Ranjith) have asked us to update the current VIC app redirect URL:
PRODUCTION:

                SSOe Base URL: https://vicbdc.prod.va.gov/

**Comment by alyssagallion** [comment]
PR Open. Add the updates to manifest repo, once have that in might get approval.

**Comment by joeniquette** [comment]
Manifests (EKS) repo related ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/50816

**Comment by alyssagallion** [comment]
Blocker: VIC App Team.

**Comment by joeniquette** [comment]
VIC team has made their changes and we need to push through the URL changes in EKS
