### ISSUE TITLE
[Desk Research] Supp Claims PACT Act

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#50752]
Context and Conclusions
Please begin to conduct desk research on the existing Notice of Disagreement.

Resources to check out
https://www.reddit.com/r/VeteransAffairs/
https://www.reddit.com/r/Veterans/
https://www.va.gov/resources/the-pact-act-and-your-va-benefits/

About Supplemental Claims
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/decision-reviews/Supplemental-Claims

About PACT Act
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/abd-vro/2022-06-PACT-Act-presumptive-veterans/PACT-Act-research-report.md

and search for "Pact Act" "Supplemental Claims" and reach through their experiences when you have a good understanding of the policy and how it will impact Supplemental Claims.

Document your findings here https://docs.google.com/document/d/17OBZtP2uX1XxIYwEBMlhztWrcc6mgf9rnF486ZF06NU/edit

Reach out to Eileen with questions.

**Comment by uxgary** [comment]
I've added my report to our [research folder](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Supplemental-Claims/Research/1222-PACT-Act/desk-research-pact-Act.md)
