### ISSUE TITLE
Explore how we want to offer cancellation and whether full authentication needs to be involved

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#50751]
## Questions to Answer
- Can we give Veterans who use Pre-check-in the ability immediately cancel an appointment or would we have to send them over to VAOS

## Tasks
- Explore how we want to offer cancellation and whether full authentication needs to be involved

**Comment by benbrasso-agile6** [comment]
Is there a current path today that Veterans can cancel in VEText? Or, it's "possible" now, but the messaging doesn't really make it available. 

Also, what happens when a Veteran revisits pre check in for a cancelled appointment?

**Comment by kristenmcconnell** [comment]
| Also, what happens when a Veteran revisits pre check in for a cancelled appointment?

Should this be a different ticket? It sounds like to might be worth exploring, but out of scope for this ticket.

**Comment by benbrasso-agile6** [comment]
If we do, I think the scenario is looking at how a cancelled appt appears on the confirmation page. I.e., someone reclicking pre check in link after it's already completed once. we could follow VAOS, but I don't personally love their solution. It could be added to the backlog, if you feel like dropping one in.

**Comment by loripusey** [comment]
In response to Kristen's comment, it would probably be helpful to show cancelled appointment in day-of and it has been on our backlog for a long time. However, since we only show today's appointments in Day-of and if they use Pre-Check-in to cancel an appointment, does it make sense to show the cancelled appointment? If you no longer have the appointment, does not seeing it tell you that you don't have the appointment?

**Comment by kristenmcconnell** [comment]
I think showing the canceled appointment in day of experience would do two things. 
1. Confirm that VA really did receive your cancelation.
2. Let a Veteran know of any appointments canceled without them realizing it (such as a doctor is out sick and the appointment was canceled shortly before it was supposed to occur).

For those reasons, I would show canceled appointments in the day of experience.

**Comment by kristenmcconnell** [comment]
That is true. That rule follows the va.gov design principle of not letting a Veteran go down a path that you know they can't complete something. So the value added to showing canceled appointments within pre-check-in would only be when you have more than one appointment in the day. This is a smaller value add.

Should we expand the VeText messages? I believe we only have this message currently.
<img width="672" alt="Screen Shot 2022-12-19 at 3 07 50 PM" src="https://user-images.githubusercontent.com/66287082/208511278-1c045c5f-efd0-4865-af0c-cfff235b2204.png">

Should we display a different SMS when we know only appointment for the day was canceled?

**Comment by benbrasso-agile6** [comment]
I think adding a message when we know an appointment that day is cancelled would be an add-value for Veterans.

**Comment by kristenmcconnell** [comment]
I added a ticket about the [new SMS message](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/50929) about canceled appointments in the day of workflow. 

I also found that we already did the work to [create wireframes to show that an appointment is canceled on a pre-check-in confirmation page](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/40179).

**Comment by acrollet** [comment]
per @loripusey let's ask @batemapf for more information on what's desired here: can we offer appt cancellation in pre-check-in for veterans that might not know that it's possible to cancel in VEText?

**Comment by batemapf** [comment]
i think the question at the top of this thread [was answered](https://github.com/department-of-veterans-affairs/va.gov-team/issues/50751#issuecomment-1357993537). i think the remaining work here is getting an answer to the "what happens if a patient wants to cancel after SMS confirm?" question, [over in slack](https://dsva.slack.com/archives/C02GXKL8WM6/p1671477944827839). if the answer is "we don't have a way to do that", then i think we should weigh the effort vs. value of adding it into the precheckin flow. but maybe im just running us in circles?

**Comment by kristenmcconnell** [comment]
Based upon [Shane's response](https://dsva.slack.com/archives/C02GXKL8WM6/p1671563586687709?thread_ts=1671477944.827839&cid=C02GXKL8WM6), it seems like adding cancel within pre-check-in right now would be a very small value add. It might even complicate things based upon how easy the VeText workflow is. My recommendation would be to not pursue further work on this feature at this time.

What do you think? @batemapf and @loripusey.

**Comment by loripusey** [comment]
I agree, the intent of our applications is to prepare for and check-in for an appointment you plan to attend; cancel doesn't seem to fit into that intent

**Comment by batemapf** [comment]
cancel the cancel functionality!

Patrick Bateman (he/him/his)
U.S. Digital Service
Office of the Chief Technology Officer
Department of Veterans Affairs
________________________________
From: Lori Pusey ***@***.***>
Sent: Tuesday, December 20, 2022 2:30 PM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Patrick Bateman ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Explore how we want to offer cancellation and whether full authentication needs to be involved (Issue #50751)


I agree, the intent of our applications is to prepare for and check-in for an appointment you plan to attend; cancel doesn't seem to fit into that intent
