### ISSUE TITLE
AWS access for Gregg Puhala

### ISSUE THREAD

**Issue by GcioGregg** [department-of-veterans-affairs/va.gov-team#50796]
### COR Name

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative Name

GovernmentCIO - Kimberly O. West

### Your Name

Gregg Puhala

### Your Email

gregg.puhala@va.gov

### Team, Role, and Company of the target individual

Developer VFEP (Education), GovCio/DBItPro

### Product Manager (PM) name and email

Darla van Nieukerk - darla.vannieukerk@va.gov

### Product Owner (PO) name and email

Michael Napper - michael.napper@va.gov

### Desired AWS Access

I need ssh access to the staging and dev EC2 instances to tail logs after code deploys, confirm tasks were run, configurations are set correctly, and troubleshoot issues..

### Access Expiration

12/22/2025

### Additional Notes

COR Name: Joseph Riccio - [Joseph.Riccio@va.gov](mailto:Joseph.Riccio@va.gov)

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [x] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [x] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by GcioGregg** [comment]
Can somebody please take a look at this?  Thanks, Gregg

**Comment by little-oddball** [comment]
@GcioGregg - I am hopping in to try and help w/ these items. Our Gov't PO had a transition and we now require to have the eQIP transmittal date provided. Would you be able to work with your PO/PM to provide that? Once that has been applied to the ticket I push move it forward to our Gov't PO for a review/approval. Thanks and sorry for the delay and any inconvenience .

**Comment by GcioGregg** [comment]
@little-oddball I reached out to my PO/PM and we believe my eQIP transmittal date is 10/11/2022.  Let me know if I need to provide any additional  info.  Thanks!

**Comment by BillChapmanUSDS** [comment]
Approved for ongoing access to dev and staging as requested.

**Comment by GcioGregg** [comment]
@BillChapmanUSDS how can I get my initial password?

**Comment by little-oddball** [comment]
@BillChapmanUSDS VFS teams do not have access to DD at the moment. That is one of the initiatives we have been pushing out and look to wrap in some upcoming sprints. Outside of that, I can't speak to the specific circumstances / needs here.

**Comment by GcioGregg** [comment]
Can anyone point me in the right direction re: how to obtain my login/password credentials for this recently granted access?  I was thinking I'd get an email after having been granted access, but I did not.  Thank you.

**Comment by pjholyoke** [comment]
Hey there @GcioGregg, I'm still working on this one. I'll shoot you a message when I have your access sorted out. (Unfortunately this is still a manual process)
