### ISSUE TITLE
Adding Jack Stevens to DSVA Slack

### ISSUE THREAD

**Issue by aschulhof** [department-of-veterans-affairs/va.gov-team#50791]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

- Please add jack.stevens1@va.gov as a full member.

Are you requesting to add an individual as a:

- Full member
- Single guest
- Multi-channel
- Switching from single-channel to multi-channel?
- What channel(s) do they need to be added to?

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add [_insert email_] as a single-channel guest to [_channel name_].
- Please add [_insert email_] as a multi-channel guest to these channels: [_channel names_].
- Please change the status of [_slack username_] from [_current status_] to [_desired status_]

**Comment by batemapf** [comment]
done!

**Comment by eunicegar** [comment]
person is already in workspace

**Comment by eunicegar** [comment]
checked status and is active. Resent invitation

**Comment by Hortonio** [comment]
@eunicegar can you please add him to the following channels?

- #check-in-releases
- #check-in-experience
- #check-in-experience-engineering

**Comment by eunicegar** [comment]
he was invited in above teams.
