### ISSUE TITLE
INTL - Chatbot - Design QA

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#50805]
# Request a design QA for new dashboard/cards

## What this form is for
As we roll out new edge case dashboards, other non-standard dashboards, or new cards to existing dashboards, we need to make sure that they are easy to use and understand.

## Resources
- [Chatbot Dashboard](https://va-gov.domo.com/page/939649897?userId=1917693988)
- **Confluence instructions:** [How to design QA a Domo dashboard](https://vfs.atlassian.net/wiki/spaces/AT/pages/2216002036/How+to+Design+QA+a+Domo+dashboard)
- [Tracking sheet](https://docs.google.com/spreadsheets/d/1Tf9hcqwXySDtnm13oZ3frJdMUsuBGLFzEdV_4YoMPA8/edit#gid=1325615287)
- [Chatbot dashboard request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/45133)
- [Chatbot modeling ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/49825)

#### For person submitting ticket
- [x] This QA is for an entire new dashboard.
- [ ] This QA is for new cards only. _(Please add titles below)_
- [x] Cards in this QA include drillpaths.
   - [ ] Applies to all cards.
   - [x] Applies to only some cards. _(Please add titles below)_

Is there anything else the person conducting the Design QA needs to know about scope of data, filter functionality, etc.?
- [ ] Yes
- [ ] No _(Please describe)_

#### For person conducting QA
- Log into the `Participant Tester` account in Domo for all tests.
- Copy "Usability checklist" table from [How to design QA a Domo dashboard](https://vfs.atlassian.net/wiki/spaces/AT/pages/2216002036/How+to+Design+QA+a+Domo+dashboard).
- Make any modifications to checklist specific to this dashboard.
- Complete all dashboard, section, and card-level checks.
  - If check is passed, paste "Pass ✅" in the Pass/Fail column
  - If check does not pass, paste "Fail ❌" in the Pass/Fail column. Describe issue and describe scope of cards affected in Actual Behavior column.
- Add any additional notes needed to the Github comment and submit, tagging the person responsible for making changes.
- Repeat until all checks have passed.

## Acceptance Criteria
- [ ] The dashboard is usable and follows the design as closely as possible.
- [ ] All cards and filters are configured correctly.
---

**Comment by michelle-dooley** [comment]
@chloedotbrown - Everything looks great!!  Just need to add the "How-to" link.

<html>
<body>
<google-sheets-html-origin><style type="text/css"></style>

Test | Expected Behavior | Actual Behavior | Pass/Fail
-- | -- | -- | --
Dashboard title | Text fully readable, without errors |   | ✅
Date filter | Every chart gets filtered for date and group by settings are changed |   | ✅
Section titles | Every section title & subtitle are spelled correctly |   | ✅
Section resources | Links to How-to Guide + Data Dictionary (if available) | Neither present.  Add link to "How-to".  Data dictionary - NA | ❌
Chart titles | Every chart title is fully readable, without errors, relevant to chart |   | ✅
Chart descriptions | All chart descriptions are disabled, so nothing appears when hovering over title |   | ✅
Hover text | All hover text "makes sense" and is spelled correctly |   | ✅
Annotations | Every annotation "makes sense," is free of errors, and visible within text box |   | ✅
Filter cards | Filter cards are easy to read and use |   | ✅
Text box formatting | Every annotation and section title box shows all text, does not generate scroll bar |   | ✅
Card interactions – filters | Clicking data point does not filter other cards |   | ✅
Card interactions – card detail | Chart title opens card in new tab |   | ✅
Card drillpaths | Card detail view filters to correct drillpath _(if using)_ |   | ✅
Display settings – date units | Date grouping ("by week/month") appears under each title |   | ✅
Display settings – multi-value gauges | Directionality of colors in period-over-period comparison makes sense |   | ✅
Display settings – summary numbers | All non-multivalue gauge charts without a date axis show date range in summary number |   | ✅
Related cards | In card detail view, all related card previews have been deleted |   | ✅
Appendix | No charts or notecards appear in appendix below dashboard |   | ✅


</body>
</html>

**Comment by michelle-dooley** [comment]
@chloedotbrown - Also what is '(first page of session)' in the 'Top pages viewed before accessing Chatbot'?  I know its just what the data pulls back just want to be able to explain in case asked.

**Comment by chloedotbrown** [comment]
"(first page of session)" is what I added in through a Beast Mode whenever the `previous_page` field was null. This is when Chatbot was the entrance page for a session. If you think other phrasing would be clearer, just let me know!

I'm a little hesitant to add links to the "How to use this dashboard" document, since the write-up and videos are SO standardized dashboard specific. I worry it may actually confuse users if it's describing functionality that this edge case doesn't have. What are your thoughts?

**Comment by michelle-dooley** [comment]
Gotcha on "first page of session" that makes sense, we are good.

Was wondering the same thing about the "how-to" I'm good with leaving it off.

**Comment by michelle-dooley** [comment]
Design QA complete.
