### ISSUE TITLE
HPA scaling for bulkhead deployments

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#50800]
## Description

The new helm chart for vets-api has adopted bulkhead deployments. This means that each vets-api module will have ingress routes/services and requests will be routed to separate pods to mitigate the latency for "slow routes". If one pod fails, it won't take down the entire deployment.

For this new deployment style, we need to create HPA resource (with min max autoscaling rules) for each deployment (e.g. vets-api, address, evss, etc). The puma backlog metric will have to be based on/scale per deployment.

**Comment by laineymajor** [comment]
On hold until complete with vets-api server migration (dev) to EKS.

**Comment by LindseySaari** [comment]
There's a way to separate the puma.backlog metrics out per deployment. I have this one for the address deployment using the `kube_deployment` tag `sum:puma.backlog{kube_cluster_name:dsva-vagov-dev-cluster,kube_deployment:address} by {kube_cluster_name}`

Tested via the [metric explorer](https://vagov.ddog-gov.com/metric/explorer?start=1671131546839&end=1671135146839&paused=false#N4Ig7glgJg5gpgFxALlAGwIYE8D2BXJVEADxQEYAaELcqyKBAC1pEbghkcLIF8qo4AMwgA7CAgg4RKUAiwAHOChASAtnADOcAE4RNIKtrgBHPJoQaUAbVBGN8qVoD6gnNtUZCKiOq279VKY6epbINiAiGOrKQdpYZAYgUJ4YThr42gDGSsgg6gi6mZaBZnHKGniqyPKVGAB0AEYYmQDWaDgwwC14DXBOmWh4Ggg6TpHqyFAaAG4YALSzMDjTcwIrA0Mj2hTdvU4C8u1Y6iIIyBhQUHYaPAAEDVi3XT19G8Oj43A8IDwAulSudx4TChcKA1TAjAxUrxH7-EDDLBoHKgeQYZEIEbKKAdfogjQQTKJNCiPpyRTlHAkqDE0lOehMZQiNweNA-fgQeyYLBOck5EAkkRKP48PgIw7iADCUmEMBQImBaB4QA)

This means that we can loop through deployments (in values.yaml) and define an HPA resource for each bulkhead deployment (vets-api-web, address, evss/bgs etc)

**Comment by LindseySaari** [comment]
@RachalCassity Also adding documentation to this ticket :)
