### ISSUE TITLE
SOCKS access for Garrett Rabian

### ISSUE THREAD

**Issue by gmrabian** [department-of-veterans-affairs/va.gov-team#50809]
### Your Name

Garrett Rabian

### Your Email

garrett.rabian@coforma.io

### Your Role and Team

Software Engineer on `VA Forms` team

### Product Manager (PM) name and email

Megan Siddle, megan.siddle@oddball.io

### Product Owner (PO) name and email

Matthew Dingee, matthew.dingee@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCsCzznUn+VXZSyjen2VthNT1ISb6/NLGjglF1dg8W0RFo9aQWk5ZBH3iQSAeH4ibS5N6uMSskQnF0Ii6uE6oLEhpZio7j8LApleJtmh0OZmVc/j0nHoViIAeDl56D23fCc5QNpZxlaJXtE5KArO4U1DHCM8FYihe0ZFi63rK3lLVjzyw4vLp0b3Zy5+yBHfwoq/zga0KFzvH4rxaBBj773PT4lENcgSjf1VM8qVkII8MjQLxeNz8vAkPO766mHxrzlmNXy4RKdb3ji3b8lUT2nlSVef9169B8WgKuDgL7riVXIvcCkg5vq+LDUW4agJhxHyo/fTb8QfjLwvZQ95JfQaUUVYwCEsK9WdCA0aNDph1KsbHcpYMSov2uvTAhLMk0ocZZEDBlQCfGPUctdukSCofQ5hhmmrE94TbxmPmbo3PrXwt6QicpYwXEXJJpoOsd/DFkiDzrUle2356/e7xrQ9sjfve9e29iwRWoC1pQ7hyw0sNJB56+z1155L6ZwInc= gmr@Coforma-WQ7N5WR2XJ-Garrett-Rabian.local

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by mynar7** [comment]
Approved and Merged https://github.com/department-of-veterans-affairs/devops/pull/12365

@gmrabian please verify you have access.

**Comment by gmrabian** [comment]
@mynar7 verified! I was able to complete the setup. Thanks!
