### ISSUE TITLE
Update Manifests file for VIC App Changes

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#50816]
Looks like you've updated vets-api settings.local.yml.j2. Please update the corresponding values in the following k8s ConfigMaps:
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps/vets-api/, file: values.yaml
In the values.yaml, please add the update values in the #ConfigmapSection.
ex:
foo: <%= ENV['FOO'] %>
If you have updated a secret value, please also update the corresponding secrets.yaml:
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps/vets-api/templates, file: secrets.yaml
ex:
key: /foo
name: foo
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps/vets-api/, file: values.yaml
In the values.yaml, please add the new secret values to the #SecretsSection.
ex:
name: foo
path: /foo
env_var: FOO
Please add a link to your vsp-infra-application-manifests PR.
Additional context: https://vfs.atlassian.net/wiki/spaces/OT/pages/2146140164/Keep+EKS-Deployed+Vets-API+Up+to+Date+with+BRD-Deployed+Vets-API

**Comment by ianhundere** [comment]
https://github.com/department-of-veterans-affairs/devops/pull/12358

**Comment by ianhundere** [comment]
there hasn't been any work in regards to the revproxy in eks in staging or prod, so i don't believe we can do this just yet until the team responsible for moving vets-api to eks has begun that work.
![image.png](https://images.zenhubusercontent.com/624b40ac4980d90d75917e4c/4855b723-1337-4540-8e6d-7c2257bd3a3a)
ps we could do it for them, but...
