### ISSUE TITLE
User unable to submit claim application of increase of disability

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#50811]
## Description

**Salesforce Ticket ID:** 
09004749

**Issue Veteran is experiencing:**

After the Veteran uploaded medical records for the application to increase disability, they received a generic error message: We're sorry, we can't submit your application now.

Veteran is using Google Chrome on a desktop (unsure of OS). 

Issue reported around 7p EST.

**Comment by kjduensing** [comment]
According to an entry in Sentry that appears to match the condition of the report, this is the error logged:

`form - The property '#/vaTreatmentFacilities/0/treatedDisabilityNames' did not contain a minimum number of items 1 in schema XXXX-XXXX`

**Comment by kjduensing** [comment]
Kim reaching out to Veteran for more information.

**Comment by sortizsh** [comment]
@saderagsdale flagging this for squad 2 grooming in January. This is a contact center ticket that came in that we think relates to 526.

**Comment by saderagsdale** [comment]
@kjduensing @sortizsh @Kimberley2019 Hi all - can you confirm that this Veteran was instructed to fill out a paper form since their submission failed?

**Comment by saderagsdale** [comment]
@kjduensing Did we store a save in progress copy on the front-end that we can review, to see if the Sentry error matches the data stored?

**Comment by saderagsdale** [comment]
Removed grooming and squad labels until we have reproducible steps.

**Comment by kjduensing** [comment]
@saderagsdale thanks for the questions!

> can you confirm that this Veteran was instructed to fill out a paper form since their submission failed?

Checking now

> Did we store a save in progress copy on the front-end that we can review, to see if the Sentry error matches the data stored?

We did, I can get you the application ID and/or the request ID. If you think GH is an appropriate place for these, I'll drop em here. Otherwise, let me know how you want me to get that info to you

Thanks!

**Comment by kjduensing** [comment]
@saderagsdale 

> paper form

The Veteran was aware of the option to fill out a paper form. CC says this route is not always helpful, and that the Veteran was not interested in taking that route.

**Comment by saderagsdale** [comment]
We cannot guarantee the timeline to reproduce, validate, or resolve this issue. The Veteran needs to be advised to fill out a paper form if they are unable to re-submit. 

I don't need the IDs (perhaps a dev would need those). I am curious to know if you can see anything missing from the data they submitted on the frontend. Basically, does the Sentry error make sense and is it specific enough to diagnose the issue? Did the Veteran skip a required field? Did they not respond to conditional logic regarding facilities?

**Comment by Kimberley2019** [comment]
@saderagsdale pursuant to our prior meetings, included in the templates that we send, there is always the option to mail in their application.  
Mailing in an application is not always feasible for the veteran.

**Comment by Kimberley2019** [comment]
@saderagsdale I have given all details provided to @kjduensing and Jared.  The user also provided a screenshot, which has been provided.  Would they be able to give you the details?

**Comment by kjduensing** [comment]
@saderagsdale, I don't really have much more detail than what's already in the ticket. I might be able to add a screenshot of the error message, but the screenshot provided by the Veteran has some things on it that _might_ be considered PII. I'll look into that for you. 

I don't know why the Veteran is unable or unwilling to use the paper form. @Kimberley2019 Do you know why a paper form is unfeasible in this case?

**Comment by coforma-terry** [comment]
In order to best serve the veteran, contact center requested a shadowing call where our engineers observes the Veteran try to complete his task, ask questions, etc. This call has been scheduled with Kyle, Kimberley, and the Vet for next Tuesday Dec 27th at 3PM ET.

**Comment by Kimberley2019** [comment]
Hi all!  After reiterating to the veteran additional ways to submit the application, he has stated he would rather have the issue resolved.  Appropriate documentation can be provided if necessary.

I will inform him we are confirmed for 12/27/22 @3PM ET and send out invitations for all parties.

Thank you to all who made this possible!  It is appreciated.

**Comment by saderagsdale** [comment]
Resolved yesterday.

**Comment by Kimberley2019** [comment]
@saderagsdale @kylesoskin THANK YOU both so very much for meeting with the veteran.  He was totally appreciative of the time we took to resolve his issue.
