### ISSUE TITLE
[Monitoring] De-duplicate the Prometheus ruleset for EC2s (for monitors setup in Datadog)

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#50823]
## Description 
Duplicate monitors lead to extra noise and confusion. As monitors are being set up in Datadog, rulesets in Prometheus should be removed to avoid duplicate information sources for platform operators. 

## Technical notes 
- Prometheus rulesets can be found [here](https://github.com/department-of-veterans-affairs/devops/tree/master/ansible/deployment/config/prometheus/rules)
- An example PR can be found [here](https://github.com/department-of-veterans-affairs/devops/pull/12351/files)

## Acceptance Criteria 
- [ ] Rules have been evaluated for deduplication 
- [ ] Rules have been removed for components and services that have corresponding monitors in Datadog 
- [ ] There is a link to the replacement monitor(s) in the PR comments
- [ ] A follow-up issue has been created to capture anything missing from Datadog that exists in Prometheus

**Comment by rsmithadhoc** [comment]
- No duplicate rules found. [\[Monitoring\] Copy Prometheus ruleset for EC2s to Datadog](https://app.zenhub.com/workspaces/platform-tech-team-2-633efe4ca5a428e5294d7ade/issues/gh/department-of-veterans-affairs/va.gov-team/51144) has been created for re-creating these rules in Datadog.

**Comment by rsmithadhoc** [comment]
TODO:
- Scan other rulesets for EC2 rules. Example: https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/prometheus/rules/revproxy.rules#L1
- File descriptors monitors (open files) should remain, added to follow-up issue.
- Entrophy - might be a custom monitor that we want to check on.

**Comment by rsmithadhoc** [comment]
TODO:
- Scan other rulesets for EC2 rules. Example: https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/prometheus/rules/revproxy.rules#L1
- File descriptors monitors (open files) should remain, added to follow-up issue.
- Entrophy - might be a custom monitor that we want to check on.

**Comment by rsmithadhoc** [comment]
TODO:
- Scan other rulesets for EC2 rules. Example: https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/prometheus/rules/revproxy.rules#L1
- File descriptors monitors (open files) should remain, added to follow-up issue.
- Entrophy - might be a custom monitor that we want to check on.

**Comment by rsmithadhoc** [comment]
TODO:
- Scan other rulesets for EC2 rules. Example: https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/prometheus/rules/revproxy.rules#L1
- File descriptors monitors (open files) should remain, added to follow-up issue.
- Entrophy - might be a custom monitor that we want to check on.

**Comment by rsmithadhoc** [comment]
- PR updates: [Remove duplicate EC2 rules that are in Datadog](https://github.com/department-of-veterans-affairs/devops/pull/12410).
    - TODO: EC2 monitors in other files
    - Linked to a monitor to cover the file descriptors per [Slack thread](https://adhoc.slack.com/archives/C044WM9PBMY/p1674753101392279).
- Entropy monitors - I didn't find much information on this other than it being [added](). I also don't see that metric in Datadog, so I created a (TODO) follow-up issue to look into adding it + a monitor.

**Comment by jhouse-solvd** [comment]
This issue is nearly complete. Ryan made some great iterations based on team feedback. This issue can be closed once the team has had an opportunity to review and verify AC.

**Comment by jhouse-solvd** [comment]
We're hoping to review Ryan's change on Thursday or Friday. Once that's done, this issue can be closed.

**Comment by ph-One** [comment]
Reached out to @olivereri to provide transparency in what we are doing. Our EC2 monitors do not currently cover CMS. Historically CMS has managed the `cms.rules` file. This could change in the future but would involve conversations that should not hold up this work. We can continue forward without the `cms.rules` file being included.

**Comment by ph-One** [comment]
Made requested changes and merged. Closing.
