### ISSUE TITLE
[Monitoring] De-duplicate the Prometheus ruleset for RDS (for monitors setup in Datadog)

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#50821]
## Description 
Duplicate monitors lead to extra noise and confusion. As monitors are being set up in Datadog, rulesets in Prometheus should be removed to avoid duplicate information sources for platform operators. 

## Technical notes 
- Prometheus rulesets can be found [here](https://github.com/department-of-veterans-affairs/devops/tree/master/ansible/deployment/config/prometheus/rules)
- An example PR can be found [here](https://github.com/department-of-veterans-affairs/devops/pull/12351/files)

## Acceptance Criteria 
- [x] Rules have been evaluated for deduplication 
- [x] Rules have been removed for components and services that have corresponding monitors in Datadog 
- [x] There is a link to the replacement monitor(s) in the PR comments
- [x] A follow-up issue has been created to capture anything missing from Datadog that exists in Prometheus

**Comment by rsmithadhoc** [comment]
https://github.com/department-of-veterans-affairs/devops/pull/12375

**Comment by jhouse-solvd** [comment]
We reviewed this as a team and verified that the AC has been met. 

This issue can be closed.

**Comment by jhouse-solvd** [comment]
re-opening to ensure PRs are merged

**Comment by jhouse-solvd** [comment]
PR verified as merged by @rsmithadhoc. These changes will go out on Friday when Prometheus is deployed. 

Closing.
