### ISSUE TITLE
[Monitoring] De-duplicate the Prometheus ruleset for the Reverse Proxy (for monitors setup in Datadog)

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#50822]
## Description 
Duplicate monitors lead to extra noise and confusion. As monitors are being set up in Datadog, rulesets in Prometheus should be removed to avoid duplicate information sources for platform operators. 

## Technical notes 
- Prometheus rulesets can be found [here](https://github.com/department-of-veterans-affairs/devops/tree/master/ansible/deployment/config/prometheus/rules)
- An example PR can be found [here](https://github.com/department-of-veterans-affairs/devops/pull/12351/files)

## Acceptance Criteria 
- [x] Rules have been evaluated for deduplication 
- [x] Rules have been removed for components and services that have corresponding monitors in Datadog 
- [x] There is a link to the replacement monitor(s) in the PR comments
- [x] A follow-up issue has been created to capture anything missing from Datadog that exists in Prometheus

**Comment by rsmithadhoc** [comment]
- [PR to remove duplicate monitor.](https://github.com/department-of-veterans-affairs/devops/pull/12448)
- [New issue created](https://github.com/department-of-veterans-affairs/va.gov-team/issues/52097) to assess/re-create the missing monitors in Datadog.

**Comment by rsmithadhoc** [comment]
Reviewed this as a team and the PR has been merged, closing this issue. This will go out with the next scheduled Prometheus deploy.
