### ISSUE TITLE
Upgrade GIDs RDS to latest patch release.

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#5082]
## User Story or Problem Statement
As a member of VSP, I need to update my DBs with the VA so I can stay compliant.

## Goal
_Update DB instances for vets-api_

## Acceptance Criteria
- [ ] _Upgrade is done and tested_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by tskinn** [comment]
Dev and staging are done. Going to do production on Saturday night.

**Comment by tskinn** [comment]
Prod was done over the weekend.
