### ISSUE TITLE
Analytics Implementation for: New Home Page

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#50835]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

</div>
</details>

### Required
- **Is this request for **Google Analytics implementation** or **QA**?**

     - [x] Google Analytics implementation
     - [ ] QA

- **Who is this request for?**

    - Public Websites
    
    
- **Provide the link(s) for Google Analytics implementation or QA**
  
    - www.va.gov/new-home-page
    
- **When is the launch date?**
    - Jan 3, 2023

- **What interactions need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked_
    
    - We have implemented code to track all interactions within the new home page (ie., between the header and the footer). **However, GTM needs to be configured to send these to GA.**
    - The elements of the new home page that were instrumented with GA events were detailed in this ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11467. They were made in [this PR](https://github.com/department-of-veterans-affairs/content-build/pull/1380/files).
    - e.g.:
      - `recordEvent({ event: 'homepage-search-tools-click', action: 'Other search tools - {{link.label}}' })`

### Optional
- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - N/A

- **Any additional comments**

    - Overall, our intention is to make it easy to find these analytics events in GA.
    - Note: Ideally, all the uniqueness would be visible in either "event action" or "event label" in GA, so that we don't have to waste a secondary dimension on finding the events we're interested in. So for the example above, it would be nice to have this complete Event Label in GA:
      - `recordEvent({ Homepage - Other search tools - Link click - {{link.label}}`

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by michelle-dooley** [comment]
@wesrowe - I will begin working on this as part of the new sprint starting tomorrow.  Could you please provide me a list of all the new homepage events?  I see the following...

homepage-search-tools-click, 
homepage-benefit-link-click, 
homepage-create-account and
homepage-popular-link-click.  

Are there others I should be looking for?  And are these unique to the new homepage?  So if I see one of these I know its new homepage vs old, correct?

**Comment by michelle-dooley** [comment]
@wesrowe - can you also tell me what event category they should each fall under?  Interaction, navigation, api call, sign-on, search or transaction.  I think I can determine but want to make sure I put them where you expect to see them from category perspective.

**Comment by wesrowe** [comment]
Thanks @michelle-dooley! Answers to your questions below.

Category: I believe these should all be Interactions. Email sign-up is a possible exception – I would be happy with Interaction there as well, but if there's a standard that it's a "transaction" or something I'll follow that.

### The ones you found already:
- homepage-search-tools-click
- homepage-benefit-link-click
- homepage-create-account 
- homepage-popular-link-click

_Hopefully these will come through with an "action" that includes detail of particular item, e.g. the link text itself._

### Additional ones:

**VA News promo links**
Article title:
event: "homepage-news-promo-title-click",
action: "Homepage News Promo - Pathfinder: The front door for engaging with VA - Title"

Read full article CTA:
event: "homepage-news-promo-click",
action: "Homepage news promo - Pathfinder: The front door for engaging with VA - CTA"

More VA News:
event: "homepage-news-promo-more-news-click",
action: "Homepage news promo - More VA News"

**Email sign-ups (bottom of page)**
event: "homepage-email-sign-up",
action: "Homepage email sign up"

**Comment by michelle-dooley** [comment]
@wesrowe - I created these new events in GTM but when going through to test I don't see any of them triggering.  Have they  not been implemented yet?

**Comment by wesrowe** [comment]
Thanks for the update. They have been implemented – I believe I pulled the details in my comment above from AdSwerve. What steps did you try testing?

**Comment by michelle-dooley** [comment]
@wesrowe - so something must be missing in the code.  The only new homepage event I see at all is 'homepage-benefit-link-click'.  Can you please confirm that other events are coded same as this one?  I can't figure out why only one is coming through?  I have tried everything and from my side they are all set up the exact same?!?!

![image](https://user-images.githubusercontent.com/93597659/216123252-589a31a0-3496-4be2-8ec2-6db868be8821.png) 

![image](https://user-images.githubusercontent.com/93597659/216123769-32018bb6-57da-411e-b5f7-497438cd5e27.png)

**Comment by wesrowe** [comment]
I need to pull in @jtmst (Josh Mills), he has been in the GA code a lot lately and can get into the technical weeds about how GTM makes the connection.

**Comment by michelle-dooley** [comment]
@jtmst and @wesrowe  - I went through and everything is working as expected now expect the 'Search' type in I only see the standard search action for that (not specific to new homepage) and 'Read the full article' I do not see homepage-news-promo-click just the standard Nav Zone One interactions.  Here is a [doc](https://docs.google.com/document/d/1V355D0WBbxAjodqVAyyg6a77kMMKJoscbTTOr-GTIW8/edit) that shows you everything I see for each new event action

**Comment by wesrowe** [comment]
@michelle-dooley, @jtmst, I'm not seeing anything at all in prod or staging for the News Promo Title or Read Full Article clicks. (Not even "zone one", which I have seen work in the past.)
<img width="588" alt="image" src="https://user-images.githubusercontent.com/4054752/217896873-f858ecb3-d3b9-4e25-b994-9f06680ff514.png">

**Comment by michelle-dooley** [comment]
@wesrowe - I have not released the new homepage to staging or prod yet, there are still in dev in GA and only I can see them.  I wanted to confirm it was all working before promoting.  However you should still see any zone one or previous events, I did not take anything away.

**Comment by jtmst** [comment]
@wesrowe I'm testing this on prod and it seems fine to me, this is for the Read Full Article:

**Comment by michelle-dooley** [comment]
I did release them to dev, staging and prod so you should seem them in all places now.

**Comment by michelle-dooley** [comment]
@wesrowe I just went through them all in staging and they are all working.

**Comment by wesrowe** [comment]
@jtmst, it turns out that I'm experiencing a bug in AdSwerve just on the News Promo links: the "Read full article" GA event doesn't show in console when I click the links. However, when I hit the back button to return from the external site to the new home page, the original event I was expecting appears back where I was expecting it.

Josh, would you mind seeing if you can reproduce? I can only see this bug on the news promo links (all three). All other new-homepate links trigger events without having to hit Back. Is there anything different about how these events are triggered?

First clicked:
<img width="596" alt="image" src="https://user-images.githubusercontent.com/4054752/218210250-05e3c02d-ae46-4d6a-ae8a-9b1830ca1e1c.png">

Same console area after going Back to new home page:
<img width="594" alt="image" src="https://user-images.githubusercontent.com/4054752/218210385-dd8d4548-e37e-4648-9eaa-4e0949f4a8b2.png">

**Comment by wesrowe** [comment]
@michelle-dooley, thanks for your work on GTM.

**Comment by jtmst** [comment]
@wesrowe I find console events to be inconsistent when going back and forth between pages like this, so usually I'll test links but just cmd+clicking so they open in a new tab and I can see the events firing in real time

**Comment by wesrowe** [comment]
@jtmst, thanks for that tip! – it 1) really simplifies the view, and 2) bypassed the bug I was seeing earlier.

**Comment by michelle-dooley** [comment]
@wesrowe sounds like you have everything you need now.  I am going to close this ticket.  Please reach out with any further questions.
