### ISSUE TITLE
[Content styleguide] Content doesn't align with VA.gov voice and tone content principles. (05.04.1)

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#50840]
#### VFS team name
Sitewide Content

#### VFS product name
VALife Static Page

#### Point of Contact/Reviewers
Cheryl Evans - @CherylEvans - Content

*For more information on how to interpret this ticket, please refer to the [Anatomy of a Staging Review issue ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Anatomy-of-a-Staging-Review-Issue-ticket.2060320997.html) guidance on Platform Website.

---

### Platform Issue
Content doesn't align with VA.gov voice and tone content principles.

### Issue Details
"Eligibility for VALife" is not written as a question.  Verbiage for eligibility is typically written as a question in production.  [Example](https://www.va.gov/health-care/eligibility/)

### VA.gov Experience Standard
[Category Number 05, Issue Number 04](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

### Platform Recommendation
Given the production example, I recommend writing "Am I eligible for VALife?" as opposed to "Eligibility for VALife".

---

### VFS Guidance

- Close the ticket when the issue has been resolved or validated by your Product Owner
- If your team has additional questions or needs Platform help validating the issue, please comment on the ticket
- Some feedback provided may be out of scope for your iteration of the product, however, Platform's OCTO leadership has stated that all identified issues need to be documented and it is still your responsibility to resolve the issue.
- If you do not believe that this Staging Review issue ticket is the responsibility of your team, comment below providing an explanation and who you believe is responsible. Please tag the Point of Contact/Reviewers. Governance team will research and will follow up.

**Comment by laurwill** [comment]
Thanks for flagging! Just confirming that this is an intentional shift from the previous question header style — we'll make sure to get this documented for future reviews of these static pages.
