### ISSUE TITLE
Review and test health checks

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#50867]
**PROBLEM STATEMENT**
We will review and test each health check to ensure we can properly access each health check (these are not working right now and is a large issue).

[List](https://vfs.atlassian.net/wiki/spaces/TT1/pages/2456813569/Health+Check+Discovery) of health check paths and subsequent testing.

**Comment by considerable** [comment]
Here is how to see the current tests running:
https://vagov.ddog-gov.com/synthetics/tests?query=tag%3A%28%22team%3ATT1%22%29

**Comment by considerable** [comment]
![synthetic_tests_vets-api.png](https://images.zenhubusercontent.com/616758e4c5e87dce2146cdcf/1e733827-89dc-462b-9f4c-cc469f3ee555)
