### ISSUE TITLE
[FE] Change VA sign in content in pre check in

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#50875]
## Description 

There is a "how can I updated my information" accordion in pre check in that's shown on the completion page and error pages. There's content in there that needs a small change. 

Here is the accordion in reference (this is the production content): https://share.goabstract.com/4f416207-0fd1-4b05-8ba5-21b6e688e75a?collectionLayerId=b0042c3c-121a-4f44-88b8-2623f54473dd&mode=design&sha=latest

The content that needs to change is, "VA account." It should change to, "VA.gov profile." 

For example, here is the use of "VA.gov profile" on a page that's not within My VA. 

Reason we're doing it is to be consistent across VA apps. [Slack thread](https://dsva.slack.com/archives/C0NGDDXME/p1671040098539439)

## Task

- [ ] Update in pre check in 

## AC

- [ ] Verified in production

**Comment by acrollet** [comment]
@loripusey @benbrasso-agile6 our usual practice for content changes is to create a new key in the English file and not add it to es/tl until we've received the new translation. This feels like a change small enough that people will be better served by seeing the old translation than the whole sentence in English. Should we show the old translation and create a follow-on issue to update those files when we get the new translation, or just follow the usual process?

**Comment by loripusey** [comment]
I'm ok with this approach, I'll have to make a note of the change in our github page to track it

**Comment by acrollet** [comment]
PR is here: https://github.com/department-of-veterans-affairs/vets-website/pull/23016

**Comment by acrollet** [comment]
I've created a PR for this work. The text is changed in three places:

## On the confirmation page after answering "no" to all three questions

### Without phone appointments

![Pre-check-in--confirmation-answer-no-to-all.png](https://images.zenhubusercontent.com/5f6b95e44ede53b783cfcc8e/8714af01-d8e3-40aa-9543-9916c11ae0e4)![Pre-check-in--confirmation-answer-no-to-all-spanish.png](https://images.zenhubusercontent.com/5f6b95e44ede53b783cfcc8e/67212d9d-190f-4fbf-b1c4-718ba49afe4b)
![Pre-check-in--confirmation-answer-no-to-all-tagalog.png](https://images.zenhubusercontent.com/5f6b95e44ede53b783cfcc8e/8185964c-b1e1-4328-913e-2ad8411085a9)

### With phone appointments

![Pre-check-in--phone-appt-confirmation-answer-no-to-all.png](https://images.zenhubusercontent.com/5f6b95e44ede53b783cfcc8e/38c36fc9-eef6-4409-a48f-6d7b1454efd7)
![Pre-check-in--phone-appt-confirmation-answer-no-to-all-spanish.png](https://images.zenhubusercontent.com/5f6b95e44ede53b783cfcc8e/bfaa4e00-f256-4f97-a871-2e8246e9ba96)
![Pre-check-in--phone-appt-confirmation-answer-no-to-all-tagalog.png](https://images.zenhubusercontent.com/5f6b95e44ede53b783cfcc8e/f40ca1a5-1988-4d5d-8fe6-2abca1d5d099)

## Canceled appointment error page

![Pre-check-in--canceled-error.png](https://images.zenhubusercontent.com/5f6b95e44ede53b783cfcc8e/3feca17e-c83a-4339-9b21-063b65eb9d44)
![Pre-check-in--canceled-error-spanish.png](https://images.zenhubusercontent.com/5f6b95e44ede53b783cfcc8e/4a5c4b6e-d65d-4770-ad39-548c94d05267)
![Pre-check-in--canceled-error-tagalog.png](https://images.zenhubusercontent.com/5f6b95e44ede53b783cfcc8e/554e2e67-84f2-43c2-b24f-fc6d391ace24)

**Comment by acrollet** [comment]
This change has been merged.
