### ISSUE TITLE
Content work on Native American and Alaska Native copay waivers

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#50878]
## Issue Description

Danielle created a new R&S article about Native American copay waivers based off a provided fact sheet. We need to do a copyedit, get final SME approval, and publish the page.

Preview link: http://preview-prod.vfs.va.gov/preview?nodeId=52082

## Tasks
- [x] Copyedit (Megan)
- [x] Send to SMEs (Danielle)
- [x] Copyedit (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] New R&S article is live on the site

**Comment by RLHecht** [comment]
Update: This is currently with SMEs awaiting final approval and will be going live in February.

**Comment by RLHecht** [comment]
@katherine-fung Here are the docs we were discussing on our call today that we need to compare against our preview link to see if there's any informational changes we'll need to make:

[https://app.zenhub.com/files/133843125/af952825-6a17-452a-85b7-e69975151fd5/download](https://app.zenhub.com/files/133843125/af952825-6a17-452a-85b7-e69975151fd5/download)

[https://app.zenhub.com/files/133843125/7bb622dd-abc1-41b2-b864-1fcccd177847/download](https://app.zenhub.com/files/133843125/7bb622dd-abc1-41b2-b864-1fcccd177847/download)

**Comment by katherine-fung** [comment]
Hi @DanielleThierryUSDSVA, 

I went through the Drupal page and the Word docs.  I've attached a Word doc with notes about the differences between the Drupal page and the Word docs. I wanted to check with you that these are changes we should make before I make. i.e. are any of the acceptable documents listed in the Word docs which don't appear to be on the Drupal page actually the same ones but just called something else? 

[https://app.zenhub.com/files/133843125/d9f475dd-bf22-44c9-b4a2-1e4c6f9e68f9/download](https://app.zenhub.com/files/133843125/d9f475dd-bf22-44c9-b4a2-1e4c6f9e68f9/download)

**Comment by DanielleThierryUSDSVA** [comment]
Hi, @katherine-fung! I answered your Qs in the doc. Thanks so much for doing this! Could we update the page today and send back to the SMEs? Randi is on that email thread and can loop you in to provide the updated preview link. Thanks!

[Copay waivers changes_dt.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/11028575/Copay.waivers.changes_dt.docx)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht and @katherine-fung. Checking in to make sure we get this page updated and changes over to VHA today. For the URL, they had previously requested a short URL for adding to print statements and press releases. I had recommended (and they had agreed) to direct people to our copay rates page and to add an alert there that links to the R&S content. You can share the preview of the rates page with them so they can check out the alert: http://preview-prod.vfs.va.gov/preview?nodeId=703

**Comment by RLHecht** [comment]
Update: I sent this to VHA today.

**Comment by RLHecht** [comment]
@megzehn This is ready for you to copyedit but we are holding to publish until Monday morning. There is still a placeholder for the form, but you can review everything else.

**Comment by megzehn** [comment]
Confirming that I copy edited the rest of this page and removed the Note about 3 urgent care visits, per Randi

**Comment by RLHecht** [comment]
This work is now live. Closing.
