### ISSUE TITLE
Update the Mockdata Repo for "View Dependents"

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#5088]
## Goal
When testing (both backend and frontend), we need to have the mockdata available for "View Dependents" so we can see that the data is going through to the frontend.  We are using the BGS "findDependentsByPtcpntId" endpoint for "View Dependents".

## Considerations
See comment below for an example

## Tasks
- [x] Update the mockdata repo (`vets-api-mockdata`) with placeholder data for testing.

## Acceptance Criteria
- [x] A PR has been submitted to the `vets-api-mockdata` repo

**Comment by kathleencrawford** [comment]
PR submitted and code samples can be found here:

https://github.com/department-of-veterans-affairs/vets-api-mockdata/pull/113
