### ISSUE TITLE
Fix broken links on About COVID-19 pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#50881]
## Issue Description

We got a Siteimprove report of a broken line on the [About COVID-19 vaccines](https://www.va.gov/health-care/covid-19-vaccine/about-covid-19-vaccine/) pages.

Under the H2 Why to get a COVID-19 vaccine, the link for "Learn more about long-term COVID-19 effects on the CDC website" is no longer working. 

The new link should be: https://www.cdc.gov/coronavirus/2019-ncov/long-term-effects/index.html

We need to make this update on the English and Tagalog pages.

## Tasks
- [x] Fix broken link
- [x] Copyedit (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] Links no longer broken on live site

**Comment by RLHecht** [comment]
@megzehn I fixed these broken links on the English and Tagalog pages. These are ready for you to copyedit and publish. Thanks!

**Comment by megzehn** [comment]
Thank you, @RLHecht! Confirming that I reviewed and published these 2 pages.

**Comment by RLHecht** [comment]
This is live. Closing
