### ISSUE TITLE
[FE] My VA Audit UX Improvements: Update copy under Applications in Progress for LOA1 Users

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#50904]
## Background
While doing internal testing we found that the copy under the Applications in Progress for LOA1 users who do not have any applications in progress is wrong. According to the [sketch files](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/529RArL) and [FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/documentation/LOA1-state-FE-documentation.md) the copy should read "You have no applications in progress." currently it says "You have no saved applications to show."

## Tasks
- [x] Update copy under the Applications in Progress section for LOA1 users who do not have an application in progress
- [x] Validate

## Acceptance Criteria
- [x] The copy and design for LOA1 users matches the design documentation

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)? Any team member_
- _How can this work be validated?_ Log in with a LOA1 staging user and validate that the copy has been corrected

**Comment by Samara-Strauss** [comment]
Can move to sprint 2 or 3 depending on when Allison is able to start this.

**Comment by ajakabcin** [comment]
Confirmed on staging with my personal LOA1 account
![image](https://user-images.githubusercontent.com/45603961/213224594-5f0ad9bc-cd75-4a17-8618-54dbb4a46620.png)

**Comment by adamwhitlock1** [comment]
Thanks for validating this! I will make make a note to make sure to ping you on these once they make it to staging as well.

**Comment by ajakabcin** [comment]
No problem @adamwhitlock1 ! thanks again for helping us out with this
