### ISSUE TITLE
Discovery: Information on control families?

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#50902]
**PROBLEM STATEMENT**
1. We need an understanding of what control families we currently have in place?
2. And HOW this does or does NOT play into zero trust? 
3. What can we improve with control families that makes system more zero trust _compliant_?

[Document all information in this RFC document.](https://vfs.atlassian.net/wiki/spaces/TT1/pages/2471919617/RFC+Template)

**Comment by laineymajor** [comment]
Per Igor: Going to work on this week as time permits.

**Comment by laineymajor** [comment]
@laineymajor to start an RFC and place in confluence... send to Igor.

**Comment by laineymajor** [comment]
Igor to include detail in the RFC document. Work on diagram. Highlight any specific questions or cross-cutting areas of security work.

**Comment by laineymajor** [comment]
@considerable have you had a chance to look at the RFC template? I would like our team to have an internal review of preliminary information on Wednesday.

**Comment by considerable** [comment]
@laineymajor - I followed the template to produce this draft:
[va.gov-platform-architecture/rfc/2023/2023-01-03 - PEP will migrate from App Pod into Traefik Ingress.md](https://github.com/department-of-veterans-affairs/va.gov-platform-architecture/blob/tt1-zta-identity-aware-proxy-pep/rfc/2023/2023-01-03%20-%20PEP%20will%20migrate%20from%20App%20Pod%20into%20Traefik%20Ingress.md)
I treated "control families" as a synonym to "policy enforcement points" in the named doc.

**Comment by considerable** [comment]
People who contributed to this [Network-Request-Topology](https://vfs.atlassian.net/wiki/spaces/OT/pages/2231304195/Platform+Infrastructure+Diagrams#Network-Request-Topology) diagram in confluence, might be an excellent cohort to further review of controls/PEPs outside of our team.

**Comment by laineymajor** [comment]
@considerable 

Notes from RFC review:
- Narrow the focus of the document to _only EKS_
- Review the document with Kyle Matheny and Kyle Crockett
- Make updates to document per meetings with Kyle and Kyle

**Comment by laineymajor** [comment]
Igor setup meeting with Joe Niquette to discuss SSO. Working on simplifying the diagrams after the meeting with Joe.
