### ISSUE TITLE
AWS access for Alex Taxer

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#50906]
### COR Name

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Alex Taker

### Your Email

alex.taker@adhocteam.us

### Team, Role, and Company of the target individual

Platform Tech Team 2

### Product Manager (PM) name and email

Jesse House - jesse.house@adhocteam.us

### Product Owner (PO) name and email

Mike Chelen - michael.chelen@va.gov 

### Desired AWS Access

Platform Frontend Engineer 

### Access Expiration

ongoing

### Additional Notes

COR is Ray Wang

Ongoing access is requested as Alex is a Platform team engineer. 

### User must exist in a roster before AWS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [x] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by jhouse-solvd** [comment]
cc: @ataker and @ph-One for tracking

**Comment by BillChapmanUSDS** [comment]
Reaching out for EQUIP Dates

**Comment by BillChapmanUSDS** [comment]
Approved for ["dsva-vagov-developers",  "lighthouse-developers","force-MFA"]

**Comment by little-oddball** [comment]
@npeterson54 @pjholyoke - Looks like this was approved a week ago and can be moved through the process and get Alex the access he needs.  Thanks!

**Comment by mynar7** [comment]
@little-oddball Alex has had the approved teams added to his AWS account. @ataker please verify you have the requested access.
