### ISSUE TITLE
GIBCT: Count queries need to be optimized

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#5091]
There are errors occurring in production due to COUNT queries taking too long. These queries need to be optimized to reduce these errors.

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/553

**Comment by dmccurdybah** [comment]
Can be tested on gibct-data-service branch `bah-institution-cleanup`

**Comment by delli-gatti-michael** [comment]
local testing complete

**Comment by dmccurdybah** [comment]
Db migration PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/557

**Comment by delli-gatti-michael** [comment]
Changes have been merged resulting in reduced latency. Closing this issue

<img width="808" alt="Screen Shot 2020-02-07 at 2 02 50 PM" src="https://user-images.githubusercontent.com/45575003/74149650-415e3900-4bd6-11ea-926c-bb6b2dd09a5c.png">
