### ISSUE TITLE
Staging Review - QA Feedback - My Education Benefits, Education Benefits Authenticated Transfer Application (22-1990e)

### ISSUE THREAD

**Issue by it-harrison** [department-of-veterans-affairs/va.gov-team#50938]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

feedback for #50828

## Thoughts/questions
-

## Feedback
- Practice areas will document their feedback following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback).

**Must:**

**Should:**
* add E2E and test coverage artifacts
* it is possible to enter an alphanumeric bank account number and save without seeing an error, e.g. `abcd` or `abc123`
* problem showing error states on the bank account information page when user navigates to previous page after seeing initial error message then returns to bank account screen the errors are gone

<img width="570" alt="Screen Shot 2022-12-20 at 10 35 58 AM" src="https://user-images.githubusercontent.com/8867779/208705571-5b2b140e-3581-48d2-b6c2-11780966d217.png">

<img width="600" alt="Screen Shot 2022-12-20 at 10 40 44 AM" src="https://user-images.githubusercontent.com/8867779/208706587-3225c203-8f3f-4f2b-8b7b-70512556c394.png">
**Consider:**

## Platform directions

- Remove the governance-team label
- Update "Issue Title"
- Link to collab cycle Request epic
- Add your feedback
- Remove the CC-Request label (only if you created the ticket using the New Issue link from the Collaboration Cycle Reviews board)
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review QA Only**: VFS PM, yourself (optional)

**Comment by btruongafs** [comment]
Alphanumeric bank account numbers are acceptable

Field validation error messages will display when the users attempts to save to progress to the next step.
