### ISSUE TITLE
[Copy] Profile 2.0: Update copy for Profile 2.0

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#5093]
## User Story

As a user, I need to be able to easily find and manage my personal information.

## Tasks

(Note to Tressa: We'll go through the screens together to figure out exactly what copy needs to be updated and what doesn't. This will determine the task list.)

- [ ] 

## Acceptance Criteria

- [ ] All copy has been updated and approved by the content team.

**Comment by Samara-Strauss** [comment]
Is this ticket still being used? Or is there a different epic?

**Comment by mshea0606** [comment]
@Samara-Strauss  I closed this ticket out since we already have the other copy tickets broken out by screen.
