### ISSUE TITLE
Onboarding Derrick Ellerbie

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#50940]
## Background

Welcome! We can use this ticket to track onboarding to the authenticated experience team.

### Intro to Authenticated Experience team members

Please schedule a short chat with each of these folks. You can schedule individual chats or talk to people in groups if you think that makes sense:

- [x] Berni Xiong (Delivery Manager/Scrum Master)
- [ ] ~Samara Strauss (Auth experience product owner, interim Profile Product Manager)~ Slack might be the best way to go at this time until she returns.
- [ ] AJ (My VA Product Manager)
- [ ] Angela Agosto, Florence McCafferty & Liz Lantz (Designers/Researchers)
- [x] Adam Whitlock, Allison Lu (Frontend developers)
- [x] Tom Harrison (Backend developer)

### Review documentation

The Authenticated Experience team is currently organized into two product teams: My VA (dashboard), and Profile (section). Here are some helpful documents to review. It would also help if you log into staging (more info at the bottom of this ticket) and check it out for yourself to get a sense of these products.

**MY VA**
- [x] [My VA product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va)
- [x] [My VA roadmap](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/authenticated-experience/roadmap/my-va-roadmap.md)

**PROFILE**

### Current projects
_The general structure of our documentation is that we keep an overarching product outline and then individual project outlines within for initiatives or versions/phases of work on those larger products. Here are the projects we currently have going on the My VA team._

**MY VA**
- [x] [My VA Audit Improvements](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/2022-audit)
- [x] [Payment Information V2](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/payment-history)
- [x] [Onsite Notifications](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/onsite-notifications)

### Additional resource documentation

**MY VA**
- [My VA use case documentation](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/use-cases) (WIP)
- [Onsite notifications use case documentation](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/onsite-notifications/use-cases#onsite-notifications-use-cases)

**PROFILE**
- [x] [Profile product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/README.md)
- [ ] [2023 goals and roadmap](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/authenticated-experience/roadmap/2023-goals-roadmap.md#profile-team)
- [ ] [Personalization and profile comparative analysis](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/discovery-research/comparative-analysis/personalization-profile-comparative-analytsis.pdf)

#### Profile products

- [ ] [Personal information product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/personal-information#readme)
- [ ] [Contact information product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/contact-information#readme)
- [ ] [Military information](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/military-information#readme)
- [ ] [Direct deposit product outline](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/direct-deposit/README.md)
- [ ] [Notification preferences product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/notifications/notification-preferences#readme)
- [ ] [Account security](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/account-security#readme)
- [ ] [Connected apps](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/connected-apps/README.md)

### Log into staging 
**PROFILE**
You can use the following info to get into staging:

Go to VA.gov.
- You can sign into staging with most ([staging users](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv)) to view the profile. Feel free to pick any user, but if you want a specific user, try user 81. **Please do not edit or update their profile, however**.
- Once you are logged in click the menu that has the user's name in the upper right of the navigation. You'll see a link to the profile in the menu.

**MY VA**
You can use the following info to get into staging:
1. Go to Staging.va.gov. and click sign in (upper right corner)
2. Select the ID.me option
3. Enter credentials for staging user 36 (Staging user info can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv) in the sensitive repo. Note that the user number refers to the number in the test user email, not the row number of the table.)
4. Click sign in
5. Accept terms
6. Click continue until you're signed in and automatically redirected to My VA

### Optional demos

**PROFILE**
- [ ] If it would be helpful, one of the profile team members can walk you through how each feature works.

**MY VA**
- [ ] If it would be helpful, one of the My VA team members can walk you through how each feature works

**Comment by Samara-Strauss** [comment]
Updates for Berni:

- Add My VA and Onsite notifications product outlines
- Combine team meetings by community of practice (eg. design). You don't have to divide by portfolio (My VA and Profile).

**Comment by BerniXiongA6** [comment]
FYI: Derrick's GitHub handle is: dellerbie

**Comment by BerniXiongA6** [comment]
Hey @Samara-Strauss I've submitted the Slack request for Derrick Ellerbie [in this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/53773)

**Comment by Samara-Strauss** [comment]
Thanks, @BerniXiongA6! [This is the request for github access](https://github.com/department-of-veterans-affairs/github-user-requests/issues/14643).

**Comment by BerniXiongA6** [comment]
This is Derrick's [Platform Orientation ticket ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54060) to be added to VFS team roster and for access to GitHub repos.

**Comment by BerniXiongA6** [comment]
Hi @dellerbie -- given that you'll be starting some My VA tickets for Sprint 5, don't feel pressured to take too deep a dive into the Profile product info above. Knowing where to find this information and bookmarking it for learning a little at a time is A-OK to do! Feel free to close this ticket when you're done with most of the items that you can get to (know you can always come back later to review anything again). Thank you!
