### ISSUE TITLE
[PM] Onboarding - Travis Cahill

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#50955]
## Background

Welcome Travis! We can use this ticket to track your onboarding activities to the Authenticated Experience team.

### Intro to Authenticated Experience team members

Please schedule a short chat with each of these folks. You can schedule individual chats or talk to people in groups if you think that makes sense:

- [x] Samara Strauss (Auth experience product owner and lead)
- [x] Chante Lantos-Swett (interim Product Lead backfilling Samara - from OCTO) 
- [x] Florence McCafferty, Liz Lantz, and Angela Agosto (Researchers/Designers)
- [x] Adam Whitlock, and Allison Lu (Frontend developers)
- [x] Tom Harrison, and Derrick Ellerbie (Backend/Full stack developers)

### Review documentation

Here are some helpful documents to review on the profile. It would also help if you log into staging and check it out for yourself to get a sense of the full section.

- [x] [Profile product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/README.md)
- [x] [2023 goals and roadmap](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/authenticated-experience/roadmap/2023-goals-roadmap.md#profile-team)
- [x] [Profile Zenhub board](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/board?labels=profile)
- [x] [Personalization and profile comparative analysis](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/discovery-research/comparative-analysis/personalization-profile-comparative-analytsis.pdf)

#### Profile products
Here  are the product outlines for each of the 7 Profile products. There's a lot to consume and it may take some time to get acclimated to each product. Bookmark these and come back often as you dive deeper into to each product. 

- [x] [Personal information product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/personal-information#readme)
- [x] [Contact information product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/contact-information#readme)
- [x] [Military information](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/military-information#readme)
- [x] [Direct deposit product outline](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/direct-deposit/README.md)
- [x] [Notification preferences product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/notification-preferences#readme)
- [x] [Account security](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/account-security#readme)
- [x] [Connected apps](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/connected-apps/README.md)

### Attend live demos for all Profile products

- [x] BX will create individual tickets to for team members to schedule and conduct a demo on each section of the Profile 
- [x] Attended all 7 Profile demos given by team members: 
    - [x] #55475 
    - [x] #55476 
    - [x] #55477 
    - [x] #55478 
    - [x] #55479 
    - [x] #55480 
    - [x] #55482

### Log into staging and check out the profile
You can use the following info to get into staging:

Go to VA.gov.
- You can sign into staging with most ([staging users](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv)) to view the profile. Feel free to pick any user, but if you want a specific user, try user 81. **Please do not edit or update their profile, however**.
- Once you are logged in click the menu that has the user's name in the upper right of the navigation. You'll see a link to the profile in the menu.

### Gain Access to Platform Tools 
- [x] GA
- [x] SOCKS access  [SOCKS access for Travis Cahill#59567](https://github.com/department-of-veterans-affairs/va.gov-team/issues/59567)
- [ ] Sentry > in process getting socks access first via
- [x] Domo ([slack guidance from Samara](https://dsva.slack.com/archives/C909ZG2BB/p1680009526002999?thread_ts=1680009082.595749&cid=C909ZG2BB))
- [x] get production access (find or document steps)
- [x] get flipper access (find or [document steps](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/))

### Accessibility Orientation Homework
- [x] Review the [VA.gov experience standards](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/va-gov-experience-standards) on Platform website
- [x] Join [#accessibility-help](https://dsva.slack.com/archives/C8E985R32) on DSVA Slack
- [x] Join [#inclusive-research](https://dsva.slack.com/archives/C033ZS9E7EW) on DSVA Slack
- [x] Read [ARIA is Spackle, not Rebar](https://css-tricks.com/aria-spackle-not-rebar/) by Eric Bailey
- [x] Try a screen reader! [Getting started with VoiceOver](https://accessibility.huit.harvard.edu/voiceover) / [Getting started with NVDA](https://accessibility.huit.harvard.edu/nvda)
- [x] Read [Prepare for an accessibility staging review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review) on Platform website
- [x] Review the [accessibility testing artifact](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=briandeconinck&labels=a11y-testing&template=a11y-testing.yaml&title=Accessibility+Testing+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D) on GitHub
- [x] [Install axe DevTools](https://www.deque.com/axe/browser-extensions/) in your browser

**Comment by BerniXiongA6** [comment]
Note for week of April 3rd, when new Matthew Travis Cahill officially starts. @BerniXiongA6 will help onboard new Profile PM. When we know his A6 email and GH handle, Berni will reach out to @Samara-Strauss or @clantosswett to help request user access to VA organization on GH. After receiving access to VA org on GH, Berni will assist him with DSVA Slack request, Platform orientation ticket, GH repo access, and ZH board access.

**Comment by Samara-Strauss** [comment]
Thanks for this, Berni! If I'm not here at that point, Chante can request GH access.

**Comment by BerniXiongA6** [comment]
FYI: Travis' GH handle is: mtcA6

**Comment by Samara-Strauss** [comment]
Thank you! What is his email address? I need that for the Github access request.

**Comment by BerniXiongA6** [comment]
I've [submitted the request for access to DSVA Slack](https://github.com/department-of-veterans-affairs/va.gov-team/issues/56178), which might take a few days as I'll need to help Travis with completing some initial Platform requirements.

**Comment by Samara-Strauss** [comment]
We should be all set on Github access!

**Comment by BerniXiongA6** [comment]
Travis has created his Platform Orientation Ticket [#56315](https://github.com/department-of-veterans-affairs/va.gov-team/issues/56315) and will complete tasks as instructed.

**Comment by mtcA6** [comment]
Scheduled meetings w some of the team members, at some point today I'll send the meetings for those I didn't schedule yet for next week
