### ISSUE TITLE
[Design] Onboarding Florence McCafferty

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#50956]
## Background

Welcome! We can use this ticket to track onboarding to the authenticated experience team.

### Intro to team members

Please schedule a short chat with each of these folks. You can schedule individual chats or talk to people in groups if you think that makes sense:

- [x] Samara Strauss (Auth experience product owner)
- [ ] (New PM)
- [x] Liz Lantz (Designer)
- [x] Adam Whitlock (Frontend developer)
- [x] Tom Harrison (Backend developer)

### Review documentation

Here are some helpful documents to review on the profile. It would also help if you log into staging and check it out for yourself to get a sense of the full section.

- [x] [Profile product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/README.md)
- [x] [2023 goals and roadmap](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/authenticated-experience/roadmap/2023-goals-roadmap.md#profile-team)
- [x] [Personalization and profile comparative analysis](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/discovery-research/comparative-analysis/personalization-profile-comparative-analytsis.pdf)

#### Profile products

- [x] [Personal information product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/personal-information#readme)
- [x] [Contact information product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/contact-information#readme)
- [x] [Military information](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/military-information#readme)
- [x] [Direct deposit product outline](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/direct-deposit/README.md)
- [x] [Notification preferences product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/notifications/notification-preferences#readme)
- [x] [Account security](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/account-security#readme)
- [x] [Connected apps](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/connected-apps/README.md)

### Log into staging and check out the profile
You can use the following info to get into staging:

Go to VA.gov.
- You can sign into staging with most ([staging users](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv)) to view the profile. Feel free to pick any user, but if you want a specific user, try user 81. **Please do not edit or update their profile, however**.
- Once you are logged in click the menu that has the user's name in the upper right of the navigation. You'll see a link to the profile in the menu.

### Optional -- profile demo

- [x] If it would be helpful, one of the profile team members can walk you through how each feature works.

**Comment by fmccaf1** [comment]
@Samara-Strauss I'm starting on this ticket. It looks like I can't assign myself at this point, so could you do that for me?

**Comment by Samara-Strauss** [comment]
Done! You've been assigned :D
