### ISSUE TITLE
Value argument for Radio Button component 

### ISSUE THREAD

**Issue by maxx1128** [department-of-veterans-affairs/va.gov-team#50959]
To learn more about contributing to the Design System or requesting new components, requesting changes to existing components, and reporting bugs, go here.
https://design.va.gov/about/contributing-to-the-design-system/

---
# Bug Report or Design System update

The [Radio Button component](https://design.va.gov/storybook/?path=/docs/components-va-radio--default) doesn't have an argument for passing in values. This means radios will look empty even if a form has a default value or one that has been filled in ahead of time.

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

While using the radio components for the new Discharge wizard form, completing the form and then going back to the page showed all the radios empty even though the values were all there in the "review your answers" section. This creates a confusing user experience with conflicting messages on if the form has been finished.

## What I expected to happen

The radio inputs retain their values since the page remembered all the answers.

**Comment by jamigibbs** [comment]
@maxx1128 The `va-radio-option` component has a `value` property. Does that help you resolve this?

![Screenshot 2022-12-20 at 1 36 11 PM](https://user-images.githubusercontent.com/872479/208751822-2f57a0ec-757e-4e0f-b0fa-42caa03a3143.png)

**Comment by maxx1128** [comment]
@jamigibbs It doesn't help in this case, but from that I did see that the `checked` parameter is what's needed to fix this issue. Just confirmed that it now works locally! 🎉  We can probably close this ticket.
