### ISSUE TITLE
Accounts table data pull

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#50954]
### Produce a report which provides the following data as known by va.gov:
1. A total count of user accounts for each login method.
2. A count of users with multiple accounts (MHV, ID.me, DS Logon, or Login.gov) 
3. Count of identities using a DS Login account to access VA applications, and no linked ID.me, or Login.gov account. This is checking if they already have a verified idme or login.gov account that is associated with a given dslogon account.
4. Count of identities with a MHV Premium account and no linked ID.me, DS Logon, or Login.gov account.  (This will help corroborate the number of accounts eligible for migration from MHV.  Expecting this number to be lower than the count we received of total users who have done MHV in-person proofing: 243,613.)
5. Counts of identities with a MHV Premium account and a linked ID.me account.  Same for DS Logon and Login.gov. 
6. Total MHV accounts without an email address.

- how many dslogon users do we need to help create either a login.gov or idme account
  - all user verifications with dslogon, list of user accounts that are verified that are associated with that dslogon. Then do a reverse query of all the accounts that dont have more than one user account
- how many mhv users do we need to help create either a login.gov or idme account

#### Additional Tasks:
- [ ] Draft potential solutions to create a dashboard for this in datadog.

**Comment by bosawt** [comment]
@joeniquette Have we satisfied all the requirements for this ticket? I think I posted this information here: https://app.zenhub.com/workspaces/identity-5f5bab705a94c9001ba33734/issues/gh/department-of-veterans-affairs/va.gov-team/52757
