### ISSUE TITLE
GIDS: Filter additional facilities from the Crosswalk Dashboard

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#5095]
As an GIDS user, I need additional facilities filtered from the crosswalk dashboard that do not meet the criterion to be displayed in the Comparison Tool so that I do not perform unnecessary maintenance activities.

## Assumptions:
1. N/A

## Acceptance Criteria
1. Facilities in the WEAMS file that do not have a "POO Status" of "Approved" are excluded from the dashboard.
2. Facilities in the WEAMS file that have one of the following "Applicable Law Codes" are excluded from the dashboard:
     - blank
     - educational institution is not approved
     - educational institution is approved for chapter 31 only

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/549

**Comment by dmccurdybah** [comment]
Can be tested on gibct-data-service branch `bah-crosswalk-fix`

**Comment by delli-gatti-michael** [comment]
Local Testing complete

**Comment by delli-gatti-michael** [comment]
Functionality is now present in Staging. Closing this issue
