### ISSUE TITLE
[DM] Onboarding Berni Xiong

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#50964]
## Background

Welcome! We can use this ticket to track onboarding to the authenticated experience team.

### Intro to team members

Please schedule a short chat with each of these folks. You can schedule individual chats or talk to people in groups if you think that makes sense:

- [x] Samara Strauss (Auth experience product owner)
- [x] AJ (My VA PM) and (New Profile PM)
- [x] Angela Agosto, Liz Lantz, and (New Profile designer) (Designers)
- [x] Adam Whitlock and (new FE devs) (Frontend developer)
- [x] Tom Harrison (Backend developer)

### Review documentation

Here are some helpful documents to review on the profile. It would also help if you log into staging and check it out for yourself to get a sense of the full section.

- [x] [My VA product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va#readme)
- [x] [Onsite notifications](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/onsite-notifications#readme)
- [x] [Profile product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/README.md)
- [x] [2023 goals and roadmap](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/authenticated-experience/roadmap/2023-goals-roadmap.md#profile-team)
- [x] [Personalization and profile comparative analysis](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/discovery-research/comparative-analysis/personalization-profile-comparative-analytsis.pdf)

#### Profile products

- [x] [Personal information product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/personal-information#readme)
- [x] [Contact information product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/contact-information#readme)
- [x] [Military information](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/military-information#readme)
- [x] [Direct deposit product outline](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/direct-deposit/README.md)
- [ ] [Notification preferences product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/notifications/notification-preferences#readme)
- [x] [Account security](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/account-security#readme)
- [x] [Connected apps](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/connected-apps/README.md)

### Log into staging and check out the My VA and the profile

You can use the following info to get into staging:
1. Go to Staging.va.gov. and click sign in (upper right corner)
2. Select the ID.me option
3. You can sign into staging with most (staging users found [here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv). Feel free to pick any user, but if you want a specific user, try user 81. Note that the number corresponds to the number in the test user email address not the row in the table. **Please do not edit or update their profile, however**.)
4. Click sign in
5. Accept terms
6. Click continue until you're signed in
7. Once you are logged in click the menu that has the user's name in the upper right of the navigation. You'll see a link to My VA and the profile in the menu.

### Optional -- demos

- [x] If it would be helpful, one of the My VA team members and one of the profile team members can walk you through how each product works.

**Comment by Samara-Strauss** [comment]
@ajakabcin heads-up that this ticket exists for the new delivery manager. I have them onboarding to both teams, but we can talk about if we want to ease them in similarly to how we did with Erica. Let me know if you have any thoughts.

**Comment by BerniXiongA6** [comment]
Not sure whether you wanted me to assign myself yet, this is Berni Xiong (Agile Six) the new delivery manager. Happy to get started!

**Comment by Samara-Strauss** [comment]
@BerniXiongA6 great! I'm glad you're able to view the ticket. I just assigned it to you. You might be able to get started on things that are viewable in our public repo, but you won't be able to view credentials for signing into staging yet. No pressure, though. We can wait until you more officially have access to things if that's easier.

**Comment by BerniXiongA6** [comment]
FYI:  Notification preferences product outline link is broken -- I get a 404 error. But I've either reviewed or printed off to continue reviewing all the other checklist items! Thanks for this great orientation! cc: @Samara-Strauss

**Comment by Samara-Strauss** [comment]
Sounds great! And sorry about the broken notification preferences link. I've fixed it.
