### ISSUE TITLE
DUPLICATE - Research and Document How Pre-fill works from the backend

### ISSUE THREAD

**Issue by charleystran** [department-of-veterans-affairs/va.gov-team#50963]
Research and document what is needed from the backend to support prefilling of forms

**Comment by charleystran** [comment]
The documentation I had hoped to create on this already exists here 
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/engineering/prefill_setup.md

This document covers both front and backend.

**Comment by charleystran** [comment]
I was unable to fully verify the above documentation due to not being able to log into vets-website locally. That issue appears to be  more global that just my setup. https://dsva.slack.com/archives/CSFV4QTKN/p1672256514596369. However following the code, everything looks to checkout and would work if implemented. I was able to round up a few resources on which test users to use however.

**Comment by tbaker1026** [comment]
Duplicate of #49700
