### ISSUE TITLE
Design & Research Orientation - January 2023

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#50967]
## Issue Description
Hosted the Design & Research Orientation Session for VA.gov Platform on 1/9/2023

---
## Tasks
- [x] Host the session and answer any questions that come up.

## Acceptance Criteria
- [x] We have provided a Design & Research Orientation session for VA.gov Platform for January 2023.

**Comment by allison0034** [comment]
Completed
