### ISSUE TITLE
RadioButton does not allow formatting of the label

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-team#50977]
To learn more about contributing to the Design System or requesting new components, requesting changes to existing components, and reporting bugs, go here.
https://design.va.gov/about/contributing-to-the-design-system/

---
# Bug Report or Design System update

- [X] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened
While using the RadioButton component, it's not possible to modify the styling of the component label. (The question itself.)

This arose in context of converting from React component to RadioButton DS component, within context of a wizard. Wizards are deprecated and should be converted to sub-tasks, however: that's a roadmap / prioritization issue with POs. So until work can be prioritized, we must use new component within wizards. 

The label of RadioButton component is non-bold standard text. Our team is not able to override / display text as bold, as styling of the RadioButton component is all "wormholed" within the DS component.

## What I expected to happen

Not sure, to be honest. @maxx1128 may be able to add notes re: what would simplify this for an FE eng adopting the component.

## Additional Context
Discussion with Natalie Hill and Sarah Koomson about this issue / options to mitigate: https://dsva.slack.com/archives/C0NGDDXME/p1671471252709569

**Comment by jilladams** [comment]
@caw310 can you clarify if this issue is resolved by the `label-header-level` property? https://design.va.gov/storybook/?path=/docs/components-va-radio--label-header

**Comment by jamigibbs** [comment]
Hi @jilladams . Can your team use the "Label Header" prop `label-header-level` to accomplish what you need to do? https://design.va.gov/storybook/?path=/docs/components-va-radio--label-header

**Comment by Andrew565** [comment]
> this issue is resolved by the `label-header-level` property? https://design.va.gov/storybook/?path=/docs/components-va-radio--label-header

Yes, you can use the label-header-level to create a bolder label.

**Comment by maxx1128** [comment]
It looks like `label-header-level` lets the component turn the label into a header, but I don't think this will resolve the issue. Adjusting the heading levels just to make text larger or bolder would mess with the headings structure and make it harder for screen reader users to navigate the page via headings. The ideal would be that the label could also include different tags such as `<strong>` and `<br />`. That way only parts of the text could be formatted if needed without changing the page's semantics.

**Comment by jamigibbs** [comment]
@maxx1128 If you use the header prop Andrew mentioned, you should be able to style it with the [part attribute](https://developer.mozilla.org/en-US/docs/Web/CSS/::part) it includes. So you would use the correct header tag and style accordingly to your design needs. Something like this:

```
va-radio::part(header) {
  /* Styles to apply to the `header` part */
}
```

https://github.com/department-of-veterans-affairs/component-library/blob/main/packages/web-components/src/components/va-radio/va-radio.tsx#L263

**Comment by maxx1128** [comment]
@jamigibbs That would help with the styling, but using a header tag there could still create issues if there shouldn't be a header there. Screen readers will see the label as a header marking off an entirely new section instead of just a radio label, which would make navigating the page (and even potentially reading the radio label) confusing and difficult.

**Comment by jamigibbs** [comment]
I'm not sure that I understand why you would need to add custom style the label but if you are specifically just looking for just a style override of the top text for the radio options, then you can use the same CSS part method described above (it's actually a `legend` though):

```
va-radio::part(legend) {
  /* Styles to apply to the `legend` part */
}
```

If this isn't what you're looking to do either, can you share a screenshot of the design you're trying to implement?

<img width="522" alt="Screenshot 2023-02-22 at 3 58 59 PM" src="https://user-images.githubusercontent.com/872479/220769320-8b2243a0-60f2-47ab-b4f0-901f011f130a.png">

**Comment by maxx1128** [comment]
My assumption was that custom formatting of the label would need to include bolding the entire text, bolding portions of it, and adding line breaks. If the custom formatting only includes making the entire text bold or not bold, then the CSS solution you mentioned would be enough. I'm sorry if I jumped to conclusions there, someone more on the design side may need to clarify what they need.

**Comment by Andrew565** [comment]
@jilladams or @maxx1128 Is this still an issue or can we close this ticket?

**Comment by jilladams** [comment]
Assigning to @eselkin to reproduce and update here if still an issue.

**Comment by jilladams** [comment]
Closing. If we have a case for needing to style portions of a label in future, we'll raise it. We also know the design system team has a project underway to make it possible to get the H1 out of the shadow DOM for accessibility reasons, and this may get fixed in the course of that.
