### ISSUE TITLE
T3 #07196991 - Veteran cannot update email and phone in HLR

### ISSUE THREAD

**Issue by jaredcunha** [department-of-veterans-affairs/va.gov-team#50982]
## Description

**Salesforce Ticket ID:** 
07196991 from 3/21/22

**Issue Veteran is experiencing:**

Veteran trying to submit HLR with email and phone fields saying they need to be updated (but when doing so attempts to leave the site) on Step 1 of 4. Veteran states that it will not let him add that formation for the last 2 days no matter how many times they try to update.

**Comment by sortizsh** [comment]
@jaredcunha  can you grab a URL and screenshot so we can address this?

**Comment by jaredcunha** [comment]
@sortizsh We were not provided a screenshot or URL. It's an issue with Higher Lever Review, which belongs to squad 2.

**Comment by Mottie** [comment]
Weird, HLR is using the profile components. I just tested it in staging and did not encounter any issues. I wonder if the Veteran has tried updating their contact info within the profile page (https://www.va.gov/profile/contact-information) and also encountered problems?

**Comment by sortizsh** [comment]
I"ll ask!

**Comment by jaredcunha** [comment]
Saw in Slack that @Kimberley2019 would go back and ask
