### ISSUE TITLE
Community Care Request Flow - Best Times to Contact (Remove)

### ISSUE THREAD

**Issue by JRRoof** [department-of-veterans-affairs/va.gov-team#50990]
## Description
The VA Request workflow has already been modified to remove the "best times for us to call you" section.  The same now needs to be done for the CC Request workflow.

---

## Acceptance Criteria

Given the user is in the CC request flow 
When the user is on the Contact Information page
Then the user will no longer see the option to select best times to contact
And page matches [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/request-cc.md#contact-information)

Given the user is in the CC request flow 
When the user is on the Review Details page
Then the user will no longer see the option to select best times to contact 
And page matches [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/request-cc.md#review-appointment-details)

Given the user is in the CC request flow 
When the user is on the Pending Confirmation page
Then the user will no longer see the option to select best times to contact 
And page matches [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/appointment-details.md#cc-request---confirmed)

Given the user is in the Pending list
When the user clicks on details for their pending appointment 
Then the user will no longer see the best times to contact 
And page matches [copy doc for pending appointment](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/appointment-details.md#cc-request---pending)
And page matches [copy doc for canceled pending appointment](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/appointment-details.md#cc-request---canceled)

### Design Assets
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdExTIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2add20b79227ce2c2a3dfdee278d99c7623c9d44/CC%20-%20Contact%20Information.png)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by shiragoodman** [comment]
@ldelacosta could I ask that label` CC-Request `be removed from this ticket? That is the label we use for all Collaboration Cycle Requests and it is a filter for our [Collaboration Cycle Reviews zh board. ](https://app.zenhub.com/workspaces/collaboration-cycle-reviews-61d89e9e5f4c120011a0ad37/board) Please let me know if you'd like help creating a new label.

**Comment by ldelacosta** [comment]
@shiragoodman - Sorry, I accidentally selected it. Thanks!

**Comment by ldelacosta** [comment]
Will add to the Ready queue when we have removed the feature toggles for V2/Acheron in production.

**Comment by ldelacosta** [comment]
No longer need a feature toggle `va_online_scheduling_request_flow_update` for this ticket cc: @JRRoof @simiadebowale

**Comment by ldelacosta** [comment]
@young1205 - please have the UX team validate this ticket when it's ready cc: @JRRoof @outerpress

**Comment by simiadebowale** [comment]
@outerpress - can you clarify the last AC about 'the Pending list'. We don't show this text in the req/pending appt details page

**Comment by outerpress** [comment]
@simiadebowale copy docs are updated, let me know if I missed any

**Comment by JRRoof** [comment]
We need to hold up on this change.  Community Care was unaware of the change and has some questions/concerns.

**Comment by young1205** [comment]
The somewhat completed Github PR of this work is https://github.com/department-of-veterans-affairs/vets-website/pull/26046

**Comment by ldelacosta** [comment]
@simiadebowale - tagging you in this ticket since Julia is no longer with the team. We will need to talk with the business and determine the next steps.

**Comment by outerpress** [comment]
@ldelacosta I rolled back these changes in the [copy docs](https://github.com/department-of-veterans-affairs/va.gov-team/commit/af94531bc95b812679073fae626ebe907b07e112) and [design file](https://www.figma.com/file/ewxCGm9dkvYt5wiNXMwvkL/Request-flow-content-update-%7C-Appointments-FE?type=design&node-id=619-20525&mode=design&t=UT6U1pPgNlICijFT-4). Let me know if anything else is needed.
