### ISSUE TITLE
[BUG]: VEText OSM scheduling in clinics that have been closed

### ISSUE THREAD

**Issue by manalo-soco** [department-of-veterans-affairs/va.gov-team#50998]
### Description 
From station 740, Daniel Rojas:

_So if the clinic is active OSM will send message for open active slots. We use leaf system for clinic cancellations and was notified clinics in OSM need to be deactivated. In VETEXT . Can the clinic in vetext stay active if clinic for those days are canceled prior , and OSM will only pick up the next available active timeslots and bypass the days that are canceled by clinic?_

Support team believes the appointments may have been manually canceled due to a clinic closure, but that clinic closure does not set any sort of closure flag within OSM. This causes OSM to pick up the canceled appointment slots for reschedule as these slots are not closed, they have been canceled. 

VEText may need to set a form of closed/canceled flag for clinic closure/OSM automation.

![image.png](https://images.zenhubusercontent.com/5e9f8d3341903e43c029c13e/c97e82aa-ac3a-4301-be3c-ec74e388c142)

### Acceptance Criteria
- [ ] Bug resolved 
- [ ] Communicate with impacted users (close loop if necessary)
- [ ] Remove announcement/banner from Support App 
- [ ] Remove announcement/banner from SharePoint

**Comment by manalo-soco** [comment]
@robertdurkin  Is this something that is feasible for VEText? 
cc @chancetheoriginal @jwowk

**Comment by lindsay-insco** [comment]
@manalo-soco to follow-up due to recent updates to OSM

**Comment by lindsay-insco** [comment]
@manalo-soco - to update

**Comment by manalo-soco** [comment]
This has been fixed from last batch update
