### ISSUE TITLE
Adjust both Puma threads and databse pool size to allow an instance to be fully utilized

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#5100]
## User Story or Problem Statement
Puma threads and database pool size should be adjusted to get more hardware utilization out of an instance before an auto-scaling event.

## Goal
Reduce necessary instances to improve cost efficiency and promote proper auto-scaling.

## Objectives or Key Results this is meant to further
- _lorem ipsum_

## Acceptance Criteria
- [ ] Higher hardware utilization on instances

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by johnpaulashenfelter** [comment]
We've done a bunch of PRs to get here in the devops repo. Current status is that both staging and production are running 6 workers with 8 threads each, which is 3x the original 0:16 configuration for number of threads.
