### ISSUE TITLE
[User flows and navigating] Static content pages and entry points (including CTAs) aren't updated to support a tool or feature launch. (03.07.1)

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#51010]
#### VFS team name
DGIB - My Education Benefits

#### VFS product name
Authenticated 22-1990e Transfer of Entitlement (TOE) Form Updates

#### Point of Contact/Reviewers
Sara Sterkenburg - @sterkenburgsara - IA

*For more information on how to interpret this ticket, please refer to the [Anatomy of a Staging Review issue ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Anatomy-of-a-Staging-Review-Issue-ticket.2060320997.html) guidance on Platform Website.

---

### Platform Issue
Static content pages and entry points (including CTAs) aren't updated to support a tool or feature launch.

### Issue Details
The breadcrumbs and URL indicate that the new form is a child of the "survivor and dependent benefits" page/section of the site. However, this page does not include an entry point to this form (it does include a link "learn about transferred benefits" that routes the user to the GI Bill Page, which then provides a link to the old version of the 22-1990e form). The new form that is part of this review is not there and can only be found by surfacing a button within the form wizard on the "how to apply" page. 

### VA.gov Experience Standard
[Category Number 03, Issue Number 07](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

### Other References
[WCAG SC 3.2.4 AA](https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=246#consistent-identification)

### Platform Recommendation
Your team should coordinate with sitewide content & IA regarding the publication of new static Drupal pages that were a part of your sitewide content & IA ticket. Those pages will correctly situate the new 22-1990e form in the correct location according to established content hierarchy (URLs, breadcrumbs). Until there is an entry point within the correct navigation, this should not go to launch.

---

### VFS Guidance

- Close the ticket when the issue has been resolved or validated by your Product Owner
- If your team has additional questions or needs Platform help validating the issue, please comment on the ticket
- Some feedback provided may be out of scope for your iteration of the product, however, Platform's OCTO leadership has stated that all identified issues need to be documented and it is still your responsibility to resolve the issue.
- If you do not believe that this Staging Review issue ticket is the responsibility of your team, comment below providing an explanation and who you believe is responsible. Please tag the Point of Contact/Reviewers. Governance team will research and will follow up.

**Comment by sterkenburgsara** [comment]
FYSA @shiragoodman @mnorthuis

**Comment by btruongafs** [comment]
@RLHecht @bethpotts @katherine-fung I believe this work has been completed and now tracking for deployment with https://github.com/department-of-veterans-affairs/va.gov-team/issues/50830. Can you confirm if there's anything else to do or can we close out?

**Comment by RLHecht** [comment]
You're correct @btruongafs We can close this out.
