### ISSUE TITLE
Adding Kristina Dela Cruz to DSVA Slack

### ISSUE THREAD

**Issue by robbie1226** [department-of-veterans-affairs/va.gov-team#51037]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

Requesting to add Maria.Kristina.Dela.Cruz@ecstech.com as a full member to DSVA Slack. She is supporting the Digital Health Platform (DHP) team.

Please add to the channels
#digital-health-platform-public
#digital-health-platform-team

**Comment by eunicegar** [comment]
Hi can you clarify if this member is a full member or guest? If guest, then I can add to channels. If not, I can add as a full member and team can take care od adding to all the channels needed.

**Comment by robbie1226** [comment]
Please add Kristina as a full member. I'm happy to add her to our Slack channels once that's done. Thanks!!

**Comment by eunicegar** [comment]
done
