### ISSUE TITLE
Draft journey maps for awareness content

### ISSUE THREAD

**Issue by elizabethkochBT** [department-of-veterans-affairs/va.gov-team#51048]
## Issue Description
- Develop user journey maps to show how Veterans will learn about Login.gov (the focus is on awareness content specifically) on VA.gov, MHV, eBen or other touchpoints.
- Maps should show the various ways users enter the VA.gov ecosystem.

---

**Comment by tygindraux** [comment]
Carl and I met to discuss this ticket. This has been enveloped in other tickets. I'm closing this issue.
