### ISSUE TITLE
Access for Kevin Mircovich

### ISSUE THREAD

**Issue by kevinmirc** [department-of-veterans-affairs/va.gov-team#5106]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your name.
   > Kevin Mircovich
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > **My Team**: VSA Caregivers Team, **My Role**: Backend Engineer, **My Employer**: GovernmentCIO
- What is the **public** SSH key?

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCuJKoQHc4+/bC3km/j8O694z0OPCDwcm01pQ9PWvS4J/Z5HN44uK1svnBd1wLlDsQDY+d0TNQmH0f2m1+a+kHJ+sXGYZSk/Vu58JWpJcl3bUJ5lb2TUyIm34LaXNGcCMWgUjj/h452naQxfnrI8M85qPC559qnvgcrJy4Z3SzI8bgmE1Nwk73IFKITeK9Em3mq+P/4OIxxEnZaJRaOtyxFWny24kI3vnv94qrpoKsFz9rBybqzxe88nWgBIVQDKBFrMS9tvJTpgsWh6b9j2JC6mEBY72rJ80ZjPtwfjoeJTieHcOaZ3xZ/9RQ/kSiFCMmDvP4Z5+xvSMc5sJXBYfFH kevinmircovich@New-MacBook-Pro.local
```

- Grant AWS Console access?
  > YES (but not required)
  >  **Please give a brief description for why you are requesting AWS access**: To view logs from the staging environment of the vets-api in order to better debug and troubleshoot issues.

**Comment by kevinmirc** [comment]
pinging @department-of-veterans-affairs/vsp-operations .

**Comment by ricetj** [comment]
@Jeff-Hayter (still using the old way)
COR: Mary O'Toole
User: Kevin Mircovich

**Comment by kevinmirc** [comment]
Hi, @Jeff-Hayter & @ricetj, Any update on the status of this?

**Comment by Jeff-Hayter** [comment]
Hi @kevinmirc last I checked no onboarding paperwork had been uploaded for you.  You should touch base with your company to make sure they've submitted all of your security paperwork.

**Comment by kevinmirc** [comment]
Hi @Jeff-Hayter. Thank you. GCIO is still submitting the paperwork. Will reopen when it's submitted.

**Comment by kevinmirc** [comment]
Hi @Jeff-Hayter, The VA should have received my paperwork at this point. Can we revisit granting me SOCKS access? Thank you!

**Comment by kevinmirc** [comment]
Also, as an update: I will need AWS access in order to set credstash variables. AWS Access is not needed immediately, though.

**Comment by nathanhruby** [comment]
You can chat with folks in #vsp-operations in slack to help you get values into credstash

**Comment by kevinmirc** [comment]
Thanks, @nathanhruby. I'll do that instead.

**Comment by kevinmirc** [comment]
Hi @Jeff-Hayter, I wanted to follow up on this. Any update on getting me SOCKS access?

**Comment by jbritt1** [comment]
@kevinmirc, I can get you set up with SOCKS access momentarily.

**Comment by jbritt1** [comment]
SOCKS access granted. @kevinmirc please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.

AWS access will still require approval from @Jeff-Hayter once your E-QIP has been submitted / received on the other end.

**Comment by kevinmirc** [comment]
Hi @jbritt1, can you please the config to use this new public key instead:
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCz0Ofd5gH+pKMqfsuc2CxJEe1rEA1xF56rMwj96VhLSBrYvkRo7zku3sKpJWTQVvsme9quteQTQLPpxg5QIPNFEXmEtD1RR98rYaJGJT8JMAWCmcTPyy4DeU+mKOUY606d4re6ojnMcJALX7AYXn2ty98txgM4U1Li0G1hTX1UC8yraanbYq+GPk24YdwjXU6wsgrZF/wKR1845hB7IOUyiq/rajNdGRs4Iu1meedE78zMnNYzLrFomI8QUm1TypL+3K6Pw/+RmnZcZXrAWANVX8p2zdRt730fkIwhAIkyaKy0Z7aHLIfEeyw1dcUNjgBZ6Sj9VZCRrP3zWBaxQeFZ kevinmircovich@Kevin-Mircovich-MacBook-Pro.local
```

Thank you!

**Comment by jbritt1** [comment]
On it.

**Comment by jbritt1** [comment]
New key updated / deployed. Let me know if you run into any issues.

**Comment by kevinmirc** [comment]
Thanks @jbritt1, I'm connected.

**Comment by ricetj** [comment]
Doesn't need AWS right now. if that changes we can open another request down the road.

**Comment by kevinmirc** [comment]
Hi All, Wanted to reopen this issue to see if I can get access to AWS.

**Comment by Jeff-Hayter** [comment]
@jbritt1 @ricetj Approved for AWS.

**Comment by tskinn** [comment]
A user for Kevin has been created in AWS and his credentials have been provided to him.

**Comment by kevinmirc** [comment]
Thanks all! I'm in AWS. Could you please add a role to view logs?

**Comment by kevinmirc** [comment]
Hi @department-of-veterans-affairs/vsp-operations,

I'm hoping to expand the scope of my AWS access to allow me to detach ec2 instances and ssh to them.

Right now the only way to view vets-api's prod sidekiq dashboard is to access an instance, boot up sidekik, and forward the port (https://dsva.slack.com/archives/CBU0KDSB1/p1607983142281200) to view it locally.

Please let me know if this is possible. Thanks!

**Comment by jhouse-solvd** [comment]
@kevinmirc - quick question - I see the comment on August 28 requesting the role to view logs? Did you ever get that? If not, do you still need it? 

also, I'm following up with the ops team regarding your request from Dec16. 

we will follow up through this ticket in the very near future. thank you for your patience! :)

**Comment by kevinmirc** [comment]
Hi @jhouse-solvd, I did receive access to logs, thanks for following up on that. Thanks for the update.

**Comment by jhouse-solvd** [comment]
@kevinmirc - just following up here: 

1. I see the comment on August 28 requesting the role to view logs? Did you ever get that? If not, do you still need it?

2. regarding Sidekiq dashboard, would there be another solution for viewing the Sideqkiq web ui that doesn't required elevated privileges? Taking an EC2 instance out of an ASG for this purpose isn't a recommended practice from the VSP Ops perspective, due to security and operational implications. 

It might be good for you and I to check this out in real-time together, so let me know if there is some time this week to take a quick peak. feel free to send me a message via Slack.

**Comment by kevinmirc** [comment]
Hi @jhouse-solvd,

1. Yes, I did receive access to logs.
2. I am not aware of any alternatives for accessing sidekiq in production. I agree accessing sidekiq this way is a terrible solution, but that seems to be the only way to access it at this time. I've created a ticket to track these issues here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/17806

I'll ping you on slack and we can dive into this some more. Thank you!

**Comment by jsev-io** [comment]
@kevinmirc @jhouse-solvd 
Can we close this ticket at this time? This issue seems to now be less permissions and more an exploration into process alternatives.

**Comment by kevinmirc** [comment]
Closing since an alternative solution for accessing sidekiq is in the works: https://github.com/department-of-veterans-affairs/va.gov-team/issues/17806

**Comment by kevinmirc** [comment]
Reopening since an immediate solution for viewing Sidekiq Jobs in production will not be completed any time soon and this is blocking vsa-caregivers from deploying a new feature.

Would like to request access to the production autoscale group to view Sidekiq using the [current process](https://dsva.slack.com/archives/CBU0KDSB1/p1607983142281200).

**Comment by kevinmirc** [comment]
Closing be-tools was able to view the dashboard as we released the new feature.
