### ISSUE TITLE
Develop communication strategy with VEO, MHV, and eBen

### ISSUE THREAD

**Issue by elizabethkochBT** [department-of-veterans-affairs/va.gov-team#51080]
### Problem Statement

The Login.gov Adoption team does not have a communication strategy in place for legacy CSP migrations and DS Logon sunset.

### Initiative: 
Develop communication strategy with VEO, MHV, and eBen
- Straw-man Conceptual
- Review initial Communication suggestions paths

Creating a customized plan with each team to identify messaging, timelines, and anticipated outcomes proactively helps all team members prepare for deployment.
Communicating the anticipated changes (the 5 W’s) and the benefits to consumers and Veterans, will demonstrate transparency and collaboration amongst the community.

### Acceptance Criteria:
- [ ] A clear communications strategy is developed.
- [ ] VEO, MHV, and eBen have reviewed and provided feedback on the strategy.

**Comment by tygindraux** [comment]
@elizabethkochBT – Let's discuss this and journey maps ticket today. I think we can consolidate and this ticket might be the epic.

**Comment by tygindraux** [comment]
Where can I find the 'initial communication suggestion paths' to review?

**Comment by tygindraux** [comment]
Carl and I met to refine this ticket. We have split this into two separate tickets. I'm closing this issue.
