### ISSUE TITLE
Wilkes-Barre Planning [PLACEHOLDER]

### ISSUE THREAD

**Issue by sarahknoppA6** [department-of-veterans-affairs/va.gov-team#51110]
1 meeting & 1 email

## Tasks
- Meet with Mark
    - Who do we test with (WB, Bay Pines?)
    - What timeframe?
    - Create f/u tickets

**Comment by benbrasso-agile6** [comment]
Met with Mark. [Related slack thread of to-do's](https://dsva.slack.com/archives/C022AC2STBM/p1683577699167849).

**Comment by benbrasso-agile6** [comment]
Sent email to wilkes-barre. @loripusey we want to close this?
