### ISSUE TITLE
Add ClinicIEN to Power BI Report

### ISSUE THREAD

**Issue by jwowk** [department-of-veterans-affairs/va.gov-team#51117]

**Comment by jwowk** [comment]
@Cmjones233 please add ClinicIEN to this appt dashboard https://app.powerbigov.us/groups/me/apps/edb20dd9-adff-4cdb-9e08-35ecc7e2ea94/reports/bf6248a7-ae15-49f3-893b-73b65f38a7fd/ReportSectionf09450dc35eef3baa8a5?ctid=e95f1b23-abaf-45ee-821d-b7ab251ab3bf

**Comment by Cmjones233** [comment]
completed
