### ISSUE TITLE
[02/07/22] UX Research for Clinic Cancellations

### ISSUE THREAD

**Issue by jwowk** [department-of-veterans-affairs/va.gov-team#51125]
## Description 
**Additional information to follow**

- Reach out to clinics using clinic cancellations and ask some general UX questions

#Acceptance Criteria
- [x] Review results and analyze
- [x] Document findings
- [x] Review with team

**Comment by ahicksfearless** [comment]
Drafted up questions on 01/19/23 to send to existing Clinic Cancellation Users. Sent to Justin for review. Awaiting approval.

**Comment by ahicksfearless** [comment]
Closed today 01/27/23. Reviewing results.

**Comment by lindsay-insco** [comment]
@ahicksfearless closed survey with 9 responses out of 36. Summary in progress

**Comment by ahicksfearless** [comment]
Reviewed summary with team 01/06/23.
