### ISSUE TITLE
Meet with team building Supplemental Claims form to see if there is anything we can learn

### ISSUE THREAD

**Issue by tbaker1026** [department-of-veterans-affairs/va.gov-team#51129]
### **Description**
The goal is to better understand how forms have been digitized in the past, and your experience with that process. My hope is that by the end of this hour together we'll have an understanding of:
- Who does what in terms of digitizing forms get a high-level overview of the process or processes, 
- Learn from your past experience of digitizing forms – what worked, and what didn’t work and what could be improved

### **Definition of Done**

- [x] Meet with Supplemental Claims Team
- [x] Synthesize Meeting information

### **Supporting Documentation**
[Document of Questions](https://docs.google.com/document/d/1j0QMBGxD19AyYjhCqQBzahfyiUNNB7_wfhjSOlGiccA/edit#heading=h.tomli58cii9p)

[Research Plan](https://docs.google.com/document/d/1nSLflJEUbmg_Jl72n6sqMvOdRkTjPjKWyhYKizLfPzA/edit?usp=sharing)

[Meeting Notes](https://docs.google.com/document/d/1qebACsREkS12l3U7Y_dbLI0JOFixzNeX5ajj_KhjUn8/edit)

**Comment by jeana-adhoc** [comment]
[Final Meeting notes](https://docs.google.com/document/d/1qebACsREkS12l3U7Y_dbLI0JOFixzNeX5ajj_KhjUn8/edit?usp=sharing)
