### ISSUE TITLE
[Due on 1/29] Pittsburgh VAMC Robots.txt File Update 

### ISSUE THREAD

**Issue by jefflbrauer** [department-of-veterans-affairs/va.gov-team#5113]
User Story
A a user of VA.gov, I now recognize va.gov/pittsburgh-health-care as the official website for VA Pittsburgh Health Care, because pittsburgh.va.gov is now redirected there. 

Goal
The entire pittsburgh.va.gov subdomain is hidden from google search and /pittsburgh-health-care is now exposed to google search.

Acceptance Criteria
When a user visits google.com
And enters search terms for "VA Pittsburgh" or similar terms
Then the user sees new results to va.gov/pittsburgh-health-care 
And the user does not see any links to pittsburgh.va.gov

Definition of Done
-Attached to a Milestone (1/29)
-Labeled with Team (CMS team support)
-Labeled with Practice Area (public websites)

Labeled with Type (request)

**Comment by kelsonic** [comment]
Current search results in Google:
![image](https://user-images.githubusercontent.com/12773166/73077011-88c99300-3e7c-11ea-8481-459e60745799.png)

**Comment by ncksllvn** [comment]
@kelsonic  looks like the robots.txt addition was doing its job then! This was intentionally excluded form search results.

**Comment by MickinSahni** [comment]
@jefflbrauer heads up—adding this to a pub websites milestones so we're able to track the work on our end.

**Comment by jefflbrauer** [comment]
Thanks @MickinSahni . This is supposed to be merged and deployed with today's 3pm build.
