### ISSUE TITLE
Update Inherited Proofing Audit Data

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#51137]
Iterate on Inherited Proofing `AuditData` class creation: https://github.com/department-of-veterans-affairs/vets-api/pull/11421

> I'm going back and forth on whether legacy_csp is necessary, especially if you're checking user_uuid in addition to audit_data.
> What I was thinking of though, if the intention is to make sure this is done with the same session that it started with, perhaps we should save the session id instead of user_uuid/legacy_csp (or oauth session uuid if we're doing SiS)?

**Comment by bosawt** [comment]
@bramleyjl Are you fine if we close this? Since it seems like we're going to deprecate inherited proofing we can prob remove tickets related to it
