### ISSUE TITLE
Request design review for "View Dependents" page

### ISSUE THREAD

**Issue by sporeboy** [department-of-veterans-affairs/va.gov-team#5114]
## View Dependents page / eBenefits migration
The View Dependents page (titled, "Dependents added to you VA disability benefits") has been revised per feedback from the design intent review, and is ready for a formal Platform Deign Review.
### Mockups
Currently this page is only fully available as static mockup here: https://xd.adobe.com/view/8cdfe895-c907-4662-7234-305056778b2a-faee/

### Review
Understanding that the design review process is in flux, we prepared mockups for this design checkpoint following the earlier criteria for the formal Platform Design Review. This particular review may be replaced by the Platform QA Review the page in staging. Please advise as to whether we should schedule a review of the mockups as they are now, or wait until they are available as coded pages in staging.

**Comment by CrystabelReiter** [comment]
@sporeboy It's custom that we wait for a staging review. If you'd like input right now, we could do more informally, asynchronous review rather than a full fledged review meeting.

**Comment by jason-gcio** [comment]
Adjusted assignees to move forward with some level of review before moving this further in staging.

**Comment by jenstrickland** [comment]
@jason-gcio I'll put some time on your calendars. Since Trevor and I are away Mon-Wed, 1/27-29, is 1/30 sufficiently soon to be helpful? Otherwise I can do our usual Friday during our meeting this afternoon.

**Comment by jason-gcio** [comment]
@jenstrickland - Sure, I think we are ready but we are neck deep with frontend and 9 minutes notice just wouldn't be fair :) Let's shoot for 1/30

**Comment by jenstrickland** [comment]
Per conversation on 1/31, aiming for a spot check a11y review soon.
