### ISSUE TITLE
[Other - Accessibility] - Page jumps when tabbing through modal (00.00.2)

### ISSUE THREAD

**Issue by briandeconinck** [department-of-veterans-affairs/va.gov-team#51142]
#### VFS team name
Sitewide

#### VFS product name
VA.gov Homepage

#### VFS feature name
Redesigned homepage

#### Point of Contact/Reviewers
Brian DeConinck - @briandeconinck - Accessibility

*For more information on how to interpret this ticket, please refer to the [Anatomy of a Staging Review issue ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Anatomy-of-a-Staging-Review-Issue-ticket.2060320997.html) guidance on Platform Website.

---

### Platform Issue
Page jumps when tabbing through modal

### Issue Details
When viewing the current homepage with the modal prompt to try the new homepage, keyboard focus is correctly trapped inside the modal. However, when you go through all three tab stops and then tab again to cycle back to the first tab stop, the page behind the modal jumps down to the footer.

For keyboard-first users, this is an unexpected movement that doesn't seem connected to what they're actually trying to accomplish. The impact is pretty small -- focus remains where it's supposed to be, and the modal in the foreground behaves the way it's supposed to behave. But the extra motion may be disorienting, especially for certain users with cognitive disabilities.

### Link, screenshot or steps to recreate
1. Navigate to https://staging.va.gov. Keyboard focus is on the [X] close modal button.
2. Press [Tab] twice. Focus is now on the "Not today" button.
3. Press [Tab] again. Focus moves back to the [X] close modal button, as expected. But behind the modal, the page jumps down to the beginning of the footer.

### VA.gov Experience Standard
[Category Number 00, Issue Number 00](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/va-gov-experience-standards) 

### Platform Recommendation
This feels like it's probably related to where the modal lives in the DOM. I wouldn't consider it launch-blocking but it's definitely worth fixing shortly after launch.

---

### VFS Guidance

- Close the ticket when the issue has been resolved or validated by your Product Owner
- If your team has additional questions or needs Platform help validating the issue, please comment on the ticket
- Some feedback provided may be out of scope for your iteration of the product, however, Platform's OCTO leadership has stated that all identified issues need to be documented and it is still your responsibility to resolve the issue.
- If you do not believe that this Staging Review issue ticket is the responsibility of your team, comment below providing an explanation and who you believe is responsible. Please tag the Point of Contact/Reviewers. Governance team will research and will follow up.

## Platform directions
- Update "Issue Title"
- Link to  Collaboration Cycle Request epic
- Add the VFS team and product name
- Add your name and practice area under Point of Contact(Practice Area)
- Add the Platform Issue. The Issue column from the [VA.gov Experience Standards](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)
- Add the Issue Details and any links, screenshots or steps to recreate
- Add the [VA.gov Experience Standard](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html) number
- Add assignees: VFS PM
- Add labels:
  - VFS team label
  - VA.gov Experience Standard Issue number (CCIssueXX.YY) where XX is the category number and YY is the issue number, per the VA.gov Experience Standards
  - Practice area labels (508/accessibility, IA, content, design) per the VA.gov Experience Standards
  - 508 defect label, if applicable (508-defect-0, 508-defect-1, 508-defect-2, 508-defect-3, 508-defect-4)
  - Launch-blocking label, if applicable

**Comment by jilladams** [comment]
Public Websites is tracking resolution to this under https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12091

**Comment by jtmst** [comment]
This appears to be fixed as a side effect of the change made here: https://github.com/department-of-veterans-affairs/content-build/pull/1415/files

**Comment by jilladams** [comment]
Nice! I also verified in Staging. Closing both this ticket and #12091.
