### ISSUE TITLE
Production/Staging Issue: Header does not get updated when changing screens

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#51156]
## Summary
The header is not updating correctly when navigating between the Pending list page and the VAOS homepage. When the user clicks on Pending list, the header on the page displays Your appointment.  When the user goes back to the homepage, the header is changed to Pending appointments. This is happening in staging and production. 

## Specs
- Device: Desktop
- Browser: Chrome

## Steps to Reproduce
Test user: cecil.morgan@id.me 

1. Go to: https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/
2. Click the `Pending` link 
3. Click the `Your appointment ` breadcrumb 

### Actual Result
When navigating between the homepage and Pending list view, the header does not get updated. 

For example (screenshots below): 

_When a user clicks on the Pending link_ 
<img width="1006" alt="Screen Shot 2022-12-22 at 12 20 41 PM" src="https://user-images.githubusercontent.com/90797205/209191135-2aa3ed29-c940-4ce9-a77c-1c0d8e5c145a.png">

_When a user clicks on the Your appointments breadcrumb_ 
<img width="986" alt="Screen Shot 2022-12-22 at 12 21 09 PM" src="https://user-images.githubusercontent.com/90797205/209191156-614c844c-3e9d-4d16-858c-fd6f32cd94c7.png">

### Desired Result
The user should see the correct header for the page. 
When the user is on the homepage, it should display Your appointments. 
When the user is on the Pending list page, it should display Pending appointments. 

## Definition of Done
- [ ] Desired result is achieved and/or document decisions made

**Comment by ldelacosta** [comment]
The changes will be implemented after the code freeze. The user can refresh their screen and the header will be updated correctly.

**Comment by ldelacosta** [comment]
@vbahinwillit - when reviewing the pending page during stand up, we saw a typo in the page description under the header "Canceled requests" 

Please update the text to "were" 

![Screen Shot 2023-01-12 at 4.16.17 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/8eed5812-e2b9-43b9-b6d1-3a56cd1c385e)

**Comment by simiadebowale** [comment]
@ldelacosta this is ready for review

**Comment by ldelacosta** [comment]
Validated the changes and no issues reported. 

Click to view pending list: ![Screen Shot 2023-01-24 at 9.03.22 AM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/ee8dd38a-f1ab-4492-82f9-01a97e2c69cd)

View page description for Canceled requests:![Screen Shot 2023-01-24 at 9.03.46 AM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/e10803ea-9b05-48c4-9968-7e5f5864ece5)


Click back to VAOS homepage: ![Screen Shot 2023-01-24 at 9.04.03 AM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/2a9030f9-e82b-4a87-884e-9177568cd685)

**Comment by marcynadeau** [comment]
Assigned to Beth for testing

**Comment by beth-wodzinski** [comment]
This passes testing. Tested with cecil and patientten, with breadcrumbs and back button. Looks good. @ldelacosta

**Comment by ldelacosta** [comment]
No issues reported. Closing out the ticket.
