### ISSUE TITLE
Better define functionality of calendar widget

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#5115]
We should put some thought into what generic functionality the calendar widget should have and what's ok to make specific to our needs. There are some attempts in the current code to make it generic, but since we didn't have a clear set of general needs to meet, it hasn't been something we're able to maintain consistently.

This will help us come up with a clear component interface and then we can refactor to make the code simpler.

**Comment by lenaecb** [comment]
Holding off on this for now.

**Comment by jbalboni** [comment]
So, we're still sort of guessing at what functionality someone other than VAOS would need. In the spirit of balancing flexibility with our needs as much as we can, here's what I would suggest we shoot for as far as high level requirements:

- The calendar displays a single month and allows you to move between a min and max date
- You can choose the month it starts on
- You can customize how both slots and the selected date indicator are rendered
    - I think we would default to the slots we show for direct scheduling, and override the renders for our AM/PM path
- You can set it to allow one slot choice or multiple slot choices
    - If you decouple this requirement from the previous one about slot rendering, you'll end up with the ability to specify props that imply you want to allow selecting multiple actual time slots, which VAOS doesn't currently need. We can throw an error to mark that combination as currently unsupported
- The calendar handles required and max selections validation, with customizable messages
- The calendar handles the display of a loading state
   - I'm sort of ambivalent about this, I'd almost rather force pages using the calendar to control this, since the calendar isn't fetching anything itself
- If a user doesn't provider either a list of slots or a way to render slots, then the calendar falls back to selecting dates
   - This is functionality that VAOS doesn't care about, so we can throw an error for now to mark it as something we may do in the future

I think these assumptions are reasonable, and somewhat generic, if we think of the calendar as a tool for selecting time slots during a day, and maybe stretch it a little to being a generic calendar date selector.

This is my attempt at a new set of props for the CalendarWidget, based on the above comments:

- id
   - We don't have this now, but I think we might need an identifier to replace `fieldName` with
- onChange
- value
   - I want to simplify the data we return from this widget, hopefully down to a ISO date string, or an array of them, depending on `maxSelections`
- minDate
- maxDate
- startMonth
- onNext
- onPrev
- required
- requiredMessage
   - This message probably has to be customizable, but hopefully the max selections one does not. We can add another prop if we need to, though
- showValidation
   - We need this to force validation when the form is submitted, in addition to internal logic around the field being "touched"
- renderSlots
   - I think this would sort of replace getOptionsByDate, but return React elements, and I would build the direct scheduling version of this into the calendar itself, since I think that's more likely to be widely applicable that our AM/PM choice
- renderIndicator
   - Similar to above, I'd make the direct schedule version of this the default, and use this component for our AM/PM bubbles
- availableSlots
   - I think this would be the same as availableDates, could stick with the previous name if we wanted
- loadingStatus
- loadingErrorMessage

I dropped `selectedDates` in here, because I think we can manage that with component state. I also dropped `multiSelect` in favor of deriving that from `maxSelections`. Technically that means you don't have a way of selecting an unlimited number of slots, but that does not seem like a reasonable requirement.

**Comment by jbalboni** [comment]
@narin Would like to get your thoughts on the above comment. Once we have a good plan in place, I can make some tickets to do refactoring.

**Comment by narin** [comment]
Hey @jbalboni I think this is well thought out and covers everything I can think of for generic calendar use.  

If the `value` is going to be an ISO date string, we'll have to do something similar to how we are representing AM/PM with our appointment requests (e.g. `AM === '00:00:00.000Z', PM === '12:00:00.000Z'`), which shouldn't be a big deal. 

That's really the only thing that stuck out to me in these notes.  Looking forward to seeing how this component looks once it is refactored, as it definitely seemed a bit messy after @jenniemc and I worked on the conversion to a functional component.

**Comment by jbalboni** [comment]
@narin Yeah, that's a good point about the date. I think the component could be agnostic about the time part of the date string if you're using `renderSlots`, if we wanted it to be. Outside of the slot render part, I think all the calendar needs to care about is the date part. But that doesn't really matter for us, we can use the format we do for the FHIR requested periods.

**Comment by jbalboni** [comment]
Ok, I've created tickets to make all these changes, prefixed by CalendarWidget refactor. Closing.
