### ISSUE TITLE
memory usage on vets-website builds

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#5116]
## User Story or Problem Statement

As promised in [Slack](https://dsva.slack.com/archives/CQH357ZTP/p1579880443033600), this issue is to track a memory bloat in the vets-website build process on CI.

We're seeing a condition where during the build it causes an OOM of the Jenkins runner with c5d.xlarge machines. It's during the "build" phase where it tries to build all 3 envs in parallel and _seems_ like maybe it's when we're merging Drupal content with what's already in the repos. It seems like it's probably timing-related. If two builds happen to be in the phase with the large memory bloat at the same time, we run out.

The best indication I have right now as to "where" it happens is that we're retrying the build without the `--pull-drupal` argument when it fails. When the "build" phase below is higher than normal, that's a good indication this has happened:

![Screen Shot 2020-01-24 at 10.01.24 AM.png](https://images.zenhubusercontent.com/59ca6a96b0222d5de4792f24/340c36e9-60bd-4284-9b01-8ca727bbddd8)

When it does, we see something like this where it retries in the steps:

![Screen Shot 2020-01-24 at 9.27.45 AM.png](https://images.zenhubusercontent.com/59ca6a96b0222d5de4792f24/b7d2dcdd-dc2d-4551-b252-b3b3696e2c27)

For now, we're going to increase the size of the worker nodes that run builds since they're auto-scaled and are hoping that'll mask the problem for the moment. However, if this is related to loading content into memory, it won't work for very long and should be addressed.

## Goal

Measure and reduce memory footprint used to create builds of the website.

## Objectives or Key Results this is meant to further

3. Enable agile VFS delivery of performant applications

## Acceptance Criteria
- [ ] we have a way to capture max memory used during a build of vets-website, investigated to ensure size of content being built is or is not a factor
- [ ] optimize build to not load all content into memory if that's determined to be the case
- [ ] reduce the size of CI workers if possible

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by cvalarida** [comment]
I have two immediate suspicions that we should verify when we go to work on this:

1. The way the build script handles files from Drupal
    - They're all stored in memory until Metalsmith is done doing its thing, if I recall correctly
      - It's possible that these are downloaded and the _path_ is stored in memory, which would make this much less expensive
    - There are a _lot_ of these files, with more added like every day
2. The production build's Webpack step uglifies the bundle, which is pretty expensive as well
    - Not sure what we can do about this, but it's likely worth investigating

**First step:** Measure the memory usage of each step of the build script.

**Comment by cvalarida** [comment]
[This PR](https://github.com/department-of-veterans-affairs/vets-website/pull/11571) measures the memory usage **before** and **after** each step (measuring the max memory usage _during_ the step was harder, and this was just a quick first stab).

Based on the output I saw, I think the thing we want to focus on is the webpack build. I'm not sure the best approach yet, but my guess is the [optimization](https://webpack.js.org/configuration/optimization/) phase in the `vagovprod` (and staging?) build(s) is a massive memory hog, but this assumption should be validated.

**Comment by timwright12** [comment]
Closing as duplicative
