### ISSUE TITLE
[Other - Accessibility] - Text overlap at 175% zoom on Safari under certain conditions (00.00.3)

### ISSUE THREAD

**Issue by briandeconinck** [department-of-veterans-affairs/va.gov-team#51161]
#### VFS team name
Sitewide

#### VFS product name
VA.gov Homepage

#### VFS feature name
Redesigned homepage

#### Point of Contact/Reviewers
Brian DeConinck - @briandeconinck - Accessibility

*For more information on how to interpret this ticket, please refer to the [Anatomy of a Staging Review issue ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Anatomy-of-a-Staging-Review-Issue-ticket.2060320997.html) guidance on Platform Website.

---

### Link, screenshot or steps to recreate
1. On a Mac in Safari, navigate to https://staging.va.gov.
2. Adjust the browser width to the narrowest width allowed (looks like 575px).
3. Press CMD + to increase zoom up to 175% and higher.
4. Note that the action link chevron icon overlaps with the text of the link, obscuring some of the text. See screenshot below.

<img width="435" alt="Try the new home page action link with the word new obscured by the chevron icon." src="https://user-images.githubusercontent.com/6844775/209196334-82d6e09f-f2eb-4d77-a206-33bf718e5f7e.png">

### VA.gov Experience Standard
[Category Number 00, Issue Number 00](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/va-gov-experience-standards) 

### Platform Recommendation
This appears to be limited to Safari, and only happens when the browser window is resized before zooming in. That's very... weird. It may be a CSS quirk for action links across all instances that we just happened to run into this time. Definitely a low-severity issue but it's worth investigating and either fixing here or reporting back to the Design System team.

---

### VFS Guidance

- Close the ticket when the issue has been resolved or validated by your Product Owner
- If your team has additional questions or needs Platform help validating the issue, please comment on the ticket
- Some feedback provided may be out of scope for your iteration of the product, however, Platform's OCTO leadership has stated that all identified issues need to be documented and it is still your responsibility to resolve the issue.
- If you do not believe that this Staging Review issue ticket is the responsibility of your team, comment below providing an explanation and who you believe is responsible. Please tag the Point of Contact/Reviewers. Governance team will research and will follow up.

## Platform directions
- Update "Issue Title"
- Link to  Collaboration Cycle Request epic
- Add the VFS team and product name
- Add your name and practice area under Point of Contact(Practice Area)
- Add the Platform Issue. The Issue column from the [VA.gov Experience Standards](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)
- Add the Issue Details and any links, screenshots or steps to recreate
- Add the [VA.gov Experience Standard](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html) number
- Add assignees: VFS PM
- Add labels:
  - VFS team label
  - VA.gov Experience Standard Issue number (CCIssueXX.YY) where XX is the category number and YY is the issue number, per the VA.gov Experience Standards
  - Practice area labels (508/accessibility, IA, content, design) per the VA.gov Experience Standards
  - 508 defect label, if applicable (508-defect-0, 508-defect-1, 508-defect-2, 508-defect-3, 508-defect-4)
  - Launch-blocking label, if applicable

**Comment by jilladams** [comment]
This modal is now deprecated, closing.
