### ISSUE TITLE
AWS access for Ksenia Coulter

### ISSUE THREAD

**Issue by kscoulter** [department-of-veterans-affairs/va.gov-team#51168]
### COR Name

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative Name

Other - please specify in 'Additional Notes'

### Your Name

Ksenia Coulter

### Your Email

kcoulter@pluribusdigital.com

### Team, Role, and Company of the target individual

Identity Team, Sr. Engineer, Pluribus Digital

### Product Manager (PM) name and email

Elizabeth Koch, elizabeth@bluetiger.digital 

### Product Owner (PO) name and email

John Rahaghi, john.rahaghi@va.gov

### Desired AWS Access

AWS Shell Access (https://depo-platform-documentation.scrollhelp.site/developer-docs/aws-shell-access)

### Access Expiration

09/01/2023

### Additional Notes

COR - Johnathan W. Ivey (JOHNATHAN.IVEY@va.gov)
VOR - Yvonne Gardner

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by little-oddball** [comment]
VFS Roster.

**Comment by little-oddball** [comment]
@kscoulter - I am hopping in to try and help w/ these items. Our Gov't PO had a transition and we now require to have the eQIP transmittal date provided. Would you be able to work with your PO/PM to provide that? Once that has been applied to the ticket I push move it forward to our Gov't PO for a review/approval. Thanks and sorry for the delay and any inconvenience .

**Comment by oseasmoran73** [comment]
@kscoulter Given that there hasn't been any follow up on this ticket, I presume AWS access is no longer required. Closing this ticket. If that is not the case, please feel to reopen so we can follow up on this request again
