### ISSUE TITLE
Choose a date error includes broken link to request flow

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#51172]
## Summary
On the "Choose a Date page" an error includes a link to "submit a request for a VA appointment" when requests are disabled. The link does nothing/goes nowhere.  

## Specs
- Device: Any
- Browser: Any

## Steps to Reproduce
1. Test user's facility has requests **disabled**
2. API fetch for appointment slots is failing
3. Navigate to "Choose a date and time" page
4. Note the error (see screenshots that follow)
5. Click "Submit a request for a VA appointment"

### Actual Result
![image](https://user-images.githubusercontent.com/2536801/209215804-ff4a3deb-6259-490f-9023-3c90c95c863e.png)

Clicking the link does nothing.

### Desired Result
Since requests are disabled, this link should be removed from this error condition. 
The link should only show if requests are enabled.

## Definition of Done
- [ ] Desired result is achieved and/or document decisions made
- [ ] Relevant documentation is updated

---
## How to configure this issue
- [ ] **Labeled with Team** (`vaos`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `design`, `product`)
- [ ] **Labeled with** `Bug`
- [ ] **Assigned to** Product for prioritization

**Comment by vbahinwillit** [comment]
Adding screenshots for different error flows per Peter's request

### Facility configured to accept appointment request
---
![localhost_3001_health-care_schedule-view-va-appointments_appointments_new-appointment_preferred-date.png](https://images.zenhubusercontent.com/5d63fdaa0845ad5f24bad7db/f03d3bcf-0c59-4b06-a057-5de93337a32e)


### Facility configure to accept appointment request (Urgent Care)
---
![localhost_3001_health-care_schedule-view-va-appointments_appointments_new-appointment_select-date (2).png](https://images.zenhubusercontent.com/5d63fdaa0845ad5f24bad7db/acf0b0af-1be4-49f2-a5ce-173453dedd49)

### Facility not configured to accept appointment request
---
![localhost_3001_health-care_schedule-view-va-appointments_appointments_new-appointment_select-date.png](https://images.zenhubusercontent.com/5d63fdaa0845ad5f24bad7db/75037ebb-bfda-4274-b5b6-fb1d99ad137d)

### Facility not configured to accept appointment request (Urgent care)
---
![localhost_3001_health-care_schedule-view-va-appointments_appointments_new-appointment_select-date (1).png](https://images.zenhubusercontent.com/5d63fdaa0845ad5f24bad7db/a6fc7294-6ac8-49d5-81fc-028873a257f7)

**Comment by outerpress** [comment]
@ldelacosta this is validated (with Jennie's help)

**Comment by ldelacosta** [comment]
No issues reported. Closing out the ticket.

**Comment by ldelacosta** [comment]
No issues reported. Closing out the ticket.
