### ISSUE TITLE
[UX] Create workflow diagram for option 1 (that captures all Veteran scenarios)

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#51173]
## Tasks 

Create workflow diagram for option 1 (that captures all Veteran scenarios). Include scenario for when a Veteran has an appt at a non PCI enabled clinic.

[Mural
](https://app.mural.co/t/vfscie8528/m/vfscie8528/1671459379892/bfa34b32cc12d8655715e493c9cffb93bbdbaacb?sender=u83bc52d7fa73658f84f27755)

For reference, the most recent workflow that was created for a specific Epic was this one that [Lori had created for travel pay](https://app.mural.co/t/vfscie8528/m/vfscie8528/1667222840454/ada0c417b71c922895f1750cd32d869f6213e129?sender=u83bc52d7fa73658f84f27755). Might be a good reference point. 

## AC

Validate with CIE team

**Comment by kellysmith1008** [comment]
Created a [basic workflow mural template](https://app.mural.co/t/vfscie8528/m/vfscie8528/1672242899246/a3ef1371373d77f02b2661467399db3f76e65a19?sender=u4f51c3ab811a3cc570d34701) today. Will work on developing this template into the workflow based on the mural above this sprint

**Comment by kellysmith1008** [comment]
@benbrasso-agile6 I took an initial stab at a workflow for this ticket. I'm happy to meet with you for some coworking or improvements based on your thoughts!

**Comment by benbrasso-agile6** [comment]
I can take a look

**Comment by benbrasso-agile6** [comment]
https://app.mural.co/t/vfscie8528/m/vfscie8528/1672855776171/4ee66e7ec8fea7bbc62312d18ae672928bb2dc48?sender=u83bc52d7fa73658f84f27755
