### ISSUE TITLE
[Spike] Talk to Shane about VEText opportunities

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#51180]
## Tasks 

Can we not send a pre-check-in link if demographics don't need to be updated?

Talk to Shane and Stephen about if...

VEText Y1 response, for example, could be used to update the pre-check-in status in VSE and VistA instead of taking Veterans to pre-check-in when demographics don't need to be updated

## AC

Document findings from speaking with Shane

**Comment by kristenmcconnell** [comment]
Shane is OO until January 9. I will message after he returns.

**Comment by benbrasso-agile6** [comment]
Added  in a question to description

**Comment by sarahknoppA6** [comment]
May also be related to skipping this link in #49869

**Comment by kristenmcconnell** [comment]
@loripusey As I was thinking about this and [reading this Slack thread](https://dsva.slack.com/archives/C02UP02HHGX/p1673458292082829), would the logic for this actually live in PCI API? Therefore, should we be talking to Chris Horton? Therefore, I wondered if the best way to bring this up was your sync with him and not me messaging. Let me know what you think?

**Comment by loripusey** [comment]
I don't really know the location for the logic, might be a better question for Adrian (@ callout now working right now). I think this is just an exploration ticket to gain some knowledge.
