### ISSUE TITLE
[Deployment Policies] Update holiday code freeze schedule for 2023

### ISSUE THREAD

**Issue by oseasmoran73** [department-of-veterans-affairs/va.gov-team#51192]
## Description

Farewell 2022 ⛄ , hello 2023! Or at least when you arrive :)

We will need to update holiday freeze schedule for 2023

## Task
- [x] Update holiday code freeze for 2023

## Acceptance Criteria
- [ ] Reflects website accordingly: [Deployment Policies - holiday freeze](https://depo-platform-documentation.scrollhelp.site/developer-docs/deployment-policies#DeploymentPolicies-2022)

**Comment by little-oddball** [comment]
@andreahewitt-odd @jwoodman5 - can y'all take a look and make sure you are cool with the dates?
