### ISSUE TITLE
Content changes to Fiduciary Claims and Supplemental Claims pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#51197]
## Issue Description

Angie Smith reached out for us to make content changes on our Supplemental Claims page about fiduciary claims. We removed an incorrect sentence and published the page but there are more changes we still need to assess and make.

We need to coordinate with the SMEs of fiduciary claims and the Supplemental Claims pages when we make the changes.

Word doc with requested revisions: 

[https://app.zenhub.com/files/133843125/c1b4da81-fbb1-464b-957a-b8fe0f36cef8/download](https://app.zenhub.com/files/133843125/c1b4da81-fbb1-464b-957a-b8fe0f36cef8/download)

Change request form: [https://app.zenhub.com/files/133843125/92480e57-3ac7-4e27-a5c1-c938cf652b1f/download](https://app.zenhub.com/files/133843125/92480e57-3ac7-4e27-a5c1-c938cf652b1f/download)

## Tasks
- [x] Revise content
- [x] Send to VA partners for review
- [x] Copyedit (Megan)
- [x] Publish (Megan)

## Acceptance criteria
- [x] Changes are live on prod

**Comment by laurwill** [comment]
We suggested a phased approach here — initial updates to add Supp Claims as an option on the fiduciary claims page, followed by larger updates to add more specific info about fiduciary claims. 

I sent the initial updates to SME thread on 1/6.

**Comment by laurwill** [comment]
Hi @megzehn , our initial updates to the fiduciary claims page are ready for copyedit and publishing. 
- Updated intro and "Mark your calendar" alert to include Supplemental Claims
- Added a section with basic info about Supplemental Claims to mirror the Higher-Level Review and Board Appeal sections

We're planning more substantial updates to this page as a next step, so I'm sure you'll notice things we'd want to update. For now, the goal is to correct the inaccurate info (by adding Supp Claims as an option). So if you could scope your copyedit for that approach, that would be great! And of course lmk if you have questions.

http://preview-prod.vfs.va.gov/preview?nodeId=3016

**Comment by megzehn** [comment]
Thanks! I reviewed the changes and published the page.

**Comment by megzehn** [comment]
@RLHecht I think we can close this!

**Comment by RLHecht** [comment]
Thanks! Closing
