### ISSUE TITLE
Access for Paul Short

### ISSUE THREAD

**Issue by short000** [department-of-veterans-affairs/va.gov-team#5120]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your name.
   > Paul Short
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Team: VSA; Role: Engineering Lead; Employer: GovernmentCIO
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Internal%20Tools.md#create-ssh-public-key) for instructions.
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDDvMSYvWLo201jjZrdy+VLD/X+AnO9ch3Xz9CTdPa4UVpvPeOHgseyZqya/ewJWycky90RdoPhKDFWhzP9CiiJrdZRCdqtpRr4UKXuGBW0vPRN52eGIW0ZPjOLplcs80z/4S5jlUWplDw/EPf4VDf0c9vAF2O710fWOyaI4XhRc+IcnPD6569o5uFaGYJQGxZreWJAKzvla3X+s2d3PG0oxjdojiPu85ggT9YJu/9nvLxUECIDsbPxzCS0paAADAg+KtQYNEZfxCl8AcP+nB4U/8WFO8nofBx/KJJFUr5CdyQ0UVgqm92dY+gGRW8pO0RSCyhxcWc6VVf0OnuWlKOH paulshort@USRMonitors-MacBook-Pro.local
```

- [Grant AWS Console access?]
  > YES
  >  General: software development, troubleshooting, and understanding of systems, potential pipeline and delivery improvement. Specific: shell access to development and staging systems for troubleshooting, log analysis, testing, and walk-through with developers.

**Comment by ricetj** [comment]
@Jeff-Hayter 
COR: Mary O'Toole
User: Paul Short

**Comment by ricetj** [comment]
@short000 due to new changes in the process, SOCKS access is granted sooner. You should now refer to this section of the instructions to set up your SOCKS. Please also keep following up with your paperwork for the VA.

**Comment by short000** [comment]
Went through the instructions, but getting "permission denied (publickey)" error:

usrmonitors-mbp:.ssh paulshort$ **ssh socks -D 2001 -N &**
[1] 80983
usrmonitors-mbp:.ssh paulshort$ dsva@52.222.32.121: Permission denied (publickey).
ssh_exchange_identification: Connection closed by remote host

**Comment by ricetj** [comment]
> Went through the instructions, but getting "permission denied (publickey)" error:
> 
> usrmonitors-mbp:.ssh paulshort$ **ssh socks -D 2001 -N &**
> [1] 80983
> usrmonitors-mbp:.ssh paulshort$ dsva@52.222.32.121: Permission denied (publickey).
> ssh_exchange_identification: Connection closed by remote host

hey @short000 can you post in the vfs-platfrom-support channel? I know someone will help you with this there. 👍

**Comment by ricetj** [comment]
> > Went through the instructions, but getting "permission denied (publickey)" error:
> > usrmonitors-mbp:.ssh paulshort$ **ssh socks -D 2001 -N &**
> > [1] 80983
> > usrmonitors-mbp:.ssh paulshort$ dsva@52.222.32.121: Permission denied (publickey).
> > ssh_exchange_identification: Connection closed by remote host
> 
> hey @short000 can you post in the vfs-platfrom-support channel? I know someone will help you with this there. 👍

Nevermind, saw you did 😅

**Comment by short000** [comment]
Thanks, they got me squared away:
https://dsva.slack.com/archives/CBU0KDSB1/p1582647655076700 

I reset my SSH key (made note of pass phrase), added it to the keychain so that it would persist between logins, Taylor updated my public key on GitHub, I closed all existing terminals (to get rid of port 2001 in-use errors), re-tested using `ssh socks -D 2001 -N &` (result: one line. number) then `curl -v --proxy socks5h://127.0.0.1:2001 sentry.vfs.va.go` (result: 302 FOUND HTTP Header).

I believe I still need AWS access but I can now reach Jenkins, Grafana, Sentry, and Prometheus.

**Comment by ricetj** [comment]
> Thanks, they got me squared away:
> https://dsva.slack.com/archives/CBU0KDSB1/p1582647655076700
> 
> I reset my SSH key (made note of pass phrase), added it to the keychain so that it would persist between logins, Taylor updated my public key on GitHub, I closed all existing terminals (to get rid of port 2001 in-use errors), re-tested using `ssh socks -D 2001 -N &` (result: one line. number) then `curl -v --proxy socks5h://127.0.0.1:2001 sentry.vfs.va.go` (result: 302 FOUND HTTP Header).
> 
> I believe I still need AWS access but I can now reach Jenkins, Grafana, Sentry, and Prometheus.

Hello Paul, yes your AWS access is still pending approval.

**Comment by Jeff-Hayter** [comment]
@ricetj Approved for AWS.

**Comment by jbritt1** [comment]
@short000 I have a PR open to add your AWS IAM access. Once that is resolved, I will contact you on Slack with first time login credentials.

**Comment by jbritt1** [comment]
First time AWS console login credentials passed via Slack DM.
