### ISSUE TITLE
Make it easy for veterans to return to the old tool

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#5124]
As a veteran, I want to be able to easily get to the old VAOS so that I can continue booking my appointment if I get stuck in new VAOS for any reason (either a bug or just confusion about the new interface).

AC
- [ ] Veteran can navigate to old vaos from any page in new vaos
- [ ] Veteran doesn't need to reauthenticate when already signed in with MHV credentials*

* If a veteran logs into VA.gov with MHV creds, they should get signed into MHV automatically. However, it's not clear if this automatic signin mechanism would work if we link directly to legacy VAOS. So, we would need to figure out whether to take veterans straight to old VAOS (ideal) or the appointments page in MHV (second choice).

@rtwell could you provide a mock for this link or alert or button or whatever it ends up being? Also, @peggygannon would love to get you to provide content for whatever this design ends up being.

Per Ryan, see the link in 'need help' footer:
![image (6)](https://user-images.githubusercontent.com/24251447/73238385-71c9c000-415e-11ea-9ea9-c3c12d0ab524.png)

**Comment by markgreenburg** [comment]
Also note that we'll want to keep track of this so that we can remove any associated content and code after the old tool is sunset.

**Comment by jbalboni** [comment]
@markgreenburg That second bullet is more of a backend issue than a front end one.

**Comment by markgreenburg** [comment]
Also probably need a link on the CTA widget (opted-in version) that has a similar way to get back to the old tool. @peggygannon would be great to get content for this link.

**Comment by peggygannon** [comment]
@rtwell @markgreenburg Hello, here is link language to add to the widgets that would allow users a path to go back to the legacy tool. The link should be placed under the blue buttons: 

{for View appointments CTA}

{button} Go to VA.gov scheduling tool
[Go to previous scheduling tool](https://www.myhealth.va.gov/mhv-portal-web/web/myhealthevet/appointments)

{for Schedule or Cancel CTA}

{button} Go to VA.gov scheduling tool
[Go to previous scheduling tool]( https://www.myhealth.va.gov/mhv-portal-web/schedule-or-cancel-a-va-appointment-online)

**Comment by jbalboni** [comment]
It's somewhat complicated to put a link to the old tool alongside the link to the new tool in the CTA, because the new tool doesn't require an MHV account, but the old tool does. How should we message that to users? There are a few different error states for MHV accounts that can be shown.

**Comment by lenaecb** [comment]
@peggygannon @rtwell -- thoughts on Jeff's comment re: messaging for MHV and the links?

**Comment by rtwell** [comment]
these words are 100% wrong, but my idea is to set the expectation from the get-go:

![image](https://user-images.githubusercontent.com/12564977/75453588-20217a80-5942-11ea-9329-bc9165d3e04f.png)

**Comment by jbalboni** [comment]
It might be easier to go through all the relevant states a signed in user could be in:

1. Signed in with id.me account, found in MVI
   - Access to new tool: yes
   - Access to old tool: Unknown, must sign in with MHV to know for sure
2. Signed in with DSLogon account, found in MVI
   - Access to new tool: yes
   - Access to old tool: Unknown, must sign in with MHV to know for sure
3. Signed in with MHV Basic or Advanced account, found in MVI
   - Access to new tool: yes
   - Access to old tool: No, needs a Premium account
4. Signed in with MHV, found in MVI, MHV account needs verification
   - Access to new tool: yes
   - Access to old tool: No, needs to verify account
5. Signed in with MHV, found in MVI, MHV account has mismatched SSN
   - Access to new tool: yes
   - Access to old tool: No, needs to fix mismatched SSN
6. Signed in with MHV, found in MVI, has multiple matching MHV accounts
   - Access to new tool: yes
   - Access to old tool: No, needs to fix multiple accounts
7. Signed in with MHV, found in MVI, MHV couldn't find patient records
   - Access to new tool: yes
   - Access to old tool: No, needs to fix account to match records
8. Signed in with MHV Premium account, found in MVI, account state is good
   - Access to new tool: yes
   - Access to old tool: yes

Currently, the CTA widget displays messages for all these states when a user only has access to the old tool.

**Comment by rtwell** [comment]
thank you for the specificity, @jbalboni !

I spoke with @lalexanderson-dsva and we decided that we will only point to old vaos from a signed-in state within new vaos, for two reasons

1) as jeff pointed out, it's complicated given all the various signed-in states and
2) when Cerner portals start opening, it will (or could) become even more confusing as to where Veterans should go for which service. 

SO, let's drop a modal onto new vaos like we utilized for the new va.gov ( @peggygannon we'll need words for this):

![image](https://user-images.githubusercontent.com/12564977/75475142-435e2100-5966-11ea-97ce-e2c9367d820e.png)

Also, @jbalboni we need to update our new vaos landing page to make sure we capture the link on that page (as well as a simplified design):

![image](https://user-images.githubusercontent.com/12564977/75475732-49a0cd00-5967-11ea-9ccc-e05adec29cb4.png)

**Comment by jbalboni** [comment]
@rtwell We have the same list of scenarios inside the VAOS application itself as we would on the call to action box. Unless we can skip MHV and link to the legacy tool directly without forcing another sign in.

**Comment by peggygannon** [comment]
hello, @jbalboni and @rtwell Ok, to clarify:

We are adding a modal as well as a link to the VAOS home screen that would allow users to go to legacy tool if they prefer? 

will take a look and provide copy..

**Comment by jbalboni** [comment]
We have two options for linking to the old tool from the redesign:

1. We link to the MHV scheduling page, like the CTA widget does
   - Pros: we know this works and it's easy to implement
   - Cons: this only works for MHV users, for other users we will force them to sign in with MHV or be stuck. We also need to communicate the different MHV error states to users.
2. We create a VAMF session and go to the scheduling tool directly
   - Pros: Any user should be able to go to legacy VAOS without signing in again
   - Cons: While MHV does this, we don't know for sure it's possible from va.gov, and would require extra backend work to research and implement

**Comment by jbalboni** [comment]
@lenaecb is going to work with @lalexanderson-dsva to figure out the right path here.

**Comment by lenaecb** [comment]
Okkkkk, here's were we landed from this morning.

Show modal _after_ veteran has logged in. Modal link should point to MyHealtheVet link. However, prior to implementing we need to test flow of all 3 logins into new VAOS and then also test flow from VAOS to MyHealtheVet from all 3 logins. 

@jbalboni

**Comment by lalexanderson-dsva** [comment]
@lenaecb @jbalboni @jkassemi 

Link in footer of the application should go to https://veteran.mobile.va.gov/var/v4/. User will NOT have to login again. It looks like they do, but they don't. 

We do not want a link to the old tool in the sign-in modals (authenticated or unauth) on this page: https://www.va.gov/health-care/schedule-view-va-appointments/. 

We DO want a link to the old tool in the footer on this page https://www.va.gov/health-care/schedule-view-va-appointments/appointments. 

Up for discussion is having a modal on this page (https://www.va.gov/health-care/schedule-view-va-appointments/appointments) that explains that you're on a new tool and can always find the link to the footer in the old tool. 

Suggested content for that 

`Welcome to the new VA online scheduling tool on VA.gov`

`This tool has been redesigned with Veteran feedback. You may use this tool to schedule, request, and cancel some VA or community care appointments.`

`If you need it, you will find a link to the mobile online scheduling tool in the footer. BUTTON: Go to the old VA online scheduling tool now.`

**Comment by peggygannon** [comment]
@lenaecb @lalexanderson-dsva For the ^^content on the modal, do we need let users know that any appointments they made on the old tool can be viewed on the new tool?

**Comment by lenaecb** [comment]
Capturing our notes from call.

For this ticket, we are going to enable:
-  a modal upon first time entry to the new VAOS tool (should show on this page - https://www.va.gov/health-care/schedule-view-va-appointments/appointments) that can be dismissed
- the consistent footer being used throughout the whole tool (see #
- In footer add link to old tool

We plan to update the modal at:
- full launch - keeping the modal but updating the copy to only acknowledge that they are in a new experience
- 3 months after launch - based on adoption - remove modal altogether (at this point all access points will be pointing to new VAOS tool) *Yay!*

**Comment by jbalboni** [comment]
Using @lalexanderson-dsva's text it would look something like this, I think:

![Screen Shot 2020-03-04 at 4.11.13 PM.png](https://images.zenhubusercontent.com/599c94608f62dc7798c3b2cd/0b6161fb-5bc9-47b0-83f4-07f5f6f59545)

However, we still have @peggygannon's question and follow up content updates. And I'm assuming that we don't want the button at the bottom to go to the old tool, but to continue through to the new tool.

**Comment by lalexanderson-dsva** [comment]
@jbalboni this looks good. 

Per @peggygannon's question: I don't want the modal to grow too much more at this time. I would recommend swapping in that text about finding your old appointments from old vaos in this tool once we make the call to retire legacy.  

> @lenaecb @lalexanderson-dsva For the ^^content on the modal, do we need let users know that any appointments they made on the old tool can be viewed on the new tool?

**Comment by peggygannon** [comment]
Hi, @jbalboni @lalexanderson-dsva , i'm working on modal text now and will be uploading my recommendation shortly! thanks for the additional feedback and the mock!

**Comment by peggygannon** [comment]
Hello, @lalexanderson-dsva @jbalboni @lenaecb @rtwell 
Here is proposed updated modal copy. Please let me know if you have any feedback. 


**Welcome to the new VA.gov online scheduling tool**
The VA appointments tool has been redesigned based on feedback from Veterans like you. You can now view, schedule, and cancel all your appointments in one place on VA.gov. 
If you want to go back to the old appointments tool, you’ll find a link to that scheduling tool at the bottom of the page in the new tool. 

{button} Continue to your VA appointments(https://www.va.gov/health-care/schedule-view-va-appointments/appointments)

**Comment by jbalboni** [comment]
![Screen Shot 2020-03-05 at 11 30 24 AM](https://user-images.githubusercontent.com/634932/76002524-bcb0c300-5ed4-11ea-911b-097231c9090b.png)

**Comment by peggygannon** [comment]
thanks, @jbalboni the updated screenshot looks good to me, assuming everyone is A-OK with the copy?

**Comment by lenaecb** [comment]
I think it looks great. 

@lalexanderson-dsva @rtwell - y'all good?

**Comment by rtwell** [comment]
lgtm!
