### ISSUE TITLE
Update Sign in Modal copy 

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#5126]
DS logon is regularly out for extended periods of time (~31 hours last week), and can be a [generally frustrating experience for veterans](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/login/ds-logon/research/research_brief.md).

we could make it clear to veterans that they can log in with id.me or create a new id.me account and their "stuff" will still be there (presuming they have verified their identity).  
Before: 
<img width="360" alt="DS_logon_Banner" src="https://user-images.githubusercontent.com/19188/73770616-af27e200-474a-11ea-95f7-db8056ca1bb1.png">

Acceptance criteria :
- [x]  BE will verify which data will/will not be present if a veteran were to log in with an idienty-proofed account and communicate that in this ticket
- [x]  Content written 
- [x]  Content will be added to Sign in Modal

**Comment by annaswims** [comment]
the current banner says 
> We’re sorry. We’re working to fix some problems with our DS Logon sign in process. If you’d like to sign in to VA.gov with your DS Logon account, please check back later.


I'd like to update it to let a user/veteran know that they could use an existing id.me account or sign up for id.me.  Regardless of what kind of account they use to log in the data they see will be the same (as long as they have an identity-verified account).  

Is there a way we could say that more concisely?  Mostly, I want to convey that they don't have to wait for DS logon to work (because it's so unreliable).

**Comment by annaswims** [comment]
It could also be helpful to put the number for DS logon help in the banner. 

DMDC/DEERS Support Office (DSO) at 800-538-9552

**Comment by peggygannon** [comment]
Hi, @annaswims Here is a recommended update to the DS Logon message. Please let me know if you think this will work. I've added a link to our sign in FAQ page so users can learn more about ID.me and how to create new account/verify their identity if they haven't already. 


**You may have trouble signing in with DS Logon**
We’re sorry. We’re working to fix some problems with our DS Logon sign in process. You can sign in to VA.gov with an existing ID.me account or you can create an account and verify your identity through ID.me. 
[Learn how to create an account through ID.me](https://www.va.gov/sign-in-faq). 

If you continue to have trouble, please call the DS Logon help desk at (800) 538-9552.

**Comment by annaswims** [comment]
<img width="1195" alt="Screen Shot 2020-02-28 at 10 47 22 AM" src="https://user-images.githubusercontent.com/19188/75585091-5264d200-5a3f-11ea-9512-0719e85efea6.png">
validated that more users use id.me when ds logon is unavailable
