### ISSUE TITLE
Design: Community pharmacy search 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#5129]
## User Story:
As a Veteran, I need accurate information about where to fill urgent care prescriptions so that I don't pay out of pocket.  

**Background** 
There are two purposes for pharmacy locations:

- Immediate need pharmacy benefit (results from referred care)
- Urgent care pharmacy benefit (results from urgent care)

With MVP release, urgent care pharmacies became searchable via facility type drop down and referral text was removed from the facility card.  

However, urgent care pharmacies can still be searched using Facility type = "Community Care (Non-VA Health)"  + Service type = "Pharmacy - Community/Retail Pharmacy". Results returned for this search will contain misleading  referral information.

![image](https://user-images.githubusercontent.com/55411834/73095879-5fb6fb80-3e98-11ea-9ebf-4ff07508a99f.png)

The pharmacy list will overlap for these two cases, making the Link/Alert confusing depending on why the veteran is looking for that kind of facility. 
-> User goes to Walgreen's to fill an urgent care prescription (needs the urgent care alert)
-> User fills the prescription at Walgreen's because he lives too far from a VA Pharmacy and needs the script too soon to fill by mail (or because it cannot be mailed due to the type of medication)

## Tasks
[ ] Research user journey [5763]
[ ] Determine workflow for Immediate need pharmacy benefit (results from referred care) search and presentation of referral information 
[ ] Determine handling of legacy search when Facility type = "Pharmacy - Community/Retail Pharmacy"

## Acceptance Criteria:
**(Details pending results of research)**

**Comment by davidconlon** [comment]
Confirming with JR that there is not a case where Pharmacy is used outside the Urgent Care workflow and requires a referral.

Want to groom this and put in backlog but should not be put into a sprint until that is confirmed.

**Comment by davidconlon** [comment]
@mmiddaugh 
Response:

There are two purposes for pharmacy locations: 
•	Immediate need pharmacy benefit (results from referred care)
•	Urgent care pharmacy benefit (results from urgent care)

In this instance I see a few things:
1. We should not suppress from main list.
2. We should consider a separate alert/information workflow
3. The behavior and card should be the same whether you access via Comm Care Facility Type + Retail Phamacy Service type *or* via the Facility Type alone

This speaks directly to the "service experience" and potentially another case to consider.

**Comment by mmiddaugh** [comment]
@davidconlon        

1. Is there any difference in the facility list for the two purposes? Do they overlap completely? Meaning, my neighborhood Walgreen's will be a facility returned for immediate need benefit and for urgent care benefit? 
2. I'm assuming the immediate need pharmacy will not need the alert with the link to the urgent care eligibility content....making behavior different for pharmacies returned to urgent care search (which we just added) vs the legacy search using VA Community Care (In Network) + Service type.              
3. Speaking of service type: 

![image](https://user-images.githubusercontent.com/55411834/73987743-36fe1f80-48f6-11ea-9495-a4b236afc4df.png)

**Comment by davidconlon** [comment]
@mmiddaugh 

Answer to 1: The facilities can be one-in-the same making the Link/Alert confusing depending on why the veteran is looking for that kind of facility. You could end up going to walgreens for urgent care because you went to urgent care and got a script. OR you could end up going to walgreens because you live too far from a VA Pharmacy and need the script too soon.

Answer to 2: They would need the referral in the case of a non-urgent care qualifier. So we need to better understand the veteran's health journey here rather than just reacting to the business.  (WE're the ones that found this issue!)

**Comment by mmiddaugh** [comment]
@arickalewis1 we'll need to add this topic to a future research plan

**Comment by mmiddaugh** [comment]
Editing the description of this issue to reflect new understanding. Created [5763] for researching user journey on this
