### ISSUE TITLE
[Due 02/06] Redirect Request: Health Travel Reimbursement 

### ISSUE THREAD

**Issue by AnneHurley** [department-of-veterans-affairs/va.gov-team#5130]
### Instructions
- Requests for redirects need to be submitted **AT LEAST** 2 weeks in advance.  Some redirects take significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation of the redirect to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders of pending redirect.  

### Description
*This is a detailed description of the request. It should include background information and reason for the request.*

### Requestor Info
Stakeholder Jeffrey Gardner and people on his team for Health Travel Reimbursement.

### Implementation Date
**02/06/20**

Please indicate when the redirect(s) needs to be implemented"
- [x ] On the same date the new URLs launch
- [ ] Can happen within 1-5 business days after new URLs launch
- [ ] Other - Please indicate timing : 

**The requesting team is responsible for notifying the group working on this issue if the target date changes. They are also responsible for ensuring the destination URLs are implemented correctly and live at the time the redirects are deployed.**

### Redirects Needed
Current URL  |  Redirect Destination (new URL)
---  |  ---
www.va.gov/healthbenefits/vtp/beneficiary_travel.asp <br>**All casing variations of this URL must be accommodated** | https://www.va.gov/health-care/get-reimbursed-for-travel-pay/

This URL is getting a 404 error:
https://www.va.gov/health-care/get-reimbursed-for-travel-pay/
****--- preview-prod.vfs.va.gov/preview?nodeId=2431****
CORRECT NEW URL COMING

Note - copy for this redirect is: https://github.com/department-of-veterans-affairs/va.gov-team/issues/4804

### Steps to complete
- [x] Above information is provided and issue is tagged and assigned appropriately - *@ requesting team*
- [x] All appropriate VA stakeholders are notified of pending redirect - *@ requesting team*
- [x] Redirect request is vetted and documented and implementation plan is clear - *@ Content & IA team*
- [x] Request is assigned to appropriate team for implementation - *@ Content & IA team*
- [ ] Implementation team completes work - *@ Implementation team*
- [ ] Implementation pushed live and redirect is validated in production - *@ all*
- [ ] Ticket is closed - *@ requesting team*

**Comment by mnorthuis** [comment]
@AnneHurley @lunascoop I don't see any legacy URLs in this request, is this ready for me to vet, or are you still waiting for information?

**Comment by lunascoop** [comment]
Hi @mnorthuis I believe this is the legacy URL: https://www.va.gov/HEALTHBENEFITS/vtp/beneficiary_travel.asp. I'll update the redirect request details.

**Comment by mnorthuis** [comment]
@lunascoop This is vetted and ready when you are.  I added a note to the table above regarding the casing issue - both the /healthbenefits/ and the /vtp/ components need to be acommodated.

**Comment by lunascoop** [comment]
Stakeholders have been notified. Redirect implementation date scheduled for **02/06**. @ncksllvn @kelsonic the URL is specified in the initial comment. Please note that both cases (upper and lower) need to be accommodated. Please see Mikki's comment directly above.

**Comment by lunascoop** [comment]
@RLHecht can you confirm that the page below has been published/live in Drupal? https://www.va.gov/health-care/get-reimbursed-for-travel-pay/

**Comment by RLHecht** [comment]
@lunascoop this page is live but I changed the URL to this one this morning after realizing what we had did not match. That means the page won't show up until after today's deployment.

**Comment by RLHecht** [comment]
@lunascoop @ncksllvn I just noticed that we are still linking to the legacy travel pay page on the health care hub landing page (in the list under Manage your health and benefits). Will this be updated when the redirect happens or should I go into Drupal and put in the Node ID. I'm thinking the latter but wanted to confirm before doing so. https://www.va.gov/health-care/#get-va-health-care

**Comment by ncksllvn** [comment]
PR is open - https://github.com/department-of-veterans-affairs/devops/pull/6312 -

> A case-insensitive redirect from /healthbenefits/vtp/beneficiary_travel.asp to /health-care/get-reimbursed-for-travel-pay/.

I got this from the issue description, but LMK if that's no longer accurate.

**Comment by MickinSahni** [comment]
Adding to sprint 14

**Comment by MickinSahni** [comment]
Q: Unsure if link should point to Drupal node id rather than legacy page considering redirect? 
A: point to node id- @RLHecht

**Comment by MickinSahni** [comment]
2020-02-06 PW Standup
- waiting for DevOps to deploy

**Comment by ncksllvn** [comment]
This is done!

**Comment by lunascoop** [comment]
Validated the redirects. Closing ticket and updating stakeholders.
