### ISSUE TITLE
Resolve issue of granting Zenhub licenses

### ISSUE THREAD

**Issue by it-harrison** [department-of-veterans-affairs/va.gov-team#51344]
Recently, [many people have needed to have Zenhub licenses granted to them](https://dsva.slack.com/archives/CU1E4CX9U/p1670436769597869?thread_ts=1670434640.409069&cid=CU1E4CX9U), even people who already had access to Zenhub, but only a Zenhub admin can grant licenses. This makes it difficult for support to field requests that come in. It would be good to find a better way to deal with this issue - this has been especially true during the Holidays when all Zenhub admins were OoO.

**Comment by shiragoodman** [comment]
hey @it-harrison . Do you know if [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/55501) will help resolve the Zenhub license issue you documented here?

**Comment by it-harrison** [comment]
@shiragoodman I think it will. This ticket can probably be closed.

**Comment by shiragoodman** [comment]
great! Let's close it then :)
