### ISSUE TITLE
STEM-1995: Update Form Picker Wizard

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#5134]
As a veteran, I need to have a clear understanding of the eligibility requirements for the STEM Scholarship so that I do not complete and submit an application unnecessarily. 

## Assumptions:
1. This work will be completed behind a production / feature flag so that it is only available in the staging environments and below.

## Acceptance Criteria:
1. The "Updating my current education benefits" answer is replaced with "Updating my program of study or place of training"
2. The "Applying to extend my benefit using the Edith Nourse Rogers STEM Scholarship" answer is replaced with "Applying to extend my Post-9/11 or Fry Scholarship benefits using the Edith Nourse Rogers STEM Scholarship"
3. If the user selects "Applying to extend my Post-9/11 or Fry Scholarship benefits using the Edith Nourse Rogers STEM Scholarship" is selected, the following content is displayed:

> To be eligible for the [Edith Nourse Rogers STEM Scholarship](https://benefits.va.gov/gibill/fgib/stem.asp), you must meet all the requirements below. You:
> • Are using or recently used Post-9/11 GI Bill or Fry Scholarship benefits
> • Have used up all your education benefits or are within 6 months of using all your benefits. Check remaining benefits
> • Are enrolled in an undergraduate program for science, technology, engineering or math (STEM), or have already earned a STEM degree and are pursuing a teaching certification. See approved STEM programs
> 
> To learn more about the scholarship, visit the VBA STEM page.

4. If the user selects "Applying to extend my Post-9/11 or Fry Scholarship benefits using the Edith Nourse Rogers STEM Scholarship" is selected, the following question is displayed after the text in AC # 3: "Based on the eligibility requirements above, do you want to apply for this scholarship?"
5. The following answers are available for the answer to the question in AC # 4:
	a. Yes
	b. No
6. If the user selects "Yes" as the answer to question in AC # 4, the "Apply Now" button is displayed.
7. If the user selects "No" as the answer to question in AC # 4, the following content is displayed: "Learn what other education benefits you may be eligible for on the GI Bill eligibility page."
     - GI Bill eligibility page is a link to the following url: https://www.va.gov/education/eligibility/

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/share/BWIACP5V5HM#/screens)
2. [Content Document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/design/wizard-update/content/wizard-content-update.md)

**Comment by delli-gatti-michael** [comment]
PR: 
https://github.com/department-of-veterans-affairs/vets-website/pull/11618

**Comment by delli-gatti-michael** [comment]
Local Testing complete

![Screen Shot 2020-02-05 at 12.33.45 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/4f018a99-de76-49f2-b242-559f9e0f711f)

**Comment by delli-gatti-michael** [comment]
@department-of-veterans-affairs/bah_uxteam This is now in Staging and ready for review.

**Comment by amyknox** [comment]
Wizard content was updated as a result of usability testing last week.  Final content - DEPO approved! - is here. https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/design/wizard-update/content/wizard-content-update.md

Wizard UI is online here https://bahdigital.invisionapp.com/share/9GIACS4WX82#/screens/296030714

And here's a screenshot
![image.png](https://images.zenhubusercontent.com/5b51ea398c1a7628d9218a42/2f1a1910-ac9d-4a84-87ca-590c1bc25358)

**Comment by elder-joseph** [comment]
@amyknox Awesome! Glad we got approval.

**Comment by delli-gatti-michael** [comment]
PR #2 https://github.com/department-of-veterans-affairs/vets-website/pull/11676

**Comment by delli-gatti-michael** [comment]
PR #3:
https://github.com/department-of-veterans-affairs/vets-website/pull/11720

**Comment by delli-gatti-michael** [comment]
Changes are in Staging. Closing this issue
