### ISSUE TITLE
[BE] Research VAOS Documentation for Unified CIE Spike

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#51342]
### Description
Look into VAOS architecture and available endpoints for [Unified CIE Spike](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/50683)

**Comment by benbrasso-agile6** [comment]
Using this ticket instead - https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/50683
