### ISSUE TITLE
[Platform Website] Update 'Key Management' documentation  

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#51348]
## Description
The Platform Content Team is editing Platform documents so that these documents no longer link to Confluence pages because VFS team members can no longer see Confluence pages. 

The "Key Management" document in the Developer Docs section of the Platform Website has at least one link to a Confluence page. 

## Resources
In [Key Management](https://depo-platform-documentation.scrollhelp.site/developer-docs/key-management), towards the bottom of the page, it says, “[Venafi: Create and download TLS certificates](https://vfs.atlassian.net/wiki/spaces/VI/pages/821264480)” with a Confluence link. 

- How do we fix this? 
  - Is there a comparable document we can link to instead? 
  - Is there a way to edit the document, so we no longer have that link? 
  - Should we add a note saying that only certain team members can access the link, so if you’re getting a broken link, don’t worry about it? 

## Acceptance Criteria
- [x] "Key Management" is updated with accurate information 

## How to configure this issue
- [x] _Team label assigned_
- [ ] _Epic assigned_
- [x] _Estimated (points assigned)_
- [x] _Sprint assigned (once planned)_
- [x] _Team member(s) assigned_

**Comment by jhouse-solvd** [comment]
Working on this now.

**Comment by jhouse-solvd** [comment]
[Key Management](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1886879804/Key+Management) has been updated in Confluence but has not yet been published on the Platform Website. 

Requesting review from @laucon.

**Comment by laucon** [comment]
This looks perfect to me. We will publish it on Tuesday. Thanks!

**Comment by jhouse-solvd** [comment]
@laucon - That sounds great. Thank you so much!
