### ISSUE TITLE
PDF Cert Content Update from Public-Websites

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#51357]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [x] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
  - [x] Content support
  - [ ] IA support
  
In an earlier ticket, #48458, SW Content provided language for two informational alerts in Find-a-form. We're warning Veterans that there might be issues with Adobe Reader after Jan 7, 2023, due to certificate expiration. Adobe changed their advice, and now we think that it matters what version of Adobe Reader Veterans are using – it has to be 2020 or later. We need to revise the informational alert language to reflect this new (and still ambiguous) situation.

Here is [Adobe's latest advice](https://experienceleague.adobe.com/docs/experience-manager-65/forms/administrator-help/configure-acrobat-reader-dc-extensions/updating-expired-reader-extension-certificates.html). (It's very confusing.) 

Previous content written for post-Jan 7:

>**Search page:**
>We recently updated some of our forms
>If you downloaded older copies of VA forms, you may not be able to use them anymore. You can download new copies now.

>**Detail page:**
>We recently updated this form
>If you downloaded an older copy of this form, you may not be able to use it anymore. You can download a new copy now.

**We now need it to say something like...**
We recently updated some of our forms, _and_ you should update your Adobe Reader to 2020 or later.

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [ ] Yes
  - [x] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
## When do you expect to launch your product to 100% of users?

Jan 7, 2023
  
*Please provide an estimated date so our team can create other relevant tickets.*
  
## Supporting artifacts
*Please provide supporting artifacts as available.*

- Link to product outline:
- Link to or attach user flows:
- Link to prototype or mockups:
- Link to any epics/issues that may be helpful:

## Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [x] No

## When does this work need to be done?
- Estimated launch date:  JAN 7, 2023
- Estimated staging review date:
- Content and IA work needed by: 

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: Dave Conlon
-	Product manager: Wes Rowe
-	Designer: 
-	FE engineer: 
-	Product/team Slack channel: Public websites

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by laurwill** [comment]
Hi @wesrowe , couple questions as we draft this content:
- Are all the forms updated to the new certificate now?
- Will users still need to download the new versions of forms after Jan 7 — or is Adobe saying that the old versions will still work as long as you use Adobe Reader 2020? (You're right that the Adobe advice is confusing!)
Thanks!

**Comment by wesrowe** [comment]
@laurwill, 
- Yes, all form have updated certs now
- No new downloads needed

**Comment by laurwill** [comment]
Hi @wesrowe ,
Just documenting from slack that we need to tell people to both download the form again and update Reader, since we're not 100% sure which step will fix the potential problem (and neither is Adobe). 

Here's our suggested text for the updated info alert:

**Having trouble opening a VA form?**
Try these steps:
1. [Get the latest version of Acrobat Reader for free from Adobe](https://get.adobe.com/reader/)
2. Download the form again

**One question for you here:** Is "opening" the right word to use in the header? Or would "using" be more accurate for the type of problem people may have?

We think it could also be helpful to adjust the language in this "download" modal to say make sure you're using the latest version. We'll suggest content updates for that as well — just wanted to get you the info alert content right away.
<img width="389" alt="image" src="https://user-images.githubusercontent.com/104158104/210839681-1e551ef0-dc6c-4faf-a187-d209a04932cf.png">

Let me know if you have questions or want to chat!

**Comment by laurwill** [comment]
Hi @wesrowe , 
Here's a new version per our slack chat about focusing more on the Adobe issue:

**Use the latest version of Acrobat Reader**
Some VA forms may not work with older versions of Acrobat Reader. You may also need to download a new copy of the VA form.
[Get Acrobat Reader for free from Adobe](https://get.adobe.com/reader/)

**Comment by RLHecht** [comment]
This work is complete. Going to close but reopen @wesrowe if you need anything more from us.
