### ISSUE TITLE
STEM-1995: Update STEM Questions in 1995 Form

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#5135]
As a veteran, I need to have a clear understanding of the eligibility requirements for the STEM Scholarship so that I do not complete and submit an application unnecessarily. 

## Assumptions:
1. This work will be completed behind a production / feature flag so that it is only available in the staging environments and below.

## Acceptance Criteria:
1. The following content is displayed at the top of the page before any questions:

> **Rogers STEM Scholarship**
> 
> The [Edith Nourse Rogers STEM Scholarship](https://benefits.va.gov/gibill/fgib/stem.asp) is offered to students training in high demand STEM (Science, Technology, Engineering, and Math) fields.
> 
> **To be considered, you must meet all the requirements below. You:**
> 
> • Are receiving Post-9/11 GI Bill or Fry Scholarship benefits
> • Have used all your education benefits or are within 6 months of using all your benefits. Check your remaining benefits 
> • Are enrolled in an undergraduate degree program for STEM, or have already earned a STEM degree and are pursuing a teaching certification See approved STEM programs

2. The "Are you applying for the Edith Nourse Rogers STEM Scholarship?" question is replaced with: 
> "Are you applying for the Rogers STEM Scholarship?"

3. After the users answers 'Yes' to "Are you enrolled in a science, technology, engineering, or math (STEM) undergraduate  degree program?" OR answers the "Do you ave a STEM undergraduate degree and are now pursuing a teaching certification?" the following required question is conditionally displayed:
> "Have you used all of your Post-9/11 GI Bill or Fry Scholarship benefits or do you have less than 6 months remaining?"

4. After clicking "Continue" on the "Rogers STEM Scholarship" page the user is directed to the "Rogers STEM Scholarship eligibility" page.

5. The "Rogers STEM Scholarship eligibility" page displays the following content:

> **Rogers STEM Scholarship eligibility**
> 
> **Based on you responses, it appears you're not eligible.**
> 
> **Your responses:** 
> - Post-9/11 GI Bill beneficiary or Fry Scholarship recipient
> - Have used all your education benefits or are within 6 months of do so 
> - Are enrolled in a STEM undergraduate degree program, or have earned a STEM degree and are now pursuing a teaching certification

6. For the your responses content display:
     - display X if user indicated "No" on the previous page 
     - Checkmark if they indicated "Yes" on the previous page

7. The following question is displayed after the eligibility summary:
> Since it appears you're not eligible for the scholarship, would you still like apply and let us determine your eligibility? (*Required)

8. The following are available answers to the question in AC # 7:
     - Yes
     - No

9. If the user answers "No" to the question in AC # 7 the following content is displayed: 
> If your situation changes in the future and you meet all of the criteria, you may return to apply for the Rogers STEM Scholarship.
> 
> [Explore other education benefits] { button } .

10. When the user clicks the "Explore other education benefits" button, they are navigated to "https://www.va.gov/education/about-gi-bill-benefits/" within the same window.

11. If the user answers "No" to the question in AC # 7 the following content is displayed after the "Explore other education benefits" button: 
> Since you're not applying for the Rogers STEM Scholarship, if you need to change your program of study or place of training, continue with this application.

12. If the user meets all eligibility criteria for the STEM scholarship, they navigate to the "Active Duty" stem question of the 1995 workflow.

13. If the user does not meet all eligibility criteria for the STEM scholarship, they navigate to the "Military History" section of the 1995 workflow.

14. If the user does not meet all eligibility criteria for the STEM scholarship and continues the 1995, it is submitted as a normal 1995 application (NOT a 1995S).

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/share/9GIACS4WX82#/screens)
2. [Content Document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/design/22-1995-stem-content-doc.md)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/11714

**Comment by delli-gatti-michael** [comment]
Tested by TestRail test case:
https://dsvavsp.testrail.io/index.php?/cases/view/287

**Comment by delli-gatti-michael** [comment]
Changes are now live in Staging

Cross-browser testing covered by this issue:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/5872

Accessibility testing covered by this issue:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/5869

**Comment by desireeturner** [comment]
UX review complete and feedback included in attachment: 
[1995 Form UX Reviewed on Staging 02.27.20.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4268474/1995.Form.UX.Reviewed.on.Staging.02.27.20.xlsx)
