### ISSUE TITLE
[Platform Support] Create "Platform Tech Support Team" Slack group for EVSS maintenance requests 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#51358]
## Description
Notices for planned EVSS maintenance are shared with Platform personnel in the #evss-prod channel. However, the "VSP Operations Group" Slack group is mentioned, but the team associated with that group handle is now defunct. 

The Platform Tech Support Team can respond to those requests but needs to be notified when there is upcoming maintenance. 

## Resources
- [Example notice in #evss-prod channel ](https://dsva.slack.com/archives/C8R3JS8BU/p1672323298697379)

## Acceptance Criteria
- [x] A "Platform Tech Support Team" Slack group is created 
- [x] Current Platform Tech Support Team members are added to the group 
- [x] A request is made that the EVSS notices use the new group handle and remove the old one 
- [x] The change is communicated w/ the Platform Tech Support Team
- [x] Maintenance windows (or other support responsibilities) documentation is updated to reflect the new Slack handle 

## How to configure this issue
- [x] _Team label assigned_
- [ ] _Epic assigned_ - N/A
- [x] _Estimated (points assigned)_
- [x] _Sprint assigned (once planned)_
- [x] _Team member(s) assigned_

**Comment by jhouse-solvd** [comment]
Requesting feedback from Platform Tech Support Team members in the following Slack thread: 

https://dsva.slack.com/archives/C02RLAUM2LV/p1672336494578799

**Comment by jhouse-solvd** [comment]
Group creation requested in ["slack-workspace-admin"](https://dsva.slack.com/archives/C01S729LX6X/p1672764018068379)

**Comment by jhouse-solvd** [comment]
The group has been created and it was tested today. I'll follow up soon to add support team members to the group and ensure the changes are communicated w/ a) the Platform Tech Support Team and b) EVSS stakeholders.

**Comment by jhouse-solvd** [comment]
I've sent a message to Bonnie requesting that she begin using the "platform-tech-support-team" group handle in Slack. I'll report back once she's confirmed and share the info with the team.

**Comment by jhouse-solvd** [comment]
I've sent a message to Bonnie requesting that she begin using the "platform-tech-support-team" group handle in Slack. I'll report back once she's confirmed and share the info with the team.

**Comment by jhouse-solvd** [comment]
Bonnie agreed to start using the new handle. I want to keep this ticket open to ensure I follow up w/ the Platform Tech Support team. 

I'll check back in the next day or two and close this.

**Comment by ph-One** [comment]
Just confirming everything mentioned in this ticket, and it looks good. Although I'm not positive I've seen @npeterson54 ack any of this

**Comment by npeterson54** [comment]
I'm not sure what it means to "ack" something, but I think this looks good.

**Comment by ph-One** [comment]
@npeterson54 to acknowledge something. I didn't see any response/reaction from you to the Slack posting(s) and wanted to be sure that you did (as part of my review process).

**Comment by jhouse-solvd** [comment]
I communicate this change w/ the Platform Tech Support Team in DSVA Slack [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1677522030461369?thread_ts=1672336494.578799&cid=C02RLAUM2LV) and updated the DevOps Support Responsibilities documentation [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2425552908/DevOps+Support+Responsibilities#Maintenance-Windows). 

This issue can be closed. But please feel free to improve the documentation or let me know if there's any way I can help.
