### ISSUE TITLE
[Letters App to Lighthouse] Create new endpoints

### ISSUE THREAD

**Issue by sortizsh** [department-of-veterans-affairs/va.gov-team#51375]
## Background

Split these up into individual tickets for each endpoint
Include testing as part of the acceptance criteria for each ticket

## Considerations
The main difference between the Lighthouse and EVSS versions of the index route is that Lighthouse's API combines the calls to letters and beneficiary into one call

**Comment by jerekshoe** [comment]
This has been split up into multiple tickets, so has been closed
