### ISSUE TITLE
Completed: Design Intent - Modernized Check In - Patient Check In, Appointments Consistent with VAOS Visual Design

### ISSUE THREAD

**Issue by CherylEvans** [department-of-veterans-affairs/va.gov-team#51399]
This ticket is for Platform tracking purposes only. There is no VFS action needed.

**Comment by shiragoodman** [comment]
@CherylEvans this has the wrong epic for Collab Cycle support. Please update to ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/50909 per the moderator responsibilities guidance.

**Comment by CherylEvans** [comment]
@shiragoodman Done! Thank you!

**Comment by shiragoodman** [comment]
also, @CherylEvans be sure to close the ticket. It should not remain open. I will close now but FYI for next time.

**Comment by CherylEvans** [comment]
@shiragoodman Thank you and I will do that next time!
