### ISSUE TITLE
[Analytics] My VA Domo dashboard: Update appointments information

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#51396]
### Background

In late December, the VA Online Scheduling Tool (VAOS) updated from V1 to V2. As such, I believe this affected how we are tracking analytics, as information for the appointments integration on My VA is no longer showing up in our Domo dashboard:

![image](https://user-images.githubusercontent.com/34068740/210384814-a8a9ddbd-06b3-430b-b396-52d2631645e0.png)

Can you look into why this is happening, and make any necessary updates so that we're able to see successful/failed `GETs` for appointment information now that we've moved to VAOS v2?

### Tasks

- [x] Investigate why appointment `GET` information stopped showing on My VA Domo dashboard (likely because of move to VAOS v2).
- [ ] Update Domo dashboard so appointment `GET` information shows up again.

**Comment by Samara-Strauss** [comment]
cc/ @ajakabcin for awareness

**Comment by michelle-dooley** [comment]
Hey @Samara-Strauss - we will look into this and get back to you.

**Comment by adamwhitlock1** [comment]
@Samara-Strauss and @ajakabcin I have updated the code and the success event has been deployed to staging.

When testing MyVa on staging I was also able to see the event fire, so after today's daily deploy we should start having events come in on prod as well.

![Screenshot 2023-01-17 at 11 40 34 AM](https://user-images.githubusercontent.com/8332986/212984381-99045771-2559-4001-81e6-f21305ad976b.png)

**Comment by Samara-Strauss** [comment]
Great, thank you! We can validate in the coming days to see if appointment data starts to show up again.

**Comment by ajakabcin** [comment]
Going to keep this open and move to next sprint for validation purposes only

**Comment by ajakabcin** [comment]
Reopening for validation from Analytics

cc @Samara-Strauss

**Comment by Samara-Strauss** [comment]
[Update from Slack](https://dsva.slack.com/archives/C909ZG2BB/p1674077921248229?thread_ts=1673030957.334439&cid=C909ZG2BB): Michelle is seeing events again in GA, but these are not pulling into Domo. @dorseypa1 is looking into the Domo issue.

**Comment by michelle-dooley** [comment]
@Samara-Strauss and @ajakabcin - Closing this ticket as Domo has been updated and is now pulling in the v2 appointment requests.

**Comment by Samara-Strauss** [comment]
Wonderful, thank you!!
