### ISSUE TITLE
Design Intent - Design Feedback - Modernized Check In Team - Patient Check In, Appointments Consistent with VAOS Visual Design

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#51409]
## VFS acceptance criteria
- [x] Let Platform know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [x] VFS team closes the ticket

## Thoughts/questions
- Thank you for the great artifacts!

## Feedback
- Practice areas will document their feedback following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). 

**Must:**
- Make sure all icons align with the [design system](https://design.va.gov/foundation/icons).
- The light weight card style is new. Please go through the [contributing to design process](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update). Look on the [Cards page](https://www.sketch.com/s/be292806-8dbf-4201-bfa7-0edbba103347) and "Candidates for testing - Desktop" artboard. Use one of those variations for the border color (v1) or border color plus drop shadow (v2). Matt doesn't have a strong preference.

**Should:**
- For previous and next, the [pagination](https://design.va.gov/components/pagination) styling is probably the closest match.

**Consider:**
- Consider moving up or adding a second action link above the schedule to help with the bounce rate.
- 
## Platform directions
- Remove the governance-team label
- Update "Issue Title"
- Link to collab cycle Request epic
- Add your feedback
- Remove the CC-Request label (only if you created the ticket using the New Issue link from the Collaboration Cycle Reviews board)
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review QA Only**: VFS PM, yourself (optional)

**Comment by zach-park** [comment]
Per discussion via slack with @humancompanion-usds @allison0034 @brianseek, the direction icon will be updated to "fa-road"  instead of "fa-directions" (which is not used at all currently on the vets-website).

**Comment by kristenmcconnell** [comment]
An [experimental design ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1419) for the card component variation was just submitted.

**Comment by zach-park** [comment]
Design intent feedback has been incorporated which includes the use of the latest card style and the DS iconography. The pagination styling issue is tabled and followed up by a separate ticket. Thank you.

**Comment by benbrasso-agile6** [comment]
@zach-park @ytsaoca are we adding a second action link to the pre-check-in intro page as part of this epic or are we handling it at a different time? 

> Consider moving up or adding a second action link above the schedule to help with the bounce rate.

**Comment by benbrasso-agile6** [comment]
Ya-ching has added an additional action link towards the top. [Conversation in this thread](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/50505).
