### ISSUE TITLE
Sidekiq HPA

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#51405]
## Description

Sidekiq in EKS is still being scaled on CPU. We need to scale on the queue size, which is a more accurate, and the recommended scaling approach.

We may need to create a [custom mapper via the datadog agent config](https://docs.datadoghq.com/developers/dogstatsd/dogstatsd_mapper/). In BRD we currently use a [custom statsd mapper ]( https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/vets-api/statsd-exporter-mapping.conf#L27-L31) which aggregates the necessary sidekiq scaling metrics.

[Currently we're lacking some of the CRDs](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/main/apps/datadog-agent/dev/values.yaml#L8)

**Comment by RachalCassity** [comment]
Sidekiq HPA metrics are currently being configured in this [PR](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/1257/files)

**Comment by RachalCassity** [comment]
This has been blocked to an error coming from the Datadog Agent. There has been an issue and support ticket issued to Datadog. We may have to look at alternative hpa solutions.

**Comment by LindseySaari** [comment]
Yesterday prod broke due to a change from Team 3. There's an issue with the Datadog Agent and it's not recognizing the regex. @RachalCassity opened an issue with Datadog. - [Slack thread](https://oddball.slack.com/archives/C045LCF8WU8/p1674662026629099)

**Comment by LindseySaari** [comment]
Rachal [created issue with Datadog for the datadog agen](https://github.com/DataDog/datadog-agent/issues/15251)t. Rachal put in a support claim as well. Team 3 is also diving into this with no progress. Devops also started to dig in. 

Still waiting to hear back from Datadog. Next steps are to explore other options

**Comment by laineymajor** [comment]
This is ideal, but we will give it one more sprint to hear back. Then we can look at other options options for sandbox.

This is not a blocking issue for our EKS work. It's a 'nice to have'

**Comment by laineymajor** [comment]
@RachalCassity can you link the message you sent to datadog folks via slack?

**Comment by laineymajor** [comment]
Rachal will have to reach out to dots va slack account as she has a ticket already started. We don't have the ticket info to follow-up on this. 

This ticket is blocking any sidekiq scaling + our current plan for load testing.

**Comment by LindseySaari** [comment]
I reached out to the [devops CoP](https://dsva.slack.com/archives/C04CYC4LMU6/p1676311792007309), and it appears that Oseas and Holden are doing some testing, but believe that the necessary config for the [Sidekiq metrics for HPA are in working order. ](https://dsva.slack.com/archives/C04CYC4LMU6/p1676312876373529)

**Comment by LindseySaari** [comment]
If we have any issues here, the [Datadog team suggests sending a flare](https://github.com/DataDog/datadog-agent/issues/15251#issuecomment-1428010449) to Datadog to help troubleshoot.

**Comment by laineymajor** [comment]
This will continue to next sprint as we are working with datadog to resolve issues.

**Comment by LindseySaari** [comment]
We can most likely[ use this query](https://vagov.ddog-gov.com/metric/explorer?start=1676393304416&end=1676396904416&paused=false#N4Ig7glgJg5gpgFxALlAGwIYE8D2BXJVEADxQEYAaELcqyKBAC1pEbghkcLIF8qo4AMwgA7CAgg4RKUAiwAHOChASAtnADOcAE4RNIKtrgBHPJoQaUAbVBGN8qVoD6gnNtUZCKiOq279VKY6epbINiAiGOrKQdpYZAYgUJ4YThr42gDGSsgg6gi6mZaBZnHKGniqyBrQcADWEMYAdHAiQWZQwHV4AEZwTploeBoIOk6R6shQGgBuGAC0czA4M-MCq4PDo9oU3X3jUZryGNnIM4ga8xjyEDwABD1Yd129-RNHJ3C7rwNDI2PvHggHgAXSornceEwoXCENUUIwMVK8WBYJAIywaByoGOWIQo2UUBwMF+GA0NUyiTQon6ckU5Rw1KgVJpTnoTGUIjcHjQwP4EHsmCwTjpORA1JESlBPD46Pk1IQAGEpMIYCgRFC0DwgA) to sum the queue size amongst the sidekiq deployments

**Comment by laineymajor** [comment]
Holden and Oseas made some updates to this. Have some metrics coming in for dev sidekiq, but not yet the higher environments... we are staying tuned for more info on the higher environments

**Comment by laineymajor** [comment]
Sidekiq overview - https://vagov.ddog-gov.com/screen/integration/45/sidekiq-overview?from_ts=1675962355592&to_ts=1676567155592&live=true

**Comment by laineymajor** [comment]
Lindsey to jump in and help oseas and holden with this... they are getting metrics for dev, but none of the higher environments

**Comment by LindseySaari** [comment]
Rachal is looking into issues with the metrics right now and anything > 60s is unavailable.
