### ISSUE TITLE
Remove IE11 from supported browsers list

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-team#51403]
### Description
IE11 support was deprecated in June 2022. It should be removed from the Supported Browsers list: https://depo-platform-documentation.scrollhelp.site/developer-docs/browser-support-policy

### Relevant URLs

https://learn.microsoft.com/en-us/lifecycle/products/internet-explorer-11

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8853

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/ie11-deprecation-banner/product-outline.md

**Comment by vbellissimo** [comment]
@jilladams Hi Jill, thanks for your content suggestions. The Platform Content team will review your request shortly for next steps.

**Comment by vbellissimo** [comment]
@jilladams This change has been made. Thank you for letting us know.

**Comment by vbellissimo** [comment]
@jilladams Hi Jill, when we made this content update, we re-published this page within this page hierarchy:

Developer docs / Quality Assurance (QA) / Browser Support Policy
https://depo-platform-documentation.scrollhelp.site/developer-docs/browser-support-policy

However, we're not actually sure if that's where it lived before. Do you happen to remember where in the website IA this page was?

Thank you.

cc @laucon

**Comment by jilladams** [comment]
Yep, thanks, that's the URL I had!
