### ISSUE TITLE
Inventory documentation for external audiences

### ISSUE THREAD

**Issue by tbaker1026** [department-of-veterans-affairs/va.gov-team#51418]
### **Description**

- We are looking to compile a list of documentation currently stored locally or in google docs which may be valuable to external audiences

### **Definition of Done**

- [x] Compile list of documentation 

- [x] Identify audience and potential value of documentation 

- [x] Determine if we want to post each piece of documentation and appropriate space to post it

**Comment by PSIEBENLIST** [comment]
[Draft audit summary](https://docs.google.com/document/d/19l0bJ7fYMapf_Z08SVGyVveTUznNdhCHnJh_otC9qbQ/edit#)
