### ISSUE TITLE
Add data validation for uniq SSNs on 10-10CG

### ISSUE THREAD

**Issue by kevinmirc** [department-of-veterans-affairs/va.gov-team#5141]
Make sure each SSN entered on the 10-10CG is unique.

**User Story**
I was troubleshooting some issues from CARMA and noticed a Veteran and their Secondary Caregiver had the same SSN.

**Comment by ala-yna** [comment]
moved to: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/13427
