### ISSUE TITLE
Lighthouse: Testing Vets-API Server from BRD to EKS (dev)

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#51413]
**Please complete by COB on 1.18.2023 (if not possible, message Lainey)**

**What’s happening?**
- As part of the testing process for vets-api server migration to EKS, we’ve tested healthcheck paths. Certain paths need to be fixed per testing. 
- We also need help testing endpoints (outside of the healthchecks). 

**Why is this important?**
- We want to verify expected behaviors from the endpoints, so the expected behavior(s) translate from BRD to EKS.
- It is important to have owners test their endpoints as you know these endpoints the best. This will also help speed up the process of moving from BRD to EKS.
---------------------------------------

**As a VFS/Platform Team, what do I need to do?**

**1. REVIEW [ENDPOINT OWNERSHIP DOCUMENT](https://docs.google.com/spreadsheets/d/1pj8D4cXtHta8VsO53Q3AUKBHwbjRmo3v0BJHUFuU-c0/edit#gid=1376638453)**
- [x] If there is anything that needs to change, this should be noted as a **comment** in [the document](https://docs.google.com/spreadsheets/d/1pj8D4cXtHta8VsO53Q3AUKBHwbjRmo3v0BJHUFuU-c0/edit#gid=1376638453).
- [x] **Within the comments of this ticket**, list out ALL of the endpoints associated your app(s) listed in Column A.
- [x] If the information is correct AND complete, please note in the comment section of **this ticket**
_Confirmed endpoints with Drew Fisher_

**2. VERIFY DEV SYNTHETIC TESTS VIA [DATADOG UI](https://vagov.ddog-gov.com/synthetics/tests?query=tag%3A%28%22team%3ATT1%22%29) and in [vets-api.yaml @ GitHub](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/datadog/catalog/synthetics/vets-api.yaml) [Adding alternative to DataDog in the comments of this ticket]**
- [ ] Verify the test from the inside of TIC firewall aka vfs-dev (if you do not have SOCKS access, please note in this ticket)
- [ ] Verify the test from the outside of TIC firewall aka revproxy-dev (going through the [Reverse Proxy](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474594232/Reverse+Proxy))
- [ ] Check for missing tests or duplicated tests
- [ ] Note any issues with lack of test data and/or users in the comments section of this ticket.

**3. IF NEED, PERFORM MANUAL TESTING**
- [ ] Setup team account in [TestRail](https://depo-platform-documentation.scrollhelp.site/developer-docs/create-a-test-plan-in-testrail)
- [ ] Upload test plans for manual testing
- [ ] Perform the testing and record test results in TestRail

**Comment by laineymajor** [comment]
@LindseySaari are you able to assign this ticket to Bryan Schofield? He's the TL I was directed to, but I'm unable to add him to the ticket...

**Comment by laineymajor** [comment]
Kayla Watanabe has sent the ticket to Drew. I asked her to also forward to Bryan. Still unable to assign tickets to VFS team members :(

**Comment by laineymajor** [comment]
Meeting with Lighthouse PMs today to review and discuss timeline.

**Comment by laineymajor** [comment]
While the preferred testing method for vets-api endpoints in EKS is Datadog Synthetics, VFS members don't currently have access to Datadog. To keep testing uniform and consistent, we are encouraging VFS teams to create a [Postman](https://www.postman.com/product/tools/) suite to hold their tests. Alternatively, you can record manual test run results in [Test Rail](https://dsvavsp.testrail.io/index.php?/dashboard).

**Comment by laineymajor** [comment]
![Screen Shot 2023-01-11 at 8.22.09 AM.png](https://images.zenhubusercontent.com/61ba3abb874c1c3d7c47bf01/8ce69eb7-ec1e-44ab-b087-1c3fc4c145ff)
![Screen Shot 2023-01-11 at 8.22.21 AM.png](https://images.zenhubusercontent.com/61ba3abb874c1c3d7c47bf01/91bb918b-54ff-4a4a-a661-580dc40483cd)
![Screen Shot 2023-01-11 at 8.22.38 AM.png](https://images.zenhubusercontent.com/61ba3abb874c1c3d7c47bf01/8d84e018-5c1e-463d-8a3f-24dd844524b8)

**Comment by laineymajor** [comment]
@laineymajor @RachalCassity look into smoke tests.

**Comment by klwatanabe** [comment]
Created https://vajira.max.gov/browse/API-22977 to track any work needed for the Claims API.

CC: @FonzMP
