### ISSUE TITLE
Create debt section for style guide

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#51434]
## Issue Description

As we create content briefs for different products and solidify the words and terms we use, we want to add this info to the style guide so that anyone working across VA.gov is using the same language. 

The first area we'll do this with is debt and payments. We'll add some content to the style guide and link off to the content brief for the full information. We can use the content brief as source material but we should figure out where this information should live in the style guide and how it should be set up for when we add other entries.

Content brief to work from: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/content-briefs/payments-debts-copay-bills.md

## Tasks
- [x] Create style guide entry
- [x] Review 
- [x] Publish

## Acceptance Criteria
- [x] New debts and payment section added to the style guide

**Comment by megzehn** [comment]
Here is a style guide entry draft:

https://dvagov-my.sharepoint.com/:w:/g/personal/megan_zehnder_va_gov/ETE_UlB_D-5MotbfOUiDjHEBDznR0aBSsM1gjHMuPmhq-A?e=vFdMTh

**Comment by megzehn** [comment]
**Update:** Randi, Beth, Danielle, and I met on 1/23 to discuss the structure.

Some notes from our call:

- We want to add a new page under "Specific topics and programs" that gives an overview of the new section. (I'll draft this based on what's currently in the content briefs). 
- For each section/topic, we want to highlight example content.
- In content briefs, we want to start adding a column that says "Ready for style guide?"  

 I made some minor tweaks to the [current draft](https://dvagov-my.sharepoint.com/:w:/g/personal/megan_zehnder_va_gov/ETE_UlB_D-5MotbfOUiDjHEBDznR0aBSsM1gjHMuPmhq-A?e=vFdMTh) based on our conversation. @DanielleThierryUSDSVA, when you get a chance, could you review the terms to make sure they're ready for the style guide? In the meantime, I'll work on a general overview page. Thank you so much!!

**Comment by RLHecht** [comment]
The team's work is complete on this issue. Closing!
