### ISSUE TITLE
Pull ICN to CSPIDs from accounts table

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#51442]
The MPI team has requested a one time snapshot of the current mappings VA.gov has stored of ICNs to CSPIDs. This is just a verification to see if we have any major discrepancies between what MPI currently has and what we have been storing over time.

- [ ] Draft query to produce the output, schedule the data query for off hours to minimize impact to production performance
- [ ] Store the export in a password protected compressed zip
- [ ] The export must be sent to Danny Reed

**Comment by bosawt** [comment]
@joeniquette Is this still a request? Can we close this?
