### ISSUE TITLE
MDT- Veteran personal info step- 508 accessibility

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#5144]
## User Story:
As a veteran with a disability rating of "x", I need to be able to still access the information displayed on the screen so that I can complete the first step of the MT ordering process.

## Tasks
- [ ] meet with the 508 Team to determine best accessibility practices
- [ ] apply 508 code elements to the page 

## Acceptance Criteria:
The veteran personal info step must meet 508 compliance standards
Please refer to the  [508 Checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/508-checklist.md)

**Comment by jenstrickland** [comment]
Please use the issue ticket template linked at https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/vsa-accessibility-review-process.md#development-reviews to request reviews.

**Comment by bradl3yC** [comment]
Axe check revealed only form system related heading nesting warnings and color contrast
