### ISSUE TITLE
Contact Center Review for [Benefits Team 1 - Supplemental Claim Form]

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#51452]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
Name: The Supplemental Claim Form (20-0995)

Description: The Supplemental claim form is the final decision review form to launch on VA.gov. Supplemental claims are filed when a claimant disagrees with a previous decision and has new and relevant evidence that may establish a theory of service connection. 

### Launch Date
Tentative launch date: 3/27/2023

### Version Number
Version 1

### Product Guide
[*Product guide link*](https://docs.google.com/document/d/1ZQb2QAcx9c5w-sDZEik3AK2Ru_KVA1EahzkUPOzmuhw/edit#)

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
Hi @saderagsdale. Did you have a link to the guide that you can drop into the ticket?

**Comment by saderagsdale** [comment]
@starlow00 Hey Steven, I'm prepping the collab cycle tickets for refinement with the team. I'll update the ticket and ping you when it's ready.

**Comment by saderagsdale** [comment]
@starlow00 @Kimberley2019 Hey Steven and Kimberley! This ticket for the contact center's guide for the Supplemental Claim form is ready for review. Can you take a look and let me know of any feedback? As a heads up, we're expecting a lot of potential submissions for this form. cc @clantosswett

**Comment by starlow00** [comment]
Thanks, @saderagsdale!

**Comment by starlow00** [comment]
Hi @saderagsdale. Guide looks good, sent to VEO for review.

**Comment by starlow00** [comment]
No changes from VEO. Current copy attached[https://app.zenhub.com/files/133843125/a16bb4d0-eaff-47e8-9b3a-485e2194f2d1/download](https://app.zenhub.com/files/133843125/a16bb4d0-eaff-47e8-9b3a-485e2194f2d1/download).
