### ISSUE TITLE
[Monitoring] List Datadog as an available tool for VFS Developers (by publishing info on the Platform Website)

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#51457]
## User Story
As a VFS developer, I need to know that Datadog is an available monitoring tool. 

## Background 
- The Platform Website is the primary location for VFS Developers looking for services and tools provided by the Platform
- Datadog is mentioned on the Platform Website under [Platform Tools](https://depo-platform-documentation.scrollhelp.site/getting-started/platform-tools), but the links do not inform VFS Developers where to look for access and usage info 

## Acceptance Criteria
- [x] VFS Developers can see that Datadog is an available monitoring tool on the Platform Website
- [x] There are links to documentation that explain
  - [x]  where to request access to the tool 
  - [x] where to look for info about how to use the tool 

## Refinement Guidance - Check the following before working on this issue: 
- [x] _Team label assigned ("platform-tech-team-2")_
- [x] _Epic assigned (if needed)_ 
- [x] _Estimated (points assigned)_
- [x] _Sprint assigned (once planned)_
- [x] _Team member(s) assigned_

**Comment by jhouse-solvd** [comment]
Note: The team pointed this as a 1, but ZenHub didn't allow that option at the time of estimation.

**Comment by jhouse-solvd** [comment]
@it-harrison - This relates to the discussion that we had today. I think this is one of the pages that we want to update: 

Platform Website > Getting Started > [Platform Tools](https://depo-platform-documentation.scrollhelp.site/getting-started/platform-tools)

If there are others that we need to update, will you please drop a note here on this issue with the name and link to the page? Thank you!

**Comment by jhouse-solvd** [comment]
We initially planned to pick this issue up this sprint but realized later that it needs to wait until after documentation is published as part of #51511

This will be a pretty quick one to implement, so I'm moving it to the next sprint and removing it from the current sprint.

**Comment by it-harrison** [comment]
Published to Platform documentation

**Comment by ph-One** [comment]
Confirmed. Closing.
