### ISSUE TITLE
Inconsistent date formatting on appointment confirmation pages

### ISSUE THREAD

**Issue by ryanshaw** [department-of-veterans-affairs/va.gov-team#51467]
## Summary
In various places within the appointment flows dates are displayed within inconsistent formatting. In some places `2022-01-03` is formatted as `January 02, 2023` and in other places it is formatted as `January 2, 2023`. This should be consistent throughout and the the preferred format is `January 2, 2023`.

## Steps to Reproduce
**Test User: cecil.morgan@id.me** 

This can be reproduced by using this test user and scheduling a first COVID-19 vaccination appointment and also by scheduling a directly scheduled appointment.

### Actual Result
![Screen Shot 2023-01-04 at 9 20 02 AM](https://user-images.githubusercontent.com/587812/210636572-f65ac719-523b-4016-944d-9ec078705252.png)
![Screen Shot 2023-01-04 at 9 19 40 AM](https://user-images.githubusercontent.com/587812/210636591-18fad335-4b0a-4c04-b71d-3a0274159f45.png)
![Screen Shot 2023-01-04 at 9 14 58 AM](https://user-images.githubusercontent.com/587812/210636617-aadb6165-1656-4abd-a838-b606ee1c5ea0.png)

### Desired Result
Dates should be formatted consistently with no leading 0 for the day number if it is < 10.

## Definition of Done
- [ ] Dates are consistently formatted when display
- [ ] All unit tests pass
- [ ] All e2e tests pass

**Comment by ldelacosta** [comment]
Validated in staging. No issues reported.![Screen Shot 2023-02-08 at 11.51.12 AM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/daf7f37a-f060-48fa-a990-3ee6a4abb222)
