### ISSUE TITLE
Replacing ForeSee with Medallia

### ISSUE THREAD

**Issue by ianMcCullough-ob** [department-of-veterans-affairs/va.gov-team#51473]
### Description
The [Platform tools page](https://depo-platform-documentation.scrollhelp.site/getting-started/platform-tools#Platformtools-Analyticsandinsightstools) makes reference to ForeSee, which has been sunsetted. We would like this to be replaced with Medallia.

### Relevant URLs
Platform tools page: https://depo-platform-documentation.scrollhelp.site/getting-started/platform-tools#Platformtools-Analyticsandinsightstools
Medallia: https://www.medallia.com/

**Comment by vbellissimo** [comment]
@ianMcCullough-ob Hi Ian, thanks for submitting this. So just to confirm, should we just delete the entire row that references ForeSee? And then in the Medallia row, we can change "Replacing ForeSee" to "Replaced Medellia". Does that sound good?

**Comment by ianMcCullough-ob** [comment]
@vbellissimo perfect!

**Comment by BSmolensky** [comment]
Completed. 
--
Brian Smolensky | Content Strategist
 

The So Company <http://thesocompany.com/> 
We make the government better.
Timezone: EST | GMT -4:00
802-356-0146 | ***@***.*** ***@***.***>  
SDVOSB | SBA 8(a) Certified | Digital Services Coalition Founding Member

**Comment by vbellissimo** [comment]
@ianMcCullough-ob The change has been made by @BSmolensky now, but it won't reflect live on the website until the end of the day today, after our deployment. I'll close this ticket once that is completed. Thank you both!

**Comment by ianMcCullough-ob** [comment]
Sounds great, thanks @vbellissimo!
