### ISSUE TITLE
SOCKS access for Ryan Johnson

### ISSUE THREAD

**Issue by rjohnson2011** [department-of-veterans-affairs/va.gov-team#51476]
### Your Name

Ryan Johnson

### Your Email

ryan.johnson@oddball.io

### Your Role and Team

Backend Engineer / Technical Support

### Product Manager (PM) name and email

Nathan Peterson

### Product Owner (PO) name and email

Andrea Hewitt

### Access Type Requesting

platform

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDrI53Ynsw3eDIxXaw6bkYV1XdTHLaEofoqAl4G0+HrYS4EplFLDM4l8lpwOmFCG+5VJve0qs3oXQ52Y/9ks/Uj8sJa3YYR+z7pJ9IUqa69htXylWOdtSWy767AptsSMbxoOszq3OPYzy12qunKccFwA3GZa9ukEOxDHYw3/sgJbkyw1iDyeQqvXRtVqsgZGAwoa4BaU0ePPdY7MCqXSg0+DfvUELFQegeyjUUSWzWTl6MFVJLXXQFBlPKSIA/ahKmtFjXmuEJe1Nj+tN7EvHBgutGY8izLsqJkWiAiP8IWASmRD00v00HsJ5WBWht0XuMPmYcwXhRw26a9Z1TGyPe3wyuwWsZP3DBGpbfa/DC/1Ua94r+9deabadYFMxlAVVLXWi3rLYcPVlpKBPRA8tojJ4XR5v1SPJ5UVBVcaC9jNYnUe8OxDAX12lgrmFGdQ0dpZwK9/S3BKhaSvuLjbszUq8wCMpR/exAAHXWgQAWBQIGv1Al7GhYFTvMd7nWKL0M= ryan@Ryans-MacBook-Air.local

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [x] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by little-oddball** [comment]
This has been fulfilled.
