### ISSUE TITLE
Manilla Power BI Report [1/11/2023]

### ISSUE THREAD

**Issue by jwowk** [department-of-veterans-affairs/va.gov-team#51497]

**Comment by Cmjones233** [comment]
Starting this dashboard

**Comment by Cmjones233** [comment]
finished and posted for review

**Comment by Cmjones233** [comment]
Add filter for current -30 days, note on dashboard about timeframe, date filter, and patient name/number

**Comment by Cmjones233** [comment]
completed

**Comment by Cmjones233** [comment]
completed
