### ISSUE TITLE
MDT- Veteran Personal info step- 3614-discovery-mock-up-of-medical-device-tool

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#5149]
## User Story:
As a frontend dev, I need to create  PR  so that I can ensure the code I produce is up to VA standards.

## Tasks
- [ ] Send out PR
- [ ] Apply recommendations. 

## Acceptance Criteria:
- [ ] GH branch is successfully deployed

## Next Steps
- TBD meet with Tze

## Dep/Blockers

**Comment by mr0sari0** [comment]
This PR was approved!
