### ISSUE TITLE
[Monitoring] Publish documentation that explains how VFS Developers can request access to Datadog 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#51509]
## User Story
As a VFS developer, I need to know how to request access to Datadog. 

## Background 
- The Platform Website is the primary location for VFS Developers looking for services and tools provided by the Platform
- Datadog is mentioned on the Platform Website under [Platform Tools](https://depo-platform-documentation.scrollhelp.site/getting-started/platform-tools), but the links do not inform VFS Developers where to look for access and usage info 

## Acceptance Criteria
- [x] The doc is ready to be published to the Platform Website
- [x] The documentation explains how to request access to Datadog 

## Refinement Guidance - Check the following before working on this issue: 
- [x] _Team label assigned ("platform-tech-team-2")_
- [x] _Epic assigned (if needed)_ 
- [x] _Estimated (points assigned)_
- [x] _Sprint assigned (once planned)_
- [x] _Team member(s) assigned_

**Comment by jhouse-solvd** [comment]
Mike Chelen suggested that for the read-only release, we - as platform personnel - send a bulk request to DOTS/ECC for all VFS teams. We still want to publish this documentation, but it might mean that VFS teams don't follow it for this first release. 

Some other call-outs: 
- The team as a whole will need to understand the publishing process
- This issue is one where we need to think about the potential for duplication across Confluence<->Platform Website

**Comment by it-harrison** [comment]
I tweaked and moved [Get Access to Datadog](https://vfs.atlassian.net/wiki/spaces/TT2/pages/2521989121/Get+Access+to+Datadog) and [Troubleshooting Access to Datadog](https://vfs.atlassian.net/wiki/spaces/TT2/pages/2521989185/Troubleshooting+Access+to+Datadog)

**Comment by jhouse-solvd** [comment]
This is looking good. I modified the AC, so the issue is not dependent on waiting for the actual publish steps. But we'll want to confirm once the doc is live on the Platform Website. 

For now, the docs are [HERE](https://vfs.atlassian.net/wiki/spaces/TT2/pages/2522054691/To+publish+on+Platform+Website).  

This ticket can be closed.
