### ISSUE TITLE
Adding Berni Xiong to DSVA Slack

### ISSUE THREAD

**Issue by sarahknoppA6** [department-of-veterans-affairs/va.gov-team#51515]
Please add Berni Xiong berni.xiong@agile6.com as a full member of the DSVA slack. She is the new Agile Six delivery manager for Authenticated Experience.

Please add her to #accountexp-authexp, #vfs-all-teams, #vfs-change-announcements

**Comment by sarahknoppA6** [comment]
@bernixiongA6

**Comment by LEHigley** [comment]
showing as a full member in slack
