### ISSUE TITLE
Digitize Form 21-0966 Intent to File a Claim

### ISSUE THREAD

**Issue by tbaker1026** [department-of-veterans-affairs/va.gov-team#51512]
### **Description**
This Form Is Used to Notify VA of Your Intent to File for the Compensation, Pension, Survivors Pension, and DIC Benefit(s). The Intent to File a claim process allows applicants additional time to gather all of the information and evidence needed to support their claim(s).  
Although this can be filed using [eBenefits](https://www.ebenefits.va.gov/ebenefits/homepage), this site maybe eventually retired. 

- Service Connected Claim
- Pension / Survivors Pension
- DIC Benefits

This form does not trigger a claim, only informs the VA of your intent to file a claim.  Would need to complete 21-526EZ(disability compensation) or 21-534EZ (Survivors Related Pension)
These forms above need to be filled out 1 year from the date of 21-0966, the intent to file a claim. This form establishes the start date of compensation of benefits if the Veteran or Claimant is awarded compensation based on the two applications above. 

This form is not required to complete the other applications, it does establish the effective date of the claim, so a Veteran can take their time in completing the lengthy application

### **User Story**
As Claimant/Veteran, I would like to submit my intent to file a claim to establish the start date of my claim for either disability compensation or Survivors Related Pension

**Comment by Mottie** [comment]
FYI: Form 526 calls a GET from a [vets-api endpoint `/intent_to_file`](https://department-of-veterans-affairs.github.io/va-digital-services-platform-docs/api-reference/#/form_526/getIntentToFile) to get a full list of ITFs. It then checks for an active compensation-type ITF, and if expired or not found, it will call that same endpoint with POST to create a new ITF ([source code](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/disability-benefits/all-claims/actions/index.js#L17)).

We have also been told to [include ITF in our Supplemental Claim form (20-0995)](https://github.com/department-of-veterans-affairs/va.gov-team/issues/52875), which is not yet released to production and is still being actively worked on. We're still discussing this addition as it may require some changes to the form if the decision is made (it may create a separate lane for 526 and Supplemental Claim compensation submissions)
