### ISSUE TITLE
[Epic] Logged-in IA/nav generative research

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#51519]
## Important documents

- [Research outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/research-and-analytics/2023-generative-logged-in-research/README.md)

## Current state 
We started by researching what we could do to surface My VA as the logged in experience 
We received some feedback concerning what might be lost by highlighting My VA in lieu of the new home page (loss of search bar, PACT Act not as prominently displayed), we've since started to explore what we could/should highlight as a result of that feedback and considering what links or items might need to be surfaced elsewhere on the site.

**Comment by mtcA6** [comment]
Closing this out as the [research](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/information-architecture/research-and-analytics/2023-generative-logged-in-research#research-outline-identifying-issues-and-challenges-people-have-finding-tasks-when-they-are-signed-in-to-vagov) has been completed. The opportunities called out from that can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/123eb1aaebf2273ffa9c744f1ddad976cd57d61f/products/identity-personalization/personalization-enhancements/opportunities.md#L4)
