### ISSUE TITLE
VAMC Data Visualization Needs Assessment

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#51522]
Identify the Pros and Cons of DOMO vs Medallia 
Set expectations and determine best approach

**Comment by ATMiddleton** [comment]
Awaiting additional information - will reach out to Sarkas to continue conversation.

**Comment by ianMcCullough-ob** [comment]
Met with Sarkis to review the initial VAMC dash design. Will present to VAMC team shortly.

**Comment by ianMcCullough-ob** [comment]
Might be able to close this ticket, determined Sarkis and his team will build the dash.

@ATMiddleton do we need this anymore?

**Comment by ATMiddleton** [comment]
Sarkis will build the dashboard and we will continue to monitor to conclusion.

**Comment by ATMiddleton** [comment]
@ianMcCullough-ob met with Sarkas to review the initial dash Designs.  Will present to VAMC team and will create another ticket for continuation.

**Comment by ATMiddleton** [comment]
Sarkas is building the dashboard.

**Comment by ATMiddleton** [comment]
Hey Ian, 

 

I updated the ticket and closed it.
