### ISSUE TITLE
Form 21-0966 Documentation

### ISSUE THREAD

**Issue by tbaker1026** [department-of-veterans-affairs/va.gov-team#51524]
### **Description**
This Form Is Used to Notify VA of Your Intent to File for the Compensation, Pension, Survivors Pension, and DIC Benefit(s). The Intent to File a claim process allows applicants additional time to gather all of the information and evidence needed to support their claim(s).

- Service Connected Claim
- Pension / Survivors Pension
- DIC Benefits

This form does not trigger a claim, only informs the VA of your intent to file a claim. The Veteran orClaimant would need to complete 21-526EZ(disability compensation) or 21-534EZ (Survivors Related Pension) applications to actually receive benefits. 
These forms above need to be filled out 1 year from the date of 21-0966, the intent to file a claim. This form establishes the start date of compensation of benefits if the Veteran or Claimant is awarded compensation based on the two applications above.

This form is not required to complete the other applications, it does establish the effective date of the claim, so a Veteran can take their time in completing the lengthy application

### **Supporting Documentation**
[User Story Documentation](https://docs.google.com/document/d/124xokXwr-y2IiQbZx5FQh-Pribfle-TKVXvS_fab5E4/edit#heading=h.y9ozwxt5etlx)

**Comment by megansiddle** [comment]
I already show this when filing out the 526EZ ![image.png](https://images.zenhubusercontent.com/620ad675b3191a70bf03f69d/400d0570-6fd7-4d04-ba01-6d02524bc8e6)

**Comment by tbaker1026** [comment]
Duplicate of #48
