### ISSUE TITLE
1010Team: Testing Vets-API Server from BRD to EKS (dev)

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#51532]
**What’s happening?**
- As part of the testing process for vets-api server migration to EKS, we’ve tested healthcheck paths. Certain paths need to be fixed per testing. 
- We also need help testing endpoints (outside of the healthchecks). 

**Why is this important?**
- We want to verify expected behaviors from the endpoints, so the expected behavior(s) translate from BRD to EKS.
- It is important to have owners test their endpoints as you know these endpoints the best. This will also help speed up the process of moving from BRD to EKS.
---------------------------------------

**As a VFS/Platform Team, what do I need to do?**

**1. REVIEW [ENDPOINT OWNERSHIP DOCUMENT](https://docs.google.com/spreadsheets/d/1pj8D4cXtHta8VsO53Q3AUKBHwbjRmo3v0BJHUFuU-c0/edit#gid=646146859)**
- [ ] If there is anything that needs to change, this should be noted as a **comment** in [the document](https://docs.google.com/spreadsheets/d/1pj8D4cXtHta8VsO53Q3AUKBHwbjRmo3v0BJHUFuU-c0/edit#gid=646146859).
- [x] **Within the comments of this ticket**, list out ALL of the endpoints associated your app(s) listed in Column A.
- [x] If the information is correct AND complete, please note in the comment section of **this ticket**

**2. VERIFY DEV SYNTHETIC TESTS VIA [DATADOG UI](https://vagov.ddog-gov.com/synthetics/tests?query=tag%3A%28%22team%3ATT1%22%29) and in [vets-api.yaml @ GitHub](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/datadog/catalog/synthetics/vets-api.yaml)**
- [ ] Verify the test from the inside of TIC firewall aka vfs-dev (if you do not have SOCKS access, please note in this ticket)
- [ ] Verify the test from the outside of TIC firewall aka revproxy-dev (going through the [Reverse Proxy](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474594232/Reverse+Proxy))
- [ ] Check for missing tests or duplicated tests
- [ ] Note any issues with lack of test data and/or users in the comments section of this ticket.

**3. IF NEED, PERFORM MANUAL TESTING**
- [ ] Setup team account in [TestRail](https://depo-platform-documentation.scrollhelp.site/developer-docs/create-a-test-plan-in-testrail)
- [ ] Upload test plans for manual testing
- [ ] Perform the testing and record test results in TestRail

**Comment by hdjustice** [comment]
@lihan for awareness and any questions you might have

**Comment by hdjustice** [comment]
The endpoints below are owned by the 10-10 team and is complete & correct:

- v0/health_care_applications/
- v0/health_care_applications/enrollment_status/
- v0/caregivers_assistance_claims
- v0/form1010cg/attachments

**Comment by lihanli** [comment]
the health check tests for `v0/health_care_applications/healthcheck` are not working in dev because [someone deleted the forward proxy we were using](https://github.com/department-of-veterans-affairs/devops/pull/11294/files)
@laineymajor should we switch to the staging forward proxy for the dev health care applications api?

**Comment by laineymajor** [comment]
Sorry --- This didn't come through in my email. Apologies for the delay! 
@LindseySaari what do you think about the above question re dev/staging...

**Comment by laineymajor** [comment]
@RachalCassity See question above from @lihanli ... What are your thoughts?

**Comment by RachalCassity** [comment]
@lihanli  Why were these deleted?

**Comment by RachalCassity** [comment]
@lihanli  ES Certs are no longer supported for dev and sandbox. Yes, please switch to staging for dev and sandbox.

**Comment by RachalCassity** [comment]
@lihanli Do these endpoints need to be tested in development or will you be switching to the staging forward proxy due to the ES certs not being supported in dev?

**Comment by lihanli** [comment]
@RachalCassity not sure why it was deleted, the person who deleted it wasn't from our team. according to this ticket your team needs the endpoints to be tested in dev? we do all our testing in staging. i made [a pr](https://github.com/department-of-veterans-affairs/devops/pull/12429) for switching the endpoints to the staging forward proxies, could i get it approved? thanks!

**Comment by lihanli** [comment]
staging forward proxy is not accessible in the dev environment, i will need to restore the HCA dev forward proxy

**Comment by laineymajor** [comment]
dev migration complete. good to close.
