### ISSUE TITLE
Identity Team: Testing Vets-API Server from BRD to EKS (dev)

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#51534]
**What’s happening?**
- As part of the testing process for vets-api server migration to EKS, we’ve tested healthcheck paths. Certain paths need to be fixed per testing. 
- We also need help testing endpoints (outside of the healthchecks). 

**Why is this important?**
- We want to verify expected behaviors from the endpoints, so the expected behavior(s) translate from BRD to EKS.
- It is important to have owners test their endpoints as you know these endpoints the best. This will also help speed up the process of moving from BRD to EKS.
---------------------------------------

**As a VFS/Platform Team, what do I need to do?**

**1. REVIEW [ENDPOINT OWNERSHIP DOCUMENT](https://docs.google.com/spreadsheets/d/1pj8D4cXtHta8VsO53Q3AUKBHwbjRmo3v0BJHUFuU-c0/edit#gid=25028748)**
- [x] If there is anything that needs to change, this should be noted as a **comment** in [the document](https://docs.google.com/spreadsheets/d/1pj8D4cXtHta8VsO53Q3AUKBHwbjRmo3v0BJHUFuU-c0/edit#gid=25028748).
- [x] **Within the comments of this ticket**, list out ALL of the endpoints associated your app(s) listed in Column A.
- [x] If the information is correct AND complete, please note in the comment section of **this ticket**

**2. VERIFY DEV SYNTHETIC TESTS VIA [DATADOG UI](https://vagov.ddog-gov.com/synthetics/tests?query=tag%3A%28%22team%3ATT1%22%29) and in [vets-api.yaml @ GitHub](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/datadog/catalog/synthetics/vets-api.yaml)**
- [ ] Verify the test from the inside of TIC firewall aka vfs-dev (if you do not have SOCKS access, please note in this ticket)
- [ ] Verify the test from the outside of TIC firewall aka revproxy-dev (going through the [Reverse Proxy](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474594232/Reverse+Proxy))
- [ ] Check for missing tests or duplicated tests
- [ ] Note any issues with lack of test data and/or users in the comments section of this ticket.

**3. IF NEED, PERFORM MANUAL TESTING**
- [ ] Setup team account in [TestRail](https://depo-platform-documentation.scrollhelp.site/developer-docs/create-a-test-plan-in-testrail)
- [ ] Upload test plans for manual testing
- [ ] Perform the testing and record test results in TestRail

**Comment by laineymajor** [comment]
@joeniquette please tag @RachalCassity  and myself when you have questions. Thanks!

**Comment by laineymajor** [comment]
@joeniquette @alyssagallion we are hoping this testing can be complete by COB 1.18. Please let us know if there is concern about meeting that timeline. Thanks!

**Comment by joeniquette** [comment]
tracking, we can meet that deadline.

**Comment by joeniquette** [comment]
All the endpoints associated with the Identity team from the document listed in this ticket:

- /v0/user
- /v1/sessions/*
- /auth/login/callback
- /sessions/new
- /sign_in/authorize

**Comment by joeniquette** [comment]
Looking to confirm that I should be adding tests to this list: https://vagov.ddog-gov.com/synthetics/tests?query=tag%3A%28%22team%3ATT1%22%29 for each of the endpoints that the Identity team is responsible for. The reason this is important is that we already have full monitoring of all identity related endpoints through our own monitoring. We did recently remove the dev ones because we didnt think we needed them, but we already have full coverage of staging and prod. 

It might be useful to add the tests we use to have for dev back in to complete the requirements of ensuring our services still work for EKS.

**Comment by joeniquette** [comment]
Dev external VA network test: https://vagov.ddog-gov.com/synthetics/details/3a4-cmz-jpf
Dev internal VA network test: https://vagov.ddog-gov.com/synthetics/details/jf9-x43-q4j 

Both of these tests hit the follow API endpoints and prove that they are up when the tests pass:

- /v0/user
- /v1/sessions/*
- /auth/login/callback
- /sessions/new
- /sign_in/authorize
