### ISSUE TITLE
Have everyone test the weird github link in the SOCKS Proxy doc

### ISSUE THREAD

**Issue by laucon** [department-of-veterans-affairs/va.gov-team#51533]
Samara and Lauren seemed to be able to acess the link "using [these instructions](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token)." in [Accessing Internal Tools (via SOCKS Proxy)](https://depo-platform-documentation.scrollhelp.site/getting-started/accessing-internal-tools-via-socks-proxy), but Jill got a broken link issue. Let's all try it together to see if it works and for whom.

**Comment by BSmolensky** [comment]
Done. I can access it too.

**Comment by taylojill** [comment]
It works!

**Comment by BSmolensky** [comment]
For me too. 
--
Brian Smolensky | Content Strategist
 

The So Company <http://thesocompany.com/> 
We make the government better.
Timezone: EST | GMT -4:00
802-356-0146 | ***@***.*** ***@***.***>  
SDVOSB | SBA 8(a) Certified | Digital Services Coalition Founding Member

**Comment by laucon** [comment]
This is funny because I knew I made this a zenhub ticket, but I didn't realize that it became a github ticket. lol
