### ISSUE TITLE
Adding Mark Viterna to DSVA Slack

### ISSUE THREAD

**Issue by regenauer-va** [department-of-veterans-affairs/va.gov-team#51540]
Good afternoon,

I am requesting Mark Viterna be added as a Multi-Channel User in the DSVA Slack workspace.

**Email**: 
viterna_mark@bah.com

**Channels**:
api-benefits-claims
team-ninjapigs

Thank you! :)

**Comment by LEHigley** [comment]
was showing as a member so reactivated their account as multi-channel guest 

both channels above are listed as private so could only add to #general
