### ISSUE TITLE
Change header levels on burial in a private cemetery page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#51547]
## Issue Description

Laura Flannery noted that we have an accessibility issue with header levels on our [Burial in a private cemetery](https://www.va.gov/burials-memorials/eligibility/burial-in-private-cemetery/) page. 

In the subway map, we skip a header level after the initial H2. We need to move each of the headers up one level. 

Original intake request for reference: #51541

## Tasks
- [x] Fix header levels
- [x] Copyedit (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] Live page has correct header level hierarchy

**Comment by megzehn** [comment]
Thanks for doing that, @RLHecht! Confirming that I reviewed and re-published the changes.

**Comment by RLHecht** [comment]
Changes are live. Closing!
