### ISSUE TITLE
Research Re-Assigning Tickets Syncing (Slack to GitHub)

### ISSUE THREAD

**Issue by powellkerry** [department-of-veterans-affairs/va.gov-team#51566]
**Description**
When you re-assign a ticket in Slack Channel it doesn't reassign in GitHub. This makes it hard to identify who owns a ticket without research or digging.

**Definition of Done**
The tasks below are complete.

**Tasks**
- [ ] Update workflow for reassign functionality to create/update labels for GitHub issues

**Comment by alyssagallion** [comment]
Being handled in this ticket: https://app.zenhub.com/workspaces/platform-tech-team-support-634ebbcc35e2bc0015b382fd/issues/zh/48 

Closing.
