### ISSUE TITLE
[Monitoring] Determine offboarding process for Platform/VFS Team members from Okta

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#51561]
## User Story
As a Platform Operator, I need to know how to offboard users from Okta. 

## Background 
- DOTS manages Okta and Datadog 
- **Platform Operators will need to request that users be offboarded from Okta by contacting DOTS via Jira ticket** 

## Resources
- Existing documentation in Confluence: "[Offboarding Team Member](https://vfs.atlassian.net/wiki/spaces/OT/pages/2097545323/Offboard+Team+Member)"
- [DOTS tools access portal](https://vajira.max.gov/servicedesk/customer/portal/1/group/3) 

## Acceptance Criteria
- [x] There is documentation for Platform Operators that explains how to offboard users from Okta.
- [x] Platform Operators know where to submit offboarding requests to DOTS/ECC (see resources above)
- [x] The [offboarding template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=analytics-insights%2C+Offboarding%2C+operations&template=offboarding-request.md&title=Offboarding+of+%5Bindividual%5D) is updated with AC for user removal from Okta

## Refinement Guidance - Check the following before working on this issue: 
- [x] _Team label assigned ("platform-tech-team-2")_
- [x] _Epic assigned (if needed)_ 
- [x] _Estimated (points assigned)_
- [x] _Sprint assigned (once planned)_
- [x] _Team member(s) assigned_

**Comment by jhouse-solvd** [comment]
According to an email from DOTS, Platform Operators can submit a ticket through Max.gov Jira, similar to the onboarding request. 

For the user that needs to be offboarded, provide their first name, last name, and email address, and DOTS can deactivate/delete their user accounts.

**Comment by jhouse-solvd** [comment]
We await communication from DOTS to clarify a few minor, specific details. 

Once we've heard back, this issue will be completed quickly.

**Comment by it-harrison** [comment]
This [page is published here](https://vfs.atlassian.net/wiki/spaces/OT/pages/2532508159/Offboarding+users+from+Okta).

Also, the offboarding template [has been updated](https://github.com/department-of-veterans-affairs/va.gov-team/pull/53768).

**Comment by jhouse-solvd** [comment]
@it-harrison - Thank you! I'll review this and #51701 together later today or tomorrow.

**Comment by jhouse-solvd** [comment]
Operational documentation for the Platform Tech Support team that explains how to offboard users from Okta has been added [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/2097545323/Offboard+Team+Member). 

This issue can be closed.
