### ISSUE TITLE
Benefits Team 1: Testing Vets-API Server from BRD to EKS (dev)

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#51565]
**What’s happening?**
- As part of the testing process for vets-api server migration to EKS, we’ve tested healthcheck paths. Certain paths need to be fixed per testing. 
- We also need help testing endpoints (outside of the healthchecks). 

**Why is this important?**
- We want to verify expected behaviors from the endpoints, so the expected behavior(s) translate from BRD to EKS.
- It is important to have owners test their endpoints as you know these endpoints the best. This will also help speed up the process of moving from BRD to EKS.
---------------------------------------

**As a VFS/Platform Team, what do I need to do?**

**1. REVIEW [ENDPOINT OWNERSHIP DOCUMENT](https://docs.google.com/spreadsheets/d/1pj8D4cXtHta8VsO53Q3AUKBHwbjRmo3v0BJHUFuU-c0/edit#gid=623772164)**
- [ ] If there is anything that needs to change, this should be noted as a **comment** in [the document](https://docs.google.com/spreadsheets/d/1pj8D4cXtHta8VsO53Q3AUKBHwbjRmo3v0BJHUFuU-c0/edit#gid=623772164).
- [ ] **Within the comments of this ticket**, list out ALL of the endpoints associated your app(s) listed in Column A.
- [ ] If the information is correct AND complete, please note in the comment section of **this ticket**

**2. VERIFY DEV SYNTHETIC TESTS VIA [DATADOG UI](https://vagov.ddog-gov.com/synthetics/tests?query=tag%3A%28%22team%3ATT1%22%29) and in [vets-api.yaml @ GitHub](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/datadog/catalog/synthetics/vets-api.yaml)**
- [ ] Verify the test from the inside of TIC firewall aka vfs-dev (if you do not have SOCKS access, please note in this ticket)
- [ ] Verify the test from the outside of TIC firewall aka revproxy-dev (going through the [Reverse Proxy](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474594232/Reverse+Proxy))
- [ ] Check for missing tests or duplicated tests
- [ ] Note any issues with lack of test data and/or users in the comments section of this ticket.

**3. IF NEED, PERFORM MANUAL TESTING**
- [x] Setup team account in [TestRail](https://depo-platform-documentation.scrollhelp.site/developer-docs/create-a-test-plan-in-testrail)
- [ ] Upload test plans for manual testing
- [ ] Perform the testing and record test results in TestRail

**Comment by jacobworrell** [comment]
@kjduensing please write tickets for our team to guide our work around this initiative.

**Comment by laineymajor** [comment]
@kjduensing please tag me and @RachalCassity if questions come up!
I'd also love to see what tickets you write from this, per Jacob's comment above.... maybe I can make those tickets for future teams. Thanks!

**Comment by laineymajor** [comment]
@kjduensing additional info per our conversation about DataDog access...

While the preferred testing method for vets-api endpoints in EKS is Datadog Synthetics, VFS members don't currently have access to Datadog. To keep testing uniform and consistent, we are encouraging VFS teams to create a [Postman](https://www.postman.com/product/tools/) suite to hold their tests. Alternatively, you can record manual test run results in [Test Rail.](https://dsvavsp.testrail.io/index.php?/dashboard)

**Comment by laineymajor** [comment]
![Screen Shot 2023-01-11 at 8.22.09 AM.png](https://images.zenhubusercontent.com/61ba3abb874c1c3d7c47bf01/fd4b3f4e-8650-40f8-bc51-7d9066d64c35)
![Screen Shot 2023-01-11 at 8.22.21 AM.png](https://images.zenhubusercontent.com/61ba3abb874c1c3d7c47bf01/1c4a4773-1f1f-4339-aaed-8285893aefc0)![Screen Shot 2023-01-11 at 8.22.38 AM.png](https://images.zenhubusercontent.com/61ba3abb874c1c3d7c47bf01/ed58ad43-954b-44c4-9d54-6d04077294f0)

**Comment by laineymajor** [comment]
@kjduensing we're hoping this testing can be complete by COB 1.18...acknowledging y'all have a LOT of endpoints, please let me know if that's not feasible. We can adjust accordingly.

**Comment by kjduensing** [comment]
@laineymajor and @RachalCassity, I understand y'all would prefer testing to be complete 01/18. Does this mean the migration has already been made? What's the status of the migration if not?

**Comment by kjduensing** [comment]
Also, @jacobworrell, the [endpoints listed in the ownership doc](https://docs.google.com/spreadsheets/d/1pj8D4cXtHta8VsO53Q3AUKBHwbjRmo3v0BJHUFuU-c0/edit#gid=623772164) should be cross-squad.

@jerekshoe, please take a look at the ownership doc - does anything look off to you? 

It would be great to use that doc as a source of truth.

**Comment by laineymajor** [comment]
![Screen Shot 2023-01-13 at 7.56.35 AM.png](https://images.zenhubusercontent.com/61ba3abb874c1c3d7c47bf01/4b1b4e0f-2638-4607-8853-7f5c266f80c9) @kjduensing

**Comment by saderagsdale** [comment]
@laineymajor @jacobworrell Hey both - please let me know if you need anything from squad 2 on this.

**Comment by jacobworrell** [comment]
@kjduensing can you link to the squad 1 specific tickets that relate tot his work?

**Comment by laineymajor** [comment]
It is up to you all to determine how to best test your endpoints. We acknowledge that you all know them way better than we do... we just want (a) confirmation that they've been tested (b) confirmation that they are behaving as expected... or if they are NOT, and (c) some sort of documentation for testing.

We will be dialing up staging traffic towards the beginning of February. Ideally, testing for dev is complete before beginning testing in staging. That being said, if these need to happen simultaneously, that's a-ok! Again... y'all know your endpoints and how to test them best!

We are working on a schedule for the remainder of testing. Should be ready next week! I'll be sure to send to all the PMs :) 

Thanks!

**Comment by laineymajor** [comment]
EKS is running in dev @kjduensing 

I am also trying to determine a better mechanism of tracking endpoint ownership & consumption. I will share this out as I have it!

**Comment by kjduensing** [comment]
@jacobworrell @laineymajor Here are the tickets related to Squad 1:
- #52328
- #52324
- #52323
- #52325
- #52326
- #52322
- #52320
- #52319

**Comment by laineymajor** [comment]
dev migration complete. good to close.
