### ISSUE TITLE
Supplemental Claims | Draft PACT recruitment plan

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#51576]
- [x] Draft plan in [platform format](https://github.com/department-of-veterans-affairs/va.gov-research-repository/blob/master/research-plan-participant-criteria-update%202.md)
- [x]  Submit as part of research review
- [x]  Add to original research plan md file

**Comment by saderagsdale** [comment]
Can be done by EOD 1/19
