### ISSUE TITLE
Remove call to V0 cc eligibility call in V2

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#51570]
## Summary
In V2, we're still making calls to the V0 cc eligibility endpoint. We already make a call to `/vaos/v2/scheduling/configurations?cc_enabled=true` to get cc eligibility info for v2. We need to remove this addition v0 call.

## Steps to Reproduce
**Test User:**  Judy Morrison.
- Log into VAOS
- Click on schedule appointment.
- Click a type of care
- Check network logs for call.

### Actual Result
- a call to the V0 cc eligibility endpoint is made.
![Screen Shot 2023-01-06 at 12.55.51 PM.png](https://images.zenhubusercontent.com/62279c01c38e1718c9102bee/35d4c57a-c22a-4c3e-96ce-5f462134620a)
### Desired Result
No calls to the V0 cc eligibility endpoint is made. We only make a call to `/vaos/v2/scheduling/configurations?cc_enabled=true` for cc eligibility info.

## Definition of Done
- [ ] Desired result is achieved

---

**Comment by simiadebowale** [comment]
@ldelacosta - This is ready for validation.

**Comment by ajmagdub** [comment]
Checked Datadog and Vets API is no longer seeing any calls to the V0 CC eligibility controller.

**Comment by ldelacosta** [comment]
No issues reported. Closing out the ticket.
