### ISSUE TITLE
Supplemental Claims | Draft PACT conversation guide

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#51575]
Initial drafting of conversation guide and task scheme for testing the PACT prototype for Supplemental Claims.

Tasks:

- [x]  Draft conversation guide in collaboration with product
- [x]  Create markdown file for research folder
- [x]  Submit with research plan for research review

**Comment by saderagsdale** [comment]
Can be done by early next week.

**Comment by saderagsdale** [comment]
Working through scenarios to test our hypotheses.

**Comment by eileen-coforma** [comment]
Submitted for review 2 days ago. Research review has been postponed until OAR gives approval or edits on copy.
