### ISSUE TITLE
Supplemental Claims | Draft PACT research plan

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#51574]
Initial drafting of plan to test the PACT prototype of Supplemental Claims.

- [x]  Draft of Supplemental Claims PACT research plan
- [x]  PACT research folder created
- [x]  Markdown file ready to share for research review

**Comment by eileen-coforma** [comment]
Initial draft started in [Google Docs](https://docs.google.com/document/d/1C4-noJiq5qpbb5OVnAutX5s4TqWTNo9i2ruZoi0VueU/edit?usp=sharing). Will move to Github when ready.

**Comment by saderagsdale** [comment]
Can be done by EOD 1/19

**Comment by eileen-coforma** [comment]
[Github markdown](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Supplemental-Claims/Research/1222-PACT-Act/research-plan.md) for research plan is here done.
@saderagsdale take a look at the recruitment criteria + screener and see if it encompasses what we talked about.

**Comment by saderagsdale** [comment]
@eileen-coforma Thanks for pulling this together! Looks great. Do you have any questions for Perigean about the recruit? They have an open session on Monday.
