### ISSUE TITLE
[Monitoring] Change Communication Plan: Send the Pre-Change Slack Communication for the release of Read-Only access to Datadog for VFS Teams

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#51581]
## Description 
Ensure that changes are communicated with VFS Teams upon release of Datadog as an available Platform Monitoring tool. 

## Background 
- The Platform Service Design Team provides a "[Change Communication Plan](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/2317647898/Change+Communication+Plan)" that helps Platform teams notify VFS Teams and stakeholders of new changes. 
- This plan should serve as a guide when communicating the release of Datadog to VFS teams 

## Acceptance Criteria
- [x] The Pre-Change Slack Communication is sent one week before the release

## Refinement Guidance - Check the following before working on this issue: 
- [x] _Team label assigned ("platform-tech-team-2")_
- [x] _Epic assigned (if needed)_ 
- [x] _Estimated (points assigned)_
- [x] _Sprint assigned (once planned)_
- [x] _Team member(s) assigned_

**Comment by jhouse-solvd** [comment]
I'm starting this issue now. I will post a link to the change communication plan once created. :)

**Comment by jhouse-solvd** [comment]
See [Change Communication Plan - Read-Only (RO) access to Datadog for VFS Teams #50774](https://vfs.atlassian.net/wiki/spaces/TT2/pages/2530836481/Change+Communication+Plan+-+Read-Only+RO+access+to+Datadog+for+VFS+Teams+50774) in Confluence for the proposed communication(s).

**Comment by oseasmoran73** [comment]
Something to keep in mind once we get to the `write` phase for VFS, is platform should assign the perms around dashboard they do not wish to modify

![image](https://user-images.githubusercontent.com/10648480/218819155-b288c822-dd5a-4918-a86e-e441036d8d61.png)

**Comment by jhouse-solvd** [comment]
Sent! _See [HERE](https://dsva.slack.com/archives/C03R5SBELQM/p1676404718122259)_

This issue can be closed.

**Comment by jhouse-solvd** [comment]
> Something to keep in mind once we get to the `write` phase for VFS, is platform should assign the perms around dashboard they do not wish to modify
> 
> ![image](https://user-images.githubusercontent.com/10648480/218819155-b288c822-dd5a-4918-a86e-e441036d8d61.png)

@oseasmoran73 - Yes, great call out. See #47066 for tracking. Feel free to drop a note on that issue with other thoughts or feedback. Thank you, sir!
