### ISSUE TITLE
MDT- 3614-discovery-mock-up-of-medical-device-tool deploy to master

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#5158]
## User Story:
As a frontend dev, I need to create  PR  so that I can ensure the code I produce is up to VA standards.

## Tasks
- [ ] Send out PR
- [ ] Feature flags 
- [ ] Apply recommendations. 

## Acceptance Criteria:
- [ ] GH branch is successfully deployed

## Next Steps
- TBD meet with Tze

## Dep/Blockers

**Comment by mojaray2k** [comment]
@wygonikGCIO What is this ticket for?
