### ISSUE TITLE
Configure Sentry to send emails about claims status tool

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#51591]
## Background
We need to configure Sentry to send us emails when there are errors with the claims status tool. This will help identify an issues that come up as part of our transition from EVSS to Lighthouse for benefits claims data

## Tasks
- [x] Send list of FE URLs to Platform Support to add to ownership list in Sentry

## Acceptance Critieria
- [ ] Emails are sent to members of the team when there are frontend Sentry errors

**Comment by jerekshoe** [comment]
@samcoforma if I remember correctly you did this for the DDL previously. Could I get you to fill out the tasks for this?

**Comment by samcoforma** [comment]
https://dsva.slack.com/archives/CBU0KDSB1/p1674762767488329
