### ISSUE TITLE
Auto export the results from the inbound messages report to CSV daily

### ISSUE THREAD

**Issue by manalo-soco** [department-of-veterans-affairs/va.gov-team#51602]
Submitted by:
Hayden.Matz@va.gov, Station 534

We are exploring the option of having escalations identified from patient responses be noted in the patient’s chart as a view alert for their care team to respond to. This would circumvent staff needing to monitor the VEText portal for patients that need to be called.

We want to automatically export the results from the inbound messages report to CSV daily, preferably every 12 hours, to a network drive. What current options do we have to automatically export CSV results from the inbound messages report?

We would like the patient’s IEN, ICN, or SSN on the inbound messages report that we export to CSV to a network drive daily.

Also, we would like one clinic to have the ability to send 8 messages. This would alleviate an issue where a veteran trying to unenroll from messages would need to send the unenroll message twice to two different messages.

**Comment by manalo-soco** [comment]
Submitted by:
Hayden.Matz@va.gov | Ralph H. Johnson VA Medical Center 

We are exploring the option of having escalations identified from patient responses be noted in the patient’s chart as a view alert for their care team to respond to. This would circumvent staff needing to monitor the VEText portal for patients that need to be called.

 

We want to automatically export the results from the inbound messages report to CSV daily, preferably every 12 hours, to a network drive. What current options do we have to automatically export CSV results from the inbound messages report?
 

We would like the patient’s IEN, ICN, or SSN on the inbound messages report that we export to CSV to a network drive daily.

Also, we would like one clinic to have the ability to send 8 messages. This would alleviate an issue where a veteran trying to unenroll from messages would need to send the unenroll message twice to two different messages.

**Comment by michelle-dooley** [comment]
@manalo-soco - We cannot report on nor due we have access to PII including inbound messages that could contain PII.  This is not something Analytics & Insights can assist with.

**Comment by jwowk** [comment]
Closed due to no longer needing as part of readmission project
