### ISSUE TITLE
[EVSS to Lighthouse] for claim status configure Test Rails for automated Cypress testing

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#51610]
## Background

We should set up Cypress tests within Test Rails. 

## Steps

- [ ] Enable cypress testing in TestRails by reaching out to appropriate gatekeepers
- [ ] Create test cases within TestRails
- [ ] Make sure we have tests that correspond to test cases
- [ ] Run tests
- [ ] Circulate test results

**Comment by Mayuresh0072** [comment]
@goldenmeanie @dillo @jjulian Hello, I want to work on this issue , Please assign me.
