### ISSUE TITLE
[EVSS to Lighthouse] FE Unit tests for claim status end points

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#51612]
In switching to use Lighthouse in place of EVSS, we need to have confidence that our functionality has remained unchanged. 

There are 2 phases:
1. Implement the response manipulation and run all the claims-status tests to ensure everything still works as expected 
2. Add/Modify frontend unit tests
3. If there are any additional migration steps that are more than just implementation details, write tests for them.

Acceptance Criteria:
- [ ] We have greater than 75% unit test coverage in [all categories for claim-status on the coverage report page](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/unit-test-coverage-report/)

Supporting docs:
[QA Standards platform documentation](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-unit-test-coverageUnitTestCoverage)

**Comment by jerekshoe** [comment]
@kjduensing The current plan is to pass through exactly what we get from Lighthouse to the frontend. This will require significant adjustments to the frontend code

**Comment by kjduensing** [comment]
Thanks @jerekshoe. What's the reason behind a straight pass-through?

**Comment by kjduensing** [comment]
After talking with @jerekshoe and @samcoforma, passing through LH responses to the FE eliminates some tech debt since it requires less data manipulation.
