### ISSUE TITLE
MDT- Address Step- mock up default address/email. 

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#5162]
## User Story:
As a veteran, I need to have to see my default address & email so that I can confirm the information.

## Tasks
- [x] Create a high fidelity mockup of the default Veteran contact details page
Upload mockup to Invision and indicate initial focus point as a comment

## Acceptance Criteria:
Mockup aligns with VA.gov’s design system
The Veteran’s default mailing address is displayed 
The Veteran’s default email address is displayed
The screen’s initial focus is incorporated
Sketch artboards are uploaded to Invision and linked in this ticket as a comment

## Next Steps
- Editing Email and Address 
- Creating a forwarding address
## Dep/Blockers

**Comment by rileyorr** [comment]
Prototype: [Desktop](https://vsateams.invisionapp.com/share/Q7VVWGZUG4N)
Things to consider:
- For the default, I designed for the _happy path_, so it can be assumed that all the Veteran's data would be pre-filled
- The Veteran can edit any text input field 
- All fields are required unless noted as optional 
- I've seen a few ways that the address section has been laid out on other forms and I am proposing this layout to VSP. I may need to update this screen based on feedback. 

@mr0sari0 & @mojaray2k pls review and let me know if you wanna meet or have any questions!
