### ISSUE TITLE
Design indicator for optional fields/questions

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#51625]
## Task Description
Design an indicator that shows when a question, or a field, is optional. This is specific to a one-thing-per-page user flow.

## References
* [This slack thread](https://dsva.slack.com/archives/C01DBGX4P45/p1672951140102929)
* [Design explorations WIP](https://www.figma.com/file/yknNdT9fcgBNb8mvz3cGIu/Optionality-Markers-Pattern?node-id=2%3A4)

## Acceptance Criteria
- [ ] Design file with optional indicators
- [ ] Experimental design ticket created

**Comment by outerpress** [comment]
@outerpress break out using the heading as the question label into a separate ticket

**Comment by outerpress** [comment]
Merged into #52050, closing

**Comment by ldelacosta** [comment]
Moved this ticket to this epic Improving the user flows in Appointments #42663
