### ISSUE TITLE
Adding Tim Wright to DSVA Slack

### ISSUE THREAD

**Issue by seheart** [department-of-veterans-affairs/va.gov-team#51629]
# Description

Please add Tim Wright as a full member.

Tim is a Managing Software Engineer for Ad Hoc on the VA Flagship mobile app. Email is [tim.wright@adhocteam.us](mailto:tim.wright@adhocteam.us).

**Comment by CoryTrimmUSDS** [comment]
Evening Seth, please update the link that you used to create this issue to remove @eunicegar from the auto-assign list. The proper link is below - 

https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=LEHigley&labels=Slack+Request&template=slack-request-template.md&title=Adding+%5Bindividual%5D+to+DSVA+Slack

**Comment by LEHigley** [comment]
tim was showing as a member already so just reactivated his account
