### ISSUE TITLE
AWS access for Elwood Gary

### ISSUE THREAD

**Issue by elwoodva** [department-of-veterans-affairs/va.gov-team#51634]
### COR Name

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative Name

Other - please specify in 'Additional Notes'

### Your Name

Elwood Gary

### Your Email

kenneth.gary@va.gov

### Team, Role, and Company of the target individual

MHV Secure Messaging, Software Engineer, By Light Professional IT Services

### Product Manager (PM) name and email

Lichelle Bain lichelle.bain@va.gov

### Product Owner (PO) name and email

Patricia Henry - Patricia.Henry@va.gov

### Desired AWS Access

Requesting the SSMApplicationLowerEnvironmentAccess policy, and to be added to the existing IAM group dsva-vfs-developers

### Access Expiration

ongoing

### Additional Notes

COR: Sean Good
Vendor Onboarding Representative: Kenneth Brown
Access Expiration: Need ongoing access to upstream data APIs in lower environments for VFS development activity

### User must exist in a roster before AWS access can be granted

- [X] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [X] Comment in this issue saying which roster the user is listed in.

**Comment by little-oddball** [comment]
VFS Team Roster

**Comment by little-oddball** [comment]
@elwoodva - I am hopping in to try and help w/ these items. Our Gov't PO had a transition and we now require to have the eQIP transmittal date provided. Would you be able to work with your PO/PM to provide that? Once that has been applied to the ticket I push move it forward to our Gov't PO for a review/approval. Thanks and sorry for the delay and any inconvenience .

**Comment by elwoodva** [comment]
1/26/2023

**Comment by little-oddball** [comment]
Above is meant to be eQIP date.

**Comment by elwoodva** [comment]
That is correct.  I'm in the middle of a new eQIP investigation right now.  That's the date we just submitted it.  I got that date from Kenneth Brown.  Is that the correct information you need?

**Comment by little-oddball** [comment]
@BillChapmanUSDS - Is the thought here we need to wait for the eQIP to come back? I thought the process was around is the transmittal date not the return but want to check with you.

**Comment by little-oddball** [comment]
@BillChapmanUSDS - Just following up on this one... Are we good to proceed here or is there additional information, etc. you need?

**Comment by BillChapmanUSDS** [comment]
Sorry about this one, I removed the awaiting approval but did not say "I approve" in a comment. 
I approve of this access as requested.
