### ISSUE TITLE
Redirect Request: Find a VA form search pages

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#5163]
### Instructions
- Requests for redirects need to be submitted **AT LEAST** 2 weeks in advance.  Some redirects take significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation of the redirect to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders of pending redirect.  

### Description
*As part of the redesign of Find a VA form search experience, the search, search results, and associated pages (viewer, help, contact) need new URLs and the current live .asp pages need to be redirected to the new MVP experience. 

This ticket does NOT include redirects for the form detail landing pages; we will submit a separate ticket for those because they are extensive and do not need to launch at the same time as the search page.*

Reference epic: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/1632 

### Requestor Info
*Public website team: Jen Lee, PO; Nick Sullivan, FE*

### Implementation Date
Date new URL(s) will be live: *TBD*

Please indicate when the redirect(s) needs to be implemented"
- ~[x] On the same date the new URLs launch~
- [ ] Redirect according to release plan here:  [TBD @stephorkandatx }

**The requesting team is responsible for notifying the group working on this issue if the target date changes. They are also responsible for ensuring the destination URLs are implemented correctly and live at the time the redirects are deployed.**

### Redirects Needed

Current URL  |  Redirect Destination (new URL)
---  |  ---
https://www.va.gov/vaforms/ <br> *This redirect cannot be greedy and should only be for this exact URL* | https://www.va.gov/find-forms/
https://www.va.gov/vaforms/search_action.asp <br> *Redirect should capture all parameter versions* | https://www.va.gov/find-forms/
~https://www.va.gov/viewer.htm~ | ~https://www.va.gov/find-forms/~
https://www.va.gov/vaforms/help.asp | https://www.va.gov/find-forms/
https://www.va.gov/vaforms/contact.asp | https://www.va.gov/find-forms/
https://www.va.gov/vaforms/Default.asp | https://www.va.gov/find-forms/

### Steps to complete
- [x] Above information is provided and issue is tagged and assigned appropriately - @lunascoop @ncksllvn @stephorkandatx 
- [x] All appropriate VA stakeholders are notified of pending redirect - @jenniferlee-dsva 
- [x] Redirect request is vetted and documented and implementation plan is clear - @mnorthuis @meganhkelley 
- [x] Request is assigned to appropriate team for implementation - *@ Content & IA team*
- [x] Implementation team completes work - *@ Implementation team*
- [x] Implementation pushed live and redirect is validated in production - *@ all*
- [x] Ticket is closed - *@ requesting team*

**Comment by jenniferlee-dsva** [comment]
@mnorthuis - I'm creating this ticket to keep in backlog, so we don't lose it; but will submit to you when new URLs are ready and we're closer to knowing launch date.

**Comment by ncksllvn** [comment]
Crosslinking to the IA review - https://github.com/department-of-veterans-affairs/va.gov-team/issues/3887

**Comment by ncksllvn** [comment]
@mnorthuis there is another page, https://www.va.gov/vaforms/Default.asp. Are interested in that at all?

**Comment by mnorthuis** [comment]
@ncksllvn yes, I'm assuming we want that redirected as well so I went ahead and added it to the top list.

**Comment by jenniferlee-dsva** [comment]
@ncksllvn and @mnorthuis - I believe that URL is already on the list ^ in my original ticket. (??) If it's missing, please add it to the list in the original ticket request at the top, so we have a consolidated list for Mikki. Thank you!

**Comment by mnorthuis** [comment]
@jenniferlee-dsva I already added it!

**Comment by stephorkandatx** [comment]
@mnorthuis We are wrapping up final pieces of feedback and are approaching launch. Can we add this ticket to the queue?

**Comment by mnorthuis** [comment]
Reviewed the above URLs and this is ready to be implemented.

**Comment by mnorthuis** [comment]
@jenniferlee-dsva I did have a question on https://www.va.gov/viewer.htm.

I don't believe this content is covered in the new page, so are we prepared to retire this?

**Comment by jenniferlee-dsva** [comment]
Replying to @mnorthuis q above about the viewer page: 

Yes, it's okay to redirect/retire it. The page is very old (last updated July 2014); and so far, we have not encountered any forms inside the forms DB that requires Flash, QT, Visio, Excel, Word, PPT, or RealPlayer.

**Comment by jenniferlee-dsva** [comment]
Per this Slack thread - we can implement these redirects on Thursday 6/25. 

I've already been communicating with forms working group stakeholders, so I'll give them the final redirect heads up with the 6/25 Thursday date. 

@stephorkandatx @ncksllvn - If you can confirm here if that date can work, much appreciated! 

@lunascoop  - no action item for advance email coms for you here.

**Comment by stephorkandatx** [comment]
@ncksllvn I've pulled this into the sprint so we can tackle this Thursday 6/25.

**Comment by jenniferlee-dsva** [comment]
Updated the ticket ^ - removing the viewer page for redirecting, per Kevin Reid who says that page is not 'owned' by the forms managers. https://www.va.gov/viewer.htm 

I'm trying to track down who the 'owner' is, but in the meantime, let's remove it from this week's redirects. I'll create another ticket just for the viewer page, if needed at a later date. @ncksllvn @stephorkandatx

**Comment by jenniferlee-dsva** [comment]
Thx @ncksllvn ! I've validated the links and redirects look good.  Thank you @mnorthuis. Have let the stakeholder working group know. 

Will close ticket now!

**Comment by MickinSahni** [comment]
@ncksllvn, i tacked on 2 points to this
