### ISSUE TITLE
Remove conditional use of the old isCerner method

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#51630]
## Description

We need to remove the 'vaOnlineSchedulingUseDsot' feature flag as the `selectPatientFacilities` selector will no longer be in use.

---

## Acceptance Criteria
we no longer use the `vaOnlineSchedulingUseDsot` toggle.

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by jilladams** [comment]
@vbahinwillit is the work here complete? I see the PR merged but ticket is open, not sure if that means you all are clear for us to go ahead with deprecation or no.

**Comment by ldelacosta** [comment]
Validated the changes in staging and no issues to report. Closing the ticket. 

@jilladams - We are providing sign-off from the VAOS team.
