### ISSUE TITLE
VA Request Flow - Content Update 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#51648]
## Description
In VAOS, the user has the ability to schedule an appointment or submit a request for an appointment. In the request flow, the Veteran may think they are scheduling an appointment but they are submitting a request for an appointment. When requesting for an appointment, the Veteran does not have a confirmed appointment until the VA staff schedules an appointment on their behalf.

No changes for the direct scheduling workflow. 
Community Care request flow will be worked on in ticket #51668

---

## Acceptance Criteria

- [x] Given the user clicks on Start Scheduling
When the user is on any page in the [VA request flow](https://www.figma.com/file/ugE1APC20v8OcArGB2IMQy/Appointments-User-Flows-%7C-Appointments-FE?type=design&node-id=1-3877&mode=design&t=hgViOFlSUj1zCY7i-4) (all pages listed in following AC).
Then the page subheading will be updated to `REQUEST AN APPOINTMENT`

- [x] Given when the user starts scheduling in VAOS and is in the VA request flow 
When the user lands on the date selection page
Then the user will see the updated page header:

> When would you like an appointment? 

And a `(*Required)` indicator under the page header 
And the description:
> You can select up to 3 preferred timeframes. We'll schedule your appointment or call to schedule with you.

And the page design matches the [design spec](https://www.figma.com/file/ewxCGm9dkvYt5wiNXMwvkL/Request-flow-content-update-%7C-Appointments-FE?type=design&node-id=607-21790&mode=design&t=nyMoz7Z4C7jyCji3-4)

- [x] Given when the user starts scheduling in VAOS and is in the VA request flow
When the user lands on the date selection page
And clicks any available date
Then the user will see two options (note the added periods):

   > A.M. Before noon
   > P.M. Noon or later

And the page design matches the [design spec](https://www.figma.com/file/ewxCGm9dkvYt5wiNXMwvkL/Request-flow-content-update-%7C-Appointments-FE?type=design&node-id=607-21925&mode=design&t=nyMoz7Z4C7jyCji3-11)

- [x] Given when the user starts scheduling in VAOS and is in the VA request flow
When the user lands on the reason for appointment page
Then the user will see the updated page header `What's the reason for this appointment?` 
And a `(Required)` indicator under the page header
And the label for the textarea question is: `Add any details you'd like to share with your provider. (*Required)`
And page design matches the [design spec](https://www.figma.com/file/ewxCGm9dkvYt5wiNXMwvkL/Request-flow-content-update-%7C-Appointments-FE?type=design&node-id=607-22184&mode=design&t=nyMoz7Z4C7jyCji3-11)

- [x] Given when the user starts scheduling in VAOS and is in the VA request flow
When the user lands on the page to select the appointment modality 
Then the user will see the updated page header `How do you want to attend this appointment?`
And a `(Required)` indicator under the page header
And page design matches the [design spec](https://www.figma.com/file/ewxCGm9dkvYt5wiNXMwvkL/Request-flow-content-update-%7C-Appointments-FE?type=design&node-id=607-22361&mode=design&t=nyMoz7Z4C7jyCji3-11)

- [x] Given when the user starts scheduling in VAOS and is in the VA request flow
When the user lands on the page to select the appointment modality 
Then the user will see the updated appointment modality options
   > In person
   > By phone
   > Through VA Video Connect (telehealth) 

   And page design matches the [design spec](https://www.figma.com/file/ewxCGm9dkvYt5wiNXMwvkL/Request-flow-content-update-%7C-Appointments-FE?type=design&node-id=607-22361&mode=design&t=nyMoz7Z4C7jyCji3-11)

- [x] Given when the user starts scheduling in VAOS and is in the VA request flow
When the user lands on the contact information page
Then the user will see the updated page header `How should we contact you?` and the description:

   > We’ll use this information if we need to contact you about your appointment. 

   And page design matches the [design spec](https://www.figma.com/file/ewxCGm9dkvYt5wiNXMwvkL/Request-flow-content-update-%7C-Appointments-FE?type=design&node-id=607-22550&mode=design&t=nyMoz7Z4C7jyCji3-11)

- [x] Given when the user starts scheduling in VAOS and is in the VA request flow
When the user lands on the review the request details page
Then the user will see the updated page header `Review and submit your request` 
And the primary CTA button 'Submit request'
And page design matches the [design spec](https://www.figma.com/file/ewxCGm9dkvYt5wiNXMwvkL/Request-flow-content-update-%7C-Appointments-FE?type=design&node-id=607-22776&mode=design&t=nyMoz7Z4C7jyCji3-4)

### Design Assets
[Figma File - VA and CC Request Flow](https://www.figma.com/file/ewxCGm9dkvYt5wiNXMwvkL/Request-flow-content-update-%7C-Appointments-FE?type=design&node-id=617-19228&mode=design&t=nyMoz7Z4C7jyCji3-4)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by ldelacosta** [comment]
No longer need a feature toggle `va_online_scheduling_request_flow_update` for this ticket cc: @JRRoof @simiadebowale

**Comment by ldelacosta** [comment]
@young1205 - please have the UX team validate this ticket when it's ready cc: @JRRoof @outerpress

**Comment by outerpress** [comment]
@ldelacosta @JRRoof as discussed I pulled these A/C's because we'll be working on these pages/changing these designs with the upcoming details page redesign work:

```
- [ ] Given when the user starts scheduling in VAOS and is in the VA request flow
When the user submits the VA request for an appointment
Then the user will see the updated page header `We received your request` 
And the description:
   > We'll try to schedule your appointment in the next 2 business days. Check back here or call your facility for updates.
   Review your upcoming appointments 
   Schedule a new appointment

   And page design matches the [design spec](https://www.figma.com/file/7xco5cdj7kLqZH4WfUodiH/Content-Review---CC-and-Request-Flow---Screen-Files?node-id=607%3A22933&t=xW6BVM4oEZJW0U4Y-4)

- [ ] Given when the user views their VA request details 
When the user is on the VA request details page
Then the user will see the updated page header `Request for appointment` 
And the description:

   > We'll try to schedule your appointment in the next 2 business days. Check back here or call your facility for updates.

   And page design matches the [design spec](https://www.figma.com/file/7xco5cdj7kLqZH4WfUodiH/Content-Review---CC-and-Request-Flow---Screen-Files?node-id=639%3A42434&t=xW6BVM4oEZJW0U4Y-4)

- [ ] Given when the user views their VA request details 
When the user cancels the VA request for appointment
Then the user will see the updated page header `Canceled request for appointment` 
And the description:

   > [Canceler] canceled this request. If you still need an appointment, call us or request a new appointment online.

   And page design matches the [design spec](https://www.figma.com/file/7xco5cdj7kLqZH4WfUodiH/Content-Review---CC-and-Request-Flow---Screen-Files?node-id=1055%3A18454&t=xW6BVM4oEZJW0U4Y-4)
```

**Comment by ldelacosta** [comment]
@outerpress - this is ready to be validated in staging.

**Comment by outerpress** [comment]
@vbahinwillit issues below, let me know if you have questions. Thanks!

Page: Choose the type of care you need.
Issue: When navigating to request flow and back, page eyebrow changes to “REQUEST AN APPOINTMENT”
Desired state: Page eyebrow should always read “NEW APPOINTMENT.

<img width="948" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN24vQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--df13ed7695a2a9393659f9e42f078b8267f3ad1f/REQUEST%20AN%20APPOINTMENT.png" alt="REQUEST AN APPOINTMENT.png" />


---

Page: Choose a location
Issue: When navigating to request flow and back, page eyebrow changes to “REQUEST AN APPOINTMENT”
Desired state: Page eyebrow should always read “NEW APPOINTMENT.

<img width="954" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3IvQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b4a7c4639d5e8143d7503470ab91b9e7f99eddb1/REQUEST%20AN%20APPOINTMENT.png" alt="REQUEST AN APPOINTMENT.png" />


---

Page: What’s the reason for this appointment?
Issue: The legend for the form is `(*Required)`. For screenreaders this announces “Asterisk Required” as the group when tabbing to an individual radio option.
Ideal solution: “What’s the reason for this appointment” would ideally be the legend for that question. There are [some components](https://design.va.gov/storybook/?path=/docs/uswds-va-radio--forms-pattern-single#label-header) that might be able to help with that. 
If that doesn’t work: If that's too big or just not doable, let me know and I’ll provide text to use for a label above the radio, like it was set up before.

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3YvQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1fdaffa3f67a8415a2c5026a412e342cbe426bc5/What%27s%20the%20reason%20for%20this.png" alt="What's the reason for this.png" />

---

Page: What’s the reason for this appointment?
Issue: The required mark should be closer to the H1 (what you did on the choose a date page would work).

---

Page: How do you want to attend this appointment?
Issue 1: Same issue as above where the H1 should be the legend for the inputs
Issue 2: Same issue as above where the required mark should be closer to the H1

---

Page: Review and submit your request
Issue: The H2 headings should use visual H2 styling. See the updated spec here.

---

Page: Review and submit your request
Issue: Under “How you want to attend” the displayed modalities should match what they selected earlier (In person, By phone, Through VA Video Connect (telehealth))

**Comment by outerpress** [comment]
@vbahinwillit one more:

Page: How should we contact you
Change sentence under heading to match the CC flow: “We’ll use this information if we need to contact you about this appointment. For most other VA communications, we'll use the contact information in your VA.gov profile.” We missed this in the designs.

Also, I'm going to edit the above comment about heading styles - the H2 Headings on the review pages should use H3 styles. (I forgot that the H1s are downsized visually to H2s)

**Comment by outerpress** [comment]
@vbahinwillit @ldelacosta some of the issues from my previous comments are still present. I checked off the ones that are looking good. (The new input treatment is working really well!) Let me know when the others are done, and I'll take another look.

Oh and it looks like the headings on the review page are the right size, but they should be in the standard heading font (Bitter).

**Comment by ldelacosta** [comment]
All the changes have been validated. A new [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/79660) will cover the items that were not part of this work.
