### ISSUE TITLE
Community Care Request Flow - Content Update

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#51668]
## Description
In VAOS, the user has the ability to schedule an appointment or submit a request for an appointment. In the request flow, the Veteran may think they are scheduling an appointment but they are submitting a request for an appointment. When requesting an appointment, the Veteran does not have a confirmed appointment until the VA staff schedules an appointment on their behalf.

This is for the Community care request flow
No changes for the direct scheduling workflow. 
VA request flow will be worked on in ticket #51648  

---
## Acceptance Criteria

- [x] Given the user clicks on Start Scheduling
When the user is on the [Community Care request flow](https://www.figma.com/file/ugE1APC20v8OcArGB2IMQy/Appointments-User-Flows-%7C-Appointments-FE?type=design&node-id=1-3760&mode=design&t=9tVVXO4YMKuOBsFW-4) 
Then the page subheading will be updated to `REQUEST COMMUNITY CARE`
And page design matches the [design spec](https://www.figma.com/file/ewxCGm9dkvYt5wiNXMwvkL/Request-flow-content-update-%7C-Appointments-FE?type=design&node-id=619-19190&mode=design&t=nyMoz7Z4C7jyCji3-4)

- [ ] Given when the user starts scheduling in VAOS and is in the Community Care request flow
When the user lands on the date selection page
Then the user will see the updated page header `When would you like an appointment?` 
And a `(*Required)` indicator under the page header
And the description
   > You can select up to 3 preferred timeframes. We'll schedule your appointment or call to schedule with you.

   And page design matches the [design spec](https://www.figma.com/file/ewxCGm9dkvYt5wiNXMwvkL/Request-flow-content-update-%7C-Appointments-FE?type=design&node-id=636-9554&mode=design&t=nyMoz7Z4C7jyCji3-4)

- [x] Given when the user starts scheduling in VAOS and is in the Community Care request flow
When the user lands on the date selection page
And clicks any available date
Then the user will see two options (note the added periods):

   > A.M. Before noon
   > P.M. Noon or later

   And page design matches the [design spec](https://www.figma.com/file/ewxCGm9dkvYt5wiNXMwvkL/Request-flow-content-update-%7C-Appointments-FE?type=design&node-id=636-9562&mode=design&t=nyMoz7Z4C7jyCji3-4)

- [x] Given when the user starts scheduling in VAOS and is in the Community Care request flow
When the user lands on the location page
Then the user will see the updated page header `What's the nearest city to you?` 
And a `(*Required)` indicator under the page header
And page matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/edit/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/cc-closest-city.md)
And page design matches the [design spec](https://www.figma.com/file/ewxCGm9dkvYt5wiNXMwvkL/Request-flow-content-update-%7C-Appointments-FE?type=design&node-id=619-19192&mode=design&t=nyMoz7Z4C7jyCji3-4)

- [x] Given when the user starts scheduling in VAOS and is in the Community Care request flow
When the user lands on the provider page 
Then the user will see the updated page header `Which provider do you prefer?` 
And page design matches the [design spec](https://www.figma.com/file/ewxCGm9dkvYt5wiNXMwvkL/Request-flow-content-update-%7C-Appointments-FE?type=design&node-id=619-19376&mode=design&t=nyMoz7Z4C7jyCji3-4)

- [x] Given when the user starts scheduling in VAOS and is in the Community Care request flow
When the user lands on the language page
Then the user will see the updated page header `What language do you prefer?` and the description 
   > Select the language you'd prefer your provider speak. (*Required)

   And page design matches the [design spec](https://www.figma.com/file/ewxCGm9dkvYt5wiNXMwvkL/Request-flow-content-update-%7C-Appointments-FE?type=design&node-id=619-20069&mode=design&t=nyMoz7Z4C7jyCji3-4)

- [x] Given when the user starts scheduling in VAOS and is in the Community Care request flow
When the user lands on the reason for appointment page
Then the user will see the updated page header `What's the reason for this appointment?` 
And the description:

   > Share any information that you think will help the provider prepare for your appointment. You don’t have to share anything if you don’t want to.

   And page design matches the [design spec](https://www.figma.com/file/ewxCGm9dkvYt5wiNXMwvkL/Request-flow-content-update-%7C-Appointments-FE?type=design&node-id=619-20254&mode=design&t=nyMoz7Z4C7jyCji3-4)

- [x] Given when the user starts scheduling in VAOS and is in the Community Care request flow When the user lands on the contact information page
Then the user will see the updated page header `How should we contact you?` 
And the description:

   > We’ll use this information if we need to contact you about this appointment. For most other VA communications, we'll use the contact information in your VA.gov profile. 

   And page design matches the [design spec](https://www.figma.com/file/ewxCGm9dkvYt5wiNXMwvkL/Request-flow-content-update-%7C-Appointments-FE?type=design&node-id=619-20525&mode=design&t=nyMoz7Z4C7jyCji3-4)

- [x] Given when the user starts scheduling in VAOS and is in the Community Care request flow 
When the user lands on the review details page
Then the user will see the updated page header `Review and submit your request`
And the submit button `Submit request`
And page design matches the [design spec](https://www.figma.com/file/ewxCGm9dkvYt5wiNXMwvkL/Request-flow-content-update-%7C-Appointments-FE?type=design&node-id=619-20600&mode=design&t=nyMoz7Z4C7jyCji3-4)

### Design Assets
[Figma file - VA and CC Request Flow](https://www.figma.com/file/ewxCGm9dkvYt5wiNXMwvkL/Request-flow-content-update-%7C-Appointments-FE?type=design&node-id=619-19190&mode=design&t=nyMoz7Z4C7jyCji3-4)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by ldelacosta** [comment]
No longer need a feature toggle `va_online_scheduling_request_flow_update` for this ticket cc: @JRRoof @simiadebowale

**Comment by ldelacosta** [comment]
@young1205 - please have the UX team validate this ticket when it's ready cc: @JRRoof @outerpress

**Comment by outerpress** [comment]
@ldelacosta @JRRoof as discussed I pulled these A/C's because we'll be working on these pages/changing these designs with the upcoming details page redesign work:

```
- [ ] Given when the user starts scheduling in VAOS and is in the Community Care request flow 
When the user submits the Community Care request 
Then the user will see the updated header on the confirmation request details page `We received your request` 
And the description:

   > We'll try to schedule your appointment in the next 2 business days. Check back here or call your facility for updates.
       Review your upcoming appointments 
       Schedule a new appointment

And page design matches the [design spec](https://www.figma.com/file/7xco5cdj7kLqZH4WfUodiH/Content-Review---CC-and-Request-Flow---Screen-Files?node-id=619%3A20643&t=EwwbmZGEDEyNw4s4-4)

- [ ] Given when the user wants to view their Community Care pending request 
When the user is opens the request details page 
Then the user will see the updated page header `Request for community care` 
And the description:

   > We'll try to schedule your appointment in the next 2 business days. Check back here or call your facility for updates.

And page design matches the [design spec](https://www.figma.com/file/7xco5cdj7kLqZH4WfUodiH/Content-Review---CC-and-Request-Flow---Screen-Files?node-id=639%3A43165&t=EwwbmZGEDEyNw4s4-4)

- [ ] Given when the user views their Community Care pending appointment 
When the user cancels the Community Care request  
Then the user will see the updated page header `Canceled request for community care` 
And the description:

   > [Canceler] canceled this request. If you still need an appointment, call us or request a new appointment online.

   And page design matches the [design spec](https://www.figma.com/file/7xco5cdj7kLqZH4WfUodiH/Content-Review---CC-and-Request-Flow---Screen-Files?node-id=1056%3A17278&t=EwwbmZGEDEyNw4s4-4)
```

**Comment by vbahinwillit** [comment]
Changes implemented in #52480

**Comment by ldelacosta** [comment]
One acceptance criteria did not change. UX team - could you confirm and see if we're missing other changes. 

<img width="775" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0wrQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--caab4057e18b186145e6e22a37a247904723d3d3/Screenshot%202024-03-21%20at%203.28.25%20PM.png" alt="Screenshot 2024-03-21 at 3.28.25 PM.png" />

**Comment by outerpress** [comment]
Hi @vbahinwillit, some changes below to add to the one @ldelacosta  mentioned above. Let me know if you have questions:

--

Pages: Choose the type of care you need and Choose a VA location
Issue: When navigating to request flow and back, page eyebrow changes to “REQUEST COMMUNITY CARE”
Desired state: Page eyebrow should always read “NEW APPOINTMENT.

--

Page: What’s the nearest city to you?
Issue: The legend for the form is `(*Required)`. For screenreaders this announces “Asterisk Required” as the group when tabbing to an individual radio option. See the other CC request ticket for more, this is the same issue. I think this is the only page in this flow with that issue.

--

Page: Review and submit your request
Change empty state message to: “No provider specified. We’ll  choose the provider nearest to you who is available closest to your preferred time.”
<img width="1040" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0FDQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cef8dd32413088a6a4a8d811fb2a2fbd242fb99c/Preferred%20provider.png" alt="Preferred provider.png" />

--

Page: Review and submit your request
Change heading to read: “Preferred date and timeframe”
<img width="514" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0lDQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--92151b2d88e39c2d91b22888bbe100951f26f163/Preferred%20date%20and%20time.png" alt="Preferred date and time.png" />

--

Page: Review and submit your request
Issue: The H2 headings should use visual H2 styling. See the [updated spec](https://www.figma.com/file/ewxCGm9dkvYt5wiNXMwvkL/Request-flow-content-update-%7C-Appointments-FE?type=design&node-id=607-22776&mode=design&t=wWOHtLUsfj1PF3hV-4) here.

--

Page: Review and submit your request
Currently the Details you shared with your provider section only shows if they enter information in that field.
Requested change: Always show the “Details you’d like to share with your provider” section.
If the field is empty, show the language: “No details shared”

**Comment by outerpress** [comment]
@vbahinwillit @ldelacosta some of the issues from my previous comment are still present. I checked off the ones that are complete. The headings on the review page are almost there, they should just be in the standard heading font (Bitter). And the second AC in the ticket isn't done (Leah's comment).

**Comment by ldelacosta** [comment]
All the changes have been validated. A new [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/79660) will cover the items that were not part of this work.
