### ISSUE TITLE
MDT- Email step- Veteran contact details - add an email address, v1

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#5167]
## User Story:
As a veteran, I need to be able to add a new email address so that I can keep my information updated and current.

## Tasks
- [x] Create a high fidelity mockup depicting how a veteran might add a new email address if one is not pre-populated
- [x] Upload exports to Invision and indicate initial focus point as a comment

## Acceptance Criteria:
Mockup aligns with VA.gov’s design system
Veteran is able to add a new email address 
The screen’s initial focus is incorporated
Sketch artboards are uploaded to Invision and linked in this ticket as a comment

## Dep/Blockers

**Comment by rileyorr** [comment]
This was an interesting one to prototype! So the [default](https://vsateams.invisionapp.com/share/RJVXC02MS3W) screen I created assumes the Veteran did not have any address/email data to pass through and has completed the address portion of the screen.
The Veteran can add an email address by just [selecting the text input box](https://vsateams.invisionapp.com/share/JVVXCA1W3GA) and typing in their email address. The focus would move to that input field once selected. 
@mr0sari0 @mojaray2k Let me know if you wanna meet to review these screens. :)
