### ISSUE TITLE
[SPIKE] [BE] [FE] How might we allow authenticated apps to access vets-api

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#51677]
## Background
Per Stephen: in preparation for some of our authenticated applications (e.g. Mobile app, Health Apartment, VAOS) to use the PCI API to check-in a Veteran for their appointment, we need to research how we might be able to do this and what is needed.

Can we put fully auth'd Veterans into existing check-in/pre-check-in apps?
Do we need to go thru LoROTA or would a new endpoint be enough to complete the check-in steps?

## Tentative Integration
https://app.mural.co/t/departmentofveteransaffairs9999/r/1675718737504?folderUuid=7ad264a1-d550-4bc6-a7b3-27fac23c9e08

## AC
- [ ] Outlining additional spikes with questions to answer

**Comment by loripusey** [comment]
The last page of this GitHub [document ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/patient-check-in/Requirements/2023.04.25%20Mobile%20app_Patient%20Check%20In%20MVP.pdf)lays out the tentative MVP

@randomsync @brianseek @wullaski @kanchanasuriya

**Comment by wullaski** [comment]
Added an area in engineering documentation for implementation notes WIP https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/engineering/full-auth-check-in
