### ISSUE TITLE
Use simplified header

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#51686]
## Background
The PR to fix content-build has been merged: department-of-veterans-affairs/content-build#1425

Next step for the header (in progress) is to test the vets-website PR with the content-build PR merged and document and submit the PR.

## AC

- [ ] Variables in the app registry work to suppress login and menu in header

**Comment by acrollet** [comment]
The PR to fix vets-website to respect the app registry variables has been merged: https://github.com/department-of-veterans-affairs/vets-website/pull/23054#pullrequestreview-1251968168

Next step is to test the [content-build PR to enable the minimal header](https://github.com/department-of-veterans-affairs/content-build/pull/1421) on its review environment with the newly merged vets-website changes and submit it for review.
