### ISSUE TITLE
Content for unified terms & conditions (T&C) flow

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#51681]
## Issue Description
We need to provide content for ~4 short pages in a centralized terms & conditions flow for all VA digital tools. 

Here's our understanding of the user flow:
- User signs in on www.va.gov/sign-in (or our sign in modal)
user is presented with unified T&C (covering all apps, including the MHV portal apps (SM, Med Records, appts, rx), with some very specific exceptions)
- VA.gov makes note of when they sign and keeps a record of that for VA & Cerner purposes
- Veteran has access to 99% of the apps on VA.gov, Cerner, MHV, Ebenefits, and Mobile without needing to sign another T&C
- If the T&C is updated, we show it again

[I'll update this with links and next steps, just getting it posted for sprint planning]
---
## Tasks
- [x] Draft T&C content (Aliyah)
- [x] Review (Laura)
- [x] Pass to Danielle to review (Aliyah/Laura)
- [ ] Danielle review

## Acceptance Criteria
- [ ]

**Comment by aliyahblackmore** [comment]
Hi @DanielleThierryUSDSVA the drafted terms and conditions document is ready for you to review! 
[Terms and Conditions_AB_1.13.23.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/10415629/Terms.and.Conditions_AB_1.13.23.docx)

**Notes/Questions:**

- We sent over an email to David and team with a few questions. 

- We wanted to flag and follow up on this "[Terms and conditions for medical information](https://www.va.gov/health-care/medical-information-terms-conditions/)" page. The information alert box has "Accept" in the header, but there is no "accept" button on this page. Additionally, if you search "VA terms and conditions" in google, this is the first result that comes up.

- We may also want to do a review of this [Privacy, policies, and legal information page](https://www.va.gov/privacy-policy/). Some links lead to the wrong page. For example, the [VCL terms of service](https://www.veteranscrisisline.net/get-help-now/text/) link doesn't lead to their terms of service page.

**Comment by aliyahblackmore** [comment]
Hi @DanielleThierryUSDSVA this content is ready for you! 

We just made a few updates based on Mike's responses to our question. 
[Terms.and.Conditions_AB_1.17.23.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/10438539/Terms.and.Conditions_AB_1.17.23.docx)


**Pulling in our previous additional questions here:** 

- We wanted to flag and follow up on this "[Terms and conditions for medical information](https://www.va.gov/health-care/medical-information-terms-conditions/)" page. The information alert box has "Accept" in the header, but there is no "accept" button on this page. Additionally, if you search "VA terms and conditions" in google, this is the first result that comes up.

- We may also want to do a review of this [Privacy, policies, and legal information page](https://www.va.gov/privacy-policy/). Some links lead to the wrong page. For example, the [VCL terms of service](https://www.veteranscrisisline.net/get-help-now/text/) link doesn't lead to their terms of service page.

FYSA @laurwill

**Comment by DanielleThierryUSDSVA** [comment]
Hi @aliyahblackmore @laurwill. Thanks so much for your work on this! I answered the questions and added some edits and comments/questions. Let me know what you think. 

[Terms.and.Conditions_AB_1.17.23_DT](https://app.zenhub.com/files/133843125/9c769c53-bce4-4b23-bb9f-afb77e4b8b15/download)

And let's definitely create a ticket in the backlog to review those other pages as a follow-up to this. Thank you for being so thorough and digging into those!

**Comment by laurwill** [comment]
Thank you Danielle! We added that note and I made a couple small tweaks that I'll show you in our 3pm sync. 

@megzehn , if you have time for a quick copyedit before we share this draft with the T&C team at 3:30 today, that's great. And if not, we'll just let them know that it still needs to go through copyedit.

[Terms of use_draft_1.18.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/10449292/Terms.of.use_draft_1.18.docx)

**Comment by laurwill** [comment]
Hi @megzehn ,
We made some updates after our call with the T&C team — could you copyedit this updated draft this morning before I send it for final review? Let me know if you have questions!
[Terms of use_1.19.23.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/10456748/Terms.of.use_1.19.23.docx)

**Comment by megzehn** [comment]
Thanks, @laurwill! This looks good!

**Comment by laurwill** [comment]
Thanks Megan! Just noting I sent this back to Carnetta and team for review.

**Comment by laurwill** [comment]
Update here: We met with the policy and identity working groups last week. We're updating based on their feedback to:
- Add more info about tool features you'll lose access to
- Add next step to get benefits if you choose to decline
- Clarify that you won't lose any VA benefits or services

**Comment by laurwill** [comment]
@megzehn , could you give this updated version a copyedit before we return it to the product team?

[Terms.of.use_updated_1.30.23.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/10537830/Terms.of.use_updated_1.30.23.docx)

**Comment by megzehn** [comment]
Hi @laurwill, thank you! This looks good. I made a minor change to some link text. But otherwise, I left it the same. 

[Terms.of.use_updated_1.30.23.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/10538474/Terms.of.use_updated_1.30.23.docx)

**Comment by laurwill** [comment]
Thank you! I sent back to Carnetta and team for review.

**Comment by RLHecht** [comment]
Closing out this ticket as it's now with the product team. We can open a new ticket if they have follow up work for us.
