### ISSUE TITLE
[bug] Certificate of Eligibility | COE creation date incorrect on COE status page.

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#51697]
## What happened?

An LGY tester pointed out that the "requested date" on User 246's COE status page was incorrect. I confirmed that it was indeed correct, and that LGY was sending us the correct date. Unfortunately, I cannot reproduce this error for this particular user today because for whatever reason the user is borked on staging. But, here is a screenshot of the "requested date" I'm referring to. After some more digging, I've learned that this is only an issue when a COE is denied.

![image](https://user-images.githubusercontent.com/7520103/211631776-96afde04-e48a-40fe-a2f6-a79e42e6e552.png)

## Specs:
- Device: Any
- Browser: Any
- Test User _(if applicable)_: Any user with a denied COE.

## Steps to Reproduce
- URL: https://staging.va.gov/housing-assistance/home-loans/check-coe-status/your-coe
- Test User _(if applicable)_: Any user with a denied COE, like User 131. 
- Go to the URL above.
- Open network tab in developer tools
- Refresh page
- Look at most recent `status` request, and identity `data.attributes.applicationCreateDate` therefrom.
- Go to https://www.epochconverter.com/ and convert the integer to a human-readable date. This is the date we expect to be rendered.
- The date rendered and the date returned from the backend do not match.

## Desired behavior
_Describe in detail what was supposed to happen; reference existing Github issue that contains a solution if possible_

- The date rendered and the date returned from the backend should match.

## Acceptance Criteria

- [ ] The date on User 131's COE status page should be Jan 4, 2023 (instead of the current date)

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by data-doge** [comment]
@saderagsdale, this is ready to review on staging. You can log in as User 131, go to https://staging.va.gov/housing-assistance/home-loans/check-coe-status/your-coe, and find the corrected date of Jan 4, 2023 (as opposed to the current date).

**Comment by saderagsdale** [comment]
@data-doge looks good to me.
