### ISSUE TITLE
For pre-check-in, add in appt instructions into confirmation page

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#51702]
## Description 

For pre-check-in, add in appt instructions into confirmation page. 

Reason is that it's likely Veterans won't see the instructions ever. Currently in the production app, they are on the confirmation page. This is more important for telephone appts. 

## AC

Update existing branch and pass along to FE

**Comment by ytsaoca** [comment]
Add that content [Screen Shot 2023-01-23 at 2.03.18 PM.png](https://images.zenhubusercontent.com/6148b41faabf78b679dbacff/c2deaf15-6115-48a5-b649-d258f32c1219) to the pre-check-in confirmation page, but do not remove it from the details pages.

**Comment by ytsaoca** [comment]
Add that content [Screen Shot 2023-01-23 at 2.03.18 PM.png](https://images.zenhubusercontent.com/6148b41faabf78b679dbacff/c2deaf15-6115-48a5-b649-d258f32c1219) to the pre-check-in confirmation page, but do not remove it from the details pages.

**Comment by ytsaoca** [comment]
Mockup for review: https://share.goabstract.com/49e5e0ca-feac-4ccb-9a03-0e05eeb05d75

**Comment by ytsaoca** [comment]
Mockup for review: https://share.goabstract.com/49e5e0ca-feac-4ccb-9a03-0e05eeb05d75

**Comment by benbrasso-agile6** [comment]
I'll take a look at this one tomorrow

**Comment by benbrasso-agile6** [comment]
Looks nice @ytsaoca all good here
