### ISSUE TITLE
[Monitoring] Provide support request process for VFS teams using Datadog 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#51705]
## User Story
As a VFS developer, I need to know how to request support for Datadog. 

## Background 
- #vfs-platform-support is the channel for submitting support requests
- Documentation may need to be updated as part of this release 

## Acceptance Criteria
- [ ] VFS Developers can request support for Datadog through #vfs-platform-support

## Refinement Guidance - Check the following before working on this issue: 
- [x] _Team label assigned ("platform-tech-team-2")_
- [x] _Epic assigned (if needed)_ 
- [x] _Estimated (points assigned)_
- [x] _Sprint assigned (once planned)_
- [x] _Team member(s) assigned_

**Comment by jhouse-solvd** [comment]
If possible, let's update the support bot selections to include Datadog.

**Comment by rsmithadhoc** [comment]
- Reviewed documentation for support.
    - [Getting help from the Platform in Slack](https://depo-platform-documentation.scrollhelp.site/support/getting-help-from-the-platform-in-slack) covers using the support bot in general.
    - I updated [Monitor Applications and Infrastructure with Datadog](https://depo-platform-documentation.scrollhelp.site/developer-docs/monitor-applications-and-infrastructure-with-datad) (see the [Confluence page](https://vfs.atlassian.net/wiki/spaces/OT/pages/2236612646/Monitor+Applications+and+Infrastructure+with+Datadog) if it hasn't published yet) with a general note to submit a support request for help.
- We can add it as a category to the bot. I don't have edit permissions, but @jhouse-solvd does, are you able to help get this updated (when you are back in office)?
    - Here's the sheet [support bot topics](https://docs.google.com/spreadsheets/d/1TItdfPMH_TiXEhgMKEqxIW2e5EaMKy4cHaBhaeQ7drU/edit#gid=1990856050&range=A36:D36). We would need to add `36`, `DataDog`, and `3,12`. This would add "DataDog" as an option to select when the "Infrastructure" and "Other" teams are selected in the support request.

**Comment by jhouse-solvd** [comment]
@rsmithadhoc - Thanks for this info! I looked at the sheet, and though I have edit permissions, that particular sheet is locked. Kerry Powell is the owner, though he's out today. It would be great to chat with him about this when he returns. I think we could even spin out that sub-task into a new ticket. Thoughts?

**Comment by rsmithadhoc** [comment]
Thanks @jhouse-solvd. I agree, let's break it out into a task so we can wrap this one up.

**Comment by rsmithadhoc** [comment]
https://app.zenhub.com/workspaces/platform-tech-team-2-633efe4ca5a428e5294d7ade/issues/gh/department-of-veterans-affairs/va.gov-team/54287 was created as a follow-up, closing this one out.
