### ISSUE TITLE
[Monitoring] Determine offboarding process for Platform/VFS Team members from Datadog

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#51701]
## User Story
As a Platform Operator, I need to know how to offboard users from Datadog. 

## Background 
- DOTS manages Okta and Datadog 
- Platform Operators may need to remove users from Datadog directly 
- Platform Operators will need to request that users be offboarded from Okta by contacting DOTS (See #51561)

## Resources
- Existing documentation in Confluence: "[Offboarding Team Member](https://vfs.atlassian.net/wiki/spaces/OT/pages/2097545323/Offboard+Team+Member)"

## Acceptance Criteria
- [x] There is documentation for Platform Operators that explains how to offboard users from Datadog.

## Refinement Guidance - Check the following before working on this issue: 
- [x] _Team label assigned ("platform-tech-team-2")_
- [x] _Epic assigned (if needed)_ 
- [x] _Estimated (points assigned)_
- [x] _Sprint assigned (once planned)_
- [x] _Team member(s) assigned_

**Comment by jhouse-solvd** [comment]
We await communication from DOTS to clarify a few minor, specific details. 

Once we've heard back, this issue will be completed quickly.

**Comment by it-harrison** [comment]
Documentation is [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/2526282894/Offboarding+Users+from+Datadog).

Also, the offboarding template [has been updated](https://github.com/department-of-veterans-affairs/va.gov-team/pull/53768).

**Comment by jhouse-solvd** [comment]
@it-harrison - Thank you! I'll review this and #51561 together later today or tomorrow.

**Comment by jhouse-solvd** [comment]
Operational documentation for the Platform Tech Support team that explains how to offboard users from Datadog has been added [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/2097545323/Offboard+Team+Member). 

This issue can be closed.
