### ISSUE TITLE
[Monitoring] Provide feedback loop for VFS teams to request Datadog features

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#51707]
## User Story
As a VFS developer, I need to know how to request Datadog features. 

## Background 
- There is a feature request process that might be relevant here (see [here](https://depo-platform-documentation.scrollhelp.site/support/Submitting-a-feature-request.1938915400.html))

## Acceptance Criteria
- [x] VFS Developers can request Datadog features through a designated process
- [x] Datadog feature requests are captured in a designated place

## Refinement Guidance - Check the following before working on this issue: 
- [x] _Team label assigned ("platform-tech-team-2")_
- [x] _Epic assigned (if needed)_ 
- [x] _Estimated (points assigned)_
- [x] _Sprint assigned (once planned)_
- [ ] _Team member(s) assigned_

**Comment by it-harrison** [comment]
Looks good!
