### ISSUE TITLE
[Monitoring] Provide feedback loop for VFS teams to suggest changes to Datadog documentation 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#51706]
## User Story
As a VFS developer, I need to know how to provide feedback for Datadog documentation. 

## Background 
- The Platform Website provides a way to submit document suggestions
- There should be a process in place for responding to that feedback 
- Vicky Bellissimo is the point of contact for the Platform Content team 

## Acceptance Criteria
- [x] VFS Teams can suggest changes to Datadog documentation (this already exists) 
- [x] PTT2 can view the suggested changes to Datadog documentation if/when it comes in 

## Refinement Guidance - Check the following before working on this issue: 
- [x] _Team label assigned ("platform-tech-team-2")_
- [x] _Epic assigned (if needed)_ 
- [x] _Estimated (points assigned)_
- [x] _Sprint assigned (once planned)_
- [ ] _Team member(s) assigned_

**Comment by ph-One** [comment]
Every page has a (1) standardized footer, which includes (2) a link to report an issue.

![image.png](https://images.zenhubusercontent.com/622146ffd0422cdb4d9fdd52/89b3fe75-2061-4290-80a6-100d9f4c9957)

That issue then lands on a GitHub Project Board, https://github.com/department-of-veterans-affairs/va.gov-team/projects/16
