### ISSUE TITLE
Add "(PDF)" to form number links

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#5171]
## Add "(PDF)" to form number links

On the results view of the Find a VA form page: http://preview-prod.vfs.va.gov/preview?nodeId=2352&q= 

- Under the **Form number** column, the form number links should display "(PDF)" file type. 
- Like this: "[10-0102 (PDF)](hyperlinkexample.com)"

Current - preview: 
![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/1cb7d0f8-8efc-43b9-8bec-7aa208f028ed)

**Comment by stphnwlkr** [comment]
Is there a value added? Do we provide forms that are not PDF?

**Comment by jenniferlee-dsva** [comment]
@stphnwlkr - It is our style guide standard to indicate file type, so it's clear that it's not simply a link that takes you to another web page.

**Comment by ncksllvn** [comment]
Is the expectation that all of the links should be PDFs? There are some that aren't -

```
https://www.gsa.gov/portal/forms/download/115898
http://www.gsa.gov/portal/forms/download/114574
https://www.archives.gov/veterans/military-service-records/standard-form-180.html
http://www.gsa.gov/portal/forms/download/116014
http://www.gsa.gov/portal/forms/download/114666
http://www.gsa.gov/portal/forms/download/114662
https://www.gsa.gov/portal/forms/download/115990
https://www.gsa.gov/portal/forms/download/150834
http://www.gsa.gov/portal/forms/download/116402
http://www.gsa.gov/portal/forms/download/116254
http://www.grants.gov/web/grants/forms/sf-424-family.html#sortby=1
```

**Comment by jenniferlee-dsva** [comment]
Let's sync on ^ tomorrow. Would like to understand where these are coming from (that index page or on results)....

I did a quick click through and none of these appear to be Veteran facing forms, or even VA forms. Let's discuss if I need to go back to Kevin and team to ask them to remove these from the forms database -- that might be the best way to approach these strange items.  

Here's what I found: 

https://www.gsa.gov/portal/forms/download/115898
This resolves to https://www.gsa.gov/forms-library/solicitation-offer-and-award-construction-alteration-or-repair showing Form SF 1442 which is a PDF

http://www.gsa.gov/portal/forms/download/114574
This resolves to https://www.gsa.gov/forms-library/guard-post-assignment-record Guard Post Assignment Record form (dated 09/1970), PDF form

https://www.archives.gov/veterans/military-service-records/standard-form-180.html This resolves to a page with SF 180 form, PDF

http://www.gsa.gov/portal/forms/download/116014 This resolves to https://www.gsa.gov/forms-library/awardcontract not V-facing, also PDF

http://www.gsa.gov/portal/forms/download/114666 Resolves to https://www.gsa.gov/forms-library/agency-request-adjustmentopac-charge-backs-fbf-rent-billings with PDF form, dated 1999, not V-facing

http://www.gsa.gov/portal/forms/download/114662 Resolves to https://www.gsa.gov/forms-library/reimbursable-work-authorization page saying paper form deprecated and replaced by electronic application, not V-facing… but oddly provides download PDF form link

https://www.gsa.gov/portal/forms/download/115990 Resolves to https://www.gsa.gov/forms-library/architect-engineer-contract SF 252 PDF form “Architect Engineer Contract,” dated 10/1983

https://www.gsa.gov/portal/forms/download/150834 Resolves to https://www.gsa.gov/forms-library/claim-reimbursement-expenditures-official-business not V-facing, PDF form for fed employees

http://www.gsa.gov/portal/forms/download/116402 Resolves to https://www.gsa.gov/forms-library/medical-record-report-medical-examination, dated 10/1994, appears to be not V facing but unclear, also PDF

http://www.gsa.gov/portal/forms/download/116254 resolves to https://www.gsa.gov/forms-library/solicitation-offer-and-award SF 33 PDF form page, not V facing

http://www.grants.gov/web/grants/forms/sf-424-family.html#sortby=1 Weird incomprehensible page, not V facing forms list

**Comment by jenniferlee-dsva** [comment]
Per convo w/ @ncksllvn - FE has implemented conditional logic to add (PDF) only to PDF forms. RE ^ non-VA and non-PDF form web pages that come up in the current (live) forms db search, I will share w/db manager to alert them - recommend removing/retiring outdated data.  Thank you Nick and @kelsonic !
