### ISSUE TITLE
Adding [Florence McCafferty] to DSVA Slack

### ISSUE THREAD

**Issue by fmccaf1** [department-of-veterans-affairs/va.gov-team#51720]
# Description

Please add Florence McCafferty (florence.mccafferty@agile6.com) as a full member to slack channels relevant for her role as UX designer on the Authenticated Experience team: #accountexp-authexp, #vfs-all-teams, #vfs-platform-support, #research-ops, and as a multi-channel member of the DSVA workplace slack.

**Comment by LEHigley** [comment]
hi @fmccaf1 -- confused here. this says to add you as a full user but also as a multi channel user to specific channels. 

what account type should it be?

**Comment by LEHigley** [comment]
already showing as a member of the workspace--reactivated account
