### ISSUE TITLE
Cleanup Variant Event Labels used for Google Analytics

### ISSUE THREAD

**Issue by JRRoof** [department-of-veterans-affairs/va.gov-team#51723]
## Description
Several Google Analytics event labels were created to track results of several variant tests.  These event labels are no longer used and should be deprecated:

vaos-variant-default-alphabetical
vaos-variant-default-distanceFromCurrentLocation
vaos-variant-default-distanceFromResidentialAddress 
vaos-variant-final-
vaos-variant-final-alphabetical
vaos-variant-final-distanceFromCurrentLocation
vaos-variant-final-distanceFromResidentialAddress
vaos-variant-method-
vaos-variant-method-alphabetical
vaos-variant-method-distanceFromCurrentLocation 
vaos-variant-method-distanceFromResidentialAddress 
vaos-variant-shown

---

## Acceptance Criteria
Background: the `va_online_scheduling_variant_testing` toggle is off

Given a VAOS engineer
When editing front end code or vets-api
Then no GA Event Labels with "variant" in the name should exist

Given a product manager
When looking at Event Labels in GA
Then no data for events with "variant" in the name should exist going forward.

### Design Assets
Removal of labels should have no effect on UI/UX.
[VAOS Analytics Definitions](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/analytics/%5Bdraft%5Dvaos-analytics-definitions.md)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by JRRoof** [comment]
I'm still seeing Variant events in GA4 in Production.  Have these changes only been made in Staging?
<img width="582" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzNGQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--83687621347d6f88c181a7b2930ea4bd877d5de7/image.png" alt="image.png" />

**Comment by JunTaoLuo** [comment]
I just merged the change today so there were still some events from this morning before the deployment completed. It should zero out tomorrow. I see the lower number of events today as a good sign it's working.
