### ISSUE TITLE
Staging: Request Location not Displayed in Queue View

### ISSUE THREAD

**Issue by JRRoof** [department-of-veterans-affairs/va.gov-team#51722]
## Summary
The requested location does not initially display when the appointments are loaded onto the page in queue view. You must reload the page and then the locations will display.

## Specs
- Device: Tested on PC
- Browser: Tested with Chrome and MS Edge

## Steps to Reproduce
**Test User:** cecil.morgan@id.me, for CC appointments use grethel.g.petryniec@id.me

1.  Login to Staging as patient with several pending VA Requests.  
2.  From the home page select the pending request queue link.  Page displays.  
3.   Expected response:  Page displays a list of requests and each request has the type of care and location.  
4.  Actual Response: Page displays list of of requests and each request only has the Type of Care.  Location is NOT displayed.
![image](https://user-images.githubusercontent.com/97117349/211857878-ecbe4925-0987-4ddf-852c-395046058733.png)

### Actual Result
In staging, when you are in the queue and the appointments are displaying on the page, their location does not display until you reload the page. This is a loss of information for the veteran. 

### Desired Result
In staging, when you are in the queue and the appointments are displaying on the page, their location displays without reloading the page. 

## Definition of Done
- [ ] Desired result is achieved and/or document decisions made
- [ ] Relevant documentation is updated

---
## How to configure this issue
- [ ] **Labeled with Team** (`vaos`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `design`, `product`)
- [ ] **Labeled with** `Bug`
- [ ] **Assigned to** Product for prioritization

**Comment by marcynadeau** [comment]
assigning to Beth for testing

**Comment by beth-wodzinski** [comment]
This passes testing. Verified with Cecil and Grethel as specified above, but also with other patients. Location shows up consistently. @ldelacosta
