### ISSUE TITLE
Fix link on mental health page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#51737]
## Issue Description

SiteImprove shows a broken link on our [VA mental health services page](https://www.va.gov/health-care/health-needs-conditions/mental-health/) for NAMI. The link is redirecting to another NAMI page, which we should change the link to directly.

In the last accordion on the page "Community mental health resources" the first link for NAMI should now point to https://www.nami.org/findsupport

## Tasks
- [x] Update link
- [x] Copyedit (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] Link no longer broken on live site

**Comment by RLHecht** [comment]
@megzehn I just fixed this link. When you get a chance can you review and publish? thanks!

**Comment by megzehn** [comment]
Thanks, @RLHecht! This is published.

**Comment by RLHecht** [comment]
This is live. Closing ticket.
