### ISSUE TITLE
Create R&S content about virtual BVA hearings

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#51743]
## Veteran story

As a Veteran needing a BVA hearing, I need to understand my option for a virtual hearing, how virtual hearings work, and how to request one.

## What's needed

Both the legacy BVA TeamSite and the modernized VA.gov pages currently link to a PDF with content about virtual hearings. 

As part of content migration and to support greater accessibility, we'll use the content from the PDF as a reference to create html Resources and Support content on this content instead.

## Files for reference

[Virtual hearings PDF](https://www.bva.va.gov/docs/VirtualHearing_FactSheet.pdf)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht! This is one of the migration tickets that I noted in sprint planning that we'll want to plan to start for this sprint if possible.

**Comment by katherine-fung** [comment]
Listing questions about this content here: 

- The fact sheet includes info on how to request a virtual hearing. It says to use a form that someone would fill out if they're using the new appeals process. If you have a legacy appeal and you had requested a hearing, can you then request to have your hearing format switched to virtual and remain in the legacy appeals process? 

- The fact sheet refers to the hearings as "virtual tele-hearings." Is this the phrase we should use? 

- The fact sheet says that you can use Google Chrome to access the hearing, but if you're on an Apple device, you need download an app. Does the requirement to download an app specifically apply to Apple devices that are mobile, or all Apple devices including computers? (I would think that someone could use Google Chrome on their Apple computer to access a hearing too)

**Comment by katherine-fung** [comment]
Hi @laurwill @DanielleThierryUSDSVA @bethpottsVADEPO - 

I'm dropping a draft of this page, along with comments/questions, here: 
[https://app.zenhub.com/files/133843125/05cbf8c1-3625-4217-859e-98e36c5cc49c/download](https://app.zenhub.com/files/133843125/05cbf8c1-3625-4217-859e-98e36c5cc49c/download)

Which SMEs can we ask to about technical guidance and other questions we have? 

cc @RLHecht

**Comment by laurwill** [comment]
Hi @katherine-fung ,

This is looking great! Here's the doc with my tracked edits: 
[Virtual hearings.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/10817698/Virtual.hearings.docx)

Want to get this in Drupal and see how it looks? Thank you!

**Comment by katherine-fung** [comment]
Thanks so much @laurwill ! I put the content into Drupal: 

http://preview-prod.vfs.va.gov/preview?nodeId=53778 

re: your comment about moving the "Get help" section below "Prepare for a virtual hearing" - I think we could move the technical help part under "Prepare" but I wonder if the info about representatives being able to join the video call should stay where it is/higher on the page? I wonder if not knowing whether their rep could join [until scrolling further down] would deter people from choosing a virtual hearing. 

re: having a friend or family member help set up the device - I couldn't find any other copy like that on va.gov, so I cut it.

**Comment by katherine-fung** [comment]
Hi @megzehn - this R&S article is ready for copy edit, before we send to stakeholders.

http://preview-prod.vfs.va.gov/preview?nodeId=53778 

Thanks! 

cc @laurwill for awareness

**Comment by megzehn** [comment]
Thanks, @katherine-fung! I reviewed this and made some minor tweaks.

**Comment by laurwill** [comment]
Thanks Megan! @katherine-fung , I think the next steps here are to:
- Confirm what the virtual hearing option is called in the online form and update if needed
- Collect remaining questions for SMEs

And noting that I added a couple sentences in the "How virtual hearings work" section to note that there's a transcript, but no video recording.

**Comment by katherine-fung** [comment]
@bethpottsVADEPO - this page is ready for your review: 

http://preview-prod.vfs.va.gov/preview?nodeId=53778 

Thanks!

**Comment by katherine-fung** [comment]
@bethpottsVADEPO - this page is ready for your review: 

http://preview-prod.vfs.va.gov/preview?nodeId=53778 

Thanks!

**Comment by katherine-fung** [comment]
We met with stakeholders to discuss this page on 4/5. We sent over a Word doc of the content so they can add comments. They're aiming to get feedback to us by the end of next week (4/14). Moving this to blocked until we hear back.

**Comment by bethpottsVADEPO** [comment]
Just noting here that we discussed this on a call, you made some more edits, and you sent to SMEs for a review. Raeed said that SMEs will have some feedback for us after a Tuesday 4/18 meeting.

**Comment by katherine-fung** [comment]
Hi @bethpottsVADEPO, 

I've worked the SME's edits into the page. Here's the page preview: http://preview-prod.vfs.va.gov/preview?nodeId=53778 

Noting here that Raeed sent edits to us. I've attached a copy of the Word doc for reference.[https://app.zenhub.com/files/133843125/fabceaeb-e9f6-423a-86db-eee6660bdfc0/download](https://app.zenhub.com/files/133843125/fabceaeb-e9f6-423a-86db-eee6660bdfc0/download)

**Comment by katherine-fung** [comment]
1 - Thanks for this! I can mention this to him when we circle back to him. 

2/3/4 - Noted. Thank you for these edits! 

5 - We'll need to confirm this. The draft that we got back from Raeed made it sound like it was one email for the date/time of the hearing and a test link but we should confirm. And I'm not sure if the link for the actual hearing is the test link or a different link, so I can ask about that too. 

6 - I added the aria code label for the second phone number. 

7 - I put these instructions about the web browsers for different devices in originally, and then I removed them because I thought they were redundant now that we don't need the detail about Apple users needing the VA Connect app. But I just reviewed the instructions and added them back in with some tweaks because the instructions for Apple *are* different (I merged the info for computers and Android devices under one H3).

**Comment by bethpottsVADEPO** [comment]
@katherine-fung for No. 5: Just noting here what's needed if Raeed says it all comes together in one email:

The way we have it now, it sounds like the user will receive 2 emails. If the link to join the hearing and the test link all arrive in the same email, we'll have to rewrite the "What's next" section and the "Test your device" section.

**Comment by katherine-fung** [comment]
I emailed Raeed with questions about points 1 and 5 above.

**Comment by katherine-fung** [comment]
I emailed Raeed and team with an updated draft and a few other notes/questions.

**Comment by katherine-fung** [comment]
Noting here that Raeed sent us feedback on Friday, 9/8. I've incorporated it into the Drupal draft, and let him know. 

@megzehn @chelsealevinson we're ready to copy edit and publish this page. (the stakeholder doesn't need to see it again). cc @strelichl 

http://preview-prod.vfs.va.gov/preview?nodeId=53778

I can forward the email thread about this work to whoever copy edits. Please let me know if you have any questions!!

**Comment by katherine-fung** [comment]
For your awareness @megzehn @chelsealevinson and @bethpottsVADEPO -  

As part of publishing this page, we'll also need to link to it from several places on va.gov. 

1. On the Resources and support landing page, @megzehn or @chelsealevinson, can you add a "Go to all articles" link to the "Decision reviews and appeals" section (if one doesn't automatically generate)? The new virtual hearings article will be the 6th article in this category. I compared the page views for the 5 articles that are currently linked from the landing page, and the legacy virtual hearings PDF. The PDF has fewer page views. 

2. On VA.gov, I'll swap out links to the legacy PDF for the new virtual hearings R&S article. I need to do this on 2 pages: 

- https://www.va.gov/decision-reviews/board-appeal/
- https://www.va.gov/decision-reviews/fiduciary-claims/ 

3. We will likely need to add this virtual hearings page to the decision reviews hub page. We need IA support to figure out where to place the link. Once we know where, I can make the update in Drupal. 

4. We'll also need IA's guidance on where to add the virtual hearings link to menus, if any. Once we know where, @megzehn or @chelsealevinson, can you please make this update?

**Comment by megzehn** [comment]
Confirming this has been published and linked to both the Fiduciary claims page and the Board Appeals page.

Thank you so much, @katherine-fung, for all your work on this!!!

**Comment by bethpottsVADEPO** [comment]
@megzehn Are you going to add a link to this article from the R&S landing page in the decision review and appeals section?

**Comment by megzehn** [comment]
Yes, sorry, I should have included that in the update. I had it in drafts but was unsure about the pathway. I just published it now!

**Comment by katherine-fung** [comment]
Emailed stakeholders to let them know this is live. Added ticket to capacity tracker and closed.
