### ISSUE TITLE
[Monitoring] Update "Creating Datadog Monitors" documentation 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#51758]
## Description
Update the document based on feedback from the recent mini-workshop with Platform Tech Team 2. 

## Resources 
- [Creating Datadog Monitors](https://vfs.atlassian.net/wiki/spaces/TT2/pages/2423914751/Creating+Datadog+Monitors)

## Feedback 
Needs work:
- could better explain where to go to create monitors and alerts
  - How/Where to login to Datadog
  - Show menu item for where to go to create monitors and alerts

## Acceptance Criteria
- [x] The document is updated and shared with the team for review

## Refinement Guidance - Check the following before working on this issue: 
- [x] _Team label assigned ("platform-tech-team-2")_
- [x] _Epic assigned (if needed)_ 
- [x] _Estimated (points assigned)_
- [x] _Sprint assigned (once planned)_
- [x] _Team member(s) assigned_

**Comment by ph-One** [comment]
Added two new sections to identify where to log in to Datadog, as well as show the menu items to create a new monitor

![image.png](https://images.zenhubusercontent.com/622146ffd0422cdb4d9fdd52/d68db2e8-2d42-4808-aac2-ae77b0957539)

**Comment by jhouse-solvd** [comment]
@ph-One - Thanks for this! I'll give it a review soon, along with the team.

**Comment by ph-One** [comment]
Updated Title
