### ISSUE TITLE
Prevention of Readmission Requirement Analysis

### ISSUE THREAD

**Issue by jwowk** [department-of-veterans-affairs/va.gov-team#51755]
## Acceptance Criteria 
- [x] Meet with readmission team (Hayden Matz) 
- [x] Refine mural process
- [x] Review mural process
- [x] Create Wireframe

**Comment by jwowk** [comment]
Work with VISN 7 to further refine requirements related to their iNet project to prevent readmissions via text messaging.

Current documentation is attached.[https://app.zenhub.com/files/133843125/13ee2b64-ac41-4095-b747-14195fc4464e/download](https://app.zenhub.com/files/133843125/13ee2b64-ac41-4095-b747-14195fc4464e/download)[https://app.zenhub.com/files/133843125/329bb127-114b-4b3d-a7fa-1d9b5e9de151/download](https://app.zenhub.com/files/133843125/329bb127-114b-4b3d-a7fa-1d9b5e9de151/download)[https://app.zenhub.com/files/133843125/409f3e53-9b18-4e1a-9a0e-7572d0657092/download](https://app.zenhub.com/files/133843125/409f3e53-9b18-4e1a-9a0e-7572d0657092/download)

**Comment by jwowk** [comment]
[https://app.zenhub.com/files/133843125/c2568add-df7a-4a5c-a4d6-e3e092725037/download](https://app.zenhub.com/files/133843125/c2568add-df7a-4a5c-a4d6-e3e092725037/download)

**Comment by ahicksfearless** [comment]
This is an ongoing conversation. Rob has begun to work on building this out on his side.

**Comment by ahicksfearless** [comment]
I have updated the mural flow-chart to reflect the most recent verbiage, potential response codes, and when to update the order note on the VEText side.

**Comment by ahicksfearless** [comment]
Met with Shane and Justin on 3/8. Updating flow to include: within the 0-21 days if the patient is readmitted, new note created, they are opted out of the program.

**Comment by ahicksfearless** [comment]
3/14/23 Updated flow chart and communicated the following with the readmission team: 

- Do we need the response codes to be threadable? In other words, do we need unique response codes between enrollments? (e.g. the patient is discharged and then readmitted and then discharged again – should the response codes differ each time? The assumption is that this is not necessary, but it’s worth covering. 
- In the 3 days post discharge column, when the vet responds yes to the check-in question, they are prompted to give more information about what they need. Then the message reads “If you have any urgent clinical needs, please call (phone number entered by facility). Our team wonders if it would be better to prompt them to call 911? This is what we do for VEText. Maybe both the facility number and 911 can be listed?
- In the same column, if the vet responds that there is something they’d like assistance with (A%1%), but then they do not give a second response, how long after that response do we want to wait to follow-up and what would you like to say? Our thoughts are 15 minutes and then follow-up with “We haven’t heard from you in a while, do you still need support?”
