### ISSUE TITLE
[Monitoring] Update "Get or Create API and Application keys for Datadog" documentation

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#51764]
## Description
Update the document based on feedback from the recent mini-workshop with Platform Tech Team 2. 

## Resources 
- [Get or Create API and Applications keys for Datadog](https://vfs.atlassian.net/wiki/spaces/OT/pages/1934655507/Get+or+Create+API+and+Application+keys+for+Datadog)

## Feedback 
Needs work:
- Potential to link this from "Getting Access to Datadog"
- See if this document can be split up into sections to reduce the "wall of text"
- Optionally rename the document
- Link/Compare to existing Datadog documentation

## Acceptance Criteria
- [x] The document is updated and shared with the team for review

## Refinement Guidance - Check the following before working on this issue: 
- [x] _Team label assigned ("platform-tech-team-2")_
- [x] _Epic assigned (if needed)_ 
- [x] _Estimated (points assigned)_
- [x] _Sprint assigned (once planned)_
- [x] _Team member(s) assigned_

**Comment by jhouse-solvd** [comment]
@it-harrison - I made a few updates to this page. Forgive me if I overstepped your work! Please continue with additional updates as needed. :)

**Comment by ph-One** [comment]
Ian has DD access, but needs additional privs for write access

**Comment by it-harrison** [comment]
I was unable to add a screenshot to show the "New" button for creating a new API key because I don't have permissions to do that...not sure if it's needed, though.

**Comment by jhouse-solvd** [comment]
This is looking good. Great work, team! 

Closing.
