### ISSUE TITLE
[Monitoring] Update "Get acquainted with Datadog" documentation 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#51761]
i## Description
Update the document based on feedback from the recent mini-workshop with Platform Tech Team 2. 

## Resources 
- [Get acquainted with Datadog](https://vfs.atlassian.net/wiki/spaces/OT/pages/1775435805/Get+acquainted+with+Datadog)

## Feedback 
Needs work:
- Link out to other documents
  - Could be existing dashboards, monitors, or existing Confluence documentation
  - Could be Datadog documentation

## Acceptance Criteria
- [x] The document is updated and shared with the team for review

## Refinement Guidance - Check the following before working on this issue: 
- [x] _Team label assigned ("platform-tech-team-2")_
- [x] _Epic assigned (if needed)_ 
- [x] _Estimated (points assigned)_
- [x] _Sprint assigned (once planned)_
- [x] _Team member(s) assigned_

**Comment by it-harrison** [comment]
In the [Resources section](https://vfs.atlassian.net/wiki/spaces/OT/pages/1775435805/Get+acquainted+with+Datadog#Resources) I added a link to [Creating Datadog Monitors](https://vfs.atlassian.net/wiki/spaces/TT2/pages/2423914751/Creating+Datadog+Monitors), which is a document in the Tech Team 2 Confluence Space; we might want to move this document to the Infrastructure Space. Or we might want to remove the link for now.

**Comment by jhouse-solvd** [comment]
@it-harrison - Thanks for this! I'll give it a review soon, along with the team.

**Comment by it-harrison** [comment]
also: update screenshots

**Comment by it-harrison** [comment]
link to platform specific dashboards and updated screenshots added

**Comment by jhouse-solvd** [comment]
This is looking great! Thanks for the excellent updates, Ian! 

Closing.
