### ISSUE TITLE
MDT- Introduction page- design

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#5176]
User story: As a Veteran interested in reordering medical device resupply items, I need an introduction about the ordering process so I know what to expect before placing my order. 

## Tasks
- [ ] Create a high fidelity mockup of the order flow introduction page 
- [ ] Upload mockup to Invision and indicate initial focus point as a comment 

## Acceptance Criteria:
- Mockup aligns with VA.gov’s design system 
- There is an alert notifying the Veteran that they are logged in
- The subway map contains all of the steps the Veteran can expect during the order flow
- (Optional) Any additional helpful content for the Veteran is included 
- The screen’s initial focus point is incorporated
- Sketch artboards are uploaded to Invision and linked in this ticket as a comment

## Dep/Blockers
- No currently known dependencies

**Comment by rileyorr** [comment]
@leahkeeler I'm going to close this ticket because the introduction screen has been completed for a while so this ticket isn't necessary anymore
