### ISSUE TITLE
[BE] [SPIKE] Investigate error in vets-api for pre-check-in to day-of check-in transition

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#51783]
## Description

CIE Eng team had a co-working session to pass pre-check-in users to day-of check-in.  While returning appointment data from lorota to front-end,  [vets-api](https://vagov.ddog-gov.com/logs?query=3d7a365f-4e86-4bcb-8e35-4e9bfa3552eb&cols=host%2Cservice&event=AgAAAYWYZMe6bcxqogAAAAAAAAAYAAAAAEFZV1laTm5OQUFBUDYtWjJvT1JpUWdBRAAAACQAAAAAMDE4NTk4NjQtZWMxMS00MjU3LTllMDUtMjA0MDRiYzJjZDJj&index=&messageDisplay=inline&stream_sort=time%2Cdesc&viz=stream&from_ts=1673298269016&to_ts=1673299169016&live=true) threw an internal server exception. (Reference [slack thread](https://dsva.slack.com/archives/C02G6AB3ZRS/p1673300540961979?thread_ts=1673300509.639779&cid=C02G6AB3ZRS))

The task is to investigate the cause of the failure in vets-api & see if the approach can be an alternate path for routing pre-check-in users to day-of check-in when the link clicked after 12 AM on the day of the appointment.

## Acceptance Criteria
- [ ] Identify the issue
- [ ] Discussion within Engineering team

**Comment by sarahknoppA6** [comment]
This is not pointed because it is a low priority for this sprint- we've agreed to spend whatever remaining time is available for the sprint on it.

**Comment by kanchanasuriya** [comment]
Reason for failure from vets-api, is demographics data not available in lorota.  When pre-check-in UUID gets passed to day-off checkin, especially when a veteran hasn’t completed the pre-check-in workflow, lorota doesn’t have the demographics data.  Front end will not have veteran’s contact information, emergency contact or next of kin.
