### ISSUE TITLE
Remove Pact from vets-api

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#51797]

**Comment by holdenhinkle** [comment]
PR - https://github.com/department-of-veterans-affairs/vets-api/pull/11493

Merged and done.

**Comment by LindseySaari** [comment]
Announcement posted here: https://dsva.slack.com/archives/C03R5SBELQM/p1673360881038769

**Comment by LindseySaari** [comment]
PRs for reference:
Backend changes: https://github.com/department-of-veterans-affairs/vets-api/pull/11493#pullrequestreview-1239120829
FE Changes: https://github.com/department-of-veterans-affairs/vets-website/pull/23073
PR to remove contract test stuff from product-directory repo - https://github.com/department-of-veterans-affairs/product-directory/pull/608
