### ISSUE TITLE
Create a Box for Alyssa with Login.gov DataDog Reporting 

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#51808]
- Total saml users logged in past month (you may need to set the time picker in the top to be 12/1-12/31): https://vagov.ddog-gov.com/dashboard/52g-hyg-wcj/vsp-identity-monitor-dashboard?
from_t[…]&to_ts=1672549140000&live=false&tile_focus=4000704399837860 + total SiS successful user logins for December: https://vagov.ddog-gov.com/dashboard/3di-esj-7wy/identity-log-queries?from_ts=16698708[…]&to_ts=1672549140000&live=false&tile_focus=6205513804236828 (you will need to add the two together for the total successful logins in December)

- Number of authenticated (proofed) users for December: https://vagov.ddog-gov.com/dashboard/52g-hyg-wcj/vsp-identity-monitor-dashboard?from_t[…]&to_ts=1672549140000&live=false&tile_focus=4000704399837860

- Number of new accounts for December(its just the view from va.gov, but your looking for the contexts that have _signup in the name. Add all of them together): https://vagov.ddog-gov.com/dashboard/52g-hyg-wcj/vsp-identity-monitor-dashboard?from_t[…]&to_ts=1672549140000&live=false&tile_focus=4000704399837860

**Comment by joeniquette** [comment]
Complete: https://vagov.ddog-gov.com/dashboard/52g-hyg-wcj/vsp-identity-monitor-dashboard?from_ts=1673548204319&to_ts=1673634604319&live=false&tile_focus=545478880764756

One caveat: the "verified logins" per month will not be accurate. Explained in the dashboard why.
