### ISSUE TITLE
Discovery: Ruby 3.0 Upgrade Blockers

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#51827]
What blockers are there to upgrade Vets API from Ruby 2.7 to Ruby 3.0?

## Checks for going live
- [x] **Native**: `bundle install` can be performed successfully
- [x] **Docker**: `bundle install` can be performed successfully
- [ ] **Native**: Complete **test suite** runs locally and passes
- [ ] **Docker**: Complete **test suite** runs locally and passes
- [ ] **GitHub**: Complete **test suite** runs and passes
- [x] **Native**: App **boots** locally and **responds** at its root route
- [ ] **Docker**: App **boots** locally and **responds** at its root route
- [ ] **BRD**: App **boots** and **responds** at its root route
- [ ] **EKS**: App **boots** and **responds** at its root route

## Issues to create
- [ ] Collect 2.7 warnings by running suite with warnings enabled
- [ ] Enable latest cops in Rubocop to aid in upgrade
- [ ] Investigate active_model_serializers and our path forward ([jsonapi-rb](http://jsonapi-rb.org)?)

**Comment by ericboehs** [comment]
As part of my preliminary research, I've found the test suite on GitHub Actions runs until the six-hour timeout is reached. Locally, however, the suite runs much faster than I'm used to (~10x) and fails with 975 test failures.

A lot of the failures look to be related to [the 3.0 change in keyword arguments](https://blog.saeloun.com/2019/10/07/ruby-2-7-keyword-arguments-redesign.html). I've already begun fixing some of these in order to get the test suite to run.

Another error I'm seeing is in regards to calling `object` on ActiveModel::Serializer. It seems to be set to `false` rather than an Array. We're using a [forked version](https://github.com/department-of-veterans-affairs/active_model_serializers/commits/master) of AMS 0.10.4. In later versions of AMS, they replace the use of `object` with `collection` (might be related).

I'm not certain of the level of effort required to upgrade here yet.

Next steps will be to compile the types of errors within the 975 test failures.

**Comment by oseasmoran73** [comment]
Helping Eric as I have some extra bandwidth. Was able to get local EKS environment up and running for testing and Docker is not playing nicely out of the box (presume issue on my end). Will debug and aid Eric as needed

**Comment by ericboehs** [comment]
Looking to pair with Oseas on this. I got Ruby 3.0 booting within Docker on my 3-0-5 branch. I need to apply my 3-0-5 changes to the k8s branch and see if it works there as well.

**Comment by ericboehs** [comment]
I created tickets around this. Doing some more K8s discovery and then closing this out.

- [🎫 53655: Discovery: Capture Ruby 2.7 Warnings](https://github.com/department-of-veterans-affairs/va.gov-team/issues/53655)
- [🎫 53657: Discovery: Capture Ruby 3.0 Test Failures](https://github.com/department-of-veterans-affairs/va.gov-team/issues/53657)
- [🎫 53658: Determine if latest version of Bundler poses any issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/53658)

**Comment by oseasmoran73** [comment]
@ericboehs Have some bandwidth this sprint to help out with this again. Is there a branch I can pull from?

**Comment by npeterson54** [comment]
Rollingi this into next sprint as there is some potential discovery remaining
