### ISSUE TITLE
Milestone 2 - Datadog monitor for acceptable verified credential

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#51836]
* Datadog monitor should be created to ingest logs written from the sidekiq scheduled job that reports queries from the `user_acceptable_verified_credential` table.
* Differences in values from these logs should allow for week by week, month by month, status of acceptable verified credential uptake

**Comment by bosawt** [comment]
@joeniquette Can you describe what information you'd like in these monitors? This would be for ongoing avc reporting

**Comment by bramleyjl** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/11657 adds a log on AVC creation and update

- `'[UserAcceptableVerifiedCredentialUpdater] - User AVC Updated'`
- { `user_account_id`, `idme_uuid`, `logingov_uuid` }

**Comment by joeniquette** [comment]
- Create a CRON Sidekiq job
  - Periodically queries AVC table, returns how many users have AVC, IVC
    - How many users don't have an AVC or IVC
      - Based on each CSP
  - How many accounts do not have an AVC or IVC
    - ID.me
    - Login.gov
    - DS Logon
    - MHV Premium
- Datadog Monitor that watches the logs from the Sidekiq job

**Comment by joeniquette** [comment]
@bosawt happy to pull the thread on this at our call later today

**Comment by rileyanderson** [comment]
@joeniquette I am going to be starting on https://github.com/department-of-veterans-affairs/va.gov-team/issues/51835. Is there a guide to how you want the log messages to be formatted?

**Comment by rileyanderson** [comment]
@joeniquette this [PR](https://github.com/department-of-veterans-affairs/vets-api/pull/11854) has been merged and the [docs](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/vsp/teams/Identity/Documentation/AVC_IVC_logs.md) have been updated. lmk if you have questions or need help on anything.

**Comment by joeniquette** [comment]
@rileyanderson will the running of the cron job set the values to their totals and then the add and remove statsd will update as we go?

**Comment by joeniquette** [comment]
How many MHV accounts do not have an AVC or IVC? - this comes from the sidekiq which will be a statsd
How many DSLogon accounts do not have an AVC or IVC? - this comes from the sidekiq which will be a statsd

How many new AVC or IVC accounts are being created? - statsd already completed for this

**Comment by joeniquette** [comment]
Complete
