### ISSUE TITLE
Update link to form on SGLI page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#51838]
## Issue Description

The life insurance business line updated the form for applying for an SGLI disability extension. We currently have a broken link on our [SGLI page](https://www.va.gov/life-insurance/options-eligibility/sgli/). Instead of linking directly to the form, we should now link to the form landing page so that if it gets updated again the link won't break.

New link: https://www.benefits.va.gov/insurance/forms/8715.htm

We'll also need to change the language to something like "Get the SGLI Disability Extension Application to download" since we aren't sending users directly to download the form.

## Tasks
- [x] Update link and text (Laura)
- [x] Copyedit (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] Link no longer broken on live page

**Comment by laurwill** [comment]
Hi @megzehn , 
I updated 3 PDF links on this page to the new landing pages — after you copyedit the draft alert, we can send the page over for approval and then pub all these changes together.
http://preview-prod.vfs.va.gov/preview?nodeId=767

**Comment by megzehn** [comment]
sounds good! Thanks, @laurwill. 

These changes look good. Leaving in drafts for now.

**Comment by RLHecht** [comment]
These changes are live. Closing ticket.
