### ISSUE TITLE
Milestone 1 - Logs should occur upon authentication to describe user's acceptable_verified_credential

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#51833]
* Upon authentication, when a `user_acceptable_verified_credential` entry is updated, a rails log should occur that describes the `user_account.uuid`, and the values of the user's `acceptable_verified_credential` and `idme_verified_credential`

**Comment by joeniquette** [comment]
@bosawt Will this include a statsd of the totals? I see a task to add a datadog monitor, but what is going to be the data source for that? Being able to say "x% have an AVC" would require a complete picture, logs wont be able to give us that. Unless you have other ideas how this will occur?
