### ISSUE TITLE
Milestone 2 - Create a Sidekiq cron job to report acceptable verified credential status

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#51835]
*Sidekiq job should be created, and appropriate entry added in the sidekiq scheduler file, which will make various queries on the `user_acceptable_verified_credential` table and write rails logs that data dog can ingest.
* The queries should discover:
  * How many users don't have an AVC or IVC
    * Based on each CSP
  * How many accounts do not have an AVC or IVC
    * ID.me
    * Login.gov
    * DS Logon
    * MHV Premium

**Comment by joeniquette** [comment]
Would this be able to give us numbers of how many total we know of? I assume this won't be accurate until we run a migration against the entire userverification table. But I want to confirm we will be able to answer the question "x% of va.gov users have an AVC" on a regular (say daily) interval in order for us map the progress. We will have to caveat that the data may go down, so the totals of known positive AVC or IVC is likely going to be the best number we have. We know the cap will be around 11 million users, but not all of those users will need to be converted over.

**Comment by rileyanderson** [comment]
based on [this comment ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/51836#issuecomment-1410896837) seems like we want to include counts of who has verified credentials and who doesn't so I put both in.

**Comment by rileyanderson** [comment]
Log message: `[UserAcceptableVerifiedCredentialCountsJob] - Ran`

Data Fields:
- `timestamp`: The date the data was collected for. The job will collect the previous days data (`1.day.ago.all_day`).
- `avc`: Acceptable Verified Credential
  -  `all`: All UserAccounts that have an Acceptable Verified Credential.
     - `added`: Count added on `{timestamp}`.
     - `total`: Count of all.
  - `idme`: ID.me verified UserAccounts that have an Acceptable Verified Credential.
    - `added`: Count added on `{timestamp}`.
    - `total`: Count of all.
  - `logingov`: Login.gov verified UserAccounts that have an Acceptable Verified Credential.
    - `added`: Count added on `{timestamp}`.
    - `total`: Count of all.
  - `dslogon`: DS Logon verified UserAccounts that have an Acceptable Verified Credential.
    - `added`: Count added on `{timestamp}`.
    - `total`: Count of all.
  - `mhv`: MyHealtheVet verified UserAccounts that have an Acceptable Verified Credential.
    - `added`: Count added on `{timestamp}`.
    - `total`: Count of all.
- `ivc`: ID.me Verified Credential
  -  `all`: All UserAccounts that have an ID.me Verified Credential.
     - `added`: Count added on `{timestamp}`.
     - `total`: Count of all.
  - `idme`: ID.me verified UserAccounts that have an ID.me Verified Credential.
    - `added`: Count added on `{timestamp}`.
    - `total`: Count of all.
  - `logingov`: Login.gov verified UserAccounts that have an ID.me Verified Credential.
    - `added`: Count added on `{timestamp}`.
    - `total`: Count of all.
  - `dslogon`: DS Logon verified UserAccounts that have an ID.me Verified Credential.
    - `added`: Count added on `{timestamp}`.
    - `total`: Count of all.
  - `mhv`: MyHealtheVet verified UserAccounts that have an ID.me Verified Credential.
    - `added`: Count added on `{timestamp}`.
    - `total`: Count of all.
- `no_avc`: No Acceptable Verified Credential
  -  `all`: All UserAccounts that DO NOT have an Acceptable Verified Credential.
     - `added`: Count added on `{timestamp}`.
     - `total`: Count of all.
  - `idme`: ID.me verified UserAccounts that DO NOT have an Acceptable Verified Credential.
    - `added`: Count added on `{timestamp}`.
    - `total`: Count of all.
  - `logingov`: Login.gov verified UserAccounts that DO NOT have an Acceptable Verified Credential.
    - `added`: Count added on `{timestamp}`.
    - `total`: Count of all.
  - `dslogon`: DS Logon verified UserAccounts that DO NOT have an Acceptable Verified Credential.
    - `added`: Count added on `{timestamp}`.
    - `total`: Count of all.
  - `mhv`: MyHealtheVet verified UserAccounts that DO NOT have an Acceptable Verified Credential.
    - `added`: Count added on `{timestamp}`.
    - `total`: Count of all.
- `no_ivc`: No ID.me Verified Credential
  -  `all`: All UserAccounts that DO NOT have an ID.me Verified Credential.
     - `added`: Count added on `{timestamp}`.
     - `total`: Count of all.
  - `idme`: ID.me verified UserAccounts that DO NOT have an ID.me Verified Credential.
    - `added`: Count added on `{timestamp}`.
    - `total`: Count of all.
  - `logingov`: Login.gov verified UserAccounts that DO NOT have an ID.me Verified Credential.
    - `added`: Count added on `{timestamp}`.
    - `total`: Count of all.
  - `dslogon`: DS Logon verified UserAccounts that DO NOT have an ID.me Verified Credential.
    - `added`: Count added on `{timestamp}`.
    - `total`: Count of all.
  - `mhv`: MyHealtheVet verified UserAccounts that DO NOT have an ID.me Verified Credential.
    - `added`: Count added on `{timestamp}`.
    - `total`: Count of all.

**Comment by rileyanderson** [comment]
Log message: `[UserAcceptableVerifiedCredentialCountsJob] - Ran`

Data Fields:
- `timestamp`: The date the data was collected for. The job will collect the previous days data (`1.day.ago.all_day`).
- `avc`: Acceptable Verified Credential
  -  `all`: All UserAccounts that have an Acceptable Verified Credential.
     - `added`: Count added on `{timestamp}`.
     - `total`: Count of all.
  - `idme`: ID.me verified UserAccounts that have an Acceptable Verified Credential.
    - `added`: Count added on `{timestamp}`.
    - `total`: Count of all.
  - `logingov`: Login.gov verified UserAccounts that have an Acceptable Verified Credential.
    - `added`: Count added on `{timestamp}`.
    - `total`: Count of all.
  - `dslogon`: DS Logon verified UserAccounts that have an Acceptable Verified Credential.
    - `added`: Count added on `{timestamp}`.
    - `total`: Count of all.
  - `mhv`: MyHealtheVet verified UserAccounts that have an Acceptable Verified Credential.
    - `added`: Count added on `{timestamp}`.
    - `total`: Count of all.
- `ivc`: ID.me Verified Credential
  -  `all`: All UserAccounts that have an ID.me Verified Credential.
     - `added`: Count added on `{timestamp}`.
     - `total`: Count of all.
  - `idme`: ID.me verified UserAccounts that have an ID.me Verified Credential.
    - `added`: Count added on `{timestamp}`.
    - `total`: Count of all.
  - `logingov`: Login.gov verified UserAccounts that have an ID.me Verified Credential.
    - `added`: Count added on `{timestamp}`.
    - `total`: Count of all.
  - `dslogon`: DS Logon verified UserAccounts that have an ID.me Verified Credential.
    - `added`: Count added on `{timestamp}`.
    - `total`: Count of all.
  - `mhv`: MyHealtheVet verified UserAccounts that have an ID.me Verified Credential.
    - `added`: Count added on `{timestamp}`.
    - `total`: Count of all.
- `no_avc`: No Acceptable Verified Credential
  -  `all`: All UserAccounts that DO NOT have an Acceptable Verified Credential.
     - `added`: Count added on `{timestamp}`.
     - `total`: Count of all.
  - `idme`: ID.me verified UserAccounts that DO NOT have an Acceptable Verified Credential.
    - `added`: Count added on `{timestamp}`.
    - `total`: Count of all.
  - `logingov`: Login.gov verified UserAccounts that DO NOT have an Acceptable Verified Credential.
    - `added`: Count added on `{timestamp}`.
    - `total`: Count of all.
  - `dslogon`: DS Logon verified UserAccounts that DO NOT have an Acceptable Verified Credential.
    - `added`: Count added on `{timestamp}`.
    - `total`: Count of all.
  - `mhv`: MyHealtheVet verified UserAccounts that DO NOT have an Acceptable Verified Credential.
    - `added`: Count added on `{timestamp}`.
    - `total`: Count of all.
- `no_ivc`: No ID.me Verified Credential
  -  `all`: All UserAccounts that DO NOT have an ID.me Verified Credential.
     - `added`: Count added on `{timestamp}`.
     - `total`: Count of all.
  - `idme`: ID.me verified UserAccounts that DO NOT have an ID.me Verified Credential.
    - `added`: Count added on `{timestamp}`.
    - `total`: Count of all.
  - `logingov`: Login.gov verified UserAccounts that DO NOT have an ID.me Verified Credential.
    - `added`: Count added on `{timestamp}`.
    - `total`: Count of all.
  - `dslogon`: DS Logon verified UserAccounts that DO NOT have an ID.me Verified Credential.
    - `added`: Count added on `{timestamp}`.
    - `total`: Count of all.
  - `mhv`: MyHealtheVet verified UserAccounts that DO NOT have an ID.me Verified Credential.
    - `added`: Count added on `{timestamp}`.
    - `total`: Count of all.

**Comment by rileyanderson** [comment]
> @rileyanderson thank you, I added your data here: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/vsp/teams/Identity/Documentation/AVC_IVC_logs.md

Thanks! Idk what happened with my comments lol. The perils of having too many tabs open I guess 😆
