### ISSUE TITLE
Update Project Intake workflow diagram with new site information

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#51844]
## Purpose
[New information](https://vfs.atlassian.net/wiki/spaces/~534593234/pages/2349302087/Introducing+Projects) has been provided on how the Intake is intended to work.

## Tasks
- [x] Update the workflow to match this new information

## Acceptance Criteria
- [x] [Workflow](https://lucid.app/lucidchart/e2d771f0-6d82-4f13-8411-9e983ec0687d/edit?invitationId=inv_fc1e26fe-e5c7-4a42-902d-2999a568b8b6&page=HWuo9Qg1GJTA#) matches spirit of the information page

**Comment by twoangstroms** [comment]
Note that the link to v1.3 is https://lucid.app/lucidchart/e2d771f0-6d82-4f13-8411-9e983ec0687d/edit?invitationId=inv_fc1e26fe-e5c7-4a42-902d-2999a568b8b6&page=HWuo9Qg1GJTA#
