### ISSUE TITLE
Post Appointment Reminders Sending Appointment Reminders CC

### ISSUE THREAD

**Issue by shanemelliott** [department-of-veterans-affairs/va.gov-team#51858]

**Comment by SlakrHakr** [comment]
This might be something we can discuss next week.
I'm 100% sure the ask here, but I'm guessing the work would primarily take place here?
https://github.com/department-of-veterans-affairs/vetext/blob/f63ba3200e99fd0c178ab2335979d4579685c96e/ll-vetext-service/src/main/java/gov/va/med/lom/vetext/tasks/workers/impl/AppointmentRemindersWorkerImpl.java#L308

**Comment by lindsay-insco** [comment]
No longe an issue
