### ISSUE TITLE
[Design] [PRE-CHECKIN] Update canceled appointment behavior & messaging

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#51866]
## Background

We [learned yesterday](https://dsva.slack.com/archives/C02UP02HHGX/p1673458292082829) that patient appointments are often canceled and rebooked at the same time rather than being edited. At this time, those appointments will all be put in LoROTA for a given pre-checkin UUID. Since we currently show the "appointment canceled" messaging if any appointment in the list is canceled, Veterans sometimes see that message when they actually have a valid appointment at that time.

[Related FE ticket
](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/51862)

## Changes

1. Only show the "Your appointment is canceled" messaging if _all_ appointments in LoROTA are canceled. (current `appointment-canceled` error case)
2. If one but not all appointments are canceled, show the [generic error page](https://app.abstract.com/projects/d9d1d6b4-192b-4ee6-95ab-e7cf42a1ac03/branches/main/commits/d90db68c5faaa10cdf19883c3ce1abaf18c7c359/files/db5cbb64-bed3-48f8-9512-2e2eef457dd1/layers/DDD7A7F4-887E-4141-892A-49AD380E345A?collectionId=336838b5-e55e-4aeb-9b4f-6d26bd66c110&collectionLayerId=6e6d1582-8dd0-4a1b-b7f8-a25f0d72ba80&mode=design&sha=d90db68c5faaa10cdf19883c3ce1abaf18c7c359)

![Screenshot 2023-01-12 at 10.03.36.png](https://images.zenhubusercontent.com/5f6b95e44ede53b783cfcc8e/17f6e2d5-22dc-4f37-a2cc-3fd542f73dd1)

## Tasks
- [x] In Sketch, add a page for this scenario. For example, add the generic error message with the name of "One but not all appointments are canceled." 
- [ ] Add use case into the errors section in the product guide for pre-checkin

**Comment by benbrasso-agile6** [comment]
@wullaski can you toss in two screenshots from local for phone appts, 1) where 1 is cancelled, and 2) where two phone appts are cancelled

**Comment by benbrasso-agile6** [comment]
Updated in pre-check-in sketch file, production file, and unified check in file

**Comment by benbrasso-agile6** [comment]
Re-pinging if anyone can help me with` two screenshots from local for phone appts, 1) where 1 is cancelled, not all appts, and 2) where two phone appts are cancelled` tomorrow. Thanks! @wullaski @brianseek @lee-delarm6

**Comment by brianseek** [comment]
@benbrasso-agile6 here is the screenshot, its the same for both scenarios:
[Uploading... localhost_3001_health-care_appointment-pre-check-in_introduction (1).png]

**Comment by brianseek** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ1N1IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--28ea3fc53efbeed53539d2bfc3f6c1ce9fb45dcc/localhost_3001_health-care_appointment-pre-check-in_introduction%20%281%29.png)

**Comment by benbrasso-agile6** [comment]
Pre check in in person

[One appt of many are cancelled](https://www.sketch.com/s/ef203d41-ca12-4088-bed4-c870fd34c945/a/MmGMRwa#Version)

[All appts in LoROTA entry are cancelled](https://www.sketch.com/s/ef203d41-ca12-4088-bed4-c870fd34c945/a/5nAoQjL#Version)

Pre check in phone appt 

One appt of many are cancelled - same as in person 

[All appts in LoROTA entry are cancelled](https://www.sketch.com/s/ef203d41-ca12-4088-bed4-c870fd34c945/a/K04L0z1#Version)

^^ I think it SHOULD be this. @brianseek can you confirm that you don't see an issue in making this change? If so, I'm going to create a backlog ticket for the FE work here.

**Comment by brianseek** [comment]
We have a ticket in the backlog to remove the cancelled message all together https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/59639

That should supersede any changes here.

**Comment by benbrasso-agile6** [comment]
Bleh, then why am I working on this ticket lol. 

Ahhh, let's check in with @loripusey when she returns tomorrow.

**Comment by brianseek** [comment]
I was wrong though, currently phone is the same as in person when all appts are cancelled. My mocker just failed to update when I was making the screenshot for the second scenario. 

![localhost_3001_health-care_appointment-pre-check-in__id=46bebc0a-b99c-464f-a5c5-560bc9eae287 (2)](https://github.com/department-of-veterans-affairs/va.gov-team/assets/13967174/e22e4609-684f-4107-aa1c-cd2f65c9fb01)

**Comment by benbrasso-agile6** [comment]
Right, but I think that "Or talk to a staff member..." sentence should be removed for the scenario we're talking about. So, again, wondering if I create a FE ticket for that work or not.

**Comment by loripusey** [comment]
@loripusey

**Comment by benbrasso-agile6** [comment]
@kellysmith1008 FYI ^^ re, cancelled appts
