### ISSUE TITLE
Egress IP range change

### ISSUE THREAD

**Issue by nathanhruby** [department-of-veterans-affairs/va.gov-team#5186]
## User Story or Problem Statement

The VAEC will change the range of IP address our outbound traffic uses.  As a result, external partners that we integrate with may need to update their firewall and/or configurations to allow for our traffic.

## Goal
- External partners are made aware of this change ahead of the change

## Objectives or Key Results this is meant to further
- XXX: unknown

## Acceptance Criteria
- [ ] Document listing our possible egress IP's
- [ ] List of external partners and contact info
- [ ] Notifications to those partners pointing at docs and timeline for change

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by wyattwalter** [comment]
The only partner that I know of that cares about this is search.gov. We should be able to let them know to add the new subnets.

We should share this info with VSP engineers for input on other partners that may care and create a place to stash information about who might care.

**Comment by wyattwalter** [comment]
We don't know when this changes or what the new subnets are. Leaving in backlog for the moment, but we should just close it if we don't hear more.

**Comment by wyattwalter** [comment]
Handled this in https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/82. I forgot that there was already a ticket for it.
