### ISSUE TITLE
[FE] My VA Healthcare: Remove/cleanup drupal flag

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#51896]
## Background
Post-transition from `isCerner` to the drupal source of truth to determine whether a VAMC System uses VistA or Cerner as its EMHR system we need to clean up and remove the feature flag.

## Tasks
- [ ] Remove the flag `myva_cerner_from_drupal` from staging and prod (specifically from vets api and the frontend moc api)
- [ ] Test

## Acceptance Criteria
- [ ] The feature flag is gone from the code and feature flag manager in staging and prod

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_  Another dev who can check the code
- _How can this work be validated?_ feature flag is gone from code and feature flag manager in staging and prod

## Resources
Previous drupal tickets: 
- #47956
- #50043
- #50173
- #51517

**Comment by allisonlu** [comment]
Note to self: [this is the Slack thread](https://dsva.slack.com/archives/C52CL1PKQ/p1672939719325459) that you were tagged in, with context from Adam

**Comment by allisonlu** [comment]
PR opened on `vets-api`: https://github.com/department-of-veterans-affairs/vets-api/pull/11836

**Comment by allisonlu** [comment]
PR opened on `vets-website` (to remove instances of the flag in mock tests): https://github.com/department-of-veterans-affairs/vets-website/pull/23410

**Comment by allisonlu** [comment]
Please validate on staging and make sure the `myva_cerner_from_drupal` feature flag does not exist anymore: https://staging-api.va.gov/flipper/features

**Comment by ajakabcin** [comment]
Confirmed in the staging flipper manager that the `myva_cerner_from_drupal` feature flag no longer exists. Thanks!

cc @jilladams
