### ISSUE TITLE
Offboarding of Matt Gardner

### ISSUE THREAD

**Issue by nanotone** [department-of-veterans-affairs/va.gov-team#51909]
# Description
Please provide the following information about the individual being offboarded:
- name:
  > William "Matt" Gardner
- team name:
  > OCTO Automated Benefits Delivery
- role on team:
  > Software engineer
- expected last day:
  > 9/8/2022 😬 
- company they work for:
  > Nava PBC
- email: _(Multiple emails listed in order of relevance to VA business, VA, Company, Personal, etc....)_
  > William.Gardner1@va.gov
  > mattgardner@navapbc.com
- GitHub username:
  > @allthesignals
- additional access they may have: _(First line formatted with access titles only. Additional notes may be added on second line after the list.)_
  > SOCKS, AWS 
 
## Acceptance Criteria
*The following steps are performed by the Platform Support team. Detailed instructions found [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/2097545323/Offboard+Team+Member)*
 - [x] Requested removal from DSVA Slack (if applicable. Search for them in Slack)
   > A comment on this ticket prefixed with `/request` (i.e. `/request FirstName LastName`) will send a message to the Slack admins automatically!
 - [x] Remove from [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=0)
 - [ ] Remove from global/config.yml / SOCKS Access removed (if applicable. Search their email in [config.yml](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/global/config.yml))
   > Use the [Remove SOCKS and AWS access Github Workflow](https://github.com/department-of-veterans-affairs/devops/actions/workflows/offboarding.yml) to create a PR to update the `global/config.yml` file and remove the public SSH key. You'll need the user's email address associated with their public key (found in `config.yml`).
 - [ ] AWS Access removed  (if applicable. Search their name in [AWS IAM](https://console.amazonaws-us-gov.com/iamv2/home#/home))
   > Use the [Remove SOCKS and AWS access Github Workflow](https://github.com/department-of-veterans-affairs/devops/actions/workflows/offboarding.yml) to remove user's entry from DSVA AWS. You'll need the user's AWS username (typically `First.Last`).
 - [x] User removed from the VA GitHub Org (user was already removed due to inactivity)

 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/platform-analytics-insights-team , @department-of-veterans-affairs/confluence-admins, @department-of-veterans-affairs/platform-design

**Comment by michelle-dooley** [comment]
No Domo or GA.

**Comment by rmtolmach** [comment]
✅ SOCKS and AWS removed in https://github.com/department-of-veterans-affairs/devops/pull/12566
