### ISSUE TITLE
Adding [multiple users] to DSVA Slack

### ISSUE THREAD

**Issue by bryan-riley-va** [department-of-veterans-affairs/va.gov-team#51912]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

<describe the request>
We are adding many users to DSVA slack to support upcoming work of moving MyHealtheVet (MHV) functionality into VA.gov.  The users in this ticket are split into two groups.   Lauren Alexanderson said she could assist with this ticket.

-The first group is a list of users that do not have any Slack username associated to their VA email address.  
-The second group have users associated to their VA email address, however they are in other workspaces (Lighthouse, DO, etc).  They need to be able to get into DSVA Slack.

Are you requesting to add an individual as a:

- Full member **(Full Member), although I'm not certain how the users that exist in other Workspaces should be handled.**
- Single guest
- Multi-channel
- Switching from single-channel to multi-channel?
- What channel(s) do they need to be added to?

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

We aim to complete slack requests within 24hrs.

**-Please add/invite this list of users to DSVA workspace:**
salome.ago@va.gov
maruf.ahmed@va.gov
tanner.bird@va.gov
matthew.campbell1@va.gov
robert.fenwick@va.gov
cody.frederickson@va.gov
Logan.Fricke@va.gov
cheryl.gabello@va.gov
kenneth.gary@va.gov
Bhanu.Goparaju@va.gov
george.goslin@va.gov
abdelhalim.hmalat@va.gov
michael.jacobsen@va.gov
Craig.Ledbetter@va.gov
laura.meier@va.gov
ryan.mosey@va.gov
krshnarao.nandipati@va.gov
ken.neff@va.gov
patrice.ngang@va.gov
caolan.odomhnaill@va.gov
bhavin.patel2@va.gov
taylor.perry@va.gov
eric.robertson@va.gov
raquel.robertson@va.gov
annapurna.saripalli@va.gov
timothy.steele@va.gov
cindy.stiles@va.gov
david.truong@va.gov
clint.wilde@va.gov
Sirisha.Yeruva@va.gov

**-These users already have Slack logins using their VA, but they are in other workspaces and not DSVA - we need them allowed in DSVA.**
christy.gales@va.gov
tuong.ngo@va.gov
melissa.ashton@va.gov
james.mcnamara@va.gov
jonathan.whetsell@va.gov
swathi.alikatti@va.gov
jeremy.farmer@va.gov
Kenneth.Holm@va.gov
sandeep.karuturi@va.gov
muazzam.khan@va.gov
melinda.latona@va.gov
john.moehrke@va.gov
an.tran@va.gov
emmanuel.tudeme@va.gov
janiece.wade@va.gov
kerry.zallar@va.gov
dan.heverly@va.gov

## Sample Descriptions 
- Please add [_insert email_] as a single-channel guest to [_channel name_].
- Please add [_insert email_] as a multi-channel guest to these channels: [_channel names_].
- Please add [_insert email_] as a full member.
- Please change the status of [_slack username_] from [_current status_] to [_desired status_]

**Comment by lalexanderson-dsva** [comment]
All folks should be added at this point.
