### ISSUE TITLE
IA Request - Yellow Ribbon MVP

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#5192]
What this is: Work with VSP Information Architecture experts to finalize the IA of your product for VA.gov

When to use this: After completion of usability/protyping, prior to moving to development

## Required Inputs:
- [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/yellow-ribbon-mvp/yellow-ribbon-mvp-product-brief.md)
-  [research findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/yellow-ribbon-mvp/research/research-findings.md)
- Desktop: https://vsateams.invisionapp.com/share/P4W04QPWHTK
- Mobile: https://vsateams.invisionapp.com/share/36W0CAZHJ2U
- Content represented in prototype

## Information Architecture Worksheet (Optional)

Provide the following information, as available, to support the final information architecture of your product.

**SEO Keywords**
- Enter a list of keywords used by your target audience when they talk about or search for your content
    - yellow ribbon
    - post 9/11 gi bill

**Proposed site map/page structure** (if more than one page)
- Provide link or image of proposed page structure

**Suggested URL(s)**
- Provide suggested URLs and any background or rationale

**Suggested entry points**
- What is the primary entry point for users to find your new content/tool - consider benefit hub pages, top nav, left nav, footer, profile/account, home page, etc.

**Crosslinking opportunities**
- What additional related areas of the site would links to your content/tool be helpful?

**Redirects/canonical tags**
- Will existing pages/tools need to be redirected or canonicalized?

## Definition of Done
- [x] Issue is created, tagged and assigned to Content and IA team
- [ ] Required information above is complete and optional information provided where available
- [x] IA reviews information and provides final feedback/recommendation on ticket
- [ ] Requesting team closes issue upon implementation

**Comment by mnorthuis** [comment]
@andaleliz Now that research is complete, this would be the next step in the VSP collab cycle.  I forgot I had created this for you awhile back, so if you could fill out the top information and assign it back, I can work on final IA work.  Thank you!

**Comment by andaleliz** [comment]
@mnorthuis thanks for bringing this up! I made some updates to the description but would like to add some more a little later today.

Question, for the bullet point reading

> - Content represented in prototype

What are you looking for there? Do the prototypes suffice?

Also, note that the latest version of the mobile prototype is a bit truncated compared to the desktop. The idea w/ the mobile prototype is to show the developers what is different between the two versions (treatment of search criteria on search results page)

**Comment by mnorthuis** [comment]
@andaleliz As long as I have an idea of the content and H1s, that prototype will work.  Thank you!

**Comment by mnorthuis** [comment]
@andaleliz IA recommendations are provided here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/websites-yellow-ribbon.md

Please take a look and let me know if you have any questions or want to discuss anything.  Some work is needed to identify all the URLs that need to be redirected/retired, that can be captured in the redirect issue #4975.

**Comment by andaleliz** [comment]
Thanks @mnorthuis this seems pretty clear - tagging @AnneHurley as many of the recommendations will involve her to execute.

What are your thoughts on the breadcrumbs once the user is on the search results page in the Yellow Ribbon school finder? In my mock-ups, I have included a separate breadcrumb for [that page](https://vsateams.invisionapp.com/share/RDW2EVOG5AP), but @jenniferlee-dsva commented that we don't typically have that pattern on other similar tools (although it is used on the GI Bill Comparison Tool).  

I'll let you know if I have any more questions. Thanks!

**Comment by mnorthuis** [comment]
That's a good question...I didn't specify one and I'm not sure we need a separate breadcrumb for it from a UX perspective because you can change your search right on the page...its not truly a separate page that has different content that you need to get back to.  We do have a separate breadcrumb step on the GIBCT that takes you back to the initial page, but in that case, there is additional content on that initial page that you lose when you do a search.

**Comment by andaleliz** [comment]
That's the same experience we have - there's some introductory text and a link back to the yellow ribbon hub page on entrance page of our tool that you can only access from that page (not from search results).  The link on the entrance page that reads `Find out of you qualify for the Yellow Ribbon program` will take the user to the Yellow Ribbon hub page, and we don't have any plans to include that same link on the search results page.

**Comment by mnorthuis** [comment]
Ah, ok, I missed that.  If that's the case then we can follow the same precedent set in other tools where the search results will have "> Search results" in the breadcrumb.  I will update the IA recommendations with this.  Thank you for catching that!

**Comment by andaleliz** [comment]
@mnorthuis I added screens to the prototype capturing your recommendations.  Should this ticket stay open until they are implemented by @RLHecht and this goes live? https://vsateams.invisionapp.com/share/P4W04QPWHTK

**Comment by mnorthuis** [comment]
I does not need to stay open, you can close it as soon as you are ready.

**Comment by AkucherGCIO** [comment]
03/04/20 PW Grooming
This ticket is being closed based on Mikki's comment.
@AkucherGCIO - Create the implementation ticket and assign to @AnneHurley @RLHecht as they will be content updates in Drupal.
