### ISSUE TITLE
AWS access for [Cyril Atarah]

### ISSUE THREAD

**Issue by cyriltech** [department-of-veterans-affairs/va.gov-team#51936]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Cyril atarah

### Your Email

cyril.atarah@oddball.io

### Team, Role, and Company of the target individual

VA Platform, platform-tech-team4. DevOps Engineer, Oddball

### Product Manager (PM) name and email

Joe Tice joe.tice@oddball.io

### Product Owner (PO) name and email

Ray Wang Gang.Wang@va.gov

### Desired AWS Access

Access to the vets-api EKS applications. I need read/write access to dev eks terminal to manage preview environment Argo CD application.

### Access Expiration

N/A

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [x] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by rmtolmach** [comment]
@cyriltech Argo terminal access is managed via membership to certain github teams. Since I am a maintainer of the teams you wanted in, I added you. You should now have access.
Teams:
https://github.com/orgs/department-of-veterans-affairs/teams/dsva-vagov-preview-environment-dev-rw/members
https://github.com/orgs/department-of-veterans-affairs/teams/dsva-vagov-preview-environment-dev-ro/members
