### ISSUE TITLE
526ez | Prepare historical claims to be stored in the e-folder for processing

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#51933]
The VBA wants to determine a way to triage and process historical claims impacted by the submission failure. Below are possible requirements to consider:

- Transfer via sftp? Maybe
- All documents in one zip or separate is fine
- The large concern here is making sure the metadata is done in a known universal format so we don't have to manually make any changes
- ~Provide something like a csv text file with definitions (if possible)~ Should not be required if everything is together

**An example format**: FileNumber|DocType|FileCreationDate|Source

**Example**: 123456789|533|2022/01/30|[Vets.gov](http://vets.gov/)

Definition of Done:

- [x] VA will not send raw data files, only pdf representations of the 526, and evidence submitted for each item
- [ ] ~VA will send a manifest of document-level metadata in csv format (file, first name, last name, doc type, file creation date, source example, receipt date if available)~ Manifest should not be required if sent in good enough format
- [x] VBA and [Va.gov](http://va.gov/) will exchange samples by EOD today to determine best format
- [ ] Method of transfer and content approved
- [x] Rejoin by Friday 1/20 to align on path forward
- [x] Decide if peering is a contingency if no other easy transfer methods are available
- [ ] EVSS deployment for REAL prod pull to happen
- [x] Create code to pull and aggregate the files, and plop them into an S3 bucket
- [x] Get S3 Buckets created
- [x] Release in staging
- [x] Test in staging
- [ ] Test transfer method(s) with VA

**Comment by saderagsdale** [comment]
@kylesoskin added Matt's notes to the ticket.

**Comment by saderagsdale** [comment]
Added tasks/notes from yesterday's discussion.

**Comment by kylesoskin** [comment]
@saderagsdale I have added more context to this ticket

**Comment by saderagsdale** [comment]
The query to extract and format the data is dependent on the EVSS fix (currently scheduled for 01/25); without this, the date stamped on the PDFs will be wrong. Once the EVSS fix is in, it will take roughly 1 week (or less) to generate the files.

Assuming EVSS deploys as scheduled on the 25th, we estimate having the PDFs ready by 02/01/23. If EVSS is able to get their change in place sooner, we could begin the PDF work sooner.

**Comment by saderagsdale** [comment]
Historical:

- ready to go code-wise from out end, starting tomorrow AM after EVSS release
- code will loop over each failed submission, compile into a zipped folder, with files inside in the format discussed, and upload each to AWS S3
- method of transfer of information is still yet to be determined
