### ISSUE TITLE
Get SME validation of form detail landing page content & new database fields 

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#5194]
## Get SME validation of form detail landing page content & new database fields 

This task is the next step of ticket #2020 and #4339. This task will get SME confirmation on the forms landing page content and the values of the **Related to** and **Online tool** data fields. 

**Action items for Jen:**

- VHA call with form owners has been scheduled 1/30.
- NCA and VBA form owners have been identified. Scheduling in flight.

**AC:**
[ ] VHA form owners have reviewed and validated. 
[x] NCA form owners have reviewed and validated. 
[x] VBA form owners have reviewed and validated. 
[ ] SME feedback/corrections have been incorporated into copydeck and spreadsheet.
[ ] Form detail landing page URLs have been determined by @mnorthuis and added to copydeck. 
[ ] Form detail landing page copydeck has been copyedited by @RLHecht.

Fysa @ncksllvn @Karak888 @lwalsh617 @kevwalsh @mnorthuis

**Comment by MickinSahni** [comment]
Still in Jen's court but will create a follow-on when the team will pick this up for a subsequent sprint.

**Comment by jenniferlee-dsva** [comment]
VHA forms content out with SMEs for review. VBA call #3 rescheduled for Thursday. NCA SME validated - no changes.

**Comment by MickinSahni** [comment]
Re-associating with more accurate epic - #5590

**Comment by jenniferlee-dsva** [comment]
keeping checklist of validated forms/SME responses. 

**NCA form:**
- Pre-Needs 40-10007 JERRY SOWDERS AND JEFF POTTS REVIEWED W/NO CHANGES

**VBA forms**
•	Compensation Forms (21) – Kayce White and Janel Keyes
•	Education Forms (22) – Rodney Hopkins **LUKE/TAMMY TEAM REVIEWED W/NO CHANGES**
•	Pension & Fiduciary (21P) – Gina Bohr and Juliann Brantseg
•	Loan Guaranty (26) – Brian Lilly, Araceli Kawakami, Iyabo Morrison, Charnae Richardson and Deborah Stewart
•	Appeals Management (20) – Shireen Lackey

**VHA forms**
- [following up for form numbers] Delaney Heffner REVIEWED W/NO CHANGES

**Comment by AkucherGCIO** [comment]
03/04/20 PW Grooming
@jenniferlee-dsva - will be thinking about different ways to get feedback from stakeholders.

**Comment by stephorkandatx** [comment]
Closing during grooming
