### ISSUE TITLE
change jenkins to use vfs.va.gov hostname

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#520]
We need to enable Jenkins to use the new vfs.va.gov hostname. Will need to cover:

- [x] announce in engineer meeting, in #vfs-all-teams and #vetsgov-engineers
- [x] test with CMS team that does some Jenkins interaction
- [x] alter the OAuth app in GitHub and ensure login is still functional

**Comment by ricetj** [comment]
@tskinn can we close this?

**Comment by tskinn** [comment]
@ricetj yeah. Everyone is being redirected to the new hostname now. There is a PR to update devops documentation still open if you want to check it out https://github.com/department-of-veterans-affairs/devops/pull/5158

**Comment by ricetj** [comment]
Done

> @ricetj yeah. Everyone is being redirected to the new hostname now. There is a PR to update devops documentation still open if you want to check it out [department-of-veterans-affairs/devops#5158](https://github.com/department-of-veterans-affairs/devops/pull/5158)

Good to go. approved.
