### ISSUE TITLE
[Auth Experience My VA audit UX improvements] PTEMS-QA Test Plan

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#52008]
\[**Product Managers**: Open this ticket **at least 2 Sprints (4 weeks)** before you expect a Platform Staging Review of this Product/Feature.  Then:
- Replace title's **[Product/Feature]** with your actual product/feature name.
- Add yourself to Assignees
- Fill-out sections below.]

**See also**: Relevant [Shared-Support-QA Manual-UI Testing process doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/engineering/qa/manual-ui-testing-process.md) for details.

## Product/Feature summary

\[Provide brief summary of product/feature to be tested on Staging by Shared-Support-QA. Also, be sure to include links to the Product/Feature Outline [or Initiative Brief], Epic, and Design artifacts.]

- Entry URL (in Staging or Drupal-preview): staging.va.gov/my-va
- Product/Feature Outline: [My VA audit ux improvements](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/2022-audit#project-outline-my-va-audit-updates-and-documentation)
- Product/Feature Epic: #41934
- Product/Feature Copy deck(s): in design
- Product/Feature Design prototypes: 

## Product-team SMEs

\[For any Practice-areas worked by 2+ team-member, clarify who specifically is assigned to this initiative/project.  Leave blank for other areas.\]

Design/Research: @aagosto90 
Content/IA: @DanielleThierryUSDSVA 
Front-end: _our previous FE dev (Taylor Mitchell) is no longer on the team, we have a new FE dev (Allison Lu) starting 1/18_
Back-end: @tpharrison 
QA: Tze-chiu Lei [@tlei123] / Erin Flaherty [@eflaherty]

## Proposed use-cases and Staging test-accounts

\[Provide specific Use Cases (all the different interactive user-flows and data-specific states) to be tested.  Use **[this Product Use Cases template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/product-use-cases-template.md)** -- copy the template's markdown into a new .md file inside your Product folder [next to Product Outline file], then start updating.

**IMPORTANT** for authenticated products (requiring sign-in): Staging test-users must be provided for all authenticated scenarios, and Staging-API test-data created to match the account-specific scenarios.]

[Test case documentation](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-myvaaudit.md)

## How to configure this issue

- [ ] **Product Manager** added to Assignees
- [ ] Attached to a **Milestone** (when will this be completed?)
- [ ] Attached to **Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] Added product-specific label (if any)

## Definition of Done

- [ ] Product references provided by Application Team.
- [ ] Use Cases provided.
- [ ] For authenticated products, Staging test-accounts and mock-data set up for Use Cases above.
- [ ] Test Cases [in TestRail] finalized based on Use Cases above.
- [ ] Test Runs completed on Staging [or Drupal pre-prod environment].
- [ ] Test Reports generated.  These should be provided to Platform at least 4 workdays before [Staging Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html).

**Comment by ajakabcin** [comment]
hey @tlei123 submitting this now to hopefully get on the schedule for mid February (that's sprint 4 for us - 2/15 - 2/28). We're just about done with our test case documentation, doing another run through and filling in a few test users. Will let you know when we're done with that review. Thanks!

**Comment by tlei123** [comment]
Sorry, @ajakabcin !  I thought team leadership had made the communications about Shared Support being "disbanded."   We at the Shared Support team have all been benched since last month due to contract changes.

I suggest contacting Platform to see if they can help or at least connect you with other available QA resources.  I'm actually busy now prepping for a potential new role.
