### ISSUE TITLE
Epic | Profile | Military info discovery

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#52006]
## Important docs

[Research outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/military-information/discovery-and-research/2023-military-info-discovery)

**Comment by mtcA6** [comment]
moving this to the icebox, the research work was completed but we don't have intentions of leveraging the research at this current time.
