### ISSUE TITLE
How are VFS teams reminded/encouraged to utilize the continuous portal?

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#52004]
## Purpose
How do we communicate & market the new portal in an ongoing way so that teams become and remain aware?

This new portal will not be effective if VFS users aren't very aware of its existence, and able to easily engage w/ it while in the middle of other tasks.

## Tasks
- [x] [Generate and evaluate methods](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2637758599/Ongoing+Marketing+for+the+Portal) for keeping teams aware:
- vfs-all-teams reminders via slackbot?
- [x] Team discussion

## Acceptance Criteria
- [x] Methods are decided upon

**Comment by tayism** [comment]
Rolled over to next sprint due to some last refinements based on discussions. Will be able to move forward swiftly.
