### ISSUE TITLE
SOCKS access for Aaron Ponce

### ISSUE THREAD

**Issue by amponce** [department-of-veterans-affairs/va.gov-team#52009]
### Your Name

Aaron Ponce

### Your Email

aaron.ponce@agile6.com

### Your Role and Team

Front End Engineer VSA Debt

### Product Manager (PM) name and email

denise.coveyduc@gcio.com

### Product Owner (PO) name and email

Emily Theis emily.theis@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDNTFWf7Syk6QNu/NqZWUpe69f34UCtqXkHE1OKhhDj9HbFVszbZsbO6qRhYI/Ro+lWjic6EACMpgRpOMan6Qd/nb/CrajXW2VBThNm3X5MUAmLUeUwMiOJ6ZQEJOVykOF1R5zpf5LpkwvKPDqL2uCpc6yAhCQN38yIPIk33FPhHZ5iaRPRCNmF591yIZvnKMp7olYYHjVODqrIBy51FXjNJ5cDPYNMWMeZ6r0F4Mnu79oRLbMjd8nNGLtf7TocmVf5Rs6IsD266eBcV2CFyVw6hvJLH4YoHrbFKiu3BrBeWwqgp2+DUYJaiVh5cHyzl1sj1DePzhgINoSNx2BygSJpuMM5imqxhIgFQmP1fdCwFae2HJrJb0O2Ws+HoT6cUSFZb9bR9qk1K1c9QYNVRXxXz2M/LldGDBLwGcb9K3NlARB5/tTAWsln2Umb9FokbncaGpK7XpjQONvNRTdhScg7BkmG6Ld+FL+k7o3P2kTrBfeEgDfGwaD5Rd/R9m+KYUE= aaron.ponce@agile6-a74.lan

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [x] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by amponce** [comment]
I'm listed in the VFS team roster on line 242

**Comment by HeatherRienks** [comment]
@denisecoveyduc - I am thinking that this ticket might need our help; should this be assigned in another workspace? Not sure it's progressing...

cc: @amponce

**Comment by amponce** [comment]
Thanks @HeatherRienks, I just opened a platform support ticket and heard back right away. I think we'll get this resolved very soon!
