### ISSUE TITLE
SB and PROD: Manifest Files

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#52016]
**PROBLEM STATEMENT**
Vets-api server needs to be migrated to EKS, opening the doors for a micro service based infrastructure.

**DEFINITION OF DONE**
- [ ] Manifest Files: All of the necessary files for the deployment will exist in the appropriate repo

**Comment by laineymajor** [comment]
For the most part this is done. Will require HPA tweaking.
@RachalCassity to review with @rmtolmach.

**Comment by laineymajor** [comment]
For the most part this is done. Will require HPA tweaking.
@RachalCassity to review with @rmtolmach.

**Comment by laineymajor** [comment]
Rachal added notes in #50604

**Comment by LindseySaari** [comment]
disabled db migrate, this ticket is mostly done

**Comment by laineymajor** [comment]
Awesome! Thanks for update :)

**Comment by laineymajor** [comment]
Had to make a tweak to the service resources. Will close.
