### ISSUE TITLE
[Research] Military info discovery: Determine if we want to do an analytics review

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#52010]
### Background

[Research outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/military-information/discovery-and-research/2023-military-info-discovery/README.md#research-outline-expanding-the-military-information-section-of-the-vagov-profile)

Currently, we have a very brief section of the profile dedicated to military info, but we've never really talked to users about it and assessed whether it meets their needs and expectations, or how we could improve it. We've never even asked them if the profile is where they'd expect to find military information. We have a lot to learn.

## Tasks
- [x] Determine if we want to do an analytics review as part of this work
- [x] If so, work with PM or PO to scope that work and get it into planning
 
--------

### Associated tickets

- #51818
- #51821
- #52010
- #51822
- #51886
- #51887
- #51888
- #51889

**Comment by fmccaf1** [comment]
I worked briefly with Liz Lantz to look at Google analytics for this section of the profile. From the view point of people arriving on and leaving from the page, it appears that majority of users are just clicking down on the left-hand nav of the profile, moving through the items.
<img width="1203" alt="image (1)" src="https://user-images.githubusercontent.com/106624475/215821614-1935c3a6-8cc8-41fe-8be3-afee36814f2e.png">

**Comment by Samara-Strauss** [comment]
@fmccaf1 temporarily reopening this, as I have a question:

What question(s) do you have re: analytics that might be helpful? It's totally fine if there's not much, or if you don't feel that an analytics review is necessary at this point in time. However, it's unclear to me if the objective of this ticket has actually been met. What might clarify that is listing out the questions you have and figuring out whether they were answered with the analytics above. If you have questions not answered by the analytics above, we can help figure out how to get you those answers.

**Comment by fmccaf1** [comment]
@Samara-Strauss, good point. 

The main question I have is: Are users seeking out the military info part of their profile intentionally? It's hard to answer this question from the analytics. Liz and I looked at data on where users were coming from when they arrive at military info and where they go next, but that doesn't really get us the exact right info. 

I think it does provide a hint that users are kind of perusing the profile, in that it seems most are just clicking through it, but we don't have certainty on how many are doing that versus the number of people coming to the profile specifically to look at that info. I think we'd be able to posit a lot more from analytics on this question and others like it if access to the profile menu was within My VA, as opposed to clicking "profile" and then getting access to that menu.

**Comment by Samara-Strauss** [comment]
Thanks for this! I get what you're saying about intentionality -- we want to know if people are intentionally seeking this info on VA.gov, yet it's hard to tell that from analytics.

In case it's helpful (totally OK if not), here are links to a couple reports if you want them:

- [Pageviews report](https://analytics.google.com/analytics/web/?authuser=0#/report/content-pages/a50123418w177519031p176188361/explorer-table.plotKeys=%5B%5D&explorer-table.rowStart=0&explorer-table.rowCount=500/): The military info page of the profile ranked 202 in the last week with 24,591 pageviews; Ranked 200 in the last month with 113,373 views; and ranked 193 in the last year with 1,081,384 views.
- [Actions people take on the military info page](https://analytics.google.com/analytics/web/?authuser=0#/report/content-event-pages/a50123418w177519031p176188361/&explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.pagePath:www.va.gov~2Fprofile~2Fmilitary-information~2F,analytics.eventCategory:Interactions/): The top clicks in the last week and month are to the "Learn how to request your DD214" CTA, which we just added in December 2022.

Otherwise, it sounds like there are no further questions, so I'll close this. Feel free to reopen if you think it's necessary!

**Comment by fmccaf1** [comment]
Thanks for these @Samara-Strauss
