### ISSUE TITLE
Community Care Preferred Language page

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#52027]
## Request
Looking for guidance from the development team for the preferred language page on the Community Care request workflow. 
We are assuming the Preferred language page should be displayed regardless but it seems like it has an edge condition. 

### Requirements to Consider
N/A 

---

## Tasks
- Answer the following questions:
  - Q1: If a user does not have an address on file, do we exclude the Preferred language page in the flow? 
  - Q2: If a user has an address on file, the FE is displaying the Preferred language page in the flow? 

Screenshot to capture the comparison between two user ids (patient999@id.me & judy.morrison@id.me) 
<img width="887" alt="Screen Shot 2023-01-16 at 9 10 27 AM" src="https://user-images.githubusercontent.com/90797205/212698405-7843e700-5edd-403e-82c1-0ac33abefdad.png">

## Time Box
_ hours

## Definition of Done
- Tasks are complete
- Research and recommendations are documented in this ticket

**Comment by ryanshaw** [comment]
The screens that are displayed to a user when they are scheduling a new appointment are determined in the front end new appointment flow (`/new-appointment/newAppointmentFlow.js`). 

The logic currently is set as:

* If the user has a residential address, they are shown the the language preference screen
* If the user does not have a residential address, they are show the reason for appointment screen

It would be a small task to change the flow to ensure that everyone is shown the language preference screen, but it would require some changes to the frontend code.

cc: @ldelacosta

**Comment by JRRoof** [comment]
After discussing with Kay Lawyer and @ldelacosta it was determined this was a bug and that veterans should be prompted for their preferred language regardless of the status of their residential address.

**Comment by ldelacosta** [comment]
Validated the changes in staging. No issues to report. 

If no address is on file, the Preferred language page displays (userID: patient999@id.me) 
![Screen Shot 2023-02-01 at 10.19.27 AM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/1b8aa975-c460-4b39-9156-0e3c451475a1)
![Screen Shot 2023-02-01 at 10.20.11 AM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/ad021e9d-3c95-4974-8c48-7952f381d5ca)

If there is an address on file, Preferred language appears in the flow (userID: judy.morrison@id.me) 
![Screen Shot 2023-02-01 at 10.22.45 AM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/b9ced57e-659e-4f4e-9c51-34c7f5ccd898)
![Screen Shot 2023-02-01 at 10.23.21 AM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/c8ba2b8a-74c1-4e2b-8a36-bb8238043d32)

**Comment by beth-wodzinski** [comment]
This passes testing. I am required to select a preferred language, and the preferred language shows up on the Review Your Details page, as shown above.  This happened for all cases. 

The preferred language does not show up on the appointment confirmation page or on the appointment details; is that a requirement? 

Cases tested:
patient999@id.me: no mailing address, no home address
brienne.b.ferrara@id.me: both mailing address and home address. 
claudia.c.lapomarda@id.me: yes mailing, no home. 

I could not find a patient with a home address but no mailing address (and the system does not allow me to remove a mailing address). 

@ldelacosta
