### ISSUE TITLE
[REFINEMENT] Check docs for blatant style guide violations that are easily fixable

### ISSUE THREAD

**Issue by laucon** [department-of-veterans-affairs/va.gov-team#52043]
### For example

- Docs that say "click here" with the link on the word "here"
- Headers not using sentence case

**Comment by johnny-jesensky-adhoc** [comment]
As part of the icebox [audit ticket](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/69802) in Sprint 41. Will need some additional refinement.

**Comment by johnny-jesensky-adhoc** [comment]
I'm going to close this out - think we can handle this as part of a general Content Audit, and this ticket is too broad to be it's own task.
