### ISSUE TITLE
<IA work for education future rates pages> from <Sitewide Content and IA>

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#52049]
## What does your team need support for? Check all that apply.
- [x] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [ ] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
  - [ ] Content support
  - [x] IA support
  
  
*Please be specific about the content or IA support you need and provide any additional documents and/or links that will help us help you. If we need to add a react widget to a page, be sure to provide the code here.*

We need to publish 4 future rates pages for the different education programs (Chapter 30, Chapter 1606, Chapter 35, and Chapter 33) a few months before the rates take effect. We'll also still have the current rates page up on the site. Eventually the future rates will move to the current rates page and the future rates page will have information explaining to users to check back for upcoming rates.

We need to determine where these will live in the IA an what the urls would be. 

The Chapter 33 (Post-9/11 GI Bill) future rates page needs to go live in the middle of February 

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [ ] Yes
  - [x] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
## When do you expect to launch your product to 100% of users?
  
*Please provide an estimated date so our team can create other relevant tickets.*
  
## Supporting artifacts
*Please provide supporting artifacts as available.*

- Link to product outline:
- Link to or attach user flows:
- Link to prototype or mockups:
- Link to any epics/issues that may be helpful:

## Will this work be going through the Collaboration Cycle?
- [x] Yes 
- [ ] No

## When does this work need to be done?
- Estimated launch date: First page to go live 2/15/23
- Estimated staging review date:
- Content and IA work needed by: 

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [ ] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: 
-	Product manager: 
-	Designer: 
-	FE engineer: 
-	Product/team Slack channel:

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by mnorthuis** [comment]
@RLHecht Here's the documentation on the education rates IA, including the future rates.  

**URLs**

**Landing page**
/education/benefit-rates/

**Veteran benefit rates**
- /education/benefit-rates/post-9-11-gi-bill-rates/
- ﻿/education/benefit-rates/post-9-11-gi-bill-rates/future-rates/
- /education/benefit-rates/post-9-11-gi-bill-rates/past-rates/
- /education/benefit-rates/montgomery-gi-bill-active-duty-rates/
- /education/benefit-rates/montgomery-gi-bill-active-duty-rates/future-rates / 
- /education/benefit-rates/montgomery-gi-bill-active-duty-rates/past-rates/
- /education/benefit-rates/montgomery-gi-bill-selected-reserve-rates/
- /education/benefit-rates/montgomery-gi-bill-selected-reserve-rates/future-rates/
- /education/benefit-rates/montgomery-gi-bill-selected-reserve-rates/past-rates/
- /education/benefit-rates/montgomery-gi-bill-600-buy-up-rates/

**Survivor and dependent rates**
- /education/benefit-rates/chapter-35-rates/
- /education/benefit-rates/chapter-35-rates/future-rates/
- /education/benefit-rates/chapter-35-rates/past-rates/
- /education/benefit-rates/fry-scholarship-rates/
- /education/benefit-rates/fry-scholarship-rates/future-rates/
- /education/benefit-rates/fry-scholarship-rates/past-rates/

**Notes:** 
- The above URLs and pages will remain constant - the pages will not be taken down, and URLs will not change. 
- Future rates page - The content of this page will move to the current rates page as of the effective date.  During the period when there are no future rates to show, temporary content will be published to indicate when the next set of rates will be published and any additional helpful content. 
- Current rates page - The content of this page will come from the future rates page once those rates are effective, and will move to the past rates page at the end of their effective dates
- Past rates page - The content of this page will come from the current rates page, and the existing content will be removed from the site. 

﻿![image.png](https://images.zenhubusercontent.com/59ca6a73b0222d5de4792f1d/5c378c71-eee7-455d-b560-272eb14953ab)

**Comment by RLHecht** [comment]
This work is complete. Closing ticket!
