### ISSUE TITLE
Move Action Link on Pre-Check-in Intro Page & Perform A/B Test

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#52054]
## Final Decision
We are not releasing this to production; after A/B testing, it was determined that the location of the link at the bottom was preferred by Veterans

## Background
Although it doesn't have an incredibly higher bounce rate compared to other pages in pre-check-in, do an A/B test to see if the bounce rate decreases on the /introduction page by making the Get Started link more visually prominent. Right now, it uses the action link component. Look to see if there's another acceptable component to use and test.

UX team decision:
Move the action link to the top of the content and do a A/B test with the current design. If bounce rate is not improve, we would like to explore more link UI design.

New mockups:
https://share.goabstract.com/1030e909-2693-4afc-b5b3-b4ee2211089c

[Reference 50505](https://github.com/department-of-veterans-affairs/va.gov-team/issues/50505)

**Comment by loripusey** [comment]
@benbrasso-agile6 are we at a point with the VAOS work that we can move forward with this one?

**Comment by benbrasso-agile6** [comment]
Yes
