### ISSUE TITLE
CoP Collaboration

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#52063]
This epic will serve as a reminder, and be used to track tickets for CoP work picked up every sprint.
This epic will NOT be pointed, but the tickets associated with it will be.

**Comment by laineymajor** [comment]
Lainey to work with Igor on posting update to change announcement slack channel

**Comment by LindseySaari** [comment]
1/25: Closed the `design.va.gov` ticket. Igor set up an alert every Tuesday to review the Jenkins cert scanner job. Tech support needs to write up tickets and @considerable will introduce this calendar to the support team.

**Comment by laineymajor** [comment]
This has been converted to an epic to track individual tickets picked up each sprint from CoP work.
