### ISSUE TITLE
[Design] Personal information update: Update Sketch files to show error alert for when Legal Name does not load correctly

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#52064]
## Background

Related to #49651

When Adam was coding the new personal information updates, he realized there was [no error for when legal name does not load](https://github.com/department-of-veterans-affairs/va.gov-team/issues/49651#issuecomment-1380783220). I believe that Adam has already coded an error message based on the error state for disability rating -- which should already exist in the Sketch files -- but we still need a Sketch mockup to show this state for documentation purposes.

## Tasks

- [x] Update Sketch files to show the Legal Name error state (check with Adam on what copy he used, since he already coded an error based on the Disability Rating error)
- [x] Post error state here

**Comment by andaleliz** [comment]
I would actually estimate this as a 1 but that doesn't seem to be an option anymore. Strange.

**Comment by andaleliz** [comment]
FYI @BerniXiongA6 it looks like the Sketch files don't show the current state, where we have legal name and disability rating, but NOT sexual orientation and pronouns.  

I've increased the estimate to account for the work of updating the current pages to match what we have on staging.

**Comment by andaleliz** [comment]
Wait! Nvm, I found them. Still a little more work to do be done than I initially thought though, so going to leave it at a 3.

**Comment by andaleliz** [comment]
The Sketch mock-ups have been updated, and I created a [new use case doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/use-cases/system-cant-display-disability-rating-or-legal-name.md) to cover both scenarios where we show an alert within a particular section.

**Comment by Samara-Strauss** [comment]
This looks great! Thank you! One note -- I would assume that we don't show the nametag if we can't load legal name, and the mockup with the legal name error still has the nametag. Worth confirming exact UX with Adam. If he says the nametag doesn't load if we can't pull legal name, I'd remove if from the mockup.

**Comment by andaleliz** [comment]
You're right, we don't show the nametag with the legal name error - I
wonder if Sketch hasn't pushed the latest version correctly? The source
file doesn't have the name tag in either the desktop or mobile version.
I'll double check that.
