### ISSUE TITLE
[ANALYTICS] Create new "Wilmington, DE" Health Services content "LIST" [BA]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#5206]
## User Story or Problem Statement
As a Content writer and Business Analyst, I need to know the specific details regarding the Health Services Provided and Content requirements, so I can document and create the Health Services listing correctly.

## Goal
_Complete a content spreadsheet following using the Pittsburgh, PA pilot design tab as a reference source_

## Objectives or Key Results this is meant to further
- _Reduction in page count_
- _Document pages that can be created in a scalable manner_

## Resources - Tools - Documentation
[VISN_4_Content_Stack](https://drive.google.com/drive/folders/1f_PRAt67ccYNm5DkJiAKwINsSX_S5_4o)
[VA.gov_Medical_Center_Map_Moqup](https://app.moqups.com/Rnc4BDEKrA/view/page/a9e1a59e9)

## Tasks
_Complete written health services content playbook criteria for the following Health Services:_
- [x] Validated listing of all Health Services provided in System
- [x] Validated list of Health Services provided by Facility in the System

## Acceptance Criteria

* Validated listing of all Health Services provided in System
* Validated list of Health Services provided by Facilities in the System

**Comment by cblakelyGCIO** [comment]
Stan, I have uploaded the List sent by Bernardo from the VA to the drive.  This story will be completed tomorrow.
