### ISSUE TITLE
Revoke and rotate leaked google analytics token

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#52073]
There is a google analytics credential was leaked in 2018 into the performance-dashboard repo (which was public at the time). We opened an issue to rotate it a while back:
#126

Credential leak:
[details in va.gov-team-sensitive repo ticket](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/411)

That old issue has some other stuff in it related to Jenkins and is no longer relevant, but the credential still needs to be rotated.

This ticket requests:

Revoke that credential as linked above
Add a new working credential for google analytics to be used by the performance dashboard with equivalent permissions. The resultant token should be added here in the same format:
/dsva-vagov/performance_dashboard/ga_serviceaccount
This is how we get it:
GA_SERVICEACCOUNT=$(aws ssm get-parameter  --with-decrypt --name '/dsva-vagov/performance_dashboard/ga_serviceaccount' | jq '.Parameter.Value' -r

It is also possible that other teams are using this credential, so we'd need to ask those teams as well and have them rotate credentials accordingly as well.

**Comment by npeterson54** [comment]
Original issue

https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/411

**Comment by gary-fallon** [comment]
This is a duplicate.
