### ISSUE TITLE
Remove users from SOCKs and/or AWS access

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#5207]
## User Story or Problem Statement
The following users need to be removed from SOCKs and/or AWS:
- [x] Derek Hall - (AWS & SOCKS)
- [x] Dina Whelan - (N/A, no changes giving access found)
- [x] Greg Summer - (N/A, no changes giving access found)
- [x] Katherine Rodriguez - (AWS & SOCKS)
- [x] Paul Sackley - (SOCKS. No AWS access found)

They were lighthouse users. 

## Goal
_These individuals don't have access anymore_

## Acceptance Criteria
- [ ] _Removed and doubled checked_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jbritt1** [comment]
AWS access removal verified, new jump / socks boxes being deployed now.

**Comment by nathanhruby** [comment]
Removed from DSVA PagerDuty:
- Derek Hall: No EP or rotation changes
- Katherine Rodriguez: EP for DevOps Critical, Devops NonCritical, VSP Enginerrs Critical, DevOps Rotation

**Comment by jbritt1** [comment]
> Removed from DSVA PagerDuty:
> 
> * Derek Hall: No EP or rotation changes
> * Katherine Rodriguez: EP for DevOps Critical, Devops NonCritical, VSP Enginerrs Critical, DevOps Rotation

@nathanhruby is that just done through the GUI? Or do we manage it in code somewhere?

**Comment by nathanhruby** [comment]
Through the GUI for now, but you need to be a Admin or Owner to do it.
