### ISSUE TITLE
Two users fetching scorecard data at the same time results in the data being duplicated

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#5208]
If a user is actively fetching scorecard data, functionality exists to prevent other users from accessing the dashboard and fetching at the same time. However, if the second user has already accessed the dashboard before the first user has clicked fetch, the second user is also able to fetch. If the second user also clicks fetch, the data is duplicated.

1. Login to GIDS as two separate users
2. As user 1, click fetch
3. Once the scorecard fetching message is displayed for user 1, click fetch as user 2.

Once fetching finishes for both users, the scorecards database table will have 14224 rows instead of the expected 7112.

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/552

**Comment by delli-gatti-michael** [comment]
Users are now prevented from fetching at the same time. PR approved

![Screen Shot 2020-01-29 at 12.14.29 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/fda297a8-0412-4ec0-9a29-32cec7f967a6)

**Comment by delli-gatti-michael** [comment]
Bug fix is live in Staging. Closing this issue
