### ISSUE TITLE
[User flows and navigating] A user flow has repetitive or redundant steps. (03.04.1)

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#52085]
#### VFS team name
DGIB - My Education Benefits

#### VFS product name
Enrollment verification

#### Point of Contact/Reviewers
Sara Sterkenburg - @sterkenburgsara - IA

*For more information on how to interpret this ticket, please refer to the [Anatomy of a Staging Review issue ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Anatomy-of-a-Staging-Review-Issue-ticket.2060320997.html) guidance on Platform Website.

---

### Platform Issue
A user flow has repetitive or redundant steps.

### Issue Details
“Cancel verification and exit” link at bottom of form pages is redundant (same link as back button)

### VA.gov Experience Standard
[Category Number 03, Issue Number 04](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

### Platform Recommendation
Remove this link

---

### VFS Guidance

- Close the ticket when the issue has been resolved or validated by your Product Owner
- If your team has additional questions or needs Platform help validating the issue, please comment on the ticket
- Some feedback provided may be out of scope for your iteration of the product, however, Platform's OCTO leadership has stated that all identified issues need to be documented and it is still your responsibility to resolve the issue.
- If you do not believe that this Staging Review issue ticket is the responsibility of your team, comment below providing an explanation and who you believe is responsible. Please tag the Point of Contact/Reviewers. Governance team will research and will follow up.

**Comment by btruongafs** [comment]
@TamGIBill confirmed no action needed and is desired functionality to allow user to exit the multi-step verification flow. Closing out.

**Comment by btruongafs** [comment]
@shiragoodman the back button will allow you go back to the previous month to change your selection if you have multiple months. This would be different than exiting all the verifications.

**Comment by sterkenburgsara** [comment]
@btruongafs thank you - I appreciate the clarification. It makes sense and I apologize for missing that when we did our review. You can go ahead and close.

**Comment by btruongafs** [comment]
@sterkenburgsara no problem! Closing out.
