### ISSUE TITLE
AWS Secrets Validation GHA

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#52098]
In the manifest repo, a GHA should ensure the paths/keys in AWS Parameter Store are present.  This has been done in the devops repo, in this [file](https://github.com/department-of-veterans-affairs/devops/blob/master/.github/workflows/validate-ssm-parameters.yaml).

This GHA action will do the following:

Ensure the path is in the AWS Parameter Store
Ensure the secret path matches the value key path
Ensure the secret name matches the value name
Alert devs to make sure env value can be parsed.

To Do:

- Merge [PR](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/1282)
- Prevent merge until all GHA pass

**Comment by laineymajor** [comment]
Work as a result of vets-api going down yesterday.
