### ISSUE TITLE
Deploy vets-api on merge to mockdata

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#52102]
## Description

The [mockdata repo](https://github.com/department-of-veterans-affairs/vets-api-mockdata) is [mounted to the vets-api deployment for each env](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/main/apps/vets-api/dev/values.yaml#L407-L434). Upon merge of a mockdata change, we should rebuild the vets-api image and re-deploy to pick up new changes.

**Comment by RachalCassity** [comment]
Do we need the mockdata mounted for staging and production?

**Comment by laineymajor** [comment]
@RachalCassity per @LindseySaari yes...

**Comment by laineymajor** [comment]
Good to close. This was done a while ago
