### ISSUE TITLE
User Task Completion Audit 

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#52116]
## Issue Description
_Devise a plan of action, which reviews how Users engage with “Find a Form” and “GI Bill” (education) navigation and completion issues.  Audit data to identify completion percentages and collaborate to create solutions that will increase productivity and User satisfaction.  

---
## Tasks
 •	We will examine Find a Form and GI Bill (Education) completion scores.
•	The data will be audited to identify gaps and create an audit template.
•	The secondary goal is to establish a standard for auditing tasks to increase User satisfaction.
•	The tertiary goal is to refine the audit process and scale across platform.  

## Acceptance Criteria
- [The audit can be completed via data query. 
The data gleaned be shared with appropriate teams for suggesting adjustments.
Increase the completion score.
Increase User satisfaction. 

] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ATMiddleton** [comment]
Combined with 52115

**Comment by ATMiddleton** [comment]
Combined with https://app.zenhub.com/workspaces/contact-center-62cdd9546ec1530018209672/issues/gh/department-of-veterans-affairs/va.gov-team/52115.

**Comment by ianMcCullough-ob** [comment]
Working on an audit pulling Medallia data for va.gov/find-forms and various about form pages.

I will be examining Medallia submissions where the user could not complete their task (Feedback) or where the user gave a score of 1-2 (Intercept).

If pertinent, I'll look at submissions where the task was completed successfully and a high score was given to see if there are positive aspects worth expanding on.

**Comment by ianMcCullough-ob** [comment]
Mural board: https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1676311311015/b2f3b67b456d44341ed35a5e461d1868656b58c7?sender=u683996861c7842a72dea8966

Data has been categorized, will write up audit in upcoming sprint

**Comment by ATMiddleton** [comment]
Excellent!

 

Thank you.

 

Regards, 

 

Anita Middleton

Senior Product Manager
