### ISSUE TITLE
GIDS: Auto-detect file delimiter

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#5212]
As a developer, I need to auto-detect the file delimiter on upload so that the file upload process is streamlined.

## Assumptions:
1. 

## Acceptance Criteria
1. The column separator label and input is no longer on the upload page.
2. On upload, GIDS inspects the header row and identifies the delimiter 
3. Helper text is displayed with the "Upload file" input:
     - "Valid file formats include: .txt, .csv
4. Helper text is displayed in the "CSV Data Requirements"
     - "Valid file delimiters include: | ,

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/555

**Comment by delli-gatti-michael** [comment]
Functionality is now live in Staging. Closing this issue
