### ISSUE TITLE
My health tree test: Results synthesis and readouts

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#52121]

**Comment by batemapf** [comment]
@mnorthuis OK to move this into `In Progress` since I think you're doing this work right now?

**Comment by mnorthuis** [comment]
I have not started on this work yet, will move when I do.

**Comment by batemapf** [comment]
Promise? 😄

**Comment by mnorthuis** [comment]
Truthfully, no, I will likely forget.  I will move now so it can show that I have really good intentions to start on this very soon.  :-)

**Comment by batemapf** [comment]
Yaaassss!

**Comment by mnorthuis** [comment]
Complete
