### ISSUE TITLE
[Design] Profile | Mobile App | Copy updates to Gender Identity screen

### ISSUE THREAD

**Issue by BerniXiongA6** [department-of-veterans-affairs/va.gov-team#52129]
## Background

The Mobile team is adding 2 lines of copy to their gender identity field (after the screen title) to help address the issue of a person not being able to remove this field (go back to null).

Danielle has approved this copy and asked for the Mobile team to share with Profile team so that VA.gov can be aligned w/ the mobile app. 

Here's the Slack thread containing that request: https://dsva.slack.com/archives/C909ZG2BB/p1673975468384139

Here's a screenshot of the mobile app Gender Identity screen: 
![Screen Shot 2023-01-17 at 11.48.03 AM.png](https://images.zenhubusercontent.com/60d0d1089008de03071a6d10/5103770b-a074-4332-8feb-430247faf2b9)

Here's a screenshot of the additional info accordion for Gender Identity (expanded view):
![image (4).png](https://images.zenhubusercontent.com/60d0d1089008de03071a6d10/3e7be05e-f9c9-4631-b840-207165a7870a)
(collapsed view):
![image (5).png](https://images.zenhubusercontent.com/60d0d1089008de03071a6d10/041544c6-a1a7-45d2-9a96-e17ffe4c1d39)
## Tasks
- [x] Update screens in personal information sketch files

## Acceptance Criteria
- [x] Sketch files have been updated by design

**Comment by Samara-Strauss** [comment]
Florence says that it would be helpful to review the Sketch files so we know how many screens need to be updated.

**Comment by andaleliz** [comment]
All the screens have been updated with this new copy
