### ISSUE TITLE
My health tree test: Run test and monitor participation

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#52120]
- [x] Optimal tests are both published and live
- [x] Participant information is sent to Perigean daily
- [x] Monitor participation to get to goal numbers of no less than 40 participants per test
- [x] Work with Perigean to send reminders as necessary
- [x] Monitor results for good responses
- [x] Close test and notify Perigean

**Comment by batemapf** [comment]
@mnorthuis It looks like all things in the description can be checked off and this issue moved to `Done`, right? Unless this is [different than what you posted about on Slack](https://dsva.slack.com/archives/C04GDQSHD1R/p1674228455865509).

**Comment by mnorthuis** [comment]
Yes, I just closed the test out this morning. :-)
