### ISSUE TITLE
[FE] 10-10EZ: add event tags on questions within the form

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#52133]
## Background
In an effort to track traffic through the conditional questions within the 10-10EZ form, we want to add event tags to the radio button answers

## Tasks
- [ ] Add event tags on radio button answers within the form

## Acceptance Criteria
- Events are being captured when an applicant completes the form

**Comment by longmd** [comment]
@hdjustice , these have been added into production. Not sure if you need to get with Michelle to see these in GA or not?

**Comment by hdjustice** [comment]
Do you have the names of the events?  I think Michelle has to do something to get them in the 'official' list, but I still might be able to pull them up in GA in the meantime

**Comment by hdjustice** [comment]
[Ticket #52345](https://github.com/department-of-veterans-affairs/va.gov-team/issues/52345) created for Analytics team to pull into GA.

**Comment by hdjustice** [comment]
@longmd - I created #52363 to validate the event tags when the Analytics team is done with their work.  We can close this, if you agree.  That way we dont have it open indefinitely

**Comment by longmd** [comment]
Sounds good to me! 🚀
