### ISSUE TITLE
VBA - Education - change URL in ask a question online

### ISSUE THREAD

**Issue by AnneHurley** [department-of-veterans-affairs/va.gov-team#5214]
## User Story or Problem Statement
As a _____, I need _____ so I can _____.
Incorrect URL on Education page, right rail, ask a question online

Content support for a static public website page
1. Is this to update existing static content? *Yes, to update URL on Education
2. Does this need a new static tool landing page? (The content team may propose a different approach in consultation with IA.)
2. Provide a list of URL/s that need to be reviewed or updated.
3. If it's a small copy section, list what the new info should be and what it is replacing.
Here is the original request:
As we just discussed, I believe the website errantly links the Comp inquiry system known as ‘Iris’ on this page instead of the EDU system formally known as ‘RNW’. The link to the page in question is https://www.va.gov/education/
The problem link is in the right nav, Questions > Message Us > Ask a question online.

URL should be changed to:

https://gibill.custhelp.va.gov/

From Tammy Hurley
VBA - Education

Steps to completion:
Anne to change URL in Drupal, @RLHecht to review

**Comment by MickinSahni** [comment]
@AnneHurley can you confirm status and then close ticket?

**Comment by AnneHurley** [comment]
@MickinSahni @RLHecht @jenniferlee-dsva  Have emailed SMEs that  this is a link on every hub, pointing to IRIS, so now closing this.

**Comment by MickinSahni** [comment]
Thanks, @AnneHurley! I'm removing the estimate as well since we didn't pick this up
