### ISSUE TITLE
Contact Center Review for Public Websits - PDF Cert Expiration alert

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#52147]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
*Please provide the name(s) of your product and a high-level description of your product.*
Find-a-form – Veteran-facing form download app.

### Launch Date
*Please provide the launch or rollout date and details.*

In Prod already

### Version Number
*Please provide the version number of the guide and/or video.*

v4 attached – Note that the "PDF Cert Expiration alert" product launched back in December, 2022. The key date involved in that certificate expiration was Jan 7, 2023, so we updated the alerts. Changes just went to prod. 

**High-level changes:** 
1. Alert copy on Form Search was updated, and 
2. The alert on Form Detail pages was removed.

### Product Guide
*Please provide product guide link*

[FindVAFormsSearch-ProductGuide_v4_10_jan_2023.pptx](https://github.com/department-of-veterans-affairs/va.gov-team/files/10440203/FindVAFormsSearch-ProductGuide_v4_10_jan_2023.pptx)

### Product Video
*Please provide product video link*
n/a

### Product Video Transcript
*Please provide product video transcript link*
n/a

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
Looks good, @wesrowe. Shared with VEO.
[FindVAFormsSearch_v4_01102023.pptx](https://github.com/department-of-veterans-affairs/va.gov-team/files/10452296/FindVAFormsSearch_v4_01102023.pptx)

**Comment by starlow00** [comment]
No changes from VEO. Attached draft of v4 ready for use.
