### ISSUE TITLE
Community Care Schedule Routing Updates

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#5215]
As a veteran, I'm confused by the city / state choices I have when scheduling CC appointments. Sometimes, I don't see any close city/state combos and am confused by which city / state to pick from the list. I want more helpful information to help me pick a city/state so that I'm confident that I'm making the right selection.

AC
- [ ] city/state list shows ALL registered systems, not just CC-supported ones
- [ ] If a veteran picks a non-supported city/state (i.e. system), in-line validation tells them to call the location instead (because it likely supports CC scheduling, just not online) and the validation error forces the continue button to be disabled
- [ ] If a veteran IS ELIGIBLE but DOES NOT have any CC-supported systems, veteran sees error message telling them to call their local facility instead (or gives option to go down VA request route if the ToC supports it)

**Comment by markgreenburg** [comment]
Update on this per discussion with Dr. Greenstone, Lauren, and the VAOS team

Short Term:
- If a veteran has no supported-sites, continue to not check eligibility and just put veteran into VA flow
- If a veteran has supported-sites, check to see if they are 'close' to the veteran's residential address. @lalexanderson-dsva to provide more guidance on determining an adequate proximity
    - Filter out sites that do not meet the proximity check thresholds before deciding whether or not to show a veteran the CC/VA choice page.

Long Term:
In ~October, Community Care scheduling clerks will all be on the same contract, meaning that *any* site that supports CC scheduling should be able to schedule a CC appointment anywhere, provided that the appointment is on behalf of a veteran who is registered at the clerk's site / system. That will allow us to:
- Remove the proximity check for supported sites
- Automatically pick the 'closest' CC-supporting VA from the veteran's list of registered systems
- Eliminate the 'pick the closest city/state for your appointment' question from the CC scheduling flow.

**Comment by lenaecb** [comment]
We will not be providing any additional community care context at this time.
