### ISSUE TITLE
[Spike] - Understanding existing GA events to prepare for GA4 migration

### ISSUE THREAD

**Issue by JRRoof** [department-of-veterans-affairs/va.gov-team#52165]
## Background/Request
VAOS has 80+ custom events that are currently being tracked by Google Analytics.  These events are used to track button clicks, clicks on links, page activity and API calls (submission/success/failure).  To prepare for migration to Google Analytics 4, we would like to understand any differences between these various event types and identify them by type.

### Goal
To understand any differences between the various custom events that are currently being tracked by VAOS and identify anything unique that will need to be accounted for in the migration.  Ideally, we would also like to classify these events by type, such as button click, api call, etc.

### Requirements to Consider
The following is the list of GA events that we are wanting to classify.  This list does not include the variant events which are being deprecated in ticket [#51723](https://app.zenhub.com/workspaces/vaos-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/51723).

vaos-cancel-appointment-submission
vaos-cancel-appointment-submission-failed
vaos-cancel-appointment-submission-successful
vaos-cancel-booked-clicked
vaos-cancel-request-clicked
vaos-cc-eligible-yes
vaos-choose-provider-click
vaos-community-care-path-started
vaos-community-care-provider-selection-page
vaos-community-care-submission
vaos-community-care-submission-failed
vaos-community-care-submission-successful
vaos-contact-info-email-changed
vaos-contact-info-email-not-changed
vaos-contact-info-email-not-populated
vaos-contact-info-email-populated
vaos-contact-info-phone-changed
vaos-contact-info-phone-not-changed
vaos-contact-info-phone-not-populated
vaos-contact-info-phone-populated
vaos-continue-with-provider
vaos-continue-without-provider
vaos-COVID-19-vaccines-at-VA-link-clicked
vaos-covid19-path-started
vaos-covid19-screener-no
vaos-covid19-screener-yes
vaos-covid19-start-scheduling-button-clicked
vaos-covid19-submission
vaos-covid19-submission-failed
vaos-covid19-submission-successful
vaos-direct-path-started
vaos-direct-submission
vaos-direct-submission-failed
vaos-direct-submission-successful
vaos-eligibility-direct-available-clinics-failed
vaos-eligibility-direct-check-past-visits-failed
vaos-eligibility-direct-no-matching-past-clinics-failed
vaos-eligibility-direct-supported-failed
vaos-eligibility-request-exceeded-outstanding-requests-failed
vaos-eligibility-request-past-visits-failed
vaos-eligibility-request-supported-failed
vaos-eligibility-supported-facilities-failed
vaos-error
vaos-facilities-not-listed-click
vaos-facilities-not-listed-locator-click
vaos-get-future-appointments-failed
vaos-get-future-appointments-retrieved
vaos-get-future-appointments-started
vaos-get-past-appointments-failed
vaos-get-past-appointments-retrieved
vaos-get-past-appointments-started
vaos-get-pending-appointments-failed
vaos-get-pending-appointments-retrieved
vaos-get-pending-appointments-started
vaos-number-of-items-retrieved
vaos-order-position-provider-selection
vaos-provider-list-paginate
vaos-request-current-location-allowed
vaos-request-current-location-blocked
vaos-request-current-location-clicked
vaos-request-path-started
vaos-request-submission
vaos-request-submission-failed
vaos-request-submission-successful
vaos-schedule-another-appointment-button-clicked
vaos-schedule-appointment-button-clicked
vaos-schedule-covid19-button-clicked
vaos-schedule-new-appointment-started
vaos-status-past-link-clicked
vaos-status-pending-link-clicked
vaos-update-address-alert-displayed
vaos-view-your-appointments-button-clicked

---

## Tasks
- Answer the following questions:
  - Q  Is there anything unique from a coding perspective about how these different events are being triggered?
  - Q  Can these events be grouped into distinct categories? If so, what are the recommended categories?
  - Q  Are there any of these events that should be deprecated?
  - Q  Are there any additional events that are not being tracked today that should be?

## Time Box
18 hours

## Definition of Done
- Tasks are complete
- Research and recommendations are documented in this ticket

---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by jenniemc** [comment]
@JRRoof Here's my short list for GA4 test recommendation. 
[EventTrackingGA4Recommend.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/11335779/EventTrackingGA4Recommend.pdf)
