### ISSUE TITLE
Offboarding of Sally Maki

### ISSUE THREAD

**Issue by nanotone** [department-of-veterans-affairs/va.gov-team#52178]
# Instructions
Fill out name of individual and *Description* section below.

*(Please add only one individual per form)*

# Description
Please provide the following information about the individual being offboarded:
- name:
  > Sally Maki
- team name:
  > OCTO Automated Benefits Delivery
- role on team:
  > Software engineer
- expected last day: _(MM/DD/YYYY)_
  > 06/10/2022
- company they work for:
  > Nava PBC
- email: _(Multiple emails listed in order of relevance to VA business, VA, Company, Personal, etc....)_
  > Sally.Maki@va.gov
  > sallymaki@navapbc.com
- GitHub username: _(Please include @ symbol)_
  > @leikkisa
- additional access they may have: _(First line formatted with access titles only. Additional notes may be added on second line after the list.)_
  > none
 
 
## Acceptance Criteria
*The following steps are performed by the Platform Support team. Detailed instructions found [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/2097545323/Offboard+Team+Member)*
 - [x] Requested removal from DSVA Slack (if applicable. Search for them in Slack)
   > A comment on this ticket prefixed with `/request` (i.e. `/request FirstName LastName`) will send a message to the Slack admins automatically!
 - [x] Requested removal from Confluence (if applicable. Check [confluence members](https://vfs.atlassian.net/wiki/people/search?q=))
 - [x] Remove from [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=0) (if applicable)
 - [x] Remove from global/config.yml / SOCKS Access removed (if applicable. Search their email in [config.yml](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/global/config.yml))
   > Use the [Remove SOCKS and AWS access Github Workflow](https://github.com/department-of-veterans-affairs/devops/actions/workflows/offboarding.yml) to create a PR to update the `global/config.yml` file and remove the public SSH key. You'll need the user's email address associated with their public key (found in `config.yml`).
 - [x] AWS Access removed  (if applicable. Search their name in [AWS IAM](https://console.amazonaws-us-gov.com/iamv2/home#/home))
   > Use the [Remove SOCKS and AWS access Github Workflow](https://github.com/department-of-veterans-affairs/devops/actions/workflows/offboarding.yml) to remove user's entry from DSVA AWS. You'll need the user's AWS username (typically `First.Last`).
 - [x] User removed from the VA GitHub Org (user was already removed due to inactivity)

 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/platform-analytics-insights-team , @department-of-veterans-affairs/confluence-admins, @department-of-veterans-affairs/platform-design

**Comment by CoryTrimmUSDS** [comment]
Removed from DSVA Slack.

**Comment by rjohnson2011** [comment]
Not on Confluence or VFS team roster.

**Comment by rmtolmach** [comment]
no socks or aws. closing.
