### ISSUE TITLE
Offboarding of Tanner Heffner

### ISSUE THREAD

**Issue by nanotone** [department-of-veterans-affairs/va.gov-team#52193]
# Instructions
Fill out name of individual and *Description* section below.

*(Please add only one individual per form)*

# Description
Please provide the following information about the individual being offboarded:
- name:
  > Tanner Heffner
- team name:
  > Automated Benefits Delivery
- role on team:
  > Software engineer
- expected last day: _(MM/DD/YYYY)_
  > 12/16/2022
- company they work for:
  > Agile 6
- email: _(Multiple emails listed in order of relevance to VA business, VA, Company, Personal, etc....)_
  > Tanner.Heffner@va.gov
  > tanner.heffner@agile6.com
- GitHub username: _(Please include @ symbol)_
  > @tjheffner
- additional access they may have: _(First line formatted with access titles only. Additional notes may be added on second line after the list.)_
  > none
 
## Acceptance Criteria
*The following steps are performed by the Platform Support team. Detailed instructions found [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/2097545323/Offboard+Team+Member)*
 - [x] Requested removal from DSVA Slack (if applicable. Search for them in Slack)
   > A comment on this ticket prefixed with `/request` (i.e. `/request FirstName LastName`) will send a message to the Slack admins automatically!
 - [x] Requested removal from Confluence (if applicable. Check [confluence members](https://vfs.atlassian.net/wiki/people/search?q=))
 - [x] Remove from [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=0) (if applicable)
 - [ ] Remove from global/config.yml / SOCKS Access removed (if applicable. Search their email in [config.yml](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/global/config.yml))
   > Use the [Remove SOCKS and AWS access Github Workflow](https://github.com/department-of-veterans-affairs/devops/actions/workflows/offboarding.yml) to create a PR to update the `global/config.yml` file and remove the public SSH key. You'll need the user's email address associated with their public key (found in `config.yml`).
 - [x] AWS Access removed  (if applicable. Search their name in [AWS IAM](https://console.amazonaws-us-gov.com/iamv2/home#/home))
   > Use the [Remove SOCKS and AWS access Github Workflow](https://github.com/department-of-veterans-affairs/devops/actions/workflows/offboarding.yml) to remove user's entry from DSVA AWS. You'll need the user's AWS username (typically `First.Last`).
 - [x] User removed from the VA GitHub Org (if applicable. Check [department-of-veterans-affairs/people](https://github.com/orgs/department-of-veterans-affairs/people))
   > Fill out request found [here](https://github.com/department-of-veterans-affairs/github-user-requests/issues/new?assignees=&labels=remove-user&template=user-remove.yml&title=Remove+User+from+Org%3A+%5Busername%5D). 

 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/platform-analytics-insights-team , @department-of-veterans-affairs/confluence-admins, @department-of-veterans-affairs/platform-design

**Comment by michelle-dooley** [comment]
No Domo or GA.

**Comment by rjohnson2011** [comment]
@department-of-veterans-affairs/confluence-admins Please remove user https://vfs.atlassian.net/wiki/people/616f1111e79ff6006f29b435

**Comment by rjohnson2011** [comment]
Removed from VFS roster.

**Comment by rjohnson2011** [comment]
Request to remove from VA Github org https://github.com/department-of-veterans-affairs/github-user-requests/issues/14188

**Comment by rmtolmach** [comment]
No AWS.
✅ socks removed in https://github.com/department-of-veterans-affairs/devops/pull/12567
