### ISSUE TITLE
[Analytics ] Implement Google Tag Manager Environments Feature on Staging

### ISSUE THREAD

**Issue by nedierecel** [department-of-veterans-affairs/va.gov-team#522]
## User Story
As an implementation specialist/strategist or front-end engineer, I would like to validate Google Analytics changes on Dev and Staging before pushing to production. Currently, this is only accomplished using a preview link and is limited in user testing to a handful of users.

This feature is already present on the dev.va.gov environment.

## Goals
- New Google Tag Manager environments feature that is used on dev.va.gov also used on staging.va.gov
- Process outlined by analytics-insights team for pushing Google Analytics changes 

## Acceptance Criteria
- [ ] Google Tag Manager environment created for staging.va.gov in GTM (or determine if we should use the same code that is on dev.va.gov)
- [ ] Code provided to engineering to implement
- [ ] Code validated on staging.va.gov and most recent container published to this environment
- [ ] Process documented for publishing and validating analytics changes on dev and staging environments

## Definition of Done
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jonwehausen** [comment]
Hi @ncksllvn ,

We have setup a staging environment within GTM we would like to leverage moving forward as part of our implementation / QA process. 

This GTM environment has a new GTM code snippet that will need to be inserted across the staging domain. 

Please let me know who we should provide this snippet to and how we should proceed in getting this code inserted.

Thanks,
Jon Wehausen

CC: @joanneesteban @nedierecel

**Comment by ncksllvn** [comment]
Hey @jonwehausen, sounds good! Can you copy and paste the code snippet here in a comment?

@Karak888 This won't take long and since we're a site-wide team it makes sense to me that our team grab it, but including you on the thread because I'm not sure exactly which team it should fall on. I could also see it going to Platform.

**Comment by jonwehausen** [comment]
Hi @ncksllvn,

Thanks for getting back to me -- please check out the snippet for the staging environment: 

**Paste this code as high in the <head> of the page as possible:**
```javascript
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl+ '&gtm_auth=inC4EKQce9vlWpRVcowiyQ&gtm_preview=env-661&gtm_cookies_win=x';f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-WFJWBD');</script>
<!-- End Google Tag Manager -->
```

**Additionally, paste this code immediately after the opening <body> tag:**
```javascript
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-WFJWBD&gtm_auth=inC4EKQce9vlWpRVcowiyQ&gtm_preview=env-661&gtm_cookies_win=x"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
```

**Comment by ncksllvn** [comment]
Hey @nedierecel, just confirming - we aren't collecting and aren't interested in collecting analytics for `localhost`, correct? It looks like there's some logic for `localhost` and `dev.va.gov` to use the same Google Analytics code, but I don't we actually need that so I'd like to remove it.

**Comment by ncksllvn** [comment]
This should be ready in Staging in about 25 minutes!

**Comment by ncksllvn** [comment]
Hey @jonwehausen , this is ready in Staging, but I'm seeing a 404 on loading up the script. Does this environment still need to be enabled in GTM?

![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/504c77b5-e5fc-46c6-82de-d1f445982013)

**Comment by jonwehausen** [comment]
Hi @ncksllvn ,

Thanks for this notice. I've gone ahead and published the GTM staging environment with our latest version of the container. 

May you see if you are still receiving that error? I'm not receiving any error within my console. 

Thanks again, 
Jon Wehausen

**Comment by ncksllvn** [comment]
The error is gone! Sounds like the Staging GTM is working okay 👌

**Comment by jonwehausen** [comment]
@nedierecel QA is ready

**Comment by nedierecel** [comment]
@jonwehausen @ncksllvn Thank you for tackling. I am confirming I see the snippet correctly in staging (particularly that the unique environment ID `env-661` is present).

Thanks for making a wish list item come to fruition!

**Comment by ncksllvn** [comment]
I was happy to, thanks for including me!
