### ISSUE TITLE
Update 508 email link on Accessibility Statement from Accessibility Team

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-team#52200]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [x] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [ ] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
  - [x] Content support
  - [ ] IA support
  
  
*Please be specific about the content or IA support you need and provide any additional documents and/or links that will help us help you. If we need to add a react widget to a page, be sure to provide the code here.*

Martha Wilkes and the Accessibility Team have received a request from the 508 Office to update the 508 email link on the [Accessibility Statement page](https://www.va.gov/accessibility-at-va/).
![image](https://user-images.githubusercontent.com/106678594/213277422-bbd81a71-002a-4e5d-a620-293d31d32c3f.png)

In order to better filter and categorize emails coming into this inbox they would like the emails coming into this page to be prefilled with specific subject and body text.  This can be achieved by updating the email link within the rich text editor to:
`<a href="mailto:section508@va.gov?subject=Section%20508%20Support%20Request&body=Thank%20you%20for%20contacting%20the%20Department%20of%20Veteran's%20Affairs%20Section%20508%20Team%20from%20the%20VA's%20accessibility%20webpage.%20Please%20fill%20out%20the%20below%20information%20to%20assist%20us%20in%20understanding%20the%20issues%20you%20encountered.%20We%20will%20respond%20to%20this%20email%20within%203%20business%20days%20to%20let%20you%20know%20we%20have%20received%20the%20request%20and%20if%20additional%20information%20is%20required.%0D%0DTitle%20of%20the%20webpage%20-%20%0D%0DWebpage%20address%20-%20%0D%0DWhat%20computer%20or%20mobile%20device%20were%20you%20using%20-%20%0D%0D
What%20internet%20browser%20were%20you%20using%20-%20%0D%0DWhat%20assistive%20or%20accessible%20technologies%20were%20you%20using%20-%20%0D%0D
Describe%20the%issue%20-%20%0D%0D">Section508@VA.gov</a>`

Below is a screenshot of what the email will now look like when a user clicks the link:
![image](https://user-images.githubusercontent.com/106678594/213270292-44242746-6988-4346-ba54-5ff947f7eb4d.png)

**Notes:**

- The Subject line and body are pre-filled so the content surrounding the 508 email link should probably be adjusted - For example, if currently says "Type 508 issue in the subject line." But now we have already added a subject line for them.
- We got this HTML from the 508 office, and the wording is a bit different from what the content on the page says (again refer to the subject line). Is this something that you would want to confirm with the 508 office, what content/words they need to help filter these emails?
- Would it be possible to let me know when this is in a preview environment for me (@laflannery) to test from an accessibility standpoint? I want to make sure that it's clear to screen reader users that it's clear what is needed within the email - that it has some content in the body but we are requesting they add additional content.

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [ ] Yes
  - [ ] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
## When do you expect to launch your product to 100% of users?
  
*Please provide an estimated date so our team can create other relevant tickets.*
  
## Supporting artifacts
*Please provide supporting artifacts as available.*

- Link to product outline:
- Link to or attach user flows:
- Link to prototype or mockups:
- Link to any epics/issues that may be helpful:

## Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [ ] No

## When does this work need to be done?
- Estimated launch date:
- Estimated staging review date:
- Content and IA work needed by: 

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [ ] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: 
-	Product manager: 
-	Designer: 
-	FE engineer: 
-	Product/team Slack channel:

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by laflannery** [comment]
Talked to Megan and these are notes for myself:
- Fix code for % in last bullet
- Remove spaces in 4th and 6th bullets
- Waiting to confirm with 508 office that we can edit pre-filled body text to more closely match what is on the page itself to avoid confusion

**Comment by laflannery** [comment]
@megzehn Turns out I didn't need to get 508 approval, I just confirmed with Martha! If you would like to send me "normal" text that you would like to show in the pre-fill email body, I can then convert it to HTML and send you new code to add for the email link.  Does that work?

**Comment by megzehn** [comment]
Hi @laflannery! 

Thanks for checking with Martha! Here's some suggested copy to match the current accessibility page. I left out questions about browser and device type since that isn't on the current page. If we need those, then I can work with our team to tweak the existing page so that they match. Let me know if that works. 

___________

Thank you for contacting VA’s Section 508 team. 

Please fill out this information to help us understand the issue you encountered. We’ll respond to this email within 3 business days to let you know that we received your support request and to ask follow-up questions if needed.

* How would you describe the issue?
* Where did you find the issue? What was the webpage address (or URL)?
* What assistive technologies were you using when you found this issue?
* If we need to send you follow-up materials, is there a specific format you’d like? 
* How can we contact you if we need more details?
* Is there anything else you want to tell us to help us fix the issue?

**Comment by laflannery** [comment]
@megzehn 

Screenshot of what this should look like, I have been known to make a typo or two haha, take a look at the screenshot and let me know if I made any mistakes and I can fix this before you implement (note that real bullets can't be done in this type of email pre-fill so it's just spacing the questions like I did):
![image](https://user-images.githubusercontent.com/106678594/215198377-1e6ed35f-f235-400e-95e6-652bea9b4002.png)

**New mailto tag:**
`<a href="mailto:section508@va.gov?subject=Section%20508%20Support%20Request&body=Thank%20you%20for%20contacting%20VA's%20Section%20508%20Team.%0D%0DPlease%20fill%20out%20this%20information%20to%20help%20us%20understand%20the%20issue%20you%20encountered.%20We'll%20respond%20to%20this%20email%20within%203%20business%20days%20to%20let%20you%20know%20that%20we%20received%20your%20support%20request%20and%20to%20ask%20follow-up%20questions%20if%20needed.%0D%0DHow%20would%20you%20describe%20the%20issue?%0D%0DWhere%20did%20you%20find%20the%20issue?%20What%20was%20the%20webpage%20address%20(or%20URL)?%0D%0DWhat%20assistive%20technologies%20were%20you%20using%20when%20you%20found%20the%20issue?%0D%0DIf%20we%20need%20to%20send%20you%20follow-up%20materials,%20is%20there%20a%20specific%20format%20you'd%20like?%0D%0DHow%20can%20we%20contact%20you%20if%20we%20need%20more%20details?%0D%0DIs%20there%20anything%20else%20you%20want%20to%20tell%20us%20to%20help%20us%20fix%20the%20issue?%0D%0D">Section508@VA.gov</a>`

**Comment by megzehn** [comment]
Thank you @laflannery! It looks like there's an extra line and space after "Where" (second question).

**Comment by laflannery** [comment]
I knew there would be something! (the line was actually my cursor lol)

New screenshot:
![image](https://user-images.githubusercontent.com/106678594/215202139-f91064d7-1771-411d-9a2f-218d232ff26f.png)

New tag (removed from above just to avoid confusion):
`<a href="mailto:section508@va.gov?subject=Section%20508%20Support%20Request&body=Thank%20you%20for%20contacting%20VA's%20Section%20508%20Team.%0D%0DPlease%20fill%20out%20this%20information%20to%20help%20us%20understand%20the%20issue%20you%20encountered.%20We'll%20respond%20to%20this%20email%20within%203%20business%20days%20to%20let%20you%20know%20that%20we%20received%20your%20support%20request%20and%20to%20ask%20follow-up%20questions%20if%20needed.%0D%0DHow%20would%20you%20describe%20the%20issue?%0D%0DWhere%20did%20you%20find%20the%20issue?%20What%20was%20the%20webpage%20address%20(or%20URL)?%0D%0DWhat%20assistive%20technologies%20were%20you%20using%20when%20you%20found%20the%20issue?%0D%0DIf%20we%20need%20to%20send%20you%20follow-up%20materials,%20is%20there%20a%20specific%20format%20you'd%20like?%0D%0DHow%20can%20we%20contact%20you%20if%20we%20need%20more%20details?%0D%0DIs%20there%20anything%20else%20you%20want%20to%20tell%20us%20to%20help%20us%20fix%20the%20issue?%0D%0D">Section508@VA.gov</a>`

**Comment by megzehn** [comment]
Thank you, @laflannery and @RLHecht! 

Confirming here that we made 2 minor tweaks to the pre-filled letter (took out please and broke up a sentence) and made the subject line sentence case. 

@laflannery reviewed for accessibility, and the page is now published.

**Comment by laflannery** [comment]
Thank you so much @megzehn! As this is my first ticket, do I close this now that it's done?

**Comment by RLHecht** [comment]
I'll close it!
