### ISSUE TITLE
Create V2 controller for cc eligibility

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#52202]
## Description
We have a VAOS::CCEligibilityService for V0 (/vaos/v0/community_care/eligibility) for determining a veteran's cc eligibility. We want to create a v2 endpoint for vaosV2 in vets-api

---

## Acceptance Criteria
- The FE should be able to make a call to the new v2 cc eligibility endpoint to get veteran cc eligibility.

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ajmagdub** [comment]
Added Vets API **/v2/community_care/eligibility/:service_type** endpoint which will replace the currently used **/v0/community_care/eligibility/:service_type** endpoint.
