### ISSUE TITLE
Copy edit for release notes from VA Mobile App

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va.gov-team#52219]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [ ] Making revisions to an existing online form, app, or tool on VA.gov
- [X] Something else (please add details in the next question)

## What do you need help with?
  - [X] Content support
  - [ ] IA support
  
I need a copy edit of the content that will appear in the "What's new" section of the iOS/Google Play app stores. This content is specific to when we release our new navigation pattern, which is a major change to the app's overall layout.

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [ ] Yes
  - [X] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
## When do you expect to launch your product to 100% of users?
  
*Please provide an estimated date so our team can create other relevant tickets.*
  
## Supporting artifacts
*Please provide supporting artifacts as available.*

- Copy for editing is below:

We’ve updated where you find tools and information in the app.

When you sign in, you’re taken to a new Home screen. At the bottom of the app for most screens you’ll find 4 buttons: Home, Benefits, Health, and Payments. Here’s what’s in each section:

- The Home section shows your name and branch of service. It also includes links for how to contact us, find VA locations, and get updated information on COVID-19.
- The Benefits section includes your disability rating, claims and appeals, and VA letters.
- The Health section includes your VA health care appointments, secure messages, and vaccine records.
- The Payments section includes your VA payment history and direct deposit information.

We moved the Profile section to the top right area of the Home screen. Your Profile section includes your personal, contact, and military information. You can also manage the app’s settings in the Profile section.

## Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [X] No

## When does this work need to be done?
- Estimated launch date: n/a
- Estimated staging review date: n/a
- Content and IA work needed by: by EOD January 27, 2023

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [X] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: VA Mobile App
-	OCTO-DE product owner: Chris Johnston
-	Product manager: Kelly Lein
-	Content designer: Misty Milliron-Grant
-	Product/team Slack channel: va-mobile-app

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by megzehn** [comment]
Hi @mistymg, thanks for answering my questions and discussing the directional language need here. Here's a copy edited version based on our conversation. Let me know if there are any concerns! 

__________

We’ve updated where you find tools and information in the app.

When you sign in, you’ll go to a new Home screen. On most screens in the app, you'll find buttons at the bottom to select these 4 sections: Home, Benefits, Health, and Payments. Here’s what’s in each section:

- The Home section shows your name and branch of service. It also includes links for how to contact us, find VA locations, and get updated information on COVID-19.
- The Benefits section includes your disability rating, claims and appeals, and VA letters.
- The Health section includes your VA health care appointments, secure messages, and vaccine records.
- The Payments section includes your VA payment history and direct deposit information.

We moved the Profile section to the top right area of the Home screen. Your Profile section includes your personal, contact, and military information. You can also manage the app’s settings in the Profile section.

**Comment by RLHecht** [comment]
I believe this ticket is complete. Going to close but please reopen if needed!
