### ISSUE TITLE
Template Onboarding New Applications to Identity 

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#52240]
Description: Create an onboarding template for developers when creating new applications that integrate or touch the Identity team. 

- [x] Find what exists in our repo (one page questionnaire that lists out our features and pick between the ones that are mutually exclusive).

- Found: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/teams/vsp/teams/Identity/Unified%20Sign%20in%20Page (but it basically lives in the sensitive repo and it would help if the questionnaire could be provided to the public)

- [ ] Duplicate and edit the template to match goals of the onboarding template

**Comment by asg5704** [comment]
This work is already completed. Should be closed.
