### ISSUE TITLE
Qualitative Data Request

### ISSUE THREAD

**Issue by APorter-Clarity** [department-of-veterans-affairs/va.gov-team#52268]
### Data Type Requested

User Surveys

### Date Range Start

11-15-22

### Date Range End

01-15-23

### Product Name(s)

Identity

### Product Description

The Identity team is responsible for all things login and the overall user experience as it relates to logging on to VA.gov. We work closely with credential service providers on Va.gov.

### Product URL(s) and/or term(s)

URLS:[VA.gov Login Modal](https://www.va.gov/?next=loginModal)

TERMS: Login, login.gov, verify, sign in, MFA, 2FA, authentication, redirect

### File Delivery Format

One file, different tab for each term/URL

### VA Email Address(es)

AMANDA.PORTER@va.gov

### Add Assignee and Labels

If not already done so, please ensure @ianMcCullough-ob is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by ianMcCullough-ob** [comment]
Hey @APorter-Clarity! Just shared the export with you. Let me know if you have any questions. Thanks!
