### ISSUE TITLE
Debt Resolution: Testing Vets-API Server from BRD to EKS (dev)

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#52261]
**What’s happening?**
We are in the process of migrating vets-api server to EKS (Amazon's K8 service), which will bring us one step closer to microservices. 
- As part of the testing process for vets-api server migration to EKS, we’ve tested healthcheck paths. 
- We also need help testing endpoints. This is where you come in!

**Why is this important?**
- We want to verify expected behaviors from the endpoints, so the expected behavior(s) translate from BRD to EKS.
- It is important to have owners test their endpoints as you know these endpoints the best. This will also help speed up the process of moving from BRD to EKS.

**As a VFS/Platform Team, what do I need to do? BY COB 2.1.2023**

**1. REVIEW [ENDPOINT OWNERSHIP DOCUMENT](https://docs.google.com/spreadsheets/d/1pj8D4cXtHta8VsO53Q3AUKBHwbjRmo3v0BJHUFuU-c0/edit#gid=1967399804)**
- [ ] If there is anything that needs to change, this should be noted as a **comment** in this ticket and tag @ laineymajor
- [ ] If the information is correct AND complete, please check the box associated with this action item

**2. VERIFY DEV SYNTHETIC TESTS**
- [ ] Verify the test from the inside of TIC firewall aka vfs-dev (if you do not have SOCKS access, please note in this ticket)
- [ ] Verify the test from the outside of TIC firewall aka revproxy-dev (going through the [Reverse Proxy](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474594232/Reverse+Proxy))
- [ ] Check for missing tests or duplicated tests
- [ ] Note any issues with lack of test data and/or users in the comments section of this ticket

**3. PER YOUR JUDGEMENT, IF NEEDED, PERFORM MANUAL TESTING**
- [ ] Complete necessary manual testing
- [ ] Link documentation, in the comments of this ticket, showing the completion of any manual testing

**4. Is your team the 'owner' of any of the following?If so, tag @ laineymajor in the comments**
As Tech Team 1 works on the migration of vets-api server to EKS, we are looking for the owners of the following forms:
- [ ] /v0/in_progress_forms/{id}
- [ ] v0/in_progress_forms#show
- [ ] v0/in_progress_forms#update,
- [ ] v0/in_progress_forms#destroy

**Comment by laineymajor** [comment]
@denisecoveyduc checking in to see if you have any questions about this ticket. Please tag @RachalCassity and me with questions. Thanks!

**Comment by denisecoveyduc** [comment]
Hey @laineymajor Thanks for reaching out and sorry for the delay I was out of the office for a few days. Let me discuss with dev team and get back to you. 
cc: @ScottyRJames @Dr-Pongo @OptionSelect @amponce @HeatherRienks

**Comment by denisecoveyduc** [comment]
After connecting with the team there is some work that needs to be done. @ScottyRJames will capture the work needed and document it in tickets to move this forward. 
cc: @HeatherRienks

**Comment by laineymajor** [comment]
dev migration complete. good to close.
