### ISSUE TITLE
Remove/replace React radio buttons present in Benefits Team 1 products

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#52272]
The VSP Design team is deprecating the React radio button. We need to migrate to the radio button web component so we So the team can move forward with deprecation. 

According to the team, there are 14 instances of the radio button being used by our team's products. More information can be found in [this ticket.](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1310)

**Comment by jacobworrell** [comment]
@saderagsdale we reviewed the products mentioned by the VSP Design Systems team and I don't think any of the products are currently owned by Squad 1. Please see the ticket linked in the description of this one.

**Comment by saderagsdale** [comment]
@jacobworrell Already flagged our team for this yesterday.

**Comment by Mottie** [comment]
I'm taking over this ticket!

**Comment by Mottie** [comment]
Work done - no obvious visual or interactive changes to test
