### ISSUE TITLE
[EKS Testing] [LOWERS] Claim Status Tool

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#52319]
In order to ensure consistent and correct behavior after the migration to EKS, we need to verify that the endpoints of this application are working as expected.

Be on the look out for errors that have to do with connectivity:
- Status Codes
  - 403: Forbidden * Check that a test user is signed in before marking as broken
  - 404: Not found * Check that the path is correct before marking as broken
  - 500: Internal Server Error
  - 502: Bad Gateway
  - 503: Service Unavailable
  - 504: Gateway Timeout
- General Errors
  - ERR_TOO_MANY_REDIRECTS: Redirect loop
  - Others?

AC:
- [ ] DEV
  - [ ] The following endpoints return the results expected.
    - [x] GET	/v0/appeals
    - [x] GET	/v0/claim_letters
    - [x] GET	/v0/claim_letters/*
    - [x] GET	/v0/evss_claims_async
    - [x] GET	/v0/evss_claims_async/*
    - [ ] POST	/v0/evss_claims_async/*/request_decsion
    - [ ] POST	/v0/evss_claims/*/documents
    - [x] GET	/v0/education_benefits_claims/stem_claim_status
  - [x] A spot check of the application works as expected OR recorded TestRail tests pass
- [ ] STAGING
  - [ ] The following endpoints return the results expected.
    - [x] GET	/v0/appeals
    - [x] GET	/v0/claim_letters
    - [x] GET	/v0/claim_letters/*
    - [x] GET	/v0/evss_claims_async
    - [x] GET	/v0/evss_claims_async/*
    - [ ] POST	/v0/evss_claims_async/*/request_decsion
    - [x] POST	/v0/evss_claims/*/documents
    - [x] GET	/v0/education_benefits_claims/stem_claim_status
  - [ ] A spot check of the application works as expected OR recorded TestRail tests pass

**Comment by jacobworrell** [comment]
We'll have to update this ticket to test the actual end points post Lighthouse migration.

**Comment by kjduensing** [comment]
@jacobworrell per a request by @jerekshoe we think it's a good idea to test this ticket as is, since it'll be a while before CST is transitioned 100%. Thoughts?

**Comment by jacobworrell** [comment]
Sounds good to me.

**Comment by kjduensing** [comment]
Unable to test `claim_letters` and `claim_letters/:id` in staging due to supposed EKS issue. Issue tracked here:

https://dsva.slack.com/archives/C04M7T1CZAS/p1675270952096209

**Comment by kjduensing** [comment]
`claim_letters/*` works in staging, proceeding with testing.
