### ISSUE TITLE
[EKS Testing] [LOWERS] View Dependents

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#52322]
In order to ensure consistent and correct behavior after the migration to EKS, we need to verify that the endpoints of this application are working as expected.

Be on the look out for errors that have to do with connectivity:
- Status Codes
  - 403: Forbidden * Check that a test user is signed in before marking as broken
  - 404: Not found * Check that the path is correct before marking as broken
  - 500: Internal Server Error
  - 502: Bad Gateway
  - 503: Service Unavailable
  - 504: Gateway Timeout
- General Errors
  - ERR_TOO_MANY_REDIRECTS: Redirect loop
  - Others?

AC:
- [ ] DEV
  - [ ] The following endpoints return the results expected.
    - [ ] POST	/v0/dependents_applications
    - [ ] GET	/v0/dependents_applications/show
    - [ ] POST	/v0/claim_attachments
  - [ ] A spot check of the application works as expected OR recorded TestRail tests pass
- [x] STAGING
  - [ ] The following endpoints return the results expected.
    - [ ] POST	/v0/dependents_applications
    - [x] GET	/v0/dependents_applications/show
    - [ ] POST	/v0/claim_attachments
  - [x] A spot check of the application works as expected OR recorded TestRail tests pass

**Comment by Mottie** [comment]
It looks like the 3 endpoints are using in form 686C-674, which our team (not sure which squad) currently owns; but it will be owned by the new benefits-disability-experience team once they are in place (according to their channel description)

**Comment by jacobworrell** [comment]
@laineymajor we are adding this ticket to our current sprint. Will test on dev and staging.

**Comment by kjduensing** [comment]
Unable to test with endpoint testing tool (Invalid authenticity token). Spot check works though.

**Comment by kjduensing** [comment]
I cannot test dev as it appears no test users are set up to work correctly with this feature in Dev. @jacobworrell, staging works - thoughts on if we can close this ticket or not?

**Comment by jacobworrell** [comment]
@kjduensing Yes, I think if staging works, we're good.
