### ISSUE TITLE
[EKS Testing] [LOWERS] Rated Disabilities

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#52320]
In order to ensure consistent and correct behavior after the migration to EKS, we need to verify that the endpoints of this application are working as expected.

Be on the look out for errors that have to do with connectivity:
- Status Codes
  - 403: Forbidden * Check that a test user is signed in before marking as broken
  - 404: Not found * Check that the path is correct before marking as broken
  - 500: Internal Server Error
  - 502: Bad Gateway
  - 503: Service Unavailable
  - 504: Gateway Timeout
- General Errors
  - ERR_TOO_MANY_REDIRECTS: Redirect loop
  - Others?

AC:
- [x] DEV
  - [x] The following endpoints return the results expected.
    - [x] GET	/v0/disability_compensation_form/rated_disabilities
    - [x] GET	/v0/disability_compensation_form/rating_info
  - [x] A spot check of the application works as expected OR recorded TestRail tests pass
- [x] STAGING
  - [x] The following endpoints return the results expected.
    - [x] GET	/v0/disability_compensation_form/rated_disabilities
    - [x] GET	/v0/disability_compensation_form/rating_info
  - [x] A spot check of the application works as expected OR recorded TestRail tests pass

**Comment by jacobworrell** [comment]
@laineymajor we are adding this ticket to our current sprint. Will test on dev and staging.

**Comment by kjduensing** [comment]
Users:

DEV: 228
STAGING: 64
