### ISSUE TITLE
[EKS Testing] [LOWERS] Dependency Verification Modal

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#52324]
In order to ensure consistent and correct behavior after the migration to EKS, we need to verify that the endpoints of this application are working as expected.

Be on the look out for errors that have to do with connectivity:
- Status Codes
  - 403: Forbidden * Check that a test user is signed in before marking as broken
  - 404: Not found * Check that the path is correct before marking as broken
  - 500: Internal Server Error
  - 502: Bad Gateway
  - 503: Service Unavailable
  - 504: Gateway Timeout
- General Errors
  - ERR_TOO_MANY_REDIRECTS: Redirect loop
  - Others?

AC:
- [ ] The following endpoints return the results expected.
  - [ ] GET	/v0/dependents_verifications
  - [ ] POST	/v0/dependents_verifications
- [ ] A spot check of the application works as expected OR recorded TestRail tests pass

**Comment by jacobworrell** [comment]
@laineymajor this feature should not be accessible to end users in production. My understanding is the code should be deprecated. Let's connect and discuss.

**Comment by laineymajor** [comment]
Sorry I didn't see this tag earlier @jacobworrell 

@RachalCassity @LindseySaari see the above comment ---- 
"@laineymajor this feature should not be accessible to end users in production. My understanding is the code should be deprecated. Let's connect and discuss."
