### ISSUE TITLE
[EKS Testing] [LOWERS] Certificate of Eligibility Status

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#52323]
In order to ensure consistent and correct behavior after the migration to EKS, we need to verify that the endpoints of this application are working as expected.

Be on the look out for errors that have to do with connectivity:
- Status Codes
  - 403: Forbidden * Check that a test user is signed in before marking as broken
  - 404: Not found * Check that the path is correct before marking as broken
  - 500: Internal Server Error
  - 502: Bad Gateway
  - 503: Service Unavailable
  - 504: Gateway Timeout
- General Errors
  - ERR_TOO_MANY_REDIRECTS: Redirect loop
  - Others?

AC:

Dev:
- [x] The following endpoints return the results expected.
  - [x] GET	/v0/coe/status
- [x] A spot check of the application works as expected OR recorded TestRail tests pass

Staging:
- [x] The following endpoints return the results expected.
  - [x] GET	/v0/coe/status
- [x] A spot check of the application works as expected OR recorded TestRail tests pass

**Comment by samcoforma** [comment]
Staging error: 

```{
	"errors": [
		{
			"title": "Gateway timeout",
			"detail": "Did not receive a timely response from an upstream server",
			"code": "504",
			"status": "504"
		}
	]
}

**Comment by samcoforma** [comment]
Staging seems to be working again:

```{
	"data": {
		"attributes": {
			"status": "ELIGIBLE",
			"reference_number": "18924856"
		}
	}
}
