### ISSUE TITLE
Platform Orientation Template Carey Otto

### ISSUE THREAD

**Issue by careyotto** [department-of-veterans-affairs/va.gov-team#52332]
Hello, I am the UX Lead for the VA Lighthouse program and need access to https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/ in order to have access to staging test user logins, please.

Because I'm on Lighthouse, I don't need any of the other platform orientation steps you usually include, just access to this repo.

Thank you!

**Comment by little-oddball** [comment]
@careyotto I do not have the permissions to be able to grant you access to that repos. This is typically something that is handled when going through the on-boarding process. I am gonna pass the request onto one of your platform dev-ops folks which should be able to help out. @pjholyoke

**Comment by careyotto** [comment]
Closing this ticket, and placing request on this one: https://github.com/department-of-veterans-affairs/va.gov-team/issues/53033
