### ISSUE TITLE
Draft content for key moments in grandfathering user flow

### ISSUE THREAD

**Issue by elizabethkochBT** [department-of-veterans-affairs/va.gov-team#52335]
## Issue Description
Users need to go through a series of steps in order to have their account grandfathered to Login.gov.

## Initiative
We will zoom in on key moments across the user flow to develop content. We'll focus on moments that are critical and less well-defined by existing prototypes. These are:

 - [Create an IAL1 account: Step 1](https://app.mural.co/t/innovationboards1199/m/innovationboards1199/1671554156732/bb8f2948581f649bf8fd8ad9816224d93818992d?wid=414-1673385361809) when a Veteran sees a banner alerting them to the need to set up Login.gov
 - [Connect back to VA: Step 3](https://app.mural.co/t/innovationboards1199/m/innovationboards1199/1671554156732/bb8f2948581f649bf8fd8ad9816224d93818992d?wid=350-1673385361809) when a Veteran returns to the VA website they started from and is told that they now have a Login.gov account and should use it moving forward
 - [Upgrade to IAL2: Step 1](https://app.mural.co/t/innovationboards1199/m/innovationboards1199/1671554156732/bb8f2948581f649bf8fd8ad9816224d93818992d?wid=199-1673385361809) when a Veteran signs into a VA service in a future session and see a banner prompting them to upgrade to an IAL2 account
 - Add task for error state
---
## Tasks
- [ ] TBD

## Acceptance Criteria
- [ ] TBD
---

**Comment by tygindraux** [comment]
Discussed with @CarlDickerson, we will keep this as one design ticket (#52074) and archive this ticket.
