### ISSUE TITLE
Automate product directory merging of bot updates

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#52347]
## Issue Description
At the time this feature was developed we were unsure how to merge directly to main for the automated product directory updates. Now that the product directory does not have a full-time owner, and we have figured this problem out on other initiatives, we should take the time to eliminate the human-maintenance step of this and set up auto-merging for automatic updates that don't have formatting concerns.

---
## Tasks
- [ ] Automate merging of changes to product directory that are done on daily schedule by our bot.

## Acceptance Criteria
- [x] Automatic updates to the product directory are merged without human intervention.
---

**Comment by CBonade** [comment]
The work for this issue has been completed. The PR is being held up currently by a failing E2E test that is under investigation. https://github.com/department-of-veterans-affairs/vets-website/pull/23233 PR link here. Estimate adjusted due to the complexity expanding to require a rewrite of the original code that drove this function.

**Comment by CBonade** [comment]
PR has been merged so this will take effect starting with tomorrow morning's scan.

**Comment by pjhill** [comment]
Looking good -- hooray for boldly auto-committing to main!
