### ISSUE TITLE
Define secondary navigation within the health portal

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#52367]
## Summary

Picking up from https://github.com/department-of-veterans-affairs/va.gov-team/issues/49253.

I believe this is roughly: "_As a user within the MHV on VA.gov health portal, how do I navigate between portal products such as Secure Messaging or Appointments while retaining my ability to navigate outside of the portal to other parts of VA.gov, so I can easily access all of the health and non-health content and tools I need._"

## Acceptance criteria
- [ ] Decision(s) documented
- [ ] Any follow on tickets created

**Comment by batemapf** [comment]
relevant thread: https://dsva.slack.com/archives/C04GDQSHD1R/p1676572672817329?thread_ts=1676400596.154349&cid=C04GDQSHD1R

**Comment by A6-toma** [comment]
Per conversation with Cara, this can be closed. May need to reopen in the future, but not likely.

![image.png](https://images.zenhubusercontent.com/645a5469a9467420f3cde02e/ccb4e685-1130-4845-a2cd-cc4a312d055b)
