### ISSUE TITLE
[Analytics] Discovery - Update Analytics dataLayer implementation to track Modernized Content

### ISSUE THREAD

**Issue by nedierecel** [department-of-veterans-affairs/va.gov-team#524]
## User Story
As an Analytics-Insights implementation team member, we want to be able to tag all Modernized tools and content with a dataLayer value. We are currently pulling Modernized data into a Google Analytics View that looks for the existence of the `GTM-WFJWBD`. This is set to custom dimension 30 in the Base Configuration settings within Google Tag Manager.

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/b55cab26-2169-43f3-86f7-5d0d97a1f1e5)

## Goal
- Determine if we should move away from current Modernized tracking implementation
- If so, work with engineering to determ a new custom dimension that tracks content as `Modernized` to distinguish this content

## Acceptance Criteria 
- [ ] Work with engineering to add custom dimension and value in dataLayer
- [ ] Update settings in GTM to distinguish Modernized dataLayer
- [ ] Validate and publish GTM container

## Definition of Done
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by nedierecel** [comment]
@bsmartin-ep Transitioning this issue to you. This is an optimization ticket that should be prioritized after VFS issues. 

**Background**:  For context when we launched the merged VA.gov site, we needed a way to distinguish modernized content from legacy content (e.g. MHV, eBenefits, etc.). 

**First Approach:**  I ran into Google Analytics view filter character limitations when we tried to filter by all the Modernized subdirectories (e.g. /health-care/, /disability/); furthermore, this may have included similar legacy content that we did not want to measure in the "WBC View".

**Working Approach:** I set a custom dimension within Google Tag Manager (dimension30) called `Content Custom Dimension - Modernized` that looks for the presence of container ID `GTM-WFJWBD`. 

**Ideas:** In place of setting the custom dimension to look for the container ID, is it a more robust solution to ask engineering to add new dataLayer variable to a global dataLayer? https://staging-va-gov-assets.s3-us-gov-west-1.amazonaws.com/js/record-event.js

**Comment by bsmartin-ep** [comment]
@jonwehausen  -

I _think_ we can close this one.

The **_TLDR_** is that we currently determine if a page is modernized by detecting if it is using GTM container _VA.gov Modernized Homepage and Tools (GTM-WFJWBD)_.

Nedie asked if it would be a better option to detect modernized pages by having the developers set the value in the dataLayer of the page or by running the page URL through a Regex Lookup table in GTM.

Do you see any situation where we have pages using this GTM container and we **do not want** to track them as modernized?  Or on the flip side, are there pages that **don't** implement this GTM container but we **do want to track** as modernized?

If no and no, I say we keep it as-is.  The chances of missing a page with the dataLayer change or our regex lookup outweighs the benefits (if any) in my opinion.

Thoughts?

**Comment by jonwehausen** [comment]
Sounds good - I think we're okay to maintain this existing structure for now. Closing.
