### ISSUE TITLE
Design Doc - review instances / ephemeral dev instances

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#5240]
## User Story or Problem Statement

As a VSP team member, I need a reference document to talk about design considerations and previous decisions made on review instances in order to communicate effectively about them with VFS teams building on the platform. Since we are re-vamping them as part of the attached epic, their description and purpose needs a revisit.

## Goal
Design doc about key problems, decisions, and use cases for review instances using the template: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/design-docs/design-doc-template.md

## Objectives or Key Results this is meant to further
O1: Any volume of simultaneous customers have a delightful, self-service, end-to-end experience using the Platform to build on VA.gov.				

## Acceptance Criteria
- [ ] design doc is written and approved for implementation on next iteration

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by meganhkelley** [comment]
@jhouse-solvd this is an old ticket that can probably be closed — I'm removing my team's label

**Comment by rmtolmach** [comment]
The QA Standards team is doing discovery for review instances. This can be closed.
