### ISSUE TITLE
Modify the 'Backend' Docker file to deploy `vets-api-mockdata`

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#52413]
# Description
Let's use the approach determined in the [ticket ](https://app.zenhub.com/workspaces/platform-tech-team-4-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/51943)to analyze and discover the best approach for creating a K8s-friendly Docker image of `vets-api` to create Docker images that are created and stored in ECR.

# Tasks
- [x] Use the approach defined in the discovery [ticket ](https://app.zenhub.com/workspaces/platform-tech-team-4-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/51943)to add `vets-api-mockdata` to the backend image

# Acceptance Criteria
- [x] A backend Docker image with `vets-api` and `vets-api-mockdata` can be created in a GHA and stored in ECR for use in a preview environment

**Comment by powellkerry** [comment]
I have begun the work to add vets-api-mockdata to the PE Dockerfile. vets-api-mockdata is a private repo so we will need to figure out how to pass credentials to the Dockerfile through GHA.

**Comment by powellkerry** [comment]
I have found some examples on how to pass secrets to the Dockerfile and have implemented them locally in my code. I need to figure out if there is already a used process of getting AWS param store values from a GHA task so that we can pass that to the Dockerfile.

**Comment by powellkerry** [comment]
I have updated this documentation to provide details on supplying the github user and password as secrets to the Dockerfile: https://vfs.atlassian.net/wiki/spaces/TT4/pages/2490761493/Vets-API+Docker+Image

**Comment by powellkerry** [comment]
This is complete, assuming that work to actually develop yml files to build and deploy the image is captured in other tasks.

**Comment by pjhill** [comment]
> This is complete, assuming that work to actually develop yml files to build and deploy the image is captured in other tasks.

It is -- nicely done, thanks!
