### ISSUE TITLE
Dev: implement message for when Veterans should request appointment using VA flow not CC flow

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#5241]
## User Story or Problem Statement
When a user is trying to request a Community Care appointment, but they already have a VA PACT assigned to them in the VA health system they chose, we need to create a message letting the Veteran know that they should request CC appointment near a different VA health systems or request through VA request flow.

Screenshot of the page where in-line message would appear: 
![2020-01-07 (2).png](https://images.zenhubusercontent.com/59b0414bb0222d5de476aa22/d23450ee-8efb-4295-9118-ab335d873c4f)

In-line message:

You can't choose this location for your appointment since you already have a VA care team assigned to you within this VA health care system. Please choose a different VA health care system or [request a VA appointment](TK link to screen in VA request flow).

**Comment by lenaecb** [comment]
Haven't seen this come back up since re-enabling CC . Closing.
