### ISSUE TITLE
Research Likert scale use for updated Survey

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#52421]
## Issue Description
Given the discussions and learnings of previous tickets, perform a quick desk research effort on the Likert scale's utility for our Survey purposes.

Research [notes](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2491383911/Quant+Measure+Options+Likert+Scales+and+Others#How-does-the-above-inform-what-we-are-trying-to-measure%3F)

## Tasks
- [x] Review usefulness
- [x] If useful, provide guidance on how to implement

## Acceptance Criteria
- [x] [Guidance](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2491383911/Quant+Measure+Options+Likert+Scales+and+Others#Recommendation) provided

**Comment by twoangstroms** [comment]
[Papercut surveys](https://shoptalkshow.com/535/)

[SenseMaker](https://thecynefin.co/how-to-use-data-collection-analysis-tool/)
