### ISSUE TITLE
Run discovery with staff - provider-based scheduling

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#52420]
## Task Description
Run a contextual inquiry with staff to understand current processes and issues with facility selection and managing resources.

## References
* [Internal discovery doc](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/health-care/appointments/research/2022-12-provider-based-multi-modality-scheduling-discovery/discovery-round-1-internal.md)
* [Research folder](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/products/health-care/appointments/research/2023-2-staff-research-provider-based-and-multi-modality-scheduling)

## Acceptance Criteria
- [ ] Research report is complete

---

**Comment by outerpress** [comment]
* Update plan based on @kristenmcconnell feedback
* Schedule logistics meeting

* Waiting on business to answer questions about facility business rules

**Comment by melissa-lefevre** [comment]
I updated the [questions to ask in Columbus ](https://app.enjoyhq.com/sh/doc/ecc38ecc-55ec-4e46-b721-30b11c50fd12)given our observations and research findings from Pittsburgh and Portland.

**Comment by melissa-lefevre** [comment]
Closing as I concluded the research and completed the report. I am now sharing out with various teams and working on next steps within the recommendations.
