### ISSUE TITLE
Content, design, and a11y review for new terms of service/privacy policy acceptance screens

### ISSUE THREAD

**Issue by artsymartha68** [department-of-veterans-affairs/va.gov-team#5242]
# Description of request

The Cerner EHR ("My VA Health") will be slowly coming online for the VA system over the next 10 years, up to a few facilities at a time. Before a Veteran can use Cerner for the first time, they must first accept the new terms of service/privacy policy (similar to a EULA, but this will all be on a single page). The Veteran should only have to accept this policy once once or if these policies have major revisions in the future. If the Veteran does not accept the policy, they cannot log into their Cerner EHR.

### Provide a link to product brief or outline:

Forthcoming (requirements are coming from Cerner)

### Provide a link to wireframes, prototype:

First draft, there are still open issues TBD

### Provide a link to any user research synthesis

n/a

### Do you need new URLs, redirects? (If yes, submit URL and redirect requests first to @ Mikki Northuis on the Platform team.)

This is being taken care of by the Apothesource team, I believe. These pages will live on VA Mobile servers (per my current understanding).

### Desired/target implementation date

Feb 7, 2020

### Is there an ETA for a particular launch or completion date when request needs to be completed (for instance, for a user research session or eBenefits migration)? Our team's capacity will determine which sprint the work falls into.

End of March is the first site (Spokane) where Veterans will see this functionality and be migrated to Cerner. 

### Type of support request

We need content support for authenticated app/tool. The terms of service/privacy policy has already undergone reviews from lawyers and other experts so this aspect of the project does not need additional content support.

In addition to the above general information, include:
1. Word document with draft if available, or link to the URL where the draft content appears: I'm having a hard time uploading docs to GH today
2. Provide design context: (Example: Is this content in a user flow, an in-line error message, tool tip, field label?): User has successfully logged into MHV and needs to accept the new My VA Health terms before they can proceed to My VA Health
3. Scope: How many screens? (Or messages, etc.): Around 5 screens total

# Requestor info

Indicate what team and who the primary contacts are on your team

### Team name

Patient portal

### DEPO product owner

Lauren Alexanderson @lalexanderson-dsva 

### Project manager 

Jenna Gaze (Apothesource) jenna@apothesource.com

### Designer

Martha Wilkes @artsymartha68 

### Content designers 

Selina Cooper scooper@governmentcio.com  

### FE engineer

Mike Ramirez (Apothesource) michael@apothesource.com

### Other team members

- carnetta.scruggs@va.gov
- richard.harman@va.gov
- gary.howard@va.gov
- craig@apothesource.com

### Product/team Slack channel

patient-portal

### Additional request

We'll also need an accessibility audit/review from @1Copenut

**Comment by artsymartha68** [comment]
[visualDesignProposal.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4124550/visualDesignProposal.docx)

**Comment by mnorthuis** [comment]
@artsymartha68 can you elaborate on this?

> These pages will live on VA Mobile servers (per my current understanding).

Are these pages being hosted outside of va.gov?

**Comment by artsymartha68** [comment]
@mnorthuis Yes we verified that these pages will live on the VAMF (VA mobile framework) servers. We had a second design review with the dev team and they took many of our suggestions. Their updated prototype is here:

First Encounter
https://xd.adobe.com/view/2bd16158-5924-4eda-45ff-f5c26bc5b2fa-5de0/

Provisioned User - Updated Terms of Use
https://xd.adobe.com/view/9f63a233-d8b3-4ca5-4a52-4415fe992639-e952/

Pass: MyVAHealth@123#

**Comment by CrystabelReiter** [comment]
Hi @artsymartha68 at what stage of the process are you guys in? Are these mockups more of exploratory ideas? or are these ready to go into user testing?

Could we schedule a 30 minute design review call where we can all take a look and hear the context of your work? We have open design review hours from this Tuesday, 11:30AM-12PM (EST) and Thursday 1:30 PM-2:30 PM EST. Please let me know which 30 minute time block can work best for you!

**Comment by artsymartha68** [comment]
Hi folks. Selina is making her content recommendations this week. If I were to come back to the dev team with more UI changes that might hurt our working relationship so I am resistant to do that now. 

I did have a first review with Kevin, Ryan, and Jen which resulted in the current set of suggestions. Happy to have another but, like I said, the dev team will not be amenable to any further changes.

**Comment by jenniferlee-dsva** [comment]
Unassigned folks not delivering for this ticket. @peggygannon - kept you on to for review. 

@lunascoop @artsymartha68 - please be sure to have Peggy review and give feedback. As we're onboarding Selina to this new role (which Peggy used to fill), I really want Selina to benefit from Peggy's experience with product UI/microcopy practice. 

Thanks!

**Comment by artsymartha68** [comment]
I sent an email to the Apothesource team to ask if they have a11y expertise to do a review. I'll report back to this issue if it turns out they need help.

**Comment by MickinSahni** [comment]
Blocked on this. Went back and forth with stakeholder on updated copy/recommendations but have not received this yet. 
@jenniferlee-dsva — would you be able to help un-block this or direct me how?

**Comment by MickinSahni** [comment]
2020-02-06 PW Standup
- Still waiting for Chip
- Risk of not meeting deadline tomorrow (Friday)
cc @jenniferlee-dsva

**Comment by lunascoop** [comment]
Here is a draft copy deck with content suggestions for review @peggygannon . SME feedback from Chip has not been received. Reviewed copy with @artsymartha68 this afternoon and awaiting confirmation from @lalexanderson-dsva to move forward in sending content suggestions to Chip before hearing from him.

[EULA-Terms of Service -Copy Deck.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4172520/EULA-Terms.of.Service.-Copy.Deck.docx)

**Comment by artsymartha68** [comment]
Thanks @lunascoop for providing a draft copy deck instead of remaining blocked by our busy stakeholders 👍

**Comment by MickinSahni** [comment]
2020-02-11 PW Standup
- Waiting for confirmation from Lauren A. before Selina sends to Chip
- Pull out into Backlog sans Milestone until we get stakeholder feedback

**Comment by lunascoop** [comment]
Draft copy sent to Chip on **Feb 10th**. It seems there is a delay in Chip getting back to me due to higher priorities. Awaiting feedback/content

**Comment by peggygannon** [comment]
Hi, @lunascoop I'm going to drop in your draft copy for review into this ticket (https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/5491), which @jenniferlee-dsva created for the content review.

**Comment by lunascoop** [comment]
I sent an updated copy deck using Craig Schneider's content audit format on 02/19. Theresa will be taking over for Chip on these efforts.
[Signup Copy Deck-Recommendations -SC.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4225478/Signup.Copy.Deck-Recommendations.-SC.docx)

**Comment by MickinSahni** [comment]
2020-02-19 PW Standup
- once we're nearly wrapped up, we'll add to sprint 15 and validate/close-out
- possibly demo with theresa tomorrow

**Comment by lunascoop** [comment]
@peggygannon I have reviewed the final draft of the My VA Health content and made some edits in tracked changes mode. I have attached it here for your review.
[My VA Health Content Mock Up Login and Terms of Agreement - FINAL DRAFT -SC.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4238487/My.VA.Health.Content.Mock.Up.Login.and.Terms.of.Agreement.-.FINAL.DRAFT.-SC.docx)

**Comment by peggygannon** [comment]
@lunascoop is there anything more you need from me on this ticket?

**Comment by lunascoop** [comment]
@peggygannon No, I don't need anything else from you on this ticket. @artsymartha68 Can we close this?

**Comment by artsymartha68** [comment]
I have heard nothing from the dev team. Yes let’s close, we can always reopen if need be.
