### ISSUE TITLE
DEV BRD Deprecation: Statsd Custom exporter mapping

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#52428]
https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/vets-api/statsd-exporter-mapping.conf#L27-L31

**Comment by rmtolmach** [comment]
`api_jobs_enqueued` is also mentioned in the vets-api datadog dashboard: https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/datadog/dashboards/vets_api_dashboard.json#L591

**Comment by laineymajor** [comment]
working on other items first THEN moving to deprecation work

**Comment by LindseySaari** [comment]
It appears that api_jobs_enqueued is [used in this board](https://vagov.ddog-gov.com/dashboard/t29-k8v-ctv/vets-api-dashboard?fullscreen_end_ts=1676909387916&fullscreen_paused=false&fullscreen_section=overview&fullscreen_start_ts=1676905787916&fullscreen_widget=5504130131431674&from_ts=1676905721379&to_ts=1676909321379&live=true). I think we may be able to use this metric for the Sidekiq HPA

**Comment by LindseySaari** [comment]
I added the [necessary changes to utilize the official metrics from the Sidekiq <> Datadog integration](https://vagov.ddog-gov.com/dashboard/t29-k8v-ctv/vets-api-dashboard?fullscreen_end_ts=1677013987776&fullscreen_paused=false&fullscreen_section=edit&fullscreen_start_ts=1677013087776&fullscreen_widget=5504130131431674&tpl_var_cluster_name%5B0%5D=dsva-vagov-staging-cluster&tpl_var_env%5B0%5D=eks-staging&tpl_var_environment%5B0%5D=staging&from_ts=1677011271253&to_ts=1677012171253&live=true). See the metrics prefixed with `sidekiq.` This will be ready to go once we no longer have the custom statsd exporter mapping

**Comment by laineymajor** [comment]
Can close per @LindseySaari for now... there will be stuff to do after go-live
@laineymajor create new ticket for post-golive work
