### ISSUE TITLE
DEV BRD Deprecation: Phantom servers/workers

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#52437]

**Comment by laineymajor** [comment]
@considerable Coordinate first with @LindseySaari, then CoP, then Kyle if needed.

**Comment by laineymajor** [comment]
@considerable have you had a chance to start this? I know we've been putting out fires, so no problem if you haven't had time yet... just checking!

**Comment by laineymajor** [comment]
Igor to kill helm101 first.
Then will start this.

**Comment by laineymajor** [comment]
Need to complete the blocking ticket

**Comment by considerable** [comment]
@rmtolmach and CoP DevOps isolated the problem in the AutoScale Group in Dev - it is set to 0 now.
