### ISSUE TITLE
DEV BRD Deprecation: Certs verification

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#52433]
Certs - verification
- See example [key/certs here](https://github.com/department-of-veterans-affairs/devops/blob/f2483e1a51fd90f42da86334b4016a7789562344/ansible/deployment/config/vets-api-server-vagov-dev.yml#L224-L240) - Are we mounting in the same way in k8s?
- [Worker example](https://github.com/department-of-veterans-affairs/devops/blob/f2483e1a51fd90f42da86334b4016a7789562344/ansible/deployment/config/vets-api-worker-vagov-dev.yml#L207-L217)

**Comment by laineymajor** [comment]
@RachalCassity might want to be involved with this ticket... any tips for Igor?

**Comment by laineymajor** [comment]
still focusing on load testing plan THEN move to this

**Comment by laineymajor** [comment]
igor focusing on load testing plan THEN will move on to this

**Comment by laineymajor** [comment]
Since you have reached a point of near-completion, please start this ticket @considerable

**Comment by laineymajor** [comment]
@considerable please start this on Monday when you return. I would like this to be completed by end of sprint.

**Comment by laineymajor** [comment]
@considerable will work on this PR today.

**Comment by laineymajor** [comment]
@considerable please provide work on what was completed yesterday.

**Comment by considerable** [comment]
The source of truth for EKS is in https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/main/apps/vets-api/dev/templates/secrets.yaml

That needs to match against the BRD source of truth in devops repo and the number of certs looks like no more than 145
```
find .  -name '*pem' -or -name '*crt' | wc -l
```
> 145 

Can tell more precisely upon longer diving into it.

**Comment by laineymajor** [comment]
@considerable are you saying this requires discovery? That's what I read when you write, "longer diving into it"...

**Comment by considerable** [comment]
- All 84 certs can be found as follows: 
```
grep -oE ' /.*dev.*(key|crt|pem|p12)' apps/vets-api/dev/templates/secrets.yaml  | sort > /tmp/certs_all.txt 
```
- Unique 79 of them can be found as follows: 
```
grep -oE ' /.*dev.*(key|crt|pem|p12)' apps/vets-api/dev/templates/secrets.yaml  | sort -u > /tmp/certs_unique.txt
```
- The duplicates are:
  -  /devops/certificates/dgi-int.crt
  -  /dsva-vagov/vets-api/dev/chip_api/key
  -  /dsva-vagov/vets-api/dev/google_analytics_cvu/private_key 
  - /dsva-vagov/vets-api/dev/healthquest/key
  -  /dsva-vagov/vets-api/dev/vagov-mobile-app-api-server-lowers.pem

If there is a solid idea of how exactly do we verify then no discovery is required. Let's find it during the next standup.

**Comment by laineymajor** [comment]
@considerable please come to standup with a solution proposal. Then the team can react to your solution. Thanks!

**Comment by laineymajor** [comment]
Steps to complete work:
1. Open up BRD instance
2. Check devops settings
3. Pull up the argo terminal
4. Check the manifest settings

Task:
1. Verify correct certs ARE in fact mounted in the correct place (do this by SSM into a BRD instance, pull up the argo terminal, and compare)
2. Verify the value against current BRD prod (use the BRD vs EKS instance)

Should not be a huge lift to put them in EKS in the first place, we just copied what existed in BRD.

Note from Rachal:
- ansible/deployment/config/vets-api-server-vagov-dev.yml

**Comment by laineymajor** [comment]
@considerable needs to finish the work from the cert renewal, then will start this. Igor is also on support so needs to straddle this ticket with support.

**Comment by laineymajor** [comment]
@considerable this needs an update asap. I know you are helping with certs, but please provide updates

**Comment by considerable** [comment]
Nailed it - NOT all 26 certs from BRD are matching different envs of EKS:

1) list of BRD 26 certs (no duplicates):
```
grep -oE '/devops.+(crt|pem|key)' \
  ansible/deployment/config/vets-api-server-vagov-dev.yml \
  | sort -u > /tmp/brd_certs.txt
```

2) list of 11 EKS dev certs (1 duplicate: dgi-int.crt):
```
grep -oE '/devops.+(crt|pem|key)' \
  -r ../vsp-infra-application-manifests/apps/vets-api/dev \
  | sort -u > /tmp/eks_dev_certs.txt
```

3) list of 14 EKS certs in staging (1 duplicate: vagov-mobile-app-api-server-lowers.key):
```
grep -oE '/devops.+(crt|pem|key)' \
  -r ../vsp-infra-application-manifests/apps/vets-api/staging \
  | sort -u > /tmp/eks_staging_certs.txt
```

4) list of 7 EKS certs in prod:
```
grep -oE '/devops.+(crt|pem|key)' \
  -r ../vsp-infra-application-manifests/apps/vets-api/prod \
  | sort -u > /tmp/eks_prod_certs.txt
```

5) list of 7 EKS certs in sandbox:
```
grep -oE '/devops.+(crt|pem|key)' \
  -r ../vsp-infra-application-manifests/apps/vets-api/sandbox \
  | sort -u > /tmp/eks_sandbox_certs.txt
```

Working on resolving those differences is another body of work, closing the tkt.
