### ISSUE TITLE
DEV BRD Deprecation: Server and worker deploy on merge to master

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#52438]
http://jenkins.vfs.va.gov/job/testing/job/vets-api/job/master/

**Comment by laineymajor** [comment]
Might be done, but should be verified.

**Comment by LindseySaari** [comment]
It looks like the vets-api-server dev is still being deployed regularly: http://jenkins.vfs.va.gov/job/deploys/job/vets-api-server-vagov-dev/

**Comment by laineymajor** [comment]
@RachalCassity can you complete this before you leave for vacation? We need this done first before Igor can start his deprecation ticket. Thanks!

**Comment by laineymajor** [comment]
From the slack messages this morning, am I correct in assuming @rmtolmach is taking over this ticket?

**Comment by laineymajor** [comment]
Priority today for Rebecca. That way Igor can proceed with other deprecation ticket (blocked by this ticket) tomorrow.

**Comment by rmtolmach** [comment]
Deleted http://jenkins.vfs.va.gov/job/deploys/job/vets-api-worker-vagov-dev/ and http://jenkins.vfs.va.gov/job/deploys/job/vets-api-server-vagov-dev/ directly from Jenkins.

**Comment by rmtolmach** [comment]
**Note** When deleting things from the Jenkinsfile (like I did in https://github.com/department-of-veterans-affairs/vets-api/pull/11781), or any other file that isn't in the k8s branch, the [sync_branch GitHub Action](https://github.com/department-of-veterans-affairs/vets-api/actions/workflows/sync_branch.yml) will fail. To resolve, push directly from master into k8s branch.
