### ISSUE TITLE
Adding Christopher Simmons to DSVA Slack

### ISSUE THREAD

**Issue by EricaRobbins** [department-of-veterans-affairs/va.gov-team#52439]
Please add Christopher Simmons as a full member. Email addresses:
- VA: christopher.simmons4@va.gov
- Contractor / Sprezzatura Email: [csimmons@sprezzmc.com](csimmons@sprezzmc.com)
- Label: **[GovCIO_VetsPS]**
- What channel(s) do they need to be added to?
   - **cto-ops-bna-pmo**

# Description

New User - Confirmed. New member of the OCTO-DE PMO Team, Acquisition Specialist supporting Mark Junda, Josh Cohen, and Jeffrey Barnes.

**Comment by EricaRobbins** [comment]
Good Morning @LEHigley - can you approve this Slack Request when you get a chance? Many thanks!

**Comment by LEHigley** [comment]
looks lke the invite had been sent last week

**Comment by EricaRobbins** [comment]
@LEHigley - unfortunately, Chris Simmons was experiencing issues with Outlook and never received this request to join Slack. Can you please resend the invitation? 

Thank you in advance!
