### ISSUE TITLE
DEV BRD Deprecation: Archive any dev BRD documentation

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#52431]
⚠️  Lists are a work-in-progress. Some pages may need small edits only (as opposed to complete overhauls or removal).

### Confluence
- [ ] https://vfs.atlassian.net/wiki/spaces/OT/pages/2231304195/Platform+Infrastructure+Diagrams - note diagram as deprecated?
- [ ] https://vfs.atlassian.net/wiki/spaces/OT/overview

### Platform Website
Pages in the **Developer docs** section are edited [in this Confluence Space](https://vfs.atlassian.net/wiki/spaces/pilot/overview?homepageId=582811793).
- [ ] https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks
- [ ] https://depo-platform-documentation.scrollhelp.site/developer-docs/backend
- [ ] https://depo-platform-documentation.scrollhelp.site/developer-docs/deployment-process
- [ ] https://depo-platform-documentation.scrollhelp.site/developer-docs/environments
- [ ] https://depo-platform-documentation.scrollhelp.site/developer-docs/statsd-metrics (mentions `vets-api` running on EC2 instances)
- [ ] https://depo-platform-documentation.scrollhelp.site/developer-docs/triaging-api-errors

**Comment by laineymajor** [comment]
Hoping to get on this later today @RachalCassity

**Comment by laineymajor** [comment]
@RachalCassity do you anticipate this being done by end of sprint? I know you've had a lot of other things (ex: ClamAV) creep up.

**Comment by RachalCassity** [comment]
@laineymajor Is this just the file audit or actually updating the docs?

**Comment by laineymajor** [comment]
This is for deprecation of old BRD docs... If you want to go ahead and do it, that's fine for these. Just make sure and note the work is complete on the [audit doc](https://docs.google.com/spreadsheets/d/1rTacvOYTXh3jMehzlfd0gGMlhiQOqu_Re-kKrGUVY80/edit#gid=0). Thanks!

**Comment by laineymajor** [comment]
Removed from sprint 21 (feb 16-28). We decided it would be best practice to complete an entire document audit of the platform website THEN complete the edits/removals of old BRD documentation all at once. This will likely be during sprint 23.

**Comment by RachalCassity** [comment]
@laineymajor I will close this issue then. I have updated the audit documentatio

**Comment by RachalCassity** [comment]
@laineymajor Perfect!!
