### ISSUE TITLE
revproxy config updates for review instances

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#5243]
## User Story or Problem Statement

The current review instance implementation uses an Ansible role and template for the revproxy configuration that is out-of-date from what's in use on production. We need to figure out a better model for running the revproxy and devise a way to keep the configurations in sync.

## Goal

Get revproxy configuration on review instances closer to the same as production, ideally using the same configuration template if possible

## Objectives or Key Results this is meant to further

- 5. Ensure VSP scalability through increased self-service tooling and documentation				"

## Acceptance Criteria

- [x] remove duplicate and out-of-date configuration from ansible/roles/revproxy-configure/templates

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jbritt1** [comment]
Awaiting guidance from @wyattwalter.

**Comment by jbritt1** [comment]
After multiple discussions, I believe we are going to try to get the work that was completed merged and then close this for now under the idea that this will likely be revisited during the infrastructure overhaul work.
