### ISSUE TITLE
DEV BRD Deprecation: Vets-API post deploy action

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#52435]
http://jenkins.vfs.va.gov/job/deploys/job/vets-api-server-vagov-dev-post-deploy/

**Comment by LindseySaari** [comment]
PR is merged, waiting for an Ops member to run the Jenkins seed job

**Comment by LindseySaari** [comment]
The PR has been merged, but I've asked the [devops CoP](https://dsva.slack.com/archives/C04CYC4LMU6/p1675954145489899) because I still see it in the seed-job list

**Comment by LindseySaari** [comment]
Devops was able to delete the job. Closing this.
