### ISSUE TITLE
Incorporate feedback into Yellow Ribbon MVP prototype

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#5244]
## Acceptance Criteria:
Update prototype based on research feedback
- split out `Location, state, or school campus` field into more logical grouping based on the data we have
- update  labels in school cards
    - `School or program` to `School website`
   - `Maximum Yellow Ribbon Benefit Amount` should include `(per student, per year)`
   - `Degree Type` TBD, need to confirm with team
-  Create a version of the prototype without comparison functionality

**Comment by MickinSahni** [comment]
Putting this into Ready until we're able to estimate/commit in Sprint 14.

**Comment by MickinSahni** [comment]
2020-02-12 PW Sprint Planning
- reviewed and committing to sprint 15

**Comment by MickinSahni** [comment]
2020-02-13 PW Standup
- Hey Jen, Liz is looking for feedback from you re: Education team
https://dsva.slack.com/archives/C52CL1PKQ/p1581553932093400

**Comment by AnneHurley** [comment]
1. For the apply page: https://www.va.gov/education/how-to-apply/
***Suggest we add a link in the list that mentions GI Bill comparison tool**:

**How do I prepare before starting my application?**
**Find out if you’re eligible for VA education benefits**
Gather the documents and information listed below that you’ll need to apply for education benefits.
See what benefits you’ll get at the school you want to attend.

- Use the GI Bill Comparison Tool
- Use the Yellow Ribbon Program Comparison Tool [[this is new]] 

2. For the post GI Bill eligibility page: https://www.va.gov/education/about-gi-bill-benefits/post-9-11/
TBD

**Comment by andaleliz** [comment]
@AnneHurley I'm confused - is this the copy that should be added to the landing page for the Yellow Ribbon MVP tool? If so, could you provide all the copy for the page, with the updates, just so it is extra clear where the additions should fall within the existing copy?

**Comment by AnneHurley** [comment]
From @jenniferlee-dsva:
Nope - links on [[[to??]] the page that the tool is on, not the tool itself. Although I defer to @Liz Lantz to recommend the UX design wrt where they should be.
My rationale is that students cannot get YR funding if they haven’t applied for the Post-9/11 GI Bill benefit.
Some students who look for YR participating schools may already have applied, but some may not have. So we just want to make sure that we are providing clear and prominent links to Post-9/11 GI Bill eligibility info and to apply for Post-911 GI Bill benefit.

Jennifer Lee  3 minutes ago
And apologies if the tool page already has CTA links to the GI Bill benefit info. I’ve only seen the tool without the context of how this will live on a page or be linked to from other pages, so I may be missing information that’s already accounted for

So @andaleliz to recap: we need links to the tool page from: 
1. The apply page: https://www.va.gov/education/how-to-apply/
*Suggest we add a link in the list that mentions GI Bill comparison tool:
**How do I prepare before starting my application?**
**Find out if you’re eligible for VA education benefits**
Gather the documents and information listed below that you’ll need to apply for education benefits.
See what benefits you’ll get at the school you want to attend.

**Use the GI Bill Comparison Tool**
**Use the Yellow Ribbon Program Comparison Tool** [[this is new]]

2. For the post GI Bill eligibility page: https://www.va.gov/education/about-gi-bill-benefits/post-9-11/
FROM ANNE: If we want to add a link to the YR Comparison Tool page from this page, we may want to re-think the content strategy/flow of the page. YR is mentioned midway down the page with a link to the main YR page. Then the GI Bill Comparison tool is at the very bottom of the page. We could add links in both places to the YR comparison tool page. Thoughts?

3. Have we decided where on the actual Yellow Ribbon Program page we want to have copy about the comparison tool? https://www.va.gov/education/about-gi-bill-benefits/post-9-11/yellow-ribbon-program/
And will we be eliminating any of the current copy or links when the YR tool goes live - see list of schools, and/or the long list of accordions at the bottom that link to Team Site? @jenniferlee-dsva  @mnorthuis

**Comment by AnneHurley** [comment]
From @jenniferlee-dsva do you want to see these links on the initial screen users will land on, that has the intro copy and the link that says Find out of you qualify for the Yellow Ribbon Program?
Can I see the pages for context? I know there's the page we link to the tool from; the page with the tool; and... not sure if the results are displayed on that same page (like our forms search) or on a still different page.
My main concern is that on the page where users see their search results, there should be clear CTAs  to the Post-9/11 GI Bill.
Eligibility: https://www.va.gov/education/about-gi-bill-benefits/post-9-11/
Apply: https://www.va.gov/education/how-to-apply/

Jennifer Lee  < 1 minute ago
@Anne Hurley - could you do a parity/content check on the eligibility info that's shown on the YR program page https://www.va.gov/education/about-gi-bill-benefits/post-9-11/yellow-ribbon-program/  -- is the Post-9/11 GI Bill eligibility info on the YR page the same as the ones listed on the Post-9/11 GI Bill eligibility page? (Minus the stuff specific to YR schools of course.) The bullet points look similar but not exactly the same.
Concerned that we may be showing 2 different versions of Post-9/11 GI Bill eligibility criteria on these 2 pages -  YR program page and the Post-9/11 GI Bill eligibility page.
Veterans AffairsVeterans Affairs
Yellow Ribbon Program | Veterans Affairs
Learn how the Yellow Ribbon Program can help you pay for tuition not covered by the Post-9/11 GI Bill if you're a qualified Veteran or eligible dependent of a Veteran. Find out if your school participates in the program.

**Comment by MickinSahni** [comment]
- making additional updates to prototype and then will close out
- met with jen re: content updates to be made

Note: capturing design decisions. will be doing this for yellow ribbon - @MickinSahni create a ticket for sprint 15

**Comment by MickinSahni** [comment]
2020-02-20 
- Opened an issue for content changes related to this prototype for Anne - Liz

**Comment by MickinSahni** [comment]
- IA recs from Mikki e.g. related to adding YR to left nav, Randi likely to implement (bc changes are required in Drupal)
  - Spin up ticket to make the changes (but put a blocker label on it until we're able to launch likely in Backlog) cc @AkucherGCIO

**Comment by AkucherGCIO** [comment]
Added #384 to the backlog for IA recs from Mikki.

**Comment by AkucherGCIO** [comment]
02-24-20 PW standup
- Jen needs to review the content and language on it.

**Comment by AkucherGCIO** [comment]
02-26-20
@AnneHurley @andaleliz @jenniferlee-dsva - What is the effort left on this and can it be closed out as done in Sprint 15 ?

**Comment by andaleliz** [comment]
@AkucherGCIO - the effort left on this is really minimal, just some small copy edits. yes, we can go ahead and close as done in sprint 15
