### ISSUE TITLE
External SiS Report

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#52455]
This ticket encompasses the setup of a readonly linkable DataDog dashboard that is available to anyone outside of our team. [Here is a resource for sharing a dashboard externally if needed](https://www.datadoghq.com/blog/dashboard-sharing/).

Questions/Research Items:

- [ ] Figure out exactly what we want to show by asking John Rahaghi (Alyssa)
- [ ]Make sure there is no PII, we probably cant show raw logs, but this shouldn't be a need anyway (Joe)

Once research is complete and the dashboard is created, Alyssa will send to John Rahaghi.

**Comment by joeniquette** [comment]
complete
