### ISSUE TITLE
Renew vaprofile/vet360 SSL Certificates

### ISSUE THREAD

**Issue by ianhundere** [department-of-veterans-affairs/va.gov-team#52467]
## Description
This ticket relates to the following support request:
- https://dsva.slack.com/archives/CBU0KDSB1/p1674225533988819?thread_ts=1674225233.875359&cid=CBU0KDSB1
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/52317

This is some important documentation surrounding VA Profile; "Vets360 was renamed to VA Profile in early 2020, however it continues to be referenced as Vets360 throughout our code.":
- https://vfs.atlassian.net/wiki/spaces/PWD/pages/1885602002/VA+Profile

The necessary places in which we install/deploy that cert are as follows in the devops repo:
- `devops/ansible/deployment/config/fwdproxy-vagov-dev.yml`
- `devops/ansible/deployment/config/fwdproxy-vagov-prod.yml`
- `devops/ansible/deployment/config/fwdproxy-vagov-sandbox.yml`
- `devops/ansible/deployment/config/fwdproxy-vagov-staging.yml`

Further information emailed to me by @little-oddball:

**Current Scheduled Certificate Updates**
PREPROD  - _Monday 1/12/23 - 5PM ET_
`ppd.vaprofile.va.gov`
`ppd.static.vaprofile.va.gov`

PRODUCTION  - _Wednesday 1/25/23 - 6PM ET_
`www.vaprofile.va.gov`
`prd.vaprofile.va.gov`
`www.static.vaprofile.va.gov`
`prd.static.vaprofile.va.gov`

## Further info
Looking at older PRs, it looks as if the vaprofile hostname used to be vet360 (just thought i would include these)? 
- https://github.com/department-of-veterans-affairs/devops/pull/10732 (this one especially as it highlights the work that needs to be done)
- https://github.com/department-of-veterans-affairs/devops/pull/7734

## Acceptance Criteria
- [ ] Replace the necessary vaprofile certs

**Comment by little-oddball** [comment]
In addition to the creation of this ticket, the item was posted in the DevOps CoP for discussion and if anyone had bandwidth to pick it up. That conversation was here:

https://dsva.slack.com/archives/C04CYC4LMU6/p1674574946189239

The TLDR:

@considerable  was willing to pick up based on his bandwidth and time zone but wanted additional information, support.
@ph-One  looked more into the request, the details and dug into working to understand what we might need to do on platform to properly support. After looking deeply into it, the feeling is there is nothing required on our end.

**Comment by little-oddball** [comment]
Added additional labels, assignees based on folks involved and sprint.

Will leave unresolved until after 1/25 when certs get rotated out

**Comment by ianhundere** [comment]
also doesn't looks like these certs expire until april:
```
[root@ip-10-247-33-83 ~]# echo "" | openssl s_client -showcerts -connect www.vaprofile.va.gov:443 2>/dev/null | openssl x509 -noout -enddate
notAfter=Apr 23 15:25:48 2023 GMT
[root@ip-10-247-33-83 ~]# echo "" | openssl s_client -showcerts -connect prd.vaprofile.va.gov:443 2>/dev/null | openssl x509 -noout -enddate
notAfter=Apr 23 15:25:48 2023 GMT
[root@ip-10-247-33-83 ~]# echo "" | openssl s_client -showcerts -connect www.static.vaprofile.va.gov:443 2>/dev/null | openssl x509 -noout -enddate
notAfter=Apr 23 15:25:48 2023 GMT
[root@ip-10-247-33-83 ~]# echo "" | openssl s_client -showcerts -connect prd.static.vaprofile.va.gov:443 2>/dev/null | openssl x509 -noout -enddate
notAfter=Apr 23 15:25:48 2023 GMT
```

**Comment by ianhundere** [comment]
looks as if we don't manage these certs; more info:
- https://dsva.slack.com/archives/C04CYC4LMU6/p1674574946189239

**Comment by ianhundere** [comment]
after further investigation, it doesn't look like these certs are managed by us:
- https://dsva.slack.com/archives/C04CYC4LMU6/p1674574946189239

**Comment by ianhundere** [comment]
looks like we don't manage these certs; more info:
- https://dsva.slack.com/archives/C04CYC4LMU6/p1675197337256639?thread_ts=1675193069.371379&cid=C04CYC4LMU6
