### ISSUE TITLE
VA Request Flow - Alerts for invalid input/selection 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#52465]
## Description
In VAOS, the user has the ability to schedule an appointment or submit a request for an appointment. In the request flow, the Veteran may think they are scheduling an appointment but they are submitting a request for an appointment. When requesting for an appointment, the Veteran does not have a confirmed appointment until the VA staff schedules an appointment on their behalf.

We will be updating the alerts for invalid input/selection in the VA request flow. No changes for the direct scheduling workflow. Community Care request flow will be worked on in ticket [#52480](https://app.zenhub.com/workspaces/vaos-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/52480)

---

## Acceptance Criteria

- [x]  Given when the user starts scheduling in VAOS and is in the VA request flow
When the user lands on the date selection page, does not select a date, and clicks `Continue`
Then the user will see an error message `Select at least 1 preferred timeframe for your appointment` 
And page design matches the [design spec](https://www.figma.com/file/ewxCGm9dkvYt5wiNXMwvkL/Request-flow-content-update-%7C-Appointments-FE?type=design&node-id=607-21790&mode=design&t=nyMoz7Z4C7jyCji3-4)

- [x]  Given when the user starts scheduling in VAOS and is in the VA request flow
When the user lands on the choose your reason for appointment page, does not select a reason, and clicks `Continue`
Then the user will see an error message `Select a reason for your appointment` 
And page design matches the [design spec](https://www.figma.com/file/ewxCGm9dkvYt5wiNXMwvkL/Request-flow-content-update-%7C-Appointments-FE?type=design&node-id=607-22184&mode=design&t=nyMoz7Z4C7jyCji3-4)

- [x]  Given when the user starts scheduling in VAOS and is in the VA request flow
When the user lands on the choose your reason for appointment page, does not enter a reason, and clicks `Continue`
Then the user will see an error message  `Provide more details about why you are requesting this appointment`
And page design matches the [design spec](https://www.figma.com/file/ewxCGm9dkvYt5wiNXMwvkL/Request-flow-content-update-%7C-Appointments-FE?type=design&node-id=607-22184&mode=design&t=nyMoz7Z4C7jyCji3-4)

- [x]  Given when the user starts scheduling in VAOS and is in the VA request flow
When the user lands on the choose where you would like to be seen page, does not select an appointment modality, and clicks `Continue`
Then the user will see an error message  `Select an option`
And page design matches the [design spec](https://www.figma.com/file/ewxCGm9dkvYt5wiNXMwvkL/Request-flow-content-update-%7C-Appointments-FE?type=design&node-id=607-22361&mode=design&t=nyMoz7Z4C7jyCji3-4)

- [x] Given when the user starts scheduling in VAOS and is in the VA request flow
When the user lands on contact information page 
Then the user will see a closed additional info component with the trigger:
  `How to update your information in your VA.gov profile`
Given the user clicks the trigger:
   > You can update your contact information for most of your benefits and services in your VA.gov profile.
Go to your VA.gov profile

  Where `Go to your VA.gov profile` is a link to the VA.gov profile contact information section (url https://va.gov/profile/contact-information)

  And page design matches the [design spec](https://www.figma.com/file/ewxCGm9dkvYt5wiNXMwvkL/Request-flow-content-update-%7C-Appointments-FE?type=design&node-id=607-22550&mode=design&t=nyMoz7Z4C7jyCji3-4)

- [x]  Given when the user starts scheduling in VAOS and is in the VA request flow
When the user lands on contact information page, does not enter a phone number, and clicks `Continue` 
Then the user will see an error message  `Enter a phone number`
And page design matches the [design spec](https://www.figma.com/file/ewxCGm9dkvYt5wiNXMwvkL/Request-flow-content-update-%7C-Appointments-FE?type=design&node-id=607-22550&mode=design&t=nyMoz7Z4C7jyCji3-4)

- [x]   Given when the user starts scheduling in VAOS and is in the VA request flow
When the user lands on contact information page, enters an invalid phone number, and clicks `Continue`
Then the user will see an error message  `Enter a valid 10-digit phone number (with or without dashes)`
And page design matches the [design spec](https://www.figma.com/file/ewxCGm9dkvYt5wiNXMwvkL/Request-flow-content-update-%7C-Appointments-FE?type=design&node-id=607-22550&mode=design&t=nyMoz7Z4C7jyCji3-4)

- [x] Given when the user starts scheduling in VAOS and is in the VA request flow
When the user lands on contact information page, does not enter an email address, and clicks `Continue`
Then the user will see an error message  `Enter an email address`
And page design matches the [design spec](https://www.figma.com/file/ewxCGm9dkvYt5wiNXMwvkL/Request-flow-content-update-%7C-Appointments-FE?type=design&node-id=607-22550&mode=design&t=nyMoz7Z4C7jyCji3-4)

- [x] Given when the user starts scheduling in VAOS and is in the VA request flow
When the user lands on contact information page, enters an invalid email address, and clicks `Continue`
Then the user will see an error message  `Enter a valid email address`
And page design matches the [design spec](https://www.figma.com/file/ewxCGm9dkvYt5wiNXMwvkL/Request-flow-content-update-%7C-Appointments-FE?type=design&node-id=607-22550&mode=design&t=nyMoz7Z4C7jyCji3-4)

- [x]  Given when the user starts scheduling in VAOS and is in the VA request flow
When the user lands on contact information page, enters an email address that exceeds the character limit, and clicks `Continue` 
Then the user will see an error message  `We don't support email addresses that exceed 50 characters`
And page design matches the [design spec](https://www.figma.com/file/ewxCGm9dkvYt5wiNXMwvkL/Request-flow-content-update-%7C-Appointments-FE?type=design&node-id=607-22550&mode=design&t=nyMoz7Z4C7jyCji3-4)

### Design Assets
[Figma File - VA and CC Request Flow](https://www.figma.com/file/ewxCGm9dkvYt5wiNXMwvkL/Request-flow-content-update-%7C-Appointments-FE?type=design&node-id=617-19228&mode=design&t=nyMoz7Z4C7jyCji3-4)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by ldelacosta** [comment]
No longer need a feature toggle `va_online_scheduling_request_flow_update` for this ticket cc: @JRRoof @simiadebowale

**Comment by ldelacosta** [comment]
@young1205 - please have the UX team validate this ticket when it's ready cc: @JRRoof @outerpress

**Comment by ldelacosta** [comment]
@outerpress - this is ready to be validated in staging.

**Comment by outerpress** [comment]
@vbahinwillit two small issues:

Page: What’s the reason for this appointment?
Error reads: `Provide more details about why you are requesting this appointment`
Change: "details" to "information"
Final error should read: `Provide more information about why you are requesting this appointment`

Page: How should we contact you?
Error reads: `We don't support email addresses that exceeds 50 characters`
Change: "exceeds" to "exceed"
Final error should read: `We don't support email addresses that exceed 50 characters`

Once that's done, this one is good to go. FYI @ldelacosta

**Comment by outerpress** [comment]
@vbahinwillit @ldelacosta see my previous comment - just need to change "details" to "information" and we're good to go

**Comment by ldelacosta** [comment]
All the changes have been validated. A new [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/79660) will cover the items that were not part of this work.
