### ISSUE TITLE
Access for Rachel Kauff

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-team#5247]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your name.
   > Rachel Kauff
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > UX Writer on the AgileSix cms team. I work for CivicActions.
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Internal%20Tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDTRUGpNROjaeFOV+rCdyDl0CWGQg4V1lrRwM2cr2uwPboXrw1wsjOnB9SSIPxI20XbLFRUHG11QCX+2TCEYN43aFEOka1zgc6gHvg6TDuZbKI6ok+nB2EPaOArRQ044xmiRfHki3/tj3uIvUC54Aep5CSGVfCg2X2NLi8iUsL418QKK03bML9vGR5a3cWqEaxPaprdWJXLfpIPYoC7rrBI23ylDOy4+bziXzSOMDwK21HXP9v4MHdi5NROog3cGWGKgVU+nBB2PMa56QBZsMy2jXb3+V4KSHz93CHk7218EphqTgjdUfG2s1kAgCtcwS5NMKuIFBSl9BlT0BN1m8Lb rachel.kauff@civicactions.com
```

- [Grant AWS Console access?]
  > NO
  >  Please give a brief description for why you are requesting AWS access.

**Comment by rachel-kauff** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by ricetj** [comment]
@Jeff-Hayter 
COR: Mary O'Toole
User: Rachel Kauff

**Comment by ricetj** [comment]
@rachel-kauff due to new changes in the process, SOCKS access is granted sooner. You should now refer to this [section](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) of the instructions to set up your SOCKS. Please also keep following up with your paperwork for the VA.
