### ISSUE TITLE
Analytics Implementation or QA Support for [Product]

### ISSUE THREAD

**Issue by Vato143** [department-of-veterans-affairs/va.gov-team#52474]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

</div>
</details>

### Required
- **Is this request for **Google Analytics implementation** or **QA**?**

     - [X] Google Analytics implementation
     - [ ] QA

- **Who is this request for?**

    - [OIT Appeals Product Line (APL) Stephanie.Salvato@va.gov]
    
    
- **Provide the link(s) for Google Analytics implementation or QA**
  
    - [Insert link(s)]
    
- **When is the launch date?**
    - [Insert launch date]

- **What interactions need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked_
    
    - [ https://www.va.gov/resources/how-to-check-your-va-claim-appeal-or-decision-review-status-online/
      The APL requests metrics on how many times Veterans view their Appeals Status on VA.gov.  The metric we are looking for is when someone clicks "View details" link under the "Higher-level review” (HLR), “Supplemental Claims” (SC), or “Appeals Modernization Act” (AMA).  ...." listed under the claim.  The Veteran can have one of those 3 types of Appeals.  We would need to know how many times they viewed the status of their Appeal of any of those 3 types. We need the metrics for one year, October 01, 2021 through September 30, 2022.  Please call or email if you need more details to understand the request. [Stephanie.Salvato@va.gov](mailto:Stephanie.Salvato@va.gov) (571) 274-5661.]
    
    - [Insert other interactions - please review the [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) and [GA Data Dictionary](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Google-Analytics-Data-Dictionary.1810464912.html)  to make sure these interactions aren't already tracked]

### Optional
- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - [Insert test user]

- **Any additional comments**

    - [Insert comments]

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by michelle-dooley** [comment]
Per our slack we do not track that level of detail and therefore cannot provide the requested metrics.
