### ISSUE TITLE
Community Care Request Flow - Alerts for invalid input/selection and confirmation

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#52480]
## Description
In VAOS, the user has the ability to schedule an appointment or submit a request for an appointment. In the request flow, the Veteran may think they are scheduling an appointment but they are submitting a request for an appointment. When requesting for an appointment, the Veteran does not have a confirmed appointment until the staff schedules an appointment on their behalf.

We will be updating the alerts for invalid input/selection in the CC request flow. No changes for the direct scheduling workflow. VA request flow will be worked on in ticket [#52465](https://github.com/department-of-veterans-affairs/va.gov-team/issues/52465)

---

## Acceptance Criteria

- [x] Given when the user starts scheduling in VAOS and is in the Community Care request flow
When the user lands on the date selection page, does not select a date and clicks `Continue`
Then the user will see an error message `Select at least 1 preferred timeframe for your appointment` 
And page design matches the [design spec](https://www.figma.com/file/ewxCGm9dkvYt5wiNXMwvkL/Request-flow-content-update-%7C-Appointments-FE?type=design&node-id=636-9554&mode=design&t=nyMoz7Z4C7jyCji3-4)

- [x]  Given when the user starts scheduling in VAOS and is in the Community Care request flow
When the user lands on the closest city page
Then the user will see a closed additional info component with the trigger: `Why we’re asking this`
When the user clicks the trigger, the component content is:
   > We'll send your request to the VA medical center nearest to the city you select. The medical center staff will help schedule your community care appointment.
  
   And page design matches the [design spec](https://www.figma.com/file/ewxCGm9dkvYt5wiNXMwvkL/Request-flow-content-update-%7C-Appointments-FE?type=design&node-id=619-19192&mode=design&t=nyMoz7Z4C7jyCji3-4)

- [x] Given when the user starts scheduling in VAOS and is in the Community Care request flow
When the user lands on the select the closest city page, does not select a city and clicks `Continue`
Then the user will see an error message `Select a city` 
And page design matches the [design spec](https://www.figma.com/file/ewxCGm9dkvYt5wiNXMwvkL/Request-flow-content-update-%7C-Appointments-FE?type=design&node-id=619-19192&mode=design&t=nyMoz7Z4C7jyCji3-4)

- [x]  Given when the user starts scheduling in VAOS and is in the Community Care request flow
When the user lands on the provider page
Then the user will see a closed additional info component with the trigger: `What happens if you skip this step`
When the user clicks the trigger, the component content is:
   > We’ll choose the provider nearest to you who is available closest to your preferred time.

   And page design matches the [design spec](https://www.figma.com/file/ewxCGm9dkvYt5wiNXMwvkL/Request-flow-content-update-%7C-Appointments-FE?type=design&node-id=619-19376&mode=design&t=nyMoz7Z4C7jyCji3-4)

- [x] Given when the user starts scheduling in VAOS and is in the Community Care request flow
When the user lands on the provider page and searches for a provider based on their home address
Then the user will see the updated page content `[Type of care] Providers`
   > Show providers nearest to this location:

   And page design matches the [design spec](https://www.figma.com/file/ewxCGm9dkvYt5wiNXMwvkL/Request-flow-content-update-%7C-Appointments-FE?type=design&node-id=619-19556&mode=design&t=nyMoz7Z4C7jyCji3-4)

- [x] Given when the user starts scheduling in VAOS and is in the Community Care request flow
When the user lands on the provider page and searches for a provider based on their nearest city
And the user does not have a home address on file
Then the user will see the updated page content `[Type of care] Providers`
   > Show providers nearest to this location: 

   And below the selection box, display a description note to the user 
      
    > **Note:** To show providers near your home, you need to add your home address to your VA.gov profile.  Go to your VA.gov profile

    Where `Go to your VA.gov profile` is a link to the VA.gov profile contact information section (url https://va.gov/profile/contact-information)

   And page design matches the [design spec](https://www.figma.com/file/ewxCGm9dkvYt5wiNXMwvkL/Request-flow-content-update-%7C-Appointments-FE?type=design&node-id=726-13687&mode=design&t=nyMoz7Z4C7jyCji3-4)

- [x] Given when the user starts scheduling in VAOS and is in the Community Care request flow
When the user lands on the provider page, chooses the provider and clicks the button `Select provider`
Then the user will see the updated page displaying the `Preferred provider`
And page design matches the [design spec](https://www.figma.com/file/ewxCGm9dkvYt5wiNXMwvkL/Request-flow-content-update-%7C-Appointments-FE?type=design&node-id=619-19884&mode=design&t=nyMoz7Z4C7jyCji3-4)

- [x] Given when the user starts scheduling in VAOS and is in the Community Care request flow
When the user lands on the updated page displaying the `Preferred provider` and the user clicks Remove
Then the user will see a pop-up message `Remove this provider?`
    > We'll remove [Provider name] as your preferred provider for this appointment request. 

   And page design matches the [design spec](https://www.figma.com/file/ewxCGm9dkvYt5wiNXMwvkL/Request-flow-content-update-%7C-Appointments-FE?type=design&node-id=780-14359&mode=design&t=nyMoz7Z4C7jyCji3-4)

- [x]  Given when the user starts scheduling in VAOS and is in the Community Care request flow
When the user lands on the choose the preferred language page, does not select a language and clicks `Continue`
Then the user will see an error message `Select a language` 
And page design matches the [design spec](https://www.figma.com/file/ewxCGm9dkvYt5wiNXMwvkL/Request-flow-content-update-%7C-Appointments-FE?type=design&node-id=619-20069&mode=design&t=nyMoz7Z4C7jyCji3-4)

- [x] Given when the user starts scheduling in VAOS and is in the Community Care request flow
When the user lands on contact information page 
Then the user will see a closed additional info component with the trigger:
  `How to update your information in your VA.gov profile`
When the user clicks the trigger the content is:
   > You can update your contact information for most of your benefits and services in your VA.gov profile.
Go to your VA.gov profile

  Where `Go to your VA.gov profile` is a link to the VA.gov profile contact information section (url https://va.gov/profile/contact-information)
And page design matches the [design spec](https://www.figma.com/file/ewxCGm9dkvYt5wiNXMwvkL/Request-flow-content-update-%7C-Appointments-FE?type=design&node-id=619-20525&mode=design&t=nyMoz7Z4C7jyCji3-4)

- [x]   Given when the user starts scheduling in VAOS and is in the Community Care request flow
When the user lands on contact information page, does not enter a phone number, and clicks `Continue`
Then the user will see an error message  `Enter a phone number`
And page design matches the [design spec](https://www.figma.com/file/ewxCGm9dkvYt5wiNXMwvkL/Request-flow-content-update-%7C-Appointments-FE?type=design&node-id=619-20525&mode=design&t=nyMoz7Z4C7jyCji3-4)

- [x]   Given when the user starts scheduling in VAOS and is in the Community Care request flow
When the user lands on contact information page, enters an invalid phone number, and clicks `Continue` 
Then the user will see an error message  `Enter a valid 10-digit phone number (with or without dashes)`
And page design matches the [design spec](https://www.figma.com/file/ewxCGm9dkvYt5wiNXMwvkL/Request-flow-content-update-%7C-Appointments-FE?type=design&node-id=619-20525&mode=design&t=nyMoz7Z4C7jyCji3-4)

- [x]  Given when the user starts scheduling in VAOS and is in the Community Care request flow
When the user lands on contact information page, does not enter an email address, and clicks `Continue`
Then the user will see an error message  `Enter an email address`
And page design matches the [design spec](https://www.figma.com/file/ewxCGm9dkvYt5wiNXMwvkL/Request-flow-content-update-%7C-Appointments-FE?type=design&node-id=619-20525&mode=design&t=nyMoz7Z4C7jyCji3-4)

- [x]  Given when the user starts scheduling in VAOS and is in the Community Care request flow
When the user lands on contact information page, enters an invalid email address, and clicks `Continue`
Then the user will see an error message  `Enter a valid email address`
And page design matches the [design spec](https://www.figma.com/file/ewxCGm9dkvYt5wiNXMwvkL/Request-flow-content-update-%7C-Appointments-FE?type=design&node-id=619-20525&mode=design&t=nyMoz7Z4C7jyCji3-4)

- [x]  Given when the user starts scheduling in VAOS and is in the Community Care request flow
When the user lands on contact information page, enters an email address that exceeds the character limit, and clicks `Continue`
Then the user will see an error message  `We don't support email addresses that exceed 50 characters`
And page design matches the [design spec](https://www.figma.com/file/ewxCGm9dkvYt5wiNXMwvkL/Request-flow-content-update-%7C-Appointments-FE?type=design&node-id=619-20525&mode=design&t=nyMoz7Z4C7jyCji3-4)

### Design Assets
[Figma File - VA and CC Request Flow](https://www.figma.com/file/ewxCGm9dkvYt5wiNXMwvkL/Request-flow-content-update-%7C-Appointments-FE?type=design&node-id=619-19190&mode=design&t=nyMoz7Z4C7jyCji3-4)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by ldelacosta** [comment]
No longer need a feature toggle `va_online_scheduling_request_flow_update` for this ticket cc: @JRRoof @simiadebowale

**Comment by ldelacosta** [comment]
@young1205 - please have the UX team validate this ticket when it's ready cc: @JRRoof @outerpress

**Comment by ldelacosta** [comment]
Validated the changes in staging. UX team will review.

**Comment by outerpress** [comment]
@vbahinwillit a few small changes for this one:

Page: How should we contact you?
Error reads: `We don't support email addresses that exceeds 50 characters`
Change: "exceeds" to "exceed"
Final error should read: `We don't support email addresses that exceed 50 characters`

Page: Which provider do you prefer?
Content:
 <img width="1318" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNi8vQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f38a521d603ddccdfff597933ba6c829acee9470/Screenshot%202024-03-21%20at%203.20.13%E2%80%AFPM.png" alt="Screenshot 2024-03-21 at 3.20.13 PM.png" />
Change 1: Add strong/bold formatting to "Note:"
Change 2: The link to the profile should drop to a new line.

This one's good to go after that - FYI @ldelacosta

**Comment by vbahinwillit** [comment]
Content update per Slack:

Peter Russo
:spiral_calendar_pad:  [6 hours ago](https://dsva.slack.com/archives/D01E9JGTZ0X/p1711116803840159?thread_ts=1711115050.304259&cid=D01E9JGTZ0X)
If so, yep it should be the same except say "locations" instead of "providers", i.e. : "Note: To show locations near your home, you need to add your home address to your VA profile."

**Comment by outerpress** [comment]
@vbahinwillit I just retested, looks good to me! FYI @ldelacosta

**Comment by ldelacosta** [comment]
All the changes have been validated. A new [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/79660) will cover the items that were not part of this work.
