### ISSUE TITLE
Styling Issues

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#52497]
## Styling Issues

Desktop widths:
- Back link does not align with rest of content
- Translation links shifting to the right side of the screen

Mobile width:
- Vertical spacing is incorrect between back link and translation links

**Comment by wullaski** [comment]
@loripusey I'm going to remove this from the Accessibility Improvements epic. This is just a FE bug and not really accessibility related. I'm going to add it to the current sprint too since it should probably get fixed before the new simplified header footer go live.

**Comment by wullaski** [comment]
Couldn't reproduce this. Closing it out.
