### ISSUE TITLE
Enable pg_stat_statements for GIDS RDS

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#5249]
Enable [pg_stat_statements](https://www.postgresql.org/docs/9.6/pgstatstatements.html) so that we can better understand usage and performance issues. Note: would require a postgresql restart.

We don't intent to use pganalyze at this time, but [this set of instructions](https://pganalyze.com/docs/install/amazon_rds/01_configure_rds_instance) looks helpful.

**Comment by gunsch** [comment]
cc @wyattwalter @jbritt1

**Comment by jbritt1** [comment]
@annaswims did you want this enabled on vets-api databases as well? Or is this only necessary for GIDS RDS at this time?

**Comment by annaswims** [comment]
Just closing the loop on slack conversation... `vets-api` would be nice to have too, but the GIDS db is where we're more actively investigating issues now.  We recently added NewRelic to GIDS so this is less necessary (but still could be useful).

**Comment by annaswims** [comment]
💃🏼 I saw that  pg_stat_statements  is enabled for vets-api and it turns out it's quite useful.  I learned that the query that takes the most time it he db is a simple select that is improperly indexed.

**Comment by ricetj** [comment]
Done
