### ISSUE TITLE
Create site-wide feature flag for the Medallia Feedback button

### ISSUE THREAD

**Issue by aubreyarcangel** [department-of-veterans-affairs/va.gov-team#52508]
## User Story

As a user I would like to have a site-wide feature flag for the Medallia feedback button because it would allow me the ability to quickly remove or read the feedback button across VA.gov 

## Expected Behavior

Toggles Medallia Feedback button site-wide

## Acceptance Criteria

- [ ] Feedback button is not visible when feature flag is on
- [ ] Feedback button is visible when feature flag is off
- [ ] Feedback button launches correct survey when visible

**Comment by ATMiddleton** [comment]
@aubreyarcangel - met with Ian and will continue to research and make progress.

**Comment by aubreyarcangel** [comment]
Even though many [VA.gov feature flags use Flipper UI](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles) I decided that wasn't necessary for this solution and can easily be managed within the liquid template control flow.

[PR for this work](https://github.com/department-of-veterans-affairs/content-build/pull/1472)

**Comment by ATMiddleton** [comment]
@aubreyarcangel  - actively working through a bug.
