### ISSUE TITLE
AWS access for Riley Anderson

### ISSUE THREAD

**Issue by rileyanderson** [department-of-veterans-affairs/va.gov-team#52516]
### COR Name

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Riley Anderson

### Your Email

riley.anderson@oddball.io

### Team, Role, and Company of the target individual

Identity Surge, Backend Engineer, Oddball

### Product Manager (PM) name and email

Mike King - mike.king@oddball.io

### Product Owner (PO) name and email

John Rahaghi - john.rahaghi@va.gov

### Desired AWS Access

I need AWS access identical to the `vsp-identity` team (e.g. Trevor Bosaw) 

### Access Expiration

ongoing

### Additional Notes

COR: Delano McVay - delano.mcvay@va.gov

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by little-oddball** [comment]
VFS Team

**Comment by little-oddball** [comment]
@rileyanderson - I am hopping in to try and help w/ these items. Our Gov't PO had a transition and we now require to have the eQIP transmittal date provided. Would you be able to work with your PO/PM to provide that? Once that has been applied to the ticket I push move it forward to our Gov't PO for a review/approval. Thanks and sorry for the delay and any inconvenience.

**Comment by rileyanderson** [comment]
> @rileyanderson - I am hopping in to try and help w/ these items. Our Gov't PO had a transition and we now require to have the eQIP transmittal date provided. Would you be able to work with your PO/PM to provide that? Once that has been applied to the ticket I push move it forward to our Gov't PO for a review/approval. Thanks and sorry for the delay and any inconvenience.

@little-oddball Thanks for the update! I previously completed the eQUIP when I was on the VSP contract and I believe that should still be valid. The transmittal date I have for that is April 5, 2021. Let me know if that will work or if I need to wait for something else.

**Comment by little-oddball** [comment]
@BillChapmanUSDS - Are there other items needed for this to be approved?

**Comment by BillChapmanUSDS** [comment]
I approve this access.

**Comment by oseasmoran73** [comment]
@rileyanderson While I understand `prod` is required (especially seeing the work y'all do), to ensure proper procedure is followed, I reached out to @BillChapmanUSDS to approve `prod` access as it was not explicitly mentioned.
