### ISSUE TITLE
AWS access for Daniel Cloud

### ISSUE THREAD

**Issue by dcloud** [department-of-veterans-affairs/va.gov-team#52511]
### COR Name

Crystal Moultrie

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### E-QIP Transmittal Date

- [x] Check this box if you have an E-QIP transmittal date.

### Your Name

Daniel Cloud

### Your Email

daniel.cloud@adhocteam.us

### Team, Role, and Company of the target individual

Health Apartment, Engineer, Ad Hoc LLC

### Product Manager (PM) name and email

Marci McGuire, marci.mcguire@adhocteam.us

### Product Owner (PO) name and email

Leila Rassi, Leila.Rassi@va.gov

### Desired AWS Access

I need SSM Access to lower environment instances. The specific IAM policy needed is "SSMApplicationLowerEnvironmentAccess", which can be granted via membership in the "dsva-vfs-developers" group.

### Access Expiration

1/1/2024

### Additional Notes

I need this access because I am working on the MHV to Va.gov project and need to be able to [tunnel to MHV APIs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/engineering/mhv-api-tunnel-setup.md).

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by dcloud** [comment]
I'm not sure about the eQIP transmittal date – I completed eQIP years ago for another agency.

I am on the VFS roster under a different team, but am tasked to help HMI/Health Apartment when Eric Voshall goes on leave.

**Comment by little-oddball** [comment]
@MarciMcGuire - Would you be able to verify eQIP for Daniel? Thank you!

**Comment by MarciMcGuire** [comment]
@little-oddball I'm a Product Manager and don't have access to any personnel info.  Daniel's manager may be able to that.

**Comment by little-oddball** [comment]
@MarciMcGuire Thanks, I don't know who his manager is. @dcloud - Please reference someone on your end that would be able to provide / verify your eQIP date. This is something required by OCTODE prior to giving AWS type permissions.

**Comment by dcloud** [comment]
@little-oddball: Per the Personnel Security Specialist at our prime:

> We received confirmation of you having a “previous investigation that meets or exceeds the current request” on **04/21/2022**.

Please let me know if that works.

**Comment by little-oddball** [comment]
Gonna give it a whirl

**Comment by little-oddball** [comment]
VFS Team Member

**Comment by dcloud** [comment]
@little-oddball Checking in. Are there any blockers, or perhaps some action I need to take to move this forward?

**Comment by dcloud** [comment]
While I'm here, linking the support ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/53156

**Comment by little-oddball** [comment]
@dcloud - Waiting on OCOTDE approval.

**Comment by BillChapmanUSDS** [comment]
I approve this access.

**Comment by dcloud** [comment]
@little-oddball What is the status of this request, please?
