### ISSUE TITLE
Accessibility Testing for [Check-in Experience, Check-in Experience, Simplified Header and Footer]

### ISSUE THREAD

**Issue by wullaski** [department-of-veterans-affairs/va.gov-team#52512]
### Product information

https://depo-platform-documentation.scrollhelp.site/developer-docs/accessibility-defect-severity-rubric

- [X] Team name, product name, and feature name have been added to the title of this issue.
- [X] Team label, product label and feature label (if applicable) have been added to this issue.

### Who completed the use of color and color contrast test?

@wullaski

### Use of color and color contrast checks

- [X] All text of 20px or smaller has a 4.5:1 contrast ratio to its background (or better)
- [X] All text of 20px or larger has a 3:1 contrast ratio to its background (or better)
- [X] Non-text elements have a 3:1  contrast ratio to their background and to neighboring elements (or better)
- [X] Color is not the only way to distinguish links from other text (eg. links are underlined)
- [X] Any charts, maps, infographics, and tables convey all information without only relying on color
- [X] Content does not refer to color, especially when providing user instructions (eg. "Click the blue button")

### How did color testing go?

- Focus styles will not meet the new 3:1 contrast ratio outlined in [WCAG 2.2](https://www.sarasoueidan.com/blog/focus-indicators/#new-focus-indicator-accessibility-requirements-in-wcag-2.2). 

### Who completed the axe scans?

@wullaski

### axe checks

- [X] Each page has been scanned using axe (results shared below)
- [X] axe is integrated into your end-to-end testing

### axe DevTools scan results

**False positive** color contrast issues detected 
- overlapping elements: body has a 100% height and overflow hidden on it
![Screen Shot 2023-01-25 at 8 52 08 AM](https://user-images.githubusercontent.com/2982977/214586996-05a4ed14-c799-4a4a-99aa-3d7475a13df7.png)
- background images on the accordion
![Screen Shot 2023-01-25 at 9 18 09 AM](https://user-images.githubusercontent.com/2982977/214587386-0957acb9-e530-4fd1-951c-202fddce56d9.png)

### How did axe testing go?

- [Fixed](https://github.com/department-of-veterans-affairs/va.gov-team/issues/51894) aria-describedby on [demographics display](http://fb317e98ddfef98bee03cab1cd5a3384.review.vetsgov-internal/health-care/appointment-check-in/contact-information)

### Who completed the content zoom and reflow test?

@wullaski

### Content zoom and reflow checks

- [X] All page elements are readable and usable at 200% zoom
- [X] All page elements are readable and usable at 300% zoom
- [X] All page elements are readable and usable at 400% zoom

### Who completed the keyboard navigation test?

@wullaski

### Keyboard navigation checks

- [X] Each link, button, form input, checkbox, radio button, select menu, and custom element can receive keyboard focus
- [X] Each link, button, form input, checkbox, radio button, select menu, and custom element responds to expected keys
- [X] All elements under focus have a visible focus indicator
- [X] The order of [Tab] stops made sense and was appropriate for completing tasks

### How did keyboard testing go?

Focus style on logo in the footer should contain the entire logo 
![Screen Shot 2023-01-25 at 9 20 38 AM](https://user-images.githubusercontent.com/2982977/214588052-8f26a4a7-1bb1-40e9-ad6c-023418ba6493.png)

### Do you have any other results to share?

**WAVE Spot Checks**

Wave Spot check pointed out flaw with functional links such as the language picker.

![Screen Shot 2023-01-18 at 4 17 54 PM](https://user-images.githubusercontent.com/2982977/213783190-73545f9c-3e43-4cff-9a9e-652bc5c77fd5.png)

Created issue to address:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/52360

**Code quality review**
Name doesn't match the name attribute on the input. The name attribute is `last-name` and the label is Your last name.

Role on the warning alert is `role="presentation"` which doesn't get read by Voice Over like the Error on validation.
![Screen Shot 2023-01-23 at 2 28 32 PM](https://user-images.githubusercontent.com/2982977/214132157-3659029e-7689-49e2-872c-7d47d3232596.png)

**Mouse only and touchscreen**

Touch target on the language picker and other links that are outside of a block of content are not 44px high. Including the call to action for starting pre check in.

**Screen Readers**

Voice Over Testing pointed out a repetition issue with the loading component from the design system and the way it was implemented by the application.

Created an issue for the design system team
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1457

Created an issue for the Check In Experience team
https://github.com/department-of-veterans-affairs/va.gov-team/issues/52509

It also pointed out an issue with the hint text for the DOB input it doesn't mention the day field which also requires two digits

Created an issue with the design system team
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1455

**Comment by briandeconinck** [comment]
Just wanted to comment here that I appreciate how thorough your testing was @wullaski!
