### ISSUE TITLE
Move site maps to Mural - Disability

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#52527]

**Comment by kristinoletmuskat** [comment]
Mural is here: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1667839622293/c8919d112d2d28d29080bf70cdc67998ef98e8aa?sender=ua67f17f1c416a96ea04d2476

**Comment by kristinoletmuskat** [comment]
- [ ] Moqups Migration
- [ ] VA.gov cross-reference
- [ ] Review journey map
- [ ] Jenny Reviewed

**Comment by mnorthuis** [comment]
duplicate of #52723
