### ISSUE TITLE
Support Bot requests with type security create ticket in sensitive repos

### ISSUE THREAD

**Issue by little-oddball** [department-of-veterans-affairs/va.gov-team#52544]
## User Story
The Support Bot currently creates issue tickets for many of the requests it handles. The valid concern has been raised around requests that may be sensitive in nature (NOTE: For a bigger approach solution there is [this](https://github.com/department-of-veterans-affairs/va.gov-team/issues/52505) ticket). The purpose of this ticket is to specifically handle items that are marked with the type **security** and the assumption those items are most likely sensitive in nature.

---

## Acceptance Criteria
- [x] Support bot requests with type security have their issues created in the sensitive repos (va.gov-team-sensitive)
- [x] Other issue creation works as expected for the. other types

**Comment by npeterson54** [comment]
This will not be completed before Harshil moves to his new team, removing it from sprint.
