### ISSUE TITLE
"no Sidekiq processes running" alert needs to ALERT

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#52558]
## Description
The alert "`[Prod] [Sidekiq] There are no Sidekiq processes running`" needs immediate attention when it's triggered. The current alerting rules, defined in [datadog/catalog/sidekiq.yaml](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/datadog/catalog/sidekiq.yaml#L8), are to post in #oncall and #console-services-notifications. According to [this Confluence doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2399371542/Support+-+Tier+1+and+Tier+2+Flow#Support%3A), the Tech Support Team should be monitoring #oncall, but that doesn't seem to be happening with the consistency needed for urgent alerts.

If this alert also routed to PagerDuty, that would be helpful during non-business hours, but that wouldn't change anything during business hours since no one is on-call (in pd) during business hours.

## Background/context 
This issue is an action item from the Postmortem
* https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/689

---
## Tasks
- [ ] Do discovery on best way to get this alert the attention it deserves when it triggers. Possibly talk to Clint about re-configuring pd to alert during the day. Or about who should be monitoring #oncall.
- [ ] implement fixes

## Acceptance Criteria 
- [ ] "no Sidekiq processes running" alert is LOUD

**Comment by rmtolmach** [comment]
This alert is also being modified as part of:
* https://github.com/department-of-veterans-affairs/va.gov-team/issues/54209

**Comment by oseasmoran73** [comment]
This comes down ultimately from a process standpoint. If notification and alerts want to be done during on-hours and off-hours, it needs to be clearly defined, which the current one does not seem to be working smoothly as things are falling through the cracks.

We can create alerts for @support_team and @pd_notification, but that seems very cluttered and redundant in my opinion. The assumption is that users will have `snooze` notification off during the night via Slack, otherwise they will also be pinged

**Comment by laineymajor** [comment]
Need discovery. This is potentially complete. @RachalCassity to complete discovery to determine if this is/is not complete.

**Comment by RachalCassity** [comment]
https://vagov.ddog-gov.com/monitors/116481

**Comment by LindseySaari** [comment]
This is complete. Closing this out.

**Comment by rmtolmach** [comment]
Alerting (paging) added in https://github.com/department-of-veterans-affairs/devops/pull/13912. In the meantime since this was opened one year ago _exactly_ 😻 pager duty was reconfigured so people are paged during the day, so if no sidekiq processes are running in prod, incident commander and then BE on-call is paged.
