### ISSUE TITLE
Staging: 404 Errors Throughout VAOS Application

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#52564]
Steps to recreate:  log in.

Expected response.  No errors

Actual response:  Errors display in dev tools.  

 Thomas Joyner:   I tested fetching appointments for cecil.morgan, patientten, brienne.b.ferrara, and cathedris mitulisk and they all return data as expected. I also didn’t see any exceptions or errors in the vaos-service logs, so I agree with Brad and think something is squirrelly in VetsApi or on the FE

Several patients with same errors:  john.morrison@id.me, cathedris.l.mitulski@id.me, brienne.b.ferrara@id.me

![image.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/5f21dcc1-feae-4b94-a9cc-234db94010ff)
![image.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/461f136a-ccbb-4edc-b347-be0e1b477cb5)
![image.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/e64f2f6e-5c57-43c7-9218-702167acfce4)

**Comment by ryanshaw** [comment]
@marcynadeau This was related to a CORS issue, not specifically with the frontend code. It appears to be working again. If you can verify when you have the chance, that'd be great.

**Comment by ymunipalli** [comment]
@ryanshaw still getting 404 errors in Staging throughout the appointment request process. Been getting them all morning.

**Comment by ymunipalli** [comment]
The errors are not just in fetching appointments. They are coming in at multiple points during the appointment request process. I think this is a wider problem than what Marcy has written.

**Comment by ryanshaw** [comment]
Hi @ymunipalli, can you verify whether or not you are getting CORS errors (that lead to the 404)?

![image](https://user-images.githubusercontent.com/587812/214903170-f2f817b2-5408-495e-9f86-7a6d95f668f4.png)

**Comment by ryanshaw** [comment]
@ymunipalli @ldelacosta I've posted a question about this in the platform support channel. I will update as I find out more.

**Comment by marcynadeau** [comment]
@ryanshaw This is still an issue. We posted screenshots in Slack.

**Comment by marcynadeau** [comment]
FYI,......so everyone is aware this issue in staging is a blocker issue and is blocking our testing. We have a deadline to get things tested as VIA is being shutdown and we have to move to Acheron. So this issue needs immediate attention and everyone needs to understand that it is a critical/blocker issue. (edited)

**Comment by marcynadeau** [comment]
The issues in Staging with 404's is still occurring. This from the Front End Platform Support Team:
We are still seeing some CORs related errors in staging. The team is planning to tackle this today as a top priority.  We've narrowed it down to CORs issues within traefik (the EKS ingress controller) for awareness

**Comment by marcynadeau** [comment]
@ldelacosta @JRRoof This ticket can be closed as the issue is fixed.
