### ISSUE TITLE
Voicebot support: copyedit intro, welcome and goodbye content

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#52576]
## Issue Description

We need to do a copyedit of the NCC intro, welcome, and goodbye content for the Voicebot team. We should be using the spreadsheet in the sharepoint file.

## Tasks
- [x] Copyedit (Megan)
- [x] Notify Voicebot team when ready (Megan)

## Acceptance Criteria
- [x] Voicebot team has final content for intro, welcome and goodbye

**Comment by megzehn** [comment]
This content is reviewed, and I let Grace know. OK to close, @RLHecht! Thanks.

**Comment by RLHecht** [comment]
Thanks! Closing this out.
