### ISSUE TITLE
[EKS Testing] [DEV] Notice of Disagreement

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#52600]
In order to ensure consistent and correct behavior after the migration to EKS, we need to verify that the endpoints of this application are working as expected.

Be on the look out for errors that have to do with connectivity:
- Status Codes
  - 403: Forbidden * Check that a test user is signed in before marking as broken
  - 404: Not found * Check that the path is correct before marking as broken
  - 500: Internal Server Error
  - 502: Bad Gateway
  - 503: Service Unavailable
  - 504: Gateway Timeout
- General Errors
  - ERR_TOO_MANY_REDIRECTS: Redirect loop
  - Others?

Resources:
- [Testing Guidance](https://depo-platform-documentation.scrollhelp.site/developer-docs/eks-endpoint-testing)
- [Testable Endpoint Collection](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/teams/vsa/teams/benefits-memorials/endpoints)

AC:
- [x] The following endpoints return the results expected.
  - [x] POST	/v0/notice_of_disagreements
  - [ ] GET	/v0/notice_of_disagreements/* (We don't actually use this endpoint)
  - [x] GET	/v0/notice_of_disagreements/contestable_issues
  - [x] POST	/v0/decision_review_evidence (Works on staging, [but not dev](http://sentry.vfs.va.gov/organizations/vsp/issues/185499/?environment=development&project=3&query=is%3Aunresolved&statsPeriod=1h). Given it works on staging, does it really matter that it doesn't work on dev? Error on dev is a timeout on `validate_pdf_with_lighthouse` by the way).
- [x] A spot check of the application works as expected OR recorded TestRail tests pass

**Comment by data-doge** [comment]
Testing done. See checkboxes above. @kjduensing can you see my comment in parenthesis on `POST /v0/decision_review_evidence` above? What do you think?

**Comment by kjduensing** [comment]
Yeah good question. [We took the same approach in this ticket](https://app.zenhub.com/workspaces/benefits-team-1-6138d7b57a2631001a4b7562/issues/gh/department-of-veterans-affairs/va.gov-team/52322), figuring that if staging works we should be good. I'm not saying it will NEVER come back to bite us, but chances are low :)
