### ISSUE TITLE
Contact Center Review for Mobile Flagship App - RX Refill

### ISSUE THREAD

**Issue by MekoHong** [department-of-veterans-affairs/va.gov-team#52616]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
*Please provide the name(s) of your product and a high-level description of your product.*

New functionality in the VA Benefits & Health mobile app:  VA Prescription Refills 

Veterans will be able to manage their VA prescriptions.  This includes requesting refills and tracking delivery.

A few areas to note:

The initial rollout of this feature on the mobile app, Veteran's will not see some information that is displayed on the web such as

- Non-VA meds
- Dispensed on date in the prescription details (this enhancement will be added in a future release)

### Launch Date
*Please provide the launch or rollout date and details.*

Target roll out to 10% of Veterans starting 1/31/23.  With an incremental rollout of

2/7 - 25%
2/9 - 75%
2/13 - 100%

this rollout plan will be dependent on successful monitoring and no major issues.

### Version Number
*Please provide the version number of the guide and/or video.*

V5.0

### Product Guide
*Please provide product guide link*

[VA Mobile App Product Guide 5.0 (2).docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/10522660/VA.Mobile.App.Product.Guide.5.0.2.docx)

### Product Video
*Please provide product video link*

### Product Video Transcript
*Please provide product video transcript link*

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
Contacted @MekoHong re. having a Word draft attached for inline review.

**Comment by starlow00** [comment]
Hi @MekoHong. Attached is the latest draft, ready for Login.gov screenshots as we discussed. Once they're in, reattach and I will send to VEO. Thanks!
[VA.Mobile.App.Product.Guide.5.0_srt.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/10521544/VA.Mobile.App.Product.Guide.5.0_srt.docx)

**Comment by starlow00** [comment]
Sent to VEO for review

**Comment by starlow00** [comment]
No changes from VEO. Draft attached.
[VA.Mobile.Health.Benefits.app.v5.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/10574123/VA.Mobile.Health.Benefits.app.v5.docx)
