### ISSUE TITLE
Acquire existing Mappings and Workflows from current project teams, and current fixed teams

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#52625]
## Purpose
Aggregate mappings for future organization.

Question:  should we make it part of the Platform Initiative to pass along any visual mappings/workflows to the SDT upon a project's completion?

## Tasks
Contact Project teams for any existing mappings of processes/services or workflows:
- [x] Tech Team 1
- [x] Tech Team 2
- [x] Tech Team 3
- [x] Tech Team 4

Contact Fixed teams for any existing mappings of processes/services or workflows
- [x] Platform Content
- [x] Design Systems
- [x] Governance

## Acceptance Criteria
- [x] Asks and correspondence completed

**Comment by twoangstroms** [comment]
@steel36 Good work. Is there one place where these are all collected?

**Comment by steel36** [comment]
@twoangstroms This will be the holding area:  https://vfs.atlassian.net/wiki/spaces/SDT/pages/2503049234/Aggregation+and+Publishing+of+platform-produced+mappings+and+workflows

**Comment by twoangstroms** [comment]
Great, thanks!


Dan Turner

Sr. UX Designer II, Ad Hoc
***@***.***

￼
