### ISSUE TITLE
[BE] | Profile | Local/Mocked Data | Discovery: Investigate Vets-api local 500 and other errors

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/va.gov-team#52628]
## Background

When running the vets-api locally there are errors being returned from api calls for profile.

#### Steps to reproduce:

- Run Vets-api locally via docker or natively (Adam ended up setting it up natively to get a better idea of the codebase in general)
- Run vets-website locally with `yarn watch`
- Navigate to localhost:3001/profile and log in with a testing user (vets.gov.user+228@gmail.com was used for initial investigation)
- Open network tab of the browser devtools and inspect network errors on specific endpoints

#### Endpoints that were failing (all 500 status code)
- `v0/profile/personal_information`
    - via`vets-api/lib/va_profile/demographics/service.rb:37`
-  `v0/profile/service_history`
    -  via `vets-api/lib/va_profile/military_personnel/service.rb:41`
- `v0/profile/ch33_bank_account`
    - via `vets-api/lib/bgs/service.rb`
- In addition to these 500 errors there is also error meta data present on the `v0/user` endpoint (status is 296 Custom) that contains this error data:

```
 {
    "externalService": "Vet360",
    "startTime": "2023-01-30T19:20:40Z",
    "endTime": null,
    "description": "Breakers::OutageException, Outage detected on VAProfile/ContactInformation beginning at 1675106435, Breakers::OutageException",
    "status": 503
}
```

## Tasks
- [x] Investigate running vets-api and FE locally to identify why some endpoints are now failing

## Acceptance Criteria
- [ ] Create tickets for endpoints that need to be fixed.

**Comment by tpharrison** [comment]
This ticket is related to configuring and updating [vets-api-mockdata](https://github.com/department-of-veterans-affairs/vets-api-mockdata) and ticket #54238 (https://github.com/department-of-veterans-affairs/va.gov-team/issues/54238).

**Comment by tpharrison** [comment]
I have things running locally and the reason the above endpoints are returning 500 errors is because mocked responses have not been configured for this user (or other users).

I need to work with the mock repository a bit more to understand how everything is wired up and will work that unders ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/54238.
