### ISSUE TITLE
AWS access for Melissa Miller

### ISSUE THREAD

**Issue by holytoastr** [department-of-veterans-affairs/va.gov-team#52620]
### COR Name

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative Name

Other - please specify in 'Additional Notes'

### E-QIP Transmittal Date

- [x] Check this box if you have an E-QIP transmittal date.

### Your Name

Melissa Miller

### Your Email

mmiller@pluribusdigital.com

### Team, Role, and Company of the target individual

Identity Team, Full Stack Engineer, Pluribus Digital

### Product Manager (PM) name and email

Elizabeth Koch, elizabeth@bluetiger.digital

### Product Owner (PO) name and email

John Rahaghi, john.rahaghi@va.gov

### Desired AWS Access

AWS Shell Access (https://depo-platform-documentation.scrollhelp.site/developer-docs/aws-shell-access)

### Access Expiration

09/01/2023

### Additional Notes

COR - Johnathan W. Ivey ([JOHNATHAN.IVEY@va.gov](mailto:JOHNATHAN.IVEY@va.gov))
VOR - Yvonne Gardner

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by little-oddball** [comment]
VFS Team

**Comment by little-oddball** [comment]
@holytoastr - I am hopping in to try and help w/ these items. Our Gov't PO had a transition and we now require to have the eQIP transmittal date provided. Would you be able to work with your PO/PM to provide that? Once that has been applied to the ticket I push move it forward to our Gov't PO for a review/approval. Thanks and sorry for the delay and any inconvenience.

**Comment by holytoastr** [comment]
@little-oddball I had reciprocity, so I am looking into when my original eQIP was done. Thanks for your patience!

**Comment by holytoastr** [comment]
@little-oddball My BI was cleared on 5/31/2018

**Comment by little-oddball** [comment]
@BillChapmanUSDS - Are there other items needed for this to be approved?

**Comment by BillChapmanUSDS** [comment]
I approve this access for non-production environments.   If prod access is needed it should be limited to 3 months while we are evaluating exceptional access request processes.
