### ISSUE TITLE
SOCKS access for Andrew Bunker

### ISSUE THREAD

**Issue by ambunker1** [department-of-veterans-affairs/va.gov-team#52632]
### Your Name

Andrew Bunker

### Your Email

andrew.bunker@adhocteam.us

### Your Role and Team

DevOps Engineer on Lighthouse

### Product Manager (PM) name and email

Gabriel Olaviarra olavarria_gabriel@bah.com

### Product Owner (PO) name and email

Andrew Fichter andrew.fichter@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDi+29kRuubya0dUQhvqyH9voUpUQunpqRJiNfdGKHccgjB1t4G09vPv4wv4uRLb4xhV6iQiMR3gBmA6hVclJSZnfmqYNMFixGijJ/ny4Snw36psDxJh7ZxGvhUhhQj676vCGlXWLzpc1zox58SrXRtJVnuD52KPCB0+PE2q1f/+2j97yGzqn70gmwI0Glo5u2wE8ZdFg+XpPCA1IkLGoNAPrQTeyVmS92airAujXriIXIC1HZz5O5CjDcyo6Bu5bGHwt93RfDTOClv7mLGQ0DJWkNdrmBQkHinGeIopltAFcaw84i4IAHASWdwdxiJ2Xzo/xc5luGXREvJ6eMX8Nh2X+ZmzWIjFOJvUMyYS9eoSfIsWn9h3N6WJdBRdY0qZD+asE7cjVO4y2Kk6uqihLypDkCx3nUWGc2kEODjh4RyyMrZq8IzyToBScipNezB2teD8pMQi+b+CQlgvyYmYk8jYQ58KLjefgQ5q0HfA8oETzgJPKGwhBU4q4zIisoZgYk= andrewbunker@Andrews-MBP-2.fios-router.home

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by rmtolmach** [comment]
@ambunker1  Access granted ✅ 

Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html 

Reach out in #vfs-platform-support if you have any trouble.
