### ISSUE TITLE
Publish Drupal Page for eBenefits

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#5267]
## Description of request
*Detailed description of the request including background information and reason for the request*

 1. **Is the request related to a VA.gov tool?** If yes, provide brief description of the tool or functionality: _This is the [unauthenticated landing page + login widget made for eBenefits last sprint](https://github.com/department-of-veterans-affairs/va.gov-team/issues/3767)_ 
 2. **Provide a link to product brief or outline:** _N/A_
 3. **Provide a link to wireframes, prototype:** _N/A_
 4. **Provide a link to any user research synthesis:** _N/A_
 5. **Do you need new URLs, redirects? (If yes, submit URL and redirect requests first to @ Mikki Northuis on the Platform team.):** _No_
 
## Desired/target implementation date
**Is there an ETA for a particular launch or completion date when request needs to be completed (for instance, for a user research session or eBenefits migration)? Our team's capacity will determine which sprint the work falls into.** 
_This is anticipated to be pretty quick, EOD 2/3 would be great_

## Type of support request
*Select all applicable* 

- [ ] Content support for authenticated app/tool. Note: Support is provided only for VSA apps teams that do not have its own dedicated content writer.

In addition to the above general information, include:
      1. Word document with draft if available, or link to the URL where the draft content appears:
      2. Provide design context: (Example: Is this content in a user flow, an in-line error message, tool tip, field label?)
      3. Scope: How many screens? (Or messages, etc.) 
      
- [ ] Content support for a static public website page
      1. Is this to update existing static content? 
      2. Does this need a new static tool landing page? (The content team may propose a different approach in consultation with IA.)
      2. Provide a list of URL/s that need to be reviewed or updated. 
      3. If it's a small copy section, list what the new info should be and what it is replacing.

- [ ] FE engineering
      1. [Let's get Nick and Kelson to provide input here on what kind of details they typically need to get started]
      2. [more stuff???]

- [x] Drupal
      1. Publish page in drafts in Drupal (ref: https://github.com/department-of-veterans-affairs/va.gov-team/issues/3767)
      
### Requestor info
*Indicate what team and who the primary contacts are on your team* 

Team name: _eBenefits_

DEPO product owner: _Steve Kovacs_

Product manager: _Jason Wolf_

Designer: _Jim Adams_

FE engineer: _Micah Chiang & Jesse Cohn_

Product/team Slack channel: _#vsa-ebenefits_

### Have you completed these steps?:

- [x] I've provided the __Description.__
- [x] I've provided the __Desired/target implementation date.__
- [x] I've selected all relevant __Type of request.__
- [x] I've filled out the __Requestor info.__
- [x] Issue is labeled with the relevant practice areas: Content, frontend
- [ ] Request is assigned  *Public Websites Team* and *@ with Kara Kamahi and Jennifer Lee* for intake

**Comment by MickinSahni** [comment]
@jason-gcio could you share a link/reference to the "page already created"? Maybe an associated ticket too?

**Comment by jason-gcio** [comment]
@MickinSahni - Sure, I think @RLHecht has a better link to the actual page, but it was referenced here (https://github.com/department-of-veterans-affairs/va.gov-team/issues/3767). 

I'll add above.

**Comment by MickinSahni** [comment]
@jason-gcio @steve-gov 
Couple things to confirm:
- Is the intent for the unauthenticated page + the sign in widget to go live in prod?
- What's the particular day this is supposed to go live?

**Comment by jason-gcio** [comment]
> @jason-gcio @steve-gov
> Couple things to confirm:
> 
> * Is the intent for the unauthenticated page + the sign in widget to go live in prod?
> * What's the particular day this is supposed to go live?

- Yes, that page can be made live
- Monday should work, if that works for you

**Comment by jason-gcio** [comment]
Slacked with @RLHecht about publishing the page on Monday.  I will most likely ping her in the morning about a more specific time.

**Comment by RLHecht** [comment]
This page was published. Moving to validate.

**Comment by RLHecht** [comment]
This page is now live on the site. Closing ticket.
