### ISSUE TITLE
link to release plan is wrong

### ISSUE THREAD

**Issue by leahbannon2** [department-of-veterans-affairs/va.gov-team#52671]
### Description
The link to the release plan on the [product development checklist](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/product-development-checklist) links to a random branch. It should be replaced with [this link to the master branch](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/release-plan-template.md)

**Comment by vbellissimo** [comment]
@leahbannon2 Hello. Thanks for submitting this content request. We'll take a look and correct the issue shortly.

**Comment by vbellissimo** [comment]
@leahbannon2 Hi Leah, thanks for letting us know about this URL change. We've made the update on the page and it will reflect live on the website today by 5pm ET. Thank you!

cc @BSmolensky
