### ISSUE TITLE
Spike - determine LOE for TRICARE taxonomy change from Women Veterans

### ISSUE THREAD

**Issue by Dottisea** [department-of-veterans-affairs/va.gov-team#52679]
## Issue Description
TRICARE serves many women who are spouses, not veterans and the Phrase "Women Veteran Care" excludes them:

Hello,
Can we receive the documentation provided from the committee for their reasoning behind denying us a name change for “Women Veteran care” to “Women’s health care”?
The decision the committee made is going to have far-reaching implications to anyone visiting the TRICARE version of the site, specifically the spouses of our active-duty service members.
You could possibly get away with an active-duty patient associating “Veteran” with themselves but just labeling it as “Women Veteran care” sends a message that we don’t provide services to spouses and that they need to look for information somewhere else.
Our patient population is roughly broken down as:

18,000 enrolled Veterans
45,000 TRICARE recruits
12,00 TRICARE beneficiaries

As you can see, we have a much larger population of TRICARE patients compared to our Veteran patients.
Please send us the documentation so we can brief our leadership on why this decision was made.
Thank you,
 Katie K. Yearley
---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by davidmpickett** [comment]
Resolved in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12586
