### ISSUE TITLE
VA Mobile App: Testing in Staging Vets-API Server to EKS

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#52692]
**What’s happening?**
We are in the process of migrating vets-api server to EKS (Amazon's K8 service), which will bring us one step closer to microservices. 
- As part of the testing process for vets-api server migration to EKS, we’ve tested healthcheck paths. 
- We also need help testing endpoints. This is where you come in!

**Why is this important?**
- We want to verify expected behaviors from the endpoints, so the expected behavior(s) translate from BRD to EKS.

**TESTING IN STAGING WILL CLOSE COB 2.28.2023. IF WE DO NOT HEAR OF ANY ISSUES YOU ARE HAVING BY THEN, WE WILL ASSUME YOUR ENDPOINTS ARE BEHAVING AS EXPECTED. TESTING FOR SANDBOX (if applicable) WILL BEGIN 3.2.2023.**

------
**As a VFS/Platform Team, what do I need to do? **

**1. WHAT ENDPOINTS DOES YOUR TEAM/APP OWN?**
- [ ] In the comments of this ticket, provide a list of endpoints your team/app owns/maintains (we know some teams have already provided this information, but we would like to verify this list again with you)

**2. VERIFY DEV SYNTHETIC TESTS (for endpoints your team/app owns)**
- [ ] Verify the test from the inside of TIC firewall aka vfs-dev (if you do not have SOCKS access, please note in this ticket)
- [ ] Verify the test from the outside of TIC firewall aka revproxy-dev (going through the [Reverse Proxy](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474594232/Reverse+Proxy))
- [ ] Check for missing tests or duplicated tests
- [ ] Note any issues with lack of test data and/or users in the comments section of this ticket

**3. PER YOUR JUDGEMENT, IF NEEDED, PERFORM MANUAL TESTING**
- [ ] Complete necessary manual testing
- [ ] Link documentation, in the comments of this ticket, showing the completion of any manual testing

**Comment by jperk51** [comment]
1. Here are our endpoints: https://department-of-veterans-affairs.github.io/va-mobile-app/api/
2. I don't believe we use the dev synthetic tests so I don't think there's anything for us to do
3. Our typical RC testing of the app should adequately test our endpoints. @laineymajor When should we expect to be able to begin our testing in staging?

**Comment by TKDickson** [comment]
Jayson, Lainey and I chatted in DSVA slack -- confirmed that [our typical regression testing cases that we run testing our new release candidate build were most recently run when all of the EKS staging work was in place (Feb 1st-3rd)](https://dsvavsp.testrail.io/index.php?/runs/view/4459). 

We did find some front-end bugs during testing (the fails and defects noted in the run), but no issues with the underlying APIs/nothing that relates to the server migration.

**Comment by laineymajor** [comment]
@TKDickson can you please mark this as complete if you all feel comfortable with staging?

**Comment by TKDickson** [comment]
Yep, I've confirmed with our team that we're good to close.
