### ISSUE TITLE
[Analytics Request] Analytics for VSP Leadership

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#527]
## User Story
As a VSP decision maker, I need VA.gov analytics so I can make metrics-informed prioritization and organizational decisions.

## Goal
Provide Andrew and Leah with the requested va.gov analytics.

## Metrics Requested
- [ ] % of HTTP requests completed successfully (basically, uptime)
- [ ] latency by percentile (i.e. median latency, 90th-percentile latency) of HTTP requests
- [x] page load time (as experienced by user) by percentile
- [ ] CI/CD build time by percentile (basically "how long does a build take after commit / for a PR"?)
- [ ] production deployment success rate (i.e. how many of our daily prod deploys succeed on the first try / without manual intervention?)

## Acceptance Criteria
- [ ] Send the requested metrics to Andrew and Rachael
- [ ] Record processes for any difficult to obtain metrics
- [ ] Record any uncaptured/unobtainable data

## Definition of Done
- [ ] **Attached to a Milestone** 
- [ ] **Attached to an Epic** 
- [ ] **Labeled with Team**
- [ ] **Labeled with Practice Area** 
- [ ] **Labeled with Type**

**Comment by nedierecel** [comment]
@joanneesteban @jonwehausen Adding documentation here for data sources, which we can update as we solidify the process: 

| Data Point | Source | 
| --- | --- |
| Modernized Page Load Time | [Google Analytics - Page Load Time Distribution WBC View](https://analytics.google.com/analytics/web/?utm_source=marketingplatform.google.com&utm_medium=et&utm_campaign=marketingplatform.google.com%2Fabout%2Fanalytics%2F#/report/content-site-speed/a50123418w177519031p184624291/_u.date00=20190501&_u.date01=20190630&_r.tabId=histogramTab&histogramTab-advancedHistogramTable.open=0,1000,3000,7000,13000,21000,35000/)|

**Comment by joanneesteban** [comment]
We provided page load times on GA. Leadership reached out to DevOps on other metrics. 

We will monitor Wyatt's responses so we have links to this data.

**Comment by joanneesteban** [comment]
Insight tasks are completed. We will be monitoring Wyatt's (Ops) dashboard progress for this data.
