### ISSUE TITLE
Facilities: Testing in Staging Vets-API Server to EKS

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#52703]
**What’s happening?**
We are in the process of migrating vets-api server to EKS (Amazon's K8 service), which will bring us one step closer to microservices. 
- As part of the testing process for vets-api server migration to EKS, we’ve tested healthcheck paths. 
- We also need help testing endpoints. This is where you come in!

**Why is this important?**
- We want to verify expected behaviors from the endpoints, so the expected behavior(s) translate from BRD to EKS.

**TESTING IN STAGING WILL CLOSE COB 2.28.2023. IF WE DO NOT HEAR OF ANY ISSUES YOU ARE HAVING BY THEN, WE WILL ASSUME YOUR ENDPOINTS ARE BEHAVING AS EXPECTED. TESTING FOR SANDBOX (if applicable) WILL BEGIN 3.2.2023.**

------
**As a VFS/Platform Team, what do I need to do? **

**1. WHAT ENDPOINTS DOES YOUR TEAM/APP OWN?**
- [x] In the comments of this ticket, provide a list of endpoints your team/app owns/maintains (we know some teams have already provided this information, but we would like to verify this list again with you)

**2. VERIFY DEV SYNTHETIC TESTS (for endpoints your team/app owns)**
- [x] Verify the test from the inside of TIC firewall aka vfs-dev (if you do not have SOCKS access, please note in this ticket)
- [x] Verify the test from the outside of TIC firewall aka revproxy-dev (going through the [Reverse Proxy](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474594232/Reverse+Proxy))
- [x] Check for missing tests or duplicated tests
- [x] Note any issues with lack of test data and/or users in the comments section of this ticket

**3. PER YOUR JUDGEMENT, IF NEEDED, PERFORM MANUAL TESTING**
- [x] Complete necessary manual testing
- [x] Link documentation, in the comments of this ticket, showing the completion of any manual testing

**Comment by laineymajor** [comment]
@ryguyk @smythe5 How is testing going? Do you all anticipate being able to sign off on staging by end of February?

**Comment by ryguyk** [comment]
@laineymajor We just pulled this into our current sprint that begins today. We should have this completed before the end of February. My plan is to approach this in the same fashion as we did for dev. I believe some existing tests are in place for staging as well. It would be super helpful if you could provide some feedback on whether our [documentation for the dev testing](https://github.com/department-of-veterans-affairs/va.gov-team/issues/52357#issuecomment-1407005348) was sufficient. If so, I'll feel a lot more confident about getting this done!

Thank you!

**Comment by ryguyk** [comment]
## TESTING RESULTS/STATUS

### Our team owns TWO (2) endpoints.
#### https://staging-platform-api.va.gov/facilities_api/v1/
- This endpoint has two synthetic tests in Datadog, each of which pings the endpoints from two separate locations (one inside and one outside the TIC, I believe):
   - https://vagov.ddog-gov.com/synthetics/details/hbk-yzw-u68?from_ts=1677069999396&to_ts=1677073599396&live=true
   - https://vagov.ddog-gov.com/synthetics/details/34n-zte-xzd?from_ts=1677069878026&to_ts=1677073478026&live=true
- At the time of this writing, all tests are passing without issue.
      
#### https://staging-platform-api.va.gov/v1/facilities/
- **This endpoint does _not_ have synthetic tests**
- We **are** able to successfully hit the endpoint manually (browser/Postman):
    - https://staging-platform-api.va.gov/v1/facilities/va/vha_674BY


(Note: This is the same testing setup and results as we saw in our [dev testing](https://github.com/department-of-veterans-affairs/va.gov-team/issues/52357#issuecomment-1412212176).)

**Comment by laineymajor** [comment]
Thanks @ryguyk !
I'll go ahead and close this ticket since you've given me the thumbs up!
