### ISSUE TITLE
Authenticated Experience: Testing in Staging Vets-API Server to EKS

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#52717]
**What’s happening?**
We are in the process of migrating vets-api server to EKS (Amazon's K8 service), which will bring us one step closer to microservices. 
- As part of the testing process for vets-api server migration to EKS, we’ve tested healthcheck paths. 
- We also need help testing endpoints. This is where you come in!

**Why is this important?**
- We want to verify expected behaviors from the endpoints, so the expected behavior(s) translate from BRD to EKS.

**TESTING IN STAGING WILL CLOSE COB 2.28.2023. IF WE DO NOT HEAR OF ANY ISSUES YOU ARE HAVING BY THEN, WE WILL ASSUME YOUR ENDPOINTS ARE BEHAVING AS EXPECTED. TESTING FOR SANDBOX (if applicable) WILL BEGIN 3.2.2023.**

------
**As a VFS/Platform Team, what do I need to do? **

**1. WHAT ENDPOINTS DOES YOUR TEAM/APP OWN?**
- [x] In the comments of this ticket, provide a list of endpoints your team/app owns/maintains (we know some teams have already provided this information, but we would like to verify this list again with you)

**2. VERIFY DEV SYNTHETIC TESTS (for endpoints your team/app owns)**
- [ ] Verify the test from the inside of TIC firewall aka vfs-dev (if you do not have SOCKS access, please note in this ticket)
- [ ] Verify the test from the outside of TIC firewall aka revproxy-dev (going through the [Reverse Proxy](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474594232/Reverse+Proxy))
- [ ] Check for missing tests or duplicated tests
- [ ] Note any issues with lack of test data and/or users in the comments section of this ticket

**3. PER YOUR JUDGEMENT, IF NEEDED, PERFORM MANUAL TESTING**
- [ ] Complete necessary manual testing
- [ ] Link documentation, in the comments of this ticket, showing the completion of any manual testing

**Comment by laineymajor** [comment]
@tpharrison How is testing going? Do you all anticipate being able to sign off on staging by end of February?

**Comment by tpharrison** [comment]
Hi @laineymajor.  I was out the last few days, but I'm going to start testing this week.  I'll be able to sign off on staging by end of the month.  I'll keep you posted.

**Comment by tpharrison** [comment]
Results of GET requests for Profile and MyVA...

![image](https://user-images.githubusercontent.com/653787/220387243-aa36f458-679b-4c51-ae3e-77ca98ce5132.png)

The `/v0/profile/connected_application` endpoint is returning a `404`, but this might be a legitimate response - going to test another user.

**Comment by laineymajor** [comment]
Thanks for the update! If the issue persists, @tpharrison please update us in #eks-migration-support and someone from my team will jump in to assist.

**Comment by tpharrison** [comment]
@laineymajor All endpoints for the Profile and MyVA pages have been tested in staging.  No issues.

| Page    | Endpoint                                       | Action         | Test Result |
| ------- | ---------------------------------------------- | -------------- | ----------- |
| Profile | /v0/disability_compensation_form/rating_info   | GET            | PASS        |
| Profile | /v0/maintenance_windows/                       | GET            | PASS        |
| Profile | /v0/mhv_account                                | GET            | PASS        |
| Profile | /v0/user                                       | GET            | PASS        |
| Profile | /v0/profile/ch33_bank_accounts                 | GET, PUT       | PASS        |
| Profile | /v0/profile/communication_preferences          | GET            | PASS        |
| Profile | /v0/profile/connected_applications             | GET            | PASS        |
| Profile | /v0/profile/full_name                          | GET            | PASS        |
| Profile | /v0/profile/personal_information               | GET            | PASS        |
| Profile | /v0/profile/service_history                    | GET            | PASS        |
| Profile | /v0/ppiu/payment_information                   | GET, PUT       | PASS        |
| Profile | /v0/profile/status                             | GET            | PASS        |
| Profile | /v0/profile/preferred_names                    | PUT            | PASS        |
| Profile | /v0/profile/gender_identities                  | PUT            | PASS        |
| Profile | /v0/profile/address_validation                 | POST           | PASS        |
| Profile | /v0/profile/addresses                          | PUT            | PASS        |
| Profile | /v0/profile/communication_preferences/:id      | PATCH          | PASS        |
| Profile | /v0/profile/telephones                         | PUT            | PASS        |
| Profile | /v0/profile/email_addresses                    | PUT            | PASS        |
| My VA   | /v0/appeals                                    | GET            | PASS        |
| My VA   | /v0/debts                                      | GET            | PASS        |
| My VA   | /v0/disability_compensation_form/rating_info   | GET            | PASS        |
| My VA   | /v0/evss_claims_async                          | GET            | PASS        |
| My VA   | /v0/health_care_applications/enrollment_status | GET            | PASS        |
| My VA   | /v0/maintenance_windows/                       | GET            | PASS        |
| My VA   | /v0/medical_copays                             | GET            | PASS        |
| My VA   | /v0/onsite_notifications                       | GET, POST, PUT | PASS        |
| My VA   | /v0/user                                       | GET            | PASS        |
| My VA   | /v0/profile/full_name                          | GET            | PASS        |
| My VA   | /v0/profile/payment_history                    | GET            | PASS        |
| My VA   | /v0/profile/service_history                    | GET            | PASS        |

**Comment by laineymajor** [comment]
Thanks @tpharrison I'll go ahead and close then!
