### ISSUE TITLE
Check-In Experience: Testing in Staging Vets-API Server to EKS

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#52715]
**What’s happening?**
We are in the process of migrating vets-api server to EKS (Amazon's K8 service), which will bring us one step closer to microservices. 
- As part of the testing process for vets-api server migration to EKS, we’ve tested healthcheck paths. 
- We also need help testing endpoints. This is where you come in!

**Why is this important?**
- We want to verify expected behaviors from the endpoints, so the expected behavior(s) translate from BRD to EKS.

**TESTING IN STAGING WILL CLOSE COB 2.28.2023. IF WE DO NOT HEAR OF ANY ISSUES YOU ARE HAVING BY THEN, WE WILL ASSUME YOUR ENDPOINTS ARE BEHAVING AS EXPECTED. TESTING FOR SANDBOX (if applicable) WILL BEGIN 3.2.2023.**

------
**As a VFS/Platform Team, what do I need to do? **

**1. WHAT ENDPOINTS DOES YOUR TEAM/APP OWN?**
- [ ] In the comments of this ticket, provide a list of endpoints your team/app owns/maintains (we know some teams have already provided this information, but we would like to verify this list again with you)

**2. VERIFY DEV SYNTHETIC TESTS (for endpoints your team/app owns)**
- [ ] Verify the test from the inside of TIC firewall aka vfs-dev (if you do not have SOCKS access, please note in this ticket)
- [ ] Verify the test from the outside of TIC firewall aka revproxy-dev (going through the [Reverse Proxy](https://vfs.atlassian.net/wiki/spaces/OT/pages/1474594232/Reverse+Proxy))
- [ ] Check for missing tests or duplicated tests
- [ ] Note any issues with lack of test data and/or users in the comments section of this ticket

**3. PER YOUR JUDGEMENT, IF NEEDED, PERFORM MANUAL TESTING**
- [ ] Complete necessary manual testing
- [ ] Link documentation, in the comments of this ticket, showing the completion of any manual testing

**Comment by sarahknoppA6** [comment]
Acknowledged. I will work with my team and report back if there are issues.

**Comment by sarahknoppA6** [comment]
@laineymajor my team would like to know if this is currently live in staging. If not, when will it be live in staging?

**Comment by laineymajor** [comment]
@sarahknoppA6 sorry this message didn't come through to me! Yes, staging is at 100% EKS! Test away!

**Comment by sarahknoppA6** [comment]
Got it, thanks! We are going to have to look at it for our next sprint starting 2/22. I will be in touch next wk when we estimate the work and let you know if we don't think testing by end of Feb is feasible.

**Comment by laineymajor** [comment]
@sarahknoppA6 thanks so much! Reach out in #eks-migration-support if you have any questions or issues.

**Comment by kanchanasuriya** [comment]
| Endpoints        | Testing status           | Test Result |
| ------------- |:-------------:| -------:|
| staging-api.va.gov/CheckIn::V2::SessionsController#show      | Verified | PASS |
| staging-api.va.gov/CheckIn::V2::SessionsController#create      | Verified | PASS |
| staging-api.va.gov/CheckIn::V2::SessionsController#show      | Verified | PASS |
| staging-api.va.gov/CheckIn::V2::PatientCheckInsController#show | Verified | PASS |
| staging-api.va.gov/CheckIn::V2::PatientCheckInsController#create| Verified | PASS |
| staging-api.va.gov/CheckIn::V2::DemographicsController#update  | Verified | PASS |
| staging-api.va.gov/CheckIn::V2:: PreCheckInsController#show     | Verified | PASS |
| staging-api.va.gov/CheckIn::V2:: PreCheckInsController#create    | Verified | PASS |
| staging-api.va.gov/CheckIn::V0::TravelClaimsController#create    | Verified | PASS |
| staging-platform-api.vfs.va.gov /CheckIn::V2::SessionsController#show      | Verified | PASS |
| staging-platform-api.vfs.va.gov /CheckIn::V2::SessionsController#create      | Verified | PASS |
| staging-platform-api.vfs.va.gov /CheckIn::V2::SessionsController#show      | Verified | PASS |
| staging-platform-api.vfs.va.gov /CheckIn::V2::PatientCheckInsController#show | Verified | PASS |
| staging-platform-api.vfs.va.gov /CheckIn::V2::PatientCheckInsController#create| Verified | PASS |
| staging-platform-api.vfs.va.gov /CheckIn::V2::DemographicsController#update  | Verified | PASS |
| staging-platform-api.vfs.va.gov /CheckIn::V2:: PreCheckInsController#show     | Verified | PASS |
| staging-platform-api.vfs.va.gov /CheckIn::V2:: PreCheckInsController#create    | Verified | PASS |
| staging-platform-api.vfs.va.gov /CheckIn::V0::TravelClaimsController#create    | Verified | PASS |
