### ISSUE TITLE
[Bug] Facility Locator - Pittsburgh VAMC Redirects - Map icons not redirecting [DRAFT]

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#5272]
[**DRAFT** - I'll be finalized bug details after all test-runs are completed]

## What happened?
On Staging & Production Find Locations page, the Pittsburgh-VAMC-redirected locations [see Proposed Scenarios in QA #3977] are not working for the map-icons' location-popup title-links.

While the pertinent text-result title-links are correctly going to the new facility pages, the map-icons' location-popup title-links still go to to the legacy facility-details ("interstitial") pages, instead of the newly-published facility pages.

## Specs:
- Device: \[browser-/device-agnostic]
- Browser: (e.g. Firefox, IE 11)

## Steps to Reproduce
1. Go to https://staging.va.gov/find-locations/
1. In **Search city...** textbox, input **pittsburg, pa**.
1. From **Search for** dropdown-menu, choose **VA Health**.
1. Click **Search** button.
1. In **map-panel**, find & click the **map-icon** corresponding to one of the redirected Pittsburgh locations. \[see #3977]
1. In **location-popup**, click **title-link**.
1. Observe that browser navigates to incorrect, legacy facility-details ("interstitial") page.

NOTE: All 7 locations are exhibiting this bug.

### Incorrect facility-details ("interstitial") page
\[**e.g., for Pittsburgh VA Medical Center - University Drive**]
![staging-facility-locator-map-icon-redirect-bug-200129a](https://user-images.githubusercontent.com/587583/73384351-5a86f180-4288-11ea-8744-1dbda3995546.png)

## Desired behavior
Map location-popups' title-links take you to the correct, new facility pages, not the legacy location-details page.

### Correct (new) facility page
\[**e.g., for Pittsburgh VA Medical Center - University Drive**]
![staging-facility-locator-map-icon-redirect-desired-page](https://user-images.githubusercontent.com/587583/73385420-5eb40e80-428a-11ea-8f75-1a4cd6a5cfac.png)

## Acceptance Criteria
\[see **Desired behavior** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by mmiddaugh** [comment]
Thanks @Tze-chiu Lei With the MVP changes that were merged today, map pop-ups will be non-existent so we're good there!

**Comment by davidconlon** [comment]
@tlei123 @mmiddaugh I think this can be closed.
