### ISSUE TITLE
Broken / missing links on page: Adding a new External Service Integration

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#52731]
### Description
The page includes file paths which are probably supposed to be links, but they are not currently linked.
For example:
`ansible/deployment/config/fwdproxy/`
Should link to:
https://github.com/department-of-veterans-affairs/devops/tree/master/ansible/deployment/config/fwdproxy

Some of the other paths like `docs/StandardOperatingProcedures/CreatingVASignedSSLCertificate.md` should link to a file, but I cannot find the correct file and it may have been moved.

### Relevant URLs
https://depo-platform-documentation.scrollhelp.site/developer-docs/adding-a-new-external-service-integration

**Comment by vbellissimo** [comment]
Thanks for your submission @mchelen-gov . We will add to our backlog and work with a subject matter expert on the Platform for this request.

**Comment by vbellissimo** [comment]
Hi @mchelen-gov . We've worked with a few engineers on the Platform team and they've updated the content on that page quite a bit. File paths with a link are now also included. Closing this ticket but if you have any other questions, let us know. Thanks!
