### ISSUE TITLE
AWS access for Kevin Duensing

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#52742]
### COR Name

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative Name

Other - please specify in 'Additional Notes'

### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Kevin Duensing

### Your Email

kevin.duensing@adhocteam.us

### Team, Role, and Company of the target individual

Benefits Team 1 - Squad 1, Full Stack Engineer, Ad Hoc LLC

### Product Manager (PM) name and email

Jacob Worrell

### Product Owner (PO) name and email

Matt Self, matthew.self2@va.gov

### Desired AWS Access

Hi there. I need membership to the following groups, please:

`"dsva-vagov-developers", "dsva-vfs-developers", "force-MFA"`

These should be the same groups as `Jerek.Shoemaker` and `Samuel.Cormier`.

Thank you

### Access Expiration

ongoing

### Additional Notes

COR - Keith Riley
VOR - Jeff Langworthy

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by little-oddball** [comment]
There is has been a request for a change from OCTODE on how this flow needs to run. I am working now to get that figured/ironed out to get traction here. Sorry for any inconvenience and will update as soon as possible.

**Comment by kjduensing** [comment]
Thanks Clint!

**Comment by little-oddball** [comment]
@BillChapmanUSDS - 5/4/2021 is his date. Additionally, he was previously on a Spike Team prior to September so we were able to verify date.

**Comment by little-oddball** [comment]
VFS Team Member

**Comment by kjduensing** [comment]
@little-oddball Just checking in - any updates on this request?

**Comment by BillChapmanUSDS** [comment]
I approve this access as requested.
