### ISSUE TITLE
Site Improvement Proposals

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#5274]
Details to come. Idea is create epic/issues/process for proposing new content/visuals/tools/functionality to VA.gov. Goal is to use our collective skills and experience to propose/create next-level experience. 

## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)

## High Level User Story/ies
As a _____, I need _____ so I can _____.

## Hypothesis or Bet
**If** _we make this change_ **then** _we expect this to happen_.

## OKR
_Which Objective / Key Result does this epic push forward?_

### What must be true in order for you to consider this epic complete? 

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)

**Comment by MickinSahni** [comment]
We can groom this further and create constituent tickets e.g. for AMA. 
Tickets within this epic will likely result in a doc/proposal for evaluation.

**Comment by wesrowe** [comment]
Epic never fleshed out
