### ISSUE TITLE
[Bug] Multiple FSR Submissions

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#52756]
## What happened?
Stakeholders (both VHA and VBA) have reported seeing multiple and identical FSR submissions for the same Veteran across multiple days. One example is from a Veteran who had 12 submissions between Jan 17-25, 2023 although the signature date remains at the 17th.

## To be investigated
- [x] Determine what is happening to cause these multiple submissions and what needs to be done to resolve.
- [x] Determine if multiple submissions are also being added to our submission metrics
- [x] Determine if email notifications are being sent for each submission

## Acceptance Criteria
- [ ] Understand/resolve issue that is causing multiple FSR submissions 

## How to configure this issue
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by ScottyRJames** [comment]
Opened [PR ](https://github.com/department-of-veterans-affairs/vets-api/pull/11685 )to disable worker retries until we can validate the cause of unnecessary retry

**Comment by ScottyRJames** [comment]
Retries are turned off for errors within background jobs and have opened this [ticket](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/53021) to resolve user not found errors.
