### ISSUE TITLE
Compare search results of Find Forms against the search results of the legacy page when using the same query

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#5277]
Executing a query using the term `health care` produces different results across the Find Forms app and the legacy equivalent.

- Find Forms: http://preview-prod.vfs.va.gov/preview?nodeId=2352&q=health+care
    - Produces 2 results
- Legacy: https://www.va.gov/vaforms/search_action.asp?FormNo=&tkey=health+care&Action=Search
    - Produces 69 results

We should investigate the differences between the two and determine if the results of Find Forms is are better or worse than that of the legacy version. If worse, determine next steps to improve the search function.

### Conclusions
- TODO
- Find Forms:
    - Executing a query that contains trailing or leading whitespace affects search results
- Legacy:
    - Seems to be using whitespace as a separator, matching each individual word against the form name and other fields

**Comment by jenniferlee-dsva** [comment]
@ncksllvn - when you share findings with the Lighthouse team, please include Andrew Fichter.

**Comment by jenniferlee-dsva** [comment]
@ncksllvn (FYSA @MickinSahni) - edited ^ ticket description and added a bit more details.

**Comment by ncksllvn** [comment]
My takeaways from this, using legacy search to refer to `/vaforms/` and Find Forms to refer to the modernized.

### Spaces between words in input
It appears that the legacy search treats whitespace inside of the input as a separator, meaning `health care` becomes `['health', 'care']`. Each element of this list is then matched against the title of each form. So, if a form title contains `health` or `care`, that form is returned as a result. For example, the second search result for `health care` on the legacy search is form `10-7959C`, titled `CHAMPVA - Other Health Insurance (OHI) Certificate`. Notice that `health` is there, but not `care`.

The Find Forms treats the input as a single compound word, so the form name must contain `health care` together. Searching `health care` on that search yields just two results, both containing `health care` together. For example, `VA Advance Directive: Durable Power of Attorney for Health Care and Living Will`.

### Trailing/leading whitespace in input
The Find Forms search function does not trim leading/trailing whitespace before executing its query. The legacy search appears to be affected if there's more than one space leading but seems to be unaffected by trailing whitespace. This is weird. 

We should update the Find Forms API to strip leading/trailing whitespace. This may be a small advantage over the legacy.

### VA Forms DB - "keywords" table
From the database export file on GitHub, we know that the VA Forms DB contains an implementation of a `keywords` table. The data behind the `keywords` table is not exposed in the HTML of the legacy search, and the API behind Find Forms currently operates by scraping the legacy page to build an local database, so it cannot take advantage of this table.

However, it's still unclear how exactly that affects results, as far as impacting the results negatively or positively. For example, when I search `health care` on the legacy search, I see form `10-0454` pull up as the 25th result, titled `Military Treatment Facility Referral to VA Liaison - fillable`. Would a user searching `health care` be interested in this form? I'm unsure.

**Comment by ncksllvn** [comment]
We may want to do a little more research on the `keywords` in the VA Forms DB, but otherwise I think next steps are -

1. Hand this work off to the Lighthouse team for prioritization and implementation.
1. Break this into ticket and schedule it for our team to implement.

**Comment by ncksllvn** [comment]
The `trailing/leading whitespace` issue is easy so I opened a PR for it in the Lighthouse API - https://github.com/department-of-veterans-affairs/vets-api/pull/3837.

**Comment by ncksllvn** [comment]
### Update after call on Feb. 3rd 
Call was attended by myself, Kevin Reid and Jenny Shin (? not sure if I heard her name correctly)

1. Jenny confirmed how a search on `/vaforms/` works - when you type into the `keywords` input, it uses spaces as a separator to form a list of terms. If a form name contains one of those terms, or if the form has a `keyword` (from the `Keywords` table in the DB) associated that matches one of the terms, the form is considered a match.
1. In the `Form_keywords` table of the VA Forms database, the `rowid` column corresponds to the `RowID` column of the `Forms` table. In the `Forms` table, the `RowId` is hidden in the [database export spreadsheet](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/database-export-VAForms_82819.xlsx). In the spreadsheet, it is column E.  I asked how well these keywords are maintained. They said that the keywords are managed by another team in a UI of some sort, so requests do not pass through them, so they aren't sure.
1. There a Dev environment of the VA Forms database. This was made recently, after our team proposed two new fields to the database, such as the benefit category. He said we should have read-only access, and suggested we reach out to @jenniferlee-dsva about that.
1. The Lighthouse team has mentioned potentially parsing the PDFs to define additional search criteria. Kevin said that this won't be particular valuable, because the focus of forms maintainers is to enter metadata into the database, not the file, so searching on the file will likely be inconsistent and not really useful. However, if we can do it, he suggested trying it out anyway.

**Comment by ncksllvn** [comment]
I think the big question here for our purposes is - does our search tool require the `keywords` data in the VA Forms database in order to be equal/better to the legacy forms search? If it does, we are effectively blocked on launch until the the Lighthouse API has access to the VA Forms DB so can begin using the `keywords` data.

**Comment by jenniferlee-dsva** [comment]
@ncksllvn - would love to sync and hear your learnings tomorrow/later in week.

**Comment by MickinSahni** [comment]
Next step: figuring out what task should come out of this exercise/ticket. Will close this out after that's created.

**Comment by MickinSahni** [comment]
2020-02-06 PW Standup
- We're closing this out in favor of subsequent decision and implementation tickets captured in the new/updated epics we spun up

**Comment by MickinSahni** [comment]
From #5702 
>The comment here is addressed in any decision we make re: keywords

> ✔️ This is related to the forms search (not the form detail pages, as this ticket refers) but from the call on February 7th, it sounds like that we want complete parity with the legacy forms search before we can roll out our modernized forms search. So, we'll likely be blocked on launching the forms search until the Lighthouse API for searching forms has access to the VA Forms DB instead of scraping the legacy webpage, because the Lighthouse API will need the ability to integrate keywords into its search algorithm.

and from this [comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/5277#issuecomment-581647850) 
> I think the big question here for our purposes is - does our search tool require the keywords data in the VA Forms database in order to be equal/better to the legacy forms search? If it does, we are effectively blocked on launch until the the Lighthouse API has access to the VA Forms DB so can begin using the keywords data.

Hey @ncksllvn, is it still an open question whether `keywords` is a part of the search MVP? Based on the analysis above, I think we're ruling it out for MVP so we can launch and iterate as needed. cc @jenniferlee-dsva

**Comment by ncksllvn** [comment]
@MickinSahni Just talked with @jenniferlee-dsva about that, and followed up here - https://github.com/department-of-veterans-affairs/va.gov-team/issues/5702#issuecomment-588300288 - although this ticket is probably a better place for the convo.

We're thinking we should implement #5693 then re-evaluate. Currently, we can't launch because of examples like this - searching `health care` doesn't pull up 10-10EZ, because its name is `Instructions For Completing Enrollment Application For Health Benefits`. It doesn't contain `health care`. However, #5693 would fix that, because it _does_ contain `health`.

**Comment by ncksllvn** [comment]
The PR for stripping trailing/leading whitespace is taking than I expected to be approved, so I wrote an issue to track it - https://github.com/department-of-veterans-affairs/va.gov-team/issues/6048
