### ISSUE TITLE
Analytics Implementation or QA Support for Pre-Need Eligibility Determination Form

### ISSUE THREAD

**Issue by ccruzgra** [department-of-veterans-affairs/va.gov-team#52798]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>Our team is beginning early discovery activities on the Pre-Need Eligibility Determination form on va.gov to potentially update parts of the UI and to integrate the application with Salesforce/BOSS systems for submission purposes. We are interested in learning if analytics are currently being captured for this application.</summary>
<div>
    <br>
<p>Use this template to request Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

</div>
</details>

### Required
- **Is this request for **Google Analytics implementation** or **QA**?**

     - [x] Google Analytics implementation
     - [ ] QA

- **Who is this request for?**

    - MBS team
    
- **Provide the link(s) for Google Analytics implementation or QA**
  
    - https://www.va.gov/burials-memorials/pre-need-eligibility/
    - https://www.va.gov/burials-and-memorials/pre-need/form-10007-apply-for-eligibility/introduction
    
- **When is the launch date?**
    - No launch date yet

- **What interactions need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked_
    
    - At this point, we are interested in learning if any interactions or analytics in general are being captured. We will make specific interaction tracking requests at a future date. 

### Optional
- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - [Insert test user]

- **Any additional comments**

    - [Insert comments]

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by michelle-dooley** [comment]
@ccruzgra -these GA reports show the events that are currently being tracked on those pages.  

[/pre-need-eligibility](https://analytics.google.com/analytics/web/#/report/content-event-pages/a50123418w177519031p184624291/_u.date00=20230101&_u.date01=20230130&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.eventAction&explorer-table.rowStart=0&explorer-table.rowCount=500&_r.drilldown=analytics.pagePath:~2Fburials-memorials~2Fpre-need-eligibility~2Findex.html)

[form-10007-apply-for-eligibility/](https://analytics.google.com/analytics/web/#/report/content-event-pages/a50123418w177519031p184624291/_u.date00=20230101&_u.date01=20230130&_r.drilldown=analytics.pagePath:~2Fburials-and-memorials~2Fpre-need~2Fform-10007-apply-for-eligibility~2Fintroduction~2F&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.eventAction&explorer-table.rowStart=0&explorer-table.rowCount=250)

Hope that helps.  Going to close this ticket.  If you need new event tracking please submit a ticket for that specific event request.

**Comment by ccruzgra** [comment]
@michelle-dooley Thanks for your help. I'm having issues viewing those links. Are you able to give me access? My VA email I'm using in Google is cindy.cruzgranados@va.gov
