### ISSUE TITLE
Discovery - Landing Page

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#52799]
Tasks
[ ] Review initial designs
[ ] Review existing MHV home page
[ ] Review Mikki's findings
[ ] Identify at least two new features to add
[ ] Determine if different authentication systems can maintain a session across domains

Acceptance Criteria
[ ] Identified the two new features to add
[ ] Document requirements for the landing page and elements that will need to be included

**Comment by mnorthuis** [comment]
I believe this work is done and this can be closed
