### ISSUE TITLE
My Health Landing Page:  Designs

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#52801]
Tasks
- [x] Create low and hi-fi mock up for MyHealth Landing Page options

Acceptance Criteria
- [x] High fi mockups
- [x] Annotations for engineers
- [x] Document design decisions

**Comment by dcloud** [comment]
Noticed that comps were linked to on #49026… so adding this comment to link the tickets

**Comment by batemapf** [comment]
@MarciMcGuire i think this can be closed, at least for the authenticated landing page designs per the ticket linked above.

**Comment by MarciMcGuire** [comment]
@batemapf will do!
