### ISSUE TITLE
Build a simple search API endpoint

### ISSUE THREAD

**Issue by johnpaulashenfelter** [department-of-veterans-affairs/va.gov-team#5280]
As part of experimenting with alternatives to our current use of modules/engines, it makes sense to build an API endpoint using a simple, straightforward, green-field approach to have an example to use for reviewing alternatives

## High Level User Story
When a search is requested from the front-end app
I want to receive a clear GET JSON request in a known format
So I can provide a clear OpenAPI formatted response with the results

## Goals
- [ ] A clear specification for the request
- [ ] A clear specification for the response
- [ ] A working integration that wraps up the va.gov search provider

**Comment by erluti** [comment]
branch for search work: https://github.com/department-of-veterans-affairs/vets-api/tree/betools-pb-greenfield-search-api

This is the basic structure of how I would implement a search api endpoint.  I was working to get my code to match the output from the existing VCR mocks.  I'm not settled on the name-spacing, but the concept is that new endpoints would be in an external_api namespace.  There's more I'd do before I'd be happy with it as a PR, but I think it meets the goals of this ticket.

**Comment by alexpappasoddball** [comment]
@johnpaulashenfelter ready for your review
