### ISSUE TITLE
Update `vets-json-schema` repo README

### ISSUE THREAD

**Issue by jholton** [department-of-veterans-affairs/va.gov-team#5281]
The README for the [`vets-json-schema` repo ](https://github.com/department-of-veterans-affairs/vets-json-schema/) could be more descriptive.  

It should at least mention that updating an existing schema could affect both the frontend and backend codebases.  Tests/specs should be run in each codebase after updating a schema.

Perhaps links to existing documents should added: ["Creating a Form Schema in Vets-JSON-Schema"](https://github.com/department-of-veterans-affairs/va.gov-team/blob/0cb404d836086dc1d73ebb4b0fa9cf0c501a1b67/platform/engineering/creating-form-schema.md)

**Comment by johnpaulashenfelter** [comment]
Added in https://github.com/department-of-veterans-affairs/vets-json-schema/pull/434
