### ISSUE TITLE
Review KB article about Vet Centers

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#52849]
## Issue Description

The CMS team made updates to their Knowledge Base article about Vet Center publishing processes. Because our team supported Vet Center editors in their site launches, we should review the article to make sure it's accurate and contains all the pertinent info.

KB article to review: https://prod.cms.va.gov/help/vet-centers/what-is-the-process-for-publishing-my-vet-centers-pages

## Tasks
- [ ] Megan review
- [x] Randi review
- [x] Provide feedback to Laura F on CMS team

## Acceptance Criteria
- [x] CMS team has our final comments

**Comment by RLHecht** [comment]
@laflannery Sorry this took so long for me to get around to. After reviewing I had a few suggestions:

-  Since the project is now complete, the first H2 is confusing. Can we change it to "If the Vet Center website is new" or "If the Vet Center isn't already live on VA.gov"? I'm not sure if there are ever brand-new Vet Centers that open that would then require a new website to be started. I'd also suggest changing the next H2 to "If the Vet Center is already live on VA.gov"
- We aren't holding office hours anymore so we should remove that info from step 3 in the first section.
- In the archiving content section, do we need to add more info to the note about how to archive content if the site is not yet published (notify the CMS help desk and they'll archive it)?
- This isn't Vet Center specific, but we should be consistent with the voice we use on VA.gov. There are a few places here where we should use contractions and active voice to meet our plain language standards.

**Comment by RLHecht** [comment]
@laflannery I don't think we would need to archive a whole Vet Center, but there were instances where we archived CAPs or one of the optional services when we realized it wasn't needed. 

I found a few more contractions and a few places where I switched the sentences to active voice. Just suggestions!

- Please know that saving your pages as **In review** doesn't send any notification to the CMS help desk team. (in steps 3 and 9)
- Step 10: You'll receive a confirmation email that you've made all necessary changes and we've sent your pages for final review.
- Step 11: Following the final review of your pages, you'll receive an email with either requested changes or confirmation that we've approved your pages to go live.
- Step 12: If we've requested additional changes, please address this feedback as quickly as possible and confirm with the team once you've made the changes.
- Step 13: Once we've published your pages, we'll update your user permissions. This will allow you to make future edits or updates to the services and locations on your page as needed.
- Under "If the Vet Center is already live..." You'll make changes and additions to your Vet Center pages in the same places where you created and edited your original content. However, now that your pages are live, we've updated your user credentials so that you're able to publish the content on your own.
- In the note for archiving: If your Vet Center site isn't published yet, you won't have this option available.
- The Draft option from the Save As dropdown menu doesn't archive or "un-publish" content...

**Comment by laflannery** [comment]
Done, Thank you!!

**Comment by RLHecht** [comment]
Going to close this. Megan, we can always reopen if you want to take a look.
