### ISSUE TITLE
Vets-Api Rails Cache - Spike

### ISSUE THREAD

**Issue by cferris32** [department-of-veterans-affairs/va.gov-team#52859]
We'd like to explore the capabilities of the Rails `ActiveSupport::Cache` mechanism to improve upon the caching we already do for various tasks in vets-api (such as storing names from provider lookup), and then implement it if/where it makes sense.

Questions to answer from research:
Q: What pros/cons does `ActiveSupport::Cache` have compared to our current caching methods?
A:
Q: What spots in vets-api (if any) would benefit from this caching tool?
A:

Timebox: 8 hrs

**Comment by ajmagdub** [comment]
In the GET Appointments call, the Appointments controller calls the VAOS Service to gather the appointment information. Once the Appointments are retrieved, the controller makes further calls to collect Facility/Clinic and Provider information. 

Facility calls can take 0.5 to 2.0 seconds each (calls to the Redis cache are much quicker). And can take more time than the original call to get appointments, as shown in the following graph:


![Typical_GET_appointments_action.png](https://images.zenhubusercontent.com/58c9796351aa2c3057788fd5/8607388e-4f00-47cf-a9fd-ed983fafb3f0)
The Facility/Clinic and Provider calls are cached on a per-request basis. The cached calls are only kept for the duration of the request; each time Vets Web calls Vets API, the cache has to be built again.

We can extend the time the cache is kept using `Rails.cache`. The time the Facility/Clinic or Provider name results are stored can be set at the time the record is put in the cache and can be from minutes to days. This will maintain the cached records over multiple Vets Web calls. 

The following method is a typical cached call, this method first tries to read from the cache, and if the data is not found, it executes the block passed to it and stores the result in the cache:
``` ruby
@facility = Rails.cache.fetch("facility_id", expires_in: 1.day) do
   # call the backend to get facility info
end
```

VAOS has not extensively used caching (other than for Vets API to VAMF token caching). This change will introduce more load to va.gov's Redis; monitoring Redis performance as the load increases is essential. Redis memory usage is also a concern. Though facility/clinic and provider information does not change very often, there exists the possibility that the cached data may become out of date (the expires_in value should be carefully chosen).

Note: there is currently a `Common::RedisStore` in use that other classes can inherit from and provides access to the Redis cache, but that relies on `::ActiveModel,` which is not used in VAOS Vets API.  `Rails.cache` is much simpler to use.
