### ISSUE TITLE
[Monitoring] Publish a list of available dashboards on the Platform Website

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#52863]
## User Story
As a VFS developer, I need an overview of available Platform Dashboards that allow me to monitor the health and performance of platform applications (ie Vets-API and related services). 

## Background 
- The Platform Website is the primary location for VFS Developers looking for services and tools provided by the Platform
- [This document exists in Confluence](https://vfs.atlassian.net/wiki/spaces/TT2/pages/2430599197/Platform+Dashboards+in+Datadog) but should be published to the Platform Website, along with any necessary edits

## Acceptance Criteria
- [x] The doc is ready to be published to the Platform Website
- [x] The documentation links to dashboards available in Datadog

## Refinement Guidance - Check the following before working on this issue: 
- [x] _Team label assigned ("platform-tech-team-2")_
- [x] _Epic assigned (if needed)_ 
- [x] _Estimated (points assigned)_
- [x] _Sprint assigned (once planned)_
- [x] _Team member(s) assigned_

**Comment by it-harrison** [comment]
Tweaked text and updated screenshots. The draft is [here](https://vfs.atlassian.net/wiki/spaces/TT2/pages/2520252551/Platform+Dashboards+in+Datadog).

**Comment by jhouse-solvd** [comment]
Docs have been copied to the Platform website drafts space [here](https://vfs.atlassian.net/wiki/spaces/PWD/pages/2529591297/Monitor+Applications+and+Infrastructure+with+Datadog). 

Pending any feedback or recommended changes, we’d like to have the documentation published by EOD on Monday, February 20, 2023.

This issue can be closed.
