### ISSUE TITLE
Implement Tags in GA for Metrics

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#52865]

**Comment by loripusey** [comment]
@brianseek thinks most tags are in place but need @benbrasso-agile6 to let FE know if there is anything else

**Comment by benbrasso-agile6** [comment]
@brianseek was right, we finished this here https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/48703
