### ISSUE TITLE
Update Filters to remove addresses in Facility Locator search

### ISSUE THREAD

**Issue by nedierecel** [department-of-veterans-affairs/va.gov-team#5286]
## What happened?
Address information is flowing into the All VA.gov view for facility locator searches and should be removed

## Specs:
- N/A

## Steps to Reproduce
- N/A

## Desired behavior
Any address information is obscured in Production view

## Acceptance Criteria
- [ ] Filter is updated on staging and production so that it strips out address information

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by jonwehausen** [comment]
@nedierecel Is this the filter we need to apply to the "**All VA.gov Website Data [Production] view**"?
![image](https://user-images.githubusercontent.com/48527022/74157591-8a1dee00-4be6-11ea-9c1a-0472d10412e0.png)

**Comment by nedierecel** [comment]
@jonwehausen Yes, this is set up in the Non-prod view. However, to be aligned with CCPA we should create a GTM customTask to remove the parameters before data gets to the views.

**Comment by nedierecel** [comment]
@jonwehausen The "Strip Facility Locator params" filter has been added to the "All VA.gov Production View". 

Can you help me monitor to ensure those parameters are removed today onward? 

As we discussed, we'll create a new issue around the GTM customTask.

**Comment by jonwehausen** [comment]
Hi @nedierecel ,

Thus far, the filter seems to be working well: transforming URLs to ```/facilities/index.html?XXX```

**Comment by nedierecel** [comment]
@jonwehausen I created a new filter as it didn't take into account that the hostname should be appended to the page path for the "All VA.gov - Production View" this has been updated.  I'll monitor one more day then will close this issue.

**Comment by nedierecel** [comment]
@jonwehausen I see the hostname included, so I will close this task.
