### ISSUE TITLE
Change link on Disability housing grants page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#52887]
## Issue Description

Raleigh asked us to update a link on our [Disability housing grants for Veterans](https://www.va.gov/housing-assistance/disability-housing-grants/) page. 

In the "Get more information section," we need to replace the link for the Guide for Specially Adapted Housing and Special Housing Adaptation Projects with this: https://benefits.va.gov/WARMS/docs/admin26/m26_13/sah-2022-update-26-13.pdf

## Tasks
- [x] Update link
- [x] Copyedit (Megan)
- [x] Publish (Megan)
- [x] Alert stakeholder that changes are live (Randi)

## Acceptance Criteria
- [ ] New link is live

**Comment by RLHecht** [comment]
I changed the link and this is now ready for you @megzehn

**Comment by megzehn** [comment]
Confirming this has been published. Thank you, @RLHecht!

**Comment by RLHecht** [comment]
This is live. Closing!
