### ISSUE TITLE
508 Findings for Staging Review for Urgent Care MVP

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#5288]
## Team Name
Facility Locator

## Product Description

Facility Locator Mapbox functionality review following version upgrade

![image](https://user-images.githubusercontent.com/55411834/73398666-c2dece80-429a-11ea-9d63-85798193dc36.png)

## Staging URL and Credentials

https://staging.va.gov/find-locations/
Facility Locator is part of unauthenticated experience and does not require test users. 

## Test Plan

- Facility Locator is part of the unauthenticated experience and as such, no special test users or credentials are needed. 
- Custom settings are not relevant to this implementation.
- Changes have been made only to the main Facility Locator search page, not to any of the Facility Detail pages. Changes are detailed in [#4872](https://github.com/department-of-veterans-affairs/va.gov-team/issues/4872) but are summarized below:
 
### Changes to search functionality

- Search functionality will use new 2 row stacked design (as in prototype and in images attached)
- Dropdown functionality has been maintained. 
- Wording at the top has changed slightly. 
- Links on the page are maintained.  
  - Need same-day care for a minor illness or injury? Search for your nearest VA health facility. Or find VA-approved urgent care locations and pharmacies near you.
  - Can’t find what you’re looking for? Try using our other tools to search.
- Iconography has been removed from dropdown

### Changes to map and list results

- Cards have changed appearance/style but content has not
- Pagination is persistent (displayed outside scroll box).

## Known Issues

- Known issues are related to Mapbox and will be resolved by the upgrade, handled separately in [#3978] (https://github.com/department-of-veterans-affairs/va.gov-team/issues/3978)

**Comment by jenstrickland** [comment]
@mmiddaugh Accessibility audit complete. cc @tlei123

**Comment by mmiddaugh** [comment]
Thanks, @jenstrickland. I will be review today and follow up with you on questions

**Comment by tlei123** [comment]
@mmiddaugh , I just created my 2nd Test Run ticket #7522 for housing a list of post-A11y-Review tickets -- for any changes your team will be making.

Please list the post-A11y-Review tickets there, and ping me when the list is complete.

Thanks much!

**Comment by mandifrances** [comment]
@mmiddaugh is this still relevant? Could it be closed or the product support label removed?

**Comment by mmiddaugh** [comment]
@mandifrances this can be closed.
