### ISSUE TITLE
Begin storing SECID in Accounts table

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/va.gov-team#5289]
Accounts table is an attempt to move off the dependency of ID.me UUIDs for various user data. It has. been in use since August 2018.

It is currently populated after sign-in, and establishes a mapping between idme_uuid, a new VA.gov-specific account_uuid, and (if available) the ICN and EDIPI obtained from MVI. The account_uuid is then used in some tables.

* We should add the IAM-issued SECID to this table and begin recording it for new sign-ins. It is currently available as a correlated ID in MVI. In the future when we receive SAML sessions from SSOe, all IAM users are guaranteed to have a SECID, but not guaranteed to have any other identifier, so this is the best common-demoninator. 
* Ensure that the account persisting mechanism performs updates on existing records so we begin adding this field for all previously-recorded accounts.
* Make the account lookup mechanism robust to searching both by idme_uuid and secid (in whatever order makes sense). This will future-proof this system against a future where we receive incoming sessions with no idme_uuid.

**Comment by patrickvinograd** [comment]
One thing to think through is what the multiplicity of these identifiers is. We know e.g. that there are instances of two ID.me UUIDs mapping to the same ICN. I think SECID should potentially not have a unique constraint on it, but I'm open to being talked out of that opinion.

**Comment by patrickvinograd** [comment]
For the near term I'd like to continue looking up by idme_uuid but also look up by secid (if present) and log a warning to sentry if we ever wind up with a different account_uuid for the two lookups. This will give us greater confidence that we are not introducing any data anomalies by switching this identifier.

**Comment by ambikaroos** [comment]
2/20 @ericbuckley working on writing new test cases

**Comment by ericbuckley** [comment]
@patrickvinograd the migrations in vets-api#3930 have been merged into master, what steps do we need to take to have these applied to dev/staging?
