### ISSUE TITLE
Sandbox Discovery

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#52902]
**PROBLEM STATEMENT**

**DEFINITION OF DONE**
All of the following are documented in Confluence in one single document:
- [x] How does auth work in sandbox, if at all?
- [x] Who uses sandbox?
- [x] What are the similarities to production and staging?
- [x] What else does sandbox mirror?
- [x] What considerations should we take into account acknowledging sandbox doesn't have a frontend?

**Comment by laineymajor** [comment]
@laineymajor  to provide link to documentation in slack and confluence... @LindseySaari to follow-up

**Comment by laineymajor** [comment]
#lighthouse-infrastructure

**Comment by LindseySaari** [comment]
Started a [Discovery doc here](https://vfs.atlassian.net/wiki/spaces/TT1/pages/2524643459/Sandbox+Discovery)

**Comment by LindseySaari** [comment]
Reached out in [#lighthouse-infrastructure here](https://dsva.slack.com/archives/C013VCQKSE7/p1676310745162519)

**Comment by LindseySaari** [comment]
I reached out to the [Lighthouse team here](https://dsva.slack.com/archives/C013VCQKSE7/p1676310745162519) and added the necessary information to complete the [Sandbox discovery doc.](https://vfs.atlassian.net/wiki/spaces/TT1/pages/2524643459/Sandbox+Discovery)
