### ISSUE TITLE
T3 Issue 08066712 - Veteran cannot see disability rating or payment history

### ISSUE THREAD

**Issue by jaredcunha** [department-of-veterans-affairs/va.gov-team#52903]
## Description

**Salesforce ticket ID:** 
 08066712

**Date issue reported:** 7/25/22

**Application ID number, if provided:** N/A

**Issue Veteran is experiencing:**

Veteran indicated that they are not experiencing issues filing claims, importing or uploading documents, but they cannot see their payment history or disability rating. However, on the disability ratings page, they can see their individual ratings.

- `/disability/view-disability-rating/rating`
- `/va-payment-history/payments/`

![Screen Shot 2023-02-01 at 10.43.52 AM.png](https://images.zenhubusercontent.com/614a22e16770da30db220ef8/cd22cfca-3371-46e4-8d1f-51e9f4c9b665)

![Screen Shot 2023-02-01 at 10.43.52 AM.png](https://images.zenhubusercontent.com/614a22e16770da30db220ef8/ca31fdab-39c3-4f07-89d7-6db0d8256a95)

**Comment by HeatherWidmont** [comment]
We are going to close this, but it can be reopened as a separate ticket with information that will allow it to be reproducible @Kimberley2019
