### ISSUE TITLE
Migrate to using account_uuid instead of idme_uuid in all database tables.

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/va.gov-team#5290]
We use the ID.me issued UUID as a primary key for various pieces of persisted data. This is sub-optimal because we are entering a world where we might not always be presented with an ID.me UUID for every user. See:

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/request-for-change/2020-01-17-sso-symmetry-and-identifiers.md

The most troublesome part of this is persisted data in the database that is indexed on this UUID. If a user arrives from another site via SSO and has such data, we might not be able to connect them to their records.   

Accounts table is an attempt to move off the dependency of ID.me UUIDs for various user data. It has been in use since August 2018 but only partially adopted by a few features. We should begin using the account_uuid more widely, as combined with #5289 we should be able to establish or derive an account_uuid for all authenticated users regardless of SSO path. 

But since there is a bunch of data using the user_uuid, we need to make all queries in affected tables robust to using either identifier. Code that populates data should begin using account_uuid, and then code that looks up data should first try the account_uuid, and then if not found also try the idme_uuid as a backup.

Acceptance criteria:
* Enumerate all tables using user_uuid - also check the various schemas/migrations under `modules`. 
* Decide whether there's any risk of collision between the idme_uuid and account_uuid formats, and if so consider prefixing account_uuids when recording.
* Update all uses of above tables to record the account_uuid and make querying/lookup robust to using either identifier.

**Comment by patrickvinograd** [comment]
Suggested approach by Kam:
1. Identify all the tables using ID.me UUID.
2. Identify appropriate people to get application specific context.
3. Determine if the lack of uniquness constraints on Accounts table has any ramifications. How do applications currently behave around separate ID.me wallets? Presumably your data would not be linked. Should it?
4. Update the tables to reference account ID after above research
5. Have teams as part of step 2 verify data integrity / regressions

Going to break this out into individual tickets along the tables/features (which is basically step 1 above).

Also: 
> Also, I think this ticket is chiefly concerned with active_record and redis backed models that might reference the UUID, but it would probably be worth taking a look at sidekiq, logging, etc too in this context.

**Comment by patrickvinograd** [comment]
Component issues cover known use cases in DB/Redis/user model. This epic should be updated to include additional issues for any other cases where we need to migrate to account_id.

**Comment by ericbuckley** [comment]
When updating the models to fetch values out of the database on account_uuid/idme_uuid, we should be careful if the model is also cached in redis as its possible that we will need to update our fetch logic in two places.  In other words the caching key and the database query will probably need to be updated.

**Comment by ericbuckley** [comment]
@patrickvinograd this isn't flushed out, and I may be thinking too naively about the problem space, but what do you think about this approach?  https://github.com/department-of-veterans-affairs/vets-api/pull/4027/files

**Comment by ericbuckley** [comment]
@patrickvinograd should we close this in favor of #7110 or put it in the ice box for someone to tackle in the future?

**Comment by patrickvinograd** [comment]
Note please keep this epic open in the Icebox category - it's still valuable work to be done at some point and there's a fair amount of research/in-progress work captured in the linked issues.

**Comment by christine-dillman** [comment]
May be needed in the future if login.gov is adopted and implemented.  With login.gov Id.me is not needed.
