### ISSUE TITLE
Full Platform Automation for EKS

### ISSUE THREAD

**Issue by BillChapmanUSDS** [department-of-veterans-affairs/va.gov-team#52910]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)

## High Level User Story/ies
As a platform architect or engineer, I need pipelined automation so I can stand up, replace, deploy or migrate an instance of EKS in a reproduceable and configuration bound way. 

## Hypothesis or Bet
If we make this change we expect to alleviate inconsistences between EKS environments and  the reliability of deployment and migration between environments. We should be able to upgrade both the platform (EKS) and the underlying virtual architecture by adding the appropriate configuration changes and kicking off the necessary pipelined deployments. This should allow us to maintain an up to date platform environment in production and help remove competiton for use of lower environments by allowing bespoke platform creation. 

## OKR
Security Response 
* Addressing the patching and rebuilding of virtual infrastrucure
* Maintaining a platform that is up to date 

Treating Staging (lower environments) as production
* We need to alleviate the shared environment issue when testing and deploying EKS (UAT) (example) bespoekMicro platform deployments can facilitate individual UAT when there is environment contension. 

Automated platform smoke tests. 
* A/B testing of new staging platform deployments with smoke test validation. 

## Definition of done
A configuration file is checked in to a repository,  A pipeline is triggered and an instance of EKS is deployed and smoke tested to the appropriate environments. 

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `Console-Services`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by npeterson54** [comment]
Closing as a duplicate of 50671
