### ISSUE TITLE
Prevent Pundit `NotAuthorizedError` from being logged to sentry

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#52935]
Pundit `NotAuthorizedError` is normally expected behavior for many users using va.gov, so it doesn't really make sense to raise Sentry errors when this happens

**Comment by dickdavis** [comment]
Is this still a concern? It looks like someone already took care of this: https://github.com/department-of-veterans-affairs/vets-api/commit/0c82df70d5286205d82b2885dc08357fe95534f6

**Comment by bosawt** [comment]
I don't see this in sentry anymore, so I think we're good
