### ISSUE TITLE
Remove V0 call to get email preferences.

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#52955]
## Description
We were previously making a call to `/vaos/v0/preferences` to get the notification preferences of a veteran when scheduling an appointment in scheduling manager. This is no longer needed since we now handle scheduling appointments in Vista.

---

## Acceptance Criteria
no calls to `/vaos/v0/preferences` should seen in our grafana or datadog logs.

**Comment by simiadebowale** [comment]
@ldelacosta - this is ready for validation.

**Comment by ajmagdub** [comment]
I verified via Datadog that we no longer see calls to the VAOS V0 preference controller.

**Comment by ldelacosta** [comment]
This was confirmed and no new issues reported. Closing out the ticket.
