### ISSUE TITLE
SOCKS access for [Michael Harlow]

### ISSUE THREAD

**Issue by ITS-mharlow** [department-of-veterans-affairs/va.gov-team#52974]
### Your Name

Michael Harlow

### Your Email

michael.harlow@va.gov

### Your Role and Team

Lighthouse Tech Lead / VA Product Ownership Team

### Product Manager (PM) name and email

Kayla Watanabe Kayla.Watanabe@va.gov

### Product Owner (PO) name and email

Janet Coutinho Janet.Coutinho@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDDjYCIfr4lKCUEC2kvndrqh03z8NT9h6z5c9EacEDvIpyioRWI1eSKGj+bPBDu1cDNbqXyNypW/gs/RnZ5M1hA79TJcXnVjAhirH898rfrdhzLVvTxzLPOcV2S001b+mtjoRHB+uxNxzfPmHKDu+lDmZ72zz60FJ7KPTU9AK9xtmcK4C8QbFST0PHQ+0Qchc4btZc6LhyR6LBnbNjqAJ2vZGOihj3wTwdGReDR5uy08VQrWin04gfsJV3cF5H8G9NoZXz5I5AfuCz4VQiic2lFMJJnmsGBNgIzC+Wrp/cI5B8NCibtB8RBnm5ASsJ12F0Tu3qHdzggh6QM5GO4IqpIVyhGoVkq8l/uMBP052qh3u1rQyn9p5m3TpQxQP5k4HaUq2wA/a9sgacDbU8DLchtLtoyMkg0CFtT/w23CSWoFtxNPmV4/hqiH2e4sqZXIA5rs5LiC0obE7pVoXp+SU3b1c5BIE3im4RZeX5P3obYwXbqr+s7PBMCpTUxJAhf3ks= VHARICHarloM@RIC-LT6075292

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by ITS-mharlow** [comment]
Please reprocess this SOCKS request. I have been added to the  VFS Team Roster. See https://github.com/department-of-veterans-affairs/va.gov-team/issues/53178

**Comment by rmtolmach** [comment]
@ITS-mharlow Our automation doesn't like the look of your ssh key. It's failing on this:
```
Run ssh-keygen -l -f ansible/roles/dsva-config/files/authorized_keys/michael.harlow@va.gov
ansible/roles/dsva-config/files/authorized_keys/michael.harlow@va.gov is not a public key file.
Error: Process completed with exit code 255.
```
Can you confirm the ssh key in this issue matches this one found here? `cat ~/.ssh/id_rsa_vagov.pub `

**Comment by ITS-mharlow** [comment]
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDDjYCIfr4lKCUEC2kvndrqh03z8NT9h6z5c9EacEDvIpyioRWI1eSKGj+bPBDu1cDNbqXyNypW/gs/RnZ5M1hA79TJcXnVjAhirH898rfrdhzLVvTxzLPOcV2S001b+mtjoRHB+uxNxzfPmHKDu+lDmZ72zz60FJ7KPTU9AK9xtmcK4C8QbFST0PHQ+0Qchc4btZc6LhyR6LBnbNjqAJ2vZGOihj3wTwdGReDR5uy08VQrWin04gfsJV3cF5H8G9NoZXz5I5AfuCz4VQiic2lFMJJnmsGBNgIzC+Wrp/cI5B8NCibtB8RBnm5ASsJ12F0Tu3qHdzggh6QM5GO4IqpIVyhGoVkq8l/uMBP052qh3u1rQyn9p5m3TpQxQP5k4HaUq2wA/a9sgacDbU8DLchtLtoyMkg0CFtT/w23CSWoFtxNPmV4/hqiH2e4sqZXIA5rs5LiC0obE7pVoXp+SU3b1c5BIE3im4RZeX5P3obYwXbqr+s7PBMCpTUxJAhf3ks= VHARICHarloM@RIC-LT6075292

This one should work. Thanks!

**Comment by rmtolmach** [comment]
@ITS-mharlow Access granted ✅ 

Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html 

Reach out in #vfs-platform-support if you have any trouble.

**Comment by ITS-mharlow** [comment]
My SOCKS proxy is working. Thanks!
