### ISSUE TITLE
AWS access for Rachal Cassity

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#52988]
### COR Name

Vilay Senthep

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### E-QIP Transmittal Date

- [x] Check this box if you have an E-QIP transmittal date.

### Your Name

Rachal Cassity

### Your Email

rachal.cassity@oddball.io

### Team, Role, and Company of the target individual

Platform Tech Team 1, Sr. Software Engineer, Oddball

### Product Manager (PM) name and email

Lainey Trahan, lainey.trahan@adhocteam.us

### Product Owner (PO) name and email

Bill Chapman, William.W.Chapman@omb.eop.gov

### Desired AWS Access

I am asking for these permissions:
- Access to full permissions (like the vsp-operations has) in the [vsp-infra-application-manifests repo](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests). This is for setting up git hub actions and helping with merging PRs. 
- Access to full permissions (like the vsp-operations has) in the [vsp-infra-argocd repo](https://github.com/department-of-veterans-affairs/vsp-infra-argocd). This is for setting up and removing test applications. 
- Access to argocd cli terminal to help with pod management
- Access to argocd app-of-apps and argocd-apps in the ArgoCD UI.

### Access Expiration

ongoing
 
### Additional Notes

Our team has been configuring EKS ArgoCD applications. I am asking for permissions because we need to be able to access these resources when debugging and trouble shooting. This will allow us to smoothly transition to sandbox and production environments going forward. I will not be needing these permissions once the entire EKS migration has been complete. 

### User must exist in a roster before AWS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [x] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by little-oddball** [comment]
eQIP - 4/21/2022

**Comment by little-oddball** [comment]
@pjholyoke @rjohnson2011 Can y'all update this one and get it to OCTODE approval?

**Comment by little-oddball** [comment]
Approval was made in the incorrect ticket. It is referenced here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/51688

**Comment by little-oddball** [comment]
Platform Team.

**Comment by rmtolmach** [comment]
I did the following:

- created a new team, `temp-eks-admin` with Lindsey and Rachal in it.
- Added their team as admins to https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests
- Added their team as admins to https://github.com/department-of-veterans-affairs/vsp-infra-argocd
- Gave increased access to ArgoCD allowing a sync of app-of-apps and app-of-projects:
    - https://github.com/department-of-veterans-affairs/vsp-infra-argocd/pull/187 ➕ 
    - https://github.com/department-of-veterans-affairs/vsp-infra-argocd/pull/188


Reminder set to remove access at the end of the quarter:

<img width="733" alt="image" src="https://user-images.githubusercontent.com/10993987/219453762-bea9c586-9a98-43f7-a2c4-2f69221d5bc2.png">

**Comment by rmtolmach** [comment]
to undo these changes, follow steps outlined in Lindsey's: https://github.com/department-of-veterans-affairs/va.gov-team/issues/53244#issuecomment-1433803096

**Comment by rmtolmach** [comment]
Extended access approved: https://dsva.slack.com/archives/C04CYC4LMU6/p1680529293989379?thread_ts=1680526843.664379&cid=C04CYC4LMU6
And reminder set:
<img width="569" alt="image" src="https://user-images.githubusercontent.com/10993987/229529131-5f4cea40-87a7-4c46-8366-5b16320f7a9d.png">

**Comment by rmtolmach** [comment]
Extended access approved:
https://dsva.slack.com/archives/C04CYC4LMU6/p1683122537159329?thread_ts=1682946024.814299&cid=C04CYC4LMU6

And reminder set:
https://dsva.slack.com/archives/C04CYC4LMU6/p1683122724000169

**Comment by rmtolmach** [comment]
Three more months approved:
https://dsva.slack.com/archives/C04CYC4LMU6/p1691505269557919?thread_ts=1690894830.998669&cid=C04CYC4LMU6

Reminder set:
https://dsva.slack.com/archives/C04CYC4LMU6/p1691513624490369
