### ISSUE TITLE
[Bug][Letters App] Users cannot download letters

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#52982]
## What happened?
Users are getting a "didn't download" error when they attempt to download their VA Benefits Letters via the Letters App. 

![image (17).png](https://images.zenhubusercontent.com/6113fbb753613f267009ce32/7dc877a5-863e-4978-bed5-94c620dfa4db)

## Specs:
- Device: (e.g. iPhone 8, Macbook): unknown
- Browser: (e.g. Firefox, IE 11): unknown
- Test User _(if applicable)_:

## Steps to Reproduce
- URL: https://www.va.gov/records/download-va-letters/
- attempt to generate and download letter

## Desired behavior
when button is clicked to download letter, it generates and downloads a pdf file

## Acceptance Criteria
- [ ] Users are able to download their letters
- [ ] The error message no longer appears. 

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by samcoforma** [comment]
What we know so far:

![image](https://user-images.githubusercontent.com/105806934/216388716-43e98458-86d4-4040-8703-d6daa2cba64a.png)

1) A 200 response is being returned
2) PDF data is being returned in the response body
3) The browser isn't downloading that data into a local file
4) letterDownloadStatus is being set to "failure" in Redux for whichever letter type was requested to be downloaded

**Comment by ITS-mharlow** [comment]
![image](https://user-images.githubusercontent.com/32102133/216398880-d3009602-3c34-40b8-8e83-0d2f1787081a.png)
The PDF endpoint is pointing to the Lighthouse letter API. However, the list of letters is still using the EVSS API. If you change the PDF URL back to the EVSS API, the downloads should start working.

**Comment by samcoforma** [comment]
@ITS-mharlow In staging, that endpoint returns a 200, also in vets-api, it looks like it's still set to use EVSS: https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/controllers/v0/letters_controller.rb#L43

Q: Are you getting that 502 consistently in production? We get 200s from that endpoint in staging (along with the PDF data returned in the response body), but are still having a download issue in the browser consistently.

**Comment by ITS-mharlow** [comment]
The 502 in the console appeared for the same request that had a 200 for the PDF.

**Comment by samcoforma** [comment]
Update (via @jerekshoe):

https://dsva.slack.com/archives/C5AGLBNRK/p1675363991467109?thread_ts=1675352034.193369&cid=C5AGLBNRK

> this was identified as an issue with some of the FE platform code and the platform team is working on a fix. Also, this issue was not isolated to the letter generator application, and affects any application on [va.gov](http://va.gov/) that downloads PDFs or other non-JSON data from vets-api

**Comment by jerekshoe** [comment]
This is the PR that platform is working on currently to fix the issue: https://github.com/department-of-veterans-affairs/vets-website/pull/23263/files
