### ISSUE TITLE
Visual bugs identified during travel reimbursement testing

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#52998]
# Issues

**[Found issue 1]** Travel pay: Your appointments page. (Refer to the attached screenshot  below (e.g., step7.png))
- The header shows with a colon. There shouldn't be a colon in the title (You appointments: --> You appointments).
- The font style for the sub-title looks to be using body style. It should be Bitter-Regular, 16px

**[Found issue 2]** Travel pay: Confirmation page (Refer to the attached screenshot  below (e.g., step7))
- The font style for the sub-title looks to be using body style. It should be Bitter-Regular, 16px

**[Found issue 3]** Travel pay: Travel pay checked in without travel pay (Refer to the screenshot below (e.g., step9.png))
- The font style for the sub-title looks to be using body style. It should be Bitter-Regular, 16px

**[Found issue 4]** Travel pay: (Refer to the screenshot below (e.g., step10.png))
- The font style for the sub-title looks to be using body style. It should be Bitter-Regular, 16px

**[Found issue 5]** Travel pay: (Refer to the screenshot below (e.g., step10_2.png))
- The font style for the sub-title looks to be using body style. It should be Bitter-Regular, 16px

**Step 7.png**
![Step7.png](https://images.zenhubusercontent.com/6155d02ed6dc2cbaa5d23b32/3113439b-552e-4999-9205-557512055973)

**Step 9.png**
![Step9.png](https://images.zenhubusercontent.com/6155d02ed6dc2cbaa5d23b32/9a101314-3969-4d17-96e8-ae4c7c213606)

**Step 10.png**
![step10.png](https://images.zenhubusercontent.com/6155d02ed6dc2cbaa5d23b32/f1bc750c-c034-4c36-ab67-06abc09b24ea)

**Step 10_2.png**
![Step10_2.png](https://images.zenhubusercontent.com/6155d02ed6dc2cbaa5d23b32/0e2e0b54-8830-410b-ab39-9164dfa81c15)

**Comment by zach-park** [comment]
Updated the description of the issue.

**Comment by loripusey** [comment]
combining these fixes with 53189 per eng refinement
