### ISSUE TITLE
[Feature] Remove V0 code from vets-website.

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#52991]
The goal of this epic is to get rid of V0 code in `vets-website`.

This includes:

- [ ] Getting rid of V0 endpoint calls in `vets-website`.
- [ ] Getting rid of V0 transformers in `vets-website`.
- [ ] Getting rid of V0 feature flags.
- [ ] Getting rid of V0 e2e tests.
- [ ] Getting rid of V0 unit tests.

**Comment by JunTaoLuo** [comment]
@simiadebowale will file additional tickets to clean up v0 logic after confirming v0 logic is no longer needed.

**Comment by ldelacosta** [comment]
No additional work is needed. Closing out the feature. cc: @simiadebowale @JRRoof @Bren22va

**Comment by JunTaoLuo** [comment]
Woooooot!
