### ISSUE TITLE
Staging: Missing secrets

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#53006]
**PROBLEM STATEMENT**
The folder `/srv/vets-api/secret/uat/` doesn't exist in EKS. [These six items](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/vets-api-server-vagov-staging.yml#L253-L287) need to be visible in EKS. If they were in Parameter Store, it would be easy, but most of them aren't and can't be added because they're too large. So. Figure out another way. Add them to the helm chart and access them using [.Files](https://helm.sh/docs/chart_template_guide/accessing_files/)? 

**LINK TO SLACK**
Thread in [#eks-migration-support](https://dsva.slack.com/archives/C04M7T1CZAS/p1675270952096209)
Original thread from [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1/p1675270560298079)

**ACTION ITEMS TO RESOLUTION**
- [ ] Figure out how to access the files
- [ ] Create another mount path and then update secrets.yaml

**NOTES FOR PROD**
This same thing will need to be done for prod.

**Comment by rmtolmach** [comment]
the files we need access to are located here: https://github.com/department-of-veterans-affairs/devops/tree/master/ansible/deployment/config/vets-api/vbms

* The contents of `/deployment/config/vets-api/vbms/vetsapi.uat.client.vbms.aide.oit.va.gov.p12`
 has been base64 encoded and stored in Parameter Store at `/devops/certificates/client.vbms.aide.oit.va.gov.p12`. 
* `vetsapi.client.vbms.aide.oit.va.gov.key` was already in param store, so I added a lookup for that.
* It the other four items we need to deal with. I tried encoding them, but the encoding gibberish is still too big for AWS. 

For Monday:
* Search Slack for history on this. I'm sure Jeremy or Matt thought about this and maybe tried some things. 
* Try to get `.Files` to work.

**Comment by LindseySaari** [comment]
@rmtolmach There's an advanced option for parameter store that can store "bigger" values. Working on the `/secrets/uat/` currently.

**Comment by rmtolmach** [comment]
All secrets except the xml have been added to paramstore. PR for all of the secrets _except_ the XML (still too big) is up. Linked ☝️

The XML. It has 1127 characters and the max for Advanced Param Store is 8192. Encoding it via `base64` makes it even longer.

**Comment by rmtolmach** [comment]
Forgot to add this to the last sprint. Also forgot to close it and respond to Lainey! Doing those things now.

Rachal also helped close this ticket. See these PRs [using this query](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pulls?q=is%3Apr+is%3Aclosed+author%3ARachalCassity+saml) from Feb 8-9.

@laineymajor I think we're good! The `/srv/vets-api/secret/uat/` folder existed in staging vets-api-server in BRD, but it doesn't exist in prod vets-api-server. This is output from a BRD production vets-api-server showing that the `uat` folder doesn't exist:
```
[root@ip-10-247-33-74 /]# ls /srv/vets-api/secret/uat/
ls: cannot access /srv/vets-api/secret/uat/: No such file or directory
```
