### ISSUE TITLE
OOB Deploy Request for VA Benefits Letter Download Tool

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#53001]
# Instructions
Fill out Details of need and the PRs related to OOB sections below.

## PRs Related to OOB
- Please provide the list of PRs related to the need for this OOB Deploy
   > https://github.com/department-of-veterans-affairs/vets-website/pull/23263
   > https://github.com/department-of-veterans-affairs/vets-website/pull/23263/files

## Active Daily Users Impacted
- How many active users are impacted at this time and day.
>  Not exactly sure on the number but there were 600,000+ transactions that took place in the last 30 days
## Has fix been confirmed in Staging? maybe?
- [x] Yes
- [ ] No

## Description
- Please provide the details/reason for the OOB Deploy
   > The download VA benefits letter tool has been down for over 24 hours. Now that the fix has been identified, it should be deployed to production ASAP to mitigate the impact to Veterans and also to contact centers who have been called on this issue. 
   
## Verify The following
 - [x] The OOB Deploy Requests is after the 2pm EST cutoff for regular deploy - [Deployment Policy](https://vfs.atlassian.net/wiki/spaces/SUP/pages/1279787009/Deployment+Policies) and [Deployment Schedules](https://depo-platform-documentation.scrollhelp.site/developer-docs/Deployments.1844641889.html)
 - [x] The OOB Deploy Requests is critial and must be resolved before the next automated deploy.

*Performed by Platform SRE team*
 - [x] PagerDuty OOB Deploy Incident Opened
 - [x] OCTO-DE staff acknowledgment of Request
 - [x] Notification is posted in the appropiate Slack support and team Channels
 - [ ] Infrastructure/Operations has acknowledge the Requests
 - [ ] Security Team has Reviewed the requests
 - [ ] An Incident Post Mortem is created within two business days

 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-product-support

**Comment by mchelen-gov** [comment]
This is approved pending:
1) Completion of PR
2) PR review by Platform
3) Fix is tested in Staging

**Comment by asg5704** [comment]
✅  PR is completed 
✅  PR reviewed by Platform
🛑  Fix isn't tested or deployed to staging

**Comment by rmessina1010** [comment]
The original OOB did not go through as the fix  would not deploy to staging, see: https://app.zenhub.com/workspaces/platform-tech-team-support-634ebbcc35e2bc0015b382fd/issues/gh/department-of-veterans-affairs/va.gov-team/53057
(@asg5704 let me know if there are any details you need on the above for the post mortem)
However, once that was corrected, we were able to push this PR through along with the daily deploy. Closing this and related tickets.
