### ISSUE TITLE
Staging: Helm101

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#53005]
**PROBLEM STATEMENT**

**LINK TO SLACK**

**ACTION ITEMS TO RESOLUTION**

**NOTES FOR PROD**

**Comment by LindseySaari** [comment]
helm101 needs to be removed in a particular order. This still needs to be removed. @considerable Would you mind revisiting please?

**Comment by laineymajor** [comment]
And let's please document the order @considerable 
Thanks!
