### ISSUE TITLE
[Mocked Auth] Mocked Authentication for Localhost and Development stacks

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#53015]
This epic encapsulates the work proposed here: [proposed mocked auth](https://lucid.app/lucidchart/74ff62d0-4d71-4184-a056-0557b33c2764/edit?invitationId=inv_341a2a96-704e-4767-9939-e988a66f4a2c). This proposal describes a feature where developers are able to select a new `mocked authentication` feature on the Unified Sign in Modal (only on localhost and dev.va.gov). After selecting `mocked authentication`, developers will be able to select what credential provider to mock authentication as, and to define a payload representing the mocked credential user information. The `vets-api` backend will then communicate with this mocked authentication entity, as if it were a 'real credential provider', and enable a user to authenticate with the mocked data.

Mocked Authentication will work for the Sign in Service method of authentication, on the localhost and development stacks only. It will be accessible through the unified sign in page, as an extra button available only on those stacks. Additionally, there will be a way to utilize the mocked authentication feature using only an API based flow, which should enable automated testing on dev stack to utilize mocked authentication to test arbitrary authenticated routes

**Comment by claytonzook** [comment]
Feature requests for future iterations of Mocked Auth:
- on the select profile page, make the user attributes more easily readable (plain text)
- when there is an error signing in, make error more easily understandable (plain language)
