### ISSUE TITLE
[Platform Support] Link incident response (IC) playbook to maintenance window documentation 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#53024]
## Description
As part of Platform Support and/or incident response duties, Platform Operators need to know how to create and manage maintenance windows. 

## Background 
- Maintenance windows are created to recognize planned downtime and avoid unnecessary alerting from services that are expected to have maintenance performed. 
- Maintenance windows can be created in PagerDuty to automatically silence notifications from associated services
- Follow-up communication is necessary to communicate maintenance windows with affected parties  

## Resources 
- [VA.Gov Incident Playbook ](https://vfs.atlassian.net/wiki/spaces/ECP/pages/1565294641/VA.Gov+Incident+Playbook)
- [Create Maintenance Window in PagerDuty](https://vfs.atlassian.net/wiki/spaces/OT/pages/2434433157/Create+Maintenance+Window+in+PagerDuty)

## Acceptance Criteria
- [x] The VA.Gov Incident Playbook is linked to "Create Maintenance Window in PagerDuty" in the appropriate place

**Comment by mynar7** [comment]
Added the following to the IC playbook: https://vfs.atlassian.net/wiki/spaces/ECP/pages/1565294641/VA.Gov+Incident+Playbook#Check-Downstream-Services

**Comment by jhouse-solvd** [comment]
@mynar7 - Great job! I made a couple of small, minor formatting changes. But I think this is good to go. 

The acceptance criteria have been met. This issue can be closed.
