### ISSUE TITLE
Add react widget to Supplemental Claims page and publish page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#53037]
## Issue Description

As part of the support of the online form for Supplemental Claims, we need to add a react widget to our [Supplemental Claims](https://www.va.gov/decision-reviews/supplemental-claim/) page as an entry point when they are launching the tool to less than 100%.

We've already provided the product team with the content, so once we have the react code we can add it to our page and publish once they give us the go-ahead.

After the tool is launched we'll create a new ticket to remove the widget and put the form link directly on the page. 

## Tasks
- [x] Add react widget to page (Katherine)
- [x] Copyedit (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] Widget is on live page

**Comment by RLHecht** [comment]
@katherine-fung the react code to put onto our page is: supplemental_claim

Let me know if you need help setting this up and I can screen share with you when you're ready.

**Comment by RLHecht** [comment]
@katherine-fung Hold off on this for now. I just tried adding it to the page and it's not rendering correctly.

**Comment by RLHecht** [comment]
The react widget is now correct but I'm going to move this ticket to the backlog. We should only add this to the page as the tool is getting closer to launch so we don't need to worry about putting it in and taking it out if we have to make other changes to the page.

**Comment by RLHecht** [comment]
@katherine-fung this is now ready to add in again but we won't publish until they launch. Once the widget is in @megzehn can do a full copyedit on the page.

**Comment by katherine-fung** [comment]
The widget is on the page now. Thanks, @RLHecht, for showing me how to add it! 

@megzehn - the page is ready for a full copy edit: 

http://preview-prod.vfs.va.gov/preview?nodeId=3011
