### ISSUE TITLE
BE | Profile | Gender Identity | QA Testing for Name Changes

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#53038]
## Background
VA Profile is changing gender identity name values.  These changes should not impact VA.gov Profile since the names are hard coded on the FE and the BE uses the codes.

Here is the new list of names (the codes remain unchanged):

| Code | Name |
| ----- | ----- |
| M | Man |
| F | Woman |
| TM | Transgender Man |
| TF | Transgender Woman |
| B | Non-Binary |
| N | Prefer not to answer |
| O | A gender not listed here |

I will run through some tests with Ian McEwan on 2/14 to ensure that everything lines up in staging.

## Tasks
- [ ] Run tests with Ian McEwan

## Acceptance Criteria
- [ ] All tests pass

**Comment by tpharrison** [comment]
@Samara-Strauss @BerniXiongA6 

Even though we don't anticipate any issues with the changes listed above, I want to make sure that I'm around when they are deployed (just in case).  

I spoke with Josh Lindsey and let him know that I'm OOO next week.  He was okay with waiting until I'm back to deploy to their QA environment.  I will run some quick tests on 2/14 with Ian McEwan to confirm that everything works. It shouldn't take more than 30 mins.

**Comment by Samara-Strauss** [comment]
@tpharrison thank you for this! I will add this to next sprint so we don't lose track of it.

**Comment by tpharrison** [comment]
Reached out to Ian McEwan today - he informed me that the GI changes are not in staging yet.  He will reach out when he is ready test.

**Comment by tpharrison** [comment]
@Samara-Strauss 

Ian reached out and let me know that staging is ready.  I ran some tests and everything looks good.  But I noticed that these changes may affect the mobile team so I reached out the Andrew Herzberg to inquire.  Andrew thinks there might be some dependencies on name values so he is checking with his team.  I'll wait to hear back from him before responding to Ian.

**Comment by tpharrison** [comment]
Tested in staging - no issues.

Followed up with mobile team - they don't have any issues, but have [opened a ticket](https://app.zenhub.com/workspaces/va-mobile---backend-61d75d03a7505500147ec7f6/issues/gh/department-of-veterans-affairs/va-mobile-app/4824) to update the name values for consistency.
