### ISSUE TITLE
Create new mock credential service to complete Sign in Service auth flow

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#53049]
* Mocked Credential Service
	* This will match the same format as the `idme` and `logingov` services (`lib/sign_in/logingov/service.rb`)
	* This will be described with namespace: `SignIn::Mock::Service`
	* This will have the following functions:
		* `render_auth`
			* This will render a form that the `vets-website` frontend can use to redirect to the mocked credential frontend page
			* The function will render the `oauth_get_form` with the following params
				*  `state`
					* This is created and given to the function by `SignInController`
				* `redirect_uri`
					* This is the redirect uri back to `v0/sign_in/callback`
			* Mostly try to follow the structure of the same function in `SignIn::Idme::Service`, or `SignIn::Logingov::Service`
		* `normalized_attributes`
			* This will take raw credential info data and normalize it into attributes 
			* Mostly try to follow the structure of the same function in `SignIn::Idme::Service`, or `SignIn::Logingov::Service`
			* Will need to normalize attributes for `idme`, `logingov`, `dslogon`, and `mhv` credentials
		* `token`
			* This will take the code created from the `/mock/authorize` route and return a ‘token’
			* The returned token can just be the code that was given, but packaged up like an access token:
				* response: ` { access_token: <code> }`
		* `user_info`
			* This will take the `token` returned from `token`, and return user credential info
			* Just check the redis entry created in `/mock/authorize`, using the given ‘access_token’ code
			* We should be able to return the raw redis entry

**Comment by mjconw3** [comment]
@bosawt ...Mike and I have reviewed this ticket, added the appropriate label and sprint and have closed. Moving forward we will be adding acceptance criteria to all tickets to make review easier (not a problem for now while you all were managing your own tickets)
