### ISSUE TITLE
Copyedit and plain language review of Lovell TRICARE taxonomy

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#53043]
## Issue Description

As part of the work for the Lovell TRICARE Health Care launch, we need to review the taxonomy to make sure they meet VA.gov's plain language and style standards. We should focus on the TRICARE description column of the spreadsheet but if there are plain language edits that need to be made to the current VAMC description, we can suggest those too.

FIle to work from: [https://app.zenhub.com/files/133843125/8df69f14-6637-498d-aab0-4f9c4adecf9d/download](https://app.zenhub.com/files/133843125/8df69f14-6637-498d-aab0-4f9c4adecf9d/download)

## Tasks
- [x] Copyedit and review for plain language (Megan)

## Acceptance Criteria
- [x] Descriptions are written in plain language and meet VA.gov style standards

**Comment by megzehn** [comment]
Thanks @RLHecht!

Confirming that I revised these descriptions for plain language and copy edited them. 

[Tricare_Taxaonomy_descriptions_copyedited_mz.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/10677191/Tricare_Taxaonomy_descriptions_copyedited_mz.xlsx)

Based on the list of descriptions on the Lovell page, I also recommend tweaking/revisiting these standard descriptions:

    - Adaptive sports
    - Allergy, asthma, and other immune system changes
    - Caregiver support
    - Colon and rectal surgery
    - Community engagement
    - Critical care
    - Dental/oral surgery
    - Gynecology
    - Infectious disease
    - Laboratory and pathology
    - Neurosurgery
    - Otolaryngology
    - Pharmacy
    - Polytrauma
    - Rehabilitation and extended care
    - Rheumatology
    - Social work
    - Urology
    - Wound care and ostomy

**Comment by RLHecht** [comment]
Thanks @megzehn . I emailed the spreadsheet to Danielle and let her know about the changes to the other descriptions. Going to close this!
