### ISSUE TITLE
Create new route to mock an authorization attempt with a CSP

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#53040]
- [x] Create a new controller, Naming will be `/mock/authorize`, `MockedAuthorizationController`
- [x] The route will be scoped to ONLY `localhost` and `development` stacks (make sure this is defined in the `routes.rb` file)
- [x] The route will be a `GET`, and will accept a request like: `http://localhost/mock/authorize?credential_info=<credential_info>`
  * Params are:
    * `credential_info`
      * This is a serialized JSON blob representing the mocked credential information (varies depending on credential)
  * Response is:
    * `<random_value_code>`
      * This is described below
- [x] Once called, `/mock/authorize` will:
  * create a random value: `SecureRandom.hex`
  * store `credential_info` in a temporary redis (TTL suggestion: 5 minutes, but any reasonable default will do), with the ‘random value’ as the key
  * Return the created random value

**Comment by bramleyjl** [comment]
Confirmed mocked auth route is returning an auth code on dev

![image.png](https://images.zenhubusercontent.com/5f99b8d1032b9709f1c7e051/c3743c37-5e52-4943-956a-929fd5658980)
