### ISSUE TITLE
Design Intent  - IA Feedback -  Forms-Digitize, Form 26-4555

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#53071]
## VFS acceptance criteria
- [x] Let Platform know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [x] VFS team closes the ticket

## Thoughts/questions
* By midpoint you should [submit a request](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request) to work with sitewide content + IA (cc @mnorthuis) to develop a plan for the IA of these pages. It would be helpful to get a sense of the high-level plan for this (and the additional 10 "low hanging fruit" forms we'll be tackling first). Here are IA areas of concern:
   * Entry points:  work on entry points, including any static pages necessary to situate this form into the global navigation. You will need to think about cross-linking opportunities and and left-nav work as well. There is a precedent set from other VA applications (e.g. [Healthcare](https://www.va.gov/health-care/how-to-apply/)) to have a trio of pages: **how to apply**, **apply now**, and **after you apply**. Will this form follow that cadence? 
   * All scenarios: this design is showing the happy path only, at midpoint we will want to see all possible scenarios 
   * Verbiage: “Your application has been saved” message has slightly different language than what appears on other applications. Try to match language when possible.
* This is only the Design Intent and I would have saved this reminder for Midpoint, but Find-A-Form search is on my mind already. Matt mentioned your team possibly taking this over and handling link replacements as these forms are digitized and go live. For now, the PDF versions are the default indexed link in that search tool - those links should be updated with modernized/digitized versions as they become available.

## Feedback
- Practice areas will document their feedback following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback).

**Must:**
* Step 5 of 6: “Is there any other medical information that you could tell us that would help you qualify for the grant”? 
This language is confusing. How would the Veteran know what kinds of additional medical information would help them qualify for a grant? Provide some examples to help guide Veterans to what information would be useful here.

**Should:**
* The page title (H1) is quite long (76 characters). It's not a deal-breaker, but making it succinct would be beneficial. General [VA guidance](https://design.va.gov/content-style-guide/page-titles-and-section-titles) is to develop H1s with 52 characters or less when possible. The sitewide content + IA team can be helpful here. At a high level, a more general name (which should be closely matched in other IA navigational elements: breadcrumbs, left-nav) such as "Apply for disability grants" may work nicely. More specific language can be included directly beneath the H1 naming the actual grant names from the application (actually, you already have this in Sketch files!)

**Consider:**
* In Step 3 of 6: Veterans are presented questions about whether or not they have ever applied to two grants: "specially adapted housing" & "home improvement and structural alteration grant." The latter name is new language - it has not been introduced yet within this application. If it is a synonym of the grants this application references in the H1, please sync that language. If it is different, some contextual information describing the "home improvement and structural alteration grant" could be beneficial.

## Platform directions
- Remove the governance-team label
- Update "Issue Title"
- Link to collab cycle Request epic
- Add your feedback
- Remove the CC-Request label (only if you created the ticket using the New Issue link from the Collaboration Cycle Reviews board)
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review QA Only**: VFS PM, yourself (optional)

**Comment by jeana-adhoc** [comment]
### For the must feedback, I updated the question to read as follows:
**Please describe any service-connected conditions you may have due to your military service. If you have a VA Decision Rating, please include that as well.**

With this additional info:
**Why do I need to provide this information?**
A service-connected condition is a disability related to an injury or disease that developed during or was aggravated while on active duty or active duty for training. VA also pays disability compensation for disabilities resulting from injury, heart attack, or stroke that occurred during inactive duty training.

This information helps establish your basic eligibility for a Specially Adapted Housing Grant. 

### For the Should feedback, I updated the form title to be
**Apply for a Specially Adapted Housing Grant** instead of Apply for a Specially Adapted Housing Grant or Special Home Adaptation Grant

### For the consider feedback, I updated the question to read:
**Have you previously applied for a special home adaptation grant?**

**Comment by sterkenburgsara** [comment]
@jeana-adhoc Those look like wonderful updates and I have no suggested edits. Thank you so much for being so thorough!
