### ISSUE TITLE
Sitewide Content review of Form 26-4555 from Digitize Team

### ISSUE THREAD

**Issue by tbaker1026** [department-of-veterans-affairs/va.gov-team#53077]
## What does your team need support for? Check all that apply.
- [x] Launching one or more unauthenticated pages, online forms, apps, or tools on VA.gov
- [ ] Making revisions to one or more existing VA.gov pages
- [ ] Something else 
 
 *Give a brief description of what your team needs support with.*
- Determining where the Veterans can find the form and review the content; How to deliver/format entry point information
- Plain language improvements to the form (improving from what is in the PDF)
- Guidance on best way to proceed and receive content support/help

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [x] Yes
  - [ ] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
## When do you expect to launch your product to 100% of users?
Not sure yet, this is our first form we are digitizing so don't have an exact date yet.
  
*Please provide an estimated date so our team can create other relevant tickets.*
Beg March Target
  
## Supporting artifacts
*Please provide supporting artifacts as available.*

- Link to product outline: [Product Outline](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/26-4555/Product%20Outline.md)
- Link to or attach user flows:
- Link to prototype or mockups: [Sketch Files](https://www.sketch.com/s/55cd7fae-eca1-4515-b460-0779f54eff60/p/5C807B24-B423-4109-9BC4-7230F0E21AEB/canvas)
- Link to any epics/issues that may be helpful: [Source of truth](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/26-4555/UX/sourceoftruth.md)

## Will this work be going through the Collaboration Cycle?
- [x] Yes 
- [ ] No

## When does this work need to be done?
- Estimated launch date:
- Estimated staging review date:
- Content and IA work needed by: 

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [x] No, but I'd like to schedule time to talk about this request
- [ ] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: Matthew Dignee
-	Product manager: Tricia Baker
-	Designer: Jeana Clark
-	FE engineer: Tze Lei
-	Product/team Slack channel: product-teams-forms

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by coforma-terry** [comment]
**Noting here for reference** - confirming no accessibility help needed.

**Comment by jeana-adhoc** [comment]
Here are the two documents I referenced on the call this morning
[Source of truth for 26-4555](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/26-4555/UX/sourceoftruth.md)

[Content Consideration Checklist](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/UX/content-consideration-checklist.md)

The step 4 question, "Please select all service-connected conditions you may have due to your military service:" is the newly revised question that I would appreciate additional support on. The list of disabilities/conditions that a user can select from comes from this [benefits page](https://www.benefits.gov/benefit/4733) 

Let me know if you have any questions!! Thank you!

**Comment by RLHecht** [comment]
Thanks, @jeana-adhoc! Should we capture any global changes we're recommending on this checklist?

**Comment by jeana-adhoc** [comment]
@RLHecht - Yes please.

**Comment by jeana-adhoc** [comment]
@RLHecht & Team - I've created another document to outline the heading structure for each of the form pages. We'd like to start considering consistent heading structure for a few reasons... 1. prep for future H1 becoming the question. 2. Consistent experience across the pages of the forms. To that end, not all of my pages have the consistent heading structure now.  I created this [doc to outline the issue](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/26-4555/UX/headings.md). I would love your support for helping identify subheads/h3 text for those pages that don't have it now.  I'm happy to talk more about this if you have questions.

**Comment by jennymayoco** [comment]
Hi @tbaker1026 and @jeana-adhoc - we are still finalizing H1 with content, guidance notes for appending /introduction to applications, as well as entry points, but we wanted to pass on the placement and breadcrumb for this form. Let us know if you have any questions or would like a walk-through detailing any flows or entry points.

![Screenshot 2023-03-02 at 11 06 48 AM](https://user-images.githubusercontent.com/122128479/222500828-3781f9cd-82f3-43b4-80b2-280aa357e326.png)
![Screenshot 2023-03-02 at 12 03 06 PM](https://user-images.githubusercontent.com/122128479/222513360-f2884612-6cd5-430a-b80f-4b8e22fb0fa1.png)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @jeana-adhoc. @megzehn is going to do a copy edit pass on this. But in the meantime, I wanted to share the [content doc](https://dvagov-my.sharepoint.com/:w:/g/personal/danielle_thierry_va_gov/EY7rJ9h1-ldLhO2nqW6gIxYB9I_yP1hFaL9bmwy3ZI19XA?e=2qet9t) with my comments.

**Comment by jeana-adhoc** [comment]
Thanks @DanielleThierryUSDSVA ! I've left some comments in the doc for you and your team.

**Comment by jennymayoco** [comment]
Hi everyone! We have finalized our [IA review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/housing-grants-application.md) and wanted to pass along to the team. 

Let us know us if you have any questions!

**Comment by megzehn** [comment]
Hi @jeana-adhoc. I finished reviewing the [content in the doc. ](https://dvagov-my.sharepoint.com/:w:/g/personal/danielle_thierry_va_gov/EY7rJ9h1-ldLhO2nqW6gIxYB9I_yP1hFaL9bmwy3ZI19XA?e=2qet9t). Let me know if there are any questions! 

Noting that I put a question in there about the heading for Step 4 of 5.

**Comment by jeana-adhoc** [comment]
Hi @megzehn ! Thanks. I replied in the word doc, but I'll reply here too. There's a typo in the doc. The "Service Connected Conditions" Should be a separate step. It's not part of a conditional, so there are 6 steps in this form. 

Step 1 of 6: Your personal information
Step 2 of 6: Your contact information
Step 3 of 6: Your past applications
Step 4 of 6: Your current details (But could it be living situation)?
Step 5 of 6: Service-connected conditions (But then that's the same as the h3 - in my mockups right now I just have Additional Information" for the chapter title.
Step 6 of 6: Review information

Feel free to ping me on slack if you'd like to talk more!

**Comment by megzehn** [comment]
Got it! Thanks for clearing that up. I adjusted my edits. This is what I have now for the steps with Danielle's edits incorporated. Let me know if you have any concerns or want to discuss!

Step 1 of 6: Your personal information
Step 2 of 6: Your contact information
Step 3 of 6: Your past applications
Step 4 of 6: Your current living arrangement
Step 5 of 6: Your conditions 
Step 6 of 6: Review information

**Comment by RLHecht** [comment]
I think this is good to close but please reopen if still needed.

**Comment by tbaker1026** [comment]
@RLHecht, we don't have a final launch date for production but we are planning on doing staging review on 3/24/2023.  How much advance notice do you need to make the site updates?

**Comment by RLHecht** [comment]
@tbaker1026 if this is launching incrementally, we will only need to place the react widget on our static page as the entry point. We don't do any of the left nav work or other entry points until the form is at 100% since that will show to everyone. We can add the ticket to this sprint to provide you with the content for the widget, which your team will need to build and give us the code for. We could give that to you early next week.

**Comment by tbaker1026** [comment]
@RLHecht Do you update the staging pages with the new online form, or just wait until it is in production?
https://staging.va.gov/housing-assistance/disability-housing-grants/how-to-apply/

https://staging.va.gov/housing-assistance/disability-housing-grants/adapted-housing/

**Comment by RLHecht** [comment]
@tbaker1026 Our team doesn't work in staging since the static pages are in Drupal. So those entry points to the new form wouldn't show until they're on production.

**Comment by megzehn** [comment]
Hi @tbaker1026, 

Here's the copy edited version of the react widget copy. Flagging that I updated the action link URL after @jennymayoco confirmed we need "form" in it. [As reflected in the updated IA specs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/housing-grants-application.md), the CTA URL should be: /housing-assistance/disability-housing-grants/apply-for-grant-form-26-4555
 
[Adaptedhousing_reactwidget_copyedit.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/11052940/Adaptedhousing_reactwidget_copyedit.docx)

Let me know if there are any questions! Thanks!

**Comment by tbaker1026** [comment]
@RLHecht - Here is the link for the react widget - Our static page can be found in vets-website at:  
src/applications/static-pages/simple-forms/26-4555/

**Comment by RLHecht** [comment]
Thanks @tbaker1026 once you have the react code for the widget please let us know so we can add it to our drupal page.

**Comment by tbaker1026** [comment]
@RLHecht here is the code - [https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/static-pages/simple-forms/26-4555](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/static-pages/simple-forms/26-4555) - we are still in the readiness review, do you want me to ping you when that has been completed?
