### ISSUE TITLE
MDT- Introduction page- 508 accessibility 

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#5308]
## User Story:
As a disabled veteran, I need to be able to easily access the introduction page's content so that I can reorder my hearing aid supplies

## Tasks
- [ ] Meet with 508 team to determine best accessibility practices
- [ ] Apply 508 code elements to the page 

## Acceptance Criteria:
The veteran personal info step must meet 508 compliance standards.
Please refer to the [508 Checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/508-checklist.md)

## Next Steps 
-

**Comment by jenstrickland** [comment]
Please use the issue ticket template linked at https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/vsa-accessibility-review-process.md#development-reviews to request reviews.

**Comment by bradl3yC** [comment]
Axe check revealed only form system related heading nesting warnings and color contrast
