### ISSUE TITLE
Remove getConfirmedAppointments function for V0

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#53080]
In the var directory (`vets-website/src/applications/vaos/services/var/index.js`), we have a list of v0 calls we want to get rid of. 
This ticket focuses on getting rid of any usage of:
`getConfirmedAppointments`.

---

## Acceptance Criteria
- [ ] Fix PastAppointmentsListV2 unit test
- [ ] Fix UpcomingAppointmentsList unit test
- [ ] Fix AppointmentListV2 unit test
- [ ] Remove appointment v0/v2 comparison tests
- [ ] Fix BackendAppointmentServiceAlert unit test

**Comment by ldelacosta** [comment]
Work completed. Closing out the ticket.
