### ISSUE TITLE
Remove getCancelReasons function for V0

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#53103]
In the var directory (`vets-website/src/applications/vaos/services/var/index.js`), we have a list of v0 calls we want to get rid of. 
This ticket focuses on getting rid of any usage of:
`getCancelReasons`.

---

## Acceptance Criteria
- [ ]  No reference to `getCancelReasons` anywhere in `vets-website`.
- [ ]  Remove all mocks associated with this api function (If any).
- [ ]  Remove unit test for this function (If any).
- [ ]  Remove e2e tests for this function (If any).

**Comment by ryanshaw** [comment]
Moving this temporarily to blocked as the amount of tests impacted is large.

**Comment by ldelacosta** [comment]
This ticket will resume after we have completed other v0 clean up. cc: @simiadebowale

**Comment by ryanshaw** [comment]
Closed with this PR: https://github.com/department-of-veterans-affairs/vets-website/pull/24624/
