### ISSUE TITLE
Remove getCommunityCareFacility function for V0

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#53100]
In the var directory (`vets-website/src/applications/vaos/services/var/index.js`), we have a list of v0 calls we want to get rid of. 
This ticket focuses on getting rid of any usage of:
`getCommunityCareFacility`.

---

## Acceptance Criteria
- [ ]  No reference to `getCommunityCareFacility` anywhere in `vets-website`.
- [ ]  Remove all mocks associated with this api function (If any).
- [ ]  Remove unit test for this function (If any).
- [ ]  Remove e2e tests for this function (If any).

**Comment by ldelacosta** [comment]
This ticket will resume after we have completed other v0 clean up. cc: @simiadebowale

**Comment by vbahinwillit** [comment]
@simiadebowale, @ldelacosta - Suggesting that this ticket be closed since this function is still used and is not v0.

```
export function getCommunityCareFacility(id) {
  return apiRequestWithUrl(`/v1/facilities/ccp/${id}`, {
    method: 'GET',
  }).then(parseApiObject);
}
```

**Comment by ldelacosta** [comment]
Ticket is closed. cc: @simiadebowale @JRRoof @vbahinwillit
