### ISSUE TITLE
Remove setContact function for V0

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#53128]
In the services directory (`vets-website/src/applications/vaos/services/appointment/transformers.js`), we have a `transformer.js` file created for v0. We want to get rid of all functions in this file. 
This ticket focuses on getting rid of any usage of:
`setContact`.

---

## Acceptance Criteria
- [ ]  No reference to `setContact` anywhere in `vets-website`.
- [ ]  Remove all mocks associated with this api function (If any).
- [ ]  Remove unit test for this function (If any).
- [ ]  Remove e2e tests for this function (If any).

**Comment by ryanshaw** [comment]
@simiadebowale Closing, can't find this function in `main` or in any merged in PRs.
