### ISSUE TITLE
User receives "Scorecard is already being fetched by another user" error when no other user is fetching

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#5312]
Original story: #4931
Related Defect: #5208

The "fetch" functionality is currently not working correctly. Every time a user clicks fetch, they are given the "Scorecard is already being fetched by another user" error. This error is displaying regardless of whether or not another user is actually fetching, so fetching is currently impossible.

![Screen Shot 2020-01-29 at 12.14.29 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/8b07f247-72ac-43bb-ab9b-5625d4df5096)

![Screen Shot 2020-01-30 at 9.30.56 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/97b99b8f-cf16-4acd-bce6-2e5b124743c0)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/554

**Comment by delli-gatti-michael** [comment]
local testing complete

**Comment by delli-gatti-michael** [comment]
Bug fix is live in Staging. Closing this issue
