### ISSUE TITLE
Remove transformATLASLocation function for V0

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#53140]
In the location directory (`vets-website/src/applications/vaos/services/location/transformers.js`), we have a `transformer.js` file created for v0. We want to get rid of all functions in this file. 
This ticket focuses on getting rid of any usage of:
`transformATLASLocation`.

---

## Acceptance Criteria
- [ ]  No reference to `transformATLASLocation` anywhere in `vets-website`.
- [ ]  Remove all mocks associated with this api function (If any).
- [ ]  Remove unit test for this function (If any).
- [ ]  Remove e2e tests for this function (If any).

**Comment by ryanshaw** [comment]
@simiadebowale I believe we are still using the `transformATLASLocation`. In [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/25025) I've moved this function to the v2 location transformers (was renamed to `src/applications/vaos/services/location/transformers.js`) after the v0 transformers file was deleted. It is called in this file `src/applications/vaos/services/location/index.js`

I think we can close this but wanted to check first.

**Comment by simiadebowale** [comment]
@ryanshaw - we can close this ticket, thank you
