### ISSUE TITLE
SOCKS access for Melanie Jones

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/va.gov-team#53172]
### Your Name

Melanie Jones

### Your Email

melanie.jones@oddball.io

### Your Role and Team

Product Manager for VA Notify

### Product Manager (PM) name and email

see above, I'm PM

### Product Owner (PO) name and email

Beverly Nelson - beverly.nelson@va.gov

### Access Type Requesting

developers

### Public SSH Key

need to create this on my GFE - pending

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by mjones-oddball** [comment]
Does anyone have instructions for how to get SOCKs on a GFE? I can't install things myself and it wasn't in the instructions as far as I could tell - https://depo-platform-documentation.scrollhelp.site/getting-started/accessing-internal-tools-via-socks-proxy.

**Comment by rmtolmach** [comment]
@mjones-oddball I was under the impression you don't need SOCKS on a GFE. Are you able to access this site on your GFE? http://jenkins.vfs.va.gov/

**Comment by mjones-oddball** [comment]
@rmtolmach Oh awesome! Once on the VA Network I was able to sign in with github and access the site. Thank you :)

**Comment by rmtolmach** [comment]
Great! I'll close this :)
