### ISSUE TITLE
Check/Fix Link & Visual Bugs

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#53189]
## Tasks
- Add a space between the period and "If"
    ![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/1a49adcb-cc49-4791-bd9b-e94e50f47d39)

- Verify that these links are correct per below
    - On the confirmation pages in the blue info boxes, need to make sure these links are correct: 
        Find out if you're eligible and how to file for travel reimbursement 
       Should point to: https://www.va.gov/health-care/get-reimbursed-for-travel-pay/
   - find out how to file for travel reimbursement
    - Should point to: https://www.va.gov/resources/how-to-file-a-va-travel-reimbursement-claim-online/

- Fix this link: it should point to: https://www.va.gov/HEALTHBENEFITS/vtp/beneficiary_travel_pocs.asp
     ![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/2b6c07d3-f5a4-4a65-be41-97c9cca21ebc)

- Fix this link: it should point to: http://va.gov/accessva-travel-claim
    ![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/c64bab02-c024-4f7b-bc5d-da12854b4b55)

- Fix this visual bug: Travel pay: Your appointments page. (Refer to the attached screenshot  below (e.g., step7.png))
    - The header shows with a colon. There shouldn't be a colon in the title (You appointments: --> You appointments).
    - The font style for the sub-title looks to be using body style. It should be Bitter-Regular, 16px

- Fix this visual bug:  Travel pay: Confirmation page (Refer to the attached screenshot  below (e.g., step7))
    - The font style for the sub-title looks to be using body style. It should be Bitter-Regular, 16px

- Fix this visual bug: Travel pay: Travel pay checked in without travel pay (Refer to the screenshot below (e.g., step9.png))
    - The font style for the sub-title looks to be using body style. It should be Bitter-Regular, 16px

- Fix this visual bug: Travel pay: (Refer to the screenshot below (e.g., step10.png))
    - The font style for the sub-title looks to be using body style. It should be Bitter-Regular, 16px

- Fix this visual bug: Travel pay: (Refer to the screenshot below (e.g., step10_2.png))
    - The font style for the sub-title looks to be using body style. It should be Bitter-Regular, 16px

**Step 7.png**
![Step7.png](https://images.zenhubusercontent.com/6155d02ed6dc2cbaa5d23b32/3113439b-552e-4999-9205-557512055973)

**Step 9.png**
![Step9.png](https://images.zenhubusercontent.com/6155d02ed6dc2cbaa5d23b32/9a101314-3969-4d17-96e8-ae4c7c213606)

**Step 10.png**
![step10.png](https://images.zenhubusercontent.com/6155d02ed6dc2cbaa5d23b32/f1bc750c-c034-4c36-ab67-06abc09b24ea)

**Step 10_2.png**
![Step10_2.png](https://images.zenhubusercontent.com/6155d02ed6dc2cbaa5d23b32/0e2e0b54-8830-410b-ab39-9164dfa81c15)

**Comment by wullaski** [comment]
@loripusey this has all been verified locally and since they are all changes not effected by which environment they are running on I think it can be closed. We can't check travel on staging at the moment either.

**Comment by loripusey** [comment]
great, thanks @wullaski ; closing
