### ISSUE TITLE
Bug: Link is wrong for "Go to AccessVA travel claim portal now"

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#53183]
This link should point to this: http://va.gov/accessva-travel-claim

![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/c64bab02-c024-4f7b-bc5d-da12854b4b55)

**Comment by benbrasso-agile6** [comment]
@kellysmith1008 I added that link to this ticket, FYI
