### ISSUE TITLE
SOCKS access for Allison Lu

### ISSUE THREAD

**Issue by allisonlu** [department-of-veterans-affairs/va.gov-team#53205]
### Your Name

Allison Lu

### Your Email

allison@cityfriends.tech

### Your Role and Team

Sr Frontend Engineer @ Authenticated Experience

### Product Manager (PM) name and email

Ana Jakabcin, ana@adhocteam.us

### Product Owner (PO) name and email

Samara Strauss, samara.strauss@va.gov

### Access Type Requesting

viewers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDqQnv/6POsD+/uW8nRBSEP4icqcLs/bWvJs36Py4uJW9AVp+sR7fZa0ZDrolinXougo5NJc9Ko8pr4UV39jTJxIrrO3Tp2LPx9fgTk6rSct9ar3fLlS+gXjmOHx/xRQM2k+FVyCyKOGfccVAOywJ+88mdeoPwF3HG75rsNz5Pafeydj+GcV8tvYmFnHoxvscPfT+Oh3twmaUKvv3bPAeiTUo/purUragwxnOgDLLOHJSHX8vfbEMFHCU9gl+WN46ARa/8u4uMvuNh9OSWAy/u57ZjRYiG3NUp0KwN5lOv+PCF7KPohc5aEgpckFN8KqAURqVxn1+dYQnKR8Gj7tVR0Tz64izxOLZybcWoRa4n4Gea2C9V2Wzy+MfBRn2ZG0yMfer+XhaO8cAZ97VoO8NFEsYuTb+s0Cgc43/zr2B4Bia3P9WAOO0N+y6FGAM+yjaNTO7mkQOOwi+uzd4m8nWdTeQl89JfmhVkz2kh6/QR8cJwHhAGzk4PnO7XVtiMlpus= allisonlu@Allisons-MBP

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by rmtolmach** [comment]
@allisonlu Access granted ✅ 

Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html 

Reach out in #vfs-platform-support if you have any trouble.
