### ISSUE TITLE
Adding Kamari Patrick to DSVA Slack

### ISSUE THREAD

**Issue by smythe5** [department-of-veterans-affairs/va.gov-team#53215]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

Please add Kamari Patrick who is a Product Manager on the Sitewide Facilities team as a multi-channel guest to the following channels:
- cms-lighthouse
- sitewide-facilities
- vfs-all-teams
- cms-support
- sitewide-program

Thank you.

We aim to complete slack requests within 24hrs.

**Comment by smythe5** [comment]
@LEHigley - wanted to check to see when this might be completed?  Thank you.

**Comment by Minh-Truong** [comment]
Hi @lindluni , @speakmin ,  can we handle this request or have to forward to a different team?

**Comment by arilivigni** [comment]
@smythe5 we do not control access to slack these requests are from github.com department-of-veteran-affairs org.
Perhaps @lindluni or @speakmin know if a contact to direct your request to, but @Minh-Truong and I do not.

**Comment by arilivigni** [comment]
@smythe5 please email the devopsteam@va.gov team with your request.
