### ISSUE TITLE
On-site Search - technical discovery for improvements

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#5322]
Based on conversations and objectives, we should define some potential technical improvements. 

Starting this doc - https://github.com/department-of-veterans-affairs/va.gov-team/pull/5184

**Comment by ncksllvn** [comment]
Note - search.gov uses the concept of "modules" for search.gov websites to customize and configure search results. AFAIK, we currently only use on on VA.gov - `Best Bets: Text`.

### Implement advanced tracking to help define measurements of success
Out-of-the-box search.gov-powered websites have a number of great insights via the search.gov. The websites generally have their own subdomain, such as `search.vets.gov`. The UX is usually very limited, however, so we've implemented search.gov on va.gov using the search.gov JSON API, giving as the flexibility to create a React-powered UX. The cost of this, however, is that we lose out on the insights. 

To make up for this, we should implement some more Google Analytics into the search product. Here are my suggestions.

1. Define `clicks` by capturing an event when a user clicks on the link in a search result.
    - We should relate this back to the module
1. Define `impressions` by capturing an event each time a particular "module" is seen. 
    - For example, when we show Page X under the Top Recommendations, capture it. 
    - This, combined with the previous step will yield the Clickthru Rate for us, dividing total `clicks` by total `impressions` to yield a percentage of users that clicked through. This will tell us how successful our Top Recommendations are.
1. Define `Raw count` by capturing an event each time a query is performed.
    - We do capture the query term in the address each time a user submits a search, but it might be nice to have a dedicated event fo queries.
    - We also have this data in the search.gov admin, but it might be nice to consolidate event tracking into GA.

More info - https://search.gov/manual/monthly-reports.html.

### Consider additional Search.gov modules
Because our implementation is API-based, I'm not sure if we can use all of these, but they're worth looking into - https://search.gov/manual/module-codes.html. For example, the `Image Results (Bing)` , `Spelling Suggestions`, and `Related Searches` could be clear paths to nice UX improvements.

More info - https://search.gov/manual/module-codes.html

### Consider routed queries
Some websites will recognize certain input so that instead of taking you to the search results page, it takes you straight to an area of the website. For example, Lowes.com matched my typo query `gardewn` and took me straight to `/l/lawn-garden.html`.

We could follow this same pattern. If a user searches for a certain term, and we know exactly what page we want them to see as a result, we could take them straight there. For example, perhaps searching `health care` could take them straight to `/health-care/`. 

More info - https://search.gov/manual/routed-queries.html

### Consider collections
Some websites and apps allow users to search just a particular area. For example, if I press `command + f` on Slack, the search bar open populated with `in:vsa-engineering`. I can then type my search term, and it will search only the `vsa-engineering` channel.

On the `department-of-veterans-affairs` GitHub page, if I type in the search bar, GitHub shows a dropdown, asking if I want to search just this organization or all of GitHub.

We can apply this behavior to our site. For example, if a user is in the Health Care hub when they start performing a search, perhaps they are interested in only that area of the site. We can follow a similar UX to that of Slack and GitHub - open a dropdown panel asking if they want to narrow their search to just the Health Care hub, or site-wide. 

More info - https://search.gov/manual/collections.html

**Comment by ncksllvn** [comment]
Hey @davidconlon, here are some suggestions on how to improve our search app, largely inspired by perusing the search.gov docs. I'd love your thoughts!

**Comment by davidconlon** [comment]
Thanks @ncksllvn This is a lot of the stuff I had already been adding to the working roadmap with a bit greater detail.

**Comment by MickinSahni** [comment]
Gonna close this one out. Thanks,  team

**Comment by ncksllvn** [comment]
Sync w/Search.gov team - 4/22/20

- Dawn McCleskey (Program manager) - summarizing 2018 of initial integration into va.gov -
     - Last spoke in October w/Kara - Kara since switched programs
     - Intros
- Sept 2018
    - 300 subdomains needed to be indexed, not all containing sitemaps so needed to be crawled
    - Crawled properties vs sitemap indexed properties
        - sitemap, daily 4 AM, schedule, taking a diff on the index 
        -  Crawled domains are NOT set up for automated maintenance, so need to make sure reindexed on a "regular enough" schedule. Used a script that took a set of domains and crawled them
- Ongoing rolling modernization of va.gov - talking about domains, which ones can we take off of this list and move to automated sitemap approach
- High-level recommendations - Search.gov - everything you need to know
- Relationship between queries and what they click on upon seeing results
    - Search.gov will provide additional doc and possibly a code snippet
    - Click data serves as a proxy for ranking factors for search.gov to improve 
- "Sampling"
    - Higher-traffic websites, terms of percentages (bounce rates, etc) GA doesn't consider all of the data that we have
    - Point of above which not all records are considered so a general percentage is provided = "sampling"
    - This means that search.gov queries in search.gov admin may not be 1:1 with GA analytics dashboard using query parameter 
- Great search.gov example -
    - nasa.gov - many subdomains but only search about 10 - those 10 are the priority search results

### Decide before next time
- GA vs search.gov admin for insight into search tool
- VA subdomain sitemap and prioritization
