### ISSUE TITLE
Update SOCKs proxy access docs

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#53236]
### Description

I learned this morning that when filing a SOCKs access request, it's important to select the correct value for the *Access Type Requesting* field, because the default value (`automation`) does not actually grant SOCKs access. Seems like general guidelines would be:

- PM/UX folks should select "viewers"
- Developers that need SSH access to review environments, lower environment vets-api/revproxy etc instances should select "developers"
- Platform CoP team members should select "platform"

I think adding this information to the [socks proxy doc](https://depo-platform-documentation.scrollhelp.site/getting-started/accessing-internal-tools-via-socks-proxy) would help folks out. Thanks!

### Relevant URLs

- https://dsva.slack.com/archives/CBU0KDSB1/p1675712993091939
- https://depo-platform-documentation.scrollhelp.site/getting-started/accessing-internal-tools-via-socks-proxy
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=external-request%2Coperations%2Cops-access-request&template=socks-access-request.yml&title=SOCKS+access+for+%5Bindividual%5D

**Comment by vbellissimo** [comment]
Hi @acrollet Thank you for your content suggestions. We will review your request and put in our backlog for next steps.

**Comment by laucon** [comment]
I edited this document according to your requests. Thank you so much for pointing that out. It should be published today at 3:30.

**Comment by laucon** [comment]
Please let me know if you need me to change anything in this [doc](https://vfs.atlassian.net/wiki/spaces/GS/pages/1821081710/Accessing+Internal+Tools+via+SOCKS+Proxy). I added the info to Steps 4 through 6 under "Configuring SOCKS Proxy on Mac."

**Comment by acrollet** [comment]
@laucon it looks great, thanks so much!
