### ISSUE TITLE
Yellow Ribbon MVP — VSA Accessibility Review of Final Mockup for Pre-usability testing

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#5324]
# Yellow Ribbon MVP — VSA Accessibility Review of Final Mockup for Pre-usability testing

## Description

- For school name, consider a label "School Name" for clarity. Since the text above says "Displaying 1-10 of 59 results" rather than "Displaying 1-10 of 59 schools" it may be cognitively unclear for those with lower comprehension or memory considerations. Same for the location. The h1 may be forgotten by the time the person is in the results. **Potential solution:** For the screen reader experience, at a minimum, those labels would be needed.

- For an experiment, grab an empty paper towel tube or roll a piece of paper up to a similar shape. View the mobile prototype, now view the desktop prototype, and view the compare layout on desktop. (Alternatively, see this video https://youtu.be/LeWAnR4JPM0, specifically at 25:00) There may be proximity considerations for desktop. **Potential solution:** Consider the mobile layout (acknowledge the empty space on the right) or a table layout which includes affordances with a rule or 'zebra-striping' to show corresponding info. If RWD for mobile is the concern, we can work on that.

- For mobile layout, what information might be presented in landscape view? In portrait view, might we offer a "View more details" accordion?

- In Compare view, consider replacing the **X** with **Remove** link for all.

- I'm not sure if this testing is solely for the display of results and compare functionality. How do I click on a school to look at more details, such as the school website?

## Point of Contact

**VFS Point of Contact:** Jennifer

**Comment by andaleliz** [comment]
Thanks for this feedback! Are any of these "must do", and is there a point in the process they need to be completed by?

Just FYI, the testing is solely for display of results and compare. One thing I'd really hopeful we'll learn from talking to Veterans is "what would you want to do next, now that you have this information"?  Since we aren't sure, we didn't guess and provide a next step.

**Comment by jenstrickland** [comment]
The first bullet is necessary, at a minimum the sr-only label. 

The second bullet, I encourage considering a table presentation for this material — with a checkbox for comparison. Take a look at that part of the video, try it on the mockup. I thought that made the proximity concern of cards really clear. 

Replace X with Remove is a **suggestion**.

Accessibility in the design phase is primarily for recommendations, so we have less gaps to fix in development.

**Comment by andaleliz** [comment]
We share the same concerns, glad we are on the same page.  And, thanks for clarifying the requirements vs suggestions!
