### ISSUE TITLE
[FE] My VA Healthcare: Schedule and manage appointments icon implementation

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#53242]
## Background
We need to update the icon for "Schedule and manage your appointments" within the Health care section on My VA from the current fa-calendar-check icon to the fa-calendar icon. This will align us with what's being used in the appointments tool and what will be used in a new MHV landing page design

Current implementation:
![Screenshot 2023-02-07 at 11 40 21 AM](https://user-images.githubusercontent.com/45603961/217307596-f93ab833-4667-415d-a6c1-1db4b723f392.png)

## Tasks
- [ ] Change the icon in the health care section for "Schedule and manage your appointments" from `fa-calendar-check` to `fa-calendar-icon` 
- [ ] Test
- [ ] Move to validate 

## Acceptance Criteria
- Icon in the health care section for schedule and manage your appointment matches the designs/sketch files @aagosto90 updated in #53241 

## How to validate
- Log in with a test user who has health care and no upcoming appointments (at time of testing this is 262)

## Resources
- [Slack thread](https://dsva.slack.com/archives/C909ZG2BB/p1675786396553929)
- [GH comment thread](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1493#issuecomment-1420904698)

**Comment by allisonlu** [comment]
bringing this into sprint 7 while we figure out next steps for #48726

**Comment by ajakabcin** [comment]
Confirmed on staging with user 262 - thanks @allisonlu !

![Screenshot 2023-04-06 at 2.12.01 PM.png](https://images.zenhubusercontent.com/60465863a45e7b63743045b3/3a8273b1-363b-40c5-90aa-cef9bd102a29)
