### ISSUE TITLE
[prod] Sync BRD and EKS settings

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#53248]
## Description
Similar to #52880, we need to make sure the values in [prod-settings.local.yml.j2](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/vets-api/prod-settings.local.yml.j2) are the same in EKS (ArgoCD) as they are in BRD (EC2). 

**Steps:**
1. Connect to one of the `dsva-vagov-prod-deployment-vagov-prod-vets-api-server` EC2 instances [in AWS](https://us-gov-west-1.console.amazonaws-us-gov.com/ec2/home?region=us-gov-west-1#Instances:instanceState=running;search=:prod-vets-api-server;v=3;$case=tags:true%5C,client:false;$regex=tags:false%5C,client:false).
2. In another window, navigate to a `vets-api-web` pod in [ArgoCD](https://argocd.vfs.va.gov/applications/vets-api-prod?resource=) and access the terminal tab.
3.  In prod-settings.local.yml.j2, copy each path that starts with `/etc/pki/tls/certs` or `/srv/vets-api/secret` (generally, things ending in `.pem` or `.key` or `.crt`. There are about 30 total.), `cat` each path in both BRD and EKS and check to make sure they match. If they do match, nothing needs to be done. 
    1. If they don't match, document the crt/key that is bad. We need to make EKS match what's in BRD. (We can assume things in BRD are working because that's where prod currently is.)
    2. Figure out why they don't match. It could be that there isn't an entry in [secrets.yaml](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/main/apps/vets-api/prod/templates/secrets.yaml), there could be a typo, a new line at the end of the value might need to be added in AWS. (#52880 lists some of the reasons for staging.)
    3. Fix it 😃 

## Acceptance Criteria
- [ ] Go through the documented list of bad certs that had to be fixed and verify they now match in EKS and BRD.

**Comment by laineymajor** [comment]
@oseasmoran73 can you review/confirm these certs and secrets... we'd love one more set of (fresh) eyes on this! Reach out in our team channel with any questions. Thanks!

**Comment by oseasmoran73** [comment]
Will be reviewing and checking those out today

**Comment by oseasmoran73** [comment]
Changes have been applied. Closing ticket
