### ISSUE TITLE
SOCKS access for [Vid Jovanovic]

### ISSUE THREAD

**Issue by vidjovanovic** [department-of-veterans-affairs/va.gov-team#53258]
### Your Name

Vid Jovanovic

### Your Email

vid.jovanovic@bylight.com

### Your Role and Team

DevOps Engineer, Kong

### Product Manager (PM) name and email

Mike King Mike.King@oddball.io

### Product Owner (PO) name and email

John Rahaghi john.rahaghi@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDyJoRE/0HoTN3Y7dfVDQs1LLgCnX0kEeC5ccJcCG31f5lLaM0DHGYsx+hxqYw2ViCB91Q6gx5hs26d3ObXikQcmOAUxAROpDnwHx4BikDpN/xMkdJvcwmq4KFvio9yZDRMfQYoLCmCOmOdh1MN7lrpdIenoBJyZmYtheVFexEe71JCb3KG3qNDbkPL0b1yh/td3Ftt7py4+oMT4UdwptBAA1pSi4qD9Xb2cSvVFonV9nRS2tPqm4zCOMSrCtqN6E4IXqxKw+ygl7fywybtTGeu/v7QCcZu05hQvnQnex5RR2Am79GWV7IMnWUC949Na6atHeaTZdPnuoMrH0vojT2+GNAe/nQAcSuCf4HGm/rsjRfiMROa/Qq+PJ4zug9+Cudhlkh9aN35O2TUCcdE3lc/PnWGJcqVmIM6wehsEm3XluIFp/amN3nl4uOnW+9Pnyp1uPNSTC09mjhpJsCULEiQxyQmrlmx2pi8cXIUbnzjKRd6So1sSO300zJ1UodcxbE= vidjovanoic@HMV2KRF70D

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by vidjovanovic** [comment]
I would like to request to have my public key updated to the following:

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDyJoRE/0HoTN3Y7dfVDQs1LLgCnX0kEeC5ccJcCG31f5lLaM0DHGYsx+hxqYw2ViCB91Q6gx5hs26d3ObXikQcmOAUxAROpDnwHx4BikDpN/xMkdJvcwmq4KFvio9yZDRMfQYoLCmCOmOdh1MN7lrpdIenoBJyZmYtheVFexEe71JCb3KG3qNDbkPL0b1yh/td3Ftt7py4+oMT4UdwptBAA1pSi4qD9Xb2cSvVFonV9nRS2tPqm4zCOMSrCtqN6E4IXqxKw+ygl7fywybtTGeu/v7QCcZu05hQvnQnex5RR2Am79GWV7IMnWUC949Na6atHeaTZdPnuoMrH0vojT2+GNAe/nQAcSuCf4HGm/rsjRfiMROa/Qq+PJ4zug9+Cudhlkh9aN35O2TUCcdE3lc/PnWGJcqVmIM6wehsEm3XluIFp/amN3nl4uOnW+9Pnyp1uPNSTC09mjhpJsCULEiQxyQmrlmx2pi8cXIUbnzjKRd6So1sSO300zJ1UodcxbE= vidjovanoic@HMV2KRF70D

**Comment by rmtolmach** [comment]
I have edited the description to match your requested key. Th edit kicked off our github action that edited your open pull request, https://github.com/department-of-veterans-affairs/devops/pull/13081

I think @Kshitiz-devops is handling SOCKS requests, so I'll let him take over :)

**Comment by mjconw3** [comment]
Hello @Kshitiz-devops I am @vidjovanovic PM and wanted to check in on the status of this request. It is holding him back from being able to get work done so I wanted to see if I/we could do anything to push it along. Thanks as always

**Comment by rmtolmach** [comment]
Hi @mjconw3, https://github.com/department-of-veterans-affairs/devops/pull/13081 was merged on Wednesday, so @vidjovanovic should have SCOKS access now. Sorry we forgot to let you know in this ticket!
