### ISSUE TITLE
[Incident Response] Add triage steps with monitoring info to IC Playbook 

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#53252]
## Description
As part of Platform Support and/or incident response duties, Platform Operators need to know how to triage incidents using available monitoring data. 

## Resources 
- [VA.Gov Incident Playbook ](https://vfs.atlassian.net/wiki/spaces/ECP/pages/1565294641/VA.Gov+Incident+Playbook)

## Acceptance Criteria
- [x] Platform Operators can reference monitoring info while following triage steps in the IC Playbook

## Refinement Guidance - Check the following before working on this issue: 
- [x] _Team label assigned ("platform-tech-team-2")_
- [ ] _Epic assigned (if needed)_ 
- [x] _Estimated (points assigned)_
- [x] _Sprint assigned (once planned)_
- [x] _Team member(s) assigned_

**Comment by mynar7** [comment]
Added the following to the IC playbook: https://vfs.atlassian.net/wiki/spaces/ECP/pages/1565294641/VA.Gov+Incident+Playbook#Triaging-an-Incident

**Comment by jhouse-solvd** [comment]
@mynar7 - This is fantastic! I love that you've linked to monitoring tools for each thing to check. I believe this will go a long way to support triage and troubleshooting during an Incident. 

Thank you for [sharing this w/ the DevOps CoP in DSVA Slack](https://dsva.slack.com/archives/C04CYC4LMU6/p1675824933652109). Please continue to share with others to promote visibility and get feedback. 

You've done great work here. The acceptance criteria have been met, and this issue can be closed.
