### ISSUE TITLE
SPIKE: Determine if messages need to be reprioritized on not eligible, confirmation page

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#53253]
## TIMBOXED
- A single 1-hour meeting

## Description 

How might we ensure that information about check in is prioritized over travel information when a Veteran is NOT eligible for travel (i.e., never presented with travel questions) and successfully checks in for their appointment? 

Specifically, [this wireframe](https://share.goabstract.com/6b69924f-904b-4d78-b5a1-4c40ed65e4d2?collectionLayerId=fda84b41-9434-41b6-a2c4-7b6007737eb3&mode=design&sha=latest). As a reminder, when a Veteran is NOT eligible for travel reimbursement, they are never presented with the option to file for travel reimbursement during the check in process. 

Secondarily, but not as important, when Veterans say, ["No," that they don't want to file for travel reimbursement](https://share.goabstract.com/6b69924f-904b-4d78-b5a1-4c40ed65e4d2?collectionLayerId=f85def7d-e62b-4abc-b09a-45881c20b29f&mode=design&sha=latest), how should the travel reimbursement message on the confirmation page be prioritized in comparison to information about their check in status? For example, [same wireframe](https://share.goabstract.com/6b69924f-904b-4d78-b5a1-4c40ed65e4d2?collectionLayerId=fda84b41-9434-41b6-a2c4-7b6007737eb3&mode=design&sha=latest). 

[For reference, general workflow for travel
](https://app.mural.co/t/vfscie8528/m/vfscie8528/1667222840454/ada0c417b71c922895f1750cd32d869f6213e129?sender=u83bc52d7fa73658f84f27755)

## Tasks
- [ ] Decide if we are going to move forward with something different for this page

**Comment by benbrasso-agile6** [comment]
Add christina

**Comment by cgednalske** [comment]
Discussed at UX sync yesterday and determined that messages can be reevaluated to clarify content priority and explore other available components. 

Next step: [ticket for creating wireframes](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/53461).

**Comment by benbrasso-agile6** [comment]
Should be good to close. @loripusey FYI
