### ISSUE TITLE
Identify points of unknown for GIDS data pertaining to Yellow Ribbon 

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#5325]
01/30/2019 2:20pm **Update**:
- Both [the `vets-api` API endpoint](https://api.va.gov/v0/gi/institutions/search) and [the GIBCT API endpoint](https://dev.va.gov/gids/v0/institutions) force pagination and do not support sorting.
- We are missing the following key-value pairs from [the `vets-api` API endpoint](https://api.va.gov/v0/gi/institutions/search) and [the GIBCT API endpoint](https://dev.va.gov/gids/v0/institutions):
1. `maxRecipients` (is this equal to studentCount? Does studentCount include non-YR programs?)
1. `maxYellowRibbonBenefitInCents` (is this equal to tuitionInState or tuitionOutState? It looks like contributionAmount from the csv in GIDS is not present in the above API endpoint)
1. `yrAvailableDegrees` (there is highestDegree, but it looks like it can be either a number or string?)
1. `yrAvailableMajors` (I don't see any key-value pair that supports this currently)
--
An example CSV that includes all the data we need for the current design spec: https://github.com/department-of-veterans-affairs/gibct-data-service/blob/master/sample_csvs/yellow_ribbon_program_source.csv

**Comment by ncksllvn** [comment]
1. The API does not support __sorting__ right now. We would have to implement this if we want to sort the results list.

**Comment by ncksllvn** [comment]
We will likely need to dig into the source of GIDS and see how the Yellow Ribbon spreadsheet is processed  into the data models - https://github.com/department-of-veterans-affairs/gibct-data-service/tree/master/sample_csvs

**Comment by kelsonic** [comment]
**In regards to the API endpoint `https://api.va.gov/v0/gi/institutions/search`, in what cases is the data specifically intended to be used only by the GIBCT and in what cases can we use the data only for a YR context?** Which data points is there a distinction between what we should show on Yellow Ribbon vs. the GIBCT?

These are some of the top questions we are trying to answer with this ticket I think...

The current model's key-value pairs:

```
address1: "309 HARDIN ADMINISTRATION BLDG"
address2: "ACU BOX 29141"
address3: null
bah: 1151
books: 1250
campusType: "Y"
cautionFlag: true
cautionFlagReason: "Warning or Equivalent-Factors Affecting Academic Quality (Concerns about issues affecting academic quality)"
city: "ABILENE"
closure109: null
country: "USA"
createdAt: "2019-12-11T17:31:21.000Z"
distanceLearning: true
dodBah: 1062
eightKeys: null
facilityCode: "31000143"
highestDegree: 4
independentStudy: true
localeType: "city"
name: "ABILENE CHRISTIAN UNIVERSITY"
onlineOnly: false
parentFacilityCodeId: null
physicalCity: "ABILENE"
physicalCountry: "USA"
physicalState: "TX"
physicalZip: "79699"
poe: false
preferredProvider: false
priorityEnrollment: false
schoolClosing: false
state: "TX"
stemOffered: false
studentCount: 257
studentVeteran: null
tuitionInState: 29450
tuitionOutOfState: 29450
type: "PRIVATE"
updatedAt: "2019-12-11T17:31:21.000Z"
vetTecProvider: false
yr: true
zip: "79699"
```

Data points that YR MVP needs: (`checked` means we feel confident the API endpoint currently supports this data accurately.)
```
- [x] availableOnline
- [ ] benefitAvailableForAmount
- [x] city
- [x] country
- [x] id
- [ ] maxYellowRibbonBenefitInCents
- [x] name
- [x] onlineOnly
- [x] state
- [ ] yrAvailableDegrees
- [ ] yrAvailableMajors
```

**Comment by ncksllvn** [comment]
From the [Yellow Ribbon CSV parsed by GIDS](https://github.com/department-of-veterans-affairs/gibct-data-service/blob/master/sample_csvs/yellow_ribbon_program_source.csv), we're interested in the highlighted columns -

![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/85439186-7fce-49da-aafc-55bb12a73b53)

We'll need to trace how this CSV is processed throughout the GIDS source code, and see if/how the data is exposed for us to use. We may need to add those CSV columns as fields into the Rails models, then export them into the JSON from each API route in GIDS.

**Comment by ncksllvn** [comment]
GIDS `institution_controller` - https://github.com/department-of-veterans-affairs/gibct-data-service/blob/master/app/controllers/v0/institutions_controller.rb

**Comment by kelsonic** [comment]
So [lines 8:11](https://github.com/department-of-veterans-affairs/gibct-data-service/blob/master/app/models/yellow_ribbon_program_source.rb#L8) are all of the key-value pairs we're missing that I mentioned in the checkboxes above. However, it's not clear how we can add these to the GIBCT API endpoint https://dev.va.gov/gids/v0/institutions...

**Comment by andaleliz** [comment]
Random data tidbit I noticed in a test today: a school with `Out-of-state` in the `school or division` column on one of the current tables. I expected these values only to be programs or majors, if you will...

**Comment by kelsonic** [comment]
@andaleliz This must be from one of the CSVs as currently the API does not have any data point (key-value pair) that supports `Programs or majors` 😬In the CSV it does seem like the values for that column are pretty inconsistent and not reliable...

**Comment by MickinSahni** [comment]
Not able to leverage data from the 4 main columns in the GIBC csv bc they're not being pulled the services we rely on to power the YR tool so effectively blocked until the API offers these updated endpoints.

**Comment by ncksllvn** [comment]
We have a meeting with the team maintaining GIDS tomorrow at 3 PM ET. Our goal for that meeting should be to conclude this research by defining any Yellow Ribbon work that needs to be done in GIDS. I suspect those will be -

1. Expose the Yellow Ribbon data fields noted in @kelsonic's comment in the GIDS API route.
1. Implements a "sort" flag in the GIDS API route (if we're still interested in that functionality)

**Comment by andaleliz** [comment]
@ncksllvn and @kelsonic multiple participants stated the alphabetical order presentation made sense to them.

Multiple participants also said would be helpful to see schools based on funding amount and/or "number of students" when asked about how they might "reduce the number of options" on the screen.  A couple specifically said "sort by..." those values whereas others said "only see schools that have unlimited funding" or "for unlimited students".

Based on the above, ideally, we could have sorting, AND filtering! But, I think filters would be more helpful because if users could narrow down the number of results, sorting would become less necessary.

**Comment by MickinSahni** [comment]
PR open for a hypothetical approach to accessing the 4 lingering k:v pairs. Will see if this unblocks us. Still have sorting/filtering questions that need answering.

**Comment by andaleliz** [comment]
We learned from participants that location is really important for them when selecting a school, and that most participants already have a school in mind when verifying YR participation. 

In our call today, I'd be interested to learn more about 

- what we can do with auto-suggest for the school name field, and
- conditional fields that are populated with options based on previous selections
    - e.g if you type a school, you can select the degree + programs offered at that school in the `degree type` field, or 
    - setting up multiple fields for location, where users could start w/ country, then select states (or overseas campuses), then cities, etc

**Comment by MickinSahni** [comment]
Putting 3 points on this

**Comment by MickinSahni** [comment]
2020-02-06 PW Standup
- Closing as we've made a decision on an approach. Subsequent work captured in #5567 (which we need to breakdown)
