### ISSUE TITLE
Archive channel #cms-platform

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-team#53265]
# Description
**Please archive the channel #cms-platform.**

The team formerly known as Platform CMS has merged with another team to become CMS Team. CMS Team is using #sitewide-cms-platform as its primary Slack home. 

Platform CMS previously had the channel #cms-platform as its home channel. We would like to retire/archive this channel to reduce confusion.

**Comment by ndouglas** [comment]
![5e7e30ec192cdf9bd11bf85bb83509e4](https://user-images.githubusercontent.com/1318579/219718778-faa435be-d394-4a62-822d-2ac037495bf6.jpg)

As far as I can tell, this channel is still open and active.  Am I missing something?

**Comment by arilivigni** [comment]
@ndouglas then please contact folks that admin slack or tag them in this issue. GitHub Support can't help archive slack channels.
