### ISSUE TITLE
Get vets-api running locally

### ISSUE THREAD

**Issue by ianhundere** [department-of-veterans-affairs/va.gov-team#53266]
## Description
Clone the [vets-api repo](https://github.com/department-of-veterans-affairs/vets-api) and get it running either the native or docker way. The README is a good place to start as well as the following link to the dev docs:
- https://depo-platform-documentation.scrollhelp.site/developer-docs/running-vets-api-locally

## Technical details
you’ll hit `localhost:3000` and should get:
```
{
message: "Welcome to the va.gov API"
}
```

and `http://localhost:3000/v0/status` will give you:
```
{
git_revision: "MISSING_GIT_REVISION",
db_url: null
}
```

## Acceptance Criteria
- [ ] Clone the vets-api repo
- [ ] Get vets-api running locally
- [ ] Other than going to the link mentioned above, find other ways of testing `vets-api`. [Trevor's video](https://drive.google.com/file/d/18Roz4i6kHfM8-3TBb-zzbGZ2AJRADE_3/view?usp=sharing) might be helping in this endeavor.

**Comment by vidjovanovic** [comment]
Got vets-api running on MacOSX
