### ISSUE TITLE
ISCP System Description and Architecture

### ISSUE THREAD

**Issue by gary-fallon** [department-of-veterans-affairs/va.gov-team#53289]
## Description
The System Description and Architecture in Section 2.1 need to be reviewed and updated.

> System environment: VFSP-Va.gov is hosted within VA-ATO'd Amazon Web Services GovCloud.  This FedRAMP approved, FISMA moderate environment provide Infrastructure as a Service (IAAS) capabilities to Vfsp-va.gov, such as web and database servers for the various applications that comprise VFSP-Va.gov.  Additionally, connectivity to VFSP-Va.gov is facilitated through a TIC-compliant site-to-site encrypted VPN tunnel between VA and AWS

## Requirements
#53111

The system environment should accurately describe all connectivity and methods of accessing our AWS environment, including, but not limited to, the SOCKS proxy.

The architecture diagram should match the BIA and all other references in eMASS.

## Tasks
The following tasks must be reviewed and completed as necessary.
- [ ] The partnerships with external organizations/systems should match the BIA and all other references in eMASS.

## Acceptance
The following tasks must be completed before this issue can be considered done.
- [x] Review for accuracy and completeness.

**Comment by jhouse-solvd** [comment]
This issue has been rated as a 5 (following the guidance [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/2354642992/Use+points+to+estimate+issue+or+story+complexity#5-%E2%80%93-Longer-time-to-deliver%2C-high-complexity%2C-likely-unknowns).

**Comment by gary-fallon** [comment]
I will be drafting the BIA and ISCP based on a new definition of the FISMA authorization boundary that includes all VFS applications.

**Comment by alyssagallion** [comment]
During our Gap Analysis, we realized that the System Security Plan (SSP) was incorrect. We have since updated it, presented it to the ISSO and Ray Wang is now reviewing the associated tickets he needs to approve. Once those are reviewed and approved, @ScottCutlip will continue the work on SSP. 

SSP is blocking BIA work and BIA work must be completed prior to ISCP work being done. Blocked.

**Comment by jhouse-solvd** [comment]
Please [see the parent epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/53216#issuecomment-1589597039) for a recent update. 

Moving to review.

**Comment by jhouse-solvd** [comment]
The ISCP has been updated w/ the most recent info. 

Please see the parent epic (#53216) for future updates and follow-up issues. 

Closing.
