### ISSUE TITLE
AWS access for Cam Bui

### ISSUE THREAD

**Issue by ncbui** [department-of-veterans-affairs/va.gov-team#53290]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### E-QIP Transmittal Date

- [x] Check this box if you have an E-QIP transmittal date.

### Your Name

Cam Bui

### Your Email

ngoccam.bui@va.gov, cam.bui@thoughtworks.com

### Team, Role, and Company of the target individual

Digital Health Platform, Developer, Thoughtworks

### Product Manager (PM) name and email

Abigail Burton abbie.burton@thoughtworks.com 

### Product Owner (PO) name and email

Abigail Burton abbie.burton@thoughtworks.com 

### Desired AWS Access

Copy permissions from @yonidoronpeters

### Access Expiration

ongoing

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by little-oddball** [comment]
Not on a roster at this point.

**Comment by little-oddball** [comment]
@ncbui - I am hopping in to try and help w/ these items. Our Gov't PO had a transition and we now require to have the eQIP transmittal date provided. Would you be able to work with your PO/PM to provide that? Once that has been applied to the ticket I push move it forward to our Gov't PO for a review/approval. Thanks and sorry for the delay and any inconvenience.

**Comment by ncbui** [comment]
Thanks for reviewing this and sharing context, @little-oddball. I'll get those dates

**Comment by ncbui** [comment]
Reopening this to get AWS access again 
I've started the Platform Orientation process again: https://github.com/department-of-veterans-affairs/va.gov-team/issues/55343
My eQIP transmittal date is: 10/29/2021

**Comment by little-oddball** [comment]
@ncbui - keeping an eye on the VFS rosters so adding the NOT YET label for when orientation is complete.

**Comment by ncbui** [comment]
thanks @little-oddball, I should be on the roster now after this issue was addressed: https://github.com/department-of-veterans-affairs/va.gov-team/issues/55343

**Comment by little-oddball** [comment]
VFS Roster.

**Comment by BillChapmanUSDS** [comment]
I approve ongoing lower environment access but any production requests are approved 3 month temporary.

**Comment by considerable** [comment]
current aws config for Jonathan.Doron-Peters (Desired AWS Access: Copy permissions from @yonidoronpeters) and for Cam.Bui looks the same as those were setup back in March 2022:
```
git blame iam_users.tf | grep -A8 Doron-Peters
git blame iam_users.tf | grep -A8 Cam.Bui
```
Therefore, I've just done the password reset to reactivate.

**Comment by considerable** [comment]
Confirmed with Cam.Bui and closing the tkt.
