### ISSUE TITLE
Add Sub-brand guidelines to Design System, Content Section

### ISSUE THREAD

**Issue by KevinMHoffmanUSDS** [department-of-veterans-affairs/va.gov-team#533]
Suggestion: add page entitled Sub-brands to the content section at:

https://design.va.gov/content-style-guide/sub-brands

Proposed content (links to a page that does not yet exist, also a proposed issue):

# Sub-brands

VA.gov is designed to be a consistent and Veteran centered user experience. For that reason, it does not support the use of customized language, imagery, logos, word marks to represent sub-brands within the content of VA.gov outside of primary VA branding elements, VA.gov approved design system components, and visuals executed within the VA brand guidelines.  

This includes customized language, imagery, logos, and word marks for sub-brands such as

* Departments
* Sub-groups and/or committees
* Special programs
* Initiatives
* Events

Read about the design guidelines for VA.gov regarding the use of [custom logos](https://design.va.gov/design/using-custom-logos).

Download the [VA Graphic Standards (PDF)](https://www.va.gov/opa/publications/graphicstandards/va_graphicstandardsguide_508_0113.pdf) to learn about the VA brand, visual identity, and related topics.

**Comment by KevinMHoffmanUSDS** [comment]
@jenniferlee-dsva I thought it made sense to add this content to the "content" section of the design system as I think of images (logos, illustrations) as content, as much as I think of them as design elements/choices. I'll leave the final call on that one up to you, however -- if you disagree or thing putting one page in the design section is sufficient, we can just close this issue out without you needing to edit this.

**Comment by jenniferlee-dsva** [comment]
See comment here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/534#issuecomment-510299454

**Comment by jaredcunha-usds** [comment]
@KevinMHoffmanUSDS This page has been added (https://design.va.gov/design/logos), so I'm going to close this issue.

**Comment by KevinMHoffmanUSDS** [comment]
@jaredcunha-usds Thanks!
