### ISSUE TITLE
Create form1095 staging s3 bucket

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#53301]
`dsva-vagov-staging-1095b-form-uploads` is missing. It's not in AWS s3 but it is defined in the code: https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/vets-api/staging-settings.local.yml.j2#L978 

Figure out why it's not in AWS.

**Comment by rmtolmach** [comment]
It's not in s3
![image](https://user-images.githubusercontent.com/10993987/218191826-6292df85-ffed-4304-8e68-9e1f91602f0d.png)
 But the groundwork was laid in [staging-settings.local.yml.j2](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/vets-api/staging-settings.local.yml.j2#L978). Bucket needs to be created with terraform. 

PR: https://github.com/department-of-veterans-affairs/devops/pull/12544

**Comment by rmtolmach** [comment]
s3 bucket is now in AWS
![image](https://user-images.githubusercontent.com/10993987/218544535-8a07bd54-289f-449c-a135-b2c8e3ea132e.png)

Closing this issue.

P.S. I was getting this message after `terraform apply`. The bucket exists but it's still showing up in the terraform plan... Hopefully it's not a big deal.
