### ISSUE TITLE
Initiate Staging AB Testing

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#53324]
Production will need to have some type of A/B testing in place before we can fully migrate to EKS. We need to ensure we have sticky sessions setup in staging and test CORS issues after all staging issues have been resolved.

**Comment by LindseySaari** [comment]
I think we can do some sort of request header technique to send requests directly to EKS to test

**Comment by laineymajor** [comment]
Good to close as complete with staging
