### ISSUE TITLE
Develop Idea & User Flow for Texting Veteran when Claim Response is Delayed

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#53330]
## Background
[Slack thread](https://dsva.slack.com/archives/C02G6AB3ZRS/p1675801869514529?thread_ts=1675786180.210829&cid=C02G6AB3ZRS)

_I think this team should be starting to do some spikes around the text message solution we were chatting about last week. (Start the claim during the check in process and the veteran gets a text when the claim submission API is complete.) I do think this is a solid flow and allows for more options and features to be added later._ 

## Tasks
- [x] Develop a user flow for this idea

**Comment by benbrasso-agile6** [comment]
Meet with Ya-ching

**Comment by benbrasso-agile6** [comment]
Started - https://app.mural.co/t/vfscie8528/m/vfscie8528/1675890779520/0f6c8b1eeda87ab857e48b54bef7f15045c258ce?sender=u83bc52d7fa73658f84f27755

**Comment by benbrasso-agile6** [comment]
Added 2 other options

https://app.mural.co/t/vfscie8528/m/vfscie8528/1675890779520/0f6c8b1eeda87ab857e48b54bef7f15045c258ce?sender=u83bc52d7fa73658f84f27755

**Comment by benbrasso-agile6** [comment]
Will keep this ticket in validate until speaking with Mark

**Comment by benbrasso-agile6** [comment]
I'll just close. We'll create a new ticket after talking to Mark.
