### ISSUE TITLE
Write Legal Definitions in Plain Language for 1010-CG

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#5334]
## User Story:
As a Caregiver filling out the 1010-CG , I need to be able to understand the form definitions in plain language so that I can understand the program requirements as I'm filling out the form.

## Acceptance Criteria:
* Rewrite legal definitions in plain language

## Configuration
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (e.g. `vsa-authenticated-exp`, `vsa-caregiver`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by psanders86** [comment]
** **

** **

** **

**Definitions for 10-10CG online form**

** **

**What is a caregiver support coordinator?**
Caregiver support coordinators are located at every VA medical center. They are clinical professionals who help you find programs and community services so you can support your Veteran.

**Who can be called a family member?**
Family members can be the Veteran&#39;s or service member&#39;s:

- Parent
- Spouse
- Son or daughter
- Step-family member
- Extended family member
- Someone who lives full-time with the Veteran, or will do so if approved as a primary family caregiver or a secondary family caregiver

**What does injured in the line of duty mean?**
This is an injury that happens or is aggravated during active military service. Veterans may not be covered under this part if:

- They are guilty of willful misconduct
- They abused alcohol or drugs
- They are guilty of desertion
- They were absent without leave

**What is power of attorney?**
A power of attorney is legal authorization for someone to act on the Veteran&#39;s or service member&#39;s behalf.

**What is a primary family caregiver?**
Primary family caregivers are approved by the Program of Comprehensive Assistance for Family Caregivers to be the main provider of personal care services to a Veteran. They can be the Veteran&#39;s or service member&#39;s:

- Parent
- Spouse
- Son or daughter
- Step-family member
- Extended family member
- Someone who lives full-time with the Veteran, or will do so if approved as a primary family caregiver

**Who can be a representative?**
A representative can be a Veteran&#39;s or service member&#39;s:

- Court-appointed legal guardian
- Special guardian
- Holder of durable power of attorney for health care
- Another designated health care agent

**What is a secondary family caregiver?**
Secondary family caregivers are approved by the Program of Comprehensive Assistance for Family Caregivers to be a back-up to the primary family caregiver. They can the Veteran&#39;s or service member&#39;s:

- Parent
- Spouse
- Son or daughter
- Step-family member
- Extended family member
- Someone who lives full-time with the Veteran, or will do so if approved as a secondary family caregiver

**How can I get a stipend?**
You may be eligible for a stipend if you are the primary family caregiver. Monthly stipends can be given in acknowledgement of the sacrifices you make to care for a seriously injured eligible Veteran.
