### ISSUE TITLE
Content guidance and support for medical records: Vaccines domain

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#53347]
## Issue Description

We need to give content support on the medical records section of the health apartment product. This work includes reviewing screens to make sure it meets VA.gov's plain langue and style standards. 

Artifacts provided by product team:

- Link to or attach user flows:
     - [User flow](https://www.sketch.com/s/0803544d-e78c-423a-a70e-7db01a9a31c7/a/MybMyWw) This is tentative, pending IA research findings. 
- Link to prototype or mockups (these will be adjusted continuously until usability testing; more screens may be added later):
     - Health history (Medical records) landing page [Desktop](https://www.sketch.com/s/f6118ebb-966d-4f83-afba-f9e987b65eac/a/MybDm39)
     - Vaccines list page [Desktop](https://www.sketch.com/s/f6118ebb-966d-4f83-afba-f9e987b65eac/a/uuid/8B956FE2-A63F-48C8-B8F1-FF93329ACE0E)
     - Selected vaccine details page [Desktop](https://www.sketch.com/s/f6118ebb-966d-4f83-afba-f9e987b65eac/a/uuid/D898C623-9070-42F2-841A-A859BFC98D09)
- Download modal (https://www.sketch.com/s/f6118ebb-966d-4f83-afba-f9e987b65eac/a/7y00pyY)
---
## Tasks
- [x] Review and edit screens 

## Acceptance Criteria
- [x] Product team has final content

**Comment by aliyahblackmore** [comment]
**Update:** Laura and I did a review. Laura added comments on the sketch screens.

**Comment by aliyahblackmore** [comment]
Hi Laura - As we chatted, this a word document with drafted content for the health history screen.  I referenced the [content brief](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/digital-health-modernization/mhv-to-va.gov/medical-records/data-domains) and the [IA recommendations](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/mhv-medical-records.md).

**Comment by laurwill** [comment]
Provided updated content for health history landing page and vaccines domain in intake ticket.

**Comment by RLHecht** [comment]
Closing this out. Will open new tickets for work to do after midpoint.
