### ISSUE TITLE
Update Folder Destination in sidekiq for Education's daily vetsgov.spl files

### ISSUE THREAD

**Issue by RileyRPM** [department-of-veterans-affairs/va.gov-team#53364]
To learn more about contributing to the Design System or requesting new components, requesting changes to existing components, and reporting bugs, go here.
https://design.va.gov/about/contributing-to-the-design-system/

---
Sidekiq has two automated jobs for Education benefits 
   307_xxx_vetsgov.spl
   351_xxx_vetsgov.spl
The Pass/Fail of that transfer is logged in #vsa-education-logs. The "spool files" are sent to a folder location on a Philly SFTP server. We need someone to just update the Folder location on that server to improve downstream automation improvements as that file gets sent to other applications. 

***

- [ ] Update file location
- [ ] Test (but how??)

**Comment by RileyRPM** [comment]
Awaiting additional information by Chris Marino RE: Folder location

**Comment by caw310** [comment]
This isn't a DST item so removing label and unassigning myself.

**Comment by christophermarino2** [comment]
The files just need to be sent to a new folder (same SFTP server).

307_xxx_vetsgov.spl should be sent to TIMS_SPOOL_FILES\rpo307
351_xxx_vetsgov.spl should be sent to TIMS_SPOOL_FILES\rpo351

**Comment by RileyRPM** [comment]
Hey @caw310 , do you know to whom it should be assigned?

**Comment by caw310** [comment]
@RileyRPM I don't.

**Comment by rmtolmach** [comment]
I did not get around to this ticket this sprint (I'm going on PTO, so my sprint ends today).

**Comment by rmtolmach** [comment]
@gia-lexa, please break this up into smaller tickets if you need to.

**Comment by holdenhinkle** [comment]
Use new periodic syntax for this instead Sidekiq scheduler.

**Comment by rmtolmach** [comment]
@RachalCassity to do discovery

**Comment by RachalCassity** [comment]
@RileyRPM When initializing the SFTPWriter, are there any params passed to determine where the file is coming from? It seems as though multiple services utilize the SFTPWriter and the writer may need specified data to ensure the other services are not affected.

**Comment by laineymajor** [comment]
spoke with Chris, and we will circle back to this once he returns from being OOO.

**Comment by laineymajor** [comment]
This one is being carried over to the next sprint due to the VA contact's schedule.
