### ISSUE TITLE
VAOS alert message - HSRM is unavailable 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#53370]
## Description
When the HSRM is unavailable, the system does not return Community Care appointments to the VAOS app which may cause the Veteran to be confused that they are missing their CC appointments. When the frontend receives a response error from the backend services when fetching in person appointments, VAOS should display an alert message to the Veteran. 

---

## Acceptance Criteria
Background: the `va_online_scheduling_vaos_v2_next` toggle is on

Given the user is in the VAOS homepage
When the frontend code receives an error when fetching in person appointments
Then user will see an alert message 
And page content matches the [copy doc]() 

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by JRRoof** [comment]
Details oof HSRM error Marcy received in Staging:

**Comment by JRRoof** [comment]
https://staging-api.va.gov/vaos/v2/appointments?_include=facilities,clinics&start=2023[…]tatuses[]=arrived&statuses[]=fulfilled&statuses[]=cancelled
image.png
"failures": [
      {
        "system": "VSP",
        "status": "500",
        "code": 10000,
        "message": "Could not fetch appointments from Vista Scheduling Provider",
        "detail": "icn=1013120820V528557, startDate=2023-01-08T00:00Z, endDate=2024-03-08T00:00Z"
      },
      {
        "system": "HSRM",
        "id": "d8a87534-4216-4f00-9a33-3ee0bacf5039",
        "status": "500",
        "code": 9008,
        "message": "There were 2 problems retrieving appointments from HSRM:  Message #1:Could not get CC Appointments from the Mobile HSRM Service.  Message #2:Could not get CC Appointment Request from the Mobile HSRM Service.",
        "detail": "Detail #1:Source System: HSRM, icn=1013120820V528557, start=2023-01-08T00:00Z, end=2024-03-08T00:00Z, detail: 500: {\"id\":\"905ab3fe-1ec2-4ca2-8492-a5ac929bb046\",\"traceId\":\"162965ee8e544593764be219d1ac3504\",\"code\":500,\"message\":\"Failed to fetch booked appointments\",\"errorCode\":2003,\"detail\":\"400: \",\"meta\":{\"upstreamErrorSource\":\"hsrm-cc-service\"}}  Detail #2:Source System: HSRM, icn=1013120820V528557, start=2023-01-08T00:00Z, end=2024-03-08T00:00Z, detail: 500: {\"id\":\"c984f30e-dd00-4aec-86b6-c3bff5f158c9\",\"traceId\":\"f9af55462588ecd60d1ec63688677292\",\"code\":500,\"message\":\"Failed to fetch requests\",\"errorCode\":2000,\"detail\":\"400: \",\"meta\":{\"upstreamErrorSource\":\"hsrm-cc-service\"}}"
      }
    ]
  }
}

**Comment by ldelacosta** [comment]
@outerpress - Please let us know what the message should state if HSRM is unavailable. If you have any questions, please let me know.

**Comment by outerpress** [comment]
@ldelacosta see my comment on the related VVS ticket [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/53372#issuecomment-1444735665). That _should_ cover this situation too.

**Comment by ldelacosta** [comment]
We implemented this work in #55068, #55280 and #55279. Closing out this ticket as we no longer need it. cc: @JRRoof @outerpress
