### ISSUE TITLE
SOCKS access for Eddie Glenn

### ISSUE THREAD

**Issue by navaeddie** [department-of-veterans-affairs/va.gov-team#53397]
### Your Name

Eddie Glenn

### Your Email

eddieglenn@navapbc.com

### Your Role and Team

Software Engineer - Disability Benefits Experience

### Product Manager (PM) name and email

Rakshinda Aslam - rakshinda.aslam@agile6.com

### Product Owner (PO) name and email

Matthew Self - matthewself.dsva@gmail.com

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDKN2Z/KobEK1xFidBY51Qgd79voXebInrW5CqkGWwYZ9TyLliuH5XNj89X7ksE5rl0LdXfxLJnrJRG2MyLmALudMotFW3oYUQUUArB2m4jQz1S9+a5fcdm0WBCgoGyC+EAohxcigrzcp5L68RSvoWLCLoboFOSI1Sbhdd/bT2ZXd80hg/YKmTYM8cNxdJK99FbhFQ3FAEYbIaFEPNivBE8how2a1iVGPI6THDfVh3BF04NkAR77tX5lzS9lR6hoW/jweZ/kXaGzEjniSySBbiZnLsa0liTdkyrYbwgsPUs1q4j+qKerCRMWOybzRqLI2gVYUbtqnXPfsqUAuanVSH9vYvC+NJskCFlSqyhxG7MLJDSlpDcWixtbUNiRae1zScY7/FOq9ROJB3cN8mRHPlo3ntR5JxVa+NEEGE5q1B9l+ql24NUADiLsFrd3N30yOuCHMEnyjMRRGo0vEGNSroqBnGqMzVVJLQRTDhpH9wNoXZt3vxHTfVWgaJXOQE+ysE= eddieglenn@Eddies-MacBook-Pro.local

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by navaeddie** [comment]
I closed this because I thought I had done it wrong, see [support ticket for background](https://dsva.slack.com/archives/CBU0KDSB1/p1675955604150959), but in talking to another developer, I started to wonder that maybe it's ok to move this forward.

**Comment by rmtolmach** [comment]
@navaeddie  Access granted ✅ 

Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html 

Reach out in #vfs-platform-support if you have any trouble.
