### ISSUE TITLE
IA design - Medical Records

### ISSUE THREAD

**Issue by kristinoletmuskat** [department-of-veterans-affairs/va.gov-team#53403]
IA design for medical records will be done in chunks - here's a draft version of how it will progress

1.  Organizational structure, URLs, and breadcrumbs for the 3 sections that will include medical records features (i.e. lab and test results, health history, download medical records) for Phase 0 will be done together
2. Secondary navigation design for this product will be done along with #1, also specific to Phase 0, also to include all 3 sections related to medical records
3.  Entry points and crosslinks will be identified as part of the phased launched work, as these will change as the medical records features moves through the different launch phases along side other features also launching
4. Broader secondary nav design for the overall patient portal will be done independently of each product launch and will be integrated at a later date. 
5. Redirects will be identified as part of the phased launch documentation and handled independently

**Comment by mnorthuis** [comment]
@alexiawunder @BobbyBaileyRB Here is the initial IA design work for the 3 sections of medical records

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/mhv-medical-records.md

Please reach out with questions or let myself or @kristinoletmuskat know if you want to talk through anything here.

**Comment by kristinoletmuskat** [comment]
I updated our IA guidance with the latest we've discussed @alexiawunder @coultonbunney-usds @BobbyBaileyRB 

We are also doing some work on our github folders, so the new url is: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/mhv-medical-records.md

**Comment by mnorthuis** [comment]
@heyjoni FYSA

**Comment by mnorthuis** [comment]
Primary IA design for medical records is complete.  IA will continue to support through build, but closing this work effort out.
