### ISSUE TITLE
BTSSS Content Intake Request from SW Public Websites

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#53402]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more unauthenticated pages, online forms, apps, or tools on VA.gov
- [x] Making revisions to one or more existing VA.gov pages
- [ ] Something else 
 
 *Give a brief description of what your team needs support with.*

We are going to update the Veteran experience on the [travel reimbursement page](https://www.va.gov/health-care/get-reimbursed-for-travel-pay/) to deep-link authenticated users directly to BTSSS. We will likely build a react widget similar to the Cerner react widgets (e.g., [refill prescriptions](https://www.va.gov/health-care/refill-track-prescriptions/)) in order to accommodate authenticated and unauthenticated users differently.

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [ ] Yes
  - [ ] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
## When do you expect to launch your product to 100% of users?
  
~~Early Q2, if things go well.~~  We've learned that Platform Collab Cycle doesn't need/want to review this, so could / will implement as soon as content is available.
 
## Supporting artifacts
*Please provide supporting artifacts as available.*

- Link to product outline: [PW BTSSS epic](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9157)
- Link to or attach user flows: Details in [discovery ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12338)
- Link to prototype or mockups: 
- Link to any epics/issues that may be helpful: above

## Will this work be going through the Collaboration Cycle?
- [x] Yes (probably)
- [ ] No

## When does this work need to be done?
- Estimated launch date: 
- Estimated staging review date:
- Content and IA work needed by: March 15

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [x] No, but I'd like to schedule time to talk about this request
- [ ] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: Dave Conlon
-	Product manager: Wes Rowe
-	Designer: Jordan Wood
-	FE engineer: Josh Mills
-	Product/team Slack channel: #sitewide-public-websites

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by wesrowe** [comment]
Mock-ups of the proposed widget (with "bad copy"):
<img width="334" alt="image" src="https://user-images.githubusercontent.com/4054752/218901412-b018b3e5-585f-4249-a7b3-ed7a138ec2ff.png">
<img width="309" alt="image" src="https://user-images.githubusercontent.com/4054752/218901431-50089039-7e74-49b8-ae51-6d24ce9938bd.png">

**Comment by RLHecht** [comment]
Thanks for adding this, @wesrowe I'll create an internal ticket for our team to provide the content for this.

**Comment by artsymartha68** [comment]
I asked "If this is a common component being reused then a quick a11y page review may be all that’s needed….?"

Danielle verified: "Yes. This is simply replacing existing content with a standard component on a templated Drupal page."

So a quick a11y validation should be all that's required. 





Danielle Thierry
  [5 minutes ago](https://dsva.slack.com/archives/C01K37HRUAH/p1676480681720919?thread_ts=1675897616.722439&cid=C01K37HRUAH)
Yes. This is simply replacing existing content with a standard component on a templated Drupal page.

**Comment by jilladams** [comment]
We've revised timing in ticket body here -- we've learned that Platform Collab Cycle doesn't need/want to review this, so could / will implement as soon as content is available. (Vs. aiming for Q2)

**Comment by laurwill** [comment]
Hi @wesrowe , here's suggested content for this widget. Does a simple action link work for the auth version? That's how the existing link to AccessVA is styled on the live page.

**Unauth widget content**
 
[H3] Sign in to file a travel pay claim
 
Sign in with your existing **Login.gov**, **ID.me**, **DS Logon**, or **My HealtheVet** account. If you don’t have any of these accounts, you can create a free **Login.gov** or **ID.me** account now.
 
Sign in or create an account [button to sign in modal]
 
**Auth widget content**
 
Go to BTSSS to file a claim [action link]

**Comment by wesrowe** [comment]
This content is being discussed in a [slack thread](https://dsva.slack.com/archives/C52CL1PKQ/p1678999585255679?thread_ts=1678993790.231659&cid=C52CL1PKQ).

**Comment by RLHecht** [comment]
This work is completed. Closing ticket. If further work needs to be done we can open a new intake request.
