### ISSUE TITLE
Audit forms, tools, & services that require DS Logon

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#53412]
## Issue Description
DS Logon will start phasing out in May 2023. We need to identify VA.gov pages and tools that encourage or require users to authenticate with DS Logon. Then we need to connect with stakeholders and decide if any changes are needed.

The DS Logon mentions seem to fall into 2 main categories: TRICARE/milConnect and eBenefits.

**Pages and tools that say to use DS Logon for TRICARE or milConnect:**
- Get your medical records (accordion section links to TRICARE): https://www.va.gov/health-care/get-medical-records/
- Get military service records: https://www.va.gov/records/get-military-service-records/
- SGLI life insurance: https://www.va.gov/life-insurance/options-eligibility/sgli/
- FSGLI life insurance: https://www.va.gov/life-insurance/options-eligibility/fsgli/

**Pages and tools that say to use DS Logon for eBenefits:**
- COE: https://www.va.gov/housing-assistance/home-loans/how-to-request-coe/
- SAH: https://www.va.gov/housing-assistance/disability-housing-grants/how-to-apply/
- Prosthetic socks: https://www.va.gov/health-care/order-prosthetic-socks/

Note: COE and SAH are both moving to VA.gov, with target dates before DS Logon phase out starts. 

**Other:**
- SECO external tool on this page: https://www.va.gov/careers-employment/family-resources/

---
## Tasks
- [ ] Audit pages for DS Logon
- [ ] 

## Acceptance Criteria
- [ ]

**Comment by laurwill** [comment]
@jeana-adhoc @tbaker1026 , here's the ticket where we're tracking any forms and tools that require DS Logon to access. DS Logon will no longer be an option on VA.gov (timeline for communicating with Veterans about the change is May to September 2023). 

I believe Veteran’s Request for Prosthetic Socks (VA Form 2345) is the only one that requires DS Logon and isn't already slated for digitization with your team. 

Could you let us know here if you're able to move this up in the forms digitize priority list? If not, we may need to temporarily remove all online options for prosthetic socks, if there's a gap between DS Logon retirement and when this form gets digitized. Thank you!

**Comment by laurwill** [comment]
Documenting updates here:
- COE is launched to 100%, that's all set
- SAH digitization is in process, should be all set by time of DS Logon sunset
- Danielle let us know that prosthetic socks team wants to remove online option entirely after 3/17/23, rather than digitize
- All non-VA sites and tools that currently use DS Logon will continue to do so, and we can continue to link to them and mention that you'll need to sign in with DS Logon

@RLHecht , we can close this ticket now. I think the only related ticket we need to open is a ticket to remove the eBenefits option from the prosthetic socks page after 3/17. We can confirm that separately with Danielle.

**Comment by RLHecht** [comment]
Thanks, Laura. I created the ticket for the change on prosthetic socks: #54766.

Closing this one!
