### ISSUE TITLE
Fine tune Sidekiq UI access

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#53420]
## Description

It appears that with the current Sidekiq UI implementation, we have [Github Oauth implemented](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/github_authentication/sidekiq_web.rb#L20), but we use a blanket Github team to provide access. (See settings... same[ Github team id in all envs](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/vets-api/dev-settings.local.yml.j2#L820)). This means if you’re on the Github team, you have access to Sidekiq UI in **ALL** envs. I think we should revisit this implementation and possibly create a team per environment for SIdekiq UI access, to provide more tightly scoped access control.

The risk here is that prod Sidekiq UI provides access to kill workers, delete jobs...all of the above perms, which includes **a lot** of risk.

[Current va.gov-sidekiq team](https://github.com/orgs/department-of-veterans-affairs/teams/va-gov-sidekiq/members)  - single use for all envs

Solution: create four of these teams and update the settings.yml to the team id per environment

**Comment by laineymajor** [comment]
Just adding your name for now until we figure out who should take this @LindseySaari

**Comment by LindseySaari** [comment]
[PR for dev env ](https://github.com/department-of-veterans-affairs/devops/pull/12617)

**Comment by LindseySaari** [comment]
PRs for higher envs: 
1. [Manifest PR](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/1547)
2. [Devops PR](https://github.com/department-of-veterans-affairs/devops/pull/12623)

**Comment by LindseySaari** [comment]
Will be testing prod after todays deploy (all other envs have already been deployed, as they are 100% EKS)

**Comment by LindseySaari** [comment]
Prod oauth still works after the team based changes ✅
