### ISSUE TITLE
GIDS: Order crosswalk issues by number of GI bill students.

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#5342]
As an Education Services Team Member, I need the Crosswalk data discrepancies to sort the facilities descending by the number of GI Bill students at the facility so that I can prioritize fixing the facilities with the most students.

## Assumptions:
1. The # of GI Bill students uses the same data source as is presented on the Profile page.

## Acceptance Criteria
1. The Crosswalk Partial Matches Issues table has a "# GI Bill Students" column.
2. The Crosswalk Partial Matches Issues table is sorted by "# GI Bill Students" descending.

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/560

**Comment by delli-gatti-michael** [comment]
Changes are now in Staging. Closing this issue
