### ISSUE TITLE
CT 116: Remove dead VET TEC search code 

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#5343]
As a developer, I need to remove unused VET TEC search code so that there is not dead code in the repository.

## Assumptions:
1. N/A

## Acceptance Criteria
1. Existing VET TEC search functionality is not impacted by the removal.
2. All dead VET TEC search code is removed from the vets-website repository.
3. All dead VET TEC search code is removed from the GIDS repository.

**Comment by dmccurdybah** [comment]
PR: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/5343

Can be tested on vets-website branch `bah-institution-cleanup`

**Comment by dmccurdybah** [comment]
GIDS PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/564

Can be tested on gibct-data-service branch `bah-remove-dead`

**Comment by sonntag-adam** [comment]
Testing passes QA

**Comment by sonntag-adam** [comment]
In staging closing story.
