### ISSUE TITLE
Analytics Reporting Request for VBA

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#5344]
# Metrics Reporting Request

## What this form is for

Use this template to request performance, usability, or outcomes va.gov metrics that is difficult to access or that needs analytics interpretation.

Insights will usually provide data reports within the current sprint, but if there is time-sensitivity, please note them in "additional comments."

## Instructions

Please fill out the following sections:
- [x] Description
- [x] Timeframe for Analytics Requested
- [x] Analytics to Track Down
- [x] Which Product Questions are you trying to answer?
- [x] Additional Comments

## Description
**Who is this request for?**
- Andrea S will take this back to VBA & the director of Office of Business Process Integration for a meeting at 3pm ET on Monday, 2/3/20.

## Timeframe for Analytics Requested
Month over Month;
or, Month vs. Month

## Analytics to Track Down
- Benefits pages

## Which Product Questions are you trying to answer?
Use the metrics to better communicate with stakeholders on what is going on on VA.gov & how does traffic on VA.gov impact the bottom line.
- What are veterans using the most?
- Special interest areas

## Additional Comments
An example impact: A new law was passed, affecting XY Facilities. XY Facilities now has an uptick in call center calls and more foot traffic. Can we see this from VA.gov metrics?

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Request Specific Acceptance Criteria
- [ ] Benefits that can be pulled
- [ ] Types of visualizations that we can provide & what kind of business question each answers

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
@joanneesteban doing some board clean-up -- closing this unless we hear further need
