### ISSUE TITLE
[Monitoring] Refine Forward Proxy Monitors based on feedback

### ISSUE THREAD

**Issue by mynar7** [department-of-veterans-affairs/va.gov-team#53440]
## Description
This ticket encapsulates refining the [Forward Proxy Monitors](https://vagov.ddog-gov.com/dashboard/9dk-y7n-6vf/platform-monitors-alerts) based on feedback provided by @ph-One in [48548](https://app.zenhub.com/workspaces/platform-tech-team-2-633efe4ca5a428e5294d7ade/issues/gh/department-of-veterans-affairs/va.gov-team/48548)

## Resources 
- [Forward Proxy Monitors](https://vagov.ddog-gov.com/dashboard/9dk-y7n-6vf/platform-monitors-alerts) 
- [Previous Ticket #48548](https://app.zenhub.com/workspaces/platform-tech-team-2-633efe4ca5a428e5294d7ade/issues/gh/department-of-veterans-affairs/va.gov-team/48548)

## Acceptance Criteria
- [Platform - AWS Forward Proxy (HAProxy) High Number of Frontend Requests](https://vagov.ddog-gov.com/monitors/102228)
  - [x] needs a description
  - [x] metric should sum by proxy and deployment_env
  - [x] consider if there is a way to use a percentage instead of absolute values for alerting (e.g., do we know the max number of requests a proxy can handle before falling over)
  - [x] No discernible absolute threshold found. Monitor changed from threshold alert to anomaly detection. [New monitor can be found here](https://vagov.ddog-gov.com/monitors/111835)
---
- [Platform - AWS Forward Proxy (HAProxy) High Number of Backend Requests](https://vagov.ddog-gov.com/monitors/102230)
  - [ ] needs a description
  - [x] metric should sum by proxy and deployment_env
  - [ ] consider if there is a way to use a percentage instead of absolute values for alerting (e.g., do we know the max number of requests a proxy can handle before falling over)
  - [x] No discernible absolute threshold found. Monitor changed from threshold alert to anomaly detection. [New monitor can be found here](https://vagov.ddog-gov.com/monitors/111836)
---
- [Platform - AWS Forward Proxy (HAProxy) High Number of Sessions](https://vagov.ddog-gov.com/monitors/102165)
  - [x] metric should sum by proxy and deployment_env
  - [ ] consider if there is a way to use a percentage instead of absolute values for alerting (e.g., do we know the max number of requests a proxy can handle before falling over)
  - [x] No discernible absolute threshold found. Monitor changed from threshold alert to anomaly detection. [New monitor can be found here](https://vagov.ddog-gov.com/monitors/111834)
---
- [latform - AWS Forward Proxy (HAProxy) High Number of Connection Attempts](https://vagov.ddog-gov.com/monitors/102225)
  - [ ] needs a description
  - [x] metric should sum by proxy and deployment_env
  - [ ] consider if there is a way to use a percentage instead of absolute values for alerting (e.g., do we know the max number of requests a proxy can handle before falling over)
  - [x] No discernible absolute threshold found. Monitor changed from threshold alert to anomaly detection. [New monitor can be found here](https://vagov.ddog-gov.com/monitors/111833)
---
- [Platform - AWS Forward Proxy (HAProxy) Connection Errors Rate](https://vagov.ddog-gov.com/monitors/108298)
  - [x] needs a description [of what an alert from this monitor means for the person getting the alert]
  - [x] update alerting chain to send to the [#oncall slack channel](https://vfs.atlassian.net/wiki/spaces/OT/pages/2513633298/Create+Monitors+and+Alerts+in+Datadog#Set-up-the-Final-Alert-Chain-(staging%2C-prod-alerts)) if this is production 
---
- [Platform - Forward Proxy BE Low 2xx Count](https://vagov.ddog-gov.com/monitors/107953) and  [Platform - Forward Proxy FE Low 2xx Count](https://vagov.ddog-gov.com/monitors/102231)
  - [ ] consider removing these monitors. a low number of 2xx return codes could signify a frontend/backend used infrequently and is not necessarily an issue. this would be a good candidate for a widget (informational) but not something that should trigger an alert. https://vagov.ddog-gov.com/monitors/103404 covers 5xx, and https://vagov.ddog-gov.com/monitors/103409 checks for alive backends, which would cover what I believe the intent of the low 2xx's intent is (no traffic, or we are erroring out)

## Refinement Guidance - Check the following before working on this issue: 
- [x] _Team label assigned ("platform-tech-team-2")_
- [x] _Epic assigned (if needed)_ 
- [x] _Estimated (points assigned)_
- [x] _Sprint assigned (once planned)_
- [x] _Team member(s) assigned_

**Comment by mynar7** [comment]
Monitors outside of the FWD proxy connection errors rate should be informational widgets, not alerts. After investigating, there were no discernible alert thresholds discovered that would indicate a problem with the forward proxy. The monitors for amount frontend and backend requests were removed, and I recommend removing the remaining monitors or converting them to instead monitor for an absence of traffic instead. 

Put another way, higher requests or connections to do not necessitate a problem with the system. However, a lack of requests or connections could potentially indicate a problem.

**Comment by mynar7** [comment]
Instead of just deleting the threshold alerts monitoring connections, sessions, and requests, I've changed them to be anomaly detection alerts instead. Because these metrics have no absolute numbers that define when the system is failing, I set up alerts to detect large swings in behavior over a short period of time. 

I recommend the team evaluate the usefulness of the new alerts over a period of time and adjust the monitors from there.

**Comment by rsmithadhoc** [comment]
I'm going to set this back to the sprint backlog and unassign this for someone to pick up. I believe we were staying away from anomaly monitors because the system fluctuates quite a bit, so there might be a lot of false positives from normal usage picking up. I think we will want to have someone convert them over to percentage based monitors.

**Comment by jhouse-solvd** [comment]
This is a feedback ticket for tracking, but I've un-assigned it from the current sprint so we can look at it in the coming sprint.

**Comment by it-harrison** [comment]
Switching to anomaly monitors:
* [backend](https://vagov.ddog-gov.com/monitors/119976)
* [frontend](https://vagov.ddog-gov.com/monitors/120093)
* [total sessions](https://vagov.ddog-gov.com/monitors/120094)
* [connection attempts](https://vagov.ddog-gov.com/monitors/120095)

And deleting previous threshold / anomaly monitors.
