### ISSUE TITLE
T3 #08200978 Veteran cannot see claim

### ISSUE THREAD

**Issue by jaredcunha** [department-of-veterans-affairs/va.gov-team#53457]
## Description
Veteran cannot see current status of his claim. eBenefits doesn't list him as having an active claim. Submitted claim in July of 2022. It moved to preparation for decision 9 days later. Only knows this because he called number to get an update.

VA App and Website does not show him that information. eBenefits is not showing anything either, saying he has zero claims.

Veteran provided screenshot of mobile app
<img width="225" alt="screen" src="https://user-images.githubusercontent.com/1094951/218822980-d0fc2263-5a34-43ff-b7ee-ff9ec15c6c50.png">

**Salesforce ticket ID:** 
08200978

**Date issue reported:**
8/10/22

**Application ID number, if provided:**

**Issue Veteran is experiencing:**

**Comment by HeatherWidmont** [comment]
We are going to close this, but it can be reopened as a separate ticket with information that will allow it to be reproducible @Kimberley2019
