### ISSUE TITLE
T3 #08155597 Veteran unable to see claim

### ISSUE THREAD

**Issue by jaredcunha** [department-of-veterans-affairs/va.gov-team#53451]
## Description

Veteran logged in to check status of claim on Aug 1, 2022 and it showed still in evidence gathering stage. Claim was visible on the Check My VA Claim Page and had the Upload Documents option and all the claim info. Tried to check status on August 3 and it said that he didn't have any submitted claims. Cannot see the claim that was processing two days before and spoke with VA Compensation they said the claim was still in the system and processing and not sure why it's not appearing on the website.

**Salesforce ticket ID:** 
08155597

**Date issue reported:**
8/4/22

**Application ID number, if provided:**

**Issue Veteran is experiencing:**

**Comment by HeatherWidmont** [comment]
We are going to close this, but it can be reopened as a separate ticket with information that will allow it to be reproducible @Kimberley2019
