### ISSUE TITLE
T3 #09035225 Claim appears delayed

### ISSUE THREAD

**Issue by jaredcunha** [department-of-veterans-affairs/va.gov-team#53458]
## Description

Veteran had claim in phase 3 and went to upload documents. Selected PDF and the window got stuck on "uploading document"

Now the status of uploading documents and submit are gone and it's been on phase 3 for 1.5 months. Things it might be delayed. 

**Salesforce ticket ID:** 
09035225

**Date issue reported:**

**Application ID number, if provided:**

**Issue Veteran is experiencing:**

**Comment by HeatherWidmont** [comment]
We are going to close this, but it can be reopened as a separate ticket with information that will allow it to be reproducible.
