### ISSUE TITLE
YR: Research Integration with EDU Yellow Ribbon SharePoint

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#5345]
As a developer, I need to research and verify that GIDS is able to integrate with the Yellow Ribbon SharePoint so that I can develop a plan to update the GIDS yellow ribbon data.

## Assumptions:
1. Access to [Yellow Ribbon Sharepoint Site](https://vaww.infoshare.va.gov/sites/educationservice/223/223C/Lists/Dashboard1/AllItems.aspx) is granted by EDU.

## Acceptance Criteria
1. Integration between GIDS and the YR Sharepoint is verified.
2. A plan for how to update the GIDS YR data using the YR SharePoint is documented.

**Comment by zurbergram** [comment]
Link has changed https://vaww.infoshare.va.gov/sites/educationservice/223/223C/Lists/Yellow*20Ribbon*20Database/AllItems.aspx

**Comment by zurbergram** [comment]
From a `dsva-vagov-staging-deployment-vagov-staging-gi-bill-data-service` you can reach https://vaww.infoshare.va.gov/sites/educationservice/223/223C/Lists/Yellow*20Ribbon*20Database/AllItems.aspx but recieve a 401 without correct username and password or credentials

**Comment by zurbergram** [comment]
REST Endpoint url to get first 100 items https://vaww.infoshare.va.gov/sites/educationservice/223/223C/_api/web/lists/Yellow_x0020_Ribbon_x0020_DatabaseList/items

Sharepoint REST Api
https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-lists-and-list-items-with-rest#retrieve-items-as-a-stream
https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-lists-and-list-items-with-rest
https://lostisland.github.io/faraday/usage/streaming
https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests#page-through-returned-items

**Comment by zurbergram** [comment]
Question about credentials: https://dsva.slack.com/archives/CBU0KDSB1/p1581019874039300

**Comment by zurbergram** [comment]
Slack thread about credentials https://dsva.slack.com/archives/CBU0KDSB1/p1581346734109000

It appears we need to reach out to VSP Operations to request help with obtaining credentials of some sort

**Comment by shawkey-daniel** [comment]
Reached out to Joseph Kemer and Venkatesh Pola regarding requirements to access Sharepoint from GIDS. No response. As of meeting with EDU on 2/24/2020, Brian Grubb from EDU recommended close issue and just update the file manually.
