### ISSUE TITLE
EKS Header solution for testing prod

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#53469]
## Description
We should have the ability to test vets-api prod through the full stack (via requests coming from vets-website) before turning up traffic to 100% EKS. A possible solution is to pass a header e.g. EKS=true, which will allow the forward proxy to route the traffic to EKS and not BRD. This will allow us to test prod in an A/B fashion for issues before fully rolling out. 

Note: Prod testing will be limited as we don't exactly have test users (unless someone who is a Veteran volunteers), but we can test non-auth'd endpoints or endpoints that don't require you to have Veteran status.

### Issues to test for AFTER this is implemented:
1. CORs
2. Certs
3. Ping healthcheck endpoints
4. Login
5. File upload

**ACTION ITEMS**
- [x] investigate what the devops cop did for dev
- [x] if there is a solution from ^^, we can mimic the solution
- [x] mimic (if applicable) the solution from the devop cop
- [ ] Find which routes were used first
- [ ] Create plan for which EKS routes will be used

**Comment by laineymajor** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Tech-Team-1-633af4074573d06c3cda142a/issues/department-of-veterans-affairs/va.gov-team/53469?planning-poker) with Zenhub @considerable

**Comment by laineymajor** [comment]
@considerable can you please provide an estimate for this ticket? Thanks!

**Comment by considerable** [comment]
@laineymajor can we have a "guest speaker" to from the FrontEnd community to help us with this?
All I can see in GitHub is that FrontEnd people have this concept of [End-to-end (E2E) / Browser tests in Cypress](https://github.com/department-of-veterans-affairs/vets-website/blob/main/README.md#end-to-end-e2e--browser-tests).
This is how we might test full-stack (requests coming from vets-website), for which CoP DevOps was never involved, but CoP FrontEnd might.

**Comment by laineymajor** [comment]
@igor did you review the action items in this ticket? Also, if you need to learn something from a member of a CoP, please reach out to them directly.... they don't need to attend one of our meetings.

**Comment by laineymajor** [comment]
@RachalCassity will start this ticket by creating the headers. Will then circle-back to this after completing other work.

**Comment by RachalCassity** [comment]
EKS Headers Added in this [PR](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/1553)

**Comment by RachalCassity** [comment]
How to test CORs and upload:

1. Go to staging.va.gov
2. Login
3. Go to https://staging.va.gov/health-care/schedule-view-va-appointments/
4. Go to Make an Appointment
5. Create an Appointment
6. Upload a file for appointment.

**Comment by RachalCassity** [comment]
https://github.com/department-of-veterans-affairs/devops/pull/11174/files

**Comment by RachalCassity** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/39687

**Comment by RachalCassity** [comment]
Do we need to configure revproxy for other envs?  revproxy was setup for dev.

- https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/371/files
- https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/373/files

**Comment by RachalCassity** [comment]
Dev EKS Header PR and issue:

- https://github.com/department-of-veterans-affairs/devops/pull/10816/files
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/37037

**Comment by RachalCassity** [comment]
[EKS Devops Header PR](https://github.com/department-of-veterans-affairs/devops/pull/12641)

**Comment by laineymajor** [comment]
Reviewed PRs, connected with Lindsey via slack, 
Made a header for the EKS config

- need to look into what routes were first used
- checked with DevOps CoP

**Comment by LindseySaari** [comment]
This looks good to me (but my review doesn't have any meaning in the devops repo)! I would ping the devops CoP to review once more, but the changes logically make sense.

**Comment by RachalCassity** [comment]
@LindseySaari I pinged Oseas, Kyle, Ian, and Peter

**Comment by laineymajor** [comment]
Rachal circling back to this now

**Comment by RachalCassity** [comment]
Kyle is reviewing the PR

**Comment by laineymajor** [comment]
Rachal made updates per Kyle's suggestions... submitting additional PR
- [ ] Kyles approval

**Comment by RachalCassity** [comment]
Still in review with Kyle. Should be okay to go though.

**Comment by RachalCassity** [comment]
Kyle did approved the PR

**Comment by LindseySaari** [comment]
4 approvals! We can merge @RachalCassity  https://github.com/department-of-veterans-affairs/devops/pull/12641

**Comment by RachalCassity** [comment]
Testing syntax errors in staging

**Comment by RachalCassity** [comment]
This caused 500 errors. I have another PR ready

**Comment by laineymajor** [comment]
Thanks for the udpate!

**Comment by RachalCassity** [comment]
Need to test with Rebecca

**Comment by RachalCassity** [comment]
Testing with Lindsey and Kyle.
PR will be in review afterwards.

**Comment by RachalCassity** [comment]
Merge PR on Tueday!

**Comment by laineymajor** [comment]
No additional work needed. Needs to be merged on Tuesday.
