### ISSUE TITLE
 Create a rough-draft support document

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#53472]
We currently have a lot of ad hoc support processes, mostly involving word-of-mouth requests and selective email threads.

In order to be able to triage these requests effectively, we need to consolidate our support processes into a unified workflow.

We should create a rough-draft workflow for providing support in the form of a "good-better-best" or "now-later-someday" document.  This document should be actionable and detailed in the short term with ideas for improvement as time goes on.

This is NOT a manifesto. This is a reference.

AC:
- [x] Document created
- [ ] Document reviewed by all team members

**Comment by kjduensing** [comment]
[Lightweight project tracker board](https://github.com/orgs/department-of-veterans-affairs/projects/904)

[README.md](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/claim-appeal-status/Benefits%20Claim%20Appeals%20support%20tracker)

**Comment by jacobworrell** [comment]
Whole team will review before end of day.

**Comment by jerekshoe** [comment]
Looks good to me, I didn't know github had this functionality built-in. Only question I have is have we thought about what the flow looks like if we need more details than are initially provided?
