### ISSUE TITLE
srv/vets-api/secret/production certs

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#53498]
1.
- [x] Pull Request Made - [PR](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/1463)

2. Confirm certs are in the eks secret production dir
- [x]  dgi-prod.crt -> dgi.crt
- [x]  lighthouse.ext.prd.vbms.vba.va.gov.crt
- [x]  lighthouse.ext.prd.vbms.vba.va.gov.key
- [x]  lighthouse.ext.prd.vbms.vba.va.gov.p12
- [x]  lighthouse-prod-samltoken.xml
- [x]  services.vbms.vba.va.gov.crt
- [x]  wss.core.prd.vbms.vba.va.gov.crt

3. Confirm the certs in the directory are correct:
- [x]  dgi-prod.crt -> dgi.crt
- [x]  lighthouse.ext.prd.vbms.vba.va.gov.crt
- [x]  lighthouse.ext.prd.vbms.vba.va.gov.key
- [x]  lighthouse.ext.prd.vbms.vba.va.gov.p12
- [x]  lighthouse-prod-samltoken.xml
- [x]  services.vbms.vba.va.gov.crt
- [x]  wss.core.prd.vbms.vba.va.gov.crt

4. Another teammate confirm the certs are correct
- [x]  dgi-prod.crt -> dgi.crt
- [x]  lighthouse.ext.prd.vbms.vba.va.gov.crt
- [x]  lighthouse.ext.prd.vbms.vba.va.gov.key
- [x]  lighthouse.ext.prd.vbms.vba.va.gov.p12
- [x]  lighthouse-prod-samltoken.xml
- [x]  services.vbms.vba.va.gov.crt
- [x]  wss.core.prd.vbms.vba.va.gov.crt

**Comment by considerable** [comment]
The cert files look good as I tested them via Argo `>_Exec`:
```
nonroot@vets-api-web-5b46759f68-kdbrr:~$ ls -alR /srv/vets-api/secret/
```

**Comment by laineymajor** [comment]
@RachalCassity are we good to close this with the double check (above) from Igor?
