### ISSUE TITLE
Email Builder Follow Up 

### ISSUE THREAD

**Issue by manalo-soco** [department-of-veterans-affairs/va.gov-team#53496]
Configuration for CC team to Email Builder function in Salesforce

**Comment by manalo-soco** [comment]
@ATMiddleton  Can we add Ervin's profile to assignee? 
https://github.com/edpearson20

**Comment by edpearson20** [comment]
Contacted Enterprise Helpdesk (INC25974390) regarding tickets RITM8354358 and RITM8204005.  Apparently, the creation of the rule must be performed by the owner.  There does appear to be a designated owner of the vatechsuppsalesforce@va.gov email address.  I've since emailed Robert Kuehn (Program Analyst - Salesforce Development) for assistance.  Awaiting response.

**Comment by edpearson20** [comment]
Today, (Wednesday, Feb. 15th) Jeremy (EVSS), Todd Unger, Bob Kuehn, Abigail Ragonesi, and myself were in an impromptu meeting where we discussed the outstanding issue and potential solutions proposed by Todd involving distribution email inboxes versus group email inboxes.  Todd also, provided an OIT contact (sean.johnson5@va.gov) that may be able to better assist with the issue.  I will follow up with Jacqueline regarding the issue and include Sean as a potential solution provider.

**Comment by ATMiddleton** [comment]
Ervin requested a meeting with the team members who can assist.

**Comment by ATMiddleton** [comment]
@edpearson20 - requested meetings, however, no response...

**Comment by edpearson20** [comment]
Called and emailed Jacqueline Perry (OIT) regarding issue.  Awaiting response.  Also reached out to Robert Kuehn regarding issue for potential assistance.

**Comment by ATMiddleton** [comment]
Still awaiting transfer to VACO team.

**Comment by edpearson20** [comment]
INC26611499 opened 4/29

**Comment by edpearson20** [comment]
VA.gov Helpdesk - Email-to-Case Troubleshooting Meeting with Salesforce Development 4/4 3PM

**Comment by edpearson20** [comment]
After troubleshooting, it is determined that another ESD / VACO IT ticket is necessary.  Closing this Zenhub ticket and creating another for the current sprint.

**Comment by manalo-soco** [comment]
@edpearson20  can you please link the new Zenhub ticket here?
