### ISSUE TITLE
Confirm certificates in /srv/vets-api/secret directory

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#53503]
1. Make PR
- [ ]

2. Confirm certs are in the eks secret production dir
- [x] carma-signing.key
- [x] gibft-sfdc-signing.key
- [x] lighthouse_fast_track_api.key
- [x] sign-in-service-oauth-prod-key.pem
- [x] vagov-mobile-app.key
- [x] vets-api.key
- [x] check-in.lorota.v1.key
- [x] health-quest.key
- [x] logingov_oauth_prod_pub.pem    
- [x] sign-in-service-oauth-prod.pem
- [x] vagov-ssoe-saml-prod-cert.pem  
- [x] vet_verification.pem
- [x] dgi-prod.key
- [x] health-quest.lighthouse.key  
- [x] mobile_lh_health_api.key
- [x] sign-in-service-token-signing-prod-key.pem  
- [x] vagov-ssoe-saml-prod-key.pem   
- [x] vic-sfdc-signing.key
- [x] edu_sftp.key
- [x] idme_oauth_prod_pub.pem      
- [x] sign-in-service-token-signing-prod.pem
- [x] va_mobile.pem
- [x] vic-signing.key

3. Confirm certs are in the eks pod secret directory
- [x] carma-signing.key
- [x] gibft-sfdc-signing.key
- [x] lighthouse_fast_track_api.key
- [x] sign-in-service-oauth-prod-key.pem
- [x] vagov-mobile-app.key
- [x] vets-api.key
- [x] check-in.lorota.v1.key
- [x] health-quest.key
- [x] logingov_oauth_prod_pub.pem    
- [x] sign-in-service-oauth-prod.pem
- [x] vagov-ssoe-saml-prod-cert.pem  
- [x] vet_verification.pem
- [x] dgi-prod.key
- [x] health-quest.lighthouse.key  
- [x] mobile_lh_health_api.key
- [x] sign-in-service-token-signing-prod-key.pem  
- [x] vagov-ssoe-saml-prod-key.pem   
- [x] vic-sfdc-signing.key
- [x] edu_sftp.key
- [x] idme_oauth_prod_pub.pem      
- [x] sign-in-service-token-signing-prod.pem
- [x] va_mobile.pem
- [x] vic-signing.key

4. Confirm certs are in the eks secret production dir
- [x] carma-signing.key
- [x] gibft-sfdc-signing.key
- [x] lighthouse_fast_track_api.key
- [x] sign-in-service-oauth-prod-key.pem
- [x] vagov-mobile-app.key
- [x] vets-api.key
- [x] check-in.lorota.v1.key
- [x] health-quest.key
- [x] logingov_oauth_prod_pub.pem    
- [x] sign-in-service-oauth-prod.pem 
- [x] vagov-ssoe-saml-prod-cert.pem  
- [x] vet_verification.pem
- [ ] dgi-prod.key ⚠️ **Note: [This is called `dgi.key`](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/main/apps/vets-api/prod/templates/secrets.yaml#L55-L56)**
- [x] health-quest.lighthouse.key  
- [x] mobile_lh_health_api.key
- [x] sign-in-service-token-signing-prod-key.pem  
- [x] vagov-ssoe-saml-prod-key.pem   
- [x] vic-sfdc-signing.key
- [x] edu_sftp.key
- [x] idme_oauth_prod_pub.pem      
- [x] sign-in-service-token-signing-prod.pem
- [x] va_mobile.pem
- [x] vic-signing.key

5. Confirm certs are in the eks pod secret directory
- [x] carma-signing.key
- [x] gibft-sfdc-signing.key
- [x] lighthouse_fast_track_api.key
- [x] sign-in-service-oauth-prod-key.pem
- [x] vagov-mobile-app.key
- [x] vets-api.key
- [x] check-in.lorota.v1.key
- [x] health-quest.key
- [x] logingov_oauth_prod_pub.pem 
- [x] sign-in-service-oauth-prod.pem
- [x] vagov-ssoe-saml-prod-cert.pem  
- [x] vet_verification.pem
- [ ] dgi-prod.key ⚠️ **Note: This is called `dgi.key`**
- [x] health-quest.lighthouse.key  
- [x] mobile_lh_health_api.key
- [x] sign-in-service-token-signing-prod-key.pem  
- [x] vagov-ssoe-saml-prod-key.pem   
- [x] vic-sfdc-signing.key
- [x] edu_sftp.key
- [x] idme_oauth_prod_pub.pem      
- [x] sign-in-service-token-signing-prod.pem
- [x] va_mobile.pem
- [x] vic-signing.key

**Comment by laineymajor** [comment]
Planning to work on this early next week

**Comment by LindseySaari** [comment]
Started working on the pod secrets via Argo Terminal today

**Comment by laineymajor** [comment]
@considerable use this ticket for the directories that have been used 
--- referencing your deprecation ticket

**Comment by LindseySaari** [comment]
[Checking with](https://oddball.slack.com/archives/C045LCF8WU8/p1678208188786769) @RachalCassity on the naming of the `dgi.key`, then this should be good to go

**Comment by laineymajor** [comment]
Can close per @LindseySaari and @RachalCassity
