### ISSUE TITLE
Production S3 buckets

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#53502]
1. Confirm the following buckets are this devops [file](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/vets-api/prod-settings.local.yml.j2)
- [x] dsva-vetsgov-prod-evss
- [x] prod-va-gov-form-10-10cg-poa-uploads
- [x] prod-va-gov-hca-uploads
- [x]  dsva-vetsgov-prod-vic
- [x] dsva-vetsgov-prod-preneeds
- [x] dsva-vetsgov-prod-reports
- [x] dsva-vetsgov-prod-claims
- [x] prod-va-gov-claims-api-documents
- [x] prod-va-gov-maintenance-windows
- [x] dsva-vagov-prod-claims-and-appeals
- [x]  dsva-vagov-prod-notice-of-disagreement
- [x] dsva-vetsgov-prod-benefits-documents
- [x] dsva-vagov-prod-1095b-form-uploads
- [x] dsva-vagov-prod-dhp-bearer-tokens

2. Confirm buckets are in S3
- [x] dsva-vetsgov-prod-evss
- [x] prod-va-gov-form-10-10cg-poa-uploads
- [x] prod-va-gov-hca-uploads
- [x]  dsva-vetsgov-prod-vic
- [x] dsva-vetsgov-prod-preneeds
- [x] dsva-vetsgov-prod-reports
- [x] dsva-vetsgov-prod-claims
- [x] prod-va-gov-claims-api-documents
- [x] prod-va-gov-maintenance-windows
- [x] dsva-vagov-prod-claims-and-appeals
- [x]  dsva-vagov-prod-notice-of-disagreement
- [x] dsva-vetsgov-prod-benefits-documents
- [x] dsva-vagov-prod-1095b-form-uploads
- [x] dsva-vagov-prod-dhp-bearer-tokens
3. Confirm the bucket values are correct in the vets-api-prod settings.
- [x] dsva-vetsgov-prod-evss
- [x] prod-va-gov-form-10-10cg-poa-uploads
- [x] prod-va-gov-hca-uploads
- [x]  dsva-vetsgov-prod-vic
- [x] dsva-vetsgov-prod-preneeds
- [x] dsva-vetsgov-prod-reports
- [x] dsva-vetsgov-prod-claims
- [x] prod-va-gov-claims-api-documents
- [x] prod-va-gov-maintenance-windows
- [x] dsva-vagov-prod-claims-and-appeals
- [x]  dsva-vagov-prod-notice-of-disagreement
- [x] dsva-vetsgov-prod-benefits-documents
- [x] dsva-vagov-prod-1095b-form-uploads
- [x] dsva-vagov-prod-dhp-bearer-tokens

--- ANOTHER TEAMMATE ALSO CONFIRMS --- @LindseySaari 

1. Confirm the following buckets are in devops
- [x] dsva-vetsgov-prod-evss 
- [x] prod-va-gov-form-10-10cg-poa-uploads
- [x] prod-va-gov-hca-uploads
- [x]  dsva-vetsgov-prod-vic
- [x] dsva-vetsgov-prod-preneeds
- [x] dsva-vetsgov-prod-reports
- [x] dsva-vetsgov-prod-claims
- [x] prod-va-gov-claims-api-documents
- [x] prod-va-gov-maintenance-windows
- [x] dsva-vagov-prod-claims-and-appeals ✅ See form526_backup: /dsva-vagov/vets-api/prod/form526-backup-submission/aws/bucket
- [x]  dsva-vagov-prod-notice-of-disagreement
- [x] dsva-vetsgov-prod-benefits-documents
- [x] dsva-vagov-prod-1095b-form-uploads
- [x] dsva-vagov-prod-dhp-bearer-tokens

2. Confirm these buckets exist in S3
- [x] dsva-vetsgov-prod-evss
- [x] prod-va-gov-form-10-10cg-poa-uploads
- [x] prod-va-gov-hca-uploads
- [x]  dsva-vetsgov-prod-vic
- [x] dsva-vetsgov-prod-preneeds
- [x] dsva-vetsgov-prod-reports
- [x] dsva-vetsgov-prod-claims
- [x] prod-va-gov-claims-api-documents
- [x] prod-va-gov-maintenance-windows
- [x] dsva-vagov-prod-claims-and-appeals - ✅ See form526_backup: `/dsva-vagov/vets-api/prod/form526-backup-submission/aws/bucket`
- [x]  dsva-vagov-prod-notice-of-disagreement
- [x] dsva-vetsgov-prod-benefits-documents
- [x] dsva-vagov-prod-1095b-form-uploads
- [x] dsva-vagov-prod-dhp-bearer-tokens

3. Confirm the bucket values are correct in the vets-api-prod settings.
- [x] dsva-vetsgov-prod-evss ~~❗ **Note:** This one has a newline.~~ ✅ Fixed newline
- [x] prod-va-gov-form-10-10cg-poa-uploads
- [x] prod-va-gov-hca-uploads
- [x]  dsva-vetsgov-prod-vic
- [x] dsva-vetsgov-prod-preneeds
- [x] dsva-vetsgov-prod-reports
- [x] dsva-vetsgov-prod-claims
- [x] prod-va-gov-claims-api-documents
- [x] prod-va-gov-maintenance-windows
- [x] dsva-vagov-prod-claims-and-appeals ✅ See form526_backup: `/dsva-vagov/vets-api/prod/form526-backup-submission/aws/bucket`
- [x]  dsva-vagov-prod-notice-of-disagreement
- [x] dsva-vetsgov-prod-benefits-documents
- [x] dsva-vagov-prod-1095b-form-uploads
- [x] dsva-vagov-prod-dhp-bearer-tokens

--- ANOTHER TEAMMATE ALSO CONFIRMS --- @rmtolmach  

1. Confirm the following buckets are in devops
- [x] dsva-vetsgov-prod-evss
- [x] prod-va-gov-form-10-10cg-poa-uploads
- [x] prod-va-gov-hca-uploads
- [x]  dsva-vetsgov-prod-vic
- [x] dsva-vetsgov-prod-preneeds
- [x] dsva-vetsgov-prod-reports
- [x] dsva-vetsgov-prod-claims
- [x] prod-va-gov-claims-api-documents
- [x] prod-va-gov-maintenance-windows
- [x] dsva-vagov-prod-claims-and-appeals. The value of `bucket: "{{ lookup('aws_ssm_custom', '/dsva-vagov/vets-api/prod/form526-backup-submission/aws/bucket') }}"` is `dsva-vagov-prod-claims-and-appeals` ✅ 
- [x]  dsva-vagov-prod-notice-of-disagreement
- [x] dsva-vetsgov-prod-benefits-documents
- [x] dsva-vagov-prod-1095b-form-uploads
- [x] dsva-vagov-prod-dhp-bearer-tokens. The value of `bucket: "{{ lookup('aws_ssm_custom', '/dsva-vagov/vets-api/dhp/prod/bucket') }}"` is `dsva-vagov-prod-dhp-bearer-tokens` ✅ 

2. Confirm these buckets exist in S3
- [x] dsva-vetsgov-prod-evss
- [x] prod-va-gov-form-10-10cg-poa-uploads
- [x] prod-va-gov-hca-uploads
- [x]  dsva-vetsgov-prod-vic
- [x] dsva-vetsgov-prod-preneeds
- [x] dsva-vetsgov-prod-reports
- [x] dsva-vetsgov-prod-claims
- [x] prod-va-gov-claims-api-documents
- [x] prod-va-gov-maintenance-windows
- [x] /dsva-vagov-prod-claims-and-appeals
- [x]  dsva-vagov-prod-notice-of-disagreement
- [x] dsva-vetsgov-prod-benefits-documents
- [x] dsva-vagov-prod-1095b-form-uploads
- [x] dsva-vagov-prod-dhp-bearer-tokens

3. Confirm the bucket values are correct in the vets-api-prod settings.
- [x] dsva-vetsgov-prod-evss
- [x] prod-va-gov-form-10-10cg-poa-uploads
- [x] prod-va-gov-hca-uploads
- [x]  dsva-vetsgov-prod-vic
- [x] dsva-vetsgov-prod-preneeds
- [x] dsva-vetsgov-prod-reports
- [x] dsva-vetsgov-prod-claims
- [x] prod-va-gov-claims-api-documents
- [x] prod-va-gov-maintenance-windows
- [x] dsva-vagov-prod-claims-and-appeals
- [x]  dsva-vagov-prod-notice-of-disagreement
- [x] dsva-vetsgov-prod-benefits-documents
- [x] dsva-vagov-prod-1095b-form-uploads
- [x] dsva-vagov-prod-dhp-bearer-tokens

**Comment by laineymajor** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Tech-Team-1-633af4074573d06c3cda142a/issues/department-of-veterans-affairs/va.gov-team/53502?planning-poker) with Zenhub @LindseySaari

**Comment by laineymajor** [comment]
Hoping to work on this Monday

**Comment by LindseySaari** [comment]
Checking on `dsva-vagov-prod-claims-and-appeals` ❗vs ❗`prod-va-gov-claims-api-documents` 

- `dsva-vagov-prod-claims-and-appeals` - Created `January 20, 2023` but not referenced in settings.yml
- `prod-va-gov-claims-api-documents` - Does not exist but IS referenced in settings.yml

**Comment by LindseySaari** [comment]
Buckets have been confirmed by myself. If we want a third set of eyes, that's the last piece

**Comment by laineymajor** [comment]
Circle back to this throughout the sprint once support calms a bit. Need adiditonal set of eyes.

**Comment by laineymajor** [comment]
Need third set of eyes. @considerable or @rmtolmach to take a look as time permits.
If not done by Friday, @considerable will review on Friday.

**Comment by rmtolmach** [comment]
✅ confirmed with my 👀 
for step 3, I searched for "BUCKET" in https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/main/apps/vets-api/prod/values.yaml, coped the `path` and found the value with some version of this command 
```
aws ssm get-parameters --names /dsva-vagov/vets-api/dhp/prod/bucket --with-decryption
```
and made sure the value matched the one in the list (which i had already confirmed in step 1 matched the value in the devops repo)
