### ISSUE TITLE
Tier 2 Case Handling

### ISSUE THREAD

**Issue by manalo-soco** [department-of-veterans-affairs/va.gov-team#53515]
Weekly handling / Resolve and close minimum 44+ cases per day within Tier 2 SF Queue

**Comment by edpearson20** [comment]
258 Cases Closed / Addressed Week Ending Mar. 3 = 51.6 per day
229 Cases Closed / Addressed Week Ending Mar. 3 = 45.8 (Team) per day
97.4 Total Cases Closed / Addressed per day by Contact Center Team (Tier 2)

**Comment by ATMiddleton** [comment]
@edpearson20 and @ATMiddleton will meet to identify metrics.  We will create a ticket for each sprint.
