### ISSUE TITLE
Sidekiq Admin UI Access Request

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#53512]
_Access to the Sidekiq Admin UI is managed through a GitHub team under the [department-of-veterans-affairs/va.gov-sidekiq team](https://github.com/orgs/department-of-veterans-affairs/teams/va-gov-sidekiq/members). Please provide your GitHub username to be added to that team, along with a reason access is required._

- GitHub username: jerekshoe
- Reason access is required: I am on the Benefits team and will be troubleshooting and investigating issues with vets-api. This includes issues that involve Sidekiq jobs failing or monitoring the queue.

**Comment by rmtolmach** [comment]
@jerekshoe, sorry this has taken so long to get looked at. For some reason it was missing the `ops-access-request` label so we didn't see it on the support team.

Which environments are you requesting access to? dev, staging, sandbox, prod. Please include justification if your request includes prod.

**Comment by jerekshoe** [comment]
@rmtolmach I was just looking to get access to dev, staging, and sandbox

**Comment by ryan-mcneil** [comment]
@jerekshoe You've been granted access to all environments, with access to Production limited to 6 months

**Comment by bdech** [comment]
@jerekshoe Your Sidekiq Admin UI Production access has expired. Would you like to request an extension of access?
