### ISSUE TITLE
Confirm /srv/vets-api/src/config/ file paths have been updated to /app/config 

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#53510]
EKS config files are stored in the app/config directory.  The BRD /srv/vets-api/src paths have to be updated.
1. Make PR
- https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/1465

2. Confirm these paths have been changed in EKS

- [x] /srv/vets-api/src/config/ssoe_idp_prod_metadata_isam.xml"

3. Confirm the values in the files are correct.
- [ ] /srv/vets-api/src/config/ssoe_idp_prod_metadata_isam.xml"

**Comment by laineymajor** [comment]
Rebecca will knock this out today, then work on secretc.yml cleanup

**Comment by rmtolmach** [comment]
* ✅ confirmed `/app/config` contains a file called `ssoe_idp_prod_metadata_isam.xml`
* ❓ `ssoe_idp_int_metadata_isam.xml` also exists in the `/app/config` directory of a prod pod. Is that expected @RachalCassity?
* ✅ I compared the value of `/srv/vets-api/src/config/ssoe_idp_prod_metadata_isam.xml` in an EC2 prod server instance to the value of `/app/config/ssoe_idp_prod_metadata_isam.xml` in a vets-api-web pod in ArgoCD and they're identical.

**Comment by rmtolmach** [comment]
> ❓ ssoe_idp_int_metadata_isam.xml also exists in the /app/config directory of a prod pod. Is that expected

Yes, Rachal helped figure out that this was being being pulled in from the `vets-api` repo! It matches what's in BRD, which is what we want.
