### ISSUE TITLE
AWS access for Andrew Bunker

### ISSUE THREAD

**Issue by ambunker1** [department-of-veterans-affairs/va.gov-team#53522]
### COR Name

Courtney Bethea

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Andrew Bunker

### Your Email

andrew.bunker@adhocteam.us

### Team, Role, and Company of the target individual

Lighthouse team, API DevOps, AdHoc

### Product Manager (PM) name and email

Gabriel Olaviarra olavarria_gabriel@bah.com

### Product Owner (PO) name and email

Andrew Fichter andrew.fichter@va.gov

### Desired AWS Access

I am requesting adfs-project-administrator access. For any finer-grained permissions, they should match either Monica Ramirez ramirez_monica@bah.com or Gabriel Olaviarra olavarria_gabriel@bah.com. 

### Access Expiration

ongoing

### Additional Notes

As a DevOps engineer, I'll be assisting in the creation and maintenance of platform components that will span many development teams and layers of AWS resources. This access will be crucial to my work for the entire time I am operating in this role. 

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by little-oddball** [comment]
VFS Team

**Comment by BillChapmanUSDS** [comment]
I approve ongoing non-production access. If production access is required it will need to be limited to 3 months while we are reviewing this process.

**Comment by considerable** [comment]
initial password provided via Keybase, closing the tkt.
