### ISSUE TITLE
[eFSR] Finalize Conversation Guide on Github

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#53531]
## Issue Description
Ensure format of the Conversation Guide matches [conversation guide template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/conversation-guide-template.md)

Add Conversation Guide to https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/combined_fsr/research/enhanced_fsr

---
## Tasks
- [x] _Finalize research plan so it lines up with Conversation Guide template_

## Acceptance Criteria
- [x] _Conversation Guide is finalized and up on Github_

**Comment by mgleo** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VSA---Debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/53531?planning-poker) with Zenhub @charlottecesana

**Comment by mgleo** [comment]
[Link to Conversation Guide on Github](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/combined_fsr/research/enhanced_fsr/conversation-guide.md)

**Comment by HeatherRienks** [comment]
Thanks @mgleo for adding the link in! So appreciated!
