### ISSUE TITLE
FE | Profile | Notification Settings | Build editing page for profile

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/va.gov-team#53545]
## Issue Description
Build a new page in the profile that can host an editing experience of any field.

## Front end tasks
- This lives at a new path `/edit` inside `/profile`
- Bootstraps the main profile layout with sidebar and navs.
- Ensure the back end data from API is displayed in local and review instance
- Ensure unit tests are available.
  - Page component sanity checks
- Ensure your code changes are covered by E2E tests
  - Feature toggle visibility checks / url availability 
- Run axe checks using the Chrome or Firefox browser plugin
  - https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review
- Test for color contrast and color blindness issues
- Zoom layouts to 400% at 1280px width
- Test with 1 or 2 screen readers
- Navigate using the keyboard only

## Acceptance Criteria
- [x] Page visible on staging with toggle, and not visible at all without
- [x] Page renders with sidebar and UI skeleton
- [x] Unit tests pass
- [x] E2E tests cover current code and regression
- [x] End-to-end tests show 0 violations.
- [x] The data returned matches API response (for given user or scenario)
- [x] All axe checks pass
- [x] All color contrast checks pass
- [x] All zoom testing passes
- [x] All keyboard checks pass 
- [x] All screenreader checks pass

**Comment by Samara-Strauss** [comment]
Moving back at least 1 sprint due to semantic list work taking priority so we can close out the accessibility project. This may need to be moved back further, which is fine.

**Comment by BerniXiongA6** [comment]
@adamwhitlock1 @BerniXiongA6 -- this ticket should be broken down and we can prioritize the first ticket for Sprint 5 and push the second ticket for Sprint 6 or beyond.

**Comment by BerniXiongA6** [comment]
Hi @adamwhitlock1 will any of this work carry over and if so do you have an estimate of how many points are left?

**Comment by adamwhitlock1** [comment]
@BerniXiongA6 waiting on PR review for this. Work is done though otherwise. I'd say we will need to roll these over since allison is OOO today, but hoping to get some reviews and on staging tomorrow if possible.

**Comment by BerniXiongA6** [comment]
Hi @adamwhitlock1 -- just validated this as instructed and everything checks out just as it should. Looks good to go!
