### ISSUE TITLE
[TF] Utility state dirty

### ISSUE THREAD

**Issue by oseasmoran73** [department-of-veterans-affairs/va.gov-team#53548]
## User Story

Utility state has been dirty for some time. Work has been to clean up, but needs additional cleaning. [Slack](https://dsva.slack.com/archives/C04CYC4LMU6/p1676060057745519) for more details

---

## Acceptance Criteria
- [ ] Utility terraform is no longer in a dirty state

## Additional information

_Links to support request, any additional context someone needs, how it was found, where in the code it needs to be changed, any relevant internal or external docs._

---
## How to configure this issue
- [x] **Labeled with 'platform-cop'** 
- [x] **Labeled with Practice Area** (`platform-cop-backend`, `platform-cop-frontend`, `platform-cop-devops`)

**Comment by pjhill** [comment]
Needs additional decomposition into steps in order to be worked by a COP member 1-2 days per sprint

**Comment by pjhill** [comment]
Per Kyle, `terraform refresh` resolved the issue --

```
# Checked the plan and it didn't show any infra changes, just that the state needed updates

# Created a plan for the state refresh and applied
rm ./.terraform ./.terraform.lock.hcl ./.terragrunt-cache -rf
terraform init -backend-config env/utility.tfbackend
terraform plan -refresh-only -var-file ./env/utility.tfvars -out utility.tfplan
terraform apply "utility.tfplan"

# To verify that it comes back clean (it did)
terraform plan -var-file ./env/utility.tfvars -out utility.tfplan
```
