### ISSUE TITLE
[Bug] Inaccurate Higher Level Review Status on VA.gov

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#53557]
## What happened?
The user has two higher level review cases that are showing as active on the VA website even though they should be in a closed status. He said the cases were closed 15 Nov 2022. EVSS support took a look and made some updates to the account but these changes did not fix the problem. EVSS was also able to confirm that the higher level review cases were closed. 

![image](https://user-images.githubusercontent.com/32465263/218482579-a8037f49-af26-40a9-b658-48170333b3a1.png)
![image](https://user-images.githubusercontent.com/32465263/218482606-6939c1d3-6ae3-4b0d-bf89-69232f4ea750.png)

## Specs:
- Device: Mobile (iPhone)
- Browser: Safari
- Test User _(if applicable)_:

## Steps to Reproduce
- URL: 
- Test User _(if applicable)_:

## Desired behavior
The status of the higher level review cases should be shown as closed (or inactive... not totally sure what the correct language is). 

## Acceptance Criteria
- The higher level review cases' status should reflect what is shown in the system.

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by clantosswett** [comment]
@mattpointzxer0 I will be sending a follow up email linking this issue and including the necessary information for further investigation (ICN, claims ID, etc).

**Comment by jacobworrell** [comment]
Noted that claim ID and ICN have been sent in a secure message.

**Comment by coforma-terry** [comment]
Commenting to revive this issue after conversation with @clantosswett - Is there anything we need or don't have to resolve this?

**Comment by jerekshoe** [comment]
We don't get our appeals info from EVSS, we go through Caseflow, so someone would need to reach out to them and find out if the appeal is closed in their system or no

**Comment by jerekshoe** [comment]
Also the screenshots are from the mobile app. Can we confirm that they were seeing the same status on VA.gov and not just on mobile?

**Comment by ATMiddleton** [comment]
Re-elevated to Benefits team and connected to EVSS - awaiting update from Benefits to update us on progress.

**Comment by jacobworrell** [comment]
This ticket is blocked until we have a connection to CaseFlow

**Comment by ATMiddleton** [comment]
A potential resolution identified.  Need Veteran confirmation.

**Comment by clantosswett** [comment]
The user responded and said the issue was fixed. I will be closing this issue but opening a separate one to look into the other claims status issues we are seeing.
