### ISSUE TITLE
AWS access for Gary Fallon

### ISSUE THREAD

**Issue by gary-fallon** [department-of-veterans-affairs/va.gov-team#53591]
### COR Name

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Gary Fallon

### Your Email

gary.fallon@oddball.io

### Team, Role, and Company of the target individual

Platform, Security Engineer, Oddball

### Product Manager (PM) name and email

Alyssa Gallion

### Product Owner (PO) name and email

Andrea Hewitt

### Desired AWS Access

I need read-only access to the AWS GovCloud account to assess platform infrastructure against the existing ATO control implementations.

### Access Expiration

ongoing

### Additional Notes

Delano McVay

### User must exist in a roster before AWS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [x] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by little-oddball** [comment]
Platform team (working ATO, etc.)

**Comment by little-oddball** [comment]
@BillChapmanUSDS - @gary-fallon is working all our ATO items and access will help speed up many aspects of that process. Thank you!

**Comment by BillChapmanUSDS** [comment]
I approve this access.
