### ISSUE TITLE
GIDS: Make file upload process transactional

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#5361]
As a developer, I need to make the GIDS file upload process transactional so that old source data is not deleted until the upload has been successful.

## Assumptions:
1.  

## Acceptance Criteria:
1. If a file upload fails:
     - The previously uploaded data is available in the corresponding table.
     - The previously uploaded data is exportable.
2. If a file upload is successful:
     - The previously uploaded data is removed from the corresponding table.
     - The previously uploaded data is not included in the CSV export.

## Technical Notes:
From @jholton
I have a program.csv  with one row that I know uploads fine. I uploaded it.  Worked fine.

> irb(main):031:0> Program.count
> => 1

All of that is as expected.
Now I try to upload one of those giant 33MB program.csv files.
I get an error:

>  Failed to upload program.csv: Illegal quoting in line 1. [SmarterCSV: csv line 146] /Users/johnny/path/to/file/csv.rb:1912:in `block (2 levels) in shift’

I don’t know if that’s a bug or not.  Point is my upload failed.
Here is the concerning part:

> irb(main):033:0> Program.count
> => 0

My programs table is now empty.
The upload process deleted all the records from the table before trying to import the new records.  Then the upload failed, leaving me with an empty table.
That is the current state of things in production.   That’s how I started down this rabbit hole.  I exported the program.csv from there.  It was an empty CSV.  So I checked the production database.  Sure enough, the programs table in production is empty right now.
The current preview version of data appears to be have been built with empty programs table because there are no institution_programs records for that version (it’s dependent on programs data), and thus there are no VET TEC program results:
https://www.va.gov/gi-bill-comparison-tool/program-search?version=9a44fbed-4b0b-4cd6-bd36-1b92e23c4c4b

**Comment by ksantiagomorgan6** [comment]
Pull Request: 

https://github.com/department-of-veterans-affairs/gibct-data-service/pull/575

**Comment by sonntag-adam** [comment]
Test passes
https://dsvavsp.testrail.io/index.php?/runs/view/178&group_by=cases:section_id&group_order=asc

**Comment by sonntag-adam** [comment]
In staging gids. Testing passes QA
