### ISSUE TITLE
Vets-api deploy (staging) when vets-api-mockdata has a change

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#53612]
http://jenkins.vfs.va.gov/job/testing/job/vets-api-mockdata/job/master/

**Comment by laineymajor** [comment]
We think this is complete, but should be double-checked to ensure complete in all environments. @oseasmoran73 please review... Lindsey and I can provide additional context if needed!

**Comment by LindseySaari** [comment]
This is basically done... and upon a change to the mockdata, all [vets-api envs are redeployed.](https://github.com/department-of-veterans-affairs/vets-api-mockdata/blob/master/.github/workflows/deploy_vets_api.yml#L19). 

**BUT** There _IS_ a better way to do this by triggering a repository_dispatch ([see comments](https://github.com/department-of-veterans-affairs/vets-api-mockdata/blob/master/.github/workflows/workflow_dispatch.yml#L1-L4)), but you can't do this on a non-master branch (e.g. k8s).

When vets-api k8s is merged to master, we can implement the repository_dispatch but this can **only** be implemented on the master branch.

Again,[ this _should_ work](https://github.com/department-of-veterans-affairs/vets-api/pull/11754/files) once the respository_dispatch is triggered.

**Comment by LindseySaari** [comment]
Added this to the After EKS prod rollout epic. cc @laineymajor
