### ISSUE TITLE
Scale down/remove the BRD vets-api-worker ASG

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#53613]

**Comment by RachalCassity** [comment]
Wait until after PROD rollout.

**Comment by laineymajor** [comment]
Adding to this sprint

Need a devops resource to assist in completing. 
currently no brd workers are running... since the deploy has gone out, no brd workers have spun up. could be done. Needs review.

@rmtolmach we might need your help to review an see if this is in fact complete -> can close?

**Comment by LindseySaari** [comment]
I believe this is complete. No BRD workers are up and running anymore and do not come up during the autodeploy. We want to leave the Jenkins jobs around for now incase of a major incident needing a rollback
