### ISSUE TITLE
Remove datadog/pagerduty/prometheus alerts for vets-api server and worker

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#53610]

**Comment by RachalCassity** [comment]
Wait until after PROD rollout.

**Comment by RachalCassity** [comment]
Wait until after PROD rollout.

Prometheus should be rolled out after PROD is up for awhile.

**Comment by laineymajor** [comment]
Likely linked with the issue that Chelen reported.

**Comment by RachalCassity** [comment]
There are no active Prometheus alerts.

Datadog alerts removed in this PR.

**Comment by considerable** [comment]
Merged the PR above and watched the [GHA](https://github.com/department-of-veterans-affairs/devops/actions/runs/4813521553/jobs/8570149830) succeed.

**Comment by RachalCassity** [comment]
Thank you!
