### ISSUE TITLE
CT 116: Add SCO Contact Details to all non VETTEC profile pages

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#5362]
As a Comparison Tool user, I need the SCO Contact Details displayed on all institution profile pages so that I know who to contact at that institution.

## Assumptions:
1. This work is completed behind a flag so that it is only available in the staging environments and below.

## Acceptance Criteria:
1. A "School certifying officials" sub-section is in the "Contact Details" section on the profile page.
2. In the "School certifying officials" sub-section, SCOs are grouped by type: Primary & Secondary.
3. The SCO Full Name is displayed on all profile pages.
4. The SCO Title is displayed on all profile pages.
5. The SCOs are displayed in alphabetical order by last name from left to right, top to bottom for each type (primary, secondary)

## Supporting Artifacts:
1. ![sco_contact_update](https://user-images.githubusercontent.com/48260534/69440546-09ea9980-0d17-11ea-9995-c55bbb09a225.png)
2. [Interactive prototype](https://bahdigital.invisionapp.com/share/APIAC31SV63#/screens/296025742)
3. [WEAMS_School_Data_CRTOFC_12122019.txt.zip](https://github.com/department-of-veterans-affairs/va.gov-team/files/4139924/WEAMS_School_Data_CRTOFC_12122019.txt.zip)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/11661
Example institution to use https://www.va.gov/gi-bill-comparison-tool/profile/11029843

**Comment by delli-gatti-michael** [comment]
Testing Passes
https://dsvavsp.testrail.io/index.php?/runs/view/177&group_by=cases:section_id&group_order=asc

**Comment by delli-gatti-michael** [comment]
Changes are now live in Staging. Closing this issue

![Screen Shot 2020-02-19 at 7.52.04 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/3a6dc423-67fd-4f39-b420-155740a578bd)
