### ISSUE TITLE
Platform Orientation Template Carly Yamrus

### ISSUE THREAD

**Issue by carly-yamrus** [department-of-veterans-affairs/va.gov-team#53639]
## Welcome and Introduction
Welcome to the Veteran's Administration (VA) Veteran Facing Services (VFS) team! 
As a new VFS team member, you will be working in the web ecosystem we call the VA.gov Platform (or "**The Platform,**" for short).  The tasks on this list are designed to get you up to speed on the role of Platform, making it easier for you to do your job.

Because the VA is a huge organization that serves millions, the Platform it runs on is equally big, complex and multilayered. Most people find that even learning the basics for their own practice area entails a significant learning curve.  The tasks on this checklist will help you acquire those basics as quickly and efficiently as possible. 

## User Story
As a new VFS team member, I need to complete onboarding activities so I can successfully work on my project and support the VA.gov Platform.

## How to fill out this ticket
- [x] Add your name to the ticket title
- [x] Complete the Onboarding Checklist below
- [x] Under **Get set up for your practice area,** you only need to complete the items for your role
- [x] You can close this ticket when all items are completed in the Onboarding Checklist and the Platform Checklist

### Share your info with Platform
- [x] Complete the fields below:
 - Name: Carly Yamrus
 - Preferred pronouns (e.g. she/her): She/Her
 - Role: Scrum Master
 - Email: Carly.yamrus@va.gov
 - GitHub handle*: carly-yamrus
 - Start date: Now
 - VFS Team: Memorials Self Service

*Providing your GitHub handle will allow Platform to provide you access to the necessary GitHub repos.

### General

- [x] Attend General Orientation session ([schedule via Calendly](https://calendly.com/collaboration-cycle/general-orientation-for-va-gov-platform?month=2021-11))
- [x] Watch [VA.gov overview video](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html#PlatformOrientation-Purpose)
- [x] Update your [Slack profile](https://depo-platform-documentation.scrollhelp.site/getting-started/Request-access-to-tools.969605215.html#Requestaccesstotools-Slack) with Program, Team, Role and Company
- [x] Review [Welcome](https://depo-platform-documentation.scrollhelp.site/getting-started/Welcome.1255276574.html) documentation
- [x] Review [Support Overview](https://depo-platform-documentation.scrollhelp.site/support/Support-overview.604012552.html) documentation
- [x] [Request Access to Tools](https://depo-platform-documentation.scrollhelp.site/getting-started/Request-access-to-tools.969605215.html)
- [x] Review the guidance on [Submitting a feature request](https://depo-platform-documentation.scrollhelp.site/support/Submitting-a-feature-request.1938915400.html)
### Norms and standards
- [x] Review guidance on the [Platform Satisfaction Survery](https://depo-platform-documentation.scrollhelp.site/support/platform-satisfaction-survey)
- [x] Review the [Code of Conduct](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/code-of-conduct.md)
- [x] Review the [Norms for Communication](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/norms-communication.md)
- [x] Review [Orientation materials](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html) on Platform Website
- [x] Review the [Guidelines for Working Safely in an Open Source Repo](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/sensitive-guidance.md)
- [x] Review the [Norms for Using Tools](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/norms-tools.md)

### Working on the platform
- [x] Review the [Platform Principles](https://depo-platform-documentation.scrollhelp.site/getting-started/platform-crew-principles)
- [x] Review the [GitHub Markdown Cheatsheet](https://help.github.com/en/categories/writing-on-github) to learn the syntax for formatting documents in GitHub
- [x] Review the [Digital Modernization Strategy](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-gov-relaunch-2018/va-gov-strategy/digitalmodernizationstrategy.pdf)
- [x] Review the [Web Brand Consolidation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-gov-relaunch-2018/va-gov-strategy/the-new-va.gov-briefing-2019-07.pdf) documentation
- [x] Review the [Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) documentation on Platform Website
- [x] Are you a Veteran? Consider adding your name to the [Veterans willing to help VA teams with product testing](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/team-veterans.md) document

#### Designers & Researchers
- [x] Review the [Research and Design Guide on Platform Website](https://depo-platform-documentation.scrollhelp.site/research-design/index.html)
- [x] Learn how we do [research at VA](https://depo-platform-documentation.scrollhelp.site/research-design/research-at-va)
- [x] Get oriented to the [Design System](https://design.va.gov/)
- [x] Get oriented to the [Collaboration cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/)
- [x] Attend Design orientation session ([schedule via Calendly](https://calendly.com/collaboration-cycle/design-orientation-for-va-gov-platform))
- [x] Attend Accessibility orientation session ([schedule via Calendly](https://calendly.com/collaboration-cycle/accessibility-orientation-for-va-gov-platform))

#### Front-end Engineers
- [ ] Review [frontend developer documentation](https://depo-platform-documentation.scrollhelp.site/developer-docs/Frontend-developer-documentation.687931428.html) on Platform Website
- [ ] [Confirm that You Can Log In as a Test User](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/accessing-staging.md)
- [ ] Attend Front-end orientation session ([schedule via Calendly](https://calendly.com/collaboration-cycle/front-end-orientation-for-va-gov-platform))
- [ ] Attend Analytics orientation session ([schedule via Calendly](https://calendly.com/collaboration-cycle/analytics-orientation-for-va-gov-platform))
- [ ] Attend Accessibility orientation session ([schedule via Calendly](https://calendly.com/collaboration-cycle/accessibility-orientation-for-va-gov-platform))
- [ ] Attend QA orientation session ([schedule via Calendly](https://calendly.com/collaboration-cycle/qa-orientation-for-va-gov-platform))
- [ ] Attend Design System/Forms Library orientation session ([schedule via Calendly](https://calendly.com/collaboration-cycle/design-system-forms-library-orientation))

#### Back-end Engineers
- [ ] Review [backend developer documentation](https://depo-platform-documentation.scrollhelp.site/developer-docs/Backend-developer-documentation.1886289964.html) on Platform Website
- [ ] [Confirm that You Can Log In as a Test User](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/accessing-staging.md)
- [ ] Attend Back-end orientation session ([schedule via Calendly](https://calendly.com/collaboration-cycle/back-end-orientation-for-va-gov-platform))
- [ ] Attend QA orientation session ([schedule via Calendly](https://calendly.com/collaboration-cycle/qa-orientation-for-va-gov-platform))

#### Product Managers
- [x] Request PM intro with @ Shira Goodman in Slack
- [x] Attend Analytics orientation session ([schedule via Calendly](https://calendly.com/collaboration-cycle/analytics-orientation-for-va-gov-platform))
- [x] Attend Accessibility orientation session ([schedule via Calendly](https://calendly.com/collaboration-cycle/accessibility-orientation-for-va-gov-platform))
- [x] Attend QA orientation session ([schedule via Calendly](https://calendly.com/collaboration-cycle/qa-orientation-for-va-gov-platform))

### Off-boarding of teammates
- [x] Review [process for when a teammate leaves](https://depo-platform-documentation.scrollhelp.site/getting-started/offboarding)

## Platform Checklist
The items in this checklist are for Platform to complete. If you are ready to close the ticket and the Platform Checklist section has not been completed, please reach out to Platform via the guidance provided in [Getting help from Platform in Slack](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).
- [x] New VFS team member has been added to the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=0)
- [ ] New VFS team member has been added to the vets.gov-write GitHub team

**Comment by shiragoodman** [comment]
@carly-yamrus you're not a member of the VA Organization on Github and this is a prerequisite to being added to the vets.gov-write team for repo access. Please refer to this [guidance on Platform Website. ](https://depo-platform-documentation.scrollhelp.site/getting-started/request-access-to-tools#Requestaccesstotools-GettingaccesstotheVAGitHuborganization)

**Comment by carly-yamrus** [comment]
I have completed all of the applicable items on this orientation template - am I able to go ahead and close this ticket?
@shiragoodman

**Comment by shiragoodman** [comment]
@carly-yamrus we have not been able to complete the 2nd Platform Checklist item due to my comment above. Were you able to look into that?

**Comment by carly-yamrus** [comment]
@shiragoodman The link to "[Add User to the VA Organization ticket]" comes up with a 404 error

**Comment by shiragoodman** [comment]
@carly-yamrus The guidance says "Ask your program manager." You don't have access and that's why it's giving a 404. You need someone else to submit this on your behalf. someone who already has access to the VA Org on github

**Comment by carly-yamrus** [comment]
Okay great it looks like I am in now! @shiragoodman  Sorry -  confusion on our end

**Comment by carly-yamrus** [comment]
@shiragoodman Hey Shira, I need "write privileges" to the VA repository so that I am able to be assigned issues- do you know how to go about doing that?

**Comment by shiragoodman** [comment]
hey @carly-yamrus - that's a task that's handled by the Platform Support team. I have added their team label and tagging their PM @alyssagallion for awareness. Thanks!

**Comment by alyssagallion** [comment]
@bmatos312 Can you help us with this one?

**Comment by bmatos312** [comment]
@carly-yamrus Hello Carly, can you ask your PM for a VA-org access again it seems like you were removed and cannot give you write access just yet.

**Comment by bmatos312** [comment]
Ping me once this is complete to further assist!

**Comment by carly-yamrus** [comment]
Hello, I now in the VA github org
