### ISSUE TITLE
FE | Profile | Info Table Accessibility Updates - Migrate Entire Direct Deposit Page to use the new Info Card

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/va.gov-team#53631]
## Issue Description
After the initial MVP of the Profile Info Card component, the rest of the Direct Deposit sections should be migrated to use this new component

The remaining sections are the Disability compensation and pension benefits, and Education benefits sections

![Screenshot 2023-02-13 at 9 37 47 PM](https://user-images.githubusercontent.com/8332986/218640699-e49925ec-4bb2-4fca-88c8-9389fee2adc4.png)

## Front end tasks
- Migrate remaining sections of Direct Deposit
  - Ensure form editing still works as expected and double check to make sure there are no layout shifts during editing flow. 
- Ensure the page is styled according to design spec. 
- Ensure the back end data from API is displayed in local and review instance
- Ensure unit tests are available. 
- Ensure your code changes are covered by E2E tests
- Run axe checks using the Chrome or Firefox browser plugin
- Test for color contrast and color blindness issues
- Zoom layouts to 400% at 1280px width
- Test with 1 or 2 screen readers
- Navigate using the keyboard only

## Acceptance Criteria
- [x] Remaining sections migrated
- [x] Page maintains existing functionality and styling
- [x] Designer comments on this issue to approve page styling 
- [x] Unit tests pass
- [x] E2E tests cover current code and regression
- [x] End-to-end tests show 0 violations.
- [x] The data returned matches API response (for given user or scenario)
- [x] All axe checks pass
- [x] All color contrast checks pass
- [x] All zoom testing passes
- [x] All keyboard checks pass 
- [x] All screenreader checks pass

**Comment by BerniXiongA6** [comment]
Hi @adamwhitlock1  will any of this work carry over and if so do you have an estimate of how many points are left?

**Comment by adamwhitlock1** [comment]
I'd say this is at a 1 right now. Majority of work is done, and just need to finish tests and get into PR

**Comment by adamwhitlock1** [comment]
This is live in staging now. To validate, a user just need to log in with any test account and verify that the Direct Deposit Displays correctly. The components shouldn't look any different, but it is the underlying page structure that has changed.

Various test users that I checked out came from here: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-direct-deposit.md

**Comment by BerniXiongA6** [comment]
Hi @adamwhitlock1 -- didn't see this until now, I can validate shortly and then comment here. Thank you!

**Comment by BerniXiongA6** [comment]
Hi @adamwhitlock1 -- I logged on as user 175 and as user 41, and both display their respective Direct Deposit Info. Looks good, thanks for the great work!
