### ISSUE TITLE
SOCKS access for Jacob Worrell

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#53638]
### Your Name

Jacob Worrell

### Your Email

jacob.worrell@adhocteam.us

### Your Role and Team

Product Manager

### Product Manager (PM) name and email

Jacob Worrell, jacob.worrell@adhocteam.us

### Product Owner (PO) name and email

Matt Self, matthewself.dsva@gmail.com

### Access Type Requesting

viewers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDNClJgZalzYcF0mklVWy2J6HqNwKG55bR35Bo7dIyfFAoQyVqVc18HLVVId1kdCQmEri9tOy1V5IagfUe8plZfFYglNk+5tXjezHTzoBjwKI3LeMk/zcu7NwBtEFosane/BK9Rw+Ebw5c+IKiaQzYtgwWtuy1aw/gxwEHLnyM9bOXcaYhQdmnJM/MygN6ulN8Oxa4Mv7psDzA/1JzH4XAGO9PvbJteyGyI/P5kLGP3RXh9QU3N6nSn+J6NVJQj+YyFEHe+hwsqYx0s/Ge16yq0sY9ablvOpnKp8O6wPQ/6wqs8U5rupILgGrf4ERLiD/7sFUmMeoQoF4YaZSi9fnL8gfdajZAb6YonpdNv0QxTEm+SXwkBec/FUy53j+Pk+k4qPpqu/2v9EgJCmPEX3eKfx04Tpzmd6c1gxanByfYpV+tG2mqj0hs7NaXGAppYmiend4cjK2vhYIK+2uSeLIrqNftBfngJqzG0U8Va1n2te1c3osOKoHzrT2+CXh/GFSM= jacobworrell@DESKTOP-1PKVBE7

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by pjholyoke** [comment]
Merged.
