### ISSUE TITLE
FE | Profile | Info Table Accessibility Updates - Update Military Info, Account Security pages to new info card component

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/va.gov-team#53632]
## Issue Description

* This ticket may need to be updated / changed as the initial MVP work proceeds with any new requirements that come to light.
After the direct deposit page has been migrated, then the rest of the profile pages need to use the new component.

Incremental rollout could be as follows:

- MilitaryInformation

- AccountSecurityContent
- AccountSecurityTables

## Front end tasks
- Military History and Account Security migrated to new component
- Ensure the page is styled according to design spec. 
- Ensure the back end data from API is displayed in local and review instance
- Ensure unit tests are available. 
- Ensure your code changes are covered by E2E tests
- Run axe checks using the Chrome or Firefox browser plugin
- Test for color contrast and color blindness issues
- Zoom layouts to 400% at 1280px width
- Test with 1 or 2 screen readers
- Navigate using the keyboard only

## Acceptance Criteria
- [x] Military History and Account Security migrated to new component
- [x] Designer comments on this issue to approve page styling 
- [x] Unit tests pass
- [x] E2E tests cover current code and regression
- [x] End-to-end tests show 0 violations.
- [x] The data returned matches API response (for given user or scenario)
- [x] All axe checks pass
- [x] All color contrast checks pass
- [x] All zoom testing passes
- [x] All keyboard checks pass 
- [x] All screenreader checks pass

**Comment by Samara-Strauss** [comment]
Slating this for sprint 6 so we can validate #53631 first. Will add formally to sprint when that auto-updates in Zenhub.

**Comment by BerniXiongA6** [comment]
Note for team: @adamwhitlock1 broke out this ticket into two manageable items, the other ticket is #55296 (can be taken on in Sprint 7)

**Comment by adamwhitlock1** [comment]
@BerniXiongA6 and @Samara-Strauss this is ready to validate in staging, and this PR includes the removal of the borders on the profile info cards.

![Screenshot 2023-03-28 at 1.23.50 PM.png](https://images.zenhubusercontent.com/60ddebd504ce2452d0e0fa92/5845b5b9-f441-48ef-be5c-99327c8ee196)

Specifically Account Security and Military History are the pages to check out in staging with a test user to verify that they display correctly and that everything looks ok.
