### ISSUE TITLE
IDP-based feature toggle

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#53665]
## Story
"As a signed in user, I want to access to certain VA.gov functionality conditioned on the identity provider I used to sign in, so that functionality that does not work well with my chosen identity provider is not made available to me."

## Background
We've done some light testing of the VA.gov --> MHV pathway for signed in users. There is some evidence that shows selecting the MHV identity provider (IDP) from the VA.gov sign-in options will result in authentication that _does not_ persist from VA.gov to MHV (specifically `https://eauth.va.gov/mhv-portal-web/web/myhealthevet/home`). ID.me and Login.gov do not appear to have this problem.

While we continue to understand what's going on here, it would be good to be able to condition the path to the new MHV on VA.gov landing page on IDP used for sign-in. This will allow us to limit the path to the new page to a small increment of users in which we are very confident of their ability to navigate from VA.gov to MHV deeplinks as expected.

## Acceptance criteria
VA.gov functionality — if available, specifically the page at `va.gov/my-health` — is toggle-able based on IDP used for sign-in.

**Comment by mdewey** [comment]
PR for landing page toggle : https://github.com/department-of-veterans-affairs/vets-website/pull/23401

**Comment by mdewey** [comment]
Linking slack thread: https://dsva.slack.com/archives/C04GDQSHD1R/p1676578006321339

**Comment by mdewey** [comment]
Toggle on the API PR : https://github.com/department-of-veterans-affairs/vets-api/pull/11833
