### ISSUE TITLE
General Login page, user flows, and SSO communication UX research

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#5367]
**Description**
Identify research areas, and log potential research questions.

**Tasks**
- [ ] ID user flows for login page, SSOe, and MHV/Cerner
- [ ] Invision prototype of screens
- [ ] Discussion guide
- [ ] Observer guide

**Comment by bridgethapner** [comment]
**A note here:** 

This week we should finalize list of all the things that we want to test in our first round of testing with alerts. I think the question here is "What else aside from Alerts at a solid and thorough enough point where we can pose a question about it to users and get meaningful feedback?" Testing could include some aspects of the login page.

**Comment by bridgethapner** [comment]
Per 2/14 conversation, this will be a separate research session from the Alerts boxes & we'll aim to test links between different sites. This will require building a prototype with screens from this stream of work and My VA Health/My HealtheVet. Preliminary research questions are:
- Does generic language (e.g. Sign In) on this page work for multiple users?
- Do users feel confused when they land here?
- Does the journey from site to site feel seamless or disjointed? 
- Are users getting the information they need at the right point on each site? 

Next step here is identifying all the flows we'd like to test. I'll start this with Martha and Eric's diagrams as a jumping off point.

**Comment by bridgethapner** [comment]
Update - High level site maps for a MHV + Cerner Patient here: https://adhoc.invisionapp.com/share/VMW6WMI9NDU#/screens/407105292_High_Level_Site_Maps_For_A_MHV___Cerner_Patient

**Comment by ambikaroos** [comment]
Discussed and will not be pursuing testing at this time, given that our team does not manage the MHV or Signup Service Flows
