### ISSUE TITLE
Monitoring Plan (now): Set up sentry dashboard 

### ISSUE THREAD

**Issue by sortizsh** [department-of-veterans-affairs/va.gov-team#53678]
We need to create a better process for application monitoring so that our team is the first to identify critical issues with our applications. This document provides detailed action items in the short term and ideas for improvement in the long term.

[purposeful] Set up sentry dashboard for all applications: Enables "at-a-glance" incident monitoring. Still a manual process, but takes a shorter time to digest.

## Acceptance Criteria

- [x] Error dashboard set up for CST
- [x] Error dashboard set up for Letters App
- [x] Error dashboard set up for Rated Disabilities

**Comment by kjduensing** [comment]
@jerekshoe @samcoforma can y'all take a look at this dashboard? Especially interested in the rated disabilities graphs... they seem high.

**Comment by samcoforma** [comment]
@kjduensing  The graph looks set up correctly, and it looks like there are a lot of errors logged for that URL: http://sentry.vfs.va.gov/organizations/vsp/issues/607/?environment=production&project=4&query=view-disability-rating&sort=freq&statsPeriod=14d
