### ISSUE TITLE
Monitoring Plan (next): Alerting slack integration

### ISSUE THREAD

**Issue by sortizsh** [department-of-veterans-affairs/va.gov-team#53683]
## Background
Using a slack channel for Sentry alerts will add an additional layer of redundancy in case we miss email alerts. Also provides a shared space for us to reference specific alerts. 

## Acceptance Criteria

- [x] New channel set up for Sentry alerts in Slack
- [x] Appropriate team members added to channel
- [ ] Alerts for CST, Letters App, and Rated Disabilities are configured and real time notifications are coming through

## Next Steps

- [x] Request permission from Sitewide to set up channel

**Comment by HeatherWidmont** [comment]
Slack channel on DSVA: #errors-benefits-claim-appeal-status 

**Update:** Kevin will open a ticket request & tag Jacob to help nudge them

**Comment by kjduensing** [comment]
See this ticket for more details. Kevin will open a ticket request & tag Jacob to help nudge them

**Comment by kjduensing** [comment]
Update from Gia (paraphrased): something with higher priority came up, but they're back on this now
