### ISSUE TITLE
[Spike] Monitoring Plan (next): Set up cloudwatch 

### ISSUE THREAD

**Issue by sortizsh** [department-of-veterans-affairs/va.gov-team#53682]
## Background

Cloudwatch has more robust alerting. It allows us to do synthetic testing, which opens capabilities we'd use to pursue initiatives coming up later in our monitoring roadmap. 

## Open Questions

- Can we even ship logs to Cloudwatch? 
- How would we get access? 
- Who can provide access? 
- Does their current plan support synthetic UI testing? 

Spike Goal:

- Assess how viable Cloudwatch is for our purposes right now

**Comment by skylerschain** [comment]
@jacobworrell Should this be in Product Backlog, not Design Backlog?
