### ISSUE TITLE
Monitoring Plan (next): Add and document sentry tags

### ISSUE THREAD

**Issue by sortizsh** [department-of-veterans-affairs/va.gov-team#53681]
## Background 

We currently have tags for claim letters. Tags will help us group related logs so that we can search by tag in Sentry instead of more complicated filtering mechanisms. 

## Acceptance Criteria

- [ ] C&AS team has the ability to create new tags
- [ ] Team has the ability to track using tags
- [ ] Appropriate tags added for CST, Letters App, and Rated Disabilities

**Comment by skylerschain** [comment]
@jacobworrell Should this be in Product Backlog, not Design Backlog?
