### ISSUE TITLE
Implement standalone login page

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#5369]
**User Story**
When a Veteran navigates directly to the My VA Health (Cerner) website, they need landing page from which they can log in with the same federated login options as exist on the VA.gov modal

**Acceptance Criteria**
- [ ] My VA Health landing page URL directs to standalone login page
- [x] Standalone login page enables same federated login flow as exists on VA.gov modal today (accepting MHV, DS Logon, and ID.me credentials)

**Comment by bridgethapner** [comment]
First draft of the standalone login page is located here (screens 2 & 3): https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/403239060

**#5369-Standalone login page-1**
- The UX is generally very similar to the modal, with the full navigation/footer from VA.gov. 
- Placeholder headline touts the ability to access My VA Health with existing credentials.
- The text accompanying the sign-in box is updated to clarify the purpose of My VA Health and the ability to access it using existing accounts (the current VA.gov modal text focuses on the one front door).
- Information callout beneath sign-in text provides some details about what My VA Health is and its features.

**#5369-Standalone login page-2**
- Same as Option 1, with the addition of CTAs to VA.gov and MHV at the bottom of the information callout in the event users land here but are looking for something else.

**Comment by bridgethapner** [comment]
Latest wireframe of baseline stand alone login page is attached to this comment. 

**Some notes from 2/3 call with @lalexanderson-dsva & @artsymartha68:** 
- This login page needs to work for a couple different uses, so have removed reference to My VA Health in headline. 
- Have removed information box for now, as discussions about if this box should exist/what it should say are still happening. 
- We could explore a dynamic headline based on where the user is coming from & a dynamic info box, and potentially test these. The goal would be to learn if users are confused by landing on this page from Cerner and if adding context on Cerner is helpful here. To do this we'd need to include Cerner screens in the test.

![#5369-Standalone login page-1@1x.png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/7ad62545-0ca9-4303-9479-721900394695)

**Comment by bridgethapner** [comment]
@hinzed1127 Latest wireframe is attached here! 

A couple things have changed - sorry for the out of date slides deck! I'm going to mark that as deprecated.

**Comment by bridgethapner** [comment]
@hinzed1127 Wireframe is here: https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/403239055.

**Content goals & needs** The goal of this page is to basically replicate the sign-in modal in a standalone page, and use universal language so that this page can be used for multiple sites in the future. Please review: 
- Page headline (Is "Sign In" too vague?) 
- Right-hand headline and body text

Future consideration: This page could house dynamic info boxes that offer more details about the tool the user is trying to sign into, if a universal sign-in page is confusing to users.

**Comment by hinzed1127** [comment]
I've added a few sub-tasks that have sprung up out of this in #5956, specifically:

1. Update the sub-route from "login" to "sign-in"
2. Redirect to the VA.gov home page upon successful sign in (currently just goes back to the login page)

**Comment by artsymartha68** [comment]
One thing that struck me today in seeing the VA.gov prototype was the "sign in" vs. "logged out" language. Seems to me that it should be either log in/log out or sign in/sign out, but not a mixture. Obviously I leave it up to the content experts here!  :)

**Comment by hinzed1127** [comment]
@artsymartha68 that's something I found confusing, as well. plenty of flexibility to change course again if we decide on a different final option

**Comment by ambikaroos** [comment]
Current staging link: [staging.va.gov/sign-in](staging.va.gov/sign-in)
Acceptance Criteria of: My VA Health landing page URL directs to standalone login page to be moved to new ticket
