### ISSUE TITLE
Developer/Documentation Portal IA & Usability

### ISSUE THREAD

**Issue by minafarzad** [department-of-veterans-affairs/va.gov-team#537]
## High Level User Story
As a VFS team member, I need to access the right VSP documentation easily so I can build applications in a self-service and agile manner.

## Hypothesis/(es)
**If** we make our documentation easy to navigate **then** VFS teams will be able to find what they need quickly and easily.

## Goals
The solution will allow VFS members to understand what VSP documentation is available, what applies to them, and allows them to access it quickly and easily. 

## Research/Notes
The first round of user research on documentation needs can be found here: https://github.com/department-of-veterans-affairs/vets.gov-team/tree/master/Products/Platform/Platform%20Support/research/documentation-research

The second round of user research on documentation needs can be found here: https://github.com/department-of-veterans-affairs/vets.gov-team/tree/master/Products/Platform/Platform%20Support/research/documentation-research-round-2

## Definition of Done
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Epic`**

**Comment by meganhkelley** [comment]
Closing this issue — not bc this is complete but bc this is not how we are tracking this anymore.

Docs site homepage MVP is #6296 which is part of super epic #2130
