### ISSUE TITLE
Declining EULA/Deactivate leads to VA.gov

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#5371]
**User Story**
When a Veteran de-activates their account from My VA Health (Cerner) - either by declining EULA, and then deactivating, or navigating directly to the Cerner opt-out page, they need to be redirected back to VA.gov, (standalone login page or elsewhere) in an authenticated state

**Acceptance Criteria**
- [ ] Users who de-activate their My VA Health Account are redirected to VA.gov, and remain authenticated
- [ ] Consider whether there is a UX alert shown to users to reflect this status

**Comment by bridgethapner** [comment]
Draft wireframes for this state of the login page are here (screens 7 & 8 are different explorations): https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/403208545

**#5371-Declining EULA Login Page-1 & #5371-Declining EULA Login Page-2**
- Both options are similar - they use a site-wide large contextual warning alert displaying the same text shown in Craig's latest prototype for the EULA agreement page. 
- Option two users an Additional Information Accordion to offer more context to users about why they're being shown this message.
- The alert is underneath the page headline of "Sign into My VA Health" to maximize visibility by putting the alert as close to the sign-in CTAs as possible and clarify the user needs to read this information before trying to sign in again.

**Comment by bridgethapner** [comment]
Most recent wireframe is attached to this comment. 

**Notes from 2/3 meeting with @lalexanderson-dsva & @artsymartha68:** 
- Preference was for error message that includes "Why am I seeing this?" drop down, to clarify to users how they got here & what they need to do to use My VA Health.
- I pulled the language on this page from Adobe XD prototype Apothosource created of EULA flow - _if this flow changes on the Apothosource side, we should update language here._

![#5371-Declining EULA Login Page-2@1x.png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/dfcaa00e-49c6-449a-be8e-0b484f880116)

**Comment by bridgethapner** [comment]
@hinzed1127 Wireframe is here: https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/403208562.

Open state of the additional info accordion is clickable in the prototype, also here: https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/405506104

**Content goals & needs** The goal of this page is to clearly communicate to users that they have been bumped back here because they declined EULA, provide as much context as possible as to why that happened, & provide transition points to other VA sites. Please review:

- Error Alert text

**Comment by bridgethapner** [comment]
Blocked per 2/19 call - will users be logged out after declining EULA or not? Have heard both and this needs to be confirmed before we move forward.

**Comment by ambikaroos** [comment]
Lauren confirming whether this situation will 1-redirect users to VA.gov and 2-if so, whether those users will be authenticated. We do know that if users have declined EULA _and_ have no EDIPI, they need to be directed to VA.gov in an authenticated state, see #6044

**Comment by ambikaroos** [comment]
@hinzed1127 @bridgethapner 
Confirmed 2/20: per Mike Ramirez in Slack, "A deliberate user action to deactivate their account or reject the EULA will result in a redirect to VA.gov, however."

https://dsva.slack.com/archives/GM5JJ5388/p1582219483104300?thread_ts=1582213456.097500&cid=GM5JJ5388

**Comment by bridgethapner** [comment]
Blocked per updated Declining EULA flow - users will have to select Decline > Deactivate Account > Confirm Deactivation before being redirected to VA.gov. Determining in call today where they should go on VA.gov after going through the entire declining EULA flow.

**Comment by bridgethapner** [comment]
Hi @hinzed1127 - included notes from 3/2 call with DEPO team here: 

After uses deactivate EULA on My VA Health, they should be sent to the VA.gov homepage. Here are the following user flows that might apply: 

1. If a user deactivates My VA Health and does not have an SSOe session, they should go to the unauthenticated VA.gov homepage. 

2. If a user deactivates My VA Health and has an SSOe session, they should go to the authenticated VA.gov homepage.

3. If a user deactivates My VA Health and has an SSOe session and has not been to VA.gov on an SSOe session before, they should go to the authenticated VA.gov homepage, passing through the SSO communication modal (#5828).

These scenarios are captured in the overall user flows map here: https://adhoc.invisionapp.com/share/VMW6WMI9NDU#/screens/407257731_No_Notifications_High_Level_Site_Maps_For_A_MHV_-_Cerner_Patient

**Comment by ambikaroos** [comment]
@hinzed1127 @bridgethapner Thanks! I think we can actually close this ticket, because the work is all captured elsewhere:

1. Not sure if this could occur, since they'd need to authenticate first before even reaching the de-activate page, right?
2. Captured in ticket #5417 (detect SSOe session for inbound to VA.gov users)
3. As you note, captured in #5828 

We verified that it'll be the Apothesource team's responsibility to make sure that after a user deactivates, they're redirected to the VA.gov homepage.
