### ISSUE TITLE
Update New UXPin Account

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#53719]
## Issue Description
Files from Ad Hoc's UXPin account will need to be transferred to our new UXPin account. After they have been transferred, the FSR project will need to be updated.

---
## Tasks
- [x] _Work with Ad Hoc and UXPin to transfer files to new UXPin account_

## Acceptance Criteria
- [x] _Team is granted access to new UXPin account_

**Comment by HeatherRienks** [comment]
UXPin Projects successfully transferred as of 2/23/23!

**Comment by HeatherRienks** [comment]
@denisecoveyduc - I am going to move this to closed so it accurately reflects that we completed this in Sprint 93, before it rolls over into the new sprint in a few hours. :)
