### ISSUE TITLE
Remove Feature Toggles in VAOS 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#53715]
## Description
Product is requesting to remove the feature toggles that are no longer applicable in VAOS. 

---

## Acceptance Criteria

Remove the following feature toggles: 
- [x]  va_online_scheduling_facility_selection_v2_2
- [x] va_online_scheduling_variant_testing
- [x] va_online_scheduling_poc_health_apt
- [x] va_online_filter36_vats

### Design Assets
None

## Definition of Done
- [ ] All acceptance criteria are met
- [x] [Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/product/feature_toggles.md) is updated

---

**Comment by ldelacosta** [comment]
If there is any code under the feature toggle, please let us know and we will determine the next steps. Thanks.

**Comment by ldelacosta** [comment]
These two toggles will be handled in a separate ticket
- [ ] va_online_scheduling_unenrolled_vaccine 
- [ ] va_online_scheduling_status_improvement

**Comment by ldelacosta** [comment]
@jenniemc - I see the feature toggles was removed in staging but I still see the feature toggles in the production list. Please see screenshots below and let me know if you have any questions. Thanks! 
![Screenshot 2023-02-28 at 8.21.59 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/64578f01-63b1-4898-8898-f935acfb4172)
![Screenshot 2023-02-28 at 8.20.53 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/b1a46467-d6df-4d28-9fa5-7d782e24e578)

**Comment by jenniemc** [comment]
@ldelacosta, I reached out to the platform support team and created a ticket on slack about promoting the change to Production. https://dsva.slack.com/archives/CBU0KDSB1/p1677688205187279

**Comment by jenniemc** [comment]
@ldelacosta the feature toggles are removed from Production. https://api.va.gov/flipper/features

**Comment by ldelacosta** [comment]
Validated the four feature toggles have been removed in production (https://api.va.gov/flipper/features): 

1.  va_online_scheduling_facility_selection_v2_2
2.  va_online_scheduling_variant_testing
3.  va_online_scheduling_poc_health_apt
4.  va_online_filter36_vats

No new issues reported. Closing out the ticket
