### ISSUE TITLE
Content guidance and support for Medical records: Labs and tests domain

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#53711]
## Issue Description

We need to give content support on the labs and tests domain of the medical records section of the health apartment product. This work includes reviewing screens to make sure it meets VA.gov's plain langue and style standards. 

Original intake request; #53759

Artifacts provided by product team:

- Link to product outline: [Medical Records Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/digital-health-modernization/mhv-to-va.gov/medical-records)
- [Link to Lab and Test Results Domain Brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/medical-records/data-domains/labs-and-tests/labs-and-tests-brief.md)
- Link to or attach user flows: [Lab & Tests User Flow](https://www.sketch.com/s/f6118ebb-966d-4f83-afba-f9e987b65eac/a/uuid/99B84A0C-F7F8-4C23-86DA-64D9DFDE2F5C)
- Link to prototype or mockups: I've only included mobile screens for brevity, but the desktop screens are available in the [Lab and Test Results section of the main Sketch File](https://www.sketch.com/s/f6118ebb-966d-4f83-afba-f9e987b65eac/p/A47501F8-078B-42CF-977B-7BF9A31B3976/canvas#Version). 
     - [Lab and test results list view](https://www.sketch.com/s/f6118ebb-966d-4f83-afba-f9e987b65eac/a/uuid/5E6C5D42-F939-4001-A7F2-50123AF7CFA8)
     - Chemistry/Hematology details page ([collapsed accordion](https://www.sketch.com/s/f6118ebb-966d-4f83-afba-f9e987b65eac/a/uuid/225256C0-861E-4F97-BA32-312CAE53864D)) and ([expanded accordion](https://www.sketch.com/s/f6118ebb-966d-4f83-afba-f9e987b65eac/a/uuid/E41A6860-3A9A-4648-B88B-4F39FEC703E2))
     - [Microbiology details page](https://www.sketch.com/s/f6118ebb-966d-4f83-afba-f9e987b65eac/a/uuid/9488FCA1-44F8-4962-AFC9-87445C40BA3E)
     - [Pathology reports details page](https://www.sketch.com/s/f6118ebb-966d-4f83-afba-f9e987b65eac/a/uuid/E337C4A2-59F6-447F-A299-651A9B00A79C)
     - [Radiology Results details page](https://www.sketch.com/s/f6118ebb-966d-4f83-afba-f9e987b65eac/a/uuid/B91B182F-4F41-47FB-A750-8CB720114CC4) (Note: this one will include an additional image element - we will update it as soon as we figure out a couple of blockers)
     - [Historical EKG Report details page](https://www.sketch.com/s/f6118ebb-966d-4f83-afba-f9e987b65eac/a/uuid/CA547596-64DE-4124-AAEE-49EB10C32BAC)

## Tasks
- [ ] Review and edit screens 

## Acceptance Criteria
- [ ] Product team has final content

**Comment by aliyahblackmore** [comment]
**Just an update here** - I passed suggestions for the list view screen to Laura via Slack yesterday
