### ISSUE TITLE
Design Intent  - IA Feedback - CTO Health Team, MHV on VA.gov Portal, Authenticated Landing Page

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#53716]
## VFS acceptance criteria
- [x] Let Platform know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [x] VFS team closes the ticket

## Thoughts/questions
- Consider the flow and ease of navigation on this page (the order of the cards themselves, and the list items within the cards; what cards will sit side by side, the words (and icons) we use to name these categories). Also consider what's not here, and will users look for something we don't list? If you needed to add a 7th card, would it throw this pattern off? 

## Feedback
- Practice areas will document their feedback following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback).

**Must:**
- Page title (My Health) does not match the breadcrumb (Myhealthevet). These must match closely. 
- I believe the secure messaging team decided on different verbiage than "compose message" - make sure to connect with them and get the most updated language there. I synced with @mnorthuis and she mentioned having some updates/tweaks for you (possibly including the things I've listed here), so I'll stop there to avoid further duplication of feedback.

**Should:**

**Consider:**

## Platform directions
- Remove the governance-team label
- Update "Issue Title"
- Link to collab cycle Request epic
- Add your feedback
- Remove the CC-Request label (only if you created the ticket using the New Issue link from the Collaboration Cycle Reviews board)
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review QA Only**: VFS PM, yourself (optional)

**Comment by MarciMcGuire** [comment]
@rtwell @batemapf @mnorthuis - I'm looking at Collab Cycle issues that have been completed.  One of the Must items for Design Intent was related to the "Compose Message" link.  Do you all know if this was resolved?  Thanks!

> I believe the secure messaging team decided on different verbiage than "compose message" - make sure to connect with them and get the most updated language there. I synced with @mnorthuis and she mentioned having some updates/tweaks for you (possibly including the things I've listed here), so I'll stop there to avoid further duplication of feedback.

**Comment by mnorthuis** [comment]
We are using the language that is on the MHV site since that is where it's pointing to in the initial launch - "compose message" is correct!

**Comment by MarciMcGuire** [comment]
Thank you @mnorthuis !

**Comment by MarciMcGuire** [comment]
@sterkenburgsara - the "Must" feedback for this has been incorporated.  Thank you!
