### ISSUE TITLE
Lack of EDIPI leads to login page

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#5372]
**User Story**
If EULA does not find a matching EDIPI (Electronic Data Interchange Personal Identifier) health record in Cerner, the Veteran should be directed to the standalone login page

**Acceptance Criteria**
- [ ] Logged in users on VA.gov who do not have matching health records on My VA Health are redirected to a standalone login page if they try to access My VA Health
- [ ] Consider whether login page application state changes to reflect this status

**Comment by bridgethapner** [comment]
First pass at state of login page for this is here: https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/405115150

**Comment by bridgethapner** [comment]
@hinzed1127 Wireframe is here: https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/405115150. 

**Content goals & needs** The goal of this page is to clearly communicate to users why they couldn't login to My VA Health & provide transition points to both the My VA Health Help Desk & My HealtheVet. Please review: 
- All language in Error Alert

@ambikaroos We still need the My VA Help Desk info.

**Comment by ambikaroos** [comment]
Apothesource invision wireframes show state of lack of EDIPI - need to check whether this is something they are covering or if we need it as a state in the sign-in page.

**Comment by bridgethapner** [comment]
Screenshots from Apothosource screens for this story for context: 

<img width="720" alt="Screen Shot 2020-02-18 at 2 37 57 PM" src="https://user-images.githubusercontent.com/54545579/74775979-5a14c180-525c-11ea-8a4e-3f131c74dd82.png">
<img width="723" alt="Screen Shot 2020-02-18 at 2 37 49 PM" src="https://user-images.githubusercontent.com/54545579/74775983-5b45ee80-525c-11ea-8c0b-b50687363a51.png">

**Comment by ambikaroos** [comment]
Lauren confirming whether this situation will 1-redirect users to VA.gov and 2-if so, whether those users will be authenticated. We do know that if users have declined EULA _and_ have no EDIPI, they need to be directed to VA.gov in an authenticated state, see #6044

**Comment by ambikaroos** [comment]
Confirmed on 2/20 with Mike Ramirez that this instance does not result in a redirect to VA.gov, instead "it'll result in the user seeing an error page. There's no automatic/implied redirect to VA.gov in that case."
@hinzed1127 @bridgethapner
