### ISSUE TITLE
Staging Review: Design System Team Banner Official Gov't Site Web Component

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#53727]
This is a request for Staging Review: Design System Team Banner Official Gov't Site Web Component

VA DS: https://design.va.gov/components/banner/official-gov
Storybook: https://design.va.gov/storybook/?path=/docs/components-va-official-gov-banner--default

[Zoom Recording](https://oddball-io.zoom.us/rec/share/NqniN5oWa4GP23uPas3ME1fxDiQdhYYPwyJHo4sVs0VdmVqX1CvZ1pwSxMBNBbHu.R_R-ntoO0G3JgZJY)
Password: gHt$9s83

**Comment by caw310** [comment]
Please include in the invite:
Matt Dingee
Jami Gibbs
Andrew Steele
Natalie Hill
Jhonny Gonzalez (optional)
Nick Gaydosh (optional)

**Comment by allison0034** [comment]
No design feedback : )

**Comment by it-harrison** [comment]
No QA feedback

**Comment by CherylEvans** [comment]
No Content feedback. :-)

**Comment by sterkenburgsara** [comment]
No IA feedback
