### ISSUE TITLE
Login page - signed out state

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#5373]
**User Story**
When a Veteran signs out of My VA Health (Cerner), they will be directed to a standalone landing page. This landing page should reflect their signed out state.

**Acceptance Criteria**
- [ ] Logged out users from Cerner are directed to standalone login page
- [ ] Consider whether login page application state changes to reflect this status

**Comment by bridgethapner** [comment]
Draft wireframes for this state of the login page are here (screens 4-6 are different explorations): https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/403236942

**#5373-Sign out Login page-1 & #5373-Sign out Login page-2**
- These options are very similar - they both show the same login page, just with a site-wide large contextual confirmation alert with the message "You have successfully logged out."
- Option 1 includes CTAs to MHV and VA.gov within the alert
- Option 2 includes CTAs to MHV and VA.gov as body text below the alert

**#5373-Sign out Login page-3**
- This option also users a large contextual confirmation alert + 2 selectable list item cards, one for MHV and VA.gov. Body copy could be added to give context to what uses can do on each site.

**Question for discussion Monday 2/3**
- Might we want to send them back to VA.gov rather back to this login page?
- What might other sites be that users want/need to visit after logging out of Cerner besides MHV and VA.gov? This can be something we test.

**Comment by bridgethapner** [comment]
@hinzed1127  Latest wireframe is attached here and is in Invision here: https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/403236945

![#5373-Sign out Login page-2@2x.png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/4b2c6852-4481-4321-a528-ff022b7da04b)

**Comment by bridgethapner** [comment]
@hinzed1127 Wireframe is here: https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/403236945.

**Content goals & needs** The goal of this page is to clearly communicate that they have been successfully logged out of My VA Health & provide transition points to other VA sites. Please review:
- Success Modal
- 'Looking for something else?' section

Future consideration: When this page is used for eBenefits, MHV, VA.gov and more, we may need to rethink the "Looking for something else?" section.

**Comment by peggygannon** [comment]
Hello,  @bridgethapner 

I wanted to confirm that for this issue, you only need me to look at the sign out screen in the wireframe? I see there are other screens, but it's not clear if those are ready for a content review? Please let me know. 

-----

Here are my recommendations for the sign out screen: 

1. Update message at top TO:  You have successfully signed out

2. I recommend changing this header "Looking for something else?"  to one of the below: 

Other VA benefits or services
OR
Looking for other VA benefits or services? 
OR 
More information about VA benefits

**Comment by bridgethapner** [comment]
Hi @peggygannon - Thank you for the content! 

The only two issues related to the stand-alone login page are this one and #6420, which is also ready for a content review. Does that answer your question?

**Comment by peggygannon** [comment]
Yes, thank you. @bridgethapner My question was about the wireframe mockup. I wasn't sure if this screen was ready for me to provide content, or if it was still a WIP?

![2020-03-05 (2).png](https://images.zenhubusercontent.com/59b0414bb0222d5de476aa22/07e8ff72-b533-414c-b86f-b87ce0b2a1bb)

**Comment by bridgethapner** [comment]
Oh sorry! @peggygannon Yes - #5828 is ready to go!

**Comment by bridgethapner** [comment]
@hinzed1127 

Desktop wireframe here: https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/403236945
- Please put a 70px margin between blue header bar and success alert
- Please put 40px padding between the bottom of the success alert + the headline "Looking for other VA benefits or services?"
- Please put 70px padding between "eBenefits" link and H1 

Mobile wireframe here: https://adhoc.invisionapp.com/share/5QWAJJQNG2J#/screens/408139785

**Comment by peggygannon** [comment]
Hi, @bridgethapner Content updates to the sign-out log in page look good.

**Comment by hinzed1127** [comment]
Right now I'm having this state be triggered by navigation to the login page with query params `logged_out=true` (ie, https:/staging.va.gov/sign-in?logged_out=true). Once we land on if this is the exact value we want, this will need to be communicated to Cerner's dev team.

cc @ambikaroos
