### ISSUE TITLE
General Alert boxes UX research

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#5374]
**Description**
Identify research areas, and begin to log potential research questions.

**Tasks**
- [x] Invision prototype of screens
- [x] Discussion guide

**Comment by bridgethapner** [comment]
# SSO: VA.gov Manage Benefit Page Alerts Discussion Guide

**[Internal] Research Objective**
Discover if design directions for alert box updates enable participants to understand what the arrival of My VA Health means for managing health benefits online via VA.gov Manage Benefits pages.

**[Internal] Research Questions**
1. Do our screens enable participants to comprehend the arrival of My VA Health?
2. What, if anything, do participants find unclear? 
3. What questions or feedback do participants have about My VA Health? 
4. Does one direction facilitate comprehension more than the others? Why? 


## Introduction (5 minutes)
Thank you for joining us today. My name is Bridget and I also have some colleagues on the line observing and taking notes.

Today, I’d like to talk about some of your interactions with VA online healthcare management tools, and also get your feedback on how we might communicate changes to healthcare management tools on VA.gov. I'm going to ask you some questions and we will look at the website VA.gov together, then I'd like to show you some updates we're considering making to VA.gov. 

Before we start, there are a few things I want to mention: 
- This entire session should take about 30 minutes.
- In our conversation today, we want to hear your honest opinions. My team’s goal is to improve VA online tools to better meet the needs of Veterans like you. I will not be offended by any opinions you express - please be as honest as you feel comfortable being with me today. 
- If it’s alright with you, I would like to record our conversation. We use the recordings to confirm that we have captured your opinions accurately. The recordings are deleted after we complete analysis, and won’t be used for anything other than our internal research purposes. Are you comfortable if I record the screen and audio as we talk today? 
- If yes: Once I start recording, I am going to confirm that you are ok with me recording this session once more.

Those are all the logistics I wanted to share. Do you have any questions for me before we get started?


## Warm Up Questions (5 minutes)
First, I want to learn a little more about you and how many VA Medical Centers you visit to receive health care. 
- Do you have a primary VA Medical Center?
- What other VAMCs do you visit on a regular basis, say once a year or more?   
- [Recap VAMCs participant listed]: Are there any other VAMCs you have visited in the last year?
- Do you know if you’re registered at any other VAMCs?
_[Prompt: These may be facilities you’re not currently using.]_

Great, thank you for sharing that. I'd next like to talk about your experience using My HealtheVet.
- Have you used My HealtheVet to manage your healthcare?
- Can you tell me a little bit about your experience using My HealtheVet?
- Have you visited VA.gov to get information about managing your healthcare benefits?

I’d like to look at VA.gov together for a minute. I have pulled up VA.gov here on my screen, and navigated to the section of the site I’d like to talk about today: VA Secure Messaging. I’m going to give you control of the mouse. What I’d like you to do is explore this page at your own pace. Don't click on anything yet.
- What sticks out to you as important? 
- Why?


## Manage Benefits Alerts (15 minutes)
Now I’d like to show you a prototype of a couple different version of the same page we were just looking at: VA Secure Messaging. These versions of this page are different options for how updates to this page might look. This prototype isn’t a real website and nothing is clickable.

First, I want to give you some context about what you’ll see. Some VA Medical Centers are switching from My HealtheVet to a new healthcare management tool called My VA Health.
[Option 1](https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/403460158)
[Option 2](https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/403460274)
[Option 3](https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/404834770)

**First Look: Repeat for all 3 options**
- What sticks out to you the most about this screen?
- What information seems important here?

**[Internal] Prompts for each option**
- Option 1: What do you think of this message about your registration? 
- Option 1: What do you think about seeing My VA Health first, and My HealtheVet below it?
- Option 2: What do you think about seeing this one alert box with all your Secure Messaging Tools?
- Option 2: What do you think about these buttons?
- Option 3: What do you think about this option to select which VA facility you'd like to message with?
- Option 3: What do you think about this information box and what it says? 

**First Comparison**
Before we look at each screen again in a little more detail, did one option stick out as clearer and easier to comprehend than the others? 

**Follow Up Questions: Repeat for all 3 options**
- Let’s say you want to send a message to a provider at Mann-Grandstaff VA Medical Center. What do you do?
- Let’s say you want to send a message to a provider at any other VA Medical Center outside of Mann-Grandstaff. What do you do?
- Let’s say you come to VA.gov, and you want to send a message to a provider at Mann-Grandstaff VA Medical Center, and a provider at another medical center. What would you do?
- Were there any questions that were raised for you in trying to complete these 2 tasks?
- What information on the page was helpful in helping you determine what to do?
- On a scale of 1 to 5, 1 being least clear and 5 being the most clear, how easy to comprehend do you find this option? 

**Second Comparison**
Now that we’ve looked at all 3 options in detail, does one option stick out as clearer and easier to comprehend than the others? Why?


## Wrap Up (2 minutes)
That’s all the questions I have for you today. We really appreciate you taking the time to share your thoughts with us. Your feedback is so helpful to us as we continue to work on the site and make sure it really works for Veterans like you.

Enjoy the rest of your day!


## If we get to it: SSOe Session Communication 
I’d like to switch gears to something different in a few remaining minutes we have.

VA.gov is launching a new feature called single sign-on. With this feature, you will be able to log in once to VA.gov and be able to also access My HealtheVet, eBenefits, and other new tools like My VA Health.
- What do you think about this feature?
- Do you have any questions about it and how it would work?
- If you saw [this alert](https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/405051384) on VA.gov after logging in, what would you think? 
- Would you want to see any more information? 


## Back pocket answers
**If a Veteran asks: What is My VA Health?**
My VA Health is a tool that houses electronic health records, and will allow you to manage tasks related to your healthcare online, like scheduling appointments, messaging, viewing lab results, and more.

**If a Veteran asks: Will I need to use this?**
To start, the VA is launching My VA Health at one VA Medical Center. Over time, it will launch at other Medical Centers. 

**If a Veteran asks: Will I need to manage my healthcare in 2 different places?**
As My VA Health is launched at VA Medical Centers around the country, a team at the VA will be working to minimize the possibility of needing to work across 2 tools. To start, that will be the case, but that won’t always be the case.
