### ISSUE TITLE
Business intake form for VBA/BTS Claims Intake

### ISSUE THREAD

**Issue by dostergaard-leidos** [department-of-veterans-affairs/va.gov-team#53741]
## Your Details
1.  **Your Name**
Dean Ostergaard
​
2.  **Business Line**
VBA / BTS (Claims Intake)
    (ex., claims, health, etc.)
​
## Notification Details
1.  **Notification type**
email
    (email, text/SMS, or both)
​
2.  **Please describe your use case.**
Per the Centralized Mail Portal BRD: When a CM Portal pending deactivation email is sent to a system account holder the email "from line" indicates that it was sent from a va.gov email domain server.

In order to avoid the appearance of spam or phishing the email cannot originate from a non-VA email server.
    (This is your chance to tell us an overview of your plans.)
​
3.  **What actions can the user take based on the notification they receive?**
Click on a link to access the CM Portal
    (ex., view secure messages, fill out a survey, schedule an appt, etc.)
​
4.  **What is the desired business outcome?**
Avoid inadvertent account deactivation
    (ex., fewer skipped appointments, less call center volume, etc.)
​
5.  **What system will kick off the notification? Please note the system should be inside the VA or have an ATO.**
Centralized Mail Portal (We have an ATO)
    (ex., BVA hearing reminders are kicked off from Caseflow)
​
6.  **What will trigger the notification?**
Number of days countdown to account deactivation.
    (ex., clicking submit, status updates for claims, appointment reminders, new services available)
​
7.  **Provide sample content per notification type, if you have it.**
![image](https://user-images.githubusercontent.com/125480532/219074578-4ef8aa57-5067-4e71-909e-15dac611050c.png)

    Please note we collaborate with all of our users on their content to ensure it meets standards.
​
8.  **Has a Privacy Officer (PO) seen and approved the content? If not, do you know who your PO is?**
Review and approval pending
    (ex., PO has seen the content but it is not approved)
​
9.  **Would you prefer to provide contact information for the recipients or would you rather VA Notify look this up for you by Veteran ID? If by ID, please let us know what identifier is used in your system.**
We will provide contact info (email address)
    (ex., VAPROFILEID, PID, BIRLS, ICN, etc.)
​
10.  **Do you currently capture communication preferences related to this notification? If so, please describe.**
This is a mandatory communication for users of the Centralized Mail Portal who are VA employees and contractors.
    (ex., opt in for claim status updates via email or text)
​
11.  **What is the anticipated volume of notifications per day, week, month?**
Less than 100 per month
​
12.  **When does this notification need to be in production?**
As soon as we can get this implemented.

**Comment by dostergaard-leidos** [comment]
Update to number 11 Anticipated volume averaged 894 per month based on 2022 numbers.

**Comment by bevnobev** [comment]
Hi @dostergaard-leidos Clarifying question for you.  Are these emails going to Veterans or VA employees and contractors?  Asking because you mentioned VA employees and contractors but fyi, our emails do come from va.gov domains, but they show up with an "External" tag when emailed to va.gov addresses

**Comment by dostergaard-leidos** [comment]
Hi @bevnobev Thanks for the question.

Currently it will be just VA Employees and contractors. The public access portion of our platform was turned off last year.

Our main goal is to not have our emails flagged as spam or phishing because the domain of the originating server differs from what is claimed in the "From" header. I will have to raise the question of the "External" subject tag with our COR and requirements analyst but so far VA Notify seems more promising than any other alternative we have found.

Thanks,
Dean

**Comment by dostergaard-leidos** [comment]
Is it possible to get the raw text of a generated sample email including all SMTP headers that are included when the recipient receives it? I am particularly interested in the Return-Path and Received headers.

Thanks,
Dean

**Comment by mjones-oddball** [comment]
@dostergaard-leidos Is this what you're looking for below? We use Amazon SES as our email provider. Our from email address is "U.S. Department of Veterans Affairs" <do-not-reply@notifications.va.gov>


```
Received: from 82230337636 named unknown by gmailapi.google.com with HTTPREST; Thu, 2 Jun 2022 11:18:39 -0700
Delivered-To: melanie.jones@oddball.io
Received: by 2002:a05:6520:3815:b0:1d0:567f:1bd5 with SMTP id b21csp6796487lkx;
  Thu, 2 Jun 2022 11:18:31 -0700 (PDT)
X-Google-Smtp-Source: ABdhPJyiqfmeIuwasEtrSxcFAVp3pJELNfoKbwlXf+kaLR2MZUUNcPDtKf+LsME/aR2yIc/gIv63
X-Received: by 2002:a17:90a:4fc7:b0:1df:9b7b:e610 with SMTP id q65-20020a17090a4fc700b001df9b7be610mr6679137pjh.177.1654193910999;
  Thu, 02 Jun 2022 11:18:30 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1654193910; cv=none; d=google.com; s=arc-20160816; b=Oh7Hz/ZA51/35e7i+Ps/G/+G4c1NkaOYw8GQm/IcgZ+40Y5e7oLG+5yueK54G3ORd5 QiWzH2FvNtmbP0UHBa71q5g/GNgsuv5IfvwVl5BtuUm2Wz1DQs95F1qDL0+DnxfJ0bnO SFdg7l5/tYyzOJZsGdspKwQ+W8FwQfykxPQxnisGezvdx5N3JHZ72O5v0II6UO202mfi aSNEfrC1mCa6iy7NsLXeLxQ3sebNhbjkyyq7yjNO/OUrN9VvIIZPZVUux8UcM61ZmQOe 5/DLGS7eawZ8rmyqwG2oP7C+bXejj2WVC44qRPRG4um9W1gJ4suT5ASJlRXerSLqo/sp SshQ==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
  h=feedback-id:date:message-id:reply-to:to:from:subject:mime-version :dkim-signature:dkim-signature; bh=cxheuQ7d8OrBZiDb8dhHGJUhfDkxxDh1ROOPlqXqZz0=; b=Osev1gF8sTVPGcato7PqM2ctz7SXIGiirG6qwNh/bF8UpdvpHmXPKQGY446VvXGxub OCahiGt4+7nDMaQpqgZi2W+HdtQEUtQMAaofCFmtYRqGHQmJ4dGT03c9X2U0Kg3j153G BBshCd5G4bZLZKza84unW2iT7ZliFehb5QEzs1f4ZbyFWOnVL0MY+m4oPzzzEwAEDQWU Z0rkLUmxsUozuBC3T30VTfpN6MFZgUVvTkdF8wOpdI38HLuUyIYkD72LEQikgirTu8cU J9OOrk8xjnmgb8e1lAQUPuVdDRmLkEYFI7pwmFsRP0amFGHiAoOyTPftOVtRF0DUEPGg MsPQ==
ARC-Authentication-Results: i=1; mx.google.com; dkim=pass header.i=@notifications.va.gov header.s=5ako3b5jlikln2ujarmq3atwiupm2ajx header.b=Dh0LQN+9;
  dkim=pass header.i=@amazonses.com header.s=kjytgwkcdurs3ghwzikg3mpvqzpkccec header.b=a45ZHkOq; spf=pass (google.com: domain of 010a018125a3f040-c959ab40-1607-4e10-81eb-f933fb0966f9-000000@ses.notifications.va.gov designates 23.249.212.27 as permitted sender) smtp.mailfrom=010a018125a3f040-c959ab40-1607-4e10-81eb-f933fb0966f9-000000@ses.notifications.va.gov; dmarc=pass (p=REJECT sp=REJECT dis=NONE) header.from=va.gov
Return-Path: <010a018125a3f040-c959ab40-1607-4e10-81eb-f933fb0966f9-000000@ses.notifications.va.gov>
Received: from d212-27.smtp-out.us-gov-west-1.amazonses.com (d212-27.smtp-out.us-gov-west-1.amazonses.com. [23.249.212.27]) by mx.google.com with ESMTPS id r9-20020a17090aad0900b001dfde430e6bsi6723588pjq.16.2022.06.02.11.18.30 for <melanie.jones@oddball.io> (version=TLS1_2 cipher=ECDHE-ECDSA-AES128-GCM-SHA256 bits=128/128); Thu, 02 Jun 2022 11:18:30 -0700 (PDT)
Received-SPF: pass (google.com: domain of 010a018125a3f040-c959ab40-1607-4e10-81eb-f933fb0966f9-000000@ses.notifications.va.gov designates 23.249.212.27 as permitted sender) client-ip=23.249.212.27;
Authentication-Results: mx.google.com; dkim=pass header.i=@notifications.va.gov header.s=5ako3b5jlikln2ujarmq3atwiupm2ajx header.b=Dh0LQN+9;
  dkim=pass header.i=@amazonses.com header.s=kjytgwkcdurs3ghwzikg3mpvqzpkccec header.b=a45ZHkOq; spf=pass (google.com: domain of 010a018125a3f040-c959ab40-1607-4e10-81eb-f933fb0966f9-000000@ses.notifications.va.gov designates 23.249.212.27 as permitted sender) smtp.mailfrom=010a018125a3f040-c959ab40-1607-4e10-81eb-f933fb0966f9-000000@ses.notifications.va.gov; dmarc=pass (p=REJECT sp=REJECT dis=NONE) header.from=va.gov
DKIM-Signature: v=1; a=rsa-sha256; q=dns/txt; c=relaxed/simple; s=5ako3b5jlikln2ujarmq3atwiupm2ajx; d=notifications.va.gov; t=1654193909; h=Content-Type:MIME-Version:Subject:From:To:reply-to:Message-ID:Date; bh=cxheuQ7d8OrBZiDb8dhHGJUhfDkxxDh1ROOPlqXqZz0=; b=Dh0LQN+9jZDoPb1RRHyXo/yM0hOaAC1397Q8A4TxfzKyP2gp8SXuBgY49QFt5ytc /he9yiazdOK2DPjDuwXB2PlXDq6QdNw9FPTIGfa/GDoVY1IVSdN2zyi/Wj4odj7o1VF BOHVnkpmjGiNMy5CC8YpmhLs97o8NkpP1x5xAyZk=
DKIM-Signature: v=1; a=rsa-sha256; q=dns/txt; c=relaxed/simple; s=kjytgwkcdurs3ghwzikg3mpvqzpkccec; d=amazonses.com; t=1654193909; h=Content-Type:MIME-Version:Subject:From:To:reply-to:Message-ID:Date:Feedback-ID; bh=cxheuQ7d8OrBZiDb8dhHGJUhfDkxxDh1ROOPlqXqZz0=; b=a45ZHkOqZG6vkOqY8zmhLEvUKQb567Otx++bbUzxMWBGgqEh/GumB1musNqOY8cP vC0NVYJjpQymMC8qGnslU1gKKMVRlFmJv2EP4HRqktpx3A2VUBall+PBQuR6gd97aJa qtjWDHWjjAxvrrOENFaFX2oXmMN9Qja7iFdBIsm0=
Content-Type: multipart/alternative; boundary="===============4267310645758064856=="
MIME-Version: 1.0
Subject: Action Required: Verify Your Monthly Enrollment for VA
From: "U.S. Department of Veterans Affairs" <do-not-reply@notifications.va.gov>
To: melanie.jones@oddball.io
reply-to: vbaatgdonotreply@va.gov
Message-ID: <010a018125a3f040-c959ab40-1607-4e10-81eb-f933fb0966f9-000000@us-gov-west-1.amazonses.com>
Date: Thu, 2 Jun 2022 18:18:29 +0000
Feedback-ID: 1.us-gov-west-1.oGbqFEtpYt3ElwI6ntMlFn4nOQx1wo9Ndwg1krTcQX0=:AmazonSES
X-SES-Outgoing: 2022.06.02-23.249.212.27
X-IS-Marked: true
```

**Comment by dostergaard-leidos** [comment]
That is perfect! Thank you!

**Comment by dostergaard-leidos** [comment]
@mjones-oddball I do not have a va.gov email, nor does the developer I was going to assign this to. Is it required to access the sandbox? I have others on my team who have VA email accounts but they won't be directly involved in the development of this notification feature.

**Comment by mjones-oddball** [comment]
@dostergaard-leidos To access our Self Service Portal you must be on the VA Network and login is via your PIV card. Our Portal is used to create and manage notification templates. We also use VA.gov email to securely send an API key via encrypted email, which is used to authorize your system to make the notification API calls to send the emails. 

1. Are you and the developer you want to assign awaiting PIV and VA.gov email addresses or is this not something you are required to get? Do you have a PIV exemption in place? This is a new situation so I just want to learn more. 
2. How do your users access the CM Portal?
3. Where is your system hosted? Is it behind the VA network? We have public and private URLs depending on the situation.

**Comment by dostergaard-leidos** [comment]
@mjones-oddball We provide a managed service (SaaS) to the VA. Our systems are hosted in our own secure AWS GovCloud environment. I have had no need for access to VA systems (other than TMS which is accessible from outside). Therefore I gave up my PIV card a couple of years ago. We have some people who do access VA systems but the developer for this feature is not one of them.

1. For either of us to  gain access to the VA networks would require us to initiate a new PIV request for this purpose.
2. CM Portal is a Web Application accessible via public URL with VA IAM PIV Authentication. My team has systems administration access via our own private interface. 
3. The system is Hosted in AWS GovCloud via public URL. We are not on the VA network. 

Please let me know if you need more info.

**Comment by mjones-oddball** [comment]
@dostergaard-leidos Thank you for providing more info! This is very helpful. Beverly, our VA Product Owner, is traveling through the end of this week. I'm going to chat with her when she returns next week and get back to you on next steps and/or follow up questions.

Your system not being behind the VA Network is not an issue for us, you would just use our public API url when making notification requests.

**Comment by mjones-oddball** [comment]
@dostergaard-leidos What is the VASI id for Centralized Mail Portal?

I discussed with Beverly, we don't have a workaround for individuals who do not have VA access/PIV. Are you able to provide a va.gov email address for someone on the team who is able to assist you with managing notification templates and a technical contact with a va.gov email who can securely receive the API key?

**Comment by dostergaard-leidos** [comment]
Hi Melanie (@mjones-oddball), The VASI ID is 2926.

I will get you the contact info for someone on my team with VA accounts later this afternoon after our sprint planning meeting.

**Comment by dostergaard-leidos** [comment]
@mjones-oddball,
Ray Matteson (raymond.matteson@va.gov) will be our point of contact for VA emails. He will also be our template developer.

**Comment by dostergaard-leidos** [comment]
@mjones-oddball, Ray has not heard from anyone at VA Notify regarding access tokens or sandbox access.

**Comment by bevnobev** [comment]
Hi @dostergaard-leidos Sorry for the delay.  Melanie plans to reach out to Ray by EOD today.

**Comment by mjones-oddball** [comment]
Hi @dostergaard-leidos I'm very sorry for the delay. I added Ray to our sandbox and emailed him the info he needs to get started. Once you all are confident and ready to move forward I will move Ray to a dedicated service in both our Staging and Production environments. All work starts in Staging where you can fully test before moving to Production. Please reach out if you have any questions!

**Comment by mjones-oddball** [comment]
@dostergaard-leidos Good morning, Dean. I'm just checking in to see how everything is going. Have you made a determination on whether or not you'd like to move forward with VA Notify? If you have any questions please let me know.

**Comment by dostergaard-leidos** [comment]
Hi @mjones-oddball Things have gone well so far. Ray was able to develop and refine a template suitable for our use case and we are ready to move on to the next step. Our emails are generated from a database so my DBA / Data Architect will be modifying our scripts to use the VA-Notify services. Please let me know what we need to do to move on to the next phase.

Thanks,
Dean

**Comment by mjones-oddball** [comment]
Good morning @dostergaard-leidos that is great news! Next phase is to move you out of the testing service and into your own service in Staging and Production. I will follow up with Ray on our encrypted email thread no later than Tuesday. Just a heads up for your DBA that some configuration points used to make the notification request change depending on the environment you're in. Service id, template id, and api key are all unique per environment.

**Comment by mjones-oddball** [comment]
@dostergaard-leidos Just following up here, Ray was sent info on how to access your new service "DMHS CM Portal" in both Staging and Production. Please let me know when you have a goal launch date in mind.

I also let Ray know that you all can configure a customer reply-to mailbox so that if anyone does reply to your emails you would have access to see them. It does not change the email address the notification is sent from, only what the recipient would reply to. Other business lines have felt it useful to see and learn from these responses as they sometimes indicate an issue with the notification or process. Although they are meant to be no-reply notifications, people do reply sometimes. 
![image](https://user-images.githubusercontent.com/99204969/228361468-0dadaa67-5d98-4af8-9a52-bbfcb925a3ff.png)

**Comment by dostergaard-leidos** [comment]
Hi @mjones-oddball 

Our target for release of this feature into production is currently targeted for our 1.38 release on 6/25/2023.

**Comment by mjones-oddball** [comment]
@dostergaard-leidos Thank you for sharing! Please let us know if you need anything in the meantime.

**Comment by mjones-oddball** [comment]
@dostergaard-leidos Just wanted to check in as I know you're planning to launch later this month. Anything your team needs? Is 6/25 still the goal?

**Comment by dostergaard-leidos** [comment]
@mjones-oddball Thanks for checking in. We are on track for the deployment on the 25th we _**may**_ deploy earlier but I'll let you know beforehand if that happens.
