### ISSUE TITLE
IA design - Login.gov Transition

### ISSUE THREAD

**Issue by kristinoletmuskat** [department-of-veterans-affairs/va.gov-team#53762]
Link to WIP google doc: https://docs.google.com/document/d/1n2UkxQw0YZU1lttNH5iFOq01Zh_79A2-YRXXuf8ENOg/edit#

**Comment by kristinoletmuskat** [comment]
Adding link to our Mural WIP of the user flows: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1676397151510/f4cf4f4187a3d0fd5f2d6d56c9bd2ba3a4376e7a?sender=ua67f17f1c416a96ea04d2476

Next step is to meet with the login team to talk through potential user pain points and use cases we might wanna add

**Comment by kristinoletmuskat** [comment]
Documentation of IA decisions and open questions is here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/auth-DSL-grandfathering.md

**Comment by mnorthuis** [comment]
I believe primary IA work for this effort is complete.  IA will continue support as questions come up, but closing out this work effort.
