### ISSUE TITLE
[BE] SPIKE: What is involved in our sending a text message for travel claim submission status

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#53763]
## Description
We need to determine the work that is needed to send a text message to a Veteran with the status of the Travel claim submission using VA Notify and create all work tickets necessary to complete the feature.

## Tasks
- Get access to VA Notify API
- Insomnia harness or swagger docs
- Create BE tickets to fully implement sending a text message to a Veteran

**Comment by loripusey** [comment]
@acrollet @brianseek @wullaski @kanchanasuriya @randomsync 
Feel free to add questions

**Comment by acrollet** [comment]
Linking Slack thread with discussion and decision to use VEText API for MVP: https://dsva.slack.com/archives/C02G6AB3ZRS/p1676490560668649

**Comment by acrollet** [comment]
https://www.va.gov/health/VEText.asp includes the text:

> Text messaging rates may apply depending on your individual cell phone plan.

**Comment by acrollet** [comment]
NB there is also a link to a sharepoint page with VEText API docs in the slack thread linked above: https://dsva.slack.com/archives/C02G6AB3ZRS/p1676493824785029?thread_ts=1676490560.668649&cid=C02G6AB3ZRS

**Comment by loripusey** [comment]
Backend to pick this up next; create design doc
