### ISSUE TITLE
Prescription page alert updates for Cerner patients

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#5377]
**User Story**
When a Veteran who is a patient at a Cerner facility is logged in on VA.gov and is on the Prescription Refill and Tracking page (https://www.va.gov/health-care/refill-track-prescriptions/), the alert box should explain to users that they will be directed to the appropriate page on My VA Health. 
_Note that in March, we may not want patients to be directed to Cerner if prescription information is missing or out of date_

**Acceptance Criteria**
- [ ] Alert box UX lets authenticated users know that they will be directed to Cerner to view their prescription list, but that prescription refills and historical records remain in MHV, and provides correct links to both prescription pages. 
- [ ] TBD: new tab automatically opens to correct Cerner page without requiring additional log in by user 
- [ ] Unauthenticated experience of the alert box is unchanged

**Comment by christine-dillman** [comment]
Not applicable to Identity/SSO.
