### ISSUE TITLE
MPI SSN Parsing Investigation

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#53774]
## Issue Description
Slack discussion thread: https://dsva.slack.com/archives/C04MM3WJN1E/p1676493245311899

The Identity team was alerted to a test user whose SSN was not properly being parsed through SiS logins, but did appear through SSOe logins and IAM session attributes:
```
username: va.chatbot.team+qa.three@gmail.com
password: oLyIbry}5TJnYtH<yYrP
```

Identity engineers examined the raw MPI profile response and discovered that the SSN XML block was slightly malformed:
```
<asOtherIDs classCode="SSN" nullFlavor="OTH">
  <id extension="900559102" root="2.16.840.1.113883.4.349"/>
  <statusCode code="S"/>
  <scopingOrganization classCode="ORG" determinerCode="INSTANCE"><id root="1.2.840.114350.1.13.99997.2.3412"/></scopingOrganization>
</asOtherIDs>
```
The `id root` passed does not match the expected `SSN_ROOT_ID` constant in vets-api; for this user the id root ends with `4.349` instead of the expected `4.1` from users without issue (below is the response for `vets.gov.user+228`):
```
<asOtherIDs classCode="SSN">
  <id extension="141557840" root="2.16.840.1.113883.4.1"/>
  <statusCode code="4"/>
  <scopingOrganization classCode="ORG" determinerCode="INSTANCE"><id root="1.2.840.114350.1.13.99997.2.3412"/></scopingOrganization>
</asOtherIDs>
```

## Tasks
- [ ] Resolve the SSN parsing issue for user `va.chatbot.team+qa.three@gmail.com`

**Comment by aparsley** [comment]
Completed work.
