### ISSUE TITLE
Update incoming web footer form

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#53784]
### Background
Potentially add a question to web footer intake form to ask whether the customer is a Platform team member vs VFS team member.

### Tasks

- [x] Review the configuration of this YAML form: https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=vbellissimo%2C+ssimmorins%2C+amygoldman&labels=documentation-support%2C+pw-footer-feedback&template=platform-website-footer-feedback.md&title=
- Find out whether/how it may be edited to ask an additional question
- If we're not able to figure out how to update it, create next task to reach out to #vfs-platform-support for help.

**Comment by taylojill** [comment]
@vbellissimo I found the issue template for the footer, and it looks like a simple task to add the additional heading. We need to figure out how to word it. Let me know what you think!
