### ISSUE TITLE
[BUG] User should see "VA Appointment" when value for Type of Care is absent

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#53780]
## Problem
In the absence of a field value for the Type of Care, the user is supposed to see "VA Appointment". Please refer to the following annotations in the [Sketch file](https://app.abstract.com/projects/ab30c34e-e2f9-4d3e-bb96-3b683b006c24/branches/0240c5f8-14e4-4b87-8cde-cd1de046993f/commits/latest/files/585436fe-2120-45f4-b4f7-fbae01d258d9/layers/453D3779-C99D-45C1-B0D9-16FB6EEA6F0F?collectionId=a7738beb-2c4a-44ad-b7f4-4ec19cbbe51a&collectionLayerId=e5982697-1fd2-4b3d-8af0-e34b3cb33be5).

![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/369b99ea-c929-4fb2-80ad-09c88d05eaf3)

## Screenshots from  Staging (left is Sketch, right is Staging
![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/cf9ffc1d-4da5-43a6-984c-9df0937dc347)

![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/8d1e7470-d0cb-4fa3-8bc3-e119e5734a3b)

**Comment by brianseek** [comment]
@benbrasso-agile6 The fix for this was just merged and should be validate-able on stage soon

**Comment by benbrasso-agile6** [comment]
Can't validate yet. Sscheduling tool been giving me issues.

**Comment by brianseek** [comment]
@benbrasso-agile6 I would test the same you were using before looks like ECHO CLINIC 5 from the screenshots

**Comment by benbrasso-agile6** [comment]
I think that clinic has a value in type of care, but i'll check again

**Comment by benbrasso-agile6** [comment]
validated
