### ISSUE TITLE
AWS access for [John Bramley]

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#53794]
### COR Name

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

John Bramley

### Your Email

john.bramley@oddball.io

### Team, Role, and Company of the target individual

Identity-Godzilla, Backend Engineer, Oddball

### Product Manager (PM) name and email

Matt Conway - mconway@clarityinnovates.com

### Product Owner (PO) name and email

John Rahaghi - john.rahaghiva@gmail.com

### Desired AWS Access

existing

### Access Expiration

ongoing

### Additional Notes

I recently transitioned from Ad Hoc to Oddball while remaining an Identity team member; my PIV card remains active and I can access my va.gov email. My credentials for AWS access were stored in my old laptop & Chrome profile, I am requesting a credential reset so that I can access it again from my new equipment.

COR: Ray Wang

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by little-oddball** [comment]
VFS Team

**Comment by rmtolmach** [comment]
>  I am requesting a credential reset so that I can access it again from my new equipment

@bramleyjl You can request this from DevOps in #vfs-platform-support

**Comment by bramleyjl** [comment]
My AWS access has been restored, closing this.
