### ISSUE TITLE
Debt Resolution Team Onboarding: Joseph Lee

### ISSUE THREAD

**Issue by HeatherRienks** [department-of-veterans-affairs/va.gov-team#53802]
## Welcome to the Debt Resolution Team

---
This ticket is to track onboarding efforts.
## Pre-Onboarding

**Delivery Manager Tasks**

**Access Requests**

- [x] Request [Access to VA Organization in GitHub](https://github.com/department-of-veterans-affairs/github-user-requests/issues/new?assignees=moschette%2C+AprilPrimous%2C+KennethC19&labels=add-user-to-org%2C+new-user%2C+user-created&template=add-user-to-the-va-organization.md&title=ADD+USER+TO+ORG+-+%5BUSERNAME%5D)
- [x] Access to [VSA GitHub Repositories](https://github.com/orgs/department-of-veterans-affairs/teams/va-gov-vsa/members)
- [x] Request access to [DSVA Slack Workspace](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=KevinMHoffmanUSDS%2C+LEHigley&labels=Slack+Request&template=slack-request-template.md&title=Adding+%5Bindividual%5D+to+DSVA+Slack)
- [x] Request New Hire to Complete VA Onboarding Paperwork
- [x] Create a [Platform Orientation ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=&template=orientation-epic.md&title=Platform+Orientation+Template) for getting onboarded with VA.gov Platform
---

## Onboarding

**New Hire Tasks**

- [x] Begin VA Contractor Onboarding paperwork (sent by prime contractor onboarding contact)
- [x] Review Onboarding checklist (this will be provided by your delivery manager)
- [x] Meet with Onboarding Buddy, set up daily check in cadence for first 2 weeks
- [x] Complete Platform Orientation ticket tasks

**Comment by josephrlee** [comment]
This is almost done! I have an accessibility and analytics platform orientation that's scheduled for next week!

**Comment by josephrlee** [comment]
Marking this as done. I have a design orientation on Monday, but I've done everything else!
cc: @HeatherRienks
