### ISSUE TITLE
Contact Center Review for [Digitize Forms - Form 26-4555]

### ISSUE THREAD

**Issue by tbaker1026** [department-of-veterans-affairs/va.gov-team#53800]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
Form 26-2555 is an Application for Speciality Housing currently available in PDF form, but will now be available in a digital online version.  Note:  The PDF will still be available. 

### Launch Date
Tentative around March 17th, 2023

### Version Number
Version 1

### Product Guide
[Product Guide](https://docs.google.com/document/d/1P8ReFnSNLd9qI3lgx1daHwwshqRl87s71NUxfkohBeo/edit#heading=h.2uq1v8id876k) - STILL IN PROGRESS

### Product Video
*Please provide product video link*

### Product Video Transcript
*Please provide product video transcript link*

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
Hi @tbaker1026. Guide looks good; sent to VEO for review, will attach copy to ticket after they're done.

**Comment by starlow00** [comment]
No changes to product guide. Current draft attached[https://app.zenhub.com/files/133843125/385c84bb-fb6b-4c1b-b7b4-3de6a638e421/download](https://app.zenhub.com/files/133843125/385c84bb-fb6b-4c1b-b7b4-3de6a638e421/download).
