### ISSUE TITLE
SOCKS access for Joann Agnitti

### ISSUE THREAD

**Issue by joagnitti** [department-of-veterans-affairs/va.gov-team#53801]
### Your Name

Joann Agnitti

### Your Email

joann@cityfriends.tech

### Your Role and Team

Senior UX Researcher

### Product Manager (PM) name and email

Erika Washburn erika@cityfriends.tech

### Product Owner (PO) name and email

Dave Conlon david.conlon@va.gov

### Access Type Requesting

viewers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDekT9STuBWO3oEB0ToCo9o1Inpak+yAu8Aa9RgyPFrGIPfbi5/cnxFpJPQCDVq2984Kha6I25kWmsCm8GSdNCu0xfbNcHYBRqXMcB3/04r8mIqO+5EypuAi+tdmNCs6ApFdY2xqDdyMnTHN71NxXGKSjoZMea4yZQ+iie+xxxfUCuea890EaLVT+Ka94wqR1LX42bf7SA6pdFaXtc2QWCB6z3Q/tu5Rc9D0qSw8VHk5r3tCXaXBiiqGY7211ZPBIyfcgZ59wnfQAjAma56275AjlrjoeiAL0eG3K8KXuR/IPkBfvND/A9N9/Z4hW+dB3nc/zeVy5e0yJg1iQqQSl82Osz3RkhZ0GxxyVcu7/IHU79gIk3OjnPduSekIl47e5iuDr2xgitbms46uVYrAbKLSJ6XE7kDY1e/6NrUd82GyxwLeZgyT0xqBsofjic105vu6JWQFcjtROACBtsJ/lOqQTBrcVLwWGouLmw9eI3QgpQ4WF2EgrAcvncNPkhEWY8= joagnitti@Jos-MacBook-Pro.lan

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by rmtolmach** [comment]
Key updated. Please give it 10 minutes to propagate. Sorry we missed this, the labels we used to identify open requests weren't on this issue :/
