### ISSUE TITLE
Design Intent - Design Feedback - Unified Pre-Check-in/Check-in Experience

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#53807]
## VFS acceptance criteria
- [x] Let Platform know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [x] VFS team closes the ticket

## Thoughts/questions
- Love the user flows!
- Be careful using too many alerts. You could explore using a [new card style/button](https://www.sketch.com/s/be292806-8dbf-4201-bfa7-0edbba103347/p/8E62D47D-F38C-4727-8E27-B5DF3424F12F/canvas)
- Matt: I do have some slight alterations to the notifications, be careful using alerts, info alert could be a success after you check in, explore other designs for hierarchy. If you want to design and test something around featured content please do so. [See notifications exploration](https://www.sketch.com/s/be292806-8dbf-4201-bfa7-0edbba103347/p/B323B60B-8BD0-4B92-9022-738A65FD36FB/canvas).
- I am attaching some screen shots of a similar "pre-check in" process. Just something to consider.
- <img width="626" alt="Screen Shot 2023-02-16 at 9 37 38 AM" src="https://user-images.githubusercontent.com/72398073/219471845-a6da6a44-45fb-495a-b5c0-c74b6f1c7c84.png">
- <img width="522" alt="Screen Shot 2023-02-16 at 9 39 20 AM" src="https://user-images.githubusercontent.com/72398073/219471939-c36f526c-e7d2-44a2-8c03-382bebb52e02.png">
- <img width="425" alt="Screen Shot 2023-02-16 at 9 39 32 AM" src="https://user-images.githubusercontent.com/72398073/219471911-e2ea6232-8606-4345-aeae-599daa8f8162.png">
- After updating and confirming contacts etc I got this screen...
- <img width="930" alt="Screen Shot 2023-02-16 at 9 44 52 AM" src="https://user-images.githubusercontent.com/72398073/219472378-12bebb9a-a462-42d2-99d4-7165c14e6725.png">

## Feedback
- Practice areas will document their feedback following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback).

**Must:**

**Should:**

**Consider:**

## Platform directions
- Remove the governance-team label
- Update "Issue Title"
- Link to collab cycle Request epic
- Add your feedback
- Remove the CC-Request label (only if you created the ticket using the New Issue link from the Collaboration Cycle Reviews board)
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review QA Only**: VFS PM, yourself (optional)

**Comment by benbrasso-agile6** [comment]
Thank you! We, @cgednalske, are exploring these options. Thanks for the links.
