### ISSUE TITLE
Route based prod rollout

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#53808]
## Description

Currently BRD serves latent traffic to a second ASG. See [Regular ASG config](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/templates/nginx_api_server.conf.j2) and [Latent ASG config](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/templates/nginx_new_api_server.conf.j2).

In an effort to have a more fine grained, route based rollout and send only specific routes to EKS (instead of configuring ALL routes via weighted pattern), we could have ONLY the second/latent ASG direct it's traffic to EKS. (e.g. EVSS, BGS and a few mobile routes) This would give us the ability to send (a handful?) of routes as an initial rollout step to EKS. See `nginx_config_secondary_split_api_url` [in the config here](https://github.com/department-of-veterans-affairs/devops/blob/b8b74b165dbc952fdb1b779b0888cebc96d743d7/ansible/deployment/config/revproxy-vagov/templates/nginx_api_server.conf.j2) - These routes currently go to the second ASG

### Second ASG routes:
1. [BGS/EVSS](https://github.com/department-of-veterans-affairs/devops/blob/b8b74b165dbc952fdb1b779b0888cebc96d743d7/ansible/deployment/config/revproxy-vagov/templates/nginx_api_server.conf.j2#L116-L120)
2. [Mobile v0/ and v1/](https://github.com/department-of-veterans-affairs/devops/blob/b8b74b165dbc952fdb1b779b0888cebc96d743d7/ansible/deployment/config/revproxy-vagov/templates/nginx_api_server.conf.j2#L188-L208)
Note: We can most likely point these [to the EKS url ](https://github.com/department-of-veterans-affairs/devops/blob/806d616c65ab2a8d435b9bfc733916723138afbb/ansible/deployment/config/revproxy-vagov/vars/nginx_config_vagov-prod.yml#L29)and/or split the traffic between ASG 2 and EKS

## Thoughts/Questions:
1. We can possibly edit the nginx config further to send additional routes to EKS

**Comment by laineymajor** [comment]
@BillChapmanUSDS , @LindseySaari spun up this ticket for us to start doing some additional research and brainstorming. Feel free to add thoughts and questions in the comments of this ticket :)

**Comment by laineymajor** [comment]
We need to identify a team we can test this with (a module team)
