### ISSUE TITLE
Content support on organic test flow for Login.gov adoption

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#53804]
## Issue Description
Carl is working on content for a small test (n=500) of a Login.gov adoption flow.

Timing is early March.

---
## Tasks
- [ ] Review content and provide feedback (Aliyah/Laura)

## Acceptance Criteria
- [ ] Content provided to Carl

**Comment by laurwill** [comment]
Hi @CarlDickerson ,
Here's a shell of a ticket for the test content you mentioned today — could you add any screens or resources here? Thanks!

**Comment by CarlDickerson** [comment]
@aliyahblackmore @laurwill Here is a link to the screens in Figma: 

https://www.figma.com/file/8vobVoSl1UqLnXsni3rcvO/Login.gov-Migration%3A-Grandfathering-IAL1-Flow?node-id=154%3A1300&t=CM3Q1iDV4SG2m50M-1

https://www.figma.com/file/8vobVoSl1UqLnXsni3rcvO/Login.gov-Migration%3A-Grandfathering-IAL1-Flow?node-id=154%3A1310&t=CM3Q1iDV4SG2m50M-1

https://www.figma.com/file/8vobVoSl1UqLnXsni3rcvO/Login.gov-Migration%3A-Grandfathering-IAL1-Flow?node-id=154%3A1296&t=CM3Q1iDV4SG2m50M-1

**Comment by laurwill** [comment]
Hi @CarlDickerson ,
Thanks for the chance to review these! I'm attaching a doc here with some initial thoughts on the organic flow content. It's great that this flow can more closely align with key messaging about Login.gov as a single account for gov websites. 

I see a few changes we need to make to align with site style — want to take a look at the comments in the doc and see if you have questions? Then you could make updates and we could look at an updated version in our Thursday sync, if that works for you.

I'm also wondering if there's anything we can say to get at the concern I've heard in some research readouts and in the blog comments about feeling like the sign-in requirements are always changing. Could we stress even more that this should be the last account they'll ever need to create for VA (if that's accurate)?

[Organic adoption flow — content review notes](https://app.zenhub.com/files/133843125/b5d94c34-aa94-425d-a54f-47dd6c064aa9/download)

Also documenting here that we discussed not needing the redirect screen in this flow — but if you decide to include it, we'll want to adjust the content there to make it clear that leaving VA.gov to create a Login.gov account is the desired action.

**Comment by CarlDickerson** [comment]
@laurwill @aliyahblackmore I've made updates to the screen based on initial feedback from yourselves, as well as design intent. One suggestion that we had was, "swapping the current header language for a meaningful action verb such as "upgrade" that conveys the goal and benefit of this process in one fell swoop. I would say the same for the button text - "get" login.gov doesn't feel as good as "upgrade" to login.gov... I will workshop with the team, but I was curious of your take here. I know that we could potentially explore this upgrade language for the "grandfathering" modal as well...

[Organic Adoption Modal in Figma](https://www.figma.com/file/8vobVoSl1UqLnXsni3rcvO/Login.gov-Adoption%3A-Design-Flows?node-id=154%3A1300&t=aKrqAEG2YxOL6sSk-1)

**Comment by aliyahblackmore** [comment]
Hey @CarlDickerson - for the organic flow we think that it's fine to leave "Upgrade" in the header,  but we wouldn't suggest changing the button/link to "Upgrade." 

We would suggest leaving "create" in the link button, as that it the action/process the user would be going through (the next pages on the flow use "create") and we'd want the button/link text to reflect that action.

**Comment by RLHecht** [comment]
This work is complete. Closing ticket.
