### ISSUE TITLE
[Feature] Update the cancellation workflow in VAOS app

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#53818]
Define MVP for the cancellation workflow in VAOS 

The VAOS FE team will need to do research and analysis to see how we can improve the Veteran experience when cancelling an appointment in VAOS. We will have to coordinate with the VAMF team to discuss the technical workflow. 

--- 

Checklist should be the same as the Appointment Details Redesign Initiative. This work was combined with the details redesign work.

**Comment by outerpress** [comment]
[Mockups of the current cancelation flow](https://www.figma.com/file/d6enlZQ15NZEuJNVD64Npg/Cancelation%2FReschedule?type=design&node-id=0-1&mode=design).

**Comment by melissa-lefevre** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdnhDIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b968116c63bbdcd5a54dbd3b55d812204f13af99/Current%20design.png)

**Comment by outerpress** [comment]
Next steps: SME sync review and A11Y review from Angela

**Comment by melissa-lefevre** [comment]
Here is a link to the [prototype ](https://www.figma.com/proto/Z1n9eLuzwMgnn31b4w11Qw/Cancellation-redesign?page-id=1303%3A38&type=design&node-id=1501-3132&viewport=910%2C433%2C0.52&t=LhV8r3xoH735OXMe-1&scaling=min-zoom&starting-point-node-id=1501%3A3132&mode=design)with the recommended changes.

Here are the current recommended UI changes:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdEZLIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--63c346ee3f2760ad347fa9171b1c5c8f1be316d6/Recommended%20screens.png)

**Comment by melissa-lefevre** [comment]
To do: 

- [ ] Discuss these changes with SMEs at sync.
- [ ] Bring these changes to A11y office hours with Angela Fowler and discuss the accessibility of these designs.

**Comment by melissa-lefevre** [comment]
@Cieramaddox will test the recommended designs when she does research with the prototype.

**Comment by ldelacosta** [comment]
Feature toggled turned on 100% on 08/19/2024 at 100% along with the Appointment Details Redesign. Closing out the feature.
