### ISSUE TITLE
SOCKS access for Amir Nashat

### ISSUE THREAD

**Issue by amirinator** [department-of-veterans-affairs/va.gov-team#53820]
### Your Name

Amir Nashat

### Your Email

amir.nashat@agile6.com

### Your Role and Team

Backend Engineer

### Product Manager (PM) name and email

Heather Rienks Heather.Rienks@agile6.com

### Product Owner (PO) name and email

Denise Coveyduc Denise.Coveyduc@govcio.com

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDV4I/eWvFgcFhDtuT28kHaQ3bxVbOlFb3df0FDAE5DW8/8Dp17HwI2x3phEWRcB/5hk1k06omGx4hORrAMS66BKQXx7X0LCCbo7ywvT4DPhAE5dJlxZ31SHSXutNGpGQUf/bvoQr9Vec5/AuQ9zSH/PxwbTX91il2sP3+0YutDOoHttu2+ndeWB1uZjqIjz+AacJBHlheTyiBMPNJ5uk/Bp+pmNkFtRnv0AYb4FksubntuXcfa3nTTm6xtaJPSLs6VUYP4S/mJJcCRXlPXiCYMWzT4kvWVU9YU3iLycgsr+SboGim74Fi4m9HQmmE0utinqsPPb+tyHXbv1RnO+QrIv8unsmMyz0lRSYIQ4ynEtyBrA5PsPgTdr0upsUrtr20WW/7zPws7JhQbHpQZ2wsla+NWtba8p7zci02LW3K4yLCIUGP5SZZlvhPw8QpSRNcIqRPBpJxb+uqcjeD69SN6iuY8EDc0HA5RnjLV3blixxtYVCTbVcVvWJKhbD2N6S0= amirinator@MacBook-Pro

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by JQuaggles** [comment]
@pjholyoke Was this rolled back?
