### ISSUE TITLE
Adding David Bielecki to DSVA Slack

### ISSUE THREAD

**Issue by huggins-va** [department-of-veterans-affairs/va.gov-team#53822]
#Adding David Bielecki to DSVA Slack

Are you requesting to add an individual as a:
- Multi-channel

- What channel(s) do they need to be added to? 
- vaapi-platform
- team-honeybadgers-support

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.
David Bielecki, DevOps/SysAdmin, new hire Lighthouse support team Honeybadgers

Thank you!

**Comment by regenauer-va** [comment]
bielecki_david@bah.com
