### ISSUE TITLE
Scheduling page alert updates for Cerner patients

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#5383]
**User Story**
When a Veteran who is a patient at a Cerner facility is logged in on VA.gov and is on the Scheduling page (https://www.va.gov/health-care/schedule-view-va-appointments/), the alert box should explain to users that they will be directed to the appropriate page on My VA Health. 
_Note that once VAOS can consume the Cerner API (eta June 2020), this may change. Also note that Columbus/Cleveland patients will be using VistA scheduling rather than VAOS in April 2020_

**Acceptance Criteria**
- [ ] Alert box UX lets authenticated users know that they will be directed to Cerner but that they can also view historical records in MHV, and provides correct links to both scheduling pages. 
- [ ] TBD: new tab automatically opens with correct Cerner scheduling page without requiring additional log in by user
- [ ] Unauthenticated experience of the alert box is unchanged

**Comment by christine-dillman** [comment]
Not applicable to Identity/SSO.
