### ISSUE TITLE
Test Results page alert updates for non-Cerner patients

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#5385]
**User Story**
When a Veteran who is not a patient at a Cerner facility is logged in on VA.gov and is on the Labs and Test Results page (https://www.myhealth.va.gov/mhv-portal-web/labs-tests/), the alert box should explain to users that they will be directed to the appropriate page on MHV. [This is the status quo, but design pattern may need to change to reflect changes being made for Cerner patients]

**Acceptance Criteria**
- [ ] Alert box UX lets authenticated users know that they will be directed to MHV, and provides correct link to MHV labs and test results page
- [ ] TBD: New tab automatically opens with correct MHV labs and test results page without requiring additional log in by user (current behavior)
- [ ] Unauthenticated experience of the alert box is unchanged

**Comment by christine-dillman** [comment]
Not applicable to Identity/SSO.
