### ISSUE TITLE
[FE] Add appt instructions into appt list on pre check in confirmation page

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#53855]
There was a decision to include the appointment instructions on the appointment list on the pre check in confirmation page. https://staging.va.gov/health-care/appointment-pre-check-in/complete

It should look like this: 

![Screen Shot 2023-02-17 at 2.43.04 PM.png](https://images.zenhubusercontent.com/62264cddfdd7546d65710eff/4d8944cd-d0aa-4bed-80e5-84fdfccf9cff)

@ytsaoca we need to [get this branch fixed in abstract](https://share.goabstract.com/49e5e0ca-feac-4ccb-9a03-0e05eeb05d75)

**Comment by brianseek** [comment]
@benbrasso-agile6 this just got merge and should be ready to validate on stage soon.

**Comment by benbrasso-agile6** [comment]
What's that difference I saw with the phone appt instructions that I saw John post? One version was longer than the other. 

> Your prover will call you. 

> Your provider will call you at your appointment time, etc.

Was that what's in the code?

**Comment by brianseek** [comment]
Yeah that is a good question. This is how it works currently. You get the short message on the intro page and the longer message on the complete page for phone appointment. In-person appointments only shows the message on the complete page. (this is a good example of all the little rules each page has that I was talking about in retro)

**Comment by benbrasso-agile6** [comment]
So, for the pre-check-in intro page, we do NOT want that alert. (Which basically removes that version of the text.)

**Comment by brianseek** [comment]
@benbrasso-agile6 So you are saying to change the phone rule and remove the alert on intro page?

**Comment by benbrasso-agile6** [comment]
@brianseek yes, remove phone alert from pre check in intro page.

**Comment by brianseek** [comment]
@benbrasso-agile6 sounds good, I'll ping back when it is ready to test.

**Comment by brianseek** [comment]
@benbrasso-agile6 this was just merged and should be ready to validate again on stage soon. Also see @acrollet's screenshots in the PR: https://github.com/department-of-veterans-affairs/vets-website/pull/23455

**Comment by benbrasso-agile6** [comment]
validated
