### ISSUE TITLE
[FE] Check width of check in now button in check in app

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#53858]
Talk to @zach-park about the primary button width for the check in now button in check in on the /details page. 

![Screen Shot 2023-02-17 at 3.00.59 PM.png](https://images.zenhubusercontent.com/62264cddfdd7546d65710eff/f9e66a3d-7b27-4c8d-8199-cb9c3ed64c9a)

Should it not be a larger width? [Here's the Abstract file.](https://share.goabstract.com/4ff1e88b-7dd0-4aac-812c-1276630ffa7f?collectionLayerId=d77f8f8e-f0fc-4907-8962-d40c0cc74dce&mode=design&sha=latest)

**Comment by loripusey** [comment]
The component will be fully justified in a mobile environment. In a larger environment it reduces to a smaller width because that is how the design system works.
@benbrasso-agile6 
Opinions?

**Comment by benbrasso-agile6** [comment]
I did not stretch when viewing on the smallest width in Chrome mac os. Let me retry.

**Comment by benbrasso-agile6** [comment]
Validated, closing
