### ISSUE TITLE
Test Results page alert updates for Cerner patients

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#5386]
**User Story**
When a Veteran who is a patient at a Cerner facility is logged in on VA.gov and is on the Labs and Test Results page (https://www.myhealth.va.gov/mhv-portal-web/labs-tests/), the alert box should explain to users that they will be directed to the appropriate page on My VA Health.

**Acceptance Criteria**
- [ ] Alert box UX lets authenticated users know that they will be directed to Cerner but that they can also view historical records in MHV, and provides correct links to both labs and test results pages. 
- [ ] TBD: New tab automatically opens with correct Cerner labs and test results page without requiring additional log in by user
- [ ] Unauthenticated experience of the alert box is unchanged

**Comment by christine-dillman** [comment]
Not applicable to Identity/SSO.
