### ISSUE TITLE
Align with DS Logon Sunset

### ISSUE THREAD

**Issue by APorter-Clarity** [department-of-veterans-affairs/va.gov-team#53875]
DSlogon sunset research level set with LGA team. What research is being planned? What has already been completed? What is in the works?

**Comment by APorter-Clarity** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/login.gov-adoption/research

**Comment by charlye-bluetiger** [comment]
This work was completed a few sprints back.   We've since kicked off a few work streams including IPP and organic adoption.

![Screenshot 2023-05-02 at 11.53.08 AM.png](https://images.zenhubusercontent.com/63ebde0fe77cb46dc5337872/f86dcbb7-85f2-40d9-ac52-6a3e97ddcee9)
