### ISSUE TITLE
Medical Records page alert updates for non-Cerner patients

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#5388]
**User Story**
When a Veteran who is not a patient at a Cerner facility is logged in on VA.gov and is on the Medical Records page (https://www.va.gov/health-care/get-medical-records/), the alert box should explain to users that they will be directed to the appropriate page on MHV.  [This is the status quo, but design pattern may need to change to reflect changes being made for Cerner patients]. Note that The alert box header (currently "Blue Button") may need to be changed, as Cerner medical records would not be the same as Blue Button

**Acceptance Criteria**
- [ ] Alert box UX lets authenticated users know that they will be directed to MHV, and provides correct link to MHV medical records page
- [ ] New tab automatically opens with correct MHV medical records page (current behavior)
- [ ] Unauthenticated experience of the alert box is unchanged

**Comment by christine-dillman** [comment]
Not applicable to Identity/SSO.
