### ISSUE TITLE
Evaluate error message content for pre check in when completion got hung up

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#53884]
## Description 

When attempting to complete pre-check-in, I received the loading indicator that something was happening. It took about 15 seconds. Then, I was brought to an error page that said, pre-check-in couldn't be completed. But, you can still complete pre-check-in up until XX (date). 

Chances are, something got timed out due to no connectivity. 

## Tasks

- [ ] Evaluate if that was a good message to show to Veterans in this scenario.  
- [ ] Create ticket with next steps, if needed

**Comment by loripusey** [comment]
Too old, closing
