### ISSUE TITLE
Use Revproxy to Route Traffic to Correct Frontend Resources

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#53892]
# Description
Given the research in this [ticket](https://app.zenhub.com/workspaces/platform-tech-team-4-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/55164), implement a design that creates a revproxy in each preview environment pod.

# Tasks
- [ ] Implement the design called out by the research ticket
- [ ] Test the routing through the revproxy to `vets-website` and `content-build` resources

# Acceptance Criteria

**Comment by JoeTice** [comment]
This seems unnecessary based on what we can do w/ Traefik
