### ISSUE TITLE
Medical Records page alert updates for Cerner patients

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#5389]
**User Story**
When a Veteran who is a patient at a Cerner facility is logged in on VA.gov and is on the Medical Records page (https://www.va.gov/health-care/get-medical-records/), the alert box should explain to users that they will be directed to the appropriate page on My VA Health. The alert box header (currently "Blue Button") may need to be changed, as Cerner medical records would not be the same as Blue Button.

**Acceptance Criteria**
- [ ] Alert box UX lets authenticated users know that they will be directed to Cerner but that they can also view historical records in MHV, and provides correct links to both medical records pages. 
- [ ] New tab automatically opens with correct Cerner medical records page without requiring additional log in by user
- [ ] Unauthenticated experience of the alert box is unchanged

**Comment by christine-dillman** [comment]
Not applicable to Identity/SSO.
