### ISSUE TITLE
Communicate va.gov-team repo consolidation strategy

### ISSUE THREAD

**Issue by minafarzad** [department-of-veterans-affairs/va.gov-team#539]
## User Story
As a team member building with or on VSP, I need to navigate VSP documentation easily so I can build things in a self-service and agile manner.

## Goal
Team members are easily able to navigate through the VSP documentation.

## Acceptance Criteria
- [x] An artifact that communicates the recommended IA for VSP documentation
- [x] An artifact that communicates how we consolidate (i.e. not "migrating" but rather copying)
- [x] Review this artifact and recommendations with DSVA
- [x] Communicate approach across VSP

**Comment by mnorthuis** [comment]
Draft approach document available here:  

https://docs.google.com/document/d/16VqaQI7B3-sL8hwhvx3oeV69ygKVRZhqs6FMO_n9R9M/edit?usp=sharing

Will refine after collaboration meetings this week and then begin communication. 
Posted draft doc in slack for visibility.

**Comment by mnorthuis** [comment]
Process, decisions, structure and build-out plan were communicated across multiple meetings and final preso was given at sprint demo.  
[repo-reorg.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/3531492/repo-reorg.pdf)
