### ISSUE TITLE
Add Supplemental Claims form to left nav

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#53909]
## Issue Description

When the Supplemental Claims form is launched to 100% of users, we need to add it to the left nav as a child of the Supplemental Claims page. 

IA doc to work from: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/bam-supplemental-claims-form.md

Link text should closely match H1 of form but should not include form number, i.e. "File a Supplemental Claim"

## Tasks
- [x] Add form to left nav

## Acceptance Criteria
- [x] Form appears in left nav of live site

**Comment by megzehn** [comment]
Thank you, @RLHecht, for talking through this with me! Confirming that I added "File a Supplemental Claim" in the left nav within Decision reviews and appeals page

**Comment by RLHecht** [comment]
This is live. Closing!
