### ISSUE TITLE
[Discovery] Static text updates across health pages on VA.gov

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#5391]
[Discovery/Analysis] Should the static text below the alert box on the Prescriptions, Messaging, Scheduling, Test Results, and Medical Records pages be updated to include information about Cerner as well as MHV?

**Comment by bridgethapner** [comment]
My next steps here per call with Lauren + Martha today: Audit the 5 pages in question on VA.gov for content that specifically applies to MHV and summarize for conversation with Samara + team on 2/6

**Comment by bridgethapner** [comment]
**Update here:** On a call with content folks 2/6, we decided to move forward with:

- De-branding the 5 Manage Benefit pages as much as possible
- Updating content on authenticated state of the 5 Manage Benefit pages only for Cerner users.

**Comment by bridgethapner** [comment]
Sharing a content audit of Manage Benefit pages done to identify MHV-specific & tool agnostic content.[https://app.zenhub.com/files/133843125/2b8e647b-d755-42c8-bcb1-101182ae640d/download](https://app.zenhub.com/files/133843125/2b8e647b-d755-42c8-bcb1-101182ae640d/download)

**Comment by peggygannon** [comment]
thank you @bridgethapner

**Comment by ambikaroos** [comment]
Closing in favor of ticket #5741, #5742, #5743, #5744, #5745 cc @bridgethapner @peggygannon
