### ISSUE TITLE
SOCKS access for Erin Flaherty

### ISSUE THREAD

**Issue by eflaherty** [department-of-veterans-affairs/va.gov-team#53923]
### Your Name

Erin Flaherty

### Your Email

erin.flaherty@adhocteam.us

### Your Role and Team

QA Engineer - CEDAR: Health Enrollment

### Product Manager (PM) name and email

Heather Justice heather.justice@adhocteam.us

### Product Owner (PO) name and email

Patrick Bateman - patrick.bateman@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC2z2XDtAfd3pDsivMtgJtnj7FXPwQbNUziWMl0YoUkd0SBgHuwoqeoDXib6mj+w1iWx8vXPMyg0/G92LZjfss0ISZSo+yie2fIaIBDoDCB51OfdYAQ7w+AW6LdGp9ILc3NhwlO+uHvjhiBKpYnNIKycRTO5WH+Fl5H8TaXEr0EPAyps2oQXWhl6HoR6wWPwT0MBP10tElQqujMeTMDV4hJfAz3h1B/wRFJQYwTCFrR36ohYDi9SvYHpgcYygmjevuOjfy5BNV/nLcbun8G4/N2rdxoxS2qY1UfeeR+GtoTCW/NWhi0C3S0o9GuCYY1yriS+KxT8xS05XRgXe32f5BwyNKdOqcMAJXYj3zODBf9sQ/h9NaBNNwO1YynKq5kXhOonMGKuaqj/dVkIVpGxW5JV2mP2hSwMTByfHf5uu0u1XTA9eo7dYSMllrI4R5vPUlQe0ksLZvjdUK3b95Xfx6sfnEiuak6phJVdA83UpCcBgXNUXdP77XdN2A8J3z0wEE= erinflaherty@Erins-MacBook-Pro.local

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by eflaherty** [comment]
I created new keys after upgrading the OS on my machine.
This request is to be added to developers group.
Please remove me from the "automation" group here as well if possible - https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/global/config.yml

**Comment by pjholyoke** [comment]
> I created new keys after upgrading the OS on my machine. This request is to be added to developers group. Please remove me from the "automation" group here as well if possible - https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/global/config.yml

Hey there @eflaherty, just to verify this is referring to AWS changes right? Are your SOCKS changes working?

**Comment by pjholyoke** [comment]
Just looking for an update on my previous questions @eflaherty 

cc: @little-oddball, @npeterson54

**Comment by eflaherty** [comment]
This isn't necessary any longer, closing.
