### ISSUE TITLE
Contact Center Review for Education Benefits Authenticated Transfer Application (22-1990e)

### ISSUE THREAD

**Issue by btruongafs** [department-of-veterans-affairs/va.gov-team#53929]
# Contact Center Review for Authenticated Transfer Application (22-1990e)

## Description
[Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/my-education-benefits/TOE%2022-1990e%20Updates/TOE%20Product%20Outline.md)

Staging URL: https://staging.va.gov/education/survivor-dependent-benefits/apply-for-transferred-benefits-form-22-1990e

### Launch Date
March 4, 2023

### Version Number
TBD

### Product Guide
NTT is creating training materials. Points of Contact: Denise Frazier, Angela Phalen, and Jeannie Daniel.

### Product Video
TBD

### Product Video Transcript
TBD

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
Hi @btruongafs. Do you have a product guide (manual) in Word format that VEO Tier 1 telephone agents can use when helping Veterans with this tool? Those are the guides I review.

**Comment by btruongafs** [comment]
@starlow00 NTT is creating training materials. Points of Contact: Denise Frazier, Angela Phalen, and Jeannie Daniel.

**Comment by starlow00** [comment]
Following up with NTT contacts re. status

**Comment by starlow00** [comment]
No news, will follow up again.

**Comment by starlow00** [comment]
No follow-up from the PM. Closing until updates are received.
