### ISSUE TITLE
Questions From Gary regarding Vets-API

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#53933]
We need to get an answer to these asap: 

- [ ] Are the VFS external service integrations up-to-date?
- [ ] Do we have an up-to-date list of connections that Platform leverages, for example, vets-API uses DGI, and Identify uses ID.me?
- [ ] What information is exchanged with any identified external connection?
- [ ] Do we have up-to-date IR procedures for these external connections, as well as POCs?
- [ ] Can the vets-API team help identify any external connections they use, if any, and what data do we exchange?

**Comment by npeterson54** [comment]
Adding into sprint as a new priority from Clint

**Comment by npeterson54** [comment]
@ericboehs have we answered all of these in other stories?

**Comment by ericboehs** [comment]
I believe so.
