### ISSUE TITLE
Fix broken link on Program of Comprehensive Assistance for Family Caregivers page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#53947]
## Issue Description

We have a broken link to the 10-10ez form on our [Program of Comprehensive Assistance for Family Caregivers](https://www.va.gov/family-member-benefits/comprehensive-assistance-for-family-caregivers/) page. 

The link should point to the 10-10ez find a form page instead.

## Tasks
- [x] Update link (Randi)
- [x] Copyedit (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [ ] Link working on live site

**Comment by RLHecht** [comment]
@megzehn I just opened this ticket while I was doing other work on this page. I changed the link mentioned above but I also changed the 10-10CG one since that was also going straight to the PDF and not the find a form page. These are ready to copyedit and publish when you get the chance.

**Comment by megzehn** [comment]
Thanks for updating these links, @RLHecht! I reviewed and published the page.

**Comment by RLHecht** [comment]
These are live. Closing ticket.
