### ISSUE TITLE
Edit Adding a new External Service Integration

### ISSUE THREAD

**Issue by laucon** [department-of-veterans-affairs/va.gov-team#53942]
### Tasks

- [x] Content updates as needed to this page: https://vfs.atlassian.net/wiki/spaces/pilot/pages/1884586162/Adding+a+new+External+Service+Integration

- [x] Reach out to Holden, Lindsay, and Oseas about Mike Chelen's request (Vicky). Slack thread started: https://dsva.slack.com/archives/CL181NRJQ/p1677087015025499

**Comment by laucon** [comment]
We're editing https://vfs.atlassian.net/wiki/spaces/PWD/pages/1884586162/Adding+a+new+External+Service+Integration

**Comment by vbellissimo** [comment]
Pending content updates made by Holden Hinkle on 2/22/23.
