### ISSUE TITLE
FAQs to include table of SSOe permutations

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#5395]
**User Story**
As a product owner, engineer, or other stakeholder working on identity issues, I want documentation on which permutations of SSOe will be supported so that I know what to expect

**Acceptance Criteria**
- [ ] Update FAQs with a table showing the combinations of user journeys to/from VA.gov, MHV, DS Logon, and Cerner, with documentation on how SSOe sessions will be supported in each combination

**Comment by patrickvinograd** [comment]
Updated FAQ here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/sso/SSOeRolloutFAQ.md
