### ISSUE TITLE
Buggy spokes on Education page

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#5396]
## What happened?
Clicking on `Get Benefits` on the [Post 9/11 Statement of Benefits page](https://www.va.gov/education/gi-bill/post-9-11/ch-33-benefit) reveals an empty accordion.  @jenniferlee-dsva  also identified the other spokes are also buggy - the Manage and More spokes are showing only one or a couple child items each, and should actually be showing the content in the images below. 
<img width="206" alt="Screen Shot 2020-01-31 at 12 14 17 PM" src="https://user-images.githubusercontent.com/55992116/73559552-46c3c280-4423-11ea-8e2f-86dc87eafbe4.png">
<img width="169" alt="Screen Shot 2020-01-31 at 12 14 11 PM" src="https://user-images.githubusercontent.com/55992116/73559553-46c3c280-4423-11ea-9bfe-8dd8a6019c29.png">

## Specs:
- Device: Macbook
- Browser: Chrome

## Steps to Reproduce
- URL: https://www.va.gov/education/gi-bill/post-9-11/ch-33-benefit
-  Click on the items in the left navigation

## Desired behavior
Parent elements should have correct number of children. (I personally am unsure of exactly what all the children should be)

## Acceptance Criteria
- [ ] Parents reveal all children

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by mattpointzxer0** [comment]
thank ya!

**Comment by MickinSahni** [comment]
Grooming:
- moving to backlog for Kelson/Nick to investigate before we determine whether Public Websites should make the change or if it should be the Drupal team
- if it's us, we'll estimate and fix

**Comment by ncksllvn** [comment]
I think I need more information here. My first instinct is that this is Drupal task - something is misconfigured about this page. From the dev side, the fix I see is to just hide the spokes that don't have any link to reveal.

**Comment by jenniferlee-dsva** [comment]
We can't hide spokes. The nav behavior is global, so we don't want to customize the way that the nav behaves per hub. 

And the edu benefit hub has links in each of the 3 spokes. The bug is what causing the links to not display. Here is the full list of links under the Manage and More resources spokes - image from original ^ ticket story: https://user-images.githubusercontent.com/55992116/73559552-46c3c280-4423-11ea-8e2f-86dc87eafbe4.png

**Comment by mattpointzxer0** [comment]
Thanks for chiming in before I could, @jenniferlee-dsva ; definitely agree. Hiding them, engineering challenges aside isn't acceptable. Thx for providing the screenshot. Let me know if there's anything we need from EDU in terms of review or guidance on what should or shouldn't be there.

**Comment by AkucherGCIO** [comment]
2020-28-02 Standup
Nick is currently working on this issue.

**Comment by ncksllvn** [comment]
I'm wondering if we should just remove the sidebar. It's kind of a confusing situation, because the Post 9/11 Statement of Benefits page is a React app, but the sidebars are configured in Drupal, so there's sort of a barrier there.

**Comment by AkucherGCIO** [comment]
03/02/20 PW Standup
@jenniferlee-dsva - Please let us know your thoughts on Nick's comment above.

**Comment by AkucherGCIO** [comment]
03/4/20 PW Standup
@jenniferlee-dsva - Please let us know your feedback on this issue.

**Comment by jenniferlee-dsva** [comment]
Replying to @ncksllvn 's [comment: ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/5396#issuecomment-592613081)

1/That's weird. (Ha!)
2/  Tool landing pages that do not have left nav are "root" level tools -- e.g., tools that span multiple benefit categories like `Check your VA claim or appeal status`. 
3/This Edu tool page is more like the [View your lab and test results online](https://www.va.gov/health-care/view-test-and-lab-results/) tool landing page: it's specific to one benefit hub. 

@AkucherGCIO @ncksllvn : Could you check with Matt Self why this page was built as a REACT page or why it might have needed that when it was built? 

If those reasons are no longer relevant -- I recommend that we migrate the static content on this page into Drupal and add the tool REACT as a widget, like we have for other benefit-specific tool landing pages. 

If we do the ^, we'll need Randi's magical Drupal help to do the manual migration and to add this to the IA, so the page appears with the correct left nav.

The screenshot in the original ticket info shows where this tool used to appear in the left nav, for Randi's reference.

**Comment by ncksllvn** [comment]
> why this page was built as a REACT page or why it might have needed that when it was built?

I think it was built this way because the application's development predates the concept of "widgets" we use now. 

I think your suggestion of converting this page into a regular tool landing page is the best way! The page would be configured and written in Drupal with two React widgets -

1. The Post-9/11 GI Bill Benefits tool status banner
1. CTA widget

The React widgets could just be chunked out of the rest of the application code. This is more work than I think we originally intended with this issue. Should we write a new issue for this, and should it go to Public Websites?

**Comment by ncksllvn** [comment]
Based on this thread, the right fix for this I think is beyond what this issue intended. The best fix seems to be converting this page into a Drupal page/widget pattern like other tool pages. I think we could break this down into -

1. [Content] In Drupal, create a page at `/education/gi-bill/post-9-11/ch-33-benefit` and configure the side nav
1. [FE] Create a Post 9/11 GI Bill tool-status widget
1. [FE] Create a Post 9/11 GI Bill CTA widget
1. [Content] Configure the Post 9/11 widgets in Drupal
1. [Launch] Publish `/education/gi-bill/post-9-11/ch-33-benefit`

It's more work than was expected but it moves the content of that page into Drupal and would fix the sidebar issues we're seeing now.

**Comment by AkucherGCIO** [comment]
@ncksllvn @jenniferlee-dsva - based on the discovery done for this issue and all of the extra work that came out of this ticket, do we want to keep this ticket for next spring or close it and add a new ticket for the extra effort.

**Comment by jenniferlee-dsva** [comment]
Agree with ^ - warrants new ticket/s.

**Comment by AkucherGCIO** [comment]
@ncksllvn @jenniferlee-dsva - Tickets created for this extra effort.

- [Content] In Drupal, create a page at /education/gi-bill/post-9-11/ch-33-benefit and configure the side nav - Ticket created - https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/6752

- [FE] Create a Post 9/11 GI Bill tool-status widget - Ticket created - https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/6753

- [FE] Create a Post 9/11 GI Bill CTA widget - Ticket created - https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/6754

- [Content] Configure the Post 9/11 widgets in Drupal - Ticket created - https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/6755

- [Launch] Publish /education/gi-bill/post-9-11/ch-33-benefit - Ticket created - https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/6756

**Comment by AkucherGCIO** [comment]
03/11/20 Sprint 17 Planning
@mattpointzxer0 - We will be fixing the issue in this ticket with the tickets mentioned above.  

Closing this ticket as other tickets will address the issue.

**Comment by mattpointzxer0** [comment]
thx so much @AkucherGCIO !
