### ISSUE TITLE
[FE] Update "Need help" section in pre-check-in and check-in

### ISSUE THREAD

**Issue by kellysmith1008** [department-of-veterans-affairs/va.gov-team#53979]
## What happened?
[Wireframe](https://share.goabstract.com/4ff1e88b-7dd0-4aac-812c-1276630ffa7f?collectionLayerId=d77f8f8e-f0fc-4907-8962-d40c0cc74dce&mode=design)

- This section title needs to be in sentence case: "Need help" 
![image.png](https://images.zenhubusercontent.com/63346ebd45ab78d62eea3201/e4cebbf3-f57b-4377-b287-815d79eca8b2)
- In Pre-check-in only, the TTY is missing from the last sentence and that sentence is missing a period.
![image.png](https://images.zenhubusercontent.com/63346ebd45ab78d62eea3201/80ea5292-98d9-4aa9-95f1-6592a59c9d22)

## Desired behavior
Please update the section title to sentence case in pre-check-in and check-in, and add TTY and the period in pre-check-in.

## Acceptance Criteria
- [ ] Updated "Need help" in pre-check-in
- [ ] Updated "Need help" in check-in
- [ ] Added TTY and period in last sentence in pre-check-in

**Comment by loripusey** [comment]
@acrollet @brianseek @wullaski Time permitting, can FE point this ticket before planning today?

**Comment by brianseek** [comment]
I put 2 points. @acrollet / @wullaski thoughts?

**Comment by acrollet** [comment]
2 points works for me.

**Comment by brianseek** [comment]
@kellysmith1008 This was just merges and should be ready to validate on stage soon.

**Comment by kellysmith1008** [comment]
Thank you!

**Comment by brianseek** [comment]
@kellysmith1008 did this all look good out on stage?

**Comment by kellysmith1008** [comment]
@brianseek My gosh, I'm so sorry! I thought I responded to this a few days ago, but apparently it slipped through the cracks. Yes, it looks great on stage. Thanks!

**Comment by brianseek** [comment]
@kellysmith1008 no problem! moving this to closed
