### ISSUE TITLE
Leadership intro on VAMC page

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#5397]
## What happened?
Leadership intro in CMS states it will show up at top of health care systems leadership page but is not displaying on Home page or top of Leadership page. 

![image (11).png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/19c4a9ed-95d5-4ef1-a562-8b87bd29b2b2)

![image (10).png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/b7ef5ae8-4a7b-4d3d-a57d-cf632e9535be)

## Specs:
- Device: 
- Browser:
- Test User _not applicable_

## Steps to Reproduce
- URL: https://www.va.gov/pittsburgh-health-care/leadership/
- Test User _(if applicable)_
- https://www.va.gov/pittsburgh-health-care -> about VA Pittsburgh -> About us -> Leadership
- Observe the leadership intro paragraph does not display

## Desired behavior
- Leadership intro content from CMS is expected to display at top of health care systems leadership page 

## Acceptance Criteria
- [ ] Leadership intro content from CMS displays at top of health care systems leadership page 

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by mmiddaugh** [comment]
@SgardnerPMP @davidconlon please add other detail as needed

**Comment by davidconlon** [comment]
@kevwalsh is there anything that CMS needs to do or is this completely front-end?
I want to say that you were talking about CMS owning next steps, but I'm a bit fuzzy today.
(Not enough coffee in the world today)

**Comment by SgardnerPMP** [comment]
Last I remember is that this is a known CMS code redirect.  The current
field does not publish. Not sure if it is a link issue from Front-end or if
it is a backend code issue?

Should put in CMS-Superteam/CMS ICEBOX.

[image: GovernmentCIO] <http://www.governmentcio.com/>

Stan Gardner | PMP, SSGB
Sr. Product Manager
| *mobile* (775) 772-1409
| *office* (775) 772-1409
| *e.* sgardner@governmentcio.com
*Government*CIO
website <https://www.governmentcio.com/> | media
<https://governmentciomedia.com/> | services
<https://www.governmentcio.com/services> | jobs
<https://careers-governmentcio.icims.com/> | map
<https://www.google.com/maps/place/101+Constitution+Ave+NW+%23100,+Washington,+DC+20001/@38.8927387,-77.0151008,17z/data=!3m1!4b1!4m5!3m4!1s0x89b7b787cdfdb85f:0x1e5a93a8a2b38b03!8m2!3d38.8927345!4d-77.0129121>
[image: Twitter] <https://twitter.com/GovernmentCIO> [image: Facebook]
<https://www.facebook.com/GovernmentCIOMedia> [image: LinkedIn]
<https://www.linkedin.com/company/governmentcio> [image: YouTube]
<https://www.youtube.com/user/GovernmentCIO/videos> [image: Instagram]
<https://www.instagram.com/gciotalent>
*Confidentiality Note: *This email may contain confidential and/or private
information.
If you received this email in error please delete and notify sender.

**Comment by kevwalsh** [comment]
As mentioned on the meeting today, we are working on this as part of the content listing refactoring work that's currently in progress. We'll have an update on Thursday March 5 at the latest.

**Comment by mmiddaugh** [comment]
This looks to be resolved. Closing this issue. 
![image](https://user-images.githubusercontent.com/55411834/82240604-ed12d580-98f7-11ea-88ff-825431f77c5b.png)
