### ISSUE TITLE
[FE] Update "Back to appointments" text

### ISSUE THREAD

**Issue by kellysmith1008** [department-of-veterans-affairs/va.gov-team#53973]
## What happened?
[Wireframe
](https://share.goabstract.com/4ff1e88b-7dd0-4aac-812c-1276630ffa7f?collectionLayerId=d77f8f8e-f0fc-4907-8962-d40c0cc74dce&mode=design)Text needs to be updated in staging from "Back to last screen" to "Back to appointments" for pre-check-in and check-in
![image.png](https://images.zenhubusercontent.com/63346ebd45ab78d62eea3201/313a9872-3974-4b2b-8ada-cb196a9548e9)

## Desired behavior
Please update the text to read "Back to appointments" in pre-check-in and check-in

## Acceptance Criteria
- [ ] Text updated in pre-check-in
- [ ] Text updated in check-in

**Comment by brianseek** [comment]
@kellysmith1008 This should get updated in abstract to be "Back to last screen". With the addition of the details link on the complete page, we no longer know what page a user is going back to. 

This ticket could get converted to a UX ticket to do that.

cc @loripusey

**Comment by loripusey** [comment]
Create this design debt [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54001)
closing
