### ISSUE TITLE
Add time zone to check-in and pre-check-in appointments

### ISSUE THREAD

**Issue by kellysmith1008** [department-of-veterans-affairs/va.gov-team#53971]
## What happened?
_When viewing check-in and pre-check-in appointment information in staging, the appointment time is missing the time zone_

## Specs:
- Device: MacBook Air
- Browser: Chrome
- Test User _Thirtytwo (04/07/1935) in clinic 500 on staging_:

## Desired behavior
_According to the wireframe and test rail requirements, the appointment date and time should include the time zone. This isn't currently displaying in staging.
[Wireframe](https://share.goabstract.com/4ff1e88b-7dd0-4aac-812c-1276630ffa7f?collectionLayerId=d77f8f8e-f0fc-4907-8962-d40c0cc74dce&mode=design)_

## Acceptance Criteria
- [ ] _Added time zone in pre-check-in appointment_
- [ ] _Added time zone in check-in appointment_

**Comment by brianseek** [comment]
@kellysmith1008 We should probably pull the TZ from the abstract. We have timezone tickets in the backlog and have been blocked on being able to display that for a while.

cc @loripusey

**Comment by loripusey** [comment]
Created a design debt [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54002)
closing
