### ISSUE TITLE
[FE] Add visual regression testing to happy path tests

### ISSUE THREAD

**Issue by wullaski** [department-of-veterans-affairs/va.gov-team#53980]
## Summary

Add visual regression testing to the existing cypress happy path tests. Implement in the same way that the screenshots are so that it can be run locally and optionally and not part of the automated github pipeline.

Result of this [spike ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/50989)

**Comment by loripusey** [comment]
too old, closing
