### ISSUE TITLE
[FE] Fix phone icon in pre-check-in and check-in appointment details link

### ISSUE THREAD

**Issue by kellysmith1008** [department-of-veterans-affairs/va.gov-team#53981]
## What happened?
[Wireframe](https://share.goabstract.com/4ff1e88b-7dd0-4aac-812c-1276630ffa7f?collectionLayerId=d77f8f8e-f0fc-4907-8962-d40c0cc74dce&mode=design)

- The phone icon is flipped in both pre-check-in and check-in

## Desired behavior
The phone icon is backwards in pre-check-in and check-in appointment detail information cards

## Acceptance Criteria
- [ ] Phone icon updated in pre-check-in
- [ ] Phone icon updated in check-in

**Comment by brianseek** [comment]
@kellysmith1008 This one can be closed, here is the thread https://dsva.slack.com/archives/C02G6AB3ZRS/p1676480349703849

I think @zach-park is going to update the abstract to reflect this

cc @loripusey

**Comment by loripusey** [comment]
I created a design debt [ticket ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/53999)for this
