### ISSUE TITLE
Load Testing with VFS

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#53983]
### **Problem statement** 
We need to gather additional information in order to have a complete load testing plan. 

### **Questions for VFS Teams:**
1. A number of [backend loadtest//.py testing scripts for Locust](https://github.com/department-of-veterans-affairs/vets-api-locust/tree/main/loadtest) might still be applicable for upcoming load testing.
**Which of those scripts are still good?**

2. A number of [frontend E2E testing scripts for Cypress](https://depo-platform-documentation.scrollhelp.site/developer-docs/end-to-end-testing-with-cypress) might be a fit for today's load testing.
**Which of them fit for load testing, if any?**

3. Are there any other scripts that you would like to see added?

4. For those scripts which VFS teams deem useful, we will convert those identified scripts into JMeter and visualize via the DataDog integration. 
**Any objections?**

### **Method of Communication**
- [ ] #endpoint-testing
- [ ] #eks-migration-support
*until COB 2.27

### **Definition of Done**
- [ ] Responses are documented from Q1
- [ ] Responses are documented from Q2
- [ ] Responses are documented from Q3

**Comment by considerable** [comment]
- This [DataDog's blog](https://www.datadoghq.com/blog/monitor-jmeter-test-results-datadog/) talks about their JMeter integration
- This [Sample dashboard](https://vagov.ddog-gov.com/dash/integration/276/jmeter-overview?from_ts=1676948400000&to_ts=1676951940000&live=false) is already up as the 1st step
- Attached screen shot pictures the sample metrics for /v0/search endpoint
![image.png](https://images.zenhubusercontent.com/616758e4c5e87dce2146cdcf/47df3ff7-a873-48eb-965f-7348ba22f8d3)

**Comment by laineymajor** [comment]
Complete
