### ISSUE TITLE
Create public repository for Sign in Service Example App

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#53987]
Deliverables of this ticket:

- An arbitrary Github user should be able to navigate to a public repository describing a Sign in Service Client Application
- We can leverage: https://github.com/18F/identity-oidc-sinatra for this work
- We shouldn't be able to push directly to master, and branches should be blocked by PR review

**Comment by rileyanderson** [comment]
- Repo: https://github.com/department-of-veterans-affairs/sign-in-service-client-sinatra
- Ticket requesting to make repo public https://github.com/department-of-veterans-affairs/github-user-requests/issues/14675
