### ISSUE TITLE
STEM-1995: Enable Form Wizard Updates in Production

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#5399]
As a developer, I need to remove the prod/feature flag so that the Wizard updates are available in the production environment.

## Assumptions:
1. The updates on staging have been reviewed and approved by the UX team as of 02/24/2020.
2. The updates on staging have been reviewed and approved by the EDU team as of [TBD].

## Acceptance Criteria
1. The work completed in story #5134 is available in the production environment.

## PR
https://github.com/department-of-veterans-affairs/vets-website/pull/11752

**Comment by elder-joseph** [comment]
PR Submitted for this story: https://github.com/department-of-veterans-affairs/vets-website/pull/11752

**Comment by delli-gatti-michael** [comment]
Updates are now in Production. Closing this issue
