### ISSUE TITLE
Add Sign in Service client config for example app

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#53995]
Deliverable of this ticket will be the addition of a client config for sign in service to interact with the example app.

This client config should be only set up for localhost environments, and should be a 'web based' sign in service setup.  

We'll have to figure out what the client_id should be, I'm not sure yet what we should call it

**Comment by mjconw3** [comment]
@bramleyjl...Mike and I have reviewed this ticket, added the appropriate label and sprint and have closed. Moving forward we will be adding acceptance criteria to all tickets to make review easier (not a problem for now while you all were managing your own tickets)
