### ISSUE TITLE
Create views for SiS Client example app

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#53991]
Deliverable of this ticket will be for embedded ruby views for the SiS client example app. These views are:

- When a user navigates to `localhost:<port>/`, they will see a simple single page app with a `Login/Sign Up` button
- When the user attempts to authenticate, they will redirect to a page that displays:
  - Credential attribute information returned from authentication
  - Current access token expiration
  - Current refresh token (session) expiration
- If authentication fails, a user should see a flash indicating the error
- When the user is at the successfully authenticated page, they should be able to select `Logout` and successfully log out

**Comment by aparsley** [comment]
Looks great, keep up the good work.
