### ISSUE TITLE
Yellow Ribbon MVP — VSP Accessibility Review of Final Mockup for Pre-usability testing

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#5402]
### Search Results page (desktop)
* **Headings** 
  * I would opt for moving the Displaying 1 - N of 59 Schools header to the far left, and having it "speak" for both columns. I think about that being your `<h2>` and maybe having a couple of `<h3>` like Filter Search Results and Schools or something like that. Probably not needed, but I'll defer to you all.
  * **Definition of done:** Visual designs have good heading relationships with the respective content. I'll defer to Liz and VSP design for the right implementation.
* **Form update and breadcrumbs**
  * This is a pretty cool UI handling, where the form is available on the app "landing" page and also the search results, with a new breadcrumb appended. Or is this meant to be the same page, just removes the instructional text and appends the cards to the right after the search returns?
  * **Definition of done:** This will be a judgment call in live code, the timing and behavior for updating the page, removing the instructional text. Jennifer or I will follow up during the staging review.
* **Add to Compare / Added button**
  * Semantically let's link this to the search result. We could use a block of screen reader only text to be more descriptive, or an aria-label.
  * Either option will give screen reader users a clear understanding of what action they'll be taking. I lean more toward the two span approach nowadays because [aria-label does not translate](https://adrianroselli.com/2019/11/aria-label-does-not-translate.html) using services like Google Translate.
  * **Definition of done:** One of the code patterns below is used in the Add to compare button HTML
```html
<button>
  <span aria-hidden="true">Add to compare</span>
  <span class="sr-only">Add Adler University to compare</span>
</button
```

```html
<button aria-label="Add Adler University to compare">Add to compare</button>
```
* **Focus management**
  * I'd like to add a keyboard focus only link in the source code after the Add to compare / Added buttons. This link would be an #anchor to the sticky footer and should only appear in markup if one or more schools have been added. The link would only be shown to users on keyboard focus. We tried out this pattern on another project I worked on, and it was well received in user testing.
  * **Definition of done:** Code approximately like the example below is added after each Add to compare button to "skip" to the toggle or footer of selected schools.
```html
<div class="add-to-container">
  <button>Add to compare</button>
  <a href="#toggle-container" class="skip-to-toggle">Skip to your selected schools</a>
</div>

...
<!-- Selected schools container -->
<div aria-live="polite" aria-atomic="false" id="toggle-container" tabindex="-1"></div>
```

```css
.add-to-container {
  position: relative;
}

.skip-to-toggle {
  position: absolute;
  right: -9999px; /* Move off-screen until focused */
  top: 15px; /* Guessing on the exact positioning */
}

.skip-to-toggle:focus {
  right: 0; /* Guessing on the exact positioning */
}
```

* **Sticky footer**
  * Let's make sure this sticky footer is in a div or container with an aria-live region, so additions or removals are announced to screen readers. The right balance of information to announce will need to be polished in live testing (ours or user testing).
  * **Definition of done:** aria-live region is added to the toggle container in live code:

```html
<!-- Selected schools container -->
<div aria-live="polite" aria-atomic="false" id="toggle-container" tabindex="-1"></div>
```

### Compare Selected Schools
*  The Remove recommendation sounds great! I'm not 100 on making this a button visually. You're right it's a button because we're modifying the UI, not navigating to a new view. I'll defer to you and the VSP designers for right visual. To me, as long as it announces as "Remove Chicago State University, button" to screen readers, I'm less concerned with the visual display.
* I'll defer to Liz and design for the right call here.

**Comment by andaleliz** [comment]
@kelsonic and @ncksllvn added you as assignees as Trevor's feedback is related to FE tasks.

**Comment by andaleliz** [comment]
@1Copenut thanks for creating this! 

@jenstrickland replying to your invision comment here, so the convo is captured w/ the ticket - just want to confirm that @1Copenut, you, and myself are all on the same page about replacing the red X with the word remove (text link appearance seems to be okay by all), and **with the focus going to the school count upon removal.**

and, actually, cc @kelsonic for the focus guidance that came out of their feedback, above. This is for the comparison table page.

**Comment by kelsonic** [comment]
>"Select/Deselect Chicago State University, button"

- Adding this `aria-label` property on the compare buttons for each search result.

- Adding `aria-live` to the sticky comparison banner.

- Adding conditional hidden `a` tag under each compare button for each search result ONLY when there are selected schools. This link directs to the comparison page.

>This is a pretty cool UI handling, where the form is available on the app "landing" page and also the search results, with a new breadcrumb appended. Or is this meant to be the same page, just removes the instructional text and appends the cards to the right after the search returns?

- Landing page + search results page are the same page, the content just changes depending on form submission and the presence of search results.

**Comment by jenstrickland** [comment]
For the "Remove" 'button' - I suggest that it be "X Remove" which might be coded something like this:

```html
<button>
  <span role="presentation">X</span> Remove
</button>
```
[HTML5 Accessibility: aria-hidden and role=”presentation”](http://john.foliot.ca/aria-hidden/)

This way there is more than color indicating interactivity for sighted users, and you don't need to use the underline styling used for links, and screen readers don't have to hear "X".

Otherwise "Remove" with the underline, as is done elsewhere on VA.gov for "Edit".

**Comment by AkucherGCIO** [comment]
Closing this ticket based on meeting with @andaleliz @AnneHurley @RLHecht
