### ISSUE TITLE
Sidekiq load testing

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#54026]
## Description

Lower environments don't run nearly quite as many jobs as the higher environments do. To verify that our HPA scaling is functioning as we expect, we should enqueue a number of jobs to test load and scaling. We may be able to pick out a job(s) and enqueue in batches via rails console. 

Note: Our load testing scripts may actually hit a number of endpoints that enqueue sidekiq jobs, so we should review this as well. 

TODO:

- [x]  Put plan in the LoadTesting Doc https://vfs.atlassian.net/wiki/spaces/TT1/pages/2492301335/Load+Testing+Plan
- [x] Create parent cron job chart https://github.com/department-of-veterans-affairs/vets-api/pull/11982
- [x] Create method in vets-api to call multiple jobs
- [x]  Run enqueued jobs in a cronjob
- [x] Put results in the LoadTesting Results

**Comment by RachalCassity** [comment]
[Staging PR testing](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/1504)

Removed Rollup increments

**Comment by laineymajor** [comment]
Does not need to be correlated with the other load testing.

**Comment by RachalCassity** [comment]
[ Sidekiqswarm concurrency PR](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/1555)

**Comment by RachalCassity** [comment]
Enqueued jobs should be tested in a cron job to prevent threads not being used.

https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/1556

**Comment by laineymajor** [comment]
note for lainey :) 
each pod has 16 threads (can do 16 jobs at a time)

remove sandbox BRD workers, then try this again (lindsey creating ticket)

**Comment by laineymajor** [comment]
Created cron job, trying to make it work in EKS... then will circle back to this

**Comment by RachalCassity** [comment]
Template example: https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/

**Comment by RachalCassity** [comment]
Cronjob configuration to run rails runner:

```
  # cronJob configuration
  cronJobs:
    sidekiq-hpa-test:
      schedule: "*/1 * * * *"
      command: ["bin/rails"]
      args: ["runner", "SidekiqHpaCronJobs.clean_up_queues"]
      imagePullPolicy: IfNotPresent
```

**Comment by RachalCassity** [comment]
Ready for testing staging! 

Plan on Monday to test HPA on sidekiq.

Update cron method to:

```
9999.times.each do |job|
  SidekiqHpaCronJobs.clean_up_queues
end
```

**Comment by RachalCassity** [comment]
staging/values.yaml config for testing. 

We want to overload staging worker

targetAverageValue: 50 --> Will autoscale up 1 pod per every 50 enqueued workers

```
autoscaling:
minReplicas: 2
maxReplicas: 64
targetAverageValue: 50 
```

**Comment by laineymajor** [comment]
this should be done today. rachal will close when complete

**Comment by RachalCassity** [comment]
Attaching results to load testing documentation
