### ISSUE TITLE
Make destination of `My Health` link in main nav conditional on toggle

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#54025]
## Story
"As the team responsible for incrementally rolling out the authenticated MHV on VA.gov landing page, I want to be able to toggle the `My Health` link in the authenticated top nav to point to `va.gov/my-health` for some increment of users, while all other users follow the existing path to the MHV portal."

## Useful links
- https://github.com/department-of-veterans-affairs/vets-website/pull/23265
- [Slack convo](https://dsva.slack.com/archives/C04KRGCASUA/p1675111684104859)

## Acceptance criteria
- [ ] Selected users are taken to `va.gov/my-health` when clicking on the `My Health` link in the authenticated main nav

**Comment by mdewey** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/23453
