### ISSUE TITLE
Content updates to static Appointments page (VAOS phased launch)

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#5404]
**Per 1/24 VAOS sync,** we're targeting late February for full VAOS launch. In the meantime, starting early Feb team will be employing a **phased approach** where a certain % of users will be routed to use the new tool vs. legacy tool after they sign in. 

We need to update the following on Appointments static page in time for this phased launch:

- [x]  Make intro copy generic (remove mention of MyHealtheVet portal, as some users will be routed to new tool). 
- [x]  Under "What types of medical appointments can I schedule online" Update list of the types of appointments **Waiting on more information before updating the type of care list.**
- [x]  Under "Can I use this tool to schedule non-VA appointments" Change answer to Yes, as the new tool and legacy tool allow users to make Community Care appointments. 
- [x]  Need to update button on the widget that shows after users log in. Add a button to take users to VAOS tool 
- [x]  Review the content that shows after users have logged in, to see if any tweaks need to be made to include new tool (the CTA copy has been dropped into dev ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/5058)

(screenshot here:)

![2020-01-24.png](https://images.zenhubusercontent.com/59b0414bb0222d5de476aa22/4c292d17-b96e-48bd-b19f-23a5c68f9a0f) 

Dev ticket for this work: https://github.com/department-of-veterans-affairs/va.gov-team/issues/5058

**Comment by peggygannon** [comment]
recommendations for updating the Types of Care list on static Appointments page:  

Option A lists the types of care.
Option B lists none
OPTION A
**What types of appointments can I schedule online?**
 It depends on the VA health facility where you’re receiving care. You can typically schedule an appointment online for the types of care that don’t require a referral. And you can schedule some types of appointments online only at certain locations.
Check with the health facility where you receive care about what types of appointments they accept online. [Find a VA health facility].
You may be able to schedule the following appointments online:
·       Amputation care
·       Audiology and speech (including hearing aid support)
·       Mental health
·       MOVE! weight management program
·       Nutrition and food
·       Ophthalmology
·       Optometry
·       Pharmacy
·        Podiatry (only available online for Community Care appointments)
·       Primary care
·       Sleep medicine
·       Social work


OPTION B
**What types of appointments can I schedule online?**
 It depends on the VA health facility where you’re receiving care. You can typically schedule an appointment online for the types of care that don’t require a referral.
Once you’re signed in to the appointments tool, you’ll be able to see what types of appointments you can schedule online at your registered health facility. (edited)

**Comment by markgreenburg** [comment]
CC @lalexanderson-dsva believe we're going with option 2 per chat in Slack yesterday. Also wondering if this and #2525 are duplicative in any way?

**Comment by peggygannon** [comment]
Hi, @markgreenburg @lalexanderson-dsva I renamed ticket 2525 to make it more clear that that ticket captures the consolidations of the CTA widgets. 

I'm making the update to the Appointment page today (option 2) and once that goes live, this ticket can be closed.

**Comment by peggygannon** [comment]
Closing. this change to "types of care" is live and validate.
