### ISSUE TITLE
Contact Center Review for govcio-vfep - Veteran ratings feature

### ISSUE THREAD

**Issue by gforbes4** [department-of-veterans-affairs/va.gov-team#54048]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
Product name: GI Bill Comparison Tool
Product description: The GI Bill Comparison Tool [link](https://www.va.gov/gi-bill-comparison-tool) is a web-based application that provides a way for veterans and their families to learn about VA education benefits programs and compare benefits by approved school, employer, or training provider. Information is offered for facilities throughout the United States, as well as for other countries.
Feature name (for the purposes of this submission): Veteran ratings.

### Launch Date
Estimated launch date for the Veteran ratings feature is 3/16/2023. It will be included in the GI Bill Comparison Tool production update.

### Version Number
1.0

### Product Guide
The GI Bill Comparison Tool User Guide is attached to this submission and is also available at the following SharePoint location on the VA network:
[link](https://dvagov.sharepoint.com/:f:/r/sites/VFEPCommunications/Shared%20Documents/General/Documentation?csf=1&web=1&e=X9UWVL)
Note: The current version of the GI Bill Comparison Tool User Guide does NOT describe the new Veteran ratings feature; that information will be added following the feature's appearance in the Comparison Tool production update on 3/16/2023. 

### Product Video
The Veteran ratings feature video is attached to this submission, and is also available at the following SharePoint location on the VA network: 
[link](https://dvagov.sharepoint.com/:f:/r/sites/VFEPCommunications/Shared%20Documents/General/Documentation/Ratings%20Feature?csf=1&web=1&e=J9KQbE)

### Product Video Transcript
Vdeo transcripts can be found in the following PDF, Word, and PowerPoint versions of the GI Bill Comparison Tool Ratings Feature document. These documents are attached to this submission, and all are available at the following SharePoint location on the VA network:
[link](https://dvagov.sharepoint.com/:f:/r/sites/VFEPCommunications/Shared%20Documents/General/Documentation/Ratings%20Feature?csf=1&web=1&e=J9KQbE)

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.
[GI Bill Comparison Tool Ratings Feature.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/10808357/GI.Bill.Comparison.Tool.Ratings.Feature.docx)
[GI Bill Comparison Tool Ratings Feature.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/10808359/GI.Bill.Comparison.Tool.Ratings.Feature.pdf)
[GI Bill Comparison Tool Ratings Feature.pptx](https://github.com/department-of-veterans-affairs/va.gov-team/files/10808360/GI.Bill.Comparison.Tool.Ratings.Feature.ppt
[GI Bill Comparison Tool User Guide.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/10808361/GI.Bill.Comparison.Tool.User.Guide.docx)
https://user-images.githubusercontent.com/40317506/220759983-50656782-9a49-4b1f-915d-f373101e7c60.mp4

**Comment by starlow00** [comment]
Hi @gforbes4. The guide looks good, and I have shared it with the VEO contact center for review. With the video, do you have a permission-free link (such as a YouTube link) that the Tier 1 phone representative can use to easily access the video while assisting Veterans?

**Comment by gforbes4** [comment]
Hi Steven,

VA has a Stream service. Will check to see if they have a YouTube channel as well.

Thanks!



From: Steven Tarlow ***@***.***>
Sent: Monday, February 27, 2023 3:31 PM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Forbes, Garry H. (governmentcio Llc) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Contact Center Review for govcio-vfep - Veteran ratings feature (Issue #54048)


Hi @gforbes4<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgforbes4&data=05%7C01%7C%7C2e39fdf681ac44b585b808db19019354%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C638131266783744522%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=q41nWsMSQA61W6b7NQg83ARk%2FiDlKn8k%2Fzri3WAPZYI%3D&reserved=0>. The guide looks good, and I have shared it with the VEO contact center for review. With the video, do you have a permission-free link (such as a YouTube link) that the Tier 1 phone representative can use to easily access the video while assisting Veterans?

-

**Comment by starlow00** [comment]
No changes from VEO. Attaching draft here[https://app.zenhub.com/files/133843125/138d3576-d623-4c17-b9fd-2d32e8b45244/download](https://app.zenhub.com/files/133843125/138d3576-d623-4c17-b9fd-2d32e8b45244/download).

**Comment by starlow00** [comment]
@gforbes4 , the public link appears to work. Thank you!

**Comment by gforbes4** [comment]
Great! Thanks, Steven!

//garry

From: Steven Tarlow ***@***.***>
Sent: Thursday, March 2, 2023 2:11 PM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Forbes, Garry H. (governmentcio Llc) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Contact Center Review for govcio-vfep - Veteran ratings feature (Issue #54048)


@gforbes4<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgforbes4&data=05%7C01%7C%7Cf8e402538a664457788b08db1b51e36e%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C638133810737318494%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YyHPrqFnAk%2Br6nFrrn5cdyxmCTJFFr7xLC6j0X1Jppw%3D&reserved=0> , the public link appears to work. Thank you!

-
