### ISSUE TITLE
Certificate scanning solution

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#54040]
## Description

The current [certificate scanning job lives in Jenkins](http://jenkins.vfs.va.gov/job/utility/job/cert-expiry-scanner/) along with the [current script](https://github.com/department-of-veterans-affairs/devops/blob/master/auditor/certs/expiry-scanner.rb). It appears that job is dependent upon certificates living in the devops repo. With the new EKS setup, certificates will live in the EKS manifest (via param store, configmaps, secrets, etc) and we need a new solution to check if certs are expiring. 

#### Possible solutions
1. **Ideal Solution**: Create a readiness script for the vets-api container/pod. The script will pull in certs and calculate days until the expiration date. If the date is within a certain amount of days (e.g. 60, 30, etc), the readiness script will post the expiration date as a log. We could then set a Datadog monitor to look for these specific logs, and if found, alert. 
2. A K8s job to scan certs
3. Microservice to scan certs 
4. Datadog Synthetic test to call a cert endpoint, request cert and verify the date

### Acceptance Criteria
- [ ] Validate that the output matches the output of the jenkins scanner. See this example in [#devops-deploys](https://dsva.slack.com/archives/C37M86Y8G/p1679932587201779)
- [ ] Update internal documentation: [Monitoring and tracking the expiration of SSL/TLS certificates](https://vfs.atlassian.net/wiki/spaces/OT/pages/2418507777/Monitoring+and+tracking+the+expiration+of+SSL+TLS+certificates) 
- [ ] announce change in #platform-cop-devops

**Comment by LindseySaari** [comment]
Ideally, we can combine [with this ticket](https://app.zenhub.com/workspaces/platform-tech-team-1-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/52433) and the script will 1) Determine if the correct scripts are there and 2) Perform cert scanning for expiration

**Comment by RachalCassity** [comment]
k8s cron job template:

`apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: <name>
spec:
  schedule: "*/5 * * * *" # every 5 minutes
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      parallelism: 1
      completions: 1
      backoffLimit: 1
      template:
        spec:
          serviceAccountName: vets-api
          containers:
            - name: <name>
              image: <image>
              command: ["/bin/sh"]
              args: ["-c", "bundle exec rails runner <Model.Method>"]
              env:
          restartPolicy: Never`

**Comment by considerable** [comment]
This a message to my future self how to convert expiration time string to epoc seconds in Linux:

```
nonroot@vets-api-web-64b9f7c988-s8dsj:~$ notAfter=$( \
  openssl x509 -noout -enddate -in /etc/ssl/certs/ca-certificates.crt \
  | cut -d = -f 2 \
  | awk '{ printf "%04d-%02d-%02d\n", \
  $4, (index("JanFebMarAprMayJunJulAugSepOctNovDec",$1)+2)/3, $2}')

nonroot@vets-api-web-64b9f7c988-s8dsj:~$ echo $notAfter
2030-12-31

nonroot@vets-api-web-64b9f7c988-s8dsj:~$ date -d $notAfter
Tue Dec 31 00:00:00 UTC 2030

nonroot@vets-api-web-64b9f7c988-s8dsj:~$ date -d $notAfter '+%s'
1924905600

```

**Comment by considerable** [comment]
And this is how to log how many days left before the SSL cert expiration, which is yet another solution for alert based on DataDog's log:

```
~$ EPOCnotAfter=$(date -d $notAfter '+%s')
~$ EPOCnow=$(date '+%s')
~$ daysLeft=$(echo "$EPOCnotAfter - $EPOCnow" | bc)
~$ logger -s "SSL daysLeft=$daysLeft"
<13>Feb 22 15:20:52 user: SSL daysLeft=247826631
```

**Comment by laineymajor** [comment]
Will copy and create a cron job. Not priority until headers are created (other ticket) @RachalCassity

**Comment by laineymajor** [comment]
Discuss 
- Discuss outside scanner that goes to devops distro email
- Discuss internal certificate scan

**Comment by rmtolmach** [comment]
Please ask the DevOps CoP about this. 
> it appears that job is dependent upon certificates living in the devops repo. With the new EKS setup, certificates will live in the EKS manifest

I could be wrong, but I think certificates are added to a certain directory in the devops repo specifically so the scanner can pick them up. The only reason we place them in that directory is for the scanner. Their real source of truth is AWS param store. As long as we continue adding certificates to the devops repo, the scanner will pick them up. (_But please confirm with devops CoP!_)

**Comment by laineymajor** [comment]
after current tickets are completed @RachalCassity will circle-back to this

**Comment by laineymajor** [comment]
after current tickets are completed @RachalCassity will circle-back to this

**Comment by RachalCassity** [comment]
I started a certificate scanner rake task in vets-api.

Question: Why are the certs in the srv/vets-api/secret directory? Can they be placed inside the app/config directory?

I just started this ticket but I am not sure how the task can loop through the files when the files are not in the app.

Solution 1: Mount certs inside the app
Solution 2: Make a sidecar container - still thinking about this one. Not sure if it's feasible.
Solution 3.: ???

**Comment by RachalCassity** [comment]
Asked devops COP in this [slack thread](https://dsva.slack.com/archives/C04CYC4LMU6/p1678475382598369)

**Comment by RachalCassity** [comment]
SSL certs have to be in the /etc/ folder.

Investigating on Monday :)

**Comment by laineymajor** [comment]
Checked in with the CoP Devops community.
@RachalCassity will update per convo with Oseas.

Was able to setup cron jobs.
Has a couple other solutions.

Might not be done this sprint.

**Comment by laineymajor** [comment]
This ticket potentially needs a step back... time for discovery.
Include discovery around code freezes and (possible?) weekend freezes for EKS.

**Comment by laineymajor** [comment]
Potential options:
1. Argo notify slack
- if we run cert scanner, can create a log entry -> run through DD and then post to slack
2. Vets-api container, mounting certs in the 2 diff directories to see expiry
3. Scan via param store

Rachal to do some research into the above options and report back...

**Comment by LindseySaari** [comment]
Still in progress. Discovery needed, but Rachal's first day back from vaca

**Comment by RachalCassity** [comment]
Thursday - Starting the discovery. Looks like there is already helm software for this. https://artifacthub.io/packages/helm/enix/x509-certificate-exporter

**Comment by laineymajor** [comment]
Thanks for updates!

**Comment by RachalCassity** [comment]
Was able to use the script by a little update. Instead of looking through files, loop through env variables to pull all certs and keys.

**Comment by laineymajor** [comment]
Will likely need to move to next sprint as we were overloaded this sprint with load testing, etc.

**Comment by RachalCassity** [comment]
![Screen Shot 2023-03-28 at 11.27.39 AM.png](https://images.zenhubusercontent.com/62e3f68264f21631c7db12fd/1d951165-be3b-4419-9ae2-c7b1897167c9)

@LindseySaari @laineymajor I was able to get a slack notification to my fake devops channel

**Comment by RachalCassity** [comment]
What needs to be done:

- [ ] PR reviewed
- [ ] PRs Merged
- [ ] devop-alerts api token

**Comment by laineymajor** [comment]
Should be complete today. See above. @RachalCassity don't close today... close tomorrow

**Comment by RachalCassity** [comment]
Adding the ArgoCD slackbot to devops-alerts is the only thing we need to do.

**Comment by RachalCassity** [comment]
Waiting for approval to create a va.gov slack user.

**Comment by laineymajor** [comment]
Reminder: This can wait until after prod rollout. I'm going to add it to the appropriate epic, but will leave it in this current sprint. If we have time to complete it, that's great... but it should wait until AFTER all tickets for the prod migration are complete.
