### ISSUE TITLE
Surface identifiers needed for health feature alert/routing in user profile

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/va.gov-team#5405]
In order to display conditional alert boxes/CTAs we need to know whether a user's data is in cerner in general, and/or if specific facilities at which that the user is a patient have been migrated to cerner. Per IAM team, that information will be surfaced in MVI correlated identifiers as follows:

> Patients whose records have been added to Cerner will have a 200CRNR correlation.  Additionally, as VistA sites are converted the VistA patient correlations will have a ^C added to the end (Example `123456^PI^station#OfVHASystem^USVHA^C`).

On the backend, we should parse these additional identifiers out of the MVI response (or equivalently out of the SSOe SAML assertion `gcids` attribute), and add them to the user profile model. They should be serialized in a way that makes them available to the frontend. 

Frontend does not likely need the actual CRNR identifier value, but rather a boolean flag that it is present. And then whether the facility IDs are presented with an additional tag that incidates they are Cerner-enabled or not, should be decided in whatever way is most useful to frontend code.

**Comment by ericbuckley** [comment]
@hinzed1127 is it the `/v0/user` endpoint that needs to be updated with this data?

**Comment by hinzed1127** [comment]
Yup! That endpoint should be available and requested on all of the pages where an alert might be. And should sync up well with how MVI info is already added on the backend, too.

**Comment by jbalboni** [comment]
Hey folks,

VAOS has a similar need for Cerner info for patients and facilities. In our use case, we'd want to have facilities listed out with a flag for Cerner migrated or not, in addition to a patient level flag based on the existence of `200CRNR` identifier. Something like this:

```
{
  isCernerPatient: true,
  registeredFacilities: [
    {
      facilityId: "983",
      isCerner: true,
    }
  ]
}
```

If that's something you'd be interested in considering, it would let us switch some VAOS code over to use the va.gov profile, instead of a separate MVI lookup through the upstream services we use (VAMF, in this case).

**Comment by jbalboni** [comment]
I'm going to rescind my previous comment. I don't think we'd want the list of facilities like that in the profile, because going foward, new Cerner patients won't have those facility specific ids. So a list like I'm suggesting will become less and less accurate over time.

**Comment by jbalboni** [comment]
Sorry for spamming this issue, but we got some further clarification that new Cerner patients will have VistA ids backfilled (though someday that process will stop). So that facility list would still be useful to us, especially in the short term before VAOS can talk to Cerner APIs.

**Comment by ericbuckley** [comment]
@jbalboni we can work on making that change as well.  To be clear, if the facility identifier ends in `^C` its a cerner registered facility?

**Comment by jbalboni** [comment]
This is what I'm going off of: https://dsva.slack.com/archives/GM5JJ5388/p1580335197031100

I believe the `^C` is a status flag at the end of the MVI identifier.

**Comment by ericbuckley** [comment]
@jbalboni that link doesn't work for me, was it in a private channel?

**Comment by hinzed1127** [comment]
@ericbuckley looks like Jeff added you. The quote in Patrick's original summary at the top is the main point from the linked thread.
