### ISSUE TITLE
Freshclam private mirror

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#54066]
## Description

It was noticed that the we currently [use a freshclam mirror to s3](https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/freshclam.conf#L5) for the freshclam signature db updates. [This job runs in Jenkins hourly](http://jenkins.vfs.va.gov/job/utility/job/clamav-updater/) to push freshclam signature updates to s3.

Having a private mirror was probably faster for build time and the clamav network is sometimes unstable (database.clamav.net). The freshclam s3 bucket upload isn’t only to update the signatures but to also replace the clamav database distribution network so that we are not relying on a somtimes slow or unreliable network connection. 

Clam/freshclam aren't part of the vets-api base image anymore and clamav is a separate sidecar container in the EKS deployment. It's currently using DNS to determine whether its databases are out-of-date (the default) but this should be revisited and as a best practice, we should most likely point to the private mirror.

This looks like the original PR that set up the private mirror to the s3 bucket: https://github.com/department-of-veterans-affairs/devops/commit/f9181b5358f1237ad34d75be4772fadead2f25cf

## Definition of Done
- [x] Update GHA to not push image unless build is successful - @LindseySaari  
- [x] Determine if we should use the clamav network/DNS to get signatures. Update: We are going to try this - @RachalCassity & @LindseySaari  
- [x]  If not, Point freshclam.conf to the private mirror in [our internal clamav repo](https://github.com/department-of-veterans-affairs/vsp-infra-clamav) - @RachalCassity 
- [x] Removed NotifyClamd - not needed because of self checks

**Comment by RachalCassity** [comment]
[Slack thread 1](https://oddball.slack.com/archives/C045LCF8WU8/p1677164847387189?thread_ts=1677115307.796099&cid=C045LCF8WU8)

**Comment by RachalCassity** [comment]
[Slack thread 2 ](https://oddball.slack.com/archives/C045LCF8WU8/p1677115307796099)

**Comment by RachalCassity** [comment]
https://github.com/Cisco-Talos/cvdupdate

**Comment by LindseySaari** [comment]
Created [this ticket](https://app.zenhub.com/workspaces/platform-tech-team-1-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/54141) to migrate the freshclam s3 private mirror Jenkins job to a k8s cronjob
