### ISSUE TITLE
Users can't get past facility selection when direct scheduling (CDW)

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#5406]
## Story
As a veteran who is trying to self-schedule an appointment online, I would like to be able to complete the self-scheduling flow so that I can make myself an appointment.

## Context
In order to enable Direct Scheduling, we need several pieces of information about any given veteran. Among that information are:
- The list of clinics associated with the particular facility and type of care combination they've selected
    - Ultimately gives us information about which clinics they've been to before (when cross-references with their appointment history)
- The PACT associations for a given veteran at a given facility

These calls average 24 second and 44 second response times in production, respectively. These services are mocked in the VAMF staging environment (and respond quickly) so we did not anticipate these high response times in production based on our staging tests.

The default response time for vets-api service dependencies is 15 seconds, so we ran into timeout issues with veterans during UAT sessions because:
- The 24 and 44 second average response times for these calls routinely exceeded the 15 second default timeout, resulting in the frontend receiving consistent `504: Gateway Timeout` errors
- `breakers` tripping after a high percentage of requests (due to low sample size given individual UAT sessions), which resulted in all subsequent retries within the next 5 minutes failing automatically

## AC
- [ ] Participants are able to complete the self-scheduling flow with high probability of success

**Comment by markgreenburg** [comment]
Note that there is likely a longer-term messaging issue we need to tackle. If responses take this long, we'll want to make it clear to veterans in the UI that things are happening and they should expect to have to wait up to a minute or so.

**Comment by lenaecb** [comment]
**Currently blocked by ECCB-960 (for ESECC) for in-scope firewall ruleset change ticket/confirmation**

**Comment by lenaecb** [comment]
@saneshark - let's use this as the tracking ticket for the time being relating to the CDW status. It captures what the issue is and why we need the changes that CDW is making. 

Status as of 3.4.20 -
- RFC-000534 has gone through ESECC approval and waiting for implementation from BPE Operations: the incident ticket filed for this work is INC9757549; for the CDW connectivity

- From Boris - "Just talked to BPE Ops, they just said they'll get to it when they can, staff is extremely light for training, which is all they can promise"

**Comment by lenaecb** [comment]
@saneshark - At this point, is this ticket closed?

**Comment by saneshark** [comment]
Yes. I think this can be closed.
