### ISSUE TITLE
Adding Janus Chung to DSVA Slack

### ISSUE THREAD

**Issue by huggins-va** [department-of-veterans-affairs/va.gov-team#54086]
Good afternoon,

Please add Janus Chung as a multi-channel user. 

Email: janus.chung@adhocteam.us

Channels: vaapi-platform & team-honeybadgers-support

Janus Chung is an additional AdHoc team member joining Lighthouse Honeybadger team. 

Thank you!

**Comment by LEHigley** [comment]
@huggins-va need the email address

**Comment by huggins-va** [comment]
janus.chung@adhocteam.us

Here you go! My oversight.  Still learning!

**Comment by LEHigley** [comment]
couldn't add to either of those channels but invited and added to victories
