### ISSUE TITLE
Appointment List Re-design - Voiceover isn’t reliably reading details links 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#54098]
## Description
Product and Design team are looking to update the appointment list to help the Veteran better understand the details for their appointment

---

## Acceptance Criteria
Background: the `va_online_scheduling_appointment_list` toggle is on

Problems found: 

- When tabbing through links, VoiceOver isn’t reading the details aria-label.

Example:

https://user-images.githubusercontent.com/2536801/221261803-d293af44-b288-4efb-b9e8-4a1b732ce7d5.mov

To recreate:
- Start VoiceOver
- Tab to any details link

Proposed solution: 

- [ ] When using VO and tab to navigate individual appts, VO announces the appointment information
- [ ] When [using VO+arrow keys to navigate the document](https://www.apple.com/voiceover/info/guide/_1131.html#:~:text=Escape-,Navigation%20commands,-Use%20these%20commands), VoiceOver announces the same information as when the user tabs to the details link.

### Design Assets
All spec copy is FPO. Use copy in copy doc.
[Screenreader spec](https://www.figma.com/file/JpGM8LGBCqAlL8qh3DmFk8/Home-Page-Redesign?node-id=1468%3A67095)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by outerpress** [comment]
@ldelacosta this ticket is good to go (the design spec is should be ready by early next week.)

**Comment by ldelacosta** [comment]
@outerpress @Cieramaddox - this ticket is ready to be validated in staging. Please let me know if you run into any issues. Thanks!

**Comment by outerpress** [comment]
@ldelacosta @vbahinwillit This worked great on Past and Upcoming appointments. For Pending it's still just announcing "Link: Details." I tried clearing my cache, lmk if there's anything else I should try on my side.

**Comment by ldelacosta** [comment]
@outerpress @Cieramaddox - ready to be tested in staging.

**Comment by outerpress** [comment]
@ldelacosta pending is announcing the aria label now, looks good!

**Comment by ldelacosta** [comment]
No new issues reported. Closing out the ticket.
