### ISSUE TITLE
Discovery: What documentation is where?

### ISSUE THREAD

**Issue by minafarzad** [department-of-veterans-affairs/va.gov-team#541]
## User Story
As a team member building on or with VSP, I need VSP documentation to be organized in an intuitive and protective way so I can access the most pertinent documentation.

## Goal
Our documentation is organized across our many repos in a way that considers our VSP needs (such as privacy for some documentation, publicity for others)

## Notes
We have documentation in several different repositories. Some of it is out of date, some of it is no longer applicable to us because of the scope of VSP work, and there is not much rhyme or reason to what is stored where right now.

We need to make a recommendation about where documentation should be stored across all of our repos. Some questions to ask and answer:
 -- What should be publicly accessible?
 -- What should be privately accessible? (make sure we connect with @wyattwalter and @ricetj on recs they've made around this)
 -- Where are all of the places that we are currently storing documentation?  i.e. how many repos do we even have? How many do we want to have?
-- Is there anything that can be obviously archived?

## Acceptance Criteria
- [x] An artifact that enumerates what documentation we have and where it is currently stored
- [x] Identify any major gaps in documentation
- [x] Review artifacts and discussion with DSVA

**Comment by mnorthuis** [comment]
Proposed high level structure was presented and discussed with Platform Support team and VSP/DSVA leadership.   Teams agreed that a single public repo and a single private repo is the preferred approach.  Document attached.  

[VSP Doc Structure.pptx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3433061/VSP.Doc.Structure.pptx)

Google doc showing the current repos
https://docs.google.com/spreadsheets/d/1waFEAra9aeXK4UFp-ODMbCcKC4MHDZCFel8Oahb2X1E/edit?usp=sharing
