### ISSUE TITLE
Appointment List Re-design - Make IDs unique 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#54105]
## Description
Product and Design team are looking to update the appointment list to help the Veteran better understand the details for their appointment

---

## Acceptance Criteria
Background: the `va_online_scheduling_appointment_list` toggle is on

Problem found: An axe DevTools scan shows some IDs that are using the same value. See the accessibility testing artifact [axe testing section](https://github.com/department-of-veterans-affairs/va.gov-team/issues/53481#:~:text=How%20did%20axe%20testing%20go%3F) for the scan results.

To recreate: [run the automated axe tests](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review#axe) on the upcoming, pending, and past lists.

Proposed solution: 
- [x] IDs should be unique 

### Design Assets
All spec copy is FPO. Use copy in copy doc.

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by outerpress** [comment]
This is good to go @ldelacosta

**Comment by ldelacosta** [comment]
@Cieramaddox @outerpress - this ticket is ready to be tested. Please validate and let us know if you run into issues. Thanks!

**Comment by outerpress** [comment]
Axe check comes back A+ 100% perfect, no issues found.

**Comment by ldelacosta** [comment]
No issues reported. Closing out the ticket.
