### ISSUE TITLE
Appointment List Re-design - Announce the correct number of appointments in the month

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#54103]
## Description
Product and Design team are looking to update the appointment list to help the Veteran better understand the details for their appointment

---

## Acceptance Criteria
Background: the `va_online_scheduling_appointment_list` toggle is on

Problem found: Currently, when using VO+arrow keys to navigate the list, the screenreader announces the number of appointments in a given month. It does not count the appointments that occur on the same day.

Example:

https://user-images.githubusercontent.com/2536801/221319317-2327a6ae-d560-4fc4-ac56-69a2eba28203.mov

Note @briandeconinck 's [recommendations in the midpoint review ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/48197)

Proposed solution:

- [ ] Voiceover announces the total number appointments in a given month when navigating via VO+arrow keys. 

### Design Assets
All spec copy is FPO. Use copy in copy doc.

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by outerpress** [comment]
@ldelacosta we'll need to talk to dev more, not sure if this needs a dev solution, design solution, or both

**Comment by outerpress** [comment]
@vbahinwillit I just tested it, and I think since all the information is there, we can leave it as is. We haven't had much luck getting screenreader users to test the list, so we should follow up with more testing and open a new ticket if we find issues with the empty group announcement. 

If you and @ldelacosta are okay with that, I think we can close this one.

**Comment by ldelacosta** [comment]
@outerpress @vbahinwillit - I'm OK with this approach. We can create tickets post-launch if we run into any issues. 

cc: @JRRoof @simiadebowale
