### ISSUE TITLE
Update system / facility rollup logic for nested systems

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#5410]
## Story
As a veteran, I want to select a system from a list of systems that most accurately aligns with where I'm located so that I feel like I have VA care options that are convenient and close to me.

## Context
A UAT participant was confused by his VA 'system' options because all systems were a 4+ hour drive away. However, one of the systems in the list actually was a parent of two other VA systems with their own child facilities. Those two systems were much closer to the veteran, but the veteran didn't know to select the parent that contained them because selecting something that's far away is inherently unintuitive.

In legacy VAOS, the VAOS system shows *all* facilities that have any child facilities as a 'system', whereas redesign VAOS only shows top-level facilities that have child facilities as 'systems.' In legacy VAOS, only end-node facilities are shown in the facilities list, whereas in redesign VAOS all non-root nodes are shown as facilities.

We may want to consider reverting our logic to match the legacy VAOS logic, but this is up for comment / debate.

## AC
- [ ] Root parents and any other facility that has linked child facilities displays in the systems list
- [ ] child facilities with no related child facilities of their own (i.e., end nodes) show in the facilities list after a system or subsystem is chosen.

**Comment by saneshark** [comment]
I'd have to see a visual representation to understand it better. I think this is more of a UX or business decision from what I can tell. Whatever is most practical to veterans I would think. Is there a reason why we're doing it differently?

**Comment by markgreenburg** [comment]
Per discussion with Ryan / Lauren, it's probably less confusing to do things the way legacy does them: bottom nodes in the facilities list, and all higher nodes (both root parents as well as mid-tier) in the systems list up top.
