### ISSUE TITLE
Eliminate direct calls of User.mvi 

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/va.gov-team#5411]
For context, see https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/request-for-change/2020-01-08-ssoe-removing-implicit-mvi-queries.md

In order to facilitate eliminating the implicit MVI query that happens on sign-in (in favor of those attributes) arriving in the SAML payload), we want to remove the invocations of User.mvi. Instead, such calls should go to User.va_profile, and then va_profile can conditionally delegate to the SSOe user_identity object (i.e. from the SAML assertion contents). 

Known invocations:
* `lib/evss/jwt.rb`. 
* `app/controllers/v0/profile/persons_controller.rb` - but this one is a cache-busting use case that probably needs to be handled with a direct MVI invocation and then selective updating of User.va_profile with profile-related attributes. - see #5412

**Comment by christine-dillman** [comment]
This work needs to be done after SSOe Inbound and Outbound are 100% deployed and stable.  Possibly Q1 2021 work.

**Comment by bramleyjl** [comment]
Updated context URL: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/request-for-comment/2020-01-08-ssoe-removing-implicit-mvi-queries.md
