### ISSUE TITLE
SOCKS access for [individual]

### ISSUE THREAD

**Issue by hgbarreto** [department-of-veterans-affairs/va.gov-team#54111]
### Your Name

Hector Barreto

### Your Email

hector.barreto@oddball.io

### Your Role and Team

DevOps Engineer Platform

### Product Manager (PM) name and email

Jesse House jesse.house@adhocteam.us

### Product Owner (PO) name and email

Mike Chelen michael.chelen@va.gov

### Access Type Requesting

platform

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDAgmeMe1bQ54MiFzFRwgJUS0FO5iH1yM6+NxeNIb+3oQXRCmUkNLUxsaGFOv5AG7yeXYqlqsZcBdXgvF86VBFzrZwyjl6KPmbJB4sInh/B+Ag+hWdQOnVg1xT884SAc4XSsYVou3lGXZR0CYUuMt34+K73PrLDxzn+n1OWx7lxFsgbwzSvKdzU8rJrt81XcUvf+ABZ9Xgnuieth0GFFHxu+zDQo1aO1o1KEm4m+Pw9DRYpeXMdunQ658B8D8BitlAfGkBKKLdq4uOye8Zla68KAiBamXs7cBvs44xKI3I9gFM8Re4ubGLGwjlb2DbwiL6ZbRYAX5+Bo/bSRXX3pGtQS+1TVuUq2o9B7TtmzblI83Np1aLtz5r9FKEznviYHD02dg0nnj4qlrjHRXjGhq039bQWbsqvpiKw406MbKPOKTBeOxG3D4ZELbnYMEiM/vP7xIgnOCRo5yH3MkkFl8+T6nn1w0VI+nkm5xG4BiS3eB3ebYBjIbJ3isXtaWQtlC8= gabyreload@LAPTOP-V9L25NJA

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [x] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by ph-One** [comment]
Hector is located in the Platform Roster, Tech Team 2
