### ISSUE TITLE
Missing HLR action links from Benefits decision reviews

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#54124]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more unauthenticated pages, online forms, apps, or tools on VA.gov
- [x] Making revisions to one or more existing VA.gov pages
- [ ] Something else 
 
While checking entry pages to the decision review forms, I noticed that an action link directing the Veteran to our Higher-Level Review form (https://www.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996) is missing on these 2 pages:

- https://www.va.gov/decision-reviews/fiduciary-claims/
- https://www.va.gov/decision-reviews/insurance-claims/

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [ ] Yes
  - [x] No - this is an already existing product available to 100% of Veterans
  
## When do you expect to launch your product to 100% of users?
  
N/A
  
## Supporting artifacts
*Please provide supporting artifacts as available.*

- Link to product outline: [HLR](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/decision-reviews/higher-level-review)
- Link to or attach user flows: [Flow](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/higher-level-review/HLR_flow.md)
- Link to prototype or mockups: [designs](https://www.sketch.com/s/96420652-15b7-45bb-80c5-5454dcd4b3c6)
- Link to any epics/issues that may be helpful: N/A

## Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [x] No

## When does this work need to be done?
- Estimated launch date: Completed
- Estimated staging review date: Completed
- Content and IA work needed by: ASAP?

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: Benefits decision reviews
-	OCTO-DE product owner: Matt Self
-	Product manager: Sade Ragsdale
-	Designer: Eileen Chi
-	FE engineer: Robin Garrison
-	Product/team Slack channel: #benefits-decision-reviews

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by RLHecht** [comment]
This work is complete. Closing.
