### ISSUE TITLE
Make user.va_profile conditionally delegate to mvi or user_identity

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/va.gov-team#5413]
See https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/request-for-change/2020-01-08-ssoe-removing-implicit-mvi-queries.md for context

In SSOe-integrated world most of the MVI-attributes will come through the SAML payload - what we typically map to a user_identity object. So there is no need to do a separate MVI lookup.

User.va_profile is used widely across the code base and can still be logically used to represent a user's VA-specific identity attributes. But, instead of delegating to mvi.profile, User.va_profile should delegate to the user_identity object IF that user_identity object came from SSOe. So when instantiating the user session we need to conditionally decide what va_profile should delegate to. We should support both cases to allow phased migration from v0 to v1 session controller.

Along the way it would probably be helpful to change all the internal references of `mvi.profile` (e.g. in the User.first_name, User.birth_date, etc) methods to use va_profile so they are similarly conditionalized.

I have not looked at specs to see how much impact this has but that's probably the bulk of the work.

**Comment by patrickvinograd** [comment]
In concert with this, should do whatever possible to mitigate data format differences between current `identity` object (aka ID.me SAML response) and SSOe SAML response. One known delta is that names (first/last/middle) need to be title-cased in a best-effort way.

**Comment by christine-dillman** [comment]
This work needs to be done after SSOe Inbound and Outbound are 100% deployed and stable.  Possibly Q1 2021 work.

**Comment by bramleyjl** [comment]
This issue is obsolete and is being replaced with an updated issue, #25230.
