### ISSUE TITLE
Access for [Hector Barreto]

### ISSUE THREAD

**Issue by hgbarreto** [department-of-veterans-affairs/va.gov-team#54144]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Hector Barreto

### Your Email

hector.barreto@oddball.io

### Team, Role, and Company of the target individual

Platform Tech Team 2, DevOps Engineer, Oddball

### Product Manager (PM) name and email

Jesse House jesse.house@adhocteam.us

### Product Owner (PO) name and email

Mike Chelen michael.chelen@va.gov

### Desired AWS Access

Platform DevOps engineer

### Access Expiration

ongoing

### User must exist in a roster before AWS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [x] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by little-oddball** [comment]
Platform team.

**Comment by BillChapmanUSDS** [comment]
I approve ongoing non-production access.  If production access is required it will need to be limited to 3 months while we are reviewing this process.

**Comment by considerable** [comment]
initial password provided via Keybase, closing the tkt.
