### ISSUE TITLE
Perform bulk data load of account table mappings into MVI

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/va.gov-team#5415]
See discussion/background in #5097 

We have agreement that it's feasible to add the ~1.5m mappings between ICN and ID.me UUID into MVI, the source of that data being the vets-api Accounts table that is written to upon login. 
Ideally the IAM team will do the actual loading of data, and can do so in a way that detects and discards data conflicts e.g. is robust to ICN changes, or if a UUID is discovered that matches with multiple MVI profiles. That will be a lot easier for them to accomplish than us. 

We need to supply this to the MVI prod operations team in whatever format is preferred by them, via secure means.

**Comment by ambikaroos** [comment]
- [ ] Need a readme of what this data is and a quick list of what conflicts there might be upon loading this data

**Comment by patrickvinograd** [comment]
README for data migration

### Background
VA.gov has recorded a mapping between ID.me UUID, ICN and EDIPI for authenticated users. Since VA.gov has previously not been integrated with SSOe, we expect that many of these mappings are not stored in MPI. We want to add the ID.me UUIDs as correlated identifiers so that subsequent authentications via SSOe can make those UUIDs to VA.gov. 

### Data Scale
There are approximately 1.5 million such mappings, accumulated by VA.gov since August 2018. 

### Data Provenance
The data is derived from a mapping table maintained in VA.gov’s Postgres database in AWS GovCloud. The table is populated after a user logs in to VA.gov with a LOA3 credential, any of ID.me, MHV, or DSLogon. For MHV and DSLogon credentials, VA.gov has an agreement where ID.me brokers those credentials, which is why an ID.me UUID is present for those credential types. 

Generally, a user authenticates and then VA.gov will use available traits to resolve the user in MPI, obtain their ICN, and then record the mapping between ID.me UUID and ICN (and EDIPI if available).  In the case of an MHV premium credential, the ICN is provided directly by the MHV federation. 

There are records in this table that contain a mapping between ID.me UUID and EDIPI, but for which no ICN is recorded. We propose to omit these from the data migration because the lack of an ICN may indicate that either the user is not in MPI or potentially that they authenticated with a non-LOA3 DSLogon credential. 

### Data Format
Data will be provided as a CSV containing the following columns:
`#idme_uuid,icn,edipi`
Strictly speaking the EDIPI may not be necessary but is provided in case it disambiguates any records.

### Possible Anomalies
1. *ICN outdated*
VA.gov’s mapping may not have updated when a user’s ICN is replaced, so the insertion process should be robust to looking up a historical/replaced ICN.

2. *ICN not found*
We do not expect this to happen - since all VA.gov mapped ICNs were successfully resolved in MPI, and MPI tracks historical ICNs, but in case it does these entries should be reported out as errors. 

3. *Different idme_uuid present for ICN*
It’s possible MPI already contains a different correlated idme_uuid for a given ICN. This could represent the user establishing two distinct ID.me wallets that eventually map to the same VA identity, e.g. possibly using a brokered MHV/DSLogon credential at some point after establishing an ID.me credential. 

In this case we believe the correct action is to add a second correlated 200_VIDM identifier to the person’s MPI record. Eventual consuming application code will need to be robust to the possibility of two ID.me identifiers in MPI. If this presents a conflict for any existing consuming applications of MPI data we’ll need to report it out as an error. 

In fact, even within the provided dataset, there are ~20,000 instances of two different ID.me UUIDs mapping to the same ICN, so if this situation is not already present in MPI it is present within this data.

4. *idme_uuid already correlated to a different ICN*
Aside from the historical ICN issue, if the same idme_uuid is already correlated to a different current ICN than the one in this dataset, then that entry should be flagged as an error and we will need to decide how to address this.  This is unexpected but could mean that MPI’s heuristic person search algorithm returned different results at different times. 

5. *EDIPI doesn’t match target record?*
The EDIPI column is provided but in most cases should be redundant. During the migration process we could consider checking the EDIPI - either making sure it also matches, or making sure that it does not pose a conflict with any other MPI records for a different person. But that might introduce unneeded complexity for little benefit relative to using just the ICN data. 

### Desired results
* Unambiguous idme_uuid to ICN mappings are added as correlated identifiers in MPI.
* Count of successful additions is reported.
* List of un-mappable entries is provided for further analysis, broken down by which of the above anomaly categories they fell in to.

**Comment by patrickvinograd** [comment]
Sent via email to additional members of IAM team.

**Comment by ambikaroos** [comment]
MVI team Danny Reed on format preference:

> Typically that is provided to me via skype in a format that is similar to the one provided below:
> ID|lastName|FirstName|MiddleName|DOB|SSN|…

**Comment by patrickvinograd** [comment]
File was transmitted to Danny Reed via Skype secure file transfer on 3/12/2020. He confirmed receipt, and I asked him to follow up via email when the ETL process was complete or if any issues arose.

**Comment by patrickvinograd** [comment]
Follow up conversation with Danny on 4/16. There were some anomalous entries - cases where an ID.me UUID was mapped to a different ICN in MVI than what VA.gov had recorded. This raised enough concern that IAM feels unable to proceed without having additional data (e.g. user traits) to correlate against. 

Since that needs to be coordinated between ID.me and IAM to do safely and securely, we're removing this as a launch requirement. Those teams can decide how/if they want to reconcile their data. 

It will increase the number of users who need to do a one-time re-authentication when they navigate to VA.gov via inbound SSO for the first time, but that has been deemed an acceptable UX compromise.
