### ISSUE TITLE
MHV on VA.gov: Landing Page MVP: Identify research questions for usability testing

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#54177]

**Comment by rbsingleton** [comment]
Research questions identified in [Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1677533989877/487a31eccb2d24e3ea72e448959900e795a213f2?sender=u1f2503bbfc7ec1e87fca8800)

Translated into [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/landing-page/research/2023-03-Landing-Page-User-Research/2023-03-research-plan.md)
