### ISSUE TITLE
Inbound SSOe users: instantiate VA.gov session

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/va.gov-team#5417]
**User story**
For the population of users who arrive on VA.gov from elsewhere with an active SSOe session, and who do have an ID.me UUID present, the frontend should detect whether they have an SSOe session, and if so, instantiate a VA.gov session. 

**Additional Information**

See #5097 for some of the limitations around this. 

VA.gov will be able to detect an SSOe session and will need to make a SAML request to SSOe to get the user's session contents. The initial SAML round trip should get the current session, and then we should parse that to determine if the user is capable of up-leveling or not. We may not get all the AAL/IAL/multifactor traits that we've asked for from ID.me in this scenario so we may have to adjust the upleveling logic and the user's account page somewhat to compensate. 

**UX Consideration**
- Do we want to automatically keep the user logged in (with some amount of hijacking the user's browser through a couple redirects) and with perhaps an alert letting them know why they are already logged in? Or do we want to give users a prompt that they can click login without needing to re-authenticate?

**Comment by ambikaroos** [comment]
Discussed UX question with @bridgethapner: will it be alarming to users who have initiated an SSOe session elsewhere (not on VA.gov), to open a new tab, navigate directly to VA.gov, and find that they are already logged in? Could the MHV team implement a notification to the sign in page from their end that lets users know that they will be logged in seamlessly to other SSOe-enabled sites

**Comment by ambikaroos** [comment]
We had a slack discussion (https://dsva.slack.com/archives/CHPA76VV5/p1580851147076100) and agreed that it might be better to create a contextual alert on VA.gov for this instance. @bridgethapner to discuss with VSP team about feasibility

**Comment by ambikaroos** [comment]
UX decision: no alert shown to users (unless they under an SSOe session for the first time, in which case they'll see the modal #5828)

**Comment by patrickvinograd** [comment]
Main issue I'm puzzling through at this point is that user_identity.rb has a validation check for `email` to be present. 

* For ID.me users, this attribute will be present.
* For MHV users, it looks potentially present in `va_eauth_commonname` but I'd like to validate that this is legitimately a user-supplied email address.
* For DSLogon users there is nothing that looks like an email address in the eauth payload.

We can relax that validation, but presumably it's there for a reason, and what downstream things will break because user.email is nil? 

There is also the ppiu_email address, and the VAProfile email address, but no telling whether those are guaranteed to be present.

**Comment by patrickvinograd** [comment]
Beyond the email thing, the other notable difference is that the AuthnContext is not going to be LOA-based or credential specific but something like `urn:oasis:names:tc:SAML:2.0:ac:classes:Password`, so any authnContext-based logic will get tripped up.

**Comment by ericbuckley** [comment]
I spoke with Nick Sullivan about this in regards to what, if any, impact this would have on vets-website.  Other than the navigation bar displaying the email address if the first name is missing, he thought the only potential issues would be within the vets-api when submitting a direct deposit form or processing a health care application.

- re nav bar; if both the email and first name are missing the UI just renders a generic person icon.
- re direct deposit; the ppiu controller and confirmed that if no email is present, the code will just issue a sentry message and proceed
- re health care application; it looks like the email used is from the form the user submits, and NOT the one registered on their profile
