### ISSUE TITLE
[Analytics Request] VEO Training and Metrics Improvement

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#542]
## User Story
As a va.gov platform analytics user, I need to clearly understand the va.gov metrics so I can use it accurately for storytelling.

## Goal
Train VEO users on Google Analytics metrics that we provide monthly and iterate on our metrics delivery based on our interactions.

## Acceptance Criteria
- [x] Train VEO stakeholders - Friday, July 12th
- [x] Provision GA to Paul Knepper and Maya Davis 
- [x] Record pain points and potential improvements
- [x] Iterate on data collection based on findings
- [x] Iterate on data design based on findings
- [x] Findings shared with team

## Definition of Done
- [ ] **Attached to a Milestone**
- [ ] **Attached to an Epic** 
- [ ] **Labeled with Team** 
- [ ] **Labeled with Practice Area**
- [ ] **Labeled with Type**

**Comment by nedierecel** [comment]
Updates:

- Access: Paul Knepper was provisioned with access on 7/15/2019
- Slide Deck: This was shared with Paul, Maya, and Jack on 7/16/2019

**Comment by joanneesteban** [comment]
Will open new ticket next sprint for automation.

**Comment by nedierecel** [comment]
Read-only access was provided to Maya Dennis on 7/18/2019
