### ISSUE TITLE
VEText | Update Message Editor Error Verbiage

### ISSUE THREAD

**Issue by chancetheoriginal** [department-of-veterans-affairs/va.gov-team#54207]
Managers are able to access the Admin/Message Templates/Edit Templates editor and input changes but are unable to save due to permission restrictions. 

Currently, VEText throws The following error: 

![Screen Shot 2023-02-27 at 9.41.58 AM.png](https://images.zenhubusercontent.com/61547adde730b5670c3cd747/37aa1d12-eb94-4cd7-a915-0bf2bba2bdb9) 

Suggesting to update the workflow to one of the following: 

- If role = Manager, Edit Templates button is disabled
- If above is not feasible, update error verbiage to direct the user to an Admin to make changes

In terms of UX, I'd feel the former would be the better option.

**Comment by chancetheoriginal** [comment]
Updated by @robertdurkin, Edit Template column disabled if role = Manager.

**Comment by lindsay-insco** [comment]
Complete
