### ISSUE TITLE
[SPIKE] Investigate broken Sentry alerts

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#54210]
Sentry alerts do not get triggered. Why is this?

**Comment by jacobworrell** [comment]
@kjduensing feel free to spend an hour looking into this. moving it into this sprint.

**Comment by kjduensing** [comment]
[Per this convo, Steve recommends attempting moving straight to Slack alerts.](https://dsva.slack.com/archives/CBU0KDSB1/p1677780195225479) I'm tempted to agree. Sounds like no one has any ideas on why email alerts are not working. @jacobworrell going straight to slack alerts leapfrogs a few interim tickets - are you good with moving forward with slack alerts?

**Comment by jacobworrell** [comment]
@kjduensing my intuition said I should just go ahead and get a channel set up for that, so we have it ready and available. Full steam ahead to Slack alerts.

**Comment by kjduensing** [comment]
🚂 Sounds good, thanks!
