### ISSUE TITLE
STEM: Post-test Content Reviews

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#5423]
Review updates with DEPO 
Review updates with VA Content

**Comment by amyknox** [comment]
But first...
- [ ] Update content per testing outcomes

**Comment by amyknox** [comment]
Content is drafted.  Will share with EDU for review after Checkpoint next week.

**Comment by ccruzgra** [comment]
Here is the prototype that we can use to for the content review:
https://bahdigital.invisionapp.com/share/3MIACRPUR5Y

Links to the individual pages:

Education Routing Wizard: https://bahdigital.invisionapp.com/share/3MIACRPUR5Y#/screens/296030603

1995 Form STEM Page (with all possible questions prefilled):
https://bahdigital.invisionapp.com/share/3MIACRPUR5Y#/screens/296030604

1995 STEM Page for Ineligible Users (with Yes/No clickable to see conditional content):
https://bahdigital.invisionapp.com/share/3MIACRPUR5Y#/screens/296030606

**Comment by ccruzgra** [comment]
Final prototype with content updates incorporated from DEPO's review: https://bahdigital.invisionapp.com/share/9GIACS4WX82

**Comment by ccruzgra** [comment]
@amyknox This story can be closed.
