### ISSUE TITLE
Staging:  Error Modal Window Displays On Home Page, Pending & Past Appt Page - No Error in Dev tools

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#54242]
Steps to recreate:  Issues happens with some users but not all users.  royal.tester@Id.me, grethel.g.petryniec@Id.me or mightykc70@gmail.com
1.  Log in to VAOS.  
2.  Results Expected:  Upcoming, Pending and Past queues display data as appropriate.  No error message displays to user.  
3.  Results Seen: Error message displays to user.  We’re sorry. We’ve run into a problem
We’re having trouble getting your upcoming appointments. Please try again later.

Looking at these two end points there were not any errors in Dev Tools. Using preview tab showed:  failures: []
https://staging-api.va.gov/vaos/v2/appointments?_include=facilities,clinics&start=2023[…]tatuses[]=arrived&statuses[]=fulfilled&statuses[]=cancelled
https://staging-api.va.gov/vaos/v2/appointments?_include=facilities,clinics&start=2022-10-30&end=2023-02-28&statuses[]=proposed&statuses[]=cancelled

 Mention the error is in line 188 in transformers.v2.js and paste the console error 
instrument.js:109 TypeError: Cannot read properties of undefined (reading 'text')
    at Y (transformers.v2.js:188:61)
    at G (transformers.v2.js:285:16)
    at transformers.v2.js:377:28
    at Array.map (<anonymous>)
    at Z (transformers.v2.js:377:16)
    at index.js:241:14
    at l (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at oe (transformers.v2.js:392:20)
    at i (transformers.v2.js:392:20)
[https://app.zenhub.com/files/133843125/c38cde44-ecbc-425b-9265-8e3889814184/download](https://app.zenhub.com/files/133843125/c38cde44-ecbc-425b-9265-8e3889814184/download)

[https://app.zenhub.com/files/133843125/e2125530-04bc-4b9a-b2f1-f4152dd6e375/download](https://app.zenhub.com/files/133843125/e2125530-04bc-4b9a-b2f1-f4152dd6e375/download)

1. Front end assumed that all requests will always have veteran comments. Right now this is correct because VAOS only gets Requests where Request Type = Veteran and all those requests have comments.
2. Backend pushed code in a VSP release that started sending all Requests to VAOS (not just type = Veteran) and those requests did not have veteran comments (because right now only Veteran type request have comments).
3. That VSP change broke Front End because Front End assumed all request have comments.
4. Backend is pushing a PR today to fix it so VAOS only gets Veteran Type request. This filtering will be done in MAS.
5. Regardless Front end will push a fix to that comments will not be required for requests.

**Comment by ryanshaw** [comment]
I am currently investigating this and noticed something in how we handle the comment field. I don’t remember if we decided there was to be a fixed order or not, but the FE code is checking currently for a position of an attribute.

Here’s an example comment field:
`preferred modality: clinic|phone number: 7039999993|email: apoldass@lts.com|preferred dates:12/30/2022 AM|reason code:ROUTINEVISIT|comments:Testing VAOSR-4892 on 11/3`

Our code is currently looking for the phone number in the third position, however it is in the second position.

I am trying to confirm that this is what is causing the error locally with some mocks, but am thinking we should be keying on the key values in that string (i.e. `preferred modality` or `phone_number` ) if the order can be variable.

**Comment by ldelacosta** [comment]
@marcynadeau - Based on the development's review, this ticket is considered an enhacement on the FE code. @ryanshaw is working on #5435. Once it is pushed to staging, I will let you know. If you have any questions, please reach out. Thanks!

**Comment by ryanshaw** [comment]
@marcynadeau I have an open PR that needs review from the team that I hope will resolve this issue.

**Comment by marcynadeau** [comment]
@ryanshaw @ldelacosta This has passed SQA testing.

**Comment by ldelacosta** [comment]
No issues reported. Closing out the ticket.
