### ISSUE TITLE
STEM: DEPO Content Review

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#5425]
Share prototype w DEPO for final content review
Discuss input
Update as necessary

**Comment by amyknox** [comment]
@peggygannon 

Booz team's completed usability testing on the Education routing wizard and VA Form 22-1995 / STEM Scholarship application.  We've syntheisized & incorporated our findings into the prototype and are ready for final content review.  

Key pages are:

Education Routing Wizard (STEM is preselected): https://bahdigital.invisionapp.com/share/3MIACRPUR5Y#/screens/296030603

1995 Form STEM Page (with all possible questions prefilled):
https://bahdigital.invisionapp.com/share/3MIACRPUR5Y#/screens/296030604

1995 STEM Page for Ineligible Users (with Yes/No clickable to see conditional content):
https://bahdigital.invisionapp.com/share/3MIACRPUR5Y#/screens/296030606


FULL PROTOTYPE
https://bahdigital.invisionapp.com/share/3MIACRPUR5Y

**Comment by peggygannon** [comment]
@amyknox I have just an edit on this screen: 

https://bahdigital.invisionapp.com/share/3MIACRPUR5Y#/screens/296030604


1. please add hyphen btw. high-demand
2. please lowercase Science, Technology, Engineering, Math in the parens: 

so it should be: 
. . . .high-demand STEM (science, technology, engineering, and math) fields.

**Comment by ccruzgra** [comment]
Final prototype with all DEPO content updates: https://bahdigital.invisionapp.com/share/9GIACS4WX82
