### ISSUE TITLE
ROOT Sitemap migration

### ISSUE THREAD

**Issue by kristinoletmuskat** [department-of-veterans-affairs/va.gov-team#54263]
For work tracking purposes, we had missed this map migration but did end up doing it. 

https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1672351995789/71a5b7ba07995735d458df39e07a696f48a9be48?sender=ua67f17f1c416a96ea04d2476

**Comment by RLHecht** [comment]
Closing this!
