### ISSUE TITLE
STEM: DEPO Design Reviews

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#5426]
Share prototype w DEPO for final design reviews
Discuss input
Update as necessary

**Comment by amyknox** [comment]
Include final 508 review as part of this story

**Comment by amyknox** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/design/working-with-platform-design-team.md#whentorequest

**Comment by ccruzgra** [comment]
Held a design review with DEPO and they checked off on our enhancements. 

@amyknox This story can now be closed.

**Comment by ccruzgra** [comment]
Adding in one more review with Trevor Pierce for 508 compliance.

**Comment by ccruzgra** [comment]
@amyknox
