### ISSUE TITLE
Mimic dev.va.gov deployment configuration

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#54307]
# Description
We want to explore the possibility of mimicking the deployments to dev or staging. The main reason for this is that we might be able to re-use the scripts used to deploy to those environments and not have to build a custom version of the static content and content build into our instances. This will save us time in building the content and space in the Dockerfile or local filesystem of the container.

## Some potential downsides to this scenario are --
1. It will be a cached version of content-build and it may not contain the changes to the content-build that some teams need to test / demo their changes
2. If a new CI workflow deploys content to the bucket that your PE is pointed to then your static content may change unexpectedly

## Potential steps for the scenario
1. Building Docker image from vets-website directory
2. Copy vets-website files into Docker image
3. yarn install in vets-website
4. yarn build in vets-website using appropriate flags to reference the assets already available in an S3 bucket from the dev/staging build workflow
5. Clone vagov-content
6. Clone vets-gov-json schema
7. Clone veteran-facing-services-tools
8. Expose the ports we need – 3000, 3001, 3002
9. When image is run --
   1. yarn watch in vets-website

## Results with preliminary experimentation

Unable to properly configure this scenario at this time. We need more information about how to reference the asset_source available in the dev/staging S3 bucket. I believe this is possible in the deploy script with a flag like --assetSource=<something here>.

# Acceptance Criteria
- [ ] We have researched the scenario of building a frontend image for a preview environment using deployment procedures that are borrowed from dev/staging

**Comment by pjhill** [comment]
This option will require the use of a revproxy. We are looking into how we might generate a Docker image that contains the revproxy. Our understanding of potential use of revproxy with regard to a preview environment is in our notes here -- https://vfs.atlassian.net/wiki/spaces/TT4/pages/2563407880/Revproxy+in+EKS

**Comment by pjhill** [comment]
This scenario seems to largely come down to the need to implement a revproxy in our preview environment pod that will forward traffic to the existing content-build cache location and forward traffic for apps through to our frontend. This is out of scope for the time being, but it may be worth pursuing post-MVP.

**Comment by JoeTice** [comment]
Note: This work informs work on the revproxy, captured in ticket [53892](https://app.zenhub.com/workspaces/platform-tech-team-4-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/53892)
