### ISSUE TITLE
Retrieve cached `content-build` when the container starts

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#54309]
# Description 
If we don’t build content-build for the image then we reduce the size of the image and the time it takes to creation the image

We can pull the cached content-build assets into the container once it is running with a script

We don’t get necessarily the latest content-build at the time the preview environment is triggered – instead it will be whatever the latest CI workflow was able to build and deploy to the content-build bucket for dev/staging/prod

# Steps
Rough outline of steps in the Dockerfile / Docker build step --
1. Clone `vagov-content`, `vets-json-schema`, `veteran-facing-services-tools`, and `content-build` into the Docker image into a subdirectory named `website`
2. Copy `vets-website` into the `website` subdirectory
3. Expose ports 3001 and 3002
4. Run the start up script

Rough steps in the start up script
1. Download a compressed and cached `content-build` from S3
2. Extract the cached build into build/localhost subdirectory
3. yarn install content-build
4. yarn serve content-build
5. yarn install vets-website
6. yarn watch vets-website

Fin

# Acceptance Criteria
- [ ] Users can navigate to the frontend of a VA.gov instance with both `vets-website` and `content-build` in a Docker container

**Comment by CBonade** [comment]
With a great deal of assistance from Peter, there's now a working version of this docker flow that gets va.gov up and running with all the content displaying. Our next step is to figure out if ArgoCD can work with this structure.

**Comment by CBonade** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/23537 PR here to merge this dockerfile and script into vets-website, awaiting approval. Will still need to be tested for devops viability.

**Comment by CBonade** [comment]
This testing has moved into the devops stage, however the script had some issues getting going in ArgoCD. Currently in troubleshooting.

**Comment by pjhill** [comment]
Given that the scope of this effort was to get a working frontend with both `vets-website` and `content-build` into a Docker file and pushed to ECR -- I think we can move this one to Review at this point. The additional work of configuring routes to the webserver(s) running on that image is almost entirely ArgoCD configuration and the scope is very different. We'll need to create another ticket to define the scope of that work.
