### ISSUE TITLE
OBE - YR: Internal Discovery Kickoff

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#5432]
Meet internally to review requirements document
Explore areas of uncertainty
Document questions for client & others

**Comment by amyknox** [comment]
Review of Ad Hoc Discovery & Testing

- Veterans aren't aware of Yellow Ribbon program
- Veterans don't get how Yellow Ribbon works
- Veterans are more likely to want to go to a school that's close to where they are than to try and optimize their $$$ / benefits

Topline Summary
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/yellow-ribbon-mvp/research/yellow-ribbon-mvp-topline-summary.md

**Comment by amyknox** [comment]
@desireeturner  - turns out there's no there there for Yellow Ribbon UX at this time. As a result, this story is OBE.
