### ISSUE TITLE
[FSR] Expanding Group

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#54354]
## Issue Description
Design tickets based on [#53953](https://github.com/department-of-veterans-affairs/va.gov-team/issues/53953). 
Platform is depreciating the Expanding Group React Component and **Step 5 of 7: Repayment or relief options: Debt forgiveness (waiver)** is impacted.

**Old design:**
Message and checkbox automatically appear after user selects waiver
![Screenshot 2023-02-28 at 3.47.35 PM.png](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/cc8eef1b-c9d5-4be9-948f-41af28183a47)

**Revised design:**
User selects waiver radio button and selects the continue button. 

![Screenshot 2023-02-28 at 4.02.07 PM.png](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/b640bb76-5510-4238-9a10-81c836fc37ce)
The text, "You selected:" along with the waiver information is repeated on the following page along with the required checkbox component.

![Screenshot 2023-03-08 at 9.57.42 AM.png](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/37769b41-16d0-47bc-b025-0e6337c91044)

**Comment by mgleo** [comment]
Meeting with Design & Accessibility Platform team on March 7, blocked for now. cc @denisecoveyduc @HeatherRienks

**Comment by denisecoveyduc** [comment]
Hey @mgleo Can you clarity why we are blocked? i.e. what are we waiting on and when do you/ the platform team think it will be available etc.

**Comment by mgleo** [comment]
@denisecoveyduc I'm attending Platform's Design Office Hours tomorrow at 3pm ET. I need to clarify that this solution is accessible. If it is approved, we can proceed but if it is not I'll need to make updates to the design.

**Comment by mgleo** [comment]
@denisecoveyduc Expanding Group tickets #53953 #54354 are now unblocked. This ticket has been updated with approved designs.
cc @amponce
