### ISSUE TITLE
EKS Rolling Update Tweaks

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#54353]
**Problem Statement**
_WHO_
_WHAT_
_WHAT FOR_
_WHERE_

**Issue Description**
_What details are necessary for understanding the specific work or request tracked by this issue?_
_Additional documentation and/or slack threads linked here_

---
**Tasks**
- [ ] _What work is necessary for this story to be completed?_

**Acceptance Criteria**
- [ ] _What will be created or happen as a result of this story?_

**Comment by RachalCassity** [comment]
[First PR](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/1535)

Results:
maxSurge: 2
maxUnavailabe: 1
Only one pod is dropped. This is independent of the desiredReplicas.

**Comment by RachalCassity** [comment]
When we run load tests we will have more knowledge and monitor rollout scalability in Datadog

**Comment by laineymajor** [comment]
@RachalCassity are your above comments also captured else where? I'm not 100% what this ticket was supposed to be, and am tempted to close it. Let me know your thoughts :)
