### ISSUE TITLE
Update separators in getAppointmentInfoFromComments function.

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#54357]
## Description
In the `getAppointmentInfoFromComments` function, we currently use the array index to split different values from the `reasonCode.text` field. To account for future changes to the order of these values, we want to use strings as the separator instead.

---

## Acceptance Criteria
- Regardless of order, values are correctly mapped from `reasonCode.text` field.

### Design Assets
All spec copy is FPO. Use copy in copy doc.

## Definition of Done
- [ ] All acceptance criteria are met

**Comment by ldelacosta** [comment]
SQA validated #54242 (no new issues reported). Closing out the ticket.
