### ISSUE TITLE
Qualitative Data Request

### ISSUE THREAD

**Issue by LeelahHolmes** [department-of-veterans-affairs/va.gov-team#54372]
### Data Type Requested

Support

### Date Range Start

03-06-2023

### Date Range End

04-01-2023

### Product Name(s)

Online Enrollment Verification, Application for Transferred Education Benefits, Download Education Letters

### Product Description

- **Online Enrollment Verification**: A tool on VA.gov that allows GI Bill students to verify and review their monthly enrollment information on the web, so that they can receive their monthly payments.
- **Application for Transferred Education Benefits:** The 22-1990e form on VA.gov that allows a Veteran's family member to apply to use transferred education benefits. In the updated version, much of the information is pre-populated and the applicant may receive an immediate decision.
- **Download Education Letters:** A tool on VA.gov that allows GI Bill applicants to download their education decision letters.

### Product URL(s) and/or term(s)

- **Everything under and including:** va.gov/education/verify-school-enrollment/
- **Everything under and including:** va.gov/education/survivor-dependent-benefits/apply-for-transferred-benefits-form-22-1990e/
- **Everything under and including:** va.gov/education/download-letters/

### File Delivery Format

One file, different tab for each term/URL

### VA Email Address(es)

miya.furukawa@va.gov, alexander.ferzola@va.gov, leelah.holmes@va.gov

### Add Assignee and Labels

If not already done so, please ensure @ianMcCullough-ob is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by ianMcCullough-ob** [comment]
Will be exporting SF data under these sub-categories:
Education Benefits Application
GI Bill Statement of Benefits

**Comment by ianMcCullough-ob** [comment]
@edpearson20 I created a report ahead of time in SF, just needs run on 4/2. I'll sync with you to make sure you have access to the reports.

**Comment by Kimberley2019** [comment]
This is now complete as of 4/3/2023.
