### ISSUE TITLE
Qualitative Data Request

### ISSUE THREAD

**Issue by LeelahHolmes** [department-of-veterans-affairs/va.gov-team#54373]
### Data Type Requested

Support

### Date Range Start

03-06-2023

### Date Range End

04-01-2023

### Product Name(s)

Online Enrollment Verification, Application for Transferred Education Benefits, Download Education Letters

### Product Description

- **Online Enrollment Verification**: A tool on VA.gov that allows GI Bill students to verify and review their monthly enrollment information on the web, so that they can receive their monthly payments.
- **Application for Transferred Education Benefits:** The 22-1990e form on VA.gov that allows a Veteran's family member to apply to use transferred education benefits. In the updated version, much of the information is pre-populated and the applicant may receive an immediate decision.
- **Download Education Letters:** A tool on VA.gov that allows GI Bill applicants to download their education decision letters.

### Product URL(s) and/or term(s)

- **Everything under and including:** va.gov/education/verify-school-enrollment/
- **Everything under and including:** va.gov/education/survivor-dependent-benefits/apply-for-transferred-benefits-form-22-1990e/
- **Everything under and including:** va.gov/education/download-letters/
- **Terms:** Verify, verifies, verified, enrollment, enrollments, monthly enrollment, school enrollment, transfer, transferred, sponsor, transfer of entitlement, transfer of benefits, transfer of education benefits, education decision letter, decision letter, COE, certificate of eligibility, 22-1990e

### File Delivery Format

One file, different tab for each term/URL

### VA Email Address(es)

miya.furukawa@va.gov, alexander.ferzola@va.gov, leelah.holmes@va.gov

### Add Assignee and Labels

If not already done so, please ensure @ianMcCullough-ob is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by ianMcCullough-ob** [comment]
@aubreyarcangel I created some pre-made filters within Medallia.

Here's a link to [Medallia live feed & search](https://va.voice.va.gov/sso/va/pages/1012)

Once you make it to the live feed & search page, there's a drop down on the top left (in the screenshot) that has 2 premade filters, one that contains all the terms and one that contains the URLs

On Apr 2, you can load Medallia and run those filters and export them.

![Screenshot 2023-03-17 121058](https://user-images.githubusercontent.com/73119703/225959761-1f19499c-8642-4c6c-a87a-4804ea7b48f5.png)

**Comment by Kimberley2019** [comment]
As of 4/4/23 currently experiencing Citrix issues, which is causing a work stoppage.  Ticket with VA Enterprise IT for a fix.

**Comment by aubreyarcangel** [comment]
data request delivered via onedrive to miya.furukawa@va.gov, alexander.ferzola@va.gov.
