### ISSUE TITLE
[technical discovery] Dependency Verification | Claim submission failures

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#54398]
## What's the problem?
Dependency Verification forms submitted through VA.gov are failing to establish, causing a spike in null claims that have to be manually established by a VBA regional office. 

---
## Background Context
[See linked document](https://docs.google.com/presentation/d/1aGtXYDRIzlalHKPRFSRuTTGfDiAgi6XH/edit#slide=id.p1)

## Discovery plan and tasks

|Do this...|...to accomplish this.|Findings and recommendation?|
|----|----|-----|
|Review the BenefitsClaimService Input/output documentation provided by Cheri Ray 02/28/23|Figure out how data should be formatted for establishment and spot VA.gov issues.|The null claims issue doesn't have to do with formatting. See https://github.com/department-of-veterans-affairs/vets-api/pull/11998 and row 2 below. However, there is a separate group of address validation issues we've seen on Sentry that should be addressed.<br><br>Recommendation: look through BGS address validation errors, and all other errors, and cross-reference our code's validations with those specified in Cheri's documentation.|
|Research the background job and the queue for processing the dependency claims.|Find other areas that may contribute to the problem and identify who can fix it.|Root cause identified. See https://github.com/department-of-veterans-affairs/vets-api/pull/11998 for short-term fix and description of long-term fix. <br><br> Recommendation: implement long-term fix referenced in PR.|
|Find out how failed submissions data is currently being collected and if/when/why failed submissions aren’t being logged and monitored in key parts of the service.|Put proper logging and monitoring in place.|We store form data for every 686c form submission but we do not distinguish between submitted and failed claims. This distinction can be inferred for claims that have failed in the past 90 days, because Sentry errors (which are only stored for 90 days) expose the saved claim's id which can be used to look up the saved claim's form data in the production database. How we would "re-submit" this data is an open question. <br><br> Recommendation: either way, we should make it easier to identify form data for failed submissions by either: i) adding a column to the saved_claims table, ii) configuring our submission sidekiq jobs to "die" rather than "fail", so that we have a record of the failed jobs, or iii) something else. 
|Investigate whether VA.gov is actually asking for the incremental EP and how the system is handling the increment.|Determine if this is a feasible way to prevent premature establishment actions.|See https://github.com/department-of-veterans-affairs/vets-api/pull/11998 and row 2 above.|
|Check duplicate dependency claim submissions and whether there is a mechanism to block subsequent claims.|Confirm if this is an effect of the issue worth triaging or adding real-time error notifications for.|Still need to think about this. I don't know whether we want to block subsequent claims or not. Either way, the fact that a vet can make multiple claims isn't the root cause of this issue. See https://github.com/department-of-veterans-affairs/vets-api/pull/11998 and row 2 above. But, I still think it would be a good idea to verify what exactly a vet is supposed to experience after submitting the 686c form on VA.gov, and then see whether that actually happens on VA.gov.<br><br>Recommendation: verify what exactly a vet is supposed to experience after submitting the 686c form on VA.gov, and then see whether that actually happens on VA.gov.|
|Check how the system is handling double-clicks.|Confirm if this is an effect of the issue worth triaging.|No need. This isn't the root cause of the null claims. See https://github.com/department-of-veterans-affairs/vets-api/pull/11998 and row 2 above.|
|Investigate whether there was a design or engineering decision to show the error in real time.|Decide if it is better to keep dependency claims processing as a background job.|Given that so many API calls to BGS are happening on submit, I think we have to process these claims on background jobs. The question is: what is our process going to be if they fail?<br><br>Recommendation: after figuring out how best to preserve and surface failed submission form data (see row 3 above) we need to spend time coming up with a process for handling these failures.|
|Verify veterans are receiving failed submission emails.|Determine the best way to give Veterans actionable/useful updates.|Yes, they are. But see https://github.com/department-of-veterans-affairs/va.gov-team/issues/56291|

## Questions or requests to pass to the VBA
- Regardless of what actually happens on VA.gov right now, what is _supposed_ to happen after a vet submits a 686 claim, and all the way up until the claim is processed/approved. Knowing the answer to this question will help me understand whether there are additional bugs with this form.

## When is this done?

- [ ] We've written the viable solutions we can implement this fiscal year
- [ ]  We have a report that includes the entire universe of Null Dependency Claims
    - It doesn't seem like this is possible. Although [VA.gov](http://va.gov/) does retain form data for all Form 686c submissions, we can only find failed form submissions (by cross-referencing Sentry data with saved claims in our prod database) if they failed within the past 90 days (Sentry only retains data for 90 days). Beyond that 90-day lookback, we have no way of easily distinguishing between successful and failed 686c submissions. As part of an effort to improve the 686c code, we probably want to improve our tracking in this regard, but we most likely cannot assemble a big retroactive report. 

---

**Comment by saderagsdale** [comment]
Check the hypothesis against the list of example claims Brandi sent over. 
Two possible batches:
- One has a quick fix
- The second needs further investigation with BGS

**Comment by data-doge** [comment]
Quick note to self. Will polish into a more formal update later on.

- Spoke to Linda, who clarified there are three relevant entities here: 1) the proc, 2) the pdf, 3) the claim. A null claim is the absence of the claim, though proc and pdf exist.
- Spoke to Brandi, who confirmed what Linda said, who gave me the broader history around null claims, and suggested I reach out to Krystal Connor (person who actually manually establishes null claims). Also says that numbers she reports come from tableau query that may need tweaks. Might need to look at tableau code. Not sure we can trust this table as source of truth.
- Spoke to Steve. Conversation about whether we need to create a PDF at all if call to BGS fails. 
- Spoke to Cory, who clarified that procs are created via a different endpoint than the insert_benefit_claim endpoint. Also suggested that we shouldn't need to create a proc at all. Need to confirm that, but so far no evidence indicating that procs serve any tangible purpose. Will do more research, if necessary. For now, sounds like we can just leave things be. 
- Spoke to Krystal. She finds out about null claims through the call center. Vet submits claim, later looks for proof of pending claim, can't find it, calls call center, call center files ticket, krystal picks up ticket, looks in VBMS eFolder, sees PDF, PDF looks fine, PDF source is lighthouse, looks in claim history, doesn't see claim, notes this a null claim, looks at PDF again, manually establishes claim with information provided. Doesn't know or care about procs, which supports Cory's suggestion that we can just do away with them. Krystal wonders why she isn't automatically alerted of failed claims -- believes that they should be "automatically off-ramped."  So actually two problems here. Krystal concerned about all the other null claims that _arent_ reported to call center. Says sometimes reported _years_ after filed. Also, Krystal not the only person who processes null claims. Other people pick up the tickets too. I asked krystal to let me know the next time she gets a null claim, so i can cross reference with our logs. She offered to give me a spreadsheet of all ~400 claims she's manually processed. Says she would ask around to see if others had the ability to produce a more comprehensive report. 
- Talked with Sam. Said that vet's claim status UI most likely pulls from VBMS by way of EVSS. Given no claim in VBMS dashboard,  likely that on success, BGS posts claim to VBMS. Meaning, we may be able to find all null claims through **VBMS**, without having to work with BGS. Can talk with Jerek for more info. There is a CST-VBMS standing weekly meeting. Could possibly join in on it. 

Takeaways: 
- actually don't need to do anything wrt "duplicate" null claims
- though, should check with kyle whether recent triplicate null claim produced more than one PDF. If not, then definitely nothing to do. May even downgrade sentry error to a sentry warning.
- need to re-think how to identify unprocessed null claims given what krystal said. may actually be able to leverage procs. also need to find the null claims that krystal hasn't yet processed.
- need to deal with all the other sources of errors, e.g. address validation, timeouts, etc. these probably produce _real_ null claims and not noise. may want to focus on clearing out sentry dashboard.

**Comment by data-doge** [comment]
Quick note to self:
- Spoke with Kyle. Duplicate submissions lead to duplicate PDFs. Additionally, if first succeeds and second doesn't, vet gets a failure email. Also, duplicate submissions each have separate request_ids in sentry, and confirmed that request ids in sentry come directly from client's x-request-id headers. Thus, indicates separate network requests and thus a FRONTEND problem. Another note, need to think about whether to send failure emails or not. Also failure emails are one way that vets would know to reach out to call center. Curious to know what those emails say. One idea for a short-term fix: do a form json check to do nothing in case of a duplicate.

**Comment by data-doge** [comment]
Quick note to self:
- To find all "null claims," we could possibly run a query to look for every vet with a 686c PDF but no associated claim, in EVSS

**Comment by data-doge** [comment]
**Summarizing takeaways from the above:**

1. Duplicate submissions resulting in null claims are the result of double-clicks on the frontend. This shouldn't be possible, but it is. I'm going to try to prevent that with a debounce function. That will require platform team's review. Once deployed, we can see whether that resolves our errors.
2. Address/name validation errors would also cause null claims. I need to resolve these next. 
3. There are _a lot_ of Sentry errors for this form, some of which may also result in null claims, or otherwise prevent vets from successfully submitting the form. I need to investigate and resolve these as well.
4. The reported numbers for null claims come from a tableau query that needs verification. We don't know for certain whether these numbers are accurate. After addressing the causes for null claims, we should review this reporting tool to ensure its accuracy.
5. Along with figuring out how to retroactively establish prior null claims, we should also: 1) improve logging and monitoring, 2) think about whether/how we alert veterans of errors, 3) think about whether we should create a PDF application in the eFolder if there is an error, 4) consider removing procs from our code, 5) think about how to automatically notify people like Krystal of errors, instead of leaving that burden with the vet.
