### ISSUE TITLE
Update va.gov-vfs-teams (Onboarding for External Contractors)

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#544]
As a new dev on VA.gov I need to successfully be onboarded and have access to tools so that I can build applications.

The following [page](https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/tree/master/Onboarding) for External Contractors will need to be updated and the new request for tools access needs to be linked to the page.

## AC
- [x] Update the [Onboarding for External](https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/tree/master/Onboarding) Contractors to be the source of truth for new dev, designers, PM and others working on VA.gov
- [x] Connect the new Environment access request template on the va.gov-team repo to the page, so new members know that they need to create an issue to gain access to dev tools.

**Comment by b00klegger** [comment]
Document explaining process for external team access merged here:
https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/pull/28

Issue template here:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/Environment-Access-Request-Template.md

**Comment by ricetj** [comment]
LGTM
