### ISSUE TITLE
FE | Profile | Notification Settings | Build editing page for profile PT2

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/va.gov-team#54434]
## Issue Description
Continues work on edit page for mobile phone number as MVP. Now that a page is created and able to be visited, now the correct form needs to be rendered, and navigation back to the previous page needs to be hooked up.

## Front end tasks
- Uses query param to load a field's form and associated buttons
- Instance of `ProfileFieldController` needs to be used and passed the field name so that form system initiates with related schema and ui:schema.
- Cancel button should use the previous page state and return user to this page when clicked.
- Ensure the page is styled according to design spec.
  - [Mobile form](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/v8ej4q3)
  - [Desktop form](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/wLGk4J9)
  - [Mobile page w/ confirmation message](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/4al7YGJ)
  - [Desktop page w/ confirmation message](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/WKLzddk)  
- Ensure the back end data from API is displayed in local and review instance
- Ensure unit tests are available.
  - Page component sanity checks
  - Checking for form instance rendering 
- Ensure your code changes are covered by E2E tests
  - Feature toggle visibility checks / url availability 
- Run axe checks using the Chrome or Firefox browser plugin
  - https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review
- Test for color contrast and color blindness issues
- Zoom layouts to 400% at 1280px width
- Test with 1 or 2 screen readers
- Navigate using the keyboard only

## Acceptance Criteria
- [x] Form renders on page for editing mobile phone number
- [x] Cancel button returns user to previous page and focuses on last active section
- [ ] Designer comments on this issue to approve page styling 
- [x] Unit tests pass
- [x] E2E tests cover current code and regression
- [x] End-to-end tests show 0 violations.
- [x] The data returned matches API response (for given user or scenario)
- [x] All axe checks pass
- [x] All color contrast checks pass
- [x] All zoom testing passes
- [x] All keyboard checks pass 
- [x] All screenreader checks pass

**Comment by BerniXiongA6** [comment]
@andaleliz can look for historical info/notes to check on "extension" discussion before removing it cc: @adamwhitlock1

**Comment by andaleliz** [comment]
@adamwhitlock1 I can't find anything around this, other than an email chain from 2022 asking for updates 🙃  I think you're fine to proceed w/ your plan to remove the field from the mobile number.

**Comment by adamwhitlock1** [comment]
I have this update up on staging.

Right now, the editing page is only turned on for test user: `vets.gov.user+75@gmail.com`

To validate, log in with the test user, make sure that they don't have a mobile number saved, then navigate to the notification-settings page and see that there is an alert present, and the alert will include a link to the new editing page.

On the new editing page you should be able to provide a new mobile number, then save and verify that the user is directed to the notification-settings page and sees a success alert at the top of the page with the notification settings now 'unlocked' and viewable

**Comment by mtcA6** [comment]
I validated this, everything looks good. Recommend an additional story for making the Update in the screenshot function the same way.l 
![image](https://user-images.githubusercontent.com/129431463/234104163-3a85668d-4324-4e9f-a776-40dd65e9b356.png)

**Comment by adamwhitlock1** [comment]
Added a ticket to update the link that @mtcA6 mentioned. Will close out now.

**Comment by andaleliz** [comment]
Hi @adamwhitlock1 and @mtcA6! I believe in stand-up last week, we talked about the need to figure out a release plan for this. Have any decisions been made around that? I don't think I should start on documentation updates #48952 until this is live on production, or we have a date I could reference in the docs.
