### ISSUE TITLE
Supplemental Claims | Submit an Intent to File

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#54435]
## Value Statement
**_As a_** Veteran that is filing a supplemental claim over one year after the decision date
**_I want to_** submit an Intent to File as soon as I begin the filing process
**_So that_** I can save the earliest effective date for my benefits. 

---
## Background Context
We have approval from the VBA to re-use the Intent to File feature that's in the 526ez. The VBA is releasing updated guidance to claims processors to ensure they know how to associate the right ITF to the right claim. 

## Acceptance Criteria
- [x] When users start an application for the Supplemental Claim form on VA.gov, they are shown whether or not they have an active ITF on file. 
- [x] If yes, we don't create a new active ITF.
- [x] If no, an ITF is submitted and stored in the VBMS ITF table.
- [x] The ITF is visible in the VBMS interface to a claim processor.

## Designs and Build Notes
- [Link to designs](https://www.sketch.com/s/d2416db4-9a4f-4919-abe4-20ba4bdcfd89/v/rWOJjA/p/B8B6038B-E3DE-4B50-B5AB-7D05D44F5C91/canvas?posX=-223.44187088132787&posY=-78.65103659702999&zoom=0.6415625214576721)
- [Link to content](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Supplemental-Claims/design/sourceofcontenttruth.md#you-submitted-an-intent-to-file) 

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by eileen-coforma** [comment]
@saderagsdale @Mottie Added designs. Let me know if you have any questions.

**Comment by eileen-coforma** [comment]
@saderagsdale I can't validate VBMS side of things. Also, since there's already an ITF submitted, I can only validate the copy for the screen that shows they already have an ITF, and that's good to go.

**Comment by Mottie** [comment]
I think you'll just need to try random users... it's a one shot deal because a newly created ITF lasts a year.

**Comment by Mottie** [comment]
In my local dev environment, the ITF dates are fixed, so it's always submitting a new one. This is the screenshot I see:

<img width="657" alt="You submitted an intent to file success alert with continue button" src="https://user-images.githubusercontent.com/136959/225923040-787b0b90-cf52-44b8-bb4a-787a5941b20b.png">

**Comment by saderagsdale** [comment]
Got it. @Mottie can we clean one user up for the staging review? They need to be able to test both screens for ITF.

**Comment by Mottie** [comment]
@kylesoskin is there any way we can reset an ITF?
