### ISSUE TITLE
Appointment List Re-design - Alignment updates

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#54445]
## Description
Product and Design team are looking to update the appointment list to help the Veteran better understand the details for their appointment

---

## Acceptance Criteria
Background: the `va_online_scheduling_appointment_list` toggle is on

- [Layout guidelines](https://www.figma.com/file/JpGM8LGBCqAlL8qh3DmFk8/Home-Page-Redesign?node-id=3842%3A59523) 
- [Hover states](https://www.figma.com/file/JpGM8LGBCqAlL8qh3DmFk8/Home-Page-Redesign?node-id=2130%3A68678)

- [x] Extend same-day divider lines so they align with the main divider lines. 
    - This change is for the desktop breakpoint (1008px and up)
    - Currently on staging the same-day divider lines are slightly shorter than the main lines: 
    - <img width="200" alt="Pasted_Image_3_2_23__9_06_AM" src="https://user-images.githubusercontent.com/2536801/222501692-521f11ad-e3a7-48a1-99f4-93c632649afd.png">

- [x] Extend the hover state background to the full width of the row
    - This change is for the desktop breakpoint (1008px and up)
    - Currently the hover state background is slightly shorter on either side:
    - <img width="1042" alt="Screenshot_2023-03-02_at_9_30_52_AM" src="https://user-images.githubusercontent.com/2536801/222507091-047e7870-6eb4-403d-95dd-b07e6df2135d.png">

- [x] Desktop: Left-align days of the week (Mon, Tue, Wed, etc). 
    - Currently, they're not left-aligned:
    - ![Pasted_Image_3_2_23__9_14_AM](https://user-images.githubusercontent.com/2536801/222503187-66afb6cc-16c5-4ab8-880f-f6e81e9e5d39.png)

### Design Assets
All spec copy is FPO. Use copy in copy doc.

## Definition of Done
- [x] All acceptance criteria are met
- [x] Documentation is updated

---

**Comment by vbahinwillit** [comment]
Please note that all column spacing issues are addressed in #54818. Thanks

**Comment by ldelacosta** [comment]
@outerpress @Cieramaddox - this is ready to be validated. Please let us know if you have any issues. Thanks!

**Comment by Cieramaddox** [comment]
@ldelacosta Everything in this ticket has been met.

**Comment by ldelacosta** [comment]
No issues reported. Closing out the ticket.
