### ISSUE TITLE
Appointment List Re-design - Breakpoint line issue

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#54444]
## Description
Product and Design team are looking to update the appointment list to help the Veteran better understand the details for their appointment

---

## Acceptance Criteria
Background: the `va_online_scheduling_appointment_list` toggle is on

A dividing line is showing up under the month only at the breakpoint between 320 and 480px.  Current example is from staging at 480px:

Upcoming appointments

<img width="481" alt="Screenshot_2023-02-27_at_12_45_17_PM" src="https://user-images.githubusercontent.com/2536801/222283574-e0fddd8e-919b-4886-9313-630675d2ed0c.png">

Past appointments

<img width="360" alt="Screenshot_2023-03-01_at_2_43_39_PM" src="https://user-images.githubusercontent.com/2536801/222283513-5590cd31-5ed7-44ed-9118-487236ac8a3c.png">

## Proposed solution

- [ ] Remove the line under the month across all breakpoints.

### Design Assets
See mobile specs on [this page](https://www.figma.com/file/JpGM8LGBCqAlL8qh3DmFk8/Home-Page-Redesign?node-id=2161%3A54658).
All spec copy is FPO. Use copy in copy doc.

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by outerpress** [comment]
@ldelacosta this one is ready to go

**Comment by ldelacosta** [comment]
@Cieramaddox @outerpress - this ticket is ready to be tested. Please validate and let us know if you run into issues. Thanks!

**Comment by outerpress** [comment]
Looks great, confirmed the line has been removed.

**Comment by ldelacosta** [comment]
No new issues reported. Closing out the ticket.
