### ISSUE TITLE
Appointment List Re-design - Truncation updates

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#54443]
## Description
Product and Design team are looking to update the appointment list to help the Veteran better understand the details for their appointment

---

## Acceptance Criteria
Background: the `va_online_scheduling_appointment_list` toggle is on

Cell text truncates before it fills up the available space in the cell. Example:
<img width="982" alt="Screenshot_2023-03-01_at_3_03_57_PM" src="https://user-images.githubusercontent.com/2536801/222287479-93f1b802-0064-496a-8322-54d3b8ac88cb.png">

### Proposed solution
- [ ] All list text fills available space before it is truncated in upcoming, past, and pending appointments on all screen sizes

### Design Assets
All spec copy is FPO. Use copy in copy doc.

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by outerpress** [comment]
@ldelacosta this is ready to go

**Comment by vbahinwillit** [comment]
This should be fixed in #54818

**Comment by ldelacosta** [comment]
No new issues. Closing out the ticket.
