### ISSUE TITLE
Supplemental Claims | Usability testing findings

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#54446]
## What's this ticket for?
This ticket includes changes we want to include in the supplemental claim form as a result of usability testing.

## Stuff to do
- Half of the participants were confused by the Appeals Modernization Act because they didn't know about the old appeals process, but still continued with the form.
- [ ] Revise AMA content and move AMA screen to the beginning the form, instead of mid-form.
  - [x] ALT: Keep AMA screen as-is and just revise AMA content to make the impact of AMA clearer.
- Most of the participants misunderstood the action for the 'print this page' button.
- [ ] Change action for _Print this Page_ to create a PDF that combines the confirmation page and watermarked copy of claim.
  - [x] ALT: Change button language on confirmation page from _Print this Page_ to _Print this Confirmation_ 
- Most participants thought the 'Edit' link on the issue summary page and evidence summary page would let them perform an action different from what they actually do.
- [x] Remove edit links from issue summary page
- [x] Edit links from list items in "You uploaded these files" will direct to the same item on the upload evidence page.
  - [x] ALT: Remove edit link on upload list item
- A few participants were not able to locate the action link to file a Supplemental Claim on the unauthorized site-wide introduction page.
- [x] Static content page link to start a supplemental claim is not easy to find - content team to update.
- A few participants experienced confusion when they reached the warning alert on the evidence summary page.
- [x] Add additional language about presumptive claims to clarify no evidence warning.

## Designs and Build Notes
- [Updated AMA content](https://www.sketch.com/s/d2416db4-9a4f-4919-abe4-20ba4bdcfd89/a/elrpb3m#Version) 
- [Confirmation page](https://www.sketch.com/s/d2416db4-9a4f-4919-abe4-20ba4bdcfd89/a/8VxWP3O#Version)
- [Evidence summary page](https://www.sketch.com/s/d2416db4-9a4f-4919-abe4-20ba4bdcfd89/a/09Dg1Me#Version)
  - For launch, remove the edit link for individual items in the document summary. Revisit later to explore a better link placement, if we are adding it back in.
- Validate this static content page is better [Content team's update](http://preview-prod.vfs.va.gov/preview?nodeId=3011)
- [Evidence summary warning alert](https://www.sketch.com/s/d2416db4-9a4f-4919-abe4-20ba4bdcfd89/a/m1Dkyrw#Version)

## Out of scope
- Half of the participants struggled with going back and uploading evidence from the evidence summary page.
- [ ] Explore ways to increase clarity behind the 'add more evidence' link.
- [ ] Explore non-linear form formats (experimental task list pattern from gov.uk)

## Open questions
- Is the PDF generation something we can do before launch, or will it wait til after launch?
- Do we want to shift the AMA to come before the form?

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by saderagsdale** [comment]
@eileen-coforma can you add links to the documents/draft designs we looked at to this ticket?

**Comment by saderagsdale** [comment]
Talk to LH about PDF endpoint.

**Comment by eileen-coforma** [comment]
@saderagsdale 
Moved the following to the OAR recommendations ticket, since it's part of the OAR requirements.
- [ ] Remove AMA check box.

**Comment by saderagsdale** [comment]
Note for "Revise AMA content and move AMA screen to the beginning the form, instead of mid-form.":

We will review post-launch data to determine the percentage of users that actually see this page.

**Comment by eileen-coforma** [comment]
Open tasks from this ticket have been turned into separate tickets:
[AMA](https://github.com/department-of-veterans-affairs/va.gov-team/issues/55781)
[Print this Page](https://github.com/department-of-veterans-affairs/va.gov-team/issues/55397)
