### ISSUE TITLE
Midpoint Review - Content Feedback - Forms-Digitize, Form 26-4555

### ISSUE THREAD

**Issue by CherylEvans** [department-of-veterans-affairs/va.gov-team#54448]
## VFS acceptance criteria
- [x] Let Platform know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [x] VFS team closes the ticket

## Thoughts/questions
-

## Feedback
- Practice areas will document their feedback following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback).

**Must:**
In accordance with VA.gov Design System Content standards, Plain Language, active voice must be used.  
An action should always be connected to a subject. If there’s no subject taking responsibility for the verb, it’s likely passive voice.

**The following are examples of passive voice verbiage:**  

- SAHG - Authenticated - Not sending to profile -> I recommend: Instead of "Your application will be saved on every change" it should be "We'll save your application on every change"

-  SAHG - Authenticated - Not sending to profile -> Green alert -> Instead of “Your request has been saved.  It was last saved on December 2, 2022, at 5:25 p.m. EST.” I recommend using the following:
“We’ve saved your request.  We saved it on December 5, 2023, at 5:25 p.m. EST.”

**Misuse of verb**

- Need help? Pages ->  SAHG - Authenticated - Not sending to profile & SAHG - Unauthenticated
"If you need help to gather your information or fill out your form," should change to "If you need help gathering your information or filling out your form"  
This is the explanation for the recommendation: "Some verbs should be followed by a to-infinitive (e.g., to go), while others require a gerund (e.g., going) Gerunds are derived from verbs."  

Some helpful examples: 

**Incorrect** "There purpose of this experiment is **implementing** a new policy.
**Correct** "The purpose of this experiment is **to implement** a new policy.

**Incorrect** "You may have difficulty **to determine** the cause of the fire."
**Correct** "You may have difficulty **determining** the cause of the fire."

**Should:**

**Consider:**

## Platform directions
- Remove the governance-team label
- Update "Issue Title"
- Link to collab cycle Request epic
- Add your feedback
- Remove the CC-Request label (only if you created the ticket using the New Issue link from the Collaboration Cycle Reviews board)
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review QA Only**: VFS PM, yourself (optional)

**Comment by jeana-adhoc** [comment]
The content edits have been made. I also spoke with the design system folks, and shared this feedback with them so we can update [guidance in the design system](https://design.va.gov/patterns/help-users-to/know-how-their-information-is-updated) as well.
