### ISSUE TITLE
SOCKS access for Luke Short

### ISSUE THREAD

**Issue by lukey-luke** [department-of-veterans-affairs/va.gov-team#54453]
### Your Name

Luke Short

### Your Email

luke@verdance.co

### Your Role and Team

Software Engineer on Contention Classification

### Product Manager (PM) name and email

Yurena Garcia - yurenagarcia@navapbc.com

### Product Owner (PO) name and email

Emily Theis - emily.theis@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC6Kex55qhFkxYRP2K2tar9RaEErsJ7DJHtcVQgG/70OL+jRFQcg2WvFK5bQVKBkj1irLitvONuIgK9ovgJqEwTv8lwqntPdOq0YgklIP9cez5OfSGdmM/bskmNZLQ3pMh6GT2P4JNJBP8EpsCTsj6s+a4ra8mA/J0CphB20Ao7N5FHkxXapQREED6Cf4l62TMx2nNCB8hJfe4+ygMHBUpIQIhDxQqLTw5KMe0gT9rLBl7LaIB79wxZA0h3QmUt8hPFWKSevRLZUAXDsosqNwpnSLScAbQ/EVx0MdFcXCaXg3+fBnPSdttT6+norfh8sNeeV1GL0cRtvuhiDqs+bXBOUidS4/ZQ5FjLhL8yZlmeIqqotTC47KxHiJGhgB6UJDsP8sqlzQiDtR7/NutcarV6DQzBiYMlhbSPNEfFtW5apz00ZDf/n3BHnx0xeohUt5vpb/ugBSxL4o9eig0zpWMnvtIzcrpPsal//ez5zZ7bwglWH6w+By3h/YkWRB0J380= verdanceluke@Verdances-MacBook-Pro.local

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by ryan-mcneil** [comment]
Adding for reference

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/41602677/6fdd182a-cdc2-4322-aef5-13c5f36365dd)
