### ISSUE TITLE
BE | My VA | Benefits Payments | Documentation

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#54462]
## Background
The [Benefits Payments backend document](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/my-va/benefits_payments/backend_documentation.md) needs to be updated.

## Tasks
- [ ] Update document
- [ ] Ensure document outline is consistent with other My VA BE documents.  

## Acceptance Criteria
- [ ] Review with Auth Exp team members

**Comment by ajakabcin** [comment]
thanks @dellerbie looks great!
