### ISSUE TITLE
[ONGOING] Increase Unit Test Coverage with an Ultimate Goal of > 75%

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#54475]
## Description
Increase Unit Test Coverage with an Ultimate Goal of > 75%

**Comment by wullaski** [comment]
@loripusey I ran a coverage report locally on our entire app and these are the results
![image](https://user-images.githubusercontent.com/2982977/228955494-48d14d1a-72c7-4057-8971-77fde6007b75.png)

**Comment by wullaski** [comment]
## Before
/check-in/day-of
![coverage--day-of](https://user-images.githubusercontent.com/2982977/231509360-5ca81c94-0b95-4817-83a3-e25a768e8325.png)

/check-in/pre-check-in
![coverage--pre-check-in](https://user-images.githubusercontent.com/2982977/231509489-6be8c738-1abe-48b3-bdd9-437966347516.png)

/check-in
![coverage--entire-app](https://user-images.githubusercontent.com/2982977/231509530-bcc4804b-1e40-4e66-8cb1-47d0f2492b8b.png)

**Comment by wullaski** [comment]
## After

Day of
![coverage-day-of.png](https://images.zenhubusercontent.com/62ace7e07463ea93483c002a/feeeb56c-44ed-41ca-8f68-46c6e47f44be)

Pre Check In
![coverage-pci.png](https://images.zenhubusercontent.com/62ace7e07463ea93483c002a/11571fd5-c11c-49ba-84d8-736c511830f8)

Entire App
![coverage-entire-app.png](https://images.zenhubusercontent.com/62ace7e07463ea93483c002a/3e6550f9-add6-444e-8cdf-4d553b5d778f)
