### ISSUE TITLE
Ruby 3 Spec: Big list of Arg Errors

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#54484]
Here's a list of failures we can work off of:

- [x] https://github.com/department-of-veterans-affairs/va.gov-team/issues/54796
- [x] https://github.com/department-of-veterans-affairs/va.gov-team/issues/54797
- [x] https://github.com/department-of-veterans-affairs/va.gov-team/issues/54798
- [x] https://github.com/department-of-veterans-affairs/va.gov-team/issues/54802
- [x] https://github.com/department-of-veterans-affairs/va.gov-team/issues/54799
- [x] https://github.com/department-of-veterans-affairs/va.gov-team/issues/54801
- [x] https://github.com/department-of-veterans-affairs/va.gov-team/issues/54800
- [x] https://github.com/department-of-veterans-affairs/va.gov-team/issues/54814
- [x] https://github.com/department-of-veterans-affairs/va.gov-team/issues/54803
- [x] https://github.com/department-of-veterans-affairs/va.gov-team/issues/54269
- [x] https://github.com/department-of-veterans-affairs/va.gov-team/issues/54272
- [x] https://github.com/department-of-veterans-affairs/va.gov-team/issues/54271
- [x] rspec ./spec/requests/v1/apidoc/shared_examples/facility_locator_spec.rb:21
- [x] rspec ./spec/requests/v1/apidoc/shared_examples/facility_locator_spec.rb:23
- [x] rspec ./spec/requests/v1/apidoc/shared_examples/facility_locator_spec.rb:30
- [x] rspec ./spec/requests/v1/apidoc/shared_examples/facility_locator_spec.rb:31
- [x] rspec ./spec/lib/saml/ssoe_user_spec.rb:561
- [x] rspec ./spec/lib/saml/ssoe_user_spec.rb:597
- [x] rspec ./spec/lib/saml/ssoe_user_spec.rb:701
- [x] rspec ./spec/lib/saml/ssoe_user_spec.rb:720
- [x] rspec ./spec/lib/saml/ssoe_user_spec.rb:782
- [x] rspec ./spec/lib/saml/ssoe_user_spec.rb:806
- [x] rspec ./spec/lib/saml/ssoe_user_spec.rb:841
- [x] rspec ./spec/support/spec_builders.rb:16
- [x] https://github.com/department-of-veterans-affairs/vets-api/pull/11954
- [x] rspec ./spec/jobs/decision_review/submit_upload_spec.rb:31
- [x] https://github.com/department-of-veterans-affairs/va.gov-team/issues/54270
- [x] https://github.com/department-of-veterans-affairs/va.gov-team/issues/54266
- [x] https://github.com/department-of-veterans-affairs/va.gov-team/issues/54267
- [x] https://github.com/department-of-veterans-affairs/va.gov-team/issues/54268
- [x] https://github.com/department-of-veterans-affairs/va.gov-team/issues/54266
- [x] https://github.com/department-of-veterans-affairs/vets-api/pull/11959
- [x] https://github.com/department-of-veterans-affairs/vets-api/pull/11955
- [x] https://github.com/department-of-veterans-affairs/vets-api/pull/11983
- [x] https://github.com/department-of-veterans-affairs/vets-api/pull/11965
- [x] https://github.com/department-of-veterans-affairs/vets-api/pull/11967

**Comment by oseasmoran73** [comment]
Looks like `./spec/requests/v1/apidoc/shared_examples/facility_locator_spec` has been resolved in the process

**Comment by holdenhinkle** [comment]
Ticket for updating the apivore Gem which will fix the failing Swagger tests - https://github.com/department-of-veterans-affairs/va.gov-team/issues/54552

**Comment by oseasmoran73** [comment]
Looks like `./spec/models/user_session_form_spec.rb:100` is fixed by https://github.com/department-of-veterans-affairs/vets-api/pull/11954/files

**Comment by oseasmoran73** [comment]
Loks like ` rspec ./spec/support/spec_builders.rb` is fixed. @holdenhinkle confirmed on his end as well

**Comment by oseasmoran73** [comment]
`rspec ./spec/lib/saml/ssoe_user_spec.rb` is fixed by [pr](https://github.com/department-of-veterans-affairs/vets-api/pull/11992)

**Comment by ericboehs** [comment]
As far as we can tell, these are all passing now.
