### ISSUE TITLE
[Content organization] Content organization and/or information within the user flow doesn't properly support all users. (02.07.1)

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#54482]
#### VFS team name
Modernized Check-in

#### VFS product name
Patient Check-in

#### VFS feature name
Appointments Consistent with VAOS Visual Design

#### Point of Contact/Reviewers
Cheryl Evans - @CherylEvans - Content

*For more information on how to interpret this ticket, please refer to the [Anatomy of a Staging Review issue ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Anatomy-of-a-Staging-Review-Issue-ticket.2060320997.html) guidance on Platform Website.

---

### Platform Issue
Content organization and/or information within the user flow doesn't properly support all users.

### Issue Details
Informational alert "parte del contenido podría estar en inglés" in Spanish mode is missing on the Tagalog page

### Link, screenshot or steps to recreate
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/staging-review-images/50817_Cheryl_1_Tagalog%20verbiage_Screenshot%202023-02-28%20at%201.53.36%20PM.png

### VA.gov Experience Standard
[Category Number 02, Issue Number 07](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

### Platform Recommendation
Informational alert "parte del contenido podría estar en inglés" in Spanish mode should also be translated and placed on Tagalog pages

---

### VFS Guidance

- Close the ticket when the issue has been resolved or validated by your Product Owner
- If your team has additional questions or needs Platform help validating the issue, please comment on the ticket
- Some feedback provided may be out of scope for your iteration of the product, however, Platform's OCTO leadership has stated that all identified issues need to be documented and it is still your responsibility to resolve the issue.
- If you do not believe that this Staging Review issue ticket is the responsibility of your team, comment below providing an explanation and who you believe is responsible. Please tag the Point of Contact/Reviewers. Governance team will research and will follow up.

**Comment by benbrasso-agile6** [comment]
Not sure who should check into this. Maybe start with frontend.

**Comment by loripusey** [comment]
We do have the content translated for Tagalog; but it does not display; so the work is to figure out why

**Comment by wullaski** [comment]
@loripusey @brianseek This seems to be that a feature toggle needs to be flipped. I'm looking at docs on how to do that and trying to get access. We should check production as well. An issue could be created to remove this feature toggle. I don't know how useful it is anymore.

**Comment by brianseek** [comment]
@wullaski we will still want the feature toggle. The idea is that we can turn it on/off as we need and complete translations for a given language.
