### ISSUE TITLE
consolidate unnecessary design tf environment

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#5449]
## User Story or Problem Statement

It looks like during some of the design.va.gov work, there was a separate environment created in terraform unnecessarily: https://github.com/department-of-veterans-affairs/devops/tree/master/terraform/environments/dsva-design-prod

We can move the thing that's in there into the dsva-vagov-prod environment and just remove that directory. This'll help us clean up a bit to shrink that reduce environment list.

## Goal

dsva-design-prod environment gone and resources managed in the dsva-vagov-prod environment

## Acceptance Criteria
- [ ] design.va.gov S3 bucket itself is untouched
- [ ] dsva-design-prod environment is gone
- [ ] resources from old environment are imported and unchanged, but managed by dsva-vagov-prod

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by benniemosher** [comment]
For steps to reproduce see https://github.com/department-of-veterans-affairs/devops/pull/6339
