### ISSUE TITLE
Midpoint Review - Accessibility Feedback - Forms-Digitize, Form 26-4555

### ISSUE THREAD

**Issue by briandeconinck** [department-of-veterans-affairs/va.gov-team#54505]
## VFS acceptance criteria
- [x] Let Platform know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [x] VFS team closes the ticket

## Thoughts/questions
I don't have a specific recommendation, but I want to flag something as potentially needing attention. 

![statement-of-truth](https://user-images.githubusercontent.com/6844775/222531975-a800948e-c96c-4889-a73d-5297992c62dd.png)

In the Statement of Truth section at the end of the form (screenshot above), there's a large block of text ("I certify that I am applying...") that comes before the name input and checkbox, plus another block of text ("Note: According to federal law..."). If a screen reader user is tabbing through the page, they may skip over each of these text blocks without ever hearing them announced. What they will hear, however, is the "I certify that the information above is correct and true..." statement that labels the checkbox.

My question -- and this is up to you all to figure out, I have no idea! -- is how critical it is that screen reader users hear both of those blocks of text before checking the box and submitting. If it's critical that the text not be skipped over, then it may be necessary to associate those paragraphs with the checkbox using `aria-describedby`. When a user tabs to the checkbox, their screen reader will announce both the checkbox label and the supporting text. If it's not critical, then no action is needed.

(To me, "critical" here means "the Veteran can't responsibly complete the task without the information in those paragraphs." If it's something a sighted Veteran would probably just skip over or ignore on their way to pushing the submit button, I don't think I'd call it critical. But I'm also not your VA stakeholder so I am not the right person to make that judgment!)

In the touchpoint meeting, @humancompanion-usds pointed out that this is a [pattern in the design system](https://design.va.gov/patterns/ask-users-for/signature) that may need attention more broadly. I'm not sure how widespread the pattern is, but I can confirm that the 10-10CG form linked from the design system does **not** currently use `aria-describedby` as suggested.

## Feedback
- Practice areas will document their feedback following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback).

**Must:**

**Should:**

**Consider:**

## Platform directions
- Remove the governance-team label
- Update "Issue Title"
- Link to collab cycle Request epic
- Add your feedback
- Remove the CC-Request label (only if you created the ticket using the New Issue link from the Collaboration Cycle Reviews board)
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review QA Only**: VFS PM, yourself (optional)

**Comment by tbaker1026** [comment]
@humancompanion-usds - see Brian's comments

**Comment by jeana-adhoc** [comment]
After discussion with the @ndsprinkle and @humancompanion-usds - We're going to go this route. 

![image.png](https://images.zenhubusercontent.com/6363f67c202a4724e630f86d/d81ccd23-5dba-4008-a565-af72a8bc4b74)

Statement of truth - h2
Fieldset
- Certifying text - legend for fields
    - Your full name
    - Certify Checkbox

Another design that breaks up the certification statement into separate checkboxes that would be checked per statement has been tabled to be tested later.
