### ISSUE TITLE
MHV on VA.gov landing page users can sign up for MHV newsletter

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#54502]
## Story
"As a user viewing the MHV on VA.gov authenticated landing page (va.gov/my-health), I can easily sign up for the MHV newsletter, so I can receive important updates from the MHV team about VHA care and related issues."

## Additional info
This is what the sign up feature looks like on authenticated MHV portal landing page (appears to be same on [unauthenticated MHV portal landing page](https://mhv-syst.myhealth.va.gov/mhv-portal-web/home)):

<img width="411" alt="image" src="https://user-images.githubusercontent.com/7645362/222530862-f8989fa2-bb46-4c83-90a8-5c3a19d9b073.png">

Entering an email address (or potentially any value) takes the user to https://public.govdelivery.com/accounts/USVHA/subscribers/qualify with a POST containing a payload like 

```
utf8=%C2%BF&authenticity_token=zrD8Ri9HkK5xMUmPd%2F64OtM13GRi0R9lmtOiprc1K4N%2FI6%2BcXT%2B0y%2Bg1HmXpYPAt0ZT4lSgWuQk99qqiAsy%2FZQ%3D%3D&topic_id=USVHA_60&email=foo%40foo.bar&commit=Submit
```

## Acceptance criteria
- [ ] User can sign up for MHV newsletter in <=3 clicks

**Comment by dcloud** [comment]
FWIW, the `va-text-input` web component doesn't appear to work with html native `required` validation for forms… I can either roll my own validation, or use a non-component input with vads/uswds styles. Leaning toward the latter as it is less reinventing the wheel for a one element form.

**Comment by dcloud** [comment]
Also the [bespoke `va-text-input` component](https://design.va.gov/storybook/?path=/docs/components-va-text-input--default#required) adds a red "(Required *)" not in the mockup. Unsure if we want that for a single input

**Comment by dcloud** [comment]
@batemapf Do we want to wait for info. from GovDelivery or move forward with the PR while we try to contact someone?

**Comment by dcloud** [comment]
The short answer from GovDelivery/Granicus was use this snippet: [USVHA_60 Signup Code.txt](https://github.com/department-of-veterans-affairs/va.gov-team/files/11113078/USVHA_60.Signup.Code.txt), which matches what's on MHV. Slightly interesting that the `authenticity_token` field is in this form but not choose.va.gov, though not worth investigating 😏 

Going to add a Cypress test and should be ready to review after that

**Comment by dcloud** [comment]
@batemapf Per my comments / request for feedback on the PR, https://github.com/department-of-veterans-affairs/vets-website/pull/23623, the GovDelivery form takes you to another form on their domain, so it may technically be <3 clicks, but involves filling out additional fields. Screenshots attached.

Also, I made the email field required on our version, as submitting without an email makes the GovDelivery flow one step/page longer. However, MHV Classic does not require the email be filled out… users just get taken to an error page.

**Comment by batemapf** [comment]
> so it may technically be <3 clicks, but involves filling out additional fields. Screenshots attached.

all good. the <3 clicks thing was arbitrary :-)

required field makes sense, thanks for adding!
