### ISSUE TITLE
[FE] Change alert content shown when Veteran is too early to check in within check in app

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#54511]
## Description 

In the check in application, before a check in window, an alert component is used to show: 

> You can check in starting at this time: 9:15 a.m.

Recommend changing the format of the content to the following: 

> You can check in starting at 9:15 a.m. 

## AC

- [ ] When accessing check in prior to an appointment's check in window, the alert content should read, "You can check in starting at {time}."

**Comment by brianseek** [comment]
@loripusey / @benbrasso-agile6 I made an exception for our translation rules on this one and updated the existing key, so we wouldn't loose our Spanish and Tagalog translations for this. But `you-can-check-in-starting-at-this-time` should get flagged for a new translation for each.

**Comment by benbrasso-agile6** [comment]
Cool. Sounds like maybe we need a ticket for guide and design artifacts to be updated. @loripusey

**Comment by brianseek** [comment]
also this is merged and ready for validation

**Comment by loripusey** [comment]
Looks like the content still has the ":", can we remove the colon? @brianseek

**Comment by loripusey** [comment]
FYI, I created 2 artifacts tickets (product & design).

**Comment by brianseek** [comment]
@loripusey created new PR here: https://github.com/department-of-veterans-affairs/vets-website/pull/24112

**Comment by loripusey** [comment]
validated
