### ISSUE TITLE
AWS access for Swapna Krishnankutty

### ISSUE THREAD

**Issue by swapna-tw** [department-of-veterans-affairs/va.gov-team#54536]
### COR Name

Courtney Bethea

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### E-QIP Transmittal Date

- [x] Check this box if you have an E-QIP transmittal date.

### Your Name

Swapna Krishnankutty

### Your Email

swapna.k@thoughtworks.com

### Team, Role, and Company of the target individual

Virtual Agent Chatbot, Quality Analyst, Thoughtworks, Inc.

### Product Manager (PM) name and email

Ian Santarinala, ian.santarinala@thoughtworks.com

### Product Owner (PO) name and email

Luciana Morais, Luciana.Morais@va.gov

### Desired AWS Access

- I need access to an EKS instance/pod so that I can run queries in rails console
- I would like to inspect secrets stored in Parameter Store in AWS. I may need to update secrets as we add new pipelines.
- I want to have access to vets-api-server log group so I can understand the identifiers that are being sent to EVSSClaims in order to build an integration with the Chatbot.
- Similar permissions as [kha.huynh@thoughtworks.com](mailto:kha.huynh@thoughtworks.com) & [raina.huerta@thoughtworks.com](mailto:raina.huerta@thoughtworks.com)

### Access Expiration

Ongoing

### Additional Notes

Additional COR : Cecilia Lee: Cecilia.Lee@VA.gov

Need this access to connect to dev-api cloud console to sync up ICNs of test data in MVI with the data in vets-api-mockdata repo.

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by little-oddball** [comment]
VFS Roster

**Comment by BillChapmanUSDS** [comment]
I approve this but just need the Eqip dated added.

**Comment by pjholyoke** [comment]
Opened PR, just waiting on review

**Comment by rmtolmach** [comment]
@swapna-tw 
>  need access to an EKS instance/pod so that I can run queries in rails console

If you're looking for vets-api EKS access, that is requested through a separate form. I recommend filling it out once you officially have AWS access
That form is here:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=external-request%2Cplatform-tech-team-support%2Cops-access-request&template=vetsapi-argo-terminal-access.yaml&title=Vets-api+terminal+access+for+%5Bindividual%5D

**Comment by pjholyoke** [comment]
Sent user login details.
