### ISSUE TITLE
Sidekiq Admin UI Access Request

### ISSUE THREAD

**Issue by mchristiansonVA** [department-of-veterans-affairs/va.gov-team#54534]
_Access to the Sidekiq Admin UI is managed through a GitHub team under the [department-of-veterans-affairs/va.gov-sidekiq team](https://github.com/orgs/department-of-veterans-affairs/teams/va-gov-sidekiq/members). Please provide your GitHub username to be added to that team, along with a reason access is required._

- GitHub username: mchristiansonVA
- Reason access is required: Team Dash Production Support - Team Dash runs the Claims API within Lighthouse and we require access to troubleshoot issues and support the Claims API in general.
- Environments requesting access to: All

**Comment by mchristiansonVA** [comment]
Any update on this?

**Comment by ryan-mcneil** [comment]
@mchristiansonVA Thanks for bumping this - I'm not sure how it slipped through the cracks. You've been approved for dev/staging/sandbox. We are currently working through an approval process for Prod and will update as soon as I can!

**Comment by ryan-mcneil** [comment]
@mchristiansonVA  You've been granted access to all environments, with access to Production limited to 6 months, expiring 11/5/23

**Comment by ryan-mcneil** [comment]
Slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1683305445275849)

**Comment by bdech** [comment]
@mchristiansonVA  Your Sidekiq Admin UI Production access has expired. Would you like to request an extension of access?

**Comment by mchristiansonVA** [comment]
Apologies, I didn't see the notifications above to request an extension. Can you please add my production access back? I'm on production support rotation this week and need this for troubleshooting Claims API requests.

**Comment by mchristiansonVA** [comment]
@bdech Just realized I forgot to re-open this one: Can you please re-add my production access for sidekiq? If you need a new ticket let me know and I'll close this and add a new request.

**Comment by bdech** [comment]
@mchristiansonVA , yes please fill out a new request. You can use this [template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=external-request%2Cplatform-tech-team-support%2Cops-access-request%2Csidekiq-access-request&projects=&template=vetsapi-sidekiq-ui-access.yaml&title=Sidekiq+Admin+UI+access+for+%5Bindividual%5D)
