### ISSUE TITLE
EKS Prod Rollout: Missing Certs and Secrets

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#54539]
**PROBLEM STATEMENT**
A number of endpoints were not functioning properly due to missing and misconfigured certs and secrets. VFS teams could not test.

**ACTION ITEMS FOR PROD**
- [x] Verification script to run via manifest probe
- [x] Manually [run through secrets and certs](https://github.com/department-of-veterans-affairs/va.gov-team/issues/53248)
- [ ] Locust tests (check with VFS teams on their tests)

**Comment by laineymajor** [comment]
This is complete BUT
@RachalCassity to review all certs and secrets again on Monday 4.3... just for another fresh set of eyes on it.

**Comment by RachalCassity** [comment]
Confirmed!

Note: DigiCertTLSRSASHA2562020CA1.crt.pem is not the same but the two certs are valid
