### ISSUE TITLE
Remove breadcrumb from print view

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#54546]
## Description
The navigation breadcrumb isn't needed on the print view. This change removes that breadcrumb from the print view of all lists.

**Current state**

![Screenshot_2023-03-03_at_7_43_49_AM.png](https://images.zenhubusercontent.com/5f7ce3163782a585b910eaf3/d61876ed-0b32-435c-9c55-8dc2fbaba740)

---

## Acceptance Criteria
Background: the `va_online_scheduling_appointment_list` toggle is on

- [ ] Given the print view is open for upcoming, past, or pending appointments 
    - Then the breadcrumb does not display

### Design Assets
All spec copy is FPO. Use copy in copy doc.

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by outerpress** [comment]
@ldelacosta this is ready. 

@Cieramaddox do we have a design spec for the print view of the lists?

**Comment by ldelacosta** [comment]
No design spec is needed.

**Comment by ldelacosta** [comment]
@Cieramaddox @outerpress - this ticket is ready to be tested. Please validate and let us know if you run into issues. Thanks!

**Comment by outerpress** [comment]
Looks great, the bread crumb doesn't show on any of the pages.

**Comment by ldelacosta** [comment]
No new issues reported. Closing out the ticket.
