### ISSUE TITLE
Align same day appointments in print view

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#54549]
## Description
When printing the upcoming or past appointment list, same day appointments aren't aligned.

![Screenshot_2023-03-03_at_8_25_02_AM.png](https://images.zenhubusercontent.com/5f7ce3163782a585b910eaf3/a1d63718-fae1-4159-97a6-63bfb4026ae7)

---

## Acceptance Criteria
Background: the `va_online_scheduling_appointment_list` toggle is on

 - [ ] Given a print view for upcoming appointments
   - Times are aligned on same-day appointments similarly to the web view

### Design Assets
All spec copy is FPO. Use copy in copy doc.

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by outerpress** [comment]
@ldelacosta looks great, this is good to go

**Comment by ldelacosta** [comment]
No issues reported. Closing out the ticket.
