### ISSUE TITLE
Pending appointments content changes

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#54544]
## Description
Product and Design team are looking to update the appointment list to help the Veteran better understand the details for their appointment. We will need to make modification to the pending request view in VAOS. 

---

## Acceptance Criteria
Background: the `va_online_scheduling_appointment_list` toggle is on

 - [ ] For all changes:
    - Page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/homepage.md#pending-1) 
    - Page design matches the [design spec](https://www.figma.com/file/JpGM8LGBCqAlL8qh3DmFk8/Home-Page-Redesign?node-id=2206%3A58279&t=yxOF8gc6pgD6bPeo-4)
         - All changes are for all screen sizes (mobile, tablet, and desktop)

- [ ] The columns show in the following order for pending and canceled requests
    - The first column displays the requested type of care
    - The second column displays the preferred modality
    - For VA appointments, the third column displays the selected location
    - For CC appointments, the third column displays the preferred provider
        - For CC appointments, if no provider has been selected, that column is blank

- [ ] Type of care shows for  pending and canceled community care requests
    - And the content of the type of care column is bold

- [ ] Add a period `.` after the description under the canceled appointments section ("These appointment requests have been canceled.")

### Design Assets
All spec copy is FPO. Use copy in copy doc.
[Design spec](https://www.figma.com/file/JpGM8LGBCqAlL8qh3DmFk8/Home-Page-Redesign?node-id=2206%3A58279&t=yxOF8gc6pgD6bPeo-4)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by outerpress** [comment]
@ldelacosta could you add the background and copy docs link?

@Cieramaddox the desktop spec looks good, tablet and mobile just need to be updated to match

**Comment by outerpress** [comment]
@Cieramaddox m/t/d specs all look good

**Comment by outerpress** [comment]
@Cieramaddox m/t/d specs all look good

**Comment by ldelacosta** [comment]
@outerpress @Cieramaddox - copy doc has been updated. Thanks.

**Comment by ldelacosta** [comment]
@outerpress @Cieramaddox - this ticket is ready to be validated. Please let us know if you have any issues. Thanks!

**Comment by outerpress** [comment]
@vbahinwillit @ldelacosta Looks like canceled requests aren't showing correctly. They should use the same pattern as pending requests (which look good).

![Screenshot 2023-03-23 at 1.22.51 PM.png](https://images.zenhubusercontent.com/5f7ce3163782a585b910eaf3/57d504a7-f2a4-4c74-9214-181424b1080c)

**Comment by ldelacosta** [comment]
@vbahinwillit - could you review Peter's comment and advise?

**Comment by vbahinwillit** [comment]
@ldelacosta - Thanks for the reminder.
@outerpress - I can make this change but it looks like the design doc needs to be updated for canceled request. If I'm looking in the wrong place, let me know. Thanks.

**Comment by outerpress** [comment]
Looks great @vbahinwillit ! @ldelacosta confirming this is good to go

**Comment by ldelacosta** [comment]
No new issues. Closing out the ticket.
