### ISSUE TITLE
Show ATLAS facility address for ATLAS appointments

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#54559]
## Description
- We don't have facility name for ATLAS appointments
- The facility address will help users understand how to attend those appointments

---

## Acceptance Criteria
Background: the `va_online_scheduling_appointment_list ` toggle is on

 - [ ] Given an upcoming or past ATLAS appointment 
   -  Then the modality column lists the ATLAS facility address 
    -  And page content matches the [copy doc](#) 
    - And page design matches the [design spec](https://www.figma.com/file/JpGM8LGBCqAlL8qh3DmFk8/Home-Page-Redesign?node-id=1194%3A66663&t=wE7tYreOagvBp6rd-4)

### Design Assets
All spec copy is FPO. Use copy in copy doc.

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by ldelacosta** [comment]
@outerpress @Cieramaddox - this is ready to be validated. Please let us know if you have any issues. Thanks!

**Comment by outerpress** [comment]
@ldelacosta I see the address showing up for ATLAS facilities, so this one is good to go

![Screenshot 2023-03-22 at 2.46.47 PM.png](https://images.zenhubusercontent.com/5f7ce3163782a585b910eaf3/ab637548-3457-4d1d-9567-f5e048253b57)

**Comment by ldelacosta** [comment]
No issues reported. Closing out the ticket.
