### ISSUE TITLE
AWS S3 Bucket Access Request

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#54555]
AWS Username: Curt.Bonade
email: curt.bonade@oddball.io

Requesting access to the s3 bucket `vetsgov-website-builds-s3-upload`. Need the ability to view files in the bucket, as well as being able to copy files from the bucket to my local machine for use in testing.

This request is in process in this PR: https://github.com/department-of-veterans-affairs/devops/pull/12636 . Ticket made for documentation purposes at Clint's request as no ticket for the access existed.

**Comment by little-oddball** [comment]
Looks merged here:

https://github.com/department-of-veterans-affairs/devops/pull/12636
