### ISSUE TITLE
Route-based PROD rollout plan

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#54557]
**PROBLEM STATEMENT:**
After completing the staging rollout to EKS, TT1 realized that the weighted rollout was not ideal. Weighing the traffic between BRD and EKS created inconsistencies, making it more challenging to solve major issues. In retrospect, we should have dialed up EKS traffic much faster. 

**PRODUCTION APPROACH:**
Tech Team 1 will complete a route-based rollout for EKS to production ON APRIL 4TH AT 9AM ET.
Goals:
1. Minimize impact to Veterans.
2. With an iterative release, we will minimize impact to VFS teams. 
3. Tech Team 1 can manage the majority of issues that arise from the route-based rollout, with minimal intervention from the Platform Communities of Practice.

**ORDER OF ROLLOUT:**
Listed below are the routes that will be used in initial rollout of EKS in production. Once all major issues are resolved, and 80% of tickets are closed, we will move the next route to EKS. 
1. Search
***Proposing Facilities Locator as second (high traffic, lower impact)
2. EVSS
3. BGS
4. Mobile
5. Modules
6. VFS teams/apps (1st volunteer for the Benefits Team)
7. OPEN TO ALL

**ROUTES, APIs, & METRICS:**
1. SEARCH
- Datadog [metrics](https://vagov.ddog-gov.com/dashboard/t29-k8v-ctv/vets-api-dashboard?from_ts=1677874084040&to_ts=1678478884040&live=true) on the Search API

**COMMUNICATION (ensure consistent with [communication guidelines](https://vfs.atlassian.net/wiki/spaces/PMCP/pages/2317647873/Change+Communication+Guide))**
**Announcement for VFS Teams**
#eks-migration-support
#vfs-all-teams
#vfs-change-announcements

Focusing on reducing the interruption to our end users, Tech Team 1 will be completing a route-based rollout to **migrate vets-api to EKS in PRODUCTION.** With this approach, we hope to:
a. Minimize impact to Veterans.
b. With an iterative release, continuously reduce the impact to VFS teams. 
c. Internally manage (Tech Team 1) the majority of issues that arise from the route-based rollout, with minimal intervention from the Platform Communities of Practice.

**On Tuesday, April 4th, we will begin the route-based of vets-api with EKS to PRODUCTION!**
We will begin with the following routes, in the order below, and will only proceed to new routes when ALL major incidents are resolved + 80% of issues are closed.
1. Search
2. EVSS
3. BGS
4. Mobile
*After the above, we will move to modules, and then VFS teams (starting with volunteers).

---
**RISKS & Notes**
- Reduce touchpoints with revproxy
- Some revproxy configs are shared between environments, so thats something else to note about route based changes. Unless you specify to conditionally route based on an environment, you may unintentionally enable header based routing in an environment that doesn't need/want it.
- Only one deployment window in prod for revproxy [Wednesdays at 4pm ET]
- Potential for breaking down the engine x component? What would this look like?
- Need Lighthouse to point to Traefik rather than BRD
---

**Comment by laineymajor** [comment]
**Questions**

1. What are the different route options?
a. **there is a very low impact search endpoint that could be a good candidate**
b. we have some routes that go to the ASG (auto scaling group)
      *we have some current EVSS and BGS that go to routes and possibly mobile (we need to make sure these are decently isolated, and not high impact)
d. then focus on the modules
e. Ask for VFS team volunteers
f. open the flood gates (YIKES)

2. Need full list of routes per app/products/teams
3. Determine which route is the most isolated for the MVP rollout (search)
4. Which route(s) are next? (see above list)


Notes:
- stay with route until 80% of issues are resolved, then move to next route (exception: all major issues need to be resolved)
- which order should we rollout the routes
- what metrics would be good to include in a [dashboard](https://vagov.ddog-gov.com/apm/services/vets-api/operations/rack.request/resources?env=production&resources=qson%3A%28data%3A%28visible%3A%21t%2Csearch%3ASearchController%2523index%2Chits%3A%28selected%3Atotal%29%2Cerrors%3A%28selected%3Atotal%29%2Clatency%3A%28selected%3Ap99%29%2CtopN%3A%215%2CselectedResourceID%3A72b7d62abdbc2323%29%2Cversion%3A%210%29&summary=qson%3A%28data%3A%28visible%3A%21t%2Cerrors%3A%28selected%3Acount%29%2Chits%3A%28selected%3Acount%29%2Clatency%3A%28selected%3Alatency%2Cslot%3A%28agg%3A75%29%2Cdistribution%3A%28isLogScale%3A%21f%29%29%2Csublayer%3A%28slot%3A%28layers%3Aservice%29%2Cselected%3Apercentage%29%29%2Cversion%3A%211%29&topGraphs=latency%3Alatency%2CbreakdownAs%3Apercentage%2Cerrors%3Acount%2Chits%3Acount&start=1677858370963&end=1678463170963&paused=true) so we can effectively monitor the routes being rolled out
- https://vagov.ddog-gov.com/dashboard/t29-k8v-ctv/vets-api-dashboard?from_ts=1677874084040&to_ts=1678478884040&live=true


Notes:
- the fewer times we have to touch revproxy, the better
- I personally would like to even break nginx_component to each one (at least how I envisioned for bulkhead)
- one deployment window in prod for revproxy (otherwise need to do a OOB request);  when is this time? 4pm W only
- can we break down the engine x component
- workers rollout... planning
- need lighthouse to point to traefik rather than BRD

**Comment by laineymajor** [comment]
Prep route the day before rollout
Rollout at 9am (before busy time); allows a couple hours to monitor before peak traffic time

**Comment by laineymajor** [comment]
Updated plan with day/time of search rollout

**Comment by LindseySaari** [comment]
## Currently weekly Traffic for BGS & EVSS routes

#### (v0|v1)/debts 

![Screenshot 2023-03-28 at 9.48.09 AM.png](https://images.zenhubusercontent.com/5d4836dda95c51615db9bdc9/ef33ab32-e63d-4c53-a0f5-ab36a9552d66)

#### (v0|v1)/debt_letters 
(not seeing info for this)

#### (v0|v1)/profile/ch33_bank_accounts
![Screenshot 2023-03-28 at 9.50.53 AM.png](https://images.zenhubusercontent.com/5d4836dda95c51615db9bdc9/b12c1e40-db25-4f96-b09e-465ef5359d5e)

#### (v0|v1)/profile/payment_history
![Screenshot 2023-03-28 at 9.51.32 AM.png](https://images.zenhubusercontent.com/5d4836dda95c51615db9bdc9/71ed4565-bf9c-4e9e-bbcc-077c71d07a52)

**Comment by LindseySaari** [comment]
#### Currently weekly Traffic for Mobile routes:

#### /mobile/v0/disability-rating
![Screenshot 2023-03-28 at 9.55.29 AM.png](https://images.zenhubusercontent.com/5d4836dda95c51615db9bdc9/19348cec-00f6-4e06-b312-0fa35a8d3023)

#### /mobile/v0/payment-history
![Screenshot 2023-03-28 at 9.54.48 AM.png](https://images.zenhubusercontent.com/5d4836dda95c51615db9bdc9/fe6d3167-4e5d-4fa7-95ff-0dce2d6a0b94)

#### /mobile/v0/user
![Screenshot 2023-03-28 at 9.55.11 AM.png](https://images.zenhubusercontent.com/5d4836dda95c51615db9bdc9/29b167cb-b37c-4fea-9737-770e62028cf2)

**Comment by LindseySaari** [comment]
@laineymajor Lets add Lighthouse to the route based rollout too. We will wait to hear back from Gabriel from Lighthouse on a list of routes

**Comment by LindseySaari** [comment]
A synthetic test for the search endpoint has been configured here: https://vagov.ddog-gov.com/synthetics/details/ywf-tw7-tzx?from_ts=1680181400394&to_ts=1680185000394&live=true

**Comment by LindseySaari** [comment]
I created an ownership rule around the /v0/search endpoint for TT1 and created a specific [#platform-tt1 team in Sentry as well](http://sentry.vfs.va.gov/settings/vsp/teams/platform-tt1/members/)

![Screenshot 2023-03-30 at 10.12.36 AM.png](https://images.zenhubusercontent.com/5d4836dda95c51615db9bdc9/9e1de683-cf0b-4ab4-9468-04792a0abca1)

**Comment by laineymajor** [comment]
@LindseySaari 
- Added lighthouse to route-based rollout
- Added the synthetic test for the search endpoint to our search rollout epic
- Added the APM board to the search epic
- Added the ownership rule to the search epic

**Comment by LindseySaari** [comment]
Let's also monitor [the breakers char](https://vagov.ddog-gov.com/dashboard/znd-bmt-vby/vets-api-breakers?from_ts=1680188762331&to_ts=1680192362331&live=true)t for any issues with fwdproxy and the API call to search.gov

**Comment by LindseySaari** [comment]
@laineymajor Let's also specifically call out the identity related routes and sync with that team about the rollout
