### ISSUE TITLE
AWS access for Raina Huerta

### ISSUE THREAD

**Issue by rd-huerta** [department-of-veterans-affairs/va.gov-team#54554]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Raina Huerta

### Your Email

raina.huerta@va.gov

### Team, Role, and Company of the target individual

Virtual Agent Chatbot, Software Developer, Thoughtworks

### Product Manager (PM) name and email

Ian Santarinala ian.santarinala@thoughtworks.com

### Product Owner (PO) name and email

Luciana Morais Luciana.Morais@va.gov

### Desired AWS Access

I need access to an EKS dev instance/pod so I can run queries in rails console

### Access Expiration

ongoing 

### Additional Notes

I need this access because we are adding test users to the `vets-api-mockdata` repo and we need to query the MPI using rails console

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by BillChapmanUSDS** [comment]
I approve dev access, but need better justification for production (I can approve 3 months) , I also need eqip date added to this thread. Thanks.

**Comment by little-oddball** [comment]
@rd-huerta - please see @BillChapmanUSDS comments above. Thank you!

**Comment by rd-huerta** [comment]
Hi, @BillChapmanUSDS. I do not need production access, but can you add staging access? My eQip date: 10/27/2022

**Comment by considerable** [comment]
@rd-huerta access was added back in 2022 - https://github.com/department-of-veterans-affairs/devops/pull/12300
and is still active, i.e. last successful login was recorded 16 days ago on March 20th. 
In other words, the account looks like it is in good standing. May we close the tkt?

**Comment by considerable** [comment]
@rd-huerta we don't have a staging access group. If you can provide a name of another user that has the kind of access you need, we can duplicate the access.

**Comment by considerable** [comment]
@rd-huerta you have prod access for 3 months that must let you do the work on staging, closing the tkt.

**Comment by rmtolmach** [comment]
@considerable I don't think AWS access is what is being asked for here. 
> I need access to an EKS dev instance/pod so I can run queries in rails console

And then:
> I do not need production access, but can you add staging access? 

So Raina needs dev and staging access in EKS, which is the Argo request form.

**Comment by rmtolmach** [comment]
@rd-huerta, I filled out the correct request form on your behalf: https://github.com/department-of-veterans-affairs/va.gov-team/issues/56477. Sorry for the confusion, it's a new process!

@considerable you can close the PR you opened for this.

**Comment by rd-huerta** [comment]
@rmtolmach Thanks for the clarification and assistance!
