### ISSUE TITLE
Enable EFS Provisioning in Dev VPC

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#54561]
# Description
In pursuit of a more performant and feature rich preview environment, Tech Team 4 would like to use EFS to create a persistent volume that stores cached builds of `content-build`. 

# Acceptance Criteria
- [ ] Tech team 4 is able to create an EFS file system that will be used to hold versions of `content-build`
- [ ] Tech team 4 is able to write content-builds to a persistent volume in an EFS file system object from GHA
- [ ] Preview environments in the dev VPC are able to mount the volume

**Comment by rmtolmach** [comment]
Tim Cosgrove: `content-build` currently pushes a cached version of itself _somewhere_ for Review Instances. They package up the build and pass it to an s3 bucket. [This is where it's currently happening](https://github.com/department-of-veterans-affairs/content-build/blob/main/.github/workflows/content-release.yml#L365)
```yaml
      - name: Upload build
        run: aws s3 cp ${{ env.BUILDTYPE }}.tar.bz2 s3://vetsgov-website-builds-s3-upload/content-build/${{needs.validate-build-status.outputs.REF}}/${{ env.BUILDTYPE }}.tar.bz2 --acl public-read --region us-gov-west-1 --no-progress
```
Preview Envs can grab it from ^^

**Comment by JoeTice** [comment]
Task no longer relevant
