### ISSUE TITLE
VFS Docs: Tools and Debugging

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#54577]
**Problem Statement**
VFS facing documentation will be out-of-date once the vets-api migration to EKS is complete. Tech Team 1 will update all relevant VFS facing documentation to reflect EKS infrastructure.

**Issue Description**
The team has completed a documentation audit of VFS facing documents. [Attached](https://docs.google.com/spreadsheets/d/1rTacvOYTXh3jMehzlfd0gGMlhiQOqu_Re-kKrGUVY80/edit#gid=0) is an overall list of documents that require an update due to the EKS migration. These updates will be summarized in tickets, and attached to this epic.

---
**Tasks**
- [x] Update Tools and Debugging pages of the backend developer section with EKS updates https://depo-platform-documentation.scrollhelp.site/developer-docs/tools-and-debugging
1. stasd metrics - AFTER PROD ROLLOUT
2. breakers outages - Created [new document ](https://vfs.atlassian.net/wiki/spaces/pilot/pages/2571173889/Breakers+Outages+for+EKS+Environments)for EKS environments
3. triaging api errors
4. aws shell access - DELETE AFTER PROD ROLLOUT - asked in [slack thread](https://dsva.slack.com/archives/C04M7T1CZAS/p1679346723398719)

**Acceptance Criteria**
- [ ] Documentation for this section is deployed to platform website.

**Comment by RachalCassity** [comment]
I've been working with Vicky to get these deployed. Should be deployed today, Friday 3/24.
