### ISSUE TITLE
VFS Docs: Platform Dashboards

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#54573]
**Problem Statement**
VFS facing documentation will be out-of-date once the vets-api migration to EKS is complete. Tech Team 1 will update all relevant VFS facing documentation to reflect EKS infrastructure.

**Issue Description**
The team has completed a documentation audit of VFS facing documents. [Attached](https://docs.google.com/spreadsheets/d/1rTacvOYTXh3jMehzlfd0gGMlhiQOqu_Re-kKrGUVY80/edit#gid=0) is an overall list of documents that require an update due to the EKS migration. These updates will be summarized in tickets, and attached to this epic.

---
**Tasks**
- [ ] Update EKS pages of the Platform Dashboards section with EKS updates https://depo-platform-documentation.scrollhelp.site/developer-docs/platform-dashboards-in-datadog

**Acceptance Criteria**
- [ ] Documentation for this section is deployed to platform website.

**Comment by laineymajor** [comment]
@considerable please complete by NO LATER than 3pm ET 3.28. Notify Lainey via slack upon completion. This is the final documentation item remaining.

**Comment by considerable** [comment]
added useful dashboards
