### ISSUE TITLE
VFS Docs: Running vets-api locally

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#54576]
**Problem Statement**
VFS facing documentation will be out-of-date once the vets-api migration to EKS is complete. Tech Team 1 will update all relevant VFS facing documentation to reflect EKS infrastructure.

**Issue Description**
The team has completed a documentation audit of VFS facing documents. [Attached](https://docs.google.com/spreadsheets/d/1rTacvOYTXh3jMehzlfd0gGMlhiQOqu_Re-kKrGUVY80/edit#gid=0) is an overall list of documents that require an update due to the EKS migration. These updates will be summarized in tickets, and attached to this epic.

---
**Tasks**
- [x] Update Running Vets-API Locally pages of the backend developer section with EKS updates https://depo-platform-documentation.scrollhelp.site/developer-docs/running-vets-api-locally
1. backend
2. base setup
3. developer setup
4. native setup
5. development
6. documentation
7. settings
8. running the app natively

**Acceptance Criteria**
- [ ] Documentation for this section is deployed to platform website.

**Comment by LindseySaari** [comment]
I can work on the updates for these pages on Monday. This will take up 8/15 allotted spaces for the 15/15 split between Monday-Tuesday. cc @laineymajor
