### ISSUE TITLE
VFS Docs: EKS

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#54575]
**Problem Statement**
VFS facing documentation will be out-of-date once the vets-api migration to EKS is complete. Tech Team 1 will update all relevant VFS facing documentation to reflect EKS infrastructure.

**Issue Description**
The team has completed a documentation audit of VFS facing documents. [Attached](https://docs.google.com/spreadsheets/d/1rTacvOYTXh3jMehzlfd0gGMlhiQOqu_Re-kKrGUVY80/edit#gid=0) is an overall list of documents that require an update due to the EKS migration. These updates will be summarized in tickets, and attached to this epic.

---
**Tasks**
- [ ] Update EKS pages of the backend developer section with EKS updates https://depo-platform-documentation.scrollhelp.site/developer-docs/eks
1. Vets-API on EKS
2. EKS endpoint testing

**Acceptance Criteria**
- [ ] Documentation for this section is deployed to platform website.

**Comment by LindseySaari** [comment]
The EKS docs are completed.
