### ISSUE TITLE
VFS Docs: External Integrations

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#54574]
**Problem Statement**
VFS facing documentation will be out-of-date once the vets-api migration to EKS is complete. Tech Team 1 will update all relevant VFS facing documentation to reflect EKS infrastructure.

**Issue Description**
The team has completed a documentation audit of VFS facing documents. [Attached](https://docs.google.com/spreadsheets/d/1rTacvOYTXh3jMehzlfd0gGMlhiQOqu_Re-kKrGUVY80/edit#gid=0) is an overall list of documents that require an update due to the EKS migration. These updates will be summarized in tickets, and attached to this epic.

---
**Tasks**

Following: 
-  [Platform website guidelines](https://vfs.atlassian.net/wiki/spaces/AP/pages/1474461889/Create+a+new+Platform+website+documentation+page)
- [Edit Platform website documentation](https://vfs.atlassian.net/wiki/spaces/AP/pages/2046558209/Edit+Platform+website+documentation)

Perform: 
- [x] Update External Integrations pages of the Integrations section with EKS updates https://depo-platform-documentation.scrollhelp.site/developer-docs/external-integrations
1. External service integration
2. search.gov
3. CARMA

**Acceptance Criteria**
- [x] Documentation for this section is deployed to platform website.

**Comment by RachalCassity** [comment]
New documentation was deployed.
