### ISSUE TITLE
[Design] Migrate unified experience wireframes to 375 width

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#54581]
## Description 

Migrate all unified experience wireframes to 375 artboard in sketch. I.e., to reduce risk of issues when viewing wireframes on small screens. 

This is design debt, but would make sense to do pretty soon as we're just about completing the core set of unified experience wireframes. Ideally, these can be converted to 375, and then we make changes moving forward in this new artboard. 

## Tasks

- [x] Convert wireframes to 375 

## AC

- [x] New sketch page is available at 375 width 

## Deliverable
The artboards are now converted to 375 widths for the [Unified Experience - Pre-Check-in and Check-in UXUI](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec#Version) page of the sketch cloud.

**Comment by zach-park** [comment]
@benbrasso-agile6, @cgednalske , @ytsaoca ing, @kellysmith1008, the artboards are now converted to 375 widths.

**Comment by benbrasso-agile6** [comment]
Nice, Zach

**Comment by loripusey** [comment]
does the above comment count as a validation? can this be closed?

**Comment by benbrasso-agile6** [comment]
Yes, all were wires were converted
