### ISSUE TITLE
Profile page scrolls when trying to submit invalid profile data

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#5458]
When using the new Address Form that uses a SchemaForm component, if you try to submit the form while there are errors on the form, the main profile page that sits behind the edit modal scrolls a bit on each submission attempt. This is purely a visual defect with not impact on functionality but should be fixed before release.

![validation-scroll](https://user-images.githubusercontent.com/20728956/73770790-e50c9c80-4731-11ea-9fbb-4031a6828977.gif)

**Comment by erikphansen** [comment]
@mshea0606 or @Samara-Strauss can you please validate that this has been fixed on staging?

**Comment by Samara-Strauss** [comment]
Validated! Scrolling issue is fixed. Closing.
