### ISSUE TITLE
[Call Centers] WHH Retro

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#546]
## User Story
As a _____, I need _____ so I can _____.

## Goal
Create documentation and readout of training. Create next steps/tasks.

## Acceptance Criteria
- [x] _What needs to happen or be created?_

## Definition of Done
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by clantosswett** [comment]
WHH synthesis is complete. The readout of the training can be found here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/Platform/Teams/Analytics%20and%20Insights/Research/WHH-visit-synthesis.md

And the results of the agent feedback form can be found here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/Platform/Teams/Analytics%20and%20Insights/Research/WHH%20July%2016-18%20Training%20Feedback%20Form%20Results.pdf
