### ISSUE TITLE
[FE] Add GA event on check in now primary button click

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#54608]
## Description 

I had talked to Brian about this in relation to https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/51109

Can we add a custom GA event on our "check in now" primary button click? 

We'd want to make sure that it's firing from both the appointment list page AND the detail pages, when it's present. The GA event values should be the same. 

Also, we want to track clicks separately for the VAOS feature. So, the events should be something similar to: 

nav-check-in-check-in-check-in-now-VAOS-design
nav-check-in-check-in-check-in-now-non-VAOS-design

## AC

- [ ] GA events are set up on appointment list page and details page for "check in now" primary button click

**Comment by acrollet** [comment]
I pulled this into the current sprint based on our PL and threw an estimate on, @wullaski can you adjust if you don't agree?

cc @loripusey @sarahknoppA6

**Comment by benbrasso-agile6** [comment]
@wullaski I validate this one. feel free to close
