### ISSUE TITLE
Remove Sandbox BRD workers + autodeploy jobs

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#54615]
## Description

100% of Sandbox traffic is going to EKS. BRD sandbox workers and servers are still up and running though. We should remove the current BRD related workers and disable the sandbox autodeploy job to not deploy workers. We need to accurately test Sidekiq HPA and cannot do so if BRD workers are still running.

Tasks:
- [x] Disable Sandbox autodeploy job for workers and servers - @LindseySaari 
- [x] Remove current running sandbox BRD workers - @rmtolmach or @considerable 
- [x] Remove current running sandbox BRD servers - @rmtolmach or @considerable

**Comment by LindseySaari** [comment]
[PR opened here](https://github.com/department-of-veterans-affairs/devops/pull/12648) to remove the autodeploy for sandbox BRD server and worker

Next steps will need to be done by someone with Ops perms. 
In the meantime, Rachal can use dev or staging for the sidekiq testing. Sandbox will be unblocked once someone completes the next steps in the ticket

**Comment by rmtolmach** [comment]
For checkboxes 2 and 3, are you referring to these in EC2?
![image](https://user-images.githubusercontent.com/10993987/223472991-2caa5ffd-62c4-425e-8c0a-7a461a2533ef.png)

Link: https://console.amazonaws-us-gov.com/ec2/home?region=us-gov-west-1#Instances:search=:sandbox-vets-api;v=3;$case=tags:true%5C,client:false;$regex=tags:false%5C,client:false

In your PR you mention decreasing the capacity of the ASGs to 0. Would we want to delete the ASGs (and launch templates) altogether? (seems like we would want to do that eventually, but idk if now is the right time.)
![image](https://user-images.githubusercontent.com/10993987/223475848-8a138ab5-453c-4ce5-afbd-fe0c31d370e8.png)

Link: https://console.amazonaws-us-gov.com/ec2/home?region=us-gov-west-1#AutoScalingGroups:

**Comment by LindseySaari** [comment]
@rmtolmach Yes, I believe so and then you may need to adjust the min/max to 0. Check with Devops please :) I'm not super confident on my answer, but those look to be the corrrect ASGs

**Comment by LindseySaari** [comment]
[PR Merged](https://github.com/department-of-veterans-affairs/devops/pull/12648) ✅

**Comment by rmtolmach** [comment]
> it looks like staging BRD workers are up again

@LindseySaari Has the deprecation of brd staging happened? I see https://github.com/department-of-veterans-affairs/va.gov-team/issues/53611 (which is part of the BRD staging deprecation epic https://github.com/department-of-veterans-affairs/va.gov-team/issues/53607). We did this in `dev`: https://github.com/department-of-veterans-affairs/va.gov-team/issues/52437

I'm going to focus on the Sandbox worker and server for this ticket, just so I can keep things straight

**Comment by rmtolmach** [comment]
Worker ASG capacity set to 0:
<img width="596" alt="image" src="https://user-images.githubusercontent.com/10993987/223762945-34c8b1d5-8fc0-481e-98ce-7baa78987407.png">

Server ASG capacity set to 0:
<img width="602" alt="image" src="https://user-images.githubusercontent.com/10993987/223763033-c3a1976d-bfa0-4c50-a7cd-aeda4d9c1afb.png">


Terminated the sandbox worker and server instances:
<img width="746" alt="image" src="https://user-images.githubusercontent.com/10993987/223763809-3658f798-793f-4e1b-b251-f7f15d9c4cb1.png">

**Comment by rmtolmach** [comment]
I think ^^ that should do it, but I will check back later today or tomorrow to verify that nothing else is spinning up sandbox instances.

**Comment by LindseySaari** [comment]
An outage occurred on the Lighthouse side after we removed the BRD servers. It's believed to be a Kong routing issue where the config is still pointing at the BRD load balancer instead of EKS ingress/traefik. @golavarr-va  is checking with the API Gateway folks. [Thread here](https://dsva.slack.com/archives/CBU0KDSB1/p1678291528937009). The removal of the servers/workers is blocked until we hear back

**Comment by laineymajor** [comment]
As we are currently blocked, and have a full load due to support, I'm going to go ahead and carry this over to next sprint.

**Comment by laineymajor** [comment]
API gateway team deployed sandbox change.
Potentially unblocked.

@LindseySaari to share thread.

**Comment by laineymajor** [comment]
Need further convo with bill before deleting anything

**Comment by LindseySaari** [comment]
@oseasmoran73 Tore down the sandbox workers today as they were causing a strange condition because BRD sandbox workers didn't have up to date images.

**Comment by oseasmoran73** [comment]
[Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/55654#event-8831825390) for sandbox removal
