### ISSUE TITLE
Prometheus consulting for Insights team

### ISSUE THREAD

**Issue by jholton** [department-of-veterans-affairs/va.gov-team#5461]
## Background

@thilton-oddball and @Clark-W-Griswold reached out to the BE Tools team to discuss some specifics about Prometheus in regards to adding metrics from GitHub API results.

https://dsva.slack.com/archives/CQHBJ5U06/p1580835705176100

I provided an hour's worth of support in the form of a Slack call and some investigation/review. Future consultation may be a possibility.

**Comment by kfrz** [comment]
Probably want to send them to the utility prometheus:

http://prometheus-utility.vfs.va.gov:9090/prometheus/alerts

**Comment by joanneesteban** [comment]
@kfrz @jholton Hi! Is there an action that Insights needs to take on this?
