### ISSUE TITLE
Use Standard RPC to Link Consult.

### ISSUE THREAD

**Issue by shanemelliott** [department-of-veterans-affairs/va.gov-team#54652]
When using DDR to link consult, it cannot be unlinked.  Ned to move to using the SDEC APP ADD option to link the consult when making appts for OSM. 

- [ ] Consult linked using SDEC APP ADD

- [ ] Tested in Staging.

**Comment by shanemelliott** [comment]
Documentation for SEC APP ADD: https://vivian.worldvista.org/vivian-data/8994/8994-3562.html

The detail on how the consult is linked is in the SDAPTYP (15) piece
`SDAPTYP
PARAMETER TYPE:   LITERAL
REQUIRED:   YES
SEQUENCE NUMBER:   15
DESCRIPTION:   
SDAPTYP - (required) Appt Request type - variable pointer pointer to
                     one of these files:
  SD WAIT LIST - E|<WL IEN> E|123
  REQUEST/CONSULTATION - C|<CONSULT IEN> C|123
  RECALL REMINDERS - R|^<RECALL IEN> R|123`

Looking at: https://vivian.worldvista.org/dox/Routine_SDEC07_source.html

`. S:$P(SDAPTYP,"|",1)="C" S**DECC("CON")=$P(SDAPTYP,"|",2)**
 . S SDECERR=$$MAKE^SDEC07B(.SDECC)
 . Q:SDECERR
 . D AVUPDT^SDEC07C(SDCL,SDECSTART,SDECLEN)`

Leads to:
https://vivian.worldvista.org/dox/Routine_SDEC07B_source.html

`; Make call using: S ERR=$$MAKE^SDEC07B(.ARRAY)
 ;
 ; Input Array -
 ; BSDR("PAT") = ien of patient in file 2
 ; BSDR("CLN") = ien of clinic in file 44
 ; BSDR("TYP") = C&P if appointment type is C&P, 3 for scheduled appts, 4 for walkins
 ; BSDR("COL") = collateral if appointment type is COLLATERAL OF VET.
 ; BSDR("APT") = Appointment type pointer to APPOINTMENT TYPE file 409.1
 ; BSDR("ADT") = appointment date and time
 ; BSDR("LEN") = appointment length in minutes (5-120)
 ; BSDR("OI")  = reason for appt - up to 150 characters
 ; BSDR("USR") = user who made appt
 ; BSDR("RES") = resource pointer to SDEC RESOURCE ^SDEC(409.831,
 ; BSDR("MTR") = MTRC flag (multiple appointments) 0=False (default)  1=True
 ; BSDR("DDT") = Desired Date of Appt in fm format
 ; BSDR("REQ") = Requested By - valid values are 1=PROVIDER  2=PATIENT or ""
 ; BSDR("LAB") = LAB date/time in fm format
 ; BSDR("EKG") = EKG date/time in fm format
 ; BSDR("XRA") = XRAY date/time in fm format
 **; BSDR("CON") = Consult link - pointer to file 123** <-------------------------------
 ; BSDR("OVB") = overbook flag - 1=yes, this is an overbook
 ; BSDR("ELG") = Patient Eligibilty`

**Comment by shanemelliott** [comment]
looks like h it should work:
 I $G(BSDR("CON")) D
 .N SDFDA,SDIEN
 .S SDIEN=+Y
 .Q:SDIEN=-1
 .S SDFDA(44.003,SDIEN_","_BSDR("ADT")_","_BSDR("CLN")_",",688)=BSDR("CON")
 .D UPDATE^DIE("","SDFDA")

**Comment by lindsay-insco** [comment]
Implemented fix
