### ISSUE TITLE
Contact Attemp Messages not reading from SQL Table

### ISSUE THREAD

**Issue by shanemelliott** [department-of-veterans-affairs/va.gov-team#54654]
When changing the contact attempt messages in the following table, the template is not used for contact attempts

[Clinical].[dbo].[smsPatientTrackingMessageTemplate]:

--  update [Clinical_Staging].[dbo].[smsPatientTrackingMessageTemplate]
--  set checkinContactAttemptMessage = 'Your VA Care team is trying to contact you about today’s appointment. Please call %VA_PHONE%. Please do not text in reply to this message.'
--  Please call your VA Care team

- Entered appt for ZZTest, ONe, 
- checked in, 
- sent message to confirm it is not working. 
- looked up record in Mongo

 {
    _id: 6406770c35a3e45020b440d2,
    className: 'gov.va.med.lom.vetext.model.PatientTracking',
    date: 3230306,
    divisionNo: '605',
    clinicName: 'LOM ACC TRAINING CLINIC ',
    physicalLocation: '',
    fmApptDatetime: 3230306.153,
    facility: '',
    patientFriendlyName: 'TRAINING CLINIC',
    patientName: 'ZZTEST,ONE',
    patientDfn: '10108320',
    patientLast4: '0049',
    cellPhone: '9094351808',
    homePhone: '9098257084',
    apptLength: 30,
    cancelled: false,
    onsite: false,
    fmOnsiteDatetime: 0,
    patientNotified: true,
    fmNotifiedDatetime: 3230306.152811,
    fmInitialNotifiedDatetime: 3230306.152811,
    defaultNotificationMessage: 'Your provider is ready to see you now.  Please proceed to your 15:30 appointment with TRAINING CLINIC  and check in with the clinic when you arrive.\r\n' +
      '\r\n' +
      'We require all visitors and patients to wear a face mask in the building. \r\n' +
      '\r\n' +
      'Please call 9094351808 if you have questions or need assistance.',
    defaultVirtualAppointmentMessage: 'Your appointment at 15:30 with TRAINING CLINIC is for a virtual visit either by telephone or virtual video.  \r\n' +
      '\r\n' +
      'Please await your providers call for telephone appointment or for virtual video appointments connect to the virtual room using the link emailed by your provider. \r\n' +
      '\r\n' +
      'Please call 9094351808 if you have questions or need assistance.',
    defaultDriveUpAppointmentMessage: 'Please proceed to the designated location for your 15:30 appointment with TRAINING CLINIC drive-up services. \r\n' +
      '\r\n' +
      'We require all patients and visitors to wear a face covering for all appointments. Please be prepared to answer screening questions at the start of your appointment.  \r\n' +
      '\r\n' +
      'If you need further assistance please call 9094351808.\r\n',
    defaultAdHocMessage: 'A Message From VA TRAINING CLINIC:',
    defaultContactAttemptMessage: **'We are trying to contact you. Please call 9094351808. Please do not text in reply to this message.',**
    defaultCallNumberMessage: 'Please call 9094351808 after returning from lab or x-ray. Please do not text in reply to this message.',
    initialNotificationMessage: 'We are trying to contact you. Please call 9094351808. Please do not text in reply to this message.',
    notificationMessage: 'We are trying to contact you. Please call 9094351808. Please do not text in reply to this message.',
    initialNotificationMessageSids: 'null',
    notificationMessageSids: 'null',
    notificationMessageStatuses: '',
    initialNotificationMessageErrors: '',
    notificationMessageErrors: '',
    notifiedByUser: 'ELLIOTT,SHANE',
    initialNotifiedByUser: 'ELLIOTT,SHANE',
    initialNotificationPhoneNumbers: '9094351808',
    notificationPhoneNumbers: '9094351808',
    checkedIn: false,
    fmCheckedInDatetime: 0,
    checkedOut: false,
    fmCheckedOutDatetime: 0,
    alertSent: true,
    unscheduled: false,
    hidden: false,
    stationNo: '605',
    dateCreated: 2023-03-06T23:28:12.370Z,
    version: 2
  }

**Comment by lindsay-insco** [comment]
User error
