### ISSUE TITLE
Extract gem from search module experiment

### ISSUE THREAD

**Issue by johnpaulashenfelter** [department-of-veterans-affairs/va.gov-team#5465]
Let's find out what is *really* involved in taking an existing module and extracting it into a standalone gem.

**Comment by johnpaulashenfelter** [comment]
@erluti has gone through this process for the search API and will create a doc outlining the process, the things that worked well, and problems/issues discovered.

**Comment by erluti** [comment]
Write-up of attempt to extract search as gem:
https://docs.google.com/document/d/1DeuTVAy9yXKfTAo6dBldZAkGzueiJSkIMTpHdRfXK4I/edit?usp=sharing

TLDR: Search is so dependent on existing work, it makes more sense to extract `lib/common` first or rewrite Search.

Relevant repos:
https://github.com/department-of-veterans-affairs/vets-api/tree/be-tools/pb/gemify-search-module
https://github.com/erluti/vets-api-common

**Comment by alexpappasoddball** [comment]
@johnpaulashenfelter need to review
