### ISSUE TITLE
[Bug] Profile - Address Validation - Alert-messages copy incorrect

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#5466]
## What happened?
On [Staging Profile](https://staging.va.gov/profile/) page, when Editing **Mailing Address**:

1. For Overridable, No Suggestions use-case, the "**Please confirm your address**" alert-message ends with "...or choose a suggested address below" but there're no suggestions.
1. For Overridable, No Suggestions use-case, the "**Please add a unit number**" alert-message instruction (at the end) says "...select Continue." but there's no Continue button.
NOTE: The pertinent design-comp screenshot in QA Epic #3948 also exhibits this bug.

## Specs:
- Device: \[This copy-bug is browser-/device-agnostic.]
- Test account: `vets.gov.user+56@gmail.com` \[see credentials [here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv)]

## Steps to Reproduce
1. Go to https://staging.va.gov/profile/ \[Sign in w/ any test-account 56.]
1. Under **Contact information**, tap/click **Edit** next to **Mailing address**.
1. Change the address for each of the 2 use-cases listed above (under **What happened?**), using the pertinent address in [this test-cases table](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/change-address/address-validation/qa-508/test-cases.md).
1. Click **Update** button.
1. Observe each use-case's alert-message copy.

### Screenshots

**Overridable, No Suggestions - Mac Chrome example**
![mac-chrome-overridable-no-suggestions-alert-200205](https://user-images.githubusercontent.com/587583/73869718-10fa5180-4808-11ea-9396-569f87fe4ace.png)

**Overridable, Add Unit# - Mac Chrome example**
![mac-chrome-overridable-add-unit#-alert-200205](https://user-images.githubusercontent.com/587583/73869762-240d2180-4808-11ea-8942-5b26ea68aaa5.png)

## Desired behavior
* For **Overridable, No Suggestions** use-case, alert-message should just end with "...please edit it."
* For **Overridable, Add Unit#** use-case, alert-message instruction should probably\* say "...select Use this address."

\*For Add Unit# use-case, get new copy-specs from Copy Reviewer.

## Acceptance Criteria
\[see **Desired behavior** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by Samara-Strauss** [comment]
Thanks for this! I need to get a little copy help on this and will assign to Erik/Brad when I have that copy.

**Comment by Samara-Strauss** [comment]
@peggygannon these are the copy updates I mentioned on Slack.

**Overridable, No Suggestions - Mac Chrome example**

We need to remove the messaging about the "suggested address" in this case. We've also modified the design so all addresses can override the "invalid" determination, so we may want to add something about selecting the address they entered if it's correct.

![mac-chrome-overridable-no-suggestions-alert-200205](https://user-images.githubusercontent.com/587583/73869718-10fa5180-4808-11ea-9396-569f87fe4ace.png)

**Overridable, Add Unit# - Mac Chrome example**

We changed this design so the button reads "Use this address" if there's only one address to select. The button was previously labeled "Continue" — which is what the copy says — because I wasn't paying close enough attention to this copy when I updated the design. Can we change this copy so it removes the mention of "Continue" and mentions the user should select the address they entered if it's correct?

![mac-chrome-overridable-add-unit#-alert-200205](https://user-images.githubusercontent.com/587583/73869762-240d2180-4808-11ea-8942-5b26ea68aaa5.png)

**Comment by peggygannon** [comment]
Hello, @Samara-Strauss please see updated content recommendations below. Let me know if you have any questions!

**Please confirm your address**
We couldn’t confirm your address with the U.S. Postal Service. Please verify your address so we can save it to your VA profile. If the address you entered isn’t correct, you can edit it. If the address is correct, please select it.

---- 

for the below message, there are two links to edit your address. Should one of them be removed? 

**Please add a unit number**
It looks like your address is missing a unit number. Please [edit your address] to add a unit number. If you don’t have a unit number, and the address you entered below is correct, please select it.

**Comment by Samara-Strauss** [comment]
@peggygannon looks good to me!

@bradl3yC or @erikphansen — when you're ready for this ticket, please update the copy as follows:

**Overridable, No Suggestions - Mac Chrome example**

**Please confirm your address**

We couldn’t confirm your address with the U.S. Postal Service. Please verify your address so we can save it to your VA profile. If the address you entered isn’t correct, you can edit it. If the address is correct, please select it.

![13  Scenario 2: Override; No suggestions](https://user-images.githubusercontent.com/34068740/74037951-572ced80-498d-11ea-8ab1-21fd5c5decd6.png)

**Overridable, Add Unit# - Mac Chrome example**

**Please add a unit number**

It looks like your address is missing a unit number. Please [edit your address] to add a unit number. If you don’t have a unit number, and the address you entered below is correct, please select it. 

![Add missing unit number with override](https://user-images.githubusercontent.com/34068740/74037962-5b590b00-498d-11ea-8703-f6209de56b38.png)

**Comment by Samara-Strauss** [comment]
@bradl3yC I went to validate this because it was in the Validate column, but I'm not seeing the correct copy. Is this on staging yet or were you still waiting for someone to review a PR or something?

**Comment by bradl3yC** [comment]
@Samara-Strauss can you provide more info or screenshots? this has been merged and _should be_ in staging.  Let me verify that it is actually deployed.

**Comment by Samara-Strauss** [comment]
Sure. Here's what I'm seeing — still seeing old/incorrect copy

<img width="457" alt="Screen Shot 2020-02-18 at 4 27 49 PM" src="https://user-images.githubusercontent.com/34068740/74779538-b6331200-526b-11ea-871a-7719b354605f.png">

<img width="472" alt="Screen Shot 2020-02-18 at 4 27 27 PM" src="https://user-images.githubusercontent.com/34068740/74779540-b6cba880-526b-11ea-870e-f49a31331127.png">

**Comment by bradl3yC** [comment]
@Samara-Strauss is the unit number copy wrong? I see what you mean with the first example

**Comment by Samara-Strauss** [comment]
Yes, for unit number, this is what the copy should be:

It looks like your address is missing a unit number. Please [edit your address] to add a unit number. If you don’t have a unit number, and the address you entered below is correct, please select it.

And to confirm, for override/no suggestions, the copy should be:

We couldn’t confirm your address with the U.S. Postal Service. Please verify your address so we can save it to your VA profile. If the address you entered isn’t correct, you can edit it. If the address is correct, please select it.

**Comment by bradl3yC** [comment]
@Samara-Strauss if they have a bad unit number with no suggestions - their only option is to click "Use this address"

**Comment by Samara-Strauss** [comment]
Yes, correct. Not sure if this is what you're suggesting — is there something inaccurate about this copy?

"It looks like your address is missing a unit number. Please [edit your address] to add a unit number. If you don’t have a unit number, and the address you entered below is correct, please select it."

**Comment by bradl3yC** [comment]
@Samara-Strauss I think so - because you cannot select the actual address (there is no radio button) you can only click the Use this address button.  As long as thats what we want, I'm not that opinionated on it.

**Comment by Samara-Strauss** [comment]
Right. I think "select it" means to click "Use this address" in this case, but I see your point.
