### ISSUE TITLE
Central Mail API 

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#54688]
## Description

I received a DM from a developer working with the Central Mail API, which was returning 500 errors.

Additional corresponding slack thread: https://dsva.slack.com/archives/CE4304QPK/p1678213556877299?thread_ts=1678199078.279169&cid=CE4304QPK

## AC
- [ ] documentation is updated https://depo-platform-documentation.scrollhelp.site/developer-docs/central-mail-api
- contact info
- update or verify the URLs that we connect to for each environment

**Comment by LindseySaari** [comment]
I suggested looking at Logs (either Loki or Datadog) and Sentry for corresponding errors.

**Comment by LindseySaari** [comment]
Found some [logs in Loki ](https://grafana.vfs.va.gov/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Loki%20(Staging)%22,%7B%22expr%22:%22%7Bapp%3D%5C%22vets-api-web%5C%22%7D%20%7C%3D%20%5C%22EmmsAPI%2FVADocument%2Fupload%5C%22%22%7D,%7B%22expr%22:%22%22%7D%5D&right=%5B%22now-1h%22,%22now%22,%22Loki%20(Dev)%22,%7B%22expr%22:%22%7Bapp%3D%5C%22vets-api-server%5C%22%7D%20%7C%3D%20%5C%22Warden%5C%22%22%7D,%7B%22expr%22:%22%22%7D%5D) indicating `Breakers failed request`

**Comment by LindseySaari** [comment]
Still working with @gmrabian. I ran `CentralMail::Service.new.upload({'metadata'=>'{"veteranFirstName":"Veteran","veteranLastName":"Surname","fileNumber":"123456789","zipCode":"12345","source":"va.gov","hashV":"44523459e69c3d64939c82dc3fdf6ff04314ff927c09815be79eb52d54420c51","numberAttachments":0,"receiveDt":"2023-03-10 14:2747","numberPages":3,"docType":"10182","businessLine":"VHA"}','document'=>Faraday::UploadIO.new('vha_10_10d-tmp.pdf',Mime[:pdf].to_s,'vha_10_10d')})` in the rails console and command failed. It may be some sort of issue within the code itself. We will wait to test when[ this PR is merged.](https://github.com/department-of-veterans-affairs/vets-api/pull/12051)

**Comment by laineymajor** [comment]
added some AC to this ticket... info needed for ATO

**Comment by laineymajor** [comment]
Still cannot find contacts for this API. Even been working with Erica Robbins on this, and no luck.

**Comment by LindseySaari** [comment]
The team is working through testing this. We should be able to close at the end of the sprint, but I will keep open for another day to see if they have additional feedback.

**Comment by LindseySaari** [comment]
From the dev: "right now we are considering using one of the lighthouse apis instead so i’m not working on it at the moment"

**Comment by LindseySaari** [comment]
The team has chosen to use a lighthouse API instead. Closing this as my support has come to an end
