### ISSUE TITLE
Sidekiq Admin UI Access Request

### ISSUE THREAD

**Issue by FonzMP** [department-of-veterans-affairs/va.gov-team#54696]
#### Access to the Sidekiq Admin UI is managed through a GitHub Teams per environment via the following teams: 
- [Dev](https://github.com/orgs/department-of-veterans-affairs/teams/va-gov-sidekiq-dev)
- [Staging](https://github.com/orgs/department-of-veterans-affairs/teams/va-gov-sidekiq-staging)
- [Sandbox](https://github.com/orgs/department-of-veterans-affairs/teams/va-gov-sidekiq-sandbox)
- [Prod](https://github.com/orgs/department-of-veterans-affairs/teams/va-gov-sidekiq-prod)

_Please provide your GitHub username to be added to that team, along with a reason access is required and which environments you're requesting access to._

- GitHub username: FonzMP
- Reason access is required: Team Dash Production Support - Team Dash runs the Claims API within Lighthouse and we require access to troubleshoot issues and support the Claims API in general.
- Environments requesting access to: All

**Comment by rjohnson2011** [comment]
Access granted to dev, staging, sandbox environments.

Awaiting OCTODE approval for production access.

**Comment by ryan-mcneil** [comment]
@FonzMP You've been granted access to all environments, with access to Production limited to 6 months (policy change after Bill's comment), expiring 11/5/23

**Comment by ryan-mcneil** [comment]
Slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1683305853954699)

**Comment by bdech** [comment]
@FonzMP Your Sidekiq Admin UI Production access has expired. Would you like to request an extension of access?

**Comment by bdech** [comment]
Removing production due to no response. If you would like to request Production access, please fill out a new request.

**Comment by FonzMP** [comment]
@bdech - can you please keep production access here. sorry for the delay, I did not see the notification from the former request, just the update today. my apologies.

**Comment by bdech** [comment]
@FonzMP Your Production access has been extended, limited to 6 months, expiring 05/15/23. Please set a reminder for yourself to return to this ticket one week prior to expiration to request an extension.

**Comment by bdech** [comment]
slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1700079075890319)

**Comment by bdech** [comment]
@FonzMP Your Sidekiq UI Production access has expired.

Would you like to request an extension? You have 72 hours to respond, or your 
access will be revoked and you will need to fill out a new request.

**Comment by bdech** [comment]
@FonzMP Your Sidekiq UI Production access has expired.

Would you like to request an extension? If we don't receive a response by 05/21 your
access will be revoked and you will need to fill out a new request.

**Comment by bdech** [comment]
Production access removed
