### ISSUE TITLE
MHV on VA.gov: Landing Page: UI tweaks

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#54691]
## Tweaks to MHV on VA.gov Landing Page as of 3/7/2023 

[Related Slack thread](https://dsva.slack.com/archives/C04GDQSHD1R/p1678197227872079)

- [x] Cut  logo down by ~50%
- [x] Add a wee bit of space above the h2s in the gray boxes — maybe a [spacing unit](https://design.va.gov/foundation/spacing-units) or so
- [x] "Your VA appointments" should be "Upcoming VA appointments"
- [x] "My medications and allergies" should be "Medications and allergies"
- [x] "Download my medical record" should be "Download medical record (Blue Button)"
- [x] "Pay your copay bill" should be "Pay copay bills"
- [x] "Update my health benefits info" should be "Update health benefits info (10-10EZR)"
- [x] "My health information card" should be "Veteran health information card"

**Comment by dcloud** [comment]
- Updated link texts
- Restricted logo to `max-width: 262px` (measured logo width in mockup). Added top and left margins to space it out
- Increased NavCard padding by one unit, adding more space above h2s

**Comment by dcloud** [comment]
See latest ["after" desktop screenshot](https://user-images.githubusercontent.com/279327/223507216-1604fc82-f49f-4603-9655-584a9da1f299.png), per department-of-veterans-affairs/vets-website/pull/23539
