### ISSUE TITLE
Issue with accordion on pre check in confirmation page

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#54719]
## Description 

In pre check in, when demos do not need to be reviewed, when viewing the /complete page, the "How can I updated my information?" accordion is appearing and the "Emergency and next of kin information" content is not displaying correctly. 

When a Veteran does not need their information reviewed or updated, this accordion should not be present on the /complete page. 

Here is documentation of the accordion logic: https://share.goabstract.com/4f416207-0fd1-4b05-8ba5-21b6e688e75a?collectionLayerId=4612e753-617c-4fed-b32e-89d4067e4277&mode=design&sha=2151938dcf37110b964ffcedc6bc508582f16dd0

![Screen Shot 2023-03-07 at 11.27.26 AM.png](https://images.zenhubusercontent.com/62264cddfdd7546d65710eff/343c9a77-fd1a-4797-8f2f-76eb092cd220)

## AC

- [ ] When a Veteran does not need their information reviewed, this accordion should not be present on the /complete page. 
- [ ] When a Veteran answers yes to all questions, this accordion should not be present on the /complete page. 
- [ ] If a Veteran needs their emergency and next of kin information updated, make sure the content in the accordion does not have issues.

**Comment by acrollet** [comment]
### Implementation note

Let's perhaps consider upgrading the logic with nice case statements like @wullaski has done for our error handling?
