### ISSUE TITLE
AWS access for Kevin Duensing

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#54713]
### COR Name

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative Name

Other - please specify in 'Additional Notes'

### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Kevin Duensing

### Your Email

kevin.duensing@adhocteam.us

### Team, Role, and Company of the target individual

Benefits - CST, Engineer, Ad Hoc

### Product Manager (PM) name and email

Jacob Worrell, jacob.worrell@adhocteam.us

### Product Owner (PO) name and email

Matt Self, matthew.self2@va.gov

### Desired AWS Access

Hello, I'm debugging a few cases from the Contact Center affecting how Veterans view their claims in the Claims Status Tool. Could I please have the `adhoc-vetsgov-ssm-prod` policy added to my AWS user in order to quickly debug these issues?

In addition, I would like to be able to create and view cloudwatch monitors, metrics, alerts, and dashboards. 

@jacobworrell @jaredcunha

### Access Expiration

ongoing

### Additional Notes

If possible, could we expedite this access request? This is a high-priority bug we're hoping to solve quickly.

COR: Keith Riley
VOR: Jeff Langworthy

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by little-oddball** [comment]
VFS Roster

**Comment by kjduensing** [comment]
@BillChapmanUSDS Thanks! 

I believe my date is 5/4/2021. This comes from a [comment Clint Little made on a previous AWS permissions ticket last month](https://github.com/department-of-veterans-affairs/va.gov-team/issues/52742#issuecomment-1419701197).

**Comment by considerable** [comment]
@kjduensing your prod access is active now. apologies for waiting time. closing the tkt.
