### ISSUE TITLE
Create method to signify which CSP has been used to authenticate, without relying on the User model

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#54726]

**Comment by bramleyjl** [comment]
@bosawt making sure I understand the intent of this story:

Currently the CSP method is accessed through `@user.identity.sign_in[:service_name]`, that is to say on the `UserIdentity` model's `sign_in` hash, obtained by going through the `User` that identity belongs to. If we don't want to have to rely on the `User` model are we looking for the instances where it's leveraged to get `sign_in` and update those to directly access the `UserIdentity`? Or is there a different solution that you had in mind?

**Comment by bosawt** [comment]
So it's interesting, I just looked through the SiS code right now, and the only place it's used is in `sign_in_controller#logout_get_redirect_url`. I was thinking it was in more places, but I suppose that makes sense, as we don't have a lot of SiS code after a user has signed in

**Comment by bosawt** [comment]
I think I might say we wait for this until we're further along on the SiS separation, as I'm not 100% sure what to do here. The specific code in `logout_get_redirect_url` might just stay in `vets-api`, in which case we wouldn't have to do anything here. But I'm not sure yet..
