### ISSUE TITLE
[BE] Log user loa level in health_care_applications#enrollment_status api

### ISSUE THREAD

**Issue by lihanli** [department-of-veterans-affairs/va.gov-team#54736]
Log user loa level in health_care_applications#enrollment_status api in order to figure out why validation errors are happening with this api even though the attributes are required for non signed in users
http://sentry.vfs.va.gov/organizations/vsp/issues/6174/events/f5c903d04a7f4ae5855cb494fc67addb/?environment=production&project=3&query=is%3Aunresolved+controller_name%3Ahealth_care_applications+level%3Aerror&statsPeriod=14d

**Comment by hdjustice** [comment]
@lihanli - Can you write up a little description of the issue you are encountering on this?

**Comment by lihanli** [comment]
@hdjustice after looking at the errors again i think they can be safely ignored. basically there were a lot of errors in our logs about the enrollment_status api. it looks like they are all coming from the my va dashboard page and it shows that a logged out user is calling that api, and it throws an error because it is expecting the user to be logged in. 

i think it is caused by a user logging in, going to their my va dashboard page, then putting their computer or phone to sleep, the user gets logged out automatically while their computer is asleep, then the user wakes up the computer again and the browser tries to call the api again even though it doesn't know that the user has been logged out.

**Comment by hdjustice** [comment]
Oh wow, interesting.  Thank you for this!
