### ISSUE TITLE
 Replace all certs and keys paths to ssm paths

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#54731]
Mounted keys and certs are not translating in the settings-local-secrets.yaml. They are showing as paths.

Cert and keys paths that are mounted are called the settings-local-secrets need to be replaced as env variables that point to a ssm path. 

ex: 
**key_path: /etc/pkl/foo** -> **key_path: <% ENV["FOO"] %>**

The three paths that need to be updated in the settings.local.yaml"
/srv/vets-api/secret
/etc/pki/tls/certs
/etc/pki/tls/private

**Comment by LindseySaari** [comment]
Yes, these are updated cc @laineymajor Closing this
