### ISSUE TITLE
Staging: Request Location not Displayed in Queue View

### ISSUE THREAD

**Issue by beth-wodzinski** [department-of-veterans-affairs/va.gov-team#54735]
This is a duplicate of https://github.com/department-of-veterans-affairs/va.gov-team/issues/51722. That issue was fixed, but has since recurred. 

The requested location does not initially display when the appointments are loaded onto the page in queue view. You must reload the page and then the locations will display.

Specs
Device: Tested on PC
Browser: Tested with Chrome and MS Edge

Steps to Reproduce
Test User: [cecil.morgan@id.me](mailto:cecil.morgan@id.me), for CC appointments use [grethel.g.petryniec@id.me](mailto:grethel.g.petryniec@id.me)

Login to Staging as patient with several pending VA Requests.
From the home page select the pending request queue link. Page displays.
Expected response: Page displays a list of requests and each request has the type of care and location.
Actual Response: Page displays list of of requests and each request only has the Type of Care. Location is NOT displayed.

Actual Result
In staging, when you are in the queue and the appointments are displaying on the page, their location does not display until you reload the page. This is a loss of information for the veteran.

Desired Result
In staging, when you are in the queue and the appointments are displaying on the page, their location displays without reloading the page.
![RefreshImage](https://user-images.githubusercontent.com/69322085/223535371-96b323b3-9dfa-474a-babf-be9f4b47d700.png)

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by ldelacosta** [comment]
@beth-wodzinski and @marcynadeau - is this still an issue with the updated appointment list redesign? Looks like this issue was resolved with the new layout. Please let me know. Thanks!

**Comment by beth-wodzinski** [comment]
I agree that this is not an issue any more and locations are showing as expected in the new layout.

**Comment by ldelacosta** [comment]
No longer an issue with the new appointment list redesign that was launched on June 7, 2023. Closing out the ticket.
