### ISSUE TITLE
General Alert boxes front-end analysis

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#5474]
**Tasks**

- [x] Identify how many unique alert components there are currently
- [x] See if there’s any sharable logic to capture and/or if the current way those exist should be simplified or abstracted

**Comment by ambikaroos** [comment]
Note that we'll also need the ability to determine which Cerner facility a user is a patient at: Columbus, OH (April 10, Scheduling only), Mann Grandstaff (March 28), and others in the future

**Comment by hinzed1127** [comment]
Validated that this is ready for development pending the completion of #5405. That ticket doesn't necessarily block this, which was more just active discovery, but it is a pre-req for successfully completing the front-end updates. 

I've started a branch in `vets-website` that has placeholders for most of the updates needed once that identifier is consumable from `vets-api`'s `/user` endpoint
