### ISSUE TITLE
[Spike] Namespace update when moving appointments to MHV on VA.gov

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#54757]
## Background
VAOS appointments will move to MHV on VA.gov in 2023 as part of the Unified Appointment Experience (UAE). As part of this move the current Appointments functionality will move to a new URL.  Product will need to understand what the effort for this initiative is and list out the tasks needed to implement the changes. 

### Goal
Update the namespace for the appointment list to MHV on VA.gov

### Requirements to Consider
A new namespace will be provided by the MHV on VA.gov team.

Updating reports will be investigated in a separate ticket.

---

## Tasks
- Answer the following questions:
  - Q1: What code, if any, will need to be changed to support a new URL?
  - Q2: Will Google Analytic events need to be changed?
  - Q3: What is the recommended approach to moving to a new URL?
  - Q4: Will this impact any of the feedback applications, like Medallia?
  - Q5: Can the move be done in stages versus a one-time switchover?
  - Q6: What else may be impacted by this move that we have not thought about?

## Time Box
18 hours

## Definition of Done
- Tasks are complete
- Research and recommendations are documented in this ticket

---

**Comment by JRRoof** [comment]
Will need an additional ticket to address changes to reports in Google Analytics, Looker Studio (formerly Google Data Studio and Domo.

**Comment by ldelacosta** [comment]
Q3: Will error tracking and alert dashboards need to be updated? Grafana? DataDog? - will work on a separate spike ticket

**Comment by simiadebowale** [comment]
Q1: In vets-api, we will need to update the href in our anchor tags, NavLink, va-link:
`<Breadcrumbs>
        <a
          href={`/health-care/schedule-view-va-appointments/appointments/va/${
            appointment.id
          }`}
        >
          Appointment detail
        </a>
      </Breadcrumbs>`
`<NavLink
          to={`/health-care/schedule-view-va-appointments/appointments/requests/${id}`}
        >
          Request detail
        </NavLink>`
`<va-link
                href="/health-care/schedule-view-va-appointments/appointments/"
                onClick={() =>
                  recordEvent({
                    event: `${GA_PREFIX}-view-your-appointments-button-clicked`,
                  })
                }
                text="View your appointments"
                data-testid="view-appointments-link"
              />`
Q2:  We do not need to update our GA events / datadog logs because we do not send urls to GA/datadogs.
Q3: Recommended approach will be to update urls in the components listed above and setting up redirects reverse proxy in the devOps repo for the old urls.
Q4: I don't foresee any impact to Medallia.
Q5: We will need to put the website changes behind a feature flag but we can breakout the url changes to smaller pieces.

**Comment by ldelacosta** [comment]
Will add this ticket as a reference to all the work related to URL, breadcrumb and title page changes. cc: @JRRoof @simiadebowale
