### ISSUE TITLE
Qualitative Data Request for New Home Page 1st 2 weeks

### ISSUE THREAD

**Issue by cindymerrill** [department-of-veterans-affairs/va.gov-team#54761]
### Data Type Requested

User Surveys

### Date Range Start

02-21-2023

### Date Range End

03-07-2023

### Product Name(s)

New VA.gov home page

### Product Description

A new VA.gov home page was launched via opt-in to 25% of users starting 2 weeks ago, and we want to see all Medallia feedback from these first 2 weeks.

### Product URL(s) and/or term(s)

https://www.va.gov/new-home-page/

### File Delivery Format

All in one file, on one tab

### VA Email Address(es)

cynthia.merrill@va.gov, WESLEY.ROWE@va.gov

### Add Assignee and Labels

If not already done so, please ensure @ianMcCullough-ob is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by cindymerrill** [comment]
FYI @wesrowe

**Comment by ianMcCullough-ob** [comment]
@cindymerrill I just shared the data with you and Wes. Let me know if you need anything else!

**Comment by wesrowe** [comment]
@ianMcCullough-ob, thanks for the quick turnaround!

**Comment by cindymerrill** [comment]
We so appreciate your rapid data delivery, @ianMcCullough-ob !
