### ISSUE TITLE
SOCKS access for Anita DeWitt

### ISSUE THREAD

**Issue by anitadewitt-va** [department-of-veterans-affairs/va.gov-team#54760]
### Your Name

Anita DeWitt

### Your Email

adewitt@thoughtworks.com

### Your Role and Team

Developer on Virtual Agent Chatbot, Thoughtworks

### Product Manager (PM) name and email

Ian Santarinala ian.santarinala@thoughtworks.com

### Product Owner (PO) name and email

Luciana Morais Luciana.Morais@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDN9s5GvNMAS2eHyzRf3JYikyirbFOYXFo66Dtdgd8GcbPX+QigzUqiRM9jmAhXQRYKIJ663/yR/bPhQGd6qv7c6PytBdjyD/SDO7mbnbQitUTGnlHhg33hFNad4GnIYhU3MgeSeJ4AuYdVAZhsQxIJqfX9ErkFJJBrsVoxiGoGIIb0s+DjIpjcXpPMajDJ5lpo+2C3lVIXDcrHA98w6MxPnPExMyXRg8983q8iWm+3kl4HTozWlkCEASQfKYFSuiMtKb98golJtliAk8iBgzztGI1KR9FxBLsBIxOBaBLcKZd2IiaQrV0AEQ6dCh8gnByX7MWK/O5ba7kkhCo3frOKd1CBFlXIpLU30WSHKLKshRxwwKSK3B++xjU41Qq9sgX7oJ7Lx+RqolKzEMUiqu2WFbQvNx47EO1Tz8Dz4EskJyjQXUtKAVuiPpDWsz2aTQU8xaVHZLVGtYpFlaguGzW+VxGA/BI6MpHgk7kQ39AcFLzq0iCTyTujSY6bQZZjM3E= anitadewitt@anitas-MacBook-Pro.local

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by anitadewitt-va** [comment]
Hello, I am not able to connect to socks. I get prompted for a passphrase and I did not create a passphrase for this. Please advise.

**Comment by little-oddball** [comment]
@anitadewitt-va - please see Peter's comment above.

**Comment by little-oddball** [comment]
@anitadewitt-va - nudge

**Comment by little-oddball** [comment]
@npeterson54 @pjholyoke @considerable - Can one of you please follow up once more and see about a response? If none, then please close the request as no response.

**Comment by considerable** [comment]
no response

**Comment by anitadewitt-va** [comment]
I am now able to connect to socks.
