### ISSUE TITLE
Finish initial wireframes 

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#54768]
## Description 

Finish remaining tasks for the initial set of wireframes for the unified experience. 

### Priorities  

- [x] Relocate all wireframes and components that aren't being used (Christina) 
- [x] Add the "you have other appointments to review" component (4 different variations of content) to the four wireframes (Zach)
- [x] Swap out all the action links and alerts with the work that Ya-ching did (Christina) https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/zx92Zoe?annotation=bc467411-6d8a-4e81-95fb-c4a00ae90b8a

### Other tasks 

- [x] Review all spacing and convert components to symbols (Zach) 
     - [x] Address spacing when there's no cards or alerts - https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/m1ZqWLJ?annotation=df3422f7-a6e2-4d8d-ab8c-9c6759433451
- [x] Some wires still need to be updated to use upcoming and past links 
- [x] Review with accessibility (Christina) 
     - [x] Action link location on appointment details page - https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/Om9P834?annotation=b0470109-643e-433c-a418-c5d68e2ae404
     - [x] Heading for the no appointments wireframe 
- [x] Content on the pre check in introduction page (Ben & Kelly)
- [x] Are we reordering components on our confirmation pages based on the decisions and discussions that have or are happening with Zach, Kelly and Ya-ching about the travel reimbursement confirmation pages? https://staging.va.gov/health-care/appointment-check-in/error?error=refresh-on-details. The decision here was to use the versions in production that have the "We'll come get you in the waiting room..." as an alert NOT at the top of the page. Therefore, we might think making sure all of our confirmation pages follow that for now. 
- [x] Finish the phone appointment confirmation page (Zach) https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/ZVMMD93?annotation=84f3bfec-ed6f-498e-afd1-de251263f8fb
- [x] Review content on check in confirmation about way finding at the clinic (Ben) - https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/PGgw5vx?annotation=b7b48660-5164-4e2a-8edf-fb845fbafe24
- [ ] Provide annotations, where needed, for site wide content and IA and engineers. For example, notification that uses singular vs plural, variations of footer, etc. (Ben)
- [ ] Review and resolve all comments. For example, some new ones were added after sharing with the engineers. (Ben and Christina.)
- [x] Final walk through with Kelly to review from a content perspective 

### Lowest priorities 

- [x] Consider removing ellipses. [See ticket from VAOS](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54917).  
- [x] Evaluate [flipping phone icon direction](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1595#issuecomment-1460484232). Is this something we do now? Or does it need to wait for DST? 
- [x] Ask Peter and Ciera about the heading for the no appointments wireframe (Christina)
- [x] Remove timezone (ET) from all appointments (talk to Zach and Christina in case they're converting appointments to symbols)

**Comment by loripusey** [comment]
@zach-park @benbrasso-agile6 is this ticket complete?

**Comment by benbrasso-agile6** [comment]
I believe we're done. @cgednalske agree we can close?
