### ISSUE TITLE
SOCKS access for Eddie Glenn

### ISSUE THREAD

**Issue by navaeddie** [department-of-veterans-affairs/va.gov-team#54779]
### Your Name

Eddie Glenn

### Your Email

hodges.glenn@va.gov

### Your Role and Team

Software Engineer - Disability Benefits Experience

### Product Manager (PM) name and email

Elizabeth Neal, elizabeth.neal@agile6.com

### Product Owner (PO) name and email

Rakshinda Aslam - rakshinda.aslam@agile6.com

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDREdpGb5I2QiIfDUuACsjVeyecy/PmR5EqTf6H59hF39rR5Ui0DwW1Elps2rdkrGPzNQn/JOwy2BAXYNM3ZKyBDTIbAXg0VXvB6ewMZMC5hz6wMoNsOP7evGrdJ0SDIYSCJml+zTDANqRlmtbUfCBp+XV33H2+aWV1xCqOtqVGwPyfh/BB8jcW0CSa/YJ7qlfvBZOmvUO8Wd7OukBNA2JLAPbvNuIMCNJm9oesjRj8asxd/NYRsextVNCWvhbJ3U4lr+AR7qQ+qtTWdpusBETGkD7kdvEUlQcd0fXUqGAMNgAk/iLX+jz2YrLTaQ6pNXlOrISjvCwLtHnXgk8zYsWs0ukg22/e8I7AOIid4FTWF2ZcSZ0nvURXu4erXUIlNKX7Whq7D6nraCWRWh+Gl1NxvJvWtRUaoH6EB57om8QKC6mc7MJEwVpgNA2fMfv5/kW6o7F8TbcIbt62Y3hyryTwhX1/3T3pkfODv06EvleeRBSsL/ILSXxbFEbZWpB5DeM= eddieglenn@Eddies-MacBook-Pro.local

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by ryan-mcneil** [comment]
Adding for reference
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/41602677/fe6a5142-bdd1-41b1-9c47-1bece6ba2eee)
