### ISSUE TITLE
Update interest rate and make other changes on NADL page-HOLD TO PUBLISH UNTIL 3/14

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#54780]
## Issue Description

Raleigh informed us that the NADL interest rate is being lowered to 2.5%. We need to make this change on the [Native American Direct Loan](https://www.va.gov/housing-assistance/home-loans/loan-types/native-american-direct-loan/) page.

He also let us know that Veterans should now contact their NADL loan coordinator instead of the regional loan center so we need to make a few other adjustments to the page. 

1. Under the H2 "Why might I want to get an NADL?" the fourth bullet these are the changes he's asking for (bold is what's new):

A low-interest, 30-year fixed mortgage (a fixed mortgage means your interest rate will stay the same over the full life of the loan). The current VA interest rate for NADLs starts at 2.5%. You can contact ~your state’s VA regional loan center~ **an NADL coordinator by email at NADL@va.gov or by phone at 888-349-7541** to find out what your interest rate will be and to get help starting your loan application.
~Find your state’s VA regional loan center~

2. In step 2 of the subway map the suggested changes are:

Contact ~the VA regional loan center for your state~ **an NADL coordinator** to begin the NADL process.
~Find your state’s VA regional loan center~
**You can contact an NADL coordinator by email at NADL@va.gov or by phone at 888-
349-7541.**

We'll need to review these changes for plain language and VA.gov style before updating. 

Changes should go live on 3/14.

## Tasks
- [x] Update Drupal page (Aliyah)
- [x] Review (Laura)
- [x] Copyedit (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] Changes are live

**Comment by aliyahblackmore** [comment]
Hi @laurwill - these changes are ready for you to review when you have a moment. 
Also noting here that Randi reverted to the last published version - I made my changes there. 
We're holding to publish this until tomorrow, 3/14. 

**Preview link:** http://preview-prod.vfs.va.gov/preview?nodeId=758

**Comment by laurwill** [comment]
Thanks Aliyah! I shortened the sentence in the bullet about interest rates to "To find out what your interest rate will be" — the sentence was getting too long, and getting help starting the application is covered elsewhere on the page.

And I took out "you can" from the start application step — there doesn't seem to be any way to do this without getting help from an NADL coordinator, so we can be more direct here.

This is all set to publish tomorrow morning.

**Comment by RLHecht** [comment]
@megzehn Just got confirmation from Raleigh that this can now go live. Can you please copyedit and publish? Thank you!

**Comment by megzehn** [comment]
Thanks @RLHecht! I reviewed and published these changes.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket!
