### ISSUE TITLE
Remove VA-ONCE mentions from Fry Scholarship page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#54788]
## Issue Description

Tammy Hurley let us know that on the [Fry Scholarship](https://www.va.gov/education/survivor-dependent-benefits/fry-scholarship/) page, we should no longer have the VA Online Certification (VA-ONCE) reference in step 2 of the subway map.

VA now uses a new tool Enrollment Manager:  https://iam.education.va.gov/auth/realms/dgib/protocol/openid-connect/auth?response_type=code&scope=openid+profile+email&client_id=apigw&redirect_uri=https://iam.education.va.gov:443/_codexch&nonce=ahr_u4pFHEcUAlXSHbKYjL72lLYnklBxnY4IjR1faIY&state=0

We need to update this info on the page and make sure we adhere to plain language and VA.gov style standards.

## Tasks
- [x] Update Fry Scholarship page
- [x] Review (Laura)
- [x] Copyedit (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] Page is live with changes

**Comment by laurwill** [comment]
Thanks @katherine-fung ! Can you change "platform" to "system"? That's the word we use for these types of online portals elsewhere, like Web LGY and SOES. And I poked around and found materials from the business line that call it a "system." Then you can pass to Megan!

**Comment by megzehn** [comment]
Thanks @katherine-fung! I reviewed and published this page. 

Over to you @RLHecht!
