### ISSUE TITLE
Ruby 3 Spec: Internal server error (76)

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#54797]
These specs are failing on the `ruby-3-0` branch:

The following three failures are due to the `fast_jsonapi` Gem. Skipping per Eric:
- [ ] `rspec "./modules/mobile/spec/request/clinics_request_spec.rb[1:2:1:1]" # L76`
- [ ] `rspec "./modules/mobile/spec/request/clinics_request_spec.rb[1:2:2:1]" # L100`
- [ ] `rspec "./modules/mobile/spec/request/clinics_request_spec.rb[1:1:1:1]" # L28`

All of the following tests in `modules/vba_documents/spec/request/v2/uploads_request_submission_spec.rb` seem to be passing now:
- [x] `rspec "./modules/vba_documents/spec/request/v2/uploads_request_submission_spec.rb[1:1:6]" # L147`
- [x] `rspec "./modules/vba_documents/spec/request/v2/uploads_request_submission_spec.rb[1:1:12]" # L170`
- [x] `rspec "./modules/vba_documents/spec/request/v2/uploads_request_submission_spec.rb[1:1:11]" # L159`
- [x] `rspec "./modules/vba_documents/spec/request/v2/uploads_request_submission_spec.rb[1:1:14]" # L182`
- [x] `rspec "./modules/vba_documents/spec/request/v2/uploads_request_submission_spec.rb[1:1:15]" # L182`
- [x] `rspec "./modules/vba_documents/spec/request/v2/uploads_request_submission_spec.rb[1:1:3]" # L122`
- [x] `rspec "./modules/vba_documents/spec/request/v2/uploads_request_submission_spec.rb[1:1:2]" # L110`
- [x] `rspec "./modules/vba_documents/spec/request/v2/uploads_request_submission_spec.rb[1:1:8]" # L147`
- [x] `rspec "./modules/vba_documents/spec/request/v2/uploads_request_submission_spec.rb[1:1:19]" # L182`
- [x] `rspec "./modules/vba_documents/spec/request/v2/uploads_request_submission_spec.rb[1:1:1]" # L95`
- [x] `rspec "./modules/vba_documents/spec/request/v2/uploads_request_submission_spec.rb[1:1:16]" # L182`
- [x] `rspec "./modules/vba_documents/spec/request/v2/uploads_request_submission_spec.rb[1:1:13]" # L182`
- [x] `rspec "./modules/vba_documents/spec/request/v2/uploads_request_submission_spec.rb[1:1:18]" # L182`
- [x] `rspec "./modules/vba_documents/spec/request/v2/uploads_request_submission_spec.rb[1:1:21]" # L182`
- [x] `rspec "./modules/vba_documents/spec/request/v2/uploads_request_submission_spec.rb[1:1:4]" # L138`
- [x] `rspec "./modules/vba_documents/spec/request/v2/uploads_request_submission_spec.rb[1:1:7]" # L147`
- [x] `rspec "./modules/vba_documents/spec/request/v2/uploads_request_submission_spec.rb[1:1:5]" # L138`
- [x] `rspec "./modules/vba_documents/spec/request/v2/uploads_request_submission_spec.rb[1:1:10]" # L147`
- [x] `rspec "./modules/vba_documents/spec/request/v2/uploads_request_submission_spec.rb[1:1:20]" # L182`
- [x] `rspec "./modules/vba_documents/spec/request/v2/uploads_request_submission_spec.rb[1:1:9]" # L147`
- [x] `rspec "./modules/vba_documents/spec/request/v2/uploads_request_submission_spec.rb[1:1:17]" # L182`
- [x] `rspec "./modules/vba_documents/spec/request/v2/uploads_request_submission_spec.rb[1:1:22:10]" # L233`
- [x] `rspec "./modules/vba_documents/spec/request/v2/uploads_request_submission_spec.rb[1:1:22:9]" # L221`
- [x] `rspec "./modules/vba_documents/spec/request/v2/uploads_request_submission_spec.rb[1:1:22:5]" # L233`
- [x] `rspec "./modules/vba_documents/spec/request/v2/uploads_request_submission_spec.rb[1:1:22:8]" # L246`
- [x] `rspec "./modules/vba_documents/spec/request/v2/uploads_request_submission_spec.rb[1:1:22:6]" # L221`
- [x] `rspec "./modules/vba_documents/spec/request/v2/uploads_request_submission_spec.rb[1:1:22:4]" # L221`
- [x] `rspec "./modules/vba_documents/spec/request/v2/uploads_request_submission_spec.rb[1:1:22:3]" # L233`
- [x] `rspec "./modules/vba_documents/spec/request/v2/uploads_request_submission_spec.rb[1:1:22:7]" # L233`
- [x] `rspec "./modules/vba_documents/spec/request/v2/uploads_request_submission_spec.rb[1:1:22:2]" # L221`
- [x] `rspec "./modules/vba_documents/spec/request/v2/uploads_request_submission_spec.rb[1:1:22:1]" # L202`
- [x] `rspec "./modules/vba_documents/spec/request/v1/uploads_request_spec.rb[1:2:10]" # L203`

Continuing:
- [x] [`rspec "./modules/mobile/spec/request/user_request_spec.rb[1:1:3:1]" # L450`](https://github.com/department-of-veterans-affairs/vets-api/pull/12027)
- [x] [`rspec "./modules/appeals_api/spec/requests/v2/notice_of_disagreements_controller_spec.rb[1:6:1]" # L386`](https://github.com/department-of-veterans-affairs/vets-api/pull/12035)
- [x] `rspec "./modules/my_health/spec/request/v1/folders_request_spec.rb[1:3:7:1:1]" # L155`
- [x] [`rspec "./modules/my_health/spec/request/v1/folders_request_spec.rb[1:3:9:4]" # L208`](https://github.com/department-of-veterans-affairs/vets-api/pull/12024)
- [x] `rspec "./modules/my_health/spec/request/v1/folders_request_spec.rb[1:3:9:4]" # L221`
- [x] `rspec "./modules/my_health/spec/request/v1/folders_request_spec.rb[1:3:8:1]" # L167`
- [x] `rspec "./modules/my_health/spec/request/v1/folders_request_spec.rb[1:3:8:2]" # L176`
- [x] [`rspec "./modules/appeals_api/spec/requests/v2/supplemental_claims_controller_spec.rb[1:2:8:2]" # L190`](https://github.com/department-of-veterans-affairs/vets-api/pull/12037)
- [x] [`rspec "./modules/appeals_api/spec/requests/v2/supplemental_claims_controller_spec.rb[1:2:6:1]" # L155`](https://github.com/department-of-veterans-affairs/vets-api/pull/12037)
- [x] [`rspec "./modules/vba_documents/spec/request/v2/uploads_request_spec.rb[1:2:10]" # L271`](https://github.com/department-of-veterans-affairs/vets-api/pull/12038)
- [x] `rspec "./modules/mobile/spec/request/community_care_providers_request_spec.rb[1:1:1]" # L23`
- [x] `rspec "./modules/mobile/spec/request/community_care_providers_request_spec.rb[1:1:7:1]" # L85`
- [x] `rspec "./modules/mobile/spec/request/community_care_providers_request_spec.rb[1:1:8:1]" # L111`
- [x] `rspec "./modules/mobile/spec/request/prescriptions_request_spec.rb[1:2:3:1]" # L177`
- [x] `rspec "./modules/mobile/spec/request/prescriptions_request_spec.rb[1:2:2:1]" # L167`
- [x] `rspec "./modules/mobile/spec/request/prescriptions_request_spec.rb[1:2:8:1]" # L361`
- [x] `rspec "./modules/mobile/spec/request/prescriptions_request_spec.rb[1:2:1:1]" # L157`
- [x] `rspec "./modules/mobile/spec/request/prescriptions_request_spec.rb[1:2:6:1:1]" # L226`
- [x] `rspec "./modules/mobile/spec/request/prescriptions_request_spec.rb[1:2:6:4:1]" # L273`
- [x] `rspec "./modules/mobile/spec/request/prescriptions_request_spec.rb[1:2:6:2:1]" # L241`
- [x] `rspec "./modules/mobile/spec/request/prescriptions_request_spec.rb[1:2:6:3:1]" # L258`
- [x] `rspec "./modules/mobile/spec/request/prescriptions_request_spec.rb[1:2:7:2:1]" # L326`
- [x] `rspec "./modules/mobile/spec/request/prescriptions_request_spec.rb[1:2:7:1:1]" # L309`
- [x] `rspec "./modules/mobile/spec/request/prescriptions_request_spec.rb[1:2:5:1]" # L206`
- [x] `rspec "./modules/vba_documents/spec/request/v1/upload_complete_request_spec.rb[1:2:1:1]" # L126`
- [x] [`rspec "./modules/appeals_api/spec/requests/v2/higher_level_reviews_controller_spec.rb[1:2:10:1]" # L214`](https://github.com/department-of-veterans-affairs/vets-api/pull/12043)
- [ ] `rspec "./modules/mobile/spec/request/v1/user_request_spec.rb[1:1:3:1]" # L451`
- [x] `rspec "./modules/mobile/spec/request/folders_request_spec.rb[1:3:5:1]" # L131`

All of the following `claims_api` failures are fixed by this PR - https://github.com/department-of-veterans-affairs/vets-api/pull/12040
- [x] `rspec "./modules/claims_api/spec/requests/v2/veterans/intent_to_files_request_spec.rb[1:1:2:1:1:1]" # L341`
- [x] `rspec "./modules/claims_api/spec/requests/v2/veterans/intent_to_files_request_spec.rb[1:1:2:2:1:1]" # L361`
- [x] `rspec "./modules/claims_api/spec/requests/v2/veterans/intent_to_files_request_spec.rb[1:1:2:2:2:2:1:1]" # L410`
- [x] `rspec "./modules/claims_api/spec/requests/v2/veterans/intent_to_files_request_spec.rb[1:1:2:2:2:2:1:2:1]" # L421`
- [x] `rspec "./modules/claims_api/spec/requests/v2/veterans/intent_to_files_request_spec.rb[1:1:2:2:3:1]" # L459`
- [x] `rspec "./modules/claims_api/spec/requests/v2/veterans/intent_to_files_request_spec.rb[1:1:2:3:1:1:1]" # L476`
- [x] `rspec "./modules/claims_api/spec/requests/v2/veterans/intent_to_files_request_spec.rb[1:1:1:4:1:1]" # L164`
- [x] `rspec "./modules/claims_api/spec/requests/v2/veterans/intent_to_files_request_spec.rb[1:1:1:1:1:1]" # L34`
- [x] `rspec "./modules/claims_api/spec/requests/v2/veterans/intent_to_files_request_spec.rb[1:1:1:6:1:1:1]" # L291`
- [x] `rspec "./modules/claims_api/spec/requests/v2/veterans/intent_to_files_request_spec.rb[1:1:1:2:2:1]" # L77`
- [x] `rspec "./modules/claims_api/spec/requests/v2/veterans/intent_to_files_request_spec.rb[1:1:1:2:3:1]" # L88`
- [x] `rspec "./modules/claims_api/spec/requests/v2/veterans/intent_to_files_request_spec.rb[1:1:1:2:4:1:1]" # L100`
- [x] `rspec "./modules/claims_api/spec/requests/v2/veterans/intent_to_files_request_spec.rb[1:1:1:2:4:3:1]" # L122`
- [x] `rspec "./modules/claims_api/spec/requests/v2/veterans/intent_to_files_request_spec.rb[1:1:1:2:4:2:1]" # L111`

**Comment by holdenhinkle** [comment]
I've been flailing on this one:
```
rspec "./modules/mobile/spec/request/v1/user_request_spec.rb[1:1:3:1]"
```

Here's the error in `response.body` (I formatted it a bit to make it easier to read):

```
"{\"errors\":[{\"title\":\"Internal server error\"
\"detail\":\"Internal server error\"
\"code\":\"500\"
\"status\":\"500\"
\"meta\":{\"exception\":\"\\n\\n================================================================================\\nAn HTTP request has been made that VCR does not know how to handle:\\n  GET https://int.vet360.va.gov/demographics/demographics/v1/2.16.840.1.113883.4.349/b2fab2b5-6af0-45e1-a9e2-394347af91ef%5EPN%5E200VIDM%5EUSDVA\\n\\nVCR is currently using the following cassette:\\n  - /Users/holdenhinkle/Documents/Oddball/va_website/vets-api/modules/mobile/spec/support/vcr_cassettes/user/get_facilities.yml\\n    - :record => :once\\n    - :match_requests_on => [:method, :uri]\\n\\nUnder the current configuration VCR can not find a suitable HTTP interaction\\nto replay and is prevented from recording new requests. There are a few ways\\nyou can deal with this:\\n\\n  * If you're surprised VCR is raising this error\\n    and want insight about how VCR attempted to handle the request,\\n    you can use the debug_logger configuration option to log more details [1].\\n  * You can use the :new_episodes record mode to allow VCR to\\n    record this new request to the existing cassette [2].\\n  * If you want VCR to ignore this request (and others like it), you can\\n    set an `ignore_request` callback [3].\\n  * The current record mode (:once) does not allow new requests to be recorded\\n    to a previously recorded cassette. You can delete the cassette file and re-run\\n    your tests to allow the cassette to be recorded with this request [4].\\n  * The cassette contains 1 HTTP interaction that has not been\\n    played back. If your request is non-deterministic, you may need to\\n    change your :match_requests_on cassette option to be more lenient\\n    or use a custom request matcher to allow it to match [5].\\n\\n[1] https://www.relishapp.com/vcr/vcr/v/6-1-0/docs/configuration/debug-logging\\n[2] https://www.relishapp.com/vcr/vcr/v/6-1-0/docs/record-modes/new-episodes\\n[3] https://www.relishapp.com/vcr/vcr/v/6-1-0/docs/configuration/ignore-request\\n[4] https://www.relishapp.com/vcr/vcr/v/6-1-0/docs/record-modes/once\\n[5] https://www.relishapp.com/vcr/vcr/v/6-1-0/docs/request-matching\\n================================================================================\\n\\n\"
\"meta\":{\"exception\":\"
================================================================================
An HTTP request has been made that VCR does not know how to handle:
  GET https://int.vet360.va.gov/demographics/demographics/v1/2.16.840.1.113883.4.349/b2fab2b5-6af0-45e1-a9e2-394347af91ef%5EPN%5E200VIDM%5EUSDVA
VCR is currently using the following cassette:
  - /Users/holdenhinkle/Documents/Oddball/va_website/vets-api/modules/mobile/spec/support/vcr_cassettes/user/get_facilities.yml
    - :record => :once
    - :match_requests_on => [:method, :uri]
Under the current configuration VCR can not find a suitable HTTP interaction
to replay and is prevented from recording new requests. There are a few ways
you can deal with this:
  * If you're surprised VCR is raising this error
    and want insight about how VCR attempted to handle the request,
    you can use the debug_logger configuration option to log more details [1].
  * You can use the :new_episodes record mode to allow VCR to
    record this new request to the existing cassette [2].
  * If you want VCR to ignore this request (and others like it), you can
    set an `ignore_request` callback [3].
  * The current record mode (:once) does not allow new requests to be recorded
    to a previously recorded cassette. You can delete the cassette file and re-run
    your tests to allow the cassette to be recorded with this request [4].
  * The cassette contains 1 HTTP interaction that has not been
    played back. If your request is non-deterministic, you may need to
    change your :match_requests_on cassette option to be more lenient
    or use a custom request matcher to allow it to match [5].
[1] https://www.relishapp.com/vcr/vcr/v/6-1-0/docs/configuration/debug-logging
[2] https://www.relishapp.com/vcr/vcr/v/6-1-0/docs/record-modes/new-episodes
[3] https://www.relishapp.com/vcr/vcr/v/6-1-0/docs/configuration/ignore-request
[4] https://www.relishapp.com/vcr/vcr/v/6-1-0/docs/record-modes/once
[5] https://www.relishapp.com/vcr/vcr/v/6-1-0/docs/request-matching
================================================================================
\"
\"backtrace\":[\"/Users/holdenhinkle/.rvm/gems/ruby-3.0.5/gems/vcr-6.1.0/lib/vcr/request_handler.rb:97:in `on_unhandled_request'\"
\"/Users/holdenhinkle/.rvm/gems/ruby-3.0.5/gems/vcr-6.1.0/lib/vcr/library_hooks/webmock.rb:120:in `on_unhandled_request'\"
\"/Users/holdenhinkle/.rvm/gems/ruby-3.0.5/gems/vcr-6.1.0/lib/vcr/request_handler.rb:24:in `handle'\"
\"/Users/holdenhinkle/.rvm/gems/ruby-3.0.5/gems/vcr-6.1.0/lib/vcr/library_hooks/webmock.rb:135:in `block in <module:WebMock>'\"
\"/Users/holdenhinkle/.rvm/gems/ruby-3.0.5/gems/webmock-3.18.1/lib/webmock/stub_registry.rb:33:in `block (2 levels) in register_global_stub'\"
\"/Users/holdenhinkle/.rvm/gems/ruby-3.0.5/gems/webmock-3.18.1/lib/webmock/stub_registry.rb:39:in `synchronize'\"
\"/Users/holdenhinkle/.rvm/gems/ruby-3.0.5/gems/webmock-3.18.1/lib/webmock/stub_registry.rb:39:in `block in register_global_stub'\"
\"/Users/holdenhinkle/.rvm/gems/ruby-3.0.5/gems/webmock-3.18.1/lib/webmock/request_pattern.rb:40:in `matches?'\"
\"/Users/holdenhinkle/.rvm/gems/ruby-3.0.5/gems/webmock-3.18.1/lib/webmock/stub_registry.rb:73:in `block in request_stub_for'\"
\"/Users/holdenhinkle/.rvm/gems/ruby-3.0.5/gems/webmock-3.18.1/lib/webmock/stub_registry.rb:72:in `each'\"
\"/Users/holdenhinkle/.rvm/gems/ruby-3.0.5/gems/webmock-3.18.1/lib/webmock/stub_registry.rb:72:in `detect'\"
\"/Users/holdenhinkle/.rvm/gems/ruby-3.0.5/gems/webmock-3.18.1/lib/webmock/stub_registry.rb:72:in `request_stub_for'\"
\"/Users/holdenhinkle/.rvm/gems/ruby-3.0.5/gems/webmock-3.18.1/lib/webmock/stub_registry.rb:64:in `response_for_request'\"
\"/Users/holdenhinkle/.rvm/gems/ruby-3.0.5/gems/webmock-3.18.1/lib/webmock/http_lib_adapters/net_http.rb:74:in `request'\"
\"/Users/holdenhinkle/.rvm/rubies/ruby-3.0.5/lib/ruby/3.0.0/net/http.rb:1270:in `get'\"
\"/Users/holdenhinkle/.rvm/gems/ruby-3.0.5/gems/faraday-0.17.6/lib/faraday/adapter/net_http.rb:86:in `perform_request'\"
\"/Users/holdenhinkle/.rvm/gems/ruby-3.0.5/gems/faraday-0.17.6/lib/faraday/adapter/net_http.rb:44:in `block in call'\"
\"/Users/holdenhinkle/.rvm/gems/ruby-3.0.5/gems/faraday-0.17.6/lib/faraday/adapter/net_http.rb:93:in `with_net_http_connection'\"
\"/Users/holdenhinkle/.rvm/gems/ruby-3.0.5/gems/faraday-0.17.6/lib/faraday/adapter/net_http.rb:39:in `call'\"
\"/Users/holdenhinkle/.rvm/gems/ruby-3.0.5/gems/faraday_middleware-0.14.0/lib/faraday_middleware/response_middleware.rb:31:in `call'\"
\"/Users/holdenhinkle/.rvm/gems/ruby-3.0.5/gems/faraday-0.17.6/lib/faraday/response.rb:8:in `call'\"
\"/Users/holdenhinkle/.rvm/gems/ruby-3.0.5/gems/faraday-0.17.6/lib/faraday/response.rb:8:in `call'\"
\"/Users/holdenhinkle/.rvm/gems/ruby-3.0.5/gems/breakers-0.6.0/lib/breakers/uptime_middleware.rb:19:in `call'\"
\"/Users/holdenhinkle/.rvm/gems/ruby-3.0.5/gems/faraday-0.17.6/lib/faraday/rack_builder.rb:143:in `build_response'\"
\"/Users/holdenhinkle/.rvm/gems/ruby-3.0.5/gems/faraday-0.17.6/lib/faraday/connection.rb:387:in `run_request'\"
\"/Users/holdenhinkle/.rvm/gems/ruby-3.0.5/gems/faraday-0.17.6/lib/faraday/connection.rb:138:in `get'\"
\"/Users/holdenhinkle/Documents/Oddball/va_website/vets-api/lib/common/client/base.rb:103:in `request'\"
\"/Users/holdenhinkle/Documents/Oddball/va_website/vets-api/lib/common/client/base.rb:141:in `get'\"
\"/Users/holdenhinkle/Documents/Oddball/va_website/vets-api/lib/common/client/base.rb:97:in `perform'\"
\"/Users/holdenhinkle/Documents/Oddball/va_website/vets-api/lib/va_profile/service.rb:24:in `perform'\"
\"/Users/holdenhinkle/Documents/Oddball/va_website/vets-api/lib/va_profile/demographics/service.rb:24:in `block in get_demographics'\"
\"/Users/holdenhinkle/Documents/Oddball/va_website/vets-api/lib/common/client/concerns/monitoring.rb:11:in `with_monitoring'\"
\"/Users/holdenhinkle/Documents/Oddball/va_website/vets-api/lib/va_profile/demographics/service.rb:21:in `get_demographics'\"
\"/Users/holdenhinkle/Documents/Oddball/va_website/vets-api/modules/mobile/app/serializers/mobile/v0/user_serializer.rb:172:in `block in fetch_demographics'\"
\"/Users/holdenhinkle/.rvm/gems/ruby-3.0.5/gems/parallel-1.22.1/lib/parallel.rb:587:in `call_with_index'\"
\"/Users/holdenhinkle/.rvm/gems/ruby-3.0.5/gems/parallel-1.22.1/lib/parallel.rb:378:in `block (2 levels) in work_in_threads'\"
\"/Users/holdenhinkle/.rvm/gems/ruby-3.0.5/gems/parallel-1.22.1/lib/parallel.rb:597:in `with_instrumentation'\"
\"/Users/holdenhinkle/.rvm/gems/ruby-3.0.5/gems/parallel-1.22.1/lib/parallel.rb:377:in `block in work_in_threads
\"/Users/holdenhinkle/.rvm/gems/ruby-3.0.5/gems/parallel-1.22.1/lib/parallel.rb:222:in `block (4 levels) in in_threads'\"]}}]}"
```

The `uri` in the [VCR cassette](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/mobile/spec/support/vcr_cassettes/user/get_facilities.yml) is:
```
uri: https://sandbox-api.va.gov/services/va_facilities/v0/facilities?ids=vha_757,vha_358
```

I tried swapping it out with this value but then I got a different error:

new value:
```
https://int.vet360.va.gov/demographics/demographics/v1/2.16.840.1.113883.4.349/b2fab2b5-6af0-45e1-a9e2-394347af91ef%5EPN%5E200VIDM%5EUSDVA
```

new error:
```
HTTP request has been made that VCR does not know how to handle:\\n  GET https://sandbox-api.va.gov/services/va_facilities/v0/facilities?ids=vha_757,vha_358\\n\\nVCR is currently using the following cassette:\\n  - /Users/holdenhinkle/Documents/Oddball/va_website/vets-api/modules/mobile/spec/support/vcr_cassettes/user/get_facilities.yml\
```

It's almost like it's looking for both URIs:
- `https://int.vet360.va.gov/demographics/demographics/v1/2.16.840.1.113883.4.349/b2fab2b5-6af0-45e1-a9e2-394347af91ef%5EPN%5E200VIDM%5EUSDVA`
- `https://sandbox-api.va.gov/services/va_facilities/v0/facilities?ids=vha_757,vha_358`

**Comment by holdenhinkle** [comment]
Regarding `rspec "./modules/mobile/spec/request/v1/user_request_spec.rb[1:1:3:1]"`

I just ran the test locally against master and it passed 3 times and failed 3 times :-/

**Comment by holdenhinkle** [comment]
All tests are passing now. Closing this...
