### ISSUE TITLE
Implement IA solution for developer doc portal/hub

### ISSUE THREAD

**Issue by minafarzad** [department-of-veterans-affairs/va.gov-team#548]
## User Story
As a team member building on or with VSP, I need a "front door" to be able to navigate throughout VSP's documentation so I can easily find what I need and build good stuff.

## Goal
A solution that allows users to orient themselves within the world of VSP documentation. Will likely look like a table of contents or index for a first shot at this.

## Acceptance Criteria
- [ ] A live page containing the solution exists @mnorthuis & matt
- [ ] This page has been reviewed and edited and copyedited etc by @peggygannon 

## Definition of Done
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mnorthuis** [comment]
Need to discuss how this work coincides with the Product Dev support team's work.

**Comment by meganhkelley** [comment]
Closing this issue — not bc this is complete but bc this is not how we are tracking this anymore. 

Docs site homepage MVP is #6296 which is part of super epic #2130
