### ISSUE TITLE
Appointment List Re-design - Strikethough updates

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#54816]
## Description
Product and Design team are looking to update the appointment list to help the Veteran better understand the details for their appointment

---

## Acceptance Criteria
Background: the `va_online_scheduling_appointment_list` toggle is on

- [ ] Continue strikethrough for canceled appointments to the modality icon.
    - See the canceled appointment [here](https://www.figma.com/file/JpGM8LGBCqAlL8qh3DmFk8/Home-Page-Redesign?node-id=3871%3A135407&t=7elWI2q1V3qCfVHh-4) for an example of the desired behavior.
    - Currently on staging the strikethrough does not continue through the icon
      <img width="200" alt="Screenshot_2023-03-07_at_7_45_02_AM.png" src="https://images.zenhubusercontent.com/5f7ce3163782a585b910eaf3/db0ebdcb-1b2c-4647-85d6-74ad263c0dcb">

### Design Assets
All spec copy is FPO. Use copy in copy doc.

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by Cieramaddox** [comment]
@ldelacosta - This looks great.

**Comment by ldelacosta** [comment]
No issues reported. Closing out the ticket.
