### ISSUE TITLE
[UX] Update the wireframes that were identified in 54750

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#54810]
## Tasks
- [ ] Update them

## AC
- [ ] Wires are updated

**Comment by loripusey** [comment]
@benbrasso-agile6 @zach-park @ytsaoca this needs to be pointed

**Comment by benbrasso-agile6** [comment]
This will be difficult to point before the dependency is completed. We can guess if that's what we need for planning. I'd give it a 3, in my opinion.

**Comment by kellysmith1008** [comment]
@ytsaoca I tagged you in comments in the unified sketch file on designs that need updating. Some of them are blanket - like almost every additional screen needs the new Need help section, so I didn't tag all of them, but I did mention in the first tag that they all needed updating. Please let me know if you have any questions!

**Comment by ytsaoca** [comment]
It's ready for review @benbrasso-agile6 @kellysmith1008. Thanks!

**Comment by ytsaoca** [comment]
It's ready for review @benbrasso-agile6 @kellysmith1008. Thanks!
