### ISSUE TITLE
Appointment List Redesign - Center row alignment (Tablet & Desktop View) 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#54817]
## Description
Product and Design team are looking to update the appointment list to help the Veteran better understand the details for their appointment

---

## Acceptance Criteria
Background: the `va_online_scheduling_appointment_list` toggle is on

- [ ] Tablet and Desktop: Day number heading should center-align with the row text
    - See  desired behavior in[ this layout guide](https://www.figma.com/file/JpGM8LGBCqAlL8qh3DmFk8/Home-Page-Redesign?node-id=3871-135407&t=hfRrO1IcvqqCWqMa-4)
    - Currently on staging the day # is bottom-aligned to the row text:
     <img width="1042" alt="Screenshot_2023-03-02_at_9_30_52_AM" src="https://user-images.githubusercontent.com/2536801/222574653-e306d339-3ddc-48ec-b8b0-ad963b490812.png">

### Design Assets
All spec copy is FPO. Use copy in copy doc.

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by Cieramaddox** [comment]
@ldelacosta I dont see the changes in this ticket addressed.

**Comment by simiadebowale** [comment]
@Cieramaddox - I center aligned the day div in the date box.

**Comment by Cieramaddox** [comment]
@simiadebowale Ah got it. I'm seeing the changes on tablet, but not on desktop. 

https://images.zenhubusercontent.com/133843125/88bf9400-0dcf-47f1-8c1a-e293221000ac/screen_recording_2023_04_17_at_11_35_24_am.mov

**Comment by Cieramaddox** [comment]
@ldelacosta This looks good!

**Comment by ldelacosta** [comment]
No new issues. Closing out the ticket.
