### ISSUE TITLE
Text message for one appt, but not the other

### ISSUE THREAD

**Issue by manalo-soco** [department-of-veterans-affairs/va.gov-team#54828]
## What happened?
Station: 585
Short Description: Text message for one appt, but not the other
Description: We have a veteran that had a Physical Therapy appointment scheduled for 03/08 & 03/15. He did not get a text message for the 8th but he did get one for the 15th. Both appts were scheduled on 02/15, and it was a multibook appt. Here locally, there were no changes to our setup.

## Specs:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)
- Test User _(if applicable)_:

## Steps to Reproduce
- URL:
- Test User _(if applicable)_:

## Desired behavior
_Describe in detail what was supposed to happen; reference existing Github issue that contains a solution if possible_

## Acceptance Criteria
- [ ] _Describe the desired working behavior_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by jwowk** [comment]
@chancetheoriginal please add cell number

**Comment by jwowk** [comment]
Moved to new board #571
