### ISSUE TITLE
Cancellation remarks in VSE needs to be corrected 

### ISSUE THREAD

**Issue by manalo-soco** [department-of-veterans-affairs/va.gov-team#54827]
## What happened?
The cancellation remarks are incorrect when cancelling by clinic. CLINIC CANCELLED - VEText Appt Cx: ALX WOMENS HEALTH PC NP Appt. on Mar 13,2023 14:00 was cancelled by the Patient. should be cancel by the clinic not by patient.

## Specs:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)
- Test User _(if applicable)_:

## Steps to Reproduce
- URL:
- Test User _(if applicable)_:

![image (3).png](https://images.zenhubusercontent.com/5e9f8d3341903e43c029c13e/352c80e7-7bc8-420b-8932-f366cd13b487)

**Comment by jwowk** [comment]
Updated to state cancelled by clinic
