### ISSUE TITLE
Lighthouse monitoring tools full outage

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#54840]
## PROBLEM STATEMENT
Kong routing will need to be updated to point to traefik instead of the BRD load balancer. As part of the production rollout, we will need to coordinate with the API Gateway team to update the prod routing. 

Staging and Sandbox are underway:
https://vajira.max.gov/browse/API-24911 - Kong - Update vets-api routing for EKS migration (staging)
https://vajira.max.gov/browse/API-24912 - Kong - Update vets-api routing for EKS migration (sandbox) 

**ADDITIONAL INFO**
https://dsva.slack.com/archives/C013VCQKSE7/p1678373209395929

**ACTION ITEMS**

**Comment by LindseySaari** [comment]
Need to check with the LH team to see when they plan on prioritizing this. I will also try to check the Jira tickets

**Comment by LindseySaari** [comment]
Lighthouse team had to adjust their port config from 3004 to 80. 

Staging ✅ - Confirmed by Kevin Gin
Sandbox - [In progress](https://dsva.slack.com/archives/C013VCQKSE7/p1678818913847369?thread_ts=1678373209.395929&cid=C013VCQKSE7)

**Comment by LindseySaari** [comment]
Waiting for confirmation and then I will close this ticket
