### ISSUE TITLE
AWS access for Edmund Dunn

### ISSUE THREAD

**Issue by edmund-dunn** [department-of-veterans-affairs/va.gov-team#54856]
### COR Name

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative Name

Agile Six - Anthony M. Arashiro

### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Edmund Dunn

### Your Email

edmund.dunn@agile6.com

### Team, Role, and Company of the target individual

CMS Team, Drupal Engineer, Agile 6

### Product Manager (PM) name and email

Dawn Pruitt, dawn.pruitt@agile6.com

### Product Owner (PO) name and email

Dave Conlon, dave.conlon@va.gov

### Desired AWS Access

I need access to AWS for the Drupal CMS platform. The group is vfs-cms-infrastructure

### Access Expiration

ongoing

### Additional Notes

COR is Jennifer O'Day

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by little-oddball** [comment]
VFS Roster.

**Comment by BillChapmanUSDS** [comment]
Needd Eqip date added here but can approve this otherwise

**Comment by edmund-dunn** [comment]
@BillChapmanUSDS Eqip date was 10/18/22

**Comment by considerable** [comment]
Account details sent via Slack, closing the tkt.

**Comment by considerable** [comment]
Edmund suggested his access group must be same as for Nathan Douglas. Reopening the tkt to run the change.
