### ISSUE TITLE
Content for "downloadable reports" domain 

### ISSUE THREAD

**Issue by aliyahblackmore** [department-of-veterans-affairs/va.gov-team#54868]
The MHV medical records team needs content that outlines what VA health summary is, what VA Blue Button is, and the difference between the two. 

This is the intake request: [#53881 ](https://app.zenhub.com/workspaces/sitewide-content-accessibility-and-ia-63a1d63232beba0011a7833f/issues/gh/department-of-veterans-affairs/va.gov-team/53881)

[This is the mural with IA work](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1671138122441/c6eae887e8c0467e616d61002f14085580dfb59c?wid=12-1677620663257&sender=u99393afd3329e0f2e2e87196)

[These are some assets from MHV that make be useful 
](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/digital-health-modernization/mhv-to-va.gov/medical-records/assets)

We'll update with more info!

**Comment by aliyahblackmore** [comment]
Noting here that I passed a draft to Laura via Slack.

**Comment by RLHecht** [comment]
Product team has this content. Closing ticket.
