### ISSUE TITLE
Add support for multiple certs with Sign in Service login.gov and id.me interfaces

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#54884]
# Issue Details
Rotating certs on a knife-edge creates unnecessary downtime on our end. We should implement an ability to create new certs and rotate them properly

Rotating certs is fairly well documented at this point within our team docs [here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/vsp/teams/Identity/How-To/Security/Rotate_certs.md) and [here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/vsp/teams/Identity/How-To/Security/SSOe_certs.md). The point of this ticket is to support the use of multiple valid (non-expired) certificates generated by sign in service as well as generated and published by our partners at idme and login.gov.

- We already can support this on vets-api for the certs we generate for saml which are then given to the IAM team. These certs are used to sign our saml requests. We can publish multiple certs to the source code within the manifests repo, specify the code to use a primary and secondary cert, then remove the secondary after the changes have rolled out to our partners. Its all in the documentation listed above (some of it in the PRs). 
- The support of multiple certs generated by our CSPs however has not been created. Both IDme and Login.gov have cert endpoints they publish which we should leverage for this work:
  - [Login.gov openid_connect certs](https://secure.login.gov/api/openid_connect/certs)
  - [ID.me oidc well-known jwks (lists certs)](https://api.id.me/oidc/.well-known/jwks)
 
#### Targeted Settings
- [x] SiS public key - `Settings.sign_in.jwt_old_encode_key`
  - [x] rotation only for `app/services/sign_in/openid_connect_certificates_presenter.rb` - presentation of current & old public key
- [x] Login.gov public cert: `Settings.logingov.oauth_url` / `Settings.logingov.oauth_public_key`
  - only used by old inherited proofing codebase - ignore
- [x] ID.me public cert: `Settings.idme.oauth_url` / `Settings.idme.oauth_public_key`
  - replace with lookup of ID.me public cert & cache in Redis

#### Update Steps
- [x] add cert rotating logic for SiS public key `openid_connect_certificates_presenter`
  - [x] two fields, jwt_encode_key, and jwt_encode_key_old or something like that, and encode with jwt_encode_key but put both in an array for the openid certs presenter
- [x] add new secondary `privatekey.pem` to `spec/fixtures` directory for localhost & testing purposes
- [x] update [environment configs](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/e23a0243692bcc58227f91c76021bb3b89360497/apps/vets-api/staging/values.yaml#L2136) to include new `privatekey`
- [x] add new `privatekey` to AWS parameter store

**Comment by joeniquette** [comment]
I asked chatgpt for a little help explaining this. There is one other part I want to figure out how to explain, Ill add that later. Here is the general technical details according to chatgpt:

To add support for multiple certificates within your Rails application, you need to follow these technical details:

1. **Create a directory for storing your certificates:** Create a directory in your Rails application's root directory to store your certificates. For example, you can create a directory named `certs`.
2. **Add your certificates to the directory:** Add all the certificates that you want to use to verify JWTs to this directory. The certificates can be in PEM or DER format.
3. **Load the certificates in your application:** In your application's code, load the certificates from the directory using the OpenSSL library. You can use the following code snippet to load the certificates:
    
    ```
    require 'openssl'
    
    certs_dir = File.join(Rails.root, 'certs')
    
    certs = Dir[File.join(certs_dir, '*.pem')].map do |cert_file|
      OpenSSL::X509::Certificate.new(File.read(cert_file))
    end
    
    ```
    
    This code loads all the `.pem` files in the `certs` directory and creates an array of `OpenSSL::X509::Certificate` objects.
    
4. **Verify JWTs using the loaded certificates:** When verifying JWTs, use the `JWT.decode` method provided by the `jwt` gem and pass the array of certificates as the `verify` option. For example:
    
    ```
    require 'jwt'
    
    certs_dir = File.join(Rails.root, 'certs')
    
    certs = Dir[File.join(certs_dir, '*.pem')].map do |cert_file|
      OpenSSL::X509::Certificate.new(File.read(cert_file))
    end
    
    jwt = 'your.jwt.token'
    
    decoded_payload, decoded_header = JWT.decode(jwt, certs, true, algorithm: 'RS256')
    
    ```
    
    This code verifies the JWT using all the certificates loaded in the `certs` array. The `true` parameter passed as the second argument to `JWT.decode` indicates that the certificate chain should be verified.

**Comment by bramleyjl** [comment]
Confirmed ID.me public certs are successfully being pulled & cached in staging environment
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc2dPIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--810424442d06ca66346611d0b108e72c6237fb1f/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc2tPIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--891da691e48451f5ec81bd976e48c6cc0014d2e2/image.png)

**Comment by aparsley** [comment]
Keep up the good work!
