### ISSUE TITLE
[Wizard] Update style of FSR link

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#54899]
# Issue Description
Add [primary button style](https://design.va.gov/components/button/) to _Request help with VA Form 5655_

![Screenshot 2023-03-27 at 12.47.18 PM.png](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/9a11cea3-7601-4eea-8e9d-8b84b9fd79a7)
Continuation of #47662

---
## Tasks
- [ ] _Validate and work with Content team to update styling of the FSR link_

## Acceptance Criteria
- [ ] _Direct link to FSR on Wizard will be updated to utilize the action link style_

**Comment by mgleo** [comment]
Adding **blocked** to this ticket. Will ask Platform whether this should be a action link or button since the URL does not change.

**Comment by mgleo** [comment]
#22733 -button vs link

**Comment by mgleo** [comment]
Unblocked: Updated to blue primary button.
Green button has been discontinued and source code shows that it is coded as a button.

**Comment by HeatherRienks** [comment]
Needs to be changed on the Front End. (This is included in ticket  #55628).
