### ISSUE TITLE
Add backend (redis) to docker-compose file

### ISSUE THREAD

**Issue by ianhundere** [department-of-veterans-affairs/va.gov-team#54895]
## Description
Add a redis image to `docker-compose` file just so that the steps in regards to configuring is more streamlined and as an opportunity for @teningnkem and @
vidjovanovic to get more Docker exposure.

## Acceptance Criteria
- [ ] http://localhost:3000/v0/status /  http://localhost:3000 provide the correct output when hit
- [ ] redis image defined in `docker-compose` file

**Comment by rileyanderson** [comment]
This seems more like a training task and not pertinent to this epic
