### ISSUE TITLE
Content Review Model

### ISSUE THREAD

**Issue by minafarzad** [department-of-veterans-affairs/va.gov-team#549]
## High Level User Story
As a _____, I need _____ so I can _____.

## Hypothesis/(es)
**If** _we make this change_ **then** _we expect this to happen_.

## Goals
_What outcome(s) do we want to see?_ 

## Objectives
_Which VSP Objectives does this body of work push forward?_ (`Intake & Onboarding`, `Automation + Instrumentation`, `Support`, `Capacity-building`)

## Definition of Done
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Epic`**

**Comment by meganhkelley** [comment]
This work is captured in epic #2139 and super epic #2137. Closing!
