### ISSUE TITLE
Contact Center Review for CTO Health Team: MyHealtheVet on VA.gov: Landing Page

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#54901]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
This is the landing page for MyHealtheVet on VA.gov.  None of the apps it will eventually connect to have been integrated into VA.gov yet, so the links all currently point to tools on MyHealtheVet.

### Launch Date
We are aiming for a 5% rollout the week of 3/22/2023

### Version Number
V1

### Product Guide
[Product Guide Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/landing-page/contact-center/MHV%20on%20VA.gov%20Landing%20Page%2003212023.docx?raw=true)

### Product Video
N/A

### Product Video Transcript
N/A

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
Hi @MarciMcGuire. The link to the guide comes back as a 404 error. Can you please re-upload it?

**Comment by MarciMcGuire** [comment]
Hi Steven!  Sorry about that.  The link should work now.

**Comment by starlow00** [comment]
Works fine now! Thanks, @MarciMcGuire.

**Comment by MarciMcGuire** [comment]
Great! Thank you!

**Comment by starlow00** [comment]
Hi @MarciMcGuire. This is ready for VEO review, so I'll send it along.

**Comment by MarciMcGuire** [comment]
Thanks, @starlow00 !

**Comment by starlow00** [comment]
No changes from VEO. Current copy attached[https://app.zenhub.com/files/133843125/3078bf64-7836-47a0-8f8a-6bee8a018be4/download](https://app.zenhub.com/files/133843125/3078bf64-7836-47a0-8f8a-6bee8a018be4/download).

**Comment by starlow00** [comment]
Thanks, @MarciMcGuire. I'll make sure VEO has this updated version:
[MHV on VA.gov Landing Page 03212023_srt.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/11056321/MHV.on.VA.gov.Landing.Page.03212023_srt.docx)

**Comment by MarciMcGuire** [comment]
Thanks so much!
