### ISSUE TITLE
Review Selina's first product UI copy 

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#5491]
### This is related to ticket: #5242 Content, design, and a11y review for new terms of service/privacy policy acceptance screens

Summary: The Cerner EHR ("My VA Health") will be slowly coming online for the VA system over the next 10 years, up to a few facilities at a time. Before a Veteran can use Cerner for the first time, they must first accept the new terms of service/privacy policy (similar to a EULA, but this will all be on a single page). The Veteran should only have to accept this policy  once or if these policies have major revisions in the future. If the Veteran does not accept the policy, they cannot log into their Cerner EHR. This prompt occurs *inside* the authenticated MHV experience.

As part of Selina's first authenticated apps UI content assignment, please be review and give feedback. As we're onboarding Selina to this new role (which Peggy used to fill), we want Selina to benefit from Peggy's experience with product UI/microcopy practice. 

Martha's Cerner eta is Feb 7 (but I don't know how hard set that is).

fysa @meganhkelley

**Comment by peggygannon** [comment]
adding Selina's draft copy to this ticket: [EULA-Terms of Service -Copy Deck.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4172520/EULA-Terms.of.Service.-Copy.Deck.docx)

**Comment by peggygannon** [comment]
Hello @lunascoop Please see edits/content recommendations for the My VA Health content. I'm happy to review/explain some of questions on a call if you prefer. 
Cc @jenniferlee-dsva 

[EULA-Terms.of.Service.-Copy.Deck.pg edits.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4195145/EULA-Terms.of.Service.-Copy.Deck.pg.edits.docx)
