### ISSUE TITLE
[CAIA intake] Content and IA Request for Allergies domain from mhv-medical-records

### ISSUE THREAD

**Issue by alexiawunder** [department-of-veterans-affairs/va.gov-team#54922]
## What does your team need support for? Check all that apply.
- [x] Launching one or more unauthenticated pages, online forms, apps, or tools on VA.gov
- [ ] Making revisions to one or more existing VA.gov pages
- [ ] Something else 
 
Note: Based on conversations with Laura and Kristin, I believe this is a content-only ticket. Kristin will combine all of the domains into one IA ticket, but all of the domains will be broken out into individual content tickets. All of medical records will go through the regular collab cycle ticket together. 
 
## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [x] Yes
  - [ ] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
## When do you expect to launch your product to 100% of users?
  October 2024
  
## Supporting artifacts

- Link to product outline: [Medical Records Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/digital-health-modernization/mhv-to-va.gov/medical-records)
- [Link to Allergies domain brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/medical-records/data-domains/allergies/allergies-brief.md)
- Link to or attach user flows: [User flow](https://www.sketch.com/s/f6118ebb-966d-4f83-afba-f9e987b65eac/a/uuid/2AD03D24-0C12-4E89-B8BE-F766E33B18AF)
- Link to prototype or mockups:
  - In Sketch, on the "For Devs and Content" page: 
    - List view [mobile](https://www.sketch.com/s/f6118ebb-966d-4f83-afba-f9e987b65eac/a/uuid/ADEEDDEE-A648-49F6-A50A-2627A6C3F517) | [desktop](https://www.sketch.com/s/f6118ebb-966d-4f83-afba-f9e987b65eac/a/uuid/8BA5C800-0E78-4F56-BB79-E3E323DCAA13)
    - Details view [mobile](https://www.sketch.com/s/f6118ebb-966d-4f83-afba-f9e987b65eac/a/uuid/E4EB5CBF-0056-49C9-828B-C57C30E8D948) | [desktop](https://www.sketch.com/s/f6118ebb-966d-4f83-afba-f9e987b65eac/a/uuid/BB92EA3D-DBB7-4991-B930-D3CA3841C27E)
    - [Alerts](https://www.sketch.com/s/f6118ebb-966d-4f83-afba-f9e987b65eac/a/uuid/5E559355-1E41-49DC-9143-1CDC25D22FE7)
- Link to any epics/issues that may be helpful: N/A

## Will this work be going through the Collaboration Cycle?
- [x] Yes 
- [ ] No

## When does this work need to be done?
- Estimated launch date: ~June 2023
- Estimated staging review date: ~June 2023
- Content and IA work needed by: We'd like to conduct usability testing with approved content at the end of March, 2023

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: mhv-medical-records
- OCTO-DE product owner: Lauren Alexanderson
- Product manager: Bryan Riley
- Designer: Alexia Wunder, Bobby Bailey
- FE engineer: Mike Moyer
- Product/team Slack channel: #mhv-medical-records

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by laurwill** [comment]
Hi @alexiawunder @BobbyBaileyRB ,
Updates here: 
- Intro and "What to know" expandable content for Allergies domain are in the [Medical records working content draft](https://dvagov-my.sharepoint.com/:w:/g/personal/laura_willwerth_va_gov/Eacz1GNGqrdNn3b5gC1j0n4BjNyZ6LyafJCpEfebp-cPVg?e=f6e3Hy)
- Added a couple comments on linked Sketch screens, including new thought on the detail view: I wonder if "Penicillin" as H1 could cause confusion with Rx records. Would we want to do "Allergy: Penicillin" or "Penicillin allergy" or something similar for the H1, to make clear that this is an allergy record?
- **Remaining questions for Allergies domain:** Do we need to tell CHAMPVA beneficiaries and others using Meds by Mail that their allergy records aren't available or aren't complete? And do these users need to tell Meds by Mail separately about their allergies?

cc @AnneCostello @aliyahblackmore @coultonbunney-usds

**Comment by laurwill** [comment]
Allergies is in phase 0, closing
