### ISSUE TITLE
migrate S3 bucket information from vetsgov to vagov tf environments

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#5492]
## User Story or Problem Statement

The vets-api compute resources were migrated into VAEC quite some time ago, but we still have all of the S3 resources being managed in the old Terraform environment. This ticket is to migrate all of the remaining AWS resources that are not tied to a specific VPC migrated out of the old environment and into the new one so they are together for an easier transition to new infrastructure management.

## Goal
_Move S3 buckets and any other resources not tied to a VPC out of the old vetsgov environments and into the corresponding vagov ones._

## Objectives or Key Results this is meant to further
- O1: Any volume of simultaneous customers have a delightful, self-service, end-to-end experience using the Platform to build on VA.gov.

## Acceptance Criteria
- [ ] Review is completed of all resources in the vetsgov environment that reference vets-api
- [ ] ticket migration or removal of any resources identified above that are tied to a VPC from that review
- [ ] migrate any resources not tied to a VPC that can be migrated in-place

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by benniemosher** [comment]
I am showing these folders:

```
dsva-vetsgov-bake/
dsva-vetsgov-dev/
dsva-vetsgov-ew-utility/
dsva-vetsgov-prod/
dsva-vetsgov-ssl/
dsva-vetsgov-staging/
dsva-vetsgov-utility/
```

**Comment by benniemosher** [comment]
Maybe more passes to:

- Move out of module or to cleaner module
- Go through environments and clean up other resources
