### ISSUE TITLE
Content review of medical records: Allergies domain

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#54932]
## Issue Description

We need to give content support on the allergies domain of the medical records section of the health apartment product. This work includes reviewing screens to make sure it meets VA.gov's plain langue and style standards. 

Original intake request; #54922

Artifacts provided by product team:

- Link to product outline: [Medical Records Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/digital-health-modernization/mhv-to-va.gov/medical-records)
- [Link to Allergies domain brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/medical-records/data-domains/allergies/allergies-brief.md)
- Link to or attach user flows: [User flow](https://www.sketch.com/s/f6118ebb-966d-4f83-afba-f9e987b65eac/a/uuid/2AD03D24-0C12-4E89-B8BE-F766E33B18AF)
- Link to prototype or mockups:
  - In Sketch, on the "For Devs and Content" page: 
    - List view [mobile](https://www.sketch.com/s/f6118ebb-966d-4f83-afba-f9e987b65eac/a/uuid/ADEEDDEE-A648-49F6-A50A-2627A6C3F517) | [desktop](https://www.sketch.com/s/f6118ebb-966d-4f83-afba-f9e987b65eac/a/uuid/8BA5C800-0E78-4F56-BB79-E3E323DCAA13)
    - Details view [mobile](https://www.sketch.com/s/f6118ebb-966d-4f83-afba-f9e987b65eac/a/uuid/E4EB5CBF-0056-49C9-828B-C57C30E8D948) | [desktop](https://www.sketch.com/s/f6118ebb-966d-4f83-afba-f9e987b65eac/a/uuid/BB92EA3D-DBB7-4991-B930-D3CA3841C27E)
    - [Alerts](https://www.sketch.com/s/f6118ebb-966d-4f83-afba-f9e987b65eac/a/uuid/BB92EA3D-DBB7-4991-B930-D3CA3841C27E)

## Tasks
- [ ] Review and edit screens 

## Acceptance Criteria
- [ ] Product team has final content

**Comment by aliyahblackmore** [comment]
**Update here:** Passed my review of the list view and detail view to Laura via Slack.

**Comment by laurwill** [comment]
@RLHecht this is another one I thought we closed/can close!
