### ISSUE TITLE
[Design] Direct deposit: Update Sketch files to match production

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#54938]
## Background

While planning the QA for the direct deposit for comp & pen EVSS > Lighthouse migration, I noticed some of the Sketch files did not match production.

### Direct deposit eligible, but not set up

Please update the following Sketch mockups:

- [Desktop 1](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131/a/ZOm73bZ)
- [Desktop 2](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131/a/9P3yvln)
- [Mobile 1](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131/a/4a38jno)
- [Mobile 2](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131/a/PGjgyEQ)

You only need to update the Comp & Pen section, as the Edu section does not allow eligible users to set up direct deposit info online. You can sign in with users 80, 82, or 230 to see this state, but **please do not add any bank info for them, since we can not delete bank info, and we need to preserve this state for these users**. 

![image.png](https://images.zenhubusercontent.com/5a4e5e33a016c5b034bc0750/a84899aa-fb0b-4392-944b-e78832560236)

### Direct deposit eligible and set up

The Edit button should be the filled-in blue state, not the outlined blue state. Please update the following Sketch mockups.

**Desktop**

- [Desktop 1](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131/a/uuid/063136B7-BB05-436E-AB28-219514611986)
- [Desktop 2](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131/a/uuid/B0DEB05C-F148-4202-A685-8A21B0769487)
- [Desktop 3](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131/a/uuid/BEE6DDB6-ECD5-4655-A7F8-AF1B171619D7)
- [Desktop 4](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131/a/uuid/674F5EA2-10FA-4D00-B324-D728911DAB3A)
- [Desktop 5](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131/a/uuid/2C1B7D38-6712-4E34-BDE8-1C42EFE1A996)
- [Desktop 6](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131/a/uuid/0F8C0957-5FE4-42AC-AFC6-BD5184F9E50F)
- [Desktop 7](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131/a/uuid/01D4D617-7D37-4A15-AE98-5617F9D6B135)
- [Desktop 8](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131/a/uuid/82E3E2F7-712E-41E3-9E49-D09A2B99A548)
- [Desktop 9](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131/a/uuid/70721B89-A05B-4894-827F-8F18B4D0558A)
- [Desktop 10](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131/a/uuid/127C057C-663D-4976-A69D-5FE16CB8AEB0)

**Mobile**

- [Mobile 1](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131/a/uuid/5816B06F-1B86-42A2-988C-1CE5880EF7B6)
- [Mobile 2](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131/a/uuid/DD2AB0E9-E5A3-4815-967F-3A3AC15AC181)
- [Mobile 3](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131/a/uuid/7B382F45-C68E-4A04-B8C1-30CD8E589165)
- [Mobile 4](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131/a/uuid/54239C0A-D025-486B-94D0-51130AD74044)
- [Mobile 5](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131/a/uuid/EA39010C-77B6-4F98-8C07-9B4132CB610A)
- [Mobile 6](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131/a/uuid/70786054-F4C3-4F8C-8E08-C625949510FC)
- [Mobile 7](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131/a/uuid/293C05D4-B578-4269-A4DD-CD106D9B1C67)
- [Mobile 8](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131/a/uuid/5D4DB42D-93BB-4181-B5E7-22EAF157C393)
- [Mobile 9](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131/a/uuid/5004C1DA-DA92-43AD-B456-C1A6FA94D0FD)

 You can sign in with users 81, 201, 226, or 378 to see this state.

![image.png](https://images.zenhubusercontent.com/5a4e5e33a016c5b034bc0750/832a2232-8f89-44c5-bbb2-8fc4826044df)

## Tasks

- [x] Update all mockups as outlined above.

**Comment by Samara-Strauss** [comment]
I have this in sprint 6, but it can get pushed back a sprint or two in favor of other work.

**Comment by BerniXiongA6** [comment]
If design needs additional work in Sprint 6, you can grab this ticket. Otherwise, we can push out to Sprint 7.

**Comment by andaleliz** [comment]
Mock-ups are updated! Thanks for all the links provided @Samara-Strauss, that helped me QA myself to be sure I got it all :)
