### ISSUE TITLE
prevent users not registered at a facility from seeing MHV on VA.gov landing page

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#54958]
if a user does not have any values in `user/va_profile/facilities`, do not allow them to navigate to va.gov/my-health and see the new authenticated landing page. instead, they will continue to be directed to the MHV portal.

**Comment by mdewey** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/23612
