### ISSUE TITLE
Midpoint Review - IA Feedback - Public Websites, Income Limits, Income Limits Web App

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#54953]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
- I am amazed at how far this has come since the Design Intent (I wasn't around then, so I watched the recording). This is in a really good place and is **hugely** improved from the previous legacy experience. 
- Great conversation guide and I really appreciate the attention to findability tasks there - I think these questions uncover good language and potential placement suggestions from research participants that align with their mental models. I look forward to reading the results!

## Feedback
- Practice areas will document their feedback following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback).

**Must:**

**Should:**

**Consider:**
* The Figma prototype on deck to be used with research participants uses a deep link on the Costs of Care page as the point of entry to this tool. I don't have any quant data on where users look for this tool most frequently to inform anything here - but it's possible that the left-nav placement suggested [in the IA ticket](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/income-limits.md) would be a more frequently used access point. Knowing it's planned destination is pretty far down in that sub-menu list, the cross-linking from other pages is a great way to drive additional discovery. I would love to see the left-nav placement tested with users and would nudge some exploration on that. But if it's too late, I think your findability questions will address the concern. cc @kristinoletmuskat @mnorthuis 

## Platform directions
- Remove the governance-team label
- Update "Issue Title"
- Link to collab cycle Request epic
- Add your feedback
- Remove the CC-Request label (only if you created the ticket using the New Issue link from the Collaboration Cycle Reviews board)
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review QA Only**: VFS PM, yourself (optional)

**Comment by cindymerrill** [comment]
We made a change to the income limits design prototype yesterday so we now link from TWO places in our static screenshot of the "Your health care costs" page: 

1. Under “Will I need to pay for any of my care, tests, or medications?” in the link [Go to the Health Benefits Explorer](https://www.va.gov/healthbenefits/apps/explorer) -- and we've changed the link to "Check our current income limits" so it matches the text in 2 below. This was done with @DanielleThierryUSDSVA 's approval.
2. Under “Does VA verify the information I provide?” in the link [Check our current income limits](https://www.va.gov/healthbenefits/apps/explorer/AnnualIncomeLimits/HealthBenefits) (this is a lot farther down the page)

**Comment by sterkenburgsara** [comment]
@cindymerrill yes, thank you so much for calling that out in the meeting and again here for tracking: the higher placement of that first link & having two total links on the page is great. The nav placement is something I wanted to note for consideration, since I don't otherwise know how we can evaluate that placement with Veterans - but you can absolutely take or leave my feedback.

**Comment by kristinoletmuskat** [comment]
Hello! Chiming in with another point @sterkenburgsara and I were chatting about. I wonder if there will be confusion around the income brackets being "$ or less" -- Like if you make 29,930 or less, you also make 90,089 or less. Could veterans be confused about whether the diff 'things' they get with each income bracket are additive or not? Why did we decide to go with this 'or less' approach, rather than income bands like "$29,930-$43,920"?

 ![Screenshot 2023-03-10 at 11.46.27 AM.png](https://images.zenhubusercontent.com/63c829f1a7fcfd33a1b47c17/06d8f219-941e-47e8-99e6-2e28a7979c93)

**Comment by cindymerrill** [comment]
Good point! 
@thejordanwood Did you ever consider have salary ranges in your designs? This wording was recommended by @DanielleThierryUSDSVA , but I don't know whether she considered salary ranges either.

**Comment by DanielleThierryUSDSVA** [comment]
Hi there. From my recollection, I don't think the original prototype had ranges and I think we edited based off that. But I think ranges would work just find for the middle 3. If you want to change that before testing, go for it. If you want to leave it to find out if there's confusion with what's there now, that's fine too. Thanks!

**Comment by cindymerrill** [comment]
I think that ranges would be great to test, @thejordanwood

**Comment by wesrowe** [comment]
I concur – especially given the interpretation our pilot user had, which seemed very natural to me.

**Comment by wesrowe** [comment]
This could have closed in June. Closing now.
