### ISSUE TITLE
[03/31/23] Pull List of VEText Users By Role

### ISSUE THREAD

**Issue by lindsay-insco** [department-of-veterans-affairs/va.gov-team#54965]
## Description
In order to ensure our user list and admins are up-to-date in VEText and comply with our ATO, the product support team is tasked with conducting an annual audit of VEText users, and ensure admins are trained and informed of their responsibilities as administrators in VEText. 

In order to complete this, the team needs an updated list of current VEText users. We will need:
- Name
- Role
- VISN
- Station

---

## Acceptance Criteria

- [x] Pull data
- [x] Share with helpdesk team

---

**Comment by Cmjones233** [comment]
completed and sent 3/27
