### ISSUE TITLE
[03/22/22] Annual VEText Audit Admin Training Schedule

### ISSUE THREAD

**Issue by lindsay-insco** [department-of-veterans-affairs/va.gov-team#54963]
## Description
In order to ensure our user list and admins are up-to-date in VEText and comply with our ATO, the product support team is tasked with conducting an annual audit of VEText users, and ensure admins are trained and informed of their responsibilities as administrators in VEText. 

To complete this obligation we need to ensure training is scheduled for each admin, and in order to conduct this, group training is pre-scheduled in advance to ensure users have ample time to attend. 

A schedule needs to be created for this based on prospective monthly deadlines the team has set. 

---

## Acceptance Criteria

- [X] Break apart VISNs to be audited by month (The team will follow this schedule for the audit to ensure training is afforded enough time)
- [X] Build schedule
- [X] Share with team
- [X] Approved by team
---

**Comment by djfredvs** [comment]
Preliminary VISN Admin training schedule sent to Lindsay 3/13/23
