### ISSUE TITLE
Configure ArgoCD routes to make preview environments accessible from a browser

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#54977]
# Description
In order to test preview environments, we need them to be accessible via a browser prior to the public routes being setup. How can we configure ArgoCD to assign a URL dynamically when a preview environment is deployed? How can we configure preview environments to be routable from within the VA's boundary?

# Tasks
- [ ] Create routes to each preview environment as they are created using a template

# Acceptance Criteria
- [ ] Each preview environment is assigned a hostname that is routable from inside the VA's boundary like if the user is connected to SOCKS or CAG

**Comment by JoeTice** [comment]
Work is in progress, was started after clearing the FE Image creation blockers, did not have time to complete it this sprint, work will extend into Sprint 23.

@cyriltech - please provide an explanation of where this work stands, or link to a document that describes that

**Comment by cyriltech** [comment]
Here is a [link](https://vfs.atlassian.net/l/cp/xkkXvCoe) to documented progress. Doc will be updated with every step and progress.

**Comment by JoeTice** [comment]
Updates being provided to the document linked by Cyril above...

So far, the issue of domain names being too long and failing to create is resolved. Now we have records created on route 53 for test app. However from the browser “vets-website-test-ecr-docker-i-dev.vfs.va.gov” we are getting “Invalid Host Header” I have look into ingress.yaml, external dns and host for deployment.yaml all looks good.

what next?

Look into Treafik configuration, make sure issue is not related to webpack

Update

Issue related to invalid host Header is resolved. From the browser we can see vets-website @vets-website-test-ecr-docker-i-dev.vfs.va.gov

At the moment vets-website is being served without content-build

Next steps:

The next step is to have vets-website and content-build visible from the browser.

**Comment by cyriltech** [comment]
![image.png](https://images.zenhubusercontent.com/6385292bddbc0cbb14b84a51/12fcabe3-1c92-4ff0-bed3-1b533d5da343) vets-website and content-build is successfully configured to be routable from the browser. Credit to @pjhill and @CBonade for their efforts.

**Comment by pjhill** [comment]
The routing portion of this is solved -- yay!
