### ISSUE TITLE
Create a workflow in `vets-api` to generate a new Docker image when `main` changes

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#54989]
# Description
In order to keep Docker image that contains the most recently merged to main code available in ECR, we need a workflow that is driven by a push to main event to generate an image using our PE Dockerfile and tag it as main:latest.

# Acceptance Criteria
- [ ] When a branch merges to main a workflow generates a new version of the backend main Docker image and pushes it to ECR

**Comment by CBonade** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/12145 PR open for review here

**Comment by CBonade** [comment]
merged

**Comment by pjhill** [comment]
So close to opening the floodgates -- thanks for knocking this out!
