### ISSUE TITLE
Finalize GHA to build, tag, and store the backend image defined by the Dockerfile when a push event occurs on a feature branch

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#54991]
# Description
Currently, the backend workflow does not generate an image because the image generation logic is commented out. We need to ensure that the code to generate the Docker image for the backend is active, generating functioning images, and pushing them to ECR.

# Acceptance Criteria
- [ ] The backend image generation process is pushing feature branch Docker images to ECR
- [ ] The reference to the backend image is written to the values file for the preview environment
- [ ] The ArgoCD deployment of the backend image generated by this workflow does not produce errors

**Comment by CBonade** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/12170 PR open for these changes here.

**Comment by pjhill** [comment]
Nice, looking good to go -- soon we will open the floodgate!
