### ISSUE TITLE
Document & publish content review process

### ISSUE THREAD

**Issue by minafarzad** [department-of-veterans-affairs/va.gov-team#550]
## User Story
As a member of a team building with or on VSP, I need to know how the content review process will work so I can manage my team's workflow.

## Goal
Teams understand what the review process is and what to expect when pushing content onto VA.gov.

## Acceptance Criteria
- [x] A markdown page in GitHub exists that explains the content review process for a builder audience
- [x ] That page exists in the right place according to @mnorthuis IA model :)
- [x] Send to DSVA for review/feedback

**Comment by peggygannon** [comment]
@minafarzad @mnorthuis

The Content Review process document is located on the va.gov-team repo here:  https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/Practice%20Areas/Content/content-review-process.md

@mnorthuis Can you let me know if this location is OK per the documentation recommendations you are working on? or this document move to the va.gov-vfs-teams repo? 

@minafarzad This document is ready to share with DSVA stakeholders for their review and feedback.

**Comment by mnorthuis** [comment]
@peggygannon This location is fine until we finalize structure.

**Comment by rroueche** [comment]
Looks good! We have additional issues to iterate from here based on testing w/VFS Teams and DSVA feedback.
