### ISSUE TITLE
Update Documentation for SOCKs Setup

### ISSUE THREAD

**Issue by rmessina1010** [department-of-veterans-affairs/va.gov-team#55007]
Update Documentation for SOCKS setup to include the following tip:

> I've had some difficulty accessing tools like Sentry and Grafana. I went through all the steps to set up SOCKS Proxy, can confirm it was running, but still couldn't access those tools.
> What worked for me was in my MacOS System Preferences going to the Proxies settings in the Network section and turning on "Auto proxy discovery" and changing the Automatically proxy configuration file from some localhost address to https://raw.githubusercontent.com/department-of-veterans-affairs/va.gov-team/master/scripts/socks/proxy.pac

Slack Source: https://dsva.slack.com/archives/CBU0KDSB1/p1678379102073689

Documentation: 
https://vfs.atlassian.net/wiki/spaces/PWD/pages/2178187323/Install+SOCKS+proxy+on+Mac

https://depo-platform-documentation.scrollhelp.site/getting-started/accessing-internal-tools-via-socks-proxy#on-mac

Definition  of Done
- [ ]  The excerpt above has been  reworded and incorporated in the MAC SOCKS setup documentation
- [ ]  If the excerpt applies, incorporate it to other OS's SOCKS set up documentation

**Comment by rmtolmach** [comment]
I see that the documentation is updated with this tip. Closing. https://depo-platform-documentation.scrollhelp.site/getting-started/accessing-internal-tools-via-socks-proxy#AccessingInternalTools(viaSOCKSProxy)-Troubleshooting-For-MacTroubleshootingforMac
