### ISSUE TITLE
SPIKE: [FE] Explore Architecture Changes Necessary to Support Unified Experience

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#55019]
## Timeboxed
2 sync meetings (1 to cowork, 1 to come back w/ answers)

## Description
We need Engineering to think through in detail how we would support the work needed for the Unified Experience MVP. 

## Questions to Answer
- What do we need to spin up a new app
    - https://depo-platform-documentation.scrollhelp.site/developer-docs/creating-a-new-application
- Can we use FF to toggle between the 2 apps
    - A few options, but none of them feel great:
        - We could have the URL shortener determine the destination. The downside is that we can't use a feature flip and it would send people at random. A patient wouldn't have a constant experience.
        - It could be done in rev proxy. Would need to get more information on what is possible here.
        - We could create a small switch board type application that routes based on the feature cookie ID. This has points for its simplicity but means we are potentially adding to load times by directing through two applications every time.
- What are our new URL structures going to look like (new router?)
    - One idea was `/health-care/appointment-tasks/`

**Comment by loripusey** [comment]
@benbrasso-agile6 can you attach a link to the UX wireframes for this in this ticket? thanks.

**Comment by benbrasso-agile6** [comment]
Updated
