### ISSUE TITLE
[Letters App to Lighthouse] Integrate backend/frontend

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#55021]
In order for the Letters App to be fully migrated, we need to incorporate any changes made to how vets-api returns data to the frontend application.

Done when:
- [ ] All unit tests pass
- [ ] All E2E tests pass

Notes:
- Assuming the context of this ticket is local development since we wouldn't want to push something to `main` without a feature flag. Is this true?
- The priority of this probably comes after the feature flag, actually
- How do we test something behind a feature flag in staging?

**Comment by samcoforma** [comment]
To-do:

[] - make sure devops PRs get merged: https://dsva.slack.com/archives/CBU0KDSB1/p1682360422153539
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/1681
https://github.com/department-of-veterans-affairs/devops/pull/12728
[] - Follow up with Jerek about whether broken config values behind conditionals would trigger errors. If we don't have the devops stuff in prod before the new letters app goes to prod, will it break things even though it's behind a feature toggle?
[] -
