### ISSUE TITLE
Add Workflow to 686: "Add a Spouse" - Part 1

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#5503]
## Story
As a Veteran using the 686 in VA.gov, I want to be able to adjust my claim to account for a new spouse so that I can maintain an accurate representation of my status with the VA.

## Goal
Include the necessary schema workflows and submit PRs for them to be incorporated.  This will fully flesh out the rest of the workflows to coincide with what has already been put out.

## Considerations
- When these are done as multiples, there are merge conflicts that will need to be carefully addressed.
- [Mockup](https://xd.adobe.com/view/ffffe536-2ba5-47c6-4c4b-ac1679179973-89ce)
- Include the spouse as a veteran as well
- This ticket might be broken up into parts based on pages (include pages 1, 2, and 3)

## Tasks
- [x] Add and/or remove the necessary schema at the workflow level and ensure there are no validation errors.

## Acceptance Criteria
- [x] A PR has been requested and completed for `vets-website`

**Comment by micahchiang** [comment]
Pull request has been merged.
