### ISSUE TITLE
DS Logon Sunset Comms Strategy 

### ISSUE THREAD

**Issue by APorter-Clarity** [department-of-veterans-affairs/va.gov-team#55045]
###Description of UX Tasks
Sync with LGA Team to discover what research has been done with the following comms: 
- email
- physical mail (USPS)
- blog/newsletter post
- pre-login- post-login (modals)
- post-login req acknowledgment (Asks user to confirm they understand that the sunset is happening)
- Aug: Begin blocking (modal to remind the user *who is logging in with DS Logon to use ID.ME/Login.gov to login)
- Sept: remove DSL Button
- Post-removal language

#### Acceptance Criteria
- [x] Meeting with LGA Team

#### Product notes
TBD

#### Artifacts
TBD

**Comment by aparsley** [comment]
The LGA Team is taking this initiative over.
