### ISSUE TITLE
Socialize analytics research

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#55046]
#### Acceptance Criteria
- [x] [Slide Deck Readout](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Research/2023-02%20Desk%20Research/Identity%20Desk%20Research%20Share.pdf) published in research drive
- [x] [Card for research](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/256) made on VA research repo
- [x] Presentation made to VA's Monday UX meeting (Mar 20)

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by michelle-dooley** [comment]
@claytonzook - is this in relation to this ticket [Capture and publish data available to researchers #48656](https://github.com/department-of-veterans-affairs/va.gov-team/issues/48656)?

**Comment by claytonzook** [comment]
@michelle-dooley - negative. It relates to this ticket - [Research device types and capabilities of Va.gov users](https://app.zenhub.com/workspaces/identity-5f5bab705a94c9001ba33734/issues/gh/department-of-veterans-affairs/va.gov-team/53876)

**Comment by michelle-dooley** [comment]
That is our label that assigns to our board so unless you need us then yeah shouldn't use that one.
