### ISSUE TITLE
[Bug] Profile - Address Validation - Entered address selection IE11 quirk

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#5505]
## What happened?
On Staging Profile, editing Mailing Address and inputting an invalid one, the entered address under **You entered:** cannot be selected by clicking the radio button.  You have to click the street address (line 1) to select.

## Specs:
- Browser: Win IE11
- Test account: `vets.gov.user+56@gmail.com` \[see credentials [here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv)]

## Steps to Reproduce
1. Go to https://staging.va.gov/profile/ \[Sign in as test-account 56].
1. Under **Contact information**, click **Edit** next to **Mailing address**.
1. Change the address to one from [this test-cases table](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/change-address/address-validation/qa-508/test-cases.md).
NOTE: Any test-case EXCEPT Overridable, No Suggestions will replicate this Bug, but for bugfix all cases should be validated.

## Desired behavior
Entered address is selectable by clicking the radio button.

## Acceptance Criteria
\[see **Desired behavior** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by Samara-Strauss** [comment]
@erikphansen @bradl3yC I know you both are in the middle of work that I don't want to interrupt. Assigning both of you to this bug and we can decide how to handle it next sprint.

**Comment by bradl3yC** [comment]
dev notes: this likely has to do with margins / box sizing of the label / input.

**Comment by bradl3yC** [comment]
@tlei123 can we get screenshots or a video snippet? I am having a tough time getting IE11 to run on my mac/vm installation

**Comment by tlei123** [comment]
@bradl3yC, here's a [video-capture](https://drive.google.com/file/d/14iOzsrKfsZssVo5a4XxZBpJvwv_Yrz7-/view?usp=sharing) of the bug.

Note how the address can't be selected by clicking the radio button \[CSS `cursor: pointer`]; it can only be select by clicking on the address text \[CSS `cursor: default`].

Thanks much & good luck!  :)

**Comment by bradl3yC** [comment]
@tlei123 muchhh appreciated.. This is a style/height issue on some of the elements :)

**Comment by bradl3yC** [comment]
@tlei123 can you verify the fix in staging?

**Comment by Samara-Strauss** [comment]
@tlei123 giving this a gentle nudge — can you validate? We're trying to close out tickets for this sprint and do planning for the next.

**Comment by tlei123** [comment]
@Samara-Strauss, sorry I missed this yesterday!

Verified fix on Staging against Win IE11; Closing ticket now.
