### ISSUE TITLE
Midpoint Review - Accessibility Feedback - Login.gov adoption team, DS Logon Grandfathering / Inherited Proofing

### ISSUE THREAD

**Issue by briandeconinck** [department-of-veterans-affairs/va.gov-team#55066]
## VFS acceptance criteria
- [x] Let Platform know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [x] VFS team closes the ticket

## Thoughts/questions
- This all looks great! Thank you for incorporating feedback from the Design Intent and for walking us through the user flows again today. This is all really helpful.

## Feedback
- Practice areas will document their feedback following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback).

**Must:**
- [Double-check the contrast ratio](https://webaim.org/resources/contrastchecker/) between the link and the background for the new experimental link style. I'd like to see a 7:1 ratio or better to meet the AAA standard, and please let me and @humancompanion-usds know if you're having any trouble reaching that level of contrast with the colors available in the design system.
- I'm not sure if @humancompanion-usds has spent any time thinking about `:hover` and `:focus` states for the new link style, but now is a good time to start! However the link and background colors may change for different states, those will also need to have 7:1 contrast ratios as well. Again, let me know if you have trouble finding a combination of colors that makes sense for these states and meets that requirement.
- I forgot to mention this in the meeting, but on the [Get the most out of your Login.gov account](https://www.figma.com/proto/8vobVoSl1UqLnXsni3rcvO/Login.gov-Migration%3A-Grandfathering-IAL1-Flow?node-id=2%3A2664&scaling=contain&page-id=0%3A1&starting-point-node-id=41%3A1311) modal, the "No thanks, I don't need to verify" action closes the modal, correct? If so, it should be a secondary button rather than a link since it's staying on this page and not navigating the user elsewhere.

**Should:**

**Consider:**

**Code implementation:**
Both user flows have users navigating to a page with an open modal:
- [Create a Login.gov account](https://www.figma.com/proto/8vobVoSl1UqLnXsni3rcvO/Login.gov-Migration%3A-Grandfathering-IAL1-Flow?node-id=1%3A13&scaling=contain&page-id=0%3A1&starting-point-node-id=41%3A1311)
- [You signed in with Login.gov](https://www.figma.com/proto/8vobVoSl1UqLnXsni3rcvO/Login.gov-Migration%3A-Grandfathering-IAL1-Flow?node-id=2%3A2608&scaling=contain&page-id=0%3A1&starting-point-node-id=41%3A1311)
- [Get the most out of your Login.gov account](https://www.figma.com/proto/8vobVoSl1UqLnXsni3rcvO/Login.gov-Migration%3A-Grandfathering-IAL1-Flow?node-id=2%3A2664&scaling=contain&page-id=0%3A1&starting-point-node-id=41%3A1311)
- [We encountered an error](https://www.figma.com/proto/8vobVoSl1UqLnXsni3rcvO/Login.gov-Migration%3A-Grandfathering-IAL1-Flow?node-id=2%3A2647&scaling=contain&page-id=0%3A1&starting-point-node-id=41%3A1311)

The modal component in the design system is built around the assumption that users take some action on the page (click a button) to open the modal. Keyboard focus moves to the modal when it opens and stays inside it while they're using the modal. Then, if/when they close the modal, keyboard focus returns to the button or other control they used to open the modal in the first place --- basically, taking them back to where they were before they started their modal side quest.

When users land on a page with a modal that's already open and they close the modal, there's no button or other control for focus to return to, since the user wasn't the one who opened the modal in the first place.

This matters for two big reasons:
- For screen reader users, what has focus determines what gets announced by their screen reader next. Something has to get focus (otherwise you just get a confusing silence), and the thing that gets focus should make sense for whatever their next task is.
   - Testing: Activate a screen reader, then close the modal. What's the first thing that gets announced after closing, and does it make as the next thing you should hear?
- For sighted keyboard-only users, what has focus determines what's next when they press [Tab]. Again, this should make sense for whatever their next task is, otherwise they'll get sent off somewhere unexpected on the page and have to [Tab] around to get back to where they want to be.
   - Testing: Close the modal, then press [Tab]. Does the next thing to get focus correspond to where your attention?

From the prototypes, it looks like users are always on My VA when they encounter these modals. If so, I would make sure focus goes to wherever focus would go if a user weren't going through this workflow (I'm not sure if that's the H1 or the nametag above it, you may want to check in with the My VA team on that). If a user will ever encounter one of these already-open modals on another page, you'll need to make this decision for those pages too.

This is probably too long-winded of an explanation, but it's one of those things that's easy to forget about and has a big impact! Let me know if there are any questions or if any of this doesn't make sense.

## Platform directions
- Remove the governance-team label
- Update "Issue Title"
- Link to collab cycle Request epic
- Add your feedback
- Remove the CC-Request label (only if you created the ticket using the New Issue link from the Collaboration Cycle Reviews board)
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review QA Only**: VFS PM, yourself (optional)

**Comment by humancompanion-usds** [comment]
@briandeconinck and @MOStudioCarolyn - I have created 2 variations of the larger Active link style here:

https://www.sketch.com/s/be292806-8dbf-4201-bfa7-0edbba103347/p/3DB6F4DD-A6B9-4BC5-9760-E2BDCB01C8ED/canvas

Something like v2 is what I saw in the modals presented as part of this work. I would stick with v2 for the modals. If you have needs outside of modals you could test with v3 as well. There are hover, focus, and active symbols for both variations.

**Comment by MOStudioCarolyn** [comment]
Notes on Must feedback: 
• Updated background to the lightest gray, so it passes AAA
• I have seen mock ups of focus and hover states for the Close button, and will be shared with front-end devs
• I will update to a button for accessible testing to be conducted.
