### ISSUE TITLE
VAOS FE Generic Alert Message for Upcoming list - HSRM/VVS/VSP is down (MVP) 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#55068]
## Description
In production, the following systems that could potentially be down are VSP, VVS and/or HSRM. When any of the systems are  unavailable, the frontend will display a generic message to the user that their appointments may be unavailable to view.

This work will focus on the Upcoming list. 

The backend service is returning an error in the response body for VSP (sample below): 
```
"system": "VSP",
"status": "500",
"code": 10000,
"message": "Could not fetch appointments from Vista Scheduling Provider",
"detail": "icn=1013120820V528557, startDate=2023-01-08T00:00Z, endDate=2024-03-08T00:00Z"

```

## Acceptance Criteria

- [ ] Given VSP system is down 
        When the user views their upcoming appointment(s)
        Then the application will display an alert message 
        And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/alert-copy-docs/upcoming-view.md#upcoming-appointments) 
        

- [ ] Given VVS system is down 
        When the user views their upcoming appointment(s) 
        Then the application will display an alert message 
        And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/alert-copy-docs/upcoming-view.md#upcoming-appointments) 
 

- [ ] Given HSRM system is down 
        When the user views their upcoming appointment(s)  
        Then the application will display an alert message 
        And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/alert-copy-docs/upcoming-view.md#upcoming-appointments) 

- [ ] Given VSP and VVS systems are down 
        When the user views their upcoming appointment(s)
        Then the application will display an alert message 
        And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/alert-copy-docs/upcoming-view.md#upcoming-appointments) 

- [ ] Given VSP and HSRM systems are down 
        When the user views their upcoming appointment(s) 
        Then the application will display an alert message 
        And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/alert-copy-docs/upcoming-view.md#upcoming-appointments) 

- [ ] Given VVS and HSRM systems are down 
        When the user views their upcoming appointment(s) 
        Then the application will display an alert message 
        And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/alert-copy-docs/upcoming-view.md#upcoming-appointments) 

- [ ] Given VSP, VVS and HSRM systems are down 
        When the user views their upcoming appointment(s) 
        Then the application will display an alert message 
        And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/alert-copy-docs/upcoming-view.md#upcoming-appointments) 

### Example (mobile view)

Default view of the alert message: 
<img width="337" alt="Screenshot 2023-03-22 at 11 14 43 AM" src="https://user-images.githubusercontent.com/90797205/226950782-c438ed6c-2754-4b29-94fe-6cc874fb7206.png">

User will click on the dropdown arrow to expand the message: 
![Screenshot 2023-03-21 at 3.42.58 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/22849173-4571-4e89-aac6-ca8a2a7a05af)

### Design Assets
[Figma File - Design Spec](https://www.figma.com/file/9ZOtrJqv7Ze4ptVHMtE1iJ/Alert-users-when-VAOS-can't-display-appointments?node-id=1045-1555&t=XMchNRXXhrIWhCWk-0#396358145)
[Storybook web component](https://design.va.gov/storybook/?path=/docs/components-va-alert-expandable--warning#warning) 

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by marcynadeau** [comment]
Related to this GitHub ticket:  https://issues.mobilehealth.va.gov/browse/VAOSR-5743

**Comment by ryanshaw** [comment]
**Desktop** (`$large-screen` breakpoint)

![localhost_3001_health-care_schedule-view-va-appointments_appointments_($large-screen).png](https://images.zenhubusercontent.com/57b5cce1e40e5714b16d8493/f8dd5d07-d8f8-4b31-a601-92dfac8ff878)

![localhost_3001_health-care_schedule-view-va-appointments_appointments_($large-screen) (1).png](https://images.zenhubusercontent.com/57b5cce1e40e5714b16d8493/c78c2d5e-5bec-44ff-b5a1-9c63e5260c01)

**Tablet** (`$small-screen` breakpoint)

![localhost_3001_health-care_schedule-view-va-appointments_appointments_($small-screen).png](https://images.zenhubusercontent.com/57b5cce1e40e5714b16d8493/dff84355-3f8c-459b-bb07-630dbe7b9459)

![localhost_3001_health-care_schedule-view-va-appointments_appointments_($small-screen) (1).png](https://images.zenhubusercontent.com/57b5cce1e40e5714b16d8493/6e0fb4e5-8479-4530-b187-14f59d301fa4)

**Mobile** (`$xsmall-screen` breakpoint)

![localhost_3001_health-care_schedule-view-va-appointments_appointments_($xsmall-screen).png](https://images.zenhubusercontent.com/57b5cce1e40e5714b16d8493/41d29b80-9e7d-4092-8307-1b5a6e2d09c9)

![localhost_3001_health-care_schedule-view-va-appointments_appointments_($xsmall-screen) (1).png](https://images.zenhubusercontent.com/57b5cce1e40e5714b16d8493/4e81e8b3-920d-4ba3-a62f-df8f06a4f742)

**Comment by ldelacosta** [comment]
No issues reported. Closing out the ticket.
