### ISSUE TITLE
Remove any references of va_online_scheduling_status_improvement feature toggle

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#55085]
## Description
We no longer need to reference the feature toggle `va_online_scheduling_status_improvement` in the frontend code. The Status List improvement feature went 100% in production in 2022. The product team is requesting to remove any references of the feature toggle. 

---

## Acceptance Criteria

- [ ] Remove any references of the feature toggle `va_online_scheduling_status_improvement` 
- [ ] Delete the feature toggle `va_online_scheduling_status_improvement` in [staging](https://staging-api.va.gov/flipper/features/ ) and [production]( https://api.va.gov/flipper/features)

### Design Assets
N/A

## Definition of Done
- [ ] All acceptance criteria are met
- [x] Documentation is updated

---

**Comment by ldelacosta** [comment]
Note: 20 files associated with this feature toggle.

**Comment by ldelacosta** [comment]
@young1205 - please notify @JRRoof to validate

**Comment by ryanshaw** [comment]
@ldelacosta There is currently a PR in progress that removes the remaining instances of this feature flag.

**Comment by JunTaoLuo** [comment]
All code changes are merged and deployed. Feature toggle removed from non-production environments (dev, sandbox, staging) and removal from production environment is tracked in https://github.com/department-of-veterans-affairs/va.gov-team/issues/84111

**Comment by ldelacosta** [comment]
This has been completed. Closing out the ticket.
