### ISSUE TITLE
Adapted is spelled wrong on the "Specially Adapated Housing Grant" page

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#55084]
### Description

"Adapted" is spelled wrong as "Adapated" on the Specially Adapted Housing Grant page

### Relevant URLs

https://depo-platform-documentation.scrollhelp.site/getting-started/specially-adapated-housing-grant

**Comment by laucon** [comment]
First, THANK YOU for pointing this out. As a UX writer, I'm not sure if the appropriate tech team will notice this if we don't tell them. But I don't know who the tech team that works on this doc is. Again, I wish this was on a doc that wasn't part of the product directory because that would make editing it so much easier for the Platform content team, which I'm part of. lol

**Comment by laucon** [comment]
So it sounds like our 2 choices are:
1. Figure out which tech team is in charge of this product directory entry and then ask them to fix it.
or
2. Leave it alone.
Unless you, Josh, have the confidence to go in and edit this yourself.

**Comment by joshkimux** [comment]
@laucon noooo, I feel for you there. It's complicated 😢 
I'm super beyond my capacity at the moment, so I'm not sure I can do either of those choices, but I can bookmark this as something to come back to when I'm not as drowned in work 🙇

**Comment by laucon** [comment]
I think I can speak on behalf of my entire team that we completely understand and also still really appreciate having this called to our attention.

**Comment by vbellissimo** [comment]
Asking Platform PMs for a known stakeholder who can make this update via [this Slack thread](https://dsva.slack.com/archives/GMX26FF9D/p1678979713567509).

**Comment by tbaker1026** [comment]
This is an older version of the form that never made it to production, our team picked up the form listed[ here ](https://depo-platform-documentation.scrollhelp.site/getting-started/26-4555-application-in-acquiring-specially-adapted)
The above [form](https://depo-platform-documentation.scrollhelp.site/getting-started/specially-adapated-housing-grant) can be removed from the Product Directory, I believe.

**Comment by vbellissimo** [comment]
@tbaker1026 Thanks for this info Tricia! I'll continue to navigate to see if we're able to remove it altogether, if that is the case.

**Comment by vbellissimo** [comment]
Short-term solution to fix the typo:
- Content update request submission: https://github.com/department-of-veterans-affairs/product-directory/issues/684
- Pull request: https://github.com/department-of-veterans-affairs/product-directory/pull/685

**Comment by vbellissimo** [comment]
While reviewing this old ticket, it looks like this product's spelling is already corrected on the site: https://depo-platform-documentation.scrollhelp.site/getting-started/specially-adapted-housing-grant

Closing this ticket.
