### ISSUE TITLE
vets-api integation with eFolder

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#5509]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/structured-data/README.md)

## Hypothesis or Bet
**If** _vets-api is integrated with eFolder_ **then** _claims assistants will not need to manually upload documents submitted by a claimant to eFolder, which will expedite the time it takes for Vets and their families to receive burial benefits_.

## OKR
1) Reduces manual work for staff
2) Reduces time to benefits for Veterans and their families

## Definition of done
- All files submitted by a claimant are uploaded to eFolder automatically

**Comment by keithdadkins** [comment]
Created a similar epic to track my work. Closing this one.
