### ISSUE TITLE
VFS Product Directory PMs are out of date

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#55092]
### Description

The VFS product directory's PM list seems to be out of date, as Ariel is still listed as a PM here (I believe she no longer works at Ad Hoc and the VA). Would it be possible to update this list?

Context: we're trying to update our accessibility dashboard, and having the names of relevant PMs would be super helpful 😄 

### Relevant URLs

https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory

### Which type of team are you on? (Platform team, VFS team, or Leadership)

CAIA

**Comment by laucon** [comment]
Thank you Josh, for pointing this out. We are working on it right now. :)

**Comment by laucon** [comment]
I feel like we could find the PM who's in charge of this edit if you think it's important. They should be making those types of edits themselves regardless. I wish the content team could edit this themselves, but it's trickier for the Platform Content team to edit the Product Directory as opposed to all the other docs that we can edit more easily.

**Comment by vbellissimo** [comment]
Asking Platform PMs for a known stakeholder who can make this update via [this Slack thread](https://dsva.slack.com/archives/GMX26FF9D/p1678979713567509).

**Comment by vbellissimo** [comment]
Messaged Jeff Roof and Leah de la Costa via Slack to ask to make the content update and sent them instructions.

**Comment by vbellissimo** [comment]
Jeff Roof messaged via Slack and let us know he will make the content update for this.

**Comment by vbellissimo** [comment]
This content update has been made: https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory
