### ISSUE TITLE
[SPIKE] [FE] Answer remaining questions around "error=no-token"

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#55097]
### Check in 

If a Veteran reloads ANY page on check in after the check in window, then they will see the following error page - https://staging.va.gov/health-care/appointment-check-in/error?error=no-token. In this scenario, they are not asked to confirm their ID verification. 

This scenario likely happens when a Veteran reopens their web browser and the browser attempts to reload ANY check in page. E.g., /complete/, /see-staff/, etc. 

### Pre check in 

If a Veteran reloads ANY page on pre check in after the pre check in window, then they will see the following error page - https://staging.va.gov/health-care/appointment-pre-check-in/error?error=no-token. In this scenario, they are not asked to confirm their ID verification. 

This scenario likely happens when a Veteran reopens their web browser and the browser attempts to reload ANY pre check in page. E.g., /complete, /introduction, etc. 

## Testing
Based on testing in Staging, the following [results ](https://docs.google.com/document/d/1yOakOfo4HN6YAEGGb2HWFJJOvuPxWjjj/edit?usp=sharing&ouid=102484762290935663699&rtpof=true&sd=true)were documented

### Check in 

- [x] What are some of the technical specifics around when a Veteran will see this error? For example, is it after the check in window has expired AND when their browser session has expired? So, it could happen immediately after the check in window has expired? Or is that session available up until the end of the day?  
```They will only see this error if they are loading from a fresh browser or clear their local data. Manually typing in the URL will result in this. A bookmark will also cause this.```
- [x] Are there any other scenarios for when a Veteran should see https://staging.va.gov/health-care/appointment-check-in/error?error=no-token outside of the scenario described above? If so, explain. 
```The scenario above doesn't quite cause this issue as described in the answer for that question. Before the reload functionality it would cause that error but not currently. One other possible path is if the user gets to the /verify page and then reopens their phone later without ever validating.```
- [x] Who needs to do the work to change the content of https://staging.va.gov/health-care/appointment-check-in/error?error=no-token to https://share.goabstract.com/42ad6c8a-1e51-458c-a098-61838b01602b?collectionLayerId=4f446618-8b5a-474b-a711-603863ef74d8&mode=design&sha=latest 
```We control all of the content.```
- [ ] Ensure implementation tickets are created and passed along to appropriate team. 

### Pre check in 

- [ ] What are some of the technical specifics around when a Veteran will see this error? For example, is it after the pre check in window has expired AND when their browser session has expired? So, it could happen immediately after the pre check in window has expired, which would be 11:59 pm the day before the appoint?  
- [ ] Are there any other scenarios for when a Veteran should see https://staging.va.gov/health-care/appointment-pre-check-in/error?error=no-token outside of the scenario described above? If so, explain. 
- [ ] Who needs to do the work to change the content of https://staging.va.gov/health-care/appointment-pre-check-in/error?error=no-token to https://share.goabstract.com/4f416207-0fd1-4b05-8ba5-21b6e688e75a?collectionLayerId=2c0b5d8c-b337-49c6-a792-d36471bbc001&mode=design&sha=latest 
- [ ] Ensure implementation tickets are created and passed along to appropriate team.

**Comment by loripusey** [comment]
Tackle in frontend office hours
@wullaski @brianseek @benbrasso-agile6 @loripusey

**Comment by loripusey** [comment]
@brianseek @wullaski can you point this when you get a chance? thanks
