### ISSUE TITLE
Update the Cerner function in VAOS 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#55093]
## Description
The Public Websites team found another area of code that will need to be updated in order for the team to deprecate the old Cerner data method. The old function that is referenced in a file owned by codeowner: [department-of-veterans-affairs/teams/vfs-vaos-fe](https://github.com/orgs/department-of-veterans-affairs/teams/vfs-vaos-fe) `src/applications/vaos/components/EnrolledRoute.jsx`. 

## Dev Notes
In the `EnrolledRoute` component, we're importing `selectPatientFacilities` from `platform/user/selectors`. We want to update this and start importing `selectPatientFacilities` from `src/platform/user/cerner-dsot/selectors.js` instead.

---

## Acceptance Criteria
- [ ] remove reference to `selectPatientFacilities` from `platform/user/selectors`. We should be referencing `selectPatientFacilities` from `src/platform/user/cerner-dsot/selectors.js`.

### Design Assets
N/A

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by jilladams** [comment]
Hi folks - any sense of when your team might be able to prioritize this?

**Comment by ldelacosta** [comment]
Hi @jilladams - @simiadebowale will work on this ticket in the next sprint (which will begin this Wed 4/12). Let me know if you have additional questions. Thanks!

**Comment by ldelacosta** [comment]
@jilladams - The work has been completed. Please let us know if you have any questions. Thanks!

**Comment by jilladams** [comment]
No questions - we'll just look out for when it's verified / closed. Thanks for the heads up!

**Comment by ldelacosta** [comment]
We have verified the changes and no new issues reported. Closing out the ticket.
