### ISSUE TITLE
Discovery/research into a feedback system for improving the VFS onboarding experience

### ISSUE THREAD

**Issue by hpjaj** [department-of-veterans-affairs/va.gov-team#551]
## Story
As a Product Support team member, I want to understand how new teams perceive the MVP onboarding process.

## Goals
Understand what's working in the MVP onboarding process and what can be improved.

## Definition of done
- [x] Research plan created
- [x] Research strategy shared and approved by the team
- [x] All items needed for research plan follow-through have been created (surveys, etc.)

**Comment by smoonpeyes** [comment]
Here is a draft of the research plan: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/Platform/Onboarding/research/Onboarding%20MVP%20-%20Jul%202019/research%20plan.md
