### ISSUE TITLE
[SW] Kickoff meeting and discovery for Streamlined Waiver

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#55102]
## Issue Description
Review what we know about the Streamlined Waiver. 

---
## Tasks
- [x] _Review Excel and PDF paths_

## Acceptance Criteria
- [x] _Kickoff meeting_ (scheduled for Wednesday, 3/22/23 and we will plan to meet on a weekly basis).

**Comment by mgleo** [comment]
Design team met 03/20. Official kickoff happened 03/22.

[Link to Mural with Streamline Waiver Flow/User Flows](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1678973946956/6f3bb65fe1ccc2b9d3bc38cd24cd09e74d18d778?sender=ua78f969c4cddcbfe56b27885)

**Comment by denisecoveyduc** [comment]
Woo hoo! Excited to move this work forward. Let's discuss next steps in our next sync.
