### ISSUE TITLE
Analytics Feature Request/Bug Report - Update VA Notify Dashboard

### ISSUE THREAD

**Issue by zlaw** [department-of-veterans-affairs/va.gov-team#55109]
# Analytics Feature Request/Bug Report

## What this form is for

Use this template to request an Analytics dashboard feature or report a dashboarding or Google Analytics/Google Tag Manager bug. This form is for enhancements to the existing KPI dashboards. If you have any analytics questions, please use the `/support` command on [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel in Slack, or attend one of our [office hours](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guidelines.1586823275.html#Analyticscustomersupportguidelines-5.AdditionalAnalyticsSupport).

Platform Analytics & Insights will use the information you provide to help improve our products and services.

## Instructions

Please fill out the following sections:

- [ ] Ticket Description
- [ ] Request/Report Description
- [ ] Additional Comments

## Ticket Description

Who is this request for?

- What is your role, and which team/project is this work for? (optional for feature requests, required for bug reports)

  _this adds research context for any data or features being requested_

  - [My name is Zachary Law, a Product Manager with VA Notfiy.]

- Is this a feature request or a bug?

  - [ ] Feature request

## Request/Report Description

Please describe the feature you are requesting or bug you are reporting. Please be as detailed as possible. 

For a new feature request:

We want to replace a campaign on our Domo board:  Can we change "22-5490 confirmation" to "edu-learn-more"? 

**Product questions to think through if you're requesting new data features:**

- Who is your audience?
- Why do you need this data?
- What are you hoping to find?
- What is your hypothesis that you're hoping the data will support?
- What area of the VA are you hoping to assess?
- How frequently do you need this data?

## Additional Comments

_Add any comments or questions for the Platform Analytics & Insights team here (if applicable)._

> Please leave the following blank

## Acceptance Criteria

- [ ] Relabel the issue where appropriate
- [ ] Follow up with the requester where necessary

For features:

- [ ] Groomed & backlogged with notes

For bugs:

- [ ] Document issue & fixes
- [ ] Report findings with team & requester

## Definition of Done

- [ ] All AC completed

**Comment by michelle-dooley** [comment]
@zlaw so you just want to change the name/label from "22-5490 confirmation" to "edu-learn-more"?  No other underlying data changes?

**Comment by michelle-dooley** [comment]
@zlaw - so is 'edu-learn-more' a current campaign code? I'm not seeing it in the date.

**Comment by zlaw** [comment]
Hey @michelle-dooley - let me know if you have any questions.  I'm planning on attending office hours today, so I can answer them there.

**Comment by zlaw** [comment]
Hi @michelle-dooley - it has not been added yet.  I was just seeing if we could replace 22-5490 Confirmation with it before adding it to UTM parameters.

**Comment by zlaw** [comment]
Hi @michelle-dooley,

Thanks for the discussion during office hours yesterday!

As we discussed, the new campaign is edu-learn-more (?utm_source=VANotify&utm_medium=email&utm_campaign=edu-learn-more) which will be applied to https://www.va.gov/education/after-you-apply/ links, replacing the 22-5490-confirmation campaign.

Thanks,
Zack

**Comment by michelle-dooley** [comment]
@dorseypa1 - can you please add campaign code = edu-learn-more to the VA Notify dashboard tables.  Same as you did for 22-5490.

**Comment by zlaw** [comment]
Hi @michelle-dooley - I don't think I added anything before... I think the Analytics team added the landing page and the campaign code showed up automatically? If there is a process I should be following, let me know.

**Comment by dorseypa1** [comment]
I updated the Google BQ view for this.  I only see one record for the new campaign.
![image](https://user-images.githubusercontent.com/117392065/231221345-35b2146a-b529-48a1-b4bd-70d32ba1ee27.png)

But, It should be read for QA.

**Comment by michelle-dooley** [comment]
@zlaw - that is also what I see in GA report.  @zlaw - I know this is new so does that seem correct at this time?
![image](https://user-images.githubusercontent.com/93597659/231273474-94a9ae06-0a47-4717-9b55-b137e92c85af.png)

**Comment by zlaw** [comment]
Hi @michelle-dooley and @dorseypa1 - We don't have any live notification templates that use the campaign code yet.  The expected behavior is when we go live with our next notification, we see the edu-learn-more campaign name listed in our Landing page table in Domo https://va-gov.domo.com/page/2040841289?userId=1718497110.
![Screenshot 2023-04-11 at 5 04 21 PM](https://user-images.githubusercontent.com/76794936/231288126-aacfad8c-eb7f-4055-b302-a120aca7995d.png)

**Comment by michelle-dooley** [comment]
Yes and you should, they Domo data only updates weekly so it will be reflected next week.  I am going to close this ticket with a reminder to check Domo next week but I think we are good.  If we need to re-open we can.

**Comment by zlaw** [comment]
sounds good to me.  Thanks @michelle-dooley and @dorseypa1 !
