### ISSUE TITLE
Generic Alert Message when HSRM/VVS/VSP is down

### ISSUE THREAD

**Issue by Cieramaddox** [department-of-veterans-affairs/va.gov-team#55116]
## Task Description
In the event that VSP, HSRM and/or VVS are down, a generic message will be displayed in place of the **upcoming**, **past** and/or **pending** appointment list. 

## References

 - [Figma design](https://www.figma.com/file/9ZOtrJqv7Ze4ptVHMtE1iJ/Alert-users-when-VAOS-can't-display-appointments?node-id=1001%3A1230&t=zq1KFp0AVk6NQN4A-1)
- #53370 - Alert when HSRM is unavailable
- #53372 - Alert when VVS is unavailable

## Acceptance Criteria
- [x] Generic alert design spec (M/T/D)
     * [Design Spec](https://www.figma.com/file/9ZOtrJqv7Ze4ptVHMtE1iJ/Alert-users-when-VAOS-can't-display-appointments?node-id=1008%3A54&t=9srWZc0X8IgtA8Ak-1)

**Comment by Cieramaddox** [comment]
@ldelacosta @outerpress @JRRoof 
Design specs are ready for review

**Comment by outerpress** [comment]
@Cieramaddox see my comments in Figma

**Comment by Cieramaddox** [comment]
@outerpress Your comments were reviewed and incorporated into designs.

**Comment by outerpress** [comment]
@ldelacosta can you confirm that this covers the design work needed in:
- #53370 - Alert when HSRM is unavailable
- #53372 - Alert when VVS is unavailable

**Comment by ldelacosta** [comment]
The current ticket will cover one generic message for any of the 3 systems. We will add to our backlog to possibly add a custom message for each system type (TBD). @outerpress Let me know if you have additional questions. Thanks!

**Comment by outerpress** [comment]
@Cieramaddox can you check if this one can be closed out?
