### ISSUE TITLE
Security stuff

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#55113]
https://github.com/department-of-veterans-affairs/vets-api/security/code-scanning?page=1

This was brought to us by Clint as a P1 issue, we will be working on this asap

**Comment by npeterson54** [comment]
THis will no longer be a problem when we are on Ruby 3.2

**Comment by npeterson54** [comment]
Rolling this into the next sprint, this will be fixed on Monday when 3.2 rolls out

**Comment by ericboehs** [comment]
Resolved this morning.
