### ISSUE TITLE
Resolve issue with MEB test users no longer working on dev stack

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#55114]
On the dev stack, the MEB test users recently stopped authenticating properly. So we need to figure out what happened and fix these users

Slack convo here: https://dsva.slack.com/archives/CSFV4QTKN/p1678725357430799

**Comment by bosawt** [comment]
The issue appears to be something that ID.me is doing with these credentials. We have reached out to ID.me to see if they can help work through what's going on with the affected credentials

**Comment by mjconw3** [comment]
@bosawt ..Mike and I have reviewed this ticket, added the appropriate label and sprint and have closed. Let us know if a follow on ticket will be needed based on the conversation with ID.me
