### ISSUE TITLE
Research Spike: Metrics/KPI gathering for DSLogon

### ISSUE THREAD

**Issue by mjconw3** [department-of-veterans-affairs/va.gov-team#55122]
In order to move forward with the successful sunsetting of DSLogon, we want to gather Metrics and key performance indicators around account creation. We need to research and find a way to gather and document:

 - Number of helpdesk calls about account creation
 - Number of verified accounts created per week

Acceptance Criteria

- [ ] Research is done on how to obtain these metrics
- [ ] Research is well documented and shared with appropriate team members
- [ ] Path forward for collection and storing metrics/KPI is defined

**Comment by aparsley** [comment]
LGA has this
