### ISSUE TITLE
Research Spike: (pre login) - inform users of DSLogon sunset for va.gov

### ISSUE THREAD

**Issue by mjconw3** [department-of-veterans-affairs/va.gov-team#55123]
We need to Work with LGA to find out what is left to start showing a modal which informs Veterans that DSLogon is “not going to be available on VA.gov any more”

Acceptance Criteria

- [ ] Collaboration with LGA to define language for a modal  
- [ ] Research and decisions are documented and shared with appropriate team members
- [ ] Path forward for tasking for modal creation and implementation is defined (collab cycle, etc)
- [ ] Follow on ticket for front end implementation and other communication methods is created/updated

**Comment by aparsley** [comment]
LGA has it
