### ISSUE TITLE
Upgrade vets-api major version on rds to pg11

### ISSUE THREAD

**Issue by jbritt1** [department-of-veterans-affairs/va.gov-team#5514]
## User Story or Problem Statement
Vets-api team has requested RDS major version to be bumped to pg11

## Goal
Vets-api RDS instances using PostgreSQL 11

## Objectives or Key Results this is meant to further
- [x] Upgrade to pg11 in _sandbox_
- [x] Upgrade to pg11 in _dev_
- [x] Upgrade to pg11 in _staging_
- [x] Upgrade to pg11 in _prod_

## Acceptance Criteria
- [ ] Upgrade of database major version and all things working as intended.

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jbritt1** [comment]
All lower environments have been upgraded at this time. Production environment has a planned time for upgrade of Thursday night @ 2100-2130 EST.

**Comment by jbritt1** [comment]
This was postponed to Saturday 2/15/2020 @ 2100-2130 EST.

**Comment by jbritt1** [comment]
Postponed again until sometime this week due to a conversation that can be observed here: https://dsva.slack.com/archives/C52CL1PKQ/p1581613985110400.

**Comment by ricetj** [comment]
database major version upgrade is slotted for Saturday 2/29 @ 2100-2130.
https://dsva.slack.com/archives/CBU0KDSB1/p1582660537113700

**Comment by jbritt1** [comment]
Production upgrade conducted as scheduled. That wraps up this ticket.
