### ISSUE TITLE
Analytics KPI dashboard update request for [Governance Team]

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#55145]
# Request an update to your KPI Dashboard  

## What this form is for

Use this ticket template to request an update to your existing KPI dashboard. To request a new product be added to our dashboards, please use [Request a New Standardized KPI Dashboard template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&template=analytics-request-kpi-dashboard.md&title=Analytics+KPI+dashboard+request+for+%5BTeam%5D).

### Expected delivery timelines

Once you’ve submitted this ticket template, your KPI dashboard update request will be pulled into the Analytics team’s workflow the following Wednesday during Platform Sprint Planning or Refinement. We expect to deliver your completed dashboard within the next sprint. 

## Instructions for the VFS team
First, tell us what type of change you need to make:

- [ ] Change basic product info
- [ ] **Forms**: funnel changes
- [ ] **Content**: Add or remove pages included
- [x] Other: We would like to request some modifications to the Github export dataset transformations happening in BigQuery for governance team's collab cycle dashboard on Domo. We have documented our request[ in this GH ticket ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/55104)(details also provided below):

* **Modification on existing field:** create 4 new fields from the existing "Practice area" field:
   * IA denoted by the `ia` label begin present on the ticket
   * Content denoted by the `content` label begin present on the ticket
   * Design denoted by the `design` label begin present on the ticket
   * Accessibility denoted by the `508/Accessibility` label begin present on the ticket
* **New field request:** Create 1 new field for Launch Blocking denoted by the label `launch-blocking` being present on the ticket.
* **New field request:** Create 1 new field for Accessibility Defect Level denoted by 1 of the following labels `508-defect-0`, `508-defect-1`, `508-defect-2`, `508-defect-3`, and `508-defect-4` being present on the ticket
* **Potential (?) new request:** We'd love to pick your brains on exporting body text from our GH tickets. Can this be effectively text-mined? We basically want a different way to insert data into these tickets than just using labels. What options do we have?

Next, use the original [KPI request template](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit#gid=981224988) or [(downloaded Excel version)](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/1586823275/KPI%20Dashboard%20Product%20Details%20Template%20-%20MAKE%20A%20COPY.xlsx?inst-v=ced1f4dd-e997-4aa2-9ae8-2cebe369b42f) you filled out to update your information. If you are not able to find that spreadsheet, reach out to the Analytics team on #vfs-platform-support for a new spreadsheet that reflects what we currently have on file.

- [X] Make a copy of the [Google Sheet](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit#gid=981224988) [(or download Excel version)](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/1586823275/KPI%20Dashboard%20Product%20Details%20Template%20-%20MAKE%20A%20COPY.xlsx?inst-v=ced1f4dd-e997-4aa2-9ae8-2cebe369b42f)
- [X] Complete worksheet as instructed - we don't really fit the format of this document, so I selected "edge case"
- [X] Link your completed spreadsheet here: [Governance team ticket](https://docs.google.com/spreadsheets/d/1EJGvUNXc9Y4c5Sqnq3zspNM09U6IndyRBfLMag9IPvA/edit#gid=981224988)
- [X] Check your sharing settings to make sure the Analytics team will be able to access it
- [X] Add your team label to follow progress

**Additional Info**

- Please use the [KPI Framework](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/Analytics%20Playbook/va-gov-platform-analytics-kpi-framework.pdf) for more information on the metrics used in the KPI dashboards. 
- If you need any analytics support, read through the [How to request Analytics support](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guidelines.1586823275.html#Analyticscustomersupportguidelines-4.RequestaKPIDashboardinDomo).
- If you do not have Domo access, please [request access here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+access-request&template=analytics-request-google-analytics-domo-access.md&title=Request+access+to+Google+Analytics+and%2For+Domo).

**Comment by sterkenburgsara** [comment]
cc @it-harrison

**Comment by michelle-dooley** [comment]
@sterkenburgsara - I will be out next week but @dorseypa1 and @ChristineYoungZA are going to work on this and will reach out as needed.

**Comment by dorseypa1** [comment]
Good afternoon @sterkenburgsara , I created a new view in google BigQuery that should fulfill the data needs for this ticket.  If you have time tomorrow I can walk you through the changes during the Analytics & Insights Office hours.   If the changes make sense to you then I will hand this off to our Domo resource to further QA the data and make the changes to the Domo Cards.

**Comment by michelle-dooley** [comment]
Updates have been completed.
