### ISSUE TITLE
Email Communications on DSLogon Sunsetting

### ISSUE THREAD

**Issue by mjconw3** [department-of-veterans-affairs/va.gov-team#55168]
One of the methods of communication we want to move forward with on DSLogon sunsetting is via email to our users. We need to coordinate with LGA to find out if they have a method to use to send mass comms or not. If they dont we need to get with VEO to assist with this tasking.

Acceptance Criteria:

- [ ] Coordinate with LGA to find on potential to send mass comms
- [ ] If no method is identified, coordinate with VEO
- [ ] Messaging will be the same as the modal
- [ ] Draft comms email
- [ ] Send comms email

**Comment by aparsley** [comment]
LGA has.
