### ISSUE TITLE
login.gov support for international addresses

### ISSUE THREAD

**Issue by mjconw3** [department-of-veterans-affairs/va.gov-team#55167]
Currently, Login.gov doesn't support international addresses. For this reason we may decide to push users to idme if they have an international address

- How do we determine that a user has an international address when they attempt to create or gain support on login.gov
- How are we going to manage redirecting these users to idme for account creation, verification, etc

**Comment by aparsley** [comment]
Get with Anthony on their communications/emails on this issue to follow up @aparsley

**Comment by aparsley** [comment]
Spoke with Dawn on effort for LGA.
