### ISSUE TITLE
Enhance help desk support for DSLogon Sunset

### ISSUE THREAD

**Issue by mjconw3** [department-of-veterans-affairs/va.gov-team#55166]
We as a team want to assist the help desk in support of the sunsetting of DSLogon. We need to investigate and establish ways in which we can do so. A potential solution would be a live chat or alerting system that allows us to support requests in real time. 

 - possibly a hook/app into slack as a support channel
 - possibly channel that includes help desk and identity members

Acceptance Criteria:

- [ ] Engagement with help desk to establish a path forward on enhancing support
- [ ] Research and gain a better understanding of why login.gov has low success rates
- [ ] Document findings and establish a path forward on solutioning and support

**Comment by aparsley** [comment]
LGA has this.
