### ISSUE TITLE
Graceful pod connection draining

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#55169]
**PROBLEM STATEMENT**
The current [vets-api rack timeout is set to 120](https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/initializers/rack_timeout.rb#L10-L12) (for some issues with latent requests). We are aligning the terminationGracePeriodSeconds to 120 as well to avoid issues with the rolling deploy and connections not being gracefully drained if they exceed terminationGracePeriodSeconds: 30 (which is the default).

According[ to the puma docs](https://github.com/puma/puma/blob/master/docs/kubernetes.md#graceful-shutdown-and-pod-termination), the pod has up to terminationGracePeriodSeconds (default: 30 seconds) to gracefully shut down. We want all connections to drain gracefully, otherwise SIGKILL kills the process and the running connections.

**ADDITIONAL INFO**
Do blue/green deployments drain connections before switching to the new version? Reading abour preStop lifecycle hooks (which could be used to drain connections before switching to new app version) and wonder if this behavior is covered by blue/green..

[Running puma in kubernetes
](https://github.com/puma/puma/blob/master/docs/kubernetes.md#graceful-shutdown-and-pod-termination)

**ACTION STEPS**
- [ ] with breaking up into separate services, for now use default and adjust individual services/endpoints as needed

**DEFINITION OF DONE**

**Comment by LindseySaari** [comment]
[Dev PR here ](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/1650)

[Higher envs PR here](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/1651/files)
