### ISSUE TITLE
Blog Posts, social media and additional communications for DSLogon Sunsetting

### ISSUE THREAD

**Issue by mjconw3** [department-of-veterans-affairs/va.gov-team#55182]
One of the methods of communication we want to move forward with on DSLogon sunsetting is via blogs and social media for our users. We need to coordinate on a method to use to send mass comms via these paths.

Acceptance Criteria:

- [ ] Coordinate to find on potential path to send mass comms via blogs and social media, etc
- [ ] Messaging will be the same as the modal
- [ ] Draft blogs and social media posts
- [ ] Send comms

**Comment by aparsley** [comment]
LGA has a retargeting Mural based off of this. https://app.mural.co/t/innovationboards1199/m/innovationboards1199/1683647958507/c5f96dd311c276618b5a0b9fccc6874229177352?sender=ucacabb8e526600a0e0285255
Looks like they will be sending out test emails around this topic.

**Comment by aparsley** [comment]
FW: Sync on MHV > VA.gov and sign in/identity content and communications
Friday, May 26⋅10:00 – 11:00am Meeting for more information tomorrow.

**Comment by aparsley** [comment]
Issue is blocked until communications are ready.
