### ISSUE TITLE
[bug] Chapter 31 (Veteran Readiness and Employment) routed to the wrong regional office

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#55207]
## What happened?
Background:
We have a product area on the site called [Veteran Readiness & Employment](https://www.va.gov/careers-employment/vocational-rehabilitation/how-to-apply/). It has two forms that allow users to submit applications for employment opportunities and counseling. The forms work by looking at the users zip code and routing their application to a certain regional office (RO).

Problem:
For a certain set of zip codes in southern New Jersey, submissions of one of those applications, Chapter 31, are being incorrectly routed upon submission; they should be going to the Newark RO but are instead winding up at the Philly RO. 

An investigation should probably include a check across the entirety of the routing behavior. Jacob and Sade have a list of known affected zip codes that include PII in the form of a list of known affected users and their IDs. (Not sure if this is the entire list or if more have occurred since the initial report.)

## Desired behavior
_Forms are routed to the correct location based on the zipcode entered by the Veteran._

**Comment by saderagsdale** [comment]
This issue can wait until the next sprint.

**Comment by kylesoskin** [comment]
Beginning to look into this.

**Comment by kylesoskin** [comment]
We us BGS, `get_regional_office_by_zip_code` to get the RO based on provided zip. So I think this will be an issue we pass along to whoever managed BGS to figure out, but I will verify/confirm that once I can test some of the provided correct and incorrect zip codes.

**Comment by kylesoskin** [comment]
Example of the return:

```
irb(main):025:0> @service.routing.get_regional_office_by_zip_code(20001, "USA", "WA", 'VRE', 123456789)
D, [2023-03-27T19:34:40.413928 #343] DEBUG -- : HTTPI /peer GET request to internal-dsva-vagov-staging-fwdproxy-1821450725.us-gov-west-1.elb.amazonaws.com (net_http)
D, [2023-03-27T19:34:40.835033 #343] DEBUG -- : HTTPI /peer POST request to internal-dsva-vagov-staging-fwdproxy-1821450725.us-gov-west-1.elb.amazonaws.com (net_http)
=> {:regional_office=>{:number=>"314", :name=>"Roanoke"}, :@xmlns=>"http://www.va.gov/vba/corp/schema/roRoutingService/v20101101", :"@xmlns:ns1"=>"http://www.va.gov/vba/corp/schema/ro/v20101101", :"@xmlns:ns0"=>"http://www.va.gov/vba/corp/schema/common/v20101101"}
```

99% sure we just use what we get back from BGS, so this will probably have to go to them to figure out. However, I will confirm that we are not fumbling or erroneously providing info in our requests to BGS before making that conclusion.

**Comment by kylesoskin** [comment]
@saderagsdale Can you speak with Matt to try and get this issue routed to some BGS developers?

**Comment by kylesoskin** [comment]
@saderagsdale can you re-follow up on this to see if it got any traction anywhere?

**Comment by saderagsdale** [comment]
This has been passed to BGS. Closing for now.
