### ISSUE TITLE
Finalize Mural site maps and communicate out

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#55224]
Work to be completed to fully publish and communicate out the location of new site maps

- [x] All site maps currently in Moqups have been moved to the Mural open room
- [x] Each public site map has a global key/legend
- [x] Each public site map has a navigation "feature" available so visitors can easily move between different site maps
- [x] All comments and notes are removed/deleted (including those resolved)
- [x] Site maps are facilitator locked
- [x] A work flow is established for when and how site maps will be maintained 
- [x] The old site map pages are cleared and replaced with messaging and a link to the new site map
- [x] Documentation links in GH are updated (in the IA folder)
- [x] Availability of new site maps are communicated out

**Comment by mnorthuis** [comment]
@kristinoletmuskat @jennymayoco It looks like all of the site maps are finalized and locked, correct?  If so, I will go ahead and communicate out.

**Comment by kristinoletmuskat** [comment]
@mnorthuis yes correct!

**Comment by mnorthuis** [comment]
We have a general process for keeping these update that will be refined as we go, and the murals have been communicated out to the world! Closing issue.
