### ISSUE TITLE
mhv landing page - add explainer text + link

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#55234]
## Story

"As a longtime MHV user familiar with the existing MHV landing page who is seeing the new MHV on VA.gov landing page for the first time and is confused by what I'm seeing, I need to be able to find additional information about what this page is, and why I'm seeing it, so I can proceed confidently."

## Background

There will be a page at va.gov/resources/_____ that explains what the new landing page is along side general information about the MHV on VA.gov effort. A link to the resource page and a small bit of explainer content will be included on the landing page itself.

**Comment by MarciMcGuire** [comment]
@batemapf - has anyone in Content started on the explainer content?  Thx!

**Comment by batemapf** [comment]
we opted for just link text. actually about to push up a PR. stand by!
