### ISSUE TITLE
Create January Contact Center Report

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#5523]
## User Story or Problem Statement
How might we _____________ ?

## Goal
_What outcome(s) do we want to see?_

## Objectives or Key Results this is meant to further
- _lorem ipsum_

## Acceptance Criteria
- [ ] Gather Contact Center data for January
- [ ] Release report on #vfs-analytics & announce at ToT

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2019** [comment]
January report was created.
