### ISSUE TITLE
Design KPI Definitions Presentation

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#5526]
## Problem Statement
How might we present the KPI definitions document in a way that is digestible for VFS teams so that we can move forward to support KPI prioritization?

## Goal
Create a presentation or visual of our measurement definitions for VFS teams.

## Description
We have a document with product and measurement definitions and examples (VSA & VSP). The definitions by themselves are confusing, and need to visualized in such a way that would be easier for VFS teams to digest. 

The idea is to reach out to VFS teams to follow up on KPI prioritization (if they need that support). Part of that prioritization process is to link the KPIs back to outcomes and OKRs. We are hoping to send this document to teams as a reference or guide to review before meeting one on one with PMs/POs to whittle down their metrics to KPIs.

## Acceptance Criteria
- [ ] Visualize the KPI definitions draft document

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by joanneesteban** [comment]
## Definitions Draft

The definitions are linked in this [Presentation](https://docs.google.com/presentation/d/15AG9fVjxBp61I0cf6o1KwaHplurd9gZPAnYxddlsLL8/edit#slide=id.g769ff1c0da_0_108) on slide 4. The VSA and VSP examples are on slides 5 & 6. An example flow is on slide 3.

There's probably a better way to visualize how each of the metrics definitions relate, and having the definitions all together without the examples is confusing to digest. A potential way to do present this is to have each of the definitions with the examples and point to where it is in the flow, but I'll leave that up to your judgment, @amycesal!

**Comment by amycesal** [comment]
### the KPI process

![Screen Shot 2020-02-12 at 4.58.36 PM.png](https://images.zenhubusercontent.com/5b2ab6f42f27e82b33e6b789/0bb77a93-6b2d-436b-be1a-57542c8aeedb)

**Comment by joanneesteban** [comment]
## Artifacts

**Google Slide Decks**
- WIP [Definition Journey](https://docs.google.com/presentation/d/15AG9fVjxBp61I0cf6o1KwaHplurd9gZPAnYxddlsLL8/edit#slide=id.g6d866f9dc2_0_170) (for us to continue tweaking without VFS interruption)
- VFS Ready [Definition Journey](https://docs.google.com/presentation/d/1OGdCLFYGA4cb5nDUTJOme_7UBdAM49bX5zpYZ-zg6rw/edit#slide=id.g769ff1c0da_0_108)
- KPI [Process Follow Up](https://docs.google.com/presentation/d/1B30K5doW3r_dFoFzO2h5RKVUaVasEPnq_LWg7H5m0bc/edit#slide=id.p)

@amycesal

**Comment by joanneesteban** [comment]
## Artifacts

**Miro Template**
- Miro [Template](https://miro.com/app/board/o9J_kvR1XwU=/) for VFS teams to map their own KPIs to OKRs
