### ISSUE TITLE
Supplemental Claims | Design bugs

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#55277]
## What's this ticket for?
This ticket includes design bugs caught in staging.

## Stuff to do
- [x] Header inconsistency for private-medical-records
  - [ ] 🚨 **Blocked** Focus not showing up (pending Josh to create a DST issue ticket post-conversation with a11y specialists) (WILL MOVE TO A SEPARATE TICKET)
- [x] Margin inconsistency for evidence-summary. Missing space between header and alert
- [ ] [Error message](https://files.slack.com/files-pri/T7GEK6MA6-F04U7AFJRTN/screenshot_2023-03-15_at_1.37.58_pm.png) for add-issue decision date doesn’t  fit the use case. 

## Out of scope
- Add here

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by eileen-coforma** [comment]
@Mottie brought the header inconsistency up to the design system in [this thread](https://dsva.slack.com/archives/C01DBGX4P45/p1678895405292809) and has a [PR open](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1609) for the fix.

**Comment by Mottie** [comment]
There is a [bug in the error messaging that was reported](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1593)

**Comment by Mottie** [comment]
Ready for review

**Comment by eileen-coforma** [comment]
@Mottie Confirmed that the header size is correct now.
The yellow focus outline that's been showing up for all the H3s do not show up for this header.

**Comment by Mottie** [comment]
The focus outline that's missing on the headers are those that are inside of a web component. This work will need to be coordinated with the Design System Team... Josh said he'd open a ticket about it

**Comment by joshkimux** [comment]
I've marked myself as the assignee! Should be able to get to this very early next week ASAP (once I can herd some for specialists together) ❤️

**Comment by saderagsdale** [comment]
Will split off the first AC; if the other two are complete we can close.
