### ISSUE TITLE
VAOS FE Generic Alert Message for Pending list - HSRM/VVS/VSP is down (MVP)

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#55279]
## Description
In production, the following systems that could potentially be down are VSP, VVS and/or HSRM. When any of the systems are  unavailable, the frontend will display a generic message to the user that their appointments may be unavailable to view.

The backend service is returning an error in the response body for VSP (sample below): 
```
"system": "VSP",
"status": "500",
"code": 10001,
"message": "Could not fetch appointments from Vista Scheduling Provider",
"detail": "icn=1013120820V528557, startDate=2023-01-08T00:00Z, endDate=2024-03-08T00:00Z"

```

This work will focus on the Pending list page. 

## Acceptance Criteria

- [ ] Given VSP system is down 
        When the user views their pending appointment 
        Then the application will display an alert message 
        And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/alert-copy-docs/upcoming-view.md#pending-appointments) 

- [ ] Given VVS system is down 
        When the user views their pending appointment 
        Then the application will display an alert message 
        And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/alert-copy-docs/upcoming-view.md#pending-appointments) 

- [ ] Given HSRM system is down 
        When the user views their pending appointment 
        Then the application will display an alert message 
        And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/alert-copy-docs/upcoming-view.md#pending-appointments) 

- [ ] Given VSP and VVS systems are down 
        When the user views their pending appointment 
        Then the application will display an alert message 
        And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/alert-copy-docs/upcoming-view.md#pending-appointments) 

- [ ] Given VSP and HSRM systems are down 
        When the user views their pending appointment 
        Then the application will display an alert message 
        And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/alert-copy-docs/upcoming-view.md#pending-appointments) 

- [ ] Given VVS and HSRM systems are down 
        When the user views their pending appointment 
        Then the application will display an alert message 
        And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/alert-copy-docs/upcoming-view.md#pending-appointments) 

- [ ] Given VSP, VVS and HSRM systems are down 
        When the user views their pending appointment 
        Then the application will display an alert message 
        And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/alert-copy-docs/upcoming-view.md#pending-appointments) 

### Example (mobile view)

Default view of the alert message: 
![Screenshot 2023-03-22 at 12.24.00 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/94647171-0870-4894-b346-32212caa45bf)

User will click on the dropdown to expand the message: 
![Screenshot 2023-03-22 at 12.24.19 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/ddb3d0d5-0e5a-4052-8dac-4d90cd604688)

### Design Assets
[Figma File - Design Spec](https://www.figma.com/file/9ZOtrJqv7Ze4ptVHMtE1iJ/Alert-users-when-VAOS-can't-display-appointments?node-id=1045-1555&t=XMchNRXXhrIWhCWk-0#396358145)
[Storybook web component](https://design.va.gov/storybook/?path=/docs/components-va-alert-expandable--warning#warning)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by jenniemc** [comment]
Desktop display
![localhost_3001_health-care_schedule-view-va-appointments_appointments_pending_desktop](https://user-images.githubusercontent.com/54327023/232836385-a2ed7076-7eec-4dd9-83c7-a60ec1700a95.png)

Tablet display
![localhost_3001_health-care_schedule-view-va-appointments_appointments_pending _tablet](https://user-images.githubusercontent.com/54327023/232836685-fe740162-476a-4571-a6ad-90e88c9965c3.png)

Mobile display
![localhost_3001_health-care_schedule-view-va-appointments_appointments_pending_mobile](https://user-images.githubusercontent.com/54327023/232837063-fbaf77b9-49fd-476f-9371-a58e888b851f.png)

**Comment by Cieramaddox** [comment]
@ldelacosta This ticket is good to go

**Comment by simiadebowale** [comment]
![image (6).png](https://images.zenhubusercontent.com/62279c01c38e1718c9102bee/fea66944-54d5-4ccb-9740-263f341ffeb8)
We want to account for these HSRM codes as well:
9002: Could not fetch cc Appt requests form HSRM
9003: Could not fetch cc Appt requests form HSRM
9007: Could not fetch cc Appt form HSRM (General)
9008: Could not fetch cc Appt form HSRM (General)

**Comment by jenniemc** [comment]
@simiadebowale, Should I also include **9006**: Could not fetch cc Appt from HSRM ?

**Comment by simiadebowale** [comment]
@jenniemc - Yes please

**Comment by ldelacosta** [comment]
Just wanted to confirm if we are good to close out this ticket @jenniemc @simiadebowale

**Comment by jenniemc** [comment]
@ldelacosta, additional error codes are being tracked through HSRM. We want to account for these HSRM codes as well.

**Comment by ldelacosta** [comment]
Additional code was added for error codes coming from HRSM. It has been merged. No new issues found. Closing out the ticket.
