### ISSUE TITLE
Staging route-based rollout

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#55286]
## Description
After Lindsey's conversation with Bill, we've decided to try a route-based rollout for staging (as a test) before doing the route-based rollout in Prod. 

### Notes
1. We do still have staging workers deployed for BRD (and the deploy Jenkins job)
2. Start with search

**Comment by LindseySaari** [comment]
Need to come up with a plan for this one. Ideally, we should pick a day/time

**Comment by LindseySaari** [comment]
Plan to take this on Monday after all other items wrap up

**Comment by LindseySaari** [comment]
[Rollback and Staging testing plan here](https://vfs.atlassian.net/wiki/spaces/TT1/pages/2578284806/Staging+Route+Based+Rollout+Testing). We will rollback at 12:30pm ET on Thursday March 30

**Comment by LindseySaari** [comment]
PRs ready to go for Thursday:
1. [PR to point staging back to BRD](https://github.com/department-of-veterans-affairs/devops/pull/12733) (Step 1)
2. [Point /v0/search to EKS staging ](https://github.com/department-of-veterans-affairs/devops/pull/12735)(Step 2)

**Comment by LindseySaari** [comment]
The staging route based rollout was successful on the search endpoint! [This is my ip hitting the search endpoint](https://vagov.ddog-gov.com/logs?query=%40named_tags.dd.env%3Aeks-staging%20%40payload.controller%3A%22V0%3A%3ASearchController%22&cols=host%2Cservice&event=AgAAAYczfevx8WPnBAAAAAAAAAAYAAAAAEFZY3pmZm5MQUFCVllJN3pua0NVNFFBRAAAACQAAAAAMDE4NzMzN2UtMDg3Yi00YTU3LTkzMzMtNzE3OTk4MjUwNmUx&index=%2A&messageDisplay=inline&stream_sort=time%2Cdesc&viz=stream&from_ts=1680194921926&to_ts=1680195821926&live=true)
