### ISSUE TITLE
For Template Review: Life Insurance

### ISSUE THREAD

**Issue by edpearson20** [department-of-veterans-affairs/va.gov-team#55290]
Summary
Information that I have had to add regarding life insurance Tier 2 cases.

https://www.va.gov/life-insurance/manage-your-policy/

Access your VA life insurance policy online
If you have VA life insurance, find out how to access and manage your policy online.

What you can do when you access your policy
Check your policy’s status to make sure it’s up to date
Pay your premium (the amount you pay each month or each year to keep your coverage)
Find out about your plan and renewal options, depending on which type of plan you have
Update your beneficiaries (the people you’ve picked to get the money from your policy if you die)
How to access your policy
You can access your policy through our VA life insurance portal if you have one of these policies:
https://www.va.gov/life-insurance/manage-your-policy/

Veterans Affairs Life Insurance (VALife)—policies that start with a G
Service-Disabled Veterans Life Insurance (S-DVI)—policies that start with an RH
Any VA life insurance policy that starts with a V, J, RS, or W
Find your policy through our VA portal https://insurance.va.gov/home/

If you have a VGLI policy
You can access your Veterans’ Group Life Insurance (VGLI) policy online through Prudential Insurance Company of America. Prudential works with us to provide VGLI benefits to Veterans.

Find your policy through Prudential https://giosgli.prudential.com/osgli/web/OSGLIMenu.html

If you have an SGLI or FSGLI policy
You can access your Servicemembers’ Group Life Insurance (SGLI) or Family Servicemembers’ Group Life Insurance (FSGLI) policy online through milConnect. Go to milConnect and select Manage my SGLI.

Go to milConnect https://milconnect.dmdc.osd.mil/milconnect/

Last updated: January 3, 2023

**Comment by edpearson20** [comment]
I will add case numbers where I've used this information.

**Comment by edpearson20** [comment]
How would you like to review this information prior to creating a new Template.  Not assigning yet until further review or feedback. @Kimberley2019 @starlow00

**Comment by starlow00** [comment]
Hi @edpearson20. I combined this info with a couple of phone numbers I've tested. I think this should work, but we may want to review it before going live with it.
[Life Insurance Template (Ervin).odt](https://github.com/department-of-veterans-affairs/va.gov-team/files/11006890/Life.Insurance.Template.Ervin.odt)

**Comment by ATMiddleton** [comment]
Reviewed and approved.
