### ISSUE TITLE
FE | Profile | Info Table Accessibility Updates - Update Contact Info and Personal Info pages to new info card component

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/va.gov-team#55296]
## Issue Description

Migrate the last sections of Profile to use the new Info Card component

- Contact Info
  -  AddressesTable
  - EmailInformationSection
  - PhoneNumbersTable
  - LegacyGenderAndDOBSection (can probably just be removed)
- Personal Info Table 

## Front end tasks
- Remainder of ProfileInfoTables migrated
- Ensure the page is styled according to design spec. 
- Ensure the back end data from API is displayed in local and review instance
- Ensure unit tests are available. 
- Ensure your code changes are covered by E2E tests
- Run axe checks using the Chrome or Firefox browser plugin
- Test for color contrast and color blindness issues
- Zoom layouts to 400% at 1280px width
- Test with 1 or 2 screen readers
- Navigate using the keyboard only

## Acceptance Criteria
- [x] Remainder of ProfileInfoTables migrated
- [x] Designer comments on this issue to approve page styling 
- [x] Unit tests pass
- [x] E2E tests cover current code and regression
- [x] End-to-end tests show 0 violations.
- [x] The data returned matches API response (for given user or scenario)
- [x] All axe checks pass
- [x] All color contrast checks pass
- [x] All zoom testing passes
- [x] All keyboard checks pass 
- [x] All screenreader checks pass

**Comment by BerniXiongA6** [comment]
Note for team: this ticket is a continuation of the work @adamwhitlock1 started in Sprint 6 via #53632

**Comment by adamwhitlock1** [comment]
@BerniXiongA6 this is live on staging for validation. 

All pages are now migrated to the new Card component, so everything should look and function as expected. For testing and validation, I have put it through the paces with several test users, but `vets.gov.user+6@gmail.com` is one test user you could use to double check. (fyi this user does have a 'bad address' indicator present, so you will see a little alert around that)

Some things you could do to test that things are working correctly:

- Update user address, phone numbers, or info on Personal Information
- Remove any of the 'removable' info like phone number or home address
- Navigate between pages and verify that things load when data is available
- Double check mobile layout across the pages

This work doesn't really change any of the actual behavior, but rather the underlying content structure behind the scenes, but I always just test some updates to info to be sure.

**Comment by BerniXiongA6** [comment]
Thanks @adamwhitlock1 -- i'll validate today!

**Comment by adamwhitlock1** [comment]
@BerniXiongA6 yea direct deposit is a bit borked on staging right now. As we are working on the migration to lighthouse, I am hoping that once that is up on staging that we can fix these issues and get staging data visible more consistently.
