### ISSUE TITLE
Staging Review - Design - CTO Health Team - MHV on VA.gov Portal, Authenticated Landing Page

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#55299]
## Thoughts/questions
- When I opened the landing page on my external monitor, the large font size was jarring, and very hard to scan or read. Looking on mobile and my laptop, everything appeared fine, it just seemed like the larger monitor, larger and bold font made it hard to read. Of course this could also just be me, but it may be something you want to keep any eye on. Especially if users are coming from a previous page with a much smaller font.

I have a Mac, used Chrome.
![Screen Shot 2023-03-16 at 1.59.34 PM.png](https://images.zenhubusercontent.com/5f7e15543782a5c1ee10f1f0/a78a6817-b7a2-42c1-b712-70f7d88c9aeb)
![mhv-landing.png](https://images.zenhubusercontent.com/5f7e15543782a5c1ee10f1f0/7a9960a2-8157-430a-8d25-9271250bc07a)

**Comment by MarciMcGuire** [comment]
@rtwell @dcloud @batemapf - do we want to put this in the backlog, or take a "wait and see" approach where we create a new issue if it crops up as a more widespread problem?

**Comment by allison0034** [comment]
I agree with the wait and see, it may just be me. I would suggest when you do user testing you make sure you have a few larger monitors in the mix and that will tell you if it really is a problem or not.

**Comment by MarciMcGuire** [comment]
Agree.  I have a 49” Samsung ultra wide and it’s only 81 ppi.  @allison0034 I will make note of that for the next round of testing (recruiting is already underway for the testing starting Wednesday.  I think resolution is the key element.
