### ISSUE TITLE
AWS access for Matthew Conway

### ISSUE THREAD

**Issue by mjconw3** [department-of-veterans-affairs/va.gov-team#55303]
### COR Name

Delano Mcvay delano.mcvay@va.gov

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Matthew Conway

### Your Email

mconway@clarityinnovates.com

### Team, Role, and Company of the target individual

Identity, Product Manager, Clarity Innovations

### Product Manager (PM) name and email

Myself

### Product Owner (PO) name and email

Tom Black, thomas.black2@va.gov

### Desired AWS Access

Our lead devops engineer is leaving the team. I have experience as a DevOps Engineer and will be assisting the team with tasking

### Access Expiration

ongoing

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by mjconw3** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/55106

**Comment by little-oddball** [comment]
VFS Roster

**Comment by mjconw3** [comment]
I need my access to match the other devops engineers on Identity...specifically @ianhundere as I will be his backup https://github.com/department-of-veterans-affairs/va.gov-team/issues/40594

**Comment by BillChapmanUSDS** [comment]
I've spoken with Ian and I'm ok with this Access but prod access should be 3 months temporary.

**Comment by mjconw3** [comment]
Sounds good! Thank you Bill. Let me know if anything else is needed on my end

**Comment by rmtolmach** [comment]
Hey @mjconw3, your prod access has expired. Do you need to request an extension to `vsp-operations` permissions, or are there some lower permissions we can grant you that don't expire?

**Comment by rmtolmach** [comment]
I DM'd Matthew. I will remove access
<img width="767" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/10993987/b7814db6-b96f-4c43-87f8-75b313696906">
