### ISSUE TITLE
Adding Grace Johnson (ID.me) to DSVA Slack

### ISSUE THREAD

**Issue by Grace-Johnson-IDme** [department-of-veterans-affairs/va.gov-team#55311]
# Description

I am requesting to be added as a multi-channel guest to the same channels Kyle Fairbanks (ID.me) has access to, including:
- #vsp-identity
- @id-va-gov
- #vfs-analytics
- #vsp-contact-center-support
- #vfs-all-teams

I am a Customer Success Manager on the ID.me team, helping manage the partnership between ID.me and VA. I will be using DSVA slack to help escalate issues between the ID.me and VA teams.

**Comment by LEHigley** [comment]
@Grace-Johnson-IDme need an email address please
