### ISSUE TITLE
Fix enrollment verification react widget so focus is to top of landing page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#55320]
## Issue Description

As a Veteran looking to verify my school enrollment, I want to be able to see all the information provided on the [enrollment verification landing page](https://www.va.gov/education/verify-school-enrollment/). 

Currently, the entry points from the left nav and the education hub landing page direct users to the CTA widget rather than to the H1, so important information can be missed. The EDU team needs to update the react widget to fix the focus to go to the top of this page.

---
## Tasks
- [ ] Fix focus in react widget 

## Acceptance Criteria
- [ ] URL directs users to top of landing page

**Comment by btruongafs** [comment]
issue has been resolved
