### ISSUE TITLE
EKS "Add a secret" instructions link to the wrong URLs

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#55324]
### Description
Steps 2 & 3 of the instructions for [adding a new secret on the vets api on EKS page](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-Stepstocreateanewsecretvalue:) links to a specific commit of the file, which shows out of date information.

#### Step 2 values.yml Link Change
**Page**: [Vets API on EKS](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks)
**Section**: `Vets API Settings and Secrets` -> `Secret Values` -> `Steps to create a new secret value` -> `Step 2`
**Link Text**: "settings-local-secrets definition in the values.yaml"
**Old URL (to be replaced)**: `https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/2634d4f4b34db26c4511f4446306f19296c6cd67/apps/vets-api/dev/values.yaml#L480`
**New URL (to replace old URL)**: `https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/main/apps/vets-api/dev/values.yaml#L532`

#### Step 3 values.yml Link Change
**Page**: [Vets API on EKS](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks)
**Section**: `Vets API Settings and Secrets` -> `Secret Values` -> `Steps to create a new secret value` -> `Step 3`
**Link Text**: "settings-configmap configMap definition"
**Old URL (to be replaced)**: `https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/2634d4f4b34db26c4511f4446306f19296c6cd67/apps/vets-api/dev/values.yaml#L1440-L1441`
**New URL (to replace old URL)**: `https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/main/apps/vets-api/dev/values.yaml#L1552-L1556`

### Screenshot:
![image](https://user-images.githubusercontent.com/462039/225948236-c980fda1-5730-4a48-84a0-1900f2a2479c.png)

### Which type of team are you on? (Platform team, VFS team, or Leadership)
VFS Team

**Comment by vbellissimo** [comment]
Hi @kjduensing, thank you for submitting this content update request. Our team is reviewing this for next steps.

**Comment by rmtolmach** [comment]
@vbellissimo This can be done at part of https://github.com/department-of-veterans-affairs/va.gov-team/issues/54580 which Tech Team 1 will start on Monday.

**Comment by rmtolmach** [comment]
one thing to note: if it's possible, maybe we shouldn't reference line numbers since those change so often. Maybe we can reference searchable keywords.

**Comment by rmtolmach** [comment]
Good call-out, thanks!

Those existing links go to correct spots in the code. BUT, being on an old commit can lead to confusion, so I've modified the docs to link to the whole file (on `master`) and explained with words and a screenshot what needs to be done. I wanted to avoid linking to a specific line in `master` because it would be out-of-date quickly (for example, a line Kevin linked is already out-of-date). So I think we're good now!

**Comment by vbellissimo** [comment]
@kjduensing Hi Kevin, please see the comments above on here and the copy updates made to this page by our Platform SMEs . I will be closing this ticket. If you have any other questions, feel free to reach out. Thank you!
