### ISSUE TITLE
Documentation support

### ISSUE THREAD

**Issue by twoangstroms** [department-of-veterans-affairs/va.gov-team#55338]
### Request type

- [ ] Writing new documentation
- [X] Updating previously published documentation
- [ ] Reviewing recently written, never-before-published drafts

### Number of docs

1

### Subject matter expert

Dan Turner

### Approvals

No

### Embedded media

- [ ] Screenshot(s)
- [X] Diagram(s)
- [ ] Video(s)

### Audience

- [ ] Developers
- [ ] Designers and researchers
- [ ] Product managers
- [X] Other

### Anything else?

We would like the [Platform Satisfaction Survey](https://depo-platform-documentation.scrollhelp.site/support/platform-satisfaction-survey) page to change the CLOSED image (see image below) to OPEN, and that should be linked to the [survey page](https://airtable.com/shrKpir00TnjDUBRS).

<img width="607" alt="Screenshot 2023-03-17 at 9 23 25 AM" src="https://user-images.githubusercontent.com/62673202/225962319-d7c34fd5-5257-4103-a06f-f4a759a807cd.png">

**Comment by vbellissimo** [comment]
@twoangstroms Hi there. Thanks for submitting your request. We're reviewing this now for next steps. Thank you.

**Comment by vbellissimo** [comment]
Closing this ticket, as the page has been updated and the change is live.
