### ISSUE TITLE
Add BTSSS widget to travel pay page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#55342]
## Issue Description

As part of the work Public Websites is doing to deep-link authenticated users directly to BTSSS on the [VA travel pay reimbursement](https://www.va.gov/health-care/get-reimbursed-for-travel-pay/) page, we need to add the widget they created with our content once they provide us with the link.

## Tasks
- [x] Add widget to travel pay page (Aliyah)
- [x] Review (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] React widget is live on the site

**Comment by RLHecht** [comment]
BTSSS widget type is: btsss-login

**Comment by megzehn** [comment]
Update: I published this page with the react widget for staging purposes, however it's in a mode where users can't see it 

When the react widget becomes visible, we'll need to remove this line from the unauth page: 

"You’ll access this system through the AccessVA travel claim portal."

CC @RLHecht and @aliyahblackmore

**Comment by megzehn** [comment]
Hi @aliyahblackmore!

The widget for this is ready. Could you help get the [VA travel pay reimbursement ](https://www.va.gov/health-care/get-reimbursed-for-travel-pay/)page ready for final copy edit? 

- Right now, the widget is placed at the bottom of the page. It should replace the AccessVA link.
- Could you remove this line again right before it? "You’ll access this system through the AccessVA travel claim portal."

I'll also review the other pages [in this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/53735) that you changed that need to be copy edited and published once the updated page is live. 

Thanks! 
CC @laurwill

**Comment by aliyahblackmore** [comment]
Thanks @megzehn - the changes are the VA travel pay reimbursement page are ready for you! 
**Preview link:** 

**Tracking the updates that we discussed:** 

- I removed the Access VA action link and moved the React Widget up  
- I put the question back in "Filing a travel pay claim for the first time?"

**Comment by megzehn** [comment]
Thanks, @aliyahblackmore! Confirming that the VA travel page is live with the widget! 

@RLHecht, I'll let you close this one out when you get back. I guess I'd keep the actual at a 4.

Since this was our first time using the flipper thing, I'll also paste [Jill's Slack thread](https://dsva.slack.com/archives/C01K37HRUAH/p1680646116552579?thread_ts=1680103283.136269&cid=C01K37HRUAH) with the order of operations we went with. Also noting that Josh had some thoughts on how to tweak the process for the future.

**Comment by RLHecht** [comment]
Thanks all! Closing!
