### ISSUE TITLE
Adding Mitchell Wise to DSVA Slack

### ISSUE THREAD

**Issue by huggins-va** [department-of-veterans-affairs/va.gov-team#55365]
Good afternoon, 

Please add **Mitchell Wise** as a Multi-channel user to the following channels: 
- Channels: 
        vaapi-auth 
        team-pivot
email: wise_mitchell@bah.com

Mitchell Wise will be the new engineer on Lighthouse team Pivot! 

Thank you!

**Comment by LEHigley** [comment]
couldn't add to team pivot
