### ISSUE TITLE
Fix mobile view  "Feedback" button  layout location.

### ISSUE THREAD

**Issue by rmessina1010** [department-of-veterans-affairs/va.gov-team#55368]
### Description 
At 320 X 520 resolution the Last Updated: div is pushing the feedback button outside of visibility. looks like that div lives in content-build/src/site/includes/last-update.html. Who would I reach out to try and get this fixed? it is occurring here [https://www.va.gov/burials-memorials/pre-need-eligibility/](https://www.va.gov/burials-memorials/pre-need-eligibility/).

### Definition of Done
- [x] button does not  overflow
- [x] follows proper style guide

### Original Support Request:
https://dsva.slack.com/archives/CBU0KDSB1/p1678733140735639

**Comment by it-harrison** [comment]
PR is [here](https://github.com/department-of-veterans-affairs/content-build/pull/1528)
