### ISSUE TITLE
[Epic] Profile 2.0: Consolidate any redirects/link updates that need to happen from #5518 into one list

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#5536]
## User story

As a person looking for my VA.gov profile, the wayfinding to/in the profile needs to make sense so I don't get lost.

## Additional background

Epic #5534

We need to make sure we have a plan for the URLs leading to/in the profile and any redirects that need to happen, and we need to make sure the URL suggestions we have match our current URL structure requirements.

## Tasks

- [x] Create a list of all the redirects and link updates that need to happen.

## Acceptance criteria

- [x] The above list is compiled and actionable steps are clear.

**Comment by mshea0606** [comment]
@mshea0606 @tressaellen  @Samara-Strauss  Updates have been consolidated and put into EPIC #8395 https://github.com/department-of-veterans-affairs/va.gov-team/issues/8395

**Comment by mshea0606** [comment]
@tressaellen  re-opening this ticket, it looks like one issue remains unfinished in issue #5518

**Comment by Samara-Strauss** [comment]
I'm sorry, what is unfinished here?

**Comment by tressaellen** [comment]
@Samara-Strauss @mshea0606 I haven't finished looking through va.gov to see if there are any other links missing outside of the ones listed in the tickets.

**Comment by Samara-Strauss** [comment]
I thought this ticket was completed by consolidating the list of updates into #8395, but yes, if there are other pages you plan to look at, feel free to do a quick audit of any other pages I may have missed before closing this out. I will say that there are tons of pages, though, so don't feel like you have to go through the whole site. Just any pages that might have to do with the profile/account settings.

**Comment by tressaellen** [comment]
Re-closing this, I didn't find any other links on va.gov.
