### ISSUE TITLE
Business intake form for [eScreening]

### ISSUE THREAD

**Issue by agantcurtis** [department-of-veterans-affairs/va.gov-team#55384]
## Your Details
1.  **Angela Gant-Curtis**
​
2.  **Business Line - Innovations - OHIL/DEAN**
    (ex., claims, health, etc.)
​
## Notification Details
1.  **Notification type**
    (email, text/SMS, or both)  
​text/SMS
2.  **Please describe your use case. **
    (This is your chance to tell us an overview of your plans.)  
​Currently, a link is sent to Veterans to their eScreening questionnaire that allows Veterans to click on the link and complete the online questionnaire.  Younger Veterans have expressed an interest in receiving the communication via text message.  Since VA Notify already provides this capability, would like to be able to send link to eScreening questionnaire via text message.
3.  **What actions can the user take based on the notification they receive? -  **
    (ex., view secure messages, fill out a survey, schedule an appt, etc.)  
​Veteran will be able to complete questionnaire
4.  **What is the desired business outcome? **
    (ex., fewer skipped appointments, less call center volume, etc.)  
​Allow Veterans to provide information to healthcare team in advance of their schedule appointment which gives them more time to with the clinician to focus on what is important to the Veteran.  Eliminates the need to spend the limited appointment time completing administrative tasks.
5.  **What system will kick off the notification? Please note the system should be inside the VA or have an ATO.**
    (ex., BVA hearing reminders are kicked off from Caseflow)
​
6.  **What will trigger the notification? **
    (ex., clicking submit, status updates for claims, appointment reminders, new services available)  
​Functionality in eScreening for sending questionnaire to Veteran will trigger the notification
7.  **Provide sample content per notification type, if you have it.**   
Subject:  Please Complete Your eScreening
Your provider has created an electronic questionnaire for you in VA's eScreening system. Please be sure to complete your electronic questionnaire using eScreening by following the link below. This is important to ensure that your provider has all the information needed to give you the best care.
[Click Here to complete questionnaire](https://xxxxxxxxxxxxxxxx]
    Please note we collaborate with all of our users on their content to ensure it meets standards.
​
9.  **Has a Privacy Officer (PO) seen and approved the content? If not, do you know who your PO is?**  
    (ex., PO has seen the content but it is not approved)  
​Yes, Kamilah Jackson (VHACO Privacy Officer) and Matt Baum (VHA Security) have seen and approved the email content.  I suspect the content may need to be shortened to meet the text message limitation. 
10.  **Would you prefer to provide contact information for the recipients or would you rather VA Notify look this up for you by Veteran ID? **
    (ex., VAPROFILEID, PID, BIRLS, ICN, etc.)
​eScreening to provide contact information for the recipients.  If by ID, please let us know what identifier is used in your system.  
11.  **Do you currently capture communication preferences related to this notification? If so, please describe.**
    (ex., opt in for claim status updates via email or text)  
​ Currently, VHA staff obtain communication preference from Veteran for use with sending notification about eScreening.  We can add a field in eScreening for the VHA staff to indicate the Veterans preference that includes Veterans indication to opt out of receiving a text message. 
12.  **What is the anticipated volume of notifications per day, week, month?**  
Anticipated volume is 500/day, 5000/week and 25,000/month
​
13.  **When does this notification need to be in production?** 
As soon as possible

**Comment by bevnobev** [comment]
Hi @agantcurtis Earlier you mentioned starting with Eastern Colorado.  Is that still the plan?
