### ISSUE TITLE
[FE/Analytics] Update analytics tracking of military info FAQ link so it's not double-tracking events

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#55398]
## Background

[Slack convo for full context](https://dsva.slack.com/archives/C909ZG2BB/p1678809986805139)

Last week, we realized that this FAQ in the military section of the va.gov profile (https://www.va.gov/profile/military-information) is being tracked in multiple GA events:

![image.png](https://images.zenhubusercontent.com/5a4e5e33a016c5b034bc0750/37d0a6d6-7d3b-4d85-8d45-2ba03e980f83)

![image.png](https://images.zenhubusercontent.com/5a4e5e33a016c5b034bc0750/ea750554-cbe6-435b-b46c-d04b2216fa39)

We need to remove the duplicate tracking and only track via one event.

## Tasks

- [ ] Remove tracking for `update-military-information` event
- [ ] Confirm that `Additional info-Expand-What if I don't think my military service information is correct?` event is still in place and tracking

**Comment by adamwhitlock1** [comment]
I have confirmed in staging that this event is no longer getting fired, and just the singular event from the design system component is firing.

![Screenshot 2023-06-02 at 1.18.26 PM.png](https://images.zenhubusercontent.com/60ddebd504ce2452d0e0fa92/777353ad-54a6-495f-880e-189f55120f1e)

I will let this ride for a bit and check the analytics dashboards in GA to confirm further and then close out.
