### ISSUE TITLE
Design Intent  - IA Feedback - Login.gov adoption team, Organic Adoption

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#55393]
## VFS acceptance criteria
- [x] Let Platform know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [x] VFS team closes the ticket

## Thoughts/questions
- Hello! Sorry to have missed you all at the design intent meeting last week, but I watched the recording and have reviewed your prototype. This is a complex project and I appreciate your team's attention to detail so much!
- Question: In the call, Elizabeth mentioned that the end-goal is Login.gov being the single login option for users. What does that mean for Id.me? I don't have much visibility into your long-term product roadmap, but wonder if that is being phased out as well. 
- The [research outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/login.gov-adoption/research/2023-03-Organic-Adoption-Messaging-Usability) mentions that organic adoption won't do the same binding as the other work under grandfathering. That makes sense, but could it introduce possibility for us to put this modal in front of users before they sign in another way(DS Logon or MHV) instead of afterward?

## Feedback
- Practice areas will document their feedback following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback).

**Must:**

**Should:**
* While you iterate on the modal's content, think about scannability. Users will read headings, bullets, and bolded text - whatever stands out, before they'll read a paragraph. Use that to your benefit if possible: consider swapping the current header language for a meaningful action verb such as "upgrade" that conveys the goal and benefit of this process in one fell swoop. I would say the same for the button text - "get" login.gov doesn't feel as good as "upgrade" to login.gov - if that makes sense. The sitewide content folks (who you mentioned already working with) will be really helpful there in getting that language just right. 
* I also echo @naomimarcussen feedback that the close button may not be clear enough to all users that this is optional. I think some version of a "do this later" option is a great idea to play with.

**Consider:**

**Comment by CarlDickerson** [comment]
@sterkenburgsara There was no "Must" feedback from our design intent, but "Should" feedback has been addressed and updated in design. 

Here is a link to the updated design: https://www.figma.com/file/8vobVoSl1UqLnXsni3rcvO/Login.gov-Adoption%3A-Design-Flows?node-id=154%3A1300&t=6xQn4RsWDUhp8eOL-1
