### ISSUE TITLE
[bug] Supplemental Claims | AMA not triggering for issues in staging

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#55403]
## What happened?
Background:
Tested staging with user 228, and selected an issue with a decision date before 2/19/2019, hit continue, and went directly to the notice of evidence needed. @Mottie says it's most likely due to the way the mock data was set up.

Problem:
AMA page is not showing after selecting an issue with a decision date before 2/19/2019

## Desired behavior
_AMA shows for users who have issues with the decision date before 2/19/2019 selected or have added a new issue (not from API)_

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by Mottie** [comment]
Ready for testing in staging.

**Comment by eileen-coforma** [comment]
Checked it. Looks good. AMA now shows for older issues.
