### ISSUE TITLE
Remove "lymphomatic" references from PACT Act content

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#55408]
## Issue Description

There have been revisions in the PACT Act presumptive conditions information. We need to remove references to "lymphomatic" on both the [PACT Act R&S page](https://www.va.gov/resources/the-pact-act-and-your-va-benefits/) and the [exposure to burn pits page](https://www.va.gov/disability/eligibility/hazardous-materials-exposure/specific-environmental-hazards/). These cancers will now fall under the "lymphoma of any type" category.

## Tasks
- [x] Remove lymphomatic cancers from all pages (Randi)
- [x] Copyedit (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] Pages are live with term removed

**Comment by RLHecht** [comment]
@megzehn These are ready for you! I changed the one Q&A on the PACT Act R&S page and the one mention on the other page.

**Comment by megzehn** [comment]
Thanks for making the changes, @RLHecht! I reviewed and published.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
Actual time: 2
