### ISSUE TITLE
Higher-Level Review | Change "senior reviewer" to "higher-level reviewer"

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#55419]
## Background Context
- [Request from Laura Willwerth](https://dsva.slack.com/archives/C5AGLBNRK/p1678483931117829)

## Acceptance Criteria
- [ ] The phrase "senior reviewer" is replaced with "higher-level reviewer" in the form

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by rocio-desantiago** [comment]
Unable to get screenshots past the introduction page locally due to address not being associated with beta mocks data. Can the application be double checked for content updates?
<img width="605" alt="Screenshot 2023-03-28 at 1 56 02 PM" src="https://user-images.githubusercontent.com/37054305/228344167-f978386a-cf74-4455-b018-7bd8346d368c.png">

**Comment by saderagsdale** [comment]
@rocio-desantiago Is this a question for me or Eileen, or someone else?

**Comment by rocio-desantiago** [comment]
> @rocio-desantiago Is this a question for me or Eileen, or someone else?

Whoever validates please 🤗

**Comment by saderagsdale** [comment]
@Mottie can you take a look at the comment above?

**Comment by Mottie** [comment]
We should be able check these changing in staging. The problem is that in a local environment our mock users don't have any contact info, so the only way to get past that contact info page is to use the save-in-progress menu.

**Comment by saderagsdale** [comment]
@rocio-desantiago you can assign this to Eileen and me.
