### ISSUE TITLE
[Due on Feb 19] Appeal Modernization Process (AMA) Changes

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#5541]
Need help removing banners from two pages (one in Drupal and one in GitHub) and copy edits within the "Can I file my claim online," Wizard.  

Please see attached Word Doc for screenshots and detailed instructions. Contact @lwalsh617 (Laura Walsh) with questions. 
[AMA related changes_FE_v3.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4165610/AMA.related.changes_FE_v3.docx)

## Acceptance Criteria
- [x ] Remove  banner from decision review page in Github
- [  ] Remove banner from Drupal file and appeal page
- [x ] Change link (and potentially link language) on How to file a claim 
- [x ] Updates to How to file a claim Wizard
- [x ] Copy-edit on decision review page

This ticket is tied to #3247, which can be referenced for background. 

Desired/target implementation date
Need screenshots of Drupal pages along with Drupal links, plus a Heroku preview link of the GitHub page for a client meeting on Friday, 2/7. **Please note they should NOT go live until Feb 19.**

**Comment by MickinSahni** [comment]
hey laura, i think this is the one you mentioned in channel? does this need to be tackled this sprint? @lwalsh617

**Comment by lwalsh617** [comment]
Hi @MickinSahni, yes. We actually need it for a client call on Friday morning. It means making a few edits to each of five pages. @ncksllvn @kelsonic I found one more change that I can't make in Git Hub. Pasting here and updating the Word doc attached above so everything is in one place. Also, if helpful, happy to get on the phone and walk you through the edits as you make them. Thanks in advance. 
![image](https://user-images.githubusercontent.com/53535663/73898086-28f8c200-4856-11ea-863f-16fe08cebefd.png)
![image](https://user-images.githubusercontent.com/53535663/73898096-2dbd7600-4856-11ea-9af0-1d16f043f3d6.png)
![image](https://user-images.githubusercontent.com/53535663/73898113-429a0980-4856-11ea-9503-94ebe4c665c4.png)

**Comment by MickinSahni** [comment]
Ok. Who specifically is going to work on this? Can they add appropriate estimates? I'll pull it into this sprint.

**Comment by lwalsh617** [comment]
@MickinSahni -- Randi is working on copy edits in Drupal. Nick is looking at the FE edits tomorrow and getting back to me. I think Kelson is handling the GitHub edits that I cannot make (because they are within graphic components that I can't edit in Markdown). I'll confirm with Nick and Kelson and let you know.

**Comment by MickinSahni** [comment]
2020-02-06 PW Standup
- moving into current sprint ahead of stakeholder meeting tomorrow

**Comment by ncksllvn** [comment]
Hi @lwalsh617, I was able to do some of these tasks outlined in the Word doc -

1. The changes to `/decision-reviews` should be visible in the Heroku link of https://github.com/department-of-veterans-affairs/vagov-content/pull/626
1. The changes to the wizard on `/disability/how-to-file-claim/` are done in this front-end PR, https://github.com/department-of-veterans-affairs/vets-website/pull/11646. I attached screenshots into the description field there, but there isn't a Heroku link available for that work.

The following items are Drupal tasks -
- [ ]  Remove banner from https://www.va.gov/disability/file-an-appeal/
- [ ] Update link in MegaMenu
    - VA Benefits and Health care -> Disability -> File an appeal -> link to https://www.va.gov/decision-reviews/
    - Per Word doc - "we MAY change the link language to read “Appeal a VA decision” am waiting direction from Mikki. Should have shortly. "

**Comment by MickinSahni** [comment]
2020-02-07 PW Standup
- Will ask cms-support to see if they can remove this
- Link can be updated once changes are published

**Comment by ncksllvn** [comment]
Should we plan on making these changes to live on the 19th?

**Comment by MickinSahni** [comment]
2020-02-10 PW Standup
- FE changes ready in respective repos
- Drupal changes needed, but can't do alert banner 
  - @lwalsh617 to find out who can do it
- Q: "should i still plan on pushing these changes on 2/19" - Nick for @lwalsh617 
   - A: we're likely going to carry this into sprint 15 until we a) wrap up changes b) confirm launch

**Comment by MickinSahni** [comment]
> Should we plan on making these changes to live on the 19th?

That's what we're anticipating, @ncksllvn.

**Comment by ncksllvn** [comment]
Alrighty, I have a reminder set to check back on this on the 19th

**Comment by MickinSahni** [comment]
moving to sprint 15

**Comment by lwalsh617** [comment]
Hi @ncksllvn and @MickinSahni 
Quick question from the SMEs on the wizard. They want to know if the Wizard is programmed so that as each day passes, any Veteran entering a decision date that is more than a year old, will get the copy that says"...because more than a year has passed since the date on your decision letter..."  (i.e., on March 16, 2020, the Wizard will begin serving up that message when someone enters a decision date of March 15,2020). 
I am assuming that's the whole point, and that the answer is yes -- but wanted to confirm with you.  
I am trying to turn revisions around by tomorrow, so appreciate it if you can take a quick look today or first thing in the morning. Please see attachment for screenshot and the SME's inserted questions. Thank you!
[AMA VA disability Claim wizard questions.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4200034/AMA.VA.disability.Claim.wizard.questions.docx)
Thank you!

**Comment by MickinSahni** [comment]
2020-02-14 PW Standup
- Hey @lwalsh617, i don't have context and nick's out and kelson isn't sure. @jenniferlee-dsva are you familiar with the behavior / can answer laura's question?

**Comment by jenniferlee-dsva** [comment]
@lwalsh617 - I believe the message in the wizard is 'dynamic-lite' -- i.e., it displays different final answer based on the choices that the user selected in the wizards questionnaire, such as the date they selected to that question (What’s the date of VA’s decision?). 

I don't know if the new date logic for Feb 19, 2020 (or whatever the anniversary cutoff date is) has been implemented already. So that will be for the assigned FE engineer to answer. 

Is there already a FE ticket to update the wizard? If not, that would need to be created.

**Comment by mnorthuis** [comment]
Per 2/14 convo with Jen and Laura, PW team requested no IA review for this work for the Feb 19th launch.  Changes should only be content and labeling changes, no changes to IA, URLs or redirects.  Link label changes are ok as long as the context of the links stays true to the hub/spoke structure (i.e. task versus resource content within the Manage Benefits spoke).  More work is needed for the decision reviews content after the Feb 19 launch.

**Comment by ncksllvn** [comment]
Update - per @lwalsh617, we need to hold off for a couple days before merging the work related to this issue.

**Comment by MickinSahni** [comment]
2020-02-19 PW Standup
- jen reviewing final edits and will then sign-off/confirm new launch date
- laura to update ticket once we know more
- 2 PRs - widget + content, good to go with merging once we get the green light

**Comment by lwalsh617** [comment]
@MickinSahni @kelsonic -- Kelson, not sure I should be flagging you on this, or someone else. I need a quick copy change to a grey box component on a GitHub page. I can't make the change myself in Markdown because it doesn't show up in the code on markdown. If you could let me know if you are able and have bandwidth to do this, I'd appreciate it!
![image](https://user-images.githubusercontent.com/53535663/74860529-d4098100-5316-11ea-9912-ef7b2968d72b.png)

**Comment by kelsonic** [comment]
Just want to confirm that this is what I should be updating:

![image](https://user-images.githubusercontent.com/12773166/74861646-f3e57880-5307-11ea-8e24-8b4dd2d8e096.png)

`Multiple party or contested claims` -> `Contested claim`

**Comment by lwalsh617** [comment]
^ is all set. Kelson helped me figure out how to do it. Thanks, @kelsonic!

**Comment by MickinSahni** [comment]
2020-02-20 PW Standup
- confirming behavior of the widget. have 2 prs open for work to go live - Nick
- @lwalsh617 @jenniferlee-dsva - can you confirm the new go-live date for Randi and Nick

**Comment by jenniferlee-dsva** [comment]
@ncksllvn (CC @lwalsh617 ) - Small additional change to your PR tracked in  ^ https://github.com/department-of-veterans-affairs/va.gov-team/issues/5541#issuecomment-583024430: 

**Please change “claim contested by multiple parties” to “contested claim,” per same change on other instances of phrase.** 
![image](https://user-images.githubusercontent.com/43381063/75002523-ba5d5c00-5432-11ea-97d2-bbe0b0a077d7.png)

**Comment by jenniferlee-dsva** [comment]
@lwalsh617 - adding question here from Slack, about the Multiple parties or contested claims page. 

Because the SMEs  requested that instances of "contested claims by multiple parties" be changed to "contested claims," should the page title (H1) of this page also change?
https://www.va.gov/decision-reviews/multiple-party-claims/

Should it now say just "Contested claims" as the H1 and also eliminate "same" in intro, per other places where "same benefit" was changed?

fysa @RLHecht in case this page also needs to be updated in Github. TBC Laura.

**Comment by jenniferlee-dsva** [comment]
@ncksllvn - I updated comment https://github.com/department-of-veterans-affairs/va.gov-team/issues/5541#issuecomment-589484569  above - added one more item wrt another REACT component. (Apologies for the back and forth. In the future, we should create sub-tickets for all the REACT things to be updated together.)

FYSA @MickinSahni ^ (BTW, can't find Aruna to @ here)

**Comment by ncksllvn** [comment]
I made the first two changes, but I can't do this one from React.

> For the claim status track REACT component on this page: https://www.va.gov/disability/file-an-appeal/ - please make the changes marked inside {BRACKETS} :
CMS node: http://preview-prod.vfs.va.gov/preview?nodeId=901

> Check the status of your legacy appeal or decision review
If you already filed an appeal or requested a decision review, {sign in or create an account to check your status.}

This should be configurable in Drupal alone. It isn't a React component. It's just an alert banner with a button link.

![image](https://user-images.githubusercontent.com/1915775/75045527-6cc40c00-5491-11ea-88f9-4b046823d8e8.png)

**Comment by ncksllvn** [comment]
Here's what I'm working with now -

![image](https://user-images.githubusercontent.com/1915775/75046337-e3153e00-5492-11ea-84b6-9187b1d4d849.png)

Hm, since Feb 18, 2019 is now over a year ago, I don't think this is a state anymore. I'm getting this message with that input -

![image](https://user-images.githubusercontent.com/1915775/75047370-a2b6bf80-5494-11ea-8274-3288cd696e4e.png)

**Comment by RLHecht** [comment]
I can make the text changes in the widget in Drupal. Having issues with my password, but once I'm in I'll make it.

**Comment by RLHecht** [comment]
@jenniferlee-dsva The text for the alert is now updated: <img width="840" alt="Screen Shot 2020-02-21 at 10 49 35 AM" src="https://user-images.githubusercontent.com/48728214/75049232-db0bcd00-5497-11ea-99dd-f23d3555e127.png">

**Comment by jenniferlee-dsva** [comment]
@ncksllvn - RE your message about the Feb 18, 2019, input result: 

> Hm, since Feb 18, 2019 is now over a year ago, I don't think this is a state anymore. I'm getting this message with that input -
It should still be a valid state, it's just that the alert message the user receives should now change to guide them to Supplemental Claim with the explanation that they can no longer use HLR or Board Appeal. 

(I'm back on VA network now, so can't upload images and files to Github - arg.) So I'll put the copy that should be changed to in {brackets} below:

**You'll need to file a Supplemental Claim**
If you disagree with a VA decision on your claim, you can file a Supplemental Claim. {Because more than a year has passed since the date on your decision letter, you can no longer request a Higher-Level Review or Board Appeal. }

**Comment by ncksllvn** [comment]
We had a sync on this yesterday. Sounds like our pull requests are ready to go, and then @RLHecht will handle the Drupal side of town. I think we're just waiting for the go-ahead on launching.

**Comment by jenniferlee-dsva** [comment]
@mnorthuis - I created another ticket with nav labeling and minimal IA update questions for this Feb 19 round of copy changes. It will probably be easier and faster to jump on a call to capture info we need: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/6182

**Comment by AkucherGCIO** [comment]
2020-26-02
Waiting for SME approval and to go live after.

**Comment by AkucherGCIO** [comment]
2020-26-02 PW Planning
Validated and closing this issue.

**Comment by AkucherGCIO** [comment]
2020-28-02 Standup
Link to the launch tickets and once we know we are good for launch, close.

**Comment by AkucherGCIO** [comment]
AMA Launch ticket - https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/6165

Closing this issue as we are launching.

**Comment by MickinSahni** [comment]
@lwalsh617 @RLHecht i reformatted the acceptance criteria above and saw that "Remove banner from Drupal file and appeal page" might still be pending. can you confirm?

**Comment by RLHecht** [comment]
@MickinSahni This work was done. No more banner on the page!
