### ISSUE TITLE
Add backend documentation for Mocked Authentication

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#55416]
Backend documentation should describe the way to use mock authentication. Description should include:
* [x] Stacks that mock auth is available on (localhost, dev)
* [x] Credential formats to use (example of a MHV, DSLogon, Login.gov, ID.me credential)
* [x] How to integrate purely from cURL (we might even want to setup a Postman interface if we want to)
* [x] I think we prob don't need to describe the flow with the frontend, as we'll have FE focused doc to describe that

* [x] Here is a description of how it should work: https://dsva.slack.com/archives/C04MM3WJN1E/p1679329084554019?thread_ts=1679325164.527129&cid=C04MM3WJN1E

* [x] Here is an example of an MHV credential (sorry for the format, you may have to reformat this):

>    'mhv_icn' => ['1012853550V207686'],
   'mhv_profile' => ['{"accountType":"Premium","availableServices":{"21":"VA Medications","4":"Secure Messaging","3":"VA Allergies","2":"Rx Refill","12":"Blue Button (all VA data)","1":"Blue Button self entered data.","11":"Blue Button (DoD) Military Service Information"}}'],
   'mhv_uuid' => ['12345748'],
   'email' => ['kam+tristanmhv@adhocteam.us'],
   'multifactor' => ['false'],
   'uuid' => ['0e1bb5723d7c4f0686f46ca4505642ad'],
   'level_of_assurance' => []

* [x] Here is an example of a DS Logon credential:

> #<OpenStruct
iss="https://api.idmelabs.com/oidc",
sub="40e5bbdb6d2044ec89aad782c97d1faa",
aud="ef7f1237ed3c396e4b4a2b04b608a7b1",
exp=1652842354,
iat=1652824354,
credential_aal_highest=2,
credential_ial_highest="classic_loa3",
dslogon_birth_date="1968-09-11",
dslogon_deceased="false",
dslogon_fname="Marti",
dslogon_gender="male",
dslogon_idvalue="666008756",
dslogon_idtype="ssn",
dslogon_lname="Ortiz Rivera",
dslogon_assurance="2",
dslogon_mname="Carmi",
dslogon_status="SPONSOR",
dslogon_uuid="2105011823",
email="joe.niquette+marti.c.ortizrivera1@oddball.io",
level_of_assurance=3,
multifactor=true,
credential_aal=2,
credential_ial="classic_loa3",
uuid="40e5bbdb6d2044ec89aad782c97d1faa">

* [x] I don't think I have an example of an ID.me or login.gov credential on hand, but if you log in on localhost with either and make a breakpoint at this line in `sign_in_controller.rb`, you should be able to see the credentials: `user_info = auth_service(state_payload.type).user_info(service_token_response[:access_token])`

- [ ] - seed `client_configs` DB table and what appropriate entry should look like

- [ ] remove `OpenStruct` from documentation - messes up mocked auth user attributes parsing

**Comment by bramleyjl** [comment]
1st draft: https://github.com/department-of-veterans-affairs/va.gov-team/pull/55439

**Comment by bosawt** [comment]
BTW I added a PR for mock data (not sure if I want it merged yet), that shows the templates for each credential type: https://github.com/department-of-veterans-affairs/vets-api-mockdata/pull/267

**Comment by mjconw3** [comment]
@bramleyjl Just reviewed this and going to close it out
