### ISSUE TITLE
Local k8s cluster for vets-api

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#55420]
## Description

Currently, for local development, we only have a docker-compose based set for vets-api on EKS. (k8s branch). For troubleshooting purposes and having an env as close to prod as possible, we should derive a solution for running vets-api on a local k8s cluster.

**Comment by LindseySaari** [comment]
@RachalCassity Can you link the repo that had the kd3 example?

**Comment by laineymajor** [comment]
No longer in the scope of this project. More related to TT2 and their current project. Removing this from sprint work and project.

**Comment by laineymajor** [comment]
Keeping our eye on this... will checking with TT2 over the next sprint to see where this is at @npeterson54

**Comment by npeterson54** [comment]
We are hoping to have this done by beginning of september @laineymajor

**Comment by jennb33** [comment]
Per Nate Peterson on 2/22/2024 this work is on hold, so the Platform Product team can close our ticket. When we do get the go-ahead to do this work, it will be done by the Infrastructure team, so no need to have it on the Product board. Closing.
