### ISSUE TITLE
clamav for native setup

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#55434]
## Description

`clamav` USED to be a service that ran in the same process as vets-api in BRD. After the EKS changes, clamav has been extracted into it's own service. `clamav` can be run via a docker-compose based setup BUT we still support a native based setup for vets-api (e.g. non-docker) and we should configure clamav to run natively with the application locally. 

For now, clamav can be run via a hybrid setup (clamav in docker, the rest via hybrid) OR a full app docker-composed based setup

**Comment by laineymajor** [comment]
lower prio

**Comment by LindseySaari** [comment]
[PR opened here](https://github.com/department-of-veterans-affairs/vets-api/pull/12810)

**Comment by LindseySaari** [comment]
Approved and merged, closing!
