### ISSUE TITLE
Qualitative Data Request

### ISSUE THREAD

**Issue by Nyanteea** [department-of-veterans-affairs/va.gov-team#55451]
### Data Type Requested

User Surveys

### Date Range Start

01-01-2023

### Date Range End

03-15-2023

### Product Name(s)

21-526ez form

### Product Description

The 526 form is the form veterans use to apply for disability compensation. In the digital experience, veterans will answer questions to determine eligibility, select injuries/ailments to claim, upload evidence to support their claims, etc. The form is quite long. The feedback button in staging currently presents a survey that gauges whether the user completed the task they set out to do, what was that task , and their overall satisfaction. 

### Product URL(s) and/or term(s)

Form entry URL - https://www.va.gov/disability/file-disability-claim-form-21-526ez/

If possible, it would be great to get every page of the form where someone submitted written feedback and reported neutral satisfaction or lower satisfaction. 

### File Delivery Format

One file, different tab for each term/URL

### VA Email Address(es)

Nyantee.Asherman@VA.gov 

### Add Assignee and Labels

If not already done so, please ensure @ianMcCullough-ob is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by ianMcCullough-ob** [comment]
@Nyanteea I just shared the data with you. I broke up as many pages into different tabs, but kept a "misc" tab for URLs that didn't have that many results (didn't want to have an export with 15+ tabs).

**Comment by Nyanteea** [comment]
@ianMcCullough-ob , this was beyond helpful! thank you!
