### ISSUE TITLE
Rollout keyboard e2e test suite to Facility Locator Team

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#5546]
As an accessibility expert on VSP, I want to test my new creation with one team before I roll it out to everyone so that I have a chance to iterate based on feedback. 

AC:
- [ ] Work with facility locator to have them test keyboard e2e test

**Comment by 1Copenut** [comment]
@andreahewitt-odd I forgot we had an issue ticket for this work #5065. Going to close this one as a duplicate.
