### ISSUE TITLE
[Platform website] Update Environments page

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#55463]
### Summary
The Environments page (Developer docs -> Infrastructure -> Environments) was edited as part of the documentation updates in https://github.com/department-of-veterans-affairs/va.gov-team/issues/54579. There are a few sections that need removed or updated _after_ prod is live. The relevant sections have comments in Confluence, so they're highlighted. 

### Links
* Environments page in Confluence where you make edits: https://vfs.atlassian.net/wiki/spaces/pilot/pages/603488279/Environments
* Platform website Environments page: https://depo-platform-documentation.scrollhelp.site/developer-docs/environments

**Comment by laineymajor** [comment]
The doc queen will take this @LindseySaari

**Comment by LindseySaari** [comment]
Picking this up this morning and combing through any child documentation that also needs updating.

**Comment by LindseySaari** [comment]
I've updated all the appropriate section with EKS related information. I added a few sections noting the manual sandbox and prod syncs for now, so when we do have all envs on CD, we will need to circle back and update this.
