### ISSUE TITLE
Assess requested changes to life insurance hub page

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#55487]
## Issue Description
Steve passed along a request from life insurance leadership to change links and organization on the life insurance hub page.

---
## Tasks
- [x] Send email back with response (Laura)

## Acceptance Criteria
- [ ]

**Comment by RLHecht** [comment]
Update: Laura sent an email to Steve on 3/23.

**Comment by RLHecht** [comment]
Closing this out. Will open new tickets when needed.
