### ISSUE TITLE
[bug] Supplemental Claims | Review and Submit page button pair top margin inconsistency

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#55481]
## What happened?
Problem:
Testing form in staging, and saw inconsistencies with the margin between the checkbox and the 'finish this application later' link. The lack of space between 'Finish this application later' and the 'Back' button makes the link harder to target, especially on mobile.

Current Behavior:
Inspected the section and compared it to the previous, and saw that there's a div missing that's supposed to contain the 'finish this application later' link and button pair, which adds a margin-top--4.
![Screenshot 2023-03-21 at 11.06.51 AM.png](https://images.zenhubusercontent.com/630d073e647e629355675b4b/471dcaeb-9107-429b-a265-23ace9f2da96)

## Desired behavior
Consistent margins for form controls.
![Screenshot 2023-03-21 at 11.06.19 AM.png](https://images.zenhubusercontent.com/630d073e647e629355675b4b/c7ecb090-07b2-48d8-a94e-29256167d10b)

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

**Comment by eileen-coforma** [comment]
@saderagsdale @Mottie Spotted this design bug while testing.

**Comment by Mottie** [comment]
A fix has been merged in, but it's not yet available in staging for testing.

**Comment by eileen-coforma** [comment]
@Mottie So this was actually a two parter.
1. The fix for the spacing between content and 'finish this application later' link looks good.
2. Somehow, the button-pair doesn't have the margin css to separate the buttons from the 'finish this application later' link, so the spacing between the two is still weird.

![Screenshot 2023-03-27 at 10 29 06 AM](https://user-images.githubusercontent.com/111457818/227970649-302295f8-11e1-400a-92a3-37450b7ed9a0.png)
![Screenshot 2023-03-27 at 10 28 38 AM](https://user-images.githubusercontent.com/111457818/227970653-2627dd93-7b92-4104-87a4-08c83659c85f.png)

**Comment by eileen-coforma** [comment]
Looks good, thanks Robin!
