### ISSUE TITLE
Design Intent - Design Feedback - 10-10 Health Apps- Improve Facility Selection

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#55490]
## VFS acceptance criteria
- [x] Let Platform know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [x] VFS team closes the ticket

## Thoughts/questions
- Thank you for mobile and user flows, this is looking really good!

## Feedback
- Practice areas will document their feedback following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback).

**Must:**
- Remove the info alert on the address, showing the address is not an alert

**Should:**
 - Removing the action link styling for choosing different facility. It is probably more appropriate to use a default text link. Action links is an eye-catching link to start a digital service.
  - Work with content and adjust the design on the page that shows both addresses. It wasn't super clear why there were 2 and what the difference was.

**Consider:**

## Platform directions
- Remove the governance-team label
- Update "Issue Title"
- Link to collab cycle Request epic
- Add your feedback
- Remove the CC-Request label (only if you created the ticket using the New Issue link from the Collaboration Cycle Reviews board)
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review QA Only**: VFS PM, yourself (optional)

**Comment by jessicastump** [comment]
Design intent feedback has been incorporated into the following Sketch links:

**Confirmation screen updates:** removed alert, changed link styling for finding a new facility and worked with content on updates
- [Mobile confirmation screen Sketch link](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/GoOPMGE)
- [Desktop confirmation screen Sketch link](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/y98PyLK)

**Accessibility feedback:** Removed pagination and added link to follow Navigate a long list pattern, team decided to not show closed facilities so a disabled radio tile state is not needed, added annotations for focus order
- [Desktop search results Sketch link](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/AZxJmLz)

**Content feedback:** Updates to confirmation screen language above

**Comment by hdjustice** [comment]
@allison0034 - the MUST feedback on this ticket has been addressed:

> Confirmation screen updates: removed alert, changed link styling for finding a new facility and worked with content on updates
> 
> [Mobile confirmation screen Sketch link](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/GoOPMGE)
> [Desktop confirmation screen Sketch link](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/y98PyLK)

**Comment by hdjustice** [comment]
@jessicastump - Did we address what we needed from this ticket?  If so, we can close it.  Thanks!
