### ISSUE TITLE
Content changes for DS Logon FAQs page

### ISSUE THREAD

**Issue by aliyahblackmore** [department-of-veterans-affairs/va.gov-team#55491]
We got confirmation that we can start making changes to the DS Logon FAQs page about creating a new DS Logon account.

Other suggested content changed are in this ticket: [53924](https://github.com/department-of-veterans-affairs/va.gov-team/issues/53924)

**Comment by aliyahblackmore** [comment]
Hi @laurwill - content changes for the DS Logon FAQs page are in this Word doc. 

As we chatted, we'll share updates via a Word doc with the identity team. 

[https://app.zenhub.com/files/133843125/62c73f2d-ae6e-4103-95f1-d3361630c3c6/download](https://app.zenhub.com/files/133843125/62c73f2d-ae6e-4103-95f1-d3361630c3c6/download)

**Comment by laurwill** [comment]
Thank you @aliyahblackmore . This looks great. Here's the doc with the additional related changes we worked on over zoom: 
[DS Logon FAQs and related updates.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/11041804/DS.Logon.FAQs.and.related.updates.docx)

Could you add the Signing in page content? Then I can review before we post for Carl.

**Comment by aliyahblackmore** [comment]
Thanks @laurwill ! As we chatted, I added in content changes for the Signing in to VA.gov page. 

I also went back to the changes for the Creating an account page following some of the insights from the identity comms meetin. On the question about signing in with a DS Logon or MHV account - I left in your initial change, but I think we'd want to shift language slightly to only include Login.gov as an account option for DS Logon. I made this suggestion in a comment!
[DS.Logon.FAQs.and.related.updates_AB_3.22.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/11043778/DS.Logon.FAQs.and.related.updates_AB_3.22.docx)

**Comment by laurwill** [comment]
Hi @aliyahblackmore ! Thanks for adding that — here's the doc back with a few more tweaks and a couple comments to you in yellow highlight. If this all looks good, you can:
- Remove my yellow highlight comments
- Share this with Carl in today's content sync
- Ask Carl how best to get review and approval on these from John Rahagi and any other identity team members who need to review this — we can post and tag him directly, or Carl can share, whichever he prefers
[DS.Logon.FAQs.and.related.updates_3.23.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/11050825/DS.Logon.FAQs.and.related.updates_3.23.docx)

I'll be online till 5 today if you have questions!

**Comment by aliyahblackmore** [comment]
Thanks @laurwill! 

Tracking some updates here:**

- Reviewed this with Carl (and other member of the identity team) on our weekly sync.
- Did a gut check with Danielle about a few changes on how to discuss "basic" DS Logon. Joe flagged that "basic shouldn't be used." 
- There's still an open question about how we discuss Premium MHV - Elizabeth with follow up with any next content steps here (like a meetineg to chat about content suggestions).
- I'll add an open question/comment about what users can do with a Premium MHV or DS Logon account - Joe mentioned that users can't actually modify certain aspects of their accounts with just a MHV or DS Logon account (like direct deposit info), so we'll just want to confirm that there aren't other features that users with **just** Premium MHV or DS Logon wouldn't be able to access.

Carl asked that I share these changes as a Google doc with their team (Amber, Joe, and Elizabeth) - so that they can make shared edits/updates. I'll get this to them by tomorrow.

**Comment by aliyahblackmore** [comment]
**Tracking an update here:** 

-Carl is OOO on Thursday. I pulled down the weekly meeting.
-We'll review the feedback from Joe, integrate feedback, and adjust content to meet VA style standards.
-We'll need to meet with John to align on a few pieces of information. We'll aim to get something on the calendar for next week.

**Comment by aliyahblackmore** [comment]
Update here: 

- We shared content updates with Tom and John.
- John provided feedback 
- I added that feedback and passed a copy our of SharePoint to Laura.
- There are a few questions called our for MHV team.

**Comment by aliyahblackmore** [comment]
**Update here:** 

We're going to move this to a copy edit (hold to publish) @megzehn 

Including the document, from Laura, with the links to the pages and changes made. 

Just a reminder/note (in case it's helpful/I had to remind myself when looking): there are a few single Q&As on the FAQs - so you'll have to click the question to see the changes reflected.

[Updates to DS Logon-related pages.5.16.23.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/11626738/Updates.to.DS.Logon-related.pages.5.16.23.docx)

**Comment by megzehn** [comment]
Thanks, @aliyahblackmore! I reviewed these and published per your guidance.

**Comment by aliyahblackmore** [comment]
Thanks @megzehn !! 

I emailed John and Tom that the changes on these four pages are now live. 

We'll plan to update these pages again as the transition moves through future phases.

We can close out this ticket @coforma-terry
