### ISSUE TITLE
[Design] Change heading style in Unified Experience Sketch files to use the mobile versions

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#55506]
## Tasks
- Change heading style in Unified ExperienceSketch files to use the mobile versions in Sketch Cloud 

## AC
- Unified Experience Sketch files use the mobile version for the heading style

**Comment by benbrasso-agile6** [comment]
This is our last priority for this sprint, and may need to get rolled over to next sprint because of time.

**Comment by loripusey** [comment]
@cgednalske @benbrasso-agile6 please validate

**Comment by benbrasso-agile6** [comment]
Will lean on @cgednalske for validation, but maybe it's something to show during UX Sync as well

**Comment by cgednalske** [comment]
Yep I think we're set here 👍 And the other questions we had today can be part of #55457
