### ISSUE TITLE
Additional steps to take if you're having difficulty with SOCKS Proxy for Mac

### ISSUE THREAD

**Issue by jaredcunha** [department-of-veterans-affairs/va.gov-team#55500]
### Description
I've had some difficulty accessing tools like Sentry and Grafana. I went through all the steps to set up SOCKS Proxy, can confirm it was running with `vtk socks on`, but still couldn't access those tools.

What worked for me was in my MacOS System Preferences going to the Proxies settings in the Network section and turning on "Auto proxy discovery" and changing the Automatically proxy configuration file from some localhost address to https://raw.githubusercontent.com/department-of-veterans-affairs/va.gov-team/master/scripts/socks/proxy.pac

<img width="451" alt="Screenshot 2023-03-21 at 1 54 50 PM" src="https://user-images.githubusercontent.com/1094951/226698895-55796900-074e-46b3-a979-eb1e859a56f0.png">

I thought it might be helpful for others having difficulty with SOCKS. Another team member of mine was experiencing a similar issue and this worked for him as well. Saw another issue in Slack where this might be the fix too: https://dsva.slack.com/archives/CBU0KDSB1/p1678204159988729

### Relevant URLs
https://depo-platform-documentation.scrollhelp.site/getting-started/accessing-internal-tools-via-socks-proxy

### Which type of team are you on? (Platform team, VFS team, or Leadership)
VFS team

**Comment by vbellissimo** [comment]
Hi @jaredcunha . Thanks for your submission. The Platform Content team will review your request and determine the necessary next steps.

**Comment by laucon** [comment]
Update, I have confirmed that Clint's info and your troubleshooting ideas are unrelated. And because of that, we would like to go ahead and write this up as troubleshooting ideas. Thank you so much!

**Comment by laucon** [comment]
@jaredcunha I've written up an additional troubleshooting section that I'm going to add to the bottom of this [SOCKS Proxy document](https://depo-platform-documentation.scrollhelp.site/getting-started/accessing-internal-tools-via-socks-proxy) after you approve. Can you take a look at [these steps](https://docs.google.com/document/d/10qX_MKa4-wKI06bEWnhonERnrH-NLP6O4N_K7o5EBtI/edit#) that I've written and tell me whether or not they match with what you have seen on your Mac when you went in to do these steps? Thanks! Once you're ok with it, we'll copy and paste the google doc text into the bottom of the [larger SOCKS Proxy doc](https://depo-platform-documentation.scrollhelp.site/getting-started/accessing-internal-tools-via-socks-proxy) and publish it.

**Comment by laucon** [comment]
@jaredcunha We have updated the [document](https://depo-platform-documentation.scrollhelp.site/getting-started/accessing-internal-tools-via-socks-proxy) with your recommendations. Thank you SO much for reaching out with those recommendations. We really appreciate it, as does every future person who will have to install SOCKS Proxy, I'm sure. lol

**Comment by jaredcunha** [comment]
Thank you @laucon!!!! Really happy to help out wherever we can to make things easier for everyone.
