### ISSUE TITLE
major upgrades of RDS for GIDS

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#5550]
## User Story or Problem Statement
GIDS team has requested RDS major version to be bumped to Postgres 11. This ticket is to track support for the upgrades.

## Goal
GIDS RDS instances using PostgreSQL 11

## Objectives or Key Results this is meant to further
O3: Stability and resiliency of the Platform's systems and teams continue to improve.				

## Acceptance Criteria
- [x] upgrade dev to 11
- [x] upgrade staging to 11
- [x] upgrade prod to 11

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ricetj** [comment]
@tskinn can we close this?

**Comment by tskinn** [comment]
Yeah I think so. I haven't seen or heard any problems or complaints since we've upgraded.

**Comment by ricetj** [comment]
Done
