### ISSUE TITLE
Mock up organic adoption flow in mobile

### ISSUE THREAD

**Issue by tygindraux** [department-of-veterans-affairs/va.gov-team#55503]
## Problem statement
Veterans need to adopt Login.gov as their primary credential in order to access VA services.

## Initiative
We need to mock up an organic adoption user journey to test with Veterans. We suggest testing in mobile, based on feedback from Design Intent.

## Tasks
- [x] @skirkman16  draft prototype in Figma for @MOStudioCarolyn to review

## Acceptance Criteria
- [x] Figma prototype has been drafted and handed over to core team

**Comment by MOStudioCarolyn** [comment]
Sofia has finished mobile designs. Designs will be handed over to Core team next Sprint after finalized.
