### ISSUE TITLE
discovery: more specific access control options

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#5551]
## User Story or Problem Statement

As a platform, we need to address issues with Jenkins where permissions are either all or nothing in the environment with the current implementation. This task is to do some discovery on how much effort it would take to build out a permissions model where we could allow specific teams and/or any authenticated user to access specific jobs or categories, but not everything.

## Goal
Discovery on permission model options and how much effort it would be to tune current permissions.

## Objectives or Key Results this is meant to further
O1: Any volume of simultaneous customers have a delightful, self-service, end-to-end experience using the Platform to build on VA.gov.		
		
## Acceptance Criteria
- [ ] _What needs to happen or be created?_

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jbritt1** [comment]
Found that project-based matrix authorization strategy may give us what we want here. A vanilla jenkins was fired up in a docker container on a small EC2 instance for testing. The instance was configured to authenticate with a test GitHub organization to test team membership based permissions. Then a copy of our seed_job.groovy was created / ran to populate folder, projects, etc. Once all of this was complete, one could then go into an individual folder or project and "Enable project-based security and apply additional settings on top of what is set at the global level.

I believe, once the code/automation part of this is nailed down, we could allow "read" permissions for everyone (after authentication with GitHub) at the global level and then configure additional permissions for teams at the folder and project level(s).

**Comment by jbritt1** [comment]
Requesting a sort of "cheat sheet" on which teams need what permissions on what jobs.

**Comment by jbritt1** [comment]
I believe we know at this time for the most part what teams will need what on which jobs. The part we need to figure out at this time is the team model. That will lead into a implementation round of what was found for the discovery.

In my opinion, this can be closed at this time as the discovery portion of this work is complete. We will need to open a new ticket for the implementation bit(s) after we meet with Andrew and figure out the right team model for us.
