### ISSUE TITLE
Vets-api terminal access for Garrett Rabian

### ISSUE THREAD

**Issue by gmrabian** [department-of-veterans-affairs/va.gov-team#55519]
### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date: 3/31/22

### Your Name

Garrett Rabian

### Your GitHub handle (terminal access is managed through GitHub)

@gmrabian

### Team, Role, and Company of the target individual

Va Forms Team, Software Engineer, Coforma

### Product Manager (PM) name and email

Tricia Baker, tricia.baker@oddball.io

### Product Owner (PO) name and email

Matthew Dingee, matthew.dingee@va.gov

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [ ] sandbox
- [x] production (if requesting, justify prod access in 'Additional Notes' section)

### COR Name (leave "None" if you listed an AWS user name above)

None

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

Oddball - Amber Malcolm

### Access Expiration

12-31-23

### Additional Notes

Justification: Need Prod Argo access so my team can verify that our form submissions are reaching the Central Mail API and being processed. This is vital to our solution. We have a non-identifying form submission UUID that we can use to call the status endpoint and verify that form reached its destination.

### User must exist in a roster before vets-api terminal access can be granted

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added
- [ ] If they included an AWS user name, check to see if their user name is listed in [iam_users.tf](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf)
- [ ] Comment in this issue saying which roster the user is listed in and confirming their AWS user name (if applicable)

**Comment by little-oddball** [comment]
VFS Roster

**Comment by jeremy6d** [comment]
User exists in VFS roster, no AWS username or COR listed, awaiting OCTODE approval and please ping @jeremy6d when ready to move forward

**Comment by BillChapmanUSDS** [comment]
Missing EQip date should be added to this, once that is done I approve poduction access for 3 months or until we update the current process (discussion in progress)

**Comment by gmrabian** [comment]
@BillChapmanUSDS I haven't requested production access, just dev and staging.
I added my eQIP submission date as per the updated process.

**Comment by jeremy6d** [comment]
You've been added to those envs, please see for more details: https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-TerminalAccess

**Comment by gmrabian** [comment]
confirmed I have access. thank you!

**Comment by gmrabian** [comment]
@BillChapmanUSDS @jeremy6d I've just reopened the ticket to add production access, please see notes and reach out to Matthew Dinghee if more clarification is needed. Thank you!

**Comment by jeremy6d** [comment]
I note Bill approved prod access last week, so prod access is granted for 3 months, expiring Thursday, July 27th, 2023. For more details on ArgoCD see: 

https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-TerminalAccess
