### ISSUE TITLE
[Bug] Profile - Address Validation - Firefox - Alert-message icon not aligned & spaced correctly

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#5553]
## What happened?
On Staging Profile page, when editing Mailing Address and seeing the validation-screen, the alert-message icon's vertical alignment and horizontal spacing do not match the [design-comp screenshots](https://github.com/department-of-veterans-affairs/va.gov-team/issues/3948#issuecomment-579920507) from QA Epic #3948.

## Specs:
- Devices:
  * Win Firefox
  * Mac Firefox
  * Mac Chrome 80 (just released Feb 4)
- Test account: `vets.gov.user+56@gmail.com` \[see credentials [here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv)]

## Steps to Reproduce
1. Go to https://staging.va.gov/profile/ \[Sign in as test-account 56]
1. Under **Contact information**, click **Edit** next to **Mailing address**.
1. Change the address to any one of those in [this test-cases table](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/change-address/address-validation/qa-508/test-cases.md).
NOTE: Any test-case will replicate this Bug, but for bugfix all cases should be validated.

### Screenshot
**Overridable, With Suggestions** use-case example
\[This bug occurs with ALL validation use-cases]
![mac-firefox-overridable-with-suggestions-alert-icon-200205](https://user-images.githubusercontent.com/587583/73875468-93880e80-4812-11ea-9bde-1ba9dfbba14d.png)

## Desired behavior
Icon alignment & spacing should match the design-comp screenshots.

## Acceptance Criteria
\[see Desired Behavior above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by Samara-Strauss** [comment]
@erikphansen @bradl3yC I know you both are in the middle of work that I don't want to interrupt. Assigning both of you to this bug and we can decide how to handle it next sprint.

**Comment by erikphansen** [comment]
Is there a screenshot?

**Comment by Samara-Strauss** [comment]
Is the one in the original comment not working/adequate? If you're on Zenhub, check it on Github.

**Comment by erikphansen** [comment]
Sorry it wasn't showing in my phone's browser. False alarm!

**Comment by erikphansen** [comment]
This is certainly peculiar. I confirmed that the AlertBox component renders fine, even at narrow sizes, by checking out this page in Firefox. https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/visual-design/components/alertbox/

**Comment by Samara-Strauss** [comment]
cc/ @tlei123 ☝️

**Comment by tlei123** [comment]
> This is certainly peculiar. I confirmed that the AlertBox component renders fine, even at narrow sizes, by checking out this page in Firefox. https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/visual-design/components/alertbox/

Yeah, I agree that is perculiar alright!  The tools' alertbox icon looks fine to me too in Firefox, so I don't know why/how our Addr. Val. screen has this Bug.  I'm guessing whatever styling got added on top of what's inherited from tools.

Let me know if you'd like me to help dig further.

Thx much!

**Comment by tlei123** [comment]
> cc/ @tlei123 ☝️

Thx @Samara-Strauss for tagging me!  FYI, for **tics I open** GH auto-Subscribes me, so you won't have to cc me -- I already saw the GH auto-email for Erik's comment.  :)

**Comment by Samara-Strauss** [comment]
This is also a problem for me in Chrome. The icon is spaced weirdly just like in @tlei123's screenshot above.

**Comment by erikphansen** [comment]
I don't see it in Chrome, but maybe we have different versions. Regardless, if we can fix this in Firefox I'm sure it'll fix it in Chrome. 

This screenshot in Firefox shows that the 16px right margin on that `::before` pseudo element is there, but it's not being respected:
![image](https://user-images.githubusercontent.com/20728956/74400728-b9458280-4dd3-11ea-8401-fd240cff09b5.png)

And as I already mentioned above, the Alert Box looks fine on the design system site when the browser window is super narrow.

**Comment by tlei123** [comment]
@Samara-Strauss @erikphansen , should we all make sure our Chromes' up to date and then recheck?

I, for one, just checked my About Google Chrome and noticed there's an update so I'm gonna install it:
![about-chrome-200213a](https://user-images.githubusercontent.com/587583/74457881-1aa63980-4e46-11ea-9de5-d776f3149426.png)

**Comment by tlei123** [comment]
@Samara-Strauss , did you update your Chrome just yesterday?

I just updated my Chrome (now at Version 80.0.3987.100 (Official Build) (64-bit)), and the icon does look a bit off (unlike previous version screenshots in the copy bug #5466):
![mac-chrome-addr-val-icon-bug-200213a](https://user-images.githubusercontent.com/587583/74458858-905ed500-4e47-11ea-831c-3443609a90af.png)

<img width="709" alt="about-chrome-200213b" src="https://user-images.githubusercontent.com/587583/74458397-e121fe00-4e46-11ea-8b96-dee66123dd7f.png">

**Comment by Samara-Strauss** [comment]
My Chrome says it's up to date — Version 80.0.3987.106 and I'm still seeing the issue. 

I thought I posted this earlier but maybe it was in another issue. Idk if this has anything to do with the issue, but my computer is still on High Sierra because we can't update our VA machines beyond that for annoying technical software compatibility issues. I'm not sure if that would impact Chrome since it's up to date, but figured it can't hurt to throw that out there.

**Comment by bradl3yC** [comment]
@Samara-Strauss @tlei123 this should be ready for validation :+1:

**Comment by Samara-Strauss** [comment]
Looks good to me! @tlei123 can you confirm as well and then close?

**Comment by tlei123** [comment]
Verified on Staging.  Closing this now.
