### ISSUE TITLE
Content review of medical records: Vitals domain

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#55549]
We need to give content support on the medical records section of the My HealtheVet on VA.gov product. This work includes reviewing screens to make sure it meets VA.gov's plain language and style standards.

This ticket is for the Vitals domain.

Artifacts provided by product team:

- Link to product outline: [Medical Records Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/digital-health-modernization/mhv-to-va.gov/medical-records)
- Link to or attach [user flow](https://www.sketch.com/s/0803544d-e78c-423a-a70e-7db01a9a31c7/a/uuid/FBE40EA8-83CC-41A6-ABDE-F16F351B0FCF)
- Link to [Domain Brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/medical-records/data-domains/vitals/vitals-brief.md)
- Link to prototype or mockups:
  - Vitals list view [mobile](https://www.sketch.com/s/f6118ebb-966d-4f83-afba-f9e987b65eac/a/uuid/4E480FBD-C72A-435B-8F8B-CB8031A673AA) | [desktop](https://www.sketch.com/s/f6118ebb-966d-4f83-afba-f9e987b65eac/a/uuid/5ACFEE0F-2FFC-42AB-BFD9-C1E69FBACE4E)
  - Details page variations:
    - Vitals/Blood pressure [mobile](https://www.sketch.com/s/f6118ebb-966d-4f83-afba-f9e987b65eac/a/uuid/BB8932F5-531E-4CB2-B66E-24B194BAD904) | [desktop](https://www.sketch.com/s/f6118ebb-966d-4f83-afba-f9e987b65eac/a/uuid/6210A759-096D-4821-BA3B-EB79DCC5164A)
    - Vitals/Height [mobile](https://www.sketch.com/s/f6118ebb-966d-4f83-afba-f9e987b65eac/a/uuid/367F815C-AEAD-4911-8C4B-AC5BED825C58) | [desktop](https://www.sketch.com/s/f6118ebb-966d-4f83-afba-f9e987b65eac/a/uuid/1F057337-F44E-4D98-9DB0-43477F5E5ADD)
    - Vitals/Pain level [mobile](https://www.sketch.com/s/f6118ebb-966d-4f83-afba-f9e987b65eac/a/uuid/19939DB4-47DF-4C38-95A6-31157D604B4F) | [desktop](https://www.sketch.com/s/f6118ebb-966d-4f83-afba-f9e987b65eac/a/uuid/159A2770-70EA-4324-BC78-D716A22B581D)
    - Vitals/Pulse Rate [mobile](https://www.sketch.com/s/f6118ebb-966d-4f83-afba-f9e987b65eac/a/uuid/7633BF05-6505-480C-B5AE-57FD34F70FFE) | [desktop](https://www.sketch.com/s/f6118ebb-966d-4f83-afba-f9e987b65eac/a/uuid/85424C3F-1BBC-4D69-8B8E-89335D2200A9)
    - Vitals/Respiration [mobile](https://www.sketch.com/s/f6118ebb-966d-4f83-afba-f9e987b65eac/a/uuid/DA2D624B-C3F1-437C-9341-6F76E2698D4C) | [desktop](https://www.sketch.com/s/f6118ebb-966d-4f83-afba-f9e987b65eac/a/uuid/9E12E49B-E6EB-4451-8E2D-C3FC3340D8D1)
    - Vitals/Temperature [mobile](https://www.sketch.com/s/f6118ebb-966d-4f83-afba-f9e987b65eac/a/uuid/34076153-8072-4D31-81E4-17EC4207D2FD) | [desktop](https://www.sketch.com/s/f6118ebb-966d-4f83-afba-f9e987b65eac/a/uuid/67E54149-D1FA-4BFB-985E-976B889B323B)
    - Vitals/Weight [mobile](https://www.sketch.com/s/f6118ebb-966d-4f83-afba-f9e987b65eac/a/uuid/1558EE8F-3C1D-4974-9061-586F45B7FFA2) | [desktop](https://www.sketch.com/s/f6118ebb-966d-4f83-afba-f9e987b65eac/a/uuid/0C6A591B-364A-4662-A56C-D99BC2298D3F)
    - Vitals/PDF (download view) [Page 1](https://www.sketch.com/s/f6118ebb-966d-4f83-afba-f9e987b65eac/a/uuid/4AD1388E-9E8E-4C5A-9902-9342D9CC8F2C) | [Page 2](https://www.sketch.com/s/f6118ebb-966d-4f83-afba-f9e987b65eac/a/uuid/800FB665-6802-4FAA-891A-BCFAADEF008B)

## Tasks
- [ ] Review and edit screens 

## Acceptance Criteria
- [ ] Product team has final content

**Comment by laurwill** [comment]
@RLHecht , this is a medical records one we can close until after testing.
