### ISSUE TITLE
Design Intent - Accessibility Feedback - 10-10 Health Apps, 10-10CG, Improve Facility Selection

### ISSUE THREAD

**Issue by briandeconinck** [department-of-veterans-affairs/va.gov-team#55545]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
- This looks really good, and is definitely going to be an improvement over what's currently in place!

## Feedback
- Practice areas will document their feedback following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback).

**Must:**

**Should:**
- Looking ahead to coding, now is a good time to start thinking about how focus moves after search results load and as you move through the pagination. I would strongly recommend focus behavior matches the existing search tools on VA.gov, and I'd encourage you to document where focus should go so you have that ready to pass along to the engineers right from the start.
- For the disabled radio tiles, WCAG color contrast requirements don't apply to disabled form elements. But in this context, users might still want to be able to read a disabled tile, eg. to see that a facility they recognize is closed. If that's a reasonable use case, I would encourage you to find a color combination/design pattern that meets at least 4.5:1 contrast against the background while also communicating that the tile is disabled.

**Consider:**
- This will probably depend on what the data you get back from the facilities API looks like, but if you're getting a consistent and reasonable number of results back for every query, consider displaying all results at once rather than using pagination. I think radio-tiles-plus-pagination will probably be fine, but it's not an interaction pattern that I can remember seeing before and I'm mostly just concerned that once it's coded we might find some unexpected accessibility complication. If you can avoid the pagination entirely that just removes one of the unknowns. (But if the API is returning a ton of results, you've got to do what you've got to do. Just make sure you work with DK or another accessibility specialist for testing!)
- If you do run into issues with the radio-tiles-plus-pagination, the design system also has a [navigate a long list pattern](https://design.va.gov/patterns/help-users-to/navigate-a-long-list) that may also work. There are likely some accessibility changes coming to the guidance on that design system page, but overall the pattern is good.

## Platform directions
- Remove the governance-team label
- Update "Issue Title"
- Link to collab cycle Request epic
- Add your feedback
- Remove the CC-Request label (only if you created the ticket using the New Issue link from the Collaboration Cycle Reviews board)
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review QA Only**: VFS PM, yourself (optional)

**Comment by jessicastump** [comment]
Design intent feedback has been incorporated into the following Sketch links:
**Confirmation screen updates:** removed alert, changed link styling for finding a new facility and worked with content on updates
- [Mobile confirmation screen Sketch link](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/GoOPMGE)
- [Desktop confirmation screen Sketch link](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/y98PyLK)

**Accessibility feedback:** Removed pagination and added link to follow Navigate a long list pattern, team decided to not show closed facilities so a disabled radio tile state is not needed, added annotations for focus order
- [Desktop search results Sketch link](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/AZxJmLz)

**Content feedback:** Updates to confirmation screen language above
