### ISSUE TITLE
Update internal Platform documentation EKS

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#55563]
### Summary
The following files have been identified as needing updates to reflect the change in infrastructure from BRD to EKS. 

- [x] https://vfs.atlassian.net/wiki/spaces/OT/pages/1474594594/Vets-API
- [x] https://vfs.atlassian.net/wiki/spaces/OT/pages/2319417610/Do+basic+debugging+for+vets-api+prod
- [x] https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/README.md
- [x] https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/vagrant/README.md
- [x] https://github.com/department-of-veterans-affairs/devops/tree/master/ansible/vagrant/jenkins-vetsgov
- [x] https://vfs.atlassian.net/wiki/spaces/OT/pages/1801682995/Platform+Tools

### Acceptance criteria
- [x] All pages are updated.

**Comment by RachalCassity** [comment]
Just began today!
