### ISSUE TITLE
[Spike] Namepsace update when moving appointments to MHV on VA.gov (BE) 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#55562]
## Background
VAOS appointments will move to MHV on VA.gov in 2023 as part of the Unified Appointment Experience (UAE). As part of this move the current Appointments functionality will move to a new URL.  Product will need to understand what the effort for this initiative is and list out the tasks needed to implement the changes. 

### Goal
Update the namespace for the appointment list to MHV on VA.gov

### Requirements to Consider
A new namespace will be provided by the MHV on VA.gov team.

---

## Tasks
- Answer the following questions:
  - Q1: Will error tracking and alert dashboards need to be updated? Grafana? DataDog? 

## Time Box
6 hours

## Definition of Done
- Tasks are complete
- Research and recommendations are documented in this ticket

---

**Comment by cferris32** [comment]
Spike findings:

Q1: Will error tracking and alert dashboards need to be updated? Grafana? DataDog?
A1: Based on our research, our error tracking and alert dashboards should not need to change for this move, since the setup is tied to our controllers and services which aren't being altered.

**Comment by ldelacosta** [comment]
@cferris32 - thanks for the update. cc: @JRRoof 

Closing out the ticket.
