### ISSUE TITLE
Supplemental Claims | More design bugs

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#55574]
## What's this ticket for?

This ticket includes design bugs caught in staging.

## Stuff to do

- [x] Move edit link on contact information page below the values ([collab cycle ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/56075))
- [x] Add a Back navigation button to the ITF page ([collab cycle ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/56076))
- [x] Change issue summary page header language to "You’ve selected these issues for review"
- [x] Change evidence summary page header language to: "Review the evidence you’re submitting"

## Designs and Build Notes
- Contact information page [DESIGN](https://www.sketch.com/s/d2416db4-9a4f-4919-abe4-20ba4bdcfd89/a/Jn9zeOe)
- ITF [DESIGN](https://www.sketch.com/s/d2416db4-9a4f-4919-abe4-20ba4bdcfd89/p/B8B6038B-E3DE-4B50-B5AB-7D05D44F5C91/canvas)
- Issue summary [DESIGN](https://www.sketch.com/s/d2416db4-9a4f-4919-abe4-20ba4bdcfd89/a/4aP5KOZ)
- Evidence summary [DESIGN](https://www.sketch.com/s/d2416db4-9a4f-4919-abe4-20ba4bdcfd89/a/y982QpK)

## Out of scope
- Add here

## Definition of Ready 

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Reviewed and approved by product and/or design

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by eileen-coforma** [comment]
@Mottie I see this is tagged with needs-grooming and needs-design. Is there anything else you'd need from me?

**Comment by eileen-coforma** [comment]
@rocio-desantiago I saw you picked up this ticket.

I linked the two collab cycle tickets that are related to the first two tasks on this ticket. It might be helpful, since it includes more info/background about the fix.

**Comment by eileen-coforma** [comment]
@rocio-desantiago 
I tried to validate the first item you checked off, and still see the edit link in-line with the values on the contact page.

**Comment by rocio-desantiago** [comment]
@eileen-coforma ah sorry I haven't pushed it yet but can definitely push each item separately in if that's helpful

**Comment by eileen-coforma** [comment]
@rocio-desantiago no worries, I assume you typically push changes for a ticket all at once?

**Comment by rocio-desantiago** [comment]
@eileen-coforma almost done. The back button threw me in for a loop but the last two tasks are much more simple. Will update the ticket once it's been merged and ready for validate.

**Comment by rocio-desantiago** [comment]
@eileen-coforma for the last copy update, it looks like the wording is already there. Am I looking at the right page for this? 
https://staging.va.gov/decision-reviews/supplemental-claim/file-supplemental-claim-form-20-0995/supporting-evidence/summary
<img width="590" alt="Screenshot 2023-04-04 at 1 21 28 PM" src="https://user-images.githubusercontent.com/37054305/229883194-15001f75-6bee-43cf-a0c0-f80a1d82934e.png">

**Comment by eileen-coforma** [comment]
@rocio-desantiago Looks like someone has already changed it.

**Comment by rocio-desantiago** [comment]
@eileen-coforma for this page or an additional page?
![image](https://user-images.githubusercontent.com/37054305/230136695-0beea571-d08f-4e42-afc9-f9840c8ff648.png)

**Comment by eileen-coforma** [comment]
Yes, it's that page.

**Comment by rocio-desantiago** [comment]
@eileen-coforma ready :D

**Comment by saderagsdale** [comment]
@eileen-coforma Let me know if you think this one is good to close.

**Comment by eileen-coforma** [comment]
Good to close
