### ISSUE TITLE
FE | Profile | Account Security fix MHV account api calls and rendering error

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/va.gov-team#55590]
## Issue Description
We encountered an issue when viewing the MHV staging user MHVZACK and viewing their account security page there was an error thrown for `useComplete must be used within a ListItem component`

This should not throw an error in the event of undefined, but should instead just default to not rendering the ConditionalProcessList Item.

In addition to this error fix, we need to not call the MHV account endpoint anymore on the Account Security page, and not have UI around this in the code.

## Front end tasks
- Fix error when undefined is passed instead of boolean
- MHV_account endpoint no longer being called
- Ensure unit tests are available. 
- Ensure your code changes are covered by E2E tests

## Acceptance Criteria
- [x] Account security is shown for MHVZACK user (must log into CAG for mhv login to work
- [x] MHV_account endpoint calls are removed
- [x] Unit tests pass
- [x] E2E tests cover current code and regression
- [x] End-to-end tests show 0 violations.

**Comment by adamwhitlock1** [comment]
@Samara-Strauss and @BerniXiongA6 This can now be validated in staging with the MHVZACK user. I was able to log in with MHV in the network and see his account security page correctly.

[Uploading... Screenshot 2023-03-24 at 12.10.09 PM.png]

**Comment by BerniXiongA6** [comment]
Happy to validate this for you shortly here thanks @adamwhitlock1 !

**Comment by Samara-Strauss** [comment]
Sorry, I meant to do this on Friday! Validated -- everything looks great!

![image](https://user-images.githubusercontent.com/34068740/228039919-711c7a7c-3516-4384-aec3-cec3af24aa4d.png)
