### ISSUE TITLE
create Mocked Auth user profiles

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#55597]
# Completion Items
- [x] create a new route within the vets-api Mocked Authentication controller to access `vets-api-mockdata` mocked profiles
- [x] route takes `type` param & only looks for mock users of that CSP type
- [x] route should check mockdata `/credentials` directory for preset mock users
- [x] route should parse mocked data into a credential hash, then call `Base64.encode64(credential_hash.to_json)`
- [x] route should return both credential hash for end user viewing as well as encoded `state` for use by client

**Comment by bramleyjl** [comment]
![Screenshot from 2023-03-31 11-02-21.png](https://images.zenhubusercontent.com/5f99b8d1032b9709f1c7e051/ba385f99-ce7e-4610-8d0d-2c1c16cf5e7a)

Credential profiles are live (though without data) at `https://dev-api.va.gov/mocked_authentication/credential_list?type=logingov`

**Comment by mjconw3** [comment]
@bramleyjl looks good! Closing this out
