### ISSUE TITLE
VFS Support: Review IA of DIC and Provide Recommendations

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#556]
For after content contract transition - so we don't lose track of decision. Note: this hub is currently migrated into Drupal.  

Background: IA concern from Angie Smith, Pension SME. After content team discussed, we agree that there is no strong user-centered or SEO reason for DIC being under Burials benefit category. (History: possibly these pages needed a home prior to the Pension hub launching.) 

## User Story
As a survivor or dependent, I need to easily find DIC benefit info, so I can apply and access what kinds of DIC benefit I'm eligible for.

## Goal
_What outcome(s) do we want to see?_ 
Co-locate DIC info in a hub that makes natural sense, so it's intuitive to find via navigation. 

## Acceptance Criteria
- [x] Agreement on placement of DIC in the IA and recommendations for crosslinking.

## Definition of Done
- [ ] **Attached to a Milestone** (when will this be completed? )
- [ ] **Attached to an Epic** (what body of work is this a part of? )
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mnorthuis** [comment]
Moving this work into Sprint 6 support work.  cc @rroueche

**Comment by mnorthuis** [comment]
For initial work on this, it was decided that we would 
- [ ]  add cross-links to DIC within the Pensions menu
- [ ] review analytics after Pensions links are added - determine timeframe
- [ ] determine if there is a clear top referrer and if DIC should be moved, crosslinking improvements needed, or more testing/insights needed

**Comment by mnorthuis** [comment]
Recommendations for cross-linking in Pensions hub:
- Add link to Pension Hub page below Survivors Pension
- Add link to DIC and content on Survivors Pension page that explains the difference and links them over
- Add link to Survivors Pension and content on DIC page that explains the difference and links them over

TBD:  Adding a link to the Pensions top nav is TBD, would like to see if traffic from Pensions is significant enough to justify this.  It would be the 3rd place in the top nav that DIC would be represented if it was added.

**Comment by mnorthuis** [comment]
After conversation with VBA SMEs, here are recommendations:

- Move DIC to live under Disability and put appropriate redirects in place
- Add DIC to left nav in Disability
- Add link and content on Survivors Pension page that crosslinks to DIC
- Add link and content on DIC page that crosslinks to Survivors Pension

To be finalized:
- Additional links within Pensions needed
- What links should remain, be changed or be removed from Burials

**Comment by jenniferlee-dsva** [comment]
Also @Karak888 for awareness. Some of the associated tasks ^ (like updating content on DIC and Survivors Pension pages, and adding analytics tracking) are website team related.

**Comment by jenniferlee-dsva** [comment]
Summary of info w/Angie Smith SME:


Confirmed – DIC really is strongly associated with disability benefits. We will move DIC from burials IA to Disability. It is already cross-linked in several places inside Disability hub, but Mikki will recommend a permanent place in the Disability left nav. 
•	The Disability hub is in content freeze for CMS QA. Like ^ ETA is Sept 5 when it’s out of freeze, when we’ll be able to implement this change. It likely will take 1-2 sprints because of several tasks associated with the IA move. 
•	@Mikki Northuis – could you create a new ticket for the actual implementation of this change?
 
**•	Several associated tasks with the IA change:**
o	URL update
o	Redirects
o	Cross-links between survivors pension and DIC pages
o	Updating content on both survivors pension and DIC pages
o	Add analytics so we can still track and make sure move is working okay related to user paths/access/search

•	**Related info:** 
o	There’s just 1 application – it covers survivors pension, DIC, and (something else); so applicants don’t need to separately apply for survivors pension and DIC; VA makes the determination which one they get (VA assigns the one that would give the family member the most $). 
o	You can’t get both pension and DIC – mutually exclusive re ^. 
o	Re service member death in the line of duty. This is the text Misty shared re Jen’s Q: “Servicemembers who died while on active duty, active duty for training, or inactive duty training, or to survivors of Veterans who died from their service-connected disabilities.”  I.e., VA essentially treats death in the line of duty as same as a veteran service connected disability – hence DIC eligibility.

**Comment by mnorthuis** [comment]
Notes, analytics and decisions documented here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/dic/ia-placement.md

New issue for implementation is here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/1727

Closing this discovery issue.
