### ISSUE TITLE
Troubleshooting HPA

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#55603]
## Description

While load testing Vets API EKS in the staging environment, we ran into some issues where pods were not scaling (HPA)

[Datadog board can be found here](https://vagov.ddog-gov.com/dashboard/bu2-7t9-cja/platform-tech-team-1-load-testing-overview?from_ts=1679502418470&to_ts=1679516818470&live=true)

[Slack thread here](https://dsva.slack.com/archives/C04M7T1CZAS/p1679510713479089?thread_ts=1679316290.820519&cid=C04M7T1CZAS) with Benefits and Claims Team.

**Comment by LindseySaari** [comment]
We are adjusting the HPA metric rollup to see if that solves the issue

**Comment by LindseySaari** [comment]
[Slack thread here](https://dsva.slack.com/archives/C04M7T1CZAS/p1679510713479089?thread_ts=1679316290.820519&cid=C04M7T1CZAS) with Benefits and Claims Team.

**Comment by LindseySaari** [comment]
Liveness was reverted back to [the TCP connection here](https://github.com/department-of-veterans-affairs/vets-api/pull/12213/files). startUp is still an http request.

**Comment by LindseySaari** [comment]
Load testing proved that the HPA scaling (up AND down) is working properly - https://app.zenhub.com/workspaces/platform-tech-team-1-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/54225
