### ISSUE TITLE
Discovery for validation before submission

### ISSUE THREAD

**Issue by lydiahooper** [department-of-veterans-affairs/va.gov-team#55601]
Issue Description
We are aware that some errors are resulting in claims not being established, and that some user-facing error messages could be improved. We need to identify what opportunities there may be for validation before submission.

Out of scope:
- All ancillary forms except PTSD

Tasks
- [x] Look into and propose options for user validation pre-submission
- [x] Connect with VA Platform/content team to get info about error message guidance

Acceptance Criteria
- [x] Tickets for discovery work

**Comment by RakshindaAslam** [comment]
cc @RakshindaAslam

**Comment by lydiahooper** [comment]
Spreadsheet for tracking error messages: https://docs.google.com/spreadsheets/d/1s3mIDmsPk98q80qCyXP9Q3XhgqdV42JMGwVVG7-InLw/edit#gid=0

**Comment by lydiahooper** [comment]
Most if not all errors do not allow user to continue through form until corrected. 

Especially with the limitations of the [design system guidance for review page](https://design.va.gov/templates/forms/review), we should consider whether to offer users opportunity to validate/communicate success by creating new section summaries, as suggested by [recent research conducted by Supplemental Claims team](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Supplemental-Claims/Research/MVP%20Usability%20Research/Design%20and%20Research%20Share%20-%20SupplementalClaimsUsability.pdf).
