### ISSUE TITLE
Requesting temporary access to BigQuery

### ISSUE THREAD

**Issue by va-albers** [department-of-veterans-affairs/va.gov-team#55610]
# Request BigQuery Access access

## What this form is for
Use this template to request access to Google Analytics and/or Domo. Please complete steps 1 & 2 below. 

## 1. Access Requirements 
Please check the analytics tool(s) you need access to:
- [ ] Google Analytics
- [ ] Domo
- [X] (Platform Teams only) BigQuery

This is a request to grant Steve access to BigQuery for the month of April (4/1 through 4/30) so he can research ways to pull better business metrics from BigQuery data.  After this period Steve will either come back with a more request for long-term access, or preferably work with the Analytics team to find a way to surface the metrics in a tool.  Edit access is not required, and no automated/API access/scheduled jobs will be done with this account.

## 2. User Email Address to Receive Access 
**Due to privacy concerns, please do not put your email in this ticket.** Instead please use `/support` on the DSVA Slack channel [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support), select `Analytics` in the "I need help from" dropdown, and then add in the `Summary of request` section: 
 1. This issue's link 
 2. Emails that need access

---

### Definition of Done
- [x] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by michelle-dooley** [comment]
Access granted.
