### ISSUE TITLE
[A11y Design Review]: Temporary medical records landing page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#55621]
## Auditor(s)

Sara Smith

## Design Review
Based on the development of the prototype, some of the following may or may not be applicable. 
- [x] [Color and contrast checks](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review#use-of-color)
  - [x] WCAG 2.1 AA
  - [x] WCAG 2.1 AAA
  - [x] [Who Can Use](https://www.whocanuse.com/?b=ecece5&c=000000&f=20&s=)
  - [x] High Contrast Mode
- [ ] [Keyboard navigation](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review#keyboard-nav). (Not Applicable) 
  - [ ] Annotations for Tab order, reflow and reading order (if needed) (Not Applicable)
- [ ] Accessible Name Annotations  (Not Applicable)
  - [ ] [Alt attributes for images](https://webaim.org/techniques/alttext/)
  - [ ] Text alternative for complex images such as charts graphs maps etc.
- [x] Language (ease of reading)
- [x] HTML Tags
  - [x] [Page Title](https://accessibility.18f.gov/page-titles/)
  - [x] [Heading order](https://accessibility.18f.gov/headings/)
   - [x] Annotations (if needed)
  - [x] Semantic Consideration for paragraphs ordered lists numbering
  - [ ] [Tables (heading rows)](https://design.va.gov/components/table)(Not applicable)
- [ ] Size of clickable areas (Not applicable)

### As Time Allows
- [ ] [Components](https://design.va.gov/components/) follow VA design system guidance.
- [ ] [Patterns](https://design.va.gov/patterns/) follow VA design system guidance.

## Prototype Link

Temp landing page [mobile](https://www.sketch.com/s/f6118ebb-966d-4f83-afba-f9e987b65eac/a/uuid/CD6EFAE2-8F48-4C0C-A5F3-F068F5A2775B) | [desktop](https://www.sketch.com/s/f6118ebb-966d-4f83-afba-f9e987b65eac/a/uuid/C5CADBEE-C7F8-4FDA-B28D-5B648416EB37)

### Concise issue description

Question for Content team.. what tool?

![Image 4-13-23 at 1.17 PM.jpg](https://images.zenhubusercontent.com/623cd4d6774110eeb19922cb/5eec71a0-4cef-4f2c-8396-54f05b118333)
#### Bandaid solution
 Specify tool in header (MyHealtheVet Medical Records Tool)

## Related Ticket/Epic
[MHV Accessibility Patterns Consolidation for Midpoint #56578](https://app.zenhub.com/workspaces/sitewide-content-accessibility-and-ia-63a1d63232beba0011a7833f/issues/gh/department-of-veterans-affairs/va.gov-team/56578)

**Comment by sara-amanda** [comment]
## CAIA Note 
Note to @SarahKay8 and our a11y partners, if reviewed while I am OOO: This page used the design of Secure Messaging replacing the content with Medical Records content, if you need to reference that landing page, during your review. Any findings here would likely be there as well. @coforma-terry 

### Potential Nav. Testing Q. // Review Prior to Audit
#### Review for accessible navigation
- Do users know how to get back to legacy? 
- Do users understand how this relates to other medical records? 
- Is it obvious where they stand in the hierarchy? Is it correlated to this part of the navigation? 

#### Process Flow
_Landing page → Medical Records → Medical Records Classic 
→ Then click on new design to go to Va.gov MHV Medical Records
Health History will have a subset of navigation items._ 

### OOO
I will be out of the office 4/11; returning 4/19, so I wanted to update you both on this ticket for coverage. Thanks!

**Comment by sara-amanda** [comment]
## CAIA New Related Ticket

### Related Ticket/Epic
[MHV Accessibility Patterns Consolidation for Midpoint #56578](https://app.zenhub.com/workspaces/sitewide-content-accessibility-and-ia-63a1d63232beba0011a7833f/issues/gh/department-of-veterans-affairs/va.gov-team/56578)
