### ISSUE TITLE
Add Specially Adapted Housing form react widget to how to apply page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#55620]
## Issue Description

Before the Specially Adapted Housing grant digitized form launches, our team needs to add the react widget to the [How to apply for a Specially Adapted Housing Grant](https://www.va.gov/housing-assistance/disability-housing-grants/how-to-apply/) page.

## Tasks
- [x] Remove content and add react widget in Drupal
- [x] Copyedit (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] React widget is live on the page

**Comment by RLHecht** [comment]
React code from product team: form264555

**Comment by RLHecht** [comment]
I let Tricia know there's a missing space in the content that they need to fix. They will let us know when the page is ready to go live and then we can do a copyedit and publish.

**Comment by megzehn** [comment]
Confirming that this has been copy edited. 

Also flagging that I changed the H1 from **How to apply for a Specially Adapted Housing Grant** to **How to apply for an adapted housing grant** to better align with the form intro page, and also reflect the 2 different grants. Confirmed with Mikki.

**Comment by megzehn** [comment]
Holding to publish until react widget is ready

**Comment by megzehn** [comment]
Confirming I did a final review and published this page.

**Comment by RLHecht** [comment]
This is now live. Closing!
