### ISSUE TITLE
Parameterized GHA Workflows for PE Configuration

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#55644]
# Description
For the post-MVP implementation of Preview Environments, we want to be able to generate an environment that accommodates some set of user preferences for environment variables by taking inputs from the user. How might we allow the user to configure their preview environment? Some potential items for configuration are --
1. Environment variables
1. Version of code used for supplemental repositories
1. Time to keep the preview environment alive
1. Who has access to the preview environment
1. Version of the Drupal cache to use

# Acceptance Criteria
- [ ] We have an implementation plan for creating GHA workflows that take basic user inputs to affect the configuration of a preview environment

**Comment by JoeTice** [comment]
These tickets are OBE as our approach is shifting, closing these tickets to reflect that.
