### ISSUE TITLE
SOCKS access for Alastair Dawson (update)

### ISSUE THREAD

**Issue by kreek** [department-of-veterans-affairs/va.gov-team#55643]
### Your Name

Alastair Dawson

### Your Email

alastair@adhocteam.us

### Your Role and Team

Principal Engineer API Governance on Lighthouse

### Product Manager (PM) name and email

Danielle Baranowski <danielle.baranowski@oddball.io>

### Product Owner (PO) name and email

Dave Mazik <david.mazik@va.gov>

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCliuzJw9bl3Mr1xuHMdxZCbPJ6AjdWYziDaZ7tG4ImHINFhrsku6VYBsOVIIXntI2krUIYf7jwg8L8mCQ8pwwERtfJ7eQzscixZi6oOU04H5qeia2Zi6hzg5lpTFrurkF+2F9wWvBxbaHv5+sk2NTtpDoQ2G1ngN8lKYISRFzrMXJFcs3OweDAVx1j8gCp6s2Qdxz8c55HTNIgS4oHZkxujEjo9ZtmCU4t0Dnw32lq7+IgS4u3uSynAabmuFe4aSoBQ6gfrYoFSNoUmVTrV/40TZtZMh6WcTox8n0gyE3gt2uLsc6w3NaEv9FHJSDDLZHGWj+eXteH+XGmSik1/EwW1jKeTlv16E3zlLSL5o5VuwcG9AefE8/WtSTxxWE0tTKKkqGyxc4kA70IGQyjw92Qz+/KX31oDYVKETdxDWpQer40umcF4FyJcGzfs+OeF8q5aRTu7rMLUWFzDuZ7o35RzABpI3f8a0nj5rOCjwIudYUC4pb3hauXCO2P7L6Z/lM= alastairdawson@Alastairs-MacBook-Pro-2.local

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by little-oddball** [comment]
VFS Roster

**Comment by pjholyoke** [comment]
Merged.
