### ISSUE TITLE
VSA Accessibility Feedback for "Submit 686"

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#5565]
Definitely a complex undertaking!
**Should** 
1.  For individual’s info — “Your first name”, and the rest — consider repeating whose info pattern throughout, i.e. “**Veteran’s first name**” for cognitive ease, including for the Veteran.  

**Consider**
1. Thinking of the cognitive/emotional load of the former spouse info questions, I wonder about the possibility of allowing this to be completed in an unauthenticated state. This use case may need the save in progress functionality, or at least ability to save in an encrypted local storage session. 
2. If the country/city/county is a free text field, is it possible to clean the data b4 it goes into the db? Ensure not ALL CAPS, for example, to future-proof data.
3. What does the workflow / screen look like if someone starts filling out the form, saves, and comes back? [I think I just saw this in the forms systems demo.]
4. Have concerns about the cognitive load of this strung-together approach. Possibility of individual links to separate workflows, collect each of them, and provide review at the end to collect into a single submission, to ease cognitive impact. 

**Note:** I am trying a new framework for providing input (Feedback on this is welcome!): 
- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 
```diff
- "Must" for if the feedback must be applied 
! "Should" if the feedback is best practice 
+ "Consider" for suggestions/enhancements 
```

**Comment by jason-gcio** [comment]
For ** Should 1**: At this time, per Peggy, because we are referencing the Veteran in the section title and we are going to be talking directly to Veterans in this first version, we should leave the field titles as is, for now.

**Comment by jason-gcio** [comment]
For **Consider 1**: unauthenticated form usage is an ongoing discussion at this time.
For **Consider 2**: massaging or scrubbing data entered before (or after) it interacts with the db is not really within our scope but the use of CAPS in our example is not necessarily the case for how data always comes back.
For **Consider 3**: we are interested in making sure this works well and will demo when the time is right.
For **Consider 4**: lets talk more about this and get some clarity.

**Comment by jenstrickland** [comment]
For **Should 1**: Looping in @1Copenut -- The 686 flow is likely to have lots of twists and turns of context, from Veteran to spouse, to other spouse, and spouse's previous spouse, plus the mobile context. Depending on how long some of the sections get, it can be tough to remember whose info it is. I got lost reviewing the mocks. If timeline allows, it would be helpful to validate with usability testing of the mobile scenario + participants with 70% rating + TBI &/ PTSD. Caregivers may also have cognitive considerations, due to the demands of their role.

**Comment by jason-gcio** [comment]
@sporeboy - I am reminded of this thread as we start talking about deeper usability sessions.  Take a look and lets see how we can include these ideas.
