### ISSUE TITLE
Sidekiq Admin UI Access Request

### ISSUE THREAD

**Issue by caseywilliams** [department-of-veterans-affairs/va.gov-team#55655]
- GitHub username: caseywilliams
- Reason access is required: I'm a vets-api backend developer on the Lighthouse appeals team (we maintain the decision reviews, appeals status, and benefits intake APIs) - we use sidekiq jobs to process all of our forms, and to automate other tasks - being able to access the UI will help us troubleshoot when things go wrong
- Environments requesting access to: dev, staging, sandbox, and prod

**Comment by ryan-mcneil** [comment]
@caseywilliams You've been granted access to all environments, with access to Production limited to 6 months, expiring 11/5/23

**Comment by ryan-mcneil** [comment]
Slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1683305951323979)

**Comment by bdech** [comment]
@caseywilliams  Your Sidekiq Admin UI Production access has expired. Would you like to request an extension of access?

**Comment by bdech** [comment]
Removing production due to no response. If you would like to request Production access, please fill out a new request.
