### ISSUE TITLE
Vets-api terminal access for Casey Williams

### ISSUE THREAD

**Issue by caseywilliams** [department-of-veterans-affairs/va.gov-team#55656]
### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Casey Williams

### Your GitHub handle (terminal access is managed through GitHub)

caseywilliams

### Team, Role, and Company of the target individual

Casey Williams, Backend Developer on Banana Peels (Appeals) Lighthouse team, Ad Hoc LLC

### Product Manager (PM) name and email

Michael Hobson (michael.hobson@adhocteam.us)

### Product Owner (PO) name and email

Janet Coutinho (janet.coutinho@va.gov)

### Your dsvagovcloud AWS user name (if applicable)

Casey.Williams

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### COR Name (leave "None" if you listed an AWS user name above)

Courtney Bethea

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

Liberty IT -  Michael G. Lovejoy

### Access Expiration

ongoing

### Additional Notes

I'm a vets-api backend developer on the Lighthouse appeals team (we maintain the decision reviews, appeals status, and benefits intake APIs). Being able to access the rails console in the deployed environments would be extremely helpful in validating that newly deployed changes are working in cases where they can't be validated with a simple API request. So far, I've had to ask other developers with more access to do this for me, but I would prefer to be able to these kinds of changes myself. Without production console access, I also haven't been able to help much when troubleshooting production issues reported to our team.

### User must exist in a roster before vets-api terminal access can be granted

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added
- [ ] If they included an AWS user name, check to see if their user name is listed in [iam_users.tf](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf)
- [x] Comment in this issue saying which roster the user is listed in and confirming their AWS user name (if applicable)

**Comment by little-oddball** [comment]
VFS Roster

**Comment by caseywilliams** [comment]
Hi all, just pinging again and hoping this doesn't get lost - it's pretty hard to move work to a complete state without being able to do anything in the console

**Comment by BillChapmanUSDS** [comment]
Approving production access for 3 months or until we update teh current process (discussion in progress)

**Comment by ryan-mcneil** [comment]
@caseywilliams Production access has been granted until July 17

**Comment by ryan-mcneil** [comment]
Slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1681751090598769)

**Comment by jknipes** [comment]
@caseywilliams Your ArgoCD/vets-api Production access has expired. Would you like to request an extension? You have 7 days to respond, or your access will be revoked and you will need to fill out a new request.

**Comment by jknipes** [comment]
@caseywilliams Per an update to our access policy, your ArgoCD/vets-api Production access has been extended for 3 months, expiring 10/24/23. Please set a reminder for yourself to return to this Issue and re-request access within 1 week of the expiration date. You'll receive 1 reminder with a 48 hour window to respond. Failure to do so will result in lost access and will require you to fill out a new request.

**Comment by jknipes** [comment]
Support reminder [HERE](https://dsva.slack.com/archives/C02RLAUM2LV/p1690234990407949)

**Comment by jknipes** [comment]
@caseywilliams Your vets-api terminal Production access has expired.
Would you like to request an extension? 
You have 72 hours to respond, or your access will be revoked and you will need to fill out a new request.
