### ISSUE TITLE
ClamAv service has no input control for the file size exceeding 100 MB

### ISSUE THREAD

**Issue by considerable** [department-of-veterans-affairs/va.gov-team#55666]
## What happened?

As per [attachment and file size limits](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/claims_api/app/swagger/claims_api/description/v1.md#attachment-and-file-size-limits), there is no limit on the number of files a payload can contain, but size limits do apply:
 - Uploaded documents cannot be larger than 11" x 11"
 - The entire payload cannot exceed 5 G
 - No single file in a payload can exceed 100 M

@LindseySaari - below this line, i'd provide the evidence how ClamAv is not rejecting a request to scan a file that is greater than 100M. However, the new default in ClamAv is exactly 100M so that we might not see any problem. Still, it is best and future-proofing to put an explicit 100M limit and test it.

Starting with [ClamAV v0.105](https://blog.clamav.net/2022/05/clamav-01050-01043-01036-released.html), the default limits for file and scan size are increased:
- MaxScanSize: 100M to 400M
- MaxFileSize: 25M to 100M

## Specs:
- Good file, 99M:
```
dd if=/dev/urandom of=/tmp/dummy99.pdf count=99 bs=1M
```
- Bad file, 101M:
```
dd if=/dev/urandom of=/tmp/dummy101.pdf count=101 bs=1M
```

## Steps to Reproduce
- TCPSocket on EKS sidecar: 127.0.0.1:3310
- TCPSocket on Docker sidecar: host.docker.internal:3310

## Desired behavior
Explicitly setup ClamAV config to reject oversized files, perhaps in `vsp-infra-clamav` repo
```
diff --git a/clamd.conf b/clamd.conf
index 21e0919..7d14e79 100644
--- a/clamd.conf
+++ b/clamd.conf
@@ -5,3 +5,6 @@ DatabaseDirectory /var/lib/clamav/database
 LocalSocket /var/run/clamav/clamd.socket
 TCPSocket 3310
 TCPAddr 0.0.0.0
+
+# Explicitly reject files larger than 100M
+MaxFileSize 100M
```

## Acceptance Criteria
- [ ] test on a 99M file in vets-api-web EKS pod
```
dd if=/dev/urandom of=/tmp/dummy99.pdf count=99 bs=1M
echo "SCAN /vets-api/dummy99.pdf" | ncat 127.0.0.1 3310
```
- [ ] test on a 101M file in vets-api-web EKS pod
```
dd if=/dev/urandom of=/tmp/dummy101.pdf count=101 bs=1M
echo "SCAN /vets-apidummy101.pdf" | ncat 127.0.0.1 3310
```
- [ ] test on a 99M file in vets-api Docker container
```
dd if=/dev/urandom of=/tmp/dummy99.pdf count=99 bs=1M
echo "SCAN /vets-api/dummy99.pdf" | ncat host.docker.internal 3310
```
- [ ] test on a 101M file in vets-api Docker container
```
dd if=/dev/urandom of=/tmp/dummy101.pdf count=101 bs=1M
echo "SCAN /vets-api/dummy101.pdf" | ncat host.docker.internal 3310
```

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by laineymajor** [comment]
This will not have an impact on the `/v0/search` rollout, but needs to be fixed prior to other rollouts.

**Comment by laineymajor** [comment]
Looks like this might be an EngineX issue @RachalCassity @LindseySaari to add some detail.

**Comment by laineymajor** [comment]
@oseasmoran73 @rmtolmach eyes on this, please!

**Comment by LindseySaari** [comment]
[PR created here](https://github.com/department-of-veterans-affairs/vsp-infra-clamav/pull/58) for review.

**Comment by oseasmoran73** [comment]
Looks like the PR has been merged. Moving to review state @LindseySaari @laineymajor
