### ISSUE TITLE
Editing saved military base mailing address behaves poorly

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#5566]
If you edit a mailing address that's a military base address, the edit modal doesn't behave correctly.

1. Sign into staging with user 37
2. Go to https://staging.va.gov/profile/
3. Edit the mailing address (which is currently an FPO in AE)

## Weirdness/bad behavior seen:
1. The "I live on a military base" checkbox should be checked.
2. But since it's not I'd expect to see a text field for City, but instead it's a dropdown for APO/DPO/FPO.
3. In order to get the City field back you need to check and uncheck the "I live on a military base" checkbox or select a country other than United States and then switch back to United States

## Expected behavior:
1. When you edit a saved address that's a military address, the "I live on a military base" box should be checked by default and the form should act as it does when that box is checked manually (ie, disable the Country drop down, limit the State options AA, AE, and AP, provide a dropdown instead of the City text field)
2. Unchecking it should restore normal, non-military base address behavior.

### Notes
- This all functions correctly with the new schema form-based edit address form that's being worked on here https://github.com/department-of-veterans-affairs/va.gov-team/issues/5078, so it might not be worth addressing this bug in the current edit address form

**Comment by erikphansen** [comment]
It's even worse than I first thought. On first page load, it appears to be impossible to get the City field to appear by simply checking/unchecking the "military base" checkbox

![ScreenFlow](https://user-images.githubusercontent.com/20728956/73887224-faf88b00-481f-11ea-850a-5bd495009198.gif)

**Comment by erikphansen** [comment]
Looking at this on staging now with the new version of the form and the checkbox is not checked like it should be but it otherwise behaves fine. Hopefully getting that checkbox to be preselected should be easy.

**Comment by Samara-Strauss** [comment]
This was working just fine for user 37 initially. When I went to edit their address, the checkbox was checked as expected.

But then I entered a bogus military address: 

811 Vermont Ave
FPO, AE 20571

And this triggered address validation. I chose to override the determination that the address was bad, clicked "Use this address", and the form closed. The address saved just fine, but then when I went to edit it, the checkbox was unchecked again. So, it appear something with address validation is breaking that checkbox.

<img width="478" alt="Screen Shot 2020-02-12 at 4 21 46 PM" src="https://user-images.githubusercontent.com/34068740/74378362-d0747800-4db3-11ea-98d2-e53ac0868d71.png">
<img width="497" alt="Screen Shot 2020-02-12 at 4 21 53 PM" src="https://user-images.githubusercontent.com/34068740/74378368-d23e3b80-4db3-11ea-8d57-5d387c434e58.png">

**Comment by erikphansen** [comment]
@Samara-Strauss it seems like this is due to the fact that we tell VA Profile that the bogus FPO address is an `"OVERSEAS MILITARY"` address when we save it, but once we fetch that saved address from VA Profile it comes back as a `"DOMESTIC"` address. And that checkbox is prechecked only for `"OVERSEAS MILITARY"` addresses.

But if we re-save the original address, `PSC 808 Box 37 FPO, Armed Forces Europe (AE) 09618`, the behavior works again. Seems that VA Profile calls an address an `"OVERSEAS MILITARY"` address based on the zip code; 09618 is a valid military base address, but 20571 is not.

We _could_ add logic to treat a saved address like a military based address if its city is APO/DPO/FPO and state is AA/AE/AP, but I think trusting VA Profile to flag the address correctly is probably the right choice.

**Comment by erikphansen** [comment]
So I think we should close this, unless there are other issues, and if we want to change how we determine if the saved address is an overseas military base that can be another ticket.

**Comment by Samara-Strauss** [comment]
> Seems that VA Profile calls an address an "OVERSEAS MILITARY" address based on the zip code; 09618 is a valid military base address, but 20571 is not.

> We could add logic to treat a saved address like a military based address if its city is APO/DPO/FPO and state is AA/AE/AP, but I think trusting VA Profile to flag the address correctly is probably the right choice.

Agreed. If they are classifying off of zip code, let's leave this as-is. Closing!
