### ISSUE TITLE
Staging:  Duplicate Appointments Display

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#55677]
1. Log into VAOS.  View upcoming appointments.
2. Expected Response:  Appt display
3. Actual Response:  Duplicate appointments display. When select to view details, in the URL the appointment ID is the same.
4. Looked at response body and the appointment is only listed once.  I tried several patients:  Royal.tester@id.me and ola.e.edgecombe@id.me

https://staging-api.va.gov/vaos/v2/appointments?_include=facilities,clinics&start=2023[…]tatuses[]=arrived&statuses[]=fulfilled&statuses[]=cancelled
![image.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/596111cd-7009-4351-97ea-b00549af615f)

**Comment by ldelacosta** [comment]
@marcynadeau - this ticket is ready to be reviewed. Please let us know if you have any questions or issues. Thanks!
