### ISSUE TITLE
Download/digital decision letters content updates

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va.gov-team#55675]
## Issue Description
Laura and Misty collaborated to make final tweaks to Download/Digital Decision Letters. This ticket is to track the final content so that it can be implemented on VA.gov. This doesn't block the launch of this feature.

## Documentation of Decisions
[Slack thread in #content-community-collaboration on content decisions](https://dsva.slack.com/archives/C03RFTSTMC7/p1679327682832929)

## Suggested Changes
New changes are in the checkboxes. Sub-bullets describe change on VA.gov, a link to the current Sketch file, and a screenshot of the current screen that needs changed.

- [x] We decided your claim on [date]
     - Changing from "closed" to "decided" was by [Beth Potts in this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54874#issuecomment-1490850988)
- [x] You can download your decision letter [online now/in the app]. We also mailed you this letter.
     - This is a change to the content in the blue alert box on a closed claim. 
Note the "in the app" part is not applicable to VA.gov. 
[Here is the current VA.gov version that needs changed](https://www.sketch.com/s/8b025901-295d-4929-95cc-8dbeb28454b3/v/DDGpx2/p/CAA1846C-79ED-4BDB-94B9-BA0EBE74EC5B/canvas?posX=-6590.960435424902&posY=-501.28525756625703&zoom=0.4730564057826996)
![Screenshot 2023-03-24 at 6.59.17 AM.png](https://images.zenhubusercontent.com/6266db4f486bbe5e4f5cd2fd/132bb19f-5676-47e1-8ed2-4d40042f564b)

- [x] You can download your claim letters. We also mail you these letters.
     - This is a change to the content after the H1 header on the list of letters screen. [Here is the current VA.gov version that needs changed](https://www.sketch.com/s/8b025901-295d-4929-95cc-8dbeb28454b3/v/DDGpx2/p/CAA1846C-79ED-4BDB-94B9-BA0EBE74EC5B/canvas?posX=-6966.014913087879&posY=-628.018981013587&zoom=0.4967584013938904)
![Screenshot 2023-03-24 at 7.04.35 AM.png](https://images.zenhubusercontent.com/6266db4f486bbe5e4f5cd2fd/d54725a6-85d9-460d-a43a-b0c35a655709)

- [x] **[Date] letter**
      - This change is for the ordering and wording on the bolded letter title. Instead of saying "Letter date [date]," we will put the date first and the word "letter" at the end. [Here is the current VA.gov version that needs changed](https://www.sketch.com/s/8b025901-295d-4929-95cc-8dbeb28454b3/v/DDGpx2/p/CAA1846C-79ED-4BDB-94B9-BA0EBE74EC5B/canvas?posX=-7114.980687581794&posY=-551.5230427599549&zoom=0.4967584013938904)
![Screenshot 2023-03-24 at 7.04.35 AM.png](https://images.zenhubusercontent.com/6266db4f486bbe5e4f5cd2fd/84d8d858-2d7d-4a68-b379-868df930ddc1)

- [x] **No claim letters**
You don't have any claim letters yet.
     - This change is to the empty state when there are no letters on the list of claims letters. [Here is the current VA.gov version that needs changed](https://www.sketch.com/s/8b025901-295d-4929-95cc-8dbeb28454b3/v/DDGpx2/p/CAA1846C-79ED-4BDB-94B9-BA0EBE74EC5B/canvas?posX=-7779.287519784388&posY=-1618.4400762974544&zoom=0.4967584013938904)
![Screenshot 2023-03-24 at 7.10.24 AM.png](https://images.zenhubusercontent.com/6266db4f486bbe5e4f5cd2fd/415d18a5-9cb8-48c3-8753-ca2f575b43e4)

**Comment by laurwill** [comment]
Hi @jacobworrell , Misty and I opened this ticket to track some content update suggestions for the claim status tool —  Misty made these tweaks in the mobile version, so now we're suggesting updates to the web version to keep them parallel. 

Sorry for delay in passing these along — I was anticipating adding a request to add "decision letters" inside the tool, but that's now tracking over [in this ticket](https://app.zenhub.com/workspaces/sitewide-content-accessibility-and-ia-63a1d63232beba0011a7833f/issues/gh/department-of-veterans-affairs/va.gov-team/47744). 

Let us know if you want to chat about any of these items!
