### ISSUE TITLE
Sitewide Content, Accessibility, and IA Review of unified appointment check-in experience from Modernized Check-in Experience

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#55686]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more unauthenticated pages, online forms, apps, or tools on VA.gov
- [x] Making revisions to one or more existing VA.gov pages
- [ ] Something else 
 
 *Give a brief description of what your team needs support with.*

**Problem**

The Modernized Check-in Experience Team is looking to evolve Patient Check In (PCI) to make it even easier for Veterans to, 1) confirm their upcoming appointments, and 2) check in for their appointments using their smartphone.

The problem areas that we're looking to address are:

- Veterans and staff don’t understand the differences between pre-check-in and check-in.
- Many Veterans use the pre-check-in link sent via SMS to initiate eCheck-in, which does not allow them to check in.
- Some Veterans skip checking in altogether when they arrive at the clinic because they think they’re checked in as a result of completing pre-check-in, which, in fact, does not initiate or complete the eCheck-in process.

**Solution**

Create a single, consistent check in app experience, instead of two applications, that supports, and highlights, medical appointment tasks that need to be completed (no matter which text message link is used to navigate to the check in application) and provides a larger view of all upcoming and past appointments (similar to the appointments tool in VAOS).

**Additional Background**

PCI is adopting the appointment list and detail page design from the VAOS application. ([Collab cycle](https://app.zenhub.com/workspaces/vaos---productdesign-5fff340c2d80a4000fb6f69c/issues/gh/department-of-veterans-affairs/va.gov-team/42025).) Here are some links to their design artifacts: 

- [VAOS appointment list page (Figma)](https://www.figma.com/file/JpGM8LGBCqAlL8qh3DmFk8/Home-Page-Redesign?node-id=2161-54658)
- [VAOS appointment modalities naming (Figma)](https://www.figma.com/file/JpGM8LGBCqAlL8qh3DmFk8/Home-Page-Redesign?node-id=985-47474)
- [VAOS appointment detail page (Figma)](https://www.figma.com/file/RcDljBwThbwVDkNrDH2xiA/Appointment-Details-Redesign?node-id=2-4&t=S2yAAFdUbarvvquV-0)

In addition, PCI has recently launched a version of our two applications that align with the VAOS appointment list page and detail page design, to the extent possible. That feature launched is in production now. ([Collab cycle](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/50817).) We have also just initiated a 508 audit request for that feature. ([508 audit request](https://yourit.va.gov/va?id=sc_request&is_new_order=true&table=sc_request&sys_id=cf25329c1b792d105d46cb78624bcbfd).)

**Support Request**

1. Review content that has changed in our [draft wireframes (Sketch)](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec) and provide feedback. Content that needs review is identified with a comment on an artboard that begins with, "For Sitewide content review." Viewing comments works best using the Sketch web app. If you need to zoom into an individual wireframe/artboard, you can double click the artboard name that will direct you to that individual wireframe/artboard. For example, [https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/bgwvQKZ](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/bgwvQKZ). Please leave a reply to the comments. Or, you can add a new comment on an artboard and tag Ben Brasso.  Note: One comment was added on 4/6/2023 to take a look at the pre-check-in text message. 
1. Provide feedback from an IA and accessibility perspective on our [draft wireframes (Sketch)](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec). 

**Other Notes**

- Our [Sketch file](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec) has two rows of wireframes. The first row is the user flow for the happy path. The row of wireframes beneath it are alternative paths. There are a few comments identified for content review in the alternative paths, but overall, we'd recommend prioritizing review of the happy path from an IA and accessibility perspective.     
- Some features and/or appointment types or modalities found in the wireframes will not be included in the MVP. However, those have not been identified to date. For example, past appointments. 
- We have received some feedback to date on IA and accessibility through collab cycle or speaking with DK, including:
     - https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/51485 
     - https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/51400
     - https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/54483
     - Keep tasks located at the bottom of [appointment detail pages](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/v8VkyAn) for individuals using screen readers to first read through the information on the page. 
     - Ensure that the HTML markup for headings winds up starting from largest to smallest on the page, especially for scenarios when the heading being used from the design system does not support nested semantic headings. 

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [x] Yes
  - [ ] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
## When do you expect to launch your product to 100% of users?
  
*Please provide an estimated date so our team can create other relevant tickets.*

Too early to estimate. Best guess is Q4 2023. 
  
## Supporting artifacts
*Please provide supporting artifacts as available.*

- Link to product outline: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/README.md
- Link to or attach user flows:
- Link to prototype or mockups: [Sketch file](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec) and [individual sketch artboard](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/bgwvQKZ)
- Link to any epics/issues that may be helpful: [Collab cycle](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/53488)

## Will this work be going through the Collaboration Cycle?
- [x] Yes 
- [ ] No

## When does this work need to be done?
- Estimated launch date: December 1, 2023
- Estimated staging review date: October 1, 2023
- Content, Accessibility, and IA work needed by: April 5, 2023 (flexible)

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: Modernized Check-in Experience 
-	OCTO-DE product owner: Stephen Barrs
-	Product manager: Lori Pusey
-	Designer: Ben Brasso, Christina Gednalske, Kelly Smith, Zach Park, Ya-ching Tsao 
-	FE engineer: Brian Seek, John Woolschlager
-	Product/team Slack channel: check-in-experience 

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by coforma-terry** [comment]
Hey @benbrasso-agile6 - FYSA - we'll do our very best but not sure we'll have all this wrapped up by April 5th :)

**Comment by benbrasso-agile6** [comment]
Thanks, Terry

**Comment by benbrasso-agile6** [comment]
@coforma-terry were you working on providing feedback from an accessibility standpoint and IA and content? Or, is @RLHecht handling the IA and content side of this ticket? Wanted to make sure I understand how each part is progressing. Thanks!

**Comment by coforma-terry** [comment]
Hey @benbrasso-agile6 - so @RLHecht will be handling the content and IA side, while I take accessibility - but for the most part we try to coordinate as much as possible to avoid duplicating efforts etc if that makes sense :)

**Comment by aliyahblackmore** [comment]
Hi @benbrasso-agile6 - my name is Aliyah and I'm a writer on the sitewide content team. 

We're starting to take a look at this content and just wanted to drop a few questions here:

1. I just want to confirm that the content called out in the sketch screen/that is being called out for us to review is only new content? I know that you all are using some of the VAOS content that was previously worked on, so we just want to make sure we're not reviewing that again.
2. I also just want to confirm that [this](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/bgwvQKZ) is the only sketch screen that we should be looking at for content? I see that there are two comments here marked with "For sitewide content review," but there **isn't a specific artboard** that begins with "For sitewide content review," as the support request details mentions.

Thanks so much for your collaboration on this!
 
CC: @RLHecht

**Comment by benbrasso-agile6** [comment]
Hello, 

1. There are roughly a dozen comments that you'll see in [sketch](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec) that start with "For sitewide content." Those comments are new and/or revised content for our web apps that we'd like to be reviewed. 
2. That is an example of one artboard of our larger [sketch page](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec). The one you referenced was simply called out as another way to navigate sketch. Here is a quick screenshot of the comments we're looking reviewed: 

<img width="963" alt="Screen Shot 2023-04-05 at 6 27 53 PM" src="https://user-images.githubusercontent.com/101129355/230226166-b10da5b9-02b8-4a73-a483-7b79e8964a3e.png">

Happy to set up a call to discuss. I am planning to drop into office hours tomorrow as well. So, happy to discuss any questions there too! Thanks!

**Comment by benbrasso-agile6** [comment]
@aliyahblackmore @RLHecht I added one comment this morning to sketch to take a look at the pre-check-in text message. This was something that we discussed at content office hours this morning. I also noted that in the above request to under Supper Request > 1.

**Comment by laurwill** [comment]
Hi @benbrasso-agile6 , we've added comments and responses to all the sketch screens you called out to us — I'll also share a few higher-level thoughts here by Monday, but wanted to confirm that our specific content suggestions are in the sketch screens. Happy to sync again or talk through any questions you have on slack. Thanks again so much for your collaboration and for syncing with us to talk through this tool!

**Comment by laurwill** [comment]
Hi again @benbrasso-agile6 , 
Adding few more thoughts in addition to the Sketch comments:
- **Task flow vs full appointment list:** We had some discussion in our syncs about this being primarily a task flow. We understand you want to test the approach of bringing users to the full appointment list page with a top card for the priority CTA, so we provided content suggestions for those screens. We'd still recommend trying an approach that takes users from the text message directly to the action — either checking in or reviewing their contact information. Then, when that action is complete, offering other actions for other upcoming appointments. We think that would align more with what Veterans expect coming from the text message content about a single appointment.
- **Communication with VEText:** We understand there are some open questions about how VEText communicates with this system. But just documenting what we talked about: If the Veteran gets a text that lets them confirm via text reply, we shouldn't ask them to confirm again in this system. And vice versa, if the Veteran gets a link to “Confirm” an appointment in this system, we shouldn't then send them a text asking them to confirm the same appointment. We already suggested changing the main "Confirm" CTAs here into "Review information" CTAs. But if it turns out communication with VEText isn't possible, we'd need to remove all "confirm appointment" links from this flow.
- **Updating information:** What happens if a user selects "no" when asked if their info is accurate? We had assumed this flow lets them update their information, but the Q&As on the confirmation page seem to say they need to go elsewhere. Do they need to leave this flow and sign in to update their VA.gov profile?

Also linking the screens with our key comments here:
- [Text message screen](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/DEPQpLj#Comment)
- [Verify identity](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/x00d8A5#Comment)
- [Appointment list with pre-visit tasks](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/bgwvQKZ?annotation=778721ff-e65c-4b05-92a1-fe127dc610d7#Comment)
- [Confirmation page](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/zx95r4b?annotation=0207e620-ef19-4f61-9d0e-7fe075cab102#Comment)
- [Check in confirmation page](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/L40YYnQ?annotation=29bf88bc-5190-4ba4-b06e-5d37be486242#Comment)

**Comment by benbrasso-agile6** [comment]
Thank you! Will give them a review.

**Comment by cgednalske** [comment]
Hi @aliyahblackmore @laurwill @kristinoletmuskat 👋 Thanks for the great discussion today! Ben and I narrowed down what the more urgent content needs are ahead of midpoint review and research, so we can first work through those and then spend more time digging into some of the other questions won't be part of testing our happy path. 

Below are those more urgent questions we didn't quite resolve today. Ben jotted down notes for everything else that we can follow up on separately. 🙂 

**"You have appointments that need review" text in tasks link collection:** 
We plan to test the current location for this and determine if a) it's noticeable enough and Veterans can easily get back to the appointment list and b) if they would expect to find this info here or somewhere else. Within the current placement in the link collection, are there any changes we should make to this text to convey that "there are things to do/that need attention" back on the appointment list?

An example of this is on [this page](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/zx95r4b).

<img width="427" alt="Screenshot 2023-05-04 at 12 25 29 PM" src="https://user-images.githubusercontent.com/79372956/236314127-9e2ac3cd-2040-41ae-b2c8-a5c275c1d488.png">

**Confirm your appointment card:** 
Along with the "review your information" card, we have an updated "confirm your appointment" card that will be surfaced for other appointments after information has been reviewed. Does this new header text work? This can be viewed on the [card annotations page](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/71pyOEE).

<img width="472" alt="Screenshot 2023-05-04 at 12 24 00 PM" src="https://user-images.githubusercontent.com/79372956/236314546-d30b83a0-b5a1-4093-9d3a-35ef223fddf2.png">

**Comment by laurwill** [comment]
Hi @cgednalske ,

For the "needs review" wording, we removed "Prepare" from the H1 on the linked screen, correct? How about this?

**Review upcoming appointments**
It's time to confirm or check in for other appointments now. 

For the confirm appointment card, suggest removing the "Upcoming appointment" subhead and the line about saving time — these don't seem necessary and they're adding a lot of extra words. And we'd hyphenate "in-person" when it's an adjective before "appointment."

**Confirm your appointment**
[Date and time]
In-person appointment with Anna Dickerson
> Confirm your appointment [link]

**Comment by RLHecht** [comment]
Sounds good! Closing this one for now!
