### ISSUE TITLE
[a11y design review] Login.gov organic adoption

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#55683]
## Auditor(s)

Sarah Koomson (SK)

## Design Review
Based on the development of the prototype, some of the following may or may not be applicable. 
- [x] [Color and contrast checks](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review#use-of-color)
  - [x] WCAG 2.1 AA
  - [x] WCAG 2.1 AAA
  - [x] [Who Can Use](https://www.whocanuse.com/?b=ecece5&c=000000&f=20&s=)
  - [x] High Contrast Mode
- [x] [Keyboard navigation](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review#keyboard-nav)
  - [x] Annotations for Tab order, reflow and reading order (if needed)
- [x] Accessible Name Annotations
  - [x] [Alt attributes for images](https://webaim.org/techniques/alttext/)
  - [x] Text alternative for complex images such as charts graphs maps etc.
- [x] Language (ease of reading)
- [x] HTML Tags
  - [x] [Page Title](https://accessibility.18f.gov/page-titles/)
  - [x] [Heading order](https://accessibility.18f.gov/headings/)
   - [x] Annotations (if needed)
  - [x] Semantic Consideration for paragraphs ordered lists numbering
  - [x] [Tables (heading rows)](https://design.va.gov/components/table)
- [x] Size of clickable areas

### As Time Allows
- [ ] [Components](https://design.va.gov/components/) follow VA design system guidance.
- [ ] [Patterns](https://design.va.gov/patterns/) follow VA design system guidance.

## Prototype Link

https://www.figma.com/file/8vobVoSl1UqLnXsni3rcvO/Login.gov-Migration%3A-Grandfathering-IAL1-Flow?node-id=154%3A1300&t=CM3Q1iDV4SG2m50M-1

https://www.figma.com/file/8vobVoSl1UqLnXsni3rcvO/Login.gov-Migration%3A-Grandfathering-IAL1-Flow?node-id=154%3A1310&t=CM3Q1iDV4SG2m50M-1

https://www.figma.com/file/8vobVoSl1UqLnXsni3rcvO/Login.gov-Migration%3A-Grandfathering-IAL1-Flow?node-id=154%3A1296&t=CM3Q1iDV4SG2m50M-1

## Moderate (defect 3)
Prototype One - Concerns with Modal 
![C583AA9A-AAC0-44D0-9803-302568910EBC.jpeg](https://images.zenhubusercontent.com/623cd4d6774110eeb19922cb/511f610d-f129-482e-af58-cc5e41d353e2)

### Concise issue description
 With a modal in the flow, it adds a lot of cognitive load and might lead to people forgetting what they wanted to do.

#### Bandaid solution
From a usability standpoint please deviate from using this modal on page load. Bandaid solutions- Link to it as a separate page static page, add it to the main page content, or add it to the existing login workflow.

#### Recommended solution
Move content out of the modal and into the main body of the page.

**Comment by SarahKay8** [comment]
@CarlDickerson Design Review complete. Please close out once reviewed.

**Comment by sara-amanda** [comment]
## CAIA Update

**5/25/2023** Login.gov IA Sync Meeting - **Modal no longer being triggered,** there is an email being triggered instead, and they are going to be working with VA Notify for these. 

_Updating ticket to reflect this update, should this ticket be referenced for a modal example in the future, testing took place, but the modal is not being implemented at this time._ 

@SarahKay8 @artsymartha68 @coforma-terry
