### ISSUE TITLE
[Development] BDD: Create Skeleton for BDD MVP Form

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#5569]
## User Story:
As a veteran, I need to be able to apply for my VA benefits before I separate from the DoD so I can get my benefits in a timely manner.

Create the skeleton for the BDD form.

## Acceptance Criteria:
- [ ] Overall BDD skeleton for the entire form is ready for page edits.

## Configuration
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (e.g. `vsa-authenticated-exp`, `vsa-caregiver`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ndsprinkle** [comment]
Invision: https://vsateams.invisionapp.com/share/BUWOTNKFPK7#/screens
