### ISSUE TITLE
Update Staging Redis in Elasticache from 3 to 6.2 or higher by July 2023

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#55701]
## Description
Redis 3.2.4, 3.2.6 and 3.2.10 will be EOL on July 31st 2023

- https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/deprecated-engine-versions.html

## Tasks
- [ ] Update Terraform (infra as code)

## Acceptance Criteria
- [ ] Staging Redis instance(s) are at or above version 6.2

**Comment by rmtolmach** [comment]
Looked at this in CoP meeting. We think the discovery and planning for this should be done by the end of May.

**Comment by laineymajor** [comment]
Done... this is a dupe https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/64051

**Comment by jennb33** [comment]
Closing this, don't know why it was reopened.
