### ISSUE TITLE
Update Prod Redis in Elasticache from 3 to 6.2 or higher

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#55702]
## Description
Redis 3.2.4, 3.2.6 and 3.2.10 will be EOL on July 31st 2023

- https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/deprecated-engine-versions.html

If possible, start with lower environments.

## Tasks
- [ ] Update Terraform (infra as code)
- [ ] Extra deodorant

## Acceptance Criteria
- [ ] Prod Redis instance(s) are at or above version 6.2

**Comment by rmtolmach** [comment]
Looked at this in CoP meeting. We think the discovery and planning for this should be done by the end of May.

**Comment by jennb33** [comment]
This update is scheduled for 1/30/2024 at 2am ET @flooose

**Comment by jennb33** [comment]
1/30/2024 - Upgrade was cancelled by VA due to a need for more time to prepare for deployment. New schedule is to come following guidance from leadership. cc: @flooose @little-oddball @LindseySaari

**Comment by jennb33** [comment]
Conversation with Jeff Keene regarding how to proceed with the upgrade to Prod<img width="1387" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXhaQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1685e9b702e66e48dedf18326d04a5b6cd329488/Screenshot%202024-02-14%20at%209.46.10%20AM.png" alt="Screenshot 2024-02-14 at 9.46.10 AM.png" />

**Comment by jennb33** [comment]
Per Aparna we need to re-schedule this upgrade: <img width="1375" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNk96QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cbba7152b3f1bb56b4afe90c81b299cecad38839/image.png" alt="image.png" />
Original slack messsage is [here](https://dsva.slack.com/archives/C06JM7UUHE3/p1709661023301929)
