### ISSUE TITLE
Secrets.yml cleanup 

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#55718]
## PROBLEM STATEMENT
The current lack of process in adding secrets.yml to the manifest repo is creating inconsistencies process and therefore causing breaking changes to be deployed (TLDR server problems).

We do not want people going into the AWS paramstore and potentially breaking the running servers, by deleting paramaters in the param store.

**Comment by laineymajor** [comment]
Closing as it's accounted for in our toil reduction work coming up!
