### ISSUE TITLE
Design | Profile | Update Sketch files: Add footer symbol at bottom of artboards that are missing it

### ISSUE THREAD

**Issue by fmccaf1** [department-of-veterans-affairs/va.gov-team#55724]
## Background

Some Sketch files include artboards that have a different footer than our standard footer symbol. For the sake of consistency, each artboard should have the same footer symbol.

## Tasks
Review these files and update the symbols if needed (including deleting any document specific symbols no longer needed)
- [x] Account security
- [x] Contact information
- [x] Notification settings
- [x] Direct Deposit
- [x] Personal information
- [x] Military information
- [x] Connected Apps

## Acceptance criteria

- [x] All Sketch files have been updated to use symbols from the design system

**Comment by andaleliz** [comment]
Completed
