### ISSUE TITLE
[EKS,Staging] Upgrade EKS Control Plane to 1.23

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#55734]
## Description
The EKS Control Plane needs updated from 1.22 to 1.23

## Notes
- https://vfs.atlassian.net/wiki/spaces/OT/pages/2471788560/EKS+Cluster+Upgrade#Upgrade-the-Control-Plane

## A/C
- [x] The EKS Staging Control Plane is running version 1.23

**Comment by hgbarreto** [comment]
##Pre-Upgrade Check
![image](https://user-images.githubusercontent.com/125288357/228314372-0cb1755a-c631-44c7-a6ea-3521f824a0ec.png)

**Comment by hgbarreto** [comment]
Staging EKS Control Plane upgrade complete
![image](https://user-images.githubusercontent.com/125288357/228318342-5f379a7a-15b6-41f4-9791-66f91dbc6c67.png)
