### ISSUE TITLE
[EKS,Dev] Upgrade EKS Nodes to 1.23

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#55739]
## Description
EKS cluster nodes need to be updated from 1.22 to 123

## Notes
- https://vfs.atlassian.net/wiki/spaces/OT/pages/2471788560/EKS+Cluster+Upgrade#Upgrade-the-Nodes

## A/C
- [x] The EKS Dev nodes are running version 1.23

**Comment by hgbarreto** [comment]
Upgrade Complete
![image](https://user-images.githubusercontent.com/125288357/228304377-87ede365-ea19-455b-b95f-0a03dd7c2d8c.png)
