### ISSUE TITLE
[EKS,Dev] Upgrade EKS Control Plane to 1.23

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#55733]
## Description
The EKS Control Plane needs updated from 1.22 to 1.23

## Notes
- https://vfs.atlassian.net/wiki/spaces/OT/pages/2471788560/EKS+Cluster+Upgrade#Upgrade-the-Control-Plane

## A/C
- [x] The EKS Dev Control Plane is running version 1.23

**Comment by hgbarreto** [comment]
## Pre-Upgrade Check
![image](https://user-images.githubusercontent.com/125288357/228247373-542a99c7-91ba-45ad-8d6c-70c8c883d4a9.png)

**Comment by hgbarreto** [comment]
Dev EKS  Control Plane upgrade complete
![image](https://user-images.githubusercontent.com/125288357/228305071-544717a3-95e0-475f-b718-29f9c229da2e.png)
