### ISSUE TITLE
[OCTO-DE Crew Onboarding]: Erika Washburn

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#55768]
### What OCTO-DE Crew is the team member joining?

Platform

### What OCTO Community of Practice is the team member part of?

Product

### Has user received VA.gov email address?

- [X] User has @va.gov email address

### VA Email Address

erika.washburn@va.gov

### Has user been added to Department of Veterans Affairs Github Organization?

- [X] User is member of Github org

### Github Username

@EWashb

### Has user been added to DSVA Slack?

- [X] User is member of DSVA Slack

### Slack Username

Erika Washburn

### Crew Specific - Platform

- [x] Add to Slack group: @octo-de-platform
- [x] Add to Github group: octo-de-platform
- [x] Post welcome Slack message: #platform-team
- [x] Register for Platform Orientation: https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=governance-team&template=orientation-epic.md&title=Platform+Orientation+Template+%5BYour+name+here%5D
- [x] Add to Confluence
- [x] Add to Confluence group "platform-crew-octo-de" https://admin.atlassian.com/s/10f8a514-fd86-4b32-8ba3-c0bfc6969f88/groups/81f1ea1a-fc6d-4b27-aed5-0bb73dd86c02
- [x] Update Team Roster (private) https://vfs.atlassian.net/wiki/spaces/OCLP/overview#Meet-the-team
- [x] Update Team Roster (public) https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623
- [x] Schedule recurring 1:1
- [x] Link to Platform team welcome guide https://vfs.atlassian.net/wiki/spaces/AP/pages/1413808450
- [x] Link to Platform team meetings https://vfs.atlassian.net/wiki/spaces/AP/pages/2141519911/Platform+Meetings
- [x] Schedule PO meetings with teams
- [x] Update Slack profile in accordance with https://depo-platform-documentation.scrollhelp.site/getting-started/Request-access-to-tools.969605215.html#Requestaccesstotools-Slack
- [x] Onboard to Pagerduty OOB Deploy https://dsva.pagerduty.com/service-directory/PSEM4B6

**Comment by EWashb** [comment]
Orientation [Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/55771)

**Comment by EWashb** [comment]
@mchelen could you add me to Pager Duty and give me an overview? After that's done we will be able to close this ticket.

**Comment by mchelen-gov** [comment]
Requested PD account: https://dsva.slack.com/archives/C01SCFMUNCA/p1681397382665389
After that I'll add you to the team: https://dsva.pagerduty.com/teams/PD4H1MP/users

We're going to do a training session for everyone: https://github.com/department-of-veterans-affairs/va.gov-team/issues/56829

**Comment by EWashb** [comment]
Registered for pager duty on 4/13/23

**Comment by mchelen-gov** [comment]
Ok you have been added to PD rotation: https://dsva.pagerduty.com/schedules#PPSGN31

To learn more see: https://vfs.atlassian.net/wiki/spaces/ECP/pages/1959165976/Out+of+band+deployment+approval

We'll walk through doc together as a team in the next week or two.
