### ISSUE TITLE
Document & Test Mock Auth for vets-api

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#55786]
## Description
For running synthetic tests against vets-api, we are limited in Datadog because we need valid auth cookies (which expire after ~30 min tops) The identity team has developed a solution to mock auth via Sign In Service in the development environment for testing purposes.

### Task
We should spin through and document the following:

#### Start with:
We’ve got mocked authentication ready to go (at least for API clients). I wanted to put down instructions on how to do it, if you were still trying to support automated authorized calls this can help (only on localhost or dev stacks):

- On `localhost`, in `idme/configuration.rb` or `logingov/configuration.rb`, set `log_credential` to `true`
- Authenticate with the test user on `localhost`, make sure to use `oauth=true` in the sign in modal to use sign in service
    - Once authenticated, a new file should be created in your `mockdata` repo representing the credential you authenticated with
- Take the new file that’s created, and perform the following: `encoded_credential = Base64.encode64(credential.to_json)`
- Now, on dev or localhost stack, start the `sign in service /authorize` process
curl `https://dev-api.va.gov/v0/sign_in/authorize?type=idme&code_challenge_method=S256&acr=loa3&client_id=vamock&code_challenge=1BUpxy37SoIPmKw96wbd6MDcvayOYm3ptT-zbe6L_zM=`
- Change `type=<csp>` to change csp you want to log in with
- This `curl`returns some params, take note of the state value
- Next, make a call to mocked authentication:
curl `localhost:3000/mocked_authentication/authorize?credential_info=<encoded_credential>&state=<state>`
- Use `encoded_credential` and `state` from above
- We intentionally don’t use `-L` option in `curl` to follow the redirect, since it’ll eventually redirect to the frontend, and we don’t want that
- The result of the curl will tell you the next url to curl, so copy that and follow it (it’ll say ‘you are being redirected to’):
- curl `https://dev-api.va.gov/v0/sign_in/callback?code=<code>&amp;state=<state>`
- This will say ‘you are being redirect to…’, grab the `code` from the URL: …`login/callback?code=<code>`
- Finally, make a call to sign in service to swap the code for tokens:
- `curl -X POST localhost:3000/v0/sign_in/token -H 'Content-Type: application/json' -d '{"grant_type": "authorization_code", "code_verifier": "5787d673fb784c90f0e309883241803d", "code": "<code>"}`
- This will give you back tokens that you can use for Bearer header for arbitrary authenticated routes

**Comment by laineymajor** [comment]
@rjohnson2011 you can potentially copy and paste the instructions (if they work) somewhere where others have access...

**Comment by laineymajor** [comment]
Tagged everyone, but this smaller item will be later int he week.

**Comment by LindseySaari** [comment]
I will run through this sometime during the week

**Comment by laineymajor** [comment]
Lindsey ran through an had an error on her local machine; Rachal also ran into problems but will look into this again today.

**Comment by LindseySaari** [comment]
I've added the instructions for[ how to mock auth in the EKS Endpoint Testing Doc](https://vfs.atlassian.net/wiki/spaces/pilot/pages/2485518367/EKS+Endpoint+Testing#Mock-Auth-(for-dev-and-local-stacks-only))

**Comment by laineymajor** [comment]
@RachalCassity have you been able to try this again?

**Comment by RachalCassity** [comment]
This is not working out of the box. 
1) client id is automatically set to vaweb - in localhost when oauth=true, the vamock should be the client id
2) File is not created in the mockdata repo

**Comment by RachalCassity** [comment]
I've been asking Identity questions regarding these instructions. I was sent [these](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity/Mocked%20Authentication) new instructions and attempting these today

**Comment by laineymajor** [comment]
Sending to the identity CoP as this is out of scope/expertise of our team. @RachalCassity please send ticket to appropriate folks.

**Comment by RachalCassity** [comment]
I was able to authenticate the user with these [instructions](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity/Mocked%20Authentication)
