### ISSUE TITLE
Update click targets to expand/collapse content in Status tab of CST

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#55797]
## Value Proposition

As a veteran trying to understand the status of my claim, I want to be able to clearly view contextual items related to different claims statuses, so that I can have deeper knowledge of where my claim sits in the process. 

## Background

Right now, the + and - icons are not clickable, which makes this pattern confusing and hard to use.

We need to expand the click target so that the user can expand/collapse by clicking on those icons as well as the text inline text and the number on the left. 

![Screenshot 2023-03-27 at 3.08.37 PM.png](https://images.zenhubusercontent.com/627a8fb8c44aae9087181480/00ff6eae-a634-4318-b184-d1edcf3db33b).

## Acceptance Criteria

- [ ] Designs are updated consistent with those provided in the comments
- [ ] Items collapse and open upon click/touch 
- [ ] Meets accessibility standards

**Comment by jerekshoe** [comment]
For context:
The yellow outline in the screenshot below highlights the clickable area currently. As highlighted above, the current clickable area doesn't include the +/- icons, which is unintuitive
<img width="507" alt="Screenshot 2023-03-27 at 2 48 07 PM" src="https://user-images.githubusercontent.com/13838621/228050800-c4b9aae6-7f18-4d3c-aad1-591b46cb9e6e.png">

**Comment by jerekshoe** [comment]
@skylerschain What do you think about this?
The only difference from a visual standpoint is that the icon is not positioned as far to the right
<img width="514" alt="Screenshot 2023-03-27 at 2 47 52 PM" src="https://user-images.githubusercontent.com/13838621/228051402-53c4fccf-c5c4-4b6f-bbed-88ccd9a708b4.png">

**Comment by jerekshoe** [comment]
This is what it would look like if it was lined up in the same place as the icon is currently
<img width="508" alt="Screenshot 2023-03-27 at 2 54 09 PM" src="https://user-images.githubusercontent.com/13838621/228051798-754b501b-d49f-428d-a578-a7644d41ab3d.png">
