### ISSUE TITLE
Load test new debounce interval and archival of institutions data table for performance of GIBCT service

### ISSUE THREAD

**Issue by mattpointzxer0** [department-of-veterans-affairs/va.gov-team#558]
*BAH Write-Up from @shawkey-daniel (07/11/2019):*

I have a writeup of the issue we want load tested for the autocomplete functionality. TLDR, we need to test different configuration values under load to find the optimal value. Please let me know, if you have questions or need more details.

The GI Bill Comparison Tool provides an autocomplete capability on the text box for the city, school or employer name. The autocomplete capability sends the characters typed in the text box to the server, where a query is performed to provide the first six results starting with the typed character string. Each typed character could cause a server request with a corresponding search result return. To limit the number of requests to the server, a debounce function is employed to only send a request when the user pauses typing for the configured amount of time.

A few weeks back, the autocomplete function was getting high usage by a particular user. This high usage caused a cascade of timeouts on the server which resulted in a temporary denial of service across the VA.gov site. Several steps were initiated to attempt to mitigate this issue from reoccurring. The platform team implemented some configuration changes to address timeouts on the server. The BAH team worked on two initiatives to address the issue. The first is to make the debounce interval configurable and increase the value from 150 ms to 333 ms. This allows the user more time to type before causing another server request.

The second initiative from the BAH team is to move historical version information out of the institutions table and into an archive table leaving only the current production version in the institutions table. This should reduce the data in the table and allow it to be much more performant.

On Monday July 8th, the system again experienced a very high usage of the autocomplete. This caused the server cpu to max out at 100% utilization. This is with the server changes and the first BAH change. Obviously, these changes have not completely mitigated the issue.

The BAH team is recommending the implementation of the second initiative and subsequent testing of the mitigations in a load testing scenario. Under a load test, the debounce interval could be changed to attempt to find the optimum value to mitigate server timeouts and high utilization. This will also help validate if the second initiative helps mitigate the performance issue. Without the load test, any changes to the debounce interval are just educated guesses that will only be tested under load in production where it is difficult to react.

*Additional Background:*
- Incident Postmortem: https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Postmortems/2019-06-10-GI-Latency.md
- Associated Tickets:
  - https://github.com/department-of-veterans-affairs/va.gov-team/issues/241
  - https://github.com/department-of-veterans-affairs/va.gov-team/issues/242

**Comment by mattpointzxer0** [comment]
#THEDANS to monitor the situation after the Institutions table is archived to see if that mitigates the issue. If so, the second suggested fix (tuning the debounce) will be closed as redundant.

**Comment by desireeturner** [comment]
This issue hasn't risen again. Closing this out.
