### ISSUE TITLE
Contact Center Review for VA Flagship Mobile App - v2.0

### ISSUE THREAD

**Issue by kellylein** [department-of-veterans-affairs/va.gov-team#55806]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
The VA Flagship Mobile App is releasing a v2.0 of the app that includes some IA changes and subtle updates to how screens are navigated.

### Launch Date
April 11th, 2023

### Version Number
Product Guide v7.0

### Product Guide
Product Guide .doc file on GitHub: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/releases/Call%20Center%20Docs/In%20use%20version/VA%20Mobile%20App%20Product%20Guide%207.0.docx

### Product Video
*Please provide product video link*

### Product Video Transcript
*Please provide product video transcript link*

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
Hi @kellylein. I apologize for being unable to reply to your inquiry before. I am currently working on the guide, and I have a question: Around page 26, there is a table listing prescription statuses and their associated definitions. In the first row, "Active," the text may be contradictory. It reads, "Active: Prescription may be available to be refilled (can be refillable or non-refillable)." The text within the parenthesis is what's confusing. Can you please advise?

**Comment by kellylein** [comment]
@MekoHong Can you provide Steven with some more detail on the Rx status?

**Comment by starlow00** [comment]
Thank you for the feedback, @kellylein and @MekoHong. The guide looks good. Sending to VEO for review.

**Comment by starlow00** [comment]
No changes from VEO. Current version attached. Informed additional changes coming soon, will adjust when the time comes.
[VA Mobile App v7_srt.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/11327340/VA.Mobile.App.v7_srt.docx)
