### ISSUE TITLE
Adding Rob Monroe to additional channel in DSVA Slack

### ISSUE THREAD

**Issue by SarahJaine** [department-of-veterans-affairs/va.gov-team#55814]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

The user Rob Monroe exists in DSVA slack with email rmonroe@rise8.us. I was hoping to get him access to the [#slack-workspace-admin](https://dsva.slack.com/archives/C01S729LX6X) channel so he can "validate the need to offer cross-workspace enhancements in the future, and investigate what is required to make that work". I believe he is currently a single channel guest on #[lighthouse-delivery-platform-support](https://dsva.slack.com/archives/C03UA9MV1EH).

Are you requesting to add an individual as a:

- Full member
- Single guest
- Multi-channel
- Switching from single-channel to multi-channel?
- What channel(s) do they need to be added to?

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add [_insert email_] as a single-channel guest to [_channel name_].
- Please add [_insert email_] as a multi-channel guest to these channels: [_channel names_].
- Please add [_insert email_] as a full member.
- Please change the status of [_slack username_] from [_current status_] to [_desired status_]

**Comment by rmonroe-va** [comment]
@LEHigley how can I help with this request? I currently work out of the VA lighthouse workspace on slack and my user account there leverages my rise 8 email rmonroe@rise8.us

**Comment by rmonroe-va** [comment]
I also need help connecting with the admin group that manages the DSVA slack workspace. I would like to meet and see if it is possible to support a service account on DSVA like we do over in the Lighthouse workspace to help with automated pipeline feedback to app dev teams.
