### ISSUE TITLE
QA Standards - VAOS - VA Online Scheduling

### ISSUE THREAD

**Issue by it-harrison** [department-of-veterans-affairs/va.gov-team#55823]
#### VFS team name
VAOS
#### VFS product name
VA Online Scheduling
#### VFS feature name
Appointment List
#### Point of Contact/Reviewers
@it-harrison Ian Harrison QA Specialist

---
#### Regression Test Plan 
- [x] Standard has been met
- [ ] Standard has not been met
#### Test Plan
- [x] Standard has been met
- [ ] Standard has not been met
#### Traceability Reports 
- [ ] Standard has been met
- [x] Standard has not been met
##### Explanation of failure to meet standard (if applicable): #####
Summary (Defects) report is an empty table (I assume not yet complete); Coverage for references link points to FrontEnd Dashboard Support page.
#### E2E Test Participation
- [x] Standard has been met
- [ ] Standard has not been met
#### Unit Test Coverage 
- [x] Standard has been met
- [ ] Standard has not been met
##### Explanation of failure to meet standard (if applicable): #####
---
### VFS Guidance

- Close the ticket when your Product Owner determines that you have sufficiently met the QA Standards.
- If your team has additional questions or needs Platform help validating the issue, please comment on the ticket

### Platform directions
- Update "Issue Title" to be of the form "QA Standards - VFS Team - VFS Product"
- Add the VFS team, product name, and feature name
- Add your name, practice area, and GH handle under Point of Contact/Reviewers
- Complete the QA Standards section, making sure to include an "Explanation of failure to meet standard" for every Standard the product does not meet.
- Link to the Collaboration Cycle Request epic
- Add assignees: 
  - VFS PM
  - Yourself (optional)
- Add labels:
  - VFS team label
  - VFS product label
  - QA-standards label
  - launch-blocking label if the product has failed to meet a required QA Standard

**Comment by ldelacosta** [comment]
Added the [traceability report ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/initiatives/appointment-list/appointment-list-traceability-report-qa.md#traceability-report---appoinment-list-redesign)to the [collab ticket #55823](https://app.zenhub.com/workspaces/vaos-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/55823). Closing out the ticket.
