### ISSUE TITLE
Design Intent - Design Feedback - Forms Team, Form 21-10210 Lay/Witness Statement

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#55828]
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- Love the flow chart and mobile views! I think your proposal of contact information chapters is great, just make sure the pages make it into some sort of testing. Work with the content team to keep the [form labels](https://design.va.gov/content-style-guide/form-labels) updated if any change.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- Must: On “Your contact information” move the Edit button under the content and add the “note”. See the [Know how their information is updated pattern](https://design.va.gov/patterns/help-users-to/know-how-their-information-is-updated#communicate-information-that-can-be-edited).
- Must: Use [memorable date](https://design.va.gov/components/form/memorable-date) for DOB
- Must: Use the [sub task](https://design.va.gov/patterns/help-users-to/complete-a-sub-task) (one thing per page) instead of the wizard.

**Comment by tbaker1026** [comment]
Not implementing Memorable Date and pre-fill patter because it is not in the forms library yet
