### ISSUE TITLE
Migrate Form Label masterlist into design system

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#5583]
Form label masterlist currently lives in a Github Markdown file. We want to move this resource into design system. Placement within design system TBD.

Form Label masterlist: 
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/content/VA.gov-form-labels.md

## Acceptance criteria
- [x]  Peggy to write a high-level Forms label landing page that will go into Content section of design system (left nav btw. "error messages" and "government forms" this landing page will include a summary of the form label masterlist and a link to the link.
- [x]  Peggy to recommend where in design system the Form label masterlist will live (possibly under Patterns where the other Form guidance lives? )
- [x] Peggy to work with Content/IA dev @billfienberg  to import Forms label  masterlist into design system. 
- [x]  Form labels are checked/validated in design system @peggygannon

**Comment by peggygannon** [comment]
+ @billfienberg and @meganhkelley I will move this into Sprint 20

**Comment by peggygannon** [comment]
@jenniferlee-dsva @RLHecht 

Hello, here is a high-level content page I'd like to include in the https://design.va.gov/content-style-guide/  and then we'll like off this page to take users to the masterlist (much like we did for the error message dictionary and stylguide). 

Can you give it a quick review and let me know if have any feedback before we move this into design system? 

cc @billfienberg 

**Form label masterlist**

The Form label masterlist documents all form labels and questions that appear on VA.gov online forms. 

When moving a paper form or legacy form online to VA.gov, content writers and UX designers should consult this resource to see if a standardized form label has already been created. These standardized labels should be used when building the form rather than teams create new ones with each form. 

This document will continually be updated as more forms are brought online and new fields and/or questions are documented.  

See the [Form label masterlist](https://design.va.gov/patterns/) for a detailed list of VA.gov form labels and questions.

**Comment by RLHecht** [comment]
@peggygannon My one fix on the wording is for this sentence (in bold):

These standardized labels should be used when building the form rather than teams **creating** new ones with each form.

**Comment by jenniferlee-dsva** [comment]
I'm off VA network, so going to try to upload Word with tracked edits. @peggygannon and @RLHecht [https://app.zenhub.com/files/133843125/e456f399-5b37-4658-8a30-e3c25d6712c2/download](https://app.zenhub.com/files/133843125/e456f399-5b37-4658-8a30-e3c25d6712c2/download)

In the content style guide, I propose we call this section "Form labels" since we're not including the masterlist itself here. 

Lmk if the file upload did not work.

**Comment by peggygannon** [comment]
Thank you both for your feedback. 

@RLHecht are you able to add this Form label summary page to the content style guide? Jen and I had discussed that on the left nav it would go between: "error messages" and "government forms" Final copy is below: 

I'll work with @billfienberg to get the actual masterlist into the design section. 


**Form labels**
When adapting a paper form into an online application or tool on VA.gov, content writers and UX designers should consult the [Form label masterlist](https://design.va.gov/patterns/form-labels) to see if a standardized label has already been created. Use the existing standardized labels when building a form rather than create new or custom labels with each new form. 
The masterlist documents all form labels and form questions that appear on our online forms. This list is continually updated as more forms are brought online and new field labels and form questions are documented. 
See the [form label masterlist](https://design.va.gov/patterns/form-labels) for a detailed list of VA.gov standardized form labels and questions. Because form fields have a lot of visual design and formatting that can affect copy, this masterlist also included in the design section.

**Comment by peggygannon** [comment]
@billfienberg Hello, here is the URL/placement I'm recommending for the form labels. 

Here is the repo that houses design system: 
https://github.com/department-of-veterans-affairs/vets-design-system-documentation

The Form labels would be placed in the Patterns section of design system.

Form labels URL:
https://design.va.gov/patterns/form-labels

**Comment by RLHecht** [comment]
@peggygannon I added this to the style guide and set up a PR for you to review and merge.
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/179

**Comment by peggygannon** [comment]
Thanks, @randi. I've approved your PR, but please wait to merge it until I have an ETA from bill on when the form label table will be migrated over.

**Comment by peggygannon** [comment]
@RLHecht I wanted to let you know that you can merge in your PR. Bill is migrating the Forms masterlist into design system today.

**Comment by RLHecht** [comment]
Just merged it! Should be live tomorrow afternoon.

**Comment by peggygannon** [comment]
OK, thank you. I will take a look tomorrow and validate that all looks good. 

Thank you @RLHecht and @billfienberg for your help!

**Comment by peggygannon** [comment]
Closing. this has been reviewed/validated in design system.
