### ISSUE TITLE
AWS access for Evan Ubiera

### ISSUE THREAD

**Issue by eubiera** [department-of-veterans-affairs/va.gov-team#55897]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Evan Ubiera

### Your Email

evan.ubiera@va.gov

### Team, Role, and Company of the target individual

Developer

### Product Manager (PM) name and email

Alina Murphy, alina.murphy@va.gov

### Product Owner (PO) name and email

Luciana Morais, luciana.morais@va.gov

### Desired AWS Access

I need access to S3 in order to push assets onto dev, staging and production servers. 

### Access Expiration

03/28/05

### E-QIP Transmittal Confirmation

![Screen Shot 2023-03-28 at 2 10 54 PM](https://user-images.githubusercontent.com/117054459/228329916-2b5fca88-b54e-47b0-b820-df662c3b0582.png)

### Additional Notes

Currently, we have a prototype to show and are using a Review Instance, however, we noticed that we need to have these images in S3 in order for them to be visible to stakeholders. 

### User must exist in a roster before AWS access can be granted

- [X] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [X] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by little-oddball** [comment]
VFS Roster

**Comment by eubiera** [comment]
Hi @little-oddball et al

We would like to know the status of this access request, as we'd like to move forward with our prototype design. 
Let us know what you might need from us, if anything.

Thanks!

**Comment by little-oddball** [comment]
@eubiera - This requires approval from OCTODE. When they approve, the awaiting approval label will be removed and then the Tech Support Team will be able to proceed with that request.

**Comment by ianpsant** [comment]
@little-oddball Can you tell us who typically / what team on OCTO-DE we can follow up with to get their approval to move this along?

**Comment by little-oddball** [comment]
> @little-oddball Can you tell us who typically / what team on OCTO-DE we can follow up with to get their approval to move this along?

@BillChapmanUSDS

**Comment by BillChapmanUSDS** [comment]
Hello,  I approve this access for staging and dev on an ongoing basis.  We do not give ongoing access to production.  I will approve production access for 3 months.   

I would like to better understand why production access is required, we should not as a rule be interfacing with production servers manually and expect an appropriate automation.

**Comment by considerable** [comment]
Initial password provided, closing the tkt.

**Comment by eubiera** [comment]
Hi @considerable ! Was this initial password sent to my VA email? Where do I look? 

Thanks!
Evan
