### ISSUE TITLE
Meet with login.gov about help desk support

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#55899]
An assertion was made that login.gov support tells them to just go create an idme account. Can we meet with login.gov to get to the bottom of this topic and perhaps get them to update it

**Comment by parkerbees** [comment]
This has been sitting in "current sprint" for a year. Moving to backlog.

**Comment by parkerbees** [comment]
Closing since this is over a year old. If still relevant it can be pulled from Zenhub archive in future.
