### ISSUE TITLE
Configure ArgoCD to Create a Route That Enables Access to Content-Build in PE FE Containers

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#55900]
# Description
At the moment, the route that is dynamically created for each preview environment only allows users to see `vets-website` running on port 3001. Let's figure out a way to get browsers routed to static content in the frontend container.
![image.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/ba276c10-2abf-4c59-a1a3-25bdc81b9d81)

# Acceptance Criteria
- [ ] Users navigating to a dynamically assigned URL for a preview environment can see both vets-website and content-build resources

**Comment by JoeTice** [comment]
OBE - a different approach made this uneccessary
