### ISSUE TITLE
Log in to VA.gov from stateside IP address and foreign countries in the same day

### ISSUE THREAD

**Issue by mjconw3** [department-of-veterans-affairs/va.gov-team#55959]
## Description

FWA has asked for data on and/or the capability to gather data as it pertains to logging in from stateside IP address and foreign countries in the same day. Does this already exist? If not, we need to investigate developing this capability.

### Notes
Data starting on March 1, 2023 to current:

## Acceptance Criteria

- [ ]

**Comment by bramleyjl** [comment]
I will be traveling abroad from Denver, CO through Newark, NJ to Lisbon, Portugal on April 20 (arriving in Lisbon the morning of April 21). I plan to log into staging.va.gov on a variety of test users within a 24-hour period on both ends of my travel.

Which test user(s) would be useful for this endeavor? I will also be unable to actually look up the logs for several weeks after, so it's probably best to have another engineer be waiting to capture them and add them to this ticket.

**Comment by bramleyjl** [comment]
Selected user is `vets.gov.user+140@gmail.com`, User uuid is `5bea5c933830438080c5558c0a979a8c`  & Account uuid is `51f16272-4b94-48d0-8a26-c4151e4aca0d` to look up logs in DD with.

**Comment by bramleyjl** [comment]
Unfortunately my travel was disrupted by over a day and in the confusion I neglected to make the US login immediately prior to boarding my flight - as a result the [initial US login](https://vagov.ddog-gov.com/logs?query=5bea5c933830438080c5558c0a979a8c%20&cols=host%2Cservice&event=AgAAAYebaxrTjj2f2AAAAAAAAAAYAAAAAEFZZWJheDRHQUFCYmlKcTdydC1kYWdBSQAAACQAAAAAMDE4NzliNmMtMjRlYS00NzAwLWJmZGItNTZkMjUzZDM1MTAz&index=%2A&messageDisplay=inline&storage=online_archives&stream_sort=desc&viz=stream&from_ts=1681711200000&to_ts=1682402340000&live=false) occurred late on 4/19 and the [European login](https://vagov.ddog-gov.com/logs?query=5bea5c933830438080c5558c0a979a8c%20&cols=host%2Cservice&event=AgAAAYeoaAu19Qif0wAAAAAAAAAYAAAAAEFZZW9hQnRzQUFESXMtRmhnUU85QlFBRAAAACQAAAAAMDE4N2E4ODEtYTNlOC00NzU0LTlkZGMtNjBkYTM0NTA2OTRm&index=%2A&messageDisplay=inline&storage=online_archives&stream_sort=desc&viz=stream&from_ts=1681711200000&to_ts=1682402340000&live=false) did not occur until over two days later.

Both logins appear normal, and the European one did include proper geolocating matching my location to Switzerland. Regardless, I'll attempt to use this data to create a dashboard that compares authentication times across a variable time frame.

**Comment by bramleyjl** [comment]
New widget created to list users that have logs from multiple distinct country codes within the given search period: https://vagov.ddog-gov.com/dashboard/r29-65b-qx7/fwa-board?index=*&from_ts=1684089610444&to_ts=1684262410444&live=false&tile_focus=4022148987930222
