### ISSUE TITLE
Define LOE for Troubleshooting Header Injection on OPRM 

### ISSUE THREAD

**Issue by KevinMHoffmanUSDS** [department-of-veterans-affairs/va.gov-team#5595]
## User Story or Problem Statement
As a user of header/footer injection on oprm.va.gov, I need the header to render properly in IE on VA provided GFE. Currently, it renders incorrectly. 

## Goal
The outcome of this issue is to measure the level of effort (LOE) to trouble
shoot, not to actually troubleshoot. 

## Objectives or Key Results this is meant to further
Header/footer injection for sites outside of VA.gov that are planned for migration to VA.gov. 

## Acceptance Criteria
- [ ] LOE estimate for time associated with troubleshooting the rendering problem.

**Comment by KevinMHoffmanUSDS** [comment]
Hey there! @rianfowler I don't seem to be able to upload files at the moment, but I can DM you a screenshot. Given your background with this, I'm wondering if you could just comment on this issue with an estimated LOE, based on that screenshot. Thanks in advance.

**Comment by KevinMHoffmanUSDS** [comment]
Per @rianfowler in Slack, it would take approximately 4 hours to troubleshoot and approximately 8 hours to build. Platform is not responsible for building this, however, as per the agreement in the original ticket: 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/658

@KevinMHoffmanUSDS will append browser and OS version information to this ticket.

**Comment by KevinMHoffmanUSDS** [comment]
@rianfowler Does this illuminate anything? 

Internet Explorer 11
Operating systemWindows NT 10.0
IP address—
help_outline
Javascript enabled Yes
Cookies enabled Yes
Flash version 32.0.0
Java version 1.8.0_231
Websockets supported Yes
WebGL supported Yes
Language en-US
Browser size 1452 x 454
Screen size 1536 x 864 (Retina)
Color depth 24 bit
AdBlock enabled No

**Comment by rianfowler** [comment]
@KevinMHoffmanUSDS it provides enough information to start troubleshooting.

**Comment by KevinMHoffmanUSDS** [comment]
Alright, cool! Thanks, @rianfowler.
