### ISSUE TITLE
Gather data on direct deposit change activity in VA.gov

### ISSUE THREAD

**Issue by mjconw3** [department-of-veterans-affairs/va.gov-team#55958]
## Description

Per FWA direction, we need to collect the data starting on March 1, 2023 to current regarding Log in to VA.gov with direct deposit change activity within VA.gov and shared with the FWA team.

### Tech Note
- Jamaica IP Addresses Country IP Range State/Region City Jamaica 65.183.0.0 - 65.183.2.255

## Acceptance Criteria

- [ ] Obtain appropriate data and metrics from datadog
- [ ] Document data 
- [ ] Share data with FWA team

**Comment by mjconw3** [comment]
@charlye-bluetiger and @joeniquette are syncing to see who has this access already

**Comment by bramleyjl** [comment]
This information can be found in the [Datadog FWA Dashboard](https://vagov.ddog-gov.com/dashboard/r29-65b-qx7/fwa-board?refresh_mode=sliding&from_ts=1700072699915&to_ts=1700159099915&live=true).
