### ISSUE TITLE
SPIKE: A login.gov like configuration dashboard

### ISSUE THREAD

**Issue by mjconw3** [department-of-veterans-affairs/va.gov-team#55967]
## Description

We want to create a login.gov like configuration dashboard for our SiS tooling that allows external teams to come in and understand SiS and integrating it seamlessly into their application. We need to investigate what this dashboard will look like, what the content will consist of and where it will live.

### Tech Notes
-Lets put link to login.gov dashboard for reference

## Acceptance Criteria

- [ ]

**Comment by bosawt** [comment]
Closing as this is effectively the same as: https://app.zenhub.com/workspaces/identity-5f5bab705a94c9001ba33734/issues/gh/department-of-veterans-affairs/va.gov-team/55971
