### ISSUE TITLE
SPIKE: developer page with documentation

### ISSUE THREAD

**Issue by mjconw3** [department-of-veterans-affairs/va.gov-team#55969]
## Description

We want to create a developer page for our SiS tooling that allows external teams to come in and understand SiS and integrating it seamlessly into their application. We need to investigate what this page will look like, what the content will consist of and where it will live.

### Tech Notes
-Link to the Login.gov developer guide: https://developers.login.gov

## Acceptance Criteria

- [ ]

**Comment by bosawt** [comment]
We have much of this information in various Github markdown files. Here are a couple of deliverables I'd like to see out of this spike:
- Is there any information in the login.gov developer guide that would be useful for Sign in Service, and which we don't currently have documentation for?
- Can we get a list of relevant developer Sign in Service documentation? (Links would be useful)
- What style should we follow? Should we just copy the structure of the login.gov documentation? Is there a better way?

**Comment by asg5704** [comment]
- Are there things that are already in place that we can use to generate this developer page?
  - Example: https://depo-platform-documentation.scrollhelp.site/developer-docs/
- Do we need our own repository to host stuff?
- Should we use a Wiki page that's included with Github? Pros/cons of it?

**Comment by mjconw3** [comment]
@kingbmike lets follow up on the things we chatted about in terms of lighthouse-api and consistency

**Comment by asg5704** [comment]
Developer documentation (https://www.notion.so/Identity-Documentation-8ec5a98a8a8f4475979ba93660322a57?pvs=4)
