### ISSUE TITLE
CANCELED**[SiS] Sign In Service Developer Portal

### ISSUE THREAD

**Issue by mjconw3** [department-of-veterans-affairs/va.gov-team#55965]
## Description

As a part of our SiS tooling, integration, and marketing, we want to create a developer portal. We believe that this can be used as a major selling point for SiS and help with buy in and ease of external app integration.

### Some of the key features we need to investigate include:

- A login.gov like configuration dashboard
- A developer page with documentation
- A client config page as a part of the developer page (or external)
- Creation of a Portal that includes all relevant SiS content

**Comment by aparsley** [comment]
As a part of our Sign in Service (SiS) tooling, integration, and marketing, we want to create a developer portal. We believe that this can be used as a major selling point for SiS that will help with buy in and ease of external app integration.

Some of the Key Features include:
A Login.gov type of configuration dashboard
A developer page with documentation
A client config page as a part of the developer page (or external)
Creation of a Portal that includes all relevant SiS content
