### ISSUE TITLE
Supplemental Claims | Code cleanup

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#55978]
## Issue Description

Supplemental Claims needs some basic code clean up and replacement of deprecated React components.

## Front end tasks
- Remove unused code
- Look for and add missing unit tests
- Replace deprecated React components, e.g. [ProgressButton](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1356)

## Acceptance Criteria
- [ ] Unused code was removed
- [ ] Replace deprecated React components
- [ ] Update unit tests
- [ ] Add missing unit tests
- [ ] Unit tests pass

**Comment by saderagsdale** [comment]
@Mottie Is this still in progress?
