### ISSUE TITLE
Feedback Site for Verification Process

### ISSUE THREAD

**Issue by mjconw3** [department-of-veterans-affairs/va.gov-team#55973]
## Description

One of the solutions we want to investigate for in person proofing is the creation of a feedback site for the verification process. We want a tool that allows users to provide feedback for current authentication processes in place that allows us to better our workflow and product.

**Comment by aparsley** [comment]
We want to investigate a solution for In Person Proofing (IPP) which is, the creation of a feedback site for the verification process. We want a tool that allows users to provide feedback for current (authentication processes in place), that allows us to streamline our workflow and product.

**Comment by aparsley** [comment]
Now called Verification Support.
