### ISSUE TITLE
Create GIDS endpoint to expose Yellow Ribbon programs

### ISSUE THREAD

**Issue by kelsonic** [department-of-veterans-affairs/va.gov-team#5597]
## Description

The [current Yellow Ribbon MVP spec](https://vsateams.invisionapp.com/share/X5VOMBG2YP4#/screens/402038362) requires 4 key-value pairs that are not currently found within [the GIDS endpoint](https://dev.va.gov/gids/v0/institutions). Those key-value pairs are `degree_level`, `division_professional_school`, `number_of_students`, and `contribution_amount`. The reason for this is that the endpoint is surfacing `Institution` models, not necessarily `YellowRibbonProgram` models.

As a result, and after discussion with the BAH team, we've decided to create a new endpoint (`https://va.gov/gids/v0/yellow-ribbon-programs`).

The response from this endpoint **must include** an array of objects that have _at least_ the following key-value pairs:

```
city
contribution_amount
degree_level
division_professional_school
facility_code
number_of_students
school_name_in_yr_database
state
street_address
zip
```

## Useful tips

As suggested by @zurbergram, this new endpoint could follow many of the same patterns as `/v0/institution_programs`. Probably a good idea to check out https://github.com/department-of-veterans-affairs/gibct-data-service/blob/master/app/controllers/v0/institution_programs_controller.rb.

Since we need to add new fields to the Yellow Ribbon model, info on how the current process of Yellow Ribbon data works may be useful:

> The way yellow ribbon data is uploaded and processed in GIDs is:
> The fields in a yellow_ribbon_program_source.csv are mapped into yellow_ribbon_program_source table using the CSV_CONVERTER_INFO object in https://github.com/department-of-veterans-affairs/gibct-data-service/blob/master/app/models/yellow_ribbon_program_source.rb
> The fields in the yellow_ribbon_program table are set from values in institutions and yellow_ribbon_program_source  at https://github.com/department-of-veterans-affairs/gibct-data-service/blob/master/app/models/institution_builder.rb#L448
> The institution profile objects that are returned by https://dev.va.gov/gids/v0/institutions are created at https://github.com/department-of-veterans-affairs/gibct-data-service/blob/master/app/serializers/institution_serializer.rb

## Note
- Data isn't available fro certain keys e.g. availableOnline or onlineOnly. We can make sure the endpoint surfaces this data, but it's not consumed by the front-end.

## Acceptance Criteria
- [ ] Create `GET https://va.gov/gids/v0/yellow-ribbon-programs` that returns a 200 response in the shape we expect. 
  - [ ] For now, `name` is the only available filter but it'll still return all results in the expected structure
- [ ] Write test specs for the new endpoint.

**Comment by kelsonic** [comment]
CC @ncksllvn

**Comment by MickinSahni** [comment]
2020-02-12 PW Sprint Planning
- The general plan is to 1) update the gids api with all changes we need then 2) update vets-api (#5599). Ideally, 2) will happen last so we make all of the changes at the same time.

**Comment by MickinSahni** [comment]
2020-02-19 PW Standup
- Endpoint is working -- need final updates + tests
- Currently only supports `name` filter. (Separate ticket for additional filters - #5604  
- Note: BAH is gonna be included on the PR review

**Comment by MickinSahni** [comment]
2020-02-20 PW standup
- shooting for a PR by eod Friday (ahead of close of sprint tuesday)

**Comment by AkucherGCIO** [comment]
02-24-20 PW Standup:
PR was sent friday and the approach needs to be different (Matt Roth) Yellow ribbon program needs to be used.  We will merge the current PR for now. 

Downsides for Yellow Ribbon Program 
-it won't have historical data but it's not needed 
-No linking between institution and YRP

**Comment by AkucherGCIO** [comment]
2020-26-02
PR hasn't been merged yet and therefore still in Progress.
Kelson will reach out BAH team to get the PR merged.
