### ISSUE TITLE
SPIKE: SiS client configuration page

### ISSUE THREAD

**Issue by mjconw3** [department-of-veterans-affairs/va.gov-team#55971]
## Description

We want to create a client config page for our SiS tooling that allows external teams to come in and understand SiS and integrating it seamlessly into their application. We need to investigate what this page will look like, what the content will consist of and where it will live (possibly on the developer page).

### Tech Notes

- External teams will need to have the ability to login and change settings solely for their own client configuration.
- It should be possible for an authenticated user to have access to multiple client configurations if they have been given proper permission
- We should investigate if we should create further roles (such as read/write access) for an entity using this functionality
- Prod changes should NOT flow automatically. They should notify someone on the Identity team and either flow after some buffer period, or require manual intervention to change
- Test stack changes should flow automatically. This should immediately be reflected in the test stack where the change occurred

The login.gov integration dashboard is a good model to take inspiration from:
![image.png](https://images.zenhubusercontent.com/5fb55f12a11eae1f7ca15bde/82df73bf-85db-4f2f-bd13-5b12fce6a7a0)
![image.png](https://images.zenhubusercontent.com/5fb55f12a11eae1f7ca15bde/15032ece-4efa-4f92-a4b5-20d1b81bfb75)
![image.png](https://images.zenhubusercontent.com/5fb55f12a11eae1f7ca15bde/65bc9061-d425-40b8-b8c7-db72a9f0907b)

## Decisions:

- Authentication for this dashboard will leverage both login.gov an id.me credentials
- We will not leverage github teams because we cannot rely on people being part of our github org in order to access this dashboard

## Ideas:
- Login.gov has some concept of roles based on how their dashboard works now for modifying configs in lowers, since they are all open source perhaps we can use this as an example

## Acceptance Criteria

- [ ]

**Comment by bosawt** [comment]
### Investigation of Login.gov Implementation
* Frontend is defined in a ‘login.gov’ dashboard repo: [GitHub - 18F/identity-dashboard: Identity developer dashboard](https://github.com/18F/identity-dashboard)
	* Interestingly this is done in Rails, with a series of Rails views
	* When you make edits, it sends updates to `teams_controller` and `service_providers_controller`
	* It looks like there are efforts to keep models like `ServiceProvider` equivalent in this dashboard repo, and in the main login.gov repo
	* It seems like when you make updates in the dashboard repo, it then updates the main login.gov system
* Dashboard has the following relevant models:
	* `Agencies` 
		* This is overall agency, like `Department of Veterans Affairs`
		* This has a `name` field only
	* `groups (teams)`
		* This has a `name`, `description`, and `agency_id`
		* Associated with `agencies`
	* `Users`
		* Pulled from login.gov credential information for the developer signing in
		* `email`, `first_name`, `last_name`
		* `admin` boolean
		* `group_id` to associate to `groups (teams)`
		* Various fields to detect when it was signed in, ip signed in, deleted at, etc
	* `UserGroups`
		* Join table on `User` and `Groups (teams)`
	* `service_providers`
		* This defines the individual integration
		* This has a ton of fields:![D24E0C3D-CE29-4CF6-A39E-6566F9213519.png](https://images.zenhubusercontent.com/5fb55f12a11eae1f7ca15bde/731f802c-cb47-41d9-bf9c-b31911a906db)
		* `security_events`
			* This includes `user_id`, `uuid`, `issued_at`, `event_type`, `raw_event`
			* There is a `SecurityEventController` that can be called to form these

**Comment by bosawt** [comment]
## Analysis
* How do we want to accomplish a similar way of setting up integrations?
	* I think we can from a high level, copy the Login.gov implementation here
		* Concepts like synchronizing with the ‘core’ backend can be leveraged from the login.gov dashboard repo
	* We’ll want `Agencies`, `Teams`, `Users`, and `Roles` to describe users and their relationships with agencies/teams
	* We’ll want `ClientConfigurations` (or maybe a better name) to come up with the configurations a client will set up
	* We might just want to copy the views here and use Rails `erb` for the frontend component. This is negotiable though

**Comment by bosawt** [comment]
Next steps required:
- Confirm backend and frontend implementation
  - Recommended backend in Rails, that leverages much from the login.gov dashboard
  - Recommended frontend in Rails ERB, that leverages much from the login.gov dashboard
- Create schema diagram to describe database associations for users, roles, and client_configurations
- Create diagram for communication flows between SiS-Dashboard and SiS
- Storyboard the views in this implementation

**Comment by bosawt** [comment]
@asg5704 Do you mind looking through the views in: https://github.com/18F/identity-dashboard , and can you comment on whether following a similar pattern would be maintainable? Or would it be preferable to separate the frontend from the Rails component?

**Comment by bosawt** [comment]
@kingbmike @mjconw3 (sorry, I forgot which team is taking this), I think we have actionable tickets out of the 'next steps required' comment I made further up

**Comment by mjconw3** [comment]
@bosawt Looks great! Appreciate all of the detail in here it will make things easier going forward on this. Closing this out.
