### ISSUE TITLE
SPIKE:Video Conferencing Support (For Verification Account Creation)

### ISSUE THREAD

**Issue by mjconw3** [department-of-veterans-affairs/va.gov-team#55986]
## Description

One of the solutions we want to investigate for in person proofing is the creation of video conferencing support for verified account creation. We want a tool that allows users to provide feedback for current authentication processes in place that allows us to better our workflow and product. We need to investigate and create a solution and provide support, for remote/video verification and the account creation process.

### Questions and Concerns

- Can we and how will we make this appointment based
- We dont have app, which is fine, need to make one
- Check with servicenow if they have a video conferencing type help solution? (Check with Kim/Chante)
- Who will be made available to answer calls?
- Dedicated support help desk?
- Scheduling system we can make available to help desk folks, there may be a servicenow integration that already exists for this type of help
- What will the wait times look like
- This solution will need to be around forever
- We should talk to Telehealth about a service we may be available to tap into?
- PMs follow up on contacts

## Acceptance Criteria

- [ ]

**Comment by charlye-bluetiger** [comment]
**Pain Point:** 
As a user who is going through the authentication/verification process, how might I provide feedback?
**Goal:** 
Highlight areas where users are encountering the biggest issues in order to focus building solutions to alleviate these problems
**Logistics:** 
1. Who would monitor this feedback?  
2. What is the process for monitoring the feedback?  Resources/bandwidth
**Considerations**
- an endpoint on va.gov exposed to users through a link
- need a way to ensure we don't get feedback from people who didn't actually attempt
- security wise we need to ensure we don't collect any PII during the process
- provide help desk folks with the ability to contact the users back about their issues or to inform them we solved the problem
- uuid, email, time date
- Can we conduct a “survey” or gather feedback? What is involved here? 
-

**Comment by mjconw3** [comment]
Concern: idme has a trusted referee solution, should we rely on this instead of building our own? What capabilities will the video support offer that is different than what IDme offers?
Some Veterans may not want to use the idme help desk and this service may be important
We should find an estimate as to how many people this may be

**Comment by mjconw3** [comment]
@kingbmike lets try and get some POCs and info together to help on this

**Comment by acaruso-oddball** [comment]
Initial MVP Questions:

**End user has the ability to schedule an appointment with an agent.** 
Will end users get an email confirming their appointment has been set? 
Will wrap-around support, such as missed appointment emails, appointment reminders, verification status updates etc. be sent? (possibly out of scope)
Will there be an option for immediate connection/help from an agent? 
How far out will end users be able to schedule their appointments? 
Will have to consider calendar integrations such as GCal, iCal, Outlook.

**End user can meet with an agent through the use of video conferencing.**  
- Will they need to upload documents prior to meeting? 
- Are we interested in allowing end users to share their screens? 
- Will it make more sense to use microsoft teams or zoom integration?
- Accessibility concerns: would transcripts be made available to the end user?

**We don’t have app, which is fine, need to make one**
- What would the MVP for this app? 
   - The ability to schedule and remind folks of their appointments
   - Zoom integration/ ability to video chat and screen share with veterans
- Immediate response/w help?
- Will this app have recording capabilities? 
- Will this be a greenfield app or integrated with another?

**Are there other options on the market?** 
 _Calendly for Outlook_ 
Not an option. Not approved for use by VA. 

_ServiceNow has Field Service Management Conferencing Integration_
   - Spoke with sales rep from ServiceNow re. this feature and they were able to confirm that it had a GUI for end users to schedule appointments, and will be sending additional documentation. 
     -  Agents can: 
          -  initiate meetings for work order tasks using Zoom and Microsoft Teams
          - Invite customer contacts and peer agents to meetings
          - View conference recordings

- Spoke with Kimberly (Chante has yet to respond) re. ServiceNow’s integration, however they had limited experience with the product and could not provide assistance. 

_ID.me Trusted Referee_
- If users are verifying with ID.me this would be a streamlined solution as no integration would be required.
- Shuts out large percentage of users verifying with Login.Gov
- Robust documentation.

**Comment by acaruso-oddball** [comment]
**Option 1:**
_Build an appointment scheduler that integrates with google cal/microsoft cal and Zoom._

- Users are presented with a calendar of possible appointment options and the option to choose the nearest available appointment. 
- Once a slot is selected, veterans will need to enter relevant information regarding their case:
  - What information should be collected at this point? Where will it need to be sent?
  - They will then be sent a confirmation email, and the option to save time as a calendar event on gcal, ical, or outlook. 
  - Appointment reminders to be sent to veterans 24 hours before the event? 
- ZOOM from there

_Possible Technologies used:_ Twilio API, Node.js, React
_Predicted Time Frame:_ 
_Resources:_ 
- https://kris101.medium.com/building-appointment-scheduler-app-in-react-and-nodejs-d01f7294a9fd
- https://www.youtube.com/watch?v=iNkryf_TtZw
- https://dev.to/novu/creating-a-scheduling-app-i-wish-somebody-showed-me-this-technique-when-i-first-started-coding-2icd

**Comment by acaruso-oddball** [comment]
*Option 2:* 
_Build a chat app that allows veterans to meet with verification helpers  in real time via chat or video support._ 
- Veterans are able to see availability of aid/wait times. 
- Veterans are able to virtually meet with aid.
- Veterans can share their screen and allow tech to control aspects of it. 

_Possible Technologies Used:_ 
_Predicted Time Frame:_
_Resources:_ 
- https://www.twilio.com/blog/build-a-custom-video-chat-app-with-react-and-twilio-programmable-video
- https://www.section.io/engineering-education/video-conferencing-app-with-react-node/
- https://www.daily.co/blog/building-a-custom-video-chat-app-with-react/
- https://www.twilio.com/blog/video-chat-react-hooks

**Comment by acaruso-oddball** [comment]
**Greenfield Option:** 
Build out platform for Veterans to work with Agents.

**Potential Technologies:** 
  - Next.JS  
  - [WebRTC](https://webrtc.org/) 
  - Firebase
  - Cloudinary  
  - Socket.io

**Resources:** 
- [The Beginner's Guide to Understanding WebRTC](https://www.stackfive.io/work/webrtc/the-beginners-guide-to-understanding-webrtc)
- [Peer-to-peer video call with Next.js, Socket.io and Native WebRTC APIs](https://www.stackfive.io/work/webrtc/peer-to-peer-video-call-with-next-js-socket-io-and-native-webrtc-apis)
- [Web RTC Crash Course](https://www.youtube.com/watch?v=QsH8FL0952k)
- [Chat App w/ Next.js & Web RTC Example App](https://github.com/mariocao/next-webrtc)
- [Real Time Communication Web App](https://cloudinary.com/blog/guest_post/real-time-communication-web-app)


App can be built using Next. Additional research required.

**Comment by mjconw3** [comment]
Looks awesome @acaruso-oddball
