### ISSUE TITLE
Add pagination to new GIDS endpoint

### ISSUE THREAD

**Issue by kelsonic** [department-of-veterans-affairs/va.gov-team#5598]
## Description

We need pagination on the [new GIDS endpoint](https://github.com/department-of-veterans-affairs/va.gov-team/issues/5597) so that requests do not take so long to resolve.

**This ticket is BLOCKED by [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/5597).**

## Acceptance Criteria
- [ ] Add pagination to the [new GIDS endpoint](https://github.com/department-of-veterans-affairs/va.gov-team/issues/5597).
- [ ] Write test specs for the new feature on the endpoint.

**Comment by kelsonic** [comment]
CC @ncksllvn

**Comment by MickinSahni** [comment]
2020-02-12 PW Sprint Planning
- We'll groom the acceptance criteria and estimate before pulling into sprint 15 *if we have room*

**Comment by AkucherGCIO** [comment]
02-24-20
Ready for integration to Frontend.

**Comment by AkucherGCIO** [comment]
2020-26-02
PR hasn't been merged yet and therefore still in Progress.
