### ISSUE TITLE
[IPP] Video Conferencing Support (For Verification Account Creation)

### ISSUE THREAD

**Issue by mjconw3** [department-of-veterans-affairs/va.gov-team#55984]
One of the solutions we want to investigate for in person proofing is the creation of video conferencing support for verified account creation. We want a tool that allows users to provide feedback for current authentication processes in place that allows us to better our workflow and product. We need to investigate and create a solution and provide support, for remote/video verification and the account creation process.

**Pain Point:** As a user who is trying to authenticate my account and I cannot proof in person, how might I get assistance to complete the process?
- Goal: Identify what tools may already be available to assist vets and what solutions we may need to develop in order to get more veterans through the authentication/verification process

**Solution Considerations:**

- If there isn’t an application that supports video conferencing/scheduling (for video assistance), we would potentially have to build a solution.
- Check with servicenow if they have a video conferencing type help solution? (Check with Kim/Chante)
- This solution will be around forever
- Telehealth may be available to tap into? (PMs follow up on contacts)
- What solutions already exist?  How can we extend those solutions (technical and process stand-point)?
- Should we make this appointment based (?)

**Logistical Concerns:**

- Who will be made available to answer calls?
- Dedicated support help desk?
- Scheduling system we can make available to help desk folks, there may be a servicenow integration that already exists for this type of help
- What will the wait times look like

**Comment by aparsley** [comment]
We want to create of video conferencing support as a solution for Verified Account creation. We want a tool that allows users to provide feedback for current (authentication processes in place), that allows us to improve our workflow and product. We need to investigate, create a solution, and provide support for remote/video verification and account creation process.

**Comment by aparsley** [comment]
Not in scope, unable to complete this action due to lack of resources, Verification Support Strategy was created out of this issue.
