### ISSUE TITLE
Connect Vets-API to GIDS endpoint for Yellow Ribbon programs

### ISSUE THREAD

**Issue by kelsonic** [department-of-veterans-affairs/va.gov-team#5599]
## Description

`vets-api` and the client can only hit the same GIBCT endpoint once per minute. As a result, we need to create a proxy endpoint for [the new GIDS endpoint](https://github.com/department-of-veterans-affairs/va.gov-team/issues/5597) on `vets-api` that includes caching.

**This ticket is BLOCKED by [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/5598).**

## Acceptance Criteria

- [ ] Create new `vets-api` endpoint that caches [the new GIDS endpoint](https://github.com/department-of-veterans-affairs/va.gov-team/issues/5597).
- [ ] Write test specs for the new `vets-api` endpoint.

**Comment by kelsonic** [comment]
CC @ncksllvn

**Comment by AkucherGCIO** [comment]
03/04/20 PW Standup
Kelson will be working on this today.

**Comment by AkucherGCIO** [comment]
@kelsonic - Are we able to close thi ticket as part of Sprint 16 ?
