### ISSUE TITLE
Adding Carlos Felix to DSVA Slack

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#55993]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

<describe the request>

Are you requesting to add an individual as a:

- Full member
- Single guest
- Multi-channel
- Switching from single-channel to multi-channel?
- What channel(s) do they need to be added to?

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

We aim to complete slack requests within 24hrs.

## Sample Descriptions 

- Please add carlos.felix@agile6.com as a full member. He needs to be a full member so that he can access the various engineering channels, announcements, MHV to VA.gov channels, platform support, etc.  Carlos is joining the team as an architect.  He is with Agile Six, the prime on the CEDAR contract.  Thank you!

**Comment by LEHigley** [comment]
i'm seeing that he is a full member?

**Comment by MarciMcGuire** [comment]
I think someone from Agile 6 entered a request right after I did.  Thank you!
