### ISSUE TITLE
Update flipper UI URLs in documentation to remove 'platform'

### ISSUE THREAD

**Issue by gmrabian** [department-of-veterans-affairs/va.gov-team#56017]
### Description

The [feature toggles guide](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide) links to a [Flipper UI](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/#flipper-ui) document that has URLs for staging and production. These URLs contain the word `platform`, though it seems like they should not.

As noted by these platform requests:
https://dsva.slack.com/archives/CBU0KDSB1/p1680115771111819
https://dsva.slack.com/archives/CBU0KDSB1/p1680099207158339

### Relevant URLs
(linked above as well)
where it directs from (just for reference, no change needed):
https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide

where the typo actually is:
https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/#flipper-ui

### Which type of team are you on? (Platform team, VFS team, or Leadership)
VFS Forms Team

**Comment by vbellissimo** [comment]
Hi @gmrabian,

Thank you for submitting this feedback. This support request outlets comes to the Platform Content team, which does not have control over https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/#flipper-ui nor the URL structures you pointed out on there.

I am going to close this ticket, but my suggestion is that you submit this comment to the general [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) Slack channel so your request is reviewed by the appropriate team.

Thank you.
