### ISSUE TITLE
AWS access for Steven Albers (OCTO Benefits Portofolio)

### ISSUE THREAD

**Issue by va-albers** [department-of-veterans-affairs/va.gov-team#56018]
### COR Name

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative Name

Other - please specify in 'Additional Notes'

### E-QIP Transmittal Date

- [x] Check this box if you have an E-QIP transmittal date.

### Your Name

Steven Albers

### Your Email

steve.albers@va.gov

### Team, Role, and Company of the target individual

Lead Engineer, Benefits Portfolio, OCTO

### Product Manager (PM) name and email

Zach Goldfine, zachary.goldfine@va.gov

### Product Owner (PO) name and email

Matt Self, matthew.self2@va.gov

### Desired AWS Access

Vets-API production access

Particularly I need access to read-only query the production database for research and to assist in issue resolution.  If it is necessary to grant access thru rails console that is acceptable.  Benefits teams I support work with the `vets-api` and `vets-website` repos. 

Access requested should be ongoing as issues that need resolved/debugged occur repeatedly. 

Prior benefits portfolio team members requested access through the following:
```
group_memberships = ["dsva-vagov-developers", "force-MFA"]

"adhoc-vetsgov-ssm-prod"
```

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

![Steve-eqip-screencapture](https://user-images.githubusercontent.com/119101230/228644497-88c6e7a9-254c-417d-9e32-b2bb5adf9389.jpg)

### Additional Notes

I'm the engineering lead for ~6 contracting teams who sometimes need assistance verifying the status of the production database to help resolve issues or verify assumptions about the state of benefits data in the production system.

I do not have a COR, as I'm a federal employee.

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by considerable** [comment]
VFS Roster.

**Comment by considerable** [comment]
initial password provided, closing the tkt.
