### ISSUE TITLE
[FE] 10-10EZ - Short Form: Add conditional to short form flow to check Financial Disclosure and Compensation type

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#56024]
## Background
The Short Form flow was created to shorten the current full 10-10EZ form, allowing Veterans with a disability rating higher than 50% to skip the Household section (including Spouse, Dependents, Income and Deductibles info), directing to the Insurance Information pages.  
A scenario was found to not follow the expected Short Form flow behavior.

**Existing behavior**
- Applicant answers the Compensation question with "No" or "Disability rating less than 40%"
- Applicant fills out the Financial Disclosure pages
- Applicant reviews answers on the Review page
- Applicant selects link to change the compensation answer
- Applicant selects "Disability rating of 50% or higher"
- Applicant is presented with confirmation box to confirm answer
- Applicant is directed through Household information pages (previously answered)
- Applicant reviews answers on Review page, which still shows the Household section information
- Applicant submits application 

**Expected Behavior**
- Applicant answers the Compensation question with "No" or "Disability rating less than 40%"
- Applicant fills out the Financial Disclosure pages
- Applicant reviews answers on the Review page
- Applicant selects link to change the compensation answer
- Applicant selects "Disability rating of 50% or higher"
- Applicant is presented with confirmation box to confirm answer
- Applicant is directed to Medicaid question (Insurance info section)
- Applicant reviews answers on Review page, which now does not show the Household section information
- Applicant submits application 

## Tasks
- [ ] Update conditional to account for the Compensation type/answer
- [ ] Test both long and short form flows when changing the Compensation answer from the Review page

## Acceptance Criteria
- When a Veteran changes their answer for the Compensation question, the 10-10EZ form will update to follow the appropriate flow, depending on the answer (short form or long form)

**Comment by hdjustice** [comment]
Fix live in staging environment
Tested several scenarios with all compensation answers (<=40%, >=50% and No), changing from Review page, as well as going back through pages, changing several times in and out of short form eligibility.  Once the compensation question is answered, the questions that follow are presented **as expected** based on whether the answer indicates a Short form eligibility or Long form requirement.
This code change can be merged to Production.  We will continue to monitor traffic and activity to ensure there are no adverse affects

**Comment by longmd** [comment]
Verified in prod as well.
