### ISSUE TITLE
Adding [Faith Jackson] to DSVA Slack

### ISSUE THREAD

**Issue by cbrizen** [department-of-veterans-affairs/va.gov-team#56020]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

Please add faith.jackson@thoughtworks.com to DSVA slack

Are you requesting to add an individual as a:

- Full member
- What channel(s) do they need to be added to? Long-covid-team

Faith Jackson join the team recently as a Business Analyst and needs to communicate with our stakeholder and other team members

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add [faith.jackson@thoughtworks.com] as a full member.

**Comment by LEHigley** [comment]
showing as an active full member
