### ISSUE TITLE
Add support for sorting to new GIDS endpoint

### ISSUE THREAD

**Issue by kelsonic** [department-of-veterans-affairs/va.gov-team#5602]
## Description

Ideally we want to be able to sort the Yellow Ribbon search results by any key-value pair that's on a Yellow Ribbon program. We also want to sort the results either ascending or descending.

**This ticket is BLOCKED by [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/5597).**

## Acceptance Criteria

- [ ] Add support for `sortBy` and `sortDirection` query params to [the new GIDS endpoint](https://github.com/department-of-veterans-affairs/va.gov-team/issues/5597).
- [ ] Write test specs for the new functionality on the new GIDS endpoint.

**Comment by kelsonic** [comment]
CC @ncksllvn

**Comment by MickinSahni** [comment]
2020-02-12 PW Sprint Planning
- We'll groom the acceptance criteria and estimate before pulling into sprint 15 *if we have room*

**Comment by AkucherGCIO** [comment]
2020-28-02 Standup
Ticket taking a little more time than expected.

**Comment by kelsonic** [comment]
Proposing to close this ticket now that it's being tracked in [this PR](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6267)! 🎉
