### ISSUE TITLE
[DD][EKS] Db-migrate monitor and alert for Prod

### ISSUE THREAD

**Issue by oseasmoran73** [department-of-veterans-affairs/va.gov-team#56034]
## Description

[db-migrate](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/datadog/catalog/vets-api.yaml) alert has already been create for all environments with the exception of Prod

## Task

- [x] Add pagerduty alert for prod
- [x] Inform support

## Acceptance Criteria

- [x] Alerts are going to #oncall and PD

**Comment by laineymajor** [comment]
Putting this ticket in 'final push to prod' as we need to ensure support is aware of this. Then we can move this to 'during prod rollout' work. @oseasmoran73

**Comment by oseasmoran73** [comment]
@laineymajor PR created and has asked COP for review/approval. Once we are ready for rollout, PR just needs to be merged

**Comment by oseasmoran73** [comment]
PR has been merged. Closing ticket
