### ISSUE TITLE
Add support for multiple filters to new GIDS endpoint

### ISSUE THREAD

**Issue by kelsonic** [department-of-veterans-affairs/va.gov-team#5604]
## Description

Ideally we want to be able to filter the Yellow Ribbon search results by any key-value pair that's on a Yellow Ribbon program.

For example, with a query param like `&number_of_students=<500`, we would like to limit the Yellow Ribbon programs that have a `number_of_students` key-value pair that `is greater than 500`.

Another example, with a query param like `&city=boulder`, we would like to limit the Yellow Ribbon programs that has a `city` key-value pair that includes `boulder`.

**This ticket is BLOCKED by [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/5597).**

## Query Params needed

```
city (includes)
country (is equal)
contribution_amount (greater than, less than, equal to)
number_of_students (greater than, less than, equal to)
school_name_in_yr_database (includes)
state (is equal)
```

## Acceptance Criteria

- [ ] Add support for the above query params to filter [the new GIDS endpoint](https://github.com/department-of-veterans-affairs/va.gov-team/issues/5597) results.
- [ ] Write test specs for the new functionality on the new GIDS endpoint.

**Comment by kelsonic** [comment]
CC @ncksllvn

**Comment by MickinSahni** [comment]
2020-02-12 PW Sprint Planning
- We'll groom the acceptance criteria and estimate before pulling into sprint 15 *if we have room*

**Comment by AkucherGCIO** [comment]
03/02/20 PW Standup
- Add Country needs to be added from  Institution to the Yellow ribbon program.
- PR will be submitted today.
