### ISSUE TITLE
Direct Scheduling Clinics returned in call Not Displayed to Veteran

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#56065]
SCENARIO #1:  INTOLA12:  EDGECOMB DIRECT SCHEDULE OPTOMETRY 

**Steps to create**
1.	Set VATS for Optometry for Cheyenne for Direct Schedule =  Yes seen in last 12 mos. Verify veteran has past optometry appt in last 12 mos.  
2.	Log in as  ola.e.edgecombe@id.me has a checked out clinic in appointment in Optometry appointment in Cheyenne  within the last 365 days (12/01/2022).  
3.	Select Eye, Select Optometry and select Cheyenne.  
4.	Expected Results:  Veteran is able to direct schedule.  And clinic listing below displays.  Dev tools shows clinics returned in this call:  https://staging-api.va.gov/vaos/v2/locations/983/clinics?clinical_service=optometry

Choose a clinic below or request a different clinic for this appointment.(*Required)

CHY OPT VAR1
Friendly Name Optometry
VISUAL FIELD
I need a different clinic
5.	Actual Results:  System displays:    We couldn’t find a clinic for this type of care.  We're sorry. This facility doesn’t have any available clinics that support online scheduling for the type of care you selected. Please call this facility to schedule your appointment or search for another facility.  Dev tools shows clinics returned in this call:  https://staging-api.va.gov/vaos/v2/locations/983/clinics?clinical_service=optometry

![image.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/71e4fa00-d2bc-43e4-8e57-5f100b315311)

VISTA PATIENT APPOINTMENT HISTORY AND CLINIC IENS
Appt Mgt Module               Mar 30, 2023@10:25:36          Page:    1 of    1 
Patient: EDGECOMBE,OLA ELAIJAH KEKIA (3860)   MT: COPAY EX            Outpatient
Total Appointment Profile        * - New GAF Required     03/30/22 thru 03/30/23

-----Clinic--------------------Appt Date/Time--------Status---------------------
6   Chy Visual Field          07/15/2022@09:00      Act Req/Checked In    
38  Chy Optometry             12/01/2022@14:45      Act Req/Checked Out   

NUMBER        NAME
--------------------------------------------------------------------------------

437           CHY VISUAL FIELD
999           CHY OPTOMETRY

DEV TOOL CALLS THAT RETURN THOSE CLINICS
https://staging-api.va.gov/vaos/v2/locations/983/clinics?clinical_service=optometry

,…}
data: [{id: "408", type: "clinics",…}, {id: "437", type: "clinics",…}, {id: "627", type: "clinics",…},…]
0: {id: "408", type: "clinics",…}
attributes: {vistaSite: 983, id: "408", serviceName: "CHY OPT VAR1", physicalLocation: null, phoneNumber: null,…}
char4: null
id: "408"
patientDirectScheduling: true
patientDisplay: true
phoneNumber: null
physicalLocation: null
primaryStopCode: 408
primaryStopCodeName: "OPTOMETRY"
secondaryStopCode: null
secondaryStopCodeName: "*Missing*"
serviceName: "CHY OPT VAR1"
stationId: "983"
stationName: "CHYSHR-Cheyenne VA Medical Center"
vistaSite: 983
id: "408"
type: "clinics"
1: {id: "437", type: "clinics",…}
attributes: {vistaSite: 983, id: "437", serviceName: "VISUAL FIELD", physicalLocation: null, phoneNumber: null,…}
char4: null
id: "437"
patientDirectScheduling: true
patientDisplay: true
phoneNumber: null
physicalLocation: null
primaryStopCode: 408
primaryStopCodeName: "OPTOMETRY"
secondaryStopCode: null
secondaryStopCodeName: "*Missing*"
serviceName: "VISUAL FIELD"
stationId: "983"
stationName: "CHYSHR-Cheyenne VA Medical Center"
vistaSite: 983
**id: "437"**
type: "clinics"
2: {id: "627", type: "clinics",…}
attributes: {vistaSite: 983, id: "627", serviceName: "CHY C&P OPTOMETRY GRUBBS", physicalLocation: null,…}
char4: null
id: "627"
patientDirectScheduling: null
patientDisplay: null
phoneNumber: null
physicalLocation: null
primaryStopCode: 408
primaryStopCodeName: "OPTOMETRY"
secondaryStopCode: 450
secondaryStopCodeName: "COMP & PENS (C&P) EXAMS"
serviceName: "CHY C&P OPTOMETRY GRUBBS"
stationId: "983"
stationName: "CHYSHR-Cheyenne VA Medical Center"
vistaSite: 983
id: "627"
type: "clinics"
3: {id: "855", type: "clinics",…}
attributes: {vistaSite: 983, id: "855", serviceName: "CHY OPTOMETRY GRUBBS RETURN",…}
char4: null
id: "855"
patientDirectScheduling: false
patientDisplay: true
phoneNumber: null
physicalLocation: "SPECIALTY CLINIC"
primaryStopCode: 408
primaryStopCodeName: "OPTOMETRY"
secondaryStopCode: null
secondaryStopCodeName: "*Missing*"
serviceName: "CHY OPTOMETRY GRUBBS RETURN"
stationId: "983"
stationName: "CHYSHR-Cheyenne VA Medical Center"
vistaSite: 983
id: "855"
type: "clinics"
4: {id: "999", type: "clinics",…}
attributes: {vistaSite: 983, id: "999", serviceName: "Friendly Name Optometry", physicalLocation: null,…}
char4: "ETEM"
**id: "999"**
patientDirectScheduling: true
patientDisplay: true
phoneNumber: null
physicalLocation: null
primaryStopCode: 408
primaryStopCodeName: "OPTOMETRY"
secondaryStopCode: null
secondaryStopCodeName: null
serviceName: "Friendly Name Optometry"
stationId: "983"
stationName: "CHYSHR-Cheyenne VA Medical Center"
vistaSite: 983
id: "999"
type: "clinics"

**Comment by jenniemc** [comment]
The booked appointment for optometry care dated 2022-07-15 is returned with the “requestedPeriods” field which the FE reads as requested appointment and NOT a past booked appointment.  Because it is now categorized as a request, FE cannot find history of clinic 437 in the past 12 months of booked appointments for ola.e.edgecombe@id.me.

Also, I cannot find an optometry appointment dated 12/01/2022 in test harness. There was one appointment for that same date but it was for primary care. 

Based on these finding, FE is working as expected.
@marcynadeau , @ldelacosta, @simiadebowale  

   ```
 {
        "id": "154125",
        "type": "appointments",
        "attributes": {
            "id": "154125",
            "identifier": [
                {
                    "system": "Appointment/",
                    "value": "4139383338313835"
                }
            ],
            "kind": "clinic",
            "status": "booked",
            "serviceType": "optometry",
            "serviceTypes": [
                {
                    "coding": [
                        {
                            "system": "http://veteran.apps.va.gov/terminologies/fhir/CodeSystem/vats-service-type",
                            "code": "optometry"
                        }
                    ]
                }
            ],
            "serviceCategory": [
                {
                    "coding": [
                        {
                            "system": "http://www.va.gov/Terminology/VistADefinedTerms/409_1",
                            "code": "REGULAR",
                            "display": "REGULAR"
                        }
                    ],
                    "text": "REGULAR"
                }
            ],
            "patientIcn": "1013120830V747912",
            "locationId": "983",
            "clinic": "437",
            "start": "2022-07-15T15:00:00Z",
            "end": "2022-07-15T15:15:00Z",
            "created": "2022-07-20T00:00:00Z",
            "requestedPeriods": [
                {
                    "start": "2022-07-20T00:00:00Z",
                    "end": "2022-07-20T00:00:00Z"
                }
            ],
            "cancellable": true,
            "extension": {
                "ccLocation": {
                    "address": {}
                },
                "vistaStatus": [
                    "ACT REQ/CHECKED IN"
                ]
            },
            "serviceName": "CHY VISUAL FIELD",
            "friendlyName": "VISUAL FIELD",
            "location": {
                "id": "983",
                "type": "appointments",
                "attributes": {
                    "id": "983",
                    "vistaSite": "983",
                    "vastParent": "983",
                    "type": "va_facilities",
                    "name": "Cheyenne VA Medical Center",
                    "classification": "VA Medical Center (VAMC)",
                    "timezone": {
                        "timeZoneId": "America/Denver"
                    },
                    "lat": 39.744507,
                    "long": -104.830956,
                    "website": "https://www.denver.va.gov/locations/directions.asp",
                    "phone": {
                        "main": "307-778-7550",
                        "fax": "307-778-7381",
                        "pharmacy": "866-420-6337",
                        "afterHours": "307-778-7550",
                        "patientAdvocate": "307-778-7550 x7517",
                        "mentalHealthClinic": "307-778-7349",
                        "enrollmentCoordinator": "307-778-7550 x7579"
                    },
                    "physicalAddress": {
                        "type": "physical",
                        "line": [
                            "2360 East Pershing Boulevard"
                        ],
                        "city": "Cheyenne",
                        "state": "WY",
                        "postalCode": "82001-5356"
                    },
                    "mobile": false,
                    "healthService": [
                        "Audiology",
                        "Cardiology",
                        "DentalServices",
                        "EmergencyCare",
                        "Gastroenterology",
                        "Gynecology",
                        "MentalHealthCare",
                        "Nutrition",
                        "Ophthalmology",
                        "Optometry",
                        "Orthopedics",
                        "Podiatry",
                        "PrimaryCare",
                        "SpecialtyCare",
                        "UrgentCare",
                        "Urology",
                        "WomensHealth"
                    ],
                    "operatingStatus": {
                        "code": "NORMAL"
                    }
                }
            }
        }
    },
```

**Comment by jenniemc** [comment]
There is a jira ticket to remove the "requestedPeriods"  from booked appointments. https://issues.mobilehealth.va.gov/browse/VAOSR-5983
