### ISSUE TITLE
Use new Yellow Ribbon `vets-api` endpoint in `vets-website` for `/yellow-ribbon/schools`

### ISSUE THREAD

**Issue by kelsonic** [department-of-veterans-affairs/va.gov-team#5608]
## Description

Now that `vets-api` has the new Yellow Ribbon endpoint, we should use this endpoint instead of `/gi/institutions/search` as it will have more accurate data.

**This ticket is BLOCKED by [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/5599).**

## Acceptance Criteria

- [ ] Use [the new `vets-api` endpoint](https://github.com/department-of-veterans-affairs/va.gov-team/issues/5599) for querying Yellow Ribbon programs on the `vets-website` page `/yellow-ribbon/schools`.
- [ ] Update unit tests.

**Comment by kelsonic** [comment]
CC @ncksllvn

**Comment by MickinSahni** [comment]
2020-02-12 PW Sprint Planning
- We'll groom the acceptance criteria and estimate before pulling into sprint 15 *if we have room*

**Comment by AkucherGCIO** [comment]
@kelsonic - Will this ticket be complete for Sprint 16 ?

**Comment by AkucherGCIO** [comment]
03/13/20 PW Standup
PR will be open today.

**Comment by MickinSahni** [comment]
2020-03-16 PW Standup
* PR opening today

**Comment by MickinSahni** [comment]
2020-03-18 PW Standup
* PR merged and need to validate

**Comment by MickinSahni** [comment]
Validated switch to new endpoint
![image](https://user-images.githubusercontent.com/13204473/76980879-22a73c80-6910-11ea-8af9-010b71e06ac8.png)
