### ISSUE TITLE
Prod Manifest Modifications - REQUIRED AFTER 100% PROD ROLLOUT

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#56086]
Configuration Checklist for vets-api-prod. These items should be configured in order.

- [x] [Enable db-migrate and worker](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/1696)
- [ ] [Enabled Auto-sync](https://github.com/department-of-veterans-affairs/vsp-infra-argocd/pull/197)

**Comment by laineymajor** [comment]
@RachalCassity where does this stand?

**Comment by laineymajor** [comment]
Closing as this is a duplicate
