### ISSUE TITLE
Alerts! Failed sync Alert (ArgoCD -> Slack)

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#56088]
Send failed sync alerts to slack. Follow this [documentation](https://argocd-notifications.readthedocs.io/en/latest/services/slack/).

*Note: ArgoCD user may already exists. Check with Rachal before creating a slack user.

**Comment by laineymajor** [comment]
@RachalCassity where does this stand?

**Comment by laineymajor** [comment]
Complete
