### ISSUE TITLE
Intro guide for SNOW usage

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#56084]
Create document with description and screenshots:
- [x] Intro to YourIT and SNOW
- [x] ITIL role explained
- [x] How to get ITIL role
- [x] Common uses for SNOW
  - [x] Technical services catalog
  - [x] Create incident

**Comment by annekerr49** [comment]
[Getting access to ServiceNow.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/11576008/Getting.access.to.ServiceNow.docx)
