### ISSUE TITLE
[Bug] Profile: "Please add your home address" link isn't working

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#5609]
## What happened?

When I tried to add a home address, clicking the "Please add your home address" link broke the page.

## Specs:
- Device: Macbook
- Browser: Chrome
- Test User: User 226 (though probably any would work)

## Steps to Reproduce
- URL: https://staging.va.gov/profile/
- Test User: User 226 (though probably any would work)

1. Go to the profile.
2. Click "Please add your home address."
3. The screen jumps down to the footer. When I scroll up, see this:

<img width="1280" alt="Screen Shot 2020-02-06 at 1 04 23 PM" src="https://user-images.githubusercontent.com/34068740/73964956-3dce6780-48e1-11ea-9b73-2e50eb70b2bf.png">

## Desired behavior

The Home address form should open after clicking "Please add your home address"

## Acceptance Criteria

- [ ] The Home address form should open after clicking "Please add your home address"

**Comment by erikphansen** [comment]
This is pretty critical. Will look into this next.

**Comment by Samara-Strauss** [comment]
Validated on staging. Closing!

**Comment by Samara-Strauss** [comment]
Validated on staging. Closing!
