### ISSUE TITLE
[Alerts] fine-tune alerts

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#56101]
**PROBLEM STATEMENT**
Before releasing vets-api in EKS to the wild, we want to make sure the appropriate alerts are in place to catch problems and that those alerts are actionable and routed correctly. 

**TASKS**
Review the alerts created as part of the epic https://github.com/department-of-veterans-affairs/va.gov-team/issues/54162 and check to see if alerts are coming in as expected and are not too spammy and are actionable. Which channels are they coming in? Are the alerts triggered when they should be? For `no_pods_running` (https://github.com/department-of-veterans-affairs/va.gov-team/issues/54255), is there a more sophisticated way to do this? Possibly comparing desired to available? ([Slack thread for reference](https://adhoc.slack.com/archives/C045LCF8WU8/p1680190112437799?thread_ts=1680189246.130709&cid=C045LCF8WU8).)

**ACCEPTANCE CRITERIA**
Alerts are in a good place: the right people are getting alerted the appropriate amount in the appropriate channels for critical infrastructure issues.

**Comment by laineymajor** [comment]
This might be done... Rachal to check.

**Comment by RachalCassity** [comment]
PR in review

**Comment by laineymajor** [comment]
@LindseySaari for a quick review :) 
https://app.zenhub.com/workspaces/platform-tech-team-1-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/devops/13075

**Comment by LindseySaari** [comment]
I gave the approval stamp on this, but don't have devops perms
