### ISSUE TITLE
Sign-in Service App - Create ECR repo

### ISSUE THREAD

**Issue by rileyanderson** [department-of-veterans-affairs/va.gov-team#56105]
Create ECR repo for sign in service

## Devops Tasks
- [x] In devops repo, add `identity-sign-in-service` to `ecr.tf`

## Acceptance Criteria
- [x] Repo successfully created
- [x] Able to push and pull images from repo

**Comment by rileyanderson** [comment]
verified repo is created

**Comment by mjconw3** [comment]
Looks good @rileyanderson appreciate it! Closing this out
