### ISSUE TITLE
Cleanup Sign-in Service infra repo

### ISSUE THREAD

**Issue by rileyanderson** [department-of-veterans-affairs/va.gov-team#56120]
## Issue Description
There seems to already be a lot of tech debt in the repo. We need to figure out what can stay/be cleaned up. It might even be easier to start fresh since we are still early in the game. 

Potential file structure
```
├── modules/
│   ├── aws/
│   │   ├── ec2/
│   │   ├── rds/
│   │   ├── vpc/
|   |   └── .../
│   └── k8s/
│       ├── deployment/
│       ├── service/
│       └── ingress/
├── environments/
│   ├── dev/
│   │   ├── aws/
│   │   │   ├── main.tf
│   │   │   ├── variables.tf
│   │   │   └── terraform.tfvars
│   │   ├── k8s/
│   │   │   ├── Chart.yaml
│   │   │   ├── values.yaml
│   │   │   └── templates/
│   │   └── terraform.tfstate
│   ├── staging/
│   │   ├── aws/
│   │   │   ├── main.tf
│   │   │   ├── variables.tf
│   │   │   └── terraform.tfvars
│   │   ├── k8s/
│   │   │   ├── Chart.yaml
│   │   │   ├── values.yaml
│   │   │   └── templates/
│   │   └── terraform.tfstate
│   └── prod/
│       ├── aws/
│       │   ├── main.tf
│       │   ├── variables.tf
│       │   └── terraform.tfvars
│       ├── k8s/
│       │   ├── Chart.yaml
│       │   ├── values.yaml
│       │   └── templates/
│       └── terraform.tfstate
├── .gitignore
└── README.md
```

## Devops tasks
- [ ] Determine which components are needed
- [ ] Ensure consistent naming
- [ ] If deemed beneficial start with a fresh repo 

## Acceptance Criteria
- [ ] Updated README and documentation

#### Tech notes

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mjconw3** [comment]
Hey @rileyanderson was taking a look at this. Looks good to me. I had a bit of a draft I was writing up I can post in here or send over but this type of structure should be fine and easy enough to navigate

**Comment by rileyanderson** [comment]
Not doing right now
