### ISSUE TITLE
add team members to bah-vetsgov-developers group so that they can view log streams in AWS

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#5612]
## Description

The following team members need updated AWS access so that they are able to view log streams in support of our testing. They are currently receiving this warning message: 

![image (3).png](https://images.zenhubusercontent.com/5b645f6fe2255460d8f0b032/c8c9b840-d84c-48da-a88d-cf0195d411d2) 

I believe the groups created for our team were bah-vetsgov-cloudwatch, bah-vetsgov-developers.

Thank you!

Team Members: 
@sonntag-adam 
@delli-gatti-michael 

## Acceptance Criteria:

- [ ] members of the BAH development team working on GIDS should be able to view the GIDS logs

**Comment by wyattwalter** [comment]
@benniemosher I'm guessing the log stream is something like `dsva-vagov-<env>/srv/gi-bill-data-service/<something>`

**Comment by benniemosher** [comment]
It appears the team name is `bah-vfs-developers`. They have the managed policies of `CloudWatchLogsReadOnlyAccess` as well as `CloudWatchReadOnlyAccess`.

However, they are still unable to see https://console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#logStream:group=dsva-vagov-staging/srv/gi-bill-data-service/src/log/gi-bill-data-service.log;streamFilter=typeLogStreamPrefix

After further investigation, they have a `Force_MFA` policy  that explicitly denies access to :all-the-things: unless MFA is set. Neither of these users have MFA set. I have asked both developers to enable MFA and then report back on if they can access the logs now.
