### ISSUE TITLE
Adding Natalia Mashaeva to DSVA Slack

### ISSUE THREAD

**Issue by huggins-va** [department-of-veterans-affairs/va.gov-team#56131]
Good morning,

Please add Natalia Mashaeva as a multi-user channel to these channels: 

api-health, team-pteracuda and team-shanktopus

Email: mashaeva_natalia@bah.com 

Thank you!

**Comment by LEHigley** [comment]
could only add to api health

**Comment by huggins-va** [comment]
Can you clarify why you could not add to other channels?
