### ISSUE TITLE
GIDS: Crosswalk updates cannot be saved

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#5613]
When reviewing Crosswalk issues on Staging, a user is able to manually update data. Once the user updates data for an institution, they save their updates by clicking the "update" button. Currently clicking this button results in an error.

1. Log in to GIDS
2. Click "Crosswalk Partial Matches" in the header
3. Click "Edit" for any issue
4. Edit the data and click "Update"

After clicking "Update" the changes should be saved and the user should be returned to the Crosswalk Partial Matches page. Instead, the user receives the error message below:

![Screen Shot 2020-02-06 at 1.46.19 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/c6387f73-588e-4aaf-837d-68ff8ffc3a0c)

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/568

gibct-data-service branch `bah-ci-form-path`

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
Fix is now live on Staging. Closing this issue
