### ISSUE TITLE
Design C&P appointment templates

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#56156]
## Task Description
Design C&P appointments as they will display in VAOS.

## References
- [C&P workflow ](https://www.figma.com/file/wpu8ihC3ps2gjAd37lPkrs/Compensation-and-Pension-(C%26P)-Exam---initial-discovery?node-id=0%3A1&t=0ZIrNDglvgEbdr6V-1)

## Acceptance Criteria
- [x] [Design specs ](https://www.figma.com/file/BK1nkXoXfSmrfRHOk4BEOR/Compensation-and-Pension?node-id=13-33)for C&P appointments in:
    - Lists: Upcoming and Past
    - Details pages: Upcoming and Past

**Comment by outerpress** [comment]
FYI @Cieramaddox no changes from 4/14 meeting. One open q, whether there's a database of facility-specific comp and pen office phone numbers we can access. Kay will set up a follow-up meeting with the Comp and Pen SME's for early next week.

**Comment by outerpress** [comment]
@Cieramaddox we want to add a link from the appointment details page to ebenefits. Kay will provide the URL and proposed language.

@klawyer could you comment here with URL and language when you have it?

**Comment by outerpress** [comment]
@ldelacosta just to confirm, we won't be looking at adding a link until later, is that right?

**Comment by Cieramaddox** [comment]
Closing ticket. Will create a new one when expectations are updated
