### ISSUE TITLE
Board Appeal ( NoD) Qualitative Data Request

### ISSUE THREAD

**Issue by Evafloyd** [department-of-veterans-affairs/va.gov-team#56154]
### Data Type Requested

User Surveys

### Date Range Start

03-01-2022

### Date Range End

03-01-2023

### Product Name(s)

Board Appeal (NoD)

### Product Description

We are looking to learn more about Board of Appeal (also known as Notice of Disagreement), including the authenticated form. 

With this data we're hoping to establish a baseline satisfaction score, establish a baseline task completion, and identify common questions and pain points. 

This is my first time submitting one of these requests so advice is welcome! And I really enjoyed your presentation for the design community a few weeks ago, very helpful. 

### Product URL(s) and/or term(s)

Unauthenticated areas of interest
- https://www.va.gov/decision-reviews/ 
- https://www.va.gov/decision-reviews/board-appeal/
- https://www.va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182 

Within the actual form
- https://va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182/veteran-details
- https://va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182/homeless
- https://va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182/contact-information
- https://va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182/filing-deadlines
- https://va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182/area-of-disagreement/0
- https://va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182/issue-summary
- https://va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182/board-review-option
- https://va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182/evidence-submission
- https://va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182/hearing-type
- https://va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182/review-and-submit

### File Delivery Format

One file, different tab for each term/URL

### VA Email Address(es)

eva.floyd@va.gov

### Add Assignee and Labels

If not already done so, please ensure @ianMcCullough-ob is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by Evafloyd** [comment]
We're curious about the typical timeframe for this type of request. Could you give us a sense of when this data might be available for our team to begin synthesis? Thank you!

**Comment by ianMcCullough-ob** [comment]
@Evafloyd Im currently OOO, will be back next week. You can reach out to the vsp-contact-center-support channel and see if someone might be able to fill in until I return.

**Comment by saderagsdale** [comment]
I reached out to @ATMiddleton in the channel. thx all!

**Comment by ianMcCullough-ob** [comment]
Hello @Evafloyd, thanks for reaching out. I've been tied up in meetings all week, will have this export to you by end of day Thursday at the latest.

**Comment by ianMcCullough-ob** [comment]
@Evafloyd Just shared the export with you, feel free to reach out through slack if you have any questions.

**Comment by Evafloyd** [comment]
Wonderful, thanks so much. I'll check my VA email and follow up with any questions.
