### ISSUE TITLE
Status Links Update

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#56168]
## Description
The Pending and Past navigation links should be styled as links but in the VAOS application they are coded as buttons. 

Reference collab ticket [#55858](https://app.zenhub.com/workspaces/vaos-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/55858)

---

## Acceptance Criteria
Background: the `va_online_scheduling_appointment_list` toggle is on

- [ ] Given when the user is on the Upcoming status view 
       When the user is on the Voiceover feature and tabs on Pending and Past 
       Then Voiceover will announce the Pending and Past links

- [ ] Given when the user is on the Pending status view 
       When the user is on the Voiceover feature and tabs on Upcoming and Past 
       Then Voiceover will announce the Pending and Past links

- [ ] Given when the user is on the Past status view 
       When the user is on the Voiceover feature and tabs on Upcoming and Pending 
       Then Voiceover will announce the Pending and Past links

### Design Assets
Not applicable 

## Definition of Done
- [x] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by Cieramaddox** [comment]
@ldelacosta - Ticket has been tested and ready to go!

**Comment by ldelacosta** [comment]
No new issues. Closing out the ticket.
