### ISSUE TITLE
Requests for product directory

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#56165]
### Description
Hi y'all! I'm currently [putting together an a11y dashboard to measure the a11y health of all VA.gov products.](https://docs.google.com/spreadsheets/d/1lgzMiZZ-0rBPDuB2gRupBAjsyF0WTe005VvEHYrMxww/edit?usp=sharing) A good chunk of that work involves:
- finding relevant labels on github for each product
- determining if products have 
  - not started yet, 
  - are live, 
  - have been archived, 
  - a team
  - or are duplicates

A couple of pain points I've experienced so far include:
 - There are two instances of Fry/DEA on the products list, are these duplicates? Or separate? 
   - Fry/DEA — VA Education Benefits For Survivors And Dependents
   - Education Benefits Application under FRY or DEA (22-5490)
- Find a form may have 3 github labels: pw-find-a-form, dt-find-va-form, sd-find-va-form; it's unclear if I should filter based on one or a combination of these
- [No work seems to have started for Form 22-5490 Updates](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/my-education-benefits/Form%2022-5490%20Updates/Product%20Outline.md), but I can't be sure
- It's unclear if several of the covid products are still owned by a team or have been archived

#### Feature request
I know y'all have a ton on y'alls plate, but a dream future state of features might include:
- github labels associated with products
- status on if a product has started, is live, or archived
- a date indicating when a product's information was last updated
- some method of maintenance not dependent on teams or some requirement for teams to keep information up to date

### Relevant URLs
[VFS product directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory)

### Which type of team are you on? (Platform team, VFS team, or Leadership)
CAIA (Content Accessibility IA)

**Comment by vbellissimo** [comment]
Hi @joshkimux Thank you for submitting this.

We actually have another process to enter these kinds of feature requests. Can you please re-enter this request through [this form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?labels=platform-feature-request&template=platform-feature-request.yml&title=%5BFeature-Name%5D%3A)? This form is part of a more strategic process to [submit feature requests](https://depo-platform-documentation.scrollhelp.site/support/submitting-a-feature-request) to the Platform. When you submit that through that process, it will be looked at at a higher, more strategic level by Platform Service Design and leadership.

(This form you submitted through is simply for content edit requests and it comes to the Platform Content team)

Thanks!
