### ISSUE TITLE
Update the aria-label on the Details link 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#56167]
## Description
In our recent work for the Appointment List redesign, we added the aria-label for the voiceover. We discovered that there is an issue with the aria-label which the Design Systems would need to address. Since the timing of the fix is unknown, we will need to implement a short term solution for this issue. 

Reference ticket [#55856](https://app.zenhub.com/workspaces/vaos-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/55856)
Steps to reproduce from Collab Cycle team:

1. On a Windows machine, log into staging with a test user and navigate to [Your appointments](https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/).
2. Activate [NVDA](https://www.nvaccess.org/download/).
3. Press [Tab] to move focus to a Details link.
Note that the link is announced as "Details" and not as its aria-label.
On a Mac, log into staging with a test user and navigate to [Your appointments](https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/).
4. Activate VoiceOver.
5. Press [Tab] to move focus to a Details link.
Note that the link's aria-label is announced as expected.

---

## Acceptance Criteria
Background: the `va_online_scheduling_appointment_list` toggle is on

- [ ] Given on the new appointment list redesign view 
        When the user is using the Voiceover feature and clicks Details
        Then the link will be an anchor component 

## Technical Specs

- [ ] _enter details_

### Design Assets
Not applicable 

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by ldelacosta** [comment]
@outerpress @Cieramaddox - This ticket is ready to be tested in staging. Thanks

**Comment by outerpress** [comment]
@ldelacosta @simiadebowale looks like this change needs to be made for Pending appts as well.

Upcoming and Past are working great though! TalkBack is announcing the links properly now.

**Comment by ldelacosta** [comment]
Re-assigning the ticket back to @simiadebowale

**Comment by ldelacosta** [comment]
@outerpress @Cieramaddox - This ticket is ready to be tested in staging. Please let us know if you have any issues.

**Comment by simiadebowale** [comment]
@outerpress - this is ready for validation

**Comment by simiadebowale** [comment]
@outerpress - this is ready for validation

**Comment by ldelacosta** [comment]
No new issues reported. Closing out the ticket.
