### ISSUE TITLE
Add Upcoming, Pending and Past links to the status view 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#56164]
## Description
We will need to add the Upcoming, Pending or Past links to the different status view to help the Veteran navigate between the appointment status.  

[Reference ticket #55857 from collab cycle](https://app.zenhub.com/workspaces/vaos-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/55857)

---

## Acceptance Criteria
Background: the `va_online_scheduling_appointment_list` toggle is on

- [ ] Given when the user is on the Upcoming view 
        When the user clicks on Pending
        Then user will see Upcoming and Past links in the Pending status page 
        And page design matches the [design spec](https://www.figma.com/file/XmvY7ijIOTPgfQ3cTXodJD/Upcoming%2C-Past-and-Pending-Links-added-to-Appointment-List?node-id=13-33&t=7ErgSTzF6JszYuo0-0) 

- [ ] Given when the user is on the Pending view 
        When the user clicks on Past
        Then user will see Upcoming and Pending links in the Past status page 
        And page design matches the [design spec](https://www.figma.com/file/XmvY7ijIOTPgfQ3cTXodJD/Upcoming%2C-Past-and-Pending-Links-added-to-Appointment-List?node-id=13-33&t=7ErgSTzF6JszYuo0-0) 

- [ ] Given when the user is on the Past view 
        When the user clicks on Upcoming
        Then user will see Pending and Past links in the Upcoming status page 
        And page design matches the [design spec](https://www.figma.com/file/XmvY7ijIOTPgfQ3cTXodJD/Upcoming%2C-Past-and-Pending-Links-added-to-Appointment-List?node-id=13-33&t=7ErgSTzF6JszYuo0-0) 

### Technical Specs
_enter_

### Design Assets
[Figma File](https://www.figma.com/file/XmvY7ijIOTPgfQ3cTXodJD/Upcoming%2C-Past-and-Pending-Links-added-to-Appointment-List?node-id=13-33&t=7ErgSTzF6JszYuo0-0) 

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by vbahinwillit** [comment]
Can't view the design spec.

**Comment by outerpress** [comment]
@vbahinwillit I just fixed the permissions, give it another try and let me know if it's still not working.

**Comment by vbahinwillit** [comment]
It's working. Thanks!

**Comment by ldelacosta** [comment]
Validated the navigation links in staging for `judy.morrison@id.me`

![Screenshot 2023-04-07 at 1.22.21 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/abfdb7f1-9602-4333-90fb-1df0d754cc42)
![Screenshot 2023-04-07 at 1.22.31 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/c1774625-3af9-450b-9739-4f46e7cddc92)![Screenshot 2023-04-07 at 1.22.53 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/48e19c88-dda0-45d7-9cc0-0ff5d4eef61e)

**Comment by outerpress** [comment]
@ldelacosta this is good to go

**Comment by ldelacosta** [comment]
No new issues. We are addressing the spacing update in [#56790](https://app.zenhub.com/workspaces/vaos-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/56790)
