### ISSUE TITLE
Update number of days to complete disability-related claims in March 2023

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#56177]
We need to update the number of days it takes to complete disability related claims. Sitewide content needs to email Tanekwa Bournes on the first of the month to get the number from the previous month and input into Drupal.

This needs to be done on the following pages:
https://www.va.gov/disability/after-you-file-claim/
https://www.va.gov/disability/how-to-file-claim/

- [x]  Email Tanekwa for most recent number (Laura)
- [x]  Input number and new month into both Drupal pages (Aliyah)
- [x]  Review and publish (Megan)

**Comment by laurwill** [comment]
Hi @aliyahblackmore ,
The number for March is 118.3. Thanks!

**Comment by aliyahblackmore** [comment]
Hi @megzehn this is ready for you! 

The VA claim process after you file your claim
**Preview link:** http://preview-prod.vfs.va.gov/preview?nodeId=870

How to file a VA disability claim 
**Preview link:** http://preview-prod.vfs.va.gov/preview?nodeId=905

**Comment by megzehn** [comment]
Thanks, @aliyahblackmore! I reviewed and published these pages.

**Comment by laurwill** [comment]
@RLHecht I validated and let Tanekwa know. You can close this out when you're back!

**Comment by RLHecht** [comment]
Thanks all! Closing this!
