### ISSUE TITLE
Access for Philip Becker

### ISSUE THREAD

**Issue by erluti** [department-of-veterans-affairs/va.gov-team#5617]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeff Hayter
- Please provide your name.
   > Philip Becker
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VSP Back End Tools, Engineer, Oddball.io
- [Grant AWS Console access?]
  > YES
  >  Necessary for engineering and support duties

**Comment by erluti** [comment]
@department-of-veterans-affairs/vsp-operations

I missed the step of adding a label for my team, and it looks like I can't edit the issue, sorry about that.

**Comment by tskinn** [comment]
Name: Philip Becker
COR: @Jeff-Hayter

**Comment by johnpaulashenfelter** [comment]
@Jeff-Hayter is there any way we can hep move this forward?

**Comment by Jeff-Hayter** [comment]
@tskinn @johnpaulashenfelter Just waiting on security documents to be transferred from the previous COR.

**Comment by johnpaulashenfelter** [comment]
Thanks for the update @Jeff-Hayter

**Comment by Jeff-Hayter** [comment]
@tskinn Approved for AWS access.

**Comment by ricetj** [comment]
AWS access was issued
