### ISSUE TITLE
Filter out serviceType on non health, non C&P appointments

### ISSUE THREAD

**Issue by cferris32** [department-of-veterans-affairs/va.gov-team#56197]
From [this recent spike](https://app.zenhub.com/workspaces/vaos-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/54558) we discovered that non-health appointments are showing health-related serviceTypes (audiology, optometry, primaryCare, etc) and we'd like to filter out this field on irrelevant appointment types as to not confuse the veteran about the service being provided. For now we would like to maintain the serviceType on health appointments and C&P appointments, and filter it out for the rest.

AC:
[ ] - vets-api filters out the serviceType on any appointment that does not have a serviceCategory of "REGULAR" or "C&P"

**Comment by klawyer** [comment]
@ajmagdub I am good with bullet #1 and #2 ( starting with 42% and 50%). For bullet 3- that is odd they don't have a Service Category. Can you send me the raw data?

**Comment by ajmagdub** [comment]
@klawyer I have collected the data and filtered it to only show VA appointments, including clinic, phone, and telehealth, without any service categories.

[https://app.zenhub.com/files/133843125/7a44a42e-99a4-4f94-9b17-5ea113830a04/download](https://app.zenhub.com/files/133843125/7a44a42e-99a4-4f94-9b17-5ea113830a04/download)

**Comment by ajmagdub** [comment]
@ldelacosta @klawyer for now, I'll leave clinic, phone, and telehealth appointments without a service category as is.
