### ISSUE TITLE
[Product Directory]: Github labels, status, and updates

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#56214]
### Describe the problem

Hi y'all! I'm currently [putting together an a11y dashboard to measure the a11y health of all VA.gov products.](https://docs.google.com/spreadsheets/d/1lgzMiZZ-0rBPDuB2gRupBAjsyF0WTe005VvEHYrMxww/edit?usp=sharing) A good chunk of that work involves:
- finding relevant labels on github for each product
- determining if products have 
  - not started yet, 
  - are live, 
  - have been archived, 
  - a team
  - or are duplicates

A couple of pain points I've experienced so far include:
 - There are two instances of Fry/DEA on the products list, are these duplicates? Or separate? 
   - Fry/DEA — VA Education Benefits For Survivors And Dependents
   - Education Benefits Application under FRY or DEA (22-5490)
- Find a form may have 3 github labels: pw-find-a-form, dt-find-va-form, sd-find-va-form; it's unclear if I should filter based on one or a combination of these
- [No work seems to have started for Form 22-5490 Updates](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/my-education-benefits/Form%2022-5490%20Updates/Product%20Outline.md), but I can't be sure
- It's unclear if several of the covid products are still owned by a team or have been archived

### Who will benefit

- Any team providing shared support that needs up to date information on products, their owners, and tracking
- Platform to better track and measure team health and performance
- Folk onboarding onto VA.gov looking to quickly understand the various teams at play

### Describe your idea

I know y'all have a ton on y'alls plate, but a dream future state of features might include:
- github labels associated with products
- status on if a product has started, is live, or archived
- a date indicating when a product's information was last updated
- some method of maintenance not dependent on teams or some requirement for teams to keep information up to date

### Provide evidence

- I have opened several tickets trying to determine if a product is archived, is a duplicate, or no longer has an owner
- In conversations, I've heard teams may be completely unaware this product directory exists
  - A possible way to check this quant wise is to see how many views/updates these pages are actually receiving / when the last time pages were updated
- Some products may have multiple github labels, or no github labels at all; for folk looking to track performance team by team by looking through their issues on github, having a label would be super clutch

From the lens of this a11y dashboard, it will enable us to have a much stronger (and critically, _measurable_) pulse check on our a11y health and performance team by team.

### Platform Mission

- [X] Keeps these products and services available, stable, and secure.
- [X] Ensures they are consistent and meet high standards of quality in Veteran-centered user experience and technical approach.
- [X] Provides shared tools, software, support, and technical infrastructure to accelerate their development.
- [ ] Other

**Comment by CBonade** [comment]
As this ticket is related to product directory issues, adding this to the Product Directory epic. Ticket will still need further refinement.

**Comment by CBonade** [comment]
@joshkimux We are currently in the process of working with OCTO to get a definitive list of products slimmed down to exist on the product directory for what's currently desired to be tracked. In some cases, we may track products that are no longer maintained as long as they are still active on VA.gov. Once that list is complete, we will evaluate further changes at that time if there are still things perceived as dated. Is this still something you're hoping to get our list tidied for or has the need changed since April?

**Comment by joshkimux** [comment]
That sounds like a great first step! Thank you @CBonade for the update.

**Comment by steel36** [comment]
Status update on this Feature Request:  @CBonade Has there been any progress on this item? Is it still under consideration or still active in some capacity?

**Comment by tayism** [comment]
Hi there @CBonade -- any recent updates here? Thanks!

**Comment by gopixelsgo** [comment]
Hi @CBonade, just following up on the status of this ticket. Do you know if it may have evolved into a "not sure" (happens a lot), or maybe it can be closed? Thanks!

**Comment by CBonade** [comment]
Hey there, all. Just an update here that the product directory maintenance has been turned over to OCTO and they will be making any adjustments to products moving forward. Can probably close this ticket as I believe they have their own plans for the future of this.

**Comment by tayism** [comment]
@CBonade Thanks for the update! I'm going to close this ticket on the Feature Request Board for now.

**Comment by tayism** [comment]
OCTO to take over Product Directory maintenance.
