### ISSUE TITLE
Load Balancer issue

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#56234]
### PROBLEM STATEMEMT
Users (veterans) are unable to use the search on https://www.va.gov/search (see comment section for screenshot)

### ADDITIONAL INFO
www.va.gov/:1 Access to fetch at 'https://api.va.gov/v0/search?query=test' from origin 'https://www.va.gov' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Issue is revproxy. Getting a 404 with nginx.**
**Revproxy unable to hit the load balancer, therefore requests could NOT hit traefik**

### ACTIONS TRIED
- [ ] Add web origins to the manifest repo
- [ ] Review and sync origin policies
- [ ] Add web origins reject(s)
web_origin_regex: "\\Ahttps?:\\/\\/.*\\.cms\\.va\\.gov\\z"
[Param store link](https://console.amazonaws-us-gov.com/systems-manager/parameters/dsva-vagov/vets-api/prod/web_origin/description?region=us-gov-west-1&tab=Table#list_parameter_filters=Name:Contains:%2Fdsva-vagov%2Fvets-api%2Fprod%2Fweb_origin)
- [ ] [Add custom headers](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/1705#pullrequestreview-1371014124)
- [ ] [PR to add custom headers ](https://github.com/department-of-veterans-affairs/devops/pull/12758/files)
- [ ] Fixing work that was completed due to the [ATO work](https://github.com/department-of-veterans-affairs/devops/pull/12734)
- [ ] Fix with the headers
- [ ] Sending the search type ahead endpoint to EKS because the frontend search box calls search type ahead and /v0/search at the same time
- [ ] proxy pass

### RESOLUTION
- [x] **[FIX LOAD BALANCER RULE ](https://github.com/department-of-veterans-affairs/devops/pull/12769/files)**
- [ ] Revert all tried efforts listed above
*Note: test in staging would not have helped, as load balancer rule was specific to prod (staging-api.va.gov)

**Comment by rmtolmach** [comment]
current cors errors 
![image](https://user-images.githubusercontent.com/10993987/229817590-f42e15b2-0714-49e3-a7d7-e2f22695b48f.png)

**Comment by rmtolmach** [comment]
current errors on ff:
![image](https://user-images.githubusercontent.com/10993987/229846743-9ed84e81-aef3-4202-b07d-834f2f0360dd.png)

**Comment by laineymajor** [comment]
Fixed and tested. Good to close.
