### ISSUE TITLE
[ZOOM]: On this page headings are hidden by floating navigation bar when page is zoomed above 150%

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#5624]
## Description

A lot of our medical center pages use the On This Page anchor links to jump to headings further down the page. These headings are being hidden by the floating navigation bar at higher screen zooms. Screenshots attached below.

## Type of Issue
Template

## Point of Contact

**VFS Point of Contact:** _Trevor_

## Acceptance Criteria

- [ ] Headings are not hidden when users click the anchor links at 150% zoom or above

## Environment

* Chrome
* MacOS Mojave
* Server destinations:
  * https://www.va.gov/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/
  * https://www.va.gov/pittsburgh-health-care/locations/h-john-heinz-iii-department-of-veterans-affairs-medical-center/
  * https://www.va.gov/pittsburgh-health-care/locations/beaver-county-va-clinic/
  * https://www.va.gov/pittsburgh-health-care/locations/belmont-county-va-clinic/
  * https://www.va.gov/pittsburgh-health-care/locations/fayette-county-va-clinic/
  * https://www.va.gov/pittsburgh-health-care/locations/washington-county-va-clinic/
  * https://www.va.gov/pittsburgh-health-care/locations/westmoreland-county-va-clinic/
  * https://www.va.gov/pittsburgh-health-care/health-services/
  * https://www.va.gov/pittsburgh-health-care/about/
  * https://www.va.gov/pittsburgh-health-care/mission-vision/
  * https://www.va.gov/pittsburgh-health-care/mission-vision/
  * https://www.va.gov/pittsburgh-health-care/work-with-us/
  * https://www.va.gov/pittsburgh-health-care/work-with-us/internships-fellowships/
  * https://www.va.gov/pittsburgh-health-care/programs/
  * https://www.va.gov/pittsburgh-health-care/programs/pirate-program-for-intensive-residential-aphasia-treatment-education/
  * https://www.va.gov/pittsburgh-health-care/research/
  * https://www.va.gov/pittsburgh-health-care/research/geriatric-research-education-and-clinical-center-grecc/
  * https://www.va.gov/pittsburgh-health-care/research/safety-security/
  * https://www.va.gov/pittsburgh-health-care/policies/
  * https://www.va.gov/pittsburgh-health-care/contact-us/

## Steps to Recreate

1. Enter a server destination from above
2. Set browser width to exactly 1280px
3. Press `Ctrl + Plus` to zoom in. Zoom to at least 175%, 200% or more would be best
4. Click one of the On this page links
5. Verify the heading is hidden behind the blue floating navigation bar

## Possible Fixes (optional)
This may be a tricky thing to correct without design changes, or JavaScript to "offset" the headings when users have zoomed in. Exploration may be in order to know zoom levels or mobile device detection.

## WCAG or Vendor Guidance (optional)

* [Understanding Success Criterion 1.4.10: Reflow](https://www.w3.org/WAI/WCAG21/Understanding/reflow.html)

## Screenshots or Trace Logs

![Screen Shot 2020-02-06 at 12.17.40 PM.png](https://images.zenhubusercontent.com/5ac217b74b5806bc2bcd3fc8/9d17b482-a562-493e-8183-eda0e86f3532)

---
![Screen Shot 2020-02-06 at 12.17.52 PM.png](https://images.zenhubusercontent.com/5ac217b74b5806bc2bcd3fc8/2bcfefd1-e5d7-4d6e-8944-cb581d16aed4)

**Comment by mmiddaugh** [comment]
@jenstrickland this may be resolved with the new left nav....will it be possible to confirm when you do the staging review?

**Comment by jenstrickland** [comment]
Yes, that would be helpful to check during the staging review, https://github.com/department-of-veterans-affairs/va.gov-team/issues/8485.

**Comment by mmiddaugh** [comment]
@jenstrickland and @1Copenut this is ready for your review

**Comment by jenstrickland** [comment]
Fix validated.
