### ISSUE TITLE
Redirect Request: Beta all claims URL

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#5626]
### Instructions
- Requests for redirects need to be submitted **AT LEAST** 2 weeks in advance.  Some redirects take significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation of the redirect to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders of pending redirect.  

### Description
*This is a detailed description of the request. It should include background information and reason for the request.*

### Requestor Info
*Indicate what team and who the primary contact on that team is*

### Implementation Date
Date new URL(s) will be live: *enter date new pages/URLs will be live*

Please indicate when the redirect(s) needs to be implemented"
- [ ] On the same date the new URLs launch
- [ ] Can happen within 1-5 business days after new URLs launch
- [x] Other - Please indicate timing : any time

**The requesting team is responsible for notifying the group working on this issue if the target date changes. They are also responsible for ensuring the destination URLs are implemented correctly and live at the time the redirects are deployed.**

### Redirects Needed

Current URL  |  Redirect Destination (new URL)
---  |  ---
https://www.va.gov/beta-enrollment/all-claims/ | https://www.va.gov/disability/how-to-file-claim/

### Steps to complete
- [x] Above information is provided and issue is tagged and assigned appropriately - *@ requesting team*
- [x] All appropriate VA stakeholders are notified of pending redirect - **n/a-internal**
- [x] Redirect request is vetted and documented and implementation plan is clear - *@ Content & IA team*
- [x] Request is assigned to appropriate team for implementation - *@ Content & IA team*
- [ ] Implementation team completes work - *@ Implementation team*
- [ ] Implementation pushed live and redirect is validated in production - *@ all*
- [ ] Ticket is closed - *@ requesting team*

**Comment by mnorthuis** [comment]
@lunascoop This redirect request is being initiated by my, its internal so no stakeholder communication is needed and it can be implemented when your team is ready.

**Comment by lunascoop** [comment]
@ncksllvn do you think we can get this redirect implemented before sprint ends next Tuesday? No seven-day hold is necessary since this is not a legacy page redirect.

**Comment by ncksllvn** [comment]
@lunascoop Yep! Just opened a PR for it. Should be good to go by then.

**Comment by ncksllvn** [comment]
@mnorthuis there is also https://www.va.gov/beta-enrollment/claims-increase. Should we redirect that as well?

Both of these pages are also in vagov-content still, so we should delete them eventually - https://github.com/department-of-veterans-affairs/vagov-content/tree/master/pages/beta-enrollment

**Comment by mnorthuis** [comment]
I'm not sure if we usually delete the content off GH, so i'll leave that up to your team to determine.

**Comment by ncksllvn** [comment]
@mnorthuis Deleting things off of GitHub is one of our favorite things to do 😄 It'll still be recoverable in GitHub history though.

**Comment by lunascoop** [comment]
Redirect live and validated. Closing ticket.
