### ISSUE TITLE
[FE] Audit Cypress Screenshots & Tests

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#56279]
## Tasks
- Audit Cypress Screenshots & Tests

**Comment by brianseek** [comment]
@loripusey this is ready for validation. The latest screenshots are in this thread (zenhub won't let me upload them here because it is too big) https://dsva.slack.com/archives/C022AC2STBM/p1681252363529909

**Comment by loripusey** [comment]
Looks good from what I can tell, closing.
