### ISSUE TITLE
526ez | Non-retryable errors not triggering a backup submission

### ISSUE THREAD

**Issue by kylesoskin** [department-of-veterans-affairs/va.gov-team#56284]
Current Issues being tracked: 

# Non-retryable errors not triggering a backup submission

- Fixed but still monitoring/keeping an eye on
- Awaiting EVSS validation relaxing to then confirm that backup claims do not hit validation errors when attempting to generate a PDF for a backup submission

# Historical Claims

- Batch 1 - ~19,000 claims generated PDF representations of, and delivered to VA, they are awaiting more guidance before processing
- Batch 2 - ~15,000 claims fail for the same reason as the backup submission failures, validation errors from EVSS getPDF endpoint. Awaiting relaxing of validation on that endpoint to gather these 
- Batch 3 - ~3,000 claims are what I am calling "wild-card" claims. They are failing for various other reasons and will need further evaluation before processing/generating PDF representations for the VA
- Batch 4 - ~700 claims are from the point of ceasing to keep track weekly of claims to release of the backup solution. It is undecided what will be done with these. At one point we considered just submitting them all via the backup PDF path, but there is/was concern over cost of doing so to the SURGE manual processing team. 
- Batch 5 - ~1300 claims that errored from the time of the release of the backup claim submission path, to now. It is also undecided how these will be worked, but assumed to be treated like previous batches. 

# Other notes

- New benefits team in in-charge of fixing client-side/front-end validation errors and has that in their pipeline I think.

**Comment by kylesoskin** [comment]
- note to self, break this up into multiple, less crappy tickets (1 per batch and one for the "Non-retryable errors not triggering a backup submission", or this one can stay that one after the others are broke out)
- Find template @data-doge used for his and copy that.

**Comment by saderagsdale** [comment]
@kyle to set aside time to break down work from each batch.

**Comment by saderagsdale** [comment]
@kylesoskin are we still validating this?
