### ISSUE TITLE
[Spike] Make SubmitForm686cJob and SubmitForm674Job idempotent

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#56285]
## Issue Description

Form 686c submission can fail for any number of reasons. Some failures (e.g. 503s or 504s from BGS) are intermittent and should be retried until they succeed. However, these jobs are not idempotent. Running them multiple times will result in duplicate requests, records, emails, etc. We need to ensure that there are no consequences to retrying these jobs. That is the aim of this ticket.

Technical discovery is required to provide a complexity estimate. Given the number of BGS requests we're making, I have a feeling that this could get complicated. My preliminary estimate is an 8.

---
## Tasks
- [x] Survey both jobs and looks for calls that cannot be made more than once (technical discovery)

## Acceptance Criteria
- [x] Document follow on work in #65052 
---

**Comment by tblackwe** [comment]
@evansmith can you please take lead on researching this design change

**Comment by tblackwe** [comment]
@evansmith can you please take lead on researching this design change

**Comment by steele-lm** [comment]
Clarifying the boundary of the issue between our team and BGS.

**Comment by tblackwe** [comment]
Copying some slack updates here so we don't lose them

From Evan:

> where I'm really digging into at the moment is at what point we can't resubmit because items have been created in BGS. within the form686c (and 674) calls that are submitted in the enqueued jobs are several calls over to BGS creating: VnpVeteran, VnpBenefitClaim, BenefitClaim, as well as Dependents, Marriages, Children, and Relationships (these are BGS defined models).
I'm wondering if there's any way to retain the generated ids in our system somewhere (a new model perhaps?) so that on each form submission we dont re-create VnpVeteran, VnpBenefitClaim etc

> so i'm investigating that what it would take to retain those ids

Once Evan finishes discovery on this ticket, we will estimate the implementation and provide a completion timeline of #56290

**Comment by tblackwe** [comment]
After conversations with RBPS I feel making these Idempotent is the correct course of action. there is too much uncertainty around how the job will be processed and we could inadvertently cause a VSR to process the same info 15 times.

**Comment by tblackwe** [comment]
After many more conversations with RBPS (thanks Linda!) I'm reversing course. Any of the `Vnp` objects created are used by RPBS and can be recreated several times without negative impact.

only the `BenefitClaim` object should be a singleton. Updating #65052 to reflect the decision points.
