### ISSUE TITLE
Sidekiq Admin UI Access Request

### ISSUE THREAD

**Issue by acovrig** [department-of-veterans-affairs/va.gov-team#56321]
#### Access to the Sidekiq Admin UI is managed through a GitHub Teams per environment via the following teams: 
- [Dev](https://github.com/orgs/department-of-veterans-affairs/teams/va-gov-sidekiq-dev)
- [Staging](https://github.com/orgs/department-of-veterans-affairs/teams/va-gov-sidekiq-staging)
- [Sandbox](https://github.com/orgs/department-of-veterans-affairs/teams/va-gov-sidekiq-sandbox)
- [Prod](https://github.com/orgs/department-of-veterans-affairs/teams/va-gov-sidekiq-prod)

_Please provide your GitHub username to be added to that team, along with a reason access is required and which environments you're requesting access to._

- GitHub username: `acovrig`
- Reason access is required: Team Dash Production Support - Team Dash runs the Claims API within Lighthouse and we require access to troubleshoot issues and support the Claims API in general.
- Environments requesting access to: All

**Comment by rjohnson2011** [comment]
Access granted to dev, staging, sandbox environments.

Awaiting OCTODE approval for production access.

**Comment by ryan-mcneil** [comment]
@acovrig You've been granted access to all environments, with access to Production limited to 6 months, expiring 11/5/23

**Comment by ryan-mcneil** [comment]
Slack Reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1683306253505709)

**Comment by bdech** [comment]
@acovrig Your Sidekiq Admin UI Production access has expired. Would you like to request an extension of access?

**Comment by acovrig** [comment]
> @acovrig Your Sidekiq Admin UI Production access has expired. Would you like to request an extension of access?

Yes, please

**Comment by bdech** [comment]
@acovrig your Production access has been extended for 6 months, expiring 05/06/24. Please set a reminder for yourself to return to this Issue and re-request access within 1 week of the expiration date. You'll receive 1 reminder with a 72 hour window to respond. Failure to do so will result in lost access and will require you to fill out a new request.

**Comment by bdech** [comment]
slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1699303728229909)

**Comment by bdech** [comment]
@LindseySaari @ph-One @ericboehs can one of you please give us a :thumbsup: to extend their access?
