### ISSUE TITLE
Vets-api terminal access for Alex Wilson

### ISSUE THREAD

**Issue by FonzMP** [department-of-veterans-affairs/va.gov-team#56322]
### E-QIP Transmittal Date

- [x] Check this box if you have an E-QIP transmittal date.

Sept 23, 2020

### Your Name

Alex Wilson

### Your GitHub handle (terminal access is managed through GitHub)

FonzMP

### Team, Role, and Company of the target individual

Team Dash - Technical Lead - Oddball

### Product Manager (PM) name and email

Kayla Watanabe

### Product Owner (PO) name and email

Janet Coutinho

### Your dsvagovcloud AWS user name (if applicable)

Alex.Wilson

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### COR Name (leave "None" if you listed an AWS user name above)

Cecila Lee

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

Oddball - Amber Malcolm

### Access Expiration

ongoing

### Additional Notes

Would like to obtain access to all environments. We have to manually resubmit failed Claim Submissions to EVSS and BGS from within Dash and working with Platform-Support is an additional step that we would like to bypass to troubleshoot and update submissions. It would be best if an individual more aligned with the code were updating and running resubmissions.

### User must exist in a roster before vets-api terminal access can be granted

- [ ] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added
- [ ] If they included an AWS user name, check to see if their user name is listed in [iam_users.tf](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf)
- [ ] Comment in this issue saying which roster the user is listed in and confirming their AWS user name (if applicable)

**Comment by ryan-mcneil** [comment]
@FonzMP Access for your AWS user `Alex.Wilson` for `prod` needs approval by OCTODE. 

Access has been granted to the `dev`, `staging`, and `sandbox` environments.

Here's some additional documentation for the [Vets API on EKS](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-TerminalAccess)

**Comment by ryan-mcneil** [comment]
@FonzMP See Bill's comment ^^

**Comment by ryan-mcneil** [comment]
@FonzMP I went ahead and granted prod access for 3 months (July 17). If you need it longer, please reopen and provide an EQIP date and we'll get Bill to approve

**Comment by ryan-mcneil** [comment]
Slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1681766799845259)

**Comment by jknipes** [comment]
@FonzMP your ArgoCD/vets-api Production access has been extended for 3 months, expiring 10/24/23. Please set a reminder for yourself to return to this Issue and re-request access within 1 week of the expiration date. You'll receive 1 reminder with a 48 hour window to respond. Failure to do so will result in lost access and will require you to fill out a new request.

**Comment by jknipes** [comment]
Support reminder [HERE](https://dsva.slack.com/archives/C02RLAUM2LV/p1690234707830929)

**Comment by jknipes** [comment]
@FonzMP Your vets-api terminal Production access has expired.

Would you like to request an extension? You have 72 hours to respond, or your
access will be revoked and you will need to fill out a new request.

**Comment by FonzMP** [comment]
@jknipes yes - please extend.

**Comment by jknipes** [comment]
@FonzMP Extension of access for your AWS user Alex.Wilson for prod will be reviewed for approval by OCTODE.

**Comment by bdech** [comment]
@LindseySaari @ericboehs can one of you please give us a :thumbsup: to extend their access?

**Comment by bdech** [comment]
@FonzMP Your ArgoCD/vets-api Production access has been extended for 6 months, expiring 5/2/24. Please set a reminder for yourself to return to this Issue and re-request access within 1 week of the expiration date. You'll receive 1 reminder with a 72 hour window to respond. Failure to do so will result in lost access and will require you to fill out a new request.

**Comment by bdech** [comment]
Slack Reminder [Here](https://dsva.slack.com/archives/C02RLAUM2LV/p1698949138976459)

**Comment by lindsay-insco** [comment]
@FonzMP Your vets-api terminal Production access has expired.

Would you like to request an extension? You have 72 hours to respond, or your
access will be revoked and you will need to fill out a new request

**Comment by lindsay-insco** [comment]
@FonzMP it has been 72 hours with no response. Vets-API access has been removed.

If you need continued access please fill out a new request [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=external-request%2Cplatform-tech-team-support%2Cops-access-request&template=vetsapi-argo-terminal-access.yaml&title=Vets-api+terminal+access+for+%5Bindividual%5D)

**Comment by FonzMP** [comment]
Ahhh. I seem to miss these pings. Any way I could get access reinstated @lindsay-insco ? I need production access for troubleshooting issues with our new 526 Disability Compensation Claims service that VA.gov just launched.

**Comment by bdech** [comment]
@LindseySaari @ericboehs can one of you please give us a :thumbsup: to extend their access?

**Comment by FonzMP** [comment]
bumping to see if I can extend access - sorry for introducing this hiccup.

**Comment by FonzMP** [comment]
@bdech any additional steps I need to take here? or should I restart the process from a fresh issue?

**Comment by bdech** [comment]
@FonzMP, Let's start with a fresh issue. You still have access to lower environments. It will just be production that we will need to go through the approval process again.
