### ISSUE TITLE
Assess monitoring and logging for our S2 products and tools list 

### ISSUE THREAD

**Issue by sortizsh** [department-of-veterans-affairs/va.gov-team#56337]
- Check what does and does not have logging and monitoring in place
- Discuss setting engineering expectations (capacity, prioritization, etc.)with Matt and Steve

Tasks:
- [x] Create a list of items in our portfolio that are or are not logged and monitored ([use this as a starting point](https://docs.google.com/spreadsheets/d/1pCFp-jGq6Pr49mcSgv3uRIVVPBPSISuc82fE_ugZb4E/edit#gid=1300771074))
- [x] Share plan internally with the development team ([draft here](https://docs.google.com/document/d/1TqBQmbYGF7Xvjzs_2q83qDuoKd9022n153wVl8V4MmI/edit))
- [x] Share externally with Matt Self and Steve Albers

**Comment by jaredcunha** [comment]
@sortizsh can we make the [portfolio spreadsheet](https://docs.google.com/spreadsheets/d/1pCFp-jGq6Pr49mcSgv3uRIVVPBPSISuc82fE_ugZb4E/edit#gid=1300771074) is up to date?

**Comment by saderagsdale** [comment]
@jaredcunha here’s the new version: https://docs.google.com/spreadsheets/d/1fr7DRsJfl9X61C7859YzOiN8Zj_kJOMaRtajYWIaYvg/edit?usp=sharing
