### ISSUE TITLE
Address the Backlog of Issues Requesting Changes for PD

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#56345]
# Description

Quite a backlog of PD issues has been established [here](https://github.com/department-of-veterans-affairs/product-directory/issues).

We should resolve these issues in the near future.

# Acceptance Criteria
- [ ] The requested changes represented by the backlog of tickets have been resolved

**Comment by CBonade** [comment]
All caught up!
