### ISSUE TITLE
Revisit Kube Cluster

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#56349]
https://dsva.slack.com/archives/C30LCU8S3/p1680720669388619

ACTION
- [ ] ensure alert only fires for web and BGS pods

**Comment by laineymajor** [comment]
This ticket will be reprioritized around the time TT1 reaches 100% migration.

**Comment by RachalCassity** [comment]
Look into today

**Comment by laineymajor** [comment]
@RachalCassity I know other things have come up as higher priority... just checking in on this. Let me know if this is something you think/want Ryan to assist with.

**Comment by RachalCassity** [comment]
Addressing this issue in this slack [thread](https://oddball.slack.com/archives/C045LCF8WU8/p1682101037599929)

**Comment by RachalCassity** [comment]
More deployments have been added to vets-api. This issue was made when we did not have multiple bulk head deployments and we were testing wildcard routing
