### ISSUE TITLE
Add ID.me button and language to organic modal

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#56353]
An initial pass at the "organic experiment" modal was merged in. This ticket requests that the modal include language and an additional button to include ID.me as an option for creating a verified account.

Previous ticket: https://github.com/department-of-veterans-affairs/vets-website/pull/23695

**Comment by asg5704** [comment]
@kingbmike @joeniquette I believe the "organic modal" does not exist anymore on the FE. This ticket should be closed.
