### ISSUE TITLE
Provide additional information about screener questions

### ISSUE THREAD

**Issue by rbsingleton** [department-of-veterans-affairs/va.gov-team#56365]
### Description
It appears that, as Perigean uses Calendly to send out screener surveys and sign participants up to participate in research sessions, that researchers are limited to only 6 screener questions. If they go over 6 screener questions, Perigean will combine screener questions. It would be helpful if this information was included in the "Write Screener Questions" portion of the "Writing Your Research Plan" section. Thank you!

### Which type of team are you on? (Platform team, VFS team, or Leadership)
VFS team

**Comment by vbellissimo** [comment]
@rbsingleton, thanks for your submission Robyn.

@naomimarcussen, can you please take a look and let us know if you would like to add this content to the website where necessary? Thank you!

**Comment by naomimarcussen** [comment]
Thank you for this @rbsingleton! I'll update the Participant recruitment section of the [Research checklist](https://depo-platform-documentation.scrollhelp.site/research-design/research-checklist), then work with Shane to get the language approved.

**Comment by naomimarcussen** [comment]
These changes have been approved by Shane Strassberg and published in the [research checklist](https://depo-platform-documentation.scrollhelp.site/research-design/research-checklist).
