### ISSUE TITLE
SOCKS access for Gia Antoniades

### ISSUE THREAD

**Issue by gia-lexa** [department-of-veterans-affairs/va.gov-team#56373]
### Your Name

Gia Antoniades

### Your Email

gia.antoniades@adhocteam.us

### Your Role and Team

Backend Engineer / Tech Team 4

### Product Manager (PM) name and email

Joseph Tice: joe.tice@oddball.io

### Product Owner (PO) name and email

Joseph Tice: joe.tice@oddball.io

### Access Type Requesting

platform

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC61Qu0msBrmhdGDuBbIaWxBOP3IJkdcy68snu31R4PU6OJw6oNTVDHhmFySgXwZFHImtoMbqk2R9vS9f9h64lKTxXuYockzuvZn0g0Drmtli+DMUmUlRLZnzL6H2J+5EJEaQVFwZRvKnZJ2d6gD+D6x9/AndMiLHXtb4q0OKNEVANvmKuLS/m/ObD0wz/lk0hs83Wt4YSGQZ33R+bvNC+wFL942PeGx6e1+U9DE2tj/0w9lRWGXLxlFMJyEA3yYAh2wIHbErSPgGLIjWXsyFQNh8SK7nDeZ/XZ0Y6jeRzMBbxGcYo7ERYEREMKWQV6ut1QjNz6DiWa20KtuoXnYS8Z5uvcxjGn1MCvLfbRDW6EBy3zoqBTw1br5UL+Fr23arWb7ewbiMSJZR7ah1OKs+TZnL8QfRK7a4wIKHrjTYHcAUrqHkOPvoPXrwIVZmjAzvcJTIv48Lqw9Ss+W21hjethP9ksotrDPgfsLDGk5ypppB8fCfAa1IutGJJ4bFpJqg0= giaantoniades@Gias-MacBook-Pro.local

### E-QIP Transmittal Confirmation

<img width="810" alt="eqiptransmittal" src="https://user-images.githubusercontent.com/103389320/230216964-830086d2-4138-4ea8-953f-5b5c18548966.png">

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [x] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by little-oddball** [comment]
Platform Roster.
