### ISSUE TITLE
Spike: Infographic for Verified Account

### ISSUE THREAD

**Issue by kingbmike** [department-of-veterans-affairs/va.gov-team#56374]
As a user who is attempting to access VA.gov tasks, I need to create a verified account in order to complete more complex functions e.g. ________ & __________.  Without verifying my account, I am limited to _________ actions.  

**Assumptions**
- Users are limited in the tasks they are able to complete with a _standard_ | _basic_ account.
- An infographic will steer users to create a verified account.
- Users don't know why they need a verified account.

**Tasks**
[ ]  Define a verified account
[ ]  Clearly articulate what users can access with a verified accounts.

**Questions**
- Where will this infographic reside? Wherever sitewide decides is most appropriate

**Comment by charlye-bluetiger** [comment]
this ticket is paused for the time being while Proactive Adoption research is being completed.  The outcome of the study will inform upcoming solutions.

**Comment by aparsley** [comment]
This infographic will be paired with the Video for Verification.

**Comment by aparsley** [comment]
@APorter-Clarity Attach artifacts

**Comment by charlye-bluetiger** [comment]
[Copy for Infographic](https://docs.google.com/document/d/11utJLfHQ2S2HrHqUoxcCgWvl6aY0L0W9rr7i4zw4OSQ/edit)

**Comment by aparsley** [comment]
Working on hard copy, thank you for going over items.
