### ISSUE TITLE
Vets-api terminal access for Kyle Soskin

### ISSUE THREAD

**Issue by kylesoskin** [department-of-veterans-affairs/va.gov-team#56386]
### E-QIP Transmittal Date

- [ ] Check this box if you have an E-QIP transmittal date.

### Your Name

Kyle Soskin

### Your GitHub handle (terminal access is managed through GitHub)

@kylesoskin

### Team, Role, and Company of the target individual

Benefits - Decision Reviews Team - Senior Backend Software Engineer

### Product Manager (PM) name and email

Sade Ragsdale <sade.ragsdale@va.gov>

### Product Owner (PO) name and email

Matthew Self <Matthew.Self2@va.gov>

### Your dsvagovcloud AWS user name (if applicable)

Kyle.Soskin

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### COR Name (leave "None" if you listed an AWS user name above)

None

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

None

### Access Expiration

ongoing

### Additional Notes

I used terminal access in all environments everyday for day-to-day work activities including:

- Troubleshooting production issues
- Gathering data for VBA from our databases
- Testing code snippets in lower environments

I currently have on-going existing access in AWS, and need to retain that same access. 

### User must exist in a roster before vets-api terminal access can be granted

- [ ] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added
- [x] If they included an AWS user name, check to see if their user name is listed in [iam_users.tf](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf)
- [ ] Comment in this issue saying which roster the user is listed in and confirming their AWS user name (if applicable)

**Comment by ryan-mcneil** [comment]
@kylesoskin you have been granted access to `sandbox`, `dev`, and `staging`. `production` access is pending, and we will update you as soon as it's available.

**Comment by ryan-mcneil** [comment]
Added Access Expiration for 3 months from now, July 11.

Slack reminder [here](https://oddball.slack.com/archives/C0459AQ5GBT/p1681247183347669)

**Comment by bdech** [comment]
@kylesoskin  your ArgoCD/vets-api Production access has been extended for 3 months, expiring 10/11/23. Please set a reminder for yourself to return to this Issue and re-request access within 1 week of the expiration date. You'll receive 1 reminder with a 48 hour window to respond. Failure to do so will result in lost access and will require you to fill out a new request.

**Comment by bdech** [comment]
slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1689252883109439)

**Comment by bdech** [comment]
@kylesoskin Vets-api Production access has expired.

Would you like to request an extension? You have 72 hours to respond, or your
access will be revoked and you will need to fill out a new request.
