### ISSUE TITLE
Setup Repository for SiS Auth Library

### ISSUE THREAD

**Issue by mjconw3** [department-of-veterans-affairs/va.gov-team#56393]
## Description

We want to migrate our auth library for SiS. The first step in doing this is to create and setup the repo where the library will live.

## Acceptance Criteria:

- [x] The repo is created within Github
  - [x] The repo should be listed as Private with only Identity team currently, will move to Internal & Public later on
  - [x] The repo should be a part of the Dept. of Veterans Affairs organization
- [x] The repo is properly configured to meet team/developer needs (aka access control for Identity team only)
- [x] The location of the new repo is properly communicated to the team in the identity-engineers

**Comment by acald-creator** [comment]
Created `identity-sdk` empty repository.
- Listed as Private
- Part of Dept. of VA org

Next steps
- Configure permissions
- Add content for communication

**Comment by acald-creator** [comment]
Also created `identity-dashboard-fe` last Friday as a Next.js app
- Listed Private
- Part of Dept. of VA org

Next steps
- Configure permissions
- Update `README.md`

**Comment by acald-creator** [comment]
Updated permissions to allow `vsp-identity` admin access to the two repos
