### ISSUE TITLE
(Identity Auth Library - FE) Spike: Look into using web components for SiS Auth library

### ISSUE THREAD

**Issue by mjconw3** [department-of-veterans-affairs/va.gov-team#56399]
## Description

As a part of migrating our auth library for SiS, we want to investigate migrating to web components. This will allow for faster, reliable code on the Web. 

## Tech Notes
- Look into Lit or Rust WASM
- [Lit](https://lit.dev/)
- [Rust WASM](https://rustwasm.github.io/book/)

## Acceptance Criteria:

- [ ] Document benefits and risks of different web components we are investigating
- [ ] Based on research, recommend the best web component tool for our project/team
- [ ] Review finding with appropriate team members
- [ ] Follow on tasking is decided on/created

**Comment by asg5704** [comment]
@kingbmike This can be moved to backlog
