### ISSUE TITLE
CT 116: Deliver SCO Contact Details for non VET TEC providers to production

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#5639]
As a developer, I need to remove the production / feature flag for the SCO contact details so that the information is available in production.

## Assumptions:
1. UX has reviewed the changes and signed off as of 02/19/20.
2. EDU has reviewed the changes and signed off as of 02/18/20.

## Acceptance Criteria:
1. The work completed in #5362 is delivered to the production environment.

**Comment by desireeturner** [comment]
Received approval to go live with these changes on the EDU call on 2/24.

**Comment by delli-gatti-michael** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/11763/files

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
Changes are live in Production. Closing this issue
