### ISSUE TITLE
Contact center metrics from login.gov/id.me

### ISSUE THREAD

**Issue by mjconw3** [department-of-veterans-affairs/va.gov-team#56391]
## Description

Login.gov currently has a feedback/contact us page where users can submit issues and provide input on their experience within the site. We want to get some information and data on their feedback specifically as it pertains to verification and account creation. Additionally, we want to investigate if we can obtain similar data from ID.me.

## Acceptance Criteria:

- [x] Get current available data from login.gov contact center
- [x] Reach out to Sierra Steward and Rachel Houghton for additional raw data (specifically for verification and account creation)
- [ ] Once data is received, create follow on ticket to conduct research/analyze the data to see how we can better address this feedback

**Comment by mjconw3** [comment]
![VA Average Business Hours to Close (Last Month) (1).png](https://images.zenhubusercontent.com/63d82bd584d18ab0a74a5985/67f927f8-ea1c-46e8-863d-1ecebbfd99ae)![VA Not Login.gov Case Topic by Sub Topic (Last Month) (1).png](https://images.zenhubusercontent.com/63d82bd584d18ab0a74a5985/df477e56-e703-4056-98db-6c004e8e6682)![VA Cases by Case Origin (Last Month) (1).png](https://images.zenhubusercontent.com/63d82bd584d18ab0a74a5985/fa2a10e2-246a-4d4f-ad10-12b6936bda42)![VA Case Sub Topics (Last Month) (1).png](https://images.zenhubusercontent.com/63d82bd584d18ab0a74a5985/17e1e75f-b83e-48f6-aa54-c82878b80cc5)![VA Case Topics (Last Month) (1).png](https://images.zenhubusercontent.com/63d82bd584d18ab0a74a5985/63cd15d1-5b21-44c4-90dd-ca709c7e5309)

**Comment by kingbmike** [comment]
[https://app.zenhub.com/files/133843125/7b833caa-004e-41a3-911a-a0ae2ab40e1c/download](https://app.zenhub.com/files/133843125/7b833caa-004e-41a3-911a-a0ae2ab40e1c/download)[https://app.zenhub.com/files/133843125/0f249eb4-b601-4ea8-a005-b495b235e487/download](https://app.zenhub.com/files/133843125/0f249eb4-b601-4ea8-a005-b495b235e487/download)

**Comment by kingbmike** [comment]
Received the above stats/info from login.gov and will be creating new tasking from this.
