### ISSUE TITLE
Adding Andrew Lazarek to DSVA Slack

### ISSUE THREAD

**Issue by huggins-va** [department-of-veterans-affairs/va.gov-team#56403]
Good morning, 

Please add Andrew Lazarek

alazarek@take2it.com

as a multi-user to the following channels:  
vaapi-platform & team-honeybadgers-support

Thank you

**Comment by LEHigley** [comment]
i think multi-user is multi-channel guest so that's the account type i used

i don't have access to either of those channels so just invited to general to get the invite out--you will have to add to those 2 specific channels

thanks!
