### ISSUE TITLE
[Datadog] Develop process and guidance for deploying Platform Monitors & Alerts using Infrastructure as Code (IaC)

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#56406]
## Description 
We need to de-risk providing write access to Datadog for VFS teams by putting Platform Monitors and Alerts into Infrastructure as Code (IaC). 

This can also serve to provide a framework for VFS teams to follow so that they can deploy their own Datadog resources using IaC. 

## Background/context 
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/55034
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/33081

## Resources
- https://vfs.atlassian.net/wiki/spaces/OT/pages/2490761544/Datadog+Terraform+Modules
- https://github.com/department-of-veterans-affairs/terraform-dd-eks-module

## Things to consider 
- Evaluate export from Datadog 
- Test it, ie terraform plan 
- Clean up data as needed 
- Test overwriting existing resources 
- What's the impact on evaluation data? 
  - is this a complete overwrite? 
  - or an update? 
- Is there a benefit to using Ansible vs Terraform? 
- Tagging! 
- We might scope this to _only_ dashboards, monitors, or alerts 

## Definition of Done 
- Identify what things should be in IaC
- Relevant Datadog resources (created by PTT2) have been written to IaC (list TBD) 
- Testing the impact on monitoring data when writing resources to Datadog using IaC
- Documentation exists for the following: 
  - How to export resources
  - How to deploy resources
  - Guidelines, standards, best practice(s) 
  - Working instructions, ie step-by-step 
- Establish the process to synchronize IaC w/ Datadog UI 
- Explore automating the synchronization of IaC w/ Datadog UI on a regular interval 
_- Demo at End of Sprint demo :)_

**Comment by jhouse-solvd** [comment]
Should we just focus on getting our own dashboard(s) into IaC? Maybe that's a lean approach?

**Comment by npeterson54** [comment]
All existing monitors that we created are in TF, closing out
