### ISSUE TITLE
Qualitative Data Request

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#56407]
### Data Type Requested

Support

### Date Range Start

03-27-2023

### Date Range End

Latest

### Product Name(s)

MHV on VA.gov (Authenticated landing page)

### Product Description

The MHV on VA.gov effort represents a large body of work to re-platform My HealtheVet health tools onto VA.gov Part of that effort is a new authenticated landing page (va.gov/my-health) where everything is connected together. This page went live on 3/27.

## URLs
ONLY: /my-health
ONLY: /resources/my-healthevet-on-vagov-what-to-know/

## Terms
- "My HealtheVet on VA.gov"
- "MHV home page"

### File Delivery Format

All in one file, on one tab

### VA Email Address(es)

patrick.bateman@va.gov

### Add Assignee and Labels

If not already done so, please ensure @ianMcCullough-ob is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by ianMcCullough-ob** [comment]
Will be using the following categories:

Navigation Issues	Secure Messaging
Navigation Issues	Header and Footer Info
Inability to Access Tool	Secure Messaging

**Comment by ianMcCullough-ob** [comment]
Hey @batemapf, just shared an export for you. Not sure if there's anything useful in there, but might be able to search within the case notes to see if anything relevant is mentioned.

Reach out through Slack if you have any questions. Thanks!
