### ISSUE TITLE
Vets-api terminal access for [Nathan Wright]

### ISSUE THREAD

**Issue by nathanbwright** [department-of-veterans-affairs/va.gov-team#56410]
### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Nathan Wright

### Your GitHub handle (terminal access is managed through GitHub)

nathanbwright

### Team, Role, and Company of the target individual

VA Notify Forms Strike Team - Eng lead (Oddball)

### Product Manager (PM) name and email

Zack Law zack.law@oddball.io

### Product Owner (PO) name and email

Beverly Nelson beverly.nelson@va.gov

### Your dsvagovcloud AWS user name (if applicable)

Nathan.Wright

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [x] production (if requesting, justify prod access in 'Additional Notes' section)

### COR Name (leave "None" if you listed an AWS user name above)

None

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

None

### Access Expiration

ongoing

### Additional Notes

Need access for developing and maintaining VaNotify email notifications and reminders within vet-api.

### User must exist in a roster before vets-api terminal access can be granted

- [ ] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added
- [ ] If they included an AWS user name, check to see if their user name is listed in [iam_users.tf](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf)
- [ ] Comment in this issue saying which roster the user is listed in and confirming their AWS user name (if applicable)

**Comment by jeremy6d** [comment]
@nathanbwright Your AWS user Nathan.Wright has been given access to the dev, staging, and sandbox environments.
Here's some additional documentation for the [Vets API on EKS](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-TerminalAccess)

**Comment by nathanbwright** [comment]
Requesting prod access. Here is my previous prod request (from before EKS): https://github.com/department-of-veterans-affairs/va.gov-team/issues/37955

I'm still in the same role (Eng lead for the VA Notify Forms Strike Team) and having prod access would make debugging issues and rolling out features flags easier (instead of relying on support for everything).

**Comment by rmtolmach** [comment]
✅ I confirmed Nathan has an AWS account and was part of the `"adhoc-vetsgov-ssm-prod"` group, meaning he **has previously been approved for elevated access**.

Example of when Nathan has needed prod access: https://dsva.slack.com/archives/CBU0KDSB1/p1686763309764239

@nathanbwright, I think OCTO will be able to approve this without to much trouble, but _just in case_, can you add a screenshot of your EQIP transmittal email if you can dig it up?

**Comment by nathanbwright** [comment]
Thanks @rmtolmach 

My EQIP was completed under a previous company (B3 Group) and was successfully transferred over to Oddball when I started here. Here is a screenshot from of my transmittal notice:

![Screen Shot 2023-06-14 at 2 32 07 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/4740018/20291986-d031-4dda-8da2-778592c7302a)

**Comment by BillChapmanUSDS** [comment]
Access approved for 3 months as per policy. 

However this particular justification is thin and will possibly not be reapproved in the future.

**Comment by bdech** [comment]
@nathanbwright You've been granted access to Prod for 3 months, expiring 9/21/23

**Comment by bdech** [comment]
slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1687365629356189)

**Comment by bdech** [comment]
@nathanbwright Per an update to our access policy, your ArgoCD/vets-api Production access has been extended for 3 months, expiring 12/21/23. Please set a reminder for yourself to return to this Issue and re-request access within 1 week of the expiration date. You'll receive 1 reminder with a 72 hour window to respond. Failure to do so will result in lost access and will require you to fill out a new request.

**Comment by bdech** [comment]
slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1695305872313489)

**Comment by bdech** [comment]
@nathanbwright Your Vets API Terminal Production access has expired.

Would you like to request an extension? You have 72 hours to respond, or your 
access will be revoked and you will need to fill out a new request.
