### ISSUE TITLE
[FE] CodePen accessibility remediation

### ISSUE THREAD

**Issue by wullaski** [department-of-veterans-affairs/va.gov-team#56416]
## Acceptance Criteria

- [ ] Fix accessibility errors pointed out by axe implementation
- [ ] Create a list of issues for UX to fix where content changes are necessary. ex: aria-labels
- [ ] Remove links to personal codepen assets

**Comment by loripusey** [comment]
@cgednalske can you validate?

**Comment by cgednalske** [comment]
Look good! 👍
