### ISSUE TITLE
Storyboard the views for SiS Dashboard implementation

### ISSUE THREAD

**Issue by mjconw3** [department-of-veterans-affairs/va.gov-team#56428]
## Description

As a developer, I want to storyboard the views for our sign in service dashboard. Login.gov already has a dashboard that we can use as an example or we can create our own. The deliverables for this ticket are agreed upon views/storyboards for our sign in service dashboard.

## Acceptance Criteria

- [x] Review [Trevors Spike](https://app.zenhub.com/workspaces/identity-5f5bab705a94c9001ba33734/issues/gh/department-of-veterans-affairs/va.gov-team/55971) for relevant notes on dashboard views
- [x] Create storyboard for our SiS dashboard views
- [x] Share and review storyboard with appropriate team members for approval
- [x] Follow on tickets and tasking create to engineer and implement views

## Tech Notes
[Identity Dashboard Code for Review](https://github.com/18F/identity-dashboard)
- Do we want to use this same or a similar pattern for our new dashboard?

**Comment by bosawt** [comment]
Sign in Service configuration for client apps, this is the table schema we use to store the configuration:

>   create_table "client_configs", force: :cascade do |t|
    t.string "client_id", null: false
    t.string "authentication", null: false
    t.boolean "anti_csrf", null: false
    t.text "redirect_uri", null: false
    t.interval "access_token_duration", null: false
    t.string "access_token_audience", null: false
    t.interval "refresh_token_duration", null: false
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.text "logout_redirect_uri"
    t.index ["client_id"], name: "index_client_configs_on_client_id", unique: true
  end

**Comment by asg5704** [comment]
Creating views in Figma for Identity dashboard skeleton

**Comment by asg5704** [comment]
Creating views in Figma for Identity dashboard skeleton

**Comment by asg5704** [comment]
Figma (views) https://www.figma.com/file/NgTUQowdoP3TsasZTHiwpu/Identity-Dashboard-(views)?node-id=0%3A1&t=H3My1IsTgKetrggY-1

**Comment by mjconw3** [comment]
Looks good @asg5704. I like the views...gonna close this out for you
