### ISSUE TITLE
(Identity Dashboard) Create schema diagram to describe database associations for users, roles, and client_configurations

### ISSUE THREAD

**Issue by mjconw3** [department-of-veterans-affairs/va.gov-team#56426]
## Description

As a developer, I want to create a schema diagram that we can use to build out a backend data model as it relates to associations for users, roles, etc for our sign in service developer portal. The deliverable for this ticket will be an agreed upon schema diagram that we can then use to begin building out the database.

## Acceptance Criteria 

- [x] Review [Trevors Spike](https://app.zenhub.com/workspaces/identity-5f5bab705a94c9001ba33734/issues/gh/department-of-veterans-affairs/va.gov-team/55971) for key details on how Login.gov currently handles this for ideas on how we can build ours
- [x] Create a diagram outlining the backend and how they relate to each other
- [x] Share and review schema diagram with appropriate team members for approval
- [x] Create follow on tickets for engineering tasks

## Tech Notes

**Comment by bosawt** [comment]
I think this schema flow is the one we will stick with

![image.png](https://images.zenhubusercontent.com/5fb55f12a11eae1f7ca15bde/bf32b408-569a-4267-b923-3734312272f2)
