### ISSUE TITLE
(Identity Dashboard) Create diagram for communication flows between SiS-Dashboard and SiS

### ISSUE THREAD

**Issue by mjconw3** [department-of-veterans-affairs/va.gov-team#56427]
## Description

As a developer, I want to create a diagram that shows the flows of communication between our sign in service dashboard and sign in service itself. The deliverable for this ticket will be an agreed upon diagram and creation of future tasking based on the diagram.

## Acceptance Criteria

- [x] Review [Trevors Spike](https://app.zenhub.com/workspaces/identity-5f5bab705a94c9001ba33734/issues/gh/department-of-veterans-affairs/va.gov-team/55971) to gather necessary background data on our developer dashboard
- [x] Create diagram outlining the flow between our SiS dashboard and SiS
- [ ] Share and review diagram with appropriate team members for approval
- [ ] Define and create follow on tasking for engineers based on the diagram

## Tech Notes

**Comment by bramleyjl** [comment]
This ticket is largely being covered by this [VA Identity Dashboard Authentication scoping ticket](https://app.zenhub.com/workspaces/identity-5f5bab705a94c9001ba33734/issues/gh/department-of-veterans-affairs/va.gov-team-sensitive/981).

These are the diagrams for [VA ID Dashboard / SiS flow](https://lucid.app/lucidchart/c0d9a2d7-0f20-4e48-94e1-87133e7227fe/edit?invitationId=inv_87605cec-f11d-4ac0-b661-6f668ddd8e0a&page=0_0#).
