### ISSUE TITLE
Spike: Recommended frontend in Rails ERB, that leverages much from the login.gov dashboard

### ISSUE THREAD

**Issue by mjconw3** [department-of-veterans-affairs/va.gov-team#56429]
## Description

As a front end developer, I want to decide on what tooling we should use to build the front end for our sign in service developer portal. The Login.gov developer portal uses Rails ERB and we can leverage/utilize what is already in place to begin building our own. That being said, we want to investigate, document and decide if this is the best path forward or if something else should be used. The deliverables for this ticket is a decision and recommendation for a front end and follow on tickets for the engineering related work.

## Acceptance Criteria

- [x] Front end code from Login.gov developer dashboard has been reviewed
- [x] Research on implementation and building based on Rails ERB and/or any other tooling has been done 
- [x] Recommendation has been shared with team and documented
- [x] Follow up tickets and tasking has been discussed and created

## Tech Notes

Provide link to Login.gov github here

**Comment by mjconw3** [comment]
@bosawt do you mind throwing the login.gov github with the rails code you mentioned in here for @asg5704 to take a look at?

**Comment by bosawt** [comment]
Here is the login.gov dashboard GitHub: https://github.com/18F/identity-dashboard

**Comment by asg5704** [comment]
Recommendations:

- No ERB code, takes too long to get up and running for FE people especially if we want to iterate fast
- BE + FE will be in the same repo, however will live in separate folders
- FWA dashboard note options
    - Option 1: Might need to implement a micro-frontend architecture if we accommodate the FWA on the Identity dashboard
    - Option 2: Subdomain the FWA app
    - Option 3: Use something like Astro to allow multipe frameworks (React, Vue, etc)
