### ISSUE TITLE
Midpoint Review - Design Feedback - Digitize Forms - Form 21-4142(a)

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#56433]
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- Thank you for the annotations and flows!

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- Must: remove the address block from the radio button tile
- Consider: moving the info about the person authorizing the release before the authorization
- Consider: adding a save button to the list and loop. Since it is currently this way in production it is likely not a problem but user testing would be great at some point.

**Comment by jeana-adhoc** [comment]
Removed the address from the radio button title. The question now looks like this:
<img width="570" alt="image" src="https://user-images.githubusercontent.com/117098918/230981518-04194b90-1329-427b-887b-0761482b4937.png">

**Comment by jeana-adhoc** [comment]
For now we're not moving the "who is filling out this form question".
1. Too heavy of a current lift for engineers at this time
2. We're going to be testing this placement in future forms (if those prove to be viable we'll suggest that we should come back and change this one)
