### ISSUE TITLE
Higher Level reviewer (HLR) Qualitative Data Request

### ISSUE THREAD

**Issue by uxgary** [department-of-veterans-affairs/va.gov-team#56435]
### Data Type Requested

User Surveys

### Date Range Start

03-01-2022

### Date Range End

03-01-2023

### Product Name(s)

Higher Level reviewer (HLR)

### Product Description

We are looking to learn more about Higher Level reviewer (HLR), including the authenticated form.

With this data we're hoping to establish a baseline satisfaction score, establish a baseline task completion, and identify common questions and pain points.

### Product URL(s) and/or term(s)

**Unauthenticated areas of interest**
https://www.va.gov/decision-reviews/ 
https://www.va.gov/decision-reviews/higher-level-review/
https://www.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996

**Within the actual form**
https://www.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/veteran-information
https://www.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/homeless
https://www.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/contact-information
https://www.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/contestable-issues
https://www.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/add-issue?index=0
https://www.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/area-of-disagreement/0
https://www.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/opt-in
https://www.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/issue-summary
https://www.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/informal-conference
https://www.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/informal-conference/conference-availability
https://www.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/informal-conference/representative-info
https://www.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/review-and-submit

### File Delivery Format

One file, different tab for each term/URL

### VA Email Address(es)

gary.homidas@va.gov
eileen.chi@va.gov
sade.ragsdale@va.gov
eva.floyd@va.gov

### Add Assignee and Labels

If not already done so, please ensure @ianMcCullough-ob is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by ianMcCullough-ob** [comment]
Hey @uxgary and @Evafloyd, just shared the export with you. Reach out via slack with any questions. Thanks!
