### ISSUE TITLE
Adding Lynne Johnson to DSVA Slack

### ISSUE THREAD

**Issue by smythe5** [department-of-veterans-affairs/va.gov-team#56463]
# Descriptions 

Please add Lynne Johnson as a full member.  She is an employee of Agile 6.  She is a Delivery Manager on the My Healthe Vet project.

**Comment by MarciMcGuire** [comment]
Hi!  I am following up on this issue.  Our new Delivery Manager doesn't seem to be able to access DSVA slack yet.  Thanks!

**Comment by LEHigley** [comment]
i'm seeing her in slack are we set here?

**Comment by MarciMcGuire** [comment]
Yep!
