### ISSUE TITLE
Create initial design mockup for "My Payment History"

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#5646]
## Goal
Based on research findings and existing product documentation, we want to create an initial mockup of the feature to start iterating.

## Considerations
There may be more than 1 mockup but the intent will be to share this (these) with Veterans 

## Tasks
- [x] Create a mockup for this feature based on existing research, so that FE engineering can make a first product pass.

## Acceptance Criteria
- [x] A mockup has been created and shared with the team.

**Comment by sporeboy** [comment]
Initial desktop and mobile designs laid out... 
- Desktop version https://xd.adobe.com/view/44399930-6143-4192-6e80-99a0566c4092-3208/screen/5b8c5a45-c694-42a6-b7f2-e2ca01b90916/View-Payments-1
- Mobile version https://xd.adobe.com/view/44399930-6143-4192-6e80-99a0566c4092-3208/screen/51e5fbb5-00cd-42cb-a145-a06e3828135f/View-Payments-Mobile-1

**Comment by sporeboy** [comment]
Elements used for these conceptual screens designs:

- Tool page layout from Rated Disabilities and View Dependents
- USWDS borderless table styling
- VA.gov pagination stepper
- Nick Sullivan's Form Finder results table

Content is meant to mimic translation of eBenefits content to VA.gov conventions.
