### ISSUE TITLE
FEATURE TOGGLES

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#56478]

**Comment by rmtolmach** [comment]
## `/feature_toggles`
- PR merged: https://github.com/department-of-veterans-affairs/devops/pull/12792
- revproxy redeployed

Logs are coming in:
![image](https://user-images.githubusercontent.com/10993987/230628015-eea8080a-77b8-4f65-8742-f99256fb95a5.png)

One concern is increased latency after the cut-over:
![Screenshot 2023-04-07 at 10 55 18 AM](https://user-images.githubusercontent.com/10993987/230630007-956ad479-ae8b-4d23-96d2-f66db5c81553.png)

Are we scaling our pods to prevent this latency? We scale based on the puma backlog. How often is HPA checking that metric? 

Bill Chapman logged into va.gov (as a real user) and, anecdotally, noticed a little slowness, but said it was still "snappy".

**Comment by laineymajor** [comment]
ADDED TO THIS SPRINT AS PART OF THE EKS MIGRATION.
