### ISSUE TITLE
Vets-api terminal access for Raina Huerta

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#56477]
### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Raina Huerta

### Your GitHub handle (terminal access is managed through GitHub)

@rd-huerta

### Team, Role, and Company of the target individual

Virtual Agent Chatbot, Software Developer, Thoughtworks

### Product Manager (PM) name and email

Ian Santarinala ian.santarinala@thoughtworks.com

### Product Owner (PO) name and email

Luciana Morais Luciana.Morais@va.gov

### Your dsvagovcloud AWS user name (if applicable)

Raina.Huerta

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [ ] sandbox
- [ ] production (if requesting, justify prod access in 'Additional Notes' section)

### COR Name (leave "None" if you listed an AWS user name above)

None

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

None

### Access Expiration

ongoing

### Additional Notes

- Access for Argo/EKS was requested in https://github.com/department-of-veterans-affairs/va.gov-team/issues/54554 and was approved

### User must exist in a roster before vets-api terminal access can be granted

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added
- [x] If they included an AWS user name, check to see if their user name is listed in [iam_users.tf](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf)
- [x] Comment in this issue saying which roster the user is listed in and confirming their AWS user name (if applicable)

**Comment by rmtolmach** [comment]
Raina is in the VFS roster and an AWS user. @rjohnson2011, can you grant @rd-huerta access to dev and staging?

**Comment by jeremy6d** [comment]
I confirmed that they are already in the dev github team but are now added to the staging team, closing this ticket. For more information see https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-TerminalAccess
