### ISSUE TITLE
AWS access for Seth Darr

### ISSUE THREAD

**Issue by sethdarragile6** [department-of-veterans-affairs/va.gov-team#56501]
### COR Name

Delano McVay

### Vendor Onboarding Representative Name

Agile Six - Anthony M. Arashiro

### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Seth Darr

### Your Email

seth.darr@agile6.com

### Team, Role, and Company of the target individual

Benefits Crew, Benefits Disability Experience Team, Agile Six Applications, Inc.

### Product Manager (PM) name and email

Rakshinda Aslam rakshinda.aslam@agile6.com

### Product Owner (PO) name and email

Matt Self matthew.self2@va.gov

### Desired AWS Access

I need access to AWS SSM Parameter Store to store application secrets such as environment variables and for the benefits disability compensation Form 526 application.

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

![e-qip transmittal email](https://user-images.githubusercontent.com/92405130/230652932-8f0ae3c7-2334-44e8-b6da-2f085b5d47a2.png)

### Additional Notes

I chose "ongoing" for the Access Expiration because i do not know if or when I will be off the team

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by considerable** [comment]
VFS Team Roster

**Comment by BillChapmanUSDS** [comment]
Requested environments were not specified. Approving production access for 3 months or until we update the current process (discussion in progress)

**Comment by sethdarragile6** [comment]
> Requested environments were not specified. Approving production access for 3 months or until we update the current process (discussion in progress)

@BillChapmanUSDS Does this mean that we are unblocked in starting to use AWS Parameter Store for all lower environments? Or are there more rounds of approval to go? Thanks! 

( cc: @ahay-agile6 @navaeddie @mchae-nava )

**Comment by considerable** [comment]
the account is created, access instructions are sent via DM in DSVA slack

**Comment by considerable** [comment]
> > Requested environments were not specified. Approving production access for 3 months or until we update the current process (discussion in progress)
> 
> @BillChapmanUSDS Does this mean that we are unblocked in starting to use AWS Parameter Store for all lower environments? Or are there more rounds of approval to go? Thanks!
> 
> ( cc: @ahay-agile6 @navaeddie @mchae-nava )

@sethdarragile6 - the access to AWS Param Store is considered prod access. 
Yes, you can access all environments if you have it.

**Comment by flooose** [comment]
@sethdarragile6 your ssm production access has expired.

Would you like to request an extension? You have 72 hours to respond, or your access will be revoked and you will need to fill out a new request.

**Comment by sethdarragile6** [comment]
> @sethdarragile6 your ssm production access has expired.
> 
> Would you like to request an extension? You have 72 hours to respond, or your access will be revoked and you will need to fill out a new request.

Ah, yes, please! I wasn't sure how to extend it, so I put [another request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63544) in 5 days ago. If that's not needed, I can close it out. Thanks!

cc: @aurora-a-k-a-lightning and @mchae-nava - my teammates who are also facing expiration...

**Comment by flooose** [comment]
@sethdarragile6 your ssm production access has expired.

Would you like to request an extension? You have 72 hours to respond, or your access will be revoked and you will need to fill out a new request.
