### ISSUE TITLE
Review Cerner Auto-login

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#56514]
Research the potential solutions, risks, and impacts to fixing auto-login on USiP for My VA Health portal login page. 

Create a write-up as output for this task. The topic will be discussed with Tom Black and the Cerner team to determine what the next steps should be.

Notes:
- Some thoughts were discussed around targetting the application= param for Cerner and seeing if we can assist with auto-login.
- Some risks are that this may have an impact on SiS functionality, other apps, and this may be more effort to create and maintain than is worth the reduction in logging in twice when a user manually goes to the cerner patient portal.
- if a user uses the deeplink from VA.gov to go to Cerner they are auto-logged in through SSOe
- Only when a user goes directly to the [cerner portal](https://staging-patientportal.myhealth.va.gov/) link are they asked to login on the USiP (even when an ssoe session is already established)

**Comment by mjconw3** [comment]
Create a follow up sync on this tomorrow @acaruso-oddball

**Comment by acaruso-oddball** [comment]
Upon examination, it was found that in this [pr](https://github.com/department-of-veterans-affairs/vets-website/pull/23054/files) a member of the OCTO team caused this breaking change by removing an Identity maintained variable in the LogoRow component `(src/platform/site-wide/header/components/LogoRow/index.js)`. The ```isUnifiedSigninPage``` variable was used to determine whether or not to conditionally render the Header component` (user-nav/containers/main.jsx)` throughout the app. When rendered, the Header component does a variety of tasks, to include rendering a sign-in button, determining if a user has a session, and how long said session lasts. At the time this conditional rendering was necessary, as it ensured that the sign-in button did not render twice on the Unified Sign In Page. However, to get AutoSSO to work, we need to ensure that the header renders regardless. To do so, we will need change what’s rendering conditionally. Feasibly said bug could be resolved by removing the code around the ```showNavLogin``` variable within the LogoRow component, and instead using CSS to conditionally show or hide the login button within the UserNav. This solution will be explored in an issue linked below.

**Comment by acaruso-oddball** [comment]
Follow Up Tickets: #57701, #57697
