### ISSUE TITLE
Automate process to easily ingest MHV data and report on CSP counts (Part 2)

### ISSUE THREAD

**Issue by elizabethmkoch** [department-of-veterans-affairs/va.gov-team#56511]
## Issue Description
The login.gov adoption team, stakeholders, and VA leadership need to review data and analyze CSP counts and CSP method changes to track login.gov adoption.

## User Story
As a Product Owner
I want to know the total user counts by CSP accessing the va.gov ecosystem as we progress through the migration
So that we can track adoption.

---
Configure Domo and Domo Workbench to load new datasets
- [ ] configure Domo to detect newly exported datasets and initiate load
- [ ] load as partitioned dataset
- [ ] configure Domo ETL to automatically run with updated datasets

Update dashboard
- [ ] confirm dashboard visualizations include view of changes over time

## Acceptance Criteria
- [ ] Process automated on regular weekly cadence

**Comment by lmorris3** [comment]
@sdickson-gt is this still relevant or is the work being handled through other tickets on the board?
