### ISSUE TITLE
Typo on Frontend developer documentation > Frontend workflow > Staged rollouts

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/va.gov-team#56526]
### Description
On the Frontend developer documentation > Frontend workflow > Staged rollouts page, under the `A feature toggle` section, the following snippet seems to have a typo in the second set of parentheses: "percentage of time" should be "percentage of users".

> The values can either be set as a percentage of users, specific user accounts (a list of login emails that are enabled), or a percentage of time. For the sake of phased rollouts it is advised that only the first two possible options (percentage of time or specific emails) be used as a percentage of time can produce unexpected results.

### Relevant URLs
https://depo-platform-documentation.scrollhelp.site/developer-docs/staged-rollouts > `A feature toggle` section

### Which type of team are you on? (Platform team, VFS team, or Leadership)
VFS team

**Comment by laucon** [comment]
I fixed this. Thank you SO much for bringing it to our attention. The correction should be published tomorrow around 3:30pm.

**Comment by vbellissimo** [comment]
This correction has been made and deployed live to the website.
