### ISSUE TITLE
BGS create_person endpoint returns PII on error.

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#56528]
## Issue Description

If a request to BGS's create_person endpoint errors, BGS sometimes returns an error message containing the veteran's file_number, which as far as BGS is concerned, must be equal to their SSN. We capture these logs in Datadog. This is a PII issue that we should address. We might also ask BGS to filter the file_number in their error message, just as they filter SSNs.

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by tblackwe** [comment]
@tfink419 can you take a look at resolving this PII gap?

**Comment by tblackwe** [comment]
I synced with Tyler on this issue, and while I think the code is good, I want to discuss a more holistic approach with some other SMEs and Steve Albers. regressing ticket until that discussion happens
