### ISSUE TITLE
Change Identity statsd metrics to use underscores instead of periods

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#56520]

**Comment by bosawt** [comment]
We could also use a wrapper method for the relevant statsd on identity to do this in a way that could be changed or reverted in a single place, instead of updating all of our statsd

**Comment by bosawt** [comment]
We could also use a wrapper method for the relevant statsd on identity to do this in a way that could be changed or reverted in a single place, instead of updating all of our statsd
