### ISSUE TITLE
Forms Dashboard Update - Pre-Need

### ISSUE THREAD

**Issue by ccruzgra** [department-of-veterans-affairs/va.gov-team#56525]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>We identified additional metrics of interest for the Pre-Need Application for Eligibility Determination (VA Form 40-10007) that we'd like to request</summary>
<div>
    <br>
<p>Use this template to request Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

</div>
</details>

### Required
- **Is this request for **Google Analytics implementation** or **QA**?**

     - [x] Google Analytics implementation
     - [ ] QA

- **Who is this request for?**

    - MBS Self-Service team
   
- **Provide the link(s) for Google Analytics implementation or QA**
  
    - https://www.va.gov/burials-memorials/pre-need-eligibility/
    - https://www.va.gov/burials-and-memorials/pre-need/form-10007-apply-for-eligibility/introduction
    
- **When is the launch date?**
    - TBD 

- **What interactions need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked_

  - Need Google Analytics standard dashboard for form 
  - Need behavior flow set up for pre-need [From the [introduction page](https://www.va.gov/burials-and-memorials/pre-need/form-10007-apply-for-eligibility/introduction) until the [confirmation page](https://staging.va.gov/burials-and-memorials/pre-need/form-10007-apply-for-eligibility/confirmation)]
  - Metrics of interest: 
    - Abandonment rates (such as for unfinished applications) 
      - Abandonment rate % & what’s causing them 
    - Any way to determine what’s causing form failures? 
      - number of form failures 
    - Which pages are users typically resuming application in when they return to complete? 
      - Note: The radio list for Relationship to service member question impacts which of the two flows they take in the form. 
    - On which pages do more users click “Finish application later” link? 
    - Getting a more specific view of the audience 
      - Signed in vs. not signed in number of users 
      - The total number of users 
      - Total number of users per user category (Veteran / service member, spouse or surviving spouse, unmarried adult child, other) based on Relationship to Veteran radio button question in Applicant Information).
      - Session length (Audience view isn’t specific to pre-need) 
      - Age of users (Audience view isn’t specific to pre-need, so we used page views to explore this further)
      - Gender of users (Audience view isn’t specific to pre-need, so we used page views to explore this further)
    - Time to complete successful submissions goal funnel 
    - Time stamp of submissions (not sure this could be tracked in GA) 
      - This might have to be something our devs do on the confirmation page that also gets sent to BTRS. Why is this needed? Need to see if there’s a delay between when it was submitted and when it’s available in Salesforce (when they started looking at it/assessed the data). Helps in more effectively addressing applications/identifying issues w/ system and how that’s being tackled. 
    - Users submitting applications with documents attached vs. not attached 
    - Questions of interest within pre-need form: 
      - How many users are selecting “Someone else” for preparer question? 
        - [Step 5 of 6: Contact Information](https://www.va.gov/burials-and-memorials/pre-need/form-10007-apply-for-eligibility/preparer)
        - [Step 6 of 7: Contact Information](https://www.va.gov/burials-and-memorials/pre-need/form-10007-apply-for-eligibility/preparer)

### Optional
- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - [Insert test user]

- **Any additional comments**

    - [Insert comments]

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by michelle-dooley** [comment]
@ccruzgra - we will review your request and get back  to you with an eta.

**Comment by ccruzgra** [comment]
@michelle-dooley Hi Michelle, I was wondering if there's an ETA on this yet. Thank you.

**Comment by michelle-dooley** [comment]
@ccruzgra - after reviewing this request I think the best place to start is to get this form added to the [Forms KPIs Domo dashboard](https://va-gov.domo.com/page/447193050). In order to do so I need you to complete the following...

- [ ] Make a copy of the [KPI Dashboard Product Details - Template](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit#gid=981224988)
- [ ] Complete worksheet as instructed
- [ ] Link your completed spreadsheet here: ______
- [ ] Check your sharing settings to make sure the Analytics team will be able to access it

Once you provide those form funnel details we can get it added as part of this upcoming sprint.

**Comment by ccruzgra** [comment]
@michelle-dooley Here's the requested link: [KPI Dashboard Product Details - Pre-Need](https://docs.google.com/spreadsheets/d/1P04pB9I8B_BHJ1InRZOcTaprrUJhosvCn87nJcznzsY/edit?usp=sharing)

**Comment by michelle-dooley** [comment]
@ccruzgra - the dashboard is composed of data from GA, so anything we report there can also be found in individual GA reports.  

Here are some things to note based on your items above:
Failure & abandonment rates - will be provided, but we will not have insight into reasons/causes for those failures/abandonments.
Resuming the application - you could back into this looking at the funnel step and date
Finish application later - 
Age/gender demographics - are part of GA reports but please note those are forecasted fields from Google and may not be the most accurate which is why they are not part of the Domo dashboard.  However if you want to see them you can view the Audience/Demographics/Overview [report](https://analytics.google.com/analytics/web/#/report/visitors-demographics-overview/a50123418w177519031p184624291/_u.date00=20230401&_u.date01=20230430&_.useg=user3zYP_UqgQPe8QnY5qsPxeA/) in GA.  You can use this segment to isolate your population  https://analytics.google.com/analytics/web/template?uid=Ji5S9aAJSEGMRl8hS_8cyg
Time stamp - we can tell you the date a form was submitted but not the exact time stamp.

**Comment by ccruzgra** [comment]
Hi Michelle, thank you. I was referring to a GA dashboard that would be accessible through the Dashboards tab seen here:
<img width="362" alt="Screenshot 2023-05-02 at 11 52 17 AM" src="https://user-images.githubusercontent.com/41477797/235719052-1f78e088-bd53-417d-94e9-11dd0576812c.png">
Unless your team doesn't create those anymore.

**Comment by michelle-dooley** [comment]
Is that an existing dashboard, I cannot see the name to know what it is?  Unfortunately we do not have the resources to create custom GA dashboards for teams.  If you want to come to office hours we can provide guidance for you to create.  However with the migration to GA4 you will need to create all new GA reports and dashboards so I am not sure how much time I would spend on creating a brand new one in the current GA property with the migration in mind.

**Comment by ccruzgra** [comment]
No, it's not existing as there aren't any for Pre-Need. That makes sense to hold off due to the upcoming migration. Thank you!

**Comment by michelle-dooley** [comment]
@dorseypa1 table for upload https://docs.google.com/spreadsheets/d/1HGHwahrS6HWC81AzeL7IQXTnwWaImD6QrAs-uFEDrAI/edit#gid=0

**Comment by ccruzgra** [comment]
@michelle-dooley We'll be releasing what we call "pre-integration" enhancements incrementally. The fully integrated form (with Salesforce and legacy systems) will be released around next spring/summer.

**Comment by michelle-dooley** [comment]
@ccruzgra will any of pre-integration enhancements be live on VA.gov? If not it may be pre-mature to start this work.

**Comment by michelle-dooley** [comment]
Sprint update:  We are currently in QA that will continue into the next sprint to complete this work.

**Comment by ccruzgra** [comment]
@michelle-dooley Thanks for the update.

**Comment by michelle-dooley** [comment]
@ccruzgra your [Domo dashboard](https://va-gov.domo.com/page/447193050) is complete.  Please let us know if you have any questions.  Thanks!! Michelle

**Comment by ccruzgra** [comment]
@michelle-dooley Is there any way to see granular details like the following in DOMO or Google Analytics like we'd noted in the request above?
Questions of interest within pre-need form:
- How many users are selecting “Someone else” for preparer question?
[Step 5 of 6: Contact Information](https://www.va.gov/burials-and-memorials/pre-need/form-10007-apply-for-eligibility/preparer)
[Step 6 of 7: Contact Information](https://www.va.gov/burials-and-memorials/pre-need/form-10007-apply-for-eligibility/preparer)

Getting a more specific view of the audience

- Signed in vs. not signed in number of users
- Total number of users per user category (Veteran / service member, spouse or surviving spouse, unmarried adult child, other) based on Relationship to Veteran radio button question in Applicant Information).

(cc: @barron-charles)

**Comment by michelle-dooley** [comment]
@ccruzgra - 

The "someone else" data is not currently collected as part of GA.  You would need to submit a  [GTM request ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+collaboration-cycle&template=analytics-implementation-and-qa-request-template.md&title=Analytics+Implementation+or+QA+Support+for+%5BProduct%5D) for that additional tracking.

To see the signed vs. not you can add a filter at the top of the page click "+" next to "Filter Views" and select "loa".  It will then show up as filter at top.  True = logged in.

 The relationship to service member radio button selection is also not tracked in GA, would need a GTM request for that configuration, would be part of the same request link above.
