### ISSUE TITLE
Vets-api terminal access for John Bramley

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#56532]
### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

John Bramley

### Your GitHub handle (terminal access is managed through GitHub)

@bramleyjl

### Team, Role, and Company of the target individual

Identity Surge, Backend Engineer, Oddball

### Product Manager (PM) name and email

Matt Conway mconway@clarityinnovates.com

### Product Owner (PO) name and email

John Rahaghi john.rahaghiva@gmail.com

### Your dsvagovcloud AWS user name (if applicable)

John.Bramley

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### COR Name (leave "None" if you listed an AWS user name above)

None

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

None

### Access Expiration

ongoing

### Additional Notes

As a backend engineer on the Identity Team I regularly am on the on-call rotation for VA.gov, and as such need ongoing access to production in case of an emergency during those periods.

### User must exist in a roster before vets-api terminal access can be granted

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added
- [ ] If they included an AWS user name, check to see if their user name is listed in [iam_users.tf](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf)
- [x] Comment in this issue saying which roster the user is listed in and confirming their AWS user name (if applicable)

**Comment by little-oddball** [comment]
VFS Roster

**Comment by jeremy6d** [comment]
Added to sandbox (dev and staging were already done)

**Comment by jeremy6d** [comment]
AWS user `John.Bramley` needs OCTO-DE approval for production access

**Comment by ericboehs** [comment]
👍 Approved

**Comment by ryan-mcneil** [comment]
@bramleyjl between comments both here and in the [linked issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/56341), access to all environments have been restored.
