### ISSUE TITLE
FACILITIES prod EKS rollout

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#56549]
4/10 11am ET

Routes:
`/v1/facilities/va` 
`/facilities_api` to EKS. 

[See Facilities charts here](https://vagov.ddog-gov.com/dashboard/ign-t33-h24/vets-api-eks-migration-production?from_ts=1681133419849&to_ts=1681133719849&live=true)

**Comment by rmtolmach** [comment]
Merged PR
- https://github.com/department-of-veterans-affairs/devops/pull/12800

And redeployed revproxy

✅ things look good in [datadog](https://vagov.ddog-gov.com/dashboard/ign-t33-h24/vets-api-eks-migration-production?from_ts=1681139714581&to_ts=1681143314581&live=true)
![image](https://user-images.githubusercontent.com/10993987/230943915-82c5c27f-ee39-45bb-b296-1b96b1825f37.png)

**Comment by laineymajor** [comment]
ADDED TO THIS SPRINT AS PART OF THE EKS MIGRATION.
