### ISSUE TITLE
[Due on 02/18] Redirect Request for DIC rate tables pages - Spouses & Children, and Parents

### ISSUE THREAD

**Issue by AnneHurley** [department-of-veterans-affairs/va.gov-team#5655]
### Description
DIC rate table pages first moved from Burials to Disability. Now we are redirecting the legacy URLs to the two new ones.

### Requestor Info
VBA, Angie Smith is our main stakeholder
Team requesting: Public Websites

### Implementation Date
URLs are now live so asap.

Please indicate when the redirect(s) needs to be implemented"
- [ ] On the same date the new URLs launch
- [x ] Can happen within 1-5 business days after new URLs launch
- [ ] Other - Please indicate timing : 

### Redirects Needed

Current URL  |  Redirect Destination (new URL)
--- | ---
https://benefits.va.gov/compensation/current_rates_dic.asp | /disability/survivor-dic-rates/
https://benefits.va.gov/pension/current_rates_Parents_DIC_pen.asp | /disability/parent-dic-rates/
https://www.benefits.va.gov/compensation/resources-rates-read-parentsdic.asp | /disability/parent-dic-rates/
https://benefits.va.gov/compensation/resources-rates-read-dic.asp | /disability/survivor-dic-rates/

### Steps to complete
- [x] Above information is provided and issue is tagged and assigned appropriately - *@ requesting team*
- [x] All appropriate VA stakeholders are notified of pending redirect - *@ requesting team*
- [x] Redirect request is vetted and documented and implementation plan is clear - *@ Content & IA team*
- [x] Request is assigned to appropriate team for implementation - *@ Content & IA team*
- [ ] Implementation team completes work - *@ Implementation team*
- [ ] Implementation pushed live and redirect is validated in production - *@ all*
- [ ] Ticket is closed - *@ requesting team*

**Comment by AnneHurley** [comment]
@mnorthuis  Note that the new URLs will also include the "how to read" legacy page info, so those 2 pages need to be redirected as well. Let me know if you have any questions.

**Comment by mnorthuis** [comment]
@lunascoop All urls are vetted and ready to go when  your team is ready to implement.

**Comment by MickinSahni** [comment]
@AnneHurley does this need to happen before tuesday i.e. within Sprint 14?

**Comment by AnneHurley** [comment]
@MickinSahni  @mnorthuis  @lunascoop  Ideally, yes. We had these in the works for a while; first we moved them from Burials to Disability, and we knew we would be redirecting them. I'm just not sure how much "wiggle room" we have in the new redirect process or if it really does take up to 2 weeks to implement. Mikki and Selena, can you confirm?

**Comment by lunascoop** [comment]
@AnneHurley @MickinSahni I still need to let the stakeholders know. The earliest the redirects can take place is next Tuesday 02/18.

**Comment by ncksllvn** [comment]
PR is open with date of 2/18 - https://github.com/department-of-veterans-affairs/vets-website/pull/11672. We can probably make it go sooner if we don't need stakeholder awareness.

**Comment by lunascoop** [comment]
Stakeholder comm has been sent. Redirect implementation date is 02/18.

**Comment by MickinSahni** [comment]
2020-02-13 PW Standup
- what's left - implement redirects, validate, and let stakeholders know!

**Comment by ncksllvn** [comment]
PR containing the redirects is merged and will be deployed today

**Comment by AnneHurley** [comment]
@lunascoop  The redirects and content look good to me.

**Comment by lunascoop** [comment]
I've validated that the redirects were implemented successfully. Closing ticket and notifying stakeholders.
