### ISSUE TITLE
Facility-entered data in field "You shared these details..."

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#56557]
## Summary
In usability sessions we saw codes in the "you shared these details about your concern" section that had been entered by the scheduler/staff. That field should only show information Veterans share with the facility.

## Specs
- Device: Multiple
- Browser: Multiple

## Steps to Reproduce
This was observed during 2-3 usability sessions on production, not sure how to reproduce.
This field appears on the details pages of some appointment types.

### Actual Result
Examples of data shown to Veteran in that field (redacted information is in _italics_)
- PAP COMPLIANCE/TELE
- DO _Date_ PID _Date_
- PID _Date_ APPT _Date_@900 PER RTC OK PER VET TPI

![Screenshot 2023-04-10 at 7.41.17 AM.png](https://images.zenhubusercontent.com/5f7ce3163782a585b910eaf3/f70d307a-ef07-4021-be94-1dacb9f66129)

### Desired Result
- The intent of this field is to show information Veterans enter in the free text entry box when scheduling an appointment in any flow
- The Veteran shouldn't be shown unhelpful codes used by clinics

## Definition of Done
- [ ] Desired result is achieved and/or document decisions made
- [ ] Relevant documentation is updated

**Comment by ldelacosta** [comment]
Created a backend ticket to see if we can get some results from Loki to help track down the source of the comment. 
[Ticket 58400](https://app.zenhub.com/workspaces/vaos-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/58400). Once we have figured the source of the comments, we can work with the team to address the issue.

**Comment by ldelacosta** [comment]
@outerpress - we know that the PID issue is not from us but more of where the staff is entering / or the BE fetching the data unintentionally. Let me know if we are good to close the ticket for now. We have the Loki tickets to track this.

**Comment by outerpress** [comment]
@ldelacosta yep that works for me 👍

**Comment by outerpress** [comment]
@ldelacosta this issue is documented [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/appointments-reference/data-reference/data-definitions.md#veteran-reason-for-appointment), okay by me to close.

**Comment by ldelacosta** [comment]
No additional work is needed. Closing out the ticket. @outerpress
