### ISSUE TITLE
Vets-api terminal access for Yang Yang

### ISSUE THREAD

**Issue by nanotone** [department-of-veterans-affairs/va.gov-team#56564]
### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Yang Yang

### Your GitHub handle (terminal access is managed through GitHub)

@nanotone

### Team, Role, and Company of the target individual

Benefits Delivery, Hypertension Software Engineer, Nava

### Product Manager (PM) name and email

Amy Lai, amy.lai2@va.gov

### Product Owner (PO) name and email

Emily Theis, emily.theis@va.gov

### Your dsvagovcloud AWS user name (if applicable)

Yang.Yang

### ArgoCD terminal access requested for the following environments

- [ ] dev
- [X] staging
- [ ] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### COR Name (leave "None" if you listed an AWS user name above)

None

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

Agile Six - Anthony M. Arashiro

### Access Expiration

10-10-23

### Additional Notes

I currently have access to vets-api production and staging console via AWS SSM, and am opening this ticket to maintain that access via EKS. [Here is the ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47374) where I was originally granted access.

Copying over the justification from that ticket:
>The OCTO Benefits Delivery team aims to use existing veteran data to programmatically accelerate decisions on certain benefits claims. To that end, I need prod rails console access to
>- inspect sample veteran data that's representative of real-world data, for UX research purposes, and
>- understand and debug new integrations, or data in existing integrations, that would be useful for determining whether a claim could be accelerated.

### User must exist in a roster before vets-api terminal access can be granted

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added
- [ ] If they included an AWS user name, check to see if their user name is listed in [iam_users.tf](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf)
- [x] Comment in this issue saying which roster the user is listed in and confirming their AWS user name (if applicable)

**Comment by va-albers** [comment]
Hi team - can prioritize this request?  It is replacing existing pre-EKS access, and is affecting our ability to research a production support issue relating to logging.

**Comment by little-oddball** [comment]
VFS Roster

**Comment by ryan-mcneil** [comment]
@nanotone `staging` access has been restored to AWS user `Yang.Yang`

@LindseySaari @ph-One  @ericboehs Can I please get approval from one of you to restore Production access to Yang for the new deployment?

**Comment by ryan-mcneil** [comment]
<img width="719" alt="image" src="https://user-images.githubusercontent.com/41602677/231223482-858d0e48-5a62-4a11-b127-6e652cecbd9c.png">

**Comment by ericboehs** [comment]
👍 Approved

**Comment by ryan-mcneil** [comment]
@nanotone `prod` access has been restored.

**Comment by bdech** [comment]
@nanotone Vets-api Production access has expired.

Would you like to request an extension? You have 72 hours to respond, or your 
access will be revoked and you will need to fill out a new request.

**Comment by bdech** [comment]
@LindseySaari @ph-One @ericboehs can one of you please give us a :thumbsup: to extend their access?

**Comment by ph-One** [comment]
This is for terminal access to vets, which is no longer done through ssm, but instead is handled through ArgoCD, and GitHub teams. @ericboehs or @LindseySaari can add users to the vets prod gh team

**Comment by ph-One** [comment]
@LindseySaari or @ericboehs can add users to the appropriate gh team

**Comment by bdech** [comment]
@nanotone your Production access has been extended for 6 months,
expiring 04/12/24.

Please set a reminder for yourself to return to this Issue and 
request an extension within 1 week of the expiration date. You'll 
receive 1 reminder with a 48 hour window to respond. Failure to 
respond will result in your access being revoked and will require 
you to fill out a new request.

**Comment by bdech** [comment]
> @LindseySaari or @ericboehs can add users to the appropriate gh team

Thanks Kyle. Support has maintainer roles for vets-api gh teams. We were simply instructed to tag one of you to approval an extension of access. I can exclude you going forward since you're devops. Our confluence documentation mentioned to tag you, along with Lindsey and Eric.

**Comment by bdech** [comment]
slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1697123171421399)

**Comment by davidpetras** [comment]
@nanotone  Vets-api Production access has expired.

Would you like to request an extension? If so you have 72 hours to respond, or your
access will be revoked and you will need to fill out a new request.

Thank you.

**Comment by bdech** [comment]
No response, removing production access. If you would like to request production access, please fill out a new request.

**Comment by nanotone** [comment]
@bdech Sorry, I was on PTO and missed the initial comment. Is it possible to keep the production access for now?
