### ISSUE TITLE
[FE] SPIKE: Explore How a VVC Appointment Got Displayed as a Phone Appointment

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#56581]
[slack thread](https://dsva.slack.com/archives/C022AC2STBM/p1681145753193229?thread_ts=1680874744.840519&cid=C022AC2STBM)

**Comment by loripusey** [comment]
@brianseek @wullaski created this ticket based on PL discussion this morning

**Comment by brianseek** [comment]
The mystery is pretty much solved in this thread: https://dsva.slack.com/archives/C022AC2STBM/p1680874744840519

the TLDR: VVC appointments all use stop code 179 which we have flagged as also being a secondary phone stopcode. So these appointments' `kind` key gets set to `phone`

**Comment by loripusey** [comment]
So, is stop code 179 only used for VVC appointments?

**Comment by brianseek** [comment]
I don't think so. It sounds like a phone appointment could also have that stop code

**Comment by wullaski** [comment]
This is the current logic to determine if an appointment is a phone or in person. 

if the clinic Stop Code is any of these
```
const PRIMARY_PHONE_STOP_CODES = [
  103, 147, 148, 169,
  178, 181, 182, 199,
  216, 221, 224, 229,
  324, 325, 326, 338,
  424, 425, 428, 441,
  527, 528, 530, 536,
  542, 545, 546, 579,
  584, 597, 611, 683,
  685, 686, 718, 901,
];
```
or Credit Stop Code is any these
```
const SECONDARY_PHONE_STOP_CODES = [
  136, 137, 179, 371,
  440, 444, 445, 446,
  447, 490, 491, 644,
  645, 646, 647, 648,
  679, 684, 690, 692,
  693, 699, 674685, 685,
];
```
Then we label the appointment as a phone appointment.

If we had a stop code pattern that would precisely identify video appointments then we could set the kind to video and have the front end code handle it.
