### ISSUE TITLE
Update Dashboards & Custom Events to Google Analytics 4

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#56586]
## NOTES
- LP & JW attended the Analytics office hours on 6/8 to get some question answered
    - Will we need to make code changes to accommodate GA 4?
        - Yes, we currently have 84 events that we programmatically log using the Platform's record-event.js abstracted code that performs the logging; while some of these events (like the API call ones) should get automatically logged in GA4, others may or may not, so we will need to make some code changes
    - What code changes do we need to make?
        -  The Analytics team will provide data-layer code to all teams and instruct them on what changes they need to make; as of 6/8, they are still a little ways from taking this action as they are still in the configuration stage for GA4
        - The new GA4 data-layer code will run in tandem with the UA data-layer code for a period of time to ensure that everything is working as expected
    - Will we have to re-create our dashboards?
        - Yes, the dashboards in GA4 are different (i.e. GA4 reports) but are supposed to be easier (we'll see)
    - Will there be any training on the new GA4 reports?
        - Yes, the Analytics team will do some training with the teams on how to use the new GA4 reports
    - What can and can't we do now?
        - We CANNOT make any code changes yet, we must wait for the Analytics team to provide us with the new GA4 data-layer code            
        - We CAN, however, do a comparison of the events that are currently showing up in our GA4 production configuration (out there now) against our current UA dashboards to determine which of our custom events are automatically getting logged and which will need us to add the GA4 data-layer code

**Comment by benbrasso-agile6** [comment]
@loripusey oh did you close this Epic? 

Nothing for us to do for this migration? Timing?

**Comment by benbrasso-agile6** [comment]
Sounds good. And often, Google will keep pushing out there cut off dates to transition.
