### ISSUE TITLE
[Datadog] IaC ElastiCache

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#56592]
# Description
Existing monitors and/or synthetics need to be captured as code for tracking changes, risk management, as well as a form of access control. 

# Notes
- See https://github.com/department-of-veterans-affairs/devops/tree/master/terraform/environments/datadog for references on how to do this

# Acceptance Criteria
- [ ] Monitor and/or Synthetic is captured as Terraform

**Comment by hgbarreto** [comment]
[PR](https://github.com/department-of-veterans-affairs/devops/pull/12875)
