### ISSUE TITLE
SOCKS access for [Jacob Uhteg]

### ISSUE THREAD

**Issue by Jake-Uhteg** [department-of-veterans-affairs/va.gov-team#56605]
### Your Name

Jacob Uhteg

### Your Email

jacob.uhteg@oddball.io

### Your Role and Team

Test Engineer on VA Notify Strike Team

### Product Manager (PM) name and email

Zack Law - zack.law@oddball.io

### Product Owner (PO) name and email

Beverly Nelson - beverly.nelson@va.gov

### Access Type Requesting

developers

### Public SSH Key
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMTChbvI6ii0UcCyrrbD0kmjiKR4wXiWmlZSVNlO1FnP 

### E-QIP Transmittal Confirmation

![Screenshot 2023-04-10 at 2 36 37 PM](https://user-images.githubusercontent.com/102548645/230969639-bc07b99a-ff26-405c-8dc4-69e5f57f5fcd.png)

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by rmtolmach** [comment]
new ssh key updated ✅ 
You should have access in ~10 min

**Comment by rmtolmach** [comment]
@Jake-Uhteg Have you been able to access SOCKS?? I JUST realized that I didn't actually merge your PR 🤦‍♀️  https://github.com/department-of-veterans-affairs/devops/pull/12828 I am so sorry!! I just merged it now. Let me know if you have any problems.
