### ISSUE TITLE
[Research] Set-up for Remote Study

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#56624]
## Description
We need to conduct the research study for Unified Experience.

## Set-up Tasks
- [x] Pilot the study/interview internally (e.g. with Stephen)
    - Identify your pilot participant
    - Set up the pilot session
    - Run the pilot session
- [x] Review A11y prep

**Comment by benbrasso-agile6** [comment]
Conducted pilot today with Robin from ad hoc
