### ISSUE TITLE
Sign-in-service app - Update Ruby and Gems

### ISSUE THREAD

**Issue by rileyanderson** [department-of-veterans-affairs/va.gov-team#56621]
## Summary
This repo hasn't really been touched since the Rails generated code was added.

- Update Ruby, Rails, and all the gems. 
- Add rubocop and 
- cleanup the generated code

**Comment by mjconw3** [comment]
Good to close @rileyanderson

**Comment by mjconw3** [comment]
Good to close @rileyanderson
