### ISSUE TITLE
Claim establishment: need values for required fields

### ISSUE THREAD

**Issue by jjulian** [department-of-veterans-affairs/va.gov-team#5663]
We need to figure out what values to use for fields that are required to establish a claim.
required:
    - serviceTypeCode
    - programTypeCode
    - benefitClaimTypeCode

**Comment by srmyers17** [comment]
following up with Chris Carricho on this and may need to speak to buis stakeholder

**Comment by bshyong** [comment]
From Shalynn Frank:

> Yes, moving forward, the business will only be using the following claim labels: "PMC Burial Allowance" for non-SC or VAMC, and "PMC SC Burial" for SC burial. However, all the other claim labels will stay in production until they are changed or closed.
