### ISSUE TITLE
Sidekiq Admin UI Access Request

### ISSUE THREAD

**Issue by klwatanabe** [department-of-veterans-affairs/va.gov-team#56642]
#### Access to the Sidekiq Admin UI is managed through a GitHub Teams per environment via the following teams: 
- [Dev](https://github.com/orgs/department-of-veterans-affairs/teams/va-gov-sidekiq-dev)
- [Staging](https://github.com/orgs/department-of-veterans-affairs/teams/va-gov-sidekiq-staging)
- [Sandbox](https://github.com/orgs/department-of-veterans-affairs/teams/va-gov-sidekiq-sandbox)
- [Prod](https://github.com/orgs/department-of-veterans-affairs/teams/va-gov-sidekiq-prod)

_Please provide your GitHub username to be added to that team, along with a reason access is required and which environments you're requesting access to._

- GitHub username: klwatanabe
- Reason access is required: I am the Product Manager for Team Dash. We own the Claims API within Lighthouse and we require access to troubleshoot issues and support the Claims API in Production.
- Environments requesting access to: All

**Comment by rjohnson2011** [comment]
Access granted to dev, staging, sandbox environments.

Awaiting OCTODE approval for production access.

**Comment by klwatanabe** [comment]
Hi, @ryan-mcneil - Here is a screenshot from the Transmittal Notice email I received about a year and a half ago. 

![E-QIP Transmittal Notice](https://user-images.githubusercontent.com/10762504/236518787-e657eec6-1dff-4fdd-b7c5-5eb25c1b77ae.png)

**Comment by ryan-mcneil** [comment]
@klwatanabe Thanks! You've been granted access to all environments, with access to Production limited to 6 months, expiring 11/5/23

**Comment by ryan-mcneil** [comment]
Slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1683305696297729)

**Comment by bdech** [comment]
@klwatanabe Your Sidekiq Admin UI Production access has expired. Would you like to request an extension of access?

**Comment by bdech** [comment]
@klwatanabe Your access has been extended 6 months, expiring 05/06/24.

Please set a reminder for yourself to return to this Issue and re-request access within 1 week of the expiration date. You'll receive 1 reminder with a 72 hour window to respond. Failure to do so will result in lost access and will require you to fill out a new request.

**Comment by bdech** [comment]
Slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1699295569399939)

**Comment by klwatanabe** [comment]
Hi, @bdech - I am trying to access sidekiq via https://api.va.gov/sidekiq/ and getting an error that I do not have access to the team. Would you be able to help me get access?

**Comment by bdech** [comment]
Hmm, that is strange. I just added you back, so you should have access now.

**Comment by klwatanabe** [comment]
@bdech - It is working now. Thanks!

**Comment by AnthonyWFlowers** [comment]
Hi @klwatanabe, your access has expired.
Would you like to request an extension? You have 72 hours to respond, or your access will be revoked and you will need to fill out a new request. Thank you!

**Comment by AnthonyWFlowers** [comment]
Greetings @klwatanabe your access has been removed, if you believe you still need access please fill out another request form [Here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=external-request%2Cplatform-tech-team-support%2Cops-access-request%2Csidekiq-access-request&projects=&template=vetsapi-sidekiq-ui-access.yaml&title=Sidekiq+Admin+UI+access+for+%5Bindividual%5D)
Thank you.
