### ISSUE TITLE
Tighten up whitespace on appointment list subnavigation

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#56648]
## Task Description
With the addition of the subnavigation across all appointment list pages, the whitespace around the subnavigation is inconsistent. This work makes the spacing consistent across all pages.

## References
- [This slack conversation/video](https://adhoc.slack.com/archives/C02UW5AHHEJ/p1680894498452689?thread_ts=1680888335.241099&cid=C02UW5AHHEJ)
- [Dev ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/56790)

## Acceptance Criteria
- [ ] M/T/D [design spec ](https://www.figma.com/file/XmvY7ijIOTPgfQ3cTXodJD/Subnavigation?node-id=13%3A33&t=2Chc82kvPC9URFvF-1)

**Comment by ldelacosta** [comment]
Please add the design spec file in [ticket 56790](https://github.com/department-of-veterans-affairs/va.gov-team/issues/56790)

**Comment by outerpress** [comment]
@Cieramaddox could you check if this one can be closed out?
