### ISSUE TITLE
Update description of Cerner My VA Health portal from OCTO Health team

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#56655]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more unauthenticated pages, online forms, apps, or tools on VA.gov
- [x] Making revisions to one or more existing VA.gov pages
- [ ] Something else 
 
We should consider removing the `new` modifier to mentions of the My VA Health portal. Example:

![image (6)](https://user-images.githubusercontent.com/7645362/231214163-1311b962-fac8-4b3d-b3fe-ec354ce684ef.png)

Thinking: there are a lot of “new” portals, the most important of which is **MHV on VA.gov**, so calling the My VA Health portal "new" might contribute to confusion. Plus there is the mere fact that the My VA Health portal is not “new” anymore, though there might be new users as sites transition.

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [ ] Yes
  - [x] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
## When do you expect to launch your product to 100% of users?
  
When work is complete.
  
## Supporting artifacts
*Please provide supporting artifacts as available.*

- Link to product outline:
- Link to or attach user flows:
- Link to prototype or mockups:
- Link to any epics/issues that may be helpful:

## Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [x] No

## When does this work need to be done?
- Estimated launch date: When work is complete
- Estimated staging review date: N/A
- Content, Accessibility, and IA work needed by: N/A

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: Patrick Bateman
-	Product manager: 
-	Designer: 
-	FE engineer: 
-	Product/team Slack channel: [#mhv-on-vagov-portal-home](https://dsva.slack.com/archives/C04GDQSHD1R)

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by batemapf** [comment]
👋 to my knowledge, this has not been resolved. thanks!

**Comment by RLHecht** [comment]
@wesrowe @jilladams I believe this content lies in the cerner react widget so isn't something our team would be able to update. Can you remove the word "new" from this?

**Comment by jilladams** [comment]
Confirmed: 

```
~/code/vets-website/src/applications/personalization/dashboard/components/cerner-widgets.js:
   56        <div>
   57          <p>
   58:           Your care team may now use our new My VA Health portal. Choose your
   59            portal based on the facility for your appointment:
   60          </p>

~/code/vets-website/src/applications/static-pages/health-care-manage-benefits/components/CernerCallToAction/index.js:
  135          <div className="usa-alert-body">
  136            <h3 className="usa-alert-heading">
  137:             Your VA health care team may be using our new My VA Health portal
  138            </h3>
  139            <h4 className="vads-u-margin-y--3">
```

Put up a PR, https://github.com/department-of-veterans-affairs/vets-website/pull/24289.

**Comment by jilladams** [comment]
This change is merged and will deploy by tomorrow.
