### ISSUE TITLE
GIBCT: Autocomplete is showing institutions that should be filtered

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#5666]
When searching for institutions in the Comparison Tool, a user is able to reduce the number of results using several different filters. The auto-complete functionality of the keyword search should use these filters to reduce the number of autocomplete results. Currently, autocomplete only accounts for the text typed into the search bar and will display results that should be filtered out by the filters selected by the user.

1. Access https://staging.va.gov/gi-bill-comparison-tool/
2. Type "college" into the search bar and click Search Schools
3. Apply the following filters:
- **Institution type:** FLIGHT
- **State:** Arizona
- **Programs:** Student Vet Group
4. In the keyword search bar type "College of Charleston"

**COLLEGE OF CHARLESTON** and **COLLEGE OF CHARLESTON DEPARTMENT OF PUBLIC SAFETY** show in autocomplete even though any of the above three filters should rule out both.

![Screen Shot 2020-02-07 at 3.03.53 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/531a7e69-c284-441a-a992-3e6f45f29a36)

**Comment by dmccurdybah** [comment]
PRs:
- https://github.com/department-of-veterans-affairs/vets-website/pull/11678
- https://github.com/department-of-veterans-affairs/gibct-data-service/pull/574

vets-website branch: `autocomplete-filter`
gibct-data-service branch: `autocomplete-filter`

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
Changes are live in Staging. Closing this issue
