### ISSUE TITLE
[BE] Migrate 1010 team disability rating code to BGS

### ISSUE THREAD

**Issue by lihanli** [department-of-veterans-affairs/va.gov-team#56673]
EVSS disability rating API is deprecated, need to migrate to BGS disability rating API.

**Comment by lihanli** [comment]
@hdjustice i was able to access the new disability rating api, the data returned is different from the old api. now there are two disability ratings, "non_service_connected_combined_degree" and "service_connected_combined_degree". which one should be used for the 1010ez short form?

**Comment by hdjustice** [comment]
I am not sure, but checking with the EVSS migration team to see if they have any insight

**Comment by hdjustice** [comment]
Can you give me the actual name of the API so I can be sure to reference it correctly?

**Comment by lihanli** [comment]
Lighthouse disability rating API which is calling the BGS disability rating API

**Comment by hdjustice** [comment]
Per Slack conversation with Michael Harlow:

> Michael Harlow
>   [5 minutes ago](https://dsva.slack.com/archives/C02CQP3RFFX/p1681408358888619?thread_ts=1681335897.763499&cid=C02CQP3RFFX)
> After looking at the vets-api code, I noticed that the 10-10EZ Health Care Application prefills vaCompensationType based on userPercentOfDisability from the EVSS /findRatingInfoPID API. EVSS populates userPercentOfDisability from the BGS serviceConnectedCombinedDegree element in their findRatingDataByPtcpntIdResponse. The Lighthouse /v1/disability_rating response has a combined_disability_rating field that's populated by the same BGS field. Hope this helps.

**Comment by lihanli** [comment]
@longmd the new disability rating API is now at `GET /v0/health_care_applications/rating_info`
it should return the same data as the old disability rating api `/v0/disability_compensation_form/rating_info`

the frontend also needs to migrate to the new API because the old API is deprecated

**Comment by longmd** [comment]
@lihanli , do you have a sample of what that response body looks like? I'm seeing this in our e2e testing in the mocked response. Obviously, I assume that type will be a different name and will the attribute keys be different?
`
{
  data: {
    id: "",
    type: "evss_disability_compensation_form_rating_info_responses",
    attributes: { userPercentOfDisability: disabilityRating },
  },
}
`

**Comment by lihanli** [comment]
@longmd this is what the new response looks like
```json
{
  "data": {
    "id": "",
    "type": "hashes",
    "attributes": {
      "user_percent_of_disability": 100
    }
  }
}
```
