### ISSUE TITLE
Increase in 503 errors

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#56689]
### PROBLEM STATEMENT
After rolling out 4 mobile routes to prod, those routes are receiving significant increase in 503 errors. 
/mobile/v0/payment-history
/mobile/v0/disability-rating
/mobile/v0/user
/mobile/v1/user

We were also just notified that the same errors have been happening in staging for the past few days. 

[Slack thread
](https://dsva.slack.com/archives/C04M7T1CZAS/p1681232273382689?thread_ts=1681214401.474099&cid=C04M7T1CZAS)

### ACTION ITEMS
- [ ] rollback to BRD for Prod while work to resolve issues in staging
- [ ] NginX needs to point to traefik rather than 2nd ASG config

**Comment by laineymajor** [comment]
@RachalCassity can you provide update as you work through the errors. thanks!

**Comment by RachalCassity** [comment]
503 errors have not been seen since we separated routes to independent bulk head deployments. Still monitoring logs next week.

**Comment by laineymajor** [comment]
Currently monitoring. Will continue to monitor.
@laineymajor to create a monitoring epic for starting next sprint. Include all monitoring items. Close current monitoring tickets if appropriate.

**Comment by laineymajor** [comment]
closing and moving to monitoring epic
