### ISSUE TITLE
Salesforce Report Update (Young Lee)

### ISSUE THREAD

**Issue by edpearson20** [department-of-veterans-affairs/va.gov-team#56695]
Adding Young Lee User Alias to daily reports.

**Comment by edpearson20** [comment]
Identified that there are two Young Lee individuals within the VA.Gov system.  Prior to today, Young.Lee7@va.gov was the individual receiving the reports.  It should have been Young.Lee8@va.gov.  Attempting to identify Young's alias to add for reporting.

**Comment by ATMiddleton** [comment]
Name identification resolved.
