### ISSUE TITLE
Get a quote from LaunchDarkly 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#567]
- gather information about traffic patterns and potential usage needs 
- determine what features we need short term vs long term

**Comment by rianfowler** [comment]
# Features and capacity 

- Team members
  - up to 18 on the core platform team 
  - up to 30 on apps teams 
  - This will be a slow ramp up over a couple of months. We're not actively releasing new stuff right now and there will be a transition period as people adapt to using feature flag driven development 
- Server connections
  - 0 to start 
  - up to 176 with current capacity (1 per puma worker)
  - Client-side MAU (monthly)
  - 8.5-9m active users across all properties 
  - 2.4m active users across va.gov 
  - 500k sessions for high traffic app (facility locator)
  - We'll roll this out to facility locator initially to demonstrate the potential to our stakeholders. 
- SSO - no
- Custom roles & permissions: yes
- Service SLA: ?
- Experimentation: ?
- Data export: yes 

# Notes for the discussion: 
- goal: leverage Launch Darkly to make to the feature flag development easy so we can focus on the process and organizational changes 
- Evaluation period one month to demonstrate:
  - release toggle
  - feature toggle
  - long term operations toggle (circuit breaker)
  - a/b test 
- vets-website and vets-api are open source / non profit projects - are we eligible for a discount?

**Comment by brandonrapp** [comment]
Outcome of this ticket is that LaunchDarkly was going to be too expensive so the team decided to utilize a free application 'Flipper'. They will be using this for all of the upcoming toggle work.
