### ISSUE TITLE
Request QA Review for "View Dependents"

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#5671]
_Include in 'Analytics Implementation' ticket once we get that info from Jon Wehausen?_
## Story  
As an engineer, I want to request a review for Security and Load Testing with the QA Team to ensure that my feature meets the requirements for publication so that my pages will safely perform as expected under heavy loads typically found in the VA.gov environment.

## Task
- Select the Milestone sprint, or otherwise provide due-date for testing results.
  - 2-3 Sprints
- Provide the following info to support testing (via links if documented elsewhere):
  - Staging URLs of product/feature:
    - Static page URL: **staging.va.gov/disability/TBD/**
    - Report/dynamic page URL: **staging.va.gov/disability/view-dependents**
      - disability might not be the eventual hub for this
  - [UX Design wireframes/comps](https://xd.adobe.com/view/8cdfe895-c907-4662-7234-305056778b2a-faee/screen/61211510-a9de-477c-950c-ae7fe5d2ce65/View-Dependents-2)
  - Copy decks
    - None at this time
  - Test-accounts `(usual staging password)`  
    - User (Mark): vets.gov.user+228@gmail.com (has zero on award, 2 not)
    - User (Eric): vets.gov.user+10@gmail.com (has zero on award, 3 not)
    - User (Jeanette): vets.gov.user+123@gmail.com (has zero on award, 1 not)
    - User (Pauline): vets.gov.user+38@gmail.com (has zero on award, 11 not)
    - User (Sam): vets.gov.user+45@gmail.com (has zero on award, 2 not)
    - User (Claude): vets.gov.user+232@gmail.com (has zero on award, 1 not)
    - User (Terrence): vets.gov.user+102@gmail.com (has zero on award, **zero** not)
    - User (Randall): vets.gov.user+99@gmail.com (has **2** on award, 1 not)
    - User (Jesse): vets.gov.user+54@gmail.com (has zero on award, 1 not)
    - User (Jerry): vets.gov.user+271@gmail.com (has **2** on award, **4** not)

  
## Acceptance Criteria
- [ ] Review has been scheduled or reviewed by [Tze-chiu Lei](https://dsva.slack.com/team/UHB9W74TA) ([tze@adhocteam.us](mailto:tze@adhocteam.us)) or [Peter Hill](https://dsva.slack.com/team/UL0FKGBDY) ([peter.hill@oddball.io](mailto:peter.hill@oddball.io))

**Comment by tlei123** [comment]
@jason-gcio , re. the test-accounts' scenarios being the same for most of the usernames...

What do you think about my proposed test-cases below?

1. Has both on-award and not on-award dependents;
2. Has only on-award dependents; and
3. Has only dependents not on-award.

Considering the View Dependents page does not have real app/widget, I'm thinking we'd only need the 3 test-cases* above to cover all info-display scenarios.

Please let me know.  Thx much!

**Comment by tlei123** [comment]
@cohnjesse @micahchiang , where can I find the destination-URL-specs for the side-panel links below?

1. Find out more about dependents and your benefits; and
2. Get help filing a claim.

Please let me know.  Thanks much!

**Comment by tlei123** [comment]
@sporeboy, a quick confirmation please...

Re. the No-dependents-info-on-file user-scenario \([this mockup screen](https://xd.adobe.com/view/8cdfe895-c907-4662-7234-305056778b2a-faee/screen/944a9424-910c-467d-bc49-9a6040414e5f/View-Dependents-No-Info-1)), does the **Find out how to add a dependent to your disability claim** link also go to https://www.va.gov/disability/add-remove-dependent/ ?

I just noticed front-end #5469 just got Closed, but I didn't see an explicit link-spec in the ticket-description for this particular screen/scenario.

Please let me know.  Thanks much!

**Comment by jason-gcio** [comment]
Pinging Tze when these test accounts start to show data
