### ISSUE TITLE
IA design for Form 40-0247 (Presidential Memorial Certificate)

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#56717]
An intake request has not come in for this form yet - please connect this ticket to that intake request when it comes in. 

The forms digitization team will be working the form to request a Presidential Memorial Certification. 

Here is their initial information:
https://docs.google.com/document/d/1Y7akCmy7eTEk1eb0UYebUUUpsHl-PxvCblSI4hGGwDU/edit

Our site currently includes a page for this memorial item within the Burials and memorials hub:
https://www.va.gov/burials-memorials/memorial-items/presidential-memorial-certificates/

We can start to draft IA for this particular form and finalize once the forms digitization team gets to this work.

**Comment by jennymayoco** [comment]
#### Preliminary questions for team once Sitewide ticket is published:

- Will QuickSubmit be retired?
- Is there a timeline for when eligible recipients would have to submit a PMC?
- If a Veteran is buried in a national cemetery and the next of kin receives a PMC, is there an opportunity for other relatives to submit this form?
   - Is there a limit of PMCs for an individual Veteran?
   - The [current PMC page](https://www.va.gov/burials-memorials/memorial-items/presidential-memorial-certificates/) states “We’ll accept multiple requests for a PMC.”
     Although at the bottom of the page, it’s stated as “Please don’t send a second application unless we ask you to.”
- For content, will the page be reordered? Is there a pattern for forms, such as a "how to apply" page must exist? Would the H1 be updated?
    Example: https://www.va.gov/careers-employment/vocational-rehabilitation/how-to-apply/

#### Next steps

- [ ] Align with team once Sitewide ticket comes in
- [ ] Confirm who from CAIA will working on this, if applicable
- [ ] Update working draft

**Comment by jennymayoco** [comment]
[Draft IA spec](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/form-digitization-40-0247.md) - waiting on h1 to confirm URL recommendation

**Comment by mnorthuis** [comment]
@jennymayoco one modification to the redirect suggestion - the existing legacy content page should redirect to our modernized version of the content page about the PMC, not directly to the form.  That is a more accurate match of the purpose of the legacy page - to describe and inform.  Thank you!

**Comment by jennymayoco** [comment]
@mnorthuis Thank you for catching! I've updated the [draft IA spec ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/form-digitization-40-0247.md) redirect to the PMC details page.

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/122128479/e872535a-caf4-4e76-9c3f-f81745751a9d)

**Comment by mnorthuis** [comment]
One last thing, can you connect with the forms team to see if they have a contact at NCA (National Cemetery Administration) that they've been working with on this form?  I want to make sure that they connect with Beth P on this so they can coordinate any communication to stakeholders on the redirects.  Sometimes redirecting these legacy pages when they haven't asked is a sensitive topic.

**Comment by jennymayoco** [comment]
Hi @mnorthuis! Update re: contact at NCA - I checked in with the team and they suggested connecting with Danielle ([thread for context](https://dsva.slack.com/archives/C044AGZFG2W/p1690573671921829))

Looping in @DanielleThierryUSDSVA 👋 Would there be a best point of contact at NCA for proposing a redirect recommendation for form 40-0247? Screenshot above for reference of the proposed legacy page, we had chatted about this one briefly

**Comment by jennymayoco** [comment]
Here is the [IA spec for this form](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/form-digitization-40-0247.md).

- [x] Has been shared with the forms team
- [x] Has been shared with Megan

I have also updated the Burial hub site map and mega URL spreadsheet.

**Comment by jennymayoco** [comment]
Closing this ticket as feedback has been shared with team
