### ISSUE TITLE
Vets-api terminal access for [Drew Fisher]

### ISSUE THREAD

**Issue by cilestin** [department-of-veterans-affairs/va.gov-team#56716]
### E-QIP Transmittal Date

- [ ] Check this box if you have an E-QIP transmittal date.

### Your Name

Drew Fisher

### Your GitHub handle (terminal access is managed through GitHub)

@cilestin

### Team, Role, and Company of the target individual

Engineering Crew Lead, Lighthouse Benefits & Appeals APIs @ Ad Hoc

### Product Manager (PM) name and email

Michael Hobson, michael.hobson@adhocteam.us

### Product Owner (PO) name and email

Janet Coutinho, janet.coutinho@va.gov

### Your dsvagovcloud AWS user name (if applicable)

Drew.Fisher

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### COR Name (leave "None" if you listed an AWS user name above)

None

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

None

### Access Expiration

Ongoing

### Additional Notes

I will need ongoing access as I am one of the on-call production support personnel for the Lighthouse Benefits & Appeals APIs. Since I oversee multiple API teams, being able to quickly help any of those teams with their support issues is vital. 

### User must exist in a roster before vets-api terminal access can be granted

- [ ] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added
- [ ] If they included an AWS user name, check to see if their user name is listed in [iam_users.tf](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf)
- [ ] Comment in this issue saying which roster the user is listed in and confirming their AWS user name (if applicable)

**Comment by ryan-mcneil** [comment]
@cilestin  Your AWS user `Drew.Fisher` has been given access to the `dev`, `staging`, and `sandbox` environments.

Access to prod is pending, and we'll update you as soon as it's available.

Here's some additional documentation for the [Vets API on EKS](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-TerminalAccess)

**Comment by ryan-mcneil** [comment]
@cilestin Access to Prod has been been granted until July 17

**Comment by jknipes** [comment]
@cilestin Your ArgoCD/vets-api Production access has expired. Would you like to request an extension? You have 7 days to respond, or your access will be revoked and you will need to fill out a new request.

**Comment by jknipes** [comment]
@cilestin Per an update to our access policy, your ArgoCD/vets-api Production access has been extended for 3 months, expiring 10/24/23. Please set a reminder for yourself to return to this Issue and re-request access within 1 week of the expiration date. You'll receive 1 reminder with a 48 hour window to respond. Failure to do so will result in lost access and will require you to fill out a new request.

**Comment by jknipes** [comment]
@cilestin Your vets-api terminal Production access has expired.
Would you like to request an extension? 
You have 72 hours to respond, or your access will be revoked and you will need to fill out a new request.

**Comment by andreahewitt-odd** [comment]
@cilestin Can you confirm your eqip transmittal has occurred?
