### ISSUE TITLE
Analytics Implementation for VA.gov CMS

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-team#5673]
# Analytics Implementation or QA Request

## What this form is for
Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets. 

> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Onboarding
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

## Description
- Is this request for Google Analytics implementation or QA?

Google Analytics implementation 

- Who is this request for?

    - Kevin Walsh, PM 
     #cms-support (or #vfs-platform support)
    
- What team/project is this work for?
    
VA.gov CMS Team

- Provide the Domain where Google Analytics needs to be implemented

prod.cms.va.gov (same as cms.va.gov)
But we don't want to track staging.cms.va.gov or stg.cms.va.gov or dev.cms.va.gov or any other .cms.va.gov

   -  No PII tracked  
   - We would like to start tracking analytics within the next two weeks if possible. 

- Typical Website Interactions to Track

    - We're still figuring this out. it will be CMS editors, including contractors and VA staff. 
    
    - [URLs here]
    
    - *Other User Interactions*: _Provide details on other interactions and metrics, like click to help text links, that are helpful in understanding user behavior._
    
Here's our github issue: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/899 

We are interested in:
- What section a user belongs to
- What content dashboards people are using
- How often each moderation transition is used in editorial workflow
- Use of various CMS subsystems
- time spent on various tasks
- All data broken down by user permission role and by what section(s) they belong to
etc.

- Sample Users when authentication is required

CMS authentication, not VA.gov authenticatoin:
    - Editors at VAMC Pittsburgh
    - Members of vsa-public-websites team

- Test Users to replicate the event

  - n/a

- Additional Comments

i recognize this is not the typical use case for this form, please get in touch via #cms-support  #vfs-plastform-support on slack for more collaboration!

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by kevwalsh** [comment]
@nedierecel @joanneesteban We currently have a research spike (mentioned in the ticket), which will determine which data points we are tracking from within the CMS. Luckily Drupal already has great tooling to make this easy for many data points. We have a meeting next week to discuss what data points are the biggest priorities (vs level of effort)

**Comment by nedierecel** [comment]
@kevwalsh Thanks for completing this issue. I'll Slack you with a few availabilities with my teammate @jonwehausen. We'd like to get a walkthrough of Drupal to understand where we can add the GTM code. Thanks!

**Comment by ethanteague** [comment]
@nedierecel can you include me in this convo, as well? Thank you!
cc: @kevwalsh

**Comment by nedierecel** [comment]
Thanks @ethanteague I sent you the calendar invitation for 2/13.

**Comment by nedierecel** [comment]
@ethanteague Please see the GTM snippet for Drupal: 

This can be used on Dev and/or Staging. If this works, we will have a slightly different version for Production. 

Place in Head:
`<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl+ '&gtm_auth=GDc7Zfyf8G-0S5j8FC1WXQ&gtm_preview=env-5&gtm_cookies_win=x';f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-WQ3DLLB');</script>`

Place in Body:
`<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-WQ3DLLB&gtm_auth=GDc7Zfyf8G-0S5j8FC1WXQ&gtm_preview=env-5&gtm_cookies_win=x"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>`

Next Steps:
- [ ] Ethan - Confirm that the snippet can work without security issues
- [ ] Kevin - Figure out best way to provision credentials for Jon and Nedie to CMS

Once we determine it's working properly and have access, we can determine timing and what features can be tracked in MVP.

**Comment by ethanteague** [comment]
Awesome, @nedierecel. Q: Don't we need some kind of a click event tracker to test that we are getting through the network to google?

**Comment by ethanteague** [comment]
I've added the above snippets to this instance: http://pr1003.ci.cms.va.gov
I will send you login creds, privately, @nedierecel @jonwehausen 
cc: @kevwalsh

**Comment by nedierecel** [comment]
@ethanteague Returning back from the holiday yesterday. I published the changes with the pageview tag, so we should begin seeing activity today.

**Comment by nedierecel** [comment]
Round 1 QA - Jon and I did a validation and are not seeing the PV tag trigger. Jon will reach out to Ethan on next steps on missing <head> snippet.

**Comment by jonwehausen** [comment]
### v1.0 Datalayer Requirements - Pending @nedierecel's Review

### Site-wide taxonomy 
1) **Push the following dataLayer code on page load -- Please see section/content page differentiation in the table below**
```javascript
dataLayer.push({
   'pagePath': '<urlAlias>/<nodeID>/{edit|workflow-participants|delete|revisions|entityqueue|entity_clone}',
   'pageTitle': '<Content Title Name> | <Node ID> | {Edit|Workflow Participants|Delete|Revisions|Entity Queue|Entity Clone}',
   'primarySection': '{Veterans Affairs | National Cemetery Administration | Veterans Benefits Administration | Veterans Health Administration | Global UX}',
   'secondarySection': '<first level dropdown>', 
   'tertiarySection': '<second level dropdown>', 
   'contentName': '<content name>',
   'contentType': '<content type>',//populate according to content type 
   'contentOwner': '<content owner>'
});
```
**Datalayer Variable** | **How to Populate** | **Example**
--------- | --------------------------- | -------------------------- | 
`pagePath` | **FOR CONTENT LANDING PAGES**: A concatenation of _urlAlias_, _nodeId number_, and _tab label_ delimited with "/" <br> **FOR SECTION LANDING PAGES** (_where the URL is most likely `/taxononmy`_): Append {`/view`\|`/edit`\|`/clone`} to existing URL on VIEW tab |  **CONTENT LANDING PAGES** page path full example: "_/health-care/67/edit_" <br> **SECTION LANDING PAGES** page path full example: "_/section/health-care-benefits-hub/view_" |
`pageTitle` | A concatenation of the **content title name** and **tab label text** separated by "\|" ![image](https://user-images.githubusercontent.com/48527022/75492585-13267a80-5986-11ea-9741-40ebafdf5f96.png) | Full page title: _VA Health Care_ \| _Edit_
`primarySection` | Top level navigation header text ![image](https://user-images.githubusercontent.com/48527022/75492882-b24b7200-5986-11ea-99ec-ffe79559a521.png) | If the user is on the Pittsburgh Health Care content landing page, this variable would populate with `'Veterans Affairs'`
`secondarySection`  | Second-level hierarchy header text |If the user is on the Pittsburgh Health Care content landing page this variable would populate with `'VHA Facilities'`
`tertiarySection`  | Third-level hierarchy header text | If the user is on the Pittsburgh Health Care content landing page, this variable would populate with `'VISN-4'`
`contentTitle` | Content named identified by content heading  | `VA Health Care`
`contentType` | Content type according to content type listed | `Benefits hub landing page`
`contentOwner` | Content owner according to content owner listed | For VA health care for example: e`Veterans Health Administration`

**Dev Notes**
- Items in contained in {} indicate a sample of possible values
- Populate with `null` for those variables such as `tertiarySection` that may or may not be surfaced

### Event Tracking
**Datalayer Code** | **Description Of Interaction** | **Screenshot** | **Google Analytics Event Naming Taxonomy**
--------- | --------------------------- | -------------------------- | -------------------------- |
```dataLayer.push({'event': 'top-level-nav'});```| Click on a top level section | ![image](https://user-images.githubusercontent.com/48527022/75498732-f6923e80-5995-11ea-8f93-85f246ded428.png) | **Event Category**: Interaction <br> **Event Action**: Navigation - Top-level - <header_name> <br> **Event Label**: top-level-nav
```dataLayer.push({'event': 'lower-level-nav'});```| Click on any lower level section | ![image](https://user-images.githubusercontent.com/48527022/75498904-78826780-5996-11ea-8d9d-9e763a62b0a5.png) | **Event Category**: Interaction <br> **Event Action**: Navigation - Lower-level - <header_name> <br> **Event Label**: lower-level-nav
```dataLayer.push({'event': 'content-edit'});```| Click on content edit button | ![image](https://user-images.githubusercontent.com/48527022/75498479-4d4b4880-5995-11ea-8a9c-12c9d515faa1.png) | **Event Category**: Interaction <br> **Event Action**: Button CTA - Edit <br> **Event Label**: content-save
```dataLayer.push({'event': 'content-save'});```| Click on content save button  | ![image](https://user-images.githubusercontent.com/48527022/75498546-74097f00-5995-11ea-9a4a-2ba167e5b5d1.png) | **Event Category**: Interaction <br> **Event Action**: Button CTA - Save <br> **Event Label**: content-save
```dataLayer.push({'event': 'content-preview'});```| Click on content preview button | ![image](https://user-images.githubusercontent.com/48527022/75498644-ba5ede00-5995-11ea-93b2-1ffd407e7b4a.png) | **Event Category**: Interaction <br> **Event Action**: Button CTA - Preview <br> **Event Label**: content-preview
```dataLayer.push({'event': 'content-save-and-continue'});``` | Click on save and continue button | ![image](https://user-images.githubusercontent.com/48527022/75498585-8c799980-5995-11ea-8a39-a133c45b0b3c.png) | **Event Category**: Interaction <br> **Event Action**: Button CTA - Save & Continue <br> **Event Label**: content-preview
```dataLayer.push({'event': 'content-unlock'});``` | Click on unlock button | ![image](https://user-images.githubusercontent.com/48527022/75498612-9ef3d300-5995-11ea-800f-5cc181c6d75c.png) | **Event Category:** Interaction <br> **Event Action**: Button CTA - Unlock <br> **Event Label**: content-preview

**Comment by jonwehausen** [comment]
cc: @nedierecel @ethanteague @kevwalsh

Potential thought for the group, if this would be easier and possible -- There is a plugin (called **pathauto**) that helps automate pagepaths for various kinds of content. 

See here: https://www.drupal.org/project/pathauto

**If this is feasible, we would then be able to pass the URL alias the plugin returns and pass to the dataLayer**

**Comment by ethanteague** [comment]
> cc: @nedierecel @ethanteague @kevwalsh
> 
> Potential alternative solution for the group, if this would be easier and possible -- There is a plugin (called **pathauto**) that helps automate pagepaths for various kinds of content.
> 
> See here: https://www.drupal.org/project/pathauto
> 
> **If this is feasible, we would then be able to pass the URL alias the plugin returns to the dataLayer**

Hey @jonwehausen - appreciate you thinking on this! Your hunch is right about pathauto. We are currently using it, and will be leveraging it to grab those aliases on push.

**Comment by jonwehausen** [comment]
@ethanteague We are ready to begin dataLayer implementation as outlined [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/5673#issuecomment-592247479)

Please let us know if you have any questions

**Comment by ethanteague** [comment]
@swirtSJW - this is the analytics task we were talking about.

**Comment by jonwehausen** [comment]
### Datalayer QA Testing

cc: @ethanteague @kevwalsh @nedierecel @joanneesteban 

#### Side-wide taxonomy
- We're seeing the side-wide code being pushed in conjunction with the event fires: if we could request the site-wide code be pushed upon on each new page load this will aid us in a more robust way to capture pageviews + basic OOB metrics across the board
- Ideally, each new page load / refresh should have 4 items within the dataLayer -- with the fourth being our global page load event push - apologies the first ```event``` line was missed in the initial requirements post, this has been updated [above](https://github.com/department-of-veterans-affairs/va.gov-team/issues/5673#issuecomment-592247479) to reflect
![image](https://user-images.githubusercontent.com/48527022/77072227-bede4b80-69c3-11ea-90d4-231337a10bbb.png)

- Once we get that corrected, we'll be able to do a more thorough QA of actual Datalayer values here

#### Event Tracking
Description of Interaction | Screenshot of DL push | Testing Status
------------ | ------------- | ------------ 
Click on any top level section | ![image](https://user-images.githubusercontent.com/48527022/77071148-eaf8cd00-69c1-11ea-8554-f9a916abe664.png) | ✅ **Passed**  |
Click on any lower level section | ![image](https://user-images.githubusercontent.com/48527022/77069082-25606b00-69be-11ea-9c9d-5d07db256948.png) | ✅ **Passed** 
Click on content edit button | ![image](https://user-images.githubusercontent.com/48527022/77069484-e2eb5e00-69be-11ea-984f-fa0deb72eb5b.png) | ➖ **Does not pass**
Click on content save button | ![image](https://user-images.githubusercontent.com/48527022/77070479-ade00b00-69c0-11ea-87fc-0721df2ba406.png) | ✅ **Passed**
Click on content preview button | ![image](https://user-images.githubusercontent.com/48527022/77069756-67d67780-69bf-11ea-9866-02e3e62ff221.png) | ✅ **Passed** 
Click on save and continue button | ![image](https://user-images.githubusercontent.com/48527022/77070673-0c0cee00-69c1-11ea-99ab-32c41e691809.png) | ✅ **Passed**
Click on unlock button | ![image](https://user-images.githubusercontent.com/48527022/77070824-52fae380-69c1-11ea-9753-f4501b833b54.png) | ✅ **Passed**

**Next Immediate Steps**
1) Correct those items outlined here and our team will re-review
2) Our team will need to connect with devops on getting Google Tag Manager preview mode lifted to verify our tag configuration as it relates to the dataLayer

**Comment by jonwehausen** [comment]
## Round 2 QA - with GTM Preview Mode now accessible

### Items to Correct - @ethanteague 

#### Page Load Event
1) We are noticing a handful of ```pagePath``` variables that are ```null``` on the ```pageLoad``` event -- we can easily set a condition within GTM to use the Page Path inherent within the URL when the pagePath is not called out within the DL, however calling out for visibility.  
2) We are also noticing there are certain pages where the ```pageLoad``` event is being pushed multiple times -- this of course should only be pushed once for each new page. Please notice this example from [Pension benefits hub](http://pr1003.ci.cms.va.gov/section/veterans-benefits-administration/pension-benefits-hub). We'll need this correction to not inflate pageviews. 
![image](https://user-images.githubusercontent.com/48527022/77564862-c1e0ac80-6e99-11ea-8519-9c6377eee988.png)
3) If we could request to consolidate the ```pageTitle``` variable to simply the raw title that would be preferable. In other words simply ```pageTitle: 'Pension benefits hub``` in this example: 
![image](https://user-images.githubusercontent.com/48527022/77566257-c73ef680-6e9b-11ea-8c38-64779da259e3.png)

#### Event Tracking
1) As noted from earlier QA, the events seem to be firing at their appropriate times -- **however there are variables within the DL that appear to be missing on certain interactions**: Here is an example of an "Edit" button click that is passing ```null``` for values surfaced. In this case, the ```content-edit``` event is correct and the DL variables associated are ```null```. The variables and their needed values are mapped with the black lines below. This consistently should be universal where appropriate: 
![image](https://user-images.githubusercontent.com/48527022/77565655-edb06200-6e9a-11ea-99d9-8e8e6d7f5688.png)
------------------------
### Correct Example for Context - @ethanteague 
For context, [here is an example page ](http://pr1003.ci.cms.va.gov/node/590/workflow-participants)where the preview button was clicked and all values populated correctly 👍 ✔️ 
![image](https://user-images.githubusercontent.com/48527022/77566843-a034f480-6e9c-11ea-932c-1313ced69463.png)

**Comment by jonwehausen** [comment]
## 3.27 QA - @ethanteague 

### Resolved
_Thanks for making the corrections! the following issues have been resolved:_
- Navigating tabs 'View' > 'Edit' on a content page is no longer is firing multiple ```pageLoad``` events 👍 
- ```pageTitle``` is no longer populating with #markup in the dataLayer 👍 

### Items to correct
1) Tested on this [page](/node/3067/edit) and saw multiple ```content-save``` events pushed on 'Save' button click
![image](https://user-images.githubusercontent.com/48527022/77750645-8e696380-6ffa-11ea-9a0c-43b0bd7d104d.png)
2) Tested on [same page]([page](/node/3067/edit)) and saw multiple ```content-save-and-continue``` events pushed on 'Save and continue editing click'
![image](https://user-images.githubusercontent.com/48527022/77750921-0fc0f600-6ffb-11ea-9e35-3e29dd26ba06.png)
3) Tested a 4 tier navigation to 'VA Pittsburgh health care' and multiple ```lower-level-nav``` events fired with DL vars identifying 'VA Wilmington' instead of Pittsburgh
![image](https://user-images.githubusercontent.com/48527022/77751527-44817d00-6ffc-11ea-8d63-92befd48b881.png)
4) General request -- Could we attach ```.trim()``` or comparable function to each dataLayer variable to ensure we're always ingesting the value with no additional whitespace, avoiding these scenarios: 
![image](https://user-images.githubusercontent.com/48527022/77750185-bf956400-6ff9-11ea-8ae8-3713ada29f64.png)

**Comment by ethanteague** [comment]
Thanks, @jonwehausen :+1: - updated

**Comment by jonwehausen** [comment]
@ethanteague Thank you for making these updates!

Looks like we are now squared away on the duplicate event fire. 👍 

### **Here are the remaining issues we are seeing:** 
1) Comparable to the #3 test scenario above  still remain is from #3 referenced above. The ```lower-level-nav``` event doesn't appear to populate with the correct metadata when clicking on 'VA Pittsburgh Health Care,' from the navigation for example. 

2) We are also noticing that on 'Edit' button clicks the metadata within the event appears to populate with the metadata what appears to be the data for the content item directly below. In this example, we click on the edit button for VA health care but received metadata for "Operating status - VA Pittsburgh health care". This screenshot also contains additional whitespace for ```contentType```. 
![image](https://user-images.githubusercontent.com/48527022/78165393-42168d00-7419-11ea-934e-1a88a82ff0fc.png)

Thank you again for all of your efforts here @ethanteague

**Comment by jonwehausen** [comment]
Hi @ethanteague - Update 4.8.2020

1.**DID NOT PASS** Went thru another round of QA and was not noticing metadata for the `lower-lever-nav` event:
![image](https://user-images.githubusercontent.com/48527022/78829437-57a92b00-79b4-11ea-9712-a72533876d5e.png)

2. **DID NOT PASS** We are noticing the same issue as described above the `content-edit` button clicks. In this example, the edit button for "VA nurse gives a family the chance to say goodbye" and we noticed the following: 
![image](https://user-images.githubusercontent.com/48527022/78830196-8f64a280-79b5-11ea-94c7-1f9a701ad25f.png)

**Comment by jonwehausen** [comment]
@ethanteague - 4.9.2020

### Retests previously failed scenarios

### Test Scenario 1- ✅ **PASSED**
- Navigated to an arbitrary page, in this case http://pr1433.ci.cms.va.gov/section/veterans-affairs and clicked on the `Edit` button
![image](https://user-images.githubusercontent.com/48527022/78917509-ef625400-7a5c-11ea-8429-6657623fbc20.png)

### Test Scenario 2 - ✅ **PASSED**
- From this page: http://pr1433.ci.cms.va.gov/section/veterans-affairs performed the navigation sequence to click on "VA Pittsburgh Health care" 
![image](https://user-images.githubusercontent.com/48527022/78918264-22591780-7a5e-11ea-8953-b893ef91b4ca.png)

**Comment by jonwehausen** [comment]
@bsmartin-ep -- Can I request you to do QA on my tagging for the events and functionality? If your SOCKS proxy is still taking some time to get up and running -- @joanneesteban this may be a case where I need to do QA of my own GTM tagging work now that @ethanteague has the DL where it needs to be.

**Comment by jonwehausen** [comment]
@bsmartin-ep Could you give my workspace "Event Tagging Config" it's QA now that we have the dataLayer where it needs to be?

**Comment by bsmartin-ep** [comment]
@jonwehausen -

_contentTitle_ has been added to the last 3 events:

![image.png](https://images.zenhubusercontent.com/5e73c8e4b62b077da52f1c14/aad64bd1-e540-4fff-9806-3324054fdea5)
---
I have some concern about these un-trimmed values but I'll defer to you if the devs need to fix this.  

![image.png](https://images.zenhubusercontent.com/5e73c8e4b62b077da52f1c14/7e6a4a08-8ba6-4789-8d36-be3987a283e5)
---
And we may want to look at adding tracking to this top top toolbar in the future.

![image.png](https://images.zenhubusercontent.com/5e73c8e4b62b077da52f1c14/7067655c-f4ae-466c-9a33-4901b6c336c0)
---
Other than that looks good to me.  Let me know if you want to publish today or schedule for early AM Monday.

**Comment by ethanteague** [comment]
> @jonwehausen -
> 
> _contentTitle_ has been added to the last 3 events:
> ## ![image.png](https://camo.githubusercontent.com/7323e29d548016cb91d3c05fc6cee4c304fc882f/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3565373363386534623632623037376461353266316331342f61616436346264312d653534302d346666662d393830362d333332343035346664656135)
> 
> I have some concern about these un-trimmed values but I'll defer to you if the devs need to fix this.
> ## ![image.png](https://camo.githubusercontent.com/c1ad29bf019b6620c6dbe217a3c08a2d4db6c04b/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3565373363386534623632623037376461353266316331342f37653661346130382d386261362d343738392d386433362d626533393837613238336535)
> 
> And we may want to look at adding tracking to this top top toolbar in the future.
> ## ![image.png](https://camo.githubusercontent.com/8cfc89615dd29feddf701bbd13ef1c9987cd7237/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3565373363386534623632623037376461353266316331342f37303637363535632d663461652d343636632d396133332d343930316236633333366330)
> 
> Other than that looks good to me. Let me know if you want to publish today or schedule for early AM Monday.

Ah - glad you caught that. I just removed, @jonwehausen @bsmartin-ep

**Comment by jonwehausen** [comment]
@ethanteague @kevwalsh @bsmartin-ep @joanneesteban 

Thank you for your patience and hard work on this request -- this has been published out! You should begin seeing pageviews and events immediately within the ["CMS Development Environment - Prod CMS" Google Analytics view](https://analytics.google.com/analytics/web/#/report-home/a50123418w196569434p211458524).
