### ISSUE TITLE
convert review instances to use the BRD base-os role

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#5675]
## User Story or Problem Statement

Right now the review instance provisioning happens using the old `roles/base-os` role for getting all of the baseline OS stuff done. This role is no longer used by anything else and should be using the `ansible/build/roles/common/base-os` role. Same name, slightly different :(

One way to validate that you got the right role is if the instance has the standard government motd thing. As far as I can tell, the old role never had that, so it's a good sanity check to make sure you got the right thing. Once review instances are using the "new" base-os role, we should be able to delete the old one and any dependencies.

## Goal
Be able to remove the `ansible/roles/base-os` role from the devops repo and still have review instances provision successfully.

## Objectives or Key Results this is meant to further
O1: Any volume of simultaneous customers have a delightful, self-service, end-to-end experience using the Platform to build on VA.gov.				

## Acceptance Criteria
- [x] `ansible/roles/base-os` role is deleted from the repo, review instance provisions successfully
- [x] review instances get the government warning motd when you login

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ricetj** [comment]
@wyattwalter  update ticket

**Comment by jbritt1** [comment]
![image](https://user-images.githubusercontent.com/56260532/74958958-c831c380-53d7-11ea-9589-72c0bdc58e91.png)
