### ISSUE TITLE
AWS permissions* for Evan Ubiera

### ISSUE THREAD

**Issue by eubiera** [department-of-veterans-affairs/va.gov-team#56757]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### E-QIP Transmittal Date

- [ ] Check this box if you have an E-QIP transmittal date.

### Your Name

Evan Ubiera

### Your Email

evan.ubiera@thoughtworks.com

### Team, Role, and Company of the target individual

Developer

### Product Manager (PM) name and email

Alina Murphy, alina.murphy@va.gov

### Product Owner (PO) name and email

Luciana Morais, luciana.morais@va.gov

### Desired AWS Access

I was wondering how I can access to actual S3 buckets for dev and staging. 

Currently I get these errors when trying to view or edit an S3 bucket:

_You need s3:GetAccountPublicAccessBlock, s3:GetBucketPublicAccessBlock, s3:GetBucketPolicyStatus, s3:GetBucketAcl and s3:ListAccessPoints permissions to perform this action._

I am only considering accessing dev and staging. 

### Access Expiration

04-12-25

### E-QIP Transmittal Confirmation

<img width="701" alt="EQIP-confirmation" src="https://user-images.githubusercontent.com/117054459/231504632-e177f96b-c7f3-4d63-b054-493494ab4c1f.png">

### Additional Notes

I only need this access to upload images for a prototype demo we're doing for stakeholders. 

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by considerable** [comment]
@eubiera 

Existing AWS user Evan.Ubiera already has developer's and prod access.
There are many s3 bucket access patterns for dev and staging with the following search returning a sorted list of them:

```
grep -r s3: * | grep -E "staging|dev" | cut -d\" -f2 | sort -u 
```
So that the request needs to be narrowed to particular buckets or supported with an example of other user having the correct access for us to copy.

**Comment by considerable** [comment]
@eubiera needs to upload images into these s3 buckets:

- dev-va-gov-assets
- staging-va-gov-assets

to better suit the need, we may change from the `read everything` access into the `read+write for only these two buckets` access upon approval from @BillChapmanUSDS

**Comment by BillChapmanUSDS** [comment]
Access approved for Dev and Staging
