### ISSUE TITLE
Review Instances - better discoverability of documentation

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#5677]
## User Story or Problem Statement

Information about review instances are pretty sparse and just discovering their existence isn't something I would expect many developers to even be able to do on their own right now. How might we make their presence more obvious and known?

They show up in GitHub's deployment in pull requests, but the information there is very limited. You get a link to the front-end and a link to the Jenkins job that ran the provision. Without more information, you wouldn't also know what's available or how to get full use of them.

## Goal
_What outcome(s) do we want to see?_

## Objectives or Key Results this is meant to further
- _lorem ipsum_

## Acceptance Criteria
- [ ] _What needs to happen or be created?_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by wyattwalter** [comment]
Not sure what direction we should go here yet, but going to drop some brainstorming and testing I did so far:

We can't seem to influence the deployment information in the GitHub UI currently, so adding more text in a description on the deployment itself is a no-go.

We could build a UI that consumed the description information and used the GitHub API as its source of truth.

One thing I noticed is that we can probably support using the same hostname for SSH that we'd use for the web UI, but it's not working at the moment. Would like to dig into that.

An idea that I had is to create a `/_vfs/info` endpoint (or something like that) where we could stash some information and/or help on the instances. We could even point the `environment_url` field to this link instead of the homepage of the website.

**Comment by jhouse-solvd** [comment]
@drorva & @f1337 - found this ticket which speaks to us wanting to clarify documentation around review instances. Moving this forward into our current sprint for me to at least refresh and harvest anything that can be used in our current efforts.

**Comment by rmtolmach** [comment]
The QA Standards team is doing discovery for review instances. This can be closed.
