### ISSUE TITLE
Retrieve 30 day of EDIPI's from Claim Status Tool Usage

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#5678]
Public Slack Channel:
https://dsva.slack.com/archives/CTFV03BSP

## User Story or Problem Statement
The majority of calls coming to the National Call Center are referencing the Claim Status Tool.  The Call Center team (Chante) is digging into to get a sense of how many people who use the claim status tool end up still calling the call center to get help with understanding or checking their claim status.  

In order to correlate calls with attempted usage of the claim status tool, they are asking if we could pull out specific data to share with the NCC for comparison.

## The current proposed plan
- In our VA.gov server logs, we log ID.me UUID along with each request
- This should allow us to pull a list of all of the claims status lookup events that happened in the past 30 days, along with a UUID.
- We also maintain an account database, includes a list of user accounts. This database has ID.me UUID and EDIPI (when we have it)
- Therefore, we should be able to:
     - Get a list of all claims status lookups going back X number of days (30)
     - Use the UUID to lookup a corresponding EDIPI in our account database
     - End result is a CSV file, one row per claim status lookup, with a timestamp/date, and an associated EDIPI
- Then Chante sends that to NCC (via Skype since that’s encrypted)

## Acceptance Criteria
- [x] Provide a csv file to Chante with the EDIPIs of all users who attempted to use the Claim Status Tool.

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kfrz** [comment]
Basic outline of what happend to get this:

- Pull all logs for the time that include the `EVSS` pathways 
- Parse logfiles for payload entries, extracting user UUID and ensuring uniqueness
- Take list of UUID and lookup each corresponding EDIPI 
- Build CSV from this lookup
- Encrypt CSV and deliver to NCC via Skype

ttps://github.com/department-of-veterans-affairs/vets-api/blob/claim-status-lookup-investigation/claims-status/get_claims_logs.rb
