### ISSUE TITLE
When should VAOS clear form data?

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#5679]
There are three scenarios where we could additionally clear form data:

1. When you are in the middle of the form and click the breadcrumbs to go back to the appointment list
2. When you click the form back button on the type of care page.
3. When you click the browser back button on the type of care page

Currently form data is cleared when you:

1. Leave the confirmation page to go back to the appointment list or create a new appointment
2. Leave the app by going to a page not underneath `/health-care/schedule-view-va-appointments/appointments`. In this case, we warn you that will lose form data.

**Comment by lenaecb** [comment]
Need to review this with @lalexanderson-dsva to ensure we treat the data clear based on standard VA.gov expectations/business rules.

**Comment by jbalboni** [comment]
There are three scenarios where we could additionally clear form data:

1. When you click the breadcrumbs to go back to the appointment list
2. When you click the form back button on the type of care page.
3. When you click the browser back button on the type of care page

Currently form data is cleared when you:

1. Leave the confirmation page
2. Leave the app by going to a page not underneath `/health-care/schedule-view-va-appointments/appointments`. In this case, we warn you that will lose form data.

**Comment by jbalboni** [comment]
@lalexanderson-dsva I tried to update the description of this issue with scenarios around when to clear form data. If you want to walk through this on a call, we can, or if you want to take a look at the scenarios and decide if any of the three are ones where we should clear data, that works, too.

**Comment by lalexanderson-dsva** [comment]
@jbalboni My understanding of the current pattern for clearing forms is: "stuff that will never change, doesn't get cleared". I think in VAOS case, the opposite is more often true. It might be safe to say that stuff which always gets changed gets cleared. Is it possible that it only gets cleared when the process is complete? (i.e. submitted request/appointment, confirmed cancellation?) 

In all three of the cases below, is there a good way to get back to the appointment scheduler? 
**1. When you are in the middle of the form and click the breadcrumbs to go back to the appointment list**
- I would be really frustrated if i was in the middle of the scheduling tool and accidentally clicked on the breadcrumb to go to the appointment list/new appointment button. If I clicked back in my browser, I would want to have the data to that point saved, if possible. If i clicked on the "new appointment" button, I would expect to start a new appointment. 

**2. When you click the form back button on the type of care page.** 
From the type of care page, I think if you hit back, you haven't gotten very far into the process, so we don't have to save where you were. 

**3. When you click the browser back button on the type of care page**
From the type of care page, I think if you hit back, you haven't gotten very far into the process, so we don't have to save where you were.

**Comment by jbalboni** [comment]
@lalexanderson-dsva To answer your first part, that's the process now, basically, we only clear form data after submission (or when someone leaves/refreshes the app and it's cleared for us). 

We have two "new appointment" buttons, one on the confirmation page and one on the appointment list page. In all three of my scenarios, you'll end up on the list page, where there's a new appointment button.

Keeping data is less work for us and it doesn't sound like you have a strong opinion about 2 and 3 above, so we could do something like this:

- Whenever you click on a "new appointment" button, your form data is reset and you have a clean place to start. 
- When you leave the app, you will lose data, and we will notify you before this happens
- Otherwise, we keep your form data in place

**Comment by lenaecb** [comment]
@jbalboni - I like you suggestions. Let's move forward with that iteration of the clear data behavior. If we need to adjust in the future we can.
