### ISSUE TITLE
EVSS Migration: BDex Team Veteran Verification API credentials

### ISSUE THREAD

**Issue by ahay-agile6** [department-of-veterans-affairs/va.gov-team#56794]
We need to make sure our Veteran Verification API credentials get pushed to the higher environment.

A way to test this is to switch our API provider on staging to Lighthouse and see if Rated Disabilities show up in the 526 flow.

- dev endpoint will suffice for this test
- need AWS access
- do we need approvals?
- lots of unknowns so some discovery work maybe needed

Slack thread - 
https://dsva.slack.com/archives/C02CQP3RFFX/p1680734479565489

Acceptance Criteria:
- Switch our API provider on staging to Lighthouse and  Rated Disabilities shows up in the 526 flow(/flipper/features)
- Create another ticket if needed after the completion of this ticket

**Comment by navaeddie** [comment]
Resources to review, they may be helpful:
- [Seth's Notes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/disability-experience/team-docs/LH%20API%20Notes.md)
- [VA Docs on Adding to Parameter Store](https://depo-platform-documentation.scrollhelp.site/developer-docs/store-a-secret-in-parameter-store#How-secrets-are-organized)
- [VA docs on accessing AWS](https://depo-platform-documentation.scrollhelp.site/developer-docs/aws-shell-access)

**Comment by navaeddie** [comment]
Questions arising from engineers meeting,

> what is the workflow for creating environment variables? (for instance, what do we add/change  in the devops repo? what do we add/change in the vsp-infra-application-manifests repo?)
> what is considered "secret"? what do we need to hide? some teams are hardcoding in the settings file and only switching the host url, some teams are "hiding" the aud url for authentication but showing the client id and rsa key path in the main public repo
> do we need a client_id per lighthouse api? in other words, can we use another team's settings block for the same lighthouse service configuration?

**Comment by sethdarragile6** [comment]
We were so close! But this will have to carry over to next sprint. We have 2 PRs ready to merge in to
- [vets-api](https://github.com/department-of-veterans-affairs/vets-api/pull/12467)
- [vsp](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/1848)
but this one got a late start
- [devops](https://github.com/department-of-veterans-affairs/devops/pull/12917)
and so still needs a BDEx1 and devops team review to call it done.

**Comment by ahay-agile6** [comment]
We were able to see our credentials in ArgoCD by printing out the environment variables added and seeing the rsa key in the application pods.
Furthermore, we tested the connection to Lighthouse from the application with our LighthouseApiProvider in the console.

:tada:**_It worked!_** :tada:

### Notes:

-For those not familiar with kubernetes, **pod = container** 
-For those not familiar with containerization in general, **container = running application image**
- We need to follow up with Lighthouse about their test data. When testing the rated_disabilities endpoints, we were getting 404 using their test user data ICNs, which means there was no data found for the Veteran.

## ArgoCD UI URL:
https://argocd.vfs.va.gov/applications/

## Go to the <environment (dev|staging|sandbox)> Pod:
https://argocd.vfs.va.gov/applications/vets-api-staging?resource=&node=%2FPod%2Fvets-api%2Fvets-api-web-6f859cdb5b-zklhh%2F0&tab=exec

Click on one of the running vets-api-<environment>-web-* pods (usually to the far right

You should be able to run normal developer things like
```
bundle exec rails c
```

## Print out our environment variables in the Terminal
```
printenv | grep FORM526
```

## check if our rsa key is in place
ls -la <path to rsa_key found in parameter store>

## Request ArgoCD GUI Terminal access
https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=external-request%2Cplatform-tech-team-support%2Cops-access-request&template=vetsapi-argo-terminal-access.yaml&title=Vets-api+terminal+access+for+%5Bindividual%5D

Aurora's ticket for reference: https://github.com/department-of-veterans-affairs/va.gov-team/issues/57530

## Next Steps
Testing the Lighthouse responses in a higher environment brought to "light" - pun intended - an important factor that was not seen while developing the ApiProvider about how the application was expecting EVSS to work vs. Lighthouse (or any reliable provider).

Documented in this ticket #57603.

Our recommendation is to pick up this ticket right away.
