### ISSUE TITLE
Update the spacing for the Upcoming, Pending and Past links 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#56790]
## Description
We completed the work to add the navigation links to each status page (Upcoming, Pending and Past) in ticket #56164. 
We are requesting to make a minor update the spacing of the links. 

---

## Acceptance Criteria
Background: the `va_online_scheduling_appointment_list` toggle is on

- [ ] Update the space for the navigation links for each acceptance criteria

1. Given when the user is on the Upcoming view
When the user clicks on Pending
Then user will see Upcoming and Past links in the Pending status page

2. Given when the user is on the Pending view
When the user clicks on Past
Then user will see Upcoming and Pending links in the Past status page

3. Given when the user is on the Past view
When the user clicks on Upcoming
Then user will see Pending and Past links in the Upcoming status page

### Design Assets
[Design Specs](https://www.figma.com/file/XmvY7ijIOTPgfQ3cTXodJD/Subnavigation?node-id=13%3A33&t=2Chc82kvPC9URFvF-1)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by jenniemc** [comment]
@leah, @Cieramaddox, All spacing in the Upcoming, Pending and Past appointment list is updated per design spec except for mobile view in Past appointment. 

**Styling Limitation on Past appointment list for Mobile breakpoint:**
The breadcrumb is assigned with margin bottom of 16px per the design spec. However the label, "Select a date range", is part of the VA web component construct. Label is assigned with a top margin of 30px which overrides breadcrumb's bottom margin (16px). I am not able to target the label selector to give it a top margin of 0px. I mentioned the style limitation during standup.
<img width="1446" alt="Screenshot 2023-04-20 at 5 45 54 PM" src="https://user-images.githubusercontent.com/54327023/234114338-6b85c416-96d1-476c-99bd-68422ae6ec75.png">

**Comment by ldelacosta** [comment]
@Cieramaddox - please validate in staging and let me know if you have any questions or issues. Thanks!

**Comment by ldelacosta** [comment]
No new issues reported. Closing out the ticket.
