### ISSUE TITLE
Update urls in megamenu

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#56792]
## Issue Description

Content was recently migrated to department.va.gov and Josh Tuscher asked us to change the urls in the About VA section of the megamenu to reflect this.

The links with new urls are as follows:

[About VA](https://department.va.gov/about/)
[History of VA](https://department.va.gov/history/)
[VA plans, budget, finances, and performance](https://department.va.gov/about/va-plans-budget-finances-and-performance/)
[All VA offices and organizations](https://department.va.gov/about/)
[Public Affairs](https://department.va.gov/administrations-and-offices/public-and-intergovernmental-affairs/)
[VA Leadership](https://department.va.gov/biographies/?_bio_position=assistant-secretary%2Cchairman%2Cdeputy-secretary%2Cgeneral-counsel%2Cinspector-general%2Cprincipal-executive-director%2Csecretary%2Cunder-secretary%2Cva-chief-of-staff%2F%3Fredirect%3D1%2Cva-chief-of-staff) 
[Agency Financial Report](https://department.va.gov/administrations-and-offices/management/finance/agency-financial-report/) (this is in the promo to the right)

## Tasks
- [x] Update menu items
- [x] Copyedit (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] New urls are live on the site

**Comment by megzehn** [comment]
Randi and I updated all the links here in the megamenu except for **VA Leadership**. We got an error when we tried to enter this link:
https://department.va.gov/biographies/?_bio_position=assistant-secretary%2Cchairman%2Cdeputy-secretary%2Cgeneral-counsel%2Cinspector-general%2Cprincipal-executive-director%2Csecretary%2Cunder-secretary%2Cva-chief-of-staff%2F%3Fredirect%3D1%2Cva-chief-of-staff

**Comment by RLHecht** [comment]
Moving to blocked until the CMS team can resolve the issue of having too long of a url for Drupal to accept.

**Comment by RLHecht** [comment]
Reached out to the CMS support team again 5/23 to ask if there's been progress on this.

**Comment by RLHecht** [comment]
The CMS team resolved the issue with the last url so I updated the megamenu and published. Moving to validate and will confirm once it's live.

**Comment by RLHecht** [comment]
These changes are now all live. Closing ticket.
