### ISSUE TITLE
Sign-in Service App - Architecture Diagram

### ISSUE THREAD

**Issue by rileyanderson** [department-of-veterans-affairs/va.gov-team#56817]
## Issue Description
Sign-in Service Application needs an architecture/network diagram to aid in app and infrastructure development. The application will live within the Platform EKS infrastructure. 

## Known
- [ ] Platform EKS
- [ ] ECR Repo
- [ ] Parameter Store 
- [ ] GitHub Actions CI/CD
- [ ] Rails application
- [ ] RDS - Postgres
- [ ] Elasticache - Redis
- [ ] Forward Proxy

## Maybe?
- [ ] Reverse proxy 

## Acceptance Criteria
- [ ] Diagram created and shared 
- [ ] Documentation has been updated
- [ ] Next steps have been determined and documented

#### Tech notes

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by joeniquette** [comment]
Diagram nearly completed: https://lucid.app/lucidchart/736e1365-e6dd-4aee-b18b-b2e7f4ff003b/edit?invitationId=inv_94add3b1-3c31-4d13-a067-e31cc93d0fbe&page=r8l0CCVxOJlc#

**Comment by joeniquette** [comment]
Diagram created and presented to Vid and Riley on 6/13/23: https://lucid.app/lucidchart/736e1365-e6dd-4aee-b18b-b2e7f4ff003b/edit?invitationId=inv_94add3b1-3c31-4d13-a067-e31cc93d0fbe&page=r8l0CCVxOJlc#
