### ISSUE TITLE
Documentation support

### ISSUE THREAD

**Issue by BillChapmanUSDS** [department-of-veterans-affairs/va.gov-team#56821]
### Request type

- [X] Writing new documentation
- [X] Updating previously published documentation
- [ ] Reviewing recently written, never-before-published drafts

### Number of docs

1

### Subject matter expert

Eric Boehs and Bill Chapman (platform Team SRE) `

### Embedded media

- [ ] Screenshot(s)
- [ ] Diagram(s)
- [ ] Video(s)

### Audience

- [X] Developers
- [X] Designers and researchers
- [X] Product managers
- [X] Other

### Anything else?

The Content is currently drafted here: https://vfs.atlassian.net/wiki/spaces/~63618f93fc0cc7a600b041f2/pages/2482864365/Core+Service+Level+Indicators+and+Objectives+for+Vets+API+DRAFT

**Comment by vbellissimo** [comment]
@BillChapmanUSDS Hi Bill, Thank you for submitting this request. The Platform Content team will review for next steps. In the meantime, is there a place in the current IA of the [Platform website](https://depo-platform-documentation.scrollhelp.site/developer-docs/) where you think this new page should be tucked under? Thanks.

**Comment by vbellissimo** [comment]
Slack thread with Eric Boehs: https://dsva.slack.com/archives/C053SSSFHPY/p1683578311882329

**Comment by vbellissimo** [comment]
Hi @BillChapmanUSDS , this page has been published live on the Platform website: https://depo-platform-documentation.scrollhelp.site/developer-docs/core-service-level-indicators-and-objectives-for-v

We are closing this ticket now. Thanks.
