### ISSUE TITLE
[WIP] Set service connection for appointment

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#5682]
## Story
As a 50%+ service-disabled veteran, I want my service-connection to be reflected in my appointment so that I don't have to pay a copay when I visit a VA doctor.

## Context
Veterans with 50%+ disability ratings should always have appointments considered as service-connected. This is important because service-connected appointments don't require a copay, where as regular appointments do. Currently, all legacy and redesign VAOS appointments are set to `type:REGULAR`.

## AC
- [ ] Veterans who are 50%+ total disability rated have appointment type set to be service-connected (note: need to double check what the actual `type` value should be set to in order to correctly denote a service-connected appointment).

**Comment by laurenernest** [comment]
Closing ticket. Will reopen or create new ticket if a need comes up for this work.
