### ISSUE TITLE
AWS access for Robert Brown

### ISSUE THREAD

**Issue by rbrown-va** [department-of-veterans-affairs/va.gov-team#56836]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Robert Brown

### Your Email

brown_robert3@bah.com

### Team, Role, and Company of the target individual

Lighthouse - Leeroy Jenkles Team, DevOps Engineer, Booz Allen Hamilton

### Product Manager (PM) name and email

Nicholas Kruger <nicholas.kruger@adhocteam.us>

### Product Owner (PO) name and email

Andrew Fichter <andrew.fichter@va.gov>

### Desired AWS Access

Please grant me the same level of access as one my fellow team mates:
Edison Velez Martinez <VelezMartinez_Edison@bah.com>

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

From:	Johnson, Shannan P.
Sent:	Thursday, April 28, 2022 9:52 AM
To:	Cecilia; Lovejoy, Michael P. (Booz Allen Hamilton); VHA Liberty ITS Onboarding Team
Cc:	brown_robert3@bah.com
Subject:	Investigation Status--Brown, Robert (Booz Allen Hamilton)

Importance:	High

Subject of Investigation Request: Brown, Robert (Booz Allen Hamilton)

This is to advise you that Brown, Robert has a previous investigation that meets or exceeds the current 
request.

The investigation request has been assigned to an adjudicator to review for reciprocity. If approved, the 
Certificate of Reciprocity (COR) will be sent to the VA Contracting Officer/COR/HR representative listed 
on the Investigation Request.

IMPORTANT NOTICE: This e-mail is NOT an authorization to begin working for the VA or authorization to 
obtain VA network access (including remote access). If you have questions regarding the requirements 
to begin work or obtain VA network access, contact your COR or HR. The Personnel Security 
Adjudication Center does not grant VA network access or determine when you may begin work.

Respectfully,

Mr. Shannan Paul Johnson
Security Assistant - SA-17
PERSONNEL SECURITY ADJUDICATION CENTER (PSAC)
2200 Ft. Roots Dr., Bldg. 192
North Little Rock, AR 72114
PSAC HELP DESK: (501) 257-4469 or (501) 257-4490  (6:30a ñ 4:30p CST Mon. ñ Fri.)
PSAC HELP DESK EMAIL -   vhalitbackgroundinvestigations@va.gov
FAX # : 5012441318
NEW PSAC RESOURCE SITE  - 
https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdvagov.sharepoint.com%2Fsites
%2FLIT%2Fvasic%2Fdefault.aspx&amp;data=05%7C01%7C%7Cc495a6d73aab43d950a308da291e34cc%
7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637867506953033007%7CUnknown%7CTWFpb
GZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7
C%7C&amp;sdata=z52FV9tnts54gSuhJfv4aq63qR5nl2ZMd6jWj%2BpiVBQ%3D&amp;reserved=0
e-Qip Login Here: 
https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.dcsa.mil%2Fis%2Feqip%2F
&amp;data=05%7C01%7C%7Cc495a6d73aab43d950a308da291e34cc%7Ce95f1b23abaf45ee821db7ab2
51ab3bf%7C0%7C0%7C637867506953033007%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMD
AiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&amp;sdata=SANjBRx3c%2
FNn49at1zFHidOUMw%2Bv5xcuMyHy4MT21dw%3D&amp;reserved=0

NOTE : It is your responsibility to protect any documents containing your PII (Personal Identifiable 
Information), that you send through unencrypted email to the PSAC. To ensure your PII is properly 
protected, provide the required documents to your VA Contracting Officer Representative who will 
ensure the documents are sent to the PSAC through secure channels (i.e. PSAC Resource Site, PKI email, 
etc.).

The Personnel Security Adjudication Center is interested in your feedback.  
Please click here to access PSAC Customer Survey Link. (must be logged onto VA network).

Thank you and have a great day!

### Additional Notes

Ongoing access is necessary as maintaining the AWS infrastructure is one of my core job duties as a DevOps Engineer.

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by rbrown-va** [comment]
Platform Orientation scheduled for 5/9 @ 2PM Eastern time

**Comment by considerable** [comment]
@rbrown-va 
Thank you for specifying the level of access by the example of your teammates.

For the next steps of verification and approval, 
please remind your management to add your name into the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)

**Comment by BillChapmanUSDS** [comment]
Thank you for the examples.  I approve this access, Sorry for the delay.

**Comment by rbrown-va** [comment]
My name is on the VFS team roster

**Comment by considerable** [comment]
initial password provided via Slack DM.
