### ISSUE TITLE
Tier 3 Reporting Creation

### ISSUE THREAD

**Issue by Kimberley2019** [department-of-veterans-affairs/va.gov-team#56843]
**Create reporting for tier 3 items.**

- Status doesn't matter since all tiers are able to utilize all available statuses.
- Subject field will be the basis of the reporting.  Having 'T3' in the subject field will differentiate possible tier 3 cases.
- Once created please place in Public folder in Salesforce.

**Comment by edpearson20** [comment]
Hi, @Kimberley2019 !  Take a look at the report (Tier 3 Cases - Subject: T3 (KD)) created and let me know whether or not it fits your requirements please. 
https://va.lightning.force.com/lightning/r/sObject/00O3d000000ZWqbEAG/view?queryScope=userFolders

**Comment by Kimberley2019** [comment]
At first glace, it appears to be exactly what I need.  Thank you so much.  I'll let you know by stand up on Monday if I need any adjustments.

**Comment by Kimberley2019** [comment]
This report is complete.
