### ISSUE TITLE
RFC review

### ISSUE THREAD

**Issue by elizabethkochBT** [department-of-veterans-affairs/va.gov-team#56853]
### Tasks
 - [x] [Review RFC](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/RFC-DSL-grandfathering-1/teams/vsp/teams/Identity/RFC/DSL_Grandfathering.md)

### Acceptance Criteria
 - [x] [Comment on PR](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/918)

**Comment by porta-antiporta** [comment]
Draft comment doc:https://docs.google.com/document/d/14Y3XGbGymsNG3IAPYnsjlyn1lPDOrj69vHMPPnpqD70/edit#

**Comment by porta-antiporta** [comment]
Comments submitted to the RFC. I also proposed edits to the RFC via this PR: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/928

Propose to close this issue
