### ISSUE TITLE
[Design Discovery] Community Care Provider Selection

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#5686]
## Problem
As a veteran, I would like the VAOS app to automatically find Community Care providers closest to my residential address and auto populate the providers I've selected into the VAOS provider fields so I don't have to manually enter or copy-paste this information.

## Open questions/comments:
- Type of care and CCE API with drive time should factor into the location selection
- For each provider list the following -- First/Last Name, Practice Name, address, city, state, zip, distance (in miles) from veteran's residential address, service(s)
  - Is this part of the PPMS data?
- What will we do if we can't return any providers for the Veteran? _Consider moving them through flow with as if they selected 'no/I don't know' option_
- What about options outside of residential address? Can veteran enter alternate address because of travel/overseas?)
- What does PPMS data return? How is it formatted?
    - How to look up CC facilities with a given type of care in a given radius from existing residential address (which address is that specifically?) specifically for the purpose of requesting an appointment is documented in GH
    - What data is returned from this lookup, and what data is required / will be needed to support our mocks, documented in GH

## AC considerations for this feature:
- [ ] Community Care providers are searchable from within the form flow
- [ ] Can select up to three providers - minimum 1
- [ ] Can rank providers
- [ ] If multiple providers, sort the list ascending order, starting from the closest to the farthest
- [ ]  If the user attempts to select a 4th choice, display a message informing them that they can only choose up to three providers

Historical reference to CC Provider selection -- https://issues.mobilehealth.va.gov/browse/VAOSR-2?filter=-4&jql=text%20~%20%22community%20care%20provider%22%20order%20by%20created%20DESC

Research folder, with research plan, conversation guide and prototype (pw: adhoc-CC01) -- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/research/oct-2020-cc-provider-discovery/README.md

**Comment by lenaecb** [comment]
Current design ideation for this:
[Uploading... image (1).png ]

**Comment by lenaecb** [comment]
Current working draft of one approach:
![image (1).png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/fde7cf60-49a9-436f-8553-6e91a5f04a9e)

**Comment by lenaecb** [comment]
Supporting documentation for this discovery here -- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/product/product-projects/cc-provider-selection.md

We need to identify a technical solution/strategy for handling the identified hurdles.

**Comment by lenaecb** [comment]
@rtwell - feel free to drop the latest sketch prototype link with the small tweaks we talked about today in this ticket. Thank ya!

**Comment by rtwell** [comment]
https://www.sketch.com/s/11b8ffa9-8333-4fb4-9344-20d56d5a3bc2/a/JYzVL0/play

**Comment by lenaecb** [comment]
@outerpress yay! party!

**Comment by outerpress** [comment]
@peggygannon Here's the prototype for your review: https://adhoc.invisionapp.com/share/QWZ7WD9GTPJ#/435681239_VAOS-CC-Pick-1

All feedback is welcome, but here are a couple of areas to focus on:

**Choose where you would prefer to receive your care screens**
The goal is to help a veteran quickly choose between community care and a VA center

**Review your appointment request details** and **Your appointment request has been submitted**
Aiming to clarify that the veteran is requesting an appointment here, rather than scheduling one directly

**Comment by outerpress** [comment]
Research plan, conversation guide, and prototype are done. We'll track language tweaks and synthesis in other tickets.
