### ISSUE TITLE
Design Intent  - IA Feedback - [Benefits Disability Experience, Disability Comp Application (21-526 EZ), Add Self Assessment Part A form information to BDD workflow]

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#56869]
## VFS actions
- [x] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [x] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [x] Close the ticket when all feedback has been addressed.

## Thoughts/questions
* For design intent meetings, it is always helpful to see a high-level user flow diagram of your product as it stands, and what you are trying to change about it. I really think this would still be helpful to create and encourage you to draw that out. Think about: what is the total 526 form flow, where does BDD fit within that, and where does this other supplemental form fit within _that_? If the supplemental form isn't submitted with the BDD, what does that user flow look like?

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

#### Try to prevent task Interruption
Linking users to the separate PDF Self-Assessment document in the middle of the form flow is a task interruption. When you start coding these changes, make sure that link opens in a new window so that it doesn't divert the user from finishing this form.

#### Add additional context on entry page
On the entry page, please add additional context to your parenthetical (that tells users to fill out the PDF on a desktop computer). If this is a form that takes 15-20 minutes and needs to be downloaded, filled out, and re-uploaded, those are helpful things for users to know before beginning this process. Fill out [ticket to work with Sitewide CAIA](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Sitewide+Content%2C+RLHecht&labels=sitewide+content%2C+sitewide+content-product+support&template=sitewide-content-intake-form.md&title=%3CType+of+Request%3E+from+%3CTeam%3E) for help massaging language to get those directions just right. 

#### Resolve dead-ends

This is a big piece of feedback, and I know it's more complicated than you wanted for your MVP solution. This is a complicated user flow, so it's going to need some slightly more complicated solutions to meet VA.gov Experience Standards. I'm open to some dialogue and ongoing solutioning here, so please feel free to pop into [office hours](https://calendly.com/platform-office-hours) or DM me anytime to talk it out! Other ideas welcome.

* For users who opt **not** to add evidence now, the instructions you have mocked up on the submission page (directing users to the VA profile for submitting the Self-Assessment later) are helpful, but they will disappear when the user leaves the page. Since they can't navigate back to that highly contextual information, this is considered a dead-end for users, and it will be a launch-blocker at staging review. I can think of a couple of options, but I'm open to ideas if you think of other solutions!
  * **preferred** Require the Self-Assessment Part A document to be uploaded _before_ the BDD can be submitted. This will require your form to have logic. You'll need to understand if that specific form got uploaded on the back-end, which builds the case for what @allison0034 and I were suggesting during the meeting: adding a new drop-down option for this supplemental PDF form. 
   * **not preferred** Create help documentation (perhaps in the resource library?) so that if users search for "BDD" or "Separation Health Part A Self-Assessment" they can find instructions (and any other relevant information) to help troubleshoot what steps they need to take to upload this form after they've already submitted the BDD form. I think I'm open to this as an MVP workaround, depending on what Sitewide CAIA thinks (ask about this in your[ intake request ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Sitewide+Content%2C+RLHecht&labels=sitewide+content%2C+sitewide+content-product+support&template=sitewide-content-intake-form.md&title=%3CType+of+Request%3E+from+%3CTeam%3E) when you fill it out), as they'd have to build a static page like this for you. @bethpotts @DanielleThierryUSDSVA @jennymayoco

**Comment by lydiahooper** [comment]
Thanks for the feedback!
- I think I mentioned that the CAIA team is working on diagramming 526 flows right now, you can ask Mikki if you have questions about that
- We'll make sure the link to the form opens in a new window 
- Will also add content on intro page about time takes to complete Part A
- Re: the dead end, we asked our VBA stakeholders and found out we can add instructions to the actual PDF, though we are unsure of the timeline for that
