### ISSUE TITLE
Text Update on Terms and Conditions from VA Notify

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/va.gov-team#56877]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more unauthenticated pages, online forms, apps, or tools on VA.gov
- [x] Making revisions to one or more existing VA.gov pages
- [ ] Something else 
 
 *Give a brief description of what your team needs support with.*

We need a couple minor text adjustments/additions to https://www.va.gov/privacy-policy/digital-notifications-terms-and-conditions/

We were recently given additional requirements for SMS notifications from AWS Pinpoint (our provider) that require some minor text changes to the existing page. Without these changes we would be unable to send new SMS (text) use cases and it could impact existing ones should the carriers audit them.

1. Section header "Delivery and messaging rates" must be changed verbatim to "Message and data rates may apply". This is a carrier requirement for SMS notifications on the terms and conditions page.
2. We are required to provide at least one method of help/contact on the page. After talking to our SMS provider, they told us it would be ok to link to our current contact us page somewhere within terms and conditions. https://www.va.gov/contact-us/
3. Please add additional reference of “T-Mobile” in the list of participating service providers under the section, "Delivery and messaging rates". Please note, “Metro by T-Mobile” is already in the list and must remain as is.

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [ ] Yes
  - [x] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
## When do you expect to launch your product to 100% of users?
  
*Please provide an estimated date so our team can create other relevant tickets.*
 
As soon as the changes are complete.
 
## Supporting artifacts
*Please provide supporting artifacts as available.*

- Link to product outline:
- Link to or attach user flows:
- Link to prototype or mockups:
- Link to any epics/issues that may be helpful:

## Will this work be going through the Collaboration Cycle?
- [x] Yes 
- [ ] No

## When does this work need to be done?
- Estimated launch date:
- Estimated staging review date:
- Content, Accessibility, and IA work needed by: 

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [x] No, but I'd like to schedule time to talk about this request
- [ ] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: VA Notify
-	OCTO-DE product owner: Beverly Nelson, @bevnobev 
-	Product manager: Melanie Jones, @mjones-oddball 
-	Designer:
-	FE engineer: 
-	Product/team Slack channel: [#va-notify-public](https://dsva.slack.com/archives/C010R6AUPHT)

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).

- We will need this, but I am holding off until we sync with content to understand next steps.

  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by mjones-oddball** [comment]
CC @bevnobev @k-macmillan @hubgitian

**Comment by mjones-oddball** [comment]
@RLHecht FYI I'm OOO next week 4/17 - 4/21, but @bevnobev will be around to discuss and answer questions as needed during that time.

**Comment by katherine-fung** [comment]
Hi @mjones-oddball, I'm starting on these changes. 

I just want to clarify - for the text "Message and data rates may apply," can this be a sentence verbatim underneath the header "Delivery and messaging rates"? 

Or does the header have to say "Message and data rates may apply"? 

Thank you!

**Comment by mjones-oddball** [comment]
@katherine-fung If you all feel that won't be too repetitive that is fine! It didn't have to be the header, but those exact words must be used on the page. CC @bevnobev

**Comment by katherine-fung** [comment]
Thank you @mjones-oddball!! The changes are now with our copy editor for review. Does your team have any plans to show the changes to SMEs or partners? We just want to know if we should wait before we publish the changes. Thanks again.

**Comment by mjones-oddball** [comment]
@katherine-fung Sorry to throw a curve ball, but our notification provider, Amazon, just came back with another change request from T-Mobile. I'm trying to determine the exact wording needed but will let you know ASAP. It should be extremely minor. 

"Participating service providers may include but aren’t limited to AT&T Wireless, Google Voice, Sprint Corporation, **Metro by T-Mobile**, UScellular, Verizon Wireless, and Virgin Mobile. "

- Either we need to add another one to the list that just says "T-Mobile" or adjust the "Metro by T-Mobile" wording. I'm asking them which it is.

As for your question above `Does your team have any plans to show the changes to SMEs or partners? We just want to know if we should wait before we publish the changes.`  - I won't need to review with other partners. Just Bev and I.

**Comment by katherine-fung** [comment]
@mjones-oddball. Thanks! Once you know the change, we'll make it, show it to you, and then publish.

**Comment by mjones-oddball** [comment]
@katherine-fung I just heard back and updated the description.

> Please add additional reference of “T-Mobile” in the list of participating service providers under the section, "Delivery and messaging rates". Please note, “Metro by T-Mobile” is already in the list and must remain as is.

**Comment by mjones-oddball** [comment]
@katherine-fung The new contact us link at the bottom of the page "Find out how to contact us" didn't work for me, but I figured that might be because of the status of the draft page. Otherwise, changes looked good to me :). Beverly is out of office currently, but she will be fine with us moving forward to publish in her absence as they are straight forward changes.

**Comment by RLHecht** [comment]
@mjones-oddball Just letting you know these changes are now live on prod: https://www.va.gov/privacy-policy/digital-notifications-terms-and-conditions/

I think we can close this ticket out but let me know if there's anything else!

**Comment by RLHecht** [comment]
Work complete. Closing ticket.
