### ISSUE TITLE
Vets-api terminal access for Swapna Krishnankutty

### ISSUE THREAD

**Issue by swapna-tw** [department-of-veterans-affairs/va.gov-team#56886]
### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Swapna Krishnankutty

### Your GitHub handle (terminal access is managed through GitHub)

swapna-tw

### Team, Role, and Company of the target individual

Virtual Agent, Quality Analyst, Thoughtworks Inc.

### Product Manager (PM) name and email

Ian Santarinala, ian.santarinala@thoughtworks.com

### Product Owner (PO) name and email

Luciana Morais, Luciana.Morais@va.gov

### Your dsvagovcloud AWS user name (if applicable)

Swapna.Krishnankutty

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [ ] sandbox
- [ ] production (if requesting, justify prod access in 'Additional Notes' section)

### COR Name (leave "None" if you listed an AWS user name above)

Cecila Lee

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

Liberty IT -  Michael G. Lovejoy

### Access Expiration

07-07-23

### Additional Notes

I need this access to setup appeals test data in vets-api-mockdata repo by connecting to MPI's staging environment through rails console.

### User must exist in a roster before vets-api terminal access can be granted

- [ ] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added
- [ ] If they included an AWS user name, check to see if their user name is listed in [iam_users.tf](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf)
- [ ] Comment in this issue saying which roster the user is listed in and confirming their AWS user name (if applicable)

**Comment by swapna-tw** [comment]
My completed e-QIP questionnaire was released to DCSA on 24th Feb 2023.

**Comment by ryan-mcneil** [comment]
@swapna-tw  You’ve been granted access to the `dev` and `staging` environments.

Here's some additional documentation for the [Vets API on EKS](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-TerminalAccess)

**Comment by swapna-tw** [comment]
Thank you!

**Comment by rmtolmach** [comment]
@swapna-tw You access expiration date has arrived! :) Do you no longer need access to the vets-api terminal in ArgoCD for dev and staging? 

To be clear, we usually limit _prod_ access, but not dev and staging access, so if you want to keep your access, that's fine. Just let us know.

**Comment by rmtolmach** [comment]
I DM'd Swapna on Slack. Access is still needed. I'm changing the expiration to "ongoing".
