### ISSUE TITLE
Content Update Request from VBA-Education

### ISSUE THREAD

**Issue by AnneHurley** [department-of-veterans-affairs/va.gov-team#5689]
## Why you're here
- Content support for static public website pages

## Instructions
* Submit this request when VSA Public Website team intervention is required
* Information on Air Force Education benefits has changed. Request from Lucas and Tammy in VBA/Education:
****
Please see the request from our Air Force Education policy contact to update the following VA website information: https://www.va.gov/education/transfer-post-9-11-gi-bill-benefits/

Current:

**Can I transfer benefits?**
You can transfer education benefits if you’re on active duty or in the Selected Reserve and you meet the requirements listed below.
At least one of these must be true: 
	You have completed at least 6 years of service on the date your request is approved and you agree to add 4 more years of service, or
	You have completed at least 10 years of service on the date your request is approved, can’t commit to add 4 more years of service because of either a policy or statute, but agree to serve for the maximum amount of time allowed
And this must also be true: 
The person getting benefits has enrolled in the Defense Enrollment Eligibility Reporting System (DEERS).
Who’s covered?
Qualified dependents

Recommended revision:
**Can I transfer benefits?**
You may be able to transfer education benefits if you’re on active duty or in the Selected Reserve and you meet the requirements listed below.
•	You have completed at least 6 years of service on the date your request is approved and you agree to add 4 more years of service, and 
•	The person getting benefits has enrolled in the Defense Enrollment Eligibility Reporting System (DEERS).
Who’s covered?
Qualified dependents

NOTE: Effective 12 July 2019, all TEB applicants will incur a 4 year service commitment from the date of application.  Members who cannot meet the 4 year service commitment are ineligible for TEB.  (DoDI 1341.13, Change 1)  

Also noted on the page under ‘Get more information’ – the first link (DoD website for information on transferring benefits ) points to a page which is no longer being maintained.  However, it does provide a new location: visit the current version of the site. (https://www.defense.gov/), please consider updating this reference as well.

V/r

John Welstead
Education Service 
 

__When to submit a request__

Requests should be submitted at least **2 weeks** in advance of the targeted launch/completion.  Make your request as soon as you're aware you will need Public Website participation. Different types of requests may require more time in advance. For apps tool content support, try to engage a content person for your project kick-off.

---

### Request Type
*Select all applicable and provide details behind your request* 

   * Word document with draft if available, or link to the URL where the draft content appears:
      * < link > 
   * Provide design context: (Example: Is this content in a user flow, an in-line error message, tool tip, field label?)
      * < design context >
   * Scope: How many screens? (Or messages, etc.) 
      * < scope > 
      
      
- [ x] **Content support for a static public website page**
   * Is this to update existing static content? 
      * < Y >
   * Does this need a new static tool landing page? (The content team may propose a different approach in consultation with IA.)
      * < N>
   * Provide a list of URL/s that need to be reviewed or updated. 
      * See above, plus potential new link in one CTA
 

     

### Desired/target implementation date
Sprint 15

--- 

### Requestor info
Tammy Hurley and Lucas Tickner, VBA

- Team name: Public websites
- DEPO product owner: *enter name*
- Product manager: *enter name*
- Content writer: Anne Hurley: 
- FE engineer: *enter name*
- Product/team Slack channel: *enter*

**Comment by MickinSahni** [comment]
Associating it with Sprint 15 as Public Websites can manage the content creation + publishing.

**Comment by AnneHurley** [comment]
@RLHecht  I've made the updates above here: https://prod.cms.va.gov/node/952/edit

(Q - do you need the "'edit" - can that get you to the page any faster?)

Couple things:
1. SMEs added this NOTE to their request: "NOTE: Effective 12 July 2019, all TEB applicants will incur a 4 year service commitment from the date of application. Members who cannot meet the 4 year service commitment are ineligible for TEB. (DoDI 1341.13, Change 1)" --- but I believe our first bullet covers this ("and you agree to serve 4 more yeras..." I've left out the note but let me know if you disagree.
2. They seem to be using TEB as their shorthand for this program while we are using "TOE" - transfer of eligibility. I just wanted to call that out; I left TOE where we have acronyms
3. Lastly, SMEs asked that the first "More information" link be to the over Department of Defense website (www.defense.gov/) - so I've edited the link text and added that new link, but to be honest I spent 20 minutes looking on the DoD website and could not find anything about this. Should we still leave it in?

@jenniferlee-dsva  FYSA

**Comment by RLHecht** [comment]
@AnneHurley Your edits to the featured content look OK to me. A few questions: 

1. Removing the note--Is it OK that we don't explicitly say that you are ineligible if you don't meet the 4-year service commitment? I do think we are providing the same information in that first bullet point otherwise. 
2. Under "Get more information" we call it the TEB Portlet, which is the only time we say TEB on the page. Looking at this [legacy page](https://www.benefits.va.gov/gibill/post911_transfer.asp) it seems they use the Transfer of Education Benefits (TEB) website to handle the TOE requests. I spelled it out in that instance but agree we should call it TOE everywhere else.
3. We had a vanity number low down on the page so I fixed that too.

**Comment by AnneHurley** [comment]
@RLHecht  Thanks much. I think we don't need that note either, but I'll point it out to the SMEs just to check, and thx for the other edits as well. 
Sending preview link to SMEs 2/11.
@jenniferlee-dsva  FYSA

**Comment by AnneHurley** [comment]
https://prod.cms.va.gov/node/952/edit
Final edits approved by stakeholders, ready for @RLHecht  to review and push live.

**Comment by RLHecht** [comment]
@AnneHurley This page is now published. Moving to validate.

**Comment by MickinSahni** [comment]
Closing out and associating with Sprint 14

**Comment by RLHecht** [comment]
@MickinSahni we should keep open in validate until we see it live on the site tomorrow afternoon

**Comment by MickinSahni** [comment]
> @MickinSahni we should keep open in validate until we see it live on the site tomorrow afternoon

Oh, think I misunderstood. Thanks, Randi! Re-opening

**Comment by MickinSahni** [comment]
2020-02-12 PW Sprint Planning
- will validate after deploy today

**Comment by RLHecht** [comment]
This has been validated on live site. Closing issue. @MickinSahni
