### ISSUE TITLE
Analytics Implementation for Facility Locator

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#5690]
# Analytics Implementation 

## Description
- Request for Google Analytics implementation

- Who is this request for?
    - Facility Locator team, #vsa-facilities
    - Contact: Michelle Middaugh, Product Manager (Ad Hoc)
    - Project: Urgent Care MVP implementation
    
 - URL: https://www.va.gov/find-locations (_No PHI, Facility Locator is part of the unauthenticated experience_)
------------------------------------------
### Overview of Tracking Needs to Support MVP
1) Need to track the percentage of users who perform an urgent care search and ultimately click through to view the urgent care eligibility/instruction web page.  There will be a call to action that displays in the following scenarios: 
- When search parameters for Facility type = "Urgent care" and Service type drop down= "Community urgent care providers (in VA’s network)" 
- When search parameters for Facility type = "Community pharmacies (in VA’s network)", link to eligibility web page is displayed.
- Clicking through the call to action to the web page will be the desired behavior. (Screenshot below)
![image](https://user-images.githubusercontent.com/48527022/74683045-bcef5580-5195-11ea-9224-0240dabf0e59.png)
- Timing
The availability, url and content of this web page will be controlled by the Office of Community Care. It is expected that it will be available by 3/1 to support the rollout of a new community care provider. (It was originally planned for 2/1.)
```javascript
dataLayer.push{(
   'event: 'cta-primary-button-click' //push with every click on button
)};
```
2) Perform dataLayer push **once each time all new search results are returned**

```javascript
dataLayer.push{(
   'event': 'fl-search-results', //push once search results have been returned from API
)};
```
----------------------
### Resources
- **[URLs: [Staging - Facility Locator](https://staging.va.gov/find-locations/)]**

## Acceptance Criteria
- [ ] Verify dataLayer fires accurately according to description above
- [ ] Verify tag fires in accordance with when events are fired
- [ ] QA has been completed

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by joanneesteban** [comment]
Hi @mmiddaugh! Wanted to check how things are going on #4026 and #5936? Those are currently the two KPIs we're dependent on to round out the KPI tracking MVP.

**Comment by jonwehausen** [comment]
Hi @brangi ,

Thanks for your work in getting the dataLayer push in place! 

At first glance, we will need one piece of the dataLayer push corrected -- apologies for not being explicitly clear here. 

Whenever a search is performed, we want to do **one ```dataLayer.push{('event': 'fl-search-results')};``` , after ALL results have been returned**. In other words, we want to do **1 push each time** the loading indicator has disappeared and search results are returned. 

Apologies again if this wasn't initially clear above, I have modified to reflect this verbiage. 

Please let me know if you have any further questions.

**Comment by mmiddaugh** [comment]
Hi @jonwehausen I created [#6443] for this adjustment

**Comment by jonwehausen** [comment]
Thanks @mmiddaugh and @brangi for your help here -- I just finished validating and everything looks good following the adjustment.
