### ISSUE TITLE
VAOS Contact Center Review

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#5691]
**Overview:** VAOS stands for ‘VA Online Scheduling.’ It is a veteran-facing online frontend for the VA healthcare appointment scheduling experience. The legacy VAOS tool with which many
veterans are familiar has been available at https://veteran.mobile.va.gov/var/v4/ and also
through the ‘Appointments’ dashboard in MyHealtheVet for the last several years. This tool will
be phased out in favor of the new VAOS tool that’s been built on top of the VA.gov platform.
This guide is only meant to cover the experience of the new tool.

**Launch Date and Details**

**Testing URL:** staging.va.gov/health-care/schedule-view-va-appointments/appointments

**Production URL:** https://www.va.gov/health-care/schedule-view-va-appointments/appointments

**Product Guide:** https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/product/vaos-product-guide.pdf

**Product Video** -- Completed 3/09/2020 - https://drive.google.com/open?id=1LucLBX2AApkvPTK7nyo72SrFa7QZqmQQ

**Product Video Transcript** -- -- coming soon once HRC demo is scheduled

## Remaining To-Dos:
- [ ] Schedule HRC demo through VAOS Mobile Team
- [ ] Create 'cheat sheet' for HRC (per suggestion of Judy)

**Comment by clantosswett** [comment]
@markgreenburg if you could provide some more details on the launch dates and/or timeline, that will help us to ensure we are communicating correctly to the call centers.

**Comment by markgreenburg** [comment]
@clantosswett thanks! Current plan is to roll out to VA.gov in late feb or march, pending everything continuing to go well. MHV will need to transition to pointing veterans to va.gov instead of the legacy version of the tool, and while that should also technically be possible around March the timing is still not completely clear because of SSOe needing to be implemented on VA.gov. Point being, both the legacy application that's available on MHV as well as the new application may be available concurrently for a bit. Happy to set up some time to chat in person if that'd be helpful.

**Comment by lenaecb** [comment]
I've updated the product guide link in the actual ticket. Sorry that was broke. 

Also for your awareness, we're tracking towards a go/no-go date by Thursday (3/5) for initial phased rollout start. Our target date for actual phased rollout start is 3/9 with a low percentage of users - about 5%. 

Here's the latest MVP rollout plan: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/product/VAOS%20MVP%20Launch%20Strategy/phased-rollout-plan.md

cc: @clantosswett

**Comment by lenaecb** [comment]
@clantosswett - Just for your awareness. We are going to add the following information to the new VAOS tool. This is straight out of the current tool and points to their corresponding HRC contact info. 

![IMG_3717.PNG](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/4fe72e89-d044-44d6-a5c2-cf8886387b75)

The one thing that I want to do, however, for this ticket is make sure we're capturing how we plan to work together now that we are proposing the support workflow stays with HRC & MDS prior to coming to us VAOS/VA.gov.

**Comment by clantosswett** [comment]
Sounds good. I think this is a fair and right assumption to make. I'll still try to clarify with HRC folks so we can be double sure.  

And just for the sake of clarity, we are good with the product guide. I passed it along to HRC but I REALLY want the VAOS team to be the one to schedule the demo with them. When I spoke to Sylvia at HRC she said she regularly communicates with the VAOS team but she didn't have specific names.  She said gets emails from these groups (vaosproductionsupportteam@va.gov; Var_release_team@va.gov; Var_release_team@va.gov; vaosleadership@va.gov. @lenaecb do you have a sense of who on the VAOS team would be the right person to work with to set up the demo call? I'd like to work with them to make sure they are working with HRC ahead of this launch.

Thanks!

**Comment by lenaecb** [comment]
@clantosswett - Just sent a follow up email to the VAOS team asking for that point of contact. Hopefully it will be a simple answer and we can move to scheduling from there. 

I'll setup a different ticket for the two VAOS teams to chat regarding process for ticket exchange on issues. Do you want to be a part of that? I assume yes, but maybe that should also include someone from the VA.gov infrastructure/monitoring side as well? Although, Kam should be able to speak on behalf of those practices as well.

**Comment by lenaecb** [comment]
@clantosswett - are we good to close out this ticket?

**Comment by clantosswett** [comment]
Good to close. Thank you!
