### ISSUE TITLE
Phone number display on CC cards

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#5692]
## What happened?
Awkward display of community care phone number and referral message: 
![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/7887a236-57b9-4bba-9d46-447575f47592)

## Specs:
- Browser: Chrome

## Steps to Reproduce
- URL: https://staging.va.gov/
- Location= Spokane, Washington, Facility type = Community providers (in VA's network), Service type = Podiatry
- Scroll to Butler, Christopher

## Desired behavior
**If you have a referral,** call this facility at: [phone number]
**If you don’t have a referral,** contact your local VA medical center.

## Acceptance Criteria
When Facility type = Community providers (in VA's network) + Service type = any (Podiatry is an example), cards displayed in results will have phone numbers if included in the data. 

[ ] If phone numbers are present, cards should display: 
**If you have a referral,** call this facility at: [phone number]
**If you don’t have a referral,** contact your local VA medical center.

[ ] If phone numbers are not present, cards should display
**If you don’t have a referral,** contact your local VA medical center.

**Comment by mmiddaugh** [comment]
@davidconlon @arickalewis1 please confirm my acceptance criteria above is correct for the instance in which a phone number may not be present in the data.

**Comment by arickalewis1** [comment]
@mmiddaugh looks right to me!
