### ISSUE TITLE
[DD][EKS] Db-migrate job not working as intended

### ISSUE THREAD

**Issue by oseasmoran73** [department-of-veterans-affairs/va.gov-team#56948]
## Description

DB-migrate was suppose to set off for one instance, but it seems it did not trigger alert as intended. Review and modify to alert accordingly

## Acceptance Criteria
- [ ] Alerts are properly being triggered to #oncall channel

**Comment by RachalCassity** [comment]
@oseasmoran73 Since we are still deploying in BRD, db-migrate job is not enabled for prod. Not sure if this is the reason

**Comment by oseasmoran73** [comment]
@RachalCassity This was for a `dev` instance when debugging occurred for openmetrics. I will let y'all validate if this is needed or not

**Comment by laineymajor** [comment]
Done
