### ISSUE TITLE
Lighthouse increase in 502s and 504s

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#56968]
Lighthouse is reporting 504 errors at the Kong layer after the Vets API migration to EKS. This mainly impacts the `/internal/auth/v2/validation` endpoint which is hosted in Vets API. The onset of these reported errors coincides with the timeline of the EKS migration that took place on April 9th.

## What is a 504 Error?
A 504 error is a Gateway Timeout error. This typically indicates that a server acting as a gateway or proxy did not receive a timely response from an upstream server it needed to access in order to complete the request.

In our context, the "proxy" latency reported by Kong refers to the time it took for the final service (which could be the Load balancer, traefik, or the pods based on our request chain) to process the request.

## The Request Chain
Our request chain for `/internal/auth/v2/validation` is as follows. `/internal/auth/v2/validation` is a Lighthouse endpoint, but resides in Vets API.

https://api.va.gov -> revproxy -> kong -> [load balancer](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/applications/platform-eks-clusters/alb.tf) -> api.va.gov:8000 (kong, again) -> traefik -> pod`

### Discovery
Upon investigation, we have discovered 504 logs [from ECS ](https://console.amazonaws-us-gov.com/ecs/v2/clusters/dvp-prod-ecs-api-gateway-cluster/services/dvp-prod-ecs-api-gateway-service/logs?region=us-gov-west-1)for the API gateway. Interestingly, the volume of 504s logs reported by Lighthouse are **not** apparent at either the pod or the Traefik layer. This implies that latency issues or errors might be occurring **prior** to the requests reaching the Traefik layer, thereby indicating that the issue likely originates from the Load Balancer.

We did update the AWS node termination handler, which was causing 504s at the traefik layer during node scaling events, but 504s are still persisting via Kong. Additionally, we adjusted the preStop command, startup and readiness probes (many iterations and different combinations).

## Impact
While there are some 504s at the traefik layer, they only amount to ~200 in a 1-day window. This doesn’t align with the thousands that Lighthouse is reporting.

### Example
From 2:11-3:11pm ET on Friday 6/16. Only 1525/307k total requests to `internal/auth/v2/validation` resulted in a 504. .5% amounts to than 1% of requests. If we were to take OVERALL requests into consideration, the percentage of 504 errors would be significantly less.

## ECS Logs
You can find relevant logs in ECS by using `"http://api.va.gov:8000/internal/auth/v2/validation" "\"status\":504"` as a filter. Access API Gateway (Kong) ECS [logs here](https://console.amazonaws-us-gov.com/ecs/v2/clusters/dvp-prod-ecs-api-gateway-cluster/services/dvp-prod-ecs-api-gateway-service/logs?region=us-gov-west-1).

## Datadog 

The [Datadog Dashboard for monitoring 502s and 504s ](https://vagov.ddog-gov.com/dashboard/pcv-wee-xf3/lighthouse-502--504-errors?from_ts=1687283080088&to_ts=1687455880088&live=true) was created to gain visibility into issues at the traefik and pod layers. Data surrounding scaling events, HPA metrics, memory and CPU can be found on the board as well.

## Possible next steps

1. Look at metrics like request count, active connections, latency, and error rates at the load balancer level. If the Load Balancer is overloaded or experiencing other performance issues, it might be reflected in these metrics.
2. Check load balancer, traefik and pod scaling events. Do the 504s align with a scalin event?
4. Check the Load Balancer's timeout settings?
6. Ensure the health checks are correctly configured on the Load Balancer
7. **Scaling the Load Balancer:** If your Load Balancer is under heavy load, you may need to scale it up or out to handle more traffic.

Note: Something happened when we shifted to EKS. We seem to have ruled out traefik and the pods, which is why we've landed on the Load Balancer.

## Additional Links
- [Thread with Derek Brown and team from Lighthouse](https://dsva.slack.com/archives/C04M7T1CZAS/p1685970319728599)
- [Datadog Dashboard for monitoring 502s and 504s ](https://vagov.ddog-gov.com/dashboard/pcv-wee-xf3/lighthouse-502--504-errors?from_ts=1687283080088&to_ts=1687455880088&live=true)

**Comment by laineymajor** [comment]
Added this to current sprint. It's taken a significant amount of time to solutiuon.

**Comment by laineymajor** [comment]
We will leave this open for monitoring purposes. Errors still persist, but have gone down significantly.
@LindseySaari if additional updates are needed.

**Comment by RachalCassity** [comment]
502 errors have not been seen since we separated routes to independent bulk head deployments. Still monitoring logs next week.

**Comment by RachalCassity** [comment]
502 errors have not been seen since we separated routes to independent bulk head deployments. Still monitoring logs next week.

**Comment by laineymajor** [comment]
additional info in duplicate ticket https://app.zenhub.com/workspaces/platform-tech-team-1-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/57008

**Comment by LindseySaari** [comment]
We met with Lighthouse to talk through the errors that we're seeing. [Notes can be found here](https://vfs.atlassian.net/wiki/spaces/TT1/pages/2658042130/Sync+with+Lighthouse+on+6+6+2023)

**Comment by LindseySaari** [comment]
## 504s

It appears that at times, the pod count for the `vets-api-auth-internal pods` dips below the 10 min replicas. [See this example](https://vagov.ddog-gov.com/dashboard/pcv-wee-xf3/lighthouse-504-errors?from_ts=1686074700000&to_ts=1686075420000&live=false). Notice in the dashboard when the Available replicas drops below 10, the spike in 504 errors at the traefik layer.

I see [logs for pods starting up during that time](https://vagov.ddog-gov.com/logs?query=env%3Aeks-prod%20service%3Avets-api%20pod_name%3Avets-api-auth-internal%2A%20%22Puma%20starting%20in%20cluster%20mode...%22%20&agg_q=host&cols=host%2Cservice&index=%2A&messageDisplay=inline&sort_m=&sort_t=&stream_sort=time%2Casc&top_n=10&top_o=top&viz=stream&x_missing=true&from_ts=1686074700000&to_ts=1686075420000&live=false).. but nothing for "Exiting". Could the liveness probe be restarting the container?

**Comment by LindseySaari** [comment]
## 504 errors continued

[In this example](https://vagov.ddog-gov.com/dashboard/pcv-wee-xf3/lighthouse-504-errors?from_ts=1686220620000&to_ts=1686221220000&live=false), I [pulled up this event](https://vagov.ddog-gov.com/event/explorer?query=source%3Akubernetes%20env%3Aeks-prod&cols=&event=AgAAAYiamkrY8IcEhQAAAAAAAAAYAAAAAEFZaWFta3JZQUFBeExwWlVfdTBMUlZwQQAAACQAAAAAMDE4ODlhY2ItOTQwOC00NGQxLTgyMzktZGNkZTRiODg5MzZh&messageDisplay=expanded-lg&options=&sort=DESC&from_ts=1686220620000&to_ts=1686221220000&live=false) and it looks to be the culprit `1 NodeNotReady: Node is not ready.` Looks like a host related error to me? If you look at the other events, it appears that there are a BUNCH of "Node is not ready" issues for that exact same host. Seems like it may be a connectivity issue where the kubelet can't report the status to the control plane or something?

![Screenshot 2023-06-08 at 9.30.57 AM.png](https://images.zenhubusercontent.com/5d4836dda95c51615db9bdc9/19006339-43c2-4364-9838-a561abbf0cfa)

**Comment by LindseySaari** [comment]
Kyle observed a kubelet crash, so that may contribute to the fact that nodes are getting oversaturated.

**Comment by LindseySaari** [comment]
Latest on 502s and 504s

1. This tends to happen during a node scaling event. May happen on scale up also.
2. We see the nodes readiness probe fail
3. Endpoint slice errors occur - Error updating Endpoint Slices for Service vets-api/vets-api-auth-internal during s scale down
4. This may happen during a scaling event when calico has not finished deploying to the new node
5. Idea: can we increase the time in which a node is declared ready? Maybe allow time for Calico to setup?

**Comment by LindseySaari** [comment]
[Monitoring 504s](https://vagov.ddog-gov.com/dashboard/pcv-wee-xf3/lighthouse-502--504-errors?from_ts=1686665190816&to_ts=1686679590816&live=true) in conjunction with unavailable nodes. The AWS node termination handler has been updated as of today, so continuing to monitor.

502's - searching and traversing the stack to see if anything sticks out. It's also possible that the AWS node term handler may help to reduce the 502s as well

**Comment by laineymajor** [comment]
Let's determine an acceptable range of errors... once we get to that range, likely move the ticket to the CoP as we are getting into load balancer and Kong work (both of those things are more DevOps related)

**Comment by LindseySaari** [comment]
To put things into perspective for the 504's, From 11am-12noon on 6/16, There were `564` 504's at the Kong layer. During this time, there were a total of 332,000 requests to the `internal/auth/v2/validation` endpoint. With this being said, only .16% of requests see a 504.

**Comment by LindseySaari** [comment]
From 2:11-3:11pm ET on Friday 6/16. Only 1525/307k total requests resulted in a 504. .5% which is still less than 1% of requests

**Comment by LindseySaari** [comment]
I've updated the ticket with the findings and (possible?) next steps. I think the ticket is now in a good place to be passed onto the Devops CoP

**Comment by LindseySaari** [comment]
This has been passed onto the DevOps CoP. The description has been updated

**Comment by LindseySaari** [comment]
[A new ticket](https://app.zenhub.com/workspaces/platform-cop-backlog-6359535e384ff5a473132130/issues/gh/department-of-veterans-affairs/va.gov-team/60934) has been created for the DevOps CoP with a reference back to this ticket (the original)
