### ISSUE TITLE
Sidekiq Admin UI Access Request

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#56972]
#### Access to the Sidekiq Admin UI is managed through a GitHub Teams per environment via the following teams: 
- [Dev](https://github.com/orgs/department-of-veterans-affairs/teams/va-gov-sidekiq-dev)
- [Staging](https://github.com/orgs/department-of-veterans-affairs/teams/va-gov-sidekiq-staging)
- [Sandbox](https://github.com/orgs/department-of-veterans-affairs/teams/va-gov-sidekiq-sandbox)
- [Prod](https://github.com/orgs/department-of-veterans-affairs/teams/va-gov-sidekiq-prod)

_Please provide your GitHub username to be added to that team, along with a reason access is required and which environments you're requesting access to._

- GitHub username: randomsync
- Reason access is required: As part of check-in process, we're adding sidekiq jobs for the travel claims to be processed in the background.
- Environments requesting access to: dev, staging, sandbox, prod

**Comment by ryan-mcneil** [comment]
@randomsync Apologies for how long this has taken. We're trying to put new processes in place for this, as OCTODE does not have a preference. Can I assume you have an E-QIP transmittal? Do you have it handy? I don't see you in some of the other lists that I'm referencing that would confirm you have it. Once you get us that, I'll approve you. Thank you!

**Comment by ryan-mcneil** [comment]
Slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1683569110584779)

**Comment by bdech** [comment]
@randomsync Your Sidekiq Production access has expired. Would you like to request an extension?

**Comment by randomsync** [comment]
Yes please. What do I need to do to request extension?

**Comment by bdech** [comment]
Sorry for the delay @randomsync. I just need your confirmation that you would like to request an extension. With that in mind, your Production access has been extended, limited to 6 months, expiring 05/15/24. Please set a reminder for yourself to return to this ticket a week prior to the next expiration.

**Comment by bdech** [comment]
slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1700060483835479)

**Comment by bdech** [comment]
@randomsync Your Sidekiq UI Production access has expired.

Would you like to request an extension? You have 72 hours to respond, or your 
access will be revoked and you will need to fill out a new request.

**Comment by bdech** [comment]
@randomsync Your Sidekiq UI Production access has expired.

Would you like to request an extension? If we don't receive a response by 05/21 your
access will be revoked and you will need to fill out a new request.

**Comment by bdech** [comment]
Production access removed.
