### ISSUE TITLE
S3 r+w AWS access for vfs-virtual-agent-team

### ISSUE THREAD

**Issue by eubiera** [department-of-veterans-affairs/va.gov-team#56980]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Evan Ubiera

### Your Email

evan.ubiera@thoughtworks.com

### Team, Role, and Company of the target individual

Developer

### Product Manager (PM) name and email

Alina Murphy, alina.murphy@va.gov

### Product Owner (PO) name and email

Luciana Morais, luciana.morais@va.gov

### Desired AWS Access

I need access to the buckets listed below for uploading images used in review instances that we spin up for demoing purposes. 

I need read/write access for the following buckets for user of email evan.ubiera@va.gov (I already have access to the _dev-va-gov-assets_ and _staging-va-gov-assets_ buckets )

_content.dev.va.gov
content.staging.va.gov_

I also need read-write access for the following four buckets for ALL of the emails listed below, as they are part of my team:

_content.dev.va.gov
content.staging.va.gov
dev-va-gov-assets
staging-va-gov-assets_

Team name -  **vfs-virtual-agent-team** 

Raina Huerta - raina.huerta@va.gov
Helene S. McCaron - helene.mccarron@va.gov
Joseph Hall - joseph.hall4@va.gov.
Maurice Okumu - maurice.okumu@va.gov
Kha Huynh - kha.huynh@va.gov
Karan Krishnani - karan.krishnani@va.gov
Anita DeWitt - anita.dewitt@va.gov
Aaron Young - aaron.young2@va.gov

### Access Expiration

04-16-25

### E-QIP Transmittal Confirmation

<img width="701" alt="EQIP-confirmation" src="https://user-images.githubusercontent.com/117054459/232588606-a6c38d27-55e6-417b-90bf-dfa349db674b.png">

### Additional Notes

I need access to the buckets listed below for uploading images used in review instances that we spin up for demoing purposes.

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by considerable** [comment]
collectively, `vfs-virtual-agent-team`
the access to these two buckets:

- dev-va-gov-assets
- staging-va-gov-assets

is already in the work by issue 56757:
- department-of-veterans-affairs/va.gov-team/issues/56757

The access to two additional buckets and organizing the policy under 
the team `vfs-virtual-agent-team`, rather than individual AWS id, is a matter to approve for @BillChapmanUSDS 

Bill, please approve access to these additional two buckets 
and moving the policy for all four buckets from Evan.Ubiera to  vfs-virtual-agent-team:
- content.dev.va.gov
- content.staging.va.gov

**Comment by considerable** [comment]
VFS team

**Comment by BillChapmanUSDS** [comment]
I approve this access.

**Comment by considerable** [comment]
Slack: https://dsva.slack.com/archives/D0524K7RWUF/p1682957341863189
