### ISSUE TITLE
Display C&P Appointments on the Appointments List (Upcoming and Past) 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#56997]
## Description
We will display the C&P appointments in the VAOS application. The C&P appointment could have a different type of care associated to the exam appointment. We will need to use the `serviceCategory` field for C&P type of care. 

In our current appointment list page, the FE code uses `serviceType` to display the type of care. In the case where serviceCategory equals COMPENSATION & PENSION then the code will be modified to display `Compensation and pension exam` instead of `serviceType`.

**Note:** 
1. There are no C&P appointment requests. 

---

## Acceptance Criteria

- [ ] Given the user has a booked C&P appointment
        When the user logins to VAOS
        Then the user will see the C&P appointment on the Upcoming Appointment List 
        And page design matches the [design spec](https://www.figma.com/file/BK1nkXoXfSmrfRHOk4BEOR/Compensation-and-Pension?node-id=13%3A33&t=X5u6JZWhgvkD41OQ-1)

- [ ] Given the user has a past booked C&P appointment
        When the user is on the Past status page
        Then the user will see the C&P appointment on the Past Appointment List 
        And page design matches the [design spec](https://www.figma.com/file/BK1nkXoXfSmrfRHOk4BEOR/Compensation-and-Pension?node-id=13%3A33&t=X5u6JZWhgvkD41OQ-1)

### Design Assets
[Design Specs](https://www.figma.com/file/BK1nkXoXfSmrfRHOk4BEOR/Compensation-and-Pension?node-id=13%3A33&t=X5u6JZWhgvkD41OQ-1)

### Technical Specs
Acceptance Criteria
- [ ] Write new unit tests to ensure we're displaying C&P appointments correctly.

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by simiadebowale** [comment]
@ldelacosta - This is ready for validation

**Comment by ldelacosta** [comment]
Validated the Past appointment list for claudia.c.lapomarda@id.me![Screenshot 2023-04-26 at 6.16.11 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/2324f010-9b5f-4b39-a9ad-0739063ac8aa)

Will validate Upcoming list after we get some future appts booked in staging

**Comment by ldelacosta** [comment]
Validated the Upcoming list for future booked and future canceled appointments in staging. No issues to report. Closing out the ticket. 
![Screenshot 2023-05-02 at 11.36.01 AM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/965a4e1f-cd44-4348-a363-52b0cead45ad)
