### ISSUE TITLE
[Terraform] AWS provider 3.76.1 update

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#56991]
# Description
Currently, it seems as though we are unable to configure changes to S3 buckets through Terraform. In particular, we are unable to configure a CORS policy change to an S3 bucket because the change is not detected in a the Terraform plan. Instead, a change related to S3 encryption scheme changes is displayed in the Terraform plan.

This issue may be resolved by upgrading the AWS provider from 3.74 to 3.76.1. However, 3.76.1 brings codebuild issues with it.

# Acceptance Criteria
- [ ] Engineers are able to integrate changes to S3 bucket configurations

**Comment by pjhill** [comment]
Probably not very urgent at the moment

**Comment by JoeTice** [comment]
Task no longer relevant
