### ISSUE TITLE
Display C&P Appointments on the Appointment Details page (Upcoming, Past and Canceled View) 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#56998]
## Description
We will display the C&P appointments in the VAOS application. The C&P appointment could have a different type of care associated to the exam appointment. We will need to use the `serviceCategory` field for C&P type of care. 

In our current appointment details page, the FE code uses `serviceType` to display the type of care.  In the case where `serviceCategory` equals COMPENSATION & PENSION then the code will be modified to display `Compensation and pension exam` instead of `serviceType`.

**Note:** 
1. There are no C&P appointment requests. 
2. The C&P appointments cannot be booked through VAOS. 
3. The C&P appointments cannot be canceled through VAOS. 

---

## Acceptance Criteria

- [ ] Given the user has an upcoming C&P appointment 
        When the user logins to VAOS and clicks on the Details link
        Then the user will see the C&P appointment details
        And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/c%26p-appointment-details.md#compensation--pension-booked-future) 
        And page design matches the [design spec](https://www.figma.com/file/BK1nkXoXfSmrfRHOk4BEOR/Compensation-and-Pension?node-id=13%3A33&t=X5u6JZWhgvkD41OQ-1)

- [ ] Given the user has a past booked C&P appointment
        When the user is on the Past status page and clicks on the Details link
        Then the user will see the past C&P appointment details 
        And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/c%26p-appointment-details.md#compensation-and-pension-booked-past) 
        And page design matches the [design spec](https://www.figma.com/file/BK1nkXoXfSmrfRHOk4BEOR/Compensation-and-Pension?node-id=13%3A33&t=X5u6JZWhgvkD41OQ-1)

- [ ] Given the user has a future canceled C&P appointment
        When the user is on the Upcoming status page and clicks on the Details link
        Then the user will see the canceled C&P appointment details 
        And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/c%26p-appointment-details.md#compensation-and-pension-booked-canceled) 
        And page design matches the [design spec](https://www.figma.com/file/BK1nkXoXfSmrfRHOk4BEOR/Compensation-and-Pension?node-id=13%3A33&t=X5u6JZWhgvkD41OQ-1)

- [ ] Given the user has an upcoming C&P appointment
        When the user is on the appointment details page
        Then the user will not see a `Cancel` link 
        And page design matches the [design spec](https://www.figma.com/file/BK1nkXoXfSmrfRHOk4BEOR/Compensation-and-Pension?node-id=13%3A33&t=X5u6JZWhgvkD41OQ-1)

### Design Assets
[Design Spec](https://www.figma.com/file/BK1nkXoXfSmrfRHOk4BEOR/Compensation-and-Pension?node-id=13%3A33&t=X5u6JZWhgvkD41OQ-1)

### Technical Specs
Acceptance Criteria
- [ ] Write new unit tests to ensure we're displaying C&P appointments correctly.

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by simiadebowale** [comment]
@ldelacosta - This is ready for validation.

**Comment by ldelacosta** [comment]
Validated past appointment details page. Still need to validate upcoming and canceled appointment details. 
![Screenshot 2023-04-28 at 11.02.08 AM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/6335b4d2-8ca4-4553-8811-85bcf0b6a2f0)

**Comment by simiadebowale** [comment]
@ldelacosta - this is ready for validation.

**Comment by ldelacosta** [comment]
@simiadebowale - We have some minor updates. 

1. We'll need to remove the text VA appointment from the details page (Upcoming, Past and Pending). 
2. Remove the spacing between the title Compensation and exam appointment and the description text on the Upcoming appointment details page![Screenshot 2023-05-04 at 11.18.49 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/f53ed937-915b-4545-9c0c-29a143a5f5cd) 
3. Remove the spacing between Compensation and pension exam and the facility name/address on the Past and Canceled details page
![Screenshot 2023-05-04 at 11.20.09 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/926b4d18-254d-4fbe-832c-6f66b9004bf5)![Screenshot 2023-05-04 at 11.23.25 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/0b894ba5-c651-4098-bc87-9aab4f62fb66)

**Comment by simiadebowale** [comment]
@ldelacosta - this is ready for validation

**Comment by ldelacosta** [comment]
Validated the Upcoming, Canceled and Past appointment and no issues to report. Will do a final check with the design team before closing out the ticket. 

Upcoming:![Screenshot 2023-05-12 at 1.32.23 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/256c0c48-0ff7-4cc7-b00e-4231492dd56b)

Canceled: ![Screenshot 2023-05-12 at 1.24.57 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/c119e964-34da-412a-b1f4-2bfd800110ef)

Past: ![Screenshot 2023-05-12 at 1.17.07 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/44605b06-0604-458c-94c9-0daa22a8f5fd)

**Comment by ldelacosta** [comment]
Ticket has been signed off. Closing it out.
