### ISSUE TITLE
Adding Oseas Moran to DSVA Slack

### ISSUE THREAD

**Issue by kacibowen** [department-of-veterans-affairs/va.gov-team#56994]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

- Please add Oseas Moran (oseas.moran@adhocteam.us) as a full member. He is a DevOps developer on the Ad Hoc TIS Event Bus team and will need access to this space.

**Comment by kacibowen** [comment]
cc @oseasmoran73

**Comment by oseasmoran73** [comment]
Hi @LEHigley ! 👋 

Any update on this ticket? Should anything be needed on my behalf, please let me know!

**Comment by ewilson-adhoc** [comment]
@LEHigley 
Oseas's va email is oseas.moran@va.gov.

**Comment by LEHigley** [comment]
reactivated account for oseas.moran@adhocteam.us
