### ISSUE TITLE
Midpoint Review - IA Feedback - VA Forms Team, Form 21-10210 Lay/Witness Statement

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#57005]
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

### Must
* **Fix inconsistencies** 
   * Story 3's review page is missing Step 2 & 3.
   * Requirements listed on intro page do not match requirements in the form itself (form isn't requiring DOB or VA file number; there is also a VA insurance number requested that is not referenced on intro page)

### Should
* **Improve scannability & content placement**
   * **How To / Intro Page**: text directly beneath the H1 is duplicative of content in the lower section of the blue back-ground box. A suggestion would be to eliminate that from the sub-header and add something about the purpose of the form instead (image below). Consider swapping the order of those two text sections within the blue area so that users can first see if they're eligible to submit before telling them the requirements.

<img width="235" alt="Screenshot 2023-04-17 at 9 53 00 AM" src="https://user-images.githubusercontent.com/115033532/232656495-0cbff93f-0493-4c59-9073-2c8a4567e2e7.png">

* **Story 1 User path**: This is minor since most users will not track this changing from page to page, but consider a consistent content placement for Chapter-specific note information. Does that need to go above or below the user's information? 

<img width="561" alt="Screenshot 2023-04-17 at 9 53 38 PM" src="https://user-images.githubusercontent.com/115033532/232658996-e0819a67-59c0-48ee-afa1-194719e93470.png">

**Comment by AndrewCoforma** [comment]
Thanks for your feedback @sterkenburgsara !   
  
I have completed the updates from both the "must" and "should" sections.  
  
Here is a summary of the updates:  
  
**Must**  
\- Story 3's review page is missing Step 2 & 3.  
\-- Fixed  
  
\- Requirements listed on intro page do not match requirements in the form itself…  
\-- We (forms team) concluded that this section should only list: Name, SSN and DOB.  We determined that these were the only required fields based on the [existing form](https://www.vba.va.gov/pubs/forms/VBA-21-10210-ARE.pdf).   
  
**Should**  
**\- Improve scannability & content placement…**  
**\--** Thank you for this great suggestion - we decided to use content from the [IA question list](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/21-10210/ia-sitewide.md) - it now reads: "A Lay/Witness statement provides an opportunity to submit a statement providing additional information in support of any disability compensation or pension claim that is on file."  
  
\-- Additionally, we swapped the order of "How do I…" and "What should I know…" - I also replaced "What should I know…" to "Who is eligible…" (which you suggested during the midpoint review).  Thanks for this!  
  
  
\- **Story 1 User path**: ... Note placement  
\-- Thanks for pointing this out.   I had accidentally used an outdated/unsupported pattern for this - I've updated the files in Story 1 to reflect our existing patterns.  
  
  
Please let me know how everything looks.
