### ISSUE TITLE
Increase in 502s for /mobile

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#57009]
### PROBLEM
It’s been rough trying to filter these logs. I’m noticing Mobile::V0::Locations  has a stack level too deep. This is getting about 2.5k errors every so often.
Here’s is a snippet of the error code because the error is over thousands of lines

[slack thread
](https://adhoc.slack.com/archives/C045LCF8WU8/p1681761491108679)

### RESOLUTION

**Comment by laineymajor** [comment]
duplicate

**Comment by laineymajor** [comment]
@RachalCassity please provide update as you are able. thanks!

**Comment by RachalCassity** [comment]
Stack level too deep is from Semantic Logging.

**Comment by RachalCassity** [comment]
502 errors have not been seen since we separated routes to independent bulk head deployments. Still monitoring logs next week.
