### ISSUE TITLE
Add hideFormNavProgress optional property to Forms Library documentation

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#57002]
### Description

Add info on new `hideFormNavProgress` optional chapter-property to Forms Library documentation [here](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-form-config-options#VAFormsLibrary-FormConfigOptions-chapters) [VA Forms Library - Form Config Options > chapters]:
- Insert a new row in the chapters properties table, between title & pages rows: 
```markdown
| hideFormNavProgress (optional) | boolean | `hideStepText: true` |
```

This new, optional `hideFormNavProgress` property enables form-chapters to optionally hide the step-counter (progress-bar & "Step X of N: ...") near the top of its pages:

```javascript
someChapter: {
  title: 'Some chapter',
  hideFormNavProgress: true,
  ...
  pages: { ... }
},
```

Other chapters without this optional `hideFormNavProgress` prop would continue to display the step-counter on their pages.

### Relevant URLs
- Ticket: department-of-veterans-affairs/va.gov-team-forms#195
- Pull request: https://github.com/department-of-veterans-affairs/vets-website/pull/23965

### Which type of team are you on? (Platform team, VFS team, or Leadership)
Platform VA.gov Product Forms team.  Eng. Lead is @ndsprinkle

**Comment by vbellissimo** [comment]
Hi @tlei123 , thanks for your request. Our team is taking a look at this for next steps.

**Comment by tlei123** [comment]
Hi, @vbellissimo !  Thanks!

FYI, i got teammates reviewing my vets-website PR right now.  Will update here again when that's approved & merged into main.  It's an optional feature, so no harm at all if the docs-update(s) lag behind.  :)

**Comment by tlei123** [comment]
@vbellissimo , FYI, vets-website PR now merged into main branch.  hideFormNavProgress optional feature's now live.

**Comment by alyssagallion** [comment]
Currently working on finding the best group/person for the task at hand.

**Comment by alyssagallion** [comment]
@rsmithadhoc Over to you.

**Comment by tlei123** [comment]
@rsmithadhoc , feel free to send me a Zoom or Google-Meet invite to sync up on this, so that I can show you what I've added to the FormNav.jsx component.

Alternatively, just let me know if you'd rather just have me add a Comment here with some proposed doc-content.

**Comment by rsmithadhoc** [comment]
Thanks @tlei123, this one got lost in the shuffle. They just needed me to give it the go ahead, it all makes sense to me. Someone from the content team will follow up to update the page.

**Comment by vbellissimo** [comment]
@tlei123 This content update has been made. Let us know if you see otherwsie. Closing this ticket. Thanks!

cc @rsmithadhoc @alyssagallion

**Comment by tlei123** [comment]
@vbellissimo , sorry I gotta re-open this!

Please correct "hideStepText" to "hideFormNavProgress" &mdash; see screenshot below.  Thanks much!

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/587583/e3d5989a-9008-4220-a680-50ab995fda9b)

**Comment by vbellissimo** [comment]
@tlei123 Closing this ticket now that you've made the updates and we have published the changes. Thanks!
