### ISSUE TITLE
Midpoint Review - Content Feedback - Form 21-10210 Lay/Witness Statement

### ISSUE THREAD

**Issue by CherylEvans** [department-of-veterans-affairs/va.gov-team#57011]
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- I encourage you to continue working with SWCAIA

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (e.g., engineering/coding notes).

# Must

- (How To - Intro - User Type) How do I prepare before submitting a Lay/Witness statement? "Veterans" is being used as a singular possessive noun and needs to read "Veteran's" instead X 4 instances.![55260 Missing Apostrophe_2023-04-17 at 1.41.07 PM.png](https://images.zenhubusercontent.com/61fa9c81372349426637bcfa/6344c6f5-4a9c-443d-a745-36efe2453c8f)

- Story 1 - Veteran on their own behalf -> 4A-Authenticated -> Start -> Unclear Verb Action -> Note: If you need to update your personal information, please us at..." should read "Note: If you need to update your personal information, please (call) us at..."![55260 Unclear Verb Action and missing comma 2023-04-17 at 3.17.18 PM.png](https://images.zenhubusercontent.com/61fa9c81372349426637bcfa/7a775c14-2409-4c41-8ac2-4ad5675a90f8)
Ignore the "comma" annotation, as you don't necessarily need it. :-) 

- (How To - Intro - User Type) -> 2 Intro -> Here's how to apply online -> Inconsistent spacing -> "Complete this form. (Requires an additional space to match the spacing on the page.)![55260_Inconsistent Spacing_ 2023-04-17 at 1.56.52 PM.png](https://images.zenhubusercontent.com/61fa9c81372349426637bcfa/98048957-bc52-47ed-af0c-2c5e0847599c)

#Should

- (How To - Intro - User Type) 1 Intro -> You can also submit -> By mail -> "Print the form, fill it out, and send it..." I recommend using "Please" before "Print" to avoid sounding dictatorial. ![55260 "Use of Please" 2023-04-17 at 1.53.26 PM.png](https://images.zenhubusercontent.com/61fa9c81372349426637bcfa/1decbaf1-cf00-4408-8381-7f68576de78f)

**Comment by AndrewCoforma** [comment]
Completed implementing feedback.  Thank you @CherylEvans !  
  
https://www.sketch.com/s/a11421d3-c148-41a2-a34f-3d7821ea676f
