### ISSUE TITLE
EKS puma backlog climbs before pods startup

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#57018]
## Description

We currently scale based on puma capacity for our vets-api-web/bgs, etc pods. There is an initialDelaySeconds for pods coming up and in the meantime, the puma backlog climbs a bit. [Puma backlog for the past week.](https://vagov.ddog-gov.com/dashboard/yk6-mrp-k96/eks-puma-backlog-metrics?from_ts=1681223133548&to_ts=1681827933548&live=true)

We should revisit the initialDelay to tweak things to allow pods to come up faster.

**Comment by RachalCassity** [comment]
1) Created specific health check endpoints.  I do not believe we need the startupProbe. The readinessProbe is not dependent on the startupProbe, detailed [here](https://blog.devgenius.io/understanding-kubernetes-probes-5daaff67599a).
2) The new endpoints will help us monitor pod startup vs pod receiving traffic

**Comment by LindseySaari** [comment]
I thought that the startUp probe disables the readiness probe until it passes (weirdly though that doesn't seem to be the case)? I thought there was a reason for the startUp probe and setting the initialDelaySeconds. 


you can disable the startup probe if you already have a readiness probe set up. However, keep in mind that these probes serve different purposes:

A startup probe is used to check whether the application within the container has started. This is particularly useful for applications that take a while to initialize. If you specify a startup probe, the liveness and readiness probes are disabled until it succeeds.

A readiness probe is used to check if the container is ready to serve requests. It ensures that traffic doesn't reach a pod until the container is ready to handle it.

If your application starts quickly and doesn't need an initialization period, you might not need a startup probe and can rely solely on the readiness (and possibly liveness) probe. If your application takes a significant amount of time to start, the startup probe can be beneficial to prevent the kubelet from killing the container before it's fully up and running.

Remember, it's not necessarily about choosing one type of probe over another. They serve different purposes, and using them in combination can help ensure your applications are running as expected and handle traffic appropriately. Before you make changes, ensure you understand the requirements and behavior of your application to choose the correct probe setup.

**Comment by LindseySaari** [comment]
In short, if we are observing the correct behavior in lower envs, it's probably safe to remove in production. I think since we don't fall into the bucket of "your application takes a significant amount of time to start" then the statement of "If your application starts quickly and doesn't need an initialization period, you might not need a startup probe and can rely solely on the readiness (and possibly liveness) probe" makes sense. cc @RachalCassity

**Comment by RachalCassity** [comment]
The startup_healthcheck endpoint needs to be removed after prod is synced.

**Comment by laineymajor** [comment]
Can close per Lindsey and Rachal
