### ISSUE TITLE
SemanticLogger 502s

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#57019]
## Description

Semantic logging is causing some 502 errors. The [SemanticLogger.reopen](https://oddball.slack.com/archives/C045LCF8WU8/p1681828001106459?thread_ts=1681827568.823199&cid=C045LCF8WU8) method is causing so many errors (2.5k errors) in one minute. The error is reported on multiple pods

[See this thread](https://oddball.slack.com/archives/C045LCF8WU8/p1681827849562399?thread_ts=1681827568.823199&cid=C045LCF8WU8)

[Loki Logs](https://grafana.vfs.va.gov/explore?orgId=1&left=%5B%22now-2d%22,%22now%22,%22Loki%20(Prod)%22,%7B%22expr%22:%22%7Bapp%3D%5C%22vets-api-web%5C%22%7D%20%7C%3D%20%5C%22SemanticLogger%5C%22%22%7D,%7B%22expr%22:%22%22%7D%5D&right=%5B%22now-1h%22,%22now%22,%22Loki%20(Dev)%22,%7B%22expr%22:%22%7Bapp%3D%5C%22vets-api-server%5C%22%7D%20%7C%3D%20%5C%22Warden%5C%22%22%7D,%7B%22expr%22:%22%22%7D%5D) - filtered by vets-api-web

[vets-api-web Datadog logs](https://vagov.ddog-gov.com/logs?query=SemanticLogger%20&cols=host%2Cservice&event=AgAAAYeUxGEmjbnqgAAAAAAAAAAYAAAAAEFZZVV4R0daQUFCaUltU00wdFJPX1FBRQAAACQAAAAAMDE4Nzk0YzUtNDVlNi00NmYwLTkxN2EtNTQ5MzAyOTkxODc5&index=%2A&messageDisplay=inline&stream_sort=desc&viz=stream&from_ts=1681655367476&to_ts=1681828167476&live=true)

**Comment by RachalCassity** [comment]
Here are other [logs](https://vagov.ddog-gov.com/logs?query=host%3Ai-0418beb8f64d1dfff%20status%3Aerror&cols=host%2Cservice&event=AgAAAYeUyQW7qtOjnAAAAAAAAAAYAAAAAEFZZVV5UW50QUFCX0tQMzE3ZF8yRHdQTQAAACQAAAAAMDE4Nzk0Y2ItM2EzOS00Mzc5LWI2NjgtNmM3YTgxZDlhNWFk&index=%2A&messageDisplay=inline&stream_sort=desc&viz=stream&from_ts=1681655367476&to_ts=1681828167476&live=true)

**Comment by LindseySaari** [comment]
This is a duplicate

**Comment by laineymajor** [comment]
Closing and adding to the monitoring epic.
