### ISSUE TITLE
SOCKS access for Randi Mays

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/va.gov-team#57026]
### Your Name

Randi Mays

### Your Email

rmays@kindsys.us

### Your Role and Team

Front End Engineer on Sitewide - Public Websites

### Product Manager (PM) name and email

Wes Rowe, wesley.rowe@agile6.com

### Product Owner (PO) name and email

Dave Conlon, david.conlon@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDB37ZmN7d3sjMnrKf6+J/vYuOYpp/Y6YSZGZ9/lvaFonCp75j7+358cn3T0qGIGReuqVG1sPnvSdZXTwDjDuer/jazuBKCwrGVWXBWraJ2U7EGFGY207O7sWC/vfWxFxJqCnnKh183yHQeOFLscxKfHT3TMCyg1TIFDQhixyObO7ivqHZ0zGs6nT7+jdSAyLQs4gU+NZKlg7RK6gTjOm+IWU7ubH/CzgdYFkVRnSGcoJnHxbRm98R9NbAsHDIeb5rIMEqgpkLZ8ciQ0ZYR5YQd2CmLsFuLngZ0wpCEIG71a6WUSgcbAzuEAMMr5f/+P1smtfG+4bsJTKrmOEt4yIiDcTvjmgIgiUXhuiO93dDWKZ8ZSJWwG51XD2gRVWe/XWGaJj0OOSack6gPlcveTCkusvutil0TAV+7dP6h3u/pIS5RKkqO2gL8nmOtzPy9pWl18Zlu6e26girUVLmGlUvjdnkvekRsX8fVvm8u9u3KvLBH9k3ExHI7eaYMeAJAZ6c= randimays@Randis-MBP

### E-QIP Transmittal Confirmation

<img width="1458" alt="Screenshot 2023-04-18 at 8 24 35 AM" src="https://user-images.githubusercontent.com/19175324/232829561-0a874265-0b40-442a-8b0b-c76716a4b47b.png">

Extra note: I am scheduled for the next available Platform Orientation on May 9.

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by randimays** [comment]
@jilladams for awareness

**Comment by considerable** [comment]
Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.

**Comment by randimays** [comment]
@considerable Might it take longer than that to propagate? Trying to run `vtk socks setup` in the terminal and I'm getting this error message: `WARN: SSH key is not approved yet. Once it is, re-run `vtk socks setup`.

**Comment by considerable** [comment]
@randimays Our [Troubleshooting (SOCKS) issues](https://vfs.atlassian.net/wiki/spaces/SUP/pages/2153742376/Infrastructure+Operations) doc says, 
If it still does not work,  then you should backup your $HOME/.ssh/config file, move it and re-run the vtk socks setup.
    This should recreate the [config file with the correct VA SSH aliases](https://github.com/department-of-veterans-affairs/devops/blob/master/ssh/config).
Please see if these steps help.

**Comment by considerable** [comment]
Hopefully, everything works by now. Closing the tkt. Please let me know if it needs to be reopened.

**Comment by randimays** [comment]
@considerable I think everything is mostly working, though I have not tried to push code yet. I do get an error when running `ssh socks`, though. It says `This account is currently not available.` and closes the connection.
