### ISSUE TITLE
[UX] Determine the ROIs for the Remaining Appointment Types/Modalities

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#57021]
## Background
Currently, Pre-Check-in only supports in-person and phone appointments and eCheck-in only supports in-person appointments. There are other appointment modalities that we could potentially support. We should do some research to determine if we should/could support these other modailities.

- List of Appointment Modalities
![image](https://user-images.githubusercontent.com/86678742/230946138-2ac1a283-8720-413e-9cf6-3a45f08eec0a.png)

- Other Info
    - Some sites at Bay Pines are sending pre-check-in links for VVC appointments.  This ends up presenting conflicting information between the SMS and pre-check-in confirmation page; the sms clearly calls out correctly that this is a video visit, but pre-check-in verbiage indicates that the provider will call the Veteran, which is relevant to telephone appointments
        - [Slack thread](https://dsva.slack.com/archives/C022AC2STBM/p1680874744840519)
    - CVT appointments have a patient-side and a provider-side appointment (2 appts) but they are treated as the same appointment ([slack thread](https://dsva.slack.com/archives/C022AC2STBM/p1656531011967319))
        - [GitHub documentation](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/discovery/cvt-appointments)

## User Story
As a team, we need to determine the ROI** for supporting each of the remaining appointment types/modalities. From this determination, we can then decide which ones we will work towards supporting in Pre-Check-in and/or eCheck-in applications and in what order.

** ROI, here, is represented by the ratio of the estimated Veteran impact to the estimated implementation effort
   In this example, a higher impact vs. effort would have a higher ROI
   5 impact/3 effort = 1.67
   3 impact/5 effort = 0.6
   5 impact/5 effort = 1

## Tasks
- Develop list of questions
- Show those to Stephen & Shawn & have a meeting with them
  - Who else should we talk to? 
- Create f/u ticket(s)

**Comment by benbrasso-agile6** [comment]
@kellysmith1008 I'm going to grab a few conversations for some background on different modalities: 

* https://dsva.slack.com/archives/C022AC2STBM/p1659452379493209

**Comment by benbrasso-agile6** [comment]
There might not actually be any other modalities to add. I think we need to confirm with Shawn and Stephen if all of the other appt types listed in the screenshot above all belong to VVC. If so, I think there was some conversation in here about not needing or being able to integrate with VVC. Probably a good idea to read through the [conversation here](https://dsva.slack.com/archives/C022AC2STBM/p1680874744840519).

**Comment by benbrasso-agile6** [comment]
* Can we accurately identify this appointment type? (Or, how might we figure this out?)
* Roughly, percentage of total appts? (E.g., how many vets does this impact?) 
* From a work flow perspective, could PCI fit into the process? Pre-check-in only? 
* Who could we talk to understand the workflow a bit more for both Veterans and staff? Any providers that we could connect with?

**Comment by benbrasso-agile6** [comment]
@kellysmith1008 

Determine the value of PCI supporting other appointment modalities (in addition to in person and phone), including: 

- VVC at a facility
- VVC at an ATLAS location
- VVC at home
- VVC using a VA device

Questions to help determine value of each: 

- How many appointments are scheduled for each? 
- Is it worth pursing PCI support? For example, how easy or difficult would it be to integrate pre-check-in? Check-in? (If unsure, who could we speak to to understand how it works?) 

And, finally: 

- Are there other appointment modalities that we're forgetting?

**Comment by kellysmith1008** [comment]
![image.png](https://images.zenhubusercontent.com/63346ebd45ab78d62eea3201/605bfcd1-711d-4c6b-8430-0b45a3be6dd4)
FY 2022:
![image.png](https://images.zenhubusercontent.com/63346ebd45ab78d62eea3201/355ff2aa-f014-4206-8bf3-5efba5011320)

[Link to slack message](https://dsva.slack.com/archives/C022AC2STBM/p1682432660843999)

**Comment by loripusey** [comment]
![image](https://user-images.githubusercontent.com/86678742/234333592-56188f02-8a12-41bb-8901-a0fdedffcdd7.png)

**Comment by kellysmith1008** [comment]
We met on May 1 to discuss this ticket. Per slack communications from Shawn, we aren't going to pursue any video appointment types because they have separate software for notifications.
