### ISSUE TITLE
Investigate Semantic Logger "stack level too deep" Exceptions

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#57031]
### PROBLEM STATEMENT

[Stack level too deep errors](https://vagov.ddog-gov.com/logs?query=SemanticLogger%20%22stack%20level%20too%20deep%22%20&cols=host%2Cservice&context_event=AYeVAfBZAAB_KP317e9ojgAy&index=%2A&messageDisplay=inline&stream_sort=time%2Cdesc&to_event=AgAAAYeVAfAIHVKgDAAAAAAAAAAYAAAAAEFZZVZBZkJaQUFCX0tQMzE3ZTlvamdBOAAAACQAAAAAMDE4Nzk1MDEtZjBkMC00MDQxLWJkMGEtMmVjZTJmYTk4NTFl&viz=&from_ts=1679242792430&to_ts=1681834792430&live=true) have been occurring at a rate of ~190/hour for over a month. When we migrated to EKS [we noticed the log level switched](https://vagov.ddog-gov.com/logs?query=SemanticLogger%20%22stack%20level%20too%20deep%22%20&cols=host%2Cservice&context_event=AYeVAfBZAAB_KP317e9ojgAy&index=%2A&messageDisplay=inline&stream_sort=time%2Cdesc&to_event=AgAAAYeVAfAIHVKgDAAAAAAAAAAYAAAAAEFZZVZBZkJaQUFCX0tQMzE3ZTlvamdBOAAAACQAAAAAMDE4Nzk1MDEtZjBkMC00MDQxLWJkMGEtMmVjZTJmYTk4NTFl&viz=&from_ts=1681420159190&to_ts=1681421656042&live=false) from `info` to `error`. The error [seems to be a loop](https://vagov.ddog-gov.com/logs?query=host%3Ai-06834b9677488d810%20service%3Avets-api%20container_id%3A694f02d4511eddbe93b45f61c5332448a690201e0eae1588a0c1a5bd4fc8483f%20filename%3A0.log%20&cols=host%2Cservice&context_event=AYeVAfBZAAB_KP317e9ojgAy&index=%2A&messageDisplay=inline&stream_sort=time%2Cdesc&to_event=AgAAAYeVAfAIHVKgDAAAAAAAAAAYAAAAAEFZZVZBZkJaQUFCX0tQMzE3ZTlvamdBOAAAACQAAAAAMDE4Nzk1MDEtZjBkMC00MDQxLWJkMGEtMmVjZTJmYTk4NTFl&viz=&from_ts=1681831844904&to_ts=1681832177971&live=false) in calling `as_json` so it may be circular serialization.

Unfortunately we can't tell which route the error is triggered from but `/mobile` routes are suspect as [those were the routes that were migrated to EKS](https://github.com/department-of-veterans-affairs/devops/pull/12836/files) when the exception was logged as `error` instead of `info`.

```[tasklist]
### Action Items
- [ ] Create a bulkhead for all mobile routes
- [ ] Migrate mobile routes in clusters until the error is logged with the new bulkhead name (e.g. vets-api-mobile) and then migrate small subsets back until the exact route is pinpointed
- [ ] Investigate code related to endpoint; delegate to mobile team after a reasonable time box
```

### ACCEPTANCE CRITERIA

"Stack level too deep" exceptions are not triggering OR a new ticket has been delegated to mobile.

**Comment by LindseySaari** [comment]
Here are other [dd logs](https://vagov.ddog-gov.com/logs?query=host%3Ai-0418beb8f64d1dfff%20status%3Aerror&cols=host%2Cservice&event=AgAAAYeUyQW7qtOjnAAAAAAAAAAYAAAAAEFZZVV5UW50QUFCX0tQMzE3ZF8yRHdQTQAAACQAAAAAMDE4Nzk0Y2ItM2EzOS00Mzc5LWI2NjgtNmM3YTgxZDlhNWFk&index=%2A&messageDisplay=inline&stream_sort=desc&viz=stream&from_ts=1681655367476&to_ts=1681828167476&live=true)

Other [Loki logs](https://grafana.vfs.va.gov/explore?orgId=1&left=%5B%22now-12h%22,%22now%22,%22Loki%20(Prod)%22,%7B%22expr%22:%22%7Bapp%3D%5C%22vets-api-web%5C%22%7D%20%7C%3D%20%5C%22%2Fsemantic_logger-4.12%5C%22%22%7D,%7B%22expr%22:%22%22%7D%5D&right=%5B%22now-1h%22,%22now%22,%22Loki%20(Dev)%22,%7B%22expr%22:%22%7Bapp%3D%5C%22vets-api-server%5C%22%7D%20%7C%3D%20%5C%22Warden%5C%22%22%7D,%7B%22expr%22:%22%22%7D%5D)

**Comment by LindseySaari** [comment]
Here are other [dd logs](https://vagov.ddog-gov.com/logs?query=host%3Ai-0418beb8f64d1dfff%20status%3Aerror&cols=host%2Cservice&event=AgAAAYeUyQW7qtOjnAAAAAAAAAAYAAAAAEFZZVV5UW50QUFCX0tQMzE3ZF8yRHdQTQAAACQAAAAAMDE4Nzk0Y2ItM2EzOS00Mzc5LWI2NjgtNmM3YTgxZDlhNWFk&index=%2A&messageDisplay=inline&stream_sort=desc&viz=stream&from_ts=1681655367476&to_ts=1681828167476&live=true)

Other [Loki logs](https://grafana.vfs.va.gov/explore?orgId=1&left=%5B%22now-12h%22,%22now%22,%22Loki%20(Prod)%22,%7B%22expr%22:%22%7Bapp%3D%5C%22vets-api-web%5C%22%7D%20%7C%3D%20%5C%22%2Fsemantic_logger-4.12%5C%22%22%7D,%7B%22expr%22:%22%22%7D%5D&right=%5B%22now-1h%22,%22now%22,%22Loki%20(Dev)%22,%7B%22expr%22:%22%7Bapp%3D%5C%22vets-api-server%5C%22%7D%20%7C%3D%20%5C%22Warden%5C%22%22%7D,%7B%22expr%22:%22%22%7D%5D)

**Comment by laineymajor** [comment]
@LindseySaari @RachalCassity 
Here's the ticket for semantic logger

**Comment by LindseySaari** [comment]
Since creating the bulkhead deployments, the `mobile-health-endpoints` pod is receiving the Semantic Logger Errors. [See logs](https://vagov.ddog-gov.com/logs?query=SemanticLogger%20%22stack%20level%20too%20deep%22%20&cols=host%2Cservice&context_event=AYeVAfBZAAB_KP317e9ojgAy&event=AgAAAYektGgg9Euf0AAAAAAAAAAYAAAAAEFZZWt0R2hJQUFESXMtRmhnUXE4U0FBQQAAACQAAAAAMDE4N2E0YjUtMGZiNC00Yzg1LTgwNjktMTk2NDQxNTAzN2M1&index=%2A&messageDisplay=inline&stream_sort=time%2Cdesc&viz=&from_ts=1682081067793&to_ts=1682095467793&live=true)



![Screenshot 2023-04-21 at 12.50.11 PM.png](https://images.zenhubusercontent.com/5d4836dda95c51615db9bdc9/c99b656b-426d-4600-b42e-af820eee16c2)

**Comment by RachalCassity** [comment]
The [json issue](https://app.zenhub.com/workspaces/platform-tech-team-1-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/57241) is the same error.

**Comment by laineymajor** [comment]
Currently with mobile team. Potential carryover to next sprint.

**Comment by laineymajor** [comment]
@RachalCassity do you think this was addressed when mobile made their changes. 

Need to revisit when we write up our policies/hand-off materials.

**Comment by laineymajor** [comment]
Very significant reduction in errors (CPU decreased by half) after working with Kris from mobile.

**Comment by laineymajor** [comment]
Going to write up a separate epic with
-guidance
-clean up instructions
-next steps
and send to teams for clean-up

^^^could be a good backend CoP item

**Comment by laineymajor** [comment]
Can be closed as mobile team commented out their logs
