### ISSUE TITLE
AWS access for Eddie Glenn

### ISSUE THREAD

**Issue by navaeddie** [department-of-veterans-affairs/va.gov-team#57034]
### COR Name

Delano McVay

### Vendor Onboarding Representative Name

Agile Six - Anthony M. Arashiro

### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Eddie Glenn

### Your Email

hodges.glenn@va.gov

### Team, Role, and Company of the target individual

Benefits Disability Experience, Software Engineer, Nava

### Product Manager (PM) name and email

Rakshinda Aslam - rakshinda.aslam@agile6.com

### Product Owner (PO) name and email

Matthew Self - matthewself.dsva@gmail.com

### Desired AWS Access

I would like to update the Parameter Store with credentials for Lighthouse APIs that `vets-api` will rely on.

### Access Expiration

January 1, 2024

### E-QIP Transmittal Confirmation

![image](https://user-images.githubusercontent.com/123964597/232842668-4da0df6f-e579-4d5b-92e3-e0551ed2d32c.png)

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by considerable** [comment]
VFS Team Roaster

@navaeddie if you know someone with an access level similar to what you need, please post it here. Otherwise, I will apply my best effort to align you with just the right group.

**Comment by navaeddie** [comment]
@considerable a teammate of mine opened a [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/56501) for the same purpose. Does that give you what you need?

**Comment by considerable** [comment]
Yes, thank you. As soon as the management removes the `Awaiting Approval` label, will move this all forward.

**Comment by BillChapmanUSDS** [comment]
I approve this access.

**Comment by considerable** [comment]
initial password provided via Slack DM.
