### ISSUE TITLE
Profile edit email modal validations on staging do not match production

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#5704]
- [x] change the validation error to: `Please enter the email address again, using this format: X@X.com`
- [x] show an error if the email text field is left blank

**Comment by erikphansen** [comment]
@Samara-Strauss or @mshea0606 this can be validated on staging now. Let me know if you need a little more info to validate it, Matt.

**Comment by Samara-Strauss** [comment]
Looks good to me!
