### ISSUE TITLE
QRG Creation 

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#57057]
## Product Outline
QRG Creation

## High Level User Story/ies
As a Tier 1 Agent I need to access to a simple and easy to understand guide so I easily answer common VA.gov questions and reduce the time it takes to assist Veteran during incoming calls to VA.gov.

## Hypothesis or Bet
**If Tier 1 Agents have Quick Reference Guides then the incoming calls can be resolved or routed correctly.  Thereby reducing the volume of issues escalated to Tier 2 Reps prolonging the time to issue resolution. 

## OKR
Case Handling Priorities
Salesforce Optimization
Transitioning to email to case in Salesforce (Q3)
Adding necessary case categories and case types (i.e. login.gov)
Organize and formalize case work with fully staffed team (Q3)
Tier 3 restructuring (Q3 + Q4)

### What must be true in order for you to consider this epic complete? 

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `Console-Services`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by clantosswett** [comment]
@starlow00 @Kimberley2019 can you work with @ATMiddleton to determine what our definition of done is for this epic? Below are some examples of criteria for what "done" looks like. These are suggestions but I do think the criteria shouldn't just be a number but also include some sort of measurement for determining continued success. 

- 20 QRG's created that cover the top 20 issue Veteran issues coming to the Tier 1 Contact Center.
- QRG's are stored in a permanent and accessible location with a plan in place for continuous updating and auditing. 
- Completed survey or focus group to get feedback on the product and determine any next steps for future work.

**Comment by starlow00** [comment]
Reached out to teammates to set a meeting to discuss this item.

**Comment by ATMiddleton** [comment]
@starlow00 - Updated number of QRG's to complete

**Comment by clantosswett** [comment]
@atmiddleton @kimberley2023-csm @starlow00 please come together to determine if this epic can be closed. I know QRGs will still be created but perhaps that can fall under the ongoing documentation epic.

**Comment by clantosswett** [comment]
@ATMiddleton, @Kimberley2019 @starlow00 Over a year since this has had any activity? Is this closed? I would propose yes.

**Comment by starlow00** [comment]
I agreed that it should be closed and that QRGs will occasionally (but not regularly) fall under the ongoing documentation epic.

**Comment by ATMiddleton** [comment]
The assumption was requests for QRGs would be more frequent - as of now, the requests are less frequent, and this ticket can be closed.
