### ISSUE TITLE
Spike: In Person Proofing Companion solution

### ISSUE THREAD

**Issue by mjconw3** [department-of-veterans-affairs/va.gov-team#57078]
## Description
One of the solutions we want to create for in person proofing is a companion "app" That allows users to have an assistant that guides them through the process of verification and account creation. We need to research what this solution could look like, what already exists and how we can build the solution to aide veterans and their families.

## Product notes, Risks and Concerns
- If Login.gov or ID.me changes their flow, we need to be in the know about it and update our app accordingly
- Will this increase the percentage of success or not? 
- Can we use this solution to track where people are having the most issues?
- Where on Login.gov or ID.me will this content/solution live?

## Acceptance Criteria
- [x] Research what documentation, guides, language already exists around aiding users in verification and account creation
- [x] Document where there are shortcomings and what we could do to create a better solution 
- [x] Investigate whether this could be an page that lives on VA.gov with a step by step, an actual application or something else
- [x] Document and Share findings with appropriate team members
- [x] Based on the findings of this spike, follow on tasking is created

**Comment by aparsley** [comment]
Please look below:

Chatbot launched messaging feature where they are re-directed to the Login and ID.Me sites for answers to their questions.
Chatbot team is working with content team to draft and post responses to questions
Comments are available on GitHub: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Research/web-comments/Findings%20from%20VA%20login%20post%20comment%20analysis.md

**Comment by aparsley** [comment]
- Content Strategy Completed
- Verification Walk Through Guide Completed
- Verification Video Transcript Completed

**Comment by aparsley** [comment]
Verification Video is now in place of this.

**Comment by aparsley** [comment]
https://docs.google.com/presentation/d/1p5AFJrXqxjuTqy5DIdn8w8qLGSFjAPm0/edit#slide=id.g24eda3b8084_0_17

Companion App Guide to be used @asg5704
