### ISSUE TITLE
IA work for past education rates

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#57094]
## Issue Description

After talking with stakeholders, we are now going to keep more than just 1 year of past education rates on VA.gov. We need to determine the urls and H1s for these past rates pages and how they'll be linked in the left nav. 

Beth and Danielle already talked through suggested changes:

Current rates page: Post-9/11 GI Bill (Chapter 33) rates
Published past rates: Past rates for Post-9/11 GI Bill
Proposed past rates: Past rates: 2021-22 Post-9/11 GI Bill

Current rates page: Montgomery GI Bill Active Duty (Chapter 30) rates
Published past rates: Past rates for Montgomery GI Bill Active Duty
Proposed past rates: Past rates: 2021-22 MGIB-AD

Current rates page: Montgomery GI Bill Selected Reserve (Chapter 1606) rates (56 char.)
Published past rates: Past rates for Montgomery GI Bill Selected Reserve
Proposed past rates: Past rates: 2021-22 MGIB-SR

Current rates page: Chapter 35 rates for survivors and dependents
Published past rates: Past rates for Chapter 35
Proposed past rates: Past rates: 2021-22 Chapter 35

**We're still checking whether we need to post these past rates:**
Current rates page: Fry Scholarship rates
Published past rates: Past rates for the Fry Scholarship
Proposed past rates: Past rates: 2021-22 Fry Scholarship

Current rates page: Edith Nourse Rogers STEM Scholarship rates
Proposed past rates: Past rates: 2021-22 STEM Scholarship

Current rates page: VET TEC rates
Proposed past rates: Past rates: 2021-22 VET TEC

Current rates page: Transferred Post-9/11 GI Bill benefit rates
Proposed past rates: Past rates: 2021-22 transferred benefits

Once these rates pages are live, we'll set up a redirect ticket for the past rates pages that already live assuming that their urls will have changed.

## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] Final IA determined and ready to be implemented

**Comment by RLHecht** [comment]
@mnorthuis @bethpottsVADEPO here's the IA ticket for this past rates work. I added the proposed H1s the two of you already talked through.

**Comment by mnorthuis** [comment]
@bethpottsVADEPO  Is there a reason we did not add the current school year to the current rates page to be consistent to how we have done this with other rates pages?

@jennymayoco This can be picked up when you are available.  Please review how we structured rates within other areas of the site.  One example is disability: https://staging.va.gov/disability/compensation-rates/veteran-rates/.  We will need to change the URL on the existing past rates page and redirect it.

**Comment by bethpottsVADEPO** [comment]
@mnorthuis This was a character count issue because with education programs, not only are several of the program names long but also the rates don't correspond to a single year but instead a date range because of the academic year (2021-22 is almost twice the character count of 2021). And for SEO reasons, some of the H1s needed to have the chapter info.

**Comment by mnorthuis** [comment]
I kind of wondered that!

**Comment by jennymayoco** [comment]
Hello! @RLHecht Here are the URLs for the proposed pages

#### Veteran benefit rates
/education/benefit-rates/post-9-11-gi-bill-rates/past-rates-2021-2022/
/education/benefit-rates/montgomery-active-duty-rates/past-rates-2021-2022/
/education/benefit-rates/montgomery-selected-reserve-rates/past-rates-2021-2022/
#### Survivor and dependent rates
/education/benefit-rates/chapter-35-rates/past-rates-2021-2022/

#### Notes
- The format for the past rates is /past-rates-YYYY-YYYY/

**Comment by RLHecht** [comment]
Thank you! I'll add this to our publishing ticket so that Megan knows the urls to set up. I think this is good to close.

**Comment by RLHecht** [comment]
@jennymayoco would you set the left nav like this?
Past rates: 2021-2022 
Past rates: 2020-2021

**Comment by jennymayoco** [comment]
@RLHecht yes! Thanks for flagging!
