### ISSUE TITLE
Create error message for the Find a VA form search MVP

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#5709]
### 1/ On this page - in the REACT widget: https://prod.cms.va.gov/find-va-forms

__Update not-found error message:__
No results were found for "<**userquery**>." Try using fewer words or broadening your search.  If you're looking for non-VA forms, go to the [GSA Forms Library](https://www.gsa.gov/reference/forms).

![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/dc3522d4-9e72-425a-9f4e-be34fa856cd7)

__Description:__
Currently there are some non-VA forms and internal forms (for contractors, employees) that have been added to the publicly searchable db. (Ex: SF1188 Cancellation of Payroll Deductions for Labor Organization Dues). 

We are asking for these forms to be removed from external searches, and in order to address those users who continue to search for non-VA and internal forms, we want to update the current 'not found message' to provide a little more detail for those users. 

## Acceptance Criteria
- [ ] Update text in REACT - @kelsonic  
- [ ] Review/check updated text - @RLHecht 

ETA: Before launch.

**Comment by jenniferlee-dsva** [comment]
@MickinSahni  fysa ^ - Not urgent.

**Comment by jenniferlee-dsva** [comment]
@MickinSahni - FYSA - not urgent

**Comment by RLHecht** [comment]
@kelsonic A word was missing in the error messaging above. I just added it in above (there was a "for" missing before "non-VA." Thanks!

**Comment by kelsonic** [comment]
Hmm, are we ok with how this is styled now that the error message is so long?

![image](https://user-images.githubusercontent.com/12773166/74377445-1ffd7880-4da1-11ea-919b-3e2c39168955.png)

**Comment by jenniferlee-dsva** [comment]
@kelsonic - I'm afraid it has to be in order to address ppl who at first continue to search for non-VA forms. Could you try using our normal (smaller) body copy font, instead of the intro text font? 
Also, ^ missing the word "for" in the last sentence.

**Comment by kelsonic** [comment]
@jenniferlee-dsva Something like this?

![image](https://user-images.githubusercontent.com/12773166/74444098-9649bb80-4e31-11ea-9e1b-b2129e4d9efb.png)

**Comment by jenniferlee-dsva** [comment]
Just asked Ryan Thurlwell for guidance - it should be the body copy font - marked up here. It is sans serif, so not just smaller. (Ug, I can't upload files on VA network, so I will slack you the screenshot.)

**Comment by kelsonic** [comment]
@jenniferlee-dsva Updated font-family:

![image](https://user-images.githubusercontent.com/12773166/74445586-dc078380-4e33-11ea-9c4f-0798ec8ed12d.png)

**Comment by kelsonic** [comment]
@jenniferlee-dsva Updated font-family and font-size:

![image](https://user-images.githubusercontent.com/12773166/74445727-18d37a80-4e34-11ea-9737-65074a480c22.png)

**Comment by jenniferlee-dsva** [comment]
Looking good.... One more typo: the period should be inside the quotation mark (per American English - TMI, British English uses periods outside, we place them inside.) 

Ex: No results were found for "xyz."  _<--period, then "_ 

Once the ^ changed, if you can get Randi to do a proofread, then all is well! Thank you @kelsonic .

**Comment by MickinSahni** [comment]
2020-02-14 PW Standup
- follow-up PR awaiting review before merging (https://github.com/department-of-veterans-affairs/vets-website/pull/11686)

**Comment by MickinSahni** [comment]
2020-02-19 PW Standup
- 2 PRs are merged and validated

![image](https://user-images.githubusercontent.com/13204473/74854032-bd5e2c80-530c-11ea-86e7-4f5f205f1a4d.png)

Note: once we update the properties used in v0/forms, that query will return a 👍
