### ISSUE TITLE
Staging:  Jacqueline Morgan one patient always/consistently showing errors

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#57096]
Log in as Jacqueline.morgan@id.me
Select Primary Care
Error displays 502 error in dev tools.  
https://staging-api.va.gov/vaos/v2/appointments?_include=facilities,clinics&start=2021-04-19T06:00:00Z&end=2022-04-19T06:00:00Z&statuses[]=booked&statuses[]=arrived&statuses[]=fulfilled&statuses[]=cancelled

{"errors":[{"title":"Bad Gateway","detail":"Received an an invalid response from the upstream server","code":"VAOS_502","source":{"vamfUrl":"https://internal-dsva-vagov-staging-fwdproxy-1821450725.us-gov-west-1.elb.amazonaws.com:4463/vaos/v1/patients/1012846043V576341/appointments?end=2022-04-19T06%3A00%3A00Z&pageSize=0&start=2021-04-19T06%3A00%3A00Z&statuses=booked%2Carrived%2Cfulfilled%2Ccancelled","vamfBody":"{\"id\":\"42d83001-7e5d-48e6-add4-51cf1a97abe2\",\"code\":500,\"errorCode\":7003,\"traceId\":\"ca4ad2d89b8912a072ad07f4d1dfd5ba\",\"message\":\"failed to fetch appointments\",\"meta\":{\"upstreamErrorSource\":\"mobile-appointment-service\",\"upstreamErrorId\":\"77433380-792c-4e69-942a-561d1c6bf8f3\"}}","vamfStatus":500},"status":"502"}]}

Decide to continue on Cheyenne.  We’re sorry. We’ve run into a problem displays on screen.  
502 error displays

https://staging-api.va.gov/vaos/v2/eligibility?facility_id=983&clinical_service_id=primaryCare&type=request
{"errors":[{"title":"Bad Gateway","detail":"Received an an invalid response from the upstream server","code":"VAOS_502","source":{"vamfUrl":"https://internal-dsva-vagov-staging-fwdproxy-1821450725.us-gov-west-1.elb.amazonaws.com:4463/vaos/v1/patients/1012846043V576341/eligibility?clinicalServiceId=primaryCare&facilityId=983&type=request","vamfBody":"{\"id\":\"a22ab14c-c963-4718-90a8-690d93f808aa\",\"code\":500,\"errorCode\":7003,\"traceId\":\"258a99e46485e174d281a8522edd81c0\",\"message\":\"failed to fetch appointments\",\"meta\":{\"upstreamErrorSource\":\"mobile-appointment-service\",\"upstreamErrorId\":\"02fcb751-bf13-4353-b561-d2f9aaa572cb\"}}","vamfStatus":500},"status":"502"}]}

**Comment by ldelacosta** [comment]
From Thomas:  I’ve been digging in to the issue with Jacqueline and the error 
@s t e v e b r u s h
 sees in the scheduling flow. It’s actually a backend issue. There’s a Cerner appointment coming back from VVS on 11/09/2021 that has a site of 0 and that’s causing issues. The eligibility check during the scheduling flow is pulling that appointment back and then it’s failing because we’re expecting a 3 digit parent facility :thinking_face:  @Laith Al-Samir @Jenna Gaze

[DSVA thread](https://dsva.slack.com/archives/CMNQT72LX/p1681920082012599)

**Comment by ldelacosta** [comment]
Per SoS update, this is not a FE issue. Here's the[ VAOSR ticket ](https://issues.mobilehealth.va.gov/browse/VAOSR-6206)to handle the work. Closing out the ticket.
