### ISSUE TITLE
Direct schedule flow - Increase the character limit on the comments field (Choose your reason for appointment page)  

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#57111]
## Description
The direct scheduling flow endpoint service is changing to Acheron. With the new Acheron changes, the comments field has increased to 500 characters. We will increase the user's comment on the Choose your reason for appointment page to 250. 

When the user selects any of the reasons, user will be able to enter up to 250 characters in the comments. 

Current: 
<img width="528" alt="Screenshot 2023-04-19 at 1 25 07 PM" src="https://user-images.githubusercontent.com/90797205/233153327-3e9fbf3a-ba81-40f9-ae59-a5672b59c3ff.png">
<img width="510" alt="Screenshot 2023-04-19 at 1 26 05 PM" src="https://user-images.githubusercontent.com/90797205/233153328-5dee7acb-bcd5-43c5-92df-dd452e6edc68.png">
<img width="518" alt="Screenshot 2023-04-19 at 1 25 30 PM" src="https://user-images.githubusercontent.com/90797205/233153330-79da0e1b-95dc-4463-a9ed-8007670f4503.png">
<img width="509" alt="Screenshot 2023-04-19 at 1 26 22 PM" src="https://user-images.githubusercontent.com/90797205/233153331-ee3514bf-6d2f-40f2-897f-2c0f29a8a273.png">

Update: 

---

## Acceptance Criteria

Given the user starts the VA direct schedule appointment flow 
When the user is on the `Choose your reason for appointment` page 
Then the user will enter up to 250 characters in the comments field. 

### Design Assets
N/A

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by ldelacosta** [comment]
In the UI, confirmed the increase of the character limit to 250 for direct scheduling. ![Screenshot 2023-06-20 at 1.30.51 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/a0e7818d-5dad-46de-8fcf-c30d39aa8145)
![Screenshot 2023-06-20 at 1.31.13 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/7ba4c861-15c0-4437-8adb-108d3fcdcd7a)![Screenshot 2023-06-20 at 1.31.38 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/8fad8e0f-299a-4028-8130-5627d375cf1c)![Screenshot 2023-06-20 at 1.31.56 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/07ec6293-4365-4abd-a984-062cb547555f)

**Comment by ldelacosta** [comment]
@jenniemc - I'm getting a 400 error when trying to submit the 250 character limit. Is this a backend issue? 

![Screenshot 2023-06-20 at 11.59.07 AM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/26c68b8a-7b61-461d-9ec8-fd200c3de273)

**Comment by jenniemc** [comment]
@ldelacosta , this is a backend issue but related to appt slot and NOT from the comment field. Please see slack thread from PPG engineering team https://vappgteam.slack.com/archives/C023EFZPX4K/p1687291294213029

**Comment by ldelacosta** [comment]
Changes have been validated. No issues to report. Closing out the ticket.
