### ISSUE TITLE
Urgent care subtypes

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#5713]
## What happened?
Only community care urgent care facilities (POS = 20) are returning when Facility type = "Urgent care" and Service type = "Community urgent care providers (in VA’s network)"

## Specs:
- Browser: Chrome

## Steps to Reproduce
- URL: https://staging.va.gov/find-locations

## Desired behavior
When Facility type = "Urgent care" and Service type = "Community urgent care providers (in VA’s network)":

- [ ] Results should include Community Care (In Network) locations (PPMS Place of Service 17 and 20), differentiated by labels on the cards

## Acceptance Criteria
- [ ] When Facility type = "Urgent care" and Service type = "Community urgent care providers (in VA’s network)", results should include only Community Care (In Network) locations (PPMS Place of Service 17 and 20)
- [ ] Result list contain a mix of POS=17 and POS= 20 locations (based on geography)
- [ ] Result list is sorted by proximity, closest location listed first 
- [ ] When POS code = 20 for a returned facility, the corresponding card displays Type of Facility: URGENT CARE
- [ ] When POS code = 17 for a returned facility, the corresponding card displays Type of Facility: RETAIL/WALK-IN CARE

All other functionality will be maintained 
 - [ ] When Facility type = "Urgent care" and Service type = "VA urgent care", results  include only VA urgent care facilities from Facilities API and card displays Type of Facility: URGENT CARE
 - [ ] When Facility type = "Community pharmacies (in VA’s network)", only community pharmacies should be returned and cards should display COMMUNITY PHARMACY (IN VA'S NETWORK)

**Comment by brangi** [comment]
The only thing front end needs is the POS code in the attributes when requesting cc_urgent_care. Do not change the type just  `pos= 20 | 17` and I can make the front end look for those
