### ISSUE TITLE
<Content Review> from <Benefits Team 1 Claim Status Tool>

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#57134]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more unauthenticated pages, online forms, apps, or tools on VA.gov
- [x] Making revisions to one or more existing VA.gov pages
- [ ] Something else 
 
 *Give a brief description of what your team needs support with.*

We are adding Board of Appeals notification letters to the Claim Letters page. As such, the current messaging below needs to be updated to reflect that the page includes letters to both claims _and_ decision reviews. 

<img width="678" alt="image (1)" src="https://user-images.githubusercontent.com/95102058/233194985-4d66cd92-876d-4bd7-9f52-ee15520fb39f.png">

We are looking to update the language of the following string: 

**Current** 
`"You can also get other letters related to your claims."`

**New**
`"You can also get other letters related to your claims and decision reviews."` (Or whatever the content team recommends).

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [ ] Yes
  - [x] No - Not a new product.
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
## When do you expect to launch your product to 100% of users?
  
*Please provide an estimated date so our team can create other relevant tickets.*
  
## Supporting artifacts
*Please provide supporting artifacts as available.*

- Link to product outline:
- Link to or attach user flows:
- Link to prototype or mockups:
- Link to any epics/issues that may be helpful:

## Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [x] No

## When does this work need to be done?
- Estimated launch date: Mid-April
- Estimated staging review date:
- Content, Accessibility, and IA work needed by: As soon as the team has a recommendation for this string.

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: Matt Self
-	Product manager: Jacob Worrell
-	Designer: Skyler Schain
-	FE engineer: Kevin Duensing
-	Product/team Slack channel: 

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by laurwill** [comment]
Hi @skylerschain,

Since the only type of decision review-related letter currently in the tool is decision letters for Board Appeals, we don't want to make this too broad and imply that letters about Supplemental Claims and Higher-Level Reviews are in here too.

**Suggested text:**
You can also get other letters related to your claims and Board Appeals.

**Notes:**
- We'll need to update this text again as other types of decision review letters become available. If you expect HLR and Supplemental Claim letters to be available very soon, we could consider making a more evergreen change now. 
- As we noted on slack, our team [previously recommended](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54874#issuecomment-1490850988) changing the header of this alert from "We closed your claim" to "We decided your claim," and it sounds like your recent research supports that change. So wanted to check on the status of that update. 

Let me know if you need anything more here or want to chat. Thank you!

**Comment by skylerschain** [comment]
Thank you very much! I don't believe we have near-term plans to include HLR and Supp Claims in the Claim Letters page. But we'll keep this ticket flagged for when we do include them, so we can adjust the language as needed. 

cc: @kjduensing @jacobworrell

**Comment by RLHecht** [comment]
Closing this ticket. Please reopen if you need more support.
