### ISSUE TITLE
AWS access for Mark Chae

### ISSUE THREAD

**Issue by mchae-nava** [department-of-veterans-affairs/va.gov-team#57168]
### COR Name

Delano McVay

### Vendor Onboarding Representative Name

Agile Six - Anthony M. Arashiro

### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Mark Chae

### Your Email

markchae@navapbc.com

### Team, Role, and Company of the target individual

Benefits Disability Experience Team, Nava PBC

### Product Manager (PM) name and email

Rakshinda Aslam rakshinda.aslam@agile6.com

### Product Owner (PO) name and email

Matt Self matthew.self2@va.gov

### Desired AWS Access

I need access to AWS SSM Parameter Store to store application secrets such as environment variables and for the benefits disability compensation Form 526 application.

[Ticket opened previously by a teammate](https://github.com/department-of-veterans-affairs/va.gov-team/issues/56501)

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

<img width="1108" alt="eQIP Transmittal notice" src="https://user-images.githubusercontent.com/129200156/233419744-42f996de-30cf-4623-9ec2-965c1c40768e.png">

### Additional Notes

'ongoing' because will need access until the migration work is complete, and potentially beyond

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by BillChapmanUSDS** [comment]
I approve this access,  Note that production access is still 3 Month Temporary.

**Comment by considerable** [comment]
initial password sent via Slack DM.
