### ISSUE TITLE
<Content Review> from <Benefits Disability Experience 526ez>

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#57175]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more unauthenticated pages, online forms, apps, or tools on VA.gov
- [x] Making revisions to one or more existing VA.gov pages
- [ ] Something else 
 
_Looking for feedback on content included in changes, as well as content to add to a PDF the service member will upload._

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [ ] Yes
  - [x] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
## When do you expect to launch your product to 100% of users?
  
End of May 2023
  
## Supporting artifacts
*Please provide supporting artifacts as available.*

- Link to product outline: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/README.md
- Link to or attach user flows:
- Link to prototype or mockups: https://www.sketch.com/s/23f30f99-cd9b-47c6-be44-e05a56f5d1b4
- Link to any epics/issues that may be helpful:
[Self Assessment Part A for BDD Flow](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/56579)
[Collaboration Cycle for [Benefits Disability Experience, Disability Comp Application](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/56612)

## Will this work be going through the Collaboration Cycle?
- [x] Yes 
- [ ] No

## When does this work need to be done?
- Estimated launch date: End of May' 2023
- Estimated staging review date: May 10th' 2023
- Content, Accessibility, and IA work needed by: April 27' 2023

## Do you plan to bring this to an upcoming content office hours session?
- [x] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [ ] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: Matt Self
-	Product manager: Rakshinda Aslam
-	Designer: Lydia Hooper
-	FE engineer: Christine Cereca
-	Product/team Slack channel: #benefits-ce-disability_exp_1

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by RakshindaAslam** [comment]
cc @lydiahooper @RakshindaAslam

**Comment by lydiahooper** [comment]
See content in areas highlighted in [Sketch file](https://www.sketch.com/s/23f30f99-cd9b-47c6-be44-e05a56f5d1b4) - much of this content repeats across screens.

In addition we propose the following language to be added to the PDF the service member will upload:

You can file a claim for disability benefits through the Benefits Delivery at Discharge (BDD) program by applying online online at www.va.gov. You will need to create an account, and then you will be able to save your work in progress. We will prefill parts of your application and you will be able to upload supporting documents with your claim, including this form. To submit this document after submitting your claim, visit My VA, find and review your claim, and submit file as a “Disability Benefits Questionaire.

**Comment by bethpottsVADEPO** [comment]
@lydiahooper I'm attaching a Word doc with edits for the content you highlighted on the form screens as well as the PDF language. Feel free to come to office hours today to go over it!
[https://app.zenhub.com/files/133843125/168e444f-0b39-41d1-af5c-1019a541973d/download](https://app.zenhub.com/files/133843125/168e444f-0b39-41d1-af5c-1019a541973d/download)

**Comment by bethpottsVADEPO** [comment]
@katherine-fung for awareness so we can align this with the content you're working on for the static page.

**Comment by lydiahooper** [comment]
Updated made to content during content office hours 4/27/23
