### ISSUE TITLE
DDL E2E Cypress tests: Unblock ticket #49849

### ISSUE THREAD

**Issue by samcoforma** [department-of-veterans-affairs/va.gov-team#57188]
## Issue Description
Investigate and fix failing test that's blocking PR for: https://github.com/department-of-veterans-affairs/va.gov-team/issues/49849

## Acceptance Criteria
- [ ] All Cypress tests are passing 
- [ ] This ticket is unblocked: https://github.com/department-of-veterans-affairs/va.gov-team/issues/49849

**Comment by jerekshoe** [comment]
I think it's safe to close this @samcoforma
