### ISSUE TITLE
Qualitative Data Request

### ISSUE THREAD

**Issue by APorter-Clarity** [department-of-veterans-affairs/va.gov-team#57181]
### Data Type Requested

Support

### Date Range Start

01-01-2023

### Date Range End

04-19-2023

### Product Name(s)

Identity 

### Product Description

The Identity team is responsible for all things login and the overall user experience as it relates to logging on to VA.gov. We work closely with credential service providers on Va.gov.

### Product URL(s) and/or term(s)

URLS:
[VA.gov Sign In Modal](https://www.va.gov/?next=loginModal)
[VA.gov Sign In Page](https://www.va.gov/sign-in/?oauth=false)

TERMS:
Login, login.gov, verify, sign in, MFA, 2FA, authentication, redirect, verification, proofing, USPS, Post Office, dslogon, MHV, MyhealtheVet, authenticate, identity, Va digital tools, account creation, account

### File Delivery Format

One file, different tab for each term/URL

### VA Email Address(es)

AMANDA.PORTER@va.gov, clayton.zook@va.gov, charlye.tran@va.gov

### Add Assignee and Labels

If not already done so, please ensure @ianMcCullough-ob is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by ianMcCullough-ob** [comment]
@APorter-Clarity Just shared a folder with you. I split the exports into 2 files to make it more manageable, one has all the terms and the other has the URLs.

Feel free to reach out via slack if you have any questions.
