### ISSUE TITLE
[Design] My VA Bene app drafts: Decide about "What benefits does VA offer" dropdown on My VA

### ISSUE THREAD

**Issue by fmccaf1** [department-of-veterans-affairs/va.gov-team#57184]
### Background

The recent [My VA Audit UAT](https://github.com/department-of-veterans-affairs/va.gov-team/issues/55789#workspaces/vft-59c95ae5fda7577a9b3184f8/board?assignees=fmccaf1) uncovered the following finding: Participants were not consistently clear on the purpose of he new section called "Benefit application drafts." Only 3 out of the 6 participants understood the meaning of the section. Some of this confusion was influenced by the dropdown in that section called, "What benefits does VA offer?", which seemed to mislead participants about what the section's purpose was. 

Moving forward with this finding, we need to do some work to understand if and how we need to change the design of this section. 

### Important Links
[UAT findings summary](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/UAT/findings-summary.md)

### Tasks

- [x] Explore analytics for the "What benefits does VA offer" dropdown. We've heard that the dropdown may get a lot of clicks, but if there are no clicks within the dropdown (the items listed there), then it is unlikely the dropdown is actually helping our users access benefits
- [x] Make decision with team about removing the dropdown or moving it elsewhere on My VA

**Comment by aagosto90** [comment]
Hi @ajakabcin ! I went over some design concepts for this with the team on Thursday 7/27. One important thing I realized in working on this ticket is that analytics aren't set up for the links within the additional info menu for "What benefits does VA offer?" So we know that dropdown gets a lot of clicks but we don't know how often people are clicking the links in the dropdown. I met with Michelle Dooley during analytics office hours on 7/26 to confirm this. Samara would like us to set up analytics for those individual links before we decide how to move forward and revisit this in a month or two when we have some data to work with. Therefore, please create a ticket for yourself for that when you're back and I'll close this one out. Thank you!

![Screenshot 2023-07-28 at 10.25.31 AM.png](https://images.zenhubusercontent.com/61f2dbbca50e2e3e2b4d0a11/4db96495-1a92-45d3-9397-379a06b51fa1)
