### ISSUE TITLE
[Design] Happy path VBMS workflow

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#57193]
## Background

In support of the following sprint goal: 

- Document happy path VBMS workflow that maps to Lighthouse data schema and FE UI states. 

## Assumption

- Documenting the happy path first allows us to build out branches that support our feature work more effectively later. 
- We will have to iteratively work on these workflows/visuals to support future feature releases
- We'll need to have a meeting of the minds across team disciplines to establish baseline
- We'll want to validate the output with Karla and refine as necessary
- Will require 1-2 hours of additional support from engineers and product 

## Goals
- Create product documentation that allows us to assess the feasibility of different solutions approaches from a design and engineering perspective. 
- Create deeper shared understanding of VA business process
- Empower team to facilitate valuable and focused discussions with Karla

## Acceptance Criteria

- [x] Happy path as defined as a disability claim with four contentions moving through the VBMS business process is visually represented
- [x] Connections to Lighthouse data attributes are visually represented
- [x] Connections to happy path UI states are visually represented and/or referenced

**Comment by skylerschain** [comment]
[Workflows](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/product-guide/product-documentation/claims-workflow-maps.md) in Github.

**Comment by rubensun** [comment]
Documentation in [sharepoint](https://dvagov.sharepoint.com/:x:/r/sites/vaabdvro/Shared%20Documents/Benefits%20Management/VBMS-CST-Value-Map.xlsx?d=wb3df268e25d344c09350a85c6675ad48&csf=1&web=1&e=uSJzQd)
