### ISSUE TITLE
Analytics Implementation or QA Support for Request a Board Appeal

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#57206]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

</div>
</details>

### Required
- **Is this request for **Google Analytics implementation** or **QA**?**

     - [x] Google Analytics implementation
     - [ ] QA

- **Who is this request for?**

    - Benefits-ce-decision_reviews aka Benefits-team-1
    
- **Provide the link(s) for Google Analytics implementation or QA**
  
    - https://staging.va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182/board-review-option
    - https://staging.va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182/evidence-submission
    - https://staging.va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182/hearing-type
    
- **When is the launch date?**
    - Already launched in April 27, 2022

- **What interactions need to be tracked?** 
   - Radio Button - {{DL - radio-button-label}} - {{DL - radio-button-option-click-label}}

### Optional
- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - Any test user should work, if not user-236

- **Any additional comments**

    - The Google event is triggering when we check the page with Adswerve, but we can't track it in Google Analytics.
<details> 
<summary> Screenshot </summary>

![screenshot_2023-04-20_at_11 36 31_am](https://user-images.githubusercontent.com/111457818/233479586-6f8c54c2-78bc-4690-960e-dcbdfc9376d9.png)

</details>

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by michelle-dooley** [comment]
@eileen-coforma - thanks for you submission.  We will review and get back to you with ETA, most likely mid-May.

**Comment by michelle-dooley** [comment]
@eileen-coforma - To see those radio button events in GA you need to use the 'event':  'int-radio-button-option-click'

Here is the data layer code to use:
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/93597659/63508e18-a4e1-4904-b4fe-7c932b181ed3)

After you implement the code let me know and I will test.

**Comment by michelle-dooley** [comment]
@eileen-coforma - just checking on the status of this update above, let me know when you are ready for me to test.

**Comment by eileen-coforma** [comment]
@michelle-dooley Thank you for following up on this, we haven't added these yet. Will update when we do.

**Comment by michelle-dooley** [comment]
@eileen-coforma - I'm going to move to our backlog, just let me know when you ready to test.

**Comment by eileen-coforma** [comment]
@michelle-dooley the code has been added
