### ISSUE TITLE
[a11y Documentation] a11y Onboarding Materials

### ISSUE THREAD

**Issue by sara-amanda** [department-of-veterans-affairs/va.gov-team#57208]
## Description
**The questions below help our team to determine the project scope for incoming documentation support requests.**

**1. What do you need help with? Check one:**
- [x] Creating new documentation
- [ ] Updating previously published documentation
- [ ] Reviewing recently written, never-before-published drafts

**2. Who are the primary users of your documentation? Check all that apply:**
- [ ] Developers
- [ ] Designers and researchers
- [ ] Product managers
- [x] Other: a11y specialists

**3. Estimate the number of pages to be created, updated, or reviewed?** 
TBD - location of documentation unknown at this time, due to ongoing accessibility documentation cleanup efforts.

**4. Do the documents contain graphics such as screenshots, code snippets, diagrams, or videos?**
- [ ] Yes, and describe ____________________
- [x] No

**5. Who is the point of contact for this documentation?** @sara-amanda, @artsymartha68 and all other a11y specialists, as this is a collaborative effort.

**6. Are there other documents, tickets, or artifacts that will be impacted by this update?**
- [x] Yes, and describe [CAIA Accessibility Documentation Epic #55956](https://app.zenhub.com/workspaces/sitewide-content-accessibility-and-ia-63a1d63232beba0011a7833f/issues/gh/department-of-veterans-affairs/va.gov-team/55956)
- [ ] No

**7. Are there plans to update other documents/pages that have similar content?**
- [ ] Yes
- [x] No - non exist to my knowledge at this time.

#### Relevant URLs: 

- [Slack: ally-specialists (private group)](https://dsva.slack.com/archives/C0335Q88X0S)
- [Google Doc for a11y Onboarding Documentation Efforts
](https://docs.google.com/document/d/1iz13YaY0xs2CYVxTKVKyBkpM1fCigTFuI53tcU36k_U/edit?usp=sharing
)

## ally Onboarding Documentation Efforts
- **View Mode**: [Google Doc for a11y Onboarding Documentation Efforts
](https://docs.google.com/document/d/1iz13YaY0xs2CYVxTKVKyBkpM1fCigTFuI53tcU36k_U/edit?usp=sharing
) 
- **Editing**: The edit link can be found in the **VA A11y Specialist Weekly Sync** meetings agenda.
- **Goal**: Collaborative team effort to provide an onboarding resource to new a11y team members. 
- **Team Effort**: All a11y specialists are invited to work on this document to help refine it and make it the best onboarding doc it can be. Discussions to take place in the **VA A11y Specialist Weekly Sync** meetings.
- Confluence training 7/25/2023 (Sara)

- **Dependency Note:** Due to the ongoing documentation work, a final home for this document is unknown at this time and will be dependent on the final decision for a11y documentation.

**Comment by sara-amanda** [comment]
## Evolution of this Ticket
@eli-oat - 

- Could we tie your [new a11y notification inquiry](https://oddball.slack.com/archives/C05LB36ATAQ/p1707149869749089) from yesterday in Slack to this ticket, to track work if you think it is applicable? Thoughts on this or something else? 
- [Here is a report that will show new hires with accessibility roles](https://lookerstudio.google.com/reporting/763af3fa-a87b-47c5-8351-b644ebea63fc). 
- [Adding to Hive mind agenda too](https://docs.google.com/document/d/1HEWt71tCuUQp1v7xWF5gVQpxxMFw40tbI144P8lbIqg/edit#heading=h.6uqy41ca5ap7), since this could be something that the other disciplines would like to approach for awareness of new roles? 

cc: @coforma-terry

**Comment by coforma-jamie** [comment]
@artsymartha68, @briandeconinck, @sara-amanda: I've been working on an onboarding doc specifically for accessibility specialists (and folks who spend more than half their time doing accessibility work, but have other titles). Ideally, this doc would be sent to new a11ys as they onboard, before they even get access to DSVA Slack.

Can you take a look at the [draft](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/CAIA/accessibility/DRAFT-a11y-specialist-onboarding.md) (in progress) and let me know your thoughts? Is anything missing, should something be removed? What are your thoughts about getting this to the folks who need it?

THank you!

**Comment by sara-amanda** [comment]
## Draft Review 
> @artsymartha68, @briandeconinck, @sara-amanda: I've been working on an onboarding doc specifically for accessibility specialists (and folks who spend more than half their time doing accessibility work, but have other titles). Ideally, this doc would be sent to new a11ys as they onboard, before they even get access to DSVA Slack.
> 
> Can you take a look at the [draft](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/CAIA/accessibility/DRAFT-a11y-specialist-onboarding.md) (in progress) and let me know your thoughts? Is anything missing, should something be removed? What are your thoughts about getting this to the folks who need it?
> 
> Thank you!


### Feedback

- [x] Feedback recommendations sent to @coforma-jamie via Slack on 5/23/2024 

<details><summary>Toggle to view feedback detail</summary>

#### Initial Feedback
- [CAIA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/CAIA/accessibility/DRAFT-a11y-specialist-onboarding.md#support-the-caia-team) - you can link to our [menu of services](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/CAIA/accessibility/README.md#services-we-offer) in this section to familiarize the newbie with all things CAIA can do.
- [Product Team](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/CAIA/accessibility/DRAFT-a11y-specialist-onboarding.md#embedded-on-a-product-team) - you could link to the [VA Mural Universe here](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1712621865931/3fea15c7e9e02e067a628b1384dac54f4006bbdb?sender=4f2c6785-c714-464d-b50c-6a21c124c574) and reference the [TOT channel](https://dsva.slack.com/archives/C031S5G29LP), where you can stay up-to-date on all things going on with the teams at VA.  You can also link to the [product directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory).
- [Governance Team](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/CAIA/accessibility/DRAFT-a11y-specialist-onboarding.md#support-the-governance-team) - you could link to the video training orientation for accessibility and link to the slides - I found them in the a11y-specialists channel but they may live on Drive or Confluence too. Do we want to link to the [defect severity rubric](https://depo-platform-documentation.scrollhelp.site/developer-docs/accessibility-defect-severity-rubric) in this section?
- [Community of Practice](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/CAIA/accessibility/DRAFT-a11y-specialist-onboarding.md#join-the-accessibility-community-of-practice-cop) - I recall there being a mention of a book club, but that may be AdHoc specific. If not, we could create a list of recommended books in GH and link to it? It could also be linked in the "improve your skills" section you have in here, too.
- [Meetings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/CAIA/accessibility/DRAFT-a11y-specialist-onboarding.md#meetings) - CAIA Office Hours Support Option: I would plug the CAIA office hours here and link to our workflow and/or link to our [Canvas](https://dsva.slack.com/docs/T03FECE8V/F06JTSH7CHZ). This way CAIA or non-CAIA members will know that is also an option for accessibility help, beyond the ones listed. Weekly design, research, content, IA and accessibility sync I think is another one you could plug in this section, since it includes accessibility and is great for team awareness/projects/decisions, etc. to join the user would follow instructions in this [Canvas](https://dsva.slack.com/docs/T03FECE8V/F04UVAB75SS).
- [Slack](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/CAIA/accessibility/DRAFT-a11y-specialist-onboarding.md#slack-channels) - we could make mention of the handles made for CAIA in this section. Users can tag us in any channel and it will notify us. If they are joining the CAIA team, we will need to make sure they get added to this. Kevin made them, so I assume he is who we would ask? Terry may know. @sitewide-caia-accessibility
- Slack Profile - I believe it was indicated that we need to have our Slack profiles reflect the teams we work on and our shared calendar. They also should include a professional(ish) photo. I would recommend we add this in the onboarding doc, in the Slack section. Platform [requires](https://dsva.slack.com/archives/C02RLAUM2LV/p1714401648876179?thread_ts=1714398455.921549&cid=C02RLAUM2LV) it before they will assist you with a ticket. [Here is a link to the Platform tools > Slack Profile page we can point them to](https://depo-platform-documentation.scrollhelp.site/getting-started/slack-profile).
- Digital Services Coalition - do we want to have this on there too? Digital Services Coalition on Slack. You will need to be initially added to the Slack group, and then you can join channels. [Sign in to DS Coalition Slack](https://dscoalition.slack.com/)
- [Figma](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/CAIA/accessibility/DRAFT-a11y-specialist-onboarding.md#figma) - you can link directly to the Figma Plugins for [accessibility](https://www.figma.com/community/tag/accessibility/plugins/free) or [a11y](https://www.figma.com/community/tag/a11y/plugins/free), instead of the research GH doc. (The two links here are filtered on free.)
- Trauma - you could also under improve your skills include a section on trauma and mention the meetings and [this doc. for designing](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/CAIA/accessibility/traumatic-brain-injury-guide.md).
- Slides: You mentioned you were working on making a few presentations on Confluence accessible, are any of those beneficial for onboarding (or the accessibility page on the Platform site)?
- [Tricky Accessibility Issues](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/CAIA/accessibility/DRAFT-a11y-specialist-onboarding.md#tricky-accessibility-issues) - should your [focus tracking](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/CAIA/accessibility/focus-tracking.md) markdown be part of the cookbook? Looks like it links out on its own. That might be a good addition!
- [Research](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/CAIA/accessibility/DRAFT-a11y-specialist-onboarding.md#any-other-resources): We could plug the [pilot guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/CAIA/accessibility/assistive-tech-pilot-guide.md) in here too, perhaps under the "any other resources??" section?
- a11y Pages - I would also list in this section the accessibility page on platform, and the [accessibility page](https://depo-platform-documentation.scrollhelp.site/developer-docs/accessibility-on-va-gov) on the [design system site](https://design.va.gov/about/accessibility/), in the event they don't navigate to the sections elsewhere on this page, it could live in the resources. Both are a great tool for newbies. You could create a section called "navigating accessibility at VA" and these two pages could live under that header? Just a thought.
### Links:
- [Access the Collaboration Cycle Schedule](https://calendar.google.com/calendar/u/0/embed?src=c_7iurst2mk3hdhfuto5u7lemgbk@group.calendar.google.com&ctz=America/New_York)
- [OPT OUT (in each browser) of website analytics](https://www.va.gov/analytics-opt-out.html)
- [A11y Specialists by Contract: on VA a11y Dashboard in Google Sheets](https://docs.google.com/spreadsheets/d/1lgzMiZZ-0rBPDuB2gRupBAjsyF0WTe005VvEHYrMxww/edit#gid=505503390) (may need a call for updates, perhaps from Martha?)
- [A11y Bookmarklets](https://www.digitala11y.com/accessibility-bookmarklets-testing/)
- [18F Checklist](https://accessibility.18f.gov/checklist/)
- [18F Tools](https://accessibility.18f.gov/tools/)
- [USWDS](https://designsystem.digital.gov/)
- [Mock form](https://staging.va.gov/mock-form-patterns/introduction)

</details>

**Comment by coforma-jamie** [comment]
Wow, thank you @sara-amanda! I added a bunch of stuff based on your feedback. There are a few things I purposely _didn't_ add that I want to call out:
- Book club is Ad Hoc-specific and might not even be around accessibility as much as design topics in general.
- DS Coalition doesn't apply to OCTO staff (and this is intended for _anyone_ who's an a11y at VA, not just contractors)
- Trauma info is already on the a11y landing page, which is linked in multiple places
- A11y specialists by contract is too out of date
- Collab cycle schedule, bookmarkets, 18F stuff, USWDS, was just too much. It's pretty long and I don't want to give folks even MORE stuff to look at :)

**Comment by artsymartha68** [comment]
Truly, the amount of resources we have is staggering! Thanks for pulling this all together like this!

I agree with the premise to not list everything under the sun. That would be too too much.

**Comment by sara-amanda** [comment]
## Edits: Onboarding Guide
### Onboarding Guide: Accessibility Specialist for VA.gov
**Updates from 5/31/2024 include and are not limited to:** consolidation, toggles to condense long scroll, heading overview in each section, tips, meeting table, and more. 
- [Round 1](https://github.com/department-of-veterans-affairs/va.gov-team/commit/efaed3e511ccc1b1b68550342a26114bfb8cbaec?diff=unified&w=0) 
- [Round 2](https://github.com/department-of-veterans-affairs/va.gov-team/commit/7f8f868b34a4c96faf81deeb20d6ec789b94261d) 
- [Round 3](https://github.com/department-of-veterans-affairs/va.gov-team/commit/ee6eb7b455e3c244fc6aeaed461a315e60970b6c) 

*I can add some of the smaller items and resource links to the onboarding canvas template I am updating @artsymartha68 @coforma-jamie 

cc: @coforma-terry

**Comment by coforma-jamie** [comment]
Now that @sara-amanda and I have compiled this documentation, what are our next steps, @artsymartha68?

**Comment by artsymartha68** [comment]
Riley is starting soon, I think next week! Great opportunity for a new a11y specialist to try out these materials and see how they work.

**Comment by coforma-jamie** [comment]
That's a good idea :) How is this new page going to get to her? I assume it's not in the standard onboarding ticket yet.

**Comment by artsymartha68** [comment]
Hmmmm. Let's go ahead and add it to the standard ticket?

**Comment by coforma-jamie** [comment]
Who would I contact to do that? :)

**Comment by coforma-jamie** [comment]
**Update:** 
- @artsymartha68 reviewed the documentation and approved it
- I added it to the top of the 🔒a11y-specialists channel Canvas
- We'll make sure the next new specialist (who's joining very soon!) gets to look at it, and will ask for her feedback
