### ISSUE TITLE
Fix broken link on Tagalog COVID vaccines page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#57221]
## Issue Description

SiteImprove flagged a broken linked on our [Tagalog COVID vaccines page](https://www.va.gov/health-care/covid-19-vaccine-tag/). The link is for the Pfizer fact sheet in this accordion:

 ![Screen Shot 2023-04-21 at 8.49.22 AM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/9acefe5a-6dde-4d12-abc1-f29dd2b76c6a)

This is the new fact sheet: https://www.fda.gov/media/167282/download

## Tasks
- [x] Fix broken link (Aliyah)
- [x] Review (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] Link working on live site

**Comment by aliyahblackmore** [comment]
This is ready for you @megzehn! 
**Preview link**: http://preview-prod.vfs.va.gov/preview?nodeId=16413

**Comment by megzehn** [comment]
Thanks, @aliyahblackmore! I reviewed and published the page. 

This is ready for validation, @RLHecht!
