### ISSUE TITLE
Board Appeal (NoD) Qualitative Data Request

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#57228]
### Data Type Requested

Support

### Date Range Start

04-27-2022

### Date Range End

04-20-2022

### Product Name(s)

Request for Board Appeal (NoD)

### Product Description

We are looking for MyVA411 data about Board of Appeal (also known as Notice of Disagreement), including the authenticated form. 

The DOMO dashboard only has Contact Center issues for Claim Status and Disability Claim Application, but nothing for decision review forms.

What is required to get this into a dashboard, or exported for our review.

Thank you!

### Product URL(s) and/or term(s)

URL: Everything under https://staging.va.gov/decision-reviews/board-appeal/ and https://staging.va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182/ 
Terms: Appeal, Board Appeal, Request a Board Appeal, Notice of Disagreement, VA Form 10182

### File Delivery Format

One file, different tab for each term/URL

### VA Email Address(es)

eileen.chi@va.gov, gary.homidas@va.gov, eva.floyd@va.gov

### Add Assignee and Labels

If not already done so, please ensure @ianMcCullough-ob is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by ianMcCullough-ob** [comment]
@eileen-coforma just shared a file with the above addresses. It has 3 tabs, each a different term.

Feel free to reach out through Slack if you have any questions on the exports. We can discuss a dashboard after the closure of this ticket.

**Comment by ianMcCullough-ob** [comment]
@eileen-coforma do you need anything else on this, or can we close the ticket?

**Comment by eileen-coforma** [comment]
@ianMcCullough-ob We are good on this. Thank you very much!
