### ISSUE TITLE
[CONSIDER] VAMC Accessibility Issues

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#5723]
## High Level User Story/ies
As an assistive device users, I need VAMC webpages content to be accessible to me so that I can get the information I need. 

## Hypothesis or Bet
**If** we address 508 and accessibility issues **then** all Veterans will have the same access to information about VAMC locations.

**Comment by mmiddaugh** [comment]
@davidconlon @1Copenut I created this epic to collect the various accessibility issues that have been found with Pittsburgh pages. FYI

**Comment by 1Copenut** [comment]
@mmiddaugh && @davidconlon I'll move all of my current findings and any additional ones into this Epic in a short. Thank you!
