### ISSUE TITLE
Json Error logs

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#57241]
Json error [logs](https://vagov.ddog-gov.com/logs?query=env%3Aeks-prod%20-service%3Aclamav%20as_json%20&cols=host%2Cservice&index=%2A&messageDisplay=inline&spanID=2291370126022430602&stream_sort=time%2Casc&viz=stream&from_ts=1681589789000&to_ts=1682021789000&live=true)

**Comment by LindseySaari** [comment]
This is now also isolated to the [mobile-health-endpoints pod](https://vagov.ddog-gov.com/logs?query=env%3Aeks-prod%20-service%3Aclamav%20as_json%20&cols=host%2Cservice&event=AgAAAYeksLPiR-vq0gAAAAAAAAAYAAAAAEFZZWtzTFE1QUFCNGhsYWtsVVRyTGdCVwAAACQAAAAAMDE4N2E0YjUtMGZiNC00Yzg1LTgwNjktMTk2NDQxNTAzN2M1&index=%2A&messageDisplay=inline&spanID=2291370126022430602&stream_sort=time%2Casc&viz=stream&from_ts=1682095252663&to_ts=1682096152663&live=true), so most likely related to the semantic logger issue.

[See comment on ticket](https://app.zenhub.com/workspaces/platform-tech-team-1-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/57031)

**Comment by RachalCassity** [comment]
This error is the same as the Semantic Logging

**Comment by RachalCassity** [comment]
I linked this issue in the Semantic Logging ticket.
