### ISSUE TITLE
RX Parser Debug Logs

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#57240]
RX Parser Debug [Logs](https://vagov.ddog-gov.com/logs?query=env%3Aeks-staging%20-service%3Aclamav%20as_json%20&cols=host%2Cservice&index=%2A&messageDisplay=inline&spanID=2291370126022430602&stream_sort=time%2Casc&viz=stream&from_ts=1681589789000&to_ts=1682021789000&live=true)

**Comment by LindseySaari** [comment]
[Checked with the mobile team](https://dsva.slack.com/archives/C018V2JCWRJ/p1682096876104939) and this is a known issue. They will be cleaning up these debugging statements
