### ISSUE TITLE
GIDS: Add Match % to auto-match table display.

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#5726]
As an EDU Team Member, I need the percent match displayed so I have an indicator that which is the most likely data that matches the current institution.

## Assumptions:
1. It is possible to display the percentage; if it is not possible, the reason is documented.
2. This story covers the research and implementation (if possible)

## Acceptance Criteria
1. A column displaying the % match is displayed as the first column in the potential matches table.
2. The table is sorted descending by % match.

**Comment by hughes-dustin** [comment]
branch: bah-5726
PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/573

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-02-12 at 8.30.26 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/4ccd9feb-ee47-4605-af5e-20a763d57935)

**Comment by sonntag-adam** [comment]
Test case passes
https://dsvavsp.testrail.io/index.php?/runs/view/174&group_by=cases:section_id&group_order=asc

**Comment by sonntag-adam** [comment]
In staging, closing story. Testing passes QA.
