### ISSUE TITLE
Errors due to missing permissions

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#57277]
### PROBLEM STATEMENT
Errors due to missing permissions when writing application keys or authorizing applications are displaying a `403 Forbidden` error. More info about various error responses can be found in the DD API documentation.

This is causing our HPA scaling to fail in Datadog because it can't call out to get the HPA metric. 

### EFFORTS TO FIX
Rotating all APP and API Keys. Keys are currently tied to a user and a developer that just left had the keys tied to their user.

### RESOLUTION
- [x] Rotate all App and API keys
- [x] Create an alert to detect this error in the future (Ryan)
- [x] Work with DOTS on a svc account to avoid attaching keys to a specific user

**Comment by laineymajor** [comment]
@LindseySaari to tag @rjohnson2011 in appropriate thread

**Comment by laineymajor** [comment]
Per rachal... Alerts needs to be refactored. @rjohnson2011 is working on this. Likely carryover to next sprint.

**Comment by RachalCassity** [comment]
This needs to be apart of an epic. This has been an issue for sidekiq enterprise as well. Keys and tokens have been tied to a certain va dev. When that person leaves, the keys and tokens expire. There needs to be a "super user" for all these permissions. We need to make a list where we need a "super user".

**Comment by laineymajor** [comment]
Will schedule a little time to review with Rebecca... + Lainey's socks access :(

**Comment by LindseySaari** [comment]
[Kyle reached out to the DOTS team](https://dsva.slack.com/archives/C01U8EYHSEM/p1682425164121659) and was able to create a service account owned API key (not attached to a specific user).

**Comment by laineymajor** [comment]
We need to create a 'super user' for these permissions. We currently have this for Sidekiq (devops distribution email).

@rjohnson2011 circle back with Kyle re thread linked above by Lindsey... is the solution currently in place?

**Comment by rjohnson2011** [comment]
In the process of creating a DataDog alert for the following logs:
```
unable to get external metric vets-api/datadogmetric@vets-api:puma-backlog-vets-api-web/nil: unable to fetch metrics from external metrics API: Internal error occurred: DatadogMetric is invalid, err: Global error (all queries) from backend
```

**Comment by rjohnson2011** [comment]
Looked for the following logs and DataDog and the results were zero. This appears to be a case where the entirety of the message is stored on the message attribute and not parsed out into the attributes hash.
See related Slack thread: https://oddball.slack.com/archives/C045LCF8WU8/p1683222949391909?thread_ts=1682347275.278689&cid=C045LCF8WU8

**Comment by rjohnson2011** [comment]
Successful service account API has been created https://dsva.slack.com/archives/C01U8EYHSEM/p1682534499966769?thread_ts=1682425164.121659&cid=C01U8EYHSEM
