### ISSUE TITLE
HPA Failing in Prod

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#57274]
### PROBLEM STATEMENT
HPA is failing in prod because some API keys have expired. 

### EFFORTS TO FIX
- [x] Bumping the min to avoid latency issues in the meantime
- [x] Create all new keys because (we believe) the keys were attached to Oseas' user and his perms were revoked

### RESOLUTION

**Comment by laineymajor** [comment]
Currently all hands to fix this issue. Potential carryover to next sprint.

**Comment by LindseySaari** [comment]
We may want to create another ticket for adjusting threads/workers and the logic for the hpa metric cc @laineymajor
