### ISSUE TITLE
Request: Analytics Intro + KPI workshop for Structured Data Team

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#5728]
- [ ]  PM and Front-End Engineers: Request analytics intro @joanneesteban @nedierecel
- [ ]  Full team: Request KPI workshop with analytics team @joanneesteban @nedierecel

**Comment by joanneesteban** [comment]
Thanks for the request, @srmyers17! 

For the Analytics Intro, can you send over some 30 minute slots for the next couple weeks?

For the KPI Setting workshop, that will be a 1.5 hour workshop. [Here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/kpi-setting-pre-workshop-template.md) is the pre-workshop template - please copy it into your team's product folder, and fill it out with your team and we can schedule that workshop when you're good to go!

**Comment by srmyers17** [comment]
Analytics intro: Team is free Weds @ 2:30 PM and Thurs @ 3:30 PM over the next couple of weeks

+ I'll look at the KPI info and get back to you soon!

**Comment by joanneesteban** [comment]
@srmyers17 

Does 2:30-3pm ET on Wednesday, 2/19/20 still work for you and your team? If you send us over your team's emails on Slack, we can get them added to an invite.

Thanks!

**Comment by srmyers17** [comment]
Yes! That time does still work @joanneesteban 

Here are our emails:

keith adkins <keith.adkins@adhocteam.us>
Ben Shyong <ben.shyong@adhocteam.us>
Jonathan Julian <jonathan@adhocteam.us>
Sophia Myers <sophia.myers@adhocteam.us>

**Comment by joanneesteban** [comment]
@srmyers17 

Thank you for meeting with us yesterday! 

Here's the "opt-out" VA.gov [link](https://www.va.gov/analytics-opt-out.html) with [background information](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/opting-out-google-analytics.md).

And the Google Analytics walkthrough [video](https://drive.google.com/file/d/1UdD1IAtdO_ODsTfIz-L7er9a8BXqNdT3/view).

**Comment by joanneesteban** [comment]
HI Sophie! Are you still looking for a KPI workshop with us?

**Comment by joanneesteban** [comment]
@srmyers17 Iceboxing this issue. Please feel free to reach out to us if you're looking for a KPI setting workshop!

**Comment by jonwehausen** [comment]
Removing myself as an assignee...already iceboxed.
