### ISSUE TITLE
Platform website documentation re deployment process

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#57284]
### AC
- [x] Documentation updated on platform website
- [x] Link HERE to where the documentation lives

**Comment by LindseySaari** [comment]
Documentation surrounding the Vets API deployment process [can be found in this doc](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-VetsAPIEKSDeployProcess)

**Comment by LindseySaari** [comment]
The deployment process docs look good, but I updated the [Bulkhead details](https://vfs.atlassian.net/wiki/spaces/pilot/pages/2452193284/Vets+API+on+EKS#Bulkhead-Deployment-Pattern) to reflect the current state.
