### ISSUE TITLE
<Content: Phone number> from <Benefits Disability Experience 526ez>

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#57297]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more unauthenticated pages, online forms, apps, or tools on VA.gov
- [x] Making revisions to one or more existing VA.gov pages
- [ ] Something else 
 
 *Give a brief description of what your team needs support with.*
The 526ez and ancillary paper forms get updated when necessary. This ticket is part of work required to get the digital 526ez form on va.gov in sync with the paper version.

This ticket includes content and design work needed for engineering to make changes that do not require user research first, to make phone number field on contact information optional and add info about where to change phone number on page about exams.

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [ ] Yes
  - [x] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
## When do you expect to launch your product to 100% of users?
  
*Please provide an estimated date so our team can create other relevant tickets.*
As soon as possible
  
## Supporting artifacts
*Please provide supporting artifacts as available.*

- Link to product outline: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/README.md
- Link to or attach user flows:
- Link to prototype or mockups: https://sketch.com/s/ae7a7a94-9e48-4cbd-bc99-006754ad2ddb
- Link to any epics/issues that may be helpful: [Design changes for phone number optional](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/57239)
- [Sync 526ez and ancillary forms with the current paper form version](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/55513)

## Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [x] No

## When does this work need to be done?
- Estimated launch date: When ready
- Estimated staging review date: Not planned
- Content, Accessibility, and IA work needed by: As soon as possible

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: Matt Self
-	Product manager: Rakshinda Aslam
-	Designer: Lydia Hooper
-	FE engineer: Cristine Cereca
-	Product/team Slack channel: https://dsva.slack.com/archives/C04KW0B46N5

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by RakshindaAslam** [comment]
cc @lydiahooper

**Comment by lydiahooper** [comment]
@katherine-fung vets who live overseas cannot enter a phone number in 526 bc the field requirements are set to US standards. I'm not sure how they go about exams, but we want to give them some guidance since they can't just wait for a call like other vets.

**Comment by katherine-fung** [comment]
Ok noted. And if someone lives in the U.S., will VA schedule a claim exam by calling the phone number they enter in the online 526 form? Or will VA schedule an exam by calling the the phone number in their VA profile, if it's different? In the alert about claim exams, we give people a link to change their phone number in their profile.

**Comment by lydiahooper** [comment]
Yes, we are adding that language in the alert since we're making the phone number field in 526 optional, we want to make sure there is a phone number on file so VA can call the vet about exam. As a reminder/for clarification, there's really just the two sentences for content review, please don't review content on the entire page.

**Comment by katherine-fung** [comment]
Thanks, @lydiahooper. I've provided the 2 sentences with edits. 

Is there a place where you're tracking other changes that we'll need to make but aren't in scope for this ticket? 

Here are the 2 sentences. To align with VA.gov style, I removed the bolding and separated the links from the running copy. If we want to highlight the first sentence without bolding, I'd recommend putting it on its own line/doing a hard return. 

**In the "You might receive a phone call from an unfamiliar number to schedule your exam" alert**

You can go to your VA.gov profile to confirm your phone number. 

[LINK] Go to your VA.gov profile (URL: https://www.va.gov/profile) 

**In the "What happens if I miss a phone call?" accordion**

If you’re a Veteran who lives overseas, you may contact an Overseas Military Services Coordinator for help scheduling a claim exam. 

[LINK] Contact an Overseas Military Services Coordinator (URL: https://www.benefits.va.gov/benefits/oms_Coordinators.asp)

**Comment by lydiahooper** [comment]
Thanks @katherine-fung . To clarify, there are no other changes we're planning to make right now.

**Comment by katherine-fung** [comment]
Ok! There's a typo in the Sketch file, and a few other things I'd flag for accessibility though - I don't know if those are in the tool itself already, or planning to be implemented, or if the copy in Sketch was just for illustration purposes.
