### ISSUE TITLE
Remove upcoming and past links

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#57292]
## Tasks

[Comment from CAIA](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/bgwvQKZ?annotation=778721ff-e65c-4b05-92a1-fe127dc610d7). 

- [x] Remove upcoming and past links from all pages in Sketch
- [x] Remove upcoming and past links from all pages in CodePen

## AC

Upcoming and past links are removed from Sketch and CodePen

**Comment by cgednalske** [comment]
This is complete in CodePen because they were conveniently never there 😄

**Comment by cgednalske** [comment]
@zach-park in order to make some other structural changes to headings, I had to go ahead and delete the Upcoming/Past links in Sketch too. So both tasks are done ✅  

Would love to sync with you on spacing next to make sure what I've done is in line with our usual approach.

**Comment by zach-park** [comment]
@cgednalske, thank you!

**Comment by cgednalske** [comment]
@zach-park or @benbrasso-agile6 forgot to officially ask if one of you could validate this? 😃

**Comment by zach-park** [comment]
@cgednalske, LGTM. But I found other artboards (unrelated to the ticket) with spacing issues. So I'll take care of them today. :)

**Comment by benbrasso-agile6** [comment]
I'm going to push this back to in progress. Looks like it's still being worked on.
