### ISSUE TITLE
Spike: What infra to use for Identity Dashboards

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#57311]
###Description of Spike

**In order to** GOAL,
We want to determine what repo setup we want to have for the three dashboards we are going to setup (configs, fwa, documentation). We also need to determine how the apps will be deployed within the current platform infrastructure. 

**we need to** ACTION,
We need to document what approach we will take to organize our micro services for both frontend and backend. We also need to document how this impacts the ability to "re-use" authentication app setup.

**so that** VALUE.
Before we get too far down the path of adding code to certain repos and setting dependencies, we should discuss and document the most ideal path. This will reduce as much time as possible from erroneous setup work.

#### Acceptance Criteria
- [ ] Documentation has been updated
- [ ] Next steps have been determined and documented

#### Timebox
- 1 week

#### MR Approver
- TBD

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by asg5704** [comment]
Just closing. IDD dead
