### ISSUE TITLE
Fix typo on VA.gov homepage: Borne, not Born

### ISSUE THREAD

**Issue by artsymartha68** [department-of-veterans-affairs/va.gov-team#5731]
There's a typo on the VA.gov homepage. Can we fix it? The heading should be Borne, not Born, to match all the other instances and image.

<img width="345" alt="Screen Shot 2020-02-11 at 11 25 29 AM" src="https://user-images.githubusercontent.com/47792423/74257429-cfafe900-4cc2-11ea-8444-77f8cf6feeb2.png">

@kelsonic advised me to open an issue, I hope I did it correctly! :)

**Comment by Hampshire100** [comment]
I made the update in Drupal. Not sure when the build is complied but whenever that is done this should be live.

**Comment by jenniferlee-dsva** [comment]
It's live. This can be closed. Thx for catching @artsymartha68!
