### ISSUE TITLE
Sitewide Content, Accessibility and IA Intake Form - Form 21-0972 Alternate Signature

### ISSUE THREAD

**Issue by tbaker1026** [department-of-veterans-affairs/va.gov-team#57319]
## What does your team need support for? Check all that apply.
- [x] Launching one or more unauthenticated pages, online forms, apps, or tools on VA.gov
- [ ] Making revisions to one or more existing VA.gov pages
- [ ] Something else 
 
 *Give a brief description of what your team needs support with.*

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [x] Yes
  - [ ] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
## When do you expect to launch your product to 100% of users?
  
*Please provide an estimated date so our team can create other relevant tickets.*
  
## Supporting artifacts
*Please provide supporting artifacts as available.*

- Link to [product outline:](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/21-0972%20Alternate%20Signer/Product%20Outline.md)
- Link to or attach user flows:
  - [Mural Userflow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1689262977711/24990c2ab9fd88497f1512d57a599b4fe7f522b5?sender=ud94436ff2bf5d5ce166a5253)    
- Link to prototype or mockups: 
  -  [Sketch Files](https://sketch.com/s/2365576f-860a-40a7-8a18-8f1cfffaa1cc) 
- Link to any epics/issues that may be helpful:
  -  [Source of Truth](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/21-0972%20Alternate%20Signer/sourceoftruth.md)
  - [Sitewide IA Questions](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/21-0972%20Alternate%20Signer/ia-sitewide.md)
  - [New Questions/Content for review](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/21-0972%20Alternate%20Signer/new-content-for-review.md)

## Will this work be going through the Collaboration Cycle?
- [x] Yes 
- [ ] No

## When does this work need to be done?
- Estimated launch date:
- Estimated staging review date:
- Content, Accessibility, and IA work needed by: 

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: Matthew Dingee
-	Product manager: Tricia Baker
-	Designer: Jeana Clark
-	FE engineer:  Garrett Rabian
-	Product/team Slack channel: veteran-facing-forms

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by jeana-adhoc** [comment]
I have created a new markdown file that extracts only the new content that has not been reviewed in our form process so far.

- [New Questions/Content for review](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/21-0972%20Alternate%20Signer/new-content-for-review.md)

**Comment by jennymayoco** [comment]
Hi @tbaker1026 ! The h1 is currently in review for this one. Once finalized, we will follow up with the finalized IA spec

**Comment by jennymayoco** [comment]
Hi @tbaker1026 @jeana-adhoc here is the [finalized IA spec](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/form-digitization-21-0972.md). Let me know if there are any questions!

**Comment by jeana-adhoc** [comment]
The content edits have been [applied to our form on staging](https://staging.va.gov/supporting-forms-for-claims/alternate-signer-form-21-0972). We are currently working through some technical issues, but the content, URL, breadcrumbs are in place.

I think this can be closed now.
