### ISSUE TITLE
[SPIKE] Remove unused schema files

### ISSUE THREAD

**Issue by amponce** [department-of-veterans-affairs/va.gov-team#57310]
## Issue Description

Remove unused employment schema files

Due to recent changes to the employment history navigation we've updated form.js to use custom pages instead of using the Schema and uiSchema 

## Front end tasks
- remove `/pages/income/employmentEnhanced/spouseGrossMonthlyIncome.js`
- remove `/pages/income/employmentEnhanced/spousePayrollDeductionInputList.js`
- remove `/pages/income/employmentEnhanced/spouseGrossMonthlyIncome.js`

- Ensure e2e tests succeed

## Acceptance Criteria
- [ ] Remove unused schema files for vet and spouse employment
- [ ] Unit tests pass

**Comment by JunTaoLuo** [comment]
I think this has already been completed by https://github.com/department-of-veterans-affairs/vets-website/pull/29474.

**Comment by JunTaoLuo** [comment]
Closing since there's no more work needed here.
