### ISSUE TITLE
Spike: Investigate Microservice Structure for Sign in Service developer dashboard

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#57325]
Sign in Service developer dashboard will initially have the feature:
* Client Configurations

But will in the future have additional features, such as:
* Fraud, Waste, Abuse dashboard
* Find MPI by ICN

So this spike is to create a recommendation on how to organize the code and deployments of these features.
Should they be deployed separately? (Microservice structure) Should they be in different repositories? Hosted in different frontends and backends?

**Comment by bosawt** [comment]
TBD: whether this makes sense as a monolith, or a series of micro services

**Comment by bosawt** [comment]
TBD: whether this makes sense as a monolith, or a series of micro services

**Comment by joeniquette** [comment]
Closing in preference for Alexs new ticket
