### ISSUE TITLE
OCTO objectives may need to be updated in research template

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#57327]
### Description
The platform research plan template points to this [draft strategy document last updated in 2022](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/strategy#readme).
Since then, it appears 2023 objectives have been drafted, but it's unclear where they officially live

![image](https://user-images.githubusercontent.com/14154792/234152986-85b06546-c1bb-4aac-90b5-a9807e322b27.png)

### Relevant URLs
https://depo-platform-documentation.scrollhelp.site/research-design/research-checklist#Researchchecklist-Writingyourresearchplan

### Which type of team are you on? (Platform team, VFS team, or Leadership)
VFS, benefits

**Comment by naomimarcussen** [comment]
I've created a new page for the [2023 OCTO-DE Priorities](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/strategy/OCTO-DE%20Priorities%202023.md) and updated the link on the research template to point to it. Fun fact - there's a bot in Slack where if you type "OCTO priorities" it'll return a list of the latest.
