### ISSUE TITLE
Midpoint Review - Design Feedback - Benefits Disability Experience, Disability Comp Application (21-526 EZ), Add Self Assessment Part A form information to BDD workflow

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#57333]
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- UI feedback is limited since the prototype is half wireframes.
- Review design intent feedback

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- **Must**: Remove all yellow highlights and notes
- **Must**: I know we talked about this at the design intent, on the supporting evidence page, for the document type, if the Veteran can only upload the Disability Benefits Questionnaire, then do not give them an option to upload other documents.
- **Must**: The << Back button chevrons should be primary blue.
- **Consider**: Align the text between Separation Health Assessment and Disability Benefits Questionnaire. Veterans will need to read the alert to understand those are the same thing.

**Comment by lydiahooper** [comment]
For whatever reason, I'm just now seeing this ticket from midpoint. We are currently past staging review, and since this was not discussed then I'm going to close this ticket.
