### ISSUE TITLE
Salesforce Training (Young Lee) - Session 04

### ISSUE THREAD

**Issue by edpearson20** [department-of-veterans-affairs/va.gov-team#57350]
Salesforce Introductory Training (Young Lee) - Session 03
Prior Ticket #56876
[/] Overview - Completed Sprint Prior to 2023-04-12
[/] Tier 1 Agent workspace - Completed Sprint Prior to 2023-04-12
[/] Tier 2 Technical Analyst workspace - Completed Sprint Prior to 2023-04-12

[/] - Report View - Completed Sprint Prior to 2023-04-12
[/] - Report Creation - Completed Sprint Prior to 2023-04-12
[/] - Case management - Completed Sprint Prior to 2023-04-12

[/] - Veteran Communication Completed Sprint Prior to 2023-06-24
[/]  - Outlook - Support Inbox(es) Completed Sprint Prior to 2023-06-24
[/]  - Knowledge management (Templates) Completed Sprint Prior to 2023-06-24
[ ]  - Email Builder
[ ]  - Omnichannel routing (Escalations) 
[ ]  - Support Analytics and Reporting

**Comment by manalo-soco** [comment]
@edpearson20  @ATMiddleton  can we move this to next Spring?

**Comment by edpearson20** [comment]
Held Salesforce Session 04 training session with Young.

- Reviewed two separate cases and provided guidance on discretionary handling
- Shared Knowledge Base Article folders for referenced cases
- Displayed method of searching Email Builder templates
- Displayed method of searching VA.Gov Website using Google.com

**Comment by edpearson20** [comment]
Discussed Tier 2 process and escalations with Young on 6/5.  Many of the follow up training items relate to Email Builder.

Remaining...

[ ] - Escalations
[ ] - Veteran Communication
[ ] - Outlook - Support Inbox(es)
[ ] - Knowledge management (Templates)
[ ] - Email Builder
[ ] - Omnichannel routing (Escalations)
[ ] - Support Analytics and Reporting

**Comment by ATMiddleton** [comment]
@edpearson20 will create another ticket including the outstanding tasks and store in backlog.

**Comment by manalo-soco** [comment]
Refer to [this ticket](https://app.zenhub.com/workspaces/contact-center-62cdd9546ec1530018209672/issues/gh/department-of-veterans-affairs/va.gov-team/60718)
