### ISSUE TITLE
Warning alert box icon abuts the H3

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#5735]
## What happened?

There's a CSS bug in the display of the Warning alert box in the modal, where the icon is too close to the `h3`.

**Alert box in Staging for Profile updates, in Firefox (both Windows and Mac)**
![20200211-Firefox-alertbox-bug-authdxp](https://user-images.githubusercontent.com/57469/74257511-f2da9880-4cc2-11ea-9300-929c62945094.png)

**Alert box in design.va.gov, also from Firefox**
![20200211-Firefox-alertbox-designsystem](https://user-images.githubusercontent.com/57469/74257512-f3732f00-4cc2-11ea-9537-3b717758f057.png)

## Specs:
- Device: Windows laptop, MacBook Pro
- Browser: Firefox 72.0.2 (64-bit), Firefox 73.0 (64-bit)
- Test User _(if applicable)_: vets.gov.user+56, aka Shirley

## Steps to Reproduce
- URL: Staging, address validation — go to Profile, edit an address with a wrong address in order to display the "Please confirm your address" modal, validate that the icon abut the `h3`
- Test User _(if applicable)_: vets.gov.user+56, aka Shirley

## Desired behavior

Ensure there is space between the icon and the `h3` to align with the design system, so that users will feel confident they are on VA.gov.

## Acceptance Criteria
- [ ] Ensure there is space between the icon and the `h3` to align with the design system

**Comment by Samara-Strauss** [comment]
Closing. Tze found the same bug in QA and we already have this issue documented here #5553.
