### ISSUE TITLE
IA design: Form 21-0972 Alternate Signature

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#57366]
## Issue Description

Intake request: https://github.com/department-of-veterans-affairs/va.gov-team/issues/57319

**Comment by RLHecht** [comment]
waiting on H1

**Comment by jennymayoco** [comment]
Here is the [IA spec](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/form-digitization-21-0972.md) for this form.

- [X] Has been shared with the forms team
- [X] Has been shared with Megan

Moving ticket to validate as feedback has been provided to team
