### ISSUE TITLE
SOCKS access for Thomas Reynolds

### ISSUE THREAD

**Issue by tsr-rise8** [department-of-veterans-affairs/va.gov-team#57364]
### Your Name

Thomas Reynolds

### Your Email

Thomas.Reynolds4@va.gov

### Your Role and Team

Software Engineer on NOVA

### Product Manager (PM) name and email

Zachary Law zack.law@oddball.io

### Product Owner (PO) name and email

Beverly Nelson beverly.nelson@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDAV+zkGjX4i/ygzk4vLpdxjkh4yfx7aUtfDs6uqOr3g3zGoLeEcp8ePMaSl6kuuPtsRmprYinOtIsXjEdODFOLltvxu7ldEwYLSNpHpvssSf2haNJd/gl7WGrzSsXU4F0r3fgUUUBeJDlH3JvluImW02Qj6lx0+GbZL3I2Xp0XRSuljlo0QIZhFFsW3d0qztm6U56LljwT97QZQGnYPA4cTavqaxej7bUCIxhF7sB9qjbVVA60qaHzW9TUrfmTw7M3DyjNcB7Zv6TnRGOx5lO3+JFVUrW66bQbkBZdsMaI/rOITjMy7zj8VQL5pbdkQadNlrtDutUkZwiC5fSqbD+nExXTqrKL9j0O/5sQiQEGN4cAFqcjuAHOsRAYeX3k2q8FIjDY/i1PTZC+2QF7kq1hzsHswjKjU+TYyRkom6jyMnK8SJcOAqTbX8hOszPYaq3AX8DqR2kQS95gdAXY9QCHLtiNv1yJovB1+OS0uyN426gwe4PZYgT6vKzd/POvGZU= rhoma@ThomassRise8M2.lan

### E-QIP Transmittal Confirmation

<img width="1363" alt="Screenshot 2023-04-25 at 1 35 37 PM" src="https://user-images.githubusercontent.com/97049393/234357215-005f0869-9672-4c50-9236-cb6a6772683c.png">

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by flooose** [comment]
@tsr-rise8 you should be good to go.
