### ISSUE TITLE
Error message content discovery - Disabilities

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#57360]
Issue Description
We are aware that some errors are resulting in claims not being established, and that some user-facing error messages could be improved. 

In scope:
- Disabilities (PTSD and individual employability)

Out of scope:
- Ancillary forms except those included in 526 flow

Need to Know:
Spreadsheet for tracking error messages

VA Platform content style guide for error messages:
https://design.va.gov/content-style-guide/error-messages/
https://design.va.gov/patterns/help-users-to/recover-from-errors

VA Platform design system template and patterns for form review page: https://design.va.gov/templates/forms/review
https://design.va.gov/patterns/help-users-to/check-answers

Tasks
- [ ] Identify error messages that are missing, incorrect, or unclear 

Acceptance Criteria
- [ ] List of error messages that need creation or rewrite

**Comment by lydiahooper** [comment]
Closing ticket as team 2/carbs is taking on this work
