### ISSUE TITLE
va.gov / SSOe session synchronization workflow

### ISSUE THREAD

**Issue by ericbuckley** [department-of-veterans-affairs/va.gov-team#5737]
When a user accesses https://www.va.gov/, they will ideally have and/or obtain 2 browser session cookies (one issued from va.gov and another from SSOe) to give them access to the features within www.va.gov and the affilated sites linked within.

Howerver when they first land, we need to check a few different states in order to figure out what path(s) a user should take to fully authenticate.

Three tests can be executed by vets-website to see what state the user is in
a) does the user have an SSOe session [GET https://eauth.va.gov/keepalive]
b) does the user have a va.gov session [GET https://api.va.gov/v0/user]
c) if **b** is true, does the user have a id.me UUID [check for attribute in the response for **b**]

Based on the results of those tests, the following flow diagram can be used to determine what options to present the user.

![vagov_login](https://user-images.githubusercontent.com/170002/74262528-e3068880-4cb1-11ea-8aaa-492a4bac8810.png)

**Comment by ericbuckley** [comment]
@ambikaroos / @patrickvinograd there is some overlap here with other tickets, specifically #5417, but I was thinking this might be helpful as an EPIC to outline the different implemenation paths we need to go down to achieve session continuity.

**Comment by ambikaroos** [comment]
@patrickvinograd to review, and then we can move content to a markdown file

**Comment by ericbuckley** [comment]
some changes were recently made to the `/keepalive` endpoint, to interact with it from within the browser you can run the following snippet.

```
fetch('https://pint.eauth.va.gov/keepalive', {
    method: 'GET',
    credentials: 'include',
    cache: 'no-store'
  })
  .then(function(response) {
    console.log(response.headers.get('session-alive'));
    console.log(response.headers.get('session-timeout'));
  })
```

**Comment by ambikaroos** [comment]
See updated flow on GH here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/sso/sso-landing-page-login-flow.png

Will add ticket to cover question about whether we need to auto-log out a user whose session is expired.
