### ISSUE TITLE
Recreate breakers charts in Datadog

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#57385]
### PROBLEM STATEMENT
It seems that [this chart](https://vagov.ddog-gov.com/dashboard/7yz-4e3-6hs/vsp-breakers?from_ts=1684925901823&to_ts=1684940301823&live=true) is not functioning now that we've fully moved vets-api into Datadog. It's possible that the `vets_api.statsd.api_external_service_up` metric used was specific to prometheus. I do see specific metrics for each service though. For example: `vets_api.statsd.api_external_service_BB_up` and `vets_api.statsd.api_external_service_EVSS_Letters_up`

We should re-create this chart to reference when downstream services are having issues.

### ACTION ITEMS
- [x] get appropriate permissions to complete the ticket
- [x] replicate grafana charts into the new DD template (breakers chart)
- [ ] potentially need to make a custom chart (be sure to utilize json)

### DEFINITION OF DONE
Chart (above) is functioning again as initially intended.

**Comment by laineymajor** [comment]
Needs PIV card before starting

**Comment by laineymajor** [comment]
Will likely carryover. Trouble getting DD access.

**Comment by laineymajor** [comment]
This needs to be moved to next sprint. NA for this sprint as Ryan is still having trouble gaining DD access. He's also been filling in on support in Lindsey's absence.

**Comment by rjohnson2011** [comment]
Original Grafana chart  - https://grafana.vfs.va.gov/d/000000022/breakers?orgId=1

**Comment by rjohnson2011** [comment]
Created Breakers External Services Success dashboard in DD - https://vagov.ddog-gov.com/dashboard/i8s-xrp-yf6?refresh_mode=sliding&view=spans&from_ts=1704379617103&to_ts=1704383217103&live=true

Working on getting other Grafana Breakers Metrics into dashboards.

**Comment by rjohnson2011** [comment]
Additional dashboards created:

Breakers External Services Failures - https://vagov.ddog-gov.com/dashboard/ddc-w3t-mtf?refresh_mode=sliding&view=spans&from_ts=1704727321414&to_ts=1704730921414&live=true

Breakers External Services Median Time - https://vagov.ddog-gov.com/dashboard/bqf-7a8-t2z?refresh_mode=sliding&view=spans&from_ts=1704727326979&to_ts=1704730926979&live=true

**Comment by LindseySaari** [comment]
Ryan is updating the charts with more detailed endpoints. He's finishing up and plans to wrap this up soon.

**Comment by jennb33** [comment]
Ryan is building out latency charts today.

**Comment by rjohnson2011** [comment]
Latency charts dashboard is up - https://vagov.ddog-gov.com/dashboard/k2y-djf-qfm?refresh_mode=sliding&view=spans&from_ts=1705417796074&to_ts=1705421396074&live=true
