### ISSUE TITLE
[Design] My VA audit ux: Update headings in Benefit Payments card documentation/designs

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#57393]
## Background
Per feedback from staging review and design intent, we need to correct the headings in the benefit payments card: Benefit payment cards have an H3 heading followed immediately by an H4 heading, which doesn't really reflect the structure of the content and can be disorienting or misleading to screen reader users navigating the content by heading. (see [54878](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54878) and [47549](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47549)). 

#### This ticket is to update designs/documentation, code to be updated in #60637.

>Using test user 80, you get this benefit payment card:

```
<div ...>
   <h3 class="vads-u-margin-top--0" data-testid="deposit-header-v2">
      +$3,057.13
   </h3>
   <h4 class="vads-u-margin-top--0">
      Compensation &amp; Pension - Recurring
   </h4>
   <p ...>
      Check mailed on November 1, 2022
   </p>
   <a ...>
      View your payment history<i ...></i>
   </a>
</div>
```

### Platform Recommendation
>My best suggestion would be to make the `h4` a `p` paragraph with styling to make it look like a heading, and then using `aria-describedby` to associate it with the `h3`. That would look something like this:

```
<div ...>
   <h3 class="vads-u-margin-top--0" data-testid="deposit-header-v2" aria-describedby="some-unique-id">
      +$3,057.13
   </h3>
   <p class="..." id="some-unique-id">
      Compensation &amp; Pension - Recurring
   </p>
   <p ...>
      Check mailed on November 1, 2022
   </p>
   <a ...>
      View your payment history<i ...></i>
   </a>
</div>
```

>Screen readers will announce the `h3` and the line beneath it together, providing full context while still having a heading structure that models the content.

## Tasks
- [x] Update design/FE documentation

## Acceptance Criteria
- Heading level is is corrected as outlined above
- documentation is updated to reflect headings

**Comment by aagosto90** [comment]
I created an [annotations doc for this in Sketch](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/OeRqarG) and added accessibility specs in the [FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/documentation/benefit-payments-FE-documentation.md#accessibility-specs) which has that Sketch link as well.
