### ISSUE TITLE
[Design] My VA audit ux: Update headings in Benefit application in progress documentation/designs

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#57394]
## Background
Per feedback from staging review, we need to correct the headings in the benefit application in progress card: When a user has a benefits application in progress (test user 220), the heading level for the application-in-progress card is an H4. The heading before that is an H2 so it skips a heading level, which can be disorienting for screen reader users. (see [54880](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54880) for full details). 

## Tasks
- [ ] Update design/FE documentation

## Acceptance Criteria
- Heading level is updated to H3 in documentation/designs as needed

**Comment by aagosto90** [comment]
There isn't really anything to change in the design for this. The heading in the card uses H3 styling already so this is a code update; but I did include [an annotation in Sketch](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/v/wDvorq/a/OeRqarG) that points out that the heading should be an H3. This is linked in the [FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/documentation/benefit-payments-FE-documentation.md#visual-specs) along with the other accessibility annotations.
