### ISSUE TITLE
Contact Center Review for Veteran Facing Forms- Digitize Form 21-4142(a) - Release Private Medical Records

### ISSUE THREAD

**Issue by tbaker1026** [department-of-veterans-affairs/va.gov-team#57404]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
- This form is currently only in PDF Version, we are digitizing the form for an online Experience.
- The General Release for Medical Provider Information to the Department of Veterans Affairs (VA Form 21-4142a) authorizes the VA to obtain medical provider information from a non-VA source, like a private doctor or hospital. This includes the name and address of a facility and the veteran’s medical treatment dates.
- The Authorization to Disclose Information to the Department of Veterans Affairs (VA Form 21-4142) authorizes the VA to obtain the veteran’s personal information from a non-VA source, like a private doctor or hospital. Examples of personal information may include the veteran’s medical treatment, hospitalizations, psychotherapy, or outpatient care.

## User Stories
- As a Veteran I would like to release my private (non VA Medical Facility) medical records to the VA to aid in processing a claim
- As a patient related to the Veteran I would like to release my private (non VA Medical Facility) medical records to the VA to aid in processing a claim

### Launch Date
- Mid May 2021
- 
### Version Number
Version 1

### Product Guide
- [Form 21-4142(a) Product Guide](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Assets/Form%2021-4142(a)%20Product%20Guide.docx)

### Product Video
N/A

### Product Video Transcript
- N/A

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by tbaker1026** [comment]
Working on Product Guide, but wanted to open issue to track work.

**Comment by starlow00** [comment]
Received draft, commencing review

**Comment by starlow00** [comment]
Currently auditing, will complete this sprint.

**Comment by starlow00** [comment]
Hi @tbaker1026. I have a couple of requests. First, in the Navigation section, the Direct URL is missing. Do you have that available? 
Second, the text in the workflow diagram is illegible for readers. Do you have a high-res version, maybe something that can be split in two over two pages?

**Comment by tbaker1026** [comment]
@starlow00 - we don't have the exact URL yet - still working with IA to find a home for it, will update it when I get it - I do have a high resolution - I broke it out into three sections - I can update the word document if you think this will work. 

![](https://user-images.githubusercontent.com/115116356/235811881-a77a55d5-e82d-4168-8183-2719505c4ed6.png)

![](https://user-images.githubusercontent.com/115116356/235811879-083a121d-d511-4acb-9bb2-ecf3fe16af78.png)

![](https://user-images.githubusercontent.com/115116356/235811880-b674ff4f-f983-4cff-a0b4-2dd0014e84de.png)

**Comment by starlow00** [comment]
Thank you for the images, @tbaker1026. I'll leave the URL as TBA, and place the images in the review draft.

**Comment by tbaker1026** [comment]
@starlow00 that upper portion really is not anything - it is just showing that if you are a Veteran filling it out - it skips the whole middle section of obtaining the persons contact information filling out the form and you as the Veteran can just sign it.  (it is just a dotted line

**Comment by starlow00** [comment]
Thanks @tbaker1026. The draft looks good. I will forward it to VEO for their review.

**Comment by starlow00** [comment]
No changes from VEO. Current version attached.[https://app.zenhub.com/files/133843125/169ceda1-a269-494f-a0e1-979b1201862d/download](https://app.zenhub.com/files/133843125/169ceda1-a269-494f-a0e1-979b1201862d/download)
