### ISSUE TITLE
AWS access for Kevin Suarez

### ISSUE THREAD

**Issue by kjsuarez** [department-of-veterans-affairs/va.gov-team#57427]
### COR Name

Jennifer O'Day

### Vendor Onboarding Representative Name

Agile Six - Anthony M. Arashiro

### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Kevin Suarez

### Your Email

kevin.suarez@agile6.com

### Team, Role, and Company of the target individual

VFS Debt Resolution - Software Engineer [Agile Six]

### Product Manager (PM) name and email

Tom Davis, Thomas.Davis@govcio.com

### Product Owner (PO) name and email

Matt Self, Matthew.Self2@va.gov

### Desired AWS Access

Access to all resources related to vets-api project.

### Access Expiration

04-26-2024

### E-QIP Transmittal Confirmation

![Screenshot 2023-04-18 at 10 51 42 AM](https://user-images.githubusercontent.com/8467971/234601926-8378c29c-4fbe-411c-bf15-61c13acf9969.png)

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by considerable** [comment]
VFS Team Roster

**Comment by HeatherRienks** [comment]
Hi @considerable :)
Just checking in the status of this ticket so @kjsuarez can begin working on a ticket. Any updates would be great. Thanks!

**Comment by BillChapmanUSDS** [comment]
I approve this access

**Comment by HeatherRienks** [comment]
@BillChapmanUSDS - thanks for the additional info. I apologize for the confusion here; @kjsuarez only needs AWS access up to staging, NOT production. He should have the same access as @ScottyRJames (our other Backend Developer).  
I did not realize that we were asking for elevated privileges. Per your request, I will ping you in Slack as well.

@shiragoodman - is there a way we can update the "AWS Console Access" section on [Platform "Request Access to Tools" page ](https://depo-platform-documentation.scrollhelp.site/getting-started/request-access-to-tools)? I think that might help clear up some confusion when new team members are requesting access. Thank you, both!

**Comment by BillChapmanUSDS** [comment]
Excellent,  I approve this access request.
