### ISSUE TITLE
Design Intent - Design Feedback - OCTO Health Apps, MHV Medical Records, After Visit Summary

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#57426]
## VFS actions
- [x] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [x] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [x] Close the ticket when all feedback has been addressed.

## Thoughts/questions

-  Matt Dingee: "On this page" isn't enough to save the After-visit summary page from being overwhelming and confusing. Far, far too much content on that single page.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

-

**Comment by kristenmcconnell** [comment]
After design explorations, we are leaning towards an accordion-based design, which we will test.
