### ISSUE TITLE
Messaging page - Unauthenticated users main content updates

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#5742]
**User Story**
As a user who is browsing the Messaging page on VA.gov without authenticating (logging in), I want the content on the page (above and below the alert box) to be neutral between MHV and Cerner so that I am not confused about where my patient portal information is housed.

**Acceptance Criteria**
1. Content on Messaging page (above and below the alert box) for unauthenticated users does not contain any references to MHV or Cerner

**Tasks**
- [x] SSO-Login team: First pass at copy changes
- [x] VSP Content-IA team: Edit and validate
- [ ] SSO-Login team: Ensure frontend implementation

_Alert box content updates are housed in separate tickets_

**Comment by bridgethapner** [comment]
@peggygannon Wireframe is here: https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/404425133_-5742_Messaging_page_-_Unauthenticated_users_content_updates. Everything I've changed from the current VA.gov unauth page is outlined with a pink box & there are comments in the Invision Prototype that explain what I've changed and why.

**Comment by peggygannon** [comment]
Hello @bridgethapner Please see below content recommendation for the copy under **What if I have more questions?** I tightened up the language a bit. 

**What if I have more questions?** 
If you have more questions about Secure Messaging on MyHealtheVet, please read the [Secure Messaging FAQs]( https://www.myhealth.va.gov/mhv-portal-web/web/myhealthevet/faqs#smGeneralFAQ) on the My HealtheVet web portal. 

Or contact the My HealtheVet help desk at 877-327-0022 (TTY: 800-877-8339). We’re here Monday through Friday, 7:00 a.m. to 7:00 p.m. CT.
You can also [contact us online](https://www.myhealth.va.gov/mhv-portal-web/web/myhealthevet/contact-mhv

**Comment by bridgethapner** [comment]
Hi @hinzed1127 - Unauth content for the messaging page is done + in wireframes. In the wireframes, I have circled all the changed areas in blue and numbered them. The correct text is below.

Wireframe link: https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/407473950_-5742_Messaging_Page


### Content Change 1
With VA Secure Messaging, you can communicate privately online with your VA health care team. Find out if you’re eligible to use Secure Messaging, and how to sign in to begin using this tool in the health management portal.

### Content Change 2
With Secure Messaging, you can write messages, save drafts, review your sent messages, and keep a record of your conversations.

### Content Change 3
**What if I have more questions?**
If you have more questions about Secure Messaging on MyHealtheVet, please go to the [Secure Messaging FAQs](https://www.myhealth.va.gov/mhv-portal-web/web/myhealthevet/faqs#smGeneralFAQ) on the My HealtheVet web portal.

Or contact the My HealtheVet help desk at 877-327-0022 (TTY: 800-877-8339). We’re here Monday through Friday, 7:00 a.m. to 7:00 p.m. CT.
You can also [contact us online](https://www.myhealth.va.gov/mhv-portal-web/web/myhealthevet/contact-mhv).

**Comment by peggygannon** [comment]
@bridgethapner Thank you. Updated wireframe for this page looks good.

**Comment by FranECross** [comment]
Ticket is old and outdated. Closing.
