### ISSUE TITLE
Midpoint Review - Design Feedback - Product 21-0972 Alternate Signer

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#57431]
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- Outstanding job on prototype and user flows!
- I am OoO for the meeting.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- **Must**: Use the [memorable date](https://design.va.gov/components/form/memorable-date) for DOB.
- **Must**: Remove the [error styling](https://design.va.gov/components/form/checkbox#error) from [this question](https://www.sketch.com/s/2365576f-860a-40a7-8a18-8f1cfffaa1cc/a/qbb0zmV) until they try to click continue without selecting an answer.

**Comment by jeana-adhoc** [comment]
The team is still working on [memorable date](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54747) (See memorable date tickets in the epic).

- My intent is that the error messages only show when they are triggered, but I wanted to show them here so the error messages could get some visibility for review.
