### ISSUE TITLE
Analytics Implementation or QA Support for Organic Adoption Experiment (LGA team)

### ISSUE THREAD

**Issue by kscoulter** [department-of-veterans-affairs/va.gov-team#57439]
# Google Analytics Implementation or QA Request
Organic Adoption Modal informs DS Logon users about Login.gov credential option and encourages them to make an account. LGA team wants to track modal dismissals, and CTA button clicks. See [issue 53788](https://github.com/department-of-veterans-affairs/va.gov-team/issues/53788)

![Screen Shot 2023-04-26 at 10 42 47 AM](https://user-images.githubusercontent.com/12025195/234612101-413219b8-d036-440e-b3ec-f8b237b888f1.png)

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

</div>
</details>

## Description
Here's the code for the modal https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/user/authentication/components/OrganicAdoptionExperimentModal.jsx

The relevant portions are line 19-23:
```
const onPrimaryButtonClick = async () => {
    setDismissalCookie();
    recordEvent({
      event: 'cta-button-click',
      'button-type': 'primary-button',
      'button-click-label': '(organic experiment) Get Login.gov now',
    });
    location.href = await authUtilities.signupOrVerify({
      policy: 'logingov',
      isLink: true,
      allowVerification: false,
      useOAuth,
    });
  };
```
Line 32-40
```
const onSecondaryButtonClick = () => {
    recordEvent({
      event: 'cta-button-click',
      'button-type': 'secondary-button',
      'button-click-label': '(organic experiment) Learn more',
    });
    location.href =
      'https://www.va.gov/resources/signing-in-to-vagov/#should-i-create-a-logingov-or-';
  };
```

And line 51
```  onClose={() => {
        setDismissalCookie();
        recordEvent({ event: 'organic-experiment-dismiss-modal' });
        onClose();
      }}
```

I cannot find `organic-experiment-dismiss-modal` event in GA dashboard. Please compare this to [other modals implementation in the header](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/user/authentication/components/SessionTimeoutModal.jsx).

```  
extendSession = () => {
    recordEvent({ event: 'login-cta-stay-signed-in' });

...
  };
```

I can see `login-cta-stay-signed-in` event in GA dashboard. When I inspect the GA events in the console using the recommended google extension, I see that `login-cta-stay-signed-in` event is fired twice, once to the correct google tag (UA-50123418-16), once to the wrong google tag (UA-69938072-4).

![Screen Shot 2023-04-26 at 10 53 28 AM](https://user-images.githubusercontent.com/12025195/234615498-75729102-d105-4b05-84df-4025afd65dec.png)

In contrast, this is what happens with Organic Adoption Experiment Modal

![Screen Shot 2023-04-26 at 10 54 56 AM](https://user-images.githubusercontent.com/12025195/234615907-baea3f80-7d66-4014-a39e-c93309d466b2.png)

### How to test
You will need [React Dev Tools Chrome Extension](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?hl=en)

- Navigate to Va.gov and inspect the page. Find the Components tab in dev tools (Fig 1).
- Find the modal with id `loginGovExperimentModal`. (Unfortunately the prod is minified, so you won't see component names, instead you'll see something like a > po > p. See the screenshot for clarification)
- On the left side of the Components tab you'll see props listed. Manually change `visible` prop to true to make any modal appear. (See Fig 2 for session timeout modal example)

**Fig 1**
![Screen Shot 2023-04-26 at 10 56 59 AM](https://user-images.githubusercontent.com/12025195/234616457-dfad2356-d499-4d24-8f59-0fe35d17d471.png)

**Fig 2**
![Screen Shot 2023-04-26 at 11 01 00 AM](https://user-images.githubusercontent.com/12025195/234617563-fea25abf-0c24-44a9-ba46-ca867c54a661.png)

### Required
- **Is this request for **Google Analytics implementation** or **QA**?**

     - [x] Google Analytics implementation
     - [ ] QA

- **Who is this request for?**

    - Platform analytics @michelle-dooley 
    
- **Provide the link(s) for Google Analytics implementation or QA**
  
    - [Insert link(s)]
    
- **When is the launch date?**
    - Whenever we have analytics set up.

- **What interactions need to be tracked?** 

- Modal dismissed
- Clicked Get Login.gov now CTA
- Clicked Learn More CTA

### Optional

Test user is being set up, please refer to this [Slack thread](https://dsva.slack.com/archives/C04LW2P19M0/p1682346393875229)

- **Any additional comments**

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by sdickson-gt** [comment]
@michelle-dooley any traction on this one?  FYI, the deployment of the modal directing users to create Login.gov credentials is a top priority of our team and we're targeting go-live in next couple weeks.  It's going to be critical to be able to collect related analytics. Appreciate your help!

**Comment by michelle-dooley** [comment]
@sdickson-gt - no progress yet.  I plan to pull this into our next sprint starting next week.

**Comment by michelle-dooley** [comment]
@sdickson-gt - for the 'X' (close modal event) you need to use the event: 'int-modal-click'.  Below is the data layer code and an example of where this is used for a different modal...

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/93597659/e564564e-79a8-45e7-84ef-c63df36ad0f9)

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/93597659/80bbd02e-be2f-46da-96bc-2408e40374b5)

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/93597659/85248a81-d3f4-4812-aeb6-25c3c6258e11)

Let me know after you make the event change and I will test it.

**Comment by kscoulter** [comment]
@michelle-dooley, changes are merged and are on prod

**Comment by michelle-dooley** [comment]
Great @kscoulter !!  Since I can't easily re-create this flow myself, could you run through it a few times as a test user (closing the modal) so I can see if the data shows up in GA as expected.

**Comment by michelle-dooley** [comment]
@kscoulter - I just ran some GA reports looking for the int-modal-click event that would come from this and I am not seeing it.  Could you run through the flow and send me screen shots of what you see in the console?  Do you see the int-modal-click event firing?

**Comment by kscoulter** [comment]
This is what I see. Looks right.

![Screen Shot 2023-05-16 at 2 47 05 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/12025195/008cad91-991a-4b5a-94e4-d842cbd967b0)

**Comment by michelle-dooley** [comment]
@kscoulter - and I see it showing up in [GA report](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20230516&_u.date01=20230517&explorer-segmentExplorer.segmentId=analytics.eventLabel&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.eventAction&explorer-table.advFilter=%5B%5B0,%22analytics.eventLabel%22,%22RE%22,%22int-modal-click%22,0%5D,%5B0,%22analytics.eventAction%22,%22PT%22,%22download%22,1%5D%5D&explorer-table.rowCount=500/).  So I think we are good on this ticket unless you have any further questions?  

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/93597659/2e552643-7946-4536-aba3-209ff81db0ab)

**Comment by kscoulter** [comment]
@michelle-dooley looks good to me
