### ISSUE TITLE
Create a test plan for current PEs

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#57433]
# Description
We need to develop a test plan for our Preview Environment system. Steps to create a test plan are --

1. Catalog the functional areas
1. Describe the expected behaviors for each area
1. Design tests to verify the expected behaviors
1. Understand where the system integrates with external systems
1. Design tests to verify the integration between systems

We can use [TestRail](https://dsvavsp.testrail.io/) to record and execute our test plan.

# Acceptance Criteria
- [x] A repeatable test plan that verifies all functional areas of the PE system is available in TestRail
- [x] A repeatable test plan that verifies all integrations between PE and other Platform systems is available in TestRail

**Comment by pjhill** [comment]
Completed a basic set of test cases to verify functionality for the PE system
