### ISSUE TITLE
[Sign-in Service Microservice] - Spike: App settings and secrets

### ISSUE THREAD

**Issue by rileyanderson** [department-of-veterans-affairs/va.gov-team#57448]
### Description of Spike
This spike is to determine the best way to store and load app config and secrets. 

vets-api uses the config gem for settings and secrets. vets-api treats every value as a secret and stores the environment configs in the k8s application manifests. This makes changing or adding simple config unnecessarily complex. 

Would it be a good idea to split out config and secrets? 

### App config
Creating config separate from secrets for every environment would allow us to checkin and easily modify config. 
- Discover ways we can set app config. 
  - Which gems are available? 
  - Should we consider making our own solution? 
- What are the pros and cons of each potential solution? 

### Secrets
How should we load secrets into our application? 
- Secrets will be loaded from AWS parameter_store in deployed environments using k8s config-maps.
- Environment variables are easiest to deal with in k8s/docker.

#### Discovery
- if we use environment variables how will we load those into the app for localhost and test?
- which solutions already exist?
- should we make our own solution? 
- are there better alternatives to environment variables? 
- what are the pros and cons to each potential solution?

**Comment by achievedaniel** [comment]
Currently vets-api uses config.rb to store configurations:
[https://github.com/rubyconfig/config](https://github.com/rubyconfig/config)

The config gem uses yml files to store configuratios using different files for each environment

For the separation of the signin service this would be unnecessary as I dont forsee the service needing the amount of configurations to make the overhead of using this gem worthwhile

The main issue of using this method is that all the configurations live with the code base and requires a code change just to change a configuration

A better easier to maintain/update solution is using AWS Parameter Store and AWS Secret Manager for both configs and secrets. By using these services we separate the configs and secrets from the code base making easier to maintain and eliminates the config files. 

https://docs.aws.amazon.com/secretsmanager/latest/userguide/intro.html
https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-parameter-store.html
 
How to use AWS Parameter Store and AWS Secret Manager with EKS:
https://docs.aws.amazon.com/systems-manager/latest/userguide/integrating_csi_driver.html

On how to use different secrets/configs per environment/stage:
https://blog.spikeseed.cloud/handling-aws-secrets-and-parameters-on-eks/

One main thing that still not clear is how to call this secrets/configs on our local environments. We could still use a separate file here and conditionally use this file only in the local environment. This will still allow local development without connection and will eliminate unnecessary calls to the service. We could create a process to sync local secrets/configs for when those are changed. 

Some possible solution in this article:

https://dev.to/hoangleitvn/07-best-practices-when-using-aws-ssm-parameter-store-6m2

**Comment by aparsley** [comment]
Thank you for suggesting the solution and keep up the good work!
