### ISSUE TITLE
Upcoming and Past Appointment List - Spacing Issue

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#57446]
## Summary
The appointment list page format is incorrect. There is an additional space. It's picking up a CSS style that it shouldn't (line-height: 3.5). 

## Specs
- Device: Mac
- Browser: Chrome 

## Steps to Reproduce
Test user:`ruben.moreno@id.me`

1. Go to: `https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/`
2. View upcoming appointment and past appointment list 

### Actual Result
![Screenshot 2023-04-26 at 12.22.27 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/f011c838-7f01-4071-9163-9afcb1531bd4)

### Desired Result
<img width="214" alt="Screenshot 2023-04-26 at 11 31 28 AM" src="https://user-images.githubusercontent.com/90797205/234626179-66b23638-21cc-4db7-a6a0-ba160d67d118.png">

## Definition of Done
- [ ] Desired result is achieved and/or document decisions made
- [ ] Relevant documentation is updated

---

**Comment by simiadebowale** [comment]
@ldelacosta - This is ready for validation

**Comment by ldelacosta** [comment]
The issue has been addressed. Validated the fix in staging. No new issues. Closing out the ticket 

**Upcoming:** 
![Screenshot 2023-05-01 at 3.02.48 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/bb909f94-e4af-4e3e-a611-27a492e79011)

**Past:** 
![Screenshot 2023-05-01 at 3.03.29 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/58910ceb-e03f-4aa8-808c-01cdc1b66f96)![Screenshot 2023-05-01 at 3.04.17 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/6819573e-b7ea-4fd1-89cd-8d5265e4b054)
