### ISSUE TITLE
Test Results page - Unauthenticated users main content updates

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#5744]
**User Story**
As a user who is browsing the Test Results page on VA.gov without authenticating (logging in), I want the content on the page (above and below the alert box) to be neutral between MHV and Cerner so that I am not confused about where my patient portal information is housed.

**Acceptance Criteria**
1. Content on Test Results page (above and below the alert box) for unauthenticated users does not contain any references to MHV or Cerner

**Tasks**
- [x] SSO-Login team: First pass at copy changes
- [x] VSP Content-IA team: Edit and validate
- [ ] SSO-Login team: Ensure frontend implementation

_Alert box content updates are housed in separate tickets_

**Comment by bridgethapner** [comment]
@peggygannon Wireframe is here: https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/405217796. Everything I've changed from the current VA.gov unauth page is outlined with a pink box & there are comments in the Invision Prototype that explain what I've changed and why. I edited the intro paragraph a fair amount, and just 1 other headline down the page.

**Comment by AkucherGCIO** [comment]
02-24-20
Selina will review it today and wrap up content audit.

**Comment by lunascoop** [comment]
@peggygannon I have reviewed and included my feedback in the attached document.
[Test results page_unauthenticated.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4247548/Test.results.page_unauthenticated.docx)

**Comment by peggygannon** [comment]
@bridgethapner Please see below content recommendations for UNATHEN Test results page. These edits have also been entered into the prototype: 

Recommended content edits: 
Intro edit: 
You can view your VA lab and test results online with our lab and test tool. Find out if you’re eligible to use this tool and how to sign in to view your results.

**How can this tool help me manage my health care?**
With this tool, you’ll be able to view and keep a record of your VA lab and test results. 
**You can use the tool to:**

**Am I eligible to use this tool?** 
You can use this tool to view and track your VA lab and test results if you meet all of the requirements listed below. 


**What if I have more questions?** 
If you have questions about lab and test results on MyHealtheVet, please go to the [Lab + Tests Results FAQs]( https://www.myhealth.va.gov/mhv-portal-web/web/myhealthevet/faqs#LabsandTests ) on the My HealtheVet web portal. 
Or contact the My HealtheVet help desk at 877-327-0022 (TTY: 800-877-8339). We’re here Monday through Friday, 7:00 a.m. to 7:00 p.m. CT.
You can also [contact us online] (https://www.myhealth.va.gov/mhv-portal-web/web/myhealthevet/contact-mhv

**Comment by bridgethapner** [comment]
Thank you @peggygannon @lunascoop @AkucherGCIO!

**Comment by bridgethapner** [comment]
Hi @hinzed1127 - Unauth content for the Lab and Test Results page is done + in wireframes. In the wireframes, I have circled all the changed areas in blue and numbered them. The correct text is below.

Wireframe link: https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/405217796

### Content Change 1
You can view your VA lab and test results online with our lab and test tool. Find out if you’re eligible to use this tool and how to sign in to view your results.

### Content Change 2
**How can this tool help me manage my health care?**
With this tool, you’ll be able to view and keep a record of your VA lab and test results.
You can use the tool to:

### Content Change 3
**Am I eligible to use this tool?**
You can use this tool to view and track your VA lab and test results if you meet all of the requirements listed below.

### Content Change 4
**What if I have more questions?**
If you have questions about lab and test results on MyHealtheVet, please go to the [Lab + Tests Results FAQs](https://www.myhealth.va.gov/mhv-portal-web/web/myhealthevet/faqs#LabsandTests) on the My HealtheVet web portal.
Or contact the My HealtheVet help desk at 877-327-0022 (TTY: 800-877-8339). We’re here Monday through Friday, 7:00 a.m. to 7:00 p.m. CT.
You can also [contact us online](https://www.myhealth.va.gov/mhv-portal-web/web/myhealthevet/contact-mhv).

**Comment by peggygannon** [comment]
Thanks, @bridget. I added one more additional  content comment in the wireframe (removal of "Are" from the bullet points. 

All other content updates look good.

**Comment by bridgethapner** [comment]
Thank you @peggygannon - made that change and added it to my Mar 9, 2020 comment above.

**Comment by FranECross** [comment]
Ticket is old and outdated. Closing.
