### ISSUE TITLE
SOCKS access for Samreen Zarroug

### ISSUE THREAD

**Issue by szarrougtw** [department-of-veterans-affairs/va.gov-team#57469]
### Your Name

Samreen Zarroug

### Your Email

Samreen.Zarroug@va.gov, samreen.zarroug@thoughtworks.com

### Your Role and Team

Developer, Digital Health Platform

### Product Manager (PM) name and email

Abigail Burton abbie.burton@thoughtworks.com

### Product Owner (PO) name and email

Abigail Burton abbie.burton@thoughtworks.com

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDjgKpnMtGgbKzGileP3ZzBigv3eKsEeA6ffDpTYaz/HBI0e2APCImDL3a4V1lw6KuQEGZYr2xGARFJlKYzormn4qbdKhYFzypJdZkFg3n70xVEYFyWXw0TNDdWkC15xQcs/jKESKmTBtrm7ZshlusFX8MZYhT32SqRbB+2KoYmmutlw8fcjJyp36uMpcXXZUvsPDtV4+zJIftiLIfbq9OOZoE0W5efqfbmSw7MaxphKA5I0Vr0P1R2wiTOe6kho8UteX0Py07+qQAZbuVV90kM7EhZ+RDt0PUtKosGtFYv/q5wPnRONUHRaCwv1f3vxdMiwr2j/lCvINkphvkINtvq7FqONUyRCfDrhOwdhaOI5QgSlcj/ZhOlkwpNAqsVYHtjbkkH1wbfuRDWjPQzYvdZvoNphcIOTj89ojrJYnylmgiWzGMRT0xWtZWsio6o1t7agUxjjJQvHUFl1EzN+J85ZKtnAu0/GU61KUsjOyekUf3ARzk7yoVfhTyylnMiFC8= samreen.zarroug@va.gov

### E-QIP Transmittal Confirmation

![transmittal_confirmation](https://user-images.githubusercontent.com/129233422/234647412-3cf598cc-acc1-4bfe-8ae6-97a4db232ee1.png)

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by considerable** [comment]
Hello @szarrougtw - I updated the comment in your SSH key to be samreen.zarroug@va.gov for consistency with your information in the VFS Team Roaster.

**Comment by considerable** [comment]
@szarrougtw you might want to update the comment on your key on your local computer as well, i.e.

```
ssh-keygen -c -f ~/.ssh/id_rsa -C 'samreen.zarroug@va.gov'
```
