### ISSUE TITLE
Contact Center Review for Flagship Mobile App - Release 2.2

### ISSUE THREAD

**Issue by kellylein** [department-of-veterans-affairs/va.gov-team#57460]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
We will be releasing v2.2 of the Flagship app on 5/9/23.  It will contain 2 new Features: the ability for Veterans to set their Preferred Name and Gender Identity as well as the ability to see their compensation claim Decision Letters.

### Launch Date
05/09/2023

### Version Number
7.1

### Product Guide
[Product Guide v7.1](https://github.com/department-of-veterans-affairs/va.gov-team/blob/aa0fc30a8d5aa5b3c8e18305e9c1832b664dde55/products/va-mobile-app/releases/Call%20Center%20Docs/In%20use%20version/VA%20Mobile%20App%20Product%20Guide%207.1.docx)

### Product Video
NA

### Product Video Transcript
NA

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
The updated draft is ready and shared with VEO.
[VA Mobile App Product Guide 7.1_05092023.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/11357005/VA.Mobile.App.Product.Guide.7.1_05092023.docx)
