### ISSUE TITLE
AWS access for Samreen Zarroug

### ISSUE THREAD

**Issue by szarrougtw** [department-of-veterans-affairs/va.gov-team#57467]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Samreen Zarroug

### Your Email

Samreen.Zarroug@va.gov, samreen.zarroug@thoughtworks.com

### Team, Role, and Company of the target individual

Digital Health Platform, Developer, Thoughtworks

### Product Manager (PM) name and email

Abigail Burton abbie.burton@thoughtworks.com

### Product Owner (PO) name and email

Abigail Burton abbie.burton@thoughtworks.com

### Desired AWS Access

Copy permissions from @yonidoronpeter

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

![transmittal_confirmation](https://user-images.githubusercontent.com/129233422/234646928-5be96bdd-5df0-4e9b-a331-811a81008c27.png)

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by considerable** [comment]
VFS Team Roaster

**Comment by BillChapmanUSDS** [comment]
Access approved,  As per usual, any production access is 3 month limited
