### ISSUE TITLE
GIDS: Upgrade to Ruby v2.6.6

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#5747]
As a developer, I need to upgrade GIDS to Ruby v.2.6.6 so that I can upgrade ruby to the most recent version.

## Assumptions:
1.

## Acceptance Criteria
1. GIDS Ruby is on version 2.6.6.
2. The Readme for the GIDS Repository is updated to reflect version 2.6.6 of Ruby

## Technical Tasks
1. Update Dockerfile
3. Update .ruby-version
4. Coordinate with devops for any additional infrastructure changes
5. Perform smoke testing of GIDS application

## Supporting Artifacts
1. https://dsva.slack.com/archives/CBU0KDSB1/p1580502997380900
2. https://github.com/department-of-veterans-affairs/vets-api/pull/3906
3. https://github.com/department-of-veterans-affairs/vets-api/pull/4103

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/659

When testing in vets-website checking that filters for both non VET TEC and VET TEC is needed as changes were made to use of filters for both search paths

**Comment by sonntag-adam** [comment]
Smoke testing passes along with testing filters on front end.

**Comment by sonntag-adam** [comment]
In staging. Closing story.
