### ISSUE TITLE
[EFSR] review and submit page audit

### ISSUE THREAD

**Issue by amponce** [department-of-veterans-affairs/va.gov-team#57484]
## Issue Description
Audit review and submit page functionality and identify missing elements on EFSR

-------

### Summary

The Enhanced Form (EFSR) lacks several key features present in the Full Form (FSR), most notably in the sections pertaining to household income and spouse information. 

The EFSR does not include fields for employment status, work history, job income, payroll deductions, social security, or additional income. Similarly, it lacks fields for spouse employment, spouse payroll deductions, spouse social security, and spouse additional income.

Overall, the EFSR is less comprehensive than the FSR

#### Household Income

- Employment
    - Your work history 
- Income for your job at (Some job)
    - Gross monthly income 
- Payroll deductions
    - Type of payroll deductions 
- Social Security 
    - Social Security Amount
- Additional Income 
    - Your other income 

#### Spouse Information

- Spouse Employment 
- Spouse Payroll deductions
    - Type of payroll deductions 
- Spouse Social Security 
    - Social Security Amount 
- Spouse Additional Income 
    - Your other income 

#### Household Assets

- Monetary assets 
    - Checking
    - Savings
    - Stocks

#### Household Expenses

- Expenses 
    - How much

#### Household Expenses

- Credit Card Bills 

###  Feature Comparison

Feature | FSR | EFSR
--- | --- | ---
Employment Status | Yes | No
Work History | Yes | No
Job Income | Yes | No
Payroll Deductions | Yes | No
Social Security | Yes | No
Additional Income | Yes | No
Spouse Employment | Yes | No
Spouse Payroll Deductions | Yes | No
Spouse Social Security | Yes | No
Spouse Additional Income | Yes | No
Monetary Assets | Yes | No
Expense List | Yes | No
Credit Card Bills | No | Yes
---
## Tasks
- [x] Audit review and submit page 

## Acceptance Criteria
- [x] Identify missing information

---

**Comment by amponce** [comment]
### FSR / EFSR side by side comparison


#### Screenshots

<table>
  <tr>
    <th>FSR Expanded</th>
    <th>EFSR Expanded</th>
  </tr>
  <tr>
 <td >
      <img src="https://user-images.githubusercontent.com/3916436/236890415-9a69b08c-ea3b-4322-b3cd-7ce044815214.png" alt="Screenshot 1" width="600" />
    </td>
    <td style="vertical-align: top">
      <img src="https://user-images.githubusercontent.com/3916436/236894436-bd2eb1dc-b077-4feb-89bd-15b52ebbdd41.png" alt="Screenshot 2" width="600"/>
    </td>
  </tr>
</table>

**Comment by amponce** [comment]
Added summary for missing features in EFSR compared to FSR in the issue description

**Comment by amponce** [comment]
@HeatherRienks After talking to @Dr-Pongo, I think the next step is to coordinate a conversation with design to triage the missing features.

Rough agenda for the conversation would be:

1. Prioritize the Missing Features as a group
2. Break Down into Sub-Tasks
3. Set a Timeline for completion

**Comment by HeatherRienks** [comment]
@amponce  & @Dr-Pongo - Sounds like a plan! Thanks for putting the agenda together.
Let's plan to use our FSR Weekly Team Check-In on Tuesday, 5/16 at10amPT. The entire team will be back in the office. Added to our agenda!

**Comment by HeatherRienks** [comment]
Per 5/16 FSR mtg, we will test, then revisit this. Closing this ticket and will create a follow on ticket.
