### ISSUE TITLE
Go through setup of VA.gov application locally

### ISSUE THREAD

**Issue by accbjt** [department-of-veterans-affairs/va.gov-team#575]
We need to go through the setup of VA.gov locally to make sure our documents are complete and easy to use. Here is the list of things we need to verify:

- Proxy setup
- Installation of front-end
- Installation of back-end (Docker)
- Installation of back-end (Native)

Peter is using --
Windows 10 Pro 64-bit Update 1903
16GB RAM

**Comment by peterhill-oddball** [comment]
I'm stuck on the "Configure SOCKS proxy" step.  Specifically, I don't seem to be able to create a pull request on the devops repo.  Perhaps, I am set to read only?
![image](https://user-images.githubusercontent.com/52456633/61216452-625fb980-a6db-11e9-9b76-447513ba4729.png)

**Comment by peterhill-oddball** [comment]
I'm pursuing additional repository permissions with Nancy.

**Comment by accbjt** [comment]
@peterhill-oddball What branch are you using. Maybe I can do a PR for you. This is definitely a blocker for teams on-boarding. Thanks for going through this exercise.

**Comment by peterhill-oddball** [comment]
@accbjt - I'm following the link provided in the "Configure the SOCKS proxy" section of the getting started documentation -- [Link](https://github.com/department-of-veterans-affairs/devops).

Robert Henrikson has granted me access to the "vets.gov-write" team, and I am still unable to create a pull request on that linked repo.  I must be doing something wrong...

**Comment by accbjt** [comment]
note: TJ Rice should be the go to person for DevOps and slack channel is vsp-operations.

**Comment by peterhill-oddball** [comment]
Permissions issues resolved.

**Comment by peterhill-oddball** [comment]
It looks like this part of the installation assumes that the user is on some kind of *nix / MacOS --
![image.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/9a1ecd62-13d2-4f07-8eff-d8098bc42bc7)

I used PuTTY / PuTTYGen to create a public / private key pair.

**Comment by accbjt** [comment]
@peterhill-oddball I think a better solution then PuTTY on Windows is the Ubuntu Subsystem or using something like GitBash. PuTTY works but having a linux system will help with setting up your development environment also. Windows makes the Ubuntu subsystem available natively so I think you just need to update the settings and install it.

Here is a tutorial on how to setup the Ubuntu subsystem on Windows

https://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/

You can also install GitBash. I have noticed the Ubuntu subsystem being slow so sometimes GitBash works better.

https://gitforwindows.org/

**Comment by peterhill-oddball** [comment]
@accbjt Excellent, I'll give the Ubuntu subsystem a try since I know and like Ubuntu.

**Comment by peterhill-oddball** [comment]
Per Bill's advice, I've installed Ubuntu subsystem for Windows 10.  It looks like 'pbcopy' is a MacOS specific thing.
![image.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/ab9319fe-c2a9-4e15-bb2e-7c339a9d3dcc)

**Comment by peterhill-oddball** [comment]
I used tail instead --
![image.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/7ad2fab2-6198-4938-a87c-3fd1a7edea6a)

**Comment by accbjt** [comment]
@peterhill-oddball yeah that works. Your going to want to find the Ubuntu version of our docs. We definitely need to update this to add Linux setup. I also want to mention that the windows file system live in `/mnt` file in the Ubuntu subsystem.

**Comment by peterhill-oddball** [comment]
@accbjt Ubuntu version of the docs?

Also, there appears to be a typo in the SOCKS proxy configuration.  At least in Ubuntu, the -K option doesn't exist.  The lowercase -k does though.

![image.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/706191a0-ee42-4d39-9561-656a171cc043)

**Comment by peterhill-oddball** [comment]
There appears to be a bug with Windows 10 Linux subsystems that prevents the use of the SOCKS proxy with the error message: "ssh: connect to host socks port 22: Resource temporarily unavailable"

This article discusses a hack to workaround the issue: https://superuser.com/questions/1098526/windows-10-linux-subsystem-ssh-client-resource-temporarily-unavailable

**Comment by accbjt** [comment]
@peterhill-oddball Thanks, that will help when we start updating the docs for a linux setup

**Comment by peterhill-oddball** [comment]
When I curl'ed the test URL, I got a 301 response "Move Permanently".
![image.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/35972fb2-c71e-4bc2-a354-125f1360bb98)

**Comment by accbjt** [comment]
@peterhill-oddball I think there were some recent changes. These changes probably have not been updated in the docs. Let me let operations know and they can probably help you out.

**Comment by peterhill-oddball** [comment]
I needed to add my public key to Github before I could clone the required repositories (https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/)

![image.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/e04016c3-0b45-4081-a1e2-d58e6d6b2e3e)

**Comment by peterhill-oddball** [comment]
Probably obvious, but it threw me for a loop for a minute.  You need to run yarn from within the repo that you are trying to get dependencies for, namely vets-website.  Maybe throw in an explicit instruction to navigate into the repo you're building before running 'yarn install' and 'yarn watch'.

![image.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/9bf211b1-e076-439d-8c2a-7347f6f2cb22)

**Comment by peterhill-oddball** [comment]
I have the front-end up and running.  It's not terribly slow running from Windows Subsystem Linux.

Chrome dev tools shows the homepage loading in about 1200ms, and clicking around shows most other pages loading in about the same amount of time.

The 'node' process is using about 2.2GB of RAM and almost no CPU/Disk.

**Comment by accbjt** [comment]
Cool, I think you probably have a decent enough computer to handle it. That's great. Was worried a little bit with getting this working on Windows. I don't think we have anyone using Windows on the team.

**Comment by peterhill-oddball** [comment]
I am unable to install the exact version of Ruby called out in the "native" back end installation documentation -- (https://github.com/department-of-veterans-affairs/vets-api/blob/master/docs/setup/native.md).
![image.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/8dbed933-434d-484a-8ecc-d08df45270c7)

`rbenv install --list`  --
 ![image.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/9c0c80ab-bb0b-41ce-a382-e6749ce08cf8)

According to Ubuntu's package manager I have the latest versions of ruby-build and rbenv --
![image.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/8a5f371c-d8dd-4725-9c3b-96940260e667)

**Comment by peterhill-oddball** [comment]
I need to specifically call the version of bundle that I manually installed because Ubuntu appears to have come with a version already installed that throws error messages at me.

![image.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/baaf6e0c-df8f-4f7a-8d3b-c797deb45db4)

Unfortunately, it seems like running bundle is attempting to pull down sidekiq files to which I do not have access.  I'm not sure why it is doing that since it looks like the gemfile is only going to do that if I am attempting to deploy to production.
![image.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/436ede22-1d7c-4568-b307-c18199072569)

**Comment by accbjt** [comment]
@peterhill-oddball Yeah I think that might be something you need to add to your .bashrc file so it uses the rbenv one.

Here is a reference on how to set that EXCLUDE_SIDEKIQ_ENTERPRISE option

https://github.com/department-of-veterans-affairs/vets-api#authentication-required-for-enterprisecontribsyscom

**Comment by peterhill-oddball** [comment]
@accbjt 

Per your suggestions, I created a bashrc alias for my manual bundle installation instead of the Ubuntu package and set that exclude parameter to true while installing.  I don't see any error messages reported however, when I proceed to step 6 "Install overcommit", the command is not found.  I tried Googling around, but the internet is filled with people discussing memory management and not any kind of binary named Overcommit.  I'm a bit lost!

Also, the link to the certificates/keys in step 7 appears to be broken.
https://github.com/department-of-veterans-affairs/vets.gov-team/tree/master/Products/Identity/Files_From_IDme/development-certificates

**Comment by peterhill-oddball** [comment]
I switched to trying the Docker setup, and I'm stuck again --
![image.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/c432bd5d-28bf-4978-b7c3-111c006812ad)

I used this pretty great write-up to get the Docker within WSL to be able to connect to Windows Docker Desktop.
https://nickjanetakis.com/blog/setting-up-docker-for-windows-and-wsl-to-work-flawlessly

**Comment by peterhill-oddball** [comment]
As an aside, I got the Front-end and Docker Back-end up and running on my Early 2013 MacBook Pro with 8GB RAM in about 90 minutes -- sigh.

**Comment by peterhill-oddball** [comment]
I created a short document indicating the deviations from the standard set of documentation in Windows.[https://app.zenhub.com/files/133843125/063ff81c-7078-46e4-9ff6-0a59edca070f/download](https://app.zenhub.com/files/133843125/063ff81c-7078-46e4-9ff6-0a59edca070f/download)

**Comment by andreahewitt-odd** [comment]
@gunsch Peter is blocked on this ticket and needs help from a technical person. Who can help him in Bill's absence? CC @peterhill-oddball

**Comment by gunsch** [comment]
can someone from @department-of-veterans-affairs/backend-review-group who knows about the build take a look at ^? (cc @annaswims to triage as needed)

**Comment by jholton** [comment]
re: installing Ruby 2.4.5
I tried your steps on my local Linux machine and had the same issue as you.  Apparently the versions of `rbenv` and `ruby-build` that you get from `apt` are both out of date.  
The following worked for me:

Uninstall `rbenv` and `ruby-build` that you got via `apt`:
`sudo apt remove ruby-build rbenv`

Install using the curl command found [here](https://github.com/rbenv/rbenv-installer#rbenv-installer):
`curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-installer | bash`

Note, per the output from the installations I had to add the rbenv directory to my PATH. In my case that meant adding this to my `.bashrc` file:
`export PATH="/home/johnny/.rbenv/bin:$PATH"`



Now you should see a current list of Ruby versions when you run `rbenv install -l`

**Comment by peterhill-oddball** [comment]
@jholton -- Nice!  That did solve the mystery of the missing Ruby version.  I had guessed that Ubuntu's package manager simply had an outdated version, but instead of trying to manually install rbenv, I went down the path of trying to update the listing in the version installed by the package manager.  That did not go well.

That cleared the logjam for the "native back-end", but I still have my issues with attempting to use Docker via Windows Subsystem for Linux.  Do you have any experience/suggestions with such a setup?

**Comment by jholton** [comment]
@peterhill-oddball for Docker setup, did you try `EXCLUDE_SIDEKIQ_ENTERPRISE=true make rebuild`?

**Comment by peterhill-oddball** [comment]
@jholton That portion of the Docker setup seems to work just fine.  I get --
`peter@THEFLOOD:~/repos/vets-api$ EXCLUDE_SIDEKIQ_ENTERPRISE=true make rebuild
WARNING: The BUNDLE_ENTERPRISE__CONTRIBSYS__COM variable is not set. Defaulting to a blank string.
Removing network vetsapi_default
WARNING: Network vetsapi_default not found.
WARNING: The BUNDLE_ENTERPRISE__CONTRIBSYS__COM variable is not set. Defaulting to a blank string.
redis uses an image, skipping
postgres uses an image, skipping
Building vets-api
Step 1/14 : FROM ruby:2.4.5-slim-stretch
 ---> b730e88a4239
Step 2/14 : ARG sidekiq_license
 ---> Using cache
 ---> d094a49eba7f
Step 3/14 : ENV BUNDLE_ENTERPRISE__CONTRIBSYS__COM=$sidekiq_license
 ---> Using cache
 ---> c28f2bbb7247
Step 4/14 : ARG exclude_sidekiq_ent
 ---> Using cache
 ---> 609ec7014819
Step 5/14 : ENV EXCLUDE_SIDEKIQ_ENTERPRISE=$exclude_sidekiq_ent
 ---> Using cache
 ---> 5e6b7e07607a
Step 6/14 : ENV APP_PATH /src/vets-api
 ---> Using cache
 ---> dc3392d590a0
Step 7/14 : RUN groupadd -r vets-api && useradd -r -g vets-api vets-api && apt-get update -qq && apt-get install -y build-essential git libpq-dev libgmp-dev clamav imagemagick pdftk poppler-utils && freshclam
 ---> Using cache
 ---> a21012684646
Step 8/14 : WORKDIR $APP_PATH
 ---> Using cache
 ---> a330d08ecd9a
Step 9/14 : ADD . /src/vets-api
 ---> 20c5ae53aa23
Step 10/14 : COPY ./docker-entrypoint.sh /
 ---> e60de15d8e99
Step 11/14 : RUN chmod +x /docker-entrypoint.sh
 ---> Running in 04777e153869
Removing intermediate container 04777e153869
 ---> fc4670d1189d
Step 12/14 : ENTRYPOINT ["/docker-entrypoint.sh"]
 ---> Running in 39b53c04d447
Removing intermediate container 39b53c04d447
 ---> e98f8573c780
Step 13/14 : ENV BUNDLE_PATH=/bundle     BUNDLE_BIN=/bundle/bin     GEM_HOME=/bundle
 ---> Running in b0021fbeaac2
Removing intermediate container b0021fbeaac2
 ---> 8eb109e68218
Step 14/14 : ENV PATH="${BUNDLE_BIN}:${PATH}"
 ---> Running in 0009114fa5e7
Removing intermediate container 0009114fa5e7
 ---> 1d6be93458b5
Successfully built 1d6be93458b5
Successfully tagged vets-api:latest`

However, using `make up` after that generates some error messages regarding Gemfiles --
`peter@THEFLOOD:~/repos/vets-api$ make up
WARNING: The BUNDLE_ENTERPRISE__CONTRIBSYS__COM variable is not set. Defaulting to a blank string.
Starting vetsapi_redis_1 ... done                                                                                       Could not locate Gemfile
Could not locate Gemfile
Makefile:31: recipe for target 'db' failed
make: *** [db] Error 10`

**Comment by jholton** [comment]
What is the output of the following?

**Comment by peterhill-oddball** [comment]
>peter@THEFLOOD:~/repos/vets-api$ which ruby
/home/peter/.rbenv/versions/2.4.5/bin/ruby
peter@THEFLOOD:~/repos/vets-api$ which gem
/home/peter/.rbenv/versions/2.4.5/bin/gem

**Comment by jholton** [comment]
I don't think you need that last PATH export for Ruby.
Try this:
* Remove that last `export PATH` line.
* add `eval "$(rbenv init -)"` to that file (.bashrc?)
* `source` that file (e.g. `source ~/.bashrc`)
* `rbenv rehash`
* `rbenv global 2.4.5`
* run `which ruby` and `which gem` again to make sure the values look right
* `gem install bundler -v 1.17.3`

and if all that ran fine, try `make up` again.

**Comment by peterhill-oddball** [comment]
Removed --
![image.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/337fa08a-3cf3-4041-814e-ea9595552820)

Performed subsequent steps --
![image.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/f9a8a2d9-a22c-40cf-be1c-cd3242c8b481)

The `which` shows that the directory has switched to a shim now.  I'm not sure if that is desirable or not.

**Comment by jholton** [comment]
I'm assuming that's the `vets-api` repo directory, but can you verify that it does contain a `Gemfile` file?

**Comment by peterhill-oddball** [comment]
![image.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/b1501d89-3f95-4674-9cff-01dc5b80c3bc)

**Comment by jholton** [comment]
Figured.  `Could not locate Gemfile` is the real error.
`recipe for target 'db' failed` is spat out when any error occurs during that `make` command.
So, why can't it find the `Gemfile`?
I'm grasping here, but try it with sudo.  `sudo make up`

**Comment by peterhill-oddball** [comment]
That's a bit of progress, I think.  I recently wiped the WSL and started over, so I haven't made the configuration changes that allow WSL to connect to Docker Desktop running in Windows.  Perhaps that is the overall problem.  However, even when I had made those configuration changes previously, I couldn't get the Docker back-end to start up.

Still, I'm going to try these steps -- https://nickjanetakis.com/blog/setting-up-docker-for-windows-and-wsl-to-work-flawlessly -- to get WSL to connect to Docker Desktop.

**Comment by peterhill-oddball** [comment]
Ok, when I try `sudo make up` I get --
>WARNING: The BUNDLE_ENTERPRISE__CONTRIBSYS__COM variable is not set. Defaulting to a blank string.
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
Makefile:31: recipe for target 'db' failed
make: *** [db] Error 1

I'm not sure why the error message displays "http+docker://localunixsocket" as I have set the DOCKER_HOST environment variable.  Is this hardcoded in the Makefile?

`echo $DOCKER_HOST`
>localhost:2375


`docker info`
>Client:
 Debug Mode: false

Server:
 Containers: 5
  Running: 2
  Paused: 0
  Stopped: 3
 Images: 50
 Server Version: 18.09.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
 runc version: 09c8266bf2fcf9519a651b04ae54c967b9ab86ec
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.9.125-linuxkit
 Operating System: Docker for Windows
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.952GiB
 Name: linuxkit-00155d007001
 ID: FGGI:BP4Z:ZEO2:SMMT:2WLZ:5GZW:VRTF:YWND:3KR2:R2ZI:PCI2:4E2B
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 22
  Goroutines: 47
  System Time: 2019-07-26T16:20:24.8268041Z
  EventsListeners: 1
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

**Comment by peterhill-oddball** [comment]
The latest issue appears to be that Docker image is being built largely empty --

Digest: sha256:1c5fd456109ccb065d7fccd8e24da18600a35c9db488dcdfa40b2ebc03dab8b5
Status: Downloaded newer image for mdillon/postgis:9.6-alpine
Creating vets-api_redis_1    ... done                                                                                                                                                                               Creating vets-api_postgres_1 ... done                                                                                                                                                                               /src/vets-api
total 4.0K
drwxr-xr-x  4 root root   80 Jul 26 19:19 .
drwxr-xr-x  1 root root 4.0K Jul 26 20:35 ..
drwxr-xr-x  2 root root   60 Jul 26 19:19 .bundle
drwx------ 19   70 root  520 Jul 26 20:36 data
/src/vets-api
WARNING: The BUNDLE_ENTERPRISE__CONTRIBSYS__COM variable is not set. Defaulting to a blank string.
Starting vets-api_redis_1    ... done                                                                                                                                                                               Starting vets-api_postgres_1 ... done                                                                                                                                                                               /src/vets-api
total 4.0K
drwxr-xr-x  4 root root   80 Jul 26 19:19 .
drwxr-xr-x  1 root root 4.0K Jul 26 20:35 ..
drwxr-xr-x  2 root root   60 Jul 26 19:19 .bundle
drwx------ 19   70 root  520 Jul 26 20:36 data
bash: foreman: command not found
Makefile:68: recipe for target 'up' failed
make: *** [up] Error 127

**Comment by smoonpeyes** [comment]
@peterhill-oddball Are you still blocked on this ticket?

**Comment by peterhill-oddball** [comment]
> @peterhill-oddball Are you still blocked on this ticket?

Yes, but I'm not sure there's a ton of value in pursuing a resolution to this ticket.  It's my understanding that it's TBD what the team will recommend for engineers working with a Windows host OS.

If the team decides that instructions for native installation of the front-end and back-end should be created/refined then i would be happy to support that effort.

**Comment by peterhill-oddball** [comment]
It now appears that this method for creating a development environment on a Windows box will not be the preferred method.  Instead, the team will be creating and refining a Vagrant image for use on GFE and general Windows machines.
