### ISSUE TITLE
[Team Workshop] Sprint Roadmapping

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#57518]
## Value Statement
**_As a_** member of the Benefits Decision Review Team
**_I want to_** workshop on a sprint roadmap
**_So that_** we can align on our priorities for the upcoming few sprints

---
## Background Context
The high-level roadmap is ambiguous and doesn't accurately represent what the team is focusing on. We want to work together as a team to figure out what we are prioritizing, and have an accurate view of what's coming down the pipeline.

## Acceptance Criteria
- [ ] An agreed upon sprint roadmap that represents design/research and engineering priorities

## Designs and Build Notes
- Mural

**Comment by saderagsdale** [comment]
- Needs enough info from research and design to be actionable for devs

**Comment by saderagsdale** [comment]
Will write new follow-up tickets.
