### ISSUE TITLE
Accessibility - 1010EZ: Move "Check all that apply" into legend

### ISSUE THREAD

**Issue by davidakennedy** [department-of-veterans-affairs/va.gov-team#57515]
**Issue description**

This is a small change that could improve the experience for Veterans who use screen readers. The "Check all that apply" sits outside of the `<legend>` element, meaning that it doesn't get announced when the `<legend>` text ("Service history") does. Moving the "Check all that apply" into the legend would announce "Military service [pause] check all that apply" It's a better experience because it sets expectations better for the Veteran.

![Military service section with red arrows pointing at "Check all that apply" and the content in the HTML source.](https://images.zenhubusercontent.com/628e7b9093a9366153cb221c/7cd38030-d3ea-43df-954c-2e363a0d2e52)

**Remediation guidance**

Add "Check all that apply" to the legend. It can still appear the same visually.

**Does this impact visual design?**

No.

**Relevant standards**

[2.4.6 Headings and Labels](https://www.w3.org/TR/WCAG21/#headings-and-labels)

**Comment by longmd** [comment]
@davidakennedy , this is in staging and ready for validation.

**Comment by davidakennedy** [comment]
I've validated this. and it works as expected.
