### ISSUE TITLE
SOCKS access for Kyle Drewno (Lighthouse)

### ISSUE THREAD

**Issue by kyle-drewno** [department-of-veterans-affairs/va.gov-team#57511]
### Your Name

Kyle Drewno

### Your Email

kyle.drewno@adhocteam.us

### Your Role and Team

Software Engineer on Lighthouse Cassowary

### Product Manager (PM) name and email

Danielle Baranowski - danielle.baranowski@oddball.io

### Product Owner (PO) name and email

Dave Mazik - david.mazik@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCwlIHSWJtrX99Cqadn2ieMgtzF5Ht+etuWng6vcXRYxxKXy6mdNXFru5zMxULkRQ4llShZn5DQk76N58WT6V0CmccxbMIzXHaWtNUqOBvoq2DCfDZGjq6rsbsYNfKMhDsW7kwqYt+KWMO1dZaWP/uF+5Vcl0ym7syGFYGHQfryigSZquXdi/gtY2oOb/IhHGcNCKfZgcoaLMBQvVp5uD54TVrFygs0MD0dKrgjroLjAoq2Uqvz9H75oQ6rt9F9qlti96xGIT+rwOQib7M+4BqCVWcrU/90h17B3cJ6rPvIjswvEiQ3DyGmvvZr30OA+coJobbwRfmoM6HmWg5eCw5EnFmqtEuPt88Ty+O1yOhd2sdWZ5DqWcIdHNeBZjt64GGGZw2px+MKQMnMdbQrFO423o/las2LJFiDf5LppYhvVTcZXKUibXCrJAbQUM8cBbb0YmyqGqQUxK696Fb4XaBj3vPQiumVrTkys+CCYAWfAKwl1PbcdZpckrL6nQahQ+E= kyledrewno@Kyles-MBP.hsd1.mi.comcast.net

### E-QIP Transmittal Confirmation

![eqip-transmittal](https://user-images.githubusercontent.com/96494232/234677316-d9aada75-b2fb-4e2f-8f2f-96eed9dd2c4c.png)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by flooose** [comment]
@kyle-drewno you should be all set. Let us know if you have any problems.
