### ISSUE TITLE
Audit and Recommend Linting Rules

### ISSUE THREAD

**Issue by brandonrapp** [department-of-veterans-affairs/va.gov-team#5751]
Take a fresh approach at the linting rules we have in place and see if we cannot get to a better recommendation for a standard set of rules that we can use for automatic quality checks.

**Comment by jhonnyoddball** [comment]
### ESLint Audit

**Current Setup up**

```
   "eslint": "^4.18.2",
   "eslint-config-airbnb": "^15.1.0",
   "eslint-config-prettier": "^3.1.0",
   "eslint-import-resolver-babel-module": "^5.0.1",
   "eslint-plugin-fp": "^2.3.0",
   "eslint-plugin-import": "^2.14.0",
   "eslint-plugin-jest": "^21.26.1",
   "eslint-plugin-jsx-a11y": "5.1",
   "eslint-plugin-mocha": "^5.2.0",
   "eslint-plugin-no-unsafe-innerhtml": "^1.0.14",
   "eslint-plugin-prettier": "^2.6.2",
   "eslint-plugin-react": "^7.12.4",
   "eslint-plugin-react-hooks": "^1.6.0",
   "eslint-plugin-scanjs-rules": "^0.1.4",
   "eslint-plugin-va-enzyme": "./script/custom-eslint/va-enzyme",
   "eslint-stats": "^1.0.0",
```

### Plugins

**[ESLint](https://eslint.org/docs/rules/)**
Rules: 267
Currently used: 6

**[fp](https://github.com/jfmengels/eslint-plugin-fp)**
ESLint rules for functional programming
Rules: 17
Currently used: 1

**[Import](https://github.com/benmosher/eslint-plugin-import)**
This plugin intends to support linting of ES2015+ (ES6+) import/export syntax, and prevent issues with misspelling of file paths and import names.
Rules: 42
Currently used: 0

**[Jest](https://github.com/jest-community/eslint-plugin-jest)**
EsLint for Jest testing framework
Rules: N/A

**[JSX-Ally](https://www.npmjs.com/package/eslint-plugin-jsx-a11y)**
Static AST checker for accessibility rules on JSX elements.
Rules: 32
Recommended: 26
Currently used: 0

**[Mocha](https://github.com/lo1tuma/eslint-plugin-mocha)**
EsLint for Mocha testing framework
Rules: N/A

**[No Unsafe InnerHTML](https://npm.taobao.org/package/eslint-plugin-no-unsafe-innerhtml)** **(NOT USED AT ALL)**
This function disallows unsafe coding practices that may result into security vulnerabilities.
Last support 3 years ago
Rules: 2
Currently used: 0
It can be removed or find a better one

**[Prettier](https://github.com/prettier/eslint-plugin-prettier)**
Runs Prettier as an ESLint rule and reports differences as individual ESLint issues.
Rules: Recommended activated
Currently used: Recommended ones

**[React](https://github.com/yannickcr/eslint-plugin-react)**
React specific linting rules for ESLint
Rules: 88
Recommended: 21
Currently used: 9

**[React-hooks](https://github.com/facebook/react/tree/master/packages/eslint-plugin-react-hooks)**
This ESLint plugin enforces the Rules of Hooks.
Rules: 2
Currently used: 2

### Recommended plugin

**[SonarJS](https://github.com/SonarSource/eslint-plugin-sonarjs)**
SonarJS is a static code analyzer for the JavaScript and TypeScript languages, plugin for SonarQube and SonarCloud.
Rules: 25
Currently used: Not installed yet

**Comment by jhonnyoddball** [comment]
### Front-end Meeting:

### Agenda:

**Brainstorm for ESLint.**

- We are currently using 12-30 rules out of maybe 500. It doesn't seem like we are taking advantage of ESLint.
- Go over ESLint audit
- Demo - SonarJS

**Discussion**

- How should we improve it?
- What are the best practices?
- Should we activate all? most? some? or just a few rules?
- How strict we should make it?
- Any new ideas?

**Comment by brandonrapp** [comment]
I had some questions too for the discussion, but only if we time at the end!

- How do we agree on which ones are 'errors' and which are 'warnings'?
- These will be standardized\published rules, does that change your thoughts about which ones we will activate? 
- How would want to handle changes to this list of rules and classification of 'errors' and 'warnings'.

**Comment by jhonnyoddball** [comment]
### SONARJS AUDIT

**Bug Detection**

Rule | Errors | Threshold | Exceptions | Alert | Suggested | Deployed
-- | -- | -- | -- | -- | -- | --
no-all-duplicated-branches | 0 | N/A |   | Error | Yes |  
no-element-overwrite | 0 | N/A |   | Error | Yes |  
no-extra-arguments | 10 | N/A |   | Error | Yes |  
no-identical-conditions | 0 | N/A |   | Error | Yes |  
no-identical-expressions | 14 | N/A |   | Error | Yes |  
no-one-iteration-loop | 0 | N/A |   | Error | Yes |  
no-use-of-empty-return-value | 0 | N/A |   | Error | Yes |  

**Code Smell Detection**

Rule | Errors | Threshold | Exceptions | Alert | Suggested | Deployed
-- | -- | -- | -- | -- | -- | --
cognitive-complexity | 68 | 50 | 4 | Error | Yes |  
max-switch-cases | 3 | 30 (default) | 3 | Error | Yes |  
no-collapsible-if | 22 | N/A |   | Error | Yes |  
no-collection-size-mischeck | 0 | N/A |   | Error | Yes |  
no-duplicate-string | 776 | 10 | 36 | Error | Yes, careful with unit test. Needs more testing |  
no-duplicated-branches | 18 | N/A |   | Error | Yes |  
no-identical-functions | 80 | N/A |   | Error | Yes, careful with unit test. Needs more testing |  
no-inverted-boolean-check | 2 | N/A |   | Error | Yes |  
no-redundant-boolean | 1 | N/A |   | Error | Yes |  
no-redundant-jump | 0 | N/A |   | Error | Yes |  
no-same-line-conditional | 0 | N/A |   | Error | Yes |  
no-small-switch | 11 | N/A |   | Error | Yes |  
no-unused-collection | 1 | N/A |   | Error | Yes |  
no-useless-catch | 0 | N/A |   | Error | Yes |  
prefer-immediate-return | 61 | N/A |   | Error?Warning? | Yes, however, immediate return can be tricky. |  
prefer-object-literal | 0 | N/A |   | Error | Yes |  
prefer-single-boolean-return | 0 | N/A |   | Error | Yes |  
prefer-while | 0 | N/A |   | Error | Yes |

**Comment by jhonnyoddball** [comment]
### Rules staging

 Rule | Batch 1 | Batch 2 | Batch 3
-- | -- | -- | --
no-all-duplicated-branches | X |   |  
no-element-overwrite | X |   |  
no-extra-arguments |   | X |  
no-identical-conditions | X |   |  
no-identical-expressions |   | X |  
no-one-iteration-loop | X |   |  
no-use-of-empty-return-value | X |   |  
cognitive-complexity |   |   | X
max-switch-cases |   | X |  
no-collapsible-if |   |   | X
no-collection-size-mischeck | X |   |  
no-duplicate-string |   |   | X
no-duplicated-branches |   | X |  
no-identical-functions |   |   | X
no-inverted-boolean-check |   | X |  
no-redundant-boolean |   | X |  
no-redundant-jump | X |   |  
no-same-line-conditional | X |   |  
no-small-switch |   | X |  
no-unused-collection |   | X |  
no-useless-catch | X |   |  
prefer-immediate-return |   |   | X
prefer-object-literal | X |   |  
prefer-single-boolean-return | X |   |  
prefer-while | X |   |

**Comment by jhonnyoddball** [comment]
### Rules staging

 Rule | Batch 1 | Batch 2 | Batch 3
-- | -- | -- | --
no-all-duplicated-branches | X |   |  
no-element-overwrite | X |   |  
no-extra-arguments |   | X |  
no-identical-conditions | X |   |  
no-identical-expressions |   | X |  
no-one-iteration-loop | X |   |  
no-use-of-empty-return-value | X |   |  
cognitive-complexity |   |   | X
max-switch-cases |   | X |  
no-collapsible-if |   |   | X
no-collection-size-mischeck | X |   |  
no-duplicate-string |   |   | X
no-duplicated-branches |   | X |  
no-identical-functions |   |   | X
no-inverted-boolean-check |   | X |  
no-redundant-boolean |   | X |  
no-redundant-jump | X |   |  
no-same-line-conditional | X |   |  
no-small-switch |   | X |  
no-unused-collection |   | X |  
no-useless-catch | X |   |  
prefer-immediate-return |   |   | X
prefer-object-literal | X |   |  
prefer-single-boolean-return | X |   |  
prefer-while | X |   |
