### ISSUE TITLE
SOCKS access for Natalia Mashaeva

### ISSUE THREAD

**Issue by mashaeva-va** [department-of-veterans-affairs/va.gov-team#57525]
### Your Name

Natalia Mashaeva

### Your Email

mashaeva_natalia@bah.com

### Your Role and Team

APM Pteracuda & Shanktopus Teams

### Product Manager (PM) name and email

Jessica Sexton, sexton_jessica@bah.com, Adam Foster, foster_adam@bah.com

### Product Owner (PO) name and email

Dave Mazik, david.mazik@va.gov

### Access Type Requesting

viewers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDXwNDHxqH7R7rLM06rqcPb+y0bZnlW8PSZCL9a6/4v1bSWvDvYLY+GX2rZaI52/LL7f/4B9hNgeDtzSRBIYraL4C2prTOQksqWWiHVo2gONxqAm3wS9CPY7ToSsrhpNsMGzXdowTpdMY6gXjG7uMVZT6erzeLaeF9R8jThcFnRTE6GAALxVM7fWwoBuwrd3S+Z6YHyFiY+EvhfHEJarf6GNxICk8iGILxWusxXBFxdeZVq+5YkUBxUCoJ/Zkq3Zwmp/+bL3v5mvkHbc1xXStmONtpcT48s2bASeHxzdmUFTbGAKM9jOslFkbsr3YGJkR3u3chjEP/Jb6Qrmy3KpWY4YFGIFsRt1Sg47+21iuQh2e2cQgqDh1GoA4JSL44B0T/FhqJc7dZYmzxK5/cj8cP7WuGspEk/P+4PqxQlA986uYvRtGt2zjdxltotXvI+aiihLN74FZahTLNCpjOxsEe4rCHQp7vKSunqueKHM5pCt6aewDYTLn/OpcQIWhNtEwE= nmashaeva@BAH5CG0167FQ9

### E-QIP Transmittal Confirmation

![eQIP Transmittal Confirmation](https://user-images.githubusercontent.com/129774384/234704956-2109a48d-273a-4e8f-8bbf-d912b53f497b.JPG)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by mashaeva-va** [comment]
Hello, just wanted to confirm if anything is needed from me to proceed with this request and when will this be approved? Thank you!

**Comment by flooose** [comment]
@mashaeva-va your change went through and you should be able to test with:

```
ssh socks
```

and it should respond similar to:

```
bind [::1]:2001: Address already in use
channel_setup_fwd_listener_tcpip: cannot listen to port: 2001
Could not request local forwarding.
```

If you have any problems, let us know. We can reopen this.
