### ISSUE TITLE
GIDS: Update Data Requirements Display

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#5752]
As an EDU Team Member, I need it to be clear what the data requirements are for each file when uploading so that I can address any reported issues without having to navigate to multiple pages.

## Assumptions:
1. Columns listed are listed by their CSV Column Name

## Acceptance Criteria
1. The formatting of the data requirements help section is formatted using order lists and bullets (see Supporting Artifact # 1 for reference).
2. The data requirements help section is displayed on the file upload success page (see Supporting Artifact # 2 for reference).

## Supporting Artifacts:
1. Format Update:
<img width="520" alt="updated_data_requirements_display" src="https://user-images.githubusercontent.com/48260534/74273498-938a8180-4cde-11ea-8c8f-3d49a31ccc5b.png">
2. Upload Success Page
<img width="1440" alt="upload_success_page" src="https://user-images.githubusercontent.com/48260534/74273661-d3516900-4cde-11ea-81ff-6d960712710a.png">

**Comment by ksantiagomorgan6** [comment]
Pull request: 

https://github.com/department-of-veterans-affairs/gibct-data-service/pull/591

**Comment by sonntag-adam** [comment]
![Accreditation_Action_validate.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/d7e2ab79-04f3-4ce9-959f-4bde74615737)![Accreditation_Action.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/90892493-7b3a-46c2-ae23-3a97d40d73bc)![Accreditation_Institute_Campus_validate.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/ac583a20-cc32-4833-aa14-ed5abd6fb40d)![Accreditation_Institute_Campus.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/5be98700-29a5-4a18-8967-df61f34a5dc6)![Accreditation_Record_validate.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/c565c2af-8141-45f1-b06c-53ca864018a1)![Accreditation_Record.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/e755b364-7117-45a9-b05c-88569db17a9c)![Arf_gi_bill_validate.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/0836451f-bd7f-4f82-801f-d48461d45bce)![Arf_gi_bill.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/38a48604-b271-4b2e-a5d2-0839f033cc09)![Calculator_constant_validate.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/c91927c5-5f36-4512-b23b-c9e28f36b396)![Calculator_constant.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/723d177b-6890-420c-8285-d77290e7a7aa)![Complaint_validate_statuses_closedreasons.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/9dd082b2-046c-4e4e-917e-db2070cdd39f)![Complaint_validate.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/0888bb69-8bac-4ca8-9370-8704dca8fe0b)![Complaint.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/9e028ccf-07f9-4759-8a25-ec31cb6915d8)![Crosswalk_validate.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/c05e8aa2-cf50-4e1f-aa22-9147004add24)![Crosswalk.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/cbbb165b-7680-48ed-b9df-a4f77d8ab9c0)![Edu_program_validate_validator.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/9cf1e2de-74d1-478b-ac72-1a3800bfb52b)![Edu_program_validate.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/08699b6a-7011-4d16-b516-150b856a552b)![Edu_program.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/122446b9-526c-49b6-a7c8-ed2e306a4381)![Eight_key.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/502b3441-d68b-4f3b-bb6b-ec8106bbb2c9)![Hcm_validate.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/c903e767-345e-41cb-a596-7950bf88af62)![Hcm.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/f6080c4b-e3fb-4625-91ab-4fd091530c46)![Ipeds_cip_code_validate.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/849d8066-c94a-494a-aabf-65cb5d68bbee)![Ipeds_cip_code.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/81a8c66d-8e9a-450c-8e32-4173d529fe51)![Ipeds_hd_validate.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/af0dbcef-03a2-415b-a176-0f5714827f4a)![Ipeds_hd.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/2035179f-9959-4c6b-8169-540b6c98d589)![Ipeds_ic_ay_validate.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/f166d6be-c8f6-4226-bb62-afed1c18a8d0)![Ipeds_ic_ay.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/e1aec1c4-0856-4d8f-ae2d-be0f7e87e0be)![Ipeds_ic_py_validate.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/33b60ef6-d2f4-46c4-987d-9b7feb8759c7)![Ipeds_ic_py.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/c79c3aba-58f2-4c40-9d79-563df121c412)![Ipeds_ic_validate.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/df019294-f514-4f97-a014-241422c5210b)![Ipeds_ic.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/11b1337e-407c-429d-b78d-23e78da5ff31)![Mou_validate.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/4ead0e93-60bb-46a8-95a1-c8da44f3a857)![Mou.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/1e607cf1-c798-476b-8c00-cb79bf016d2e)![Outcome_validate.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/a4684ac6-5181-47ca-b25f-7f2fdae0aa79)![outcome.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/3ecaed57-ba73-4c29-923c-07dadaa0de1f)![p911_tf_validate.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/62d78db2-dc09-4797-8e51-bfad8d7be931)![p911_tf.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/337c71ef-86ea-452d-9a57-efed607437f2)![p911_yr_validate.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/2309b1e1-1764-4d3d-9735-612c15578efa)![p911_yr.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/029177f5-d188-414d-9792-af49aa8ea04d)![program_validate_type.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/9cb69bd3-abee-439f-a2e3-f015fb204a4d)![Program_validate.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/c4a8f39b-cf72-414c-b2b2-56fc4beefd88)![Program.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/2c1c7abd-af8d-4a7a-8fd2-7c92d8dab463)![School_certifying_official_validate.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/c3ddfc34-d4cf-469c-b0ec-61b2af294db9)![School_certifying_official.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/607bbf13-b583-4216-98ef-1f4e5273922d)![School_closure_validate.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/d2ae3f58-77bd-4bb6-b6a6-ac660432b7b5)![School_closure.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/c114c652-8dc3-4cb8-a2ea-d199ca7c352b)![Scorecard_validates.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/2d38232d-bcc9-4cf3-8291-93e696a425aa)![Scorecard.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/d9a7058b-87fd-41c5-87c6-e288d3e356d2)![Sec109_closed_school_validate.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/c4a9e2f0-9555-4475-b8b1-d1850cbb9a93)![Sec109_closed_school.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/12904aac-14c1-4c5f-933f-d86b40d2e2e6)![Sec702_school_validate.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/7c109f82-1036-4b7f-8840-4c9fa8f87124)![Sec702_school.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/f234ac2e-c32c-4494-bcc5-495a57761159)![Sec702_validate.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/9e01296d-b877-4e68-9970-5a46aac5a795)![Sec702.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/b5b755b1-adc3-4b66-9b3f-225ddf60b061)![Settlement_validate.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/59df7199-a590-40fa-9647-bfd23183ee70)![Settlement.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/852ed4cd-e6ec-49ec-b810-d8da4602d301)![Stem_cip_code_validate.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/c69f95a2-67bf-4c99-8770-7ee99529fd1c)![Stem_cip_code.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/046854ff-5556-4f62-b19f-a8bfe9c26de4)![SVA_validate.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/3145becb-6dd3-41c6-81c1-088807e671cc)![SVA.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/03f64272-c7d4-4d57-a9b6-a81c357d6d1f)![vsoc_validate.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/42b0fb8b-b5ea-46f6-9798-a556e3379173)![vsoc.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/8468c273-e6a7-4907-a63d-5a6469be1a11)![weam_validates.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/594ea1c0-f592-434a-939d-9b93fe1adec6)![weam.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/5bcf10e0-8405-4c38-83f9-fd17cb2cf845)![Yellow_ribbon_program_source_validate.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/42e6eabe-5afa-4fb0-b118-894b49f20c96)![Yellow_ribbon_program_source.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/b45c428d-ecfc-462d-99cb-8e90a07798b3)

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-02-27 at 11.52.39 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/0c3b3d5b-dc5d-4535-81b3-bdbb38bae881)

**Comment by sonntag-adam** [comment]
Testing passes https://dsvavsp.testrail.io/index.php?/runs/view/201&group_by=cases:section_id&group_order=asc

**Comment by sonntag-adam** [comment]
In staging. Closing story.
