### ISSUE TITLE
Decision Review pages: Remove anomalies 

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#5753]
# Decision Review pages: Capture anomalies & recommendations for addressing

This is follow on work that should happen _after_ ticket #5541 is completed. It is interrelated to other tickets to updating the DR/AMA pages (like adding left nav; determining any updates to the IA). 

__Problem description:__
The Decision Review pages are currently live on GH. During benefit hub migration into the CMS in 2019, these DR pages could not be migrated because they had too many content anomalies. 

__Action:__ 
In order to move these pages into Drupal, we first need to identify anomalies, recommend how to address them, and inform SMEs. 

__Checklist:__

- [x] Meet with @kevwalsh to identify anomalies
- [x] Recommend fixes for  anomalies
- [x] Create presentation for SMEs
- [x] Get final internal approval on presentation
- [x] Present to SMEs

__Pages:__

1. VA decisions reviews and appeals https://www.va.gov/decision-reviews/
2. After you request a decision review https://www.va.gov/decision-reviews/after-you-request-review/
3. File a Supplemental Claim with new evidence  https://www.va.gov/decision-reviews/supplemental-claim/
4. Request a Higher-Level Review https://www.va.gov/decision-reviews/higher-level-review/
5. Request a Board Appeal https://www.va.gov/decision-reviews/board-appeal/
6. After a Board Appeal ... https://www.va.gov/decision-reviews/board-appeal/after-board-appeal-decision/
7. Multiple party contested claims https://www.va.gov/decision-reviews/multiple-party-claims/
8. Fiduciary claims https://www.va.gov/decision-reviews/fiduciary-claims/
9. Insurance claims https://www.va.gov/decision-reviews/insurance-claims/
10. FAQs https://www.va.gov/decision-reviews/faq/
11. Get help with... https://www.va.gov/decision-reviews/get-help-with-review-request/

**Comment by jenniferlee-dsva** [comment]
@MickinSahni - ^ fysa. The various Decision Reviews tickets might be good to collect under a new epic.

**Comment by MickinSahni** [comment]
> @MickinSahni - ^ fysa. The various Decision Reviews tickets might be good to collect under a new epic.

Thanks, @jenniferlee-dsva. What would be the overarching problem to solve that I can add to that new epic? Or should this be converted to an epic?

**Comment by jenniferlee-dsva** [comment]
Adding @AkucherGCIO for awareness - this work (along with adding Decision Review pages to IA/nav) should be picked up in the upcoming spring, upon go live of #5541.

**Comment by jenniferlee-dsva** [comment]
We probably need an epic :-)

**Comment by AkucherGCIO** [comment]
02-27-20 PW Standup
Call with Kevin Walsh on Monday

**Comment by AkucherGCIO** [comment]
03/04/20 PW Grooming
@lwalsh617 - based on the research being done on anomalies, please update the estimate for this ticket.

**Comment by lwalsh617** [comment]
@jenniferlee-dsva -- For your review:  Here is a Word doc that captures changes we're proposing to address anomalies. 
[decision-review-page-anomalies-and-recommendations.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4314405/decision-review-page-anomalies-and-recommendations.docx)

**Comment by AkucherGCIO** [comment]
03/11/20 Sprint 17 Planning
@AkucherGCIO - Need a new ticket for migration of Decision Review Pages for Drupal.  
@lwalsh617 - Will close this ticket after feedback from @jenniferlee-dsva on 3/11/20.

**Comment by lwalsh617** [comment]
@RLHecht Per our Slack chat: at the top of this ticket, I added check boxes to the numbered list of pages that are moving so we can track which ones are done.

**Comment by lwalsh617** [comment]
@jenniferlee-dsva @mnorthuis @RLHecht -- Here's the document for Monday SME call (does not include Mikki's IA recommendations.) LMK if you have questions/feedback. 
Thank you!
[decision-review-page-anomalies-and-recommendations_031320.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4330693/decision-review-page-anomalies-and-recommendations_031320.docx)

**Comment by MickinSahni** [comment]
> 03/11/20 Sprint 17 Planning
> @AkucherGCIO - Need a new ticket for migration of Decision Review Pages for Drupal. Another ticket for creating a new hub page. Another ticket for updating Hub and Nav.
> @lwalsh617 - Will close this ticket after feedback from @jenniferlee-dsva on 3/11/20.

Safe to close this out, @lwalsh617 @jenniferlee-dsva ? Looks like the other tickets have already been created.

**Comment by MickinSahni** [comment]
2020-03-16 PW Standup
* Closing this out!
