### ISSUE TITLE
turn on global downtime notification 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#5754]
- Rollback the changes in this PR: https://github.com/department-of-veterans-affairs/vets-website/pull/11626/files
- configure the global downtime for thursday 2020 Feb 13 @ 2100-2130 EST
- validate on staging (work with Rian on this)

**Comment by rianfowler** [comment]
Testing: 

- locally you can test this by just not running the vets-api with the vets-website watch task. the call to /maintenance_windows and /backend_statuses will automatically fail
- set your system time to the time configured
- navigate to the facility locator ( /find-locations)
  - this will trigger the call to maintenance_windows which will fail and trigger the downtime notification to display on the page (<- validate this occurs)
- click sign in
  - this will trigger the call to /backend_statues which will fail and trigger the downtime notification to display in the modal (<- validate this occurs) 

On staging you can accomplish a similar effect by blocking the call in the network tab. 

![Screen Shot 2020-02-12 at 17 25 41](https://user-images.githubusercontent.com/4998130/74383183-bc814400-4dbc-11ea-8591-2e6eae5e58a8.png)

_Long term we would be able to simulate the failure more accurately so we can improve the experience. for example, the upgrade prompting this downtime is going to cause the database to be down. this kind of failure doesn't trigger a timeout for 30+ seconds._

**Comment by Clark-W-Griswold** [comment]
Thank you @rianfowler! I did some testing around this following your instructions. After a bit of debugging, I found the following method in the `LOADING_BACKEND_STATUSES` action which prevented the banner from showing. 
```
!environment.isLocalhost()
```

When commented out, we get the desired banner.  Going to review the code after some rest tonight and will make the PR first thing in the morning.

**Comment by Clark-W-Griswold** [comment]
Verified on staging:
![image](https://user-images.githubusercontent.com/6521723/74560177-ff195c80-4f33-11ea-8218-474a0e4dfc11.png)

**Comment by Clark-W-Griswold** [comment]
Verified on prod:
![image](https://user-images.githubusercontent.com/6521723/74564615-544d7200-4f24-11ea-9837-39773e07fd36.png)

**Comment by peggygannon** [comment]
@rianfowler Hello, can we update this message to show the time in regular time not military time? 

12:30 should be rendered 9:30 p.m. EST

**Comment by Clark-W-Griswold** [comment]
Updated to have modal format date to 12 hour format:
![image](https://user-images.githubusercontent.com/6521723/74569482-5d900c00-4f2f-11ea-9515-84613a07ef79.png)
