### ISSUE TITLE
Deploy New EKS Control Plane

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#57547]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)

## High Level User Story/ies
As an engineer on VSP, when deploying a new version a control plane is automatically deployed and I am able to connect to it via kubectl

## Hypothesis or Bet
If we make the change to deploy our new Control plane with every cluster, it will help in our automation of deploys and teardowns [per our overall objective](https://app.zenhub.com/workspaces/platform-tech-team-2-633efe4ca5a428e5294d7ade/issues/gh/department-of-veterans-affairs/va.gov-team/50671)

## Definition of done
- The new plane can be deployed and torn down via kubectl
- You can verify all resources are up and running via kubectl (worker nodes, aws resources, etc...)

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `Console-Services`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by EWashb** [comment]
@npeterson54 I'd like to work with you to get this epic info filled out so we make sure we are working towards the correctly scoped goal.

**Comment by npeterson54** [comment]
This is complete
