### ISSUE TITLE
GitHub Actions to Apply and tear down Terraform resources

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#57550]
## Product Outline
- https://github.com/department-of-veterans-affairs/vsp-platform-infrastructure/tree/main

**Comment by ph-One** [comment]
This work was completed shortly after creating this ticket. https://github.com/department-of-veterans-affairs/vsp-platform-infrastructure/commit/22cde68b57ddf388767556b2e51b25ce6d876d81
