### ISSUE TITLE
[GitHub Action] Rename Master to Main and Protect

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#57555]
## Description
All repos must use `main` as their primary branch; rename accordingly.

## Resources 
- https://github.com/department-of-veterans-affairs/vsp-platform-infrastructure

## Acceptance Criteria
- [ ] The primary branch is named `main`
- [ ] The `main` branch is protected [from directly committing to]

## Refinement Guidance - Check the following before working on this issue: 
- [x] _Team label assigned ("platform-tech-team-2")_
- [x] _Epic assigned (if needed)_ 
- [x] _Estimated (points assigned)_
- [x] _Sprint assigned (once planned)_
- [x] _Team member(s) assigned_

**Comment by ph-One** [comment]
Renamed `master` to `main`

**Comment by ph-One** [comment]
Only allowing squash merges to enforce conventional PR titles that will later generate tags and releases

**Comment by ph-One** [comment]
No force pushing. Require PR and approvals before merging.
