### ISSUE TITLE
[Documentation] Standards and Best Practices

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#57554]
## Description
For best long-term maintenance and consistency in the system we need to establish naming conventions, standards, and best practices for the work that we do.

## Notes
- Naming conventions
- GitHub Action best practices (i.e., using parameters, allowing for manual triggering, etc.)

## Acceptance Criteria
- [x] Documentation is captured within the `vsp-platform-infrastructure` repo (this can live as a PR until discussed with team)
- [x] Document and discuss with the team your thoughts on standards and naming conventions
- [x] Create follow-on tickets for GitHub Actions that will enforce these standards and practices
- [x] Audit for compliance of all past project work
  - [x] Create follow-on tickets for any remediation that is needed

## Refinement Guidance - Check the following before working on this issue: 
- [x] _Team label assigned ("platform-tech-team-2")_
- [x] _Epic assigned (if needed)_ 
- [x] _Estimated (points assigned)_
- [x] _Sprint assigned (once planned)_
- [x] _Team member(s) assigned_

**Comment by hgbarreto** [comment]
Follow-on Tickets
- [ ] Standardizing Tags and Names with terraform-null-label module
   -> https://oddball.slack.com/archives/C044WM9PBMY/p1684344931123699
