### ISSUE TITLE
[GitHub Action] Add a cron action to apply github actions

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#57559]
## Description
Create a GitHub Action that checks for terraform/infrastructure drift on a set schedule.

## Notes
- There may be an existing Action that can be called to run a `terraform plan` against a given branch (parameter) #57553
- The Slack notification will temporarily be assigned to the Tech Team 2 channel until a more permanent home is decided

## Acceptance Criteria
- [x] Cron schedule: Nightly at 3am EST
- [ ] ~~Perform a `terraform plan` (to detect drift) by calling an existing Action that makes this call against a tree-ish~~
- [x] Send a Slack notification to Oddball #platform-tech-team-2

## Refinement Guidance - Check the following before working on this issue: 
- [x] _Team label assigned ("platform-tech-team-2")_
- [x] _Epic assigned (if needed)_ 
- [x] _Estimated (points assigned)_
- [x] _Sprint assigned (once planned)_
- [x] _Team member(s) assigned_

**Comment by hgbarreto** [comment]
The cron action is complete - the team has decided to add the acceptance criteria item (calling an existing Action) to this [issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/57553)

**Comment by hgbarreto** [comment]
The PR was review by the teaming - closing out.
