### ISSUE TITLE
GIDS: Research adding feature flag / prod flag support.

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#5755]
As a developer, I need to determine if it is possible to add feature flag / prod flag support to GIDS so that we can avoid a backlog of pull requests to deploy to production.

## Assumptions:
1. 

## Acceptance Criteria
1. Documentation outlining an implementation plan for feature or prod flags is created OR documentation outlining why adding feature / prod flags is not feasible.

**Comment by zurbergram** [comment]
put something that is defined in each of the files in https://github.com/department-of-veterans-affairs/gibct-data-service/tree/master/config/environments and let the ruby config gem handle it
