### ISSUE TITLE
Accessibility - 1010EZ: Increase specificity of aria-label in insurance section

### ISSUE THREAD

**Issue by davidakennedy** [department-of-veterans-affairs/va.gov-team#57563]
**Issue description**

The current `aria-label` for the Edit button on added insurance plans is: `aria-label="Edit Provider 1234`. Where Provider is the insurance company and 1234 is the  policy number. The label is pretty solid, but I think it could be more informative. Currently, it's hard to know what the number may connect to when reading it.

![Insurance screen with Edit button and red arrows pointing to it and the aria-label in the HTML source code.](https://images.zenhubusercontent.com/628e7b9093a9366153cb221c/1d98900b-99fc-494d-b714-67b15ed2e42c)

**Remediation guidance**

Some recommendations: Change `aria-label="Edit Provider 1234`:

`aria-label="Edit Provider, Policy number 1234` or `aria-label="Edit Provider, Group number 1234`

**Does this impact visual design?**

No.

**Relevant standards**

[2.4.6 Headings and Labels](https://www.w3.org/TR/WCAG21/#headings-and-labels)

**Comment by longmd** [comment]
@davidakennedy , this is in staging and ready for validation.
