### ISSUE TITLE
Create Salesforce Report (WH VA Hotline Tier 2 / EVSS Case Closure) 

### ISSUE THREAD

**Issue by edpearson20** [department-of-veterans-affairs/va.gov-team#57587]
Technical Support Cases Not Closed_Copy

https://va.lightning.force.com/lightning/r/Report/00O3d000000ZVGhEAO/view?queryScope=userFolders

**Comment by ATMiddleton** [comment]
Report has been updated and completed.  Updated settings in closure report to reflect modified cases.  Also updated delivery cadence.
