### ISSUE TITLE
AWS access for Tuong Ngo

### ISSUE THREAD

**Issue by tuongngova** [department-of-veterans-affairs/va.gov-team#57595]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Tuong T Ngo

### Your Email

tuong.ngo@bylight.com

### Team, Role, and Company of the target individual

Backend DevOps Engineer with Identity team

### Product Manager (PM) name and email

Mike King (Mike.King@oddball.io) PM

### Product Owner (PO) name and email

John Rahaghi; john.rahaghiva@gmail.com

### Desired AWS Access

As a DevOps Engineer support Identity team, I need full AWS access on all resources.

Thanks,
Tuong, aka. Tim

### Access Expiration

06/2026

### E-QIP Transmittal Confirmation

2/13/2023

### Additional Notes

Joe Niquette [joe.niquette@oddball.io] is the Lead Engineer of Surge Identity Team who can vow for my access.

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by considerable** [comment]
VFS Team Roster

**Comment by BillChapmanUSDS** [comment]
Access approved,  As per usual, any production access is 3 month limited
