### ISSUE TITLE
Circular link in Burials hub

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#5759]
## What happened?
On this page: https://www.va.gov/burials-memorials/memorial-items/headstones-markers-medallions/ - the “replacement” text link is linking to itself (just lands you at the top of the page).

The link is pointing to this legacy page which appears to be redirecting to the above new headstones page inside our hub:  https://www.cem.va.gov/cem/hmm/replacements.asp

Same thing is happening for the “Replacements” left nav link. 

## Specs:
- All devices and browsers

## Steps to Reproduce
- navigate to https://www.va.gov/burials-memorials/memorial-items/headstones-markers-medallions/
- click "replacements" in left nav
- link navigates to https://www.cem.va.gov/cem/hmm/replacements.asp, which redirects to the above URL

## Desired behavior
"Replacements" no longer exists in the left nav.

## Acceptance Criteria
- [x] "Replacements" removed from left nav

## Screenshots
![image](https://user-images.githubusercontent.com/13204473/74284041-ff75e580-4cf0-11ea-8d0f-56de4e187e63.png)
![image](https://user-images.githubusercontent.com/13204473/74284057-06045d00-4cf1-11ea-8228-f9b487e77b7e.png)

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by AnneHurley** [comment]
Have removed link from body text, and @RLHecht  removed "Replacements" from the left nav.

**Comment by MickinSahni** [comment]
Validating this after deploy tomorrow afternoon. Associating with Sprint 15

**Comment by RLHecht** [comment]
This has been validated on live site. Closing issue. @MickinSahni
