### ISSUE TITLE
SOCKS access for David Kennedy

### ISSUE THREAD

**Issue by davidakennedy** [department-of-veterans-affairs/va.gov-team#57598]
### Your Name

David Kennedy

### Your Email

david.kennedy@adhocteam.us

### Your Role and Team

Staff UX Designer on 1010 (Health Enrollment)

### Product Manager (PM) name and email

Heather Justice: heather.justice@adhocteam.us

### Product Owner (PO) name and email

Patrick Bateman: patrick.bateman@va.gov

### Access Type Requesting

viewers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDr7Ptb4HOH91Tpj3d0W2zyedxcqotWKSynNfqWlP12DaNiNafChwXEY56xghA7IkUB8cNt36DwqlaDz22YFf0tuiXMehOWEE+BQ1dlAZlIUAno/ZKOq7EUVwrTxTrxY9yan6QEprzaU43JucWkyjSQs3NSFcBUlrbPBWIm37+JWuTBtUWvjDDgrdXXcsFJLdLOZ5bZNiXxwEi3OL1U6CaDKRYC91sDM9sPwdNO07IfBYC/3MDqcJgcfXuWRifBKpgCdiuXYKgCKAErdYGgP0AchnE/YEgcQ47h2wSGdc+rv8FeBkeQwdr4iaai9t038UAsdPipCRIXEsknpoE34oc3j3pXajFBgB4tTgo8EjeOf7hWe17W7q+T0DKPfUH9Mu/tw6SYG4tUwzkBHMSYXiXUkukitnEx7wjJAAZQNHIf8rvC2Qo6TsxSACgK/00Myr7MsX+rO61z+/EwfHn9bMSM+lIX41NpTOzPmKDtIWDhHxVrLTEG3ILjcf0IkSAF1B0= davidkennedy@batwing.local

### E-QIP Transmittal Confirmation

![image](https://user-images.githubusercontent.com/1473618/234977184-df603cd6-48a4-4c2b-9888-2b911ba5027f.png)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by flooose** [comment]
@davidakennedy you should be all set. Let us know if you run into problems.
