### ISSUE TITLE
Midpoint Review - IA Feedback - Veteran Facing Forms - Product 21-0972 Alternate Signer

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#57596]
## VFS actions
- [x] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

### Must:
* **H1**: I completely appreciate that you are trying to use clearer language for form titles, but the language here now is wrong - this doesn't actually submit an application for benefits on behalf of someone - it certifies someone else as a designated signer. Work with Sitewide CAIA on naming for this form. 
* **Required fields**: The intro page says to be prepared with the Veteran's VA file number (if they have one) - but what if they don’t? Jeana mentioned in the meeting that it's a conditional requirement and will only be revealed if the Veteran has submitted a previous claim. That's fine as long as there is no possible user path where someone who has submitted a claim would be missing this number. Otherwise we should remove the requirement. 
* **Inconsistent language**: 
    * Dynamic step/chapter headings (e.g. "Veteran's spouses....") are not the same as those on the summary review page - these should match.
    * Action link to enter form - link text should somewhat closely match our name for the form (H1)
    * Success message (after form is submitted) - heading language should somewhat closely match our name for the form (H1) 

### Consider:
* **Intro page** "when to use this form" section: the first sentence doesn’t completely describe what this form is for. Can we be more explanatory there and make it very clear what the purpose of this form is? ﻿The language you use for Step 1 of 13 could possibly be re-used: “By filling out this form, the VA will be able to accept benefit applications signed by you on behalf of veterans and claimants.” 
* **Page structure of unhappy path**: thank you for giving us the most complex user path in these wireframes. This is just a consider item, it's ultimately up to you what to do here, but it may be more intuitive for a third-party signer to fill out information about the claimant before they fill out information about the Veteran. 
    * You made a good point about follow-on questions being further separated from the claimant section if you do that. I agree with you & support tying those questions to the relevant section if you decide to swap page order around.

**Comment by jeana-adhoc** [comment]
Notes:

**Must feedback**
1. Must feedback for H1 & Inconsistent language: We need to get confirmation on the right title here. I had previously worked with Danielle on this title, but I might not have represented the form well. Once we figure out the title, the Action link to enter the form and the success message on the confirmation page will be fixed.
2. We've fixed the 'required' label/path for the VA file number.
3. On the review page the steps are automatically pulled from the steps - I've updated the sketch file to be accurate

**Consider feedback**
1. I've updated the "When to use this form" language a bit. I hope site wide content can help review it.
2. We're considering re-arranging the flow for the page structure of the unhappy path. 

I'm going to go ahead and close this ticket as most of these things will hopefully be addressed when sitewide reviews the content.
