### ISSUE TITLE
Change Faraday::TimeoutError from ERROR to INFO

### ISSUE THREAD

**Issue by omgitsbillryan** [department-of-veterans-affairs/va.gov-team#576]
## Problem
`Faraday::TimeoutError` from `Sidekiq/EVSS::UpdateClaimFromRemoteJob` is triggering a Sentry `ERROR` ([link](http://sentry.vetsgov-internal/vets-gov/platform-api-production/issues/67131/)), which in turn triggers a Sentry Alert that we cannot act upon.

## Extra Context
Our [Sentry Alert Rules](http://sentry.vetsgov-internal/settings/vets-gov/projects/platform-api-production/alerts/rules/) are configured, such that, Sentry Issue Events that are of `INFO` level _will not_ be a qualifying event for a Sentry Alert. Our overall goal is to get our Sentry Alerts to be much less noisy and much more actionable.

A related issue to this one may be found here:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/509

## Work to Be Done
- [ ] Change `Faraday::TimeoutError` errors to instead be logged as `INFO` level, so that it does not trigger a Sentry Alert.

**Comment by omgitsbillryan** [comment]
Status update:

- last seen in sentry July 24th
- last alerted in #vfs-sentry-alerts July 12th

It's possible that we fixed this as a result of another fix. It's also possible, that the timeout stopped being reached so regularly.

**Comment by kfrz** [comment]
Closing for now as it's not specific enough to be actionable.
