### ISSUE TITLE
SOCKS access for Adrian Rollett

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#57602]
### Your Name

Adrian Rollett

### Your Email

adrian.rollett@va.gov

### Your Role and Team

Engineering, Health Apps, OCTO

### Product Manager (PM) name and email

N/A

### Product Owner (PO) name and email

N/A

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDSShJ9s70RoKqvyarT3Bb7/tYIR6oVwLccAAUgc12X3WH2F+99DtMa6M3Q+8oGkKuuLsOkLYM09o7cYHYfrsFMxhLiSyQuHJjsE9MFkYUtg8n7zX5Ael4l/cqd7vfaAjPX1hb6k6heKeIq5KFSlTohktTMM1YZtrB7U5pn8oGF77dy5ZXcroExGRWnM3mAUMqZPErWzklRGNWH23ZRt03fgyaR7SKZo8EmqPc55ywpank5b32iwaIMQY4k1Y5A4E9JQhTizOgqUjlYeNdb+0W5DbC28JLH3Pf9TAOfC29FN0pOY9SSqaXArK61XmDVHpL4uTVfmPsx4m+tpUl2o9kb92nwC1YE1p4eQueeFTuKONg4hvTOShZC2ydhRTRQIs1fPziHXOjAm1SEjKFyoJTx3LQK3fLghWZj3FVL6fWojlHCIELOMOl+P5bnDMx4UOtvJk37wLTXykCax2gtQqOzyaQvQsDGVSEGDrWFmno+Ip+2naE/x+x+xfftz3dUvLM= acrollet@devbox

### E-QIP Transmittal Confirmation

I've had SOCKS access since 2020, just requesting for new machine now that I'm with OCTO.

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by flooose** [comment]
@acrollet does this mean the [old entry](https://github.com/department-of-veterans-affairs/devops/blob/460ab4a30a43b27c63477ac9e8bdad0b657eaa96/ansible/global/config.yml#L290) and [corresponding key](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/roles/dsva-config/files/authorized_keys/adrian.rollett%40agile6.com) should be removed?

**Comment by flooose** [comment]
The entry in the "VFS Team Roster" is also still there with the old email address. I'm not sure what this means for this issue.

**Comment by acrollet** [comment]
> @acrollet does this mean the [old entry](https://github.com/department-of-veterans-affairs/devops/blob/460ab4a30a43b27c63477ac9e8bdad0b657eaa96/ansible/global/config.yml#L290) and [corresponding key](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/roles/dsva-config/files/authorized_keys/adrian.rollett%40agile6.com) should be removed?

yes, thank you!

**Comment by rmtolmach** [comment]
@acrollet What I've seen when people move from contractor to OCTO, is that an [offboarding request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=analytics-insights%2C+Offboarding%2C+operations&template=offboarding-request.md&title=Offboarding+of+%5Bindividual%5D) is filled out. I didn't see one for you. I don't know if it's strictly necessary, but I guess what I would ask is, is there anything you have access to from your Agile6 time that you no longer need? Here's a screenshot of the comprehensive list (from the offboarding template). 
![image](https://user-images.githubusercontent.com/10993987/235957962-c12f7607-7fe5-4e3e-b98b-de6b06b85445.png)

@flooose has removed your old SSH key in https://github.com/department-of-veterans-affairs/devops/pull/12969 ✅, but is there anything else? Do you still need your AWS access?

**Comment by acrollet** [comment]
@rmtolmach I still need all those items, thanks! 🙂 In general I wouldn't recommend that the full offboarding be done when folks move from contractor to VA, it would lead to a whole lot of churn re-gaining access. If anything, a separate process that just checks for any unneeded items and ensures that email addresses are updated to the person's VA email would be the way to go.

**Comment by rmtolmach** [comment]
👍 got it, I think we can close then, then. 

I totally agree on the full offboarding being overkill. I wonder if it's an ATO requirement or something?

**Comment by acrollet** [comment]
> 👍 got it, I think we can close then, then.
> 
> I totally agree on the full offboarding being overkill. I wonder if it's an ATO requirement or something?

not a clue! 😅

**Comment by flooose** [comment]
@acrollet I've merged your corrected public key. Let me know if you have any problems.
