### ISSUE TITLE
Design Intent  - IA Feedback - OCTO Health Apps, MHV Medical Records, After Visit Summary

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#57605]
## VFS actions
- [x] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [x] Comment on this ticket:
  - [x] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [x] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- Thank you for bringing this in such early stages - it is really helpful to see the lo-fi wireframes and a user-flow. Your walk-through answered a ton of questions, and it sounds like you have a great game plan going forward. 
- This work is exciting and will bring a net positive to literal millions of Veterans, so I am excited to see what you come up with. Also happy to hear this is a joint team effort across MHV integration & VAOS/appointments.
- Polyhierarchy: a question came up during the meeting about this link on the appointments details page and where that will send users. This is complicated! Tagging @mnorthuis - she already has thoughts on how you can handle breadcrumbs in initial phases.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

* Must: there is a lot of content here - break this page up as much as possible to make it more scannable and navigable.
* Consider: Launching the MVP to align with the PDF printout makes sense, and I am grateful you explained that so thoroughly. After that it would be helpful to see:
    * A phased rollout plan that brings this into alignment with the MHV work over time (data fields and label language aligning with MHV work)
    * A content model that will guide how all gets laid out on the page and in what order

**Comment by kristenmcconnell** [comment]
@outerpress Added you to the ticket, so you can keep track of the IA discussion. 

@JRRoof too.

@sterkenburgsara Thank you for the feedback.

@mnorthuis I'll find some time on our calendars after the offsite to chat about AVS (unless we end up being able to quickly sync during the offsite).

**Comment by kristenmcconnell** [comment]
After design explorations, we are moving forward to test an accordion-based design to help break up the content. We are also continuing conversations with Kristin and Mikki about IA.
