### ISSUE TITLE
Vets-api terminal access for Nick Sprinkle

### ISSUE THREAD

**Issue by ndsprinkle** [department-of-veterans-affairs/va.gov-team#57617]
### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date: 10/27/19

### Your Name

Nick Sprinkle

### Your GitHub handle (terminal access is managed through GitHub)

@ndsprinkle

### Team, Role, and Company of the target individual

VA Forms, Engineering Lead, Oddball

### Product Manager (PM) name and email

Tricia Baker, tricia.baker@oddball.io

### Product Owner (PO) name and email

Matthew Dingee, matthew.dingee@va.gov

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [ ] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### COR Name (leave "None" if you listed an AWS user name above)

None

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

Oddball - Amber Malcolm

### Access Expiration

12-31-23

### Additional Notes

Justification: Need Prod Argo access so my team can verify that our form submissions are reaching the Central Mail API and being processed. This is vital to our solution. We have a non-identifying form submission UUID that we can use to call the status endpoint and verify that form reached its destination.

### User must exist in a roster before vets-api terminal access can be granted

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added
- [ ] If they included an AWS user name, check to see if their user name is listed in [iam_users.tf](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf)
- [ ] Comment in this issue saying which roster the user is listed in and confirming their AWS user name (if applicable)

**Comment by ryan-mcneil** [comment]
@ndsprinkle Are you on a vfs team? I'm not seeing your name listed anywhere. Please see the last section re: existing in a roster and follow the necessary steps.

**Comment by ndsprinkle** [comment]
@ryan-mcneil Sorry for the very long delay, I should now show up on the VFS team roster. I came from the platform program to the VA forms program I am currently on and assumed I would still be there, so that was my mistake

**Comment by ryan-mcneil** [comment]
User found on VFS Roster ✅ 

eQIP date is from 2019, so @BillChapmanUSDS you'll probably have to confirm on your side (Still working on that list!)

**Comment by bdech** [comment]
@ndsprinkle You've been granted PROD access for 3 months, expiring 06/21/2023

**Comment by bdech** [comment]
slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1687365913693589)

**Comment by bdech** [comment]
@ndsprinkle Per an update to our access policy, your ArgoCD/vets-api Production access has been extended for 3 months, expiring 12/21/23. Please set a reminder for yourself to return to this Issue and re-request access within 1 week of the expiration date. You'll receive 1 reminder with a 72 hour window to respond. Failure to do so will result in lost access and will require you to fill out a new request.

**Comment by bdech** [comment]
slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1695302942424089)

**Comment by bdech** [comment]
@ndsprinkle Your Vets API Terminal Production access has expired.

Would you like to request an extension? You have 72 hours to respond, or your 
access will be revoked and you will need to fill out a new request.

**Comment by bdech** [comment]
Removing production access due to no response.
