### ISSUE TITLE
[EKS Control Plane] DISCOVERY:  Figure out our IP space

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#57612]
## Description
The team would like to understand if we can create VPCs per cluster and/or additional private subnets to existing VPCs

## Resources 
- https://github.com/department-of-veterans-affairs/platform-security/issues/251

## Acceptance Criteria
- [ ] Discuss the CSOC decision as a team

## Refinement Guidance - Check the following before working on this issue: 
- [x] _Team label assigned ("platform-tech-team-2")_
- [x] _Epic assigned (if needed)_ 
- [x] _Estimated (points assigned)_
- [ ] _Sprint assigned (once planned)_
- [ ] _Team member(s) assigned_

**Comment by jhouse-solvd** [comment]
@ph-One & @hgbarreto - Please feel free to go ahead w/ the worker node IP address change. _Per Gary's comment [here](https://github.com/department-of-veterans-affairs/platform-security/issues/251#issuecomment-1572490660)_

PSEC will continue to seek feedback from CSOC, but that isn't a blocker. A route _(ie, NAT + ACL)_ may be needed to allow CSOC/BigFix scan access in the near future, but PSEC can create an issue for that once we've received additional info. 

Thanks for bringing it to our attention! We'll look at how to streamline communication around changes like this moving forward. In the meantime, let me know if there's any additional info we can provide.

**Comment by ph-One** [comment]
Thank you @jhouse-solvd and @gary-fallon
