### ISSUE TITLE
Offboard user to correct scheduling path when Cerner-enabled 

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#5762]
## User story
As a Veteran registered at specific Cerner-enabled VA healthcare system, I want to be routed to the correct scheduling workflow (either VAOS or My VA Health/Cerner) based where I am registered. 

## AC:
- [ ] Veteran registered at both Cerner (including Columbus) and non-cerner users can still see appointments on VA Appointments homepage
- [ ] Veterans registered at Columbus-only can still see appointments on VA Appointments homepage
- [ ] Veterans cannot cancel appointments on VA Appointments homepage 
- [ ] For Cerner sites, VAOS should provide 2 alerts in tool during the flowing flow stages:
    - 1 "VA Appointments" homepage -- Message: "you cannot SCHEDULE, REQUEST, or CANCEL VA, Community Care, or VA Video Connect appointments and provide a link to My VA Health."
    - 2 "VA Facility" page -- Message: "you cannot schedule or request a VA appointment at this location at this time and must go to My VA Health. (with a link)"
- [ ] Veteran can still schedule, request, or cancel appointments for non-Cerner sites in VAOS

## Notes:
We need to create messaging within VAOS tool for users who are registered at health facilities that have migrated to Cerner as their patient portal that they can't use VAOS to schedule or cancel appointments.  

Messages will appear in the following places: 
- A message should appear on the VAOS landing page. 
- A message will appear as an alert on the facility/system selection page (after the first question where you pick a system).
- First CSS health care system will be Columbus VA **April 10th 2020** (as of 2/18/2020)
- Spokane will be first full health care system to migrate ~ _Spokane Cerner rollout delayed until July 2020

## VAOS-R JIRA Ticket
https://issues.mobilehealth.va.gov/browse/VAOSR-326

**Comment by lalexanderson-dsva** [comment]
- Veteran logs in at full Cerner site, we should get 220CRNR ID in MVI: 
  - Need: Alert on the scheduling page (Bridget and team)
  - Need: Alert on My VA page (Bridget and team)
  - Need: Alert on the landing page (VAOS)
  - Need: Alert midstream (VAOS)
  - Confirm: should not be able to see any upcoming appointments 
  - Need: Cannot cancel an appointment at a full cerner site. --> Cerner
  - Need: Cannot cancel a video appointment from a full cerner site. --> Cerner
  - Need: Cannot request a community care appt at a full cerner site 
  - Need: Cannot schedule or request a VA appt at a full cerner site 
  - 
- Veteran logs in at a CSS site (Columbus)  - we will get 200CRNR  ID in MVI
  - Need: Alert on the scheduling page (Bridget and team)
  - Need: Alert on My VA page (Bridget and team)
  - Need: Alert on the landing page (VAOS) --> go to Cerner 
  - Need: Alert midstream (VAOS) -->go to Cerner
  - Need: Cannot cancel an appointment at a CSS site. --> Go to Cerner
  - Need: Cannot cancel a video appointment from CSS site. --> Go to Cerner
  - Need: Cannot request a community care appt at a CSS site 
  - Need: Cannot schedule or request a VA appt at a CSS site

**Comment by lalexanderson-dsva** [comment]
We need to make sure that the alert on the home page of VAOS specifies that you cannot SCHEDULE, REQUEST, or CANCEL VA, Community Care, or VA Video Connect appointments and provide a link to My VA Health. 

We need to make sure that the alert midstream specifies that you cannot schedule or request a VA appointment at this location at this time and must go to My VA Health. (with a link)

**Comment by lenaecb** [comment]
@rtwell - can you help with mockups for the two states in-app for Cerner-specific appointments and facilities? We decided to keep this all in one ticket but let me know if you want to break it out.

**Comment by rtwell** [comment]
dropping some questions here:

1. In the first acceptance criteria, we say "Veteran registered at both Cerner and non-cerner sites can still see appointments on VA Appointments homepage". Does that mean they can see both Cerner AND VA appts? I assume no (they can only view VA appts), but would like to clarify.
2. Do we have any thoughts on slightly different treatments for users that are **only** registered at a Cerner site? It seems like an opportunity to reroute them immediately instead of letting them get several clicks deep into VAOS only to discover they cannot make an appt on this web page.

**Comment by lenaecb** [comment]
Some Q&A for this specific Cerner/Columbus story:

- **Will My VA Health portal show upcoming appointments previously scheduled at a now Cerner-enabled site**? - 
  - Lauren: Unlikely

**- Should VAOS show upcoming Columbus appointments data on VAOS “Appointments” page?** 
   - Lauren: Yes, but do not let Veterans cancel.
   - Yes - show alert on “Appointments” homepage about Columbus
   - Hide the cancel button on displayed appointments -- Yes
   - Disable ability to select the Cerner site from the drop down of possible parent sites or allow selection of that site and at that point display info to the Veteran or maybe we just put the info display on the front page? This is something the UX experts will need to determine. -- Lauren: I’m inclined to disable the Cerner site and put an alert there redirecting them to My VA Health but want Ryan’s input.
  - If there are identifiers that are NOT Cerner sites, the Veteran can continue to do all the standard stuff with them -- Yes
  - Redirect user to My VA Health Portal to perform any action need for Columbus specific appointments -- Yes

**In the future, will a Veteran who is registered to both Cerner and non-Cerner sites (not just Columbus) see upcoming Cerner appointments on VAOS “Appointment” page?** Lauren - For NON Columbus, Cerner sites, NO they will not see their appointments on VAOS.

For Cerner only they will be directed to MY VA Health portal on the static VA.gov appts page with a CTA. They will still have need to have access to either VAOS or MHV to view 'past appointments' and 'appointments previously scheduled at a now Cerner-enabled site.'

I want to minimize the above by getting 'past appts' complete in new VAOS. But these CTAs also depend on our rollout. If we are not 100% by April 10th (which is now at risk) we will need to push them to MHV for 'past appointments.'

**Comment by lenaecb** [comment]
@peggygannon - at this point, this story has been broken down into smaller stories and those are linked back to the original epic here -- #5734

Ryan is working on the designs now. Let me know if I should tag you in those design stories.
