### ISSUE TITLE
Seed credential list in vets-api-mockdata

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#57635]
Now that Mocked Auth feature is live, we need more credentials in the mocked credential list. This is 'sorta' automated, you'll still have to log in manually with each credential, but it'll update your `vets-api-mockdata` repo automatically.

There's a list of test accounts here, but I'm not sure if we need all of them mocked: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv

**Comment by joeniquette** [comment]
the users here would be good too: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/vsp/teams/Identity/Test%20Documentation/test_accounts.md
