### ISSUE TITLE
Business intake form for OBA

### ISSUE THREAD

**Issue by vbadmr** [department-of-veterans-affairs/va.gov-team#57655]
## Your Details
1.  **Your Name**
David M. Reis
​
2.  **Business Line**
Office of Benefits Automation - OBA
​
## Notification Details
1.  **Notification type**
Email
​
2.  **Please describe your use case.**
We are establishing claims via a batch process and need to notify Veterans by email a claim has been established and the next steps 
​
3.  **What actions can the user take based on the notification they receive?**
View message only, no further support is requested
​
4.  **What is the desired business outcome?**
Less call center volume based on receiving notice at the same time as the claim is established since these Veterans would not be expecting a claim filed on their behalf
​
5.  **What system will kick off the notification? Please note the system should be inside the VA or have an ATO.**
A VETSNET Batch process will establish the claims at which time we would like the email sent
​
6.  **What will trigger the notification?**
Batch establishment of claims, we could coordinate a trigger based on this requirement as needed
​
7.  **Provide sample content per notification type, if you have it.**
I have attached the PDF version of the letter that will go out.  We are wanting all of the letter content to be sent via email, omitting the fillable content at the top like the address and salutation.
​
[CS Application Failure Notification - General.Final.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/11356796/CS.Application.Failure.Notification.-.General.Final.pdf)

8.  **Has a Privacy Officer (PO) seen and approved the content? If not, do you know who your PO is?**
To my knowledge the PO has not seen this content, but was approved for release via the concerned business lines.  The same content has been approved for release VIA paper letter as well.  I am not aware of who my PO is if this sign off is required.
​
9.  **Would you prefer to provide contact information for the recipients or would you rather VA Notify look this up for you by Veteran ID? If by ID, please let us know what identifier is used in your system.**
va.gov could provide a list of email addresses used for correspondence or we could use your provided records whichever is deemed more accurate
​
10.  **Do you currently capture communication preferences related to this notification? If so, please describe.**
No opt in has been selected nor solicited.  This email is in addition to a paper letter with the same content being mailed, but due to mailing times we needed a timely notification as well.
​
11.  **What is the anticipated volume of notifications per day, week, month?**
​These emails will be generated once, but over multiple batch jobs.  The total volume of affected Veterans if about 32,000 and the first email will be sent to about 15k or possibly as many as 29k Veterans​

12.  **When does this notification need to be in production?**
June 5, 2023

**Comment by mjones-oddball** [comment]
@vbadmr Hi, I have some initial questions:
1. Is the reason for this failure something that will never recur? I see in the description it is a one-time email, but I am wondering if more failures will occur over time for claims (not necessarily for the same people). If so this could become an automated email at the time of failure after the initial retroactive batch.
2. 
> I have attached the PDF version of the letter that will go out. We are wanting all of the letter content to be sent via email, omitting the fillable content at the top like the address and salutation.

- Can we keep the salutation at the top with their first name, so it is personalized?
- How will the recipient know which type of claim and/or claim number this is in reference to? 
- Can you confirm we will not be including file number, which is located at the top of the letter?
- At the bottom of the letter there is a mailing address for pension claims and another for compensation claims. Is this notification for both types of claims?
3. Contact information for email can be handled 1 of 2 ways. Either the requesting system would send the email address for the individual OR a recipient identifier (participant id, ICN, va profile id, birls id) and VA Notify would use to look up the contact details in the authoritative source, VA Profile.
4. Will VETSNET be generating the API request per recipient to trigger notifications through VA Notify? Apologies as I'm unfamiliar with VETSNET, is that a system you manage on your team?

**Comment by vbadmr** [comment]
Thank you for the questions and my answers are provided below.  If you would like to meet and discuss any of this please reach out to me.  IM is preferred if that works for you.  

1.	Is the reason for this failure something that will never recur? I see in the description it is a one-time email, but I am wondering if more failures will occur over time for claims (not necessarily for the same people). If so this could become an automated email at the time of failure after the initial retroactive batch.  **The problems will continue to recur at least in the sort term, but we are working to try and resolve all failures and eliminate the need for these emails.  Our current thinking is that claims that continue to fail will go through these batch establishments thus needing an email so if there is a way to automate this handoff during the batch establishment perhaps we could look into this?  We may need to met on this topic and discuss further the ideas for automating in the future.**
2.	
I have attached the PDF version of the letter that will go out. We are wanting all of the letter content to be sent via email, omitting the fillable content at the top like the address and salutation.
•	Can we keep the salutation at the top with their first name, so it is personalized?  **If this is possible to personalize the email without extending the development timeline I think this is certainly something we would be interested in, but we would not want to add this salutation/personalization if it would add onto the delivery timeframe.**
•	How will the recipient know which type of claim and/or claim number this is in reference to?  **Due to the constraints of the letter content we could not reference a specific claim which failed.  These Veterans, having filed a claim on va.gov, could log onto va.gov and locate the new claim form which they can see the claim status and details associated.**
•	Can you confirm we will not be including file number, which is located at the top of the letter?  **We will not include the file number.**
•	At the bottom of the letter there is a mailing address for pension claims and another for compensation claims. Is this notification for both types of claims?  **Yes**
3.	Contact information for email can be handled 1 of 2 ways. Either the requesting system would send the email address for the individual OR a recipient identifier (participant id, ICN, va profile id, birls id) and VA Notify would use to look up the contact details in the authoritative source, VA Profile.  **Using the authoritative source would be ideal in these cases as this would provide the best opportunity to contact these Veterans.  Do you know if this authoritative source is the same email that is “attached” to the va.gov account?  If so, I see no downside to using it.  If they are different we may want to discuss which to use based on these claims originating in va.gov.**  
4.	Will VETSNET be generating the API request per recipient to trigger notifications through VA Notify? Apologies as I'm unfamiliar with VETSNET, is that a system you manage on your team?  **The VETSNET Batch team are generating the claims which will trigger the need for these emails.  We will need to determine the proper way to get your group an input file and what would be needed and the timing required for this file.  We may need a meeting between the groups to sort this one out.  I can arrange a meeting if needed.  Feel free to contact me directly if easier.**
