### ISSUE TITLE
[CAIA a11y Research] MHV on VA.gov: Secure Messaging Usability Testing (Testing October TBD)

### ISSUE THREAD

**Issue by rbsingleton** [department-of-veterans-affairs/va.gov-team#57653]

**Comment by sara-amanda** [comment]
## CAIA Research Support
**NEW!** [CAIA Research Support Ticket Available](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name) @rbsingleton for when you need it, if you wanted to tie it into this Epic. 🙌 

cc: @artsymartha68 @SarahKay8 @AngelaFowler82

**Comment by coforma-terry** [comment]
Moving to Backlog

**Comment by rbsingleton** [comment]
Sorry - I'll close this issue as we'll be collaborating with Angela Fowler on this study. Thank you!
