### ISSUE TITLE
Screen Reader Testing Request from Debt Resolution

### ISSUE THREAD

**Issue by HeatherRienks** [department-of-veterans-affairs/va.gov-team#57662]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more unauthenticated pages, online forms, apps, or tools on VA.gov
- [X] Making revisions to one or more existing VA.gov pages
- [ ] Something else 
 
 *Give a brief description of what your team needs support with.*
We would like to ensure that the FSR enhancements we are working on meet the accessibility standards. We specifically would like help with screen reader testing.

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [ ] Yes
  - [X] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
## When do you expect to launch your product to 100% of users?
  
*Please provide an estimated date so our team can create other relevant tickets.*
  
## Supporting artifacts
*Please provide supporting artifacts as available.*

- Link to product outline: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/fsr_enhancements/product_outline.md
- Link to or attach user flows: 
- Link to prototype or mockups: https://preview.uxpin.com/f43733391f52c409c4d3152e9a4b101a392e29df#/pages/161460688/simulate/sitemap
- Link to staging environment: https://staging.va.gov/manage-va-debt/request-debt-help-form-5655/introduction
Login: user228

## Will this work be going through the Collaboration Cycle?
- [X] Yes 
- [ ] No

## When does this work need to be done?
- Estimated launch date: June 12, 2023
- Estimated staging review date: June 6, 2023
- Content, Accessibility, and IA work needed by: Preferably end of May, prior to Staging Review which we are hoping to coordinate on June 6

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [X] No, but I'd like to schedule time to talk about this request
- [X] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: Debt Resolution
-	OCTO-DE product owner: Matt Self
-	Product manager: Tom Davis
-	Designer: Joseph Lee, Megan Gayle, Charlotte Cesana
-	FE engineer: Aaron Ponce, Andrew Rodiek, Brandyn Sullins
-	Product/team Slack channel: #benefits-debt-resolution

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by SarahKay8** [comment]
Hi @HeatherRienks! Do you have availability today to discuss this request?

**Comment by HeatherRienks** [comment]
@SarahKay8 - Hi! Yes, would you happen to be available today at 4:40pm ET/ 1:30pm ET?

**Comment by SarahKay8** [comment]
@HeatherRienks Yes that works for me!

**Comment by HeatherRienks** [comment]
@SarahKay8 Great- I will send an invite! Thanks!

**Comment by HeatherRienks** [comment]
Team met with @SarahKay8 and she will assist with using JAWS and voice over technology to look at Staging and will provide feedback when completed. Thanks!

**Comment by SarahKay8** [comment]
Hey @HeatherRienks I'm experiencing some issues testing this form. The VA server is down at the moment. I'll try again in a few. ![Image 6-7-23 at 2.03 PM.jpg](https://images.zenhubusercontent.com/623cd4d6774110eeb19922cb/43c51129-e96c-4225-af28-e54e71e6e25c)

**Comment by HeatherRienks** [comment]
@SarahKay8 - thanks for letting us know! Please keep us posted!

cc: @josephrlee @mgleo @charlottecesana @Tom-Davis

**Comment by SarahKay8** [comment]
Hey @HeatherRienks @josephrlee ! Continue button on the “what debt do you need help with?” step  is not working after clicking space or enter. Showing click event but nothing is happening. 

Tried using a mouse and still no action. 
I'm unable to get passed this step in order to move forward with testing. There's warning from Sentry saying `target element not found` I'm not 100% sure if that is what's causing the issue.
![Image 6-8-23 at 3.32 PM.jpg](https://images.zenhubusercontent.com/623cd4d6774110eeb19922cb/0e48f2d9-6940-4611-9eda-beca67a139c7)

**Comment by mgleo** [comment]
Hi @SarahKay8, are you logged in using the email address that ends in 228? It is showing that the user in the screenshot does not have an overpayment or copay bill. User 228 should have it.

**Comment by HeatherRienks** [comment]
@SarahKay8 - thank you so much for all of the feedback! We really appreciate it.

cc: @mgleo @josephrlee @charlottecesana

**Comment by SarahKay8** [comment]
Of course! Closing this out! :)

**Comment by josephrlee** [comment]
@SarahKay8 Thanks for all the feedback! We know the issues on the Household Income section on the review page. It's definitely something we're actively working on to address right now. For context, the new enhancements were not included in the review page as the views for them are significantly more complicated than the other fields on the review page. So that's why it's confusing. We are planning to make it better in the upcoming sprints.

**Comment by SarahKay8** [comment]
Of course anytime. Thanks for the clarification! @josephrlee
