### ISSUE TITLE
[Datadog] Set up integration with vets-api

### ISSUE THREAD

**Issue by it-harrison** [department-of-veterans-affairs/va.gov-team#57677]
## Description 
In order to complete #49287 we need to integrate relevant VA repos with Datadog. This ticket is for the `vets-api` repo.

## Notes
- https://vagov.ddog-gov.com/integrations/github/add

## Acceptance Criteria
- [ ] `vets-api` repo can be monitored in Datadog

**Comment by ph-One** [comment]
https://github.com/department-of-veterans-affairs/vets-api/settings/hooks/415002692?tab=deliveries
