### ISSUE TITLE
[Datadog] Set up integration with vets-website

### ISSUE THREAD

**Issue by it-harrison** [department-of-veterans-affairs/va.gov-team#57679]
## Description 
In order to complete #49287 we need to integrate relevant VA repos with Datadog. This ticket is for the `vets-website` repo.

## Notes
- https://vagov.ddog-gov.com/integrations/github/add

## Acceptance Criteria
- [ ] `vets-websiste` repo can be monitored in Datadog

**Comment by ph-One** [comment]
https://github.com/department-of-veterans-affairs/vets-website/settings/hooks/415002754?tab=deliveries
