### ISSUE TITLE
[Datadog] Set up integration with content-build repo

### ISSUE THREAD

**Issue by it-harrison** [department-of-veterans-affairs/va.gov-team#57678]
## Description 
In order to complete #49287 we need to integrate relevant VA repos with Datadog. This ticket is for the `content-build` repo.

## Notes
- https://vagov.ddog-gov.com/integrations/github/add

## Acceptance Criteria
- [ ] `content-build` repo can be monitored in Datadog

**Comment by ph-One** [comment]
https://github.com/department-of-veterans-affairs/content-build/settings/hooks/415002945?tab=deliveries
