### ISSUE TITLE
[Datadog] Set up integration with devops repo

### ISSUE THREAD

**Issue by it-harrison** [department-of-veterans-affairs/va.gov-team#57676]
## Description 
In order to complete #49287 we need to integrate relevant VA repos with Datadog. This ticket is for the `devops` repo.

## Notes
- https://vagov.ddog-gov.com/integrations/github/add

## Acceptance Criteria
- [ ] `devops` repo can be monitored in Datadog

**Comment by ph-One** [comment]
https://github.com/department-of-veterans-affairs/devops/settings/hooks/415002603?tab=deliveries
