### ISSUE TITLE
Comparison Analysis of Claims Status Usage and Call Center Issues

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#5768]
## User Story or Problem Statement

How might we track usage of claims status tool so we can compare against call center issues and determine major pain points for users accessing the claims status tool on VA.gov? 

## Goal

Completed comparison analysis of call center issues and claims status tools usage that provides insight into any correlations between claims status tool and calls to the NCC. 

## Objectives or Key Results this is meant to further
- _lorem ipsum_

## Acceptance Criteria
- [x] Determine method for pulling logs on claim status tool usage.
- [x] Send data log to NCC team.

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by clantosswett** [comment]
The back end team was able to complete a log analysis and pull data on usage of the claims status tool. That document was delivered to VBA, specifically to Regina Yount and Michael Crouse. They will need to do their own cross analysis to determine how much overlap there was between users accessing the tool and users calling in. I will also be reaching out to see if we are able to start getting access to recordings to do initial listening sessions on NCC callers whose issues were tagged as "general status."

**Comment by clantosswett** [comment]
I reached out to Regina Yount to see what progress they have made on the cross analysis. I haven't heard anything yet but will reach back out again today to see if we can help with this effort.

**Comment by joanneesteban** [comment]
Finished out our end of this. Closing this out and will open a new issue in June when we hear back from VBA.

**Comment by clantosswett** [comment]
Received the analysis from VBA (attached here). The analysis will be used to make changes to the claims status tool to address some of the issues users are frequently calling in about.

[https://app.zenhub.com/files/133843125/9e998a33-09d1-4551-a92b-d2c3cbb6f59c/download](https://app.zenhub.com/files/133843125/9e998a33-09d1-4551-a92b-d2c3cbb6f59c/download)
