### ISSUE TITLE
SOCKS access for Ian Perera

### ISSUE THREAD

**Issue by ianperera** [department-of-veterans-affairs/va.gov-team#57696]
### Your Name

Ian Perera

### Your Email

ian.perera@va.gov

### Your Role and Team

Software Engineer on NOVA

### Product Manager (PM) name and email

Zachary Law zack.law@oddball.io

### Product Owner (PO) name and email

Beverly Nelson beverly.nelson@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDGN/i8Iwm2oL6fvcsgE5PihW5iwEPov/SBiO5/G/4+Xa+fzxZhTwRFCtsSrlyBqm0YHeb07MHDTSip2Mt247CYYRSijZ+4KsB1iyVU57+WOkf2VE8o/It5+EuKurPv10M6qey43klrh+22P4k8JLfts8c3ENkafF2ov9T/BblHgr7BtSGQA4sWYBRAkTDU1HdYNuH1L+tcUsdpCpT+nvEX0mHQdDANo5Z66ReaTuZUZIpVbWUHlpalkTf6i92/R2wyBYfrLXhU8TxJFlJ+gLW1TDS1MkBdBicQJ6r2JVppaAsm3y3BuIW22HSlTW/BOpZTboBLNR1H0Nvr3tBDlWC5401XuQ5ZB0gFPZKbTKDEyGL5DhhQ8HNpFCeipwd2y6y2v2J3AyB0L4TWYTc2T8d/WtpgyZlEu5FXCOcAG5FzAaqVeAUhV7dmK3Sqf0y8Mzp6W4jESf2g93JwqIHRrUCHZllAEKSbKp8i8tB6J2loX4eJKFqz0dPq0Qya7pgqiEU= irperera@Cyber-MBPro.local

### E-QIP Transmittal Confirmation

![image](https://user-images.githubusercontent.com/25709133/235475832-56707ea3-d833-4264-bd8e-862325e978e6.png)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by flooose** [comment]
@ianperera you should be all set here.

**Comment by ianperera** [comment]
@flooose can I change that Public Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCoXfooj8pFAYoIjlCX22Rj2L9TFhuSXgBrHXn5lyWAi7kCksWVV+k1OWSDr++axN4CxUH7FfUsdY6baRM6o0p8o70waXhLQVt4VbrjusdCcTrrGVuCH6R0QbJtUtZx5L1C2/gvstiZkbm0tpEhKAIxVrO2pLeG0Clh7jdIrAc0TvBn4zERtGc+/rPGRyv9xEp70VqVZCLexY+Zgk4XpukAw4qAkbPjvGOHv4wAenAVkfN82zTdrdDCHXHN/FJB05T1mG6mz5Z+VhTbWS2Wke6YqJd0jhT8L5v7dKP42NDotJ3nSgmumQalJwUavTtk53l4Mg5D8ruTtXT15KIPPDQ/4N940ByydRqBnGe2Qn6S7N0sze3APSAzBxnpuKaw9dpZKm42faepnh6kbXVjiV/6xmNnKttzKhUazSJkJLBSZ+yGgohaLMKF2eFEF/G+kfuVU89cZszoJotyLi+XsgfryY7WnLPPYGNInKJtNV0mXFPDCEbz3iwgpHq+giSc6n0= irperera@Cyber-MBPro.local

**Comment by flooose** [comment]
Sure. I'll put it on my list for the day. Sorry I didn't see this yesterday.

**Comment by flooose** [comment]
should be all taken care of. If there are problems, let me know.
