### ISSUE TITLE
Loki data logging for Telehealth Appointments (Part 2) 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#57703]
## Description
Continuing the logging for Telehealth Appointments [previous ticket #54542](https://app.zenhub.com/workspaces/vaos-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/54542). The team would like to see what sites return for Video Connect using GFE appointments (VA clinics, ATLAS location, other). 

Copy Doc: 
[Video Connect using a GFE](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/appointment-details.md#vvc-gfe-booked-future)

---

## Acceptance Criteria
- [ ] log telehealth data from appointments for GFE, including ATLAS facility/VA facility/other address values 

### Design Assets
None

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by ajmagdub** [comment]
Slack thread on Mobile GFE: https://vappgteam.slack.com/archives/C023EFZPX4K/p1692121395464659?thread_ts=1692121360.354879&cid=C023EFZPX4K

**Comment by ajmagdub** [comment]
VAOS appointment telehealth logging expanded to include more data points like patient has GFE details and other miscellaneous details. The `log_telehealth_data` method has been refactored. Initially, it logged only the 'atlas' information from an appointment's 'telehealth' field. Now, it logs 'atlas', 'gfe', and other miscellaneous details. It uses new helper methods like `atlas_details`, `gfe_details`, and `misc_details` to extract these details. Additionally, error handling has been added to this method. The `atlas_details` method now extracts 'siteCode' and 'address' from the 'atlas' field in 'telehealth'. The new method `gfe_details` gets the 'hasMobileGfe' detail from an appointment's 'extension' field. The `misc_details` method provides details like 'vvsKind', 'siteId', 'clinicId', and the names of 'practitioners'. Another new `method extract_names` constructs the full names of practitioners given their first and last names. A helper method `non_empty_array_of_hashes?` has been added to check if the argument is a non-empty array of hash objects.

**Comment by ajmagdub** [comment]
Returned the issue status to 'In Progress' so that the data can be attached to the ticket once the data has been collected.

**Comment by ajmagdub** [comment]
# Summaries:

 |hasMobileGfe|| 
|-------|---------|
|FALSE| 679100 |
| TRUE| 20900 |
| Total | 700000 |

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmhFQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1929620bb284b24a9004ee8916608e20d73cfa3d/has-mobile-gfe.png)

------------------

| **vvs Kind**|| 
|-------|----------|
|ADHOC | 691587 |
|CLINIC_BASED | 1824 |
|MOBILE_ANY|6477|
|MOBILE_GFE|111|
|STORE_FORWARD|1|
|**Total**|**700000**|

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEJFQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c330efb2b3d8335529ade0db663aac4a875f751c/vvs-kind.png)

**Comment by ldelacosta** [comment]
Could you send us the latest data for this ticket? @ajmagdub

**Comment by ajmagdub** [comment]
[2024-02-22-telehealth-data.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeE9EQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c0463ead2089522d78c8087ec04e88bc67ba5c95/2024-02-22-telehealth-data.xlsx)
Hi @ldelacosta please find attached the latest data collected from this ticket.

**Comment by ldelacosta** [comment]
@ajmagdub - thanks for the latest data. Please turn off the logging for this work. Let me know when it's done and I'll close out the ticket.

**Comment by ajmagdub** [comment]
@ldelacosta - appointments telehealth data logging has been removed.

**Comment by ldelacosta** [comment]
Work is complete. Logging has been stopped. Latest data is available in the ticket. cc: @JRRoof @outerpress @Cieramaddox @melissa-lefevre
