### ISSUE TITLE
AWS access for Christopher Floess

### ISSUE THREAD

**Issue by flooose** [department-of-veterans-affairs/va.gov-team#57726]
### COR Name

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Christopher Floess

### Your Email

christopher.floess@adhocteam.us

### Team, Role, and Company of the target individual

Platform Tech Support Team, Software Engineer III, Ad Hoc

### Product Manager (PM) name and email

Ryaan Boyd

### Product Owner (PO) name and email

ryaan.boyd@adhocteam.us

### Desired AWS Access

vsp-operations

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

![image](https://user-images.githubusercontent.com/123168/235508294-94b3a07a-2c8e-41f6-9cff-f7d93e923872.png)

### Additional Notes

COR: [Ray Wang gang.wang@va.gov](mailto:gang.wang@va.gov)
"ongoing" - because @considerable said :)

### User must exist in a roster before AWS access can be granted

- [ ] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [x] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by considerable** [comment]
Platform Team Roster

**Comment by BillChapmanUSDS** [comment]
Access approved,  As per usual, any production access is 3 month limited

**Comment by considerable** [comment]
initial password provided via slack DM.
