### ISSUE TITLE
Preferences User Research

### ISSUE THREAD

**Issue by LynneJohnson224** [department-of-veterans-affairs/va.gov-team#57730]
Design and research team to start digging in to see what needs to be included in preferences.

- [ ] Internal Research - what's in VA Profile in VA.gov already
- [ ] How do preferences fit into VA.gov?
- [ ] Where should preferences live - va.gov, MHV on va.gov, application level?

Link to [preferences spreadsheet](https://dvagov.sharepoint.com/:x:/r/sites/HealthApartment/Shared%20Documents/General/Preferences%20and%20Notifications/MHV%20and%20New%20Profile%20and%20Preferences.xlsx?d=wd9e64dc034eb48d7ae03abb11b731c78&csf=1&web=1&e=4koCHd&isSPOFile=1) Kay Lawyer put together.

[Notes ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/meetings/cto-health-team-weekly-mtg.md )from 4/27 Health Apt Team meeting Preferences discussion:

**Comment by LynneJohnson224** [comment]
@fmccaf1 @jonathanjnelson here is the ticket for Preferences research. Can you please add any other tasks or deliverables that may come from this work? Also, take a look at [54196 ](https://app.zenhub.com/workspaces/mhv-to-vagov-cto-team-pi-10-integration-planning-board-63a31dce3fe3310026840f42/issues/gh/department-of-veterans-affairs/va.gov-team/54196 )and it's child tickets to see if the tickets contain any helpful information. Thanks!

**Comment by fmccaf1** [comment]
Thanks @LynneJohnson224. I hadn't seen 54196 yet. I'm thinking I might need to take a task next sprint just to familiarize myself with the work that Jonathan has already done with understanding preferences associated with the health dashboard, as I see he has done a lot of work there.

**Comment by LynneJohnson224** [comment]
@fmccaf1 @carafrissell1 given the refinement discussions this week, do we still need this ticket?

**Comment by fmccaf1** [comment]
I don't think we do @LynneJohnson224. Closing ticket.
