### ISSUE TITLE
Appointment Modality is incorrect for VA in person appointment 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#57734]
## Summary
When logging as ruben.moreno@id.me in staging, the user booked a direct scheduling for Audiology on June 7, 2023 at 8 am and June 8, 2023 at 10 am at the Cheyenne, VA location. When returning back to the appointment list, the appointment is being displayed as a Video appointment when it is a In-person appointment at the VA. 

## Specs
- Device: Mac
- Browser: Google Chrome

## Steps to Reproduce
**Test User:** ruben.moreno@id.me 

1. Go to: https://staging.va.gov/health-care/schedule-view-va-appointments/appointments
2. Start Scheduling
3. Select type of care Audiology 
4. Facility preference select VA clinic 
5. Select Cheyenne Medical VA 
6. Select Wheatland Audiology
7. Select patient indicated date June 7, 2023 
8. Select date June 7, 2023 at 8:00 AM 
9. Select `My reason isn't listed here` and enter the comment
10. Enter contact details phone number and email address 
11. Confirm the details and submit the appointment 
12. View the appointment details on the confirmation screen
13. Return to the Upcoming list to view the appointment that was created 

### Actual Result
The appointments that were created are Video appointments and not in person appointments 
<img width="387" alt="Screenshot 2023-05-01 at 3 18 45 PM" src="https://user-images.githubusercontent.com/90797205/235529554-598c8fc4-b678-4098-9dee-c91567c1680b.png">

### Desired Result
The appointment modality is an in person appointment 

## Definition of Done
- [ ] Desired result is achieved and/or document decisions made
- [ ] Relevant documentation is updated

---

**Comment by simiadebowale** [comment]
We are getting an appt kind returned as 'telehealth'.
The only thing I found while doing more research was the secondaryStopCodeName of the clinic selected was: "RT CLIN VID CARE HOME".
is there a logic in vaos-service that uses secondary stop codes to determine appointment modality? 
![Screenshot 2023-05-03 at 3.37.34 PM.png](https://images.zenhubusercontent.com/62279c01c38e1718c9102bee/6d323fc5-d961-418e-8f38-8b14bbca7f79)
cc: @marcynadeau @ldelacosta

**Comment by marcynadeau** [comment]
@simiadebowale @ldelacosta There is an issue with this clinic and it is the secondary stop code that is causing that issue.  .  I noted this on the test data wiki page in regards to the clinic:  DO NOT USE for direct scheduling.  WILL SHOW UP A VIDEO VISIT APPT WITH NO LINKS.  https://wiki.mobilehealth.va.gov/pages/viewpage.action?spaceKey=VAOSR&title=VAOS+SQA+TEST+DATA+SETUP

And one of the things on my to do list is to log a CDW ticket for the data architect to remove that secondary stop code.

**Comment by ldelacosta** [comment]
@marcynadeau - was secondary stop code removed?

**Comment by marcynadeau** [comment]
@ldelacosta No this is around #8 on my to do list. Do I need to bump it up to the top?  I have. noted on the test data page that I need to fix this clinic.  
https://wiki.mobilehealth.va.gov/display/VAOSR/VAOS+SQA+TEST+DATA+SETUP

DO NOT USE for direct scheduling.  WILL SHOW UP A VIDEO VISIT APPT WITH NO LINKS.  NEED TO LOG CDW TICKET TO REMOVE SECONDARY STOP CODE.  Appointments in a clinic with a secondary stop of "secondaryStopCode":179,"secondaryStopCodeName":"RT CLIN VID CARE HOME will have the modality = telehealth

**Comment by ldelacosta** [comment]
@marcynadeau - I was just checking the status but let me know if there is anything we can do to help. Thanks!

**Comment by ldelacosta** [comment]
@marcynadeau - just checking in to see the status of this ticket. Let me know when you have a chance. Thank you!

**Comment by marcynadeau** [comment]
@ldelacosta This is so far down on my to do list right now.  If you need this done, I would talk to Grace.  Maybe she can find a resource.

**Comment by ldelacosta** [comment]
Closing out the ticket. An issue with how the clinic is set up in staging. 

Recent thread between me and Marcy in the #appointments-team channel 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ2h1IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d67c9ae71399755d569c89e9e4ec6b566f772eed/Screenshot%202023-09-05%20at%206.17.06%20PM.png)

cc: @JRRoof @simiadebowale
