### ISSUE TITLE
Reason code is not displayed in the Review Details and Request Details page 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#57739]
## Summary
When the user selects the `Reason code` and enters their comments in the `Choose a reason for appointment` page, the app should display what the user selected and display the free text comment on the Review details, Appointment Details and Request details page. 

## Specs
- Device: Mac
- Browser: Google Chrome

## Steps to Reproduce for Direct Scheduling 
**Test Users:** ruben.moreno@id.me 

1. Go to: https://staging.va.gov/health-care/schedule-view-va-appointments/appointments 
2. Start Scheduling
3. Select type of care Audiology
4. Facility preference select VA clinic
5. Select Cheyenne Medical VA
6. Select Wheatland Audiology
7. Select patient indicated date June 7, 2023
8. Select date June 7, 2023 at 8:00 AM
9. Select `My reason isn't listed here` and enter the comment 
10. Enter contact details phone number and email address
11. Confirm the details and submit the appointment
12. View the appointment details on the confirmation screen
13. Return to the Upcoming list to view the appointment that was created

### Actual Result
The app is not displaying the reason code only the free text comment 
<img width="1159" alt="Screenshot 2023-05-01 at 3 14 09 PM" src="https://user-images.githubusercontent.com/90797205/235540562-acb43216-efee-46e7-900c-dd9a6b1ced69.png">

### Desired Result
The app should display `Reason code: Veteran's comment `

Design spec screenshot: 
<img width="230" alt="Screenshot 2023-05-01 at 6 14 30 PM" src="https://user-images.githubusercontent.com/90797205/235540864-3f46a1df-b6dc-4f53-aa56-234f3c3e27b5.png">

## Definition of Done
- [ ] Desired result is achieved and/or document decisions made
- [ ] Relevant documentation is updated

**Comment by ryanshaw** [comment]
@ldelacosta This is how it looks on staging now:

![staging va gov_health-care_schedule-view-va-appointments_appointments_requests_163807](https://user-images.githubusercontent.com/587812/235757217-55fc1838-3afe-4e9e-8f24-6137a274f044.png)

**Comment by ldelacosta** [comment]
Tested the direct schedule workflow and the reason code is not displaying @ryanshaw 
![Screenshot 2023-05-02 at 7.30.49 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/70ba4ba0-f600-4ffe-9f0d-3cde4067ef43)

**Comment by ldelacosta** [comment]
@ryanshaw - moving this back to In progress. Let me know when it's ready in staging. Thanks!

**Comment by ryanshaw** [comment]
@ldelacosta I dug into this a little bit. For the [direct scheduling appointment](https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/va/170760) that you referenced above we are getting this returned for the reason code:

```json
"reasonCode": {
    "text": "LD test 05/02 select 1 This is a routine or follow up visit. "
},
```

And for the [requested appointment](https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/requests/170761) that is displaying the reason code correctly, we are getting this returned:

```json 
"reasonCode": {
    "text": "station id: 983GD|preferred modality: FACE TO FACE|phone number: 2011001000|email: ldtest@id.me|preferred dates:06/01/2023 AM,06/01/2023 PM|reason code:MEDICALISSUE|comments:LD test 05/02 I have a new medical issue"
},
```

This is using the ruben test user.

**Comment by ldelacosta** [comment]
@ryanshaw - if the changes are done for request flow, please move to Validate and I will close it out. Will work with the BE team to address the direct scheduling flow. Thanks for all your help!

**Comment by ldelacosta** [comment]
Request flow has been validated in staging. No new issues to report. Closing out the ticket.![Screenshot 2023-05-08 at 10.50.32 AM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/2f1682de-2f2c-43d3-91ef-c99c7df1a6e1)
