### ISSUE TITLE
Datadog Log Message Tagging

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#57745]
## Description

[It was reported here](https://dsva.slack.com/archives/C04M7T1CZAS/p1683028676217339?thread_ts=1683028373.843099&cid=C04M7T1CZAS) that (the same) log messages are being tagged/labeled with different levels of criticality. 

It appears that the Datadog API does the tagging and we could possibly look into [custom log status remapper config](https://docs.datadoghq.com/logs/guide/logs-show-info-status-for-warnings-or-errors/) to define logs as they are expected.

Also dig into how the Datadog API determines log statuses (I think it may be based on the http status code)

**Comment by LindseySaari** [comment]
According to Trevor[ in this thread](https://dsva.slack.com/archives/C04M7T1CZAS/p1683058829182969?thread_ts=1683028373.843099&cid=C04M7T1CZAS), the identity team has been expirmenting with turning off custom log parsing/tagging rules. This seems to be the cause for the difference in error tagging (info vs critical). Now that we are fully on EKS, the logs are ingested into datadog as a hash instead of being jammed into one field (hence needing custom parsing tagging rules). Identity is planning to continue experimenting with the rules.

**Comment by laineymajor** [comment]
Provide documentation around logging... but that's about all that will be in our team's scope.

**Comment by laineymajor** [comment]
Lainey to look into current projects on the platform project board... if there's a datadog project, link to that.

**Comment by jennb33** [comment]
@jennb33 to check with Trevor on whether or not this is still an issue.
