### ISSUE TITLE
SOCKS access for Brandyn Sullins (New Laptop Setup)

### ISSUE THREAD

**Issue by OptionSelect** [department-of-veterans-affairs/va.gov-team#57749]
### Your Name

Brandyn Sullins

### Your Email

brandyn.sullins@govcio.com

### Your Role and Team

Front End Engineer on VA Benefits Debt 2 (Debt Resolution)

### Product Manager (PM) name and email

Tom Davis - thomas.davis@govcio.com

### Product Owner (PO) name and email

Matt Self - Matthew.Self2@va.gov

### Access Type Requesting

automation

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDjbY2vu0SJzgO/PHytcOqiM9i3xwkCLntseSQFNFxTHGhVig5u2D/7W/kbMyRE3x50B2GJiSCRD3iCOiGkQ2t9WG/Jgo5UHqX/wPyLIB2sRKrEwCWt9CRKUzigY64ERJ/7Q4yQpBVNBid1p84Umnr2fXmjmUkjsyLnOWy04fFxltTJbA0ZoqPzwSB/mORq0JR8zZxIsqYu5oMVAiiAdhKqbbaReJu0x5DgTC8VtqLSe9iUVFBFLCOHeGM70AefykbcuZWipCLaiS6dFa5Pe/Zl1kH81cU50DJ7VEPmEwPZ3YRmZOllNBxtoBplit5YpZ0V60i+u77Ajm5MuwvnVOHdZh9oWdZ2RJ/oQJn3yeuaRt82Y68vhikmb8xwcXj3nLNSP+N5F1xUiZ0iMgrw4YJhKWzPi7GIAtB5JvVztdwVGXDKn2rgq7j+3gYlB85StnunzObYxGbigcbPAYG9gxvuPadVigCC4HNC3ObbNj8E/BGpdtA5GA6zgpdBBhTMJWE= brandyn.sullins@FVFH47G7Q05N.lan

### E-QIP Transmittal Confirmation

N/A
Link to previous access request
https://github.com/department-of-veterans-affairs/va.gov-team/issues/36412

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by flooose** [comment]
@OptionSelect your access should propagate through the system in the next hour.

**Comment by flooose** [comment]
@OptionSelect had you  run `vtk setup` first? I had the specific case that I had generated my own ssh key, independent of vtk, when I set up my laptop. When I ran `vtk setup` a new one was generated, which I hadn't added to my GH account.

I think something in this direction could be your problem, maybe also your ssh agent. I guess step one is to check if you have two ssh keys now.

**Comment by OptionSelect** [comment]
Yep looks like that may be the case. 
Runing the below command returns the following. What do you recommend? :)

 ~  ssh-add -l
256 SHA256:2z5vaJA+ZpNAcIemF6TzJBjtmo+QVQplc8gX7nqQN10 brandyn.sullins@gmail.com (ED25519)
3072 SHA256:t5mr8rKfy0DF1Xcn81NjrWyUOo3cCNVKjDbE80pbd1s brandyn.sullins@FVFH47G7Q05N.lan (RSA)

**Comment by OptionSelect** [comment]
Yes I would like that! I am available at your convenience! I would rather be sure to do it right! :)

**Comment by flooose** [comment]
This is the correct public key

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCmoRQSSR9Kh7oh6ZZw851YfMBiKOHWq01Mn25BFbCuJ/YazFw0A//5Ibrm+6cXnoYMDmlXpPIJRDlH6yb0Ba+BURWuYWAo/fRiLM4n6W5QrUWjoVRmI+oN3PTEJARKS++TAphrldSKo210kQBqta5yfs0GhVld1EoolQglzp9FhznXUAEQqRa+0cZbcC5c9sdsx8DwBdQdfHYabnZlaHHcN1yAROb8ol/NoQc+nJaNHFBlE5cdmQG141mTRTYKOQDSeKPm2hYdIa3rybIy3gdsnsTeqK/9Tu3mZ5GFNvxK75jTheSSP73I3hs23VCAVtfhJ/c6d0Cuj8erhJExn4j80oH2lAjdnMT6rxE9w454P3X0AkwOTpayXjin/YKlb82atiQlzO4a4TD+zOe/6JqpchLlfcoPQ9CmhoiDeOI/IQNkpJWUkKP6MPdNSmr4jQzpIIUYpL2tELHZyNmMCNbgI+eOWqtRfpXnF347nvPdwS5viTkGau88Y5ZXGarwkIE= brandyn.sullins@FVFH47G7Q05N.lan
```

**Comment by HeatherRienks** [comment]
@Tom-Davis -not sure why this was added here, this ticket is for @OptionSelect, so no action is needed from you. :)

**Comment by considerable** [comment]
all looks done to me. following the end-of-week tradition, closing the tkt. please feel free to reopen if things show up.
