### ISSUE TITLE
Adding James Barrett to DSVA Slack

### ISSUE THREAD

**Issue by vievemarg** [department-of-veterans-affairs/va.gov-team#57740]
# Description

Please add James Barrett (james.barrett@adhocteam.us, james.barrett4@va.gov) as a full member of DSVA Slack. James is Senior UX Designer II on the UI/UX team for the VHA Enrollment System Modernization program. He will need access to multiple channels to communicate effectively within this role. Thank you.

**Comment by LEHigley** [comment]
sent to VA email
