### ISSUE TITLE
Adding teammates to DSVA Slack

### ISSUE THREAD

**Issue by alexander-ferzola** [department-of-veterans-affairs/va.gov-team#57746]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

Requesting the rest of my team has access to slack to be able to contact the platform team about best practices with VA.Gov design system and guidance on research initiatives

Are you requesting to add an individual as a:

Multi-channel
- What channel(s) do they need to be added to?
general, research op, design, inclusive research

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add [jacob.l.buller@accenturefederal.com] as a multi-channel guest to these channels: [#general, #research op, #design, #inclusive research].
- Please add [jim.adams@accenturefederal.com] as a multi-channel guest to these channels: [#general, #research op, #design, #inclusive research].
- Please add [joanna.yu@accenturefederal.com] as a multi-channel guest to these channels: [#general, #research op, #design, #inclusive research].
- Please add [l.nasser@accenturefederal.com] as a multi-channel guest to these channels: [#general, #research op, #design, #inclusive research].

**Comment by alexander-ferzola** [comment]
Hi Lacey @LEHigley , I'm sorry - i forgot a team member, haha. Could we also add kyle.west@accenturefederal.com to the same channels? Apologies for the second request!

**Comment by LEHigley** [comment]
done!

**Comment by alexander-ferzola** [comment]
Thank you 👯

**Comment by alexander-ferzola** [comment]
@LEHigley  whenever you get a chance, can you please re-send the request to Joanna [[joanna.yu@accenturefederal.com](mailto:joanna.yu@accenturefederal.com)] as a multi-channel guest to these channels: [#general, #research op, #design, #inclusive research].

**Comment by LEHigley** [comment]
made joanna multi channel guest
