### ISSUE TITLE
Determine A11y Changes in VAOS Appointments based on Recent Research

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#57768]
1 meeting

## Tasks
- Meet with Peter to Determine A11y Changes in VAOS Appointments based on Recent Research
- Create f/u tickets

**Comment by cgednalske** [comment]
@benbrasso-agile6 set up a sync with Peter next Tuesday. Here's a [ticket](https://app.zenhub.com/workspaces/vaos---productdesign-5fff340c2d80a4000fb6f69c/issues/gh/department-of-veterans-affairs/va.gov-team/57827) with some of the semantic improvements they'll make right after launch.

**Comment by benbrasso-agile6** [comment]
f/u ticket - https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/58140

@cgednalske can we close this?

**Comment by cgednalske** [comment]
Thanks @benbrasso-agile6! Yep - I'll close it now 👍
