### ISSUE TITLE
Review Instances - custom 502 handler

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#5777]
## Problem Description

Since review instances are internal and meant for testing out changes to code, it'd be really useful to take over the error pages served up by nginx to show how to find documentation and troubleshoot issues where nginx can't connect to one of the services hosted on the instance. While we want them to look as much like prod as we can, this should be an easy substitute since we'd be swapping out a single html file (in theory, anyway). Need to:

- [ ] develop text for the html page that gets displayed
- [ ] create page for troubleshooting so we can include in the page above
- [ ] implement in the nginx proxy on review instances

## Acceptance criteria

- [ ] when you manually stop the vets-website service on a review instance, the resulting page that's served describes the issue and gives links for documentation on how to troubleshoot issue
- [ ] the above is not dependent upon anything besides nginx being started

**Comment by wyattwalter** [comment]
The text on this page is going to be influenced by what happens in #6086

**Comment by rmtolmach** [comment]
The QA Standards team is doing discovery for review instances. This can be closed.
