### ISSUE TITLE
[Analysis] Review Analytics and Data for 1010 CG

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#57779]
As a team member, I would like to better understand how users are using the 1010 CG form so that I can make any changes to help Veterans get healthcare.

-  Review Medallia survey results
-  Review Analytics and discuss with team
-  Review Datadog RUM recorded sessions
-  Review video replays (not loading)
-  Review and triage list of errors
-  Come up with list of findings about success and impediments
-  Share findings with team
-  Come up with list of fixes/enhancements/etc. for the team
-  Come up with list of metrics/behaviors to track/follow going forward:

 

This was the EZ Doc write up for reference: https://docs.google.com/document/d/1lyq91j-1-buUBcUFcXgRE9FJFHh7XnMxuOBKu3vEsUg/edit

**Comment by luis-simauchi** [comment]
write up of the CG survey data exercise is here:
