### ISSUE TITLE
[Design] 10-10EZ - Facility Selection: Create new Facility search & selection design

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#57772]
## Background
We have created a design for the Facility selection on the 10-10CG, we would like to use that design as a baseline in the 10-10EZ.  
The facility selection page on the EZ form does not need to reference Caregiver facilities or present a confirmation page.
Additional discovery 

#### Benefit to Veteran
An easier way to search and recognize VA medical facilities to choose as their initial primary when enrolling in health care.

#### Where
Internal team improvement on the UX side; getting the facilities database updated (moved from static list) is a related initiative driven by the business. 

#### Why
An alignment with facilities search on the CG form and to echo sentiments heard in usability testing that it would be nice to search by postal code or other method when picking a facility. Have also heard the random order of the facilities not being alphabetized or only listing the unfamiliar name and not the address as being a pain point.

#### What
Designs in Figma to outline the phased approach to update the facilities page based on search of postal code to start and moving up to flow and dynamic recommendations based on home address. 

### References + Resources

[UX] 10-10EZ - Facility Selection: Evaluate dynamic search options on EZ #84027
- [Figma page](https://www.figma.com/design/UljiHam46o5DItC5iDgmPd/10-10EZ?node-id=3831-40050&t=63RJPPPiktdyUIP8-0)
- [Draft user flow options](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1717792007491/6c4a62cc037aa751acade917131f29077fe4483b?sender=uadf1ed7fe7c76f0914967329)
- [Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1720636135631/20c44b67060152d2f8b0b1c961fb7f51c6d39bad?sender=uadf1ed7fe7c76f0914967329)

- [Updated Figma page of CG designs](https://www.figma.com/design/TxXD5bGUOhbHHWLb85GPjK/10-10CG?node-id=2478-18708&t=36hh5JZXFLBpFqvj-4)

#### ARCHIVED SKETCH LINKS
CG designs - Use these as a reference
- [wireflows](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/dlyed5l)
- Desktop
     - [search input](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/jgnAQyo) desktop
     - [search results](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/zx9e3Yb) desktop
     - [select](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/Jn1QKqr) desktop

- Mobile
     - [search input](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/dlyemEb) mobile
     - [search results](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/ZOGQjqp) mobile
     - [select](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/v8VZMbM) mobile

## Tasks
- [x] Create designs for 10-10EZ Facility Selection page in release phases/iterations
- [x] Review with the team for feedback

## Acceptance Criteria
- Design for new Facility selection page is presented to the team for thoughts & questions

**Comment by jessicastump** [comment]
- Discovery ticket [[UX] 10-10EZ - Facility Selection: Evaluate dynamic search options on EZ #84027](https://github.com/department-of-veterans-affairs/va.gov-team/issues/84027)
- [User flow exploration in Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1717792007491/6c4a62cc037aa751acade917131f29077fe4483b?sender=uadf1ed7fe7c76f0914967329)
- [Desk research, discovery and early designs in Figma](https://www.figma.com/design/UljiHam46o5DItC5iDgmPd/10-10EZ?node-id=3831-40050&t=9URQml9lwhU7xxdV-0)

**Comment by jessicastump** [comment]
[Figma page with design phases/releases](https://www.figma.com/design/UljiHam46o5DItC5iDgmPd/10-10EZ?node-id=5131-3754&t=HoegRCnQbcaQQ1nG-0)

**Comment by jessicastump** [comment]
Reviewed phased approach with team: 

1. Add search with postal code to replace facility selection page at end of insurance section, move first appt question to it's own page, remove ACA check box
2. Expand search to include city, state, postal code
3. Move to new step: Step 2: VA facility
4. Suggest facilities based on home address with a path to search by city, state, postal code

Next steps: Designs for overall form review page to align with CG direction (needs ticket) + development (needs tickets) + research planning (include GA before/after data)

 @hdjustice - I think this ticket is okay to close based on meeting notes above? :)

**Comment by hdjustice** [comment]
Yep, good to close.  I am in the process of creating the dev, QA and launch tix, wasn't sure if you needed more design tix

**Comment by jessicastump** [comment]
@hdjustice I will add the review screens to this ticket/Figma page to align with the CG, so no new ticket needed there :) 
We can chat at refinement/standup - but maybe we open one for research per-planning? just to outline what data and metrics in GA to track and when during the phases we would want to run usability sessions.

**Comment by jessicastump** [comment]
Review screens added to [Figma page here](https://www.figma.com/design/UljiHam46o5DItC5iDgmPd/10-10EZ?node-id=5131-3754&node-type=CANVAS&t=QUEIDSSYyipJErQK-0)

**Comment by hdjustice** [comment]
a pre-planning ticket is a good idea.  That will help us to really identify meaningful metrics
