### ISSUE TITLE
[FE] 10-10EZ - Household Optimization: Pre-push to Staging

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#57787]
## Background
All development work is complete, we are now pending Pull Request (PR) review to be completed. This can take some time, as there are ~150 file changes that need review. We are capturing any issues or time taken to address questions/concerns during the PR review. We also need to verify that the household section, in its current state, was not affected by any development and will not create any issues while staging review and testing takes place.

## Resources
- [Link to Review Instance (must have SOCKS proxy running to access)](http://cbba62c06b79ff5cd9df8862b1f5015b.review.vetsgov-internal/)

## Tasks
- [ ] Verify the original household section functions as it is supposed to and that the optimization did not affect any current functionality

## Acceptance Criteria
- PR review is completed, all concerns/issues are addressed and functionality has been verified.

**Comment by longmd** [comment]
@hdjustice / @davidakennedy / @jessicastump / @JoshingYou1 - When y'all get a few free moments, can you [go through this review instance](http://cbba62c06b79ff5cd9df8862b1f5015b.review.vetsgov-internal/) and side-by-side with the current household section to ensure nothing has changed or been affected by the V2 build. 

I have been through it several times now and believe it is in good shape, but want to get other eyes on it.

**Comment by hdjustice** [comment]
I will check this out today!  thanks @longmd!

**Comment by jessicastump** [comment]
I went through the form a couple of times via unauthenticated - the review instance and staging seem to match. Should we run through with some test users/logged in too?

**Comment by hdjustice** [comment]
I have also gone thru it a couple times, and saw no discrepancies

**Comment by JoshingYou1** [comment]
LGTM!

**Comment by davidakennedy** [comment]
Also checked this out, and everything looked good.

**Comment by longmd** [comment]
Y'all are the best. Thank you for that. @davidakennedy , if you want.. I'll go ahead and turn on V2 and we can start doing some preliminary Accessibility auditing ahead of the staging push.

**Comment by longmd** [comment]
@JoshingYou1 / @jadon1979 , [here is the link to the current active PR](https://github.com/department-of-veterans-affairs/vets-website/pull/24098).

**Comment by JoshingYou1** [comment]
Couple of things I noticed when going through the different test cases:

1. When the user chooses yes to living with their spouse and sharing the same address, they still get the "Did you provide financial support to your spouse in 2022 even though you didn’t live together?" question on the following page.
![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExYjU5NWQ5NzE0ZGUwOGQ3MTZkZTQ1YTE3MzM4MmFjNzM2Y2JmMDBlOCZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PWc/cjCGhN8vilfskrDKxH/giphy.gif)
2. When selecting "No" for the dependent educational expenses question, it still requires the user to enter a dollar amount for expenses.
![](https://images.zenhubusercontent.com/64189db1a8eccf9be4d62bdd/5f9800a6-2fb7-4b9f-a01b-5cee728f9fb1)
If the functionality for both of these scenarios is intentional, please disregard.

**Comment by longmd** [comment]
@jessicastump , I was going to bring up Josh's first question, too, during our review... it does seem a bit silly to ask that question if they answer yes to the cohabitate question.

**Comment by davidakennedy** [comment]
Agreed on Josh's first question. I noticed this too today when testing, and thought it was odd.

**Comment by jessicastump** [comment]
Adding to the agreement pool, also thinking the same thing while completing the [Sketch QA file](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/p/12B7255E-72F6-4C6A-83C3-81BF9A1CEBDE/canvas). Thought it was too late to change the flow to that extent, but this page has evolved to being way more than one question per page. Ideally it would be better to only present questions that don't contradict previous answers.

**Comment by longmd** [comment]
All, the PR for this has been merged and deployment to staging is in progress.

**Comment by longmd** [comment]
I've been through a couple times now on staging with V1 and have seen no issues. If anybody else wants to have a go, you're more than welcome.

**Comment by longmd** [comment]
The branch as been successfully deployed to prod. I have enabled the new household section for all users on Staging, so @davidakennedy , you're free to wrap up your init QA and screenreader testing in that environment.

@hdjustice , I have also submitted an application under my own name and account to for initial verification with Josh F.

**Comment by longmd** [comment]
Just adding comment that we did receive successful submission confirmation from Josh F. with household V2 enabled.
