### ISSUE TITLE
[Data/FE/Testing] Reproduce and Diagnose Start Button Issue (Desktop)

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#57782]
As a Veteran, I would like to be able to fill out the 1010-EZ form in my email so that I can quickly and easily apply for the VA healthcare benefits that I have earned.

- [x] - Determine what desktop Browsers users are having issues on
- [x] - Test against those browsers
- [x] - Come up with solution, either with JS replacements, or a notification for users to update their browser
- [x] - See if there is a front end solution (maybe reach out to platform team)
- [x] - Work with Benefits group to divide and conquer (as needed)

**Browser Checklist (list of recent browsers with issues):**

**Edge**
**Facebook**
**Google**
**Safari**
**Opera**
**Internet Explorer**

-----------------------------------------------------

- Make/suggest fix
- Test
- Go through review process
- Release to Prod

Matt L: Benefits Team 1 - Robin Garrison and his team are going to continue to track every single FE error through June.We were seeing the the same or similar errors on the load and login from our form as they are with their form.

**Comment by luis-simauchi** [comment]
Edge

111.0.1661.62

Facebook

406.0.0

Google

256.2.518341946

Mobile Safari

16.3

Safari

16.3

**Comment by luis-simauchi** [comment]
link to the google doc we are working out of for browsers / OS combinations:
https://docs.google.com/spreadsheets/d/1WiHzmVTWjCTptCyP2QGeXdut8ElHem-wCba-31wxi2M/edit?pli=1#gid=0

**Comment by luis-simauchi** [comment]
all (available) desktop browser versions have been tested, updated doc here, first & second tab: https://docs.google.com/spreadsheets/d/1WiHzmVTWjCTptCyP2QGeXdut8ElHem-wCba-31wxi2M/edit?pli=1#gid=0

3.25K tests were conducted In a combo of Browser & OS  
Takeaways from both Windows & Mac desktop OS:
Across the board, older versions of browsers seem to have a hard time either loading the VA site in totality, loading elements of introduction page or the start button working as intended. 

Breakdown of browser versions that had constant issues across all OS' tested
Chrome versions: 15 - 52
Firefox versions: 3 - 62
Opera versions: 10 - 39

We can talk action items once a have a debrief from both this issue ticket & its' sister ticket for MOBILE.

@alexseelig @hdjustice @emily-brown34

**Comment by luis-simauchi** [comment]
Matt Long & I chatted about possible action items and one recommendation that is worth mentioning:
 
"There is no way to mitigate for users/applicants using older browsers on VA.gov with a frontend or back end solution for the sign in button for the 1010 form; or any of the sign in portals across the entire site for that matter."  
 
Instead it may be wise to pitch for a global banner element be implemented to warn site visitors to update their browser of choice else certain site functionality will not be available.  

We have discovery / research material to justify the recommendation to the appropriate team.

**Comment by luis-simauchi** [comment]
This was discussed with the group as a whole last week and the best recommendation that came out of the discussions was a notification for users to update their browser when they try to sign-in to their VA.gov experience.
