### ISSUE TITLE
[IA Tracker] New Appointments Home

### ISSUE THREAD

**Issue by kristinoletmuskat** [department-of-veterans-affairs/va.gov-team#57788]
Current work being documented here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/health-appointments.md

**Comment by kristinoletmuskat** [comment]
From Mikki:
Thoughts about the appointments work that we should work with the team on to clarify and then work through in documentation:

- We only need to document the main appointments page - www.va.gov/my-health/appointments/, then make note that the views will be handled by filters on the page. In the notes we can make a suggestion for the parameter name of "view", and give examples of parameter values of "pending", "upcoming", etc.  But those can be worked out with engineering.  Does that make sense?  We are essentially saying that we want 1 main appointments page.

- Same with the appointment detail view - www.va.gov/my-health/appointments/details/

- We should discuss whether they plan to keep cancel flow in a modal or move to a sub-task flow - a11y would likely call for a sub-task flow and then we would assign a URL for it.

- For the scheduling flow, we can simplify the table by putting all the sub-pages in a list somewhere.  Are you suggesting any changes to any of the sub-pages?  If not, we could just note that and leave the, out entirely, and just note that they would follow the main page

**Comment by RLHecht** [comment]
Closing!
