### ISSUE TITLE
Vets-api terminal access for Aurora Hampton

### ISSUE THREAD

**Issue by ahay-agile6** [department-of-veterans-affairs/va.gov-team#57795]
### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Aurora Hampton

### Your GitHub handle (terminal access is managed through GitHub)

@ahay-agile6

### Team, Role, and Company of the target individual

Benefits Disability Experience

### Product Manager (PM) name and email

Rakshinda Aslam rakshinda.aslam@agile6.com

### Product Owner (PO) name and email

Matt Self matthew.self2@va.gov

### Your dsvagovcloud AWS user name (if applicable)

Aurora.Hampton

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### COR Name (leave "None" if you listed an AWS user name above)

Delano McVay

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

Agile Six - Anthony M. Arashiro

### Access Expiration

ongoing

### Additional Notes

I made a previous ticket here #57530  for the lower environments, think I didn't need production yet, but our team keeps getting requests in which we need to be able to debug issues for Form526 usage which requires looking at metrics in the production environment.

thank you!

### E-QIP Transmittal Confirmation

![image](https://user-images.githubusercontent.com/19178435/230650231-6995fbeb-b7f8-46ab-bd26-ced408cb384a.png)

### User must exist in a roster before vets-api terminal access can be granted

- [ ] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added
- [ ] If they included an AWS user name, check to see if their user name is listed in [iam_users.tf](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf)
- [ ] Comment in this issue saying which roster the user is listed in and confirming their AWS user name (if applicable)

**Comment by ryan-mcneil** [comment]
Access to `prod` is pending approval by OCTODE, and we'll update you as soon as it's available.

**Comment by BillChapmanUSDS** [comment]
Access approved,  As per usual, any production access is 3 month limited

**Comment by ryan-mcneil** [comment]
@ahay-agile6 You've been granted access to all environments, with access to Production limited to 6 months, expiring 11/10/23

**Comment by ryan-mcneil** [comment]
Slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1683757077864519)

**Comment by bdech** [comment]
@aurora-a-k-a-lightning  Per an update to our access policy, your ArgoCD/vets-api Production access has been extended for 3 months, expiring 11/10/23. Please set a reminder for yourself to return to this Issue and re-request access within 1 week of the expiration date. You'll receive 1 reminder with a 72 hour window to respond. Failure to do so will result in lost access and will require you to fill out a new request.

**Comment by bdech** [comment]
slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1691677141031619)
