### ISSUE TITLE
Address VA.gov  back button not working as expected.

### ISSUE THREAD

**Issue by rmessina1010** [department-of-veterans-affairs/va.gov-team#57809]
VA.gov this morning: the back button didn’t work as i expected so i took this short screen recording of me reproducing the bug.

Transferring the following issue to FE CoP: (#54943) https://app.zenhub.com/workspaces/platform-tech-team-support-634ebbcc35e2bc0015b382fd/issues/gh/department-of-veterans-affairs/va.gov-team/54943
Submitted By: lainey.trahan
Topic: va.gov - Incident
Team: Frontend Support

Support request thread link: https://dsva.slack.com/archives/CBU0KDSB1/p1678465107274819

Note I was able  able to reproduce this behavior in Firefox and Safari(old)

### Next Steps
- [ ]  attempt to reproduce issue locally 
- [ ]  do we provide browser specific fixes ( could be an issue with router).

**Comment by CBonade** [comment]
We believe this was resolved along with a related analytics issue that surfaced around almost the same exact time. The resolution eliminated the behavior of many copies of a page being open in the browser history. Closing this ticket.
