### ISSUE TITLE
GIDS: Update File Upload Status Alerts

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#5780]
As a GIDS tool user, I need the messaging around the file upload status to be clearer so that I know what actions need to be taken in order to publish a new version of data for the Comparison Tool.

## Assumptions:
1. N/A

## Acceptance Criteria
1. After the file is uploaded, with success or failure, the status messaging is displayed at the bottom of the page (success, warning, or error styling).
2. After the file is uploaded, with data issues or failure:
     - For data validation issues, detailed messaging is displayed at the bottom of the page with warning styling
     - For failures, detailed messaging is displayed at the bottom of the page with error styling
3. If the file is successfully uploaded, the messaging is displayed at the bottom of the page with success styling.
     a. As part of the successful upload messaging, the following information is displayed:
> Total Data Rows: X
> Valid Data Rows: Y
> Invalid Data Rows*: Z
>
> * Invalid Data Rows are not included in new version generation.

4. If there is an exception, a user friendly error message is displayed.

## Supporting Artifacts:
1. Current messaging:
<img width="1440" alt="old_file_upload_data_issues" src="https://user-images.githubusercontent.com/48260534/74349087-bd48b480-4d81-11ea-90c4-eba02b2ff66d.png">
<img width="831" alt="old_file_upload_error" src="https://user-images.githubusercontent.com/48260534/74349092-bde14b00-4d81-11ea-82cb-bb40d150cba6.png">

2. Example of new messaging:
<img width="812" alt="new_fle_upload_error" src="https://user-images.githubusercontent.com/48260534/74349143-ca65a380-4d81-11ea-9052-bd5ce89ac689.png">
<img width="831" alt="new_success" src="https://user-images.githubusercontent.com/48260534/74349145-cafe3a00-4d81-11ea-87d3-70b53009055a.png">

3. File that causes exception:

[WEAMS_School_Data_PGM_02032020.csv.zip](https://github.com/department-of-veterans-affairs/va.gov-team/files/4194071/WEAMS_School_Data_PGM_02032020.csv.zip)

**Comment by hughes-dustin** [comment]
branch: bah-5780
PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/585

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-02-26 at 8.20.48 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/f9690400-4014-41af-b99b-53bb198b00d2)
##
![Screen Shot 2020-02-26 at 8.20.17 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/a3899273-f074-40d1-85a5-3b1a533d009d)

**Comment by sonntag-adam** [comment]
Testing passes https://dsvavsp.testrail.io/index.php?/runs/view/200&group_by=cases:section_id&group_order=asc

**Comment by sonntag-adam** [comment]
In staging, testing passes QA.
