### ISSUE TITLE
Vets-api terminal access for Seth Darr (for production)

### ISSUE THREAD

**Issue by sethdarragile6** [department-of-veterans-affairs/va.gov-team#57802]
### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Seth Darr

### Your GitHub handle (terminal access is managed through GitHub)

sethdarragile6

### Team, Role, and Company of the target individual

Benefits Disability Experience

### Product Manager (PM) name and email

Rakshinda Aslam rakshinda.aslam@agile6.com

### Product Owner (PO) name and email

Matt Self matthew.self2@va.gov

### Your dsvagovcloud AWS user name (if applicable)

Seth.Darr

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### COR Name (leave "None" if you listed an AWS user name above)

Delano McVay

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

Agile Six - Anthony M. Arashiro

### Access Expiration

ongoing

### Additional Notes

I made a previous ticket here https://github.com/department-of-veterans-affairs/va.gov-team/issues/57531 for the lower environments, thought I didn't need production yet, but our team keeps getting requests in which we need to be able to debug issues for Form526 usage- which requires looking at metrics in the production environment.

### User must exist in a roster before vets-api terminal access can be granted

- [ ] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added
- [ ] If they included an AWS user name, check to see if their user name is listed in [iam_users.tf](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf)
- [ ] Comment in this issue saying which roster the user is listed in and confirming their AWS user name (if applicable)

**Comment by ryan-mcneil** [comment]
@sethdarragile6 Access to `prod` is pending approval by OCTODE, and we'll update you as soon as it's available.

**Comment by BillChapmanUSDS** [comment]
Please add EQUIP transmittal date.

**Comment by BillChapmanUSDS** [comment]
Found equip in linked ticket: Access approved,  As per usual, any production access is 3 month limited

**Comment by ryan-mcneil** [comment]
@sethdarragile6 You've been granted access to all environments, with access to Production limited to 3 months, expiring 8/10/23

**Comment by ryan-mcneil** [comment]
Slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1683757417357259)
