### ISSUE TITLE
SOCKS access for Ryan McNeil

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#57803]
### Your Name

Ryan McNeil

### Your Email

ryan.mcneil@oddball.io

### Your Role and Team

Sofware Engineer on VA.gov Platform

### Product Manager (PM) name and email

Andrea Hewitt - andrea.hewitt@oddball.io

### Product Owner (PO) name and email

Ray Wang - gang.wang@va.gov

### Access Type Requesting

platform

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC40pxF+rpKudkTdIWoXgBTNQSrvvdUa20jdbZPBn7pr/uBQEIFY2Xcor+KzOUOGFE4zIb0x0BhFj5aWc/p3dbKYki2767dlPT4ormsQV66ENtIif1lBF2unjBQKUVbQTobjvUMNrC0gb/ez9ta8OaB9hIg6FTGGyo+3suMOOHOV6SeB/lEDcTG1tEmeWm3k0Zdk3Ba/AiP6yNut3PD7caPwjLQwI6Q+UddFPTi3HqqYDTK7+0lfrHbtBtqs2lnYw3LMp+YXVu2KbN/1v3xzyYNFA/AUz60whEbyqI1bEQKrffg4g3wOtREEHsWsb5dYA3v1dQZkDDP7sC8YZTj8lpgolT717u1tPUnpMNEveZoDImnAsd/Q0EjotQJQsF/eGzss/dHWq17/c+keLRMDV9i74HLdPjlwy3dCFsWhx5FBpDlOE6ucJApTKSupSVAjHDe+18KVzveuku9+PWbr92U8IIomIHEFp9YRhw/lmq979J5BBycCytord3LhAYl1RE= ryanmcneil@Ryans-Air.lan

### E-QIP Transmittal Confirmation

<img width="1007" alt="image" src="https://user-images.githubusercontent.com/41602677/235803932-59bb4126-98a4-4b42-bb70-39c643287746.png">

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [X] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by ryan-mcneil** [comment]
Platform Team 😄

**Comment by flooose** [comment]
@ryan-mcneil this should propagate through the system in the next hour.
