### ISSUE TITLE
OOB Deploy Request

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/va.gov-team#57806]
# Instructions
Please fill out the necessary details and list the PRs related to the OOB deployment in the sections below.

## PRs Related to OOB
- Please provide the list of PRs related to the need for this OOB Deploy below:
   https://github.com/department-of-veterans-affairs/vets-website/pull/24105
   https://github.com/department-of-veterans-affairs/vets-website/pull/24108 - updates downtime alert for more generic usage.

- Original PR where problem was created: 
 https://github.com/department-of-veterans-affairs/vets-website/pull/24033

## Active Daily Users Impacted
- How many active users are impacted at this time and day.
- Unsure of total impact at this time other than it is affecting production. A service down alert has been activated to prevent users from failing to update their direct deposit, but the issue was active for approximately 2 hours after today's daily deployment.

## Has fix been confirmed in Staging?
- [ ] Yes
- [x] No, ongoing

## Description
- Please provide the details/reason for the OOB Deploy
- there was an issue with the direct deposit update that was pushed out to production today.
Unfortunately there was a mandatory blank field that needed to have a dummy string passed into the request, and that string was removed. This resulted in updates to direct deposits failing with a 500 server error.
   
## Verify The following
 - [x] The OOB Deploy Request is after the 2pm EST cutoff for regular deploy.[^1] 
 - [x] The OOB Deploy Request is critical and must be resolved before the next automated deploy.
 - [x] You are prepared to create an Incident Post Mortem[^2] within two business days.

[^1]: (See [Deployment Policy](https://depo-platform-documentation.scrollhelp.site/developer-docs/deployment-policies) and [Deployment Schedules](https://depo-platform-documentation.scrollhelp.site/developer-docs/Deployments.1844641889.html)
[^2]: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/Postmortems

*Performed by Platform Support Team*
 - [ ] PagerDuty OOB Deploy Incident Opened
 - [ ] OCTO-DE staff acknowledgment of Request, via `/pd trigger`
 - [ ] Notification is posted in the appropriate Slack support and team Channels
 - [ ] Infrastructure/Operations has acknowledge the Requests
 - [ ] Security Team has Reviewed the requests

 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-product-support

**Comment by humancompanion-usds** [comment]
This all looks sane to me. Please proceed.

@adamwhitlock1 - This is the 2nd time a problem like this has occurred in recent memory where a string that was required was removed and not detected in testing. In the previous case I think a comment in the code would have been prudent and might have prevented the problem. Is there an opportunity to do the same here? If so, please do add a comment and point back to this breadcrumb trail. 

Also, and I realize we're getting into post-mortem territory, but is there a test for this that should have failed? This seems preventable with a test.

**Comment by adamwhitlock1** [comment]
I personally haven't seen an issue like this on our team, but 100% agree that this could have been avoided with further testing, and I take full responsibility for that. I have a branch open for adding further tests and will comment on the code to clarify the need to keep this dummy string on the api request body.

This particular api endpoint is being phased out and a new lighthouse based api is going to be used, which will not require this string to be passed into the request. That is what we are working on currently, and part of the reason this problem arose.

I will prepare a post mortem shortly. Thank you for your support on this.

**Comment by adamwhitlock1** [comment]
closing as post mortem was created and issue was resolved
