### ISSUE TITLE
Set Cancellable:false for Compensation and pension appointments

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#57824]
## Description
We will disable the cancellation link for compensation and pension appointments in `vets-api.` 

---

## Acceptance Criteria

- [ ] When the `serviceCategory = COMPENSATION AND PENSION`, then vets-api will send `cancellable: false` to the frontend

### Design Assets
N/A

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by ajmagdub** [comment]
Updated VAOS::V2::AppointmentService so that on retrieving appointments the cancellable field is set to false for Compensation and Pension appointments.

**Comment by ldelacosta** [comment]
Thanks @ajmagdub. Will validate this with #57748.

**Comment by ldelacosta** [comment]
Work is completed. No new issues. Closing out the ticket.
