### ISSUE TITLE
Fix burn pit link

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#57825]
Currently if you search for burn pit on va.gov (https://www.va.gov/search/?query=burn%20pit&t=false) and click on the top result, which is https://veteran.mobilehealth.va.gov/AHBurnPitRegistry, as a logged in user on VA.gov, you are not auto logged in. This is because we dont list the deeplink. We should modify this result to use the deeplink: https://eauth.va.gov/MAP/users/v1/landing?redirect_uri=/AHBurnPitRegistry/registry/

Any other locations on VA.gov that link to the burn pit should also use this deeplink.

**Comment by joeniquette** [comment]
I tested changing the URL in the search results to https://eauth.va.gov/MAP/users/v1/landing?redirect_uri=/AHBurnPitRegistry/registry/ for non-logged in users and the redirect still works fine and doesnt force the user into a sign in page. I recommend we change all links for that page to the MAP link.

**Comment by asg5704** [comment]
Update
- Found a bug in how the redirect is occuring which is why it redirects to the Burn Pit incorrectly

Will track all changes with this to include that bug.

**Comment by asg5704** [comment]
Update (see Slack thread https://dsva.slack.com/archives/C04MM3WJN1E/p1684781570293049)

### Content/IA
1. We can create a "search best bets" ticket (see [best bets](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/standards/search-best-bets.md)) for the Content/IA to update the URL for the Burn Pit link to point to the SSOe-enabled URL:
    1. https://eauth.va.gov/MAP/users/v2/landing?redirect_uri=/AHBurnPitRegistry/registry/

### eAuth/IAM
- We need eAuth to make a change to their code for authenticated vs unauthenticated user flow and a minor bug

Putting in the Block pending eAuth's change

**Comment by asg5704** [comment]
Update: Sent an email to IAM/eAuth & MAP team + Tom B. & Joe N. for requested changes. Moving to blocked (pending eAuth/IAM + MAP changes)

**Comment by asg5704** [comment]
Update: Received email from MAP team, they want to set up a time to talk and recommend not changing the URL to the direct eAuth link.

**Comment by asg5704** [comment]
Update: We are not fixing this

**Comment by aparsley** [comment]
Thank you for the update
