### ISSUE TITLE
Submission pages redesign

### ISSUE THREAD

**Issue by lydiahooper** [department-of-veterans-affairs/va.gov-team#57828]
This work is part of syncing with paper version of form
Had discussed doing user research for this work
Will need to go through collab 

Issue Description

This ticket is part of work required to get the digital 526ez form on va.gov synced with the paper version. The scope of this work is to prepare for design intent and user research for redesign of review/submit and post-submission pages. This redesign will involve user research, which could include discovery around a post-submission experience that ensures vet is able to submit all required info while still being able to submit additional/less necessary info at a later time. Redesign should include...

Review page changes:
- potentially highlighting user entries about homeless and terminally ill, in case status has changed since they started the application
- for BDD claims, to ensure date of claim fits within policy parameters-- consider whether to make active duty status an editable field on the review page

Additional page for: (this is the part to connected to paper sync)
- certification statement and required checkbox for certification 

Post-submission/confirmation page redesign/changes:
- link(s) to [ancillary forms](https://www.va.gov/disability/how-to-file-claim/additional-forms/) with instructions
- keep BDD SHA instructions
- info/alert about bank account info 

Notes:
- Testing of these pages should include new toxic exposure questions on review page
- Implementation of these changes during development will include removing bank account info screens, removing additional benefits screens (except for IU which will be moved to additional info section 4), and potentially moving POW question to earlier in flow (see notes with VBA on Jun 13)
- There are other tickets/issues that will need to be closed/resolved once implementation is complete, including this one: https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/59618
- This sheet explains ancillary forms decisions made with VBA and digital forms team in April 2023: https://docs.google.com/spreadsheets/d/1gYOQFXQxfacFIf5B0qb4-NGUDLvzVQ3oEMMNjvxk86I/edit#gid=0
Can communicate with digital forms team 

Tasks
- [ ] 

Acceptance Criteria
- [ ] Create ticket for collab cycle design intent

**Comment by lydiahooper** [comment]
@juliepedtke @nnicholas7 @austinjprice Would be curious to know if your team wants to take on this work sooner than later? CC: @RakshindaAslam

**Comment by evelynhilbrichdavis** [comment]
New initiative to improve the submission/post-submission experience will reevaluate this work.
