### ISSUE TITLE
Vets-api terminal access for Mark Chae

### ISSUE THREAD

**Issue by mchae-nava** [department-of-veterans-affairs/va.gov-team#57835]
### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Mark Chae

### Your GitHub handle (terminal access is managed through GitHub)

mchae-nava

### Team, Role, and Company of the target individual

Benefits Disability Experience

### Product Manager (PM) name and email

Rakshinda Aslam rakshinda.aslam@agile6.com

### Product Owner (PO) name and email

Matt Self matthew.self2@va.gov

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### COR Name (leave "None" if you listed an AWS user name above)

Delano McVay

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

Agile Six - Anthony M. Arashiro

### Access Expiration

ongoing

### Additional Notes

ongoing - project work/timeline is still TBD

prod access - BDex team has been encountering bug reports that would be much more easily diagnosed with real consumer data.

AWS access has been approved, but still waiting on an invite to create an account

### User must exist in a roster before vets-api terminal access can be granted

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added
- [ ] If they included an AWS user name, check to see if their user name is listed in [iam_users.tf](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf)
- [ ] Comment in this issue saying which roster the user is listed in and confirming their AWS user name (if applicable)

**Comment by mchae-nava** [comment]
Yup! On the VA ABD Team, I see myself on row 73 of the [VFS team roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)

**Comment by mchae-nava** [comment]
@ryan-mcneil Yup! On the VA ABD Team, I see myself on row 73 of the [VFS team roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)

**Comment by ryan-mcneil** [comment]
@mchae-nava Thanks for pointing that out. I must have fat-fingered when I was searching your name.

You’ve been granted access to the `dev`, `staging`, and `sandbox` environments.

Here's some additional documentation for the [Vets API on EKS](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-TerminalAccess)

Access to `prod` is pending approval by OCTODE, and we'll update you as soon as it's available.

**Comment by mchae-nava** [comment]
@ryan-mcneil Thank you! If it helps, we only need read-only access to prod

**Comment by ryan-mcneil** [comment]
@mchae-nava please confirm, but you should have read access by default. If write access isn't needed I can remove the access request. Thanks!

**Comment by mchae-nava** [comment]
@ryan-mcneil Is that the case? I've been hearing that there're separate read-only permissions and speculated they would be quicker to get. Read-write would still be ideal, I just put that out there in case it would help expedite our case.

**Comment by mchae-nava** [comment]
Perfect, thank you. I'll follow up with you sometime today!

**Comment by BillChapmanUSDS** [comment]
Was this request already sorted as per notes above?

**Comment by mchae-nava** [comment]
@BillChapmanUSDS Confirmed that we **do not** have any prod access, and will still need that approved

**Comment by ryan-mcneil** [comment]
@BillChapmanUSDS We've given access to lower envs, but prod access is still required, as stated in notes above. I'll add the label back, as you haven't given explicit approval, and I don't want this to be missed. Thank you.

**Comment by BillChapmanUSDS** [comment]
@mchae-nava  please add a screenshot of your EQip transmittal or other proof of transmission here and I can approve 3 months production access.

  I should note that in 3 months time we'd like to have an alternate solution suggested for this access. What specific consumer data do you need? A lot of non-PII interaction information can be mined from the logs in Datadog and Splunk and probably Google Analytics.  For Vets API database  that contains PII we could maybe suggest a  background job that pulls specific data and stores it appropriately as needed but that would need to be discussed.

**Comment by mchae-nava** [comment]
<img width="1108" alt="eQIP Transmittal notice" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/129200156/19cd063d-c354-4da0-ab65-2139e81b3aab">

@BillChapmanUSDS Our team has a growing backlog of bugs that are very difficult to definitely diagnose or sometimes even repro without some ability to cross reference actual consumer data. Read access would be sufficient, as would be your background job suggestion, if that can be set up or is in the works

**Comment by BillChapmanUSDS** [comment]
3 Month production access approved.

**Comment by ryan-mcneil** [comment]
@mchae-nava You've been granted access to all environments, with access to Production limited to 3 months, expiring 8/18/23

**Comment by mchae-nava** [comment]
Hello, can I request an extension for prod access? [My teammate also extended via comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/56501#issuecomment-1681334010), wanted to take that option as well, if possible

**Comment by mchae-nava** [comment]
@flooose @ryan-mcneil Hello, can I request an extension for prod access as well? [My teammate's ticket for reference](https://github.com/department-of-veterans-affairs/va.gov-team/issues/56501#issuecomment-1681334010), wanted to get in front of this, if possible

**Comment by ryan-mcneil** [comment]
@mchae-nava Thanks for staying on top of this! The support team will circle back in a couple days and grant your extension.

**Comment by bdech** [comment]
@mchae-nava  Per an update to our access policy, your ArgoCD/vets-api Production access has been extended for 3 months, expiring 11/17/23. Please set a reminder for yourself to return to this Issue and re-request access within 1 week of the expiration date. You'll receive 1 reminder with a 72 hour window to respond. Failure to do so will result in lost access and will require you to fill out a new request.

**Comment by lindsay-insco** [comment]
@mchae-nava Your vets-api terminal Production access has expired.

Would you like to request an extension? You have 72 hours to respond, or your
access will be revoked and you will need to fill out a new request

**Comment by lindsay-insco** [comment]
@mchae-nava it has been 72 hours with no response. Vets-API access has been removed.

If you need continued access please fill out a new request [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=external-request%2Cplatform-tech-team-support%2Cops-access-request&template=vetsapi-argo-terminal-access.yaml&title=Vets-api+terminal+access+for+%5Bindividual%5D)
