### ISSUE TITLE
Remove production BRD servers and autodeploy job

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#57831]
## Description

Since we've successfully moving to EKS, we no longer have a need for BRD servers. BRD servers are throwing disk errors, and they're no longer necessary. We can also now remove the Jenkins autodeploy job. 

100% of production traffic is going to EKS.

![Screenshot 2023-05-03 at 12.03.44 PM.png](https://images.zenhubusercontent.com/5d4836dda95c51615db9bdc9/8894e6bf-d538-4aba-9fb5-525af6ee80c8)

## Context
* Be sure not to clean up the one instance of `vets-api` that devs are still using -- `TEMPORARY-dsva-vagov-prod-deployment-vets-api-server-2nd`

## Action Items
- [x] configure ASG
- [x] Jenkins deploy will scale everything down during deployment 
- [x] Remove from code
- [x] Re-run seed job (devops perms)
- [x] Remove from UI (devops perms)
- [x] Additional cleanup (internal healthchecks, etc)

**Comment by laineymajor** [comment]
@rmtolmach , @RachalCassity is going to find some time with you on this... we don't have permissions to complete this work.

**Comment by laineymajor** [comment]
@pjhill we need to move this to the DevOps CoP backlog as no one on my team has permissions to do this work. If anyone has questions about it, reach out to @LindseySaari @RachalCassity (and @rmtolmach is aware of this work, too)

**Comment by laineymajor** [comment]
sent to devops CoP for approval

**Comment by pjhill** [comment]
Thanks, we'll plan to triage this in our DevOps COP meeting tomorrow.

**Comment by laineymajor** [comment]
Thanks Peter! Removing the tech team 1 tag

**Comment by LindseySaari** [comment]
I've [opened a PR](https://github.com/department-of-veterans-affairs/devops/pull/13125) here to remove the autodeploy job from code, but someone from Devops will need to remove the job from the UI

**Comment by LindseySaari** [comment]
PR merged and I've pinged Rebecca to re-run the seed job and remove the autodeploy from the UI
