### ISSUE TITLE
[FE] 1010EZ - Give continue button a disabled or loading state when clicked on ID Form page

### ISSUE THREAD

**Issue by longmd** [department-of-veterans-affairs/va.gov-team#57836]
## Description
For the ID form page that unauthenticated users use to access the application, there is no disabled or loading state for the continue button. If the server takes a bit of time to respond, the user could become confused and think that nothing is happening after click. We need to give this button a disabled/loading state while the server is verifying the form.

## Screenshot(s)
As is:
![Screenshot 2023-05-03 at 12.13.51 PM.png](https://images.zenhubusercontent.com/62054990e6d52fbafd985d41/9a72adbb-1de3-44a8-b478-f2300657aab3)

Desired result:
![Screenshot 2023-05-03 at 12.19.17 PM.png](https://images.zenhubusercontent.com/62054990e6d52fbafd985d41/ea6cbc5d-8729-47e4-a051-5e018bdbedf5)

## Acceptance Criteria
- Button gives a clear indication that an action is occurring after click

**Comment by longmd** [comment]
@davidakennedy or @jessicastump , do either of you have any guidance on what that text should actually be in the disabled state. At the end of the form, when the submit button changes, it just goes to "Submitting...". Here we aren't really submitting, but just validating the name, DOB and SSN. I was thinking something along the lines of "verifying" or "validating". Thoughts?

**Comment by jessicastump** [comment]
A lot of questions - I couldn't replicate the button text changing in staging to "Submitting", is it supposed to do that today? Only if the server is slow to respond? DS guidance doesn't seem to show button text changing for disabled state as an option and it does seem off. Also, not sure the loading indicator component makes sense as it is not loading additional content, but the Veteran's info is being 'verified'. What does 'verified' mean - is this checked against enrollment data to see if the Veteran already has health care? What does this mean to the Veteran?

**Comment by longmd** [comment]
1. Yea, so the button gives no indication anything is happening today. 
2. Correct, we are checking if the veteran is already enrolled in health care. 

The purpose of this ticket would be to give some indication that something is actually taking place and not creating any confusion or feeling that something is broken. The disabled state with the "Submitting..." text is what happens when you click the submit button at the end of the form, so my first thought is to mimic that same behavior but give some sort of meaningful label as to what is taking place.

**Comment by jessicastump** [comment]
What does the Veteran see if they **are already enrolled** in health care? 

similar to what is found on [this outdated Mural flow](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1632923531828/474bfdde942c22a0df26ad416a0b23e36b834d4a?sender=uadf1ed7fe7c76f0914967329) alerts?

**Comment by longmd** [comment]
The following alert is displayed: 
![Screenshot 2023-05-03 at 2 59 06 PM](https://user-images.githubusercontent.com/6738544/236016927-b2fc5f01-4955-42b9-9ac5-b84390ead694.png)

**Comment by longmd** [comment]
Also... that is not limited to just enrolled folks. If the response comes back with any of the following statuses EXCEPT "none of the above", the user will see that alert. 

![Screenshot 2023-05-03 at 3 01 29 PM](https://user-images.githubusercontent.com/6738544/236017555-58cd7fb8-0742-4e28-bb29-2c69b9e6ecd5.png)

**Comment by jessicastump** [comment]
Thanks for that context! Knowing that, would a loading or progress indicator stating "Reviewing your information" be more clear/plain language? Could also bring this to the next content office hours for their input too.

**Comment by longmd** [comment]
I think that's a perfectly good option, too. I'll leave it up to you if wanted to ask the content folks or not.

**Comment by davidakennedy** [comment]
Yeah, ➕ to the suggestion from @jessicastump. The tricky bit here is we don't tell them what's going to happen here. I think they may just assume that they're filling out the form, and they may not even think about it, unless it errors. So plain language is a good route.

**Comment by jessicastump** [comment]
Adding here what we chatted about during parking lot - let's go with "Reviewing your information" for that content so it is consistent with the alert the user could see next. 

Also noting - maybe all state messages should be added to the error content audit, expanding that work to capture any conditional or action based content seen.

**Comment by longmd** [comment]
@jessicastump / @davidakennedy , this is in staging if you would like to review.

**Comment by jessicastump** [comment]
Is the "Review" loading indicator supposed to show in both situations - when proceeding onto the next page for name and when the alert shows prompting them to log in? 

Also, saw this error below and wanted to make sure if this is a staging whoops or if this is an error that should be added to the audit.

![screencapture-staging-va-gov-health-care-apply-application-id-form-2023-05-10-13_04_03 (1)](https://github.com/department-of-veterans-affairs/va.gov-team/assets/98367393/21a9475a-ee28-4fc6-9f5d-358a46be0b03)

**Comment by longmd** [comment]
Yes, as soon as you hit continue and the API starts looking for your info, it will show. We don't know what the next step is until the API response comes back. That looks like the staging API encountered an error. It has nothing to do with this change.

**Comment by jessicastump** [comment]
Thanks! So don't add the "Something went wrong" error message to the audit file.
I think the loading state with the intended error message is fine.

**Comment by longmd** [comment]
OH... are you talking about your error audit for content for next week? If so, definitely go ahead and add it to the list.
