### ISSUE TITLE
Update Contributing to VA.gov Projects

### ISSUE THREAD

**Issue by humancompanion-usds** [department-of-veterans-affairs/va.gov-team#57842]
### Description

The list of individuals under the Contact header no longer work at the VA. ClareM is now Federal CIO. SuzanneC is back at USDS. Alex is now CTO at National Geospatial-Intelligence Agency. I don't know if this page is relevant any longer but we should not be directing folks to contact these individuals.

### Relevant URLs

[Contributing to VA.gov Projects](https://depo-platform-documentation.scrollhelp.site/developer-docs/contributing-to-va-gov-projects)

### Which type of team are you on? (Platform team, VFS team, or Leadership)

Platform-crew leadership.

**Comment by vbellissimo** [comment]
@humancompanion-usds Hi Matthew, thanks for submitting this request. The Platform Content team is currently taking a look at this for next steps.

**Comment by vbellissimo** [comment]
Vicky inquiring with Jason on how to update content to replace the current people listed as points of contact.

**Comment by jwoodman5** [comment]
@humancompanion-usds Hey Matt - do you know who replaced those folks?

**Comment by vbellissimo** [comment]
Hi @humancompanion-usds , we deleted the "Contact" paragraph on this page as per our [Slack convo here](https://dsva.slack.com/archives/CL181NRJQ/p1684243313074439). Let us know if you have any questions or need anything else. Thanks!
