### ISSUE TITLE
(Identity Auth Library - FE) Copy over SiS utilities (OAuth only)

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#57849]
## Issue Description
Copy over the Sign in Service utilities (which is OAuth only) into the following repo https://github.com/department-of-veterans-affairs/identity-sdk. 

_Note* This should only be for the OAuth (oauth/utilities and accompanying files) if you try to do (authentication/utilities) you're going to have a bad time because some of this includes SSO/SAML stuff so try to separate it as much as possible._

## Acceptance Criteria
- [x] Place utilities (OAuth utils) into the Utilities package in the above repo
- [ ] Ensure the utilities are tree-shakeable when imported
  - [ ] *Note: Turborepo or similar tool might take care of this for you
- [ ] Update `utilities` README documentation on usage

**Comment by asg5704** [comment]
@kingbmike This can be moved to backlog

**Comment by acald-creator** [comment]
I have a branch that I started on about a couple of weeks ago.

https://github.com/department-of-veterans-affairs/identity-sdk/tree/feat/migrate-components
