### ISSUE TITLE
[FE] 10-10EZ Typo found in content

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#57856]
## Issue Description
During content audit of h3/radio buttons task, found a typo in an additional info component on the medicare date page, third paragraph.

URL: health-care/apply/application/insurance-information/medicare-part-a-effective-date
Page: Medicare Effective Date

---
## Tasks
- [ ] Correct typo of "supplimental" to supplemental 

## Acceptance Criteria
- [ ] No longer a spelling error
---

**Comment by longmd** [comment]
@jessicastump , This update has been published to prod.
