### ISSUE TITLE
[FE] Update text in success alert for check in happy path complete page

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#57878]
## Description 

On the check in completion "happy path" page, change text in the success alert component to: 

> **We're processing your travel reimbursement claim.** We'll send you a text to let you know the status of your claim. 

Here is the sketch file for a visual of the success alert: https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/L40YYnQ

This change is based on [feedback from sitewide content during the unified check in experience review](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/L40YYnQ?annotation=29bf88bc-5190-4ba4-b06e-5d37be486242). We modified their suggestion. 

## Tasks

- [ ] Update content in the success alert for check in complete happy path 

## AC 

- [ ] Content has been updated

**Comment by benbrasso-agile6** [comment]
Waiting to ping Lori until we meet with sitewide content to double-check / confirm this direction.

**Comment by benbrasso-agile6** [comment]
Should be good enough to proceed for now. Can lump this into whenever engineers are doing bug fixes for travel.

**Comment by wullaski** [comment]
@benbrasso-agile6 this is ready to be validated on staging.

**Comment by benbrasso-agile6** [comment]
Validated
