### ISSUE TITLE
Get Drupal access

### ISSUE THREAD

**Issue by tygindraux** [department-of-veterans-affairs/va.gov-team#57889]
## Description
We need Drupal access so we can update and maintain the campaign landing page.

## Acceptance criteria
- [x] Carl, Sofia, Elizabeth have access to Drupal and can update/maintain Drupal pages

## Tasks
- [x] Access requested via [VAHELP-5758](https://va-gov.atlassian.net/browse/VAHELP-5758)

[VAHELP-5758]: https://va-gov.atlassian.net/browse/VAHELP-5758?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by elizabethkochBT** [comment]
Requested access via VAHELP-5761
