### ISSUE TITLE
Adding Nicole Lindbergh to DSVA Slack

### ISSUE THREAD

**Issue by nilinva** [department-of-veterans-affairs/va.gov-team#57897]
# Description

The user nicole.lindbergh@va.gov does not exist in the DVSA slack, and an account should be created and added to the slack.

I am requesting to be added as a single multi-channel full member to the Digital Service @ VA general channels and any channels related to Voicebot project. 

I am a contract software developer on the Voicebot project with BOOZ ALLEN HAMILTON. 

Thank you so much for your help!

**Comment by LEHigley** [comment]
hi there--i need to know if you'd like nicole.lindbergh@va.gov added as a full  member or multi-channel guest. if a multi-channel guest i need to know the specific channels. 

thanks!
