### ISSUE TITLE
SF Case 10002612

### ISSUE THREAD

**Issue by Kimberley2019** [department-of-veterans-affairs/va.gov-team#57943]
I have attempted on CHrome and Edge, after clearing the cache, cookies, etc.  

 

I am using ID.me (although it happens with DS Logon and my CAC as well) to verify.

 

Steps:  

1) Open VA.gov & select go to new home page (have tried using old home page as well)

2) Sign in using ID.me & authentication code sent to phone.

3) Click "File for disability compensation"

4) Select yes for "are you on active duty right now?

5) Fill in dates 07/31/2023

6) Click "File a BDD disability claim on line"

7) Message comes up.

 

Attached is a screen capture of the message, with URL.

 

Thanks again,

**Comment by Kimberley2019** [comment]
5/2/23 - Jeremy reached out to Chante and I for assistance with this issue.

5/2/23 - I sent email to Rakshinda, benefits PM for assistance.

5/2/23 – Rakshinda responded stating that this is different from other 2 cases sent previously.  Asked for more context on what the user did and what they saw before coming to the attached screen?

5/2/23 – Jeremy agreed different from other 2 cases previously sent to her regarding BDD claims

5/2/23 – Kim reached out to user with tier 3 template for more information

5/4/23 – He responded with information.

5/5/23 – Kim opened ZH ticket for tracking and responded to email thread with Chante, Jeremy, Rakshinda, Matt, and I on VA side.  Updated SF ticket.

**Comment by ATMiddleton** [comment]
Awaiting feedback from Benefits team

**Comment by Kimberley2019** [comment]
Hi Kimberley,

    This case is also tied to the same Zenhub ticket and Case # 09964639. The discovery of this issue has been completed and the fix is waiting on getting prioritized. I will send an update once it gets picked up for work. Thanks for your patience!

 

https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/57946

app.zenhub.comapp.zenhub.com

Zenhub

Zenhub | Productivity Management for Software Teams

**Comment by Kimberley2019** [comment]
Sync held on 6/13/23 with Matt Self, Lydia Hooper, Austin Price, Chante Lantos-Swett, Anita Middleton, and I.  
Action Items:
- Matt will send responses to the Tier 3 needed items for us to update our processes.
- Matt will send along Mural board for our review.
- Tier 3 will update process to start creating ZH tickets for issues instead of sending via email.

**Comment by Kimberley2019** [comment]
Original issue in case in being tracked in ticket.

https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/57946
