### ISSUE TITLE
[AFTER RESEARCH] SPIKE - Do we want to Allow Check in Text when No Appointments/Tasks

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#57954]
## Questions
When the Veterans texts "check in" but has no appointments for which to check in, do we want to still allow them to get to the unified experience and see their appointments and see that they have no tasks to complete right now.

## Description 

It's possible that at launch of the MVP that we're still supporting Veteran's texting "check in" to 53079. So, knowing that that's a possibility and, for the moment, let's assume a UUID is returned, what are the wireframes that are needed? 

Think through the different scenarios: 

- What if there are appts for today? 
- What if there are no appts for today? 

Likely, we need to create another version of our expired alert. 

## Tasks
- [ ] Think through this scenario and decide if we want to pursue it
- [ ] Create f/u tickets if needed

**Comment by benbrasso-agile6** [comment]
This is not a priority to complete before the Veteran research

**Comment by loripusey** [comment]
Don't need right now
