### ISSUE TITLE
[SSO-Login] Main content updates on VA.gov Health pages (non-alert box)

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#5795]
As a Veteran who is a patient at a facility using Cerner, I need content above and below the alert boxes on VA.gov health pages (Messaging, Medical Records, Prescriptions, Scheduling, Test Results) to either be facility agostic, or to give me accurate information about MHV or Cerner facilities, depending on whether I am logged in or not.

**Comment by christine-dillman** [comment]
Not Applicable to Identity/SSO.
