### ISSUE TITLE
[FE] 10-10EZ Content changes household section - Post QA

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#57959]
## Issue Description
A place to put any remaining income content changes that have been received during the remaining content review. Also to use for a place for any content errors and corrections found during initial QA.

[Sitewide Content IA Ticket
](https://github.com/department-of-veterans-affairs/va.gov-team/issues/52920)

[Comment with summary to date
](https://github.com/department-of-veterans-affairs/va.gov-team/issues/52920#issuecomment-1536795982)

### Page - Dependent’s educational expenses
Questions re-worded:
NEW: If your dependent is between 18 and 23 years old, were they enrolled as a full time student in 2022?
CURRENT: If your dependent is between 18 and 23 years of age, did they attend school during the last calendar year?

NEW: Enter the total amount of money your dependent paid for college, vocational rehabilitation, or training (like tuition, book, or supplies)
CURRENT: Expenses your dependent paid for college, vocational rehabilitation, or training (e.g., tuition, books, materials)

NEW: Did your dependent live with you in 2022?
OLD: Did your dependent live with you last year?

NEW: Did your dependent earn income in 2022?
OLD: Did your dependent earn income last year?

#### Page - Dependent’s support
NEW: Financial support for [dependent's name]
OLD: [First Last]’s support

NEW: If your dependent didn’t live with you last year, did you provide financial support?
OLD: If your dependent didn’t live with you last year, did you provide support?

OLD: Hint text
NEW: Additional info component
Label: What we consider financial support
Content: Please count all support contributions even if they weren’t paid in regular and set amounts. Support can include tuition or medical bill payments.

---
## Tasks
- [ ] Update review instance/staging with content changes.

## Acceptance Criteria
- [ ] All content changes listed here up to DATE will be made in staging for team review prior to running research study. 
- [ ] 
---

**Comment by hdjustice** [comment]
Revisit when QA Is complete (or almost complete)

**Comment by jessicastump** [comment]
Additional content updates after bi-weekly meeting 3/12:

**Dependent's support page**

New:
[headline] Financial support for [dependent's name]
[label] If your dependent didn’t live with you last year, did you provide financial support?

[additional info component]
What we consider financial support

We consider any payments, even if they aren’t regular or the same amount, to be financial support.
This includes payments for these types of expenses:

Tuition or medical bills
Monthly child or spousal support
One time payment financial support

OLD: 
[headline][First Last]’s support
[label] If your dependent didn’t live with you last year, did you provide support?
[hint text] Please count all support contributions even if they weren’t paid in regular and set amounts. Support can include tuition or medical bill payments.

**Comment by jessicastump** [comment]
### Content edits found during a staging QA review 5/16:

#### Page = {household-information/financial-onboarding}
PASS/No content edits

#### Page = {household-information/financial-disclosure}
**Content change needed**
Change label to question, only need Yes/No as answer radio labels

Do you want to share your household financial information? (*Required)
Yes
No

#### Page = {household-information/financial-information}
PASS / No content edits

#### Page = {household-information/financial-information}
**Content change needed**

Bold first part of sentence for each paragraph
[design Sketch file](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/GomvmqL)

---

#### Page = {household-information/marital-status}
PASS / No content edits

#### Page = {household-information/spouse-basic-information}
**Content changes needed**
- Remove “please” at beginning of intro text
- Missing SSN field (on mock, on paper form)

#### Page = {household-information/spouse-additional-information}
PASS / No content edits
SME Question 

#### Page = {household-information/spouse-financial-support}
PASS / No content edits
SME Question 

#### Page = {household-information/spouse-contact-information}
- Question about State/Province/Region label in design vs. just State in staging

---

#### Page = {household-information/dependents}
**Content edits needed**
- Remove headline "Dependents"

#### Page = {household-information/dependent-information?index=0} = Basic Information
**Content changes**
Current headline: Dependent - basic information
TO UPDATE TO: Dependent’s basic information

#### Page = {household-information/dependent-information?index=0} = Educational Expenses Page
**Content changes**

- See [content changes in ticket description](https://github.com/department-of-veterans-affairs/va.gov-team/issues/57959#issue-1698216436)

#### Dependent's Additional Information Page
**Content changes**
Two questions content updates: Replace that year with in 2022
Did your dependent live with you in 2022?
Did your dependent earn income in 2022?


#### Dependent Financial Support
[See content review 5/12
](https://github.com/department-of-veterans-affairs/va.gov-team/issues/57959#issuecomment-1546242340)

#### Dependent Modals
Cancel editing Modal
Bold First Last name of dependent

Cancel adding Modal
PASS

Cancel editing Modal
PASS

#### Annual income and deductible content 
Review pending

**Comment by jessicastump** [comment]
### Content updates received 5/19

**Financial support for dependent page:**
- Replace "This" with "Financial support" in additional info component, bold text
- Hyphen for "one-time"
- [Sketch file link](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/mPPqJ2L)

**Comment by jessicastump** [comment]
### Content changes 5/19 for Annual Income pages 
_Use for Veteran's income page, spouse's income page and for dependents income page with slight label variations, see Sketch links_

[H3] Your annual income from 2022

[p.bold or fieldset label] Gross income from work
[hint text] Gross income is your income before taxes and any other deductions are subtracted.

[Additional info component] 
[label] What we consider gross annual income 
[content]
[p.bold]Gross income includes these types of income from a job:
[ul]
- Wages 
- Bonuses 
- Tips 
- Severance pay  
[END additional info component]
[field label] Enter your gross annual income from 2022

[p.bold or fieldset label] Net annual income from your farm, property, or business 
[hint text] Net income is your income after any taxes and other deductions are subtracted.
[label] Enter your net annual income from a farm, property, or business from 2022

[p.bold or fieldset label] Other income  
[hint text] TBD
[additional info component]
[label]What we consider other income 
[content]
[p.bold] Other income includes things like:
[ul] 
- Retirement benefits
- Unemployment
- VA benefit compensation
- Money from the sale of a house
- Interest from investments.
[END Additional info component]

[label field] Enter other income from 2022 


Sketch links
- [Veteran's annual income - add info open](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/3oKK9zd)
- [Veteran's annual income - add info closed](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/4ognGMJ)
- [Spouse's annual income](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/r9qq3VK)
- [Dependent's income](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/WddpxZ0)

**Comment by hdjustice** [comment]
### Review Page - Household section, Income & Deductibles - Number/Currency formatting is not consistent 
- Income amounts are showing as numbers with no dollar signs ($) or decimal points
- Deductible amounts are showing as currency with dollar signs and decimal points

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/92328831/371b8198-539a-4115-85f8-90669419d19e)

**Comment by jessicastump** [comment]
### Content changes to Deductible Expenses page

[Sketch file mobile design](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/v/8b1vv7/a/JA88E27)

[Page headline] Your deductible expenses from 2022

[p] (Remove alert component, use plain text)
**Note:** We understand in some cases your expenses might be higher than your income. If your expenses exceed your income, we’ll adjust them to be equal to your income. This won’t affect your application or benefits.

[p bold]Non-reimbursable medical expenses
[additional info component label] What we consider non-reimbursable medical expenses 
[add info content] Non-reimbursable medical expenses include costs you or your spouse paid for these types of health care for yourselves, your dependents, or other you have the moral obligation to support:
- Doctor or dentist appointments
- Medications
- Medicare or health insurance
- Inpatient hospital care
- Nursing home care 
[end additional info component]
[input label] Enter the amount you or your spouse paid in non-reimbursable medical expenses in 2022 *Required

[p bold] College or vocational education expenses
[additional info component label] What we consider college or vocational expenses 
[add info content]
College and vocational expenses include payments for these expenses related to your own education: 
- Tuition
- Books 
- Fees 
- Course materials

Only include expenses for your own education (not your dependents' education).
[end additional info component]

[input label] Enter the amount you paid for your own college or vocational education in 2022 *Required


[p bold]Funeral and burial expenses for a spouse or dependent child who died 
[hint text] Funeral and burial expenses are any payments made by you, like prepaid expenses.
[input label] Enter the amount you paid for funeral or burial expenses in 2022 *Required

**Comment by jessicastump** [comment]
Tagging example for income and deductible pages:

<img width="340" alt="html annotations screen shot" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/98367393/fe1d0a52-d3e8-4708-8551-d3220e339773">

**Comment by hdjustice** [comment]
@longmd @jessicastump - Are we ready to pick this up yet?  QA has been done on most of the changes (i think the error ticket is still in progress).  Looking to see if we can put in next sprint to get done.  Once done (or close to) I want to engage ES team to test, would like to have that before staging review

**Comment by longmd** [comment]
@hdjustice , I will be ready for this next sprint, for sure. The error ticket will rollover slightly, but would love to do this on the heels on that ticket.

**Comment by jessicastump** [comment]
From a content review, this is good to go. 
Just need to circle back to Aliyah and Danielle after we get answers back from stakeholders (the various SME questions) - those answers we get could then result in a couple more minor content changes. Given timing, might be best to open those, if any, as a new ticket.

**Comment by hdjustice** [comment]
I think Alex has the notes from that meeting, he is looking into that, but might be tomorrow morning since he is out the rest of today

**Comment by hdjustice** [comment]
Reached back out to Stakeholders today - pending resp

**Comment by hdjustice** [comment]
@jessicastump - were there any other content changes based on the answers we got back from the business?

**Comment by hdjustice** [comment]
@longmd  The only thing I saw missing from this ticket that is not showing in Staging is one line on the Deductibles page.  
The [comment ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/57959#issuecomment-1563186511) states to add a line to the College or vocational education expense accordion.

- **Currently in Staging**
- ![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/92328831/066f074f-9f68-4d9f-80f6-2ba68bafedf6)

- **In the comment and Sketch**

> [add info content]
> College and vocational expenses include payments for these expenses related to your own education:
> 
> Tuition
> Books
> Fees
> Course materials
> Only include expenses for your own education (not your dependents' education).
> [end additional info component]

- ![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/92328831/f35bf39f-ef8f-4cfe-9a07-d811338128ca)

**Comment by jessicastump** [comment]
Went through this in staging and a couple of things:

Content did have the suggestion to relabel to "household financial information" is that a huge structural change or a minor content change?

Edits needed:
- Label on fields on spouse address/contact info page. The Sketch file/Design System use State/Province/Region. Should it be that way consistently across the form? Or is there a reason to only use State?
- Same page, update label of "phone" to "Phone number" on spouse contact page

- Dependent's additional info dropdown some text was cut off (in bold). But did not see again on the review dependents page.. "They're living with a permanent disability that happened **before they turned 18**"

- Headline missing on multiple dependents add/review page.  "Review your dependents"

Non-content items to note:
- On the modal, for cancel adding, there was some odd spacing. The buttons were an odd width and there was no spacing between.
<img width="483" alt="Screenshot 2023-06-27 at 2 10 21 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/98367393/5aaba835-3c28-4d10-8fb0-39b000e8450a">
- On the review page, there was an odd bullet showing:

<img width="632" alt="Screenshot 2023-06-27 at 2 33 48 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/98367393/7ffbd680-d45c-429f-8775-b772a43edfbd">

**Comment by jessicastump** [comment]
@hdjustice - Regarding what we learned for the SME questions from stakeholders, none of the content edits are impacted - and if anything comes up in the future that is separate work/tickets.

**Comment by jessicastump** [comment]
Also adding to this ticket I marked the instances of when the exact year is used (2022 in mockups) in the Sketch file (mobile screens). I will work on writing this up so we have it to reference in Sketch and GitHub. 

And the exact year is used 25 times throughout the household section

**Comment by hdjustice** [comment]
Validated content changes.  Findings from 6/27 are in a separate ticket #61038
