### ISSUE TITLE
Update SOCKS Access Guidance

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#57968]
# Description
Corry Trimm provided this comment -- https://vfs.atlassian.net/wiki/spaces/GS/pages/1821081710?focusedCommentId=2624684034 in the [document](https://vfs.atlassian.net/wiki/spaces/GS/pages/1821081710/Accessing+Internal+Tools+via+SOCKS+Proxy) describing how to gain SOCKS proxy access to users.

* How might we best address Cory's comment?
* Are there other updates that we should make to the document?

# Acceptance Criteria
- [x] Cory's comment has been addressed
- [x] Cory's comment is marked as resolved in Confluence
- [x] GHA workflow is implemented that scans user input for if it is a public key -- if not then throw a warning into the issue in the form of a comment; set label to `not yet`

**Comment by rmtolmach** [comment]
This is slightly different, but related to https://github.com/department-of-veterans-affairs/va.gov-team/issues/58282. We're making a SOCKS troubleshooting guide, specifically for people on Support to use when users have SOCKS questions.

**Comment by pjhill** [comment]
@hgbarreto -- to verify that the proposed changes address Cory's comment sufficiently

**Comment by pjhill** [comment]
We could create an event driven GHA workflow that scans the ticket created for SOCKS requests for whether the user has provided their key as an input.

Is it a valid public SSH key?
If yes -- yay
If no -- you have accidentally published your private key

**Comment by pjhill** [comment]
Link to GitHub -- https://github.com/department-of-veterans-affairs/devops/pull/13198

**Comment by rmtolmach** [comment]
I was making edits to the SOCKS page in Confluence for a different ticket and so I just added a Warning panel to [the doc](https://vfs.atlassian.net/wiki/spaces/GS/pages/1821081710/Accessing+Internal+Tools+via+SOCKS+Proxy). It should be live on the Platform Website tomorrow afternoon. Feel free to change it up.

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/10993987/0a28aa5d-e5e2-4c7c-9b8d-5f352e11fa30)

Hopefully this + the GHA Chris is working on will cut down on PATs being included in SOCKS issues.

**Comment by pjhill** [comment]
PR approved, looking to get this merged before end of sprint.
