### ISSUE TITLE
DISCOVERY: Prep vets-api for maintenance mode

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#57993]
### PROBLEM STATEMENT
Once vets-api is deemed stable, and all outlined automation work is complete, vets-api will be moved to `maintenance mode` and be passed to the backend and devops CoPs. In order to set vets-api up for success when moving to `maintenance mode` we want to ensure the maintaining teams have the best information possible, allowing them to maintain to product (vets-api in EKS).

### ACTIONS
- [x] @rjohnson2011 will review all current vets-api (EKS) documentation and note areas where improvement/clarification is needed. Ryan is part of the BE and was recently on support. Having his fresh perspective will help TT1 gauge where additional clarity is needed.
- [x] @laineymajor to 'interview' Ryan Johnson (from BE) and a member of the devops CoP to determine what would be helpful to include in a vets-api maintenance guide.
Documentation is up to date and easy to understand

### DEFINITION OF DONE
- [x] [List](https://vfs.atlassian.net/wiki/spaces/TT1/pages/2638250053/DISCOVERY+PREP+FOR+VETS-API+MAINTENANCE) of "areas of improvement and clarification" needed for vets-api documentation
- [x] An outline of _what_ would be helpful to include in a vets-api maintenance guide for the CoPs that will be supporting vets-api while in maintenance mode
*[doc](https://vfs.atlassian.net/wiki/spaces/TT1/pages/2633662753/External+Secrets) started by Rachal
*cron job [doc](https://vfs.atlassian.net/wiki/spaces/TT1/pages/2564325465/Rails+CronJob) started by Rachal

**Comment by LindseySaari** [comment]
Rachal is going to create a guide around PR reviews in the manifest repo, which stems [from this thread](https://dsva.slack.com/archives/CBU0KDSB1/p1683904098334329). There have been many issues in the past week. We could also benefit from a similar training guide and to start training other devs in relation to the new EKS deployment structure.

**Comment by laineymajor** [comment]
@laineymajor to update per meeting with rebecca and jeremy

**Comment by laineymajor** [comment]
https://vfs.atlassian.net/wiki/spaces/TT1/pages/2638250053/DISCOVERY+PREP+FOR+VETS-API+MAINTENANCE
