### ISSUE TITLE
Health-content.md question

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#58]
Hi @DanielleSoCompany and @RLHecht 
Please look at note below. You can see this page in context here: https://department-of-veterans-affairs.github.io/vets-design-system-documentation/content-style-guide/health-content
Please note ^ there are a couple line break errors right now that Jared's fixing before deploying. 

In the original Vets.gov repo version, tip #5 was "Provide reassurance, especially for sensitive issues..." which was a little repetitious of tip #4 "Provide brief reassurance...." 
 
### 5. Give hope ***[ @DanielleSoCompany - I wasn't sure what to call this one, so that it's not just a duplication of #4. Any preference for approach? /jl]***
Especially for sensitive issues, provide reassurance that the reader is not alone and that there's hope for their condition.

This may come in the form of:
•	Brief statements about the condition, such as:
o	“Depression is a serious illness. But this common mental health condition is also highly treatable.”
o	“If you’re struggling with substance use, you’re not alone.”
•	Quotes or stories from others living with the condition
•	Links to communities and advocacy groups for people living with the condition

**Comment by jenniferlee-dsva** [comment]
@DanielleSoCompany - assuming the ^ was fine as is? (Regarding point 5 ^.) If you don't agree or would like to make a suggestion, lmk. Otherwise I'll close this.

**Comment by DanielleSoCompany** [comment]
Hi @jenniferlee-dsva. Apologies for delay! I looked at this, and then got distracted...

What do you think about this?

**4.** Provide brief reassurance of medical expertise

**5.** Destigmatize sensitive conditions and build hope

**Comment by RLHecht** [comment]
@jenniferlee-dsva This looks like this has been completed on the live site so @Karak888 should be able to close the issue.

**Comment by jenniferlee-dsva** [comment]
Yes, thanks for confirming.

**Comment by Karak888** [comment]
closing per above confirmation.  Thanks
