### ISSUE TITLE
Research Ticket: Platform Support Team Analytics Overhaul

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#58005]
This ticket is for the research of metrics that can be pulled into a dashboard to improve Platform Support's operations and efficiency. We are seeking to track the following metrics:

- Support Requests Received
- Support Requests Completed
- Initial Response Time (Hours/Days)
- Time to Resolution (Hours/Days)
- Tickets Per Support Person
- Number of Tickets in Backlog
- Percentage Increase/Decrease of Tickets in Backlog (WoW)
- Ticket Buckets
- Percentage of Tickets Erroneously Sent to Support (manual calculation or can it be automated)?

<b>See below screenshot for additional context.</b>

![Screenshot 2023-05-08 at 12.18.10 PM.png](https://images.zenhubusercontent.com/634f039195964c85374018cc/234b38dd-1ffa-4d4e-80cc-289197073fa9)>

*Note: This request was submitted as a result of a private DM with Michelle Dooley.

**Comment by michelle-dooley** [comment]
@ChristineYoungZA - for your discovery work...

GH data:  review [github_issues](https://console.cloud.google.com/bigquery?project=vsp-analytics-and-insights&ws=!1m5!1m4!4m3!1svsp-analytics-and-insights!2svsp_testing_tools!3sgithub_issues) data - do we have what we need to answer above questions?  This is the dataset that is feeding the Collab Cycle and Platform Website dashboards (below)

To see how other platform teams are using GH data:

[Collab Cycle dashboard](https://va-gov.domo.com/page/1340527018)

[Platform Website Git Hub Support dashboard](https://va-gov.domo.com/page/189282309)

**Comment by michelle-dooley** [comment]
Hey @alyssagallion - [Here](https://docs.google.com/spreadsheets/d/1HVtCjYCq57yaVu8jdbFYXyg9AHc1XXtyl29d2Vrg6fE/edit#gid=0) is what we have determined based on your requested metrics.  I think we are good on most if it just need to get "Pipelines" added.  

Couple questions:
Are there specific labels you are interested in or all?
For ticket buckets, is there a place in the GH ticket that would tell us that?

**Comment by michelle-dooley** [comment]
Hey @alyssagallion - I'm going to close this ticket since discovery is complete.  I will reach out regarding next steps.
