### ISSUE TITLE
DISCOVERY: DO WE NEED THIS? [Datadog] Set up duration/latency monitor and alert for EKS Clusters

### ISSUE THREAD

**Issue by it-harrison** [department-of-veterans-affairs/va.gov-team#58014]
# Description
We need to create a duration (ala the RED methodology) to monitor EKS:Clusters. 

# Acceptance Criteria
- [ ] A duration/latency monitors is created, if appropriate
- [ ] Alerts are created, if appropriate

# Notes
The other aspects of RED for EKS:Clusters were created in a [previous ticket](https://app.zenhub.com/workspaces/platform-tech-team-2-633efe4ca5a428e5294d7ade/issues/gh/department-of-veterans-affairs/va.gov-team/49291) but attempts to implement a duration/latency monitor failed because the output of the monitor were very large value, whereas latency should be << 1 second. There seems to be a mismatch in the window between the two metrics used in the monitor:
* `kubernetes.kubelet.runtime.operations.duration.sum`
* `kubernetes.kubelet.runtime.operations.duration.count`
But we were not able to determine how this mismatch is occurring or how to fix it.

**Comment by npeterson54** [comment]
Should we be reaching out to Datadog regarding this? 

@hgbarreto would like to take a crack before reaching out to DD

@ph-One do we need this?

**Comment by ph-One** [comment]
If the Kubelet is struggling, there are other monitors and alerts that will trigger. This is not needed, unless a very specific use case is found, and then we can reopen the ticket
