### ISSUE TITLE
Update user flows

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#58026]
## Task Description
Review the current user flows in VAOS and update the screens to match Staging and the copy docs:
- If any screens are out of sync, update them in the user flow. You can use either screengrabs or copy screens from the templates file if they're up to date.
- Error states are out of scope. If you see differences in error states, add a comment to the user flows.

## References
- [User flows](https://www.figma.com/file/xRs9s6QWoBPRhpdYCGc3cV/User-Flow?type=whiteboard&node-id=0%3A1&t=Gb2N9BmAYumZBIGW-1)
- [Staging URL](https://staging.va.gov/)

## Acceptance Criteria
- [x] User flows updated

**Comment by melissa-lefevre** [comment]
@outerpress I updated every screen with a green thumbs up. Can you please take a look and see if it looks good and I will delete the thumbs and close this ticket.

**Comment by outerpress** [comment]
Looks good @melissa-lefevre ! I cleaned up some of the connecting lines, but all the screens look good to go.

**Comment by melissa-lefevre** [comment]
Closing this
