### ISSUE TITLE
Move user flow screen files into templates

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#58020]
## Task Description
The User Flow Screen Files document duplicates work in the VAOS Templates document. 
- Move screens from Screen Files into the appropriate location in Templates
- Update screen copy to match the copy docs
- Once screens are captured in the Templates, delete them from the Screen Files document. 

## References
- [User flow screen files](https://www.figma.com/file/qFinQDFCkI7ibpSBAm1TOk/User-Flow-Screen-Files?type=design&node-id=0%3A1&t=j7nerVfsWd4cdz5K-1)
- [User flow Figjam](https://www.figma.com/file/xRs9s6QWoBPRhpdYCGc3cV/User-Flow?type=whiteboard&node-id=0%3A1&t=vjOE7PPLTKxcHksB-1)
- [VAOS templates](https://www.figma.com/file/twogqAIoOL9WAFRqvUbwiS/VAOS-Templates?type=design&node-id=0%3A1&t=zpfJ8FalwxH6h0iN-1)
- [Copy docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/appointments/va-online-scheduling/content/copy-docs)

## Acceptance Criteria
- [x] All relevant screens in the Screen Files document are captured in the Templates document
- [x] The screen files document has been deleted.

**Comment by melissa-lefevre** [comment]
I either moved or recreated screens to the VAOS Templates file.
