### ISSUE TITLE
allow list link broken

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#58029]
### Description

On this [E2E Stress Test and Allow List documentation page](https://depo-platform-documentation.scrollhelp.site/developer-docs/e2e-stress-test-and-allow-list), the link to [allow-list.yml](https://github.com/department-of-veterans-affairs/qa-standards-dashboard-data/blob/master/.github/workflows/allow-list.yml) is broken. It appears that the list was split into [allow-list-notify.yml](https://github.com/department-of-veterans-affairs/qa-standards-dashboard-data/blob/master/.github/workflows/allow-list-notify.yml) and [allow-list-publish.yml](https://github.com/department-of-veterans-affairs/qa-standards-dashboard-data/blob/master/.github/workflows/allow-list-publish.yml)

### Relevant URLs

- [Additional Notes](https://depo-platform-documentation.scrollhelp.site/developer-docs/e2e-stress-test-and-allow-list#E2EStressTestandAllowList-AdditionalNotes)

### Which type of team are you on? (Platform team, VFS team, or Leadership)

VFS team - Benefits decision reviews

**Comment by vbellissimo** [comment]
Hi @Mottie , thanks for your support request. The Platform Content team is reviewing this for next steps.

**Comment by vbellissimo** [comment]
Slack support thread: https://dsva.slack.com/archives/CBU0KDSB1/p1683649289350609

**Comment by vbellissimo** [comment]
Hi @Mottie, we've updated that section of the page you referenced with the help of a Platform technical SME. We will be closing this ticket now. Thanks for the feedback!
