### ISSUE TITLE
vets-api session key rotation process

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#58024]
### Summary
The Backend CoP is supposed to rotate the vets-api session keys monthly. Do we need to be rotating keys in all environments? The docs do specify all environments, but @jeremy6d and I were wondering if this was necessary, or if we really just needed to rotate the `prod` keys. 

Note: Looking at the history in AWS parameter store, we can tell this hasn't happened monthly. It's possible that if this task was _just_ for `prod`, it might be more approachable and less time consuming? 

### Links
- Internal docs for this process: https://vfs.atlassian.net/wiki/spaces/VI/pages/1766621207/Session+Key+Rotation+for+Vets+API
- History: First implemented in https://github.com/department-of-veterans-affairs/va.gov-team/issues/23867

### Tasks
- [x] reevaluate the environments in which we need to rotate the vets-api session key
- [x] reevaluate the frequency in which this task is done. (Ask security?)

**Comment by stevenjcumming** [comment]
Based on NIST Recommendation for Key Management ([source] (https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-57pt1r5.pdf)) 

Section 5.3.6 9b (page 42)
> Cryptoperiod: An appropriate cryptoperiod for a symmetric master key might be one
> year, depending on its usage environment, the sensitivity/criticality of the information
> protected by the derived keys, and the number of keys derived from the master key.

The recommendation suggest that the secret_key_base should be rotated yearly. However, it doesn't provide a distinction between production & non-production environments, nor provides a lower-bound frequency. So my recommendation is yearly for non-production environments and monthly for the production environment.
