### ISSUE TITLE
Code Owners - Outline process to shift FE code review ownership to VFS Teams

### ISSUE THREAD

**Issue by brandonrapp** [department-of-veterans-affairs/va.gov-team#5803]
As the VSP platform, we need a systematic process for VFS teams to decide on and implement changes in GH to enable the shifting of responsibilities for front end code reviews from the VSP platform to each VFS team.

- [x] Ensure to document how teams will update GH to make the necessary code owner changes
- [ ] Work with Product Support to integrate this work into the on-boarding\off-boarding processes
- [ ] Demo how to make code owner changes to VSA team leads

Measuring Success:
- 100% of VFS teams switch their code reviewers from VSP to their own team

**Comment by rianfowler** [comment]
Code owners stuff: https://github.com/department-of-veterans-affairs/va.gov-team/pull/5907

**Comment by rianfowler** [comment]
can we close this?
