### ISSUE TITLE
SOCKS access for Brandyn Sullins

### ISSUE THREAD

**Issue by OptionSelect** [department-of-veterans-affairs/va.gov-team#58043]
### Your Name

Brandyn Sullins

### Your Email

brandyn.sullins@govcio.com

### Your Role and Team

Front End Engineer on Debt

### Product Manager (PM) name and email

Tom Davis

### Product Owner (PO) name and email

Matt Self

### Access Type Requesting

automation

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDDvSukmUjuk8qqrShdm7aGKtKCSJBaLQpTgj8UBrGqfU+cKgY8/b2M5wXs48bj1S3jk2qpts+VzxpiIYKSFvxp/vkbmhEoI4lER+6zEiRacYz7qBnDhu2Mo3bnUVB6IVtOgKjKscdwN3BwuMIth676GwAdyrmLjjm4UwSKaD1uE+4Drll3T+h2QcxJBGNPgARfffHlFSeMRtTAnq4FVMctHOI74k7xY7e9Ak8LITVv3piHJgjW7s6GMYVpueh11ysPa0LwnJjr74nwA1nof/MBU84iCJyLDwncrZyQ9OwANq2gNAVJeDloLmyb6EMAxcCV1SV/0riae9DpA/W3Geb9uE22YJRPwtw48UiVYOEPm3mzmH2rpa0fX+CWH8vyAsN0a0JpOkAUco0mdTg+pHKIHSwMt3XoE41fCr7tmI7FWGiv/cOfotfNnokuhHUs2AB+Tnc07pbZtqeg0lBzbgeXn1/osGTDE1ROXl0uBab4AVs/RKRBjlpzWR41c+HsbSk= brandyn.sullins@FVFH47G7Q05N.lan

### E-QIP Transmittal Confirmation

N/A

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by flooose** [comment]
Got it done! Thanks you @rmtolmach for pointing out the wrong location in the yml file! 🚀

**Comment by rmtolmach** [comment]
oh wow, I'm glad that did the trick! Makes me wonder if any of those other users listed in the `automation` section have socks access 🤷
