### ISSUE TITLE
686c | [technical discovery] Investigate "Incident Flash" error

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#58045]
## Issue Description

See [Sentry](http://sentry.vfs.va.gov/organizations/vsp/discover/results/?field=count%28%29&field=message&field=error.value&name=Top+Errors&query=%28controller_name%3Adependents_applications+OR+SubmitForm686cJob+OR+SubmitForm674Job+OR+job%3ABGS%3A%3ASubmitForm686cJob+OR+job%3ABGS%3A%3ASubmitForm674%29+AND++level%3Aerror+AND+message%3A%22%2AFlash%2A%22&sort=-count&statsPeriod=30d&widths=-1&widths=-1&widths=-1) for frequency. 

Here's [an example](http://sentry.vfs.va.gov/organizations/vsp/discover/platform-api:4c208e9f47e94a94a3c5251226ab7d4b/?field=timestamp&field=message&field=error.value&name=Most+Recent+Errors&query=%28%28controller_name%3Adependents_applications%29+OR+%28SubmitForm686cJob%29+OR+%28SubmitForm674Job%29+OR+job%3ABGS%3A%3ASubmitForm686cJob+OR+job%3ABGS%3A%3ASubmitForm674%29+AND++%28level%3Aerror%29+AND+%21message%3A%22%2Aget_dependents%2A%22&sort=-timestamp&statsPeriod=24h&widths=-1&widths=-1&widths=-1) of an individual Sentry error.

We get this error about 0.6 times a day. 

![image](https://user-images.githubusercontent.com/7520103/236927542-9c8f1d58-7549-49a9-9b0e-349697c0b662.png)

Additional detail from Michael Taylor: Incident flash - this is a HARD stop for the entire application process. These [VA.gov](http://va.gov/) users asked VBA to set up a fraud flag to prevent online transactions. We need to stop the application process and have them write us in paper to remove the flash.

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---

**Comment by saderagsdale** [comment]
@data-doge I moved this into the PB for refinement. Before Our refinement on Thursday, can you add the DOR and DOD to this story?

**Comment by tblackwe** [comment]
[New Sentry Link](http://sentry.vfs.va.gov/organizations/vsp/discover/results/?field=title&field=event.type&field=project&field=user.display&field=timestamp&name=All+Events&query=%28controller_name%3Adependents_applications+OR+job%3ABGS%3A%3ASubmitForm686cJob+OR+job%3ABGS%3A%3ASubmitForm674%29+AND+level%3Aerror+AND+message%3A%22%2AFlash%2A%22&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1)

**Comment by tblackwe** [comment]
@tfink419 @evansmith if you get a chance, could you add this to your list of tickets to research?

**Comment by tblackwe** [comment]
These occur almost daily, BIS ticket being opened for research

**Comment by tblackwe** [comment]
INC29294067 created to research

**Comment by steele-lm** [comment]
Ticket to capture email changes is #56291
