### ISSUE TITLE
Bug - Fix - Required validation error not displaying for BDD Supporting Evidence

### ISSUE THREAD

**Issue by christinec-fftc** [department-of-veterans-affairs/va.gov-team#58050]
#### What I expected to happen

1. Start a new BDD claim
1. On the 2nd Supporting evidence view, (page is "/disability/file-disability-claim-form-21-526ez/supporting-evidence/evidence-types-bdd"), select Yes for "Is there any evidence that you’d like us to review as part of your claim?", but do not select any checkboxes
1. Click Continue
1. Validation error feedback displays 'Please select at least one type of supporting evidence'

#### What _SHOULD_ happen
Above steps, but error is not displayed. This could be confusing for users. They will not know how to proceed unless they make a different selection (select one of the checkboxes or No)

Error is reproducible on staging

#### Screenshots or Supporting Evidence
![image.png](https://images.zenhubusercontent.com/641341411444ec27c3eb60a4/45874dea-951f-4d35-88d2-4423e5176eb5)

#### Severity of the issue
- [ ] High severity
- [ ] Medium severity
- [ ] Low severity

#### Visibility
- [ ] User visible
- [ ] Stakeholder visible

#### MR Approver
- TBD

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RakshindaAslam** [comment]
cc @RakshindaAslam

**Comment by mchae-nava** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/24402
Branch: bdex/58050-evidence-validation-error

This is being put back in to the backlog while we await design updates

**Comment by mchae-nava** [comment]
@lydiahooper do we have an open design ticket I can link this to?

**Comment by lydiahooper** [comment]
@mchae-nava hope to address this with this design ticket next sprint: https://github.com/department-of-veterans-affairs/va.gov-team/issues/58793
