### ISSUE TITLE
Add filter options to YR MVP

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#5805]
Update prototype to include filtering on search results. Will depend on the work @kelsonic does for the new endpoint, not totally sure what the options are at this point.

**Comment by MickinSahni** [comment]
2020-02-12 PW Sprint Planning
- Dependent on initial gids work

**Comment by AkucherGCIO** [comment]
03/04/20 PW Grooming
This issue is being closed as it is covered in the Incorporate feedback ticket for YR.
