### ISSUE TITLE
AWS access for Ryan McNeil

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#58053]
### COR Name

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Ryan McNeil

### Your Email

ryan.mcneil@oddball.io

### Team, Role, and Company of the target individual

VA.gov Platform, Software Engineer, Oddball

### Product Manager (PM) name and email

Andrea Hewitt - andrea.hewitt@oddball.io

### Product Owner (PO) name and email

Ray Wang - gang.wang@va.gov

### Desired AWS Access

I've been told to request same permissions as Holden

### Access Expiration

Ongoing

### E-QIP Transmittal Confirmation

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/41602677/236930656-4dcb59f9-4ed2-4e6b-9708-c5ff40099b30.png">

### Additional Notes

Ongoing, as I'm on the Platform team + Support and will regularly need access to various services (Parameter store, EKS, etc) to perform my duties.

COR - Ray Wang

### User must exist in a roster before AWS access can be granted

- [ ] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [x] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by considerable** [comment]
Platform Team Roster

**Comment by BillChapmanUSDS** [comment]
Access approved,  As per usual, any production access is 3 month limited

**Comment by ryan-mcneil** [comment]
@considerable Are we waiting on anything here?

**Comment by flooose** [comment]
Access info sent in slack via direct message. Feel free to reopen this if there are problems.
