### ISSUE TITLE
DISCOVERY: Where can we add automation w vets-api?

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#58061]
### PROBLEM STATEMENT
Vets-api has been migrated to EKS. Once vets-api is stable _post migration_, we will be preparing vets-api to move to it's _maintenance phase_. In order to set vets-api maintenance up for success, TT1 will complete an automation/toil reduction project to ensure vets-api is as easily maintainable as possible.

### ACTION ITEMS
- [ ] Where can we automate components of vets-api, making it more maintainable?

### DEFINITION OF DONE
- [ ] Compiled discovery linked here, answering: Where can we automate components of vets-api?

**Comment by LindseySaari** [comment]
Automatic env vars

**Comment by LindseySaari** [comment]
We should make the test failures blocking in the k8s branch. The k8s branch has some intermittent failures currently

**Comment by laineymajor** [comment]
https://app.zenhub.com/workspaces/platform-tech-team-1-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/58521

**Comment by LindseySaari** [comment]
Automation Ideas: Syncing prod (this will be part of the next few sprints),

**Comment by LindseySaari** [comment]
Automation: Is there any room for automation when it comes to Sidekiq and ArgoCD Terminal requests?

**Comment by LindseySaari** [comment]
Create dashboards to aid in debugging
