### ISSUE TITLE
always send parent-code to systems/direct-sched-facilities

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#5806]
Currently the parent ID is marked as optional in the schema. It should be required and always sent to var resources so that the new version of the service will not break VAOS when it deploys to production.

![Screen Shot 2020-02-11 at 12.42.10 PM.png](https://images.zenhubusercontent.com/59c29173b0222d5de478791d/d81205dd-1def-4ea6-81cd-448be9f99918)

![Screen Shot 2020-02-11 at 12.42.16 PM.png](https://images.zenhubusercontent.com/59c29173b0222d5de478791d/9b73ca5c-0559-4708-a49c-077b0f96ae76)

**Comment by kreek** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-api/pull/3898
