### ISSUE TITLE
[Discovery] Cerner data deep dive

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#5808]
## Story
As a developer, I want to know how to correctly identify when a patient wants to schedule something at a Cerner site so that I can offboard them to the Cerner portal when Cerner sites start going online in March / April.

## Some Notes
- Patrick V on startup team might be working on Cerner-related things
- Work is already underway on Cerner-related messaging in other places on va.gov. Talk to Peggy / Lauren to coordinate.
- Columbus is first site to use Cerner, they use Epic currently, which kind of layers on top of VistA. What can they see in VAOS now?

## AC
- [ ] Documentation exists in GH about what Cerner data is available for any given patient:
    - [ ] Where we get the info from
    - [ ] What identifiers we need have in order to pull the data
    - [ ] What is the patient-level Cerner data we have access to? (Parent system IDs, facility IDs, etc.)
    - [ ] What will Cerner sites look like in the UI when, for example, a veteran gets to the system selection page in VAOS
- [ ] Columbus -- need to know what data exists in which systems for Columbus Veterans; Columbus uses EPIC tool (not VAOS), understand identifiers

**Comment by saneshark** [comment]
Is shared services planning on exposing an interface for us to know or will these need to be hard-coded in vets-api? I don't think we know who the source of truth is as of right now. We could certainly hard-code it if it is only a few sites.

**Comment by markgreenburg** [comment]
Note: Patrick might be doing some work on this, probably worth talking to him.

**Comment by jbalboni** [comment]
Related SSO work is here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/5405

**Comment by lalexanderson-dsva** [comment]
From a meeting i had today with Lynne Case et al:

- Veteran logs in at full Cerner site, we should get 220CRNR ID in MVI: 
  - Need: Alert on the scheduling page (Bridget and team)
  - Need: Alert on My VA page (Bridget and team)
  - Need: Alert on the landing page (VAOS)
  - Need: Alert midstream (VAOS)
  - Confirm: should not be able to see any upcoming appointments 
  - Need: Cannot cancel an appointment at a full cerner site. --> Cerner
  - Need: Cannot cancel a video appointment from a full cerner site. --> Cerner
  - Need: Cannot request a community care appt at a full cerner site 
  - Need: Cannot schedule or request a VA appt at a full cerner site 
  
- Veteran logs in at a CSS site (Columbus)  - we will get 200CRNR  ID in MVI
  - Need: Alert on the scheduling page (Bridget and team)
  - Need: Alert on My VA page (Bridget and team)
  - Need: Alert on the landing page (VAOS) --> go to Cerner 
  - Need: Alert midstream (VAOS) -->go to Cerner
  - Need: Cannot cancel an appointment at a CSS site. --> Go to Cerner
  - Need: Cannot cancel a video appointment from CSS site. --> Go to Cerner
  - Need: Cannot request a community care appt at a CSS site 
  - Need: Cannot schedule or request a VA appt at a CSS site

**Comment by jbalboni** [comment]
Created some documentation in the team repo around our data discovery for Cerner: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/engineering/Cerner_data_discovery.md

**Comment by lenaecb** [comment]
@jbalboni - do you want to keep this open?
