### ISSUE TITLE
[Wizard] Update copy for existing paths

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#58094]
## Issue Description

Work with Content team to update copy for existing paths that appear on the FSR Wizard.

Content team added comments to the linked [“Wizard - All terminus”](https://www.sketch.com/s/79aa4a84-fef1-4c06-9495-e0431a6390bd/a/YGbvgAd) screen related to decision reviews vs appeals. 

---
## Tasks
- [x] _Text updates made to Sketch_

## Acceptance Criteria
- [x] _Updates made to Sketch_

**Comment by mgleo** [comment]
@Tom-Davis @HeatherRienks @denisecoveyduc 

Question about the [Wizard paths to disagree or reconsider](https://staging.va.gov/manage-va-debt/request-debt-help-form-5655/introduction). How will users know whether they need to go through **Committee of Waivers and Compromises** or **Board of Veterans' Appeals**?

Can we update the language on these to make it more clear?

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcUswIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--937e829d8b427e2a573bc84ade08542d48000f96/Screenshot%202023-09-19%20at%2011.11.17%20AM.png)

**Comment by mgleo** [comment]
Further background:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaVMxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--533f71d46be1841c5362f3110f7f1ac90face0be/Screenshot%202023-09-19%20at%2012.04.31%20PM.png)

**Comment by mgleo** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaXExIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9abc6de149e1bd35354f6e84eb06a32e4668b303/Screenshot%202023-09-19%20at%2012.05.02%20PM.png)

**Comment by mgleo** [comment]
PDFs from email screenshot above ^ 
[part 1.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdk8xIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f7a0e2a1cfc4a704654d61f49dd1e095b785fbbc/part%201.pdf)
[part 2.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdlMxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--80e7dd7ebca67b489c1fde93d3323935fab2ecd8/part%202.pdf)

**Comment by mgleo** [comment]
Question about Copay > Monthly payment plan
The [latest content](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/48837#issuecomment-1719802316) is sending users to VA Form 1100 via [this link](https://www.va.gov/health-care/pay-copay-bill/financial-hardship). 
 
Is this still correct? Do we want to mention the compromise resolution option on the FSR? Looks like Form 1100 is much shorter so it maybe the best option but it is only available as a paper form.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdnUxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--79b4bba40217559ef0f599f3ff58efcbeccf35b5/Screenshot%202023-09-19%20at%201.45.41%20PM.png)

**Comment by mgleo** [comment]
Question about Copay > Request Debt relief 

Should it state that this is for copay debt within the past 6 months?

The Overpayment path on the [current wizard](https://staging.va.gov/manage-va-debt/request-debt-help-form-5655/introduction) asks who has the debt. Is listing spouses and dependents still applicable to overpayments? Is listing spouses and dependents applicable for copays. Can they acquire copay debt?

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ3UyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--be8095f6f1274873fd255c73b68d90fff985fb92/Screenshot%202023-09-19%20at%201.57.34%20PM.png)

**Comment by HeatherRienks** [comment]
Per Design Sync on 9/25/23, @denisecoveyduc will confirm with SME's on the questions noted above.

**Comment by mgleo** [comment]
@denisecoveyduc 
Do we know what users should do if they have reoccurring prescription debt? Can we provide that information on this Wizard?

**Comment by denisecoveyduc** [comment]
Hi Team, Some responses to the outstanding questions on this ticket.  Let me know if I missed any or if here are clarifying questions and I will be sure to turn around faster ;P 

**Question 1:** Question about the Wizard paths to disagree or reconsider. How will users know whether they need to go through Committee of Waivers and Compromises or Board of Veterans' Appeals? Can we update the language on these to make it more clear?
</br>
**Response to Question 1:** Yes I understand that Veterans may be aware of these two groups and we should clarify the messaging. Here are two descriptions that might help the team construct some language. 
_Committee on Waivers and Compromises (COWC)_ is the decision-making panel that makes decisions on a request for a waiver or compromise.  
 
_Board of Veterans’ Appeals (Board)_ 
If a Veteran is dissatisfied or disagree with a VA decision, they have the right to file an appeal with the Board of Veterans’ Appeals. The Board will review the evidence presented and issue a decision. The board reviews decisions made by COWC as well as claim decisions. 
 
I have also attached a document “Notice of Rights to Appeal” that may provide additional clarity.
[Uploading... Waiver denied Notice of right to appeal.pdf]


</br>

**Question 2:** the email from Andrew Thomas. 
**Response to Question 2:** This email is referring to the VBA wizard. I have confirmed that yes we should remove the phone number. So let’s make that change to remove the phone number from the VBA side for “Ask VA to reconsider the decision on my waiver request”.  We will not however suggest that they complete a new FSR. Veterans always have the option to complete and submit a new form. 

</br>
</br>

 **Question 3:** DMC JANDE comment “This is not managed by DMC or VHA – where does this route?”  
**Response to Question 3:** I am not sure what the question here is, maybe the info from Question 1 will help answer this one but if not let me know. 

</br>
</br>

**Question 4:** The latest content is sending users to VA Form 1100 via this link. Is this still correct? Do we want to mention the compromise resolution option on the FSR? Looks like Form 1100 is much shorter so it maybe the best option but it is only available as a paper form.
**Response to Question 4:** Current understanding is that this is the correct link. No let’s not mention the compromise resolution options on the FSR. 

</br>
</br>

**Question 5:** Question about Copay > Request Debt relief. Should it state that this is for copay debt within the past 6 months? The Overpayment path on the current wizard asks who has the debt. Is listing spouses and dependents still applicable to overpayments? Is listing spouses and dependents applicable for copays. Can they acquire copay debt?
**Responses for Question 5:** taking one at a time… see below….
-	Should it state that this is for copay debt within the past 6 months? Response:  No, there is no need to mention the timeframe
-	The Overpayment path on the current wizard asks who has the debt. Is listing spouses and dependents still applicable to overpayments?   Response: Yes, this is still applicable for overpayments
-	Is listing spouses and dependents applicable for copays. Can they acquire copay debt? Response: No, Spouses and dependents do not have medical copays for this process. 

</br>

**Question 6:** Do we know what users should do if they have reoccurring prescription debt? Can we provide that information on this Wizard?
**Response for Question 6:** I am not sure I understand this question. Many Veterans have reoccurring prescriptions and most come with a copayment. 
 
</br>

Let me know if there are follow up questions. 
FYSA: @josephrlee @mgleo

**Comment by HeatherRienks** [comment]
Per SP on10/10, this ticket is completed and @Mgleo will create a new ticket to capture additional changes.

**Comment by HeatherRienks** [comment]
Here are the new tickets created for the Wizard (thank you @mgleo )
Sprint 110:
[Wizard] VBA and VHA paths for feedback#67232

Future sprint (when we receive feedback from each team:
[Wizard] VBA Make updates based on stakeholder feedback#67234
[Wizard] VHA Make updates based on stakeholder feedback#67235

cc: @Tom-Davis
