### ISSUE TITLE
QA Test Plan - Caregiver 1010CG MVP

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#5811]
## Product/Feature Summary

The online 1010CG form is being created to make the user experience in applying for caregiver benefits easier by making a streamlined form user experience. This ticket is for the first pass of the form and get into the codebase so we can incrementally add features and build it up to a launch-able product. This form is not integrated to a backend, but does show the basic shape of the data and a non-optimized user experience.

Form should have an intro,  review, and confirmation page as long as three form sections two fo which being required. The required sections are the Veteran/Service member, and Primary Caregiver sections. Secondary One and Secondary Two are not required. 

Product/Feature Outline: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/caregiver/product-outline.md
Product/Feature Epic: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/4996
Product/Feature Pre-Launch Checklist: Doesn't exist, yet
Design tasks/wireframes/comps: [Invision screens](https://vsateams.invisionapp.com/share/G2VL3SAN8XB#/screens)
Front-end task: #4095, #4997, #4999, #5331, #5333

## SMEs

\[PM: List points-of-contact for all involved subject-matter-experts from design/development domains.  Most often, these would be the relevant development-team members (Product Manager, UX Designer, Front-End Developer, & Full-Stack or Back-End Developer]

* Product Mgr: Alayna Abel (@ala-yna) 
* UX Designer/Researcher: Jonathan Nelson (@jonathanjnelson)
* Content Writer: Patrick Sanders (@psanders86)
* Front-end Engineer: Justin Linn (@LinnJS)
* Back-end Engineer: Kevin Mircovich (@kevinmirc)
* QA Engineer: Tze-chiu Lei (@tlei123)

## Proposed Scenarios

As a non-authenticated user I should be able to fill out the form with and without secondary caregivers review, sign, submit and get a confirmation page.

Note Signature must match the exact first and last name, case sensitive.

## Test Coverage

Should be tested agents all the usual browsers and devices supported by VA.gov. 

## Staging Test-Readiness

Not currently testing for authenticated experience, just unauthenticated on first pass.

## Review

[Describe notes and comments derived from the review of QA activities with developers and product manager.]

## Definition of Done

- [ ] Test Plan reviewed by Product Team.
- [ ] Test Plan finalized per review-feedback from above.
- [ ] Test Plan approved.
- [ ] QA Test-Run ticket\* linked \[ticket-template coming soon]

**Comment by tlei123** [comment]
Starting this Test Plan ticket -- will populate pertinent details in description above over the next few days.

**Comment by tlei123** [comment]
@ala-yna , I'm starting this QA Test Plan ticket to gather QA-required info/links for @LinnJS's 1st-draft #4095, and will need you help compiling the details "placeholdered" in the main Description above...

\[@jenstrickland, if you know any of these details, please feel free to add them above too.  Thx in advance!]

My 1st question is, do we have an Epic that tracks your Build phase?  The f/e ticket's linked to a Discovery Epic (#1142), and as such it's not showing the build-phase details that I'm trying to document here.

Please let me know about any Build-phase Epic that may exist, and also start filling-out the placeholdered details in the Description.  Feel free to ping me on Slack (Tze-chiu Lei) if you have any questions/problems.

Thanks much!  :)

**Comment by jenstrickland** [comment]
@tlei123 — I'm afraid I don't have any further details. @ala-yna are you able to provide answers to Tze's questions?

**Comment by ala-yna** [comment]
Hi @tlei123! The epic should be: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/4996

I'll add some more info to the placeholders above. Thanks!

**Comment by ala-yna** [comment]
@tlei123 - All filled in! Please let me know if there's anything else I can do to help.

**Comment by tlei123** [comment]
Thanks, @ala-yna!  I'm starting test-cases development now based on the [deploy-instance](https://vetsgov-pr-11352.herokuapp.com/caregivers/introduction) created by @LinnJS's PR #11352.

If I have further questions, I'll add them in a new Comment.

**Comment by tlei123** [comment]
@LinnJS, how do I go about finding all the **specs** for all the reference/resource (e.g., "Learn more...") links?

Is there a centralized doc for them (say, from IA implementation(s))?

The [Intro page](https://vetsgov-pr-11352.herokuapp.com/caregivers/) appears to have the most reference/resource links, but I also see a couple more here & there on subsequent form-pages as well.

Please let me know.  Thanks much!

**Comment by tlei123** [comment]
@ala-yna, would you mind scheduling a 15-minute **online meeting with @LinnJS & me** please, so that I can share my first test-case on TestRail\* with you & Justin?

My Gmail Calendar is public for free/busy, but feel free to Slack me if you still can't see my availabilities.

Thanks much!

\*Check your email Inbox for TestRail shared-account credentials; I've sent them separately to you & Justin.

P.S.  If you just want a quick sneak-peak in the meantime, here's the link to my Main flow test-case: https://dsvavsp.testrail.io/index.php?/suites/view/11&group_by=cases:section_id&group_order=asc&group_id=47

**Comment by LinnJS** [comment]
Added all frontend tickets reflected in this PR in the FETask section of the ticket at the top. Designs are changing a pretty good amount, as far as I am aware all elements that are staying are present. There is no centralized doc that I know of @tlei123. I am concerned about work you might have to do over again with the automated testing with the design changes. Is this something that should be happening before pre-launch? Or is it easier to have test in place incrementally?

**Comment by jonathanjnelson** [comment]
It seems like the designs are in a good spot to merge. There is another version of the form that we will be tackling this next sprint. The design changes quite a bit.

**Comment by tlei123** [comment]
@jonathanjnelson , does InVision have version history for each screen?

I'm wondering if it's possible to have version-specific deeplinks to the screens as of the time @LinnJS's PR is opened.  That way, you can keep updating your designs without causing QA-testing confusion -- the PR takes a couple days to get approved, and once merged takes 2-3 days to QA.

Please let me know.  Thanks much!

**Comment by tlei123** [comment]
@ala-yna @LinnJS, please review my [10-10CG VMP Test Plan](https://dsvavsp.testrail.io/index.php?/plans/view/175)\*, and add a Comment with your approval/feedback...

Here's a quick review rundown:

1. **Test Plan**: The link above will take you to the Test Plan overview page.  Review the Plan's description -- summary info and reference-links to the key pertinent GitHub tickets/docs for your product/feature -- to ensure the details are accurate.
1. **Test Run**: Scroll down to the bottom of the overview page, then click **10-10CG MVP - Test Run** link.  You'll be taken to the Test Run page, where its three included Test Cases are listed.  Validate here whether the Test Cases list covers all the User-scenarios/flows for your product/feature.  NOTE: This Run will be "exploded" into separate browser-/device-specific runs (e.g., Win Edge, Mac Safari, iPhone 11, Galaxy S9, etc.), once reviewed & approved.
1. **Test Cases**: From the Test Cases list, click each Case-link to see the Case's Steps and Expected Results.  Review the Steps and Expected Results to ensure they're correct.  Repeat for each Test Case, clicking your browser's Back button to return to the Test Run overview page for the next Case.

Feel free to tag me on your DSVA-Slack #vsa-caregiver team-channel if you have any questions/problems.

\* Check your email Inbox for the TestRail VSA shared-account credentials I sent to you last week.

**Comment by starofaragon2010** [comment]
HI Team, 
@ala-yna 
As a reminder, the form can be filled out by 1 vet, 1 primary caregiver, and 1 secondary caregiver at the same time. It will not always be 1 vet and 1 caregiver either primary or secondary

**Comment by tlei123** [comment]
@ala-yna, per my separate email to VSA Product Mgrs., please request your team-specific TestRail account from @pjhill, and pass on  to whoever's assigned TestRail tasks (e.g., @LinnJS right now for final Test Plan review/approval).

Thanks much!

**Comment by LinnJS** [comment]
Looks great walked through the entire form made updates to the first test case as needed, should be good to go, thank you so much for setting this up for us!

**Comment by tlei123** [comment]
@ala-yna, all test-runs are now completed, and QA artifiacts are ready for @pjhill's review/feedback.

Defects logged: #9666, #9667, #9742, #9745

**TestRail links**:
- [Test Plan](https://dsvavsp.testrail.io/index.php?/plans/view/175)
- [Coverage for References report](https://dsvavsp.testrail.io/index.php?/reports/view/94)
- [Summary (Defects) report](https://dsvavsp.testrail.io/index.php?/reports/view/93)
