### ISSUE TITLE
Change the header 2 on the Upcoming list/Homepage 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#58110]
## Description
We will need to update the header two on the Upcoming list page/Appointments homepage. It will display `Appointments` instead of `Your appointments `

---

## Acceptance Criteria

- [ ] When the user enters the Appointment List page (upcoming) 
        Then the user will see the updated header and breadcrumb `Appointments` 
         And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/homepage.md#homepage-refresh-toggle)
         And page design matches the [specs](https://www.figma.com/file/WSyST4k1Q3eKxMmbhYMHNG/Header-changes-on-appt-list?type=design&node-id=11%3A49&t=EiFXVIayii3SkvBP-1)
         

### Design Assets
[Design spec](https://www.figma.com/file/WSyST4k1Q3eKxMmbhYMHNG/Header-changes-on-appt-list?type=design&node-id=11%3A49&t=EiFXVIayii3SkvBP-1)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by Cieramaddox** [comment]
@ldelacosta [Here](https://www.figma.com/file/WSyST4k1Q3eKxMmbhYMHNG/Header-changes-on-appt-list?type=design&node-id=11%3A49&t=EiFXVIayii3SkvBP-1) are the design specs with the updated header.

**Comment by ldelacosta** [comment]
Validated the changes in staging. No issues to report. Closing out the ticket. 
![Screenshot 2023-05-15 at 1.34.01 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/98d98639-17fa-4dea-a777-8f5c9930074f)
