### ISSUE TITLE
**BUG** - STS errors on dev.va.gov

### ISSUE THREAD

**Issue by kingbmike** [department-of-veterans-affairs/va.gov-team#58113]
#### What I expected to happen

1. Should be able to sign in w/o error
1. 
1. 

#### What actually happened

1. unable to log into dev.va.gov (staging works) - we tried both id.me and login.gov - this is with oauth=true & without
we. get the below image and at the bottom of the page we have the following error code
1. Error code: 007
Request ID: No corresponding Request ID was found
1. ![image.png](https://images.zenhubusercontent.com/63cee7d980153fa49846104e/a850b7bf-36d6-47e0-a0ef-9e14d9372059)

#### What _SHOULD_ happen

1. 
1. 
1. 

#### Severity of the issue
- [ ] High severity
- [x] Medium severity
- [ ] Low severity

#### Visibility
- [x] User visible
- [x] Stakeholder visible

#### MR Approver
- TBD

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by bosawt** [comment]
This occurs in at least two places:
- In Progress Forms Controller: http://sentry.vfs.va.gov/organizations/vsp/issues/201120/?environment=development&project=3&query=is%3Aunresolved&statsPeriod=14d
- Sign in Controller: http://sentry.vfs.va.gov/organizations/vsp/issues/183062/?environment=development&project=3&query=is%3Aunresolved&statsPeriod=14d
- Sessions Controller (this is a single example, it's harder to correlate since it reports events in sentry as Sign in Controller): https://vagov.ddog-gov.com/logs?query=env%3Aeks-dev%20%22sts%3AAssumeRoleWithWebIdentity%22%20%40named_tags.request_id%3Ac40e7a04-af69-49b6-a2d7-76a9ba5675c8&cols=host%2Cservice&index=%2A&messageDisplay=inline&stream_sort=desc&viz=stream&from_ts=1683568365530&to_ts=1683654765530&live=true

**Comment by rileyanderson** [comment]
It appears that there may be some clashing with the preview environment and dev. 
[Datadog logs](https://vagov.ddog-gov.com/logs?query=%40message_content%3A%22Not%20authorized%20to%20perform%20sts%3AAssumeRoleWithWebIdentity%22%20&cols=host%2Cservice%2Cdirname&index=%2A&messageDisplay=inline&stream_sort=desc&viz=stream&from_ts=1682488800000&to_ts=1683698340000&live=false)
<img width="903" alt="Screen Shot 2023-05-10 at 9 09 19 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/10853209/4d50a252-c9e0-431c-8287-7bc26fa47ea2">


April 27th - May 3rd: the errors were coming from `DIRNAME: /var/log/pods/test_vets-api-web-xx/vets-api-web`

May 3rd-May 5th: there was a period of no errors

Starting EOD May 5th - Now: Errors started again but coming from `DIRNAME: /var/log/pods/preview-environment_vets-api-web-xx/vets-api-web`

The errors restarting May 5th coincide with the release of this [preview-environment Code](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/commit/350dd5e0ad1c36d2a595cf7e7e9e329da4d95f0e) 

The [Sentry Errors](http://sentry.vfs.va.gov/organizations/vsp/issues/183062/events/2b5f4ddbcf6e40848c7b7063ef5221c5/?environment=development&project=3&statsPeriod=14d) last 30 days line up with the Datadog errors
<img width="319" alt="Screen Shot 2023-05-10 at 9 12 33 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/10853209/8ca884f3-e728-46bd-b46f-d40e1aa628a4">

**Comment by joeniquette** [comment]
@laineymajor @LindseySaari Would you mind taking a look at the notes in this ticket. This is impacting dev development of authenticated features. It seems related to the preview environment work, but unsure. If you feel this isn't something related to work on your team please let me know. This isn't prod so not a high priority issue, but this is something that impacts development and has been occurring for a while. Any help would be appreciated.

**Comment by joeniquette** [comment]
@JoeTice @pjhill Since this appears to maybe be related to preview environments do you mind taking a look?
