### ISSUE TITLE
Configure front-end to use custom vets-api endpoint

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#58129]
# Description
Now that our preview environment manifest is successfully starting up the EKS migration `vets-api` pod and a front-end pod side by side, we need to configure the front end to make `vets-api` requests to the `vets-api` pod resource. The frontend container is capable of communicating with the backend container --

![image.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/bd05243e-97ea-4587-9942-47ee45cad1e7)

But, the initial attempt at configuring the frontend to point to the custom endpoint does not appear to be working --
![image.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/86347017-8dfc-40e4-a9ff-6422459622ba)

Project characteristics that will affect the solution:
1. We want to keep the FE image as small as possible, so we are doing a bunch of local filesystem stuff in the startup script. In the near future we hope to have most of the storage solution in a persistent volume.
2. Communication across pods can not use localhost
3. 

# Acceptance Criteria

- [ ]

**Comment by pjhill** [comment]
The fix for this issue is being worked in this ticket instead -- https://app.zenhub.com/workspaces/platform-tech-team-4-633b069d2920b776613c93d8/issues/gh/department-of-veterans-affairs/va.gov-team/59194
