### ISSUE TITLE
Salesforce 09880558 Case Type Inability to Access Tool Category Claim/Appeal Status

### ISSUE THREAD

**Issue by Kimberley2019** [department-of-veterans-affairs/va.gov-team#58120]
Veteran has a ticket in for a mobile app. Now she is unable to see anything, she said this has been on going for about three months now. She uses ID.me to login, she is unable to access any of her tools. Since she put in her last ticket she is unable to see anything.

Veteran was told this would be resolved in 5-10 business days, this issue has been going on for three months. Veteran is only able to see her name it tells her she has no claims or appeals in progress, it will not show her her payment history. Veteran has not received any correspondence about this at all.

**Comment by Kimberley2019** [comment]
Additional information has been collected and provided to Joe N. on the Identity team for review.
This ticket has been opened for tracking purposes.
Additional labeling will be added as the ticket progresses.

**Comment by ATMiddleton** [comment]
Awaiting input from Identity Team

**Comment by Kimberley2019** [comment]
From: Joe Niquette Office365@messaging.microsoft.com
Sent: Tuesday, May 9, 2023 4:33 PM
To: Daniels, Kimberley N. Kimberley.Daniels@va.gov; Niquette, Joseph P. (Oddball, Inc.) Joseph.Niquette@va.gov
Cc: Joe Niquette joe.niquette@oddball.io
Subject: [EXTERNAL] Re: Case 09880558 T3

 

Im looking into this now with the team. I do see some errors with their data not being correctly linked up. Trying to determine why.

 

From: Daniels, Kimberley N. Kimberley.Daniels@va.gov
Sent: Tuesday, May 9, 2023 3:48:09 PM
To: 'Joe Niquette' joe.niquette@oddball.io; Niquette, Joseph P. (Oddball, Inc.) Joseph.Niquette@va.gov
Subject: RE: Case 09880558 T3

 

Hey Joe,

 

She responded with some screenshots, see attached.  Let me know if that helps at all.

 

 

Thanks,

 

Kim

 

From: Daniels, Kimberley N.
Sent: Tuesday, May 9, 2023 2:36 PM
To: Joe Niquette joe.niquette@oddball.io; Niquette, Joseph P. (Oddball, Inc.) Joseph.Niquette@va.gov
Subject: Case 09880558 T3

 

Hey Joe,

 

Can you take a look at the attached email?  It contains a case where the user is having an issue with their data being linked to their profile.  Here is the link for the ZH ticket for tracking purposes, I have NOT added you to this ticket. 

 

EVSS has already taken a look and has notes in the case (below). Is there anything that you can see on the backend that may be giving her this issue?  Also, I have already asked her to provide a screenshot and/or the entire URL where she is encountering this issue.

 

 

No mismatches, no duplicates found, records are clean.
POS and Rating info are also properly set.

ICN: 1023619009V028676

 

 

Kind Regards,

 

Kim

**Comment by Kimberley2019** [comment]
mismatch found between id.me info and DEERS info.  Damien from IAM will have member review and fix this morning.
User has been notified.  SF ticket has been updated.  Will not close either ticket until fix is complete and tested.

**Comment by Kimberley2019** [comment]
Issue was resolved on 5/10/23.  Caller responded on 5/11/23, providing confirmation that she is able to access all of her data.
Sf ticket has been updated with all appropriate details and closed out.
