### ISSUE TITLE
[Discovery] Determine business logic for claims waiver.

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#58139]
# Background

We need to understand the business logic for what the 5103 claim waiver does and doesn't do and when, so that we can solution an experience that helps veterans know when to fill out the waiver. 

# Acceptance Criteria

- [ ] We know what cases it benefits a veteran to fill out the waiver. 
- [ ] We know what cases it would not benefit the veteran to fill out the waiver.
- [ ] We understand the relationship between the waiver and VBMS triggers like "suspense date".

**Comment by rubensun** [comment]
Veterans authorize the VA to make requests on their behalf to gather evidence supporting their claims as a part of the 526. During the claim development process, the VA may reach out to gather additional evidence from federal or private agencies that were not included in the initial benefits application. 

In these situations, a 5103 will be provided notifying the veteran that the VA is reaching out to perform their duty to assist. No additional authorization is required on behalf of the veteran. The notice is sent to inform them of the VBA's actions. This notice also serves to give the veteran the opportunity to provide this documentation in the case they have relevant records.

With private agencies, such as hospitals, the VA will follow up twice to chase down these additional pieces of evidence. Impact on the suspense date follows the same rules as other pieces of evidence gathered (15 days for medical records or ACE exams, and 30 days for physical or virtual exams).
