### ISSUE TITLE
Amend "View Dependents" Mockup to Address a Split List Notification 

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#5813]
## Goal
Create mockup that shows the View Dependents screen when a call comes back with data for one list (on-award/not on-award), but not the other.

## Tasks
- Update the mockups to show data for on-award, but no data for not on-award
- Update the mockups to show data for not on-award, but no data for on-award
- Share mockups with frontend engineers

## Acceptance Criteria
 - [ ] XD mockups showing two data states for View Dependents

**Comment by sporeboy** [comment]
Mockups created: 

No "not-on-award" https://xd.adobe.com/view/8cdfe895-c907-4662-7234-305056778b2a-faee/screen/ac668bed-4f9a-4bac-a9f4-16bd7e5bcdc7/View-Dependents-Split-Data-1

No "on-award" https://xd.adobe.com/view/8cdfe895-c907-4662-7234-305056778b2a-faee/screen/a09021f8-e1d4-4b62-84c6-b685c05ddd61/View-Dependents-Split-Data-2
