### ISSUE TITLE
Request For Tech Support/EVSS Testers VA CX SRP June Release User Acceptance Testing Session 5/9-5/11

### ISSUE THREAD

**Issue by edpearson20** [department-of-veterans-affairs/va.gov-team#58144]
I'll be testing with Robert Kuehn and the Salesforce Development Team.

**Comment by edpearson20** [comment]
Performing testing spread out over the course of two days (Wednesday and Thursday).  Quite lengthy with several tabs of test scripts and several hundred steps.

**Comment by edpearson20** [comment]
Forwarded test script to Chante and Anita.

**Comment by edpearson20** [comment]
Not complete as of yet.

**Comment by Kimberley2019** [comment]
Okay to close per @edpearson20.  Any additional notes will be added before sprint end.
