### ISSUE TITLE
SOCKS access for Mark Chae

### ISSUE THREAD

**Issue by mchae-nava** [department-of-veterans-affairs/va.gov-team#58151]
### Your Name

Mark Chae

### Your Email

markchae@navapbc.com

### Your Role and Team

Software Engineer on Benefits Disability Experience

### Product Manager (PM) name and email

Rakshinda Aslam rakshinda.aslam@agile6.com

### Product Owner (PO) name and email

Matthew Self matthew.self2@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDFPKx50HdNRmf/0RvCq/HMj4+e5b3as1SHwBikHT9PgueheMChaNHAcIpS69CNebVv5bECXaJxreyAE9pdoGn86g7Kfi7C/hrcdWzHVPIExZhwtRnvmnHfthYfc3xNFCMYLKXIad0REfX2Zz5joTwX9AiR4zU1DMJzu+H/doZRrWktzexFK7nvlBQdJLbMs1iYhzXtftmW++Fsj2dktWyUnU5OELCGSCjmAZzX5urmGu7IhKEoJ4dtk/DIMY27TsW/YO6S7D5nn+nNt1thbBFuTvjhzCIps7q7WHekR+cgpc6HpeOXmEUenANMOLksmsLmg1AWs7HrMAmLWsPTctfhvl9lyCchHWwMr9I1jqfXjeZ70/iOiehMnfvU6B+VM4qJTrbYXTD+NLcg7NoUoavvd6ystGkYgorT+f9K0DhBPNBbpMGKLdRsFmv3tAntLEOPwTQ6WSiXiVtK7L+bZskte33hMfueFjJT/R/YR6tnPhT7HEVCt1W55/uAFryOky0= markchae@Marks-MacBook-Pro.local

### E-QIP Transmittal Confirmation

[](url)
<img width="1108" alt="eQIP Transmittal notice" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/129200156/28be12d1-592c-4a66-ae40-9a4d90eeeb44">

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by flooose** [comment]
@mchae-nava your socks access should be available within an hour. Feel free to reopen this if you have problems.
