### ISSUE TITLE
Research: Support Bot Workflows

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#58156]
<b>Description:</b>

The goal of this ticket is to identify current opportunities for clear communication and efficiency within the Support Bot process. 

<b>Definition of Done:</b>

- All tasks below are complete

<b>Tasks</b>

- [x] <i>Support Bot Form:</i> Identify existing categories in our support bot form and identify gaps where additional categories could exist 
- [x] <i>Ticket Creation/Adding a Ticket Link in Form:</i> Brainstorm ways we can streamline ticket creation (right now two tickets are being created at once, one on PS board and typically the ticket that the user has already created). This will make more sense as to why we are doing this later. 
- [ ] Also exploring adding fields to the initial support bot field to ensure we get the info we need (in addition to template overhauls already happening like PR template).
- [x] <i>Other Category Update:</i> Break out potential categories from the "Other" category
- [x] 
<b>Resources:</b>

- <i>Dashboard:</i>  https://lookerstudio.google.com/u/0/reporting/9d61ff32-82f9-46a4-8c58-dfa3ee38bff5/page/F3VEC
- <i>Slack Channel Responses:</i> https://docs.google.com/spreadsheets/d/1TItdfPMH_TiXEhgMKEqxIW2e5EaMKy4cHaBhaeQ7drU/edit#gid=0
- <i>Slack Channel:</i>  https://dsva.slack.com/archives/CBU0KDSB1
- <i> Platform Support Bot Overview: https://vfs.atlassian.net/wiki/spaces/SRE/pages/1883406342/Platform+Support+Bot
- <i>Platform Support Bot Configuration:</i>https://vfs.atlassian.net/wiki/spaces/SRE/pages/1883340805/Platform+Support+Slack+Bot+Configuration#Google-Sheet-Setup
- <i>Screenshots of Slack Bot Fields Currently:</i>  

[Screenshot 2023-05-09 at 1.43.54 PM.png](https://images.zenhubusercontent.com/634f039195964c85374018cc/cf8a30cd-239a-470f-93bc-33a385b5ec16)![Screenshot 2023-05-09 at 1.44.01 PM.png](https://images.zenhubusercontent.com/634f039195964c85374018cc/920408f3-b34c-4354-9ecb-6c1e9629e977)![Screenshot 2023-05-09 at 1.45.24 PM.png](https://images.zenhubusercontent.com/634f039195964c85374018cc/99d93cd7-074b-4267-a227-3e1dd8e5ced0)![Screenshot 2023-05-09 at 1.46.01 PM.png](https://images.zenhubusercontent.com/634f039195964c85374018cc/4129a1db-085c-47e9-856d-e859f21af193).

**Comment by jknipes** [comment]
1)
**### Existing categories**

**Assigned To**:

- Analytics & Insights
- Back End Support
- Design Systems/Forms Library
- Dev Ops Support
- Front End Support
- Governance Team
- Other
- Platform Content

ADD: 5 Remaining Teams (or break down OTHER to include)
- Collab Cycle
- QA Standards
- Platform Security
- Forms Library
- Console UI

2)
Assigned To: OTHER
Break down further to include these Teams:
- Collab Cycle
- QA Standards
- Platform Security
- Forms Library
- Console UI

Remove topics from Other: 
Google Analytics/Domo = Platform Analytics Team
Security = Platform Security

3)
**Currently Available Topics**
Access Request
Accessibility (_currently disabled_)
API (_currently disabled_)
App Logging/Monitoring
App Setup
Automated Tests
CI Error
Collab Cycle
Console UI
Content & IA (_currently disabled_)
Datadog
Design (_currently disabled_)
Design System
Design System
Environments
Failed Deployment
Forms
Google Analytics/Domo
Off-Cycle Deployment
Orientation/Onboarding
Pipeline
Platform website content
Platform website deployment/publishing (for Platform teams only)
PR Review
QA (_currently disabled_)
Review Instance
Security
SOCKS
Something Else
Test Accounts / Data
Test Failure
Testing Support Form (_currently disabled_)
Testing Tool Access
Testing Tools (_currently disabled_)
va.gov - Incident

May be important to ADD: 
Cert expiration for fwdproxy (to renew via Venafi)
Cert expiration for revproxy (to renew via SSLmate)
Cert expiration for SSOe (to let @Joe Niquette's team manage it)
Access requests for
 - AWS
 - DataDog
 - Sentry (to be decommissioned?)
 - Loki (to be decommissioned?)
 - Sidekiq UI
 - SOCKS
 - TestRail
 - ArgoCD Terminal
 - GitHub team membership
Questions about documentation
Questions about log/monitoring
- Suggested needs also include: Onboarding, Offboarding, navigating any self-help system, and analyzing performance issues.

4)
Additional question: Can Assignment be configured to auto-populate to the correct team according to the Topic?

**Comment by jknipes** [comment]
**Ticket Creation/Adding a Ticket Link in Form**
Potential fields for Slackbot:
- Knowing what team came from/adding label/slack notification (tag of some sort?)
- What have you tried?
- Have you tried VFS Slack search under support?
- What is the ask here?

**Comment by jknipes** [comment]
**What we do now**

**What we need for the future**
**What it would take to make these changes**
**What is better**
Zendesk
