### ISSUE TITLE
Incorporate Spike EKS Migration `vets-api` Backend into PE Architecture

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#58167]
# Description
Now that we have a spike in place to successfully deploy the EKS migration version of `vets-api` into our PE apps, we need to incorporate the tailored manifests into our PE deployment process.

How might we keep our tailored manifests in sync with changes to the EKS migration `vets-api` solution?

# Acceptance Criteria
~~- [ ] Preview environment workflows result in the creation of PE apps that contain a backend using the `vets-api` EKS migration solution~~
- [x] Changes to the `vets-api` production EKS configuration are continuously synchronized with our PE configuration

**Comment by pjhill** [comment]
This bug from the Identity team appears to be related to this spike -- https://app.zenhub.com/workspaces/identity-5f5bab705a94c9001ba33734/issues/gh/department-of-veterans-affairs/va.gov-team/58113

**Comment by cyriltech** [comment]
We are using dependency in chart.yaml which fetches the helm package for vets-api and that includes the template manifest for k8s but not the values itself.
Values itself is injecting directly from repository itself, in our case it is coming from the values.yaml presented in pe-envs, They have their own Values.yaml file completely isolated from here, so whatever changes are made to their values.yaml or PE-ENV values.yaml, they only applies to the respective release of helm and don't affect the other release.

**Comment by cyriltech** [comment]
If any dev wants to update something for the vets-api values, then he/she can make changes to the values.yaml file directly and raise PR. For example If someone had to update the image version then he can do that by changing the tag as shown below in the image.
![image.png](https://images.zenhubusercontent.com/6385292bddbc0cbb14b84a51/ea99dfa0-2265-42aa-982e-967fed55342c)

**Comment by cyriltech** [comment]
Also to this question

> How might we keep our tailored manifests in sync with changes to the EKS migration vets-api solution?
`IMO It is not ideal to sync values.yaml from other repository because going forward developers will be making changes to vets-api for their own release, lets say changing the image tag or could be any other value, so this thing will be conflicting with the vets-api-dev values.yaml `
