### ISSUE TITLE
Create Verification Companion App Draft

### ISSUE THREAD

**Issue by mjconw3** [department-of-veterans-affairs/va.gov-team#58181]
## Description
As the identity team, we want to provide users with a step by step guide that helps walk them through the account verification process. The deliverable for this ticket will be a draft of that document that we can then get approved by the accessibility team for use on VA. gov

## Acceptance Criteria

- [x] Go to VA.gov and Select Create Login.gov account
- [x] Document and screen shot every step of the verification process as you go through it
- [x] Compile notes and screen shots into a draft document

## Product Notes
[VA.gov login](https://www.va.gov/?next=loginModal)

[Example Document for Reference](https://app.zenhub.com/files/133843125/00d930c5-86a4-4421-80c1-a41e532ffba4/download)

**Comment by charlye-bluetiger** [comment]
@aparsley and I have started on [this document](https://docs.google.com/presentation/d/1p5AFJrXqxjuTqy5DIdn8w8qLGSFjAPm0/edit#slide=id.g2429c3c9235_0_89).

**Comment by aparsley** [comment]
Reached out to Danielle Thierry on May 26th with the following questions: My team wanted to ask the following questions:
What do MHV coordinators actually want?
What can we actually hand out to Veterans when considering bulk?
Are there any previous document samples that we can take a look at?

**Comment by aparsley** [comment]
https://docs.google.com/presentation/d/1p5AFJrXqxjuTqy5DIdn8w8qLGSFjAPm0/edit#slide=id.g24eda3b8084_0_17
