### ISSUE TITLE
Update link to Spanish 10-10ez form on 3 pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#58194]
## Issue Description

SiteImprove identified 3 pages where we have broken links to the Spanish 10-10EZ PDF form. We need to update the link to the following: https://www.va.gov/vaforms/medical/pdf/VA_Form_10-10EZ_Spanish.pdf

Pages to fix:
- [Eligibility for VA health care](https://www.va.gov/health-care/eligibility/)
- [How to apply for VA health care](https://www.va.gov/health-care/how-to-apply/)
- [Spanish vaccines page](https://www.va.gov/health-care/covid-19-vaccine-esp/)

## Tasks
- [x] Fix links on 3 pages
- [x] Copyedit (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] Links no longer broken on live site

**Comment by RLHecht** [comment]
@megzehn I just fixed these links. These are ready for you to review and publish. Thanks!

**Comment by megzehn** [comment]
Thank you, Randi!! I reviewed and published these 3 pages.

**Comment by RLHecht** [comment]
These changes are all live. Closing ticket.
