### ISSUE TITLE
SSL cert renewals for September

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#582]
## Description

We have some certs that have come up in the 60 day warning period that need to be replaced and provided to Gateway Ops. Certs covering:

dev-api.va.gov
dev-developer.va.gov
dev.va.gov
staging-api.va.gov
staging-developer.va.gov
staging.api.va.gov

## AC

- [x] new certs are being used for internal listeners
- [x] new certs are provided to and being used by TIC
- [ ] old certs are deleted from AWS cert manager and SSL check job comes back clean

**Comment by wyattwalter** [comment]
Hey @tskinn, I know you can't access VA-internal stuff right now, but can you get these certs staged?

**Comment by tskinn** [comment]
`staging.api.va.gov` doesn't appear in sslmate.
```
sslmate list
Name                      Type  Status   Expiration  Local Status
-----------------------------------------------------------------
dev-preview.va.gov        DV    Pending  -           None
preview.va.gov            DV    -        -           None
*.vets.gov                DV    Active   2019-11-12  None
www.va.gov                DV    Active   2020-01-18  None
design.va.gov             DV    Active   2020-04-05  None
dev-design.va.gov         DV    Active   2020-04-05  None
staging-design.va.gov     DV    Active   2020-04-05  None
api.va.gov                DV    Active   2020-07-11  None
developer.va.gov          DV    Active   2020-08-08  None
dev-api.va.gov            DV    Active   2020-08-31  No key file
dev-developer.va.gov      DV    Active   2020-08-31  No key file
dev.va.gov                DV    Active   2020-08-31  No key file
staging-api.va.gov        DV    Active   2020-08-31  No key file
staging-developer.va.gov  DV    Active   2020-08-31  No key file
staging.va.gov            DV    Active   2020-08-31  None
```

**Comment by boris-ning-usds** [comment]
search.vets.gov's certificate will expire in 8 days as well.
The discussion thread is here: https://dsva.slack.com/archives/C7S6EA0ES/p1564552123061400

I'm not sure who to reach out to, as it is one of our integrations, isn't it?

**Comment by b00klegger** [comment]
Certs applied in dev / staging and appear to be functional via `openssl s_client` test from jumpbox(s).

**Comment by b00klegger** [comment]
Started process to get certificates to GatewayOps

**Comment by b00klegger** [comment]
Opened ticket for access to ChangeGear problem. Cannot open ESCCB request.

**Comment by b00klegger** [comment]
Certs were installed and appear to be functioning properly. Will remove files from repo tomorrow with final PR.

**Comment by ricetj** [comment]
done
