### ISSUE TITLE
Front End Responsibilities Documentation 

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#58206]
<b>Description:</b>

The goal of this ticket is to document <i>current</i> Platform Support responsibilities.

<b>Definition of Done:</b>

- Documentation draft has been created and sent to Alyssa Gallion

<b>Resources or Examples</b>

-  <i>PM Responsibilities:</i> https://vfs.atlassian.net/wiki/spaces/PTST/pages/2426110021/Platform+Tech+Support+Team+PM+Responsibilities
- <i>DevOps Responsibilities:</i></i>https://vfs.atlassian.net/wiki/spaces/PTST/pages/2425552908/DevOps+Support+Responsibilities#AWS-IAM-Expiration
-  <i>BackEnd Support Responsibilities:</i> https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities

<b>Create Documentation Here:</b>

https://vfs.atlassian.net/wiki/spaces/PTST/pages/2630975664/FrontEnd+Support+Responsibilities

**Comment by rsmithadhoc** [comment]
Updated this page https://vfs.atlassian.net/wiki/spaces/PTST/pages/2630975664/FrontEnd+Support+Responsibilities. I think that's enough to call this done but I will keep adding to it as I come across more.
