### ISSUE TITLE
Staging Tool Error

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#58218]
## Error
~~For the BTSSS test users in our staging tool, it appears that changing the phone number can cause the error below.~~

~~This is preventing the testing of the travel feature from moving forward.~~

Errors in the stage tool aren't handled well if there is no `data` object. Update to check for data and if not found send full error text.

![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/9d2090e2-b4dc-4e4c-bafd-a251fe0662a1)

**Comment by loripusey** [comment]
@randomsync @brianseek can you point this before planning today?

**Comment by brianseek** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/58218?planning-poker) with Zenhub @lee-delarm6 @wullaski

**Comment by brianseek** [comment]
Changes are deployed to tool. Moving to closed
