### ISSUE TITLE
SOCKS access for Melissa Miller (Updating key)

### ISSUE THREAD

**Issue by holytoastr** [department-of-veterans-affairs/va.gov-team#58213]
### Your Name

Melissa Miller

### Your Email

mmiller@pluribusdigital.com

### Your Role and Team

Full Stack Engineer on Identity Team

### Product Manager (PM) name and email

Elizabeth Koch, elizabeth@bluetiger.digital

### Product Owner (PO) name and email

John Rahaghi, john.rahaghi@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDK2jH863k24HhY/O+x0cpr7FI2r7dupU2ST69rccuUE+UMtbD6KXWBb+y4qYIzoBl3CFRduivej0DiiwDfdoS+CHnBss3QfY//fjwi1SYaNZxaxUs9kTRbVjLm6TCElpS2izOAAM7V9ZeUbX7+fzAzvTFoSsEYhocdXzeVW7Xx1ilZo0kQfYsafBY9ScvCHIAxfqKXhe8wSQr80/TFOVX1yacuWQtqC0Xqp2VC1+eRbtDUKUQgOK2/khmb5iOmT9Mocz10puxHnBJY2xpP00s72BP/KYtDlf17TaXpPWhZGXHoTrZfK/AQ/hmHWuiB1w1F5WEhTLYQjUhbW1JNxztzu7KSnLYxPQDGZ5zUXdJmKE2EaKo79lHEIdM3b81zwG2scU0m8v53DPuBc6OXRrKx888ZppXwLeHyE2Dtzao41/Csas21hW23n9GByZBP6ADKHJ/NCYjISwEfV03JMJMogVq/ABxbh+/EcwrmKv1c3tUCJ+lwG3/p1+M5pwiX8Ks= melissamiller@Melissas-MBP

### E-QIP Transmittal Confirmation

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/4822313/162b6f50-e49a-4582-9ffb-93441b0dbfb2)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by flooose** [comment]
Closing this. @holytoastr if you have any other issues, let us know.
