### ISSUE TITLE
[FE] Notification Component: Document experimental design + component build/design system process

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#58222]
## Background
The team recently completed the process of building a component and having it added to the design system library. This is the first time we've gone through this process (at least with these team members) and the process was a but confusing. We should document the process for future use if we or other future team members need to understand how this process works, beginning with the experimental design process through review, approval and deployment into design system library. This ticket is the for the FE portion of this effort. The partner Research and Design ticket is #60328  

We should be sure to include links to example tickets and templates as well as any supporting documentation from platform.

## Tasks
- [x] Create a write up in GH documenting the process. Shell/draft [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/onsite-notifications/update-design-system-component/documentation/experimental-design-and-component-build.md).

## Acceptance Criteria
- [x] Document explaining this process exists in GH

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Any team member
- _How can this work be validated?_ Review document in GH

**Comment by allisonlu** [comment]
Added my insight under the [Engineering section](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/onsite-notifications/update-design-system-component/documentation/experimental-design-and-component-build.md#engineering)!

Let me know if this all makes sense; happy to make any changes

**Comment by ajakabcin** [comment]
Hey @allisonlu this is great thank you so much! I think the only thing I would consider adding is maybe a small section (a sentence or two) to say, knowing what you know now about the process, what would you (or any other dev looking to this for reference) do differently next time? My understanding is that maybe we would build in the design system space vs our own directory from the jump, because it seems like they had you re-work things once we moved things over. Maybe I'm misunderstanding though! Overall this is great and I think will be a helpful resource. Thank you!
