### ISSUE TITLE
[Spike] - Understand the differences in clinic/facility calls in VAOS Service vs MFSv2

### ISSUE THREAD

**Issue by cferris32** [department-of-veterans-affairs/va.gov-team#58234]
Currently for retrieving clinic and facility data, we use a combination of calls to VAOS service and MFS. Due to difficulties with maintaining testability for MFS calls in staging, we'd like to look into transitioning more of our calls over to VAOS service. To do this, we want to understand any differences in the contracts between VAOS service and MFS. This spike would be to identify those gaps and note if there would be any blockers on making the transition.

AC:
[ ] - identify what contract gaps there are, if any, between VAOS service and MFS for retrieving clinic and facility data.

Timebox: __ hours

**Comment by ldelacosta** [comment]
No longer need this ticket.
