### ISSUE TITLE
Facility locator pagination issue for edge cases

### ISSUE THREAD

**Issue by jholton** [department-of-veterans-affairs/va.gov-team#5823]
## What happened?
The `BaseFacility.per_page` value is 20
Criteria for bug to occur:
* `cc_provider` search
* the number of number of results is evenly divisible by 20
* the user is on what should be the last page

Then, a pagination link to the "next" page is erroneously shown.

[Here](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/controllers/v0/facilities/va_controller.rb#L55) is where the problem lies.

`total_pages: total / BaseFacility.per_page + 1`
If `total` is 19: 19/20+1 = 1.  Correct.
if `total` is 21: 21/20+1 = 2.  Correct.
if `total` is 20: 20/20+1 = 2.  Incorrect.

## Steps to Reproduce
Found while investigating [this Sentry entry](http://sentry.vfs.va.gov/vets-gov/platform-api-production/issues/99628/events/latest/).
[Here is a live link](https://www.va.gov/find-locations/?zoomLevel=9&page=1&address=04901&facilityType=cc_provider&serviceType=204D00000X&location=44.57090430226874%2C-69.63958740234376&context=Waterville%2C%20Maine%2004901%2C%20United%20States) that demonstrates the problem.
The page loads with 20 search results.  However there is a link for the next page.  Clicking it generates a 500 error.

## Desired behavior
Pagination links should not be present when on last page.

## Acceptance Criteria
- [ ] Fix the `total_pages` calculation to work when `total` is evenly divisible by `BaseFacility.per_page`

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by patrickvinograd** [comment]
`Math.ceil` should get you where you need to go.

**Comment by jholton** [comment]
Do you mean `Float#ceil`?  I don't see a `Math.ceil`
But good call.

`total_pages: (total.to_f / BaseFacility.per_page).ceil` should do it.

**Comment by patrickvinograd** [comment]
@jholton Yeah I was thinking this was calculated on the frontend so was thinking JS not Ruby.

**Comment by darkbushido** [comment]
Since PPMS isn't paginated this logic is only so the FE can pull another page. 
The change was only done in the CCP controller and not the VA controller.

**Comment by mmiddaugh** [comment]
Created [#6641] for the switch to the ccop controller.
