### ISSUE TITLE
Structured-Data Team: Request load testing, QA, privacy, and security intro 

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#5824]
Hi @pjhill - As part of our orientation, the Structured-Data team (@keithdadkins, @bshyong  and @jjulian) is requesting to meet next week to discuss load testing, QA, etc. 

**Team availability next week:**
Mon - 4:30-5:30 PM EST
Tues - 10-11 AM EST
Weds - 10 Am EST or 12:30-2PM EST
Thurs - 10-12 PM or 2:30-4PM EST
Fri - 3-5 PM EST

Eager to get this information as we're gearing up for our first release! Thank you.

**Comment by pjhill** [comment]
Hey, @srmyers17 , I'm out all next week except for Friday - 2/21.  Would it be OK to schedule something in the Friday - 3-5 PM EST time slot that you listed?

**Comment by srmyers17** [comment]
Yes that works! @pjhill

**Comment by pjhill** [comment]
@srmyers17 -- Invites sent to @keithdadkins, @bshyong and @jjulian, but I wasn't able to find a good email address for you.  Would you like an invite as well?

**Comment by srmyers17** [comment]
@pjhill - Yes, please! sophia.myers@adhocteam.us
