### ISSUE TITLE
Confirm highly trafficked and/or other important test accounts work with mocked auth, resolve if necessary

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#58246]
We have a document with test users that seem to not properly finish auth, we should see if we want to attempt fixing any of these (we should NOT fix all of them, just pick important ones to us or the platform):

https://docs.google.com/spreadsheets/d/1DhqALI0MfcC-j5PLmd_YrlEgQPjxR4lv7-HM5l-kggo/edit#gid=0

**Comment by bosawt** [comment]
Update: We should ensure that as many users as possible in the Test User Dashboard are reflected in mocked auth and are able to authenticate properly

**Comment by joeniquette** [comment]
this is difficult to pick up due the current dev STS errors. There is another ticket that has been give to Joe Tice's team on platform to resolve. If time permits I will try to find a window where these errors on dev aren't occurring. Until then it stays in current sprint to be picked up as soon as possible.

**Comment by joeniquette** [comment]
Working from this sheet now: https://docs.google.com/spreadsheets/d/1jCSScmlTbe2Rz3Bjg4IwfL2n7SNA1T51jkVeGfbXU7Y/edit#gid=0

**Comment by joeniquette** [comment]
@bosawt Document is updated with ICNs for the TUD accounts that arent working correctly in MA: https://docs.google.com/spreadsheets/d/1jCSScmlTbe2Rz3Bjg4IwfL2n7SNA1T51jkVeGfbXU7Y/edit#gid=146563829

**Comment by aparsley** [comment]
Thank you for attaching correct documentation and completing the ticket.
