### ISSUE TITLE
UX treatment to communicate new SSO feature to VA.gov users and frontend implementation

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#5828]
**User Story**
As a user logging in to VA.gov after the SSOe launch, I want some information to be displayed that explains to me that this new feature enables session continuity, so that I do not feel confused or alarmed if I navigate to another SSOe site and find that I am already logged in.

This same treatment will be used to handle:
- Users who log in for the first time after SSOe is launched on VA.gov
- Inbound users who have established an SSOe session and navigate independently to VA.gov in a new tab for the first time after SSOe is launched on VA.gov #5417
- Inbound users who have established an SSOe session elsewhere and are redirected to VA.gov for the first time after SSOe is launched on VA.gov

**Comment by bridgethapner** [comment]
Wireframe is here: https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/407512637

The goal of this modal is to communicate the benefit of SSO to users in terms they'll understand + speak more to value for them (you won't have to sign in again). Users may not know what "single sign-on" means.

Content of modal should be headline, body copy, and CTA to dismiss. Body copy should mention My HealtheVet and eBenefits by name and also allude to other websites.

**Comment by peggygannon** [comment]
@bridgethapner Here is suggested copy for the modal. Please let me know if you have any feedback. 
I'm also including another header idea below if we felt like we need to say "single sign on" in the content.


**Sign in once to access the VA sites you use most**
Now when you sign into VA.gov, we'll also sign you into your accounts on MyHealtheVet , eBenefits,  and other VA sites. So you can track and manage your VA benefits and services with just one username and password.
{CTA button} Continue to VA.gov

Another header option: 
**Welcome to single sign on—one password for your most common VA sites**

**Comment by bridgethapner** [comment]
Thank you @peggygannon! This copy looks good to me. I did speak with the VSP team this morning, and they suggested using a different modal pattern - in which we can use bullet points if we'd like to. Is that something you'd want to leverage now that it's an option?

**Comment by peggygannon** [comment]
thanks, @bridgethapner on the update. 

So instead of a modal, the guidance is to use a header and bullet points? If so, I'll need to recast the language a bit. I didn't write the copy as "bullets." Do you have a visual of what the UX pattern would look like?

**Comment by bridgethapner** [comment]
@peggygannon Yes!

![Group.png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/66e13d77-4bfb-413e-a362-c81431ac7f71)

**Comment by peggygannon** [comment]
Hi, @bridgethapner Here is the update content to fit better into the new modal pattern and one question for you below. Please let me know if you think this'll work? 

for the link, I think we could direct users to this page, https://www.va.gov/sign-in-faq/
Do you know if there's been discussion about updating the FAQ page to remove VA.gov branding once SSO launches?

-----

{title} **Sign in once to access the VA sites you use most**
Now when you sign into VA.gov, we'll also sign you into your accounts on MyHealtheVet , eBenefits, and other VA sites. 

**With single sign on, you can:** 
-	Track and manage your VA benefits and services with just one username and password
-	Use your existing DS Logon, My HealtheVet, or ID.me account to sign in
-	Access the VA sites you use most without having to sign in each time

{CTA button} Continue to VA.gov

[link]Get answers to [frequently asked questions about signing in](https://www.va.gov/sign-in-faq/)

**Comment by bridgethapner** [comment]
Hi there @peggygannon - Thank you for the copy! This looks great. 

I don't believe there's been discussion over removing branding from the FAQ page - good Q. @ambikaroos - see the question below - have you heard anything about this?

1. Will the [sign-in FAQ](https://www.va.gov/sign-in-faq/) page need to be updated to consider SSO, in terms of editing the info there now, adding new info, and speaking more broadly to VA sites over VA.gov?

**Comment by bridgethapner** [comment]
Also @peggygannon - putting the updated text into wireframes, I had a couple of thoughts: 

1. "Now when you sign into VA.gov, we'll also sign you into ~your accounts on~ MyHealtheVet, eBenefits, and other VA sites." - I think it might confuse users to say "your accounts" since they may be thinking of their login credentials as their accounts, like DS Logon account. Are you okay with removing the struck-thru part?

2. I removed the first bullet since it's the same functionality that exists today.

Let me know if looks okay.

![#5828_In-page Modal @1x.png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/2a3c79ef-d04e-4c3d-896e-2c4de72bf981)

**Comment by peggygannon** [comment]
Thanks, @bridgethapner Yes, I'm fine with taking out the strikethrough copy. and good point about removing that first bullet point. 

also, can you put this line on its own and in boldface. This is a content pattern we use across the site when we want to highlight and as a means to set up the bullets. 

**With a single sign on, you can:**

**Comment by ambikaroos** [comment]
@bridgethapner - I don't think we have a _requirement_ to make the language on the sign in page inclusive of other SSOe enabled sites (listed here: https://eauth.va.gov/accessva/), but we certainly _could._  My feeling is that whatever we decide, we should keep it parallel to VA.gov login modal language.  Its possible that in the future, other VA sites like MHV or eBenefits may migrate to using this standalone login page, at which point we also might want to re-address.

**Comment by bridgethapner** [comment]
@ambikaroos That makes sense! I wonder if now, we might want to consider adding an accordion fold with something like "What is single sign-on?" - if we add [the FAQs link](https://www.va.gov/sign-in-faq/) in the SSO comms modal, I think we need to add that. We can also remove the link. Both are fine solves for now, I think. Imo we should update the FAQ page only if we have historic data that shows users are accessing that page. 

@peggygannon Thank you for the feedback! I have made the change to the bullet headline. Updated comp is here: https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/407512637

**Comment by peggygannon** [comment]
Thanks, @bridgethapner updated mockup looks good.

**Comment by bridgethapner** [comment]
@hinzed1127 Hi there Dan - this modal uses the **Informational / Plain Text modal** from the design library.

Desktop wireframe is [here](https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/407512637); mobile wireframe is [here](https://adhoc.invisionapp.com/share/5QWAJJQNG2J#/screens/408300890). The link to "frequently asked questions about signing in" is https://www.va.gov/sign-in-faq/.

**Comment by hinzed1127** [comment]
UX question for @bridgethapner / @peggygannon : with regards to #6336, is this something we want to communicate in the modal and/or the sign in faq page? Basically communicate to users that SSO implies both being logged in across sessions and uniformly _signing out_ across sessions too.

**Comment by bridgethapner** [comment]
Hi there @hinzed1127 - that's a really good point. Thanks for bringing this up! Yes, we should include that here. I added a bullet & tweaked the bullet header to speak to that - @peggygannon can you review? 

Also heads up the FAQ link has been removed for now - my POV is we don't need FAQ content at SSO launch. We can add as a future improvement.  

![#5828_In-page Modal @2x.png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/eb73e207-cf9d-4d2b-8b64-4720de366749)

**Comment by peggygannon** [comment]
hi, @bridgethapner here are some additional edits. 

it looks like in the updated screenshot, the "a" got dropped from this line: 

**With a single sign on, you can:**

Here's slight tweak on the last bullet: 
-Sign out of VA.gov and be signed out of other VA sites

**Comment by bridgethapner** [comment]
Thank you @peggygannon! 

Alright, @hinzed1127 we are good to go with the updated copy in [wireframes](https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/407512637). (And [mobile](https://adhoc.invisionapp.com/share/5QWAJJQNG2J#/screens/408300890)). And copy is here below: 

### Sign in once to access the VA sites you use most
Now when you sign into VA.gov, we'll also sign you into MyHealtheVet, eBenefits, and other VA sites. 

**With a single sign on, you can:**

- Track and manage your VA benefits and services with just one username and password
- Access the VA sites you use most without having to sign in each time
- Sign out of VA.gov and be signed out of other VA sites

_Continue to VA.gov_
