### ISSUE TITLE
BE | Profile |  Grant Berni and Travis access to feature flag flipper

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#58286]
## Background
Add Travis and Berni to the [yml file](https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/settings.yml) for feature toggle access. 

Email addresses will be shared via slack

## Acceptance Criteria
- [x] Add Travis and Berni to the file 
- [ ] confirm they have access to the feature toggle page

**Comment by tpharrison** [comment]
@mtcA6 @BerniXiongA6 You should have administrative access to toggle features.  When you get a chance, please try it out in staging - https://staging-api.va.gov/flipper/features.  

For reference, here are the feature Admin URLs for each environment:
- https://dev-api.va.gov/flipper/features
- https://staging-api.va.gov/flipper/features
- https://api.va.gov/flipper/features

Let me know if you have any questions/issues.

Thanks!

**Comment by mtcA6** [comment]
@tpharrison meant to test this yesterday and then got pulled into calls in the afternoon! this works! and thanks for the links!!!!
