### ISSUE TITLE
Documentation: SOCKS Troubleshooting and Best Practices

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#58282]
<b> Description:</b>

The goal of this ticket is to identify best practices and troubleshooting tactics for SOCKS related requests.

<b> Definition of Done:</b>

- All tasks below are complete

<b> Tasks</b>

- [x] Document best practices and troubleshooting tactics here (Rebecca):
https://vfs.atlassian.net/wiki/spaces/PTST/pages/2633236495/SOCKS+Troubleshooting+Best+Practices
- [x] Send for review to the team in #platform-tech-support-team
- [x] Add the link to the Advanced Troubleshooting section of the page here (Alyssa will do this): https://vfs.atlassian.net/wiki/spaces/PTST/pages/2630353240/Advanced+Ticket+Support+Best+Practices
- [x] Add a few more basic troubleshooting tips to the [Troubleshooting section](https://depo-platform-documentation.scrollhelp.site/getting-started/accessing-internal-tools-via-socks-proxy#AccessingInternalTools(viaSOCKSProxy)-Troubleshooting-For-MacTroubleshootingforMac) of the Accessing Internal Tools site on the platform website. 👉 Edit from [this confluence page](https://vfs.atlassian.net/wiki/spaces/GS/pages/1821081710/Accessing+Internal+Tools+via+SOCKS+Proxy).

<b>Resources:</b>

Slack thread: https://dsva.slack.com/archives/CBU0KDSB1/p1683056240515669

**Comment by alyssagallion** [comment]
Feedback from the Slack Thread mentioned above:

**Melissa Miller**

Some feedback thoughts:

- The PAT part was confusing
- I think things went wonky when I first ran setup and there were conflicts/confusion related to the key I had generated for my git setup. Maybe some clarification there with a warning?
- I'd probably add the "trash everything and start over" instructions to the troubleshooting so folks know it's ok to try that. I was afraid to delete the file because I was worried about making things worse, but that ended up being the fix I needed.

**Comment by rmtolmach** [comment]
I know @flooose had opinions about this, so I added him as an assignee. I can shepherd this through to the end, though. 

I'm going to add a task to update this troubleshooting section of this page on the platform website as well: https://depo-platform-documentation.scrollhelp.site/getting-started/accessing-internal-tools-via-socks-proxy#AccessingInternalTools(viaSOCKSProxy)-Troubleshooting-For-MacTroubleshootingforMac. I think we could at least add a few more tips there!

**Comment by flooose** [comment]
Ok, so I've played a little more with the setup and the documentation, and if I understand everything correctly, the only people who *might* need a PAT are non-developers going through this setup. If that's the case, then I say  remove any mention of the PAT from the documentation. 

I think the only thing the token does is allow `vtk` to add your ssh key to your github account for you. I would argue though, if we already have people (even non-developers) running things in the terminal, like `sudo gem install vtk`, we can trust them to upload the ssh key to their github account themselves. It's probably easier than generating the PAT anyway.

If we go this route, I think we can make the documentation a lot less confusing.

@rmtolmach you're probably wondering why I wrote all of this when you were just asking about your "Troubleshooting" section :)

I do think it's good that you added it. It's a way to get a look at the "magic" that `vtk` hides away from you and does for you. I'm just not sure, it would have helped Melissa Miller (and one other person iirc) avoid their problem of accidentally using their PAT as a password for an ssh key.

What do you  think?

**Comment by rmtolmach** [comment]
I added an info panel to the [platform website](https://vfs.atlassian.net/wiki/spaces/GS/pages/1821081710/Accessing+Internal+Tools+via+SOCKS+Proxy) explaining that starting over is a reasonable solution. 

My edits are here: https://vfs.atlassian.net/wiki/pages/diffpagesbyversion.action?pageId=1821081710&selectedPageVersions=47&selectedPageVersions=48

**Comment by flooose** [comment]
I think this is getting us close to what we need. I do still see a couple of issues though:

1. If the person _does_ have `git` set up, there's a pretty high likelihood that they've done it with the classic ssh key names, i.e. `id_rsa` and `id_rsa.pub`, but `vtk` expects the keys to be named `id_rsa_vagov` and `id_rsa_vagov.pub`, meaning, `vtk` will generate an additional key-pair. I think it might be good to add a note about this, so that it's clear that the user will have an additional key-pair that also needs to be present in github.
2. If the user _doesn't_ have `git` set up, it will _offer_ to use either password _or_ access token to upload the ssh key. This gets back to the wording in [my comment](https://vfs.atlassian.net/wiki/spaces/GS/pages/1821081710?focusedCommentId=2642739346) about this in confluence. With all the changes we've made to the documentation already, I think the wording isn't as important to change, but it might still throw some people off 🤷 

Is that all understandable?

**Comment by rmtolmach** [comment]
### Notes from setting up socks on my new computer
I generated new ssh keys, confirmed I was able to `git clone`, etc. Then ran `vtk socks setup` and hit enter (for no passphrase). Then I filled out the socks request and merged the devops PR. And then I went back to my terminal and ran `vtk socks setup` again and I got an error:
```
----> Testing SOCKS SSH connection... ✅ DONE
----> Configuring SOCKS tunnel to run on system boot... ❌ FAIL
----> Configuring system proxy to use SOCKS tunnel... ✅ DONE
----> SOCKS setup complete.
```
It was the EOD so I closed my computer and then this morning it was still giving that same message. I opened Chrome and it worked 🎉 then I restarted Firefox (which is the browser I had originally been using) and it worked 🎉 So a browser restart worked. I added this to the troubleshooting doc. 

### Responding to flooose
That all makes sense, but this ticket is mostly scoped to this internal troubleshooting doc in confluence: https://vfs.atlassian.net/wiki/spaces/PTST/pages/2633236495/SOCKS+Troubleshooting+Best+Practices so I'm going to close out this ticket 🎉 
I do agree that the Platform Website SOCKS guide needs some more work to make it less confusing. Maybe we could find a time to just get that done.
1. I could see this being a good addition. But I could also see it being too much information 🤔 
2. Maybe we could have a flow for people _without_ git set up and a flow for people _with_ get set up.
