### ISSUE TITLE
Midpoint Review - Content Feedback - Disability Comp Application (21-526EZ), 526 Intro Pages

### ISSUE THREAD

**Issue by CherylEvans** [department-of-veterans-affairs/va.gov-team#58293]
## VFS actions
- [x] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [x] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [x] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [x] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- I know you've been working with Beth Potts to refine the Content for this product. I encourage your team to continue this important work with SWCAIA and fully implement their recommendations. 

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (e.g., engineering/coding notes).

### Must 

- There are multiple instances throughout the pages of the Sketch files where contractions aren’t used when they could be, per VA.gov [guidance](https://design.va.gov/content-style-guide/plain-language/use-contractions). 
- There is an inordinately large amount of text for an intro page.  I recommend reducing the amount of text used, as it could lead to cognitive overload for the Veteran.
- Regarding your Content source of Truth, there are numerous misspellings, grammar, and punctuation errors throughout the SoT that are reflected in the Sketch files.  For example, "seperately" is misspelled (should be separately), and there is a sentence, "Are you a currently on active duty as a service member?" that is poorly worded. I recommend working with SWCAIA to resolve these issues in the SoT to resolve the same errors in the Sketch files.
- The last paragraph on the Intro page, "If you want to submit additional documentation after you submit your claim, you have up to one year to do so.  However, we may decide your claim before the end of that one-year period, in which case we may request you.."  It ends there without any resolution.  I recommend working with SWCAIA to ensure content "completeness."

**Comment by lydiahooper** [comment]
Thank you @CherylEvans for pointing out those errors, and for your patience as I continued to work on the SOT and prototypes after receiving Beth's feedback. We will continue to work with Beth to make the content the best it can be. We are hoping to learn through research how to balance the need for information with concerns about cognitive overload.
