### ISSUE TITLE
Demo flags aren't updating in staging tool 

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#58308]
## Description 

I used check in, answered "yes" to demo questions. Then, logged into the staging scheduling tool. And, the demos were still marked as "needs review." However, I scheduled another appt, checked in and was not asked the demo questions. 

Expectation is that the demo fields in the staging tool would have updated to "no." 

## Tasks

- [ ] Fix demo flags in staging appt tool

**Comment by loripusey** [comment]
@wullaski is there a quicker way to update these flags?

**Comment by benbrasso-agile6** [comment]
@wullaski these may be working as expected now. Working for me.

**Comment by wullaski** [comment]
@benbrasso-agile6 @loripusey It wasn't working for me this morning but I got on a call with @acrollet and we got it figured out. There was a [deployment](https://github.com/department-of-veterans-affairs/chip/releases/tag/v3.1.0) to vista last week that changed what endpoint to use for demographics update. Give it another shot and let me know if you run into any problems.

**Comment by benbrasso-agile6** [comment]
Think it was working today. Will check again next week.

**Comment by benbrasso-agile6** [comment]
Fairly certain this has been fixed. closing
