### ISSUE TITLE
Adding Adam Antonioli to DSVA Slack

### ISSUE THREAD

**Issue by carly-yamrus** [department-of-veterans-affairs/va.gov-team#58306]
I requesting access for Adam Antonioli, adam.antonioli@va.gov, who accidentally let his original slack invitation expire and will need to be re-invited.

Adam is a developer on the Memorials Self-Service team.

Thank you

**Comment by MichelleDieudonne** [comment]
@LEHigley Can we please get a status on Adam's DSVA Slack access?  He is a new developer on our project and is unable to reach out to the Platform via DSVA Slack for PR Review and other items necessary to preform his duties.  

Thank you,
Michelle
