### ISSUE TITLE
Vets-api terminal access for Tuong Ngo

### ISSUE THREAD

**Issue by tuongngova** [department-of-veterans-affairs/va.gov-team#58305]
### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Tuong Ngo

### Your GitHub handle (terminal access is managed through GitHub)

tuongngova

### Team, Role, and Company of the target individual

Backend DevOps Engineer with Identity team

### Product Manager (PM) name and email

Mike King (Mike.King@oddball.io) PM

### Product Owner (PO) name and email

John Rahaghi; john.rahaghiva@gmail.com

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### COR Name (leave "None" if you listed an AWS user name above)

Cecila Lee

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

Oddball - Amber Malcolm

### Access Expiration

ongoing

### Additional Notes

As a DevOps Engineer for Surge Identity team, I need to have on going access to support the separation of sign-in-service api out of the monolith vets-api containerization.

Please reach out to Joe Niquette should you need any validation.

### User must exist in a roster before vets-api terminal access can be granted

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added
- [ ] If they included an AWS user name, check to see if their user name is listed in [iam_users.tf](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf)
- [x] Comment in this issue saying which roster the user is listed in and confirming their AWS user name (if applicable)

**Comment by ryan-mcneil** [comment]
Found on VFS Team Roster, but does not have AWS user.

**Comment by ryan-mcneil** [comment]
@tuongngova You’ve been granted access to the `dev`, `staging`, and `sandbox` environments.

Here's some additional documentation for the [Vets API on EKS](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-TerminalAccess)

Access to `prod` is pending approval by OCTODE, and we'll update you as soon as it's available.

**NOTE** Please provide a screenshot of your EQIP Transmittal, as it will expedite Production approval.

**Comment by considerable** [comment]
VFS Team Roaster

**Comment by BillChapmanUSDS** [comment]
Please add EQIP transmittal details. Thanks.

**Comment by ryan-mcneil** [comment]
@tuongngova Apologies for how long this is taking. I'm going to update this template as apparently a screenshot of the EQIP is required now. If you can please provide the screenshot (It's an email title `Transmittal Notice--<NAME>...` of the body of the email, Bill will approve on his next rounds.

**Comment by joeniquette** [comment]
@ryan-mcneil just wanted to document here that the above mentioned access is no longer required. Tim will be moving off of the project on the 19th of June.

**Comment by ryan-mcneil** [comment]
Closing, as user no longer requires access
