### ISSUE TITLE
[Tier 3: Medium] Users Can't Submit Disability Claim Application

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#5832]
**Issue Description:** Users are completing the disability claims application and getting to the end of the application. When they get to the end and click the "submit" button, they are seeing the below error message and can't submit their application. 

_We’re Sorry. We can’t submit your form right now. We’re working to fix the problem. Please make sure you’re connected to the Internet, and then try saving your form again. If it still doesn’t work, please call VA Benefits and Services at 800-827-1000._

Users have checked the "affirm" box, have attempted on different devices, accounts, browsers. The issue continues to happen. 

**Priority:** Medium

**Total Number of Issues:** 5

Issue Number and User Description:

**- IRIS: 200131-000708**

_I am having issues trying to submit a disability increase claim on VA.Gov. I have   logged into VA.GOV thru my PC (internet explorer), iphone (Safari), and   MacBook (Safari) by using the Myhealthevet and Phone pin to verify it’s me logging in. Side note I also tried submitting via ID.me and DS Logon as well, all ended up with the same result. Once on the main page I scroll down to   “Disability” and click on the link “File for a VA disability increase”. I currently have a compensation application (21-526EZ) that I have started and   I click on the link “Continue your application”. I will add that I even tried   deleting the application and starting a new one, same result I’m about to   share. The next screen says “You already have an Intent to File” and I click   “Continue”. It then brings me to the File for Disability Compensation Form   210526EZ. I fill out all the steps all the way to step 5 of 5 called “Review   Application”. I verify everything is correct and I check the box next to “I   have read and accept the privacy policy”. When I click “Submit application” I   get this error:          Red Exclamation Point – We’re Sorry. We can’t submit your form right now.   We’re working to fix the problem. Please make sure you’re connected to the   Internet, and then try saving your form again. If it still doesn’t work,   please call VA Benefits and Services at 800-827-1000.          I tried calling that number and was told there is no helpdesk for VA.GOV   only the ebenefits site. Moreover, that I can’t submit for an increase on the   ebenefits site, only on VA.gov. I’ve tried on Safari -MAC OS and on Internet   Explorer. I’ve been trying for a couple weeks now ._

**- IRIS: 191129-000476**

_I am   trying to send an updated disability claim request to the VA via the va.gov   website and I get to the "Submit Application" button and it shows   "Sending", but nothing else happens. I've waited for hours for the   Sending to complete, but it never does.     website URL:   va.gov/disability/file-disability-claim-form-21-526ez/review-and-submit_

**- IRIS: 200113-001235**

_I am   going through the application process for compensation. I have filed      with ebenefits before but they told me any supplemental claims must go        through va.gov. I add all my info, upload supporting docs, and go to hit        submit and the error message occurs. Here is the message. URL        https://www.va.gov/disability/file-disability-claim-form-21-526ez/review-and-submit.        I have a MacBook and have tried safari and chrome. I've tried a dell PC        internet explorer. I've signed in using DS logon and ID.me.           We’re sorry. We can't submit your form right now.           We’re working to fix the problem. Please make sure you’re connected to the        Internet, and then try saving your form again.      Save your form      .           If it still doesn’t work, please call VA Benefits and Services at      800-827-1000 <18008271000>.      If you have hearing loss, call TTY: 711._

**- IRIS: 200117-001165**

_I log   into VA.GOV by using the Myhealthevet and Phone pin to verify it’s me logging   in. (Side note I also tried submitting via ID.me and DS Logon). Once on the   main page I scroll down to “Disability” and click on the link “File for a VA   disability increase”. I currently have a compensation application (21-526EZ)   that I have started and I click on the link “Continue your application”. I   will add that I even tried deleting the application and starting a new one,   same result. The next screen      says “You already have an Intent to File” and I click “Continue”. It then   brings me to the File for Disability Compensation Form 210526EZ. I fill out   all the steps all the way to step 5 of 5 called “Review Application”. I   verify everything is correct and I check the box next to “I have read and   accept the privacy policy”. When I click “Submit application” I get this   error:           Red Exclamation Point – We’re Sorry. We can’t submit your form right now.   We’re working to fix the      problem. Please make sure you’re connected to the Internet, and then try   saving your form again. If it still doesn’t work, please call VA Benefits and   Services at 800-827-1000.           I tried calling that number and was told there is no helpdesk for VA.GOV   only the ebenefits site. Moreover, that I can’t submit for an increase on the   ebenefits site, only on VA.gov. I’ve tried on Safari -MAC OS and on Internet   Explorer. I’ve been trying for a couple weeks now._

**- IRIS: 200129-000552**

_My compensation claim (12-04-2019) been receiving error when submitting. I did   all proper measures and checked the affirm but still having a technical error   box. My claim is completely finished and a I’m at-risk/hardship veteran.   Overall, it has been ready to be submitted._

**Comment by Mottie** [comment]
- IRIS: 200131-000708 & IRIS: 200117-001165 might be the same user, and IRIS: 200113-001235 (a different user). This looks like it might be that the save-in-progress component is showing this error. I'm not sure if it can't load the in-progress data, or if there was a problem with actually submitting. We'll need to investigate this more.

- IRIS: 200129-000552 - the error here _might_ be the same as the above issue, but it isn't clear.

- IRIS: 191129-000476 shouldn't be happening any more. The submit _should_ time out after 30 seconds and add a log in the console - we'll need to actually see the error to make it easier to troubleshoot the problem.

**Comment by ndsprinkle** [comment]
The source of the "Please make sure you’re connected to the Internet, and then try saving your form again" error message comes from [here](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/forms/save-in-progress/RoutedSavableReviewPage.jsx#L105), but I'm not sure what causes the message to appear. That message gets passed down through several components, so it's difficult to track it down

**Comment by clantosswett** [comment]
@Mottie see my comments below in **bold**

IRIS: 200131-000708 & IRIS: 200117-001165 might be the same user, and IRIS: 200113-001235 (a different user). **You are right. This is the same person. Sorry about that!** 

IRIS: 191129-000476 shouldn't be happening any more. The submit should time out after 30 seconds and add a log in the console - we'll need to actually see the error to make it easier to troubleshoot the problem. **I can reach out again to this user and see if they were able to submit**

**Comment by clantosswett** [comment]
We received another example of a user having the issue with the Sending... issue. I've attached the screenshot from the user that shows what is happening. 

![Screenshot_20200207-133956_Chrome.jpg](https://images.zenhubusercontent.com/5ccc89746759571a65993844/6acc0216-d3e3-4637-8e1d-549d7a14b22d)

**Comment by Mottie** [comment]
Hmm, the submit button shouldn't get stuck any more... after 30 seconds, it _should_ show an error messages reporting that there was a problem.
- If that submit button stays stuck, then I'll have to look into this situation again.
- If it does un-stick after 30 seconds, maybe we could get in on a call with them so we can look at the data that is output to the console log.

**Comment by ndsprinkle** [comment]
@Mottie So right now there is a hard coded 30 second timeout on the button? Like after 30 seconds it will auto fail? I can look into that to see if there's any condition that would break that

**Comment by Mottie** [comment]
Yes, I added that in this PR: https://github.com/department-of-veterans-affairs/vets-website/pull/11508

**Comment by luke-gcio** [comment]
Closing - this is as far as we can get with this particular bug since the 30 second key stuck fix was worked.

**Comment by clantosswett** [comment]
@luke-gcio I am reaching out to the users to see if they are still unable to submit their disability claim application. If I hear back that they are still stuck in this way, do you propose creating a new issue to address that issue?

**Comment by luke-gcio** [comment]
I would rather create a new issue unless it ends up being the same veteran with the same issue.

**Comment by clantosswett** [comment]
I heard back from one of the veterans from this issue and they are having the same problem. I haven't heard back from any of the other veterans. 

**- IRIS: 200113-001235**
_New Communication_

Negative. Just tried to submit the previous claim I had in progress and 
says the same response. Unable to submit... 

_Previous Communication_

I am going through the application process for compensation. I have filed with ebenefits before but they told me any supplemental claims must go through va.gov. I add all my info, upload supporting docs, and go to hit submit and the error message occurs. Here is the message. URL https://www.va.gov/disability/file-disability-claim-form-21-526ez/review-and-submit. I have a MacBook and have tried safari and chrome. I've tried a dell PC internet explorer. I've signed in using DS logon and ID.me. We’re sorry. We can't submit your form right now. We’re working to fix the problem. Please make sure you’re connected to the Internet, and then try saving your form again. Save your form . If it still doesn’t work, please call VA Benefits and Services at 800-827-1000 <18008271000>. If you have hearing loss, call TTY: 711.

**Comment by luke-gcio** [comment]
What is the date of the above submission attempt?

**Comment by clantosswett** [comment]
2/26/2020

**Comment by uberoak** [comment]
Was there ever a resolution for this? I am trying to submit my VA 21-526EZ as well, and I am getting the exact same error, and have been for the past year.

**Comment by uberoak** [comment]
Hey! Not sure if anyone is still tracking this issue, but I found a resolution. You cannot submit the form successfully if you are logged in through HealtheVet. You must log-in through Id.Me, and then it will work. 

It only took me 363 days in order to figure this out.

**Comment by LUPUS2006** [comment]
Hi!  I'm a Veteran and having this exact problem.  76 phone calls to Tier 2 and Tier 3 support, Whitehouse help line, etc. and no answers.  Cleared cache, cookies, tried computers, ISP's, and still the same problem.  I've signed into ID.me and nothing different.  When you "hit" the submit application, it gives you the warning message that the VA is having a tough time processing the claim.  PLEASE help......Please

**Comment by luannpeach** [comment]
Hi. I am a Veteran and having the problem with submitting my claim.  I have also called but no one seems to be able to help.  I have used multiple computers and platforms.
This is what it ways when I select submit:

**It's taking us longer than expected to submit your claim.**
This delay should be resolved within a few hours. We’ll keep trying to submit your claim. You can check the status of your claim online after 24 hours.

[Check the status of your claim](https://www.va.gov/track-claims)

If you don’t see your disability claim online after 24 hours, please call Veterans Benefits Assistance at [800-827-1000](tel:+18008271000), Monday through Friday, 8:00 a.m. to 9:00 p.m. ET**

PLEASE HELP ME!  This has been going on since last month.  I have tried everything that is suggested on this site.

**Comment by crcfail** [comment]
Having same problem:

"It's taking us longer than expected to submit your claim.
This delay should be resolved within a few hours. We’ll keep trying to submit your claim. You can check the status of your claim online after 24 hours."

I've used:
IE11, Edge, Firefox, Chrome - all from PC
Then tried Firefox and Chrome from Android both with local wifi and data
Plus every option with 8.8.8.8 DNS and OpenDNS.

Nothing works, been trying for about a week with always the same message. Could this perhaps be tied to a file format somewhere in uploaded files within the application, such as pdf, doc, jpg etc that the system isn't liking?

**Comment by crcfail** [comment]
I tried 11 times with 11 failures. I gave up and a few weeks later there
were 11 identical claims filed. So each time you're sending it, it could be
going through.

**Comment by killjoy1022** [comment]
Thanks.. I'll keep an eye on it. 



> I tried 11 times with 11 failures. I gave up and a few weeks later there were 11 identical claims filed. So each time you're sending it, it could be going through.
