### ISSUE TITLE
Temporarily fix incorrect timezone in new appointment list.

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#58321]
This ticket is to fix the incorrect timezone we're seeing in the upcoming appointment list for the new appointment list feature.

**Comment by ldelacosta** [comment]
@simiadebowale is this work under `va_online_scheduling_convert_utc_to_local` feature toggle.

**Comment by simiadebowale** [comment]
this is ready for validation

**Comment by simiadebowale** [comment]
@ldelacosta - no, it's not

**Comment by ldelacosta** [comment]
We addressed the timezone issue. I validated the appts for Judy in staging and the timezone matches on the appointment list and appointment details. Please reach out if you guys see the same issue elsewhere. @marcynadeau @beth-wodzinski 

Issue before the fix:![Screenshot 2023-05-17 at 1.00.55 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/2264fb86-1de3-4d60-9f6b-80b26779a245)
![Screenshot 2023-05-17 at 1.01.22 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/114dc2e0-ec51-4d16-9a79-06bc19754237)



Fix: 
![Screenshot 2023-05-17 at 12.57.38 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/c5c38d49-caa4-47b3-95b4-66f6e386b720)

![Screenshot 2023-05-17 at 12.58.15 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/7f12a242-e8fd-4ce4-9aae-286c19bee080)

**Comment by MaragathaJayashankar85** [comment]
SQA team has tested this. Closing this ticket. Thanks. CC: @marcynadeau @beth-wodzinski
