### ISSUE TITLE
Application Preferences Research

### ISSUE THREAD

**Issue by LynneJohnson224** [department-of-veterans-affairs/va.gov-team#58337]
For the health tools (MR, SM, Appointments, Medications), determine if users are allowed to set application specific preferences and document the answer.  Confirm with each team they are planning/researching/developing their tool level preferences. 

Note: if the tools do not allow a user to set application specific preferences, will close out the app preferences effort/no further work or research will be needed. 

### Acceptance Criteria:

- Document results of slack messages with each team.
- Create follow on tickets if needed to track work for application level preferences

**Comment by fmccaf1** [comment]
![image.png](https://images.zenhubusercontent.com/629a1db0e70457da479e69ae/fde71950-0493-4567-a734-45493dabd02a)

[Link to thread^](https://dsva.slack.com/archives/C03ECSBGSKX/p1684855452609199)

**Comment by fmccaf1** [comment]
![image.png](https://images.zenhubusercontent.com/629a1db0e70457da479e69ae/790efb00-230e-4659-8ac9-3de916663b48)

[Link to thread^](https://dsva.slack.com/archives/C04PRFEJQTY/p1684855553782939)

**Comment by fmccaf1** [comment]
### To summarize findings from the above slack threads: 
- All 4 product teams will be implementing preferences associated with their tools
- Currently, Secure Messaging, Medical Records and Medications have preferences
- Appointments does not currently have preferences, but believe they have a need for preferences in the future

@LynneJohnson224 @batemapf I'm not sure what exactly is the follow-on work from these findings (for the purpose of making tickets). Should next tickets be for work simply to get more specific and document what we can learn from each team about current and future preferences?

**Comment by batemapf** [comment]
honestly skimming those slack threads, it doesn't seem like there is much for us to do in terms of follow on work. seeing a number of notifications related preferences, which belong to their own bucket and i trust will be managed by the individual application team + VA Notify (+ and likely the My VA/authenticated experience team). other things like SM message signature or VHIE opt in/out are very application specific and i don't think need any kind of central coordination from our team. so i think this is safe to close out and we can say that no further work is needed in the application-level preferences space.
