### ISSUE TITLE
Analytics Reporting Request for VA Online Scheduling 

### ISSUE THREAD

**Issue by lalexanderson-dsva** [department-of-veterans-affairs/va.gov-team#5833]
# Metrics Reporting Request: VAOS Foresee Analytics

## What this form is for

Use this template to request performance, usability, or outcomes va.gov metrics that is difficult to access or that needs analytics interpretation.

Insights will usually provide data reports within the current sprint, but if there is time-sensitivity, please note them in "additional comments."

## Instructions

Please fill out the following sections:
- [ ] Description
- [ ] Timeframe for Analytics Requested
- [ ] Analytics to Track Down
- [ ] Which Product Questions are you trying to answer?
- [ ] Additional Comments

## Description
Who is this request for?: 
- [This request is for Lauren Alexanderson & the VAOS Stakeholders (Kathy Frisbee, Leo Greenstone, Kay Lawyer, Steve Eaton, Eric Hopkins)]
    _Send Slack message to DSVA Slack Channel, `#VFS-Platform-Support`, that includes: email address(es) for user(s) requesting data and link to this Github issue._
- What team/project is this work for? VA Online Scheduling 

## Timeframe for Analytics Requested
_Monthly_

## Analytics to Track Down

> - [ ] Foresee data from the 2 links in: https://github.com/department-of-veterans-affairs/va.gov-team/issues/3452 
> - [ ] Scheduled appointments 
> - [ ] Appointment requests 
> - [ ] Canceled appointments 

## Which Product Questions are you trying to answer?
- Did we increase the number of veterans entering the 'new appointment' flow ?
- Did we increase the percent of veterans who are able to successfully request or schedule an appointment after starting the 'new appointment' flow compared to the existing tool? 
- Are users satisfied with their experience? Were they able to do what they were trying to do? 

## Additional Comments
_We're looking to feed this data into an existing VAOS monthly data report._

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by lenaecb** [comment]
@nedierecel @narin - at this point do we want to close this ticket or keep it open? It looks like most of the feedback for analytics is falling into our Event tracking ticket

**Comment by nedierecel** [comment]
Hello @lenaecb - I'm going to close this since we are addressing the reporting requirements in #6961.

CC: @joanneesteban
