### ISSUE TITLE
[Tier 3: Medium] User's rated disability is not appearing in disability claim application

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#5834]
**Issue Description:** There is one user that has reported trying to file a claim for increased disability rating but is unable to select one of his previously rated disabilities.  The user is going through the application but when he gets to the page where he is asked to select a current rated disabilities, he is unable to because none of his claims are showing (see screenshots below)

I followed up with the user to determine if he was sure he had rated disabilities to select and he responded that he has "three rated conditions from 2011 not filing on a new condition." I was also able to verify this in SHARE. 

**Priority:** Medium

**Total Number of Issues:** 1

Issue Number and User Description:

**- IRIS: 200121-000695**

_I am   attempting to file a claim for increased disability rating, i have the   application in progress but the website is not allowing me to select current  rated disabilities._

**Comment by clantosswett** [comment]
![rated disability](https://user-images.githubusercontent.com/32465263/74447460-6ad1cb80-4e47-11ea-95ae-41cb5572f385.png)

![rated disability error](https://user-images.githubusercontent.com/32465263/74447495-7ae9ab00-4e47-11ea-8bae-cadf06dea217.png)

**Comment by luke-gcio** [comment]
Acknowledging the assignment to Benefits and Memorials team.

**Comment by ndsprinkle** [comment]
I think @SMLuthi and I will need more specific details about this veteran, but I will go ahead and investigate situations that cause no rated disabilities to appear. Silvio also may understand this situation more and there may be an obvious reason the disabilities are not appear.

**Comment by clantosswett** [comment]
@ndsprinkle let me know what specific details would be helpful. I do have some access to additional information and can also reach out to other VA teams for any other missing information. I can also do direct follow up with the veteran with any questions you might have.

**Comment by ndsprinkle** [comment]
@SMLuthi After digging into the code, it looks like ratedDisabilities comes directly from the back end and were aren't doing any filtering that would cause rated disabilities to disappear from the list.

**Comment by ndsprinkle** [comment]
The form also isn't doing any checks on the "One or more of my rated conditions that have gotten worse" checkbox, so we display that as an option even if the veteran doesn't have rated disabilities. @clantosswett but you said you confirmed the veteran does indeed have rated disabilities?

**Comment by clantosswett** [comment]
@ndsprinkle yes. I was able to confirm they had three rated disabilities from 2011.

**Comment by SMLuthi** [comment]
@clantosswett @ndsprinkle We are going to need to reach out directly to EVSS for this. Retrieving the rated disabilities is a straight pass through for us to their API. So most likely the veteran isnt seeing disabilities because EVSS isnt returning any to us. EVSS will need to be contacted with the veterans information so they can investigate.

**Comment by Kimberley2019** [comment]
@SMLuthi contacting EVSS, is that something that you or one of your team members will do or is that a task for @clantosswett and @Kimberley2019 ?

**Comment by clantosswett** [comment]
I reached out to the EVSS team but would like to include someone from the benefits team in that thread as they already have follow up questions. Who should be included? @SMLuthi @ndsprinkle

**Comment by AZSchneider** [comment]
Can you include @SMLuthi and @luke-gcio (and me for awareness) on the email chain?

**Comment by luke-gcio** [comment]
Thanks @clantosswett I see the email.

**Comment by Kimberley2019** [comment]
@SMLuthi @clantosswett 
I have reach out to the user today, requesting an update.  I also informed him that @AZSchneider  has attempted to contact him for a follow up call.  Advised him that he can respond to either email.  
Will keep everyone posted if/when I receive a response.  Please do the same if he responds to the email that Andrea sent on March 25th.

**Comment by Kimberley2019** [comment]
@SMLuthi @clantosswett @AZSchneider 
I am unsure if anyone else has heard back from the user, but I have reached out to the user again today.

**Comment by Kimberley2019** [comment]
@SMLuthi @AZSchneider @ndsprinkle @luke-gcio @clantosswett 
I have not heard back from the user.
Has there been any movement on this issue?  If not, can the team advise on how you would like to handle this issue?  If yes, can the ticket be updated with the information and closed?

**Comment by clantosswett** [comment]
User was able to see rated disabilities and also able to submit their claim application online. If @annaswims was the one to find the solution to this problem. Thank you and also if you want to add anything to this ticket for documentation, please do.
