### ISSUE TITLE
Life Insurance Hub IA Audit 2023: Draft

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#58345]
VA.gov is constantly launching new too content and tools, and as well as continually updating content to ensure accuracy.  As a result of this constant growth and evolution, the organization of pages and features on the site, as well as implementation of key navigation components, can fall out of sync with standards.   

The purpose of the annual IA audit is to quickly review all pages and features within the unauth benefit hub space to identify IA debt that needs to be corrected to ensure proper site structure and accurate navigation and flow.

Audit focus area: Life insurance hub

[IA audit process info](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/information-architecture/process/ia-audits)

**Comment by jennymayoco** [comment]
- [ ] Go through audit template and document benefit page (started on 08/25/2023)
- [ ] Share with Kristin for her review
- [ ] Share findings with Mikki and update audit template with feedback
- [ ] Share findings with content team and update audit template with feedback
- [ ] Note suggested changes and confirm with team if these are good to go
- [ ] Make IA changes to benefit page
- [ ] Download PDF and upload to GH IA folder for documentation

**Comment by jennymayoco** [comment]
Closing this ticket as the first step in the audit is done
