### ISSUE TITLE
AWS access for Josh Mills

### ISSUE THREAD

**Issue by jtmst** [department-of-veterans-affairs/va.gov-team#58352]
### COR Name

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative Name

Agile Six - Anthony M. Arashiro

### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Josh Mills

### Your Email

joshua.mills10@va.gov

### Team, Role, and Company of the target individual

Software Engineer, Public Websites, Front end, Agile6 (kind)

### Product Manager (PM) name and email

Wesley Rowe wesley.rowe@va.gov

### Product Owner (PO) name and email

Dave Conlon (david.conlon@va.gov)

### Desired AWS Access

Read and write access to the S3 bucket sitewide-public-websites-income-limits-data which is used to house data files needed for the new [Income Limits application](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/income-limits-app).

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

<img width="1131" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/61624970/4b18c243-a824-4f19-b9b3-ebb6e4ebecc4">

### Additional Notes

COR: [Keith.riley@va.gov](mailto:Keith.riley@va.gov)

ongoing access for coverage on updating s3 CSV data as required for income limits app

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by considerable** [comment]
VFS Team Roster

@jtmst - thank you for specifying the application you are working on. 
we just finished making terraform config for your app.
will move this tkt to the next steps upon the management's approval.

**Comment by flooose** [comment]
I've added your comment to the agenda for the next devops cop.
