### ISSUE TITLE
Manifest Repo PR Review Guide

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#58367]
Document how the values file correlates with the secrets file. How to ensure the PR is valid.  This will help developers understand how the helm files work. Slack thread [here](https://dsva.slack.com/archives/CBU0KDSB1/p1683904098334329).

**Comment by RachalCassity** [comment]
[External Secret Documentation](https://vfs.atlassian.net/wiki/spaces/TT1/pages/2633662753/External+Secrets)

**Comment by laineymajor** [comment]
This will be done tomorrow.
