### ISSUE TITLE
Publish Portal Page on Platform Site

### ISSUE THREAD

**Issue by twoangstroms** [department-of-veterans-affairs/va.gov-team#58366]
## Purpose
Publish the new portal page on Platform Doc site

## Tasks
- [x] Publish page to Support space in Confluence (follow instructions [here](https://vfs.atlassian.net/wiki/spaces/AP/pages/1474461889/Create+a+new+Platform+website+documentation+page)

## Acceptance Criteria
- [x] Verify that page can be accessed after Platform Content updates the site

**Comment by steel36** [comment]
@twoangstroms Hey, I saw this move to In Progress.  You're not planning to launch it yet, are you?

**Comment by twoangstroms** [comment]
No, I just wanted to get the background processes rolling so we’d be ready when we’re ready. For instance, I’m not sure the established Platform Content processes include putting a link/child page at https://depo-platform-documentation.scrollhelp.site/support/, so that’s something that needs to be checked.


Dan Turner

Sr. UX Designer II, Ad Hoc
***@***.***

￼
