### ISSUE TITLE
Design | Profile | Notification Settings | Edit as subtask | User Flow

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#58365]
## Background
Using the [sketch files for editing as a sub task, we need to create a user flow](https://www.sketch.com/s/1fd4d140-84ad-4301-9c74-d5cebc4a012d)

## Tasks
- [x] Use the sketch file to create a user flow 
- [x] Comment on the #57820 linking the flow notifying PM in order to add it to the collab cycle
  

## Validation
- Who can validate this ticket? PM/Design

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by andaleliz** [comment]
[User flow here](https://www.sketch.com/s/1fd4d140-84ad-4301-9c74-d5cebc4a012d/p/293F15EA-9CCC-466C-A3B7-3E54E3111676/canvas)
