### ISSUE TITLE
Test Results page - Authenticated users main content updates

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#5838]
**User Story**
As a user who is a patient at a Cerner facility and who is browsing the Test Results page on VA.gov after authenticating (logging in), I want the content on the page (above ad below the alert box) to give me the correct information about Cerner and/or MHV so that I am not confused about where my patient portal information is housed.

Note that authenticated users who are not patients at Cerner facilities should see the same content/UX as unauthenticated users (see #5744)

**Acceptance Criteria**
1. Content on Test Results page (above and below alert box) for authenticated Cerner patients displays the necessary Cerner-specific information
2. Content on Test Results page (above and below the alert box) for authenticated users who are not Cerner patients is the same as for unauthenticated users

**Tasks**
- [x] SSO-Login team: First pass at copy changes
- [x] VSP Content-IA team: Edit and validate
- [ ] SSO-Login team: Ensure frontend implementation

**Comment by bridgethapner** [comment]
@peggygannon Wireframe is here: https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/405218216.

- Everything I've changed from the unauthenticated page (#5744) is outlined with a pink box. There are comments in the Invision prototype that explain the changes I have made and why.
- All the updates made to the unauthenticated page should also be shown here. I've outlined those with a blue box to help clarify that.

Please let me know if you have any questions.

**Comment by AkucherGCIO** [comment]
02-24-20
Selina reviewing content and will send it to Peggy.

**Comment by lunascoop** [comment]
@peggygannon I have reviewed the test results page wireframe and made my edits in the attached document.
[Test results page.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4247526/Test.results.page.docx)

**Comment by peggygannon** [comment]
@bridgethapner Please see below for content recommendations for the AUTHENTICATED Test results page. These edits are also entered into the prototype: 

Intro edit:  You can view your VA lab and test results online with our lab and test tool. Find out if you’re eligible to use this tool and how to sign in to view your results.


 **How are My VA Health and My HealtheVet different?**

Where you receive care and the types of results you want to access will determine whether you’ll view your lab and test results on My VA Health or My HealtheVet. If you receive care at both Mann-Grandstaff VA medical center and another VA facility, you may need to use both web portals.

**If you receive care at Mann-Grandstaff VA medical center, you'll use My VA Health Labs and Vitals tool to:**
•	View some of your VA lab and test results (like blood tests, microbiology reports, pathology reports, radiology reports, and cardiology reports) from providers at Mann-Grandstaff VA medical center 

**If you receive care at another VA medical center, you'll use My HealtheVet Labs + Tests tool to:**
•	View your VA chemistry/hematology lab and test results (like blood tests, blood sugar, liver function, and blood cell count) from all other VA medical centers 
•	Add results from non-VA health care providers and labs 

**Can I view lab results from non-VA providers?**
No. Labs results from non-VA providers aren't listed in the tools. However, you can enter your own lab results from non-VA providers into MyHealtheVet.  


**Once I’m signed in, how do I view my results?**

**If you’re viewing results on My VA Health**,
In the navigation panel, click “Health Record.” Then choose “Labs and Vitals” to see a full list of available reports. This will take you to a new page with links to view test results.

If you’re signed in with a Premium account, you’ll see: 
VA test results listed by date and specimen. A specimen is the sample studied by the test (like blood, urine, a tissue biopsy, or a throat swab). You can click on each result to view details from your VA medical record.

**If you’re viewing results on My HealtheVet**
On your Welcome page dashboard, you’ll see a module for “Health Records.” Within that module, click on “Labs and Tests.” This will take you to a new page with links to view test results.

If you’re signed in with a Premium account, you’ll see:
- VA chemistry/hematology results listed by date and specimen. A specimen is the sample studied by the test (like blood, urine, a tissue biopsy, or a throat swab). You can click on each to view details from your VA medical record.
- Test results from non-VA providers that you’ve entered yourself**

**What if I have more questions?** 

**If you have questions about lab and test results on MyHealtheVet**, please go to the [Lab + Tests Results FAQs]( https://www.myhealth.va.gov/mhv-portal-web/web/myhealthevet/faqs#LabsandTests ) on the My HealtheVet web portal. 
Or contact the My HealtheVet help desk at 877-327-0022 (TTY: 800-877-8339). We’re here Monday through Friday, 7:00 a.m. to 7:00 p.m. CT.
You can also [contact us online] (https://www.myhealth.va.gov/mhv-portal-web/web/myhealthevet/contact-mhv\)

**If you have questions about lab and test results on My VA Health**, you can call the My VA Health help desk at xxx-xxx-xxxx (TTY). We’re here Monday through Friday, 7:00 a.m. to 7:00 p.m. CT. You can also [contact us online].

**Comment by AkucherGCIO** [comment]
03/04/20 PW Standup
@lunascoop has completed her portion of this effort.  Please let us know if anything else is needed.

**Comment by bridgethapner** [comment]
Hi @AkucherGCIO @lunascoop @peggygannon - thank you for the content updates. Can you provide guidance on how to handle the **Can I view all my VA lab and test information using these tools?** section of the page? I think the section doesn't feel necessary given the content edits for **How are My VA Health and My HealtheVet different?** - would you recommend removing for the AUTH page?

**Comment by AkucherGCIO** [comment]
@peggygannon @lunascoop - Please address the questions above from @bridgethapner.

**Comment by lunascoop** [comment]
@bridgethapner I think that the **Can I view all my VA lab and test information using these tools?** of the page is unnecessary.

**Comment by bridgethapner** [comment]
Thank you @lunascoop, I will remove.

**Comment by FranECross** [comment]
Ticket is old and outdated. Closing.
