### ISSUE TITLE
Midpoint Review - Design Feedback - Benefits Disability Experience Team, Disability Comp Application (21-526EZ), 526 Intro Pages

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#58382]
## VFS actions
- [x] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [x] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [x] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [x] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- Love the user flows!
- If you try the accordions please fill out an [experimental design ticket](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- **Must**: Follow the [intro template](https://design.va.gov/templates/forms/introduction) guidance for sign in UI.
  - Remove the blue background from the sign in button. Replace button text with “Sign in to start your application”
  - <img width="381" alt="Screen Shot 2023-05-12 at 2 43 08 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/72398073/2ce75a4c-a82c-42ff-860d-e3cf91ce63d7">
  - Work with content on the sign in info alert at the bottom of the page. We do have [guidance](https://design.va.gov/templates/forms/introduction#save-work-in-progress-alert) around content, if your needs are different work with content.
- **Must**:Take a look at your alert styling on all the pages. If there is a negative consequence then ‘[warning alerts](https://design.va.gov/components/alert-expandable#choosing-between-variations) are ok to use. We have noticed a lot of alert fatigue so if possible drop the alert style. Strongly consider using [additional info components](https://design.va.gov/components/additional-info) (no border if inside the process list) if the content does not warrant an alert.
- **Must**: Per our [guidance](https://design.va.gov/components/alert#how-to-use-alerts) do not stack alerts. Typically [default alerts](https://design.va.gov/components/alert#placement) are placed near the top of the page.

**Comment by lydiahooper** [comment]
@allison0034 We will certainly continue to work with Beth/content. Per one of the musts you listed, I'd like to avoid having both a PACT Act alert and Sign in alert stacked at the top of the page. Perhaps I could've asked this in the call: Is there a process for me to get approval to depart from the template, so we can keep the PACT Act one there instead? It occurred to me that there is already a "Sign In" button in the top menu anyhow!

**Comment by allison0034** [comment]
@lydiahooper since the PACT Act alert is important, I think it is fine to leave that at the top of the page. Just remove the light blue background from behind sign in. Basically if you look at our [intro page layout](https://design.va.gov/templates/forms/introduction), you are flipping the sign in alert and the plain sign in button without the alert. Does that make sense?

**Comment by lydiahooper** [comment]
Will address must feedback per Allison's last comment and continue to work with content. Note we are changing content/designs so alerts will not be stacked.
