### ISSUE TITLE
Midpoint Review - Accessibility Feedback - Benefits Disability Experience Team, Disability Comp Application (21-526EZ), 526 Intro Pages

### ISSUE THREAD

**Issue by briandeconinck** [department-of-veterans-affairs/va.gov-team#58381]
## VFS actions
- [x] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [x] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [x] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [x] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [x] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- Really like the user flow change here, and I'm excited to see it move forward!

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- **Must:** Small content thing. In the [process flow](https://www.sketch.com/s/0fa92d93-0841-4c62-8112-c9c528204092/a/71pnPqE) step 2, the "Here is a list" link text doesn't clearly explain where the link is going without the context of the paragraph around it. For screen reader users jumping from link to link or having their computer announce a list of all links on the page, they may hear "Here is a list" without that supporting context. Adjust the text of that link, or remove that sentence altogether and link the "accredited veterans services officer (VSO)" text instead.
- **Should:** For [active-duty users entering their service end date](https://www.sketch.com/s/0fa92d93-0841-4c62-8112-c9c528204092/a/P1mxwOL), the current prototype has the blue info alert appearing dynamically based on what date is entered. If possible, this should be its own separate page following the "one thing per page" ethos, ie. user selects date, clicks Continue, gets a page with that text. That avoids having to do some extra work for assistive technology support with the conditional display of the alert -- and may also solve that stacked alert issue that Allison raised in her feedback.
   - **Conditional Must:** If it's not possible or desirable to move that info alert to its own page, make sure everyone on the team is aware of the relevant guidance around this pattern (and please reach out if there are any questions!):
      - [Retrofit this pattern section](https://design.va.gov/patterns/wizards#retrofit-this-pattern) on the Design System page about wizards
      - [Accessibility implementation notes](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-getting-started-with-the-forms-li#VAFormsLibrary-GettingStartedwiththeFormsLibrary-Conditionallydisplayedfields) for developers  around conditionally-displayed fields

**Comment by lydiahooper** [comment]
I amended the content per the "must", and moved the info that was in the blue alert to a new separate page per the "should". Thanks!
