### ISSUE TITLE
[Design and Research] Onboarding Pam Drouin to Authenticated Experience

### ISSUE THREAD

**Issue by BerniXiongA6** [department-of-veterans-affairs/va.gov-team#58388]
## Background

Welcome Pam! We can use this ticket to track onboarding to the Authenticated Experience team.

### Intro to Authenticated Experience team members

Please schedule a short chat with each of these folks. You can schedule individual chats or talk to people in groups if you think that makes sense:

- [x] Chante Lantos-Swett (interim Product Lead backfilling Samara - from OCTO) 
- [x] Travis Cahill (Profile Product Manager)
- [x] AJ Jakabcin (My VA Product Manager)
- [x] Liz Lantz, Angela Agosto (Designers / Researchers)
- [x] Adam Whitlock, and Allison Lu (Frontend developers)
- [x] Tom Harrison, and Derrick Ellerbie (Backend/Full stack developers)

### Review documentation

Here are some helpful documents to review on the profile. It would also help if you log into staging and check it out for yourself to get a sense of the full section.

- [x] [Profile product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/README.md)
- [x] [2023 goals and roadmap](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/authenticated-experience/roadmap/2023-goals-roadmap.md#profile-team)
- [x] [Personalization and profile comparative analysis](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/discovery-research/comparative-analysis/personalization-profile-comparative-analytsis.pdf)

#### Profile products

- [x] [Personal information product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/personal-information#readme)
- [x] [Contact information product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/contact-information#readme)
- [x] [Military information](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/military-information#readme)
- [x] [Direct deposit product outline](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/direct-deposit/README.md)
- [x] [Notification preferences product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/notifications/notification-preferences#readme)
- [x] [Account security](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/account-security#readme)
- [x] [Connected apps](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/connected-apps/README.md)

### Check out the VA.gov Profile in Staging environment
- [x] Log into staging and check out the profile. You can use the following info to get into staging:

Go to VA.gov.
- You can sign into staging with most ([staging users](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv)) to view the profile. Feel free to pick any user, but if you want a specific user, try user 81. **Please do not edit or update their profile, however**.
- Once you are logged in click the menu that has the user's name in the upper right of the navigation. You'll see a link to the profile in the menu.

### Optional -- VA.gov Profile Demo

- [x] If it would be helpful, one of the profile team members can walk you through how each feature works.

**Comment by BerniXiongA6** [comment]
Pam Drouin's GitHub handle: @pamela-drouin

**Comment by pamela-drouin** [comment]
@BerniXiongA6 I've started working on this, and will update the ticket once I have access to Github.

**Comment by pamela-drouin** [comment]
@BerniXiongA6 I've been able to access all the links, except this one: products/identity-personalization/notifications/notification-preferences

I get a `404 - page not found The master branch of va.gov-team does not contain the path 
products/identity-personalization/notifications/notification-preferences.`

Does it exist? I do have access now to the sensitive Direct Deposit Product Outline.

**Comment by BerniXiongA6** [comment]
Hi @pamela-drouin -- I'm pretty sure the page was moved. I think it's this now: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/notification-preferences/README.md

**Comment by pamela-drouin** [comment]
Just scheduled my final team chat! Closing this issue 😄
