### ISSUE TITLE
Scheduling page - Authenticated users main content updates

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#5839]
**User Story**
As a user who is a patient at a Cerner facility and who is browsing the Scheduling page on VA.gov after authenticating (logging in), I want the content on the page (above ad below the alert box) to give me the correct information about Cerner and/or MHV so that I am not confused about where my patient portal information is housed.

Note that authenticated users who are not patients at Cerner facilities should see the same content/UX as unauthenticated users (see #5745)

**Acceptance Criteria**
1. Content on Scheduling page (above and below alert box) for authenticated Cerner patients displays the necessary Cerner-specific information
2. Content on Scheduling page (above and below the alert box) for authenticated users who are not Cerner patients is the same as for unauthenticated users

**Tasks**
- [x] SSO-Login team: First pass at copy changes
- [x] VSP Content-IA team: Edit and validate
- [ ] SSO-Login team: Ensure frontend implementation

**Comment by bridgethapner** [comment]
@peggygannon Wireframe is here: https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/404881778.

I don't believe any updates are needed to the unauthenticated version of this page. Everything I've changed is outlined with a pink box. The updates are:
- Changing one section title
- Updating the help section. (Note: we're still awaiting My VA Health Help Desk information)

Please let me know if you have any questions.

**Comment by peggygannon** [comment]
Hi, @bridgethapner I have just one content recommendation for this page. (comment posted in the mockup)

**Comment by bridgethapner** [comment]
Thank you @peggygannon I made the update you noted to the breadcrumb. 

I also took a look and changed a couple more things, [the updated wireframe is here](https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/404881778). All areas that need content review are labeled. 

**Summary of changes:** 
- Changed "Can I use this tool to schedule non-VA appointments?" to "Can I use these tools to schedule non-VA appointments?"
- Edited "What if I have more questions?" to be consistent with the edits you suggested on other pages.

I have a question I am capturing here for near future discussion with Lauren:
- I see that changes to the Scheduling page have been made to say that non-VA appointments can be scheduled with VAOS. Can non-VA appointments be scheduled with My VA Health?

**Comment by bridgethapner** [comment]
## Summary of Content Changes
Content changes are outlined in pink in [the wireframe](https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/404881778).

#### Content Change 1
**With VA Online Scheduling you can:** 
- Schedule some of your VA medical appointments online
- Reschedule and cancel appointments made online
- View appointments on your health calendar
- Find the location of the VA facility for your appointments
- Set up email reminders for upcoming appointments
- Print a list of your future appointments
- Look up past appointments from the last 2 years
- Add non-VA appointments to your health calendar

**With My VA Health you can:**
- Schedule some of your VA medical appointments online
- Cancel appointments made online
- View appointments on your health calendar
- Find the location of the VA facility for your appointments
- Print a list of your future appointments

### Content Change 2

**What if I have more questions?**
**If you have questions about appointment scheduling on VA Online Scheduling**, please go to the [VA Appointments FAQs](https://www.myhealth.va.gov/mhv-portal-web/faqs#Appointments) on the My HealtheVet web portal.

Or contact the My HealtheVet help desk at 877-327-0022 (TTY: 800-877-8339). We’re here Monday through Friday, 7:00 a.m. to 7:00 p.m. CT.

You can also [contact us online](https://www.myhealth.va.gov/mhv-portal-web/web/myhealthevet/contact-mhv).

**If you have questions about appointment scheduling on My VA Health**, you can call the My VA Health help desk at xxx-xxx-xxxx (TTY). We’re here Monday through Friday, 7:00 a.m. to 7:00 p.m. CT. You can also contact us online.

**Comment by peggygannon** [comment]
Hello, @bridgethapner Here is my content feedback. I also left feedback in the mockup. thank you! 

Updates to first content block: 

Change *With VA Online Scheduling you can:** TO

**With the VA appointments tool you can:** 

Remove last bullet in that list: Add non-VA to your health calendar

**With My VA Health you can:**

------

2nd content block: 
I have a question, about the first line pointing user to MHV FAQs

This line points user to MHV FAQs, which we don't want to do anymore once VAOS launches. (assuming VAOS is launching just ahead of the Columbus Cerner launch). 

I will chat with VAOS team about about where to point users to if they have questions/FAQ about the new VAOS tool. 


In the meantime, let's rewrite this first line to: 
**If you have a question about scheduling an appointment on the VA appointments tool,**

**Comment by peggygannon** [comment]
@bridgethapner 

Per our 4/2 content sync, we'll update the **Authenticated**Schedule and View page with the following: 

1. rewrite header and first sentence to:
**How can these appointment tools help me manage my health care?**
These appointment tools offer a secure, online way...... 

2, update bullets points under that header to make them more general. 

**You can use these tools to:**

Schedule some of your VA medical appointments online
Cancel appointments made online
View appointments on your health calendar
Find the location of the VA facility for your appointments
Print a list of your future appointments

3. Under "What if I have more questions?"
We'll leave this copy about VA appointments tool, as is (since the tool is called the"VA appointments" tool on MHV and VA.gov). 

4. Cerner help info tk.

**Comment by bridgethapner** [comment]
Thank you @peggygannon! 

@hinzed1127 The content is mostly done, [the wireframe is here](https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/404881778_-5839-Scheduling-Auth). However, we are still awaiting the Cerner Help desk link. 

In addition to the 3 changes from #5745 carrying over here, there is just one more change. 

## Content Change 1
To the bottom of **What if I have more questions?** section, please add the following:

If you have questions about appointment scheduling on My VA Health, you can call the My VA Health help desk at 1-800-962-1024. You can also [contact us online].

**Comment by FranECross** [comment]
Ticket is old and outdated. Closing.
