### ISSUE TITLE
List print view improvements

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#58393]
## Task Description
Improve the information shown on the print view for all appt lists:
- Display page headings
- Include Appts "Need Help?" footer

This does **not** include changes to layout, or adding data to print view that doesn't exist in web view.

## References
- [TBD - Product initiative brief]()

## Acceptance Criteria
- [x] [Design Spec](https://www.figma.com/file/sI4udk4AmnACHGj62PdPx7/List-print-view-improvements?type=design&node-id=1212%3A35&t=oIBgVLRxdwxOkqOw-1)

**Comment by outerpress** [comment]
Dev ticket: #59732

**Comment by Cieramaddox** [comment]
Design work here is finished and this ticket is ready to close out.
