### ISSUE TITLE
Directions uses search parameters

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#5840]
## User Story or Problem Statement
As a Veteran, I want the directions to the facility to be based on my search so that I do not have to re-enter the values into Google maps. 
**Example use cases:**
I want to find a facility close to my work location (rather than to my home). 
I am planning for a visit when I will be in a different area than my current location. 

![image](https://user-images.githubusercontent.com/55411834/74387551-b172e780-4dad-11ea-9f4e-bae2c3eaa151.png)

![image](https://user-images.githubusercontent.com/55411834/74387724-2cd49900-4dae-11ea-91fa-2d364da28c6e.png)

## Goal
-Directions should reflect the user's search parameters

## Objectives or Key Results this is meant to further
- Improve the Veteran experience

## Acceptance Criteria
- [ ] When a user clicks _Directions_ from the result list, the parameters entered in _Search by city, state or postal Code_ are reflected in Google maps. 
[ ] When user enters geographic search parameters which are different than his current location, the directions are based on the parameters entered. 
[ ] When user has enabled browser location, **_(what is expected result here)_**?
[ ] When user clicks  _Directions_ from facility detail page **_(what is expected result here)_**?

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
@arickalewis1 @davidconlon 
What is expected behavior when...

1. user has enabled browser location?
2. user clicks  _Directions_ from facility detail page?

**Comment by arickalewis1** [comment]
@mmiddaugh my assumptions are that 

1. The location identified would populate in google maps
2. Google maps could use their current location or they could input a location.
