### ISSUE TITLE
Qualitative Data Request

### ISSUE THREAD

**Issue by elizabethkochBT** [department-of-veterans-affairs/va.gov-team#58409]
### Data Type Requested

Support

### Date Range Start

1/1/2023

### Date Range End

05/14/2023

### Product Name(s)

Login.gov Adoption

### Product Description

The Login.gov adoption team aims to streamline the sign-in process on VA.gov by offering Login.gov as a preferred credential option while phasing out duplicative and non-compliant legacy credentials. 

### Product URL(s) and/or term(s)

We are looking for information on Login.gov contact center cases to identify trends in issues submitted by Veterans. This includes both quantitative and qualitative data on cases related to login. 
For example:
1. Quantitative - we would like to access any issue reports broken down by topic/subtopic within Login.gov to identify any trends / pain points.
2. Qualitative - comments/free text submissions that we can parse to identify trends / clustering.

### File Delivery Format

All in one file, on one tab

### VA Email Address(es)

elizabeth.koch4@va.gov, anthony.decanini@va.gov, michael.antiporta@va.gov

### Add Assignee and Labels

If not already done so, please ensure @ianMcCullough-ob is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by ianMcCullough-ob** [comment]
@elizabethkochBT sounds great! Thanks for the clarification.

**Comment by porta-antiporta** [comment]
@ianMcCullough-ob Thx for the clarification. The case notes would be fine. It's not that we're looking for specific terms in the case notes; it's more parsing through the case notes to see if there are trends we see. (i.e. We don't know what we don't know). 

Looking at the volume from @elizabethkochBT screenshot, to limit the size of the export, case notes could be limited to the last 2 weeks of cases related to Login.gov.

**Comment by ianMcCullough-ob** [comment]
Good morning @elizabethkochBT and @porta-antiporta, I just shared an export with the above emails. It's an export of VA411 Technical Support issues with the categories and types you mentioned from the last 2 weeks. Feel free to reach out on Slack or on here if you have any questions.

**Comment by porta-antiporta** [comment]
tyvm @ianMcCullough-ob!

**Comment by ianMcCullough-ob** [comment]
Hello @elizabethkochBT and @porta-antiporta! Just wanted to reach out and see if I can close this ticket. Let me know if you need anything else. Thanks!
