### ISSUE TITLE
Troubleshoot Sentry errors

### ISSUE THREAD

**Issue by rsmithadhoc** [department-of-veterans-affairs/va.gov-team#58423]
## Description

A [support request](https://dsva.slack.com/archives/CBU0KDSB1/p1684164801781429) mentions new errors in Sentry that should be looked into.

- [13 blocked `style`](http://sentry.vfs.va.gov/organizations/vsp/discover/results/?end=2023-05-16T04%3A59%3A59.000&field=message&name=Supplemental+Claims&project=4&query=url%3Ahttps%3A%2F%2Fwww.va.gov%2Fdecision-reviews%2Fsupplemental-claim%2Ffile-supplemental-claim-form-20-0995%2F%2A+level%3Aerror+message%3A%22Blocked+%27style%27+from+%27data%3A%27+style-src-elem%22&sort=-message&start=2023-05-08T13%3A00%3A00.000&widths=-1)
- 6 blocked `connect` from region1.google-analytics.com ([4 here](http://sentry.vfs.va.gov/organizations/vsp/discover/results/?end=2023-05-16T04%3A59%3A59.000&field=message&name=Supplemental+Claims&project=4&query=url%3Ahttps%3A%2F%2Fwww.va.gov%2Fdecision-reviews%2Fsupplemental-claim%2Ffile-supplemental-claim-form-20-0995%2F%2A+level%3Aerror+message%3A%22Blocked+%27connect%27+from+%27region1.google-analytics.com%27+%5BFiltered%5D%3A+connect-src%22&sort=-message&start=2023-05-08T13%3A00%3A00.000&widths=-1) & [2 here](http://sentry.vfs.va.gov/organizations/vsp/discover/results/?end=2023-05-16T04%3A59%3A59.000&field=message&name=Supplemental+Claims&project=4&query=url%3Ahttps%3A%2F%2Fwww.va.gov%2Fdecision-reviews%2Fsupplemental-claim%2Ffile-supplemental-claim-form-20-0995%2F%2A+level%3Aerror+message%3A%22Blocked+%27connect%27+from+%27region1.google-analytics.com%27+connect-src%22&sort=-message&start=2023-05-08T13%3A00%3A00.000&widths=-1))
- [1 unexpected token](http://sentry.vfs.va.gov/organizations/vsp/discover/platform-web:2237871f106b414f9ef2c2a10dedd4d5/?end=2023-05-16T04%3A59%3A59.000&field=message&name=Supplemental+Claims&project=4&query=url%3Ahttps%3A%2F%2Fwww.va.gov%2Fdecision-reviews%2Fsupplemental-claim%2Ffile-supplemental-claim-form-20-0995%2F%2A+level%3Aerror+message%3A%22Unexpected+token+%27%3C%27%2C+%5C%22%3C%21DOCTYPE+%5C%22...+is+not+valid+JSON+SyntaxError+https%3A%2F%2Fwww.va.gov%2Fdecision-reviews%2Fsupplemental-claim%2Ffile-supplemental-claim-form-20-0995%2Fadd-issue%22&sort=-message&start=2023-05-08T13%3A00%3A00.000&widths=-1) `<`, `<!DOCTYPE` (related to #search-header-dropdown-input-field)
- 1 [Blocked unsafe inline 'script'](http://sentry.vfs.va.gov/organizations/vsp/discover/platform-web:0533fa0c8c1d4744bf6447de21590600/?field=message&name=Supplemental+Claims&project=4&query=url%3Ahttps%3A%2F%2Fwww.va.gov%2Fdecision-reviews%2Fsupplemental-claim%2Ffile-supplemental-claim-form-20-0995%2F%2A+level%3Aerror+message%3A%22Blocked+unsafe+inline+%27script%27+%27self%27+script-src+script-src+%27self%27+%27unsafe-inline%27+%27nonce-mhkZeHFnEIxtlt9IefZHH5HGhAaXNops%27+http%3A%2F%2Fwww.google-analytics.com+https%3A%2F%2F%2A.uservoice.com+https%3A%2F%2Fdap.digitalgov.gov+https%3A%2F%2Fdesignsystem.digital.gov+https%3A...%22&sort=-message&statsPeriod=14d&widths=-1)

**Comment by CBonade** [comment]
Front end COP members do not have access to see these in Sentry - need to pursue a route to be able to diagnose this further.

**Comment by CBonade** [comment]
On attempting to get some more details into this, it would appear many of these Sentry errors are no longer available in the console. Going to close this out and we can readdress if these errors crop back up in the future.
