### ISSUE TITLE
[Datadog] Create APP and API Key attached to Platform Service Account

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#58429]
# Description
Platform was using user created app keys, which inherit the privileges of the owner. When said owners leave the company and/or project, things begin to break. Create new API and APP keys associated with the "Platform" service account in Datadog.

# A/C
- [x] API Key is created and owned by the Platform service account
- [x] APP Key is created and owned by the Platform service account
- [x] API Key is updated in parameter store `/dsva-vagov/datadog-gov/common/API_KEY`
- [x] APP key is updated in parameter store `/dsva-vagov/datadog-gov/common/APP_KEY`

**Comment by rmtolmach** [comment]
I confirmed `terraform` commands in the datadog environment are working.

This was the error we were seeing before this fix.
```
│ Error: error getting monitor from https://api.ddog-gov.com/api/v1/monitor/88881: 403 Forbidden: {"errors":["Forbidden"]}
│ 
│   with module.datadog_monitors.datadog_monitor.default["haproxy-appeals-staging"],
│   on .terraform/modules/datadog_monitors/main.tf line 6, in resource "datadog_monitor" "default":
│    6: resource "datadog_monitor" "default" {
```
