### ISSUE TITLE
Migrate MFS clinics search call over to vaos service

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#58434]
## Description
We currently call the MFS clinic endpoint: `/facilities/v2/facilities/?/clinics/` to search clinics by id and display clinic data in the appointment response. We want to migrate the call over the vaos service clinic call: `/vaos/v1/locations/?/clinics`.

## Acceptance Criteria
- [ ] All clinic calls are made through vaos service.

**Comment by ldelacosta** [comment]
There's a feature toggle that we will need to validate the changes for this ticket. [See ticket 58719](https://github.com/department-of-veterans-affairs/va.gov-team/issues/58719). 

Once the changes have been implemented, we will plan the testing activity and set a release date.

**Comment by ajmagdub** [comment]
It has been determined that a feature flag is unnecessary because the change is solely internal to the Vets API and does not require any modifications to Vets Web.
