### ISSUE TITLE
Update PDFs for the EZ and EZ-R forms on health care pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#5843]
## User Story or Problem Statement
As a Veteran, I need to be able to use online forms so I can apply for health care or update my information.

Both the 1010-EZ and 10-10EZ-R forms had been revised but not updated in the forms database, causing broken links on several pages. 

## Goal
Working PDFs on pages where there were previously broken links.

## Objectives or Key Results this is meant to further
As a temporary fix, we need to update the PDFs to revised versions and initiate a content-only deploy in Drupal. Once the forms are fixed in the database we need to update to the correct permanent PDFs and issue another content-only deploy.

Temporary PDFs to use: 
- 10-10EZ: https://www.va.gov/vaforms/medical/pdf/10-10EZ_revised_Jan%2024%202020.pdf
- 10-10EZR: https://www.va.gov/vaforms/medical/pdf/10-10EZR_revised_Jan%2024%202020.pdf

New PDFS to use:
- 10-10EZ: https://www.va.gov/vaforms/medical/pdf/10-10EZ-fillable.pdf
- 10-10EZR: https://www.va.gov/vaforms/medical/pdf/vha-10-10ezrfill.pdf

Update these on the following pages:
- https://www.va.gov/health-care/after-you-apply/
- https://www.va.gov/health-care/how-to-apply/
- https://www.va.gov/health-care/update-health-information/

## Acceptance Criteria
- [x] Update pages with temporary revised URLS
- [x] Issue content-only deploy and confirm working on site
- [x] Update pages with new correct PDFs from forms database
- [x] Issue content-only deploy and confirm working on site

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
This work has been validated on live site. Closing issue. FYI @MickinSahni

**Comment by MickinSahni** [comment]
@MickinSahni add to sprint report as unplanned
