### ISSUE TITLE
GIDS: Update % Match to use custom formula

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#5845]
As an EDU Team Member, I need the % match to better reflect how closely the IPEDS data matches the WEAMS data so I can make a better decision about how to update the crosswalk.

## Assumptions:
1. Before creating a pull request; evaluate the match list to determine if we need to tweak the match formula and or logic.

## Acceptance Criteria
1. The % Match formula is calculated the following way:  (% name match + max%(physical address match OR mailing address match)) / 2
     - ex. 100% name, 100% physical address, 20% mailing address = 100%
2. There is a 100% match on the state value of either address (mailing or physical) to be included in potential match list.

## Supporting Artifacts:
1. N/A

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/592

Can be tested on gibct-data-service branch `crosswalk-issue-rating`

**Comment by delli-gatti-michael** [comment]
Tested by Test Case:
https://dsvavsp.testrail.io/index.php?/cases/view/305

**Comment by delli-gatti-michael** [comment]
Functionality is now present in Staging. Closing this issue
