### ISSUE TITLE
SPIKE: Identify CHIP API Changes Needed to Accommodate the Bare-Boned MVP Scenario

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#58451]
Will most likely need to roll this over.

## Mobile Team Info
[API Docs](https://department-of-veterans-affairs.github.io/va-mobile-app/api/#operation/getAppointments)

## User Story
As a team, we need to support the native mobile app's feature to allow a Veteran to check-in for an appointment from the app on their mobile device.

## Reference
[Native Mobile App MVP](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/patient-check-in/Requirements/2023.04.25%20Mobile%20app_Patient%20Check%20In%20MVP.pdf)

[Current engineering notes](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/engineering/full-auth-check-in)

## Use Case 1: Ask if a patient can check-in for 1 or more appointments
- Given I
    - Am a Veteran using the VA's native mobile app
- When I
   - Open the Mobile app on my phone
- Then
   - Mobile app sends Patient ID, Appointment ID, Appointment Type to find out if they can check in
   - API returns Yes/No if they can check in (for each appointment)
        - If no, code for the specific reason why not                  
             - Needs to review insurance 
             - Needs to review demographics 
             - Needs to review emergency contact 
             - Needs to review next-of-kin 
             - Not an in-person appointment
             - Facility is not enabled for check-in
             - Veteran has already checked-in
             - NOTE: control of the check-in window will happen on the Mobile App side

## Use Case 2: Request to check-in a patient for an appointment
- Given I
    - Am a Veteran using the VA's native mobile app
    - Am presented with the option to check-in for one of my appointments
- When I
   - Choose to check-in for my appointment
- Then
   - The native mobile app tells the CHIP API to check-in a specified Veteran for a specified appointment
   - The CHIP API performs the check-in and responds to the native mobile app with success or failure message

## Use Case 3: Update 1 or more flags for a patient
- Given I
    - Am a Veteran using the VA's native mobile app
    - Am presented with the option to verify one or more of my contact information
- When I
   - Complete the verification workflow
- Then
   - The native mobile app tells the CHIP API to update 1 or more flags (insurance & contact) for a specified Veteran
   - The CHIP API performs the update of the flags

## AC
- [ ] Determine changes needed to provide the Mobile app the status information for the Veteran and their appointments for today
- [ ] Determine changes needed to update the flags for a Veteran
- [ ] Determine changes needed to check-in a Veteran
- [ ] Develop sequence diagrams of to the interactions between the Mobile App, vets-api, & CHIP API, etc.
- [ ] Create engineering tickets necessary to perform the necessary changes

**Comment by stephenBarrs** [comment]
We need to determine what information is already returned in the existing Appointment payload used by Mobile App.  Can we inject relevant data into that response so an additional call is not required to determine check in eligibility?  Or if at least the `e-checkin-allowed` flag is included in the initial payload, Mobile App may only need to make calls for eligibility for appointments at enabled clinics (which would reduce the number of calls required).   
@brianseek @wullaski there was a mention about assuming all appointments are `check-in-able` so Mobile App would not need to make an eligibility call for every appointment; it seems like this would take the Veteran down a dead end path.  If you are thinking of this differently can you describe that?  Thanks!

**Comment by wullaski** [comment]
@stephenBarrs in @brianseek's absence I don't know that I can properly defend the idea of all appointments being check-in-able. That said, I do agree that it would lead to a dead end in some cases. If it was a quick dead end it might not be bad but in my opinion should probably be avoided by getting as much data ahead of time that is possible.

Getting `e-checkin-allowed` would be very helpful! Another thing that would be easy to determine and prevent dead ends is the 45 minute window. The app could probably do that without any extra data. Those two things would probably avoid most dead ends I think. Then if the veteran clicks the check in button we could check if demographics and insurance are up to date, possibly route them through screens to confirm, and check the veteran in.

I think the ideal solution would be to get all the data you need with the list of appointments show the button if it's eligible and check the veteran in on click.

**Comment by anita-halici** [comment]
To do:  
- sync with Shane ( Vista api) to figure out the what is needed to check in for the appointment with Vista API on mobile.
- Research: CHIP API WHAT VISTA API ENDPOINTS ARE called and what data is being passed to Vista API

**Comment by loripusey** [comment]
@brianseek @wullaski @randomsync @kanchanasuriya We need to create some engineering tickets before planning today; closing this spike ticket, we should move into design & implementation phase now
cc: @anita-halici

**Comment by randomsync** [comment]
created 2 tickets for designing the solution. we'll add more details as we go:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/59385
https://github.com/department-of-veterans-affairs/va.gov-team/issues/59387
