### ISSUE TITLE
Test in Production

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#58452]
## Description
Per the [release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/release-plan/check-in-travel-release-plan.md), we need to test this feature in production.

## AC
- DONE - Get Production API keys (Mark has asked) & determine if we can test in production (ask Mark)
- DONE - Get Production VA Notify templates (Mark has asked)
- DONE - Update the code to include the production API keys & ID for production templates
- Add Wilkes-Barre station code to the application (station & clinic as dictated by Stephen and/or Robert Tow)
- Test in production using Robert Tow's account 
    - Update the allow list to include Wilkes-Barre
        -  Our filter works with parent station number and clinic IEN. If we are going to not do all of Wilkes-Barre, we will need to add all of the individual clinicIENs to the list. Or we could update the filter to look at `sta6a` but I am not too keen on a code change this close to the pilot and prod testing.
    - We need for Robert to have a single appointment for the testing day/time in production at a Wilkes-Barre clinic
    - We need Robert Tow to have a BTSSS account in production (or do we?)
    - Schedule the test for after hours (ET) at 693 station code

**Comment by loripusey** [comment]
@mdewey Have we heard back about getting API keys for production or getting the VA Notify templates created in production?
cc @randomsync @kanchanasuriya

**Comment by brianseek** [comment]
@loripusey moving this to closed since this was successfully validated on prod
