### ISSUE TITLE
My VA Treating Facilities field - discovery/research

### ISSUE THREAD

**Issue by LynneJohnson224** [department-of-veterans-affairs/va.gov-team#58460]
Research the My VA treating facilities field - deciding if we bring over and where to put it if we do.

![image.png](https://images.zenhubusercontent.com/629a1db0e70457da479e69ae/165ace5c-2d48-45be-a3d3-66df221d379c)

[Link to Github doc with notes from conversations on this topic](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/preferences/My-VA-Treating-Facilities.md)

- [ ] How does this field impact a user's experience - ensure we have a full understanding
  - [ ] Potential demo from NP team on this field to understand the use of the field.
  - [x] What problem was this field trying to solve?
- [x] Is the field useful for users? Background: Currently, this field can help limit the facilities a user sees (ex. Cerner facilities can be DoD or VA), which can then help ensure messages are sent to the right doctor.
- [ ] Is this field currently used by users?
- [ ] Where does the data go when field changed in NP - is it only stored or accessed by other systems?

**NOTE: If the outcome of this ticket is that the Treating Facilities field will not be retained, #58846 should be closed as unnecessary.**

### Acceptance Criteria:

- MHV NP team - slacks/discuss field, including potential demo 
- Document findings (is the field useful, how does the field impact a user's experience, is the field being used, where is the data stored, is the data accessed by other systems?) in ticket

### Dependencies:
MHV NP team - are they able to answer these questions? 
Potential dependency on other teams (analytics)

**Comment by batemapf** [comment]
some random thoughts on the topic:

<img width="1425" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/7645362/b7aa96dd-3f31-4303-80b4-1d256893ef47">

**Comment by fmccaf1** [comment]
Thanks for posting this conversation @batemapf. One question I have: what would be impacted by a list that allows users to mark that they no longer receive care at a facility? When Coutlon says "that would be helpful for a variety of things," I'm wondering what those things are.

**Comment by fmccaf1** [comment]
![image.png](https://images.zenhubusercontent.com/629a1db0e70457da479e69ae/aa12feb6-0a0e-4428-b396-9d747c9795e4)

[link to thread ^](https://dsva.slack.com/archives/C04DRS3L9NV/p1685118852895439)

**Comment by fmccaf1** [comment]
Patrick wrote to Carnetta Scruggs 6/2/23 requesting any info she might have on the field

**Comment by fmccaf1** [comment]
Set up meeting with myself and Carnetta on Wednesday, June 14.

**Comment by fmccaf1** [comment]
[Notes from call with Carnetta.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/preferences/My-VA-Treating-Facilities.md)

Need to know: Helpdesk uses data from the field to determine the correct VAMC to transfer Veteran caller to

**Comment by fmccaf1** [comment]
Scheduled call with Patty Henry for today, June 21.

**Comment by fmccaf1** [comment]
[Notes from call with Patty Henry today.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/preferences/My-VA-Treating-Facilities.md)

Next steps:
- [ ] Set up call with Patty and Nicole Ortego

**Comment by fmccaf1** [comment]
Scheduled call with Patty Henry and Nicole Ortego for July 13 at 3:30.

**Comment by fmccaf1** [comment]
I had scheduled a call with Patty Henry and Nicole Ortega for last week on Thursday, at 3 central. Both marked that they would be attending, but neither showed up to the meeting. 

Instead of trying to reschedule, I sent the two of them an email from my VA.gov account. Here is the text of that email:

> Hi Patricia and Nicole,
> As Patty already knows, I work with Patrick Bateman on the new My Health section of VA.gov. I’ve been working for awhile now to understand the implications of potentially discontinuing the MyHealtheVet field called “My VA Treating Facilities.” This is a field that is chosen by the user, but the system populates the dropdown options based on what facilities have the user’s medical records (I believe coming from the JLV).
> From what I remember from our conversation awhile back, Patty, you thought this field may affect what is generated and downloaded in a user’s Blue Button report. Since our conversation, I’ve been in touch with the Medical Records Team for My Health and they let me know that, as far as they are aware, that field does not impact what is generated for the Blue Button report.
> I also had a conversation with Carnetta on this topic and she raised a concern that the field may play an important role in allowing the help desk to quickly and effectively assist callers who are encountering an issue while trying to use the health tools that have historically been on the MyHealtheVet site. Nicole, I’m wondering if you could speak to this concern, and how much of a risk it would be to deprecate the “My VA Treating Facilities” field from the help desk’s standpoint.
> Thank you both for your help.

**Comment by fmccaf1** [comment]
On Tuesday, July 18, Brenda Torres-Hill responded: Adding our leads to assist with your questions. 

That same day, I responded to Brenda, Nicole, Patty and the help desk leads (HRCCDMOHelpDeskTeamLeads@va.gov) the following:

> Thanks for your responses, Brenda and Nicole.

> To answer your question, Nicole: As part of the move over to VA.gov, multiple user-defined fields have been determined unnecessary for the new My Health section of VA.gov. We have yet to make a decision about this one field – My VA Treating Facilities – because we’ve been unable to get a clear answer to the question: What does this field impact? Right now, the only thing I am aware that it could impact is the help desk, in particular when staff are trying to identify a Veteran caller’s primary treating facility. I understand there are other ways to get this information, but I’d like input from help desk leaders before we move forward with a decision.

> **So to help desk Leads: Is the My VA Treating Facilities field (user-defined) essential to staff being able to effectively and quickly help Veterans? If so, why?**

**Comment by fmccaf1** [comment]
Okay, we are making moves finally! Today (Friday 7/21) I received emails from two Leads for the MHV help desk.

From Lameka Kendrick:
> From what we see, if can affect what they are able to see on the site. For instance, if they call and say “I cannot see my note from B facility”. We have them go check the treating facility and save the facility and then go back to the Notes in Blue Button and it will show up. Whether it is a glitch or actually makes a difference, we cannot tell but it has worked for us in several instances.

 


And from Katie Everett:
> As Lameka said, we mostly use it to help troubleshoot issues with Blur Button, but we also sometimes use it in troubleshooting Secure Messaging issues; for example, if a veteran has switched facilities and they are not seeing their new providers in their contact list we will have them select their preferred facility.

I responded back to both of them with the following questions:
1. As far as you know does the facilities field change anything else about the Blue Button report besides the Notes?
2. Are you aware of help desk staff using the facilities field for any other purposes?

**Comment by fmccaf1** [comment]
Received the following response from Katie Everett end of day Friday 7/21:

> As far as I know, it doesn’t affect any other fields within Blue Button report, no. Also, I am not aware of any other purpose besides the ones mentioned that HD staff would use it to troubleshoot. The developers do want the veteran’s treating facility listed when we escalate issues with appointments displaying on MHV, but that’s not something we generally have the veteran check or use to troubleshoot with appointment issues.

**Comment by fmccaf1** [comment]
Shared finding about impact of field on BB report with Medical Records team in slack. [Here is a link to that conversation.](https://dsva.slack.com/archives/C03Q2UQL1AS/p1690221249179719)

**Comment by fmccaf1** [comment]
I asked Katie to provide more info about why add appointments to tickets to dev team and she suggested I reach out to Melissa Ashton. I did, and Melissa put me in touch with Lichelle Bain and Bresha Lipscomb. 

Today, 7/27, Lichelle responded to my email to say that she and Bresha need some time to ensure they have correct answers to the questions I sent them, which were the following: 

- How does the My VA Treating Facilities field impact what Veterans see within the Appointments tool?
- What are other ways that this field impacts the Veteran's experience?
- Is there any way to know for sure all of the ways this field can impact the Veteran's experience by looking at where this field's data is sent?

**Comment by fmccaf1** [comment]
On 8/3, Lichelle and Bresha got back to me, but only to introduce me to Carnetta Scruggs (who I have already spoken to on this topic).

When I wrote back that Carnetta and I had already spoken and asked to speak to developers who might know more about the field, Lichelle added Jason Boire, Sandeep Karuturi, and JB Walters to the emails.

Jason Boire, who I also have already spoken to about this field, wrote on 8/8 that I should speak with Haritha Cheruvu, Swathi Alikatti, and Sandeep Karuturi. I wrote to Haritha, Swathi and Sandeep on 8/8: 
> Due to a lack of knowledge about the My VA Treating Facilities field, teams working on the national portal to VA.gov transition are currently planning to omit the field in future iterations. It is therefore very important that, if this field impacts the users' experience, we understand exactly how. Is this something you can help with? 

JB Walters also responded (after I wrote that message) on 8/8, adding Arienne Walters, Bob Lewis, and Joel Calumpong to the thread.

**Comment by fmccaf1** [comment]
On 8/3, Lichelle and Bresha got back to me, but only to introduce me to Carnetta Scruggs (who I have already spoken to on this topic).

When I wrote back that Carnetta and I had already spoken and asked to speak to developers who might know more about the field, Lichelle added Jason Boire, Sandeep Karuturi, and JB Walters to the emails.

Jason Boire, who I also have already spoken to about this field, wrote on 8/8 that I should speak with Haritha Cheruvu, Swathi Alikatti, and Sandeep Karuturi. I wrote to Haritha, Swathi and Sandeep on 8/8: 
> Due to a lack of knowledge about the My VA Treating Facilities field, teams working on the national portal to VA.gov transition are currently planning to omit the field in future iterations. It is therefore very important that, if this field impacts the users' experience, we understand exactly how. Is this something you can help with? 

JB Walters also responded (after I wrote that message) on 8/8, adding Arienne Walters, Bob Lewis, and Joel Calumpong to the thread.

**Comment by fmccaf1** [comment]
By 8/11, still hadn't heard from Haritha Cheruvu, Swathi Alikatti, and Sandeep Karuturi. I sent another message to the thread starting with:

> I'm still waiting on hearing back from Haritha, Swathi and Sandeep

By 8/15 I still hadn't heard from them and I reached out to Sean Good (with the hopes he could get them moving). 

Sean Good's response on 8/17:

> I reached out to Jason and his team and they don't know what the field is used for, at least from the access side. 

Jason Boire also wrote on 8/17:

> I spoke with our team about this. We don't know much about how / where that field is used. We know that what the Veteran checks or unchecks is displayed to the users in the Admin Portal, so the help desk and admin staff can see which facilities the user says they get treatment at. We don't know what other MHV components may or may not be using that data to adjust the user experience. If none of the other product lines have said they use the data, it's possibly that this will just impact the help desk flows in that the data will become more stale over time if the users are unable to make updates to it.

**Comment by fmccaf1** [comment]
[I included a summary of findings on the notes page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/preferences/My-VA-Treating-Facilities.md)

I'll close this ticket now and talk about next steps with Patrick in our cartography channel.
