### ISSUE TITLE
Update the appointments events code to GA4 (Part 1) 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#58468]
## Description
We will need to migrate the appointments analytics to GA4 (Google Analytics). We have selected the first five events for this initiative. Our team partnered with the Analytics team and they have provided the configuration of the GA4 properties and will need to validate if it is working as expected [(see ticket #57685)](https://app.zenhub.com/workspaces/vaos---productdesign-5fff340c2d80a4000fb6f69c/issues/gh/department-of-veterans-affairs/va.gov-team/57685)

Below is the sample data layer code from the Analytics team. The required fields are `event` and `action`. All of the other fields are optional for the team to use. 

event: 'interaction',
action: 'enter event name'
custom_string_1: '<custom_string_1>',
custom_string_2: '<custom_string_2>',
custom_number_1: <custom_number_1>,
custom_number_2: <custom_number_2>,
selected: '',
status: ,
previous_value: '<previous_value>',
value: '',
selected: '',
type: '',
required: '',
heading_1: <heading_1>,
heading_2: <heading_2>,
component_name: <component_name>,
component_version: <component_version>

---

## Acceptance Criteria

1) Update the `vaos-cancel-appointment-submission` event
- [ ] The event will be 'interaction' 
- [ ] The action will be 'vaos-cancel-appointment-submission'

2) Update the `vaos-cancel-booked-clicked` event
- [ ] The event will be 'interaction' 
- [ ] The action will be 'vaos-cancel-booked-clicked'

3) Update the `vaos-direct-path-started` event
- [ ] The event will be 'interaction' 
- [ ] The action will be 'vaos-direct-path-started'

4) Update the `vaos-direct-submission` event
- [ ] The event will be 'interaction' 
- [ ] The action will be 'vaos-direct-submission'

5) Update the `vaos-eligibility-direct-check-past-visits-failed` event
- [ ] The event will be 'interaction' 
- [ ] The action will be 'vaos-eligibility-direct-check-past-visits-failed'

### Design Assets
N/A

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by ldelacosta** [comment]
@jenniemc - moving this ticket back to In Progress.

**Comment by jenniemc** [comment]
cancelled direct appointment
<img width="416" alt="Screenshot 2023-05-31 at 9 03 16 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/54327023/c799b484-e600-482a-9979-0688f4e85be7">

**Comment by ldelacosta** [comment]
We will need to make modifications. I have created a new ticket for the new work. 

1. Create a new feature toggle (#60596)
2. Move the five GA4 events to the new feature toggle (#60657
3. Update the format for the four events (#60657)

Closing out this ticket since there is no further work needed.
