### ISSUE TITLE
My VA team follow up - Emergency Contact Name, Next of Kin, and ICE Preferred Contact Method fields

### ISSUE THREAD

**Issue by LynneJohnson224** [department-of-veterans-affairs/va.gov-team#58462]
Follow up with the My VA team on the Emergency Contact Name, Next of Kin, and ICE Preferred Contact Method fields:

- [ ] Are these fields being added to My VA?
- [ ] If they are not being added to My VA, is it appropriate for this to be on My VA or MHV on VA.gov and where? 

### Acceptance Criteria:

- Meet/slack with My VA to confirm ownership.
- If we have ownership, create follow on tickets
- Document discussion/findings in ticket

### Dependency
Dependency on My VA Team, availability for the discussion, and the results of the conversation.

**Comment by fmccaf1** [comment]
### Next steps

We need to set up a meeting to get this conversation started:
- Should these fields move over the My VA?
- What language should be used? i.e. Emergency contact vs. next of kin and additional field(s) for email address, phone number(s)?
- What support will the Unauthenticated Experience team need to get these fields over?

**Comment by fmccaf1** [comment]
[Created ticket 59421 for follow-on work](https://app.zenhub.com/workspaces/mhv-on-vagov-top-level-view-62619a987d74510018ecc546/issues/gh/department-of-veterans-affairs/va.gov-team/59421)
