### ISSUE TITLE
[Design] MDT- Review order page - edit contact details, v1

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#5847]
## Tasks:
Create high fidelity mockup(s) showing how a Veteran might update their  address and contact details
Upload to Invision with a comment to highlight initial focus state

## Acceptance criteria:
Mockup aligns with VA.gov’s design system
Include a way for Veterans to edit their mailing and email addresses
Include a way for Veterans to save or cancel their edits
Initial focus point documented in Invision
Sketch artboards are uploaded to Invision and linked in this ticket as a comment

**Comment by rileyorr** [comment]
@leahkeeler This work has been completed for a while and this ticket is no longer necessary
