### ISSUE TITLE
GIDS: Combine Fuzzy and Manual Match Pages

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#5848]
As an EDU Team Member, I need to be able to see potential matches and the manual match functionality on the same page so that I have all information available when making decisions to update the crosswalk.

## Assumptions:
1. The Fuzzy Match Page (https://staging.va.gov/gids/crosswalk_issues/partials/find_matches/35589) will be merged into the Manual Match Page (https://staging.va.gov/gids/crosswalk_issues/partials/35589).

## Acceptance Criteria
1. All match functionality is on a single page (https://staging.va.gov/gids/crosswalk_issues/partials/xxxxx).
2. There is a single action button on the "Crosswalk Issues" table: Fix
3. The WEAMS table displays the following readonly information:
     - Name
     - Facility Code (link to comparison tool that opens in new window ex. https://staging.va.gov/gi-bill-comparison-tool/profile/21907103)
     - Full Address
     - Full Physical Address
     - IPEDS
     - OPE
     - Action
4. The WEAMS action column has a button that allows the user to set the crosswalk IPED AND OPE fields to match the corresponding WEAMS values.
5. The IPEDS table displays the following readonly information:
     - % Match (Whole Number)
     - Name
     - Full Address
     - IPEDS (link to college navigator. ex: https://nces.ed.gov/collegenavigator/?id=217819)
     - OPE
     - Action
6. The IPEDS action column has a button that allows the user to set the crosswalk IPED AND OPE fields to match the corresponding IPEDS HD values.
7. The Crosswalk table displays the following information:
     - Name
     - Facility Code
     - City
     - State
     - IPEDS
     - OPE
     - Notes
     - Action
8. The crosswalk action column has a button that allows the user to clear the crosswalk IPED AND OPE values.
9. If the crosswalk OPE and IPED data:
     a. matches a row in the IPEDHD, the crosswalk table has a highlighted readonly row reflecting the current crosswalk data for the facility code.
     b. does not match a row in the IPEDHD, there is no separate readonly row.
10. The crosswalk table has a row reflecting the user selected data with the following states for each field:
     - Name (readonly)
     - Facility Code (readonly)
     - City (readonly)
     - State (readonly)
     - IPEDS (editable)
     - OPE (editable)
     - Notes (editable)
     - Action
10. The action buttons update the crosswalk "update" row with the user selected data.
11. The user can save the changes to the crosswalk.
12. The user can cancel the changes and return to the crosswalk issues table.

## Supporting Artifacts:
1. Mockup:
![combined_match_2](https://user-images.githubusercontent.com/48260534/74476514-763ceb00-4e77-11ea-92bc-c2ab97487120.png)

## PRs
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/580

**Comment by dmccurdybah** [comment]
Can be tested on gibct-data-service branch `crosswalk-cleanup`

**Comment by sonntag-adam** [comment]
AC #1
![Screen Shot 2020-02-21 at 12.28.10 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/6a3fec89-41d8-4da9-894e-443c72bf7cde)

**Comment by sonntag-adam** [comment]
AC 2
![Screen Shot 2020-02-21 at 12.28.28 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/aae7095e-7105-43fb-806c-1d9a00de65a0)

**Comment by sonntag-adam** [comment]
AC 1/3/4/5/6/7/8/9/10
![Screen Shot 2020-02-21 at 12.28.28 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/21c6f5c1-b150-4c12-b4fc-17cfac8820bf)
##
AC 2
![Screen Shot 2020-02-21 at 12.28.10 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/d74c9be3-de2b-4ee3-a4d1-a53055c15ede)
##
AC 9b with no read only row
![Screen Shot 2020-02-21 at 12.40.09 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/a7f67957-91c7-4e71-ac8b-ac3b0bcd0045)
##
AC 11/12 update
![Screen Shot 2020-02-21 at 12.44.38 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/1a4b30af-1b93-4e74-9dc7-aad1f1e8d4d6)
##
AC 13 cancels and returns to "GI Bill Comparison Tool Crosswalk issue"
##
All match actions work as desired

**Comment by sonntag-adam** [comment]
Testing passes
https://dsvavsp.testrail.io/index.php?/runs/view/197&group_by=cases:section_id&group_order=asc&group_id=46

**Comment by sonntag-adam** [comment]
In staging closing story
