### ISSUE TITLE
Look into 2 URLs with duplicate form info for transferred benefits

### ISSUE THREAD

**Issue by megzehn** [department-of-veterans-affairs/va.gov-team#58516]
These 2 URLs have very similar info. We need IA to investigate and see if this is intentional or if they should be combined. 

- https://www.va.gov/education/apply-for-education-benefits/application/1990E/introduction
- https://www.va.gov/education/survivor-dependent-benefits/apply-for-transferred-benefits-form-22-1990e/introduction

The first link has slightly older content, and it shows up earlier in search results. You can access the second link from the [How to apply](https://www.va.gov/education/how-to-apply/) page, after answering the questions in the action button.

**Comment by kristinoletmuskat** [comment]
Did work on this in the google doc here: https://docs.google.com/document/d/1PEb01jKks1DeD-KDzuRG9DHWeyGaBqnxmw-eBRRK_LQ/edit#heading=h.v3h6noex9qy7

After reviewing this, I think that the first page listed (https://www.va.gov/education/apply-for-education-benefits/application/1990E/introduction) might have been a missed redirect, and we can solve this problem by implementing a redirect now. 

Next steps:
- [ ] Confirm this plan with Mikki
- [ ] @katherine-fung could you double check with the Education forms team you work with (if that seems like the right team), that this is a duplicate page?

**Comment by mnorthuis** [comment]
FYI, there are intentionally two forms here - one is for unauthenticated users, and the other for authenticated users.  This is not a great situation, but how the education team was contracted to do this.   We can't redirect one of the forms, but ideally we should make one of them the canonical version.   Unfortunately we need the education team to do that work.  They took a similar approach on the 1990 form.

**Comment by mnorthuis** [comment]
Blocking this issue - @bethpottsVADEPO to follow up with VBA education SMEs on adding canonical tag to unauth 1990E form to hopefully alleviate some search issues.

**Comment by bethpottsVADEPO** [comment]
**Update:** Email sent to stakeholders in Education Service last week. Setting up a meeting with them for this week to go over what needs to happen.

**Comment by kristinoletmuskat** [comment]
@mnorthuis and @bethpottsVADEPO Q for documentation -- are these URLs changing as part of this fix?

**Comment by mnorthuis** [comment]
@kristinoletmuskat The URLs will not change, they will stay as is.

**Comment by kristinoletmuskat** [comment]
From Beth on 7/25: this is for Education Service to deal with. I'm not sure if they've fixed this yet, but I can follow up with them. You can close this ticket.
