### ISSUE TITLE
FE - Landing Page Error Investigation

### ISSUE THREAD

**Issue by LynneJohnson224** [department-of-veterans-affairs/va.gov-team#58527]
FE landing page error investigation

- [x] CSP errors (Content Security Policy): [Datadog query](https://vagov.ddog-gov.com/rum/explorer?query=%40type%3Aerror%20%40application.name%3A%22MHV%20on%20VA.gov%22%20env%3Aproduction%20-%40browser.name%3AHeadlessChrome%20%40error.message%3A%2Acsp_violation%2A&cols=&index=%2A&type=rum&viz=stream&from_ts=1684429501906&to_ts=1684515901906&live=true)
- [x] Non-CSP errors: [Datadog query](https://vagov.ddog-gov.com/rum/explorer?query=%40application.name%3A%22MHV%20on%20VA.gov%22%20env%3Aproduction%20-%40browser.name%3AHeadlessChrome%20-%40error.message%3A%2Acsp_violation%2A%20%40error.type%3ATypeError%20%40type%3Aerror&cols=&index=%2A&type=rum&viz=stream&from_ts=1684429501906&to_ts=1684515901906&live=true)

**Comment by batemapf** [comment]
> A session replay for an error occurred shortly after testing with Stephen, and it looks like the user's browser had trouble loading things

not sure if this was the case, but the session replay functionality usually renders a little weird (datadog is rebuilding the page based on what it can access, then mapping the users actions on top of it — or that's what i've inferred), so if things look wonky in a replay, doesn't necessarily mean they were wonky for the user.

**Comment by batemapf** [comment]
random thought you've prob already tried — are the CSP errors occurring on other VA.gov DD RUM applications? we instrumented the 10-10EZ and the check-in products with RUM (pretty much same config as landing page), so if the CSP errors they are happening on those products, this suggests a wider VA.gov thing (and maybe it's safe to just create a ticket in the platform team's backlog and close this one out as non-actionable).

**Comment by LynneJohnson224** [comment]
Closing ticket - will create ticket in Platform BL.
