### ISSUE TITLE
Portal Level Preferences Research

### ISSUE THREAD

**Issue by LynneJohnson224** [department-of-veterans-affairs/va.gov-team#58539]
- [x] Review all existing MHV National Portal Global Preferences in the spreadsheet
- [x] ID which global preferences are orphans/stragglers this team is responsible for
- [x] Create individual tickets for migration of those orphans as needed

### Acceptance Criteria
- [x]  Tickets have been created for all orphans
- [x]  Larger team has been notified of orphans with related ticket numbers

Orphans previously ID'd:
#58462
#58461 (Medical records will be handling)
#58460
#59196

**Comment by carafrissell1** [comment]
5/19 notes Backlog Grooming notes:
- Preferences that could impact multiple applications in the portal
- There's a handful of preferences that don't fit neatly into an application or va profile, including: Treating Facility 
- This team's role to look at those straggler preferences

**Comment by A6-toma** [comment]
Task 1 - look at unfiltered spreadsheet to identify any additional "orphan" preferences; add column to spreadsheet to ID which team is responsible for each orphan and open communication with them

**Comment by jonathanjnelson** [comment]
Adding Health info card (which is related to #58462)

**Comment by jonathanjnelson** [comment]
Don't think a followup ticket is needed but wanted to document here (please push back). 

This section of Personal Information allows users to manage their password, and view account details, including log-in attempts.

This section appears to become irrelevant once we migrate to VA.gov. What are your thoughts @batemapf @fmccaf1 

![Screenshot 2023-05-26 at 12.21.29 PM.png](https://images.zenhubusercontent.com/5df3ac60534bc19675f4ca43/f7cded8a-6077-48ab-9c1e-aa3f672d76c6)

**Comment by jonathanjnelson** [comment]
It seems like there is general conscious the links section is no longer needed - could make an additional followup ticket if you think it's needed? @fmccaf1 @batemapf 

![Screenshot 2023-05-26 at 12.20.42 PM.png](https://images.zenhubusercontent.com/5df3ac60534bc19675f4ca43/cc032888-f01f-4d76-9260-39d7210d7939)

**Comment by batemapf** [comment]
> the links section is no longer needed

concur

**Comment by jonathanjnelson** [comment]
Closing this ticket as the stragglers have been identified from spreadsheet and additional tickets made. All appropriate people are aware.
