### ISSUE TITLE
[Research] Discovery for Veteran Information Editing 

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#58542]
)As a Veteran, I would like to be able to update my financial information online so I make sure I don't have to constantly fill out paperwork and make sure I don't have to pay co-pays if I don't need to. 

- Connect with Kristen McConnell
- Determine everywhere Veteran can update their information online
- Here is a link to EZR vs. My VA gap analysis https://docs.google.com/spreadsheets/d/1IGLA8GT35ffS2PnFvCwdnA7bWTL5187TN9QlVwUXYr4/edit#gid=0 
- Determine how Veteran updates information IRL
- Come up with proposed workflow for updating EZR
- Share with team
- Share with stakeholders (Patrick, EZ stakeholders, Kristen)
- 

Link to EZR form: 
[https://app.zenhub.com/files/133843125/04c99ace-4f31-4342-aaa6-320fc48eb90d/download](https://app.zenhub.com/files/133843125/04c99ace-4f31-4342-aaa6-320fc48eb90d/download

**Comment by jessicastump** [comment]
A [blank Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1684943221068/4b11f2d1902d05f12f53468263a561c2d5a460a9?sender=uadf1ed7fe7c76f0914967329), if needed, to start for EZR discovery gathering.
