### ISSUE TITLE
[Dev] Review Front End Unit Tests

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#58545]
As a team member, I would like all front end Unit Tests to work so that I know we have full test coverage and deploys are easy.

- Review FE Unit Tests
- rerun

**Comment by longmd** [comment]
We actually don't have any flakey tests in our suite. There is an automated process that notifies teams when they have tests that are flakey. This can be updated to actually creating and writing unit tests for areas where testing lacks currently.

**Comment by longmd** [comment]
[#60897](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60897) & [#60898](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60898) have been created to address the work needed to meet specification.
