### ISSUE TITLE
EVSS Migration - rated disabilities - implement `rated_disability_id` in Lighthouse API Provider transform layer

### ISSUE THREAD

**Issue by aurora-a-k-a-lightning** [department-of-veterans-affairs/va.gov-team#58558]
## Notes
- This is the follow-up to #58214
- Dependent on Lighthouse's implementation of `rated_disabilities_id` in the individual rating data object
-- best case scenario it would be ready by mid June 2023

- 6/21, LH has made the update; currently live in prod
- LH also added a `diagnostic_text` field. There is a requirement from va.gov to map this to `name` instead of `diagnostic_type_name`
- Schema documentation: https://staging-developer.va.gov/explore/verification/docs/veteran_verification?version=current

## AC
- transform layer unit test - check for rated disability id
- Updated RRD rated disability unit test to not use an ID of 0

**Comment by mchae-nava** [comment]
[https://app.zenhub.com/files/133843125/8af67fe4-ebc7-43a0-8a7a-b18014e7b122/download](https://app.zenhub.com/files/133843125/8af67fe4-ebc7-43a0-8a7a-b18014e7b122/download)
