### ISSUE TITLE
PROD: Veterans are Selecting CC Providers in VAOS that Should Not Be Selectable

### ISSUE THREAD

**Issue by JRRoof** [department-of-veterans-affairs/va.gov-team#58553]
## Description
Veterans are selecting Community Care providers in VAOS that should not be selectable.  VA HSRM Staff are going into the PPMS system and flagging the providers as not available but the veterans are still able to select those unavailable providers in VAOS.   This is the issue.  BE team owns mobile-ppms-service, but it's just a pass-through to the PPMS API.  When using the PPMS API, all the providers are returned and there isn’t any status information or comments indicating a provider is unavailable.  

VAOS uses this PPMS API and calls directly from the Front End:  FacilityServiceLocator to get a list of providers.

VAOS needs PPMS to either do the filter unavailable providers or or send us the status to that F/E or B/E can filter.

Per call with PPMS, provider can be set as available/unavailable and then the services for a provider can also be set as active/inactive. As an example, Dr Smith does Podiatry and Primary Care but may be active for Podiatry (service is active) and not primary care (service is inactive).  So Front End would need to check provider avail and if service (VAOS Type of Care selected) was active/inactive.

ISSUE:  Per Edison L. Badua -
We’ve been receiving Primary care requests in VAOS requesting for the same community providers where they’re not practicing in a primary care clinic but rather in a specialty clinic or long-term care facility. This has been an ongoing issue and it’s becoming redundant/tedious by calling the Veterans every time a request comes in with their preference. When we notify the Veteran about this, s/he will complains as to why the providers are even on this list as one of their options. I am uncertain on how to get this resolved or prevent this issue from occurring again, and unfortunately having these additional steps to  process consults is a wasted time.  

As I stated previously, we are able to update the status of provider availability in PPMS by entering a pre-selected comment and will flag the staff that this provider is not available and thus cannot be selected.

## Proposed Solution
The provider/service availability and status are available in the PPMS database, but not accessible via an API end point today.  The available fields are:
**ppms_unavailablestartdate
ppms_unavailableenddate
ppms_availabilityname**

In order to retrieve this information we will need to pass the ppms_provideridentifer and possibly the ppms_specialtycode to the new PPMS API end point.

The ppms_provideridentifer and the ppms_specialtycode

These values are retrieved using the Facilities API **/facilities_api/v1/ccp/provider**.  A typical set of data will look like this:

    {
      "id": "1154867018",
      "type": "provider",
      "attributes": {
        "accNewPatients": "true",
        "address": {
          "street": "3800 RESERVOIR RD NW FL 1",
          "city": "WASHINGTON",
          "state": "DC",
          "zip": "20007-2113"
        },
        "caresitePhone": "202-444-3000",
        "email": null,
        "fax": null,
        "gender": "Female",
        "lat": 38.911431,
        "long": -77.075268,
        "name": "GUILD, MICHAELA",
        "phone": null,
        "posCodes": null,
        "prefContact": null,
        "uniqueId": "1154867018"
      },
      "relationships": {
        "specialties": {
          "data": [
            {
              "id": "363LP2300X",
              "type": "specialty"
            }
          ]
        }
      }
    },

In this example:

**ppms_provideridentifer = attributes.uniqueId = 1154867018
ppms_specialtycode = relationships.specialties.data.id = 363LP2300X**

Once the PPMS team provides us with the new API end point then we will add a lookup to PPMS to check the availability of provider/service before displaying a list of providers to a veteran.  

## Reference 
Jira issue [VAOSR-5161](https://issues.mobilehealth.va.gov/browse/VAOSR-5161)
PPMS Change Order - CR065

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by ldelacosta** [comment]
Need to check with Kay if this is still something we want to implement cc: @JRRoof

**Comment by ldelacosta** [comment]
This is not needed anymore. Closing out the ticket. cc: @JRRoof
