### ISSUE TITLE
Create messaging for February scheduled downtime 

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#5856]
## User story
We have scheduled PC update for Saturday Feb 15 for between 2100-2130 (9:00-9:30 p.m.) EST. We need downtime notifications to let users know some tools/services won't be available during this time frame. 

## Notes

**Advanced messaging**
We'll be doing site maintenance on [Date] between [Time] and [Time]. You won’t be able to sign in or use some tools during this time.

**Countdown message**
Scheduled maintenance starts in [X minutes]. If you’re filling out a form, sign in or create an account to save your work.

**During downtime**
We're working on VA.gov. If you have trouble using online tools, check back after ${expiresAt.format('MMM Do [at] h:mm a z')}.

## Acceptance criteria

We need 3 promo banners:
- [ ] **Advanced messaging** (see below comment) 12 hours beforehand.
- [ ] **Countdown message** (see below comment) 60 minutes beforehand.
- [ ] **During downtime message** (see below comment) until 21:30 EST.
- [ ] These messages should be easily configurable in the near future if we have this request again.

**Comment by peggygannon** [comment]
Hello @jenniferlee-dsva Here are the recommended messages for the downtime that's scheduled for 2/15. I mirrored them off of the one we did last month. Please let me know if you have any questions/feedback. 

@kelsonic @KevinMHoffmanUSDS 

**Advanced messaging**
We'll be doing site maintenance on [Date] between [Time] and [Time]. You won’t be able to sign in or use some tools during this time. 

**Countdown message**
Scheduled maintenance starts in [X minutes]. If you’re filling out a form, sign in or create an account to save your work.

**During downtime** 
We're working on VA.gov. If you have trouble using online tools, check back after ${expiresAt.format('MMM Do [at] h:mm a z')}.

**Sign in message**
**You may have trouble signing in or using some tools or services**
We’re doing some work on VA.gov right now. We hope to finish our work by [Date and Time]. If you have trouble signing in or using any tool or services, check back after then. 

**In-app message**
**This form is down for maintenance**
We’re making some updates to this form. We’re sorry it’s not working right now and we hope to be finished by [Date and Time]. Please check back soon.

**Comment by kelsonic** [comment]
Thank you @peggygannon for making this!! ❤️

**Comment by MickinSahni** [comment]
Adding this to sprint 15

**Comment by jenniferlee-dsva** [comment]
Looks great. Thank you @peggygannon @kelsonic @MickinSahni . 

@MickinSahni RE messages for sign in and apps - other teams implement those, so can we pull it out of this ticket?

**Comment by peggygannon** [comment]
@MickinSahni @jenniferlee-dsva I've asked VSP devs for guidance on who/which team we should loop in to implement the sign-in and in-app notification. I remember there was a bit of confusion on this last time!

**Comment by MickinSahni** [comment]
Pulling into Public Websites's Sprint 15

**Comment by MickinSahni** [comment]
2020-02-14 PW Standup
- "MVP" merged and the notification is merged, but there's clean-up to do (in a separate PR)

**Comment by kelsonic** [comment]
I think there's a plan being formed to potentially abstract this code into PagerDuty where the times can be managed (instead of sending up PRs to `vets-website` every time we need to update scheduled downtime maintenance): https://dsva.slack.com/archives/CBU0KDSB1/p1582038661311900?thread_ts=1582035678.308200&cid=CBU0KDSB1

**Comment by MickinSahni** [comment]
2020-02-19 PW Standup
- reverted merge for this downtime
- waiting for sign-off for when the downtime will occur so that we can merge back in the notification
- will drag into the appropriate sprint when good-to-go

Note: this is a banner across the bottom of the screen, letting folks know when the downtime is expected

@KevinMHoffmanUSDS @rianfowler - we're looking to you for the go-ahead as to when we'll need to merge this in.

**Comment by MickinSahni** [comment]
- removing blocked label and continuing to work on making downtime notifications easier
- feb 29, 9p et -- anticipated downtime

**Comment by kelsonic** [comment]
Merged in a PR that makes downtime messaging easily configurable in the future: https://github.com/department-of-veterans-affairs/vets-website/pull/11732

**Comment by MickinSahni** [comment]
- planning to go out in Friday's afternoon deploy and will be available for validation after
- validation steps: change OS time to 12 hrs, 1 hr, during downtime, after downtime

**Comment by jenniferlee-dsva** [comment]
@MickinSahni just want to make sure (bc now I'm a little paranoid) that the above 'planning to go out in Friday's deploy' - is only referring to the reusable behavior, not publishing the downtime messages for today/tomorrow? 

[Per this slack thread](https://dsva.slack.com/archives/CBU0KDSB1/p1582147754428000?thread_ts=1582035678.308200&cid=CBU0KDSB1) - I think the next actual API downtime is scheduled for Feb 29, next Saturday, and 9:00 p.m. ET. (Unless they've modified that target.)

**Comment by MickinSahni** [comment]
@jenniferlee-dsva that's correct; the PR to make it easier to set downtime notifications is going out this afternoon for us to test (by changing our system time, etc.)

**Comment by MickinSahni** [comment]
Validated. @kelsonic @AkucherGCIO feel free to close if it makes sense
![image](https://user-images.githubusercontent.com/13204473/75270374-72d72700-57c8-11ea-94a1-c87d796b4be5.png)

![image](https://user-images.githubusercontent.com/13204473/75270383-75d21780-57c8-11ea-8cea-908eb8402019.png)

![image](https://user-images.githubusercontent.com/13204473/75270395-79fe3500-57c8-11ea-9e87-e99bd3f5e3ad.png)
