### ISSUE TITLE
Left Navigation Research/Discovery

### ISSUE THREAD

**Issue by LynneJohnson224** [department-of-veterans-affairs/va.gov-team#58588]
Documenting the current left navigation decisions by MHV on VA.gov app teams (in tool navigation) and hand over standards to app teams.

- [x] Conversation with Coulton on the current status/where things are
- [ ] Understand LN roadmaps for each app.
  - [ ] Who has done what with the LN?
  - [ ] What does LN in each app look like? How far apart are they?
  - [ ] Reasoning for decisions?
- [ ] Align decisions - Standards for left navigation - extract decisions that were made for SM, standardize and share with other teams/POs for implementing in their tools.

### Acceptance Criteria

- Discuss and document current status
- Review with team and create additional tickets as needed
- Document current practices

**Comment by LynneJohnson224** [comment]
relevant thread: https://dsva.slack.com/archives/C04GDQSHD1R/p1676572672817329?thread_ts=1676400596.154349&cid=C04GDQSHD1R

**Comment by batemapf** [comment]
@carafrissell1 if you haven't already, please connect with @coultonbunney-usds and @mnorthuis about this work and making sure we're not doing this work twice. and now that i've typed that, i see the first task is to

**Comment by carafrissell1** [comment]
Left Nav discovery Mural from Mikki:
https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1685564778598/5a5e366d9a442a515f73b89e1c47d6364e9a9ece?wid=0-1685565559026&sender=ub0f383fafad4c2df7fc53935

**Comment by carafrissell1** [comment]
Closing ticket based on convo with @coultonbunney-usds and @mnorthuis 
Will create new tickets in future as needed![Screenshot 2023-06-09 at 2.00.53 PM.png](https://images.zenhubusercontent.com/6435822304a0a83eda66ee47/cd4fd658-55ab-4b54-b4e8-b71554d074c5)
