### ISSUE TITLE
 Sidekiq Periodic Jobs  Replace Sidekiq Scheduler

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#58609]
UPDATED

The Sidekiq Periodic jobs will replace the Sidekiq Scheduler, not cron jobs 

**Updated info below:** 
EKS cron jobs need to replace the Sidekiq Scheduler. Any information for this ticket can be found in this [documentation](https://vfs.atlassian.net/wiki/spaces/TT1/pages/2564325465/EKS+Cron+Job+Deployments).

A cron job needs to be created for each Sidekiq job listed in this [file](https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/sidekiq_scheduler.yml).

**Comment by laineymajor** [comment]
This should be done by COB 5.25

**Comment by RachalCassity** [comment]
PR is review

**Comment by laineymajor** [comment]
@rmtolmach for review

**Comment by LindseySaari** [comment]
@RachalCassity It looks like there are a few comments to address. @laineymajor can you work with Rachal to make a general announcement about these changes. Some jobs have been shifted a bit to space things out, and it shouldn't cause issue, but we should make teams aware of the changes coming along.

**Comment by RachalCassity** [comment]
PR Merged!
