### ISSUE TITLE
Add `credential_used_uuid` to `sso_cookie_content`

### ISSUE THREAD

**Issue by rileyanderson** [department-of-veterans-affairs/va.gov-team#58640]
## Issue Description
If a user has both an IDme and login.gov account `user_uuid` in the logs will be set to IDme uuid regardless of which method they logged in with. To find a logingov uuid in this instance, one would have to query the database. Add the `credential_used` uuid to the log to avoid having to do that

## Back end tasks
- [ ] Add `credential_used_uuid` to `sso_cookie_content`
- [ ] change `user_uuid` in `sso_logging_info` to `idme_uuid` and `logingov_uuid`

**Comment by parkerbees** [comment]
Closing. This ticket is over a year old. If still relevant it can be pulled from Zenhub in future.
