### ISSUE TITLE
Intermittently fails to download letters

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#58646]
401 authorization errors occurring on LH download endpoints intermittently

See this Slack thread for clues:
https://dsva.slack.com/archives/C02CQP3RFFX/p1684351510607389

**Comment by samcoforma** [comment]
Some things to consider before diving in:

- Lighthouse CCG tokens expire after 5 minutes: https://dsva.slack.com/archives/C02CQP3RFFX/p1684352600094349?thread_ts=1684351510.607389&cid=C02CQP3RFFX
- CSRF tokens and sessions can be "stolen" by another browser logged in with the same user at the same time (this mirrors my use case during the demo when this was happening): https://github.com/department-of-veterans-affairs/va.gov-team/issues/58058

**Comment by kjduensing** [comment]
This one is hard to test/replicate because we need to wait for the 30 min user session to expire.

**Comment by kjduensing** [comment]
I don't understand right now how this behavior could happen. After waiting 30 mins in one browser, I was logged out of both browsers. 30 mins is the session length described in the platform ticket (#58058). Next I'll try logging in, waiting 10 mins (to expire the Ligthhouse CCG token) and see if I get the expected behavior.

**Comment by kjduensing** [comment]
Waiting a shorter amount of time to stay inside of the user session, but outside of the LH CCG token sessions exp did not reproduce the issue either.

**Comment by kjduensing** [comment]
@samcoforma - you originally discovered this issue, maybe you and I can do some testing later today

**Comment by kjduensing** [comment]
[I have a fix  out there](https://github.com/department-of-veterans-affairs/vets-api/pull/12760).
