### ISSUE TITLE
Analytics KPI dashboard update request for VA Notify - Add LGY Landing Page

### ISSUE THREAD

**Issue by bevnobev** [department-of-veterans-affairs/va.gov-team#58649]
# Request an update to your KPI Dashboard  

## What this form is for

Use this ticket template to request an update to your existing KPI dashboard. To request a new product be added to our dashboards, please use [Request a New Standardized KPI Dashboard template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&template=analytics-request-kpi-dashboard.md&title=Analytics+KPI+dashboard+request+for+%5BTeam%5D).

### Expected delivery timelines

Once you’ve submitted this ticket template, your KPI dashboard update request will be pulled into the Analytics team’s workflow the following Wednesday during Platform Sprint Planning or Refinement. We expect to deliver your completed dashboard within the next sprint. 

## Instructions for the VFS team
First, tell us what type of change you need to make:

- [ ] Change basic product info
- [ ] **Forms**: funnel changes
- [ ] **Content**: Add or remove pages included
- [X] Other____Add landing page to dropdown menu_________________________

Next, use the original [KPI request template]() or [(downloaded Excel version)](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/1586823275/KPI%20Dashboard%20Product%20Details%20Template%20-%20MAKE%20A%20COPY.xlsx?inst-v=ced1f4dd-e997-4aa2-9ae8-2cebe369b42f) you filled out to update your information. If you are not able to find that spreadsheet, reach out to the Analytics team on #vfs-platform-support for a new spreadsheet that reflects what we currently have on file.

In the VA Notify KPI Domo Dashboard, we have a landing page section where we track the number of clicks from an email notifications to a landing page. We would like to add a new landing page in the drop down menu.

Please add campaign code = 1880-SIP-reminder to the VA Notify dashboard tables. This campaign will link to https://www.va.gov/housing-assistance/home-loans/request-coe-form-26-1880/introduction as the Landing Page.  The other utm variables are as follows:  

- utm_source=VANotify
- utm_medium=email
- utm_campaign=1880-SIP-reminder

The campaign will launch tomorrow 5/18 so you may not see any hits yet.

**Adding a note on 5/19 - the campaign is the dropdown, but the corresponding Landing Page is not present.  Can you add the landing page for the campaign and make the landing page = LGY Reminder  https://www.va.gov/housing-assistance/home-loans/request-coe-form-26-1880/introduction**

- [ ] Make a copy of the [Google Sheet](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit#gid=981224988) [(or download Excel version)](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/1586823275/KPI%20Dashboard%20Product%20Details%20Template%20-%20MAKE%20A%20COPY.xlsx?inst-v=ced1f4dd-e997-4aa2-9ae8-2cebe369b42f)
- [ ] Complete worksheet as instructed
- [ ] Link your completed spreadsheet here: ______
- [ ] Check your sharing settings to make sure the Analytics team will be able to access it
- [ ] Add your team label to follow progress

**Additional Info**

- Please use the [KPI Framework](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/Analytics%20Playbook/va-gov-platform-analytics-kpi-framework.pdf) for more information on the metrics used in the KPI dashboards. 
- If you need any analytics support, read through the [How to request Analytics support](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guidelines.1586823275.html#Analyticscustomersupportguidelines-4.RequestaKPIDashboardinDomo).
- If you do not have Domo access, please [request access here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+access-request&template=analytics-request-google-analytics-domo-access.md&title=Request+access+to+Google+Analytics+and%2For+Domo).

**Comment by bevnobev** [comment]
cc: @gitsamjennings

**Comment by michelle-dooley** [comment]
@bevnobev - we will get this added to our next sprint.

**Comment by dorseypa1** [comment]
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/117392065/53e81eac-76b1-4c8b-92e7-a31980f1ebbe)

The new landing page has been added in BigQuery.  This ticket is ready for QA in Domo.
