### ISSUE TITLE
Add Sign in Service private_key_jwt authentication option to SiS Sinatra Client Sample App

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#58648]

**Comment by bosawt** [comment]
Will need this to be merged first: https://github.com/department-of-veterans-affairs/vets-api/pull/12690

**Comment by bramleyjl** [comment]
Covered by https://github.com/department-of-veterans-affairs/sign-in-service-client-sinatra/pull/24
