### ISSUE TITLE
Design intent - Design Feedback - BAH-MBS-SelfServ, Pre-Need Self Service, Pre-Need modernization and CaMEO Integration

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#58660]
## VFS actions
- [x] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [x] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [x] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [x] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- Love the user flows!
- If you are updating the profile for contact information, consider using the "[know their info is update](https://design.va.gov/patterns/help-users-to/know-how-their-information-is-updated)" pattern

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- Must: Remove the blue background alerts from things that are not alerts.[ Background only alerts](https://design.va.gov/components/alert#usage) are used mostly for immediate feedback.
“We require some basic…”
“Please note: This doesn't guarantee you’ll be buried…”
- Must: use [memorable date](https://design.va.gov/components/form/memorable-date) for DOB
- Must: There are a couple of [wizards](https://design.va.gov/patterns/wizards) in the prototype. “Did you serve under another name” and “Which VA national cemetery would you prefer” The wizard pattern is deprecated. Try 1 thing per page instead.
- Must: Submit application button should be on 1 line.
- Must: “Go back to VA.gov” should be an [action link](https://design.va.gov/templates/forms/confirmation#back-to-vagov-link)
- 

- Consider: Add the [success alert](https://design.va.gov/templates/forms/confirmation#success-alert) after the user submits their application.
- Consider: Review the [sub task pattern](https://design.va.gov/patterns/help-users-to/complete-a-sub-task) pattern and see if it is a better fit than [multiple responses](https://design.va.gov/patterns/ask-users-for/multiple-responses) (list and loop)

**Comment by ccruzgra** [comment]
@allison0034 Thank you for the feedback! We'll be working on reflecting your recommendations in our designs.

Regarding the Memorable Date component, our developers ran into an accessibility issue when trying to implement it for the DOB field. Based on Matthew Dingee's [guidance here in Slack](https://dsva.slack.com/archives/C0NGDDXME/p1666116702349269?thread_ts=1666116054.195219&cid=C0NGDDXME) that it is optional for teams to implement it and to "use with "caution", we may not be able to follow through on that item, but @AlexanderSherrow and @MichelleDieudonne may be able to provide more guidance about the issues we ran into.

**Comment by allison0034** [comment]
Hi @ccruzgra was the accessibility issue for [memorable date](https://design.va.gov/components/form/memorable-date) or the [date input](https://design.va.gov/components/form/date-input)? Looking at [your ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47460) I think it is date input.

@humancompanion-usds are you ok with this team not using memorable date? Cindy brings up a good point about the "use with caution"

**Comment by ccruzgra** [comment]
@allison0034 It was for the memorable date. @ConnorJeff could probably provide more context, but the validation messaging wasn't triggering until the user pressed the Continue button when they input incorrect data as opposed to happening when going off field. 

For the "Must: Submit application button should be on 1 line." would it be something like this?
![Screenshot 2023-05-22 at 9.49.47 AM.png](https://images.zenhubusercontent.com/5b55212f6dabc3393a2dbe50/85dbebd5-7213-4276-9ec1-82560fdc480c)

**Comment by allison0034** [comment]
@ccruzgra not the buttons, just the words. But I also logged in to see how it behaves and there could be certain break points where Submit is above application so you can keep it as it was. Sorry for the confusion.

**Comment by ccruzgra** [comment]
@allison0034 No worries! Thanks again for the feedback!

**Comment by ccruzgra** [comment]
@a
