### ISSUE TITLE
Resolve Critical Dependabot Alerts

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#58685]
### Issue Description
https://github.com/department-of-veterans-affairs/vets-website/security/dependabot?q=is%3Aopen+sort%3Amost-important

Alerts have begun to pile up in the vets-website repository. We need to resolve these starting with the critical alerts and working our way down the list.

---

### Tasks

- [x] Resolve all critical dependabot alerts

**Comment by it-harrison** [comment]
Some of the updates are problematic because dependencies are not compatible with the dependabot upgrade. Will break out into separate ticket.
