### ISSUE TITLE
Contact Center Review for [Veteran-facing-forms - Form 21-10210]

### ISSUE THREAD

**Issue by PSIEBENLIST** [department-of-veterans-affairs/va.gov-team#58684]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
*Please provide the name(s) of your product and a high-level description of your product.*
- This form is currently only in PDF Version, we are digitizing the form for an online Experience.
- The lay/witness statement (VA form 21-10210) provides an opportunity to submit a statement providing additional information in support of any disability compensation or pension claim that is on file.
- [Product outline](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/21-10210/product%20outline.md) 
- [ia-sitewide content questions](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/21-10210/ia-sitewide.md) 

## User Stories
*Please provide the name(s) of your product and a high-level description of your product.*
- As a Veteran, I would like to submit a statement on behalf of myself in support of a claim of benefits/services 
- As a claimant, I would like to submit a statement on behalf of myself in support of a claim of benefits/services
- As a witness, I would like to submit a statement on behalf of a Veteran in support of a claim of benefits/services made by the Veteran
- As a witness, I would like to submit a statement on behalf of a claimant in support of a claim of benefits/services made by the claimant 

### Launch Date
*Please provide the launch or rollout date and details.*
Tentative around June 1

### Version Number
*Please provide the version number of the guide and/or video.*
Version 1

### Product Guide
*Please provide product guide link*
[21-10210 Product Guide](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/21-10210/Form%2021-10210%20Product%20Guide%20v2.pages)

### Product Video
*Please provide product video link*
n/a

### Product Video Transcript
*Please provide product video transcript link*
n/a

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by PSIEBENLIST** [comment]
Hi @jwoodman5 @Kimberley2019! Following up to see if you any questions on this contact center review. Thanks!

**Comment by tbaker1026** [comment]
[Link to Word Document](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/21-10210/Form%2021-10210%20Product%20Guide.docx)

**Comment by PSIEBENLIST** [comment]
Hi @jwoodman5 @Kimberley2019 - just wanted to flag this contact center review to see if you have an update or any questions. We are hoping to go live next week. Thanks

**Comment by starlow00** [comment]
Hi @PSIEBENLIST. Thanks for bringing this to my attention, as I do need to review this draft before submission to the VEO Call Center. This is the first I've heard of this, and I apologize for any delays. I will begin the review today!

For future reference, here is the Contact Center procedure for Product Guide submission: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md

**Comment by starlow00** [comment]
Hi @PSIEBENLIST. The guide looks good, but it will need a few replacement screenshots for Stories 2 (starting on page 12) and 4 (starting on page 23). The "Step X of 8" or "Step X of 10" are mixed up a little. Look at this attached draft and you'll see what I mean, but feel free to contact me if you have questions. Thanks!
[Form 21-10210 Product Guide v2 07132023.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/12059455/Form.21-10210.Product.Guide.v2.07132023.docx)

**Comment by starlow00** [comment]
Sharing this with VEO today.

**Comment by starlow00** [comment]
Sent for VEO review.

**Comment by starlow00** [comment]
No changes from VEO. Current document attached here.[https://app.zenhub.com/files/133843125/5434b677-8718-4f66-a0d2-041b9d913e0b/download](https://app.zenhub.com/files/133843125/5434b677-8718-4f66-a0d2-041b9d913e0b/download)
