### ISSUE TITLE
Resolve High Dependabot Alerts

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#58687]
### Issue Description
https://github.com/department-of-veterans-affairs/vets-website/security/dependabot?q=is%3Aopen+sort%3Amost-important

Alerts have begun to pile up in the vets-website repository. Once the critical alerts have been dealt with, the high ones are next on the list.

---

### Tasks

- [ ] Resolve all high dependabot alerts

**Comment by rmessina1010** [comment]
The following is a list of dependency upgrades that are complex and will require separate tickets:
(The sub dependencies are  the packages we currently use that are holding us back from updating the  corresponding dependencies)

##### fast-xml-parser vulnerable to Regex Injection via Doctype Entities 
[#112](https://github.com/department-of-veterans-affairs/vets-website/security/dependabot/112
)
0.2.3 >>> 0.4.0
**Sub dependencies:** jsdom@15.2.1, node-sass@4.14.1,request@2.88.2, yo@4.3.0 
***
##### http-cache-semantics vulnerable to Regular Expression Denial of Service 
[#107](https://github.com/department-of-veterans-affairs/vets-website/security/dependabot/107
)
3.8.1 >> 4.1.1
**Sub dependencies:** yo@4.3.0 
***
##### Prototype Pollution in JSON5 via Parse Method 
[#103](https://github.com/department-of-veterans-affairs/vets-website/security/dependabot/103
)
0.5.1 >> 1.0.2
**Sub dependencies:** @babel/core@7.17.7 , @cypress/code-coverage@3.10.0,  babel-plugin-istanbul@6.0.0,
babel-plugin-module-resolver@4.1.0, eslint-plugin-unicorn@35.0.0, file-loader@6.2.0, find-imports@1.1.0, 
null-loader@4.0.1 , stylelint@13.13.1, svg-url-loader@7.1.1 , url-loader@4.1.1, 
***
##### Regular expression denial of service in scss-tokenizer
[#55](https://github.com/department-of-veterans-affairs/vets-website/security/dependabot/55
)
0.2.3 >>> 0.4.3
**Sub dependencies:** node-sass@4.14.1
***
##### Inefficient Regular Expression Complexity in nth-check
[#9](https://github.com/department-of-veterans-affairs/vets-website/security/dependabot/9
)
1.0.2 >> 2.0.1
**Sub dependencies:** enzyme@3.11.0
***
##### Regular Expression Denial of Service (ReDOS)
[#8](https://github.com/department-of-veterans-affairs/vets-website/security/dependabot/8
)
2.0.0 > >3.1.4
**Sub dependencies:** [from yeoman-doctor 5.0.0] yo@4.3.0

**Comment by rmessina1010** [comment]
The following is a list  of tickets  for vulnerabilities  that have no patches or are "ignored",  please note that all these are sub dependencies  of other  packages, and none are direct imports from any VSF or Platform team.

TaffyDB can allow access to any data items in the DB #106
https://github.com/department-of-veterans-affairs/vets-website/security/dependabot/106
No patch…[from jsdoc]
OK to Close??
***
Crash in HeaderParser in dicer #47
https://github.com/department-of-veterans-affairs/vets-website/security/dependabot/47
[from dd-trace 2.4.2]
No patch… sounds severe
OK to Close?
***
node-fetch is vulnerable to Exposure of Sensitive Information to an Unauthorized Actor #27
https://github.com/department-of-veterans-affairs/vets-website/security/dependabot/27
?? Current ver 2.6.7  which is patched??
OK to ignore??

**Comment by rmessina1010** [comment]
The following is a list  of tickets  for vulnerabilities  that have no patches or are "ignored",  please note that all these are sub dependencies  of other  packages, and none are direct imports from any VSF or Platform team.

TaffyDB can allow access to any data items in the DB #106
https://github.com/department-of-veterans-affairs/vets-website/security/dependabot/106
No patch…[from jsdoc]
OK to Close??
***
Crash in HeaderParser in dicer #47
https://github.com/department-of-veterans-affairs/vets-website/security/dependabot/47
[from dd-trace 2.4.2]
No patch… sounds severe
OK to Close?
***
node-fetch is vulnerable to Exposure of Sensitive Information to an Unauthorized Actor #27
https://github.com/department-of-veterans-affairs/vets-website/security/dependabot/27
?? Current ver 2.6.7  which is patched??
OK to ignore??

**Comment by rmessina1010** [comment]
Prototype Pollution in protobufjs #54 , Crash in HeaderParser in dicer #47,  TaffyDB can allow access to any data items in the DB #106 and added to complex tickets list; with the additional caviat that an alternate module may need to be found.
node-fetch is vulnerable to Exposure of Sensitive Information to an Unauthorized Actor #27
(isomorphic-fetch seems to be the problem), research into this

**Comment by rmessina1010** [comment]
I had to perform a manual update,  but  #112 fast-xml-parser  has been updated and merged

**Comment by rmessina1010** [comment]
[Prototype Pollution in JSON5 via Parse Method #102](https://github.com/department-of-veterans-affairs/vets-website/security/dependabot/102) and [Prototype Pollution in JSON5 via Parse Method #103  ](https://github.com/department-of-veterans-affairs/vets-website/security/dependabot/103)seem to be the same issue ( or at least stem from the same root).

This could be resolved by updating babel-plugin-module-resolver@4.1.0 to ^5.0.0,  unfortunately,  that  version is documented as requiring node  >=16. I am creating a corresponding ticket.

**Comment by rmessina1010** [comment]
### Conclusion
All Critical severity  alerts have been successfully resolved.
All but five (5) High Priority alerts have been successfully resolved. 
I have created  individual tickets for each of those.  In general,  updating those  dependencies to non-vulnerable versions will require updating  our repo to Node 16 or above.  In some cases no patch is available and research into alternative dependencies needs to be done.

Closing ticket.
