### ISSUE TITLE
Resolve Low Dependabot Alerts

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#58689]
### Issue Description
https://github.com/department-of-veterans-affairs/vets-website/security/dependabot?q=is%3Aopen+sort%3Amost-important

Alerts have begun to pile up in the vets-website repository. Once the moderate alerts have been dealt with, the low ones are next on the list.

---

### Tasks

- [ ] Resolve all low dependabot alerts

**Comment by rmessina1010** [comment]
Both low level alerts required deeper  attention;

Created tickets: 
https://app.zenhub.com/workspaces/frontend-cop-backlog-6452b043f27c8b0011a25236/issues/gh/department-of-veterans-affairs/va.gov-team/63265

Appended:

**Comment by rmessina1010** [comment]
Both low level alerts required deeper  attention;

Created tickets: 
https://app.zenhub.com/workspaces/frontend-cop-backlog-6452b043f27c8b0011a25236/issues/gh/department-of-veterans-affairs/va.gov-team/63265

Appended:
