### ISSUE TITLE
Findings for spot check a11y review for Medical Device Ordering Tool VA FORM 2346

### ISSUE THREAD

**Issue by mojaray2k** [department-of-veterans-affairs/va.gov-team#5868]
### For reference

**VSA Development Review** - [https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/review-process.md#development-review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/review-process.md#development-review)

## Team Name

Benefits and Memorial 2
## Product/Feature Name
Form 2346 

Introduction, Veteran's Peronsl Info, and Confirm Address Pages.
## Product Description
These pages are the beginning of the application to allow a veteran to order hearing aid batteries and accessoris. 

## Checkpoint Stage

[ ] **Design-Development Intent Checkpoint** (Review design to discuss approach to take with development, identify what components and semantic HTML would be appropriate, identify any accessibility issues and how to address) - This would happen as designs are passed to development, before development begins.

[x ] **Spot Check Review Checkpoint** (Review and follow the steps in the [508 Checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/508-checklist.md) first.) This happens well before launch, so that the 508 office can review and any issues addressed *before* launch.

[ ] **Pre-Launch 508 Review** Once your code is stable in Staging (Review [Pre-Launch 508 Review platform-level documentation](https://github.com/department-of-veterans-affairs/va.gov-team/edit/master/platform/accessibility/508-request-prelaunch-review.md)) **All applications and features on the Veteran-facing Services Platform are required to be accessible and 508 compliant.** This includes adherence to the updated [Section 508](https://www.section508.gov/) standards and the [Web Content Accessibility Guidelines (WCAG)](https://www.w3.org/TR/WCAG20/) Level A and AA success criteria.

## Point of contact

Amen Ra @mojaray2k and @mr0sari0 

## Preferred times for dev intent checkpoint

Any time between 1pm and 3pm

## Staging URL and Credentials

 https://staging.va.gov/hearing-aid-batteries-and-accessories/introduction

## Test Plan

username: vets.gov.user+1@gmail.com

Test URL endpoint: `/hearing-aid-batteries-and-accessories/ `
1. Test this introduction Page
2. Test the Veteran Information Page
3. Test the Confirm Address Page.

## Next steps

1. Accessibility specialist will create an epic in Zenhub to capture issues.

2. Team will coordinate another review after work is updated by @-comment in Zenhub in the Github issue.

3. Once all issues are addressed, the ticket is closed with a final comment, “All issues are addressed”, @-comment developer who opened issue, and close ticket/issue.

**Comment by jenstrickland** [comment]
@wygonikGCIO @mojaray2k I'll be out of office Feb 14 and 17, and will begin this on Feb 18.

**Comment by jenstrickland** [comment]
Use `vets.gov.user+1@gmail.com` to check the prefill. /per Slack thread

**Comment by mojaray2k** [comment]
> Use `vets.gov.user+1@gmail.com` to check the prefill. /per Slack thread

@jenstrickland yes that s the user we are using.

**Comment by jenstrickland** [comment]
Let's hold off on an accessibility spot check review until the team's designers have a chance to take a look, and any changes from usability testing are incorporated. An initial scan revealed the breadcrumbs component is missing and on the Introduction page the h2 needs a utility class applied. Otherwise, it looks like the forms system is using semantic html 🎉 .  As the pages are developed, feel free to ping me on Slack to take a look at anything.

**Comment by leahkeeler** [comment]
HI Jen, Launch date estimated is June 15, 2020. Please let me know if we need to provide anything else. 

Thanks, Leah

**Comment by jenstrickland** [comment]
On the buttons there is a small arrow icon.  These icons should be hidden from screen readers, as they are decorative. This applies to any instance of the arrow icon on the buttons throughout the product.

**Current code**
```html
<span class="button-icon"> »</span>
```

**Recommended code**
```html
<span aria-hidden="true" role="presentation" class="button-icon"> »</span>
```

![Screen Shot 2020-05-12 at 11 30 48 AM](https://user-images.githubusercontent.com/57469/81713573-0e7d4880-9444-11ea-9200-711eaa56164c.png)

**Comment by jenstrickland** [comment]
There is a new method for coding phone numbers on VA.gov, and Robin Garrison just added a PR for a global component. **Consider** adding the aria-label to ensure the screen reader reads the number empathetically. Using a title attribute on links is not recommended. 

**Current code**
```html
<a title="Dial the telephone number 303-273-6200" href="tel:303-273-6200">303-273-6200</a>
```

**Recommended code**
```html
<a aria-label="3 0 3. 2 7 3. 6 2 0 0." href="tel:303-273-6200">303-273-6200</a>
```

**Guidance**
* [I thought title text improved accessibility. I was wrong.](https://silktide.com/blog/2013/i-thought-title-text-improved-accessibility-i-was-wrong)
* [Accessibility and phone number formatting](https://thatdevgirl.com/blog/accessibility-phone-number-formatting)

![Screen Shot 2020-05-12 at 11 32 31 AM](https://user-images.githubusercontent.com/57469/81713793-500df380-9444-11ea-8884-47e3514b831e.png)

**Comment by jenstrickland** [comment]
The date of birth should be spelled out, as [documented in the VA design system](https://design.va.gov/content-style-guide/dates-and-numbers#dates-and-years).

**Current**
Date of birth: 04/05/1933

**Recommended**
Date of birth: April 5, 1933

![Screen Shot 2020-05-12 at 11 43 31 AM](https://user-images.githubusercontent.com/57469/81715124-d4ad4180-9445-11ea-9c71-51692490e7cd.png)

**Comment by jenstrickland** [comment]
Heading levels should only increase by one

The card headings are currently h4, but are not preceded by an h3. **Should** be an h3 and use the utility class to visually style as h4.

**Current code**
```html
<h4 class="review-card--title vads-u-display--inline vads-u-margin--0">Permanent address</h4>
```

**Recommended code**
```html
<h3 class="review-card--title vads-u-display--inline vads-u-margin--0 vads-u-font-size--h4">Permanent address</h3>
```


![Screen Shot 2020-05-12 at 11 48 33 AM](https://user-images.githubusercontent.com/57469/81715729-8c425380-9446-11ea-9d92-7bcc1aa2fc97.png)

**Comment by jenstrickland** [comment]
For the link "Edit permanent address", please remove the `aria-label="Edit permanent address"` as it is unnecessary here because it is identical to the link.

**Current code**
```html
<a class="vads-c-link vads-u-margin-top--1 vads-u-width--auto" 
  aria-label="Edit permanent address" 
  style="min-width: 8rem;">
    Edit permanent address
</a>
```

**Recommended code**
```html
<style>
.review-card--body a.vads-c-link {
  min-width: 8rem; }
</style>
<a class="vads-c-link vads-u-margin-top--1 vads-u-width--auto">
  Edit permanent address
</a>
```

I also moved the inline CSS to a style declaration for re-use and maintainability.

![Screen Shot 2020-05-12 at 11 58 01 AM](https://user-images.githubusercontent.com/57469/81717341-6ae26700-9448-11ea-97bc-94c1d6805974.png)

**Comment by jenstrickland** [comment]
- The container of the radio input options **should** be enclosed by a `role="group"` attribute.
- The email inputs **must** have labels.
- Labels **must** have for attributes that pair with the related input's id attribute.

**Current code**
```diff
<form class="rjsf" novalidate="">
  <div>
-    <div class="input-section schemaform-field-container">
      <div>
        <p class="vads-u-margin-top--2">
          We'll ship your order to the address below. Orders typically arrive within 7 to 10 business days.
        </p>
        <div class="review-card">
          <div class="review-card--header vads-u-background-color--gray-lightest vads-u-padding-top--0 vads-u-padding-x--1 vads-u-display--flex vads-u-justify-content--space-between vads-u-align-items--center vads-u-padding--2" style="min-height: 5rem;">
            <h4 class="review-card--title vads-u-display--inline vads-u-margin--0">
              Permanent address
            </h4>
          </div>
          <div class="review-card--body vads-u-border-color--gray-lightest vads-u-background-color--gray-lightest vads-u-border--2px vads-u-border-top--0 vads-u-padding-x--2 vads-u-padding-bottom--2 vads-u-padding-top--0 vads-u-margin-bottom--1">
            <div class="vads-u-border-left--7px vads-u-border-color--primary">
              <p class="vads-u-margin-left--2 vads-u-margin-top--0">
                101 Example Street<br>
                Apt 2<br>
                Kansas City, MO 64117
                <span class="vads-u-display--block">USA</span>
              </p>
            </div>
-            <a class="vads-c-link vads-u-margin-top--1 vads-u-width--auto" aria-label="Edit permanent address" style="min-width: 8rem;">
              Edit permanent address
            </a>
            <div class="radio-button vads-u-background-color--primary button-dimensions vads-u-color--white vads-u-border-color--primary vads-u-border--2px">
              <input id="permanentAddress" type="radio" checked="">
              <label class="vads-u-font-weight--bold" for="permanentAddress">
                Send my order to this address
              </label>
            </div>
          </div>
        </div>
      </div>
      <div>
        <div class="review-card">
          <div class="review-card--header vads-u-background-color--gray-lightest vads-u-padding-top--0 vads-u-padding-x--1 vads-u-display--flex vads-u-justify-content--space-between vads-u-align-items--center vads-u-padding--2" style="min-height: 5rem;">
            <h4 class="review-card--title vads-u-display--inline vads-u-margin--0">
              Temporary address
            </h4>
          </div>
          <div class="review-card--body vads-u-border-color--gray-lightest vads-u-background-color--gray-lightest vads-u-border--2px vads-u-border-top--0 vads-u-padding-x--2 vads-u-padding-bottom--2 vads-u-padding-top--0 vads-u-margin-bottom--1">
              <div class="vads-u-border-left--7px vads-u-border-color--primary">
                <p class="vads-u-margin-left--2 vads-u-margin-top--0">
                  201 Example Street<br>
                  Galveston, TX 77550
                  <span class="vads-u-display--block">USA</span>
                </p>
              </div>
              <a class="vads-c-link vads-u-margin-top--1 vads-u-width--auto" aria-label="Edit temporary address" style="min-width: 8rem;">
                Edit temporary address
              </a>
              <div class="radio-button vads-u-background-color--white vads-u-color--link-default button-dimensions vads-u-border-color--primary vads-u-border--2px">
                <input id="temporaryAddress" type="radio">
                <label class="vads-u-font-weight--bold" for="temporaryAddress">
                  Send my order to this address
                </label>
              </div>
            </div>
          </div>
        </div>
        <div>
          <div class="schemaform-field-template vads-u-margin-bottom--3 schemaform-first-field">
            <label id="root_email-label" class="schemaform-label" for="root_email">
              <h4>
                Email address
              </h4>
            </label>
            <p>We will send an order confirmation email with a tracking number to this email address.</p>
-            <p>Email address</p>
            <div class="schemaform-widget-wrapper">
              <input type="email" id="root_email" name="root_email" class="va-input-large" value="veteran@gmail.asd">
            </div>
            <div>
            </div>
          </div>
        </div>
        <div>
          <div class="schemaform-field-template">
-            <label id="root_confirmationEmail-label" class="schemaform-label" for="root_confirmationEmail">
              Re-enter email address
            </label>
            <div class="schemaform-widget-wrapper">
              <input type="email" id="root_confirmationEmail" name="root_confirmationEmail" class="va-input-large" value="">
            </div>
            <div>
            </div>
          </div>
        </div>
        <div>
          <div class="schemaform-field-template vads-u-display--none">
-            <label id="root_currentAddress-label" class="schemaform-label" for="root_currentAddress">
-            currentAddress
            </label>
            <div class="schemaform-widget-wrapper">
-            <select id="root_currentAddress" name="root_currentAddress" class="undefined ">                    
-                <option value="permanentAddress">permanentAddress</option>
-                <option value="temporaryAddress">temporaryAddress</option>
-          )}</select>
           </div>
         <div>
         </div>
       </div>
     </div>
   </div>
  </div>
  <div class="row form-progress-buttons schemaform-buttons">
    <div class="small-6 medium-5 columns">
      <button type="button" class="usa-button-secondary null" id="9-continueButton">
-        <span class="button-icon">« </span>Back
      </button>
    </div>
    <div class="small-6 medium-5 end columns">
      <button type="submit" class="usa-button-primary null" id="10-continueButton">
-        Continue<span class="button-icon"> »</span>
      </button>
    </div>
  </div>
  <div>
    <div></div>
    <div>
      <div name="saveFormLinkTop"></div>
      <span>
        <button type="button" class="va-button-link schemaform-sip-save-link">
          Finish this application later
      </button>.
    </span>
  </div>
 </div>
</form>
```


**Recommended code**
```diff
<form class="rjsf" novalidate="">
  <div>
+    <div role="group" class="input-section schemaform-field-container">
      <div>
        <p class="vads-u-margin-top--2">
          We'll ship your order to the address below. Orders typically arrive within 7 to 10 business days.
        </p>
        <div class="review-card">
          <div class="review-card--header vads-u-background-color--gray-lightest vads-u-padding-top--0 vads-u-padding-x--1 vads-u-display--flex vads-u-justify-content--space-between vads-u-align-items--center vads-u-padding--2" style="min-height: 5rem;">
            <h4 class="review-card--title vads-u-display--inline vads-u-margin--0">
              Permanent address
            </h4>
          </div>
          <div class="review-card--body vads-u-border-color--gray-lightest vads-u-background-color--gray-lightest vads-u-border--2px vads-u-border-top--0 vads-u-padding-x--2 vads-u-padding-bottom--2 vads-u-padding-top--0 vads-u-margin-bottom--1">
            <div class="vads-u-border-left--7px vads-u-border-color--primary">
              <p class="vads-u-margin-left--2 vads-u-margin-top--0">
                101 Example Street<br>
                Apt 2<br>
                Kansas City, MO 64117
                <span class="vads-u-display--block">USA</span>
              </p>
            </div>
            <a class="vads-c-link vads-u-margin-top--1 vads-u-width--auto">
              Edit permanent address
            </a>
            <div class="radio-button vads-u-background-color--primary button-dimensions vads-u-color--white vads-u-border-color--primary vads-u-border--2px">
+              <input id="permanentAddress" type="radio" checked="" name="address" value="permanent address">
              <label class="vads-u-font-weight--bold" for="permanentAddress">
                Send my order to this address
              </label>
            </div>
          </div>
        </div>
      </div>
      <div>
        <div class="review-card">
          <div class="review-card--header vads-u-background-color--gray-lightest vads-u-padding-top--0 vads-u-padding-x--1 vads-u-display--flex vads-u-justify-content--space-between vads-u-align-items--center vads-u-padding--2" style="min-height: 5rem;">
            <h4 class="review-card--title vads-u-display--inline vads-u-margin--0">
              Temporary address
            </h4>
          </div>
          <div class="review-card--body vads-u-border-color--gray-lightest vads-u-background-color--gray-lightest vads-u-border--2px vads-u-border-top--0 vads-u-padding-x--2 vads-u-padding-bottom--2 vads-u-padding-top--0 vads-u-margin-bottom--1">
              <div class="vads-u-border-left--7px vads-u-border-color--primary">
                <p class="vads-u-margin-left--2 vads-u-margin-top--0">
                  201 Example Street<br>
                  Galveston, TX 77550
                  <span class="vads-u-display--block">USA</span>
                </p>
              </div>
              <a class="vads-c-link vads-u-margin-top--1 vads-u-width--auto" aria-label="Edit temporary address" style="min-width: 8rem;">
                Edit temporary address
              </a>
              <div class="radio-button vads-u-background-color--white vads-u-color--link-default button-dimensions vads-u-border-color--primary vads-u-border--2px">
+                <input id="temporaryAddress" type="radio" name="address" value="temporary address">
                <label class="vads-u-font-weight--bold" for="temporaryAddress">
                  Send my order to this address
                </label>
              </div>
            </div>
          </div>
        </div>
        <div>
          <div class="schemaform-field-template vads-u-margin-bottom--3 schemaform-first-field">
            <label id="root_email-label" class="schemaform-label" for="root_email">
              <h4>
                Email address
              </h4>
            </label>
            <p>We will send an order confirmation email with a tracking number to this email address.</p>
+            <label for="root_email">Email address</label>
            <div class="schemaform-widget-wrapper">
              <input type="email" id="root_email" name="root_email" class="va-input-large" value="veteran@gmail.asd">
            </div>
            <div>
            </div>
          </div>
        </div>
        <div>
          <div class="schemaform-field-template">
+            <label for="root_confirmationEmail-label" class="schemaform-label" for="root_confirmationEmail">
              Re-enter email address
            </label>
            <div class="schemaform-widget-wrapper">
              <input type="email" id="root_confirmationEmail" name="root_confirmationEmail" class="va-input-large" value="">
            </div>
            <div>
            </div>
          </div>
        </div>
        <div>
+ <!-- these items are for the schema, I believe -->
          <div class="schemaform-field-template vads-u-display--none">
+            <label for="root_currentAddress-label" class="schemaform-label" for="root_currentAddress">
-            currentAddress
            </label>
            <div class="schemaform-widget-wrapper">
-            <select id="root_currentAddress" name="root_currentAddress" class="undefined ">                    
-                <option value="permanentAddress">permanentAddress</option>
-                <option value="temporaryAddress">temporaryAddress</option>
-          )}</select>
           </div>
         <div>
         </div>
       </div>
     </div>
   </div>
  </div>
  <div class="row form-progress-buttons schemaform-buttons">
    <div class="small-6 medium-5 columns">
      <button type="button" class="usa-button-secondary null" id="9-continueButton">
        <span aria-hidden="true" role="presentation" class="button-icon">« </span>Back
      </button>
    </div>
    <div class="small-6 medium-5 end columns">
      <button type="submit" class="usa-button-primary null" id="10-continueButton">
        Continue<span  aria-hidden="true" role="presentation" class="button-icon"> »</span>
      </button>
    </div>
  </div>
  <div>
    <div></div>
    <div>
      <div name="saveFormLinkTop"></div>
      <span>
        <button type="button" class="va-button-link schemaform-sip-save-link">
          Finish this application later
      </button>.
    </span>
  </div>
 </div>
</form>
```


**Guidance**
* [MDN Using the group role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_group_role)
* [W3C WCAG 2.0 - ARIA17: Using grouping roles to identify related form controls](https://www.w3.org/TR/WCAG20-TECHS/ARIA17.html)


![Screen Shot 2020-05-12 at 12 06 57 PM](https://user-images.githubusercontent.com/57469/81717893-1f7c8880-9449-11ea-902e-342f3c00d9e6.png)

**Comment by jenstrickland** [comment]
Heading levels should only increase by one

**Current code**
`<h4>Select the hearing aids that need batteries</h4>`

**Recommended code**
`<h3 class="vads-u-font-size--h4">Select the hearing aids that need batteries</h3>`


![Screen Shot 2020-05-12 at 12 53 21 PM](https://user-images.githubusercontent.com/57469/81722588-961c8480-944f-11ea-8a91-de74f1ef2b98.png)

**Comment by jenstrickland** [comment]
The link for `Find contact information for your local VA medical center` should open in a new tab, to prevent losing user's data.

**Current code**
```html
<a href="https://www.va.gov/find-locations/?_ga=2.149519669.2053714992.1589203977-1336706735.1575487663">Find contact information for your local VA medical center</a>
```

**Recommended code**
```html
<a href="https://www.va.gov/find-locations/?_ga=2.149519669.2053714992.1589203977-1336706735.1575487663" target="_blank" rel="noopener noreferrer">Find contact information for your local VA medical center</a>
```


![Screen Shot 2020-05-12 at 12 55 48 PM](https://user-images.githubusercontent.com/57469/81722834-f9a6b200-944f-11ea-8ee6-c093a08b5da4.png)
![Screen Shot 2020-05-12 at 12 55 56 PM](https://user-images.githubusercontent.com/57469/81722836-fa3f4880-944f-11ea-86d1-4905d52cbd20.png)

**Comment by jenstrickland** [comment]
`<dl>` elements must only directly contain properly-ordered `<dt>` and `<dd>` groups, `<script>` or `<template>` elements.

There is a `<p>` tag in the `<dl>` and there should not be.

Issue location: `<dl class="review">`
Related node: `.vads-u-margin-top--2`

![Screen Shot 2020-05-12 at 1 07 44 PM](https://user-images.githubusercontent.com/57469/81723938-96b61a80-9451-11ea-89bd-38ac61524da5.png)

**Comment by jenstrickland** [comment]
Heading levels should only increase by one

**Current code**
`<h5 class="form-review-panel-page-header">Shipping address</h5>`

**Recommended code**
`<h3 class="form-review-panel-page-header vads-u-font-size--h5">Shipping address</h3>`

**Comment by jenstrickland** [comment]
Focus outline should not be applied to non-interactive focusable content, as a pattern on VA.gov.


![Screen Shot 2020-05-12 at 1 10 26 PM](https://user-images.githubusercontent.com/57469/81724214-fd3b3880-9451-11ea-9b1d-bb64debc7ff7.png)

**Comment by jenstrickland** [comment]
When zoomed to 400% at 1280, the button exceeds the card edge. 


![Screen Shot 2020-05-12 at 1 16 22 PM](https://user-images.githubusercontent.com/57469/81724696-d2051900-9452-11ea-8d70-81704b619c22.png)

**Comment by jenstrickland** [comment]
@leahkeeler Spot check is complete. Let me know if you'd like me to write these up as issue tickets, instead of the comments provided.

**Comment by leahkeeler** [comment]
@jenstrickland Thank-you for finishing this - I think this is fine, no need to spend extra time writing up. I know how busy you are. 

Thanks again, Leah

**Comment by bradl3yC** [comment]
Finding 1 - The Arrow in the button is in platform code and part of the form system
Finding 3 - The heading level for permanent address is also part of the form system
Finding 5 - Shipping address is also being passed in to the form system so we do not have direct access to its heading levels.
Finding 6 - Review Page focus is being set as a part of the ReviewPage component within form system 
```
class ReviewPage extends React.Component {
  componentDidMount() {
    scrollToTop();
    focusElement('h2');
  }
```

The rest of the fixes are included in PR https://github.com/department-of-veterans-affairs/vets-website/pull/12656

**Comment by bradl3yC** [comment]
@leahkeeler @jenstrickland

**Comment by jenstrickland** [comment]
> Finding 1 - The Arrow in the button is in platform code and part of the form system
> Finding 3 - The heading level for permanent address is also part of the form system
> Finding 5 - Shipping address is also being passed in to the form system so we do not have direct access to its heading levels.
> Finding 6 - Review Page focus is being set as a part of the ReviewPage component within form system
> 
> ```
> class ReviewPage extends React.Component {
>   componentDidMount() {
>     scrollToTop();
>     focusElement('h2');
>   }
> ```
> 
> The rest of the fixes are included in PR [department-of-veterans-affairs/vets-website#12656](https://github.com/department-of-veterans-affairs/vets-website/pull/12656)

@1Copenut - Are you aware of techniques for addressing the accessibility issues in the forms system components for individual teams' deliverables?

**Comment by bradl3yC** [comment]
@jenstrickland these heading levels are hard coded in the form system components.  We pass in a title and schema and thats it.  We don't have any recourse to change these from the form config.

**Comment by jenstrickland** [comment]
@bradl3yC I understand. I believe I've seen some devs change these structures (@Mottie, for example), so I wonder if there's something different they're doing.

**Comment by bradl3yC** [comment]
@jenstrickland my worry is that, If I change them to fix my form, that it will break a11y for others.  We need a way to set these heading levels within the form config so they're dynamic.

**Comment by jenstrickland** [comment]
@bradl3yC I went back through the list of findings and added a Finding #, and then listed them below. I started putting an * in front of those you've listed as forms system. Would you please edit this comment to add an asterisk in front of the items you're referring to? I think the numbering may be off, and I want to be sure we're all talking about the same things (I have @Mottie @rianfowler @1Copenut looking into the forms system stuff). Thanks! 😄 


1. * Finding 1 - On the buttons there is a small arrow icon. These icons should be hidden from screen readers, as they are decorative.
1. Finding 2 - New method for coding phone numbers on VA.gov, and Robin Garrison just added a PR for a global component. Consider adding the aria-label to ensure the screen reader reads the number empathetically. Using a title attribute on links is not recommended.
1. Finding 3 - The date of birth should be spelled out, as documented in the VA design system.
1. * Finding 4 - Heading levels should only increase by one - The card headings are currently h4, but are not preceded by an h3. Should be an h3 and use the utility class to visually style as h4. On this page, the change should apply to both Permanent and Temporary address cards.
1. Finding 5 - For the link "Edit permanent address", please remove the aria-label="Edit permanent address" as it is unnecessary here because it is identical to the link.
1. Finding 6 
    - The container of the radio input options should be enclosed by a role="group" attribute.
    - The email inputs must have labels.
    - Labels must have for attributes that pair with the related input's id attribute.
1. Finding 7 - Heading levels should only increase by one - This issue repeats on multiple pages.
    Current code `<h4>Select the hearing aids that need batteries</h4>`
1. Finding 8 - The link for Find contact information for your local VA medical center should open in a new tab, to prevent losing user's data.
1. Finding 9 - `<dl>` elements must only directly contain properly-ordered `<dt>` and `<dd>` groups, `<script>` or `<template>` elements. There is a `<p>` tag in the `<dl>` and there should not be.
1. Finding 10 - Heading levels should only increase by one - Current code: `<h5 class="form-review-panel-page-header">` Shipping address `</h5>`
1. Finding 11 - Focus outline should not be applied to non-interactive focusable content, as a pattern on VA.gov.
1. Finding 12 - When zoomed to 400% at 1280, the button exceeds the card edge.

**Comment by Mottie** [comment]
@bradl3yC I _may_ have fixed most of those heading issues in the PRs I've been working on:

- https://github.com/department-of-veterans-affairs/vets-website/pull/12449 - lots of fixes to the dl/dt/dd wrapping
- https://github.com/department-of-veterans-affairs/vets-website/pull/12654 - mostly 526 headers, but does add another fix to the file upload component

**Comment by bradl3yC** [comment]
@jenstrickland @leahkeeler I fixed most of those in the PR I messaged you about yesterday - most of the tickets created may be superfluous - Updated with asterisks as requested.  The fixes for the non-VAFS stuff is currently on staging

**Comment by jenstrickland** [comment]
@bradl3yC @leahkeeler I created the tickets at the request of @rianfowler, so that the forms system folks will address them in upcoming work. 

I'm not able to see the PR until it gets to staging, due to lack of SOCKS access until the VAMC locations open up again. What is "non-VAFS"? I tried to find it in the DSVA /wtf bot, but it came up empty. :(

**Comment by bradl3yC** [comment]
@jenstrickland VAFS = Forms system.  The changes I merged are in staging as of this morning.

**Comment by jenstrickland** [comment]
Since this was a spot check, the findings provided are for the BAM2 team to validate. This is a health check, generally done well ahead of requesting a staging review.

Ahead of the staging review, the team should certify they've completed their own accessibility testing on the staging review request. I recommend editing the staging review request ticket to include the [checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/vsa-accessibility-test-cases-checklist.md), and then check each of the items as a team. The checklist is generally more straightforward, compared to the TestRail or separate Github Markdown file. 

The five tickets written on this epic are the responsibility of VSP and the forms team.

**Comment by bradl3yC** [comment]
Issue #6 - CurrentAddress select option is wrapped in a display none - this is done to have an entry in state necessary for keeping selectedAddress components aware of which radio button is selected
