### ISSUE TITLE
Edits to PL section of style guide

### ISSUE THREAD

**Issue by megzehn** [department-of-veterans-affairs/va.gov-team#58680]
We need to make these edits to the style guide in the PL section, per BP: 

- Main top 10 page: https://design.va.gov/content-style-guide/plain-language/
There are a couple periods underlined where we have linked standards in the top 10 list. Can you remove the underlining for the periods for the first and third bullets?

- Can you break this sentence into 2 in the "Use pronouns" bullet?: For example, address the Veteran as an individual with “you” and ”your.” Refer to VA with “we” and “our.”

- For the last bullet: Structure your content so it’s easy to follow... can you add a bit to the parenthetical that's just "subway map" right now?: (like our design system's subway map)
https://design.va.gov/content-style-guide/plain-language/don-t-use-jargon: the second "Like this" is missing the article "a" before "Veterans Law Judge."

- Use short sentences: https://design.va.gov/content-style-guide/plain-language/use-short-sentences
For the little description above the examples, can you add to that second sentence, so it says: "You can also start a sentence with a conjunction (and, or, but), especially when you want to emphasize the information that follows the conjunction."

**Comment by RLHecht** [comment]
This work is complete. Closing!
