### ISSUE TITLE
STEM: Conduct Accessibility Testing

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#5869]
As a MVP development team, I need to request an Accessibility/508 review as part of the pre-launch activities in support of the Build and Test phase.

Assumptions:
1. The Accessibility and 508 compliance process is documented in GitHub: https://github.com/department-of-veterans-affairs/vets.gov-team/blob/ead0fe129bfee6b8e7eaae59d7f4f681a37dec15/Practice%20Areas/Accessibility/Readme.md
2. For support on executing the feature flow using keyboard strokes only, see the WebAIM keyboard accessibility guide for keyboard strokes. - zoom browser to 400% and verify that the layout is still meaningful and the feature is still usable (see WCAG guide for understanding reflow)
3. The feature flow has been completed on vets.gov supported browsers with the most commonly used screenreader(s) (see for example 2017 WebAIM screenreader survey)
4. End to End manual testing scripts are captured here: https://confluence.boozallencsn.com/display/VACM/4142%3A+End+to+End+Testing
6. How to access Safari Voice Over: https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Work%20Practices/Accessibility%20and%20508/Mac_VoiceOver_guide.md
7. The final/complete build has been deployed to staging
8. All parts of the form are present and working correctly in the flow
9. Tester has access to most common browsers including: Chrome, Safari, IE 11, Firefox. -- This could be using an external tool like Browserstack or a Virtual Machine
10. Tester can access mobile simulation and desktop formats

Acceptance Criteria:
1. The updates to the 22-1995 related to STEM have been evaluated and run through from beginning to end with no errors or problems on most common browsers and formats.

Tasks:

 [ ] Ensure that all changes are deployed to Staging as part of the all claims flow before being testing
 [ ] Test with Voice Over
 [ ] Test with JAWS
 [ ] Test with NVDA
 [ ] Test with Axe

**Comment by delli-gatti-michael** [comment]
Tested by Test Case
https://dsvavsp.testrail.io/index.php?/tests/view/1234&group_by=cases:section_id&group_order=asc&group_id=51

**Comment by delli-gatti-michael** [comment]
Form Test Case
https://dsvavsp.testrail.io/index.php?/cases/view/295&group_by=cases:section_id&group_order=asc&group_id=51

**Comment by delli-gatti-michael** [comment]
Accessibility testing is complete 

Defect found:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/6290
