### ISSUE TITLE
Spacing issue on past appointment list

### ISSUE THREAD

**Issue by Cieramaddox** [department-of-veterans-affairs/va.gov-team#58700]
## Summary
Spacing is off (too tight) above the H2 **month** header on the **past** appointment list

## Specs
- Device: Mobile, Tablet and Desktop
- Browser: Google Chrome

## Steps to Reproduce
Background: the `va_online_scheduling_appointment_list` toggle is on
Test user: Judy Morrison
Go to: https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/past?postLogin=true

#### Mobile view

<img width="309" alt="Screenshot 2023-05-18 at 10 58 43 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/92750161/532a2332-7e92-4f06-ab24-2c30af445f14">

#### Tablet view

<img width="580" alt="Screenshot 2023-05-18 at 10 58 56 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/92750161/f29aceb0-9271-4fca-a754-177089861c3d">

#### Desktop view

<img width="971" alt="Screenshot 2023-05-18 at 10 59 01 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/92750161/433c7898-cf6d-4c45-826e-3ed9cbfbca5e">
______________________________________________________________________________________________________________

## Desired Result

Spacing above month header should be 32px.

#### Mobile view

<img width="289" alt="Screenshot 2023-05-18 at 11 56 52 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/92750161/af89cc03-343b-4d3c-9e0c-15b1c56188c2">

#### Tablet view

<img width="577" alt="Screenshot 2023-05-18 at 11 56 40 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/92750161/7f69e4bd-cc72-4580-a738-c6b2c6ba64a2">

#### Desktop view

<img width="867" alt="Screenshot 2023-05-18 at 11 56 18 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/92750161/2d02f429-bc4d-43bf-96b0-622aa482ccf8">

## Definition of Done
- [ ] Spacing is updated to 32px

**Comment by ldelacosta** [comment]
@Cieramaddox - this. ticket is ready to be validated in staging. Please let us know if you run into any issues. Thanks!
