### ISSUE TITLE
Sidekiq Admin UI Access Request

### ISSUE THREAD

**Issue by gia-lexa** [department-of-veterans-affairs/va.gov-team#58717]
#### Access to the Sidekiq Admin UI is managed through a GitHub Teams per environment via the following teams: 
- [Dev](https://github.com/orgs/department-of-veterans-affairs/teams/va-gov-sidekiq-dev)
- [Staging](https://github.com/orgs/department-of-veterans-affairs/teams/va-gov-sidekiq-staging)
- [Sandbox](https://github.com/orgs/department-of-veterans-affairs/teams/va-gov-sidekiq-sandbox)
- [Prod](https://github.com/orgs/department-of-veterans-affairs/teams/va-gov-sidekiq-prod)

_Please provide your GitHub username to be added to that team, along with a reason access is required and which environments you're requesting access to._

- GitHub username:  gia-lexa
- Reason access is required: Access is required for my upcoming Backend On-Call shifts
- Environments requesting access to: All, thank you!

**Comment by ryan-mcneil** [comment]
Platform Team 🤖   - Providing ongoing Access to each environment. 

@gia-lexa - Access Granted ✅
