### ISSUE TITLE
Design Intent - IA Feedback - BAH-MBS-SelfServ, Pre-Need Self Service, Pre-Need modernization and CaMEO Integration

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#58714]
## VFS actions
- [x] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [x] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [x] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [x] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [x] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- Thank you so much for walking us through the background to this product & drawing up these user flows - they are such a critical tool for us! Really appreciate it.
- I also see some really great content updates to this form in your prototype! We do have a team that provides support on content, a11y, and IA, (CAIA) and we encourage you to [submit an intake ticket with them](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Sitewide+Content%2C+RLHecht&labels=sitewide+content%2C+sitewide+content-product+support&template=sitewide-content-intake-form.md&title=%3CType+of+Request%3E+from+%3CTeam%3E) when it makes sense. Thank you!

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- Consider: I posed a question during the meeting around whether you'd thought about grouping form field information for a single type of person (applicant, decedent, etc.). For example, the "Applicant info" section has personal identification information in it. But a later section called "contact information" also asks for applicant information, and it is 4 steps removed from the prior one. Is there ux value in putting those together? Before considering any changes, it may be valuable to sync with @humancompanion-usds who mentioned in the meeting that one of his teams (digitizing forms team) is considering making some patterns around this. 
- Consider: you have the "happy path" user flow prototyped, but I wonder if user testing a more complex flow would reveal insights that you won't otherwise get to. I am specifically curious how the term "sponsor" in the form language will land with users, but that won't display in this happy-path scenario. Just something to consider.

**Comment by ccruzgra** [comment]
@sterkenburgsara Thanks so much for your helpful feedback! We are interested in exploring grouping the sections of the form differently to make it easier for users to get through so we will be following up on that.

**Comment by humancompanion-usds** [comment]
@ccruzgra - Talk to @jeana-adhoc or @PSIEBENLIST on the Veteran-facing Forms team for help with how we're building out patterns in our forms work.

**Comment by ccruzgra** [comment]
I spoke to @jeana-adhoc and got some great advice regarding form flows. We will be incorporating what's possible into our form depending on technical feasibility.
