### ISSUE TITLE
AWS Access for [Ben Allen]

### ISSUE THREAD

**Issue by ben-allen-oddball** [department-of-veterans-affairs/va.gov-team#58723]
### COR Name

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Benjamin Allen

### Your Email

ben.allen@odball.io

### Team, Role, and Company of the target individual

Platform TT2, DevOps, Oddball

### Product Manager (PM) name and email

Nate Peterson, nate.peterson@adhocteam.us

### Product Owner (PO) name and email

Mike Chelen, michael.chelen@va.gov

### Desired AWS Access

Please copy from Kyle Matheny, kyle.matheny@oddball.io

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

![Screenshot from 2023-05-19 07-36-50](https://github.com/department-of-veterans-affairs/va.gov-team/assets/132920583/d56d6948-0598-4d62-8c52-2e283444eed8)

### Additional Notes

COR: Bates, Bertina B <Bertina.Bates@va.gov>

### User must exist in a roster before AWS access can be granted

- [ ] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [x] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by BillChapmanUSDS** [comment]
Access Granted, Production if necessary is still 3 month limited

**Comment by flooose** [comment]
This is taken care of. I've asked Ben directly.
