### ISSUE TITLE
STEM: Cross-Browser Testing

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#5872]
As a MVP development team, I need to conduct cross browser testing as part of the pre-launch activities in support of the Build and Test phase.

Assumptions:
Requirements for cross browser testing are located in GitHub: https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/DeveloperDocs/testing/cross-browser-manual-testing.md
The final/complete build has been deployed to staging
All parts of the form are present and working correctly
Tester has access to most common browsers including: Chrome, Safari, IE 11, Firefox. This could be using an external tool like Browserstack or a Virtual Machine
Tester can access mobile simulation and desktop formats
End to End test script exists here: [INSERT LINKS]

Acceptance Criteria:
1. The 22-1995 with STEM-related updates has been tested and run through from beginning to end with no errors or problems on most common browsers and formats.

Tasks
- [x] Ensure that all changes are deployed to Staging before being testing
- [x] Test form end to end on Chrome
- [x] Test form end to end on Firefox
- [x] Test form end to end on Safari
- [x] Test form end to end on IE 11
- [x] Test form end to end on Edge
- [x] Test form end to end on Mobile
- [x] Test form using google's responsive features.

**Comment by sonntag-adam** [comment]
Testing passes https://dsvavsp.testrail.io/index.php?/runs/view/181&group_by=cases:section_id&group_order=asc

**Comment by delli-gatti-michael** [comment]
Cross-browser testing complete with no browser-specific issues found.

TestRail test run:
https://dsvavsp.testrail.io/index.php?/tests/view/1288&group_by=cases:section_id&group_order=asc&group_id=51
