### ISSUE TITLE
Design Intent - Accessibility Feedback - Authenticated Experience, Profile, Notification Settings - Default Send Functionality

### ISSUE THREAD

**Issue by briandeconinck** [department-of-veterans-affairs/va.gov-team#58790]
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- All of this is great! All of my feedback is pretty small stuff, you're in great shape here.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- **Must:** For the "Add to your profile" and "Update" links for phone numbers and email addresses, make the link text more explicit about what contact information is being added/updated, eg. "Add email address to your profile" and "Update phone number." If I'm a screen reader user tabbing through the page or I have my screen reader announce a list of links on the page, I'll hear those links out of context and won't know what I'm adding or updating. You could also use `aria-label` or even `aria-describedby` but for links this simple I think it makes sense to just adjust the visible link text and call it a day rather than over-engineer.
- **Conditional Must:** There was some discussion of making these toggles instead of checkboxes. I don't have an opinion on that either way. But if you decide to try that route, there's no toggle in the design system---so you'll need to build your own and make it accessible! Some resources for both code and design inspiration:
   - Heydon Pickering's [Inclusive Components on toggle buttons](https://inclusive-components.design/toggle-button/)
   - Adrian Roselli's [Under-Engineered Toggles](https://adrianroselli.com/2019/03/under-engineered-toggles.html) and [Under-Engineered Toggles Too](https://adrianroselli.com/2019/08/under-engineered-toggles-too.html)
   - Sara Soueidan's [On Designing and Building Toggle Switches](https://www.sarasoueidan.com/blog/toggle-switch-design/)
   - Kitty Giraudel's [An accessible toggle](https://kittygiraudel.com/2021/04/05/an-accessible-toggle/)
- **Should:** This might be a little outside the scope of what we look at in a Design Intent, but since we were looking at the CodePen prototype I wanted to test auto-saving with a screen reader. When I test with NVDA it behaves a little differently than I would expect. I'm not getting the announcement that the change has saved until after I tab away from the checkbox I've changed. That could be a weird CodePen thing or something on my end, but I would recommend double-checking this with an accessibility specialist as code is committed to the actual product.
- **Consider:** I don't love auto-save functionality because it's tricky to get right for screen reader users and it introduces the possibility of accidental errors (see [WCAG 3.3.4](https://www.w3.org/WAI/WCAG21/Understanding/error-prevention-legal-financial-data.html) and its stronger version, [WCAG 3.3.6](https://www.w3.org/WAI/WCAG21/Understanding/error-prevention-all.html)). Given the technical constraints you described, I think it makes sense here and putting `role="alert"` on the success alerts is a good solution. But if you ever discover a way to make it smooth and practical to have a two-click solution (check the box, submit with a button) that's probably going to be my preference.

**Comment by mtcA6** [comment]
For the MUST, we're updating things with #58890
Conditional Must we're not incorporating a toggle so we're going to ignore that item 

For should and consider, I'll circle back.
