### ISSUE TITLE
GIDS: Staging 405 method not allowed when matching IPEDS HD

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#5880]
Steps to reproduce:

1. Navigate to https://staging.va.gov/gids/crosswalk_issues/partials/find_matches/35589
2. Select "Match" for any institution
3. Receive error 405 Method Not Allowed
Code: MethodNotAllowed
Message: The specified method is not allowed against this resource.
Method: POST
ResourceType: OBJECT
RequestId: 8BC74B623B2AD5A2
HostId: GKYkrAaG2M8KfYjkvTvF+T6ZsRmrL6k1T4iA+bsZxKd4UAbZHHghTHbYvHrcyv6ctCstHtEb8Xk=
##

![Screen Shot 2020-02-14 at 11.14.50 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/60efa2a4-f8b0-4b97-8ef2-48dff4a829ce)

**Comment by hughes-dustin** [comment]
branch: bah-form-path-5726 
PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/577

**Comment by sonntag-adam** [comment]
Able to match locally

**Comment by sonntag-adam** [comment]
In staging, error resolved.
