### ISSUE TITLE
Analytics KPI dashboard update request for [Governance] - CMS Repo Data

### ISSUE THREAD

**Issue by it-harrison** [department-of-veterans-affairs/va.gov-team#58818]
# Request an update to your KPI Dashboard  

## What this form is for

Use this ticket template to request an update to your existing KPI dashboard. To request a new product be added to our dashboards, please use [Request a New Standardized KPI Dashboard template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&template=analytics-request-kpi-dashboard.md&title=Analytics+KPI+dashboard+request+for+%5BTeam%5D).

### Expected delivery timelines

Once you’ve submitted this ticket template, your KPI dashboard update request will be pulled into the Analytics team’s workflow the following Wednesday during Platform Sprint Planning or Refinement. We expect to deliver your completed dashboard within the next sprint. 

## Instructions for the VFS team
First, tell us what type of change you need to make:

- [ ] Change basic product info
- [ ] **Forms**: funnel changes
- [ ] **Content**: Add or remove pages included
- [x] Other: Governance Team would like to see a Big Query table pulled into Domo that duplicates what is done for the `va.gov-team` repo but for the **`va.gov-cms`** repo.  Some background: usually Collaboration Cycle Staging Review tickets are logged in the `va.gov-team` repo but occasionally they are logged in the `va.gov-cms` (due to the nature of the product under review).  In order to get a complete picture of Staging Review issues we want to make sure to include all tickets. 

Next, use the original [KPI request template](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit#gid=981224988) or [(downloaded Excel version)](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/1586823275/KPI%20Dashboard%20Product%20Details%20Template%20-%20MAKE%20A%20COPY.xlsx?inst-v=ced1f4dd-e997-4aa2-9ae8-2cebe369b42f) you filled out to update your information. If you are not able to find that spreadsheet, reach out to the Analytics team on #vfs-platform-support for a new spreadsheet that reflects what we currently have on file.

- [ ] Make a copy of the [Google Sheet](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit#gid=981224988) [(or download Excel version)](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/1586823275/KPI%20Dashboard%20Product%20Details%20Template%20-%20MAKE%20A%20COPY.xlsx?inst-v=ced1f4dd-e997-4aa2-9ae8-2cebe369b42f)
- [ ] Complete worksheet as instructed
- [ ] Link your completed spreadsheet here: ______
- [ ] Check your sharing settings to make sure the Analytics team will be able to access it
- [ ] Add your team label to follow progress

**Additional Info**

- Please use the [KPI Framework](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/Analytics%20Playbook/va-gov-platform-analytics-kpi-framework.pdf) for more information on the metrics used in the KPI dashboards. 
- If you need any analytics support, read through the [How to request Analytics support](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guidelines.1586823275.html#Analyticscustomersupportguidelines-4.RequestaKPIDashboardinDomo).
- If you do not have Domo access, please [request access here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+access-request&template=analytics-request-google-analytics-domo-access.md&title=Request+access+to+Google+Analytics+and%2For+Domo).

**Comment by michelle-dooley** [comment]
@it-harrison - Is this in reference to GH Issues dataset?  You want to have va.gov-cms repo data added to it? Do you have any more info on how/where we would get that data?  Apologize I am not really familiar with other repo datat.

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/93597659/488e5b42-60d8-4d60-9c49-d258d111a298)

**Comment by it-harrison** [comment]
@michelle-dooley Yes, we want to bring GH data from the `va.gov-cms` repo into Big Query for import into Domo. I looked at the settings on the `va.gov-team` repo for comparison and didn't see a webhook set up to feed data to Big Query so I'm not sure how that is working but I assumed it could be duplicated. If it's easier, we don't need you to merge the GH datasets in Big Query, we could do that in Domo.

**Comment by michelle-dooley** [comment]
@it-harrison - this is going to require updates to the GH source code that I do not own or manage.  I am working on another request that also requires updates to this code.  Unfortunately there is no longer a "real" owner of this data but I was able to find out that Ryan on Tech Team 1 is familiar with and can make updates to the code but it requires a ticket be submitted and prioritized by that team first in order for us to be able to access that data.  Can you please submit this data request ticket to that team to kick this off.

**Comment by it-harrison** [comment]
@michelle-dooley Thanks Michelle, will do.

**Comment by laineymajor** [comment]
I'm going to add this to the backend CoP... and see when @rjohnson2011 can work this (or if someone else has the capacity).

**Comment by rjohnson2011** [comment]
There is now a `github_issues_cms` BigQuery table populated with vets-cms data.
