### ISSUE TITLE
[Platform IaC] Standardizing Tags and Names with terraform-null-label module

### ISSUE THREAD

**Issue by hgbarreto** [department-of-veterans-affairs/va.gov-team#58836]
## Description
In order to enforce the standardization of names and tags, the team has decided to use the terraform-null-label module. More information about this module can be found [here](https://github.com/cloudposse/terraform-null-label) 

## Resources 
- Previous Slack discussion [here](https://oddball.slack.com/archives/C044WM9PBMY/p1684344931123699)
- This ticket was generated from the work done in https://github.com/department-of-veterans-affairs/va.gov-team/issues/57554

## Acceptance Criteria
- [ ] terraform-null-label module implemented
- [ ] documentation 

## Refinement Guidance - Check the following before working on this issue: 
- [x] _Team label assigned ("platform-tech-team-2")_
- [x] _Epic assigned (if needed)_ 
- [x] _Estimated (points assigned)_
- [x] _Sprint assigned (once planned)_
- [x] _Team member(s) assigned_

**Comment by ben-allen-oddball** [comment]
Still need to resolve some conflicts and testing of colisions with AWS provider default tags and tags specified in resources.

**Comment by ben-allen-oddball** [comment]
Tested for colisions.  No problems.   Implemented inside the EKS modules.
