### ISSUE TITLE
Identity Dashboard (FE) - Set up CI/CD and Github Actions

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#58853]
## Issue Description
Set up a Github Actions (GHA runners) to perform linting, testing, and building (build should have a versioning setup)

https://github.com/department-of-veterans-affairs/identity-dashboard-fe

## Acceptance Criteria
- [x] Set up a new Github Action that does the following
  - [x] Performs linting (in accordance with vets-website ESLint rules)
     - [x] Failures, stop the flow
     - [x] Success, continue
  - [x] Performs unit testing with new test runners
    - [x] Failure, stop the flow
    - [x] Success, continue
  - [x] Perform final build
    - [x] Failure, stop the flow
    - [x] Success, continue
- [x] Successful flow should update the versioning release

**Comment by aparsley** [comment]
Looks great, thank you for attaching the Github page with read.me.
