### ISSUE TITLE
Sitewide content support for Login.gov CLP

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#58893]
## Issue Description
Sofia from Login.gov adoption team shared a content doc for a CLP landing page. We'll provide some comments in the doc and work with their team to align content on VA.gov and the CLP.

---
## Tasks
- [x] Review CLP and provide feedback

## Acceptance Criteria
- [x] Feedback shared with LGA team

**Comment by laurwill** [comment]
Noting I passed some initial questions and comments to Sofia in [this document](https://docs.google.com/document/d/1tvWiMseA519miCizMNC8nStDwBRwYOqSObaQmmrtnFE/edit). We'll plan to talk more about this as part of our identity syncs later this week.

**Comment by RLHecht** [comment]
@laurwill is this good to close? I heard on ToT that their CLP is live, but I wasn't sure if we're still making edits.

**Comment by laurwill** [comment]
Yes! we can close — I provided some initial feedback and we'll consult as needed on additions to the page.

**Comment by RLHecht** [comment]
Closing this.
