### ISSUE TITLE
Address security advisory 1065

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#589]
@ncksllvn commented on [Mon Jul 15 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19253)

In this [pull request](https://github.com/department-of-veterans-affairs/vets-website/pull/10413), we added a security exception for this [advisory](https://www.npmjs.com/advisories/1065). We should investigate if we can upgrade our dependencies (especially in Formation) to truly fix this, and then remove the exception. Sample output:

```
Security advisory:

  Title: Prototype Pollution

  Module name: lodash

  Dependency: lodash

  Path: lodash

  Severity: high

  Details: https://npmjs.com/advisories/1065

      



Security advisory:

  Title: Prototype Pollution

  Module name: lodash

  Dependency: @department-of-veterans-affairs/formation-react

  Path: @department-of-veterans-affairs/formation-react>lodash

  Severity: high

  Details: https://npmjs.com/advisories/1065

      



Security advisory:

  Title: Prototype Pollution

  Module name: lodash

  Dependency: react-leaflet

  Path: react-leaflet>lodash

  Severity: high

  Details: https://npmjs.com/advisories/1065

      



Security advisory:

  Title: Prototype Pollution

  Module name: lodash

  Dependency: redux

  Path: redux>lodash

  Severity: high

  Details: https://npmjs.com/advisories/1065
```

---

@ncksllvn commented on [Mon Jul 15 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19253#issuecomment-511517032)

@rianfowler @rtluu Can you make sure I labeled this properly? The issue came up today.

**Comment by rianfowler** [comment]
@annaswims labels are good- thanks for writing this up.

**Comment by annaswims** [comment]
I didn't write it up, I just moved the issue from vets.gov-team.

**Comment by rianfowler** [comment]
# Artifact 
- research notes on recommended approach 
- resolution of issue if small; ticket for work if it's large

**Comment by U-DON** [comment]
The following packages will need to be updated to the corresponding versions:

```
react-leaflet: ^2.2.0,
redux: ^4.0.0
```

`vets-website` and `@department-of-veterans-affairs/formation-react` will also need to update `lodash` to `^4.17.15`.
