### ISSUE TITLE
Itemized list of discrepancies between paper form and online

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#5890]
## User Story or Problem Statement

Problem description. How might we ensure that the online PCAFC application includes all of the requirements of the paper 1010-CG?

## Goal
- Share list with program stakeholders to get buy in and make requirements decisions
## Acceptance Criteria
- [ ] Create itemized list of discrepancies between paper form and online

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by psanders86** [comment]
# Discrepancies between paper form and online requirements


## Issue 1

The paper form asks applicants for specific personal information, including name, Social Security number, and where they currently receive health care. Applicants can choose to sign and submit the form without completing those fields. A printed privacy statement advises applicants that "providing the requested information, including Social Security Number, is voluntary, but if any or all of the requested information is not provided, it may delay or result in denial of your health care benefits."

The online form requires name, address, Social Security and other specific information, and will not proceed if the sections are left blank.

## Issue 2

The paper form advises applicants that if a power of attorney or representative fills out the form on behalf of the Veteran, then he/she must attach legal documentation stating that permission to the form.

The online form does not make that requirement. I've asked the VHA forms team how this was handled on the 10-10EZ form, which has a similar requirement on its paper version.
