### ISSUE TITLE
Track Click Events for Links in Breadcrumb Trail

### ISSUE THREAD

**Issue by JRRoof** [department-of-veterans-affairs/va.gov-team#58914]
## Description
The design team would like to understand the usage of the current breadcrumb trail for authenticated veterans viewing their upcoming, pending or past appointments.

1) When viewing upcoming appointments, the following breadcrumb links should be tracked when clicked:

- Home = vaos-breadcrumb-home-clicked
- Health care = vaos-breadcrumb-health-care-clicked
- Schedule and manage health appointments = vaos-breadcrumb-schedule-manage-clicked

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/97117349/c230facf-3fe9-4b22-9c78-3b00217e895b)

2) When viewing pending appointments, the following breadcrumb links should be tracked when clicked:

- Home = vaos-breadcrumb-home-clicked
- Health care = vaos-breadcrumb-health-care-clicked
- Schedule and manage health appointments = vaos-breadcrumb-schedule-manage-clicked
- Appointments = vaos-breadcrumb-appointments-clicked

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/97117349/cd4b3767-4642-476c-98af-1d9f3946c2bf)

3) When viewing past appointments, the following breadcrumb links should be tracked when clicked:

- Home = vaos-breadcrumb-home-clicked
- Health care = vaos-breadcrumb-health-care-clicked
- Schedule and manage health appointments = vaos-breadcrumb-schedule-manage-clicked
- Appointments = vaos-breadcrumb-appointments-clicked

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/97117349/957ddd50-3a91-402d-b34c-9c56bed0ea38)

---

## Acceptance Criteria
Background: User is authenticated and viewing upcoming, pending or past appointments

Given authenticated user viewing upcoming appointments
When clicking on Home, Health care or Schedule and manage health appointments in the breadcrumb trail
Then track that click event in Google Analytics
And page content matches the N/a 
And page design matches the N/A

Given authenticated user viewing pending appointments
When clicking on Home, Health care, Schedule and manage health appointments or Appointments in the breadcrumb trail
Then track that click event in Google Analytics
And page content matches the N/a 
And page design matches the N/A

Given authenticated user viewing past appointments
When clicking on Home, Health care, Schedule and manage health appointments or Appointments in the breadcrumb trail
Then track that click event in Google Analytics
And page content matches the N/a 
And page design matches the N/A 

### Design Assets
N/A

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ryanshaw** [comment]
@JRRoof This is merged in now, keep an eye out for the new events in GA,

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket.
