### ISSUE TITLE
Mobile Design for 1010-CG

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#5891]
## User Story or Problem Statement
As a Veteran or Caregiver, I need to fill out the 1010-CG application on my mobile device so that I can apply for the PCAFC.

## Goal
First draft of mobile version of online 1010-CG

## Objectives or Key Results this is meant to further
- Increasing the number of applications

## Acceptance Criteria
- [ ]  Create first draft of mobile version of online 1010-CG

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jonathanjnelson** [comment]
https://vsateams.invisionapp.com/share/8HW2IDDJ2SC
