### ISSUE TITLE
Supporting Artifacts one Github Page

### ISSUE THREAD

**Issue by tbaker1026** [department-of-veterans-affairs/va.gov-team#58934]
### Describe the problem

During the Collab Cycle, there are many links to include in the Collab Cycle ticket, Analytics ticket, Sitewide etc.  Some of these links are redundant links - examples - Product Outline and Sketch files, so a lot of copying and pasting and room for error when including them in each ticket. 

### Who will benefit

Product Managers who update and maintain the Collab Cycle tickets.  

### Describe your idea

Create one Gihub File that has links to all of the Supporting Artifacts:
Product Outline
Sketch Files
Source of Truth
QA links 
Product Guide 
Etc.

Then you can have one section in each ticket for Supporting Artifacts and link to the one page. 

### Provide evidence

No Evidence - just an idea

### Platform Mission

- [ ] Keeps these products and services available, stable, and secure.
- [ ] Ensures they are consistent and meet high standards of quality in Veteran-centered user experience and technical approach.
- [X] Provides shared tools, software, support, and technical infrastructure to accelerate their development.
- [ ] Other

**Comment by shiragoodman** [comment]
Questions/comments from the team:

- how would we keep track of various versions of Sketch files? we'd want to make sure we're looking at, and can easily find, the correct version of sketch files
- most teams don't move through Collab Cycle as quickly as Forms team has
- if Forms team can maintain a page/folder with all their relevant artifacts, we'd be open to receiving artifacts that way. Not sure if we'd want to open this up to all VFS teams bc finding artifacts has been a challenge for us in the past

**Comment by tbaker1026** [comment]
@shiragoodman   
We only have one version of Sketch that we update so the link would always be the same  
I will give it a try with the next form and share with you and see what you think

**Comment by shiragoodman** [comment]
solution for Forms team specifically was communicated with @tbaker1026 . No further action at this time.

**Comment by steel36** [comment]
This item was completed.  Moving ticket to done.
