### ISSUE TITLE
Midpoint Review - Content Feedback - Unified Pre-Check-in/Check-in Experience

### ISSUE THREAD

**Issue by megzehn** [department-of-veterans-affairs/va.gov-team#58946]
## VFS actions
- [x] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [x] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [x] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- Thanks for walking us through the design! I don't have anything in the must column, but a bunch of tiny things in the should column. Let me know if anything is unclear. Thanks!

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

Must:

- Nothing in the must column! 

Should:

[1st panel in happy path – Initial confirmation message](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/Oemxgow)

- Add a.m./p.m. to the appointment time, if feasible.
- Change “options 2” to “select 2” after “For more info”
- Remove parentheses around area code (909) near phone number
- Replace “Ask your provider to receive your flu shot” with “Ask your provider for a flu shot”
- Replace “Find a location of the closest pharmacy” with “Find the closest pharmacy here”
- Replace “Phone VA first” with “Call VA first” 
- Put commas after both instances of phone numbers
- Remove “the” in front of VA
- Replace “Walgreens Pharmacy” with “a Walgreens’ pharmacy”

[3rd panel in happy path – After confirmation](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/DEPQpLj)
- Replace “is confirmed” with “you’ve confirmed
- Replace “thoughts on suicide” with “thoughts of suicide” 
[4th panel in happy path – Log in](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/x00d8A5)
- Use numerals, so replace two with 2 and four with 4

[5th panel – pre-checkin > next steps](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/bgwvQKZ)

- Hyphenate in-person when it’s before a noun (i.e. in-person appointment)

8th  panel – Review demographics > Next of kin
- Add plain language statement under header explaining what this is, like “Next of kin is your closest living relative.” 

[9th panel – Demographics reviewed > In person > Completion screen](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/zx95r4b)
- Remove period in H1 “Your contact information is up to date” 
- Fix unclear link language / hyperlinked space with “sign in.”

**Comment by benbrasso-agile6** [comment]
@allison0034 this feedback is for [memorable date component](https://design.va.gov/components/form/memorable-date). Do you want to take or should I submit a ticket? 

> Use numerals, so replace two with 2 and four with 4

**Comment by benbrasso-agile6** [comment]
- 1st panel 
     - That is for the VeText team. I will start a dialogue with them. 
- 3rd panel
     - Speaking to sitewide content about this   
- 4th panel  
     - Speaking to sitewide content about this   
- Memorable date component comment is for DS team 
- Hypen for in-person
     - Will address

**Comment by allison0034** [comment]
@benbrasso-agile6 thank you. I will bring it up with the design system team.
