### ISSUE TITLE
Attach ICNs to CARMA submission

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#5894]
## User Story or Problem Statement
Given that the program office wants to make sure that all online 10-10CG applications are on behalf of verified veterans,
I want to verify the veteran identity in MPI (and return a 400 if the Veteran can't be found)
So that we can ensure that only the applications of verified veteran get submitted.

I also want to return the ICN of a Primary or Secondary Caregiver, if applicable. 

## Objectives or Key Results this is meant to further
- Reduce processing burden on the Program office

## Acceptance Criteria
- [ ] Relevant years are used to query MVI
- [ ] Return 400 if Veteran can't be found 

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevinmirc** [comment]
**Examples**
`modules/veteran_confirmation/app/services/veteran_confirmation/status_service.rb:16`
```rb
emis_resp = EMIS::VeteranStatusService.new.get_veteran_status(edipi_or_icn_option(mvi_resp.profile))
```
