### ISSUE TITLE
Midpoint Review - Accessibility Feedback - Unified Pre-Check-in/Check-in Experience

### ISSUE THREAD

**Issue by briandeconinck** [department-of-veterans-affairs/va.gov-team#58952]
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- There is a LOT here, and it's all really good! It's really great and I'm not seeing anything that's especially concerning.
- Really appreciate the accessibility annotations. Makes my job so much easier when I don't have to guess about what your intentions are, and I'm really grateful for them.
- Love the CodePen prototypes for research, and thank you for sharing them!
- This may be out of scope for this work and this team, but I'm curious about the thought process behind the initial appointment reminder text message and the response codes `Y1`, `N1`, and `D1`. Mainly I'm thinking the `1` part seems unnecessary and introduces a possible failure point for screen reader users (possible, though maybe not likely, that a screen reader user hears "Y1" but doesn't have the visual cue about using the numeral and replies "y one" and it's not recognized). Are there some reminder messages that have another set of Y/N/D response codes? Like Y1 for your first appointment today, Y2 for your second appointment?

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- **Must:** Super small thing: In the Need Help section, any time you have a TTY 711 link the "TTY:" part should be inside the link with the 711. When coding everything the `tty` attribute on the `va-telephone` component does all the formatting for you.
- **Consider:** For [Upcoming Appointments](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/uuid/DB61800E-7440-4F6D-9ADD-70A4FB604881) when displaying the check-in status for an appointment, consider whether it makes sense to move the status message up earlier in that list item. For sighted users, the status message is probably fine in its current location. 
   
   For screen reader users (and maybe screen magnification users), there might be some benefit for getting the "You checked in at 8:55am"-type messages closer to the appointment name and before the modality/location. I'm just thinking if I'm sitting in the waiting room and sifting through all the appointments I have scheduled for today, it's probably better to hear "Primary care... you checked in at..." and then move on to the next list item rather than listen to the whole "Primary care... In person at... Details for... You checked in at..." before knowing if I can move on to the next one. 
   
   It's not a huge amount of extra information you have to listen to so the impact is probably pretty small. But it might make the interaction a bit smoother.
- **Engineering/coding:** Any time there's an alert on a page that contains information that's important for a user to know about right away (as opposed to in-context as they explore the page), you'll need to make sure it's announced on page load by screen readers. I'm thinking especially of the [information up to date success alert](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/uuid/8BDCA2AE-00CE-4162-BEDE-9D0B349E24E6), and something like the [expired link alert](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/uuid/D3C6AF7F-07D1-4345-9379-115B8E60B5FA) might fit that use case too, although you know your product better than me and can make that determination better. Note that just having the alert at the top of the page after the H1 isn't really enough, since a screen reader user may skip around rather than listen to the whole page from the start.
   
   How to decide if an alert needs to be announced immediately: Does it provide feedback about the success/failure of an action the user just took (eg. completed pre-check in and info is up to date)? Does it give information that the user needs to know when deciding what their immediate next step is after the page loads? If either of those questions is "Yes" then it probably needs to be announced immediately. If both are "No" then the alerts can just be present in context and you don't need to do anything special.
   
   How to make sure the alert gets announced immediately: Add `role="alert"` to the alert itself or to the containing element. If it's an error alert, the design system component already has `role="alert"` included out of the box. If the alert is a success, warning, or info alert, you'll need to make sure that role gets added.

**Comment by benbrasso-agile6** [comment]
> This may be out of scope for this work and this team, but I'm curious about the thought process behind the initial appointment reminder text message and the response codes Y1, N1, and D1. Mainly I'm thinking the 1 part seems unnecessary and introduces a possible failure point for screen reader users (possible, though maybe not likely, that a screen reader user hears "Y1" but doesn't have the visual cue about using the numeral and replies "y one" and it's not recognized). Are there some reminder messages that have another set of Y/N/D response codes? Like Y1 for your first appointment today, Y2 for your second appointment?

I'll share this feedback with the VeTExt team

**Comment by benbrasso-agile6** [comment]
Got it. Implementing all of this.
