### ISSUE TITLE
[Data] 10-10 Forms: Come up with Use Cases for Stakeholder Data

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#58953]
As a team member, I would like to understand the data and metrics that our CG and EZ stakeholders have so that I can understand how forms are processed and can use that to come up with a plan for bettering the experience for Veterans and Care Givers.

- Come up with potential use cases for EZ data
- Come up with potential use cases for CG data
- Reach out to EZ and CG stakeholders to collect data
- **AS: I'm thinking we just have this story for coming up with use cases and requesting data, and then we can do a separate story for analyzing the data.**

For CG:
- From the business, we get a monthly report of:
     - Total Paper applications received
     - Total Online applications received
     - Total applications received
     - Total apps approved 
     - Online apps approved
     - Total apps denied
     - Online apps denied
     - Total apps marked invalid/duplicate/created in error
     - Online apps marked invalid/duplicate/created in error
 

For EZ:
- We do not get any monthly data from the business, though we have asked for it many times in the past.  The group we are working with now seem to be more likely to provide data on a request by request basis.

**Comment by luis-simauchi** [comment]
questions for the stakeholders for use cases for data access are keep here in the mural board: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1684348883203/49fc4ff1bf31f3cabe200663708c1002645b447f?sender=4b42d181-fb8d-4f3f-8169-4012a29bcf42

**Comment by luis-simauchi** [comment]
use case for data requests here: https://docs.google.com/document/d/1EbrIKcllGXCdro5SPWFWR1eRgRGMUR2DN_30m1QTkM8/edit?usp=sharing
