### ISSUE TITLE
Sitewide Content, Accessibility and IA Intake Form - Form 21P-0847

### ISSUE THREAD

**Issue by tbaker1026** [department-of-veterans-affairs/va.gov-team#58950]
## About your team

- Team name: 
-	OCTO-DE product owner: Matthew Dingee
-	Product manager: Tricia Baker
-	Designer: Jeana Clark
-	FE engineer: Garrett Rabien
-	Accessibility specialist: Jeana Clark
- Content writer: 
-	Product/team Slack channel: veteran-facing-forms
 
### What does your team need support for? Check all that apply.
- [x] Launching one or more unauthenticated pages, online forms, apps, or tools on VA.gov
- [ ] Making revisions to one or more existing VA.gov pages
- [ ] Accessibility review of wireframes and/or prototypes
- [ ] Accessibility issue (general request)
- [ ] Accessibility PDF review request
- [ ] Accessibility user research support ([submit a separate, additional request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name))
- [ ] Something else 
 
### Give a brief description of what your team needs support with:
- Landing Page for the form, this form can be used for both Pension and Compensation claims
- URL & Breadcrumbs
My team needs support with ...
 - Review content verbiage within the form - NOTE: There are no new questions being asked that need reviewed.  Most of the content within the form came from the PDF directly.  
   - We have however provided more language for the "Remarks" question, and have provided helper text throughout the form to set the context for users  
 
### Will this new product be released incrementally (for instance 25% of users initially)? 
  - [x] Yes
  - [ ] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
### When do you expect to launch your product to 100% of users?
  
*Please provide an estimated date so our team can create other relevant tickets.*
Development work has not started but would like the content within the form reviewed first so we can have final designs for when the developer begins - Around Mid June
 
### Will this work be going through the Collaboration Cycle?
- [x] Yes 
- [ ] No
 
#### If yes, please check all of the phases in the Collaboration Cycle you have completed: 
- [ ] Design Intent
- [ ] Midpoint Review
- [ ] Staging
 
### When does this work need to be completed?
- Estimated launch date:
- Estimated staging review date:
- Content, Accessibility, and IA work needed by: 
  
## Supporting artifacts
*Please provide supporting artifacts as available.*

- Link to product outline:  [Product Outline](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/21P-0847/product%20outline.md)
- Link to or attach user flows: [Mural User Flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1689260999607/483df0b93f188bc90af38e2a3ef0aef0f5ae9f29?sender=ud94436ff2bf5d5ce166a5253)    
- Link to prototype or mockups: [Sketch Files](https://sketch.com/s/3ac6c625-5f29-454c-9b90-7d06460c4dcf)
-  [Source of Truth](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/21P-0847/source-of-truth.md)
- Link to your research plan: 
- Link to any epics/issues that may be helpful:

#### Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [ ] No, let's work asynchronously and meet if needed

 **Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.
 
### Accessibility Help in Slack
The [#accessibility-help channel](https://dsva.slack.com/archives/C8E985R32) in the DSVA Slack, is also available to you as a resource. Everyone is welcome to ask questions or get help from our a11y (accessibility) specialists. Tag `@Terry Nichols` to get a11y help asap.

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

- If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
- If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)
 
 - If you are creating an [experimental design,](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) please [also contact the DST. ](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)
- If you are requesting [a11y support for user research,](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name) please complete this form, next.

**Comment by jennymayoco** [comment]
Hi everyone! Here is the [finalized IA spec](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/form-digitization-21p-0847.md). We included a user journey map we created to help us identify opportunities for discovery of the form. Let me know if there are any questions!

**Comment by DanielleThierryUSDSVA** [comment]
@tbaker1026 @jeana-adhoc @PSIEBENLIST Here's a [link to the Word doc with intro page content and some of the form content](https://dvagov-my.sharepoint.com/:w:/g/personal/megan_zehnder_va_gov/ERrmddEwLCpDiVSFsGFbt7MB3hz0upTLLAgr-js3GzELIg?e=XGdQkj). Rest of comments on form on in sketch. We can go over these in our Friday office hours.

**Comment by jeana-adhoc** [comment]
- Ticket where we used a github diff to communicate to engineers the text edits that needed to be made (and were made in less than 30 minutes!!)
  - https://github.com/department-of-veterans-affairs/VA.gov-team-forms/issues/392

- Final [Source of Truth](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/21P-0847/source-of-truth.md)
