### ISSUE TITLE
Analytics Implementation for address validation in the VA.gov profile

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#5895]
# Analytics Implementation for address validation in the VA.gov profile

## Description
- Is this request for Google Analytics implementation or QA?

Google analytics implementation

- Who is this request for?

  - Authenticated experience team  
  - @Samara-Strauss and @mshea0606 are points of contact
  - Slack: #vsa-authd-exp
    
- What team/project is this work for?
     
  - Address validation: The authenticated experience team has been working on a feature in the VA.gov profile that screens the address a user tries to save and determines how likely it is that the US Postal Service would be able to deliver mail to the address entered. If the validation feature determines that the address entered may be problematic, it lets the user know and suggests potential addresses to save instead.

- Provide the Domain where Google Analytics needs to be implemented
    - https://staging.va.gov/profile   
    - No PII is passed in the URL

- Please provide any upcoming deadlines or important milestones

- We are targeting sprint 16 (two weeks from now) for launch, but I'm realizing I may have gotten this request in too late for that to be possible. Let's talk about when this might be completed and we can adjust our launch accordingly. There is no hard deadline for launch yet.

- Typical Website Interactions to Track

    - *Conversions - Understanding the User Flow:* _Provide URLs that are part of the application from introduction page to successful form completion; conditional pages that are visible depending on an applicant's answer should be marker accordingly._
    
    - There is only one URL for the profile — https://staging.va.gov/profile/. This particular flow happens in the mailing and home address forms, but those forms do not have unique URLs.
    
    - *Other User Interactions*: _Provide details on other interactions and metrics, like click to help text links, that are helpful in understanding user behavior._
    
    - Not sure how to answer this.

- Sample Users when authentication is required

    - You can view the VA.gov profile/update the mailing or home addresses with any staging user.

- Test Users to replicate the event

    - You can view the VA.gov profile/update the mailing or home addresses with any staging user.

- Certain conditions/responses that need to be reviewed

    - Not sure how to answer this.

- Additional Comments

To view the address validation feature:

1. Sign in to VA.gov and go to the user profile.
2. Edit the mailing or home address.
3. Enter a bogus address, or one of [these addresses](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/change-address/address-validation/qa-508/test-cases.md), to bring up the address validation screens.
4. You can edit the address entered or save it. If there are suggestions, you can save one of those.

What we want to track for this feature:

1. Track how often the address validation screen is triggered
 - Override w/ suggestions
 - Override w/ no suggestions
 - Add unit number
 - Edit unit number
2. How many people edit their address from the address validation form
3. How many people select a suggested address
4. How many people choose to override and use the address they originally entered

Let's set up a time soon to chat about this. Thanks for your help!

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by nedierecel** [comment]
@Samara-Strauss Confirming that @jonwehausen and I reviewed the issue. We'll reach out via Slack for time this week to walk through the story with you.

**Comment by Samara-Strauss** [comment]
Great, thank you both!

**Comment by jonwehausen** [comment]
## DRAFT - Datalayer Requirements - Pending @nedierecel's review

### 1) **When the Veteran inputs their address information and clicks '**Update**'** 

**Screenshot of interaction**
![image](https://user-images.githubusercontent.com/48527022/75288634-bc386e00-57ea-11ea-9ce2-23e25a36ae47.png)

**Execute the following DL push**
```javascript
dataLayer.push({
  'event': 'profile-navigation',
  'profile-action': 'update-button',
  'profile-section': 'mailing-address',
  'profile-addressValidationAlertShown': 'yes' //'no' 
  'profile-addressSuggestionProvided': 'yes' //or 'no'
});
```
**Additional Dev Notes**
- ```profile-addressValidationAlertShown``` should populate ANYTIME the yellow 'Please confirm your address is displayed', even if an actual suggesstion address is not provided 
- ```profile-addressSuggestionProvided``` should populate when a suggested address is presented back to the Veteran

### 2) **When the veteran edits from either EDIT link after being presented a validation**

**Screenshot of Interaction**
![image](https://user-images.githubusercontent.com/48527022/75289604-a461e980-57ec-11ea-932f-7356d2d59d76.png)

**Execute the following DL push**
```javascript
dataLayer.push({
  'event': 'profile-navigation',
  'profile-action': 'edit-link',
  'profile-section': 'mailing-address', //change according to address type
});
```

### 3) **When the veteran clicks the update button to submit their address update**
**Screenshot of Interaction**
![image](https://user-images.githubusercontent.com/48527022/75291716-c198b700-57f0-11ea-86c8-c73ac506d589.png)

**Execute the following DL push**
```javascript
dataLayer.push({
'event': 'profile-transaction',  //remain consistent for every update click
'profile-section': 'home-address', //i.e 'mailing-address' change according to address being modified
'profile-addressSuggestionUsed': 'yes' //i.e 'no'
});
```
**Additional Dev Notes**
- The `profile-transaction` event already exists, we just want to add `profile-addressSuggestionUsed` to that event push
- Use the value of `'no'` when the user "overrides" and uses the address the entered

### 4) **When the veteran clicks 'Update' and the API call is made to suggest an address and the service is unavailable or an unexpected error occurs**
![image](https://user-images.githubusercontent.com/48527022/75292862-0de4f680-57f3-11ea-8c4e-5f024ee5dd35.png)

```javascript
dataLayer.push({
  'event': 'profile-edit-failure',
  'profile-action': 'address-suggestion-failure',
  'profile-section': 'home-address' //or 'mailing-address'
});
```

**Additional Dev Notes**
- The screenshot above is just an example of what I was able to generate with no internet connection, please include for any unexpected API response that causes an error or prevents from 
effectively calling the service

**Comment by Samara-Strauss** [comment]
@jonwehausen wanted to clarify some things from above. Let me know if you have any questions about which state represents what and how to accurately track analytics for each metric we're looking for. Thanks for your work on this!

### Tracking when someone overrides and saves the original address

**When there are suggestions**

Override will look like this if there are suggestions.

![7  Scenario 1: Override; Suggestions_Override selected](https://user-images.githubusercontent.com/34068740/75388049-50213d00-58b2-11ea-84cd-da25c4b6d128.png)

**When there are NO suggestions**

Override will look like this if there are NO suggestions.

![13  Scenario 2: Override; No suggestions](https://user-images.githubusercontent.com/34068740/75388308-bd34d280-58b2-11ea-95d7-12fa781a58d4.png)

![Add missing unit number with override](https://user-images.githubusercontent.com/34068740/75388312-bf972c80-58b2-11ea-9fce-dcc37bec651e.png)

![Edit bad unit number with override](https://user-images.githubusercontent.com/34068740/75388319-c160f000-58b2-11ea-91ff-c26735f869ca.png)

### Tracking when someone chooses a suggestion 

![7  Scenario 1: Override; Suggestions](https://user-images.githubusercontent.com/34068740/75388406-e5243600-58b2-11ea-8934-4573c55d46c1.png)

**Comment by jonwehausen** [comment]
Hi @Samara-Strauss ,

Thank you for the thorough details here!

Pending @nedierecel 's review and confirmation, I believe we have accounted for each of these scenarios [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/5895#issuecomment-591103075).

Following @nedierecel 's review, we then can move forward with getting the updates in staging. 

Thanks again,
Jon Wehausen

**Comment by nedierecel** [comment]
Thanks @jonwehausen and @Samara-Strauss - I'm confirming receipt and reviewing the scenarios again. I'll send an update when complete.

**Comment by Samara-Strauss** [comment]
@jonwehausen from what you outlined, I'm still confused on how you're tracking the differentiation between choosing to override and suggested addresses. I'm also confused about:

> When the veteran clicks 'Update' and the API call is made to suggest an address and the service is unavailable or an unexpected error occurs

Having no suggestions does not mean something went wrong or we tried to ping the API and there was a problem. Everything might be working perfectly and there are just no suggestions (and it's worth noting the "add unit number" and "edit unit number" states never have suggestions no matter what).

I realize some of my confusion might be because I don't totally understand how you all go about translating our work into something trackable, so there may not be an issue. Just let me know what your thoughts are and if it's worth regrouping for 15 minutes to go over this.

**Comment by jonwehausen** [comment]
Setting up meeting for 3:30 to reconvene on above items

**Comment by jonwehausen** [comment]
#### Notes from Samara and I's conversation confirming functionality. 
- The yellow alert box will only show after the user inputs their address **IF** there is further validation needed. In other words, if a perfect address is provided, the modal will simply close and the update will occur. 
- If the alert box does show, this doesn't necessarily mean a suggestion will be provided, so we **DO** want the distinction between if the alert box shows, and if a suggested address was ultimately provided. 
- We will then determine if the vet used the suggested address during the final submission of the address update
- We **DO NOT** need to directly determine within reporting an edit occurred specifically related to needing to validate a unit number
- We will also push a specific event for when the API call is made to validate the address and an unexpected error occurs

**Comment by jonwehausen** [comment]
@nedierecel Let's review event syntax for navigation and submit when available.

**Comment by Samara-Strauss** [comment]
@jonwehausen I have an additional request — on the dashboard you create for address validation, can you include metrics for successful mailing and home address form submissions (which I know we already track) as well as errors/unsuccessful form submissions (not sure if we track this)? That information would give a lot more context to how address validation is affecting the greater landscape. Let me know if you have questions or if we need a quick call to discuss.

**Comment by jonwehausen** [comment]
Hi @Samara-Strauss,

Okay, certainly -- this make sense here. 

Also we would like to confirm the dataLayer requirements [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/5895#issuecomment-591103075) are ready for your dev resource.

**Comment by Samara-Strauss** [comment]
Yep! That looks good to me!

**Comment by Samara-Strauss** [comment]
We don't yet have a ticket for FE implementation — do you need us to create one, or will you create one? If you need us to create one, please work with @mshea0606 to do that.

**Comment by mshea0606** [comment]
@Samara-Strauss @jonwehausen @bradl3yC datalayer requirements added to ticket "[FE] Address Validation Analytics - Front End Implementation #6213"

**Comment by bradl3yC** [comment]
@Samara-Strauss @jonwehausen what an AWESOMELY written card.  THANK YOU 🙏

**Comment by Samara-Strauss** [comment]
Hello! Since it's the end of the sprint, just wanted to see if we could get a status update on this. I'm trying to figure out a launch date (!!). Let me know how things are going once you get to take a look at Brad's work and if we can close this out.

**Comment by jonwehausen** [comment]
Hi @Samara-Strauss ,

Thanks - next steps are for us to verify DL and tags within staging. We are currently hitting a login issue with user accounts thru ID.me. This looks to be a known issue within vfs-platform-support. 

We will be able to begin QA as soon as this issue is resolved.

**Comment by jonwehausen** [comment]
Hi @Samara-Strauss and @bradl3yC ,

Thank you for being patient with us during this time. The majority of the dataLayer looks to be working as expected except for a couple items from our QA -- **please see below.** 

## Items for Correction from QA: 
1) We are noticing duplicate datalayer events for both `profile-navigation` and `profile-transaction` when a validation is necessary. With one of each type containing the correct variables, and the other not. **Could we request each event without the relevant DL variables be removed?** 
![image](https://user-images.githubusercontent.com/48527022/76475830-927c6b00-63d6-11ea-8301-9b24071594bb.png)

2) We also noticed under the scenario where a perfect address is provided -- **and no validation is necessary or suggestion is provided** there is a `yes` value for `profile-addressSuggestionProvided`. In addition, the `profile-transaction` event is missing the `profile-addressSuggestionUsed` DL under this scenario as well. 

Please see snippet and recommended correction from dataLayer test below. 

![image](https://user-images.githubusercontent.com/48527022/76476321-1125d800-63d8-11ea-9f9d-6a8da7dd9f03.png)

Please let us know if you have any questions / concerns.

**Comment by Samara-Strauss** [comment]
Thanks for this! @bradl3yC said he would address this today.

**Comment by jonwehausen** [comment]
Hi @sonntag-adam / @Samara-Strauss ,

Thank you both for getting these updates in quickly. I've done another QA within staging and everything looks good now! 

I would just like to ask @nedierecel now to QA GTM tagging and we should be ready to publish shorly thereafter.

**Comment by Samara-Strauss** [comment]
@jonwehausen did you mean to tag @bradl3yC in the message above? 

Also, this sounds good, and we'll wait for final word from Nedie before closing anything! 😃

**Comment by nedierecel** [comment]
Thanks @jonwehausen @Samara-Strauss This is under review.

**Comment by nedierecel** [comment]
@jonwehausen Confirming this passes validation. Unless you have any comments on my QA, this is ready to publish and close.

CC: @mshea0606 and @Samara-Strauss 

**Situation 1: Address Validation Alert Shown, Address Suggestion Displayed, and Address Suggestion Accepted=No**

| Interaction | Value | Pass QA? | 
| --- | --- | --- | 
| Alert Screen | custom metric 19=1 | Yes |
| Address Suggestion Displayed | custom metric 20=1 | Yes |
| Suggestion Accepted | custom metric 21=undefined | Yes |

_Address suggestion displayed is cut off in screenshot_
![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/9a6eb3d7-0986-4c08-98cf-21d08b497d09)

**Situation 2: Address Validation Alert Shown, Address Suggestion Displayed, and Address Suggestion Accepted=Yes**

| Interaction | Value | Pass QA? | 
| --- | --- | --- | 
| Alert Screen | custom metric 19=1 | Yes |
| Alert Suggestion | custom metric 20=1 | Yes |
| Suggestion Accepted | custom metric 21=1 | Yes |

**Situation 3: Address Validation Alert NOT Shown for Correct Address**

| Interaction | Value | Pass QA? | 
| --- | --- | --- | 
| Alert Screen | custom metric 19= undefined | Yes |
| Alert Suggestion | custom metric 20=undefined | Yes |
| Suggestion Accepted | custom metric 21=undefined | Yes |

**Order of Events**
For each situation, I saw these as expected order of events:
- profile-navigation
- profile-transaction
- profile-saved

**Save Failures**
I could not recreate any save failures.

**Comment by jonwehausen** [comment]
@nedierecel Thanks for your QA. I was able to simulate a save failure and this also checks out. We have now published out the workspace. 

Thank you @Samara-Strauss and @bradl3yC for your help and coordination here. Data will begin flowing when launched to production.

**Comment by Samara-Strauss** [comment]
YAY! I am so glad this is done! 

Before we close out for good — can someone show me where I can view these metrics once the feature launches? I'll need to be keeping an eye on them from day one as we work on the phased ramp up.

**Comment by jonwehausen** [comment]
Hi @Samara-Strauss and @mshea0606,

Please use this link as a dashboard template for the validation launch: https://analytics.google.com/analytics/web/template?uid=s9Jd2GS8QhGbM6tsEsh-jw. You can set the view to be 'All VA.gov Website Data [Production]'

**Let us know if this satisfies your needs here! Please note -- due to ingestion lead time with GA it may not be until tomorrow morning or so you see these reports populate with adequate data.**

**Comment by Samara-Strauss** [comment]
@jonwehausen it worked!!

<img width="1280" alt="Screen Shot 2020-03-17 at 1 38 47 PM" src="https://user-images.githubusercontent.com/34068740/76884893-cf23e880-6854-11ea-84cd-9eae6a006a1e.png">

Now that I can see it, I have some questions:

1. What are "Total Profile Transactions"?
2. What are "Total Profile Updates"?
3. Can we see the following as well on this board? I believe we track all of these already:
  - Total mailing address and home address successes
  - Total mailing address and home address failures

**Comment by jonwehausen** [comment]
Hi @Samara-Strauss and @mshea0606,

Please see this [updated dashboard template](https://analytics.google.com/analytics/web/template?uid=2xuc53y7Sw6Mat1b0JoMHw) encompassing the items you called out above. I've modified many of the labels too to give better clarity to the metrics. 

**A couple notes on items you'll see:** 
- "Total Address Update Attempts - Home and Mailing - Including Errors" includes **ALL** final save attempts -- meaning when the user clicked the final 'update' button to ultimately save into their profile
- "Total Update Attempts - Validation Needed or Not" includes **ALL** clicks on the first 'update' button -- whether a validation was provided or not. 
- "Total Mailing Address Suggestion Failures" and "Total Home Address Suggestion Failures" records how many API / unexpected errors occurred in trying to return a suggestion
- "Total Mailing Address Save Failures" and "Total Home Address Save Failures" records **ALL** save errors -- both for providing suggestions and attempting to save. We can reference these metrics with the suggestion failures numbers above to determine how many would be suggestion-related and how many are save-related. 

**Note: Data still seems to be pulling thru this morning, so many are still showing low volume** 

We hope this helps!

**Comment by Samara-Strauss** [comment]
> > "Total Address Update Attempts - Home and Mailing - Including Errors" includes ALL final save attempts -- meaning when the user clicked the final 'update' button to ultimately save into their profile
> "Total Update Attempts - Validation Needed or Not" includes ALL clicks on the first 'update' button -- whether a validation was provided or not.

I'm sorry, I'm not trying to be dense, but I still don't quite understand the difference here. Is it that one is just how many people clicked "Update" on the address form regardless without address validation popping up, and the other includes totals for all save attempts whether or not address validation popped up?

> "Total Mailing Address Suggestion Failures" and "Total Home Address Suggestion Failures" records how many API / unexpected errors occurred in trying to return a suggestion

Got it. I don't see this yet — is it safe to assume the dashboard just hasn't updated yet, and this will show later?

> "Total Mailing Address Save Failures" and "Total Home Address Save Failures" records ALL save errors -- both for providing suggestions and attempting to save. We can reference these metrics with the suggestion failures numbers above to determine how many would be suggestion-related and how many are save-related.

To clarify — are these showing just address validation-related errors, or other errors as well? Also, same as above — I don't see this yet on the dashboard. Is this just because the dashboard isn't showing those updates, but will later?

<img width="293" alt="Screen Shot 2020-03-18 at 10 38 00 AM" src="https://user-images.githubusercontent.com/34068740/76972809-7eb89380-6905-11ea-8b4d-29f5feb8a665.png">

Also, I have a question about this ☝️. We have released this feature to a couple of people on our team to test, so it's good that we are seeing stats populate! But I'm concerned that we are showing "0" under how many times we've needed to show suggestions, yet it shows "1" under how many times a suggestion has been saved. Is there possibly something wrong with the implementation? cc/ @bradl3yC

**Comment by Samara-Strauss** [comment]
Good morning! Stats are looking good today — people are using the tool!

I'm realizing I don't know how to determine how many people use override instead of a suggestion. I think we talked about that when we were talking through the original set up — can we see that?

**Comment by Samara-Strauss** [comment]
Also, we might want to meet at some point if it's easier than hashing things out over github — I still have some questions about what we're looking at and what we're not yet seeing. Let me know what's easier in terms of talking this through.

**Comment by jonwehausen** [comment]
I agree - lets setup a 1on1 so we can discuss in detail.

**Comment by Samara-Strauss** [comment]
Opened a ticket in #7054 for one of the bugs we're seeing.
