### ISSUE TITLE
[Identity Dashboard] - Create add/edit/read routes for Sign in Service Client Configs

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#58965]
Sign in Service needs to enable the ability to add/edit/read Client Configs. This needs to be enabled by a route, and needs to be protected with appropriate certs.

I should be able to:
- Call the route with a client_id and get a serialized set of attributes for the requested Client Config
- Call the route with a client_id and a set of attributes and update the existing Client Config
- Call the route with a client_id and a set of attributes and create a new Client Config

**Comment by aparsley** [comment]
Keep up the good work!
