### ISSUE TITLE
Enable authenticated routes by inspecting access token from sign in service

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#58969]
Arbitrary authenticated routes on Identity Dashboard need to be protected with authentication performed by inspecting access token cookies given to the backend. These cookies will be signed by the Sign in Service, so the authentication must leverage the public cert provided by sign in service to decode the cookie and confirm it is not expired

**Comment by bramleyjl** [comment]
https://github.com/department-of-veterans-affairs/va-identity-dashboard/pull/18

**Comment by aparsley** [comment]
Keep up the good work.
