### ISSUE TITLE
Investigate Rolify/Pundit for user roles

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#58966]
Investigate if we can use the Rolify and Pundit gems to implement user roles on Identity Dashboard

https://github.com/RolifyCommunity/rolify
https://github.com/varvet/pundit

**Comment by rileyanderson** [comment]
@bosawt can we close this?

**Comment by bosawt** [comment]
Investigated these, we might leverage Pundit, but we will not be using Rolify (instead we will create our own user roles schema)
