### ISSUE TITLE
Enable Identity Dashboard logging to datadog

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#58970]
Identity Dashboard must create logs in a format that datadog can ingest, datadog must be able to pick up the logs so that we can display them on datadog dashboards

 - Add Datadog client gem
 - Add datadog statsD gem and configure app to send metrics
 - Configure Rails logger to send logs to Datadog in appropriate format

**Comment by achievedaniel** [comment]
**Questions:**

Do I need to replicate what vets-api is doing?

	They seem to be using sidekiq in some way to send loggs?

	They are also using ddtrace to send logs

	I don't see the 'regular' set up of the different datadogs setup in the current vet-api

Do we need to add the datadog configs to the docker file?

What's the difference when running in kubberneties/EKS?

Do I have to worry about that at all or just use the 'regular' set up?

What's the Datadog API key?

What does it mean to 'Configure Rails logger to send logs to Datadog in appropriate format'?

	Is this related to this documentation? [https://docs.datadoghq.com/logs/log_collection/ruby/?tab=lograge](https://docs.datadoghq.com/logs/log_collection/ruby/?tab=lograge)

What levels of loggs are we sending to Datadog? **DEBUG , INFO , WARN , ERROR , FATAL?**

Are we just consuming the raw logs? Any metrics?

**Comment by achievedaniel** [comment]
Just to hold documentation for reference:

Datadog with Docker:
[https://medium.com/code-wild/collecting-logs-for-docker-rails-application-with-datadog-f8bc9848aeb](https://medium.com/code-wild/collecting-logs-for-docker-rails-application-with-datadog-f8bc9848aeb)

Datadog with Kubernetes:
[https://docs.datadoghq.com/containers/kubernetes/integrations/?tab=kubernetesadv2](https://docs.datadoghq.com/containers/kubernetes/integrations/?tab=kubernetesadv2)

Datadog trace:
[https://docs.datadoghq.com/tracing/trace_collection/dd_libraries/ruby/](https://docs.datadoghq.com/tracing/trace_collection/dd_libraries/ruby/)

Datadog API:
[https://docs.datadoghq.com/api/latest/](https://docs.datadoghq.com/api/latest/)

Logarage Rubi:  
[https://docs.datadoghq.com/logs/log_collection/ruby/?tab=lograge](https://docs.datadoghq.com/logs/log_collection/ruby/?tab=lograge)

Datadog gem:  
[https://github.com/DataDog/dogstatsd-ruby](https://github.com/DataDog/dogstatsd-ruby)

Datadog API gem:  
[https://github.com/DataDog/datadog-api-client-ruby](https://github.com/DataDog/datadog-api-client-ruby)

**Comment by bosawt** [comment]
> 

Generally I'd say yes, we want to replicate what vets-api is doing. If it's simple enough though, we could leverage one of the other options. For example I know they recommend `lograge`, I have no issues using that instead of the tool that vets-api is using. Overall we want to send all logs to Datadog and it will be up to the stack itself what level of logs it wants to output anyways (so the 'production' stack will be set to either `info` or `warn` to send to datadog, other stacks may or may not be set to `debug`, depending on how much it'll spam datadog). The request to 'configure Rails logger to send logs in an appropriate format' just means to make sure we send the logs in a JSON blob that datadog can properly ingest.

For this ticket, only scope it to actual Rails.logger logs. We'll want to send other things to datadog, but that will be in other tickets

The reason it looks like there's a sidekiq method to sending logs is that they are giving a logger to the Sidekiq config so that it can log job metrics.

For the datadog API key, ask for it in the identity engineers slack channel, and someone will give you it so you can play around with it. Make sure you don't check the key in though, even for a draft PR.

**Comment by bosawt** [comment]
For this ticket, we should focus on getting the Gem installed and make sure the logs are output in a format we expect

**Comment by bosawt** [comment]
Decide if log rage or semantic logger is a better option

**Comment by bosawt** [comment]
Here is a link to the vets-api datadog initializer:

https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/initializers/datadog.rb

**Comment by aparsley** [comment]
Keep up the good work!
