### ISSUE TITLE
Pagination 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#5897]
## What happened?
The number of results displayed is different than the number expected, impacting pagination 

## Specs:
- Browser: Chrome

## Steps to Reproduce
- URL: https://www.va.gov/find-locations
- Enter Spokane, Washington + Urgent care + Community urgent care providers (in VA's network)
- Observe 19 results shown
- Compare to response from PPMS which returns 41 results

## Acceptance Criteria
- Data matches between back end and what is displayed to user on front. 
- Search results displayed are relevant to facility type searched
- User experience includes pagination when search returns more than 20 results 
- Pagination is displayed at bottom of results list
- Number of search results is shown
- User can move to next page of search results

**Comment by mmiddaugh** [comment]
We need to provide an estimate for this issue.

**Comment by mmiddaugh** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/5033 deals with adjusting the number of results on the server. Are these related and should/could they be done together?

**Comment by darkbushido** [comment]
they aren't related. they can be done together.

**Comment by chrisj-usds** [comment]
Chiming in on behalf of @davidconlon , who's out today but is being asked by a stakeholder for status on this. Anyone have an update to share? @mmiddaugh

**Comment by darkbushido** [comment]
the fix for #5823 isn't working where I want it to go. pulling back and putting it in a better location.

**Comment by mmiddaugh** [comment]
Changes have been made but this issue is persistent for a variety of reasons. I will create new issues when we revisit this in a grooming session next week.  Meanwhile, I am closing this.
