### ISSUE TITLE
Update card component 

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#58995]
## Description 

Use the [bordered card](https://design.va.gov/storybook/?path=/docs/components-va-card--default) when using a single card and the drop shadow when there are multiple cards.

## Tasks

- [x] Switch card components to use the [bordered card](https://design.va.gov/storybook/?path=/docs/components-va-card--default) when using a single card and the drop shadow when there are multiple cards.
- [x] Check symbols
- [x] Check annotations

## AC

- [x] Final wireframes created

## Delivery
- Single card: https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/bgwvQKZ
- Multiple cards: https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/mP19p3w
- Annotations: https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/oMMjpEL

**Comment by zach-park** [comment]
@benbrasso-agile6 , the task is ready for review.

**Comment by benbrasso-agile6** [comment]
Validated

@cgednalske FYI, not applying this to codepen
