### ISSUE TITLE
Writing for SEO question

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#59]
SEO.md issue

*** @DanielleSoCompany @RLHecht @mikki    RE the below text: I'd like to omit, as I can't find a good way to consolidate/incorporate into the rest of the recommendations on this page and it is a bit counter to everything we recommend: https://department-of-veterans-affairs.github.io/vets-design-system-documentation/content-style-guide/seo

Is it basically that it's okay  to leave it up to each person or line of business to decide? I'm concerned that if our guidance says it's okay not to have descriptions sometimes, then .... why have them?  We could just say write a good search optimized intro text and skip meta description ?  But it's sometimes easier to write a strong SEO description in the meta than in the intro which is always geared a little more toward the on page user experience vs. ppl scanning search results for those bolded keywords... I'm just not sure.  /jl***

- It's ok to not write meta descriptions—sometimes.

  - Google will generate them for you.

  - Rule of thumb for identifying whether to write your own:

    > If a page is targeting between one and three heavily searched terms or phrases, write your own meta description that targets those users performing search queries including those terms.

    > If the page is targeting long-tail traffic (three or more keywords), it can sometimes be wiser to let the engines populate a meta description themselves. The reason is simple: When search engines pull together a meta description, they always display the keywords and surrounding phrases that the user has searched for. If a webmaster writes a meta description into the page's code, what they choose to write can actually detract from the relevance the engines make naturally, depending on the query.

    > **One caveat to intentionally omitting meta description tags:**  Keep in mind that social sharing sites like Facebook commonly use a page's meta description tag as the description that appears when the page is shared on their sites. Without the meta description tag, social sharing sites may just use the first text they can find. Depending on the first text on your page, this might not create a good user experience for people encountering your content via social sharing.

**Comment by DanielleSoCompany** [comment]
Hi @jenniferlee-dsva. Yes, I think it's totally fine to omit this. I'd written this guide with Melissa from DSVA as kind of a working guide...but now that it's going to be used outside of our team, I think it's a good idea to keep it as simple and straightforward as possible. So I'm onboard with deleting!

**Comment by jenniferlee-dsva** [comment]
Awesome. Will close this issue then.
