### ISSUE TITLE
Memorable date validation issue

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#59018]
## Description 

During midpoint review for unified check-in, the platform team pointed out the following issue with the memorable date component: 

> Enter invalid year into year field. E.g., 1800. Then, enter valid year. E.g., 2000. Submit form via "Continue." Expected behavior was to throw a "info does not match our records error." Gets no feedback. Hits "Continue" second time and gets feedback.

https://images.zenhubusercontent.com/133843125/90bd7b1e-158d-4567-ab3b-ec2730fc012b/screen_recording_2023_05_24_at_9_59_28_am.mov

## Tasks

[Slack thread](https://dsva.slack.com/archives/C02G6AB3ZRS/p1684936952160449) 

- [ ] Fix bug or assign work to DS team 

## AC

- [ ] Bug is no longer present or assigned work to DS team

**Comment by loripusey** [comment]
@wullaski @brianseek can you add some points to this one?

**Comment by brianseek** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/59018?planning-poker) with Zenhub @wullaski

**Comment by loripusey** [comment]
@loripusey assign in platform channel
