### ISSUE TITLE
Add `returnUrl` to form page config

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#59012]
## Issue Description

In a `CustomPage`, the `setFormData` function also triggers an auto save which sets the `returnUrl` to the current path. If that `CustomPage` is usually hidden (`depends` callback always returns `false`), then if the user closes the browser and later returns, the `returnUrl` will point to a hidden page and the save in progress continuation will cause the button click to return to the introduction page. There is no way to fix this "broken" `returnUrl` without restarting the form.

## Front end tasks

- [ ] Add a method to set the `returnUrl` for hidden Custom pages
- [ ] If the "Finish this application later" link is visible & used, it also uses the set `returnUrl`
- [ ] Check the review & submit page auto save
- [ ] Add unit tests
- [ ] Request to add documentation

## Acceptance Criteria
- [ ] All tests passing
- [ ] Include documentation

**Comment by saderagsdale** [comment]
@Mottie this wasn't added to the sprint plan. I'll add it.
