### ISSUE TITLE
Replace babel-eslint with @babel/eslint-parser

### ISSUE THREAD

**Issue by acald-creator** [department-of-veterans-affairs/va.gov-team#59030]
In two different repos as I have found uses `babel-eslint`.
- `vets-website`
- `veterans-facing-services-tools`

Please see the package at https://www.npmjs.com/package/babel-eslint which suggests using `@babel/eslint-parser`.

Why do we need this updated?

- The package `babel-eslint` has been deprecated and has not been active for 3 years now. It has been deprecated in favor of `@babel/eslint-parser`.
- The package also has not been receiving maintenance and also no updates either.
- This will also help anyone in the future that wants to create a new repo and would like to utilize the `@department-of-veterans-affairs/recommended` eslint plugin.
- For our Identity team,  we are creating our own Sign-in-Service dashboard, it would be great to be able to take small steps to update and replace this deprecated package with the current package.

There seems to be no negative effect in updating `babel-eslint` with `@babel/eslint-parser` in `veterans-facing-services-tools`, but this has not been tested in `vets-website`, though I would like to update this as well.

**Comment by acald-creator** [comment]
Open PR here: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/931

**Comment by acald-creator** [comment]
Pr in `vets-website`, https://github.com/department-of-veterans-affairs/vets-website/pull/24355

**Comment by acald-creator** [comment]
The PR was reverted, so I'll be submitting another one when I get the approval.

**Comment by acald-creator** [comment]
This issue is now blocked with this open issue 

https://github.com/department-of-veterans-affairs/vets-website/pull/24369

**Comment by acald-creator** [comment]
open PR https://github.com/department-of-veterans-affairs/vets-website/pull/25105

**Comment by aparsley** [comment]
Keep up the good work!
