### ISSUE TITLE
Create and test a page before sign in that encourages migration

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#59031]
#### Acceptance Criteria
- [ ] Reviewed by UX Team
- [ ] Reviewed by PMs
- [ ] Documentation has been updated
- [ ] Put published research in drive

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by APorter-Clarity** [comment]
Meeting with comms team tomorrow 5/26 to see if we are announcing the migration

- Could be a new page similar to the modal (could potentially be before the auth page- how/when do we "interrupt the login process", before they enter credentials)
- (questions) Will this be less or just as distracting as the modal

**Comment by aparsley** [comment]
Closing due to this initiative being now LGAs.
