### ISSUE TITLE
Investigate issues around VHA FSR confirmation emails

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#59055]
## Issue Description
Jill and Ashlie have brought up instances of a Veteran filling out a VHA FSR form and not receiving their confirmation email. Based on the VA Notify portal it looks like this may be a reoccurring issue

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ScottyRJames** [comment]
Complex debugging within sidekiq batch and lack of sidekiq admin UI contributed to ticket rolling over to S101

**Comment by HeatherRienks** [comment]
@ScottyRJames - any details you can share on the resolution? Might be good to have noted for future reference. Thank you!
