### ISSUE TITLE
OOB Deploy Request

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#59062]
# Instructions
Please fill out the necessary details and list the PRs related to the OOB deployment in the sections below.

## PRs Related to OOB
- Please provide the list of PRs related to the need for this OOB Deploy below:
   > https://github.com/department-of-veterans-affairs/vets-website/pull/24347

## Active Daily Users Impacted
- How many active users are impacted at this time and day.
   >  _All_ users that are attempting to submit a Notice of Disagreement

## Has fix been confirmed in Staging?
- [x] Yes
- [ ] No - ~still awaiting the [staging build to finish](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/)~

## Description
- Please provide the details/reason for the OOB Deploy
   > We will be conducting user research on the Notice of Disagreement form, I was asked to add a feature flag to disable the submit button on the review & submit page. After deliberation, I added code to implement this change. I merged in the code on 5/23 expecting to test it after it was available in staging; and it worked as expected. Today, I discovered that the code in place has disabled the submit button for all users.
   
## Verify The following
 - [x] The OOB Deploy Request is after the 2pm EST cutoff for regular deploy.[^1] 
 - [x] The OOB Deploy Request is critical and must be resolved before the next automated deploy.
 - [x] You are prepared to create an Incident Post Mortem[^2] within two business days.

[^1]: (See [Deployment Policy](https://depo-platform-documentation.scrollhelp.site/developer-docs/deployment-policies) and [Deployment Schedules](https://depo-platform-documentation.scrollhelp.site/developer-docs/Deployments.1844641889.html)
[^2]: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/Postmortems

*Performed by Platform Support Team*
 - [x] PagerDuty OOB Deploy Incident Opened
 - [x] OCTO-DE staff acknowledgment of Request, via `/pd trigger`
 - [x] Notification is posted in the appropriate Slack support and team Channels
 - [x] Infrastructure/Operations has acknowledge the Requests
 - [x] Security Team has Reviewed the requests

 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-product-support

**Comment by rmessina1010** [comment]
OOB performed. Closing.
