### ISSUE TITLE
Creating an Error State Document and Wireframes for the AVS MVP.

### ISSUE THREAD

**Issue by ninaranusavice** [department-of-veterans-affairs/va.gov-team#59064]
# Description
Before the AVS MVP goes live on VA.gov, all possible Error State Messages have to identified and designed into the AVS MVP.

# Documentation
-   [Error State Messages Wireframes](https://www.sketch.com/s/05d5a740-4fc7-4380-8d83-e7acfbab201b/p/8F26F305-C37C-46D2-819B-D524994C02C8/canvas)

# Tasks
- [x] Discover all of the possible Error Messages that users of the AVS MVP can encounter coming in from VA.gov.
- [x] Create Wireframes of the Error State Messages using the VA Design System. 

# Acceptance Criteria

**Comment by kristenmcconnell** [comment]
Error states to be shown in [appointments product](https://www.figma.com/file/VHHxvo1QA1ndWc0TBhfkNq/Add-After-Visit-Summary?type=design&node-id=1820%3A24083&mode=design&t=d73L7cwbfSfa6JfE-1).
