### ISSUE TITLE
Insure proper PR checks are made for Identity Dashboard

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#59079]
Make sure only allowed users can merge PRs
Make sure merging to main is not allowed
CI failures should block merging
Other checks that are relevant should be enabled

**Comment by rileyanderson** [comment]
@bramleyjl I meant to assign you this one since you're basically done with it 
- department-of-veterans-affairs/va.gov-team#58971

**Comment by rileyanderson** [comment]
I added this:
![Screen Shot 2023-05-26 at 3.42.56 PM.png](https://images.zenhubusercontent.com/6050e89f7bf33bf313eb2428/83a791dd-ed1d-4fdb-a3f5-03658e04c613)

Everything else was already enabled
