### ISSUE TITLE
Research campaign platforms

### ISSUE THREAD

**Issue by alevindecanini** [department-of-veterans-affairs/va.gov-team#59070]
VA Notify vs. GovDelivery
Any other viable options?

**Comment by kscoulter** [comment]
Drip campaigns in GovDelivery https://support.granicus.com/s/article/Analyzing-a-Drip-Marketing-Campaign?c=govDelivery%20Suite&p=govDelivery

**Comment by kscoulter** [comment]
Given that GovDelivery API returns XML, it is not the best candidate for campaign management for this team.
