### ISSUE TITLE
Assess the test user's eligibility

### ISSUE THREAD

**Issue by alevindecanini** [department-of-veterans-affairs/va.gov-team#59074]
Building off the eligibility functionality created for the organic adoption modal: when a user logs in with a legacy credential, we want to assess their eligibility for either the organic adoption or reactivation campaigns. 

Business rules are in [this Mural](https://app.mural.co/t/innovationboards1199/m/innovationboards1199/1684329312312/df1c36fc281d2e288446e9feb0603321e115525d?sender=uaaa67493ae613f0003928743)

**Comment by jrjamespdx** [comment]
Reopening this issue as it is still in PR review.
