### ISSUE TITLE
Add plain language statement to explain next of kin

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#59089]
## Description 

Feedback from platform content during unified check-in to add plain language statement to next of kin page to better explain. E.g., "Next of kin is closes living relative." (This is just an example. Develop whatever content is best.) 

## Tasks

- [x] Draft content
- [ ] Finalize wireframe

## AC

- [x] Reviewed with CAIA team 
- [ ] Finalized wireframe
- [ ] Create ticket for FE

**Comment by loripusey** [comment]
@loripusey pull into next sprint goals

**Comment by kellysmith1008** [comment]
Danielle Thierry
  5 days ago
Hi! Here's how we define "next of kin" related to records.
You may be considered the next of kin if you’re related to the Veteran in any of these ways:
Surviving spouse who hasn't remarried, or
Parent, or
Child, or
Sibling
We could rework that here to be something like this:
Your next of kin is your closest living relative (like your spouse, parent, child, or sibling).
We can definitely add this to the appt content brief as well as the word list in the style guide. (edited)

**Comment by kellysmith1008** [comment]
Mocked up the proposal from Danielle and posted in the above slack thread to get her blessing on it. Once we receive that, it just needs the update to the wireframe and we can move the ticket into validate for Ben to validate before closing it, @ytsaoca !

**Comment by kellysmith1008** [comment]
Danielle did respond in the ticket with some updated text, so I updated the content in the sketch file text box. She also recommended verifying with our SMEs that this is how they're using next of kin information. @benbrasso-agile6  or @loripusey - would you know who else we should tag on this ticket when we push this to validation to satisfy that recommendation?

**Comment by benbrasso-agile6** [comment]
I mean, that would be the facilities. Maybe try to DM Shawn Adams and ask if he thinks it’s accurate to his understanding. Let me know what he says.

**Comment by kellysmith1008** [comment]
This is from Shawn Adams, so we'll need to rethink that wording just a bit: 
"My understanding is NOK is not used to keep someone informed of care, that'd be the Emergency Contact (ECONT).  NOK is purely for death notice, survivor benefits, requesting certain medical or documentation like a DD214
like if someone is admitted, I believe we contact ECONT which can be anyone
whereas NOK can only be a relative" 
I can tackle that later today

**Comment by benbrasso-agile6** [comment]
Cool cool

**Comment by kellysmith1008** [comment]
Updated the content with Shawn's feedback. @ytsaoca I updated it in the sketch file, but you may want to take one last glance over for spacing and such. I don't think it changed the layout any. Then I think we can move this to validate and have @benbrasso-agile6 take a look when he's back on Monday

**Comment by ytsaoca** [comment]
Wireframe for review: https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/v/2golO5/a/bLMdwA9#Version
@ben-allen-oddball 
'cc @kellysmith1008

**Comment by kellysmith1008** [comment]
@ytsaoca Looks great!

**Comment by benbrasso-agile6** [comment]
@kellysmith1008 did you want to toss it back in the slack thread with Danielle to show her too? https://dsva.slack.com/archives/C01K37HRUAH/p1687290331801719

Also, is "Tell us who..." best to use here. Like, they can't edit this information to "tell" us. All they can do is review what's on file and say whether it's accurate or not. Still think "tell" is fine to use there? 

Other than that, looks cool. 

Once we're ready, I would also go ahead and add that artboard to the other files: 

Unified check design page - https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/0EC89917-F949-4461-A7B3-32A5201FD2A2/canvas

All of the artboards in the production file - https://www.sketch.com/s/231af204-0959-46b4-80f0-eebb94922744/p/6559E321-AF82-42D1-837D-75F9DB19DF15/canvas

Check in file - https://www.sketch.com/s/a31fc97a-2d0c-4ef0-a698-7b73b773836f/p/CBFBBA86-0271-4FF5-8812-2FD13E200F3F/canvas

Pre check in file - https://www.sketch.com/s/ef203d41-ca12-4088-bed4-c870fd34c945/p/F6CA3E59-142F-4778-B7DB-5C3A27C27AB5/canvas

Also, there's a few teams that have been talking about next of kin recently, including 1010 team. Once our content is finalized, we should probably post in #appointments-ux so other teams are aware that we created a definition for next of kin, for those that want to start using it.

**Comment by kellysmith1008** [comment]
@benbrasso-agile6 I sent a few options over to Danielle today. I'll update here when I hear back and make the changes in the links you provided.

**Comment by benbrasso-agile6** [comment]
Right on

**Comment by kellysmith1008** [comment]
Confirmed from Danielle to use "Confirm who you'd like us" - will update that content now

**Comment by kellysmith1008** [comment]
@benbrasso-agile6 So this is significantly much more text than is currently in the artboards - I would want to pair with @ytsaoca or @zach-park to make sure the spacing, alignment, etc stays (or gets updated as needed) as it shoulud after adding this content. Would it be ok to close this ticket and create a separate one this sprint to do that work - just so we can close this ticket? Or do you want to just carry this one over?

**Comment by benbrasso-agile6** [comment]
If it’s still the same user story and task, I would just keep this ticket for next sprint if it needs to be rolled over.

**Comment by kellysmith1008** [comment]
@ytsaoca I've updated the artboards with the new content. Please take a look for spacing and alignment and such. I'll tag you on the individual artboards to make it easier

**Comment by loripusey** [comment]
@ytsaoca where's the link to the new artboards? the old link still has the old content.

**Comment by benbrasso-agile6** [comment]
@ytsaoca can we get this ticket finished up? It looks like Lori has the work slated for FE this sprint. We need to make sure that the sketch files are updated across all sketch files. Some use the background information alert, some use the additional information component. 

> [Slack convo in here](https://dsva.slack.com/archives/C04J6H2LYUU/p1691691420058319)

**Comment by benbrasso-agile6** [comment]
Briningin in @cgednalske for awareness and how it impacts or doesn't her work on demograhpics.

**Comment by cgednalske** [comment]
Thanks @benbrasso-agile6! Are we going with this as the final solution or are we open to further changes depending on demographics work? Either way is probably fine, but it will definitely impact our component options for demographics.

**Comment by benbrasso-agile6** [comment]
You guys should talk it out :) If you need me to review something from https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/63301, I'm happy to help weigh in.

**Comment by benbrasso-agile6** [comment]
So, I'm good with where we landed: https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/mPo902k

I think everyone is good with this. 

But, because this is in the "tech debt epic" and FE will work on this now, @ytsaoca, we need to update this in our check in, pre check in, and production sketch files. 

@loripusey That sounds correct, right?

**Comment by benbrasso-agile6** [comment]
@loripusey if you want FE to get going, they should be able to reference this https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/kKaj1nA

... while Ya-ching is updating the check in and pre check in sketch files. 

Up to you.

**Comment by benbrasso-agile6** [comment]
Pushing back to in progress for Ya-ching to finish up

**Comment by benbrasso-agile6** [comment]
@loripusey check-in next of kin update is ready - https://www.sketch.com/s/a31fc97a-2d0c-4ef0-a698-7b73b773836f/p/26257414-A4F5-4E5B-9BAF-B012609F7494/canvas#Version

@cgednalske toss in the pre-check-in one when you have it ready

**Comment by benbrasso-agile6** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/62927#issuecomment-1688220500

**Comment by benbrasso-agile6** [comment]
Going to close this. We can update our production file when this goes to production.
