### ISSUE TITLE
Add hypen to "in person" on appt detail page

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#59082]
## Description 

The heading for in-person appts should use a hypen, because it precedes a noun, "appointment." 

For pre-check-in and check-in, the heading for in-person appts on the appt detail pages (not the appt list pages) should include a hypen. E.g., "In-person appointment"

## Tasks

- [ ] Add hypen in pre-check-in and check-in 

## AC

- [ ] When this ticket is complete, we need to close the platform ticket - https://github.com/department-of-veterans-affairs/va.gov-team/issues/59131

**Comment by brianseek** [comment]
@benbrasso-agile6 This is merged and should be ready to validate in stage shortly

**Comment by loripusey** [comment]
I validated that the json file in the main branch now says "in-person appointment"; don't know if anyone wants to actually set eyes on it
