### ISSUE TITLE
Sample 526ez Defect Ticket

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#59096]
### Issue Description
Description of the issue

### Information for assessment:
- How many users are being impacted? # of related cases in the last x days/weeks/month?
- What is the impact of the issue?
- Is there a workaround? 
- Does the issue stop someone from meeting a legal requirement?  
- Can people lose service as result of the issue?
- Does the problem have a permanent impact?  For instance can you resubmit the form for a veteran, or do you lose the submission entirely?  Can the VSR reopen the case later and process it, or does the issue send out an incorrect message to a veteran?
- How long has the issue been occurring?
- Is this a potential security/privacy vulnerability?

### Information for troubleshooting:
- Date/Time with timezone when the issue was reported
- What form/page is this error encountered?
- Screenshot or the exact error message on the page
- Steps to reproduce
- UID / ICN / FormID
- Specific example with application ID
- Is it hardware specific? e.g old computer/mobile phone
- Browser type / version
- Case#, if available
- Reporter name in va.gov

### Additional Information:
- Where does the user think they are in the process?
- Does it impact a specific flow or population?
- Is this issue seen consistently or has it just started?
- When have we started seeing this issue?
- What UX/UI components are the users interacting with before the error is produced?

**Comment by mchae-nava** [comment]
I'm thinking I'll try to use this template as best as I can during my shift, and then write out feedback as a comment at the end. If that sounds good, maybe we can all follow suit on subsequent shifts?

**Comment by mchae-nava** [comment]
- Maybe PM/PO review could happen before assessment? 
- - Some assessment Q's could be answered when creating the bug ticket
- - Would let us move straight from assessment to addressing/assigning resources to the solution
- Person on Lamb duty could potentially just resolve smaller issues without bringing into a sprint
- - Would give us some agility on smaller issues
- Maybe Lamb duty person could even do refinement on the larger items so that they can be addressed immediately in a sprint?

**Comment by RakshindaAslam** [comment]
@mchae-nava - recommend we write feedback on the idea board in the issue management section so that we have all feedback in one place and easy to review.

**Comment by mchae-nava** [comment]
Yes will do!
