### ISSUE TITLE
Remove sign in from simplified header

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#59092]
## Description 

Remove Sign In from simplified header 

[Slack thread with screenshot](https://dsva.slack.com/archives/C02G6AB3ZRS/p1684960669215559)

## Tasks 

- [ ] Remove Sign In from simplified header

**Comment by loripusey** [comment]
@brianseek where are we with this one?

**Comment by brianseek** [comment]
@loripusey still in progress/research phase. For sure need to roll over.

**Comment by brianseek** [comment]
Moving to backlog for now

**Comment by benbrasso-agile6** [comment]
closing because 69082 should take care of this issue
