### ISSUE TITLE
Environment access for James Hupp (external contractor)

### ISSUE THREAD

**Issue by jameshupp** [department-of-veterans-affairs/va.gov-team#591]
# Description
- Please provide your name.
   > James Hupp
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > subcontractor content strategist through Nava and Agile6, working on VA.gov facilities content migration and modernization
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Internal%20Tools.md#create-ssh-public-key) for instructions.
  > ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCr7blf38VHRvxJZQU1P8+XLTEfvJPfyvcVUPXlBZGYttFNQtMfSCZmVtWJ4qRzpMn+/v2usJQAsYV97KZXb3n6Dl7C/647PD8oHsrFhWdEISqL8wEpFNvRsxL3clRpBgTOTua/Kb0CE+6FWJ/nbAxPSNIlf0qMMTRks9v/c5wlaeHnjxFHwHO1kzQNiLsrTFspllEXiQagMJJSJ5BIUuIzYCtwUZ+/0T9509EUjZyVzs3Ry+WDorZtJDCBkGF7STGIf+ITMmTj7NQAWoUmHWnvbLowmqcdX1hnS/l3AvMNIfE5yPcU+X+EfIP0H3jeEw6+uJxlTyPkRxLJ2y0m/RjNcUpz/f+2qXwWCcRQAxjUq/q2Jfr+ASgNj4z0IUzIDekJs5N9ZLFqEyNyYf0TSOEUJ0d/VQcO1sxsc14pFO9HaEhsX9Nogipv3RQXIs0ZxYvdbX2vXoaL3D2o5HtpdvZ5KjxmMn1wtORhNQBFbesS9haJb95VfHzYY4beJX5/4TE96AgiyxMPDVk7iYxtJhEZPA84qpLGqxWUkZuSbYUvqmbunvU732g6Xo/zhdYLoMzKvtEhXNcV3MK0FOc6kAAT1XLTmbETfPT0mFPDvswKEfyPuuC+7o9NVlECdIL1MG/5X8SA41tPBS1MkpUrrkqPoN64g0x1h7GjpCKsGZuCtw== jameshupp@navapbc.com

**Comment by tskinn** [comment]
@jameshupp you should be able to connect now. If not reach out slack.
