### ISSUE TITLE
Dashboard - research SSOe data

### ISSUE THREAD

**Issue by alevindecanini** [department-of-veterans-affairs/va.gov-team#59109]
As a dashboard admin I want to be certain that the api fields available in SSOe will adequately track MHV sign in via DSL.

ACCEPTANCE CRITERIA:
Access SSOe data
SSOe api fields are reviewed for clarity
Parameters are clear
Parameters tie back to DSL sign in tracking

Definition of Done:
Data mapping of fields and their definitions is shared with dev team
Required SSOe data fields added to visualization ticket

**Comment by sdickson-gt** [comment]
@alevindecanini John has made a few Dashboard requests recently.  #1 and #2 are related but #1 adds the additional dimension of complexity. If #1 isn't as high or a priority (#2 and #3 were from Chris Johnston feedback), suggest we focus on #2 in this sprint.

1. applications access by CSP (datasource SSOe for all SSOe applications)
2. report on unique authentications by month for all VA (datasource SSOe)
	2a. total unique authentications
	2b. total unique authentications by CSP
3. login success/failures (datasource TBD)

**Comment by sdickson-gt** [comment]
design content: https://docs.google.com/document/d/12zh0ck5eoxmF7aREdfqTJtYQQfwP53mP/edit
