### ISSUE TITLE
Dashboard - create DSL Login architectural design

### ISSUE THREAD

**Issue by alevindecanini** [department-of-veterans-affairs/va.gov-team#59111]
As a dashboard admin I want a flow designed to ensure veteran data is properly handled so that it isn’t exposed.

ACCEPTANCE CRITERIA:
- [x] A data flow diagram is produced to clearly articulate:
- [x] Hash and remove PII 
- [x] PII storage
- [x] Creation of unique identifiers
- [x] How unique authentication events are tracked
- [x] How recurring feeds are handled
- [x] How data is ingested (e.g. DOMO workbench or endpoint)
- [x] The schema for all required data

Definition of Done:
- [x] Data flow diagram shared with team for changes and stored in repo

**Comment by sdickson-gt** [comment]
Design: https://docs.google.com/document/d/12zh0ck5eoxmF7aREdfqTJtYQQfwP53mP/edit
