### ISSUE TITLE
Draft strategic comms plan for campaigns

### ISSUE THREAD

**Issue by alevindecanini** [department-of-veterans-affairs/va.gov-team#59113]
As an email campaign admin I want a plan for messaging veterans about login.gov adoption so that I understand the frequency, segmentation and messaging for communications and can share it with stakeholders.

ACCEPTANCE CRITERIA: 

Categorizes campaigns by intent (Login.gov organic adoption)
Lists realistic channels for comms (emails, blogs)
Recommends veteran segments (Who are we reaching out to first? login credential type)
Includes testing phase for initial emails and recommends # of veterans to reach out to for early feedback)
Links to content for messaging where available

**Comment by CarlDickerson** [comment]
Comms plan draft pdf attached her[https://app.zenhub.com/files/133843125/3e97a847-519d-46c3-91cf-aaf2ba8cd592/download](https://app.zenhub.com/files/133843125/3e97a847-519d-46c3-91cf-aaf2ba8cd592/download)e
