### ISSUE TITLE
Publish campaign landing page

### ISSUE THREAD

**Issue by alevindecanini** [department-of-veterans-affairs/va.gov-team#59114]
As a content admin I want to publish the login.gov landing page so that veterans have a one-stop shop for information about changing their credential.

## Acceptance criteria: 
- [x] Finalize content and images
- [x] Get approvals from Sitewide, Content SMEs (e.g. Danielle Thierry)
- [x] Link cannot be accessed without having the direct url

## Definition of Done: 
- [x] Publicly accessible; is available for demo and use in future email content.

**Comment by skirkman16** [comment]
We met with Sitewide and Danielle Thierry to confirm all updates made to the CLP draft. Landing page is now published and will be found at https://www.va.gov/initiatives/sign-in-securely-with-logingov. Link will go live at 3PM PST/6PM EST. Next steps is to choose existing FAQs (between 3-10) to highlight and an FAQ to link to for more information. The design team will meet to make these decisions. No blogs were linked yet to ensure that we are communicating the right message at this time. For future reference, we can only link two blogs on the CLP at a time.
