### ISSUE TITLE
Platform Support Onboarding & Rotation

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#59127]
Clarifying approach to assigning and rotating members of various teams to support team

**Comment by jknipes** [comment]
Selection depends on who has already been through the rotation + what makes sense from where someone is in their work on a project. Dedication to a project will also change based on current needs for that project.

Ex: 5 Dev Ops people to choose from, 3 have served rotation, 2 have not. Choose from the 2 remaining based on bandwidth. 

Tech Support Team mostly works around a quarterly rotation
Tier 2 works on a sprint rotation
Incident Commander (on-call) works on a weekly rotation
Tier 2 (on-call) works on a weekly rotation 

Support team is the only team with definitive time frame. Any engineer that comes on to team is held to 1 Quarter, because this is outside their original purpose. Rarely do they cycle off sooner, sometimes cycle off later, usually 1 extra week to accommodate keeping another engineer on a project where she is needed. "Not a light-switch approach, more of a dimmer".

**Comment by jknipes** [comment]
Link to edit [HERE](https://vfs.atlassian.net/l/ce/h0C08J1a)

**Comment by alyssagallion** [comment]
@jknipes I think we have already documented this in our Tier 1 to Tier 2 escalation process right? Might be moot now!

**Comment by jknipes** [comment]
@alyssagallion that's correct! Closing now
