### ISSUE TITLE
Adding Obie Abdi to DSVA Slack

### ISSUE THREAD

**Issue by oabdi-112** [department-of-veterans-affairs/va.gov-team#59139]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

I am a member of the DSVA Slack but would like to have access to other channels within the DSVA slack workspace.

Are you requesting to add an individual as a:

- Full member

- Please add obaidullah.abdi@va.gov as a full member.

**Comment by LEHigley** [comment]
obaidullah.abdi@va.gov was already showing as a single channel guest. updated to full member. 

in future requests please note if someone is already in the workspace.
