### ISSUE TITLE
Identity Dashboard (FE) - Authentication integration

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#59142]
## Description
Set up authentication with our Sign in Service API

## Tasks
- [x] Implement authentication to our Sign in Service
- [x] Add a callback page for the token exchange (see AuthApp.jsx in vets-website for this)

**Comment by asg5704** [comment]
BLOCKED

**Comment by asg5704** [comment]
Update: Unblocked

**Comment by aparsley** [comment]
Keep up the good work.
