### ISSUE TITLE
BE | Profile | Personal Information | Rules for managing demographics

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#59140]
## Background
Some questions came up from the mobile team regarding the rules for allowing a user to manage demographic information.

The rules for accessing/managing personal information data:
- A user must authenticate with an identity verified account through either a ID.me or Login.gov (DS Logon and MHV credentials are gated because of security issues).
- A user must have a CSP ID and the correct assigning authority of ID.me or Login.gov.  If not, then an access denied error is returned from VA Profile.

The questions are centered around a situation in which a user logs in using DSL or MHV.  In these situations, a user is brokered through ID.me.  So in this scenario, if a user does have a CSP ID and the correct assigning authority, and the authentication was brokered by ID.me, then should they be able to manage their demographic info?

At this point, we believe the answer is that they should be allowed to manage demographic info, but we haven't arrived at a final answer.

This thread contains the details https://dsva.slack.com/archives/C7TE0PFTL/p1684946206797519

**Comment by tpharrison** [comment]
cc/ @mtcA6

**Comment by mtcA6** [comment]
Thanks @tpharrison. 
This feels REALLY closely paired w/ the issue @adamwhitlock1 is working on [FE | Profile | Sign-in updates for MHV and DS logon users#47070](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47070). Do we have potentially need to circle the wagons to make sure there aren't more things hiding as it relates to logging in w/DS and MHV that we need to take care of?

**Comment by tpharrison** [comment]
@mtcA6 Good point.  Yes, let's discuss further just to make sure we're all on the same page.

**Comment by tpharrison** [comment]
Update made by mobile team - https://github.com/department-of-veterans-affairs/vets-api/pull/12813
