### ISSUE TITLE
Design Intent - Accessibility Feedback - Authenticated Experience, Profile, Notification Settings, Updates to Edit Flow (first example using mobile number)

### ISSUE THREAD

**Issue by briandeconinck** [department-of-veterans-affairs/va.gov-team#59155]
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- Everything looks great!

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- **Must:** Cancel and go back to the last page should be a link rather than a button (which I think was where you were already leaning). It's a little bit of an edge case but the decision here comes down to:
   - You're navigating to a different URL when you click the element.
   - There's no saving or submission of user data when you click it.
- **Consider:** Make the H1 specific to the situation the user is in, eg. if there's no phone number saved the H1 should be "Add your mobile phone number" and if there's already a phone number saved it should be "Update your mobile phone number." It's not a big thing but it helps clarify exactly what your purpose is for being on the page.
- **Consider:** If possible, make the back link text specify where you're going back to rather than just saying "last page." That reduces cognitive load and helps in task interruption situations.
- **Consider:** Thinking about the discussion about this interaction taking you out of the user flow you were coming from, consider adding some text to the page indicating what happens next, eg. "After you save your phone number, you will be returned to [page]." That should help with cognitive load and task interruption as well.

**Comment by andaleliz** [comment]
Hi @briandeconinck thanks for the feedback, I'm glad everything looks great! I'll close this out since there is no action item from our team. 

CC @mtcA6
