### ISSUE TITLE
[UX] Change "verify" to "confirm"

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#59162]
## Background

In check-in, on the "Did you travel from your home address?" page, change "verify" to "confirm."

This request came from collab cycle feedback during the staging review. See [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/59130).
  
## Tasks
- [ ] Change "Verify" to "Confirm"

**Comment by ytsaoca** [comment]
Wireframe for review: https://www.sketch.com/s/a31fc97a-2d0c-4ef0-a698-7b73b773836f/a/3oPlkKw

**Comment by ytsaoca** [comment]
Wireframe for review: https://www.sketch.com/s/a31fc97a-2d0c-4ef0-a698-7b73b773836f/a/3oPlkKw

**Comment by ytsaoca** [comment]
Wireframe for review: https://www.sketch.com/s/a31fc97a-2d0c-4ef0-a698-7b73b773836f/a/3oPlkKw

**Comment by benbrasso-agile6** [comment]
LG

@ytsaoca because it's such a small update, I would recommend to go ahead and update everything now on these artboards too:

Travel feature page in check in file - https://www.sketch.com/s/a31fc97a-2d0c-4ef0-a698-7b73b773836f/a/1VPPZKy
Production - https://www.sketch.com/s/231af204-0959-46b4-80f0-eebb94922744/a/Mmlppnw
Unified check in file - looks good as is

Then close the ticket

**Comment by ytsaoca** [comment]
Edited Travel feature page in check in file and Production. I'll close this ticket.
