### ISSUE TITLE
Add eyebrow to check-in question pages

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#59168]
## Tasks

- [ ] Add eyebrow to pre-reg, travel and appointments list pages

Not placing it as a blocker, but here's the related design ticket https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/58989

**Comment by benbrasso-agile6** [comment]
@loripusey @brianseek @wullaski abstract file https://app.abstract.com/projects/ab30c34e-e2f9-4d3e-bb96-3b683b006c24/branches/056e1747-6917-4f7a-a9cd-d9a1a6eb7426/collections/61c77060-293f-4241-aced-8a848e93afb1

**Comment by loripusey** [comment]
@benbrasso-agile6 can we close this ticket then and proceed with the frontend work?

**Comment by benbrasso-agile6** [comment]
This is the FE ticket. Yes, proceed. But, I did tag @cgednalske on the design ticket, but tagging her here too. We need to provide some information about including the eyebrow in the h1. Christina, don't you have that documented? It would be nice to include that in @ytsaoca 's abstract branch. For now, I would drop it in here as a comment.

**Comment by loripusey** [comment]
@benbrasso-agile6 just wanted to confirm that the eyebrow now says "CHECK IN" for all check-in pages; can you confirm if that is correct?
cc: @brianseek @wullaski

**Comment by cgednalske** [comment]
Here is the accessibility guidance for making sure the eyebrow reads out correctly and not as individual letters:

```
HTML:
<h1><span class=“eyebrow”>Check-In</span>
Did you travel in your own vehicle?</h1>

CSS:
.eyebrow {text-transform: uppercase;}
```

**Comment by loripusey** [comment]
Has this been validated? @brianseek

**Comment by brianseek** [comment]
I saw it out there when we were prod testing, but I would lean on you or @benbrasso-agile6 to validate from a UX/product perspective. You should be able to see the work on stage.

**Comment by benbrasso-agile6** [comment]
LGTM 

![Screenshot 2023-06-23 at 10.28.17 AM.png](https://images.zenhubusercontent.com/62264cddfdd7546d65710eff/0e8f32c0-1e08-4bdd-b12f-4b8efc5bb59c)
