### ISSUE TITLE
[BE] Fix 1010ez validations

### ISSUE THREAD

**Issue by lihanli** [department-of-veterans-affairs/va.gov-team#59175]
Name length validation (and maybe other validations) does not match 1010ez API. Ask 1010ez team for documentation on all their validations and change our validations to match theirs.

**Comment by hdjustice** [comment]
Lihan mentioned to Joshua F, pending response

**Comment by lihanli** [comment]
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/830084/bee527a2-4ec6-4980-a0be-8b4b0e9645e3)
