### ISSUE TITLE
[DISCOVERY][EKS] Define IAM Role Per Tier

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#59184]
## Description
Brainstorm and propose:
- Define an IAM role per Tier (dev, staging, prod, sandbox, utility) to allow user access to appropriate cluster resources
- Are there areas of a cluster that the user should not have access to?
- Consider mapping existing IAM groups to new roles

## Notes
- Would like to avoid having to grant individual access rights  i.e. if you are a developer, you should be able to access what you need
- May need to educate others on the use of `kubectl debug` to troubleshoot nodes

## Acceptance Criteria
- [ ] Detail roles per tier (documentation)
- [ ] Discuss findings with the team

**Comment by npeterson54** [comment]
removing from sprint due to needing more refinement

**Comment by ph-One** [comment]
I'm on support. Bumping this out a Sprint.

**Comment by ericboehs** [comment]
For backend devs, it would be useful to replicate all the access we have in Argo.

For example, viewing (get/list/describe) the various cluster resources (pods, services, deployments, and namespaces). Seeing `logs` and `exec`into into the pods within the appropriate namespaces (e.g. vets-api or platform-atlas).

**Comment by ph-One** [comment]
| Tier | IAM Group
|-|-|
| Next | dsva-vfs-developers, vsp-operations
| Dev  | dsva-vfs-developers, vsp-operations
| Staging | dsva-vfs-developers, vsp-operations
| Prod | vsp-operations |

**Comment by adhoc-nshipman** [comment]
Added access for vsp-operations to each cluster that's created. Moving dev access to a different ticket with the changes to access entry.
