### ISSUE TITLE
[deploy nodes to control plane] Build AMI Packer

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#59185]
## Description
Build the AMI with VA requirements

## Resources 
- https://github.com/department-of-veterans-affairs/devops/tree/master/packer

## Acceptance Criteria
- [x] Amazon Linux EKS Base
- [x] VA Certs installed 
- [x] VA Monitoring agents installed
- [x] Consider Naming convention
- [x] GHA that builds this

## Refinement Guidance - Check the following before working on this issue: 
- [x] _Team label assigned ("platform-tech-team-2")_
- [x] _Epic assigned (if needed)_ 
- [x] _Estimated (points assigned)_
- [x] _Sprint assigned (once planned)_
- [x] _Team member(s) assigned_

**Comment by ph-One** [comment]
Action seems to be failing without a clear reason why (it builds when executed manually).
