### ISSUE TITLE
[Deploy Nodes to control plane] size nodes for clusters

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#59188]
## Description
Lead team discussion for cluster sizing of each tier (dev, staging, sandbox, utility, prod)

## Acceptance Criteria
- [x] Set up team meeting 
- [x] Document accordingly

## Refinement Guidance - Check the following before working on this issue: 
- [x] _Team label assigned ("platform-tech-team-2")_
- [x] _Epic assigned (if needed)_ 
- [x] _Estimated (points assigned)_
- [x] _Sprint assigned (once planned)_
- [x] _Team member(s) assigned_

**Comment by ben-allen-oddball** [comment]
Dev
        Min:            3
        Max:            20
        Desired:        3
        Nodes:
                r5.4xlarge
                r5.4xlarge
                r5n.4xlarge
Sandbox
        Min:            3
        Max:            20
        Desired:        3
        Nodes:
                m5n.2xlarge
                m5.2xlarge
                m5.2xlarge
Staging
        Min:            5
        Max:            20
        Desired:        5
        Nodes:
                r5.4xlarge
                r5.4xlarge
                r5.4xlarge
                r5.4xlarge
                r5.4xlarge
Utility
        Min:            3
        Max:            18
        Desired:        3
        Nodes:
                r5.4xlarge
                r5.4xlarge
                r5.4xlarge
Prod
        Min:            5
        Max:            60
        Desired:        15
        Nodes:
                r5.4xlarge
