### ISSUE TITLE
Identity Dashboard BE Milestone 1 - Client Configuration

### ISSUE THREAD

**Issue by acald-creator** [department-of-veterans-affairs/va.gov-team#59182]
What is the Client Config application?

This allows a Sign in Service client to view and update their Sign in Service integration (Client Configuration)
On lower stacks, a User should be able to make an update and have it immediately propagated to Sign in Service
On production, a User should be able to make an update and trigger a notification to an 'admin' (Identity team, or maybe just Joe for now), who can propagate the change manually (we might promise that it updates within 48 hours, so definitely does not need to be triggered within minutes or anything)

Work involved in the Milestone (backend/devops):

Backend
VA Identity Dashboard auth w/ SiS
User Roles implemented (manual updating only, no ability to update roles from Frontend)
Repository set up, proper CI pipelines and repo rules
Ability to view and update Client Configs for Sign in Service

Devops
Dev stack deployed and accessible
Production stack deployed

Potential blockers
Frontend: Frontend will facilitate auth
Devops: Test/Prod stacks implemented by end of milestone

**Comment by bramleyjl** [comment]
Backend Scoping Lucid document to pull tickets from
https://lucid.app/lucidchart/51c1d366-4d46-4242-b923-d3644144c478/edit?invitationId=inv_b2ae38eb-5fd7-4deb-8348-ca07dd849d1d&page=0_0#
