### ISSUE TITLE
My VA team follow up - Printed health Info card

### ISSUE THREAD

**Issue by jonathanjnelson** [department-of-veterans-affairs/va.gov-team#59196]
Follow up with the My VA team on the Printed health Info card:

- [ ] Are these fields being added to My VA?
- [ ] If they are not being added to My VA, is it appropriate for this to be on My VA or MHV on VA.gov and where? 

### Acceptance Criteria:

- Meet/slack with My VA to confirm ownership.
- If we have ownership, create follow on tickets
- Document discussion/findings in ticket

### Dependency
Dependency on My VA Team, availability for the discussion, and the results of the conversation.

**Comment by batemapf** [comment]
slack thread: https://dsva.slack.com/archives/C04GDQSHD1R/p1685461861219419

**Comment by LynneJohnson224** [comment]
Waiting for Lauren to follow up with Dr. Josephs.

**Comment by jonathanjnelson** [comment]
Closing this ticket based off of conversation with. leadership: https://dsva.slack.com/archives/C0581MN69TJ/p1685998447917599
