### ISSUE TITLE
Vets-api terminal access for Gregg Puhala

### ISSUE THREAD

**Issue by GcioGregg** [department-of-veterans-affairs/va.gov-team#59191]
### E-QIP Transmittal Date

- [x] Check this box if you have an E-QIP transmittal date.

### Your Name

Gregg Puhala

### Your GitHub handle (terminal access is managed through GitHub)

@GcioGregg

### Team, Role, and Company of the target individual

VFEP Sustainment, Ruby on Rails Developer, GCIO

### Product Manager (PM) name and email

Kara Ciprich, Kara.Ciprich@va.gov

### Product Owner (PO) name and email

Darla van Nieukerk, Darla.vanNieukerk@va.gov

### Your dsvagovcloud AWS user name (if applicable)

Gregg.Puhala

### ArgoCD terminal access requested for the following environments

- [ ] dev
- [ ] staging
- [ ] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### COR Name (leave "None" if you listed an AWS user name above)

None

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

None

### Access Expiration

ongoing

### Additional Notes

Requesting **read-only** terminal access for ARGOCD Vets-Api production. I would like to have this access so I can confirm production code pushes worked successfully by checking for lines of code that got pushed.
We have had a couple of issues with production releases not going off correctly and need to get out in front of them right away instead of getting notified through users having issues.

### User must exist in a roster before vets-api terminal access can be granted

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added
- [x] If they included an AWS user name, check to see if their user name is listed in [iam_users.tf](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf)
- [x] Comment in this issue saying which roster the user is listed in and confirming their AWS user name (if applicable)

**Comment by GcioGregg** [comment]
We were told there is currently no read-only access, so please make this request for full access.  Thanks.

**Comment by jknipes** [comment]
@GcioGregg we have confirmed your AWS user name. Access to `prod` is pending approval by OCTODE, and we'll update you as soon as it's available.

**Comment by jknipes** [comment]
@GcioGregg NOTE: Please provide a screenshot of your EQIP Transmittal, as it will expedite Production approval.

**Comment by GcioGregg** [comment]
@jknipes, I'm not sure what a "screenshot of my e-QIP transmittal" is exactly or where I would get it from - can you give me guidance on where to get this?  Thanks.

**Comment by GcioGregg** [comment]
Here is an email re: my EQIP transmittal.  It wouldn't allow me to attach or copy in a screenshot, so this is the plain text.  If you need it in screenshot format, let me know how to do that here.  Thanks.

-----Original Message-----
From: Arnone, Joseph E. <[Joseph.Arnone@va.gov](mailto:Joseph.Arnone@va.gov)> 
Sent: Tuesday, October 11, 2022 12:12 PM
To: [gpuhala@gmail.com](mailto:gpuhala@gmail.com)
Cc: Riccio, Joseph <[Joseph.Riccio@va.gov](mailto:Joseph.Riccio@va.gov)>; Blanchard, Lee J. (BAH) <[Lee.Blanchard@va.gov](mailto:Lee.Blanchard@va.gov)>
Subject: Transmittal Notice--Puhala, Gregg (GovernmentCIO)

Subject of Investigation Request: Puhala, Gregg (GovernmentCIO)

The e-QIP questionnaire you completed has been released to the Defense Counterintelligence and Security Agency (DCSA). It may take up to 5 days for DCSA to schedule, or initiate, your investigation. Contact your Contracting Officer Representative (COR) or Human Resources (HR) Liaison for assistance in obtaining a VA Personal Identity Verification (PIV) card. The PSAC does not sponsor or issue PIV cards.

The Personnel Security Adjudication Center or DCSA may contact you for more information or to schedule an interview. It is important that you respond to such requests in a timely manner. Failure to cooperate with an investigator will cause your background investigation to be cancelled.

IMPORTANT NOTICE: This e-mail is NOT an authorization for you to begin working for the VA or authorization to obtain VA network access. If you have questions regarding the requirements to begin work or obtain VA network access, contact your COR or HR. The Personnel Security Adjudication Center does not grant VA network access or determine when you may begin work.

Joseph Arnone
Security Assistant
Department of Veterans Affairs
Office of Identity  Credential and Access Management (OICAM) PSAC - Personnel Security Adjudication Center
2200 Ft. Roots Dr., Bldg. 192
North Little Rock, AR 72114
PSAC-HELP DESK: (501) 257-4469 or (501) 257-4490 Desk# 501-244-1156
Fax: 501-244-1318

**Comment by ryan-mcneil** [comment]
@jknipes while atypical, Bill seems to have given his permission per receipt of the eQIP date, which we now have. I think we can give Gregg access for 3 months.

**Comment by jknipes** [comment]
Slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1686942356728829)

**Comment by lindsay-insco** [comment]
@GcioGregg Your Vets API Terminal Production access has expired.

Would you like to request an extension? You have 72 hours to respond, or your access will be revoked and you will need to fill out a new request.

**Comment by GcioGregg** [comment]
Yes, I need an extension.  I use this access on a daily basis to confirm Pull Requests files are updated appropriately on vets-api production.

**Comment by lindsay-insco** [comment]
@GcioGregg access to Production has been extended by 6 months, expiring 06/06/25.

Please set a reminder for yourself to return to this Issue and request an extension within 1 week of the expiration date. You'll receive 1 reminder with a 72 hour window to respond. Failure to respond will result in your access being revoked and will require you to fill out a new request.

**Comment by lindsay-insco** [comment]
Slack reminder [here](https://dsva.slack.com/archives/C06CY71PCAX/p1733512111300139)

**Comment by GcioGregg** [comment]
It's that time again, I need an extension. I use this access on a daily basis to confirm Pull Requests files are updated appropriately on vets-api production.  Thanks.

**Comment by lindsay-insco** [comment]
@LindseySaari @ericboehs can one of you please give us a 👍 to extend their access?

**Comment by lindsay-insco** [comment]
@GcioGregg access to Production has been extended by 6 months, expiring 12/06/25.

Please set a reminder for yourself to return to this Issue and request an extension within 1 week of the expiration date. You'll receive 1 reminder with a 72 hour window to respond. Failure to respond will result in your access being revoked and will require you to fill out a new request.
