### ISSUE TITLE
As a Search user, when the Search.gov upstream is not responsive, I can still see popular results

### ISSUE THREAD

**Issue by kfrz** [department-of-veterans-affairs/va.gov-team#592]
## User Story
As a Search user, when the Search.gov upstream is not responsive, I need to still see popular results so I can find the information I am seeking (to get benefits, GI Bill info, etc).

## Goal
Search results are cached or otherwise presented when the Search.gov upstream service is unavailable

## Acceptance Criteria
- [ ] 

## Definition of Done
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by johnhashva** [comment]
@denisecoveyduc I happened upon this one in the PW icebox.   It's an interesting edge case so worth talking about so we can decide whether to close or put in out backlog. (FYSA @brianalloyd )

**Comment by srsuddath** [comment]
This is an interesting edge case that we will consider in the future! There will need to be some conversations had on what content (if any) would be made available: like best bets vs web results.

**Comment by nicole-leonard** [comment]
@srsuddath is this still relevant or has this been resolved?

**Comment by srsuddath** [comment]
Hey I totally missed the ping on this, my bad. but yeah, this is not something we are interested in pursuing
