### ISSUE TITLE
Sidekiq Admin UI Access Request

### ISSUE THREAD

**Issue by jamiew-vmware** [department-of-veterans-affairs/va.gov-team#59208]
#### Access to the Sidekiq Admin UI is managed through a GitHub Teams per environment via the following teams: 
- [Dev](https://github.com/orgs/department-of-veterans-affairs/teams/va-gov-sidekiq-dev)
- [Staging](https://github.com/orgs/department-of-veterans-affairs/teams/va-gov-sidekiq-staging)
- [Sandbox](https://github.com/orgs/department-of-veterans-affairs/teams/va-gov-sidekiq-sandbox)
- [Prod](https://github.com/orgs/department-of-veterans-affairs/teams/va-gov-sidekiq-prod)

_Please provide your GitHub username to be added to that team, along with a reason access is required and which environments you're requesting access to._

- GitHub username: jamiew-vmware
- Reason access is required: I am reviewing the onboarding process to improve
- Environments requesting access to: all

**Comment by ryan-mcneil** [comment]
@jamiew-vmware Sorry, I am in the middle of revamping this request process, which will provide more explicit requirements for access.

Can I get your full name so that I can confirm you're on one of the rosters? 
Which team are you on?
Can you help me understand why "reviewing onboarding processes" is reason enough for being able to access Production? I will also need proof of your E-QIP transmittal (a screen shot of the email is perfect). 

Thank you!

**Comment by ryan-mcneil** [comment]
@jamiew-vmware 

Oh, ok, that makes sense! Well as of yesterday I released the updated [Access Request Template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=external-request%2Cplatform-tech-team-support%2Cops-access-request%2Csidekiq-access-request&projects=&template=vetsapi-sidekiq-ui-access.yaml&title=Sidekiq+Admin+UI+access+for+%5Bindividual%5D) that is much more explicit about what is required. That template is now linked from the [Sidekiq UI docs](https://vfs.atlassian.net/wiki/spaces/pilot/pages/2555183177/Sidekiq+UI+Access).

Please let me know if you have any questions after that. If it's all clear, I'll close this request.

If it's all the same to you, I'm going to skip the actual step of adding you to the teams, as it will just create another step for someone else to remove you down the road (especially if you don't intend to access the UI anyway.

Thanks!

**Comment by jamiew-vmware** [comment]
Hey Ryan, when I went to the link for Sidekiq admin access, I receive [this](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jeff2d2&labels=tools-be%2C+sidekiq-access-request&template=sidekiq-admin-ui-access-request.md&title=Sidekiq+Admin+UI+Access+Request) which I believe is the old request. The link I'm using is on this [page](https://depo-platform-documentation.scrollhelp.site/developer-docs/sidekiq-jobs).
<img width="1199" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/134732737/1c39cc76-ddd7-480a-aeca-116c76fbfc64">

**Comment by ryan-mcneil** [comment]
@jamiew-vmware Thanks! I'm trying to catch all of the different entry points. I'll fix it!

Does everything else look good? Can I close this?

**Comment by ryan-mcneil** [comment]
@jamiew-vmware I updated that page you referenced. I didn't have that one on my radar at all, and it was very out of date. I revamped it and pointed to the external [Sidekiq UI Access](https://vfs.atlassian.net/wiki/spaces/pilot/pages/2555183177/Sidekiq+UI+Access) page that I had worked on.

**Comment by jamiew-vmware** [comment]
Thanks Ryan!
