### ISSUE TITLE
OOB Deploy Request

### ISSUE THREAD

**Issue by aherzberg** [department-of-veterans-affairs/va.gov-team#59229]
# Instructions
Please fill out the necessary details and list the PRs related to the OOB deployment in the sections below.

## PRs Related to OOB
- Please provide the list of PRs related to the need for this OOB Deploy below:
   > https://github.com/department-of-veterans-affairs/vets-api/pull/12826

## Active Daily Users Impacted
- How many active users are impacted at this time and day.
   >  don't have an accurate number for users impacted. I'm seeing only about 1k requests to that endpoint per day during the weekend. but this will turn into magnitudes more requests that could overwhelm the servers and effect unknown number of users
## Has fix been confirmed in Staging?
- [x] Yes
- [ ] No

## Description
- Please provide the details/reason for the OOB Deploy
   > when a veteran doesn't have the necessary permissions to access this endpoint, our app hits the endpoint /mobile/v0/user/gender_identity/edit hundreds of times within a few seconds which we're worried this will overwhelm the servers. so If this causes server issues, it can bring down other services provided by the server. 
   
## Verify The following
 - [x] The OOB Deploy Request is after the 2pm EST cutoff for regular deploy.[^1] 
 - [x] The OOB Deploy Request is critical and must be resolved before the next automated deploy.
 - [x] You are prepared to create an Incident Post Mortem[^2] within two business days.

[^1]: (See [Deployment Policy](https://depo-platform-documentation.scrollhelp.site/developer-docs/deployment-policies) and [Deployment Schedules](https://depo-platform-documentation.scrollhelp.site/developer-docs/Deployments.1844641889.html)
[^2]: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/Postmortems

*Performed by Platform Support Team*
 - [ ] PagerDuty OOB Deploy Incident Opened
 - [ ] OCTO-DE staff acknowledgment of Request, via `/pd trigger`
 - [ ] Notification is posted in the appropriate Slack support and team Channels
 - [ ] Infrastructure/Operations has acknowledge the Requests
 - [ ] Security Team has Reviewed the requests

 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-product-support

**Comment by ryan-mcneil** [comment]
@chrisj-usds Provided approval in the respective [Slack thread](https://dsva.slack.com/archives/CBU0KDSB1/p1685134676915319) and @RachalCassity performed the deploy
