### ISSUE TITLE
CF / RVR: Usability Testing Discussion Guide

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#5922]
Create interview discussion guide
Review with UX team
Update based on feedback
Coordinate with prototype designer

**Comment by amyknox** [comment]
From Crystabel via design review: Try Asking users during testing what the amount of these caution flags mean to them (especially the ones with 2-3 flags). In the design system's usability section for alerts, it says "But don’t overdo it (alerts)— too many notifications will either overwhelm or annoy the user and are likely to be ignored." I suggest asking whether these alerts overwhelm or successfully communicate to them that they should avoid the school.

**Comment by amyknox** [comment]
Notes from PI Planning

We Will Test
	• Are users less likely to click thru on results with generic or specific warnings?
	• Do icons add value or distract from caution? 
	• What caution alerts do participants perceive as most critical and would most likely deter them from applying to schools?
Order of accordions on profile pages (do warnings need to move? Up or down?)
