### ISSUE TITLE
Contact Center Review for [Authenticated Experience My VA - onsite notifications design update]

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#59228]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
We launched onsite notifications on My VA in summer 2022. We have an updated design of the onsite notifications which leverages a new design system notification component. The latest version of the guide we're submitting for review updates screenshots to reflect the new design system component. The text content of the guide has not changed as the functionality has not changed.

### Launch Date
Aiming to release the component on My VA in June 2023

### Version Number
My VA Product Guide version 7

### Product Guide
[My.VA.2.0.Product.Guide.Version.7.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/11580015/My.VA.2.0.Product.Guide.Version.7.docx)

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
Received today, will review.

**Comment by starlow00** [comment]
Draft looks good, sending to VEO for review.

**Comment by starlow00** [comment]
No changes from VEO. However, additional changes have been sent, will add and update.

**Comment by starlow00** [comment]
(Updated image of current VA.gov home page, uploaded to VEO)
