### ISSUE TITLE
Design Intent  - IA Feedback - Authenticated Experience, Profile, Notification Settings, Updates to Edit Flow (first example using mobile number)

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#59251]
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions
- Sorry to miss this meeting in person. I have watched the recording want to thank everyone for the background and presenting the research at a high level.
- First, I am glad to see this work. I have also been confused with the movement between pages in order to edit information in profile. I think this will be a nice improvement, and we always appreciate research backed improvements / suggestions that come right from Veterans!
- I agree with @humancompanion-usds that this new page feels a little unmoored without any contextual information about what area of the website you're in. The "eyebrow" Matt mentioned could definitely help (example below), but I think there are options in how to handle it. In general, just make sure to add some type of content that helps clarify for Veterans where this page is located. Take a look at the [DS subtask flow pattern guidance](https://design.va.gov/patterns/help-users-to/complete-a-sub-task) to inform your work as you iterate.

<img width="320" alt="Screenshot 2023-05-23 at 11 11 15 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/115033532/ca478c7f-366c-40d7-8e47-dce7b19b8f2d">

**Comment by andaleliz** [comment]
Thanks @sterkenburgsara, this makes sense and I appreciate the feedback! I'll work on this in the current or next sprint.

**Comment by andaleliz** [comment]
I would just use this ticket to create the work @mtcA6

**Comment by andaleliz** [comment]
We're going to close this ticket since it has the same feedback as #[59158](https://github.com/department-of-veterans-affairs/va.gov-team/issues/59158), and we'll leave comments on that one.
