### ISSUE TITLE
CF: Prototype review w DEPO pre-UT

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#5926]
Review Prototype w DEPO 
- Design 
- 508 
- Content (invite, optional)

**Comment by ccruzgra** [comment]
Met with DEPO earlier to review our latest enhancements. 

Meeting outcomes will be posted here:
https://github.com/department-of-veterans-affairs/va.gov-team/edit/master/products/education-careers/school-comparison-tool/design/caution-flags/design-history.md
