### ISSUE TITLE
[Other - Accessibility] Link opens in new tab without warning users. (00.00.1)

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#59264]
#### VFS team name
Benefits Disability Experience Team

#### VFS product name
Disability Comp Application (21-526 EZ), Add Self Assessment Part A form information to BDD workflow

#### VFS feature name
Add Self Assessment Part A form information to BDD workflow

#### Point of Contact/Reviewers
Brian DeConinck - @briandeconinck - Accessibility

*For more information on how to interpret this ticket, please refer to the [Anatomy of a Staging Review issue ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Anatomy-of-a-Staging-Review-Issue-ticket.2060320997.html) guidance on Platform Website.

---

### Platform Issue
No VA.gov Experience Standard for the issue found.

### Issue Details
On [/supporting-evidence/additional-evidence/](https://staging.va.gov/disability/file-disability-claim-form-21-526ez/supporting-evidence/additional-evidence) and on [/confirmation/](https://staging.va.gov/disability/file-disability-claim-form-21-526ez/confirmation), the link to the Part A Self-Assessment opens in a new tab. That makes sense for this situation, but opening in a new tab without warning can be disorienting for screen reader users who don't see the visual cues that they've shifted to a new tab, and can create cognitive load issues more broadly.

### VA.gov Experience Standard
[Category Number 00, Issue Number 00](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

### Platform Recommendation
Include a warning about this behavior in the link text, eg. `<a href="..." target="_blank">Separation Health Assessment - Part A Self-Assessment (opens in a new tab)</a>`.

### Acceptance Criteria - 
- [ ] the change is implemented for all occurrences (4 pages)
```
/introduction
/supporting-evidence/evidence-types-bdd (when you select no)
/supporting-evidence/additional-evidence
/confirmation

```
---

### VFS Guidance

- Close the ticket when the issue has been resolved or validated by your Product Owner
- If your team has additional questions or needs Platform help validating the issue, please comment on the ticket
- Some feedback provided may be out of scope for your iteration of the product, however, Platform's OCTO leadership has stated that all identified issues need to be documented and it is still your responsibility to resolve the issue.
- If you do not believe that this Staging Review issue ticket is the responsibility of your team, comment below providing an explanation and who you believe is responsible. Please tag the Point of Contact/Reviewers. Governance team will research and will follow up.
-

**Comment by christinec-fftc** [comment]
This is a trivial fix from an implementation standpoint, but was wondering if there's any concern about having long link names. There is an interesting approach described [here](https://www.ucop.edu/electronic-accessibility/web-developers/inform-users-when-a-link-opens-in-a-new-window.html) using an icon with alt text

**Comment by lydiahooper** [comment]
@christinec-fftc @RakshindaAslam this is another ticket we might want to discuss
