### ISSUE TITLE
[UX] Create Poster Versions to Include Information About Checking-in using the Mobile App

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#59276]
## Scenario
The Mobile App team is not including a push notification as part of the MVP. We have been asked to add information to the posters to let Veteran know that they can check-in using the Mobile App.

## Tasks
- [x] Update Poster to Include Information About Checking-in using the Mobile App

**Comment by benbrasso-agile6** [comment]
Starting to think about this. Might do a low-fi sketch.

**Comment by kellysmith1008** [comment]
@benbrasso-agile6 I thought I was on this ticket so I created a mockup that I shared with Zach. I don't think this needs to be something super complicated, but feel free to use or discard what I created (and keep in mind I used an old version of the poster so I didn't screw anything up with the current version, so Zach will need to update this for the current version if you want to use it) https://www.sketch.com/s/d7b25f47-70fe-4d14-88b4-ffa4ec4ef63d

**Comment by benbrasso-agile6** [comment]
No problem. I'll take a look.

**Comment by benbrasso-agile6** [comment]
Options: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1685971544982/d2f440b3f0a725bb46bc4d8ff851486771b58094?sender=u37bb983bd3fc3cc00c7d3286

Will share at UX Sync and collect feedback

**Comment by benbrasso-agile6** [comment]
@zach-park create options 4 and 5 https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1685971544982/d2f440b3f0a725bb46bc4d8ff851486771b58094?sender=u37bb983bd3fc3cc00c7d3286

**Comment by benbrasso-agile6** [comment]
Actually, 5 doesn't really work because it's missing an action on the poster now. I would just do 4 for now and see how it turns out.

**Comment by benbrasso-agile6** [comment]
@zach-park I added the feedback into sketch. I would go ahead and make those changes. But, we will want to see if Martha has feedback. Looks like she's out of the office today. 

I'm going to move this into validate for now

**Comment by zach-park** [comment]
Here is the link to the various sizes and language poster versions: 
https://www.sketch.com/s/9798426e-bba3-46dd-9d87-73d77dcf6599
