### ISSUE TITLE
[DEV] Make Domain Model for Editing Veteran Information Online

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#59286]
As a team member, I would like a diagram for how Veteran information is edited, stored, and transferred online so that I understand how adding in EZR information will impact the ecosystem, and so that I can have a visual to use to discuss this with other teams. 

- Look for any existing domain model(s) that capture how Veteran Info is changed online
- Look for Domain Models that capture how EZR is updated in the Enrollment System (ES) (would probably be good to ask Josh Faulkner)
- Create/update Domain Model for how, and what, Veteran Information is currently updated online
- Add in how EZR information (financial, Next of Kin, Address, Name/Gender, etc.) will be update
- Present to teams this impact and tweak as needed
- **Deliverable:** An updated Diagram that shows how EZR information will be updated and what it impacts

**Comment by lihanli** [comment]
@alexseelig this is my conversation with josh faulkner
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/830084/2bcafc5e-3fe2-4bd2-94a9-fcd968657ed4)

**Comment by lihanli** [comment]
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/830084/8081369e-ef23-432a-a975-643d115285ff)
