### ISSUE TITLE
[Design] Create Final Wireframes for Adding Mobile App Info to the Check-in Login Page

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#59282]
## Scenario
The Mobile App team is not including a push notification as part of the MVP. We have been asked to add information to the Check-in lo-in page to let Veteran know that they can check-in using the Mobile App.

## Tasks
- [ ] Create final mockups with callouts 
- [ ] Decide: Should a content and accessibility review be part of this ticket or separate tickets due to scope?

## Acceptance Criteria
- [ ] UI review meeting with product/UX team for feature capabilities
- [ ] UI review meeting with engineering for layout and callouts (can be the same meeting as above)
- [ ] Wireframe available on Sketch Cloud
- [ ] If the wireframes applies to an error state or text message, then update the [GitHub source of truth](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/design/text-and-error-messages.md) documentation.

**Comment by benbrasso-agile6** [comment]
No feedback via https://dsva.slack.com/archives/C022AC2STBM/p1686327940875589?thread_ts=1686080601.673549&cid=C022AC2STBM

Closing
