### ISSUE TITLE
Test Station & Facility Travel Access

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#59284]
## Tasks
- Test the feature to allow a station list and optional facility lists for the travel claims feature

**Comment by brianseek** [comment]
Tested this functionality on a review environment with stage data. 

This environment only has clinic 195 in station 530 enabled for travel claims: http://7ad15c09d8a44222cf692559b732aaf3.review.vetsgov-internal/

I tested with an appointment in clinic 64 and I get the travel questions on stage, but not in the review environment.
Testing with an appointment in clinic 195, shows travel questions in review environment and stage.

Moving to validate incase others want to confirm for themselves. To test, create an appointment in stage and test here: http://7ad15c09d8a44222cf692559b732aaf3.review.vetsgov-internal/

cc. @loripusey @wullaski

**Comment by loripusey** [comment]
I will take your word for it; with GA4 I don't think I'm going to have a lot of free time
