### ISSUE TITLE
RVR: Secondary Research

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#5929]
Review secondary sources including va.gov, edu journey, edu roadmaps, etc. 
Document observations, findings in Mural

**Comment by amyknox** [comment]
Random sources from PI notes... 
SVA - Student Veteran Association
Scholar.google.com

**Comment by amyknox** [comment]
Mural to capture findings" https://app.mural.co/t/bahdigitalexperience6902/m/bahdigitalexperience6902/1581520580641/faca0e2643fea6730c281f5fadcf062fc1a3b8ae

**Comment by JLynnJ** [comment]
Full documentation of findings in GitHub:

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/colmery-act-2019/research/reducing-veteran-risk/scholarly-research.md
