### ISSUE TITLE
Evaluate our use of React Router

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#5930]
@jbalboni commented on [Wed Nov 28 2018](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/15363)

Do we need to use React Router? If we do, we should upgrade to the latest. If not, we should research other libraries and find a path forward.

RR and the History module are pretty large, so if we can move away from them it'd be helpful.

---

@rianfowler commented on [Fri May 24 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/15363#issuecomment-495690482)

might be good to centralize routing concern- I've seen routing done in several places in view components instead of through a centralized call.

**Comment by meganhkelley** [comment]
Evaluate as part of #27348
