### ISSUE TITLE
FE | Profile | Direct Deposit | Fix links in CreateAccountLink component

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/va.gov-team#59300]
## Issue Description
Spacing on links is off in `CreateAccountLink`

![Screenshot of direct deposit page with links to create account showing incorrect padding](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8332986/dfd8ab59-8fce-4237-aabf-6e1db6bf23dd)

## Front end tasks
- Adjust padding to make icons line up with link text
- Ensure the page is styled according to design spec.
- Run axe checks using the Chrome or Firefox browser plugin
- Test for color contrast and color blindness issues
- Zoom layouts to 400% at 1280px width
- Test with 1 or 2 screen readers
- Navigate using the keyboard only

## Acceptance Criteria
- [x] Designer comments on this issue to approve page styling
- [x] Tests pass

**Comment by adamwhitlock1** [comment]
Having a hard time reproducing the styling issue locally. I am actually not seeing the icons display at all, and there doesn't seem to be anything indicative that they would have icons in the markup itself. Going to continue to investigate in staging.

![Screenshot 2023-06-29 at 10.46.40 AM.png](https://images.zenhubusercontent.com/60ddebd504ce2452d0e0fa92/c73987d2-5943-4238-8084-ddebd8700e8f)

**Comment by andaleliz** [comment]
@adamwhitlock1 not a particular user that I can remember, but maybe the component got updated? It looks like originally it was the [secondary action link component](https://design.va.gov/components/link/action) and now they're displaying a link a regular old link.

Aaaand - I just checked - the [Sketch files show a regular old link for this alert](https://www.sketch.com/s/ebd4596f-0707-46cb-941e-247a808725cc/a/AZnYY8R) anyway, so maybe somehow Sketch and the FE started chatting one night and lined themselves up automagically? 😆 that is so weird but I think no further work is needed, other than maybe understanding what exactly happened?

**Comment by adamwhitlock1** [comment]
Thanks for checking the design files and linking them here! I'm not exactly sure either, but I'm glad the design matches what is in production. I'll close this now.

As far as how it got this way, the most recent update to the link code was [9 months ago here's the PR](https://github.com/department-of-veterans-affairs/vets-website/pull/22343) and in that PR there are screenshots showing the links without the icons so :shrug:
