### ISSUE TITLE
[FE] Severity 3: Web #4 - Pattern - Screen Title Not Specific

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#59312]
## Issue
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/86678742/d4724b5a-939f-44b1-b776-0044cd547d14)

Original Spreadsheet Source for Issue: [Mobile Audit 05102023 Patient Check-in (eCheck-in  Pre-Check-in) Web.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/11614848/Mobile.Audit.05102023.Patient.Check-in.eCheck-in.Pre-Check-in.Web.xlsx)

## Tasks
- [ ] [FE] Resolve issue
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by lee-delarm6** [comment]
This is for us on Check-In team, the change should be able to be made through the page level components (not design, ours). It looks like there's 30-40 areas to update. This may increase as certain pages may have multiple states that the ticket requests we address.

The overall complexity is not high, but making sure we address all the pages may take a moderate amount of time

**Comment by loripusey** [comment]
Since this is a low priority, moving to CIE Tech Debt

**Comment by loripusey** [comment]
too old, closing
