### ISSUE TITLE
[FE] Severity 10: Web #11 - In the header: The currently-selected language (for example,  "English") is indicated visually with bold text,  so this requires an equivalent indication for assistive technology.  

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#59322]
## Notes
LP: I'm guessing that we don't have any control over this control?

## Issue
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/86678742/145d5e2d-ee4c-4b0b-be4f-57ad3527143b)

Original Spreadsheet Source for Issue: [Mobile Audit 05102023 Patient Check-in (eCheck-in  Pre-Check-in) Web.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/11614848/Mobile.Audit.05102023.Patient.Check-in.eCheck-in.Pre-Check-in.Web.xlsx)

## Tasks
- [ ] [FE] Resolve issue
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by lee-delarm6** [comment]
I don't think we have control over this component, likely Design team on this

**Comment by loripusey** [comment]
Submitted Platform support ticket for the Design System [here](https://dsva.slack.com/archives/CBU0KDSB1/p1687293774975819); closing
