### ISSUE TITLE
[FE] Severity 10: Web #13 - The dialog that appears when user activates "Talk to the Veterans Crisis Line now" control (at the top or bottom of the Screen) has been implemented as role="alertdialog".  This is an aggressive form of dialog,  and has specific requirements,  such as setting focus to the first interactive control (in this case,  the "Close" button) and applying the aria-modal="true" attribute.  

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#59325]
## Notes
LP: I'm guessing that we don't have any control over this control?

## Issue
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/86678742/f471b137-758d-4d75-a51e-94a2c2f7b16e)

Original Spreadsheet Source for Issue: [Mobile Audit 05102023 Patient Check-in (eCheck-in  Pre-Check-in) Web.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/11614848/Mobile.Audit.05102023.Patient.Check-in.eCheck-in.Pre-Check-in.Web.xlsx)

## Tasks
- [ ] [FE] Resolve issue
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by lee-delarm6** [comment]
Looks like a Design team fix, we don't have control over this component at all from what I see

**Comment by loripusey** [comment]
Submitted Platform support ticket for the Design System [here](https://dsva.slack.com/archives/CBU0KDSB1/p1687293774975819); closing
