### ISSUE TITLE
[FE] Severity 10: Web #12 - When screen reader reads content starting at the top of the Screen,  the SR reads invisible content after the VA logo and before the language selection links.  It seems to be an unused progress bar.  SR announces "Progress bar indeterminate.  Finding your appointment".  

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#59324]
## Notes
LP: I'm guessing that we don't have any control over this control?

## Issue
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/86678742/c5e8ae74-1026-4384-90d3-5fb39e2ed6e0)

Original Spreadsheet Source for Issue: [Mobile Audit 05102023 Patient Check-in (eCheck-in  Pre-Check-in) Web.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/11614848/Mobile.Audit.05102023.Patient.Check-in.eCheck-in.Pre-Check-in.Web.xlsx)

## Tasks
- [ ] [FE] Resolve issue
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by lee-delarm6** [comment]
We don't have control over that section, I'm not sure who does to be honest as it may not be design team

**Comment by loripusey** [comment]
Submitted Platform support ticket for the Design System [here](https://dsva.slack.com/archives/CBU0KDSB1/p1687293774975819); closing
