### ISSUE TITLE
Copyedit for 2023 disability hub audit: The VA claim process after you file a claim

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#59340]
## Issue Description
For the annual audit of all the pages in the disability hub, OCTO content lead assessed these 6 content issues on the [VA claim process after you file a claim](https://www.va.gov/disability/after-you-file-claim/) page and made changes that need copyediting before we republish the page:

- The intro paragraph has no more than 2 to 4 sentences and is within 200 to 400 characters with spaces
- Header levels are hierarchical (noting here the problem with our "number of days" component and that I've added it to the backlog ticket to fix at a later date)
- The page has no broken links
- Text links have purpose and target
- The content is free of ability-focused language (view, walk, see, hear)
- Relevant terms from page are in content brief and any relevant backlog work is noted

## Additional questions to ask SME when you request an accuracy review:
- Are all the claim statuses in the subway map still correct? (show screen shot of subway map)--as in, do we use these exact labels still or do we need to update these at all?
- Logic of this sentence in No. 2 in the subway map: "Your claim will move to step 3 if we don't need anymore evidence to support it." This doesn't make sense because No. 3 is about "evidence gathering." I think we could probably just cut that sentence entirely (as Paul if he agrees). If we end up reworking the sentence instead, we should lead with the conditional if-statement.

---
### Copyedit the changes made 
(review revisions only, not the full page) to https://www.va.gov/disability/after-you-file-claim/
- [x] The intro paragraph has no more than 2 to 4 sentences and is within 200 to 400 characters with spaces
- [x] Header levels are hierarchical (noting here the problem with our "number of days" component and that I've added it to the backlog ticket to fix at a later date)
- [x] The page has no broken links
- [x] Text links have purpose and target
- [x] The content is free of ability-focused language (view, walk, see, hear)
- [x] Relevant terms from page are in content brief and any relevant backlog work is noted

### Check accuracy with SME and publish
- [x] Request review from SME Paul Shute
- [x] Incorporate any edits from SME to Drupal
- [ ] Add notes from him to the record of audit for this page
- [ ] Publish page
- [x] Record the Flesch-Kincaid before and after grade level

<details>
<summary>Prepublishing checklist</summary>

### Before you begin
- [ ] Confirm that there are no updates in draft by other content authors that aren't ready to be published. Check the revision log and then confirm with the content author who made the previous edits that the page is ready to publish.

### Accessibility standards

- [ ] If your link or button will take the user off VA.gov, confirm that the text for the link or button contains a purpose and a target. The user should be able to tell from the link or button text what the call to action is (the purpose) and where they will end up if they click on the link (the target). The following link is an example of this: <br>[Read more about making links accessible on AccessibilityOz](https://www.accessibilityoz.com/2014/02/links-and-accessibility/)</br> 
**Note:** When you direct the user to another VA.gov page, the link only needs to contain text indicating purpose (the call to action).
- [ ] Confirm all phone numbers are in aria labels. [Learn how to code numbers with aria labels](https://design.va.gov/content-style-guide/dates-and-numbers#phone-numbers)
- [ ] Confirm that the hierarchy of section and subsection titles is correct (H1 to H2 to H3—levels shouldn't be skipped). [Learn more about section titles](https://design.va.gov/content-style-guide/page-titles-and-section-titles)
- [ ] Replace any sighted language ("view," "see," "look") with a word that's inclusive of our screen reader users ("check," "go to," "review").
- [ ] Avoid using other ability-focused language. ("hear back from")

### Link standards

- [ ] Confirm that links work (aren't broken—no error message) and point to the intended page (you pasted in the correct URL or chose the correct node ID).
- [ ] Confirm all link text is 100 characters or less.
- [ ] Check that you've selected a node ID for all links pointing to VA.gov (internal) pages. Only paste in a URL if the page you're linking to doesn't live in our CMS (isn't one of our modernized pages). [Learn how to add node IDs in Drupal](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/how-to-do-different-tasks/linking-with-node-ids.md) 
- [ ] Check that all anchor/jump links are pointing to a node followed by # and the header identifier (Example: /node/47278/#information-for-survivors). Double check all anchor/jump links post-publish. 

### CMS standards

- [ ] Make sure all apostrophes and quotation marks are curly not straight. (Once this is automatic in Drupal, we can remove this item.)
- [ ] If there are alerts at the top of the Drupal Edit node for broken links, redirected links, or links to unpublished pages, correct the issues. If there's an alert for a broken link but the link is actually working, report the issue to the CMS help desk. [Read more about link alerts in the CMS knowledge base](https://prod.cms.va.gov/help/cms-basics/how-to-fix-broken-links-and-redirects)
- [ ] If publishing a brand-new page, confirm the left nav and url are set up correclty. (If the page is a child page, the section needs to be the same as the parent page in order for the left nav to show.) [Learn how to set up a url and left nav in Drupal](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/how-to-do-different-tasks/adding-left-nav-and-url.md)
- [ ] Check if the page has a new or updated alert. If so, publish the alert separately. 

### Additional checks for translated articles
- [ ] If we don't have updated translated versions, add the alert that links to the corresponding English page and lets users know that the translated pages aren't up to date. 

</details>

## Acceptance Criteria
- [ ] Updates are live on the site

**Comment by megzehn** [comment]
Update: Paul's team connected us with a new team to review. Matt, the new SME, returned feedback to us on 10/20. Beth, Chelsea, and I are meeting on 10/27 to discuss next steps!

**Comment by megzehn** [comment]
Update: SME agreed with our changes, and we published. 

I also updated the [GH file](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/governance/annual-audit/2023/disability/after-you-file-your-claim/the-va-claim-process-after-you-file-your-claim.md) for this page. Moving to validate.
