### ISSUE TITLE
Claim Type

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#59360]

**Comment by nnicholas7** [comment]
Policy information about Claim Type can be found here: https://docs.google.com/spreadsheets/d/1MUFiKgz7NDZ__xFDRbGgJEFHfmOsWYPOyXe3C7tsSb8/edit#gid=810102445

**Comment by austinjprice** [comment]
@nnicholas7 @juliepedtke closing ticket
