### ISSUE TITLE
Medical Records

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#59369]

**Comment by nnicholas7** [comment]
Policy information about medical records can be found here: https://docs.google.com/spreadsheets/d/1MUFiKgz7NDZ__xFDRbGgJEFHfmOsWYPOyXe3C7tsSb8/edit#gid=810102445

**Comment by austinjprice** [comment]
@juliepedtke @nnicholas7 closing ticket
