### ISSUE TITLE
[FE] Design for mobile check-in from a CHIP perspective (for fully authenticated check-in)

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#59387]
For Mobile app to use the check-in endpoints, we need to create CHIP endpoints that support a fully-authed check in.

AC:

- Create design documents for CHIP endpoints (sequence diagrams, component diagram ([example](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/engineering/architecture-diagrams)))

**Comment by loripusey** [comment]
@wullaski is this one done?
cc: @anita-halici
