### ISSUE TITLE
FE | Profile | Contact Information | Discovery | Isolate required components to platform level folders

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/va.gov-team#59386]
## Issue Description
To allow increased reusability for profile information (specifically contact info), an engineer should be able to import the needed components to embed updating capabilities into any form. The gist is that there is some code in the platform/vap-svc folder and some code in the actual personalization application that is getting imported in other apps. 

All code should just be imported from the platform side of things, and the application level code should just host code related to the profile application itself.

## Front end tasks
- Discover what LOE is required to move all required parts of code from profile to platform based folders.
  - and example of a PR that is attempting to import from profile is https://github.com/department-of-veterans-affairs/vets-website/pull/24389
  - for now contact information should be the focus of isolating all needed components to platform folders

## Acceptance Criteria
- [ ] Discovery is done and documented
- [ ] Further tickets are created to piece out this work
- [ ] Audit of any application changes is done and any compatibility based changes are summarized in a ticket for that work to ensure that any impacted applications do not see any downtime from the changes.

**Comment by mtcA6** [comment]
duplicate - work was completed and is in the forms system already
