### ISSUE TITLE
[BE] Understand and create the design for vets-api module to call CHIP endpoints for full auth check-in

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#59385]
For Mobile app to use the check-in endpoints, we need to create a module within vets-api that mobile code can use.

AC: 
- Create design documents for vets-api module (sequence diagrams, component diagram ([example](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/engineering/architecture-diagrams)))
- Add implementation stories with design details

**Comment by loripusey** [comment]
@randomsync @kanchanasuriya can you point this before planning?

**Comment by randomsync** [comment]
This design is dependent on the overall design + the CHIP API design #59387.  We (all engineers) are continuing to work on figuring out all the details. I think once the CHIP API design is there, we should be able to complete this as well.
