### ISSUE TITLE
[FE] 10-10EZ - Household: Update Dependent card from horizontal to vertical stack view

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#59397]
## Background
Per a recent Design Council meeting ([see notes from Design Council meeting](https://docs.google.com/document/d/1H22K4Pg2GCxqJEH7-2VBn1OaMUtkVccbuDYFH-397XM/edit) (note, no final decision or next steps were listed)), it was recommended that we consider magnification used by Veterans, and how information and actions can be missed when aligned horizontally across the page. 
[Experimental Ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1565)

Updated image below. DSC guidance to not horizontal align as items on the right are often missed with magnification settings. Design updates include a stacked mobile friendly layout:
<img width="302" alt="card design" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/98367393/53dcf7b8-3ea4-4b60-abec-b5b1b5e19bd5">

Currently In staging: 
<img width="629" alt="Screenshot 2023-05-26 at 8 25 29 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/98367393/a316cacb-a304-4c3e-9562-7761642e97cd">

## Tasks
- [ ] Adjust the current state Dependent card from horizonal alignment to a vertical stacked layout - as shown in the image above

## Acceptance Criteria
- Dependents entered and displayed in a vertical stacked layout with action links will be easer to see and use when viewed with screen magnifiers

**Comment by longmd** [comment]
Here is a screenshot of the updated card: 
![Screenshot 2023-06-06 at 12 05 39 PM](https://github.com/department-of-veterans-affairs/vets-website/assets/6738544/c74deb53-2316-4055-aca1-87842ef9d2a4)
