### ISSUE TITLE
[FE] 10-10EZ - Household: Create conditional for Child Educational Expenses page

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#59395]
## Background
During a QA round on the Household section optimization feature, a question came up for the page that displays the Child Educational expenses.
- Can the page be conditional based on birthdate entered (on the previous page), Since it is referring to a specific age range in the question?

### Resources 
- Link to form flow: [Household section form flow](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/p/12B7255E-72F6-4C6A-83C3-81BF9A1CEBDE/canvas)
- ![image.png](https://images.zenhubusercontent.com/6172ff6d924e737b978a12ea/88e5b8a4-e303-4d10-bee2-4aa700b0d325)

## Tasks
- [ ] Make the Dependent Educational Expenses page conditional on the birthdate entered on the previous page.
     -  **Only display** the Dependent Educational Expenses page if the timeframe between the birthdate and the current date is between 18 and 23 years.
     - If the timeframe between the birthdate and the current date is less than 18 years, **do not display** the Dependent Educational Expenses page
     - If the timeframe between the birthdate and the current date is 24 or more years, **do not display** the Dependent Educational Expenses page

## Acceptance Criteria
- The Dependent Educational Expenses page will only display to the Veteran if their dependent's age is determined to be between 18 and 23 years old.

**Comment by longmd** [comment]
@hdjustice / @jessicastump / @davidakennedy , this is functional and in staging.
