### ISSUE TITLE
Install Infrastructure for NewRelic on vets-api

### ISSUE THREAD

**Issue by johnpaulashenfelter** [department-of-veterans-affairs/va.gov-team#5940]
The NewRelic Infrastructure tool requires installation at the base-os layer to instrument Docker containers. 

There are directions for doing it directly: https://docs.newrelic.com/docs/infrastructure/install-configure-manage-infrastructure/linux-installation/install-infrastructure-linux-using-package-manager

And in Ansible: https://docs.newrelic.com/docs/infrastructure/new-relic-infrastructure/config-management-tools/configure-new-relic-infrastructure-using-ansible

**Comment by alexpappasoddball** [comment]
@johnpaulashenfelter would you say this is complete and can be closed now?

**Comment by johnpaulashenfelter** [comment]
Installed and running on staging and production.
