### ISSUE TITLE
[Identity Dashboard] Create ClientConfig Model/Schema

### ISSUE THREAD

**Issue by rileyanderson** [department-of-veterans-affairs/va.gov-team#59418]
## Issue Description
Create client client config and table on Identity dashboard. This should mirror the client config on SiS with additional identifying fields, `synced_at`, etc . 

## Back end tasks
- [x] Migrations
- [x] Model
- [x] Validations

**Comment by bosawt** [comment]
For test stacks, we should synchronously update ClientConfig on Sign in Service when the ClientConfig is updated on the Identity Dashboard

**Comment by bosawt** [comment]
For production stack, we should create a 'shadow object' representing the changes to be made to a ClientConfig.

This should be stored in a database (not redis)

**Comment by aparsley** [comment]
Looks great, thank you for creating this Schema.
