### ISSUE TITLE
Bug: Filter cancelled appointments

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#59414]
## Background
[Slack thread 1](https://dsva.slack.com/archives/C02UP02HHGX/p1684847248762479)
[Slack thread 2](https://dsva.slack.com/archives/C022AC2STBM/p1685655021919689)

## Tasks
- Modify CHIP to return an error from initiate-precheckin if the appointment has been cancelled

## Acceptance Criteria
- SMS messages are not created for cancelled appointments

**Comment by loripusey** [comment]
@brianseek @wullaski updated this ticket based on slack thread number 2

**Comment by brianseek** [comment]
This has been deployed to prod, not sure what the validation chain is going to be for chip prod but I can look at the logs in a week and compare to see if this has helped remove some of the cancelled error page visits

**Comment by brianseek** [comment]
Moving this to closed. The metrics haven't changed much but seem to be trending down since this change. It's hard to tell how many are legitimate canceled appointments though and we don't keep RUM logs for long enough to look back too far.
