### ISSUE TITLE
CT 107: Remove Prod Flag for Update School Locations Section Paging

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#5941]
As a developer, I need to remove the prod flag for the paging updates so that the new functionality is available in the production environment.

## Assumptions:
1. The functionality has been signed off by the UX team.
2. The functionality has been signed off by the EDU team as of  02/14/2020.

## Acceptance Criteria:
1. The functionality in story #4383 is available in the production environment.

## Supporting Artifacts:
1. N/A

**Comment by sonntag-adam** [comment]
Shows in prod build
##
![Screen Shot 2020-02-19 at 1.18.46 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/b1f5a3b6-5f6c-499a-9248-118958e1a856)
##
![Screen Shot 2020-02-19 at 1.19.05 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/e4af0926-df86-49dd-a17b-1c280d79d2cf)

**Comment by ksantiagomorgan6** [comment]
Pull request: 
https://github.com/department-of-veterans-affairs/vets-website/pull/11724

**Comment by sonntag-adam** [comment]
In production, testing passes QA.
