### ISSUE TITLE
Create plan for moving emergency contact fields to My VA

### ISSUE THREAD

**Issue by fmccaf1** [department-of-veterans-affairs/va.gov-team#59421]
## Info
Follow on work from [#58462.](https://app.zenhub.com/workspaces/mhv-on-vagov-top-level-view-62619a987d74510018ecc546/issues/gh/department-of-veterans-affairs/va.gov-team/58462)

At this point, there is no clear plan or decision around where emergency contact name and associated information will live. We need to meet with the authenticated experience team to discuss: 
- Should these fields move over the My VA?
- What language should be used? i.e. Emergency contact vs. next of kin and additional field(s) for email address, phone number(s)?
- What support will the Unauthenticated Experience team need to get these fields moved over?

## Acceptance Criteria
- [x] Set up meeting with Auth Exp team including: Chante Lantos-Swett, Anastasia Jakabcin, Angela Agosto, Travis Cahill, Liz Lantz and on our side, make sure to include Patrick Bateman, Tom Anderson, and Eric Voshall

**Comment by batemapf** [comment]
very relevant thread re: plans of VA Profile and My VA (auth exp) teams to add emergency contact and NOK to My VA / VA.gov Profile

https://dsva.slack.com/archives/C7TE0PFTL/p1685998262690309?thread_ts=1685977200.921009&cid=C7TE0PFTL

**Comment by fmccaf1** [comment]
[Slack thread on wording / explanation around "next of kin" language](https://dsva.slack.com/archives/C01K37HRUAH/p1687290331801719)

**Comment by carafrissell1** [comment]
1010 Enrollment currently does not collect Next of Kin or Emergency Contact info 
https://dsva.slack.com/archives/CMJ2V70UV/p1688153443697539

**Comment by batemapf** [comment]
to split hairs a tiny bit, the VA.gov Health Care Application (which is commonly known as the "online 10-10EZ") does not collect next of kin and emergency contact information (as indicated in that slack thread). The paper 10-10EZ _does_ collect this information. I imagine at some point, a veteran who has applied for health care using the VA.gov Health Care Application will be asked for emergency contact and next of kin information to complete their registration.

**Comment by carafrissell1** [comment]
@batemapf that's useful information thanks for sharing.  I think then it would be useful to know 1) if those responses are coming over to a digital format and 2) where is it stored and who has access and edit power to it

**Comment by A6-toma** [comment]
Closing this ticket. The plan moving forward is for Cartographers team to conduct technical and use-case discovery and then coordinate with the Authenticated Experience team to make a final determination on who will do what work.
