### ISSUE TITLE
Regression Test 

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#5944]
Manual test of all 3 user flows

AC:
• none of the service calls break
• all user flows still work as expected
    - view appts/requests
    - cancel appts/requests
    - request VA appt
    - request CC appt
    - schedule VA appt
- [ ] Per Jeff also "the parent-code issue in staging, so we probably want to do some regression testing in staging to make sure nothing else in the 4.18.3 release will trip us up."

**Comment by lenaecb** [comment]
@jbalboni - how would we go about verifying the parent-code issue? We did regression and all was still seems up to snuff.

**Comment by jbalboni** [comment]
@lenaecb The VA flow was completely broken by the parent-code issue, so I think being able to make it through that flow is enough testing. There's an additional edge case around nested facilities that we can't create in staging, but I was able to create mock data locally to replicate the issue. The regression testing was mostly to make sure nothing else other than the parent-code issue had broken. I think we can close this ticket.

**Comment by lenaecb** [comment]
Awesome, thank you @jbalboni ! Closing now.
