### ISSUE TITLE
Sidekiq Admin UI access for [individual]

### ISSUE THREAD

**Issue by jamiew-vmware** [department-of-veterans-affairs/va.gov-team#59444]
### Your Name

Jamie Wang

### Your GitHub handle (Sidekiq Admin UI access is managed through GitHub)

jamiew-vmware

### Team, Role, and Company of the target individual

VMware Tanzu Hello World VFS Team, PM, VMWare Inc.

### COR Name

Other - please specify in 'Additional Notes'

### Please confirm if you are on the VFS Team Roster or Platform Team Roster

- [X] [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Sidekiq UI Access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [ ] production (if requesting, justify prod access in 'Additional Notes' section)

### If PRODUCTION ACCESS is required, confirm/complete ONE of the following

- [ ] I have an AWS Username and it is listed in [here](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf)
- [ ] I currently have access to vets-api Production Terminal via ArgoCD
- [ ] I've attached a screenshot of my E-QIP Transmittal Notice E-mail (Drag or Copy/Paste in Additional Notes Section below)

### Additional Notes

COR is Doug Davis

**Comment by jamiew-vmware** [comment]
I'd like to see what it takes to get access. So from here, if I'll be provisioned an account with username/password or what. I don't need PRD access for sure, but if I can still go through this process, I'd appreciate it.

**Comment by ryan-mcneil** [comment]
@jamiew-vmware If the developer was to follow the instructions above, they would have access as laid out above. This isn't an "account" given out to anyone, it is a permission given to those who need it. And those who need it would hopefully understand how to use it and access it. I believe that's explained in the document that you linked me to in the previous ticket, that I've now gone through and updated

**Comment by jamiew-vmware** [comment]
Yep, that does! Thanks for your help.
