### ISSUE TITLE
Add "schedulable" query parameter to MFS facilities call

### ISSUE THREAD

**Issue by cferris32** [department-of-veterans-affairs/va.gov-team#59503]
MFS is changing their `/facilities` endpoint to accept a `schedulable` query parameter in order to correctly filter which facilities a veteran can schedule at. We need to make a change in our vets-api facilities call to send this parameter.

MFS documentation: https://coderepo.mobilehealth.va.gov/projects/VDMS/repos/mobile-facility-service/browse/mobile-facility-service/src/main/resources/swagger.json?useDefaultHandler=true#221

Related CKM ticket: https://issues.mobilehealth.va.gov/browse/CKM-16591

AC:
[ ] - vets-api passes the `schedulable` query parameter in its call to the `/facilities` endpoint

**Comment by ldelacosta** [comment]
@cferris32 - We created a feature toggle for this work (#60614). I referenced the ticket as the dependency. Please reach out if you have any questions.  Thanks!

**Comment by ldelacosta** [comment]
This effort is completed under the feature toggle `va_online_scheduling_required_schedulable_param`
@marcynadeau - let me know if it's OK to turn it on for all users in staging or do you have specific users? Please let me know when you have a chance.

**Comment by marcynadeau** [comment]
Testing completed.  

SCENARIO #1:   Facility Classification is Valid for Use in VAOS.  - NO HARM TESTING
Expected resulted:  Site can be selected on Choose a VA location page and no errors display in dev tools.  
Facility Classification in Staging.  
#1.1:  Multispecialty CBOC:  
983GC Fort Collins – Direct Schedule Amputation = Yes 36 mos.  john.morrison@id.me.  Fort Collins has clinics configured for direct scheduling.  In VAOS select type of care =Amputation.  Choose a VA Location = Fort Collins.  Expected Results:  Choose a VA Clinic Page displays.  
984GA Middletown – Direct Schedule Sleep = Yes 12 mos.  jacobreid.r.iasimone@id.me.  Fort Collins has clinics configured for direct scheduling.  In VAOS select type of care =Amputation.  Choose a VA Location = Fort Collins.  Expected Results:  Choose appointment date/time page displays.
#1.2:  Other Outpatient Service (OOS):  
983GB Sidney – Direct Schedule Ophthalmology = Yes Any.  kidys.b.quankep@id.me .  Sidney has clinics configured for direct scheduling.  In VAOS select type of care = Ophthalmology.  Choose a VA Location = Sidney.  Expected Results:  Choose a VA Clinic Page displays.  
984QA Rawlins – Request Audiology = Yes Any.   kidys.b.quankep@id.me.  In VAOS select type of care = Audiology.  Choose a VA Location = Rawlins.  Expected Results:  Choose appointment date/time page displays.  
#1.3:  Primary Care CBOC. 
983QD Direct Schedule Mental Health.  Cecil.morgan@id.me.  In VAOS select type of care = Social Work.  Choose a VA Location = Loveland.  Expected Results:  Choose a VA Clinic Page displays.
983GD Loveland.  Direct Schedule Social Work = Yes 12.  Cecil.morgan@id.me.  In VAOS select type of care = Social Work.  Choose a VA Location = Loveland.  Expected Results:  Choose a VA Clinic Page displays. 
984GB Lima.  Request Optometry = Yes Any.   brienne.b.ferrara@id.me.  In VAOS select type of care = Optometry.  Choose a VA Location = Lima.  Expected Results:  Choose appointment date/time page displays.
#1.4:  VA Medical Center VAMC. 
983 Cheyenne. Direct Schedule Clinical Pharmacy = Yes 12.  Cecil.morgan@id.me.  In VAOS select type of care = Clinical Pharmacy.  Choose a VA Location = Cheyenne.  Expected Results:  Choose a VA Clinic Page displays.
984 Dayton VAMC.  Request Primary Care = Yes Any.  Cecil.morgan@id.me In VAOS select type of care = Primary Care.  Choose a VA Location = Dayton.  Expected Results:  Choose appointment date/time page displays.


SCENARIO #2:   Facility Classification is NOT Valid for Use in VAOS.  
Expected Result:  Site can NOT be selected on Choose a VA location page and no errors display in dev tools.  
Any patient
Go into VATS and configure each of these sites for requests as indicated
2.1:  Extended Care Site (Community Living Center) (Stand-Alone):  983QB Torrington VA Mobile Clinic - Primary Care Request = Yes.   Choose a VA Location = Site NOT selectable.  
2.2:  Health Care Center (HCC):  983QF-Cheyenne VA Mobile Clinic - Mental Health Request = Yes.   Choose a VA Location = Site NOT selectable.  
2.3:  MCS:  983GE Northern Colorado VA Clinic -  Audiology Direct Schedule = Yes.  Choose a VA Location = Site NOT selectable
2.4: Residential Care Site (MH RRTP/DRRTP) (Stand-Alone):  983HK-Wheatland VA Mobile Clinic - Food and Nutrition Direct Schedule = Yes.  Choose a VA Location = Site NOT selectable


SCENARIO #3:  Facility Classification = NULL
Expected Result:  Site can NOT be selected on Choose a VA location page and no errors display in dev tools.  
983PP Jackson Hole Clinic
3.1 Set all types of care to Yes.  Primary Care Request = Yes.   Choose a VA Location = Site NOT selectable. Repeat for other types of care.

**Comment by ldelacosta** [comment]
This has been validated. Closing out the ticket and no new issues to report.
