### ISSUE TITLE
Adding Tolase Akinwale to DSVA Slack

### ISSUE THREAD

**Issue by dawnpruitt** [department-of-veterans-affairs/va.gov-team#59513]
Please add Tolase Akinwale as a full member. He is a new Civic Actions Dev Ops Engineer on the CMS Team who will require visibility into many channels. Thank you!

**Comment by LEHigley** [comment]
i need an email address @dawnpruitt

**Comment by dawnpruitt** [comment]
Sorry about that @LEHigley - it is tolase.akinwale@civicactions.com
