### ISSUE TITLE
[ISSUE] Invalid email validation message references unhelpful Regular Expressions

### ISSUE THREAD

**Issue by NB28VT** [department-of-veterans-affairs/va.gov-team#59510]
## Issue Description
When a user enters an invalidly-formatted email into the email field on the "Contact information" page, they get a message telling them to use an accepted email format. However, the examples they are given just list [Regular Expressions](https://medium.com/factory-mind/regex-tutorial-a-simple-cheatsheet-by-examples-649dc1c3f285) that presumably appear in the actual validation code somewhere.

Regular Expressions are confusing for developers who work with them from time to time, let alone anyone else filling out the form. The common way to communicate to the user which format they should use for an email would be something like "example@example.com"

![Screenshot 2023-05-26 at 12.04.30 PM.png](https://images.zenhubusercontent.com/647627f92b5e617343beedd1/b0b8d2dd-7230-4f9c-ac3f-70a38852457a)

### Information needed to assess the severity of the issue
- Users Impacted:   All of them  
- Issue Impact: Presumably the user has no idea what the problem is and they have to retry their email       
- Workaround: If a user has a valid email, they probably typed it wrong so would eventually figure that out            
- Legal Requirement:    
- Loss of Service:       
- Permanent Impact:   
- Vulnerability:      

### Information that aids in the research and troubleshooting of the issue
- Date and Time of Issue:     
- Form/Page of Issue: `disability/file-disability-claim-form-21-526ez/contact-information`         
- Error Message:              
- How to reproduce:           
- Unique IDs:                 
- Application ID:             
- Hardware Issue Observed On: 
- Browser type / version:
- Case#, if available: 
- Reporter name in va.gov: 

### Any Additional Information:

Acceptance Criteria:

Update error message to follow the design as listed here:https://design.va.gov/patterns/ask-users-for/email-address for these scenarios:

- [ ] When a user doesn’t enter an email address: Say ‘Enter an email address’ When a user enters an invalid email address:

- [ ] Say ‘Enter a valid email address’ When an email address is above the 50-character limit:

- [ ] Say ‘We don’t support email addresses that exceed 50 characters’

**Comment by mchae-nava** [comment]
Issue has the potential to impact all users, but likely only blocking for a very small subset (those not familiar with emails). However, the error message is not helpful to a majority of users. Solution involves design copy for an error message, and then frontend implementation of catching the error to display the new error message

**Comment by lydiahooper** [comment]
We are planning to remove the validation of this field per https://github.com/department-of-veterans-affairs/va.gov-team/issues/57392

**Comment by austinjprice** [comment]
Yes, we will review and combine with the Form Error Validation epic

**Comment by austinjprice** [comment]
Moving to product backlog for prioritization

**Comment by SamStuckey** [comment]
[PR resolving this bug](https://github.com/department-of-veterans-affairs/vets-website/pull/25728)
