### ISSUE TITLE
Add link to Github handbook source reference

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#59539]
### Description
This page has great info on how to get added to GH org:
https://depo-platform-documentation.scrollhelp.site/getting-started/request-access-to-tools#Requestaccesstotools-GettingaccesstotheVAGitHuborganization

It should also link to the official handbook for further info & reference: https://department-of-veterans-affairs.github.io/github-handbook/guides/onboarding/getting-access#step-3-access-to-the-department-of-veterans-affairs-organization

### Relevant URLs
https://depo-platform-documentation.scrollhelp.site/getting-started/request-access-to-tools#Requestaccesstotools-GettingaccesstotheVAGitHuborganization
https://department-of-veterans-affairs.github.io/github-handbook/guides/onboarding/getting-access#step-3-access-to-the-department-of-veterans-affairs-organization

### Which type of team are you on? (Platform team, VFS team, or Leadership)
Leadership

**Comment by vbellissimo** [comment]
Hi @mchelen-gov , thanks for leaving this request. We'll take a look for next steps.
