### ISSUE TITLE
Midpoint Review - Design Feedback - Veteran Facing Forms - Form 21P-0847

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#59550]
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- Great user flows!

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- **Must**: Use the [memorable date component](https://design.va.gov/components/form/memorable-date) for DOB and DOD.
- **Should**: Our [guidance for hint text](https://design.va.gov/components/form/#default-hint-text) is "These should ideally not wrap more than twice for a total of three lines." Since your wraps to a 4th line try to trim the content or use regular text or possibly [additional info](https://design.va.gov/components/additional-info).

**Comment by humancompanion-usds** [comment]
I agree. Dev team on Veteran-facing Forms needs to get the Memorable date in (and DST has a bug or 2 to fix there as well).

@jeana-adhoc - One note, on the Intro page we say that VA file number is needed when filling out this request (in the Prepare step). But that's not totally accurate, correct? They only need it if they don't have the SSN. Could that be made more clear?
