### ISSUE TITLE
Research Upgrade TLS to v1.2

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#59574]
# Description
AWS is dropping support for TLS 1.0/1.1 -- https://aws.amazon.com/blogs/security/tls-1-2-required-for-aws-endpoints/

June 28th, 2023 appears to be the cutoff date for "disruption to your AWS workloads". 

## Details
* Security team scans are evaluating our use of TLS 1.0
* How might we independently evaluate ourselves?
* We DO know that there are some instances that are operating with TLS 1.0 and TLS 1.1
* We have issues with NESSUS scan results targeting IP addresses instead of logical resources
   * One option may be to work with the group running the NESSUS scan to execute the scan synchronously
   * We would have to break chunks of the infrastructure off and process them
   * Can we get tailored results with more than the IP address?
* What are our remediation tactics for this?

# Tasks
- [ ] We need to identify all the clients that are still using TLS 1.0 or TLS 1.1 that touch AWS endpoints
   * Consider using some coordination with security scanning tools to detect these clients
   * Consider using AWS Cloudtrail to discover the TLS 1.0/1.1 connections (Cloudtrail details for TLS endpoints in AWS console, Cloudwatch query possible too)

# Acceptance Criteria
- [ ] All instances of TLS 1.0/1.1 usage with AWS endpoints have been upgraded to TLS 1.2

**Comment by cyriltech** [comment]
I did a query on cloudtrail and cloud watch log insights and the output result shows zero record of any endpoint using tls 1.1. ![image.png](https://images.zenhubusercontent.com/6385292bddbc0cbb14b84a51/c7bd9758-5bb3-4752-90d2-fc607343e8b7)
![image.png](https://images.zenhubusercontent.com/6385292bddbc0cbb14b84a51/33635d5c-f547-47e9-bf36-d7335f28d8b4)

**Comment by pjhill** [comment]
Potential mitigation path for old clients hitting S3 bucket in prod:
https://repost.aws/knowledge-center/s3-access-old-tls

**Comment by raywangoctova** [comment]
@JoeTice @pjhill  Do we expect to remediate this before 06/28? If not, what is the impact and mitigation after the cutoff date? VA is asking for an update.

**Comment by pjhill** [comment]
* VA.gov infrastructure does not appear to be the source of any of the connections negotiated with TLS < 1.2.
* The source of the flagged connections listed above appear to be user clients connecting directly to S3 to retrieve the production website.
   * The VA is not able to directly resolve this issue.
   * It may be worth considering placing a banner on the page warning users that if their browser experiences an issue with the site they should consider a modern browser.

**Comment by raywangoctova** [comment]
@pjhill Are you suggesting a banner on the homepage?

**Comment by mchelen-gov** [comment]
@pjhill Do we have an approximate estimate of what volume or percent of traffic is using TLS <1.2? Given that we only support IE 11+ we likely do not need to handle this edge case: https://caniuse.com/tls1-2

**Comment by pjhill** [comment]
Looking through those screen shots, I believe Cyril found 25 instances of TLS < 1.2 connections in the past 30 days. I believe he was using the recommended CloudTrail queries from Amazon. Let me see if I can get exact numbers for you.

**Comment by pjhill** [comment]
@raywangoctova -- I _was_ floating that idea until Mike pointed out the magnitude of the problem is likely quite small.

**Comment by pjhill** [comment]
Some additional info is available in the sensitive repository. Gary ran a scan as of last Friday and updated the existing scan results ticket -- https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/452

**Comment by JoeTice** [comment]
Based on this info and discussions of the matter, we believe that we are all agreed on Mike C's recommendation, no further action needed at this time, and this ticket will be closed.
