### ISSUE TITLE
Sidekiq Admin UI access for Scott James

### ISSUE THREAD

**Issue by ScottyRJames** [department-of-veterans-affairs/va.gov-team#59570]
### Your Name

Scott James

### Your GitHub handle (Sidekiq Admin UI access is managed through GitHub)

@ScottyRJames

### Your dsvagovcloud AWS user name (if applicable)

Scott.James

### Team, Role, and Company of the target individual

Benefits Debt Resolution, Backend Engineer, GovCIO

### COR Name

Jennifer O'Day

### Please confirm if you are on the VFS Team Roster or Platform Team Roster

- [X] [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Sidekiq UI Access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [ ] production (if requesting, justify prod access in 'Additional Notes' section)

### If PRODUCTION ACCESS is required, confirm/complete ONE of the following

- [ ] I have an AWS Username and it is listed in [here](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf)
- [ ] I currently have access to vets-api Production Terminal via ArgoCD
- [ ] I've attached a screenshot of my E-QIP Transmittal Notice E-mail (Drag or Copy/Paste in Additional Notes Section below)

**Comment by jknipes** [comment]
@ScottyRJames You've been granted access to Dev/Staging/Sandbox
