### ISSUE TITLE
 526 Exit Rate Technical Research

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#59584]
This epic is intended as a technical research spike to review and understand current documentation, update documentation where needed, group known issues and generally build up technical understanding of the 526 work flow within DBEx Team 2 (Team Carbs). Each step in the process is listed an issue in this epic as defined and named by this analytics export:

https://docs.google.com/spreadsheets/d/1WTUQAfbA1oCbjJ1yUievONKgkU72cmGJlLtBWT-F_t0/edit#gid=1624765285

As DBEx team 1 has undoubtedly done a similar exercise its probably prudent to review current documentation in Github and DBEx team 1 idea board:
 https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1677075027359/3be1457e29c424eeada818562a30b363a778fff0?sender=u63a72fa7eede9e4d2d960707 

https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/disability/526ez

Categories to explore for each Step

- General information:
-- Form ids in each step
-- Urls in each
-- branching possibilities (i.e. can this step be skipped, and what are different options with in a step) 
-- user information held

- Validation Error list (i believe there should some information here: https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/54285)
--What are the list of errors and messages for each step

- Integration/Api calls
--What data is sent received at each step
--Where is it coming from / going to

- Known issues / issues that need ux review (Austin to copy report of related support issues once he receives)

Etc...

Success Criteria:

Documentation is updated and linked in each story
A general flow diagram has been created with labeled decision points and relevant API calls

**Comment by tblackwe** [comment]
Before starting researching various steps, check with DBEx Team 1 to determine if they already have these items documented.

**Comment by tblackwe** [comment]
Found this document that the Lighthouse API team created to help with the backend flow.

https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1663868736153/1040f1c6df6230104917bdff6e5e157264ef9153?sender=u4258b43f8cbb5244de228516

**Comment by tblackwe** [comment]
This flow describes the 526 overall flow 
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/526-overall-flow.md

**Comment by austinjprice** [comment]
Just to note the flow above i am referring to is titled: Simplified Form Flow
