### ISSUE TITLE
Medical Records

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#59600]
Nichole recommends using the simplified (under the main flow) in Mural as reference. https://app.mural.co/t/coforma8350/m/coforma8350/1686317911061/2ff3d4b4c2d9d84eaa61e9eda95a533041f137da?sender=u674f33e99d68adb0c1952030

**Comment by austinjprice** [comment]
Discussed in Refinement - use standup to discuss on Tuesday

**Comment by austinjprice** [comment]
@micahaspyr @SamStuckey @NB28VT please take an initial pass and list out questions / interests you want to explore for this particular step. Time box: 2 half days each

**Comment by NB28VT** [comment]
Moving this back to in progress (assume you meant to do this following your last comment @austinjprice) and taking a look at the second flow in a manner similar to how Sam did the first flow
