### ISSUE TITLE
Learn about support outlets for My HealtheVet users

### ISSUE THREAD

**Issue by fmccaf1** [department-of-veterans-affairs/va.gov-team#59619]
## Story
"As a member of the Cartography Team, I need to obtain and analyze user feedback, so I can make informed decisions about the direction of the MHV on VA.gov landing page."

## Acceptance Criteria

- [x] Meet with Susan Haidary
- [ ] Write up tickets with new knowledge for final outcome of gaining access to user support data starting April

**Comment by fmccaf1** [comment]
## Follow up items from call
- Contact Patty Henry: access to HRC-run MHV call center data? access directly to Iris system? 
- Contact Jean Good: access to tier 3 issue data? (tend to be more technical issues)
- Find a contact to get in touch about secure message field questions group
- Learn how central office folks keep track of what coordinators from Veterans (specifically about using MHV)

@batemapf does this look right to you? Anything jump out as missing?

**Comment by fmccaf1** [comment]
@batemapf I just wanted to make sure you saw this and do not have additional follow-up items or nuance to add. I can make tickets and drive work forward if we're feeling confident about the list of follow-ups above.

**Comment by batemapf** [comment]
this looks good. do you have notes from the call with susan and/or general notes on this work so far? would be good drop a cleaned up version of those in GH for reference later.

**Comment by fmccaf1** [comment]
Got it, will do. Thanks.

**Comment by fmccaf1** [comment]
[Added notes to GH.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/metrics-performance-monitoring/meeting-Susan-Haidary.md)

Feel free to modify/add anything I might've missed, @batemapf. I'll work on getting these follow-ups ticketed.

**Comment by fmccaf1** [comment]
Created tickets:
- [60049](https://app.zenhub.com/workspaces/mhv-on-vagov-top-level-view-62619a987d74510018ecc546/issues/gh/department-of-veterans-affairs/va.gov-team/60049)
- [60058](https://app.zenhub.com/workspaces/mhv-on-vagov-top-level-view-62619a987d74510018ecc546/issues/gh/department-of-veterans-affairs/va.gov-team/60058)
