### ISSUE TITLE
[ISSUE] Medical records disclosure authorization check defaults to "authorized"

### ISSUE THREAD

**Issue by NB28VT** [department-of-veterans-affairs/va.gov-team#59617]
## Issue Description
On Step 3 of the 526EZ form, the "Supporting evidence" step, the user is prompted to either upload their private medical records or authorize a doctor to disclose them.

However, it appears selecting the "No, please get my records from a doctor." option **automatically checks the box indicating the user is consenting to authorize those records are released.**

This seems contrary to most legal permission-based prompts in these types of web forms, where the user has to manually check the box acknowledging they consent. This box should be unchecked and the user should not be able to proceed with the medical release option unless they check it. This prevents a user accidentally consenting. 

![Screenshot 2023-06-02 at 12.50.29 PM.png](https://images.zenhubusercontent.com/647627f92b5e617343beedd1/192fee46-8e16-4c0b-9c08-eb51955b6630)

### Information needed to assess the severity of the issue
- Users Impacted:   Anyone selecting the release records option intentionally or by mistake.
- Issue Impact:     At worst, a user authorizing a medical records release when they don't want to. This seems very unlikely in this case but it's still arguably unethical as folks don't always read forms carefully.
- Workaround:            
- Legal Requirement:  It arguably means the VA is not keeping user consent at top of mind.
- Loss of Service:       
- Permanent Impact:   
- Vulnerability:      Certainly a privacy vulnerability if the user consents to something by mistake.

### Information that aids in the research and troubleshooting of the issue
- Date and Time of Issue:     
- Form/Page of Issue:         http://localhost:3001/disability/file-disability-claim-form-21-526ez/supporting-evidence/private-medical-records
- Error Message:              
- How to reproduce:           Select the "No please, get my records from my doctor"
- Unique IDs:                 
- Application ID:             
- Hardware Issue Observed On: 
- Browser type / version:
- Case#, if available: 
- Reporter name in va.gov:

**Comment by lydiahooper** [comment]
We are redesigning this experience as part of 4142 redesign this sprint https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/58793
