### ISSUE TITLE
Evaluate onsite notifications for Appointment Reminders

### ISSUE THREAD

**Issue by A6-toma** [department-of-veterans-affairs/va.gov-team#59623]
Evaluate onsite notifications for Appointment Reminders.

Need to make sure notifications are kept fresh due to complexity of potentially cancelled appointments.

Kay Lawyer is SME for Appointments.

VEText (SMS) does appointment reminders already. Shane Elliott and Rob Derkin.

See related ticket regarding notifications for appointment cancellations #59624. 

TASKS
- [x] UX evaluation
- [x]  Technical evaluation

### Acceptance Criteria
UX complexity and technical complexity of implementing Appointment Reminder onsite notification have been documented.

**Comment by A6-toma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MHV-on-VAgov-Top-Level-View-62619a987d74510018ecc546/issues/department-of-veterans-affairs/va.gov-team/59623?planning-poker) with Zenhub @AngelaFowler82 @carafrissell1 @carlosfelix2 @ericvoshall @fmccaf1 @jonathanjnelson @keithcheung828

**Comment by keithcheung828** [comment]
@A6-toma Hi Tom, please clarify the placeholder that is currently blocking this ticket. I am trying to assign this ticket to myself for evaluation. Thanks

**Comment by keithcheung828** [comment]
Research and design by VA provided by Kay Lawyer
https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/products/health-care/appointments/research/2021-10-appointment-notifications-service-map

**Comment by keithcheung828** [comment]
Per VA's usability research, user could receive 15 SMS to confirm or cancel the same appointment. 
User receive email reminders ahead of each appointment:
- 1 week
- 3 days
- 1 day
- Day of ___
- 30 minutes before
- Optionally an additional remind can be configured

**Comment by keithcheung828** [comment]
VA design exploration for in person and video appointment reminders

![Screenshot 2023-08-07 at 11.45.11 AM.png](https://images.zenhubusercontent.com/6464f284c180c50c10d70791/30a47ad2-5c85-440c-8da8-e1f3f9e5a95d)

![Screenshot 2023-08-07 at 11.45.26 AM.png](https://images.zenhubusercontent.com/6464f284c180c50c10d70791/accce800-6eca-4f25-949e-a9796e989f09)

**Comment by keithcheung828** [comment]
Technical review:
- Each system (phone, text, email, etc.) has its own method to trigger notifications.
- Different groups within each facility may be responsible for configuring the systems. This makes it hard for staff to know what facilities are sending Veterans.
- Depending on how they are configured, the systems can send Veterans excessive notifications or none at all.
- VA Video Service can be configured to send appointment reminders via email or text to staff. Other than that, MSAs and health care providers must look in the right system to know the status of an appointment.

Besides relying on VEText, the only scheduling tool, to find out if sent notifications are successful, there is no clear metrics to define the success of the appoint reminders.

**Comment by keithcheung828** [comment]
After @sterkenburgsara and I synced with the appointment team on 8/10, this [Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1688162673250/b82ff829e6cbf831f54e9636017d31f75630648c?sender=87661907-3b79-46e5-85c6-4c46c3f1b062) was provided.

We may need to have more time and resources for the determination of appointment classifications due to the complexity of the reminder types.

**Comment by keithcheung828** [comment]
After studying the entire notification system, the classification of appointment reminder notification is completed ([See Mural link](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1692054883249/7af5e34c574446f17d214203ce3fe44e71d49205?sender=u4c72b2ff45e7c2f8e2942500))

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ0lVIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--24e73126e6f97ccdc0b59e27b5a89eaab2bb262f/Screenshot%202023-08-17%20at%209.07.12%20AM.png)
