### ISSUE TITLE
[FE] Edit phone number modals sometimes do not reset themselves on open

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#5963]
## To reproduce
1. sign in to staging with user 37
2. go to https://staging.va.gov/profile/
3. edit the home phone number
4. change the phone number and close the modal _without_ hitting the "Update" button
5. open the modal again and see that the modal is not showing the phone number that's currently on file, instead it's showing the number you entered but did not save in step 4.
6. close and open the modal again and see that the modal is now showing the correct phone number that's currently on file.

![edit-phone-modal-bug](https://user-images.githubusercontent.com/20728956/74785172-86314200-525e-11ea-95be-6e32fbb015c9.gif)

## Desired behavior
The modal should always show the phone number that is on file for the Veteran and "forget" what was entered in the modal if the modal is closed/exited. 

Note that the email and address modals do not have this issue.

## Notes
The issue is that the `PhoneNumberWidget`'s `value` prop is updated to the correct data value but that value does not update the corresponding `state.val` so its child `TextWidget` is not updated to match the source of truth.

![Screen Shot 2020-03-02 at 11.57.35 AM.png](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/564c8b4e-84ed-4c2a-84fd-cb555e36a2d9)

**Comment by erikphansen** [comment]
@mshea0606 @Samara-Strauss this can be validated on staging now.

**Comment by Samara-Strauss** [comment]
Looks good to me! Feel free to close.
