### ISSUE TITLE
Design alternate states of After Visit Summary

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#59642]
## Task Description
Design states on appointment details page for After Visit Summary when it is:
- Unavailable (empty state)
- Can't be retrieved (error state)

## Notes / References
- Past Appointment list
   - [Empty State](https://www.figma.com/file/VHHxvo1QA1ndWc0TBhfkNq/Add-After-Visit-Summary?type=design&node-id=1619%3A19591&t=9fL1BdNbDPY0UOI1-1)
   - [Error State](https://www.figma.com/file/VHHxvo1QA1ndWc0TBhfkNq/Add-After-Visit-Summary?type=design&node-id=1628%3A21018&t=9fL1BdNbDPY0UOI1-1)
- After Visit Summary
   - [Error State](https://www.figma.com/file/VHHxvo1QA1ndWc0TBhfkNq/Add-After-Visit-Summary?type=design&node-id=1618%3A18265&t=9fL1BdNbDPY0UOI1-1)

## Acceptance Criteria
- [x] Empty state designed
- [x] Error state designed
- [ ] M/T/D specs complete

## Design Specs
- Appointment Details page
   - [Empty State](https://www.figma.com/file/VHHxvo1QA1ndWc0TBhfkNq/Add-After-Visit-Summary?type=design&node-id=1621%3A20715&t=9fL1BdNbDPY0UOI1-1)
   - [Error State](https://www.figma.com/file/VHHxvo1QA1ndWc0TBhfkNq/Add-After-Visit-Summary?type=design&node-id=1618%3A28187&t=9fL1BdNbDPY0UOI1-1)

**Comment by Cieramaddox** [comment]
@kristenmcconnell @ninaranusavice What is the path forward when an after visit summary is unavailable? 

We could:
- Tell them to **check back later**, but there is a chance that it will never arrive, correct?
- Tell them to **call the facility**, but the facility wont necessarily have their after visit summary. 
- Tell them that _this_ after visit summary isn't here, but link them to the care summaries page to see _other_ after visit summaries.

**Comment by kristenmcconnell** [comment]
Copying Slack convo response here:
We were planning for the “Come back later” route, because most often we envision not showing the AVS due to the API being down.

When the API comes back, then they should see the AVS.

Bullet two would be challenging, because you need someone who can access to VistA and their medical record to pull the AVS. Bullet three is interesting, but we can’t do that yet. That section doesn’t exist yet. We could circle back to that later and see if it matches Veteran expectations.

**Comment by Cieramaddox** [comment]
@kristenmcconnell When do we make a call to the API? Should we save the click and surface the error on the details page, rather than on the AVS page?

**Comment by kristenmcconnell** [comment]
Talking with @acrollet, we are planning designs for both situations. Nina created the version, which I think she sent to you, for the AVS page. While you are working on the version on the details page.

**Comment by Cieramaddox** [comment]
@kristenmcconnell Okay, great. Designs are completed on our end.

**Comment by kristenmcconnell** [comment]
@Cieramaddox I added a bunch of comments in Figma. The wireframes don't quite match the scenarios. Let me know if you have any questions.

**Comment by Cieramaddox** [comment]
@kristenmcconnell I made changes based off of your comments

**Comment by kristenmcconnell** [comment]
Looks good.

@ninaranusavice For awareness.
