### ISSUE TITLE
Midpoint Review - Accessibility Feedback - Veteran Facing Forms - Form 21P-0847

### ISSUE THREAD

**Issue by briandeconinck** [department-of-veterans-affairs/va.gov-team#59649]
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- As always, love those annotations! 😄 

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- **Should:** Maybe I'm misunderstanding something, but [2 of 9 - Your relationship](https://www.sketch.com/s/3ac6c625-5f29-454c-9b90-7d06460c4dcf/a/uuid/94932A24-4AB1-4380-B508-662F9DA01940) seems to be an issue. If my relationship isn't listed, I would want to write something in the text field -- but I'm also required to select a radio button with an incorrect option? I'm guessing that's unintentional! 
   
   But I'd love to see this broken into a one-thing-per-page --- "What's your relationship" with an option for "Not listed here," and then next page is a conditional "Tell us what your relationship is" when that "Not listed" option is selected. Or something like that.

**Comment by jeana-adhoc** [comment]
Thank you for that "should" recommendation. You totally understood the problem we had been facing and hadn't quite figured out a solution for. There was some work done on another form that would toggle the required label based on which one you filled out. 

But this, this just simplified it and we feel silly for not discovering the solution earlier. 

This is going to be implemented in this form.
