### ISSUE TITLE
Create technical document for lack of create account button

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#59640]
Sitewide content and other teams have asked for the technical reason why the current "create account button" for idme and login.gov do not redirect directly a "create account" page instead of the current login page.

Acceptance Criteria:
- Github document in public repo [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity/Design%20Documents)
- Peer reviewed statements approved by VA.gov Identity team
- Peer reviewed statements approved by ID.me and Login.gov
- Peer reviewed statements approved by Tom Black (PO)
- Merge document into public repo

**Comment by joeniquette** [comment]
@mjconw3 alerting for the next chance to throw in the priority queue

**Comment by parkerbees** [comment]
@joeniquette is this still needed? looks like it was a priority effort a year and a half ago.

**Comment by parkerbees** [comment]
Closing due to no response. If still needed we can pull from Zenhub archive.
