### ISSUE TITLE
[Bug] Facility Locator - Text results copy & styling don't match designs

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#5965]
## What happened?
**NOTE**: There are contradicting details between design references, causing similarly confusing mismatch-details below.  These should be reconciled, and ticket details below updated.

On Staging Facility Locator, text results do not match designs:

* Mismatches per [**Card-types PDF**](https://github.com/department-of-veterans-affairs/va.gov-team/files/4119731/FL-MVP-Card-Types.pdf):
  * Facility-type & Distance on separate lines -- should be on one line.
  * Phone numbers have labels -- should just have numbers.
* Mismatches per [**Invision Prototypes**](https://vsateams.invisionapp.com/share/EZVJMETDFTK#/screens/400664663):
  * Missing icon (A, B, C, etc) in front of Distance -- should have icon with letter corresponding to map-icon.
  * Main-phone-number label is "Main number" -- should be "Main phone".

These mismatches are common across all card-types.

## Specs:
**Browser(s)/Device(s)**: \[This bug is browser-/device-agnostic]

## Steps to Reproduce

1. Go to https://staging.va.gov/find-locations/
1. In **Search by** textbox, input **Washington, DC**.
1. Click **Search** button.
1. Note VA-health text-results in **View List** tab (or **left-panel** on desktop).
1. Note same copy/styling mismatches other facility-types' text results by changing search-filters and re-Searching.

## Screenshots
**iPhone 6 example**
![text-results-copy-styling-iphone-11-200218](https://user-images.githubusercontent.com/587583/74790647-6ce7c000-5275-11ea-9db9-183e993ead46.png)

## Desired behavior

Copy/styling matches updated styling references.  \[Reconcilliation details TBD.]
\[Alternatively, document agreed/approved deviations here.]

**Current VA health card-type example** \[as of 2020-02-20]
![va-health-card-ref](https://user-images.githubusercontent.com/587583/74790971-69a10400-5276-11ea-9102-c35785f880bc.png)

**Current VA health InVision-prototype example** \[as of 2020-02-20]
![va-health-design-ref](https://user-images.githubusercontent.com/587583/74791129-d916f380-5276-11ea-860a-613cc0912b15.png)

## Acceptance Criteria
\[see **Desired behavior** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by mmiddaugh** [comment]
@tlei123 Good catches!
Missing icon (A, B, C, etc) in front of Distance -- should have icon with letter corresponding to map-icon....this work was moved into https://github.com/department-of-veterans-affairs/va.gov-team/issues/5620
@davidconlon @arickalewis1 how critical are these deviations? Need input on prioritization

**Comment by arickalewis1** [comment]
The card is correct -- my wireframe was only for information. This should be compared to what @rtwell provided in Zeplin

**Comment by mmiddaugh** [comment]
closing this as the only issue which needs correction is already separately documented in [#5620]
