### ISSUE TITLE
[Bug] Facility Locator - Vet Centers service-type dropdown menu is enabled

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#5967]
## What happened?
On Staging Facility Locator, the service-type dropdown is enabled for Vet Centers facility-type.

## Specs:
**Browser(s)/Device(s)**: \[This bug is browser-/device-agnostic]

## Steps to Reproduce

1. Go to https://staging.va.gov/find-locations/
1. From **Choose a VA facility type** dropdown, choose **Vet Centers**.
1. Tap/click to expand **Choose a service type** dropdown.
1. Observe that service-type dropdown is enabled, with only 1 single option available.

**iPhone 11 example**
![vet-centers-svc-type-dropdown-enabled-iphone-11-200218](https://user-images.githubusercontent.com/587583/74800813-e9889780-5291-11ea-9d29-e03c0410c2c5.png)

## Desired behavior
Service-type dropdown is disabled for Vet Centers **facility-type.**

## Acceptance Criteria
\[See **Desired behavior** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by brangi** [comment]
merged
