### ISSUE TITLE
Review Instances - Improving testing on VA.gov

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#5968]
## User Story and Problem Statement
As a VFS or VSP team member, I want to have a better testing experience, so I can develop on VA.gov faster.

### High Level User Story/ies or Description
There are two types of review instances we use on VA.gov. the first is for testing content or any visual changes (Heroku instance) that may need to be made. The second is a way to test a service or application on VA.gov or a backend change. These review instances are a deployment of a combination of vets.api and vets-website at specified versions.

The work we are undertaking is to make improvements to the second in order to improve the testing experience overall.

### Pain Points being addressed:
- Testing will be easier 
- Testing against live backends. 

### Product Outline: 
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/review-instances/product-outline.md

## VSP Objective (Q1 & Q2 2020)
O1: Any volume of simultaneous customers have a delightful, self-service, end-to-end experience using the Platform to build on VA.gov.	

## Measuring Success (KRs/KPIs)
- [VSP KR] Increase in customer NPS
- [VSP KR] Reduction in volume of “non-human-needed” support requests month over month from VFS teams
- Testing quality for VFS teams (increases)

**Comment by brandonrapp** [comment]
Next Steps: We need to get real user feedback about how people are using this (if any). How can we make this more attractive to potential VFS teams.

**Comment by rmtolmach** [comment]
The QA Standards team is doing discovery for review instances. This can be closed.
