### ISSUE TITLE
[Analysis] Measure and track impact of moving 1010 link off of VA.Gov homepage

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#59684]
As a stakeholder, I would to understand how moving the direct link to the 1010 form from the VA.Gov homepage impacts the usage of the 1010 form so that I can help remediate any loss of visibility to Veterans and ensure all Veterans who want to enroll in healthcare know how to.

- Compare and contrast time periods before and after new homepage launch
- Look at similar timespans for other years (if numbers are relatively consistent year to year)
- Look at the number of completed forms before and after homepage
- Set up monitoring to continue tracking this
- Present to team and stakeholders (can be informal, 1-2 slides, whatever you think is best) about the impact on the 1010 forms
- Determine any next steps in addition to continuing to monitor these numbers (e.g. is there enough of a drop off to warrant making a case to the homepage content team to reinstate 1010 direct link?)

**Comment by ChristineYoungZA** [comment]
@michelle-dooley need assistance.

**Comment by luis-simauchi** [comment]
@ChristineYoungZA @michelle-dooley I am not sure if you need to chime in here, I am almost done with this request. Everything we needed was already in GA in some description. But if you want to by all means.

**Comment by luis-simauchi** [comment]
FINDINGS:
Depending on timeframe used. There is a counter argument to what was observed earlier with overall pageviews. It seems YOY vets who are going to completed the HCA are finding a way to the intro page of the 1010ez regardless of the new, less obvious experience on Homepage.

Current Selection: www.va.gov/health-care/apply/application/introduction/		
Previous Page Path	             Pageviews	% of Total Pageviews
www.va.gov/		
Feb 21, 2023 - Jun 5, 2023	4,702	7.72%
Feb 21, 2022 - Jun 5, 2022	3,066	4.98%
% Change	                        53.36%	54.91%

**Comment by luis-simauchi** [comment]
Previous Findings:
there seems to be a initial decline in pageview traffic from HP to intro page of the 1010ez form.
![Capture.PNG](https://images.zenhubusercontent.com/6421ffdd55816016e6d0ec89/1ede6cea-ca1f-4a31-b981-90c5afc81b16)
![Capture2.PNG](https://images.zenhubusercontent.com/6421ffdd55816016e6d0ec89/ffc97af1-b4df-4a35-af6b-5eba263a6336)

**Comment by luis-simauchi** [comment]
Conclusions:
Moving the direct link to the 1010 form from the VA.Gov homepage has likely impacted the visibility of the 1010ez form for Vets who are in the _initial stages of researching_ what is required to complete said form. Vets who had completed the form seemed to go from homepage to the start of the application in greater numbers despite the lack of direct link.
