### ISSUE TITLE
Add a new feature flag for Breadcrumb and URL (MHV on VA.gov Initiative) 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#59709]
## Item Description
We will need to create a feature toggle to update the breadcrumbs and URLS for Appointments app on MHV on VA.gov. 

---

## Tasks
- Add `va_online_scheduling_breadcrumb_url_update` feature toggle

## Acceptance Criteria: 
- [ ] The toggle is created for VAOS

## Definition of Done
- [x] All acceptance criteria are met
- [x] [Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/product/feature_toggles.md) is updated
---

**Comment by simiadebowale** [comment]
@ldelacosta - this is ready for validation.
![Screenshot 2023-06-22 at 1.02.46 PM.png](https://images.zenhubusercontent.com/62279c01c38e1718c9102bee/fee6681e-abd9-493d-85fc-7f2db2960d5d)

**Comment by ldelacosta** [comment]
Validated the acceptance criteria. No issues to report. Closing out the ticket.
