### ISSUE TITLE
"Try me" content from MHV website to new appointments tool 

### ISSUE THREAD

**Issue by aliyahblackmore** [department-of-veterans-affairs/va.gov-team#59726]
We have a request for a brief  "Try the new appointments on VA.gov" info alert on the top of the MHV "View My VA Appointments" page. Since this is content for the MHV site, we'll work with Ngozi to draft this content. 

We'll need 2 versions:
- A first nudge to try the new tool without a date attached
- A second more firm warning that the tool is moving to VA.gov on X date

We'll need the same kind of alerts for all the MHV tools as they move into phase 1, so we'll use this as a model.

- [x] Draft content (Aliyah)
- [x] Review draft (Laura) 
- [x] Share with Ngozi (Aliyah/Laura)
- [x] Review for alignment with MHV on VA.gov comms (Danielle)
- [x] Send to partners (Laura/Aliyah)

**Comment by aliyahblackmore** [comment]
Hi @laurwill - the drafted content is ready for you in this document. 

I called out a few questions regarding the phases as they relate to the change management comms deck. 
I also flagged the use of "page" vs. "tool."

[Info alert about appointments page_AB_6.5.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/11669294/Info.alert.about.appointments.page_AB_6.5.docx)

**Comment by aliyahblackmore** [comment]
I sent this content to Danielle in an email and sent a Slack message to let her know that this is ready for her.

**Tracking content here:**

**Suggestions for Phase 1 and 2 (try me):**  

**Try our new appointments tool on VA.gov**

We’re giving the My HealtheVet appointments tool a new home on VA.gov. Try the new tool early so you have plenty of time to get used to it. 

Try appointments on VA.gov now [link]

**Suggestions for Phase 3** 

Suggestions for Phase 3 (date when existing tool is going away): 

**Our appointments tool is moving to VA.gov on [date/month]**  

We’re giving the My HealtheVet appointments tool a new home on VA.gov. Try the new tool now so you’re ready for the change. 

Try appointments on VA.gov now [link]

**Comment by aliyahblackmore** [comment]
Laura and I chatted with Danielle about this today. 

Danielle is going to get back to us about how we should be communicating the timing.

**This is an updated version of content: ** 

**You'll need to switch to our appointments tool on My HealtheVet on VA.gov by [month/year]**

We're continuing to improve our appointments tool on My HealtheVet on VA.gov. 

Here's what you can do in our improved tool:

    - Review VA health care, community care, and claim exam appointments
    - Request and self-schedule some appointments
    - Cancel appointments

Try appointments on VA.gov now so you’re ready for the change.

Try appointments on [VA.gov](http://va.gov/) now [link]

**Comment by laurwill** [comment]
Here are the versions we'll pass back to Lichelle and team:

Version 1 (June 2023)

**Try managing your appointments on VA.gov**
We're building a new home for My HealtheVet on VA.gov. By fall 2023, you’ll need to start managing your appointments on VA.gov.

Here's what you can do in appointments on VA.gov:
- Review your VA health care, community care, and claim exam appointments
- Request and self-schedule some appointments
- Cancel appointments

Try it now so you’re ready for the change.
[Go to appointments on VA.gov]

Version 2 (late summer 2023)
**You'll need to start managing your appointments on VA.gov this fall**
Here's what you can do in appointments on My HealtheVet on VA.gov:
- Review your VA health care, community care, and claim exam appointments
- Request and self-schedule some appointments
- Cancel appointments

Try it now so you’re ready for the change.
[Go to appointments on VA.gov]

**Comment by laurwill** [comment]
I passed this to Lichelle via email. @RLHecht , we can close this ticket.

**Comment by RLHecht** [comment]
Thanks! Closing
