### ISSUE TITLE
Document vets-api status endpoint

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#59724]
### Description

The vets-api backend includes a status endpoint which returns the current commit: http://api.va.gov/v0/status 

This should be documented on https://depo-platform-documentation.scrollhelp.site/developer-docs/deployments

### Relevant URLs
https://depo-platform-documentation.scrollhelp.site/developer-docs/deployments

### Which type of team are you on? (Platform team, VFS team, or Leadership)
Leadership

**Comment by rmtolmach** [comment]
Added it to the table https://vfs.atlassian.net/wiki/spaces/pilot/pages/1844641889/Deployments

<img width="715" alt="Screenshot 2023-06-06 at 10 47 49 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/10993987/b8589d03-18c5-4878-9973-942f3a887aac">

**Comment by vbellissimo** [comment]
@mchelen-gov Closing this ticket as the content update has been published.
