### ISSUE TITLE
Print Upcoming, Pending and Past Appointments List

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#59732]
## Description
We will implement the print feature which will allow the user to print their upcoming, pending or past appointments. 

---

## Acceptance Criteria
Background: the `va_online_scheduling_print_list` toggle is on

- [ ] Given the user is on the Upcoming appointment list
        When the user clicks on the Print Tertiary Button
        Then the user is able to print their Upcoming appointments list
        And page design matches the [design spec](https://www.figma.com/file/sI4udk4AmnACHGj62PdPx7/List-print-view-improvements?type=design&node-id=1212-35&t=38QFeoE110nTloOh-4)

- [ ] Given the user is on the Pending appointment list
        When the user clicks on the Print Tertiary Button
        Then the user is able to print their Pending appointments list
        And page design matches the [design spec](https://www.figma.com/file/sI4udk4AmnACHGj62PdPx7/List-print-view-improvements?type=design&node-id=1216-5551&t=38QFeoE110nTloOh-4)

- [ ] Given the user is on the Past appointment list
        When the user clicks on the Print Tertiary Button
        Then the user is able to print their Past appointments list
        And page design matches the [design spec](https://www.figma.com/file/sI4udk4AmnACHGj62PdPx7/List-print-view-improvements?type=design&node-id=1216-5523&t=38QFeoE110nTloOh-4)

### Design Assets
[Design link](https://www.figma.com/file/sI4udk4AmnACHGj62PdPx7/List-print-view-improvements?type=design&node-id=13-33)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by JRRoof** [comment]
Blocked until feature flag is added - #59708

**Comment by ldelacosta** [comment]
@Cieramaddox @melissa-lefevre - if one of you could validate to make sure the design specs matches the layout in staging. If you have any issues, please let me know. Thanks!

**Comment by Cieramaddox** [comment]
@ldelacosta Everything here has been validated!

**Comment by ldelacosta** [comment]
The specs have been reviewed and no issues to report. Closing out the ticket.
