### ISSUE TITLE
Appointment List - Upcoming, Pending and Past (Print Tertiary Button)  

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#59730]
## Description
We will implement the print feature which will allow the user to print their upcoming, pending or past appointments. 

---

## Acceptance Criteria
Background: the `va_online_scheduling_print_list` toggle is on

- [x] Given the user is in the Appointments application
        When the user views their Upcoming appointment list
        Then the Print Tertiary Button will be displayed on the page

- [x] Given the user is on the Upcoming appointment list 
        When the user clicks on Pending 
        Then the Print Tertiary Button will be displayed on the page

- [x] Given the user is on the Upcoming appointment list 
        When the user clicks on Past 
        Then the Print Tertiary Button will be displayed on the page

- [ ] Add a tracking event in Google Analytics GA4 on the Print Tertiary Button

### Design Assets
[Design link](https://www.figma.com/file/qm63ZVrjq6eohFpWnVqj7F/Add-Print-Button-to-Appt-List?type=design&node-id=1297%3A27839&t=eajWEdE4LLsNJDTB-1) 

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by jenniemc** [comment]
@ldelacosta , this ticket is ready for validation. Please turn on the feature flag `va_online_scheduling_print_list` in staging for the Governance team review.

**Comment by ldelacosta** [comment]
Add a tracking event in Google Analytics GA4 on the Print Tertiary Button acceptance criteria will be handled in a separate ticket part of the GA4 migration initiative.

**Comment by ldelacosta** [comment]
Validated the changes. There's a minor issue with one of the breakpoints. @Cieramaddox  will be opening a bug ticket. Closing out this ticket. 

![Screenshot 2023-06-29 at 5.32.19 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/416f69a8-9cc4-44b5-89e5-fab89b2d953b)![Screenshot 2023-06-29 at 5.32.44 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/81103710-95ad-489d-846f-4da17e9c723a)

![Screenshot 2023-06-29 at 5.33.16 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/9ba9db5d-a8ff-4bc7-b6e5-63a230b8881c)!
