### ISSUE TITLE
Update the URL and title page on the Appointments landing page (MHV on VA.gov) 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#59733]
## Description
The Appointments application will be under the MHV on VA.gov portal. We will need to update the title page and URL structure. #59733 will focus on the Appointments Landing page. 

---

## Acceptance Criteria
Background: the `va_online_scheduling_breadcrumb_url_update` toggle is on

- [ ] Given the user is on the MHV on VA.gov portal
        When the user clicks on `Upcoming VA appointments`
        Then the URL will be updated to www.va.gov/my-health/appointments
        And the page title will be [`Appointments | Veterans Affairs`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/homepage.md#upcoming-appointments)

### Reference
[Spike ticket #54757](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/54757)

### Design Assets
[Title tag format guidance](https://design.va.gov/content-style-guide/seo#title-tags)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by JRRoof** [comment]
Blocked until feature flag is added - #59708

**Comment by ldelacosta** [comment]
Unblocked the ticket since #59709 is almost complete. Moved the ticket to the ready queue.

**Comment by ldelacosta** [comment]
Validated the changes in staging for judy.morrison@id.me. Notified the UX team to review the changes in staging. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdG93IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--174daba2244693f755035e4fc58dba315ee10462/Screenshot%202023-08-23%20at%204.52.39%20PM.png)

**Comment by Cieramaddox** [comment]
@ldelacosta We've validated this. All good on the UX side.

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket. cc: @JRRoof
