### ISSUE TITLE
Change "Call Centers" to "Contact Centers" on VFS Documentation

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#5974]
## User Story or Problem Statement
How might we maintain accuracy and consistency for contact center documentation?

## Goal
Change "Call Centers" to "Contact Centers" on all documentation.

## Acceptance Criteria
Change naming convention on the following
- [x] Github Markdowns
- [x] Github label
- [x] Slack Channels & descriptions
- [x] Team of Teams slides (Joanne)
- [x] Insights Onboarding (Joanne)
- [x] Insights - all of our slide decks (Joanne)
- [x] Double check Domo dashboards

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by clantosswett** [comment]
@Kimberley2019 I don't think we ever decided who would take lead on this issue. Can you take the lead on this?

**Comment by Kimberley2019** [comment]
Good Afternoon,

Of course I can.



Kind Regards,

Kimberley

**Comment by Kimberley2019** [comment]
I have reached out to Bill and Meghan on Content-ia to see if they are able to assist in this matter.

**Comment by Kimberley2019** [comment]
Here is the ZH ticket that was created for the ia team to run the report for changes.

 https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/6200

**Comment by joanneesteban** [comment]
## Insights Artifacts

- ToT changed (agenda + team slide)
- Insights internal + external artifacts changed (artifacts located [here](https://miro.com/app/board/o9J_kvUTOYk=/?moveToWidget=3074457347284688991))

There _may_ be Insights artifacts stragglers, but the main items have been edited.

**Comment by joanneesteban** [comment]
## Github Labels

- Also changed the Zenhub label, `call center` to `contact-center`

**Comment by Kimberley2019** [comment]
Amy Cesal was able to verify that changes have been made in Domo.
