### ISSUE TITLE
Create guidance and best practices for creating helpful user flows

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#59749]
The Governance team just announced that teams will be required to bring user flow diagrams to the Design Intent touchpoint.  

This is an opportunity for Sitewide IA to 
- help teams understand why user flows are helpful to the design process
- provide guidance and best practices documentation to help teams understand what makes a good user flow diagram
- remind teams that Sitewide IA is a shared service available to work with teams in the creation of those flow diagrams should they need assistance

This work should be done in collaboration with the Governance team IA role as much as possible to ensure we are capturing what that team needs within the documentation to best help with the their DI review.

**Comment by mnorthuis** [comment]
@jennymayoco @kristinoletmuskat I took a look at your [user flows mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1686257056852/44184951e75f4ed6fcd9520c7168f9d0de59986a?sender=u2aba00c97ab77c6ec1573123) - looks like you have a good outline of what this documentation could be.  I think next steps are to get an actual document drafted.  I think this will likely live in GH initially. 

You can pull this issue out of blocked and back into your backlog to pick back up.

**Comment by kristinoletmuskat** [comment]
Thanks Mikki! Just moved it over.

**Comment by jennymayoco** [comment]
Hi @mnorthuis [attaching here the user flows draft](https://docs.google.com/document/d/1j_tSLKS0YokbLC3bWNhxcQJfu3a79VZCFsUKPHFReFE/edit#heading=h.jonn7r98b2y) that is ready for your review

**Comment by jennymayoco** [comment]
Moving to ready as Mikki has reviewed the doc and given the okay to transfer to [IA standards](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/information-architecture/standards) in GH

**Comment by jennymayoco** [comment]
Next steps:

- [x] Publish in [GH IA standards](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/standards/user-flow-guidance.md)
- [ ] Share with CAIA and IAs
- [ ] Make edits as per feedback from team
- [ ] Write blurb to share in `#design` channel in Slack

**Comment by jennymayoco** [comment]
tasks done so moving this ticket to validate
