### ISSUE TITLE
Automation for rolling pods via annotations

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#59741]
## Description

We often need to “roll” the pods during deployments for things like forcing startup logic to occur again such as reloading of a modified Secret, etc. A change has been added here to add an annotation that can be manually adjusted to roll the pods. For example, if you adjust the `manualRoll` value, when the helm chart is applied, it will see this as a "change" and roll the pods. This makes it easier for developers/support engineers to roll pods to pick up secret modifications, which happen frequently (e.g. things are updated in param store, but the manifest remains unchanged). 

#### Preferred solution: 

Through the usage annotations via `configmap.reloader.stakater.com/reload` and `secret.reloader.stakater.com/reload`, we should be able to perform a rolling update when the specified secrets and configmaps are updated. 

![Screenshot 2023-06-06 at 2.05.19 PM.png](https://images.zenhubusercontent.com/5d4836dda95c51615db9bdc9/d541a689-aef5-4f10-bcb0-d19d2e3a7d9a) 

Here's a list of all the names of our current configmaps and secrets:

![Screenshot 2023-06-06 at 2.06.46 PM.png](https://images.zenhubusercontent.com/5d4836dda95c51615db9bdc9/c7961db7-8074-4653-a452-c49908f573c6)

If anything changes, the pods will automatically do a rolling restart. We should just need to add the secret and configmap annotation to the Deployment resource and list out the cm's and secrets that we want to trigger a reload. For more info see https://github.com/stakater/Reloader

Additionally, we should add another annotation that can be manually changed to roll the pods

**Comment by jennb33** [comment]
@LindseySaari to review this ticket for accuracy and to see if this work is still required.

**Comment by LindseySaari** [comment]
The goal here was to have a way to recycle pods where kubectl access is restricted. We've been able to identify another solution to recycle the pods via the ArgoCD UI, [detailed here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Restarting-ArgoCD-Deployments-to-Recycle-Pods). This has the same affect as the `manualRoll` config detailed above. A backend engineer will have the ability to recycle pods in scenarios where pods need to be rolled to pick up things like secrets, etc
