### ISSUE TITLE
Depreciate Sidekiq Scheduler

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#59770]
Sidekiq Scheduler needs to be depreciated.

## Tasks

1. Have teams remove remaining jobs using sidekiq scheduler.
2. Remove Sidekiq Scheduler from vets-api (files, references, and gem)

**Comment by RachalCassity** [comment]
@laineymajor @LindseySaari 

For next sprint..

**Comment by laineymajor** [comment]
I will help with this one, and we will break it apart:
1. Communications with instructions for VFS teams to act on (include deadline)
2. Ticket that will go in the BE CoP backlog to remove sidekiq scheduler from vets api

**Comment by RachalCassity** [comment]
@laineymajor I was able to modify the tests for 6/7 of the scheduled jobs so there is only one team to contact, Lighthouse Appeals API.

**Issue** 
Sidekiq scheduler is being replaced with Periodic Jobs which are supported in our Sidekiq Enterprise subscription.  The ability to pass dynamic arguments when enqueuing a scheduled job will no longer be available with Periodic Jobs.   The VRE::CreateCh31SubmissionsReportJob has `include_metadata` enabled, seen [here](https://github.com/department-of-veterans-affairs/vets-api/pull/8465/files#diff-ef94735773b3cb08b2f1fb3fec208383803e70154f8c55e05afa2f8174433129R243). 

The reason `include_metadata ` is enabled is discussed in this [issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/33026). Here's the background info:
_The summary report currently queries the db by updated_at. We need to change it to query via created_at. We also need to allow a specific date to be passed in so that a one-time report can be sparked from rails console so VRE can get the report that was not correct for Monday the 15th._

**Questions** 
1) Is this still relevant?
2) If relevant, at what frequency are arguments being passed to VRE::CreateCh31SubmissionsReportJob? Can this be resolved in another way?

**Comment by RachalCassity** [comment]
Reached out the benefits-ce-decision_reviews slack channel. Seems like the team that used this is no longer here.

**Comment by RachalCassity** [comment]
Meeting with Non Disability Benefits team this week.

**Comment by laineymajor** [comment]
Will meet with owning team to see if this is something being used.

**Comment by RachalCassity** [comment]
@tblackwe @steele-lm FYI

**Comment by RachalCassity** [comment]
Tom and his team are looking into the job. I have a PR to remove Sidekiq Scheduler.

**Comment by tblackwe** [comment]
I've been unable to track down who required this generated report. I can continue to research it under the new ticket.

**Comment by RachalCassity** [comment]
@tblackwe Thank you!

**Comment by RachalCassity** [comment]
@tblackwe Thank you!
