### ISSUE TITLE
Vets-api terminal access for Maxwell Antonucci

### ISSUE THREAD

**Issue by maxx1128** [department-of-veterans-affairs/va.gov-team#59791]
### E-QIP Transmittal Date

- [x] Check this box if you have an E-QIP transmittal date.

### Your Name

Maxwell Antonucci

### Your GitHub handle (terminal access is managed through GitHub)

@maxx1128

### Team, Role, and Company of the target individual

Sitewide Facilities Team, Sr. Front-end Developer, AgileSix

### Product Manager (PM) name and email

Kamari Patrick, Kamari.Patrick@va.gov

### Product Owner (PO) name and email

Dave Conlon, david.conlon@va.gov

### ArgoCD terminal access requested for the following environments

- [ ] dev
- [X] staging
- [ ] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### COR Name (leave "None" if you listed an AWS user name above)

None

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

Agile Six - Anthony M. Arashiro

### Access Expiration

ongoing

### Additional Notes

I need access so the facilities team can check and update the information in vets-api that is made available to the different facilities platforms, such as the facilities locator.

I set "access expiration" as "ongoing" since I will be doing continued work on vets-api for the facilities team in the future with no specific end date currently set. If there is a custom or requirement to renew access expiration after a certain amount of time, I can change it to whatever is typical or expected.

### User must exist in a roster before vets-api terminal access can be granted

- [ ] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added
- [ ] If they included an AWS user name, check to see if their user name is listed in [iam_users.tf](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf)
- [ ] Comment in this issue saying which roster the user is listed in and confirming their AWS user name (if applicable)

**Comment by ryan-mcneil** [comment]
@maxx1128, please provide a screenshot of your eQIP `Transmittal Notice` email to verify the transmittal date. Upon receipt I can grant access to Staging, and pass along the Production request to OCTODE for approval.

**Comment by maxx1128** [comment]
@ryan-mcneil Sure thing!

<img width="1445" alt="Screen Shot 2023-06-12 at 1 05 12 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/10790736/05723ba9-d919-4fdd-96ec-658148cd88e1">

**Comment by ryan-mcneil** [comment]
@maxx1128 I just noticed you're not on the VFS Team roster. Per the instructions, can you please start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)

**Comment by jilladams** [comment]
@ryan-mcneil if @maxx1128 can provide proof that he already did a Platform orientation when he joined the ecosystem in April 2022, would that suffice? The Platform roster / orientation process was not as firmly set up then as it is now, and In theory, Max had to do that orientation in order to get SOCKS access back then. 

@maxx1128 maybe search your calendar to check and see if you did, last year?

**Comment by maxx1128** [comment]
> @ryan-mcneil if @maxx1128 can provide proof that he already did a Platform orientation when he joined the ecosystem in April 2022, would that suffice? The Platform roster / orientation process was not as firmly set up then as it is now, and In theory, Max had to do that orientation in order to get SOCKS access back then.
> 
> @maxx1128 maybe search your calendar to check and see if you did, last year?

The closest thing I can find is "VFS-CMS project onboarding" parts 1, 2, and 3 for April 5th through 7th, I'm unsure if that's the same orientation @ryan-mcneil is referring to or is more of a general project introduction.

**Comment by jilladams** [comment]
Nope, that's team internal. So you _will_ need to go ahead and schedule for the next available Plat orientation then. Thanks for checking!

**Comment by ryan-mcneil** [comment]
@maxx1128 @jilladams If you believe Max is already versed in the Platform, perhaps the name not getting added to the VFS Roster was an oversight. Personally, I'm not exactly sure HOW/WHEN/BY WHOM your name gets added. I just know that somewhere in that process it gets added. I will investigate on my side, but it could be worth asking your VOR/Manager to see if they have any ideas.

**Comment by jilladams** [comment]
Yeah, thanks @ryan-mcneil . The VFS Platform Roster process changed quite a lot around the time our contract was spinning up last year, so not everyone followed the same flow to get in there. We can chase both -- Max booking an orientation, and then  if you get news that it's not needed, yay.

**Comment by ryan-mcneil** [comment]
@maxx1128 @jilladams We don't have record of the process being initiated, so we will ask you to go through the "Orientation". So your first step is just completing the Orientation Template mentioned [here](https://depo-platform-documentation.scrollhelp.site/getting-started/guidance-for-new-teams-and-team-members#Guidancefornewteamsandteammembers-NewVFSTeammembers).

One that ticket is received, a member of the Platform Governance team will add you to the roster and we can get moving on this side! Thanks for working with us!

**Comment by rmtolmach** [comment]
and just to be clear, you don't need to _complete_ everything on that checklist to get on the roster (in fact, you've probably completed many of those things), but that ticket needs to be created in your name to get you added to the roster. It usually take a couple days before you're added to the roster, fyi.

**Comment by maxx1128** [comment]
@ryan-mcneil I opened up [a Platform Orientation Ticket here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60257) and will start checking the items off.

**Comment by ryan-mcneil** [comment]
@maxx1128  Thanks! You've already been added to the roster 👌 

You’ve been granted access to the `staging` environment.

Here's some additional documentation for the [Vets API on EKS](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-TerminalAccess)

Access to `prod` is pending approval by OCTODE, and we'll update you as soon as it's available.

**Comment by maxx1128** [comment]
@ryan-mcneil Thank you! Do you still need me to go through all the Orientation items or is it unneeded at this point?

**Comment by ryan-mcneil** [comment]
That's all _I_ need, but if you're working with the platform it's probably a good idea to check some more boxes. I'll leave that up to you and your Manager's discretion

**Comment by BillChapmanUSDS** [comment]
Access granted for 3 months as per policy.   

Note that the justification may not meet the level of requirement for future evaluations. You may be required to suggest an alternative approach or justify why production access is the only way you can accomplish this.

**Comment by bdech** [comment]
slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1687366327934049)

**Comment by bdech** [comment]
@maxx1128 Per an update to our access policy, your ArgoCD/vets-api Production access has been extended for 3 months, expiring 12/21/23. Please set a reminder for yourself to return to this Issue and re-request access within 1 week of the expiration date. You'll receive 1 reminder with a 72 hour window to respond. Failure to do so will result in lost access and will require you to fill out a new request.

**Comment by bdech** [comment]
slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1695304132728439)

**Comment by maxx1128** [comment]
I'm re-opening this with a request to extend my vets-api production access.

**Comment by bdech** [comment]
@LindseySaari @ericboehs can one of you please give us a :thumbsup: to extend their access?

**Comment by bdech** [comment]
@maxx1128 your ArgoCD/vets-api Production access has been extended for 6 months, expiring 06/14/24. Please set a reminder for yourself to return to this Issue and re-request access within 1 week of the expiration date. You'll receive 1 reminder with a 72 hour window to respond. Failure to do so will result in lost access and will require you to fill out a new request.

**Comment by bdech** [comment]
@maxx1128 Your Vets API Terminal Production access has expired.

Would you like to request an extension? You have 72 hours to respond, or your 
access will be revoked and you will need to fill out a new request.

**Comment by jilladams** [comment]
@bdech Max is on PTO through the holidays til 1/5, but will definitely need terminal access through Q1 2024. Please do extend, and I'm happy to answer any questions on his behalf during his PTO. Thanks!

**Comment by bdech** [comment]
Thanks @jilladams.

**Comment by bdech** [comment]
@LindseySaari @ericboehs can one of you please give us a 👍 to extend their access?

**Comment by bdech** [comment]
@maxx1128 Your `Production` access has been extended 6 months, expiring 06/21/24. Please set a reminder for yourself to return to this Issue and re-request access within 1 week of the expiration date. You'll receive 1 reminder with a 72 hour window to respond. Failure to do so will result in lost access and will require you to fill out a new request.

**Comment by bdech** [comment]
support slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1703774523020979)

**Comment by davidpetras** [comment]
@maxx1128 Your Vets API Terminal Production access has expired.

Would you like to request an extension? You have 72 hours to respond, or your
access will be revoked and you will need to fill out a new request.

**Comment by maxx1128** [comment]
> @maxx1128 Your Vets API Terminal Production access has expired.
> 
> 
> 
> Would you like to request an extension? You have 72 hours to respond, or your
> 
> access will be revoked and you will need to fill out a new request.

I would like to request an extension, please @davidpetras

**Comment by davidpetras** [comment]
@LindseySaari @ericboehs can one of you please give us a 👍 to extend access here?

**Comment by davidpetras** [comment]
@maxx1128 your `production` access has been extended 6 months, expiring 12/16/24. Please set a reminder for yourself to return to this Issue and re-request access within 1 week of the expiration date. You'll receive 1 reminder with a 72 hour window to respond. Failure to do so will result in lost access and will require you to fill out a new request.

**Comment by AnthonyWFlowers** [comment]
Greetings @maxx1128 Your Vets API Terminal Production access has expired.

Would you like to request an extension? You have 72 hours to respond, or your access will be revoked and you will need to fill out a new request.

**Comment by jilladams** [comment]
@AnthonyWFlowers -> https://github.com/department-of-veterans-affairs/va.gov-team/issues/92782. Max won't need access.

**Comment by AnthonyWFlowers** [comment]
Thank you @jilladams 
User has been onboarding and no longer has access.
