### ISSUE TITLE
[Discovery] Adding the Claims Product to the Product Health MVP

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#598]
## User Story
As a Claims product decision maker, I need updated data on my product so I can easily add analytics to my product decision making workflow.

## Goal
Discover if/how we can add the Claims product to the Product Health MVP. 

## Acceptance Criteria
- [x] Use/iterate on education product health MVP:
   - [x] Write Claims Conversation Guide
   - [x] Update Claims Research Plan
- [x] Meet with Andrea to determine Claims data needs (how are they tracking data right now?)
- [x] Determine which other stakeholders we need to speak to
- [x] If applicable, determine data points that should be added

## Definition of Done
- [ ] **Attached to a Milestone** 
- [ ] **Attached to an Epic** 
- [ ] **Labeled with Team**
- [ ] **Labeled with Practice Area**
- [ ] **Labeled with Type**

**Comment by joanneesteban** [comment]
1st task: Meet with Andrea to determine their current data tracking workflow. 

@leahbannon [Notes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/Platform/Teams/Analytics%20and%20Insights/Research/Undiscovered%20Metrics%20Research/Claims%20PA%26I%20-%20Meeting%20with%20PM.md) from previous meeting with Mark and Andrea on their offline data gathering.

**Comment by joanneesteban** [comment]
Meeting set for Monday, July 22 with Andrea.

**Comment by amycesal** [comment]
### Conversation Questions
- Which claims forms would you want included in a potential dashboard?
- Would you want metrics for form views, form submissions or both?
- How did you she get PA&I data? How are you implementing and using that data? 
- Is there anything you'd like us to know about the products that would help us add claims products to the current Product Health MVP?

**Comment by amycesal** [comment]
Which claims forms would you want included in a potential dashboard?
> - disability benefits form (526). Not clear we're tracking other forms because it's one submission. 
> - Permission for va to retrieve medical benefits (4142) 
> - PTSD form (781) <- optional

Would you want metrics for form views, form submissions or both?
> not as much about the view, more about the submissions. 

How are you implementing and using PA&I data? Do you have a sample of the data that we could use for our prototype?
> comparisons between the different channels for submission. track overall usage. how submission breaks down throughout the process. Cross comparison and how it affects the process. 

Is there anything you'd like us to know about the products that would help us add claims products to the current Product Health MVP?
> Plans: 
> - trying to change to allow veterans to allow to submit to VA.gov even if they've never submitted previously. Currently send people back to ebenefits. Change happening in fall, then the re-direct to va.gov volume could skyrocket. 
> 
> Fold in appeals lane, fork them out into decision review. track how many people diverge into appeals instead of going to a new claim

**Comment by joanneesteban** [comment]
Claims Forms to add: (GA)
-526
-4142
-781
