### ISSUE TITLE
Vets-api terminal access for Ksenia Coulter

### ISSUE THREAD

**Issue by kscoulter** [department-of-veterans-affairs/va.gov-team#59800]
### E-QIP Transmittal Date

- [x] Check this box if you have an E-QIP transmittal date.

### Your Name

Ksenia Coulter

### Your GitHub handle (terminal access is managed through GitHub)

@kscoulter

### Team, Role, and Company of the target individual

Login Gov Adoption team, software engineer, Pluribus Digital

### Product Manager (PM) name and email

Anthony Levin-Decanini

### Product Owner (PO) name and email

anthony@themostudio.com

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [ ] production (if requesting, justify prod access in 'Additional Notes' section)

### COR Name (leave "None" if you listed an AWS user name above)

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

Other - please specify in 'Additional Notes'

### Access Expiration

01-01-2025

### Additional Notes

COR - Jennifer O'Day
VOR - Paula G. Mendoza

### User must exist in a roster before vets-api terminal access can be granted

- [ ] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added
- [ ] If they included an AWS user name, check to see if their user name is listed in [iam_users.tf](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf)
- [ ] Comment in this issue saying which roster the user is listed in and confirming their AWS user name (if applicable)

**Comment by ryan-mcneil** [comment]
@kscoulter, please provide a screenshot of your eQIP Transmittal Notice email to verify the transmittal date. Upon receipt I can grant access the requested envs. Thanks!

**Comment by kscoulter** [comment]
@ryan-mcneil does that work?

<img width="1445" alt="Screen Shot 2023-06-08 at 10 47 47 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/12025195/04a3f743-3319-4b34-b978-23e3c25f74a2">

**Comment by ryan-mcneil** [comment]
@kscoulter That's exactly what we need! Thanks!

You’ve been granted access to the `dev`, `staging`, and `sandbox` environments.

Here's some additional documentation for the [Vets API on EKS](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-TerminalAccess)
