### ISSUE TITLE
Developer Research Spike: 526ez Pull Disability list from LIghthouse API (41302)

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#59815]
### Acceptance Criteria:
- [ ] Attach research notes/design approach for changes required to vets-api
- [ ] Attach research notes/design approach for changes required to vets-website
- [ ] Update the Acceptance Criteria in #41302

Time-box: 12 hrs per doc (raise if we are approaching limit or think we will)

**Comment by NB28VT** [comment]
Front End next steps: make time to share findings with someone in `bdex-engineers` Slack from team 1. Re: how do you think we should plan to approach this?

**Comment by SamStuckey** [comment]
I accidentally dropped this comment in the wrong ticket.  This is a summary of my initial findings pre-ticketing, for posterity.  

---
Additional context from my initial research indicates that whoever focuses on the backend of this ticket will need to answer two primary questions:

What is our performance need / availability requirement for this data via that API? This will inform whether or not we decide to cache this data at the application level (likely), or allow for a read through to the lighthouse API. Caching will present the issue of cache breaking to consider, while non-caching will make our API dependent on lighthouse uptime and the appropriate query route being exposed by lighthouse, e.g. do they have a 'fuzzy' match api we can use? This will also depend on the FE use cases captured by the FE researcher here.
What is our current solution for interacting with Lighthouse via the API? In other words, how big of a lift will it be to plug our API into a new route (and potentially a cache busting webhook). Is there an auth pattern to follow? A Lighthouse API wrapper object, etc... To answer this question, research existing API to lighthouse requests.

**Comment by SamStuckey** [comment]
I accidentally dropped this comment in the wrong ticket.  This is a summary of my initial findings pre-ticketing, for posterity.  

---
Additional context from my initial research indicates that whoever focuses on the backend of this ticket will need to answer two primary questions:

What is our performance need / availability requirement for this data via that API? This will inform whether or not we decide to cache this data at the application level (likely), or allow for a read through to the lighthouse API. Caching will present the issue of cache breaking to consider, while non-caching will make our API dependent on lighthouse uptime and the appropriate query route being exposed by lighthouse, e.g. do they have a 'fuzzy' match api we can use? This will also depend on the FE use cases captured by the FE researcher here.
What is our current solution for interacting with Lighthouse via the API? In other words, how big of a lift will it be to plug our API into a new route (and potentially a cache busting webhook). Is there an auth pattern to follow? A Lighthouse API wrapper object, etc... To answer this question, research existing API to lighthouse requests.

**Comment by micahaspyr** [comment]
It's been tough getting clarity into the workings of Lighthouse, so we'll just treat it as a black box.  Because the Lighthouse API endpoint lacks fuzzy searching, we'll just need to search upon the data received on the backend via the ruby controller code.   The best way forward is to just cache the list of disabilities, then do some text searching on the values returned by lighthouse.  The data needing to be returned looks to just be the "name" and "id" of each pair. Name being the name of the ailment, and id maps to the "code" of a disability.  We can just return an array of json values for the frontend end to consume.

The research has brought to my attention that all data from the benefits reference endpoints can be cache.  This isn't necessarily in the purview of this ticket but perhaps something to look at later.

**Comment by NB28VT** [comment]
Quick Update, just got a great high level overview from Christine on what docs I need to read to map out the front end for this fix:

**Current Goals**
- [ ] Understand patterns for retrieving API data in the front end
- [ ] Understand how to work with the Redux store
- [ ] Understand how I would write a unit test for this
- [ ] Understand how if at all I would tweak the 526 form e2e cypress tests for this
- [ ] Understand how our form library works
- [ ] Map out what I would change where when we actually implement this new endpoint

TODO:
- [ ] Refresher on [Redux](https://redux.js.org/tutorials/index), which I haven't used in a few years and even then, it was set up in an unconventional way
- [ ] Review the [VA Forms Library documentation](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-overview)
- [ ] Review our [front end unit testing setup docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/unit-tests-for-forms-pages)

**Comment by NB28VT** [comment]
Nathan: note to self move this ticket to the "done" column once you've unblocked work on the ticket this blocks

**Comment by austinjprice** [comment]
@NB28VT @micahaspyr @tblackwe @RakshindaAslam @lydiahooper  moving to icebox as this is blocked based on feedback from TRex and Shannon Ford. Meeting with team 1, 3pm est and we can determine next steps to unbock or if this needs to go back to backlog
