### ISSUE TITLE
Descriptive Back Link on the Appointment Details page

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#59814]
## Description
We are improving the appointment details page by adding a descriptive back link allowing the Veteran to return to the previous page.

Current Design (mobile): 
<img width="303" alt="Screenshot 2023-06-06 at 3 36 37 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/90797205/2c02b421-184a-4e59-979b-16ac54e612f4">

---

## Acceptance Criteria
Background: the `va_online_scheduling_descriptive_back_link` toggle is on

- [x] Given when the user is on the Upcoming Appointment List 
       When the user clicks on the Details link
       Then the descriptive back link will be on the page
       And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/appointment-details.md#va-in-person) 
       And page design matches the [design spec](https://www.figma.com/file/rRC53gTEuva01EKfCdExeS/Appointment-list-navigation?type=design&node-id=1234-26284&t=eazMBNXplTJEJV1B-0) for mobile, tablet and desktop

- [x] Given when the user is on the Pending List 
       When the user clicks on the Details link
       Then the descriptive back link will be on the page
       And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/appointment-details.md#va-requests) 
       And page design matches the[ design spec](https://www.figma.com/file/rRC53gTEuva01EKfCdExeS/Appointment-list-navigation?type=design&node-id=1234-26284&t=eazMBNXplTJEJV1B-0) for mobile, tablet and desktop

- [x] Given when the user is on the Past List 
       When the user clicks on the Details link
       Then the descriptive back link will be on the page
       And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/appointment-details.md#va-in-person---past)
       And page design matches the [design spec](https://www.figma.com/file/rRC53gTEuva01EKfCdExeS/Appointment-list-navigation?type=design&node-id=1234-26284&t=eazMBNXplTJEJV1B-0) for mobile, tablet and desktop

### Design Assets
[Design Specs](https://www.figma.com/file/rRC53gTEuva01EKfCdExeS/Appointment-list-navigation?type=design&node-id=1234-26284&t=eazMBNXplTJEJV1B-0)

### Sample Design Spec for Mobile 
<img width="137" alt="Screenshot 2023-06-06 at 3 22 47 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/90797205/82e62624-02a9-4d97-a759-1344f76a1b32">

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by simiadebowale** [comment]
@ldelacosta @outerpress - this is ready for validation. `va_online_scheduling_descriptive_back_link` flag needs to be turned on for user to test

**Comment by Cieramaddox** [comment]
@ldelacosta This ticket has been validated and is good to go!

**Comment by ldelacosta** [comment]
Validated the changes in staging. No issues to report. Closing out the ticket. 

**Upcoming appointment details:** 
![Screenshot 2023-07-07 at 3.35.31 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/80cbc0d3-6fef-44e7-b30d-fd647d525139)

**Pending appointment details:** 
![Screenshot 2023-07-07 at 3.35.56 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/06e9d5fd-f65b-4c82-a438-fdef50a12911)

**Past appointment details:** 
![Screenshot 2023-07-07 at 3.36.41 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/b5b6d30d-de87-42b3-90b8-9472c10ee06f)
