### ISSUE TITLE
Analytics Research: Identify top 5 flow steps based on exit rate

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#59818]
Check in by eow (June 9) with Laura and Julie

**Comment by nnicholas7** [comment]
Analytics research can be found here: 526 Form Fields and Analytics- https://docs.google.com/spreadsheets/d/1MUFiKgz7NDZ__xFDRbGgJEFHfmOsWYPOyXe3C7tsSb8/edit#gid=810102445.

Steps highlighted in pink and gray have been selected as top steps based on exit.

Blockers
- Still trying to understand data analytics around drop rates

-

**Comment by nnicholas7** [comment]
Update as of 6/16/23
- Add a column for Hypothesized Solutions.  This section includes possible recommendations we can make for the top five drop-off steps
- I also created a document with all possible recommendations, general best practices, and resources that can be found here: https://docs.google.com/document/d/13hMUdXwXw8BN8yu-hYMje3P5tkB8e7i5wSv0VIMuv3U/edit#heading=h.pu2il5cssksv
