### ISSUE TITLE
Developer Research Spike: Logging and Monitoring

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#59821]
Acceptance Criteria:

1. Comprehensive overview of error handling and monitoring implementation with respect to 526
2. Finish document started by squad 1
3. Proof point of being able to create an event

Time-box: 20 (5 half days)

**Comment by SamStuckey** [comment]
Additional context from my initial research indicates that whoever focuses on the backend of this ticket will need to answer two primary questions:
1. What is our performance need / availability requirement for this data via that API?  This will inform whether or not we decide to cache this data at the application level (likely), or allow for a read through to the lighthouse API.  Caching will present the issue of cache breaking to consider, while non-caching will make our API dependent on lighthouse uptime and the appropriate query route being exposed by lighthouse, e.g. do they have a 'fuzzy' match api we can use?   This will also depend on the FE use cases captured by the FE researcher here.
2. What is our current solution for interacting with Lighthouse via the API?  In other words, how big of a lift will it be to plug our API into a new route (and potentially a cache busting webhook).  Is there an auth pattern to follow?  A Lighthouse API wrapper object, etc... To answer this question, research existing API to lighthouse requests.

**Comment by SamStuckey** [comment]
My previous comment was intended for another ticket, disregard.

**Comment by SamStuckey** [comment]
I've opened this document to track my findings as I step through.  My current approach for a first pass
- go page by page
- for each page, look for error handling (tag setting, product inclusion, catching, etc)
- notate assumptions for later verification

I'm assuming this will give me a birds eye view and allow me to make a few informed recommendations.  My WIP notes live in this document:

https://docs.google.com/document/d/12q_bqnMUGPjW1fk8YDEu-4qvx9S9Yu_vgheZVECl-j4/edit

Feel free to add comments but please do not edit the main text

**Comment by sortizsh** [comment]
Please move that document into here https://drive.google.com/drive/folders/1Vjkle-URBLGTJtXQb8ZVsbIiCpagy1GD
