### ISSUE TITLE
REPORT - Case Closure/Modification Report - VA T2 | Salesforce

### ISSUE THREAD

**Issue by edpearson20** [department-of-veterans-affairs/va.gov-team#59824]
See attachment

![Case Closure_Modification Report - VA T2_Salesforce.JPG](https://images.zenhubusercontent.com/5f9b3d8c88bc8853d462e678/0591995e-45fa-4a21-806d-87e634d1a61f)Case Closure/Modification Report - VA T2 | Salesforce
Report providing a record count of cases last modified by VA.Gov Tier 2 Tech Support whereas the status is Closed, In Progress, Follow Up, or escalated.	Current: Daily
Future: Daily, weekly, monthly
•	Daily – Include in ZH ticket that shows tier 2/3 case closures and modifications

**Comment by edpearson20** [comment]
The report has been fixed.  Here is some detail regarding my findings.  Since it was a report that I created, it doesn’t protect me from my own edits that may affect the future runs of the report.  I’ll often change the filter to see what cases I’ve closed on a particular day.  For example, I’ll change the VACX Case: Last Modified Date filter to “Today” so I can see the cases that I’ve closed / modified for that day.  If I do not change that filter back to “Yesterday” and since the report is generated in the early morning, it was not reflecting any data since no cases were closed / modified between 12AM and 1AM (when the report is set to run).

Here are the updates that I’ve made to try to alleviate future issues…

- [ ] I’ve changed the name of the report from to VACX Case Close_Mod AutoRpt T2 PriorDay
- [ ] I created a report for my use and renamed the report “VACX Case Close_Mod T2 PriorDay_EP”
- [ ] I verified our Young Lee as the correct alias (ylee) within the report.
Unfortunately, both Young Lee’s have the exact same Salesforce alias of ylee
- [ ] 	I added the alias’s shown below to the VACX Case: Owner Name filter so that all cases, including those owned individually, are reflected within the report.
WH VA Hotline Tier 2, WH VA Hotline EVSS Service Desk, aarca, amidd, clant, epear, imccu, kdani, mmana, starl, ylee
- [ ] Updated current distribution list of report to reflect the correct Young Lee.  Awaiting confirmation (next day) 2023-07-19 that report is distributed correctly.

***Note, the automatic distribution of the report is separate from the email aliases associated with the report.  Currently, there are two Young Lee users within Salesforce with no differentiation within the Users list upon attempting to add as a report recipient.

**Comment by manalo-soco** [comment]
Cc @edpearson20  
Automated report working as of 7/25:
**![image.png](https://images.zenhubusercontent.com/5e9f8d3341903e43c029c13e/774b962a-222a-412e-a832-bf1617c751f6)**

**Comment by manalo-soco** [comment]
@ATMiddleton  Do we move this into review?

**Comment by edpearson20** [comment]
This report is complete and awaiting review.

**Comment by ATMiddleton** [comment]
Kimberley/Chante/Anita review.
