### ISSUE TITLE
REPORT - Tier 2 Feedback Report | Salesforce

### ISSUE THREAD

**Issue by edpearson20** [department-of-veterans-affairs/va.gov-team#59827]
See attachment...

Tier 2 Feedback Report | Salesforce
Report providing feedback on cases routed to our team that could/should have been handled at tier 1 level	Monthly	Marlee, Todd, Sam, Chante, Anita, Ervin, Young, Mike

Reports	Description	Cadence	Recipients

![Tier 2 Feedback Report_Salesforce.JPG](https://images.zenhubusercontent.com/5f9b3d8c88bc8853d462e678/54f08ece-514a-49a6-b4f0-b0a69a93d34f)

**Comment by ATMiddleton** [comment]
Report has been created.
