### ISSUE TITLE
Salesforce Training (Email Builder) - Email Builder

### ISSUE THREAD

**Issue by edpearson20** [department-of-veterans-affairs/va.gov-team#59823]
Youngs training is complete with the exception of Email Builder and extenuating issues that he may run into with regard to Salesforce Case Handling.

This ticket is to address Email Builder and the training as it relates to Youngs (and the teams) remaining training items.

[ ] - Veteran Communication
[ ] - Outlook - Support Inbox(es)
[ ] - Omnichannel routing (Escalations)
[ ] - Knowledge management (Templates)

Reference Ticket #57350

https://app.zenhub.com/workspaces/contact-center-62cdd9546ec1530018209672/issues/gh/department-of-veterans-affairs/va.gov-team/new?issueType=issue

**Comment by ATMiddleton** [comment]
Closing as updated ticket #64275
