### ISSUE TITLE
REPORT - Daily Case Report EVSS T3 Issues | Salesforce

### ISSUE THREAD

**Issue by edpearson20** [department-of-veterans-affairs/va.gov-team#59829]
See attachment...

Daily Case Report EVSS T3 Issues | Salesforce
EVSS cases from the previous day. Reviewed by a Lead	Current: Daily
Future: Daily, weekly, monthly
•	Weekly – Include in ZH ticket that shows tier 2/3 case closure
Monthly – Include on SF dashboard for high level visibility.	Current – Internal team
Future- TBD

Reports	Description	Cadence	Recipients

![Daily Case Report EVSS T3 Issues_Salesforce.JPG](https://images.zenhubusercontent.com/5f9b3d8c88bc8853d462e678/9cdfe2b9-0169-4b51-91d8-9d40d0a2f2f7)

**Comment by Kimberley2019** [comment]
Hi Team! We made it through another week to a FRIDAY!!!!!! :its-friday: Here is the breakdown for Thursday (6/23) opened cases

Total Cases: 72
T[otal T2 Cases](https://va.lightning.force.com/lightning/r/Report/00O3d000000ZoQ5EAK/view?queryScope=userFolders): 28
T3 Cases: 44
VA.gov T[echnical Support T3 Cases](https://va.lightning.force.com/lightning/r/Report/00O3d000000ZoQAEA0/view?queryScope=userFolders): 25
[EVSS T3 Cases](https://va.lightning.force.com/lightning/r/Report/00O3d000000ZoPgEAK/view?queryScope=userFolders): 19
Please let me know if you have any questions!

**Comment by edpearson20** [comment]
I have completed the [VACX EVSS-T3 Open Case Data Report](https://va.lightning.force.com/lightning/r/sObject/00OOE000000JWry2AG/view?queryScope=userFolders)

Please inform whether or not this fits the needs.

**Comment by ATMiddleton** [comment]
@Kimberley2019 @kimb, @clantosswett and @ATMiddleton will discuss 7/21/23 and @ATMiddleton will update accordingly.

**Comment by edpearson20** [comment]
![image.png](https://images.zenhubusercontent.com/5f9b3d8c88bc8853d462e678/c40b1dd0-6369-4aee-be2b-6e7435da8aa4)

https://va.lightning.force.com/lightning/r/Report/00OOE000000JWry2AG/view?queryScope=userFolders

**Comment by starlow00** [comment]
Determining what data is needed from the report.

**Comment by ATMiddleton** [comment]
Kimberley/Anita/Chante will review off line and approve.
