### ISSUE TITLE
REPORT - Technical Support Cases Not Closed | Salesforce

### ISSUE THREAD

**Issue by edpearson20** [department-of-veterans-affairs/va.gov-team#59845]
See attachment...

Technical Support Cases Not Closed | Salesforce
Report created by Todd Unger, indicating aged technical cases that remain open.	Ad hoc	N/A

Reports	Description	Cadence	Recipients

![Technical Support Cases Not Closed_Salesforce.JPG](https://images.zenhubusercontent.com/5f9b3d8c88bc8853d462e678/29f416c7-86dc-4b3e-a768-369b92b702af)

**Comment by ATMiddleton** [comment]
Reports have been created.
