### ISSUE TITLE
REPORT - Weekly Open Cases Detail | Salesforce

### ISSUE THREAD

**Issue by edpearson20** [department-of-veterans-affairs/va.gov-team#59843]
See attachment...

Weekly Open Cases_ Detail | Salesforce
Cases Opened for the week broken down by case type and case category.	Current: Daily
Future: Daily, weekly, monthly
•	Weekly – Include in ZH ticket that shows tier 2/3 case closure
Monthly – Include on SF dashboard for high level visibility.	Current – Anita, Chante
Future - TBD

Reports	Description	Cadence	Recipients

![Weekly Open Cases_Detail_Salesforce.JPG](https://images.zenhubusercontent.com/5f9b3d8c88bc8853d462e678/73c184aa-0b7c-4d2a-9fa9-4da66f64c241)

**Comment by ATMiddleton** [comment]
Report has been created.
