### ISSUE TITLE
REPORT - Weekly Open Cases Detail | Salesforce

### ISSUE THREAD

**Issue by edpearson20** [department-of-veterans-affairs/va.gov-team#59842]
See attachment...

Weekly Open Cases_ Detail | Salesforce
Cases Opened for the week broken down by case type and case category.	Current: Daily
Future: Daily, weekly, monthly
•	Weekly – Include in ZH ticket that shows tier 2/3 case closure
Monthly – Include on SF dashboard for high level visibility.	Current – Anita, Chante
Future - TBD
![Weekly Open Cases_Detail_Salesforce.JPG](https://images.zenhubusercontent.com/5f9b3d8c88bc8853d462e678/d480dce1-bbe5-4b54-a397-0b4b4b4daf2f)

**Comment by Kimberley2023-CSM** [comment]
This report and information are outdated.  We are now using DOMO to track and report data.
Please refer to ticket https://app.zenhub.com/workspaces/vagov-veteran-support-62cdd9546ec1530018209672/issues/gh/department-of-veterans-affairs/va.gov-team/76582
