### ISSUE TITLE
REPORT - Tier 2 Tech Support | Salesforce

### ISSUE THREAD

**Issue by edpearson20** [department-of-veterans-affairs/va.gov-team#59846]
See attachment...

Reports	Description	Cadence	Recipients

Tier 2 Tech Support | Salesforce
Report created by Lana Waters indicating all tier 2 cases, original reporting	Ad hoc	N/A

![Tier 2 Tech Support_Salesforce.JPG](https://images.zenhubusercontent.com/5f9b3d8c88bc8853d462e678/8d5be088-da8a-43fb-bb72-6067ee9b0790)

**Comment by ATMiddleton** [comment]
Reports have been created.
