### ISSUE TITLE
Make tarball available in production

### ISSUE THREAD

**Issue by brandonrapp** [department-of-veterans-affairs/va.gov-team#5984]
Need access to the production content for use as part of the tome-sync build process.

Discussion:
We only require the production environment data but not sure if other environments could be utilized?

Acceptance Criteria
- [ ] Production content tarball is available for build process to consume

**Comment by ElijahLynn** [comment]
This is done now, see https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/READMES/cms-export.md for docs.
