### ISSUE TITLE
Terms of Use (Terms and Conditions)

### ISSUE THREAD

**Issue by mjconw3** [department-of-veterans-affairs/va.gov-team#59853]
VA.gov is looking to implement a policy and workflow for terms of use for users who access VA.gov. We need to build out this workflow and user experience for approval for stakeholders and implement it.

**Comment by jimcconnelly** [comment]
**Action Items from 11-01-2023 meeting:**

**Pre-Launch**
- Final legal document from Content Team _(Tom to get)_
- Logout URL for people who don't accept TOU. _(Alex)_
- Cerner Cookie.  _(Alex)_
- Request from MHV to send their users to our login page & redirect back to MHV afterwards. _(Alex)_
- Bug: mobile app not redirecting mobile users who don't accept TOU. _(Alex)_
- Remove Accept/Decline button placement on top. _(Alex)_
- Get a timeline

**Post-Launch**
- Add some indication that the Accept/Decline buttons are on the bottom?
- Do we want functionality to set one of the buttons as a default? _(Tom)_
- Continue to investigate how to make page more user-friendly:
   - Making the page more obvious as a Terms of Use Page
   - Remove whitespace
   - Content changes
- Add link in site footer so Vets can change their choice if they wish?
- Gather reporting metrics:
  - How many people accepted?
  - How many people declined
  - How many people took no action.
