### ISSUE TITLE
Create and automate monthly reporting

### ISSUE THREAD

**Issue by djmunoz1** [department-of-veterans-affairs/va.gov-team#59859]
As a dashboard admin I want a report that shows a monthly accounting of login instances for unique users across all active credential services.

Definition of Done:
• report is in .xls(x) format
• displays monthly count for all 4 credential services (MHV, DSL, Id.me, login.gov) since Jan 2022
• aggregates counts on 1) DSL and DSL with Id.me MFA and 2) MHV and MHV with Id.me MFA
• formatted in accord with the attached file
• automated to send monthly to specified users (see Dawn for list)

[Total CSP Auth by Unique User](https://app.zenhub.com/files/133843125/79b3bada-9e55-413d-9aa8-48849705474a/download)

**Comment by lmorris3** [comment]
Closing, all stories are complete.
