### ISSUE TITLE
AWS access for Tim Wright

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va.gov-team#59850]
### COR Name

Courtney Bethea

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### E-QIP Transmittal Date

- [x] Check this box if you have an E-QIP transmittal date.

### Your Name

Tim Wright

### Your Email

tim.wright@adhocteam.us

### Team, Role, and Company of the target individual

VA Mobile, Engineering Lead, Ad Hoc

### Product Manager (PM) name and email

Seth Eheart

### Product Owner (PO) name and email

Rachel Han, RachelXiaolu.Han@va.gov

### Desired AWS Access

I need access to the AWS Paramstore to store some sensitive keys

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

See screenshot in comment

### Additional Notes

Bill Chapman pointed me in this direction.

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by rmtolmach** [comment]
> I need access to the AWS Paramstore to store some sensitive keys

@timwright12, do you know which keys or paths in particular? This can help us scope your permissions accurately. 

re: E-QIP Transmittal Confirmation: It'll be an email that looks something like the one pasted in https://github.com/department-of-veterans-affairs/va.gov-team/issues/58352
I know you've been here a while, so if you're not able to dig it up you might be able to ask Bill for a workaround.

**Comment by timwright12** [comment]
@rmtolmach I need to add new keys for the mobile team to be able to use and access in CI workflows. We have some iOS/Android access keys we were told to store there.

Found the email, attaching here:

<img width="758" alt="Screenshot 2023-06-07 at 10 53 23 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/459581/66ac485f-8523-4e35-a246-f2367ae62298">

**Comment by timwright12** [comment]
Just checking in on this

**Comment by rmtolmach** [comment]
Hey @timwright12, one more thing. You don't actually exist on the [VFS roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665) 😱 Can you open up a [Platform orientation template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=analytics-insights%2C+analytics-request%2C+governance-team%2C+platform-orientation&template=orientation-epic.md&title=Platform+Orientation+Template+%5BYour+name+here%5D)? Once you open it in your name, you will get added (usually within a couple days).

**Comment by timwright12** [comment]
@rmtolmach all set https://github.com/department-of-veterans-affairs/va.gov-team/issues/60655

**Comment by rmtolmach** [comment]
Nice! And you've already been added to the VFS roster! 🎉 The next step is OCTO approval. And after that, DevOps Support will grant access.

**Comment by BillChapmanUSDS** [comment]
Access is granted but limited to 3 months as per process.

**Comment by timwright12** [comment]
Thank @BillChapmanUSDS! How do I get to it (login, etc - I didn't see an access email come through)?
I'm not sure 3 month access will work for the mobile team storing critical keys vs. github secrets, but I'll keep looking in there to something that meets our criteria

**Comment by flooose** [comment]
@timwright12 that's the next step. We're working on it :)

**Comment by timwright12** [comment]
@BillChapmanUSDS oh ok, Sorry!
