### ISSUE TITLE
Update Transformers to include new data (entity id's, breadcrumbs, etc...) 

### ISSUE THREAD

**Issue by brandonrapp** [department-of-veterans-affairs/va.gov-team#5986]
## Problem
The current transformers were written without tome-sync content that contained some data that's required in the transformers. If this data isn't added, the resulting HTML will be different in the tome-sync build than the GraphQL build.

## Acceptance Criteria
- [ ] `entityId` is added to all transformers where available
    - Not all transformers actually need it, but why not be consistent if we have the ability?
- [ ] `breadcrumb` is added where available
- [ ] All test data is updated

## Additionally
There are a couple other things to check for which may not produce any changes in the code.

- Verify `metatags` are still working properly
  - They were included in the original dump we were building from, but they weren't in the production Drupal build
- Verify `processed` strings are fine
  - Whatever this means
  - The strings in the tome-sync output didn't match the GraphQL version (`pages.json`)

**Comment by cvalarida** [comment]
I split this out into multiple separate tickets.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/11123
https://github.com/department-of-veterans-affairs/va.gov-team/issues/11125
