### ISSUE TITLE
Please remove Tuong Ngo (Tim) from VA Platform CoP DevOps

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#59864]
Tuong is on the VA.gov Identity team where I am the lead engineer. I am requesting that all of Tuong's permissions remain in place except the AWS and VA Platform CoP DevOps permissions. Please set Tuong's AWS permissions to read only and remove him from the DevOps group as soon as possible. Tuong's last day on the project will be June 19th at which time a full off boarding request will be put in.

## Related links
- discussion https://dsva.slack.com/archives/CBU0KDSB1/p1686078414198879
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/59809

**Comment by ryan-mcneil** [comment]
@joeniquette I just saw this while searching for proof of eQIP. Can I assume Tuong's [ArgoCD access request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/58305) can be closed, then?

**Comment by joeniquette** [comment]
Yes that can be closed as well.
