### ISSUE TITLE
Build automated report

### ISSUE THREAD

**Issue by djmunoz1** [department-of-veterans-affairs/va.gov-team#59863]
As a dashboard admin I want to an excel report that captures the CSP authentications for unique users so that I can share it with stakeholders.

ACCEPTANCE CRITERIA:
• report is in .xls(x) format
• displays monthly count for all 4 credential services (MHV, DSL, Id.me, login.gov) since Jan 2022
• aggregates counts on 1) DSL and DSL with Id.me MFA and 2) MHV and MHV with Id.me MFA
• formatted in accord with the attached file
[Total CSP Auths by Unique User](https://app.zenhub.com/files/133843125/2a74b786-e4fd-4c76-a029-3f51ad721e66/download) 
* automated to deliver on the 4th Monday of the month (this may change but any alterations will be noted here)
* automatically sends to specified user list (see Dawn for emails)
---
* Automation may not be possible depending on outcome of [tech discovery](https://app.zenhub.com/workspaces/logingov-adoption-team-632280b31e745000136a61fc/issues/gh/department-of-veterans-affairs/va.gov-team/59862). 

Definition of Done:
If automation exists, schedule test send to Dawn (dawn@themostudio.com)
If automation does not exist, sample report should be delivered manually to Dawn upon completion of this ticket and upon request (monthly) going forward.

**Comment by sdickson-gt** [comment]
Domo only supports CSV as attached data format.  Domo doesn't support data tables with dynamic column names, i.e. months (it can visualize as a datatable with months as columns but it is an image). To format the data as required, the data can be imported into Excel and formatted with a PivotTable.

An automated report has been set up to run on the 4th of every month. 

The monthly ETL of SSOe data into Domo may need to be manual in June if not yet automated by then.
