### ISSUE TITLE
BE | Auth Exp | Name Tag: Rated Disabilities | Migrate from EVSS to Lighthouse

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#59869]
The [Benefits Disability Experience team](https://www.google.com/url?q=https://dsva.slack.com/archives/C02CQP3RFFX&sa=D&source=calendar&ust=1681756396419963&usg=AOvVaw3FVomqTZdqf7Hcb2eUBUjA) has migrated the endpoint from EVSS to Lightouse so disability rating data will now come from the [Lighthouse Veteran Verification API](https://developer.va.gov/explore/verification/docs/veteran_verification?version=current).

Backend (vets-api) code will need to be updated to retrieve data from the new Lighthouse API endpoint.  This will affect the nametag/disability rating section for both the Profile and My VA pages.

The existing `/v0/disability_compensation_form/rating_info` endpoint will be updated to return data from Lighthouse instead of EVSS.

- [x] Add a feature toggle so that we can switch between EVSS and Lighthouse.
- [x] Add configuration for making Lighthouse calls.
- [x] Update `V0::DisabilityCompensationFormsController` to make service call to `VeteranVerification::Server`.
- [x] Add specs.

Acceptance Criteria:

- [x] Code review changes with Benefits Disability Experience BE engineer.
- [ ] Test in staging.

**Comment by mtcA6** [comment]
@tpharrison do we need to pull together front end tickets for processing error message differences, similar to the Direct Deposit work? Or will this be purely backend work?

**Comment by tpharrison** [comment]
@mtcA6 No, this is a simple read-only endpoint.  Any error messages should be consistent.

**Comment by tpharrison** [comment]
@mtcA6

Just tested this in staging.  The `profile_lighthouse_rating_info` feature flag is used to toggle between getting rating-info from either EVSS or Lighthouse.

- When turned off, data will come from EVSS.
- When turned on, data will come from lighthouse.

I tested the flag in the 'off' state and it works fine - data is returned from EVSS.

Testing with the flag 'on' returns a `404` error.  This might be due to a LH configuration settings in staging.  I will reach out to Aurora Hampton (on the benefits team) and ask.

**Comment by mtcA6** [comment]
@tpharrison do you need a new ticket to track that effort in coordinating with the LH team?

**Comment by tpharrison** [comment]
@mtcA6  Here is the ticket - https://github.com/department-of-veterans-affairs/va.gov-team/issues/60622.
