### ISSUE TITLE
SOCKS access for [Ben Allen]

### ISSUE THREAD

**Issue by ben-allen-oddball** [department-of-veterans-affairs/va.gov-team#59870]
### Your Name

Ben Allen

### Your Email

ben.allen@oddball.io

### Your Role and Team

DevOps Engineer

### Product Manager (PM) name and email

Nate Peterson, nate.peterson@adhocteam.us

### Product Owner (PO) name and email

Mike Chelen, michael.chelen@va.gov

### Access Type Requesting

platform

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDG//DTObMVdOaWpdBH6jJA1LRnBrtn21D5NkWWoDp52hJOujV2FLgv/tWEQ1buRrT5ouVQ7ILEfDk9MHeELOAgvxN7AvSz+R1dKxntCnwkVpbCnHyWJbh4tqLdplHqRMi3Sfq/IGLuT7C7E/4LCpzlQd0Q69oYxxR4yeaVOibwCRJNq7kzrXr19Ff4KS2oazBVRhsdVwBkHrRL2lrr1APC6fILQF2gcE0mRt/nF1R2KBDdqXRtAl1pO/M5RQKBdAQo8yYtqyVCNPdBcxkuZwW6WRlYQV0UKYiacNXp93RSAL1pkP00eeU6RyHU7atnlikhJMqiCjIFwllYjeaEOPfCO8G8WZ8RJ0/D3k6n/QNK6qEldkXU9J2y8mrIx8pRAl8jQpcUxuG6SzTdI5ypM4jVEseHXGMqVmemAHoBQoCuN34Uqx0a1/8cI2PxWOnMRDeN7tYslgxUtQP23XEdln9iGmNd2iARNb7vF3xdv43qdCSrq6xggU9S7r6ghcZytsc= bmallen@bmallen-StarBook

### E-QIP Transmittal Confirmation

![Screenshot from 2023-05-19 07-36-50](https://github.com/department-of-veterans-affairs/va.gov-team/assets/132920583/fb1293a4-a8df-468b-ab10-92be846f83d9)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [x] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by ph-One** [comment]
Found on Platform Roster
