### ISSUE TITLE
Clean up forms and forms-system folders 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#599]
The platform directory has two folders: `forms` and `forms-system`. The `forms-system` folder was the first part of reintegrating the forms system into `vets-website`. There is overlap between these folders that needs to be reconciled.

**Comment by andreahewitt-odd** [comment]
@rianfowler So just to be clear, we should only have the forms folder?

**Comment by rianfowler** [comment]
@andreahewitt-odd there should be only one folder and the duplicate stuff should be removed. I think it's up to @Clark-W-Griswold to determine how we structure it for long term needs (e.g. if we bundle it or put it in another repo).

**Comment by taylorkaren** [comment]
Forms: https://github.com/department-of-veterans-affairs/vets-website/tree/master/src/platform/forms.
Forms System: https://github.com/department-of-veterans-affairs/vets-website/tree/master/src/platform/forms-system

**Comment by caw310** [comment]
Closing

**Comment by caw310** [comment]
Closing as this is old there is a team focused on building forms and updating the forms library. If this is still an issue, file a new bug for the forms team.
