### ISSUE TITLE
Fix time zone display on Confirmation Page

### ISSUE THREAD

**Issue by narin** [department-of-veterans-affairs/va.gov-team#5990]
## What happened?
Time zone shows up as `null` on confirmation page

## Desired behavior
Time zone should be removed as in previous design or fixed

## Steps to reproduce
1. Create a new appointment with direct schdule

## Screenshots
![image](https://user-images.githubusercontent.com/786704/75285133-e1b57f80-57ca-11ea-9bcf-f5379df73add.png)

## Acceptance Criteria
- [ ] Time zone should be removed as in previous design or fixed

**Comment by jbalboni** [comment]
@narin Where do you see this happening? I see the tz locally and on staging.

**Comment by jbalboni** [comment]
I think I might have been looking on the review page, I see it on staging on the confirmation page.

**Comment by narin** [comment]
I saw it come up as `null` briefly while we were demo'ing last week on staging.  I'll try to reproduce it on my end.
