### ISSUE TITLE
[identity-helm-library] - Add code checks

### ISSUE THREAD

**Issue by rileyanderson** [department-of-veterans-affairs/va.gov-team#59948]
## Issue Description
Add code check that run on merges to main and on pull_requests.
These checks should run `unit-tests` and `lint`
Merging to main should be blocked until these checks pass

## Devops tasks
- [x] Create code_checks.yml workflow
  - [x] Unit tests
  - [x] lint
  - [x] check if docs created
- [x] Update branch protection rules to block unless passing
- [x] Update documentation

## Acceptance Criteria
- [x] Checks successfully run
- [x] Branch protection rules updated
- [x] Documentation updated

**Comment by aparsley** [comment]
Looks great, keep up the good work and thank you for checking off the Acceptance Criteria.
