### ISSUE TITLE
Request Design Review - STEM Application

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#5995]
**Context:** 
The Buffalo Regional Processing Office reports more than 90% of Rogers STEM Scholarship applications are being denied due to ineligibility.  The new functionality provides cues, messaging, obstacles and alternate options for individuals passing through the Education Benefits routing wizard and VA Form 22-1995 to inform them of the specific scholarship requirements and alert them if it appears they may not be eligible. 

- **VA Form 22-1995 application** - https://staging.va.gov/education/apply-for-education-benefits/application/1995/benefits/stem
 
- **Prototype (Wizard & Form)** - https://bahdigital.invisionapp.com/share/9GIACS4WX82#/screens

**New Design Patterns (if any):** N/A

**Design Challenges (if any):** 

_Tricky design problem 1_: The most challenging issue with this form was getting users to pause, engage with the content that indicated they weren't eligible and then provide a viable off-ramp for them.  We put together and tested one solution that we thought would be effective and it failed completely.  Users clicked right through and continued applying - even though we were telling them they weren't eligible.  The team quickly turned around a new solution that included a stand-alone "Based on your responses, it appears you're not eligible" page which performed really well.  The page, which is ONLY shown to applicants who don't meet the scholarship criteria, presents the scholarship criteria with the applicants responses so they can track where they don't align.  In addition, the page offers a number of attractive alternate pathways for ineligible applicants so they don't feel like continuing with the application is their only path forward. 

_Tricky design problem 2_: On the ineligibility alert page, mentioned above, we used 3 icons to show criteria that 1) was met (green check); 2) wasn't met (grey X); 3) wasn't specified (grey question mark).  The color-coding is not the sole indicator of the status and we worked with Trevor to address 508 concerns & considerations for structuring the content effectively for screen readers. 

NOTE: 508/Accessibility review for this work completed under https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/5869

**Comment by amyknox** [comment]
@CrystabelReiter - I think you already completed this review as part of the STEM Wizard update.
@1Copenut - You have a separate issue for 508 this time.

**Comment by 1Copenut** [comment]
Thank you @amyknox for the link to your QA team's accessibility testing. It should make my staging review go smoothly and quickly. I'll be going through that later today.
