### ISSUE TITLE
Vets-api terminal access for Evan

### ISSUE THREAD

**Issue by eubiera** [department-of-veterans-affairs/va.gov-team#59952]
### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Evan Ubiera

### Your GitHub handle (terminal access is managed through GitHub)

evan.ubiera@va.com

### Team, Role, and Company of the target individual

Developer

### Product Manager (PM) name and email

Alina Murphy, alina.murphy@va.gov

### Product Owner (PO) name and email

Luciana Morais, luciana.morais@va.gov

### Your dsvagovcloud AWS user name (if applicable)

Evan.Ubiera

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [ ] sandbox
- [ ] production (if requesting, justify prod access in 'Additional Notes' section)

### COR Name (leave "None" if you listed an AWS user name above)

Cecila Lee

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

Liberty IT -  Michael G. Lovejoy

### Access Expiration

04-12-25

### Additional Notes

I need this monitor some tables that are getting written to from the chatbot, via Azure. 

### User must exist in a roster before vets-api terminal access can be granted

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added
- [ ] If they included an AWS user name, check to see if their user name is listed in [iam_users.tf](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf)
- [ ] Comment in this issue saying which roster the user is listed in and confirming their AWS user name (if applicable)

**Comment by ryan-mcneil** [comment]
@eubiera Can you please provide a screenshot of your eQIP `Transmittal Notice` email?

**Comment by eubiera** [comment]
<img width="701" alt="EQIP-confirmation" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/117054459/dc0cbdff-335d-4572-890c-d37523830f72">

**Comment by ryan-mcneil** [comment]
User is on VSF Team Roster

**Comment by ryan-mcneil** [comment]
@eubiera Thanks! You’ve been granted access to the `dev` and `staging` environments.

Here's some additional documentation for the [Vets API on EKS](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-TerminalAccess)
