### ISSUE TITLE
Helm Chart Template:External DNS Endpoint

### ISSUE THREAD

**Issue by mjconw3** [department-of-veterans-affairs/va.gov-team#59966]
## Description
In order to properly isolate Sign in Service, we need to create Helm chart templates for each component of SiS. The deliverable for this ticket will be a Helm chart for External DNS Endpoint created in the new child repo.

## Acceptance Criteria
- [x] Verify the Chart is working as intended
- [x] Helm chart reviewed and approved by another member of the team

## Tech Notes

**Comment by vidjovanovic** [comment]
Currently working on this now, have added `Kind: DNSEndpoint` as resource and am building it out.

**Comment by vidjovanovic** [comment]
Have submitted PR for this.

**Comment by vidjovanovic** [comment]
Finished 06/29

**Comment by aparsley** [comment]
Looks great, thank you for checking off criteria.
