### ISSUE TITLE
Helm Chart Template: Deployment

### ISSUE THREAD

**Issue by mjconw3** [department-of-veterans-affairs/va.gov-team#59964]
## Description
In order to properly isolate Sign in Service, we need to create Helm chart templates for each component of SiS. The deliverable for this ticket will be a Helm chart for Deployment created in the new child repo.

## Acceptance Criteria
- [x] Verify the Chart is working as intended
- [x] Helm chart reviewed and approved by another member of the team

## Tech Notes

**Comment by vidjovanovic** [comment]
This was started on a few days ago, just created a PR for it last night:
https://github.com/department-of-veterans-affairs/identity-helm-library/pull/7

**Comment by vidjovanovic** [comment]
I got my review back from Riley and am working to fix some of the issues in my deployment.yaml and values.yaml based on his comments.

**Comment by vidjovanovic** [comment]
Finished 06/29

**Comment by aparsley** [comment]
Thank you for going back into the review and correcting issues.
