### ISSUE TITLE
Helm Chart Template:IngressRoute

### ISSUE THREAD

**Issue by mjconw3** [department-of-veterans-affairs/va.gov-team#59967]
## Description
In order to properly isolate Sign in Service, we need to create Helm chart templates for each component of SiS. The deliverable for this ticket will be a Helm chart for IngressRoute created in the new child repo.

## Acceptance Criteria
- [x] Helm chart template created for IngressRoute in new child repo
- [x] Verify the Chart is working as intended
- [x] Helm chart reviewed and approved by another member of the team

## Tech Notes

**Comment by aparsley** [comment]
Looks great, thanks for checking off all your dependencies.
