### ISSUE TITLE
[ISSUE] undefined is not an object (e.mailingAddress.country)

### ISSUE THREAD

**Issue by va-albers** [department-of-veterans-affairs/va.gov-team#59965]
# Instructions
Please fill out the form below, providing as much detail as possible. 

## Issue Description
Weekly we see between 1 and 12 of the following errors in Sentry:

> TypeError
> undefined is not an object (evaluating 'e.mailingAddress.country')

from /generated/526EZ-all-claims.entry.js

See examples at:
[Sentry report](http://sentry.vfs.va.gov/organizations/vsp/discover/results/?field=title&field=event.type&field=project&field=user.display&field=timestamp&name=All+Events&query=%22undefined+is+not+an+object+%28evaluating+%27e.mailingAddress.country%27%29%22&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1)

---

### Information needed to assess the severity of the issue
- Users Impacted:    ? There are 51 events, 21 users impacted in the last 90 days.
- Issue Impact:       Unknown.  We need to validate how this happens to understand the impact.
- Workaround:        N/A
- Legal Requirement:  N/A
- Loss of Service:    Paper forms should be an alternative, but the answer would be better known when exact issue is determined.   
- Permanent Impact:   This may stop processing for a particular claim.  The idea that 21 users had 51 events suggest that users had to retry this step.
- Vulnerability:      Unlikely

### Information that aids in the research and troubleshooting of the issue
- Date and Time of Issue:     Ongoing, but examples go back to at least March 14th
- Form/Page of Issue:         /generated/526EZ-all-claims.entry.js
- Error Message:              ![image.png](https://images.zenhubusercontent.com/63b72d0f91f21b3f4235de84/45903116-6efd-4394-960c-6bb00fdbe5f4)
- How to reproduce:           TBD
- Unique IDs:                 N/A
- Application ID:             ?
- Hardware Issue Observed On: N/A
- Browser type / version: Mobile Safari (16.1, 16.2), Safari (16.4, 16.5, ), 
- Case#
- Reporter name in va.gov: Steve Albers (using Sentry reports), issue was not directly reported.

### Any Additional Information:
- Does it impact a specific flow or population? Possibly only Safari users?
- Is this issue seen consistently or has it just started? It has been ongoing at a very low level since at least March 2023

**Comment by tblackwe** [comment]
acknowledged. thank you for bringing it to our attention

**Comment by tblackwe** [comment]
It is interesting this only affects Apple Users. possibly a downstream effect of safari privacy settings. 

Regardless, development will need time to find the code that is failing (generated location doesnt help much sadly). Once they locate the offending code can make a recommendation on how to root cause and fix.

**Comment by RakshindaAslam** [comment]
Need the following:
- User Impact
- # of users
- Is there a workaround?
