### ISSUE TITLE
Helm Chart Template: Datadogmetric

### ISSUE THREAD

**Issue by mjconw3** [department-of-veterans-affairs/va.gov-team#59972]
## Description
In order to properly isolate Sign in Service, we need to create Helm chart templates for each component of SiS. The deliverable for this ticket will be a Helm chart for Datadogmetric created in the new child repo.

## Acceptance Criteria
- [ ] Helm chart template created for Datadogmetric in new child repo
- [x] Verify the Chart is working as intended
- [x] Helm chart reviewed and approved by another member of the team

## Tech Notes

**Comment by vidjovanovic** [comment]
Started on 06/26 - Doing research but will have to reach out for help with this one. Will probably use 'externalmetric' resource

**Comment by aparsley** [comment]
Thank you for checking off criteria.
