### ISSUE TITLE
Helm Chart Template: Autoscaler

### ISSUE THREAD

**Issue by mjconw3** [department-of-veterans-affairs/va.gov-team#59971]
## Description
In order to properly isolate Sign in Service, we need to create Helm chart templates for each component of SiS. The deliverable for this ticket will be a Helm chart for Autoscaler created in the new child repo.

## Acceptance Criteria
- [ ] Helm chart template created for Autoscaler in new child repo
- [x] Verify the Chart is working as intended
- [x] Helm chart reviewed and approved by another member of the team

## Tech Notes

**Comment by vidjovanovic** [comment]
Completed this hpa auto scaler and am ready for review.
