### ISSUE TITLE
Convert remaining components to USWDS v3

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#59985]
## Problem Statement 
The DST has been working on upgrading to USWDS v3. The team focused on converting components that would be used in the Forms Library so that the Veteran Facing Forms Library Team could start building forms using v3 USWDS MVP components. But there are more components in the VADS that need to be converted. 

How might we provide a consistent design system to VFS teams to use to build forms and digital applications using the most up to date components? 

## Hypothesis or Bet
*How will this initiative impact the quality of VFS or Platform teams' work?*
*How will this initiative be easy for VFS or Platform teams? Or how will it be easier than what they did before?*
Converting all the relevant components to USWDS v3 will allow VFS teams to build more consistent digital applications. 

## We will know we're done when... ("Definition of Done")
*What requirements does this project need to meet for you to finish this initiative?*
The following components have been converted: 

File Input
Pagination
Featured Content
Table
Search
Reconcile adding character count to Text Input and Text Area - updating our design 

## Known Blockers/Dependencies 
*List any blockers or dependencies for this work to be completed*

## Projected Launch Date
FY Q1 2023 (Q4)

**Comment by humancompanion-usds** [comment]
@caw310 - Please provide an update. I believe we just have Table left to do? I think everything else is either done or actively in flight. Can you confirm and delivery date? Thanks.

**Comment by humancompanion-usds** [comment]
The File input component from USWDS was lacking in some critical design elements (no clear way to replace or remove an uploaded file) that caused us to have to redesign it and now rebuild it. That's underway but, it's going to take a few more sprints to get done. Table is in progress and should be done next sprint. Those are the 2 remaining components that don't have a v3 equivalent.

**Comment by humancompanion-usds** [comment]
## Deprecation of v1 components - Deadline Wednesday May 8th

* The ask: Please move all v1 web-components to their v3 equivalent. 
* NOTE: There is no deadline for converting "imposter" components to v3
* Also, this excludes the following v3 components that are still in-work:
    * va-table - [v3 borderless table available in Storybook](https://design.va.gov/storybook/?path=/docs/uswds-va-table--default); guidance and sorting to follow.
    * va-file-input - v3 version to be available end of May
    * va-number-input - Prefix and suffix will be added to va-text-input and va-number-input will be deprecated as the functionality will all be present in va-text-input.
* 56 instances of v1 components remain (1.7% of all components)
* All v1 web-components will be removed from code on July 31st. Thus any exemptions given expire on 7/31.

**Comment by caw310** [comment]
Update for Q2 work on Converting remaining components to USWDS v3 
* va-table has been converted- [v3 borderless table available in Storybook](https://design.va.gov/storybook/?path=/docs/uswds-va-table--default); [guidance now available](https://design.va.gov/components/table). We will be adding sorting to va-table in Q3
* va-file-input - v3 single file input is done. We are working on multiple file input which will be available at the end of June
* va-number-input - will be deprecated and functionality will be added to va-text-input (such as prefix and suffix)

**Comment by humancompanion-usds** [comment]
@caw310 - Either we have a date for finishing this or we create a new initiative for just these 3, open that for the next quarter, and close this one. Thanks.

**Comment by caw310** [comment]
@humancompanion-usds I will close this initiative and write a new initiative for finishing up va-table, va-file-input and completing, adding fetures to va-text-input and deprecation work for va-number-input.

**Comment by caw310** [comment]
For reference. https://github.com/department-of-veterans-affairs/va.gov-team/issues/85615
