### ISSUE TITLE
QA Standards - Benefits Team 2 - Financial Status Report (FSR)

### ISSUE THREAD

**Issue by it-harrison** [department-of-veterans-affairs/va.gov-team#59993]
#### VFS team name
Benefits Team 2

#### VFS product name
Financial Status Report (FSR)

#### VFS feature name
FSR Enhancements
#### Point of Contact/Reviewers
Ian Harrison - @it-harrison  - QA specialist
---
#### Regression Test Plan 
- [ ] Standard has been met
- [x] Standard has not been met
##### Explanation of failure to meet standard (if applicable): #####
No regression plan artifact.

#### Test Plan
- [x] Standard has been met
- [ ] Standard has not been met
#### Traceability Reports 
- [x] Standard has been met
- [ ] Standard has not been met
#### E2E Test Participation
- [x] Standard has been met
- [ ] Standard has not been met
#### Unit Test Coverage 
- [ ] Standard has been met
- [x] Standard has not been met
##### Explanation of failure to meet standard (if applicable): #####
No code coverage artifact
---
### Product defects (bugs) found:
* If you put in a value of $ 1 for bills or expenses that you have, it will make some of the values negative ($ -1) instead of the value that was actually input.  This has happened 3 times on 3 different screens whereby you can enter dollar values.
![Screen Shot 2023-06-08 at 2 10 02 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8867779/eeaabfc3-9c82-452b-a966-2fce24241bd9)

* If you go to Step 4 of 7: Household expenses > randomly start selecting or checking all of the boxes > some checks will disappear if you check a different box and reappear on a completely different box. 

* on Step 4 of 7: Household expenses, when inputing credit card information there is no validation to prevent negative numbers:
<img width="793" alt="Screenshot 2023-06-08 at 4 26 22 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/8867779/1e56a491-07df-4cd8-9b8b-e1fde80ff51e">

### VFS Guidance

- Close the ticket when your Product Owner determines that you have sufficiently met the QA Standards.
- If your team has additional questions or needs Platform help validating the issue, please comment on the ticket

### Platform directions
- Update "Issue Title" to be of the form "QA Standards - VFS Team - VFS Product"
- Add the VFS team, product name, and feature name
- Add your name, practice area, and GH handle under Point of Contact/Reviewers
- Complete the QA Standards section, making sure to include an "Explanation of failure to meet standard" for every Standard the product does not meet.
- Link to the Collaboration Cycle Request epic
- Add assignees: 
  - VFS PM
  - Yourself (optional)
- Add labels:
  - VFS team label
  - VFS product label
  - QA-standards label
  - launch-blocking label if the product has failed to meet a required QA Standard

**Comment by HeatherRienks** [comment]
Closing this ticket as it appears that no further QA Validation is needed. Refer to Staging Review QA Standards ticket (#63629). 

cc: @Tom-Davis
