### ISSUE TITLE
[Bug] Facility Locator - Search button cut off on tablet screens

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#5999]
## What happened?
On Staging Facility Locator, the Search button is cut off at right edge of tablet screens.

## Specs:
**Browser(s)/Device(s)**:
* iPad 6th gen
* iPad Air 2

## Steps to Reproduce
1. Go to https://staging.va.gov/find-locations/
1. Either resize browser window to tablet screen-width, or activate Chrome Dev Tools' iPad emulator.
1. Observe that **Search** button is cut off at right edge of tablet-screen.

**iPad 6th gen example**
![search-btn-styling-ipad-gen6-200219](https://user-images.githubusercontent.com/587583/74865748-e1227200-530e-11ea-9969-34da7b4ae5d1.png)

## Desired behavior
**Search** button is displayed fully on tablet screens.

## Acceptance Criteria
\[see **Desired behavior** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by mmiddaugh** [comment]
Confirmed on my iPad.

**Comment by mmiddaugh** [comment]
fine in landscape, still present in portrait
