### ISSUE TITLE
VFS Support: Spanish translation of new benefits hub pages

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#60]
**Problem:** We do not provide user-friendly, Veteran-focused translations of essential benefit information online. Federal regulation (see below) requires each agency to translate important information. Currently, VBA translates regional office sites and print brochures in Spanish (and some Tagolog). A handful of outdated online benefit pages are translated in Spanish. VHA does not provide any translation of health benefits information. 

**Primary need:** Currently the most up-to-date, Veteran-focusing benefit content online is not available in translation to LEP (limited English proficient) users. 

**Hypothesis:** We believe our primary users are LEP family member beneficiaries and/or caregivers of LEP Veterans. And that there are older Veterans (Vietnam era) who are LEP and currently don't access all the benefits they're eligible for partly due to language barrier. 

**User value:** Localization of key benefit hubs will provide a small but forgotten audience better access to important benefit information.
^added 8/20/19

Starting issue here, so we have central place to add information during this early discovery stage. Once it gets further along, I think this would be a good thing to do a project brief for this. (@lalexanderson-dsva  - maybe?)  Also this would be a nice thing to do some user research around or at least usability sessions to inform how we might better provide access paths to translated content (less hidden than a text link which is how legacy pages link ppl to Spanish content). 

Please feel free to add screenshots of good/bad translation affordances here, so we can consider external ideas! 

@rtwell  and @lalexanderson-dsva  @chrisj-usds @bethpotts  - for now,  fysa only. 

### Info from comments in 2019:

Ryan Thurwell's Invision prototype link - used for the usability/user research sessions: https://vsateams.invisionapp.com/share/DCRWYHDNVPM#/screens

Old WIP research folder moved here: https://github.com/department-of-veterans-affairs/vets.gov-team/tree/master/Products/Global/benefits-spanish-localization

And new user research docs here: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/content/spanish-translation

**Comment by jenniferlee-dsva** [comment]
@DanielleSoCompany  and @mnorthuis  - Adding spreadsheet here from/to Sandy Tadeo. You'll see a couple rows where we currently don't have VA.gov new page equivalent to the Spanish and point to a legacy page. So these might affect you as you complete legacy rewriting, if you decide content on any of those pages need to be brought over to the new hubs. If that happens, please sync with Sandy re possibly getting the new rewritten content in his translation work stream (if the timing works out). 

His new translation contract will start September. (But he's trying to figure out page inventory/word count before then, for budgeting purpose.)

And Danielle - please let us know here what you learn from JeffG re VHA translations, if any. 
[All_Translated_Contents-VBA-SandyTadeo-040319-jlee.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3070983/All_Translated_Contents-VBA-SandyTadeo-040319-jlee.xlsx)

**Comment by jenniferlee-dsva** [comment]
Esp language toggle example - body content level
![spanish-toggle](https://user-images.githubusercontent.com/43381063/56002574-f8c1b080-5c90-11e9-8cbb-b17b80ee227a.jpeg)

**Comment by lalexanderson-dsva** [comment]
Thanks @jenniferlee-dsva - I'm happy to work with you on a project brief/roadmap. As you've had the most convos on this, it'd be helpful if you could be our "expert" on this for the time being. I'd love to see if Carola or any of our designers and user researchers who speak Spanish might be interested in helping us out with some user research here.

**Comment by rtwell** [comment]
On what page(s) within VA.gov will this live?

**Comment by jenniferlee-dsva** [comment]
@rtwell - it would be on several existing benefit hub pages. We're still working on the inventory - Sandy's spreadsheet ^ is not final and it's only VBA-administered benefits. Danielle is checking with Jeff G about health pages we might do the same for. 

@lalexanderson-dsva  - Carola - that's a great idea! And I could be really wrong here about what's needed - maybe simple is best? (Just not they way they do it today on legacy pages, which kind of buries the text link in the right rail, or sometimes way down low on the body of pg.)

**Comment by jenniferlee-dsva** [comment]
Adding a couple examples from NYT. They just use a simple text link, but at the TOP of the page, before body content, so it's pretty visible but without being distracting. 

Ix path, IA seem different depending on whether the translation content is just a page translation vs. content that lives on a localized site (like China edition of the nytimes.com). 

En source page: https://www.nytimes.com/2019/04/07/smarter-living/how-to-be-happier-at-work.html

ESP page: https://www.nytimes.com/es/2019/04/10/como-ser-feliz-en-el-trabajo/   [unique esp URL, but not a localized site. ]
![esp-language-nyt-example](https://user-images.githubusercontent.com/43381063/56045461-4aa91b80-5d0f-11e9-904d-9c414313033d.png)

**Comment by jenniferlee-dsva** [comment]
NYT example when there are 2 languages available. 
EN source page: https://www.nytimes.com/2019/04/10/world/asia/taiwan-china-united-states.html

Tr Ch: https://cn.nytimes.com/asia-pacific/20190411/taiwan-china-united-states/zh-hant/  [points to localized site pg - China NYT edition of nytimes.com]

S Ch: https://cn.nytimes.com/asia-pacific/20190411/taiwan-china-united-states/

![2019-04-11_22-51-01](https://user-images.githubusercontent.com/43381063/56045522-66142680-5d0f-11e9-84b8-32625dd5d15a.png)

**Comment by jenniferlee-dsva** [comment]
Including government examples. 

From Misty Sweet: 
https://www.usa.gov/ 
https://www.usa.gov/espanol/ 
 
In footer of https://www.hhs.gov/ 
https://www.hhs.gov/civil-rights/for-individuals/language-assistance/index.html#spanish 
 
And on Gov.uk site - footer: https://www.gov.uk/  - they have a link to Welsh translated content.

**Comment by jenniferlee-dsva** [comment]
Resources, best practices to consider:
https://digital.gov/resources/top-10-best-practices-for-multilingual-websites/

Spanish language style guide for IT terms:
https://digital.gov/resources/spanish-language-style-guide-and-glossaries/spanish-language-style-guide-glossaries-information-technology-terms/

https://digital.gov/resources/top-10-best-practices-for-multilingual-websites/

A bit old, but interesting - Nat'l Cancer Institute's Spanish language persona research: https://digital.gov/2015/03/02/persona-development-case-study-nci-and-spanish-language-outreach/

Federal regulations stuff... 
[Spanish-translation-VA.gov-project-brief-DRAFT-042219.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3104882/Spanish-translation-VA.gov-project-brief-DRAFT-042219.docx)

https://www.lep.gov/13166/eolep.htm
EO 13166 and its accompanying policy guidance require agencies and groups that receive federal funding to provide all users with “meaningful access” to their services, meaning that “the programs and activities they normally provide in English are accessible to LEP persons.” (Source: https://sunlightfoundation.com/2019/02/14/explained-the-federal-governments-responsibilities-to-provide-online-content-in-non-english-language/)

The attached brief is still in-flight - DRAFT. 
[Spanish-translation-VA.gov-project-brief-DRAFT-042219.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3104886/Spanish-translation-VA.gov-project-brief-DRAFT-042219.docx)

**Comment by jenniferlee-dsva** [comment]
Interesting update - about the different IA approaches in the NYT examples. @mnorthuis - FYSA. https://github.com/department-of-veterans-affairs/va.gov-team/issues/60#issuecomment-482599526 

The esp content initially was page level translation only - they had kept the nav, menu, related stories, etc., in English. But going back to NYT Spanish pages recently, they've gone fully localized - so there's actually a localized SITE, where now everything is localized.  (Impossible without enterprise level MT+human translation.)  

Since VA.gov doesn't have enterprise-wide localization budget or initiative at this point, I think we should treat this as an MVP, and start with page-level translations.

**Comment by jenniferlee-dsva** [comment]
Top organic search pages for Spanish language benefits (VBA benefits):
[Analytics-organic-Spanish-benefits-April 2018-2019-042919.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3128609/Analytics-organic-Spanish-benefits-April.2018-2019-042919.xlsx)

Top traffic pages - VBA benefits in Spanish:
[Analytics-top-all-traffic-Spanish-benefits-April 2018-2019-042919.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3128636/Analytics-top-all-traffic-Spanish-benefits-April.2018-2019-042919.xlsx)

**Comment by carolaponce** [comment]
@jenniferlee-dsva  per our meeting today, here are some thoughts about planning our initial research.  **Feel free to clarify any of my points.**

### Goals:

- To provide English-as-a-second-language (ESL) or limited-English-proficiency (LEP) Veterans, beneficiaries, or caregivers access to plain language, single source of truth, benefits content, so they have equal access to the benefits they have earned.
- To meet federal/agency requirements for providing translated benefit information.
- IA - To determine the best way to present Spanish language materials:
- 1.  Most important information - most necessary, most visited, most searched, etc. 
- 2. Best way to navigate to translated content.
- Figure out needed resources - Necessary budget, contracting resources to get these translations done, reviewed and shipped.

**User Archetypes**
- Veterans
- Claimants: Family members and Caregivers

_Other possible archetypes, but not likely:_

- Power of Attorney
- Attorney
- Contestant claimant (could be a family member or an attorney)

**Where can we look for users?**

Without having the actual date on the number of Veteran populations, these are the U.S. regions with greater Spanish speaking populations:
- Puerto Rico
- Southern California 
- New York, New Jersey, Long Island 
- Miami, Fort Lauderdale, Pompano Beach FL 
- Texas
- Bay Area CA
- Washington DC Metro Are
- Chicago IL

[A good reference to Spanish speaking regions](https://en.wikipedia.org/wiki/List_of_United_States_cities_by_Spanish-speaking_population)

**Content we need feedback about**
I am reviewing the list of links you provided but I would really on your knowledge of va.gov to navigate the right approach to test the Information architecture.

**NOTES:**

I like the idea of including a link on regular VA content to translated pages - Español Link -  at the top of the page, etc…

I like the idea of linking to Translated pages from the footer, but this would require a separate IA to link all information in Spanish, in a separate hierarchy based on prioritized content.

I would like to include a page like this from the footer: https://www.hhs.gov/civil-rights/for-individuals/language-assistance/index.html#spanish

**Other notes:**

- Use a stand-alone, dedicated URL for marketing and search engine optimization (SEO) purposes.
- Let's conduct usability tests to understand the cultural considerations of this target audience. _Regardless of the language used, the online experience must be culturally relevant to achieve an emotional connection with the audience._

**Other resources**
https://www.usa.gov/espanol/militares-y-veteranos
https://www.usa.gov/espanol/beneficios-familias-militares

**Comment by DanielleSoCompany** [comment]
Hi @jenniferlee-dsva. Here's an update from my call today with Jeff Grandon from VHA:

- Jeff is not aware of federal regulations for VHA content in this area.
- Jeff can be our point of contact on this, but he is also going to reach out to the VHA Health Eligibility Center to ask about key content for translation.
- Jeff also may have translation resources who are familiar with VHA content. He will follow up to find out about this.

If I don't hear before then, I'll check in with Jeff for a status update at next week's weekly meeting. Thanks!

**Comment by jenniferlee-dsva** [comment]
For WIP usability session discussion guide, mockup Spanish content, project brief: 
https://github.com/department-of-veterans-affairs/vets.gov-team/tree/master/Products/benefits-spanish-localization

For research plan:  
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/user-research/spanish-translation

Lauren is getting Perigean started on recruiting for mid-May.

**Comment by jenniferlee-dsva** [comment]
@carolaponce  - @rtwell is going to work on low fidelity mockups of our pages today. Could you tell him what the link/affordance text in Spanish should be for our test? I like the New York Times example above but not sure if that's the best for our context. Could you make a few suggestions? Thank you!

**Comment by carolaponce** [comment]
### Capturing notes and ideas about content recommendations. I will add more as we gather user feedback.

**Glossary of VA specific terminology**
There are terms used throughout the VA that become the name of a benefit or a project or a process, these can get translated to Spanish using different words depending on who is translating them.

For example, Dishonorary Discharge can be translated as:
Baja Deshonrosa
Or
Descarga Deshnorable

- They are both correct, so it is important to decide what translation to use for each name of processies or benefit and consistently use these options.
- Keep this glossary updated and accessible for all future translations.

**VA brand**
Our current va.gov pages in Spanish use:
Veterans Benefits Administration as the header of each page.
Decide what the brand names should be, if this needs to always be in English for name recognition, etc.

**Voice & Simple language**
When presenting information to Veterans and their families, use simple language and present information as if you were talking to them, instead of talking about them like they are a 3rd person.

**Familiar vs. Formal ways to address your user.**
**Tu (Vos) vs. Ud.**
Depending on the country or region, native Spanish speakers are more or less likely to use a more personal way to address others such as tú, or a more formal like usted.

My recommendation is to translate VA information in a formal way, addressing the user as usted or ud.

**Comment by jenniferlee-dsva** [comment]
From Misty Sweet: 
Jen and Sandy,

Sending [Celebrating our “Quinceañero” blog link](https://blog.usa.gov/celebrating-our-quinceanero) from USA.gov. Think the background and info is helpful. It also references EO 13166 and we 

I am not sure if the author of the above blog is still active but [Laura Godfrey](https://digital.gov/communities/multilingual/), the Multilingual Community of Practice at USA.gov, seems to be. Also thought the [Multilingual Community of Practice listserv](https://digital.gov/communities/multilingual/) might be a useful resource.

**Comment by jenniferlee-dsva** [comment]
Government-wide repository of Spanish/multilingual translation glossaries (IRS, HHS, SSA, Nat'l Cancer Inst, etc.) https://digital.gov/resources/bilingual-glossaries-dictionaries-style-guides/   (A good place to include VA terms when we get one.)

**Comment by tadeosss** [comment]
**Other agency websites with Veterans and service members' benefits information in Spanish**

I think the sites below were curated content for Spanish but I’m not sure what their process was. The main usa.gov benefits content (links below) pertain to both military and veterans so it doesn’t just comprise of VA content. They have more content in English and they didn’t seem to translate all their English content into Spanish.

**USA.gov**
-English: https://www.usa.gov/military-and-veterans
-Spanish: https://www.usa.gov/espanol/militares-y-veteranos

On that note, we also work with **Benefits.gov** in regards to Veterans benefits:
- https://www.benefits.gov/categories/Military%3A%20Active%20Duty%20and%20Veterans
- https://www.benefits.gov/es/categories/Military%3A%20Active%20Duty%20and%20Veterans

**Comment by tadeosss** [comment]
Hi @carolaponce, please refer below for my input regarding your recommendations:

**Glossary of VA specific terminology**
I think this is a great idea. We can compile terminologies as a reference for translators and users. I like the glossaries mentioned on the [Digital.gov site](https://digital.gov/resources/bilingual-glossaries-dictionaries-style-guides/), either as a PDF or a web page.
@jenniferlee-dsva, are we going to include a this list/glossary on the [VA content style guide](https://design.va.gov/)?

**VA brand**
_Our current va.gov pages in Spanish use:
Veterans Benefits Administration as the header of each page.
Decide what the brand names should be, if this needs to always be in English for name recognition, etc._

I think that we should not translate the agency/administration's name into Spanish, according to 6102 standards:
- https://vaww.va.gov/6102/VA_Graphic_Standards.asp
- https://vaww.va.gov/6102/seals.asp

I did not read any mention of translated content but it stated that we should not change the titles. We use English titles/signatures on our Spanish fact sheet headers. I did not see any mention of the seal/signature on the new VA content style guide.

**Voice & Simple language**
_When presenting information to Veterans and their families, use simple language and present information as if you were talking to them, instead of talking about them like they are a 3rd person._
I agree, per Plain Language, we should avoid 3rd person, if possible.

**Comment by carolaponce** [comment]
Our feedback review session notes:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/60

**Comment by jenniferlee-dsva** [comment]
Share out of synthesis scheduled with VBA, VHA, and NCA partners on June 10, 2pm.

**Comment by jenniferlee-dsva** [comment]
Deck from user research share-out. 
[VA.gov-Spanish-benefits-link-user-research-061019.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/3273454/VA.gov-Spanish-benefits-link-user-research-061019.pdf)

From Danielle - VHA print publication - translated online: https://www.va.gov/healthbenefits/resources/publications/hbco/

**Comment by jenniferlee-dsva** [comment]
FYSA. 
@tadeosss, @DanielleSoCompany, and I had a call with Les' in NCA. VHA no show. NCA doesn't currently have a translation program but they're willing to contribute funding to Sandy's translation vendor budget, so we can translate selected benefit pages in the burials/memorial hub, too.  Next: will track down VHA. 

Thank you Sandy - he's going to be our point for translation program! /jen

Email thread. 

From: Devine, Daniel C. 
Sent: Tuesday, June 18, 2019 5:02 PM
To: Melnyk, Les' <Les.Melnyk@va.gov>; Nosal, Timothy A. <Timothy.Nosal@va.gov>
Cc: Tadeo, Sandy A., VBAVACO <Sandy.Tadeo@va.gov>; Brunner, William S. <William.Brunner@va.gov>; Lee, Jennifer Y. <Jennifer.Lee27@va.gov>; Provost, Lawrence A. <Lawrence.Provost@va.gov>
Subject: RE: Spanish translation > benefits content > coordination of translation & funding

I will work this. It is something I’ve been working on anyway 


Sent with BlackBerry Work
(www.blackberry.com)
From: Melnyk, Les' <Les.Melnyk@va.gov>
Date: Tuesday, Jun 18, 2019, 4:54 PM
To: Nosal, Timothy A. <Timothy.Nosal@va.gov>, Devine, Daniel C. <daniel.devine@va.gov>
Cc: Tadeo, Sandy A., VBAVACO <Sandy.Tadeo@va.gov>, Brunner, William S. <William.Brunner@va.gov>, Lee, Jennifer Y. <Jennifer.Lee27@va.gov>, Provost, Lawrence A. <Lawrence.Provost@va.gov>
Subject: RE: Spanish translation > benefits content > coordination of translation & funding

Danny; Tim;
 
I had the pleasure this afternoon of chatting with Sandy Tadeo of VBA and Jennifer Lee of OIT (CC line).  The topic was translating some of our benefits information into Spanish for the new VA.gov website.
 
As VA stands up its new website and benefits content is given a new, fresh look, OIT is making an effort to ensure benefits availability information is translated into Spanish.  Jennifer’s office has done some research into this, and found that Spanish translations are particularly useful for family and caregivers.  I can share OIT’s research with you if you like.  To my knowledge, NCA does not currently have any benefits information in Spanish and does not have its own Spanish translation service or contract.
 
In order to get our benefits information translated, OIT is suggesting that NCA add money onto a translation contract that VBA already has.  This would ensure consistency of the translated word across the new VA.gov site.  Presumably, this would mean that NCA would transfer some funding to VBA in exchange for the service.  It would not be a particularly large amount of money – for example, NCA has already been provided its page on the new website to review.  The page contains nearly all of the NCA benefits information we’d like to convey:  https://vagov-content-pr-137.herokuapp.com/burials-memorials/eligibility/  
 
There are just over 2,400 words on this page when you open up and count all the sub-pages (by clicking on the little “+” signs).  Sandy Tadeo told me he believes that the cost of translation to Spanish is about 7 cents per word, so a ballpark total of $168.  There may be additional translation work that needs to be done as additional NCA material if brought over to VA.gov, but probably not much.  Not everything that NCA has on its current website needs to be translated on the new VA.gov – just the benefits information that we feel is most important for the public at large to have.
 
It seems almost silly to ask, but who in NCA could effectuate an intra-departmental transfer of less than $500 to VBA?
 
R/
Les’
 
Les' A. Melnyk
Chief, Public Affairs and Outreach
National Cemetery Administration
Department of Veterans Affairs
Les.Melnyk@va.gov
(Desk) (202) 443-5644
(Cell)  (202) 891-9987
 
Follow us:
      
Visit our website:  http://www.nca.va.gov
 
 
From: Lee, Jennifer Y. 
Sent: Tuesday, June 18, 2019 4:45 PM
To: Melnyk, Les' <Les.Melnyk@va.gov>
Cc: Thierry, Danielle E. <Danielle.Thierry@va.gov>; danielle@thesocompany.com; Tadeo, Sandy A., VBAVACO <Sandy.Tadeo@va.gov>; Grandon, Jeffrey <Jeffrey.Grandon@va.gov>; Brunner, William S. <William.Brunner@va.gov>
Subject: Spanish translation > benefits content > coordination of translation & funding
 
Hi Les’, 
It was nice to meet you, and thank you for helping us get this to the “right lane.” Per our call, I’m including here 2 decks – one about the initial project discovery and the other a summary of the research user interviews we conducted. 
 
Summary:
•	Sandy Tadeo is PM for VBA’s translation contract. He works with a COR for funding. To get started, please connect the person you identify for us to Sandy. Please cc me if you don’t mind, so I can ensure we keep moving forward and can help nudge things along if needed.
•	The translation cost is around 7 cents/word. This is just a ball park. 
•	For translation MVP, we will identify select benefit pages (so not all of burials hub or VA.gov). 
•	The initial user research indicates that Veteran family members and caregivers are a primary audience for translated benefit information. 
•	Burials and memorial benefit hub – Beth Potts is currently working with Scott to get SME feedback on additional parity/legacy content migration. 
•	Sandy shared a couple of VBA-hosted fact sheets about burial benefits. Jen will share with Beth and confirm if we have 1)captured that for parity and 2) if we should remove them from VBA pages. 
 
 
 
--
Jennifer Lee
Content Designer
Digital Service at VA
Jennifer.lee27@va.gov  | 202-664-6532

**Comment by jenniferlee-dsva** [comment]
All - @tadeosss and I met. Based on the user research findings we decided to change our approach for what to translate for MVP. 

Instead of translating selected pages across all benefit hubs, we will instead take a vertical hub approach - pick 1 to a few hubs and translate all of the pages inside that hub, including nav. 

**Next step:** 
- Break out of this discovery issue and start Epic and milestones. (I need help with this part, @chrisj-usds . Okay if I reach out to Kara for help? )
- Offline - Sandy and I will identify which hub/s (of Disability, Housing, Pensions, Edu) and non-VBA (Burials, Health care).

**Comment by jenniferlee-dsva** [comment]
@tadeosss: 
Benefit hub pages - complete list as of 6/28, per Mikki's doc: https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Information%20Architecture/files/VA.Gov%20Master%20URL%20Mapping%2006282019.xlsx

Per Nick - Our sitemap is actually generated during every build, so this list is always the most up-to-date, https://www.va.gov/sitemap.xml

**Comment by mnorthuis** [comment]
@jenniferlee-dsva fyi regarding the xml sitemap...it is not a complete listing of all pages on the site, and also include some  pages that really shouldn't be in the xml.  There is a backlogged issue to work on this somewhere down the line.  The Master URL file is a complete listing of all static pages.

**Comment by tadeosss** [comment]
Hi, @mnorthuis, the Master URL link above is 404 for me.

**Comment by jenniferlee-dsva** [comment]
[VA.gov-URLs-06282019.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3369317/VA.gov-URLs-06282019.xlsx)

Sandy - I emailed you the raw file. Here attached again. (I removed the vanity urls sheet as I don't think we need that for our purposes.)

**Comment by chrisj-usds** [comment]
@jenniferlee-dsva Could we add to the top level description the primary need / user value / problem  here?

**Comment by jenniferlee-dsva** [comment]
@chrisj-usds - like this okay? https://github.com/department-of-veterans-affairs/va.gov-team/issues/60#issue-432317355

**Comment by aeltarhoni** [comment]
@Karak888 will follow up.

**Comment by jenniferlee-dsva** [comment]
Old WIP research folder moved here: https://github.com/department-of-veterans-affairs/vets.gov-team/tree/master/Products/Global/benefits-spanish-localization

**Comment by jenniferlee-dsva** [comment]
Ryan Thurwell's Invision prototype link - used for the usability/user research sessions: https://vsateams.invisionapp.com/share/DCRWYHDNVPM#/screens

**Comment by jilladams** [comment]
CAIA drives translation, and manages benefit hubs. This old ticket is no longer at the front of translation efforts. Closing, and Sitewide will coordinate with CAIA for future iterations to benefit hubs for translation.
