### ISSUE TITLE
Access for Michael Talbot

### ISSUE THREAD

**Issue by talbotmj** [department-of-veterans-affairs/va.gov-team#600]
# Instructions
1. Fill out **Description**
1. Add the label used by your team (eg: `BAH-526`)
1. Assign the issue to your DSVA contact 

# Description
- Please provide your name.
   > Michael Talbot
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > MyHealtheVet, Software Engineer, BYLIGHT
- Request type: [ AWS console, SSH key internal tools ]
   > SSH Key access?
   > Access to internal tools or access to the AWS console? Internal Tools, Developer tools.
- ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDa+8RZFo9VU/pPlFMSG8VIfsiJbNZyaIbumS9FawYnB/xWvK7uJx+HwDv8sDy7YJ4ZJR638O9kJi0/BGLkS0L6D/Sdqd6nQ4xrNZkWJsAoglpjTzvdNXgawr3MH+tICr9gqlCw/bOo7c0uaOSDQTpYf7r19beXQ77FBPGX9yd6zmLE3F7Ofd/ezkGQ+tr9WVwsbv7aSFp6QFhzFF0V53duR/LSdAE7tS7JBCO9Z/x1wGsHiD8D4KRJdmP+aXsy0znVC1dc65HpbOvOCNq7cmuAIyS1bG7SHByEZhankPWaKb8EOULbft9rXV2sBXa9ut1kkn6vbiDXCzl8BaNA3ZeotHLYqShboKFNyrwAwTYB6KQOWy3M/naGeFgpLo10gLmDuQX+tnl3I3sJvDNpcUq2LlcBjMTYh091mVg0OOFEcpzVfKZj1wHlsLas399Qx9T9njFQQxdHIUki3/YXyHkM4TeGvYuZRoxFYo0wViaCyiFUgyLZYDdNppmxHP3QqpHHsNl3Fcr61slZpbZFML+Ebqsp/vvxGS2ojLHbSVU5mLucTbr9UP+9W+jYQKGHz4wKYWbyCL2C2uE5uyGYjKT1i+kuKENYp7HIofsq67+omIy07Kh4+161egkzCDYhIQCt2YIyfGITUCEt61BZxTDHysp2kuN+KYZE/JBLerW8qQ== michael.talbot@va.gov
 

@smoonpeyes for review (not sure how to add you as an Assignee

**Comment by talbotmj** [comment]
I am unable to determine how I add an assignee to this issue/request for access - I believe I need to 'tag' this for: vsp-operations  and assign Layla Soileau layla@adhocteam.us to review/

**Comment by smoonpeyes** [comment]
Thanks, @talbotmj! Tagging @department-of-veterans-affairs/vsp-operations to take a look.

**Comment by b00klegger** [comment]
`ssh` public key deployed to infrastructure. Please continue with [step 3](https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/Onboarding/request-access-to-tools.md#3-when-your-key-has-been-added-dsva-will-close-the-github-issue-which-will-send-a-github-notification-to-you-this-is-your-signal-that-you-can-continue-to-the-next-step).
