### ISSUE TITLE
Implement New Secure Message onsite notification

### ISSUE THREAD

**Issue by A6-toma** [department-of-veterans-affairs/va.gov-team#60007]
As a user, I want to see a notification on the landing page when I have unread secure messages in my inbox so I can take action on those messages as needed.

Steps in the user flow:
1. provider sends new message
2. user signs into va.gov
3. user navigates to va.gov/my-health
4. user sees notification letting them know they have unread messages (_content text TBD_)
5. User sees a badge if unread messages exist in their inbox 
5. user clicks notification
6. user lands on message center (va.gov/my-health/messaging/inbox - _**need to verify correct path**_)
7. user sees unread messages

[Related Slack thread](https://dsva.slack.com/archives/C0581MN69TJ/p1687365157722479)

### Acceptance Criteria
- [ ] A badge exists showing if there are unread messages in the user's inbox
- [ ] When the user has at least one unread message in their inbox, a notification appears on the landing page alerting them about the unread message(s)
- [ ] Clicking the landing page notification navigates the user to their inbox
- [ ] Review Authenticated Experience code for notification to determine accessibility  
- [ ] Click volume on secure message link can be measured 
- [ ] Accessibility passes in Staging (rollback if functionality does not pass accessibility review)

**Comment by LynneJohnson224** [comment]
Authenticated experience team is implementing this on My VA. We will pick this ticket up after that team does user testing and passes it over to this team.

**Comment by LynneJohnson224** [comment]
@jzucadi @radavis can you please add a story point value to this ticket?

**Comment by LynneJohnson224** [comment]
accessibility review - label is not associated correctly and needs to be corrected.

**Comment by LynneJohnson224** [comment]
@radavis to check the PR status

**Comment by radavis** [comment]
This merged PR _should_ have fixed accessibility for this feature: https://github.com/department-of-veterans-affairs/vets-website/pull/26118

**Comment by LynneJohnson224** [comment]
Accessibility passed (Test User 41) - https://dsva.slack.com/archives/C0581MN69TJ/p1697475278706389
