### ISSUE TITLE
Access for Beau Grantham

### ISSUE THREAD

**Issue by beaugrantham-va** [department-of-veterans-affairs/va.gov-team#6000]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Courtney Bethea
- Please provide your name.
   > Beau Grantham
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > LAP, Liberty IT Solutions, Software Engineer
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Internal%20Tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDeMF50b6k9IPxCJUPvhX2BoU8trVv88rpx03igmP4ycEelvYj2uS/pGPWuAT19RxaxcpOKcYoOIb+mqJ6YhRQlXULf5OVK1FDJCOxU2bzvmEoEAKL/QqgWLXfUMh1JB5mvWUUmH/yv1kCqRX0UWNyWNjI9y+gMqTImVNLO8/zqjDZg8Af298TvFUs57dRh5YQ83/dyKnaEMBiQPD6CHqfLVFEQ6JqSUJuoKEFNHuieEAmCN8/PW/g87zVrSLT//K+fGf3KPSmIAY6k2wVXAt4bIQ1kkAjL2+9I2sNDx2rSpNYSZ128awIhUpreIlqcM53xNiRhiXiD1o0Ogjz1+ssN beau@DESKTOP-BGRANTHAM
```

- [Grant AWS Console access?]
  > NO
  >  AWS console access already granted. Just need the SSH key above.

**Comment by beaugrantham-va** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by tskinn** [comment]
@Jeff-Hayter 
COR: Courtney Bethea
Name: Beau Grantham

**Comment by ricetj** [comment]
due to new changes in the process, SOCKS access is granted sooner. You should now refer to this section of the instructions to set up your SOCKS. Please Also keep following up with your paperwork for the VA.
