### ISSUE TITLE
Veteran cannot add files to their claim

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#60042]
Veteran claims the files tab is missing from the claim details page. Was able to submit a claim successfully with attached files, but when going to view the claim, they cannot see the files uploaded, or even the files tab.

**Comment by jerekshoe** [comment]
I would make sure that this is actually a claim that they are talking about, I'm not aware of there being any way that a specific tab would not render for claim details

**Comment by kjduensing** [comment]
For example a supplemental claim, appeals, decision review - no files tab shows up, probably
