### ISSUE TITLE
Update to download decision letters web content in CST

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#60047]
## Issue Description
While Misty was giving feedback to Benefits team engineer, she gave incorrect feedback on copy changes related to copy shown on the CST for closed claims with/without the claims letter link [(ticket 55675)](https://github.com/department-of-veterans-affairs/va.gov-team/issues/55675). This issue was opened by to correct the copy. And the copy changes noted below are only for the body copy in the informational alert that is displayed.

---
## Acceptance Criteria
- [x] When the user is reviewing a closed claim in which we show the claims letters link, the body copy for the informational alert will read:
- You can download your decision letter online now. We also mailed you this letter.

- [x] When the user is reviewing a closed claim in which we don't show the claims letter link, the body copy for the informational alert will read:
- We mailed you a decision letter. It should arrive within 10 days after the date we decided your claim. It can sometimes take longer.

---
## Other notes
Misty and Laura talked about this copy correction on 6/9 and agreed to these changes.

**Comment by mistymg** [comment]
Hi @jacobworrell! @jaredcunha knows about this ticket. I gave him some incorrect feedback on a prior ticket and this new ticket is to correct my mistake. Let me know if either of you want to chat about it. Thanks, and sorry Jared for the confusion!
cc: @laurwill

**Comment by jaredcunha** [comment]
Pull request started. 

The first checkbox up top was already correct, but I corrected the second one. 
https://github.com/department-of-veterans-affairs/vets-website/pull/24527/files#diff-d92dba5c0b4fd7d97d7943f805dc10d696169b0853ffc87f34c40fb0178dbbdbR18-R26
