### ISSUE TITLE
AWS access for Justin Lattimore

### ISSUE THREAD

**Issue by Wyzardsleeves** [department-of-veterans-affairs/va.gov-team#60048]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### E-QIP Transmittal Date

- [ ] Check this box if you have an E-QIP transmittal date.

### Your Name

Justin Lattimore

### Your Email

justin.lattimore@va.gov

### Team, Role, and Company of the target individual

MHV Secure Messaging, Software Engineer, By Light Professional IT Services

### Product Manager (PM) name and email

Patricia Henry  - Patricia.Henry@va.gov

### Product Owner (PO) name and email

Lichelle Bain - lichelle.bain@va.gov

### Desired AWS Access

Requesting the SSMApplicationLowerEnvironmentAccess policy, and to be added to the existing IAM group dsva-vfs-developers

### Access Expiration

Ongoing

### E-QIP Transmittal Confirmation

![Screenshot 2023-06-09 at 11 55 43 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/9909777/881ea939-a839-4ebd-b913-363e047580be)

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by BillChapmanUSDS** [comment]
Approved for lower environment access

**Comment by flooose** [comment]
Hi @Wyzardsleeves, so it turns this [group already has this permission](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf#L2111).

Did you have problems with something specific that led you to believe this permission was missing?

**Comment by flooose** [comment]
Closing this. Feel free to reopen if problems persist or arise.
