### ISSUE TITLE
Fix web component being required after touched

### ISSUE THREAD

**Issue by rhasselle-oddball** [department-of-veterans-affairs/va.gov-team#60059]
from Jeana open issues referenece: https://github.com/department-of-veterans-affairs/va.gov-team/issues/59928

1. if you focus a web component, enter something to trigger validation, then blur, then try to submit, you can't proceed because it thinks its required, even if its not.

Test on any field (e.g. a text field) which is not required, but has a pattern match, such as email or ssn or phone.
Not sure if applies to all fields, or just ones with 'pattern' match.
Done ✅

2.
Fix being able to not continue on memorable date
Done ✅

3.
#### SSN Pattern
When the SSN isn't validated in one field, it automatically is invalidated down the page for a field that hasn't been filled out yet. This error did *not*  occur for the VA file number or service number patterns.
Done ✅

https://github.com/department-of-veterans-affairs/va.gov-team/assets/117098918/d6121d80-8bbc-4876-8d52-4263103f193f

4.
#### Error showing up on input focus AND submitting w/out required fields.

There's two things happening in this video.
1. The error message displays that the field is not filled out as soon as I click in the field. (time stamp 0:03) It should only show up onblur after I tab out of the field if there is an error
2. When I go back and clear out that field, I am able to still continue to the next page even though this field is required.
Done ✅

https://github.com/department-of-veterans-affairs/va.gov-team/assets/117098918/e5384375-dde0-43ec-9a8c-b91d11b066aa

5.
### How did keyboard testing go?
Note: covered by this ticket: https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team/60060

I was trapped within memorable date inconsistently. Even though the date matched the validation requirement, I could not use the keyboard to submit the form. Once I clicked on all the fields with the mouse, sometimes I was able to click submit with the mouse. Here's a video of the behavior:
Done ✅

https://github.com/department-of-veterans-affairs/va.gov-team/assets/117098918/e4419f05-0b51-45bd-b4d6-30bb848fcebb

Also, the error validation would be triggered before I had a chance to finish filling out the fieldset.

**Comment by rhasselle-oddball** [comment]
note: this is defect as part of the RJSF/web-component integration. in the forms-system/src/js/web-component-fields, forms-system/src/js/web-component-patterns directories, and/or forms-system/src/js/components/FieldTemplate.jsx file. 

can test this with simple-forms/mock-simple-forms-patterns form
yarn watch --env entry=mock-simple-forms-patterns
and going to http://localhost:3001/mock-simple-forms-patterns/introduction

**Comment by jeana-adhoc** [comment]
@rhasselle-oddball - Here is the [staging review ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60378) where there's another/similar issue regarding the field being touched a second time triggers error messages regardless of anything having been typed before.

**Comment by rhasselle-oddball** [comment]
fixed majority of issues but needs another round of testing since there were several things touched
