### ISSUE TITLE
Request for Information (RFI)

### ISSUE THREAD

**Issue by ianMcCullough-ob** [department-of-veterans-affairs/va.gov-team#60067]
### Information Type Requested

Support

### Date Range Start

01-01-2023

### Date Range End

06-09-2023

### Tool Name(s)

Contact Center

### Tool Description

Testing ticket submission.

### Tool URL and term(s)

Anything mentioning "feedback" or "play 12 of the USWDS playbook"

### File Delivery Format

Test

### VA Email Address(es)

ian.mccullough1@va.gov

### Add Assignee and Labels

If not already done so, please ensure @Kimberley2019 is set as the assignee for this issue and "VSP-contact-center" and "request-for-information-cc" are set as labels.
Please leave this field as is when submitting.

**Comment by Kimberley2023-CSM** [comment]
Closing ticket.  This process is outdated, and another process has been incorporated for RFI creations. 

Please refer to ticket https://app.zenhub.com/workspaces/vagov-veteran-support-62cdd9546ec1530018209672/issues/gh/department-of-veterans-affairs/va.gov-team/73952
