### ISSUE TITLE
Vets-api terminal access for [Thomas Blackwell]

### ISSUE THREAD

**Issue by tblackwe** [department-of-veterans-affairs/va.gov-team#60077]
### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Thomas Blackwell

### Your GitHub handle (terminal access is managed through GitHub)

tblackwe

### Team, Role, and Company of the target individual

Teams DBEx 2, Non-Disability Benefits Exp, Dependents Exp. Tech Lead from Coforma

### Product Manager (PM) name and email

Austin Price austin.price@coforma.io

### Product Owner (PO) name and email

Matt Self matthew.self2@va.gov

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### COR Name (leave "None" if you listed an AWS user name above)

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

Other - please specify in 'Additional Notes'

### Access Expiration

ongoing

### Additional Notes

COR: Jennifer O'Day
VOR: Jeff Langworthy [jeff.langworthy@coforma.io](mailto:jeff.langworthy@coforma.io)

I need this access to investigate issues in vets-api. I need to be able to debug and review so that I can understand issues and bugs in vets-api. 

### User must exist in a roster before vets-api terminal access can be granted

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added
- [ ] If they included an AWS user name, check to see if their user name is listed in [iam_users.tf](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf)
- [ ] Comment in this issue saying which roster the user is listed in and confirming their AWS user name (if applicable)

**Comment by ryan-mcneil** [comment]
Exists on VFA Roster, and found EQIP Transmittal screenshot in his [AWS Request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60005) (FYI @BillChapmanUSDS ) 

✅

**Comment by ryan-mcneil** [comment]
@tblackwe  You’ve been granted access to the `dev`, `staging`, and `sandbox` environments.

Here's some additional documentation for the [Vets API on EKS](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-TerminalAccess)

Access to `prod` is pending approval by OCTODE, and we'll update you as soon as it's available.

**Comment by ryan-mcneil** [comment]
😆

**Comment by BillChapmanUSDS** [comment]
Access granted with 3 month period as per policy. 

The next renewal we will be stricter about the justification. For example, troubleshooting should be done via logs shipped to Datadog, SPlunk etc.. and issues should be debugged in lower environments. Developers who are not Devops team members and who commit code to vets-api as developers will begin to see production access reduced in the future.

**Comment by bdech** [comment]
@tblackwe You've been granted Prod access for 3 months, expiring 9/21/23

**Comment by bdech** [comment]
slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1687366810350949)

**Comment by bdech** [comment]
@tblackwe Per an update to our access policy, your ArgoCD/vets-api Production access has been extended for 3 months, expiring 12/21/23. Please set a reminder for yourself to return to this Issue and re-request access within 1 week of the expiration date. You'll receive 1 reminder with a 72 hour window to respond. Failure to do so will result in lost access and will require you to fill out a new request.

**Comment by bdech** [comment]
slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1695304545188559)

**Comment by bdech** [comment]
@tblackwe Your Vets API Terminal Production access has expired.

Would you like to request an extension? You have 72 hours to respond, or your 
access will be revoked and you will need to fill out a new request.

**Comment by tblackwe** [comment]
Yes. I need this every day to research and remediate claims. Please extend my access.

Cc @va-albers @BillChapmanUSDS @emilytheis

**Comment by bdech** [comment]
@LindseySaari @ericboehs can one of you please give us a :thumbsup: to extend their access?

**Comment by bdech** [comment]
@little-oddball can one of you please give us a 👍 to extend their access?

**Comment by bdech** [comment]
@little-oddball can you please give us a 👍 to extend their access?

**Comment by little-oddball** [comment]
> @little-oddball can you please give us a 👍 to extend their access?

Sorry I missed this yesterday. Yes, please extend their access.

**Comment by bdech** [comment]
@tblackwe Your `Production` access has been extended 6 months, expiring 06/21/24. Please set a reminder for yourself to return to this Issue and re-request access within 1 week of the expiration date. You'll receive 1 reminder with a 72 hour window to respond. Failure to do so will result in lost access and will require you to fill out a new request.

**Comment by bdech** [comment]
support slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1703794267109659)

**Comment by tblackwe** [comment]
Yes, please renew my access, I am still supporting Code Yellow

**Comment by davidpetras** [comment]
@LindseySaari  @ericboehs  can one of you please give us a 👍 to extend their access?

**Comment by davidpetras** [comment]
@tblackwe Your Production access has been extended 6 months, expiring 12/25/24. Please set a reminder for yourself to return to this Issue and re-request access within 1 week of the expiration date. You'll receive 1 reminder with a 72 hour window to respond. Failure to do so will result in lost access and will require you to fill out a new request.

**Comment by AnthonyWFlowers** [comment]
Greetings @tblackwe your access has expired. Would you like to request an extension? You have 72 hours to respond, or your access will be revoked and you will need to fill out a new request. Thank you

**Comment by AnthonyWFlowers** [comment]
Greetings @tblackwe vets-api prod access, will be removed. If you again need access please fill out a [form](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-Access) to request prod access. Thank you.
