### ISSUE TITLE
Identity Dashboard (FE) - Set up Chakra UI

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#60070]
## Description
Set up Chakra UI to integrate with the Identity Dashboard (FE)

## Tasks
- [ ] Integrate Chakra UI into the current Identity Dashboard (FE)
- [ ] Integrate VA Design System with Chakra UI (if necessary)

**Comment by acald-creator** [comment]
Closing in favor of https://app.zenhub.com/workspaces/identity-5f5bab705a94c9001ba33734/issues/gh/department-of-veterans-affairs/va.gov-team/59982
