### ISSUE TITLE
[SCREENREADER, KEYBOARD]--PART 2: Edit address link will not receive keyboard focus r

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#6008]
## Description

This is an add-on to ticket #5866.  Per Jennifer Strickland, the edit it link in the paragraph is address, and the "Edit this address" link needs a similar treatment in order to be focusable. 

https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/5866

## Point of Contact
**VFS Point of Contact:** Jennifer

## Acceptance Criteria
As a keyboard user, I want to be able to tab to all interactive content on the page.

As a keyboard or screen reader user, I want to be able to access the ability edit my address from the "Please confirm your address" screen.

## Environment
Operating System: all
Browser: all
Screenreading device: all
Server destination: staging

## Steps to Recreate
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/5866

**Comment by Samara-Strauss** [comment]
@bradl3yC can you add an estimate to this when you get a chance?

**Comment by bradl3yC** [comment]
@Samara-Strauss done - 1

**Comment by bradl3yC** [comment]
@Samara-Strauss ready for validation

**Comment by Samara-Strauss** [comment]
I'm still not able to tab to this link:

<img width="436" alt="Screen Shot 2020-02-21 at 1 20 02 PM" src="https://user-images.githubusercontent.com/34068740/75060535-fe8d4280-54ac-11ea-807a-d68e500ce4ee.png">

**Comment by jenstrickland** [comment]
Validated in the original ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/5866.
