### ISSUE TITLE
[CHIP] SPIKE: Determine LOE to Reduce Fields Populated in the LoROTA Entry Upon Creation

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#60103]
## Background
In order to meet the requirements of our ATO, we have been asked to reduce the data that is stored in a LoROTA database entry, when it is created, to the following:
    - IEN
    - Last Name
    - DOB

## Tasks
- [ ] [BE] When a LoROTA entry is created for the first time (i.e. not on refresh), we should only stored the following fields per our ATO:
    - IEN
    - Last Name
    - DOB

## Acceptance Criteria
- [ ] LOE Determined
- [ ] Test in dev environment

**Comment by brianseek** [comment]
In my initial research I don't think it is viable to only have IEN, last name, and DOB. 

Ideally this would work pretty smoothly with last name, DOB, IEN, stationNo, and patientDFN. The LOE would be pretty small.

We could maybe remove patientDFN with a large-ish LOE.

I don't think we can get by at all without knowing the stationNo. 

I'm going to keep digging to understand the LOE for removing patientDFN and using only last, DOB, IEN, and stationNo.

**Comment by brianseek** [comment]
After talking to Stephen in [this thread](https://dsva.slack.com/archives/C052K48SJE6/p1687533892274559) we decided to reduce things down to last name, dob, appointment ien, patient dfn, and station number.

**Comment by brianseek** [comment]
[Ticket to complete work](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/60840)

**Comment by loripusey** [comment]
@brianseek did you actually determine a LOE? I believe @stephenBarrs needs this information before a decision can be made as to whether to prioritize this work.
cc: @anita-halici

**Comment by brianseek** [comment]
@loripusey good point, not sure that I ever quantified what it would be. This would be around a 3 point ticket...but should go through a proper refinement.

What terms do we normally put LOEs in?

**Comment by loripusey** [comment]
I think in terms of number of sprints is a good measure; So a 3-point ticket is half a sprint (+ or -)?

**Comment by brianseek** [comment]
yeah lets call it a half sprint LOE
