### ISSUE TITLE
Vets-api terminal access for Kevin Duensing

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#60105]
### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Kevin Duensing

### Your GitHub handle (terminal access is managed through GitHub)

@kjduensing

### Team, Role, and Company of the target individual

Benefits Management, Backend Developer, Ad Hoc

### Product Manager (PM) name and email

Jacob Worrell - jacob.worrell@adhocteam.us

### Product Owner (PO) name and email

Matthew Self - matthew.self2@va.gov

### Your dsvagovcloud AWS user name (if applicable)

Kevin.Duensing

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### COR Name (leave "None" if you listed an AWS user name above)

None

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

None

### Access Expiration

ongoing

### Additional Notes

I need prod access in order to debug issues that come in from the Contact Center regarding our application(s). It's really hard to debug without inspecting certain things about a claim. Thanks!

### User must exist in a roster before vets-api terminal access can be granted

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added
- [ ] If they included an AWS user name, check to see if their user name is listed in [iam_users.tf](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf)
- [ ] Comment in this issue saying which roster the user is listed in and confirming their AWS user name (if applicable)

**Comment by ryan-mcneil** [comment]
User found on VFS Roster.

@BillChapmanUSDS I found his Transmittal Date via his AWS request and a [comment from Clint Little](https://github.com/department-of-veterans-affairs/va.gov-team/issues/52742#issuecomment-1419701197), so we have approved before

**Comment by ryan-mcneil** [comment]
@kjduensing You’ve been granted access to the `dev`, `staging`, and `sandbox` environments.

Here's some additional documentation for the [Vets API on EKS](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-TerminalAccess)

Access to `prod` is pending approval by OCTODE, and we'll update you as soon as it's available.

**Comment by BillChapmanUSDS** [comment]
access granted for 3 months as per policy.   

We'll need more justification for future access requests. Troubleshooting and debugging should be happening in lower environments and production logs should be appropriately shipped and visible.

**Comment by bdech** [comment]
@kjduensing Per an update to our access policy, your ArgoCD/vets-api Production access has been extended for 3 months, expiring 12/21/23. Please set a reminder for yourself to return to this Issue and re-request access within 1 week of the expiration date. You'll receive 1 reminder with a 72 hour window to respond. Failure to do so will result in lost access and will require you to fill out a new request.

**Comment by bdech** [comment]
slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1695302577593269)

**Comment by bdech** [comment]
@kjduensing Your Vets API Terminal Production access has expired.

Would you like to request an extension? You have 72 hours to respond, or your 
access will be revoked and you will need to fill out a new request.

**Comment by kjduensing** [comment]
Didn't mean to ignore you there @bdech - I'm fine having my prod access removed, thank you.

**Comment by bdech** [comment]
Thank you for the follow up Kevin.
