### ISSUE TITLE
Identity Dashboard (FE) - Move inline SVG to public folder

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#60117]
## Description
Move inline SVG icons and save in the `public` folder

## Tasks
- [ ] Create a folder for images in the public folder
- [ ] Find all inline SVG icons and move to the `public` folder

**Comment by ianmagenta** [comment]
After playing around with this for a bit, I'm going to close this ticket for now. @acald-creator's current solution for the icons solves this the most elegantly. While the svg paths are still present in the icons.js file of the Sidebar component, this is actually the structure that Chakra recommends for using custom icons with its Icon component.
