### ISSUE TITLE
[Research] 10-10EZ - EZR: Conduct Pittsburgh EZR Call

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#60126]
As a team member, I would like to better understand how Veterans use the 10-10EZR paper form so that I can make a good digital experience for those want to update their information online. 

**AS: Separate story for call prep**
- Figure out what the Pittsburgh call attendees do
- Conduct call with Pittsburgh 
- Do a synthesis--can be informal, here's what we learned, here's what we still wonder, here's what we want to test with Veterans 
- **AS Note: Based on feedback from Kristen today (6/20), review staff research report examples Kristen will send and fill it out and send it to her**

**Comment by jessicastump** [comment]
Here are the [notes from this call](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/EZ(R)%20Update%20Capabilities/Meeting%20Notes/2023-06-16%20EZR_Reg%20Only%20-%20Pittsburgh%20VAMC%20Conversation.md).
