### ISSUE TITLE
SOCKS access for [Brandon Dech]

### ISSUE THREAD

**Issue by bdech** [department-of-veterans-affairs/va.gov-team#60129]
### Your Name

Brandon Dech

### Your Email

brandon.dech@oddball.io

### Your Role and Team

Support Specialist - The Platform

### Product Manager (PM) name and email

Alyssa Gallion, alyssa.gallion@oddball.io

### Product Owner (PO) name and email

Bill Chapman, william.w.chapman@omb.eop.gov

### Access Type Requesting

platform

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDE9EkT8MlMWg/ROHJdM8eeQEymXlYPN1aX7OdYWplZK7XNE/l0eABvuEaEaIZtb/3HGZ0wEIEZToELofCBllS6/5la57L07sy33vVwPzcFMSRbyKDlCClzWz5R43BzUpp/1m4ny9Dae+xjlyTru/F9Y2TztlQapQAhPdjh32XbtGjH+CVKU2iBMURb1w9CAIpgznMFYANLHOlhq+IZF8bIuP2Tw+o3fZMbQDkrmYaD6TG0jMau9RTmm5x4lP+Fh7hjOehkdZ/1bD0bwGglLhzr9l73/vPL0RbaWpiQABKhe8clinwuMLDSNPbLSL8mrcYv2exzLhAWMO8CCHaNG5Rgew5et7vB//Xs+v71insfA1N5Y+8I97DcGxVVFZ147NmpfPmetdiGv758pUcs85vxYVzl61jXFHMFRcepYzI0ihGu3qb7C7+3D0UixyYQvi0KobO3Oz6r4vM5Wo2T41HDo70euv1UFThV9aPR4fysFSdJ8cSHKqBpXgLNxMK1QcU= brandondech@LenovoWork

### E-QIP Transmittal Confirmation

<img width="638" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/135037265/47e7f6a0-66df-4414-a4bc-7868b3e17f00">

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by rmtolmach** [comment]
you should be good to go (in 5 min!)

**Comment by rmtolmach** [comment]
You should be good now, Brandon! run `vtk socks setup` again
