### ISSUE TITLE
[BE, FE, Data] 10-10CG - Performance Monitoring: Sprintly review on Datadog and/or other log applications

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#60128]
## Background
As a result of a possible issue being reported to us, we found that a regular cadence of performance monitoring review is needed to maintain the application and allow for early discovery of potential issues.
We will have a ticket for every sprint to account for this review.

Possible issue reported that uncovered our need for a regular review from Adrian Rollet:
>just want to surface a possible UX issue I happened across while looking for something else in RUM
>
>There are a lot of dead clicks on the H1 https://vagov.ddog-gov.com/dash/integration/rum_frustration_signals_browser_and_mobile[…]10-10EZ&from_ts=1685973570507&to_ts=1686578370507&live=true
>
>my guess, and it seems to be backed up by [session replays](https://vagov.ddog-gov.com/rum/replay/sessions/6b99c7ab-febe-4aa6-a3ea-759dd60e85d8?highlightedEventId=AgAAAYiuExropy89ewAAAAAAAAAYAAAAAEFZaXVFekgtQUFBNW1mSVpFdzc4TlFBTgAAACQAAAAAMDE4OGFlOTUtMzJiNi00NDg0LTk0MDMtNmI4Mzc0YzU5MjNi&seed=4dfd9ee4-f4aa-428c-ad51-967e8d07486f&ts=1686547667688&from=1686547666280), is that on slow devices/connections, the application spinner isn't showing for some amount of time after the H1 loads in, leading users to think that "Apply for VA Health Care" is the action to click on.
>And when I say a lot, it looks like over 1k in the past week.

## Tasks
- [x] Review Datadog (including RUM) for any performance issues during the last sprint to current day
     - Looking for  anything that would indicate system performance or user experience degradation 
- [x] Review Sentry, Grafana and other logging applications we use to check for performance or user issues

## Acceptance Criteria
- Performance and User Experience is monitored on a sprint-ly basis and any issues found are shared with the team for review and solution (if needed)

**Comment by luis-simauchi** [comment]
reviewed the events explorer in DATADOG, no glaring errors for found for this sprint cycle.

**Comment by luis-simauchi** [comment]
To elaborate... a few error messages were found, but these errors do not seem to be session breaking. examples:
