### ISSUE TITLE
Remaining GH Actions

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#60125]
**Problem**
If a GH action fails, the deploy still goes out.
Needs to be blocked.

For the time being, you can't create blocking (separate) workflows for Github Actions if not in the master branch. As a temporary solution, the k8s branch GHA's will be moved into the same workflow (as separate jobs). This way, we can create jobs that are dependent on the success of one another. e.g. The image build and push are dependent upon successful linting and test runs.

**Comment by LindseySaari** [comment]
I'm working on making the test and linting jobs blocking if either fail.

**Comment by LindseySaari** [comment]
The tests and linting actions are now blocking the ECR build and image tag update actions. Tests are successful.
