### ISSUE TITLE
[Research] 10-10EZ - EZR: Conduct EZR call with Martinsburg VAMC

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#60130]
## User Story
As a team member, I would like to better understand how Veterans use the 10-10EZR paper form so that I can make a good digital experience for those want to update their information online. 

## Resources
- [Initial Meeting Notes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/EZ(R)%20Update%20Capabilities/Meeting%20Notes/2023-6-12%20Mtg%20with%20Shawn%20Lawson.md) with Shawn Lawson
- **AS: [Separate story for call prep](https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/59891)**

## Tasks
- Figure out what the Matrinsburg call attendees do
- Conduct call with Matrinsburg
- Do a synthesis--can be informal, here's what we learned, here's what we still wonder, here's what we want to test with Veterans 
- - **AS Note: Based on feedback from Kristen today (6/20), review staff research report examples Kristen will send and fill it out and send it to her**

**Comment by jessicastump** [comment]
[Link to meeting notes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Registration/Meeting%20Notes/2023-06-22%20-%20EZR_Reg%20Only%20-%20Martinsburg%20VAMC%20conversation.md) from 6/22/23.

**Comment by katelyncai** [comment]
I missed Jessica's comment and [added meeting notes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/EZ(R)%20Update%20Capabilities/Meeting%20Notes/2023-06-22%20Martinsburg%20Frontline%20Staff%20Convo) in another place that [Hieu had linked me to](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/application/va-application/EZ(R)%20Update%20Capabilities/Meeting%20Notes). I'm not sure why we have meeting notes in two places. I added synthesis for the 6/22/23 conversation to my new page — @hdjustice would you determine which spot is best for the notes and I'll make sure synthesis is there. After that, this ticket is ready to be closed!

**Comment by hdjustice** [comment]
@katelyncai - I actually think we should put the synthesis in the [research folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/application/va-application/research/2023-06-Staff%20facing%20EZR%20and%20Reg%20Only%20research).  
The meeting notes folders are just that, but the synthesis is more structured toward findings, which I think should live in research.

**Comment by katelyncai** [comment]
Added synthesis to research folder's meeting notes.
