### ISSUE TITLE
SOCKS access for Evan Smith

### ISSUE THREAD

**Issue by evansmith** [department-of-veterans-affairs/va.gov-team#60132]
### Your Name

Evan Smith

### Your Email

evan.smith@oddball.io

### Your Role and Team

Software Engineer - Benefits and Claims

### Product Manager (PM) name and email

Austin Price austin.price@coforma.io

### Product Owner (PO) name and email

Matt Self Matthew.Self2@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDabtFAYNzxPRAp0/WPZnV+mXT5yG8SBe+buRfgQd7KucnAfien74LvjglJbuoNYUZiWOR+t8KzDTiy/zjakioyJnMYYpnJO/ZNU7o+rUy/6C9QJFGPZ6AUfQNX87nJzc3Rd0iyIiTk7ARMvpnfmOvdBsDG33QDTxg0sXlEjweRcnfIh5RqeyaMhXyzoiAXYIinkgpENNqiaiMe1t0Xl8Q44x/abY+QkF9M+x597ZY6kd6T9LYC13mTH261pZzcX3eL4xK6zrGq5HyJwCYTf3OEYxnGjZRcPNc5yQbGeV0rSA08lf1V+sbSZQ8qOOoldd7KWnoX48h81g1O/5352v6tdwWL1b2BdBn9eAyyOXpPycWHwI/Jw5ViKzLiPRxsmfRGIrwYJuKrzaStqPWcQx/d1VlRQrwowv9OfEYgog63ClGM5c0Q58/nnKCpro1FZ6jne3U4iyIDR2GAuwTMRSSiAEakFUuKgVZqENfR6mSHDXERodKdvW37J1krw5aNLXk= esmith@Evans-MBP.lan

### E-QIP Transmittal Confirmation

![Screenshot 2023-06-12 at 11 42 26 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/1820743/0c139a72-389d-4e8d-adec-7d061701befb)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by rmtolmach** [comment]
You have been granted access. see docs for more info: https://depo-platform-documentation.scrollhelp.site/getting-started/accessing-internal-tools-via-socks-proxy
