### ISSUE TITLE
EZ Registration Only Path - Keyword Research for Site

### ISSUE THREAD

**Issue by luis-simauchi** [department-of-veterans-affairs/va.gov-team#60131]
I as an analyst want to learn how veteran is thinking about the process of applying for benefits or registration for services. 

Some research questions to answer:
What search terms are veterans using to navigate to medical benefits forms or other registration benefits? 
How often is a version of "enroll" or "register" or "eligible" used by site visitors? 
Where do they go post keyword search?

**Comment by hdjustice** [comment]
Closed - work completed on another ticket
