### ISSUE TITLE
Suggested addition to Unit test documentation 

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#60153]
# Description

I think it would be extremely helpful to frontend developers to have documentation on the unit testing environment and how to avoid writing flaky tests. A suggested starting point:

### Background

The most important thing to understand about the writing tests for VA.gov applications is that Mocha does not run individual tests in isolation. This means that any test you write can affect any other test, and any other test can affect your test.

#### Global variables

Be sure that you restore any modified globals (such as `navigator`) to their original state in an `after` or `afterEach` hook.

#### Node.js require caching

If you `require()` a file in one unit test and modify the required object, those modifications will be preserved in other unit tests, even when you require the same file again! Ways to avoid this problem:

* don't `require()` the same file twice (e.g. use separate fixture files)
* [invalidate the require cache](https://stackoverflow.com/questions/9210542/node-js-require-cache-possible-to-invalidate) once your test is complete

## How to debug flaky unit tests

Unit tests are run in a different order each time tests are run locally or in CI. To re-run tests in the same order, use the same `CHOMA_SEED` value. You will see output in the CI logs similar to the following:

```
choma: to re-use this ordering, run tests with CHOMA_SEED=JAM0CXhqeC
```

You can then re-run tests in the same order with:

```
CHOMA_SEED=JAM0CXhqeC yarn test:unit --log-level=error
```

Note that it's important to run the entire test suite to catch issues caused by tests from other applications. If the issue is test order dependent, you should see the same failure. To speed testing cycles, you may also include the paths to specific unit test files to avoid having to run the entire test suite once you've determined which files are in conflict.

## Relevant URLs

Documentation: https://depo-platform-documentation.scrollhelp.site/developer-docs/unit-tests
Discussion in frontend CoP channel: https://dsva.slack.com/archives/C04868KS69L/p1686585167635789

## Which type of team are you on? (Platform team, VFS team, or Leadership)

VA engineering.

**Comment by brianseek** [comment]
I would also note that when using the CHOMA order, that you should run all of the tests to see the same error locally. Sometimes in the directory context they will pass with the CHOMA because the previous tests were excluded.

**Comment by acrollet** [comment]
Thanks @brianseek , good callout - I updated above.

**Comment by vbellissimo** [comment]
Hi @acrollet This content has officially deployed on [this page](https://depo-platform-documentation.scrollhelp.site/developer-docs/debugging-unit-tests). We will close this ticket now. Thanks!
