### ISSUE TITLE
Update content and links for Yellow Ribbon MVP

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#6016]
## User Story or Problem Statement

How might we clearly provide relevant eligibility and next step information to Veterans interested in Yellow Ribbon benefits?

## Goal

- Provide access to Yellow Ribbon school finder in benefit hub
- Make it clear to users that they need to apply for Post-9/11 GI Bill benefits to receive Yellow Ribbon benefits
- Provide easy access to Post-9/11 GI Bill benefit eligibility information
- Provide easy access to the Post-9/11 GI Bill application

## Acceptance Criteria

- [ ] Update the [Yellow Ribbon hub page](https://www.va.gov/education/about-gi-bill-benefits/post-9-11/yellow-ribbon-program/) to include links to the **Find Yellow Ribbon schools** tool.  
  - We may need to restructure the page, or add content, so that users have enough information to determine which is the best tool to complete their task.
  - Mock-up with some suggestions [available here](https://vsateams.invisionapp.com/share/K5W2BOA34ZH)
- [ ] The new YR school finder tool will live within the Education benefits hub and be linked to from the "More resources" spoke.  (See [IA Structure recommendations](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/websites-yellow-ribbon.md#ia-structure-urls-and-breadcrumbs-))
- [ ] **Hub page** add a link and teaser text under the "More information and resources" spoke of the [Education benefits hub page](https://www.va.gov/education/) (see [Navigation/Entry point recommendations](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/websites-yellow-ribbon.md#navigationentry-points-))
  - The option should be the 2nd option in the list, just below the GI Bill Comparison tool option
  - Determine the link label and teaser text.
- [ ] **Left Nav** Add a link to the Education hub left nav under the "More resources" spoke  (see [Navigation/Entry point recommendations](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/websites-yellow-ribbon.md#navigationentry-points-))
  - The option should be the 2nd option in the list, just below the GI Bill Comparison tool option
  - Finalize the link label, suggestion "Yellow Ribbon participating schools"
- [ ] Consider adding a link to our tool to the right rail of the GI Bill Comparison tool: https://www.va.gov/gi-bill-comparison-tool
- [ ] Add copy to [our MVP landing page](https://vsateams.invisionapp.com/share/P4W04QPWHTK#/405236720_Landing) so that 
  - users understand Yellow Ribbon benefits are directly related to their Post-9/11 GI Bill benefits, and
  - give them access to apply for the benefit, and
  - Give them access to eligibility criteria (this might be covered by the link already on the page pointing back to the hub page)
- [ ] Add copy and links under the h1 to [our MVP search results cards](https://vsateams.invisionapp.com/share/P4W04QPWHTK#/screens/405289243) so that 
   - users have access to access to apply for the benefit, and
  - have access to eligibility criteria (this might be covered by the link already on the page pointing back to the hub page)
- [ ] @jenniferlee-dsva please review this issue and ensure we've correctly identified all content areas needing content attention

**Comment by andaleliz** [comment]
@AnneHurley I believe this to be a comprehensive list of all the YR content needs, including executing the IA recommendations provided by Mikki [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/websites-yellow-ribbon.md) .  I'm not sure if those are your responsibility or something our devs (or someone else?) would work on.  Please feel free to move those tasks to another issue if they're not yours to complete.

I also tagged @jenniferlee-dsva here just to ensure this plan makes sense to her, now that we have Mikki's IA recommendations in. Jen, I left a checkbox for you to check off once you're reviewed :)

**Comment by andaleliz** [comment]
Also, @AnneHurley I'll put this in the milestone for our current sprint, but please change if you don't have bandwidth to complete before that ends.

**Comment by MickinSahni** [comment]
2020-02-20 PW Standup
- Anticipating being able to complete this story in this sprint. Moving into Sprint 15/Current Sprint as a result

**Comment by AnneHurley** [comment]
[Yellow Ribbon school finder copy v1]
(https://github.com/department-of-veterans-affairs/va.gov-team/files/4232865/Yellow.Ribbon.school.finder.copy.docx)
@andaleliz  @jenniferlee-dsva  @mnorthuis  This doc contains all the different YR pieces of copy listed above. One thing I think we should clarify is whether we should use "Yellow Ribbon participating schools" as our left nav copy if we are using Yellow Ribbon Program comparison tool for most / all other references. thx!

**Comment by andaleliz** [comment]
@AnneHurley Thanks for this! I'm not clear on if I need to provide mock-ups for all the updates to existing pages.  Are those content updates you make in Drupal, or that our developers need to do?

Your question for #3- yes, I think that is a duplicate of #2- my bad!

Also, for #7 in your document, I think there was some confusion.  In the cards, we are sticking with the `Get Started` recommendation and single URL to the school website.  But, under the `h1` we need to include the links that Jen asked for yesterday (GIB eligibility and application), and probably some copy to give them context.  So, the bullet is still accurate and we'll need that content.

**Comment by AnneHurley** [comment]
@andaleliz  Copy updates we discussed, attached.

**Comment by MickinSahni** [comment]
- Should be wrapped up by end of sprint

**Comment by AnneHurley** [comment]
[YR MVP content updates v3]
(https://app.zenhub.com/files/133843125/8c59b9f1-a644-4356-821b-d04247e81755/download)
@andaleliz Updated and ready for you.

**Comment by andaleliz** [comment]
@AnneHurley Thank you! I think we are good between this and the comments you put in InVision.  [Here is the latest version of the prototype](https://vsateams.invisionapp.com/share/P4W04QPWHTK) if you'd like to review and be sure everything lines up.  The first 3 screens are our MVP; the next 5 reflect the IA recommendations @mnorthuis made. Also, cc to you Mikki, in case you want to check them out. 

Anne, to answer your comments in the doc:

- No problem for the additional copy to push the fields a little further down on the MVP landing page
- You left a comment regarding the `h1` (below).  The `h1` as you see it on the MVP currently (lowercase s) is how Peggy suggested we word it.

> Style q – thinking that “Find a Yellow Ribbon School Tool” would have school and tool capped as part of the name of the tool, but that “Find a Yellow Ribbon school” would not have capped S.

**Comment by AkucherGCIO** [comment]
02-24-20 PW Standup
Closing this issue since its been implemented.
