### ISSUE TITLE
Determine if engineers have access to test FHIR API in any environment

### ISSUE THREAD

**Issue by MarciMcGuire** [department-of-veterans-affairs/va.gov-team#60162]
In order to integrate Cerner data into MHV medications application on VA.gov, we need to know if engineers currently have access to test FHIR API in any of our environments.  Adrian is working with Angela Chen on this.

**Comment by carlosfelix2** [comment]
There is no access at the moment to connect to B1930, however, we have a Smart App utility in PowerChart to play with FHIR API GET requests. We are able to get data for specific patient encounters in either DSTU2 or R4 versions of the API. Note that the default requests made by the app is DSTU, but one can make requests to the R4 version in the short amount of time the tokens are valid. HINT: close and reload a patient encounter to reset the token.
