### ISSUE TITLE
[ISSUE] EVSS 15006 errors/file corrupted

### ISSUE THREAD

**Issue by va-albers** [department-of-veterans-affairs/va.gov-team#60165]
# Instructions
Please fill out the form below, providing as much detail as possible. 

## Issue Description <br>

EVSS:DisabilityCompensationForm::SubmitUploads getting back corrupt file messages (EVSS_15006), appears to be continuing to retry:
[{"key"=>"EVSS_15006", "text"=>"We were unable to complete your upload because the uploaded file is corrupted and cannot be uploaded. Please verify that the file is valid. If you still have problems, call the VA  at 1-800-827-1000 (711, if you use a TDD) for assistance. When you call, provide the following error code: EVSS_15006.", "severity"=>"ERROR"}]

### Information needed to assess the severity of the issue
- Users Impacted:     Few
- Issue Impact:       Potential loss of uploaded application or supporting documentation file from veteran.  Not clear if there is any notification, submitter notification or after-action process for this case.
- Workaround:         We have to identify if this upload is lost entirely or if there is a workaround (is there a notification?)  
- Legal Requirement:  Unsure
- Loss of Service:    Unsure
- Permanent Impact:   Unsure if the file upload is entirely lost in this case.
- Vulnerability:      No

### Information that aids in the research and troubleshooting of the issue
- Date and Time of Issue:     Ongoing issue
- Form/Page of Issue:          check Sentry or Datadog APM traces for EVSS_15006 errors
- Error Message:              [{"key"=>"EVSS_15006", "text"=>"We were unable to complete your upload because the uploaded file is corrupted and cannot be uploaded. Please verify that the file is valid. If you still have problems, call the VA  at 1-800-827-1000 (711, if you use a TDD) for assistance. When you call, provide the following error code: EVSS_15006.", "severity"=>"ERROR"}]
- How to reproduce:           
- Unique IDs:                 
- Application ID:             
- Hardware Issue Observed On: 
- Browser type / version: N/A
- Case#, if available: 
- Reporter name in va.gov:

**Comment by tblackwe** [comment]
The error looks pretty clear from the backend. a user attempted to upload a file that was corrupted in some way. The only thing we could do is check for file corruption prior to submitting it to EVSS but we would need to understand what rules they were looking for. 

Recommend closing as `Won't FIx`

**Comment by RakshindaAslam** [comment]
@va-albers - please review comment above.
cc @tblackwe

**Comment by tblackwe** [comment]
Good point Rakshinda, we should make sure the front end is appropriately alerting on this and not allowing Vet to believe it was successful

**Comment by RakshindaAslam** [comment]
Next steps
   - Are these getting picked up in the workaround? 
   - Investigate if the claim is getting submitted without the file
   - Confirm if the file is corrupted in these cases
   - Can we notify veteran that the evidence did not get attached to the claim
   - Do not retry if corrupt
   
Action - Moving back to In Assessment for more investigation and some proposals

**Comment by RakshindaAslam** [comment]
Complete this for assessment 
- Are these getting picked up in the workaround?
Investigate if the claim is getting submitted without the file

**Comment by tblackwe** [comment]
@NB28VT This is related to the #60157 issue you are currently researching. Thoughts on working both at same time?

**Comment by NB28VT** [comment]
> @NB28VT This is related to the #60157 issue you are currently researching. Thoughts on working both at same time?

This will be a separate fix but it is adjacent to the wider problem of EVSS upload errors, I've referenced this [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60157#issuecomment-1655990202) in the other ticket.

One potential course of action here @austinjprice @tblackwe is an epic where we:
1. Learn how to gather data on the frequency of these three EVSS upload error types and what percentage of total uploads they are failing (DataDog).
2. Address them in separate fixes that are done back to back
3. Monitor and document the frequency of these errors/successful uploads once the fixes go live.
4. Have a clear "before and after" story to tell around greatly improving submissions that are held up because of these problems.
