### ISSUE TITLE
Execution: Reconfigure Platform Support Bot - Topic Before Assignment

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#60172]
**Description**
User types '/support' into the Platform Support Bot and complete list of assignable Topics appears first. Once Topic is selected, user can then choose to specify Assignment.

**Definition of Done**

- Platform Support Bot functions easily with new change

**List of Tasks to Complete**

- [ ] Propose changes and get approval from Clint Little and Andrea Hewitt
- [ ] contact Curt Bonade, FE CoP to schedule work
- [ ] Test changes for completion
- [ ] Test useability for 1 week in Slack #vfs-platform-support Slack channel

**Documentation**
https://github.com/department-of-veterans-affairs/platform-support-slackbot

**Comment by alyssagallion** [comment]
All support bot changes are going to be done in this EPIC: https://app.zenhub.com/workspaces/platform-tech-team-support-634ebbcc35e2bc0015b382fd/issues/gh/department-of-veterans-affairs/va.gov-team/61279

Closing.
