### ISSUE TITLE
Facility type labels on Facility Detail pages

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#6017]
## What happened?
During Urgent Care MVP implementation, (non-urgent) Community Care facilities were briefly labeled _Community Care (Non-VA Health)_. The label was then changed to _Community providers (in VA’s network)_ The label change did not carry over to Community Care Facility Detail pages.

![ccare facility type label.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/55257792-9794-45ff-aa0d-4cdf598c443e)

note: the missing Facility name in the screenshot above is handled in a separate issue. 

## Specs:
- Browser: Chrome

## Steps to Reproduce
- URL: https://www.va.gov/find-locations/provider/ccp_1356574321
Enter location parameters, Choose Facility Type = Community providers (in VA’s network) and any Service type (Podiatry, Foot and Ankle Surgery, for example)
Click on facility/provider name in the search results list to be taken to the facility detail page
Note the Facility type is displayed as _Community Care (Non-VA Health)_

## Desired behavior
Facility Detail pages for Community care providers (non-urgent care, non-pharmacies) should display the Facility Type as _Community providers (in VA’s network)_ 

## Acceptance Criteria
[ ] Given the facility type in the search = VA health, when user selects a search result to view the Facility Detail page, then the facility type is shown as VA health.
[ ] Given the facility type in the search = Community providers (in VA’s network), when user selects a search result to view the Facility Detail page, then the facility type is shown as Community providers (in VA’s network).

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by mpelzsherman** [comment]
Shouldn't it be "provider" (singular), since the label applies to one (1) provider?

**Comment by davidconlon** [comment]
Facility Detail pages for Community Care providers are going away.
This issue is obsolete.
