### ISSUE TITLE
AWS access for Rockwell Rice

### ISSUE THREAD

**Issue by rockwellwindsor-va** [department-of-veterans-affairs/va.gov-team#60180]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Rockwell Rice

### Your Email

rockwell.rice@oddball.io

### Team, Role, and Company of the target individual

Software Engineer II, Dash, Oddball

### Product Manager (PM) name and email

Kayla Watanabe, kayla.watanabe@adhocteam.us

### Product Owner (PO) name and email

Janet Coutinho, janet.coutinho@va.gov

### Desired AWS Access

lighthouse developers IAM

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

<img width="1049" alt="Screenshot 2023-06-07 at 3 48 35 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/129893414/7ddc2634-6c58-4130-a68e-724d194af2f0">

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by rockwellwindsor-va** [comment]
You can find me on the VFS Roster from the list above.

**Comment by bdech** [comment]
Found in VFS Team Roster

**Comment by rockwellwindsor-va** [comment]
Looks like the "awaiting approval" badge has been removed.

Thanks everyone for the help!

**Comment by rockwellwindsor-va** [comment]
Sounds like I still need "dvp-developers" added.

**Comment by flooose** [comment]
@BillChapmanUSDS I'm reopening this because 

1. I just saw [this comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60180#issuecomment-1618758125) and I'm not sure I understand it
2. Rockwell additionally needs approval for "dvp-developers"

**Comment by FonzMP** [comment]
@flooose - To provide some additional details, looks like Rockwell was having issues accessing Param Store and some other items in AWS that we use. When I started comparing, seems like he's missing the above (dvp-developers) from his groups. If you'd like to refer to Rockwell's teammates, feel free to peruse Alex.Wilson (myself), Matthew.Christianson and Jennica.Stiehl in the terraform. 

I don't know if this is a "sub-group" of the lighthouse role that should have been attached or if there's an additional IAM role we need to request in future issues to receive this group, but please do let us know so we can update / correct any onboarding lists we have to save both of us the headache. 

Thanks for your help on this!

**Comment by FonzMP** [comment]
@flooose are we still waiting on approval? curious what steps we can assist with from our end. Seems like it is taking an extremely long time to get Rockwell onboarded, and onboarded correctly.

Unfortunately we're fairly dependent on AWS in our day to day so curious if there is anything we can do to help speed up the process?

**Comment by flooose** [comment]
@FonzMP it's not taking an extremely long time. Our work has a weekly cadence and flow and we simply haven't prioritized this above that. I had open questions for Bill and it's all documented above. It is always possible to expedite things, but we don't do that automatically. You can consider this expedited.

@BillChapmanUSDS since the additional need for "dvp-developers" is consistent with the other developers on the team and seems to be an "implementation detail", I've [prepared a PR](https://github.com/department-of-veterans-affairs/devops/pull/13246).

I'm still curious about [this comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60180#issuecomment-1618758125) though, because it seems to indicate that we shouldn't have anything to do with managing access to lighthouse resources, which doesn't seem to be the case in our terraforms :)

**Comment by BillChapmanUSDS** [comment]
@flooose I personally only gatekeep access to platform / vets-api AWS resources.  I had read this as a request for access to LHDI resources.  I may have be mistaken but this is the first time I've noticed a request for "lighthouse developers IAM". I'll ping you in slack to sort this one out.

**Comment by BillChapmanUSDS** [comment]
It's not clear to me what access is being requested here but as per the latest policy adjustment's if  @rockwellwindsor-va  can provide an example of a task they would like to perform on a production environment that cannot be done or is too cumbersome to do in lower environments or through another mechanism (logs are in datadog etc..) than you can grant 6 month expiring access and add the access-justification-example-provided tag. In absense of that detail you can allow 3 months expiring access.

**Comment by rockwellwindsor-va** [comment]
Looks like the "awaiting approval" badge has been removed @flooose @Kshitiz-devops

Thanks everyone for all the help on this!

**Comment by flooose** [comment]
oh, sorry, yeah, your additional access has also [been given](https://github.com/department-of-veterans-affairs/devops/pull/13246) :)

**Comment by rockwellwindsor-va** [comment]
Apologies to bring this back to life.  A little confused on why I still cannot view EC2, S3 or Parameter Store?  These are the resources my team utilizes often, some like EC2 daily.  It does appear we have the exact same `group_memberships` but the update appeared to be from last week so perhaps it did not update yet?

<img width="1384" alt="Screenshot 2023-08-02 at 4 13 10 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/129893414/32b969e6-6845-480b-97b0-74320ee7e1d2">

<img width="1023" alt="Screenshot 2023-08-02 at 4 18 02 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/129893414/cca89f92-a7c7-4f26-ae21-53387574c7a7">

<img width="1161" alt="Screenshot 2023-08-02 at 4 19 27 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/129893414/8404724d-7d62-4d7e-931f-9ddd06e18f50">

**Comment by flooose** [comment]
It seems, you haven't enabled MFA, can you try that?

https://depo-platform-documentation.scrollhelp.site/developer-docs/Setup-your-AWS-Account.1886781475.html

**Comment by rockwellwindsor-va** [comment]
@floose 100% right, my apologies for missing that step.  Thank you _**SO**_ much for all your help here with this, got in and verified.

**Comment by flooose** [comment]
No Problem. I'm glad we finally got this through. Sorry about all the delays :)
