### ISSUE TITLE
[Spike] - Review Data Fields from Cerner

### ISSUE THREAD

**Issue by JRRoof** [department-of-veterans-affairs/va.gov-team#60191]
## Background/Request
The VAOS service will soon be returning appointment data from Cerner.  The VAOS service will be retrieving the data via a new service called CS PRO (Cerner Scheduling Provider Read Only).  The following link outlines the data mapping between Cerner and VAOS.

https://coderepo.mobilehealth.va.gov/projects/EAS/repos/mobile-appointment-service/browse/mobile-appointment-service/src/main/java/gov/va/mobile/appointment/v2/data/mappers/CernerMapper.java?at=b2f4a695b0887db176a7e7b22d6f7a2b63cff80d

### Goal
Review the data mapping and compare the fields being returned from Cerner to the fields we currently receive from VistA and note any missing or inconsistent fields.

### Requirements to Consider

---

## Tasks
- Answer the following questions:
  - Q - Are there any fields that we require that are not being returned from Cerner?
  - Q - Are there any additional fields being returned that need to be included in our UI?
  - Q - Are there any fields that will need to be modified to accommodate the Cerner data format?

## Time Box
8 hours

## Definition of Done
- Tasks are complete
- Research and recommendations are documented in this ticket

---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by ajmagdub** [comment]
I reviewed the Cerner appointment data field by referring to the current [VAOS Service swagger doc](https://coderepo.mobilehealth.va.gov/projects/VAR/repos/vaos-service/browse/vaos-service/src/main/resources/swagger.json), the
[CernerMapper.java](https://coderepo.mobilehealth.va.gov/projects/EAS/repos/mobile-appointment-service/browse/mobile-appointment-service/src/main/java/gov/va/mobile/appointment/v2/data/mappers/CernerMapper.java?at=b2f4a695b0887db176a7e7b22d6f7a2b63cff80d) file in the Mobile Appointment Service, and the Cerner Millennium FHIR R4 appointment
documentation. By starting with the VAOS Service swagger as the base, I examined the mapping in the
CernerMapper.java to determine the fields that were actually mapped. Additionally, I consulted the [Cerner
FHIR R4](https://fhir.cerner.com/millennium/r4/base/workflow/appointment/) appointment documentation to explore any additional information that may be available.
 
The mapping from Cerner FHIR appointment to VAOS Service appointment is shown in the table below. There are no
significant gaps, so there is no need for a major rewrite of the Vets API code. However, it appears that the
current locationId field is not being mapped and instead a facilityId field is being returned. Additionally, the
clinic field is also not mapped. Both of these fields are used by the Vets API to retrieve the service
name/friendly name and physical location of the appointments.

No other fields from the Cerner FHIR R4 appointment specification are currently needed. However, there is an
"is-reschedulable" field that could be useful in the future if there is a need to implement rescheduling.

Web developers should review the mappings for any potential user interface issues. 

|VAOS Service appointment|Cerner| Notes |
|----|------|------|
|id| mapped | |
|identifier[<br>&emsp;{<br>&emsp;&emsp;system<br>&emsp;&emsp;value<br>&emsp;}<br>]| mapped | |
|kind| mapped | |
|status| mapped | |
|serviceTypes: [<br>&emsp;{<br>&emsp;&emsp;coding [<br>&emsp;&emsp;&emsp;&emsp;{<br>&emsp;&emsp;&emsp;&emsp;&emsp;system<br>&emsp;&emsp;&emsp;&emsp;&emsp;code<br>&emsp;&emsp;&emsp;&emsp;&emsp;display<br>&emsp;&emsp;&emsp;&emsp;}<br>&emsp;&emsp;]<br>&emsp;&emsp;text<br>&emsp;}<br>]| mapped | |
|serviceCategory [<br>&emsp;{<br>&emsp;&emsp;coding [<br>&emsp;&emsp;&emsp;&emsp;{<br>&emsp;&emsp;&emsp;&emsp;&emsp;system<br>&emsp;&emsp;&emsp;&emsp;&emsp;code<br>&emsp;&emsp;&emsp;&emsp;&emsp;display<br>&emsp;&emsp;&emsp;&emsp;}<br>&emsp;&emsp;]<br>&emsp;&emsp;text<br>&emsp;}<br>]| not mapped | |
|reasonCode: {<br>&emsp;&emsp;coding [<br>&emsp;&emsp;&emsp;&emsp;{<br>&emsp;&emsp;&emsp;&emsp;&emsp;system<br>&emsp;&emsp;&emsp;&emsp;&emsp;code<br>&emsp;&emsp;&emsp;&emsp;&emsp;display<br>&emsp;&emsp;&emsp;&emsp;}<br>&emsp;&emsp;]<br>&emsp;&emsp;text<br>&emsp;}| mapped | |
|description| mapped | |
|priority| not mapped | |
|patientIcn| mapped | |
|locationId| not mapped | locationId is not mapped but<br>a facilityId is being mapped/returned.<br>There is no facilityId in the VAOS Service swagger doc |
|clinic| not mapped | |
|practitioners [<br>&emsp;{<br>&emsp;&emsp;identifier [<br>&emsp;&emsp;&emsp;{<br>&emsp;&emsp;&emsp;&emsp;system<br>&emsp;&emsp;&emsp;&emsp;value<br>&emsp;&emsp;&emsp;}<br>&emsp;&emsp;]<br>&emsp;&emsp;name {<br>&emsp;&emsp;&emsp;family<br>&emsp;&emsp;&emsp;given [ ]<br>&emsp;&emsp;}<br>&emsp;&emsp;address {<br>&emsp;&emsp;&emsp;type<br>&emsp;&emsp;&emsp;line [ ]<br>&emsp;&emsp;&emsp;city<br>&emsp;&emsp;&emsp;state<br>&emsp;&emsp;&emsp;postalCode<br>&emsp;&emsp;&emsp;country<br>&emsp;&emsp;&emsp;text<br>&emsp;&emsp;}<br>&emsp;}<br>] | mapped | only name is mapped/returned |
|start| mapped | |
|end| mapped | |
|minutesDuration| mapped | |
|slot {<br>&emsp;id<br>&emsp;start<br>&emsp;end<br>}| not mapped | |
|created| not mapped | |
|requestedPeriods [<br>&emsp;{<br>&emsp;&emsp;start<br>&emsp;&emsp;end<br>&emsp;}<br>]| mapped | |
|contact {<br>&emsp;telecom [<br>&emsp;&emsp;{<br>&emsp;&emsp;&emsp;type<br>&emsp;&emsp;&emsp;value<br>&emsp;&emsp;}<br>&emsp;]<br>}| not mapped | |
|preferredTimesForPhoneCall [ ]| not mapped | |
|preferredLocation {<br>&emsp;city<br>&emsp;state<br>}| not mapped | |
|cancelationReason {<br>&emsp;coding [<br>&emsp;&emsp;{<br>&emsp;&emsp;&emsp;system<br>&emsp;&emsp;&emsp;code<br>&emsp;&emsp;&emsp;display<br>&emsp;&emsp;}<br>&emsp;]<br>&emsp;text<br>}| mapped | |
|comment| mapped | |
|preferredLanguage| not mapped | |
|cancellable| mapped| always returns false |
|patientInstruction| mapped | |
|telehealth{<br>&emsp;url<br>&emsp;atlas {<br>&emsp;&emsp;siteCode<br>&emsp;&emsp;confirmationCode<br>&emsp;&emsp;address {<br>&emsp;&emsp;&emsp;streetAddress<br>&emsp;&emsp;&emsp;city<br>&emsp;&emsp;&emsp;state<br>&emsp;&emsp;&emsp;zipCode<br>&emsp;&emsp;&emsp;country<br>&emsp;&emsp;&emsp;latitutde<br>&emsp;&emsp;&emsp;longitude<br>&emsp;&emsp;&emsp;additionalDetails<br>&emsp;&emsp;}<br>&emsp;}<br>&emsp;group<br>&emsp;vvsKind<br>}| mapped | only url is mapped/returned |
|extension {<br>&emsp;desiredDate<br>&emsp;ccLocation {<br>&emsp;&emsp;practiceName<br>&emsp;&emsp;address {<br>&emsp;&emsp;&emsp;type<br>&emsp;&emsp;&emsp;line [ ]<br>&emsp;&emsp;&emsp;city<br>&emsp;&emsp;&emsp;state<br>&emsp;&emsp;&emsp;postalCode<br>&emsp;&emsp;&emsp;country<br>&emsp;&emsp;&emsp;text<br>&emsp;&emsp;}<br>&emsp;&emsp;telecom [<br>&emsp;&emsp;&emsp;{<br>&emsp;&emsp;&emsp;&emsp;system<br>&emsp;&emsp;&emsp;&emsp;value<br>&emsp;&emsp;&emsp;}<br>&emsp;&emsp;]<br>&emsp;}<br>&emsp;ccRequestedCancellation<br>&emsp;hsrmTaskId<br>&emsp;hsrmConsultId<br>&emsp;vistaStatus: [ ]<br>&emsp;ccTreatingSpecialty<br>&emsp;modality<br>}| mapped | only modality is being mapped/returned |

**Comment by ldelacosta** [comment]
@JRRoof @simiadebowale - here are the details provided by AJ

**Comment by JRRoof** [comment]
So if we are looking to implement read-only for Cerner appointments to begin with, then serviceCategory , locationId and clinic are pieces of the appointment data we would be missing?

**Comment by ldelacosta** [comment]
Per comment from @simiadebowale via Slack https://dsva.slack.com/archives/C0331ERT9C6/p1688740897207529

> yes. If we have c&p Cerner appointments, we won't be able to display them correctly because we rely on the serviceCategory field. We can probably map faclityId to locationId assuming the serve the same purpose. we would need the clinic id to display clinic information

**Comment by ldelacosta** [comment]
No additional info is needed at this time. Closing out the ticket.
