### ISSUE TITLE
Determine if pending requests need a back button

### ISSUE THREAD

**Issue by melissa-lefevre** [department-of-veterans-affairs/va.gov-team#60197]
## Description 
As a Veteran, I want a way to navigate to my appointment requests that is consistent with the other pages I am navigating, so that I can do not have to look for a different way to navigate or accidentally click "cancel appointment".

As part of this story we want to:   

- Determine if the pending requests details screen needs a back button.
![Screenshot 2023-06-12 at 9.25.37 AM.png](https://images.zenhubusercontent.com/603fe0d8f45baf5a1d422aaf/a2a849b6-d319-45da-98b2-66f4bfadbbba)
## Acceptance Criteria
  

-  [ ] AC 1
-  [ ] AC 2
-  [ ] AC 3

**Accessibility Requirements**
- [ ] AC 1
- [ ] AC 2
- [ ] AC 3

## Notes & Open Questions

- Dependencies/Roadblocks:
    - Any internal/external dependencies?
    - Test accounts needed?
- Does this require QA?
    
- Dev Notes: 

## Ticket Checklist

- [ ] Acceptance criteria defined
- [ ] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic

**Comment by outerpress** [comment]
@melissa-lefevre a couple clarifying q's:
- Is the problem statement basically "users who reach the end of a requests page may not be able to easily navigate back to the list"?
- Is this specific for requests, or for all details pages?

**Comment by outerpress** [comment]
@melissa-lefevre the descriptive back link seems to be working well on details pages so I'm closing this one. Reopen if there are any other angles we should look at.
