### ISSUE TITLE
[BE] Determine LOE to Finish All Work and Release to Production

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#60202]
## Description
We need to determine the level of effort to finish all work related to this epic and release it to production. If it will encompass more than 1 sprint for 1 person's time then we need to meet with Stephen & reassess.

**Comment by loripusey** [comment]
@randomsync will you have a LOE before the end of the sprint today? We need this for prioritization.
cc: @stephenBarrs @anita-halici

**Comment by kanchanasuriya** [comment]
Based on the remaining tasks in [epic](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/46631), LOE seem to be

**BE** - 2 Sprints
**FE** - 1 Sprint
**UX** - 2 points
**Prod Release** - 1 point

With all the teams working in parallel, roughly we should be able to complete it in 2 sprints.
