### ISSUE TITLE
Evaluate findability of authenticated tools not tied to a single benefit

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#60201]
Based on research and visitor feedback, we know that visitors can struggle to find some of our authenticated tools that are not specific to a single benefit.  

**Tools to analyze:**
- View payment history
- Claim and appeal status tool
- Change address
- Change direct deposit
- Manage VA debt
- Update dependents

**Build analysis and profile of the current state and performance of tools**
- Current state analysis
  - Current home in IA (i.e. root level, disability hub, etc)
  - All entry points in high priority positions - links in top nav, header/footer, hub pages, home page, and best bets.  
- Analytics - Page data
  - What are key search terms on VA.gov to find and external search engines related to this tool
  - What are the top referring (previous) pages to this tool
  - What are the top next pages when leaving this tool
  - Page views / % unique page views
  - Entrance rate (% of page views are entrances)
  - Bounce rate
  - Exit rate
- Analytics - Event data
  - Total clicks on high priority entry points 
  - Best bet performance
- Qualitive data - Visitor feedback
  - Medallia feedback survey from tool static pages 
    - visitor answered "no" to whether they were able to complete their task
  - Medallia intercept survey
    - Visitor rated 1 or 2 on overall experience
    - Must include keywords: can't find

**Comment by mnorthuis** [comment]
@kristinoletmuskat @jennymayoco I updated the description of this issue to better define the task.  This is pulling data, analytics, and veteran feedback on the auth tools that we often hear are "difficult to find".  This will help us analyze how they are currently performing and how visitors are currently navigating to/finding them.

**Comment by jennymayoco** [comment]
[Draft spreadsheet](https://docs.google.com/spreadsheets/d/1ASxzrGBIIRmZvAALmHCezR9-Vh33wW1RJZvJgpJopo0/edit#gid=0)

**Comment by jennymayoco** [comment]
Next steps:
- [ ] Connect with team who manages qual survey feedback to see if they have any recommendations for parameters
- [ ] Identify any additional parameters
- [ ] Submit ticket for qual survey

**Comment by jennymayoco** [comment]
hi @strelichl! I'm currently reviewing qual data so will keep this ticket open

**Comment by jennymayoco** [comment]
Hi team, I've added the insights and recs in the spreadsheet. Here's the [doc](https://docs.google.com/spreadsheets/d/1ASxzrGBIIRmZvAALmHCezR9-Vh33wW1RJZvJgpJopo0/edit?gid=0#gid=0)

Most immediate, I think updating the best bets for `/manage-va-debt` is a good next step so I'll update that so it better matches search terms most frequently used.
