### ISSUE TITLE
Small typo on External Integrations page

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#60213]
### Description

First paragraph should be changed from `viAs you build on VA.gov` to `As you build on VA.gov`.

### Relevant URLs

https://depo-platform-documentation.scrollhelp.site/developer-docs/external-integrations

### Which type of team are you on? (Platform team, VFS team, or Leadership)

VA engineer

**Comment by taylojill** [comment]
Thanks @acrollet The typo has been corrected.
