### ISSUE TITLE
build roadmap for milestones for GitHub teams project rollout

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#6022]
## Problem description

Some pieces of the GitHub teams project were written out in a doc that was agreed upon with DSVA, but the milestones haven't been explicitly been written out in an easy-to-share way. Need to build an artifact with the plans for this rollout and what we can expect as this goes forward to communicate out to both VSP teams and VFS teams.

## AC

- [ ] Milestones doc written out and in a state where it's shareable with others

**Comment by jhouse-solvd** [comment]
When / if it's decided to move forward with [this](https://github.com/department-of-veterans-affairs/va.gov-team/issues/2166) rollout, we will look into how to roadmap and communicate with stakeholders based on current processes and artifacts. 

Closing.
