### ISSUE TITLE
[Design] 10-10CG - Improvements: Create design to include proposed solutions to business feedback

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#60228]
## Background
In November 2022, our team asked questions of the Caregiver operations management to get a sense of what kind of issues they are seeing when processing applications.  One of the main topics was incorrect or conflicting data on the application.
We need to explore some of these issues, and consider what kinds of improvements we might be able to implement.

Notes from [1/13/2023 bi-weekly meeting](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/Meeting%20Notes/01-13-2023%20CG%20Stakeholder%20Touchbase.md)
>- They [applicants] don't know stuff, causing delays
>     - They don't know to use primary physical residence vs mailing/PO box
>     - DOB functionality is not being used right
>          - year or day will flip one over (one number off) [issue with dropdown)
>     - Signature fields
>          - wrong person name entered (secondary enters in primary field) [PAPER ONLY, NOT POSSIBLE ONLINE]
>     - First & Last name
>          - listing Jon instead of Jonathan, Cat or Cathy instead of Catherine
>     - Non-required fields that are useful
>          - Such as Middle name, useful in ensuring Bank info matches so payments can be processed

In ticket #53405, we have documented proposed solutions to address some of the feedback items

## Tasks
- [ ] Create designs of CG pages showing improvements we can make to address the feedback
- [ ] Share with the team

## Acceptance Criteria
- Designs with proposed changes that will effectively address business feedback (based on pain-points being experienced by staff)

**Comment by katelyncai** [comment]
Designs are complete, [frontend ticket here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60229).

**Comment by katelyncai** [comment]
Designs are complete, [frontend ticket here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60229).
