### ISSUE TITLE
SOCKS access for Micah Frazier

### ISSUE THREAD

**Issue by micahaspyr** [department-of-veterans-affairs/va.gov-team#60227]
### Your Name

Micah Frazier

### Your Email

micah.frazier@oddball.io

### Your Role and Team

Full Stack Engineer

### Product Manager (PM) name and email

Austin Price austin.price@coforma.io

### Product Owner (PO) name and email

Matt Self Matthew.Self2@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCfR5Bg8Zi5dOXiYzYjUXaJGu/62NOV29C0aelGdpKwS081U9v3WzlM+nWgQvzSwiSmTeqFBX1DqAgQIy5L66nHg+eJ+rOzxg71HgMJ27kABEgp3M6YgDl0ROSZdxCmnXmHfo/stLxJnnCRZ5h4LhiA6DZTQuvb/a6FW+tlxllD4N06ACri0dI9O5m/JlUgyZ8XRppcLMht2776Ug70LyST3iWs1EKP7k09i5QuqtWc6Hldc0SPAzNafgnTCob69+aPJVS0YuHJkm3e/QbyMHPygqH7dP/7BIk9ZYz4AxSWnP5StsMUlt61ipCZucwfNFULRfUhAMX6HgVnvh2beVYdrQc4exV2VMrj2PQJp7t/XuhN1+qfJDHKHNnZskFQ/psFojMtYYG0ztNjdG3DmEWrk9a72Qm4pcsmOsBXTM+iBNk/A2lSaY23AtKr/hjUDhGXMS6qidJbdIKlBgYUQwAcwq6Dqs4smvMx4Eg5kxQBoHK4etO1pp/aXMCVoXNiiRE= micahfrazier@MF-Dooms-MBP

### E-QIP Transmittal Confirmation

<img width="822" alt="Screenshot 2023-06-13 at 11 52 31 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/6454840/b082c969-3f51-4b8b-850d-6144df15e2df">

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by micahaspyr** [comment]
@rmtolmach I ran the vtk socks setup again but it created a new ssh-key and is trying to open up a new ticket identical to this one.  Not sure what went wrong there....

**Comment by rmtolmach** [comment]
@micahaspyr Can you run `cat ~/.ssh/id_rsa_vagov.pub` and see if that is the same as what's in this file? https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/roles/dsva-config/files/authorized_keys/micah.frazier%40oddball.io

If it's not, can you edit the description of this issue (three dots in top right corner) and replace your ssh key with what you see in `~/.ssh/id_rsa_vagov.pub`?

**Comment by rmtolmach** [comment]
Open a ticket in #vfs-platform-support in the DSVA Slack if you need more help. That will be faster.

**Comment by micahaspyr** [comment]
Ok, I went ahead and updated the ssh_key requested.

**Comment by micahaspyr** [comment]
@rmtolmach The proper key is in the ticket now. Sorry I should have put a mention in the previous comment 🤦

**Comment by rmtolmach** [comment]
oops, just seeing this! I merged the associated PR, so you should be good in about 10 min!

**Comment by micahaspyr** [comment]
@rmtolmach All good!  It's working for me now 👍 .  Thank you!
