### ISSUE TITLE
[FE] 10-10CG - Improvements: Implement new design updates to address business feedback

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#60229]
## Background
In November 2022, our team asked questions of the Caregiver operations management to get a sense of what kind of issues they are seeing when processing applications.  One of the main topics was incorrect or conflicting data on the application.
We need to explore some of these issues, and consider what kinds of improvements we might be able to implement.

Notes from [1/13/2023 bi-weekly meeting](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/Meeting%20Notes/01-13-2023%20CG%20Stakeholder%20Touchbase.md)
>- They [applicants] don't know stuff, causing delays
>     - They don't know to use primary physical residence vs mailing/PO box
>     - DOB functionality is not being used right
>          - year or day will flip one over (one number off) [issue with dropdown)
>     - Signature fields
>          - wrong person name entered (secondary enters in primary field) [PAPER ONLY, NOT POSSIBLE ONLINE]
>     - First & Last name
>          - listing Jon instead of Jonathan, Cat or Cathy instead of Catherine
>     - Non-required fields that are useful
>          - Such as Middle name, useful in ensuring Bank info matches so payments can be processed

In ticket #53405, we have documented proposed solutions to address some of the feedback items
In ticket #60228, we have updated the design to include the changes needed

## Tasks
- [x] Implement changes based on design updates - [See comment below](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60229#issuecomment-1642436274)
- [ ] Share with team to validate in Staging prior to Production Deployment window

## Acceptance Criteria
- Design changes from business feedback are implemented in the 10-10CG form online

**Comment by katelyncai** [comment]
cc @mkerns1 for when you're back!

**Comment by hdjustice** [comment]
Validated changes have been made in Staging and it looks good!
The Legal Name and Address hint text is present on Veteran, Primary Caregiver and Secondary Caregiver screens to assist with data input.

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/92328831/9b76e006-e2d4-4a5e-8c16-7e29c5a217de)

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/92328831/08eab7cf-591f-46bd-bff9-c1e8ee91f7bb)
