### ISSUE TITLE
SOCKS access for Jeremy Weiland

### ISSUE THREAD

**Issue by jeremy6d** [department-of-veterans-affairs/va.gov-team#60224]
### Your Name

Jeremy Weiland

### Your Email

jeremy.weiland@adhocteam.us

### Your Role and Team

Managing Software Engineer

### Product Manager (PM) name and email

Alyssa Gallion <alyssa.gallion@oddball.io>

### Product Owner (PO) name and email

Bill Chapman William.W.Chapman@omb.eop.gov

### Access Type Requesting

platform

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDKWL7DuXTOif6rV6YdFaTd7fPaI9wBXgmf1eScX6PszurRSBUm3S9Fqy5yDUAxyE3ONervXpDdsXySuM79wGeM8p1T29wcXAlEFraCyy25yGud3mPMTPRY4Pd4N7GO6B9ibPJswGsBXSeG42uM4rY1ZXXp4cgadFP31wpKJS9myBIQ9LUzltEL3f2Ol7nSI/0JRav/plvzEl3tyGBeIWWYOIUT19a4vW2lPMUqfFPPHyWIuCoekoDAAGgm8x3aZsKAF6D2jrJ24ca7Qg3aa1MidZw16JVZe0ULZWVIEILwW6hjmB/KASPaMKbMnpi/nIyeOH02q8w0rQJiz/c8bWt4WhCG+YCzDJzrc7p+hf5jY8JZ92g58jvjId4RI1GleFBEmI9nXXcyuiMuOaocu0Fbg6ggIyaHpEqTN7avXtnEZh836eINhUZVgmuLaRzWKY9SybAA/5+A0qHBrRhvqnLp1aYYcA9tA1cVvW7bAlMRssMdvpudm8mxf2/jpWIuyuE= jeremyweiland@ADHOCMBP-JPW.local

### E-QIP Transmittal Confirmation

![Image 6-13-23 at 1 28 PM (2)](https://github.com/department-of-veterans-affairs/va.gov-team/assets/945/8dc1b17b-852d-40ef-bf94-ff6d55180d9f)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by rmtolmach** [comment]
✅ you should be good in about 10 min!

I'm going to change your PO. PO in this context is a VA PO.

**Comment by jeremy6d** [comment]
I didn't get the key right

**Comment by rmtolmach** [comment]
i confirmed Jeremy has access 😎
