### ISSUE TITLE
SOCKS access for Rocio De Santiago

### ISSUE THREAD

**Issue by rocio-desantiago** [department-of-veterans-affairs/va.gov-team#60231]
### Your Name

Rocio De Santiago

### Your Email

rocio@coforma.io

### Your Role and Team

Front End Engineer | VA Benefits Decision Reviews Team

### Product Manager (PM) name and email

Sade Ragsdale | sade@coforma.io

### Product Owner (PO) name and email

Matt Self | matt.self@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj/TR5YlZvVadOd7t/Ug4G4r0ooVAQ2SZadg2CGWJpC+0imIfplpZCn6X43j96QNI8HDrs9w6UJ5KzjNnvZFGd0sdJneeqlhSO9+mqGqwaV5fb2dimLeSF+2e0+EnVPSDbtMUtIGTZ4qfGgLwtR6ycuuy5XMAmiZijZtS3JYJqQ/j+A+No9RwrGD3Z5I4/XG/3jTlIJIetyWyM7xXO2q3QhsFKeF4vSoY5i37sS8dvS1TUOJAm3YimG+FcjrIQjlEWbYAo1Hy5PUuQhG3Bbd5Et6tIaea2gtIjoG+YPhRPf8vxRm/3hpLpWV193TjSfDYaEztX7RvIBIBs6HLwzuRdIOszMdzh8yPLyXiOoL/b++pEnYPGQAdunEBAiadW5n2Q57QZ1MZIpuL+npeeQak5ccdQ+vX2a8C4e3Lm3Pmsehe7EAABzOn/thKM1fPadQEltVGlL5S0nvHxXBkJQWFB92hjoV83lfichIMTyCdRY6j4JLxD3b5DONz3Z7ILKbc= rociodesantiago@CoformaSantiago.lan

### E-QIP Transmittal Confirmation

Re-requesting access. Access previously approved [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/41741).

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by rmtolmach** [comment]
@rocio-desantiago, i updated your key. It was prefixed with `sh-rsa` instead of `ssh-rsa`. I'm assuming this was just a typo, but correct me if i'm wrong! You should be able to confirm with the command: `cat ~/.ssh/id_rsa_vagov.pub`.

**Comment by rocio-desantiago** [comment]
@rmtolmach ah yes! Thank you for noticing that typo!

**Comment by rmtolmach** [comment]
😄 We have a github action that noticed the key wasn't quite right in the PR https://github.com/department-of-veterans-affairs/devops/pull/13142

@rocio-desantiago I merged your PR, so you should have SOCKS access in about 10 min! Docs if you need them: https://depo-platform-documentation.scrollhelp.site/getting-started/accessing-internal-tools-via-socks-proxy
