### ISSUE TITLE
Add Workflow to 686: "Add a Student 18 to 23 Years Old (674)" Part 1

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#6023]
## Story
As a Veteran using the 686 in VA.gov, I want to be able to adjust my claim to account for adding a 18 to 23 year old student so that I can maintain an accurate representation of my status with the VA.

## Goal
Include the necessary schema workflows and submit PRs for them to be incorporated.  This will fully flesh out the rest of the workflows to coincide with what has already been put out.

## Considerations
- When these are done as multiples, there are merge conflicts that will need to be carefully addressed.
- [Mockup](https://xd.adobe.com/view/bccb4115-4715-4c19-74fc-71759fd7042d-cafa/) (pages 1 to 4)
- There seems to be some overlap/other logics that take this workflow into potentially different directions: we want to ensure that is wholly complete
- List and loop: adding another entity, as applicable: determine if the backend has the ability to take more than one at a time...for now this is for one student.

## Tasks
- [x] Add and/or remove the necessary schema at the workflow level and ensure there are no validation errors.

## Acceptance Criteria
- [x] A PR has been requested and completed for `vets-website`

**Comment by micahchiang** [comment]
PR merged - https://github.com/department-of-veterans-affairs/vets-website/pull/11928
