### ISSUE TITLE
Unit Test for Workflow: "Add a Student 18 to 23 Years Old (674) Part 1

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#6024]
## Goal
Write and complete a unit test for the workflow mentioned above.

## Considerations
- Implement items from previous unit test tickets.
- Use some existing unit test as a model.

## Acceptance Criteria
- [ ] 80% coverage for the workflow has been achieved.

**Comment by micahchiang** [comment]
This workflow has 7 pages. Let's figure out how to break out the work. This almost feels like it should be its own little epic.

**Comment by micahchiang** [comment]
PR merged - https://github.com/department-of-veterans-affairs/vets-website/pull/11945
