### ISSUE TITLE
508-defect-3 [COGNITION]: Consider updating 24/7 HTML for screen reader understanding (VAMC)

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#6025]
## Description

Some pages are using a shorthand pattern like **Mon:** 24/7 to represent Monday, 24 hours a day, 7 days a week. This is an implicit relationship, but is not made clear to assistive technology. I'd like to consider updating this markup to better serve screen reader users. Code snippet below.

The announcement of the full day name has been moved into #21731 as it can be handled from the template. This issue is now limited to handling 24/7 handling. 

## Type of Issue
template

## Point of Contact

**VFS Point of Contact:** _Trevor_

## Acceptance Criteria

* [ ] Screen reader announces the hours of the day and days of the week

## Environment

* MacOS Mojave
* Safari
* VoiceOver

## Possible Fixes (optional)

```html
<ul class="vads-u-flex--1 va-c-facility-hours-list vads-u-margin-top--0 vads-u-margin-bottom--1 small-screen:vads-u-margin-bottom--0 vads-u-margin-right--3">
  <li>
    <b class="abbrv-day">
      <span aria-hidden="true">Mon:</span>
      <span class="vads-u-visibility--screen-reader">Monday</span>
    </b>
    <span aria-hidden="true">24/7</span>
    <span class="vads-u-visibility--screen-reader">Twenty-four hours a day. Seven days a week.</span>
  </li>
</ul>
```

## WCAG or Vendor Guidance (optional)

* [Info and Relationships: Understanding SC 1.3.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-programmatic.html)

## Screenshots or Trace Logs

<img width="657" alt="Screen Shot 2020-02-19 at 4 31 54 PM" src="https://user-images.githubusercontent.com/934879/74883339-5e151200-5336-11ea-8723-743807338d1e.png">

**Comment by davidconlon** [comment]
@1Copenut Is this something that we should test? 24/7 comes out of the Facilities API for hours for many facilities so this may be an issue we want to consider addressing at the source because of how ubiquitous this problem could be (e.g. it's on VAMC pages, Facility Locator, potentially consumed by CERNER, etc)

That being said, as a cognition issue is this something we could test & validate before making a decision on what to do?

**Comment by 1Copenut** [comment]
Good call @davidconlon. Given the potential wide reach, I'm on board for testing and validating. LMK how I can help.

**Comment by mmiddaugh** [comment]
@arickalewis1 want to call this one out for you to ponder...

**Comment by davidconlon** [comment]
@1Copenut for the Mon/Tues etc we may want to document something in the design system for when we use the abbreviations. (https://design.va.gov/content-style-guide/dates-and-numbers)

@mmiddaugh I think we can tackle the day of the week easier than the data we get from the API so we should consider splitting this issue
<span aria-hidden="true">Mon:</span>
      <span class="vads-u-visibility--screen-reader">Monday</span>

**Comment by mmiddaugh** [comment]
Updated description to limit this issue to hours of operation
Moved days of the week into #21731

**Comment by 1Copenut** [comment]
Thank you for the suggestion @davidconlon. I opened a content ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/22231 for updating design.va.gov.
