### ISSUE TITLE
[COGNITION]: Consider updating the ARIA markup on the upcoming and past events links

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#6026]
## Description

The upcoming and previous events links are announcing as buttons. This is confusing because we are making a full roundtrip to the server and the URL is changing. They're coded as links, so let's remove the extra ARIA markup. Screenshot below.

## Type of Issue
template

## Point of Contact

**VFS Point of Contact:** _Trevor_

## Acceptance Criteria

**Definition of done**
* [ ] Screen reader announces the current and upcoming events as links
* [ ] Screen reader announces the current page because it has an `aria-current="page"` attribute

## Environment

* MacOS Mojave
* Safari
* VoiceOver
* https://www.va.gov/pittsburgh-health-care/events/

## WCAG or Vendor Guidance (optional)

* [Info and Relationships: Understanding SC 1.3.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-programmatic.html)

## Screenshots or Trace Logs

![Screen Shot 2020-02-19 at 4 42 31 PM](https://user-images.githubusercontent.com/934879/74883816-61f56400-5337-11ea-8e53-4e5b90084d00.png)

**Comment by mmiddaugh** [comment]
I think this is resolved. Please validate at your convenience, @1Copenut or @jenstrickland

**Comment by jenstrickland** [comment]
validated 🎉
