### ISSUE TITLE
[CNI] Implement CNI

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#60277]
## Description
Implement the CNI 

## Resources 
- Defined as a helm chart
- Deployed as terraform
- https://docs.cilium.io/en/stable/helm-reference/

## Acceptance Criteria
- [ ] CNI deployed to existing environment and tiers
- [ ] Ensure AWS builtin CNI is not included in eks cluster TF modules

## Refinement Guidance - Check the following before working on this issue: 
- [x] _Team label assigned ("platform-tech-team-2")_
- [x] _Epic assigned (if needed)_ 
- [ ] _Estimated (points assigned)_
- [ ] _Sprint assigned (once planned)_
- [x] _Team member(s) assigned_

**Comment by npeterson54** [comment]
Pulling into sprint

**Comment by ph-One** [comment]
Initial helm chart is drafted and manually working. Scripts need added to the Terraform for modification of existing services as well as removal of services that Cilium will be replacing.
