### ISSUE TITLE
[POD PRIORITY CLASSES] Create one for Shared Services

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#60279]
## Description
Create a shared services pod priority class

## Resources 
- Create a helm chart which configures the pod priority classes
- Shared services should be lower than system critical but higher than "application workloads"

## Acceptance Criteria
- [x] Priority class defined but not applied to any workloads

## Refinement Guidance - Check the following before working on this issue: 
- [x] _Team label assigned ("platform-tech-team-2")_
- [x] _Epic assigned (if needed)_ 
- [x] _Estimated (points assigned)_
- [x] _Sprint assigned (once planned)_
- [x] _Team member(s) assigned_

**Comment by hgbarreto** [comment]
Priority Class is now defined and integrated into platform-distro. All workflows triggered were completed successfully including the new helm chart release workflow.
