### ISSUE TITLE
[CNI] R&D on Network Policies

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#60276]
## Description
Determine networking boundaries for CNI.

## Resources 
- Document defining target network boundaries for future implementation.

## Acceptance Criteria
- [ ] Identify and record network boundaries.

## Refinement Guidance - Check the following before working on this issue: 
- [x] _Team label assigned ("platform-tech-team-2")_
- [x] _Epic assigned (if needed)_ 
- [ ] _Estimated (points assigned)_
- [ ] _Sprint assigned (once planned)_
- [x] _Team member(s) assigned_

**Comment by npeterson54** [comment]
Pulling into sprint

**Comment by ph-One** [comment]
R&D'd and implemented
