### ISSUE TITLE
[AWS Node Termination Handler] Install it

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#60289]
## Description
We need to determine if this is needed now that there are newer versions

## Acceptance Criteria
- [ ] Confirm we need this
- [ ] install it
- [ ] test it

## Refinement Guidance - Check the following before working on this issue: 
- [ ] _Team label assigned ("platform-tech-team-2")_
- [ ] _Epic assigned (if needed)_ 
- [ ] _Estimated (points assigned)_
- [ ] _Sprint assigned (once planned)_
- [ ] _Team member(s) assigned_

**Comment by ph-One** [comment]
We use node groups. This handler is not need -- it is called out in their documentation explicitly that if you are use node groups that you do not need this handler.
