### ISSUE TITLE
[ExternalSecrets] communicate changes to all necessary parties

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#60288]
## Description
New ExternalSecrets Operator requires application changes and needs communicated out the need for the changes. Use the #platform-team Slack channel.

## Acceptance Criteria
- [x] Communication has been sent out regarding the need to update helm chart's ExternalSecrets
- [x] if needed, collab on this with teams that need help

## Refinement Guidance - Check the following before working on this issue: 
- [ ] _Team label assigned ("platform-tech-team-2")_
- [ ] _Epic assigned (if needed)_ 
- [ ] _Estimated (points assigned)_
- [ ] _Sprint assigned (once planned)_
- [ ] _Team member(s) assigned_

**Comment by ph-One** [comment]
We have communicated this and Vets API has performed updates to their Helm chart to be compatible with the new operator

**Comment by ph-One** [comment]
The Vets API helm chart is already up to date, as well as all new v.Next secrets
