### ISSUE TITLE
[Datadog Stack] Install Agent

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#60283]
## Description
Install existing datadog helm chart using terraform as part of a standard platform.

## Resources 
- Review versions of componants ensuring latest compatible.

## Acceptance Criteria
- [ ] Existing helm chart for data dog is deployed.

## Refinement Guidance - Check the following before working on this issue: 
- [x] _Team label assigned ("platform-tech-team-2")_
- [x] _Epic assigned (if needed)_ 
- [x] _Estimated (points assigned)_
- [x] _Sprint assigned (once planned)_
- [x] _Team member(s) assigned_

**Comment by ph-One** [comment]
I have pushed all of the latest images to ECR already. https://github.com/department-of-veterans-affairs/vsp-infra-k8s-datadog-agent/actions/runs/5507812889

**Comment by hgbarreto** [comment]
Currently working on converting externalSecrets to the new operator model. Need to document simple conversion instructions and possibly demo for the team.

**Comment by hgbarreto** [comment]
Completed the necessary configuration for the Datadog chart to function with new externalSecrets operator. Working on packaging/publishing the chart to our helm repo. From there, I will immediately begin testing on the cluster.

**Comment by hgbarreto** [comment]
Confirmed that the cluster is now reporting to Datadog. Looking into confirming that everything is reporting correctly

**Comment by hgbarreto** [comment]
Final fix for the helm chart has been confirmed to work.
