### ISSUE TITLE
[Helm] Add Datadog Private Location Chart

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#60284]
## Description
We need to be able to runt tests within our cluster that report back to datadog.  A private location agent will do that

## Acceptance Criteria
- [ ] Datadog Private Location chart is built and released in VPI repo

## Refinement Guidance - Check the following before working on this issue: 
- [x] _Team label assigned ("platform-tech-team-2")_
- [x] _Epic assigned (if needed)_ 
- [x] _Estimated (points assigned)_
- [x] _Sprint assigned (once planned)_
- [x] _Team member(s) assigned_

**Comment by hgbarreto** [comment]
Initial files in place. Currently researching solutions for private location config generation

**Comment by hgbarreto** [comment]
Going to work on Datadog Agent first in order to regroup on strategy for private location automation.

**Comment by ph-One** [comment]
I'm not confident that this should be installed on every cluster. More R&D must be done to see what happens if a cluster runs tests and is later destroyed. Do the tests fail, or are they somehow marked as invalid?

**Comment by ph-One** [comment]
Bumped to an `8` due to prereq of building out and storing a separate Helm chart in our Helm Repo prior to installing it into our cluster

**Comment by ph-One** [comment]
Chart is deployable, but the configuration needs to be dynamic, which is requiring extra considerations not previously known
