### ISSUE TITLE
[eFSR] Collab cycle staging review Content doesn’t align with style guidance in VA.gov content style guide. (02.04.1) (Post Launch)

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#60297]
During our 6/9 Staging Review, this issue was brought up and noted here: department-of-veterans-affairs/va.gov-team#60035 

Step 4 of 7: Installment contracts and other debts > Date the loan > Date Received > Date is written in YYYY-MM-DD format. The VA Style Guide says to use mm/dd/yyyy in form fields.

Link, screenshot or steps to recreate
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/staging-review-images/47462_Cheryl_2_Incongruent%20Syntax%20Page%202_Screen%20Shot%202023-06-08%20at%202.28.05%20PM.png

**Comment by HeatherRienks** [comment]
We will plan to address post SW MVP launch.
