### ISSUE TITLE
cleanup pass on operations docs

### ISSUE THREAD

**Issue by nathanhruby** [department-of-veterans-affairs/va.gov-team#6029]
there are multiple operations, infrastructure, and devops directories in the `va.gov-team` repo.  These folders have a bunch of docs, some useful, some not, some that has been mangled though repo migrations.  

Pre task:
- [ ] rubric on what docs could be public or not.

We need to take some time and clean up':
- [ ] audit to make sure the content is correct, in the right place in the repo, and not duplicated
  - we don't need to rewrite everything in this pass, just make sure it's not wrong, broken, or mishomed
- [ ] move the majority of devops docs into this repo as well, so we only have one place to look
- [ ] pull info from pinned slack items into docs, and update slack to point at the doc
- [ ] make follow up tickets for rewriting tasks

**Comment by nathanhruby** [comment]
this is probably a good one-day all-team intensive exercise to do on a deploy freeze day or other time when we can focus

**Comment by ricetj** [comment]
It would be nice a rubric on what docs could be public or not.

**Comment by jhouse-solvd** [comment]
There will be a forthcoming initiative in 2021 in coordination with the Content & IA team for the Platform Website. The goal will be to audit, re-write, and move documentation for Ops-owned services into a new tool (currently planned for Confluence Data Center). 

Closing.
