### ISSUE TITLE
[eFSR] Collab cycle staging review Design components and patterns in use are outdated (04.08.2) (Post Launch)

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#60295]
During our 6/9 Staging Review, this issue was brought up and noted here: department-of-veterans-affairs/va.gov-team#60033 

The privacy agreement component on the form summary page is out of date. It does not indicate to users that the link to review the privacy statement is external and will open in a new page. This indication should be visual and auditory.

**Comment by HeatherRienks** [comment]
We will plan to address post SW MVP launch.

**Comment by HeatherRienks** [comment]
Will bring into S106
