### ISSUE TITLE
Content review: UAT  review for CMS content migrations

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#603]
## User Story
As content is migrated from Github to drupal, we need to ensure all page components, formatting, and content are accurate and correct before before migration.

## Goal
Content migrated into drupal is functional and bug-free. 

## Acceptance Criteria
We need to follow the UAT process and checklist,  located here:  
[UAT process and checklist](https://github.com/department-of-veterans-affairs/vets.gov-content/blob/master/templates-and-guides/checklists/UAT-process-for-content-migration.md)

## Order of Content Migrations 
- [x]  Records (completed)
- [x]  Pension (completed)
- [x] Careers and Employment (completed)
- [x] Root (completed)
- [x] Life Insurance (completed)
- [x] Housing (Stakeholder feedback has been incorporated on all but 2 pages that need legal review) 
- [x] Disability (completed)
- [x] Education  (completed)
- [x]  Burials (this section is being migrated from a heroku instance. We need to carefully check the menu links, as we can't pull them in from the heroku instance). 
- [x] Service member hub landing page (completed) 
- [x]  Family member hub landing page (completed)

## Definition of Done
This is an ongoing task as hubs are migrated into drupal.

- [x] Content completes UAT testing review, following the checklist that is linked above (@peggygannon)

- [x] Content logs in any migrations bugs and CMS migration spreadsheet in Benefit Migration spreadsheet

- [x] Content team member does a final check that all fixes have been done correctly before migration

**Comment by Karak888** [comment]
@peggygannon thanks for being here!

**Comment by peggygannon** [comment]
@jenniferlee-dsva Now that UAT is "complete" do you think we are ready to close this issue? 

cc: @Karak888

**Comment by jenniferlee-dsva** [comment]
I guess the Burials SME updates are not technically part of UAT, so this sounds right. Close this EPIC epic. Thank you for a phenomenal job of coordinating this huge effort @peggygannon !

**Comment by peggygannon** [comment]
Closing this issue, as all benefit hubs have been migrated to drupal. 

UAT check is complete for all of those hubs.
