### ISSUE TITLE
AWS access for [Sam Stuckey]

### ISSUE THREAD

**Issue by SamStuckey** [department-of-veterans-affairs/va.gov-team#60301]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Sam Stuckey

### Your Email

sam.stuckey@oddball.io

### Team, Role, and Company of the target individual

DBEX-Carbs, Fullstack Engineer, Oddball.io

### Product Manager (PM) name and email

Austin Price austin.price@coforma.io

### Product Owner (PO) name and email

Matt Self Matthew.Self2@va.gov

### Desired AWS Access

I am on the VA Benefits team and will be making features and bugfixes, along with investigating issues, to the vets-api and vets-website repos.

I need access to debug and investigate issues in those environments, and also need all permissions needed to develop on the platform.

Access requested should be ongoing as issues that need resolved/debugged could come and go at anytime.

My Access can be copied from Kyle Soskin [kyle.soskin@adhocteam.us](mailto:kyle.soskin@adhocteam.us) dsvagovcloud AWS user name: Kyle.Soskin

At a minimum, I need group_memberships    = ["dsva-vagov-developers", "dsva-vfs-developers" ,"force-MFA"]

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

<img width="1120" alt="Screen Shot 2023-06-14 at 12 59 39 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/15328092/da3412ee-6f3a-44b6-9fc4-7c80bfdefad3">
<img width="1122" alt="Screen Shot 2023-06-14 at 12 59 49 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/15328092/1d8f782a-8566-4a3b-955a-cb3b35bcc5a6">
VOR: Jeff Langworthy [jeff.langworthy@coforma.io](mailto:jeff.langworthy@coforma.io)

### Additional Notes

VOR: Jeff Langworthy [jeff.langworthy@coforma.io](mailto:jeff.langworthy@coforma.io)

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by BillChapmanUSDS** [comment]
We are beginning the process of requiring more specific descriptions of production access and will have a stricter burden of justification.  Can you describe some of the tasks you would like to perform on production environments that cannot be completed in lower environments?  I will allow the standard 3 months access once specific details are provided  but depending on the justification the access may be limited in future requests.

**Comment by BillChapmanUSDS** [comment]
IF @SamStuckey  can provide a more detailed example of production access justification and add the access-justification-example-provided label we can allow 6 months. But you can allow them 3 months access now.
