### ISSUE TITLE
[identity-helm-library] Release helm chart

### ISSUE THREAD

**Issue by rileyanderson** [department-of-veterans-affairs/va.gov-team#60307]
## Issue Description
On merges to main a github action should run that packages and releases them to a downloadable source. 

## Devops tasks
- [x] Determine release and hosing method
- [x] Implement release

## Acceptance Criteria
- [x] Helm repo is accessible
- [x] Able to access tarballs
- [x] Solution is secure

**Comment by aparsley** [comment]
Looks good.
