### ISSUE TITLE
SOCKS access for Adrian de la Cruz

### ISSUE THREAD

**Issue by adrian-delacruz-a6** [department-of-veterans-affairs/va.gov-team#60304]
### Your Name

Adrian de la Cruz

### Your Email

adrian.delacruz@agile6.com

### Your Role and Team

Software engineer on Health Apps 1010

### Product Manager (PM) name and email

Heather justice heather.justice@adhocteam.us

### Product Owner (PO) name and email

Emily Brown emily.brown@agile6.com

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDGTmbcSRMJvmf6pBHl+DDmfK1Cy4nbhzo5CwFU0m3jQam67K737XSXn1SDMpu8N+rRKcm8iof5IL5b0SxqzrYZD4Bj4O+3MG+9FCXfHJGSiY8D6/W9k7cTdUA8MPydpJ4UZbsgkv9Iu2FAp/6J1NYatfxptyuB4F8dwMtucsYe7I8VYYI3JWjFSt+FGLqUQieUBaWga4av9IxcvDadyMGYE8zOnTbJ8afhcQgISfYmjfEAuWJVmSfZ6G6FQ9kOyHsEEUnD7i4x41Fuuyj41OwYwP47yNddN1v0p9lpCQIp68EZsWnUAMmJm2LHKShPZ32DvJaOO0JXhzFnmDP9Bce932k5EcGyuwz3eMkBlWvKHutk2IPjizsYbFETF4+5oSwDbEqcN/KHvA9eEnpvu0kr5otjbVoxE/JMFH/29H3nIR1KmTqIxBT8uIwyPlpA0bk6wN2eaio7wWYRvqVQ1gcgtTsqubS1A8jswZNzJacXb8WRIdap5kEfuVJxB7toiXM= adrian.delacruz@Adrian-DeLaCruz.attlocal.net

### E-QIP Transmittal Confirmation

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/133033564/941deaf2-d55e-442d-b3f1-722d2252a8d4)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by rmtolmach** [comment]
@adrian-delacruz-a6 ✅ access granted. Give it ~10 min before trying to access sites behind SOCKS. Docs if you need them: https://depo-platform-documentation.scrollhelp.site/getting-started/accessing-internal-tools-via-socks-proxy
