### ISSUE TITLE
Add military service history content and validation greater than 180 days

### ISSUE THREAD

**Issue by christinec-fftc** [department-of-veterans-affairs/va.gov-team#60313]
## Issue Description
Some claims are being populated with a future Date of Claim(DOC) when the user is entering their Contract End Date instead of active Service Exit Date. The discovery has identified that the reservists and national guards are able to submit claims with > 180 days exit date. Validation will soon prevent reservists and national guards from entering a date > 180 days. 

We also discovered that this same validation and error message should apply for all service members.

Add content and validation to prevent future date of claims

https://www.sketch.com/s/ff18b4fb-376a-4f9f-b014-e888f69d9957

## Front end tasks
- Ensure the page is styled according to design spec. 
- ~~Ensure the back end data from API is displayed in local and review instance~~
- Ensure unit tests are available. 
- Ensure your code changes are covered by E2E tests
- Run axe checks using the Chrome or Firefox browser plugin
- Test for color contrast and color blindness issues
- Zoom layouts to 400% at 1280px width
- Test with 1 or 2 screen readers
- Navigate using the keyboard only

## Acceptance Criteria
- [ ] Content changes: Update labels for date fields and add note underneath the dates
- [ ] Add/modify validation message for all service members if Active service end date is more than 180 days
- [ ] Form does not accept > 180 days as service exit date for all service members
- [ ]  Updated content clearly explains what is expected in this field.
- [ ] Designer comments on this issue to approve page styling 
- [ ] Unit tests pass
- [ ] E2E tests cover current code and regression
- [ ] End-to-end tests show 0 violations.
- [ ] ~~The data returned matches API response (for given user or scenario)~~
- [ ] All axe checks pass
- [ ] All color contrast checks pass
- [ ] All zoom testing passes
- [ ] All keyboard checks pass 
- [ ] All screenreader checks pass

## Appendix
<details> 

 <summary>Ensure your code changes are covered by E2E tests (expand)</summary>
 
 - Add E2E tests if none exist for this addition/change. 
 
 - Update existing E2E tests if this code will change functionality. 
 
 - Include axe checks, including hidden content
 
</details>

<details> 

 <summary> Run axe checks using the Chrome or Firefox browser plugin (expand)</summary>
 
- Ensure no heading levels are skipped.

- Ensure all buttons and labeled inputs use semantic HTML elements.

- Ensure all buttons, labeled elements and images are identified using HTML semantic markers or ARIA roles.

- Ensure form fields have clearly defined boundaries or outlines.

- Ensure form fields do not use placeholder text. 

- Ensure form fields have highly visible and specific error states. 

</details>

<details> 

 <summary> Test for color contrast and color blindness issues (expand) </summary>
 - All text has appropriate contrast. 

</details>

<details> 

 <summary> Zoom layouts to 400% at 1280px width (expand)</summary> 
 - Ensure readability and usability are supported when zoomed up to 400% at 1280px browser width
 - Ensure no content gets focused offscreen or is hidden from view.
 
</details>

<details> 

 <summary> Test with 1 or 2 screen readers (expand)</summary> 
 
 - Ensure the page includes a skip navigation link. 
 
 - Ensure all links are properly descriptive. 
 
 - Ensure screen reader users can hear the text equivalent for each image conveying information. 

 - Ensure screen reader users can hear the text equivalent for each image button. 

 - Ensure screen reader users can hear labels and instructions for inputs. 
 
 - Ensure purely decorative images are not announced by the screenreader. 
 
</details>

<details> 

 <summary>Navigate using the keyboard only (expand)</summary> 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be reached with the tab key in a logical order. 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure all interactive elements can be reached with the tab key in a logical order 
 
 - Ensure all interactive elements can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure focus is always visible and appears in logical order.
 
 - Ensure each interactive element has visible focus state which appears in logical order.
 

</details>

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RakshindaAslam** [comment]
Add a ticket for BE validation in general. cc @RakshindaAslam

**Comment by mchae-nava** [comment]
@RakshindaAslam, noting that the text block copy at the bottom of the design ("add text" in screenshot) involves an update to `vets-json-schema`, and therefore some complexity in coordinating across a few PRs.

![Screenshot 2023-07-03 at 4.21.38 PM.png](https://images.zenhubusercontent.com/642494d169d76bbcaeb6679d/7e540e79-f8ec-4a59-9646-310c2b81d01c)

Alternatively, if we move that copy to the bottom of the form (outside the grey box), we can avoid touching `vets-json-schema` altogether.

Otherwise, if we want it coupled in the box, I'll separate out another ticket with the solution to just the text block in order to avoid holding up the rest of the work here, which is complete.

**Comment by mchae-nava** [comment]
Sorry, meant to tag @lydiahooper too

**Comment by lydiahooper** [comment]
@mchae-nava I like placing this text outside the gray box, just beneath it instead.
