### ISSUE TITLE
Landing Page New Secure Message Notification - UX Design

### ISSUE THREAD

**Issue by A6-toma** [department-of-veterans-affairs/va.gov-team#60311]
As a VA.gov user, when I have a new secure message I want to see a notification on the landing page alerting me to that fact and allowing me to navigate to the message.

Questions for consideration:
1. Will New Secure Message landing page notifications be dismissible? If so, what mechanism should be used to dismiss the notification (i.e. 'X' button vs. Dismiss button, confirmation to prevent accidental dismissal or not)
2. What title and content should be included in the notification itself?
3. What mechanism should be used to allow the user to navigate to the message - link/button/other?
4. Should navigation to the message open the message itself or just the Secure Messages page?
5. What accessibility concerns need to be addressed?

### Acceptance Criteria
Designs for the landing page New Secure Message notification have been documented and communicated to relevant teams and individuals.

**Comment by batemapf** [comment]
is this ticket necessary given #60306 (which is specific to new SM, but will be applicable to all subsequent notification types)?

**Comment by fmccaf1** [comment]
Here's a screenshot of the SM inbox showing the visual indicators (blue dot and bolded text) for unread messages: 


![Desktop-Landing Page Inbox-Next page.jpg](https://images.zenhubusercontent.com/629a1db0e70457da479e69ae/8d952d25-7fea-4171-8447-bb038fdb816a)


I asked in the SM slack channel if those visual indicators are successful from a UX standpoint and Anne Costello said they were: 

![image.png](https://images.zenhubusercontent.com/629a1db0e70457da479e69ae/016f1784-06ba-445b-8101-852a2370c13a)

[Here's a link to that Slack thread^](https://dsva.slack.com/archives/C03ECSBGSKX/p1689094784583889)

**Comment by fmccaf1** [comment]
[Here are secure notification badge designs for both desktop and mobile.](https://sketch.com/s/f9050748-823b-4245-98c9-e9738c15a271) I think we're ready to go forward with the collab cycle.
