### ISSUE TITLE
[EFSR] Feature Flag Routing 

### ISSUE THREAD

**Issue by amponce** [department-of-veterans-affairs/va.gov-team#60338]
### Veteran information Chapter

| Path                         | old   | combined | enhanced |
| ---------------------------- | ----- | -------- | -------- |
| /veteran-information         | true  | true     | true     |
| /available-debts             | true  | false    | true     |
| /all-available-debts         | false | true     | false    |
| /contact-information         | true  | true     | false    |
| /current-contact-information | false | false    | true     |
| /edit-mobile-phone           | false | false    | true     |
| /edit-email-address          | false | true     | true     |
| /edit-mailing-address        | false | false    | true     |

### Household Income Chapter

| Path                                 | old   | combined | enhanced |
| ------------------------------------ | ----- | -------- | -------- |
| /employment                          | true  | true     | false    |
| /employment-records                  | true  | true     | false    |
| /employment-question                 | false | false    | true     |
| /enhanced-employment-records         | false | false    | true     |
| /gross-monthly-income                | false | false    | true     |
| /deduction-checklist                 | false | false    | true     |
| /deduction-values                    | false | false    | true     |
| /employment-history                  | false | false    | true     |
| /income/:index                       | true  | true     | false    |
| /benefits                            | true  | true     | false    |
| /your-benefits                       | false | false    | true     |
| /edit-benefits                       | false | false    | true     |
| /social-security                     | true  | true     | false    |
| /social-security-records             | true  | true     | false    |
| /additional-income                   | true  | true     | false    |
| /additional-income-records           | true  | true     | false    |
| /additional-income-checklist         | false | false    | true     |
| /additional-income-values            | false | false    | true     |
| /other-income-summary                | false | false    | true     |
| /add-other-income                    | false | false    | true     |
| /spouse-information                  | true  | true     | true     |
| /spouse-name                         | false | false    | true     |
| /enhanced-spouse-employment-question | false | false    | true     |
| /enhanced-spouse-employment-records  | false | false    | true     |
| /spouse-gross-monthly-income         | false | false    | true     |
| /spouse-deduction-checklist          | false | false    | true     |
| /spouse-deduction-values             | false | false    | true     |
| /spouse-employment-history           | false | false    | true     |
| /spouse-employment                   | true  | true     | false    |
| /spouse-employment-records           | true  | true     | false    |
| /spouse/income/:index                | true  | true     | false    |
| /spouse-benefits                     | true  | true     | true     |
| /spouse-benefit-records              | true  | true     | true     |
| /spouse-social-security              | true  | true     | false    |
| /spouse-social-security-records      | true  | true     | false    |
| /spouse-additional-income            | true  | true     | false    |
| /spouse-additional-income-records    | true  | true     | false    |
| /spouse-additional-income-checklist  | false | false    | true     |
| /spouse-additional-income-values     | false | false    | true     |
| /spouse-other-income-summary         | false | false    | true     |
| /spouse-add-other-income             | false | false    | true     |
| /dependents                          | true  | true     | false    |
| /dependents-count                    | false | false    | true     |
| /dependent-records                   | true  | true     | false    |
| /dependent-ages                      | false | false    | true     |

### Household Assets Chapter

| Path                                | old   | combined | enhanced |
| ----------------------------------- | ----- | -------- | -------- |
| /monetary-assets                    | true  | true     | false    |
| /monetary-asset-checklist           | false | false    | true     |
| /monetary-asset-values              | false | false    | true     |
| /real-estate-assets                 | true  | true     | false    |
| /real-estate-asset-records          | true  | true     | false    |
| /enhanced-real-estate-assets        | false | false    | true     |
| /enhanced-real-estate-asset-records | false | false    | true     |
| /vehicles                           | true  | true     | true     |
| /vehicle-records                    | true  | true     | false    |
| /your-vehicle-records               | false | false    | true     |
| /vehicles-summary                   | false | false    | true     |
| /recreational-vehicles              | true  | true     | true     |
| /cold -recreational-vehicle-records | false | true     | false    |
| /recreational-vehicle-records       | true  | false    | true     |
| /other-assets                       | true  | true     | false    |
| /other-asset-records                | true  | true     | false    |
| /other-assets-checklist             | false | false    | true     |
| /other-assets-values                | false | false    | true     |
| /other-assets-summary               | false | false    | true     |
| /add-other-asset                    | false | false    | true     |

### Household Expenses Chapter

| Path                           | old   | combined | enhanced |
| ------------------------------ | ----- | -------- | -------- |
| /expenses-explainer            | false | false    | true     |
| /expenses                      | true  | true     | false    |
| /household-expenses-checklist  | false | false    | true     |
| /household-expenses-values     | false | false    | true     |
| /utilities                     | true  | true     | false    |
| /utility-records               | true  | true     | false    |
| /utility-bill-checklist        | false | false    | true     |
| /utility-bill-values           | false | false    | true     |
| /utility-bill-summary          | false | false    | true     |
| /add-utility-bill              | false | false    | false    |
| /repayments                    | true  | true     | false    |
| /repayment-records             | true  | true     | false    |
| /credit-card-bills             | false | false    | true     |
| /your-credit-card-bills        | false | false    | true     |
| /credit-card-bills-summary     | false | false    | true     |
| /installment-contracts         | false | false    | true     |
| /your-installment-contracts    | false | false    | true     |
| /installment-contracts-summary | false | false    | true     |
| /other-expenses                | true  | true     | false    |
| /other-expense-records         | true  | true     | false    |
| /other-expenses-checklist      | false | false    | true     |
| /other-expenses-values         | false | false    | true     |
| /other-expenses-summary        | false | false    | true     |
| /add-other-expense             | false | false    | true     |

### Repayment or relief options

| Path                                | old   | combined | enhanced |
| ----------------------------------- | ----- | -------- | -------- |
| /option-explainer                   | true  | true     | true     |
| /resolution-options                 | true  | false    | true     |
| /resolution-option/:index           | false | true     | true     |
| /resolution-comment/:index          | false | true     | true     |
| /resolution-waiver-agreement/:index | false | true     | true     |
| /resolution-comments                | true  | true     | true     |

### Bankruptcy History Chapter

| Path                                 | old   | combined | enhanced |
| ------------------------------------ | ----- | -------- | -------- |
| /bankruptcy-history                  | true  | true     | true     |
| /bankruptcy-history-records          | true  | true     | false    |
| /enhanced-bankruptcy-history-records | false | false    | true     |

**Comment by HeatherRienks** [comment]
Closing this ticket, per FE consensus. 
Link to current funnel logic:
https://docs.google.com/spreadsheets/d/1ZlwjHdCAZZLp2k7QRX0Bf0xsEBr98W_UYUW_rjW7Hlk/edit#gid=1132090508
