### ISSUE TITLE
Sign in Service - Service Account Access Token Validation

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#60336]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Sign-In%20Service/Components/Service_Accounts.md

- [x] create API access token authentication method
  - [x] validations: decode with SiS private key, expiration, requested route is within access token `scopes`
  - [x] unit tests for `authenticate_service_account` & `ServiceAccountAccessTokenJWTDecoder`

**Comment by bramleyjl** [comment]
Service Account Access Token documentation: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/vsp/teams/Identity/Sign%20In%20Service/Service_Account_Authentication.md

**Comment by aparsley** [comment]
Thank you for attaching artifacts.
