### ISSUE TITLE
Analytics Implementation or QA Support for Veteran Facing Forms- Form 21-4142(a)

### ISSUE THREAD

**Issue by tbaker1026** [department-of-veterans-affairs/va.gov-team#60334]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

</div>
</details>

### Required
- **Is this request for **Google Analytics implementation** or **QA**?**

     - [x] Google Analytics implementation
     - [ ] QA

- **Who is this request for?**

    - [Insert team name(s), for individual's names please use the `/support` tracker on the #vfs-platform-support channel and link this ticket.]
    
    
- **Provide the link(s) for Google Analytics implementation or QA**
  
    - [Insert link(s)](https://staging.va.gov/supporting-forms-for-claims/release-information-to-va-form-21-4142/introduction)
    
- **When is the launch date?**
    - 6/26/2023

- **What interactions need to be tracked?** _NOTE: [Links to Track](https://docs.google.com/spreadsheets/d/1ki0Krx8v5ZQyx-HdzHibSl9ELv-avHYjG5bywED9LxU/edit#gid=0)
- [Test Users](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/simple-forms-test-accounts.md)
    
    - [If this is a funnel, insert each step's URL - pages visible depending on the applicant's answers should be marked accordingly]
    
    - [Insert other interactions - please review the [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) and [GA Data Dictionary](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Google-Analytics-Data-Dictionary.1810464912.html)  to make sure these interactions aren't already tracked]

### Optional
- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - [Insert test user]

- **Any additional comments**

    - [Insert comments]

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by michelle-dooley** [comment]
@tbaker1026 - I will review with team and get back to you with any questions and timing.

**Comment by michelle-dooley** [comment]
@tbaker1026 - we don't generally track back and next for other forms, is it required for this particular form and if so what is the use case?  Just need to get better understanding of what you need/how you are using it to determine best next steps.

**Comment by tbaker1026** [comment]
@michelle-dooley we don't need to track those interactions - just wasn't sure what to put in for interactions

**Comment by michelle-dooley** [comment]
@tbaker1026 - ok so I don't think we need this ticket.  We are working on your [Domo dashboard request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/62493) now and I think that will give you everything you need.  So I am going to close this ticket.  After the dashboard is complete if there is something new we need to set up we can discuss.
