### ISSUE TITLE
Sidekiq Admin UI access for [individual]

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va.gov-team#60355]
### Your Name

Mark Dewey

### Your GitHub handle (Sidekiq Admin UI access is managed through GitHub)

mdewey

### Your dsvagovcloud AWS user name (if applicable)

mark.dewey

### Team, Role, and Company of the target individual

OCTO Health Apps Team 

### COR Name

Other - please specify in 'Additional Notes'

### Please confirm if you are on the VFS Team Roster or Platform Team Roster

- [X] [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Sidekiq UI Access requested for the following environments

- [ ] dev
- [ ] staging
- [ ] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### If PRODUCTION ACCESS is required, confirm/complete ONE of the following

- [x] I have an AWS Username and it is listed in [here](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf)
- [ ] I currently have access to vets-api Production Terminal via ArgoCD
- [ ] I've attached a screenshot of my E-QIP Transmittal Notice E-mail (Drag or Copy/Paste in Additional Notes Section below)

### Additional Notes

I am an OCTO Engineer looking to debug an issue with a production sidekiq job for the highly visible Travel Pay feature on va.gov.

**Comment by bdech** [comment]
@mdewey  You've been granted access to all environments, with access to Production limited to 6 months, expiring 12/15/23

**Comment by bdech** [comment]
slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1686846605567329)

**Comment by bdech** [comment]
Hi @mdewey, your Production access has expired.

Would you like to request an extension? You have 72 hours to respond, or your 
access will be revoked and you will need to fill out a new request.

**Comment by bdech** [comment]
No response, access revoked. If you would like to request access again please fill out a new Sidekiq Admin request.
