### ISSUE TITLE
[GHA] Generate Release Notes for Terraform Modules

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#60350]
# Description
It would be nice to have a spec/usage document with each module release

# Notes
- https://github.com/department-of-veterans-affairs/vsp-platform-infrastructure/blob/main/.github/workflows/tfmod-release.yaml
- Leverage `terraform-docs`
- Generate a README/Usage document and attach to release
- Generate a sample tfvars and attach to release

**Comment by ph-One** [comment]
Reopening

![image.png](https://images.zenhubusercontent.com/622146ffd0422cdb4d9fdd52/f92d09a0-43be-4695-a4af-2ae736b80e4d)

**Comment by npeterson54** [comment]
Due to unexpected PTO moving into next sprint

**Comment by ph-One** [comment]
Moving to backlog. This is a nice-to-have, but not something that should be placed ahead of, say, getting some critical components deployed.
