### ISSUE TITLE
Sidekiq Admin UI access for [individual]

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#60354]
### Your Name

Adrian Rollett

### Your GitHub handle (Sidekiq Admin UI access is managed through GitHub)

@acrollet

### Your dsvagovcloud AWS user name (if applicable)

Adrian.Rollett

### Team, Role, and Company of the target individual

VA (OCTO Health Engineers)

### COR Name

Other - please specify in 'Additional Notes'

### Please confirm if you are on the VFS Team Roster or Platform Team Roster

- [x] [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Sidekiq UI Access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### If PRODUCTION ACCESS is required, confirm/complete ONE of the following

- [X] I have an AWS Username and it is listed in [here](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf)
- [ ] I currently have access to vets-api Production Terminal via ArgoCD
- [ ] I've attached a screenshot of my E-QIP Transmittal Notice E-mail (Drag or Copy/Paste in Additional Notes Section below)

### Additional Notes

I need this access to debug production issues (currently for patient check-in, but potentially for any health application). Thanks!

**Comment by ryan-mcneil** [comment]
@acrollet You've been granted access to all environments, with access to Production limited to 6 months, expiring 12/15/23

**Comment by ryan-mcneil** [comment]
Slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1686844355102959)

**Comment by bdech** [comment]
Hi @acrollet, your Sidekiq Production access has expired.

Would you like to request an extension? You have 72 hours to respond, or your
access will be revoked and you will need to fill out a new request.

**Comment by acrollet** [comment]
no extension needed at this time, thanks
