### ISSUE TITLE
Sidekiq Admin UI access for Stephen Barrs

### ISSUE THREAD

**Issue by stephenBarrs** [department-of-veterans-affairs/va.gov-team#60356]
### Your Name

Stephen Barrs

### Your GitHub handle (Sidekiq Admin UI access is managed through GitHub)

stephenBarrs

### Your dsvagovcloud AWS user name (if applicable)

stephen.barrs

### Team, Role, and Company of the target individual

OCTO FTE Engineering CoP

### COR Name

Other - please specify in 'Additional Notes'

### Please confirm if you are on the VFS Team Roster or Platform Team Roster

- [ ] [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Sidekiq UI Access requested for the following environments

- [ ] dev
- [ ] staging
- [ ] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### If PRODUCTION ACCESS is required, confirm/complete ONE of the following

- [X] I have an AWS Username and it is listed in [here](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf)
- [ ] I currently have access to vets-api Production Terminal via ArgoCD
- [ ] I've attached a screenshot of my E-QIP Transmittal Notice E-mail (Drag or Copy/Paste in Additional Notes Section below)

### Additional Notes

Debugging of production issues, currently related to Patient Check In, but also any future applications.  Also prefer that OCTO FTE Engineers have access.

**Comment by bdech** [comment]
@stephenBarrs I can't locate you in the VFS Team Roster. You will want to reach out to your project manager to get you added

**Comment by bdech** [comment]
@stephenBarrs You will want to complete the [Platform Orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)

As soon as you start orientation one of the teams is notified and then adds you to the VFS roster

**Comment by bdech** [comment]
@stephenBarrs Have you been able to start Platform Orientation?

**Comment by stephenBarrs** [comment]
I have been working in OCTO for 3+ years and did all the onboarding when I joined the team.

**Comment by bdech** [comment]
found old platform orientation [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/30115). Ticket indicates users have been added to VFS Teams Roster.

**Comment by bdech** [comment]
@stephenBarrs Can you get in touch with your project manager to get added to the VFS Teams Roster. I found your old Platform Orientation ticket. Once you're added to the VFS Roster I will grant access.

**Comment by bdech** [comment]
@stephenBarrs I am following up on this request. Were you able to get in touch with your project manager to be added to the VFS team roster? Also, can you provide a screenshot of your EQIP transmittal notice?

**Comment by bdech** [comment]
no response, closing request.
