### ISSUE TITLE
Issues from Shawn Adams to Consider

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#60370]
## Description
[Slack thread](https://dsva.slack.com/archives/C022AC2STBM/p1686840455788919?thread_ts=1686750983.948059&cid=C022AC2STBM)

- Issue 1
   ![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/96389922-3630-4c00-9c7b-008023927aad)

- Issue 2
   ![image.png](https://images.zenhubusercontent.com/60db6a817900f619905e68b1/b376b0d5-8e5e-4e8d-a87e-21475ba7e780)

**Comment by loripusey** [comment]
@benbrasso-agile6 here are the issues that Shawn brought up in the slack thread

I'll schedule some time with him to understand these (@loripusey )

**Comment by benbrasso-agile6** [comment]
Those are good/important points. But, sure, don't require to be complete prior to pilot release date.
