### ISSUE TITLE
[Other - Accessibility] Error messages display while still entering response (possible bug). (00.00.1)

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#60378]
#### VFS team name
Digitize Forms

#### VFS product name
Form 21-4142(a)

#### Point of Contact/Reviewers
Brian DeConinck - @briandeconinck - Accessibility

*For more information on how to interpret this ticket, please refer to the [Anatomy of a Staging Review issue ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Anatomy-of-a-Staging-Review-Issue-ticket.2060320997.html) guidance on Platform Website.

---

### Platform Issue
No VA.gov Experience Standard for the issue found.

### Issue Details
On some inputs in the workflow, error messages instructing users on how to format their responses are displaying as you type your response (after the first character) rather than after the `blur` event when focus moves out of the input. This doesn't seem to be happening consistently, but it does seem to be happening at least some of the time in some places. See the steps to reproduce below.

Displaying an error message while the user is still entering their value for the input is distracting --- essentially interrupting a user to tell them they've done something wrong before they even get a chance to finish doing it. But for screen reader users, it's literally interrupting them. The `role="alert"` on the error message is the same as an `aria-live="assertive"`, meaning the error message gets announced before anything else, including what the user is typing into the field. It's a little too intrusive.

### Link, screenshot or steps to recreate
As noted above, the behavior here seems inconsistent. But these steps seem to definitely trigger the behavior.

1. Go to [Form 21-4142](https://staging.va.gov/supporting-forms-for-claims/release-information-to-va-form-21-4142/introduction) and start the workflow as an unauthenticated user.
2. At Step 2, enter a single-character value for the VA file number (eg. `2`).
3. Press [tab] to move focus to the next input. The validation error should appear on `blur`.
4. Press [shift] + [tab] to move focus back to the VA file number input. Delete the single-character value. The validation error should go away.
5. Press [tab] to move focus to the next input. Still no error.
6. Press [shift] + [tab] to move back to the VA file number input. Enter a single-character value.
7. Note that the error message now appears while focus is in the input, rather than happening on `blur`.

These steps are a little contrived (users probably aren't going to go back and forth like that), but they reliably reproduce the behavior. In my testing I saw this happen on the first attempt to enter a value without having to go back and forth --- or at least I thought I did! The inconsistency of the behavior here has me second-guessing myself.

[Example of the behavior](https://raw.githubusercontent.com/department-of-veterans-affairs/va.gov-team/master/platform/working-with-vsp/vsp-collaboration-cycle/staging-review-images/54257-brian-000001-1.gif)

And here's [another example, with screen reader audio](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/staging-review-images/54257-brian-000001-2.mov)

Huge thank you to @jeana-adhoc, @joshkimux, and @jaredcunha for helping me reproduce this, and Josh and Jared for capturing the videos.

### VA.gov Experience Standard
[Category Number 00, Issue Number 00](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

### Platform Recommendation
Error messages should appear on `blur` when a user moves out of the input. Really not sure what's happening here, but hopefully you all can tug at these threads and track down where this might be going wrong!

---

### VFS Guidance

- Close the ticket when the issue has been resolved or validated by your Product Owner
- If your team has additional questions or needs Platform help validating the issue, please comment on the ticket
- Some feedback provided may be out of scope for your iteration of the product, however, Platform's OCTO leadership has stated that all identified issues need to be documented and it is still your responsibility to resolve the issue.
- If you do not believe that this Staging Review issue ticket is the responsibility of your team, comment below providing an explanation and who you believe is responsible. Please tag the Point of Contact/Reviewers. Governance team will research and will follow up.

**Comment by briandeconinck** [comment]
As noted in the staging review meeting, this may be a component bug. Tagging @caw310 for awareness, cc @shiragoodman @humancompanion-usds

**Comment by jeana-adhoc** [comment]
[We are starting to look into this issue on ticket 434 in the va forms repo](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/issues/434)

**Comment by rhasselle-oddball** [comment]
Re: the above mentioned 60059. 

We have changed all form logic to now only show errors to begin showing errors/validation after the user has blurred a non-empty field - this means that if the user tabs through empty fields, they will no longer be presented with errors when reentering a blank field and start typing for the first time. 

This doesn't however change the behavior described in this ticket about reentering a populated field, then clearing it and now expecting errors go away. Errors will continue to persist as soon as they are first introduced, because we have a flag to determine: "Has the field been touched or not?", and once that flag is turned on, we don't turn it off. It would be more difficult to implement a behavior where this was dynamic based on always watching the state of their changed input.

**Comment by jeana-adhoc** [comment]
This has been out on production for over a week. Resolving - we will monitor for other issues. But I think we've been able to tackle this one.
