### ISSUE TITLE
create version of email #1 with CTA for staging test 

### ISSUE THREAD

**Issue by djmunoz1** [department-of-veterans-affairs/va.gov-team#60385]
As an email admin I need a email content that includes a CTA so that I can run a staging test and confirm that I'm getting analytics data on clickthrough rates.

ACCEPTANCE CRITERIA:
- finalized email content contains CTA button

DEFINITION OF DONE:
- staging test email content stored in shared drive for easy dev access (link to ticket)

**Comment by alevindecanini** [comment]
@CarlDickerson can you add the link please

**Comment by CarlDickerson** [comment]
Link to content: https://drive.google.com/file/d/1Trn-tBCEOfLyrZoXOX0uBfkfZa9MIhDk/view?usp=drive_link
