### ISSUE TITLE
create script for automating SSOe data

### ISSUE THREAD

**Issue by djmunoz1** [department-of-veterans-affairs/va.gov-team#60384]
As a database admin I want data from SSOe to automatically update so that I can see the latest changes in CSP credential events in the dashboard or download them without having to do manual work.

ACCEPTANCE CRITERIA:
- [technical]

DEFINITION OF DONE:
- SSOe data automatically updates on 'x' cadence 
- document (in ticket) the names of any SMEs who gave input when implementing this work

**Comment by sdickson-gt** [comment]
Brent Caunt on IAM team confirmed that the API user account that he had created for us does have access to create new scheduled splunk queries.  He provided the following URL as a guide: https://hurricanelabs.com/splunk-tutorials/splunk-searching-with-rest-api/

**Comment by sdickson-gt** [comment]
Domo Workbench jobs to pull SSOe data are scheduled to run on 8 am on first day of each month.  The outstanding issue is that Domo Workbench is a Windows application that runs as a user process.  It is subject to the frequent forced reboots by the VA and will have to be manually restarted each month.  Need to look into whether it can set to restart on reboot or be run as an service on a server.

Design notes have been updated: https://docs.google.com/document/d/12zh0ck5eoxmF7aREdfqTJtYQQfwP53mP/edit.

Scripts, Domo jobs, and datasets are backed up on shared network drive: \\vacohsm01.dva.va.gov\VACO_Workgroups\Information & Technology\OCTO Digital Experience\ETL\scripts
