### ISSUE TITLE
[Bug] Facility Locator - Results summary subhead updates prematurely (and number displayed is incorrect)

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#6039]
## What happened?
On Staging Facility Locator, changing facility-type updated results summary subhead prematurely, **before** clicking Search button and new results loaded for the newly-selected facility-type.

## Specs:
**Browser(s)/Device(s)**: \[This bug is browser-/device-agnostic]

## Steps to Reproduce
1. Go to https://staging.va.gov/find-locations/ \[enable/allow geolocation if prompted]
1. After geolocation results have auto-loaded, from **Choose a VA facility type** dropdown, choose **Urgent Care**\*.
1. Observe that the results summary subhead updates immediately after facility-type selection (before you click Search button or Urgent-care results load) -- this causes confusion as the previously-loaded VA-health results are still displayed.

\*This bug occurs basically whenever you change facility-type, and before you click Search button.

**Mac Chrome example** \[after changing facility-type, before clicking Search button]
<img width="1095" alt="fac-loc-results-summary-mac-chrome-200219" src="https://user-images.githubusercontent.com/587583/74888416-1d6bc780-533b-11ea-94ad-2e9fba664d07.png">

## Desired behavior
\[I couldn't find any specs for the results summary subhead]
I propose that we either:
* **Hide the results summary** upon filter changes, re-displaying only after new results have loaded; or
* **Suppress the updating** of the results summary until new results have loaded.

## Acceptance Criteria

-[ ] Results summary subhead displays accurate search result numbers 
-[ ] Results summary subhead correctly updates when the user goes to subsequent pages
-[ ] Results summary subhead correctly updates with new facility type searches and does not prematurely load

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by mmiddaugh** [comment]
The number of results presented in the results summary subhead is also incorrect for Community Care searches and may be misleading and confusing to users. Given this plus the premature display, @davidconlon @arickalewis1 what do you think about hiding it?

**Comment by arickalewis1** [comment]
@mmiddaugh is there a way to stop it from updating until the search is triggered again? I'd prefer that over hiding the result count.

**Comment by mmiddaugh** [comment]
Decision was made to suppress subhead summary in [#6775](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6775). This issue will resolve the underlying issue
