### ISSUE TITLE
create question doc for Granicus on GovDelivery API

### ISSUE THREAD

**Issue by djmunoz1** [department-of-veterans-affairs/va.gov-team#60393]
As a developer I want to ensure I understand all the relevant attributes of the GovDelivery API so that I can send email campaigns to veterans.

ACCEPTANCE CRITERIA:
Review existing GovDelivery api documentation
Develop question doc considers technical needs for veteran email campaigns that allow us to:
- A/B testing of content
- define email frequency for users (ideal state is likely monthly emails for 
- define distribution volume (i.e. throttling the no. of veterans that receive a campaign)
- permit unsubscribes
- use a VA template to send content with CTAs for users
- trigger email sends when user logs in (this is not high priority, emails can be async if needed)

DEFINITION OF DONE:
 - Question doc is in shared drive to review with Granicus (GovDelivery)

**Comment by djmunoz1** [comment]
As a developer I want to ensure I understand all the relevant attributes of the GovDelivery API so that I can send email campaigns to veterans.

ACCEPTANCE CRITERIA:
Review existing GovDelivery api documentation
Develop question doc considers technical needs for veteran email campaigns that allow us to:
- A/B testing of content
- define email frequency for users (ideal state is likely monthly emails for 
- define distribution volume (i.e. throttling the no. of veterans that receive a campaign)
- permit unsubscribes
- use a VA template to send content with CTAs for users
- trigger email sends when user logs in (this is not high priority, emails can be async if needed)

DEFINITION OF DONE:
 - Question doc is in shared drive to review with Granicus (GovDelivery)

**Comment by jrjamespdx** [comment]
At this time, we do not have any additional technical questions regarding their API.
