### ISSUE TITLE
Request Design Review - Education Routing Wizard

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#6040]
**Context:** 
The Buffalo Regional Processing Office reports more than 90% of Rogers STEM Scholarship applications are being denied due to ineligibility.  The new functionality provides cues, messaging, obstacles and alternate options for individuals passing through the Education Benefits routing wizard and VA Form 22-1995 to inform them of the specific scholarship requirements and alert them if it appears they may not be eligible. 

- **Education Benefits routing wizard** - https://staging.va.gov/education/how-to-apply/ and https://staging.va.gov/education/eligibility/ 
 
- **Prototype (Wizard & Form)** - https://bahdigital.invisionapp.com/share/9GIACS4WX82#/screens

**New Design Patterns (if any):** N/A

**Design Challenges (if any):** Design challenge for the Wizard was adding additional information about Rogers STEM Scholarship requirements and a confirmation question in a way that allows users to evaluate their eligibility and if they're not eligible, give them a viable option for their next step.

**Comment by amyknox** [comment]
@CrystabelReiter , @emilywaggoner, @1Copenut 
Do you have a status update on the STEM Wizard design review?
Wizard is accessible via the green "Find your education benefit form" on the How to apply page. 

![image.png](https://images.zenhubusercontent.com/5b51ea398c1a7628d9218a42/4d842fd8-15fe-490e-9158-df51acec8790)

**Comment by CrystabelReiter** [comment]
Hi @amyknox sorry for the late response! I got confused and thought last week's meeting was supposed to be about this tool and I think I just misunderstood!

This looks great. The one point of feedback I would have is the language surrounding the "Learn more"s after every option  in section 2.  Please consider changing the copy and use descriptive instead of using standalone Learn more text. This helps bring more context to the users and where they're going. 

Thank you for being patient!

<img width="739" alt="Screen Shot 2020-02-27 at 1 51 19 PM" src="https://user-images.githubusercontent.com/18386248/75476936-70f89980-5969-11ea-8a7e-e901ddc90dc8.png">

**Comment by amyknox** [comment]
Oh wow, this is not a great page, is it?  We have always been doctoring the STEM pages of this form and leaving the other stuff alone but this needs some help.  I'll see if we can add this to our backlog and make the update asap.

Thanks for the quick turn around today!

**Comment by amyknox** [comment]
@CrystabelReiter - technically this review request was specifically for the Wizard which is the first screen on the **How to apply** page.  

The Design Review for the application STEM updates (and the learn more extravaganza above) is https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/5995

**Comment by CrystabelReiter** [comment]
@amyknox Thank you for clearing that up! 

One question I have is that is there a purpose around the yellow box around the radio button options? 

Another thing that stood out to me is that the alert title is not aligned with the icon. 

<img width="844" alt="Screen Shot 2020-02-27 at 5 21 10 PM" src="https://user-images.githubusercontent.com/18386248/75496352-e9258600-598e-11ea-9cf8-3a30fffff264.png">

**Comment by 1Copenut** [comment]
@amyknox I've looked through the wizard with an eye on the third radio, for the STEM scholarship. The only thing I can call out for accessible design is a consideration only, not a must do. Screen reader users sometimes move through forms using the `| f |` key to move by form elements. The text of requirements is not a form element, so there *could* be an opportunity for that to be missed by screen readers.

I can see a couple options that might work:

1. Add a link that says something like "Review eligibility requirements" at the end of the "Based on the eligibility requirements above, do you want to apply for this scholarship?" `<legend>` text. This link would be an anchor that points to the paragraph above.
2. Adding an `aria-describedby` attribute to the `<legend>` that references a unique ID on the paragraph of requirements. This would need tested with screen readers, but either could give full context, if somewhat redundant.

I'd rather come down on the side of redundancy than have important content get missed.

**Comment by amyknox** [comment]
Thank you @CrystabelReiter and @1Copenut for the input.  Since there are no show-stoppers, I'm closing this story and will discuss the suggestions with my team to see what we can pull in and when.
