### ISSUE TITLE
My VA Dashboard and veteran appointments

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#6041]
As a veteran, I want to be able to get access to my upcoming appointments through the My VA dashboard because this is where I track in one location my VA communication and benefits. 

##AC
- [ ] For MVP, Schedule an appointment link should point to ...
- [ ] Post MVP, veteran should be able to see next upcoming appointments
-- [ ] Discovery on specific information what specific information would be helpful to veteran -- consider newest / upcoming based on other work on dashboard (prescriptions and secure message) (samara working on dashboard redesign
--- [ ] Show details of "your next appointment"

**Comment by laurenernest** [comment]
Covered by Authenticated Experience team
