### ISSUE TITLE
Vets-api terminal access for Kevin Suarez

### ISSUE THREAD

**Issue by kjsuarez** [department-of-veterans-affairs/va.gov-team#60449]
### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Kevin Suarez

### Your GitHub handle (terminal access is managed through GitHub)

kjsuarez

### Team, Role, and Company of the target individual

Benefits Debt Resolution, Backend Engineer, Agile6

### Product Manager (PM) name and email

Tom Davis, Thomas.Davis@govcio.com

### Product Owner (PO) name and email

Matt Self, Matthew.Self2@va.gov

### Your dsvagovcloud AWS user name (if applicable)

Kevin.Suarez

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [ ] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### COR Name (leave "None" if you listed an AWS user name above)

None

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

None

### Access Expiration

01-12-23

### Additional Notes

I'm requesting prod access specifically so I can hit the Prod VAProfile API.

### User must exist in a roster before vets-api terminal access can be granted

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added
- [ ] If they included an AWS user name, check to see if their user name is listed in [iam_users.tf](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf)
- [ ] Comment in this issue saying which roster the user is listed in and confirming their AWS user name (if applicable)

**Comment by ryan-mcneil** [comment]
User found in VFS Team Roster ✅ 

@BillChapmanUSDS Found users's eQIP Transmittal Email details in his [AWS request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/57427)

**Comment by BillChapmanUSDS** [comment]
This seems to be more of a systems / integration type request and not a specific AWS user access.  What is the minimum access required to provide this ability? 

"I'm requesting prod access specifically so I can hit the Prod VAProfile API."

**Comment by ryan-mcneil** [comment]
@kjsuarez Bill makes a good point. Can you please clarify why Rails console access in production helps you solve your specific issue?

**Comment by BillChapmanUSDS** [comment]
If @kjsuarez  can provided the detail requested we can allow a 6 month expiring access. Otherwise I will allow 3 months with a note that this might not be allowed in the next policy go around.

**Comment by kjsuarez** [comment]
As a backend developer working on vets-api I (and my team members) will sometimes encounter situations where logging does not sufficiently reveal the full nature of a production problem caused by data propagated by upstream production systems. In these cases my typical response would be to try to reproduce the problem on a production console, since I would get a different (and sometimes none at all) set of data to work with in a staging env.

**Comment by bdech** [comment]
@BillChapmanUSDS I am including you for visibility on this request.

**Comment by BillChapmanUSDS** [comment]
Access justification approved

**Comment by BillChapmanUSDS** [comment]
Thank You, 6 month access approved.

**Comment by bdech** [comment]
@kjsuarez You've been granted access to `Prod` for 6 months, expiring February 7th.  

Please set a reminder for yourself to return to this Issue and re-request access within 1 week of the expiration date. You'll receive 1 reminder with a 72 hour window to respond. Failure to do so will result in lost access and will require you to fill out a new request.

**Comment by bdech** [comment]
slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1691502524404729)

**Comment by bdech** [comment]
@kjsuarez  Your Vets API Terminal Production access has expired.

Would you like to request an extension? You have 72 hours to respond, or your 
access will be revoked and you will need to fill out a new request.

**Comment by kjsuarez** [comment]
Yes please I would very much like an extension.

**Comment by bdech** [comment]
@LindseySaari @ericboehs can one of you please give us a :thumbsup: to extend their access?

**Comment by bdech** [comment]
@kjsuarez your vets-api Production access has been extended for 6 months, expiring 08/08/24. 

Please set a reminder for yourself to return to this Issue and re-request access within 1 week of the expiration date. You'll receive 1 reminder with a 72 hour window to respond. Failure to do so will result in lost access and will require you to fill out a new request.

**Comment by bdech** [comment]
support slack reminder [here](https://dsva.slack.com/archives/C06CY71PCAX/p1707423491083579)
