### ISSUE TITLE
[BE] Notification Center: Implement support for new FE functionality

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#60454]
## Background
We need to make some minor BE updates to support the new FE for notification center. This effort is broken into two tickets, this ticket for feature flag set up and support for display dismissed notifications in the NC, and [60639](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60639) to support pagination.

## Tasks
- [x] Create feature flag for notification center mvp (including 'global' flag as it's a new app - see notes from Adam in the Resources section below)
- [x] Add support to include dismissed notifications when given a flag (e.g., GET v0/onsite_notifications?dismissed=true)

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ @adamwhitlock1 
- _How can this work be validated?_ ... 

## Resources
- [Technical discovery: Notification Center MVP](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/onsite-notifications/notification-center-mvp/engineering/technical-discovery.md#backend-be)
- [Adam's notes on "global" flag needed for new applications](https://dsva.slack.com/archives/C909ZG2BB/p1686952264176109?thread_ts=1686948691.655719&cid=C909ZG2BB)

**Comment by adamwhitlock1** [comment]
Do we know of a test user that has multiple dismissed / undismissed notifications?

**Comment by tpharrison** [comment]
@dellerbie I tried adding a few notifications to vets.gov.user+11@gmail.com.  The user has a total of 8 notification; 6 of which have been dismissed.

I tried testing querying the endpoint using postman with the `include_dismissed` parameter set to 'true', but it still only returned 2 records.  

Let's sync up and discuss further.

**Comment by tpharrison** [comment]
@dellerbie Tested with [vets.gov.user+11@gmail.com](mailto:vets.gov.user+11@gmail.com).  Querying the endpoint using postman with the `include_dismissed` parameter set to `true` returned all 8 records records.

Everything looks good!

**Comment by adamwhitlock1** [comment]
@dellerbie I tested via postman with user 228 and was also able to retrieve all dismissed and non-dismissed notifications with the query param. Looks good to me too!
