### ISSUE TITLE
Design: Iterate on experience around "Community Care" from updated MHV landing page

### ISSUE THREAD

**Issue by jonathanjnelson** [department-of-veterans-affairs/va.gov-team#60479]
# Overview
We met with Danielle Thierry as part of [this ticket](https://app.zenhub.com/workspaces/mhv-on-vagov-top-level-view-62619a987d74510018ecc546/issues/gh/department-of-veterans-affairs/va.gov-team/58904) to better understand the history and future of the term Community Care and work being done around a couple of issues that came up in [recent landing page usability testing. ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/landing-page/research/2023-03-Landing-Page-User-Research/2023-04-landing-page-readout.md)

## Acceptance Criteria
- [x] Design and document a potential solution to help address users understanding of the "Community Care" link on the landing page  
- [x] Share solutions with Danielle Thierry and content team 
- [x] Integrate feedback into designs 
- [x] Share with Cartography team

**Comment by A6-toma** [comment]
If Jonathan is not the one to take up this ticket, need to include some KT.

**Comment by jonathanjnelson** [comment]
Notes from initial meeting with Danielle Terry: 

- They are working on all the Community Care websites/content over to VA.gov.
- Danielle shared the drupal preview pages document 
- When asked about term - in her SEO research, no alternative terms emerged really 
- Quick solutioning (one min): Maybe there needs to be two separate links on the landing page? One for Eligibility/enroll and one for how to make a community care appointment? for the two audiences

**Comment by jonathanjnelson** [comment]
Quick white board session: ![Screenshot 2023-07-19 at 1.58.50 PM.png](https://images.zenhubusercontent.com/5df3ac60534bc19675f4ca43/07f4c0fa-14b1-4414-ba17-04b783bbc85f)

**Comment by jonathanjnelson** [comment]
Potential helpful studies to understand Community Care (provided by Peter Russo): 

- [CC provider selection usability study](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/research/2020-10-cc-provider-selection-usability/research-findings.md) - all but 1 participant was familiar with Community Care
- [CC Manager Research](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/community-care/CCM%20Research%20Findings.pdf) - a staff study done in collab with the facilities team, but may be helpful to understanding the process

**Comment by jonathanjnelson** [comment]
Additionally info from Danielle Terry seen on this thread: https://dsva.slack.com/archives/C04DRS3L9NV/p1689801010090999?thread_ts=1689778656.425519&cid=C04DRS3L9NV 

Surfacing this info from thread: I think these are likely the 2 pages that are most likely the most helpful to point folks to to capture those 2 audience needs:

- For folks not already using community care: [Eligibility for community care outside VA](https://www.va.gov/resources/eligibility-for-community-care-outside-va/)
- For folks using community care: P[robably How to get community care referrals and schedule appointments ](https://www.va.gov/resources/how-to-get-community-care-referrals-and-schedule-appointments/)because it's the most general information. Though you'll see in the audit that urgent care is the most access page on the legacy site. Here's the modernized "how to get urgent care" page.

**Comment by jonathanjnelson** [comment]
Submitted intake ticket for [Content and IA team](https://github.com/department-of-veterans-affairs/va.gov-team/issues/62725)

**Comment by LynneJohnson224** [comment]
Tkt blocked - waiting for update/movement on CAIA ticket

**Comment by jonathanjnelson** [comment]
Please see the [content ticket here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/62725#issuecomment-1678380263). The [desktop mocks here](https://www.sketch.com/s/f9050748-823b-4245-98c9-e9738c15a271/a/j4oVxeW) and  [Mobile mockups here](https://www.sketch.com/s/f9050748-823b-4245-98c9-e9738c15a271/a/dg1rxdE)

**Comment by jonathanjnelson** [comment]
Please see [64372](https://app.zenhub.com/workspaces/mhv-on-vagov-top-level-view-62619a987d74510018ecc546/issues/gh/department-of-veterans-affairs/va.gov-team/64372) for FE work
