### ISSUE TITLE
Migrate technical architecture overview doc to new repos

### ISSUE THREAD

**Issue by gunsch** [department-of-veterans-affairs/va.gov-team#6047]
https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/TechnicalArchitectureOverview.md

I believe this doc got migrated to va.gov-team, then had to be deleted (non-public). Could this be migrated to va.gov-team-sensitive?

**Comment by meganhkelley** [comment]
PR to merge docs into sensitive repo https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/55
