### ISSUE TITLE
Make search results insensitive to trailing and leading whitespace

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#6048]
A query for ` health care ` should produce the same results as a query for just `health care`. However, currently, this affects our search results. We should update the behavior of the Lighthouse Forms API to strip trailing and leading whitespace to achieve this behavior.

## Acceptance criteria
- [ ] Queries with leading and/or trailing whitespace produce the same search results on our search tool, https://dev.va.gov/find-va-forms-beta/

**Comment by MickinSahni** [comment]
- awaiting PR review

**Comment by AkucherGCIO** [comment]
@ncksllvn - Is this ready to be closed since PR has been merged.

**Comment by AkucherGCIO** [comment]
2020-26-02
@ncksllvn - It looks like  #5693 is the technical task for this story.  If so, this can be closed out.  Agree ?

**Comment by ncksllvn** [comment]
Yep! Closing -

![image](https://user-images.githubusercontent.com/1915775/75358169-74642600-5880-11ea-8056-5a7029dc4fa4.png)
