### ISSUE TITLE
Remove "First Issued On" property from API

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#6050]
The "First Issued On" property was deprecated in the Lighthouse Forms API, now always returning a `null` value. We need to update our middleman API route to reflect these changes in order to resolve the server error we're seeing - 

![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/c6e0d921-a954-4d40-adc2-f227e188d71a)

### Acceptance criteria
- [ ] We no longer encounter a server error when searching on https://dev.va.gov/find-va-forms-beta/

**Comment by MickinSahni** [comment]
- adding to sprint 15 as unplanned, waiting for PR review

**Comment by ncksllvn** [comment]
PR merged! The search widget on http://preview-prod.vfs.va.gov/preview?nodeId=2352 should be back up and running after 3 PM today.

**Comment by AkucherGCIO** [comment]
2020-26-02
@ncksllvn - Can this be closed since PR has been merged ?

**Comment by ncksllvn** [comment]
@AkucherGCIO yep! You can see that the property name is removed from the docs here, https://department-of-veterans-affairs.github.io/va-digital-services-platform-docs/api-reference/#/forms/getForms
