### ISSUE TITLE
[686c] RBPS Re-Processing Phase 5 | Prepare for Reprocessing 

### ISSUE THREAD

**Issue by HeatherWidmont** [department-of-veterans-affairs/va.gov-team#60536]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)

## High Level User Story/ies
As Team Tree, I need to Prepare for Reprocessing so I can proceed with reprocessing null 686 claims.

## Hypothesis or Bet
**If** prepare for reprocessing **then** we can move to the initial rounds of reprocessing.

## Description
Once we know the extent to which RBPS will be able to reprocess previously failed claims (Phase 4), we will need to write reprocessing code that will leverage our existing claim submission code but ensure that logging, emails to veterans, and perhaps more, are handled appropriately and distinctly from ordinary claim submissions.  Depending on what we discover during RBPS testing, we may also have to write code to refrain from processing null claims we have determined are ineligible for RBPS reprocessing.  We will also have to coordinate with RBPS on a reprocessing plan.

### Best Case - 2 Days
In the best case, we would be able to leverage most of the code we previously wrote, and RBPS testing would not have revealed any complicated limitations around what we can and cannot process, or how we need to process different kinds of claims.

### Expected - 3 Days
Eugene expects that we will have to make some slight modifications to our code or do a little bit of work to work around limitations discovered during RBPS testing.

### Worst Case - 2 Weeks
In the worst case, RBPS testing would have revealed severe consequences for reprocessing certain kinds of claims, and we would be forced to write complicated code to avoid those consequences.

[[Link to full RBPS Re-Processing Estimates Doc](https://docs.google.com/document/d/1a41sVMaWsVBI0HWyOsqonDdSK547p6qQ8hNf3t7NRMU/edit)](url)

## OKR
_Which Objective / Key Result does this epic push forward?_

### What must be true in order for you to consider this epic complete? 

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

**Comment by steele-lm** [comment]
Closing as null claims will no longer be processed through RBPS.
