### ISSUE TITLE
[686c] RBPS Phase 2 | Prepare CSVs for Reprocessing

### ISSUE THREAD

**Issue by HeatherWidmont** [department-of-veterans-affairs/va.gov-team#60532]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)

## High Level User Story/ies
As Team Tree, I need to prepare the CSVs so I can proceed with reprocessing null 686 claims. 

## Hypothesis or Bet
**If** we prepare the CSVs for preprocessing **then** we can move onto preparing for RBPS Testing. 

## Description
Once we have a spreadsheet of all null claims, we will need to extract the information necessary for preprocessing, order the rows by date, and then split the spreadsheet into several 500 row CSVs. If we end up using Matt B.'s report, there will be a small handful of unprocessable rows that we can off-ramp for manual establishment. 

### Best Case - 4 Hours
Assumes that developer tools exist on the VA remote Windows desktop, and that these tools are easy enough for a Mac developer to learn and use. 

### Expected - 1 Day
I expect that I will have some difficulty with the Windows environment, but will be able to figure out how to do what I would typically do on a Mac machine relatively quickly. 

### Worst Case - 3 Days
Assumes that working on the remote Windows desktop is a complete nightmare, so much so that I am forced to do something like use a largely manual process in a VA staging console. 

### Dependencies
None. 

[[Link to full RBPS Re-Processing Estimates Doc](https://docs.google.com/document/d/1a41sVMaWsVBI0HWyOsqonDdSK547p6qQ8hNf3t7NRMU/edit)](url)

## OKR
_Which Objective / Key Result does this epic push forward?_

**Comment by steele-lm** [comment]
Closing as null claims will no longer be processed through RBPS.
