### ISSUE TITLE
[686c] RBPS Re-Processing Phase 7 | Additional Rounds of Reprocessing and Handoff to OFO

### ISSUE THREAD

**Issue by HeatherWidmont** [department-of-veterans-affairs/va.gov-team#60539]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)

## High Level User Story/ies
As Team Tree, I need to do additional rounds of reprocessing so I can handoff to OFO.

## Hypothesis or Bet
**If** we do additional rounds of reprocessing and handoff to OFO **then** we will be done with RBPS Re-Processing.

## Description 
As mentioned earlier, some portion of the claims we attempt to reprocess will fail again.  This phase is dedicated to understanding why these claims failed and attempting to reprocess them again.  Any claims that we determine cannot be reprocessed through RBPS will be passed off to OFO to be manually processed.

It’s very difficult to predict how many of these claims will fail, and to what extent they’ll be retriable.  Additionally, Eugene imagines that once we get to this point, we will want to reconsider whether to continue reprocessing through RBPS or pass the baton to OFO for manual establishment.  For instance, if 60% of claims were successfully reprocessed and it looked like it was going to be very difficult to reprocess any more claims, we may consider shifting the burden to OFO.  Or, if only 40% of claims were successfully reprocessed but it looked like another 25% could be reprocessed with a few minor tweaks to our code and process, we may consider continuing our reprocessing efforts.  For these reasons, Eugene will not provide estimates for this phase of work.

[[Link to full RBPS Re-Processing Estimates Doc](https://docs.google.com/document/d/1a41sVMaWsVBI0HWyOsqonDdSK547p6qQ8hNf3t7NRMU/edit)](url)

## OKR
_Which Objective / Key Result does this epic push forward?_

### What must be true in order for you to consider this epic complete? 

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

**Comment by steele-lm** [comment]
Closing as null claims will no longer be processed through RBPS.
