### ISSUE TITLE
Update Spotlight Links - June 2023

### ISSUE THREAD

**Issue by A6-toma** [department-of-veterans-affairs/va.gov-team#60544]
Here are the current three featured on the homepage:

[Five Exercises for Balance](https://www.myhealth.va.gov/mhv-portal-web/ss20210707-better-balance-standing-exercises)

[PACT Act Special Enrollment Period](https://www.myhealth.va.gov/mhv-portal-web/ss20230428-pact-act-special-enrollment)

[Get Back to Sleep](https://www.myhealth.va.gov/mhv-portal-web/ss20190321-path-to-better-sleep/)

**Comment by radavis** [comment]
Superseded by #60940. Closing.
