### ISSUE TITLE
[identity-dashboard-ui] Create ECR repo

### ISSUE THREAD

**Issue by rileyanderson** [department-of-veterans-affairs/va.gov-team#60566]
## Issue Description
Create ECR repo for `identity-dashboard-ui`

## Devops tasks
- [x] add `identity-dashboard-ui` to `ecr.tf`
- [x] add permissions to the `gha_identity_user` to push and pull from repo

## Acceptance Criteria
- [x] ECR repo successfully created
- [x] Github user able to push and pull

**Comment by aparsley** [comment]
Looks great, keep up the good work!
