### ISSUE TITLE
engineering milestone list

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#60573]
Create list of objectives and milestones to share with product and UX.

**Comment by aparsley** [comment]
Current Initiatives for Product/UX:

Video recording for verification guide
Edit video- Clayton
Mocked auth research with devs
Identity dashboard usability research
Research plan for video
Product briefs - finish and add to github
TOU ux related tasking - meet with Tom, research on UX and flow

**Comment by joeniquette** [comment]
https://docs.google.com/spreadsheets/d/1dk-bVAaLjgQYLaBE3JC6ZGLVDB9WxJcVjQy7ZqpAxkg/edit#gid=0

**Comment by joeniquette** [comment]
Ready to be shared with PM leadership

**Comment by aparsley** [comment]
Approved, thank you.
