### ISSUE TITLE
[Dev/BE] Determine Enrollment System (ES) data requirements for online EZR info

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#60588]
As a Veteran, I would like to update my Financial Disclosure information online without filling out an entire 10-10EZR paper or digital form so that I can make sure I don't have to pay co-pays and don't have to fill out a bunch of information the VA already has. 

- Talk to Faulkner about what information is required on the back end to make changes to ES for information currently associated with EZR
- Determine how we can make it so that user only has to change the field they want to change, not _all EZR required fields_
- Determine if we need a user to "review" the other required data fields for EZR
- Determine if a user simply being logged in and _not changing_ the other required fields is sufficient to make an EZR change in ES
- Determine if changes based on Financial Disclosure are all automated or require human intervention 
- Determine status of ES modernization and modularization and come up with how (if at all) this will impact Financial Disclosure and future EZR online functionality
- Help Alex come up with implementation stories

**Comment by lihanli** [comment]
just to be clear we want to allow a user to update only section IV and section V of the [1010ezr](https://www.va.gov/vaforms/medical/pdf/va%20form%2010-10ezr.pdf) on the profile page?

**Comment by lihanli** [comment]
> Determine if changes based on Financial Disclosure are all automated or require human intervention  

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/830084/dac6ae26-e591-4737-8ebb-7b82c87e7f36)

**Comment by lihanli** [comment]
@alexseelig logged in identity verified users can update only the financial fields, but only if they are already enrolled. the enrollment & eligibility can tell us if a user is already enrolled or not.
