### ISSUE TITLE
[Epic] Research Financial Disclosure and Priority Group on VA.Gov Profile

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#60584]
## Background
The 10-10EZR form is used by Veterans to update their information in their VA Profile. This information includes: mailing address, phone #, SIGI information, Dependents, Insurance, Next of Kin, Emergency Contact, insurance information, and Financial Disclosure. 
The HEC and VEO stakeholders have requested an online 10-10EZR form. While doing discovery for this request, the team learned that there are roughly hundreds of thousands of EZRs filed every year, that some information editable via the paper EZR can be change via the VA.Gov profile, and that the primary purpose for the EZR is to update Financial Disclosure--a capability that is not currently online. 
This team needs to research if Veterans would like to have the capability to review/update financial information online, as well as the ability to view their Priority Group and what it means to them, and if so how and where this capability should "live." 

### Resources
- [Epic](https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/57417)
- 10-10EZR paper form PDF (attached)[https://app.zenhub.com/files/133843125/648d269f-69ef-425b-bd82-a78b6af9c7d1/download](https://app.zenhub.com/files/133843125/648d269f-69ef-425b-bd82-a78b6af9c7d1/download) 
- [Research Plan Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-plan-template.md)
- Overview of EZR form fields and VA.Gov profile fields (attached)[https://app.zenhub.com/files/133843125/adacb673-4c31-4c71-b236-229cf55a5c3d/download](https://app.zenhub.com/files/133843125/adacb673-4c31-4c71-b236-229cf55a5c3d/download) 

### Financial Disclosure Use Cases

- Learn more about how Veterans would like to go about applying, discovering eligibility and getting the most health care benefits they qualify for and what amount of information they feel they need to provide vs what VA should have in that process.
- Learn more about how Veterans would like to go about providing updated information, especially financial and dependent updates, that could impact their health care benefits post-application/initial enrollment.
- as a 0% SC veteran with one dependent who earned $15K last year, i may need to file an annual financial disclosure, so i can maintain access to beneficiary travel
- As a 0% SC veteran with one dependent who lost their $55K/year job and now has no income and was previously assigned to PG 8, i want to file a new financial disclosure, so i can access the medical benefits package under PG 5, be exempt from medication copays, and be reimbursed for my travel expenses.
- As a 20% SC veteran with one dependent who earned $15K last year, i may need to file an annual financial disclosure, so i can maintain access to beneficiary travel
- As a 30% SC veteran who recently enrolled in medicaid, i want to tell VA that im now enrolled in medicaid, so i can access medication copay exemption

### Priority Group Use Cases

- Learn more about Veteran's mental model when applying for health care benefits including the terms they use and how they see levels of benefits/Priority Groups/copays impacting them during the health care application process, during and ongoing after.

### Outstanding Questions

- Do Veterans want this?

### Acceptance Criteria

- Write Research Plan
- Write Conversation Guide
- Review these with VA.Gov Profile Team
- Put in request with Perigean
- Schedule interviews
- Conduct interviews
- Do Research Results write up 

Break into three tickets:

- Research Planning
- Schedule and conduct interview
- Synthesis

**Comment by hdjustice** [comment]
Does this need to be an epic? (currently a 'story')
