### ISSUE TITLE
Add a new feature toggle for the GA4 events migration 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#60596]
## Item Description
We will need to create a feature toggle to update the tracking events to Google Analytics 4. 

---

## Tasks
- Add `va_online_scheduling_GA4_migration` feature toggle

## Acceptance Criteria: 
- [ ] The toggle is created for VAOS

## Definition of Done
- [x] All acceptance criteria are met
- [x] [Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/product/feature_toggles.md) is updated
---

**Comment by ldelacosta** [comment]
@young1205 - please notify @JRRoof to validate

**Comment by simiadebowale** [comment]
@young1205 - don't forget to update the [documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/product/feature_toggles.md)

**Comment by young1205** [comment]
Documentation updated and now deployed to staging. @JRRoof this is now ready for validation

**Comment by ldelacosta** [comment]
Validated the changes in staging. No issues to report. Closing out the ticket. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdFJ6IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1a31ba36867869dd2f642e407c2287dcc5191f61/Screenshot%202023-09-06%20at%203.48.46%20PM.png)
