### ISSUE TITLE
Identity Dashboard (FE) - Dockerize application

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#60606]
## Description
Set up the Identity Dashboard FE to have a Dockerfile to allow uploading to AWS ECR for Riley to enable Kubernetes support

## Tasks
- [x] Add a Dockerfile
  - [x] Ensure Dockerfile runs appropriately
- [x] Add docker-compose sample to allow network share within Pods

**Comment by aparsley** [comment]
Thank you for adding the Dockerfile and checking it runs.
