### ISSUE TITLE
Switch to using account_id for MVI cache indexing

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/va.gov-team#6061]
See #5290 for context - using user.uuid (aka ID.me UUID) is not reliable going forward, so we want to switch to keying the MVI redis cache insertion/lookup on user.account_id instead.

There are existing records using user.uuid, but as it's a cache we are probably relatively safe to just start using account_id.

One wrinkle is that the account_id is established (if it doesn't already exist for a user) in the `AfterLoginJob` which may be invoked after the MVI lookup. We may need to re-jigger this; if account_id becomes more central it may not do well to establish it in an async job since other API invocations will expect it to be present.

**Comment by ericbuckley** [comment]
@patrickvinograd does this class also need to be converted to support `User.account.uuid` lookups?  https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/vet360_redis/contact_information.rb#L179

**Comment by ericbuckley** [comment]
closing in favor of #7110
