### ISSUE TITLE
Investigate dynamic content in emails

### ISSUE THREAD

**Issue by alevindecanini** [department-of-veterans-affairs/va.gov-team#60610]
We want to be able to dynamically refer to the user's modern credential: Login.gov or ID.me. We need to investigate the feasibility of this. 
Per Jesse:
- After-login action provides user's record
- We can pass attributes (ie firstname) from that record in the API call to VA Notify
- Special parts of the template (double square brackets) will populate that content

Draft content here:
https://app.zenhub.com/workspaces/logingov-adoption-team-632280b31e745000136a61fc/issues/gh/department-of-veterans-affairs/va.gov-team/60610

Acceptance Criteria:
-

**Comment by alevindecanini** [comment]
Content copied from this [Figma file](https://www.figma.com/file/8vobVoSl1UqLnXsni3rcvO/Login.gov-Adoption%3A-Design-Flows?type=design&node-id=2316%3A4026&mode=design&t=xaSN7mLfi8SsU9Q9-1) - @CarlDickerson @MOStudioCarolyn can you confirm that this is correct?

----

Dear [Name],

We’re sending this email to help you prepare for changes to how you sign in to VA websites to manage your health care and benefits. 

As we move toward a more secure sign-in experience, we ask that from now on you sign in using your Login.gov or ID.me account. Login.gov and ID.me meet our new stronger security requirements and will give you access to all the same information and services you use today with [MHV/DSL]. Our records show that you already have a [Login.gov/ID.me] account that you have used to sign in with in the past. Follow the link below to sign in now. 

Sign in to VA with [Login.gov/ID.me]

We’re here to help

Visit https://www.va.gov/initiatives/sign-in-securely-with-logingov/ to learn more about Login.gov and the changes that are coming to the sign-in process. If you have a technical issue while you’re trying to sign in, call our My VA 411 main information line at 800-698-2411. We’re here 24 hours a day, 7 days a week.
```

**Comment by holytoastr** [comment]
@CarlDickerson @MOStudioCarolyn Can you confirm that the user should see `MHV` or `DSL` and not `MyHealthyVet` or `DSLogon`?

**Comment by alevindecanini** [comment]
@holytoastr the user should see `MyHealtheVet` or `DSLogon`, not the acronyms we use internally.

**Comment by holytoastr** [comment]
Keys to use in template:
`name` => [Name],
`legacy_credential` => [MHV/DSL],
`modern_credential` => [Login.gov/ID.me]

**Comment by alevindecanini** [comment]
Once related tickets (#59073, #59765, #59074) are merged, Melissa will rebase the code to be up to date. It's otherwise tested, cleaned up, and ready to go. Others will be able to use these keys going forward.
