### ISSUE TITLE
[Discovery] Priority Group Discovery and Desk Research

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#60620]
As a Veteran, I would like to be able to view my Priority Group (PG) online and understand what it means for me so that I make sure I am getting the most out of my VA healthcare benefits.

- Review current [VA.Gov PG page](https://www.va.gov/health-care/eligibility/priority-groups/#:~:text=We%20assign%20the%20lowest%20priority,disability%20compensation%20(monthly%20payments).)
- Conduct desk research on research previously done on PG
- See if you can find any other explainers, guidelines, or other information on PG (might be good to reach back to Pittsburgh to see if they have any training materials on this)
- Come up with an overview (can be informal) of PGs and initial proposal/hypothesis for what should exist online that currently doesn't

**Comment by jessicastump** [comment]
The Mural board can be our source of truth for this info.
- [Some links to VA.gov existing pages ](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1687381992402/ac027de3375351079c9cbc93d1662510ffd3cb1a?wid=0-1687444730001&outline=open)
- On the current content board is also a link to a Welcome folder that Kristen shared with us. Initial discovery research suggests this Welcome letter and packet (which can vary by Facility) is where the PG is communicated to the Veteran
- [Research Repo Findings](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1687381992402/ac027de3375351079c9cbc93d1662510ffd3cb1a?wid=0-1687382001518&outline=open)

**Comment by hdjustice** [comment]
@jessicastump - is this the ticket you were thinking of?

**Comment by jessicastump** [comment]
I was thinking of this [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60690) @hdjustice .

**Comment by hdjustice** [comment]
Closing ticket.  Desk research & discovery done in Mural board linked above.  Any further work will be captured under the #60690 research ticket.
