### ISSUE TITLE
[Epic] 10-10EZR: Make Financial Disclosure available online

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#60634]
**AS 6/21: Will inquire with Patrick about whether we're just doing Section IV of EZR or IV and V, right now lets assume IV 
10-10EZR: [https://app.zenhub.com/files/133843125/baaa8a3f-5881-4f3b-9f49-35c7bc83ad4e/download](https://app.zenhub.com/files/133843125/baaa8a3f-5881-4f3b-9f49-35c7bc83ad4e/download)
EZR paper form vs. VA.Gov Profile: [https://app.zenhub.com/files/133843125/ff2d53fb-801d-46a7-91ca-1e972647731b/download](https://app.zenhub.com/files/133843125/ff2d53fb-801d-46a7-91ca-1e972647731b/download).**

## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)

## High Level User Story/ies
As a Veteran, I would like to be able to update my VA Financial Disclosure information online so that I don't have to pay co-pays if I'm not required to.

As a Veteran, I would like to update my financial information online so that I can get more of my healthcare through the VA without having to go through my State's Medicaid program.

As a _____, I need _____ so I can _____. (template)

## Acceptance Criteria
- Discussions are held with VAMC staff to determine most common use(s) of 10-10EZR paper form
- Research is done with end users (Veterans) to determine if they would like to update their financial disclosure information online
- Research is done with Veterans to determine how and where they would like to update their financial information online
- Ensure that we can legally display a Veteran's existing financial information online (namely if it comes from the IRS)
- Allow Veteran to view their financial information online
- Allow Veteran to edit their Financial Information online
- Ensure Financial Information updated by a Veteran online goes to the ES the same way a paper change would
- Ensure that any downstream effects (e.g. change of Priority Group) is the same as what is done with the paper form
- Collaborate with VA.Gov Profile Team on how to implement Financial Disclosure online
- Build solution
- Test and submit for collaboration review
- Create training guide(s)
- Release 

## Hypothesis or Bet
**If** we allow Veterans to view and update their financial disclosure online, **then** _we expect that far fewer of the hundreds of thousands of paper 10-10EZRs filed per year will be necessary_.

**If** we allow Veterans to view and update their financial disclosure online, **then** _we expect that more Veterans will be able to get the care they're entitled to because it is so much easier to update their financial information_.

## OKR
_Which Objective / Key Result does this epic push forward?_ (Template)
- Reduction in paper EZRs
- Veterans will be updating their financial information online instead of via paper EZR or during their office appointments

### What must be true in order for you to consider this epic complete? (template)
A Veteran can view and edit their financial information online

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `Console-Services`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by emily-brown34** [comment]
Does this include Financial Disclosure AND Priority Group or just FD?
Cause we have another epic https://github.com/department-of-veterans-affairs/va.gov-team/issues/60603 for Priority Group
