### ISSUE TITLE
Design Intent  - IA Feedback - Disability Benefits Experience Team 1, 21-526EZ, Toxic Exposure Page

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#60631]
## VFS actions
- [x] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- This is a tricky one and I agree the 526 deserves some out-of-the box thinking considering its size. One thing that would probably be helpful for you all, is to draw out the user flows. You provided what I would call a form flow at design intent (showing us the high-level steps of the form and which pieces are changing), but I didn't see user scenarios and how users flow through it. What are all the possible user scenarios? I'd love to better understand which conditional questions trigger which other portions of the form. Which of those conditionals are introducing significant time burdens? How common are those paths? I encourage you to fill out a [Sitewide CAIA ticket ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=RLHecht%2C+coforma-terry&labels=sitewide+CAIA%2C+sitewide+content-product+support%2C+Sitewide+IA%2C+sitewide+content%2C+sitewide+accessibility&projects=&template=sitewide-content-intake-form.md&title=%3CType+of+Request%3E+from+%3CTeam%3E)and request IA help to map some of this out. // cc @kristinoletmuskat & @jennymayoco

- In terms of batching the questions, I like the idea of A/B testing some options with Veterans in user research as I definitely agree that for this form, less new pages may be better if the cognitive load is not problematic for users. Cognitive load of individual page vs. cognitive load of entire form is a tough battle to weigh. I don't know that there are great answers, but you're on the right track. Keep it going!

- The digitize forms team is doing interesting work with some of their forms where they ask conditional questions upfront (it comes after the OMB estimation, but before the form itself & any step indicator appears) - these trigger specific form layouts based on the user's answers. It may be worth connecting with them to explore that - reach out to @jeana-adhoc @PSIEBENLIST // cc @humancompanion-usds 

- I'll echo @allison0034 suggestion to explore some UI options that may give users more context into what is to come. I also think the new segmented progress bar with chapters is much improved and will impact users' understanding of where they are in the form and how much further they have to go.

**Comment by lydiahooper** [comment]
Sitewide CAIA has already helped us with creating a sitemap that 526 team 2 is working to keep up to date - here is most current version

The conditional questions upfront is what we've had in place for BDD flow in 526, but if you recall we are currently past midpoint for the redesign of that since it's not an ideal experience (I suspect the difference being that 526 requires authentication and some other forms don't.).

We do plan to do some A/B testing for this epic, and hope to tackle navigational issues more broadly in a future epic. Thanks!

**Comment by kristinoletmuskat** [comment]
Hey @lydiahooper -- I know you closed this issue but I just wanted to link to the mural for Sarah (you mentioned it above but the link didn't come through): https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1686768383603/3f4415dd2ddb71bbd104ebefd92a2c7b553ad792?invited=true&sender=ua67f17f1c416a96ea04d2476

I was chatting with Sarah earlier and we went over the awesome diagrams ya'll have been building off of. She mentioned that the "Simplified Form Flow" in the mural with the decision points was exactly what she was talking about (seeing how the question impacts the user experience with conditional questions/branching/etc. I think it would be awesome if we could keep the simplified flow updated as well, and I saw that ya'll said it was on pause for the moment. Is there anything we can do to support in updating that diagram?

**Comment by lydiahooper** [comment]
I'm glad to hear this is continuing to be useful @kristinoletmuskat ! Copying @juliepedtke as she's been the one leading/working on this, so hopefully she can follow up to answer your question.

**Comment by sterkenburgsara** [comment]
Thanks @kristinoletmuskat for the link - I didn't realize you all had done such thorough user flows for the 526 before we chatted! @lydiahooper this "simplified form flow" that Kristin put together is very helpful - it abstracts the form from the UI and helps me understand which sections are the largest & where the 526 is affected by this toxic exposure work. Definitely let Kristin know if they can help make that diagram more useful so that it serves your team well! 

See you later today 👍

**Comment by juliepedtke** [comment]
I've set up some time for us to connect with @kristinoletmuskat to discuss! Thanks all.
