### ISSUE TITLE
Add link to Schedule a Burial checklist in Burials hub

### ISSUE THREAD

**Issue by AnneHurley** [department-of-veterans-affairs/va.gov-team#6063]
## User Story or Problem Statement
As a family member of a deceased Veteran, I need to know what I have to have ready to schedule a burial.

---
## Task
[ ] add Schedule a Burial checklist link [[[https://www.cem.va.gov/cem/pdf/NCA_NCSO_BeforeYouCallChecklist_Sep2019.pdf]]]
to this page: https://www.va.gov/burials-memorials/schedule-a-burial/
In the subway map.

**Comment by AnneHurley** [comment]
@RLHecht  @jenniferlee-dsva  I added a link to the PDF in the subway map. The page already lists a lot of docs that people might need or use, but I thought if we added it in that first step after the 2 mandatory things, it might be all right. Q - would you tighten the spacing? Add bullets? 
Preview: http://preview-prod.vfs.va.gov/preview?nodeId=861

Otherwise this is ready for you both to review and give feedback on. Once we've updated everything it's then ready to send to the Burials team.

**Comment by RLHecht** [comment]
@AnneHurley @jenniferlee-dsva I just reviewed your changed. I added (PDF) after the link and fixed the spacing so it matched how we had it on the live site before adding the third link. I don't think we need them as bullets but I defer to Jen. 
Preview: http://preview-prod.vfs.va.gov/preview?nodeId=861

**Comment by AnneHurley** [comment]
@RLHecht Thanks much for the edits, and agree we don't really need bullets. At some point can I ask you how you tightened up that spacing? thx!

**Comment by jenniferlee-dsva** [comment]
Looks good, thank you both!

**Comment by AkucherGCIO** [comment]
02-26-20
@jenniferlee-dsva @AnneHurley @RLHecht - Is this ready to be closed out ?

**Comment by RLHecht** [comment]
@AkucherGCIO The work is done on our end but @AnneHurley needs to send it to the Burials team for their review. If they are OK we can publish the page and then close it out once it's validated on the live site. We could put the awaiting feedback label on this if it's easier to keep track of.

**Comment by AkucherGCIO** [comment]
@RLHecht  - Added Awaiting feedback label.  @AnneHurley - Please let us know the feedback from Burials team review so we can close this out.

**Comment by AnneHurley** [comment]
@RLHecht  @AkucherGCIO  - Randi we can go ahead and push this live. I'll send the live link to Burials when it's up.

**Comment by RLHecht** [comment]
This is now published. I will validate later this afternoon that it's live on site and will close ticket then.

**Comment by AnneHurley** [comment]
@RLHecht thanks so much! can you shoot me a quick email when it's up so I can send to the stakeholders. Appreciate it

**Comment by RLHecht** [comment]
This is now live on the site. @AnneHurley this looks like it's not attached to our Public Websites sprint and didn't have an estimate or anything. Before closing, do you want to make sure everything is updated?

**Comment by AnneHurley** [comment]
@RLHecht  Will do, thanks!

**Comment by MickinSahni** [comment]
removing authenticated experience team sprint milestone

**Comment by AnneHurley** [comment]
Added milestone, estimate, sent final email to stakeholders.

**Comment by AkucherGCIO** [comment]
2020-28-02 Standup
Another pdf was sent.  Stakeholders are happy with the placement.

**Comment by AnneHurley** [comment]
@RLHecht  Updated with latest pdf and ready for publish.

**Comment by RLHecht** [comment]
This is published. Will validate after today's deployment.

**Comment by RLHecht** [comment]
@AnneHurley This new PDF looks good on the page. Closing ticket! @AkucherGCIO FYI
