### ISSUE TITLE
[Design] Wireframes for Priority Group

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#60643]
As a Veteran, I would like to be able to view my Priority Group information online so that I better understand my benefits.

- Conduct desk research to see if any has been done about Priority Group on VA.Gov profile, and to see if there are any more insights about VA.Gov Profile that are applicable
- Come up with 2-3 place where Priority Group could live and create wireframe 
     - Including MHV on VA.gov, Per Slack message from Patrick on 6/27/23:
> hey folks! i made a decision to initially put a user’s priority group info on the MHV on [VA.gov](http://va.gov/) landing page ([va.gov/my-health](http://va.gov/my-health)). this definitely does not preclude putting it on [va.gov/my-va](http://va.gov/my-va) (or elsewhere as appropriate) but i wanted to at least get something minimal out in front of users to test the hypothesis that this is a useful bit of data for users to see
- Share wireframe with team for review
- Share wireframe with Kristen and Patrick
- Share wireframe with VA.Gov profile team
- Share wireframe with HEC stakeholders
- Make any requested changes

**Comment by jessicastump** [comment]
An initial [Mural board started here](https://app.mural.co/invitation/mural/departmentofveteransaffairs9999/1687381992402?sender=uadf1ed7fe7c76f0914967329&key=2694912f-19c7-4254-8e86-ce74e6a4bdf0) to use for discovery and gathering links/screen captures/wireframes to visualize the possible options

**Comment by IMHieuVo** [comment]
Here is the [Sketch](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6) file. The wireframes can be found in the Priority Group section.
