### ISSUE TITLE
Additional changes for the appointments events code to GA4 (from Part 1)  

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#60657]
## Description
We recently implemented five appointments events to GA4 (see ticket #58468). We will need to make a couple of modifications.  

---

## Acceptance Criteria
Background: the `va_online_scheduling_GA4_migration` toggle is on

- [ ]  Move the updated GA4 events to the new feature toggle (ticket #60596): 
    - `vaos-cancel-appointment-submission` 
    - `vaos-cancel-booked-clicked` 
    - `vaos-direct-path-started` 
    - `vaos-direct-submission`
    - `vaos-eligibility-direct-check-past-visits-failed` 

- [ ]  Update the custom string format for the following events (similar to the format that was done for `vaos-direct-submission`): 
    - `vaos-cancel-appointment-submission` 
    - `vaos-cancel-booked-clicked` 
    - `vaos-direct-path-started` 
    - `vaos-eligibility-direct-check-past-visits-failed` 

### Design Assets
None

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by JRRoof** [comment]
@jenniemc updated the vaos-direct-submission action for GA4 and we are now seeing correct data coming through for Custom String 1 and Custom String 2.
 ![image.png](https://images.zenhubusercontent.com/61e5d4ebffa2c826e18c07db/8610c6e1-108e-40cf-9755-17f89e34ab18)

**Comment by ldelacosta** [comment]
This is covered in the following tickets: #61346, #61347, #61348, #61349, #61350, #61352, #61353 and #61355. Closing out this ticket.
