### ISSUE TITLE
`check-parameters` GHA can't verify more than 10 parameters

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#60667]
### Summary
I noticed in https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/2050, it said the parameters were valid, but I knew for a fact that some of them hadn't been created yet. So I looked into it and saw there was an error in the action, `Member must have length less than or equal to 10`.

Full error:
`An error occurred (ValidationException) when calling the GetParameters operation: 1 validation error detected: Value '[/dsva-vagov/vets-api/sanbox/token_validation/appeals_status/api_key, /dsva-vagov/vets-api/sanbox/token_validation/contestable_issues/api_key, /dsva-vagov/vets-api/sanbox/token_validation/higher_level_reviews/api_key, /dsva-vagov/vets-api/sanbox/token_validation/legacy_appeals/api_key, /dsva-vagov/vets-api/sanbox/token_validation/notice_of_disagreements/api_key, /dsva-vagov/vets-api/sanbox/token_validation/supplemental_claims/api_key, /dsva-vagov/vets-api/sandbox/token_validation/appeals_status/api_key, /dsva-vagov/vets-api/sandbox/token_validation/higher_level_reviews/api_key, /dsva-vagov/vets-api/sandbox/token_validation/legacy_appeals/api_key, /dsva-vagov/vets-api/sandbox/token_validation/notice_of_disagreements/api_key, /dsva-vagov/vets-api/sandbox/token_validation/supplemental_claims/api_key, /dsva-vagov/vets-api/staging/token_validation/contestable_issues/api_key]' at 'names' failed to satisfy constraint: Member must have length less than or equal to 10`

### Action items
The action should fail if it wasn't able to check all of the parameters. Or maybe it can check them in batches. Or, I'm sure there are other possible solutions to this. No matter the solution, the check should not return a false positive.
- is this coming from a CLI command or GHA command? 
- make sure it is clear that you can have up to 10, but no more than 10 parameters

**Comment by LindseySaari** [comment]
No updates. eMIS is being prioritized

**Comment by laineymajor** [comment]
Moving this to next sprint as we've had to deprioritize.

**Comment by laineymajor** [comment]
@rmtolmach do you think we should kick this back to the CoP?

**Comment by rmtolmach** [comment]
That sounds good @laineymajor, since eMIS deprecation is a priority at the moment. I just unassigned myself.

**Comment by alyssagallion** [comment]
@rmtolmach We good to close this?

**Comment by laineymajor** [comment]
Work will continue on this during our part 2 of the double sprint. Support was a shared schedule amongst the team due to people being out.

**Comment by laineymajor** [comment]
Gia on support, so work might be halted for a bit, but:
Exploring ways to alter logic. Putting this into a PR. Unsure how exactly to test this.

**Comment by jennb33** [comment]
@gia-lexa has PR up, needs to test it a little more on 1/22

**Comment by jennb33** [comment]
@rmtolmach tested this and screenshot. @gia-lexa will merge and close the ticket.
