### ISSUE TITLE
<New Content:Toxic Exposure> from <Benefits Disability Experience 526ez>

### ISSUE THREAD

**Issue by lydiahooper** [department-of-veterans-affairs/va.gov-team#60669]
## About your team
- Team name: Benefits Disability Experience 526ez Team 1
- OCTO-DE product owner: Matt Self
- Product manager: Rakshinda Aslam
- Designer and content writer: Lydia Hooper
- FE engineer: Christine Cereca
- Accessibility specialist: n/a
- Product/team Slack channel:https://dsva.slack.com/archives/C04KW0B46N5
 
### What does your team need support for? Check all that apply.
- [ ] Launching one or more unauthenticated pages, online forms, apps, or tools on VA.gov
- [ ] Making revisions to one or more existing VA.gov pages
- [ ] Accessibility review of wireframes and/or prototypes
- [ ] Accessibility issue (general request)
- [ ] Accessibility PDF review request
- [ ] Accessibility user research support ([submit a separate, additional request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name))
- [x] Something else 
 
### Give a brief description of what your team needs support with:

My team needs support with reviewing new content for new toxic exposure screens to be tested and then added to 526 flow.
These changes are covering:
- Part of updates to make the 526ez digital form current with the new paper version
- Changes to lower the burden for completing these forms by setting expectations and improving information to help the veteran complete the form.

### Will this new product be released incrementally (for instance 25% of users initially)? 
  - [ ] Yes
  - [x] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
### When do you expect to launch your product to 100% of users?
  
We'll need to go through midpoint ideally in the next week.
 
### Will this work be going through the Collaboration Cycle?
- [x] Yes 
- [ ] No
 
#### If yes, please check all of the phases in the Collaboration Cycle you have completed: 
- [x] Design Intent
- [ ] Midpoint Review
- [ ] Staging
 
### When does this work need to be completed?
- Estimated launch date:
- Estimated staging review date:
- Content, Accessibility, and IA work needed by: As soon as possible, ideally by Monday June 26
  
## Supporting artifacts

- Link to product outline: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/README.md
- Link to or attach user flows: https://sketch.com/s/c353146f-eceb-4626-9918-7603c693417f
- Link to prototype or mockups: In progress
- Link to your research plan: In progress
- Link to any epics/issues that may be helpful: https://github.com/department-of-veterans-affairs/va.gov-team/issues/60140
- Link to original content in Google doc: https://docs.google.com/document/d/1qyCxRpesCNwQLN9o22j6BJV3UfM5SssYqTMKnatH1Ww/edit?usp=sharing
- Link to SOT on Github: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/design/toxic%20exposure%20questions%20June%202023.md

#### Do you plan to bring this to an upcoming content office hours session?
- [x] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [ ] No, let's work asynchronously and meet if needed

 **Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.
 
### Accessibility Help in Slack
The [#accessibility-help channel](https://dsva.slack.com/archives/C8E985R32) in the DSVA Slack, is also available to you as a resource. Everyone is welcome to ask questions or get help from our a11y (accessibility) specialists. Tag `@Terry Nichols` to get a11y help asap.

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

- If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
- If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)
 
 - If you are creating an [experimental design,](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) please [also contact the DST. ](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)
- If you are requesting [a11y support for user research,](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name) please complete this form, next.

**Comment by lydiahooper** [comment]
Content has agreed to get reviewed content to product team by EOD this Wednesday so we can get VBA and collab cycle approval by end of week and research can happen while I'm away in July.

**Comment by bethpottsVADEPO** [comment]
@lydiahooper CAIA will need some more time to provide guidance before you take this to stakeholders. Katherine has some content questions and we also need to bring our IA and accessibility experts in for their input. 
cc @DanielleThierryUSDSVA and @shannonkford

**Comment by lydiahooper** [comment]
@bethpottsVADEPO How much more time? Our VBA stakeholder is expecting to meet with us tomorrow so your request is last minute.

**Comment by bethpottsVADEPO** [comment]
@lydiahooper We should just need a couple more days. I know this throws off your tight schedule this week, but there are some important things to address before more people review. We'd like to set up some time to talk through the content/accessibility/IA feedback. We'll be in touch to schedule that with you and @shannonkford.

**Comment by lydiahooper** [comment]
@bethpottsVADEPO if you want to chat before I leave, we'd need to do that tomorrow or Monday FYI

**Comment by bethpottsVADEPO** [comment]
@lydiahooper I wanted to let you know that @shannonkford and I touched base and agree that there's no need to rush this CAIA feedback through ahead of your leave. So I'm updating this ticket to say that CAIA is on track to provide feedback later this week.

**Comment by lydiahooper** [comment]
@bethpottsVADEPO thanks for the update. The IA and accessibility tickets that came out of midpoint have items related to content. I'd rather not have multiple versions of content floating around so they will probably not get resolved until we get CAIA feedback, but I wanted to at least make sure CAIA is aware of them.

**Comment by katherine-fung** [comment]
Hi @shannonkford, 

Thanks for your feedback earlier this week. As we discussed, I've re-worked the content around presumptive conditions for toxic exposures, and C-123 aircraft. And added information about VA Form 21-10210 back to the evidence screen. 

I also tagged you in some clarifying comments, and explained why I'm recommending we leave the claim exam info off the evidence screen. 

Since you noted there are no plans to change some of the screens, I removed those edits from the doc. 

A few more notes: 

-  I did have a question about the screens we ask Veterans to describe the service connection for their conditions. You commented we don't plan to change those screens. On the source of truth Github page, these screens add examples of scenarios that aren't currently live. I left my edits to just those examples, in case we do make those updates to the pages. 

- I have a few questions about the screen that asks "Have you been exposed to any of these hazards? Check all that you've been exposed to."  

The draft had a follow-up question, "When were you exposed?" I want to confirm with VBA that we need the Veteran to provide a time frame. 

If we do, "When were you exposed?" is a potentially confusing question since the previous question allows the Veteran to choose multiple hazards. I recommend replacing "When were you exposed?" (and the following question "If you were exposed multiple times, please provide additional dates and locations of potential exposures.) with a question that allows them to provide a time frame (and potentially location) for a specific hazard, and allows them to add additional times (and potentially locations). Do we need the Veteran to provide location information? If so, I can tweak the proposed content to ask that. 

Here's the Sharepoint link again: 
https://dvagov-my.sharepoint.com/:w:/g/personal/katherine_fung_va_gov/EdlkhNa0yERNo0a9JN_DaykBc5BCqsi3ZbHOLfr1DdOkrg

Thanks again for your collaboration, and let me know if you want to meet again to discuss. 

cc @bethpottsVADEPO for awareness

**Comment by shannonkford** [comment]
Thanks for your patience as we worked through multiple staff outages and your detailed feedback. I have accepted most if not all changes to the TE screens, providing some additional comments on the time frames questions based on discussions with VBA stakeholders. I have left the edits to the contention screens in step 2 as well as the evidence screens intact as we can refer to them later when we pick up work in those sections. I believe the questions above in your comment are also addressed. We are putting together prototypes and plan to test the week of Aug 21. Please let me know if you have any questions.

cc @bethpottsVADEPO

**Comment by katherine-fung** [comment]
Thanks @shannonkford!

**Comment by lydiahooper** [comment]
@RLHecht @katherine-fung We'd like to share what we learned from user research and how we are moving forward. Can you please advise on how you prefer to do that? In this ticket or via meeting or something else?

**Comment by katherine-fung** [comment]
Hi @lydiahooper, 

I briefly reviewed the recording of your research shareout. Thanks for your thoughtful approach to the research. I haven't watched the recording in full, but the insights I heard were very interesting and helpful. It was also very helpful to hear the feedback from partners at VBA on that recording, to give context to the work. For example, I had wondered whether it was necessary to ask Veterans about the dates of their exposure, so it's helpful to know that that's a point of discussion for you all. 

I'd like to learn more about your findings in a meeting. I'm happy to meet at a time we're both available. Also, do you see opportunities to collaborate with the content team on the language to implement recommendations based on the findings? 

Ahead of our meeting, can you link me to the prototype of the screens that Veterans tested?

**Comment by lydiahooper** [comment]
I've made changes to content on final wireframes per conversation with @katherine-fung today, so I'm closing this ticket now. Thanks to all for the collaboration and support on this project!
