### ISSUE TITLE
QA Standards - VA Forms Team - Form 21-10210 Lay/Witness Statement

### ISSUE THREAD

**Issue by it-harrison** [department-of-veterans-affairs/va.gov-team#60671]
#### VFS team name
VA Forms Team
#### VFS product name
Form 21-10210 Lay/Witness Statement
#### VFS feature name
Form 21-10210 Lay/Witness Statement Online Form
#### Point of Contact/Reviewers
@it-harrison - Ian Harrison - QA
---
#### Regression Test Plan 
- [x] Standard has been met
- [ ] Standard has not been met
#### Test Plan
- [x] Standard has been met
- [ ] Standard has not been met
#### Traceability Reports 
- [ ] Standard has been met
- [x] Standard has not been met
##### Explanation of failure to meet standard (if applicable): #####
No Traceabiilty Reports included, ie Coverage for References and Summary(Defects). The link takes me to the Frontend Support Dashboard.

#### E2E Test Participation
- [x] Standard has been met
- [ ] Standard has not been met
#### Unit Test Coverage 
- [ ] Standard has been met
- [x] Standard has not been met
##### Explanation of failure to meet standard (if applicable): #####
code coverage percentage for Lines, Functions, Statements, Branches are all less than 75%.

---
### Product Defects / Bugs
1. **Launch-blocking**

- as an unauthenticated user click "Start your application without signing in"
- select "My own claim"
- click "continue"
- select "Yes" when asked "Are you a Veteran"
- click "continue"
- enter first name, middle name, last name and date of birth
- click "continue"
- enter SSN
- click "continue"
- enter mailing address
- click "continue"
- enter phone / email
- click "continue"
- when you reach the Statement of Truth enter only first and last name or misspell one of your names. You will see a red error message. Try to correct the error so you can submit the form. You won't be able to and therefore the form cannot be submitted.   

![Screen Shot 2023-06-21 at 9 27 58 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8867779/596e3061-bea4-4c2a-bc99-2f70915ce744)

2. **Not Launch-blocking**
when entering a birthdate the validation is broken:
- any four integers passes validation
<img width="444" alt="Screenshot 2023-06-21 at 4 06 25 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/8867779/f6a66db7-3617-4a33-a347-c944f1f15684">

- if the user tries to enter a 1,2, or 3 digit integer the error message is too technical
<img width="566" alt="Screenshot 2023-06-21 at 4 06 42 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/8867779/f4925c7b-5f11-464f-a008-369cd62f94ea">

---
### VFS Guidance

- Close the ticket when your Product Owner determines that you have sufficiently met the QA Standards.
- If your team has additional questions or needs Platform help validating the issue, please comment on the ticket

### Platform directions
- Update "Issue Title" to be of the form "QA Standards - VFS Team - VFS Product"
- Add the VFS team, product name, and feature name
- Add your name, practice area, and GH handle under Point of Contact/Reviewers
- Complete the QA Standards section, making sure to include an "Explanation of failure to meet standard" for every Standard the product does not meet.
- Link to the Collaboration Cycle Request epic
- Add assignees: 
  - VFS PM
  - Yourself (optional)
- Add labels:
  - VFS team label
  - VFS product label
  - QA-standards label
  - launch-blocking label if the product has failed to meet a required QA Standard

**Comment by tlei123** [comment]
@it-harrison , several members of our team and I have not been able to replicate the Review-page Statement-of-Truth signature-validation bug here...

Can you provide you OS/browser specs please?  thx much!

**Comment by tlei123** [comment]
Re. the Date-of-birth validation bug:

- Any 4-digit year input passes validation: That's expected behavior.  We shouldn't set an arbitrary minimum year, which wouldn't prevent any User from inputting an incorrect birth-year anyway.
- Error-message too technical: We're going to try replacing that field with our new Memorial-date field, which should have plain-language error-messages built-in.

**Comment by sterkenburgsara** [comment]
Hi @tlei123 Design System guidance sets date restrictions on year of birth. See [here](https://design.va.gov/components/form/memorable-date). We require that year of birth be between 1900-2123. If you enter something outside of those bounds on the default box on DS guidance page, you should see the correct error message.

**Comment by tlei123** [comment]
Oh cool!  Thx, @sterkenburgsara for the spec link!  Now _that's_ something I can fix & set!  :D

**Comment by tlei123** [comment]
Re. #2 DoB validation bug, I've fixed this via [21-0845's UI/UX Catch-all ticket](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/issues/391) that's still WIP.  Once the [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/24930) for that one's merged, I can fix this one too.

**Comment by tlei123** [comment]
DoB validation bug already fixed via [PR for #491](https://github.com/department-of-veterans-affairs/vets-website/pull/25284).

Review-page signature-field bug was never successfully replicated.

Closing now.
