### ISSUE TITLE
Adding Lisa Kahler to DSVA Slack

### ISSUE THREAD

**Issue by regenauer-va** [department-of-veterans-affairs/va.gov-team#60692]
Good morning,

I am requesting Lisa Kahler be added to the DSVA Slack workspace as a Multi-channel user.

Email: lisa.kahler@oddball.io
Channels:
vaapi-platform
team-cassowary

Thank you!

**Comment by LEHigley** [comment]
don't have ability to add to either channel--invited as multi channel guest to general
