### ISSUE TITLE
[Research] Research synthesis for Financial Disclosure/Priority Group Research

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#60695]
As a Veteran, I would like to view and update my Financial Disclosure information, and view my Priority Group online so that I can make sure the VA has accurate information and my correct Priority Group, and not have to pay co-pays if I don't need to.

### Acceptance Criteria

- [x] Do research synthesis
- [x] Create research findings doc and presentation using Platform templates
- [x] --Include recommendation and justification (e.g. we believe ID/PG should go in the profile because...)
- [x] --Come up with a "pitch" to Patrick and Kristen--this can be informal, maybe 4-5 slides just outlining our findings and recommendations 
- [x] --Come up with a pitch for Authenticated Experience team (can be same as or similar to pitch for Patrick and Krsiten)
- [x] --Propose next steps (e.g. prototype research on FD/PG in profile)
- [x] Present to Patrick and Kristen
- [x] Present to AE team
- [x] Reach out in DSVA design channel to schedule time to present at a future weekly sync
- [x] Update key findings and move research repo item to complete
- [x] Submit to research archive

## Background
The 10-10EZR form is used by Veterans to update their information in their VA Profile. This information includes: mailing address, phone #, SIGI information, Dependents, Insurance, Next of Kin, Emergency Contact, insurance information, and Financial Disclosure. 
The HEC and VEO stakeholders have requested an online 10-10EZR form. While doing discovery for this request, the team learned that there are roughly hundreds of thousands of EZRs filed every year, that some information editable via the paper EZR can be change via the VA.Gov profile, and that the primary purpose for the EZR is to update Financial Disclosure--a capability that is not currently online. 
This team needs to research if Veterans would like to have the capability to review/update financial information online, as well as the ability to view their Priority Group and what it means to them, and if so how and where this capability should "live." 

### Resources
- [Epic](https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/57417)
- 10-10EZR paper form PDF (attached)[https://app.zenhub.com/files/133843125/648d269f-69ef-425b-bd82-a78b6af9c7d1/download](https://app.zenhub.com/files/133843125/648d269f-69ef-425b-bd82-a78b6af9c7d1/download) 
- [Research Plan Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-plan-template.md)
- Overview of EZR form fields and VA.Gov profile fields (attached)[https://app.zenhub.com/files/133843125/adacb673-4c31-4c71-b236-229cf55a5c3d/download](https://app.zenhub.com/files/133843125/adacb673-4c31-4c71-b236-229cf55a5c3d/download) 

### Financial Disclosure Use Cases

- Learn more about how Veterans would like to go about applying, discovering eligibility and getting the most health care benefits they qualify for and what amount of information they feel they need to provide vs what VA should have in that process.
- Learn more about how Veterans would like to go about providing updated information, especially financial and dependent updates, that could impact their health care benefits post-application/initial enrollment.
- as a 0% SC veteran with one dependent who earned $15K last year, i may need to file an annual financial disclosure, so i can maintain access to beneficiary travel
- As a 0% SC veteran with one dependent who lost their $55K/year job and now has no income and was previously assigned to PG 8, i want to file a new financial disclosure, so i can access the medical benefits package under PG 5, be exempt from medication copays, and be reimbursed for my travel expenses.
- As a 20% SC veteran with one dependent who earned $15K last year, i may need to file an annual financial disclosure, so i can maintain access to beneficiary travel
- As a 30% SC veteran who recently enrolled in medicaid, i want to tell VA that im now enrolled in medicaid, so i can access medication copay exemption

### Priority Group Use Cases

- Learn more about Veteran's mental model when applying for health care benefits including the terms they use and how they see levels of benefits/Priority Groups/copays impacting them during the health care application process, during and ongoing after.

### Outstanding Questions

- Do Veterans want this?

**Comment by jessicastump** [comment]
Adding some resources from past research synthesis and more details here.

There a a mix of working files and deliverables needed:
Refer to [notes folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/application/va-application/research/2023-06-Priority%20Group%20and%20Financial%20Disclosure/team-notes) from team and [Perigean transcripts](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/application/va-application/research/2023-06-Priority%20Group%20and%20Financial%20Disclosure/transcripts) and recordings (Recordings note: only in Zoom account or local, do not upload to GH or other shared drive) as needed
Setup a [Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1690832432428/9dc824f17b6dd1fe6c00ba64e036834dc91d9c2c?sender=uadf1ed7fe7c76f0914967329) in the Research folder to use if wanted, see examples below. 
Key findings will be listed on original [Research Repo ticket](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/346)
Key findings GH template to use and place in research folder
Template to use for design sync meetings
This one will probably need a unique stakeholder presentation (separate ticket?)

[Resource of Platform site](https://depo-platform-documentation.scrollhelp.site/research-design/research-synthesis)


### Past study examples
Household study 
- [Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1670614790707/7d9bfeebfc6ff21692ad756c74e395c1cef050cd?sender=uadf1ed7fe7c76f0914967329)
- [Spreadsheet](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/research/2022-10-Household%20Information%20Section/research-notes/HouseholdResearchSynthesis.xlsx)
- [Findings github md file](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/research/2022-10-Household%20Information%20Section/Research%20Findings.md)
- [Findings presentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/research/2022-10-Household%20Information%20Section/2022-12-Household%20information%20section%20usability%20-%2010-10EZ.pdf)

**Comment by hdjustice** [comment]
@katelyncai @davidakennedy @IMHieuVo

**Comment by jessicastump** [comment]
[Here is the link link to the Platform presentation](https://docs.google.com/presentation/d/1bmh_zzhjrXlRdyOnmuTJkz6ppQhOU5LwngBnVEr87Kw/edit?usp=sharing) template completed. Once feedback/final changes are incorporated we can export and upload a PDF to the research folder.
