### ISSUE TITLE
Create Deployment policy

### ISSUE THREAD

**Issue by jholton** [department-of-veterans-affairs/va.gov-team#607]
This is an action item created as a result of a [postmortem](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Postmortems/2019-07-03-VFS-emergency-deployment.md).

## User Story
As a VSP team, we need to create a Deployment policy so that expectations are clearly defined for VFS teams.

## Relevant points to include
* We have daily automated deployments of `vets-api` and `vets-website`.  We encourage VFS teams to structure their work and deployment timing expectations around these automated deployments.
* Automated deployments happen M - F.  At 2 PM Eastern a release is created in GH. This release is deployed at 3 PM Eastern.  Automated deployments do not happen on weekends or holidays.
* Manual deployment requests will be granted to resolve critical bugs.  
* If a manual deployment is needed for any other reason, an escalated approval must be obtained from ??? (Patrick/Leah? Charles Worthington? Somewhere in between?)
* Include a note that Rails migrations are run via a separate Jenkins job. VFS teams will need to request of the devops team to run that job anytime there are migrations, whether the code was deployed manually or automatically.

## Acceptance Criteria
- [ ] First draft of policy written
- [ ] Policy is linked to in VFS documentation
- [ ] check with Mikki on where to store this

**Comment by batemapf** [comment]
re:

> If a manual deployment is needed for any other reason, an escalated approval must be obtained from ??? (Patrick/Leah? Charles Worthington? Somewhere in between?)

Final decision maker will be @chrisj-usds, escalated up through Patrick/Leah.

**Comment by rroueche** [comment]
Notes to include in ROE (from post mortem debrief w/Johnny, Nancy, Wyatt, Andrew G, Rachael):

- An automated deploy kicks off every day at 3 PM ET. If a VFS Team doesn't have their code merged in in time, their updates will go out in the following day's deploy.
- If a VFS Team needs to request a deploy outside of the automatic daily one, we will hold until we have approval from Chris J. VFS teams will need to escalate through Patrick and Leah who'll discuss with Chris J. It's up to VFS Teams to get ahold of Patrick and Leah for their custom deploy request, not VSP.
- Still need to discuss what to do if there's a bug impacting users and we want to quickly get a deploy out - can we have a hatch path for not having to escalate through P&L&C?

**Comment by batemapf** [comment]
> automated deploy kicks off every day at 3 PM ET

I believe code needs to be in by 2pm ET, when release is cut and built, prior to the resultant build being deployed at 3pm ET.

**Comment by andreahewitt-odd** [comment]
Final draft: https://docs.google.com/document/d/1nBbUHIQ4P-0xkL04M-lujU8cdAlVp9fyo363RES1lZw/edit?ts=5d572e24#heading=h.df1pvisl7eve

**Comment by andreahewitt-odd** [comment]
@mnorthuis Where would be a good place to put this document now that we are reorganizing the repo?

**Comment by andreahewitt-odd** [comment]
@gunsch Want to give this another read?  https://docs.google.com/document/d/1nBbUHIQ4P-0xkL04M-lujU8cdAlVp9fyo363RES1lZw/edit?ts=5d572e24#heading=h.df1pvisl7eve

**Comment by mnorthuis** [comment]
@thatmattjohnson another one to review for repo placement

**Comment by gunsch** [comment]
Given another read.

Location-wise, this feels like a pretty good case for "Administrative/Policies" (or whatever the final name of this folder ended up being).

**Comment by thatmattjohnson** [comment]
@mnorthuis @gunsch @mnorthuis recommend platform/about-vsp/policies-work-norms

**Comment by andreahewitt-odd** [comment]
@thatmattjohnson Hey does this folder exist already? I'm having trouble finding it.
