### ISSUE TITLE
Expired ItF preventing submission

### ISSUE THREAD

**Issue by navaeddie** [department-of-veterans-affairs/va.gov-team#60705]
[Chante Lantos-Swett] received a message from Melissa Rebstock from VEO who has been trying to help the spouse of someone who works here at VA submit a 526 application. The Veteran is trying to file an original claim for benefits (526EZ) and provided the following screenshots. He said his intent to file expired and he was trying to submit the claim before it expired and kept getting an error. He tried after it expired and still got an error. Melissa already had the EVSS team look to see if anything was wrong in terms of duplicate records or data mismatches and they didn't see anything. Melissa as hoping to get back to Veteran to let him know what he should do next. Do we think this is a technical bug on our end that could be investigated and resolved? Or is there another path this veteran should pursue given the error he is seeing?

 I have details about the name/ssn for the veteran and reach out for more details but wanted to flag this information first to see if there are any immediate updates I could provide to Melissa.

![MicrosoftTeams-image.png](https://images.zenhubusercontent.com/63dd30048b2159302590655a/a97b98dc-027e-40d1-8d16-2ec9021bd6d8)

![MicrosoftTeams-image (1).png](https://images.zenhubusercontent.com/63dd30048b2159302590655a/45ed7b9b-9c56-4630-96c6-bea9b5a97b4d)

Source: [Slack Conversation](https://dsva.slack.com/archives/C05BDU0HR42/p1687441922864639)

**Comment by micahaspyr** [comment]
@navaeddie any info in the logs or is it just something generic?

**Comment by navaeddie** [comment]
@micahaspyr they haven't sent me any PII on this case so I haven't looked in the logs yet.

**Comment by navaeddie** [comment]
```
To get a DOB from SSN:
bgss = BGS::Services.new(external_uid: ssn, external_key: ssn)
p = bgss.people.find_by_ssn(ssn)
puts p
```

**Comment by RakshindaAslam** [comment]
@Kimberley2019 - were we able to get any further information on this?
cc @mchae-nava @tblackwe
