### ISSUE TITLE
Salesforce Training (Young Lee) - Session 05

### ISSUE THREAD

**Issue by manalo-soco** [department-of-veterans-affairs/va.gov-team#60718]
Prior Ticket [#57350](https://app.zenhub.com/workspaces/contact-center-62cdd9546ec1530018209672/issues/gh/department-of-veterans-affairs/va.gov-team/57350)

[ ] - Email Builder
[ ] - Omnichannel routing (Escalations)
[ ] - Support Analytics and Reporting

**Comment by ATMiddleton** [comment]
Conclude Young's training.

**Comment by Solarith** [comment]
Got with Mike 8/23, discussed on getting training in next week once he has a better handle on his schedule from catch up from being out.

**Comment by ATMiddleton** [comment]
@Solarith - @manalo-soco is getting caught of from an absence.  Will update by the end of next sprint.

**Comment by manalo-soco** [comment]
Scheduled for Monday 8/28 - Will update ticket after session.

**Comment by manalo-soco** [comment]
[✓ ] - Omnichannel routing (Escalations)
- Reviewed routing to Tier 3 
- Will review international T2 cases team cc @Kimberley2023-CSM @ATMiddleton @starlow00 to ask questions from team 

[ ✓ ] - Support Analytics and Reporting
After reviewing/closing T2 cases, Young will look to give a report breakdown of trends he says in T2 cases for the week and cc Sarifa, Kimberley @aubreyarcangel in Standup reporting for visibility and internal review. 

- Email Builder (will review after launch)
