### ISSUE TITLE
External Facing: What We Do/What We Don't Do - Quick View Doc

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#60710]
**Description:**
[Quick View document ](https://vfs.atlassian.net/wiki/spaces/~63442b7bb380bb46a0906c45/pages/2668003344/What+We+Do+and+Don+t+Do+-+Platform+Support+-+Draft)with common topics

**Definition of Done**
Tier 2 Support has reviewed and contributed answers, management has approved for publication on Platform Website

**List of Tasks to Complete**

- [x] Create document
- [x] Request input from Tier 2 Support team members
- [x] Submit for review to Clint Little and/or Andrea Hewitt
- [x] Approved by Content Team
- [x] Published on Platform Website

**Comment by alyssagallion** [comment]
Document created here: https://depo-platform-documentation.scrollhelp.site/support/what-we-can-help-with-platform-support 

Closing.
