### ISSUE TITLE
Prep for IPP workshop

### ISSUE THREAD

**Issue by alevindecanini** [department-of-veterans-affairs/va.gov-team#60729]
We need to touch base on IPP and make sure the team is on the same page for the MVP. 
The workshop will be prepared in [this mural](https://app.mural.co/t/innovationboards1199/m/innovationboards1199/1687898880676/cbd07692471b08a9aca860dca29a82e29dca6313?sender=u99cd1ac4f5c240d8dffd4204)

There are three documents that will support the prep for this workshop:
[IPP Workshop Outline](https://docs.google.com/document/d/1EteoLxKf8JSmG5SxsgZa9T-xlh3doSJ1LmQDgzJwcY0/edit)
[IPP Conceptual Model](https://app.mural.co/t/innovationboards1199/m/innovationboards1199/1682696582966/6afcfe6eba33c68ab039d3fcbf7a6665aa86c96d?sender=u99cd1ac4f5c240d8dffd4204)
[Open Questions About IPP](https://docs.google.com/document/d/1gMvZaAT8PcVIlA9MoC_bNkB9xMhYuxw0ZLZQybJ3zoI/edit)

**Comment by skirkman16** [comment]
Workshop will take place over two sessions on 6/28 and 6/30. I drafted the first version of the workshop based on three documents Anthony shared with me. Anthony revised this workshop and led the first half of our discussion yesterday.
