### ISSUE TITLE
Direct scheduling comments field truncated 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#60726]
## Summary
When testing in staging, we noticed the comments field being truncated. 

## Specs
- Device: Desktop
- Browser: Google Chrome

## Steps to Reproduce
**Test User:** grethel.g.petryniec@id.me

1. Go to: https://staging.va.gov/health-care/schedule-view-va-appointments/appointments
2. Click Start Scheduling
3. Select Mental health type of care
4. Select Cheyenne Medical Center for the facility
5. Select CHY MENTAL HEALTH ONE for the clinic
6. Select Tuesday, July 25, 2023 at 12:00 p.m. MT
7. Select Routine/Follow up visit for the reason for appointment 
8. Enter comment:` comments go here.  Entering 250 comments. this is a routine or follow up visit.  !@#$%&*()_+{}\":<>?/.,';\\][=-0987654321~`xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\nxxx\nxxxxx\nxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx123`
9. Submit and schedule the appointment after entering the contact details 

### Actual Result
![image (3)](https://github.com/department-of-veterans-affairs/va.gov-team/assets/90797205/b319878c-a61e-41ba-bb52-54a9148a4b9c)

### Desired Result
The full text should be displayed "comments go here.  Entering 250 comments. this is a routine or follow up visit.  !@#$%&*()_+{}\":<>?/.,';\\][=-0987654321~`xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\nxxx\nxxxxx\nxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx123"

## Definition of Done
- [ ] Desired result is achieved and/or document decisions made
- [ ] Relevant documentation is updated

---

**Comment by ldelacosta** [comment]
@marcynadeau - this ticket is fixed in staging. If you want to quickly verify and let me know if you have any questions. Thanks!

**Comment by marcynadeau** [comment]
Validated and passed.  @ldelacosta

**Comment by ldelacosta** [comment]
No new issues to report. Closing out the ticket.
