### ISSUE TITLE
Confirm that Internal Tools on Gatsby site links to correct va.gov-team folder

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#6073]
This page https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/internal-tools/

Links here https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/onboarding/request-access-to-tools.md

But the correct link is https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/orientation/request-access-to-tools.md

Once the Gatsby build is fixed #4217 we should come back to this to confirm that the correct link is in place

**Comment by gmaciolek** [comment]
Link fixed: https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/internal-tools/
