### ISSUE TITLE
Update the breadcrumb on the Pending appointments page (MHV on VA.gov)

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#60753]
## Description
The Appointments application will be under the MHV on VA.gov portal. We will need to update the breadcrumb structure. #60753 will focus on the Pending appointments page. 

---

## Acceptance Criteria
Background: the `va_online_scheduling_breadcrumb_url_update` toggle is on

- [x] Given the user is on the MHV on VA.gov portal
        When the user clicks on `Upcoming VA appointments` and lands on the Appointments homepage 
        Then user clicks on `Pending` link, the breadcrumbs will be updated to `VA.gov home > My HealtheVet > Appointments > Pending appointments`
        Where the URL for `VA.gov home` is `va.gov`
        And the URL for `My HealtheVet` is `va.gov/my-health/`

### Reference
[Spike ticket #54757](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/54757)

### Design Assets
[Title tag format guidance](https://design.va.gov/content-style-guide/seo#title-tags)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by ldelacosta** [comment]
Validated the changes in staging for jacquline.morgan@id.me. Notified the UX designers to review changes in staging. 
![Screenshot 2023-08-15 at 12.07.24 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/9d6c1c23-5c38-40dd-a42f-54824eb1ea07)

**Comment by melissa-lefevre** [comment]
no issues to report @ldelacosta

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket.
