### ISSUE TITLE
Update the URL and title page on the Past appointments page (MHV on VA.gov) 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#60754]
## Description
The Appointments application will be under the MHV on VA.gov portal. We will need to update the title page and URL structure. #60754 will focus on the Past appointments list page. 

---

## Acceptance Criteria
Background: the `va_online_scheduling_breadcrumb_url_update` toggle is on

- [x] Given the user is on the MHV on VA.gov portal
        When the user clicks on `Upcoming VA appointments`, user will land on the Appointments landing page
        And the user clicks on `Past` link
        Then the URL will be updated to : https://va.gov/my-health/appointments/past
        And the page title will be [`Past appointments | Veterans Affairs`
](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/homepage.md#past-appointments)

### Reference
[Spike ticket #54757](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/54757)

### Design Assets
[Title tag format guidance](https://design.va.gov/content-style-guide/seo#title-tags)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by ldelacosta** [comment]
Validated the changes in staging for jacquline.morgan@id.me. Notified the UX designers to review the changes. 
![Screenshot 2023-08-15 at 12.09.44 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/6045de6f-dc18-4775-9f38-2c324d6a594c)

**Comment by melissa-lefevre** [comment]
No issues found @ldelacosta

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket.
