### ISSUE TITLE
Sprint 30-Day 1 Huddle

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#60757]
# Description
We chose to spend some time working as a team to resolve some blockers. We were aimed at --

* Resolving the seeming non-deterministic behavior of our FE pod deployment
* Resolving any comments from Rachal as she volunteered her time to review our EKS deployment methods

# Acceptance Criteria
- [ ] Our FE pod consistently deploys and reflects all changes expected
- [ ] Rachal's comments about improvements to our EKS deployment ticket have been resolved

**Comment by pjhill** [comment]
Created a revised version of the FE image with a custom built content-build here -- https://github.com/department-of-veterans-affairs/vets-website/tree/pe_slow_content_build

**Comment by pjhill** [comment]
Deploying the above branch's image appears to work fairly well. The initial test worked well, but we encountered a space issue after one test. We have not been able to recover space for additional testing yet.
