### ISSUE TITLE
[TF Mod] Constructing ECR repo link

### ISSUE THREAD

**Issue by hgbarreto** [department-of-veterans-affairs/va.gov-team#60765]
## Description
Determine if using Route 53 or any other method is viable when constructing the ECR repo links.
The team would like to dynamically create the ECR repo link using account/region id calls

## Notes
image.repository = "${local.account_id}.dkr.ecr.${local.region_id}.amazonaws.com/${local.repo_name}"

## Resources 
- Artifacts - i.e., issues, documentation, code, etc. - that help explain what's needed to work on this issue

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this issue?_

## Refinement Guidance - Check the following before working on this issue: 
- [x] _Team label assigned ("platform-tech-team-2")_
- [ ] _Epic assigned (if needed)_ 
- [ ] _Estimated (points assigned)_
- [ ] _Sprint assigned (once planned)_
- [ ] _Team member(s) assigned_

**Comment by ph-One** [comment]
We may end up in a situation where we are using ECR across regions, or even AWS accounts. This effort is no longer relevant since images may get pulled from multiple locations. Closing the ticket, but we can open a new one if this work becomes relevant again.
