### ISSUE TITLE
Midpoint Review - Design Feedback - Authenticated Experience, Profile, Notification Settings - Default Send Functionality

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#60766]
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- Love all the mobile and screens!

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- **Must**: The font weight of the [active link](https://design.va.gov/components/link/#active) should be 700.
- **Consider**: I know we discussed this at the design intent, but do the alert style need to be a warning alert? Maybe they do not want notifications.
- <img width="317" alt="Screen Shot 2023-06-22 at 1 24 10 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/72398073/37e459fa-6d90-4b13-921a-35a6ea9dea2b">

**Comment by andaleliz** [comment]
I've updated the screens so the link has a 700 weight now.

> I know we discussed this at the design intent, but do the alert style need to be a warning alert? Maybe they do not want notifications.

We initially went with the warning alert since the whole section is blocked. I really could go either way though! We've got an alert audit coming up once the content team publishes the latest messaging directory so we will wait for that before we update, just in case their new guidance provides something strong to go off of for this use case.

**Comment by adamwhitlock1** [comment]
@andaleliz Was working on updates to this alert, and was using this file for design guidance:

https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/9P49mAx

Should the links in that alert be bolded as well? I'm. using the va-link design system component with the `active` property which adds the chevron and makes them bolded by default.

**Comment by allison0034** [comment]
@adamwhitlock1 yes, the [active link style](https://design.va.gov/components/link/#active) is bold : )

**Comment by allison0034** [comment]
@andaleliz ah ok, @humancompanion-usds do you know if the active link should always be bold? Sketch shows a variation but [Storybook](https://design.va.gov/storybook/?path=/docs/components-va-link--active#active) and DS do not.

**Comment by humancompanion-usds** [comment]
Yes, active links are always bold. Use the active link web component: https://design.va.gov/storybook/?path=/docs/components-va-link--active

**Comment by andaleliz** [comment]
Thanks @humancompanion-usds.  

@adamwhitlock1 I've updated the mock-ups to reflect the bold text.
