### ISSUE TITLE
Update the radio button selection on the confirmation and review details page 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#60762]
## Description
We will make a minor update on the confirmation and review details page. When the user selects the reason for the appointment, the description of the selection is not consistent with the selection on the "Choose your reason for the appointment" page. 

---

## Acceptance Criteria

- [x] Given the user is in the direct schedule workflow 
       When the user selects `This is a routine or follow up visit` and enter the comments 
       Then the confirmation details will display `Routine/Follow-up`

![Screenshot 2023-06-23 at 10.37.35 AM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/fa5c267f-b345-49fd-8a04-60d3a12f70ee)

![Screenshot 2023-06-23 at 10.33.03 AM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/30b54de1-a10f-4c5c-ae6c-eba02f6435a3)

- [x] Given the user is in the direct schedule workflow 
        When the user selects `I have a medical issue` and enter the comments
        Then the review details and confirmation page will display `New medical issue`

![Screenshot 2023-06-23 at 10.28.21 AM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/1639d20a-ce81-4a61-b144-3bff1558af24)
![Screenshot 2023-06-23 at 10.39.26 AM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/cf173cd6-459a-4521-8497-e75b6af75a8e)

- [x] Given the user is in the direct schedule workflow 
        When the user selects ` I have a concern or question about my medication` and enter the comments
        Then on the confirmation details page will display `Medication concern`

![Screenshot 2023-06-23 at 10.41.32 AM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/8cd140f7-9189-4cb8-b4a5-b89454a90c99)

### Design Assets
N/A 

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by ldelacosta** [comment]
Considered very low priority.

**Comment by ldelacosta** [comment]
@young1205 - please have the UX team validate this ticket when it's ready cc: @JRRoof @outerpress

**Comment by ldelacosta** [comment]
@young1205 - please have the UX team validate this ticket when it's ready cc: @JRRoof @outerpress

**Comment by Cieramaddox** [comment]
This has been validated by the UX team and will be closed out.

**Comment by outerpress** [comment]
@young1205 should UX close out tix after they are validated, or do we assign them back to you?
