### ISSUE TITLE
Staging: VSP Error, No VistA Appts Display and No message displayed to veteran

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#60769]
The Bay Pines VistA instances were down and because of the that VAOS was not displaying VA appointments.  
Expected Response:  Message displays to veteran indicating not all of their appointments may be displaying
Actual Response:  No message displayed.

Dev Tools showed:  https://staging-api.va.gov/vaos/v2/appointments?_include=facilities,clinics&start=2023-05-24&end=2024-07-22&statuses[]=booked&statuses[]=arrived&statuses[]=fulfilled&statuses[]=cancelled

    ],
    "meta": {
        "pagination": {
            "currentPage": 0,
            "perPage": 0,
            "totalPages": 0,
            "totalEntries": 0
        },
        "failures": [
            {
                "system": "VSP",
                "id": "14617184-6d58-4d46-8724-789811972b29",
                "status": "500",
                "code": 6000,
                "message": "There were errors fetching appointments from VSP: Resource types: [appointments]: Failed to fetch appointments for patient 984/552161050; Failed to fetch appointments for patient 983/7216691"
            },
            {
                "system": "VSP",
                "id": "80030aea-0c2c-44c8-a629-3483afb14ffe",
                "status": "500",
                "code": 6000,
                "message": "There were errors fetching appointments from VSP: Resource types: [requests]: Failed to fetch appt requests for patient 984/552161050; Failed to fetch appt requests for patient 983/7216691"
            }
        ]
    }
}

**Comment by ldelacosta** [comment]
The only difference I see from this defect and the ticket we worked on when we implemented (#55068, #55280 and #55279) was the `"code."` In Marcy's response, we see `"code": 6000`, but not sure if the FE code is expecting `"code": 1000`

**Comment by simiadebowale** [comment]
@ldelacosta - this issue has been fixed and tested
screenshot:
<img width="1496" alt="Screenshot 2023-06-26 at 2 06 48 PM" src="https://github.com/department-of-veterans-affairs/vets-website/assets/47654119/b4d02d00-1e69-4d25-9636-ca43eb2e80d1">

pending:

<img width="1491" alt="Screenshot 2023-06-26 at 4 12 17 PM" src="https://github.com/department-of-veterans-affairs/vets-website/assets/47654119/caaab11c-bccf-4a22-960f-f52cf3d8f925">

**Comment by ldelacosta** [comment]
No new issues. Closing out the ticket.
