### ISSUE TITLE
[TF Mod] enabling the helm-install mod to accept more than one values.yaml

### ISSUE THREAD

**Issue by hgbarreto** [department-of-veterans-affairs/va.gov-team#60771]
## Description
Enabling the helm-install module to accept more than one values.yaml.

## Notes
value_files = ["helm_cert-manager-values.yaml", "helm_cert-manager-values-2.yaml"]

## Resources 
- Artifacts - i.e., issues, documentation, code, etc. - that help explain what's needed to work on this issue

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this issue?_

## Refinement Guidance - Check the following before working on this issue: 
- [x] _Team label assigned ("platform-tech-team-2")_
- [ ] _Epic assigned (if needed)_ 
- [ ] _Estimated (points assigned)_
- [ ] _Sprint assigned (once planned)_
- [ ] _Team member(s) assigned_

**Comment by ph-One** [comment]
This work is no longer needed. It has no use case.
