### ISSUE TITLE
6/22/23 Case Breakdown

### ISSUE THREAD

**Issue by Kimberley2019** [department-of-veterans-affairs/va.gov-team#60777]
Hi Team! We made it through another week to a FRIDAY!!!!!! Here is the breakdown for Thursday (6/22) opened cases.

Total Cases: 72
[Total T2 Cases:](https://va.lightning.force.com/lightning/r/Report/00O3d000000Yn4zEAC/view) 28
T3 Cases: 44
VA.gov [Technical Support T3 Cases:](https://va.lightning.force.com/lightning/r/Report/00O3d000000ZoQAEA0/view?queryScope=userFolders) 25
[EVSS T3 Cases](https://va.lightning.force.com/lightning/r/Report/00O3d000000ZoPgEAK/view?queryScope=userFolders): 19
Please let me know if you have any questions!

**Comment by ATMiddleton** [comment]
Completed.
