### ISSUE TITLE
Access for Jonathan Julian

### ISSUE THREAD

**Issue by jjulian** [department-of-veterans-affairs/va.gov-team#6077]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Dan Navarra
- Please provide your name.
   > Jonathan Julian
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Structured Data VFS / Pension Automation, Engineer, Ad Hoc
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Internal%20Tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDei5Qv/zftjCyf6i2Sqa2cFjuNlV0ZjjomjRmc2Yq26U+pVkuKcWS3HskEO1wRL0c6RUzWdjzk2Pmv6GYVbuQ0Y9z3HCeXmHLexzm+44cFzqketJC4EkT/h9OKJyqcNHuoNNesSmRzN7Ir1jfHE7yzxb35n4wT+iTDs9GPyz8lThkYP8JkZ5c24D7Mk4MW5VDG+hNGt1Qz7M656K2DTEIx1SOym8HXCwgdncATLWSbKPjfxHZS0RAdvFQMAQ1nv/AH6L4L8c3zzplBWM7/iW8wSLLspoIGXJfqfcQ91Hnz1jpoolh4Nyy1QZiu1C03LeC7rKmYXy80yevAHkyKfMgp 20200221_jjulian@adhoc
```

- [Grant AWS Console access?]
  > YES
  >   I will need access to AWS console in order to assist my team with work such as managing resources, logging, monitoring, debugging, etc.

**Comment by ricetj** [comment]
due to new changes in the process, SOCKS access is granted sooner. You should now refer to this [section](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) of the instructions to set up your SOCKS. Please Also keep following up with your paperwork for the VA.

**Comment by ricetj** [comment]
For AWS Access
@Jeff-Hayter 
User: Jonathan Julian
COR: Dan Navarra

**Comment by Jeff-Hayter** [comment]
@ricetj Approved for AWS.

**Comment by jbritt1** [comment]
@jjulian, once the above PR is approved and merged I will contact you on Slack with first-time login credentials / instructions.

**Comment by jbritt1** [comment]
Approved, merged, applied. 
First-time login credentials / instructions delivered to Jonathan via Slack.
Closing ticket.
