### ISSUE TITLE
Midpoint Review - Design Feedback - Disability Benefits Experience Team 1, 21-526EZ, Toxic Exposure Page

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#60770]
## VFS actions
- [x] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [x] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [x] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- Allison is on PTO during this review.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- **Must**: Fix the alignment on month/year fields
- **Must**: Chevrons on "Back" button should be blue
- <img width="211" alt="Screen Shot 2023-07-05 at 2 43 11 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/72398073/bec21999-ed53-4dc7-b1ae-e3b949476ed8">
- **Must**: For the multiple responses for when they served, use the [single page pattern](https://design.va.gov/patterns/ask-users-for/multiple-responses#how-to-design-and-build---single-page). One possible way to do this is to add conditional logic to "Did you serve in any of the Gulf War Hazard locations" to it's own page and then if they select "yes" ask for dates on the next page. Follow the UI for the single page pattern on that page (card style/save button). This also applies to the multiple responses for "Have you been exposed to any of the following"
- <img width="221" alt="Screen Shot 2023-07-05 at 2 55 58 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/72398073/6c8a9d9f-0149-4a7a-a95f-6ceb464bcbe1">
- <img width="206" alt="Screen Shot 2023-07-05 at 2 58 26 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/72398073/35a71099-13c2-4ea2-8b5e-4d88c2d9ec00">
- Must: Change the border of the [tile checkbox](https://design.va.gov/components/form/checkbox#tile) to gray
- <img width="207" alt="Screen Shot 2023-07-05 at 3 03 28 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/72398073/a32d2e60-0c4d-4dbf-98a9-1d9bf522673f">

- **Should**: Put the locations list in alphabetical order
- <img width="210" alt="Screen Shot 2023-07-05 at 2 45 23 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/72398073/5d3d5c42-dd31-4bd5-a493-2b8d751e5dfb">

**Comment by shannonkford** [comment]
All comments have been addressed, except for "Must: Change the border of the tile checkbox to gray" as this page is not in scope for changes. We can note this as a backlog item, however.

**Comment by lydiahooper** [comment]
Closing per Shannon's previous comment
