### ISSUE TITLE
Add sticky behavior to feature flags on vets-website 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#6078]
## Overview 

- Unauthenticated users won't consistently see a specific feature variant when activating on a % of users  
- the `/feature_toggles` end point now supports locking a user into a particular variant by a unique ID

## Potential tasks  

- Read the backend implementation [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/5997)
- Update the call to `feature_toggles` to pass a unique id for unauthenticated users- the backend ticket has some suggested ids but you could also just generate it

**Comment by ericbuckley** [comment]
@rianfowler / @annaswims I see the related [vets-api PR has been merged](https://github.com/department-of-veterans-affairs/vets-api/pull/3868), but was wondering has anyone started working on the vets-website changes?

**Comment by rianfowler** [comment]
It's in the FE tools backlog: https://github.com/department-of-veterans-affairs/va.gov-team/issues/6078

It hasn't been prioritized yet. Let @brandonrapp know if there's a short term need to get this in the website.

**Comment by ambikaroos** [comment]
@brandonrapp @rianfowler this feature is a dependency for the SSO team's end of March release cc @ericbuckley @patrickvinograd

**Comment by jhonnyoddball** [comment]
Implementation is completed.
[Pull Review](https://github.com/department-of-veterans-affairs/vets-website/pull/11890)

**Comment by ambikaroos** [comment]
FYI @ericbuckley
