### ISSUE TITLE
Identity Dashboard (FE) - Fix Header (Chakra)

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#60798]
## Description
Bug: Fix the Header to look like the Figma prototype

## Tasks
- [ ] Fix the bug with styling the Header

**Comment by acald-creator** [comment]
Close as duplicate of https://app.zenhub.com/workspaces/identity-5f5bab705a94c9001ba33734/issues/gh/department-of-veterans-affairs/va.gov-team/61176
