### ISSUE TITLE
[DA] 10-10 Forms: Sprintly Metrics update

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#60805]
## Background
As part of a regular sprint-ly cadence, we need to update various metrics on our applications - 10-10EZ and 10-10CG.

### References
- [Metrics Spreadsheet](https://docs.google.com/spreadsheets/d/1T_iRon2SsOwL7cRSEyDIiRnC0Ci81FpVThAs2RgPyKY/edit#gid=1033337103)

## Tasks

- [x] Update metrics on the spreadsheet for both applications
- [x] Share any anomalies with the team for further review

## Acceptance Criteria
- Metrics for both applications are collected and tracked on a regular, sprintly basis

**Comment by luis-simauchi** [comment]
Metrics within [google doc](https://docs.google.com/spreadsheets/d/1T_iRon2SsOwL7cRSEyDIiRnC0Ci81FpVThAs2RgPyKY/edit#gid=2089468283) were updated for this sprint cycle.
Sprint: Jun 14 - Jun 27, 2023
