### ISSUE TITLE
[DA] 10-10 Forms: Sprintly Metrics Update 

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#60806]
## Background
As part of a regular sprint-ly cadence, we need to update various metrics on our applications - 10-10EZ and 10-10CG.

### References
- [Metrics Spreadsheet](https://docs.google.com/spreadsheets/d/1T_iRon2SsOwL7cRSEyDIiRnC0Ci81FpVThAs2RgPyKY/edit#gid=1033337103)

## Tasks

- [x] Update metrics on the spreadsheet for both applications
- [x] Share any anomalies with the team for further review

## Acceptance Criteria
- Metrics for both applications are collected and tracked on a regular, sprintly basis

**Comment by hdjustice** [comment]
Hi @luis-simauchi - We have ticket #62970 for the current sprint.  Is there something we need to do on this ticket still?

**Comment by luis-simauchi** [comment]
no no this was my mistake! I a brought up the wrong ticket for this sprint, thank you for catching this!
