### ISSUE TITLE
prod Vets-api terminal access for Eddie Glenn

### ISSUE THREAD

**Issue by navaeddie** [department-of-veterans-affairs/va.gov-team#60824]
### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Eddie Glenn

### Your GitHub handle (terminal access is managed through GitHub)

navaeddie

### Team, Role, and Company of the target individual

Benefits Disability Experience, Software Engineer, Nava

### Product Manager (PM) name and email

Rakshinda Aslam - rakshinda.aslam@agile6.com

### Product Owner (PO) name and email

Matthew Self - matthewself.dsva@gmail.com

### ArgoCD terminal access requested for the following environments

- [ ] dev
- [ ] staging
- [ ] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### COR Name (leave "None" if you listed an AWS user name above)

Delano McVay

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

Agile Six - Anthony M. Arashiro

### Access Expiration

June 1, 2024

### Additional Notes

Benefits Disability Experience team has adopted a rotation for handling incoming bugs and whatnot. We routinely require prod access to carry out this work.

So I would like prod access to carry out this work.

Sorry for the inconvenience, this is a followup to [another issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/59719) where I was granted access in the lower environments.

### User must exist in a roster before vets-api terminal access can be granted

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added
- [ ] If they included an AWS user name, check to see if their user name is listed in [iam_users.tf](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf)
- [ ] Comment in this issue saying which roster the user is listed in and confirming their AWS user name (if applicable)

**Comment by bdech** [comment]
Found in VFS Team Roster

@BillChapmanUSDS E-QIP transmittal found in this [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54779)

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/135037265/6085bb0c-25c6-473e-b445-127310aaa0fa)

**Comment by bdech** [comment]
@navaeddie Access to `prod` is pending approval by OCTODE, and we'll update you as soon as it's available.

**Comment by BillChapmanUSDS** [comment]
We are beginning the process of requiring more specific descriptions of production access and will have a stricter burden of justification.  Can you describe some of the tasks you would like to perform on production environments that cannot be completed in lower environments?  I will allow the standard 3 months access once specific details are provided  but depending on the justification the access may be limited in future requests.

**Comment by bdech** [comment]
@navaeddie Can you provide some insight to Bills question above?

**Comment by navaeddie** [comment]
@bdech @BillChapmanUSDS sorry for the delay in responding.

At least once per month I'll be on bug duty which will principally require investigating issues that veterans are having (in prod) when trying to submit a 526ez claim. When I was on bug duty a couple weeks ago, there were a few different users who encountered difficulties that made our team want to investigate the `in_progress_forms` or `intents_to_file` associated with their account to find errors.

It generally calls for an approach of, no one knows exactly what's wrong with the system, so one of us needs to go in to prod and make a few educated guesses to see if the problem arises from our part of the system.

For what it's worth, this is the [Zenhub bug board](https://app.zenhub.com/workspaces/526ez-bugs-and-defects-646e4436ff6787001ac4771a/board) where we are tracking these issues (and the [Github issues](https://github.com/department-of-veterans-affairs/va.gov-team/issues?q=is%3Aopen+is%3Aissue+label%3A526ez-Defects) filtered for the relevant label in case you don't have Zenhub access), I haven't done this work long enough to say what proportion of these issues will require prod access. But a conservative estimate would be at least one during every rotation.

Let me know if you need more from me.

**Comment by BillChapmanUSDS** [comment]
Aa per our updated policy access period can be extended from 3 months to 6 months as detailed justification has been provided Thank You!  Access Approved.

**Comment by bdech** [comment]
@navaeddie  You've been granted access to `Prod` for 6 months, expiring 01/21/24.

**Comment by bdech** [comment]
slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1689948030484669)

**Comment by bdech** [comment]
@navaeddie  Your Vets-API Terminal Production access has expired.

Would you like to request an extension? You have 72 hours to respond, or your 
access will be revoked and you will need to fill out a new request.

**Comment by bdech** [comment]
No response, access revoked.
