### ISSUE TITLE
External Facing Document: Support Best Practices

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#60837]
**Description:**
[External document](https://vfs.atlassian.net/wiki/spaces/~63442b7bb380bb46a0906c45/pages/2667675700/External+Facing+Support+Best+Practices+-+DRAFT+60837) to introduce transparency and expectations of service from the platform support team - This Document could live in Platform Developer docs as well

**Definition of Done**
All steps below completed

- [x] Document created
- [x] Edited & Reviewed by Platform Support Team
- [x] Reviewed and approved by Clint Little, Andrea Hewitt
- [x] Approved by Content Team
- [x] Published on Platform Website

**Resources or Examples**
External Document could have headings or bullets like:

- This is a channel for Platform-specific issues
- FAQ's
- Things Support Team has no control over/Outside of our realm
- List of Resources to try before opening a support ticket
- Your project is something we can't easily help with
- Flaky tests = Ask Front End directly, among things to keep in mind

**Comment by alyssagallion** [comment]
Document has been created here: https://depo-platform-documentation.scrollhelp.site/support/support-best-practices
