### ISSUE TITLE
Midpoint Review - Accessibility Feedback - Authenticated Experience, Profile, Notification Settings - Default Send Functionality

### ISSUE THREAD

**Issue by briandeconinck** [department-of-veterans-affairs/va.gov-team#60838]
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- Everything looks great! And we're always so grateful for such thorough artifacts.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- **Engineering note:** I went back and looked at the CodePen prototype you shared at Design Intent, and I've been thinking about  how the page is structured for screen reader users. If your plans have evolved since building that prototype, this may or may not be relevant!
   
   In CodePen, each notification has a `fieldset` containing an `h3`  and then the checkboxes for each notification method that's available. And then each checkbox label has an `aria-label` that provides sufficient context so you understand which checkbox you're on, instead of just hearing "Notify me by email" over and over again.
   
   That's all fine, until you have the extra hint text for prescription shipment and tracking. Here's how it's coded:
   
   ```
   <fieldset class="vads-u-padding--1 vads-u-border-left--5px vads-u-border-color--white" id="channel4-1">
        <h3 class="sans-serif-label">Prescription shipment and tracking updates</h3>
        <p>Only available at some VA health facilities. Check with your VA pharmacy first.</p>
        <input id="channel4-1-0" name="Prescription shipment and tracking updates-1" type="checkbox" value="true" data-alert-trigger=""><label class="vads-u-margin--0 vads-u-padding-y--1" name="Prescription shipment and tracking updates-1-0-label" for="channel4-1-0" aria-label="Notify me of Prescription shipment and tracking updates by text">Notify me by text</label>

        <input id="channel4-1-1" name="Prescription shipment and tracking updates-1" type="checkbox" value="false" data-alert-trigger=""><label name="Prescription shipment and tracking updates-1-1-label" for="channel4-1-1" aria-label="Do not notify me of Prescription shipment and tracking updates by text" class="vads-u-margin--0 vads-u-padding-y--1p5">Notify me by email</label>

   </fieldset>
   ```
   
   If a user has their screen reader announce the whole page or skips to the H3 and then announces the page from there, it's fine. But more often I would expect users to tab through the checkboxes rather than listening to the whole thing. When they land on those checkboxes, they won't hear the H3 or the "Only available at some VA health facilities" message. The `aria-label` on each checkbox label covers the H3, so that's fine. But the "only available" helper text still gets skipped.
   
   Getting helper text inside a `fieldset` to be programmatically associated with the inputs consistently across screen readers is... surprisingly difficult. Two options here:
   
   Option 1: Put both the H3 and the helper text inside a `legend`, then style them to make them look right. Markup would be something like:
   
   ```
   <fieldset>
      <legend>
        <h3 class="sans-serif-label">Prescription shipment and tracking updates</h3>
        <p>Only available at some VA health facilities. Check with your VA pharmacy first.</p>
      </legend>
        
      ...

   </fieldset>
   ```
   
   Option 2: Associate both the heading and the helper text with the `fieldset` using `aria-labelledby`:
   
   ```
   <fieldset aria-labelledby="unique-heading-id unique-helper-id">
        <h3 id="unique-heading-id">Prescription shipment and tracking updates</h3>
        <p id="unique-helper-id">Only available at some VA health facilities. Check with your VA pharmacy first.</p>
        
      ...

   </fieldset>
   ``` 
   
   I have a slight preference for Option 1, but both should result in the heading and the helper text both being read out when you tab to the first checkbox in the `fieldset`. I would also recommend restructuring all of the notification fieldsets to be consistent with whichever of these you go with (or some other solution), so that screen reader users are navigating a consistent structure across all of them regardless of whether they have helper text.
   
   Note that in either case, this makes the `aria-label` on the checkboxes unnecessary. The grammar changes a little, but all of the information that's added via the `aria-label` now gets announced when entering the `fieldset` and the extra text in the `aria-label` would be duplicative.
- **Engineering note:** An issue related to the `aria-label` text, which is moot if you address the item above and get rid of that text entirely. But I'll include it here anyway just in case. In the CodePen, the visible checkbox `label` reads "Notify me by [text/email]" and the `aria-label` reads "Notify me of [notification type] by [text/email]." When you add an `aria-label` to an interactive element, that overrides the visible label to become the element's name in the accessibility tree. In addition to screen readers announcing it, that also means voice command software will use it when looking for matches when a user speaks a command.
   
   For a sighted voice command user, they'll see "Notify me by text" and say "Click Notify me by text," and their software will highlight anything that it identifies as a possible match. For a page like this, that means it will highlight all of the "Notify me by text" checkboxes on the page and assign them a number, and then the user will say "Click 3" or whatever to specify which one they want. But note the difference in sentence structure between what's spoken "Notify me by text" and the accessible name "Notify me of [notification] by text." Some voice command software does a great job of accounting for this when looking for matches, others not so much. The good ones should be able to parse that and behave as expected. Less good ones might get tripped up, and just highlight every "Notify me" partial match (so, all of the email and text checkboxes). And worse ones might get stuck and not give you a match at all.
   
   The solution here is to have the `aria-label` text string match the visible text string up until you're adding new information, eg. visible text says "Notify me by text" and the `aria-label` says "Notify me by text for [notification type]." The grammar isn't quite as clean but it sets up the voice command software for easier matches.

**Comment by mtcA6** [comment]
@adamwhitlock1 heads up, i think this impacts how you progress through #59940

**Comment by adamwhitlock1** [comment]
I wrapped the heading and any description if present in a legend as recommended and this work is being done and in PR as part of issue [61013](https://github.com/department-of-veterans-affairs/va.gov-team/issues/61013)
