### ISSUE TITLE
Vets-api terminal access for Micah Frazier

### ISSUE THREAD

**Issue by micahaspyr** [department-of-veterans-affairs/va.gov-team#60839]
### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Micah Frazier

### Your GitHub handle (terminal access is managed through GitHub)

@micahaspyr

### Team, Role, and Company of the target individual

Sr Full Stack Engineer

### Product Manager (PM) name and email

Austin Price austin.price@coforma.io

### Product Owner (PO) name and email

Matt Self Matthew.Self2@va.gov

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [x] production (if requesting, justify prod access in 'Additional Notes' section)

### COR Name (leave "None" if you listed an AWS user name above)

Delano McVay

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

Oddball - Amber Malcolm

### Access Expiration

23-06-2025

### User must exist in a roster before vets-api terminal access can be granted

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added
- [ ] If they included an AWS user name, check to see if their user name is listed in [iam_users.tf](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf)
- [ ] Comment in this issue saying which roster the user is listed in and confirming their AWS user name (if applicable)

**Comment by bdech** [comment]
Found in VFS Team Roster

**Comment by bdech** [comment]
E-QIP `Transmittal Notice` found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60227)

**Comment by bdech** [comment]
@micahaspyr You've been granted access to `dev`, `staging`, and `sandbox` environments.

Here is some additional documentation for the [Vets API on EKS](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-TerminalAccess)

**Comment by micahaspyr** [comment]
@bdech I'm needing production Argo access as well.  I'm needing to pull some data to troubleshoot 526 errors we've seen the past few months

**Comment by bdech** [comment]
Access to `prod` is pending approval by OCTODE, and we'll update you as 
soon as it's available.

**Comment by micahaspyr** [comment]
@bdech any update on this?

**Comment by JonathanKamensDVA** [comment]
6-month prod access approved.

**Comment by bdech** [comment]
@micahaspyr You've been granted access Production, access limited to 6 months, expiring 04/20/24.

Please set a reminder for yourself to return to this Issue and 
request an extension within 1 week of the expiration date. You'll 
receive 1 reminder with a 72 hour window to respond. Failure to 
respond will result in your access being revoked and will require 
you to fill out a new request.

**Comment by bdech** [comment]
Slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1697811655704689)

**Comment by bdech** [comment]
@micahaspyr Vets API Terminal Production access has expired.

Would you like to request an extension? You have 72 hours to respond, or your 
access will be revoked and you will need to fill out a new request.

**Comment by micahaspyr** [comment]
@bdech I would like an extension please

**Comment by bdech** [comment]
@LindseySaari @ericboehs can one of you please give us a :thumbsup: to extend their access?

**Comment by micahaspyr** [comment]
@ericboehs I'm on a new team now and troubleshoot code yellow issues.  I got AWS access a few weeks ago for that code yellow initiative so this access might be a bit redundant

**Comment by bdech** [comment]
@micahaspyr, your Production access has been extended for 6 months, expiring 10/22/24.

Please set a reminder for yourself to return to this Issue and request an extension within 1 week of the expiration date. You'll 
receive 1 reminder with a 48 hour window to respond. Failure to respond will result in your access being revoked and will require 
you to fill out a new request.

**Comment by bdech** [comment]
support slack reminder [here](https://dsva.slack.com/archives/C06CY71PCAX/p1714482389255499)

**Comment by bdech** [comment]
@micahaspyr Your Vets API Terminal Production access has expired.

Would you like to request an extension? You have 72 hours to respond, or your access will be revoked and you will need to fill out a new request.
