### ISSUE TITLE
Allow Submission of Travel Claim for 1 Facility Per Day

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#60843]
## BTSSS API Team
Currently in their backlog:
- Creating job to find claims that have been submitted before the appt was completed and sending them back through the rules engine
- Adding API endpoint to get the status of a claim
- Upgrading the performance of claim submission API endpoint
- Adding API endpoint to determine if Veteran is eligible

## Background
After a few days of the pilot, we noticed something off with the claims created by Veterans during the check-in process.  

- What is going on: The claims have been created in the system (yay!), but the status is being set to "Claim Submitted." According to our BTSSS experts, when the claim is created, the appointment is set to "not completed." (See attached screenshot). It's my understanding that claims in this state will not be processed until manual intervention happens. 

- What needs to happen for the claims created this way:  We need to intervene manually. A travel clerk needs to go into the BTSSS CRM system and, for each of the claims created, mark the appointment are completed and then resubmit the claim. Updating and resubmitting the claim will cause the system to reevaluate and process it accordingly. This manual process will have to happen for the duration of the pilot until the engineering team gets this resolved. 

 - What we are doing to resolve this issue:  The engineering team is working through how we can change the submission process from a technical perspective to avoid making these claims un-processable.

## Timeframe
BTSSS API team is projected to be done with their effort to create a new API endpoint for submitted a mileage-only travel claim that accepts both the appt date & the appt time

**Comment by benbrasso-agile6** [comment]
@loripusey does this epic also address the need for Veterans to be able to file when more than 1 appt is scheduled for the day? Or, is that a different epic? 

If this is the right place for that, we might want to create a ticket to update the user flow too https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1677531124203/5edcfd3ea4b1eaf1ef082d56782a8b3291ef3932?sender=u37bb983bd3fc3cc00c7d3286

I can do that, but just want to keep that document up to date.

**Comment by loripusey** [comment]
it does, it includes 

1. Changes to our logic to show the travel questions unless the Veteran has already submitted a claim for the same facility and date
2. Changes to our BTSSS API call to forward the appointment time, which is all they said they would need; apparently if the appointment time is included the code will go down the path of letting multiple claims be filed (1 per facility per date)

**Comment by loripusey** [comment]
done
