### ISSUE TITLE
[FE] Notification Component: GA tracking on "manage your VA debt" seems incorrect

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#60845]
## Background
While testing the notification component on My VA on staging, I was confirming our event tags and noticed that the "Manage your VA debt" link was showing an event tag associated with the date of the notification

## Steps to Reproduce
1. Log into staging with user 221
2. Open console
3. Right click the "Manage your VA debt" link for the notification triggered on May 25 to open the "current VA debt" page
4. See in the console that the GA event is `Navigation - Link Click - Thursday, May 25, 2023 - Thursday, May 25, 2023`  (screenshot in resources section)

## Tasks
- [ ] Correct GA event to be `Dashboard-Navigation-View Link from Notifications - View Manage VA debt`

## Acceptance Criteria
- [ ] Event tag on link within the notification is corrected

## Validation
- _Who can validate this ticket? (FE, BE, Design, PM)?_ Any team member_
- _How can this work be validated?_ repeated steps to reproduce and confirm correct GA tag

## Resources
![Screenshot 2023-06-26 at 9 36 25 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/45603961/a38cc7d4-dd30-4a50-9782-5167514407d9)

**Comment by caw310** [comment]
DST will be working to add analytics to va-notification events. 
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1803

**Comment by ajakabcin** [comment]
Bringing this down to a 0 and moving to sprint 14 until 1803 is complete and we can validate and resolve this

**Comment by allisonlu** [comment]
Can confirm that the close GA event is firing on staging for user 11!

![Screenshot 2023-09-19 at 3 41 38 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8542413/e755897a-e817-45fd-974e-f88fd0cf5d5e)

**Comment by ajakabcin** [comment]
Closing as complete
