### ISSUE TITLE
review instances not pulling drupal content

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#6084]
## Problem Description

It looks like a thing that was missed along the way for the vets-website builds on review instances was pulling content from Drupal. Pages that are directly related to content that's already in vagov-content or vets-website shows up (with a fallback apparently for the homepage), but anything managed by the CMS is missing.

From the vets-website docs, we just need to run `npm run fetch-drupal-cache` before doing the build.. However, due to #5116 we can't actually pull off a build on this small of an instance without OOM'ing the virtual machine. Need to investigate what our possible options might be here to get all of this content loaded if possible.

## AC

- [x] create a new review instance and check that http://foo.review.vetsgov-internal/health-care/how-to-apply/ returns a valid page and not a 404
- [x] ensure that the above isn't succeeding somehow in spite of OOM's

**Comment by jbritt1** [comment]
Fresh review instance for change testing:

![image.png](https://images.zenhubusercontent.com/5d9b3f56add771000187d3a8/06e26609-b9f9-4a10-82aa-19c2ec09a7b7)

**Comment by jbritt1** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/11916
