### ISSUE TITLE
[Technical Discovery] What data on decision letters can we provide so VBA can run a cohort analysis? 

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#60848]
## Value Prop
It would be good if we could provide user data that allowed VBA to compare veteran outcomes between people who used DDL and those who didn't. This would allow us to prove/disprove one of our core hypotheses, that access to DDL would condense the time veterans spend deciding which decision review pathway to pursue. 

## Background

Matt Braoitta at VBA has requested this data so he can run a cohort analysis. he has access to all the claims and user data. 

## Open questions

- [ ] What data do we have access to, if any, that could help Matt run such an analysis? 
- [ ] If we don't have that data, are there other options that could help test this hypothesis using data we DO have? 
- [ ] What are our options? 
- [ ] Is there additional monitoring we could put in place to allow for this kind of analysis in the future (that wouldn't violate privacy/security policy)

## Acceptance Criteria

- [ ] Open Questions answered
- [ ] Assessment documented
- [ ] Recommendation documented

**Comment by kjduensing** [comment]
Consider looking into tokenization for secure, meaningful logs.
