### ISSUE TITLE
[Technical Discovery] Investigating what data we could provide VBA that would allow them to run a cohort analysis on decision letters

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#60846]
## Value Prop

If we were able to compare the time it takes for veterans who used DDL to choose a decision review pathway to those who did not, we'd have evidence to prove/disprove the hypothesis that access to DDL would accelerate the process of choosing a decision review. 

## Background

Matt Braiotta has access to user and claim data such that he can isolate a segment of veterans run a cohort analysis comparing their outcomes to the averages. Unfortunately, the has no way of knowing which veterans used our DDL feature and which have not. 

## Open questions to explore

- [ ] Is there data we could provide that would allow Matt to do such an analysis? 
- [ ] If there is, what would it take to provide it? 
- [ ] If not, are there other approaches that could get us close to the goal of what Matt and VBA are trying to achieve? What are they?
- [ ] De-dupe criteria?

## Acceptance Criteria

- [ ] All open questions answered
- [ ] Assessment of technical possibilities and limitations are documented
- [ ] Recommendation on how to proceed is documented

**Comment by jacobworrell** [comment]
It may be possible to go from DD > user_uuid > participant_id > file_number. We could create a spreadsheet of file numbers to download times.

**Comment by jerekshoe** [comment]
DD > user_uuid (vets_api) > participant_id (BGS) > file_number (VBMS)

**Comment by jerekshoe** [comment]
Caveats:
* Full DataDog (DD) log only go back 30 days
