### ISSUE TITLE
Clarify request empty state content

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#60855]
## Task Description
Clarify request description on list and empty state to help Veterans understand what they are.

## Notes and References
- Go to office hours to get feedback from Danielle on language.

## Acceptance Criteria
- [x] Requests page empty state: Update message to provide more context on what requests are for Veterans who haven't requested any
- [x] Request main page: Update language describing requests

## Deliverables
[Design Spec](https://www.figma.com/file/UhAKGzqeH8vTQ1zuI6U99S/Clarify-request-empty-state-content-%7C-Appointments-FE?type=design&node-id=0-1&mode=design)

**Comment by Cieramaddox** [comment]
@outerpress This is ready for you to take a looksie

**Comment by ldelacosta** [comment]
CAIA ticket created #61540

**Comment by outerpress** [comment]
FYI @Cieramaddox @ldelacosta we decided to keep "pending" as a bucket for requests and future non-scheduled appts like recall letters and referrals. So this ticket is now about clarifying our description of requests in the app.

**Comment by outerpress** [comment]
Next steps: review with Kay to confirm our description of the process is accurate.

**Comment by Cieramaddox** [comment]
Kay approved the content changes to the pending list description and empty state description. Awaiting next steps

**Comment by Cieramaddox** [comment]
@JRRoof Has an epic been created for this?

**Comment by outerpress** [comment]
@Cieramaddox dev ticket is #71716 - the empty state work was already done at some point, so this just updates the single sentence on the request page description

**Comment by outerpress** [comment]
Dev ticket is done, closing
