### ISSUE TITLE
SOCKS access for Tolase Akinwale

### ISSUE THREAD

**Issue by teeshe** [department-of-veterans-affairs/va.gov-team#60887]
### Your Name

Tolase Akinwale

### Your Email

tolase.akinwale@civicactions.com

### Your Role and Team

DevOps Engineer on CMS Team

### Product Manager (PM) name and email

Mike Hollen, michal.hollen@va.gov

### Product Owner (PO) name and email

Erika Washburn, erika.washburn@va.gov

### Access Type Requesting

drupal_developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDOMehgojWl+dV8wG84Pq8lzZ8qEW52j5c6QrAlVZSr9pPUsUohC1i10RpfSguG1AWV0le5zeDfzbCLVIrM3H1QwCernsSeWkSTSyXbblXYwvLWN3FhH5/pexbEfIgjcR3ogRFS2bZbT4DCK2N3cPGhL74v5ILPti859/tjpg5TBnTREuKThv5jcklcvgtNrhf6Eip4TeFG+8v4VIbflmkskal/TXfFdwvmtlYxOkoDsc997tKDL3FqPrzqVOSOBc14Lq9cyqFBhfpoRKFo4ylvwOvav0mJQ46e2/xrob4RktDuHWBsCm2wlqSdZr9Dnu27IpkwAVejWNieKZP5NOlIZe5iGz+ZH9vjDcShkRyTAwenf4vySQgGM2RgAaakX61ealdxpX0ix8o5k4ysjchsEAbsRXyDfQA6DWT+BxvXZUZXHs/kUkroA8I8FjgRExdDfcUnORCJeeSs6ABAn1cvY/CUHxaZvs2pOMThit2XYRC1XGVXu5SUozCTpkmN2vs= takinwale@LAPTOP-U48KAU6N

### E-QIP Transmittal Confirmation

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/39352093/fd98c4de-f1b2-4833-b3b4-2a356d21052c)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by teeshe** [comment]
User is listed in the VFS Team Roster

**Comment by rmtolmach** [comment]
@teeshe  Access granted ✅ 

Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html 

Reach out in #vfs-platform-support if you have any trouble.
