### ISSUE TITLE
Memoize RSA Certificate read as part of configuration.

### ISSUE THREAD

**Issue by saneshark** [department-of-veterans-affairs/va.gov-team#6089]
To avoid repeatedly reading the certificate used to verify JWT signatures we should look to memoize. I think we can just add the read file as a constant or even instance variable in our configuration singleton. Once the singleton is initialized, it should have the instance variable permanently set for that particular EC2 instance and not require further IO/reads

**Comment by kreek** [comment]
PR https://github.com/department-of-veterans-affairs/vets-api/pull/3946, confirmed endpoints still work on staging
