### ISSUE TITLE
More specific tab title descriptions for claim details

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#60900]
## Value Statement
As a veteran, I would like the browser tab title to help me distinguish one claim from another if I have multiple claim tabs open in a browser.

## Context
These are the tab titles we have decided on:

* Status Of June 15, 2023 Compensation Claim | Veterans Affairs
* Files For June 15, 2023 Compensation Claim | Veterans Affairs
* Details Of June 15, 2023 Compensation Claim | Veterans Affairs

## Background 

Relates to a defect coming out of an accessibility audit. Details here [https://github.com/department-of-veterans-affairs/va.gov-team/issues/60176](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60176)

## Acceptance Criteria

- [x] Tab title helps distinguish the claim from other claims
- [x] Title helps veteran identify the claim the tab is for
- [x] Title is not insanely long

**Comment by joshkimux** [comment]
Love this ticket regarding the `title` element! [Fortunate for us we have platform guidance here on page titles](https://design.va.gov/content-style-guide/page-titles-and-section-titles#page-titles)

## Acceptance criteria can be interpreted as:

### Must
- [ ] Use the primary SEO keyword in the page title. On VA.gov, page titles use the H1 tag.
- [ ] Quickly tell people the main purpose of the page—what they can do or what information they can get on that page.
- [ ] Be unique.

### Should
- [ ] Try to keep page titles to 52 characters maximum, with spaces. 

I would also add the following accessibility criteria:

- [ ] The `h1` should be within the page `title` (the page title can be abbreviated provided it maintains words from the original `h1`)

## First intermediary iteration
In our current improvements, we won't be completely redesigning the IA of the page-- meaning we can't solve the big wicked problem at the heart of the issue (the hubless spoke). 

As a result of generic headings (all tabs share the same `h1`), the above governance recommendations are insufficient.

We can get around this by following this pattern:

**[Page name] | [Unique claim card title] | Veterans Affairs**

That being said, the pattern we use depends. I'll reach out to CAIA for content support here.

### Plain language
This prioritizes the language Veterans understand. In research, we learned that Veterans in testing did not use, recognize, or find value in the Claim ID number. We're not sure if this extends to Veterans who use assistive technologies like screen readers as research did not include them.

From this perspective, we could use the submission date as the unique identifier like so:

- Status | Claim for compensation submitted on June 15, 2023 | Veterans Affairs
- Files | Claim for compensation submitted on July 4, 2023 | Veterans Affairs
- Overview | Claim for compensation submitted on January 24, 2022 | Veterans Affairs

That being said, within the context of tabs, users will likely only see:

- Status | Claim for comp...

Which makes it impossible to tell the difference between open tabs. These titles also all go beyond the 52 character recommendation.

### Unique readability using IDs
We could change how we approach this by focusing on empowering Veterans to tell tabs apart by using the claim ID. For example:

- Status | Claim #600392913 | Veterans Affairs
- Files | Claim #60034134 | Veterans Affairs
- Overview | Claim #60039214 | Veterans Affairs

These keep the title character count below the suggested 52 character recommendation, but the IDs themselves won't provide much utility beyond simply differentiating one from tab from another.

**Comment by joshkimux** [comment]
## Update 8/2/23

### Governance office hours
I met with the governance team during their office hours. They recommended:
- being consistent with language when possible AND
- ideally keeping the language briefer when possible
- reaching out to the CAIA content team for further suggestions on the page title, specifically around "| Veterans Affairs"

### Async discussion with Skyler @skylerschain 
I routed those suggestions back to Skyler, who noted a preference for a conversational approach and pointed out the current language tested well with Veterans.

### Next steps
I'm going to schedule a meeting with the CAIA content team to determine the following:
- Is it OK for us to maintain the conversation `h2` "What's happening with your claim" if we can reason it is equivalent to "status"?
- Is it a requirement to include "| Veterans Affairs" in the title element? If so, is it ok if we go past the 52 character limit count with `Status | Claim for compensation submitted on June 15, 2023 | Veterans Affairs`

**Comment by uxgary** [comment]
Update: Placed a comment for the CAIA team in an[ existing ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/61696); awaiting feedback.

**Comment by uxgary** [comment]
After meeting with Skyler, Kristen and Laura (from CAIA team), we have decided on the copy for the browser tab title and breadcrumb titles. Both of which will update when veterans click on the, status, files and overview tabs in CST. The approved content are as follows:

**New browser tab title**

- Status of June 15, 2023 compensation claim | Veterans Affairs
- Files for June 15, 2023 compensation claim | Veterans Affairs
- Overview for June 15, 2023 compensation claim | Veterans Affairs

**New breadcrumb to read:** 

- Status of compensation claim
- Files for compensation claim
- Overview of compensation claim

**Comment by HeatherWidmont** [comment]
@jerekshoe is going to create separate tickets for the implementation of this work (thanks Jerek! 😆 ) 

@skylerschain will post a link to the mocks once he creates them

**Comment by skylerschain** [comment]
Hey @kristinoletmuskat and @laurwill: After meeting with our engineering team, it seems the breadcrumbs we decided on above would be hard to implement. The reason is that including the claim type dynamically is not technically feasible. 

So instead of "Status of compensation claim" we are thinking of making the breadcrumb simply "Status," "Files," and "Overview." Any concerns with this? I've attached some mocks of how this would look below. 


![StatusTab](https://github.com/department-of-veterans-affairs/va.gov-team/assets/95102058/9f647e99-7297-407f-9131-05a7e8e78140)

![FilesTab](https://github.com/department-of-veterans-affairs/va.gov-team/assets/95102058/b84237eb-f22d-4883-b074-8cdb553343ef)

![OverviewTab](https://github.com/department-of-veterans-affairs/va.gov-team/assets/95102058/fc687b0a-f943-4399-a760-414286e45e0e)

**Comment by kristinoletmuskat** [comment]
@skylerschain I'm still concerned that the breadcrumb wouldn't indicate that the user is on a specific claim. What is we just added the word "claim" to the front of the breadcrumb" Ex: Claim files, Claim status, Claim overview. Do all the different claim types at least have "claim" in the name?

**Comment by jerekshoe** [comment]
Are we sure that the words "For" and "Of" should be capitalized in the tab titles? It's unusual to capitalize either of those words when used in a sentence

**Comment by kristinoletmuskat** [comment]
Ugh this is a tough one with the breadcrumbs. Could we just pull the H1 into the breadcrumb and then append the tab name onto that? So instead of pulling in the claim type dynamically, we're just pulling in the H1. 

Example 1:
H1 = Your compensation claim
Tab = Status
Breadcrumb = Status of your compensation claim

Example 2:
H1 = Your board appeal
Tab = Files
Breadcrumb = Files for your board appeal

@uxgary @jerekshoe

**Comment by jerekshoe** [comment]
It's possible, but we won't ever be able to move the breadcrumbs into content-build if we go this route. Also, we are not touching appeals currently

**Comment by jerekshoe** [comment]
Also, we haven't changed the tabs in the details page yet, so I don't know if it makes sense for the titles to not align to the tab names?

**Comment by jerekshoe** [comment]
@skylerschain @uxgary This is what I am planning on going with for now for the tab titles:
* Status tab: Status Of June 15, 2023 Compensation Claim | Veterans Affairs
* Files tab: Files For June 15, 2023 Compensation Claim | Veterans Affairs
* Details tab: Details Of June 15, 2023 Compensation Claim | Veterans Affairs

**Comment by skylerschain** [comment]
@jerekshoe Can you speak more to the downside of not being able to move the breadcrumbs to content-build? And am I right to assume that means we can't manage it from Drupal? Or does that mean something else?

**Comment by skylerschain** [comment]
The browser tab titles you listed above look good though @jerekshoe. Should we keep this ticket open so we don't forget to update the Details tab to Overview when the time comes? Or spin up a new ticket? @jerekshoe defer to you on how you want to operationalize that.

**Comment by jerekshoe** [comment]
I think it'd be better to add the tab titles matching the tab names as acceptance criteria for the ticket for updating the tabs themselves. I'd like to close this ticket and anything related to breadcrumbs can continue in this ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/64883
