### ISSUE TITLE
[FE] Add direct deposit error for people who have fiduciary/are deceased

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#6090]
## Background
Tressa will be updating the direct deposit screen to reflect security enhancements related to no longer showing the "direct deposit" option if the user has been determined to be incompetent or has a fiduciary"

Reference #6094 

These are the relevant indicators:

PPIU API   control information | PPIU conversion from BGS | BGS   EBenefitsAddressUpdateWebService | BGS definition
-- | -- | -- | --
isCompetentIndicator | True if incompetentInd is not ‘Y’ | incompetentInd | incompetentInd – whether the Veteran   is incompetent or not
noFiduciaryAssignedIndicator | True if fiduciaryInd is not ‘Y’ | fiduciaryInd | fiduciaryInd – whether the record has   a Fiduciary or not

## Tasks
- [ ] Make necessary updates to the frontend to ensure the Direct Deposit info no longer appears based on user attributes based on Tressa's updated design changes

## Acceptance Criteria
- [ ] Direct Deposit info no longer available/visible  if user is incompetent or has a fiduciary

**Comment by mshea0606** [comment]
@tressaellen Can you put you Direct Deposit Screen mockups in here when complete? Thanks!

**Comment by tressaellen** [comment]
@mshea0606 sure thing! Content is taking a look at it now and I'll make any updates and drop it in here.

**Comment by erikphansen** [comment]
I'm adding a link to this ticket where the design/copy discussion took place https://github.com/department-of-veterans-affairs/va.gov-team/issues/6094

**Comment by erikphansen** [comment]
I bumped this from a 1 to 2. I was under the impression that this alert was going to go inside of the direct deposit component. But since the alert lives at the top of the profile section it's more involved than I expected.

**Comment by erikphansen** [comment]
@mshea0606 The work for this was merged. You can see the new alert on the profile using user 33
