### ISSUE TITLE
Design System Staging Review - IA Feedback - Maintenance Banner web component

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#60910]
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

#### Number of banners
- DS guidance for this component says that up to 3 banner components can be added at once. Does this mean three _maintenance_ banners at once, or three total banners of any type (including the "this is a government website" default banner)? 
  * This particular type of banner reads as an alert. Since we typically provide guidance not to stack alerts, I wonder what your team thinks about clearer limitations on alert-style banners? (especially if a hyperlink in the alert is likely - this would potentially mean stacking multiple possible task interruptions).
#### Content confusion
- I don't understand the meaningful difference between the [two content options](https://design.va.gov/content-style-guide/error-messages/system) for each of _advance notification_ and _during downtime_ scenarios (image below). Do we need two? With that said, some issues with the content as it is blocked out:
  * Problematic field label: "Start/End time" puts two concepts together on the same line  without plain language - this could be difficult to parse / be confusing for people to understand.
  * Problematic field label: "Date" as it is written in the scheduled downtime notification table (image below) looks fine, but in the component UI it doesn't follow its own guidance - it doesn't spell out the day, date, and year (uses integers instead) and adds in a time (see other image below). This conflates two concepts but the label only describes one: "Date."
  * Labels enhance IA and improve usability by making things really easy to scan. But, when the label doesn't match or clearly convey what will comes after it, it does the opposite. Either ensure the bolded labels are very clear, or alter approach to build out a sentence in plain language with the same information (e.g. Maintenance will begin on Thursday, June 29th at 11:00pm and continue until Tuesday, July 4th at 11:59pm). Consult with @CherylEvans and CAIA if you need content help.
 <img width="1026" alt="Screenshot 2023-06-26 at 4 16 26 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/115033532/a23fe9ac-e438-45a0-839e-9b77b9ae4938"> 

#### Metadata 
- Metadata fields for this component do not match field outputs in a meaningful way - this may trip up FE designers. I recommended using unique metadata language that points to a clear field output (do not use close linguistic matches for different fields - e.g. "starts at" and "warn-starts-at" within the same component - the difference between these is not clear and designers may flip flop them accidentally) 
<img width="804" alt="Screenshot 2023-06-26 at 3 56 47 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/115033532/5db76416-1971-4ca1-b264-688865287cdf">

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

#### Hyperlink in component
- **Must**: In Storybook and the DS guidance (hyperlink is not included on Sketch instance) for this component, the planned maintenance example has a hyperlink included, but there are no behavioral guidelines around it. What are allowed hyperlinks (if customizable) or where does it direct users (if standard)? Since these banners have global site presence, a link could be a potential task interruption (depending on where a user is / what they're doing on the site). Can we add in guidance that hyperlinks should be used with caution?
<img width="771" alt="Screenshot 2023-06-26 at 3 25 40 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/115033532/2002ee9b-9c81-4160-a41a-9763735387c3">. 

#### Required vs. optional elements 
- **Should**: Clarify what is optional vs. required. For example, it seems possible that maintenance "end" time may be unknown. Can a designer remove the "expires-at" field if they don't know an end-time?

**Comment by powellkerry** [comment]
@sterkenburgsara @taylojill Here is what I have come up with in regards to making the meta-data fields more readable and updating the verbiage /labels surrounding the date/time fields of the component. Let me know if I should change anything or if something doesn't make sense.

**Meta-data/properties:**
![Screenshot 2023-07-06 at 1.48.01 PM.png](https://images.zenhubusercontent.com/620ff46ada91444aac696d7b/79bdbd47-66a8-4ee4-9f8b-e8c3a68cfbf9)!

**Update showing change to separate out date and time as well as display duration field:**
*This change was made on both the upcoming maintenance warning and the active maintenance alert to be more consistent.
![Screenshot 2023-07-06 at 1.57.44 PM.png](https://images.zenhubusercontent.com/620ff46ada91444aac696d7b/00db0fcf-78ab-4a7e-8b5c-4c9e2a9f2096)

![Screenshot 2023-07-06 at 1.58.06 PM.png](https://images.zenhubusercontent.com/620ff46ada91444aac696d7b/407ddce1-4c8e-47e1-a589-18088d0effd5)

**Comment by taylojill** [comment]
Hi @powellkerry Your changes look good to me.
