### ISSUE TITLE
[Dependabot] Add Terraform to Dependabot

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#60926]
# Description
Use dependabot to keep Terraform Providers up-to-date

# Notes
- Dependabot docs, https://docs.github.com/en/code-security/dependabot
- Example: https://github.com/department-of-veterans-affairs/vsp-platform-infrastructure/blob/main/.github/dependabot.yml
- This should be done for revproxy, fwdproxy, and VPI repos

# A/C
- [ ] `dependabot` is configured to check our Terraform Providers for updates

**Comment by Efe-Oddball** [comment]
Pushed out a PR for the VPI repo. Will resolve ticket once PR is merged

**Comment by Efe-Oddball** [comment]
We cannot merge this at this time because not all providers are managed within the terraform modules. There are some providers that are managed within the terragrunt wrapper configuration and dependabot does not work with terragrunt wrapper directly. So we have to architect a solution to make sure all providers gets updated

**Comment by Efe-Oddball** [comment]
The proposal is to
1. Write a workflow that extracts provider blocks from terragrunt.hcl and saves the extract in a .tf file, e.g. providers.tf
2. Run dependabot directly against the newly created provider.tf file
3. Once dependabot updates for provider.tf files have been merged,
4. Run another workflow to make the changes and create a PR to merge the updates to terragrunt.hcl

**Comment by Efe-Oddball** [comment]
this ticket will require more than a 3 pointer

**Comment by Efe-Oddball** [comment]
I have created workflow to extract a required_providers.tf file that contains the providers configured within terragrunt. Now trying to figure out how best to get dependabot to target the extracted file

**Comment by Efe-Oddball** [comment]
This ticket will have to roll over

**Comment by Efe-Oddball** [comment]
Testing a workflow today to create PR after dependabot makes any commits to the terragrunt-dependabot branch. I am just trying to automate the system as much as I can

**Comment by Efe-Oddball** [comment]
The intention was to automate the whole process, but our enterprise Github is currently not configured to Allow GitHub Actions to create and approve pull requests. As a result, the automation process at this time stops at the creation of a new branch with the updated terragrunt.hcl. A PR has been pushed out for that and the ticket will be closed once approved and merged. Moving ticket to a review stage.

**Comment by Efe-Oddball** [comment]
Revproxy and Fwd proxy repos do not have providers defined within terragrunt.hcl. Moving this ticket to a resolved state
