### ISSUE TITLE
Analytics Implementation for 22/1995

### ISSUE THREAD

**Issue by jonwehausen** [department-of-veterans-affairs/va.gov-team#6092]
# Analytics Implementation or QA Request

## Description
**Tracking needs**: (https://app.zenhub.com/files/133843125/61b7c180-8f9b-4652-ba4a-53efd9dd5190/download)

- Who is this request for?
    - [BAH - Amy Knox, Theresa McCurdo, Cindy Cruz]

    
- What team/project is this work for?
      - Education - Booze Allen Hamilton -  Form 22/1995
    
- Provide the Domain where Google Analytics needs to be implemented
    _i.e. www.staging.va.gov_
    - **Form starting point**: https://bahdigital.invisionapp.com/share/9GIACS4WX82#/screens/296030718
    - **Updated STEM questions**: § https://bahdigital.invisionapp.com/share/9GIACS4WX82#/screens/296030728
    - **NEW Ineligibility alert page**: https://bahdigital.invisionapp.com/share/9GIACS4WX82#/screens/296030743
    
- Please provide any upcoming deadlines or important milestones
    _Week of March 9_ 

- Test Users to replicate the event _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

## Acceptance Criteria
- [ ] Datalayer has been implemented
- [ ] Google Tag Manager configuration has been completed
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
## DRAFT - Datalayer Requirements - Pending @nedierecel's review

### 1) When veterans reaches ineligible message

**Screenshot of message**
![image](https://user-images.githubusercontent.com/48527022/75294145-b1370b00-57f5-11ea-896b-97359211f987.png)

**Perform the following dataLayer push on any of the following interactions:**
   - Continue click
   - Explore other benefits click (green button displayed when 'No' is selected) 
   - Finish later click
   - Back click
   - Browser closed (abandon) 
```javascript
dataLayer.push({
  'event': 'edu-1995--formStepEvent', 
  'edu-formStepLabel': 'education-benefit', //remain consistent for all interaction on the 'Education Benefits' step
  'edu-formStepNavigation': 'continue-click', //'explore-other-benefits-click', 'finish-later-click', 'back-click', 'browser-close'
  'edu-ineligibleStillApply': 'yes' //or 'no', 
});
```
### 2) When the veteran SUBMITs the form, add the following dataLayer variable to the existing ```'edu-1995--submission-successful'``` event push based on the veterans response to the new question

**Screenshot of question**
![image](https://user-images.githubusercontent.com/48527022/75296902-7be1eb80-57fc-11ea-9ab4-1d6bb5997675.png)

**Add this dataLayer variable**
```javascript
'edu-exhaustedAllBenefits': 'yes' //or 'no'
```

### 3) When the veteran clicks on any of the links within the STEM scholarship block
**Screenshot of section**
![image](https://user-images.githubusercontent.com/48527022/75297258-5b666100-57fd-11ea-99ec-8acc3e1fb1f9.png)

**Execute this dataLayer push**
```javascript
dataLayer.push({
   'event': 'edu-1995-linkClick', 
   'edu-1995-clickLabel': 'Check remaining benefits' //dynamically populate according to click label text
});

**Comment by nedierecel** [comment]
@jonwehausen Thanks for including me in the review. Please see feedback by each requirement.

1. Mid-form dataLayer push
- Existing Tag: If you think it aligns with your logic and intent, there is an existing tag for "Education Navigation" with a look up table: https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/734

- Approach: I think you're right that this is an edge case, where we don't typically configure events at the continue or back level. Do you think this should be handled like a `gibct-formChange` whereby it happens at time of selection? My concern is how this might be sent with the browser close. 

2. This looks good--thanks for making it a global solution
3. I recommend using the `edu-navigation` event that exists in GTM now. You could use the look up table built within this tag to form the "Event Action".

**Comment by jonwehausen** [comment]
Hi @nedierecel,

Thanks so much for your recommendations! I have updated the above comment to be version 1.1 with the latest requirements. 

Thanks!

**Comment by amyknox** [comment]
@jonwehausen It looks like you have two #3's in comment v1.1 above. 

3) When the veteran SUBMITs the form, add the following dataLayer variable to the existing 'edu-1995--submission-successful' event push based on the veterans response to the new question
and
3) When the veteran clicks on any of the links within the STEM scholarship block

The screenshot that accompanies the first #3 doesn't look like it goes with the description (screenshot: exhaustion of benefits question; datalayer push: form submission success )

**Comment by jonwehausen** [comment]
Hi @amyknox,

Oops! Thanks for your observations. I have corrected the numbering above. 

Regarding now #3 above, apologize if the screenshot was confusing... To clarify, we want to add the dataLayer variable  ```'edu-exhaustedAllBenefits'``` to the existing ```'edu-1995--submission-successful'``` event at time of form submission. cc: @nedierecel 

@nedierecel Keep us posted on the status of your final review given the most recent updates. 

Thanks
Jon Wehausen

**Comment by nedierecel** [comment]
@jonwehausen Confirming receipt--I have some recommendations on the continue and back buttons, so I'll thread in a discussion on Slack.

**Comment by jonwehausen** [comment]
@nedierecel Have updated the requirements above based on our conversations from last week: 
- Removed continue/back button events as were deemed unnecessary 
- Updated screenshot and datalayer to only perform the push on ```explore-other-benefits``` and ```finish-later```
- Updated screenshot of sequence segments to reflect explore other benefits scenario

**Comment by nedierecel** [comment]
@jonwehausen @amyknox This is approved.

Jon, once data is available on Staging, you and I can look at the various report options (segments, custom funnels, and behavior flow). Thanks.

**Comment by hughes-dustin** [comment]
@jonwehausen @nedierecel The "Finish this application later" link is a platform specific. We don't have any control over it in 1995 so I don't think we can push any event to the `datalayer` there. 

I did notice however the the action is being tracked as` event: "edu-1995-sip-form-saved"` in the `datalayer`.

**Comment by jonwehausen** [comment]
@hughes-dustin Thanks for the note here -- Okay, that is fine. We can do without and utilize the existing event where needed.

**Comment by hughes-dustin** [comment]
branch: bah-6092
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/11824

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-03-06 at 11.01.01 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/d9013496-4560-41b7-a547-a67c8ca0bd87)
##
![Screen Shot 2020-03-06 at 11.02.12 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/50178fbf-d46d-4f58-b6be-f671b75cb85f)

**Comment by sonntag-adam** [comment]
@jonwehausen, @amyknox, @nedierecel

**Comment by nedierecel** [comment]
Thanks @sonntag-adam - Has this also been pushed to staging? We updated a few settings in Google Tag Manager that we need to validate.

**Comment by jonwehausen** [comment]
Hi @sonntag-adam ,

Thanks again for your work here! We really appreciate it.

Through our testing, we noticed a small update to correct -- We noticed a **'Yes'** radio button selection of "_Have you used all of your Post-9/11 GI Bill or Fry Scholarship benefits or do you have less than 6 months of benefits left_?" is populating with **'No'** at form submission for the ```edu-exhaustedAllBenefits``` dataLayer variable. 

Please see screenshot. 
![image](https://user-images.githubusercontent.com/48527022/76362185-f0398600-62f6-11ea-8503-791fc83b2a9d.png)

### Remaining Validation

## ✔️ STEM Scholarship Radio Button
- Validates the on-click event tag for Yes and No
![image](https://user-images.githubusercontent.com/48527022/76362528-94233180-62f7-11ea-81c2-2c4578c9da33.png)

## ✔️ 'Explore Other Benefits' 
- Validates the on-click event tag for Explore Other Benefits
![image](https://user-images.githubusercontent.com/48527022/76362664-ccc30b00-62f7-11ea-8b66-b6b4e12a51fc.png)

**Comment by hughes-dustin** [comment]
@jonwehausen 

Can we get a little more information? I've attempted to recreate the scenario but am getting the expected results. 

![image.png](https://images.zenhubusercontent.com/5c98ddbd98ed1e00013adfec/383f28a1-aee2-422e-88a3-fbe5096685aa)

**Comment by hughes-dustin** [comment]
For `exhaustionOfBenefitsAfterPursuingTeachingCert` tracking:

Branch: bah-6092-2
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/11868

**Comment by jonwehausen** [comment]
Hi @hughes-dustin ,

Thanks, the ```edu-exhaustedAllBenefits``` seems to be working fine, ran a couple more tests to confirm. 

![image](https://user-images.githubusercontent.com/48527022/76429126-fc6c2480-6384-11ea-9d57-fac9cb24c6c2.png)

**Comment by sonntag-adam** [comment]
@jonwehausen here is an update with your prior selection of 

edu-stemApplicant: "Yes"
edu-undergradStem: "No"
edu-pursueTeaching: "Yes"

Is this what we want for functionality? 

![Screen Shot 2020-03-11 at 10.45.05 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/1ca36b47-40eb-46a5-8d99-36dfe646adcc)
##
![Screen Shot 2020-03-11 at 10.46.40 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/bedfcc99-8732-4e66-bbd6-64e84a89204a)

**Comment by jonwehausen** [comment]
Hi @sonntag-adam ,

Thanks for confirming. Yes -- this is correct. 

@hughes-dustin is confirming this functionality also for when the Pursuing Teaching question is **NOT** surfaced. Like in the screenshot below. 

![image](https://user-images.githubusercontent.com/48527022/76435256-275a7680-638d-11ea-8cab-f47856cbfae3.png)

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-03-12 at 7.13.20 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/7aec1a4b-34f2-4c2c-8f8b-6d7ad5030067)
##
![Screen Shot 2020-03-12 at 7.16.28 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/7c5eab41-744d-44b3-b73d-8328a712e3c0)

**Comment by nedierecel** [comment]
@jonwehausen Confirming I am reviewing now so changes can be published.

**Comment by jonwehausen** [comment]
@nedierecel @sonntag-adam @hughes-dustin @amyknox 

Confirming this has in fact been published. Closing.
