### ISSUE TITLE
Please update this site to reflect proper API for Centralized Mail Portal

### ISSUE THREAD

**Issue by timothy-wagner** [department-of-veterans-affairs/va.gov-team#60936]
### Description
Please change the site to direct developers to the OBI-BTS's Benefits Intake API provided by lighthouse.  The current information on this site, https://depo-platform-documentation.scrollhelp.site/developer-docs/central-mail-api, is outdated and incorrect.  It does not provide error handling among other things. 

### Relevant URLs
https://developer.va.gov/explore/benefits/docs/benefits?version=current

### Which type of team are you on? (Platform team, VFS team, or Leadership)
OBI-BTS

**Comment by vbellissimo** [comment]
Platform support Slack thread started: https://dsva.slack.com/archives/CBU0KDSB1/p1687877047404279

**Comment by tbaker1026** [comment]
@vbellissimo 

Content Updates:

Header: Central Mail API (Deprecated)

Please use the \[Benefits Intake API\](https://developer.va.gov/explore/api/benefits-intake/docs?version=current)

NOTE:  not sure how you usually handle deprecated content on the site.

**Comment by vbellissimo** [comment]
@timothy-wagner @tbaker1026 @PSIEBENLIST just confirming we've updated this page to ensure the user knows this API was deprecated and provided a link to the appropriate place. Thank you all.

**Comment by timothy-wagner** [comment]
Looks good to me.  Thank you!  Much appreciated!

Tim Wagner
Program Analyst
Veterans Benefits Administration
Office of Business integration (20C)
Mobile - 224-275-4141
***@***.******@***.***

From: Vicky Bellissimo ***@***.***>
Sent: Tuesday, August 22, 2023 10:36 AM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Wagner, Timothy D., VBAVACO ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Please update this site to reflect proper API for Centralized Mail Portal (Issue #60936)


@timothy-wagner<https://github.com/timothy-wagner> @tbaker1026<https://github.com/tbaker1026> @PSIEBENLIST<https://github.com/PSIEBENLIST> just confirming we've updated this page to ensure the user knows this API was deprecated and provided a link to the appropriate place. Thank you all.

-
