### ISSUE TITLE
Lighthouse increase in 502s and 504s

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#60934]
## Description

[Original Ticket from TT1.](https://app.zenhub.com/workspaces/platform-tech-team-1-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/56968) See ticket for additional details.

Lighthouse is reporting 504 errors at the Kong layer after the Vets API migration to EKS. This mainly impacts the `/internal/auth/v2/validation` endpoint which is hosted in Vets API. The onset of these reported errors coincides with the timeline of the EKS migration that took place on April 9th.

## What is a 504 Error?
A 504 error is a Gateway Timeout error. This typically indicates that a server acting as a gateway or proxy did not receive a timely response from an upstream server it needed to access in order to complete the request.

In our context, the "proxy" latency reported by Kong refers to the time it took for the final service (which could be the Load balancer, traefik, or the pods based on our request chain) to process the request.

## The Request Chain
Our request chain for `/internal/auth/v2/validation` is as follows. `/internal/auth/v2/validation` is a Lighthouse endpoint, but resides in Vets API.

https://api.va.gov -> revproxy -> kong -> [load balancer](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/applications/platform-eks-clusters/alb.tf) -> api.va.gov:8000 (kong, again) -> traefik -> pod`

### Discovery
Upon investigation, we have discovered 504 logs [from ECS ](https://console.amazonaws-us-gov.com/ecs/v2/clusters/dvp-prod-ecs-api-gateway-cluster/services/dvp-prod-ecs-api-gateway-service/logs?region=us-gov-west-1)for the API gateway. Interestingly, the volume of 504s logs reported by Lighthouse are **not** apparent at either the pod or the Traefik layer. This implies that latency issues or errors might be occurring **prior** to the requests reaching the Traefik layer, thereby indicating that the issue likely originates from the Load Balancer.

We did update the AWS node termination handler, which was causing 504s at the traefik layer during node scaling events, but 504s are still persisting via Kong. Additionally, we adjusted the preStop command, startup and readiness probes (many iterations and different combinations).

## Impact
While there are some 504s at the traefik layer, they only amount to ~200 in a 1-day window. This doesn’t align with the thousands that Lighthouse is reporting.

### Example
From 2:11-3:11pm ET on Friday 6/16. Only 1525/307k total requests to `internal/auth/v2/validation` resulted in a 504. .5% amounts to than 1% of requests. If we were to take OVERALL requests into consideration, the percentage of 504 errors would be significantly less.

## ECS Logs
You can find relevant logs in ECS by using `"http://api.va.gov:8000/internal/auth/v2/validation" "\"status\":504"` as a filter. Access API Gateway (Kong) ECS [logs here](https://console.amazonaws-us-gov.com/ecs/v2/clusters/dvp-prod-ecs-api-gateway-cluster/services/dvp-prod-ecs-api-gateway-service/logs?region=us-gov-west-1).

## Datadog 

The [Datadog Dashboard for monitoring 502s and 504s ](https://vagov.ddog-gov.com/dashboard/pcv-wee-xf3/lighthouse-502--504-errors?from_ts=1687283080088&to_ts=1687455880088&live=true) was created to gain visibility into issues at the traefik and pod layers. Data surrounding scaling events, HPA metrics, memory and CPU can be found on the board as well.

## Possible next steps

1. Look at metrics like request count, active connections, latency, and error rates at the load balancer level. If the Load Balancer is overloaded or experiencing other performance issues, it might be reflected in these metrics.
2. Check load balancer, traefik and pod scaling events. Do the 504s align with a scalin event?
4. Check the Load Balancer's timeout settings?
6. Ensure the health checks are correctly configured on the Load Balancer
7. **Scaling the Load Balancer:** If your Load Balancer is under heavy load, you may need to scale it up or out to handle more traffic.

Note: Something happened when we shifted to EKS. We seem to have ruled out traefik and the pods, which is why we've landed on the Load Balancer.

## Additional Links
- [Thread with Derek Brown and team from Lighthouse](https://dsva.slack.com/archives/C04M7T1CZAS/p1685970319728599)
- [Datadog Dashboard for monitoring 502s and 504s ](https://vagov.ddog-gov.com/dashboard/pcv-wee-xf3/lighthouse-502--504-errors?from_ts=1687283080088&to_ts=1687455880088&live=true)

**Comment by pjhill** [comment]
The first thing that DevOps COP needs to do with this ticket is do some basic analysis of the problem and get our bearings on this ticket.

**Comment by pjhill** [comment]
* May be related to a recent issue that bubbled up through support regarding 499 errors. This issue came up the week of 7/27 or the previous week.
* Recently, Hector ran down an issue with VA Notify team about 499 errors. Error trail appeared to end with client side issues.

**Comment by hgbarreto** [comment]
Haven't been able to give this issue the deeper attention it needs. Parking it back in the backlog.

**Comment by ericboehs** [comment]
This has been solved as of Monday by increasing our Puma thread count to 8 and the worker count to 6. We've monitored this over the past few deploys and no issues regarding the 502/504s. This is because we've overprovisioned our resources. A follow-up initiative to tune our Vets API infra will be created.
