### ISSUE TITLE
Update the URL and title page on the appointments details page (MHV on VA.gov) - Upcoming/Booked Appointments

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#60946]
## Description
The Appointments application will be under the MHV on VA.gov portal. We will need to update the title page and URL structure. #60946 will focus on the appointment details page for booked/upcoming appointments. 

---

## Acceptance Criteria
Background: the `va_online_scheduling_breadcrumb_url_update` toggle is on

- [x] Given the user is on the MHV on VA.gov portal
        When the user clicks on `Upcoming VA appointments`, user will land on the Appointments landing page
        And the user clicks on `Details` link for a booked appointment 
        Then the URL will be updated to: https://va.gov/my-health/appointments/[ID]
        And the page title will be [`VA appointment on [Weekday], [Month] [DD], [YYYY] | Veteran Affairs`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/appointment-details.md#va-in-person---upcoming)

- [ ] Given the user is on the MHV on VA.gov portal
        When the user clicks on `Upcoming VA appointments`, user will land on the Appointments landing page
        And the user clicks on `Details` link for a canceled booked appointment 
        Then the URL will be updated to: https://va.gov/my-health/appointments/[ID]
        And the page title will be [`VA appointment on [Weekday], [Month] [DD], [YYYY] | Veteran Affairs`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/appointment-details.md#va-in-person---upcoming)

- [ ] Given the user is on the MHV on VA.gov portal
        When the user clicks on `Upcoming VA appointments`, user will land on the Appointments landing page
        And the user clicks on `Details` link for a Community Care booked appointment 
        Then the URL will be updated to: https://va.gov/my-health/appointments/[ID]
        And the page title will be [`Community care appointment on [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/appointment-details.md#community-care-appointments)

### Reference
[Spike ticket #54757](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/54757)

### Design Assets
[Title tag format guidance](https://design.va.gov/content-style-guide/seo#title-tags)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by ldelacosta** [comment]
@young1205 - please have the UX team validate this ticket when it's ready cc: @JRRoof @outerpress

**Comment by Cieramaddox** [comment]
@young1205 This has been validated by UX.
