### ISSUE TITLE
Update the URL and title page on the confirmation details page (MHV on VA.gov) - Upcoming/booked appointments

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#60948]
## Description
The Appointments application will be under the MHV on VA.gov portal. We will need to update the title page and URL structure. #60948 will focus on the appointment confirmation page for booked appointments. 

---

## Acceptance Criteria
Background: the `va_online_scheduling_breadcrumb_url_update` toggle is on

- [ ] Given the user is on `Upcoming VA appointments` landing page, 
        And the user clicks on `Start Scheduling` button and books an appointment
        Then the URL will be updated to: https://va.gov/my-health/appointments/[ID]?confirmMsg=true
        And the page title will be [`VA appointment on [Weekday], [Month] [DD], [YYYY] | Veteran Affairs`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/appointment-details.md#va-in-person---confirmed)

### Reference
[Spike ticket #54757](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/54757)

### Design Assets
[Title tag format guidance](https://design.va.gov/content-style-guide/seo#title-tags)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by ldelacosta** [comment]
@young1205 - please have the UX team validate this ticket when it's ready cc: @JRRoof @outerpress

**Comment by Cieramaddox** [comment]
@young1205 This ticket has been validated by the UX team
