### ISSUE TITLE
Access for Derek Brown

### ISSUE THREAD

**Issue by dbrown-va** [department-of-veterans-affairs/va.gov-team#6095]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Courtney Bethea
- Please provide your name.
   > Derek Brown
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > LAP, Liberty IT Solutions, Software Engineer
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Internal%20Tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCtJJHMpimT9bxzh6dlzZgzYt8zMRUOmvwgATrzNpwiR02fe/yy3OA8vb53T5Mq+Qt8Yvj3czY2RicT25zL2CeC52Dx16mkuawFFgTK9WV6y1ClmeiIO/r1etHRvEOHI63hulUpvADW8XffZDA2IufQKO8sYj0LY7+xqcl60Y0ET4yvHADtUX0AY+aRwSuBboMHKLKJeTJGh8fKzd6TZvEfR7sAhQ/9QbyveHxfPhUkCcDIRHONSZP0uSvo4hbOjKtgaRWxFXMGajova9QxcRCF2fXin4BBYtiBVCUKotkinTZuy+sR8j6fO/77EFGHu+2M1nkjNser6ZbjVaCLonfp AzureAD+DerekBrown@DESKTOP-DBROWN
```

- [Grant AWS Console access?]
  > NO
  >  AWS console access already granted. Just need the SSH key above.

**Comment by dbrown-va** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by ricetj** [comment]
SOCKS access is granted. You should now refer to this [section](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) in the instructions to set up your SOCKS.
