### ISSUE TITLE
Update the breadcrumb on the appointments details page (MHV on VA.gov) - Upcoming/Booked appointments

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#60955]
## Description
The Appointments application will be under the MHV on VA.gov portal. We will need to update the breadcrumb structure. #60955 will focus on the booked appointments page. 

---

## Acceptance Criteria
Background: the `va_online_scheduling_breadcrumb_url_update` toggle is on

- [x] Given the user is on the MHV on VA.gov portal
        When the user clicks on `Upcoming VA appointments`, user will land on the Appointments landing page
        And the user clicks on `Details` link for a booked appointment , the breadcrumbs will be updated to `< Back to [h1 of previous page]`

- [x] Given the user is on the MHV on VA.gov portal
        When the user clicks on `Upcoming VA appointments`, user will land on the Appointments landing page
        And the user clicks on `Details` link for a canceled booked appointment , the breadcrumbs will be updated to `< Back to [h1 of previous page]`

### Reference
[Spike ticket #54757](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/54757)

### Design Assets
[Title tag format guidance](https://design.va.gov/content-style-guide/seo#title-tags)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by jenniemc** [comment]
@ldelacosta, The AC for this ticket was completed in #61086 . Closing this ticket

**Comment by ldelacosta** [comment]
Validated the changes in staging for judy.morrison@id.me 

![Screenshot 2023-08-02 at 2.48.56 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/eeec6f5f-fe8d-44d9-9a0d-c4afc2d0843d)
![Screenshot 2023-08-02 at 2.49.41 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/188e6a66-5445-4dcf-befc-0402c499333b)
