### ISSUE TITLE
Submitting a 1995-STEM form results in a 1995 form being saved

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#6096]
When a logged-in user submits a 1995-s form, a 1995 from is saved. This results in the user having a saved form which is a copy of an already submitted form. This bug is currently present in Staging.

1. Access https://staging.va.gov/education/apply-for-education-benefits/application/1995/introduction 
2. Log in and begin a new application
3. Fill in all required fields on the applicant information page and click continue
4. Select either of the Chapter 33 benefits and click continue
5. Select Yes for "Are you applying for the Edith Nourse Rogers STEM Scholarship?(*Required)" and Yes for "Are you enrolled in an undergraduate STEM degree program?(*Required)"
6. Complete the rest of the application and submit
7. After a successful submission, ensure you are still logged in and access https://staging.va.gov/education/apply-for-education-benefits/application/1995/introduction  again

The user will receive a message that their 1995 form is still in progress.

![Screen Shot 2020-02-21 at 3.39.04 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/e42070b1-79e1-4b65-a07e-8843ec96aa53)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/3945

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/3945

**Comment by delli-gatti-michael** [comment]
Local testing has been completed

**Comment by sonntag-adam** [comment]
In staging, testing passes QA
