### ISSUE TITLE
Content request from MHV on VA.gov Cartography Team

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#60960]
## About your team

- Team name: 
-	OCTO-DE product owner: Patrick Bateman
-	Product manager: Tom Anderson
-	Designer: 
-	FE engineer: 
- Accessibility specialist:
- Content writer: 
-	Product/team Slack channel:
 
### What does your team need support for? Check all that apply.
- [ ] Launching one or more unauthenticated pages, online forms, apps, or tools on VA.gov
- [x] Making revisions to one or more existing VA.gov pages
- [ ] Accessibility review of wireframes and/or prototypes
- [ ] Accessibility issue (general request)
- [ ] Accessibility PDF review request
- [ ] Accessibility user research support ([submit a separate, additional request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name))
- [ ] Something else 
 
### Give a brief description of what your team needs support with:

My team needs support with adding a user's health care priority group information to the MHV on VA.gov landing page (va.gov/my-health). Our hypothesis is that by putting this information in the user's path, the user will better understand their healthcare eligibility status and take actions to correct that status if it differs from what they believed it to be.

From a content perspective, we need support the actual verbiage to place on the page, as well as recommendation on how to connect the user with explanatory content (e.g., a resource page); or include explanatory content on the MHV on VA.gov landing page; or both.
 
 
### Will this new product be released incrementally (for instance 25% of users initially)? 
  - [ ] Yes
  - [x] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
### When do you expect to launch your product to 100% of users?
  
Mid-July
 
### Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [x] No
 
#### If yes, please check all of the phases in the Collaboration Cycle you have completed: 
- [ ] Design Intent
- [ ] Midpoint Review
- [ ] Staging
 
### When does this work need to be completed?
- Estimated launch date: Mid-July
- Estimated staging review date:
- Content, Accessibility, and IA work needed by: Before mid-July, but the implementation effort is pretty minimal, main outstanding task is content.
  
## Supporting artifacts

- Link to product outline:
- Link to or attach user flows:
- Link to prototype or mockups:
<img width="943" alt="image (9)" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/7645362/419abb41-1c04-4098-85ce-d353fb200856">
- Link to your research plan: 
- Link to any epics/issues that may be helpful:

#### Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed

 **Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.
 
### Accessibility Help in Slack
The [#accessibility-help channel](https://dsva.slack.com/archives/C8E985R32) in the DSVA Slack, is also available to you as a resource. Everyone is welcome to ask questions or get help from our a11y (accessibility) specialists. Tag `@Terry Nichols` to get a11y help asap.

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag `@Terry Nichols`.**

- If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
- If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)
 
 - If you are creating an [experimental design,](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) please [also contact the DST. ](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)
- If you are requesting [a11y support for user research,](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name) please complete this form, next.

**Comment by kristinoletmuskat** [comment]
Hello! I am doing some of the IA work while Mikki is out, and just synced with our content team on this request. We were wondering the following:

1. Have ya'll thought yet about what else we might want in this section? That would inform how we might want to format and label things. You might consider taking a look at all of the veteran attributes we're aware of (in [this spreadsheet](https://docs.google.com/spreadsheets/d/1BTIlmYyiCInqOiYjIMPCCR2dDf5nmSNLEOmWFMcmXuQ/edit#gid=0), you can request access), and thinking about what other things we might want to pull in. 

2. Here's an example I wanted to share of a health insurance portal that has a similar feature -- there's a section that lists high level information about the policies, and includes links to ID card and Coverage details. There's also a section at the bottom for 'recent activities', which I think Danielle mentioned ya'll were considering for the future (containing things like incomplete healthcare applications and notifications).

![My Policies section of health insurance website](https://github.com/department-of-veterans-affairs/va.gov-team/assets/122126772/e572ef8d-4eed-4ec2-8b61-1f511a1a36af)

![Coverage details of a policy](https://github.com/department-of-veterans-affairs/va.gov-team/assets/122126772/157622d8-fa4d-4ead-a187-041a5140fda6)

![ID card detail](https://github.com/department-of-veterans-affairs/va.gov-team/assets/122126772/b4bb90e3-53dc-4ae0-a3eb-91807d1b5110)

3. Have ya'll done any user research on personalization for this page? Another option we could consider is adding info like this to the My VA landing page, or to the profile (or all 3!) -- I wonder if we could learn more about user preferences for finding this type of info about themselves via user research!

**Comment by batemapf** [comment]
thanks @kristinoletmuskat! some initial thoughts:

> Have ya'll thought yet about what else we might want in this section? That would inform how we might want to format and label things. You might consider taking a look at all of the veteran attributes we're aware of (in [this spreadsheet](https://docs.google.com/spreadsheets/d/1BTIlmYyiCInqOiYjIMPCCR2dDf5nmSNLEOmWFMcmXuQ/edit#gid=0), you can request access), and thinking about what other things we might want to pull in.

For MVP, we're really just focused on the user's priority group assignment and some way for the user to learn more about what that assignment means (i.e., link to a resources page or accordion or some kind of UX magic). That said, I'd love to look at the spreadsheet, but Google Sheets is blocked on the VA network. I'll reach out on Slack for a copy.

I think post-MVP, we'd be absolutely interested in adding in other pieces of data that further elucidate the users specific benefits (i.e., dynamically calculate the user's Rx or outpatient copays). But we wanted to start small with the most foundational information, which is priority group.

> Here's an example I wanted to share of a health insurance portal that has a similar feature -- there's a section that lists high level information about the policies, and includes links to ID card and Coverage details. There's also a section at the bottom for 'recent activities', which I think Danielle mentioned ya'll were considering for the future (containing things like incomplete healthcare applications and notifications).

I love the examples. I could very much see the basic priority group information expanding to cover lots of these things post MVP, all in the spirit of increasing health benefit transparency for the Veteran to encourage either greater engagement with care or rectification of incorrect priority group assignment or means test result (which impacts things like beneficiary travel and copays).

> Have ya'll done any user research on personalization for this page? Another option we could consider is adding info like this to the My VA landing page, or to the profile (or all 3!) -- I wonder if we could learn more about user preferences for finding this type of info about themselves via user research!

Our very informal plan is to:

1. Place basic priority group information on the MHV on VA.gov landing page (va.gov/my-health) with some kind of explanatory content alongside.
2. Monitoring how real users engage with this data using GA and/or DD RUM.
3. Include priority group (both itself as a VA concept as well as where a Veteran would expect to find it / interact with it) in upcoming research done by the Cartography team, the Health Enrollment team, or both.

Long term, I think it does make sense for this information to live near / alongside the My VA "Your disability rating..." element and link to the [Rated Disabilities](https://staging.va.gov/disability/view-disability-rating/rating). But that is mostly a personal assumption that Veterans mentally link their disability ratings, compensation, and health benefits tightly together. I think the research in step #3 mentioned above will certainly help us validate.

**Comment by laurwill** [comment]
Hi @batemapf , 
We'll look forward to hearing what you learn in this research! For testing purposes, here's suggested content changes to the priority group content in your mockup:

**Your VA priority group:** [number]
[Learn about priority groups and how they may affect you](https://www.va.gov/health-care/eligibility/priority-groups/)
