### ISSUE TITLE
SOCKS issue

### ISSUE THREAD

**Issue by bdech** [department-of-veterans-affairs/va.gov-team#60975]
Tolase

I submitted a ticket (https://github.com/department-of-veterans-affairs/va.gov-team/issues/60887) for SOCKS access which has been granted and followed through the steps here (https://depo-platform-documentation.scrollhelp.site/getting-started/accessing-internal-tools-via-socks-proxy) to have it configured on my PC but I am still unable to access the websites that requires SOCKS proxy on my browser.

**Comment by bdech** [comment]
https://dsva.slack.com/archives/CBU0KDSB1/p1687816419243369

**Comment by bdech** [comment]
Had Tolase restart and run Ubuntu as an admin
Had Tolase run `vtk socks off` and then `vtk socks on`

This resolved Tolase issue

**Comment by rmtolmach** [comment]
Trying to get this in the "closed" column. Going to reopen and then close.
