### ISSUE TITLE
Grant new team member access to va.gov-team

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#6098]
Please grant the following github user access to va.gov-team repo as well as the https://github.com/orgs/department-of-veterans-affairs/teams/bah-526-developers team. Note that their GH username has been verified. Thank you!

GH username: JLynnJ
VA email: jennifer.jones11@va.gov

**Comment by bobrox1973** [comment]
@desireeturner, I have invited the user to the bah-526-developers-team. I also invited the user to the vet.gov-write team, so they have srite access to the va.gov-team repo. If the user does not need write access to the va.gov-team repo, let me know and I can update the invite.
