### ISSUE TITLE
[CHIP] [SPIKE] Research how to Add & Deploy Endpoints on AWS

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#60991]
## Tasks
- [ ] Document steps to create new endpoints with terraform

https://github.com/department-of-veterans-affairs/checkin-devops

https://github.com/department-of-veterans-affairs/checkin-devops/blob/master/terraform/applications/chip/prod/lambda/lambda.tfstate

**Comment by lee-delarm6** [comment]
Lambdas are added through the `chip` repo .yml files. Will talk to Jeremy tomorrow about what part the terraform repo `checkin-devops` plays in all this

We (Brian & I) successfully added an endpoint through the .yml files in testing this out

**Comment by lee-delarm6** [comment]
The`checkin-devops` repo is a project that has some (memcached setup) active items, but chip has not been activated or moved over from SAM (regular lambda) in the `chip` repo
