### ISSUE TITLE
[GitHub Action] Manage Cluster for each PR (cleanup)

### ISSUE THREAD

**Issue by hgbarreto** [department-of-veterans-affairs/va.gov-team#60997]
## Description
When a PR is closed or the label is removed, kick off the cleanup for the cluster

## Acceptance Criteria
- [ ] Clusters are cleaned up for respective PR when PR is closed 
- [ ] Clusters are cleaned up for respective PR when PR has `CICD` label removed

## Refinement Guidance - Check the following before working on this issue: 
- [x] _Team label assigned ("platform-tech-team-2")_
- [ ] _Epic assigned (if needed)_ 
- [ ] _Estimated (points assigned)_
- [ ] _Sprint assigned (once planned)_
- [ ] _Team member(s) assigned_

**Comment by npeterson54** [comment]
Removing from sprint.  Not as important as some other things we'd like to get done.  Nice to have

**Comment by ph-One** [comment]
Closing. This is an old ticket that does not apply right now. If this capability comes back up, a new ticket will be created. We do not deploy a cluster per PR.
