### ISSUE TITLE
Number callouts from CMS don't render on preview servers

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-team#6099]
## What happened?
"Number callout" CMS component appears empty in preview. 

## Steps to Reproduce

Visit http://preview-prod.vfs.va.gov/preview?nodeId=901 and go to the bottom of the page.

![Manage_A_Legacy_VA_Appeal___Veterans_Affairs](https://user-images.githubusercontent.com/643678/75074431-afa1d600-54c9-11ea-8605-c2ee371a464f.jpg)

## Desired behavior

It should look like the component on the prod site. https://www.va.gov/disability/file-an-appeal/ 
![File_A_VA_Disability_Appeal___Veterans_Affairs](https://user-images.githubusercontent.com/643678/75074480-cc3e0e00-54c9-11ea-9e74-9867d280eb3f.jpg)

## Acceptance Criteria
- [ ] Number Callouts can be previewed

**Comment by AkucherGCIO** [comment]
2020-26-02 Sprint Planning:
Need to find out if it's Preview Issue or Rendering/Publishing issue.

**Comment by ncksllvn** [comment]
I'm guessing that we rewrote the content on http://preview-prod.vfs.va.gov/preview?nodeId=901 to not use the number callout for the time-being?

![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/89a2b6b1-9036-4280-b58d-12d6117cac62)

**Comment by ncksllvn** [comment]
Interestingly, the number callout appears to work from the preview of the health care page -

http://preview-prod.vfs.va.gov/preview?nodeId=35

![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/1949ebda-afa2-4f54-bb52-a5941ed3beaa)

Can you share any more insight @kevwalsh?

**Comment by AkucherGCIO** [comment]
03/02/20 PW Standup
@ncksllvn needs help from @RLHecht who has Drupal access.

**Comment by AkucherGCIO** [comment]
03/05/20 PW standup
Randi will be troubleshooting the issue with this ticket.

**Comment by ncksllvn** [comment]
Recreated here (but maybe temporarily) - http://preview-staging.vfs.va.gov/preview?nodeId=901

**Comment by ncksllvn** [comment]
Very strange. For some reason, the response JSON from Drupal is missing the data required for drawing the Number Callout - 

![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/ad209f91-d3f9-4beb-a48d-49ab465dca54)

I'm wondering if this is an issue in the GraphQL queries of the preview server, but I don't see how it's different than that of the website build.

**Comment by AkucherGCIO** [comment]
@RLHecht @ncksllvn - Has this been validated and are we able to close this ticket ?

**Comment by ncksllvn** [comment]
No, I haven't done this yet. I looked into it, but was stumped. We'll need to carry this over into next sprint if we want to continue on it.

**Comment by AkucherGCIO** [comment]
@ncksllvn - Changed the Milestone to Sprint 17

**Comment by kevwalsh** [comment]
> Interestingly, the number callout appears to work from the preview of the health care page -
> 
> http://preview-prod.vfs.va.gov/preview?nodeId=35
> 
> ![image.png](https://camo.githubusercontent.com/b2e162a8d7ad6e5ed55dbb0b2185331ec832b64f/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3539636239646531623032323264356465343739353364382f31393439656264612d616661322d346635342d626235322d613539343165643362656161)
> 
> Can you share any more insight @kevwalsh?

Sorry i missed this last week. i really don't have an idea. it does seem to work in some places but not others.

**Comment by kevwalsh** [comment]
Variables maybe worth investigating: nesting, repetition...

**Comment by RLHecht** [comment]
I just built a decision reviews page in Drupal and the number callout is showing as a gray box. This one isn't stacked or near another component. It's node ID 3003 if you need another example. ![Screen Shot 2020-03-12 at 2.17.27 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/278e6ecb-a4eb-48d5-a1e8-3b35da7f324f)

**Comment by MickinSahni** [comment]
2020-03-16 PW Standup
* PR opened, but tbd if that will address

**Comment by ncksllvn** [comment]
Should be fixed today!

**Comment by ncksllvn** [comment]
This issue wasn't contained to just the preview server - it would have been an actual issue on the website, but we never tried publishing because we couldn't preview it in the first place.

Per @RLHecht, this is fixed!

https://dsva.slack.com/archives/C52CL1PKQ/p1584456871296300?thread_ts=1584454302.294500&cid=C52CL1PKQ

> Just built a Drupal page for decision reviews and the number callout is showing correctly in preview. Woo hoo!!
