### ISSUE TITLE
Open questions from CMS health hub content bug QA

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#61]
I flagged a few areas for clarification. Not urgent except maybe # 6.

1/ The number 1 vs one issue came up a few times. This might mean that we clarify or simplify our number guidance for future proofing content. Even I couldn't make heads/tail of whether it should really be "one" or "1"! Guidance topic - @RLHecht 

2/ "In Spanish" text link - should we make it in Spanish? -- En espanol. This was on just one page. @DanielleSoCompany  

3/ Substance use (vs abuse) - search value question - and if we're not getting info to veterans @DanielleSoCompany 

4/ Facility locator - found one place we link to the old tool. @DanielleSoCompany  

5/ Download links - guidance topic @RLHecht 

**6/ Mental health - weird phone # issue** @DanielleSoCompany 

7/ Not captured in doc but also noticed that sometimes we do phone #s like this: 800-nnn-VETS [(800-nnn-VETS)](hyperlink.com)   and other times like this: [800-nnn-VETS (nnnn)](hyperlinkwholething.com)

I prefer the latter as it saves some repetition and will firm that up in style guide unless you all have any objections.  (I don't think we should go back to 'fix' this - leave it; but with new content, just have the one documented way.)

[health-hub-open-issues-041619.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3096053/health-hub-open-issues-041619.docx)

**Comment by DanielleSoCompany** [comment]
Hi @jenniferlee-dsva. Please see my answers to questions for me in the attached. (note: Github was giving me trouble uploading the file, so I deleted some of the screenshots to make it smaller). Thanks!

[health-hub-open-issues-041619_dt.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3096281/health-hub-open-issues-041619_dt.docx)

**Comment by bethpotts** [comment]
@jenniferlee-dsva Let's look at this rule in our 1:1 so I can clarify. Here is a list of the correct way to style the examples you found of one/1:
You may qualify for: one-time dental care (bug)
You may qualify for: a one-time course of dental care (bug)
If you've received one of these discharge statuses (correct as is)
...if you meet at least one of the requirements listed below (correct as is)
...at least one of the descriptions below is true for you (correct as is)
...one of these...(correct as is)

**Comment by jenniferlee-dsva** [comment]
@DanielleSoCompany  - for ph# bug. So it should be:
Or call 800-273-TALK (800-273-8255)  -->?

NOT:
Or call 800-273-TALK (8255) (800-662-4357)

![image](https://user-images.githubusercontent.com/43381063/56434704-accfc680-62a3-11e9-98c7-a43fa54f36f4.png)

**Comment by DanielleSoCompany** [comment]
@jenniferlee-dsva Yes. Or, I see that above you noted wanting to move to 800-nnn-VETS (nnnn) across the board. So we could either do:

Or call 800-273-TALK (800-273-8255)
**Or** 
Or call 800-273-TALK (8255)

**Comment by jenniferlee-dsva** [comment]
^ Okay, let me know either way. There's no deployment today, so we have until Monday afternoon. I did see the second style on other pages and like it better than the repetitious version, but yeah, maybe there was a reason...

**Comment by vastphnwlkr** [comment]
I believe the words in phone numbers are a throwback to the days of rotary dial and touch-tone phones. They were more of a vanity plate than they were useful. I don't know anybody that likes them (limited feedback) and I personally find them annoying.

**Comment by jenniferlee-dsva** [comment]
@bethpotts RE https://github.com/department-of-veterans-affairs/va.gov-team/issues/61#issuecomment-484751833  - and our convo - those instances on dental care page have been updated to reflect correct usage (one-time; one of these).   All these will go live with Monday's afternoon deploy.

And @DanielleSoCompany - the locator tool link will now point to our new facility tool. (I thought it might have been pointing to the old one because that one includes Puerto Rico; but I checked our tool, and we also include P.R. in searches, too. So all fine.)

@DanielleSoCompany - the "In Spanish" link will now say "En español" on the MST page. 

Remaining items:
^ ph # and accessibility Q
From inside doc - download links of PDFs, etc. @bethpotts - l'll post this to you and Randi for firming up.

**Comment by DanielleSoCompany** [comment]
Hi @jenniferlee-dsva. Re: phone numbers, Trevor said he doesn't have a strong opinion on which is better, but that he believes having the full number in parentheses is clearer for assistive devices, and gives the listener a second opportunity to hear the first and middle numbers, which are often the hardest to remember.

Given this and @vastphnwlkr's feedback above, I would lean toward keeping the full number in parentheses like 800-273-TALK (800-273-8255)....or even moving toward just the number sans words at some point: 800-273-8255.

Thanks!

**Comment by jenniferlee-dsva** [comment]
@DanielleSoCompany - Looked at our phone # guidance and it just says, "For vanity phone numbers, provide the numerals in parentheses at the end: 877-222-VETS (8387)."  I'm seeing it done both ways on our site; but don't have a sense of which is the more common. I also like eliminating the vanity text and just going with numbers. Given Trevor's feedback, it sounds like it would be better to lead with number and then with the vanity text in parens if at all.

So, here are the 3 options per ^ comments: 

A.  
800-273-8255  --> hyperlink the whole thing; omit vanity text.

B.
800-273-TALK (800-273-8255)  --> repeat the full number, as numbers; hyperlink the # inside parentheses.

800-273-8255 (TALK)  --> hyperlink the whole thing; this way gives assistive devices the number first. 

Let's chat at Tuesday's weekly sync and we can bring this up also at Thursday's content style guide working group. (Whatever we decide, we can apply it to new content going forward; and update current pages only as we make other content changes. I don't see this item as something visible enough to warrant retroactive updating like sentence case and service member.)

Thx for your input @vastphnwlkr

**Comment by bethpotts** [comment]
@jenniferlee-dsva I vote for A. I've always wondered if the vanity number is really useful. Let me know if you agree, and I'll let Randi know. She's working on something this very minute that has a vanity number and was wondering what we'd decided...

**Comment by DanielleSoCompany** [comment]
@jenniferlee-dsva @bethpotts Agree on A being best option.

**Comment by jenniferlee-dsva** [comment]
We're all agreed. It cuts down on repetition, and letters are not useful accessiblity either, even if it's not a problem. 

Only open item here is the PDF (or other assets) that are linked as a downloadable. @RLHecht and @bethpotts - could yo uweigh in here? Sorry I haven't had a chance to Slack you offline. Basically, I see a few types of CTA text links on our pages - for PDFs and ones sending ppl to a video. I propose we label those links so it's clear - without having to add additional instruction or note text -- that what the person is about to click on is going to download or take them to a video. 

Like this: 

Download VA Form 10-10EZ (pdf)   <-- I'm impartial to casing, if you have  feelings one way or other

10 tips for adjusting to civilian life (video)   

^ if it goes to YouTube, it would be nice to say  "(YouTube)" but I think there's some sort of government best practice guidance around not appearing to promote or favor particular private companies. Obvs no one can adhere to this with social media things, but... ?

**Comment by vastphnwlkr** [comment]
@jenniferlee-dsva For the video don't you want an action work "Watch 10 tips for adjusting to civilian life"? Especially with the use of modern browsers and the built in pdf viewers, is stating "pdf" sufficient? Are the forms fillable and if so do they require a version of Adobe Acrobat versus just pdf.

**Comment by jenniferlee-dsva** [comment]
RE ^ [mental health page and weird ph#](https://github.com/department-of-veterans-affairs/va.gov-team/issues/61#issuecomment-484958230) - made the update and should go live with today's deploy. I used our updated option A. styling and omitted the vanity letters, but did not retroactively update other vanity letters on this page. (Should I???)  

Preview screenshot: 
![image](https://user-images.githubusercontent.com/43381063/56673658-aa47e500-6686-11e9-88c6-1608ce4836e8.png)

**Comment by bethpotts** [comment]
@jenniferlee-dsva Would recommend we give these two tasks to Randi, who could start making updates in the CMS this week:
1. remove all vanity phone numbers in the health care hub
2. add (PDF) following text links prompting the user to download a form 

I will have the temp copyeditor, Jen R., make these same 2 changes in github files going forward.

**Comment by jenniferlee-dsva** [comment]
@bethpotts  - I believe this issue has already been resolved. The task wasn't to update all the instances, but to address that one sepcific phone # bug. (And tangentially, to clarify the guidance in the style guide separately for new content going forward.)
