### ISSUE TITLE
Access for Brittany Clausen

### ISSUE THREAD

**Issue by brittanyclausen** [department-of-veterans-affairs/va.gov-team#610]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Assign the issue to your DSVA contact 

# Description
- Please provide your name.
   > Brittany Clausen
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > My HealtheVet, Web Developer, By Light

- Request Type
  > Access to internal tools or access to the AWS console. Internal Tools, Developer tools.

- ssh-rsa 
  >AAAAB3NzaC1yc2EAAAABIwAAAQEAxUNbPU+q+dySoELtB7Gk5UuC7bC+0BoyGZDIOwZyMV
KbGRn05QY1wOLwCBJ2Imez7tfMYK7sKlHocfSImo+nOMuPTyxeAbOHhChP/xexSGwSFeKM
vhxFblYwCJArpL23tdjFrmFlqRacPu45v3d7ZsWNSLUPI21P+97cdHthVuxoWrKvu9v1Yq
JqQCijz5xWBUYUH9NuX8HU09bwKriL548d5XTYnwVuRPpAtUpxjQWBhIYdjpvnC2t3zbf1
fJQlKUiHauEnOcNV3wZEXeHkPSqBECnlC3x0DGaIUGVIEzvRaTdbtKoQhvR04kC2gcbwDR
fZh03TnlzMfU0htfyWvw==brittany.clausen@va.gov

**Comment by smoonpeyes** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by b00klegger** [comment]
PR opened for sshkey
ref: https://github.com/department-of-veterans-affairs/devops/pull/5229

**Comment by b00klegger** [comment]
Job complete.
http://jenkins.vfs.va.gov/job/infrastructure/job/sshkeys/330/console
Closing issue, reopen and update if experiencing any issues.
