### ISSUE TITLE
Internal PDF Generation (Logging)

### ISSUE THREAD

**Issue by SamStuckey** [department-of-veterans-affairs/va.gov-team#61000]
# Overview
Investigate this action using the guidelines in the epic.  Document findings and improve logging as documented.

## Action
PDF generation of files locally on the filesystem.  This is NOT the sending off of these documents, but rather that semi-brittle logic around creating them on the vets-api server.  The following forms are generated locally as such:

**forms for normal auto-establish path:**
- 4142
 

**forms for backup path:**
- 4142
- 0781(a)
- 8940

## Up / Down stream system
None?  TBD, but seems internal.  

## How
[This file is the entry point for this logic](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/form526_submission.rb)

## User stories
- As a dev, i have understood and documented the existing logging around this action
- As a dev, I have improved logging around this action if required.

## Output
This work will require research into what, if any logging we have around this action.  
- Documentation around this features existing / new logging is added to the top level document for this purpose (linked in epic)
- PR adding / improving logging around this feature.

**Comment by sortizsh** [comment]
timebox to 8 more hours/EOD 7/25
