### ISSUE TITLE
[UX] Update the 45-minute Reminder Text to include Information about Checking in with Mobile App

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#61004]
## Scenario
The Mobile App team is not including a push notification as part of the MVP. We have been asked to update these text messages we send Veterans as part of check-in to ensure that they are aware that they can check-in using the Mobile App.
 - Text message reminder that will be sent 45-minutes before a Veteran's appointment
  
## Content
[https://github.com/department-of-veterans-affairs/va.gov-team/issues/59278](https://github.com/department-of-veterans-affairs/va.gov-team/issues/59278)

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/86678742/2715cecb-393a-4338-a519-0bcb278f6210)

## Tasks
- [ ] Collaborate with the VeText team to have the content for the existing VA Notify template updated

**Comment by benbrasso-agile6** [comment]
Think this work is completed: https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/59755
