### ISSUE TITLE
Analytics Feature Request

### ISSUE THREAD

**Issue by GcioNapoleon** [department-of-veterans-affairs/va.gov-team#61017]
# Analytics Feature Request/Bug Report

## What this form is for

Use this template to request an Analytics dashboard feature or report a dashboarding or Google Analytics/Google Tag Manager bug. This form is for enhancements to the existing KPI dashboards. If you have any analytics questions, please use the `/support` command on [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel in Slack, or attend one of our [office hours](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guidelines.1586823275.html#Analyticscustomersupportguidelines-5.AdditionalAnalyticsSupport).

Platform Analytics & Insights will use the information you provide to help improve our products and services.

## Instructions

Please fill out the following sections:

- [ ] Ticket Description
- [ ] Request/Report Description
- [ ] Additional Comments

## Ticket Description

Who is this request for? VA EDU benefits

- What is your role, and which team/project is this work for? Team (GOVCIO EDU Benefits contractor )  Link to the Team ( [govcio-vfep](https://github.com/orgs/department-of-veterans-affairs/teams/govcio-vfep)
- Feature Request: VA Management is looking for a way visualize the most searched cities in an analytics chart. We are currently able to see the search by name
-  
![Screenshot 2023-06-27 at 3 13 32 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/95312667/759cd3d6-8a7d-4b04-a821-a5a4c8510e97)

![Screenshot 2023-06-27 at 3 20 17 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/95312667/1bfe2601-b0d3-4c9b-ac7e-5922bf1a56f4)

- (optional for feature requests)
- This is a current screenshot of the search by location screenshot

![Screenshot 2023-06-27 at 2 39 50 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/95312667/00e043cf-8456-496b-90e3-44313b28b192)

-   

  _this adds research context for any data or features being requested_

  - [Insert role, team and project]

- Is this a feature request or a bug?

  - [x] Feature request
  - [ ] Bug report

## Request/Report Description

Please describe the feature you are requesting or bug you are reporting. Please be as detailed as possible. 

For a new feature request:

- Description of desired feature
- Why the feature is needed

- (Data) What timeframes are you looking to analyze (e.g. before vs. after dd/mm/yy)?

For a new bug:

- Steps to reproduce the issue
- Test user (if applicable)
- Expected result
- Observed result

**Product questions to think through if you're requesting new data features:**

- Who is your audience?
- Why do you need this data?
- What are you hoping to find?
- What is your hypothesis that you're hoping the data will support?
- What area of the VA are you hoping to assess?
- How frequently do you need this data?

## Additional Comments

_Add any comments or questions for the Platform Analytics & Insights team here (if applicable)._

> Please leave the following blank

## Acceptance Criteria

- [ ] Relabel the issue where appropriate
- [ ] Follow up with the requester where necessary

For features:

- [ ] Groomed & backlogged with notes

For bugs:

- [ ] Document issue & fixes
- [ ] Report findings with team & requester

## Definition of Done

- [ ] All AC completed

**Comment by michelle-dooley** [comment]
I will review with the team and get back to you.

**Comment by GcioNapoleon** [comment]
Thank you. I appreciate your assistance.

**Comment by michelle-dooley** [comment]
@GcioNapoleon - the GA 'Search Term' is not collecting the location same as it is name, however there are 2 custom events 'nameSearch' and 'locationSearch' that can give you this.  See reports below....

[nameSearch GA report](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p184334251/_u.date00=20230601&_u.date01=20230630&explorer-table.plotKeys=%5B%5D&explorer-table.filter=nameSearch&explorer-table.rowStart=0&explorer-table.rowCount=5000&_r.drilldown=analytics.eventCategory:Interactions,analytics.eventLabel:gibct-form-change/)

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/93597659/2842bc5f-8530-4b17-ada1-4f7b95d9f1e1)

[locationSearch GA report](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p184334251/_u.date00=20230601&_u.date01=20230630&explorer-table.plotKeys=%5B%5D&explorer-table.filter=locationSearch&explorer-table.rowStart=0&explorer-table.rowCount=1000&_r.drilldown=analytics.eventCategory:Interactions,analytics.eventLabel:gibct-form-change/)

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/93597659/96f7a4cd-e1ff-438e-97e5-aa9a6ce4f07f)

Hope this helps, let me know if you have any questions...

**Comment by GcioNapoleon** [comment]
Thank you. I'll share this information with the VA when they get back Monday.
