### ISSUE TITLE
Update the breadcrumb on the confirmation details page (MHV on VA.gov) 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#61015]
## Description
The Appointments application will be under the MHV on VA.gov portal. We will need to update the breadcrumb structure. #61015 will focus on the confirmation details page. 

---

## Acceptance Criteria
Background: the `va_online_scheduling_breadcrumb_url_update` toggle is on

- [x] Given the user is on `Upcoming VA appointments` landing page, 
        And the user clicks on `Start Scheduling` button and books an appointment
        Then confirmation page breadcrumbs will be updated to `< Back to [h1 header]`

- [x] Given the user is on `Upcoming VA appointments` landing page, 
        And the user clicks on `Start Scheduling` button and submits a pending VA appointment
        Then confirmation page breadcrumbs will be updated to `< Back to h1 header]`

- [x] Given the user is on `Upcoming VA appointments` landing page, 
        And the user clicks on `Start Scheduling` button and submits a pending Community Care appointment
        Then confirmation page breadcrumbs will be updated to `< Back to h1 header]`

### Reference
[Spike ticket #54757](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/54757)

### Design Assets
[Title tag format guidance](https://design.va.gov/content-style-guide/seo#title-tags)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by ldelacosta** [comment]
We will use descriptive back link for the initiative.

**Comment by ldelacosta** [comment]
Validated the confirmed VA booked appointment and pending CC request. There is an issue with displaying the type of care for VA pending appointments. Will validate once the issue has been resolved in staging. 

**Confirmed VA booked appointment:** 
![Screenshot 2023-07-31 at 5.48.20 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/3b8b5c90-b18d-4e3a-8bef-015f811e54db)

**Submitted a CC pending request:** ![Screenshot 2023-07-31 at 5.51.42 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/460296b1-99e1-4b5a-9c2d-5ba6ed8420ed)

**Comment by ldelacosta** [comment]
Looking back, I see why we added the 'Requests.' It should be Back to h1 header for the descriptive back link. Let me know if you we need to re-work this ticket @jenniemc. Production version that was released today have the correct description. Let me know if we need to discuss.

**Comment by ldelacosta** [comment]
Validated the changes in staging for Judy Morrison. Notified the designers to validate the ticket. 

Pending VA appointment confirmation details page: 
![Screenshot 2023-08-08 at 2.59.02 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/4279e6d1-93df-4fff-ae65-3b5dc62eef4a)

Pending CC appointment confirmation details page: ![Screenshot 2023-08-08 at 3.03.58 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/84ae8909-084e-4ac0-be5b-2efbe0f82216)

**Comment by melissa-lefevre** [comment]
This looks good but I noticed that there is not a "type of care" line for tester royal.tester@id.![Screenshot 2023-08-09 at 11.18.31 AM.png](https://images.zenhubusercontent.com/603fe0d8f45baf5a1d422aaf/00135c6f-9d5a-441a-8213-47c8fdd24818)me

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket.
