### ISSUE TITLE
[FE] 10-10EZ - Household: Update content based on final QA findings

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#61038]
## Background
A final QA run-through was completed and there were some minor content updates that are needed.  Once these are done, we are good to go for Staging review and E2E testing with Enrollment System team.

<details>
<Summary>QA Finding #1 (click to expand)</Summary>

@longmd  The only thing I saw missing from this ticket that is not showing in Staging is one line on the Deductibles page.  
The [comment ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/57959#issuecomment-1563186511) above on 5/25 states to add a line to the College or vocational education expense accordion.

- **Currently in Staging**
- ![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/92328831/066f074f-9f68-4d9f-80f6-2ba68bafedf6)

- **In the comment and Sketch**

> [add info content]
> College and vocational expenses include payments for these expenses related to your own education:
> 
> Tuition
> Books
> Fees
> Course materials
> Only include expenses for your own education (not your dependents' education).
> [end additional info component]

- ![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/92328831/f35bf39f-ef8f-4cfe-9a07-d811338128ca)

</DETAILS>

<details>
<Summary>QA Finding #2 (click to expand)</Summary>

Went through this in staging and a couple of things:

Content did have the suggestion to relabel to "household financial information" is that a huge structural change or a minor content change?

Edits needed:
- Label on fields on spouse address/contact info page. The Sketch file/Design System use State/Province/Region. Should it be that way consistently across the form? Or is there a reason to only use State?
- Same page, update label of "phone" to "Phone number" on spouse contact page

- Dependent's additional info dropdown some text was cut off (in bold). But did not see again on the review dependents page.. "They're living with a permanent disability that happened **before they turned 18**"

- Headline missing on multiple dependents add/review page.  "Review your dependents"

Non-content items to note:
- On the modal, for cancel adding, there was some odd spacing. The buttons were an odd width and there was no spacing between.
- 
<img width="483" alt="Screenshot 2023-06-27 at 2 10 21 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/98367393/5aaba835-3c28-4d10-8fb0-39b000e8450a">

- On the review page, there was an odd bullet showing:

<img width="632" alt="Screenshot 2023-06-27 at 2 33 48 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/98367393/7ffbd680-d45c-429f-8775-b772a43edfbd">

</DETAILS>

## Tasks
- [x] Complete content updates from QA feedback
- [ ] Validate changes with team members (PM and Design)

## Acceptance Criteria
- QA Findings are addressed and the form is updated

**Comment by longmd** [comment]
@jessicastump / @hdjustice , these have been completed and are ready for sign-off.

**Comment by hdjustice** [comment]
Can confirm all changes were completed and validated.
Question @longmd - The modal spacing looks good, were we able to adjust that?

**Comment by longmd** [comment]
@hdjustice , nope! There were no changes that were specific to anything related with the modal. Maybe some magic happened or maybe there was a change that went out from the DST that then got corrected? Thats super sweet if there are no issues with it, though!!
