### ISSUE TITLE
Add Healthcare Priority Group to Landing Page - Implementation

### ISSUE THREAD

**Issue by A6-toma** [department-of-veterans-affairs/va.gov-team#61049]
As a user, I want to see my healthcare priority group on the homepage so I can take action to correct it if necessary.

As a Veteran, I want to see my Priority Group assignment at https://www.va.gov/health-care/eligibility/priority-groups/, so that I can know how this assignment impacts my care.

We need to implement adding the healthcare priority group for a signed-in user  per the approved UX design (#61045). This includes: 
- Adding the approved content
- Analytics/tracking of when a user interacts with the "Learn more about priority groups" link
- Moving the "Learn more about MyHealtheVet on VA.gov" link to top of the **More resources and support** section at the bottom of the landing page.

[Sketch design file](https://www.sketch.com/s/f9050748-823b-4245-98c9-e9738c15a271/p/8CD4EBCA-BAB8-4671-B1CD-396B77B240E9/canvas) - look at VA-MHV-PG v1

### Acceptance Criteria
1. The correct healthcare priority group appears on the landing page, priority-groups URL for a signed-in user.
2. Tracking of when a user interacts with the "Learn more about priority groups" link is captured.
3. "Learn more about MyHeatheVet on VA.gov" link has been moved to the top of the **More resources and support** section at the bottom of the page.

**Comment by radavis** [comment]
In order to display dynamic user data on the [VA Priority Groups](https://www.va.gov/health-care/eligibility/priority-groups/) static page, I will take the approach of creating a [new React widget](https://depo-platform-documentation.scrollhelp.site/developer-docs/creating-a-new-react-widget) in `vets-website`.

**Comment by radavis** [comment]
When we're ready to pursue design recommendation #1, we will need to submit an intake request with the Sitewide Content Team: https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=RLHecht%2C+coforma-terry&labels=sitewide+CAIA%2C+sitewide+content-product+support%2C+Sitewide+IA%2C+sitewide+content&template=sitewide-content-intake-form.md&title=%3CType+of+Request%3E+from+%3CTeam%3E

**Comment by radavis** [comment]
Current open PR implements design recommendation # 2.

Issued a support request on how to appropriately create accounts and mock data for accessing `/my-health`: https://github.com/department-of-veterans-affairs/va.gov-team/issues/62972

**Comment by fmccaf1** [comment]
[Link to Sketch file](https://www.sketch.com/s/f9050748-823b-4245-98c9-e9738c15a271/p/8CD4EBCA-BAB8-4671-B1CD-396B77B240E9/canvas)

The Design is the first in top left on page titled MHV V1.2 Priority Group. Here are jpgs for desktop and mobile: 
![Priority group w learn more link](https://github.com/department-of-veterans-affairs/va.gov-team/assets/106624475/53a3aa41-e061-4d48-8c50-83823cab4e44)
![Priority group w learn more link mobile](https://github.com/department-of-veterans-affairs/va.gov-team/assets/106624475/e476b2ad-9999-44d0-9581-83bc87475d17)

### Recommendation for ARIA text for priority group text and link: "Your health care priority group is ____. Learn more."

**Comment by radavis** [comment]
Updated my PR to include these changes: https://github.com/department-of-veterans-affairs/vets-website/pull/25343

**Comment by carafrissell1** [comment]
What is the Priority Group" "When a Veteran applies for VA health care, they get assigned to a group that determines how soon the VA signs them up for health care benefits and how much they will have to pay towards the cost of care. A Veterans' priority group can change if their income changes or if their service-connected disability gets worse and they receive a higher disability rating."

**Comment by wesrowe** [comment]
No op
