### ISSUE TITLE
Add Healthcare Priority Group to Landing Page - API Testing

### ISSUE THREAD

**Issue by A6-toma** [department-of-veterans-affairs/va.gov-team#61047]
As a user, I want to see my healthcare priority group on the homepage so I can take action to correct it if necessary.

We need to test pulling the healthcare priority group data for a user from the VA Profile system. API documentation says the data is there, but we need to confirm.

### Acceptance Criteria
VA Profile API has been tested to see if it returns a user's healthcare priority group and test results have been documented.

**Comment by radavis** [comment]
Priority Group is not currently surfaced by `vets-api`. Found a reference to priority group in the response from the Health Care Application Enrollment Eligibility service backend. It will take a little work to surface this info.

- [`spec/requests/health_care_applications_request_spec.rb`](https://github.com/department-of-veterans-affairs/vets-api/blob/d97426ca77e046bac9ea119ae754f14ae668babc/spec/requests/health_care_applications_request_spec.rb#L154)
- [`spec/lib/hca/enrollment_eligibility/service_spec.rb`](https://github.com/department-of-veterans-affairs/vets-api/blob/d97426ca77e046bac9ea119ae754f14ae668babc/spec/lib/hca/enrollment_eligibility/service_spec.rb#L30)
- [`spec/support/vcr_cassettes/hca/ee/lookup_user.yml`](https://github.com/department-of-veterans-affairs/vets-api/blob/master/spec/support/vcr_cassettes/hca/ee/lookup_user.yml#L69C270-L70C26)

**Comment by radavis** [comment]
We should be able to expose this information through the `/v0/health_care_applications/enrollment_status` API path.

**Comment by radavis** [comment]
Thanks to @lihanli for verifying that the HCA EE backend response has not changed.

https://dsva.slack.com/archives/CMJ2V70UV/p1688660091494659
