### ISSUE TITLE
Add Healthcare Priority Group to Landing Page - UX Design

### ISSUE THREAD

**Issue by A6-toma** [department-of-veterans-affairs/va.gov-team#61045]
As a user, I want to see my healthcare priority group on the homepage so I can take action to correct it if necessary.

### Tasks
- [x] Review this mockup and alter as needed:
        ![image.png](https://images.zenhubusercontent.com/645a5469a9467420f3cde02e/2aea33f8-55dd-42f0-bab7-16667c219814)
- [x] Finalize content and any links/explanatory detail needed for MVP

### Acceptance Criteria
1. Mockup has been updated
2. Content has been finalized and approved
3. Link target has been defined
4. Explanatory detail has been determined

**Comment by fmccaf1** [comment]
Tom could you please provide the url that this text will link to?

**Comment by fmccaf1** [comment]
I'm also curious to know if there is a user question that is answered by offering a link. For example, are users asking, "What is my priority group?" Or something else?

**Comment by fmccaf1** [comment]
I realized while looking at staging today that the design that Ryan created (in the content of the ticket) is not including a link that is on staging and prod, shown in this screenshot:

![image.png](https://images.zenhubusercontent.com/629a1db0e70457da479e69ae/6034bf05-0ef5-44c7-b558-7ac556287b7b)

I asked Patrick [in this slack thread](https://dsva.slack.com/archives/C0581MN69TJ/p1688747071153229) if we might be able to move this link. If not, we'll likely need to go a different route with priority group placement

**Comment by fmccaf1** [comment]
[Here's the sketch file with recommended design changes](https://sketch.com/s/f9050748-823b-4245-98c9-e9738c15a271)

And here's a list of the changes recommended:

 1. Add priority group info and link to learn more at top  ![image.png](https://images.zenhubusercontent.com/629a1db0e70457da479e69ae/e151fa08-5f9d-41d7-b573-7f8c92354141)



 2. Move link to learn more about MHV on VA.gov to footer ![image.png](https://images.zenhubusercontent.com/629a1db0e70457da479e69ae/8f8c8149-68d2-4404-887f-1cb728218a22)



 3. I also noticed in staging that there are no breadcrumbs. Not sure if that was an intentional design or not. If not: ![image.png](https://images.zenhubusercontent.com/629a1db0e70457da479e69ae/0c1265ab-2c07-4a0f-bc58-b83e5a781ffd)

**Comment by fmccaf1** [comment]
## Recommendation 1: Will take longer and require collaboration with another team, but is better in terms of UX, visual design, and following the site's existing information architecture

I [found this mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1687381992402/ac027de3375351079c9cbc93d1662510ffd3cb1a?sender=ua13e567cb5c4221acaa14949) from which I took the following screenshot:

![image.png](https://images.zenhubusercontent.com/629a1db0e70457da479e69ae/b29911a0-d77f-4e0a-8cd6-4fa6248bc804)

If assigned priority group is added here (in the alert on the Apply for VA health care page), it also makes sense to add one’s priority group to an alert in the priority group page for the following reasons:
1. It follows the existing pattern on VA.gov of personal/specific to user information lives on relevant content pages (just like this example above shows). 
2. It allows users - both those who access My Health and those who don’t - to search for priority groups as a way to find their own priority group on VA.gov
3. It’s a simple solution that doesn’t require us to come up with something new that is outside of the norm both in terms of design and information architecture.

Here's a screenshot [of the existing VA priority groups page](https://www.va.gov/health-care/eligibility/priority-groups/):

![image.png](https://images.zenhubusercontent.com/629a1db0e70457da479e69ae/285cb3dc-a45e-4f80-b401-6019dd52bc98)

This recommendation includes changes to the VA priority groups page as follows:

1. Change alert style on the VA priority groups page to green with checkmark
2. Remove PACT Act text and link (I checked and the link leads to a page that doesn’t mention priority groups, probably not great UX to have it here
3. Change text to something like: “Your assigned priority group is X (updated on date). If your income has changed or your service-connected disability has gotten worse, you may qualify for a different priority group. Use form 10-10EZR to update your information (linked).”

If we follow this recommendation, the landing page can remain clean and focused, and the links we want to add can be added neatly with other links towards the bottom of the page.

Here is an image of the redesigned landing page (desktop) if we take this route: 
[https://app.zenhub.com/files/133843125/71d06cdd-7802-44e0-9373-f303ec80311f/download](https://app.zenhub.com/files/133843125/71d06cdd-7802-44e0-9373-f303ec80311f/download)

**Comment by fmccaf1** [comment]
If we determine that Recommendation #2 is going to take long enough that we want an intermediary step, then we can implement this design to add priority group info to the landing page (to be updated later)

**Comment by fmccaf1** [comment]
As part of implementation, I got a few questions from Richard via Slack. I wanted to bring those messages here so we have them for the sake of record and open conversation.

**Question**: What should be shown to the user if they are not currently logged in? The PACT Act information? A message such as "Sign in to see your Priority Group"? Something else?

**Answer:** [This is the correct component.](https://design.va.gov/storybook/?path=/docs/components-va-alert--sign-in-or-tool-prompt)
Header: You might already have an assigned priority group
Text: If you've already applied for VA health care, you may have been assigned a priority group. Once you are signed in, your priority group assignment will be viewable here.
Button: Sign in to view your priority group

**Question**: I thought of a couple of other user states we should consider: User is signed in, but they haven't finished form 10-10EZ. User is signed in, but the api request for their priority group fails.

**Answer**: 
For user who has not completed 10-10EZ / hasn't applied for healthcare:
- use the default alert type (blue vertical bar)
- header: You have not (yet) been assigned to a priority group
- p text: When you apply for VA health care, we'll assign you to 1 of 8 priority groups. If you have already applied for VA health care, you will see your priority group here once it is assigned.If you have not applied for VA health care, you can learn more about the application process here. (link to https://staging.va.gov/health-care/how-to-apply/)

For user that experiences an api request fail:
- use the warning alert type (yellow vertical bar)
- header: We can't access your priority group information
- p text: Something went wrong on our end. Please refresh or try again later.

**Comment by radavis** [comment]
We will need to coordinate with the Sitewide Content Team in order to get Recommendation 1 approved. [link to slack thread](https://dsva.slack.com/archives/C52CL1PKQ/p1689869649975389)
