### ISSUE TITLE
Finalize removing old BRD documentation

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#61061]
PROBLEM STATEMENT:
There is old BRD documentation that still exists on platform website.

Actions:
- [x] Documentation is complete, it just needs to be deployed
- [ ] Comm with content team to ensure BRD documentation os archived
- [ ] Comm with content team to ensure EKS documentation has been published to website

**Comment by RachalCassity** [comment]
@laineymajor I added a POST MIGRATION sheet [here](https://docs.google.com/spreadsheets/d/1rTacvOYTXh3jMehzlfd0gGMlhiQOqu_Re-kKrGUVY80/edit#gid=1169320644). Two documents need to be removed and one document needs to be updated.

**Comment by laineymajor** [comment]
2 files that need to be removed
1 file needs to be updated

https://docs.google.com/spreadsheets/d/1rTacvOYTXh3jMehzlfd0gGMlhiQOqu_Re-kKrGUVY80/edit#gid=1169320644

**Comment by laineymajor** [comment]
Closing as this information has been sent to the content team for completion.
