### ISSUE TITLE
Update the URL and title page on the appointments details page (MHV on VA.gov) - Pending Appointments

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#61083]
## Description
The Appointments application will be under the MHV on VA.gov portal. We will need to update the title page and URL structure. #61083 will focus on the appointment details page for pending appointments. 

---

## Acceptance Criteria
Background: the `va_online_scheduling_breadcrumb_url_update` toggle is on

- [ ] Given the user is on the MHV on VA.gov portal
        When the user clicks on `Upcoming VA appointments`, user will land on the Appointments landing page
        User will click on the `Pending` link, then clicks on `Details` for a pending appointment
        Then the URL will be updated to: https://va.gov/my-health/appointments/pending/[ID]
        And the page title will be [`[Page Header] | Veterans Affairs`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/appointment-details.md#va-request---pending)

- [ ] Given the user is on the MHV on VA.gov portal
        When the user clicks on `Upcoming VA appointments`, user will land on the Appointments landing page
        User will click on the `Pending` link, then clicks on `Details` for a canceled pending appointment 
        Then the URL will be updated to: https://va.gov/my-health/appointments/pending/[ID]
        And the page title will be [`[Page Header] | Veterans Affairs`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/appointment-details.md#va-request---canceled)

### Reference
[Spike ticket #54757](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/54757)

### Design Assets
[Title tag format guidance](https://design.va.gov/content-style-guide/seo#title-tags)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by ldelacosta** [comment]
@young1205 - please have the UX team validate this ticket when it's ready cc: @JRRoof @outerpress

**Comment by Cieramaddox** [comment]
Ticket has been validated by UX team.
