### ISSUE TITLE
Update the URL and title page on the confirmation details page (MHV on VA.gov) - Pending appointments

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#61085]
## Description
The Appointments application will be under the MHV on VA.gov portal. We will need to update the title page and URL structure. #61085 will focus on the appointment confirmation page for pending appointments. 

---

## Acceptance Criteria
Background: the `va_online_scheduling_breadcrumb_url_update` toggle is on

- [x] Given the user is on `Upcoming VA appointments` landing page, 
        And the user clicks on `Start Scheduling` button and submits a pending VA appointment
        Then the URL will be updated to: https://va.gov/my-health/appointments/requests/[ID]?confirmMsg=true
        And the page title will be [`[Page Header] | Veterans Affairs`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/appointment-details.md#va-request---confirmed)

- [x] Given the user is on `Upcoming VA appointments` landing page, 
        And the user clicks on `Start Scheduling` button and submits a pending Community Care appointment
        Then the URL will be updated to: https://va.gov/my-health/appointments/requests/[ID]?confirmMsg=true
        And the page title will be [`[Page Header] | Veterans Affairs`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/appointment-details.md#community-care-requests)

### Reference
[Spike ticket #54757](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/54757)

### Design Assets
[Title tag format guidance](https://design.va.gov/content-style-guide/seo#title-tags)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by ldelacosta** [comment]
Validated the changes in staging for judy.morrison@id.me. Notified the UX team to review the latest updates. 

Pending VA appointment confirmation details: 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbzhJIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7127ac785cbff72134d6b93e358de4bbed9b87a1/Screenshot%202023-08-15%20at%207.23.00%20PM.png)

Pending Community Care confirmation details: 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcEFJIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ef65f067d989fb7c49e685b1a3f5bdf606d78434/Screenshot%202023-08-15%20at%207.18.58%20PM.png)

**Comment by melissa-lefevre** [comment]
- [ ] When I submitted a pending VA appointment this is the url  https://staging.va.gov/my-health/appointments/requests/181134?confirmMsg=true
- [ ] When I submitted a pending community care appointment this is the url https://staging.va.gov/my-health/appointments/requests/181009?confirmMsg=true

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket.
