### ISSUE TITLE
Descriptive Back Link on the Confrimation Details page

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#61086]
## Description
We are improving the confirmation details page by adding a descriptive back link allowing the Veteran to return to the previous page.

Current state booked confirmation page (mobile): 
![staging va gov_health-care_schedule-view-va-appointments_appointments_va_177262_confirmMsg=true(iPhone XR)](https://github.com/department-of-veterans-affairs/va.gov-team/assets/90797205/3ac2783c-ed1c-4182-b963-ebc76fc1409a)

---

## Acceptance Criteria
Background: the `va_online_scheduling_descriptive_back_link` toggle is on

- [ ] Given when the user is on the Upcoming Appointment List 
       When the user clicks on the `Start scheduling` and books an appointment 
       Then the descriptive back link will be on the confirmation page
       And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/appointment-details.md#va-in-person) 
       And page design matches the [design spec](https://www.figma.com/file/g7bNlDUjuLY8TC9FVacium/Descriptive-back?type=design&node-id=13%3A33&mode=design&t=t0SysRjWuyBQNbiL-1)

- [ ] Given when the user is on the Upcoming Appointment List  
       When the user clicks on the `Start scheduling` and submits a request for an appointment 
       Then the descriptive back link will be on the confirmation page for pending appointments
       And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/appointment-details.md#va-in-person)
       And page design matches the[ design spec](https://www.figma.com/file/g7bNlDUjuLY8TC9FVacium/Descriptive-back?type=design&node-id=13%3A33&mode=design&t=t0SysRjWuyBQNbiL-1)

### Design Assets
Link to [figma design file](https://www.figma.com/file/g7bNlDUjuLY8TC9FVacium/Descriptive-back?type=design&node-id=13%3A33&mode=design&t=t0SysRjWuyBQNbiL-1)

### Sample Design Spec for Mobile 
![Details Mobile](https://github.com/department-of-veterans-affairs/va.gov-team/assets/79866060/367ae876-e200-4727-9618-82c971ff5814)

### Sample Design Spec for Tablet
![Details tablet](https://github.com/department-of-veterans-affairs/va.gov-team/assets/79866060/5fcfd13e-2a0f-4d44-8a19-a43eb5e76772)

### Sample Design Spec for Desktop
![Details](https://github.com/department-of-veterans-affairs/va.gov-team/assets/79866060/0124851d-9f3c-482b-9466-897d183381e9)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by simiadebowale** [comment]
@ldelacosta - this is ready for validation

**Comment by ldelacosta** [comment]
High level validation completed in staging. Design team will double check. cc: @Cieramaddox @melissa-lefevre 
![Screenshot 2023-07-12 at 1.35.08 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/ecf34e37-f483-4867-9771-8ae86e1950ce)

**Comment by ldelacosta** [comment]
@outerpress @Cieramaddox @melissa-lefevre - if you want to quickly validate this ticket and make sure it looks good before I close it. Thanks.

**Comment by melissa-lefevre** [comment]
Looks good, you can close it @ldelacosta
