### ISSUE TITLE
[Design] 10-10EZ - Improvements: Figma Updates for 1010EZ Authenticated Flow (design maintenance)

### ISSUE THREAD

**Issue by davidakennedy** [department-of-veterans-affairs/va.gov-team#61089]
## Task Description

We don't have a good source of truth in Figma for the authenticated flow in the 1010EZ form. It exist in bits and pieces here and there, but could be brought together along with our other main flow. This would help with future work in this area, if it comes up. We could also add some of it to the flow board in Mural.

## Notes and References
- Some screens and alerts exist in [Introduction pages variations- 47707](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6).
- Another page showing the alert for authenticated / prefill "short form" alert is in [Short form - Epic 27679](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6).
- This work grew out of #57951.

## Acceptance Criteria
Design team members can view new Figma files, both desktop and mobile, clearly showing the entire authenticated flow.

## Deliverables
- Figma files in the main sections of the 1010EZ, showing any screens and/or alerts related to the authenticated flow.

**Comment by hdjustice** [comment]
@jessicastump @aagosto90 @katelyncai @IMHieuVo - I think we might be ok to close this item.  With moving to Figma and constant updates over the 6 months, this has probably been done but I want to confirm with yall.

**Comment by jessicastump** [comment]
Probably repurpose from Sketch to Figma... This ticket was to create screens of the Auth experience that **did not** exist in Sketch at all. So not really part of the migration.
However, as part of the EZ intro page work, all the variations of the alerts and FAQs (ES Statuses) are being added to Figma under [Intro Page: Issue #69447](https://www.figma.com/file/UljiHam46o5DItC5iDgmPd/10-10EZ?type=design&node-id=82-35870&mode=design&t=FqwXHa7BIFCN8DK8-0)

**Comment by hdjustice** [comment]
Ok, I will revise this ticket then.  Thank you!

**Comment by jessicastump** [comment]
Placing links to the [Figma designs](https://www.figma.com/file/UljiHam46o5DItC5iDgmPd/10-10EZ?type=design&node-id=0-5961&mode=design&t=EJEiwUHZAh4rD1EK-0) of all the variations of the introduction page documented at this time.

**Comment by hdjustice** [comment]
@jessicastump do you want to put points on this?

**Comment by jessicastump** [comment]
@hdjustice and @longmd - the (sort-of) overlap ticket with the one around the prefill alert reduction #[72871](https://github.com/department-of-veterans-affairs/va.gov-team/issues/72871). I have been logging in with test users 3 and 7, and using test user 228 to confirm short form, so I can confirm the authenticated elements like the alerts when creating these in [Figma](https://www.figma.com/file/UljiHam46o5DItC5iDgmPd/10-10EZ?type=design&node-id=0-6399&mode=design&t=D1Oa8UPOpGw8ejsI-0). We can use the Figma file to comment and note which ones should be removed for prefill only. I will also add the video of prefill alert disappearing when I tried to continue a saved app.

**Comment by jessicastump** [comment]
Closing this ticket as it's purpose is complete - there is now a complete picture of the authenticated variations and the short form screens in the source of truth files.
