### ISSUE TITLE
Access for Michael for AWS Console

### ISSUE THREAD

**Issue by talbotmj** [department-of-veterans-affairs/va.gov-team#611]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Sean Good
- Please provide your name.
   > Michael Talbot
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > MyHealtheVet, Software Engineer, BYLIGHT
- AWS Console Request

- [Grant AWS Console access?]
  > YES
  > Our infrastructure is hosted in and makes use of services in AWS GovCloud. This account is shared amongst many different
  > teams; changes made to resources in this account will affect many services. You will need access to AWS for troubleshooting, 
  > log file review and to apply changes to the running instances and services.

**Comment by smoonpeyes** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by b00klegger** [comment]
@Jeff-Hayter 
Here is our first candidate check! Please let me know if any more information is needed from the requestor.
W

**Comment by Jeff-Hayter** [comment]
@b00klegger - Confirmed. Please grant access.

**Comment by b00klegger** [comment]
Account added via console, imported into Terraform state and DM sent to user. Please reopen and update the ticket if any problems are encountered.
