### ISSUE TITLE
Discovery - CSV Requirements

### ISSUE THREAD

**Issue by tblackwe** [department-of-veterans-affairs/va.gov-team#61107]
###Description of Spike

**In order to** process the CSV source data

**we need to** discover what transformation of the CSV needs to happen

**so that** we can create the script responsible for transformation.

#### Acceptance Criteria
- [x] Documenting what fields in CSV are required for our processing
- [x] Documenting the format of the CSV

#### Timebox
8 Hours

**Comment by sortizsh** [comment]
We need to speak with Eugene about where this data is stored. We will only be able to access this on our virtual machines

**Comment by sortizsh** [comment]
won't do
