### ISSUE TITLE
Alert messaging review from Benefits team 1

### ISSUE THREAD

**Issue by uxgary** [department-of-veterans-affairs/va.gov-team#61108]
## About your team

- Team name: 
-	OCTO-DE product owner:  Matthew Self
-	Product manager: Jacob Worrell
-	Designer: Gary Homidas
-	FE engineer: Sam Cormier
- Accessibility specialist: Josh Kim
- Content writer: 
-	Product/team Slack channel:
 
### What does your team need support for? Check all that apply.
- [ ] Launching one or more unauthenticated pages, online forms, apps, or tools on VA.gov
- [X] Making revisions to one or more existing VA.gov pages
- [ ] Accessibility review of wireframes and/or prototypes
- [ ] Accessibility issue (general request)
- [ ] Accessibility PDF review request
- [ ] Accessibility user research support ([submit a separate, additional request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name))
- [ ] Something else 
 
### Give a brief description of what your team needs support with:
We're adding new alert messages (warnings) in the Claims status tab and the claims letter page when decision letters are made unavailable due behind the scenes issue (ie technical, administrative).

My team needs support with reviewing and/or rewriting the messages.
 
 ## Timeframe

 ### Will this new product be released incrementally (for instance 25% of users initially)? 
  - [ ] Yes
  - [X] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
### When do you expect to launch your product to 100% of users?
ASAP so we can launch ASAP

*Please provide an estimated date so our team can create other relevant tickets.*
 
### Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [X] No
 
#### If yes, please check all of the phases in the Collaboration Cycle you have completed: 
- [ ] Design Intent
- [ ] Midpoint Review
- [ ] Staging
 
### When does this work need to be completed?
- Estimated launch date:
- Estimated staging review date:
- Content, Accessibility, and IA work needed by: 
  
## Supporting artifacts
*Please provide supporting artifacts as available.*

- Link to product outline:
- Link to or attach user flows:
- Link to prototype or mockups: [Sketch file](https://www.sketch.com/s/0f11d505-f486-4ebb-9c33-36838cac2742)
- Link to your research plan: 
- Link to any epics/issues that may be helpful: [Github Issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/57346)

#### Do you plan to bring this to an upcoming content office hours session?
- [X] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [ ] No, let's work asynchronously and meet if needed

 **Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.
 
### Accessibility Help in Slack
The [#accessibility-help channel](https://dsva.slack.com/archives/C8E985R32) in the DSVA Slack, is also available to you as a resource. Everyone is welcome to ask questions or get help from our a11y (accessibility) specialists. Tag `@Terry Nichols` to get a11y help asap.

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag `@Terry Nichols`.**

- If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
- If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)
 
 - If you are creating an [experimental design,](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) please [also contact the DST. ](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)
- If you are requesting [a11y support for user research,](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name) please complete this form, next.

**Comment by sara-amanda** [comment]
@laurwill this appears to be a content request: 
> My team needs support with reviewing and/or rewriting the messages.

**Comment by laurwill** [comment]
Hi @uxgary ,
The phone number in the alert content seems to be the health benefits hotline number.
Is there a phone number or another contact option Veterans can call to get information about their claim decisions when this feature isn't working?

**Comment by uxgary** [comment]
Hey @laurwill Ive found a new number from this sentence, "You can call us at 800-827-1000 (TTY: 711). We’re here Monday through Friday, 8:00 a.m. to 9:00 p.m. ET."

I found it on the [VA Check Claims or Appeals](https://www.va.gov/claim-or-appeal-status/) does this work?

**Comment by laurwill** [comment]
Hi @uxgary , that page says the number is for general questions about checking your claim status. 

Can your team confirm if Veterans can actually find out what decision VA made on their claim by calling that number?

**Comment by uxgary** [comment]
Thanks for the feedback @laurwill , a team member has confirmed that Veteran can and do.

**Comment by laurwill** [comment]
Hi @uxgary ,
Here's our suggested content for the alerts:

**Decision letters aren't available to download right now**
We're fixing some problems with this tool. Check back later.
If you need information about your decision letters now, call us at [800-827-1000](tel:8008271000) (TTY: 711). We’re here Monday through Friday, 8:00 a.m. to 9:00 p.m. ET.

We'll also need to adjust the content in the blue info alert on the **Your compensation claim** page. We want to avoid saying "You can download your letter now" if the feature isn't available. We also previously suggested changing "closed" to "decided" in this alert. Here's suggested content for this alert when the feature is down, which would appear above the yellow alert about the feature being down:

**We decided your claim on [date]**
We mailed you a decision letter.

Additional notes:
- Phone number and TTY need aria labels for accessibility
- On the Your compensation claim page, the info alert is a full alert style, but the warning alert is background only — should these be the same alert style?

**Comment by laurwill** [comment]
Also, @mistymg is looking into how this alert will work in the mobile app version — she may reach out with more questions. Thanks!
