### ISSUE TITLE
Discovery - VA RDP scripting tools

### ISSUE THREAD

**Issue by tblackwe** [department-of-veterans-affairs/va.gov-team#61109]
###Description of Spike

**In order to** process the CSV source data

**we need to** determine what scripting tools are available to us

**so that** we can create our CSV Transformation Script

Basically, we need to research what tools are installed already on the VA Remote Desktops so we can find a scripting tool we are comfortable working in. 

#### Acceptance Criteria
- [ ] Comment in ticket what tools are available

#### Timebox
4 Hours

#### MR Approver
- TBD

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by tblackwe** [comment]
- Windows Powershell
- Bash Script

Visual Studio Code is available on the Azure remote instances, but Node/Ruby/Python runtimes are not installed to support it.

**Comment by tblackwe** [comment]
I'd like to make sure we have permission to do this kind of work on the remote system. I don't want to need a GFE to do it but the Sign-on warning makes the creation of scripts and executing a bit dubious

**Comment by sortizsh** [comment]
Tyler is going to look into this
