### ISSUE TITLE
Create CSV Transformation Script

### ISSUE THREAD

**Issue by tblackwe** [department-of-veterans-affairs/va.gov-team#61111]
###Description of Spike

**In order to** process the CSV source data

**we need to** create a transformation script

**so that** the CSV is broken into manageable pieces (suggestion of 500 rows per file)

#### Acceptance Criteria
- [ ] If required, script stored in source control
- [ ] Review script with team 
- [ ] Demonstrate testing of script to team

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by steele-lm** [comment]
Closing as null claims will no longer be processed through RBPS.
