### ISSUE TITLE
Disabilities and conditions lists not being updated when user changes from claimingNew and claimingIncrease to claimingNew only

### ISSUE THREAD

**Issue by christinec-fftc** [department-of-veterans-affairs/va.gov-team#61117]
**Overview**
Filing a ticket for an issue that Lydia found where disability and conditions lists are displaying an incorrect list.

**Steps to reproduce**

1. start a new 526 claim. 
2. on the `claim-type` page, select "One or more of my rated conditions that have gotten worse"
`rated-disabilities` page
3. go back and switch the checkbox to "a new condition" on the `claim-type` page
4. continue on in the form until you get to the `disabilities/summary` and `va-medical-records` pages

**Expected**
Only new conditions are listed on the summary and va-medical-records pages.

**Actual**
Rated disabilities are displaying on these pages, even though the user changed their claim type
(In this example, ALS is a new condition and the other two are rated disabilities)
![image.png](https://images.zenhubusercontent.com/641341411444ec27c3eb60a4/b664bbf3-0c29-489a-bb71-8ec0653ba700)

**Comment by RakshindaAslam** [comment]
cc @austinjprice

**Comment by sethdarragile6** [comment]
Not knowing what I don't know on the front end (which is a lot), I would actually expect to see all my conditions on the summary page- not just the ones I newly added. I take it this is _not_ the case?

**Comment by christinec-fftc** [comment]
Thanks for taking a look at this @sethdarragile6 and sorry for the confusion. This is an internally reported bug so I don't think it needs to go through the support rotation triage. We can skip on over to product backlog for pm's to prioritize. I'll move it along. This ticket was created a couple weeks ago, but i think ended up on the bug board in the new column when the defects label was added.

In this case, since the user switched their claim type to new, they should only see the new disabilities on the summary page. Desc says "Below is the list of disabilities you’re claiming in this application."

**Comment by christinec-fftc** [comment]
Created [#65860](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65860) to look into submission issue
