### ISSUE TITLE
References to Max.gov JIRA should be replaced

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/va.gov-team#61125]
### Description
MAX.gov Jira was replaced by a VA-hosted Jira instance (jira.devops.va.gov). At minimum the DataDog instructions need to be updated to not refer to Max.gov, and have all relevant links updated to point to the correct Jira instance.

The DOTS service desk on Jira is now located at 
https://jira.devops.va.gov/servicedesk/customer/portal/1/group/3

### Relevant URLs
Here's are two pages that have references/links to Max.gov JIRA:
https://depo-platform-documentation.scrollhelp.site/developer-docs/get-access-to-datadog
https://depo-platform-documentation.scrollhelp.site/developer-docs/troubleshooting-access-to-datadog

### Which type of team are you on? (Platform team, VFS team, or Leadership)
Leadership

**Comment by vbellissimo** [comment]
Hi @patrickvinograd , thanks for submitting this request. the Platform is taking a look for next steps.

**Comment by mchelen-gov** [comment]
linking: https://github.com/department-of-veterans-affairs/va.gov-team/issues/61545

**Comment by vbellissimo** [comment]
Hi @patrickvinograd, Just wanted to let you know that we went ahead and updated both of these pages based on more information provided to us by SMEs here at the Platform. Please let me know if there's anything else you noticed that we may have missed. Thank you.

- https://depo-platform-documentation.scrollhelp.site/developer-docs/get-access-to-datadog
- https://depo-platform-documentation.scrollhelp.site/developer-docs/troubleshooting-access-to-datadog
