### ISSUE TITLE
Update the breadcrumb on the appointments details page (MHV on VA.gov) - Pending appointments

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#61142]
## Description
The Appointments application will be under the MHV on VA.gov portal. We will need to update the breadcrumb structure. #61142 will focus on the Pending appointments page. 

---

## Acceptance Criteria
Background: the `va_online_scheduling_breadcrumb_url_update` toggle is on

- [x] Given the user is on the `Upcoming VA appointments` landing page, 
        When the user clicks on `Pending` link and `Details` link for a pending appointment, then breadcrumbs will be updated to `< Back to [h1 of previous page]`

- [x] Given the user is on the `Upcoming VA appointments` landing page, 
        When the user clicks on `Pending` link and `Details` link for a canceled pending appointment, then breadcrumbs will be updated to `< Back to [h1 of previous page]`

### Reference
[Spike ticket #54757](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/54757)

### Design Assets
[Title tag format guidance](https://design.va.gov/content-style-guide/seo#title-tags)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by jenniemc** [comment]
@ldelacosta, The AC for this ticket was also covered and completed by the second AC in  #61015

**Comment by ldelacosta** [comment]
@jenniemc Reviewed the pages in staging for judy.morrison@id.me. The descriptive back link should be Back to H1 of the previous page. 

The page should be updated. Let me know if you have any questions.  

![Screenshot 2023-08-02 at 3.03.02 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/3df6e30a-617f-43ea-bdd2-ab465c996058)

![Screenshot 2023-08-02 at 3.03.30 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/9129aa47-e1e9-4d96-9d80-03166ca3386d)

**Comment by ldelacosta** [comment]
Validated the changes in staging for Judy Morrison. Notified the designers to validate the ticket. 

![Screenshot 2023-08-08 at 2.53.06 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/7d0bd143-be2a-4768-a8ba-0cd8624fe1ec)
![Screenshot 2023-08-08 at 2.53.54 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/91afd9a1-304e-4441-bd39-ee17c7593666)

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket.
