### ISSUE TITLE
Update the breadcrumb on the appointments details page (MHV on VA.gov) - Past appointments

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#61143]
## Description
The Appointments application will be under the MHV on VA.gov portal. We will need to update the breadcrumb structure. #61143 will focus on the Past appointments page. 

---

## Acceptance Criteria
Background: the `va_online_scheduling_breadcrumb_url_update` toggle is on

- [x] Given the user is on the `Upcoming VA appointments` landing page, 
        When the user clicks on `Past` link and `Details` link for a past appointment, then breadcrumbs will be updated to `< Back to [h1 of previous page]`

### Reference
[Spike ticket #54757](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/54757)

### Design Assets
[Title tag format guidance](https://design.va.gov/content-style-guide/seo#title-tags)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by jenniemc** [comment]
@ldelacosta, The AC for this ticket was also coincidentally completed by #61086.

**Comment by ldelacosta** [comment]
Validated the change in staging for judy.morrison@id.me 

![Screenshot 2023-08-02 at 2.51.58 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/5f76d5d9-1c93-4fe3-a574-bf3fd31693d6)

**Comment by melissa-lefevre** [comment]
Validated. looks good @ldelacosta

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket.
