### ISSUE TITLE
Add information to frontend new application creation docs

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#61156]
### Description

A couple of suggestions:

1. I think the following note at the end of step 4 should be split out into its own step, I've talked to multiple devs trying to create new applications that have missed this important step:

>Note: you must [update revproxy config](https://depo-platform-documentation.scrollhelp.site/developer-docs/routing#Routing-ReverseProxyConfig) to reflect the addition of your application in order internal links via react-router to work properly.

2. I think it would be helpful to add this information:

When creating a new application, you'll need to merge your application into `vets-website` before CI will pass on the registry addition in `content-build`.

### Relevant URLs

- https://depo-platform-documentation.scrollhelp.site/developer-docs/creating-a-new-application

### Which type of team are you on? (Platform team, VFS team, or Leadership)

OCTO engineering

**Comment by vbellissimo** [comment]
Hi @acrollet , thanks for submitting this request. Do you have any thoughts on where to place this recommended line on the page?

> When creating a new application, you'll need to merge your application into `vets-website` before CI will pass on the registry addition in `content-build`.

**Comment by acrollet** [comment]
@vbellissimo I think I would probably add an `h2` titled something like "PR merge order" below the manual setup section and adjust the text to be:

> Whether you use the Yoeman generator or create your application manually, you'll need to get your PR to `vets-website` approved and merged first. Automated tests should then pass for the registry addition in `content-build`.

**Comment by vbellissimo** [comment]
Excellent. Thank you so much, @acrollet . We will get this ready for someone on my team to update.

**Comment by taylojill** [comment]
Hi @acrollet I made the following updates to the Creating a new application page. I have attached a PDF export showing the changes. Let me know if they work for you. If so, I will make changes to the live page and get it ready for deployment on Monday afternoon. Thanks!
CC @vbellissimo 
[Copy of Creating a new application_JT edits.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/11983743/Copy.of.Creating.a.new.application_JT.edits.pdf)

1. Added a step 5 to Update revproxy config...
2. After Manual setup section, added PR merge order section and text

**Comment by acrollet** [comment]
@taylojill thanks! 🙂 I have a couple of edits:

- the paragraph of text in the new step 5 should be in step 4 underneath the code sample.
- step 5 is missing a word. I think I would change it to something like "Update revproxy config to reflect the addition of your application so that internal links created via react-router will work properly."

**Comment by taylojill** [comment]
Hi @acrollet I'll update the page and get it ready for deployment today. Thank you!
cc @vbellissimo

**Comment by acrollet** [comment]
thank you @taylojill !
