### ISSUE TITLE
[Other - Accessibility] Focus indicator is misleading. (00.00.2)

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#61159]
#### VFS team name
Authenticated Experience

#### VFS product name
My VA

#### VFS feature name
Notification design system component

#### Point of Contact/Reviewers
Brian DeConinck - @briandeconinck - Accessibility

*For more information on how to interpret this ticket, please refer to the [Anatomy of a Staging Review issue ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Anatomy-of-a-Staging-Review-Issue-ticket.2060320997.html) guidance on Platform Website.

---

### Platform Issue
No VA.gov Experience Standard for the issue found.

### Issue Details
When tabbing through notifications, if a button or link inside a notification has focus, the entire notification gets a focus outline ring around it. For keyboard-only or keyboard-first users, it's a little unusual to see something that looks like it has focus and also see multiple things inside it that can receive focus. It shouldn't trip up most users, but it's possible that it could cause confusion about where focus is and what's actually going to be activated.

### VA.gov Experience Standard
[Category Number 00, Issue Number 00](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

### Platform Recommendation
I *think* I see what's happening here. The Formation CSS file has a style rule for focus indicators that targets anything with an `href` attribute. (So that functional links get the focus indicator, but other `a` elements don't, I guess?) The property of the `va-notification` component that handles the action link destination is named `href`, and so the CSS rule targeting anything with an `href` attribute is getting triggered. So renaming that property to something other than `href` should solve this.

---

### VFS Guidance

- Close the ticket when the issue has been resolved or validated by your Product Owner
- If your team has additional questions or needs Platform help validating the issue, please comment on the ticket
- Some feedback provided may be out of scope for your iteration of the product, however, Platform's OCTO leadership has stated that all identified issues need to be documented and it is still your responsibility to resolve the issue.
- If you do not believe that this Staging Review issue ticket is the responsibility of your team, comment below providing an explanation and who you believe is responsible. Please tag the Point of Contact/Reviewers. Governance team will research and will follow up.

**Comment by ajakabcin** [comment]
Closing this - the feature was removed from My VA and design system component deprecated/marked for deprecation
