### ISSUE TITLE
[Other - Accessibility] `focus`, `hover`, and `active` styling for improved material honesty. (00.00.3)

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#61160]
#### VFS team name
Authenticated Experience

#### VFS product name
My VA

#### VFS feature name
Notification design system component

#### Point of Contact/Reviewers
Brian DeConinck - @briandeconinck - Accessibility

*For more information on how to interpret this ticket, please refer to the [Anatomy of a Staging Review issue ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Anatomy-of-a-Staging-Review-Issue-ticket.2060320997.html) guidance on Platform Website.

---

### Platform Issue
No VA.gov Experience Standard for the issue found.

### Issue Details
For the close button with close text, it's important to maintain material honesty and help users recognize that it's a button and not some other element. The lightweight styling (no background, no border) doesn't really do enough on its own to indicate that the button is a button.

### VA.gov Experience Standard
[Category Number 00, Issue Number 00](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

### Platform Recommendation
I don't think Matt's [tertiary button explorations](https://www.sketch.com/s/be292806-8dbf-4201-bfa7-0edbba103347) have been officially adopted into the design system yet, but the hover/focus/active states in that Sketch file are the compromise we landed on for a lightweight style that still distinguishes itself from links or other elements.

---

### VFS Guidance

- Close the ticket when the issue has been resolved or validated by your Product Owner
- If your team has additional questions or needs Platform help validating the issue, please comment on the ticket
- Some feedback provided may be out of scope for your iteration of the product, however, Platform's OCTO leadership has stated that all identified issues need to be documented and it is still your responsibility to resolve the issue.
- If you do not believe that this Staging Review issue ticket is the responsibility of your team, comment below providing an explanation and who you believe is responsible. Please tag the Point of Contact/Reviewers. Governance team will research and will follow up.

**Comment by ajakabcin** [comment]
Closing this - the feature was removed from My VA and design system component deprecated/marked for deprecation
