### ISSUE TITLE
The ID.me Smartphone Question

### ISSUE THREAD

**Issue by kingbmike** [department-of-veterans-affairs/va.gov-team#61172]
As we chatted, we’re interested in having your team provide more insights on what someone should do if they have any of the three options listed (like using KBV instead).
Again, we could consider making this info a new question- that is still TBD/sitewide content team can make this determination.
If you can use tracked changes, with any updated information, that would be great.
After you all are done, we’ll review the content and make any adjustments to align with VA style.

I don’t have a smartphone. How do I verify my identity through ID.me?
You’ll need either a landline or mobile phone, and a computer with an internet connection.
At this time, we can’t support:
 [ ] Phones registered under a family member or spouse
 [ ] Virtual phone services like Skype or Google Voice
 [ ] International phone numbers

**Comment by aparsley** [comment]
I can confirm that the below text is currently accurate. 

I don’t have a smartphone. How do I verify my identity through [ID.me](http://id.me/)?
You’ll need either a landline or mobile phone, and a computer or tablet with an internet connection.
If you do not have a mobile phone or your mobile phone is registered under a family member or spouse, you may be asked to [verify your identity on a video call](https://help.id.me/hc/en-us/articles/360052242853) with an ID.me Trusted Referee.
If you do not have a U.S. phone number, please follow the instructions to verify your identity here: [What if I don't live in the United States](https://help.id.me/hc/en-us/articles/4415907236375-What-if-I-don-t-live-in-the-United-States-)?
At this time, we can’t support voice-over IP phone numbers like Skype or Google Voice.
You don’t need a smartphone to verify your identity with ID.me. You can also verify your identity using a computer or tablet—as long as it has access to the internet and meets ID.me’s [technical system requirements](https://help.id.me/hc/en-us/articles/1500004615921-What-are-the-technical-requirements-to-verify-my-identity-).
The following ID.me Help Center resources may be helpful to users:
[Do I need a smartphone to verify my identity?](https://help.id.me/hc/en-us/articles/1500007988602-Do-I-need-a-smartphone-to-verify-my-identity-#:~:text=You%20can%20also%20verify%20your,me's%20technical%20system%20requirements.)
[Why can't my phone number be verified?](https://help.id.me/hc/en-us/articles/360017839774-Why-can-t-my-phone-number-be-verified-)
