### ISSUE TITLE
Identity Dashboard (FE) - Client config BE integration

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#61181]
## Description
This will track the scope of work that is required to fully integrate the Client Configs management (Client Config page) with the Backend. Note* this can and probably should be further refined into smaller tickets

## Scenarios
- [x] On the *Create new integration* page
  - [x] The required fields should be validated (use `yup` or other validation library)
  - [x] The state should should be captured/saved when clicking forward/backward through the 
  - [x] When clicking the "Finalize setup" button
    - [x] A fetch request (POST) occurs to the BE API to "Client Config creation" endpoint with the necessary fields from BE
- [ ] When on the "Client Configuration" page
  - [x] Create a Fetch request to the BE API to see if the teams exist and conditionally render the "Table of Client Configs" or the "Empty State Client Configs" page
    - [x] When on the "Table of Client Configs" view
      - [x] Clicking the "Modify" button takes me to the "Edit my Client Config" page 
    - [x] When on the "Empty State Client Config" view
      - [x] Current functionality exists

**Comment by acaruso-oddball** [comment]
blocked by CORS config Alex will review

**Comment by acaruso-oddball** [comment]
also connected issue #60072
