### ISSUE TITLE
Access for Bill Fienberg

### ISSUE THREAD

**Issue by billfienberg** [department-of-veterans-affairs/va.gov-team#6119]
# Instructions
1. Fill out **Description** ✅ 
2. Add the label used by your team (eg: `BAH-526`) ✅ 
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team ✅ 
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Contracting Officer's Representative (COR) name: Nancy Smith
- Please provide your name.
   > Name: Bill Fienberg
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Team: Content & IA
   > Role: Senior Frontend Engineer
   > Company: Oddball
- **Public** SSH key:
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDnQhHV5dLpUA50hSPAPHrhIhXdGKad+Huv53UaytWZK80sqCgbo4NLccKH7fAsPbFtizKlhHkDQ7bdcdiQEal/0CvVpogrYPoklORGvWCdqfZZHVOEw6KTkE13Z7Ej6QDTpCX4TYxhbSDoQDtaJ9DGguSTWZGerjXsRUdTQCgQIs3U2iTKvcxDvjO/yiUCrudHUna6EjoSYkz+rNL8UY4ueUm4RqVhrLzYZQCM6OEUF2NOMBx6bKMRQeXFNudaVwY5wbiEkqqOZ0QzyY/pS8BCO1g7tEbX0AQtkQblDRshaJVHWeX5/NfrHUu9Op3a3uyXdlFBO+JFhReY3Id9UawV bill@Williams-MacBook-Air.local
```

- [Grant AWS Console access?]
  > NO

**Comment by billfienberg** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by ricetj** [comment]
SOCKS access is granted. You should now refer to this [section](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) in the instructions to set up your SOCKS.
