### ISSUE TITLE
OOB Deploy Request: injected header fix

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-team#61197]
# Instructions
Please fill out the necessary details and list the PRs related to the OOB deployment in the sections below.

## PRs Related to OOB
- Please provide the list of PRs related to the need for this OOB Deploy below:
   > https://github.com/department-of-veterans-affairs/vets-website/pull/24698

## Active Daily Users Impacted
- How many active users are impacted at this time and day.
   >  All users of TeamSites using injected header/footer, numbers unknown 

## Has fix been confirmed in Staging?
- [ ] Yes
- [x] No -- not possible for injected header sites

## Description
- Please provide the details/reason for the OOB Deploy
   > Public Websites merged a change to add the VA web components library to be available on Injected Header sites. Due to limitations around testing the injected sites, we were not able to verify behavior pre-prod, and accepted risk of shipping to prod with fast follow rollback if the change was not successful.   With this change in place, injected header/footer do not appear on the TeamSites where they should. We need to roll back.   (Launch plan discussion for reference: https://dsva.slack.com/archives/C52CL1PKQ/p1687895579831899)
   
## Verify The following
 - [x] The OOB Deploy Request is after the 2pm EST cutoff for regular deploy.[^1] 
 - [x] The OOB Deploy Request is critical and must be resolved before the next automated deploy.
 - [x] You are prepared to create an Incident Post Mortem[^2] within two business days.

[^1]: (See [Deployment Policy](https://depo-platform-documentation.scrollhelp.site/developer-docs/deployment-policies) and [Deployment Schedules](https://depo-platform-documentation.scrollhelp.site/developer-docs/Deployments.1844641889.html)
[^2]: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/Postmortems

*Performed by Platform Support Team*
 - [x] PagerDuty OOB Deploy Incident Opened
 - [x] OCTO-DE staff acknowledgment of Request, via `/pd trigger`
 - [ ] Notification is posted in the appropriate Slack support and team Channels
 - [ ] Infrastructure/Operations has acknowledge the Requests
 - [ ] Security Team has Reviewed the requests

 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-product-support

**Comment by jilladams** [comment]
This ticket was in response to https://dsva.slack.com/archives/CBU0KDSB1/p1688067509766669

**Comment by lindsay-insco** [comment]
Deployed and post-mortem completed
