### ISSUE TITLE
Access for Dorothy J. Biederman

### ISSUE THREAD

**Issue by dorothyjb** [department-of-veterans-affairs/va.gov-team#612]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Greg Kirk
- Please provide your name.
   > Dorothy J. Biederman
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > BYLIGHT, Project Support, By Light Professional IT Services LLC
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Internal%20Tools.md#create-ssh-public-key) for instructions.
  > ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAmgBUiFar4FH/xqM65MF3AQPdKfs9sGoofL+ENG1wKeTJ/LsihWT6vri3Ewp9fmuH/QsFNRSWDo2yG0IGNrh/8jzd5TiEmYRn3KLyU4lEKz4D79elZJgiraTpcItnZTbgVB7n+Nu8VJXRBoOkhA+ZVO1XK7MJSnQzkB5+0h5OHQQ2NeDcNzdoOH0AsOtg0HQ+UeL7NAwGJ47AjsyhoNYgPjN01FikfvFLzPuK403hER4elxbDIf8AzK7Z5OqAKw/A8aeJDEdfhHnkXAQ0wupxmID1USGfp/7fmrIuPPl2BmdMTmyjgiAHHZX03jmuw+g9KloPNkL7u9VF6smuO8Rqfw==
rsa-key-20190717

- [Grant AWS Console access?]
  > YES

@department-of-veterans-affairs/vsp-operations

**Comment by b00klegger** [comment]
@Jeff-Hayter 

> COR - Greg Kirk
> Req - Dorothy J. Biederman

**Comment by Jeff-Hayter** [comment]
@b00klegger - Confirmed.  Please grant access.

**Comment by b00klegger** [comment]
Public key added to infrastructure. Account created in AWS. @dorothyjb You are OK to complete the rest of the onboarding process.
