### ISSUE TITLE
Documentation - Make Architecture diagram for planned end state

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#61209]
# Description
Given the current state of our research and implementation in the problem space, how do we expect the system to look upon completion of the MVP?

# Tasks
- [x] Extend and detail the existing diagrams [here](https://lucid.app/lucidchart/ad6dd0e9-d314-4fd3-b9cf-23b158e9276b/edit?viewport_loc=-469%2C40%2C4377%2C3510%2C0_0&invitationId=inv_159d8a3a-5b50-4b5a-8505-d31268eaa4ee)

# Acceptance Criteria
- [x] An architecture diagram with details for all system components is available

**Comment by pjhill** [comment]
Diagram updated to reflect --
* caching of content-build with datasync
* argocd orchestrating deployment
* use of traefik route to vets-api
