### ISSUE TITLE
Modify GHA workflows to write values to manifests

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#61203]
# Description
Given that we want to have BE pods with unique resource names for use in multiple PE instances, we need to feed the unique values into the manifests by passing dynamically generated values in from the GHA workflows that generate the manifests.

Use the values associated with a given branch and repository to supply a dynamically generated name for `vets-api` resources in a PE instance.

# Tasks
- [ ] Use the list of values required to make `vets-api` resources unique to guide the create of new variables assigned during GHA workflow execution

# Acceptance Criteria
- [ ] When a PE instance starts, it uses dynamically generated values to name `vets-api` resources for each PE instance

**Comment by CBonade** [comment]
@cyriltech are you able to please provide a list of the values that need to be updated and what kind of format we're hoping for them to appear in?

**Comment by CBonade** [comment]
Still awaiting specifications on what needs to be altered to be able to complete this ticket.

**Comment by cyriltech** [comment]
This [PR](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/2099) is to push new template-values file

**Comment by JoeTice** [comment]
Believe this ticket is OBE and no longer will be done as originally planned
