### ISSUE TITLE
update Identity Dashboard authentication diagrams

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#61202]
## Issue Description
Identity Dashboard needs up-to-date diagrams of its authentication flows.

---
## Tasks
- [x] update [Identity Dashboard Auth flow](https://lucid.app/lucidchart/c0d9a2d7-0f20-4e48-94e1-87133e7227fe/edit?page=0_0&invitationId=inv_87605cec-f11d-4ac0-b661-6f668ddd8e0a#) to reflect frontend-driven nature of SiS authentication
- [x] add [diagram for Service Account authentication](https://lucid.app/lucidchart/809ec338-4f67-4062-82d5-2c5313f7cf63/edit?page=0_0)

**Comment by aparsley** [comment]
Thank you for attaching updated diagrams for review.
