### ISSUE TITLE
Midpoint Review - Content Feedback - Authenticated Experience, Profile, Notification Settings, Updates to Edit Flow

### ISSUE THREAD

**Issue by CherylEvans** [department-of-veterans-affairs/va.gov-team#61214]
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

-

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

### Must

- Bread crumb verbiage on Mobile and Desktop don't match. Desktop: Back to last page Mobile: Back to previous section. Verbiage must be consistent on both mobile and desktop devices.
![58231_Desktop_Back to Last Page_Screenshot 2023-06-28 at 3.28.49 PM.png](https://images.zenhubusercontent.com/61fa9c81372349426637bcfa/71191c53-f77e-475e-84ea-cb86c31c96be)![58231_Mobile_ Back to Previous Section_Screenshot 2023-06-28 at 3.29.01 PM.png](https://images.zenhubusercontent.com/61fa9c81372349426637bcfa/5efcfccb-a0d6-485c-8bea-5d062c2d84ec)

**Comment by mtcA6** [comment]
@CherylEvans what wasn't clear for me is, should we maintain the breadcrumbs or remove them?

**Comment by CherylEvans** [comment]
@mtcA6 Good morning, Travis.  The breadcrumbs are fine; however, the verbiage between the desktop and mobile applications should match. The mobile says, "back to previous section," and the desktop says "back to the last page."  If this is going to change before the Staging review, that's fine, but they should match.  Please feel free to reach out to me if further clarification is needed. :-)

**Comment by andaleliz** [comment]
@adamwhitlock1 the page in question here is for the edge case where we don't have a query in the URL. If that's the case, would we have a dynamic "previous section/page" to populate the breadcrumb, or do we need to plan for a static link?

**Comment by adamwhitlock1** [comment]
> @adamwhitlock1 the page in question here is for the edge case where we don't have a query in the URL. If that's the case, would we have a dynamic "previous section/page" to populate the breadcrumb, or do we need to plan for a static link?

This is a great point, and since the breadcrumbs are a _newish_ added part of this page, one that I hadn't thought about in regards to this edge case.

I would say that the best thing to put there is a static link to the `/profile` if there isn't the correct information present in the URL. Would you agree @andaleliz?

**Comment by andaleliz** [comment]
Yep @adamwhitlock1 I agree with that. I'll update the mock ups to display a static `Back to profile`

**Comment by andaleliz** [comment]
[Desktop](https://www.sketch.com/s/1fd4d140-84ad-4301-9c74-d5cebc4a012d/v/0qGRoj/a/ZOzGKLZ) and [mobile](https://www.sketch.com/s/1fd4d140-84ad-4301-9c74-d5cebc4a012d/a/yg23exo) mockups have been updated
