### ISSUE TITLE
Design System Staging Review - IA Feedback - Converted components: Alert and Additional info

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#61217]
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- The term “notifications” is used throughout DS guidance page for this the alert component. Maybe a larger discussion would be helpful to settle on distinct definitions for the two concepts. This is closely related to the staging review on the notifications component this week. 

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

#### Design System Guidance:

Section: Usage > How to use alerts section
* **Must**: Two of the bullets read “Don’t include notifications that aren’t related to the user’s current goal” and "Allow a user to dismiss a notification wherever appropriate." Notifications & alerts are being conflated here. These should be distinct components with their own use cases. 

Section: When to use a Slim alert
* **Must**: Guidance says that headings are optional in Slim alerts (which matches the examples above and looks fine) but earlier on the page under Examples - Properties > Heading level there is guidance that says "alerts should contain headings." Clarify in both instances if Slim alerts are exempt from that requirement. 
<img width="912" alt="Screenshot 2023-06-29 at 4 44 10 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/115033532/ecd8dd11-f00b-4555-b77e-10954c43e3cb">

Section: None [Missing guidance on when to use a variation]
* **Should**: Provide guidance on when to use variations with icons.

#### DS, Sketch & Storybook: 
* **Should**: We give guidance not to stack alerts. But the guidance also says that default & slim styles can be used to build a hierarchy of alerts. This is competing guidance, but if it is allowed can we show an example of nested / hierarchical alerts? What would this look like done correctly?

**Comment by humancompanion-usds** [comment]
I updated the guidance for the items that were still relevant. Notification component was deprecated already so that made the task a bit easier.
