### ISSUE TITLE
Midpoint Review - IA Feedback - Authenticated Experience, Profile, Notification Settings, Updates to Edit Flow

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#61212]
## VFS actions
- [x] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [x] Comment on this ticket:
  - [x] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [x] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [x] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [x] Close the ticket when all feedback has been addressed.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- **Should**: add content to communicate that updating a phone # or email address will affect the user's entire profile.
- ~~**Should**: The "required" text is throwing me - I thought this was optional? I understand that _technically_ we need the user to enter something in order to save it on the page, but this red text communicates that I **must** add this info to add this to my profile in order to proceed. Consider removing the "required" text and instead trigger an error message if users try to save an empty content box.~~ 
- **Should**: The link "cancel and go back to previous page" is the same as the back breadcrumb. Redundancy is not necessarily bad, but on a page with such little content, the semantics are noticeably duplicative. Consider reducing text to just "Cancel" to make it clear that the intention for this link is to undo the action. 
<img width="209" alt="Screenshot 2023-06-29 at 3 57 39 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/115033532/d7becafe-ab9c-4209-ace4-01707c6fccf9">

- **Consider**: This is minor since it is literally one field that requires pretty low effort, but currently, if a user types something in and then hits "cancel" (or forgets to click "save") it is a single destructive action. Do you want to add a modal that asks the user to confirm before losing their progress (e.g. "wait, did you want to save your update before leaving this page?")

**Comment by andaleliz** [comment]
Thanks for this feedback! One question about this:

>The "required" text is throwing me - I thought this was optional? I understand that technically we need the user to enter something in order to save it on the page, but this red text communicates that I must add this info to add this to my profile in order to proceed. 

Hmm, I see what you're saying, but I'm struggling to think of a use case where it would _not_ be required for a person to proceed from whatever call to action they clicked on to get there (a link saying "Update your [profile information] or something like that).  Are there any in particular you're thinking about?

>Consider removing the "required" text and instead trigger an error message if users try to save an empty content box.

This would be a departure from any other form I've seen on VA.gov and I'm inclined not to re-invent any wheels unless it's absolutely necessary :)

**Comment by sterkenburgsara** [comment]
@andaleliz Thanks for pushing back on that - I definitely don't intend for you to do something that is a departure from other similar work on VA.gov! I don't completely agree that this interaction will feel like a form to users, as it is a single field without a "submit" button. But it certainly is on the back-end. I do follow what you're saying about removing "required" and then flagging users for not entering something. There may not be a perfect solution for this edge case. I chatted with @allison0034 about this and we agreed your solution is the clearest path we could think of, so please dismiss my "should" feedback about removing that required text. 

Thanks!

**Comment by andaleliz** [comment]
Thanks @sterkenburgsara! I won't move forward with it then, but I want to confirm we're talking about the same thing since you said
>as it is a single field without a "submit" button.

The "edit as a sub-task" page does have a button, though the label says Save instead of Submit.  The notification settings page a person starts on to get to the sub-task page auto-saves, so it does _not_ have a button.  

You were talking about the first one this whole time, correct?

**Comment by sterkenburgsara** [comment]
@andaleliz yep, talking about the same thing 👍

**Comment by pamela-drouin** [comment]
@andaleliz I'll finish this ticket

**Comment by pamela-drouin** [comment]
@andaleliz Updated mocks here: https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/p/8F33D983-75FB-4317-9DAF-D8306F3966FB/canvas

**Comment by mtcA6** [comment]
@pamela-drouin do we have updated desktop mocks as well?

**Comment by pamela-drouin** [comment]
Not yet, I will need to pull those together!

*Pam Drouin*
*Sr. UX Researcher/Designer*

**Comment by andaleliz** [comment]
@pamela-drouin these look great, and I like how you did the flows too! I think as part of the flow update I'm working on, I'm going to adopt your arrow styles, and add an example of how the "update" (instead of add) works, just for clarity.  Thanks for adding the desktop mocks.

**Comment by mtcA6** [comment]
@pamela-drouin so i can prep for planning, how many points did you complete, how many are carrying over or need to be added?

**Comment by pamela-drouin** [comment]
@mtcA6 There is one point left to do.

**Comment by pamela-drouin** [comment]
@andaleliz -- I added desktop screens to the page I was working in: https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/p/8F33D983-75FB-4317-9DAF-D8306F3966FB/canvas

Would you check and see if I got everything? Do I need to do anything else?

**Comment by andaleliz** [comment]
@pamela-drouin, thanks for doing this! There are a couple of things I see:
1. The desktop screens need to have the breadcrumb + sub-heading that we added after the first round of feedback. The mobile screens have them so hopefully it's not too much to copy them over there.

2. I think we have all fallen victim to the conflation of the "edit as a sub-task" being tied to notification settings, and I apologize for not catching this sooner. I believe the modal screens, and button updates, should be in the "[edit as a sub-task](https://sketch.com/s/1fd4d140-84ad-4301-9c74-d5cebc4a012d)" Sketch file, instead of notification settings, since those changes would need to be applied regardless of what someone is updating. The good news is that since that file is set up to show variable text, we don't need to do "add mobile" AND "add email" variations.

I'm going to incorporate the work you did into the flow on the mobile page, so it is certainly not wasted effort.

I wonder if we should re-think how these are organized, since they continue to confuse everyone, including me? I'm not sure of a better way.

**Comment by pamela-drouin** [comment]
@andaleliz I will fix what I missed. I'm glad you're able to use this to incorporate into the mobile page!

Let's make some time to meet about the organization so we can figure out what needs changing (if anything, it could just be me not quite getting the gist!).

**Comment by andaleliz** [comment]
Pam and I met today, and everything is updated where it needs to be. The Sketch file for our [edit as a sub-task flow](https://sketch.com/s/1fd4d140-84ad-4301-9c74-d5cebc4a012d) has the desktop and mobile screens with:
- updated "Save to profile" button label
- cancel modal
