### ISSUE TITLE
Adding Rockwell Rice to DSVA Slack

### ISSUE THREAD

**Issue by rockwellwindsor-va** [department-of-veterans-affairs/va.gov-team#61231]
I am trying to get added as a multi-user channel to these channels: team-banana-peels and api-benefits-claims
Email: [rockwell.rice@oddball.io](mailto:rockwell.rice@oddball.io)

This was originally requested here https://github.com/department-of-veterans-affairs/va.gov-team/issues/56126

It appears the memebers on my team have access to these channels but I cannot access links that are shared so wanted to come back here and see if I could get added.

Thanks!

**Comment by KevinMHoffmanUSDS** [comment]
Going to close this issue as I've DMed with Rockwell directly. If there are any issues, please reopen and assign to me. Cheers!

**Comment by rockwellwindsor-va** [comment]
Just in case this needs to be documented.  Tried getting an invite today from someone in a channel and the return was
```
from Slackbot: "You mentioned  @Rockwell Rice, but they're a Single-Channel guest and don't have access to this channel."```

**Comment by KevinMHoffmanUSDS** [comment]
I believe this issue has been resolved. Reopen if needed, and have a great weekend!
