### ISSUE TITLE
Design System Staging Review - Design Feedback - Converted components: Alert and Additional info

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#61232]
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

### Alert
Sketch
- **Must** add a dismissible version to Sketch

### Additional Info
- no feedback

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

-

**Comment by humancompanion-usds** [comment]
Added Alert - Info - Dismissible to Sketch: https://www.sketch.com/s/a52734dd-00d0-44f1-9c9e-ff4016130e5c/p/5E24F540-2558-488C-BD6D-823F4A2F5607/canvas
