### ISSUE TITLE
SSOe session keep-alive from va.gov

### ISSUE THREAD

**Issue by hinzed1127** [department-of-veterans-affairs/va.gov-team#6123]
# Story

As a SSO user, I want my SSOe session to be extended as long as I stay active on VA.gov.

## Background

Since VA.gov doesn't explicitly make any requests to IAM that would extend the life of an SSOe session, we need to track this from the front-end and periodically make requests via a keepalive endpoint.

## Technical Details

The endpoint to hit is https://pint.eauth.va.gov/keepalive (note that the 'pint' portion needs to be adjusted based on environment)

The response of this request will have a `session-timeout` header that will always be 0 or 900 (900 being seconds, ie 15 min, before the SSOe session expires, or 0 for an inactive session). 

Per @ericbuckley :

> some changes were recently made to the /keepalive endpoint, to interact with it from within the browser you can run the following snippet.

```js
fetch('https://pint.eauth.va.gov/keepalive', {
    method: 'GET',
    credentials: 'include',
    cache: 'no-store'
  })
  .then(function(response) {
    console.log(response.headers.get('session-alive'));
    console.log(response.headers.get('session-timeout'));
  })
```

This logic will get added into the api utility of `vets-website` (`src/platform/utilities/api/index.js`)

## ACs

- [ ] An active VA.gov user with an active SSO session is extended as long as they remain active 
- [ ] The keepalive checks are feature-flagged to prevent non-SSO users from making unneccesary requests

**Comment by ericbuckley** [comment]
As noted from Marat on the IAM team, we should attempt to only hit the keepalive endpoint at most once per minute, per user.

**Comment by hinzed1127** [comment]
Something parallel to #5405, but what is the best way to look detect an IAM session from any given page? There's a bunch of different cookies that seem to get set by IAM, but I'm not sure what the definitive thing to check should be.

Specifically thinking about this in the context of rate limiting keepalive requests

**Comment by ericbuckley** [comment]
hitting the `/keepalive` endpoint should give us this information.  If the value in `response.headers.get('session-timeout')` is "0" then there is no session, any positive value would mean that the user has an active session.

**Comment by hinzed1127** [comment]
Thinking through initialization of this with respect to minimizing the impact, even under the hood, this has on non-SSO users. 

Right now, the callback redirect to the frontend after authenticating is the same for both v0 and v1 sessions controllers. In order to only initialize the session timeout value in `localstorage` for the relevant users, would it make sense to do this via a flag returned from the backend that indicates an SSO session active? This would ensure that the sessionTimeout is initialized just for SSO users without anything sneaky from the frontend and in a natural flow of the login process. Then subsequent requests to the api wrapper could follow this logic:

1. Is there a localstorage item for SSO? If no, do nothing
2. If yes, go through the additional logic of whether we need to call the keepalive endpoint

**Comment by ericbuckley** [comment]
@hinzed1127 what about the case where a user vists va.gov from an affiliated site they've already logged in to.  To determine what to do with that user, we'd need to run the "keep alive" check before any authentication step.

**Comment by hinzed1127** [comment]
@ericbuckley that's a good callout that I think should get addressed in a separate PR, but after thinking on it a bit more, my tentative approach there would be via the header component, and just determining the UX flow.

Right now the user dropdown checks this on page load (ie, so the "Sign in" button can become a dropdown with the user's first name if signed in). My thought would be to incorporate the SSO localstorage check there, too, and then if it's not present, make a keep-alive call and initialize accordingly.

I think this has already been answered, but if the SSOe session exists but the `vets-api` one does _not_ , what is the process for initializing that session?

**Comment by ericbuckley** [comment]
@hinzed1127 I believe we just want to redirect the user to `/v1/sessions/idme/new`.  This will trigger a new authentication flow with SSOe, but the type (idme, mhv, dslogon) shouldn't matter in this case.  The hope being that since SSOe already has a cached response for this user it will immediately redirect back to va.gov with the appropirate SAML response (which would then create the va.gov session) and not attempt to send the user to the IDP for login.

The one exception is that in some cases we will need to redirect the user to `/v1/sessions/idme/new?force=true` to force a one time reauthentication.
