### ISSUE TITLE
Add alert about awaiting translation to Tagalog PACT page

### ISSUE THREAD

**Issue by megzehn** [department-of-veterans-affairs/va.gov-team#61237]
We need to add an alert to PACT pages in Tagalog when we're awaiting translation. We need to copy the content from the alert we used for the COVID pages, and update the link with the [English PACT page. ](https://www.va.gov/resources/the-pact-act-and-your-va-benefits/)

Tasks

- [x]  Create new alert for main PACT page in Tagalog, using [copy from the alert we used for COVID ](https://prod.cms.va.gov/block/236?destination=/admin/content/alerts)(Ana)
- [x]  Copy edit alert (Megan)
- [x]  Publish alert (Megan)
- [x]  Publish Tagalog PACT page and alert (Megan)

We'll then need to remove the alert when we update the page with the most recent translation.

**Comment by ABeltran77** [comment]
Alert added.

**Comment by megzehn** [comment]
Reviewed and published page with the alert. Thanks, Ana!
