### ISSUE TITLE
VFS Product Directory CR 404

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#61245]
### Description

I'm trying to submit change requests for the VFS Product Directory and the form links 404.

### Relevant URLs

[https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory-user-guide](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory-user-guide)

[https://github.com/department-of-veterans-affairs/product-directory/issues/new?assignees=cbonade&labels=&template=update-product-request.yml&title=Product+Directory+Change+Request+for+%5BProduct+Name%5D](https://github.com/department-of-veterans-affairs/product-directory/issues/new?assignees=cbonade&labels=&template=update-product-request.yml&title=Product+Directory+Change+Request+for+%5BProduct+Name%5D)

https://github.com/department-of-veterans-affairs/product-directory/issues/new?assignees=pjhill%2Cjoetice&labels=&template=update-restricted-attribute.yml&title=Restricted+Attribute+Update+Request+for+%5BProduct+Name%5D

### Which type of team are you on? (Platform team, VFS team, or Leadership)

VFS team - Appointments and MHV on VA.gov

**Comment by vbellissimo** [comment]
@laurenernest Thank you for submitting this request. We're taking a look for next steps.

**Comment by vbellissimo** [comment]
@laurenernest , actually can you please send me a screenshot of the hyperlink sending you to a 404 page? I'm having trouble replicating. They are seem to work fine for me.

**Comment by laurenernest** [comment]
I may not have access to that repo then :( How best can I submit change requests in that case?

![](https://github.com/department-of-veterans-affairs/va.gov-team/assets/72046525/66b9e979-c275-48ec-8b69-f4a1418e8588)

**Comment by vbellissimo** [comment]
@laurenernest Hmmmm, that does seem to be the case. If you need to request access to a specific repo, I am not sure what that looks like. You can try going to the greater Platform support team by submitting a support request via [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1).

**Comment by vbellissimo** [comment]
Hi @laurenernest , I'm going to close this ticket since you opened/created [this request](https://dsva.slack.com/archives/CBU0KDSB1/p1688655648405549) on the Platform Support Slack channel. If you have any other questions regarding repo access or how to update content _specifically for the VFS Product List_, please continue through the Slack channel. Thank you.
