### ISSUE TITLE
Profile | EVSS>LH | Direct Deposit C&P | Failed TestCase 6

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#61252]
## Background

[Test case 6](https://docs.google.com/spreadsheets/d/1xflLNJhUSVslzLbVQtMkYkzsBGAhIccnmYW0GL_Ihd0/edit#gid=0&range=A8)
LOA3 user: User is eligible for direct deposit for comp & pen, but has not set it up yet. They should see the direct deposit section of the profile, but they should see a prompt under the comp & pen section to add bank information.

Correct message on screen should allow the user to edit:
> Disability compensation and pension benefits
> Account
> Edit your profile to add your bank information.
> Edit

### **USER 80:** 
data prep issue, but results a semi-pass EVSS and LH are matching 

- EVSS https://staging-api.va.gov/v0/ppiu/payment_informationuser 80 has direct deposit info

- LH https://staging-api.va.gov/v0/profile/direct_deposits/disability_compensations
user 80 has same direct deposit info 

### **USER 82** 
- EVSS > no account info > correct message  = PASS

> Disability compensation and pension benefits
> Account
> Edit your profile to add your bank information.
> Edit

```
{
    "data": {
        "id": "",
        "type": "evss_ppiu_payment_information_responses",
        "attributes": {
            "responses": [
                {
                    "controlInformation": {
                        "canUpdateAddress": true,
                        "corpAvailIndicator": true,
                        "corpRecFoundIndicator": true,
                        "hasNoBdnPaymentsIndicator": true,
                        "identityIndicator": true,
                        "isCompetentIndicator": true,
                        "indexIndicator": true,
                        "noFiduciaryAssignedIndicator": true,
                        "notDeceasedIndicator": true
                    },
                    "paymentAccount": {
                        "accountType": "",
                        "financialInstitutionName": null,
                        "accountNumber": "",
                        "financialInstitutionRoutingNumber": ""
                    },
                    "paymentAddress": {
                        "type": "DOMESTIC",
                        "addressEffectiveDate": "2016-12-16T06:00:00.000+00:00",
                        "addressOne": "212 WEST LN",
                        "addressTwo": "",
                        "addressThree": "",
                        "city": "CLEVELAND",
                        "stateCode": "OH",
                        "zipCode": null,
                        "zipSuffix": null,
                        "countryName": "CLEVELAND",
                        "militaryPostOfficeTypeCode": null,
                        "militaryStateCode": null
                    },
                    "paymentType": "CNP"
                }
            ]
        }
    }
}
```

-LH > FAIL

> "Disability compensation and pension benefits
> Our records show that you don’t receive VA disability compensation or pension payments.
> If you think this is an error, call us at 800-827-1000 (TTY: 711). We’re here Monday through Friday, 8:00 a.m. to 9:00 p.m. ET.
> Learn more about disability eligibility
> Learn more 

about VA pension eligibility"

```
{
    "data": {
        "id": "",
        "type": "hashes",
        "attributes": {
            "controlInformation": {
                "canUpdateDirectDeposit": true,
                "isCorpAvailable": true,
                "isCorpRecFound": true,
                "hasNoBdnPayments": true,
                "hasIndex": true,
                "isCompetent": true,
                "hasMailingAddress": true,
                "hasNoFiduciaryAssigned": true,
                "isNotDeceased": true,
                "hasPaymentAddress": true,
                "hasIdentity": true
            },
            "paymentAccount": {
                "name": null,
                "accountType": null,
                "accountNumber": null,
                "routingNumber": null
            }
        }
    }
}
```

### USER 230 
Stopped testing because of the errors above

**Comment by mtcA6** [comment]
@adamwhitlock1 any idea what's up here and why user 82 when requesting from EVSS displays correctly but from LH displays the wrong error message?

**Comment by adamwhitlock1** [comment]
I was able to get a fix deployed and checked with user 82. There is some weird stuff going on with their profile in general, like the personal info endpoint for that user is throwing a 400 error, and the contact info is generally missing except for the mobile phone number _but_ the check now works and shows that the user is eligible for direct deposit.

**Comment by mtcA6** [comment]
this looked good!
