### ISSUE TITLE
Adding Claire Crinion to DSVA Slack

### ISSUE THREAD

**Issue by vievemarg** [department-of-veterans-affairs/va.gov-team#61266]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

claire.crinion@va.gov needs to be added as a full member to #vha-es-modernization

Claire is a Senior Researcher on the VES Modernization UI/UX team. Thank you.

**Comment by lkoenigsberg** [comment]
Added to workspace
