### ISSUE TITLE
Adding Nick Cunningham to DSVA Slack

### ISSUE THREAD

**Issue by vievemarg** [department-of-veterans-affairs/va.gov-team#61265]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

nick.cunningham@va.gov needs to be added as a full member to #ves-portfolio-research

Nick is a Data Analyst on the VES Portfolio Research team. Thank you.

**Comment by lkoenigsberg** [comment]
Added to workspace
