### ISSUE TITLE
Midpoint Review - IA Feedback - Disability Benefits Experience Team 1, 21-526EZ, Toxic Exposure Page

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#61260]
## VFS actions
- [x] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [x] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [x] Close the ticket when all feedback has been addressed.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- **Must**: We discussed this during the Design Intent meeting, but Public Websites team is doing related work and building what they are calling a PACT Act "Wizard" that will be available for all Veterans (won't require authentication) that walks them through a series of questions to understand their eligibility. That team is handling questions and conditional logic a little differently than you are (though it is definitely in a very early stage). I wanted to [point you to their Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1686687282873/beba3bd2c148677a82aa5b5c59a4f550e82d98e1?invited=true&sender=uf94a77a19aaf687331c09367) to see what that looks like. Please work closely with CAIA - especially @DanielleThierryUSDSVA to coordinate your approaches. Aligning content and flow across both of these products will be important.

- **Must**: You touched on this during design intent, and I'll +1 this being a good idea: definitely include findability tasks in your user research sessions to better understand the language that Veterans naturally use around this topic. This may look like starting the session by asking participating Veterans how they would begin looking for toxic exposure coverage. Do they use a search engine and Google "toxic exposure" or another term? Do they come to Va.gov first? What words do they use? Try to avoid using our language and be ambiguous in the way you ask questions / see what words they come up with. Getting at their mental models and whether "toxic exposure" is well-understood is crucial. @rbsingleton can be helpful here with crafting research tasks around this while Shane is out. 
- **Must**: On the supporting evidence page, the terms "records," "documentation," and "evidence" are used interchangeably. Please review.

- **Should**: The additional info component with "List of Gulf War Hazard Locations" has a long list of countries/locations without a clear rationale for the order in which they appear. Please order them in a logical sequence. 
- **Should**: The supporting evidence page is long. It's a hard problem to solve for with so much to communicate to Veterans! But I'd strongly recommend breaking it up to make it easier to scan/digest - especially if you know there are usability issues around uploading evidence. Consider utilizing design components such as additional info and the accordion component.
    - In my reading, it seems like you at least answer these three questions that could maybe (?) fit nicely into an FAQ accordion structure: 1.) What documentation does VA already have about my conditions? 2.) What new documentation is useful to add in support of this new claim? 3.) What if I don't have any documentation to add?

- **Consider**: While we're seeing these pages sequentially in the sketch file, they do not appear sequentially for the Veteran in the overall 526 flow (some are in section 2: disabilities, others are in section 3: supporting evidence). When you do user research, consider asking Veterans to go through the full flow of pages that live between these sections to mimic the true user experience as much as possible.

**Comment by sterkenburgsara** [comment]
// cc @kristinoletmuskat @jennymayoco

**Comment by lydiahooper** [comment]
We are waiting for CAIA review (see epic for link to that ticket), and have notified them there are relevant items in this ticket. 

@Nyanteea will add 2nd Must item listed here to research plan (also linked to in epic)

For the consider item, note that the missing pages in the prototyped flow (POW and Additional Benefits pages) are pages we are planning to move/remove in upcoming features so that's why we decided not to include them.

**Comment by RakshindaAslam** [comment]
cc @RakshindaAslam - add estimate after meeting with Shannon and Julie

**Comment by shannonkford** [comment]
Providing an updated response to the feedback:

**Must**: We discussed this during the Design Intent meeting, but Public Websites team is doing related work and building what they are calling a PACT Act "Wizard" that will be available for all Veterans (won't require authentication) that walks them through a series of questions to understand their eligibility. That team is handling questions and conditional logic a little differently than you are (though it is definitely in a very early stage). I wanted to point you to their Mural to see what that looks like. Please work closely with CAIA - especially @DanielleThierryUSDSVA to coordinate your approaches. Aligning content and flow across both of these products will be important.

**Response**
The CAIA team provided detailed feedback and rewrites to conform to the PACT wizard approach. We discussed a few instances where toxic exposure needed to be more broadly based than PACT presumptives and made those changes together where needed.

**Must**: You touched on this during design intent, and I'll +1 this being a good idea: definitely include findability tasks in your user research sessions to better understand the language that Veterans naturally use around this topic. This may look like starting the session by asking participating Veterans how they would begin looking for toxic exposure coverage. Do they use a search engine and Google "toxic exposure" or another term? Do they come to Va.gov first? What words do they use? Try to avoid using our language and be ambiguous in the way you ask questions / see what words they come up with. Getting at their mental models and whether "toxic exposure" is well-understood is crucial. @rbsingleton can be helpful here with crafting research tasks around this while Shane is out.

**Response**
Findability is likely out of scope for the research, though we can address basic comprehension of the term toxic exposure in context of the pages. Working on the plan this week.

**Must**: On the supporting evidence page, the terms "records," "documentation," and "evidence" are used interchangeably. Please review.

**Response**
Content changes to this and other Step 2/Step 3 screens that were in the test prototype are out of scope, but subject to an upcoming content audit and subsequent clarification and implementation. We will address your feedback at that time.

**Should**: The additional info component with "List of Gulf War Hazard Locations" has a long list of countries/locations without a clear rationale for the order in which they appear. Please order them in a logical sequence.

**Response**
Now in alpha order

**Should**: The supporting evidence page is long. It's a hard problem to solve for with so much to communicate to Veterans! But I'd strongly recommend breaking it up to make it easier to scan/digest - especially if you know there are usability issues around uploading evidence. Consider utilizing design components such as additional info and the accordion component.

In my reading, it seems like you at least answer these three questions that could maybe (?) fit nicely into an FAQ accordion structure: 1.) What documentation does VA already have about my conditions? 2.) What new documentation is useful to add in support of this new claim? 3.) What if I don't have any documentation to add?

**Response**
Making changes to this page is now out of scope, but we will return to this feedback when we take this page up again.

**Consider**: While we're seeing these pages sequentially in the sketch file, they do not appear sequentially for the Veteran in the overall 526 flow (some are in section 2: disabilities, others are in section 3: supporting evidence). When you do user research, consider asking Veterans to go through the full flow of pages that live between these sections to mimic the true user experience as much as possible.

**Response**
Agreed, though we will likely not be going through the whole process this round of research. See Lydia's response above as well for some missing screens

**Comment by lydiahooper** [comment]
Closing per Shannon's previous comments
