### ISSUE TITLE
Adding Rob Dalton to DSVA Slack

### ISSUE THREAD

**Issue by huggins-va** [department-of-veterans-affairs/va.gov-team#61283]
Please add Robert Dalton (rob.dalton@oddball.io) as multi-channel user to: vaapi-platform and team-quokka 

Robert Dalton is onboarding to Lighthouse program (team Quokka) on 7/3/2023 as a Software Engineer. 

Thank you!

**Comment by lkoenigsberg** [comment]
Added as a member of the workspace.
