### ISSUE TITLE
Update the breadcrumb for the direct schedule workflow (MHV on VA.gov) 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#61284]
## Description
The Appointments application will be under the MHV on VA.gov portal. We will need to update the breadcrumb structure. #61284 will focus on the direct schedule workflow in the appointments application. 

---

## Acceptance Criteria
Background: the `va_online_scheduling_breadcrumb_url_update` toggle is on

Given the user is on `Upcoming VA appointments` landing page, 
And the user clicks on `Start Scheduling` button and lands on the,  

- [x] Choose the type of care page you need page, then breadcrumb will be `VA.gov home > My HealtheVet > Appointments > [Page Header]`
- [x] Choose a VA location page, then breadcrumb will be `VA.gov home > My HealtheVet > Appointments > [Page Header]`
- [x] How to schedule page, then breadcrumb will be `VA.gov home > My HealtheVet > Appointments > [Page Header]`
- [x] Choose a clinic page, then breadcrumb will be `VA.gov home > My HealtheVet > Appointments > [Page Header]`
- [x] When do you want to schedule this appointment page, then breadcrumb will be `VA.gov home > My HealtheVet > Appointments > [Page Header]`
- [x] Choose a date and time page, then breadcrumb will be `VA.gov home > My HealtheVet > Appointments > [Page Header]`
- [x] Choose a reason for this appointment, then breadcrumb will be `VA.gov home > My HealtheVet > Appointments > [Page Header]`
- [x] Confirm your contact information, then breadcrumb will be `VA.gov home > My HealtheVet > Appointments > [Page Header]`
- [x] Review your appointment details page,  then breadcrumb will be `VA.gov home > My HealtheVet > Appointments > [Page Header]`

---

- [x]  Given the user is on `Upcoming VA appointments` landing page, 
        And the user clicks on `Start Scheduling` button and lands on the
        Choose a sleep care page, then breadcrumbs will be `VA.gov home > My HealtheVet > Appointments > [Page Header]`
       And page matches [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/schedule-all-flows.md#choose-sleep-care)

- [x]  Given the user is on `Upcoming VA appointments` landing page, 
        And the user clicks on `Start Scheduling` button and lands on the
        Choose an eye care page, then breadcrumbs will be `VA.gov home > My HealtheVet > Appointments > [Page Header]`
        And page matches [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/schedule-all-flows.md#choose-eye-care)

- [x]  Given the user is on `Upcoming VA appointments` landing page, 
        And the user clicks on `Start Scheduling` button and lands on the
        Choose an audiology page, then breadcrumbs will be `VA.gov home > My HealtheVet > Appointments > [Page Header]`
        And page matches [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/schedule-all-flows.md#choose-audiology-care)

### Reference
[Copy doc - all scheduling flows](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/schedule-all-flows.md#scheduling---all-flows)
[Copy doc - VA direct schedule flow](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/schedule-va.md)
[Spike ticket #54757](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/54757)

### Design Assets
[Title tag format guidance](https://design.va.gov/content-style-guide/seo#title-tags)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by ldelacosta** [comment]
@young1205 - please have the UX team validate this ticket when it's ready cc: @JRRoof @outerpress

**Comment by ldelacosta** [comment]
Validated the work in staging for judy.morrison@id.me and patient999@id.me. Notified the UX team to review the changes.

**Comment by outerpress** [comment]
@ldelacosta @young1205 Reviewed, looks great!

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket.
