### ISSUE TITLE
Update the URL and title page for the direct schedule flow (MHV on VA.gov) 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#61280]
## Description
The Appointments application will be under the MHV on VA.gov portal. We will need to update the title page and URL structure. #61280 will focus on the direct schedule workflow in the appointments application. 

---

## Acceptance Criteria
Background: the `va_online_scheduling_breadcrumb_url_update` toggle is on

Given the user is on `Upcoming VA appointments` landing page, 
And the user clicks on `Start Scheduling` button and lands on the,  

- [ ] Choose the type of care page you need page, then URL will display https://va.gov/my-health/appointments/schedule/type-of-care
- [ ] Choose a VA location page, then URL will display https://va.gov/my-health/appointments/schedule/location
- [ ] How to schedule page, then URL will display https://va.gov/my-health/appointments/schedule/how-to-schedule
- [ ] Choose a VA clinic page, then URL will display https://va.gov/my-health/appointments/schedule/clinic
- [ ] When do you want to schedule this appointment page, then URL will display https://va.gov/my-health/appointments/schedule/preferred-date
- [ ] Choose a date and time page, then URL will display https://va.gov/my-health/appointments/schedule/date-time
- [ ] Choose a reason for this appointment, then URL will display https://va.gov/my-health/appointments/schedule/reason
- [ ] Confirm your contact information, then URL will display https://va.gov/my-health/appointments/schedule/contact-information
- [ ] Review your appointment details page, then URL will display https://va.gov/my-health/appointments/schedule/review

---

Given the user is on `Upcoming VA appointments` landing page, 
And the user clicks on `Start Scheduling` button and lands on the,  

- [ ] Choose the type of care page you need page, then page title will be `[Page Header] | Veterans Affairs`
- [ ] Choose a VA location page,  then page title will be `[Page Header] | Veterans Affairs`
- [ ] How to schedule page, then page title will be `[Page Header] | Veterans Affairs`
- [ ] Choose a clinic page, then page title will be `[Page Header] | Veterans Affairs`
- [ ] When do you want to schedule this appointment page, then page title will be `[Page Header] | Veterans Affairs`
- [ ] Choose a date and time page, then page title will be `[Page Header] | Veterans Affairs`
- [ ] Choose a reason for this appointment, then page title will be `[Page Header] | Veterans Affairs`
- [ ] Confirm your contact information, then page title will be `[Page Header] | Veterans Affairs`
- [ ] Review your appointment details page,  then page title will be `[Page Header] | Veterans Affairs`

---

- [ ]  Given the user is on `Upcoming VA appointments` landing page, 
        And the user clicks on `Start Scheduling` button and lands on the
        Choose the type of sleep care you need page, then URL will display https://va.gov/my-health/appointments/schedule/sleep-care and page title 
        will be `[Page Header] | Veterans Affairs`
       And page matches [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/schedule-all-flows.md#choose-sleep-care)

- [ ]  Given the user is on `Upcoming VA appointments` landing page, 
        And the user clicks on `Start Scheduling` button and lands on the
        Choose the type of eye care you need page, then URL will display https://va.gov/my-health/appointments/schedule/eye-care and page title 
        will be `[Page Header] | Veterans Affairs`
        And page matches [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/schedule-all-flows.md#choose-eye-care)

- [ ]  Given the user is on `Upcoming VA appointments` landing page, 
        And the user clicks on `Start Scheduling` button and lands on the
        Choose the type of audiology care you need page, then URL will display  https://va.gov/my-health/appointments/schedule/audiology-care and page title 
        will be `[Page Header] | Veterans Affairs`
        And page matches [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/schedule-all-flows.md#choose-audiology-care)

### Reference
[Copy doc - all scheduling flows](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/schedule-all-flows.md#scheduling---all-flows)
[Copy doc - VA direct schedule flow](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/schedule-va.md)
[Spike ticket #54757](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/54757)

### Design Assets
[Title tag format guidance](https://design.va.gov/content-style-guide/seo#title-tags)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by JRRoof** [comment]
Validated - Live in Production
