### ISSUE TITLE
Update the URL and title page for the VA request flow (MHV on VA.gov) 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#61287]
## Description
The Appointments application will be under the MHV on VA.gov portal. We will need to update the title page and URL structure. #61287 will focus on the VA request workflow in the appointments application. 

---

## Acceptance Criteria
Background: the `va_online_scheduling_breadcrumb_url_update` toggle is on

Given the user is on `Upcoming VA appointments` landing page, 
And the user clicks on `Start Scheduling` button and lands on the,  

- [x] Choose the type of care page you need page, then URL will display https://va.gov/my-health/appointments/schedule/type-of-care
- [ ] Choose where you want to receive your care page, then URL will display https://va.gov/my-health/appointments/schedule/facility-type
- [x] Choose a VA location page, then URL will display URL: https://va.gov/my-health/appointments/schedule/location
- [x] Choose an appointment date and time page, then URL will display https://va.gov/my-health/appointments/schedule/va-request
- [x] Choose a reason for this appointment, then URL will display https://va.gov/my-health/appointments/schedule/va-request/reason
- [x] Choose a type of appointment, then URL will display https://va.gov/my-health/appointments/schedule/va-request/preferred-method
- [x] Confirm your contact information page, then URL will display https://va.gov/my-health/appointments/schedule/va-request/contact-information
- [x] Review your appointment details page, then URL will display https://va.gov/my-health/appointments/schedule/va-request/review

Given the user is on `Upcoming VA appointments` landing page, 
And the user clicks on `Start Scheduling` button and lands on the,  

- [x] Choose the type of care page you need page, then page title will be `[Page Header] | Veterans Affairs`
- [x] Choose where you want to receive your care page, then page title will be `[Page Header] | Veterans Affairs` 
- [x] Choose an appointment date and time page, then page title will be `[Page Header] | Veterans Affairs`
- [x] Choose a reason for this appointment, then page title will be `[Page Header] | Veterans Affairs`
- [x] Choose a type of appointment, then page title will be `[Page Header] | Veterans Affairs`
- [x] Confirm your contact information page, then page title will be `[Page Header] | Veterans Affairs`
- [x] Review your appointment details page, then page title will be `[Page Header] | Veterans Affairs`

### Reference
[Copy doc - all scheduling flows](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/schedule-all-flows.md#scheduling---all-flows)
[Copy doc - VA request flow](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/request-va.md)
[Spike ticket #54757](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/54757)

### Design Assets
[Title tag format guidance](https://design.va.gov/content-style-guide/seo#title-tags)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by ldelacosta** [comment]
@young1205 - please have the UX team validate this ticket when it's ready cc: @JRRoof @outerpress

**Comment by ldelacosta** [comment]
Validated the ticket in staging for judy.morrison@id.me. Notified the UX team to review the changes. cc: @young1205

**Comment by Cieramaddox** [comment]
This has been validated by UX
