### ISSUE TITLE
MVP database

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#61298]
### PROBLEM STATEMENT
An MVP script to pull code from vets-api has been created, and run. Once we have _what_ code in in `vets-api` we need a drafted way to store and organize both the code and the information we need associated to the code.

### ACTIONS
- [x] Create draft list of information we need to know about code and include in database (crew, associated slack channel, code owner not know, etc)
- [x] Create draft of database to store code and info to associate with code

### DEFINITION OF DONE
- [x] MVP of database is complete and readable by all of TT1

**Comment by LindseySaari** [comment]
We should also decide on where we plan to store this information. I know we discussed to possibly piggy back off of Vets API or create a separate app/database?

**Comment by laineymajor** [comment]
Build Tables:
VfsTeam: id, name, slack_channel_id, github_team_id, vsa_team_id (maybe)
VsaTeam: id, name, slack_channel, Github team name
GithubTeam table: id, name
SlackChannel table: id, name
File: id, file_name, vfs_team_id

**Comment by laineymajor** [comment]
Documentation from Lindsey (where we are MVPing the info)
https://docs.google.com/spreadsheets/d/1Nvd738_-y0RrTPqDVAtI8mFcaPepRiy8fe026q20c1c/edit#gid=0

**Comment by laineymajor** [comment]
NEXT STEPS
- define VFS github team name that's associated to a vfs team name, slack channel (github team name is what can be mapped to codeowners)
- determine a way to refresh the product directory json (add slack channels, etc) --- Eric working on a way to manage this
- [Lainey's list from OCTO and team of teams](https://docs.google.com/spreadsheets/d/1zRKiiIaZNiUQz3FC69xy1A7HUU2zRBPmZSYYNuDsFQ4/edit#gid=0)

**Comment by laineymajor** [comment]
[Link to canvas with all of our documents we are working from and on...](https://adhoc.slack.com/docs/T025UGMV9/F05GR0GR5NW)

**Comment by laineymajor** [comment]
Updates/Next Steps:
- LH looked at GH handles with the VFS roster info; creating a script to generate the teams that do NOT exist. Putting all this info in [the roster. ](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2444951) ---- LT to communicate with Shira that the roster is being updated :) 
- Eric to reseed the database once Lindsey is complete with above info
- Lainey to check with teams that have missing gh handles for IC; add info as received to roster
- Lainey to check with Chelen about deactivated users OR check the offboarding requests to determine who is no longer active
- MVP database design. 90% good for the schema. Would like to add codeownership present within codeownership file.
- Ryan: Initializers, serializers, specs in the spreadsheet ([lib directory](https://docs.google.com/spreadsheets/d/1Nvd738_-y0RrTPqDVAtI8mFcaPepRiy8fe026q20c1c/edit#gid=360924264)).... look into this info and run scripts to id authors 
- Ryan: As assigning teams, make sure the GH team name in the [roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2444951)
- Lainey to complete matching of [GH team name, IC, and IC gh handle](https://docs.google.com/spreadsheets/d/1zRKiiIaZNiUQz3FC69xy1A7HUU2zRBPmZSYYNuDsFQ4/edit#gid=1367716793)

Q:
- did we determine a process for unknown = this will be assigned to platform
