### ISSUE TITLE
Update the URL and title page for the Community Care request flow (MHV on VA.gov) 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#61291]
## Description
The Appointments application will be under the MHV on VA.gov portal. We will need to update the title page and URL structure. #61291 will focus on the Community Care request workflow in the appointments application. 

---

## Acceptance Criteria
Background: the `va_online_scheduling_breadcrumb_url_update` toggle is on

(Type of care to test: Podiatry) 
Given the user is on `Upcoming VA appointments` landing page, 
And the user clicks on `Start Scheduling` button and lands on the,  

- [x] Choose the type of care you need page, then URL will display https://va.gov/my-health/appointments/schedule/type-of-care
- [x] Choose an appointment day and time page, then URL will display https://va.gov/my-health/appointments/schedule/community-request
- [x] What’s the closest city to you page, then URL will display https://va.gov/my-health/appointments/schedule/community-request/closest-city
- [x] Request a provider page, then URL will display https://va.gov/my-health/appointments/schedule/community-request/preferred-provider
- [x] Choose a preferred language page, then URL will displayhttps://va.gov/my-health/appointments/schedule/community-request/preferred-language
- [x] Tell us the reason for this appointment page, then URL will display https://va.gov/my-health/appointments/schedule/community-request/reason
- [x] Confirm your contact information page, then URL will display https://va.gov/my-health/appointments/schedule/community-request/contact-information
- [x] Review your appointment details page, then URL will display https://va.gov/my-health/appointments/schedule/community-request/review

---

(Type of care to test: Audiology) 
- [x] Choose the type of care you need page, then URL will display https://va.gov/my-health/appointments/schedule/type-of-care
- [x] Choose where you want to receive your care page, then URL will display https://va.gov/my-health/appointments/schedule/location
- [x] Choose the type of audiology care you need page, then URL will display https://va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/audiology
- [x] Choose an appointment day and time page, then URL will display https://va.gov/my-health/appointments/schedule/va-request
- [x] What’s the closest city to you page, then URL will display https://va.gov/my-health/appointments/schedule/community-request/closest-city
- [x] Request a provider page, then URL will display https://va.gov/my-health/appointments/schedule/preferred-provider-cc-request
- [x] Choose a preferred language page, then URL will display https://va.gov/my-health/appointments/schedule/community-request/preferred-language
- [x] Tell us the reason for this appointment page, then URL will display https://va.gov/my-health/appointments/schedule/community-request/reason
- [x] Confirm your contact information page, then URL will display https://va.gov/my-health/appointments/schedule/community-request/contact-information
- [x] Review your appointment details page, then URL will display  https://va.gov/my-health/appointments/schedule/community-request/review

--- 

(Type of care to test: Podiatry) 
Given the user is on `Upcoming VA appointments` landing page, 
And the user clicks on `Start Scheduling` button and lands on the,  

- [x] Choose the type of care you need page, then page title will be `[Page Header] | Veterans Affairs`
- [x] Choose an appointment day and time page, then page title will be `[Page Header] | Veterans Affairs`
- [x] What’s the closest city to you page, then page title will be `[Page Header] | Veterans Affairs`
- [x] Request a provider page, then page title will be `[Page Header] | Veterans Affairs`
- [x] Choose a preferred language page, then page title will be `[Page Header] | Veterans Affairs`
- [x] Tell us the reason for this appointment page, then page title will be `[Page Header] | Veterans Affairs`
- [x] Confirm your contact information page, then page title will be `[Page Header] | Veterans Affairs`
- [x] Review your appointment details page, then page title will be `[Page Header] | Veterans Affairs`

--- 

Given the user is on `Upcoming VA appointments` landing page, 
And the user clicks on `Start Scheduling` button and lands on the,  

(Type of care to test: Audiology) 
- [x] Choose the type of care you need page, then page title will be `[Page Header] | Veterans Affairs`
- [x] Choose where you want to receive your care page, then page title will be `[Page Header] | Veterans Affairs`
- [x] Choose the type of [type of care] care you need page, then page title will be `[Page Header] | Veterans Affairs` 
- [x] Choose an appointment day and time page, then page title will be `[Page Header] | Veterans Affairs`
- [x] What’s the closest city to you page, then page title will be `[Page Header] | Veterans Affairs`
- [x] Request a provider page, then page title will be `[Page Header] | Veterans Affairs`
- [x] Choose a preferred language page, then page title will be `[Page Header] | Veterans Affairs`
- [x] Tell us the reason for this appointment page, then page title will be `[Page Header] | Veterans Affairs`
- [x] Confirm your contact information page, then page title will be `[Page Header] | Veterans Affairs`
- [x] Review your appointment details page, then page title will be `[Page Header] | Veterans Affairs`

---

### Reference
[Copy doc - all scheduling flow](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/schedule-all-flows.md#scheduling---all-flows)
[Copy doc - CC request flow](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/request-cc.md)
[Spike ticket #54757](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/54757)

### Design Assets
[Title tag format guidance](https://design.va.gov/content-style-guide/seo#title-tags)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by ldelacosta** [comment]
@young1205 - please have the UX team validate this ticket when it's ready cc: @JRRoof @outerpress

**Comment by ryanshaw** [comment]
Noticed some things that might have been wrong in this issue's description:

- The facility type URL is incorrectly noted in the description for audiology appointments (as `schedule/location/`). It should be [`schedule/facility-type`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/schedule-all-flows.md#choose-va-or-cc-facility)
- The audiology type of care URL is incorrectly noted in the description for audiology appointments (as `new-appointment/audiology`). It should be [`schedule/audiology-care`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/schedule-all-flows.md#choose-audiology-care)
- The audiology choose a preferred date and time URL is incorrectly noted in the description for audiology appointments (as `schedule/va-request`). It should be [`schedule/community-request`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/request-cc.md#preferred-date)
- The audiology choose a preferred provider URL is incorrectly noted in the description for audiiology appointments (as `schedule/preferred-provider-cc-request`). It should be [`community-request/preferred-provider`](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/request-cc.md#request-a-provider-optional)

**Comment by ldelacosta** [comment]
I believe this work is done. Could you confirm and I'll close out the ticket. @ryanshaw

**Comment by ryanshaw** [comment]
@ldelacosta Yes, it was completed with [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/25957) that's been merged in

**Comment by ldelacosta** [comment]
Ticket work is done. Closing out the ticket.
