### ISSUE TITLE
Update the breadcrumb for the Community Care request workflow (MHV on VA.gov) 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#61292]
## Description
The Appointments application will be under the MHV on VA.gov portal. We will need to update the breadcrumb structure. #61292 will focus on the Community Care request workflow in the appointments application. 

---

## Acceptance Criteria
Background: the `va_online_scheduling_breadcrumb_url_update` toggle is on

(Type of care to test: Podiatry) 
Given the user is on `Upcoming VA appointments` landing page, 
And the user clicks on `Start Scheduling` button and lands on the,  

- [x] Choose the type of care you need page, then breadcrumb will be `VA.gov home > My HealtheVet > Appointments > [Page Header]`
- [x] Choose an appointment day and time page, then breadcrumb will be `VA.gov home > My HealtheVet > Appointments > [Page Header]`
- [x] What’s the closest city to you page, then breadcrumb will be `VA.gov home > My HealtheVet > Appointments > [Page Header]`
- [x] Request a provider page, then breadcrumb will be `VA.gov home > My HealtheVet > Appointments > [Page Header]`
- [x] Choose a preferred language page, then breadcrumb will be `VA.gov home > My HealtheVet > Appointments > [Page Header]`
- [x] Tell us the reason for this appointment page, then breadcrumb will be `VA.gov home > My HealtheVet > Appointments > [Page Header]`
- [x] Confirm your contact information page, then breadcrumb will be `VA.gov home > My HealtheVet > Appointments > [Page Header]`
- [x] Review your appointment details page, then breadcrumb will be `VA.gov home > My HealtheVet > Appointments > [Page Header]`

---

(Type of care to test: Audiology) 
- [x] Choose the type of care you need page, then breadcrumb will be `VA.gov home > My HealtheVet > Appointments > [Page Header]`
- [x] Choose where you want to receive your care page, then breadcrumb will be `VA.gov home > My HealtheVet > Appointments > [Page Header]`
- [x] Choose the type of [type of care] care you need page, then breadcrumb will be `VA.gov home > My HealtheVet > Appointments > [Page Header]`
- [x] Choose an appointment day and time page, then breadcrumb will be `VA.gov home > My HealtheVet > Appointments > [Page Header]`
- [x] What’s the closest city to you page, then breadcrumb will be `VA.gov home > My HealtheVet > Appointments > [Page Header]`
- [x] Request a provider page, then breadcrumb will be `VA.gov home > My HealtheVet > Appointments > [Page Header]`
- [x] Choose a preferred language page, then breadcrumb will be `VA.gov home > My HealtheVet > Appointments > [Page Header]`
- [x] Tell us the reason for this appointment page, then breadcrumb will be `VA.gov home > My HealtheVet > Appointments > [Page Header]`
- [x] Confirm your contact information page, then breadcrumb will be `VA.gov home > My HealtheVet > Appointments > [Page Header]`
- [x] Review your appointment details page, then breadcrumb will be `VA.gov home > My HealtheVet > Appointments > [Page Header]`
--- 

### Reference
[Copy doc - all scheduling flow](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/schedule-all-flows.md#scheduling---all-flows)
[Copy doc - CC request flow](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/request-cc.md)
[Spike ticket #54757](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/54757)

### Design Assets
[Title tag format guidance](https://design.va.gov/content-style-guide/seo#title-tags)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by ldelacosta** [comment]
Validated the ticket in staging for judy.morrison@id.me. Notified the UX team to review the changes in staging.

**Comment by Cieramaddox** [comment]
@young1205 This ticket has been reviewed and validated by the UX team.
