### ISSUE TITLE
[Spike] Display Clinic Location on the Appointment details page 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#61295]
## Request
The Appointments team is looking to add the Clinic location on the Appointment details page. We need to do technical research if the data is available in vaos-v2 service. 

FE ticket for the work: [#32593](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/32593)

### Goal
Be able to add the clinic location on the appointments details page 

### Requirements to Consider
- [ ] Be able to fetch `physicalLocation` in order to display the Clinic location to the user 

---

## Tasks
- Answer the following questions:
  - Q1. What endpoint can we get `physicalLocation` from?
  - Q2. Do we have to make an additional call to this endpoint to display this field in the appointment details? if yes, do you advice we handle this on the api/ FE layer?

## Time Box
4 hours vets-website 
4 hours vets-api

## Definition of Done
- Tasks are complete
- Research and recommendations are documented in this ticket

---

**Comment by ldelacosta** [comment]
This would require frontend and backend developers to research

**Comment by ajmagdub** [comment]
@ldelacosta here's the backend discovery

Currently, the Vets API makes a call to the VAOS Service endpoint **/vaos/v1/locations/\<station_id\>/clinics?clinicIds=\<ids\>**
to retrieve clinic information. The information includes the physical location of the clinics, which is returned in
the appointment.physicalLocation field. Here are some examples of the clinic's physical location values in the staging
environment:

    physicalLocation: BLDG 310, ROOM 9, 
     physicalLocation: CHEYENNE,
     physicalLocation: FORT COLLINS AUDIO,
     physicalLocation: MHC,
     physicalLocation: PATIENT TOWER, 2ND FLOOR,
     physicalLocation: SIDNEY CLINIC,
     physicalLocation: WHEATLAND,
     physicalLocation: prob,

**Comment by ldelacosta** [comment]
FE developer will work on the spike. @simiadebowale 
Moving back to the ready queue.

**Comment by ldelacosta** [comment]
@young1205 - Please notify @JRRoof when the ticket is done.

**Comment by ldelacosta** [comment]
We have completed the work #69444 (https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/69444). Closing out this spike ticket.
