### ISSUE TITLE
Cerner Re-direct on the Appointments homepage 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#61301]
## Description
We are looking to improve the Cerner re-direct in the appointments application. Our goal is to provide easier access to direct the user back to Cerner if needed. 

##
Dev Notes:
Logic for getting cerner sites:
We can call `getVamcSystemNameFromVhaId`: [https://github.com/department-of-veterans-affairs/vets-website/blob/a5d53c37ac6126[…]orm/site-wide/drupal-static-data/source-files/vamc-ehr/utils.js](https://github.com/department-of-veterans-affairs/vets-website/blob/a5d53c37ac6126b8facfe8217eeeb3b7603db2ae/src/platform/site-wide/drupal-static-data/source-files/vamc-ehr/utils.js#L6-L8)

That function requires that you pass in the data, though, so you need to grab that from the global state first: [https://github.com/department-of-veterans-affairs/vets-website/blob/a5d53c37ac6126[…]ide/drupal-static-data/source-files/vamc-ehr/selectors/index.js](https://github.com/department-of-veterans-affairs/vets-website/blob/a5d53c37ac6126b8facfe8217eeeb3b7603db2ae/src/platform/site-wide/drupal-static-data/source-files/vamc-ehr/selectors/index.js#L6-L7)

---

## Acceptance Criteria

- [ ] Given the user is registered at a Cerner site(s)
       When the user is authenticated to use the Appointments application 
       Then the user will land on the Appointments landing page and will see the Cerner alert message 
       And page matches the [design spec](https://www.figma.com/file/iqjkZx2EbrZu6leL6YfN45/Cerner-Handoff?type=design&node-id=13-33&mode=design&t=81aSZDSCbbtNbSEE-0)

### Design Assets
Mobile example: 
<img width="235" alt="Screenshot 2023-07-03 at 10 53 35 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/90797205/2d46a92a-66d5-4034-a1c3-20bb3129f877">

[Design spec](https://www.figma.com/file/iqjkZx2EbrZu6leL6YfN45/Cerner-Handoff?type=design&node-id=13-33&mode=design&t=81aSZDSCbbtNbSEE-0)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by ldelacosta** [comment]
@vbahinwillit - could we implement the event tracker [ticket](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/62997) before merging the changes into production. We do not have a feature toggle for this work. cc: @simiadebowale

**Comment by vbahinwillit** [comment]
Just an fyi,

The event, 'nav-alert-box-link-click' is sent each time a button is clicked as well:

```
alert-box-backgroundOnly: true
alert-box-clickLabel: "Go to My VA Health"
alert-box-closeable: false
alert-box-headline: "To manage appointments at these facilities, go to My VA Health"
alert-box-status: "warning"
component-library-version: undefined
event: "nav-alert-box-link-click"
event-source: "component-library"
```

**Comment by ldelacosta** [comment]
@vbahinwillit - I validated the changes in staging for two users judy.morrison@id.me and ssoissoetesting+mhvcss3@gmail.com. 

For judy.morrison@id.me, it looks to be working as expected. I have asked the designers to check on the layout. 
![Screenshot 2023-08-08 at 6.47.41 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/499270d0-1f41-4cb7-80fc-0757ea250f42)

For ssoissoetesting+mhvcss3@gmail.com who is registered at two Cerner sites Spokane and Central Ohio (looking at the Public Website widget to confirm), the changes are not being displayed on the Appointments landing page. The user does not have any upcoming appointments but I am unsure if that's why it's not being displayed. Could you please advise? 

**Public Website Widget:** 
![Screenshot 2023-08-08 at 6.59.37 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/069c222d-d34c-4f53-b937-3e7508546a3e)

**Appointments Landing Page**![Screenshot 2023-08-08 at 7.04.22 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/26c5e94e-bcc3-4ea4-bc82-64e7eb0c4e3b)

**Comment by ldelacosta** [comment]
Moving the ticket back to In Progress. Please remove the feature toggle for the work. @vbahinwillit 

@outerpress - please add your comments when you have a chance. Thanks.

**Comment by outerpress** [comment]
A couple of notes @vbahinwillit :
* I checked around and the link to My VA Health should open in a new tab (other Cerner links follow the same pattern)
* We talked about this in standup but just to note here there's extra padding at the bottom of the widget that sounds like it's related to the shadow dom. LMK if you figure out any options for addressing this. I'll follow up here after I review it with Kristen.

**Comment by melissa-lefevre** [comment]
Update: The extra padding is still there. I asked in [this thread](https://dsva.slack.com/archives/CBU0KDSB1/p1691699542594149) if the new version has been shipped yet.

**Comment by melissa-lefevre** [comment]
Update: the padding is correct now. [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcFVaIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--786e6e156ec69881319dfda98a0e5b4c39676cb9/Screenshot%202023-08-18%20at%2010.24.15%20AM.png)

**Comment by ldelacosta** [comment]
Validated judy.morrison@id.me in staging. No issues to report. Closing out the ticket. cc: @JRRoof @outerpress 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ1FhIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ef97168956980c370e3de293e792f10cb2ba6e17/Screenshot%202023-08-18%20at%2011.30.57%20AM.png)
