### ISSUE TITLE
Update life insurance VBA form link and current rate tables

### ISSUE THREAD

**Issue by AnneHurley** [department-of-veterans-affairs/va.gov-team#6131]
## 1. Replace outdated link to application form on this page: https://www.va.gov/life-insurance/options-eligibility/tsgli/

Current link is to a 2015 form. This is a quick-fix solution for a longer term solution that will involve getting the Prudential Life Insurance updated forms to live in the VA Forms Database per @jenniferlee-dsva. For now we will update the link manually. 

2. Update the rates for SGLI here: https://www.va.gov/life-insurance/options-eligibility/sgli/

To include current rate numbers from Lori and Ruth. 

Anne to handle updates in Drupal as soon as we get the correct info.

**Comment by AnneHurley** [comment]
@RLHecht  or @peggygannon  The first of these tasks is ready. Link is: https://prod.cms.va.gov/node/768/edit

If one of you could review that the new PDF works (I did as well) and then push to publish that would be great.

Will have tables updated 2/25

**Comment by RLHecht** [comment]
@AnneHurley Which PDF on the page was updated? the second one (the TSGLI appeal form) takes me to a weird link. It's also not a PDF so I removed that after the link. But maybe that wasn't the one you updated?

**Comment by RLHecht** [comment]
@AnneHurley I reviewed the changes and published the page.

**Comment by AnneHurley** [comment]
@RLHecht  - thanks! Now the SGLI updated table rates page is ready for you. The rates all look right to me, but in preview I am now seeing a 5th column, with values of "0" all the way down the table. Can you see how this was introduced and let me know? And then it's otherwise ready for you to review and push live.

Also, attached is the word doc the VBA folks sent with the updated rates for the 2 types of insurance coverage.
[Updated Life Insurance rate tables as of 2019]
(https://app.zenhub.com/files/133843125/c2664ecb-a4bd-44aa-9b8b-1f9635445382/download)

**Comment by jenniferlee-dsva** [comment]
I don't need to review these. Please move forward with normal copy edit and proof reading steps. Please be sure to send Lori a preview link as FYSA before go-live.

**Comment by AnneHurley** [comment]
@RLHecht  FSGLI rates tables updated. Note that even when I logged out and back in again I am still seeing the extra "0" column. I will check back in a little while to see if this page and the ^ previous page have been fixed with that preview bug. 

http:preview-prod.vfs.va.gov/preview?nodeId=765

**Comment by AkucherGCIO** [comment]
2020-27-02 PW Standup
Anne will be checking to see if a bug in Drupal is fixed and will send live links to the stakeholders.

**Comment by RLHecht** [comment]
@AnneHurley I fixed the tables for both of the life insurance pages that had the Drupal issue. Please just look them over to make sure it didn't introduce any other errors. If the next step is publishing, let me know.

**Comment by AnneHurley** [comment]
@RLHecht  These look great, ready to go.

**Comment by RLHecht** [comment]
@AnneHurley Both these pages are now published. There was an issue with a broken jump link on the SGLI page that I fixed and another one of those links to a page before the PDF on the Family members' page. I fixed both. Moving to validate and can close this afternoon once it's published. @AkucherGCIO FYI.

**Comment by AnneHurley** [comment]
Thank you @RLHecht and thanks for finding those link issues.

**Comment by AkucherGCIO** [comment]
2020-28-02 Standup
Randi will check this afternoon and will be closing the ticket.

**Comment by RLHecht** [comment]
These pages look good. Closing ticket! @AnneHurley @AkucherGCIO
