### ISSUE TITLE
SOCKS access for An Tran

### ISSUE THREAD

**Issue by antranva** [department-of-veterans-affairs/va.gov-team#61366]
### Your Name

An Tran

### Your Email

an.tran@va.gov

### Your Role and Team

SQA - MyHealtheVet (MHV)

### Product Manager (PM) name and email

Sean.Good@va.gov

### Product Owner (PO) name and email

Gregory.Kirk@va.gov

### Access Type Requesting

viewers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDqcPe8HLONDUwjk7HC8GjD5FeeMOwl2bxYMu9/oEpyLBC4qqN4u39KQhKgE5YzZRd2SGn+1Y6LLUnMBWPvgr7qRlX2t+5qOLbRtBCCBedfN+AsRbHQKq7VAI6Pp86ujFOo/gj/2mTBHvbu2e4qhOUyJjsJ8EbE28VBdrBYlaDNSvSbRWnM+LW9JRnO0ECeN2Mp4P8K9zmQi3adodlaRpx/XsIHEHjVQpS35NSqrrEiiHSCFGNCW44BJrX0LNbW+r5n+Jub5KLNLLvklI4z+b4HOtDijmI90HUqziC+TEN1WOdW/7N3PAUR7k1IiwTt/mrfqUZHRjX8K2ia06PiYnW6eiz130cBUzrxlK/68r2zKtSIzNmkC0MS6te0nofWX3OIcCW4RZQiCD26hj1ojx+3gGEE2VlZ1Y6sL1VuidgLPhSzUlnpIjn0uyBj6GAg4eE6ft0wBnVBM8nm+LIB1HBAvN2nwn2DbjBEN7C6AFRtDVPK9hneBSHQU07AP4P20g0= antran@antran

### E-QIP Transmittal Confirmation

![EQIP Transmittal Notice email screenshot](https://github.com/department-of-veterans-affairs/va.gov-team/assets/87745153/c7f8d0b2-45eb-42f4-84b2-b2cf48adb1e2)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by flooose** [comment]
::error:: The attached ssh key failed to validate

**Comment by flooose** [comment]
::error:: The attached ssh key failed to validate

**Comment by flooose** [comment]
::error:: The attached ssh key failed to validate
