### ISSUE TITLE
Review VRE::CreateCh31SubmissionsReportJob

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#61373]
Review VRE::CreateCh31SubmissionsReportJob. Is this job still needed?

## Background

This ticket was created from the last uncompleted task that was apart of [Depreciating Sidekiq Scheduler](https://app.zenhub.com/workspaces/platform-tech-team-1-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/59770)

**Comment by tblackwe** [comment]
We've been unable to find anyone to speak to this report. @RachalCassity you can delete the scheduled task and if we will resolve the metadata issues if/when the consumer of the report comes looking for it.
