### ISSUE TITLE
Double check call center numbers in VAOS footers

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#6137]
Update needed for the VAOS call center numbers. 

- [ ] We need to isolate the "For help scheduling an appointment, or if you have questions about enrollment or eligibility, please call:" to the VA Facility and Community Care Appointments _only_ instead of being copy that encapsulates both VA facility and CC appointments and VA Video Connect Appointments

- [ ] We need to add the following copy above VVC (VA Video Connect) "For issues or questions about joining your VA Video Connect appointment please call:"

## Correct Contact Information
*National Telehealth Technology Help Desk*
    866-651-3180
    703-234-4483
    Monday — Saturday 7 a.m. — 11 p.m. (ET)

*For help desk, here is what it looks like in the existing tool:*
![IMG_3717.PNG](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/7896199e-5e64-48e0-8933-39b519cd6467)

@peggygannon @rtwell @jbalboni -- see above for correct contact information and current help desk info/copy from legacy VAOS.

Current UI that needs update:
![need help update.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/8fe3e1b8-3edd-4359-9971-9e6c6b387933)

**Comment by lenaecb** [comment]
Hi @clantosswett - can you confirm the information (phone numbers, text) for VA facility and community care appointments? We have confirmation and correct info for getting the video appts assistance. 

![Screen Shot 2020-02-27 at 10.43.55 AM.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/a5ff05a8-3eac-4067-a7fe-cf31b35ec991)

**Comment by lenaecb** [comment]
@peggygannon - A request came in to update the copy to better frame around the contact information. I've added thoughts on how to achieve that based on feedback from one of the VAOS stakeholders. Thoughts?

**Comment by lenaecb** [comment]
@clantosswett - Mentioned this in Slack. If you verify, please do! Thank you!

**Comment by clantosswett** [comment]
@lenaecb I've reached out to a few contact center leads to confirm who the number you have listed is correct since I don't know for sure the answer to this.

**Comment by lenaecb** [comment]
Ok, thanks @clantosswett !

**Comment by lenaecb** [comment]
@peggygannon @rtwell @jbalboni - we're still working to get the updated numbers for VA facilities and community care ( @clantosswett is on it!) but we need to update the footer to something similar to what I've added to the issue. 

We should also do this with context of the updated request for the link back to old VAOS tool in footer. See #5124

Thoughts?

For awareness, this issue and #5124 are must haves for Phase 1 rollout.

**Comment by peggygannon** [comment]
@lenaecb @rtwell 

Here's copy recommendation for the footer. A couple of things to clarify: 

--phone numbers for both are the same. Per your comment above, someone from contact center is comfirming we have the correct numbers and hours? 

--I leave it up to Ryan to decide how he wants to format this content. (would column format be better? more readable?)

--I pulled the link to the "old scheduling tool" from Lauren's copy in #5124, please confirm that that is correct? It looks like it's for mobile device, so I want to double check that it's also correct link for desktop? 


**Need help?**
For help scheduling a VA or Community Care appointment, or if you have questions about enrollment or eligibility, please call 877-222-8387 (TTY: 800-877-8339). We’re here Monday-Friday, 8:00 a.m. to 8:00 p.m. ET. 

For questions about joining a VA Video Connect appointment, please call 877-222-8387 (TTY: 800-877-8339). We’re here Monday-Friday, 8:00 a.m. to 8:00 p.m. ET. 

[Go back to the old VA appointment tool](https://veteran.mobile.va.gov/var/v4/)

**Comment by rtwell** [comment]
![image](https://user-images.githubusercontent.com/12564977/75819716-2318d280-5d69-11ea-802d-0670483e289c.png)

**Comment by lenaecb** [comment]
@peggygannon @rtwell @jbalboni - updated the issue with the correct contact info and also dropped the following screenshot from legacy VAOS help desk (see below) into issue. 

I don't think we need all of the copy from legacy, but some of the explanation is helpful. ![IMG_3717.PNG](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/680bef85-d912-4f78-912f-9a191c6af5c3)

**Comment by lenaecb** [comment]
VA appt info should be:
National Telehealth Technology Help Desk
866-651-3180
703-234-4483
Monday — Saturday 7 a.m. — 11 p.m. (ET)

**Comment by jbalboni** [comment]
Based on the numbers we have and Ryan's design, this is my tentative implementation:

![Screen Shot 2020-03-04 at 10.20.50 AM.png](https://images.zenhubusercontent.com/599c94608f62dc7798c3b2cd/6359ff8d-ef6e-4e17-b0cb-40a0c91f4ca1)

One questions I have is around TTY. I switched it to follow what our other need help components do, which is point to 711. We do this same thing for the other 3 or 4 numbers we point people to on va.gov.

**Comment by lenaecb** [comment]
Looks good @jbalboni and I agree we should keep the consistency with TTY: 711

**Comment by peggygannon** [comment]
Hello, @lenaecb sorry to nickpick, but the times aren't formatted per our style. 

Can we update the times to: 

We’re here Monday-Friday, 8:00 a.m. to 8:00 p.m. ET.


We’re here Monday-Saturday, 7:00 a.m. to 11:00 p.m. ET.

**Comment by lenaecb** [comment]
Ah, thanks @peggygannon !

**Comment by jbalboni** [comment]
![Screen Shot 2020-03-04 at 4 15 14 PM](https://user-images.githubusercontent.com/634932/75923557-59228900-5e33-11ea-935c-3cffe00b09f0.png)

**Comment by lalexanderson-dsva** [comment]
The TTY should stay the same correct.
