### ISSUE TITLE
Vets-api terminal access for Samuel Cormier

### ISSUE THREAD

**Issue by samcoforma** [department-of-veterans-affairs/va.gov-team#61395]
### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Samuel

### Your GitHub handle (terminal access is managed through GitHub)

samcoforma

### Team, Role, and Company of the target individual

VA Benefits, Engineer, Coforma

### Product Manager (PM) name and email

Jacob Worrell, jacob.worrell@adhocteam.us

### Product Owner (PO) name and email

Matthew Self, Matthew.Self2@va.gov

### Your dsvagovcloud AWS user name (if applicable)

Samuel.Cormier

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### COR Name (leave "None" if you listed an AWS user name above)

None

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

None

### Access Expiration

ongoing

### Additional Notes

I need prod access in order to debug issues that come in from the Contact Center regarding our application(s). It's really hard to debug without inspecting certain things about a claim. I also need access to debug things in staging, like investigating the state of staging account's eFolders for DDL. Thanks!

### User must exist in a roster before vets-api terminal access can be granted

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added
- [x] If they included an AWS user name, check to see if their user name is listed in [iam_users.tf](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf)
- [x] Comment in this issue saying which roster the user is listed in and confirming their AWS user name (if applicable)

**Comment by jknipes** [comment]
@samcoforma found in VFS Team Roster, AWS user name confirmed. You've been granted access to the `dev`, `staging`, and `sandbox` environments.

**Comment by jknipes** [comment]
@samcoforma Access to `prod` is pending approval by OCTODE, and we'll update you as soon as it's available.

NOTE Please provide a screenshot of your EQIP Transmittal, as it will expedite Production approval.

**Comment by BillChapmanUSDS** [comment]
Access to prod allowed with 3 month limit as per policy.

**Comment by jknipes** [comment]
@samcoforma you have been given access to `prod` until October 3rd.

**Comment by jknipes** [comment]
Support Team reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1688584207671869)

**Comment by bdech** [comment]
slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1696511057837099)

**Comment by samcoforma** [comment]
Yes, I’d like an extension please. Thank you!

**Comment by lindsay-insco** [comment]
@LindseySaari @ericboehs can one of you please give us a 👍 to extend their access?

**Comment by lindsay-insco** [comment]
@little-oddball can you please give us a 👍 to extend their access?

**Comment by lindsay-insco** [comment]
@samcoforma Your `Production` access has been extended 6 months, expiring 06/18/24. Please set a reminder for yourself to return to this Issue and re-request access within 1 week of the expiration date. You'll receive 1 reminder with a 72 hour window to respond. Failure to do so will result in lost access and will require you to fill out a new request.

**Comment by lindsay-insco** [comment]
@samcoforma Your Vets API Terminal Production access has expired.

Would you like to request an extension? You have 72 hours to respond, or your
access will be revoked and you will need to fill out a new request

**Comment by bdech** [comment]
No response, production access removed. If you would like to request production access, please fill out a new request
