### ISSUE TITLE
[a11y-defect-4]: Additional evidence page should not used nested fieldsets

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#61391]
## Point of contact

@joshkimux

## Severity level

4, Minor. Consider fixing or exploring in 2-4 sprints post-launch.

## Details

The additional evidence page currently uses a nested fieldset. This isn't a major or moderate issue as it doesn't share similar problems presented by the dynamic wizard (where it would be unclear where on section ended vs another).

<img width="1218" alt="Screenshot 2023-07-05 at 11 52 13 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/14154792/11c84d0c-6737-4a51-9f1f-a9b5b74a3c16">

That being said, we could clean this up so we don't have nested fieldsets (which is usually not a great thing).

## Reproduction steps

1. Log in to NoD as user 236
2. Add an issue
3. On the select a board review option page, select "submit more evidence"
4. Inspect the code, confirm there are two fieldsets

## Proposed solution or next steps

Through small content changes, we can adjust this form to only have one fieldset/legend pair:
- Rename the `h3` to be the question from the second fieldset's legend
- Use `aria-describedby` to use the remaining paragraph to describe each of the radio button inputs

<img width="1229" alt="Screenshot 2023-07-05 at 11 38 26 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/14154792/6d04d37d-cbe0-425d-ae98-fa415744d595">

Through VoiceOver, it'll sound like this:

https://github.com/department-of-veterans-affairs/va.gov-team/assets/14154792/66ccdba6-1195-43a9-ae44-bd25022dd60c

## References, articles, or WCAG support

1. [The problem with nested fieldsets](https://adamsilver.io/blog/the-problem-with-nested-fieldsets-and-how-to-avoid-them/)

## Type of issue

- [ ] Screenreader
- [ ] Keyboard
- [ ] Focus
- [ ] Headings
- [ ] Color
- [ ] Zoom
- [X] Semantics
- [ ] Axe-core
- [ ] Something else

**Comment by Mottie** [comment]
@joshkimux This is ready for testing in staging! 🙏🏽

**Comment by joshkimux** [comment]
@Mottie amazing!! ❤️ 

Confirming that the main issue with nested fieldsets is fixed ✔️ 

Small engineering question: is it possible for us to still connect the descriptive paragraph to the checkboxes or fieldset? It's a more minor issue, but worth giving a shot if it's technically feasible.
<img width="1549" alt="Screenshot 2023-08-01 at 12 48 12 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/14154792/e0e66376-7be8-481f-a8e1-a2d364e7427a">

**Comment by Mottie** [comment]
yes, we can add an `aria-describedby` to those radios since we're still using the form system here. If we were using the `va-radio` web component, I don't think we could - I might have to open a ticket for this.

**Comment by Mottie** [comment]
Done & ready for testing in staging

**Comment by joshkimux** [comment]
Will validate today 🖖

**Comment by joshkimux** [comment]
<img width="1075" alt="Screenshot 2023-08-02 at 1 37 45 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/14154792/5a68e0ab-9bce-421c-878b-a4586d2b96bf">
Confirming this has been fixed, thanks @Mottie 🥳
