### ISSUE TITLE
[UX] Create TestRail Test Cases

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#61398]
## Release 2 Wireframes
[Wireframes](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/868762F3-8E8F-4E23-B0DA-34C1783F0A03/canvas)

## Tasks
- [x] Create TestRail Test Cases 

## Acceptance Criteria
- [x] TestRail test cases have been created and are ready to use based on the workflow for this feature

**Comment by loripusey** [comment]
@benbrasso-agile6 @kellysmith1008 ready to validate

[Release 2 Test Plan](https://dsvavsp.testrail.io/index.php?/plans/view/4796)
NOTE: each test run is the same

**Comment by kellysmith1008** [comment]
Morning, @loripusey ! Could you help me figure out what I'm doing wrong? I think I have a weird filter on or something. I'm not seeing any tests in the UX test run (or any of them, which is what makes me think I have a weird filters). This is what I see: [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBakltIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8dc69c4758eca4037f43d9b1455cf915186e5d06/image.png)
I'm 1000% sure this is user error, I just can't figure out what I'm doing wrong!

**Comment by kellysmith1008** [comment]
Ah, yep, I had a weird modernized check-in filter applied. I see the tests now :)
