### ISSUE TITLE
Qualitative Data Request - VA Homepage, June 2023

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#61396]
### Data Type Requested

User Surveys

### Date Range Start

06-01-2023

### Date Range End

06-30-2023

### Product Name(s)

VA Homepage

### Product Description

The VA Homepage (which received a major update on June 1)

### Survey URL(s), key term(s), case category or type

www.va.gov ONLY

### File Delivery Format

All in one file, on one tab

### VA Email Address(es)

wesley.rowe@va.gov

### Add Assignee and Labels

If not already done so, please ensure @ianMcCullough-ob is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by newworld2616** [comment]
Hi, I have shared the data please confirm once you received it. Thank you.

**Comment by wesrowe** [comment]
thank you. someone already provided this data, as I needed it for an analysis in early August

**Comment by newworld2616** [comment]
Thank you for confirming, I will close the request!

**Comment by wesrowe** [comment]
@newworld2616, my PO just pointed out that the data you sent me for Sept is from June. I need the correct data pulled ASAP. Will slack you also.
