### ISSUE TITLE
Consider: Integration with after-visit summary

### ISSUE THREAD

**Issue by melissa-lefevre** [department-of-veterans-affairs/va.gov-team#61406]
## Description 
As a Veteran reviewing my past appointments, I want to be able to review my after visit summary. 

![Screenshot 2023-07-05 at 12.19.06 PM.png](https://images.zenhubusercontent.com/603fe0d8f45baf5a1d422aaf/c530e5b5-1c11-4375-834e-8eed976b5939)

As part of this story we want to :   

- Link to after-visit summary in past appointment details
- Borrow what MHV is doing with test results

## Acceptance Criteria
  

-  [ ]  

**Accessibility Requirements**
- [ ] 
Notes & Open Questions

- Dependencies/Roadblocks:
    - Any internal/external dependencies?
    - Test accounts needed?
- Does this require QA?
    
- Dev Notes: 

## Ticket Checklist

- [ ] Acceptance criteria defined
- [ ] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic

**Comment by outerpress** [comment]
This should become a reality in the next couple of months, closing :)
