### ISSUE TITLE
Consider: One thing per page

### ISSUE THREAD

**Issue by melissa-lefevre** [department-of-veterans-affairs/va.gov-team#61409]
## Description 
As a Veteran scheduling an appointment, I want to have one task per page so that I can stay focused on the question being asked and not experience cognitive overload. 

![Screenshot 2023-07-05 at 12.21.37 PM.png](https://images.zenhubusercontent.com/603fe0d8f45baf5a1d422aaf/e7eedf68-6730-499e-89ad-9dead0cdaac2)

As part of this story we want to :   

- Removes confusing breadcrumb
- Removes extra question label
- Simplifies form navigation

## Acceptance Criteria
  

-  [ ]  

**Accessibility Requirements**
- [ ] 
Notes & Open Questions

- Dependencies/Roadblocks:
    - Any internal/external dependencies?
    - Test accounts needed?
- Does this require QA?
    
- Dev Notes: 

## Ticket Checklist

- [ ] Acceptance criteria defined
- [ ] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic

**Comment by AnkitAnandMastery17** [comment]
Hey. Is this issue still open? If yes,I want to work on this.

**Comment by outerpress** [comment]
Consolidated this into #59659, closing
