### ISSUE TITLE
Update Poster to Include "You're Checked in"

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#61426]
## Tasks
- Update the [poster version that was created to include the check-in from the Mobile App](https://www.sketch.com/s/9798426e-bba3-46dd-9d87-73d77dcf6599/p/6D6EA671-49DC-454E-9F9B-8D92396D3244/canvas) to include the "you're checked in" information

## Resources
- Kelly's content work: https://www.sketch.com/s/e43551b4-033a-4dd3-a876-076646e1f580

**Comment by zach-park** [comment]
@benbrasso-agile6 @kellysmith1008 , the revised posters in all sizes are ready to be validated. Thank you.

https://www.sketch.com/s/9798426e-bba3-46dd-9d87-73d77dcf6599/p/52EFC518-9960-412B-8FDA-CD176F937599/canvas

**Comment by benbrasso-agile6** [comment]
LGTM

**Comment by zach-park** [comment]
@loripusey, ready for validation.

**Comment by kellysmith1008** [comment]
Looks great, Zach!

**Comment by loripusey** [comment]
LGTM
