### ISSUE TITLE
Update the GA Dashboard to Add Metrics for App Store Clicks

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#61437]
## Tasks
- Update the GA eCheck-in dashboard to include metrics for the 2 app store links (see below)

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/86678742/858a9526-e2c4-4416-a487-63eab49ecee0)

**Comment by loripusey** [comment]
@benbrasso-agile6 can you point this ticket?

**Comment by benbrasso-agile6** [comment]
So long that there's a GA event to listen for, 2 pts. I assume FE will make that happen by default. So, 2 pts.

**Comment by loripusey** [comment]
yeah, there's a separate ticket for FE to add the custom events for the 2 clicks
