### ISSUE TITLE
[FE] Add Tagalog Translations

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#61443]
## Tasks
- [ ] Add the following Tagalog translated content to the appropriate json file    
- [ ] Generate screenshots for workflow documents to submit to the State Department

[Tagalog_5_1_2024.json](https://github.com/department-of-veterans-affairs/va.gov-team/files/15178044/Tagalog_5_1_2024.json)

**Comment by AnkitAnandMastery17** [comment]
Hi. In which language do you want the translation?

**Comment by AnkitAnandMastery17** [comment]
Can you give me more information about this, if possible because I want to work on this.

**Comment by brianseek** [comment]
Screenshots 
[travel.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNy9NQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fd9e6fd719975c2d309a567c4b0be83d34a13e22/travel.zip)

[day-of.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzdNQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bee86d82b44afe957dbd64ef8a5cab8f79adeb7f/day-of.zip)

[pre-check-in.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzNNQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5e38886e55db74a05f2871a8c258c5dc701efbc3/pre-check-in.zip)

**Comment by brianseek** [comment]
@loripusey this is merged and will be live soon. I did find one translation that we were missing all together, so I added it to the english file.
```
  "appointments_one": "appointment",
  "appointments_other": "appointments"
```
Not sure if you want to try to look at other translations and add this in Spanish and Tagalog ourselves since it was missed and never sent.

Here is the usage:
<img width="678" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNURQQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--427cb36290793634f07e367cff49e81d8bf27460/Screenshot%202024-05-10%20at%208.15.18%E2%80%AFAM.png" alt="Screenshot 2024-05-10 at 8.15.18 AM.png" />

**Comment by loripusey** [comment]
@brianseek Found this issue:
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/86678742/db2a50c8-92a8-4f78-b781-9251840f4149)

Should be:
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/86678742/f7a494a7-dab0-40b9-9353-008e79e15091)

**Comment by loripusey** [comment]
Another issue: missing the "t" in appointment

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/86678742/7790031e-40b2-498a-a738-530aa170cd1a)

**Comment by brianseek** [comment]
@loripusey I can't reproduce that one
<img width="457" alt="Screenshot 2024-05-13 at 10 30 50 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/13967174/c81a121f-b477-4911-ac05-c3e662706cd4">

**Comment by loripusey** [comment]
Ignore my comment above about the singular vs. plural, I am still trying to sort through that.

**Comment by loripusey** [comment]
validated
