### ISSUE TITLE
Accessibility Testing for Appointments FE, Appointments, Print Feature 

### ISSUE THREAD

**Issue by Cieramaddox** [department-of-veterans-affairs/va.gov-team#61440]
### Product information

- [X] Team name, product name, and feature name have been added to the title of this issue.
- [X] Team label, product label and feature label (if applicable) have been added to this issue.

### Who completed the use of color and color contrast test?

This was completed in staging:
User: Judy.morrisson@idme.com
Instance: https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/
Browser: Chrome
OS: Ventura
### Use of color and color contrast checks

- [x] All text of 20px or smaller has a 4.5:1 contrast ratio to its background (or better)
- [x] All text of 20px or larger has a 3:1 contrast ratio to its background (or better)
- [ ] Non-text elements have a 3:1  contrast ratio to their background and to neighboring elements (or better)
- [x] Color is not the only way to distinguish links from other text (eg. links are underlined)
- [ ] Any charts, maps, infographics, and tables convey all information without only relying on color
- [x] Content does not refer to color, especially when providing user instructions (eg. "Click the blue button")

### How did color testing go?

 - Active and hover tertiary button uses #DCE4EF for background with #003E73 for text. This is an 8.46:1 ratio. 
 - Focus tertiary button uses #DCE4EF for background with #0071BB for text. This is a 4.01:1 ratio. 

### axe checks

- [x] Each page has been scanned using axe (results shared below)
- [x] axe is integrated into your end-to-end testing

### axe DevTools scan results

Upcoming: 27 issues - 
Elements must only use allowed aria attributes
[Upcoming axe results](https://github.com/department-of-veterans-affairs/va.gov-team/files/11970654/Upcoming.axe.results.csv)

Pending: 3 issues - 
ID of active elements must be unique
[Pending axe results](https://github.com/department-of-veterans-affairs/va.gov-team/files/11970657/Pending.axe.results.csv)

Past: 33 Issues - 
Need unique aria labels
[Past axe results](https://github.com/department-of-veterans-affairs/va.gov-team/files/11970661/Past.axe.results.csv)

### How did axe testing go?

Axe testing picked up several issues, none of which pertaining to the print feature. **0 issues found with print button.**

### Who completed the content zoom and reflow test?

@Cieramaddox 

### Content zoom and reflow checks

- [x] All page elements are readable and usable at 200% zoom
- [x] All page elements are readable and usable at 300% zoom
- [x] All page elements are readable and usable at 400% zoom

### How did content zoom and reflow testing go?

Everything worked well, no issues found.

### Who completed the keyboard navigation test?

@Cieramaddox 

### Keyboard navigation checks

- [x] Each link, button, form input, checkbox, radio button, select menu, and custom element can receive keyboard focus
- [x] Each link, button, form input, checkbox, radio button, select menu, and custom element responds to expected keys
- [x] All elements under focus have a visible focus indicator
- [x] The order of [Tab] stops made sense and was appropriate for completing tasks

### How did keyboard testing go?

Keyboard test successful with no issues, 

### Do you have any other results to share?

Tested VoiceOver on Chrome for Mac iOS Ventura.
Everything worked as it should.

**Comment by ldelacosta** [comment]
Work is completed. Closing out the ticket.
