### ISSUE TITLE
AWS access for [Gerard Robert Sullivan]

### ISSUE THREAD

**Issue by gerard-sullivan** [department-of-veterans-affairs/va.gov-team#61457]
### COR Name

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative Name

Other - please specify in 'Additional Notes'

### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Gerard Robert Sullivan

### Your Email

Gerard.Sullivan@va.gov

### Team, Role, and Company of the target individual

MHV Medications, Full Stack Engineer, Higherechelon

### Product Manager (PM) name and email

Raquel Robertson - raquel.robertson@va.gov

### Product Owner (PO) name and email

Patricia Henry - Patricia.Henry@va.gov

### Desired AWS Access

Requesting the SSMApplicationLowerEnvironmentAccess policy, and to be added to the existing IAM group dsva-vfs-developers

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

![Screen Shot 2023-07-10 at 8 10 08 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/132001256/33fd3988-bf68-435a-a43a-0fc9ac4f53a0)

### Additional Notes

COR: Sean Good
Vendor Onboarding Representative: Kenneth Brown
Access Expiration: Need ongoing access to upstream data APIs in lower environments for VFS development activity

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by bdech** [comment]
Found in VFS Team Roster

**Comment by BillChapmanUSDS** [comment]
Lower environment access approved.
