### ISSUE TITLE
[Documentation update] Choose a location - VA Direct Schedule Flow

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#61482]
## Description
The team is currently working on the data mapping initiative and would like to reference the technical design and development testing in the documentation. 

---

## Acceptance Criteria
- [ ] Fill out the technical design and development section in the [GH document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/feature-reference/schedule-flow/va-direct--choose-location.md#technical-design)

### Design Assets
N/A

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by ajmagdub** [comment]
updated development testing section with Vets API tests

**Comment by outerpress** [comment]
This looks good to me, thanks! FYI @ldelacosta

**Comment by ldelacosta** [comment]
No issues found. Closing out the ticket.
