### ISSUE TITLE
Access for Kenneth Elwood Gary

### ISSUE THREAD

**Issue by elwoodva** [department-of-veterans-affairs/va.gov-team#615]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Greg Kirk
- Please provide your name.
   > Kenneth Elwood Gary
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > BYLIGHT, Software Engineer, By Light Professional IT Services LLC
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Internal%20Tools.md#create-ssh-public-key) for instructions.
  > should look something like this:

  > ssh-rsa 
  >  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCnC4xb1ORni6vwLKp5eQH+H1NZy3TPJ2oA7mdUiYBvQW1jJeE34gMb7EhuklvoJ9oodS++p4SZTScEUHLomgKlINT16YGPt3SyvnFY9FGFBls9adIymaRRjqU3H7XX+uv5Q3VidMZl33cAUiSd+2NMOgU7JuVWxvEaoS9TKfTm+mK0x4DjZci83iJJoSkXDCA/Li7gux+n779Lm+7nlgOu4wZPTpLWNUnxfsVtVPLFOH7isHH3LCyIBmy/coXlbztjWUQkbYASllwio0UnxEd2OkeoPNk0ntWiB1oV9g74kExmZ8f8yZlxDF2EJqwovQ7v0tN+fBRg4uzLsgl0LPbb kenneth.gary@BY-CBWMZ52

- [Grant AWS Console access?]
  > YES
  > Our infrastructure is hosted in and makes use of services in AWS GovCloud. This account is shared amongst many different
  > teams; changes made to resources in this account will affect many services. You will need access to AWS for troubleshooting, 
  > log file review and to apply changes to the running instances and services.

**Comment by elwoodva** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by tskinn** [comment]
@Jeff-Hayter 

> COR - Greg Kirk
> Req - Kenneth Elwood Gary

**Comment by Jeff-Hayter** [comment]
@tskinn - Confirmed.  Please grant access.

**Comment by tskinn** [comment]
@elwoodva your SSH key has been added and AWS and Sentry accounts created. Contact us via slack if you encounter any issues.
