### ISSUE TITLE
Dividing line extends to mobile (360px - 481px) screen on pending page

### ISSUE THREAD

**Issue by Cieramaddox** [department-of-veterans-affairs/va.gov-team#61509]
## Summary

The dividing line beneath the sub-navigation should not appear on mobile screen sizes, and only appear on the tablet and desktop screens. The line is still present on mobile between 360 and 481 pixels.

## Specs
- Device: Mobile (360px - 481px)
- Browser: Chrome

## Steps to Reproduce
**Test User:** Judy.morrison@idme.com

1. Go to: https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/pending
2. Set screen size to 360px - 481px

### Actual Result
Line is present on mobile screen sizes on pending page.

### Desired Result
No line present on mobile screen sizes on pending page. 

## Definition of Done
- [ ] Line is removed

**Comment by Cieramaddox** [comment]
@ldelacosta This ticket has been validated and good to close out!

**Comment by ldelacosta** [comment]
No new issues to report. Closing out the ticket.
