### ISSUE TITLE
Midpoint Review - Content Feedback - Veteran Facing Forms, 40-0247: Presidential Memorial Certificate Form

### ISSUE THREAD

**Issue by CherylEvans** [department-of-veterans-affairs/va.gov-team#61516]
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- How does the content associate with the position of the progress bar steps? The progress bar "steps" don't match up with the progress of the steps on the pages.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

### Must
- Future v2 > 2 - Step 2 of 12 - Number of certificates requested > "be sent" is passive voice. I recommend: How many certificates are you requesting we send to your address?"
- Future v2 > 6 - Step 6 of 12 > Additional certificates request > The verbiage syntax doesn't match. I recommend: "Yes, I would like to request additional certificates mailed to a separate address.
- Current > Veteran's personal information > Always capitalize **Veteran**. I think you can drop the article "the" as well.
- Future v2 > 4B - Step 4 of 12 > Application address Copy > "Let us know where the you'd like to send the additional requests," contains a typo and improper use of verbiage.  I recommend: "additional certificate/s" vs. "additional requests," because you're not sending a request, you're sending a certificate. Also take out the word "the" because it's a typo![60496_Passive Voice_Screenshot 2023-07-06 at 8.20.50 AM.png](https://images.zenhubusercontent.com/61fa9c81372349426637bcfa/97ab28f6-a179-465d-bd8a-db9c0601bba6)![60496_Incongruent Syntax_Screenshot 2023-07-06 at 8.24.36 AM.png](https://images.zenhubusercontent.com/61fa9c81372349426637bcfa/17fcb2c2-7176-41cd-a7d4-f9917bf270c3)![60496_Improper use of verbiage_1_Screenshot 2023-07-06 at 8.32.16 AM.png](https://images.zenhubusercontent.com/61fa9c81372349426637bcfa/a2cb16e9-043d-47b6-9d86-d0ef1e882e46)![60496_Improper use of verbiage_2_Screenshot 2023-07-06 at 8.37.25 AM.png](https://images.zenhubusercontent.com/61fa9c81372349426637bcfa/b0f84bbc-c742-41ea-9dc8-8f05cd270904).

### Should

- Intro page > Enlisted Officer > Note: "The preferred discharge document to establish eligibility for the certificate is the DD Form 214."  The syntax for this form is different is different to other locations across the VA.gov website and the DoD Forms Library. I have provided multiple examples. I believe Form DD214 might be the standard usage, but recommend confirming with SWCAIA.

- Intro page > Enlisted Officer > Note: "The preferred discharge document to establish eligibility for the certificate is the DD Form 214. > The way this is worded leads the user to believe that there is another way to establish eligibility that may not be "preferred." If this is the case, it should be specified to the user.

![60496_DD Form 214_1_Screenshot 2023-07-06 at 11.07.24 AM.png](https://images.zenhubusercontent.com/61fa9c81372349426637bcfa/ac4671b3-db5d-449b-b6b5-840aa0643b10)![60496_DD214 VA.gov website examples_2_Screenshot 2023-07-06 at 8.01.57 AM.png](https://images.zenhubusercontent.com/61fa9c81372349426637bcfa/d6ecdadc-1688-4527-914e-6e9ce273683d)![60496_DD214_DoD Forms_3_Screenshot 2023-07-06 at 7.57.29 AM.png](https://images.zenhubusercontent.com/61fa9c81372349426637bcfa/072f3f84-829a-4bde-8ef2-12d9a2425177)![60496_DD214_DoD FormsList_4_Screenshot 2023-07-06 at 7.54.28 AM.png](https://images.zenhubusercontent.com/61fa9c81372349426637bcfa/14615ba5-4d10-4e94-b8da-ccfbb8e50625)![60496_OOS?_Preferred Discharge Document_Screenshot 2023-07-05 at 4.28.30 PM.png](https://images.zenhubusercontent.com/61fa9c81372349426637bcfa/54c44956-e24c-46d6-a139-4f4456726a47)

**Comment by rachelshearerux** [comment]
All feedback has been incorporated into the sketch and markdown file ✅! 

Re: the comment on the progress bar, that graphic has been fixed to accurately reflect the 10 steps in the request form.
