### ISSUE TITLE
Finalize content for Reactivation Test - Version B

### ISSUE THREAD

**Issue by alevindecanini** [department-of-veterans-affairs/va.gov-team#61520]
As a veteran who already has a login.gov/id.me account (reactivation segment) I want to receive an email that informs me about the upcoming credential service changes and gives me a way to take action now.

ACCEPTANCE:

- [x] finalize email content following feedback from the Sitewide Team
- [x] add final content to VA Notify email template

**Comment by CarlDickerson** [comment]
Content in Figma here: https://www.figma.com/file/8vobVoSl1UqLnXsni3rcvO/Login.gov-Adoption%3A-Design-Flows?type=design&node-id=2450%3A4103&mode=design&t=hg5sD4HXYo2KX7VK-1

Final content in drive: https://drive.google.com/file/d/12UZtKafoV9iEmb4C8yuoId1dlt1at6Ec/view?usp=drive_link
