### ISSUE TITLE
Add Access Requirements to Onboarding Docs

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#61524]
**Description:**

Add all access types needed for Tier 1 and Tier 2 to the [Platform Support Onboarding Doc](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2509310692/Platform+Support+Onboarding).

**Definition of Done:**

- When all access types below are added

Access Types to Add 

- [x] DataDog
- [x] Terminal
- [x] Sidekiq
- [x] Sentry
- [x] SOCKS
- [x] PagerDuty

**Comment by lindsay-insco** [comment]
Access requirements added to onboarding document
