### ISSUE TITLE
Midpoint Review - Accessibility Feedback - Veteran Facing Forms, 40-0247: Presidential Memorial Certificate Form

### ISSUE THREAD

**Issue by briandeconinck** [department-of-veterans-affairs/va.gov-team#61533]
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

-

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- **Should:** For the [supporting discharge documents](https://www.sketch.com/s/e570369e-2610-4b06-a65a-dbfb61b450f4/a/vRQA2pQ), I think the content here is right on the edge of needing some additional heading structure. It's probably not *necessary*, but I'd suggest trying headings for the enlisted service members and enlisted officers sections.
- **Should:** In the Future v2 version when providing [multiple addresses](https://www.sketch.com/s/e570369e-2610-4b06-a65a-dbfb61b450f4/a/K0RO2qV), I think there's a potential cognitive load challenge from separating the requestor's address and the addresses submitted in the list and loop. If I'm requesting a certificate for myself (requestor address), my brother (additional address) and the Veteran's best friend (additional address), I will only see two addresses (brother and friend) listed on that page. Users may have trouble remembering that their address was provided separately, or may be confused about whether they need to enter it more than once. Three possible solutions (no strong preference from me!):
   - Static text on the multiple addresses page making clear that the requestor's address is already accounted for.
   - Dynamic card listing the requestor in addition to whatever cards get added through the list and loop.
   - Reorder the user flow so that the requestor provides their address as a part of this list and loop, so all the addresses happen at the same time.
- **Consider:** Echoing Allison in #61530, for the multiple addresses consider a multi-page multiple responses pattern if possible.

**Comment by rachelshearerux** [comment]
I've added new hierarchy via a subway-map component to the intro page to more logically lay out what's expected of users in the request form. 

Re: the list-and-loop feedback, we're no longer collecting personal details other than address and number of certificates which simplifies the list-and-loop experience.
