### ISSUE TITLE
Midpoint Review - Design Feedback - Veteran Facing Forms, 40-0247: Presidential Memorial Certificate Form

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#61530]
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- Thank you for the mobile view!

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- **Must**: Updated the segments in the [progress bar](https://design.va.gov/storybook/?path=/docs/uswds-va-segmented-progress-bar--default) to match the heading content. Eg if there are going to be 10 chapters there should be 10 segments.
- **Must**: Use the word "files" instead of "documents" for [uploading](https://design.va.gov/patterns/ask-users-for/files). Our design system examples need to be updated.
- **Consider**: There seems to be a lot of information for your list and loop. Consider using the [multi page](https://design.va.gov/patterns/ask-users-for/multiple-responses#how-to-design-and-build---multi-page) multiple responses

**Comment by PSIEBENLIST** [comment]
Regarding the list and loop feature, the form stakeholder confirmed applicants who fill out another form to send certificates honoring the deceased Veteran to another address, will almost always address the additional certificates to themselves. As such, we will be removing the name and contact info from the list & loop page.

**Comment by PSIEBENLIST** [comment]
Hi @allison0034 - quick follow-up question on your feedback "Must: Use the word "files" instead of "documents" for [uploading](https://design.va.gov/patterns/ask-users-for/files). Our design system examples need to be updated."

 On the supporting documentation page, there are 4 instances of "document." Can you confirm which ones should be updated to "file"? It's a bit unclear from the current DS examples

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/109593519/40839a6a-faae-4593-8925-e1da6491b7db)

**Comment by allison0034** [comment]
Hi @PSIEBENLIST that is a good question. This was a recent change that came from the content team. @DanielleThierryUSDSVA can you help answer Pat's question?
