### ISSUE TITLE
Updating Jira instance information for Datadog access

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#61545]
### Description
Around May 2023, the MAX Jira instance (https://vajira.max.gov/) was migrated to a DOTS instance (https://jira.devops.va.gov)

The documentation on https://depo-platform-documentation.scrollhelp.site/developer-docs/get-access-to-datadog needs to be updated so that:

- Links are updated to new instance
- Screenshot of sign in window is updated

### Relevant URLs
- https://depo-platform-documentation.scrollhelp.site/developer-docs/get-access-to-datadog
- https://vajira.max.gov
- https://jira.devops.va.gov

### Which type of team are you on? (Platform team, VFS team, or Leadership)
Leadership

**Comment by vbellissimo** [comment]
Hi @mchelen-gov , thanks for submitting this. We're looking into updating this soon. Thanks for flagging.

**Comment by vbellissimo** [comment]
Slack support thread: https://dsva.slack.com/archives/CBU0KDSB1/p1688046560896589

**Comment by mchelen-gov** [comment]
Thanks! This page is also probably outdated in the same way: https://depo-platform-documentation.scrollhelp.site/developer-docs/troubleshooting-access-to-datadog
(I don't see any other max.gov references on the platform docs site)

**Comment by mchelen-gov** [comment]
The links can be updated just by changing the domain, i.e.:
https://vajira.max.gov/servicedesk/customer/portal/1/create/18
to
https://jira.devops.va.gov/servicedesk/customer/portal/1/create/18

**Comment by vbellissimo** [comment]
@mchelen-gov , does this look like the correct sign-in page screenshot to replace the current one on Step #2 of [this page](https://depo-platform-documentation.scrollhelp.site/developer-docs/get-access-to-datadog)? 


![Screenshot 2023-08-31 at 9 25 23 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/106613300/7c39089d-581f-4eb1-a312-73f8db75ae11)

**Comment by vbellissimo** [comment]
Hi @mchelen-gov Just wanted to let you know that we went ahead and updated both of these pages based on more information provided to us by SMEs here at the Platform. Please let me know if there's anything else we missed. Thank you!

- https://depo-platform-documentation.scrollhelp.site/developer-docs/get-access-to-datadog
- https://depo-platform-documentation.scrollhelp.site/developer-docs/troubleshooting-access-to-datadog

**Comment by mchelen-gov** [comment]
@vbellissimo Thanks! It looks like the screenshots on https://depo-platform-documentation.scrollhelp.site/developer-docs/troubleshooting-access-to-datadog are still for the old max.gov site though?
