### ISSUE TITLE
[FSR] - Review display - Hiding default edit buttons on review page

### ISSUE THREAD

**Issue by amponce** [department-of-veterans-affairs/va.gov-team#61546]
## Issue Description

We're aiming to render the 'review and submit' page as read-only. To accomplish this, we need to eliminate the option to edit each individual section, thereby aligning these sections with our updated read-only design. 

## Front-end Tasks
- [x] Utilize CSS to target and hide the edit buttons on the 'review and submit' page.

## Acceptance Criteria
- [x] Edit buttons are no longer visible on the 'review and submit' page.
- [x] Users can still submit forms.
- [x] All tests are successful.

**Comment by amponce** [comment]
PR has been created and will be one of the last things to merge.

https://github.com/department-of-veterans-affairs/vets-website/pull/24790/files

**Comment by Dr-Pongo** [comment]
Updating title to match other FE tickets generated to address review page read only effort
