### ISSUE TITLE
Change Pending language to Requests from Appointments Team (formerly VAOS)

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#61540]
## About your team

- Team name: Appointments Team
-	OCTO-DE product owner: Katherine Lawyer
-	Product manager: Jeff Roof and Leah De La Costa
-	Designer: Peter Russo, Ciera Maddox, Melissa Lefevre
-	FE engineer lead: Simi Adebowale 
- Accessibility specialist:
- Content writer: 
-	Product/team Slack channel: #appointments-team
 
### What does your team need support for? Check all that apply.
- [ ] Launching one or more unauthenticated pages, online forms, apps, or tools on VA.gov
- [X] Making revisions to one or more existing VA.gov pages
- [ ] Accessibility review of wireframes and/or prototypes
- [ ] Accessibility issue (general request)
- [ ] Accessibility PDF review request
- [ ] Accessibility user research support ([submit a separate, additional request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name))
- [ ] DST component or pattern 
- [ ] Something else 
 
### Give a brief description of what your team needs support with:

Our team is looking to update the `pending` language to `requests` in the Appointments application. 
In the Pending status, these appointments have not been booked by the VA/Community care providers. 
 
 
### Will this new product be released incrementally (for instance 25% of users initially)? 
  - [ ] Yes
  - [X] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
### When do you expect to launch your product to 100% of users?
  
October 2023

### When does this work need to be completed?
- Estimated launch date: October 2023
- Estimated staging review date: September 2023
- Content, Accessibility, and IA work needed by: August 2023

### Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [X] No

### If no ...
- Skip to the _supporting artifacts_ section, below.
 
#### Please provide the link to your Collaboration Cycle ticket: 
- Ticket (number): 
- Collab. Cycle Ticket Opened (date): 
 
#### Please check all of the phases in the Collaboration Cycle you have completed: 
- [ ] Design Intent
- [ ] Midpoint Review
- [ ] Staging
 
##### Design Intent
- [ ] Accessibility
- [ ] Content
- [ ] IA
- [ ] Translation
- [ ] Already completed, no assistance needed.
- [ ] Unknown at this time.
##### Midpoint
- [ ] Accessibility
- [ ] Content
- [ ] IA
- [ ] Translation
- [ ] Already completed, no assistance needed.
- [ ] Unknown at this time.
##### Staging
- [ ] Accessibility
- [ ] Content
- [ ] IA
- [ ] Translation
- [ ] Already completed, no assistance needed.
- [ ] Unknown at this time.
  
## Supporting artifacts
*Please provide supporting artifacts as available.*

- [Link to product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/initiatives/cc-request-flow.md)
- [Link to or attach user flows](https://www.figma.com/file/BQxFP7vqmXRIeX0GIuc8A4/Change-%60pending%60-language-to-%60requests%60?type=design&node-id=1302-7094&mode=design&t=ucyaYlAj3t8bmoE9-0)
- [Link to prototype or mockups](https://www.figma.com/file/BQxFP7vqmXRIeX0GIuc8A4/Change-%60pending%60-language-to-%60requests%60?type=design&node-id=1302%3A7271&mode=design&t=IO5WeeVXeFDF3Fur-1)
- [Link to your research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/research/2023-02-appt-list-usability-screenreader/README.md)
- [Link to any epics/issues that may be helpful](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/53491)

#### Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [X] No, let's work asynchronously and meet if needed

 **Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.
 
### Accessibility Help in Slack
The [#accessibility-help channel](https://dsva.slack.com/archives/C8E985R32) in the DSVA Slack, is also available to you as a resource. Everyone is welcome to ask questions or get help from our a11y (accessibility) specialists. Tag `@Terry Nichols` to get a11y help asap.

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag `@Terry Nichols`.**

- If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
- If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)
 
 - If you are creating an [experimental design,](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) please [also contact the DST. ](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)
- If you are requesting [a11y support for user research,](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name) please complete this form, next.

**Comment by mistymg** [comment]
@laurwill When you start to work on this, could we tag-team it? This affects mobile app, and I have some wild ideas to through out :)

**Comment by outerpress** [comment]
FYI @DanielleThierryUSDSVA this is the work we talked about at the SME sync a couple of weeks ago

**Comment by outerpress** [comment]
@coforma-terry based on a recent sync we want to make some modifications on these designs. We think the pending "bucket" might be useful for referrals and recall letters. 

I'll work on the changes and add a comment when they're ready. In the meantime, could you hold off on this ticket? Thank you!

**Comment by laurwill** [comment]
@outerpress , I'll move this to our blocked lane for now — thanks for the update!

**Comment by ldelacosta** [comment]
Hey CAIA team! Our team will hold off making any updates to the content. Closing out the ticket. Will open a new ticket when we are ready to start again. Thanks for your help & support. cc: @JRRoof @outerpress @Cieramaddox @melissa-lefevre
