### ISSUE TITLE
Design Intent - Accessibility Feedback - Benefits Management Tools, Claim Status Tool, Improve Evidence Request/Submission Experience

### ISSUE THREAD

**Issue by briandeconinck** [department-of-veterans-affairs/va.gov-team#61550]
## VFS actions
- [x] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [x] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [x] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- Since there's a lot happening in this redesign, I would very much appreciate accessibility annotations that indicate some of the structure and code choices intended in the design at Midpoint Review. In particular, it would be great to see:
   - Heading hierarchy
   - Any expected focus management
   - Any expected `aria-label` or other screen reader only text
- Expanding on a question from Sara during the meeting, I just want to mention that the mobile-first ethos is also important for accessibility. A large share of disabled Veterans only have a mobile device or use their mobile device as their primary device, and designing/doing user research at the smaller form factor can also help ensure the design works for low vision users who keep their browsers at high zoom levels. I think you said mobile design work was happening alongside what was presented, but I'd love to see mobile prototypes used for user research too.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- **Must:** Avoid using disabled inputs and buttons on the [claim files page](https://www.sketch.com/s/98e35645-34eb-40cf-80c1-6c4952943584/prototype/a/AE755A09-3FA2-4C5C-8436-6FC32DEF37CE). Sounds like that change is already in progress, so thank you! 😄 
- **Must:** Each link and button (including the control for the additional info component) needs to have a unique accessible name, so that screen reader users tabbing through interactive elements can identify what element they're on without needing to explore the surrounding context. In situations where you have duplicate text (eg. repeated "View Details" on the ["Your claims or appeals" page](https://www.sketch.com/s/98e35645-34eb-40cf-80c1-6c4952943584/prototype/a/252DFC7E-C58A-478F-A521-5C082886DA75) and the ["Overview of claim process" page](https://www.sketch.com/s/98e35645-34eb-40cf-80c1-6c4952943584/prototype/a/92A82483-D152-443A-BE8C-D8F1E8E3D835)), the easiest way to accomplish this is to edit the link text to just have words to help distinguish them from each other: "View details for claim #600392913" or "View details for step 2" etc. If that's not practical for design reasons, the next-best option would be to use an `aria-label` to ensure screen reader users get that unique text. But if you can avoid ARIA here I would recommend it!
- **Consider:** There was some discussion in the call about the placement of the tag on the cards. I think @joshkimux summarized the accessibility perspective here pretty well. My slight preference would be for the tag to be placed above the heading as Allison suggested, but semantically grouped inside the `h` element following the "eyebrow" pattern, eg. `<h3><span class="tag">Tag Text</span><span class="heading-text">Whatever the heading is</span></h3>`. But that's just a slight preference and would need to be run by someone from content since it changes what the heading is and the order content is announced to screen reader users. Otherwise, I think the placement you currently have works.

**Comment by skylerschain** [comment]
Thanks Brian. 

- Yes, I'm working with @joshkimux on updating the upload pattern on the Files tab so that there is no disabled state button!
- Roger that regarding unique links. For the Overview of claim process page, I have a new version with unique strings for each step. For the "View details" link on the claim card, I'm leaning towards using an `aria-label`. Reason being, we are moving away from Claim IDs for this first version (they didn't test well) and so will be using the "submitted on" date to establish unique headers for a11y purposes. Putting the full "submitted on" date in the "View details" button I don't think will work.
- I think it makes sense to move the tag up to an eyebrow, since that seems to be the standard pattern in the design system. If for some reason including it semantically in the header like you suggest won't work, we can revert to the initial design.
