### ISSUE TITLE
Midpoint Review - IA Feedback - Veteran Facing Forms, 40-0247: Presidential Memorial Certificate Form

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#61571]
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions
- Over time, I'd love to better understand the statistics and use cases for non-Veteran caregivers logging into Va.gov with an account to complete tasks like this. It is an under-studied area.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

**Must:** Use updated privacy policy component so that it indicates that opening that link will be external.
**Should:** Discuss the additional two question screens about the Veteran's demographic background information (gender and race) with Sitewide CAIA. I struggle with these because this is a repeatable form, and folks filling it out may not correctly assess those pieces of information about the Veteran. Will multiple people potentially enter different data about the same person? Does that matter? 
**Consider:** On the intro page, and potentially in the subtitle, think about describing the purpose of the form/ what it does. I had to Google this! There is a [legacy content page here](https://www.cem.va.gov/facts/Presidential_Memorial_Certificates.asp) that does a great job describing the Presidential  Memorial Certificate form. I think some of this language would be very useful, both for comprehension and SEO.

**Comment by rachelshearerux** [comment]
Re: the demographics data collection question, we passed along the feedback to SWCAIA who let us know further review is needed. We'll keep things as they are while they dig in deeper to clarify guidance around this and future places where these show up.
