### ISSUE TITLE
updates to review instance page

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#61577]
### Description
recommend the following additions:

- call out that users will likely need to disable CORS (e.g., use the CORS E extension on firefox) to utilize most/any functionality in a review instance
- note that users will likely need to set `oauth=false` in their URL bar when signing into a review instance (without that change, clicking on any of the identity providers in the sign on modal results in various errors)

### Relevant URLs
https://depo-platform-documentation.scrollhelp.site/developer-docs/review-instances

### Which type of team are you on? (Platform team, VFS team, or Leadership)

OCTO

**Comment by vbellissimo** [comment]
Hi @batemapf , thanks for your request. We're taking a look for next steps.

**Comment by vbellissimo** [comment]
Hi @batemapf , the updates requested have been made. The changes will reflect live on the site after 3:30pm ET
