### ISSUE TITLE
Adding Adrian Brewster to DSVA Slack

### ISSUE THREAD

**Issue by BerniXiongA6** [department-of-veterans-affairs/va.gov-team#61588]
# Description

Please add Adrian Brewster as a full member of the DSVA slack. He is the new Delivery Manager for Authenticated Experience team, who is replacing Berni Xiong (Berni will complete a revised Slack Request to edit her new team assignment, under separate cover).

Email: adrian.brewster@agile6.com
GitHub handle: @adrian-brewster (https://github.com/Adrian-Brewster)

Please add him to #accountexp-authexp, #vfs-all-teams, #vfs-change-announcements

**Comment by KevinMHoffmanUSDS** [comment]
Adding now

**Comment by KevinMHoffmanUSDS** [comment]
Done!
