### ISSUE TITLE
[SCREENREADER]: Links in map attribution SHOULD open in new tab to aid in error recovery

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#6158]
# [508-defect-2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)

```diff
! Leaflet-Mapbox issue
```

**Feedback framework**
- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

While testing the Mapbox upgrade with the screen reader I heard the Zoom In Zoom Out controls and attempted to tab back from the attribution text to test the controls. However, the Leaflet link was activate. I didn't know how to get back, so I tried closing the window, expecting the VA Facility Locator to be in the browser tab below. However, it had opened in the same window and I was lost. For these attribution links, they **SHOULD** them open in a new tab so the facility locator remains readily available.

```diff
- "Must" for if the feedback must be applied 
! "Should" if the feedback is best practice 
+ "Consider" for suggestions/enhancements 
```

## Point of Contact

**VFS Point of Contact:** Jennifer

## Acceptance Criteria

As a screen reader user, I want to interact with the relevant content on the page and easily recover from mistakenly accessing less or not relevant content (such as technology attribution links).

## Environment

* Operating System: any
* Browser: any
* Screenreading device: any
* Server destination: production

## Steps to Recreate

1. Enter `https://www.va.gov/find-locations` in browser
2. Start screen reading device listed in Environment
3. Try to activate the Zoom In or Zoom Out a couple of times
4. Verify that it is very easy to hit the wrong link, and recovery from an error would be valuable

## Possible Fixes 

Have the attribution links open in a new tab, as they are a diversion from the primary purposes of using the facility locator

**Comment by mmiddaugh** [comment]
New Mapbox icon does open a new tab.

**Comment by mmiddaugh** [comment]
This issue is ready to be validated @joshkimux @tlei123, whenever you are able.

**Comment by tlei123** [comment]
@joshkimux , I'll leave this one to you, but feel free to ping me if you get swamped.

**Comment by joshkimux** [comment]
@mmiddaugh Validated 👍  

A couple of questions though:
- I remember that you mentioned the possibility of removing the mapbox icon from the tab order, is that still in the pipeline? It may be a better alternative given that it eliminates the chance of being ejected from the experience.
- The "search this area of the map" button only manages focus on the first time the user uses the zoom in and zoom out buttons. Afterwards, it is no longer a part of the tabbing order which would be a launchblocker. Has this been documented?

https://user-images.githubusercontent.com/14154792/103006333-2ea7d680-4500-11eb-9a8c-b26e26ff578f.mov

**Comment by mmiddaugh** [comment]
Thank you @joshkimux 
Both comments are topics of an upcoming meeting with you and are documented in separate issues. I will close this now.
