### ISSUE TITLE
Create agendas for meetings between VFS teams and specialists

### ISSUE THREAD

**Issue by emilywaggoner** [department-of-veterans-affairs/va.gov-team#616]
## User Story
As a VSP Accessibility, Content, Analytics, or IA specialist, I need agendas and talking points prepared so that I can set up VFS teams for successful collaboration, set expectations appropriately, and communicate best practices when I meet with them.

As a VFS team, I need to meet with VSP specialists so I can understand the expectations of how we'll work together, understand how the review processes work, and set up the appropriate cadence for communication.

## Goal
Have agendas and talking points created for when VFS teams meet with Trevor, Peggy, Mikki, and Nedie. VFS teams are instructed to schedule 30 minute meetings with them after they have gone through the full-team and practice area breakout onboarding sessions.

## Acceptance Criteria
- [x] Agenda created for Accessibility
- [x] Agenda created for Content
- [x] Agenda created for IA
- [x] Agenda created for Analytics
- [ ] Agendas reviewed by respective specialists
- [ ] All agendas stored in Github

## Definition of Done
- [ ] All AC complete
- [ ] Reviewed with DSVA

**Comment by emilywaggoner** [comment]
Here is a first draft of the agendas for the practice area meetings (I've also added a section for Analytics too):

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/Platform/Onboarding/agendas-talking-points-specialist-meetings.md

Tagging in @peggygannon, @mnorthuis, @1Copenut, and @nedierecel to ask for your review on each of your respective sections in the document above. Feel free to edit the document directly, add questions specific to your practice area, etc. Also if you don't mind, leave a note here when you're ready to call yours done. Thank you all!

**Comment by 1Copenut** [comment]
@emilywaggoner This looks great! No changes for 508 section.

**Comment by andreahewitt-odd** [comment]
@emilywaggoner Did you get any other feedback on this? Can we work together to get it through the pipelines?

**Comment by shiragoodman** [comment]
@emilywaggoner @andreahewitt-odd  - this is listed as In Progress. Is it still? It's showing up on my teams board and I don't think anyone is currently working on this. Should we move to backlog or close out?

**Comment by shiragoodman** [comment]
@shiragoodman
