### ISSUE TITLE
SPIKE: Design Implementation for Phase 1

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#61609]
## Background
We will be taking a phased approach to implementing Unified Check-in. We will start with swapping out the landing page for both Pre-Check-in and eCheck-in so that they are consistent in design and function.

[Link to the Unified Check-in WF](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/0EC89917-F949-4461-A7B3-32A5201FD2A2/canvas)

[Link to new Pre-Check-in landing page in the WF](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/uuid/058808E2-6278-41C8-B9D4-33C61B3B85B1)

[Link to new Check-in landing page in the WF](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/uuid/DB61800E-7440-4F6D-9ADD-70A4FB604881)

- NOTE: We will **NOT** be implementing the following in this phase (per the wireframe)
     - Display confirm/check-in status for each upcoming appointment
     - Allow the execution of a task NOT related to the appointment for the link clicked

## Questions
Will we have a dependency on VeText

## Tasks
- Design the implementation for Phase 1
- Create FE & BE tickets as necessary to complete Phase 1 and attach to this [Epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/61390)

**Comment by benbrasso-agile6** [comment]
Phase 1 (although it's labeled as Release 2) https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/F05730C4-9E76-4B1D-AEA0-63CEC7E61175/canvas#Version

**Comment by brianseek** [comment]
@loripusey Can this be moved to closed, or was there something more to this effort?

**Comment by loripusey** [comment]
yes, closing
