### ISSUE TITLE
Adding Stefan Tanenbaum to DSVA Slack channels

### ISSUE THREAD

**Issue by huggins-va** [department-of-veterans-affairs/va.gov-team#61607]
# Description

Please add Stefan Tanenbaum as a multi-channel user to the follow channels: 

- vaapi-platform 
- team-honeybadgers-support 
- team-tornado

Stefan Tanenbaum (stanenbaum@rise8.us) is re-joining Lighthouse and will support both Honey Badgers and Tornado teams. 

Thank you! 

## Sample Descriptions 
- Please add [_insert email_] as a single-channel guest to [_channel name_].
- Please add [_insert email_] as a multi-channel guest to these channels: [_channel names_].
- Please add [_insert email_] as a full member.
- Please change the status of [_slack username_] from [_current status_] to [_desired status_]

**Comment by KevinMHoffmanUSDS** [comment]
@huggins-va They have been invited and added to #general. If those are private channels, please have members of those channels invite Stefan once he joins, as Slack admins cannot see private channels.
