### ISSUE TITLE
Design Intent  - IA Feedback - Identity Core Team, Terms of Use (Terms and Conditions)

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#61619]
## VFS actions
- [x] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions
- Thank you so much for including the current state! That's really helpful to see.
- Please mock this up on mobile; I am not sure that this will be able to reasonably fit "above the fold" on a reduced screen size. 
- Is it correct that new accounts and existing accounts that have not yet accepted the terms of use would both get send to the Terms of Use page immediately upon login? Can we prevent them from navigating off of the page?
- If the Terms of Use get updated or changed in the future, how will that work for users? 

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- **Must:** the "Cancel" CTA is navigational, so it must be a link (not a button)
- **Must:** Please [submit an intake request ticket with the Sitewide CAIA team](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=RLHecht%2C+coforma-terry%2C+kristinoletmuskat%2C+laurwill%2C+sara-amanda&labels=sitewide+CAIA%2C+sitewide+content-product+support%2C+Sitewide+IA%2C+sitewide+content%2C+sitewide+accessibility&projects=&template=sitewide-content-intake-form.md&title=%3CType+of+Request%3E+from+%3CTeam%3E) to 1.) get help from content to create a new static content page that can support the message we need to communicate to users that click "Cancel." Also request to work with IA to determine where that page will live on Va.gov.
- **Must:** If you decide to keep the links to the PDFs, those should probably indicate to users that they will open in a new tab. See the [privacy agreement component](https://design.va.gov/components/form/privacy-agreement) in the Design System as an example of what that looks like. 
- **Should:** The bottom section with the heading "Using VA Benefits if you don't accept" should be above the "Agree" button. Users should be able to review that before making a decision.

**Comment by asg5704** [comment]
@sterkenburgsara I'm going to summarize based on your recommendations and comments.

## Thoughts
- [ ] "Above the fold" might not be feasible in mobile-screens
> I agree that it might not be feasible on mobile-screens. I am working based on accessibility (a11y) feedback and asking for guidance around the Fixed-height scrollable content and whether or not we want to breakdown each section of the Terms of Use into an Accordion.  That way we can save on screen real estate in both mobile and desktop.
- [ ] Will this redirect new + existing users to this page after sign? Can we prevent users from navigating away?
> Yes, it will require new and existing users to navigate to the Terms of Use page. I will have to look at which version of `react-router` we are using, but I will preemptively say "yes" we should be able to prevent users from navigating away, or if they do navigate away we should be able to sign them out. I will have to verify this one.
- [ ] Terms of Use get updated or changed in the future, how will that work for users?
> Short answer is I'm not sure we are still coordinating with all parties involved. There are still talks on whether on the following actions: Minor changes = email to users about the updates, Major changes = require users to re-accept Terms of Use.

## Feedback
- [ ] Cancel button
> The "Cancel" will be a button.  The "Cancel" button will make an API request to the user accepting or declining the Terms of Use, log them out, and finally redirecting them to the "We signed you out because..." page.
> If IA, Content, and Accessibility all agree that the "Cancel" should still be a link that's fine however we should also update the "Sign in buttons" in the Sign in modal to also be links AND design.va.gov should also be updated to take a strong stance on it as well so we are consistent across the design ecosystem.
- [ ] Intake form for CAIA
> I'm not sure if this will be a static page as there will need to be multiple API requests to handle user interactions. We also already have an existing "Terms of use" page that lives on VA.gov (see https://www.va.gov/health-care/medical-information-terms-conditions for reference)
- [ ] PDF as links
> That is a good callout for the PDF links. Accessibility also brought up that links should not live within the checkbox labels due to cognitive overload and misinterpretation by the user concerning the primary action. I brought up to accessibility that as it stands right now, the checkboxes are not a hard requirement and if we have sufficient enough data to support it, we might be able to remove them completely.
- [ ] Using VA benefits if you don't accept
> Accessibility also brought up this point as well.

This is what I shared with accessibility based on their feedback. Take note that I removed the checkboxes pending accessibility & your recommendations on them.

![Based on a11y](https://github.com/department-of-veterans-affairs/va.gov-team/assets/67602137/bc23e6a1-76ff-458b-9791-e781f2015728)

**Comment by sterkenburgsara** [comment]
hi @asg5704 this is super fantastic follow-up. I am assuming you wanted me to read through and check the boxes above, but holler at me if not :-)  You answered most questions, here are remaining thoughts:

* **Cancel button** - Interesting! Thanks for explaining this one. Using "cancel" for a button is a bit of a departure from other instances I can think of for "Cancel" on VA.gov. A different term for that button (e.g. "Decline") that doesn't compete with mental models for what "Cancel" may mean could be more clear to end-users. If you do go with "Cancel," consider testing with that term and asking specific questions around it to make sure it aligns with user expectations.
* **CAIA intake ticket** -  Despite not needing a unique static page to support the "Cancel" flow, I'd still recommend working with CAIA for content support on this to get the language just right. Will you change the URL, or will that stay the same? CAIA IA team may need to know if you plan to place a redirect.

Thanks again!

**Comment by aparsley** [comment]
Looks good, keep up the good work.
