### ISSUE TITLE
Add filter to clinic selection to prevent direct scheduling of video visits

### ISSUE THREAD

**Issue by JRRoof** [department-of-veterans-affairs/va.gov-team#61614]
## Description
Facilities are not supposed to allow direct scheduling of video visits.  A large number of sites have clinics configured this way.  When a veteran schedules in one of these clinics, the corresponding video visit does not get created.  When a veteran views the details of an appointment created this way there is no link available to join the video visit.  Kay Lawyer has requested that we filter out these clinics so veterans can not select them.  These clinics can be identified by their secondary stop code.  Kay is to provide a list of all secondary stop codes to filter out.

[VAOSR-6861: Filter out clinics that allow direct booking and have stop codes in predefined list](https://issues.mobilehealth.va.gov/browse/VAOSR-6861)

---

## Acceptance Criteria
No feature flag is needed for this enhancement

Given a veteran is scheduling a direct appointment for any type of care
When the secondary stop code of the clinic is {179, etc.} -  Kay Lawyer to provide complete list of secondary stop codes
Then don't display these clinics to the veteran as an option.
And page content matches the [copy doc](#) 
And page design matches the design spec

### Design Assets
All spec copy is FPO. Use copy in copy doc.

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ldelacosta** [comment]
There's a BE dependency to address this issue. Here's the JIRA ticket to track the effort: [VAOSR-6861](https://issues.mobilehealth.va.gov/login.jsp?permissionViolation=true&os_destination=%2Fbrowse%2FVAOSR-6861&page_caps=&user_role=)

@young1205 - just giving you a heads up. You can check updates from BE team during the SoS meeting or reach out to Jeff.

**Comment by JRRoof** [comment]
BE work was completed and working as intended
