### ISSUE TITLE
Design Intent - Design Feedback - Identity Core Team, Terms of Use (Terms and Conditions

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#61617]
## VFS actions
- [x] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- Looks like you are heading in the right direction. User flows and mobile would be helpful, love the "current" state.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- **Consider**: Look at [additional info](https://design.va.gov/components/additional-info) and [expandable alert](https://design.va.gov/components/alert-expandable) components and see if your use case fit the guidelines. It may save space on the page.

**Comment by allison0034** [comment]
Hi @asg5704 ! This was just "consider" feedback. Meaning it may be something to look into. I was suggesting it to help you save space and possibly be able to move the "If you decline..." info above the button. I believe you will want that info to be above the buttons for accessibility reasons, but confirm that.

You are actually using a [default alert](https://design.va.gov/components/alert), not the [additional info](https://design.va.gov/components/additional-info) or [expandable alert](https://design.va.gov/components/alert-expandable). The default alert will not save you space.

**Comment by asg5704** [comment]
Thank you for the clarification @allison0034. My UX team and I were still working through whether we want to use an expandable alert or a default alert - we're still not sure if we want to hide the fact that users will be logged out.

**Comment by aparsley** [comment]
Thank you for the clarification and attaching feedback.
