### ISSUE TITLE
GIDS: Create Interface to Manage CalculatorConstants

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#6163]
As an EDU team member, I need the ability to manage the calculator constants within GIDS so that I can manage them without having to use a CSV.

## Assumptions:
1. The upload / export functionality will remain as a backup for the time being.

## Acceptance Criteria
1. There is a "Calculator Constants" option in the header menu/nav bar at the top of the page
2. When clicking "Calculator Constants", the user is redirected to a new page that contains a form for managing the calculator constants.
     - The page title is: "Calculator Constants"
     - There is a description of how the data is used.
3. The form displays a read only view of the following data:
     - Constant Name
     - Constant Description (See supporting artifact 2)
4. The form allows the user to edit the following data:
     - Constant Value
5. The calculator constant meets the the following criteria:
     - Is required
     - Is a number (need to differentiate fields between integers v. floats)
6.  The user can cancel editing the form and it returns them to the dashboard.
7.  The user can save the form edits and they are persisted.
9.  If there is an error, no changes are made to the data.

## Notes
1. Need to confirm that type of number ( integers v. floats) does not need to be specified in validation. 
2. Brian Grubb is researching where Constant Description comes from. 

## Supporting Artifacts:
1. Mockup:
![manage_calculator_constants](https://user-images.githubusercontent.com/48260534/75266093-da3ca900-57bf-11ea-85aa-c7b32b7dbb8b.png)
2. Calculator Constants with Description:
[CalculatorConstant.txt](https://github.com/department-of-veterans-affairs/va.gov-team/files/4251318/CalculatorConstant.txt)

**Comment by hughes-dustin** [comment]
branch: bah-6163
PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/600

**Comment by desireeturner** [comment]
We're requesting additional calculator constant descriptions from EDU today for those missing from supporting artifact 2 included above.

**Comment by sonntag-adam** [comment]
AC 1/2/3
![Screen Shot 2020-03-12 at 10.24.12 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/1e18e3b4-fe89-4d98-b928-348a14691362)
##
AC 4
![Screen Shot 2020-03-12 at 10.26.07 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/ea4468e6-c30f-4c26-a274-916e9a2d8798)
##
AC 5 required when trying to save blank value/ only values allowed 1234567890-e.
![Screen Shot 2020-03-12 at 11.29.44 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/5ad9e593-b8d2-4932-8a40-d898052703e1)
![Screen Shot 2020-03-12 at 11.34.55 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/1947ba66-64bf-40a4-8865-0fbee7f247a7)
##
AC 6 no screenshot applicable. Selecting Cancel on by buttons takes you back to dashboard without saving
##
AC 7 screenshot for AC5 shows the saving of changes made
##
AC 8 if an error occurs no successful message displays and no changes are made

**Comment by sonntag-adam** [comment]
Testing passes https://dsvavsp.testrail.io/index.php?/runs/view/210&group_by=cases:section_id&group_order=asc

**Comment by sonntag-adam** [comment]
In staging. Closing story.
