### ISSUE TITLE
[FE/QA] FE Discovery: Gaps in automated testing

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#61639]
As a team member, I would like to identify any gaps in Frontend test coverage so that we can ensure that we always release defect-free software. 

- [ ] Review Front End test library with devs and QA
- [ ] Identify any large or medium-sized gaps in test cover
- [ ] Document these gaps 
- [ ] Come up with plan for remediation (work with Alex to come up with User Stories)

**Comment by hdjustice** [comment]
This is being accomplished within other projects/FE tickets
