### ISSUE TITLE
[Data/BE] Discovery: Answer questions from Ambroja's email

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#61647]
I'm not going to do an "as a user" for this, and instead say that Ambroja (HEC stakeholder) responded to Patrick's email with some questions about how things work currently. I think it would be good to have the team dive into some of these things (I think the answers for some will be straightforward), and then respond back to her. Let me know if you have any questions or need more context! 

Questions:
- [x] --If a user doesn’t have a MHV, Login.gov, or ID.me account how does VA.gov authenticate information for Veteran?
- [x] --What is the current data of anonymous application usage vs. creating an account to use the 1010EZ?
- [x] Respond to email
- [x] **Success: We respond with answers to all of Ambroja's questions**

**Comment by luis-simauchi** [comment]
![Data_Discover_ Answers 2.PNG](https://images.zenhubusercontent.com/6421ffdd55816016e6d0ec89/428b944b-dba4-4289-b32e-c49fc3cc50ff)

**Comment by luis-simauchi** [comment]
One hypothesis:
logged in folks can save and return to continue the application at their leisure.
