### ISSUE TITLE
[BE/QA] EZ BE Discovery: Gaps in automated testing/ways to improve

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#61640]
As a team member, I would like to make sure that all backend tests are correct and thorough so that we continue to release defect-free software. 

- [x] Review Back End test library with devs and QA
- [x] Identify any gaps in test cover
- [x] Document any areas for improvement 
- [ ] Come up with plan for remediation (work with Alex to come up with User Stories)
- [ ] **Success: The team has reviewed the EZ BE tests and has identified any areas for improvement, asked questions about how they work, and generally feel more comfortable with the application**

**Comment by JoshingYou1** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Automated%20Testing%20/Ticket%20%2361640%20-%20EZ%20BE%20Discovery:%20Gaps%20in%20automated%20testing%20(ways%20to%20improve).md
