### ISSUE TITLE
Simplecov bug(s)

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#6164]
## What happened?
When I go to view [simplecov results on Jenkins ](http://jenkins.vfs.va.gov/job/testing/job/vets-api/job/master/2379/artifact/coverage/index.html) I see a page without js/css
## Specs:

- Browser: chrome 

## Steps to Reproduce
go to http://jenkins.vfs.va.gov/job/testing/job/vets-api/job/master/2379/artifact/coverage/index.html in chrome.  
<img width="1665" alt="Screen Shot 2020-02-25 at 11 28 38 AM" src="https://user-images.githubusercontent.com/19188/75268028-f858d800-57c4-11ea-8d42-03a452dbfe8c.png">

## Desired behavior
simplecov html page works with .js & .css

I suspect that there is one or more issues.  The first is best described by this notice in the console.
`A cookie associated with a cross-site resource at http://jenkins.vfs.va.gov/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.`. This issue manifests when http://jenkins.vfs.va.gov/job/testing/job/vets-api/job/master/2379/artifact/coverage/assets/0.12.0/application.css is called from the html page, but not when you navigate directly to that url.

But why have one problem when you could have two?  After the first issue is addressed, s[implecov's changelog](https://github.com/colszowka/simplecov/blob/master/CHANGELOG.md#0184-2020-02-24) makes it sound like upgrading may be necessary to get some bugfixes.

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by annaswims** [comment]
😢 Why have one problem when you could have several?

If I change my same-site cookie preference in chrome I get further, 
<img width="1097" alt="Screen Shot 2020-02-26 at 11 46 42 AM" src="https://user-images.githubusercontent.com/19188/75367539-7cc35d80-588e-11ea-8471-0f8d099ed2d8.png">
but I see  `Blocked script execution in 'http://jenkins.vfs.va.gov/job/testing/job/vets-api/job/jp%252Fupdate-simplecov/1/artifact/coverage/index.html' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.`

**Comment by johnpaulashenfelter** [comment]
This is fixed on CircleCI, which is probably good enough for now.

https://app.circleci.com/pipelines/github/bkjohnson/vets-api/38/workflows/4c614cfc-7584-43ab-93d4-c12bd946b8af
