### ISSUE TITLE
Qualitative Data Request

### ISSUE THREAD

**Issue by nnicholas7** [department-of-veterans-affairs/va.gov-team#61655]
### Data Type Requested

User Surveys

### Date Range Start

03-16-2023

### Date Range End

05-15-2023

### Product Name(s)

21-526ez form

### Product Description

The 526 form is the form veterans use to apply for disability compensation. In the digital experience, veterans will answer questions to determine eligibility, select injuries/ailments to claim, upload evidence to support their claims, etc. The form is quite long. The feedback button in staging currently presents a survey that gauges whether the user completed the task they set out to do, what was that task , and their overall satisfaction.

### Survey URL(s), key term(s), case category or type

Form entry URL - https://www.va.gov/disability/file-disability-claim-form-21-526ez/

### File Delivery Format

One file, different tab for each term/URL

### VA Email Address(es)

nichole.nicholas@va.gov

### Add Assignee and Labels

If not already done so, please ensure @ianMcCullough-ob is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by newworld2616** [comment]
Hi, I have shared the requested data, please verify once you receive it. Thank you!
