### ISSUE TITLE
[TFMod] Helm Install Wait for Cluster Ready

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#61654]
- The Helm Install module is not waiting for the cluster to be ready
- This can create timeout errors during deployment

![image.png](https://images.zenhubusercontent.com/622146ffd0422cdb4d9fdd52/a342d7a1-758f-4f2e-9ec9-358afaf4b59d)

**Comment by npeterson54** [comment]
Nice to have, low priority

**Comment by ph-One** [comment]
I have not seen this happen since seeing it this one time. Will create a new ticket if it comes back up.
