### ISSUE TITLE
527EZ Incorrect Field Names for Adding Dependents

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#61676]
#### What I expected to happen
1. When you add dependents, the fields should say: "Dependent first name", "Dependent middle name", "Dependent last name"

#### What actually happened
1. When you add dependents, the fields for the dependent say: "Your first name," "Your middle name," and "Your last name.

#### Screenshots or Supporting Evidence
See attached.

#### Severity of the issue
- [ ] High severity
- [ ] Medium severity
- [X] Low severity

![527EZ Dependent Info.png](https://images.zenhubusercontent.com/64820e3ee0808dee239ecb52/4ea03c83-9af3-4081-bd4b-4231b908dae9)

**Comment by steele-lm** [comment]
@vbellissimo I came across this old ticket in our backlog. Can you confirm the new pension designs addressed this issue? Thanks!

**Comment by vbellissimo** [comment]
@steele-lm we actually did address this! So it can be closed.
