### ISSUE TITLE
Profile | Investigate Sentry Address Validation Errors, and add additional reporting info 

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/va.gov-team#61671]
## Issue Description
[A sentry error around validation has been occuring.](http://sentry.vfs.va.gov/organizations/vsp/issues/17162/events/195e61a9572840908c574d02e9222e5c/?project=4)

Frequency is not super high, but has been happening enough that it warrants looking into further. Also there is supposed to be a section of 'context' captured that shows the response data in the sentry event, but it looks like it is set to `null` so it isn't giving us any usable information on why the error occurred.

My suggestion would be to try and capture the response as well as the error itself that is caught.

Code location for the sentry data capture:

https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/user/profile/vap-svc/actions/transactions.js#L386 

## Front end tasks
- Investigate errors further and see if any details are getting reported that could indicate the issue with the api
- Update sentry calls to report more info if possible
- Monitor sentry for this error once new reporting is available to determine next steps with this issue.

## Acceptance Criteria
- [ ] Sentry is reporting detailed information around the error `error parsing address validation response`

**Comment by adamwhitlock1** [comment]
![Screenshot 2023-07-11 at 9 00 08 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8332986/ed4dd4ba-ca68-4f18-bea7-b97f4d8b9df5)

Here are all the main details on the error as seen in Sentry. My initial thought is that if we can capture some additional context to send to sentry then we may be able to track down what specifically is happening.

Ideally we would have an extra section at the bottom of the sentry error screen like this example below (from a different profile error where we capture extra data):

![Screenshot 2023-07-11 at 9 05 08 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8332986/98d11df2-bc96-4651-9fc3-feb8711b86f7)

**Comment by adamwhitlock1** [comment]
There is a bit more data within the Datadog metrics and in looking at the last month, I can see that the address validation endpoint has a failure rate of less than 0.5% so that is a good thing.

An example of a datadog report for just the last week can be viewed at [this link (requires VA datadog account)](https://vagov.ddog-gov.com/logs?query=env%3Aeks-prod%20%40http.url_details.path%3A%2Fv0%2Fprofile%2Faddress_validation%2A&agg_q=status%2Cservice&cols=host%2Cservice%2C%40http.status_code%2C%40payload.user_uuid&index=%2A&messageDisplay=inline&sort=time&sort_m=%2C&sort_t=%2C&spanID=299573421812391432&stream_sort=time%2Cdesc&top_n=10%2C10&top_o=top%2Ctop&viz=stream&x_missing=true%2Ctrue&from_ts=1691550827737&to_ts=1692155627737&live=true)

The largest number of errors are `Unprocessable Entity` errors that we can research more, but we would need to use the `user.uuid` to look into particular user's addresses to see if there is any correlation like foreign addresses or really long addresses that might cause an error. That would require production database access, which I don't have but BE engineers may be able to access.

I will follow up with Tom, but I would say that because datadog has actual error response data, and has more details, that it should be the source of truth over Sentry.

I'd recommend we close this ticket out as it isn't really requiring any extra FE work and look at BE records and go from there.

**Comment by mtcA6** [comment]
@adamwhitlock1 @tpharrison could you all write the next story for this so we can get to the bottom? Closing this out ahead of sprint planning
