### ISSUE TITLE
[Terraform] Remove providers from all modules

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#61674]
- Individual modules should not have any providers defined
- Only the top-level `terraform/tiers/terragrunt.hcl` should have `provider` blocks
- Helps enforce consistency across modules
- Keeping modules in sync on their providers helps to keep modules from lagging behind

**Comment by ben-allen-oddball** [comment]
Bringing into sprint.

**Comment by ph-One** [comment]
Looks like it's just `eks-cluster` and `helm-install` that have providers

```
modules/eks-cluster/auth.tf:provider "kubernetes" {
modules/helm-install/versions.tf:provider "helm" {
tiers/terragrunt.hcl:provider "aws" {
```
