### ISSUE TITLE
Business intake form for VERA Appt Confirmation and Reminders

### ISSUE THREAD

**Issue by sbainazarov** [department-of-veterans-affairs/va.gov-team#61688]
## Your Details
1.  **Your Name**
​ Suleiman Bainazarov
2.  **Business Line**
    (ex., claims, health, etc.)
VA VERA
## Notification Details
1.  **Notification type**
    (email, text/SMS, or both)
​​SMS
2.  **Please describe your use case.**
    (This is your chance to tell us an overview of your plans.)
​Automatic notification for VA meetings.
3.  **What actions can the user take based on the notification they receive?**
    (ex., view secure messages, fill out a survey, schedule an appt, etc.)
​Attend a Teams Meeting
4.  **What is the desired business outcome?**
    (ex., fewer skipped appointments, less call center volume, etc.)
​Fewer missed meetings. 
5.  **What system will kick off the notification? Please note the system should be inside the VA or have an ATO.**
    (ex., BVA hearing reminders are kicked off from Caseflow)
​ VA VERA using Salesforce Flow
6.  **What will trigger the notification?**
    (ex., clicking submit, status updates for claims, appointment reminders, new services available)
​2 hours before the scheduled meeting. And on creation of an appointment via the VERA public community site.
7.  **Provide sample content per notification type, if you have it.**
    Please note we collaborate with all of our users on their content to ensure it meets standards.
​
8.  **Has a Privacy Officer (PO) seen and approved the content? If not, do you know who your PO is?**
    (ex., PO has seen the content but it is not approved)
​Not sure
9.  **Would you prefer to provide contact information for the recipients or would you rather VA Notify look this up for you by Veteran ID? If by ID, please let us know what identifier is used in your system.**
    (ex., VAPROFILEID, PID, BIRLS, ICN, etc.)
​We provide contact information
10.  **Do you currently capture communication preferences related to this notification? If so, please describe.**
    (ex., opt in for claim status updates via email or text)
​SMS Notification prompts are part of the new build for VERA
11.  **What is the anticipated volume of notifications per day, week, month?**
​Not sure
12.  **When does this notification need to be in production?**
About 6 months from now.

**Comment by sbainazarov** [comment]
I am a contractor working on VA Vera phase III. We were approved to use VA Notify and I wanted to get access to the app and maybe schedule a meeting. Thank You

**Comment by mjones-oddball** [comment]
@sbainazarov Thank you for reaching out! I also saw your email - apologies for the delay. I've updated your intake form to include the form questions so we could identify what information we still need.

Questions:
1. Can you please provide screenshots of the SMS opt in/phone number collection process you all will be incorporating in VERA?
2. Do you integrate with VA Profile for contact information?
3. We will need some estimates on volume to identify the right type of sender to use. Are you able to provide a rough estimate or average for how many meetings you all plan to notify on in the future per day and/or month?
4. Is your application behind the VA network? Where is it hosted?

Please let me know what day/time works best for a 30 minute sync on next steps:

- 7/25 4 pm - 4:30 pm ET
- 7/26 1:30 pm - 2 pm ET
- 7/28 2:30 pm - 3 pm ET

Agenda:
- Use Case Details
- Type of sender phone number needed
- Preferences and contact info/opt out management

CC @bevnobev

**Comment by mjones-oddball** [comment]
@sbainazarov Can you please let me know what day/time works best and who you'd like me to include from your team? I know everyone is busy so I want to make sure we get time on the schedule :)

- 7/25 4 pm - 4:30 pm ET
- 7/26 1:30 pm - 2 pm ET
- 7/28 2:30 pm - 3 pm ET

**Comment by sbainazarov** [comment]
@mjones-oddball Hey thanks for your hard work on this. The team had to move some dates around and 7/26 is no longer viable. Can move the meeting to 7/28 2:30pm?

**Comment by mjones-oddball** [comment]
@sbainazarov I'll get back to you! Friday doesn't work but I'm looking to see if we can offer any Monday times.

**Comment by sbainazarov** [comment]
Monday 7/31/23 1pm or 3pm is best. Thank You

**Comment by mjones-oddball** [comment]
@sbainazarov Awesome, moved to Monday at 3.

**Comment by mjones-oddball** [comment]
Launched May 23, 2024
