### ISSUE TITLE
Datadog RUM site for 526EZ forms

### ISSUE THREAD

**Issue by va-albers** [department-of-veterans-affairs/va.gov-team#61680]
This is a tracking issue for the addition of a 526EZ RUM for for DSVA Datadog.  

It is not necessary for anyone else to actually add the RUM app - Steve can do this.  We are tracking this for awareness/comment on adding new RUM tracking

**Usage:**  Per DOMO, the 526 application currently averages 82,264 sessions per week, which at $1.80/1000 sessions would cost approximately $150/week.  This appears to be comparable to the current Patient Check-in session count and 2.5 times the current traffic for 10-10EZ.  We will set an initial sampling rate of 10% (or $15/week) to manage intake costs based on recommendations.  This may be revised upwards after review.

** Pilot status**  
- The team understands that this is a pilot effort that may be ended after review
- The Benefits team is available for discussion prior to launch and and/or review of metrics after an initial launch, and we are flexible on items such as sample rate.

**Comment by micahaspyr** [comment]
Initial Discovery:

- datadog/browser-rum is v4.22.0 which is fairly up to date, with the latest being 4.45.0
- Datadog docs state that a monolithic application should only have one service name, which the useDatadogRUM.jsx file is configured to show the service as 'patient-check-in'.  Not sure if this is something to look into too deeply but just a reminder.
![Screenshot 2023-07-13 at 3 17 10 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/6454840/b5cbd505-5d60-4567-a09f-2efa913fa836)

**Comment by micahaspyr** [comment]
Looks like the heat maps feature requires a datadog package to be upgraded to > 4.40

**Comment by sortizsh** [comment]
Can you create a short video before you leave for vacation and DM to Sarah? Include 10% replay, environment variables,

**Comment by micahaspyr** [comment]
@va-albers it looks like datadog does NOT record any masked data when recording a session.  👍 
<img width="835" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/6454840/a1fea924-9d86-4f55-a69b-84b8307a8efa">

**Comment by austinjprice** [comment]
@austinjprice and @micahaspyr to review in meeting and record any potential PII issues

**Comment by micahaspyr** [comment]
Doc created for RUM.  It is zipped because it contains a video besides text

[Datadog RUM.zip](https://github.com/department-of-veterans-affairs/va.gov-team/files/12542774/Datadog.RUM.zip)

**Comment by micahaspyr** [comment]
For reference, I was asked by the 2346 team to pull some dd-privacy-mask out of their shared codespace as they're implementing RUM on their own now
