### ISSUE TITLE
[CAIA A11y Support]: Benefits and Claims, Dependents Form Audits: Forms 21-686c and 21-674

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#61685]
### What do you need support with?

...
Maintenance audit for forms 21-686c, 21-674, 21P-509

### When do you need this support by?

7/31/2023

### How urgent is this request?

A little urgent, we need this support before the date we provided above

### Supporting artifacts (if any)

- [Dependency Verification Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/dependents/dependency_verification)
- [Add/remove Dependents Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/view-and-update-dependents)
- [686 form flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1687976281975/2a9c6ca9ea6d955afa7977c777bbb72b15280903?sender=u0e8ac1d6d7681bb7e1b80558)
- [Ticket with a collection of old outstanding issues:](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60983)
- [Form 21-686c for Adding/removing Dependents](https://www.va.gov/find-forms/about-form-21-686c/)
- [Form 21-674 for school experience](https://www.va.gov/find-forms/about-form-21-674/)
- [Form 21P-509 for Statement of Dependency of Parent(s)](https://www.va.gov/find-forms/about-form-21p-509/)
...

### Who's on your team?

Team name: Dependents (Team Tree)
OCTO-DE product owner: Matt Self
Product manager: Laura Steele (Coforma)
Designer: Daniela Jones
FE engineer: Thomas Blackwell
Product/team Slack channel: benefits-ce-dependents_exp
...

### Do you have an accessibility champion on your team?

No, we don't have a champion (yet)

<hr>

## Audit Detail: View or change dependents on your VA disability benefits form
[Link to View or change dependents on your VA disability benefits form](https://staging.va.gov/view-change-dependents/)
### Product information

- [x] Team name, product name, and feature name have been added to the title of this issue.
- [x] Team label, product label and feature label (if applicable) have been added to this issue.

### Who completed the use of color and color contrast test?

@coforma-jamie

### Use of color and color contrast checks

- [x] All text of 20px or smaller has a 4.5:1 contrast ratio to its background (or better)
- [x] All text of 20px or larger has a 3:1 contrast ratio to its background (or better)
- [x] Non-text elements have a 3:1  contrast ratio to their background and to neighboring elements (or better)
- [x] Color is not the only way to distinguish links from other text (eg. links are underlined)
- [x] Any charts, maps, infographics, and tables convey all information without only relying on color
- [x] Content does not refer to color, especially when providing user instructions (eg. "Click the blue button")

### How did color testing go?

No issues found

### Who completed the axe scans?

@coforma-jamie

### axe checks

- [x] Each page has been scanned using axe (results shared below)
- [x] axe is integrated into your end-to-end testing

### axe DevTools scan results

| Axe results  | Page |
| ------------- | ------------- |
| 0 issues  | [Landing page](https://staging.va.gov/view-change-dependents/)  |
| 0 issues  | [Introduction](https://staging.va.gov/view-change-dependents/add-remove-form-21-686c/introduction)  |
| 0 issues | [Step 1: Options selection](https://staging.va.gov/view-change-dependents/add-remove-form-21-686c/686-options-selection) |
| 0 issues | [Step 2: Veteran's information / confirmation](https://staging.va.gov/view-change-dependents/add-remove-form-21-686c/veteran-information) |
| 0 issues | [Step 2: Veteran's information / contact info](https://staging.va.gov/view-change-dependents/add-remove-form-21-686c/veteran-address) |
| 0 issues | [Step 3: Add spouse / basic info](https://staging.va.gov/view-change-dependents/add-remove-form-21-686c/add-spouse) |
| 0 issues | [Step 3: Add spouse / marriage info](https://staging.va.gov/view-change-dependents/add-remove-form-21-686c/current-marriage-information) |
| 0 issues | [Step 3: Add spouse / marriage address](https://staging.va.gov/view-change-dependents/add-remove-form-21-686c/current-marriage-address) |
| 0 issues | [Step 3: Add spouse / current spouse marriage history](https://staging.va.gov/view-change-dependents/add-remove-form-21-686c/current-spouse-marriage-history) |
| 0 issues | [Step 3: Add spouse / veteran's marriage history](https://staging.va.gov/view-change-dependents/add-remove-form-21-686c/veteran-marriage-history) |
| 0 issues | [Step 4: Add child / basic info](https://staging.va.gov/view-change-dependents/add-remove-form-21-686c/add-child) | 
| 0 issues | [Step 4: Add child / child's status](https://staging.va.gov/view-change-dependents/add-remove-form-21-686c/add-child/0) |
| 0 issues | [Step 4: Add child / location](https://staging.va.gov/view-change-dependents/add-remove-form-21-686c/add-child/0/additional-information) |
| 0 issues | [Step 4: Add child / evidence](https://staging.va.gov/view-change-dependents/add-remove-form-21-686c/add-child-evidence) |
| 0 issues | [Step 5: Add student 18 to 23 / basic info](https://staging.va.gov/view-change-dependents/add-remove-form-21-686c/report-674) |
| 0 issues | [Step 5: Add student 18 to 23 / student's address](https://staging.va.gov/view-change-dependents/add-remove-form-21-686c/report-674-student-address)
| 0 issues | [Step 5: Add student 18 to 23 / school](https://staging.va.gov)
| 0 issues | [Step 5: Add student 18 to 23 / term or course dates](https://staging.va.gov/view-change-dependents/add-remove-form-21-686c/report-674-student-school-term-dates)
| 0 issues | [Step 5: Add student 18 to 23 / attend last term?](https://staging.va.gov/view-change-dependents/add-remove-form-21-686c/report-674-student-last-term-information)
| 0 issues | [Step 6: Remove divorced spouse](https://staging.va.gov/view-change-dependents/add-remove-form-21-686c/report-a-divorce)
| 0 issues | [Step 7: Remove a stepchild / basic info](https://staging.va.gov/view-change-dependents/add-remove-form-21-686c/686-stepchild-no-longer-part-of-household)
| 1 issue | [Step 7: Remove a stepchild / stepchild status](https://staging.va.gov/view-change-dependents/add-remove-form-21-686c/686-stepchild-no-longer-part-of-household/0)
| 0 issues | [Step 8: Remove deceased / basic info](https://staging.va.gov/view-change-dependents/add-remove-form-21-686c/686-report-dependent-death)
| 0 issues | [Step 8: Remove deceased / date of death](https://staging.va.gov/view-change-dependents/add-remove-form-21-686c/686-report-dependent-death/0/additional-information)
| 0 issues | [Step 9: Remove child who is now married](https://staging.va.gov/view-change-dependents/add-remove-form-21-686c/686-report-marriage-of-child)
| 0 issues | [Step 10: Remove child 18 to 23 not in school](https://staging.va.gov/view-change-dependents/add-remove-form-21-686c/report-child-stopped-attending-school)
| 0 issues | [Step 11: Net worth](https://staging.va.gov/view-change-dependents/add-remove-form-21-686c/net-worth)
| 0 issues | [Step 12: Review and submit](https://staging.va.gov/view-change-dependents/add-remove-form-21-686c/review-and-submit)

### How did axe testing go?

1 issue discovered on [Step 7: Remove a stepchild / stepchild status](https://staging.va.gov/view-change-dependents/add-remove-form-21-686c/686-stepchild-no-longer-part-of-household/0): 
Headings skipped a level. "Step 7 of 12..." is an H2, but "[stepchild's name]" is an H4. It should be an H3. [View this screenshot](https://tinyurl.com/22y7kxeu) to see the heading issue.

There's 1 global issue on the navigation menu. [There's an open discussion about this issue](https://dsva.slack.com/archives/C0335Q88X0S/p1679342626265369) and it shouldn't impact users: 
> "We took a deep dive and think that this shouldn't impact experience, except load times, and it should not impact accessibility experience because it is hidden, and is likely just an issue with the code."

### Who completed the content zoom and reflow test?

@coforma-jamie

### Content zoom and reflow checks

- [x] All page elements are readable and usable at 200% zoom
- [x] All page elements are readable and usable at 300% zoom
- [ ] All page elements are readable and usable at 400% zoom

### How did content zoom and reflow testing go?

2 issues

At 400% zoom, there were two issues:
- Breadcrumb text didn't wrap properly
- "Continue >>" text in the back/continue buttons didn't wrap properly

[I discussed this with the DST in Slack](https://dsva.slack.com/archives/C01DBGX4P45/p1691431164561389). They recommend that you use VA components for the breadcrumbs and bottom buttons, which should solve these issues. (Looking at your source code, it looked like you were using "raw" buttons and breadcrumb navigation. If I'm wrong, please let me know so I can report to the DST.) Here's where to find info about the components:
- [Button pairs](https://design.va.gov/components/button/button-pair)
- [Breadcrumbs](https://design.va.gov/components/breadcrumbs)

### Who completed the keyboard navigation test?

@coforma-jamie

### Keyboard navigation checks

- [x] Each link, button, form input, checkbox, radio button, select menu, and custom element can receive keyboard focus
- [x] Each link, button, form input, checkbox, radio button, select menu, and custom element responds to expected keys
- [x] All elements under focus have a visible focus indicator
- [x] The order of [Tab] stops made sense and was appropriate for completing tasks

### How did keyboard testing go?

No issues

### Do you have any other results to share?

1. One defect-x was discovered in this testing: #63206 
2. On the last page of the form, there's a link to the privacy policy. This link opens in a new window/tab, which is indicated using an icon. For links within the VA domain that open in a new tab or window, we recommend that you remove the icon and "(opens in new tab)".
3. The accessibility defect rubric recommends that a page `<title>` should match that page's `<h1>`. That's not currently the case on this form - the `<h1>` doesn't have the form number, the `<title>` does. There's been [internal discussion](https://dsva.slack.com/archives/C0335Q88X0S/p1691432513356529) about the form heading and this `<title>` issue, and a consensus hasn't been reached yet. We want to prioritize a larger fix to form headers, so for now, keep the `<title>` as-is. (Reference: [1326](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1326))

**Comment by steele-lm** [comment]
@tblackwe

**Comment by sara-amanda** [comment]
## CAIA Notes
This ticket contains three forms, with five open issues, and a maintenance audit is being requested before 7/31/2023. This is ticket 1 of 4 tickets. 

### 3 Forms

1. 21-686c
2. 21-674
3. 21P-509

### Tickets
-  **5 open issues**
- 2 closed

### :warning: Login Needed
_@steele-lm Please provide a link to where we should grab the testing login for these 3 forms._  

cc: @coforma-terry @ohgreatkate

**Comment by steele-lm** [comment]
@sara-amanda try this one:
vetsgov+test236@id.me
Password1234!

**Comment by sara-amanda** [comment]
## CAIA INVENTORY UPDATE

### PDF VERSIONS (3)
- [Form 21-686c for Adding/removing Dependents](https://www.va.gov/find-forms/about-form-21-686c/)
- [Form 21-674 for school experience](https://www.va.gov/find-forms/about-form-21-674/) 
- [Form 21P-509 for Statement of Dependency of Parent(s)](https://www.va.gov/find-forms/about-form-21p-509/) **PDF ONLY**

### DIGITAL VERSIONS (2)
- [Form 21-686c for Adding/removing Dependents](https://www.va.gov/find-forms/about-form-21-686c/)
- [Form 21-674 for school experience](https://www.va.gov/find-forms/about-form-21-674/) 

@coforma-terry

**Comment by sara-amanda** [comment]
## CAIA Form Audits
@coforma-jamie @ohgreatkate I went ahead and put two templates in this ticket body for the two digital forms we will be auditing on this ticket. 

- Form 21-686c for Adding/removing Dependents
- Form 21-674 for school experience

When done - or as you make progress, feel free to update everyone in the comments of the ticket. 

_**Thank you for working on this! So glad to have you both on the CAIA Team!**_ 

cc: @coforma-terry

**Comment by sara-amanda** [comment]
## Access Issue
@steele-lm we are not able to use the login information provided. Do you happen to have additional login information available that you can link to in GitHub? 
cc: @coforma-jamie @ohgreatkate

**Comment by steele-lm** [comment]
@sara-amanda [These test accounts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/ebenefits/dependency-verification/research-design/usability-testing-1/dependent-verifiy-usability-1-research-plan.md) were used during usability testing, and we've used user 108 recently.
@coforma-terry @ohgreatkate @coforma-jamie

**Comment by sara-amanda** [comment]
## CAIA Note on VA page `<title>`

- [ ] Full-issue fix status: Pending, as of 8/7/2023
- [x] Notes compiled from a11y-specialists conversations/information gathering c/o @coforma-jamie 
- [x] Foundational Audit Completed by @coforma-jamie 
- [ ] Assistive Tech Audit (new ticket to be created by @coforma-jamie) 

## Issue: VA page <title>

### Current Guidance: a11y Defect Rubric

According to the a11y defect rubric: [a11y-defect-2](https://depo-platform-documentation.scrollhelp.site/developer-docs/accessibility-defect-severity-rubric#Accessibilitydefectseverityrubric-a11y-defect-2) Page` <title>` tags must update on every route (URL) change. 
- This includes single-page apps (SPAs).
- `<h1>` should match the `<title>` or be included in the `<title>`

- **Example title:** Check your appeals status | [VA.gov](http://va.gov/)
- **Example heading:** Check your appeals status

### Current Recommended Practice

- For now, in general, the `<title>` should match the `<h1>`.
- However, if Veterans refer to the form by its number, put the number in the <title>.

### [Pending] Potential Future Fix

- **Future fix** would include switching to unique `<h1>`
    - ⚠️ **Please do not implement at this time**, as there is an outstanding ticket related to this. Please wait for the permanent fix. More info. below. 
    - **Contacts:** Laura Flannery or Josh Kim
- **Related Items:**
   - [Experimental Design [Simple Form Header] #1326](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1326)

> - There is a subtask pattern where the `<h1>` is unique on each page of the form but many forms haven't yet adopted this pattern.
> - There was also an issue encountered when implementing a form using the subtask pattern - generated [an issue](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14046) that the `<title>` did not match the `<h1>` . It was looked into and it couldn't be implemented at all because of the way the page/form is built.

- Internal a11y note: [Slack Thread Ref](https://dsva.slack.com/archives/C0335Q88X0S/p1691432513356529).
