### ISSUE TITLE
Create Incident Response Playbook for CHIP & LoROTA API Support

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#61693]
## Tasks
- Review the [PCI API Tier 3 Production Support Team On-Call Monitoring Playbook](https://github.com/department-of-veterans-affairs/checkin-devops/blob/master/docs/PCI%20API%20Tier%203%20Team%20Playbook.md#agreements)
- Create a Playbook for production support of eCheck-in, Pre-Check-in and their APIs that is based on the playbook above
- Determine how to configure PagerDuty to suit our team's needs
- Get buy-in from all the engineers

**Comment by lee-delarm6** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/decisions/Chip-Lorota-Playbook.md

@brianseek @wullaski @randomsync @kanchanasuriya Please take a look and add (or remove) anything you see which you think we'll need on this before we close this up
