### ISSUE TITLE
Evaluate onsite notifications for New Copay

### ISSUE THREAD

**Issue by A6-toma** [department-of-veterans-affairs/va.gov-team#61701]
Evaluate onsite notifications for New Copay

**TASKS**

- [x]  UX evaluation [(document with notes)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/landing-page/notifications/new-copay.md)
- [ ]  Technical evaluation

### Acceptance Criteria
UX complexity and technical complexity of implementing New Copay onsite notification have been documented.

**Comment by fmccaf1** [comment]
@LynneJohnson224 just finished this one. I'll move to done if you feel ok taking on creating a ticket for technical eval?

**Comment by LynneJohnson224** [comment]
@fmccaf1 will do - thanks!
