### ISSUE TITLE
Right margin of the appointment list is too close to the right edge of screen

### ISSUE THREAD

**Issue by jenniemc** [department-of-veterans-affairs/va.gov-team#61727]
## Summary
The right margin of the appointment list is too close to the right edge of the screen

## Specs
- Device: 
- Browser: Chrome

## Steps to Reproduce
Log into staging
click on "past" on breadcrumb 

### Actual Result
Right margin is too close to the right edge. The horizontal dividing lines between each appointment comes up right to the edge of the screen in the tablet and mobile view.
![Screenshot 2023-07-10 at 2.57.59 PM.png](https://images.zenhubusercontent.com/5d6463ed1325bafe0674800b/0bd34b23-35d2-4843-a917-2d80009036ad)

![Screenshot 2023-07-10 at 3.03.35 PM.png](https://images.zenhubusercontent.com/5d6463ed1325bafe0674800b/8b8602f2-1a6d-4aba-90fe-f874350bda94)

### Desired Result
 The right margin gutter should match the left margin

## Definition of Done
- [ ] Desired result is achieved and/or document decisions made
- [ ] Relevant documentation is updated

---
## How to configure this issue
- [ ] **Labeled with Team** (`vaos`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `design`, `product`)
- [ ] **Labeled with** `Bug`
- [ ] **Assigned to** Product for prioritization

**Comment by ldelacosta** [comment]
Work is completed. No new issues to report. Closing out the bug ticket.
