### ISSUE TITLE
Update Simplified Form Flow

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#61749]
Based on meeting with Kristin O from CAIA it does seem important to update and maintain the Simplified flow

Acceptance Criteria:

**Comment by juliepedtke** [comment]
Update complete! BDD and RNG don't really impact the length of the form, so those use cases aren't very interesting, but seeing the CFI quite a bit shorter and the PTSD flow stretch out way long seems helpful. I also think we could suss out some additional use cases that have a big impact on form length, such as additional benefits and evidence types.
