### ISSUE TITLE
Corrections/updates for /developer-docs/onboarding FAQ section

### ISSUE THREAD

**Issue by radavis** [department-of-veterans-affairs/va.gov-team#61754]
### Description

Noting a few discrepancies at `/developer-docs/onboarding`

- List Item 3: "this video" link is private (https://www.youtube.com/watch?v=l_ErfXWckjI)
- List Item 5: HTTP basic auth is no longer used for logging into staging.va.gov
- List Item 7: Org chart is not available at url https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/backend
- List Item 9: @ mina is deactivated on Slack.

### Relevant URLs

https://depo-platform-documentation.scrollhelp.site/developer-docs/onboarding#Onboarding-Background/FAQ

### Which type of team are you on? (Platform team, VFS team, or Leadership)

VFS

**Comment by vbellissimo** [comment]
@radavis Hello. Thank you for highlighting these issues. The Platform Content team is taking a look for next steps. Thanks

**Comment by rmtolmach** [comment]
Thanks for bringing this page to our attention @radavis! I made the edits and they should be live later this week. @vbellissimo I'll let you close it 🙂

**Comment by vbellissimo** [comment]
@radavis , the changes Rebecca made have been deployed. Closing this ticket now. Thank you.
