### ISSUE TITLE
[Helm] Update Directory Name

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#61759]
## Description
Update helm chart directory name to `charts/`

## Acceptance Criteria
- [ ] Rename `helm/` to `charts/`
- [ ] Update the Helm Release workflow to point at the new directory location

## Refinement Guidance - Check the following before working on this issue: 
- [x] _Team label assigned ("platform-tech-team-2")_
- [ ] _Epic assigned (if needed)_ 
- [x] _Estimated (points assigned)_
- [x] _Sprint assigned (once planned)_
- [x] _Team member(s) assigned_

**Comment by hgbarreto** [comment]
Adding to sprint before first helm chart publish.
