### ISSUE TITLE
AWS access for Kyle Cardwell

### ISSUE THREAD

**Issue by KyleCardwell** [department-of-veterans-affairs/va.gov-team#61764]
### COR Name

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative Name

Other - please specify in 'Additional Notes'

### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Kyle Cardwell

### Your Email

kyle.cardwell@va.gov

### Team, Role, and Company of the target individual

MHV Secure Messaging, Front End Engineer, By Light / ACS

### Product Manager (PM) name and email

Lichelle Bain - lichelle.bain@va.gov

### Product Owner (PO) name and email

Patricia Henry - Patricia.Henry@va.gov

### Desired AWS Access

Requesting the SSMApplicationLowerEnvironmentAccess policy, and to be added to the existing IAM group dsva-vfs-developers

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

<img width="949" alt="Screenshot 2023-07-11 at 9 52 14 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/79024398/d0dd21db-7f53-428b-a802-59c412d32092">

### Additional Notes

COR: Sean Good
Vendor Onboarding Representative: Kenneth Brown
Access Expiration: Need ongoing access to upstream data APIs in lower environments for VFS development activity

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by jknipes** [comment]
User found in the VFS Team Roster

**Comment by jknipes** [comment]
### For AWS ACCESS
User: Kyle Cardwell
COR: Sean Good
VOR: Kenneth Brown
Approval needed: @department-of-veterans-affairs/operations-aws-approvers 
AWS Admin Role: no

**Comment by BillChapmanUSDS** [comment]
Lower environment access granted.
