### ISSUE TITLE
Adding [individual] to DSVA Slack

### ISSUE THREAD

**Issue by emilygoodrich5623** [department-of-veterans-affairs/va.gov-team#61766]
# Description

Please add the following individuals:

@caseywilliams  casey.williams@adhocteam.us
@kristen-brown  kristen.brown@adhocteam.us
@michaelhobson michael.hobson@adhocteam.us
@mathisto matt.kelly@adhocteam.us
@emilygoodrich emily.goodrich@oddball.io

 individual as a:

- Single guest

What channel(s) do they need to be added to?
 - va-forms

The individuals on are Team Banana Peels. They are now supporting the VA Forms project and need access to be able to communicate with the other VA Forms teams

We aim to complete slack requests within 24hrs.

**Comment by KevinMHoffmanUSDS** [comment]
All requested folks have been added to the channel.
