### ISSUE TITLE
Vets-api terminal access for [Austin Covrig]

### ISSUE THREAD

**Issue by acovrig** [department-of-veterans-affairs/va.gov-team#61771]
### E-QIP Transmittal Date

- [ ] Check this box if you have an E-QIP transmittal date.

### Your Name

Austin Covrig

### Your GitHub handle (terminal access is managed through GitHub)

austin.covrig@oddball.io

### Team, Role, and Company of the target individual

VA API, Rails Engineer, Oddball

### Product Manager (PM) name and email

Kayla Watanabe kayla.watanabe@adhocteam.us

### Product Owner (PO) name and email

Jannet Coutinho Janet.Coutinho@va.gov

### Your dsvagovcloud AWS user name (if applicable)

Austin.Covrig

### ArgoCD terminal access requested for the following environments

- [ ] dev
- [ ] staging
- [ ] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### COR Name (leave "None" if you listed an AWS user name above)

None

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

None

### Access Expiration

ongoing

### Additional Notes

Team Dash Support - Team Dash runs the Claims API within Lighthouse and we require access to troubleshoot issues and support the Claims API in general. We have to manually resubmit failed Claim Submissions to EVSS and BGS from within Dash and working with Platform-Support is an additional step that we would like to bypass to troubleshoot and update submissions. It would be best if an individual more aligned with the code were updating and running resubmissions.

### User must exist in a roster before vets-api terminal access can be granted

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added
- [x] If they included an AWS user name, check to see if their user name is listed in [iam_users.tf](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf)
- [ ] Comment in this issue saying which roster the user is listed in and confirming their AWS user name (if applicable)

**Comment by bdech** [comment]
@acovrig I have a couple of questions for your request. Are you on VFS or Platform? Also, have you filled out your E-QIP questionnaire? The E-QIP transmittal notice is a requirement that will need to be provided for Vets-api terminal access.

**Comment by acovrig** [comment]
> @acovrig I have a couple of questions for your request. Are you on VFS or Platform? Also, have you filled out your E-QIP questionnaire? The E-QIP transmittal notice is a requirement that will need to be provided for Vets-api terminal access.

I submitted my e-QIP ~1.5yr ago (I understood that checkbox to be "will be submitted at a future date"). I am not on VFS or Platform but have requested being added to the VFS roster.

**Comment by acovrig** [comment]
> @acovrig I have a couple of questions for your request. Are you on VFS or Platform? Also, have you filled out your E-QIP questionnaire? The E-QIP transmittal notice is a requirement that will need to be provided for Vets-api terminal access.

@bdech I have now been added to the VFS roster also.

**Comment by bdech** [comment]
Found in VFS Team Roster

**Comment by bdech** [comment]
@acovrig Is there any chance you can provide the original transmittal email, or an email indicating a favorable approval? You can reach out to your VOR, and they should be able to provide some proof. I only ask because we are maintaining record and paper trail for these requests. Bill Chapman will likely require this documentation before granting production access.

**Comment by bdech** [comment]
@acovrig What is a COI PDF? Yea if it contains any PII do not post it here.

**Comment by acovrig** [comment]
@bdech I asked my VOR for a transmittal email and they replied with a "Certification of Investigation" PDF.

**Comment by bdech** [comment]
Thanks @acovrig . Would it be possible for you to take a screenshot, redact any PII, and post it here?

**Comment by acovrig** [comment]
@bdech - [Covrig_COI  (03-18-2022)-pub-flat.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/12097947/Covrig_COI.03-18-2022.-pub-flat.pdf)

**Comment by bdech** [comment]
Access to `prod` is pending approval by OCTODE, and we'll update you as soon as it's available.

**Comment by bdech** [comment]
@acovrig You've been granted access to `Prod` for 6 months, expiring 01/20/24.

**Comment by bdech** [comment]
slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1689886424325549)

**Comment by bdech** [comment]
@acovrig Your Vets-API Terminal Production access has expired.

Would you like to request an extension? You have 72 hours to respond, or your 
access will be revoked and you will need to fill out a new request.

**Comment by acovrig** [comment]
> @acovrig Your Vets-API Terminal Production access has expired.
> 
> Would you like to request an extension? You have 72 hours to respond, or your 
> access will be revoked and you will need to fill out a new request.

@bdech yes,id like an extension, thanks.

**Comment by bdech** [comment]
@LindseySaari @ericboehs can one of you please give us a :thumbsup: to extend their access?

**Comment by bdech** [comment]
@acovrig your Production access has been extended 6 months, expiring 07/22/24.

Please set a reminder for yourself to return to this Issue and 
request an extension within 1 week of the expiration date. You'll 
receive 1 reminder with a 72 hour window to respond. Failure to 
respond will result in your access being revoked and will require 
you to fill out a new request.

**Comment by bdech** [comment]
support slack reminder [here](https://dsva.slack.com/archives/C06CY71PCAX/p1706799944447539)

**Comment by bdech** [comment]
@acovrig Your Vets-API Terminal Production access has expired.

Would you like to request an extension? You have 72 hours to respond, or your
access will be revoked and you will need to fill out a new request.
