### ISSUE TITLE
[FE] 10-10CG - Facility page: Create search result list component for Facility Selector

### ISSUE THREAD

**Issue by longmd** [department-of-veterans-affairs/va.gov-team#61777]
## Background
To improve the Facility Selection experience, we are implementing new functionality to allow users to input their city, state or postal code and get a list of results from which they can choose. We need to create the results list that contains radio cards to allow for the selection of a single facility. 

The cards should contain the facility name and address as shown in the Sketch designs listed below. Based on consultation with design system and accessibility experts, we can omit any pagination for this list. We should show all results on the same screen.

**NOTE:** To get appropriate styling between the facility name and facility description, we may need to request for the Design System team to add a CSS part attribute to that markup in the web component to allow us to target those items for styling. 

### Resources
- [Initiative brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/Improve%20Facility%20Selection/Improve%20Facility%20Selection%20-%20Initiative%20Brief.md)
- Sketch designs
     - Desktop
          - [Search Input](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/jgnAQyo)
          - [Search Resutls](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/AZxJmLz)
          - [Search Selection](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/DEEeYAk)
          - [Confirmation - different](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/y98PyLK)
          - [Confirmation - same](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/mP1qqEP)
     - Mobile
          - [Search Input](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/dlyemEb)
          - [Search Resutls](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/L40r8GW)
          - [Search Selection](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/pYayMQA)
          - [Confirmation - different](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/GoOPMGE)
          - [Confirmation - same](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/K0vrOZe)
     - [Error states](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/8VxD1oa)
     - [Wireflows](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/dlyed5l)

## Tasks
- [ ] Create accessible list of search results using radio cards
- [ ] Ensure all work is implemented behind feature flag and not visible in production

## Acceptance Criteria
- Facility selection search results component successfully renders a list of facilities
- All created components match the provided designs from the UX team

**Comment by jessicastump** [comment]
The Sketch file has been updated with the corrected card styles/component. Refer to the design system guidance for the latest - [use default white with border](https://design.va.gov/components/card#default---white-with-border)

**Comment by longmd** [comment]
@jessicastump , we will look to use the radio card component for this one. It looks like they have yet to match that styling with the  new card component styling, but we can refer that to them, instead of recreating the wheel.

**Comment by jessicastump** [comment]
Just noting the [image on the design system site](https://design.va.gov/components/card#containers-for-radio-button-tiles-and-checkboxes) does look outdated (rounded corners are a giveaway), but yes the radio component with the latest border/corner guidance on the default styling. :)
