### ISSUE TITLE
Discuss RFC for documentation engine that allows developers to write and update documentation on their own

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#6179]
Our documentation is in a woeful state with three main issues - First our documentation is not easy for developers to update. A separate pull request needs to be made to a separate repo to update documentation, this leads our documentation to not get updated as often as we should be. Second our documentation is not well organized, this leads it to not be the first place folks look for help as it is a much more direct path to simply ask in a Slack channel for help. Third our documentation does not include troubleshooting steps for most items. Our documentation tells you how to set things up but it doesn't tell you anything you can do when things do work the way they are expected to, which is often.

## Motivation
I spend quite a lot of time researching issues with our codebase that could easily be documented in our own documentation. This research and troubleshooting usually takes me on a path from Google, back to the code, to Google, To StackOverflow, to our Slack channels and waiting for a response in Slack. This all takes quite a bit of time, time that I am not able to spend in pursuit of our mission, helping provide value to Vets.

## Potential Solution
To solve these three issues we need a documentation process that is easy for developers to update, is much better organized, and includes troubleshooting steps for when things go wrong. To address these three issues we should -

1. To fix our documentation not being easy to update we should implement a documentation engine, such as [JSDoc](https://jsdoc.app/), these documentation engines use comments in specific formatting inside our code to generate a documentation site. This means that engineers can write comments that document the code right along side the code itself. In order for this to work we will most likely need to also implement standards and conventions for commenting, and thus documenting, our code.

2. To fix our documentation not being well organized we should enforce a plan to organize our documentation like a book, with a table of contents and chapters. This allows us to not only utilize a format that everyone understands but also makes it easy for us to organize documentation around specific topics, like on-boarding or troubleshooting. This type of organization can be achieved with documentation engines mentioned above in #1.

3. To fix our documentation not having troubleshooting steps we should organize both our comments, and thus the documentation around a feature, and some chapters around troubleshooting steps for when things go wrong. These troubleshooting steps should be a requirement in the standards and conventions for commenting we implement.

## Risks of this potential solution
There is a risk with implementing a documentation engine that is owned and maintained by the developers that it could be an added burden on developers. This risk should be minimal and taken as the same amount of risk that would come with any other dependency in our build system.

There is also a risk that if we do not use this new documentation process that it could become a documentation 'graveyard' like our current documentation is. We would need to adhere to actually using this new documentation to minimize this risk.

## Alternative solutions
We could stick with the current documentation process and organization we have, this worked in the past and could potentially work in the future if we took a long hard look at how we can patch the current process to work better in the areas outlined above.

We could create markdown files within our codebase, this is actually used here and there in our codebase already. These could potentially get very large and become very hard to organize so if we wanted to go this route I still recommend we go with #2 and #3 on the list above.

There are probably other alternatives not mentioned here but this is really just meant to open up conversation around this so we can hopefully find a solution that works for all.

**Comment by cohnjesse** [comment]
@billfienberg CCing you here

**Comment by billfienberg** [comment]
Here are some relevant links:
- Folder of Content & IA doc site resources: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/platform/documentation-site
- Slack channel for doc site discovery sprint: https://dsva.slack.com/archives/CRKEKFJ2C/p1576084312002100
- Slack channel to share documentation role models/examples: https://dsva.slack.com/archives/CRKFZR613/p1576085277000300
- Conf talk about Google's documentation solution:
  - Video: https://www.usenix.org/node/197471
  - Slides: https://www.usenix.org/sites/default/files/conference/protected-files/srecon16europe_slides_macnamara.pdf
- Repo folder for [current, broken Gatsby site](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/gatsby-configurations/): https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/tree/master/packages/documentation
