### ISSUE TITLE
Centrally store email lists

### ISSUE THREAD

**Issue by djmunoz1** [department-of-veterans-affairs/va.gov-team#61823]
As an email admin I need to see all email send lists stored in a centralized location so that I can easily reference them.

ACCEPTANCE:
- email list for Reactivation Test A and B stored in folder
- accessible to LGA team

DEF OF DONE:
- link to folder shared in ticket

**Comment by sdickson-gt** [comment]
Stored here:  vacohsm01.dva.va.gov\VACO_Workgroups\Information & Technology\OCTO Digital Experience\Logingov Adoption\email campaigns

Let me know if you don't have access
