### ISSUE TITLE
Adding Scott Weber to DSVA Slack

### ISSUE THREAD

**Issue by vievemarg** [department-of-veterans-affairs/va.gov-team#61821]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

Please add Steve Scott Weber, Delivery Lead for VES Modernization UI/UX Team, to DSVA Slack as a full member. His email is STEPHEN.WEBER@va.gov. Thank you. 

Are you requesting to add an individual as a:

- Full member
- Single guest
- Multi-channel
- Switching from single-channel to multi-channel?
- What channel(s) do they need to be added to?

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add [_insert email_] as a single-channel guest to [_channel name_].
- Please add [_insert email_] as a multi-channel guest to these channels: [_channel names_].
- Please add [_insert email_] as a full member.
- Please change the status of [_slack username_] from [_current status_] to [_desired status_]

**Comment by KevinMHoffmanUSDS** [comment]
Invited!

**Comment by vievemarg** [comment]
Hi @KevinMHoffmanUSDS I apologize, the correct address for Stephen Weber is scott.weber@adhocteam.us
Would you please add him there as you have capacity? Thank you.

**Comment by vievemarg** [comment]
Hi again - can someone help adjust this email? Thanks so much for that.

**Comment by KevinMHoffmanUSDS** [comment]
Invite sent, thanks for your patience!

**Comment by KevinMHoffmanUSDS** [comment]
@vievemarg Just be sure to REOPEN the issue if there's new stuff to do, as we generally don't browse closed issues.

**Comment by vievemarg** [comment]
Thanks @KevinMHoffmanUSDS  - noted!
