### ISSUE TITLE
Resolve nav label questions for AMA Feb 19 content changes

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#6182]
### This is a sub-task of [Ticket 5541: [Due on Feb 19] Appeal Modernization Process (AMA) Changes ](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/5541)

@mnorthuis FYSA @AkucherGCIO @lwalsh617 @RLHecht @ncksllvn 

Per our discussions, we're not changing any IA for this release (adding/removing or relocating nav items) -- with this round of publication. (IA work post-this release is tracked in #4141.) 

**There are however 2 page name changes we want to alert you to:**
1/ **File a VA disability appeal** is changing to **Manage a legacy VA appeal** - currently `/file-an-appeal/`

2/  **Multiple party or contested claims** is changing to **Contested claims** - currently `.gov/decision-reviews/multiple-party-claims/` 

**For the go-live of AMA content updates, could you advise us on the following:**

1. Should the URLs of the above 2 pages change? 
2. `File an appeal` link label in the current nav menu will be updated to reflect new `Manage a legacy VA appeal` page name  (Or do you recommend we  point to the` Decision review` page instead with this release?)
3. ` File an appeal` link label in the hub landing page menu will be updated to reflect new `Manage a legacy VA appeal `page name (Or do you recommend we  point to the `Decision review` page instead with this release?)
4. RE global flyout menu: the link called` File an appeal` - for this release, should we update just the label to the new `Manage a legacy VA appeal` name or change the link completely and point to the `Decision review` page instead?

Also - for IA awareness:  the business has requested we remove the Board of Veterans' Appeal hearing link from the left nav. (It currently points to this URL: https://www.va.gov/disability/file-an-appeal/board-of-veterans-appeals/

**Comment by lwalsh617** [comment]
@jenniferlee-dsva, for question #4 above, attaching Fred's original feedback (see screenshot) for consideration. Didn't want it get lost. 
<img width="674" alt="Screen Shot 2020-02-25 at 7 22 07 PM" src="https://user-images.githubusercontent.com/53535663/75299845-2578ab00-5804-11ea-81b4-26396f587d9e.png">

**Comment by jenniferlee-dsva** [comment]
**Per Wed call w/ @mnorthuis , @ncksllvn , @lwalsh617 , @RLHecht , @AkucherGCIO ** 

1/ File a VA disability appeal is changing to `Manage a legacy VA appeal` - currently /file-an-appeal/  **[for this release, keep existing URL]**

2/ Multiple party or contested claims is changing to `Contested claims` - currently .gov/decision-reviews/multiple-party-claims/ **[ for now keep existing URL]**

3/ global flyout menu: the link called File an appeal - **[Remove for now]**

4/ File an appeal link label in the current nav menu and breadcrumb will be updated to reflect new `Manage a legacy VA appeal` page name ]**[ yes]**

5/ File an appeal link label in the hub landing page menu will be updated to reflect new `Manage a legacy VA appeal` page name **[yes and the new copy will be:]**
**Manage a legacy VA appeal** > <links to https://www.va.gov/disability/file-an-appeal/>
If you filed a Notice of Disagreement for a decision dated before February 19, 2019, find information on the legacy VA appeal process.

6/ Also - for IA awareness: the business has requested we remove the Board of Veterans' Appeal hearing link from the left nav. (It currently points to this URL: https://www.va.gov/disability/file-an-appeal/board-of-veterans-appeals/ **[removing in the nav, but keeping the page as-is]**

**Comment by AkucherGCIO** [comment]
03/04/20 PW Grooming
This issue can be closed because it's related to the changes that launched already.
