### ISSUE TITLE
correlate ICNs with email list - Reactivation Tests (A)

### ISSUE THREAD

**Issue by djmunoz1** [department-of-veterans-affairs/va.gov-team#61822]
As an email admin I want to check the login activity of veterans who received a Reactivation email Test A so that I can understand their post-email login behavior.

**ACCEPTANCE:**
- get email send list for Reactivation Test A and C (2500 veteran emails)
- get ICNs for each email recipient
- check login activity for ICNs on the Reactivation Test A recipient list between 7.11 and 7.25

**DEF OF DONE:**
- data sheet listing login activity by credential by day by credential for each ICN exists for Test A and Test C send lists
- process for pulling this data is repeatable and documented

**Comment by sdickson-gt** [comment]
Getting all login activity for a list of users is doable but larger effort and would take more effort to fully automate.  As an alternative, @djmunoz1 and @jrjamespdx , can we address success of reaactivation using just the last login dates for the list of users?  Latter can be obtained using the monthly user credentials from MPI.

**Comment by djmunoz1** [comment]
hi @sdickson-gt yes, let's go with last log in dates for now thx

**Comment by djmunoz1** [comment]
@sdickson-gt updated this ticket per my note in slack. The ask is for ICN matching on Tests A & C now (vs A & B). If there's any reason Monday is an issue, pls let me know asap.

**Comment by sdickson-gt** [comment]
Started a new dashboard to show results from the various tests.  First iteration is based on monthly MPI credential snapshots.  Currently investigating how to correlate user lists with DataDog for more up to date results.

**Comment by djmunoz1** [comment]
this is great (adding to Dashboard)!
