### ISSUE TITLE
[BE] FD/PG API prototype: SEND data from ES

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#61834]
As a Veteran, I would like to view the financial information the VA has for me online, as well as my Priority Group, so that I can make sure I don't have to pay copays if I don't have to.

- Confirm that we can send the following to VES --all are Previous Year(EZR Section IV-V):
- [x]  Gross Annual Income from employment: Veteran, Spouse, All Dependent
- [x]  Net Income from Farm, Ranch, Property, Business: Veteran, Spouse, All Dependent
- [x]  Other Income Amounts: Veteran, Spouse, All Dependent
- [x]  Total non-reimbursed medical expenses paid by Veteran and Spouse
- [x]  Funeral and Burial Expenses
- [x]  College or vocational expenses
- [ ]  Create Document for API auth
- [ ]  Any other relevant information (AS: I don't know what this would look like, but anything else that catches the eye that might relate to a Veteran's income and/or a Priority Group calculation)
- [ ]  **Success: Team confirms or denies that API prototype can send all of the above fields from the Enrollment System**

-----------------------------------------------
**Resources:**

- **[API Docs](https://ves.va.gov/esr-ws/spring-ws/getEESummary/eeSummary.wsdl)**
- [Lihan's Documentation](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/tutorials/record_vcr.md)
- [VA Profile API sharepoint](https://dvagov.sharepoint.com/sites/OITEPMOVAPROPUB/SitePages/Getting-Started.aspx)
- [Health Benefits Swagger Doc](https://qa.vaprofile.va.gov:7005/health-benefit/swagger-ui/index.html?configUrl=/health-benefit/v3/api-docs/swagger-config)
- [Personal Information](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/profile/personal_information/backend_documentation.md)
- [Contact Information](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/profile/contact_information/backend_documentation.md)
- [Military Information](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/profile/military_info/backend_documentation.md)
- [Direct Deposit Information](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/profile/direct_deposit/backend_documentation.md)
- [Notification Settings](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/profile/notification_settings/backend_documentation.md)
- [Account Security](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/profile/account_security/backend_documentation.md)

**Comment by lihanli** [comment]
sending spouse and dependent data requires also sending the dependent and spouse information from the 1010ezr
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/830084/1ed7365e-612d-4cfc-8a58-e8a8602bf391)

i asked josh faulkner if updated income is applied to the previous calendar year, he said he doesn't know
