### ISSUE TITLE
[MOBILE, ZOOM]: Content SHOULD fit within the viewport when zoomed to 400%.

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#6184]
# [508-defect-2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)
**Feedback framework**
- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 
## Description

Content **SHOULD** fit within the viewport when zoomed to 400%.

As part of the VA accessibility testing process, we [zoom to 400%](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/508-accessibility-best-practices.md#zoom-to-400) to evaluate for reflow, which may be an issue for mobile or those who use magnification tools. Most layouts should not scroll sideways or have content to the edges. Horizontal scrolling is permitted for content like images, maps, diagrams, presentations, and data tables. As shown in the screenshots below, the map does not scroll horizontally but is cut off and the contextual controls are also cut off. 

I'm not sure if this issue belongs to the Mapbox upgrade, the [Urgent Care MVP](https://github.com/department-of-veterans-affairs/va.gov-team/issues/5288), or a later effort.

```diff
- "Must" for if the feedback must be applied 
! "Should" if the feedback is best practice 
+ "Consider" for suggestions/enhancements 
```

## Point of Contact

**VFS Point of Contact:** Jennifer

## Acceptance Criteria

As a user of magnification tools, I want to view all the content of the Facility Locator within the viewport frame.

## Steps to Recreate

1. Enter `https://www.va.gov/find-locations` in browser
2. Zoom to 400%
3. Verify that controls and map are cut off

## Possible Fixes (optional)

These are suggestions, based on a quick inspection. I am not aware of the reasons for the decisions below, so these may not be accurately relevant.

- Within the form#facility-search-controls, there is div class="columns marg-left". If I remove the marg-left everything flows properly within the form controls. 

- For the map container, there is inline CSS padding-left: 0px that appears to be cutting off the content within.

- For the pagination, there is a container div class="width-35" and when I remove that class, the pagination is no longer cut off and aligns centered below the map area.

## WCAG or Vendor Guidance (optional)

* [Understanding Success Criterion 1.4.10: Reflow](https://www.w3.org/WAI/WCAG21/Understanding/reflow.html)
* [WCAG: Understanding Reflow](https://www.w3.org/WAI/WCAG21/Understanding/reflow.html)

## Screenshots or Trace Logs

![Facilities-mapboxupg-400pct-2](https://user-images.githubusercontent.com/57469/75296475-47b9fb00-57fb-11ea-91cc-74b724a73b93.png)
![Facilities-mapboxupg-400pct-1](https://user-images.githubusercontent.com/57469/75296476-48529180-57fb-11ea-96ef-1a8cc291254c.png)
![Screen Shot 2020-03-18 at 5 39 03 PM](https://user-images.githubusercontent.com/57469/77010035-66656a80-693f-11ea-913e-c5c2fd4dbc03.png)

**Comment by mmiddaugh** [comment]
This is a duplicate issue and will be validated in implementation of new design [#11460](https://github.com/department-of-veterans-affairs/va.gov-team/issues/11460)
