### ISSUE TITLE
Adding Rachel Shearer to DSVA Slack

### ISSUE THREAD

**Issue by megansiddle** [department-of-veterans-affairs/va.gov-team#61854]
# Description

Please add Rachel Shearer [Rshearer@pluribusdigital.com](mailto:Rshearer@pluribusdigital.com) as a Full Member of DSVA Slack. Rachel is a UX Designer working on the CEDAR VA Product Team Forms Task Order.

**Comment by KevinMHoffmanUSDS** [comment]
Invited!
