### ISSUE TITLE
Files uploaded with text exceeding the char limit return 'File type not supported'

### ISSUE THREAD

**Issue by mchae-nava** [department-of-veterans-affairs/va.gov-team#61851]
## Issue Description

Certain fields that accept text files as input are also subject to the same char limit as text fields. However, these fields are not validated on the frontend and return a misleading error message once they reach EVSS

This character limit is also subject to the same issue detailed in [42476](https://app.zenhub.com/workspaces/526ez-bugs-and-defects-646e4436ff6787001ac4771a/issues/gh/department-of-veterans-affairs/va.gov-team/42476)

EVSS found 3,152 logs specifically for "file type not supported", which encompasses both actual filetype not supported issues as well as files containing > char limit

### Information that aids in the research and troubleshooting of the issue
- Form/Page of Issue:          
- Error Message:              
- How to reproduce:           
- Unique IDs:                 
- Application ID:             
- Date and Time of Issue:     
- Hardware Issue Observed On: 
- Browser type / version:
- Case#, if available:  
- Reporter name in va.gov: 
- Link to details in Sharepoint, if available: 

### Information needed to assess the severity of the issue
- Issue Impact:       
- Workaround:            
- Legal Requirement:    
- Congressional or other requirement:  
- Loss of Service:       
- Permanent Impact:   
- Users Impacted:     
- Vulnerability:      

### Acceptance Criteria for moving it to Ready for PM/PO review (**For the Disability Experience Team only**)
- [ ] Impact summary
  - Description of impact to the veteran/submitter
  - How many users/events (is that including retries?)
  - Is this issue causing the submission to fail?
      - Is there a workaround?
      - Is it getting submitted via the paper form through the back end processing
      - Is the failure silent?
  - Is this caused by a downstream back-end exception?
- [ ] Severity Assigned ( sev-critical / sev-major / sev-moderate / sev-minor ) [Link](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1677075027359/3be1457e29c424eeada818562a30b363a778fff0?wid=0-1685044574087)

**Comment by austinjprice** [comment]
@sethdarragile6 to determine if failure results un retry to EVSS or do we stop, and do we successfully create a pdf for sending to central mail or does application drop

**Comment by sethdarragile6** [comment]
@kylesoskin [mentions](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60157#issuecomment-1636160925) on #60157 that the retry process is generally meant to handle known external issues like temporary network outages, not necessarily internal error conditions like this. I would expect that the PDF wouldn't even be generated in this case, but I will try to confirm this in more detail.

**Comment by sethdarragile6** [comment]
Just got access to Sidekiq, and searched their "[morgue](https://api.va.gov/sidekiq/filter/dead)" for 'EVSS_15004'. It gave me 432 dead entries over the last 5 months. This encompasses ALL 'EVSS_15004' errors, however, and not just the "false positive" case w/the max char limits. But it seems pretty clear to me that these sorts of errors are NOT retryable and end up in the "dead pool". (searching for 'EVSS_15004' in the Retry queue also shows these type of errors, and often they are on their 13th and final retry)

**Comment by austinjprice** [comment]
@NB28VT for viz as he is working on similar issue as reported by @va-albers here via Sentry log: x [ISSUE] EVSS_15004 file type errors from EVSS

Apologies for not connecting the dots earlier but good opportunity to pair

**Comment by austinjprice** [comment]
@NB28VT to add to overall solution of file upload failure and make sure logging implementation includes this use case
