### ISSUE TITLE
Enable Isolated Application Builds for MHV on VA.gov

### ISSUE THREAD

**Issue by radavis** [department-of-veterans-affairs/va.gov-team#61867]
## Story

As a Developer
I want to enable Isolated Application Builds for MHV on VA.gov
So that I can leverage the features of the platform and achieve faster builds.

## Acceptance Criteria

- [ ] `src/applications/mhv` has no cross-application imports
- [ ] `/my-health` passes the header test
- [ ] A Slack User Group is created and associated with the `mhv` application within vets-website

[[source](https://depo-platform-documentation.scrollhelp.site/developer-docs/how-to-add-your-application-to-the-allow-list)]

**Comment by radavis** [comment]
- [x] `src/applications/mhv` has no cross-application imports
- [x] `/my-health` passes the header test

![Screenshot from 2023-07-12 14-02-50](https://github.com/department-of-veterans-affairs/va.gov-team/assets/1299034/ed128763-60b2-4323-ba01-5b0d932b6c5a)

**Comment by radavis** [comment]
Slack Group:

![Screenshot 2023-07-12 144228](https://github.com/department-of-veterans-affairs/va.gov-team/assets/1299034/cdf77d4e-71f0-4a21-be22-d9f2aa53a3f7)

**Comment by dcloud** [comment]
Linking previous ticket, department-of-veterans-affairs/va.gov-team/issues/53811, where we found that the continuous build config didn't support nested folders. This spawned a platform ticket, department-of-veterans-affairs/va.gov-team/issues/58176, that appears to still be open
