### ISSUE TITLE
BUG: non-2FA Direct Deposit users should see "set up 2FA" message

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#6187]
LOA3 users who do not have 2FA set up should be shown a message that they need to set up 2FA so that they can see their direct deposit information. But they are currently not shown anything.

**Comment by erikphansen** [comment]
@Samara-Strauss / @mshea0606 I have a PR up for this, but I'm not sure how we'll be able to validate it on staging. Do we have a test user that is LOA3, does not have 2FA set up, and also has access to Direct Deposit?

**Comment by Samara-Strauss** [comment]
So [Jamie.wood](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/test-users.md) is the test user we have for this case, and I am still not seeing direct deposit with the 2FA prompt for him.

**Comment by erikphansen** [comment]
@Samara-Strauss sorry it's not on staging yet! will let you know when my PR is merged

**Comment by erikphansen** [comment]
And thanks for the link to that doc!

**Comment by Samara-Strauss** [comment]
> sorry it's not on staging yet! will let you know when my PR is merged

I see now that you said you had a PR up and I just went ahead to validate 😂 Sorry for being overly enthusiastic! I'll sit tight and will check in once the fix is ready :)

**Comment by erikphansen** [comment]
It should be on staging now, @Samara-Strauss

**Comment by erikphansen** [comment]
It should be on staging now, @Samara-Strauss

**Comment by Samara-Strauss** [comment]
Having trouble getting into the Jamie.Wood account to test right now, so I'll try later and see if we have any luck.

**Comment by Samara-Strauss** [comment]
Having trouble getting into the Jamie.Wood account to test right now, so I'll try later and see if we have any luck.

**Comment by Samara-Strauss** [comment]
FINALLY was able to get into the test account for this. Seeing the 2FA prompt as expected. Validated!
