### ISSUE TITLE
Create Figma Prototype For Usability Test

### ISSUE THREAD

**Issue by charlye-bluetiger** [department-of-veterans-affairs/va.gov-team#61875]
### Description of UX Tasks

- [ ] Update Figma prototype for Usability Test. [Figma File](https://www.figma.com/file/rw8kJXf4VKliimoMpsEy4Q/Identity-Dashboard-(initial)?type=design&node-id=2-57&mode=design&t=pPE6XZz28veWCZ4L-0)

#### Acceptance Criteria
- [x] Reviewed by UX Team
- [x] Reviewed by PMs
- [x] Documentation has been updated
- [x] Put published research in drive

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by aparsley** [comment]
Keep up the good work.
