### ISSUE TITLE
Vets-api terminal access for Anita DeWitt

### ISSUE THREAD

**Issue by anitadewitt-va** [department-of-veterans-affairs/va.gov-team#61871]
### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Anita DeWitt

### Your GitHub handle (terminal access is managed through GitHub)

@anitadewitt-va

### Team, Role, and Company of the target individual

Developer on Virtual Agent Chatbot, Thoughtworks

### Product Manager (PM) name and email

Joy Elizabeth joy.elizabeth@thoughtworks.com

### Product Owner (PO) name and email

Luciana Morais Luciana.Morais@va.gov

### Your dsvagovcloud AWS user name (if applicable)

Anita.DeWitt

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### COR Name (leave "None" if you listed an AWS user name above)

Cecila Lee

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

Other - please specify in 'Additional Notes'

### Access Expiration

02-03-2024

### Additional Notes

VOR is Booz Allen Hamilton. 

I would like access to production in order to have another way to turn my feature toggle in vets-api on and off since I am currently seeing an error when doing so.

### User must exist in a roster before vets-api terminal access can be granted

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added
- [x] If they included an AWS user name, check to see if their user name is listed in [iam_users.tf](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf)
- [ ] Comment in this issue saying which roster the user is listed in and confirming their AWS user name (if applicable)

**Comment by bdech** [comment]
@anitadewitt-va Can you please provide a screenshot of your E-QIP transmittal notice?

**Comment by bdech** [comment]
@anitadewitt-va Can you please attach a screenshot of your E-QIP transmittal to this ticket? I attempted to find your E-QIP transmittal from other GitHub issues but was unable to locate a screenshot.

**Comment by bdech** [comment]
@anitadewitt-va Can you please attach a screenshot of your E-QIP transmittal to this ticket?

**Comment by anitadewitt-va** [comment]
Sorry for the delay -- I submitted my equip form on January 14th 2021. 
<img width="952" alt="Screenshot 2023-08-14 at 1 39 44 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/8662795/fa81c5b8-d821-4c3d-b9bf-1df1f1d4df07">

**Comment by bdech** [comment]
@anitadewitt-va  You've been granted access to the `dev`, `staging`, and `sandbox` environments.

Here's some additional documentation for the [Vets API on EKS](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-TerminalAccess)

Access to `prod` is pending approval by OCTODE, and we'll update you as soon as it's available.

**Comment by BillChapmanUSDS** [comment]
access approved for 6 months

**Comment by bdech** [comment]
ou have been granted ArgoCD/vets-api 'Prod' access for 6 months, expiring 02/17/24. Please set a reminder for yourself to return to this Issue and re-request access within 1 week of the expiration date. You'll receive 1 reminder with a 72 hour window to respond. Failure to do so will result in lost access and will require you to fill out a new request.

**Comment by bdech** [comment]
slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1692292404147269)

**Comment by bdech** [comment]
@anitadewitt-va Your Vets API Terminal Production access has expired.

Would you like to request an extension? You have 72 hours to respond, or your 
access will be revoked and you will need to fill out a new request.

**Comment by bdech** [comment]
@anitadewitt-va Your Vets API Terminal Production access has expired.

Would you like to request an extension? You have 48 hours to respond, or your
access will be revoked and you will need to fill out a new request.

**Comment by bdech** [comment]
Removing production access due to no response. If you would like to request production access, please fill out a new request.
