### ISSUE TITLE
Discuss git hook for alerting developers of potential breaking changes

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#6188]
# RFC: Git Hook For Breaking Change Alerts

- Date: 2020/02/25

## Background
Currently while developing code for the VA.gov codebase there are several breaking changes committed to our code per month. A breaking change being something that stops a developer from writing code in order for them to have to run commands to update and fix their local development environment.
Since we have so many developers pushing code to our codebase per day these breaking changes tend to get buried and it is up to the developer to research or seek out a fix.
It would save a lot of time if we implement a git hook to alert the developer of exactly what changed and exactly what steps to follow to fix it.

## Motivation
This would be a big time saver for our developers. Our mission here is to provide as much value for Vets as we can and every
minute we spend fixing our internal tools is a minute we can't spend providing value for Vets.

## Design
This would most likely be a good candidate for the `post-merge` hook on local environments. Using this hook we can look at
what files are changed by pulling the codebase and if certain files are changed, i.e. files that would include obvious 
breaking changes, we can give instructions on how to fix issues caused by the breaking changes. For example, if a change
was made to the `yarn.lock` file we can tell the user that this file was changed and that they will most likely need to -

1. Stop their local environment
2. Run `yarn install`
3. Restart their local environment

We would want to basically watch for changes in any file that can break a developer's local environment, i.e. all of the files
directly in the root of `vets-website` and all of the files directly in the root of `vets-api`. 

A nice to have would also be a git hook on the server that can send a Slack message to #vfs-platform-support telling developers
about the breaking change so that they can be on the lookout for it.

## Risks
The risks are minimal however since we already use git hooks using them for this scenario could lead users to get overwhelmed
and ignore our messages from git hooks altogether. 

## Alternatives
We could also implement a specific Slack channel for breaking change notifications however most of our developers already
belong to numerous Slack channels and have turned off notifications for them. It is also very easy for a Slack notification
to get buried since we get so many of them a day.

We could have the developers send out an email to the other engineers telling them about the change however this could add
additional work to our developers' already heavy workload. It would also be quite easy for these emails to get buried as
many of our developers get many emails per day.

**Comment by cohnjesse** [comment]
@cvalarida CCing you

**Comment by cohnjesse** [comment]
Here is a potential git hook that could be used on local environments

#!/bin/sh

CHANGED=`git diff HEAD@{1} --stat -- $GIT_DIR/../yarn.lock | wc -l`
if [ $CHANGED -gt 0 ];
then
    echo "the yarn.lock file changed"
    echo "You will most likely need to run 'yarn install'"
fi

**Comment by gunsch** [comment]
cc @rianfowler (OOO this week) @bkjohnson for other thoughts

OK, now that I'm looking at this more closely --- it sounds like by "breaking changes committed", you mean "developers have to run `yarn install`", not "the codebase doesn't build"? I think we have a pretty low rate of breaking changes (https://circleci.com/build-insights/gh/department-of-veterans-affairs/vets-website/master shows 100% success the last 3 weeks).

Reading this... isn't running `yarn install` after `git pull` pretty standard workflow for frontend codebases? 🤔 I'm not sure this is something we should be going to the trouble of automating in our codebase, I don't think we're particularly special in this regard.

Some other related links/discussions:
* [Automatically install dependencies on yarn start](https://github.com/facebook/create-react-app/issues/3796), from Facebook's `create-react-app`, in which they suggest that automatically running `yarn install` in a codebase with `npm` and `yarn` is probably not a great idea
* [yarnhook](https://github.com/allybee/yarnhook), which seems to be a package that automatically runs `yarn install` every time `yarn.lock` changes (probably not what we want)
* [Why I never have to run `yarn install` again](https://medium.com/@theshinytuxedo/i-never-have-to-run-yarn-install-again-50e112399d47), in which someone describes how to set this up for your own local workspace

I'll leave this to @cvalarida and @rianfowler (OOO this week) to make a call on whether or not we should implement this, but my 2c is that this is probably not the kind of developer tooling change we want to impose on everyone. Maybe our repo setup instructions could link to some advice on how to do this locally?

**Comment by cvalarida** [comment]
The more I think about this, the more I'm of the opinion that it's a cool tool that we can provide engineers if they want to use it, but since updating the installed dependencies is a normal enough task, I think we should give folks the choice to opt into it.

@cohnjesse I'd recommend you test run that git hook for a while, and if you find it useful, make a PR to the documentation somewhere (I can help you figure out where when we get there) to add a little blurb like:

> ### My `node_modules` keep getting updated on me!
> Because there are many engineers working in `vets-website`, some dependencies are updated really frequently. `vets-json-schema` is an outlying offender. If you don't re-install your dependencies when this happens, your local build can break in weird ways.
> To help remind you when to update your installed dependencies, you can put the following script in `vets-website/.git/hooks/post-merge`:
> ```sh
> # script goes here
> ```

**Comment by bkjohnson** [comment]
Yeah, my thoughts echo what has already been written.  When I run into errors with the site not building I'll run `yarn` again to update things, but I can imagine that a VFS engineer might get frustrated if they have to do this several times a day. Just because I don't think that something would make a big difference to _me_ doesn't mean that it wouldn't help others.

I agree with Chris that testing that example script with your regular workflow seems like a good starting point. If it reduces frustration then it may be good to communicate it out to others and have it accessible in the repo.

Right now I don't see a super strong value in having a server hook or CI process that sends out a slack message saying something like "`yarn.lock` was changed" (communicating that after a `git pull` seems more likely to have an effect), but I'm not against it if enough engineers are encountering this problem and feel like that would help them avoid it.

Do you encounter breaking changes other than `node_modules` being out of date or missing?

**Comment by rianfowler** [comment]
Optional script sounds good to me. 

https://www.thoughtworks.com/insights/blog/pre-commit-don-t-git-hooked

**Comment by cohnjesse** [comment]
@cvalarida @rianfowler @bkjohnson  For sure,  I definately don't think running `yarn install` automatically is a good idea, I am really more looking for ways to alert users that there are changes that require them to run it ( and the yarn thing is just one example, we have also had changes like gem versions updating or ruby versions changing in the vets-api which have the same effect but require different steps to fix). Usually when we run `git pull` there are tens if not hundreds of files that changed and knowing when something mission critical changed is really what I am trying to alert folks of. The steps to fix the issue are often straight forward, its just that knowing that you need to fix something often isn't or what you need to fix isn't. I will use the git hook for a while and see how it goes and if it helps I'll put in a PR for it and post about it in the appropriate Slack channels so peeps can have easy access to it.
