### ISSUE TITLE
Placeholder 526 Paper sync: Add payment question 29

### ISSUE THREAD

**Issue by christinec-fftc** [department-of-veterans-affairs/va.gov-team#61887]
Add question 29 "I certify that i do not have an account with a financial institution or certified payment agent"

![image.png](https://images.zenhubusercontent.com/641341411444ec27c3eb60a4/8fb4ce65-a85c-4471-9c2f-e7fcc3192703)

Screenshot of existing digital form (does not contain this question)
![image.png](https://images.zenhubusercontent.com/641341411444ec27c3eb60a4/a3fcfb12-102e-4a47-864f-02817bd8809c)

**Comment by lydiahooper** [comment]
@christinec-fftc We are removing payment screens so this does not need to be done. 
Ticket in backlog with more info: https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/57828
