### ISSUE TITLE
Placeholder 526 Paper sync: Add unit info questions 21D and 21E

### ISSUE THREAD

**Issue by christinec-fftc** [department-of-veterans-affairs/va.gov-team#61886]
Add questions 21D and 21E to the online form for
21D Current or last assigned name and address of unit
21E Current or assigned phone number of unit

![image.png](https://images.zenhubusercontent.com/641341411444ec27c3eb60a4/8ab8c966-367f-46ff-8f22-b0ba3f95c257)

**Comment by lydiahooper** [comment]
Combined this work with other related ticket: https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/61883
