### ISSUE TITLE
[Design/FE] - Email input has regex style error message that's not helpful

### ISSUE THREAD

**Issue by davidakennedy** [department-of-veterans-affairs/va.gov-team#61888]
## Background

In the email address section of the form, if you enter an invalid email address, you get an error message, but it's not one that Veterans would understand. See screenshot.

![Email error message with a really long regex pattern.](https://github.com/department-of-veterans-affairs/va.gov-team/assets/1473618/4dd9a463-f8ff-4682-a6d9-a89ac2b89053)

Another thing we might want to do is look at any similar fields to see if there are other unhelpful error messages. That could be another ticket though.

Props @briandeconinck for finding this one during accessibility testing for an upcoming staging review.

### For this ticket

We want to update the error message to be plain language and sync with the other error messages in the form.

## Tasks

- [x] Determine the right content for the error message (Design).
- [x] Implement content changes (Engineering).

## Acceptance Criteria

- Plain language error message replaces current regex style message.

**Comment by longmd** [comment]
@davidakennedy , what're you thinking for the verbiage here? My default go-to would be "Please enter a valid email address."

**Comment by davidakennedy** [comment]
@longmd Yep, that's perfect.

**Comment by longmd** [comment]
@davidakennedy , so it looks like just a bug in the actual form system itself. This is the message they have in their component: `Enter a valid email address using the format email@domain.com. Your email address can only have letters, numbers, the @ symbol and a period, with no spaces.`. Im going to fix their bug and that will be what is displayed.

**Comment by longmd** [comment]
Local screenshot with fix in place:
![Screenshot 2023-08-02 at 2 51 50 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/6738544/b411f86c-2c27-41f3-8aab-0116ad6c5310)
