### ISSUE TITLE
QA Standards - 10-10 Health Apps - 10-10EZ

### ISSUE THREAD

**Issue by it-harrison** [department-of-veterans-affairs/va.gov-team#61889]
#### VFS team name
10-10 Health Apps
#### VFS product name
10-10EZ

#### VFS feature name
Household Information Optimization
#### Point of Contact/Reviewers
@it-harrison - Ian Harrison - QA

---
#### Regression Test Plan 
- [x] Standard has been met
- [ ] Standard has not been met
#### Test Plan
- [x] Standard has been met
- [ ] Standard has not been met
#### Traceability Reports 
- [x] Standard has been met
- [ ] Standard has not been met
#### E2E Test Participation
- [x] Standard has been met
- [ ] Standard has not been met
#### Unit Test Coverage 
- [ ] Standard has been met
- [x] Standard has not been met
##### Explanation of failure to meet standard (if applicable): #####
Coverage for functions and branches are a little below the 75% goal.

---
### VFS Guidance

- Close the ticket when your Product Owner determines that you have sufficiently met the QA Standards.
- If your team has additional questions or needs Platform help validating the issue, please comment on the ticket

### Platform directions
- Update "Issue Title" to be of the form "QA Standards - VFS Team - VFS Product"
- Add the VFS team, product name, and feature name
- Add your name, practice area, and GH handle under Point of Contact/Reviewers
- Complete the QA Standards section, making sure to include an "Explanation of failure to meet standard" for every Standard the product does not meet.
- Link to the Collaboration Cycle Request epic
- Add assignees: 
  - VFS PM
  - Yourself (optional)
- Add labels:
  - VFS team label
  - VFS product label
  - QA-standards label
  - launch-blocking label if the product has failed to meet a required QA Standard

**Comment by hdjustice** [comment]
We are in progress of raising the unit test coverage - [#60897](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60897)

**Comment by hdjustice** [comment]
Closing ticket - we have another ticket we are actively working to raise the Unit Test Coverage.
