### ISSUE TITLE
Add email/user to Test User Dashboard

### ISSUE THREAD

**Issue by bdech** [department-of-veterans-affairs/va.gov-team#61898]
From: Robert Rodriguez: Request to add user/email to Test User Dashboard 

KARSYN.GPSYSASYNCTWO@ID.me

https://dsva.slack.com/archives/CBU0KDSB1/p1689090338890219

There isn't a defined process for this request. Pete Hill suggested creating a ticket for Backend COP to accomplish

**Comment by rmtolmach** [comment]
Thanks, Brandon! I removed the support label and added `platform-cop` so it shows up on the CoP board.

**Comment by holdenhinkle** [comment]
User can still be used even if it's not in TUD. Super TUD is in the pipeline. Closing this.
