### ISSUE TITLE
Implement monitors and create "526 Monitoring Package"

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#61907]
Some initial thoughts here: 

https://docs.google.com/document/d/13Bbkb5qjmVeCJ3pQlpcpb_Vib_DawjjvSZxHSK6XVbk/edit

Acceptance criteria:
1. What dashboards have we created?
2. What work have we completed that should/can be incorporated in a dashboard (e.g. 3pi work and/lor RUM?)
3.  Where has data dog worked, where does it not work? What data can we not pull in?

Output: "This is 526 monitoring package" that includes:

1. Here is what we had
--initial KPIs from Kyle and some initial monitors
2. Here is what we have added
--list of new monitors, what they measure and why?
3. What are next steps (e.g. playbook) 
--Playbook and dissemination (just list these as next and new ticket to complete)

**Comment by austinjprice** [comment]
Determine how to best present database in GUI, tools needed, etc..

**Comment by tblackwe** [comment]
Discussed with @zyellowhorse earlier today to help with DataDog research.

**Comment by SamStuckey** [comment]
[Document Tracking ideas for possible new health metrics](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/engineering_research/possible_new_health_metric_research.md)

**Comment by SamStuckey** [comment]
[PR adding some logging to allow for latency dashboards](https://github.com/department-of-veterans-affairs/vets-api/pull/13908)

**Comment by austinjprice** [comment]
Changed name to be more accurate to the work. will discuss remaining work to close out this ticket in planning
