### ISSUE TITLE
Technical Architecture of Solution

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#61917]
## Goals
- [x] Summarize Technical Implementation below
- [x] Create ticket for backend "ID verification" service
- [x] Create ticket for backend endpoint to utilize above service
- [x] Create ticket for front end message display component
- [x] Create ticket for investigating "Add Person" flow
- [ ] Create ticket for refactoring "Add Person" flow (if needed)
- [x] Create ticket for refactoring this flow on the front end to use the above pieces.
- [x] Create ticket for removing all remnants of ye olde flow.

## Technical Implementation Summary
In order to address the issues laid out in [this epic](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/61419), I'm proposing the following.

### Current Implementation
First, to summarize the way these messages are currently displayed, by order of operations:
1. On the front end we check if we have submitted an "Add Person" request to MVI for the user
2. If not, we do this, but appear to display a "Missing data" message even if that succeeds?
3. We check if DOB is missing and if so, display a message saying that.
4. We make a bunch of arbitrary checks against the "services" a user has access to and display inaccurate or misleading messages accordingly.

### New Implementation
What I'm proposing instead is, by order of operations:
1. We still attempt to add the User to MVI if necessary, but we figure out how to actually handle this properly.
2. Once that's completed, we hit a new endpoint that validates we have the necessary informaiton for the user to allow them to proceed to complete 526EZ. If we don't, return a list of exactly what we are missing.
3. If we are missing information, render a standard boilerplate message that prompts the user to reach out to a contact center and displays exactly which data is missing.

### Iterative Build Schedule
The order in which I would implement and PR this is:
1. Build backend "ID verification" service which checks for the presence of the missing IDs on the user record and returns a list of missing IDs, if any.
2. Build backend endpoint to utilize above service which returns a list of missing data if there is any.
3. Build front end message display component with standard boilerplate language agreed upon in the [research ticket](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/61915), which displays the language and a summary of the missing data.
4. Refactor "Add Person" flow. The current flow is confusing and nonsensical. Research required.
5. Tie everything together into a new flow on the front end that uses the new endpoint at the right moment and displays the new component accordingly.
6. Remove the naughty old infrastructure one the front end once we don't need it anymore.

**Comment by NB28VT** [comment]
Technical Solution Architected, will mark this ticket done once I create tickets for all of the pieces of the refactor, which I plan to implement iteratively (shorter PRs, clearer progress, isolated commits FOR THE WIN)
