### ISSUE TITLE
Identity Dashboard (FE) - Create refresh ability

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#61913]
## Description
Add refresh capability for Identity Dashboard

## Tasks
- [x] Add an ability for refresh to get called using either method below
  - [x] Automatically called every 4 minutes until a user signs out (see vets-api, lib/flipper/views/layout.erb)
  ~- [ ] Only on failed 403: Access token has expired (see vets-website, apiRequest + retry-fetch)~
  ~- [ ] Some other option not listed (see https://authjs.dev/guides/basics/refresh-token-rotation#client-side)~

**Comment by aparsley** [comment]
Keep up the good work!
