### ISSUE TITLE
create tasks for campaign workflow for Inform phase

### ISSUE THREAD

**Issue by djmunoz1** [department-of-veterans-affairs/va.gov-team#61910]
As a campaign admin I need a workflow for push and pull campaigns so that I understand how to implement tasks for the Inform phase.

ACCEPTANCE:
 create email flowchart for a drip campaign that considers:
- reactivation cohort
- organic cohort
- mhv and dsl segmentation
- retargeting messaging for veterans who do not take desired behavior
- nurturing messaging for veterans who take desired behavior 
- timing between messages
- 'pull' marketing actions (i.e. can veterans subscribe to a campaign list?)
- other marketing channels (e.g. social media)
- 
DEF DONE:
- Inform phase workflow for drip campaigns and multichannel comms is detailed in [Release v2 Mural](https://app.mural.co/t/innovationboards1199/m/innovationboards1199/1688133032414/e747c01cb55c142d7e727f990ba336a6667be9d7?sender=uc3c8b97062727fbe21716300)
- Product and Design Leads are tagged for review

**Comment by lmorris3** [comment]
Closing, completed.
