### ISSUE TITLE
Mock up "Need More Info: Error Message with improved language

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#61915]
[Overview (non-technical) on existing messages](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/engineering_research/526_entry_error_discovery.md)

To summarize, this appears to be the data required at the moment to begin the 526 flow:

* Date of Birth
* SSN
* BIRLS ID (Beneficiary Identification and Records Locator (Sub)System)
* EDIPI (Electronic Data Interchange Personal Identifier)
* Participant ID

Acceptance Criteria:

1. Modify language of the Error message so that it can display any combination of the above missing data points
2. Get approved through appropriate channels
3. Update implementation ticket with approved mock up

**Comment by juliepedtke** [comment]
[CAIA intake ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=RLHecht%2C+coforma-terry%2C+kristinoletmuskat%2C+laurwill%2C+sara-amanda&labels=sitewide+CAIA%2C+sitewide+content-product+support%2C+Sitewide+IA%2C+sitewide+content%2C+sitewide+accessibility&projects=&template=sitewide-content-intake-form.md&title=%3CType+of+Request%3E+from+%3CTeam%3E) (once we've gotten input from contact center and have draft language ready)

**Comment by NB28VT** [comment]
Updated the ticket with some general info for y'all. @juliepedtke I was going to reference the "recover from errors" design pattern mentioned by Lydia in [this ticket](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/60420), but it looks like you found it already, awesome.

Feel free to tag me here if I can help in any way

**Comment by NB28VT** [comment]
Just got some good insight from Aurora here - it appears `participant_id` may be getting sunsetted by Lighthouse/is no longer supported by Lighthouse, so in your research if you come across a contact/know of a contact who can verify that let me know. FYI @juliepedtke @nnicholas7 @austinjprice

**Comment by austinjprice** [comment]
Removed block and added acceptance criteria

**Comment by sortizsh** [comment]
@nnicholas7  can you please add the approved text here?

**Comment by sortizsh** [comment]
@austinjprice  can you create a FE ticket for Nathan?

**Comment by nnicholas7** [comment]
CAIA (Beth Potts) has provided us with feedback based on style and voice standards for the VA and approved the following message for this error:

Header: We need more information for your application

Body: We’re missing your [insert missing identifier(s) here—and if there are 2 or more, just connect each with commas (including Oxford) and “and”]. We need this information before you can file a claim for disability compensation.
Call us at 800-827-1000 (TTY: 711) to update your information. We’re here Monday through Friday from 8:00 a.m. to 9:00 p.m. ET. Tell the representative that you want to add this missing information to your file.

**Comment by NB28VT** [comment]
> CAIA (Beth Potts) has provided us with feedback based on style and voice standards for the VA and provided the following recommended message for this error:
> 
> Header: We need more information for your application
> 
> Body: We’re missing your [insert missing identifier(s) here—and if there are 2 or more, just connect each with commas (including Oxford) and “and”]. We need this information before you can file a claim for disability compensation. Call us at 800-827-1000 (TTY: 711) to update your information. We’re here Monday through Friday from 8:00 a.m. to 9:00 p.m. ET. Tell the representative that you want to add this missing information to your file.

🎉 awesome thank you!

Quick question for them: how do they want each of the missing identifiers displayed? Here is what I have now. The values on the left are the name of the identifier in the database, the ones on the right are what they will be displayed as. Does this work for them or do they want any of these changed?

```
    particpant_id: "Participant ID",
    birls_id: "BIRLS ID (Beneficiary Identification and Records Locator (Sub)System ID)",
    ssn: "Social Security Number",
    birth_date: "Date of Birth",
    edipi: "EDIPI (Electronic Data Interchange Personal Identifier)",
```

**Comment by austinjprice** [comment]
Based on convo with EVSS help-desk who ultimately fixes these, the user will likely not know what these so the goal is to keep the language as simple as possible for the User to say them, the Contact Center to record them. Since thats the goal Id recommend we remove the parentheticals and just use "Participant ID", "BIRLS ID", "Social Security Number", "Date of Birth" and "EDIPI"

**Comment by juliepedtke** [comment]
I agree with what Austin suggested! Concision seems more important here, since the user wouldn't know what these are even when they're expanded.

**Comment by NB28VT** [comment]
Got it @austinjprice @juliepedtke , yeah we had some existing hover over tooltips describing what those acronyms mean so initial thought is we would want to clarify so the if the user comes across those terms they know what they are. But based on what you heard from the Contact Center and the logic above I agree with y'all. Will keep it simple thanks!

**Comment by nnicholas7** [comment]
Item to consider, but not a design recommendation:
According to the VA style guide for the structure of an error message, I noticed the layout is title, description, and button or link.  This message doesn't have the button or link that is described in the [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaWRSIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ff216ad201c5bf49a352456c71b245cacdcc322f/Screenshot%202023-08-30%20at%208.26.48%20AM.png)
style guide. 

Error Message Layout Style Guide- https:[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaWhSIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ba42aa5703f9971d5665860cca9f3c5fc4933143/Screenshot%202023-08-30%20at%208.26.59%20AM.png)
//design.va.gov/patterns/help-users-to/recover-from-errors
