### ISSUE TITLE
Cleanup bulkhead deployment

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#61923]
### PROBLEM STATEMENT
The deployment was failing and the processes to fix the deployment are currently unclear for engineers on platform.

### ACCEPTANCE CRITERIA
- [ ] Bulkhead deployment is cleaned up
- [ ] Clear documentation on processes to fix (troubleshooting)

**Comment by RachalCassity** [comment]
https://app.zenhub.com/workspaces/platform-tech-team-1-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/vsp-infra-application-manifests/2081
