### ISSUE TITLE
Design Solution for Improved Review and Submit Evidence Validation

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#61922]
The Review and Submit section of the 526 Form currently presents the following usability issues:

- While some sections of the form can be edited on this page, the evidence section has a validation error where the user can edit part of their response, but not the documentation that was uploaded in that section. This results in a red alert, but no way for the user to navigate back to that page without using the "back" button incrementally to go through every page since. See screenshots in the [form flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1686768383603/3f4415dd2ddb71bbd104ebefd92a2c7b553ad792?sender=udbd39c1bbebb4ec4d7d08829).

We are looking to offer a short-term solution through research and design, such as including a link that would take users directly to the evidence section, then back to Review and Submit once the change is made. 

VA Platform content style guide for error messages:
https://design.va.gov/content-style-guide/error-messages/
https://design.va.gov/patterns/help-users-to/recover-from-errors

Acceptance Criteria

- [x] Update the 526 Error Message Tracker with the ticket number and details
- [x] Check with Team 1 on plans to redesign this page
- [x] Brainstorm short-term solutions for the Review and Submit validation error
- [x] Mock up best ideas and reference style guides and design system to ensure consistency
- [x] Depending on the extent of the change, reach out to CAIA team on Slack to see if more support is needed ([notes on this process here](https://docs.google.com/document/d/1q6rBmp4rjou1tiSknJzaS15mvDbUXIJQOEgD8rKgjTY/edit)) 
- [x] Check with engineering on the technical lift for various solutions
- [x] Present one proposal for feedback from VBA stakeholders to ensure alignment
- [ ] Handoff to engineering for implementation

**Comment by nnicholas7** [comment]
Sprint 8- 7/17-8/1/2023
Deliverables
- Error Message Mock Up (Sketch)- https://sketch.com/s/b9586d37-c195-423b-aa29-1e8ec655c2ce
- Review and Submit Error Message Decision Tree (Mural)- https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1690817339845/a1489c4116120a37175b7e868df627a31241d313?sender=u813bb40bd648bc2b58599242

**Comment by nnicholas7** [comment]
Sprint 9- 8/2-8/15/2023
Deliverables
- Review and Submit Mockup (Sketch)-  https://sketch.com/s/b9586d37-c195-423b-aa29-1e8ec655c2ce
Update
- VBA has reviewed the Review and Submit screens and approved a selection. Selection noted in Sketch file. There is still research needed on whether the screen can be created in a mobile-friendly version.

**Comment by sortizsh** [comment]
still a known issue, but it ranked pretty low in prioritization exercise.

**Comment by juliepedtke** [comment]
After conversation with stakeholders we moved away from this short-term solution (including a link that would take users directly to the evidence section, then back to Review and Submit once the change is made) because it was too clunky and introduced other usability concerns. There are still known usability issues with the Review and Submit page (which impact all forms that use this pattern), but we have not prioritized this as an area to explore in the near term. We can close this ticket.
