### ISSUE TITLE
ITF Message and Expiration UX Design (message and experience) 

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#61921]
As part of the ITF research it was discovered that Veterans are presented with a message indicating the expiration of their ITF that is inconsistent with the actual expiration date.

As part of this story, we need to update the user experience by incorporating the lenient definition of "1 year since the submission of ITF".

The goal of this story is narrow and only focuses on improving the expiration date experience. Further improvements to the  impact of the expiration will be handled elsewhere

Acceptance criteria:
1. Message Veteran receives about ITF date is clear and understandable
2. Actual expiration date and time is consistent with what the user is presented with in the message
3. Edge cases like leap year, time zone changes are considered and accounted for

**Comment by micahaspyr** [comment]
@juliepedtke @austinjprice I have an example of the time formatting being changed here. I made the text bold to make it stand out a bit more.  Thoughts?
<img width="709" alt="Screenshot 2023-08-23 at 11 31 02 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/6454840/3a94bab4-db8b-4e22-94fd-c9b1a3ee987c">

**Comment by juliepedtke** [comment]
A tiny suggestion, could we add "at" so it would read "Friday, August 28, 2015 at 2:52 p.m. ET"? I think that would make it a bit more readable since it's a lot of numbers in a row. 

Otherwise looks consistent with the [design system](https://design.va.gov/content-style-guide/dates-and-numbers#times-and-time-zones ) - note that if there is a time that's exactly on the hour, we should still include the minutes (2:00 p.m. ET NOT 2 p.m. ET).

**Comment by juliepedtke** [comment]
Also is this a duplicate ticket with [#63748](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/63748)? We left a screenshot over there so just wanted to check!

**Comment by micahaspyr** [comment]
@juliepedtke it looks like a duplicate.  I'll move discussions over there

**Comment by austinjprice** [comment]
closing as duplicate
