### ISSUE TITLE
Publish verification videos

### ISSUE THREAD

**Issue by charlye-bluetiger** [department-of-veterans-affairs/va.gov-team#61943]
### Description of UX Tasks

- [ ] Discover who needs to approve hosting to official YouTube channel(s)
- [ ] Coordinate with appropriate teams to figure out where to host videos
- [ ] Coordinate with appropriate teams to publish videos and infographic
- [ ] Meet with Tim Hudak from VEO

#### Acceptance Criteria
- [ ] Reviewed by UX Team
- [ ] Reviewed by PMs
- [ ] Documentation has been updated
- [ ] Put published research in drive

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by joeniquette** [comment]
Working with Tom, may have another path for this soon.
