### ISSUE TITLE
Contact Center Review for [526 Disability Benefits Claims - Flow changes]

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#61945]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
[Disability Comp Application (21-526 EZ)](https://depo-platform-documentation.scrollhelp.site/getting-started/disability-comp-application-21-526-ez) This product enables veterans and active service member to file disability benefits claim via va.gov.

Purpose for this change:
This change is part of a larger initiative for making the 526ez form on va.gov in sync with the paper version.

Scope:
- Removed "Fully Developed Claim" page
- Moved Homeless and Terminally Ill pages to Veteran Details section 

Collab cycle ticket - [Collaboration Cycle for [Benefits Disability Experience, Disability Comp Application (21-526 EZ), Sync 526ez form with paper version]#56844](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/56844)

### Launch Date
End of July, 2023

### Version Number
*Please provide the version number of the guide and/or video.*
2.0

### Product Guide
[526ez Disability Benefits Claims Product Guide.docx](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/product/526ez%20Product%20Guide/526ez%20Disability%20Benefits%20Claims%20Product%20Guide.docx)

### Product Video
*Please provide product video link*

### Product Video Transcript
*Please provide product video transcript link*

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
On track for 8/1 sprint.

**Comment by starlow00** [comment]
Hi @RakshindaAslam. The guide looks good. I will submit it to VEO today for their review.

**Comment by starlow00** [comment]
No changes from VEO. Current draft attached.[https://app.zenhub.com/files/133843125/742cfb7d-8d98-4a38-8ea7-8300add206a1/download](https://app.zenhub.com/files/133843125/742cfb7d-8d98-4a38-8ea7-8300add206a1/download)
