### ISSUE TITLE
Sidekiq Admin UI access for [Derek Brown]

### ISSUE THREAD

**Issue by dbrown-va** [department-of-veterans-affairs/va.gov-team#61948]
### Your Name

Derek Brown

### Your GitHub handle (Sidekiq Admin UI access is managed through GitHub)

dbrown-va

### Your dsvagovcloud AWS user name (if applicable)

Derek.Brown

### Team, Role, and Company of the target individual

Team Pivot (Lighthouse), Software Engineer, Booz Allen (formerly Liberty ITS)

### COR Name

Cecila Lee

### Please confirm if you are on the VFS Team Roster or Platform Team Roster

- [X] [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Sidekiq UI Access requested for the following environments

- [ ] dev
- [X] staging
- [X] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### If PRODUCTION ACCESS is required, confirm/complete ONE of the following

- [X] I have an AWS Username and it is listed in [here](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf)
- [ ] I currently have access to vets-api Production Terminal via ArgoCD
- [ ] I've attached a screenshot of my E-QIP Transmittal Notice E-mail (Drag or Copy/Paste in Additional Notes Section below)

### Additional Notes

Access required for supporting 2 Lighthouse Sidekiq jobs for emailing consent & revocation events for the VA.gov Connected Apps page.

**Comment by bdech** [comment]
@dbrown-va It doesn't look like you've been added to the VFS Team Roster yet. You will want to reach out to your project manager so they can add you to the roster. Once you're added to the roster I will grant Sidekiq access

**Comment by dbrown-va** [comment]
> @dbrown-va It doesn't look like you've been added to the VFS Team Roster yet. You will want to reach out to your project manager so they can add you to the roster. Once you're added to the roster I will grant Sidekiq access

@bdech , confirmed my addition to the VFS Roster. 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/61981#issuecomment-1636273449

**Comment by bdech** [comment]
found in VFS Team Roster

**Comment by bdech** [comment]
@dbrown-va You've been granted access to `staging`, `sandbox`, and `production`. Production access is limited to 6 months, expiring 01/18/24.

**Comment by bdech** [comment]
slack thread [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1689687821049439)

**Comment by lindsay-insco** [comment]
@dbrown-va Production access has expired.

Would you like to request an extension? You have 72 hours to respond, or your
access will be revoked and you will need to fill out a new request

**Comment by dbrown-va** [comment]
Good morning @lindsay-insco , we were able to successfully migrate all Sidekiq jobs to event driven notifications.

Access can be revoked at this time.  Thank you

**Comment by lindsay-insco** [comment]
Access to Sidekiq `staging`, `sandbox`, and `production` removed for @dbrown-va
