### ISSUE TITLE
Database has been updated

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#61951]
### PROBLEM STATEMENT
TT1 has updated the script(s) used to complete a code inventory for vets-api, but we need a place to store the information so that it's able to be updated and accessible to the appropriate parties.

### ADDITIONAL INFORMATION
Link ticket from previous sprint

### ACTION ITEMS
- [x] Complete v2.0+ of database 
- [x] Populate database with inventory data
- [ ] Marking code as 'dead' (moved to own ticket)
- [x] audit log feature explored (added to automation discovery)

### DEFINITION OF DONE
- [x] Database 2.0+ is populated with output from updated script

**Comment by LindseySaari** [comment]
Lindsey: Ran snippet in console to update console-services-team to backend-review-group.

Eric: Worked on generating codeowners from Database. Someone can pick this up.

For script: If all files in a directory have the same owners (could be multiple), only show the directory in the Codeowners.

Lindsey: Working on softdelete

**Comment by laineymajor** [comment]
Need to create a process with the gov team
- what does it look like when a team is removed?
- when a service is removed/no longer supported?
- when endpoint(s) are no longer supported?
