### ISSUE TITLE
Discovery: How might we create an automated library for vets-api code?

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#61955]
### PROBLEM STATEMENT
As TT1 works to identify owners of code, we are discovering why and how this information can easily and quickly go stale. 

How might we develop processes to keep information in our code inventory accurate?

## Ideas to keep things not stale
1. Recurring job? - Compare the team names and the github team names to the spreadsheet. If different - do something. Can we maintain this? 
2. Keep Codeowners up to date - Combination of GHA and Governance?
3. How to keep all the actual GH teams up to date - Governance Team? 
4. What to do if a team is renamed?
5. If codeowners changes - Update the db - via Github actions?
6. When new files are added, they need a codeowner entry - Github Actions
7. Keeping historical data around folks who have off boarded
8. Work with governance team to ensure there are no gaps from onboarding -> roster
9. How might we be better at maintaining historical data (ex: users on what teams)?
10. Governance - establish a standard for onboarding around slack profiles and having a minimum set of information
10. Should we enable/push an allowlist model similar to what FE did with vets-website... what would the requirements be to get on and remain on the allowlist

## Deployment ideas
1. We will most likely need sidekiq
2. Moving the deployment to k8s in house
3. A PG instance
4. Write manifests

### ACTION ITEMS
- [ ] Add options to a confluence page

### DEFINITION OF DONE
- [ ] List of recommendations (linked here) for keeping the inventory is up-to-date and automated as possible.

**Comment by LindseySaari** [comment]
## Ideas to keep things not stale
1. Recurring job? - Compare the team names and the github team names to the spreadsheet. If different - do something. Can we maintain this? 
2. Keep Codeowners up to date - Combination of GHA and Governance?
3. How to keep all the actual GH teams up to date - Governance Team? 
4. What to do if a team is renamed?
5. If codeowners changes - Update the db - via Github actions?
6. When new files are added, they need a codeowner entry - Github Actions
7. Keeping historical data around folks who have off boarded

## Deployment ideas
1. We will most likely need sidekiq
2. Moving the deployment to k8s in house
3. A PG instance
4. Write manifests

**Comment by laineymajor** [comment]
Lainey to pull this back up half way through the sprint... divide and conquer

**Comment by LindseySaari** [comment]
Started on a branch with some sidekiq job pseudocode for automation: https://github.com/department-of-veterans-affairs/platform-codeowners/compare/lh-automatic-updates-sidekiq-jobs

**Comment by laineymajor** [comment]
We'll be meeting tomorrow as a team to review discovery and turn to action.
