### ISSUE TITLE
Adding Tanner Heffner to DSVA Slack

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-team#61969]
# Description
Please add Tanner Heffner (tanner.heffner@agile6.com) as a **full member**. Note that Tanner Heffner was previously a Slack member and was deactivated. He is back with a VA project and will need to be in Slack.

Tanner will be Tech Lead for the Accelerated Publishing team, contract starting 7/13/2023. He will need free access to Slack and Slack history to effectively perform his role.

**Comment by KevinMHoffmanUSDS** [comment]
Reactivated.

**Comment by timcosgrove** [comment]
@KevinMHoffmanUSDS Tanner has received his invite to Slack, but it is asking him for 2FA backup codes that he no longer has (they were with a prior work laptop which he returned). How should he proceed?

**Comment by tjheffner** [comment]
Is there a mechanism by which I can reset my 2FA for the DSVA slack? It is currently tied to an old phone, and the backup codes were on an old work computer I no longer have access to (and was presumably wiped)

**Comment by tjheffner** [comment]
@EWashb Thank you! I am in the DSVA slack and I have a new 2FA set up for my account again. Appreciate the help!
