### ISSUE TITLE
Configure BE pod to use correct image

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#61964]
# Description
TT1 indicated that we are using a vets-api image based on main, but we should be using the image based on the k8s branch. Based on this recommendation, we will plan to change our setup to reflect that.

# Tasks
- [x] Swap out references in our manifest(s) to the main image for references to the k8s image

# Acceptance Criteria
- [x] A BE container starts up and serves the status page using the new image

**Comment by pjhill** [comment]
This was completed.
