### ISSUE TITLE
Interview Memorials Team

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#61974]
### Teams to check with:
Memorials Self-Service Team. PM is Cat Hughes [#54528](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54528)

Form Name: Pre-Need Determination of Eligibility for Burial in a VA National Cemetery
Number: VA Form 40-10007
Link: https://www.va.gov/burials-and-memorials/pre-need/form-10007-apply-for-eligibility/introduction

What was their experience?
What worked?
What didn't work well?
What were big pain points

## Tasks
- [x] Conduct interviews/meetings
- [x] Capture [notes](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2716663809/Notes+from+Memorials+workshop)

## Acceptance Criteria
- [x] Notes captured

**Comment by twoangstroms** [comment]
Still adding notes, may roll over
