### ISSUE TITLE
Adding Daniel Schiavone to DSVA Slack

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-team#61971]
# Description
Please add Daniel Schiavone (daniel.schiavone@civicactions.com) as a **full member**. Note that Daniel Schiavone was previously a Slack member and was deactivated. He is back with a VA project and will need to be in Slack.

Daniel will be a backend engineer for the Accelerated Publishing team, contract starting 7/13/2023. He will need free access to Slack and Slack history to effectively perform his role.

**Comment by KevinMHoffmanUSDS** [comment]
Reactivated!
