### ISSUE TITLE
BE | Profile | Grant Adrian and Pam access to feature flipper

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#61997]
## Background
Add our new joiners to the [yml file](https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/settings.yml) for feature toggle access. 

Email addresses will be shared via slack

For reference, here are the feature Admin URLs for each environment:

https://dev-api.va.gov/flipper/features
https://staging-api.va.gov/flipper/features
https://api.va.gov/flipper/features

## Acceptance Criteria
- [x] New joiners have been added to the yml file
- [ ] confirm they have access to the feature toggle page

**Comment by tpharrison** [comment]
@Adrian-Brewster @pamela-drouin 

You should have admin access to feature toggles.  Please verify when you have a chance.  Let me know if you need help.
