### ISSUE TITLE
Incorrect link on "Adding applications and features" page

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#61994]
### Description

In the [Applications section](https://depo-platform-documentation.scrollhelp.site/developer-docs/adding-applications-and-features#Addingapplicationsandfeatures-Applications) of the "Adding applications and features" page, the "applications" link points to a VFS confluence page. I believe it should instead point to [https://depo-platform-documentation.scrollhelp.site/developer-docs/creating-a-new-application](https://depo-platform-documentation.scrollhelp.site/developer-docs/creating-a-new-application).

### Relevant URLs

- https://depo-platform-documentation.scrollhelp.site/developer-docs/adding-applications-and-features
- https://depo-platform-documentation.scrollhelp.site/developer-docs/creating-a-new-application

### Which type of team are you on? (Platform team, VFS team, or Leadership)

OCTO

**Comment by vbellissimo** [comment]
@acrollet , thanks for flagging this! We will be correcting this shortly. Thank you.

**Comment by taylojill** [comment]
Hi @acrollet The link has been updated. The page will deploy Monday after 3:30pm. Thanks!
