### ISSUE TITLE
GitHub Access Changes

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-team#61999]
### Description

It has been shared with me that some teams have trouble using our GitHub access information when teams are moving into the VA.gov space for the first time. These teams do not have a program manager who has access to GitHub so they cannot create a request for access because those managers don't have a GH account either. We need additional information that details what to do when our step 1 isn't possible. The GitHub Handbook provides the best information for this case, so I have linked it below. 

The GitHub handbook is the single source of truth on this, so it may be best just to link there.

### Relevant URLs

[Platform Website link
](https://depo-platform-documentation.scrollhelp.site/getting-started/request-access-to-tools#Requestaccesstotools-GitHub)[GitHub Handbook
](https://department-of-veterans-affairs.github.io/github-handbook/guides/onboarding/getting-access)

### Which type of team are you on? (Platform team, VFS team, or Leadership)
VA Leadership

**Comment by vbellissimo** [comment]
Hi @EWashb , thanks for letting us know. I'll create a task for someone on the team to incorporate the link to the VA GitHub Handbook.
