### ISSUE TITLE
Sidekiq Admin UI access for Jennica Stiehl

### ISSUE THREAD

**Issue by stiehlrod** [department-of-veterans-affairs/va.gov-team#62000]
### Your Name

Jennica L Stiehl

### Your GitHub handle (Sidekiq Admin UI access is managed through GitHub)

@stiehlrod

### Your dsvagovcloud AWS user name (if applicable)

Jennica.Stiehl

### Team, Role, and Company of the target individual

Dash | Engineer | Oddball

### COR Name

Cecila Lee

### Please confirm if you are on the VFS Team Roster or Platform Team Roster

- [X] [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Sidekiq UI Access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### If PRODUCTION ACCESS is required, confirm/complete ONE of the following

- [X] I have an AWS Username and it is listed in [here](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf)
- [X] I currently have access to vets-api Production Terminal via ArgoCD
- [X] I've attached a screenshot of my E-QIP Transmittal Notice E-mail (Drag or Copy/Paste in Additional Notes Section below)

### Additional Notes

![Screenshot 2023-07-14 at 7 57 00 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/25069483/87771263-120d-49e5-843a-47a055dc3e8b)

**Comment by bdech** [comment]
@stiehlrod You've been granted access to all environments, with access to Production limited to 6 months, expiring, 01/14/24

**Comment by bdech** [comment]
slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1689343668883379)

**Comment by lindsay-insco** [comment]
@stiehlrod Your Production access has expired.

Would you like to request an extension? You have 72 hours to respond, or your
access will be revoked and you will need to fill out a new request.

**Comment by lindsay-insco** [comment]
@stiehlrod your Sidekiq `production` access has expired. If you need continued access please fill out a new request.
