### ISSUE TITLE
GIDS: Institution CSV is blank on export

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#6201]
When attempting to export the institutions csv from gids, the file is downloaded but contains no data. This applies to the latest production version, preview version, and all archived versions. 

1. Log into GIDS
2. Under Latest Production version click Download Export CSV
3. If there is not a preview version, click Generate Preview Version
4. Click Download Export CSV for the preview version
5. Click "Archives" in the header
6. For any archived version, click Download Institution CSV

All Institution CSVs are downloaded but contain no data

**Comment by zurbergram** [comment]
To test 
- generate a preview
- in pgadmin change the number value of the verisons row that was just created from preview generation, id should not equal number for the row
- refresh dashboard, preview should now show the new "number" you set
- export the preview version

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/590

**Comment by delli-gatti-michael** [comment]
On Staging
Current and Preview versions can both be exported with valid data. 
On the Archives Tab, the furthest back you can go is 95. Version 94 and before are still blank on export

**Comment by delli-gatti-michael** [comment]
Defect related to version 94 and before will be covered by a separate issue. Closing this as complete
