### ISSUE TITLE
Requesting documentation on VA.gov session timeout behavior

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#62033]
### Description

Occasionally developers and other stakeholders need to know what the exact session timeout behavior is on VA.gov. AFAIK there is no existing documentation on this. After some research, my understanding is as follows:

> The session timeout is 30 minutes and is extended for another 30 minutes (up to a maximum of 12 hours) each time an API call is made to `vets-api`. At the end of the session, a modal will pop up giving the veteran 30 seconds to continue their session before they are automatically logged out.

### Relevant URLs

Platform support discussion: https://dsva.slack.com/archives/CBU0KDSB1/p1689347092230189

Code references:
- https://github.com/department-of-veterans-affairs/vets-api/blob/dc30ac0269458c4cc28e46dddc18af3951d490dd/app/models/session.rb#L14
- https://github.com/department-of-veterans-affairs/vets-api/blob/dc30ac0269458c4cc28e46dddc18af3951d490dd/config/redis.yml#L9
- https://github.com/department-of-veterans-affairs/vets-website/blob/692da53ce1dad97aa8f92c21b879f076efd450c7/src/platform/user/authentication/components/SessionTimeoutModal.jsx#L106

### Which type of team are you on? (Platform team, VFS team, or Leadership)

OCTO

**Comment by vbellissimo** [comment]
Hi @acrollet , thank you for flagging this for us. We'd be happy to make sure this exists on the Platform website. I reviewed the original support request you made in Slack and I see that Mike Chelen also aligned with you on the content you're request we add. 

**Question for you...** Based on the info I saw in Slack, it looks like it was categorized as "backend" related.

- Is there a specific page you believe this belongs to within the [Backend developer documentation](https://depo-platform-documentation.scrollhelp.site/developer-docs/backend-developer-documentation) of the site? We'd love to see where it makes sense for this content to live from the user perspective; OR
- Do you think it makes sense for it to live as its own page? And if so, where in the IA do you think it makes sense?

Thank you so much for your help, as always.

**Comment by acrollet** [comment]
Hi @vbellissimo ,

I think I would probably expect to see this info on the [authentication page](https://depo-platform-documentation.scrollhelp.site/developer-docs/authentication). 

Side note: the "Overview of User Authentication and Authorization for the VA.gov API" link on that page is broken, I think the current location is: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/login/reference-documents/auth/authentication-and-authorization-simplified.md

**Comment by taylojill** [comment]
Hi @acrollet Where should the session timeout info live on the page? Should it go in an existing section or under a separate heading? Also, I'll fix the broken link. Thank you!

**Comment by acrollet** [comment]
> Hi @acrollet Where should the session timeout info live on the page? Should it go in an existing section or under a separate heading? Also, I'll fix the broken link. Thank you!

personally I would put it under its own H2 heading. thanks!

**Comment by taylojill** [comment]
Hi @acrollet I added the content under a new Session timeout (h2) heading (below the Overriding Authentication heading). I also corrected hyperlink. No launch-blocking issues, ready for deployment.
