### ISSUE TITLE
Adding Godwin Effiong to DSVA Slack

### ISSUE THREAD

**Issue by vievemarg** [department-of-veterans-affairs/va.gov-team#62037]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

Please add Godwin Effiong as a full member. Godwin is a Data Engineer for the VES Portfolio Research program. His email is godwin.effiong@adhocteam.us.

**Comment by vievemarg** [comment]
Checking in on this request - thanks!

**Comment by KevinMHoffmanUSDS** [comment]
This person is already a member. 
<img width="1780" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/50150810/70434915-21a4-4c95-bf2e-e17954894861">
