### ISSUE TITLE
(Samara) Finish and submit Team of Teams slide

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#62046]
## Tasks

- [ ] Add Jill's Thursday's deployed pages to the Google slide.
- **NOTE**: Do not add the "Currently Disallowed Cypress Test Specs on VA.gov" page or the 100+ Product Directory pages.
- [Link to slide here](https://docs.google.com/presentation/d/1EJB3QujBeJ9xlVfYbeZoxKg8HTY63hBB/edit?usp=sharing&ouid=104362113771391164792&rtpof=true&sd=true).
- [ ] Download the Google slide to Microsoft PowerPoint.
- [ ] On Friday 7/21:
- Submit the slide to [#team-of-teams-slide-collection](https://dsva.slack.com/archives/C031S5G29LP) Slack channel as an attachment.
- Your message can say "Platform Content Team's slide for 7/25" and CC Nate Peterson
- [Here's an example of how I shared last week's](https://dsva.slack.com/archives/C031S5G29LP/p1689598815953949) of last week's submission.

**Comment by SSimmorins** [comment]
ToT slide has been updated and sent to the channel cc'ing Nathan Peterson.
