### ISSUE TITLE
SOCKS access for Michael Delli-Gatti

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#62058]
### Your Name

Michael Delli-Gatti

### Your Email

delli-gatti_michael@bah.com

### Your Role and Team

QA Engineer on Memorials Self Service

### Product Manager (PM) name and email

Catherine Hughes hughes_catherine@bah.com

### Product Owner (PO) name and email

Matt Self matthew.self2@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDsD520R/0IL2SKi0o+eU6OwqlNUvtdZ/m62aRR9xgsU6M8XXuCrr6iJ59cmB8is97uuuXj8sylj9YIWscD6CTjes+H3sJQMazXPjmC6CsGLFPdAQXyZDu9MzeehMm/1rcjYxk9CZWrYw23UQgRfyhgHyFTv2K+wlfYuA3v4W7HQMyMCEw5JDh3iksBeBaIMT+IaxN0aJaywlMe2SrZjDU+Me3tFzh8HGECkWRsJVh6swlDsBBPYLA8DnWdR4yDNhMwQ49jypd/XQC0vKGOLYIRHxvgswx4/cLfqtFHBMXRsr4DE2rJSS6DSwKYHmMq5MjzGctSq3tuVXm1S2WoC4YKCwocVMkI8kQy8uRlh6oqbD6anhYufSvCPpeTTy8sImdCiEGDyq18HwxbgtEIVt45nq/gdShbS/z2N53QxR0lG0V0DwaygX//c9GjGbAuFOcjs6ExJSMH8kWMGN9J5QGs2VU2tiGCOkzi65OhhaIGk/npErGDdPSCwUE7XobMQOs= michaeldelligatti@V973W2KFVW

### E-QIP Transmittal Confirmation

<img width="1072" alt="Screenshot 2023-07-17 at 10 07 37 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/45575003/d8b71e32-0ac4-4ddd-8aba-ee6e279689b9">

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by rmtolmach** [comment]
@delli-gatti-michael access has been granted. See https://depo-platform-documentation.scrollhelp.site/getting-started/accessing-internal-tools-via-socks-proxy for next steps and reach out in #vfs-platform-support with any questions.
