### ISSUE TITLE
pull email list for Organic/Reactivation Test 

### ISSUE THREAD

**Issue by djmunoz1** [department-of-veterans-affairs/va.gov-team#62057]
As an email admin I want an email list so that I can run a test of messaging for the Organic Campaign as well as a simultaneous test of the Reactivation campaign for veterans with DSL+ID.me credentials.

ACCEPTANCE:

List 1
Test Name: Organic Test A
segment: veterans who do not have a login.gov or id.me account
volume: 75,000 emails; random

List 2
Test Name: Reactivation Test D
segment: veterans with DSL + ID.me credentials
volume: 50,000 emails; random

DEF OF DONE:
- both email lists shared with Product lead (Dawn) as csv files
- both email lists clearly titled as organic and including pull date; centrally stored along with the email lists from Reactivation Tests

**Comment by sdickson-gt** [comment]
@jrjamespdx For the Reactivation Test D email list, can you share the emails already used for prior tests and/or how they were selected from the speadsheet of eligible users for reactivation - so they can be filtered out.

**Comment by jrjamespdx** [comment]
@sdickson-gt I've dropped the two VEO send files for Reactivation Emails A and C into our VA Teams private channel/message.  The file for email A has 2,500 emails and the email C file has 71,327 emails.

**Comment by sdickson-gt** [comment]
@djmunoz1 I sent you the CSV files via VA teams message.  (don't want to send emails/PII outside of VA).  The CSV files are stored at \\vacohsm01.dva.va.gov\VACO_Workgroups\Information & Technology\OCTO Digital Experience\Logingov Adoption\email campaigns.  I'm looking into how to modify Windows ACLs to allow access to you and other newer teammembers...Elizabeth had added Melissa but it's not apparent to me just how she did it yet.  Worst case, we submit a ticket to VA support.

**Comment by sdickson-gt** [comment]
lists have been pulled and provided
