### ISSUE TITLE
correlate ICNs and login activity with Reactivation Test B

### ISSUE THREAD

**Issue by djmunoz1** [department-of-veterans-affairs/va.gov-team#62055]
As an email admin I want to check the login activity of veterans who received a Reactivation email Test B so that I can understand their post-email login behavior.

Extra Information:
- We can query the `CredentialAdoptionEmailRecords` table in the `vets-api` database to get information on which ICN's were sent the email.
  - query options include:
    - `icn`
    - `email_address`
    - `email_template_id`
    - `email_triggered_at`
- Check with @sdickson-gt on how to obtain login information for the list of ICNs

ACCEPTANCE:

get recipient list for Reactivation Test B (this had a 5% rate limiter, which veterans received the message?)
get ICNs for each email recipient
check login activity for ICNs on the Reactivation Test B recipient list between 7.20 and 7.25

DEF OF DONE:

data sheet listing login activity by credential for each ICN

NOTE:
This ticket is blocked by time. We want to allow 5 days after the Reactivation Test B send date (July 20) before pulling this information.

**Comment by jrjamespdx** [comment]
@djmunoz1 I had a question after looking over this ticket:

- This ticket's title and description only mention doing the ICN/email address correlation and login activity results from the soon-to-be-live VA Notify-sent Reactivation Test B, but later the ticket references the VEO-sent Reactivation Test A and waiting 14 days after it was sent before pulling this information.

**Comment by djmunoz1** [comment]
test b did was unsuccessful due to use of wrong api key
