### ISSUE TITLE
Plan for Longitudinal Study Pilot

### ISSUE THREAD

**Issue by djmunoz1** [department-of-veterans-affairs/va.gov-team#62062]
As a veteran I want a coherent agenda for the first veteran study session I'm participating in so that I can understand goals and initial needs.

ACCEPTANCE:

- [x]  agenda includes goal, plans for anticipated meetings in the near future, first feedback request
- [x]  share agenda with Robyn Singleton
- [x]  incorporate feedback

DEF OF DONE:

- [x] completed agenda is stored in central location and linked in this ticket

**Comment by skirkman16** [comment]
[Perigean project memo](https://docs.google.com/document/d/1jfAe32xcogIJ_0VcPYiXsCEy3zG4VAbotzL3l9sJXlM/edit) will inform our research plan

**Comment by skirkman16** [comment]
Plan for pilot is coming together on [this mural](https://app.mural.co/t/innovationboards1199/m/innovationboards1199/1690218514507/04f28aeaf2f17dba77d6549ab6c05a4eaac1bf48?sender=u99cd1ac4f5c240d8dffd4204). Yesterday we had a brainstorming session and between this afternoon and friday we will refine the activities into more concrete sessions. We will share out with the team before we share to Robyn for approval.

**Comment by skirkman16** [comment]
We outlined the first session of our pilot and completed our research plan and accompanying conversation guide. Both can be found in our github repo [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/login.gov-adoption/research/longitudinal%20study)

**Comment by skirkman16** [comment]
Next steps is to outline the next two sessions of the pilot and draft conversation guides for each
