### ISSUE TITLE
Adding Rockwell Rice to DSVA Slack

### ISSUE THREAD

**Issue by emilygoodrich5623** [department-of-veterans-affairs/va.gov-team#62068]
- Please addRockwell Rice as a single-channel guest to #vsp-identity.

**Comment by LEHigley** [comment]
need an email address

**Comment by emilygoodrich5623** [comment]
***@***.***@va.govOn Jul 31, 2023, at 11:58 AM, Lacey Higley ***@***.***> wrote:﻿
need an email address

**Comment by LEHigley** [comment]
@emilygoodrich5623 i need an email address here

**Comment by emilygoodrich5623** [comment]
***@***.******@***.*** Aug 9, 2023, at 7:42 AM, Lacey Higley ***@***.***> wrote:﻿
@emilygoodrich5623 i need an email address here

**Comment by emilygoodrich5623** [comment]
I keep replying to the email but it apparently doesn't make it to you UGH, but here is rocky's email for oddball (contracting company) and VA 

[Rockwell.rice@oddball.io](mailto:Rockwell.rice@oddball.io) 

[Rockwell.rice@va.gov](mailto:Rockwell.rice@va.gov)
