### ISSUE TITLE
SOCKS access for [individual]

### ISSUE THREAD

**Issue by fred-khoury-oddball** [department-of-veterans-affairs/va.gov-team#62067]
### Your Name

Fredrick Khoury

### Your Email

fred.khoury@oddball.io

### Your Role and Team

Full Stack Engineer on Benefits and Claims

### Product Manager (PM) name and email

Laura Steele laura.steele@coforma.io

### Product Owner (PO) name and email

Matt Self Matthew.Self2@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDJh9OU1Jwk2/o4sq9nFz+AtV/giDteKFaGAbXEjNRTrShgSogllFhMse9jNVGWT225ET27bPMbf/xrUmxAxCwPKYTQO2mqnbFXI7HH3yZmDbY+6ivh+BWSLBXoHsnVq9STCB4j8d/YVX4LFrJFKLmrwYz7YCRXT3YodAZIt0dF3SJZMvht//J3uAHbIdanbhrjwIzSHI2wrbLYetCSkq3lqFsRVlKWkzfqa27osM6xpoj5RTe9qfKvtzWMpBhOpEuFr4OVea9CdEE0TfiDmiP3PhWTHj/+ocF1iYnUP8diXt3HTioMkJwoBmjRAgpnhbXhfzImi8edlgXFeTYKaBMfpitJ4Lgcjd4txViGRMLkD5JtDLY2g4j9aWhVWkbp7wefxQ2LRlzwKXox8pgkHw1mxS6MJeGaxVurd4UyQU0SHaPdTIA0/VK36FJBOvUhO2hTm9BotSeL3VahGt8NglRp4fnr8kmAFOHmRTCfWwGsIXwmEo38uk18+YrsnBfDfJE= fk@fks-MacBook-Pro.local

### E-QIP Transmittal Confirmation

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/135056639/828ef235-8354-49c6-a8d6-94b2f9aa688f)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by rmtolmach** [comment]
@fred-khoury-oddball access has been granted. See https://depo-platform-documentation.scrollhelp.site/getting-started/accessing-internal-tools-via-socks-proxy for next steps and reach out in #vfs-platform-support with any questions.
