### ISSUE TITLE
FE | Profile | Notification Settings | Consume Default Send - Incorporate any missing midpoint review feedback

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#62077]
## Background

Continuing our work from #61013 we need to pull in the remainder of the feedback we've received from our midpoint review for default send/email as a channel. 

## Documentation 

#60818
- "We don't have your contact information" alerts have been updated for [mobile](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/r9rvgAa) and [desktop](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/9P49mAx)

#60766 
- Ensure the active link has a weight of 700

## Acceptance Criteria
- [x] Confirm all of the Midpoint Review Feedback has been incorporated 
- [x] add in test coverage around the review points
- [ ] Alert the team so they can test 
- [ ] Ready for staging review

**Comment by adamwhitlock1** [comment]
I fixed the bug where you could remove just one number / character and hit cancel and not be prompted with the modal.

This should be able to be validated now @mtcA6.

**Comment by mtcA6** [comment]
i think things look good

**Comment by mtcA6** [comment]
does this mean we're ready for QA?

**Comment by adamwhitlock1** [comment]
There is one other issue to work through next sprint #63333, and then I think we would do a staging review before QA correct?

**Comment by mtcA6** [comment]
@adamwhitlock1 QA feeds into staging review actually :/ so we have to present our QA artifacts on the staging review ticket section

**Comment by adamwhitlock1** [comment]
Okay, well then I suppose we close this out, and start QA once the last ticket is complete.
