### ISSUE TITLE
Access for Sarah Szekeresh

### ISSUE THREAD

**Issue by SarahJaine** [department-of-veterans-affairs/va.gov-team#6210]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O’Toole
- Please provide your name.
   > Sarah Szekeresh
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VSA/Benefits and Memorial Services 1 (disability compensation claims) - Ad Hoc
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Internal%20Tools.md#create-ssh-public-key) for instructions. (Example below)
I already opened [a PR](https://github.com/department-of-veterans-affairs/devops/pull/6402) for this.

- [Grant AWS Console access?]
  > YES 
  >  As a backend dev I will need access to CloudWatch logs and other AWS products.

And here is [my second PR](https://github.com/department-of-veterans-affairs/devops/pull/6847) for AWS access.

**Comment by SarahJaine** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by ricetj** [comment]
Hello @SarahJaine we can grant SOCKS, but you will need to submit your eQIP or have your paperwork transferred before granting AWS.

**Comment by ricetj** [comment]
@Jeff-Hayter 
User: Sarah Szekeresh
COR: Mary O’Toole

**Comment by SarahJaine** [comment]
> Hello @SarahJaine we can grant SOCKS, but you will need to submit your eQIP or have your paperwork transferred before granting AWS.

Let's do this in two PRs then. I removed AWS access from the PR I already have open, so it'll just grant SOCKS access.

**Comment by benniemosher** [comment]
SOCKS PR merged.

**Comment by SarahJaine** [comment]
Part 2, getting aws access, is blocked until I receive and complete EQIP paperwork.

**Comment by SarahJaine** [comment]
@ricetj Hi TJ, It appears that the VA noticed that I had a previous investigation so the eQIP was not necessary. I have been submitted for a PIV card. I now have CAG access and a VA email as well.  Does this mean I'm far enough along in the process for you all to give me AWS access?  It would really be helpful for debugging purposes.  I opened a new PR to make my request clear for the team. https://github.com/department-of-veterans-affairs/devops/pull/6847

**Comment by Jeff-Hayter** [comment]
@ricetj Confirmed and approved for AWS.

**Comment by jbritt1** [comment]
Sarah-Jaine had already made her own PR as she is aware of our setup and the perms necessary for her workflow. PR was approved, applied, and merged granting her a user account. First time login credentials provided via Slack DM. Closing.
