### ISSUE TITLE
Remove old "Missing ID" messages Infrastructure

### ISSUE THREAD

**Issue by NB28VT** [department-of-veterans-affairs/va.gov-team#62131]
**TBD what we plan to remove here. These are likely isolated enough we can just delete these files and all references**

**Comment by NB28VT** [comment]
@austinjprice FYI I actually think we should keep this one open, not sure what the rollout looks like for these small fixes but at some point I will need to remove the flipper to enable the new messages for everybody and then delete all of the old code that's not used anymore.

**Comment by tblackwe** [comment]
@NB28VT do we still need this?

**Comment by sortizsh** [comment]
Sarah will talk to Kimbereley about finding another Veteran to test with.

**Comment by tblackwe** [comment]
Closing this ticket as the work is represented in another ticket, and it is linked to this
