### ISSUE TITLE
[FE] Address Validation Analytics - Front End Implementation 

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#6213]
# Background
We will need to implement frontend tracking to gain insight into the success of the address validation feature.

# Tasks
- [ ] Implement the dataLayer requirements outlined below for address validation performance tracking

https://github.com/department-of-veterans-affairs/va.gov-team/issues/5895#issuecomment-591103075

**Comment by bradl3yC** [comment]
@nedierecel and @jonwehausen this should be in staging after the next deployment for validation

**Comment by bradl3yC** [comment]
@nedierecel and @jonwehausen this is ready for re-review.  It should be available in staging in the next 20-30 minutes.

**Comment by nedierecel** [comment]
@mshea0606 @jonwehausen I'm beginning my review this morning of the Address Validation. Thanks!
