### ISSUE TITLE
VA.gov Edit request - Home Loans

### ISSUE THREAD

**Issue by AkucherGCIO** [department-of-veterans-affairs/va.gov-team#6214]
What is the process to request changes to the VA.gov website?

 

Our Cleveland Regional Loan Center staff noticed that the VA.gov site for home loan funding fees is out of date.  (https://www.va.gov/housing-assistance/home-loans/funding-fee-and-closing-costs/) As of January 1, 2020, the funding fees for home loans changed (per P.L. 116-23).

 

LGY updated our own website with this information (and embedded Table), but we goofed by not informing you VA.gov folks as to the changes.  The changes to your site should include:

 

You won’t have to pay a VA funding fee if any of the below descriptions is true for you. You’re:

Receiving VA compensation for a service-connected disability, or
Eligible to receive VA compensation for a service-connected disability, but you’re receiving retirement or active-duty pay instead, or
A surviving spouse of one who died in service, from a service-connected cause, or totally disabled; and receiving Dependency and Indemnity Compensation (DIC), or
A Servicemember with a proposed or memorandum rating from VA, prior to loan closing, as eligible to receive compensation as a result of a pre-discharge claim, or
A Servicemember on active duty who provides, on or before the date of loan closing, evidence of having been awarded the Purple Heart
VA funding fee rate charts

Effective January 1, 2020, based on Public Law 116-23

Review the VA funding fee rate charts below to determine the amount you’ll have to pay. Down payment and VA funding fee amounts are expressed as a percentage of total loan amount.

For example: If you’re using a VA-backed loan for the first time and you’re taking out a loan of $200,000 and paying a down payment of $10,000 (5% of the $200,000 loan), you’ll pay a VA funding fee of $3,135 (1.65% of the $190,000 loan amount).

(* for clarification the funding fee is on the loan amount, not the purchase prices. And note, even I ask for confirmation, since it’s not intuitive - RC)

 

* Rates for Veterans and service members with active duty, National Guard, and Reserve service

 

*VA-backed cash-out refinancing loans

 

(* see attached for the new rates.  Note AD, NG, and Reservists all pay the same rate now for 1) Purchase and 2) Cash-outs)

 

Other VA home loan types

(* see attached and please add Vendee loan rate of 2.25%)

 FYI that the VA website appears to be displaying incorrect information regarding funding fee tables.![image001.png](https://images.zenhubusercontent.com/5e4d73c84ff78270a88d2ae8/6b7c6346-9e77-4ce7-83da-ce7211dfdf10)

![image003.png](https://images.zenhubusercontent.com/5e4d73c84ff78270a88d2ae8/dafd280c-183b-4d0f-982f-e45dbf31d7ae)

[https://app.zenhub.com/files/133843125/1832f95a-0bb7-4eb6-b960-92db2c91a2b8/download]

**Comment by AkucherGCIO** [comment]
@AnneHurley - i've changed to Public websites Sprint 16.

**Comment by AnneHurley** [comment]
Uploading the new rates doc stakeholders sent for records
[Home Loan Funding Fee Tables FINAL.docx]
(https://github.com/department-of-veterans-affairs/va.gov-team/files/4263997/Home.Loan.Funding.Fee.Tables.FINAL.docx)

**Comment by AkucherGCIO** [comment]
2020-28-02 Standup
@AkucherGCIO Move to In-Progress.

**Comment by AnneHurley** [comment]
@jenniferlee-dsva  @AkucherGCIO  - FYI we are temporarily blocked by a bug in Drupal that takes edited tables and adds extra, empty columns. Kevin Walsh and Howie are working on it.

**Comment by AkucherGCIO** [comment]
03/04/20 PW Standup
@AnneHurley - will be emailing the VA Stakeholder related to the technical issue and once it's fixed, the rates will be updated. @kevwalsh - Waiting for the issue to be resolved by your team.

**Comment by AkucherGCIO** [comment]
03/05/20 PW Standup
@annehurley - will be working on fixing how the table is rendered.

**Comment by AnneHurley** [comment]
Page and tables are updated here: http://preview-prod.vfs.va.gov/preview?nodeId=748

I've sent the link to Raleigh and the other stakeholders for their approval. 
@AkucherGCIO  and @jenniferlee-dsva  FYSA

**Comment by AkucherGCIO** [comment]
03/06/20 PW standup
@annehurley - This work should be wrapped up today.  The CMS team helped troubleshoot issues with this page and so it was blocked for a couple of days.

**Comment by AnneHurley** [comment]
@RLHecht  This page now has all of Raleigh's last edits incorporated. However, we are using this wording for all the types of service/Veterans who're eligible:

"...Veterans, active-duty service members, and National Guard and Reserve members" 

When the page is live I'll send Raleigh a note with the link and an explanation of our style, how "service member" is its own indivisible unit, and not like the "members" of the National Guard or Reserves. 

Once you've reviewed, this can be pushed live.

@AkucherGCIO  and @jenniferlee-dsva  FYSA.

**Comment by RLHecht** [comment]
@AnneHurley This page has been published. I fixed the wording to match what you have in the comment above for the text above the second table. I'll move this to validate and we can close it later this afternoon.

**Comment by RLHecht** [comment]
Validated this page is live. Closing ticket. @AnneHurley @AkucherGCIO
