### ISSUE TITLE
[Terraform] Create Route53 Private Hosted Zone

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#62143]
## Acceptance Criteria 
- Each Platform Cluster should have it's own private hosted zone in Route53
- Should be in the format of `{tier}-{eid}.vfs.va.gov`

## Tasks
- [ ] Update route53 module to use expected format
- [ ] Update platform-distro with new module

**Comment by npeterson54** [comment]
any problems that come from it should make new stories or readjust points
