### ISSUE TITLE
[BE] Discovery: Figure out how ES handles Previous Year financial info

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#62148]
As a Veteran, I would like to be able to update my financial information any time of year so that I'm not updating for the wrong "Previous Year."

- [x] Figure out how ES handles "Previous year," is it a field that says previous year, or is it the year itself
- [ ] Come up with solution for making sure Financial Disclosure information in the profile is always available and displayed as the "Previous Year" without us having to make manual changes on 1/1/xxxx
- [x] Figure out if previous years prior to previous year is used for anything
- [x] Report back to team
- [x] **Success: We quell Samara's fear that we will need to update this every year on New Year's Day**

**Comment by lihanli** [comment]
ES displays the year itself when looking up a user's financial information
