### ISSUE TITLE
[Research] Make updates to Research Plan/Convo Guide based on AE/KM feedback

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#62150]
As a Veteran, I would like to be able to update my financial disclosure information online so that I ensure I do not have to pay copays I am not required to pay. 

- [x] Share Research Plan and Convo Guide with AE Team and Kristen
- [x] Review AE team feedback
- [x] Integrate relevant AE team feedback
- [x] Respond to any other AE team feedback
- [x] Share RP/CG with Kristen
- [x] Review her feedback and integrate any feedback
- [ ] Submit for scheduling 
- [ ] **Success: Relevant stakeholders have had their say on the research plan and it is submitted for research review and scheduling** 

----------------------------------------------------

Liz Lantz's feedback: 
**[Research plan](https://dsva.slack.com/archives/C909ZG2BB/p1689618975630719?thread_ts=1689295431.992559&cid=C909ZG2BB)**
Check assumptions and terminology used to remain Veteran-centric
:point_up: I love this outcome :heart_eyes:
Currently, do Veterans prefer to provide updated information in person at appointments or over the phone?
I assume these are the only two ways a veteran can currently provide this info - so you’re wondering of the two options, which do they prefer? Or could “online” be a valid preference in response to this research question?
Do dependent updates cross benefits in the Veteran’s POV or do they associate them only with their health care benefits?
I think to truly answer this question, you should consider adding Veterans who have disability benefits and dependents to your recruitment criteria.  If a person only has health care, or disability and no dependents, they may not have any idea that dependents mean different things in the VA ecosystem, depending on the benefits they are associated with.  Other combinations might work but I’m not familiar w/ dependents outside of disability
Recruitment criteria
You might want to specify VA health care in your screener question, just to be extra sure you don’t get someone who has applied for health care elsewhere.
You may want to consider requesting a mix of ages, since you’re interested in learning more about how well people understand priority groups and how that fits into their health care. People who have had VA health care for a long time may have developed a strong understanding out of necessity over time whereas people who are new to it might not get it yet.
In the spirit of equity and inclusion, I would love to see you add more underrepresented groups in your primary criteria: people who identify as other than white, women, people with cognitive considerations (diagnosed or otherwise).
Team Roles
I love how you guys are approaching this as a team and taking turns moderating and with the pilot. Is the purpose of 3 pilots so everyone gets a chance to practice, or do you anticipate more changes between each one

[Conversation guide
](https://dsva.slack.com/archives/C909ZG2BB/p1689623335182849?thread_ts=1689295431.992559&cid=C909ZG2BB)Overall comments
I don’t have experience participating in a study where there is a rotation of moderators, but overall, I wonder if there should be more guidance throughout the guide about follow-up questions, optional probes, etc. Just to minimize variety across sessions and attempt to get the most consistent data possible over the course of the study.  I noticed the health wayfinding study that is currently under way has “Optional probes - very flexible, adapt as appropriate depending on participant behavior” throughout their conversation guide which I really liked and plan to use in future guides that I write.
This is totally just me, but you may want to rephrase questions that could be answered as a yes or no. I’m not sure if everyone on the team has the same level of facilitation experience, but in the spirit of minimizing variation I think this could help. I’m making some assumptions on what you are really going for here, but one example is the “Do you know what priority group you’re in…” question. Assuming you’d follow up with “what does that mean” or other questions to get them to elaborate on a “yes or no”, you could start with “Tell me about the priority group you are in…” which starts the whole section of on a more conversational, open note.
Similar feedback for “Can you tell me where you would like to be able to access your Priority Group number? Why do you list [this] place?” Instead you could say “What are some places it would be helpful to be able to access your PG number? Why?”
Warm up
What is the goal of the warm-up question, “And do you sign in every time or how often do you sign in?”
dependents section
I wonder if these prompts will adequately support your research question “Do dependent updates cross benefits in the Veteran’s POV or do they associate them only with their health care benefits?”  It feels to me like the questions won’t really get to insights about the POV with crossing benefits, but it could totally be that I don’t fully understand what you’re going for or the follow-up questions that’ll be asked.
EZR Tasks
In this task, you ask how a person would like to receive a communication. Earlier in the session, they answered a question “Have you been notified that since you enrolled that you had to provide new information or updates?” - you might get a more objective response from the participant if you use whatever information they shared about notifications they received earlier in the session vs asking them to predict their preference.  Or maybe you could use what they said to tee up the scenario to begin with.
In the [Global questions] section, bullets 2, 3 and 4 feel duplicative of the bullets under [Where to find]. I wonder if the bullets under [global questions] would be better as follow-ups to the [where to find]? I think participants would touch on all of those things as they walk you through, though I’m not sure if “annual income” is different from “financial information”, so I could be misunderstanding.
If you leave those bullets under [Global questions]: “What would you be looking for when you first login to update this information? Something in the sidebar or a notification?” I would recommend adding a note for moderators here to say this only if a person mentions they’d login. I assume every participant will, but you know what they say about assumptions :wink:
I’m sure you’ll get at this but if they do validate the profile hypothesis, it’ll be super helpful to learn where exactly within the profile they’d expect to do it. if it’s a new section, we’d love to hear what they would call that section, and what else they might expect to find within it. Could you add those as follow-up questions please?

**Comment by jessicastump** [comment]
Ticket tasks and points moved to ticket: [Research] Prepare for Financial Disclosure/Priority Group Research #60690. This can be closed.
