### ISSUE TITLE
[EPIC] Next of Kin/Emergency Contact (read-only)

### ISSUE THREAD

**Issue by carafrissell1** [department-of-veterans-affairs/va.gov-team#62159]
Below is an outline of an idea of how the workflow around Next of Kin/Contact could go.  

Tentative, in progress and SEEKING FEEDBACK:

Phases:

1. **Discovery on current practices**
    1. Validate that this information is collected — it’s not all clearly collected in one digital place (ticket # documents some of this but are there are probably more places for 
    2. Technical discovery — where and how is this information currently stored? How is it accessed? —- Note: after this, 
    Regroup after technical discover in Slack:  #accountexp-authexp 

**Note: Based on findings/decisions from Phase 1, move forward with, adapt or cancel following phases**

2. **User needs and use cases** (What problem is this information solving and how?)
    1. Review past research and known parts of the veteran journey to see if this information would be useful, in particular:
        a. Who would find this useful? What different user groups?
        b. When would this be useful?  When would a user interact with this?
        c. How would this user use/interact with this information?
            1. What does the user need to know/see/be able to do in order to make this useful?
        Note: Extant research may not be able to answer all these questions, in which case we will explore our options 

3. **Solutioning** 
 User - facing:
 Based on Phase 1+2 findings, ideate:
         1. Where should this go in the current IA? (as of 7/18 leaning toward somewhere in Profile, but where? What language 
           should we use?) 
         2. Note: this would probably also benefit from evaluation at the content level before moving into design 
         3. What could interacting with this information look and feel like for the user? (Enter, edit, view, etc.)

Engineering solutioning 
      1. What storage considerations are there for the different ways this information needs to be used?
           a. Note: CF not sure where this effort fits best at the moment 

**4. Evaluation and iteration (User-facing)**
-  Evaluate different solutions against the different use cases and user needs identified most likely via some kind of  usability test or cognitive walkthrough
-  Iterate based on research findings 

 **5.  Implementation**

**Comment by andaleliz** [comment]
Danielle connected me with Greg Hughes (Division Director, National Care Coordination, Veterans and Military Crisis Line) to get answers to some questions - dropping what I learned here until we get some docs spun up to capture these kinds of things:

When a Veteran calls VCL, do the representatives have access to any of their information? 
> Yes, but only if the Veteran grants them access to their medical record, otherwise they only have access to prior call history. 


If so, what information do they have access to? How might they use it? 
> They have access to the full medical record as well as a dashboard known as CRISTAL, which presents specific risk factor for suicide information to the responder. They can also access JLV for any DOD info available. The VCL call history is in our own database, known as Medora, which will have prior call history, including risk assessments and dispositions.

Which interface are the responders using to access the medical record? We’d like to be able to confirm they’d be able to access the emergency contact info.
> They have read-only access to CPRS/VISTA and JLV.

Are there any kinds of other VA records accessed or available to the responder? I’m wondering about Veterans who don’t have a medical record, which I believe could be possible if they’ve never used a VAMC or applied for a disability rating. 
> We typically only access CPRS/VISTA – we do talk to many Veterans who have never used VHA (or VA at all) as well as family, friends, professionals regarding Veterans they are associated with.

In your opinion, is what I described (responder accessing emergency contact information during a VCL call) a viable use case? 
> I think it would be helpful to us as we may have difficulty locating a Veteran who has called in crisis and may (in extreme cases) use emergency contacts for assistance.

**Comment by carafrissell1** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/tree/59d59574d8ba034f147e89d2537a7b71e80ee461/products/health-care/digital-health-modernization/mhv-to-va.gov/Next%20of%20Kin-Emergency-Contact

**Comment by wesrowe** [comment]
Veterans have expressed their desire to edit contacts online as a result of frustration with getting it done through VA staff. Relevant teams are actively discussing how to meet this need.

**Comment by wesrowe** [comment]
Done! moving on to edit functionality in new epic.
