### ISSUE TITLE
Technical Discovery - Next of Kin/Emergency Contact

### ISSUE THREAD

**Issue by A6-toma** [department-of-veterans-affairs/va.gov-team#62154]
### Issue Description
We have been tasked with surfacing Next of Kin (NOK) and Emergency Contact (EC) VA Profile data to use in MHV. This ticket is to perform technical discovery as a foundation to doing that work.

### Questions to answer:
- Where and how is this information currently stored? 
- How is it accessed?
- What are other places we ask for this information, and how do we do it in those places? 
- What are other places that we display this information, and how do we do it those places? It’s definitely on va.gov via the check-in app. And of course there is what’s on MHV national portal already. There might be other places too.

### Background Information
Currently, the data is collected using1010 EZR.

POCs on the Profile and Authenticate Experience teams include Alex Seelig, Liz Lantz, Emily Brown, and Samara Strauss.

Relevant [Slack thread](https://dsva.slack.com/archives/C7TE0PFTL/p1685977200921009)

[Research results](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Research/2022-05-MHV-profile-research/recommendations.md#we-should-collaborate-with-the-health-apartment-team-to-determine-where-it-makes-the-most-sense-to-put-health-related-profile-items) that include NOK and EC

Communication with other teams should be done in the **#accountexp-authexp** Slack channel.

### Acceptance Criteria
The above questions (and others that arise during discovery itself) have been answered, documented, and shared with the Profile, Authenticated Experience, and Cartographers teams.

**Comment by radavis** [comment]
Notes, here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/engineering/ice-nok-technical-discovery.md
