### ISSUE TITLE
write content for Organic Test A

### ISSUE THREAD

**Issue by djmunoz1** [department-of-veterans-affairs/va.gov-team#62164]
As a veteran who does not have a login.gov or ID.me account I want an informative email about login.gov and ID.me login options so that I might try setting up a new account.

ACCEPTANCE:
- language informs veteran that login.gov and ID.me meet stronger security standards 
- there is no mention of DSL or MHV eventual sunset

DEF OF DONE:
- Draft content stored in Content folder and shared with Sitewide for input

**Comment by CarlDickerson** [comment]
Final content with revisions suggested by Sitewide:https://docs.google.com/document/d/1PXD3-AW095JJEv_EWHDGQOtWA7JcaoIeSmrNNjnGL80/edit?usp=sharing
