### ISSUE TITLE
finalize Reactivation segment content - Inform; Aug

### ISSUE THREAD

**Issue by djmunoz1** [department-of-veterans-affairs/va.gov-team#62166]
As an email admin I need to communicate plans for upcoming campaigns so that surrounding VA offices are able to prepare for veteran feedback.

ACCEPTANCE:
- pulls from existing language already reviewed by the content team
- login.gov only OR login.gov and ID.me --> push to login.gov
- ID.me --> push to ID.me
- content drafts exist on a single file stored in appropriate content folder
- content intake request completed to request review on the document
- incorporate Sitewide content edits and add final content to appropriate content folder

Resources: Segments Tab ('LGA Priorities')[https://docs.google.com/spreadsheets/d/1Q2W_2PKVwCKaMNEG-RsThlb7nUErJ18rIXg1Mr1W0ZU/edit#gid=643610543]

**Comment by djmunoz1** [comment]
@CarlDickerson if you can think of a way to consolidate the messaging for the Reactivation Campaign such that we can send a single email to the entire cohort, i'm interested. It may be wise to reduce risk since we're not handling the sending of the comms ourselves.

**Comment by djmunoz1** [comment]
Hi @CarlDickerson to simplify this we're going to collapse the segments into a single one and try to slightly modify content to account for ID.me users.

**Comment by CarlDickerson** [comment]
Content with combined language around Login.gov & Id.me:https://docs.google.com/document/d/1vnNlYXU023ANsKdzjkSR0usVnDsuZhPF/edit?usp=sharing&ouid=100160945628119230222&rtpof=true&sd=true
