### ISSUE TITLE
mock content for updated Sign In Page

### ISSUE THREAD

**Issue by djmunoz1** [department-of-veterans-affairs/va.gov-team#62167]
As a veteran I need to see updated content on the VA.gov Sign In page so that I can be informed about anticipated changes to login options and encouraged to try the modern credentials.

ACCEPTANCE:
- updated sign in page informs visitor that login.gov and ID.me meet stronger security requirements and tells veterans to try setting up an account.
- Audience: veterans who do not have a modern account: DSL only, MHV only, or DSL and MHV only

Resources:
- sign in page url: https://www.va.gov/?next=loginModal

**Comment by djmunoz1** [comment]
@MOStudioCarolyn can we try transforming the DSL and MHV buttons into links?

**Comment by CarlDickerson** [comment]
Mock content in figma: https://www.figma.com/file/8vobVoSl1UqLnXsni3rcvO/Login.gov-Adoption%3A-Design-Flows?type=design&node-id=2601-33&mode=design&t=gOTR3WqXJfs1GJ0R-0
