### ISSUE TITLE
Design Intent - Design Feedback - Sitewide Facilities, Facility Locator, Improve Search, Add Filters

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#62175]
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- Think about what happens if they can't find what they are looking for.
- Matt Dingee: The "search by state" in the footer feels like it is just another way to search. 

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- **Consider:** We are trying to align icons across VA. Before you create a new icon for provider core training complete, look at our [icons library](https://design.va.gov/foundation/icons) and see if one fits your need.
- **Consider:** Matt Dingee: We don’t love these tabs and have been trying to get rid of them. I think at some point you could replace that with the [US system segmented button group](https://designsystem.digital.gov/components/button-group/).
- **Consider:** Matt Dingee: I don’t love the filters in the modal. Consider using the draw. [GI Bill](https://app.zenhub.com/workspaces/collaboration-cycle-reviews-61d89e9e5f4c120011a0ad37/issues/gh/department-of-veterans-affairs/va.gov-team/44187) was working on a drawer option as well. Modals typically are there to stop an action.

**Comment by mmiddaugh** [comment]
@thejordanwood is this issue still needed or have we addressed all the feedback?

**Comment by thejordanwood** [comment]
@mmiddaugh This feedback has been addressed. I'll go ahead and close this.
