### ISSUE TITLE
IA support on CPAP supply reordering

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#62184]
Supply reordering team opened [an intake](https://app.zenhub.com/workspaces/sitewide-content-accessibility-and-ia-63a1d63232beba0011a7833f/issues/gh/department-of-veterans-affairs/va.gov-team/61624) to add CPAP supplies to the existing hearing aid batteries tool. 

We'll need to provide IA support for this work.

**Comment by kristinoletmuskat** [comment]
IA work in mural captured here: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1679086662310/cbe41468d45afc03206a3d0a7f6b979517c523d8?wid=0-1689953198747

Next step is to make an IA spec doc

**Comment by kristinoletmuskat** [comment]
And IA spec doc is done: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/order-cpap.md
