### ISSUE TITLE
Add Workflow to 686: "Add a Spouse" - Part 2

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#6219]
## Story
As a Veteran using the 686 in VA.gov, I want to be able to adjust my claim to account for a new spouse so that I can maintain an accurate representation of my status with the VA.

This ticket incorporates page 4 and 5 of the 686c workflow to add a spouse. 

## Goals
- Include the necessary schema workflows and submit PRs for them to be incorporated.  This will fully flesh out the rest of the workflows to coincide with what has already been put out.

## Considerations
- When these are done as multiples, there are merge conflicts that will need to be carefully addressed.
- [Mockup](https://xd.adobe.com/view/ffffe536-2ba5-47c6-4c4b-ac1679179973-89ce)
- This section (page 4 and 5) contains two separate arrays of information, one for a spouse's former spouse's name (SFSN), and then another for entering information pertinent to the spouse's former marriage to said person (Spouse's Former Marriage Information Section - SFMIS).
- The SFMIS section should be labeled with the names found in the SFSN array.

## Tasks
- [x] Add and/or remove the necessary schema at the workflow level and ensure there are no validation errors.

## Acceptance Criteria
- [x] A PR has been requested and completed for `vets-website`

**Comment by micahchiang** [comment]
PR here - https://github.com/department-of-veterans-affairs/vets-website/pull/11820

**Comment by micahchiang** [comment]
PR merged.
