### ISSUE TITLE
[SW] Observer Notes Documents

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#62207]
## Issue Description
Create documents for notetaking for SW research study.
---
## Tasks
- [x] _Create Mural_
- [x] _Create Google Spreadsheet_

## Acceptance Criteria
- [x] _Mural created_
- [x] _Spreadsheet created_

**Comment by josephrlee** [comment]
@mgleo @charlottecesana , moving this to the current sprint in-progress since y'all started this already.

**Comment by josephrlee** [comment]
Here's the spreadsheet: https://docs.google.com/spreadsheets/d/16CdqgwZ2rAVX5H3biqwwP8sxkAE6xPZT/edit#gid=1074480362

**Comment by charlottecesana** [comment]
Also complete! @Tom-Davis @HeatherRienks
