### ISSUE TITLE
[CSI] Implement CSI

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#62202]
## Description
Implement CSI 

## Resources 
- Artifacts - i.e., issues, documentation, code, etc. - that help explain what's needed to work on this issue

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this issue?_

## Refinement Guidance - Check the following before working on this issue: 
- [ ] _Team label assigned ("platform-tech-team-2")_
- [ ] _Epic assigned (if needed)_ 
- [ ] _Estimated (points assigned)_
- [ ] _Sprint assigned (once planned)_
- [ ] _Team member(s) assigned_

**Comment by ben-allen-oddball** [comment]
What CSI are we talking about other than EFS and EBS?

**Comment by ben-allen-oddball** [comment]
Also as our tiers are persistant...  How do we want to deal with the CSI for Dev, Staging, Sandbox, Prod, Next vs everything else?
