### ISSUE TITLE
[Github Actions] Create IAM role for use with github action OIDC

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#62206]
## Description
Create IAM role that Github uses to perform its operations

## Resources 
- https://github.com/department-of-veterans-affairs/vsp-platform-infrastructure/pull/68
- https://github.com/department-of-veterans-affairs/vsp-platform-infrastructure/blob/main/.github/workflows/helm-release.yaml

## Acceptance Criteria
- [x] The role exists
- [x] All workflows are updated to use this role instead of AWS secrets

## Refinement Guidance - Check the following before working on this issue: 
- [x] _Team label assigned ("platform-tech-team-2")_
- [ ] _Epic assigned (if needed)_ 
- [x] _Estimated (points assigned)_
- [x] _Sprint assigned (once planned)_
- [x] _Team member(s) assigned_

**Comment by hgbarreto** [comment]
`vsp-infra-gha-oidc-role` has been created

**Comment by hgbarreto** [comment]
New OIDC  role use has been merged and confirmed to work.
