### ISSUE TITLE
Unit Test for Workflow: "Add Spouse" - Part 2

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#6220]
## Goal
Write and complete a unit test for the workflow mentioned above.

## Considerations
- Implement items from previous unit test tickets
- Use some existing unit test as a model
- Pages 4 and 5 will have some list and loop functions

## Acceptance Criteria
- [ ] 80% coverage for the workflow has been achieved.

**Comment by micahchiang** [comment]
PR - https://github.com/department-of-veterans-affairs/vets-website/pull/11833

**Comment by micahchiang** [comment]
PR merged.
