### ISSUE TITLE
[Design] Determine design applications for non disability claim types, STEM, and decision review cards

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#62217]
## Acceptance Criteria

- [ ] Mock designs for the key non-disability claim types, STEM, and decision review cards
- [ ] Design aesthetic matches approach to disability card redesign.

**Comment by skylerschain** [comment]
This is a dupe of https://github.com/department-of-veterans-affairs/va.gov-team/issues/62179.
