### ISSUE TITLE
Contact Center Review for Veteran Facing Forms - Form 21P-0847

### ISSUE THREAD

**Issue by tbaker1026** [department-of-veterans-affairs/va.gov-team#62215]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
Digitizing Form 21P-0847 - Substitute Claimant upon Claimants death

### Launch Date
Tentatively week of July 31st, 2023

### Version Number
Version 1

### Product Guide
[*Please provide product guide link*](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/21P-0847/Form%2021P-0847%20Product%20Guide.docx)

### Product Video
*Please provide product video link*

### Product Video Transcript
*Please provide product video transcript link*

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
@starlow00 Note to self.

**Comment by starlow00** [comment]
In progress, will be complete this sprint.

**Comment by starlow00** [comment]
Hi @tbaker1026 :) Are you able to obtain a higher-resolution capture of the workflow chart image under Substitute Claimant Upon Claimant's Death? The current one in the document is too small to read easily.

**Comment by starlow00** [comment]
One more thing re. images on this one, @tbaker1026: For Step 6: Claimant's Relationship to Veteran, the image seems mostly correct, but the step number that appears in the image is 2 rather than 6. Can you please send me a corrected image?

**Comment by tbaker1026** [comment]
@starlow00 Updated Product Guide - [https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/21P-0847/Form%2021P-0847%20Product%20Guide%20(2).docx](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/21P-0847/Form%2021P-0847%20Product%20Guide%20(2).docx)  
  
Link to workflow  
[https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/21P-0847/21P-0847workflow.png](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/21P-0847/21P-0847workflow.png)

Let me know if these work

**Comment by starlow00** [comment]
Hi @tbaker1026 :) Thank you for the Workflow image. The image for Step 6 still says "Step 2 of 9," though.

**Comment by tbaker1026** [comment]
@starlow00 try this link  
https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/21P-0847/Form%2021P-0847%20Product%20Guide%20(3).docx

**Comment by starlow00** [comment]
Thank you, @tbaker1026. The guide looks good now; sending it to VEO for review.

**Comment by starlow00** [comment]
No changes from VEO. Current copy attached. [VA Form 21P-0847 Product Guide SRT 10122023.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVZNQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--37798852f987463be9058326253c3b054f4c20ae/VA%20Form%2021P-0847%20Product%20Guide%20SRT%2010122023.docx)
