### ISSUE TITLE
Design Intent  - IA Feedback - Sitewide Facilities, Facility Locator, Improve Search, Add Filters

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#62212]
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions
- The addition of clickable map targets with number tags is a great idea - @briandeconinck may be able to field more questions about any a11y concerns there as you iterate. 
- A plug to fill out an[ intake ticket with Sitewide CAIA](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=RLHecht%2C+coforma-terry%2C+kristinoletmuskat%2C+laurwill%2C+sara-amanda&labels=sitewide+CAIA%2C+sitewide+content-product+support%2C+Sitewide+IA%2C+sitewide+content%2C+sitewide+accessibility&projects=&template=sitewide-content-intake-form.md&title=%3CType+of+Request%3E+from+%3CTeam%3E) team. They may be able to provide content, a11y, & IA help here. For IA specifically, you'll need to determine what to name these various buttons and fields and well as where those additional search tools (searching by state) will be located on the global site (if you decide they need their own page at all). What will their URLs should be? How and when will they cross-link? Can users find them and understand the difference? 
- The tab design on mobile poses challenges. It may not be possible, but I'd nudge you to explore ways you can make a single pane without tabs work.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- **Should**: Like others in the meeting, I prefer the drop-down accordion button to the modal design you mocked up. But I agree with @briandeconinck and am wary of the _placement_ (on Desktop) of it off to the far right / share concerns of it getting lost. If you have good rationale to keep it there, definitely include findability tasks for Veterans around this component in user research. 
- **Consider**: is there any reason users may want to **sort** their search results on some criteria other than closest distance? 
- **Consider**: I love the thought behind the "types of care" search index that leverages typeahead search and additional keywords added to those care types. Have you considered also linking to the full list of the 110+ types of care so that users can look at that in full (vs. only being able to keyword search against it)?  

cc // @erinrwhite

**Comment by mmiddaugh** [comment]
@thejordanwood is this issue still needed or have we addressed all the feedback?

**Comment by thejordanwood** [comment]
@mmiddaugh This feedback has been address. I'll close this ticket.
