### ISSUE TITLE
SOCKS access for [Joe Knipes]

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#62222]
### Your Name

Joe Knipes

### Your Email

joe.knipes@oddball.io

### Your Role and Team

Support Specialist - VFS Platform Support

### Product Manager (PM) name and email

Alyssa Gallion, Alyssa.gallion@oddball.io

### Product Owner (PO) name and email

NA

### Access Type Requesting

platform

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDUMEneeLb/MPWmLO9ySdEW/6Fr++janpuR+yejsnFG/TwsCr5r+FLPkdB1RL0ysXzNb0PlyZNg7OSBDD7qmYrJ2iiFgp9CNoh7vLpE5EGmZZ8odLUECsGPoT0aqn/2aE+qt4dTPF34Ffw2wRzZpAybIo260fe9iCm8djZoa/ju0/CbLjlidMP+xkJ88szJIiey59gCj6RwsuGmhiFPQ8iSgFFv+fVsUorZ380Tly7Iu6nVzCBg+u0DVR+h/C3XQf/QIBiKbMA1ebDga9XtB8fVUrJKv3TfWxLrA2WX5UxSK0AHFAWduWhsC1Tda0ze7c13Qg7H95uPBeyIoVkA9fObXtcVZJIsLjD4T6bhq/nE5y569HlKBY4ExNVi/vRQgGHTflGTFPNyJ6U919C8GcesJkF4kW5qerAdQN3fFAr8LPJP2gde/j/zXAM5AY1BRxs1Z21jROmc9NpDNiMwUgakCe3+dhIkGw8Sd869aqLlC9Le+6T0Cz9OpjdwzjOFuqc= joeknipes@josephs-air.lan

### E-QIP Transmittal Confirmation

![Screenshot 2023-07-18 at 4 22 57 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/131686965/fe5131fe-e022-4c4a-be81-18147b300308)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by rmtolmach** [comment]
@jknipes run `vtk socks setup` and then you should be good!

**Comment by flooose** [comment]
> @jknipes run `vtk socks setup` and then you should be good!

We failed. Starting again tomorrow :/
