### ISSUE TITLE
Sign out all button - Secondary Research

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#62224]
#### Acceptance Criteria
- [x] Conduct Secondary Research on how "sign out all" works on various sites
- [ ] Make recommendations to team on how this feature could be implemented on VA.gov
- [ ] Reviewed by UX Team
- [ ] Reviewed by PMs
- [ ] Documentation has been updated
- [ ] Put published research in drive

#### Context
Copied over from a comment on the FE ticket

charlye-bluetiger
commented on Mar 15
Logout of all devices button needs to be included for a security requirement
Envs:
Staging - SiS exists on all
Production - only flagship VA.gov only on mobile
QUESTION to be answered: Where would users prefer to see “log out” (of everything)?
Potential placement:
￼
SSOe users should not see this option
Eventual goal to deprecate IBM solution across the board
Staggered migration of user sessions to leverage Identity’s SiS
Timing for logout
SSOe 15 minute increments for keep alive, logout after 30 minutes
SiS 5 minutes refresh, logout after 30 minutes
Timing:
Single sign on to access all VA sites e.g. MyHealtheVet, eBenefits, VA.gov
Logout of all sessions

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by charlye-bluetiger** [comment]
https://app.mural.co/t/oddball4265/m/oddball4265/1694188194725/8b8d5007a442ec71eabcd36941e819eb97dc8968?sender=ub6d328e737d4511e3f063904
