### ISSUE TITLE
wireframe IPP concept

### ISSUE THREAD

**Issue by djmunoz1** [department-of-veterans-affairs/va.gov-team#62247]
As a business stakeholder I want to see a rough visual of the concept for IPP so that I can more easily identify integration points.

ACCEPTANCE:
- roughly illustrates user flow for veteran as it is currently understood
- need to illicit feedback from login.gov and NIST so should reference some data parameters
- reflects user and trusted referee interaction

DEF OF DONE:
- wireframe doc stored in shared team product folder

**Comment by skirkman16** [comment]
wireframes and workshop are in [this mural](https://app.mural.co/t/innovationboards1199/m/innovationboards1199/1690383825978/b274397c49860b2b3bed435eb18054e3bbf691a9?sender=u99cd1ac4f5c240d8dffd4204)
