### ISSUE TITLE
DR | Request Lighthouse API rate-limit increase

### ISSUE THREAD

**Issue by kylesoskin** [department-of-veterans-affairs/va.gov-team#62250]
We have encountered >50 429s in the last 2 weeks. Want to request raising a bit. 

![Screenshot 2023-07-19 at 11.04.30 AM.png](https://images.zenhubusercontent.com/62067253500f33af56810776/46a11fb3-d80a-415b-9b29-34f26c11a3b0)

https://vagov.ddog-gov.com/apm/traces?query=%40_top_level%3A1%20env%3Aeks-prod%20%40http.status_code%3A429%20%40http.path_group%3A%2Adecision_reviews%2A&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_code&graphType=flamegraph&historicalData=true&messageDisplay=inline&query_translation_version=v0&shouldShowLegend=true&sort=time&spanType=service-entry&start=1688569386687&end=1689778986687&paused=false

https://developer.va.gov/support/faq say to email Lighthouse support email and ask for a raise in limit.

**Comment by saderagsdale** [comment]
Update: The request is in, they approved the increase, just have not yet heard back if it was completed or not yet.
