### ISSUE TITLE
Vets-api terminal access for Tze-chiu Lei

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#62281]
### Your Name

Tze Lei

### Your GitHub handle (terminal access is managed through GitHub)

@tlei123

### Team, Role, and Company of the target individual

VA Product Forms, Front-end Engineer, Ad Hoc LLC

### Product Manager (PM) name and email

Tricia Baker tricia.baker@oddball.io

### Product Owner (PO) name and email

Matthew Dingee, matthew.dingee@va.gov

### COR Name (leave "None" if you listed an AWS user name above)

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

None

### Please confirm if you are on the VFS Team Roster or Platform Team Roster

- [X] [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Please confirm E-QIP Transmittal/Adjudication. This could be a screenshot of your Transmittal/Adjudication email, a link to another request where you've submitted this proof (i.e. AWS/SOCKS), etc.

- [X] I have attached proof that I have either transmitted my E-QIP survey or previously received a favorable decision (by including in "Additional Notes" section below)

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [ ] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### Additional Notes

Re. my name in the systems: I'm **Tze Lei** [tze@adhocteam.us] on the VFS Team Roster, but I'm **Tze-chiu Lei** on VA paperwork/systems [tze-chiu.lei.va.gov], as well as on Google [tclei2009@gmail.com] & GitHub [where all 3 email addresses are included in my profile].  Sorry for any confusion!

I need access to both Staging & Production, to monitor submissions of our pre- & post-launch digitized VA forms at the `vets-api-web*` endpoints -- Staging just before form-launches and Production just after.

FWIW, Garret Rabian's one of my VA-Product-Forms teammate, and he's [already been approved](https://github.com/department-of-veterans-affairs/va.gov-team/issues/55519).

COR [current]: Jonathan Ivey Jonathan.ivey@va.gov

EQIP Transmittal Notice screenshot [from 2019 (2 contracts ago; can't remember the COR back then):
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/587583/bccfe20b-13c4-4dd7-bdef-d8db3406c1dd)

### Additional resources for Support Engineer

- [ ] For users on a VFS team but not in the VFS Team Roster, they must start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] Instructions for handling requests [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access) - Support Only

**Comment by bdech** [comment]
Found in VFS Team Roster

**Comment by bdech** [comment]
@evansmith You’ve been granted access to the `dev`, and `staging` environments.

Here's some additional documentation for the [Vets API on EKS](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-TerminalAccess)

Access to `prod` is pending approval by OCTODE, and we'll update you as soon as it's available.

**Comment by evansmith** [comment]
@bdech I think I was tagged on the wrong ticket.

**Comment by bdech** [comment]
> @bdech I think I was tagged on the wrong ticket.

Yes, im sorry that was my mistake

**Comment by evansmith** [comment]
@bdech no problem!

**Comment by BillChapmanUSDS** [comment]
@tlei123  We are beginning the process of requiring more specific descriptions of production access and will have a stricter burden of justification. Can you describe some of the tasks you would like to perform on production environments that cannot be completed in lower environments?  

3 Month access is granted but can be expanded to 6 months if the question above is answered and the access-justification-example-provided tag is added.

**Comment by bdech** [comment]
@tlei123 You've been granted access to `Prod`, expiring 10/20/24. I will update the expiration to 6 months if access justification is provided, and Bill approves.

**Comment by bdech** [comment]
slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1689886711053579)

**Comment by tlei123** [comment]
@ndsprinkle @tbaker1026 , looks like the Prod-access justification I provided wasn't enough [see previous 2 comments from @bdech ]...

Would you mind add something here in this ticket to justify my Prod-access please?  Otherwise, access will expire in 6 mos. instead of a year.  Thanks much!

**Comment by bdech** [comment]
@tlei123 `Prod` access is currently designated to 3 months, but can be extended to a maximum of 6 months if Bill approves justification for extended access.

**Comment by tlei123** [comment]
@bdech , please keep this tic Open for just a few days longer.  I'm waiting for higher-level justification to be given for bumping access to 1 year.  I'll update with another Comment once I have that.  Thanks much!  :)

**Comment by tlei123** [comment]
@bdech , please feel free now to Close this ticket.  Our team has met on access-expiration, and decided we'll just re-apply after 3 months if necessary.

Thanks much for your support, and have a great weekend!  :)

**Comment by lindsay-insco** [comment]
@tlei123 Your Vets API Terminal Production access has expired.

Would you like to request an extension? You have 72 hours to respond, or your
access will be revoked and you will need to fill out a new request

**Comment by lindsay-insco** [comment]
@tlei123 Production access has been removed. If you would like access, please fill out a new request.
