### ISSUE TITLE
Research - Contact Center

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#62295]
**Background:**

As part of improving the messaging around the current errors found when starting the 526 EZ it is critical that we understand how the contact center will respond the the information we provide in the error message. 

Once implemented the new error message could indicate to the user to call the Contact Center phone number and provide  some or all of the missing information to the Contact Center representative:

- Date of Birth
- SSN
- BIRLS ID (Beneficiary Identification and Records Locator (Sub)System)
- EDIPI (Electronic Data Interchange Personal Identifier)
- Participant ID

As part of this research we should determine how the Contact Center would currently respond to this type of inquiry and how they would instruct the Vet to find this information, what they would do with this information and how they would instruct the vet to proceed with their form once they have updated this information. 

Also, since we maintain a product guide that is utilized by the contact center, we should understand how they receive product guide updates, if and how they reference it, and how they go about training when its updated. 

Finally, since there may be multiple times we make changes that effect the contact center this could be a good chance to get some foundational information about the contact center, such as how many people work there, how calls get routed, what a typical day in the life is like, etc... this will help us better partner with them and anticipate future opportunities or challenges. 

**Update**
Based on conversations with Kimberly and Chante it was discovered we could get some good information from the EVSS help desk

Additional points added to acceptance criteria for this cohort

**Acceptance Criteria:**

1. Understand how script is used by Contact Center?
2. Understand what is/can be done by the Contact Center with the five possible missing data points
3. Understand how the product guide is utilized in the Contact Center work
4. High level understanding of a contact center representative "day in the life"
5. Understand how these type of problems are escalated to the EVSS Help Desk
6. Determine whats steps the EVSS Help Desk would perform to resolve these issues
7. Determine if/how their responsibility may change with the Lighthouse Migration work once its completed

**Comment by austinjprice** [comment]
@nnicholas7 @juliepedtke I added additional criteria based on direction we are receiving to reach out to EVSS Helpdesk as first step while we wait to get access to Contact Center.

**Comment by nnicholas7** [comment]
Notes from Contact Center Conversation- https://docs.google.com/document/d/1D5pwgQFMmTPvm5lIEdvhhrIuPDudqec9ZDavnIVdnxA/edit
