### ISSUE TITLE
Research - ITF Experience and Policy Options

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#62296]
As part of the "Intent to File" expiration date discovery work completed during technical research it was determined that the ITF date is set at **exactly** 1 year from the date of creation. This suggests that if a user, while in New York, starts there form at 11 am on Aug 1 2022, then their ITF will expire at 8 am on Aug 1 2023. 

The assumption is that users are provided a date but not a time of expiration, and a user would, understandably, assume expiration would occur at the end of the day regardless of where they are in the world. 

To ensure we build the best possible experience for the veteran and reduce ITF related issues we should consider the following:

1. When and how is a used first provided with an Expiration Date and what does that information convey?
2. How often are they reminded of this Date while in the form or outside of this form?
3. Is there any indication of a soon to be approaching expiration in the form or outside of the form?
4. What happens in the form once an ITF has come pass? What happens after attempted submission?

Finally, we should identify and confer with policy to understand options to provide maximum leniency and clear understanding of that policy.

Acceptance criteria:
1. Clearly documented flow of the current ITF experience
2. Documented policy options around ITF
3. Testable hypotheses for Short, Medium and Long term improvements to the ITF experience

**Comment by nnicholas7** [comment]
Ticket Update 8/1/23:
Deliverables
- Process Flow of ITF experience- https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1690405473003/4b31d27cd55718422ae4453cb958ec8075ff2944?sender=u813bb40bd648bc2b58599242
- ITF Policy Q&A Document- https://docs.google.com/document/d/1bdt4KTEWY0uvylXRrB-Ek_VACAvwAudwdmOS4DdZT-k/edit

**Comment by micahaspyr** [comment]
[ITF ticket expiration.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/12448765/ITF.ticket.expiration.docx)

**Comment by juliepedtke** [comment]
Adding the [Policy Q&A with improvement scenarios](https://docs.google.com/document/d/1bdt4KTEWY0uvylXRrB-Ek_VACAvwAudwdmOS4DdZT-k/edit) listed in acceptance criteria. This work was deprioritized before we could complete this doc and close all comments, which I think means the original AC should have been edited to reflect this.
