### ISSUE TITLE
Draft updates to VA.gov FAQ page

### ISSUE THREAD

**Issue by djmunoz1** [department-of-veterans-affairs/va.gov-team#62307]
Context
VA.gov FAQ page needs to be updated to provide information on both Login.gov and ID.me, sunset date, and relevant links to other pages in order to provide Veterans with the most up to date and relevant information for them to migrate to either modern credential. 

User Story
As a Veteran, I need to be able to find a FAQ page with the answers that are most relevant to my questions related to modern credential migration so that I know how and why I need to start using a modern credential. 

AC
- [ ] Show common questions and answers related to modern credential migration
- [ ] Provide information on how to create either modern credential
- [ ] Working hyperlinks to relevant pages
- [ ] Contact information for support

**Comment by djmunoz1** [comment]
https://app.ddog-gov.com/sb/f327ad72-c02a-11ec-a50a-da7ad0900007-073855edd898d683ad70cee79e5a282d?from_ts=1682084808544&to_ts=1689860808544&live=true

**Comment by lmorris3** [comment]
@CarlDickerson this is being handled by the VA.gov team/CAIA. I think we can share with them what we've drafted so far but remove this from our deliverables. Do you agree?

**Comment by CarlDickerson** [comment]
@lmorris3 agreed here.

**Comment by SophiaPhilipMO** [comment]
Sitewide is owning
