### ISSUE TITLE
Review Login.gov transition blog 

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#62310]
Carl shared a draft blog post for review. 
Here's the context he shared via slack: "Assessing content that has been released in blog thus far, I saw a gap in explaining the "why" of this certain uptick in talking about sign-in and pushing Login.gov, so this particular piece focuses on Digital Modernization efforts and moving toward a better sign-in experience."

[https://app.zenhub.com/files/133843125/03065d81-8d44-40fe-ba28-2078e804266e/download](https://app.zenhub.com/files/133843125/03065d81-8d44-40fe-ba28-2078e804266e/download)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @CarlDickerson. This sounds like it's driven by an identified opportunity, not a specific deadline attached to an event or milestone. Is that correct? Asking for prioritization purposes. Thanks!

**Comment by CarlDickerson** [comment]
@DanielleThierryUSDSVA That is incorrect. perhaps I could have given better context. As part of our campaign plan, we're aiming to do roughly one Login.gov featured blog post per month. As part of our plan we were hoping to have this content reviewed and ready for submission to VEO by end of our current sprint, Wednesday 8/2. Is this doable on your end or when is the soonest that you could provide feedback?

@djmunoz1 looping in for transparency.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @CarlDickerson. Thanks for the added information on timing. I can provide some high-level feedback tonight, but I can't provide the type of in-depth feedback I've provided on previous blog posts this quickly. I'll touch base with the team and communications group about working out a schedule for communications reviews moving forward. Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @CarlDickerson @djmunoz1. Here's some high-level feedback:

- Did the identified gap for this topic surface from Veteran feedback that they're wondering why there's been an uptick in talk about sign-in? If yes, that's great. If no, I'm not saying not to put this one out there definitively, but I would caution us to not do too many "you might like to know" type blogs. We don't want to risk having people tune out of articles about Login.gov and then potentially miss some of the more critical, time-sensitive, actionable pieces of information.
- If we do use this angle, shorten the intro to get into the article faster.
- Recommend removing the reference to the commercial product in the quote. I've explained more in a [comment in the doc](https://dvagov-my.sharepoint.com/:w:/g/personal/danielle_thierry_va_gov/EfW5mmGJOE1Hk_kn-Wj8jy8ByrWDwsPq_5AVGz6FVRnFFQ?e=kwo9ZE). 
  - Check with IT strategic communications to ask if the VA digital modernization vision from 2017 the language we want to use now or if there's more updated language for this vision. 
  - The blog refers to DS Logon and My HealtheVet as "tools." This risks confusing people about My HealtheVet the portal and My HealtheVet the account. Per content brief and discussions, please always be sure to use "account" whenever we're referring to the account. 
  - Similarly, avoid "you can use Login.gov" and instead always put in the context of "you can use your Login.gov account." I believe research showed confusion around whether Login.gov is itself a website/portal or an account.
  - Refer to additional note in doc about the line about secure experience through MHV and DS Logon.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @CarlDickerson @djmunoz1. Here's some high-level feedback:

- Did the identified gap for this topic surface from Veteran feedback that they're wondering why there's been an uptick in talk about sign-in? If yes, that's great. If no, I'm not saying not to put this one out there definitively, but I would caution us to not do too many "you might like to know" type blogs. We don't want to risk having people tune out of articles about Login.gov and then potentially miss some of the more critical, time-sensitive, actionable pieces of information.
- If we do use this angle, shorten the intro to get into the article faster.
- Recommend removing the reference to the commercial product in the quote. I've explained more in a [comment in the doc](https://dvagov-my.sharepoint.com/:w:/g/personal/danielle_thierry_va_gov/EfW5mmGJOE1Hk_kn-Wj8jy8ByrWDwsPq_5AVGz6FVRnFFQ?e=kwo9ZE). 
  - Check with IT strategic communications to ask if the VA digital modernization vision from 2017 the language we want to use now or if there's more updated language for this vision. 
  - The blog refers to DS Logon and My HealtheVet as "tools." This risks confusing people about My HealtheVet the portal and My HealtheVet the account. Per content brief and discussions, please always be sure to use "account" whenever we're referring to the account. 
  - Similarly, avoid "you can use Login.gov" and instead always put in the context of "you can use your Login.gov account." I believe research showed confusion around whether Login.gov is itself a website/portal or an account.
  - Refer to additional note in doc about the line about secure experience through MHV and DS Logon.

**Comment by CarlDickerson** [comment]
@DanielleThierryUSDSVA thank you for all of your assistance! The high level feedback you have provided, I will now take back and try to rework the post a bit. Hopefully we can work out a timeline for continued collaboration, editing and topic discussions.

**Comment by DanielleThierryUSDSVA** [comment]
@coforma-terry Closing this ticket - thanks!
