### ISSUE TITLE
[ToU] SuS API client - called in SSOe & SiS auth flows

### ISSUE THREAD

**Issue by aparsley** [department-of-veterans-affairs/va.gov-team#62325]
## Issue Description
Able to be broken out when SiS is migrated to standalone.

## Acceptance Criteria
- [ ] Called in SSOe & SiS Auth Flows

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by parkerbees** [comment]
Closing. This ticket is over a year old. If still relevant it can be pulled from Zenhub in future.
