### ISSUE TITLE
[ToU] Add secrets to parameter store and update application manifests

### ISSUE THREAD

**Issue by aparsley** [department-of-veterans-affairs/va.gov-team#62329]
## Issue Description
We need to add secrets to parameter store and update application manifests

## Acceptance Criteria
- [ ] Add secrets to parameter store
- [ ] Update application manifests

#### Tech notes

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by parkerbees** [comment]
Closing. This ticket is over a year old. If still relevant it can be pulled from Zenhub in future.
