### ISSUE TITLE
[ToU] Create route to determine current user SuS status

### ISSUE THREAD

**Issue by aparsley** [department-of-veterans-affairs/va.gov-team#62327]
## Issue Description
we need to create route to determine current user SuS status

## Acceptance Criteria
- [ ] RESTful, ICN provided by frontend as mandatory param
- [ ] Redis cache for status tied to user redis cache lifespan

#### Tech notes

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by parkerbees** [comment]
Closing. This ticket is over a year old. If still relevant it can be pulled from Zenhub in future.
