### ISSUE TITLE
[ToU] Creating prototype for ToU frontend

### ISSUE THREAD

**Issue by aparsley** [department-of-veterans-affairs/va.gov-team#62337]
#### Acceptance Criteria
- [ ] Create Figma
- [ ] Choose frontend framework / ui library - spin up github
- [ ] Use testing framework (RTL or Jest)
- [ ] Block out prototype pages (need to find out how many pages will be needed)
- [ ] Reviewed by PMs

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by asg5704** [comment]
@kingbmike @jimcconnelly this can be closed
