### ISSUE TITLE
pull email list for all Reactivation segments

### ISSUE THREAD

**Issue by djmunoz1** [department-of-veterans-affairs/va.gov-team#62346]
As an email admin I want the full list of veterans who are counted in the Reactivation segment so that I can send them a message about login.gov adoption.

ACCEPTANCE:
- there are two separate email lists (csv files)
- The Reactivation segment is divided into two buckets (veterans who have login.gov and any other credential, veterans who have ID.me and any other credential except login.gov)
- List 1 includes the following segments...
DSL+LG 
MHV+DSL+LG
MHV + LG
DSL + ID.me + LG
MHV + DSL + ID.me + LG
MHV + ID.me + LG
- List 2 includes the following segments...
DSL + ID.me
MHV+DSL+ID.me
MHV + ID.me

Resource:
[LGA Priorities](https://docs.google.com/spreadsheets/d/1Q2W_2PKVwCKaMNEG-RsThlb7nUErJ18rIXg1Mr1W0ZU/edit#gid=643610543) 

DEF OF DONE:
- lists emailed to dawn.munoz@va.gov

**Comment by sdickson-gt** [comment]
@djmunoz1 I recall in our discussion yesterday, that you were looking for a couple specific "sub-segments", but the ticket specifies two email lists: 1 for all reactivation and 1 for all organic.  Do you want to distinguish the 2 reactivation buckets in any way "The Reactivation segment is divided into two buckets (veterans who have login.gov and any other credential, veterans who have ID.me and any other credential except login.gov)". 
e.g. divide the reactivation emails into 2 lists?  Or do you want a separate list of each segment?

**Comment by sdickson-gt** [comment]
Some notes... we have MPI dataset and MHV dataset.  MHV is tracking about 3.4M MHV credentials whereas MPI is only aware of 2.xM MHV credentials.  We (currently) only have the ICNs for the MHV credentials, not the emails, so for the moment we're dependent on the MPI dataset for emails.  Also, in terms of whether any of the 1M MHV credentials that IAM MPI isn't tracking meet the reactivation criteria: problem is we also don't (currently) have the last used date in the MHV dataset.  So, until we get more info and regular updates of MHV datasets, we have to just rely on solely the MPI dataset.

**Comment by djmunoz1** [comment]
right, to two lists @sdickson-gt for a little color, the dividing line is basically whether or not the veteran has login.gov vs IDm.e. So one bucket: has login.gov OR login.gov and ID.me + any legacy cred.  Other bucket: has ID.me + any legacy cred + !login.gov

**Comment by djmunoz1** [comment]
got it re: MPI and MHV datasets, interested in chatting about where we are with that ask and whether any product-side outreach would be helpful so we can get access to that missing 1M.

**Comment by sdickson-gt** [comment]
emails sent via VA teams chat.  Note that the numbers won't meet the segment counts because some records in the MPI dataset don't have emails
