### ISSUE TITLE
FE | Profile | Contact Information | Fix / remedy failed unit tests for useProfileTransaction hook

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/va.gov-team#62368]
## Issue Description
The CI/CD Github action runs have been failing periodically due to unit tests that the team is responsible for. 

Specifically the unit tests for the `useProfileTransaction` hook. Not really sure why those passed for a long time and now are failing, but the hook really isn't used outside of experimental forms library work.

I think the plan of action should probably go:

- figure out if there is an obvious solution to the failing tests, and fix the tests if possible.
**OR**
- if the tests are flakey to the extent that they should be rebuilt, or the hook should be completely rebuilt, then we will need to do more work to just remove the related functionality all together. Since it's not used in prod, and the form system is not in active development there isn't a reason to the keep the code.
  - Create a `feature archive branch` that has the current code, so that in the future if we really wanted to revisit it, we can just pull down that branch and attempt to merge/rebase with main so as to get back all the code we remove.
  - Remove, hook, tests, and experimental component. The home phone was the only section of the profile that had used the new form library.
  - Remove feature toggle around using the experimental form system from FE and API
  - I'm kind of leaning towards ripping it all out. Its been a while since we did this work and its just been sitting around for probably over a year at this point.

## Front end tasks
- Ensure the page is styled according to design spec. 
- Ensure the back end data from API is displayed in local and review instance
- Ensure unit tests are available. 
- Ensure your code changes are covered by E2E tests
- Run axe checks using the Chrome or Firefox browser plugin
- Test for color contrast and color blindness issues
- Zoom layouts to 400% at 1280px width
- Test with 1 or 2 screen readers
- Navigate using the keyboard only

## Acceptance Criteria
- [x] Designer comments on this issue to approve page styling 
- [x] Unit tests pass
- [x] E2E tests cover current code and regression
- [x] End-to-end tests show 0 violations.
- [x] The data returned matches API response (for given user or scenario)
- [x] All axe checks pass
- [x] All color contrast checks pass
- [x] All zoom testing passes
- [x] All keyboard checks pass 
- [x] All screenreader checks pass

**Comment by mtcA6** [comment]
notes fron 7/24 huddle  
  
adam you said it's unused code, is it unused as in it's behind a feature flag? yes it is behind a feature flag it was for using a new forms library   
we wanted to use a new forms library - the code isn't likely going to be put into production at any time  - the team was disbanded - there isn't likely to be progress the form library code is in maintenance

**Comment by adamwhitlock1** [comment]
Some more context. 

The underlying [library dependency called Formik](https://formik.org/) for the VAFSC (VA Form System Core) that was being developed is kind of in maintenance mode / not under active development, and there are some performance concerns that have bubbled up in the community around the library. It obviously isn't up to me, but I would say that if the work started back up on VAFSC, I would look at something like the [react-hook-form](https://www.react-hook-form.com) instead of Formik.

All that being said, the work tickets around using the VAFSC should probably be closed for now, and we can re-open tickets if/when that work resumes and we get the go ahead for using it. There are several components and pieces of code in the existing profile codebase that could be removed, so I think removing them is a good idea for consistency and cleaning up the cruft in general.

Some further links to things around this:

The archive branch I created is: ["do-not-delete-VAFSC-profile-MVP"](https://github.com/department-of-veterans-affairs/vets-website/tree/Profile/aw/do-not-delete-VAFSC-profile-MVP). This branch could start as a point where we could pick this work back up and not lose all the previous work I did.

The [VAFSC library repo](https://github.com/department-of-veterans-affairs/va-forms-system-core) in case anyone wants to see it or keep tabs on active development when it starts back up.

[Most recent slack discussion that I am aware of around VAFSC work picking back up](https://dsva.slack.com/archives/CBU0KDSB1/p1685727274202479?thread_ts=1679493582.438199&cid=CBU0KDSB1)

**Comment by adamwhitlock1** [comment]
@mtcA6 this is ready to validate.

Steps to validate in staging:
- log in with any LOA3 user, and view profile > contact information page
- update home phone
  - since that was the only piece of profile that was hooked up to the experimental form system, that is the only section that needs to be checked
  - verify that home phone number updates correctly and changes persist after page refresh

**Comment by mtcA6** [comment]
This looks good, should i close this ticket or do you still need to merge the code before I do that?

**Comment by adamwhitlock1** [comment]
Ill close it now.
