### ISSUE TITLE
[COGNITION]: Consider moving the urgent medical need alert box above the action buttons

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#6237]
## Description

The If you have an urgent medical need alert box is after the Back | Continue buttons. It could be missed by assistive technology users, so I'd like to consider evaluating it for placement on the page. Screenshot attached below.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## Acceptance Criteria

* [ ] As a screen reader user, I do want to hear the alert box information before I decide to go back or continue scheduling an appointment

## WCAG or Vendor Guidance (optional)

* [Info and Relationships: Understanding SC 1.3.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-programmatic.html)

## Screenshots or Trace Logs

![Screen Shot 2020-02-26 at 1 56 35 PM](https://user-images.githubusercontent.com/934879/75383080-4d6a1c00-58a1-11ea-8bbf-f3225564dcc1.png)

**Comment by 1Copenut** [comment]
@lenaecb I ran into this box today while re-testing the H1 focus management. Right now we have the alert in a div with `aria-live="assertive"` so it will interrupt the screen reader and read the alertbox before anything else on the page. I think this is the intended behavior, but wanted to ask if it would *always* appear on the page, or there was conditional logic making it appear.

LMK and I'll adjust my ticket as needed. Thank you.

**Comment by jbalboni** [comment]
@1Copenut It's always on the page.

**Comment by 1Copenut** [comment]
@jbalboni Roger that. I'm not sure we need to set it to `role="assertive"` unless there's not an easy way to reduce that. I'm concerned it overrides the default H1 announcement and is a fair bit of information to make AT users parse through on page load.

**Comment by jbalboni** [comment]
We could definitely remove that role. I think we may have been overzealous adding those roles to the alerts. Seems like we only need them when they're dynamically added to a page?

**Comment by 1Copenut** [comment]
Yeah, that feels right in this case, to remove the `role`. Because it's always on the page, having it read inline makes sense. Unless there's a compelling content case to force the issue and have it read aloud first.

**Comment by 1Copenut** [comment]
@jbalboni I'll test in the morning. Today was a bit swamped.

**Comment by 1Copenut** [comment]
@jbalboni I confirmed new placement of the alert box and that it did *not* read aloud. Everything is working as expected and no axe errors. Moving to close.
