### ISSUE TITLE
Profile 2.0 Screens Copy Epic

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#6238]
# User Story
As a user, I need to be able to easily find and manage my personal information.
 
# Tasks
(Note to Tressa: Samara to go through the screens together  with Tressa to figure out exactly what copy needs to be updated and what doesn't. This will determine the task list.)

# Acceptance Criteria
 All copy has been updated and approved by the content team.

**Comment by Samara-Strauss** [comment]
@tressaellen step one here is for you and I to sit down and review the screens and go over what is already approved copy/what is not so we can adequately communicate this to whoever we work with on copy. I'll DM you to set this up.

**Comment by Samara-Strauss** [comment]
@tressaellen I legit do not remember if we ever did this since it looks like it was in The Before Times 😂 . I am assuming we can close since we're good on copy. Feel free to reopen if we need it for any reason.
