### ISSUE TITLE
[FE] My VA Claim Status EVSS > Lighthouse: Map status from Lighthouse to user-friendly descriptions

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#62397]
## Background
The statuses returned from the Lighthouse API for the CST are not user/human friendly - for example test user 81 has an underscore in the status via Lighthouse:
![TC1 81 LH](https://github.com/department-of-veterans-affairs/va.gov-team/assets/45603961/a0950299-20ed-400f-810c-0e65fc2fe8e9)

Compared to EVSS:
![TC1 81 EVSS](https://github.com/department-of-veterans-affairs/va.gov-team/assets/45603961/6289ff4f-af45-42aa-ad16-bd1902e76721)

## Tasks
- [x] Update status returned from Lighthouse API to use more user friendly display names ([for example](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/claims-status/components/ClaimsListItem.jsx#L8-L15))
- [x] Test
- [ ] Validate

## Acceptance Criteria
- [ ] Test a variety of test users with Lighthouse to confirm statuses are displayed with proper formatting 

## Validation
- **_Who can validate this ticket? (FE, BE, Design, PM)?_** Anyone
- **_How can this work be validated?_** 
1. Log into staging with test user with the feature flag for Lighthouse not applied
2. View claim status, take a screenshot for comparison
3. Log out
4. Turn Lighthouse flag (`my_va_lighthouse_claims`) on for that same staging user 
5. Sign back into staging with the user
6. View claim status - compare to EVSS version and confirm formatting

**Comment by adamwhitlock1** [comment]
When trying with user 81 and judy morrison on staging, I am getting a 403 from the benefits_claims endpoint. Not sure if there is an issue with the endpoint or something else is afoot.

**Comment by ajakabcin** [comment]
We're waiting on a fix from Lighthouse to be able to validate this. Moving to next sprint for validation only

**Comment by ajakabcin** [comment]
Confirmed on staging with user 81 and judy - status look good now
81:
![Screenshot 2023-08-02 at 12 28 25 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/45603961/c48a574b-ee91-42de-ba0e-0d7bb424bd9f)

Judy:
![Screenshot 2023-08-02 at 12 41 21 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/45603961/15b4ffd9-dff4-4f5f-826e-f300e3070ef1)
