### ISSUE TITLE
[Data/UX] Discovery: Analyze and report on EZR-related searches

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#62399]
As a team member, I would like to understand what the searches and page views surrounding the 10-10EZR are so that I can build a product for Veterans that help those looking for this information online. 

- [x] Go through Google searches for Financial Information and determine those flows 
- [x] Look at searches for EZR and similar terms (e.g. "update my address, phone #, etc.")
- [x] Go through Google searches for "Priority Group" and determine how often it is searched for and what the flow is for those users (e.g. they end up on the PG page on VA.Gov and then drop off)
- [x] Look through [Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1687381992402/ac027de3375351079c9cbc93d1662510ffd3cb1a?sender=alexseelig5897) to see the team's outstanding usage questions
- [x] Talk to UX about other potential workflows and searches we would like to pull usage data on
- [x] Collate and report to team
- [x] Come up with next steps with Alex and Team
- [x] **Success: The team has a solid understand of how people are currently searching for and finding information about Priority Group and EZR**

**Comment by luis-simauchi** [comment]
Priorities for Discovery:
-- Tasks with "financial" info is the first to be worked on
--  Then Priority group search queries next
-- Then  the team's outstanding usage questions

**Comment by luis-simauchi** [comment]
list of search terms used by VA site users for Financial Information (or related functions) 
https://docs.google.com/spreadsheets/d/1QemrsFIHkdrdGTa0hDXoISnzE_4OrQOWSIjvUKv2IMI/edit#gid=1971984470

**Comment by luis-simauchi** [comment]
destination pages when site search was used with the terms listed above:
https://docs.google.com/spreadsheets/d/1s9c50wBt4YEfK43sWSZLl8pr7SoTRtB22CSVUXlQJXI/edit#gid=852521014

**Comment by luis-simauchi** [comment]
Takeaways from the search queries related to EZR / financial / priority group terms now listed within our mural board, under the Financial Disclosure Google Search section
https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1687381992402/ac027de3375351079c9cbc93d1662510ffd3cb1a?sender=dd86b16b-9350-41da-a40f-73e7da0a9598
