### ISSUE TITLE
[Spike] authentication datadog widget 

### ISSUE THREAD

**Issue by careyotto** [department-of-veterans-affairs/va.gov-team#62409]
###Description of Spike

Lighthouse is re-evaluating its refresh token policy and we're trying to better understand the impact forcing re-authentication more frequently might have on Veterans who have chosen to connect their VA data to a third-party application and access it from there.

We're interested in any quantitative data or insight VA.gov has into Veterans' experience of re-authenticating with VA.gov. For example, what percentage of Veterans struggle to successfully complete signing in on subsequent visits. (Especially for users who aren't regular visitors to the site.) 

Joe mentioned y'all might be able to create a datadog widget to help gain insight here next sprint? This ticket is a request to consider that as you do your planning :) 

**In order to** GOAL,
Have insight into the percentage of Veterans who struggle to successfully complete signing in to VA.gov on subsequent visits. (Especially for users who aren't regular visitors to the site.) 

**we need to** ACTION,
Need a datadog widget that surfaces that information

**so that** VALUE.
VA can make informed decisions on refresh token lifespans.

#### Acceptance Criteria
- [ ] Documentation has been updated
- [ ] Next steps have been determined and documented
- [ ] Results of Spike have been communicated to VA Lighthouse @careyotto @beaugrantham-va @dbrown-va 

#### MR Approver
- TBD

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by beaugrantham-va** [comment]
@dbrown-va Is this still relevant?

**Comment by parkerbees** [comment]
@dbrown-va we are migrating from Zenhub to Jira and are generally closing tickets that were created more than a year ago; however given Beau's comment above I wanted to check with you first. if this is still relevant I will make sure it gets moved to Jira and prioritized.

**Comment by dbrown-va** [comment]
@parkerbees, this should be fine to close.

**Comment by parkerbees** [comment]
Thanks, Derek! Closing.
