### ISSUE TITLE
Identity Dashboard (FE) - Fix metadata on Homepage

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#62407]
## Description
Fix the pages that use `use client` to ensure the metadata like `title` and `description` are updated

## Tasks
- [x] Ensure `localhost:3001` does not show up in the title

**Comment by acald-creator** [comment]
Blocked: `jest` test failed due to `metadata` works in the server component, not client component

Open issue for reference:

https://github.com/vercel/next.js/issues/47299#issuecomment-1477912861

Will see if the workaround works for now.

**Comment by acald-creator** [comment]
Next.js updated their `with-jest` example from this PR. https://github.com/vercel/next.js/pull/54989

Testing this current PR to see if I get the test passing.
