### ISSUE TITLE
Adding Jane Xiong to DSVA Slack

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-team#62406]
# Description

Jane Xiong was previously an AgileSix employee, and was a full member in DSVA Slack. 
Jane is returning to VA **8/1/2023**, as an employee of Friends from the City. 

Her new email address is jane@cityfriends.tech

Is it possible to: 
1. Reinstate her previous user account, as a full member. This would be very helpful, to have access to previous DMs, etc. if possible.
2. Update her Email address from `jane.xiong@agile6.com` to `jane@cityfriends.tech`

If this would require accessing her agile6 email address, then it won't work. 

Am filing this ticket very early in hopes of understanding how this can / should work before Jane's first day. But: if that messes up systems, feel free to close and I'll reopen or file a new separate ticket on her 1st day.

**Comment by LEHigley** [comment]
it looks like jane was already invited and joined w/the new email address
