### ISSUE TITLE
[COGNITION]: Let's consider moving the Edit links on the review page after their text blocks

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#6241]
## Description

The Edit links on our /review page are in between the label and text details in the source order, which creates a slightly confusing readout for screen readers. I'd like to consider moving the Edit links after the text in each "block". Screenshot attached below.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## Acceptance Criteria

* [ ] As a screen reader user, I'd like to hear "Follow-up/Routine, <MSG>, then Edit purpose of appointment, link" read aloud

## Environment

* Windows 10
* Chrome/IE11
* JAWS
* https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/review

## WCAG or Vendor Guidance (optional)

* [Info and Relationships: Understanding SC 1.3.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-programmatic.html)

## Screenshots or Trace Logs

![Screen Shot 2020-02-26 at 2 49 21 PM](https://user-images.githubusercontent.com/934879/75386780-e439d700-58a7-11ea-81d2-b258ebef6431.png)

**Comment by lenaecb** [comment]
@jbalboni - are we good to close this?

**Comment by jbalboni** [comment]
@lenaecb Not yet, still trying to the PR for this merged.

**Comment by 1Copenut** [comment]
Confirmed in staging on NVDA and JAWS. Moving to close. 

/cc @lenaecb
