### ISSUE TITLE
IdD: Refactor Providers

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#62419]
## Description
See tasks

## Tasks
- [x] Use the `.reduce` method to nest the Providers more succinctly

**Comment by acald-creator** [comment]
https://github.com/department-of-veterans-affairs/identity-dashboard-fe/pull/46

**Comment by acald-creator** [comment]
completed: https://github.com/department-of-veterans-affairs/identity-dashboard-fe/pull/46
