### ISSUE TITLE
Link to no longer maintain Product Outline template

### ISSUE THREAD

**Issue by yurenanava** [department-of-veterans-affairs/va.gov-team#62433]
### Description

In this page https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/collaboration-cycle-kickoff the Product Outline link in the Kickoff artifacts section takes to a no longer maintain template

### Relevant URLs

https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/collaboration-cycle-kickoff

### Which type of team are you on? (Platform team, VFS team, or Leadership)
Other

**Comment by laucon** [comment]
Thank you for pointing this out to our team. We will look into it and try and fix it ASAP.

**Comment by BSmolensky** [comment]
This issue was resolved on 7/24/23. Contacted Cheryl Evans. She provided the correct link. New link (and hyperlink text) was added to the page. The page was deployed that afternoon.
