### ISSUE TITLE
Investigate usage of mhv_account_type on the User model

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#62430]
Mobile team asked us a question about the usage of the `mhv_account_type` field on the user model. We need to investigate the behavior of this field for Sign in Service authentications that occur with:
* A user who has an MHV account and authenticates with an MHV account
* A user who has an MHV account and authenticates with a different credential (id.me, login.gov, dslogon)

Also, need to compare this behavior with the same cases in SSOe authentications.

Finally, we need to be confident of how this field is sourced, both for SSOe and Sign in Service

Slack convo here: https://dsva.slack.com/archives/CSFV4QTKN/p1689959585422909?thread_ts=1689608324.102329&cid=CSFV4QTKN

**Comment by bosawt** [comment]
It looks like we successfully return `Premium` as a result for `mhv_account_type` when a veteran has previously authenticated with MHV. This `Premium` is returned regardless of the credential the veteran is currently using. Additionally, this works for both SSOe and Sign in Service.

If a user hits certain criteria, they are automatically upgraded to MHV `Premium`, but this only occurs on the myhealthevet site. So a verified ID.me user who has never authenticated with MHV will have `nil` for `mhv_account_type`, even if they would be auto upgraded on MyHealtheVet

**Comment by aparsley** [comment]
Thank you, keep up the good work!
