### ISSUE TITLE
Github ticket #62433

### ISSUE THREAD

**Issue by laucon** [department-of-veterans-affairs/va.gov-team#62449]
We need to fix the link in [Collaboration cycle kickoff](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/collaboration-cycle-kickoff)

https://github.com/department-of-veterans-affairs/va.gov-team/issues/62433

**Comment by BSmolensky** [comment]
This issue was resolved on 7/24/23. Contacted Cheryl Evans. She provided the correct link. New link (and hyperlink text) was added to the page. The page was deployed that afternoon.
