### ISSUE TITLE
Profile 2.0 Screen Copy - Direct Deposit

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#6245]
reference Epic #6238

# Task
- [ ] Add copy for the Direct Deposit screen

**Comment by tressaellen** [comment]
Sections that need to be reviewed have been outlined in red.

![Direct Deposit 1.jpg](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/f114b7b4-6c71-43de-8814-9ee53f4b1123)![Direct Deposit 5.jpg](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/0c331a12-fbd9-4116-81f7-e0636abfebdf)

**Comment by tressaellen** [comment]
@peggygannon I've dropped screens in here for review, as well as issue #6246 and #6247 in case you'd like to look things over before our meeting on Monday.  The sections that need to be reviewed have been outlined in red.  Thank you!

**Comment by peggygannon** [comment]
Hello @tressa 

please see below content recommendations for the Direct deposit screen:

first screenshot: 
Update copy in box to: View your payment history

---
 
second screenshot
Update copy to: Your direct deposit information has been saved. 
(no exclamation point)
