### ISSUE TITLE
Spike: Investigate usage of Terms and Conditions service

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#62450]
We have a need to integrate with a backend Terms and Conditions service (confusingly, called the 'Sign Up Service', no relation to 'Sign In Service'), and we need to investigate the service and confirm it has the behavior we need for a new Terms and Conditions effort:

- I should be able to create an association between a User's ICN and a Terms and Condition template/version
- I should be able to query the service with a User's ICN and confirm whether they have accepted a Terms and Conditions template/version
- I should be able to create an association between a User's ICN and a Terms and Condition template/version denial
- I should be able to query the service with a User's ICN and confirm whether they have denied a Terms and Conditions template/version
- I should be able to correlate a Terms and Conditions template/version with the actual text in a display Terms and Conditions page

**Comment by bosawt** [comment]
[https://app.zenhub.com/files/133843125/c355cda3-0c51-4a49-8581-9d886a5f323a/download](https://app.zenhub.com/files/133843125/c355cda3-0c51-4a49-8581-9d886a5f323a/download)

**Comment by achievedaniel** [comment]
End point for the terms and conditions: `https://veteran.apps.va.gov/signup/v1/terms-and-conditions`
There is no security with this end point

Sample of the response: 
{
    "name": "Universal VA Terms and Conditions",
    "content": {text of the Universal VA Terms and Conditions}
    "createDate": "2023-05-31T10:55:11.409509Z",
    "lastModifiedDate": "2023-05-31T10:55:11.409509Z",
    "version": 2,
    "bypassNumOfDays": 180,
    "isWithinBypassPeriod": true,
    "lastDayOfBypassPeriod": "11/26/2023"
}

**Comment by achievedaniel** [comment]
Endpoint to check if an user has accepted the agreement: `https://veteran.apps.va.gov/signup/v1/patients/{icn}/status/summary`
There is no security with this end point

Sample of the response:
```
{
    "agreementSigned": false,
    "optOut": false,
    "cernerProvisioned": false
}
```

**Comment by bosawt** [comment]
Some info on how to create a token to call routes that require authentication:
- We need a token to call these services, which is generated through these endpoints:
```
The full URLs for the Mobile OAuth STS endpoints that you will need to use are

SQA - https://veteran.apps-staging.va.gov/sts/oauth/v1/token
PROD - https://veteran.apps.va.gov/sts/oauth/v1/token
```
And this document describes how to create a JWT to call these services and request a token: [https://app.zenhub.com/files/133843125/071dae9e-5674-4b51-a5a0-076ab66ad58c/download](https://app.zenhub.com/files/133843125/071dae9e-5674-4b51-a5a0-076ab66ad58c/download)

**Comment by bosawt** [comment]
Finally, they gave us client ids that we use in the client id field for those JWT:
```
For the "localhost" cert you provided, the associated client id is:  afa37e9ab0cf
For the "lowers" cert you provided, the associated client id is:  c7d6e0fc9a39
```

**Comment by bosawt** [comment]
[https://app.zenhub.com/files/133843125/b1bdbb5a-1d39-4fb6-b64a-eca69e1c0b49/download](https://app.zenhub.com/files/133843125/b1bdbb5a-1d39-4fb6-b64a-eca69e1c0b49/download)

**Comment by bosawt** [comment]
They gave us an 'updated' doc on how to create the JWT
