### ISSUE TITLE
Profile 2.0 Screen Copy - Account

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#6246]
## Tasks

- [x] Create copy for the "Account" screen

**Comment by tressaellen** [comment]
Sections that need to be reviewed have been outlined in red.

![Account 1.jpg](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/07c6124b-f1f8-4120-9923-3ea9b2ee00e2)![Account Disconnect.jpg](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/514a1c26-c2e3-4b62-8471-5b07d966be36)

**Comment by peggygannon** [comment]
@tressaellen as discussed, I'll hold off on the content for Connected Accounts until we have information on design direction. 

My recommendation for the header and left nav is: Account
(removing your).

 I'm working with Mikki on reviewing VA.gov site/pages where we use "your".  We're trying to establish a pattern/style when to do so. For these profile 2.0 screens, I recommend we remove "your" from the pages and keep "your" when referring to Your profile.

**Comment by tressaellen** [comment]
Closing as content for 'connected apps' is now being tracked in #6748
