### ISSUE TITLE
Add past rates for VET TEC page & publish current rates page-HOLD TO PUBLISH UNTIL  8/1/23

### ISSUE THREAD

**Issue by megzehn** [department-of-veterans-affairs/va.gov-team#62462]
Once the new VET TEC rates go into effect, we need to publish the current rates page and update the past rates page. 

- [x] Clone current page and update current rates (Katherine)
- [x] Update past rates page (Katherine)
- [x] Review (Megan) 
- [x] Pre-pub and publish on August 1, 2023 (Megan)

**Comment by laurwill** [comment]
This page is live! Closing out — @katherine-fung @megzehn can you track capacity for this one? Thank you!
