### ISSUE TITLE
Publish past rates for TOE and update current rates - HOLD TO PUBLISH AUGUST 1, 2023

### ISSUE THREAD

**Issue by megzehn** [department-of-veterans-affairs/va.gov-team#62463]
Once the new TOE rates go into effect, we need to publish the current rates page and update the past rates page. 

- [x] Clone current page and update current rates (Katherine)
- [x] Update past rates page (Katherine)
- [x] Review (Megan) 
- [x] Pre-pub and publish on August 1, 2023 (Megan)

**Comment by katherine-fung** [comment]
Hi @megzehn, 

Here's the TOE rates page that I updated to be the past rates page: 
http://preview-prod.vfs.va.gov/preview?nodeId=51816 

I cloned the past rates page to create the new current rates page, and updated it with the current rates: 
http://preview-prod.vfs.va.gov/preview?nodeId=59416 

(Here are the 2023-2024 year rates for the new current rates page for August 1, 2023: 
[https://app.zenhub.com/files/133843125/c3f0cb80-00ca-436b-8855-a1ed8299f5e8/download](https://app.zenhub.com/files/133843125/c3f0cb80-00ca-436b-8855-a1ed8299f5e8/download)

**Comment by megzehn** [comment]
Thank you, @katherine-fung for getting these all ready!! Confirming that I verified the URL with the IA team, and these are now live.
