### ISSUE TITLE
Profile 2.0 Screen Copy - Personal and contact information

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#6247]
## Tasks

- [ ] Create Copy for "Personal and contact information"

**Comment by tressaellen** [comment]
Sections that need to be reviewed have been outlined in red.

![Contact 1 Checkbox.jpg](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/14d678a5-df02-4dff-bf40-c0382c28734f)![Contact Edit Mailing 4.jpg](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/c8297ae0-2b64-4a1b-bba3-42d23a69ad21)

**Comment by peggygannon** [comment]
Hello, @tressaellen, here are recommendations for this screen: 
 
Personal and contact information screen

1. Make Profile: Your profile

2. Update save message to: We’ve saved your mailing address. 

3. for the email section, I wanted to see if we can add links off to the different accounts. also please let me know if my updated copy reflects what the user experience will be? Let me know any feedback you have!

**How do I update the email address I use to sign in to VA.gov?** 

To update the email address you use to sign in, go to the account where you manage your settings and identity information. Any email updates you make there will automatically update on VA.gov. 

{link} Update email address on ID.me(link to ID.me)
{link} Update email address on MyHealtheVet(link to MHV)
{link} Update email address on DS Logon(link to DS Logon)

**Comment by tressaellen** [comment]
This is super helpful - thanks @peggygannon !

**Comment by tressaellen** [comment]
Clarification update from Peggy:

breadcrumb and side nav- Profile
dark blue banner at top (with the user name/details)- Your profile
light blue drop down- Profile menu
