### ISSUE TITLE
[Team] Discovery: Determine what we need for EZR online to be PRA/OMB compliant (BLOCKED--needs updating)

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#62473]
As a team member, I would like to understand what we need to do to be PRA/OMB compliant for Financial Information editable online so that I make sure we follow the law and don't get out stuff taken down.

- [ ] Look at how this team handles PRA statements (and any other relavent type of disclosure) in the EZ and CG
- [ ] Talk to PRA folks again (meeting 7/28)
- [ ] Review the [disclosure library ](https://design.va.gov/components/omb-info)
- [ ] Suggestion: Reach out to Forms team (Jeanna Clark and Pat Siebenlist) 
- [ ] Review VHA Directive 6309 (Patrick has done this, I don't think we need to do it more)
- [ ] Discuss with Patrick what is required (and see his note pasted below)
- [ ] Come up with list of things we will need to display and/or link to
- [ ] **Success: We know what we need to display/link to/develop in order to be compliant with PRA and OMB guidelines**

**AS Note: There will be separate stories to design for and implement this.**

https://design.va.gov/components/omb-info

[From Patrick](https://dsva.slack.com/archives/CMJ2V70UV/p1690225305935309?thread_ts=1690219959.853419&cid=CMJ2V70UV), we will likely need to include: 

- Form number: 10-10EZR
- Control number: 2900-0091
- Estimated burden: 24 min
- Expiration date: 06/30/2024
- PRA statement: The Paperwork Reduction Act of 1995 requires us to notify you that this information collection is in accordance with the clearance requirements of Section 3507 of the Paperwork Reduction Act of 1995. We may not conduct or sponsor, and you are not required to respond to, a collection of information unless it displays a valid OMB number. We anticipate that the time expended by all individuals who must complete this form will average 15 minutes. This includes the time it will take to read instructions, gather the necessary facts and fill out the form.
- Privacy Act Information: VA is asking you to provide the information on this form under 38 U.S.C. Sections 1710, 1712, and 1722 in order for VA to determine your eligibility for medical benefits. Information you supply may be verified from initial submission forward through a computer matching program. VA may disclose the information that you put on the form as permitted by law. VA may make a “routine use” disclosure of the information as outlined in the Privacy Act systems of records notices and in accordance with the Notice of Privacy Practices. Providing the requested information is voluntary, but if any or all of the requested information is not provided, it may delay or result in denial of your request for health care benefits. Failure to furnish the information will not have any effect on any other benefits to which you may be entitled. If you provide VA your Social Security Number, VA will use it to administer your VA benefits. VA may also use this information to identify veterans and persons claiming or receiving VA benefits and their records, and for other purposes authorized or required by law.

**Comment by longmd** [comment]
@alexseelig , I think you can close this. We have all this info as part of the intro page, and it is already implemented as part of the shell build-out.

**Comment by hdjustice** [comment]
Closing ticket
