### ISSUE TITLE
SOCKS access for [Luke Short]

### ISSUE THREAD

**Issue by lukey-luke** [department-of-veterans-affairs/va.gov-team#62488]
### Your Name

Luke Short

### Your Email

luke@verdance.co

### Your Role and Team

Software Engineer on Contention Classification

### Product Manager (PM) name and email

Yurena Garcia - yurenagarcia@navapbc.com

### Product Owner (PO) name and email

Emily Theis - emily.theis@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDGpcIpUZOlOYJA0TDkgK4y1fyA+UFKN58qmjhsxmz/448rDTUBqxBep1BLoBdhDBspvKC0xLMLFrXbzW3NBJCzN3Bmk0i74RSQzG180CgRt6kpLyHyGE7CxoSL5gEiHE9MAnR+Byd2oLDVrPyzyYCdfHcN8TNSHzi/xxVxELToJGtMVE4GKA5eY2GSTs+av6urMmiZTbPGkyR7d1wP9uE5BpN+iyWdYKpeQfmWgh6PIZI8VwlPxnWYwPXkXfX3kyhrIFi/Afum3T0/y2EmyCHs0F5axK10hiP6YHAnt0nUVDAjV//wnG940Q5D48nHAD0z0wJSUNoi2wG8F3ByMtoJiWwc+X9pYql/F6nJlC7899O215oBheuOn4UR2JPdDAefCWkteRk5DUzQVw196qBmeEdwkApKb2uggEYgLipWiiTzhwrHiPhhiEx3XSzuyT+Q3mdtalSIoeN1xRMF+l7KA20xeg2qNBngWH6Mlbsoi734pPpT0i4IdpCH1UZk+hs= verdanceluke@Verdances-MacBook-Pro.local

### E-QIP Transmittal Confirmation

![eqip_transmittal](https://github.com/department-of-veterans-affairs/va.gov-team/assets/17188013/ba36aa2a-700f-45f2-8459-a8344fe6bff3)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by lukey-luke** [comment]
This is the third time I've submitted request for socks access as I had to go to Apple (again) and get my computer replaced on Friday (7/21/23).

**Comment by lukey-luke** [comment]
Previously submitted SOCKS requests [HERE](https://github.com/department-of-veterans-affairs/va.gov-team/issues/61819) and [HERE](https://github.com/department-of-veterans-affairs/va.gov-team/issues/55038).

**Comment by flooose** [comment]
Your socks connection should work shortly.
