### ISSUE TITLE
Configure Closed Testing of Sentry/Slack Integration

### ISSUE THREAD

**Issue by gia-lexa** [department-of-veterans-affairs/va.gov-team#62490]
## Description

An implementation plan for a Slack-Sentry integration was approved in this recent [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/61589#event-9853710514). 
As a requirement of that plan moving forward, first a closed test of the  proposed configuration needs to be enabled and run for 1-2 weeks. 

## Acceptance Criteria
- [x] Implement the closed test as [described in the previous ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/61589#issuecomment-1636011360)
- [ ]  Keep the test running for 1-2 weeks, monitoring regularly to identify any issues.
---

**Comment by pjhill** [comment]
This ticket was bumped to a lower priority below other high priority support issues that popped up over the past two weeks.

Hector is planning to be able to address this ticket further on Monday 8/21/2023.

**Comment by npeterson54** [comment]
More difficult than expected, changing to an 8

**Comment by hgbarreto** [comment]
The webhook works - taking time to format the messages correctly

**Comment by hgbarreto** [comment]
I plan to split this one ticket into 2 tickets:
1. Implementation ticket - completed this sprint
2. formatting the message - to be completed next sprint

**Comment by hgbarreto** [comment]
Closing this issue as "Research and Implentation" complete. Referenced issue above will complete the message formatting portion.
