### ISSUE TITLE
[FE] My VA UX audit improvements: missing Outstanding Debts and Benefit payments sections when user has no debts

### ISSUE THREAD

**Issue by allisonlu** [department-of-veterans-affairs/va.gov-team#62492]
## Background
One of the findings of the UX audit is that all LOA3 users (whether veteran or not) should see **all** sections of My VA, even if it is an empty state.

Currently on prod, a user with no debts will not see Outstanding debts section, and a user with no benefit payments won't see the Benefit payments section. 

I think this is the line of code that is causing the issue:

https://github.com/department-of-veterans-affairs/vets-website/blob/95b3214eaa694fdf082914c3f5bc24a36a14ee6a/src/applications/personalization/dashboard/components/Dashboard.jsx#L244

Essentially, the logic currently checks if the user is LOA3 (which is true), the show v2 dashboard feature flag is on (also true), and if we can access the payment history (which is undefined for those with no debts).

I see intended behavior for the section when I remove the last check locally. I think it's safe to push a change to remove this check because we have error handling at the component level.

**Comment by allisonlu** [comment]
@Samara-Strauss @aagosto90 

I logged in with my prod account and see both the Outstanding debts and Benefit payments sections (empty states). Can you help validate too?

**Comment by aagosto90** [comment]
I see them in my prod account too. Thanks again for taking action on this so quickly @allisonlu !

**Comment by Samara-Strauss** [comment]
I'm now seeing the blank states for outstanding debts and benefit payments. Thank you!

I am getting an error for health appointments (I don't have any), and I am not sure whether that is totally unrelated to this update or not. I wanted to flag it just in case this update could have introduced a problem. Otherwise, I'll assume it's an unrelated backend issue.

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/34068740/25448539-0f65-4a1d-96ac-f7a19be37c5d)

**Comment by aagosto90** [comment]
FWIW I see an empty health care section as expected in my prod account; no errors.
<img width="502" alt="Screenshot 2023-07-26 at 12 06 32 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/97965610/06c34a1d-d2bb-4815-a91c-a66c5150a0e6">

**Comment by Samara-Strauss** [comment]
I'm no longer seeing the health care error, so we are good to go! Looks like that was completely unrelated.

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/34068740/e40766b1-9804-44aa-b6f4-8cbe4e598678)

**Comment by ajakabcin** [comment]
Looks great - confirmed I'm seeing debts and payments sections in my prod account as well. Thanks for tackling this so quickly @allisonlu !
