### ISSUE TITLE
[KEYBOARD]: Let's make the Schedule an appointment just a button and not wrap it in a link

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#6250]
## Description

Our `Schedule an appointment` is a button wrapped in a link. I'd like to standardize this as a button if we can, to match our form's Back | Continue buttons, or a link styled as a button if we need the route. This is causing an unusual "double tab stop" in Firefox, and could be confusing to screen reader and keyboard users. Screenshot attached.

## Point of Contact

**VFS Point of Contact:** _Trevor_

## Acceptance Criteria

* [ ] As a keyboard user, I want to press `TAB` just one time to move focus away from the Schedule an appointment button

## Environment

* Windows 10
* Firefox
* https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/

## WCAG or Vendor Guidance (optional)

* [Parsing: Understanding SC 4.1.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/ensure-compat-parses.html)

## Screenshots or Trace Logs

![Screen Shot 2020-02-26 at 3 46 48 PM](https://user-images.githubusercontent.com/934879/75391695-3252d880-58b0-11ea-919a-8f5fb4f7f191.png)

**Comment by jbalboni** [comment]
Ha, that's weird. I think it would need to be a link, since the real action is move to the new appointment page.
