### ISSUE TITLE
Create 11 x 17 Poster Size

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#62518]
## Background
The Poster pilot sites would like to be able to display the poster on a TV monitor. As a result, they need to have an 11 x 17-sized version of the poster.

## Tasks
- Create an 11 x 17-sized poster version
- Create a jpg version of the 11 x 17-sized poster
- Publish the poster and jpg to GitHub

**Comment by loripusey** [comment]
@zach-park can you make sure we get this one in before the end of the sprint? thanks.

**Comment by zach-park** [comment]
> @zach-park can you make sure we get this one in before the end of the sprint? thanks.

Yes, of course!

**Comment by loripusey** [comment]
Looks good

**Comment by zach-park** [comment]
@kellysmith1008 , FYI!

**Comment by benbrasso-agile6** [comment]
@zach-park  Content should be this version - https://www.sketch.com/s/9798426e-bba3-46dd-9d87-73d77dcf6599/a/qbVYwk5

This group was the one that wanted the extra information about "You're checked in." 

No need for tagalog version on this one. 

But, design looks good. Don't forget, they requested jpg format. I would give them both color options.

**Comment by zach-park** [comment]
@benbrasso-agile6 , @loripusey , and @kellysmith1008 , the content is updated. The posters are uploaded on the GitHub page: 
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/design/visual-collateral/README.md
