### ISSUE TITLE
Schedule Design-Development Intent Checkpoint

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#6252]
## Backgroud
(https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/vsa-accessibility-review-process.md)

This review happens as the design is passed to development, before beginning development. The accessibility specialist(s) will review the design with the developer(s) to:

a. Discuss approach to take with development, for WCAG compliance

b. Identify what components and semantic HTML would be appropriate

c. Identify any accessibility issues and how to address

## Tasks
- [ ] [Schedule Design-Development Review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=1Copenut%2C+jenstrickland&labels=508%2FAccessibility%2C+development+review%2C+product+support&template=request_dev_review_vsa.md&title=Request+development+review+for+ENTER_PRODUCT_NAME)

**Comment by Samara-Strauss** [comment]
Removing myself from this ticket. I don't need to be part of this conversation, but I hope it goes well!
