### ISSUE TITLE
[Helm] Private repo is throwing a 404

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#62529]
## Description
- When using private helm chart repo we are getting a 404
- Suspect it's related to authentication

## Resources 
- Artifacts - i.e., issues, documentation, code, etc. - that help explain what's needed to work on this issue

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this issue?_

## Refinement Guidance - Check the following before working on this issue: 
- [x] _Team label assigned ("platform-tech-team-2")_
- [ ] _Epic assigned (if needed)_ 
- [x] _Estimated (points assigned)_
- [x] _Sprint assigned (once planned)_
- [x] _Team member(s) assigned_

**Comment by hgbarreto** [comment]
Despite [chart-releaser having the update]( https://github.com/helm/chart-releaser#usage-with-a-private-repository) that fixes our problem, the [chart-releaser-action] (https://github.com/helm/chart-releaser-action) has yet to implement it.
