### ISSUE TITLE
[DE] Profile 2.0: VSP Usability Testing Design Review

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#6253]
[Fill this out to submit VSP Usability Testing Review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=andreahewitt-odd%2C+meganhkelley&labels=product+support%2C+content-ia-team&template=usability-testing-prep.md&title=Pre-Usability+Review+%5BFeature-Name%5D)

## Steps to complete Usability Testing Prep: 
- [x] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in #vfs-platform-support in Slack; tag @ Megan Kelley @ AndreaHewitt
- [x] Andrea and Megan to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [x] At least 2 days before scheduled meeting, you must complete list of artifacts below
- [x] VSP <> **requesting team** review meeting completed
- [ ] Practice area reviewers create sub-issues attached to this one with feedback for your team on *feature name*
- [x] **Requesting team** completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)
- [x] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Additional Notes: 
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, QA, and optional: information architecture (IA), product

**Comment by Samara-Strauss** [comment]
I don't need to be part of this, but hope it goes well!

**Comment by Samara-Strauss** [comment]
I noticed I was assigned again and IDK if that was intentional or a glitch or not, but I've gone ahead and unassigned myself. This is on your plates to figure out/schedule/manage. Hope it goes well!

**Comment by mshea0606** [comment]
@tressaellen @Samara-Strauss  Moving this back to account for design changes (edit-in-place vs modal)

**Comment by Samara-Strauss** [comment]
Sounds good! I went ahead and cleared the milestone.
