### ISSUE TITLE
Redirect the existing URLs to the new URLs for MHV on VA.gov - Status List

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#62549]
## Description
We will need to re-direct the Veteran to the new URLs for Appointments on MHV on VA.gov. 

---

### Status list   

- [x] Given the user is authenticated on MHV on VA.gov 
       When the user is on the Appointments landing page (view upcoming appointments) and the existing URL is https://va.gov/health-care/schedule-view-va-appointments/appointments
       Then the user will be re-directed to the new URL for MHV on VA.gov https://va.gov/my-health/appointments
       And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/homepage.md#homepage-copy-doc) 

- [x] Given the user is authenticated on MHV on VA.gov 
       When the user is on the Pending list page and the existing URL is https://va.gov/health-care/schedule-view-va-appointments/appointments/pending
       Then the user will be re-directed to the new URL for MHV on VA.gov https://va.gov/my-health/appointments/pending
       And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/homepage.md#pending-appointments) 
 
- [x] Given the user is authenticated on MHV on VA.gov 
       When the user is on the Past list page and the existing URL is https://va.gov/health-care/schedule-view-va-appointments/appointments/past
       Then the user will be re-directed to the new URL for MHV on VA.gov https://va.gov/my-health/appointments/past
       And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/homepage.md#past-appointments) 

### Design Assets
[Copy doc - Homepage/Status list](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/homepage.md)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by ldelacosta** [comment]
Please let us know if any work is required for this ticket (working tickets: #59753, #60752 and #60755). If no work is needed, we can use this ticket as a checklist to verify it works as expected. cc: @JRRoof

**Comment by ldelacosta** [comment]
@young1205 - please have the UX team validate this ticket when it's ready cc: @JRRoof @outerpress

**Comment by JRRoof** [comment]
Redirects added in production October 4, 3023.
