### ISSUE TITLE
Vets-api terminal access for Zack Youngren

### ISSUE THREAD

**Issue by zack** [department-of-veterans-affairs/va.gov-team#62558]
### Your Name

Zachary (Zack) Youngren

### Your GitHub handle (terminal access is managed through GitHub)

@zack

### Team, Role, and Company of the target individual

Team Dependents Experience, Senior Software Engineer, Coforma

### Product Manager (PM) name and email

Laura Steele: <laura.steele@coforma.io>

### Product Owner (PO) name and email

Matt Self: <matthew.self2@va.gov>

### COR Name (leave "None" if you listed an AWS user name above)

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

Other - please specify in 'Additional Notes'

### Please confirm if you are on the VFS Team Roster or Platform Team Roster

- [X] [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Please confirm E-QIP Transmittal/Adjudication. This could be a screenshot of your Transmittal/Adjudication email, a link to another request where you've submitted this proof (i.e. AWS/SOCKS), etc.

- [X] I have attached proof that I have either transmitted my E-QIP survey or previously received a favorable decision (by including in "Additional Notes" section below)

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### Additional Notes

COR: Jennifer O'Day
VOR: Jeff Langworthy [jeff.langworthy@coforma.io](mailto:jeff.langworthy@coforma.io)

Production justification: Investigating ongoing issues with 21-686c forms being incorrectly redirected after submission over the next 3 months. After that we should have a more permanent monitoring solution set up.

#### E-QIP Transmittal Confirmation

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/2482403/dd2f005a-2d58-497d-802b-fb9ecb0de217)

Thanks!

### Additional resources for Support Engineer

- [ ] For users on a VFS team but not in the VFS Team Roster, they must start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] Instructions for handling requests [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access) - Support Only

**Comment by bdech** [comment]
Found in VFS Team Roster

**Comment by bdech** [comment]
@zack You've been granted access to the `dev`, `staging`, and `sandbox` environments.

Here's some additional documentation for the [Vets API on EKS](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-TerminalAccess)

Access to `prod` is pending approval by OCTODE, and we'll update you as soon as it's available.

**Comment by BillChapmanUSDS** [comment]
Access approved as per current policy

**Comment by bdech** [comment]
slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1691502719692189)

**Comment by bdech** [comment]
@zack  Your Vets API Terminal Production access has expired.

Would you like to request an extension? You have 72 hours to respond, or your 
access will be revoked and you will need to fill out a new request.

**Comment by bdech** [comment]
No response, production access revoked.
