### ISSUE TITLE
Redirect the existing URLs to the new URLs for MHV on VA.gov - VA Request

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#62579]
## Description
We will need to re-direct the Veteran to the new URLs for Appointments on MHV on VA.gov. 

---

### Request

- [ ] Given the user is on the schedule workflow (VA request) 
       When the user is on the `Preferred date` page and the existing URL is https://va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/request-date
       Then the user will be re-directed to the new URL for MHV on VA.gov https://va.gov/my-health/appointments/schedule/va-request
       And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/request-va.md#preferred-date) 

- [x] Given the user is on the schedule workflow (VA request) 
       When the user is on the `Reason for appointment `page and the existing URL is https://va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/reason-appointment
       Then the user will be re-directed to the new URL for MHV on VA.gov https://va.gov/my-health/appointments/schedule/va-request/reason
       And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/request-va.md#reason-for-appointment) 

- [x] Given the user is on the schedule workflow (VA request) 
       When the user is on the `Preferred modality` page and the existing URL is https://va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/choose-visit-type
       Then the user will be re-directed to the new URL for MHV on VA.gov https://va.gov/my-health/appointments/schedule/va-request/preferred-method
       And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/request-va.md#preferred-modality) 

- [x] Given the user is on the schedule workflow (VA request) 
       When the user is on the `Contact information` page and the existing URL is https://va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/contact-info
       Then the user will be re-directed to the new URL for MHV on VA.gov https://va.gov/my-health/appointments/schedule/va-request/contact-information
       And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/request-va.md#contact-information) 

- [x] Given the user is on the schedule workflow (VA request) 
       When the user is on the `Review details` page and the existing URL is https://va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/review
       Then the user will be re-directed to the new URL for MHV on VA.gov https://va.gov/my-health/appointments/schedule/va-request/review
       And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/request-va.md#review-appointment-details) 

### Design Assets
[Copy doc - VA request workflow](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/request-va.md) 

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by ldelacosta** [comment]
Please let us know if any work is required for this ticket (working ticket #61287). If no work is needed, we can use this ticket as a checklist to verify it works as expected. cc: @JRRoof

**Comment by ldelacosta** [comment]
@young1205 - please have the UX team validate this ticket when it's ready cc: @JRRoof @outerpress

**Comment by simiadebowale** [comment]
set up a general redirect for: https://va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/ to: /my-health/appointments/schedule/type-of-care

**Comment by JRRoof** [comment]
Redirects added in production October 4, 3023.
