### ISSUE TITLE
Analytics Implementation for [Disability Experience - 526 Flow]

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#62575]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

</div>
</details>

### Required
- **Is this request for **Google Analytics implementation** or **QA**?**

     - [x] Google Analytics implementation
     - [ ] QA

- **Who is this request for?**

    - This request will support all current and future Disability Experience (DBEx) teams working on the 526 ez form. Specifically this will be very useful for UX and product teams to make smarter hypotheses and validate outcomes.
    
    
- **Provide the link(s) for Google Analytics implementation or QA**
  
    - Due to the large number of links I have atteached a spreadsheet link: https://docs.google.com/spreadsheets/d/1Bi65N54v2yKCFFR42aStk3SGHBXlHDOCNbchKHb8ddg/edit#gid=0
    - General information for spreadsheet:
      - The spreadsheet contains all possible URLs contained with in the 526
      - The first two tabs represent all currently live URLs, while the third tab represents some URLs existing in stageing but not available in production. 
      - Each URL contains a number of columns not currently relevant for analytics
      - Each URL is grouped in chapters, however, this is also will not be relevant for this request
    
- **When is the launch date?**
    - 526 ez is currently in production. This request is focused on updating funnels to match past changes and get more granular data.

- **What interactions need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked_
    
    - [If this is a funnel, insert each step's URL - pages visible depending on the applicant's answers should be marked accordingly]
    - See spreadsheet link listed above for each URL. 
      - We would like both the Completion Rate Funnel and the Exit Rate Funnel to be update to include every URL listed in Tab 1 and Tab 2. 
      - Most important is the tables that include the URL, Percentage, and total number
      - While it could be nice to include grouping at the Chapter level listed in the spreadsheet, we dont want to add uneeded complexity
      - From an ordering perspective, we would like the URLs in the PTSD tab to follow as a continuation of the Disabilities section in tab 1. 
    
    - [Insert other interactions - please review the [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) and [GA Data Dictionary](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Google-Analytics-Data-Dictionary.1810464912.html)  to make sure these interactions aren't already tracked]
    - No other interactions need to be tracked for now, but we would like to confirm Completion and Exit will be defined as:
      - Completion: in a session, the user landed on that URL and then successfully navigated to a following URL
      - Exit: In a session, the user landed on that URL and then ended their session on that URL 

### Optional
- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - [Insert test user]

- **Any additional comments**

    - [Insert comments]

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by michelle-dooley** [comment]
@austinjprice - thank you for your submission.  I will review with team and get back to you with timing.

**Comment by michelle-dooley** [comment]
@austinjprice - this is the current [form funnel](https://docs.google.com/spreadsheets/d/1gRmJqZvzRKSgoz8BzAxULRfRHegVrAOV6ciZU3fVWq0/edit#gid=0) in use today.  Can you please create a similar table that combines all the new urls listed in the various tabs into one worksheet so we ensure we get everything set up as you want it to be in the V2 version of the funnel that will be used in Domo.

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/93597659/aa0eb8f9-5412-4e3d-afee-e22e20d0a97c)

**Comment by austinjprice** [comment]
hey @michelle-dooley sorry missed this. I have a link in the "Provide the link(s) for Google Analytics implementation or QA" section with all of the URLs. Are you able to access that document?

**Comment by austinjprice** [comment]
Or are you jus asking that I consolidate into one tab?

**Comment by austinjprice** [comment]
@michelle-dooley gotcha, on it!

**Comment by michelle-dooley** [comment]
Hey @austinjprice - just following up on this, when you do you think you will be able to complete? Just trying to get idea of timing for our sprint planning. Thanks!!

**Comment by austinjprice** [comment]
hey @michelle-dooley, I created a new tab in the sheets doc linked above called funnel. I listed out each URL and numbered them. It took me a bit of time to clarify the naming and order, so totally understand the confusion. We are essentially moving away from looking at chapters for the funnel and want to see each individual listed out one by one both for the Completion Funnel and the Exit Funnel. Let me know if you have any questions!

**Comment by michelle-dooley** [comment]
And step 18 should the * be at the end of ptsd*?

**Comment by michelle-dooley** [comment]
Sprint update:  data has been loaded and we are testing.  Should complete in next sprint.

**Comment by austinjprice** [comment]
Thank you!

**Comment by michelle-dooley** [comment]
@austinjprice - this work has been completed.  You can see V2 of this form starts on 8/13, any data prior to that date will be based on the original V1 funnel. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaEpGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e96cc80752ad78a166e2525e897fdfbe4495b900/image.png)

**Comment by austinjprice** [comment]
thanks @michelle-dooley! Great progress! I have some questions on the data but will post in the Analytics channel and join the office hours. Thanks again
