### ISSUE TITLE
Integrate MPI with isolated Services

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#62574]
Test what is necessary to integrate MPI access with Sign in Service or Identity Dashboard

**Comment by bosawt** [comment]
The referenced issue or this branch on the identity dashboard: `62574_mpi_integration`, show the MPI test integration. We may want to connect with MPI in a different way for identity dashboard, so I don't want to check this in yet. But the concept is there and ready for use either in identity dashboard, or in Sign in Service isolated

**Comment by aparsley** [comment]
Keep up the good work!
