### ISSUE TITLE
GIDS: Crosswalk issue OPE in Action column for IPEDS table

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#6257]
Navigate to https://staging.va.gov/gids/crosswalk_issues/partials/38338

Observe the OPE value in the Action column

![Screen Shot 2020-02-27 at 7.57.54 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/348f5294-1bb9-440f-878b-32b84e5e3dcd)

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/586

Can be tested on gibct-data-service branch `crosswalk-resolution`

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-02-28 at 7.43.34 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/76564055-3f26-4de5-890a-582636a4975a)

**Comment by sonntag-adam** [comment]
In staging, closing bug.
