### ISSUE TITLE
Landing Page Appointment Reminder Notification - UX Design

### ISSUE THREAD

**Issue by A6-toma** [department-of-veterans-affairs/va.gov-team#62584]
## User Story
As a VA.gov user, I want to see an indicator on VA.gov reminding me about upcoming appointments so that I can quickly get the information and follow the notification to additional details about my appointment if I need them.

As a cartography team member, I want to design a notification for appointment reminders that is clear, helpful, and makes sense, and aligns with our working [definitions & UX principles about notifications](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/landing-page/notifications/notification_definitions_and_ux_principles.md). 

This ticket is to design a notification for Appointment Reminders. See related ticket #59623 for additional context as needed.

## Related Artifacts
* [Appointment notifications documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/landing-page/notifications/appointments.md)
* Other resources linked in ticket #59623 (evaluation of appointment reminders)

## Tasks
[x] - Consult documented considerations and information about appointment reminders
  * [Slack thread](https://dsva.slack.com/archives/C03CGTDLTFF/p1694009165975579) w/ appointments team about notification start/end timing
[x] - Develop a design concept for appointment reminders
[x] - Determine whether this notification should be duplicated on MyVA page

### Acceptance Criteria
Design considerations for the landing page Appointment Reminder indicator have been documented.

**Comment by sterkenburgsara** [comment]
@A6-toma update: per conversation that @keithcheung828 and I had with appointment team on 8/10/23, Appointment notifications are highly complex with a lot of technical nuance that we will need to tease out. Their team has worked on mapping that out & have a # of resources we can refer to. ([See Slack Thread here](https://dsva.slack.com/archives/C03CGTDLTFF/p1691513531528899)). 

@kristenmcconnell shared that pursuing a notification for the After-Visit Summary (AVS) would be really helpful in the near-term. But the most actionable appointment-related notifications to implement today are: appointment cancellations and appointment reminders.

**Comment by keithcheung828** [comment]
[Github page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/landing-page/notifications/ux-design-evaluation.md) is created to highlight the pros and cons of dot/ card designs

**Comment by sterkenburgsara** [comment]
[UX analysis for this work was completed](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/landing-page/notifications/appointments.md), and after syncing with MyVA team, they already have an onsite notification for upcoming appointment reminders in the works. Their documentation[ is listed here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/use-cases/health-care-use-cases/health-care-appointments.md). 

Appointments team does not surface a notification for this information, but puts it in context in the health section on the MyVA page. They also have logic for when a user a.) does not have VA healthcare and b.) when a user does not have an upcoming appointment. We should move forward with this design in our own way without changing the way that the Auth Experience team surfaces this information with additional context on their page. 

Our running logic is to pattern-match the push notiication timing of the mobile app as much as possible when issuing the dot notification on the My Health landing page. The write-up for this is [detailed here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/landing-page/notifications/appointments.md) under "appointment reminders."

Also issuing a dot on the appointments team pages has not been explored / discussed at this juncture. We have the answer to pursue a dot on the landing page, but whether or not users can follow it to the exact appointments it is referencing without a dot on the follow-up page in the Appointments space is a larger question.
