### ISSUE TITLE
Redirect the existing URLs to the new URLs for MHV on VA.gov - Community Care Request

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#62580]
## Description
We will need to re-direct the Veteran to the new URLs for Appointments on MHV on VA.gov. 

---

### Community Care 

- [ ] Given the user is on the schedule workflow (CC request)  
       When the user is on the `Preferred date `page and the existing URL is https://va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/request-date
       Then the user will be re-directed to the new URL for MHV on VA.gov https://va.gov/my-health/appointments/schedule/community-request
       And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/request-cc.md#preferred-date) 

- [ ] Given the user is on the schedule workflow (CC request)  
       When the user is on the `Closest city `page and the existing URL is https://va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/choose-closest-city
       Then the user will be re-directed to the new URL for MHV on VA.gov https://va.gov/my-health/appointments/schedule/community-request/closest-city
       And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/request-cc.md#nearest-city) 

- [ ] Given the user is on the schedule workflow (CC request)  
       When the user is on the `Request a provider` page and the existing URL is https://va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/community-care-preferences
       Then the user will be re-directed to the new URL for MHV on VA.gov https://va.gov/my-health/appointments/schedule/community-request/preferred-provider
       And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/request-cc.md#request-a-provider-optional) 

- [ ] Given the user is on the schedule workflow (CC request)  
       When the user is on the `Preferred language` page and the existing URL is https://va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/community-care-language
       Then the user will be re-directed to the new URL for MHV on VA.gov https://va.gov/my-health/appointments/schedule/community-request/preferred-language
       And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/request-cc.md#choose-a-language) 

- [ ] Given the user is on the schedule workflow (CC request)  
       When the user is on the `Reason for appointment` page and the existing URL is  https://va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/reason-appointment
       Then the user will be re-directed to the new URL for MHV on VA.gov https://va.gov/my-health/appointments/schedule/community-request/reason
       And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/request-cc.md#reason-for-appointment) 

- [ ] Given the user is on the schedule workflow (CC request)  
       When the user is on the `Contact information` page and the existing URL is https://va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/contact-info
       Then the user will be re-directed to the new URL for MHV on VA.gov https://va.gov/my-health/appointments/schedule/community-request/contact-information
       And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/request-cc.md#contact-information) 

- [ ] Given the user is on the schedule workflow (CC request)  
       When the user is on the `Review details` page and the existing URL is https://va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/review 
       Then the user will be re-directed to the new URL for MHV on VA.gov https://va.gov/my-health/appointments/schedule/community-request/review
       And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/request-cc.md#review-appointment-details) 

### Design Assets
[Copy doc - CC request workflow](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/request-cc.md)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by ldelacosta** [comment]
Please let us know if any work is required for this ticket (working ticket #61291). If no work is needed, we can use this ticket as a checklist to verify it works as expected. cc: @JRRoof

**Comment by ldelacosta** [comment]
@young1205 - please have the UX team validate this ticket when it's ready cc: @JRRoof @outerpress

**Comment by simiadebowale** [comment]
set up a general redirect for: https://va.gov/health-care/schedule-view-va-appointments/appointments/new-appointment/ to: /my-health/appointments/schedule/type-of-care

**Comment by JRRoof** [comment]
Redirects added in production October 4, 3023.
