### ISSUE TITLE
Redirect the existing URLs to the new URLs for MHV on VA.gov - Confirmation Details 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#62582]
## Description
We will need to re-direct the Veteran to the new URLs for Appointments on MHV on VA.gov. 

---

### Confirmation details 

- [ ] Given the user is authenticated on MHV on VA.gov 
       When the user schedules a direct VA appointment and the existing URL is https://va.gov/health-care/schedule-view-va-appointments/appointments/va/[ID]?confirmMsg=true
       Then the user will be re-directed to the new URL for MHV on VA.gov https://va.gov/my-health/appointments/[ID]?confirmMsg=true
       And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/appointment-details.md#va-in-person---confirmed) 

- [ ] Given the user is authenticated on MHV on VA.gov 
       When the user submits a request for a VA appointment and the existing URL is https://va.gov/health-care/schedule-view-va-appointments/appointments/requests/[ID]?confirmMsg=true
       Then the user will be re-directed to the new URL for MHV on VA.gov https://va.gov/my-health/appointments/pending/[ID]?confirmMsg=true
       And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/appointment-details.md#va-request---confirmed) 

- [ ] Given the user is authenticated on MHV on VA.gov 
       When the user submits a request for a Community Care appointment and the existing URL is https://va.gov/health-care/schedule-view-va-appointments/appointments/requests/[ID]?confirmMsg=true
       Then the user will be re-directed to the new URL for MHV on VA.gov https://va.gov/my-health/appointments/pending/[ID]?confirmMsg=true
       And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/appointment-details.md#community-care-requests) 

### Design Assets
[Copy doc - Appointment details page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/appointment-details.md)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by ldelacosta** [comment]
Please let us know if any work is required for this ticket (working ticket #60948). If no work is needed, we can use this ticket as a checklist to verify it works as expected. cc: @JRRoof

**Comment by ldelacosta** [comment]
@young1205 - please have the UX team validate this ticket when it's ready cc: @JRRoof @outerpress

**Comment by simiadebowale** [comment]
No need to set up redirects for these urls
