### ISSUE TITLE
Redirect the existing URLs to the new URLs for MHV on VA.gov - Appointment Details 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#62581]
## Description
We will need to re-direct the Veteran to the new URLs for Appointments on MHV on VA.gov. 

---

### Appointment details (Confirmed/Upcoming) 

- [ ] Given the user is authenticated on MHV on VA.gov 
       When the user is on the Appointments landing page (view upcoming appointments), clicks on `Details` for a VA booked appointment and the existing URL is https://va.gov/health-care/schedule-view-va-appointments/appointments/va/[ID]
       Then the user will be re-directed to the new URL for MHV on VA.gov https://va.gov/my-health/appointments/[ID]
       And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/appointment-details.md#va-in-person---upcoming) 

- [ ] Given the user is authenticated on MHV on VA.gov 
       When the user is on the Appointments landing page (view upcoming appointments), clicks on `Details` for a VA canceled booked appointment and the existing URL is https://va.gov/health-care/schedule-view-va-appointments/appointments/va/[ID]
       Then the user will be re-directed to the new URL for MHV on VA.gov https://va.gov/my-health/appointments/[ID]
       And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/appointment-details.md#va-in-person---canceled) 

- [ ] Given the user is authenticated on MHV on VA.gov 
       When the user is on the Appointments landing page (view upcoming appointments), clicks on `Details` for a Community Care booked appointment and the existing URL is https://va.gov/health-care/schedule-view-va-appointments/appointments/cc/[ID]
       Then the user will be re-directed to the new URL for MHV on VA.gov https://va.gov/my-health/appointments/[ID]
       And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/appointment-details.md#cc-appointment---upcoming) 

- [ ] Given the user is authenticated on MHV on VA.gov 
       When the user is on the Appointments landing page (view upcoming appointments), clicks on `Details` for a Community Care canceled booked appointment and the existing URL is https://va.gov/health-care/schedule-view-va-appointments/appointments/cc/[ID]
       Then the user will be re-directed to the new URL for MHV on VA.gov https://va.gov/my-health/appointments/[ID]
       And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/appointment-details.md#cc-appointment---canceled) 

---
### Appointment details (Pending) 

- [ ] Given the user is authenticated on MHV on VA.gov 
       When the user is on the Pending list page, clicks on `Details` for a pending VA appointment and the existing URL is https://va.gov/health-care/schedule-view-va-appointments/appointments/requests/[ID]
       Then the user will be re-directed to the new URL for MHV on VA.gov https://va.gov/my-health/appointments/pending/[ID]
       And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/appointment-details.md#va-request---pending) 

- [ ] Given the user is authenticated on MHV on VA.gov 
       When the user is on the Pending list page, clicks on `Details` for a pending Community Care appointment and the existing URL is https://va.gov/health-care/schedule-view-va-appointments/appointments/requests/[ID]
       Then the user will be re-directed to the new URL for MHV on VA.gov https://va.gov/my-health/appointments/pending/[ID]
       And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/appointment-details.md#cc-request---pending) 

- [ ] Given the user is authenticated on MHV on VA.gov 
       When the user is on the Pending list page, clicks on `Details` for a canceled pending VA appointment and the existing URL is https://va.gov/health-care/schedule-view-va-appointments/appointments/requests/[ID]
       Then the user will be re-directed to the new URL for MHV on VA.gov https://va.gov/my-health/appointments/pending/[ID]
       And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/appointment-details.md#va-request---canceled) 

- [ ] Given the user is authenticated on MHV on VA.gov 
       When the user is on the Pending list page, clicks on `Details` for a canceled pending Community Care appointment and the existing URL is https://va.gov/health-care/schedule-view-va-appointments/appointments/requests/[ID]
       Then the user will be re-directed to the new URL for MHV on VA.gov https://va.gov/my-health/appointments/pending/[ID]
       And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/appointment-details.md#cc-request---canceled) 

---
### Appointment details (Past) 

- [ ] Given the user is authenticated on MHV on VA.gov 
       When the user is on the Past list page, clicks on `Details` for a past VA booked appointment and the existing URL is https://va.gov/health-care/schedule-view-va-appointments/appointments/past/va/[ID]
       Then the user will be re-directed to the new URL for MHV on VA.gov https://va.gov/my-health/appointments/past/[ID]
       And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/appointment-details.md#va-in-person---past) 

- [ ] Given the user is authenticated on MHV on VA.gov 
       When the user is on the Past list page, clicks on `Details` for a past Community Care appointment and the existing URL is https://va.gov/health-care/schedule-view-va-appointments/appointments/past/cc/[ID]
       Then the user will be re-directed to the new URL for MHV on VA.gov https://va.gov/my-health/appointments/past/[ID]
       And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/appointment-details.md#cc-appointment---past) 

### Design Assets
[Copy doc - Appointment details page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/appointment-details.md)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by ldelacosta** [comment]
Please let us know if any work is required for this ticket (working tickets: #60946, #61083, #61084). If no work is needed, we can use this ticket as a checklist to verify it works as expected. cc: @JRRoof

**Comment by ldelacosta** [comment]
@young1205 - please have the UX team validate this ticket when it's ready cc: @JRRoof @outerpress

**Comment by simiadebowale** [comment]
set up general redirect from:  
`/health-care/schedule-view-va-appointments/appointments/` to : `/my-health/appointments/`

**Comment by JRRoof** [comment]
Redirects added in production October 4, 3023.
