### ISSUE TITLE
FE | Profile | Default Send/Checkboxes | Remove toggle(s) / cleanup

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#62604]
Once we've completed the Default Send work  we need to remove the toggles to clean up the feature flipper. 

Some of the toggles will need to remain until MHV items have been migrated to production. This ticket is to remove 

## Toggles details 
**Toggle ready to be removed**
- `profile_use_notification_settings_checkbozes`
  - toggles the usage of radio buttons vs checkboxes as the input type that is used for every notification. Also consumes default send indicator boolean when turned on.

## Tasks 
- [ ] Toggle for checkboxes is removed 

## Acceptance Criteria
- [ ] checkbox toggle is no longer in any of the feature flipper environments

**Comment by mtcA6** [comment]
@adamwhitlock1 how long after launch before we remove? can we consider this in the next sprint since we'll have been live for a couple of weeks?

**Comment by adamwhitlock1** [comment]
I think that we could break this ticket into 2 tickets, one to remove the `profile_use_notification_settings_checkboxes` which can be done asap/next sprint, and then the MHV and email as a channel toggles will be on hold till those items are ready for prod use.

**Comment by mtcA6** [comment]
Good call out, when we first created these we weren't sure timelines, now we for sure know MHV isn't ready :) 

Created this ticket #69486 to carve off the MHV items

**Comment by adamwhitlock1** [comment]
I updated the points on this. I started looking at the work and it's going to be quite a bit more than expected

**Comment by mtcA6** [comment]
@adamwhitlock1 what's the best way to validate?

**Comment by adamwhitlock1** [comment]
I jumped the gun slightly on this, since its still working it's way through the PR merge, but it should be up on staging shortly.

I think validation would be done through just loading up the notification settings page and making sure things work on staging. Nothing is added, but nothing should be broken essentially.

Checking and unchecking notifications
Refreshing page and making sure checkboxes state is preserved

**Comment by adamwhitlock1** [comment]
This just landed in staging. I updated a user's notifications several times and it looks good to me.

**Comment by mtcA6** [comment]
tested w user 202 and things looked great. Thanks Adam!
