### ISSUE TITLE
Send Final Test Comm

### ISSUE THREAD

**Issue by djmunoz1** [department-of-veterans-affairs/va.gov-team#62602]
As an email admin I want to send a final test comm to veterans before launching a full campaign so that I can explore the business and veteran outcomes and adequately prepare to scale.

ACCEPTANCE:
- Reactivation Test D content and list shared with PM
- Organic Test A content and list shared with PM

**Comment by lmorris3** [comment]
@djmunoz1 When all issues are completed in an epic, can we close it? (It looks like all of these are complete but it seems like the epic doesn't automatically close).

**Comment by lmorris3** [comment]
Closing - all features within this epic have been completed
