### ISSUE TITLE
[Tier 3: Medium] Possible Incorrect Content

### ISSUE THREAD

**Issue by Kimberley2019** [department-of-veterans-affairs/va.gov-team#6260]
**Issue Description:** User attempted to call a number listed on the VA Website, however it is incorrect.

**Priority:** Low

**Total Number of Issues:** 1

**Issue Number and User Description:**

**SalesForce: 02390494**
_The veteran states that on the VA’s website under patient’s right, a phone number is listed for the Joint Commissions Office of quality monitoring @ 1-800-994-6610. The veteran states that the number does not work and he is requesting someone to reach out to him with the correct number. After telling the veteran the veteran the case number. He demanded the actual number to the Joint Commissions Office of quality monitoring. The veteran was informed that I do not have the number and he demanded a supervisor. While being transferred, The veteran disconnected the call. this is the ling in question:_ [https://www.va.gov/health/rights/patientrights.asp]

**Comment by Kimberley2019** [comment]
@Karak888 have you been able to review any of the ticket?  Is there a status update?

**Comment by Kimberley2019** [comment]
@Karak888 have you been able to review the ticket?  Is there any status update that can be provided?

**Comment by Kimberley2019** [comment]
Reach out to Kara via slack message inquiring on a status update.

**Comment by MickinSahni** [comment]
@jenniferlee-dsva 

This refers to a page on the legacy site it seems: https://www.va.gov/health/rights/patientrights.asp

What're the rules of engagement for updates/fixes?

**Comment by Kimberley2019** [comment]
The phone number is a working number.  Pages in questions may be out of date.

https://www.va.gov/health/rights/patientrights.asp shows a last update date of May 11, 2015.

https://www.maryland.va.gov/about/OIG_JointCommission.asp shows a last update date of April 23, 2019.
