### ISSUE TITLE
[Tier 3: Medium] User's Having Issues Accessing/Downloading Statement of Benefits and VA Letters

### ISSUE THREAD

**Issue by Kimberley2019** [department-of-veterans-affairs/va.gov-team#6261]

**Comment by Kimberley2019** [comment]
**Issue Description:** Users are having difficulty accessing/downloading their Statement of Benefits or other VA Letters.  One issue is receiving the error message:

_“We’re sorry. Our systems is temporarily down while we fix a few things. Please try again later.”_

**Priority:** Low

**Total Number of Issues:** 4

**Issue Number and User Description:**

**Comment by Kimberley2019** [comment]
@luke-gcio @SMLuthi have you been able to review any of the issues that were sent over?  Any status update?

**Comment by luke-gcio** [comment]
This one in particular seems like it may have been related to EVSS being down for a while but it is tough to tell without knowing exact times/dates.  For these in general, is there any way to add that information into the bug report?  It does appear like this issue would not be specific or caused by our VSA Benefits team.

**Comment by Kimberley2019** [comment]
@luke-gcio This information can be requested by the Contact Center team, however, I am unsure if the  users will have that exact information.  Also, requesting that information could cause a delay in your research depending on how long it takes them to reply (and they still may not be able to advise us on the information that you are requesting).
I can reach out to the user to see if they can provide us with that information and keep you posted non the details.

**Comment by luke-gcio** [comment]
Is there any way we can change the process in a way where that information is part of the bug reporting?  I know it may be hard to retroactively get this information but it has been making it very difficult to debug without having it up front.

**Comment by Kimberley2019** [comment]
@luke-gcio No progress has been made on the issues listed in this ticket.  There has been no response from the followup sent to each user listed above.  
How do you feel about closing this ticket since there has been no movement for quite some time?

**Comment by Kimberley2019** [comment]
@luke-gcio @SMLuthi 

Has there been any movement on this issue? If not, can the team advise on how you would like to handle this issue? If yes, can the ticket be updated with the information and closed?

**Comment by Kimberley2019** [comment]
@luke-gcio @SMLuthi

Has there been any movement on this issue? If not, can the team advise on how you would like to handle this issue? If yes, can the ticket be updated with the information and closed?

**Comment by annaswims** [comment]
we are working on this issue in #7816

**Comment by Kimberley2019** [comment]
Hi @annaswims thank you for the update.  Will you comment here when the fix has been completed along with the information that we will need to tell the veterans?

**Comment by Kimberley2019** [comment]
Closing ticket.  Too much time has lapsed.  
If there are updates that would be beneficial, please reopen ticket @vhenry07
