### ISSUE TITLE
Updates to privacy and security on VA page

### ISSUE THREAD

**Issue by aliyahblackmore** [department-of-veterans-affairs/va.gov-team#62627]
We'll make updates to the [VA privacy and security page](https://www.va.gov/resources/privacy-and-security-on-vagov/). The LGA team will review this page and add any additional information about Login.gov that's needed needed.

As a first step, we'll need to review the page and note adjustments we should make to the existing content to better align with content on existing VA identity pages (i.e. how we talk about multifactor authentication).

- [x] Assess page (Aliyah)
- [ ] Review (Laura)
- [ ] LGA team Login.gov content
- [ ] Review (Aliyah/Laura) 
- [ ] Share with SMEs/stakeholders 
- [ ] Copy edit (Megan)
- [ ] Publish (Megan)

<details>
<summary>Prepublishing checklist</summary>

### Before you begin
- [ ] Confirm that there are no updates in draft by other content authors that aren't ready to be published. Check the revision log and then confirm with the content author who made the previous edits that the page is ready to publish.

### Accessibility standards

- [ ] If your link or button will take the user off VA.gov, confirm that the text for the link or button contains a purpose and a target. The user should be able to tell from the link or button text what the call to action is (the purpose) and where they will end up if they click on the link (the target). The following link is an example of this: <br>[Read more about making links accessible on AccessibilityOz](https://www.accessibilityoz.com/2014/02/links-and-accessibility/)</br> 
**Note:** When you direct the user to another VA.gov page, the link only needs to contain text indicating purpose (the call to action).
- [ ] Confirm all phone numbers are in aria labels. [Learn how to code numbers with aria labels](https://design.va.gov/content-style-guide/dates-and-numbers#phone-numbers)
- [ ] Confirm that the hierarchy of section and subsection titles is correct (H1 to H2 to H3—levels shouldn't be skipped). [Learn more about section titles](https://design.va.gov/content-style-guide/page-titles-and-section-titles)
- [ ] Replace any sighted language ("view," "see," "look") with a word that's inclusive of our screen reader users ("check," "go to," "review").
- [ ] Avoid using other ability-focused language. ("hear back from")

### Link standards

- [ ] Confirm that links work (aren't broken—no error message) and point to the intended page (you pasted in the correct URL or chose the correct node ID).
- [ ] Confirm all link text is 100 characters or less.
- [ ] Check that you've selected a node ID for all links pointing to VA.gov (internal) pages. Only paste in a URL if the page you're linking to doesn't live in our CMS (isn't one of our modernized pages). [Learn how to add node IDs in Drupal](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/how-to-do-different-tasks/linking-with-node-ids.md) 
- [ ] Check that all anchor/jump links are pointing to a node followed by # and the header identifier (Example: /node/47278/#information-for-survivors). Double check all anchor/jump links post-publish. 

### CMS standards

- [ ] Make sure all apostrophes and quotation marks are curly not straight. (Once this is automatic in Drupal, we can remove this item.)
- [ ] If there are alerts at the top of the Drupal Edit node for broken links, redirected links, or links to unpublished pages, correct the issues. If there's an alert for a broken link but the link is actually working, report the issue to the CMS help desk. [Read more about link alerts in the CMS knowledge base](https://prod.cms.va.gov/help/cms-basics/how-to-fix-broken-links-and-redirects)
- [ ] If publishing a brand-new page, confirm the left nav and url are set up correclty. (If the page is a child page, the section needs to be the same as the parent page in order for the left nav to show.) [Learn how to set up a url and left nav in Drupal](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/how-to-do-different-tasks/adding-left-nav-and-url.md)
- [ ] Check if the page has a new or updated alert. If so, publish the alert separately. 

### Additional checks for translated articles
- [ ] If we don't have updated translated versions, add the alert that links to the corresponding English page and lets users know that the translated pages aren't up to date. 

</details>

**Comment by aliyahblackmore** [comment]
Hi @laurwill - as we chatted with the LGA team in last week's meeting, this is my review of the existing content on the privacy and security page. I've made notes/adjustments to align content with other identity pages (i.e. how we're talking about multifactor authentication).

After you've done a review, next step here is to pass this to Dawn from the LGA team and they agreed to provide updated information re: Login.gov.

[Privacy and Security on VA.gov_Review_AB_7.24.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/12176293/Privacy.and.Security.on.VA.gov_Review_AB_7.24.docx)

**Comment by laurwill** [comment]
Update: We'll plan to archive and redirect this page, to point to the main Privacy, policies, and legal information page instead. @DanielleThierryUSDSVA will share this plan with Lauren and Tom, and we'll wait for confirmation before we request the redirect.

**Comment by aliyahblackmore** [comment]
@strelichl / @laurwill I'm unassigning myself from this ticket. Laura continue this work as part of the sign in and identity work.

**Comment by laurwill** [comment]
@DanielleThierryUSDSVA can we go ahead and redirect this? It's that ancient privacy page that promotes ID.me and doesn't mention Login.gov, and I think we were just waiting on approval from Tom to archive and direct to main privacy policies page.

If this is good to go, I'll request redirect from PW!

**Comment by laurwill** [comment]
Documenting that Danielle confirmed the redirect plan and I requested in this ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/96621

Moving this to validate
