### ISSUE TITLE
Documentation | Profile | Direct Deposit EVSS>LH Migration | Ensure our various FE and BE documentation items are updated

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#62628]
## Background 
Now that the API is live in production we need to scan through relevant directories to ensure our documentation references the updated items. 

## Acceptance Criteria 
- [x] BE direct deposit documentation has been updated 
- [x] FE direct deposit documentation has been updated

**Comment by adamwhitlock1** [comment]
Updated the direct deposit sections of the FE docs. I will close this now.

https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/profile/direct_deposit/frontend_documentation.md
