### ISSUE TITLE
Breadcrumbs should include schedule-view-va-appointments page

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#6263]
See screenshot below. 

When user tries to use the breadcrumb to navigate back to "Health care" it goes to "sorry can't be found" page. 

![Screen Shot 2020-02-27 at 10.23.17 AM.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/a7811abc-ba60-49ec-a792-38faf806918b)

Click on 'Health care' takes you back to this page with following url: https://staging.va.gov/health-care

![Screen Shot 2020-02-27 at 10.23.26 AM.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/31df5a85-bcb3-49aa-8008-eec1491ac16c)

It should take you back to url: https://staging.va.gov/health-care/schedule-view-va-appointments/
(Static schedule appointment landing page)

**Comment by jbalboni** [comment]
I think the bug here is that we need an extra item in the breadcrumbs that points to the schedule and view page. The link to `/health-care` should be in there and is correct, but for some reason that page is missing on staging.
