### ISSUE TITLE
Access for Justin Linn

### ISSUE THREAD

**Issue by LinnJS** [department-of-veterans-affairs/va.gov-team#6264]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toddle
- Please provide your name.
   > Justin Linn
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Name of Team: Caregivers
   > Role: Sr Front End Engineer
   > Company: GovernmentCIO

- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Internal%20Tools.md#create-ssh-public-key) for instructions.

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDNC6SumYnoUmHABBtY4Q2UCXqU1KNOLGpX5hgRrcRaJm32A0W3TwNF811li0WAzrj9/jlIToJfI/qfjtJtwWLjN+SoDzXkj+n18z11zXCB1R49uAwQ62gHT9HD18E7p/ATCTF5ks++G1yrgIbFVYOo48ACWwXkSojgvqAH+LbZy4ELSr5Q9Kpa8c0Ew9pZyDyamEn8LZdpKMK9qiMpoBbjg68tdCprxTlX12BnJxEZg4SDsOY3zm6RuUGQMxbWAJWmvvm9FlWYLXSLmDkJblHNSm5nX4LgKiCO3hNY7QgZindc2tZPAUlUQCo19ayHEj1kxnaBYj0JvN/cpETUC7zn justinlinn@boaz.local
```

- [Grant AWS Console access?] No
  > YES / NO
  >  Please give a brief description for why you are requesting AWS access.

**Comment by LinnJS** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by ricetj** [comment]
@Jeff-Hayter 
User: Justin Linn
COR: Mary O'Toddle

**Comment by ricetj** [comment]
@LinnJS You have been granted SOCKS, please follow the remaining instruction on how to configure.

**Comment by gunsch** [comment]
> Please give a brief description for why you are requesting AWS access.
> I am the only Frontend Engineer on my team and will be responsible for all analytics tagging and user experience analytics.

@LinnJS this sounds like you need access to Google Analytics, not AWS. if that's not the case, can you give more details about what in AWS you need access to?

**Comment by LinnJS** [comment]
@gunsch perhaps I misunderstood  amended answer to No

**Comment by LinnJS** [comment]
@ricetj thank you will get all that setup now, thank you for process my request so quickly!

**Comment by LinnJS** [comment]
Getting a `suspended` error will direct my questions to`#vfs-platform-support` slack channel

![image](https://user-images.githubusercontent.com/23741323/75590286-028c0800-5a4b-11ea-91e8-f19074369d1f.png)

**Comment by ricetj** [comment]
> Getting a `suspended` error will direct my questions to`#vfs-platform-support` slack channel
> 
> ![image](https://user-images.githubusercontent.com/23741323/75590286-028c0800-5a4b-11ea-91e8-f19074369d1f.png)
> 
> Link to support thread:
> https://dsva.slack.com/archives/CBU0KDSB1/p1582927704273400

thank you for threading in the support channel.

**Comment by ricetj** [comment]
Now that you have SOCKS closing this issue. If you have any other questions please reach out in the support channel.
