### ISSUE TITLE
Duplication of Institutions When WEAM Data Contains Duplicate Facility Codes

### ISSUE THREAD

**Issue by elder-joseph** [department-of-veterans-affairs/va.gov-team#6265]
As a developer, I need to prevent duplicates from being added to the `institutions` table when duplicate facility codes are present in `weam.csv`

## Assumptions:
N/A

## Acceptance Criteria
1. The SQL Query used in `institution_builder` is corrected to resolve the duplication issue based off of `version_id`

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-02-28 at 1.11.54 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/0015ce45-17cf-4791-bb8d-124b75c96c7c)
![Screen Shot 2020-02-28 at 1.12.01 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/2348a44c-e507-494a-9a3c-dcaa048159de)

**Comment by sonntag-adam** [comment]
In staging. Closing story.
