### ISSUE TITLE
[FE] Copy Mailing Address bug

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#6266]
1. Edit home address
2. Click the "my home address is the same as my mailing address" checkbox
3. Hit the modal's "save" button

Expected: the address should save
Actual: form fields are marked as invalid

![copy address bug.gif](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/c83957a2-bb55-4f70-9ca2-3e9f60542b44)

**Comment by erikphansen** [comment]
@mshea0606 can you validate that this is fixed?

**Comment by mshea0606** [comment]
@erikphansen 
![erik](https://user-images.githubusercontent.com/60523453/76467764-b92fa700-63c0-11ea-86e8-e3dac250007f.png)

**Comment by mshea0606** [comment]
@erikphansen what staging user do you use to check this? I'm not sure if it was a user issue or a FE issue.

**Comment by erikphansen** [comment]
I've been using user 37. Which user did you use on staging? How did you end up with the screenshot you shared? Did you try updating both mailing and home addresses? Or did you just try to update the home address using the "my home address is the same as my mailing address" checkbox to get the screen you shared?

**Comment by mshea0606** [comment]
@erikphansen i used staging user "vets.gov.user+27@gmail.com" aka William Daniels. I just tried again and it worked correctly.

For this user they had a mailing address but a blank home address. I checked "home address is the same as my mailing address" and it worked correctly this time. .

**Comment by mshea0606** [comment]
@erikphansen is there a particular staging user we are supposed to use for Address Validation? Also, what is the email for user 37?

**Comment by erikphansen** [comment]
@mshea0606 we've used users 24, 37, 56, and 360 which all work with the VA Profile service. And apparently so does user 27.

All user emails are `vets.gov.user+<user-number>@gmail.com`
