### ISSUE TITLE
Contact Center Review for [10-10 Health Apps team - Household section optimization]

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#62679]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
*Please provide the name(s) of your product and a high-level description of your product.*
- We have updated the Financials/Dependents section (aka Household financial information section) to include more information on how the information is used, what documentation may be needed to provide details, and various updates to how the pages look.
- **NOTE**: there are no changes to how the application flows or what information is being requested.  All fields remained the same.

### Launch Date
*Please provide the launch or rollout date and details.*
- As soon as this guide is reviewed and approved, we are ready to launch.  We wanted to launch 7/24, however we had minor staging review feedback to address.
- We plan to launch in phases over a 2-week period: 25%, 50%, 100%

### Version Number
*Please provide the version number of the guide and/or video.*
- We do not have a version number

### Product Guide
*Please provide product guide link*
- [HCA.Product.Guide.HJ.draft.07272023.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/12185525/HCA.Product.Guide.HJ.draft.07272023.docx)

### Product Video
*Please provide product video link*
- Video is not needed

### Product Video Transcript
*Please provide product video transcript link*
- Video is not needed

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
Hi @hdjustice. I notice that VEO Contact Center has a product guide for the 10-10EZ short form in their archive, dating back to 2022. Would this current guide be considered a new version of that, or a separate product? If needed, I can attach a reference copy of the short form guide.

**Comment by hdjustice** [comment]
Hi @starlow00 - that is the same guide, no new product.  "Short Form" was the feature we were working on the last time we had the guide updated and should not have been part of the name. I am sorry for the confusion.

**Comment by starlow00** [comment]
Thanks, @hdjustice. The guide looks good. I made sure the table of contents included the new subsections. I'll share it with VEO for their review today. After they're done, I'll post the active copy to this ticket.

**Comment by hdjustice** [comment]
great, thank you @starlow00

**Comment by starlow00** [comment]
No changes from VEO. Copy attached.[https://app.zenhub.com/files/133843125/5bd0be2d-d3d2-4929-be84-34c7a890e124/download](https://app.zenhub.com/files/133843125/5bd0be2d-d3d2-4929-be84-34c7a890e124/download)

**Comment by hdjustice** [comment]
Wonderful, thank you @starlow00 !
