### ISSUE TITLE
Criteria for Ranking Validation Errors

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#62674]
https://docs.google.com/spreadsheets/d/1s3mIDmsPk98q80qCyXP9Q3XhgqdV42JMGwVVG7-InLw/edit#gid=0

To help prioritize these errors and assist in giving a holistic overview to the product and technical teams we would like to visualize current form validation problems identified so far. 

Acceptance criteria:

1. For all Validation messages that need improved wording / better ux: reproduce and take a screen shot 
2. For both Validation messages that need improvement and "missing FE validation" problems, lets visualize on the Site Map in its own layer to show where the problem exists. 
3. Where possible apply a subjective UX impact grade (High, Medium, Low)
4. For Failures pulled by Eng we should determine if there is a corresponding place in the UI where that error originated from

Stretch goal:

1. Work with Engineering to determine frequency of error
2. For missing FE Validation errors, determine what the downstream impact is

**Comment by nnicholas7** [comment]
Criteria Ranking has been created for the current errors. 
Instructions for Criteria: https://docs.google.com/document/d/1NeWDaksm58Y5sByR4E6EpL6UucbprEbNyVlYXoJuiVQ/edit#heading=h.9cgnnwxto9b3

Error Message Tracker: https://docs.google.com/spreadsheets/d/1s3mIDmsPk98q80qCyXP9Q3XhgqdV42JMGwVVG7-InLw/edit#gid=0
