### ISSUE TITLE
Rename "vet360" references to "vapSvc"

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#6268]
The Vet360 service changed its name to VA Profile a few of months ago. We should update the FE code to prevent confusion and enhance clarity. Vet360 or any reference to 360 really doesn't mean anything anymore and could really confuse someone who is new to this code or the program.

## Guiding principles:
- We should drop vet360 or 360 when possible, replacing it with VAP or ~VAPSvc or~ vapSvc or VAP_SVC or simply dropping it altogether depending on the situation.
- We should aim to _not_ use the phrase "VAProfile" in our code when possible. This is ambiguous and could refer to the Profile feature we develop and maintain on VA.gov or the VA Profile service that we integrate with. 
- We should aim to simply use "Profile" when referring to the feature we are developing and maintaining and use the terser "VAP" (or some variation like "vapSvc") when referring to the service that we integrate with.

## Ideas:
- rename any mentions of `vet360` to `vapSvc`
- rename any mentions of `VET360` to `VAP_SVC`
- rename any `Vet360` files and components to `VAP` or `VAP`
- rename all references of `profile360` to `profile` as our Profile is always backed by VA Profile (ie, there is no longer a non-VA Profile/VET360 profile so we no longer need to specify which one is the VA Profile/VET360 version)
- rename the `VAProfileApp` to `ProfileApp`

## Caveats:
- be careful not to rename any strings that contain vet360 (such as error codes)
- for the time being we should not touch the top-level `vaProfile` item in the Redux store, which is a different ball of wax

**Comment by erikphansen** [comment]
I threw this in the Icebox earlier today, thinking that this was work we'd never get around to because it would potentially create big mess and/or break things. But I revisited it with the idea of using `VAP` or VAPSVC` (rather than `VA Profile`) in place of Vet360 as it will still be clear when we are talking about the service we are integrating with or the feature we are building. `VA Profile` is now a potentially very confusing term in our code. But `VAP` or `VapSvc` stands out in code the same way that `Vet360` does so I think it will be clear that `VAP` is referring the the service and `Profile` is referring to the feature we are building.

@ncksllvn @sanlouise do you have any thoughts?

**Comment by sanlouise** [comment]
I think it would be nice to get rid of the 360 references, but do you think it would be a good time to do this now or would it be better to address this when we roll out Profile 2.0 and could include this in a larger cleanup? I assume we'll need to remove the current profile references/components once Profile 2.0 is validated and live? Also, I like more descriptive names - so instead of `vapSvc` could we instead rename it to `vapService`?

**Comment by ncksllvn** [comment]
`vap` is a great idea! I like @sanlouise's idea of the full `service` part, `vapService`. Should it be pascal case, like `VapService`, or the extreme `VAPService`

We should also start thinking ahead what the next name might be after it's renamed again 🤔

**Comment by erikphansen** [comment]
cool, yeah we don't need to do this now and using full `service` is cool with me!

**Comment by erikphansen** [comment]
Closing after merging in these 10 PRs

[PR 1 renamed the `vet360` folder to `vap-svc`](https://github.com/department-of-veterans-affairs/vets-website/pull/14798)
[PR 2 renamed the `vet360` Babel alias to `@@vap-svc`](https://github.com/department-of-veterans-affairs/vets-website/pull/14811)
[PR 3 renamed the `isVet360Configured` helper to `isVAProfileServiceConfigured`](https://github.com/department-of-veterans-affairs/vets-website/pull/14834)
[PR 4 renamed Redux's `profile.vet360` data to `profile.vapContactInfo`](https://github.com/department-of-veterans-affairs/vets-website/issues/14866)
[PR 5 renamed some `VET360` constants, actions and selectors](https://github.com/department-of-veterans-affairs/vets-website/pull/14888)
[PR 6 renamed more `VET360` constants to `VAP_SERVICE`](https://github.com/department-of-veterans-affairs/vets-website/pull/14899)
[PR 7 renamed some contact information selectors](https://github.com/department-of-veterans-affairs/vets-website/pull/14912)
[PR 8 renamed the top-level `vet360` slice in Redux to `vapService`](https://github.com/department-of-veterans-affairs/vets-website/pull/14917)
[PR 9 renamed remaining Vet360 components](https://github.com/department-of-veterans-affairs/vets-website/pull/14929)
[PR 10 renamed remaining Vet360 constants](https://github.com/department-of-veterans-affairs/vets-website/pull/14930)
