### ISSUE TITLE
Create informational write-up about the need for and benefits of non-visual prototypes

### ISSUE THREAD

**Issue by A6-toma** [department-of-veterans-affairs/va.gov-team#62705]
## Issue Description
As a development team, I want to have access to non-visual prototypes for products and features we're building  so that we can conduct research with people who use assistive technologies, (e.g. - Keyboard, Screen Reader) in order to make our research more inclusive..

This ticket is meant to create introductory materials regarding non-visual prototypes. This includes: 
- What non-visual prototypes are
- Why non-visual prototypes are needed
- How non-visual prototypes can be used 
- What benefits can be gained by having non-visual prototypes available

## Tasks
- [ ] Write a document detailing the need for non-visual prototypes as well as the benefits of having them.
- [ ] Make the document available to other teams in Github, SharePoint, or another similar shared location.

## Acceptance Criteria
The document outlined above has been written and made available to other teams.

**Comment by AngelaFowler82** [comment]
The info sheet has been drafted:

https://docs.google.com/document/d/1qBufa_KemrFXI6dobjGZAJZiZHGdQkY2AzszNBHq8zE/edit
