### ISSUE TITLE
Deploy app via MRSK

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#62706]
### PROBLEM STATEMENT:
Need to deploy app with the latest changes via MRSK

### ADDITIONAL INFORMATION:
This relates to merging to master. Need to get the latest changes out in the live environment.

### ACTION ITEMS:
- [x] deploy on the CL 
- [x] make sure any migration necessary are run

**Comment by laineymajor** [comment]
This should have been part of the last sprint for this project... moving it to the sprint starting Aug 17, which should be our last sprint for this work.

**Comment by laineymajor** [comment]
In review as either 
-nearly complete
-or NA

**Comment by LindseySaari** [comment]
Closing this because mrsk is no longer necessary once we deploy this in house (almost there!)
