### ISSUE TITLE
Platform Codeowners - Rspec

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#62704]
### PROBLEM STATEMENT:

Rspec has not been setup.

[Rspec-rails ](https://github.com/rspec/rspec-rails)can be setup following github instructions.

### ACTION ITEMS:

**Comment by laineymajor** [comment]
on hold until soft delete is complete

**Comment by laineymajor** [comment]
@RachalCassity will start this when Lindsey gives the go-ahead

**Comment by LindseySaari** [comment]
I've created the test suite for models and controllers for existing functionality through a super_user flow. Changes are pushed up and ready for Gia to add in soft delete testing and Rachal to provide tests for non-super user flows.

**Comment by LindseySaari** [comment]
I've created the test suite for models and controllers for existing functionality through a super_user flow. Changes are pushed up and ready for Gia to add in soft delete testing and Rachal to provide tests for non-super user flows.

**Comment by laineymajor** [comment]
Is #63473 part of this ticket?
