### ISSUE TITLE
CRON JOB:updating the database

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#62703]
### PROBLEM STATEMENT:
We need to create a Github Action so that when codeowners is updated, the database gets updated automatically. 

**UPDATE**

A cron job can be easily run` bin/rails runner ProductDirectory::File.populate` every day to update the codeowners database. A github action is no longer needed.

### ADDITIONAL INFORMATION:
This is a different branch than the one Gia is working on re another GHA.

### ACTION ITEMS:
- [ ] Get codeowners up and running in EKS
- [ ] Add cron job to the eks manifests

**Comment by laineymajor** [comment]
@RachalCassity is taking this on. Near complete, but need to repopulate parts of the database.

**Comment by laineymajor** [comment]
Carryover to next sprint. Had to shift focus and help with PACT ACT

**Comment by RachalCassity** [comment]
This will be a cron job

**Comment by RachalCassity** [comment]
Cron job added to the manifest! Marking this as done! @laineymajor

**Comment by RachalCassity** [comment]
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/commit/4503e41797a4212eef01e4894c48a72c5e259813
