### ISSUE TITLE
Work with VFS teams to verify ownership

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#62712]
### PROBLEM STATEMENT:
We need VFS teams to verify file ownership. adding a 'verification' column and will work with VFS teams to verify.

### ACTION ITEMS:

**Comment by laineymajor** [comment]
Rules are implemented per Rachal (preventing teams from messing with data they shouldn't have write access to).
We need to make sure we have all the correct team 'members' in the database so the correct people can verify what we need them to verify.

Options:
a) direct teams to the team roster, make sure the teams have the correct team name and people on their 'team'
b) Rachal create own app to use our team as a guinea pig to ensure we can get the right users on their 'teams'

**Comment by laineymajor** [comment]
Lainey to send message with instructions on how to login to the app... if they cannot login, instructions on what to do (contact us)
https://va-codeowners.boehs.com/

**Comment by laineymajor** [comment]
Rachal to make recording and send to Lainey

**Comment by RachalCassity** [comment]
Login instructions: https://vfs.atlassian.net/wiki/spaces/TT1/pages/2733998148/How+to+Login

**Comment by RachalCassity** [comment]
How to view Github Team Files https://vfs.atlassian.net/wiki/spaces/TT1/pages/2733998160/View+Github+Team+Repository+Owned+Files

**Comment by laineymajor** [comment]
This has been sent out and we are tracking progress in a separate ticket.
