### ISSUE TITLE
Job to update codeowners

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#62711]
### PROBLEM STATEMENT:
Need GH action to listen for changes in the codeowners file so the database gets updated (all specific to vets-api).

### ADDITIONAL INFORMATION:
- We have a parsing mechanism in place (link and review)
- Review discovery ticket (confluence [doc](https://vfs.atlassian.net/wiki/spaces/TT1/pages/2719350811/DISCOVERY+How+might+we+create+an+automated+library+for+vets-api+code+61955))

### ACTION ITEMS:
- [ ] setup periodic job to run every day (currently set to every hour... wait and see what to leave as final)
- [ ] update codeowners if team is deleted
- [ ] update codeowners if team name changes
- [ ] if someone creates a new file, there is an entry
- [ ] if someone deletes a file, we need to make sure the codeowners entry (and database entry) are removed

**Comment by laineymajor** [comment]
ryan <> gia - schedule to add to the PR
- gia setup the job to run every hour (this ticket can be amended)

**Comment by laineymajor** [comment]
Carryover required. Adding to next sprint.

**Comment by laineymajor** [comment]
Gia's work on this branch is complete. @RachalCassity now working on it. @RachalCassity to update ticket please

**Comment by laineymajor** [comment]
This is likely a duplicate.

**Comment by RachalCassity** [comment]
@laineymajor Completed in this ticket. https://app.zenhub.com/workspaces/platform-tech-team-1-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/62703

**Comment by laineymajor** [comment]
Can this ticket be closed? Seems like it can be...

**Comment by laineymajor** [comment]
This is now in prod. Good to close. Was a dupe.
