### ISSUE TITLE
Design System Staging Review - Accessibility Feedback - Converted components: Text input, Text area, Number input

### ISSUE THREAD

**Issue by briandeconinck** [department-of-veterans-affairs/va.gov-team#62724]
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- On the [number input component](https://design.va.gov/storybook/?path=/docs/uswds-va-number-input--default), the `currency` prop doesn't seem to do anything. Is there any intended behavior there? Possibly a Storybook issue?

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- **Must:** On all three components, the `hint` text isn't programmatically associated with the input. That means it won't be announced by screen readers when tabbing into the input, so a screen reader user may miss out on important context or instructions. Recommendation here would be to associate the `hint` using `aria-describedby`.
- **Must:** On the text input component, the character min/max length text isn't programmatically associated with the input. It sounds like this might be in flux with changes coming to better match USWDS. Either way, similar behavior as the `hint` text.
- **Consider:** On the number input component, there's no visible text (or text announced by screen reader) to reflect the min/max values. Not sure if it's desirable from a design standpoint, but it seems like a similar use case as the character min/max length on the text input.
- **Should:** From the meeting, I think I better understand the intention behind `message-aria-describedby` on the text input. I think it makes sense to make that property available on all three of these components.

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/va.gov-team/62724?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @nickjg231 @powellkerry

**Comment by jamigibbs** [comment]
> On the [number input component](https://design.va.gov/storybook/?path=/docs/uswds-va-number-input--default), the currency prop doesn't seem to do anything. Is there any intended behavior there? Possibly a Storybook issue?

A couple of clarifications about the `currency` prop:

1. At the moment, we only have it available with the [non-USWDS version](https://design.va.gov/storybook/?path=/docs/components-va-number-input--with-currency) of this component. I believe our intention for the USWDS version is to use an [input prefix like in the USWDS example](https://designsystem.digital.gov/components/input-prefix-suffix/). We just have not built this feature out yet.
2. On the non-USWDS version that does have a [currency option](https://design.va.gov/storybook/?path=/docs/components-va-number-input--with-currency), we got some [accessibility feedback on that from this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/55335) but if there are any other updates you think we need to make, I'm happy to look into it more.

**Comment by jamigibbs** [comment]
Hi @briandeconinck! I have created a [PR for the updates requested](https://github.com/department-of-veterans-affairs/component-library/pull/788) here. I believe I have addressed all of the Must, Consider, and Should there (as well as a clarifying comment above). I'm not sure if you need to validate them as well but I will pause on closing this ticket until I get a thumbs up from you.
