### ISSUE TITLE
<Content and IA> from <Cartography team (MHV on VA.gov)> 

### ISSUE THREAD

**Issue by jonathanjnelson** [department-of-veterans-affairs/va.gov-team#62725]
## About your team

- Team name: Cartography Team (MHV on VA.gov)  
-	OCTO-DE product owner: Patrick Bateman 
-	Product manager: Tom Anderson 
-	Designer: Jonathan Nelson, Florence McCafferty, Keith Cheung
- Accessibility specialist: Angela Flower 
- Content writer: N/A 
-	Slack channel: [#mhv-on-vagov-portal-home](https://dsva.slack.com/archives/C04GDQSHD1R)
 
### Describe what you need in a few sentences:

</br> We learned from March's usability study [03/2023 landing page user research findings summary](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/landing-page/research/2023-03-Landing-Page-User-Research/2023-04-landing-page-readout.md): 

Participants who already knew what Community Care (5 participants) were drawn to it, while those who were not already familiar with the service Community Care (8 participants) did not recognize the term and instead sought another way to communicate with the VA team.

We are working to design a potential solution to help address users understanding of the "Community Care" link on the landing page...

- We need to make sure the content/links we’re using in our tool is written in plain language and follows the style guide. 
- We need to confirm the links lead to an appropriate page  

### Which are you doing?
- [ ] **Launching a new** page, tool, form, or app
- [x] **Making changes** to an existing page, tool, form, or app

### Types of Support
What areas does your team need support in? Check all that apply.
#### Content
- [ ] Collaboration on content written by your team’s dedicated content writer 
- [x] Collaboration on content if your team does not have a dedicated content writer
#### Accessibility
- [ ] Accessibility review of wireframes and/or prototypes
- [ ] Accessibility issue (general request)
- [ ] Accessibility PDF review request
- [ ] Accessibility user research support ([submit a separate, additional request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name))
- [ ] DST component or pattern 
- [ ] Something else 
#### IA
- [x] User Flows
- [ ] Page placement
- [ ] Object-Oriented UX (OOUX) support
- [x] URLs
- [ ] Breadcrumbs and Left Nav placement
- [ ] Redirects
#### Multilingual content
- [ ] Translating content
 
## Timeframe
_We guide and work alongside teams across nearly every OCTO digital product. We also work with partners across VA to lead content migration and manage all unauthenticated content on VA.gov. And we're always working to expand the VA.gov content style guide and our IA and accessibility documentation. We need to prioritize all intake requests based on our overall workload and VA and OCTO priorities._

_Tell us about your product's timeline. And we'll work with you to meet timeline needs as best we can._

### Have you worked with CAIA before? 
  - [ ] Yes
  - [x] No

### What's your team’s next step and its timing?

- **Our next step is** Implementing feedback/guidance into designs, update landing page, include in next round of usability study 
- **Provide date if available**: ASAP 

#### Timing for your next step: 
  - [x] Next week
  - [ ] This month
  - [ ] Next month
  - [ ] This quarter
  - [ ] Next quarter
  - [ ] 6 months
  - [ ] 1 year

### Is this timing related to a specific event or Congressionally mandated deadline?
  - [ ] Yes
  - [x] No

### If you're conducting research, when is that starting? 
**Provide date if available:** xx/xx/xxxx
  - [ ] Next week
  - [ ] This month
  - [ ] Next month
  - [ ] This quarter
  - [ ] Next quarter
  - [ ] 6 months
  - [ ] 1 year

### Will you release this new product incrementally (for example, release to 25% of users to start)? 
  - [ ] Yes
  - [x] No
 
**Note**: _If you checked yes, we’ll reach out to discuss details about the content in the react widget (we use these widgets to display entry points for new products to a certain percentage of users who visit our static pages)._

  
### When do you expect to launch your product to 100% of users?
  
*Please provide an estimated date so our team can create other relevant tickets.*
- **We expect to launch our product to 100% of users on:** xx/xx/xxxx
  
### Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [x] No

### If no ...
- Skip to the _supporting artifacts_ section, below.
 
#### Please provide the link to your Collaboration Cycle ticket: 
- **Ticket (number)**: 
- **Collab. Cycle Ticket Opened (date)**: xx/xx/xxxx
 
#### Please check all of the phases in the Collaboration Cycle you have completed: 
- [ ] Design Intent
- [ ] Midpoint Review
- [ ] Staging
 
##### Design Intent
- [ ] Accessibility
- [ ] Content
- [ ] IA
- [ ] Translation
- [ ] Already completed, no assistance needed
- [ ] Unknown at this time
##### Midpoint
- [ ] Accessibility
- [ ] Content
- [ ] IA
- [ ] Translation
- [ ] Already completed, no assistance needed
- [ ] Unknown at this time
##### Staging
- [ ] Accessibility
- [ ] Content
- [ ] IA
- [ ] Translation
- [ ] Already completed, no assistance needed
- [ ] Unknown at this time
  
## Supporting artifacts
*Please provide links to supporting artifacts as available.*
- **Product outline**:  [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/digital-health-modernization/mhv-to-va.gov/landing-page)
- **User flows**:  
- Option one: [Adding two links around Community Care ](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/v/G53Zjw/a/71aOw7b)
- Option two: [Keeping "Community Care" and adding link for those unfamiliar with the term "Community Care"](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/oMvM8Q5)
- **Prototype or mockups**: [Landing page Prototype](https://cdpn.io/pen/debug/VwGVjZG)
- **If this is in Sketch, which version or specific page should we focus on?**
- **Content source of truth**: N/A
- **Research plan:** N/A
- **Any epics/issues that may be helpful**:  https://app.zenhub.com/workspaces/mhv-on-vagov-top-level-view-62619a987d74510018ecc546/issues/gh/department-of-veterans-affairs/va.gov-team/60479
- **Link to testing accounts** (please do not paste them in this ticket): 

### Have you already worked with someone from OCTO leadership?
- [x] Danielle
- [ ] Beth
- [ ] Mikki
- [ ] Martha

### How do you plan to work with us on this request?
- [x] I’ll take this to Beth or Danielle’s office hours.
- [x] I’d like to schedule time to talk about this.
- [x] Let’s work async and meet as needed.

 
### Accessibility Help in Slack
The [#accessibility-help channel](https://dsva.slack.com/archives/C8E985R32) in the DSVA Slack, is also available to you as a resource. Everyone is welcome to ask questions or get help from our a11y (accessibility) specialists. Tag `@Terry Nichols` to get a11y help asap.

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag `@Terry Nichols`.**

- If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
- If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)
 
 - If you are creating an [experimental design,](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) please [also contact the DST. ](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)

- If you are requesting [a11y support for user research,](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name) please complete this form, next.

**Comment by kristinoletmuskat** [comment]
Hey @jonathanjnelson thank you for submitting this ticket! Just to confirm, are we talking about this entry point on the landing page and the [legacy page](https://www.va.gov/COMMUNITYCARE/programs/veterans/index.asp) it links to?

![Image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/122126772/a3391afa-f8ac-454a-9743-1723c0ce8965)

And could you share what the task was that we had users do re: community care in the research? Just for context so we can understand the feedback better. 

Also for me the sketch files with option 1 just go to the general MHV link -- could you share a screenshot or tag me and @laurwill in the exact spot in sketch where you're showing the options?

Thanks! Feel free to reach out in slack if that's easier too.

**Comment by laurwill** [comment]
Hi @kristinoletmuskat , I'm able to view the Sketch files — here are screenshots:
Option 1: 
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/104158104/c657eb58-9695-4292-a293-745a1601e1ac)
Option 2:
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/104158104/f33db430-9ffd-4d7f-aaac-de15103f099e)

@jonathanjnelson the prototype has different link text for many of the surrounding links, compared to what's in the Sketch files. Is the prototype the most up to date source for the link styling? (The Sketch files switch between "my" and "your" wording, and the prototype is more consistent.) Thanks!

**Comment by jonathanjnelson** [comment]
> Just to confirm, are we talking about this entry point on the landing page and the [legacy page](https://www.va.gov/COMMUNITYCARE/programs/veterans/index.asp) it links to?

Yes, we are talking about the entry point on the landing page. Hope to link to the modernized community care pages though.

**Comment by jonathanjnelson** [comment]
@laurwill Thank you and my apologizes. Let me make sure those are aligned. Also, I thought about this a bit more yesterday and I want to purpose a less complicated solution. 

Instead of the "two link solution" - we were thinking we should just work on content of "Community Care" link. Let me get you a screen shot.

**Comment by jonathanjnelson** [comment]
Hi @laurwill and @kristinoletmuskat, I updated the links in this ticket to help reflect my current thinking on this work. Please let me know if you have any questions. 

We were thinking if we can rework the content in the "community care" link (realizing the content below is not there yet) it would help Veterans both learn about and schedule/get referrals. We can link to the [About our VA community care network and covered services](https://www.va.gov/resources/about-our-va-community-care-network-and-covered-services/)

Option one:
[Visit a non-community care provider](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/pY4LdQk)
[Learn about our community care and covered services](https://www.sketch.com/s/908b453b-ef8b-4193-b955-ea00f9fd14aa/a/YZJnlyd)

The question we asked in the study was: 

> If you needed to see a healthcare provider outside of the VA and you wanted to see if that would still be covered by your VA benefits, how would you figure that out?

@laurwill In terms of consistency, what links are you referencing? As you know, sometimes things get messy in Sketch.

**Comment by jonathanjnelson** [comment]
![VA-MHV-Home-March-lg-one-link](https://github.com/department-of-veterans-affairs/va.gov-team/assets/58444931/bad02c49-08ec-4676-9299-f4af6f7a938c)
![VA-MHV-Home-March-lg-one link](https://github.com/department-of-veterans-affairs/va.gov-team/assets/58444931/14de7135-59a5-43f4-adf4-5b54fd011b27)

**Comment by kristinoletmuskat** [comment]
Yo! Confirming that there's no IA work we need to do here -- Laura's on the content.

**Comment by laurwill** [comment]
Hi @jonathanjnelson ,

This is tricky! To really describe what the network is, the link would probably need to get much longer ("Learn about getting care from non-VA providers in our community care network"). But that wouldn't fit with the rest of the page.

Since the other links in this section are very short, I wonder if just a small change can help here:
- **Community care network and covered services**

That might give more of an idea that it's a network of providers and that VA covers care through it. Let me know what you think of that approach.

Can you confirm if the current link text in the landing page uses "my", "your", or no pronouns? I still see different link text in the prototype than in the screenshots. We want the link here to be consistent with others on the page. Thank you!
