### ISSUE TITLE
[Data] 10-10EZ - Deeper Dive into "Passive" Error

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#62732]
As a Veteran applying for Healthcare, I would like to do so without getting any errors so that it is as easy for me as possible to get the care I deserve. 

- [x] Create Data Dog view
- [x] Determine who this is happening to and what tech they're using (mobile, OS, browser, etc.)
- [ ] Determine if there are any correlations with time of day
- [x] Determine if there is any correlation with user flow
- [x] Come up with conditions under which this is happening
- [ ] Present to team (we will have a separate story for any solution)

SERVICE:  10-10ez

ERROR_TYPE:  PreventDefaultPassive

ERROR_MESSAGE:  Unable to preventDefault inside passive event listener due to target being treated as passive.

STACK_FRAME
https://www.chromestatus.com/feature/6662647093133312
  at <anonymous> @ https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/hca.entry.js:2:1685953

**Comment by luis-simauchi** [comment]
There were 1.74k errors over a period of the last 14 days affecting 822 sessions (2% of all sessions)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb0VWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--175ec1216522e265f23ce732c9929f4e38cc654f/Capture%2003.PNG)

**Comment by luis-simauchi** [comment]
List of top pages where the error occurs most frequently

/health-care/apply/application/military-service/service-information
20%
/health-care/apply/application/?/spouse-personal-information
18%
/health-care/apply/application/?/dependent-information
16%
/health-care/apply/application/household-information/dependent-information
16%
/health-care/apply/application/household-information/spouse-information
15%
/health-care/apply/application/id-form
8%
/health-care/apply/application/insurance-information/medicare-part-a-effective-date
4%

**Comment by luis-simauchi** [comment]
List of top browsers where the error is occurring most frequently

BROWSER NAME

Chrome
78%

Edge
22%

Opera
< 1%

**Comment by luis-simauchi** [comment]
Elements in question is the date selector present on certain pages of the application:

/health-care/apply/application/?/spouse-personal-information
/health-care/apply/application/?/dependent-information
/health-care/apply/application/military-service/service-information
/health-care/apply/application/id-form
/health-care/apply/application/household-information/dependent-information
/health-care/apply/application/insurance-information/medicare-part-a-effective-date
/health-care/apply/application/household-information/spouse-information
/health-care/apply/application/veteran-information/profile-information-dob
/health-care/apply/application/review-and-submit

prevent default may be tied to "date selector" or the "continue" button on portions of the application as the error is occurring 

Hypothesis from Matt Long:  Likely on Progress Button (Continue) - Button has a declared function that only prevents default. Function has comment of “function that bypasses onBlur when clicking” . Errors are tossed only 1s prior to the click event firing.

This is the ProgressButton.jsx file in platform/forms-system/src/js/components/ProgressButton.jsx

**Comment by luis-simauchi** [comment]
Example replay of how the passive error is materializing for a user:

https://vagov.ddog-gov.com/rum/replay/sessions/f55c387d-f96f-465b-a835-fde6cd16ff1a?highlightedEventId=AgAAAYoj8KwSFwpy7wAAAAAAAAAYAAAAAEFZb2o4TWtZQUFDSTJpYWhUdmRzNHdBRwAAACQAAAAAMDE4YTIzZjUtODA5Ny00ZWM4LWJlZmEtMzk4MzIzMTM5MWZj&seed=36b7ef89-0f3d-49e2-9302-c431598f52de&ts=1692820089874&from=1692819956152

**Comment by luis-simauchi** [comment]
multiple replays reveal that it is the date selector element that is tossing the error out and not necessarily the continue button.

https://vagov.ddog-gov.com/rum/sessions?query=%40issue.id%3A3461e3ae-7fe1-11ed-8a07-da7ad0900007%20%40type%3Aerror&cols=&p_tab_h_event=AgAAAYos25mRjy9y6wAAAAAAAAAYAAAAAEFZb3MyLVBfQUFDSTJpYWhUalBsQ0FBQwAAACQAAAAAMDE4YTJjZTktNTk0Ni00MDc1LWJhMGYtZGQ2NTBjYzgwYWY5&viz=stream&from_ts=1691763671099&to_ts=1692973271099&live=false

**Comment by luis-simauchi** [comment]
the prevent default error is most likely tied to the "date selector" element on portions of the application as the error is occurring right after the element is clicked on by users and not necessarily the continue button; as the session replays reveal a consistent pattern of behavior prior to the error materializing. This makes sense in that the pages that the error occurs on the most are those with date selector elements present on them; such as the "/health-care/apply/application/?/spouse-personal-information" page.
