### ISSUE TITLE
Login.gov organic adoption test email

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#62748]
Dawn from Login.gov adoption team shared that their team is planning to send the first "organic adoption" test email on 8/2. 

Draft content is in this [Google doc](https://docs.google.com/document/d/1PXD3-AW095JJEv_EWHDGQOtWA7JcaoIeSmrNNjnGL80/edit). 

- There are some changes we'll need to make around the "Learn more" section (currently the intro text, link text, and actual URL don't align.)
- We may also want to make some additional adjustments for content standards
- Audience: veterans who do not have a modern credential and are using only DSL and/or MHV
- Intended send date: w/o 7/31
- Pls review by: EOD 8/2

**Comment by laurwill** [comment]
@djmunoz1 @CarlDickerson , here's a very quick stub ticket I put up to capture this request. 

Dawn, can you confirm:
- When you're planning to send this email and when you would need our feedback by? 
- Are you planning to exclude Veterans who **can't** create Login.gov accounts from this test? (Like those with foreign addresses). 

cc @DanielleThierryUSDSVA for awareness

**Comment by CarlDickerson** [comment]
@laurwill the email is schedule to deploy on 8/2, so we would need any feedback by EOD. The content is similar to what we've been viewing and we made updates based on feedback to get ahead, so hopefully this won't be too much of a lift.

**Comment by djmunoz1** [comment]
@laurwill we are not planning to exclude those with foreign addresses. We anticipate this is an edge case and are seeking the data from MPI to back it up. We have discussed with our PO and for this test given its small scale, we will leverage feedback from call centers to help determine how much of an issue this as we pursue the data.

**Comment by djmunoz1** [comment]
We appreciate the attention @laurwill! These messages are so urgent. What's the anticipated ETA?

**Comment by DanielleThierryUSDSVA** [comment]
Hi @djmunoz1. I happened to see this comment come through as I was working late this evening. The ticket says "Pls review by: EOD 8/2." I see that Laura noted she'll provide feedback later today, and I'm sure she intends to do that. But it's 8/1 so just checking to ask if the urgency for an ETA tonight is due to the deadline moving up a day?

**Comment by laurwill** [comment]
Hi @djmunoz1 and @CarlDickerson , I've attached a Word doc here with edits to align with content standards and with the use case for creating a new Login.gov account. 

I realized after a closer review that this email referenced upcoming sign-in changes, but it's labeled "organic adoption." Is the intention here to:
- Refer to a need for Veterans to change to a more secure sign-in option? Or
- Encourage Login.gov with no reference to any specific changes or need to change?

I edited assuming it was the first case (referring to upcoming changes and the need to change). If that's not the intention, let's talk about that tomorrow.

**Comment by laurwill** [comment]
Hi @djmunoz1 , also noting an item from last week's identity comms sync here — Carnetta mentioned that MHV contact centers often get calls about emails like this, and asked that your team send copies of any emails for contact centers to refer to. I think you're already sharing these with MHV, just wanted to document here!

**Comment by djmunoz1** [comment]
Yes! We're definitely giving them heads up via their preferred template for each scheduled send -- thanks for documenting!
