### ISSUE TITLE
Adding [andrew.bergeron@coforma.io] to DSVA Slack

### ISSUE THREAD

**Issue by jlang10761** [department-of-veterans-affairs/va.gov-team#62763]
Please add andrew.bergeron@coforma.io as a full member, they will be joining the CEDAR CDS project. We will add them to the appropriate channels once they are in.

Please reach out to Jeff Langworthy on DSVA slack for any questions/clarifications.

**Comment by LEHigley** [comment]
had previously been a member--reactivated their account
