### ISSUE TITLE
Add links about fraud to Pension pages

### ISSUE THREAD

**Issue by AnneHurley** [department-of-veterans-affairs/va.gov-team#6276]
##Content request from VBA##

Following up on our VBA check-in yesterday, on closer look, the FCC and Consumer Finance pages do have more helpful information than our current VA blog and benefits.va.gov content. 

@Anne Hurley – Add links to the above:  
On these Pension pages: 
https://www.va.gov/pension/
https://www.va.gov/pension/survivors-pension/

Add contextual or more info links to: 
https://www.fcc.gov/veterans-targeted-benefits-scams
https://www.consumerfinance.gov/about-us/blog/helping-prevent-scams-targeted-veterans/

Angie – the only link that would be redundant is the link to this requested page: https://www.va.gov/oig/hotline/default.asp - We currently already link to the OIG site on all of our pages, per the federal requirement to link to OIG website. It currently lives in the footer (because that is actually the location that has been mandated), as well as on our Privacy, policies, and legal information page.

**Comment by AnneHurley** [comment]
@RLHecht  The survivors pension page is ready for your review/publish. I added the 2 links at the bottom of the related links/more  info section

https:://cms.va.gov/node/590/edit

**Comment by AnneHurley** [comment]
@RLHecht  Main pension hub page is now updated with the 2 links in bottom box on spotting and avoiding scams:

https://prod.cms.va.gov/node/73/edit

**Comment by RLHecht** [comment]
@AnneHurley The Survivors Pension page is OK and published. I changed "Aid & Assistance" to "Aid & Attendance" in the last link.

**Comment by AnneHurley** [comment]
When pages are live I'll send links to Angie Smith, with this additional note, per Jen:

We decided not to link to this requested page: 
https://www.va.gov/oig/hotline/default.asp 

We currently already link to the OIG site on all of our pages, per the federal requirement to link to OIG website. It currently lives in the footer.

**Comment by RLHecht** [comment]
@AnneHurley the Pensions hub page is also now published. I can move this ticket to validate.
