### ISSUE TITLE
DB export when we create our new app via pg_dump/etc

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#62771]
### ADDITIONAL INFO
Blocked until after verification
This should be one of the last things we do for this project/app

### ACTION ITEMS
- [ ] need to reseed the database after verification
- [x] Export the database from fly.io: `pg_dump -U username -h hostname -d databasename -f dumpfile.sql`
- [ ] Transfer the dump file to where we want it
- [ ] Import the database into RDS: `psql -U username -h hostname -d databasename -f dumpfile.sql`

**Comment by LindseySaari** [comment]
## Notes:

1. Export the database from fly.io: `pg_dump -U username -h hostname -d databasename -f dumpfile.sql`
2. Transfer the dump file to where we want it
3. Import the database into RDS: `psql -U username -h hostname -d databasename -f dumpfile.sql`

**Comment by LindseySaari** [comment]
Reminder to us: see the comment above. We will want to do a re-run of the owners, teams and members from the roster incase things have changed since we first started to develop this

**Comment by laineymajor** [comment]
Will be last... not 100% convinced we need to do a pg_dump

**Comment by flooose** [comment]
@LindseySaari have you considered the context in which the import should run, i.e. `kubectl`, init containers, jobs, other? I ask because our RDS instances don't simply allow you to connect to them and run shell commands.
