### ISSUE TITLE
[Bug]: Edit Address modal does not handle 400 errors from `POST address_validation`

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#6278]
## Summary

We do not handle this error response from the `POST address_validation` endpoint:

```json
{
  "errors": [
    {
      "title": "Address Validation Error",
      "detail": {
        "messages": [
          {
            "code": "ADDRVAL101",
            "key": "SpectrumServiceError",
            "text": "The Spectrum Service returned an error",
            "severity": "FATAL"
          }
        ]
      },
      "code": "VET360_AV_ERROR",
      "status": "400"
    }
  ]
}
```

We show the address validation modal without suggestions or the ability to override instead of an error message on the edit address modal.

<img width="470" alt="Screen Shot 2020-02-27 at 3 50 08 PM" src="https://user-images.githubusercontent.com/34068740/75486076-dce2fe00-5979-11ea-8849-3a931920b690.png">

We should show an error alert at the top of the edit address modal and not show the address validation modal.

Also, as soon as the "Update" button is clicked in the Edit Address modal, the modal disappears when it should be showing the loading spinner in place of the "Update" button. Then when the error comes back from the endpoint the Address Validation modal appears. This actually appears to have a different root cause because it's happening locally when no 400 error comes back from the validation endpoint.

This issue was originally reported in this ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/6277

**Comment by Samara-Strauss** [comment]
Closing in favor of #6203
