### ISSUE TITLE
Define the metrics of the pilot

### ISSUE THREAD

**Issue by skirkman16** [department-of-veterans-affairs/va.gov-team#62782]
As a UX Researcher, I understand what is being measured throughout the pilot in order to ascertain if the pilot is succeeding across front and back end experiences

AC:
- [x] List of metrics (quantitative and qualitative)
- [x] Justification as to how metrics indicate goal progress
- [x] Engineering has confirmed they can collect backend metrics

Definition of Done:
- [x] IPP Pilot plan updated
- [x] IPP research plans updated

**Comment by jrjamespdx** [comment]
Process Suggestion:  Product, Design, and Research could meet to come up with a list of needs/wants (and any related context and/or use case examples) for metrics for the pilot.  Once that list is ready, the Engineering team can do an investigation into what's feasible and the difficulty involved.  

Given the myriad of potential data sources, each with their own rules/processes/regulations, Engineering will not be able to give a real-time, in-the-moment feasibility assessment.

**Comment by SophiaPhilipMO** [comment]
Qualitative Data:
Collected via the following methods:
Pre-and post- surveys for VA Staff
Feedback survey post pilot for Veteran
Direct observation

Quantitative Data: 
Collected, including the following metrics:
# of Veterans who complete in-person identity proofing 
# of failed verifications as a result of tool limitations 
# of Veterans who receive their Case # in an email
:# of accounts verified
# of Veterans who rate in-person proofing ‘good’ or ‘great’ (or whatever the two highest ratings end up being on the survey)
Key Performance Indicators:
Veterans receive an email with their Case # when they elect ‘verify identity in person’ in the application
Receive Verify 9 Veterans for in-person proofing at the pilot site successfully within a 1 week period 
Veterans bring the correct materials for identity verification
Veterans have their Case # and/or their Case # can be retrieved by the Proofing Agent
Proofing Agents are able to complete all steps of the identity verification process
Veteran feedback is collected before and after their identity verification sessions with the Proofing Agents
Proofing Agent feedback is collected prior to the start of the pilot and at the pilot’s completion
Pain points in Veteran experience and flow are identified
Pain points in Proofing Agent experience and flow are identified
Attitudes and receptivity to in-person identity verification are collected for Veterans
Attitudes and receptivity to in-person identity verification are collected for VA Staff

**Comment by SophiaPhilipMO** [comment]
Mentioned in [IPP Pilot proposal](https://docs.google.com/document/d/1p_fGqtrLOz3UyINsNP0riSEGEWNbC9_FgJJ8A0G0kYg/edit)

**Comment by SophiaPhilipMO** [comment]
@lmorris3 ready for review
