### ISSUE TITLE
Request for elevated DataDog permissions

### ISSUE THREAD

**Issue by JRRoof** [department-of-veterans-affairs/va.gov-team#62803]
The Appointment team engineers who are responsible for monitoring the production deployment of VA online scheduling require write access to DataDog in order to trouble shoot alerts and issues with the application and environment.  The following members of our team require access:

AJ Magdub - [Ahmed.Magdub@va.gov](mailto:Ahmed.Magdub@va.gov)
Corey Ferris - [Corey.Ferris@va.gov](mailto:Corey.Ferris@va.gov)
Jeffrey Roof - [Jeffrey.Roof@va.gov](mailto:Jeffrey.Roof@va.gov)

**Comment by lindsay-insco** [comment]
Tagging @little-oddball to assist with reviewing the request.

**Comment by lindsay-insco** [comment]
Elevated privileges were granted. Discussion finalized [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1690569141923589)
