### ISSUE TITLE
STEM-1995: Eligibility Summary Update

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#6280]
@WillMcCormack commented on [Thu Feb 27 2020](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/20107)

As a Veteran, I need the eligibility summary page hidden if I do not answer the benefit question but answer the remaining questions that meet the eligibility criteria so that I am not deterred from applying for the STEM program. 

## Assumptions:

1. This work will be completed behind a production / feature flag so that it is only available in the staging environments and below.

## Acceptance Criteria

1. The user does not make a selection on the benefit selection page [Question text: Which benefit are you currently using or have you recently used? ]
2. The user progresses to the Rogers STEM Scholarship Screen of  Form 22-1995
3. The user answers Yes to "Are you applying for the Rogers STEM Scholarship" question
4. The user answers Yes to "Are you enrolled in a science technology, engineering, or math (STEM) undergraduate degree program?" OR to the "Do you have a STEM undergraduate degree and are now pursuing a teaching certification?" question.
5.  The user answers Yes to "Have you used all of your Post-9/11 GI Bill or Fry Scholarship benefits or do you have less than 6 months of benefits left?"
6. The user clicks continue
7. Eligibility Summary Page is hidden
8. The user proceeds through the form
9. Eligibility Summary Page is hidden in Application Review

![image.png](https://images.zenhubusercontent.com/5b51ea398c1a7628d9218a42/73692419-8c4d-44a3-8ca8-936b97a6fc09)

## Supporting Artifacts:

1. [Prototype](https://bahdigital.invisionapp.com/share/9GIACS4WX82#/screens)
2. [Content Document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/design/22-1995-stem-content-doc.md)
3. [Process flow for Summary Page display](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/VA-Form-22-1995-Process-Flow-for-STEM-Pages-Only-021020.pdf)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/11783

**Comment by delli-gatti-michael** [comment]
Local testing passes

### With no benefit selected, the Eligibility requirements page does not display when the other two requirements are met
![6280](https://user-images.githubusercontent.com/45575003/75581430-715f6600-5a37-11ea-8705-c65c7201765f.gif)

---

### The eligibility requirements page does not display on the summary page
![Screen Shot 2020-02-28 at 2 32 59 PM](https://user-images.githubusercontent.com/45575003/75581433-745a5680-5a37-11ea-9645-c184cea6e0df.png)

**Comment by delli-gatti-michael** [comment]
TestRail Test Case https://dsvavsp.testrail.io/index.php?/tests/view/1282&group_by=cases:section_id&group_order=asc&group_id=51

**Comment by delli-gatti-michael** [comment]
Changes are live in Staging. Closing this issue
