### ISSUE TITLE
Accessibility Testing for [Public Websites, Income Limits]

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-team#62818]
### Product information

- [X] Team name, product name, and feature name have been added to the title of this issue.
- [X] Team label, product label and feature label (if applicable) have been added to this issue.

### Who completed the use of color and color contrast test?

@laflannery 

### Use of color and color contrast checks

- [x] All text of 20px or smaller has a 4.5:1 contrast ratio to its background (or better)
- [x] All text of 20px or larger has a 3:1 contrast ratio to its background (or better)
- [x] Non-text elements have a 3:1  contrast ratio to their background and to neighboring elements (or better)
- [x] Color is not the only way to distinguish links from other text (eg. links are underlined)
- [x] Any charts, maps, infographics, and tables convey all information without only relying on color
- [x] Content does not refer to color, especially when providing user instructions (eg. "Click the blue button")

### Who completed the axe scans?

@laflannery 

### axe checks

- [x] Each page has been scanned using axe (results shared below)
- [x] axe is integrated into your end-to-end testing

### axe DevTools scan results

This is a screen shot of just one of the pages but there were no issues from axe on any of the pages
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/106678594/f97ec403-3a64-4040-a601-1f4d0e36735d)

### Who completed the content zoom and reflow test?

@laflannery 

### Content zoom and reflow checks

- [ ] All page elements are readable and usable at 200% zoom
- [ ] All page elements are readable and usable at 300% zoom
- [ ] All page elements are readable and usable at 400% zoom

### Who completed the keyboard navigation test?

@laflannery

### Keyboard navigation checks

- [x] Each link, button, form input, checkbox, radio button, select menu, and custom element can receive keyboard focus
- [x] Each link, button, form input, checkbox, radio button, select menu, and custom element responds to expected keys
- [x] All elements under focus have a visible focus indicator
- [x] The order of [Tab] stops made sense and was appropriate for completing tasks

### Do you have any other results to share?

There are issues that were found that have been ticketed, those can be seen [here](https://github.com/department-of-veterans-affairs/va.gov-cms/issues?q=is%3Aopen+is%3Aissue+label%3A%22Income+limits+app%22+label%3Aaccessibility).

At least one of these issues is a DST issue that will need to be resolved upstream.

**Comment by laflannery** [comment]
Note: Income Limits is the product but that label doesn't exist yet in this repo and I wasn't sure if I was supposed to add it or not so that is why there is no product label

**Comment by wesrowe** [comment]
Product has launched and collab cycle ticket is closed, I presume that I can close this ticket.
