### ISSUE TITLE
GIDS: Research why Institutions search by ID endpoint is taking longer than it should

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#6281]
As a developer, I need to research the performance of the institutions search by ID API Endpoint is taking a significant amount of time, so that appropriate performance improvements can be taken to improve performance and stability of the application.

## Assumptions:
1. This story is specific to the [official search by ID] API Endpoint

## Acceptance Criteria:
1. Recommended improvements are documented on this story so they can be included in a future implementation story.

## Supporting Artifacts:
1. N/A

**Comment by dmccurdybah** [comment]
Recommended solution:

- Add index on `institutions.parent_facility_code_id`
- Remove unnecessary query of version from `api_controller.rb` when there is no version ID parameter
