### ISSUE TITLE
Update the URL and title page for the COVID-19 vaccine appointment workflow - Appointment Details page (MHV on VA.gov)

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#62826]
## Description
The Appointments application will be under the MHV on VA.gov portal. We will need to update the title page and URL structure. #62826 will focus on the COVID-19 vaccine appointment details page. 

---

## Acceptance Criteria
Background: the `va_online_scheduling_breadcrumb_url_update` toggle is on

- [x] Given the user is on Upcoming VA appointments homepage,
And the user clicks on `Details` for their upcoming COVID-19 appointment details, then the URL will be https://va.gov/my-health/appointments/[ID]

- [x] Given the user is on Upcoming VA appointments homepage,
And the user clicks on `Details` for their upcoming canceled COVID-19 appointment details, then the URL will be https://va.gov/my-health/appointments/[ID]

- [x] Given the user is on Past appointments view,
And the user clicks on `Details` for their past COVID-19 appointment details, then the URL will be https://va.gov/my-health/appointments/past/[ID]

---

Given the user is on `Upcoming VA appointments` homepage, 
And the user clicks on `Start Scheduling` button for COVID-19 vaccine appointment, then page title will be `VA appointment on [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

- [x] Given the user is on Upcoming VA appointments homepage, 
And the user clicks on `Details` for their upcoming COVID-19 appointment details, then page title will be `VA appointment on [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

- [x] Given the user is on Upcoming VA appointments homepage,
And the user clicks on `Details` for their upcoming canceled COVID-19 appointment details, then page title will be `VA appointment on [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

- [x] Given the user is on Past appointments view,
And the user clicks on `Details` for their past COVID-19 appointment details, then page title will be `VA appointment on [Weekday], [Month] [DD], [YYYY] | Veterans Affairs`

### Reference
[Copy doc - COVID-19 workflow - upcoming appointment details](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/appointment-details.md#va-in-person-vaccine-appointment---upcoming)
[Copy doc - COVID-19 workflow - upcoming canceled appointment details](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/appointment-details.md#va-in-person-vaccine-appointment---canceled)
[Copy doc - COVID-19 workflow - past appointment details](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/appointment-details.md#va-in-person-vaccine-appointment---past)
[Spike ticket #54757](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/54757)

### Design Assets
[Title tag format guidance](https://design.va.gov/content-style-guide/seo#title-tags)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by ldelacosta** [comment]
@young1205 - please have the UX team validate this ticket when it's ready cc: @JRRoof @outerpress

**Comment by Cieramaddox** [comment]
@young1205  This has been validated by the UX team.
