### ISSUE TITLE
GIDS: Research query optimization for institutions_programs

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#6282]
As a developer, I need to research the performance of the institutions and institutions_programs queries, so that appropriate performance improvements can be taken to improve performance and stability of the application.

## Assumptions:
1. As part of this research, generate a large number of programs to test against. 

## Acceptance Criteria:
1. Recommended improvements are documented on this story so they can be included in a future implementation story.

## Supporting Artifacts:
1. N/A

**Comment by elder-joseph** [comment]
### Overview
Closing this issue after testing the performance of the `institution_programs` related queries.

### Assumptions + setup
During the course of this research, I created a tool that produces large `edu_program.csv` and `program.csv` flat files used to populate a large data set of simulated `institution_programs` in the database. In this case I was able to produce the two previously mentioned files to generate a set of 50000 records for clearer indications of performance improvements or worsening.

### Testing
There are already existing indices on all of the affected tables in this story, and removing them or adding additional indices, had no real effect on the averaged performance of the queries being executed, even considering the relatively large data set.
