### ISSUE TITLE
Perform a System Audit and Remove Unused User Accounts

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#62836]
## Background
Request from ATO folks:

> Part of our artifact gathering effort is to ensure that CIE performs regular annual user account audits. These amount to reviews where the team removes no-longer in use user accounts, documents the process, and conducts the activities to do so.

> To demonstrate compliance with this procedure the team can create a GitHub ticket and run through the process of reviewing user accounts and deactivating out of use ones. The team can attach screenshots and commentary regarding the endeavor to the GitHub ticket. Once the process is complete we will save a copy of the ticket and use that as an artifact. The other option is that we can initiate the process of reviewing the accounts and provide guidance via email. Once the team has completed the audit you can reply to that email thread and that can serve as evidence.

## Tasks
- Perform an audit of the Pre-Check-in and Check-in applications and the CHIP & LoROTA APIs and remove/de-activate no-longer in use user accounts
- Document the process & attach documentation to this ticket

**Comment by EthanClarke-J3T** [comment]
Within the scope of this audit are any accounts for which we are responsible and/or have the ability to add/remove/disable/or modify. This includes user accounts, administrator accounts, developer accounts, emergency accounts, temporary accounts, etc. We need to determine if these accounts are still needed. 

_Ex. A developer left the project and still has an account on the system._
This would be an account that needs to be removed, and accounted for in the user account audit.

**Comment by brianseek** [comment]
@EthanClarke-J3T Is this scoped only to accounts that we manage as part of our project/software? For example, I am assuming that this doesn't cover accounts managed by others like GitHub, OKTA, pagerDuty, etc..

**Comment by brianseek** [comment]
@EthanClarke-J3T we do have AWS access that is provided via elevated privileges and a zero account token. Is AWS access part of this? If yes do you know how to perform that audit of AWS

**Comment by EthanClarke-J3T** [comment]
The audit includes all accounts that are in the control of the application team. This would potentially include pagerDuty, OKTA and other tools not directly a part of CIE but used in the development and maintenance of the system. While admins may not have control over GitHub accounts directly, they do have control over repo access and that permission management would fall within the scope of this review as well. AWS as described would certainly be included. Feel free if you have any questions to reach out to schedule a quick conversation. 

v.r.,

ec

**Comment by brianseek** [comment]
@EthanClarke-J3T I think a quick conversation would be great, I'll ping you on slack to coordinate something.

**Comment by brianseek** [comment]
work started and will roll over to next sprint to be completed after an example is provided.

**Comment by loripusey** [comment]
@EthanClarke-J3T can we get that example? we'd like to knock this out this sprint

**Comment by EthanClarke-J3T** [comment]
@brianseek @loripusey 

I have found an example of a user account audit housed in CIE's eMASS and routed it to Brian Seek. 

I attended a meeting with Tsegay Gebremedhin, the DevSecOps System Steward for CIE. He essentially said that there is no standard format for presenting the user account audit. I would advise that it should generally include a summary of accounts requiring action, what action is to be taken, and demonstrate that action is taken to review and update accounts. You can also broadly describe what is being done on this GitHub ticket and include appropriate screenshots (that do not include PII/PHI or sensitive data), we can use this ticket as evidence.

**Comment by brianseek** [comment]
here is the document: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/Reports/user-account-audit.md

After feedback from the team and Ethan, this is what we have come up with.

@loripusey could you help fill in the last TBD items in the doc? I think this is good to close after that.

**Comment by brianseek** [comment]
@loripusey I think this can be closed
