### ISSUE TITLE
Technical spike - Passing validated attributes from IPP process to Login.gov for consumption 

### ISSUE THREAD

**Issue by porta-antiporta** [department-of-veterans-affairs/va.gov-team#62830]
# Supporting use case
* As a Veteran who recently completed the in-person proofing process at a VA facility, I want to obtain a Login.gov verified account so that I have a modern credential I can use at VA and other federal agencies

# Background

In order to preserve privacy and security of Veterans' personally identifiable information (PII), we want to minimize the amount of time our IPP application is holding validated PII. However, we cannot simply pass it to Login.gov because Login.gov protects PII in a very particularyway. 

Login.gov has implemented a double layer of encryption on validated PII.
1. "Standard" KMS encryption for its entire data store.
2. "Row level" encryption where each users' PII bundle (Name, DOB, SSN etc) is encrypted with the user's password (and a second copy is encrypted with a personal key to aid in account recovery when a password reset is triggered.

This second level of encryption ensure that not even Login.gov personnel with root level access to their cloud infrastructure can exfill account holders' PII.

As a result, our IPP application cannot just send PII over to Login.gov without Login.gov having the user's password in context.

# Login.gov PII bundle

The attributes that Login.gov protects with this double layer of encryption are located on the [attributes page of their Login.gov developer documentation](https://developers.login.gov/attributes/).

For convenience they are listed here:

* Name
* DOB
* SSN
* Address
* (optional) phone number

These are the set of attributes required to be sent to Login.gov in order for Login.gov to establish an identity verified Login.gov account. The phone number is optional because when verifying identity remotely at Login.gov, the applicant can select to validate their address via a physical letter sent to their address.

# Login.gov RISC events
Login.gov also supports [RISC events](https://developers.login.gov/security-events/) by which non sensitive, i.e. absent CUI (Controlled Unclassified Information) such as PII information can be sent. For example, RISC framework could be used to send Login.gov "type of evidence used" but not "driver's license #).  Given the payload of RISC events are by design devoid of CUI, Login.gov does not require that second level of encryption.

This is mentioned as a general information. From the workshop on 7/27, Login.gov did not request any metadata around the IPP event. But this can be used at a later time if that information were needed to be sent.

# Possible options

The [notes document from the IPP workshop](https://docs.google.com/document/d/1SUl3DC1FAnOtQlGhKU-5J9V2t5OnEYF4FGY1JuvBQSQ/edit) on 07/27/2023 has options put forth in the discussion.
These are not meant to be the only options to be considered, just those that have been thought of thus far.

# Acceptance Criteria

- [x] 1 pager on technical approach to pass Login.gov verified PII from our IPP flow
- [x] Concurrence from Login.gov on the approach
- [x] An understanding of what changes are needed in Login.gov vs. our IPP application
- [x] Tradeoff analysis with the following lens
   - Technical merit
   - Effort
   - Timing / dependency

**Comment by djmunoz1** [comment]
qs to explore: consider using OpenID

**Comment by porta-antiporta** [comment]
The options (including which is preferred) is now present in the [product brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/login.gov-adoption/products/in-person%20support/product-brief.md)

**Comment by porta-antiporta** [comment]
The options (including which is preferred) is now present in the [product brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/login.gov-adoption/products/in-person%20support/product-brief.md)
