### ISSUE TITLE
GIDS: Research improve indexes for GIDS tables

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#6283]
As a developer, I need to research the indexes on the GIDS tables, so that appropriate index improvements can be created to improve performance and stability of the application.

## Acceptance Criteria:
1. Recommended improvements are documented on this story so they can be included in a future implementation story.

## Supporting Artifacts:
1. N/A

**Comment by dneel-bah** [comment]
At this time all indexes that would provide a noticeable impact to the end user have been added.  Closing this story out as OBE as no additional research / work is necessary at this time.
