### ISSUE TITLE
Collaboration Cycle - Needs a workflow/process map

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#62845]
### Description
[This page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/) while offering a "flow image":
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/dc889bd3-ad6c-4cc7-8568-9bfd8e914ed6)

as a relatively new joiner, the process is VERY opaque. One thing from prior jobs that I'm used to seeing is a process map that's more detailed with swim-lanes to call attention to specific responsible parties to help a new person understand a complicated process. 

While the documentation is thorough for each specific item eg, questions you have to answer for a kickoff ticket, there's not something that delineates responsibilities and steps and the stages when those things should occur. Even for a more experience folks, this would help elevate everyone's understanding of the process and might help increase engagement at the 'right' times. 

### Relevant URLs
https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/

### Which type of team are you on? (Platform team, VFS team, or Leadership)
VFS Team - AE profile

**Comment by vbellissimo** [comment]
Hi @mtcA6 , thanks for your feedback. We'll take a look for any next steps.

**Comment by mtcA6** [comment]
Thanks! Is it safe if I close this?

**Comment by mtcA6** [comment]
@shiragoodman This may be a talk ask... but is there a copy I could get of the mural where i could make edits? I'd like to at least be able to download the content and upload it to my VA Mural account to noodle on it and make my own notes

**Comment by shiragoodman** [comment]
let me look into this and I will follow up @mtcA6

**Comment by allison0034** [comment]
Hi @mtcA6 , I made a [copy for you](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1690902677349/6922e2a045ba8ca9f628c1a7b83dfdb9f7a79cf7?sender=u045df875f30f7e9f34339908) that you can edit. When you are finished let me know. I would love to see if there are things in our Mural we can improve.

**Comment by mtcA6** [comment]
@allison0034 of course!

**Comment by vbellissimo** [comment]
Closing this ticket per governance team chat. Thank you all.
