### ISSUE TITLE
STEM: Update logic related to STEM yes/no on 22-1995 Summary Page & Spool File

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#6284]
## Issue: 
1. In the 22-1995, select answers that make you ineligible for the STEM scholarship and then answer "No" to "Since it appears you're not eligible for the scholarship, would you still like to apply and let us determine your eligibility?(*Required)" on https://staging.va.gov/education/apply-for-education-benefits/application/1995/benefits/stem-eligibility 
2. On the 22-1995 summary page, the summary shows "Yes" as the answer to the "Are you applying for the Rogers STEM Scholarship?" in the Benefits section. 
![Screen Shot 2020-02-28 at 9 05 39 AM](https://user-images.githubusercontent.com/41790951/75555107-9b019880-5a09-11ea-8d1d-11894aa350c2.png)
![Screen Shot 2020-02-28 at 9 05 25 AM](https://user-images.githubusercontent.com/41790951/75555121-9f2db600-5a09-11ea-8947-cc637d6f7d9b.png)

## Assumptions: 
1. Answering No to Since it appears you're not eligible for the scholarship, would you still like to apply and let us determine your eligibility?(*Required) on /benefits/stem-eligibility is the same as answering No to Are you applying for the Rogers STEM Scholarship?(*Required) on /benefits/stem

## Acceptance Criteria: 
1. If a user answers "No" to "Since it appears you're not eligible for the scholarship, would you still like to apply and let us determine your eligibility?(*Required)" then
a. The 22-1995 summary page displays "Are you applying for the Rogers STEM Scholarship? Yes"
b. The spool file reflects that the applicant is NOT applying for STEM

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/11783

**Comment by delli-gatti-michael** [comment]
Local testing complete

### Summary Page
![Screen Shot 2020-02-28 at 1 39 59 PM](https://user-images.githubusercontent.com/45575003/75577396-e62ea200-5a2f-11ea-9f6b-a92f4bf73d3a.png)

---

### Spool File Entry
![Screen Shot 2020-02-28 at 1 38 27 PM](https://user-images.githubusercontent.com/45575003/75577408-e9299280-5a2f-11ea-972d-09c97a7ab641.png)

**Comment by delli-gatti-michael** [comment]
TestRail Test Case
https://dsvavsp.testrail.io/index.php?/tests/view/1283&group_by=cases:section_id&group_order=asc&group_id=51

**Comment by delli-gatti-michael** [comment]
The following submissions were made on 3/3/20 and should be present with "NO" for "Are you applying for the Rogers STEM Scholarship?" in the spool file generated on the morning of 3/4/20:

- V-EBC-4431
- V-EBC-4432

**Comment by delli-gatti-michael** [comment]
The above submissions are shown as expected in the staging spool file. Closing this story
