### ISSUE TITLE
STEM: "would you still like to apply" question should be required

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#6285]
In the Stem application workflow, there is a series of questions to determine whether or not an applicant is eligible. If it is determined that the applicant is not eligible, they are given a message explaining why and are asked if they still want to apply. This question is indicated as "required" but if it is not answered, the applicant can still continue to the next page. 

1. Start the STEM application at https://staging.va.gov/education/apply-for-education-benefits/application/1995/introduction
2. On the Rogers STEM Scholarship page, answer yes to `Are you applying for the Rogers STEM Scholarship?(*Required)` and No to all other questions
3. On the eligibility page, do not provide a response to `Since it appears you're not eligible for the scholarship, would you still like to apply and let us determine your eligibility?(*Required)` and click continue

The user should be unable to continue and should receive a "Please provide a response" error message if the question is unanswered

![ezgif.com-video-to-gif.gif](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/91bb8ac1-d7d0-48cd-9cf9-8282317cf3cb)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/11783

**Comment by delli-gatti-michael** [comment]
The question is now required. Local Testing complete


![Screen Shot 2020-02-28 at 1 19 10 PM](https://user-images.githubusercontent.com/45575003/75574795-ed07e580-5a2c-11ea-8dac-16cccc3abe18.png)

**Comment by delli-gatti-michael** [comment]
Changes are now live on Staging. Closing this issue
