### ISSUE TITLE
Label guidance in Collaboration Cycle Kickoff

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#62856]
## User Story
As a Governance team member, I want better consistency with VFS labels on Collaboration Cycle Request tickets so that I can track team, product, and feature data in our domo dashboards.

Assignee: @briandeconinck 
Peer Reviewer: @allison0034 

## Description
The [VFS Product Directory ](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory)was supposed to replace Governance teams need to collect Github labels for VFS team, product and feature within the Collaboration Cycle. However, the Product Directory has not been regularly maintained/updated by VFS teams and is unreliable. Governance team still needs to collect team, product and feature labels in the Collab Cycle Request ticket. 

This ticket will address the following:

- Collect the gh team label (currently we only collect the product and feature label)
- If a VFS team does not have a gh team, product and/or feature label, we will need to assign one.
- We need to ensure that all 3 labels are added to the Collaboration Cycle Request ticket, preferably by the VFS team, however we will need to verify

## Impacted Artifacts
[Collab Cycle request yaml](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/collaboration-cycle-request.yml)
[Collaboration Cycle Kickoff - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities)

### Collab Cycle Request YAML
- [x] Add a new required field in the CC request yaml template for GitHub label for VFS team
- [x] Add a step at the bottom, requesting the VFS team add their gh team label, gh product label and gh feature label to the Collab Cycle Request template
- [x] Submit for peer review
   - PR #70642 

### Collab Cycle Kickoff- Moderator Responsibilities
- [x] In Step 4: Add GitHub ticket metadata, we need to add a new step for verifying GitHub labels
   - [Draft with updates to Step 4](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2849341441/62856+-+Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities#Step-4:-Add-GitHub-ticket-metadata)
- [x] The VFS team label, product label, and feature label should be added to the CC request ticket by the VFS team, however if they aren't, then we need to do it.
- [x] If a VFS team specifies N/A for either their team label or product label, then we need to create one for them or identify if a label already exists for the product or team
   - [x] If we identify a label already exists for the product or team, add the team and/or product label to the CC Request ticket
   - [x] If we cannot identify a label, then we need to create one. Team labels and product labels should be short and direct, without spaces and with hyphens, if necessary. If the product is for a form, it should use the form number/letters and not the common name. 

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] VFS teams communicate their gh team label to us
- [ ] VFS teams are directed to add their gh team, product and feature labels to their new CC request tickets
- [ ] Governance team members add the gh team, product and/or feature labels to the CC Request ticket when the VFS team has not completed this step
- [ ] Governance team member create new gh labels for the team or product (not feature) when necessary, and ensure they are added as labels to the CC request ticket

### Refinement
- [ ] Ticket has user story, description, tasks, and acceptance criteria
- [ ] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [ ] Ticket has been sized 
- [ ] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
This ticket was planned for the Nov 9-21 sprint, however, due to bandwidth,  it was not picked up by the team. Will move to next sprint.

**Comment by briandeconinck** [comment]
@allison0034 This is ready for review!
- PR #70642
- [Updated Step 4 in the kickoff guidance](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2849341441/62856+-+Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities#Step-4:-Add-GitHub-ticket-metadata)

One question for you and for @shiragoodman: There's a scenario not addressed here. Looking at #65707 as an example (but I feel like this is pretty common), Lindsay provided a product label that matches the team name and not the product, `accredited-representation-management-team`. I'm guessing if we asked for the team label too she'd give us the same thing for that field. Do we:
1. Add specific instructions to the yaml form that they need to be different labels?
2. Create our own distinct label if a team submits duplicate labels anyway?
3. Not care?

**Comment by shiragoodman** [comment]
@briandeconinck that's a good question. I think we need to go with option a - add instructions stating they need to be different labels. The reason for this is bc it's possible an issue at a Staging Review might not be the responsibility of the team the SR is for. We see this often with DST. If a team and product label are one in the same, and we remove the VFS team label and add the DST label (indicating it's the responsibility of DST), then we'd either be a) removing the product label too - not good, or b) having 2 team labels on the ticket, making it unclear who is responsible.

Let me know if you'd like to discuss further!

**Comment by allison0034** [comment]
@shiragoodman @briandeconinck I want to push back a little on this...

- The VFS team label, product label, and feature label should be added to the CC request ticket by the VFS team, however if they aren't, then we need to do it.

I disagree. We are not their babysitters and I think we hold their hands a little too much. I think we need to respond and ask them to add them if they are missing. The whole "teach a person to fish" idea.

**Comment by allison0034** [comment]
Same for this one...

-  If a VFS team specifies N/A for either their team label or product label, then we need to create one for them or identify if a label already exists for the product or team
Why are we creating labels for them?

**Comment by shiragoodman** [comment]
thanks for pushing back on this @allison0034 . As discussed in standup, we will use the product and team labels provided by the VFS team. If they don't provide one (or provide N/A) then we need to ask them to provide one instead of coming up with one ourselves. FYI @briandeconinck . Let me know if you'd like to discuss further.

**Comment by briandeconinck** [comment]
@allison0034 I've updated based on our conversation to shift more responsibility to the VFS PM. I've kept "we create the label" as a last and final step if the PM just refuses to provide a label but that's hopefully not going to come up!

**Comment by allison0034** [comment]
@briandeconinck this is good to close.

**Comment by shiragoodman** [comment]
thank you both!
