### ISSUE TITLE
Best bet request for Reporting Harassment at VA

### ISSUE THREAD

**Issue by artsymartha68** [department-of-veterans-affairs/va.gov-team#62852]
# Template Instructions
- You are here to createor change a Best Bet on VA.gov pages.

 -  Select Request Type:
    - [x] NEW: You would like to create a new best bet
    - [ ] CHANGE: You would like to change an existing best bet

- Post a link to this issue in Slack Channel #sitewide-content-ia and tag  @Jenny Mayo

### Description
Please provide a description and supporting information for the new best bet, or the existing best bet you want to change. Include any research or data you have to support the request. 

 - The new page for reporting harassment at VA does not appear until page 2 when I search for "harassment" on VA.gov. Do we want this to be a Best Bet?  https://www.va.gov/report-harassment/

###  Target Dates
Do you have any target dates we should be aware of?

 - na/
 
### Specify the target page for the Best Bet 
What is the destination page for the best bet?
       
- https://www.va.gov/report-harassment/

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

***Note: All requests will be reviewed against the [Search best bet standards](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/standards/search-best-bets.md) by the Sitewide Content, Accessibility, and IA team. Reach out via Slack #sitewide-content-ia with any questions.***

**Comment by jennymayoco** [comment]
Hi @artsymartha68! Here are our recommendations for this best bet. We agree a best bet would help highlight this page, which is such an important resource for folks. We plan to review and adjust keywords as needed as we learn more from analytics. Let us know if there are any questions!

#### Recommendations
- Since the word “harassment” is in the H1 and metadescription, we suggest instead adding “harrassment” as a keyword to comprise common misspellings.
- We also suggest adding keywords that are similar to the H1 text as folks may use other terms for their search. These are:
    - rreport assault
    - file complaint
    - sexual harassment
- Update ORMDI page best bet
    - The ORMDI page has a current best bet that includes the keyword “harassment” as well as “harrassment”. We are archiving the existing
    best bet and replacing it with a new one to direct to the HPP page
    - This page is still important for VA employees so we believe updating it will ensure that employees are still able to find the necessary resources for workplace-specific harassment
    - These are all the current keywords:
        - discrimination
        - diversity - removing to keep focus on defining harassment and how to report
        - harassment
        - harrassment
        - Resolution Management - removing to keep focus on defining harassment and how to report
        - workplace harassment - adding to distinguish this page specifically to VA employees

#### Implementation
- [ ] Create a best bet for the new reporting harassment page and update with the shortened metadescription provided by @megzehn 
- [ ] Add keywords
- [ ] CAIA team is planning a SEMrush training and so we will review this best bet afterwards and see if there’s any updates we can make to the keywords based on those analytics
- [ ] Take down existing ORMDI best bet and create a new one with updated description, link, and keywords

**Comment by jennymayoco** [comment]
Hi @artsymartha68, I wanted to check in on this best bet to see how it's been performing. We haven't received SEMrush training at this time so this update is only informed by GA. This best bet will continue to remain on our radar and I've made note of this in our team's hive mind meeting notes. Some quick updates on this:

- Top 5 searches (7/1/23-11/3/2023)
   - Sexual assault - 6
   - Sexual harassment - 4
   - Reports - 2
   - Assault - 1
   - File complaint - 1
- The top search keywords are already in the best bet so we don't have any new suggestions. "Reports" can refer to many other situations, such as "report of contact", "report a death", "blue button report", "report death", and "financial status report", pulled from the same date ranges on GA. As such, we don't recommend adding "reports" as a keyword.

**Comment by artsymartha68** [comment]
Thanks so much for the detailed update.

From: jennymayoco ***@***.***>
Sent: Friday, November 3, 2023 1:25 PM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Wilkes, Martha A. (she/her/hers) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Best bet request for Reporting Harassment at VA (Issue #62852)


Hi @artsymartha68<https://github.com/artsymartha68>, I wanted to check in on this best bet to see how it's been performing. We haven't received SEMrush training at this time so this update is only informed by GA. This best bet will continue to remain on our radar and I've made note of this in our team's hive mind meeting notes. Some quick updates on this:

  *   Top 5 searches (7/1/23-11/3/2023)
     *   Sexual assault - 6
     *   Sexual harassment - 4
     *   Reports - 2
     *   Assault - 1
     *   File complaint - 1
  *   The top search keywords are already in the best bet so we don't have any new suggestions. "Reports" can refer to many other situations, such as "report of contact", "report a death", "blue button report", "report death", and "financial status report", pulled from the same date ranges on GA. As such, we don't recommend adding "reports" as a keyword.

-
