### ISSUE TITLE
Demo:  current Digitization RI state and snapshots

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#62868]
## Purpose
Demo our ongoing learnings and thoughts

## Tasks
- [x] Create [demo deck](https://docs.google.com/presentation/d/1mhOFvctG1FUUWI73YPWl00ZpUx8O6ZRT2krp5mP7q5E/edit#slide=id.p1)
Ready for review [here](https://docs.google.com/presentation/d/1HWfY7PqYC3JH4V-bv7YSj0WAGFKr6G9BIQIjteVrY0E/edit#slide=id.p1)
- [x] Deliver demo

## Acceptance Criteria
- [x] Deck is ready
- [x] Demo shared.

**Comment by twoangstroms** [comment]
Demo is shared on Wednesday, so this ticket will roll over

**Comment by twoangstroms** [comment]
Right, PHANTOM ZONE!
