### ISSUE TITLE
Analytics Implementation or QA Support for [Authenticated Experience My VA - My VA, Benefit Application Drafts section

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#62875]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

</div>
</details>

### Required
- **Is this request for **Google Analytics implementation** or **QA**?**

     - [X] Google Analytics implementation
     - [ ] QA

- **Who is this request for?**

    -  Authenticated Experience My VA
    - This is not a new feature but a subsection we recently learned did not have click tracking on it.
    
    
- **Provide the link(s) for Google Analytics implementation or QA**
 
    1. Navigate to va.gov (or staging.va.gov)
    2. Log in (or log in with a staging user)
    3. Once on My VA (va.gov/my-va or staging.va.gov/my-va), scroll to the Benefit Application Drafts section
    4. Expand the sub-header "What benefits does VA offer?"
    5. See the list of links that starts with "Health care" and ends with "Family member benefits" - that entire list needs to have click tracking on it.

![Screenshot 2023-07-31 at 2 15 00 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/45603961/ea8ba0e6-151d-452d-9c0c-0742f3b29b37)

    
- **When is the launch date?**
    - ASAP - whenever we're able to get tracking created and implemented on our side

- **What interactions need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked_
    - click tracking 

### Optional
- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - Any LOA3 test user 

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by michelle-dooley** [comment]
@ajakabcin - thank you for your submission.  I will review with our new GTM specialist next week.  There is a bit of a backlog in front of this so I will have to get back to you with timing.
