### ISSUE TITLE
NOD | Improve veteran UX for intermittent errors

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#62872]
## Issue Description

We get a number of intermittent errors on the contestable_issues#index endpoint and nod#create endpoints, including 503s and 504s. The 504s appear to be momentary errors, whereas the 503s appear to be the results of multi-hour outages. These are the kinds of errors that we can't prevent, so we just want to improve the veteran's UX around them.

For momentary errors, we can re-design our requests on the front end to automatically retry, maybe up to three times. For extended periods of outages or timeouts, we could render an error message asking the veteran to retry later (unless we are already doing that).

## Design & Build Notes
- [DESIGN](https://www.sketch.com/s/0424c51d-7818-43ea-8821-6de91eb7ab27/a/qbAvv22)
- This error should only show if we load issues. If the Veteran has no issues on file, show the default error message.
- Changed the language in the body to: These are the issues we have on file for you. If you don’t see the issue you want us to review, you can add a new issue.

## Definition of Ready

- [ ] For both endpoints, check whether error message exists, and if so, whether it shows an appropriate error message
- [x] Get feedback / approval from design on proposed resolution

## Definition of Done

Assuming design/engineering agrees on the proposed resolution above:
- [ ] We retry requests that 503, 504, or otherwise return an error that could be intermittent
- [ ] We display error messages when retries don't result in a successful request
- [ ] Those error messages have an appropriate CTA for the veteran

## Front end tasks
- Ensure the page is styled according to design spec. 
- Ensure the back end data from API is displayed in local and review instance
- Ensure unit tests are available. 
- Ensure your code changes are covered by E2E tests
- Run axe checks using the Chrome or Firefox browser plugin
- Test for color contrast and color blindness issues
- Zoom layouts to 400% at 1280px width
- Test with 1 or 2 screen readers
- Navigate using the keyboard only

## Acceptance Criteria
- [ ] Retryable
- [ ] Updated error messaging 
- [ ] Unit tests pass
- [ ] E2E tests cover current code and regression
- [ ] End-to-end tests show 0 violations.
- [ ] The data returned matches API response (for given user or scenario)
- [ ] All axe checks pass
- [ ] All color contrast checks pass
- [ ] All zoom testing passes
- [ ] All keyboard checks pass 
- [ ] All screenreader checks pass

## Appendix
<details> 

 <summary>Ensure your code changes are covered by E2E tests (expand)</summary>
 
 - Add E2E tests if none exist for this addition/change. 
 
 - Update existing E2E tests if this code will change functionality. 
 
 - Include axe checks, including hidden content
 
</details>

<details> 

 <summary> Run axe checks using the Chrome or Firefox browser plugin (expand)</summary>
 
- Ensure no heading levels are skipped.

- Ensure all buttons and labeled inputs use semantic HTML elements.

- Ensure all buttons, labeled elements and images are identified using HTML semantic markers or ARIA roles.

- Ensure form fields have clearly defined boundaries or outlines.

- Ensure form fields do not use placeholder text. 

- Ensure form fields have highly visible and specific error states. 

</details>

<details> 

 <summary> Test for color contrast and color blindness issues (expand) </summary>
 - All text has appropriate contrast. 

</details>

<details> 

 <summary> Zoom layouts to 400% at 1280px width (expand)</summary> 
 - Ensure readability and usability are supported when zoomed up to 400% at 1280px browser width
 - Ensure no content gets focused offscreen or is hidden from view.
 
</details>

<details> 

 <summary> Test with 1 or 2 screen readers (expand)</summary> 
 
 - Ensure the page includes a skip navigation link. 
 
 - Ensure all links are properly descriptive. 
 
 - Ensure screen reader users can hear the text equivalent for each image conveying information. 

 - Ensure screen reader users can hear the text equivalent for each image button. 

 - Ensure screen reader users can hear labels and instructions for inputs. 
 
 - Ensure purely decorative images are not announced by the screenreader. 
 
</details>

<details> 

 <summary>Navigate using the keyboard only (expand)</summary> 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be reached with the tab key in a logical order. 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure all interactive elements can be reached with the tab key in a logical order 
 
 - Ensure all interactive elements can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure focus is always visible and appears in logical order.
 
 - Ensure each interactive element has visible focus state which appears in logical order.
 

</details>

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by saderagsdale** [comment]
@Mottie talk to Eugene about number of times to call the endpoint @data-doge

**Comment by Mottie** [comment]
After discussing with @data-doge & @eileen-coforma, this change will involve:
- Add one contestable issue load retry on the contestable issue page (after failed call)
- Update content to "you can come back later" to indicate leaving the form and coming back could resolve the issue.

**Comment by saderagsdale** [comment]
@Mottie add remaining tasks

**Comment by Mottie** [comment]
Ready for testing in staging. Follow these steps to test (sorry it's a little complex, but I can walk you through it if needed):
- Log into any user in staging
- Go to [NOD introduction page](https://staging.va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182/introduction)
- Open the dev tools panel (F12, or right-click & inspect page)
- Go to network ta
- Reload NOD page
- Right-click on `contestable_issues` in the network "Name" column
- Choose "Block request URL" to disable the endpoint
- Reload NOD page
- Start the form & navigate to contestable issues page
- Once on the page, you should see one additional call to the `contestable_issues` endpoint, which will fail because we just blocked the request
- Navigate to the previous page
- Return to contestable issues page
- Note that the `contestable_issues` endpoint was only called once on the contestable issues page

**Comment by eileen-coforma** [comment]
Confirmed that this works, and the error message is correct.
