### ISSUE TITLE
Update message shown when request or appointment submission fails

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#6288]
@lenaecb @jbalboni  Here's the updated message adding a link to their local VA medical center. 

One followup question: are we able to provide the phone number to the medical center or should we direct users to facility locator?

**UPDATED MESSAGE**
**Your {request}{appointment} didn’t go through**
We’re sorry. Something went wrong when we tried to submit your request and you’ll need to start over. We suggest you wait a day to try again or you can call your medical center to help with your request. 

{link}  [Call your local VA medical center](link to facility locator? or to phone number for their local medical center??)

**Comment by jbalboni** [comment]
@peggygannon Can you update the rest of the message here? Let me know if there's more info you need.

**Comment by peggygannon** [comment]
Hi, @jbalboni We need clarification on **where** to send users for help submitting their request. Last I talked to Ryan and Mark about this we didn't have an answer or place to send users. 

Once we have that info, message can be updated.

**Comment by lenaecb** [comment]
User can:
- call facility
- try again later

Reference Facilities page for how we handle issues currently.

**Comment by peggygannon** [comment]
@lenaecb @jbalboni @rtwell I've updated message above ^^ with one question for you all.

**Comment by rtwell** [comment]
@peggygannon if possible, we should provide the phone number for the facility (or VAMC) where they were trying to schedule/request an appt.

**Comment by jbalboni** [comment]
@rtwell @peggygannon Is this too much info?

![Screen Shot 2020-03-06 at 12.41.10 PM.png](https://images.zenhubusercontent.com/599c94608f62dc7798c3b2cd/aeada767-be05-420c-9aa9-2db520364bb9)

**Comment by rtwell** [comment]
i think it's just enough info—there's a phone number to call and I can confirm the location b/c the address is there, and if i'm unfamiliar with the address i can click the link to see which location it's referring in google. love it!

**Comment by peggygannon** [comment]
Hi, @jbalboni Looks good. I agree with Ryan, I think all the important info is there!
