### ISSUE TITLE
Wrong EP code for pre-discharge claims 

### ISSUE THREAD

**Issue by sortizsh** [department-of-veterans-affairs/va.gov-team#62896]
**Issue:** 
Barry Cooper, Program Analyst, received the following message from a national VSO this morning and had a brief discussion with him. He stated pre-discharge claims submitted via SEP are often receiving the incorrect EP at claims establishment. Is this a know issue that is being addressed? Is this something the user needs to file a ticket for or some other action to bring attention to the issue?

The below VSO (VFW) stated they submitted the below BDD claim in SEP today (5/10/23), but it was established as 400 - eBenefits 526EZ-Pre Discharge (400). The below VFW rep. also stated he has submitted other BDD claims that were established as an EP 020 or 010.

I reviewed the below claim and it does meet the BDD requirements. This may be why the NOIs from EVSS (SEP and eBenefits) are being sent to HAIMS labeled as “Pre-Discharge Unknown” or BDD-excluded (submitted 1-89 days before RAD) when in fact they are actually BDD claims (submitted 180-90 days before RAD). Just in case anyone doesn’t already know, BDD claims need to be established with an EP 336 – BDD and BDD-excluded are EPs 010, 020 or 110. There are no prior claims showing in VBMS or current pending claims, so I don’t know why EVSS would establish it as a 400.

**Context:** 
EP (end product) this is a three digit code that is generated in VBMS when a claim is submitted, we use this code (EP 336) to track BDD claims that are submitted, SEP [Stakeholder Enterprise Portal](https://www.sep.va.gov/sep/web/guest/sep) – this is a site that Veterans Service Organizations (VSOs) use to submit claims electronically directly to VA, HAIMS Healthcare Artifact and Image Management Solution (HAIMS) this is the system DoD uses to store Service members (SMs) medical records, and RAD - released from active duty (Service members discharge date

**How the process works:** 
Service Member (SM) submits the claim on [VA.gov](http://va.gov/) or the VSO submits it through SEP, the claim is established in VBMS via EVSS as an end product EP 336, then the notification of interest (NOI) requesting service treatment records (STRs) is sent to DoD via VBMS to DAS (VA intermediary) then to HAIMS (the DoD’s military medical file system). Then, HAIMS will send back the STRs from HAIMS to DAS and into the VBMS eFolder.

Claim ID 99173515
Submitted by VSO on May 10, 2023, 136 days prior to the future RAD/discharge date of September 23, 2023.

Document Properties
Shipping Number:
New Mail: false
Document ID: {63DF9999-CAE2-41AE-8A24-F3683C275056}
Date of Upload: Wed May 10 10:25:49 EDT 2023
Content Source: VDC
Source Comment: {"docSvcVersion":"3.7.127"}
System Source: EVSS
Moved by:

**- Form/Page of Issue:**  Where in the application did this issue occur? - At the end, after the claim is submitted in SEP, the incorrect EP is established, it has been established as an EP 400, 020, 110, etc.
**- How to reproduce:**  Detailed steps on how to reproduce, or a video of the issue: See below, the only way to reproduce is submit a claim on SEP. I do not have access to SEP or the SEP testing environment.
**- Workaround: I**s there a workaround? If so, what is it? No, the claims processor must change the EP. However, we do not know if a new NOI is submitted once the EP is changed.
- Legal Requirement: Does the issue stop someone from meeting a legal requirement? Yes, the STRs must be submitted with the BDD claim.
**- Loss of Service:   Can people lose service as result of the issue?** Yes, their claim may be missed, delayed and/or not processed due to incorrect EPs.
**- Permanent Impact:  Does the problem have a permanent impact?** For instance can you resubmit the form for a veteran, or do you lose the submission entirely? 
**- Can the VSR reopen the case later and process it, or does the issue send out an incorrect message to a veteran?** Yes, because the NOI is labeled wrong and this is a Benefits Executive Committee (BEC) milestone and the VBA chairman is Josh Jacobs, USB.
**- Users Impacted:   How many users are being impacted? # of related cases in the last x days/weeks/month?** All BDD claims
**- Vulnerability:  Is this a potential security/privacy vulnerability?** Yes

**Comment by navaeddie** [comment]
The team(s) were unsure how to address this report. We are waiting for the reporter to provide more information, although they may be unreachable.
Slack message for context: https://dsva.slack.com/archives/C05BDU0HR42/p1690916029935019?thread_ts=1690835358.674839&cid=C05BDU0HR42

**Comment by sortizsh** [comment]
I have added additional context to the ticket, let me know if you have enough information to prioritize now.

**Comment by sethdarragile6** [comment]
-   Impact summary  
    - Description of impact to the veteran/submitter  
	   
	   Veterans who have their BDD claims submitted through SEP are being established with the wrong end product code (should be 336, but instead are being established as 400, 010, 020, or 110, etc.
    - How many users/events (is that including retries)  
     
      Above it says "All BDD Claims", but I would like to get a better answer than that. See slack thread referenced below
    - Is there a workaround? If the submission is failing, is it getting submitted via the paper form?  
       
       No, aside from the claims processor changing the end product code. An NOI *might* need to be regenerated somehow, if changing it doesn't automatically regenerate one
    - Is the failure silent?  
      
      Yes
    - Is this part of downstream back-end exception?
      
      Could be an exception somewhere in EVSS/SEP or VBMS. Claims submitted from SEP only get  posted directly to VBMS ([through VDC](https://dsva.slack.com/archives/C1VBAHWQL/p1692647803674859)), so any relevant exception would be within those systems
-   Severity Assigned ( sev-critical / sev-major / sev-moderate / sev-minor )
  Still unknown. I reached out to Kyle [on this thread](https://dsva.slack.com/archives/C1VBAHWQL/p1692647803674859) to see if I could get better numbers on the user impact, but it doesn't look promising

**Comment by austinjprice** [comment]
thanks @sethdarragile6 ! @NB28VT fyi for review tomorrow in bug triage

**Comment by austinjprice** [comment]
Per discussion with @emilytheis it was determined this is owned by a different group with with SEP (a tool used for VSOs). EVSS team currently has a ticket "EVSS-12382 "Wrong ep Code for Pre-Discharge Claims" to address this problem.
