### ISSUE TITLE
What should happen when the appointment slots fetch fails?

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#6289]
Currently this is what shows if fetching appointment slots fails:

![Screen Shot 2020-02-28 at 10.51.13 AM.png](https://images.zenhubusercontent.com/599c94608f62dc7798c3b2cd/bcc02183-e4fd-4e72-b11c-545317c19e70)

I believe we could:

1. Show our generic error message, or
2. Route users back into the VA request flow

**Comment by rtwell** [comment]
i think we could give users both options. We could surface our error alert box and say something like:

There was a problem loading appointment availability. You can:
• Request an appointment instead (link to request flow), or
• Try again later

@lalexanderson-dsva / @peggygannon thoughts?

**Comment by peggygannon** [comment]
@lenaecb @rtwell Here's content recommendation for this alert: 

@jbalboni Please let me know if this will work? I'm not sure how much VAMC contact information we are able surface/provide to the user, so I might need to tweak that part a bit. 


**We’ve run into a problem when trying to find available appointment times**
 To schedule this appointment, you can [submit a request for a VA appointment](URL to request flow) or [call your local VA medical center](link to local VAMC information)

**Comment by jbalboni** [comment]
@peggygannon That would work, we can get any facility contact info we need, including a link to the facility page directly.

**Comment by jbalboni** [comment]
![Screen Shot 2020-03-19 at 2.46.11 PM.png](https://images.zenhubusercontent.com/599c94608f62dc7798c3b2cd/63353ccb-5f5a-441e-a18c-cf02afd4fb7c)

**Comment by peggygannon** [comment]
@jbalboni Looks good. Thank you!
