### ISSUE TITLE
Infinite load on Track Your Prescriptions static landing page

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/va.gov-team#629]
## What happened?
I go to the static landing page for Track Your Prescriptions (either by entering the URL directly, navigating there from Homepage, or navigating there through menu nav) and get an infinite load symbol under the intro paragraph with the text: "Loading your information"

![image](https://user-images.githubusercontent.com/8680732/61493055-89322000-a967-11e9-9276-c94d1d1ce118.png)

## Specs:
- Device: Macbook, and iPhone 7
- Browser: Chrome, Safari

## Steps to Reproduce
- URL: https://www.va.gov/health-care/refill-track-prescriptions/

## Desired behavior
Something loads in that spot... maybe the login component? IDK what's supposed to be there.

**Comment by rroueche** [comment]
Not sure if this should be handled by VSP Tools Team (since it's maybe an Identity issue), a VFS Team (unsure if there is a known Product Owner for Track your Prescriptions static landing page...), or handled by Triage...

**Comment by rroueche** [comment]
Update: I'm seeing the same bug across static landing pages for all MHV apps:

https://www.va.gov/health-care/schedule-view-va-appointments/
https://www.va.gov/health-care/secure-messaging/
https://www.va.gov/health-care/view-test-and-lab-results/
etc

**Comment by erikphansen** [comment]
I'll take this.

**Comment by kfrz** [comment]
Deployed @erikphansen 's branch this morning, this looks to be resolved.
