### ISSUE TITLE
Design Intent - Accessibility Feedback - VA Integration - Ask VA

### ISSUE THREAD

**Issue by briandeconinck** [department-of-veterans-affairs/va.gov-team#62901]
## VFS actions
- [x] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [x] Comment on this ticket:
  - [x] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [x] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [x] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- I think you've got the right priorities, and you're already working with the CAIA folks. Looking forward to seeing you at Midpoint Review!
- Very much appreciate the one-thing-per-page approach!

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- **Consider:** Right now, there's some inconsistency between different steps in the workflow where some have a descriptive heading and/or fieldset/legend, while others just have the input beneath the step indicator. There are a couple of other teams who have been working on form flows in which each page has a unique H3 on each page that either serves as a statement of the question on the page or summarizes the collection of questions. This serves to:
   - Have consistent visual weight moving through the workflow.
   - Provide a consistent target for receiving keyboard focus that's unique for each page, so screen reader users get immediate feedback on their progress even when there are multiple pages in a single step.
   This isn't something required or even something super common on VA.gov, but it's a nice practice to follow if you're able. I'd encourage you to reach out to Josh Kim and Robin Garrison for their thoughts/examples of implementation.

**Comment by tygindraux** [comment]
Thanks for your feedback, Brian! Very helpful.

Josh and Robin shared some examples with us (and some more context!) We've now updated the flows so that each page has a unique H3. [Here's one flow with these updates (see V3).](https://sketch.com/s/6a75d0a2-e484-4f1e-8675-ad5747a1a871)

We're looking forward to your feedback on this at midpoint review.

**Comment by tygindraux** [comment]
I'm going to close this ticket now!
