### ISSUE TITLE
After Visit Summary - Past appointment details page (UI) 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#62906]
## Description
The team is looking to implement the After Visit Summary feature in the appointments application. This will give the Veteran the capability to view their appointment summary from their provider. 

---

## Acceptance Criteria
Background: the `va_online_scheduling_after_visit_summary` toggle is on

- [x] Given the past appointment has an appointment IEN linked to the appointment ID
        When the user is on the Past appointment list page and clicks on `Details` for an appointment 
        Then the link will be displayed `Go to after-visit summary details` 
        And page design matches the [design spec](https://www.figma.com/file/VHHxvo1QA1ndWc0TBhfkNq/Add-After-Visit-Summary?type=design&node-id=2012%3A34945&mode=design&t=KEbJ79SOagCUmN7u-1)

- [x] Given the past appointment has an appointment IEN linked to the appointment ID
        When the user clicks on the link `Go to after-visit summary details` 
        Then the user will be directed to the After Visit Summary Details page 
        And page design matches the [design spec](https://www.figma.com/file/VHHxvo1QA1ndWc0TBhfkNq/Add-After-Visit-Summary?type=design&node-id=2012%3A34945&mode=design&t=KEbJ79SOagCUmN7u-1)

- [x] Given the past appointment details does not have an appointment IEN linked to the appointment ID
        When the user is on the Past appointment list page and clicks on `Details` for an appointment 
        Then the `Go to after-visit summary details`  link will not be displayed 

- [x] Given the past appointment has an appointment IEN linked to the appointment ID
        When the user clicks on the link `Go to after-visit summary details` 
        Then an event `vaos-after-visit-summary-link` will trigger in Universal Analytics (UA)
        (Separate ticket will be created for migrating the event to Google Analytics) 

### Technical Ticket
-  Spike ticket: [63359](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/63359)
-  BE ticket: [63692](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/63692)

### Design Assets
[Figma design spec](https://www.figma.com/file/VHHxvo1QA1ndWc0TBhfkNq/Add-After-Visit-Summary?type=design&node-id=2012%3A34945&mode=design&t=KEbJ79SOagCUmN7u-1)
<img width="127" alt="Screenshot 2023-07-31 at 6 12 27 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/90797205/69b49b02-e2cd-4d49-9fb8-13cee8ca311e">

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by JRRoof** [comment]
Updated design links to reflect work being done in this ticket.

**Comment by ldelacosta** [comment]
@young1205 - please have the UX team validate this ticket when it's ready cc: @JRRoof @outerpress

**Comment by simiadebowale** [comment]
@JRRoof this is ready for validation in staging

**Comment by JRRoof** [comment]
@simiadebowale - which test user(s) have AVS data?

**Comment by JRRoof** [comment]
### After Visit Summary display on past appointment for:
Judy Morrison - October 13, 2023 / 9:00am MT - VA Appointment

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/97117349/f77722f1-56b6-429b-9cba-6b5361c601bf)

### AVS link redirects to this AVS page
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/97117349/9a3b0e44-9910-4d0b-84ca-b0a613ca8082)

### Questions
1) Is it the intended behavior that the AVS page loads without data being displayed?  Had to click on Medical Records for the page to load the AVS info.
2) Is there a way for the user to get back to the appointment details they were viewing?

**Comment by JRRoof** [comment]
Page matches design and link functions.  AVS page content being tested by AVS team.

<img width="1018" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0Z0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dd3a31c396c9d96715a8afcd035075591de46bf1/image.png" alt="image.png" />

<img width="871" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1Z0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f7f85facaffb53cb9d324d7d0145d971479e9683/image.png" alt="image.png" />
