### ISSUE TITLE
Research improve upload speed by batching

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#6292]
As a developer, I need to research the performance of the upload batching, so that appropriate performance improvements can be taken to improve performance and stability of the application.

## Assumptions:
1. If a minimal number of improvements are identified, they can be completed as part of this story.

## Acceptance Criteria:
1. Recommended improvements are documented on this story so they can be included in a future implementation story.

## Supporting Artifacts:
1. N/A

**Comment by dmccurdybah** [comment]
The difference between batch sizes of 100 and 50000 was only 1-2 seconds when importing a 20 MB file. No change recommended.
