### ISSUE TITLE
[Docs] Create Architecture diagrams

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#62936]
## Description
With the new automated process for deployment and tear down.  We need to provide new docs on how this process will work and the process flows it will take. 

## Resources 
- Equivalent diagrams to what have been developed for our current platform https://vfs.atlassian.net/wiki/spaces/OT/pages/2231304195/Platform+Infrastructure+Diagrams#Overview-and-high-level-workflow
- Diagrams of AWS resources
- Diagrams of Kubernetes resources/structure

## Acceptance Criteria
- [ ] deployment process is diagramed and documented
- [ ] tear down process is diagramed and documented
- [ ] docs are easily found and understood
- [ ] diagrams of AWS resources
- [ ] diagrams of Kubernetes resources involved in Platform

## Refinement Guidance - Check the following before working on this issue: 
- [x] _Team label assigned ("platform-tech-team-2")_
- [x] _Epic assigned (if needed)_ 
- [x] _Estimated (points assigned)_
- [x] _Sprint assigned (once planned)_
- [x] _Team member(s) assigned_

**Comment by ph-One** [comment]
I've been in touch with @jhouse-solvd surrounding some of the details that Security would like to see in diagrams to be sure that the new diagrams meet expectations of others who may rely on them

**Comment by npeterson54** [comment]
@ph-One that link is broken for me.
