### ISSUE TITLE
GIDS: Research query optimization in institution_builder

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#6293]
As a developer, I need to research the performance of the institution_builder queries, so that appropriate performance improvements can be taken to improve performance and stability of the application.

## Acceptance Criteria:
1. Recommended improvements are documented on this story so they can be included in a future implementation story.

## Supporting Artifacts:
1. N/A

**Comment by zurbergram** [comment]
`ipeds_ic_ays` is used at https://github.com/department-of-veterans-affairs/gibct-data-service/blob/master/app/models/institution_builder.rb#L326
and would need an index on `cross` 

`ipeds_ic_pies` is used at https://github.com/department-of-veterans-affairs/gibct-data-service/blob/master/app/models/institution_builder.rb#L337
and would need an index on `cross` 

`school_certifying_officials` is used at https://github.com/department-of-veterans-affairs/gibct-data-service/blob/master/app/models/institution_builder.rb#L594
and would need an index on `facility_code`

`sec109_closed_schools` is used at https://github.com/department-of-veterans-affairs/gibct-data-service/blob/master/app/models/institution_builder.rb#L126
and would need an index on `facility_code`

**Comment by zurbergram** [comment]
Instead of 2 loops could switch last part of query in https://github.com/department-of-veterans-affairs/gibct-data-service/blob/master/app/models/institution_builder.rb#L172 to be an `IN` statement

**Comment by zurbergram** [comment]
`hcms` is used at https://github.com/department-of-veterans-affairs/gibct-data-service/blob/master/app/models/institution_builder.rb#L398 and would need an index on `ope6`

**Comment by zurbergram** [comment]
Switch over https://github.com/department-of-veterans-affairs/gibct-data-service/blob/master/app/models/institution_builder.rb#L499 to use `version.id` removing need for a join in the SQL
