### ISSUE TITLE
SOCKS access for John Bramley - Laptop

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#62932]
### Your Name

John Bramley

### Your Email

john.bramley@oddball.io

### Your Role and Team

Backend Engineer on Identity Core Team

### Product Manager (PM) name and email

Mike King mike.king@oddball.io

### Product Owner (PO) name and email

Tom Black thomas.black2@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCO0jwNb3eSrFpmrxUnZEy2Vj2MNb92NvCs5fw+Ftblg+TIDUbHBnE+s/EMu9t/5wiRmLfydsGka9Pb3mBrukVLbdmys0tjJZEo5FruHlELOGv2bpmdIwt9EvEEWa7HvqM/roYtVM4mD8eHuyx8BXo4rXY6HjtrmrXGiGcSgXK0GXOTuccF8PygfHQi5/ph+ggXl0DG5iDWoR9Jn59SGPA8ZZRSjKfCQyD10GCN2aOHKjkFTmrgkNf+32/nuJG/0MzDdhvT9A2ETwrLp7MiXtThktPAeTA9+HXSZJm9pancowEWS8Am3V0409n+uGMooGHLp3bNsg4v9FaQp9Ug23BEanFVRLlwLr2uQNBoJmA53wZ5WRaavZDrXJbioMrcMVs+jezK5u8tezj3POkd29CCS3ZTRLOvJd5pNE56aKnrjpFdtHkJrr7Y5XqVflPnEIVzihySmbEdnUpFb+z48Tm6vw7orFcOW4GTEAhYnQMZAmeDgdSJdGSjkQWInEYEiJk= john@xiaopang
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCt78YEMn52KQ2OHxraRqTHCNkbZpJK7aK434caMn8VBlH0Tjz8NbTsDmWNzR03pI3bylvst5nes89Qrwj0FfVFDIMhBhmygWUTuk1pC94RTrYSLBVKZeeyVzNEuEbJcRkq3tSK806sXRwaZdyF0N3nL+3+jkqbl/hcPe9/gWqdhOyQWo00jGQeL5uzG2e3jKj4eCIy0PHuleo0SP6OkmFHRj9Eemn9Onh6HPS11AU1fAjDXKOxUc0Iw6HatjRiLyatABqsUo8EueEuYPWB1XNldYYZqlUnhbXBlwIgcsFKGqKpYa4cfPBwcx+73eOLEqxaS3aka3BmLhukB9hokQ71vovoLXU6/EYpvWpB38953KFkNgztPZR35EFoHFZ8nLWjg6qftAkwqIY0S5oFpsepGtb1NLWwvf0aW7DCSjy9Bjgj28hk2FUatsxZn68xH1vAJg2OwoLPIT/mL7etV8YnPG7uIsNJkq1FlWng8AlWlMHGIn9rvLMb9laIUAsaMS8= john@maomi

### E-QIP Transmittal Confirmation

Already confirmed, have SOCKS / PIV access.

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by flooose** [comment]
@bramleyjl am I understanding you correctly, your SOCKS access has never worked? While I haven't seen two keys in one authorized_keys file like in your [previous attempted](https://github.com/department-of-veterans-affairs/devops/pull/12693/files), I don't think this is an unrealistic request and I want to make sure this is the actual problem, and not something else. Do you have a windows system, or mac (or other)?

**Comment by bramleyjl** [comment]
Both of my systems are Linux/Ubuntu; I've always been able to get a single key working - whichever key is listed first. So at present my desktop Ubuntu (`john@xiaopang`) has working SOCKS access. I'm currently away from home and would like to get my new Ubuntu laptop (`john@maomi`) up and working with SOCKS, as well as remove the key for my old Ubuntu laptop (`john@feldon`), a key that has never worked anyways since it was 2nd in the file and I couldn't figure out how to get it picked up.

Hope this helps explain the situation; when I previously tried I couldn't' find anyone else with two different working SOCKS keys that knew how to make it happen, but it should be possible!

**Comment by flooose** [comment]
Ok, since you say you've tried using two keys, but only the first one in the file has ever worked, the most immediate solution I can think of is that we put the new key up top into the authorized_keys file until we can figure out if the lack of support for multiple keys is intentional. Alternatively some people have also chosen to copy their ssh keys to second computers. That would mean the ssh key pair for `john@xiaopang` would get copied to your new system, if I remember correctly. Or don't you have access to that key pair because you're away from home?

**Comment by bramleyjl** [comment]
I didn't think that I had changed anything but now I'm seemingly unable to successfully connect to SOCKS on my desktop:
```
> vtk socks setup
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 1 (delta 0), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (1/1), 879 bytes | 879.00 KiB/s, done.
----> Testing SOCKS SSH connection... ✅ DONE
----> Configuring SOCKS tunnel to run on system boot...[sudo] password for john: 
 ✅ DONE
----> SOCKS setup complete. 
> socks
[1] 50149
> vtk socks on
----> ERROR: Could not connect to SOCKS. Try running `vtk socks setup` first.
----> Verbose Output from SSH log:

OpenSSH_8.9p1 Ubuntu-3ubuntu0.3, OpenSSL 3.0.2 15 Mar 2022
debug1: Reading configuration data /home/john/.ssh/config
debug1: /home/john/.ssh/config line 23: Applying options for socks
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug2: resolve_canonicalize: hostname 172.31.2.171 is address
debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/home/john/.ssh/known_hosts'
debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/home/john/.ssh/known_hosts2'
debug1: Executing proxy command: exec ssh -l dsva -A 52.222.32.121 -i ~/.ssh/id_rsa_vagov -W 172.31.2.171:22
debug3: timeout: 5000 ms remain after connect
debug1: identity file /home/john/.ssh/id_rsa_vagov type 0
debug1: identity file /home/john/.ssh/id_rsa_vagov-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.9p1 Ubuntu-3ubuntu0.3
Connection timed out during banner exchange
Connection to UNKNOWN port 65535 timed out
```

I had thought the results of `ssh socks -D 2001 -N &` being `[1] 50429` meant that I had a successful connection?

**Comment by ben-allen-oddball** [comment]
Closing, stale, presuming resolved.

**Comment by bramleyjl** [comment]
Apologies, yes this was resolved by simply duplicating the top-line/original SSH key for both computers. Thank you for your help!
