### ISSUE TITLE
Design Intent - Design Feedback - AE Profile , Authenticated Menu Modifications

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#62939]
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- No feedback. Take a peak at the [divider in experimental design](https://github.com/orgs/department-of-veterans-affairs/projects/946/views/3?pane=issue&itemId=29995748). Maybe you can help define the divider and possibly some guidelines although that specific request is in a page with content and not a menu.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

-

**Comment by mtcA6** [comment]
Closing this as we're going to look at this [here ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/62944)
