### ISSUE TITLE
Team review of new VA.gov Experience Standards

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#62952]
## User Story
As a Governance team member, I want to do one last review of the modified VA.gov Experience Standards so that I can be confident applying them to future Staging Reviews.

Assignee: @erinrwhite 
Peer Reviewer: @shiragoodman @CherylEvans @allison0034 @it-harrison @briandeconinck 

## Description
We have taken our newly mapped experience standards and formally mapped them in a spreadsheet. Before we continue working on this effort, we want to ensure the Governance team members have reviewed the standards for consistent and preferred language, and evaluated if there are any gaps, duplicates and/or inconsistencies. We also want to ensure that all standards have the same level of granularity (as much as we can control for it). 

> Notes from 8/10 refinement:
> 
> - Maintain change history of new standard language. 
> - Re; DS and Content Style guide tickets, it may be difficult to write those new standards from the Veteran/user perspective. Allison recommended referencing the Design principles https://design.va.gov/about/principles#impact

## Impacted Artifacts
[Revised Experience Standards](https://docs.google.com/spreadsheets/d/1q6UGLEd8re94B5o69EFDz2HNMHw6WvdAHl46FHYsA9s/edit#gid=2030084267) spreadsheet
Relevant tabs:

- FOR REVIEW: Old/New Standards 
- FOR REVIEW: Categories
- FOR REVIEW: New Standards

### First round - August 31-September 12 sprint
- [x] it is encouraged that you all take notes in your own personal folder and/or on paper so that you can raise your concerns at the appropriate time without having to remember everything
- [x] In the FOR REVIEW: Old/New Standards tab, review the mapping of the old standard to the new standard. Identify if you agree with the mapping for each experience standard (Yes) or if you disagree/want to discuss (No or let's discuss).
   - [x] Allison
   - [x] Brian
   - [x] Cheryl
   - [x] Erin
   - [x] Ian
   - [x] Shira
- [x] In the FOR REVIEW: Categories tab, review the definition and name of each category. Identify if you agree with the category name and definition (Yes) or if you disagree/want to discuss (No or let's discuss).
   - [x] Allison
   - [x] Brian
   - [x] Cheryl
   - [x] Erin
   - [x] Ian
   - [x] Shira
- [x] In the FOR REVIEW: New Standards tab, review the language and granularity of each new standard. Identify if you agree with the proposed wording and granularity (Yes) or if you disagree/want to discuss further (No or let's discuss).
   - [x] Allison
   - [x] Brian
   - [x] Cheryl
   - [x] Erin
   - [x] Ian
   - [x] Shira
- [x] Review as a team at the Weekly Initiative Meeting on 9/12 to discuss any items where we are not in alignment

### Second round - September 13-27 sprint
- [x] [Standards mapping](https://docs.google.com/spreadsheets/d/1q6UGLEd8re94B5o69EFDz2HNMHw6WvdAHl46FHYsA9s/edit#gid=628171129): 
  - [x] For each old standard with an action item, assign an appropriate new experience standard 
  - [x] Create a google form for team to provide feedback on new mappings (yes/no and comments)
  - [x] Team: complete form to review standards mappings
    - [x] Allison
    - [x] Brian
    - [x] Cheryl
    - [x] Erin
    - [x] Ian
    - [ ] Shira
- [ ] [New standards list](https://docs.google.com/spreadsheets/d/1q6UGLEd8re94B5o69EFDz2HNMHw6WvdAHl46FHYsA9s/edit#gid=2030084267):
  - [x] Rewrite standards to consistently use "user" instead of "users"
  - [x] Rewrite standards to remove sighted word "sees" and replace with "experiences" or "encounters"
  - [x] Move standards to [Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1687405248108/d062ed36c1e5191571492e64cfe61ac87c02c9fc?sender=30a66039-88f6-44cf-a8f0-cbb01dabc22e) so that similar standards can be combined or clearly differentiated, and narrow standards can be identified for potential consolidation
  - [x] Team: [review and edit Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1687405248108/d062ed36c1e5191571492e64cfe61ac87c02c9fc?sender=30a66039-88f6-44cf-a8f0-cbb01dabc22e)
    - [ ] Allison
    - [ ] Brian
    - [ ] Cheryl
    - [x] Erin
    - [ ] Ian
    - [ ] Shira 

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] Governance team is in alignment on the new VA.gov Experience Standard categories and their definitions
- [ ] Governance team is in alignment on how the old standards mapped to the new standards.
- [ ] Governance team is in alignment on the wording, definition, and granularity of each new VA.gov Experience Standard.

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by erinrwhite** [comment]
The team took a pass at the revised standards today, Tuesday 9/12. We identified some old standards that needed to be mapped to different new standards, and talked about bigger-picture refinements needed for the list of new standards that were too narrow or needed to be rewritten. The team is in agreement that more time is needed to accurately account for all old standards standards and ensure the new standards are similarly scoped and consistently written.

We'll move work into the next sprint with some additional refinement tasks for the task list.

**Comment by erinrwhite** [comment]
Shared google form [Experience standards ballot](https://docs.google.com/forms/d/e/1FAIpQLSd2K5uLmLtodLhHCBQ0JOhoor4Sj5mGW1lunFxdFWS6arAUrA/viewform) with team on Slack, deadline Tuesday 9/19 at noon Eastern.

**Comment by erinrwhite** [comment]
Great call with the team today where we agreed on next steps for 19 previous standards. Next step is to update documentation and move ahead with Mural board for new standards.

**Comment by erinrwhite** [comment]
Shared [Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1687405248108/d062ed36c1e5191571492e64cfe61ac87c02c9fc?sender=399257d0-61f4-4f91-af8a-3ddbef065897) for team review and feedback.

**Comment by erinrwhite** [comment]
Team discussed mural board today and Erin will work in the next sprint to get MVP of language for standards and categories ready to ship.

**Comment by erinrwhite** [comment]
Final round of edits based on team feedback last week:
- [Experience standards](https://docs.google.com/spreadsheets/d/1q6UGLEd8re94B5o69EFDz2HNMHw6WvdAHl46FHYsA9s/edit#gid=2089466616)
- [Categories](https://docs.google.com/spreadsheets/d/1q6UGLEd8re94B5o69EFDz2HNMHw6WvdAHl46FHYsA9s/edit#gid=1992248744)

**Comment by erinrwhite** [comment]
Per conversation with Shira this morning, officially closing this ticket!
