### ISSUE TITLE
[UX] Pull out Wireframes for Priorities 7-9

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#62964]
## User Story
As UX, we need to make sure that the changes needed for each of the releases 7 through 9 are clear so that engineers will know what work needs to be completed for each release.

## Tasks
- Pull out Wireframe & Info Needed for Releases 7-9

## Releases
- Release 7
    - Updated details page
        - Design tweaks to statuses
       - Adding the confirm action for pre-check-in
- Release 8
    - Changes to Need Help
    - [Change alert on travel pages to additional info component](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/59126) 
- Release 9
    - Allow Veterans to access Pre-Check-in & Check-in regardless if the link has expired or they have no appointments for today (can we re-generate the LoROTA entry for some limited time period? does this affect the ATO?)

**Comment by zach-park** [comment]
@benbrasso-agile6 , priority 7 is ready for validation now (and priority 8 is completed).

**Comment by benbrasso-agile6** [comment]
Yep, 8 is all validated. Will check out 7.

**Comment by benbrasso-agile6** [comment]
7 is validated

**Comment by benbrasso-agile6** [comment]
9 is validated

**Comment by benbrasso-agile6** [comment]
@zach-park you share the work on this ticket during sprint review
