### ISSUE TITLE
[UX] Pull out Wireframes for Releases 3-6

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#62963]
## User Story
As UX, we need to make sure that the changes needed for each of the releases 3 through 6 are clear so that engineers will know what work needs to be completed for each release.

## Tasks
- Pull out Wireframe & Info Needed for Releases 3-6

## Releases
- Release 3
    - New completion page for check-in & pre-check-in (phone & in-person)
	  - Design tweaks
	  - New message based on the following scenarios
	      - Clicked on "Review your info" & answered Yes to all questions
	      - Clicked on "Review your info" & answered No to at least 1 question
          - New link to get back to the new landing page (minus the message of other tasks to do)
          - Add eyebrow into pre-check-in
- Release 4
    - New message page for info is up-to-date & clicked the pre-check-in link
        - [WF link](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/uuid/8BDCA2AE-00CE-4162-BEDE-9D0B349E24E6)
    - New error pages in this format (excludes login errors);
        - Message - message for the task corresponding to the link clicked
        - Upcoming Appointments
             - Excluding the ability to see the check-in/pre-check-in status for each appointment
             - Excluding the ability to complete tasks for other appts
-  Release 5
    - Ability to see the action status for each upcoming appointment (both on the details page & the appointments page) (this includes if you have already completed the action or when you can do it)
- Release 6
    - Ability to complete a task for an appointment NOT associated with the link clicked
        - NOTE: we will need to ensure that status's are set properly so that the Veteran does not receive more pre-check-in reminders & VSECS is updated as well
    -  Update completion page for pre-check-in (phone & in-person)
	  - New message based on the following scenarios
	      - Clicked on "Confirm your appointment"

**Comment by benbrasso-agile6** [comment]
Made some updates to 3. Will look at 4-6 next week.

**Comment by benbrasso-agile6** [comment]
@cgednalske minor comments for you in priority 5 and 6. Take a look and then let's get this ticket closed. TY
