### ISSUE TITLE
[DA] 10-10 Forms: Sprint (8/9-22) Metrics update

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#62970]
## Background
As part of a regular sprint-ly cadence, we need to update various metrics on our applications - 10-10EZ and 10-10CG.

### References
- [Metrics Spreadsheet](https://docs.google.com/spreadsheets/d/1T_iRon2SsOwL7cRSEyDIiRnC0Ci81FpVThAs2RgPyKY/edit#gid=1033337103)

## Tasks

- [x] Update metrics on the spreadsheet for both applications
- [x] Share any anomalies with the team for further review

## Acceptance Criteria
- Metrics for both applications are collected and tracked on a regular, sprintly basis

**Comment by luis-simauchi** [comment]
An error as appeared more frequently as of the past 14 days that we should keep an eye on moving forward:
[Public Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbThWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--eec4e7313e751d1674cca890a6b720542caeed3b/Capture01.PNG)

**Comment by luis-simauchi** [comment]
metrics sheet has been updated and the data dog error tracker as been reviewed for the week.
