### ISSUE TITLE
Adding Sara (Beth) Golson to DSVA Slack

### ISSUE THREAD

**Issue by huggins-va** [department-of-veterans-affairs/va.gov-team#62983]
Please add Sara (Beth) Golson as a multi-channel user to:
api-facilities and team-marmoset 

Sara (Beth) Golson is joining team Marmoset as a Salesforce Business Analyst and will need access to perform their job requirements. 

Thank you!

**Comment by LEHigley** [comment]
need email

**Comment by huggins-va** [comment]
Golson_Sara@bah.com

No VA email yet
