### ISSUE TITLE
Create documentation site homepage MVP 

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#6299]
## User Story or Problem Statement

As a team member building on or in support of VA.gov, I need a landing page where I can access documentation from all sources, so that I can self-sufficiently find what I need to be successful.

## Details/Notes 

This MVP build is not inclusive of mobile designs/responsiveness.

## Acceptance Criteria
- [x] Public user can visit documentation site homepage
- [x] Public user can navigate to relevant links and open source documentation in new tab

**Comment by billfienberg** [comment]
PR: https://github.com/department-of-veterans-affairs/va.gov-team/pull/7045
