### ISSUE TITLE
Midpoint Review - Design Feedback - Sitewide Facilities VBA Regional Offices

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#63006]
## VFS actions
- [x] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- Thank you for mobile and current view!
- If you are using anything outside of the design system, please go through [experimental design](https://design.va.gov/about/contributing-to-the-design-system/).
- Work with Matt on a variation of breaking up the text within the accordion instead of the left blue border. 
   - Matt: I think if you use the borderless version of the Accordion you could use the [new Card style ](https://design.va.gov/components/card#default---white-with-border)(which does have a border) inside an Accordion

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

-

**Comment by davidmpickett** [comment]
To discuss in Facilities UX Refinement
- Borderless accordion? Worth investigating?
- Experimental design request - opening a ticket
- What to do for prototype? (Assuming we're not blocking research with the experimental design request)

**Comment by thejordanwood** [comment]
@allison0034 Wanted to ping you on this again because I'm not sure if I should open an experimental design ticket for the accordion/card combo.

**Comment by allison0034** [comment]
@thejordanwood I am sorry I missed your first comment! I do not believe so but I want to confirm with Matt since that was his feedback. @humancompanion-usds are you ok with Jordan using the new card inside a borderless accordion?

@thejordanwood is the first image the old design and the second image new?

- <img width="490" alt="Screen Shot 2023-08-22 at 12 26 58 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/72398073/46b647d9-611c-4999-baee-c33ab2e10845">
- <img width="337" alt="Screen Shot 2023-08-22 at 12 25 55 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/72398073/19e0152d-d0fc-4a61-9447-745403d9b66a">

**Comment by thejordanwood** [comment]
@allison0034 Correct! The first image is what we had at design intent and the second image is what we changed it to based on the feedback we got from design intent.

**Comment by humancompanion-usds** [comment]
Does not need to come to Design System Council and does not need to be an experimental ticket. I don't know that's successful given how massive that first Card is. I'll be interested to hear how it goes with users.

**Comment by thejordanwood** [comment]
I'll keep you updated Matt! I'm interested to see how usability testing goes too.
