### ISSUE TITLE
SOCKS access for Maurice Okumu

### ISSUE THREAD

**Issue by Maurice-Okumu** [department-of-veterans-affairs/va.gov-team#63017]
### Your Name

Maurice Okumu

### Your Email

maurice.okumu@thoughtworks.com

### Your Role and Team

Software Developer Chatbot team

### Product Manager (PM) name and email

Alina Murphy amurphy@thoughtworks.com

### Product Owner (PO) name and email

Luciana Morais  luciana.morais@va.gov

### Access Type Requesting

Developer

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDU5tiDFiejXyoXUmkRWZczy8fU0Z7grgjnI/HZ7hY1a/Oq4WsH25MA2eTmLkzKg5isPN+myp2LJ/hutgN0zsSW0k8E7ql1HCDvmUCcorRFbpFCYvnkGqbGA0ovc9BkVJZLjln9Bannx+LG0pteDegEn84PiAXnecY/a9674eImu1rHZxQgS+pftX0cMHGNHsU5kVDX8O4nF/DLKCIz7hZTBjYjEdb81OASuzAfTZTwPfUTjZqy2ntiyhgn9MbV++UZ7On2zu+l/dXGtpBlZA7D8mp6tngUzDDzpd0ejapr+KYrzuPvYjE3sxG7Y+jp/aS6Q9MVebeXLgOmyk82AHU2ft/XtPiYFCQsi80/WaSvqzW6wq0TWLpHokmAbULKh5M7RoRoiGNvu9mGg93+8NZ6SHRvr8e8BwQSpcb3mUfi7Rs7UHyvnCl0oBFLZcBtxGuaS2Dhl1J3J+CebuQ3efLw48JqWYDeyolmYdI8O1VWm0HpTy+AMIWdW10BevBQcD8= mauriceokumu@Maurices-MBP

### E-QIP Transmittal Confirmation

<img width="1266" alt="eqip-transmittal" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/74667197/645da2a3-1874-4700-8680-cb8c33757ae4">

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by Maurice-Okumu** [comment]
I was just added to the VFS Roster

**Comment by ph-One** [comment]
SOCKS access completed
