### ISSUE TITLE
Determine best "get help/make a suggestion" link/contents for docs site homepage MVP

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#6301]

**Comment by gmaciolek** [comment]
Link curation spreadsheet
https://docs.google.com/spreadsheets/d/1Q3-2yvECkh2r7Ltrk_pP0TF3PHnfrc6TFAvm0z22ljk/edit#gid=0

Content exploration mockup:
https://www.figma.com/file/c6b69YK0FINg8y2SO8xlXo/Untitled?node-id=1%3A2

**Comment by meganhkelley** [comment]
Notes from mtg with Gretchen & Naomi on 3/2:

TESTING FOR THE HOMEPAGE
- Service Design doesn’t have any regular processes (yet) 
- Service Design should be involved the the testing of the homepage, if we want Service Design to run the testing they could do that
- MVP timeline: soft launch sprint 23? 

**“Can’t find what you’re looking for? Reach out to us.” — ZENHUB TEMPLATE**
Also, find a way to embed a 1-5 rating survey?
