### ISSUE TITLE
Update MHV API documentation

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/va.gov-team#63023]
### Description
[These docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/my-healthe-vet) for MHV APIs can be updated to include the View Test and Lab Results application.

Code usage in vets-website:
https://github.com/department-of-veterans-affairs/vets-website/blob/d767b9e1aab84f61b3c720cf5fde51e640d1fab9/src/applications/static-pages/health-care-manage-benefits/view-test-and-lab-results-page/components/AuthContent/index.js#L30

Very similar to the Refill / Track Prescriptions app:
https://github.com/department-of-veterans-affairs/vets-website/blob/81e0d256ddbb31721ef3807374ed9a65d8b5ec0f/src/applications/static-pages/health-care-manage-benefits/refill-track-prescriptions-page/components/AuthContent/index.js#L30

### Which type of team are you on? (Platform team, VFS team, or Leadership)

VFS - Sitewide / Public Websites

**Comment by vbellissimo** [comment]
Hi @randimays , thanks for your request. We're taking a look for next steps.

**Comment by vbellissimo** [comment]
Slack support thread: https://dsva.slack.com/archives/CBU0KDSB1/p1691002615871569

**Comment by taylojill** [comment]
Hi @randimays I'll work with you to get the My Healthe Vet page updated. Will this new content live under the "Integration Points" heading? If so, can you provide the specific details for View Test and Lab Results. See below screen shot...I'm assuming it be here. If not, where will the content live on the page? Thanks!

![screen shot_issue 63023](https://github.com/department-of-veterans-affairs/va.gov-team/assets/97645218/8fd68e27-38f8-428e-8608-1c9b4a599ecd)

**Comment by randimays** [comment]
Hey @taylojill I think we just need to add it into this line:

>MHV APIs provide Secure Messaging (SM), Prescriptions (RX), and Health Records aka Blue Button (BB) support as well as authentication.

**Comment by taylojill** [comment]
Added "View Test and Lab Results" to existing sentence. Also added "login required" statement to hyperlinks that resolved to "server not found" error.
