### ISSUE TITLE
Midpoint Review - IA Feedback - Sitewide Facilities VBA Regional Offices

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#63026]
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- Thanks for including the mobile designs in the Sketch!
- The escape hatch at the end of the page is a nice touch.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- **Should:** Include a [back to top component](https://design.va.gov/components/back-to-top)
- **Consider:** Adding a link to search for nearby VA locations in the "Other nearby VA locations" section

Thanks!

**Comment by jilladams** [comment]
Include a [back to top component](https://design.va.gov/components/back-to-top) is already an AC on #13960

**Comment by thejordanwood** [comment]
Update on this: We added the back to top component and added a search link under the "Other nearby VA locations" section. [Sketch link](https://sketch.com/s/891d33ae-152d-471c-ab5d-9aedf89cf6ff)
