### ISSUE TITLE
User testing - documentation site homepage MVP

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#6302]

**Comment by meganhkelley** [comment]
Initial brainstorming notes: https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/6301#issuecomment-594560636

**Comment by vbellissimo** [comment]
Cancelling/old task.
