### ISSUE TITLE
SOCKS access for [Alexander Mendoza]

### ISSUE THREAD

**Issue by lealmendozaalexander** [department-of-veterans-affairs/va.gov-team#63033]
### Your Name

Alexander Mendoza

### Your Email

alex.mendoza@thoughtworks.com

### Your Role and Team

Software Developer in chatbot team

### Product Manager (PM) name and email

Alina Murphy alina.murphy@thoughtworks.com

### Product Owner (PO) name and email

Luciana Alexander Morais luciana.morais@va.gov

### Access Type Requesting

automation

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC0W7wk5a6hK7HYf8dOiI/OEk16IniWOLiRhmOEjWBY9x9eMdy2ocrpXv+E9d4P1YIhmE1WJaVGEBT/BV/UDhwLk5hVga2roexNCRNOdpxYqREwPXdeVEHaw8MJNKTRychWpySQ/WmZPHsxE9JzY+z4HGwXAQBoMHyMKlQpvdTHy/8inYXaV/k3HZDRO97Ki3LQoItC2zPWhj+CSMiovGLkq/QC3LDOrg4ZQTbYOFIdRodQDp1Nz/noht/vqFjag30x5+f+n2OxNjARdu5N8XaAk7oo2+bcprL2SZxksCNyYk5pOYY/p5LE2kvNM4NhYLp48sFVez/TElFhfqMML0pP8yZlNAFYH+CTcGebUjDAdSB59Jf4gX96S598CnRGxYDqVwxpaL278cBxurYA0kI1gWN+8pMkukgb8CNXn8aCyg+k/ceyhLGdNa8oz7eHBJHKeeINeq7pS6L8ZC5BzKTw7iJT2sNPzqNEtD38juehFDk9QxdWSULlV4kfB7EJZgE= [alexandermendoza@Alexanders-MBP.hsd1.il.comcast.net](mailto:alexandermendoza@Alexanders-MBP.hsd1.il.comcast.net)

### E-QIP Transmittal Confirmation

![Screenshot 2023-08-02 at 11 45 35 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/137556584/43305fbd-cbf5-4653-9a05-cab83ac69036)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by lealmendozaalexander** [comment]
I have been added to the VFS roster

**Comment by ph-One** [comment]
SOCKS access completed

**Comment by lealmendozaalexander** [comment]
Had to uninstall then reinstall socks. So I needed to update my ssh key.

**Comment by ben-allen-oddball** [comment]
Updated MR to reflect Dev rather than automation.

**Comment by ben-allen-oddball** [comment]
Closed already completed.
