### ISSUE TITLE
Broken link is showing up in VA search 

### ISSUE THREAD

**Issue by megzehn** [department-of-veterans-affairs/va.gov-team#63055]
There's a broken link that's showing up prominently in VA's search tool results:

https://www.va.gov/supporting-forms-for-va-claims/

The correct link is also showing up, but in a lower position:

https://www.va.gov/supporting-forms-for-claims/

We need to figure out the best way to remove the broken link.

**Comment by jennymayoco** [comment]
Created [a redirect request](https://app.zenhub.com/workspaces/sitewide-content-accessibility-and-ia-63a1d63232beba0011a7833f/issues/gh/department-of-veterans-affairs/va.gov-team/63082) for the support forms page

**Comment by megzehn** [comment]
this seems to be showing up correctly! I'll move this to validate and close it out. Thanks again, @jennymayoco!
