### ISSUE TITLE
Vets-api terminal access for [Fletcher Bonds]

### ISSUE THREAD

**Issue by fbonds** [department-of-veterans-affairs/va.gov-team#63069]
### Your Name

Fletcher Bonds

### Your GitHub handle (terminal access is managed through GitHub)

fbonds

### Team, Role, and Company of the target individual

Health Enrollment, Software Engineer, Agile Six (Ad Hoc)

### Product Manager (PM) name and email

Heather Justice (heather.justice1@va.gov)

### Product Owner (PO) name and email

Patrick Batemen (Patrick.Bateman@va.gov)

### COR Name (leave "None" if you listed an AWS user name above)

Rolanda Copeland

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

Agile Six - Anthony M. Arashiro

### Please confirm if you are on the VFS Team Roster or Platform Team Roster

- [X] [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Please confirm E-QIP Transmittal/Adjudication. This could be a screenshot of your Transmittal/Adjudication email, a link to another request where you've submitted this proof (i.e. AWS/SOCKS), etc.

- [X] I have attached proof that I have either transmitted my E-QIP survey or previously received a favorable decision (by including in "Additional Notes" section below)

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [ ] production (if requesting, justify prod access in 'Additional Notes' section)

### Additional Notes

![eqip-tranmittal-notice](https://github.com/department-of-veterans-affairs/va.gov-team/assets/9326800/33c99a06-e91f-43c4-80c5-cac6c881533f)

### Additional resources for Support Engineer

- [ ] For users on a VFS team but not in the VFS Team Roster, they must start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] Instructions for handling requests [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access) - Support Only

**Comment by bdech** [comment]
Hi @fbonds It doesn't look like you've been added to the VFS Team Roster yet. You will want to reach out to your project manager  to get added to the roster. Also do you have a screenshot of your E-QIP release transmittal notice. It looks like the image below.

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/135037265/f692360e-bb14-4368-a378-c02153d2a638)

**Comment by fbonds** [comment]
I'm in the VFS roster.  I think the mix up is my legal name and my preferred name.  Sorry I put my preferred name in the ticket accidentally.  I'm Joseph Bonds in the VFS roster.  Joseph Fletcher Bonds is my full name.  Joseph.Bonds@va.gov is my va email.

**Comment by fbonds** [comment]
https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665

I see me here as Fletcher Bonds @bdech

**Comment by bdech** [comment]
Thank you for the clarification, I was able to find you in the VFS team roster. Give me just a moment and I will grant you the requested access.

**Comment by bdech** [comment]
@fbonds You’ve been granted access to the `dev`, `staging`, and `sandbox` environments.

Here's some additional documentation for the [Vets API on EKS](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-TerminalAccess)
