### ISSUE TITLE
Draft Script for Known Login.gov Issues to Support Campaigns and Updated Sign In Page on VA.gov

### ISSUE THREAD

**Issue by djmunoz1** [department-of-veterans-affairs/va.gov-team#63075]
## Problem
There are a number of known issues when it comes to signing in with Login.gov (and ID.me). (Only about 35-40% of Veterans who attempt remote identity verification are successful). We cannot fix these issues since they reside with the respective teams, but we can help Call Centers prepare for questions about these issues so they can quickly help Veterans through the process. How might we uncover all known issues? How might we write instructions for troubleshooting that are clear and easy to follow without training?

## User Story
As a Call Center Representative, I would like to know how to help Veterans who call with questions about creating modern sign in credentials or verifying their identity remotely so they can set up their new modern accounts.

## Acceptance Criteria
- Known issues have been researched and documented
- Script is written for Call Centers/Help Desks that addresses known issues 
- Script is clear and understandable for Call Center representatives

Next Steps:
- review with call center representatives
- refine and distribute

**Comment by lmorris3** [comment]
@djmunoz1 is this work still needed? And can you provide some context? Is this to help Veterans navigate known issues with login on the modern credentials? Are we wanting to create this script for support/help center staff?
