### ISSUE TITLE
Qualitative Data Request - VAgov Homepage

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#63072]
### Data Type Requested

User Surveys

### Date Range Start

07-01-23

### Date Range End

07-31-23

### Product Name(s)

VAgov Homepage

### Product Description

The homepage only, no sub-pages

### Survey URL(s), key term(s), case category or type

www.va.gov/

### File Delivery Format

All in one file, on one tab

### VA Email Address(es)

wesley.rowe@va.gov

### Add Assignee and Labels

If not already done so, please ensure @ianMcCullough-ob is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by aubreyarcangel** [comment]
@wesrowe Shared. Please verify you have received your data request in your VA email.

**Comment by aubreyarcangel** [comment]
Data request received[ confirmed ](https://dsva.slack.com/archives/CNCEXNXK4/p1691096913171769?thread_ts=1691078987.160629&cid=CNCEXNXK4)
