### ISSUE TITLE
create FAQ-based script draft for Call Center to support Campaigns and updated Sign In Page on VA.gov

### ISSUE THREAD

**Issue by djmunoz1** [department-of-veterans-affairs/va.gov-team#63074]
As a call center rep I want a list of FAQs so that I can properly guide veterans who call about the changes to the VA.gov sign in page and email campaigns.

ACCEPTANCE:
- word doc
- first section should reference the changes (image of new Sign In page, sample email)
- next section should leverage FAQs on VA.gov to create separate document for Call Center reps with the response written in script format (how the rep would speak to the veteran)
- address potential questions related to why this is happening and the benefit to the Veteran
- include Content (Carl) to review for accuracy
- send draft to PO (John) and PM (Dawn) for final review and send
- glossary of terms (veterans get confused about the different credentials. They think for example that login.gov is a just a website or that VA.gov is a credential "How do I get my VA.gov username and password?") So identifying the definitions for key terms a Call Center rep might encounter is important

**Comment by MOStudioCarolyn** [comment]
First draft shared https://docs.google.com/document/d/1iv-O0RiaBG3rPC1eh9-Hys1P5HL7Go5fPyIk4a2Y9kE/edit

**Comment by MOStudioCarolyn** [comment]
Login.gov FAQs shared with Chante Thur 8/10
