### ISSUE TITLE
Research Logging Options for new Sign in Page Visitors

### ISSUE THREAD

**Issue by djmunoz1** [department-of-veterans-affairs/va.gov-team#63084]
**Problem**
We need to be able to track logins for the new Sign in Page when it launches so that we can understand the impact it has on modern credential account creation. 

Currently, logging via StatsD only provides a simple count and doesn’t give us much opportunity to pass details along.  
Currently vets-api utilizes Sentry for error tracking and monitoring. Anywhere you see them calling or sending errors via Raven is where errors are being sent to Sentry. The LGA Team does not currently have access to Sentry, so no errors being sent there are observable by the team. As of the time of this document I had still not been able to find anyone who could point me to who owns and controls the Sentry permissions and team management.

**Proposed Solution:**
- Instead of relying on StatsD alone, you can also use DogStatsD which is a DataDog enhancement of StatsD in vets-api.  There are likely a few ways it could be used, but I saw the “events” as being potentially really useful.
https://docs.datadoghq.com/developers/dogstatsd/
- You could also use the standard Rails loggers, but you’ll want to make sure that doing so isn’t against the rules/processes of the Platform Team.  I’ve looked through their docs and don’t see any references to it being banned/frowned upon, but it’s probably worth a check.

ACCEPTANCE:
- meet with Platform and discuss logging tasks and options
- define how and where we'll pull in this data
- ensure solution can log and monitor results from sign in page roll-out, specifically
- [ ] details around errors
- [ ] details around attempts
- [ ] other (what other details are needed here?)

DEF OF DONE:

- [ ] document tasks via tickets for setting up logs based on Platform feedback

**Comment by sdickson-gt** [comment]
From an analytics and reporting perspective, we already have established and understand the integration between Domo and DataDog, so we would be able to readily build a solution on logs in DataDog.  We would just need to be able to parse out the relevant information to address reporting on KPIs.
Also, Domo can only pull metrics, not logs, i.e. aggregate totals of log events.

**Comment by lmorris3** [comment]
Logging on which users see the page, what links they click on. Thinking through USiP Alert box - new link in the message "learn more."

**Comment by lmorris3** [comment]
Closing as complete.
