### ISSUE TITLE
pull email list for Campaign 1 (Target Date TBD)

### ISSUE THREAD

**Issue by djmunoz1** [department-of-veterans-affairs/va.gov-team#63087]
As an email admin I want the full list of veterans who are counted in the Organic segment so that I can send them a message about login.gov adoption.

ACCEPTANCE:
- list includes veterans in Organic segment per LGA Priorities 'Segments' tab
Organic
769,962		MHV + DSL
1,470,417		DSL
678,316		MHV
- Parameters include: 
 user email
 first name

Resources:
- Definition of Organic = veteran  does not have ID.me and veteran does not have LGN
- [LGA Priorities Segments Tab](https://docs.google.com/spreadsheets/d/1Q2W_2PKVwCKaMNEG-RsThlb7nUErJ18rIXg1Mr1W0ZU/edit#gid=64361054)

DEF OF DONE:
- list emailed to lmorris2@va.gov, cc carl@themostudio.com
Next steps: Carl: upload list to GovDelivery and touch base with Taylor to confirm no issues

**Comment by sdickson-gt** [comment]
@djmunoz1 I can get the list now if you like or I can pull an up to date list closer to when we're planning to send the emails out. Do you have an updated estimate for when that is?

**Comment by sdickson-gt** [comment]
@djmunoz1 @lmorris3 The last MPI dataset is from 9/25.  Let me know if you prefer we wait a week for the next MPI data pull for an up to date list of organic segment?
Also, I will add another task (1 story point) to update the segment counts based on latest MPI dataset and the data quality tasks related to total credentials in prior sprint.

**Comment by sdickson-gt** [comment]
segment counts are updated

**Comment by lmorris3** [comment]
@sdickson-gt we discussed last week but I didn't close the loop in the comments - we will pull the fresh email lists closer to Nov email distro. We can keep it in the current sprint (carryover from 31) but we may end up pushing out another sprint if we don't have approval to send email campaign.
