### ISSUE TITLE
ensure data needs for monthly report can be met on 8/20

### ISSUE THREAD

**Issue by djmunoz1** [department-of-veterans-affairs/va.gov-team#63080]
As an admin I want to understand the accurate authentication numbers across the VA ecosystem so that I can adequately assess changes in credential log ins.

ACCEPTANCE:
- 'unique' auth numbers by credential by month
- Jan - Aug (month-to-date)
- includes separate mobile SIS numbers from VA.gov

Resources:
https://docs.google.com/document/d/1hLtWEqKZh77rRB4SqTXDJ4nfIGufh6cJcb6W3A77CtE/edit#heading=h.j8uyqaxjix7f

Def of Done:
- dev comment in ticket that we are prepared to pull this data on 8.20 and deliver to the appropriate stakeholders

**Comment by sdickson-gt** [comment]
couple updates 
- spoke with Joe and he is going to work with Trevor to update the DataDog logs to include icn such that we'll be able to correlate with SSOe data for distinct/unique users.  I can work on the datadog integrations, such that when the icn field is added and we have a month of data, we can add to the reports
- will look into automating pulling the SSOe data for the "month to date" reports

**Comment by djmunoz1** [comment]
Great! Looking forward to this.

**Comment by sdickson-gt** [comment]
some more thoughts on having a unified report - even when DataDog is updated with ICN in the SiS event logs, we will also have to pull all the ICNs from SSOe into Domo too, versus what we're currently doing - just totals.  This will 1) add more complexity (more maintenance of the ETL process) and 2) will increase the need to find a solution for Domo Workbench scheduled jobs to run without being impacted by my forced GFE restarts etc (this needs to be done anyway, but higher priority if we want to start getting feeds more frequently than a month)

- we could report unique authentications separately for each federation: SiS and SSOe (and potentially MHV option 2).

**Comment by sdickson-gt** [comment]
As mentioned during standup - it's not clear how to pull log events from DataDog using the Domo connector.  While I'm having some progress doing the same on the SSOe side, it's feeling over-engineered.  Is the proverbial juice worth the squeeze versus a distinct report for each federation?
