### ISSUE TITLE
[Identity Dashboard Infrastructure] - Update Argo App Name

### ISSUE THREAD

**Issue by rileyanderson** [department-of-veterans-affairs/va.gov-team#63098]
## Summary
The app name in argo is `identity-dashboard-api`. This needs to be changed to `identity-dashboard` now that `api` and `ui` will be together

**Comment by asg5704** [comment]
@rileyanderson is this already complete?

**Comment by rileyanderson** [comment]
> @rileyanderson is this already complete?

@asg5704 Not yet. It's just tech debt - not blocking anything.

**Comment by asg5704** [comment]
@rileyanderson No worries, I was just checking if I could close it. Thank you!
