### ISSUE TITLE
refine user flow for modal and /or page for modern account creation

### ISSUE THREAD

**Issue by djmunoz1** [department-of-veterans-affairs/va.gov-team#63096]
As a Veteran I need to see escalated messaging on VA.gov so that I create a login.gov or ID.me account by December if I don't already have one.

ACCEPTANCE:
- messaging starts in September, updates monthly thru December
- shows to all users who have only DSL
- considers use of modal and/or pages; modals have low buy-in
- hold internal sync btwn Product and UX to define requirements more fully
- refers to current draft flow https://app.mural.co/t/innovationboards1199/m/innovationboards1199/1692029447960/78e61d1057d7aa48c5f655c4980ffbca7b87de3f?sender=uc3c8b97062727fbe21716300

DEF OF DONE:
- base level documentation of a flow that we can refine and share out for feedback
- create content tickets 
-

**Comment by MOStudioCarolyn** [comment]
Mural has been updated with most up to date flow. Waiting for refinements from DSL team.

**Comment by djmunoz1** [comment]
additional comments added to Mural from #64169
