### ISSUE TITLE
Share documentation so VFS teams can build a vets-api endpoint using the sample app

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#631]
Description of work here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/128

Sprint artifact shall be a WIP documenting representing a the majority of the items on the above ticket

**Comment by kreek** [comment]
This ticket is rolling over, have the start of the documentation [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/f8510cac3b75053a8a7b593f729a6c15405135d8/Practice%20Areas/Engineering/Backend/Tutorials/endpoint_guide.md), but I ran out of time with VAOS commitments (and house issues 🏠🔥)
