### ISSUE TITLE
confirm data usage efficiency (cost of DD)

### ISSUE THREAD

**Issue by djmunoz1** [department-of-veterans-affairs/va.gov-team#63104]
AC:
- confirm with Platform that current data usage is acceptable

DEF OF DONE:
- Confirm that current data usage is acceptable (Michelle already confirmed we're within threshold for DOMO)

**Comment by lmorris3** [comment]
@sdickson-gt is this complete? If so, you can close. Ty.

**Comment by sdickson-gt** [comment]
This has been confirmed as a non-issue.  Also, we have redesigned the ETL to use summary indexes and thus no longer requires accumulation of large snapshot datasets.
