### ISSUE TITLE
Create Helm Chart Repository with Chart Publishing/Release automation

### ISSUE THREAD

**Issue by hgbarreto** [department-of-veterans-affairs/va.gov-team#63125]
## High Level User Story/ies
- As a DevOps Engineer working on the Platform team, I need a Helm repository in S3 so we can have a centralized location for storing and distributing Helm charts specific to this effort
- As a DevOps Engineer working on the Platform team, I need a GitHub workflow/s that will automate the publishing/release of new helm packages.

## Hypothesis or Bet
By creating and implementing our own Helm chart repository, we can version, update, customize, configure and deploy our own helm charts specifically for the platform-distro.

## OKR
_Which Objective / Key Result does this epic push forward?_

## Definition of done
Helm chart repository is implemented along with workflows to automate the publishing and release of new helm packages.

## How to configure this issue
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `Console-Services`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by ph-One** [comment]
@npeterson54 the work here has been completed not once, but twice (pivoted and patched). this one is good to close

**Comment by npeterson54** [comment]
Done
