### ISSUE TITLE
SOCKS access for Alex Taker

### ISSUE THREAD

**Issue by ataker** [department-of-veterans-affairs/va.gov-team#63120]
### Your Name

Alex Taker

### Your Email

alex.taker@adhocteam.us

### Your Role and Team

Senior Software Engineer - Design System Team

### Product Manager (PM) name and email

Carol Wong Carol.Wong@oddball.io

### Product Owner (PO) name and email

Matthew Dingee matthew.dingee@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDe4DRNTMFExFC9exxkZU3/iNzI1eBlRaseQtXP+HYO9QvwqYnqvUtpqmoOGPOqgqHwNLHpLWeAVfd+Z2I7NgBk2EfKi9DROUFS2rZEJPP80Gpw/9tI7I1NnuIVYb2wu8/ug39a2eHvq50u2eF1daH+xOzGF+iEqX/hloTTyBkjA/gbF3LsnQSB4Ri+pOlJ5wmo4NKHWg2Isj10Hr+Q4peO+QliUVP2onvvUpG2RiU4MdkyamyoOacRhrvsL0VqZFY8SnGaSy/VEuXnSpQR/1QCGvAEKA5mCKJmU3/YaOdvvkZgQ1HlWMOn2EgiPpYBtNgJDKLXRijcupBf2s171BXfioFPf9smTTNFlHBCUPIuU2rlI3vsIn8Gxi/Y48oGRK5IBU1MVbKVYtgvE3uLmB91jULrHhUHMWklaM21AD+bCuWhXQSSbFuOWEuqSSmg0VhwZzF9rmJUJ61NvicCgrbLducSMcVYPYJv1palJ+RwUI37PT0aW2n5GyOvFj3+Fxc= alextaker@Alexs-MacBook-Pro.local

### E-QIP Transmittal Confirmation

<img width="1097" alt="Screenshot 2023-08-03 at 3 16 35 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/1413938/a8c643e5-1ba3-4b53-b1ea-8b78381e1dd0">

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by ph-One** [comment]
SOCKS access completed
