### ISSUE TITLE
SPIKE: Make sure our changes don't impact other k8s apps

### ISSUE THREAD

**Issue by kingbmike** [department-of-veterans-affairs/va.gov-team#63142]

**Comment by kingbmike** [comment]
Relevant b/c work is being done to create live instances when PRs are created before being merged.  Impacts dev stack and stops working.  Makes sure our changes don't have negative impact.

**Comment by charlye-bluetiger** [comment]
move info to GH

**Comment by vidjovanovic** [comment]
This has been moved to here https://github.com/department-of-veterans-affairs/va.gov-team/pull/66718

Should be done.

**Comment by vidjovanovic** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/pull/66718
