### ISSUE TITLE
[Discovery] Move 'how to apply' wizards to the application/tool start landing pages

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#6315]
## Discovery: Move 'how to apply' wizards to the application/tool start landing pages

Some of our applications require the Veteran to answer a series of questions before beginning their application. Depending on their prerequisite answers:

- The Veteran is shown only certain (but not all) parts of an online application (e.g., the 526ez online app)
OR 
- The Veterans sent/routed to a specific application (e.g., 1 of 6 possible education benefit application)

**Reference:** 
[How-to wizards hard to find (PDF)](https://app.zenhub.com/files/133843125/87e61032-a83c-49d1-8677-a0dc51ff3931/download)

**Examples - this may not be a complete list of pages that have wizards on our site:**
https://www.va.gov/disability/how-to-file-claim/
https://www.va.gov/education/how-to-apply/
[In flight - wizard for Add/remove dependents tool]
[Mikki's IA documentation](https://app.moqups.com/Rnc4BDEKrA/view/page/abd763ecc) may help us find more examples: 

We want to move/consolidate these pre-requisite Wizard steps with the application tool landing page in order to:

1/ Make the Veteran experience of starting their online application more seamless. (Today, they have to find the Wizard on a content page, and from there, fill out the wizard and then go to or are sent to the tool landing page.)

2/ Make apply online CTAs from tier 2 content and other content outside of the benefit hubs more clear and direct. Example: from our mvp form detail landing pages or from the modernized mvp form search results. 

**Additional info as FYSA** 
Background info, somewhat not in alignment and somewhat outdated, but for history:
https://design.va.gov/patterns/wizards
Very old: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/84

**Note:** Please stay in close sync with Matt Self and his Edu (BAH) team wrt education wizard. They're current working on updating the wizard question/answer content, as part of their updates to the education benefit application (adding STEM scholarship into the app flow). This shouldn't affect this ticket, but to be safe.

**Comment by jenniferlee-dsva** [comment]
@AkucherGCIO per convo, let's 3 of us talk to understand. We'll want to make sure we work with the the apps team.

**Comment by jenniferlee-dsva** [comment]
Additional background info as FYSA - these are somewhat not in alignment and somewhat outdated, but for history: 
https://design.va.gov/patterns/wizards
Very old: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/84

Note: Please stay in close sync with Matt Self and his Edu (BAH) team wrt education wizard. They're current working on updating the wizard question/answer content, as part of their updates to the education benefit application (adding STEM scholarship into the app flow). This shouldn't affect this ticket, but to be safe.

**Comment by andaleliz** [comment]
Added info from above comment to epic description, to ensure it doesn't get missed as this epic (and it's comments) grow.

**Comment by andaleliz** [comment]
@ncksllvn  added a log statement to his local website to check for React widgets (thank you Nick!).  I audited the pages based on the URLs he provided, and it looks like we have 4 pages currently using the form wizard (manage dependents is in progress so would not appear on this list).  
- https://va.gov/education/eligibility
- https://va.gov/disability/eligibility
- https://va.gov/disability/how-to-file-claim
- https://va.gov/education/how-to-apply

![Screen Shot 2020-03-02 at 7 50 23 PM](https://user-images.githubusercontent.com/55992116/75732028-530b9b80-5cbf-11ea-92df-189770374d5c.png)

I'm meeting w/ Mikki tomorrow (along w/ Kelson, Anne, and Aruna) to get background info she has, and a better understanding of the site maps.

**Comment by jenniferlee-dsva** [comment]
@andaleliz - Also there's one that's in-flight, not currently live - for the Add/remove dependents (VA form 686c online tool). We might not need to include that here for ux discovery. But @AkucherGCIO @andaleliz - would you mind checking with the eBen team (Jason Wolf PM/Steve Kovacs DEPO PO) on timeframe of their wizard, to determine if we need to include it here (or omit, and handle as future work when they're launching)?

**Comment by andaleliz** [comment]
@jenniferlee-dsva, the PDF you linked above ([How-to wizards hard to find (PDF)](https://app.zenhub.com/files/133843125/87e61032-a83c-49d1-8677-a0dc51ff3931/download)) has one page with the heading `The Solution`. Is there a corresponding problem statement page?

**Comment by jenniferlee-dsva** [comment]
Hmm, I must have forgotten to include the contextual slides. LMK if this updated upload doesn't work, and I can Slack you the file.

**Comment by andaleliz** [comment]
@jenniferlee-dsva was not able to upload - slides shared in [this Slack message](https://dsva.slack.com/archives/C52CL1PKQ/p1583429309440400)

**Comment by MickinSahni** [comment]
2020-03-16 PW Standup
* Completing taxes as an analogy for this Veteran-facing problem
  * i.e. they start with the solution—a particular form—rather than with the problem. This may result in them completing the wrong form

**Comment by jenniferlee-dsva** [comment]
We discussed this on the DEPO product call today and got a go-forward.  
1/ John Hashimoto will take this on as PO.  
2/ @AZSchneider would like a walkthrough of the user flows for the affected applications. 
3/ @john hashimoto will reach out to get that started with @andaleliz, @mattpointzxer0 @AZSchneider (and include me and @mnorthuis as optional attendees).

**Comment by johnhashva** [comment]
At walkthrough of user flows with @AZSchneider  and @mattpointzxer0 led by @andaleliz today, next steps outlined:
- Get representative front-end engineers to discuss preserving ability to throttle traffic to impacted app pages -- in particular new Higher Level Review page planned 
- @mattpointzxer0 will provide a walkthrough for EDU stakeholder to ensure no concerns
- Then, re-connect to decide which teams -- PubWebsites or Apps -- will take on the work.

**Comment by johnhashva** [comment]
@andaleliz I reviewed the user flows -- with focus on Higher Level Review -- with @luke-gcio and @ndsprinkle and we will need to make adjustments to reflect the actual flow from the [How to file disability claim ](https://staging.va.gov/disability/how-to-file-claim/) to HLR which is still in development.  Recommend we set a quick meeting next week with @kevinstachura and @chrvalla to iron out.

**Comment by andaleliz** [comment]
@johnhashva, that sounds good. I didn't realize the How to file a disability claim page would link to HLR.  The flows I created just show how the wizard planned for the HLR content page will now be moved to the form intro page (which you have prob already realized).

**Comment by johnhashva** [comment]
@andaleliz got it.  Still be good to sync with Kevin and Chris to firm up things, agree?  Do note: Luke said his team would be open to taking on this work.

**Comment by andaleliz** [comment]
yep, that sounds good to me!
-- 
Liz Lantz
UX Designer, Ad Hoc
843-898-4463
http://adhoc.team

**Comment by johnhashva** [comment]
Updates:

- @mattpointzxer0 provided walkthrough for EDU stakeholder and one concern was raised, per Matt: 
losing the ability to direct-link to form starts via Direct Mail their primary form of marketing.  This is **not a blocker**, more of a concern that we should think about mitigating, if possible.
- @mattpointzxer0 is also tracking down via the VA education team the number of  eligible vs. ineligible submissions received so can track against this as a key success metric. 

Still To Be Done: 

- Get representative front-end engineers to discuss preserving ability to throttle traffic to impacted app pages -- in particular new Higher Level Review page planned; @stephorkandatx will organize
- Meet with HLR design team to ensure our understanding of the flow is accurate; we may need to tweak things a bit to reflect pathing from the Wizard, per @luke-gcio.  Meeting set for 3/29.
- Work with Analytics team to determine if/how to quantify the success of this bet -- e.g. increase use of Wizards leads to more eligible submissions.


Then, re-connect to decide which teams -- PubWebsites or Apps -- will take on the work.

**Comment by jenniferlee-dsva** [comment]
Hi @johnhashva - for the success measure - I would also include reduction in wrong submissions. They're a little overlapping but not necessarily bc there will always be a certain amount of ineligible submissions (bc eligibility rules are super complex for some things); also adding the wizard as a prerequisite step could reduce overall #s of submissions in general -- but still lead to better ratio of good to bad submits.

**Comment by johnhashva** [comment]
Got it, @jenniferlee-dsva.  Let me ask @AZSchneider and/or @mattpointzxer0  see if there is a distinction made between "ineligible" and "wrong" in our assumed data capture process.

**Comment by mattpointzxer0** [comment]
This is what I was trying to say on slack yesterday; it is not possible to equate and "ineligible" and "wrong". In some situations they could be, but not always. I am trying to track down from EDU the number of eligible/ineligible determinations for each of their forms.
Up to you guys to determine if that distinction matters to you or not...But it is a distinction.

**Comment by johnhashva** [comment]
For posterity, the Higher Level Review Wizard clickable prototype is here:
https://vsateams.invisionapp.com/share/W5U21BDFTQK#/404075470_HLR_-_Info_Page

**Comment by johnhashva** [comment]
Updates:

- @mattpointzxer0 reports that his education SME says "eligible vs. ineligible" benefits for [education benefits](https://www.va.gov/education/eligibility/) is not tracked at any level.   That said, anecdotally, his SME says there have been far too many cases of "ineligibles" for a STEM education benefit -- and he is checking to see if there is data that quantifies that.
- the Analytics team is expecting to complete their [wizard tracking evaluation ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8572) this week.
- @AZSchneider will meet with me this week to zero-in on the requirements for page gating/throttling to help engineers finalize the implementation approach
- @stephorkandatx will schedule a meeting for the product leads later this week to close any final gaps and determine how to divvy up the development effort across [disability ](https://www.va.gov/disability/eligibility/), [education ](https://www.va.gov/education/eligibility/) and [HLR ](https://www.va.gov/decision-reviews/higher-level-review/)

**Comment by stephorkandatx** [comment]
@johnhashva meeting currently scheduled for Wednesday

**Comment by johnhashva** [comment]
Status Update:

- **Execution Plan:**Transitioned execution to  @AZSchneider and @mattpointzxer0 and their teams today, as agreed.  

- **Delivery Timeframe:** Aspirational is for launch in June to couple with Public Websites launch of the full Find a Form/Form Details redesign experience, however the teams (Education, Disability, HLR) are involved in high priority projects at this time -- so July/August may be more realistic. @mattpointzxer0 will provide an update in the next week.

- **Success Metrics:** Analytics team is recommending  the approach already taken with the education benefits wizard  -- e.g. GA can report on “Started Education How To Apply - Did not Complete [Funnel Segment]” as it could be a good proxy for success if we apply this across the HLR and Disability wizards as well.   The KPI would be to show reduced bounce rate on the Wizards – implying that a more informed veteran would then be prepared to apply (e.g. reduction in ineligibles).

**Comment by andaleliz** [comment]
Since this epic is labeled [Discovery], and discovery has ended, should we close it out? 

Or is the implementation work done by other teams covered in this epic as well (and perhaps some dependancies need to be added)?

**Comment by johnhashva** [comment]
Agree, I will close this out as I've captured all essentials [in this Epic](https://app.zenhub.com/workspaces/vsa-5dcabe208aade000013aafba/issues/department-of-veterans-affairs/va.gov-team/9665) which is meant to guide the development activities by the Ed & Benefits team.
