### ISSUE TITLE
Business intake form for CTO Consulting Team

### ISSUE THREAD

**Issue by lexicalninja** [department-of-veterans-affairs/va.gov-team#63154]
## Your Details
1.  Patrick Saxton and Alastair Dawson
@lexicalninja @kreek ​

2.  **Business Line**
    CTO consultation 
​
## Notification Details
1.  **Notification type**
    email
​
2.  **Please describe your use case.**
As part of a request from Charles Worthington and Cory Trimm to gather information on the VA platforms, we have been asked to make an app with an integration into the VA system. VANotify was identified as a system to integrate in the lower environments with our sample/example app that we launch in each of the platforms.

​
3.  **What actions can the user take based on the notification they receive?**
 no actions after
​
4.  **What is the desired business outcome?**
       Have a sample app that is integrated with VA systems so that we can find all the potholes in each of the platforms when spinning up new business lines or applications
​
​
5.  **What system will kick off the notification? Please note the system should be inside the VA or have an ATO.**
    our test app

6.  **What will trigger the notification?**
   api call or similar

7.  **Provide sample content per notification type, if you have it.**
    NA
​
8.  **Has a Privacy Officer (PO) seen and approved the content? If not, do you know who your PO is?**
   NA
​
9.  **Would you prefer to provide contact information for the recipients or would you rather VA Notify look this up for you by Veteran ID? If by ID, please let us know what identifier is used in your system.**
    (ex., VAPROFILEID, PID, BIRLS, ICN, etc.)
​NA

10.  **Do you currently capture communication preferences related to this notification? If so, please describe.**
    No
​
11.  **What is the anticipated volume of notifications per day, week, month?**
​low
12.  **When does this notification need to be in production?**
Never

**Comment by mjones-oddball** [comment]
Hi @lexicalninja - I read through your intake form. How soon do you want to get started on this? I could look for dates/times next week between W - F or the following week for a kick off.

**Comment by lexicalninja** [comment]
Next week would be awesome, @kreek does that work for you, since youre going to have to do the heavy lifting until they reissue my network creds?

**Comment by kreek** [comment]
@lexicalninja next week works for me.

**Comment by kreek** [comment]
Hi @mjones-oddball, 8/10 at 10:30: AM ET works for us. Thanks!

**Comment by lexicalninja** [comment]
patrick.saxton@adhocteam.us
alastair@adhocteam.us

**Comment by mjones-oddball** [comment]
Sent an invite for 8/10 at 10:30 am

**Comment by mjones-oddball** [comment]
@kreek I sent you an encrypted email with your api key and added you to our Staging self service portal. Let me know if you have any questions!

**Comment by mjones-oddball** [comment]
@kreek just wanted to check in and see how things were going. Anything VA Notify can do to support?

**Comment by kreek** [comment]
Hey @mjones-oddball, thanks for checking in! 😄 We don't have any questions or blockers at this time. We're currently working on getting set up in our dev environment, and once that's done, we'll start testing out VA Notify there.
