### ISSUE TITLE
Additions to .gitignore in manifests repo for helm charts

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#63160]
Add Chart.lock and anything in /charts to .gitignore in the manifests repo. We currently don't have an entry in .gitignore for the `Chart.lock` and `/charts` directory. These shouldn't be committed to source control and therefore can be added to .gitignore.

**Comment by laineymajor** [comment]
@LindseySaari and @holdenhinkle please add additional detail to this ticket. Thanks!

**Comment by laineymajor** [comment]
Lindsey reviewed and approved, but this is not merged yet.

**Comment by rmtolmach** [comment]
I approved and merged. 

### Validation:
A modification to a `Chart.lock` file should not show up as a modified file in git. 

**Before (without the gitignore changes)**
<img width="527" alt="Screenshot 2023-11-20 at 11 22 57 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/10993987/a834bfcd-1592-45ea-a58d-5c2c4b7616ab">
This file shows up as being modified. That is expected here. 

**After (with the gitignore changes)** 
<img width="657" alt="Screenshot 2023-11-20 at 11 24 06 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/10993987/eca271d0-d431-4f01-b35e-0a17a1df2c20">
The file still shows up as modified. Not expected 😕 

Why? Lindsey noticed there is _another_ gitignore file ([apps/sign-in-service/.gitignore](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/main/apps/sign-in-service/.gitignore)) that is probably overriding the main one.

**Comment by rmtolmach** [comment]
this can be closed because it adds a global .gitignore config with the option to override for each application
