### ISSUE TITLE
[FE] 10-10EZ - Enable Feature Toggle for Screener Question Removal in Prod

### ISSUE THREAD

**Issue by longmd** [department-of-veterans-affairs/va.gov-team#63167]
## Description
Once we have the resubmission bug fixed and the confirmation page for ID form data in place, we can enable the feature toggle to remove the screener questions. 

## Tasks
- [x] Enable feature toggle for all users
- [x] Refer to PM for sign-off of feature use

## Acceptance Criteria
- Feature toggle is successfully enabled for all users

**Comment by hdjustice** [comment]
Tested change in production, and the screener page is working as expected.  The Read-only page displays the information correctly and does not impact the data entered on the subsequent screens.  Looks great!
