### ISSUE TITLE
DR | Refactor "date validations" into shared directory

### ISSUE THREAD

**Issue by rocio-desantiago** [department-of-veterans-affairs/va.gov-team#63177]
## Value Statement

**_As a_** developer
**_I want to_** refactor the common validations shared across the 3 forms: 995, 996 and 10182 (SC, HLR & NOD)
**_So that_** tech debt is reduced and so that future developers don't have to make the same change across the shared validations in SC, HLR & NOD redundantly.

## Background Context

- Research was completed with the assistance of GitHub codeclimate.
- Related ticket: [DR | Investigate Decision Reviews forms refactoring](https://github.com/department-of-veterans-affairs/va.gov-team/issues/62362 & [DR | Refactor validations into shared directory](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63134)
- The following files will be refactored into one shared utils directory:

**date**

> [src/applications/appeals/10182/validations/date.js](https://codeclimate.com/github/department-of-veterans-affairs/vets-website/src/applications/appeals/10182/validations/date.js)
> [src/applications/appeals/996/validations/date.js](https://codeclimate.com/github/department-of-veterans-affairs/vets-website/src/applications/appeals/996/validations/date.js)
> [src/applications/appeals/995/validations/date.js](https://codeclimate.com/github/department-of-veterans-affairs/vets-website/src/applications/appeals/995/validations/date.js)

## Out of scope

* Other apps/forms not in Decision Reviews

## Tasks

- [ ] One shared directory created
- [ ] Unit tests updated
- [ ] E2E tests updated
- [ ] Validate that forms functionality has not changed

## Definition of Ready 

- [x] Have access to decision reviews folder (src/applications/appeals/{appName}/utils) in vets-website repository 
  > 995 - Supplemental Claims (src/applications/appeals/995/validations)
  > 996 - Higher Lever Review (src/applications/appeals/996/validations)
  > 10182 - Notice of Disagreement (Board Appeal) - (src/applications/appeals/10182/validations)

## Definition of Done

- [ ] Functionality not changed
- [ ] Reduced files
- [ ] CodeClimate warnings go away

**Comment by rocio-desantiago** [comment]
**Between 995, 996, and 10182 (all 3)**
`errorParts`, `isValidDate`, `partsError`

**Between 996 and 10182**
```
if (
    !year ||
    !day ||
    day === '0' ||
    !month ||
```

**Comment by HeatherWidmont** [comment]
@Mottie doing code review, if it looks good then we can close this ticket

**Comment by saderagsdale** [comment]
@Mottie Is this good to close? Can you update with a comment?

**Comment by rocio-desantiago** [comment]
@saderagsdale not yet. Addressing some code feedback.

**Comment by HeatherWidmont** [comment]
Found things that were out of scope for this ticket, @rocio-desantiago will bring that into refinement. She's currently addressing a couple more comments & will be pushing the changes later today

**Comment by saderagsdale** [comment]
@rocio-desantiago can you create a ticket for the new work?

**Comment by HeatherWidmont** [comment]
@data-doge will review this either today in the parking lot or later this afternoon
