### ISSUE TITLE
Soft launch of Find Forms search page

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#6317]
Per this [comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/5693#issuecomment-592645033), we're ready for a soft launch of Find Forms. This mean to publish the [Drupal page](http://preview-prod.vfs.va.gov/preview?nodeId=2352), but prevent it from showing in search results. This way, we can share with stakeholders to evaluate without it going completely public.

## Acceptance criteria
- [ ] Find Forms search page is published to www.va.gov/find-forms
- [ ] Implements Basic Auth to prevent crawlers from indexing it

Soft launch GH folder: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/find-va-forms-redesign/soft-launch

**Comment by ncksllvn** [comment]
Full launch is here - https://github.com/department-of-veterans-affairs/va.gov-team/issues/5589

**Comment by AkucherGCIO** [comment]
03/02/20 PW Standup
- Going live on the site and no SEO is needed.
- Phase 1 MVP is parity with VA.gov site.

**Comment by AkucherGCIO** [comment]
03/04/20 PW Grooming.
@jenniferlee-dsva will be setting up a meeting with @kevwalsh @mnorthuis to discuss the alternative that Kevin posted in Slack today before we soft launch.

**Comment by jenniferlee-dsva** [comment]
FYSA - added soft launch GH folder link to original ticket info ^

**Comment by AkucherGCIO** [comment]
03/06/20 PW Standup
DevOps needs to help with this deployment.  We might have to wait for the DevOps cycle.

**Comment by ncksllvn** [comment]
Adding @RLHecht to publish the page in Drupal

**Comment by RLHecht** [comment]
This page has been published.

**Comment by ncksllvn** [comment]
Should be live today!

**Comment by AkucherGCIO** [comment]
Closing this ticket as it went live on Friday, March.6th 2020.
