### ISSUE TITLE
Create backend onboarding project

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#63186]

**Comment by bosawt** [comment]
ntroduction

* I have a simple web app, and I want to give my users the ability to log in, see some personal information about themselves, and navigate throughout my web app. However, I don’t have the resources, or ability, to create a credential service, or session management for my users. What I want is the ability to send my users to another service where they can create an account, or sign in, and which my application can offload general authentication and session responsibilities to


## Requirements

* We need to create a Rails application which accomplishes the following:
* Provides an OAuth interface for authentication
  * This includes the ability to authenticate and generate tokens for my users
  * This also includes the ability to extend my session if necessary
  * I must also be able to log out my users
  * If we want, we can have minor diversions from the standard OAuth flow if they make sense, don’t worry about pedantically supplying everything necessary to make OAuth compliance
* Gives my users the ability to navigate to a page where they can create or sign into their account on a browser (I don’t want to force them to type their credentials in a URL or anything weird like that)
  * I am fine if this application leverages existing credentials, like Google login, Apple login, or Login.gov
* I should be able to request for specific data about my users (in this case I’d like their email, first name, and last name) once they’ve authenticated

## Deliverables

* To accomplish this work, it is expected that we use similar processes and deliverables to the Identity team today, this includes:
  * An initial planning session to create tickets for work
  * Weekly progress checkins (feel free to ask for clarification, comments, or even paired work more often though!)
  * Specific tickets describing individual facets of work (can be done in any project planning free tool, like Trello or anything you prefer)
  * A Github repository for the application with:
    * PRs that are associated with a ticket, well commented and described, and approved before merged into main
  * A final presentation of the work


## Resources

* Feel free to use any resources you’d like for this work, this includes the Sign in Service in `vets-api` (yes, this application will be very similar to the Sign in Service, feel free to copy any aspect of it that you’d like)
* Sign in Service is a tool that the Identity tool has created to facilitate an OAuth authentication and session management
  * The controller is located here: [vets-api/app/controllers/v0/sign_in_controller.rb at master · department-of-veterans-affairs/vets-api](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/controllers/v0/sign_in_controller.rb)
  * This repository describes a client for the Sign in Service (which sets up an integration of Sign in Service and communicates with it. This repository would be analogous to ‘my  simple web app’ in the introduction of this project): [department-of-veterans-affairs/sign-in-service-client-sinatra: A sample app interfacing with Sign-In Service built with Sinatra](https://github.com/department-of-veterans-affairs/sign-in-service-client-sinatra)
* To research this work, SuperTokens is a great place to start, and the inspiration for the Sign in Service: 
  * Documentation: [User Recipes](https://supertokens.com/docs/guides)
  * Blog: [Open Source Authentication](https://supertokens.com/blog)
  * Session Management: [All you need to know about user session security](https://supertokens.com/blog/all-you-need-to-know-about-user-session-security)
* I would research the OAuth Specs as well
  * [Specs](https://oauth.net/specs/)
    * Look through some of the RFC section of that. It’s very dense, but technically all of the OAuth information is there

**Comment by aparsley** [comment]
Keep up the good work!
