### ISSUE TITLE
Aggregate Poster Pilot Feedback Data

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#63188]
## Background
Now that the Poster pilot is completed. Let's aggregate the [feedback data](https://dvagov-my.sharepoint.com/:x:/r/personal/lori_pusey_va_gov/_layouts/15/doc2.aspx?sourcedoc=%7B5d062c85-a394-4f27-84f8-00b166fb8e57%7D&action=edit) that we received.

**Comment by benbrasso-agile6** [comment]
@loripusey I need permission to review that document benjamin.brasso@va.gov

**Comment by loripusey** [comment]
you should have edit permission now

**Comment by benbrasso-agile6** [comment]
@loripusey i categorized and broke into percentages, fyi 

I'll do something with them in the slides

[Patient Check-in Poster Pilot - July 2023.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcU1PIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e9ce6d7cd6e2c6c0e59ce75674677fd97c471dbe/Patient%20Check-in%20Poster%20Pilot%20-%20July%202023.xlsx)

Right now, this file is just local

**Comment by benbrasso-agile6** [comment]
Posted presentation in slack https://dsva.slack.com/archives/C022AC2STBM/p1692303115417709
