### ISSUE TITLE
Request for elevated DataDog permissions

### ISSUE THREAD

**Issue by JRRoof** [department-of-veterans-affairs/va.gov-team#63184]
The Appointment team back end engineers who are responsible for monitoring the production deployment of VA online scheduling require access to DataDog in order to trouble shoot alerts and issues with the application and environment. The following members of our team require read-only access:

Clayton Hickok - [clayton.hickok@va.gov](mailto:clayton.hickok@va.gov)
William Thompson - [william.thompson1@va.gov](mailto:william.thompson1@va.gov)
Thomas Joyner - [thomas.joyner@va.gov](mailto:thomas.joyner@va.gov)
Paul Pearson - [paul.pearson1@va.gov](mailto:paul.pearson1@va.gov)

The following members of the team require write access:

Ryan Lemire - [Ryan.lemire@va.gov](mailto:Ryan.lemire@va.gov)
Mohammed Jabber - [mohammed.jabbar@va.gov](mailto:mohammed.jabbar@va.gov)
Nicholas Daily - [Nicholas.Daily@va.gov](mailto:Nicholas.Daily@va.gov)
Laith Al-Samir - [Laith.Al-Samir@va.gov](mailto:Laith.Al-Samir@va.gov)

**Comment by lindsay-insco** [comment]
Access was granted
