### ISSUE TITLE
Contact Center Review for Profile - Notification Settings Updates and Removal of Terms and Conditions Section

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#63198]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
*Please provide the name(s) of your product and a high-level description of your product.*

We have two things that go hand-in-hand, to prepare for adding email as a channel into the notification settings of the profile, we've updated the UI to move away from radio buttons to checkboxes. This is to reduce the number of items in the UI, when we add in notification items that use email as a channel, the radio button build would have been too repetitive.  Email will not be added at this time a future update will be required to document those changes, this is simply paving the way for those future modifications. 

In addition, from the notification screen we're introducing a new workflow that allows users to edit their phone/email by entering a 'sub-task flow' directly from the notification settings screen. To do this you simply follow the alert at the top of the notification setting screen. User flow [here](https://www.sketch.com/s/1fd4d140-84ad-4301-9c74-d5cebc4a012d/p/293F15EA-9CCC-466C-A3B7-3E54E3111676/canvas) 

You can use the testing steps 1-22 [here](https://docs.google.com/spreadsheets/d/1-oSUr_kFqyptbSI6jRC3O7wqk3TNDOwaWedmO3eh7FA/edit#gid=1459792507) to review the changes in question. 

**updated checkbox ui** [mobile](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/v/jWZp8o/p/B5792AF8-87F2-496D-AE7A-DAD1448A6018/canvas?posX=-472.97586814237275&posY=-3773.829280008568&zoom=0.4474524259567261) or [desktop](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/v/jWZp8o/p/C9FF1DE2-F54A-4E1F-9847-4A2799011AB8/canvas?posX=-995.6449693643194&posY=-585.0924328454164&zoom=0.2667314410209656)

**editing subtask** [mobile](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/v/jWZp8o/p/B5792AF8-87F2-496D-AE7A-DAD1448A6018/canvas?posX=-4435.966849366007&posY=-6065.156301898397&zoom=1.1932064294815063) or [desktop](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/v/jWZp8o/p/C9FF1DE2-F54A-4E1F-9847-4A2799011AB8/canvas?posX=-9587.242579130045&posY=-673.0947528964489&zoom=0.37466806173324585)

#### Email as a channel/checkbox UI/default send #61101  
[Project Outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/notification-preferences/default-send) 

#### Editing as a subtask #49319
[Initiative Brief ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/contact-information/mobile-phone-edit-flow/README.md)

### Launch Date
*Please provide the launch or rollout date and details.*
TBD - hoping for late August early September 2023
[Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/notification-preferences/default-send/releasePlan/defaultSendReleasePlan.md) will be updated with dates once we complete QA 

### Version Number
Version 6

### Product Guide
[Profile Product Guide Directory ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/product/product-guides.md)

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
The draft looks good. I will share this with VEO for their review.

**Comment by starlow00** [comment]
No changes from VEO. A working copy is attached.
[VAgov.Profile.v6_SRT08302023.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/12516657/VAgov.Profile.v6_SRT08302023.docx)
