### ISSUE TITLE
Unable to complete due to lack of Zip Code

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#63205]
![FB Screenshot.png](https://images.zenhubusercontent.com/646e747a1a53d1c4194a124b/0581a037-962a-4eac-9130-832e8dabc3a2)

Per email forwarded from Matt Self:

From email: VBA Office of Communication intercepted a Facebook message from an overseas Veteran who claims, “I have a intent to file on VA.GOV for six months now. I can't complete it because a zip code is required. I'm overseas and we use Postal Codes. any remedy for that? except mail it in? thanks”

From Khristina Sly, Digital Media Specialist in email "I’m wondering if there's a work around available that we can share with them - like entering 11111 or 00000 to "flag" that it's an overseas claim and for them to still be able to successfully submit it for review/consideration"

**Comment by micahaspyr** [comment]
Looking into the codebase of vets-api, 00000 is used for veterans with international addresses for various forms.  This could be something we need to ask EVSS about as their API handles the creation of ITFs.

**Comment by austinjprice** [comment]
Short term solution - Austin to reach out to Kristina Sly with 00000 solution

Long term solution - Austin to start convo with Dependents team about their discovery

**Comment by austinjprice** [comment]
Closed as user is no longer reachable and fix pending redesign and implementation from @steele-lm team
