### ISSUE TITLE
Fix broken CDC link on COVID-19 pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#63208]
## Issue Description

We got a SiteImprove report of a broken link on several COVID-19 pages. We need to update these. If there isn't a new link, we should remove it.

Broken link: https://www.cdc.gov/coronavirus/2019-ncov/vaccines/different-vaccines/mrna.html

Pages link is on:
- [About COVID-19 vaccines](https://www.va.gov/health-care/covid-19-vaccine/about-covid-19-vaccine/) (English, Spanish, and Tagalog) The link is in the accordion labeled "mRNA COVID-19 vaccines don’t change your DNA"
- [COVID-19 vaccines at VA](https://www.va.gov/health-care/covid-19-vaccine/) (English, Spanish, and Tagalog) The link is in the accordion labeled "Currently available COVID-19 vaccines"

## Tasks
- [x] Fix or remove broken link
- [x] Review (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [ ] COVID-19 pages no longer have broken link on live site

**Comment by megzehn** [comment]
Validated. Closing.
