### ISSUE TITLE
Implement Checkbox compontent

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#6320]
## User Story or Problem Statement
Given that the users will need to check boxes on the 1010-CG (for signature and healthcare selection)
I want to implement the checkbox component
So that we can add the functionality while maintaining accessibility and design standards.

## Acceptance Criteria
- [ ] Checkbox component added
- [ ] Merged to master
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by starofaragon2010** [comment]
Hi 
@ala-yna 
As a reminder, you may need more than 2 check boxes as it could be filled out by 1 vet, 1 primary, and 1 secondary

**Comment by ala-yna** [comment]
Hi @starofaragon2010 - thanks for the reminder! What's your name? I don't see your name in your GH profile - just want to make sure I can put names to conversations :)
