### ISSUE TITLE
Drop the "depo" from PW URL

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#63213]

**Comment by johnny-jesensky-adhoc** [comment]
As part of the icebox [audit ticket](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/69802) in Sprint 41, we'll be keeping this in the icebox.

**Comment by johnny-jesensky-adhoc** [comment]
Closing this out for now - maintain idea outside of Zenhub.
