### ISSUE TITLE
[ISSUE] Research large file upload patch options

### ISSUE THREAD

**Issue by SamStuckey** [department-of-veterans-affairs/va.gov-team#63218]
# EVSS Downtime problem research

## Purpose
Tie up loose communication threads around the problem of EVSS downtime as caused
by large document uploads.

## Resources
- This work is currently spinning off of this [EPIC](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/62913)
- Slack channels
    - `lighthouse-delivery-platform-support` for general support from LH, if needed
    - `vfs-evss-service-migration` for questions about the EVSS -> LH migration
- Slack Threads
    - [Steve A -> team](https://dsva.slack.com/archives/C05462H2D6V/p1691086966630549) 
    - [Sam S -> team](https://dsva.slack.com/archives/C053U7BUT27/p1691423435109849)
-  Human touch points
    - @mchae-nava has context on LH migration timeline
    -  @kylesoskin if generally knowledgable and available
    -  Michael Harlow (LH senior Tech Lead) may be available good point of contact for tech questions on migration between EVSS and LH
    -  Janet Coutinho (lighthouse PM) may be available to help delegate more complicated questions to her team.

## Action Items:

1. Will LH fix this issue? (async)
    - the answer to this question will inform follow up work, but not these
      action items
        - if YES: the minimal patch outlined in these action items will be sufficient
        - if NO: the minimal patch outlined here will eventually need to be replaced with a more robust fix.
        - if UNCERTAIN: put the patch in place and plan to keep an eye on this after the migration

ANSWER: Probably.  The issue is caused by the splitting up of big files on EVSS.  LH will not be doing this, so we almost certainly will not have to deal with this after the LH migration is complete.  **HOWEVER we should plan on using EVSS for the next year or so**, so we still need to fix this.

2. Questions for EVSS
    - What EVSS endpoints are affected? 
        - this will inform WHAT we throttle in our patch.
    - Is it a complete outage or a slow down?
        - this will inform HOW MUCH we throttle in our patch.
    - Does EVSS have a queuing system we could use to push our jobs to so we don't have to worry about throttling?
        - almost certainly not, but worth asking before we build a solution on our end.
    - How long does it take the affected endpoint(s) to get back online?
        - This will inform HOW LONG we throttle for.
        - On what is it dependent?  is human intervention required?  Or will it automatically reboot eventually?
            - this will inform how we know WHEN TO STOP throttling.
        - what error code / message or combination of conditions can we use to reliably identify this issue starting.
        

3. Plan for a patch
    - If we decide to throttle: we MUST ensure no jobs are lost while waiting to be sent to EVSS.  This will require a robust, persistent queue.  
        - does sidkiq support this?  How robust is it?
        - Who offers a service like this?  AWS?  what's it called?  what's the cost?
        - What is the timeframe for executing on this?
     - IF there is a non-throttling option, we may want to consider it
        - EG robust failure logging allowing for manual retries?  Probably a bad example....
        - May not be an option, but we should at least think about it.

4. Execute on a patch
    - build / leverage queuing system
    - code patch

5. Test patch
    - this is important enough we should probably roll it out to a small number of applications as a test.
        - his work will require its own failsafe, most likely.
    - testing code should be simple.  testing the queue is probably harder.

**Comment by SamStuckey** [comment]
Passing off to @micahaspyr for execution

**Comment by micahaspyr** [comment]
Some of this is taken from the Slack thread stated in the description just for organization.

In the last 2000 submissions, that had uploads, there were a total of 6570 uploads. Of those, 35 were over 50MB or ~0.5%
- Hard 50MB limit as a temporary work around? 
  -  Probably fixes the crashing issue seen across the app but would need to be temporary

From Michael Harlow:
   
   - The EVSS document-services server crashes when iText gets stuck in an infinite loop trying to split large PDFs. These requests timeout 
   because the server is unable to respond. If we assume all requests that timeout shouldn't be retried, someone would need to manually upload 
   them to eFolder and manually update the suspense date. Not fun. Instead, VA.gov should start migrating to the Benefits Documents API that 
   Lighthouse released in prod last week.

**Comment by micahaspyr** [comment]
Saw this link in the #vfs-all-teams slack channel that was shared today.  Lists who the contacts are for EVSS.  May not mean much but at least we have some more names https://github.com/department-of-veterans-affairs/lighthouse-ux/blob/master/Benefits%20and%20Appeals%20Research/2023-05-EVSS-Playbooks-Draft/Draft%20EVSS%20Playbook%20Template.md
