### ISSUE TITLE
Re-check unified 2.0 release knowing that VeText 45 min text won't be ready

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#63221]
## Description 

Stephen mentioned we could just start with editing pre-check-in and check in messages. That might be a better way to evaluate what we need to change in our wireframes. 

## Tasks

- [x] Evaluate release 2.0 to ensure it's consistent exp for Veterans

**Comment by benbrasso-agile6** [comment]
https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/F05730C4-9E76-4B1D-AEA0-63CEC7E61175/canvas#Version

Think this is good. @loripusey You want to validate and close?

**Comment by loripusey** [comment]
Looks good, I think it might be helpful to split up each release into its own Sketch file. Trying to navigate the hole thing is going to be error-prone for the engineers.  Can we start with having a separate file just for release 2 and I'll put a link to that in the release 2 tickets. Thanks @benbrasso-agile6

**Comment by benbrasso-agile6** [comment]
@loripusey 

https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/868762F3-8E8F-4E23-B0DA-34C1783F0A03/canvas

Do you want to place this link in the appropriate tickets for engineers?

**Comment by benbrasso-agile6** [comment]
Closing
