### ISSUE TITLE
Best bet request for Pension Deactivation

### ISSUE THREAD

**Issue by kristinoletmuskat** [department-of-veterans-affairs/va.gov-team#63238]
-  Select Request Type:
    - [ ] NEW: You would like to create a new best bet
    - [X] CHANGE: You would like to change an existing best bet

### Description
Please provide a description and supporting information for the new best bet, or the existing best bet you want to change. Include any research or data you have to support the request. 

 - here's our google doc that links to the initiative: https://docs.google.com/document/d/191ygG1BkqM-QPoBCoXmkyxZOFSCdcuzkCrcuV3R4gu4/edit

| Keyword        | Action needed                                                                                                                                              |
|----------------|------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 21p527ez       | Add this keyword to https://www.va.gov/find-forms/about-form-21p-527ez/ instead, and remove from https://www.va.gov/pension/application/527EZ/introduction |
| Form 21p 527ez | Add this keyword to https://www.va.gov/find-forms/about-form-21p-527ez/ instead, and remove from https://www.va.gov/pension/application/527EZ/introduction |

**Comment by jennymayoco** [comment]
Looks like this might be a duplicate. Added feedback to [#63240](https://app.zenhub.com/workspaces/sitewide-content-accessibility-and-ia-63a1d63232beba0011a7833f/issues/gh/department-of-veterans-affairs/va.gov-team/63240)
