### ISSUE TITLE
Begin discussion around type-ahead component for medical facilities

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#6323]
## User Story or Problem Statement
As a user
I want to filter the list of VA medical facilities in my state by typing the first few letters
So that I don't have to search through the whole list

## Notes
See: 
- There are some filter/autosuggest patterns in the GI Bill Comparison Tool - cc @Darrell Neel @Will McCormack @Amy Knox 
- Also in disability compensation @Andrea Schneider @Ming Ligh

**Comment by will** [comment]
Hi, I don’t think you meant me when you @ mentioned my github username?

**Comment by starofaragon2010** [comment]
Hi team, 

Is it typing the first few letters of the state, name of facility?

Reminder: Issue is that what people call the facility vs actual name of the facility may not be the same AND some facilities have the same names but are in different states

**Comment by LinnJS** [comment]
Discussion: https://dsva.slack.com/archives/CBU0KDSB1/p1583850252178400
