### ISSUE TITLE
Content support for unified terms of use UI

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#63260]
Core identity team is taking over the new unified terms of use flow for VA.gov. Sitewide content team previously drafted UI content for a version of this flow. We've also worked on editing the legal terms of use.

Ahead of usability testing with Veterans at the end of August, we'll provide content support on the updated UI in the Figma prototype. Laura synced with Amber, Mike, and Tom from Core Identity, and they confirmed that no legal/policy review has happened outside of the work our team did with policy reviewers over the past several months. 

- [Core identity team's Figma prototype](https://www.figma.com/proto/Fhw9P7r6pyaCGXRmolruoQ/Terms-of-Use?type=design&node-id=227-26&t=6Iu86HTNhe9kB8yC-0&scaling=scale-down&page-id=0%3A1&starting-point-node-id=381%3A31&show-proto-sidebar=1)

- [Terms of use UI content the sitewide content team presented to ToU working group](https://dvagov-my.sharepoint.com/:w:/g/personal/danielle_thierry_va_gov/EUJ2CL4M4QZHvtC036A9dMkBSAskrTEgRYAFC40dlpzRtQ?e=HqzNbC )

- [In-process text of the unified terms of use (still under privacy review, not final)](https://gcc02.safelinks.protection.outlook.com/ap/w-59584e83/?url=https%3A%2F%2Fdvagov-my.sharepoint.com%2F%3Aw%3A%2Fg%2Fpersonal%2Flaura_willwerth_va_gov%2FEXsNiSN-vA1CoKAmXPOd6mMB_t4ZGnw4fkReC9fNl5rvAw%3Fe%3Dctnbg4&data=05%7C01%7C%7C684474dd629b4efdd4fd08db62164999%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C638211620079434884%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=sP4E7sF9sw4kKcUn1Bqozjz%2FzoqzaxVji%2BEF1%2F1FIUA%3D&reserved=0)

**Comment by laurwill** [comment]
Noting that I'll plan to sync with the Core Identity Team this week about this work.

**Comment by laurwill** [comment]
Hi @aparsley @claytonzook @kingbmike ,
Thanks for meeting to discuss the terms of use UI! I've left a bunch of comments in the Figma file, and documenting my high-level notes here. Let me know if a sync would be helpful to discuss any of this.

**Structure and organization**
- Our suggested UI content presented the "What to know if you don't accept" content on a second confirmation page. Placing everything on a single page adds a lot of additional content a Veteran needs to read or scan through before they get to the required action. And this ToU flow is interrupting a task, so we want to allow them to accept the terms and return to their task as quickly as possible. 
- **Question:** If you want to test this as a single page, could we explore ways to do this without making the Veteran read through all this content before accepting? For example, could we dynamically load the "What to know if you decline" section only after they select "Decline" and then ask them to confirm?

If you keep this content before the Accept and Decline buttons, we'll need to adjust the content order and headers. There's currently a big chunk of content in between the "Do you accept?" question and the answer options — we want to present answers directly after the question. And the information about what happens if you decline is currently split into 2 disjointed sections. 

Here's a suggested heading structure for this single-page approach:
H1 VA online services terms of use
H2 Terms
H3 What to know if you decline these terms
H4 Getting VA benefits and services if you decline
H2 Do you accept these terms?

**Other notes**
- The legal terms content will need an update to match the final version. For now just noting that the lengthy General disclaimer section at the top of the legal terms seems to be missing.
- I suggested changes to the Decline page to fit the scenario of a Veteran declining the terms on purpose. The current content treats this scenario more like an error or mistake — I'd suggest creating separate screens/content for those scenarios.
- If you test with "decline," we should change all instances of "don't accept" to "decline" for consistency.

**Questions**
- Is there a requirement to name the privacy act of 1974, etc, in the page UI? I'm concerned about duplicating or contradicting language that's in the legal terms.
- Will Veterans need to expand all of the accordion sections before they can accept the terms?

**Comment by aparsley** [comment]
@asg5704

**Comment by asg5704** [comment]
@laurwill Sounds good. These are the changes for the Declined page:

![Image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/67602137/b4873913-6edb-4b02-8163-afdeeb1dd284)

**Comment by asg5704** [comment]
@laurwill Additionally, for the Terms of Use page I tweaked the content a little based on conversations you had with Clayton.

- The paragraph below the "Getting VA benefits and services if you don’t accept" header
    - Removes "in person" to keep consistent with Declined page messaging
- Paragraph in the va-alert will be updated to:
    - _If you decline these terms, we’ll sign you out. You can still get VA health care and benefits by phone, by mail, or in person. But  you won't be able to use some online services, like:_
    - What changed: I removed "websites" in favor of "online services"
    - Why: To keep it more general so we can include the VA: Health and Benefits mobile app


![Image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/67602137/33663d06-945c-4037-b19e-3ff9ab7b67d9)

**Comment by laurwill** [comment]
Hi @asg5704 , I missed your last notifications here, my apologies! 

I have a couple more notes:

- On both screens, is there a specific reason you're naming the "MyVA411 main information line"? We aim to use simply "call us" for phone contacts wherever possible. Suggest changing "call our MyVA411 main information line for help" to "call us" unless there's a specific need to name this here.
- On the decline page. we need to remove "Note:" under the "What you can do" header on the decline page. That doesn't flow naturally from that header. The content under the header should start with "You can still get ...."
- In the "What will happen if you decline" box on the main page, we need to adjust the intro to the first bulleted list to be a complete sentence. If this list is complete, we can say "But you won't be able to use these VA online services:" If the list is incomplete, we can say "But you won't be able to use some VA online services, including these services:"

**Comment by laurwill** [comment]
And 2 notes on the legal terms in [this version on dev](https://dev.va.gov/terms-of-use): 

- Where did this chunk of content come from? I don't see this in the legal terms document: 

![Image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/104158104/1808799f-687b-421e-822e-8b0da8351339)

- In the first accordion, the "d" in "General disclaimer" should be lower case.

**Comment by laurwill** [comment]
Hi @claytonzook and @asg5704 , we were also thinking a final copyedit pass on the legal terms language would be a good idea, since that language went through so much close review. Could you let us know when you expect to finish any final updates to the dev or staging version, so we can pass to our copyeditor? 

And of course let me know if you have any questions about my last notes, or if a quick sync would be helpful!

cc @DanielleThierryUSDSVA FYSA

**Comment by asg5704** [comment]
@laurwill my apologies I was out yesterday. For the

> And 2 notes on the legal terms in [this version on dev](https://dev.va.gov/terms-of-use):
> 
> * Where did this chunk of content come from? I don't see this in the legal terms document:
> 
> ![Image](https://private-user-images.githubusercontent.com/104158104/286626111-1808799f-687b-421e-822e-8b0da8351339.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzNjg2NzEsIm5iZiI6MTcwMTM2ODM3MSwicGF0aCI6Ii8xMDQxNTgxMDQvMjg2NjI2MTExLTE4MDg3OTlmLTY4N2ItNDIxZS04MjJlLThiMGRhODM1MTMzOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEzMFQxODE5MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YmE1OTNjOTlhZGZkNTYwNTkyYWU1MmJhZTI0Y2Y5OTlhNDQ1ZjFkOWM3MmYyMjkyZDcyZTNjN2M3Y2JkOWVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.H4k5LSpUm7k9B33epL0H4vOS_A6Rl6HpxAFHH08T29k)

I believe this content was part of the original prototype and was supposed to serve as a general overview for Terms of use but not be a part of the General disclaimer portion.

**Comment by laurwill** [comment]
> @laurwill my apologies I was out yesterday
> 
> > And 2 notes on the legal terms in [this version on dev](https://dev.va.gov/terms-of-use):
> > 
> > * Where did this chunk of content come from? I don't see this in the legal terms document:
> > 
> > ![Image](https://private-user-images.githubusercontent.com/104158104/286626111-1808799f-687b-421e-822e-8b0da8351339.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzNjg2NzEsIm5iZiI6MTcwMTM2ODM3MSwicGF0aCI6Ii8xMDQxNTgxMDQvMjg2NjI2MTExLTE4MDg3OTlmLTY4N2ItNDIxZS04MjJlLThiMGRhODM1MTMzOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEzMFQxODE5MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YmE1OTNjOTlhZGZkNTYwNTkyYWU1MmJhZTI0Y2Y5OTlhNDQ1ZjFkOWM3MmYyMjkyZDcyZTNjN2M3Y2JkOWVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.H4k5LSpUm7k9B33epL0H4vOS_A6Rl6HpxAFHH08T29k)
> 
> I believe this content was part of the original prototype and was supposed to serve as a general overview for Terms of use but not be a part of the General disclaimer portion.

 @asg5704 , if this isn't part of the legal terms, then we need to remove it — all text in the legal terms needs to go through approval with legal and privacy SMEs, and this currently looks like part of the legal terms because it's under that header.

**Comment by laurwill** [comment]
And thanks @asg5704 for making that checklist! For the "call us" item, there are many examples throughout the site where we say "Call us" and then list a phone number, without naming the specific line or office that phone number is for. Here's an example from the [Signing in to VA.gov](https://www.va.gov/resources/signing-in-to-vagov/) page: 
<img width="653" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/104158104/1e56b730-8ff2-47f7-a350-937e3bd2f4ab">

**Comment by kdmeg-bluetiger** [comment]
Hey team 👋 @asg5704 looped me in on the intro text copy (above) that received some feedback. Here are some suggestions for the experience based on whether or not the Veteran is already logged in. In both cases, I'm suggested to lead with "To access your benefits online" language rather than "To sign in" language. Because this emphasizes the value proposition more explicitly. Open to feedback!

**Unauthenticated experience:**
It looks like we need a **button to direct them to log in and accept** the new terms if they’re ready. On the current page there isn’t an action they can take to move forward. We may also need to provide navigational direction on *where* they should go after they sign in to accept the updated terms.

For copy I’d suggest: 
To access your benefits online, read the updated terms of service. Then sign in and [navigate to X] to accept the terms.

 **Authenticated experience:**
We might need to clarify that this action will enable them to *continue* to sign in and access benefits (since they are already signed in).

For copy I’d suggest: 
To continuing accessing your benefits online, read and accept the updated terms of service.

**Comment by laurwill** [comment]
Hi @kdmeg-bluetiger ,
Thanks for these suggestions!

Couple thoughts here:
- We've been using "terms of use" to describe the legal terms, so we should be careful not to vary with "terms of service" here.
- For unauth experience, we shouldn't need to direct them where to go after signing in — my understanding is that any user who has not already accepted the terms of use will get served the ToU flow when they attempt to sign in, no navigation required. @asg5704 let me know if that's not correct!
- And that's a good question about including a way to sign in and accept from the unauth version — we hadn't previously discussed including an entry point to the "accept or decline" flow from the unauth version, so we'll need to confirm this with our IA.
- For auth experience, I'm not sure if we consider them "signed in" before they've accepted the terms. I've been thinking of the ToU acceptance as a required step in the sign-in process. From your team's perspective, is a user fully authenticated on VA.gov **before** they've accepted the terms?

**Comment by laurwill** [comment]
Hi @kdmeg-bluetiger , 

Based on the IA mural and our chats here, here's suggested content updates.

**Unauthenticated intro**
- Adjust to present signing in as an optional next step. 
- Add an action link to direct them into to the sign in flow with the ToU, if they choose to sign in now.

> We've recently updated our terms of use for VA.gov and other VA online services. Read the updated terms on this page. If you haven't yet accepted these terms, you can sign in and accept them now.
> Sign in to VA.gov >

**Authenticated intro**
- Let's keep this intro as is — this content went through several rounds of review with legal and privacy SMEs, and as we chatted above, this is really a step in the sign in flow and not a "continue accessing" step. (It's possible this is the first time a user has signed in to VA.gov.)

Let me know if you want to chat more about this! 

I also see a suggestion in the IA mural to add a link back to the unauthenticated version of the terms from the decline page — what if we add a simple text link "Review the updated terms of use" above the sign in button on that page?

**Comment by kdmeg-bluetiger** [comment]
Hey @laurwill - that sounds good! The authenticated intro copy makes sense to me, and I like your suggested copy for the new link to review the terms from the decline page 👍  Thanks for all your work on this!

**Comment by asg5704** [comment]
👋  Hello all, I will be updating the Figma prototype to represent the expected changes from the Mural and the above content change requests. I want to ensure we finalize it before I start writing code. Also I want to reiterate that there are 3 user states, not 2! They are fully unauthenticated, middle auth (user currently in the process of reading the terms of use but is not completely authenticated), and fully authenticated (user has already accepted).

**Comment by kdmeg-bluetiger** [comment]
Thanks @asg5704 for calling this out! I believe folks who are in the process of signing in are technically still "unauthenticated" since we're forcing them to review the ToU before they complete the sign in process.

cc @laurwill for your thoughts on this 🙏

**Comment by asg5704** [comment]
@kdmeg-bluetiger @laurwill Content-wise yes they will be considered "unauthenticated" however, the UI and available actions are changed. The updated Figma will provide some clarification because we don't want the user to navigate away from this page if we display the "unauthenticated" content like the "Sign in to VA.gov" action link.

**Comment by laurwill** [comment]
Thanks both! I put some comments in the Figma, and @asg5704 is speedily responding and updating :) 

Oh and we had discussed having one of our CAIA copyeditors do an errors and omissions review of the legal terms in staging — is that all up to date and ready for a final copyedit?

**Comment by asg5704** [comment]
@laurwill Yes you can do a finaly copyedit, the last time we modified it was from September 25th. If there has been additional things that has changed since then we will need to update it.

**Comment by laurwill** [comment]
Thanks @asg5704 ! And should what link should we use for that final copyedit? Is this in staging, still in a protoype, etc?

**Comment by asg5704** [comment]
@laurwill You can use the staging one: https://staging.va.gov/terms-of-use

**Comment by laurwill** [comment]
Thanks @asg5704 ! 

Here's suggested intro content for the new flow where an authenticated user who previously accepted returns to the terms page:
> You previously accepted these terms of use. If you'd like to change your answer, you can decline the terms on this page.

And for the "Do you accept?" section at the bottom of the page, the "Accept" button doesn't do anything, right? (I'm assuming we don't differentiate between the original acceptance of terms and subsequent acceptance of the same terms on the back end.) So if an authenticated user comes back to this page to review the terms, we're forcing them to choose between 2 buttons, but only 1 button changes something. Could we consider alternatives for this?

One thought is to relabel the "Accept" button, though this would still be a button that doesn't do anything:
> **Do you accept these terms of use?**
> Continue to accept [button]
> Decline [button]

Or we could remove the accept button and provide another way for users to get off the page without changing their answer. There aren't breadcrumbs on this version, right? If the only way to get here is from the privacy policies page, we could consider adding a link back to that page. Something like:
> **Do you accept these terms of use?**
> You previously accepted the terms. 
> **If you want to keep your answer,** you don't have to do anything.
> Go back to the privacy, policies, and legal information page [link]
> **If you want to change your answer,** you can decline the terms now.
> Decline [button]

Let me know what you think!

**Comment by asg5704** [comment]
@laurwill 
1. Introtext - Sounds good we will update the introtext to your recommendation (and update the Figma for record keeping)
2. Buttons - So I think we will opt for the first option and just change the button copy to what you recommended. In the fully authenticated flow the Accept button does technically do something 😅 but its all in the backend which doesn't mean much to the user, but it acts as an audit log for VA

**Comment by kdmeg-bluetiger** [comment]
Hey team 👋  For continuity, I'm adding a [link to this issue ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/75894)about a bug my team discovered when certain users reject the ToU and attempt to log back in to accept them.

**Summary:** 
Due to a bug within the patient portal and SSOe flows, users aren't able to log back in to the patient portal if they decline terms within the same browser session. 

If the user reaches the [decline error page](https://staging.va.gov/terms-of-use/declined), they will encounter an error when they sign back in **unless** they close out of their current browser session or clear their cookies.

**Desired fix:** add some language to the [decline error page](https://staging.va.gov/terms-of-use/declined) to inform users about the issue.

**My initial thoughts:** not all users will encounter this error, only the ones logging in through the channels mentioned above. How explicit do we want to be about alluding to a potential error?

**One suggestion:** be direct and instruct users to **first** "restart" their browser session by closing the current window or clearing their cookies, and **then** sign in again to accept the terms.

_To access online services, you can sign in and accept the terms. First, restart your browser session by closing the current window or clearing your cookies. Then sign in again to accept the terms._

**Another suggestion:** be more explicit and tell the user they might encounter an error if they don't complete this action.

_To access online services, you can sign in and accept the terms. To avoid a browser error, restart your browser session first. Close the current window or clear your browser cookies before you sign in again. Then sign in to accept the terms._

cc @laurwill for your thoughts on this 🙏

**Comment by laurwill** [comment]
Hi @kdmeg-bluetiger , thanks for looping us in!

Couple questions first:
- You said that not all users encounter this error. Do all users who reach the ToU decline page and select the "Sign in" button on that page (without starting a new browser session) encounter the error? If so, we'd also need to remove the sign in button from this page, since it will never work.
- This doesn't seem like a good user experience, especially for an action that we're requiring users to take in order to access their VA benefits online. Is there a plan to fix this error on the backend, so this would only be a temporary solution?

**Comment by kdmeg-bluetiger** [comment]
@laurwill - the ticket says the bug only applies for "patient portal and SSOe flows." While I don't think this is 100% of cases, I believe the scope of SSOe is pretty broad. 

cc @asg5704 for your input on the scope of the error, and context on when there may be a backend solution. TY!

**Comment by asg5704** [comment]
@laurwill @kdmeg-bluetiger 
- Yes I am aware that the Sign in button will be removed.
- Currently, the "backend" team proposed a solution that could make these content changes a "nothing burger". We are preparing what the content / page would be if the proposed solution does not work as expected.

So in other words I'm not sure. I see this as being a permanent solution that may or may not be introduced. 🤷

**Comment by laurwill** [comment]
Okay great — so hopefully this will never get implemented. 

If we do need to implement something like this, I have a couple more questions about the instructions:
- Do they need to close the current window before opening a new one? Or will opening a new window (and leaving the current window open) also work?
- Or do they need to quit and reopen the browser entirely?

**Comment by asg5704** [comment]
Okay @laurwill and @kdmeg-bluetiger I have received some updated information.

The hope is that this will be temporary as IBM attempts to fix the issue. Our stakeholders would like to move forward with rolling out the content.

The user will be required to use the latter option, quit and reopen the browser entirely. So that the cookies and cache would be removed. I gave you and Megan edit access to the [Figma](https://www.figma.com/file/nxW1NHF0q1EasvUGp1eh5a/Terms-of-Use---Final?type=design&node-id=1%3A561&mode=design&t=KMYTqAFzVWLRtrjV-1), or if you would prefer a [Google Doc](https://docs.google.com/document/d/14mVvD_Z4Pm7sJny6VT-GCLD3BQi7lv2MELN_ZNqQwqI/edit?usp=sharing) I can put the content there as well.

**Comment by laurwill** [comment]
HI @asg5704 @kdmeg-bluetiger @claytonzook , I made a suggested edit in the [Google Doc](https://docs.google.com/document/d/14mVvD_Z4Pm7sJny6VT-GCLD3BQi7lv2MELN_ZNqQwqI/edit?usp=sharing) — tried using a numbered process list to communicate the need to quit and reopen the browser. See what you think!

**Comment by kdmeg-bluetiger** [comment]
Hey @laurwill - I think these instructions are really clear! I had 2 questions:

- Should the instructions be a numbered list or a bulleted list (like a [process list component](https://design.va.gov/components/process-list))?
- Do we want to keep the link to the logged out ToU at the bottom of the page here while we are dealing with this bug? My concern is that folks might get stuck on that logged out page without access to the instructions for restarting their browser if they decide they want to proceed. I wasn't sure if this was a requirement to include the path to the logged out page. 

Thanks for clarifying!

**Comment by laurwill** [comment]
Hi @kdmeg-bluetiger , 
- Great point about the link to the logged out ToU. I agree that could be confusing — I think fine to remove until we fix the bug
- And good Q about the process list — wayyy down the component page, it says not to use this for simple step-by-step instructions: 
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/104158104/c493b27d-13d9-4e78-8259-285ae04a21c8)
So we should keep it as a simple numbered list, since it's sequential steps in a simple process.

Let me know if you want to chat about anything else!

**Comment by kdmeg-bluetiger** [comment]
@laurwill - that sounds good to me! Thank you for taking a look to confirm 🙏 

@asg5704 - here's where we landed:
- We'll remove that link to the logged out ToU page for now until the bug is fixed.
- We'll keep the instructions in a numbered list based on this guidance.

**Comment by asg5704** [comment]
@kdmeg-bluetiger Sounds good. Creating a ticket for dev work.

**Comment by laurwill** [comment]
Terms of use work is finished, closing out
