### ISSUE TITLE
Design Intent  - IA Feedback - Virtual Agent, Chatbot, Prescription

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#63276]
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- Thanks for bringing this to us! This is a new type of project/interface for me on two axes (chatbot + voice). Lots of complexity here. I think user testing will yield a lot of useful information for future chatbot workflows.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- **Must:** Include an entry point - some information on the chatbot welcome screen or introductory message to let Veterans know that they can ask the chatbot about prescriptions.
- **Must:** Include exit points and direct to other ways to contact the VA if users are not able to find what they are looking for or perform a desired action. If there's another way for Veterans to manage their prescriptions online without a chatbot, provide a link. The potential for frustration is high with chatbots in general, so providing pressure release valves will be important.
- **Consider:** Testing on mobile, especially the voice to text component. 
- **Consider:** Working with CAIA for guidance on user flows
- **Consider:** Limiting the number of calls to action displayed on screen to reduce the need for users to scroll back up to previous chatbot messages (saw this happening on the video when there were 4 CTAs)
- **Consider:** Clarifying which prescription is which, helping Veterans differentiate their prescriptions in ways other than the name/dosage. On one screen there was an image/description of what the pills look like, which could accomplish this. Another option might be describing the med's purpose, or its brand name if it's commonly known.

**Comment by Joy-Elizabeth** [comment]
@erinrwhite Is there anything the Chatbot team needs to do with this open ticket?

**Comment by erinrwhite** [comment]
@Joy-Elizabeth I think this ticket is good to close - this skill launched in production, yes? Hopefully the feedback was useful for the team. Thanks!

**Comment by Joy-Elizabeth** [comment]
@erinrwhite The Rx skill has launched in desktop only and mobile is still being addressed with other issues. The multiple pieces of feedback have been very insightful, yet with the continued tickets still open, I'm not sure what this ticket is open for in regards to action items for us.
