### ISSUE TITLE
Midpoint Review - Design Feedback - Debt Resolution, Streamlined Waiver

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#63286]
## VFS actions
- [x] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [x] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [X] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [63392](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/63392) - [SW] Midpoint Review - Change the sim alert to a standard alert (63286) **Closed**
  - [X] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [63397](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/63397) - [SW] Midpoint Review - Profile update when pre filled data is updated (63286) (Post Launch)
- [x] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- Yay for the new card style!!! : )
- I do have a question. In the work history, I added 2 jobs. After adding the 2nd job, but before clicking "Continue" I only see 1 job card, not 2. I never saw the 2 jobs together. Is that just part of the prototype? In other words will the user see all work history cards before proceeding the the next chapter?
- <img width="698" alt="Screen Shot 2023-08-08 at 12 20 18 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/72398073/9f9c906e-ae65-4192-ac8b-5ab6004b566e">
- Also keep in mind that if the user deletes one of those cards they will need to have some sort of action to confirm deleting it. I have seen some use a modal. Jeanna Clark may have some advice on that. Since I was not able to test the delete I just wanted to make you aware before Staging.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- **Must**: There is a [wizard](https://design.va.gov/patterns/wizards) at the beginning of the form for "Is this the form I need?". We have moved to a 1 thing per page for accessibility reasons. Change the wizard and remove the conditional logic. If this page is not included in this review please put this on the back log.
- **Must**: Love the new card style! [This card](https://design.va.gov/components/card#with-drop-shadow) is now in the design system. It looks as though your drop shadow is slightly different. Please align with the design system drop shadow.
- **Must**: You are using a slim alert for the "You can skip questions..." message. [Slim alerts](https://design.va.gov/components/alert#when-to-use-a-slim-alert) are mostly reserved for immediate feedback without a full page load. Instead use the [standard alert](https://design.va.gov/components/alert#informational-alert).
- <img width="764" alt="Screen Shot 2023-08-08 at 12 30 02 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/72398073/ac09fa92-95ee-4475-85b3-4acfad2951dd">
- **Should**: In your form when a user updates any pre filled information from their profile it does not update profile, it only updates this application. The preference is to have the profile updated as well.

**Comment by mgleo** [comment]
- A new card will be added when another job is added. This is just a prototype limitation.

- We're excluding the Wizard from this collab cycle. We are planning on implementing one thing per page after this MVP launch.

- The card styling has been updated on production/staging to match the design system. Here is a screenshot from staging: ![Screenshot 2023-08-09 at 5.36.58 PM.png](https://images.zenhubusercontent.com/5f91de193a0ac23f49d7bf89/ece10d64-65b4-4b02-a82b-2f63db8e9eff)

**Comment by josephrlee** [comment]
@allison0034, here's a screenshot of the updated transition page with the correct alert style:

![Transition Page Alert](https://images.zenhubusercontent.com/63ea96045c6deec1c9a25425/719503a6-3e2a-4d70-9067-20a12111ed46)

**Comment by HeatherRienks** [comment]
@allison0034, we have created 2 tickets on our board for this feedback:
"Must have" feedback is here: #63392
"Should have" feedback is here: #63397, which we will plan to complete post-launch.

Please let us know if there is any additional action needed from us. Thanks!

cc: @Tom-Davis

**Comment by allison0034** [comment]
@HeatherRienks no additional action needed, thank you!

**Comment by Tom-Davis** [comment]
Closing as all must complete pre MVP launch items are finished.

**Comment by HeatherRienks** [comment]
Please note that all "Should" have feedback noted here has been completed. Ticket #63397 has been closed too!
