### ISSUE TITLE
FSR Bug Failing Cypress Test -   Chromium Renderer process just crashed.

### ISSUE THREAD

**Issue by amponce** [department-of-veterans-affairs/va.gov-team#63283]
### Summary
A test within the fsr-5655-alert-cards-combined.cypress.spec.js file is causing the Chromium Renderer process to crash during execution in the CI environment. This is blocking other tests and may be related to memory or environmental issues.

### Details
File Affected: `fsr-5655-alert-cards-combined.cypress.spec.js`

### Error Message:
We detected that the Chromium Renderer process just crashed.

This is the equivalent to seeing the 'sad face' when Chrome dies.

This can happen for a number of different reasons:

- You wrote an endless loop and you must fix your own code
- You are running Docker (there is an easy fix for this: see link below)
- You are running lots of tests on a memory intense application
- You are running in a memory starved VM environment
- There are problems with your GPU / GPU drivers
- There are browser bugs in Chromium

You can learn more including how to fix Docker here:

https://on.cypress.io/renderer-process-crashed

  (Results)
┌──────────────────────────────────────────┐
│ Tests:        0                         │
│ Passing:      0                         │
│ Failing:      1                         │
│ Pending:      0                         │
│ Skipped:      0                         │
│ Screenshots:  0                         │
│ Video:        true                      │
│ Duration:     0 seconds                 │
│ Spec Ran:     fsr-5655-alert-cards-combined.cypress.spec.js │
└──────────────────────────────────────────┘

**Comment by amponce** [comment]
Fixed

**Comment by HeatherRienks** [comment]
@amponce - Yay, it's fixed! Can this be closed out now or is there anything left to do?
