### ISSUE TITLE
[Design] Discovery: Profile 2.0 badge/logos

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#6328]
## Background
We would like to provide the users service badge/logo on their profile in order to provide a more customized profile experience.

Tressa to meet with Erik to determine the following:
- Which logos are stored (if any)?
- Where are they stored?
- How do we retrieve badges/logos?

## Tasks
- [x] Erik to provide relevant information related to to badges and logo storage/retrieval/availability etc to Tressa
- [ ] Post discovery findings on this ticket and copy Matt and Tressa

**Comment by erikphansen** [comment]
@tressaellen We have the following badges ready to go on the server:
- https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/img/vic-army-symbol.png
- https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/img/vic-usmc-emblem.png
- https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/img/vic-cg-emblem.png
- https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/img/vic-air-force-coat-of-arms.png
- https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/img/vic-army-emblem.png

**Comment by tressaellen** [comment]
@erikphansen thank you!

**Comment by erikphansen** [comment]
closing as I think I found what we need for this.
