### ISSUE TITLE
Update the page description on the Pending status list page 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#63294]
## Description
We would like to improve the content language on the Pending status page. 

---

## Acceptance Criteria

- [ ] Given when the user is authenticated into the Appointments application 
       When the user clicks on `Pending` 
       Then the user will see the updated page description above their pending appointment list 
       And page design matches the [design spec](https://www.figma.com/file/BQxFP7vqmXRIeX0GIuc8A4/Clarify-request-empty-state-content?type=design&node-id=1302-7156&mode=design&t=qqHtvSMJ9lTk77xl-0)

- [ ] Given when the user is authenticated into the Appointments application 
       When the user clicks on `Pending` and has no pending appointment(s) 
       Then the user will see the updated page description 
       And page design matches the [design spec](https://www.figma.com/file/BQxFP7vqmXRIeX0GIuc8A4/Clarify-request-empty-state-content?type=design&node-id=1302-7156&mode=design&t=qqHtvSMJ9lTk77xl-0)

### Design Assets
[Figma file](https://www.figma.com/file/BQxFP7vqmXRIeX0GIuc8A4/Clarify-request-empty-state-content?type=design&node-id=1302-7156&mode=design&t=qqHtvSMJ9lTk77xl-0)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by ldelacosta** [comment]
@young1205 - please have @JRRoof and UX team validate this ticket when it's ready in staging. Thanks!

**Comment by Cieramaddox** [comment]
@young1205 The UX team has validated this ticket.
