### ISSUE TITLE
Should we create/maintain a roster of Platform and/or VFS roles?

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#63298]
## Purpose
This information has to be referenced manually by various teams fairly often. How to create a repository and easily keep it up to date?

## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_

Update:  no longer needed with the launch of Atlas

**Comment by tayism** [comment]
Some pre-existing resources on this:

- [Platform roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [VFS Team roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit#gid=2042046665) (doesn't seem to be updated when folks move teams or roll off contracts. Governance owns this)
- [Product Directory](https://vfs.atlassian.net/wiki/spaces/GS/pages/2294120662/VFS+Product+Directory)
- [VA Design Universe Map](https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1632350543960/1ba30f5bd8327234e15bd5eedf06b2d1b0418621?sender=u9ea6bd3ca12795949b606150) (Naomi owns this)

**Comment by tayism** [comment]
What if this was something we asked VFS Teams to help maintain, say, on the Platform Website?

**Comment by steel36** [comment]
@tayism Also note that this could intersect w/ our potential work on Orientation/onboarding, since the functioning roster is updated at that point.

**Comment by steel36** [comment]
There was also an airtable that was created by someone to accomplish something similar for only a certain type of role.  I'd have to dig that up.  Think I may have gotten it from Naomi.  Airtable seems like a great way to run it because you could pivot on various variables.
