### ISSUE TITLE
[a11y-defect-1]: description of issue here

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#63297]
### Point of contact

joshkimux

### Severity level

1, Launchblocker. Critical. Must be fixed before launch.

### Details

...

### Reproduction steps

1.
2.
3.
...

### Proposed solution or next steps

...

### References, articles, or WCAG support

1.
2.
3.
...

### Type of issue

- [ ] Screenreader
- [ ] Keyboard
- [ ] Focus
- [ ] Headings
- [ ] Color
- [ ] Zoom
- [ ] Semantics
- [ ] Axe-core
- [ ] Something else

**Comment by coforma-jamie** [comment]
This was a dummy created for training purposes. Closing this
