### ISSUE TITLE
Analytics Implementation or QA Support for [FSR 5655]

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#63299]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

</div>
</details>

Looking to addd tracking on form submission [similar to how we implemented it here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47442#issuecomment-1387465418) for `submission-type`. 

We are planning to add `streamlined` with the potential values of `streamlined-short`, `streamlined-long`, `streamlined-false`. 

### Required
- **Is this request for **Google Analytics implementation** or **QA**?**

     - [x] Google Analytics implementation
     - [ ] QA

- **Who is this request for?**
Michelle Dooley
    
    
- **Provide the link(s) for Google Analytics implementation or QA**
  
    - [Insert link(s)]
    
- **When is the launch date?**
    - 08/17/2023

- **What interactions need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked_
    
    - [If this is a funnel, insert each step's URL - pages visible depending on the applicant's answers should be marked accordingly]
    
    - [Insert other interactions - please review the [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) and [GA Data Dictionary](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Google-Analytics-Data-Dictionary.1810464912.html)  to make sure these interactions aren't already tracked]

### Optional
- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - [Insert test user]

- **Any additional comments**

    - [Insert comments]

> Please leave the following blank

## Acceptance criteria
- [x] All appropriate issue tagging is completed
- [x] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by michelle-dooley** [comment]
@Dr-Pongo - will review with our new GA specialist and get back to you with timing.  There is currently a bit of a backlog but we should be catching up soon!!

**Comment by amponce** [comment]
PR created with analytics events https://github.com/department-of-veterans-affairs/vets-website/pull/25171

**Comment by amponce** [comment]
The frontend work is completed, we just need to verify how this can be QA'd with the analytics team now

**Comment by amponce** [comment]
Hi @michelle-dooley I was hoping to get a quick confirmation on the structure of the analytics events before I merge this to staging. Does the above local output look correct?

**Comment by jestutt** [comment]
@amponce  Yes, this looks correct

**Comment by amponce** [comment]
The analytics updates are currently on stage and ready for verification

**Comment by jestutt** [comment]
I see the new variable in the datalayer and have added it to the Action for the FSR submission event. 

Datalayer Event viewed from GTM test: 
<img width="388" alt="Screenshot 2023-08-10 at 5 23 42 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/141653184/82dd68c4-0fcb-4e49-835d-91726aae46eb">

Non-Production GA: 
<img width="1254" alt="Screenshot 2023-08-10 at 5 25 37 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/141653184/da5a3f32-f1f1-4653-a07c-daf1cd61d1dd">

**Comment by amponce** [comment]
@jestutt perfect! Is there anything else we need to do on the front end side?

**Comment by jestutt** [comment]
@amponce Other than push to production, I don't think so.

**Comment by HeatherRienks** [comment]
@jestutt -  one question for you that I wanted to be sure we didn't overlook -  an item listed on the Acceptance Criteria was "Events have been added to Product and Benefit Hub Content Groups"

Has this been updated? TY!

**Comment by HeatherRienks** [comment]
@jestutt -Just wanted to check on this. We are hoping to go live this week.
Thanks!
