### ISSUE TITLE
Start creating PR guidelines 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#633]
# Goal 
- Reduce friction created by current PR review process 

# Tasks 
- Do a deep dive to identify core issues with current PR review process
- Start creating guidelines that improve clarity and consistency of pull request reviews 
- Offer recommendations to address management of long term burden of reviews 
- Review popular PR guideline approaches 

# Artifact 
- Research notes 
- Draft PR guidelines 

# Notes
- [Sprint 4 Reviews - partial list](https://github.com/department-of-veterans-affairs/va.gov-team/issues/624)

**Comment by rianfowler** [comment]
Review and incorporate the PR review guide for CMS reviews: https://gist.github.com/jbalboni/dab1cac5f027001913eb6e4f45822106#pr-review-guide

**Comment by annaswims** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/pull/717
