### ISSUE TITLE
Redirect the existing URLs to the new URLs for MHV on VA.gov - COVID-19 workflow 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#63304]
## Description
We will need to re-direct the Veteran to the new URLs for Appointments on MHV on VA.gov. 

---

## Acceptance Criteria

Given the user is on `Upcoming VA appointments` homepage, 
And the user clicks on `Start Scheduling` button for COVID-19 vaccine appointment then lands on

- [x] When the URL for `COVID-19 vaccine appointment plan ahead` page is https://va.gov/health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-appointment, then user will be re-directed to the new URL https://va.gov/my-health/appointments/schedule/covid-vaccine
- [x] When the URL for `Have you received a COVID-19 vaccine?` page is https://va.gov/health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-appointment/confirm-doses-received, then user will be re-directed to the new URL https://va.gov/my-health/appointments/schedule/covid-vaccine/doses-received
     - [ ] When user selects `Yes` and lands on the `We can’t schedule your second dose online` page and URL is https://va.gov/health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-appointment/contact-facility, then user will be directed to the new URL https://va.gov/my-health/appointments/schedule/covid-vaccine/contact-facility
- [ ] When user selects `No/I'm not sure,` and lands on the `Choose a location` page where the URL is https://va.gov/health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-appointment/choose-facility, then user will be directed to the new URL https://va.gov/my-health/appointments/schedule/covid-vaccine/location
- [ ] When the URL for `Choose a clinic` is https://va.gov/health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-appointment/choose-clinic, then user will be re-directed to the new URL https://va.gov/my-health/appointments/schedule/covid-vaccine/clinic
- [ ] When the URL for `Choose a date page ` is https://va.gov/health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-appointment/select-date, then user will be re-directed to the new URL  https://va.gov/my-health/appointments/schedule/covid-vaccine/date-time
- [ ] When the URL for `When to plan for a second dose` page is https://va.gov/health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-appointment/second-dose-info, then user will be re-directed to the new URL https://va.gov/my-health/appointments/schedule/covid-vaccine/second-dose
- [ ] When the URL for `Confirm your contact information` is https://va.gov/health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-appointment/contact-info, then the user will be re-directed to the new URL https://va.gov/my-health/appointments/schedule/covid-vaccine/contact-information
- [ ] When the URL for `Review your appointment details` page is https://va.gov/health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-appointment/review, then user will be re-directed to the URL https://va.gov/my-health/appointments/schedule/covid-vaccine/review
- [ ] When the URL is https://va.gov/health-care/schedule-view-va-appointments/appointments/va/[ID]?confirmMsg=true for when a user schedules a COVID-19 vaccine appointment, then user will be re-directed to the new URL for the confirmation state https://va.gov/my-health/appointments/[ID]?confirmMsg=true

### Design Assets
[Copy doc - COVID-19 flow](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/schedule-va-covid.md)
[Copy doc- COVID-19 confirmation state](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/appointment-details.md#va-in-person-vaccine-appointment---confirmed)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by ldelacosta** [comment]
@young1205 - please have the UX team validate this ticket when it's ready cc: @JRRoof @outerpress

**Comment by JRRoof** [comment]
Redirects added in production October 4, 3023.
