### ISSUE TITLE
Remove (*Required) text in all the scheduling flows

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#63316]
## Description
Remove the (*Required) text from the page description for all the scheduling flow pages. 

Current design for the type of care page:  
<img width="518" alt="Screenshot 2023-08-08 at 2 20 52 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/90797205/8398b087-0345-4940-8d66-9e631fa6bd83">

---

## Acceptance Criteria

- [ ] Given the user is on the Appointments landing page 
        When the user clicks on `Start Scheduling` and starts on the direct schedule VA workflow 
        Then the user will not see the `(*Required)` text on the page description for each page in the flow 

- [ ] Given the user is on the Appointments landing page 
        When the user clicks on `Start Scheduling` and starts on the direct schedule for COVID-19 appointment 
        Then the user will not see the `(*Required)` text on the page description for each page in the flow 

- [ ] Given the user is on the Appointments landing page 
        When the user clicks on `Start Scheduling` and starts on the pending appointment VA workflow 
        Then the user will not see the `(*Required)` text on the page description for each page in the flow 

- [ ] Given the user is on the Appointments landing page 
        When the user clicks on `Start Scheduling` and starts on the pending appointment Community Care workflow 
        Then the user will not see the `(*Required)` text on the page description for each page in the flow 

### Design Assets
[TBD] 

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by outerpress** [comment]
@ldelacosta @JRRoof I think we should close this one. It wouldn't add a ton of value, and I'd want to see platform guidance on this before we went ahead and did it. I like leading the pack on this kind of thing, but this would be better dealt with at the platform level. I'll file a ticket on their side if there isn't one already.

**Comment by ldelacosta** [comment]
Thanks for the update. I'll close it out. But if you want to reference the ticket # here when you file one in case we do want to revisit this work in the near future @outerpress
