### ISSUE TITLE
Redirect the existing URLs to the new URLs for MHV on VA.gov - COVID-19 appointment details page

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#63313]
## Description
We will need to re-direct the Veteran to the new URLs for Appointments on MHV on VA.gov.

---

## Acceptance Criteria

- [ ] Given the user is on Upcoming VA appointments homepage,
And the user clicks on `Details` for their upcoming COVID-19 appointment details and when the URL is https://va.gov/health-care/schedule-view-va-appointments/appointments/va/[ID], then the user will be re-directed to the new URL https://va.gov/my-health/appointments/[ID]

- [ ] Given the user is on Upcoming VA appointments homepage,
And the user clicks on `Details` for their upcoming canceled COVID-19 appointment details and when the URL is https://va.gov/health-care/schedule-view-va-appointments/appointments/va/[ID], then the user will be re-directed to the new URL https://va.gov/my-health/appointments/[ID]

- [ ] Given the user is on Past appointments view,
And the user clicks on `Details` for their past COVID-19 appointment details and when the URL is  https://va.gov/health-care/schedule-view-va-appointments/appointments/past/va/[ID],then the user will be re-directed to the new URL https://va.gov/my-health/appointments/past/[ID]

### Design Assets
[Copy doc - COVID-19 appointment details page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/appointment-details.md#va-in-person-vaccine-appointment---upcoming)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by ldelacosta** [comment]
@young1205 - please have the UX team validate this ticket when it's ready cc: @JRRoof @outerpress

**Comment by JRRoof** [comment]
Redirect added in production October 4, 3023.
