### ISSUE TITLE
[SPIKE] Determine Steps Needed to Evolve Travel

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#63320]
## Background
We have been asked to evolve our feature to allow the submission of a travel reimbursement claim during online check-in.

[Link to feature ideas prioritization event](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1691694352663/51d6b8bc5d8394bf8466fa0c4523a54a3ad24483?sender=ud3aa760e30b39bcf436d4473)

## Tasks
- Identify the tasks necessary to do the discovery work
- Create tickets & attach them to this [Epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47818)

**Comment by loripusey** [comment]
@benbrasso-agile6 thought we'd get started with a ticket to brake down some initial work; can you have UX point this and we'll see if it fits into next sprint when we get to planning? thanks.

**Comment by loripusey** [comment]
@benbrasso-agile6 here is a link to the original Travel ideas mural exercise we did a while ago
[Link to feature ideas prioritization event](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1691694352663/51d6b8bc5d8394bf8466fa0c4523a54a3ad24483?sender=ud3aa760e30b39bcf436d4473)

**Comment by benbrasso-agile6** [comment]
[User flow options as a result of API latency](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1677531401756/f2ecd191cf691044fb11f57fe3398b91ad4dbc82?sender=u37bb983bd3fc3cc00c7d3286)

**Comment by benbrasso-agile6** [comment]
[Pros and cons of different user flows presentation](https://docs.google.com/presentation/d/1V1y0JiqRv_wWMqQvmBi4GiMJ0UBwapJknZBpdSI6oAs/edit?usp=sharing)

Recommendation of post-appt experience got nixed because Stephen imagined it would be easier and quicker to market for us to include within the existing eCheck-in flow, which no one disagreed with.

**Comment by benbrasso-agile6** [comment]
[Earlier user flow options we looked at](https://www.sketch.com/s/42a478e7-cb38-49e5-9500-9b21182873da/p/552EBE6C-AE8A-440B-A977-78EAF354D73B/canvas)

**Comment by benbrasso-agile6** [comment]
Started thinking about this, haven't created tickets yet, but I will. Just jotting some notes down for now: 

* Review all related materials (including [18F presentations](https://drive.google.com/drive/folders/1r2yIMcN7s-iQq0irwViUHlHbiouBzcR_?usp=sharing)
* Ask Ben Williams (probably over email or Teams) for rough breakdown % of different types of claims. (I'm not sure we have them all documented.) E.g., public transportation. And, ask if any of those types need pre-approval. If so, when and how does that pre-approval work? 
* Talk to After Visit Summary team (Kristen McConnell) about what they've been working on. E.g., user flows, designs, etc. The cross-over with AVS is that travel pay also happens after the visit. So, we need to check their plans for design and if they're planning to do a post visit text. 
* I'll list out known options for consideration. We don't have to analyze them all. E.g., post-visit standalone web app with LoROTA, fully standalone web app with LoROTA that can be accessed 24/7 like the claims tool, change user flow of check to check in > then travel after, expand types of claims in check in, file for travel via MSA and VSE, etc. 
* Create pros and cons table similar to one of the files above in the comments for each idea. Include whether it supports blind and low vision Vets. Do not need t shirt size or level of effort. These are ideas to help OCTO make decisions. 
* Share presentation with OCTO and Lori (and maybe CIE team optional)

**Comment by benbrasso-agile6** [comment]
@loripusey feel free to give that a quick review. I'm still tinkering with it, and will create tickets this week.

**Comment by loripusey** [comment]
Looks like a good start

**Comment by benbrasso-agile6** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/64050
