### ISSUE TITLE
SOCKS access for Derek Fitchett

### ISSUE THREAD

**Issue by dfitchett** [department-of-veterans-affairs/va.gov-team#63334]
### Your Name

Derek Fitchett

### Your Email

derek.fitchett@agile6.com

### Your Role and Team

Software Engineer on Employee Experience Team

### Product Manager (PM) name and email

Amy Lai amylai@navapbc.com

### Product Owner (PO) name and email

Zach Goldfine zachary.goldfine@va.gov and Emily Theis emily.theis@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDbgBJZHg3/hm6zheiIWoT87wuPQzD9sjP1he0ZAoWtptIEm1h4unq8hQPIdH0MkFBZebe2GwN7lPcCIQPa1NbQ+KvT9lto61cCq7qMdvLG5qXlti5X9UPj68qktNnMiznyQv2haa307s2MiTBADMu+Fah1wwQxOx7UhBDZ9SfpvK4ofwsT08KOCp0JwYVpGMdisuOBgMYd0uhdfOXXFulaCBEsniSSGcoZEnGgB5UHH6KcMO+RdFGLLhiZb85u/xT8ibnk/vxJOP/KBWJyRRY81AymsvXD7Cng5w3y4SQwd9cubrcLiYfqUWt1WXUbxdM2HM60d6/MvHUFy/EQnDn6NWd6navh3cZtG3tUi+CCzjz9XtiiQEoKIt1wz4iqnLL5d+ukJ91YXhXzxc7SNFXa4AEebJNTHp88r6ZeHMlVjDMIochtawkdJhRxYew112fpkiEyic3wVNtQom4XMdShrk/He1m2kL3UL2O78kHZ7Ajebo03+BZHUYdroE5ieB0= derek.fitchett@Derek-Fitchett.lan

### E-QIP Transmittal Confirmation

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/135860892/d03cb543-97cd-46f0-a7ca-d3dd0808c7d6)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by ph-One** [comment]
SOCKS access completed
