### ISSUE TITLE
Midpoint Review - Accessibility Feedback - Debt Resolution, Streamlined Waiver

### ISSUE THREAD

**Issue by briandeconinck** [department-of-veterans-affairs/va.gov-team#63355]
## VFS actions
- [x] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [x] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [x] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [63404](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/63404) - [SW] Midpoint Review - Accessibility updates (63355) **Closed**
  - [x] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [63406](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/63406) - [SW] Midpoint Review - Accessibility headings updates (63355) (Post Launch)
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- This looks really good! Looking forward to seeing it at staging.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- **Must:** Very minor, but the TTY 711 phone links are inconsistent from page to page. When it's coded, make sure you use the `va-telephone` component, which has a `tty` prop for ensuring consistent presentation and `aria-label`.
- **Must:** When editing information the VA already has about the Veteran, eg. [step 1, edit phone number](https://preview.uxpin.com/6940f648e5994b8fad9550934a5530b4cd73cacb#/pages/163500333/simulate/no-panels?mode=cvhid), the note about updates only making changes for this request may be more appropriate as hint text with the input component. If there's a design preference to keep that text more prominent above the component, you'll need to make sure it's associated with the input using `aria-describedby` to ensure that screen reader users hear that note when tabbing into the field.
- **Should:** I really appreciate the unique H3 headings describing each page within the multipart steps. If you're not already planning to do this, those headings should receive keyboard focus when landing on each page of the workflow. That will ensure they're the first thing a screen reader user hears --- meaning they'll know they've advanced to the next step and have some context for where they are, instead of hearing "Step 1 of 7" multiple times as they move through the workflow.

**Comment by HeatherRienks** [comment]
FYI @Tom-Davis

**Comment by mgleo** [comment]
- Telephone numbers were recently updated on staging/production and should consistent and coded for screen readers.
- Front end team recently updated the form and now contact info updates **will** be applied to their VA profile. I've removed that line from our prototype and it is not present on staging/production.

**Comment by HeatherRienks** [comment]
Ticket has been created on our board; #63406.

@briandeconinck - is there any additional action needed from us? Thanks!

cc: @Tom-Davis

**Comment by Tom-Davis** [comment]
Closing as all must complete pre MVP launch items are finished.

**Comment by HeatherRienks** [comment]
Additionally, all "should" feedback has also been completed via #63406.
