### ISSUE TITLE
[Spike] - Adding After Visit Summary path/link in single appointment response.

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#63359]
## Background/Request
We want to add and the `After Visit Summary` link to past appointments details if available. 

### Dev Notes
To get AVS link, we need to call the avs endpoint with the station number and appointmentIEN: `/avs/v0/avs/search?stationNo={stationNo}&appointmentIen={appointmentIen}`. Sample response:

```
{ path: "my-health/medical-records/care-notes/avs/9A7AF40B2BC2471EA116891839113252" }

```
If no avs link is found for that appointment, an empty object is returned.

The appointment response contains an `identifier` field:

```

"identifier": [
                {
                    "system": "http://www.va.gov/Terminology/VistADefinedTerms/409_84",
                    "value": "984:4333"
                }
            ],

```
The 984 would be the station Number, and 4333 would be the IEN.

### Goal
As a veteran, when I view the appointments details for any of my past appointments, If there are after visit summaries available for that appointment, the `/vaos/v2/appointments/${id}` endpoint should return field: `avsPath` with the link to the appointment AVS. I.e, `avsPath: "my-health/medical-records/care-notes/avs/9A7AF40B2BC2471EA116891839113252"`

## Tasks
- Answer the following questions:
  - What's the best way to handle passing the avs to the appointments endpoint to reduce risk of increasing load time?
  - Should we only return the avsPath field in the appointment list call as well or just the single appointment call?

## Time Box
18 hours

## Definition of Done
- Tasks are complete
- Research and recommendations are documented in this ticket

**Comment by cferris32** [comment]
Spike findings:

**Q1:** What's the best way to handle passing the avs to the appointments endpoint to reduce risk of increasing load time?
**A1:** Upon receiving the appointment response, we will check for a status of `booked` and a `startDate` that is in the past. This will let us know if it's a past appointment where an after visit summary is applicable. By only fetching the avs link in these scenarios, we will minimize total number of calls and load time.

**Q2:** Should we only return the `avsPath` field in the appointment list call as well or just the single appointment call?
**A2:** In most scenarios, the website will have fetched the whole appointment list and have access to it before fetching a single appointment id, so it would be ideal to have the avs link available to all past appointments from this call. The only relevant scenario where we'd fetch a single appointment and not already have access to the appointment list would be when the individual appointment details page is refreshed, thus warranting another request for that appointment id in which we'd also want to include the avs link. In summary, it seems to be ideal to make the avs call for both the bulk fetch and individual fetch.
