### ISSUE TITLE
508 Findings for Pre-Launch 508 Review for Appeal Modernization Process (AMA)

### ISSUE THREAD

**Issue by AkucherGCIO** [department-of-veterans-affairs/va.gov-team#6335]
## Team 

VSA Public Websites

## Product

Appeal Modernization Process (AMA)

## Product Description

The Appeals Modernization Act (AMA) caused a shift from the old or  legacy appeals process to the new decision-review process.

Some legacy appeals will still be pending for months or years to come. All new appeals must be filed using the decision review process.  As a result, both the decision-review and legacy-appeal processes must coexist on VA.gov.

The VA wants to move away from “appeals” language toward “decision review” and “disagreement” language. This is a challenge as “appeal” is a deeply entrenched term, as demonstrated by SEO keyword research.

## Checkpoint Stage

Pre-Launch 508 Review 

## Point of contact

Aruna Kucherlapati

## Staging URL and Credentials

See https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/6165 for full list of work.

- Disability benefits hub: https://www.va.gov/disability/
- How to file a disability claim: https://www.va.gov/disability/how-to-file-claim/
- After you file a claim: https://www.va.gov/disability/after-you-file-claim/
- Manage a legacy VA appeal: https://www.va.gov/disability/file-an-appeal/
- VA decision reviews and appeals: https://www.va.gov/decision-reviews/
- Supplemental Claim: https://www.va.gov/decision-reviews/supplemental-claim/
- Higher-Level Review: https://www.va.gov/decision-reviews/higher-level-review/
- Request a Board Appeal: https://www.va.gov/decision-reviews/board-appeal/
- Contested Claims: https://www.va.gov/decision-reviews/multiple-party-claims/

## Test Plan

See https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/6165 for full list of work.

**Comment by AkucherGCIO** [comment]
03/04/20 PW Grooming
@AkucherGCIO - Some of these issues might be resolved with the anomalies that will get resolved . @lwalsh617 - FYSA.

**Comment by jenstrickland** [comment]
@AkucherGCIO - I'm still in the middle of the accessibility review for this work. The majority of the issues so far are in the CMS itself, and I'm still trying to find out who to assign that to. For now, Trevor said to assign it to you, but the label has CMS. 

When the audit is complete, I'll post a comment here to let you know.

**Comment by jenstrickland** [comment]
@AkucherGCIO The accessibility review is complete. It's okay to begin working on the issues now.

Please let me know if you'd like to review the issue tickets above, or if any clarification is needed. Per discussion with Kevin Walsh of the CMS team, the CMS tickets above are for your team.

The next step is to send to the VA 508 Office for their review. I will send them a list of the known issues.

**Comment by lwalsh617** [comment]
@jenstrickland @stephorkandatx - I believe all issues in this ticket were either:
- Solved by migration to Drupal
- Are bigger template/site wide issues to solve. Do we have a ticket for those larger issues?

**Comment by jenstrickland** [comment]
@lwalsh617 @stephorkandatx Thanks for your diligence! The open items above are all sitewide / design system / CMS / components, and assigned to VSP to address. They remain in the epic for this work, where the issue was documented, but your team is not responsible for addressing them. VSP will address.

**Comment by jenniferlee-dsva** [comment]
completed, including tickets. closing.
