### ISSUE TITLE
End VA.gov session if logged out on other SSO site

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#6336]
As a Veteran who has logged out on MHV, eBenefits, or some other SSOe-enabled site, I want my VA.gov session to also end.

**Comment by patrickvinograd** [comment]
Ticket #7127 overlaps with this one - thinking about how to reconcile the MHV vs. SSO cookie detection when we are authenticating a user. 

It might be tricky since we can detect presence of the SSO cookie on the _frontend_ but can detect and deal with the MHV shared cookie on the _backend_.

**Comment by ericbuckley** [comment]
Would this only be needed for our inbound SSO launch?
