### ISSUE TITLE
Vets-api terminal access for Derek Fitchett

### ISSUE THREAD

**Issue by dfitchett** [department-of-veterans-affairs/va.gov-team#63363]
### Your Name

Derek Fitchett

### Your GitHub handle (terminal access is managed through GitHub)

@dfitchett

### Team, Role, and Company of the target individual

Software Engineer on Employee Experience Team, Agile 6

### Product Manager (PM) name and email

Amy Lai amylai@navapbc.com

### Product Owner (PO) name and email

Zach Goldfine zachary.goldfine@va.gov and Emily Theis emily.theis@va.gov

### COR Name (leave "None" if you listed an AWS user name above)

Jennifer O'Day

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

Agile Six - Anthony M. Arashiro

### Please confirm if you are on the VFS Team Roster or Platform Team Roster

- [X] [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Please confirm E-QIP Transmittal/Adjudication. This could be a screenshot of your Transmittal/Adjudication email, a link to another request where you've submitted this proof (i.e. AWS/SOCKS), etc.

- [X] I have attached proof that I have either transmitted my E-QIP survey or previously received a favorable decision (by including in "Additional Notes" section below)

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [ ] production (if requesting, justify prod access in 'Additional Notes' section)

### Additional Notes

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/135860892/090c27b2-05fa-4e9d-8628-a42b13d267a3)

### Additional resources for Support Engineer

- [ ] For users on a VFS team but not in the VFS Team Roster, they must start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] Instructions for handling requests [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access) - Support Only

**Comment by bdech** [comment]
found in VFS Team Roster

**Comment by bdech** [comment]
@dfitchett You’ve been granted access to the `dev`, `staging`, and `sandbox` environments.

Here's some additional documentation for the [Vets API on EKS](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-TerminalAccess)
