### ISSUE TITLE
Determine Strategy to raise ForeSee Data Awareness

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#6337]
## User Story or Problem Statement
How might we provide more awareness to all teams that ForeSee data exists?

## Goal
Determine a strategy to report or raise awareness for ForeSee user data use for VFS teams.

## Acceptance Criteria
- [ ] Joanne, Chante, Amy, & Kimberley schedule brainstorm strategy session
- [ ] Platform Insights has a drafted strategy to report ForeSee data that can be globally seen by VFS teams
- [ ] The strategy is linked to current Contact Center triaging as well as the Product Success Tool strategy so that the data is not silo'd and can eventually link up to a single source for VFS teams
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by joanneesteban** [comment]
### Some Follow Up 

**Question for Nancy**: If we can pull in open-ended questions to Domo, can we? We would have to hide the PII on Domo.

** @amycesal  to Follow Up**: Consumer Financial Protection Bureau & their data munging.

**Comment by amycesal** [comment]
Adding the follow up. CFPB has a script that they created with Deloitte to remove PII from comments.
