### ISSUE TITLE
Adding Eric Hoelzer to DSVA Slack

### ISSUE THREAD

**Issue by katieriddle** [department-of-veterans-affairs/va.gov-team#63372]
Eric Hoelzer is a new program manager on behalf of Ad Hoc, and it is requested he be a full member. He will be engaged in the team discussion, and he will need oversight of the Ad Hoc team members.

Initially, he will need access to these channels: 
#1010-health-apps
#accountexp-authexp
#sitewide-program
#veteran-facing-forms

Thanks!

**Comment by LEHigley** [comment]
need an email address

**Comment by katieriddle** [comment]
Email:  eric.hoelzer@adhocteam.us

**Comment by katieriddle** [comment]
@LEHigley Just checking in on this one. Really appreciate your help/support!
