### ISSUE TITLE
Add practice area label and touchpoint label to DI and MPR feedback tickets

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#63370]
## User Story
As a Governance team member, I want to ensure touchpoint and practice area labels are added to my Design Intent and Midpoint Review feedback tickets so that I can begin pulling this data into Domo for analysis.

Assignee: @CherylEvans 
Peer Reviewer: @erinrwhite 

## Description
Governance team does not add the practice area label or the touchpoint label to the feedback tickets created at Design Intent and Midpoint Review. As our Collaboration Cycle dashboard matures, adding these labels to our tickets will help us tie feedback from earlier touchpoints to findings at Staging Review. While we are not currently pulling the DI and MPR data into Domo for analysis, by implementing this change now we'll be able to seamlessly connect DI, MPR and SR data in a future state of the Collaboration Cycle dashboard.

This ticket will serve 2 purposes:

1. Updating the DI and MPR operational process for documenting feedback to ensure that touchpoint and practice area labels are added consistently moving forward.
2. Adding touchpoint and practice area labels to historical feedback tickets from January 1, 2023 forward. We will not be updating tickets created prior to 2023 (at this time).

Touchpoint labels:
`design-intent`
`midpoint-review`

Practice area labels:
`content`
`design`
`IA`
`accessibility`

Note: `QA` label is not applicable as QA feedback is not provided at Design Intent or Midpoint Review. 

## Impacted Artifacts
[How to document feedback for a Design Intent](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1934426130/How+to+document+feedback+for+a+Design+Intent)
[How to document feedback for a Midpoint Review](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1945239838/How+to+document+feedback+for+a+Midpoint+Review)

### Operational process

- [x] Add a step the Design Intent document feedback process for adding the touchpoint label:  `design-intent` 
- [x] Add a step the Design Intent document feedback process for adding the practice area label:  `design`, `IA`, or `accessibility`
- [x] Add a step the Midpoint Review document feedback process for adding the touchpoint label:  `midpoint-review` 
- [x] Add a step the Midpoint Review document feedback process for adding the practice area label:  `design`, `IA`, `content` or `accessibility`
- [x] Optional: for both DI and MPR, former team member Jim Ryan created "readymade Design Intent feedback tickets" and "readymade Midpoint Review feedback tickets" that are currently linked in the How to provide feedback for a Design Intent and How to provide feedback for a Midpoint Review guidance pages. If the team would find it valuable to have these templates pre-populated and ready to go, we can and should create them as part of this ticket. 

### Historical tickets
- [x] [This query ](https://github.com/department-of-veterans-affairs/va.gov-team/issues?q=is%3Aopen+is%3Aissue+label%3Acollab-cycle-feedback+label%3Acollaboration-cycle+created%3A%3E2023-01-01+-label%3ADS-Staging-Review)shows all design intent feedback tickets and midpoint review feedback tickets from 2023. As of 8/15, there's 187 issue tickets where we will need to add 1) touchpoint:  `design-intent` or `midpoint-review`, and 2) practice area: `content`, `design`, `IA`, or `accessibility`
- [x] Please check the boxes below to verify that both labels have been added for your applicable practice area tickets:
   - [x] Allison added `design` label and `design-intent` label to all Design Intent - design feedback tickets
   - [x] Allison added `design` label and `midpoint-review` label to all Midpoint Review - design feedback tickets
   - [x] Erin added `IA` label and `design-intent` label to all Design Intent - IA feedback tickets
   - [x] Erin added `IA` label and `midpoint-review` label to all Midpoint Review - IA feedback tickets
   - [x] Brian added `accessibility` label and `design-intent` label to all Design Intent - accessibility feedback tickets
   - [x] Brian added `accessibility` label and `midpoint-review` label to all Midpoint Review - accessibility feedback tickets
   - [x] Cheryl added `content` label and `midpoint-review` label to all Midpoint Review - content feedback tickets

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Feedback tickets from Jan 1 2023 onward have both the touchpoint and practice area label
- [x] Governance team members have a process for adding the touchpoint label and practice area label to all future Design Intent and Midpoint review touchpoints

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by erinrwhite** [comment]
Updated historical IA tickets - 48 tickets total.

**Comment by CherylEvans** [comment]
Updated historical Content tickets - 9 tickets total

**Comment by CherylEvans** [comment]
Documentation Drafts created:

- [How to document feedback for a Design Intent](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2742190141/63370+-+Cheryl+-+Copy+of+How+to+document+feedback+for+a+Design+Intent)
- [How to document feedback for a Midpoint Review](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2742190158/63370+-+Cheryl+-+Copy+of+How+to+document+feedback+for+a+Midpoint+Review)

**Comment by CherylEvans** [comment]
@erinrwhite The first four tasks in the Operational Process section were updated in my drafts. Once you give the thumbs up, I will update the source pages with those changes.

**Comment by erinrwhite** [comment]
@CherylEvans Looking good! I didn't think about this earlier, but doublecheck the prepopulated titles on the DI and MPR readymade tickets. Right now the ticket titles are all saying "design feedback" and should be updated for each ticket type...

so in the URL for those links, check the title attribute as well as adding the tags:

For example, the part of the address `&title=Design+Intent+-+Design+Feedback+-+Name+of+Project` would become 
`&title=Design+Intent+-+IA+Feedback+-+Name+of+Project` for IA

I think that captures it! Let me know if you want a doublecheck on any URLs.

**Comment by CherylEvans** [comment]
@erinrwhite It is now correct on both source pages. Please double-check to ensure. :-)

**Comment by erinrwhite** [comment]
@CherylEvans double-checked. All links working as they should! 👍🏻

**Comment by allison0034** [comment]
I have updated all the design tickets

**Comment by erinrwhite** [comment]
All set! I found a few tickets that needed labels and got those added as well. 👍🏻 Think we are good to close.

**Comment by CherylEvans** [comment]
@erinrwhite Thank you. The source documents are updated. :-)
