### ISSUE TITLE
Limit PDF file size to 99 MB

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#63384]
This helps EVSS deal with the increased user load and mitigates timeouts.

**Comment by jerekshoe** [comment]
I think this is done right @kjduensing?

**Comment by jerekshoe** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/25153

**Comment by kjduensing** [comment]
oh. yep.

**Comment by jerekshoe** [comment]
@kjduensing can you add an estimate to this? Want to make sure you get credit for the effort put into this
