### ISSUE TITLE
[SW] Midpoint Review - Design Feedback - Change the sim alert to a standard alert (63286)

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#63392]
During the midpoint review there was one question and one update that needs to be made noted here #[63286](https://app.zenhub.com/workspaces/collaboration-cycle-reviews-61d89e9e5f4c120011a0ad37/issues/gh/department-of-veterans-affairs/va.gov-team/63286)

- I do have a question. In the work history, I added 2 jobs. After adding the 2nd job, but before clicking "Continue" I only see 1 job card, not 2. I never saw the 2 jobs together. Is that just part of the prototype? In other words will the user see all work history cards before proceeding the the next chapter?
- <img width="698" alt="Screen Shot 2023-08-08 at 12 20 18 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/72398073/9f9c906e-ae65-4192-ac8b-5ab6004b566e">
- Also keep in mind that if the user deletes one of those cards they will need to have some sort of action to confirm deleting it. I have seen some use a modal. Jeanna Clark may have some advice on that. Since I was not able to test the delete I just wanted to make you aware before Staging.
##
- **Must**: There is a [wizard](https://design.va.gov/patterns/wizards) at the beginning of the form for "Is this the form I need?". We have moved to a 1 thing per page for accessibility reasons. Change the wizard and remove the conditional logic. If this page is not included in this review please put this on the back log.
- **Must**: Love the new card style! [This card](https://design.va.gov/components/card#with-drop-shadow) is now in the design system. It looks as though your drop shadow is slightly different. Please align with the design system drop shadow.
- **Must**: You are using a slim alert for the "You can skip questions..." message. [Slim alerts](https://design.va.gov/components/alert#when-to-use-a-slim-alert) are mostly reserved for immediate feedback without a full page load. Instead use the [standard alert](https://design.va.gov/components/alert#informational-alert).
- <img width="764" alt="Screen Shot 2023-08-08 at 12 30 02 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/72398073/ac09fa92-95ee-4475-85b3-4acfad2951dd">

**Comment by HeatherRienks** [comment]
@josephrlee will address alert and shadow feedback
@mgleo will share Wizard feedback

**Comment by mgleo** [comment]
Alert style and platform ticket have been updated.
@Tom-Davis @HeatherRienks

**Comment by HeatherRienks** [comment]
Great! Is there anything left to do on this ticket? Looks like we are done!  If so, let's move it to Validate! Thanks!!!
