### ISSUE TITLE
[SW] Midpoint Review - IA clarification updates (63343) (Post Launch)

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#63395]
During the midpoint review there 3 updates that needs to be made noted here #[63343](https://app.zenhub.com/workspaces/collaboration-cycle-reviews-61d89e9e5f4c120011a0ad37/issues/gh/department-of-veterans-affairs/va.gov-team/63343)

- **Consider:** which step the [You can skip questions](https://preview.uxpin.com/bee98dfe15974e66ea5958c976cb43a2c08ecabc#/pages/163781813/simulate/sitemap?mode=cvhid) page H2 should display. It's currently listed under Step 7: Review Information, which is a bit of a leap after users are on step 2 or 3.
- **Consider:** [Final review page](https://preview.uxpin.com/bee98dfe15974e66ea5958c976cb43a2c08ecabc#/pages/163781815/simulate/sitemap?mode=cvhid) - Statement of truth mentions bankruptcy history, but it wasn’t asked about in the UXpin user flow. Might cause confusion for Veterans if they see this and wonder why they weren't asked about it.
- **Consider:** Continue working with CAIA on [confirmation page](https://preview.uxpin.com/bee98dfe15974e66ea5958c976cb43a2c08ecabc#/pages/163781844/simulate/sitemap?mode=cvhid) content for scannability and clarity to help the Veteran quickly understand that their information has been submitted and what they need to do next. "You don't need to do anything else at this time" might be the most important sentence on the page, and it's down the page a bit.

**Comment by HeatherRienks** [comment]
Per sprint planning on 8/15 - we need to review these 3 items.

Some items are not showing on staging (Ex: green box "You're tentatively eligible...")

**Comment by josephrlee** [comment]
I'm looking at these, and I believe we have fixes in place for all of them and that they've been accounted for. 

I think this can be closed, moving it to validate for now, and I'll let @Tom-Davis close it out!

cc: @mgleo , @HeatherRienks
