### ISSUE TITLE
SOCKS access for Tanner Heffner

### ISSUE THREAD

**Issue by tjheffner** [department-of-veterans-affairs/va.gov-team#63391]
### Your Name

Tanner Heffner

### Your Email

tanner.heffner@agile6.com

### Your Role and Team

Tech Lead on Accelerated Publishing

### Product Manager (PM) name and email

Tim Cosgrove, tim.cosgrove@agile6.com

### Product Owner (PO) name and email

Erika Washburn, Erika.Washburn@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDoydH3JuigZZo10anObGIi3GFsnxjDvB8QT0HcME67cmb0lM394JfwXvoct44hELw+OYE+kniaEC8ybArMU9dOtZ4cQsuW5z7fji8TCJ1SfuLoQGnPzVh70Hh5Q+7n5zFqDDqtu53wsEVCwqO+vN3Fd+lsIgNImvS4RJOO0HrjkJKg9K+9m3DCJHkEXD7AqR5OdzNqQAmQFNqEsugdUmtW4sZ7s60LC0h2FmB1dtQwEI9tepRvMsUyLnxfZ05HoBQbEJ3WZE20XFrnJ0vtwR5VnVrsdhEuHkzWGzR0orXATiYOWnJP4wYkQxTzNAcaavvitkVVYsr3sdqsS0aQ+NRMOQsg5Df7PTQUROtE8Ox6JPLDAwmjKvyWfZcAT4asuepLrpORoM+MnukwtluRNcIb6C4ZM78A1OHypi3Ys0RP3j8HfsKSpez+D3R+7PwNczjcdTpWlBr61Povo5p4eoIkuqGzfODRmGTtFkudFG0kLkj9wq1/JohntfBY+7ns710= heffner@Tanner-Heffner.localdomain

### E-QIP Transmittal Confirmation

I did not receive a file confirmation this time, as I had a previous e-QIP from my last engagement with the VA.
`A background investigation (T2) has been completed for TANNER JAMES HEFFNER on 02/09/2022. A Favorable determination has been made on 07/25/2023`

previous onboarding / offboarding tickets:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/32245
https://github.com/department-of-veterans-affairs/va.gov-team/issues/52193

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by ph-One** [comment]
SOCKS access completed
