### ISSUE TITLE
[SW] Midpoint Review - IA links and typo updates (63343)

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#63393]
During the midpoint review there 3 updates that needs to be made noted here #[63343](https://app.zenhub.com/workspaces/collaboration-cycle-reviews-61d89e9e5f4c120011a0ad37/issues/gh/department-of-veterans-affairs/va.gov-team/63343)

- **Must:** Include an exit route or next step for users who see error states for overstatements or copays Example error page - current error pages are a dead end
- **Must**: Privacy policy link next to the checkbox on the final review page should have an indicator that the link opens in a new window so that users know they can review the link while staying in the form flow.
- **Must**: Fix small typos, apologies if this is already in the hopper or on another ticket:
Your spouse’s info - “mariatal” should be marital
Your current job deductions and Spouse deduction amounts - "Retirment" should be Retirement

**Comment by HeatherRienks** [comment]
@mgleo - will check on Staging/protoypes for typos
@josephrlee - will check on privacy link
@mgleo - will check on exit route - where should we direct user to?

**Comment by mgleo** [comment]
- Updated the prototypes to correct typos (only present there)
- Updated the privacy policy on prototypes
- Updated the exit route on the prototype

Still to do:
- Update the privacy policy on staging/production
- Update the exit route on staging/production

@Tom-Davis @HeatherRienks

**Comment by HeatherRienks** [comment]
@mgleo - fabulous! Is there any additional help that is needed from FE to complete the "Still to do" items?

cc: @Tom-Davis

**Comment by OptionSelect** [comment]
We need more clarification on which pages are a dead end and what they mean by exit route. I don't really have any context on what to do other than when they tell us what pages have errors to add a link back to the form or something.

@Tom-Davis @HeatherRienks

**Comment by mgleo** [comment]
Hi @OptionSelect, 
We need an action link that takes you back to the homepage on each Error or Empty state. 
Here are the mockups:
[Empty state- no copays or overpayments](https://preview.uxpin.com/6940f648e5994b8fad9550934a5530b4cd73cacb#/pages/163500322/simulate/sitemap?mode=i)
[Error state- no copays or overpayments](https://preview.uxpin.com/6940f648e5994b8fad9550934a5530b4cd73cacb#/pages/163500323/simulate/sitemap?mode=i)
[Error state-  overpayments only](https://preview.uxpin.com/6940f648e5994b8fad9550934a5530b4cd73cacb#/pages/163500324/simulate/sitemap?mode=i)
[Error state-  copays only](https://preview.uxpin.com/6940f648e5994b8fad9550934a5530b4cd73cacb#/pages/163500325/simulate/sitemap?mode=i)

**Comment by OptionSelect** [comment]
Thank you I'll start on it

**Comment by OptionSelect** [comment]
PR for Exit Link: https://github.com/department-of-veterans-affairs/vets-website/pull/25184
