### ISSUE TITLE
[SW] Midpoint Review -Design Feedback: Profile update when prefilled data is updated (63286) (Post Launch)

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#63397]
During the midpoint review there was one post MVP update that needs to be made noted here #[63286](https://app.zenhub.com/workspaces/collaboration-cycle-reviews-61d89e9e5f4c120011a0ad37/issues/gh/department-of-veterans-affairs/va.gov-team/63286)

- **Should:** In your form when a user updates any pre filled information from their profile it does not update profile, it only updates this application. The preference is to have the profile updated as well.

**Comment by mgleo** [comment]
This has been updated on our prototypes/staging/production. 
@Tom-Davis @HeatherRienks
