### ISSUE TITLE
AWS access for Tanner Heffner

### ISSUE THREAD

**Issue by tjheffner** [department-of-veterans-affairs/va.gov-team#63403]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Other - please specify in 'Additional Notes'

### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Tanner Heffner

### Your Email

tanner.heffner@agile6.com

### Team, Role, and Company of the target individual

Accelerated Publishing, Tech Lead, Agile 6

### Product Manager (PM) name and email

Tim Cosgrove, tim.cosgrove@agile6.com

### Product Owner (PO) name and email

Erika Washburn, Erika.Washburn@va.gov

### Desired AWS Access

I should have similar AWS access as Tim Cosgrove (@timcosgrove)

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

I did not receive a file confirmation this time, as I had a previous e-QIP from my last engagement with the VA.
`A background investigation (T2) has been completed for TANNER JAMES HEFFNER on 02/09/2022. A Favorable determination has been made on 07/25/2023`

previous onboarding / offboarding tickets:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/32245
https://github.com/department-of-veterans-affairs/va.gov-team/issues/52193

### Additional Notes

VOR: Scott Mason, Booz Allen Hamilton

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [ ] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [x] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by timcosgrove** [comment]
https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster#Accelerated-Publishing-Team

**Comment by hgbarreto** [comment]
User can be found in the [Platform Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster#Accelerated-Publishing-Team)

**Comment by flooose** [comment]
@BillChapmanUSDS I'm adding "Awaiting Approval" for this one because the role involves elevated access.

**Comment by timcosgrove** [comment]
@flooose who would be the approver in this case?

**Comment by BillChapmanUSDS** [comment]
@timcosgrove  Under our  current policy we are asking that when one asks for production environment access they list at least one task they need to do that cannot be accomplished (or is very difficult) on lower environments. We will not judge the validity of the request but are trying to compile a full list of toil and how we can add tools and policies to help folks not need to be in production environments and also want to make sure we are not giving out  "just in case I need it" access. 

But with the #access-justification-example-provided tag added and the above question answered it can be extended to 6 month between approvals and we are hoping to have a tighter process in place by then.  

@flooose  access approve for 3 months to get them moving,  you can extend to six month if they add the example and tag.

**Comment by timcosgrove** [comment]
@BillChapmanUSDS apologies for missing your comment here - I need to get better at filtering my Github notifications down to useful ones :)

@tjheffner is the technical lead on the Accelerated Publishing project. In that role he will be working on setting up production systems for Accelerated Publishing. This may include:

* instantiating and troubleshooting EC2 instances running the Accelerated Publishing build system
* Accessing and troubleshooting S3 instances that are ultimately Veteran-facing (content.www.va.gov among them)
* Accessing and troubleshooting VA CMS, including production, to set up and troubleshoot integration between the CMS and the AP build system
* Creating stored values/secrets in AWS SSM Param store

He does *not* need access to the clusters that run api.va.gov, nor direct access to the reverse proxy (though we will eventually be proposing small modifications to how traffic gets routed to content.www.va.gov). 

Let me know if that's sufficient justification for allowing Tanner's access to continue to be elevated.

Best, Tim Cosgrove

**Comment by ph-One** [comment]
Pulling in @JonathanKamensDVA , since he is now handling these requests

**Comment by JonathanKamensDVA** [comment]
Approved.

**Comment by JonathanKamensDVA** [comment]
@ph-One tagging me should _theoretically_ be sufficient to get my attention about issues like this, but as a hedge against the future when my inbox is so full that keeping up is more challenging, and also to ensure that other people can back me up when I'm unable to handle access requests, please also remember to add the "Awaiting Approval" tag.

**Comment by ph-One** [comment]
> @ph-One tagging me should _theoretically_ be sufficient to get my attention about issues like this, but as a hedge against the future when my inbox is so full that keeping up is more challenging, and also to ensure that other people can back me up when I'm unable to handle access requests, please also remember to add the "Awaiting Approval" tag.

Thank you. I only tagged you bc of the age of this request, and was not sure if it was captured on anyone's radar. I'll verify that older requests have the labels you're looking for. Thanks, again

**Comment by ph-One** [comment]
Work completed. This was merely an approval for continued access. The user already had production access.
