### ISSUE TITLE
[SW] Midpoint Review - Accessibility headings updates (63355) (Post Launch)

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#63406]
During the midpoint review there 2 updates that needs to be made noted here #[63355](https://app.zenhub.com/workspaces/collaboration-cycle-reviews-61d89e9e5f4c120011a0ad37/issues/gh/department-of-veterans-affairs/va.gov-team/63355)

- **Should:** I really appreciate the unique H3 headings describing each page within the multipart steps. If you're not already planning to do this, those headings should receive keyboard focus when landing on each page of the workflow. That will ensure they're the first thing a screen reader user hears --- meaning they'll know they've advanced to the next step and have some context for where they are, instead of hearing "Step 1 of 7" multiple times as they move through the workflow.

**Comment by HeatherRienks** [comment]
@OptionSelect to confirm this has been completed.

**Comment by HeatherRienks** [comment]
@Dr-Pongo to confirm if this has been completed.

**Comment by HeatherRienks** [comment]
Great, thanks @OptionSelect and @Dr-Pongo! Closing this ticket.
