### ISSUE TITLE
spike | BE | Profile | VA Profile API

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#63408]
## Background 
There are some other teams that are migrating from EMIS that are potentially already plugging into VA Profile API. 

We need to check in w them and get a brain dump from them to see if it's worth it to move forward w/ connecting to the API.

**Comment by tpharrison** [comment]
Travis and I met with Rebecca Tolmach on 8/24 to discuss scope of work for migrating military service history from eMIS to Lighthouse.  

We explained that our team already migrated our military service history endpoint from eMIS to VA Profile last year (for the Profile page dependency).  For the LH migration, the benefits-disability team is responsible for migrating military service history from eMIS to Lighthouse (which calls VA Profile).

At this point, we don't have any responsibilities or assignments for this migration.  However, we did communicate that we are willing to provide assistance if needed.

cc/ @mtcA6

**Comment by mtcA6** [comment]
@tpharrison this ticket is for the discovery around the VA Profile API stuff, plugging into their API for that expanded list of items. This ticket is specifically to figure out all the things we'd need to do to plug into that API ([see the EPIC](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63024)) 

Not the same eMIS convo from last week.

**Comment by mtcA6** [comment]
i think we can close this out as not-planned for now, we are likely going to get at some of this data with the  military information work but the original idea behind this ticket and the corresponding epic was to help us where there were gaps w/LH. We've since found we don't really need this.
