### ISSUE TITLE
Design for deleting an uploaded file

### ISSUE THREAD

**Issue by lydiahooper** [department-of-veterans-affairs/va.gov-team#63414]
The scope of this ticket is to identify improvements to UX of uploading and deleting files that will be attached to digital claim. We need to ensure UX is easy for all use cases, including users with more than one document and users who decide not to upload. Also need to address [accessibility concerns flagged in collab cycle staging review](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/59263), and consider recommendations made in that ticket.

**Comment by mengA6** [comment]
@jinaryu and I will be starting on this:

1. Replicate and get screenshots / screen recordings of the issue in staging
2. Identify design system components / patterns we could use to address it

**Comment by mengA6** [comment]
Jina found that there was a confirmation dialog in staging. 
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTNCQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3a51f2fcaa83531065598839c5cb9e135b68a3c2/screen-capture.webm)

We are trying to follow the TestRail case to reproduce this as it was found

https://dsvavsp.testrail.io/index.php?/projects/overview/65
Project - 526 / Disability experience
There is a testplan for BDD SHA

- [requesting access to TestRail here](https://dsva.slack.com/archives/CBU0KDSB1/p1709831328293849).

**Comment by mengA6** [comment]
Also need to capture the screen reader experience. I'm testing with VoiceOver on Mac OS

**Comment by mengA6** [comment]
[BDD Add Separation Health Assessment - TestRail.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDNDQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--51f67496af2f37d938e9be96cf7919d21c55d24c/BDD%20Add%20Separation%20Health%20Assessment%20-%20TestRail.pdf)

I think ^ is the test case to use

**Comment by mengA6** [comment]
Verified as close as I could to the test case that this delete confirmation dialog is in place on staging, and it is announced as expected to screen readers (tested with Mac OS VoiceOver)


[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGZDQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--089613ce2790dee725d8b50d766a9fb54592048e/upload%20evidence%20-%20delete%20confirmation%20%28voice%20over%29.mp4)

**Comment by jinaryu** [comment]
Verified delete confirmation dialog is in place on staging for BDD flow as well.

![BDD delete file](https://github.com/department-of-veterans-affairs/va.gov-team/assets/141759567/02e8a836-c6a7-4afa-98f1-cea63688cb0a)
![BDD delete file alert](https://github.com/department-of-veterans-affairs/va.gov-team/assets/141759567/c29a999a-6990-44f4-a3db-3b30294d6cbc)

https://github.com/department-of-veterans-affairs/va.gov-team/assets/141759567/05dbe85a-f4d2-40bf-bce4-3fa6ffef8572

**Comment by mengA6** [comment]
@jinaryu completed a [design for a confirmation on file deletion](https://www.figma.com/file/rG5tNh3dS8FUoc5jtDshUk/526EZ-BDD-SHA-updates?type=design&node-id=15-3412&mode=design&t=XEeRWppIU7SFnyWo-11). This is based on the [content style guide page on feedback messages](https://design.va.gov/content-style-guide/error-messages/feedback), which is specific about the language and alert placement for a delete confirmation

**Comment by mengA6** [comment]
Realized that the style guide guidance specified a "dismissible" alert component for these scenarios, so I've updated the Figma file with that. Also verifying with [this platform support ticket](https://dsva.slack.com/archives/CBU0KDSB1/p1710188854023859) what the height is supposed to be when there is no message content (only a title).
