### ISSUE TITLE
Analytics New KPI dashboard request for Authenticated Experience

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#63413]
# Request a New Standardized KPI Dashboard

## What this form is for

Use this ticket template to request a new standardized KPI dashboard on Domo for your product. To make updates to a product already on a standardized dashboard, please use the [Request an Update to your Standardized KPI Dashboard template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=michelle-dooley&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&template=analytics-request-update-kpi-dashboard.md&title=Analytics+KPI+dashboard+update+request+for+%5BTeam%5D).

Standardized dashboards are currently available for Forms, Content, & Search products only. To see if you should request a standardized dashboard, check [Should I request a standardized KPI dashboard](https://docs.google.com/presentation/d/16mRcslbkWtW44rlsfQGXZnHtQ3GoLjn6GpFnd3Gvva8/edit#slide=id.p). If you’re not sure which dashboard(s) your product(s) qualify for, check the [Eligibility Dashboard](https://va-gov.domo.com/page/1550814739).

If your VA.gov product is not eligible for a standardized dashboard, you may be able to request an “edge case” dashboard. Please reach out to the Platform Analytics & Insights team on #vfs-platform-support for more information on this process.

### Expected delivery timelines

Once you’ve submitted this ticket template, your KPI dashboard request will be pulled into the Analytics team’s workflow the following Wednesday during Platform Sprint Planning or Refinement. We expect to deliver your completed dashboard within **2-4 business** days from this time. 

## Instructions for the VFS team
In order to pull the correct data for your product, we need your help to define what pages and events to include, in addition to basic product info. We’ll need a filled out [KPI request template](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit#gid=981224988) before we can pull this ticket into our sprint.

*NOTE: If you do not have Google access, you can download an Excel version of the template [here](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/1586823275/KPI%20Dashboard%20Product%20Details%20Template%20-%20MAKE%20A%20COPY.xlsx?inst-v=ced1f4dd-e997-4aa2-9ae8-2cebe369b42f).*

- [x] Make a copy of the [Google Sheet](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit#gid=981224988) [(or download Excel version)](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/1586823275/KPI%20Dashboard%20Product%20Details%20Template%20-%20MAKE%20A%20COPY.xlsx?inst-v=ced1f4dd-e997-4aa2-9ae8-2cebe369b42f)
- [x] Complete worksheet as instructed
- [x] [Link your completed spreadsheet here](https://docs.google.com/spreadsheets/d/1fzYoQ7zJ-R3x_x3eTA8xKmprwfMipipaoxRmYLRiGYs/edit#gid=981224988)
- [x] Check your sharing settings to make sure the Analytics team will be able to access it
- [x] Add your team label to follow progress

**Additional Info**

- Please use the [KPI Framework](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/Analytics%20Playbook/va-gov-platform-analytics-kpi-framework.pdf) for more information on the metrics used in the Standard KPI dashboards. 
- If you need any analytics support, read through the [How to request Analytics support](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guidelines.1586823275.html#Analyticscustomersupportguidelines-4.RequestaKPIDashboardinDomo).
- If you do not have Domo access, please [request access here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+access-request&template=analytics-request-google-analytics-domo-access.md&title=Request+access+to+Google+Analytics+and%2For+Domo).
---
## Request details

We need a dashboard (GA or Domo, whatever is easiest) that tracks the following:

- Total clicks into this menu:

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/34068740/3e0cd81b-0cce-46c9-ad8e-457b8958351e)

- From that menu, total clicks into each of the pages listed in the menu
- And for comparison purposes, total clicks into this menu **when users are logged in**:

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/34068740/02e73a90-3238-4514-bc3a-982b96a5006e)

**Comment by Samara-Strauss** [comment]
@ajakabcin @mtcA6 just FYI that I submitted a request for analytics on the authenticated menu.

**Comment by michelle-dooley** [comment]
@Samara-Strauss I think we can get to this in GA with current event tracking.

events from top right menu drop down (I don't see MHV or sign out though - not sure how important those 2 are for you?) 
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/93597659/830ae636-e084-4708-ae98-eda870cfe080)

events from the top left menu (GA report will need to use LOA segment)
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/93597659/04e5b689-946e-46a6-8e63-a54a1ff224af)

@jessicastump can look at creating a GA report for this and will get back to you with any questions.

**Comment by Samara-Strauss** [comment]
@michelle-dooley @jestutt can we get a status update on this?

**Comment by jestutt** [comment]
@michelle-dooley Here's the [GA dashboard](https://analytics.google.com/analytics/web/#/dashboard/jTwco5hFRBmuXcjZN9YSPA/a50123418w177519031p176188361/)

A couple items: 

- There is no menu open event when someone clicks on the user menu.
- For the 'VA Benefits and Health Care' navigation clicks, we can only tell that someone was logged in during that Session, not that clicks happened before or after that login.  

Any question, comments or changes?

**Comment by Samara-Strauss** [comment]
@jestutt thanks for this! I do have a couple requests:

Can you put the following in a table instead of individual graphs?:

- My VA clicks
- Profile clicks
- My Health clicks
- Sign out clicks

For clicks into the VA Health and Benefits menu, you can remove the requirement to only show this for signed in users. I can add that as a segment if I want to see info by logged in/out users.

**Comment by Samara-Strauss** [comment]
Yes, this more closely matches the layout I was hoping for. Thanks!

I want to confirm we're looking at the correct data, though. Given that there are links to My VA and MyHealtheVet in the main nav, are we sure those clicks are not being calculated in the Total Menu Clicks table? For the purposes of this dashboard, I only want to see clicks into these tools from the "name" menu, not the main nav.

So only clicks from here:

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/34068740/5d1c3463-67ad-4dcf-83d7-83abf43845e2)

NOT from here:

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/34068740/0cb25643-650f-4048-9b86-b39a39451153)

**Comment by jestutt** [comment]
@Samara-Strauss Were there any more questions or changes? If not, I'll mark this as closed.

**Comment by Samara-Strauss** [comment]
Great! Thank you. No more questions, but one more request -- could you put total authenticated menu clicks into the same table with the My VA/MHV/Profile clicks? And then could you also show the clicks into VA Health Care and Benefits as a separate table? That'll just be easier to see/compare the data that way. Then I think we are done and good to close this ticket.

**Comment by Samara-Strauss** [comment]
Actually, another thing (sorry!) -- we just added two links to this menu in staging, and we plan to launch to prod soon. Can you add tracking for the links for Letters and Dependents so that we can see data when those links go to prod?

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/34068740/43c15593-cc29-46e4-9c89-d9c6ca564e51)

**Comment by jestutt** [comment]
> Great! Thank you. No more questions, but one more request -- could you put total authenticated menu clicks into the same table with the My VA/MHV/Profile clicks? And then could you also show the clicks into VA Health Care and Benefits as a separate table? That'll just be easier to see/compare the data that way. Then I think we are done and good to close this ticket.

@Samara-Strauss  What do you mean by total authenticated menu clicks?

**Comment by jestutt** [comment]
@Samara-Strauss As I said when I first shared the dashboard link last night, there is no event for users clicking to open the User menu. That chart is the cumulative clicks on the menu items -- which I guess you could say is also the minimum times it was opened since it had to open for those links to be clicked on.

**Comment by Samara-Strauss** [comment]
@jestutt I am sorry I missed that earlier. Then we do not need the graph for total menu clicks, so can you take that out?

**Comment by jestutt** [comment]
@Samara-Strauss I removed the Total Menu Click chart and added a table for the 'VA Benefits and Health Care' clicks. Any other edits? 

For the name change of 'My Health' to 'My HealtheVet' and the new items in the User menu, you need to request the correct tracking code be added. It will be the same as the one on "My VA" and "Profile" only with click text that aligns to the new links. Once that's in place, they should automatically show up in the dashboard.

**Comment by Samara-Strauss** [comment]
@jestutt thank you! This looks great.

> For the name change of 'My Health' to 'My HealtheVet' and the new items in the User menu, you need to request the correct tracking code be added. It will be the same as the one on "My VA" and "Profile" only with click text that aligns to the new links. Once that's in place, they should automatically show up in the dashboard.

@mtcA6 can you create a ticket to add FE tracking to the Dependents and Letters links in the auth menu?

**Comment by Samara-Strauss** [comment]
Thank you @mtcA6! @jestutt this should be good to close.
