### ISSUE TITLE
CF: Post Test Prototype Updates

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#6345]
Update prototype after usability testing
Distribute to UX Team
Review / Update, if necessary

**Comment by amyknox** [comment]
**Finding: Veterans perceive equivalence between VA & DOE caution flags and feedback from students**

- Veterans tended to weigh caution flag detailed descriptions equally with Student Feedback in the Cautionary Information accordion.​
- 
- Some Veterans bypassed the caution flags and studied the student feedback section more intently.

**Recommendation**
Incorporate a heading into the Cautionary Information accordion that conveys the importance and credibility of caution flags.

**Comment by ccruzgra** [comment]
Prototype has been updated here: https://bahdigital.invisionapp.com/share/NCIAD3HABU7
