### ISSUE TITLE
Update MHA rates on current Post-9/11 GI Bill and Fry Scholarship rates page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#63455]
## Issue Description
We learned we have incorrect numbers for the MHA information we list on our current [Post-9/11 GI Bill rates](https://www.va.gov/education/benefit-rates/post-9-11-gi-bill-rates/) and [Fry Scholarship rates](https://www.va.gov/education/benefit-rates/fry-scholarship-rates/) pages. We need to update this with the correct info in the accordions in the monthly housing allowance section of the page.

National average for MHA: $2,109
Half the national average for MHA: $1,054.50

## Tasks
- [x] Update drupal pages
- [x] Review
- [x] Publish

## Acceptance Criteria
- [ ] Pages are live with correct info

**Comment by RLHecht** [comment]
@laurwill This is ready for you to review and publish

**Comment by laurwill** [comment]
Thanks @RLHecht , I reviewed and published these — moving to validate.
