### ISSUE TITLE
CF: Post Test Content Updates

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#6346]
Update content after usability testing
Distribute to UX Team
Review / Update, if necessary

**Comment by amyknox** [comment]
[Content excel repository in Sharepoint](https://boozallen.sharepoint.com/:x:/r/teams/benefitsintegrationplatform/ClaimsModernization/_layouts/15/Doc.aspx?sourcedoc=%7B0CBDDB53-9D68-455E-8A6A-0B4BB4BF62A3%7D&file=Caution%20Flag%20Copy%20for%20Review%20v.2.0.xlsx&action=default&mobileredirect=true)

**Comment by amyknox** [comment]
the fine print...
“Before enrolling in a program at this institution, VA recommends that potential students consider these cautionary warnings. Caution flags indicate that VA or other federal agencies like the Department of Defense (DoD) or Department of Education (ED) have applied increased regulatory or legal scrutiny to this program.”

**Comment by amyknox** [comment]
New heading: Alerts from VA and other federal agencies
New jumplink: View details below
