### ISSUE TITLE
[Other - Accessibility] Excessive motion in smooth scrolling between pages. (00.00.1)

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#63470]
#### VFS team name
Public Websites

#### VFS product name
Income Limits

#### Point of Contact/Reviewers
Brian DeConinck - @briandeconinck - Accessibility

*For more information on how to interpret this ticket, please refer to the [Anatomy of a Staging Review issue ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Anatomy-of-a-Staging-Review-Issue-ticket.2060320997.html) guidance on Platform Website.

---

### Platform Issue
No VA.gov Experience Standard for the issue found.

### Issue Details
On each transition between pages, the browser smooth-scrolls to the top of the page. This motion can be disorienting and uncomfortable to users with vestibular disorders, especially if they also use screen magnifiers or have their browsers at a high zoom. (It is a wild ride at 400% zoom!)

Note that this has [already been logged](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14613) by @laflannery and looks like it's going to be resolved soon!

### Link, screenshot or steps to recreate
Video demo at 400% zoom: 

https://github.com/department-of-veterans-affairs/va.gov-team/assets/6844775/4b57373c-1d65-4c73-85af-638faac063e5

### VA.gov Experience Standard
[Category Number 00, Issue Number 00](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

### Platform Recommendation
Best recommendation here is that the viewport moves to the H1 (matching keyboard focus) without the smooth scroll effect.

---

### VFS Guidance

- Close the ticket when the issue has been resolved or validated by your Product Owner
- If your team has additional questions or needs Platform help validating the issue, please comment on the ticket
- Some feedback provided may be out of scope for your iteration of the product, however, Platform's OCTO leadership has stated that all identified issues need to be documented and it is still your responsibility to resolve the issue.
- If you do not believe that this Staging Review issue ticket is the responsibility of your team, comment below providing an explanation and who you believe is responsible. Please tag the Point of Contact/Reviewers. Governance team will research and will follow up.

**Comment by wesrowe** [comment]
Fixed and shipped by [PW ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14613). Closing.
