### ISSUE TITLE
correlate ICNs from tests to understand login activity

### ISSUE THREAD

**Issue by djmunoz1** [department-of-veterans-affairs/va.gov-team#63471]
As an admin I want to see data from the campaigns that have been sent so that I can understand the login activity of message recipients.

ACCEPTANCE:
- includes data for the following tests: Reactivation Test C, Reactivation Test D, Organic Test A
- references Datadog as source (time boxed to one week)
- alternative: use Splunk to pull data for all tests though it excludes mobile

DEF of DONE:
- data for each test shared via spreadsheet with PM (dawn.munoz@va.gov)

**Comment by sdickson-gt** [comment]
Update: Have worked out an approach in a lab env which looks viable.  Couple technical unknowns and potential gotcha still: 1) VA.gov DD is more complex and there must be some log pre-processing occurring that I'm not seeing, so I've not accounted for that in lab env.  2) It's not yet clear how to do a distinct query of users for a time range - best I've found so far is that given a time range, DD will run distinct on sub-time ranges e.g. If I query a month, I can get distinct authns for each day.  If I query a year, I can get distinct by month.
Will start looking into testing in VA.gov DD and with a non-prod env.

**Comment by sdickson-gt** [comment]
DataDog configuration Notes: https://docs.google.com/document/d/17WfM9QyRgprCQgLdUkaAO10e-XXfcoQ2cYtYX5WCiFk/edit

**Comment by sdickson-gt** [comment]
@djmunoz1 The dashboard is now reporting daily distinct user counts per CSP for the test groups.  Current day totals are updated hourly.  If you have access to Domo, have a look. Or I can do a screenshare.  https://va-gov.domo.com/page/923236635
Let me know if you would like to take add additional metrics or take in a different direction?  Or if you still want to get total distinct user transactions since the tests went live - only know how to get that from SSOe data.

**Comment by sdickson-gt** [comment]
Noticed that the date is showing a prior day for USiP counts.  Also, there's a bug in the processing of the MPI data.  The total for Oragnic Test A in July should by 75,000 exactly, and 50,000 for Reactivation Test D.  Will work on fixing those.

**Comment by sdickson-gt** [comment]
The data doesn't exist in DataDog currently to track the test user authns with SiS, specifically we need icn attribute added to the SiS callback logs.  Once added, we would need to add some additional processors to identify and tag logs and get queryable metrics. So reporting would be point forward once this is in place.  Will ping core team to get icn added.

**Comment by sdickson-gt** [comment]
FYI, we got another dataset from MPI and ran the import on it.  The _LastUsed_ data field from MPI is not looking like a good source of data...number of anomalies found.  Will focus on getting the numbers we discussed from start of test dates via SSOe splunk.

**Comment by sdickson-gt** [comment]
@djmunoz1 Status update: the SSOe splunk query and flow are configured. Just need Brent from IAM team to import the test group lookup CSV files into Splunk.  He's generally pretty responsive, so hopefully will have visualizations ready for tomorrow demo.   See the appendix for sample of what I was thinking of reporting for each test group. https://va-gov.domo.com/page/923236635
Once again, the ability to have it (and all the SSOe-based reports) updated automatically on a regular schedule is limited by finding a place to host Domo Workbench that's not affected by restarts.
