### ISSUE TITLE
Add RSpec Tests for Non-Super Users

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#63473]
### Description
As part of improving our application's test coverage and ensuring proper functionality, we need to create RSpec tests that specifically target non-super users. These tests will help us verify that non-super users have the appropriate access and permissions within the application.

### Acceptance Criteria
- [ ]  Create RSpec tests to cover scenarios related to non-super users.
- [x]  Test scenarios should include but are not limited to:
- [ ] Verifying access to restricted areas.
- [ ] Testing permissions for actions that non-super users are allowed to perform.
- [ ] Ensuring non-super users cannot perform super-user-exclusive actions.
- [x]  Tests should be well-organized, follow best practices, and have meaningful descriptions.
- [ ]  Test both positive and negative scenarios to validate behavior under different conditions.

### Steps to Implement
1. Review the application codebase to identify areas related to non-super user permissions and actions.
2. Create new RSpec test files or add tests to existing ones based on the identified areas.
3. Implement the necessary test scenarios using RSpec matchers and appropriate test data.
4. Ensure tests accurately reflect the expected behavior of non-super users.
5. Run the test suite locally to verify new tests and ensure they pass.
6. Commit the changes to a new branch in your fork of the repository.
7. Open a pull request targeting the main branch of the repository.
8. Address any code review feedback and make necessary adjustments.
9. Once the pull request is approved, merge it into the main branch.
10. Additional Information
11. If you're new to creating RSpec tests or need guidance, feel free to ask for help from colleagues or refer to our testing documentation.
12. Make sure to follow the project's coding guidelines and testing standards while writing the new tests.
13. Consider using FactoryBot or similar libraries to generate test data efficiently.

**Comment by laineymajor** [comment]
Will require additional work. Carrying over to next sprint.

**Comment by laineymajor** [comment]
Started this work on Friday.
Adding the rspec policies. [will circle back after debugging of json data]

**Comment by laineymajor** [comment]
Rachal to circle back to this soon

**Comment by laineymajor** [comment]
Finishing work on oauth, then circling back to this.

**Comment by laineymajor** [comment]
This should be done today per @RachalCassity

**Comment by laineymajor** [comment]
begun digging through this, not certain of how we originally intended to build out the role spec.

**Comment by RachalCassity** [comment]
Gia and I are meeting after stand up on 9/12 to go over our meeting yesterday. :)

**Comment by laineymajor** [comment]
Carryover work to next sprint.

**Comment by RachalCassity** [comment]
(PR)[https://github.com/department-of-veterans-affairs/platform-codeowners/pull/114] has been merged. Closing today after stand up :)

**Comment by laineymajor** [comment]
Done
