### ISSUE TITLE
create journey map/storyboard for MHV coordinators

### ISSUE THREAD

**Issue by djmunoz1** [department-of-veterans-affairs/va.gov-team#63476]
# Use case

As a MHV coordinator potentially volunteering as a proofing agent for the IPP pilot, I am aware of what the pilot IPP flow looks like so that I can make a better decision on whether to volunteer or not.

# Background

We need peeps to act as proofing agents for our IPP pilot. Given that identity toolkit is being considered as a tool that proofing agents will use, MHV coordinators may be likely volunteers as we have heard that they often have the role of Identity Verifiers.

There is a meeting with Susan Haidary (sp?) being scheduled where our team will present our IPP pilot approach and field questions.

# Acceptance Criteria
- [x] Review of discovery material on [MHV premium in person proofing](https://drive.google.com/drive/folders/1r0Fl4ibj12zQXnvmJ5tndpEPZxGwm-Hr) There is a link to the process at the end of that document. Must be in VA Citrix.
- [x] Visual artifact (deck, storyboard / strip etc) describing our IPP pilot from the perspective of the proofing agent
- [x] Call out:
    - [x] Why there's a different process
    - [x] What would be different from their current process

**Comment by djmunoz1** [comment]
porta, pls add criteria to this ticket (precedes setting the meeting with Susan H for MHV coordinator support

**Comment by porta-antiporta** [comment]
@djmunoz1 updated description with draft criteria.

**Comment by porta-antiporta** [comment]
@skirkman16 am seeing all the AC checked. Good to close?

**Comment by skirkman16** [comment]
Verifier flow [here](https://app.mural.co/t/innovationboards1199/m/innovationboards1199/1692994115776/5b6e2c85cd304e3d011dbddf2eec0bfe158f4ca8?sender=u99cd1ac4f5c240d8dffd4204)
Need to validate with MHV
