### ISSUE TITLE
Design | Direct Deposit | Update to radio buttons for accessibility concerns

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#63495]
## Background 

Dropdown boxes aren't as accessible as radio buttons for screen reader users. We've used a dropdown in the profile Direct Deposit screen and should shift that to a radio button. 

### Original note:

<img width="432" alt="Screen Shot 2021-02-05 at 1 22 58 PM" src="https://user-images.githubusercontent.com/14154792/107073441-61a6e080-67b5-11eb-9d51-6b10e9b48cb4.png">

Would it be possible to use radio buttons instead of a dropdown here? For sighted users, options will be more immediate. For screen reader users, additional context is naturally provided e.g. "Savings, 1 of 2, selected" without the "check mark" empty selection.

<img width="1431" alt="Screen Shot 2021-02-05 at 1 26 22 PM" src="https://user-images.githubusercontent.com/14154792/107073749-bea29680-67b5-11eb-857f-82558b8906a1.png">

Technically this still meets compliance standards, so it's not of concern if it's too late to fix. The UX benefits for sighted and screen reader users would be really nice though!

---

A fun video on this topic 🤓 
[F*** dropdowns - SXSW Keynote](https://www.fuckdropdowns.com/)

_Originally posted by @joshkimux in https://github.com/department-of-veterans-affairs/va.gov-team/issues/19495#issuecomment-774208560_

## Tasks 
- [x] create new mocks 

## Acceptance Criteria
- [ ] Ready for FE

**Comment by andaleliz** [comment]
@mtcA6 moving to validate - all the mocks have been updated
