### ISSUE TITLE
Analytics Implementation or QA Support for 21-4142 Form

### ISSUE THREAD

**Issue by tbaker1026** [department-of-veterans-affairs/va.gov-team#63497]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

</div>
</details>

## Description
- Do you know where/how we can track views of each page of the form?
- Which report would be best to use to pull average time spent on each page of the form?
- Is there a way to update the DOMO dash to include this information?
### Required
- **Is this request for **Google Analytics implementation** or **QA**?**

     - [ ] Google Analytics implementation
     - [x] QA

- **Who is this request for?**

    - [Insert team name(s), for individual's names please use the `/support` tracker on the #vfs-platform-support channel and link this ticket.]
    - Tricia Baker - Veteran Facing Forms
    
    
- **Provide the link(s) for Google Analytics implementation or QA**
  
    - [Insert link(s)](https://www.va.gov/supporting-forms-for-claims/release-information-to-va-form-21-4142/introduction)
    - Was looking at this report in Analytics but not seeing the drill down of the page views 
    - https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/_u.date00=20220801&_u.date01=20220810&explorer-table.filter=21-4142&explorer-table.plotKeys=%5B%5D&explorer-table.rowStart=0&explorer-table.rowCount=50/
    
- **When is the launch date?**
    - Launched on 7/17/2023

- **What interactions need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked_
    
    - [If this is a funnel, insert each step's URL - pages visible depending on the applicant's answers should be marked accordingly]
    
    - [Insert other interactions - please review the [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) and [GA Data Dictionary](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Google-Analytics-Data-Dictionary.1810464912.html)  to make sure these interactions aren't already tracked]

### Optional
- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - [Insert test user]

- **Any additional comments**

    - [Insert comments]

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by michelle-dooley** [comment]
Thanks @tbaker1026, we will review and get back to you with timing.

**Comment by tbaker1026** [comment]
@michelle-dooley More information - if I can see the pages I can put something together too  
  
How many users hit the Intro page or more broadly a Views vs. Entries ratio

*   Referring page (particularly interested in this to make the argument that Find a form is the main entry point and that we should be redesigning it)
*   Abandonment % and where users are exiting
*   How many make it to the confirmation page or more broadly Views vs. Completions percentage
*   \# of notifications sent (might need to talk to Beverly's team about how to get at this; really would like this to demonstrate that Veterans are getting better communication from the VA if they submit online)
*   **User type**: Particularly for these forms it would be interesting to know the breakdown of who is filling them out. So Veteran vs. Non-Veteran.

**Comment by michelle-dooley** [comment]
@tbaker1026 - the [forms dashboard](https://va-gov.domo.com/page/447193050) work we are doing for this form should give you the first 3. 

For notifications is there a campaign you are wanting to track?  What kind of notifications are you looking for, are they specific to this form?

Not sure if we will know Veteran vs. Non-Veteran. Will need to look into that.

**Comment by tbaker1026** [comment]
@michelle-dooley I will work with Beverly's team on notifications - wanted to leave it here to see if you tracked notifications via GA.    
The only thing I can think of for Veteran vs Non Veteran is if they logged in or not -

**Comment by michelle-dooley** [comment]
@tbaker1026 - you can determine if they are logged in or not but adding the LOA filter to the [dashboard top drow down](https://va-gov.domo.com/page/447193050), if =true they are logged in, if =false they are not logged in. We cannot determine for the not logged if they are the veteran or not. Other than that you should have everything else you need in the dashboard so I am going to close this ticket.

**Comment by michelle-dooley** [comment]
@tbaker1026 click the + sign next to 'Filter Views' and you will see all the different filter options you can add, select LOA and it will appear in the top filter bar.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcVdYIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--26d0f4eb955632674b2781d78996a8b8d005f5e9/image.png)

**Comment by tbaker1026** [comment]
@michelle-dooley got it thanks
