### ISSUE TITLE
Launch new standards

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#63508]
## User Story
As a Governance team member, I want to launch the revised VA.gov Experience Standards for VFS teams so that we can begin using the new process with revised standards at Staging Review.

Assignee: @erinrwhite @allison0034 
Peer Reviewer: @rferguson13 

## Description
Governance team has done all of the prep work necessary for launching the revised VA.gov Experience Standards and changes to our Staging Review process. Now that we have completed our research and implemented additional changes based off our research findings, we are finally ready to launch our new process for VFS teams.

The purpose of this ticket is to publish all VFS-facing guidance on Platform Website, retire all language in operational docs about the pilot/research, retired older versions of the DraftingTemplate, document a change log post for the Collaboration Cycle Change history page, write/publish a change announcement for the #vfs-change-announcements channel, communicate in the weekly Monday Design meeting (confirm availability with Naomi).

**Update from PO 4/5:** @humancompanion-usds shared that he would like the revised VA.gov Experience Standards to live on the VA Design System website, among the other standards. We will need to work with Matt in order to get the page on VADS published. There should still be a page for the VA.gov Experience Standards on Platform Website, however it should direct folks to the VADS page.

## Impacted Artifacts

VFS-facing
- [Anatomy of a SR issue ticket](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2923757569/63506+-+Anatomy+of+a+Staging+Review+Issue+ticket)
- [VA.gov Experience Standards](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2927722529/63506+-+VA.gov+Experience+Standards) on Platform website
- [Experience Standards page on Design System website](https://design.va.gov/about/experience-standards/)
- [Change history](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/change-history)

Internal/operational
- [Staging Review - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808348923/Staging+Review+-+Scheduling)
- [Staging Review - During the meeting](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808447039/Staging+Review+-+During+the+meeting)
- [Staging Review - After the Meeting](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808447023/Staging+Review+-+After+the+Meeting)
- [Drafting Template Outline](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2385248274/DraftingTemplate+Outline)
- [Staging review findings issue template](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2548957608/Staging+Review+findings+-+issue+template)
- [How to generate staging review tickets](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808217924/How+to+generate+Staging+Review+issue+tickets)
- [Drafting Template](https://docs.google.com/spreadsheets/d/1djyvPR9XrJcHXFFBNVQccMLk8DDPgmLZm4T1IM6LAxU/edit#gid=1732371940)
- [Drafting Template DST](https://docs.google.com/spreadsheets/d/1rkORbwvrsKP4fBxxamuP_6plYOGRKXCaqBw3Qd55pTU/edit#gid=1732371940)
- [Experience Standards](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2001862791/VA.gov+Experience+Standards#Updating-Experience-Standards-and-descriptive-tags)

### VFS-facing documentation
- [x] Work with Matt to get the VA.gov Experience Standards page published on VA Design System
   - Does Matt already have a place in mind where the ES page will live? Or will we need to determine that?
   - We had drafted an [updated ES page for the Platform website](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2927722529/63506+-+VA.gov+Experience+Standards) as part of #63506 
   - [Experience Standards page on Design System website](https://design.va.gov/about/experience-standards/)
- [x] Draft an updated [VA.gov Experience Standards page for Platform Website](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/va-gov-experience-standards) that links out to the VADS page. - @allison0034 
- [x] Publish the changes to the [Anatomy of a SR page](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket) @allison0034 
- [x] [Draft a change history post](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3099590657/63508+Change+history+and+slack+post) for the Platform Website change history page. This can get lengthy, so focus on 2 things: 1) the revised VA.gov Experience Standards, and 2) the changes to the Staging Review process @erinrwhite 

### Slack post
- [x] [Draft a change announcement for #vfs-change-announcements](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3099590657/63508+Change+history+and+slack+post) @erinrwhite 

### Operational docs
- [x] Remove all language re: the pilot from SR operational docs
  - [Staging Review - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808348923/Staging+Review+-+Scheduling)
  - [Staging Review - During the meeting](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808447039/Staging+Review+-+During+the+meeting)
  - [Staging Review - After the Meeting](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808447023/Staging+Review+-+After+the+Meeting)
  - [Drafting Template](https://docs.google.com/spreadsheets/d/1djyvPR9XrJcHXFFBNVQccMLk8DDPgmLZm4T1IM6LAxU/edit#gid=1732371940)
  - [Drafting Template DST](https://docs.google.com/spreadsheets/d/1rkORbwvrsKP4fBxxamuP_6plYOGRKXCaqBw3Qd55pTU/edit#gid=1732371940)
- [x] Remove all guidance for DraftingTemplate 1.0
  - [Drafting Template Outline](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2385248274/DraftingTemplate+Outline)
  - [Staging review findings issue template](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2548957608/Staging+Review+findings+-+issue+template)
  - [How to generate staging review tickets](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808217924/How+to+generate+Staging+Review+issue+tickets)
- [x] Archive DraftingTemplate 1.0 in the SR folder on Drive

### Publish and notify
- [x] Once draft pages are approved/peer reviewed and VA.gov Exp Stds page is live on VADS, publish all pages to Platform Website
- [x] Once all pages are live on VADS and PW, post change announcement to #vfs-change-announcements. X share to #design,  #platform-collaboration-cycle and #vfs-all teams
- [x] Notify Shira to announce in ToT and notify Naomi to announce in the Monday design meeting
- Once the ES are published on Design System:
  - [x] [Update the Experience Standards source of truth and sheets in the Drafting Templates](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2001862791/VA.gov+Experience+Standards#Updating-Experience-Standards-and-descriptive-tags) with the links to each individual Experience Standard. 
  - [x] In the GitHub upload sheet of the Drafting Templates, update the code for the body of the staging review tickets to hyperlink the relevant experience standard back to its page on the Design System.

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] Governance team has officially launched the revised VA.gov Experience Standards and the revised Staging Review process
- [x] VFS teams have been made aware of the new changes to the VA.gov Experience Standards and the revised Staging Review process

## Team Notification
- [x] ~~Slack post on #platform-governance-team~~ x share change announcement on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by erinrwhite** [comment]
@shiragoodman Drafting up documentation for OCTO #63014

Will this ticket be an epic/initiative containing other launch-related tickets, or will it have its own distinct to-dos? Want to make sure we're capturing everything.

**Comment by shiragoodman** [comment]
This will be all the steps we need to take to publish updated Platform Website pages, roll out changes to our operational processes, announce changes to VFS teams via Slack, etc. It's basically the ticket to ensure all our ducks are in a row before launch.

**Comment by shiragoodman** [comment]
@allison0034 @erinrwhite I spoke with @humancompanion-usds this morning re: getting the new page set up on the design system. Please connect with him ASAP in order to get this work going. Thank you!

**Comment by erinrwhite** [comment]
Thanks @shiragoodman, started a [slack thread](https://dsva.slack.com/archives/GNF5GSD9N/p1712860598008179) tagging Matt and doing some preliminary divvying up of these ticket tasks.

**Comment by shiragoodman** [comment]
@erinrwhite I see you reorganized the ticket! all good. Whatever works for you :) I just wanted to share that I may have forgotten to mention that we also need to remove the pilot messaging from the DraftingTemplate. Thx!

**Comment by erinrwhite** [comment]
@shiragoodman Ah, thank you! I updated the DT to change the italic text at the top of the tickets - will add that here. 

*And* I also just realized that once the ES are published we should update our ES spreadsheets and Drafting Templates with the links to each Experience Stand - so that we can link to the standard from the generated SR tickets. That seems like maybe a separate ticket for next sprint? But I can also fold that one in here in the publish and notify section if you think we should grab it during this sprint.

**Comment by shiragoodman** [comment]
ahh good point! I had completely forgotten about that. 

I'd prefer if we got that work done within this ticket. Would you be open to updating the DraftingTemplate yourself? I can check the code when I'm back mid-next week and make changes if needed. Could you please add that to the scope of this ticket?

Thank you, Erin!!! @erinrwhite

**Comment by erinrwhite** [comment]
@shiragoodman will do. Thank you!

**Comment by erinrwhite** [comment]
[Experience Standards page on Design System website](https://design.va.gov/about/experience-standards/) is up! Thank you @humancompanion-usds! 👍🏻

**Comment by erinrwhite** [comment]
Drafting templates and Experience Standards source of truth now have links to the specific experience standards and categories on the Design System page. These links are in the reference sheets `VA.govES` and `DescriptiveTags` and should also appear in the body of the generated GitHub tickets.

- [Drafting Template](https://docs.google.com/spreadsheets/d/1rkORbwvrsKP4fBxxamuP_6plYOGRKXCaqBw3Qd55pTU/edit#gid=727681601)
- [Drafting Template - DST](https://docs.google.com/spreadsheets/d/1djyvPR9XrJcHXFFBNVQccMLk8DDPgmLZm4T1IM6LAxU/edit#gid=727681601)
- [Experience Standards source of truth](https://docs.google.com/spreadsheets/d/1y9hjr9WYqDrTJEAnhDKCAgf4izQ8sOLg511tinAE_jU/edit#gid=500057009)

**Comment by erinrwhite** [comment]
@allison0034 I'm out Monday! Tossing this one in your court if you have some time to check behind me on the Drafting Template updates, take a swing at changes to the Platform site or start on the change announcements.

**Comment by allison0034** [comment]
@erinrwhite I was out Monday as well. What do you need me to do?

**Comment by erinrwhite** [comment]
@allison0034 thank you for scheduling time for us to chat about this tomorrow!

**Comment by erinrwhite** [comment]
@rferguson13 half of this work is ready for your review! Please see all of the checked-off boxes in the Tasks list - mostly operational documentation. @allison0034 and I are working on updates to Platform website and change announcement text next. Thank you!

**Comment by rferguson13** [comment]
@erinrwhite - What has been provided so far looks good!

**Comment by shiragoodman** [comment]
agreed! It's looking good! Excited to roll this out next week!

**Comment by allison0034** [comment]
@rferguson13 [draft](https://vfs.atlassian.net/wiki/spaces/PWD/pages/3099590744/VA.gov+experience+standards) of updated experience standards page is ready for your review.

**Comment by allison0034** [comment]
Moved changes to the Anatomy of a SR page, waiting for Platform website to publish.

**Comment by rferguson13** [comment]
@allison0034 Looks good!

**Comment by erinrwhite** [comment]
Draft [Change history post](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3099590657/63508+Change+history) ready for review @rferguson13 and @shiragoodman too! I tried to stick to the stuff that VFS teams will care most about.

**Comment by rferguson13** [comment]
@erinrwhite I have nothing to add besides Shira's comments. I agree that the main paragraph should be broken up in some way, either with line breaks or bullets.

**Comment by allison0034** [comment]
I moved the draft to be published.

**Comment by allison0034** [comment]
Confirmed pages published to PW

**Comment by erinrwhite** [comment]
@allison0034 @rferguson13 @shiragoodman Draft [change announcement posts](https://vfs.atlassian.net/wiki/spaces/PPST/pages/3099590657/63508+Change+history+and+slack+post), including Slack posts are ready for your review!

**Comment by shiragoodman** [comment]
@erinrwhite revised Change announcement looks good! you have my approval 👍

**Comment by erinrwhite** [comment]
@shiragoodman @allison0034 @rferguson13 update to the [change history](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/change-history) page is queued up for publishing this afternoon!

**Comment by erinrwhite** [comment]
@rferguson13 @allison0034  we're all done!

- [change history](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/change-history) posted
- announcements made in Slack
- will be announced at Monday's design meeting 4/29

We good to close? 🎉

**Comment by rferguson13** [comment]
@erinrwhite - Close it!

**Comment by erinrwhite** [comment]
Woo hoo! Closing @rferguson13 @allison0034
