### ISSUE TITLE
Vets-api terminal access for Connor Fewin

### ISSUE THREAD

**Issue by ConnorJeff** [department-of-veterans-affairs/va.gov-team#63503]
### Your Name

Connor Fewin

### Your GitHub handle (terminal access is managed through GitHub)

@Connorjeff

### Team, Role, and Company of the target individual

MBMS Self Service Software Developer at Booz Allen

### Product Manager (PM) name and email

Cat Hughes hughes_catherine@bah.com

### Product Owner (PO) name and email

Matt Self matthewself.dsva@gmail.com

### COR Name (leave "None" if you listed an AWS user name above)

None

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

None

### Please confirm if you are on the VFS Team Roster or Platform Team Roster

- [ ] [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Please confirm E-QIP Transmittal/Adjudication. This could be a screenshot of your Transmittal/Adjudication email, a link to another request where you've submitted this proof (i.e. AWS/SOCKS), etc.

- [X] I have attached proof that I have either transmitted my E-QIP survey or previously received a favorable decision (by including in "Additional Notes" section below)

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [ ] sandbox
- [ ] production (if requesting, justify prod access in 'Additional Notes' section)

### Additional Notes

![Screenshot 2023-08-10 at 4 11 49 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/122034971/7132d5bd-28fd-45d3-b178-28ec2195d5ca)

### Additional resources for Support Engineer

- [ ] For users on a VFS team but not in the VFS Team Roster, they must start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] Instructions for handling requests [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access) - Support Only

**Comment by bdech** [comment]
Found in VFS Roster

**Comment by bdech** [comment]
@ConnorJeff You’ve been granted access to the `dev` and `staging` environments.

Here's some additional documentation for the [Vets API on EKS](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-TerminalAccess)
