### ISSUE TITLE
[CHIP] Support the Push out a Check-in SMS Message to a Veteran 45-minutes Before an In-person Appointment

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#63529]
## NOTES
This is a placeholder ticket for the CIE team's CHIP work to support this 45-minute reminder; here is the [VeText team's work ticket](https://app.zenhub.com/workspaces/vetext-development-641b2bcbee60f0047f164130/issues/gh/department-of-veterans-affairs/vetext/1248) for the VeText team

This is the [slack thread](https://dsva.slack.com/archives/C02G6AB3ZRS/p1695738433612699) for the discussion about what Rob needs to support his work in VeText.
   - Add a new param "setStarted" to the existing endpoint; if false (default) then we will NOT set the eCheckInStarted in Vista, if true then we will set the eCheckInStarted in Vista
   - update response to include the URL by itself in the attributes. i.e. 
```
{
  "data": {
    "attributes": {
      "message": "Check in for your VA appointment at https://sandbox.va.gov/c/Gn99gsT",
      "uuid": "69e38271-624d-463a-a8cf-0dca9510967c",
      "url": "https://sandbox.va.gov/c/Gn99gsT"
    },
    "id": "69e38271-624d-463a-a8cf-0dca9510967c",
    "type": "InitiateCheckinResponse"
    }
}
```

There is a meeting scheduled for 10/12 between CIE & VeText to discuss the CHIP work

## Considerations for the VeText Team
As the VA, in order to encourage more Veterans to use the feature to check-in for an in-person appointment using their smartphone, we would like to push out to each Veteran, who has SMS notifications enabled and if my insurance review is up-to-date, an SMS message that contains the check-in message and check-in link 45 minutes before their in-person appointment for which check-in is enabled.

**NOTE: Scenarios we need to decide on whether we should cover them**
- What about the scenario where Veterans start to expect these reminders and their insurance review is NOT up-to-date, do we want to send them a text?
- Do we want to delay pre-check-in links being sent out on the day a check-in message is being pushed

See [slack thread](https://dsva.slack.com/archives/C022AC2STBM/p1695130206174559?thread_ts=1695048379.114739&cid=C022AC2STBM)

## Tasks
-  Add a new param "setStarted" to the existing endpoint; if false (default) then we will NOT set the eCheckInStarted in Vista, if true then we will set the eCheckInStarted in Vista
- Coordinate with Rob Durkin on testing in Staging

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by brianseek** [comment]
closing ticket, work is in pre-release 3.4.0 https://github.com/department-of-veterans-affairs/chip/releases/tag/v3.4.0
