### ISSUE TITLE
Qualitative Data Request - Appointments Team

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#63535]
### Data Type Requested

User Surveys

### Date Range Start

08-05-2023

### Date Range End

08-13-2023

### Product Name(s)

Appointments Team (formerly VAOS)

### Product Description

Hello. I am requesting August 5th-13th 2023 Medallia feedback for Appointments. If you could send it to [peter.russo1@va.gov](mailto:peter.russo1@va.gov). If you have any questions, please reach out. Thanks!

### Survey URL(s), key term(s), case category or type

va.gov/health-care/schedule-view-va-appointments/appointments/

### File Delivery Format

All in one file, on one tab

### VA Email Address(es)

peter.russo1@va.gov

### Add Assignee and Labels

If not already done so, please ensure @ianMcCullough-ob is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by outerpress** [comment]
I received it, thank you! Question, where do Veterans get asked the A11Y feedback questions? I know where the VFS questionnaire is triggered but not that one.

**Comment by newworld2616** [comment]
The accessibility (A11Y) feedback question for the [VA.gov] (http://va.gov/) website can usually be found on the website's contact or feedback page. You might look for a section or link related to accessibility concerns or disabilities, as that's where they often provide information on how to report any accessibility issues on the website. Or try using the website's search function to search for "accessibility feedback". Hope this answers your questions.

**Comment by newworld2616** [comment]
Data request sent and received!

**Comment by newworld2616** [comment]
The A11y questionnaire is randomly triggered to 5% of va.gov users if they stay on any page longer than 30 seconds.
