### ISSUE TITLE
Update the URL on the widget on the static landing page (Public Website)

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#63539]
## Description
We will need to update the URL on the Public Websites static landing page widget to support the MHV on VA.gov initiative. 

Current UI: 
<img width="589" alt="Screenshot 2023-08-11 at 11 30 07 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/90797205/7c0748cd-7150-4e6f-baea-fe1116507506">

---

## Acceptance Criteria
Background: the `va_online_scheduling_breadcrumb_url_update` and `va_online_scheduling_static_landing_page` toggles are turned on

- [ ] Given the user (not a Cerner user) is on the static landing page (Public Websites) 
When the user clicks on `Go to your VA appointments` button
Then the user will be directed to the Appointments landing page and the new URL will be www.va.gov/my-health/appointments

- [x] Given the user (Cerner user) is on the static landing page (Public Websites) 
When the user clicks on `Go to appointments on VA.gov` link
Then the user will be directed to the Appointments landing page and the new URL will be www.va.gov/my-health/appointments

### Design Assets
N/A

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by ldelacosta** [comment]
PR will need to be reviewed by the Public Websites team.

**Comment by ldelacosta** [comment]
@young1205 - please have the UX team validate this ticket when it's ready cc: @JRRoof @outerpress

**Comment by ldelacosta** [comment]
The changes have been validated for john.morrison@id.me in staging. Notified the UX team to review the changes. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdmcyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--243984179264ca81994ec2f78f4114a96dc7ae49/Screenshot%202023-08-24%20at%201.08.13%20PM.png)

**Comment by Cieramaddox** [comment]
@ldelacosta Everything here is validated. Looks good from the UX side.

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket. cc: @JRRoof
