### ISSUE TITLE
Error when following "Debugging unit tests" DEPO instructions

### ISSUE THREAD

**Issue by radavis** [department-of-veterans-affairs/va.gov-team#63543]
### Description

When following the instructions within [Debugging unit tests](https://depo-platform-documentation.scrollhelp.site/developer-docs/debugging-unit-tests), I get the following error.

```
✖ ERROR: --opts: configuring Mocha via 'mocha.opts' is DEPRECATED and no longer supported.
          Please use a configuration file instead.
```

### Relevant URLs

- https://depo-platform-documentation.scrollhelp.site/developer-docs/debugging-unit-tests

### Which type of team are you on? (Platform team, VFS team, or Leadership)

VFS

### Solution that worked for me

Changing from `--opts src/platform/testing/unit/mocha.opts` to `--config config/mocha.json` (**Note**: only tried this with VS Code).

**Comment by vbellissimo** [comment]
Hi @radavis , thank you for your feedback. Our team will take a look for next steps.

**Comment by vbellissimo** [comment]
Slack thread with support: https://dsva.slack.com/archives/CBU0KDSB1/p1691774207933449

**Comment by laucon** [comment]
I fixed the code. It should be deployed at 3:30pm today. So hopefully it should work now.

**Comment by radavis** [comment]
Took a look at the updates. The instructions for running the debugger from the command line have been updated and look good. The instructions for debugging via VSCode should be updated as well.

```
  {
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Mocha Tests",
            "env": {"BABEL_ENV": "test"},
            "runtimeExecutable": "${workspaceFolder}/node_modules/.bin/mocha",
            "runtimeArgs": [
                "--inspect",
                "--config",
                "${workspaceFolder}/config/mocha.json",
                "--recursive",
                "${workspaceFolder}/{test,src}/**/*.unit.spec.js?(x)",
                "${workspaceFolder}/src/platform/testing/unit/helper.js"
            ],
            "port": 9229
        }
    ]
  }
```

**Comment by vbellissimo** [comment]
@radavis Hi Randy, just confirming we're closing this ticket now. If you need anything else let us know. Thanks for your help.
