### ISSUE TITLE
Sidekiq Admin UI access for [Rockwell Rice]

### ISSUE THREAD

**Issue by rockwellwindsor-va** [department-of-veterans-affairs/va.gov-team#63542]
### Your Name

Rockwell Rice

### Your GitHub handle (Sidekiq Admin UI access is managed through GitHub)

@rockwellwindsor-va

### Your dsvagovcloud AWS user name (if applicable)

Rockwell.Rice

### Team, Role, and Company of the target individual

Dash, Software Engineer II, Oddball

### COR Name

Cecila Lee

### Please confirm if you are on the VFS Team Roster or Platform Team Roster

- [X] [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Sidekiq UI Access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### If PRODUCTION ACCESS is required, confirm/complete ONE of the following

- [X] I have an AWS Username and it is listed in [here](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf)
- [X] I currently have access to vets-api Production Terminal via ArgoCD
- [X] I've attached a screenshot of my E-QIP Transmittal Notice E-mail (Drag or Copy/Paste in Additional Notes Section below)

### Additional Notes

As part of team Dash I monitor and at times need to rerun sidekiq jobs due to failed claims for various reasons, or cancel them if there is an issue.

Dragging the screenshot of mye-QIP transmittal notice image into this editor to attach it kept failing,  it did attached in my previous [AWS Access ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60180), or you can view that image of the e-QIP at this link. (If I get the image to upload I will remove the link)
[https://user-images.githubusercontent.com/129893414/244199539-7ddc2634-6c58-4130-a68e-724d194af2f0.png](eQuip)

* One thing I would like to note in case it helps, the link shared from my team returned this message `You don't have access to team 7462512`. So I guess I need to make sure that team is what I get added to (in case there are options).  Thanks!

**Comment by bdech** [comment]
@rockwellwindsor-va You've been granted access to all environments, with access to Production limited to 6 months, expiring, 02/11/24

**Comment by bdech** [comment]
slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1691773323868729)

**Comment by bdech** [comment]
@rockwellwindsor-va Your Sidekiq UI Production access has expired.

Would you like to request an extension? You have 72 hours to respond, or your 
access will be revoked and you will need to fill out a new request.

**Comment by rockwellwindsor-va** [comment]
@bdech  Yes absolutely still very much need this for my day to day.  How long is the extension for?

**Comment by bdech** [comment]
sounds good. Access is limited to 6 months. Once that 6 month threshold has been passed, we reach out and ask if you would like an extension. Extensions are also 6 months.

**Comment by bdech** [comment]
@LindseySaari @ericboehs can one of you please give us a :thumbsup: to extend their access?

**Comment by bdech** [comment]
@rockwellwindsor-va your Production access has been extended for 6 months,
expiring 08/12/24.

Please set a reminder for yourself to return to this Issue and 
request an extension within 1 week of the expiration date. You'll 
receive 1 reminder with a 48 hour window to respond. Failure to 
respond will result in your access being revoked and will require 
you to fill out a new request.

**Comment by bdech** [comment]
support slack reminder [here](https://dsva.slack.com/archives/C06CY71PCAX/p1707757790319649)

**Comment by lindsay-insco** [comment]
@rockwellwindsor-va Your Production access has expired.

Would you like to request an extension? You have 72 hours to respond, or your
access will be revoked and you will need to fill out a new request

**Comment by lindsay-insco** [comment]
@rockwellwindsor-va your Sidekiq `production` access has been removed. If you need continued access please fill out a new request.
