### ISSUE TITLE
Google Analytics implementation for documentation site homepage

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#6354]
### User Story 

As a documentation site maintainer, I need to see how people building on and in support of VA.gov are using the documentation site homepage MVP, so that I can address issues and iterate on it. 

### Details 
Documentation site homepage will be hosted here: https://department-of-veterans-affairs.github.io/va.gov-team/

URL may change

Per discussion with Jon/Nedie/Bill/Megan, we do not need any custom events tracking, GA's "out of the box" metrics will be a great start.

### Definition of Done 
- [ ] GTM Tag Management has been tested
- [ ] Documentation site homepage metrics are tracked and accessible via a GA dashboard

### Acceptance Criteria
- [ ] Track homepage pageviews, uniques, time spent on site
- [ ] Track clicks to destination URLs

**Comment by nedierecel** [comment]
@meganhkelley Confirming receipt. 

@jonwehausen I can help establish the new GA property and GTM for this story. Thanks.

**Comment by nedierecel** [comment]
Hello @billfienberg - Will this table of contents page have a staging environment also? I created the new Google Analytics property and Google Tag Manager container and have code ready but need to configure settings before sending over. Thanks!

**Comment by billfienberg** [comment]
> Hello @billfienberg - Will this table of contents page have a staging environment also? I created the new Google Analytics property and Google Tag Manager container and have code ready but need to configure settings before sending over. Thanks!

No. We don't currently plan to have different environments.

**Comment by nedierecel** [comment]
@billfienberg Please see the snippet for the ```<head>```:

```
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-T2ZTDXZ');</script>
<!-- End Google Tag Manager -->
```

And an additional script for the ```<body>```:

```<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-T2ZTDXZ"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
```

**Comment by jonwehausen** [comment]
@meganhkelley @billfienberg @nedierecel @joanneesteban 

### Overview of current configuration: 
- In order to capture / identify link clicks, we are leveraging the click class contained within each link. Here is an example: 
![image](https://user-images.githubusercontent.com/48527022/77093144-f9a2ac80-69e0-11ea-9fa0-40d9fbfaf607.png)
- In the case of URLs and/or click labels changing over time, as well as new links being added -- the class naming convention **would need to be maintained at the front of the ```class``` attribute to continue tracking functionality.** 
- The class names we currently are listening for as they relate to @billfienberg's MVP solution: 
   - ```practice-area-link```
   - ```working-with-vsp-link```
   - ```repo-link```
   - ```policy-link```
   - ```product-link```
   - ```tool-link```

### Current Sample Event Fire
- This example is for when the user clicks on any link within the "Practice Area Quick Links" section
- Since this is a brand new implementation - the items you currently see in Category, Action, Label can be tweaked to the level of granularity needed. We recommend keeping the Event Category and Event Label generic and simple
- Within the screenshot below, the syntax here is: 
   - **Event Category**: Interactions 
   - **Event Action**: \<section> - \<click text> - \<click URL>
   - **Event Label**: \<class_name_used> -- see list above
![image](https://user-images.githubusercontent.com/48527022/77094935-92d2c280-69e3-11ea-9887-b0e011cb0d91.png)

**Comment by billfienberg** [comment]
Thanks for the update, @jonwehausen. I have no objection to ensuring that the link type `class`-es are the first thing in the `class` string. That being said, I am curious why that is the case. I naively assumed it was using a CSS selector, and therefore assumed the order of the `class` names didn't matter. Are you able to provide me with a short explanation and/or link to documentation about why the order of the `class` names matters?

**Comment by jonwehausen** [comment]
Hi Bill, 

Great question! It terms of final solutioning -- it doesn't technically matter whether it's at the beginning. Our configuration is currently setup to listen specifically for the click class under "**starts with**" logic but can certainly be generalized to "**contains**" logic. I simply chose the starts with for robustness and compliance with what I was seeing.

**Comment by billfienberg** [comment]
Thanks, @jonwehausen. That makes sense.

**Comment by nedierecel** [comment]
@jonwehausen Confirming I see this. Items noted below:

1. Add an exception in GTM so it does not trigger PVs on the sandbox environment. 
2. Add to the RegEx table a rule to capture the `practice-area-heading`
3. Add a scroll depth tag

**Comment by jonwehausen** [comment]
@nedierecel -- 1 and 2 have been accounted for. 

@bsmartin-ep Could I task you with setting up a scraping method to capture the practice area heading and store within the event action label? 

Once configured, this can be added to "RegEx - Event Action" to pass into each click event action and we can retest.

**Comment by bsmartin-ep** [comment]
Sure thing @jonwehausen

**Comment by bsmartin-ep** [comment]
@jonwehausen - Think the heading should be in the front of the group or the end?

Practice Area Click - {{Click Heading}} - {{Click Text}} - {{Click URL}}

**Comment by jonwehausen** [comment]
@bsmartin-ep Great question! Let's roll with the front. That way our syntax is consistent in terms of Most General > Most Specific.

**Comment by bsmartin-ep** [comment]
@jonwehausen - OK cool.  I added the Custom JavaScript to pull the heading and updated the RegEx. 

Think the heading and regular link clicks should be split up into different events?

**Comment by jonwehausen** [comment]
@bsmartin-ep I'm with you -- Let's break this one out for heading clicks.

**Comment by bsmartin-ep** [comment]
@jonwehausen - Updated.  These actions look OK to you?

Practice Area - Heading Click - Research - https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/research

Practice Area - Link Click - Research - Research plan template - https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-plan-template.md

**Comment by jonwehausen** [comment]
Thanks Brian! Confirming container has been published here and closing story. 

cc: @billfienberg @meganhkelley
