### ISSUE TITLE
Analytics Implementation or QA Support for Profile | Hub

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#63551]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

</div>
</details>

### Required
- **Is this request for **Google Analytics implementation** or **QA**?**

     - [X] Google Analytics implementation
     - [ ] QA

- **Who is this request for?**

    - [authenticated-experience, profile]
    
    
- **Provide the link(s) for Google Analytics implementation or QA**
  
    - [Insert link(s)]
    
- **When is the launch date?**
    - [Oct/Nov 2023]

- **What interactions need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked_
    
    - [If this is a funnel, insert each step's URL - pages visible depending on the applicant's answers should be marked accordingly]
    
    - [Insert other interactions - please review the [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) and [GA Data Dictionary](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Google-Analytics-Data-Dictionary.1810464912.html)  to make sure these interactions aren't already tracked]

### Optional
- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - [Insert test user]

- **Any additional comments**

- See [slack thread ](https://dsva.slack.com/archives/C1Q4294JJ/p1691525591192939)for more details. We need tracking on the profile menu vs the hub 

We need to know when users follow the links from the hub vs. when they're entering a page using the nav menu 

hub:

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/05b93ad6-5964-47cf-89ff-5e116427ea7c)

nav menu:

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/ab43e300-7713-4ed1-90f4-ef112ceafa46)

> Please leave the following blank

## Acceptance criteria
- [x] All appropriate issue tagging is completed
- [x] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by michelle-dooley** [comment]
Thanks @mtcA6 for your submission, we will review and get back to you with timing.

**Comment by michelle-dooley** [comment]
@mtcA6 - just to confirm this is when a user views Profile information on VA.gov from their mobile device?  Or is this for the mobile app?

**Comment by mtcA6** [comment]
@michelle-dooley mobile device not the app.

**Comment by Samara-Strauss** [comment]
@michelle-dooley this is for any view -- whether it's desktop, tablet, or mobile.

**Comment by mtcA6** [comment]
@jestutt did you get a chance to review this after we talked a couple of weeks back? I know you had said it would be pretty easy to get us the events. If GA4 is ruining those chances, that's ok, only curious so I can prepare for launch w/some sort of backup plan.

**Comment by jestutt** [comment]
@mtcA6  Working on this right now.

**Comment by mtcA6** [comment]
🕺 thanks!!!!!

**Comment by jestutt** [comment]
@mtcA6  Events have been added for clicks on links in the Profile Hub cards and the side navigation. 

So far I only see my [test clicks in GA](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w178298118p176884211/_u.date00=20231120&_u.date01=20231126&_.useg=userGL9in2egQbiSGUUh3rPFYQ,userE2PNNf6WR9CfjYePQ5botQ&explorer-table.plotKeys=%5B%5D&explorer-table.filter=navigation%20-%20profile&explorer-table.rowCount=25&_r.drilldown=analytics.eventCategory:Interactions/): 
<img width="595" alt="Screenshot 2023-11-27 at 11 40 00 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/141653184/5a5aef97-0383-48cf-8ac7-e9bf3fde4ac5">

**Comment by mtcA6** [comment]
This is great, thanks for implementing this @jestutt
