### ISSUE TITLE
Updates needed on feature toggles guide

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#63559]
### Description

- [x] **First issue**

At the bottom of step 7 on https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide there is this text:

> Here is a live e[See an example from vets-website](https://github.com/department-of-veterans-affairs/vets-website/blob/f6178ac59b1d691e0f31fb36903b8ba54091b517/src/applications/gi/containers/ProfilePage.jsx#L118).

- [x] **Second issue**

The import guidance in step 7 is outdated and should be as follows:

> Also, note that toggleValues is imported from `@department-of-veterans-affairs/platform-site-wide/selectors` and FEATURE_FLAG_NAMES is imported from `@department-of-veterans-affairs/platform-utilities/featureFlagNames`.

The second line of the code block should read:

`import { toggleValues } from '@department-of-veterans-affairs/platform-site-wide/selectors';`

- [x] **Third issue**

The section on how to access the Flipper UI should be updated as the access method and process have changed: https://dsva.slack.com/archives/C03R5SBELQM/p1691616340610669

- [x] **Fourth issue**

These two pages contain a lot of the same information, and are both being updated, so they're likely diverging. We should merge them (and probably find a better home/section, as neither one really makes sense)

https://vfs.atlassian.net/wiki/spaces/pilot/pages/1859780873/Feature+toggles
https://vfs.atlassian.net/wiki/spaces/pilot/pages/590938137/Feature+toggles+guide

### Relevant URLs

- https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide
- https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretogglesguide-1.AccessFlipperUI

### Which type of team are you on? (Platform team, VFS team, or Leadership)

- OCTO engineer

**Comment by acrollet** [comment]
Updating to note that @ryan-mcneil is already working on at least some of these changes 🙂

**Comment by ryan-mcneil** [comment]
I've added a new page describing the new process for [Flipper UI Access](https://vfs.atlassian.net/wiki/spaces/pilot/pages/2734030875/Flipper+UI+Access) and have updated respective pages (this should cover the "Third Issue" ✅ 

I would say that our biggest TODO here is merging the two Feature Toggles/Flipper UI pages:
https://vfs.atlassian.net/wiki/spaces/pilot/pages/1859780873/Feature+toggles
https://vfs.atlassian.net/wiki/spaces/pilot/pages/590938137/Feature+toggles+guide

They contain a lot of the same information, but are both being updated independently and likely diverging.

One lives under `Infrastructure` which doesn't make sense (nor does the Infrastructure team know much about the implementation), and the other lives under `Frontend Developer Docs` despite it having both FE and BE subsections. Perhaps it deserves a section of its own? I'd bet there's some other pages that would likely fit in there too.

**Comment by vbellissimo** [comment]
@ryan-mcneil Thanks for the updates made to the new page you started.

As for the consolidation approach you recommended above, I can assign that to one of the writers in the my team. Would you mind if they work with you directly on this?

Thank you.

**Comment by ryan-mcneil** [comment]
@vbellissimo sure, happy to help

**Comment by ryan-mcneil** [comment]
@laucon makes sense to me! I'll likely be making another pass on Flipper related stuff in the next couple months, so I'll give the entire content an update (if needed) at that point in time

**Comment by laucon** [comment]
Great! In that case, I'm going to go ahead and do all that. :)

**Comment by laucon** [comment]
@ryan-mcneil One thing I do need help with is figuring out where in the IA [Feature toggles guide](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide) should go. Right now it's under Developer Tools-->Infrastructure. Is that an ok place? And if not, do you have any better suggestions?

**Comment by laucon** [comment]
Also, I fixed the first issue. I'll fix the second issue as soon as I can.

**Comment by ryan-mcneil** [comment]
@laucon 🤔 . The thing is that it's not related to infrastructure at all. And it's used by both Frontend and Backend devs (hence why there's both FE and BE sections in the doc). There's not really a good place for it in the current structure. Perhaps there should be a "General Tools" section at the same level as Infra/FE dev docs/BE dev docs (though I don't LOVE that name for this...). I've asked my team for other suggestions, too.

**Comment by laucon** [comment]
ok. We have a section about accessing tools in the "Getting Started" section, which is outside Developer docs. Would that make any sense as a place?

**Comment by laucon** [comment]
@ryan-mcneil actually, wait, the original Features Toggle section which we merged was under "Developer docs-->Frontend-->Tools." I know it's not ideal since it's also used by backend, but maybe we should put it there?

**Comment by ryan-mcneil** [comment]
@laucon Neither REALLY make sense but I suppose that's better than the other options. I could see it confusing people though. It seems like we should have a general section for tools/practices that might apply to both FE and BE devs 🤷

**Comment by laucon** [comment]
@ryan-mcneil ok. I'm going to talk to my team about that idea. I've now merged them. And I'll take care of Second issue as soon as I can.

**Comment by ryan-mcneil** [comment]
@laucon sounds good! Happy to be a sounding board if needed (though I'm generally more likely to answer slack, so maybe try me there. I'm glad I saw the notification for this 😆)
