### ISSUE TITLE
Flipper UI access for Chris Kim

### ISSUE THREAD

**Issue by chriskim2311** [department-of-veterans-affairs/va.gov-team#63564]
### Your Name

Chris Kim

### Your GitHub handle (Flipper UI access is managed through GitHub)

chriskim2311

### Team, Role, and Company of the target individual

Sitewide Public Websites: Front End Developer at Kind Systems

### Please confirm if you are on the VFS Team Roster, Platform Team Roster or are a Federal User

- [X] [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

**Comment by ryan-mcneil** [comment]
@chriskim2311 Approved for Flipper access across all environments
