### ISSUE TITLE
Adding Turi Clausell to DSVA Slack

### ISSUE THREAD

**Issue by huggins-va** [department-of-veterans-affairs/va.gov-team#63582]
Please add: 
Turi Clausell (turi.clausell@oddball.io) as a Multi-channel user to vaapi-consumer-support & team-okapi

Turi is the new Product Manager on team Okapi (onboarding date: 8/14/23)
work email: turi.clausell@oddball.io
va email: tbd
github username: tbd

Thank you,
Nora 

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add [_insert email_] as a single-channel guest to [_channel name_].
- Please add [_insert email_] as a multi-channel guest to these channels: [_channel names_].
- Please add [_insert email_] as a full member.
- Please change the status of [_slack username_] from [_current status_] to [_desired status_]

**Comment by LEHigley** [comment]
added to slack but can't add to either channel--invited to #general
