### ISSUE TITLE
[QA] 10-10CG - Facility page: Create Test Cases in TestRail

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#63595]
## Background
The Facility selection page on the 10-10CG is being updated to allow for a dynamic search using City, State or Postal (zip) code.
We will have a search page, results page and a confirmation page showing the selection and the parent facility (if different).  If the selection and parent facility are the same, only the one facility will appear on the confirmation page.
We need to enter test cases in TestRail for using the new Facility pages.

### Resources
- [Existing Use Case document](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-10-10cg-facility-selection.md) (in Sensitive repo)
- [TestRail - Team Dashboard](https://dsvavsp.testrail.io/index.php?/projects/overview/10)

## Tasks
- [ ] Enter the test cases into TestRail, based on the Use Cases outlined
- [ ] Review with PM

## Acceptance Criteria
- Test Cases will be created in TestRail to cover the new Facility pages functionality.

**Comment by fbonds** [comment]
Completed.  Added test cases C43794 through C43811

**Comment by hdjustice** [comment]
Looks great!  I created a Subsection under CG Manual test cases and put the Facilities there, grouped together.
