### ISSUE TITLE
[QA] 10-10CG - Facility page: Create Use Cases

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#63594]
## Background
The Facility selection page on the 10-10CG is being updated to allow for a dynamic search using City, State or Postal (zip) code.
We will have a search page, results page and a confirmation page showing the selection and the parent facility (if different).  If the selection and parent facility are the same, only the one facility will appear on the confirmation page.
We need to outline use cases for using the new Facility pages.

### Resources
- [Existing Use Case document](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-10-10cg-facility-selection.md) (in Sensitive repo)
- [Example from Household section QA](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-1010EZ-household-section-optimization.md)

## Tasks
- [ ] Outline various uses cases that take the applicant through the Facility search, selection and confirmation pages.
- [ ] Review with PM

## Acceptance Criteria
- Use Cases will be created to cover the new Facility pages functionality.

**Comment by fbonds** [comment]
Complete & ready for validation @hdjustice

**Comment by hdjustice** [comment]
Looks good!  We will be able to add more detail once the development is almost done.  We will be able to understand the behavior of the fields a bit better.
