### ISSUE TITLE
[Bug] Analytics Failures Appear to be Underreported for Education Feedback Tool

### ISSUE THREAD

**Issue by nedierecel** [department-of-veterans-affairs/va.gov-team#636]
## What happened?
- The sum of `submission-successful` and `submission-failed` events should total the `edu-feedback-tool--submission` events. It appears failures may be underreported.
- [GA report showing successes are closer to the number of sessions reaching the form completion - see bottom of funnel](https://analytics.google.com/analytics/web/#/report/conversions-goal-funnel/a50123418w177519031p184334251/_u.date00=20190601&_u.date01=20190719&_.goalOption=10/) 
- [GA Report Showing Successes+Failures](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p184624291/_u.date00=20190601&_u.date01=20190719&explorer-segmentExplorer.segmentId=analytics.eventLabel&explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.eventLabel%22,%22RE%22,%22edu-feedback-tool-(-submission%7Csubmission-successful%7Csubmission-failed)%22,0%5D%5D&explorer-graphOptions.selected=analytics.nthDay/)
- Screenshot
![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/6bc9f32c-df77-417b-9645-3f7f746f4e3d)
- We also see two naming conventions of the `submission-failed` used. 

## Specs:
- N/A

## Steps to Reproduce
- Analytics-Insights team has not been able to reproduce

## Desired behavior
- 'submission-failed` should trigger with failures, so we will need to understand why there is a current gap. 

## Acceptance Criteria
- [ ] Correct possible underreporting of `submission-failed` events

## Definition of Done
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by joanneesteban** [comment]
@alexpappasoddball Tagging Triage - This is an analytics issue that rose from users calling in (Call Centers) that we need engineers to help out with.

**Comment by omgitsbillryan** [comment]
This is a polling endpoint, in that, the browser submits the requests and will then "poll" the API once per second until a proper response is received. I'd guess that `edu-feedback-tool--submission` represents that polling behavior. So rather than errors being _under_-reported, I'm guessing that the total is being _over_-reported.

**Comment by nedierecel** [comment]
@omgitsbillryan Thanks for the clarification. Is it within our control to reduce the polling and fix the overreporting of --`submission` events?

**Comment by cvalarida** [comment]
:thinking: It doesn't looks like the `--submission` events are part of the polling loop after all. :confused:

From what I can tell, this is what's happening:
1) Submit controller calls standard form `submitForm`
2) `submitForm` records `--submission` event
3) `submitForm` calls `formConfig.submit`
4) `formConfig.submit` makes a request to `/gi_bill_feedbacks`
5) The `apiRequest` is passed `onSuccess`, which calls `pollStatus`
6) `pollStatus` loops recursively, calling `checkStatus` until the result is not `pending`
    - `checkStatus` makes a request to `/gi_bill_feedbacks/${guid}`

I'll turn this into a diagram to see if I can track down if we're missing recording any successes or failures.

**Comment by cvalarida** [comment]
Hrm. So I just poked around in the code for a while and came up with this: 
![image](https://user-images.githubusercontent.com/12970166/62098077-cc30a500-b23d-11e9-9c76-bebb249268af.png)

From what I can tell, we're logging successes and failures in all the right places and _aren't_ logging the `--submission` event more than we should be, so this is...pretty confusing to me.

@nedierecel What are you using this report for? I'm typically leery of using GA for absolute numbers myself; from my experience, they're pretty squidgy and are better for getting an idea of the order of magnitude or relative frequency. If you need hard numbers, we might be able to get you a report from the database...or something... _waves hands vaguely._ (Caveat: I don't actually know if that's possible.)

At any rate, it's clear there _is_ a discrepancy and I don't know why. Only thing I can think of is that the request maybe takes a long time and a good chunk of users give up before getting the `success` or `failed` response.

**Comment by nedierecel** [comment]
@cvalarida Thanks so much for outlining this! 

*Uses of Successes/Failures*: We're using it to directionally measure error and success rate by form. I imagine it won't always add up but worthy of a discussion if we think there could be an acceptable discrepancy range.

**Comment by cvalarida** [comment]
Gotcha, that makes sense, @nedierecel. :+1: 

@omgitsbillryan Is there any way we can find out how long that async job takes so we can get an idea of how long users may be waiting around for that confirmation page? I've got a hunch it takes a while, so we're seeing user dropoff before we're getting the `success` or `failed` GA events.

**Comment by omgitsbillryan** [comment]
Not easily, I'm afraid. Our automatic StatsD monitoring only records failures and successes. I think Sidekiq dumps some info to the rails log, but that would be difficult to sift through to get a real sense of how long it takes.

**Comment by cvalarida** [comment]
@omgitsbillryan Boo. Okay. Thanks for the update.

@nedierecel I'm not sure how you want to proceed, but I think that's the problem. To record these events, the user has to wait around for an asynchronous job to get back to them. I think the fundamental problem here is relying on user behavior.

:thinking: I don't suppose there's any way you can get the average time they wait around on the confirmation page, can you? (Ideally, more than just the average time would be awesome, but I don't even know what to ask for at this point.)

**Comment by omgitsbillryan** [comment]
Our existing BE monitoring only records success & failure increments, but I dont think it would be too much work to add some monitoring for benchmarking how long the external service call takes.

Something to consider is that the external service call could succeed on the BE, but then the browser closes the window before the next 1 second poll call.

**Comment by nedierecel** [comment]
@cvalarida We can get average page duration on confirmation, but could get more granular for each hit timestamp with the Google Analytics<>BigQuery connection. One other caveat of time on page is that it will not calculate page duration if that page is an exit page within that user's session.

Chris, based on our implementation, do you think there are further steps here (knowing that the delta could be explained by the exit occuring before the `-success` or `-failed` events occur? 

@joanneesteban Adding you here for more visibility on BigQuery and additional benefits that we would receive.

**Comment by cvalarida** [comment]
@nedierecel I don't think there's anything more to do on the FE -> GA side of things; we can't record a success or failure event in GA until we know which it is from the back end, and the back end won't know until the asynchronous job is finished, by which point the user may have left the page.

That query may give us better insight into whether that theory (users getting bored and leaving) is true, but we won't be able to change anything if it is.

A better approach to this (and similar scenarios) is to get the events from the back end, but I think that has to be outside of analytics.

**Comment by nedierecel** [comment]
Thanks @cvalarida - let's plan on closing this task, and we will monitor if we start to see larger discrepancies with submission successes and failures.
