### ISSUE TITLE
FE Discovery for Toxic Exposure 

### ISSUE THREAD

**Issue by christinec-fftc** [department-of-veterans-affairs/va.gov-team#63604]
Look into the following to prep for the upcoming TE work which is currently going through research
- Is there a technical limitation on how many date ranges we can have? (this is for the list loop pages)
- For the OOB review and submit page, how will this look and behave? Will we need to do any customization?
- Do we have an idea of what the submission data will look like?
- Is there any processing we need to do on the data before passing it to BE?
- Get a rough idea of Story/ticket breakdown
- What kind of unit and e2e tests will we need for the new pages?
- Toggle setup

**Comment by RakshindaAslam** [comment]
@christinec-fftc - is this discovery ticket include showing the information and allowing edits on Submit and Review screen?

**Comment by christinec-fftc** [comment]
### Discovery Findings (still in progress)

**1. Is there a technical limitation on how many date ranges we can have? (This is for the list loop pages)**
No limitation on the front end beyond browser constraints for page size. However, there may be limitations on the Lighthouse end. We’ll get more clarity as the API contract is finalized (see details in item 3).

**2. How will the Review & Submit page look and behave? Will we need to do any customizations?**
TBD - wait for Monday meeting

**3. Do we have an idea of what the submission data will look like from vets-website to vets-api and finally to Lighthouse?**
Reviewed the LH spec. It looks like we have a misalignment with two items.  The LH spec only accepts a single date for each of the Gulf War, Herbicide and Hazard Exposure questions (same as paper form), while the mocks allow for multiple dates on each of these questions. Also, question 15E is a freeform text box on the paper form, but the LH api has a rigid format.
	
We have at least 3 different options we could move forward with
3.1 Request that the multipleExposures field be changed from an object to a string.
This would align the digital form with the paper form. Currently it is an object with one set of exposureDates, exposureLocation and hazardExposedTo fields.

We could build the 526 pages as per the mocks, and transform the data before submit, putting only the first of each of the dates for the Gulf War, Herbicides, and Hazard Exposure questions. Then build a string for the rest of the dates, locations and exposures (i.e. question 15E).

For example:
```
Gulf War Exposure: 01-2020 to 02-2020, 01-2021 to 10-2021
Herbicide Exposure: 05-2005 to 12-2005
Hazard Exposure: 11-2020 to 12-2020
```

Note: Make sure to clarify max length for this string

3.2 Request the following fields be changed to array instead of object (this effectively means we would never populate multipleExposures field)
gulfWarHazardService.serviceDates
herbicideHazardService.serviceDates
additionalExposures.exposureDates

```
{
  "gulfWarHazardService": {
    "servedInGulfWarHazardLocations": "YES",
    "serviceDates": [
      {
        "beginDate": "07-1999",
        "endDate": "01-2005"
      }
    ]
  },

  "herbicideHazardService": {
    "servedInHerbicideHazardLocations": "YES",
    "otherLocationsServed": "Guam",
    "serviceDates": [
      {
        "beginDate": "03-2002",
        "endDate": "10-2004"
      }
    ]
  },
  "additionalHazardExposures": {
    "additionalExposures": ["ASBESTOS", "SHIPBOARD_HAZARD_AND_DEFENSE"],
    "specifyOtherExposures": "Other exposure details",
    "exposureDates": [
      {
        "beginDate": "07-2011",
        "endDate": "10-2013"
      }
    ]
  }
}

```

3.3 If LH api cannot change, use a page attachment for the additional dates, locations, and exposures.

**4. What kinds of tests will we need for this new flow?**
Unit tests should be added with each of the pages
Update mock data for e2e tests, along with any necessary helper functions
Test Rail scenario(s) for manual tests & collaboration cycle review 
	
**5. Toggle Setup**
There are two options for the new pages. Option 2 is preferred
1. Use sessionStorage to store the toggle value, similar to SHOW_8940_4192 
2. Read in the toggle in the form app  and add to form data

**6. Pre-fill**
No pre-fill work needed. All the data will be new info from the user.

**7. Page migration**
7.1 The new pages have newly required fields so we’ll want to make sure user is redirected appropriately to fill them out. This will be tricky, but essentially if the user has a save in progress form and would be bypassing the TE pages, we should redirect them there.

7.2 For the page being removed, we'll also have to handle the redirect properly.

**8. Story/ticket breakdown**
Based on the current mocks, there are a dozen front end stories for this work

Stories 1- 4 (for the 9 pages we’re adding)
Each of these stories, should have unit tests and update mock data as we go

1. toxic-exposure (also create toggle)
toxic-exposure-confirm


2. gulf-war-exposure
gulf-war-exposure-dates
herbicide-exposure
herbicide-exposure-dates

3. hazard-exposure
hazard-exposure-dates

4. toxic-exposure-summary

5. Remove page /new-disabilities/follow-up and handle its page migration


6. Possibly bundle the following content changes into one story
Disabilities follow-up questions
Conditional questions
Supporting evidence

7. Submit transformer: add and transform any data before passing to vets-api

8. Page migration for the new TE section

9. E2E tests

10. Test Rail scenarios, staging Review prep

11. Product documentation updates

12. Post launch toggle clean up


**9. Resources**
Pre-fill
https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-how-to-work-with-pre-fill

Submit transformer
https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-how-to-work-with-transformforsubm

Lighthouse api docs (go to the POST for 526 -> Schema or Example Value)
https://dev-developer.va.gov/explore/api/benefits-claims/docs?version=current
