### ISSUE TITLE
Platform Atlas App Login and Code Verification

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#63606]
Determining and verifying code ownership is a step towards enabling additional autonomy for VFS teams in deploying code to vets-api. We need your help verifying ownership of code so we can ensure we start with accurate information.

Directions:
1. Each team should verify that they are able to [login and view code ownership](https://va-codeowners.boehs.com/).![Screenshot 2023-08-15 at 10.56.18 AM.png](https://images.zenhubusercontent.com/61ba3abb874c1c3d7c47bf01/6d7a811c-b6eb-42bf-821e-e1d3b6bda197) 
![Screenshot 2023-08-15 at 10.56.26 AM.png](https://images.zenhubusercontent.com/61ba3abb874c1c3d7c47bf01/fb5a56f0-1552-4f03-b527-a1289610dd09)
2. Each team should verify that the correct vets-api files are assigned to your team.![Screenshot 2023-08-15 at 10.58.28 AM.png](https://images.zenhubusercontent.com/61ba3abb874c1c3d7c47bf01/ef3c3ae6-0c44-4b63-b44e-899dd6de6da6)![Screenshot 2023-08-15 at 10.58.39 AM.png](https://images.zenhubusercontent.com/61ba3abb874c1c3d7c47bf01/f8837c9d-fabd-40a6-8586-8047626a2bb7) 
3. Indicate completion of the above (2) tasks by commenting in the comments below.

**Comment by laineymajor** [comment]
Teams have started verification.
@laineymajor to remind teams throughout the week via slack and ToT.
@RachalCassity continuing to debug

**Comment by cferris32** [comment]
I've logged in and confirmed vets-api code ownership for the appointments/VAOS team

**Comment by RachalCassity** [comment]
@cferris32 Thank you!

**Comment by maxx1128** [comment]
I've logged in and confirmed `vets-api` ownership for myself and the Facilities team.
