### ISSUE TITLE
Business intake form for [Benefits & Claims: Burial Form (530) Deactivation Notice]

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#63615]
## Your Details
1.  **Your Name**: Laura Steele
​
2.  **Business Line**: Benefits and Claims -> Non-Disability Experience -> Burial
​
## Notification Details
1.  **Notification type**: Email
​
2.  **Please describe your use case.**
The digital application for burial benefits (530) form will be temporarily deactivated while it's updated to align with the paper version. Veterans with in-progress applications need to be notified that they cannot continue with their digital claim and that they need to start over with a paper claim.
​
3.  **What actions can the user take based on the notification they receive?**
Veterans with in-progress applications can...
   - click through to visit the "review claim" page on VA.gov and view a summary of the information they have entered and saved.
   - click to download a copy of the pdf form from VA.gov
   - click through to learn more about how to apply on VA.gov
   - open the pdf form via the attachment
​
4.  **What is the desired business outcome?**
Veterans with in-progress applications read the email and take one of the actions outlined in number 3 above. The primary goal is to have recipients download the pdf 527 form from VA.gov or open the 527 pdf attached to the email.
​
5.  **What system will kick off the notification? Please note the system should be inside the VA or have an ATO.**
TBD - We are working to understand where the in-progress claim flag/attribute is stored.
​
7.  **What will trigger the notification?**
This will be a one-time notification for Veterans with in-progress forms, and the distribution list will be pulled in tandem with deactivating the form (it will not be an ongoing list).
​
8.  **Provide sample content per notification type, if you have it.**
[Draft email text](https://dvagov.sharepoint.com/:w:/s/vaabdvro/EXVCnaTlTSVGnbhmJzaXTFkBSg2Nl_JaFUXiamYwF1_6Yw)
​
9.  **Has a Privacy Officer (PO) seen and approved the content? If not, do you know who your PO is?**
Not yet. We are working to determine who our PO is, but we do not anticipate using anything other than the Veteran's first name within the email.
​
10.  **Would you prefer to provide contact information for the recipients or would you rather VA Notify look this up for you by Veteran ID? If by ID, please let us know what identifier is used in your system.**
Are there any recommendations for which option to use? We anticipate that Veterans will be identified on VA.org by ICN.
​
11.  **Do you currently capture communication preferences related to this notification? If so, please describe.**
No.
​
12.  **What is the anticipated volume of notifications per day, week, month?**
Anticipate 3k for one-time notification. Looking for input from VA Notify team on whether or not to batch these.
​
13.  **When does this notification need to be in production?**
In coordination with the release of the redesigned 530 form review page that my team is also releasing in approximately 1 month. Sequence of events:
   - Deactivate 530 online form and release review form page.
   - Quickly follow (next day) with email to users with in-progress forms notifying them that the online application cannot be submitted and they must apply via paper form.

**Comment by steele-lm** [comment]
@fiorella-io @tblackwe @fred-khoury-oddball

**Comment by bevnobev** [comment]
Hi @steele-lm Forgot to ask during the meeting.  Can you send a list of email addresses (va.gov) for the people who will creating the email content?  @GitSamJennings can get you setup in our staging environment

**Comment by steele-lm** [comment]
@bevnobev Thanks for meeting with us and for reaching out. @fred-khoury-oddball (FREDRICK.KHOURY@va.gov) and @fiorella-io (fiorella.galvez@va.gov) will need access!

**Comment by GitSamJennings** [comment]
Hi @steele-lm, we have added them both to the VA.gov service as Editors in Staging. Please let us know, if you have additional questions. Thanks!

**Comment by fiorella-io** [comment]
@GitSamJennings Should we create the emails in staging, or is production fine? If we need to do it in staging, I don't have access to staging. Every time I log in, it loads forever until I see an error 70 message. However, once I'm logged into production, I don't have access to the "Notification Templates" button like in the onboarding document. It says to submit an intake form. Do I need to submit one for myself?

**Comment by GitSamJennings** [comment]
@fiorella-io let me look into this and I will respond as soon as I know more. Thank you for your patience!

**Comment by fred-khoury-oddball** [comment]
Hey some of this work is being transitioned to @tblackwe . Could we please request staging and prod access to the va notify dashboard for @tblackwe .
@GitSamJennings

**Comment by mjones-oddball** [comment]
Hi @fred-khoury-oddball Sam is OOO today. We will grant @tblackwe access tomorrow and let you know when complete.

**Comment by mjones-oddball** [comment]
@tblackwe you should now have access in staging and prod, can you please log in when you get a chance and let me know if you have any questions? CC @fred-khoury-oddball

**Comment by tblackwe** [comment]
I'm in! TYVM

**Comment by steele-lm** [comment]
We are targeting deactivating the pension 527 and burial 530 forms on Wednesday, September 27th, and I anticipate that the notification email will also go out the 27th.

**Comment by steele-lm** [comment]
@GitSamJennings @bevnobev We received confirmation that we are NOT deactivating the Burial Form 530, so we will not be sending out a notification email.
