### ISSUE TITLE
Business intake form for [Benefits & Claims: Pension Form (527) Deactivation Notice]

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#63614]
## Your Details
1.  **Your Name**: Laura Steele
​
2.  **Business Line**: Benefits and Claims -> Non-Disability Experience -> Pension
​
## Notification Details
1.  **Notification type**: Email
​
2.  **Please describe your use case.**
The digital application for pension (527) form will be temporarily deactivated while it's updated to align with the paper version. Veterans with in-progress applications need to be notified that they cannot continue with their digital claim and that they need to start over with a paper claim.
​
3.  **What actions can the user take based on the notification they receive?**
Veterans with in-progress applications can...
   - click through to visit the "review claim" page on VA.gov and view a summary of the information they have entered and saved.
   - click to download a copy of the pdf form from VA.gov
   - click through to learn more about how to apply on VA.gov
   - open the pdf form via the attachment
​
4.  **What is the desired business outcome?**
Veterans with in-progress applications read the email and take one of the actions outlined in number 3 above. The primary goal is to have recipients download the pdf 530 form from VA.gov or open the 530 pdf attached to the email.
​
5.  **What system will kick off the notification? Please note the system should be inside the VA or have an ATO.**
TBD - We are working to understand where the in-progress claim flag/attribute is stored.
​
7.  **What will trigger the notification?**
This will be a one-time notification for Veterans with in-progress forms, and the distribution list will be pulled in tandem with deactivating the form (it will not be an ongoing list).
​
8.  **Provide sample content per notification type, if you have it.**
[Draft email text](https://dvagov.sharepoint.com/:w:/s/vaabdvro/EXVCnaTlTSVGnbhmJzaXTFkBSg2Nl_JaFUXiamYwF1_6Yw)
​
9.  **Has a Privacy Officer (PO) seen and approved the content? If not, do you know who your PO is?**
Not yet. We are working to determine who our PO is, but we do not anticipate using anything other than the Veteran's first name within the email.
​
10.  **Would you prefer to provide contact information for the recipients or would you rather VA Notify look this up for you by Veteran ID? If by ID, please let us know what identifier is used in your system.**
Are there any recommendations for which option to use? We anticipate that Veterans will be identified on VA.org by ICN.
​
11.  **Do you currently capture communication preferences related to this notification? If so, please describe.**
No.
​
12.  **What is the anticipated volume of notifications per day, week, month?**
Anticipate 2k for one-time notification. Looking for input from VA Notify team on whether or not to batch these.
​
13.  **When does this notification need to be in production?**
In coordination with the release of the redesigned 527 form review page that my team is also releasing in approximately 1 month. Sequence of events:
   - Deactivate 527 online form and release review form page.
   - Quickly follow (next day) with email to users with in-progress forms notifying them that the online application cannot be submitted and they must apply via paper form.

**Comment by steele-lm** [comment]
@fiorella-io @tblackwe @fred-khoury-oddball

**Comment by steele-lm** [comment]
@GitSamJennings This will be an email message sent out at a specific point in time to a defined group of people, so I'm not sure a trigger is needed. We will be deactivating the form and then reaching out to individuals who got stuck in limbo with in-progress forms. I think we can pull that list of people via a query. @tblackwe what do you think?

**Comment by bevnobev** [comment]
Hi @steele-lm VA Notify needs a trigger, API call, to send a notification.  At the moment we don't functionality to send from a list or spreadsheet.  

We have written triggers for saved in progress notification reminder, so that code could be reused/refactored for this.  I'm not an engineer, so please don't quote on this.  Happy to meet to discuss cc: @GitSamJennings

**Comment by tblackwe** [comment]
ty @bevnobev. I'd like to take you up on that meeting offer, along with @fred-khoury-oddball who will likely be the engineer from our side. We understand who our user set will be, but will need to understand how to facilitate a trigger event.

**Comment by bevnobev** [comment]
Monday 8/21 @ 10:30am CT works for my team

**Comment by steele-lm** [comment]
@bevnobev I sent out the meeting request for 8/21 and included @nathanbwright and @tsr-rise8. The [burial notification request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63615) will mirror the pension request, so we can include that in the conversation. Thanks!

**Comment by bevnobev** [comment]
Hi @steele-lm No need to coordinate the timing of the emails, just let us know a few days before you send so we can be on alert if there are any issues.  I have asked my team to give me a send "rate" that you should stay within as to not overload our system.  I I'm not sure how many forms are in progress, so that may not be necessary.  Once I have the rate, I'll let you know.

**Comment by steele-lm** [comment]
@fiorella-io Looping you in. @bevnobev mentioned that we can track downloads of the pdf if a link to it is included in the email. What do you think?

**Comment by fiorella-io** [comment]
@steele-lm I think anything we can track will be helpful!

**Comment by bevnobev** [comment]
Hi @steele-lm More details on timing/coordination.  

We'd want to know in advance what time of day they expect the blast to go out, total size of blast, and how often these can be expected so we can make sure there's no conflicts with our largest volume use cases.

Typically we wouldn't want a service to be sending more than 15 requests per second.

Let me know if you have any questions.

**Comment by GitSamJennings** [comment]
@steele-lm do you happen to know what date you will deactivating the forms and then how soon after will you be sending the blast? We just want to make sure we have it on our radar to monitor. Also, would you mind confirming with your engineers that the API requests within the batch will not exceed 15/second? Thanks!

**Comment by steele-lm** [comment]
@GitSamJennings We're still working through the staging review process, so I anticipate we may be ready to deactivate both forms within the next 2 weeks. I'll circle back with you when I have a better idea of specific dates. @fred-khoury-oddball can you confirm that the API requests will not exceed 15/second?

**Comment by fred-khoury-oddball** [comment]
Good call out thank you for the heads up. We will be sure that we are not sending more than 15 api requests per second.

**Comment by steele-lm** [comment]
@GitSamJennings The related burial form deactivation is scheduled to go through staging review later today. Assuming there are no release-stopping issues, we will most likely deploy early next week.

**Comment by GitSamJennings** [comment]
If Burial 530 deactivation is scheduled to go out early next week, does that mean that Pension 527 deactivation is as well?

**Comment by steele-lm** [comment]
At the earliest, pension could go live mid-week. The pension staging review is scheduled for 9/26. I'm working on getting some additional clarity on what form volume looks like for each day of the week and coordinating with Emily Theis on a specific deactivation date for both forms.

**Comment by steele-lm** [comment]
We are targeting deactivating the pension 527 and burial 530 forms on Wednesday, September 27th, and I anticipate that the notification email will also go out the 27th.

**Comment by GitSamJennings** [comment]
Thank you!

**Comment by bevnobev** [comment]
Hi @steele-lm I know you plan to send notifications out tomorrow.  I didn't see a utm tracking for the "Learn how to apply" link.  Is number of Veterans that click the link, something you would like to track?

**Comment by steele-lm** [comment]
@bevnobev or @GitSamJennings  Is there documentation available on how to add the utm tracking? It looks like the analytics info that was under the "post launch checklist" [section on GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-notify/README.md#successes) was recently removed.

**Comment by GitSamJennings** [comment]
Hi @steele-lm, you can create a UTM campaign when you go to edit your template. After you select Edit, you would then navigate to the Analytics Link Generator, which will display this page. 
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/132367046/06eebc19-2f83-4f35-b1b7-c7ad4104cf19)
Please let us know, if you have additional questions. Thank you!

**Comment by tblackwe** [comment]
@steele-lm @fiorella-io I have validated that I can make the modification to the UTM tracking. Any opinions on what it should be called?

`PensionsDeactivation102023` ?

**Comment by steele-lm** [comment]
@tblackwe Great! I didn't realize you had access, so I had just asked @fiorella-io! For the campaign name, I would use:
- Pension: Temporary Deactivation of Online Application for VA Pension Benefits
- Burial: Temporary Deactivation of Online Application for VA Burial Benefits

**Comment by tblackwe** [comment]
I dont know that it can be that long. this will appear in the Veterans URL bar

**Comment by tblackwe** [comment]
yep, spaces are not allowed. 
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/7817263/1daf54e4-78df-4a64-be7e-af12fa1a29d8)

**Comment by steele-lm** [comment]
Sorry, I missed that the name was going to appear as part of the url within the address bar. In that case:
- pension: 527EZdeactivation
- burial: 530deactivation

**Comment by tblackwe** [comment]
Change has been applied to the staging templates

**Comment by GitSamJennings** [comment]
Good morning @steele-lm! Are you still planning on going live today for this form, as well as Burial 530 for the deactivation?

**Comment by steele-lm** [comment]
@GitSamJennings The timeline for release was put on hold yesterday pending some additional discussions around the timeline for re-activating the forms. We hope to have a firm decision on deactivation timing next week. Apologies for the shifting timelines!

**Comment by GitSamJennings** [comment]
Good morning! @steele-lm just circling back to see if a new timeline has been established or if it's still being discussed.

**Comment by steele-lm** [comment]
@GitSamJennings The timeline is still TBD. Apologies for the lack of a firm date. Conversations have continued around the deactivation approach and timeline. Looping in @vbellissimo bc her team may end up actioning the email distribution.

**Comment by GitSamJennings** [comment]
No worries at all. I appreciate the quick response!

**Comment by bevnobev** [comment]
@GitSamJennings @mjones-oddball This launched today.  Tracking utm analytics [here](https://analytics.google.com/analytics/web/#/report/content-landing-pages/a50123418w177519031p176188361/_u.date00=20231109&_u.date01=20231109&_r.drilldown=analytics.landingPagePath:www.va.gov~2Fpension~2Fapplication~2F527ez~2Fintroduction~2F&explorer-table.secSegmentId=analytics.campaign&explorer-table.plotKeys=%5B%5D/)
