### ISSUE TITLE
UX | Profile Hub | Conduct the Study

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#63622]
## Background 
This ticket is to conduct our Hub research w Perigean

## Tasks 
- [x] complete the research 

## Acceptance Criteria 
- [x] research is completed ([ready to work on the topline summary])

**Comment by pamela-drouin** [comment]
@mtcA6 I edited this ticket slightly -- I took out the `draft the summary` task and the `talk with PM/PO` A/C, since this ticket leads into the topline summary ticket. **This ticket is complete!** 😀
