### ISSUE TITLE
Analytics KPI dashboard update request for Profile | Direct Deposit 

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#63633]
# Request an update to your KPI Dashboard  

## What this form is for

Use this ticket template to request an update to your existing KPI dashboard. To request a new product be added to our dashboards, please use [Request a New Standardized KPI Dashboard template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&template=analytics-request-kpi-dashboard.md&title=Analytics+KPI+dashboard+request+for+%5BTeam%5D).

### Expected delivery timelines

Once you’ve submitted this ticket template, your KPI dashboard update request will be pulled into the Analytics team’s workflow the following Wednesday during Platform Sprint Planning or Refinement. We expect to deliver your completed dashboard within the next sprint. 

## Instructions for the VFS team
First, tell us what type of change you need to make:

- [x] Change basic product info
- [ ] **Forms**: funnel changes
- [ ] **Content**: Add or remove pages included
- [ ] Other_____________________________

Next, use the original [KPI request template](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit#gid=981224988) or [(downloaded Excel version)](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/1586823275/KPI%20Dashboard%20Product%20Details%20Template%20-%20MAKE%20A%20COPY.xlsx?inst-v=ced1f4dd-e997-4aa2-9ae8-2cebe369b42f) you filled out to update your information. If you are not able to find that spreadsheet, reach out to the Analytics team on #vfs-platform-support for a new spreadsheet that reflects what we currently have on file.

- [ ] Make a copy of the [Google Sheet](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit#gid=981224988) [(or download Excel version)](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/1586823275/KPI%20Dashboard%20Product%20Details%20Template%20-%20MAKE%20A%20COPY.xlsx?inst-v=ced1f4dd-e997-4aa2-9ae8-2cebe369b42f)
- [ ] Complete worksheet as instructed
- [ ] Link your completed spreadsheet here: ______
- [ ] Check your sharing settings to make sure the Analytics team will be able to access it
- [ ] Add your team label to follow progress

**Additional Info**

- Please use the [KPI Framework](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/Analytics%20Playbook/va-gov-platform-analytics-kpi-framework.pdf) for more information on the metrics used in the KPI dashboards. 
- If you need any analytics support, read through the [How to request Analytics support](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guidelines.1586823275.html#Analyticscustomersupportguidelines-4.RequestaKPIDashboardinDomo).
- If you do not have Domo access, please [request access here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+access-request&template=analytics-request-google-analytics-domo-access.md&title=Request+access+to+Google+Analytics+and%2For+Domo).

**Comment by Samara-Strauss** [comment]
@michelle-dooley -- I added new `GET` and `PUT` codes to [row 10 of the profile spreadsheet](https://docs.google.com/spreadsheets/d/1TOZ4HNLc-TXjPl32ISvdQ4tq_a7fOpayg8wY6mL2SOE/edit#gid=615520209). Does this work for updated documentation?

**Comment by michelle-dooley** [comment]
@Samara-Strauss yep that should work, we will pull into this sprint.  In an effort to keep things clean, I am going to close the OS/browser ticket and include the Profile users counts by page card requests to this, that work is almost done, @dorseypa1 just needs to complete the dataset update with the cleaned up version of the page_name. Will get back to you if we need anything else.

**Comment by michelle-dooley** [comment]
Sprint update: The QA work to complete this will be completed in the next sprint.

**Comment by michelle-dooley** [comment]
Sprint update: QA work to complete this ticket will be completed in next sprint.

**Comment by michelle-dooley** [comment]
Hey @Samara-Strauss - the new profile get/put events have been added to the API tracking and the users by page card has been added. Let me know if you have any questions or need anything further.

**Comment by Samara-Strauss** [comment]
Hey Michelle! A few things:

1. Thank you for adding users by page. Looks great!
2. For the direct deposit PUT information, I moved that to row 21 of the spreadsheet, which looks like amore accurate place for it.
3. Looking at the numbers in Domo, I'm worried we may not be pulling the right information. For direct deposit for comp & pen retrievals, Domo shows ~14K for the last week. However, [a GA dashboard we have set up to track the backend migration from EVSS > Lighthouse](https://analytics.google.com/analytics/web/?authuser=0#/dashboard/DRqBrmiyTD6l8L75rei0fw/a50123418w177519031p176188361/) show about ~42K successful retrievals from EVSS and about ~6500 successful retrievals from Lighthouse (we are currently live to 25% of users for Lighthouse). I would have assumed the new codes I gave you would have reflected the Lighthouse numbers, but they don't appear to. @mtcA6 @adamwhitlock1 can you help me figure out if I gave Michelle the correct codes for our updated Lightouse migration [in rows 10 and 21 of this spreadsheet](https://docs.google.com/spreadsheets/d/1TOZ4HNLc-TXjPl32ISvdQ4tq_a7fOpayg8wY6mL2SOE/edit#gid=615520209)? If not, can you get her the correct codes?

**Comment by michelle-dooley** [comment]
Hey @Samara-Strauss that is because we are filtering the counts to the specific page as noted in your worksheet, so we are only counting direct deposit events for va.gov/profile/direct-deposit. Looking a detailed [page report](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p184624291/explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.pagePath&explorer-table.advFilter=%5B%5B0,%22analytics.eventAction%22,%22RE%22,%22CNP%20Direct%20Deposit%20Retrieval%20Successful%20-%20Eligible%20-%20Setup%20Complete%22,0%5D%5D&explorer-table.rowStart=0&explorer-table.rowCount=25&explorer-segmentExplorer.segmentId=analytics.eventAction) you see the majority of that event action is occurring on the va.gov/profile/ page. We can expand and/or remove the page filter and only look at the event actions if that is what you want?
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaURTIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--874ba509a93b49229d5f48727f970344e9782447/image.png)

**Comment by michelle-dooley** [comment]
@Samara-Strauss so we should remove the sub page filter for all the event actions, i.e. any one of the event actions that happened on va.gov/profile/ would be counted?  Is this true to save events too? [Here](https://docs.google.com/spreadsheets/d/19WJeYmdpp5Y2JiB5l0DLOph1uoyi62u_Cis4eVE5VGE/edit#gid=0) is the current worksheet we are using to pull this info, we would just change page url to va.gov/profile/* for all of them and disregard which profile page they occurred on?

**Comment by Samara-Strauss** [comment]
@michelle-dooley I don't have access to the spreadsheet you linked to above (I've requested it), so I updated [this spreadsheet](https://docs.google.com/spreadsheets/d/1TOZ4HNLc-TXjPl32ISvdQ4tq_a7fOpayg8wY6mL2SOE/edit#gid=615520209) in rows 1 - 11 to use `va.gov/profile/*` instead of the specific page URLs. For saves, you can leave the pages as-is, as people can only submit each form from the specific page they are on.

**Comment by michelle-dooley** [comment]
This work will continue into next Sprint with revised requirements.

**Comment by michelle-dooley** [comment]
Hey @Samara-Strauss the filter parameter for retrievals has been updated to include all va.gov/profile/ pages that specific events occur on not on the pages specific to that event as it was before. This change has increased you retrieval counts as expected. As this work is complete I am going to close this ticket. Please reach out if you have any further questions.

**Comment by Samara-Strauss** [comment]
Looks great! Thank you!
