### ISSUE TITLE
Vets-api terminal access for [individual]

### ISSUE THREAD

**Issue by achievedaniel** [department-of-veterans-affairs/va.gov-team#63647]
### Your Name

Daniel da Silva

### Your GitHub handle (terminal access is managed through GitHub)

@achievedaniel

### Team, Role, and Company of the target individual

Back end devrelper

### Product Manager (PM) name and email

Danielle Baranowski danielle.baranowski@oddball.io

### Product Owner (PO) name and email

Tom Black  thomas.black2@va.gov

### COR Name (leave "None" if you listed an AWS user name above)

Laurene "Reney" Cook

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

Oddball - Amber Malcolm

### Please confirm if you are on the VFS Team Roster or Platform Team Roster

- [ ] [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Please confirm E-QIP Transmittal/Adjudication. This could be a screenshot of your Transmittal/Adjudication email, a link to another request where you've submitted this proof (i.e. AWS/SOCKS), etc.

- [X] I have attached proof that I have either transmitted my E-QIP survey or previously received a favorable decision (by including in "Additional Notes" section below)

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [ ] production (if requesting, justify prod access in 'Additional Notes' section)

### Additional Notes

I need access to Argo terminal to test API accesses to the SUS API that is only access 

<img width="1353" alt="232549474-7a5071c0-a633-4816-9256-72a5fdb6c0e2" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/128069626/95317c90-3622-4113-a655-91c73ba41625">

### Additional resources for Support Engineer

- [ ] For users on a VFS team but not in the VFS Team Roster, they must start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] Instructions for handling requests [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access) - Support Only

**Comment by bdech** [comment]
Found in VFS Roster

**Comment by bdech** [comment]
@achievedaniel  You’ve been granted access to the `dev`, `staging`, and `sandbox` environments.

Here's some additional documentation for the [Vets API on EKS](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-TerminalAccess)
