### ISSUE TITLE
Remove any references of va_online_scheduling_appointment_list feature toggle 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#63664]
## Description
We no longer need to reference the feature toggle `va_online_scheduling_appointment_list` in the frontend code. The Appointment List Redesign work was deployed on June 7, 2023. The product team is requesting to remove any references of the feature toggle. 

---

## Acceptance Criteria

- [ ] Remove any references of the feature toggle `va_online_scheduling_appointment_list` 
- [ ] Delete the feature toggle `va_online_scheduling_appointment_list` in [staging](https://staging-api.va.gov/flipper/features/ ) and [production]( https://api.va.gov/flipper/features)
- [ ] Changes have been updated in `vets-website` and `vets-api`

### Design Assets
N/A

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] [Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/product/feature_toggles.md) is updated

**Comment by ryanshaw** [comment]
Already started this a week or so ago, so assigning to myself.

**Comment by ldelacosta** [comment]
Low priority ticket. We will work on this once we complete the MHV on VA.gov initiative.

**Comment by ldelacosta** [comment]
@young1205 - please notify @JRRoof to validate

**Comment by ryanshaw** [comment]
Related to the following pull requests:

https://github.com/department-of-veterans-affairs/vets-website/pull/26885
https://github.com/department-of-veterans-affairs/vets-website/pull/27935
https://github.com/department-of-veterans-affairs/vets-api/pull/15499

**Comment by ldelacosta** [comment]
No issues found. Closing out the ticket.
