### ISSUE TITLE
Review UX of downtime messaging and solidify UX patterns

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#6366]
## Review UX of downtime messaging and solidify UX patterns

@artsymartha68 
We currently have standardized messaging text for scheduled and unscheduled downtimes (for public site, in-app, sign on, sitewide vs. single app). However we don't have a clear picture of what the UX and behavior are for each of these scenarios. 

1/ We need an inventory of downtime messaging UX for each of these use cases today, 
2/ Please recommend proposed UX updates/changes if needed, and 
3/ Solidify design system documentation of UX for each of these use cases

**Background:**
Peggy's standardized messaging text: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/4895 (In flight documentation: https://design.va.gov/patterns/messaging-dictionary#system-messaging)

**Sitewide scheduled downtime messaging UX currently:** 
1. In a promo announcement banner - dismissable
2. First advance msg: 12 hours minimum ahead of scheduled downtime
3. Second advance msg: 60 minutes countdown to scheduled downtime
4. Third 'advance' msg: During downtime - message taken down after completion

**Other scenarios - we don't have these documented or know what the UX for these are today:** 
1. Scheduled downtime - Sign in exp
2. Scheduled downtime - apps
3. Unscheduled sitewide 
4.  Unscheduled single app (ex: only Direct Deposit tool is down)
5.  Unscheduled sign in {I think the message just appears in the modal, but not sure if/where documented}
6.  {Others? }

FYSA @AkucherGCIO @peggygannon.

**Comment by artsymartha68** [comment]
@rtwell is going to take a look at this.
