### ISSUE TITLE
Remove any references of va_online_scheduling_required_schedulebale_param feature toggle - (vets-api) 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#63682]
## Description
We no longer need to reference the feature toggle `va_online_scheduling_required_schedulebale_param` in the code. The issue was resolved in July 2023 [(PR #13087)](https://github.com/department-of-veterans-affairs/vets-api/pull/13087). The product team is requesting to remove any references of the feature toggle. 

---

## Acceptance Criteria

- [x] Remove any references of the feature toggle `va_online_scheduling_required_schedulebale_param`
- [ ] Delete the feature toggle `va_online_scheduling_required_schedulebale_param` in [staging](https://staging-api.va.gov/flipper/features/ ) and [production]( https://api.va.gov/flipper/features)
- [x] Changes have been updated in `vets-api`

### Design Assets
N/A

## Definition of Done
- [ ] All acceptance criteria are met
- [x] [Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/product/feature_toggles.md) is updated

**Comment by JunTaoLuo** [comment]
Feature flag removed from all environments.
