### ISSUE TITLE
Product Director links?

### ISSUE THREAD

**Issue by davidconlon** [department-of-veterans-affairs/va.gov-team#63691]
### Description

Links to the "Product Directory" seem to link to a google doc, but should they link to https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory
https://depo-platform-documentation.scrollhelp.site/support/incident-management

**Comment by vbellissimo** [comment]
Hi @davidconlon , thanks for flagging this. We're looking into it for next steps.

**Comment by vbellissimo** [comment]
These updates have been completed and will be closing this now. Thanks again.
