### ISSUE TITLE
Flipper UI access for Derek Fitchett

### ISSUE THREAD

**Issue by dfitchett** [department-of-veterans-affairs/va.gov-team#63705]
### Your Name

Derek Fitchett

### Your GitHub handle (Flipper UI access is managed through GitHub)

@dfitchett

### Team, Role, and Company of the target individual

Employee Experience Team, Software Engineer, Agile 6

### Please confirm if you are on the VFS Team Roster, Platform Team Roster or are a Federal User

- [X] [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [X] Lesser Environments (Dev/Staging/Sandbox)
- [X] Production (if requesting, justify prod access below)

### Reason for Production Access (If requested)

As a member of the Employee Experience Team, I need prod access to toggle features created by our team.

**Comment by ryan-mcneil** [comment]
@dfitchett You've been granted access to all environments
