### ISSUE TITLE
[SW] Staging Review: Design components or patterns don't align with Design System guidelines. (04.07.3)

### ISSUE THREAD

**Issue by HeatherRienks** [department-of-veterans-affairs/va.gov-team#63714]
During the Staging Review on 8/15/23 this launch blocking feedback was provided #63673

### Platform Issue
Design components or patterns don't align with Design System guidelines.

### Issue Details
The review page does not have the edit buttons.

### Link, screenshot or steps to recreate
[Screenshot](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/staging-review-images/57105-Allison-040703.png)

### VA.gov Experience Standard
[Category Number 04, Issue Number 07](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

### Other References
WCAG SC 3.2.4 AA

### Platform Recommendation
Add the edit buttons in each review section and allow users to edit the information they entered. See the [design system](https://design.va.gov/templates/forms/review) for example.

**Comment by HeatherRienks** [comment]
* Per our UX Team, this work will also need to go through the Experimental Design Council

**Comment by HeatherRienks** [comment]
Per @denisecoveyduc - this is no longer launch-blocking. Team is working to resolve ASAP.

**Comment by josephrlee** [comment]
Once we have #60560 done, it will satisfy this ticket.

**Comment by josephrlee** [comment]
This is being worked on now by FE team in #64313

cc: @denisecoveyduc , @Tom-Davis , @mgleo , @HeatherRienks

**Comment by HeatherRienks** [comment]
This will roll into S108 - about 2pts of work left, per Andrew.

**Comment by HeatherRienks** [comment]
Once #64213 is merged by @Dr-Pongo - this can be closed!

**Comment by HeatherRienks** [comment]
@Dr-Pongo will be doing final testing today (10/10) on #64213 and then we can close this ticket.

**Comment by HeatherRienks** [comment]
@Dr-Pongo - is this good to close out now? :)

**Comment by HeatherRienks** [comment]
Work has been completed!
