### ISSUE TITLE
Scheduling Page: Alert Box Update for Columbus + Spokane Patient

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#6372]
Determine UX for what Scheduling page alert box update should be for a patient who is registered at both Columbus + Spokane.

**Acceptance Criteria**
- [ ] For Spokane, users should be directed to schedule appointments in My VA Health + be able to navigate there.
- [ ] For Columbus, users should be directed to schedule appointments using MHV Secure Messaging + receive updates about appointments in My VA Health; be able to navigate there.

**Comment by ambikaroos** [comment]
Encompassed in #5384
