### ISSUE TITLE
SPIKE: Investigate questions and needs from STS and Sign up Service in order to integrate between these and vets-api

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#63725]
Before we can create tickets and plan for Sign up Service integration, we need to figure out exactly how we're planning on doing this from the perspective of `vets-api`, so we need to compile observations, questions, and likely blockers around this.

**Comment by bosawt** [comment]
* What questions do we have for the `Sign Up Service`?
  * Are these all the stacks that you have?
    * SQA - Cerner Namespace
    * PROD - Veteran
    * PROD - Staff
  * Do we at least have a non-Cerner SQA stack?
  * What list of features will we need?
    * We need to query status of current agreement (`accepted`, `denied`, or `no action` yet)
      * `GET /patients/{icn}/status`
        * Authenticated
        * Do we want to use this?
      * `GET /patients/{icn}/status/summary`
        * Un-authenticated
        * Do we want to use this?
    * We need to update `accept` status of current agreement
      * `POST /patients/{icn}/agreements`
    * We need to update `decline` status of current agreement
      * `DELETE /patients/{icn}/agreements`
    * We need a full text of the current terms and conditions
      * Do we want to retrieve this from `Sign Up Service`, or some more ‘hard coded’ scheme in frontend?
      * If we want it from `Sign Up Service`:
        * `GET /terms-and-conditions`

**Comment by bosawt** [comment]
* What questions do we have for the `MAP STS Service`?
  * There is an `SQA` and `Prod` stack, are there other stacks?
  * Is there any way to get a stack that’s accessible outside of the VA network?
    * Otherwise we’ll need to mock with `Betamocks`
  * Are there any concerns about performance with tokens?
    * We will be requesting a token for every single auth, and since ICN is in JWT, we won’t be able to cache for reuse or anything like that
    * Alternatively, there’s a ‘non-authenticated’ way to get agreement status in `Sign Up Service`
      * Perhaps we could get status unauthenticated and only get an authenticated token if we need to make an update?

**Comment by bosawt** [comment]
We will want `vets-api` to have a database that stores veteran ICN, terms and conditions version, and whether user has accepted or denied terms.  If we do this, will we need to `GET` T&U information from Sign up Service? Or will we only have to `POST` changes to them?

**Comment by bosawt** [comment]
Proposed flow is:
- User authenticates on USiP
- `vets-api` checks internal database for `T&U` selection for user
  - If user has accepted `T&U`, continue auth
  - If user has declined `T&U`, show `T&U` page for current terms
  - If user has neither accepted nor declined `T&U`, show `T&U` page for current terms
- Once shown `T&U` page, if user accepts
  - Save accept on local `vets-api` database
  - Make call to `Sign up Service` to associate user with a `T&U` accept
- Once shown `T&U` page, if user declines
  - Save decline on local `vets-api` database
  - Make call to `Sign up Service` to associate user with a `T&U` decline

**Comment by aparsley** [comment]
Keep up the good work
