### ISSUE TITLE
Implement Immediate ITF Fix (show current ITF time)

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#63748]
Currently users are presented with an ITF message when they first start a 526 application and when they continue with an in progress application. This message lets the user know the day their ITF expires but does not currently communicate the time during the day it expires. While we are working towards a fix that will improve the overall experience by changing the time set by the ITF Endpoint we need to implement an immediate fix that communicates whatever time is currently set so that Veterans truly know when their ITF will expire. 

Acceptance criteria:

1. Update message to include the hour and minute the ITF expires as currently calculated by the ITF Endpoint. 
2. Time format should be HH:MM with timezone

**Comment by austinjprice** [comment]
@juliepedtke @nnicholas7 can you add screen shot of "immediate fix" mock as discussed with Shannon here?

**Comment by juliepedtke** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcHNoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a8e4fda76ad19776e7d8eb05f719f10f0ebf7c54/Screenshot%202023-08-21%20at%2010.43.51%20AM.png)

**Comment by austinjprice** [comment]
@micahaspyr to add a screen of staging or production to validate that this is working as expected!
