### ISSUE TITLE
Access for Theo Bentum

### ISSUE THREAD

**Issue by theodur** [department-of-veterans-affairs/va.gov-team#6374]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeff Hayter
- Please provide your name.
   > Theo Bentum
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Name of Team: VSP Tools - Frontend
   > Role: Frontend Engineer
   > Company: Ad Hoc
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Internal%20Tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDOavkYn+IumCdePBHkeUA/V+RIjNhGArsbmVUGwy6MV20ZNc0C2KdZiTqqzfJ/HtwSMJpcinlBFmOoYN4mVIByvcqgekrpTBDa94cV8htC41w3rZVNkrKxVbdvZbhJkiEGuCZE2NOO1AMaihioMeybOJwFeg767YPCBQwmebP9k6ql0AWVam+NarxFjvlJEjqJCE+spRwWxPt9E/i10BBAlVgmZQbxBAL1dW7ayry95t3blxiGqCDUUwW5HtiAByjK9clttumaqI+QdDpyudmK6giQ51J1+gQBGGLipV8mAK94sCFH6ixLJxnqmX/Lzfa8FFEowzTsaQg6tQsa2YQd/wz5NXNUglsOS0IlUoZ2ab9dEmfsJJXpUV5cCK7h4Fu5+y43Oha4IPSqO8LnoY2sz0ijuZfYBRmTZSLgq+gTVLpUQe9c0eDEa7cisVD2O6XKHYEhuG9XPvFK4MGO/AN4cBSYz4RSeb6ARCEH80hJ28lDzGBm6yP+l45TpOWOMraV+ezW0g7RqBGcD4qqKs5o1igDoyFrwSYHDCgGc7hWsZyXs+MWqD+X5M+lHaVZNEfYhpab4UKvwdlSzHDPnhLPtTPhJqxbqIrmZDRphw5IxFRMC7L2Nq4/tk4cs7TsUKrFepyT9uJL0oxJYeaydp34q6j+YNMgB4N/epl8pS4Q3Q== theo@adhocteam.us
```

- [Grant AWS Console access?] NO
  > YES / NO
  >  Please give a brief description for why you are requesting AWS access.

**Comment by theodur** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by ricetj** [comment]
@theodur You have been granted SOCKS access. Please follow the steps to configure.
