### ISSUE TITLE
[UX] 10-10EZR UX Discovery: Come up with a list of EZR "touchpoints"

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#63746]
As a user, I would like to have the ability to find where I can update my information online so that I know I can do it and it's where I expect it to be. 

- [x] Identify all of the touch points where Veterans would look to update their information or look for an EZR
- [x] Use [Luis' GA research](https://docs.google.com/spreadsheets/d/1QemrsFIHkdrdGTa0hDXoISnzE_4OrQOWSIjvUKv2IMI/edit#gid=1971984470) as a baseline for where Veterans are searching for this information (Story #[62399](https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/62399))
- [x] Do desk research/review desk research we've already done 
- [x] Compile a list of "touchpoints" where a Veteran would look to edit their information
- [x] **Success: We identify all of the places we might want to put a link to the form**

**Comment by jessicastump** [comment]
Mural board [started here](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1692890274951/df867bfc9103c8d9bd2e9e334a914cbdcaa11000?sender=uadf1ed7fe7c76f0914967329) - in the process of gathering current found locations on VA.gov and looking through at this from a behavior lens of the ways a Veteran might approach the task

**Comment by jessicastump** [comment]
Wanted to note here and on the Mural board under the form mental model row, the introduction page variation for the **EZ** will also need to be updated as part of this effort.
The [Sketch link here](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/MyZyrxW) for the Introduction Page Variation - Authenticated Version
