### ISSUE TITLE
[BE] 10-10EZR API Discovery: Form questions for Josh F.

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#63745]
As a team member, I would like to understand the capabilities and limitations of VES so that I can build a form for Veterans to update their information online that is as easy to use and close to real time as possible. 

- [ ] Look through API docs and other docs and come up with questions for Faulkner for the entire EZR form
- [ ] Compile questions that have been floating around (e.g. what would autofill require?)
- [ ] Meet with Faulkner
- [ ] Document answers
- [ ] **Success: We get all of our questions answered by Faulkner and they are documented**

**Questions:**

1. If a user is logged in, can we prefill all of the data we have on file for them when they open up the form view?
2. If a user updates their address, how long would it take for it to show up in their profile?
3. If a user updates their financial info, how long would it take for them to be able to view the change (i.e. they open the form up again)?
     - How does the EZR information get reviewed by staff?
     - Is there a systematic trigger/flag?
     - Does/will it go to a queue of sorts?
5. What fields are Required to submit an EZR change? (I know we've asked this before but it might be good to ask again in the light of doing a form)
6. What would happen if a Veteran delete information in a non-required field and not replace it? (e.g. Financial Info, Health Insurance)
     - What happens to the data in ES if:
          - Fields are blank on EZR, but there is data for those fields in ES
          - Fields are blank on EZR and there is no data for those fields in ES
          - Fields have data on EZR prefilled from ES, is changed by Veteran?
          - Fields have data on EZR prefilled from ES, is NOT changed by Veteran?
8. What work are you doing for the PACT Act 103 Toxic Exposure additional questions?
9. What, if any, are the differences between the EZ and EZR when it comes to sending requests to the ES?

**Comment by lihanli** [comment]
can we submit the next of kin and emergency contact fields to the 1010ez api?
