### ISSUE TITLE
SOCKS access for Connor Fewin

### ISSUE THREAD

**Issue by ConnorJeff** [department-of-veterans-affairs/va.gov-team#63764]
### Your Name

Connor Fewin

### Your Email

fewin_connor@bah.com

### Your Role and Team

Software Developer

### Product Manager (PM) name and email

Cat Hughes hughes_catherine@bah.com

### Product Owner (PO) name and email

Matt Self matthewself.dsva@gmail.com

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDQM9VO4FqW8ABDwMcqvvimbbyHYd/P2qn3K9hjeOsQlTcoBK/VjXrVWY6p9HDfDhaTCyAFLBnwTW5hHZHASPZEi0Nq+yApJRSkn5xe54cxpcvdKlamzvKomfJSii6GC46dCM36MjMwJxPa/lamiN8UVQcTVHtxMDrSn7+G1a0IXSK+hJomZer49NbKxV82/jOAjJX5RiMSvoY7eFlAC5BX3vMwEC6Lrhx3ymroRxsPTfpUMFtOcvFYwmHH+8OrTVzjex9idbf0VjNz/tn8PCZvsYmZ0jJhj129O33ON7wqm7VjBgpEu63pUj2pFjmwR9G7eVXS53G1d2zN2GxsjvuiJxzraW3dhQanH2LZoEdFug2QWleDCbanVdzgPWV1/53lqlNjsEBCoS3R9T1aIuoUka/9xAwaMpe7k1gzhkoqbzqRoQ133s0Ad9pObba1LArPvnorSzQctJRK+O/a4U3heu2+wMmedy5IwKAcojAFuJaRIkNADe6MUC4CCweGI9E= connorfewin@T93NH7T6RK

### E-QIP Transmittal Confirmation

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/122034971/1fbcea46-6c6e-49da-9b50-89a4a73eb7f6)

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by ben-allen-oddball** [comment]
Verified merged.  Cleanup.
