### ISSUE TITLE
PM | Hub | KPI / analytics check 

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#63767]
## Background

Determine KPI's for the Profile Hub.

## Tasks: 
- [x] [discuss metrics  w/PO](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/hub/mvp/README.md#measuring-success)

**Comment by Samara-Strauss** [comment]
Acknowledging receipt. I'll need to think more about this next week after my PTO.
