### ISSUE TITLE
EVSS Migration - 526 Submit - Form526BackupSubmissionProcess Discovery

### ISSUE THREAD

**Issue by sethdarragile6** [department-of-veterans-affairs/va.gov-team#63779]
## Issue Description
Within the Form526BackupSubmissionProcess, which resubmits 526EZ and related forms in the event of an error/outage, there are migratable calls to the EVSS Document service (getPDF) and the EVSS submit endpoint. However, without fully understanding the backup submission process, we can not safely just do the usual "create flipper flag + conditional callout to LH/EVSS" at the callout points. The goal of this story is to

1. get a more thorough understanding of the backup submission process
2. come up with some strategies to safely migrate the process

NOTE: migration will _also_ depend on actually implementing calls with the new [Document Upload Service](https://github.com/department-of-veterans-affairs/vets-api/pull/13090/files) to ultimately upload all docs to VBMS. This work was "abstracted" in [#57231](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/57231) but has not been implemented.  

---
## Questions
- [ ] Will we need to call out to our transformation service _at all_ for migration to work?
- [ ] - the code may only need the original request JSON to determine which additional docs need to be resubmitted, in which case it shouldn't matter if that request is in LH or EVSS format
- [ ] - however, calls to getPDF are mysteriously POST requests, so _maybe_ that format is important?
- [ ] Are the LH and EVSS getPDF endpoints getting from the same datasource/database?
- [ ] - if so, it might not be important which getPDF endpoint we're hitting as we're working with the same PDF content
- [ ] - if _not_, it becomes VERY important to know where each individual request first attempted to submit to (LH or EVSS) before the flipper switch was toggled

## Relevant Docs
- [VA.gov 526ez KPIs](https://github.com/department-of-veterans-affairs/va.gov-team/issues/57489#issuecomment-1540202820)
- submission failure handling notes from [lamb duty doc](https://docs.google.com/document/d/1IIRz1og52BRLxkAPmowHJRxX8POlBK1zWt3dtWewTHM/edit#heading=h.dft9uul4fqvq)

## Acceptance Criteria
- [ ] Create documentation (or gather it, if it exists) detailing the backup submission process (a diagram will probably be most helpful)
- [ ] Come up with a plan to migrate these endpoints, considering the answers to the questions above
- [ ] Update [#62170](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/62170) accordingly
- [ ] Does this need to be released to release the submit endpoint?

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by sethdarragile6** [comment]
Here are some important findings on this ticket that relate to our prioritizations:

1. **We should not go to TE until we are 100% migrated to LH on the submit endpoint.** We can't open the front end to toxic exposure and then have to roll back on submit. EVSS will never process these, and so they'll have to remain as dead submissions or otherwise be in limbo until some workaround is scrapped together
2. **We can safely migrate to the submit endpoint before migrating getPDF** If an LH-bound submission fails and goes to the backend submission process, there is nothing to stop it from being safely "submitted" there via the EVSS getPDF endpoint because the request saved to the submission record is already in the EVSS format by default. In short, it gets to its ultimate destination regardless

Given all of the above, I don't believe there are any additional stories to output from this. When the getPDF endpoints are migrated, however, their lighthouse requests will need to be converted to the LH request format on the fly before sending it off to Lighthouse. This should amount to a relatively simple call to our transform service. This should be noted in the Carbs ticket to migrate getPDF, if it exists (if it doesn't, I'll create one)

FYI [here](https://lucid.app/lucidchart/b93a0b4d-c62b-49b0-8efc-c7e9e4a05d1c/edit?viewport_loc=5850%2C610%2C5450%2C2571%2C0_0&invitationId=inv_a7c98577-e6f5-4ec2-897b-3b0f6212b08d) is my working diagram of the whole submission process. it is about 98% complete. It's a bit on the "vast and unwieldy" side, my intent is produce a few screenshots of major chunks of this diagram and put them into a GH wiki page that puts the whole flow into a more generalized context

@RakshindaAslam @aurora-a-k-a-lightning @SamStuckey @NB28VT

**Comment by RakshindaAslam** [comment]
Thanks for the detailed summary @sethdarragile6! A thing to note is that we are doing /getPDF migration and have a ticket on our board and team 2 is doing document services. Let me know if that changes anything.

**Comment by sethdarragile6** [comment]
Discovery doc created [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/evss-to-lighthouse-migration/526-backup-submission-discovery.md)
