### ISSUE TITLE
Create 'onboarding' public docs directory with backend, frontend, devops 'new hire' projects

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#63774]
Right now only a 'backend' project has been written, so this should be put in a place that's at least fairly publicly accessible by new hires:
https://app.zenhub.com/workspaces/identity-5f5bab705a94c9001ba33734/issues/gh/department-of-veterans-affairs/va.gov-team/63186

Additionally we should create a similar document for new frontend engineers and new devops engineers

**Comment by parkerbees** [comment]
Moved to Jira. Closing.
