### ISSUE TITLE
IA Request Medical Device Reordering 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#6378]
What this is: Work with VSP Information Architecture experts to finalize the IA of your product for VA.gov

When to use this: After completion of usability/protyping, prior to moving to development

## Required Inputs:
- Link to product outline https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/medical-device-tool
- Link to or attach prototype or mockups https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/medical-device-tool/design and https://vsateams.invisionapp.com/share/6MVTG94WNH5#/screens 
- Link to research readout/results https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/research/usability-march20/research-readout.md
- Link to [reseach history masterlist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-history.md) showing that you have added your research to the list as applicable
- Link to or attach final content including H1s (if separate from prototype/mockup)

## Information Architecture Worksheet (Optional)

Provide the following information, as available, to support the final information architecture of your product.

**SEO Keywords**
- Enter a list of keywords used by your target audience when they talk about or search for your content

**Proposed site map/page structure** (if more than one page)
- Provide link or image of proposed page structure

**Suggested URL(s)**
- Provide suggested URLs and any background or rationale

**Suggested entry points**
- What is the primary entry point for users to find your new content/tool - consider benefit hub pages, top nav, left nav, footer, profile/account, home page, etc.

**Crosslinking opportunities**
- What additional related areas of the site would links to your content/tool be helpful?

**Redirects/canonical tags**
- Will existing pages/tools need to be redirected or canonicalized?

## Definition of Done
- [x] Issue is created, tagged and assigned to Content and IA team
- [x] Required information above is complete and optional information provided where available
- [x] IA reviews information and provides final feedback/recommendation on ticket
- [ ] Requesting team closes issue upon implementation
- [ ] Requesting team member complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

**Comment by mnorthuis** [comment]
@leahkeeler per our slack conversation, the IA won't be complete until the research is complete. Once you have synthesis, please link to it in this ticket.  Thank you!

**Comment by leahkeeler** [comment]
Hi Mikki, Usability is complete - link above and also here https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/research/usability-march20/research-readout.md. 

Thanks! Leah

**Comment by mnorthuis** [comment]
Thank you @leahkeeler, I will start working on this!

**Comment by mnorthuis** [comment]
@leahkeeler Can you provide answers to these questions:
- Is the Veteran required to have health care benefits to utilize the order form?  I believe the current content states that, but wanted to be sure. 
- If the above is true, I am assuming the user actually has to be signed in to use the order form, correct?

**Comment by leahkeeler** [comment]
Hi MIkki, 

The Veteran has to have a prescription from an audiologist for hearing aids in order to be able to order batteries and accessories. If they do not, they are directed to contact the DLC 

the veteran does need to be signed in, when they sign in and authenticate and API  call retrieves the items they are eligible to order. If they are eligible for the items but no eligible based on 6 month supply window, they get a message letting them know the date they are eligible. 

Please let me know if you have any other questions. 

Thanks, Leah

**Comment by mnorthuis** [comment]
Thanks for the above info @leahbannon 

Here is the final IA work: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/bam2-med-device-order.md

Please let me know if you have any questions or want to go through this together.  Much of this information will be needed by the Public Websites team for implementing the static/unauthenticated content work.   

You are welcome to close this issue at your discretion.
