### ISSUE TITLE
Vets-api terminal access for Kenneth Santiago

### ISSUE THREAD

**Issue by ksantiagoBAH** [department-of-veterans-affairs/va.gov-team#63786]
### Your Name

Kenneth Santiago

### Your GitHub handle (terminal access is managed through GitHub)

@ksantiagoBAH

### Team, Role, and Company of the target individual

MBS (Memorials benefits system), Tech Lead, Booz Allen Hamilton

### Product Manager (PM) name and email

Cat Hughes hughes_catherine@bah.com

### Product Owner (PO) name and email

Rhonda Jones rhonda.jones1@va.gov

### COR Name (leave "None" if you listed an AWS user name above)

None

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

None

### Please confirm if you are on the VFS Team Roster or Platform Team Roster

- [X] [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Please confirm E-QIP Transmittal/Adjudication. This could be a screenshot of your Transmittal/Adjudication email, a link to another request where you've submitted this proof (i.e. AWS/SOCKS), etc.

- [X] I have attached proof that I have either transmitted my E-QIP survey or previously received a favorable decision (by including in "Additional Notes" section below)

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [x] production (if requesting, justify prod access in 'Additional Notes' section)

### Additional Notes

I need prod access to remediate form that have failed in the form submissions table. Prod accessed would be used to run a rake task.

![Screenshot 2023-08-16 at 2 08 39 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/50601724/31761e7c-d03e-4d00-9b0b-73ef0bc15932)

### Additional resources for Support Engineer

- [ ] For users on a VFS team but not in the VFS Team Roster, they must start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] Instructions for handling requests [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access) - Support Only

**Comment by bdech** [comment]
Found in VFS Team Roster

**Comment by bdech** [comment]
@ksantiagoBAH You’ve been granted access to the 'dev', 'staging', and 'sandbox' environments.

Here's some additional documentation for the [Vets API on EKS](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-TerminalAccess)

**Comment by ksantiagoBAH** [comment]
Thank you

**Comment by bdech** [comment]
Access to `prod` is pending approval by OCTODE, and we'll update you as soon as it's available.

**Comment by JonathanKamensDVA** [comment]
>### Team, Role, and Company of the target individual
>
>Booz Allen Hamilton

Please provide your team and role as indicated in the form and then put the "Awaiting Approval" tag back on the issue when you have done that.

**Comment by JonathanKamensDVA** [comment]
Approved.

**Comment by bdech** [comment]
Support slack reminder [here](https://dsva.slack.com/archives/C06CY71PCAX/p1733332991292259)

**Comment by bdech** [comment]
@ksantiagoBAH Your Vets API Terminal Production access has expired.

Would you like to request an extension? You have 72 hours to respond, or your access will be revoked and you will need to fill out a new request.

**Comment by bdech** [comment]
@LindseySaari @ericboehs can one of you please give us a :thumbsup: to extend their access?

**Comment by bdech** [comment]
support slack reminder [here](https://dsva.slack.com/archives/C06CY71PCAX/p1749136449635729)
