### ISSUE TITLE
[Design] 10-10EZR - Standalone form: Intro page Design

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#63797]
## Background
Now that the decision has been made to build a standalone 10-10EZR form, we need to design an Introduction page that informs the Veteran how they can fill out the form (online, download) and why.

**Things to consider**
- Do we need an Intro page?
    - Need OMB, PRA language
    - Intro page is standard on VA
- If so, What information should be included on it?
- How do we leverage the existing landing page to lead into our form?
     - Existing landing page (in staging) - https://staging.va.gov/health-care/update-health-information/
- What are we missing/forgetting?

## Tasks
- [x] Design Intro page
     - Include How Veterans can fill out the form, why they should fill it out and what info they need to fill it out, OMB number, time burden, PRA stuff, Need Help footer
- [ ] Review with the team/PO/PM

## Acceptance Criteria
- Intro page design is created and shared with the team

**Comment by jessicastump** [comment]
- [Sketch page](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/p/2D0EB0C7-1AAA-4803-A927-7A980EF8D5E8/canvas) - intro page v1

**Comment by jessicastump** [comment]
[Sketch page link moved to here](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/p/34F1F294-5E1D-46C1-ADE6-AC6C398E2130/canvas) for mvp version after discussion on Friday 9/1.

**Comment by jessicastump** [comment]
Adding [a link to the corresponding content ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65056#event-10299648879)

**Comment by jessicastump** [comment]
An update/current after some iterations:

1. We don't have to use the process list / subway map (1-2-3) component on the intro page. There was a concern it might be a design system constraint but it is not, we can use the updated v3 based template that does not use the process component and starts with the h2 "what to know before you fill out this form"
2. Looking at 4 alert states for this page that is mostly new content: 1- Not yet signed in, 2. Signed in and enrolled status, 3. Signed in and not enrolled status, 4. Form saved in progress
3. [Sketch file has been updated](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/p/34F1F294-5E1D-46C1-ADE6-AC6C398E2130/canvas)
4. Attending Platform design office hours on Sept. 19th to chat about v3 components and alerts
5.  @aliyahblackmore - I know you have a content ticket version of this page/content work, but tagging you here too

**Comment by jessicastump** [comment]
An update/current after some iterations:

1. We don't have to use the process list / subway map (1-2-3) component on the intro page. There was a concern it might be a design system constraint but it is not, we can use the updated v3 based template that does not use the process component and starts with the h2 "what to know before you fill out this form"
2. Looking at 4 alert states for this page that is mostly new content: 1- Not yet signed in, 2. Signed in and enrolled status, 3. Signed in and not enrolled status, 4. Form saved in progress
3. [Sketch file has been updated](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/p/34F1F294-5E1D-46C1-ADE6-AC6C398E2130/canvas)
4. Attending Platform design office hours on Sept. 19th to chat about v3 components and alerts
5.  @aliyahblackmore - I know you have a content ticket version of this page/content work, but tagging you here too

**Comment by jessicastump** [comment]
An update/current after some iterations:

1. We don't have to use the process list / subway map (1-2-3) component on the intro page. There was a concern it might be a design system constraint but it is not, we can use the updated v3 based template that does not use the process component and starts with the h2 "what to know before you fill out this form"
2. Looking at 4 alert states for this page that is mostly new content: 1- Not yet signed in, 2. Signed in and enrolled status, 3. Signed in and not enrolled status, 4. Form saved in progress
3. [Sketch file has been updated](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/p/34F1F294-5E1D-46C1-ADE6-AC6C398E2130/canvas)
4. Attending Platform design office hours on Sept. 19th to chat about v3 components and alerts
5.  @aliyahblackmore - I know you have a content ticket version of this page/content work, but tagging you here too

**Comment by jessicastump** [comment]
We received some content feedback on the intro page. Updated links below.

- [Static page](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/a/P19en1P) (CAIA will handle these updates/this is the drupal page)

**Introduction page and alert states**
1. Not yet signed in, [Sketch link desktop](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/a/w5wn5kV) and [Sketch link mobile](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/a/qb9nbmd) 
2. Signed in and enrolled in VA health care status,  [Sketch link desktop](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/a/pYAwLrZ) and [Sketch link mobile](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/a/715M1Yw) 
3. Signed in and not enrolled status,  [Sketch link desktop](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/a/oM129z3) and [Sketch link mobile](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/a/DE034Dk) 
4. Form saved in progress [Sketch link desktop](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/a/x0yGbWJ) and [Sketch link mobile](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/a/j4o5VYG)

**Comment by jessicastump** [comment]
Content has been updated with the draft provided. Closing ticket and will tag development ticket.
