### ISSUE TITLE
Project Kickoff [Appeal Modernization Process (AMA) Follow Up Changes]

### ISSUE THREAD

**Issue by AkucherGCIO** [department-of-veterans-affairs/va.gov-team#6380]
## Steps to complete Project Kickoff
- [x] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in #vfs-platform-support in Slack; tag @ Megan Kelley @ AndreaHewitt
- [x] Andrea and Megan will schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [ ] VSP <> **requesting team** kickoff meeting completed
- [ ] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please bring the following to the kickoff meeting_
- Link to rough draft of product outline (https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/AMA%20Follow%20Up/AMA%20Follow%20Up%20Product%20Outline.md))

## Meeting attendees from **requesting team**
- Product Manager (required): **Aruna Kucherlapati**
- DEPO Product Lead (required): **Jennifer Lee**
- Entire VFS team (recommended): **Nick Sullivan, Aruna Kucherlapati, Kevin Walsh, Kevin Stachura, Laura Walsh**

## Scheduling
Preferred dates or times:

**Comment by meganhkelley** [comment]
Removing Mikki and Peggy from your "entire VFS team" list, as they are not on Public Websites but are members of VSP (my team in fact! 😎). That being said they will be present for this Project Kickoff as members of VSP. 👍

**Comment by andreahewitt-odd** [comment]
Schedule for 3/5 at 1:30 ET

**Comment by sshein** [comment]
Hi there - @lwalsh617 as I mentioned feel free to reach out to me as you're determining how to deal with the new requirements to change the wording to "decision review" from "appeal" - I had to do something like this when I worked on the Quality Payment Program and we had some "bridge language" the first year of the change

**Comment by mnorthuis** [comment]
High-level list of IA elements to be considered:
- Entry point placement - links exist within disability only currently
- Entry point labeling - "appeals" vs "decision review"
- Structure/IA of Decision Review content pages
- Placement of File an Appeal pages within IA
- Left nav implementation within Decision Review content area
- Content updates that result in changes to content page context, structure or location will impact IA
- CTA labeling/consistency - i.e. "File an Appeal" vs "Request Decision review"
- Claim and appeal status tool - review of content and labeling
- Design elements potentially needed for IA components: Left nav topper 

Additional items may be uncovered during discovery work.
