### ISSUE TITLE
Apply for burial benefits page is missing the nav element + breadcrumbs

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#6381]
## What happened?
The [apply for burial benefits page](https://www.va.gov/burials-and-memorials/application/530/introduction) is missing the `nav` element, which means it's also missing it's breadcrumbs
![image](https://user-images.githubusercontent.com/55992116/75731193-01faa800-5cbd-11ea-9072-1dc9f42092c3.png)

## Specs:
- Device: Macbook
- Browser: Chrome

## Steps to Reproduce
- Visit the [apply for burial benefits page](https://www.va.gov/burials-and-memorials/application/530/introduction).
- Compare with other apply pages such as [Pension benefits](https://www.va.gov/pension/application/527EZ/introduction), or [education benefits](https://www.va.gov/education/apply-for-education-benefits/application/1990/introduction)

## Desired behavior
I would expect the page to have 

- the `nav` element and breadcrumbs (either `Home` >  `Burials and memorials` > `Burial allowance` > `Apply for burial benefits` or  `Home` >  `Burials and memorials` > `Apply for burial benefits`), OR 
- that the `h1` have some additional visual breathing room to keep it in line with where the breadcrumbs sit on the page (~ 36px)

## Acceptance Criteria
- [ ] the page has the `nav` element and breadcrumbs  OR
- [ ] the h1 has increased padding to give it some breathing room from the main navigation

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by ncksllvn** [comment]
Hey @AkucherGCIO, this is a simple one, so I'm gonna go ahead and knock it out real quick. Can you add it to our current sprint?

**Comment by AkucherGCIO** [comment]
@ncksllvn - It's added to the Sprint.

**Comment by ncksllvn** [comment]
Merged! @andaleliz should be in staging in about 30 mins if you're interested in sweeping through the forms and apps to make sure they're okay.

**Comment by ncksllvn** [comment]
In working on this, I discovered some weirdness with some other React apps, where the content was outdated or the breadcrumbs just not completely accurate to the page path, so I corrected those too. In total, the breadcrumbs for these apps/pages should be corrected -

1. /burials-and-memorials/application/530
1. /education/opt-out-information-sharing/opt-out-form-0993
1. /education/about-gi-bill-benefits/how-to-use-benefits/vettec-high-tech-program/apply-for-vettec-form-22-0994
1. /education/apply-for-education-benefits/application/1990
1. /education/apply-for-education-benefits/application/1990E
1. /education/apply-for-education-benefits/application/1990N
1. /education/apply-for-education-benefits/application/1995
1. /education/apply-for-education-benefits/application/549
1. /health-care/apply/application
1. /pension/application/527EZ
1. /records/get-veteran-id-cards/apply

**Comment by ncksllvn** [comment]
If someone can double check the breadcrumbs for accuracy on those pages on staging.va.gov, then I think we can close this.

**Comment by andaleliz** [comment]
@ncksllvn I feel compelled to respond since I opened this ticket, but I don't believe I'm the best person to confirm the breadcrumbs across all of these pages are accurate. Would a content or IA resource be the right person?

**Comment by ncksllvn** [comment]
For the purposes of this issue, I think just a check for general accuracy (no outright problems)  would be enough

**Comment by andaleliz** [comment]
RIght, but I think you need to ping Mikki if you're concerned about the accuracy of the breadcrumb path, or Peggy if you're concerned about the language. 

I looked at the first few, [this one](https://staging.va.gov/education/opt-out-information-sharing/opt-out-form-0993/claimant-information) seems off to me  because the h1 doesn't match the breadcrumb 1:1.  It doesn't have the exact same language or casing.  But I don't know if it does 100% of the time...  I feel like it should but our content and IA experts would be the authority on that.

**Comment by ncksllvn** [comment]
Okay, thanks. I messaged on Slack about this, https://dsva.slack.com/archives/C52CL1PKQ/p1583353572407200. I'm afraid of this ticket turning into ground for just anything breadcrumbs, so I'm going to close. My main concern was the Burials form not having _any_ breadcrumbs, affecting the style of the page, which is fixed now. Closing this out.

**Comment by ncksllvn** [comment]
Follow-up ticket for confirming breadcrumb accuracy, https://github.com/department-of-veterans-affairs/va.gov-team/issues/6582
