### ISSUE TITLE
[Design] 10-10EZR - Standalone form: Confirmation page design

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#63827]
## Background
Now that the decision has been made to build a standalone 10-10EZR form, we need to design the Confirmation page after the form has been submitted.

## Tasks
- [x] Design the Confirmation page
     - Include an option to print the confirmation page
- [x] Review with the team/PO/PM

## Acceptance Criteria
- Confirmation page designs are created and shared with the team

**Comment by IMHieuVo** [comment]
The UX team decided the Print Option will be on V2 instead.

[Sketch Link](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/p/5832D810-94E4-48FE-A8F1-A142424BA072/canvas).

**Comment by hdjustice** [comment]
Hi @IMHieuVo - Can you tell me what "print option" you are referring to?

**Comment by IMHieuVo** [comment]
@hdjustice  There are at least two flows for the confirmation page:
1) For a successful submission, the Veteran can simply print the confirmation page.
2) For unsuccessful submission, the Veteran can print what they already filled out and send it through mail. This Print Option requires some backend work to pull data and put it on the PDF.

**Comment by hdjustice** [comment]
Ok so are we keeping the Print confirmation, but not Print completed form?

**Comment by IMHieuVo** [comment]
That is correct.

**Comment by longmd** [comment]
@IMHieuVo , just coming across this and there are some things that will be omitted or changed. 

1. There is no unsuccessful confirmation screen. If the submission fails, you never leave the review page, so you may want/need to revisit that alert content to make sense on the review page.
2. There is no confirmation number for successful submissions

**Comment by IMHieuVo** [comment]
@longmd 

1. I noticed there was a [GitHub ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/45667) and [mockup](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/v/gyyaRk/p/80CE9C5F-F2DC-44EB-BF50-C5D9865D2E18/canvas?posX=-3411.8453526304615&posY=-260.4462227290769&zoom=0.40265241265296936) around the Unsuccessful Confirmation screen for 10-10EZ. This was not implemented for the 10-10EZ?  I'll look into incorporating the alert into the Review page instead.

2. I'll update the successful submissions mock to omit the Confirmation Number.

**Comment by longmd** [comment]
@IMHieuVo , yea, Nick wasn't aware that you don't go to a failed "confirmation" page. On failure, the submit button on the Review page basically is removed and that alert that you have from the GitHub ticket is what gets rendered in it's place.
