### ISSUE TITLE
[Design] 10-10EZR - Standalone form: Review & Submit page design

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#63826]
## Background
Now that the decision has been made to build a standalone 10-10EZR form, we need to design the Review page that will display all the fields and data input for the Veteran to review, disclosure verbiage for Consent to Copay, Assignment of Benefits, and statement of truth.  We must also include a submission button that will trigger a transmission of the data input to Enrollment system.

## Tasks
- [x] Design the Review page
- [x] Review with the team/PO/PM

## Acceptance Criteria
- Review page designs are created and shared with the team

**Comment by IMHieuVo** [comment]
[Sketch Link](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/p/AE6DF9B2-59AA-47A8-A038-DD8F238C92DB/canvas)
