### ISSUE TITLE
draft September email content - Reactivation

### ISSUE THREAD

**Issue by djmunoz1** [department-of-veterans-affairs/va.gov-team#63835]
As a Veteran I want to receive another message from VA encouraging me to sign in with my login.gov or ID.me so that I am prepared for changes to VA sign in options.

ACCEPTANCE:
- borrows from final (August) content from reactivation segment
- language is updated so that the message and urgency is relatively the same 
- August and September language should not be carbon copies since veterans will be seeing this message for a second time
- 
DEF OF DONE:
-draft added to content folder and internally reviewed (UX Lead, PM); ensure internal alignment before sending to VHA-MHV-VA.gov Communications Group

**Comment by CarlDickerson** [comment]
Draft completed and reviewed internally. Draft has been moved back to "in-progress content" folder following new Unified Comms approval process. We have submitted previous (August) Reactivation email content for review and will hold off sharing this content with reviews until we have feedback from final August emails (on which these are based). Draft content can be found here: https://docs.google.com/document/d/1J_wj0n8hbDQlyHrM6gneTjbwWiaKkMxaLfbp_7z4C9s/edit
