### ISSUE TITLE
VAOS - use account_id instead of user_uuid

### ISSUE THREAD

**Issue by saneshark** [department-of-veterans-affairs/va.gov-team#6383]
user_uuid is going to be deprecated and we should look at using the account_id instead for redis key, as part of that effort, I strongly advise that we put the account_id in an X-internal-id header of some sort via middleware. In fact maybe this should be part of common/client anytime the user context is known.

**Comment by lenaecb** [comment]
@saneshark - when is this getting deprecated? as part of the SSOe work?

**Comment by saneshark** [comment]
Yes. It's a very minor fix and should probably have launch blocker label. As it will be more difficult to do after we've launched. Can be done before SSOe changes are in effect.

**Comment by saneshark** [comment]
If we did it after launch, any users with open sessions might run into some minor issues, but I don't think it would be a problem either... just safer to do before launch i would think. It has to do with the session we create in VAMF not the session created signing in to VA.gov -- so not a HUGE deal either way, but better to do before launch.

**Comment by kreek** [comment]
PR https://github.com/department-of-veterans-affairs/vets-api/pull/3999
