### ISSUE TITLE
Platform Codeowners: Add Datadog APM

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#63845]
## Description:
We need to integrate Datadog Application Performance Monitoring (APM) into our Codeowners Rails application. This will help us to gain insights into the performance of the app, trace requests from end-to-end, and troubleshoot issues more effectively.

## Acceptance Criteria:

- [x] Datadog APM is integrated into the Codeowners Rails application
- [x] APM data is visible in our Datadog dashboard
- [x]  Necessary documentation is updated to reflect the changes

Action Items:
- [x] Set Up Datadog Account and Access

 Confirm that we have a Datadog account and that the necessary team members have access.
- [x] Retrieve the Datadog API key and Application Key. (agent is already set up)

 Install the Datadog Agent on servers where the Codeowners app is running.
- [x]  Configure the Agent with the API key.
- [x] Install Datadog APM Ruby Gem

- [x] Add the ddtrace gem to the Gemfile.
- [x]  Run bundle install to install the gem.
- [x] Configure the Datadog.configure block in an initializer (e.g., config/initializers/datadog.rb).
- [x]  Configure APM for Rails (see Vets API setup)

- [x]  Inside the Datadog.configure block, enable and configure the Rails integration.
- [x] Test in a development or staging environment to ensure traces are sent to Datadog.
- [x]  Tune APM Settings (if necessary)

 Review and adjust sampling rates, if necessary.
- [x]  Set up meaningful tags and environment names in the APM traces.
- [x] Update Documentation

- [x] Update the internal documentation with steps on how the Datadog APM integration was set up.
- [ ]  Include information on where to find data in the Datadog dashboard and how to use it.

Additional Notes:
Be mindful of the security implications and ensure that sensitive data is not being sent to Datadog.

**Comment by laineymajor** [comment]
Will start today.

**Comment by RachalCassity** [comment]
[Platform Atas PR](https://github.com/department-of-veterans-affairs/platform-atlas/pull/218) Merged.
[Manifest PR](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/2409/files) awaiting approval.

**Comment by RachalCassity** [comment]
Platform APM documentation: https://vfs.atlassian.net/wiki/spaces/TT1/pages/2840494149/Datadog+APM+Integration+with+Rails+App+in+ArgoCD+EKS

**Comment by laineymajor** [comment]
Lindsey reviewed and approved
