### ISSUE TITLE
Update mocked authentication view template in vets-api

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#63841]
## Description
Update the Mocked Authentication UI to add additional information in the Mocked Profile dropdown and code view to include whether an MPI record is mocked or not

## Tasks
- [x] Update the `mocked_authentication/credential/index.html.erb` file to include the new `mpi_mock_exists` property

**Comment by aparsley** [comment]
Is this set up to be monitored yet or does this need to be completed?
