### ISSUE TITLE
confirm IPP design system

### ISSUE THREAD

**Issue by djmunoz1** [department-of-veterans-affairs/va.gov-team#63864]
Code repository for [LG design system](https://github.com/18F/identity-design-system).

Design guidelines for partners also exist at: <update with link>

However, AFAICT it unlike USWDS, there's not a hosted site along with Figma/Sketch controls that can be incorporated into mockups.

- get familiar with login.gov design system
- 

DEF OF DONE:
- confirm whether login.gov or VA.gov design system will be used

**Comment by porta-antiporta** [comment]
Confirmed from Login.gov that they no longer have a public link that hosts / renders their design system. The [github repo](https://github.com/18F/identity-design-system) is what is available.

Sync'd with @skirkman16 on this topic and the preference is to use the Login.gov design system for the intake portions of the process to minimize the back and forth for a Veteran from going from a Login.gov experience to a VA experience for filling out intake.

She is going to check to confirm she can use the instructions in the readme for the Login.gov design system to complete the mockups for intake.

**Comment by skirkman16** [comment]
Porta sent me a link to [Login.gov's design system ](https://github.com/18F/identity-design-system)which is an extension of the USWDS. I will continue to review the documentation and experiment with applying the design system to the landing page tomorrow.
