### ISSUE TITLE
PROD:  VVC on VA device display as VVC@Home.  Should display as VVC on VA Device

### ISSUE THREAD

**Issue by JRRoof** [department-of-veterans-affairs/va.gov-team#63865]
## Description
The MOBILE_GFE appointment kind that is returned from VVS has been deprecated and should no longer be used to determine if an appointment is VA `Video Connect on VA Device` or `VA Video Connect at Home`. Instead, VVS now returns MOBILE_ANY as the kind along with a boolean called patientHasMobileGfe. This combination of kind + boolean is what should be used to determine what type of video connect appointment should be displayed.

vaos-service is going to start returning a new extension: `Appointment.extension.patientHasMobileGfe` which maps this new boolean value. The front end will need to look at the `Appointment.telehealth.vvsKind` to see if it's MOBILE_ANY/ADHOC and then look at the `Appointment.extension.patientHasMobileGfe` to see if it's true. If we have (MOBILE_ANY/ADHOC)/true then it will be a "VA Video Connect on VA Device" appointment, but if it's (MOBILE_ANY/ADHOC)/false then it would be "VA Video Connect at Home".

---

## Acceptance Criteria

Given a veteran viewing appointments online
When `Appointment.telehealth.vvsKind` is MOBILE_ANY and `Appointment.extension.patientHasMobileGfe` is true
Then appointment modality should display as "VA Video Connect on VA Device"

Given a veteran viewing appointments online
When `Appointment.telehealth.vvsKind` is MOBILE_ANY and `Appointment.extension.patientHasMobileGfe` is false
Then appointment modality should display as "VA Video Connect at Home"

### Design Assets
All spec copy is FPO. Use copy in copy doc.

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by ldelacosta** [comment]
@young1205 - please notify @JRRoof when the ticket is ready.

**Comment by ldelacosta** [comment]
@JRRoof - if you can validate and make sure the changes are good.

**Comment by marcynadeau** [comment]
[VVC_VA_Device_VAOSR6958.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ0I0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--de315064e8146786aefeac0d4d498b562de028b4/VVC_VA_Device_VAOSR6958.docx)

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket.
