### ISSUE TITLE
Analytics Implementation or QA Support for Ask VA

### ISSUE THREAD

**Issue by beckyphung** [department-of-veterans-affairs/va.gov-team#63860]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

</div>
</details>

### Required
- **Is this request for **Google Analytics implementation** or **QA**?**

     - [x] Google Analytics implementation
     - [ ] QA

- **Who is this request for?**

    - Ask VA integration team 
    
    
- **Provide the link(s) for Google Analytics implementation or QA**
  
    - https://ask.va.gov/
    
- **When is the launch date?**
    - Ask VA is currently in production outside of VA.gov in a separate Portal. Michelle Dooley noted it’s not being tracked in Google Analytics right now ([see Slack thread](https://dsva.slack.com/archives/CBU0KDSB1/p1690385956681789)). Our work will involve moving Ask VA to VA.gov. We want to start tracking as soon as we’re able to set this up because we need to understand current referrals to the current Ask VA site at ask.va.gov.

- **What interactions need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked_
    
    - Clicks to ask.va.gov from VA.gov (For example, the Ask VA link on the [Contact Us page](https://www.va.gov/contact-us/#contact-us-online-through-ask-))
    - Clicks to ask.va.gov from non-VA.gov sources
    - 8/30 Update: Clicks on `Submit` button on "Review your Information" page

### Optional
- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - n/a

- **Any additional comments**

    - 8/30 Update: We'd like to also understand the % of of users that complete the journey to submit their inquiry. We added another interaction to track above.
    - Ultimately, we want to understand referrals to ask.va.gov. Please let us know if these are the right interactions to ask for, or if you can provide further guidance on the best way to answer this question of referrals to ask.va.gov. Thank you!

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by ChristineYoungZA** [comment]
@michelle-dooley please assist here.

**Comment by michelle-dooley** [comment]
We will review and get back to you with timing.

**Comment by beckyphung** [comment]
@michelle-dooley Hi Michelle! Do you have an update on timing?

**Comment by beckyphung** [comment]
@michelle-dooley Just wanted to let you know that we've added an additional interaction to track, since we also want to understand the % of users who successfully complete the journey of submitting an inquiry on Ask VA.

**Comment by jestutt** [comment]
@beckyphung To get started, we need to have GTM installed on all pages of the ask.va.gov website. This might be a reusable component that can be carried over from the www.va.gov site. If it's not, here are the [implementation instructions by environment](https://docs.google.com/document/d/1DysO9vpWgAdpDXX3c6SChfZLtYRXd0-mStv0pxopgfY/edit?usp=sharing). 

Let me know once this is done.

**Comment by beckyphung** [comment]
@jestutt Thanks for this info. Could you add the folks below to that doc? I couldn't access it with that link: 
- becky.phung@va.gov; ruchi.shah@thoughtworks.com; jacob@docme360.com; joe.hall@thoughtworks.com; khoa.nguyen@oddball.io; eddie.otero@oddball.io

@joehall-tw - Could you or someone on the Engineering team look into installing Google Tag Manager on all ask.va.gov pages after confirming that you can open that doc too? Thank you!

Sidenote: Mikki Northius helped set up [outbound clicks from VA.gov to Ask VA](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20230907&_u.date01=20230907&explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.eventAction%22,%22PT%22,%22outbound%20link%20clicked:%20https:~2F~2Fask%22,0%5D%5D&explorer-table.secSegmentId=analytics.pagePath&explorer-table.rowStart=0&explorer-table.rowCount=100&_r.drilldown=analytics.eventCategory:Interactions/) in the Universal Analytics property. This helps with the `Clicks to ask.va.gov from VA.gov` interaction we have outlined above. But we still need need to understand the entire pathway/other interactions.

**Comment by beckyphung** [comment]
@jestutt Thank you for sharing the updated link. @joehall-tw Could you address the technical question re: updating the code for tracking? 

Since this form contains a lot of conditional log, we're working on mapping the flow for each category in [this open Mural folder](https://app.mural.co/t/departmentofveteransaffairs9999/r/1686859097688?folderUuid=01d6b9c9-6118-42cd-9bb7-e4562713b786).

**Comment by beckyphung** [comment]
@jestutt and @michelle-dooley We're going to need to work with our VA partners to add this code to ask.va.gov. But we have more questions around exactly what they or we need to do, and if their emails need to get added to analytics.google.com to do this work. Could we have a quick meeting to go over how this works, especially since they haven't had experience with GA before? I'll send a calendar invite, and let me know if this time will work for you.

**Comment by beckyphung** [comment]
Michelle replied to my message via Slack - noted there are office hours we can attend, so I'll let our team know they can come then. And I shared the code snippet doc with them.
