### ISSUE TITLE
VSO Discovery for Campaign support

### ISSUE THREAD

**Issue by djmunoz1** [department-of-veterans-affairs/va.gov-team#63870]
As a VSO I want to receive guidance so that I can coach Veterans through the creation and adoption of modern login credentials.

ACCEPTANCE:
- meet with Matt Self and document takeaways
- identify VSO contacts

DEF OF DONE:
- create concept doc to pitch to PO

**Comment by MOStudioCarolyn** [comment]
Discovery notes captured in [Mural](https://app.mural.co/t/innovationboards1199/m/innovationboards1199/1692888352486/f40898c7205139c669ebe72c5c360aaf8fd64479?sender=u1e2c263656ad89ecadb41603)
Next step: meet with Kimberly Mitchell (VSO Liaison) and others from VBA
