### ISSUE TITLE
engage PO on 6150 directive updates

### ISSUE THREAD

**Issue by djmunoz1** [department-of-veterans-affairs/va.gov-team#63874]
# Use Case

As VA, I want clear guidance as to what document types and authoritative sources exist for identity verification so that our agency can be supportive of in person proofing.

# Context

During the IPP workshop, NIST had recommended to review and amend identity policies at VA so that it's clear that MHV and VHIC, systems and cards used for adjudicating benefits to Veterans, can be used for identity as well.

# Acceptance criteria
- [x] Review 6510 draft guidance
- [x] Provide recommendations for change that are supportive of IPP

**Comment by porta-antiporta** [comment]
Received access from Tom to 6510 draft policy and identity handbook. In process of reviewing

**Comment by porta-antiporta** [comment]
After reviewing both the 6510 [directive] and the [handbook], much of what is needed seems to be already covered from a procedural perspective. The next step for IPP is to write some of the acceptance statements and put forth in front of the system owner for acceptance.
In particular:
* System DIRA (though this is a bit in reverse. Typically, based on a systems needs an assurance level is specified. In our case, we're specifying an assurance level and showing how our system meets it)
* Digital Identity Acceptance Statement - writing out how we will leverage MPI and why that meets NIST is the key.
