### ISSUE TITLE
BE: Block redirect to Cerner if user is not eligible

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#63878]
VA.gov will interrupt  the user auth flow on the callback which detects if a user is Cerner eligible. 
- If they are not eligible, we will send them to an error page which says they are not Cerner eligible and tells them they can try to use MHV.
- we need another error page, or find the one we already have.

As an external user who is not Cerner eligible, I have logged into an SSOe enabled web application, I then manually go to https://patientportal.myhealth.va.gov/, I should be redirected to an error page (hosted within va.gov) that states I am not eligible for Cerner and should try myhealthevet if I believe I should have access to VA healthcare. I should not be logged out.

There is a dependency on the frontend to complete this work.

**Comment by bosawt** [comment]
As of now we won't make calls to Cerner during our auth flow (we will rely on SSOe doing this during their 'second' Cerner auth)

**Comment by joeniquette** [comment]
No work completed on this ticket
