### ISSUE TITLE
1990 and 1990e QRG and template creation

### ISSUE THREAD

**Issue by Kimberley2023-CSM** [department-of-veterans-affairs/va.gov-team#63882]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

QRG and template needed to advise Tier 1 agents and Veterans of how to proceed when submission errors are encountered with GI Bill education benefits forms 22-1990 (Application for VA Education Benefits) and 22-1990e (Application for Family Member to Use Transferred Benefits). Workaround is provided. 

---
## Tasks
- [x] _Create QRG
- [x] _Create template 
## Acceptance Criteria
- [ x] Complete QRG, templates and publish to VEO glossary---
## How to configure this issue

- [x ] **Attached to an Epic** (what body of work is this a part of?)

**Comment by Kimberley2023-CSM** [comment]
@starlow00 I don't know what usually goes into the ticket for your template ZH ticket, but please update accordingly.  I will also link/attach the education application guidance that I have.

**Comment by Kimberley2023-CSM** [comment]
Hey @starlow00 I'm having issues attaching the email/information from the email in this ticket.  The information you need to complete this ticket is in the email that I sent to you on Monday July 24, 2023 at 1:50 titled Agenda items for 7/25/23 sync.  It's one of the three attachments I sent in that email.

I also didn't want to post the entire email due to contacts being present and this platform being public.

**Comment by Kimberley2023-CSM** [comment]
After meeting with Steven during our one on one on 8/24/23 it was mentioned that I imposed the numbers causing confusion for the template creation.

Although this was a setback, this ticket is still able to be completed this sprint.

**Comment by starlow00** [comment]
QRG and template created. Provided in latest edition of VEO Glossary, attached here. Can be found within the Glossary via Shift-F keyword search, or via links the Change Log or Table of Contents.

[VEO Glossary 08252023.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa0EvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6c58c2f6764ef267a4d09dc2cfaa4f4a08e90446/VEO%20Glossary%2008252023.docx)
