### ISSUE TITLE
Upgrade gems included in Gemfile

### ISSUE THREAD

**Issue by johnpaulashenfelter** [department-of-veterans-affairs/va.gov-team#6388]
bundle outdated --only-explicit

`
Outdated gems included in the bundle:
  * active_model_serializers (newest 0.10.10, installed 0.10.4, requested = 0.10.4) in groups "default"
  * activerecord-postgis-adapter (newest 6.0.0, installed 5.2.2, requested ~> 5.2.2) in groups "default"
  * awrence (newest 1.1.1, installed 1.1.0) in groups "test"
  * aws-sdk-s3 (newest 1.60.2, installed 1.9.0, requested ~> 1) in groups "default"
  * aws-sdk-sns (newest 1.21.0, installed 1.1.0, requested ~> 1) in groups "default"
  * carrierwave (newest 2.1.0, installed 0.11.2, requested ~> 0.11) in groups "default"
  * carrierwave-aws (newest 1.4.0, installed 1.3.0) in groups "default"
  * connect_vbms (newest 1.2.0 baefc1a, installed 1.2.0 bebad55) in groups "default"
  * danger (newest 6.3.1, installed 6.1.0) in groups "development, test"
  * dry-struct (newest 1.3.0, installed 1.2.0) in groups "default"
  * dry-types (newest 1.3.1, installed 1.2.2) in groups "default"
  * faraday (newest 1.0.0, installed 0.17.0) in groups "default"
  * faraday_middleware (newest 0.14.0, installed 0.13.1) in groups "default"
  * flipper-active_record (newest 0.17.2, installed 0.17.1, requested ~> 0.17.1) in groups "default"
  * flipper-active_support_cache_store (newest 0.17.2, installed 0.17.1, requested ~> 0.17.1) in groups "default"
  * flipper-ui (newest 0.17.2, installed 0.17.1, requested ~> 0.17.1) in groups "default"
  * json_schemer (newest 0.2.10, installed 0.2.8) in groups "default"
  * jsonapi-parser (newest 0.1.1, installed 0.1.1.beta3) in groups "default"
  * nokogiri (newest 1.10.9, installed 1.10.8, requested ~> 1.10) in groups "default"
  * oj (newest 3.10.3, installed 3.9.0) in groups "default"
  * openid_auth (newest 1.0.2, installed 0.0.1) in groups "default"
  * pg (newest 1.2.2, installed 1.2.0) in groups "default"
  * puma-plugin-statsd (newest 0.2.0, installed 0.1.0, requested ~> 0.1.0) in groups "default"
  * pundit (newest 2.1.0, installed 1.1.0) in groups "default"
  * rack (newest 2.2.2, installed 2.2.0 f690bb7) in groups "default"
  * rails (newest 6.0.2.1, installed 5.2.4.1, requested ~> 5.2.4) in groups "default"
  * rails_semantic_logger (newest 4.4.3, installed 4.4.0, requested ~> 4.4) in groups "default"
  * redis (newest 4.1.3, installed 3.3.5) in groups "default"
  * restforce (newest 4.2.2, installed 3.0.0) in groups "default"
  * rubocop (newest 0.80.1, installed 0.79.0) in groups "development, test"
  * rubocop-rspec (newest 1.38.1, installed 1.37.1) in groups "development, test"
  * rubyzip (newest 2.2.0, installed 2.0.0) in groups "default"
  * sentry-raven (newest 3.0.0, installed 2.9.0, requested = 2.9.0) in groups "default"
  * shrine (newest 3.2.1, installed 2.19.3) in groups "default"
  * shrine-memory (newest 0.3.1, installed 0.2.2) in groups "test"
  * sidekiq (newest 6.0.5, installed 4.2.10, requested ~> 4.2) in groups "development, test"
  * sidekiq-ent (newest 2.0.1, installed 1.6.1) in groups "production"
  * sidekiq-pro (newest 5.0.1, installed 3.7.0) in groups "production"
  * sidekiq-scheduler (newest 3.0.1, installed 3.0.0, requested ~> 3.0) in groups "default"
  * statsd-instrument (newest 3.0.0, installed 2.6.0) in groups "default"
  * utf8-cleaner (newest 1.0.0, installed 0.2.5) in groups "default"
  * vets_json_schema (newest 3.141.0 53c351b, installed 3.140.0 ad0b80a) in groups "default"
  * web-console (newest 4.0.1, installed 3.7.0) in groups "development"
  * will_paginate (newest 3.3.0, installed 3.1.0) in groups "default"
`

**Comment by erluti** [comment]
`statsd-insturment` deprecates how we configure it starting in version 2.7 https://github.com/Shopify/statsd-instrument/blob/master/CHANGELOG.md#version-270
newer versions fail `modules/vaos/spec/services/middleware/vaos_logging_integration_spec.rb` with a different increment message

**Comment by johnpaulashenfelter** [comment]
Made a ton of progress, moved responsibility over to utility developer role, and time to close.
