### ISSUE TITLE
Flipper UI access for [Samuel Stuckey]

### ISSUE THREAD

**Issue by SamStuckey** [department-of-veterans-affairs/va.gov-team#63887]
### Your Name

Samuel Stuckey

### Your GitHub handle (Flipper UI access is managed through GitHub)

SamStuckey

### Team, Role, and Company of the target individual

BDX-2 (team  carbs), engineer, Oddball (via CoForma)

### Please confirm if you are on the VFS Team Roster, Platform Team Roster or are a Federal User

- [X] [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [X] Lesser Environments (Dev/Staging/Sandbox)
- [ ] Production (if requesting, justify prod access below)

**Comment by ryan-mcneil** [comment]
@SamStuckey You've been granted access to lower envs ✅
