### ISSUE TITLE
Contact Center Review for Public Websites - Income Limits Application Product Guide

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#63899]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
*Please provide the name(s) of your product and a high-level description of your product.*
The Income Limits Wizard/Calculator is a simple 2-3 question form flow that tells Veterans what income limits apply to their health care eligibility. Income limits don’t apply to all Veterans; it depends on their priority group. 

### Launch Date
*Please provide the launch or rollout date and details.*
Approximately 9/1/23, no staged rollout. Timing dependent on completion of Collab Cycle (including this step).

### Version Number
*Please provide the version number of the guide and/or video.*
Version 1

### Product Guide
*Please provide product guide link*
Attached to the issue (per instructions)

### Product Video
*Please provide product video link*
N/a

### Product Video Transcript
*Please provide product video transcript link*
N/a

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by wesrowe** [comment]
[Income Limits product guide - V1.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/12374076/Income.Limits.product.guide.-.V1.docx)

Note: I couldn't find Kimberley's github username to assign her to this ticket.

**Comment by wesrowe** [comment]
cc @jilladams, for your visibility.

**Comment by starlow00** [comment]
Thanks, @wesrowe. I tagged Kimberley. FYI, she's listed under Kimberley2023-CSM now.

**Comment by wesrowe** [comment]
Thanks Steven – FYi I think issue templates can be set up to auto-add the labels and assignees. It might help product teams get it right on the first try, if you see this problem frequently.

Also: thanks for the word template and examples, they were really helpful! One possible addition, if you really want people to do the table of figures, you could add a starter one at the end like you have for the table of contents. After I googled around I found it was pretty easy, but the very cool captions feature in Word was new to me.

I look forward to getting the go-ahead from you all for launch!

**Comment by wesrowe** [comment]
@starlow00, I just realized I have a KPI question that would be good to bring up here. Do you think that calls regarding this new app (Income Limits) might be trackable by the call center?

**Comment by starlow00** [comment]
Hi @wesrowe. Those are good suggestions; thank you! I'll let Anita or Kimberley sound off on the tracking question.

**Comment by starlow00** [comment]
@wesrowe, draft looks good. Sending to VEO for review.

**Comment by starlow00** [comment]
No changes from VEO. Working copy of product guide attached.
[Income Limits product guide SRT 09012023.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/12423572/Income.Limits.product.guide.SRT.09012023.docx)

**Comment by starlow00** [comment]
Hi @ATMiddleton and @Kimberley2023-CSM. Just wanted to follow up on behalf of Wes Rowe and his KPI question about tracking Income Limit-related calls (see above).
