### ISSUE TITLE
1995-STEM Review page: "would you still like to apply" question answer should not be editable until clicking the edit button

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#6389]
If a user is found to be ineligible when applying for the Rogers STEM Scholarship, they are presented with a page that explains why they are ineligible and asks if they would still like to apply. The answer to this question is recorded and can be seen on the review page prior to submitting the application. Like all other questions on this page, the answer should be editable, but only after clicking the "edit" button. Currently, the question can be edited even without clicking "edit" and the button effectively serves no purpose.

1. Navigate to https://staging.va.gov/education/apply-for-education-benefits/application/1995/introduction
2. Begin the application
3. Fill in all required applicant information and continue
4. Select any benefit and continue
5. On the "Rogers STEM Scholarship" answer "Yes" to "Are you applying for the Rogers STEM Scholarship?(*Required)"
6. Answer "no" to all other questions and continue
7. Proceed through the rest of the form and stop on the review/submit page
8. On the review page, expand the Education Benefit section
- note the "Based on your responses, it appears you're not eligible." box is editable before clicking "Edit"

![Screen Shot 2020-03-03 at 10.53.36 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/f19d20be-f744-4689-92c1-6001e59a6803)

# AC
1. The yes/no response should not be editable but should still be displayed similar to the responses directly above it
2. The yes/no response should be editable, but only after clicking Edit as shown in the screenshot below
![Screen Shot 2020-03-03 at 10.53.43 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/56306627-ea1a-47f8-9241-a4d12b2f9046)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/11817

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-03-05 at 10.04.51 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/04a5501e-fa15-4196-b781-8195b2d601a4)
##
After selecting "Edit"
![Screen Shot 2020-03-05 at 10.04.56 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/cd46f8db-99b9-40b0-9bfc-3be4eafda427)

**Comment by sonntag-adam** [comment]
In staging, testing passes QA.
