### ISSUE TITLE
[UX] 10-10EZR: Present Form Wireframes to HEC Team

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#63890]
As a HEC Stakeholder, I would like to understand how the Digital 10-10 team is building the EZR online so that I can make sure that my needs are met on the backend and so that I can support them.

- [ ] Come up with desired outcomes
- [ ] Come up with Agenda
- [ ] Review Agenda with Patrick
- [ ] Create a slide deck that walks them through the wireframes
- [ ] Review slide deck with Patrick
- [ ] Review Patrick's changes
- [ ] Present!

**Comment by IMHieuVo** [comment]
Instead of a slide deck, we decided to present the Flow in Sketch since it would allow us to move around the Flow with ease.

[Sketch Link](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/p/2243222A-201E-413F-8CC2-8A8C237726DC/canvas).
