### ISSUE TITLE
[CST Scalability] Set up concurrent job monitoring in Datadog

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#63906]
## Value Prop

Monitoring product performance so we can address issues quickly. 
## Background

Sidekiq jobs should stay below a threshold approximately equal to the threshold of average evidence submission requests/min. **A count of sidekiq jobs above this threshold indicates longer than average wait times for completion of submission.** Also predicts a need to coordinate with platform to increase sidekiq workers. Measured only for endpoints that create sidekiq jobs.

Notes:
- We don't have DataDog write access so we can't directly create monitors and alerts. 2 ways around this are:
  - Build out a temporary chart with the information needed to complete this work and work with Steve Albers to create the monitor; Steve has write access.
  - Build out a temporary chart and translate that into Terraform. Make a pull request to the [devops repo](https://github.com/department-of-veterans-affairs/devops/tree/master/terraform/environments/datadog)
 
## Acceptance Criteria:
- [ ] Low watermark identified
- [ ] High watermark identified
- [ ] Set up quick dashboard in DD and give Steve query we used
- [ ] Share requested requirements for DD config (Alert created and routed to Slack channel, Chart created and added to Datadog dashboard, etc.)

**Comment by kjduensing** [comment]
After [asking about this in the #benefits-ce-engineering channel](https://dsva.slack.com/archives/C053U7BUT27/p1693489781062699), it sounds like jobs won't really get stuck in the queue due to retry logic, timeouts, and speed at which the jobs are processed.

I recommend we close this ticket, since this monitor won't be that useful. @jacobworrell @jerekshoe @samcoforma thoughts?

**Comment by HeatherWidmont** [comment]
@jerekshoe will look into it & get back to @kjduensing
