### ISSUE TITLE
Update carrierwave gem

### ISSUE THREAD

**Issue by johnpaulashenfelter** [department-of-veterans-affairs/va.gov-team#6390]
Our carrierwave gems are significantly out of date *and* involved in file uploads, which require a higher level of manual testing in the AWS environment.

We need to 

- [ ] Update the gems
- [ ] Keep specs passing
- [ ] Verify that files upload successfully to S3
- [ ] Verify any postprocessing (clamAV, resizing/etc) continues to work

**Comment by erluti** [comment]
resolved by this PR https://github.com/department-of-veterans-affairs/vets-api/pull/5022#event-3861618304
