### ISSUE TITLE
[CST Scalability] Set up error rate monitoring in Datadog

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#63901]
## Value Prop

Monitoring product performance so we can address issues quickly. 

## Background

In order to maintain confidence in the CST as well as to predict and respond to issues, the error rate should stay below a low water mark. Above the low watermark is a warning sign. Above a high watermark is a problem. Error rates should be measured for each error type on each endpoint.

Notes:
- We don't have DataDog write access so we can't directly create monitors and alerts. 2 ways around this are:
  - Build out a temporary chart with the information needed to complete this work and work with Steve Albers to create the monitor; Steve has write access.
  - Build out a temporary chart and translate that into Terraform. Make a pull request to the [devops repo](https://github.com/department-of-veterans-affairs/devops/tree/master/terraform/environments/datadog)
 
## Acceptance Criteria:
- [ ] Low watermark identified
- [ ] High watermark identified
- [ ] Set up quick dashboard in DD and give Steve query we used
- [ ] Share requested requirements for DD config (Alert created and routed to Slack channel, Chart created and added to Datadog dashboard, etc.)

**Comment by kjduensing** [comment]
Metrics query:
`sum:trace.rack.request.hits{env:eks-prod AND service:vets-api AND (resource_name:v0::evssclaimsasynccontroller* OR resource_name:v0::benefitsclaimscontroller* OR resource_name:v0::documentscontroller*) AND NOT http.status_code:20*}.as_rate()`

**Comment by kjduensing** [comment]
Warning threshold: 0.2 hits/s
Critical threshold: 0.5 hits/s

**Comment by kjduensing** [comment]
@va-albers Another monitor set up to add to the pile :). No rush with these, I'll ping you in Slack when they're all finished. Just tagging you hear for awareness

**Comment by va-albers** [comment]
Dashboard: https://vagov.ddog-gov.com/dashboard/uc8-jnr-zhm
https://vagov.ddog-gov.com/monitors/157719
