### ISSUE TITLE
Qualitative Data Request- Appointments Team

### ISSUE THREAD

**Issue by melissa-lefevre** [department-of-veterans-affairs/va.gov-team#63912]
### Data Type Requested

User Surveys

### Date Range Start

08-14-2023

### Date Range End

08-20-2023

### Product Name(s)

Appointments Team (formerly VAOS)

### Product Description

Hello. I am requesting August 14th 2023 to August 20th 2023 Medallia feedback for Appointments. If you could send it to melissa.lefevre@va.gov. If you have any questions, please reach out. Thanks!

### Survey URL(s), key term(s), case category or type

va.gov/health-care/schedule-view-va-appointments/appointments/

### File Delivery Format

All in one file, on one tab

### VA Email Address(es)

melissa.lefevre@va.gov

### Add Assignee and Labels

If not already done so, please ensure @ianMcCullough-ob is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by newworld2616** [comment]
Hi, I have sent the requested data, please verify, if you received it. Thank you!

**Comment by melissa-lefevre** [comment]
Hi, I did receive it. However it is missing the weekend dates. It should be 8-14 through 8-20. Would you mind re-sending the whole requested date range?

**Comment by newworld2616** [comment]
Sorry about that! I will re-run it!

**Comment by newworld2616** [comment]
Hi @melissa-lefevre. I have sent the requested data, please verify if you received it. Thank you!

**Comment by newworld2616** [comment]
Data request sent!
