### ISSUE TITLE
Revisiting ClamAV Mirroring Solution

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#63916]
## Background:
We implemented a mirroring pod solution for ClamAV to obtain the updated virus signature db's. However, we've observed issues such as 404 errors during node scaling and/or potential rate limiting and an unstable ClamAV network. There is a current Jenkins job that mirrors the db's to an s3 bucket, which we are using for the time being. We should see if there's any research as to why the s3 bucket solution was adopted in the first place (~6 years ago). It's possible the developer ran into the same issue we are seeing with the 404s.

## Objective:
Reassess the current ClamAV mirroring pod solution and determine if there's a more optimal and efficient alternative. One potential solution could be utilizing an S3 bucket updated via a cron job.

### Acceptance Criteria:

- [x] Investigate the root causes of the 404 errors during node scaling
- [x] Identify if rate limiting is causing any disruption, and if so, at what frequency.
- [x] Design an S3-based Solution + Github Action
- [x] Teardown clamav mirror config
### Design a solution where ClamAV updates are stored in an S3 bucket.
- [x]  Implement a github action that frequently checks for updates and pushes them to the S3 bucket.
- [x]  Ensure that the S3 bucket has appropriate permissions, so only necessary services can fetch updates.
- [x]  Point the clamav DB config to the s3 bucket 

### Scalability & Redundancy:
- [x]  Ensure the new solution can efficiently scale and is resilient.
- [x]  Optimize to minimize latency and potential downtimes during updates.

### Documentation:
- [x]  Update all related documentation to reflect the changes.
- [x]  Include detailed setup, maintenance, and troubleshooting guides.

### Testing:
- [x]  Test the new solution in a controlled environment to ensure stability and functionality.
- [x]  Monitor the update mechanism to ensure it's running seamlessly and efficiently.

**Comment by RachalCassity** [comment]
Blocked by devops. Need S3 Permissions.

**Comment by RachalCassity** [comment]
Awaiting aws credentials

**Comment by RachalCassity** [comment]
clamav-mirror repository was archived: `Your repository "department-of-veterans-affairs/vsp-infra-clamav-mirror" was successfully archived.`

**Comment by RachalCassity** [comment]
Created teardown ticket: https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/77205

**Comment by RachalCassity** [comment]
Awaiting approvals

**Comment by RachalCassity** [comment]
Clamav-updater job should be removed in the next sprint.
