### ISSUE TITLE
Contact Center Review for [MHV Medical Records]

### ISSUE THREAD

**Issue by bryan-riley-va** [department-of-veterans-affairs/va.gov-team#63915]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
*Please provide the name(s) of your product and a high-level description of your product.*
MHV Medical Records will provide Veterans the ability to see their historical medical records through VA.gov.  As part of the implementation they will eventually be able to view Allergies, Vaccines, Vitals, Health Conditions, Care Summaries/Notes, Radiology Reports/Images, Labs/Tests, Microbiology, Pathology.  They will be able to view the information on a browser, or download information in a PDF or TXT file.  They will ultimately also be able to manage their health record information sharing options as well.

### Launch Date
*Please provide the launch or rollout date and details.*
We are going to be launching into Phase 0 by 10/1/2023 one 'domain' at a time.  It's anticipated we will have Allergies available on 10/1, followed shortly after by Vaccines.  From there additional domains will be released as they are ready.

### Version Number
*Please provide the version number of the guide and/or video.*
v1

### Product Guide
*Please provide product guide link*
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/medical-records/product/MR%20on%20VA.gov_Product%20Guide_Draft.docx

### Product Video
*Please provide product video link*
https://youtu.be/FslmUpuI-7U

### Product Video Transcript
*Please provide product video transcript link*
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/medical-records/product/Script.docx

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by bryan-riley-va** [comment]
Hi - any questions or concerns with this ticket or info?

**Comment by starlow00** [comment]
Hi @bryan-riley-va. Sorry I haven't been able to update this yet, it's been a busy sprint. I will review and make sure VEO has it for their review within a few days. I will let you know if I have questions. Thanks!

**Comment by starlow00** [comment]
The guide looks good. Sent to VEO for their review.

**Comment by starlow00** [comment]
Hi @bryan-riley-va. My VEO contact had the following questions. Any info you have at your disposal will be much appreciated:

1. If I try this new tool, am I still able to use MyHealtheVet if that’s my preference?
2. When will MyHealtheVet shut down?
3. If I log in using a verified MyHealtheVet account, will I need to make an account with a different login provider like Login.gov?
4. I receive care from a location that underwent Electronic Health Record Modernization. Am I still able to use this tool?

**Comment by bryan-riley-va** [comment]
1-If I try this new tool, am I still able to use MyHealtheVet if that’s my preference?  BR-Yes, for this launch we will only have a small number of invited users that will access the new platform.  Over time additional users will be added.  Up until the final release (estimated October 2024) users will continue to be able to access the existing MHV Medical Records experience.
2-When will MyHealtheVet shut down?  Estimate approximately October 2024...
3-If I log in using a verified MyHealtheVet account, will I need to make an account with a different login provider like Login.gov?  Invited users will be those that will not need to make any additional accounts.
4-I receive care from a location that underwent Electronic Health Record Modernization. Am I still able to use this tool?  Invited users initially will not include these users.  In a future Phase (several months down the line), we will have integrated with Cerner data and only then will those users be invited/impacted.

**Comment by starlow00** [comment]
Thanks, Bryan. VEO has the info now. Draft attached.
[Medical Records Tool MHV to VA.gov_08292023.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/12542729/Medical.Records.Tool.MHV.to.VA.gov_08292023.docx)
