### ISSUE TITLE
Update sidekiq to v5

### ISSUE THREAD

**Issue by johnpaulashenfelter** [department-of-veterans-affairs/va.gov-team#6392]
Our sidekiq gems are mission-critical for running asynchronous jobs and are two major versions out of date. 

Upgrading these gems requires thorough testing on staging as well as monitoring in production to ensure things work as expected.

**Comment by erluti** [comment]
Began upgrading sidekiq to 5 here, https://github.com/department-of-veterans-affairs/vets-api/tree/be-tools/pb/upgrade-sidekiq
Broke a 50 or so tests, so now I'm working on fixing those

**Comment by erluti** [comment]
`sidekiq-instrument` is locked to be incompatible with sidekiq v6
https://github.com/enova/sidekiq-instrument/blob/master/sidekiq-instrument.gemspec#L19

**Comment by erluti** [comment]
Merged https://github.com/department-of-veterans-affairs/vets-api/pull/4128
