### ISSUE TITLE
Identity Dashboard (FE) - Sidebar Responsive View

### ISSUE THREAD

**Issue by acald-creator** [department-of-veterans-affairs/va.gov-team#63927]
## Description
Fix the Sidebar component to make responsive view

## Tasks
- [ ] Create a responsive view for the Sidebar (wrap to top with menu icon)
  - [ ] *Note whoever picks this up let me know if you need me to add some design in Figma for this.

**Comment by asg5704** [comment]
Closing as IDD is dead
