### ISSUE TITLE
SOCKS access for Josh Houston

### ISSUE THREAD

**Issue by jhouston0** [department-of-veterans-affairs/va.gov-team#63923]
### Your Name

Josh Houston

### Your Email

josh.houston@bylight.com

### Your Role and Team

Devops Engineer on Identity team

### Product Manager (PM) name and email

Mike King Mike.King@oddball.io

### Product Owner (PO) name and email

John Rahaghi john.rahaghi@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDtZDpv/Tw4iFoEh/IjlB1P2Jq8E4mu7I6sAyxncICqpG+Bvsb9RJKl0GpXbf7S22wWcea8c0mDotJ7hOmI07DT6ZSMYYWTqmAzRZRraquaByDodwPGdqqX4Zvp0JfWcwYAtvT+Yfe25yE9Ij1rCUTLWXA+W/6MrdgfBpiGFbDXwWrcNcNP1K4AgNwI1Xz0o9WQMeVCiWlDFG7bmL/x8P2N9ird1GDv76N3CZyfuI3bXrB3JaUmOr4bpSNByFXO6FKqWElB4FYH3IsfcH4FLrjDnR571xgtHgH6YLzZKubha0ryBym8FWrxeGQnMmQ07dewFSWPB1qzc5LsW7agzTtkVM3yfpsgi22oUYWvsFPfDnV8oh2mRK8f9xRSWJMdXXLO+XXwHAsXJ4BaL/hUC423gsIq77e04qF2pdmSl6c0pZNoZabnzxdCMVmBeT1hEQKCWoNt/SG3preWOEH8MlBo7RoNbgkgoAv88uGcEn4IKPHocceyET2huwWe7ZKmU4s= josh.houston@TT7GN4CPW0

### E-QIP Transmittal Confirmation

![Screenshot 2023-08-21 at 9 39 40 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/139352061/00449286-7c9e-4599-aea3-4aec641335d9)

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by hgbarreto** [comment]
SOCKS Access granted ✅ 

Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.
https://depo-platform-documentation.scrollhelp.site/getting-started/accessing-internal-tools-via-socks-proxy
