### ISSUE TITLE
1995-STEM: "Based on you responses" should be "Based on your responses"

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#6393]
A typographical error is present on the "Rogers STEM Scholarship eligibility" page of the 1995-STEM form. "You" in the header of the box indicating why a user is not eligible should be "your". See screenshot below

![Screen Shot 2020-03-03 at 11.20.50 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/6371de00-f39d-4344-b687-d2c7939378cf)

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-03-06 at 11.34.31 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/9bddf234-ed0b-46cf-8969-0452310f7e04)

**Comment by sonntag-adam** [comment]
In staging, closing bug.
