### ISSUE TITLE
[Congressional] V10737996 - Issues with VA.gov account showing wrong name {Rep. Chavez-DeRemer) Due 9/15/23

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#63938]
## Issue Description
_ Veteran needs his name corrected on VA.gov. Please review documents provided. Veteran can be contacted via. email or telephone provided on document._

---
## Tasks
- [ ] Review congressional correspondence 
- [ ] Resolve Issue 
- [ ] Notify Veteran and congressional correspondence channel of solution 

## Acceptance Criteria
- [ ] Veteran issue will be resolved or responded to with final answer to issue 
- [ ] Congressional Correspondence will receive details of the resolution 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by clantosswett** [comment]
This needs to be sent to EVSS since it is a name change request.

**Comment by ATMiddleton** [comment]
@Kimberley2023-CSM @ATMiddleton will create a process to resolve during this sprint.

**Comment by Kimberley2023-CSM** [comment]
@Kimberley2023-CSM sent sharepoint link to Jeremy Haas for review and resolution on 9/11/23.  Awaiting feedback.

**Comment by clantosswett** [comment]
EVSS was able to correct Veteran's last name. EVSS emailed Veteran on 9/8 asking to confirm if last name is showing correct. They received a response from Veteran the same day confirming last name is now correct.
