### ISSUE TITLE
Vets-api terminal access for Josh Houston

### ISSUE THREAD

**Issue by jhouston0** [department-of-veterans-affairs/va.gov-team#63942]
### Your Name

Josh Houston

### Your GitHub handle (terminal access is managed through GitHub)

 jhouston0

### Team, Role, and Company of the target individual

Identity, Devops Engineer, by light

### Product Manager (PM) name and email

Mike King Mike.King@oddball.io

### Product Owner (PO) name and email

John Rahaghi john.rahaghi@va.gov

### COR Name (leave "None" if you listed an AWS user name above)

Laurene "Reney" Cook

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

Oddball - Amber Malcolm

### Please confirm if you are on the VFS Team Roster or Platform Team Roster

- [X] [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Please confirm E-QIP Transmittal/Adjudication. This could be a screenshot of your Transmittal/Adjudication email, a link to another request where you've submitted this proof (i.e. AWS/SOCKS), etc.

- [X] I have attached proof that I have either transmitted my E-QIP survey or previously received a favorable decision (by including in "Additional Notes" section below)

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [ ] production (if requesting, justify prod access in 'Additional Notes' section)

### Additional Notes

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/139352061/930178ad-c31f-4bbc-9efa-abab5f2fc089)

### Additional resources for Support Engineer

- [ ] For users on a VFS team but not in the VFS Team Roster, they must start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] Instructions for handling requests [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access) - Support Only

**Comment by bdech** [comment]
@jhouston0 Have you completed the E-QIP questionnaire? Once you complete it you will receive an email that looks like this 
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/135037265/671a604e-5bef-4aae-a0b7-3957169d7c7e)

I only ask because the screenshot provided doesn't have any identifying info. Can you provide a screenshot similar to the example I provided?

**Comment by jhouston0** [comment]
ah i apologize, I do not have that email yet, I just submitted the SF85p and thought that was the same thing. I will close this issue and create a. new issue  I do. Sorry!

**Comment by bdech** [comment]
No worries at all. Once you receive the transmittal notice, re-open this ticket and attach it. You can @ me here once you have the transmittal notice, and we'll get you squared away.

**Comment by ryan-mcneil** [comment]
@jhouston0 Brandon is out for the week, so I'll help ya out.

You’ve been granted access to the `dev`, `staging`, and `sandbox` environments.

Here's some additional documentation for the [Vets API on EKS](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-TerminalAccess)
