### ISSUE TITLE
AWS access for Josh Houston

### ISSUE THREAD

**Issue by jhouston0** [department-of-veterans-affairs/va.gov-team#63945]
### COR Name

Laurene "Reney" Cook

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Josh Houston

### Your Email

josh.houston@bylight.com

### Team, Role, and Company of the target individual

Identity, Devops Engineer, by light

### Product Manager (PM) name and email

Mike King Mike.King@oddball.io

### Product Owner (PO) name and email

John Rahaghi john.rahaghi@va.gov

### Desired AWS Access

 DevOps permissions for the Identity team

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

![Screenshot 2023-08-21 at 9 39 40 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/139352061/af516aa9-8fb7-4e4c-b3f9-8c7d265f5178)

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by jhouston0** [comment]
re-opened with correct e-quip transmittal confirmation

**Comment by hgbarreto** [comment]
User can be found in [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)

**Comment by hgbarreto** [comment]
Awaiting approval from @BillChapmanUSDS

**Comment by jhouston0** [comment]
Hi @BillChapmanUSDS, yes I am a DevOps Engineer on the Identity team.

**Comment by hgbarreto** [comment]
Access has been granted
