### ISSUE TITLE
Identity Dashboard (FE) - Create a dropdown for `Applications`

### ISSUE THREAD

**Issue by acald-creator** [department-of-veterans-affairs/va.gov-team#63956]
- [ ] Create a dropdown for the `Applications` where `Client Config` is the only child route

**Comment by acald-creator** [comment]
Need to find out which icon is to be used for this.

**Comment by acald-creator** [comment]
open PR: https://github.com/department-of-veterans-affairs/identity-dashboard-fe/pull/62

**Comment by aparsley** [comment]
Identity Dashboard (FE) - Update figma for BPDR monitoring page #64002
