### ISSUE TITLE
Add severity (launch-blocking or not) to Staging Review finding template

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#63984]
## User Story
As a VFS team member, I want to understand whether a Staging Review finding is launch-blocking, so that my team can prioritize our tickets and ship our product faster.

Assignee:
Peer Reviewer:

## Description
When resolving a recent Staging Review finding ticket, a VFS team member was unsure whether or not the issue was launch-blocking or not. The only indicator of whether a ticket is not launch-blocking is the lack of `launch-blocking` label which is not clearly communicated. The purpose of this ticket is to add text within the ticket to specify if the finding is launch-blocking or not launch-blocking. 

## Impacted Artifacts
- Staging review ticket template
- Staging review template?
- Staging review GH issue generator
- [Collab cycle dashboard metrics?](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2365063202/Collab+Cycle+Dashboard+metrics)
- Documentation: 
  - [Staging review moderator duties](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1819476255/Staging+Review+-+VFS+-+Moderator+Responsibilities)
  - [Anatomy of a staging review ticket](https://vfs.atlassian.net/wiki/spaces/CC/pages/2060320997/Anatomy+of+a+Staging+Review+Issue+ticket)
  - [Drafting template outline](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2385248274/DraftingTemplate+Outline)

## Tasks
- [ ] _Placeholder task_

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] _Placeholder AC_

### Refinement
- [ ] Ticket has user story, description, tasks, and acceptance criteria
- [ ] Ticket has [additional appropriate labels](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2220359751/WIP+Tech+Debt+Ticket+Organization), if applicable
- [ ] Ticket has been sized 
- [ ] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [ ] Ticket has been assigned to appropriate initiative or quarterly epic
- [ ] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
FYI @erinrwhite please feel free to add to the ticket if there's more info to communicate.

**Comment by erinrwhite** [comment]
Looking good! I took a swipe at the user story and the artifacts but I don't think it's comprehensive...yet.

**Comment by shiragoodman** [comment]
@erinrwhite how do you feel about postponing this work and merging it into the VA.gov Experience Standards improvement work? We already know we need to modify the findings template, so I think it makes sense to delay this a couple sprints and we can make the change as part of ticket #64417

**Comment by shiragoodman** [comment]
closing as the ticket will be addressed/merged with #64417
