### ISSUE TITLE
[formation-react] [CollapsiblePanel] Fix runtime error in scroll function for consumers outside of vets-website

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#640]
In vets-website, we defined a custom global called `window.VetsGov` in order to pass information from unit/E2E tests into the browser/component. This is fine for our purposes, but consumers of the design system that do not define `window.VetsGov` will hit a runtime error. We are seeing this in the [scroll function of the CollapsiblePanel component](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/formation-react/src/components/CollapsiblePanel/CollapsiblePanel.jsx#L24).

We should fix this so that this component is portable outside of vets-website and does not require a global `window.VetsGov`. As one possible solution, it might make sense to move the data in `window.VetsGov.scroll` into `defaultProps`, like -

```
CollapsiblePanel.defaultProps = {
    scrollSettings: window.VetsGov ? window.VetsGov.scroll : {
        duration: 500,
        delay: 2,
        smooth: true,
      }
};
```

Then just reference `this.props.scrollSettings` in `scrollToTop`.

**Comment by ncksllvn** [comment]
CC: @rianfowler @accbjt @annaswims

**Comment by FranECross** [comment]
Closing due to age and inactivity. More than likely obsolete. Can reopen if needed in the future, or a new ticket created.
