### ISSUE TITLE
Adding Evelyn Davis to DSVA Slack

### ISSUE THREAD

**Issue by alatempa24** [department-of-veterans-affairs/va.gov-team#64005]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

<describe the request>

Are you requesting to add an individual as a:

- [X] Full member

- Single guest
- Multi-channel
- Switching from single-channel to multi-channel?
- What channel(s) do they need to be added to?

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

Evelyn Davis is a new UX Researcher with the Disability Benefits Experience team 1, part of ABD Apps contract. They need DSVA slack to communicate with the team and VA on their work.

Please add evelyn@cityfriends.tech as a full member to:
- #benefits-ce-disability_exp
- #benefits-ce-disability_design
- #benefits-onboarding
- #benefits-ce
- #benefits-portfolio 

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add [_insert email_] as a single-channel guest to [_channel name_].
- Please add [_insert email_] as a multi-channel guest to these channels: [_channel names_].
- Please add [_insert email_] as a full member.
- Please change the status of [_slack username_] from [_current status_] to [_desired status_]

**Comment by LEHigley** [comment]
already showing as full member
