### ISSUE TITLE
Add MyVAHealth Cerner Patient Restriction on MyVAHealth USiP

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#64008]
** Must be tested in staging with MHV leadership prior to going to production **

If a verified user is attempting to go to MyVAHealth through VA.gov USiP and they are not Cerner eligible, we should redirect the user to an error page on VA.gov informing the user they are not Cerner eligible. If the user thinks they should be, they should be shown the help desk number, otherwise show a deeplink to MHV.

- [ ] Get user attribute check requirements from Mike Ferraro
- [ ] Add this check in prior to release of first version of ToU
- [ ] Add requirements to MyVAHealth USiP documentation

Tentative Requirements (verify with Mike Ferraro):
Cerner- patient  eligibility:  If a Patient (PI) has 200CRNR and at least one of the five migrated treatment facilities (Spokane 688, Roseburg 653, White City VA 692, Walla Walla 687, Columbus VA) then display links to My VA Health

### **More details from another ticket:**

VA.gov will interrupt  the user auth flow on the callback which detects if a user is Cerner eligible. 
- If they are not eligible, we will send them to an error page which says they are not Cerner eligible and tells them they can try to use MHV.
- we need another error page, or find the one we already have.

As an external user who is not Cerner eligible, I have logged into an SSOe enabled web application, I then manually go to https://patientportal.myhealth.va.gov/, I should be redirected to an error page (hosted within va.gov) that states I am not eligible for Cerner and should try myhealthevet if I believe I should have access to VA healthcare. I should not be logged out.

There is a dependency on the backend to complete this work.

**Comment by asg5704** [comment]
Closed by https://github.com/department-of-veterans-affairs/vets-website/pull/29882

**Comment by asg5704** [comment]
@kingbmike I think we're good to close this one.
