### ISSUE TITLE
[ZOOM]: Foresee Feedback button SHOULD not overlap content

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#6401]
**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

See screenshot below. For screen magnifier and mobile users, the blue Feedback button is overlapping the content, interfering with the ability to read it. 

## Point of Contact

**VFS Point of Contact:** Jennifer

## Acceptance Criteria

- As a screen magnifier user, I want to read all the content of the page without it being covered.

- As a mobile user, I want to read all the content of the page without it being covered.

## Environment

* Operating System: any 
* Browser: any
* Server destination: production

## Steps to Recreate

1. Enter `https://www.va.gov/decision-reviews/higher-level-review/` in browser
2. Set viewport width to 1280px wide
3. Zoom to 400%
4. Verify that the button is covering content

## Screenshots or Trace Logs

![VA-feedback-button-overlaps-content](https://user-images.githubusercontent.com/57469/75807425-5cdede80-5d53-11ea-964e-4c95ff3b631e.png)

**Comment by timwright12** [comment]
Do we need this since foresee is in the process of being removed?
