### ISSUE TITLE
[FE] 10-10EZR: Add RevProxy entry in DevOps Repo for approved URL

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#64018]
As a team member, I would like to enter the EZR form into the reverse proxy DevOps Repo to reserve the URL for use with our application. 

- [x] Get a path from IA ticket (get the finalized URL)
- [x] Add entry to reverse proxy file they have
- [x] Declare whether it's protected or not (Logged in vs. not)
- [x] **Success: We have the EZR form in the DevOps file**

**Comment by longmd** [comment]
The path given to us for this is: `my-health/update-benefits-information-form-10-10ezr`. We will not protect the path and allow for it to be accessed in any authenticated state.
