### ISSUE TITLE
Remove any references of va_online_scheduling_request_flow_update feature toggle

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#64029]
## Description
We have decided that the feature toggle `va_online_scheduling_request_flow_update` for the [VA/CC flow content update](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/53491) initiative is no longer needed in the frontend code. . 

---

## Acceptance Criteria

- [x] Remove any references of the feature toggle `va_online_scheduling_request_flow_update`
- [x] Delete the feature toggle `va_online_scheduling_request_flow_update` in [staging](https://staging-api.va.gov/flipper/features/ ) and [production]( https://api.va.gov/flipper/features)
- [x] Changes have been updated in `vets-website` and `vets-api`

### Design Assets
N/A

## Definition of Done
- [x] All acceptance criteria are met
- [x] [Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/product/feature_toggles.md) is updated

**Comment by ldelacosta** [comment]
@young1205 - please notify @JRRoof to validate

**Comment by JunTaoLuo** [comment]
Marking this issue as blocked until full review of all feature toggles to be removed.

**Comment by JunTaoLuo** [comment]
Removal of feature toggle is completed in dev/staging/sandbox environments and removal in production will be completed in https://github.com/department-of-veterans-affairs/va.gov-team/issues/84111
