### ISSUE TITLE
eMIS deprecation `form1010cg` service

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#64033]
### Summary
eMIS is being deprecated at the end of September 2023. eMIS (Enterprise Military Information Service) is an external service heavily integrated into vets-api. It is being replaced with VA Profile.

All references to `emis` in [`/app/services/form1010cg/service.rb`](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/services/form1010cg/service.rb) need to be changed. 

### Things to note
- #44856 will impact this work.
- [ ] Link to any relevant PRs.

### Definition of Done
eMIS is no longer being called or referenced in `form1010cg/service.rb`

**Comment by laineymajor** [comment]
For 10-10 team

**Comment by LindseySaari** [comment]
We should be ready for testing within the next few days.

**Comment by laineymajor** [comment]
The team is currently testing and in communication with us. The primary purpose for this ticket was for us to save space/time for TA, answering questions, etc. 

This can be closed this sprint.
