### ISSUE TITLE
eMIS deprecation veteran verification & confirmation modules

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#64032]
### Summary
eMIS is being deprecated at the end of September 2023. eMIS (Enterprise Military Information Service) is an external service heavily integrated into vets-api. It is being replaced with VA Profile.

All references to `emis` in [the veteran_verification module](https://github.com/department-of-veterans-affairs/vets-api/tree/master/modules/veteran_verification) and [veteran_confirmation module](https://github.com/department-of-veterans-affairs/vets-api/tree/master/modules/veteran_confirmation) need to be changed. 

### Things to note
- `{ authorize :emis, :access? }` will be changed in https://github.com/department-of-veterans-affairs/va.gov-team/issues/44868.
- Also dependent on #61657
- If it's helpful, VCR cassettes for VA Profile live here: https://github.com/department-of-veterans-affairs/vets-api/tree/master/spec/support/vcr_cassettes/va_profile
- Reach out in #-emis-deprecation Slack channel with questions!

### Definition of Done
eMIS is no longer being called or referenced in the veteran_verification or veteran_confirmation modules

**Comment by laineymajor** [comment]
For the authenticated experience team.

**Comment by mtcA6** [comment]
@tpharrison seems like this might be your wheelhouse, could you take a look ahead of refinement later today? we can discuss on the call as well.

**Comment by tpharrison** [comment]
Hi @rmtolmach!  Do you have some time to discuss this?  We switched over to VA Pro from eMIS last year for the Profile, but I'm not sure what else I should migrate.

**Comment by rmtolmach** [comment]
I met with Tom. `modules/veteran_verification` is not owned by his team, it's owned by Lighthouse.

**Comment by rmtolmach** [comment]
Update from Lorri:
> 1 consumer involved and it's a configuration item for us to change it. I submitted a ticket to our devops team to make the change

@lglover-va this ticket can be closed when you're all done on your end 🙂

**Comment by lglover-va** [comment]
Veteran Verification /V1 has been migrated off vets-api and no longer uses eMIS (moved to dvp utilizing va-profile.   Closing.
