### ISSUE TITLE
Contact Center Review for MHV Medications

### ISSUE THREAD

**Issue by IdeaTrail** [department-of-veterans-affairs/va.gov-team#64046]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
MHV Medications provides veterans with a list of their medications, details about each medications, a refill request button for refillable medications and tracking information for medications that were sent to the veteran via third party carrier.

### Launch Date
September 29, 2023

### Version Number
Version 1
### Product Guide
(https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/digital-health-modernization/mhv-to-va.gov/medications/product)

### Product Video
(https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/digital-health-modernization/mhv-to-va.gov/medications/product)

### Product Video Transcript
(https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/digital-health-modernization/mhv-to-va.gov/medications/product)

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by IdeaTrail** [comment]
Any questions on this request?

**Comment by starlow00** [comment]
Hi @IdeaTrail. Sorry I haven't updated this yet, it's been a busy sprint. I will review it within the next couple of days and contact you if I have questions. I will also make sure VEO receives their review copy. Thanks!

**Comment by IdeaTrail** [comment]
Thank you. I'll keep an eye out.

**Comment by starlow00** [comment]
Update (@IdeaTrail): Draft looks good, sending to VEO review today.

**Comment by starlow00** [comment]
Will have final VEO review verdict by Friday 9/8.

**Comment by starlow00** [comment]
No changes from VEO. Copy attached for future use/revisions.[Medications MHV to VA.gov product guide SRT 09042023.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcENCIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--af6836c674879d4288391fc20b7ff7a731445f88/Medications%20MHV%20to%20VA.gov%20product%20guide%20SRT%2009042023.docx)
