### ISSUE TITLE
eMIS deprecation `military_person?`, `served_in_military?` and `veteran?`

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#64042]
### Summary
eMIS is being deprecated at the end of September 2023. eMIS (Enterprise Military Information Service) is an external service heavily integrated into vets-api. It is being replaced with VA Profile.

[The user model](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/user.rb) delegates attributes to `veteran_status`, which comes from eMIS. 
```rb
  # emis attributes
  delegate :military_person?, to: :veteran_status
  delegate :veteran?, to: :veteran_status
```
The `served_in_military?` also references the (veteran? || military_person?) methods

Any references to these attributes in vets-api 

### Things to note
- #44856 will impact this work.
- [ ] Link to any relevant PRs.

### Definition of Done
`military_person?` and `veteran?` references on `veteran_status` are pulling form VA Profile and updated as needed. emis references are removed or replaced.

**Comment by laineymajor** [comment]
This is directly related to the ticket Ryan is currently working. This is also blocking other work (for VFS teams).

**Comment by laineymajor** [comment]
@rjohnson2011 will complete this ticket after his current emis ticket.

**Comment by laineymajor** [comment]
We don't think we will get to this during this sprint... adding it to next sprint

**Comment by LindseySaari** [comment]
These are passing along with the other tests in Ryans branch. Next step is to wrap the underlying methods in a feature toggle and test in lower envs. Rachal will be working on the discovery around the caching piece that goes along with this

**Comment by LindseySaari** [comment]
These tests are passing as well, we basically got this one for free along with the other veteran_status ticket

**Comment by laineymajor** [comment]
in testing now. once testing is done with one, it will likely account for testing of all 3.
