### ISSUE TITLE
Cerner re-direct widget post launch updates (Public Websites) 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#64048]
## Description
We will need to update the Cerner re-direct widget on the Public Websites page. 

---

## Acceptance Criteria
Background: the `va_online_scheduling_static_landing_page` toggle is on

- [x] Given when the user is registered at one Cerner site
       When the user lands on the Cerner widget in https://www.va.gov/health-care/schedule-view-va-appointments/
       Then the message description should display `to manage appointments at this facility...`
       And page design matches the [design spec](https://www.figma.com/file/iqjkZx2EbrZu6leL6YfN45/Cerner-Handoff?type=design&node-id=1851-27388&mode=design&t=pgkIWY55pbPRbPeY-4)

- [x] Given when the user is registered at multiple Cerner sites (two or more) 
       When the user lands on the Cerner widget in https://www.va.gov/health-care/schedule-view-va-appointments/
       Then the message description should display `to manage appointments at these facilities...`
       And page design matches the [design spec](https://www.figma.com/file/iqjkZx2EbrZu6leL6YfN45/Cerner-Handoff?type=design&node-id=1851-27388&mode=design&t=L8VCCynpro2yf5F1-0)

- [x] Given the user is registered at a Cerner site(s)
       When the user lands on the Cerner widget in https://www.va.gov/health-care/schedule-view-va-appointments/ and clicks on clicks on `Go to appointments tool on VA.gov` link
       Then the user will be directed to the Appointments landing page on the same tab. 

- [x] Given the user is registered at a Cerner site(s)
       When the user lands on the Cerner widget in https://www.va.gov/health-care/schedule-view-va-appointments/ and clicks on clicks on `Go to My VA health` link
       Then the user will be directed to the Cerner portal in a new tab. 

### Design Assets
[Registered at one facility](https://www.figma.com/file/iqjkZx2EbrZu6leL6YfN45/Cerner-Handoff?type=design&node-id=1851-27388&mode=design&t=L8VCCynpro2yf5F1-0)
[Registered at multiple facilities](https://www.figma.com/file/iqjkZx2EbrZu6leL6YfN45/Cerner-Handoff?type=design&node-id=1631-22883&mode=design&t=pgkIWY55pbPRbPeY-4)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by ldelacosta** [comment]
@young1205 - please have the UX team validate this ticket when it's ready cc: @JRRoof @outerpress

**Comment by ldelacosta** [comment]
Validated in staging for judy.morrison@id.me (registered at one facility) and ssoissoetesting+mhvcss3@gmail.com (registered at multiple facilities). Notified the UX research team to review the changes. 

Registered at one facility: 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaWhaIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--65a493d9e1bcecc7cd12d8a04a24981bc547e737/Screenshot%202023-08-31%20at%209.19.48%20AM.png)

Registered at multiple facilities: 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaXhaIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ae6d307b561a0cd23167bd2c366484d83c8935fa/Screenshot%202023-08-31%20at%209.18.03%20AM.png)

**Comment by melissa-lefevre** [comment]
Multiple Cerner facilities:
 [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbmRhIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b16a6f7c1899a070b7931491fd5923a5d9690248/Screenshot%202023-08-31%20at%2011.58.01%20AM.png)
Single Cerner facility:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbmhhIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fac8f76a1ea6db686758d0f3c5f573e43f5be597/Screenshot%202023-08-31%20at%2010.25.55%20AM.png)

**Comment by melissa-lefevre** [comment]
no issues found @ldelacosta

**Comment by ldelacosta** [comment]
Validated by the UX team. Closing out the ticket.
