### ISSUE TITLE
Contact Center Review for Veteran Facing Forms - 21-0972 Alternate Signer

### ISSUE THREAD

**Issue by tbaker1026** [department-of-veterans-affairs/va.gov-team#64063]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
*Please provide the name(s) of your product and a high-level description of your product.*
VA Form 21-0972 - Digitize Alternate Signer
### Launch Date
*Please provide the launch or rollout date and details.*
Target 9/21/2023

### Version Number
*Please provide the version number of the guide and/or video.*
1
### Product Guide
*Please provide product guide link*
https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/21-0972%20Alternate%20Signer/Form%2021-0972%20Product%20Guide.docx
### Product Video
*Please provide product video link*

### Product Video Transcript
*Please provide product video transcript link*

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
@starlow00 Note to self.

**Comment by starlow00** [comment]
In progress, will be complete this sprint.

**Comment by starlow00** [comment]
Hi @tbaker1026. I'll also need a higher-resolution image of the Workflow chart for this product guide. It's too small to read currently.

**Comment by starlow00** [comment]
Hi @tbaker1026. Just a reminder on the Workflow image for this one. Same problem I had with the image for 21P-0847.

**Comment by tbaker1026** [comment]
@starlow00   
https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/21-0972%20Alternate%20Signer/21-0972workflow.png

**Comment by starlow00** [comment]
No changes from VEO. Current copy attached.
[VA Form 21-0972 Product Guide SRT 10132023.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWhNQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4cbd0c380a29b8083c23d88e5652ea11da1856d1/VA%20Form%2021-0972%20Product%20Guide%20SRT%2010132023.docx)
