### ISSUE TITLE
Create guidelines for VA helpdesk to address first line calls related to fraud

### ISSUE THREAD

**Issue by aparsley** [department-of-veterans-affairs/va.gov-team#64074]
We need to create a training guide for Helpdesk in order to start tracking cases and remediation.

*Provide resources to help educate on prevention of fraud, monitor credit reports, changing of account passwords for enhanced security (Don't use the same passwords for general accounts especially accounts users have across VA)

**Comment by parkerbees** [comment]
Moved to Jira, clsing
