### ISSUE TITLE
`streamlined` value should be nil if flag is off

### ISSUE THREAD

**Issue by kjsuarez** [department-of-veterans-affairs/va.gov-team#64079]
## Issue Description
_VBS wants to discriminate between SW submissions that do not pass muster (`streamlined: false`) and normal FSR submissions that never had the chance to be streamlined (`streamlined`: nil)_

---
## Tasks
- [x] Force `streamlined` value to be `nil` for any submission who's user does not have the `financial_status_report_debts_api_module` flag turned on.

**Comment by kjsuarez** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-api/pull/13604

**Comment by HeatherRienks** [comment]
Per @kjsuarez - this has been reverted.
