### ISSUE TITLE
[Content] ToU consolidation into PDF Form

### ISSUE THREAD

**Issue by aparsley** [department-of-veterans-affairs/va.gov-team#64093]
Product Folder: ToU consolidation into PDF Form
* Get with Alex on consolidation and create PDF
   * Must make it a11y friendly if putting it on va.gov (might need a11y folks help on that)
* Sync with Tom on a final yes/no on whether or not to move forward with this
* [Research findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/6ed993cbc9d56b47459871f766d587789ef2d6d6/products/identity/Research/2023-07%20Terms%20of%20Use/2023-08%20Terms%20of%20use%20research%20findings.md#recommendations) that TOU PDF isn't important for folks. The mental model is to look for the TOU page on the site if needed later

**Comment by claytonzook** [comment]
At this point on hold, or at least a lower priority than for MVP release

**Comment by claytonzook** [comment]
At this time we are not moving forward with a PDF download for TOU, in part due to research finding no interest in that. Folks will look first on the website to find the TOU if they need it at some point in the future
