### ISSUE TITLE
"How to debug flaky unit tests" Section could use instructions on waitFor

### ISSUE THREAD

**Issue by radavis** [department-of-veterans-affairs/va.gov-team#64097]
### Description

Ran into an issue where my test was not waiting for state and UI changes. Tests would pass locally in isolation, but fail when run as part of a larger test suite. 

After getting assistance from a number of helpful devs, Adrian Rollett suggested that other developers could benefit from our learning and suggested an update to this section of the docs.

https://dsva.slack.com/archives/C02V265VCGH/p1692733516168829?thread_ts=1692386204.624589&cid=C02V265VCGH

### Relevant URLs

https://depo-platform-documentation.scrollhelp.site/developer-docs/debugging-unit-tests#Debuggingunittests-Howtoavoidwritingflakyunittests

### Which type of team are you on? (Platform team, VFS team, or Leadership)

VFS, MHV on VA.gov Cartographers

**Comment by vbellissimo** [comment]
Hi @radavis , thank you for flagging this. Can one of our content writers work with you directly to figure out the details of what you're suggesting would be helpful to add to the page?

**Comment by radavis** [comment]
Hey @vbellissimo, I'd be happy to collaborate with someone on your team on this issue.

**Comment by radavis** [comment]
Hi @taylojill! I'll write something up and have it to you before the end of the week.

**Comment by radavis** [comment]
Hey, @taylojill. Here's that writeup I promised: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/engineering/testing-library-wait-for.md

**Comment by taylojill** [comment]
Thank you @radavis!

**Comment by taylojill** [comment]
Here's what I did:
1. Added the waitFor content to the "How to debug flaky unit tests" section of the page.
2. Checked page for launch-blocking issues. No issues found!
3. Updated page has been deployed!
