### ISSUE TITLE
[Content] Review NIST draft directive and give feedback

### ISSUE THREAD

**Issue by aparsley** [department-of-veterans-affairs/va.gov-team#64091]
This priority area covers NIST guidance (e.g. the 800-63 Rev 4 draft), OMB policies (e.g. the pending fraud EO, memos), and VA directives. The new ICAM Governance Council is finalizing drafts of VA Directive 6510, which will cover both internal and external identity. The draft directive can be reviewed here, along with the companion handbook. I’m not sure how much opportunity left there is for feedback, but we should review and see how external identity is affected by this draft and where we would want to push back, clarify, make revision requests.

**Comment by aparsley** [comment]
Setting meeting time with Tinu, Mike, and Myself to discuss any other suggestions/feedback etc.

**Comment by tawoliyi** [comment]
Met with Amber 8/29 for steps moving forward, Mike 8/23, meeting 8/29 w/ Mike & Amber to discuss further.

**Comment by tawoliyi** [comment]
Meeting with @aparsley Amber 8/29 to discuss directive and handbook utilizing NIST 800-63 and OMB policies.

**Comment by tawoliyi** [comment]
Currently working on crosscheck with NIST 800-63

**Comment by tawoliyi** [comment]
Completed Directive Draft Alignment 9/6
