### ISSUE TITLE
FE | Alert Consistency | Update Direct Deposit alerts for load error case

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/va.gov-team#64109]
## Issue Description
When either the direct deposit information for CNP or EDU fails, there should be a warning alert component that is displayed. Right now the alert displays but there are 2 issues.

- Alert is an 'info' alert and not a warning alert
- When the EDU direct deposit fails to load the alert displays right under a content section, and it needs some margin to look correct. See screenshot below:

![Screenshot 2023-08-22 at 2 50 28 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8332986/4bb9003a-1a7d-477c-a975-548d8622981c)

Here are mobile mock-ups of the desired state:
- [CNP unavailable](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131/a/pa3zdeZ)
- [EDU unavailable](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131/a/EeKlpm2)

## Front end tasks
- Fix alert status to be 'warning' so that styling in that regard is correct
- When EDU alert is displayed add margin to the top of it to match other alert's spacing 
- If it would be easy to update copy as part of this work, check with Pam to see if any copy changes need to be made since she recently completed an audit.

## Acceptance Criteria
- [ ] Designer comments on this issue to approve page styling 
- [ ] Validated in staging. (use chrome devtools to block one or the other endpoint)

**Comment by adamwhitlock1** [comment]
@andaleliz So I was looking at the code for this, and what I am currently seeing is that actually if _either_ of the direct deposit api calls fail to load, then we are showing the entire page to be blocked with the singular alert like this:

<img width="950" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEROQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8f20d2288def30541e31158c00c9283d8754c8db/Screenshot%202024-03-11%20at%2010.32.44%E2%80%AFAM.png" alt="Screenshot 2024-03-11 at 10.32.44 AM.png" />

My recollection is that this was done because if the CNP direct deposit api call fails, then that is where the fiduciary, deceases, and incompetent indicators come from, so we should just block all of the direct deposit if we can't get those indicators.

This renders this ticket unneeded, and the code essentially for each section having an alert is unreachable at this point. 

Do my above assumptions seem reasonable, and if so should we remove these alerts from the code and the design files?

**Comment by andaleliz** [comment]
>Do my above assumptions seem reasonable, and if so should we remove these alerts from the code and the design files?

yes and yes! They're already removed from the post-migration design files.

**Comment by adamwhitlock1** [comment]
Okay, thank you @andaleliz for the ⚡ fast response. @mtcA6 I think we can just close this one out with wont do/dont need.

**Comment by adamwhitlock1** [comment]
I ended doing a little work around this, and have a PR up to clean up unit tests, but also fix this alert in the case that CNP loads fine but Ch33 does not load.

**Comment by mtcA6** [comment]
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/5d82a55e-019b-4232-835d-50c9ceb4e2ba)

cool I'm able to validate this change, that looks way better than how it was blocking the entire page before. 

@adamwhitlock1 Should we be concerned that the edu benefits are failing on so many test accounts? I see that endpoint failing on I think every account I've loaded. I've tried so many different users today it's been dizzying I should have kept better track.

**Comment by adamwhitlock1** [comment]
Today the ch33 endpoint has started working again. Unfortunately there is no darn users with EDU that we can check in staging since the one that has both is flagged as deceased. I will double check that user though and make sure it is shown if they are set to non-deceased manually.

**Comment by mtcA6** [comment]
What's weird though, user 380 looks like it should have both but isn't tagged as deceased. 

    "data": {
        "id": "",
        "type": "hashes",
        "attributes": {
            "controlInformation": {
                "canUpdateDirectDeposit": false,
                "isCorpAvailable": true,
                "isEduClaimAvailable": false,
                "isCorpRecFound": true,
                "hasNoBdnPayments": true,
                "hasIndex": true,
                "isCompetent": true,
                "hasMailingAddress": true,
                "hasNoFiduciaryAssigned": true,
                "isNotDeceased": true,
                "hasPaymentAddress": false,
                "hasIdentity": true
            },

any idea what's up there?
