### ISSUE TITLE
Orientation Sessions Slide Decks

### ISSUE THREAD

**Issue by davidconlon** [department-of-veterans-affairs/va.gov-team#64114]
### Description

Orientation Sessions Slide Decks are currently housed on Google Docs.
Not only is this is not an approved VA system but as a result these documents are inaccessible from the VA network (when on prem) or when VA staff person is using the VPN.

cc: @EWashb for awareness

### Relevant URLs

https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions

### Which type of team are you on? (Platform team, VFS team, or Leadership)
leadership

**Comment by EWashb** [comment]
This is likely require coordination with Governance team as well.

**Comment by vbellissimo** [comment]
Hi @shiragoodman , I wanted to put this request on your radar. Do you have any thoughts on how you'd like to handle this information? Our team can help remove the links or replace with new links to different formats if needed. Let me know if you have any ideas. Thanks.

**Comment by shiragoodman** [comment]
thanks @vbellissimo . This is something we're aware of. Long term goals for orientation include removing the slide decks all together and just directing people to the Platform Website. We'd like to have a Orientation checklist on PW that just links out to other PW pages that people need to know, ideally with short videos on each page explaining the info on the page. 

I don't have a solution for how we can handle this in the interim. What other formats are available to us?

**Comment by vbellissimo** [comment]
@shiragoodman can you turn the slides into PDFs? We could do that in the interim until the longer-term strategy is in place.

**Comment by shiragoodman** [comment]
we could, however PDFs are notoriously inaccessible. We try and practice what we preach, so another solution would be preferred.

**Comment by vbellissimo** [comment]
@shiragoodman Formats available would be pointing to other PW content, PDFs, video or images. None of which are a viable short term solution, except for an accessible PDF.

Do you happen to know about how many people are trying to access from the VA network? I assume most of our audience are orientation attendees who have access to google formats. My recommendation is we add a message next to each link that warns the visitor that the link may break if they are within the VA network and they can contact your team for a copy of the information. This is the solution we use to warn visitors when links may require SOCKS proxy, etc. What do you think?

**Comment by shiragoodman** [comment]
I think that's a good immediate solution, but I imagine leadership will still want us to find another option for the slides at some point. 

What about Github? Excel and word docs are definitely downloadable, maybe viewable too. I know we're trying to move away from having Platform guidance on Github, but it is likely still preferrable over having things in a Google Drive.

**Comment by vbellissimo** [comment]
In speaking with our product owner about this, we think the best solution is to add disclaimers about limited access if using the VA network for now.

Github is not something we want to go back to, given the efforts we've put on getting away from that format for documentation in general. Other Microsoft formats you mentioned @shiragoodman are likely okay with our team and probably permissible to the VA network, as long as they are provided with any accessibility concerns in mind.

**Comment by shiragoodman** [comment]
I'm okay with this. 

FYSA - I will be working on creating a doc to demonstrate the desired future state of Platform Orientation. I'll share in this thread when ready.

**Comment by vbellissimo** [comment]
@shiragoodman , sounds good. I'll ask one of my team mates to reach out to you to confirm the disclaimer language and we will update the page accordingly.

**Comment by taylojill** [comment]
We received Shira's approval to include a disclaimer for Slide deck links to the General Orientation Presentation. The disclaimer language is: (Limited access if using the VA network). See image below.

**Comment by taylojill** [comment]
All tasks completed. Here's what I did:
1. Added disclaimer statement to all Slide deck links.
2. Checked page for launch blocking issues. No issues found.
3. I deployed the updated page.

**Comment by shiragoodman** [comment]
thanks Jill!
