### ISSUE TITLE
Vets-api terminal access for [Samuel Stuckey]

### ISSUE THREAD

**Issue by SamStuckey** [department-of-veterans-affairs/va.gov-team#64119]
### Your Name

Samuel Stuckey

### Your GitHub handle (terminal access is managed through GitHub)

SamStuckey

### Your dsvagovcloud AWS user name (if applicable)

Sam.Stuckey

### Team, Role, and Company of the target individual

Team Carbs (DBX-2), Engineer, Oddball via CoForma

### Product Manager (PM) name and email

Austin Price austin.price@coforma.io

### Product Owner (PO) name and email

Jennifer Bertsch Jennifer.Bertsch@va.gov

### COR Name (leave "None" if you listed an AWS user name above)

None

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

None

### Please confirm if you are on the VFS Team Roster or Platform Team Roster

- [X] [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Please confirm E-QIP Transmittal/Adjudication. This could be a screenshot of your Transmittal/Adjudication email, a link to another request where you've submitted this proof (i.e. AWS/SOCKS), etc.

- [X] I have attached proof that I have either transmitted my E-QIP survey or previously received a favorable decision (by including in "Additional Notes" section below)

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### Additional Notes

I will be taking over the 526 batch retry work previously handled by @kylesoskin .  

<img width="808" alt="Screenshot 2023-08-23 at 10 18 44 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/15328092/91344ed4-754d-491c-a6b2-997cc980b749">

### Additional resources for Support Engineer

- [ ] For users on a VFS team but not in the VFS Team Roster, they must start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] Instructions for handling requests [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access) - Support Only

**Comment by lindsay-insco** [comment]
Access to `prod` is pending approval by OCTODE, and we'll update you as soon as it's available.

**Comment by BillChapmanUSDS** [comment]
Access Approved as per current 6 month policy

**Comment by lindsay-insco** [comment]
Production access has been extended for 6 months, expiring 02/29/24 (Leap year!). Please set a reminder for yourself to return to this Issue and re-request access within 1 week of the expiration date. You'll receive 1 reminder with a 72 hour window to respond. Failure to do so will result in lost access and will require you to fill out a new request.

**Comment by lindsay-insco** [comment]
Slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1693325592757189)

**Comment by lindsay-insco** [comment]
@SamStuckey Your Vets API Terminal Production access has expired.

Would you like to request an extension? You have 72 hours to respond, or your
access will be revoked and you will need to fill out a new request

**Comment by lindsay-insco** [comment]
@SamStuckey more recent linked prod ticket [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83870)

Looks like prod access would expire 11/29/24 

Please set a reminder for yourself to return to this issue and re-request access within 1 week of the expiration date. You'll receive 1 reminder with a 72 hour window to respond. Failure to do so will result in lost access and will require you to fill out a new request.

**Comment by davidpetras** [comment]
@SamStuckey Your Vets API Terminal Production access has expired.

Would you like to request an extension? You have 72 hours to respond, or your
access will be revoked and you will need to fill out a new request

**Comment by davidpetras** [comment]
@SamStuckey  since you have not responded we have removed your prod access. You will have to submit a new request if you would like to have access again.
