### ISSUE TITLE
OCTO-DE Crew Jonathan Kamens Onboarding: 

### ISSUE THREAD

**Issue by BillChapmanUSDS** [department-of-veterans-affairs/va.gov-team#64126]
### What OCTO-DE Crew is the team member joining?

Platform

### What OCTO Community of Practice is the team member part of?

Engineering

### Has user received VA.gov email address?

- [x] User has @va.gov email address

### VA Email Address

jonathan.kamens@va.gov

### Has user been added to Department of Veterans Affairs Github Organization?

- [x] User is member of Github org

### Github Username

JonathanKamensDVA

### Has user been added to DSVA Slack?

- [x] User is member of DSVA Slack

### Platform Onboarder Tasks

- [x] Add to Slack group: @octo-de-platform https://dsva.slack.com/admin/user_groups
- [x] Add to Github team: octo-de-platform https://github.com/orgs/department-of-veterans-affairs/teams/octo-de-platform
- [x] Post welcome Slack message: #platform-team
- [x] Add to Confluence group "platform-crew-octo-de": https://admin.atlassian.com/s/10f8a514-fd86-4b32-8ba3-c0bfc6969f88/groups/81f1ea1a-fc6d-4b27-aed5-0bb73dd86c02
- [x] Update Team Roster: https://vfs.atlassian.net/wiki/spaces/LEAD/overview#OCTO-DE-Leadership (can be seen on https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [x] Schedule recurring 1:1
- [x] Pagerduty OOB Deploy setup - Admin : https://vfs.atlassian.net/wiki/spaces/ECP/pages/1959165976/Out+of+band+deployment+approval#Admin
- [x] Add to VA GOV DEVOPS Service Now group: https://github.com/department-of-veterans-affairs/CTO/discussions/100
- [x] Add to MS Teams / Sharepoint group: https://teams.microsoft.com/l/team/19%3aWKiBsscnhmaeQZivkkji2GkkHwY1RNX0AXrCfiJdkwg1%40thread.tacv2/conversations?groupId=1dc3d637-a996-47c3-a0cb-0562475da049&tenantId=e95f1b23-abaf-45ee-821d-b7ab251ab3bf

### Platform Onboardee Tasks

- [x] Register for Platform Orientation: https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=governance-team&template=orientation-epic.md&title=Platform+Orientation+Template+%5BYour+name+here%5D
- [x] Schedule PO meetings with teams
- [x] Update Slack profile in accordance with: https://depo-platform-documentation.scrollhelp.site/getting-started/Request-access-to-tools.969605215.html#Requestaccesstotools-Slack
- [x] Pagerduty OOB Deploy setup - User : https://vfs.atlassian.net/wiki/spaces/ECP/pages/1959165976/Out+of+band+deployment+approval#User
- [x] Link to Platform team welcome guide: https://vfs.atlassian.net/wiki/spaces/AP/pages/1413808450
- [x] Link to Platform team meetings: https://vfs.atlassian.net/wiki/spaces/AP/pages/2141519911/Platform+Meetings
```[tasklist]
### Custom Tasks
```

**Comment by JonathanKamensUSDS** [comment]
Hello!

I now have a VA email address, Jonathan.Kamens@va.gov.

I have also created a new Github account to isolate my VA access. The username of that account is "JonathanKamensDVA".

I need all of the access currently assigned to JonathanKamensUSDS to be transferred to JonathanKamensDVA.

I also need additional access to be assigned to JonathanKamensDVA to enable me to edit tickets in this repository more than JonathanKamensUSDS can now, e.g., JonathanKamens can't edit ticket descriptions or edit the labels assigned to a ticket, and I need to be able to do that.

@davidconlon can you help me with this? It's somewhat urgent since I need to be able to review and approve access requests while @BillChapmanUSDS is out of town for two weeks starting COB today.

**Comment by JonathanKamensUSDS** [comment]
(Also, Bill says he doesn't have the access, and Ray's also out of town between now and Wednesday, so I'm hoping there's someone else who can get me set up.)

**Comment by annekerr49** [comment]
Can we close this item now that Pager Duty licenses have arrived?

**Comment by JonathanKamensDVA** [comment]
Not quite yet I need to review it and make sure I've covered everything that needs to be covered. Thanks.

**Comment by mchelen-gov** [comment]
Added to `VA DOT GOV DEVOPS` SNOW group.
