### ISSUE TITLE
Prometheus prod deploy fails

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#64134]
### Summary
Prometheus in prod has not deployed successfully since January 2023. This is blocking https://github.com/department-of-veterans-affairs/devops/pull/13241 and any other prometheus alerts that need to be modified or deleted in the future.

### Definition of done
- [ ] Prometheus is deployed in prod

**Comment by ph-One** [comment]
- Resolved (utility was trying to deploy a file that did not existing)
- https://dsva.slack.com/archives/C30LCU8S3/p1695923408444999

**Comment by ph-One** [comment]
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/1580012/9c27a5b2-62ab-42ca-ae8f-2943f60e638b)


![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/1580012/671e2fe1-30bf-40de-bf74-a1daa358388b)

**Comment by rmtolmach** [comment]
- https://github.com/department-of-veterans-affairs/devops/pull/13517
