### ISSUE TITLE
SPIKE | Null Claim - 674 - Hours per week in Class

### ISSUE THREAD

**Issue by tblackwe** [department-of-veterans-affairs/va.gov-team#64141]
In 674, we ask the Veteran how many hours per week their dependent is in class.  If the veteran enters more than X* hours, then BGS rejects the claim as out of bounds.

\* I assume X is 168 (24*7) but I do not know for certain. needs discovery

Once we determine what X is, we can prevent these issues by adding data validation on the appropriate input field

[Exceeds Precision Error
](http://sentry.vfs.va.gov/organizations/vsp/discover/platform-api:ada979e9a8fa45c9ac675cabde9246ab/?end=2023-07-03T23%3A59%3A59.000&field=title&field=event.type&field=project&field=user.display&field=timestamp&name=All+Events&query=job%3ABGS%3A%3ASubmitForm674Job&sort=-timestamp&start=2023-07-03T00%3A00%3A00.000&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1#grouping-info)

[Detected Exception
](http://sentry.vfs.va.gov/organizations/vsp/discover/platform-api:6a77503090954e66985bc21bbfe8ef70/?end=2023-07-03T23%3A59%3A59.000&field=title&field=event.type&field=project&field=user.display&field=timestamp&name=All+Events&query=job%3ABGS%3A%3ASubmitForm674Job&sort=-timestamp&start=2023-07-03T00%3A00%3A00.000&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1)

[BGS code for discovery](https://github.com/department-of-veterans-affairs/vets-api/tree/master/lib/bgs)

Sample Data from linked exception:
` {"name"=>"University of North Carolina at Charlotte",
     "address"=>{"country_name"=>"USA", "address_line1"=>"9201 University City Blvd", "city"=>"Charlotte", "state_code"=>"NC", "zip_code"=>"28223"},
     "term_begin"=>"2022-08-16",
     "date_term_ended"=>"2023-05-16",
     "classes_per_week"=>4,
     "hours_per_week"=>1200},`

**Comment by tblackwe** [comment]
@zack added links to sentry exception and BGS code.

**Comment by sortizsh** [comment]
Hold off until Steve is back from retreat after labor day.

**Comment by zack** [comment]
So thanks to Thomas' great sleuthing, we now have copies of the schema for the relevant database table. The hours columns are typed as `NUMBER(4,1)`, [which means](https://www.oracletutorial.com/oracle-basics/oracle-number-data-type/) they can take 4 total digits with 1 to the right of the decimal place. That means it can take numbers from 0.0 to 999.9. It cannot accept 9999.

I suggest that we implement front-end validation such that the number of hours in class must be less than or equal to 168 (the total hours in a week). Any number larger than that is necessarily a mistake and if we try to go lower than that (40? 50? 60?) it could get fuzzy, especially if the student is in a boarding school or in multiple programs or something with long/weird hour.

This means we'll never see a db error for this again and we'll also never accept a value that breaks the known laws of physics; two goals I personally find appropriate.

**Comment by zack** [comment]
@steele-lm and @tblackwe just bringing your attention to this update when you have a minute. :) ^^

**Comment by steele-lm** [comment]
@zack I agree with your approach -- great research. I'll update the follow on ticket #64344 with the info.

**Comment by tblackwe** [comment]
agreed on approach. thanks Zack!
