### ISSUE TITLE
Flipper UI access for Thomas Reynolds

### ISSUE THREAD

**Issue by tsr-rise8** [department-of-veterans-affairs/va.gov-team#64154]
### Your Name

Thomas Reynolds

### Your GitHub handle (Flipper UI access is managed through GitHub)

@tsr-rise8

### Team, Role, and Company of the target individual

VA Notify Software Engineer, Rise8 | Oddball

### Please confirm if you are on the VFS Team Roster, Platform Team Roster or are a Federal User

- [X] [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [X] Lesser Environments (Dev/Staging/Sandbox)
- [X] Production (if requesting, justify prod access below)

### Reason for Production Access (If requested)

As a software on the VA notify team, I need to be able to enable/disable the flipper feature flags for our email notifications.

**Comment by lindsay-insco** [comment]
Found in VFS Team Roster 

Access to lesser environments and prod granted.
