### ISSUE TITLE
[Congressional]  V10754502 - Issues with VA locking DS login (Rep. Green) Due 9/18/23

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#64175]
## Issue Description
Veteran states in 2019 the VA Fraud Department locked his DS Logon, but he doesn’t use the VA. Veteran needs this corrected because they do not use health care services through Fort Campbell, KY and can’t use the new MHS Genesis Patient Portal because of the previous actions by the VA. Veteran's contact information is provided on documents.

---
## Tasks
- [ ] Review congressional correspondence
- [ ] Resolve issue 
- [ ] Notify Veteran and congressional correspondence channel of solution. 

## Acceptance Criteria
- [ ] _Veteran issue will be resolved or responded to with final answer to issue.
- [ ] Congressional Correspondence will receive details of the resolution.

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by clantosswett** [comment]
Chris Johnston reached out to DMDC to review this case on 8/25. Will wait to hear back from the email thread before doing anything more with this.

**Comment by clantosswett** [comment]
Closing this because it is in DMDC purview.
