### ISSUE TITLE
[Congressional] V10751495 Unable to access ID ME (Rep. McCaul) Due 9/26/23

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#64180]
## Issue Description
Constituent is having issues accessing his travel pay. Veteran's contact information is provided on documents.
Case Attachments in Folder: V10751495 - Unable to access ID ME (Rep. McCaul)

---
## Tasks
- [ ] Review congressional correspondence
- [ ] Resolve issue 
- [ ] Notify Veteran and congressional correspondence channel of solution. 

## Acceptance Criteria
- [ ] Veteran issue will be resolved or responded to with final answer to issue 
- [ ] Congressional Correspondence will receive details of the resolution 

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by clantosswett** [comment]
This seems to be an ID.me issue. This was escalated to ID.me's channel today. Will complete necessary outreach once we hear back with initial investigation from ID.me.

**Comment by clantosswett** [comment]
ID.me responded saying they have not received any support requests from the user. I let the user know they should contact ID.me directly if they are having issues creating an account.

**Comment by clantosswett** [comment]
Veteran responded on 9/19 saying the answer provided wasn't sufficient. I responded letting the Veteran know that I could ask ID.me to contact him directly if that would help.
