### ISSUE TITLE
Pull list of APIs timeouts per ITF Postmortem

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#64199]
As part of the ITF Retro, team 2 agreed to pull a list of APIs used in the 526 application to identify where there may be disconnects between the API and the backend API Service. 

Acceptance criteria:

1. Document list of endpoints for each 3rd api call
2. Get our call timeout and document
3. Get 3rd part service timeout for each and document

**Comment by austinjprice** [comment]
cc: @va-albers

**Comment by SamStuckey** [comment]
[WIP document to track discovery](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/engineering_research/endpoint_timeout_discovery.md)

**Comment by SamStuckey** [comment]
Handed off to @RakshindaAslam and crew
