### ISSUE TITLE
Standalone sign-in page - UX & content updates

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#6420]
**User Story**
When a Veteran navigates directly to the My VA Health (Cerner) website, they need landing page from which they can log in with the same federated login options as exist on the VA.gov modal

**Tasks**
- Align on content changes

**Comment by bridgethapner** [comment]
Hi there @peggygannon - Ambika opened a new ticket for the Standalone sign-in page. 

Here is the wireframe we looked at today: https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/403239055

Copy should be universal so this page can eventually work for multiple sites. Please let me know if you have any questions!

**Comment by peggygannon** [comment]
Hello, @bridgethapner  please see below for content recommendations to the standalone sign in page. Let me know if you have any questions. I've also put these comments into the wireframe. Thx. 

1. Please change login to sign in, per VA.gov styleguide.

So it would read:
One sign in. A lifetime of benefits and services at your fingertips.

2. also, i think we can still keep the bullets that exist on the current page to show all the services available. They seem general enough

So it would read: 

One sign in.  A lifetime of benefits and services at your fingertips. 
	Check your disability claim and appeal status
	Find out how much money you have left to pay for school or training
	Refill your prescriptions and communicate with your health care team
	...and more

Use your existing DS Logon, My HealtheVet, or ID.me account to sign in to access and manage your VA benefits and health care. 

-----

3. Can we alter the content at the bottom of the page to remove VA.gov? This reads like boilerplate content, so I wanted to see if we need to run this by a stakeholder before removing VA.gov?

**Comment by bridgethapner** [comment]
@peggygannon - Ty again for your content! I posed the question re VA.gov in the content about the footer on Slack. 

@hinzed1127 
Desktop wireframe here: https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/screens/403239055

A couple of design notes:
- Margin of 50px above and 30px below H1
- Aadd 20px of padding to the left of the explanation content? 
- Increase the height of the blue top bar from 98px to 155px

Mobile wireframe here: https://adhoc.invisionapp.com/share/5QWAJJQNG2J#/screens/408139784_1_-6420_-_Standalone_Signin_Page_-_Mobile

- On mobile, the sub-head "One sign in.." should come above the sign-in box.

**Comment by peggygannon** [comment]
@bridgethapner I reviewed the updated prototype for the standalone page. Updates look good.
