### ISSUE TITLE
FE | Direct Deposit | Update to radio button 

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#64204]
## Background 
This issue was found as part of our 2022 accessibility audit. Mocks are below to switch the account selection type from a dropdown to a radio button. 

>@mtcA6 moving to validate - all the mocks have been updated:
>- [mobile](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131/p/837E4048-F554-48CA-B877-2C1007AB5D43/canvas)
>- [desktop](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131)
>_Originally posted by @andaleliz in https://github.com/department-of-veterans-affairs/va.gov-team/issues/63495#issuecomment-1690810416_
            

## Acceptance Criteria 
- [ ] the dropdown is now a radio button

**Comment by mtcA6** [comment]
on our planning call on 9/13 we discussed working this ticket with 65506

**Comment by adamwhitlock1** [comment]
@mtcA6 This wasn't part of this sprint, but while I was rearranging the fields for #65506, I went ahead and changed it to a radio group, since it is in the same part of the code. So we can validate this alongside that ticket and I guess add it to unplanned work for this sprint?
