### ISSUE TITLE
[ARGO CD] Discovery, how do we handle/use argo in our deployment process?

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#64217]
## Description
We need to determine if we want to use the pull vs the push model for Argo.  This will have a large impact on product onboarding and each cluster deployment

## Acceptance Criteria
- [ ]  A process for Argo CD is determined 
- [ ]  The determined process is communicated to impacted parties 
- [ ]  The determined process is documented and published to the appropriate places

## Refinement Guidance - Check the following before working on this issue: 
- [x] _Team label assigned ("platform-tech-team-2")_
- [ ] _Epic assigned (if needed)_ 
- [ ] _Estimated (points assigned)_
- [ ] _Sprint assigned (once planned)_
- [ ] _Team member(s) assigned_
- [ ] _Understands how this work aligns with the overall platform_

**Comment by npeterson54** [comment]
Moving out of sprint due to AL1 priorities

**Comment by ph-One** [comment]
This will be discussed in the SRE meeting. Closing the ticket as communication has started. Additional tickets will be created once work items are identified
