### ISSUE TITLE
Appeal Modernization Process (AMA)/Decision Review Part 2

### ISSUE THREAD

**Issue by AkucherGCIO** [department-of-veterans-affairs/va.gov-team#6421]
## Product Outline
[Decision Review Requests and Appeals Digital Experience Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/README.md)
[Appeal Modernization Process (AMA)- Follow Up Changes Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/AMA%20Follow%20Up/AMA%20Follow%20Up%20Product%20Outline.md)

## High Level User Story/ies
- As a Veteran, I would like to submit all new appeals under the decision review process.
- As a Veteran, I would like to use the VA.gov website to find content related to both the decision-review and legacy-appeal processes.
- As a content writer, I would like to balance plain language [appeal] with the Client’s desire for adoption of decision review terminology.

## Hypothesis or Bet
- IA Recommendations: Identify optimal structure for content location and entry points, and address nav labeling.
-  Move to Drupal: Identify and rectify anomalies that will allow all decision review pages to be moved from GitHub to Drupal.
- Claim status tool CTAs: Make CTAs for this tool consistent across all pages.
## OKR
_Which Objective / Key Result does this epic push forward?_

### What must be true in order for you to consider this epic complete? 

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## Urls

1. VA decisions reviews and appeals https://www.va.gov/decision-reviews/
2. After you request a decision review https://www.va.gov/decision-reviews/after-you-request-review/
3. File a Supplemental Claim with new evidence https://www.va.gov/decision-reviews/supplemental-claim/
4. Request a Higher-Level Review https://www.va.gov/decision-reviews/higher-level-review/
5. Request a Board Appeal https://www.va.gov/decision-reviews/board-appeal/
6. After a Board Appeal ... https://www.va.gov/decision-reviews/board-appeal/after-board-appeal-decision/
7. Multiple party contested claims https://www.va.gov/decision-reviews/multiple-party-claims/
8. Fiduciary claims https://www.va.gov/decision-reviews/fiduciary-claims/
9. Insurance claims https://www.va.gov/decision-reviews/insurance-claims/
10. FAQs https://www.va.gov/decision-reviews/faq/
11. Get help with... https://www.va.gov/decision-reviews/get-help-with-review-request/
12. Board hearings with a VLJ https://www.va.gov/decision-reviews/board-appeal/veterans-law-judge-hearing/

**Comment by AkucherGCIO** [comment]
03/04/20 PW Grooming
@AkucherGCIO - Add the 508 accessibility issues to this epic.

**Comment by MickinSahni** [comment]
Hey Tze, Peter — following up to the [thread here](https://dsva.slack.com/archives/CQV81GBBM/p1585160871002000) re: the AMA effort and the Collab Cycle. 

I'm flagging this epic for your QA expertise along with these tickets:
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/5541
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/6799
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/6371
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/6359

@tzelei @pjhill

**Comment by pjhill** [comment]
> * #5541
> * #6799
> * #6371
> * #6359

@MickinSahni -- I'm scanning through these issues.  It looks 3 out of 4 of them are closed, and it looks like they've all been resolved.  Once you've verified that the resolutions are in place, I find that it is beneficial to include test cases that verify the resolution as part of your regression testing for the next sprint or two.

@tzelei -- I'd recommend creating test cases that verify the fixes described in those tickets.

Are you looking for a different form of feedback, or is this what you had in mind?
