### ISSUE TITLE
Content review:  VA.gov Forms Sketch Template

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#6422]
## User story
VSP Content feedback on Form sketch template staging review

Template prototype we're reviewing:  https://vsateams.invisionapp.com/share/A2W64P7YUG9

------

## Content feedback is here: 
- Screen 1: Eligibility blue box doesn't have updated content format (for example, we no longer use "Whose covered?" subheading in eligibility content. Will find updated drupal template for you! 

- Screen 1: crisis alerts should be placed above eligibility boxes on the page
- Screen 6: I've recently completed a form introduction page template providing guidance on this page (https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/content/form-introduction-page-template.md
- Screen 6: blue and green CTA buttons should start with action word (guidance https://design.va.gov/content-style-guide/button-labels)
- Screen 14 Form labels should be sentence-cased 

Overall feedback: 
Use sentence-case capitalization for most content, including page titles, headings, subheadings, buttons, and text links, unless a word is a proper noun. Don’t capitalize common words for emphasis or importance

some additional content resources for you! Feel free to link or add to your resources as needed. 

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/content/form-content-process.md
https://design.va.gov/patterns/messaging-dictionary
https://design.va.gov/patterns/messaging-error-messages

**Comment by rebeccawalsh** [comment]
@peggygannon Do you mind sending me the updated drupal template for your first feedback point?

**Comment by peggygannon** [comment]
Hi, @rebeccawalsh Yes, am tracking this down and will post to this issue.
