### ISSUE TITLE
[identity-dashboard] - Add valid TLS cert to identity dashboard

### ISSUE THREAD

**Issue by rileyanderson** [department-of-veterans-affairs/va.gov-team#64239]
## Issue Description
HTTPS is enabled but it is using an internal cert. Internal certs are seen as invalid because there is no CA. We need to find a way to add a valid cert behind socks. Can we use Let's Encrypt, an Amazon cert, or another service?

Historical Information:
- https://dsva.slack.com/archives/C02SLSSGSBX/p1657212579228699
-  https://github.com/department-of-veterans-affairs/va.gov-team/issues/36494#issuecomment-1047248065
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/36494#issuecomment-1047324219

Question Asked in platform-devops-cop
- https://dsva.slack.com/archives/C04CYC4LMU6/p1692811179197719

**Comment by parkerbees** [comment]
Moved to Jira. Closing.
