### ISSUE TITLE
Host Call Center focus group

### ISSUE THREAD

**Issue by djmunoz1** [department-of-veterans-affairs/va.gov-team#64234]
Context: 
As a Veteran, I want to be able to contact any call center and be provided support for questions regarding the Login.gov Adoption Communication campaign. The support team should have supporting documents to answer my questions as the communication campaign is rolled out. The supporting documents will provide information relevant to whether I am a Veteran with modern credentials or not and which type of mode of communication I have received. 

Acceptability Criteria:

- [x] Contact volunteers (Carnetta, Chante, Brenda) and align on times

Definition of Done

- [x] Focus group scheduled 

- [ ] Docs prepped and sent out to stakeholders at least 24 hrs in advance of the mtg

**Comment by SophiaPhilipMO** [comment]
Focus group scheduled for 8/31
