### ISSUE TITLE
Design experience for creating a case ID

### ISSUE THREAD

**Issue by porta-antiporta** [department-of-veterans-affairs/va.gov-team#64238]
# Use Case

As a Veteran who was opted to proof in person, I am able to bind my account to an in person proofing so that I have confidence that only my identity is associated to my account.

# Background

This comes after the welcome screen. 
By this point the Veteran has a Login.gov account, we now need to help them attain a case ID that they will take to the IPP location.

- This code will be used to present to the proofing agent that will ensure we have a connection between the IPP event and the Login.gov account that will become verified.
    - It's going to be bound to a Login.gov UUID
    - Multiple Case IDs can be bound to a Login.gov UUID
    - However, a Case ID can only be bound to 1 Login.gov UUID
    - i.e. Case ID n : 1 Login.gov UUID
  
Must have 
- [x] Understanding of what the experience looks like on the app
- [x] Understanding of what notifications will exist outside of app
- [x] Handling of code expiration.

Open
- [x] For the pilot, should we be implementing a "search for IPP locations"? Or just have a placeholder where we'll fill in once we have finalized the pilot location?

Devious QA mindset
- [ ] What happens if a Veteran has an existing case ID and tries to create a new one?

# Acceptance criteria
- [x] Mid fidelity mockups for application (screens model Login.gov design system
- [x] Detailed sitemap involving application, Login.gov, Veteran and email/SMS (other notification channel outside of app)

**Comment by skirkman16** [comment]
I am going to create a sitemap [here](https://app.mural.co/t/innovationboards1199/m/innovationboards1199/1693247301831/8d4607e5fb235c42b53b37b31e2ce561f55de81c?sender=u99cd1ac4f5c240d8dffd4204) to complement the mockups I am building. Mockups live [here](https://www.figma.com/file/PfrWKmxiQ5RjChwx6I18QE/IPP-Wireframes?type=design&node-id=132%3A2&mode=design&t=Iso0mxDFN429MqxT-1) under mid-fi 8/30

**Comment by skirkman16** [comment]
Updating the materials for demo today but the materials (prototype and sitemap) will be finalized by tomorrow's demo. We will plan on sharing them out with Login.gov in our meeting with them next week. My answer for the open question would be let's determine the sites within an area and recruit people from that area to complete IPP. This is assuming we are testing the functionality of the app and we are focusing on a more metropolitan area. We can discuss this idea with Login and with MHV if we determine that coordinators will be our proofing agents. No answer yet for the Devious QA but planning on discussing this in tomorrow's IPP meeting
