### ISSUE TITLE
Data mapping: API Architecture 

### ISSUE THREAD

**Issue by melissa-lefevre** [department-of-veterans-affairs/va.gov-team#64256]
## Description

Collaborate monthly with other VA teams to knowledge share and develop resources. 

## Acceptance Criteria

- [x] Create a MURAL to share with other VA teams displaying the [API Architecture diagram](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/appointments/va-online-scheduling/engineering/architecture). 

- [x] Schedule a monthly meeting

**Comment by melissa-lefevre** [comment]
[Mural of API Diagram](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1692889819900/359e62f45ee1d06e8d00f0d1614b75c24e618436?sender=uc6180068871478c530ab2434)

**Comment by outerpress** [comment]
Initial work is done, tracking the rest in a separate ticket
