### ISSUE TITLE
[BE] 10-10EZ Performance: ENROLLMENT ELIGIBILITY Vets-API Load Testing

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#64267]
As a Veteran, I would like to be able to submit my 10-10 EZ during peak submission times so that I can get the PACT Act-related benefits that I have earned.

- [ ] Use Locust 
- [ ] Utilize existing examples of testing form
- [ ] Test Enrollment Eligibility API at 100x the normal rate (100x/minute)
- [ ] Record results
- [ ] **Success: We know that the Submission API can handle 100x requests per minute and that they get to the ES okay. We have documentation, ideally visual-based, to show this.**

---------------------------
## Background
Our Health Tools Crew Chief, Lauren Alexanderson, informed us that the CIO and OIT leadership would like us to demonstrate readiness for up to a 10x spike in submissions between 9/20-9/30. We'll be looking to do some load testing within the next week (Sprint 107 8/23-9/5) on this and other downstream dependencies.
See the [meeting notes](https://github.com/department-of-veterans-affairs/va.gov-team/issues/64123#issuecomment-1690404808) in the comments below for more information.

### Resources
- [Platform info on Load Testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/load-tests)
- Example [Address Validation load test](https://github.com/department-of-veterans-affairs/devops/tree/master/loadtest/address_validation#setup)
- Example from Check-in team - [Testing Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/url-shortener/performance_testing.md)
- Example from Check-in team - [Report](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/url-shortener/performance_testing_report.md)
- Example tests reports
     - [Locust test definition](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/url-shortener/supporting_docs/locustfile.py)
     - [Baseline test report](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/url-shortener/supporting_docs/baseline_test.html)
     - [Production load test report](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/url-shortener/supporting_docs/production_load_test.html)
     - [Stress test report](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/url-shortener/supporting_docs/stress_test.html)

The [draft post mortem](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/1227) of the disability benefits incident that sparked the current scrutiny of the 1010EZ resiliency
>- tl;dr, vets-api processes submissions synchronously, downstream service got bogged down, vets-api timed out before downstream service could finish processing, errors back to user.

**Service calls from the FE:**
> The 1010 specific calls from the FE i see are:
> - GET v0/health_care_applications/enrollment_status
> - GET v0/health_care_applications/rating_info
> - POST v0/health_care_applications
> - POST /v0/hca_attachments
> 
> then there are the shared vets-api service calls from the FE:
> - GET v0/feature_toggles
> - GET v0/backend_statuses
> - GET v0/user
> - GET v0/maintenance_windows
> - DELETE / GET / PUT v0/in_progress_forms

Links to our [Testing Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/engineering/Load%20Testing/10-10EZ%20Loan%20Testing%20Plan.md) and [Report](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/engineering/Load%20Testing/10-10EZ%20Load%20Testing%20report.md) documents

**Comment by lihanli** [comment]
@alexseelig 
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/830084/b3be10d0-2371-4e9c-9a47-f16ac2d14b6f)
I made 4114 test requests to the enrollment eligibility endpoint in the staging environment at a rate of 6.86 requests per second. This endpoint connects to both the HCA e&e api and the MPI API. There were no errors. The MPI data in the screenshot is for a fake test user, not real PII.

**Comment by batemapf** [comment]
> a rate of 6.86 requests per second

@lihanli how does this compare to historicals in production?

**Comment by batemapf** [comment]
so 4184/(7*24*60*60) = 0.0069/s, or 944x normal throughput. feels sufficient :-)

**Comment by lihanli** [comment]
### cpu load
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/830084/ff61a1f6-a8d8-42a8-9089-e1c340a62f0c)

### api latency
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/830084/b481f6aa-ffcd-4045-8655-649364b4c691)

### network bytes sent
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/830084/1234e96a-ee50-4d05-9e14-943e103404fc)

### network bytes received
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/830084/1b9d458f-36c0-4197-bc82-03a335220b10)

**Comment by hdjustice** [comment]
Load testing complete for this endpoint - see the [Load testing report](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/engineering/Load%20Testing/10-10EZ%20Load%20Testing%20report.md) for details
