### ISSUE TITLE
BE | EVSS > LH Disability Rating | Update documentation for BE docs

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#64268]
## Background

Now that we've launched disability rating through LH we need to update our documentation to reflect the new infrastructure versus the old

## Acceptance Criteria 
- [ ] we've updated BE documentation for the completed launch

**Comment by tpharrison** [comment]
[Nametag Document](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/nametag/backend_documentation.md) was updated.  It includes a link to disability ratings document.
