### ISSUE TITLE
[BE] 10-10EZ Performance: SUBMISSION API Load Testing

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#64261]
As a Veteran, I would like to be able to submit my 10-10 EZ during peak submission times so that I can get the PACT Act-related benefits that I have earned.

- [x] Use Locust 
- [x] Utilize existing examples of testing form
- [x] Test Submission API at 100x the normal rate (100x/minute)
- [x] **AS Note: I believe this is used for both save in progress and submitting at the end** 
- [x] Record results
- [x] Check with Josh F and make sure everything submitted smoothly
- [x] **Success: We know that the Submission API can handle 100x requests per minute and that they get to the ES okay. We have documentation, ideally visual-based, to show this.**

---------------------------
## Background
Our Health Tools Crew Chief, Lauren Alexanderson, informed us that the CIO and OIT leadership would like us to demonstrate readiness for up to a 10x spike in submissions between 9/20-9/30. We'll be looking to do some load testing within the next week (Sprint 107 8/23-9/5) on this and other downstream dependencies.
See the [meeting notes](https://github.com/department-of-veterans-affairs/va.gov-team/issues/64123#issuecomment-1690404808) in the comments below for more information.

### Resources
- [Platform info on Load Testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/load-tests)
- Example [Address Validation load test](https://github.com/department-of-veterans-affairs/devops/tree/master/loadtest/address_validation#setup)
- Example from Check-in team - [Testing Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/url-shortener/performance_testing.md)
- Example from Check-in team - [Report](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/url-shortener/performance_testing_report.md)
- Example tests reports
     - [Locust test definition](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/url-shortener/supporting_docs/locustfile.py)
     - [Baseline test report](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/url-shortener/supporting_docs/baseline_test.html)
     - [Production load test report](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/url-shortener/supporting_docs/production_load_test.html)
     - [Stress test report](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/url-shortener/supporting_docs/stress_test.html)

The [draft post mortem](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/1227) of the disability benefits incident that sparked the current scrutiny of the 1010EZ resiliency
>- tl;dr, vets-api processes submissions synchronously, downstream service got bogged down, vets-api timed out before downstream service could finish processing, errors back to user.

**Service calls from the FE:**
> The 1010 specific calls from the FE i see are:
> - GET v0/health_care_applications/enrollment_status
> - GET v0/health_care_applications/rating_info
> - POST v0/health_care_applications
> - POST /v0/hca_attachments
> 
> then there are the shared vets-api service calls from the FE:
> - GET v0/feature_toggles
> - GET v0/backend_statuses
> - GET v0/user
> - GET v0/maintenance_windows
> - DELETE / GET / PUT v0/in_progress_forms

Links to our [Testing Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/engineering/Load%20Testing/10-10EZ%20Loan%20Testing%20Plan.md) and [Report](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/engineering/Load%20Testing/10-10EZ%20Load%20Testing%20report.md) documents

**Comment by lihanli** [comment]
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/830084/58eab16e-31dd-4655-a77f-da6918f3c621)
These are the results for form submissions that all include a 5mb file upload: 249 requests at a rate of 0.42 requests per second and 16 failures. There were some failures but since we have a retry system they should all go through in the end.

**Comment by jadon1979** [comment]
This is testing against the prep.ves.gov infrastructure with 200 users at 2 per second spawn rate.
`Type	Name	Request Count	Failure Count	Requests/s	Failures/s																
POST	/v0/hca_attachments	14053	875	39.3519792	2.450222856																
POST	/v0/health_care_applications	14163	59	39.66000722	0.165215027`

**Comment by lihanli** [comment]
@jadon1979 how did you test against prep? did you change the forward proxy in staging?

**Comment by jadon1979** [comment]
@lihanli yes.

**Comment by lihanli** [comment]
looks like it's still set to SQA https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/fwdproxy-vagov-staging.yml

**Comment by lihanli** [comment]
@hdjustice graphs for file upload testing:

### cpu load
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/830084/219deb4f-d12c-46d2-9f06-fc29c157e3d9)

### latency
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/830084/2e7e53e2-8d01-4cda-a821-681e25fd1443)

### bytes sent
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/830084/0519754e-a5c8-4015-9486-d4f0a5ac9328)

### bytes received
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/830084/fc8c0bbe-cd09-4e8e-95c1-75f26a01176e)

**Comment by lihanli** [comment]
graphs for [this load test](https://dsva.slack.com/archives/CMJ2V70UV/p1694104247245869?thread_ts=1694013210.585079&cid=CMJ2V70UV)

### cpu load
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/830084/fd02bbca-ad65-4bdc-b84c-0a6563ef6ea0)

### latency
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/830084/e9444997-5899-43c4-9efa-389809b13ad7)

### bytes sent
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/830084/317a2df9-f395-41ec-9b2c-c3f80b98eb29)

### bytes received
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/830084/51251d42-c26b-47ab-9ffa-dfccbb77410d)

**Comment by hdjustice** [comment]
Load testing has been completed for Submissions and File Upload - See [Load testing report](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/engineering/Load%20Testing/10-10EZ%20Load%20Testing%20report.md) for details
