### ISSUE TITLE
Copyedit for 2023 audit: Pre-discharge claim

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#64277]
## Issue Description
For the annual audit of all the pages in the disability hub, OCTO content lead assessed these 8 content issues on the [Pre-discharge claim](https://www.va.gov/disability/how-to-file-claim/when-to-file/pre-discharge-claim/) page and made changes that need copyediting before we republish the page:

- The intro paragraph has no more than 2 to 4 sentences and is within 200 to 400 characters with spaces
- Header levels are hierarchical
- The page has no broken links
- Text links have purpose and target
- The content is free of ability-focused language (view, walk, see, hear)
- Relevant terms from page are in content brief and any relevant backlog work is noted
- Remove "What kind of disability benefits can I get?" section (if needed)
- Shorten blue box by moving content outside/under the blue box. This may involve some rewriting and restructuring.

---
### Copyedit the changes made 
(review revisions only, not the full page) to [Pre-discharge claim](https://www.va.gov/disability/how-to-file-claim/when-to-file/pre-discharge-claim/) page
- [x] The page has no broken links
- [x] The intro paragraph has no more than 2 to 4 sentences and is within 200 to 400 characters with spaces
- [x] Header levels are hierarchical
- [x] Text links have purpose and target
- [x] The content is free of ability-focused language (view, walk, see, hear)
- [x] Relevant terms from page are in[ content brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/content-briefs/disability-compensation.md) and any relevant backlog work is noted
- [x] Remove "What kind of disability benefits can I get?" section (if needed)
- [x] Shorten blue box by moving content outside/under the blue box. This may involve some rewriting and restructuring.

### Check accuracy with SME & publish
- [x] Request review from Paul Shute, SME
- [x] Incorporate his changes in Drupal
- [x] Add notes from him to the record of audit for this page
- [x] Publish page
- [x] Record the Flesch-Kincaid before and after grade level

## Additional questions for the SME
- [x] Who connects the service member to IDES when they're wounded, injured, or fall ill while serving and can’t perform their duties? Right now we have passive voice in the text ("you’ll be referred to the Integrated Disability Evaluation System (IDES)"), and we'd like to update it to active.

## Acceptance Criteria
- [ ] Updates are live on the site.

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by megzehn** [comment]
Confirming I published our initial copy edits. And that I sent this over to Paul's team for an accuracy check.

**Comment by megzehn** [comment]
Moving to blocked while we wait for SME revisions

**Comment by megzehn** [comment]
Update: we incorporated SME edits and got them approved. 

@chelsealevinson when you have a minute, could you review and publish? Thank you!!
