### ISSUE TITLE
Discovery for access to SNOW

### ISSUE THREAD

**Issue by Kimberley2023-CSM** [department-of-veterans-affairs/va.gov-team#64280]
There are issues that come into the Service Now CRM (SNOW) that our team is not aware of due to the lack of access to this system.

@Kimberley2023-CSM will take the lead of this effort since Chante will be OOO staring in 4 weeks.  I will be working with Steve Albers, Chante Lantos-Swett, and Mike Chelen to get this access and to determine who should be the owner of our team queue.

**Comment by Kimberley2023-CSM** [comment]
@Kimberley2023-CSM has provided the names of team members to Steve Albers that will need access to this system on 8/24/23.

**Comment by Kimberley2023-CSM** [comment]
No updates on this access as of yet.  Will discuss with @clantosswett and @ATMiddleton on our Leadership sync on 9/8/23.

**Comment by ATMiddleton** [comment]
No updates on this access as of yet. Will discuss with @clantosswett and @ATMiddleton on our Leadership sync on 9/15/23.

**Comment by ATMiddleton** [comment]
@Kimberley2023-CSM will connect with Steve Albers - Contact Center/Veteran Support group must be created in SNOW - CIO Group in SNOW includes Chante - however, we need to create a Veteran Support Group. Chante/Kimberely will reach out to Mike.  Kimberley has Chante's approval.

**Comment by Kimberley2023-CSM** [comment]
Awaiting response from Mike Chelem.  Sent Slack message on 9/25/23.

**Comment by ATMiddleton** [comment]
Still awaiting access.

**Comment by Kimberley2023-CSM** [comment]
Kimberley now has access to the “VA DOT GOV DEVOPS” group in SNOW.  Denise is awaiting access as well.  

Next steps is training in SNOW with Denise.

Our team also needs to create our own queue for cases that our team can manage. Denise is aware of this and will assist with this.
