### ISSUE TITLE
Research methods for automating unit test allow list testing

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#64288]
# Description
Given the parameters of the system being created, our typical automated testing strategy may not be applicable. Let's research an appropriate method for automating testing of this component.

We could consider something like dropping a unit test spec into the github actions folder like we did for the changed apps script -- `vets-website/script/github-actions/get-changed-apps.unit.spec.js`

# Acceptance Criteria
- [x] A recommendation for automated testing approach is presented in this ticket's comments or a confluence document

**Comment by IGallupSoCo** [comment]
My proposal is to write a self test job suite into the unit test allow list workflow.  We would need the following:

- A static, cloned vets-website repo
- Customized versions of the unit test jobs that would point to a static unit test allow list, a small, static set of unit tests, and a static set of test cases.
- A job that would compare the outputs of the unit stress test job to a list of expected results

The tests would simply run with every run of the unit test stress test workflow itself, ensuring consistency without the need to do any additional scheduling or manual testing.

**Comment by IGallupSoCo** [comment]
There is already a workflow in our CI for unit testing.  What appears to be needed is to write tests within the allow-list folder.

**Comment by IGallupSoCo** [comment]
Linked is the proposed test set, to be performed with Jest Test as part of our existing CI workflow.

https://dsvavsp.testrail.io/index.php?/suites/view/2740&group_by=cases:section_id&group_order=asc&display_deleted_cases=0
