### ISSUE TITLE
Analytics KPI dashboard update request for [VA Notify]

### ISSUE THREAD

**Issue by christy-tongty** [department-of-veterans-affairs/va.gov-team#64285]
# Request an update to your KPI Dashboard  

## What this form is for

Use this ticket template to request an update to your existing KPI dashboard. To request a new product be added to our dashboards, please use [Request a New Standardized KPI Dashboard template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&template=analytics-request-kpi-dashboard.md&title=Analytics+KPI+dashboard+request+for+%5BTeam%5D).

### Expected delivery timelines

Once you’ve submitted this ticket template, your KPI dashboard update request will be pulled into the Analytics team’s workflow the following Wednesday during Platform Sprint Planning or Refinement. We expect to deliver your completed dashboard within the next sprint. 

## Instructions for the VFS team
First, tell us what type of change you need to make:

- [ ] Change basic product info
- [ ] **Forms**: funnel changes
- [ ] **Content**: Add or remove pages included
- [x] Other: __To create a new landing page campaign on VA.gov Notify KPIs: https://va-gov.domo.com/page/2040841289 in order to track the clickthrough from Form 22-0994 email notification template to Form 22-1990 application page__

Next, use the original [KPI request template](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit#gid=981224988) or [(downloaded Excel version)](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/1586823275/KPI%20Dashboard%20Product%20Details%20Template%20-%20MAKE%20A%20COPY.xlsx?inst-v=ced1f4dd-e997-4aa2-9ae8-2cebe369b42f) you filled out to update your information. If you are not able to find that spreadsheet, reach out to the Analytics team on #vfs-platform-support for a new spreadsheet that reflects what we currently have on file.

- [x] Make a copy of the [Google Sheet](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit#gid=981224988) [(or download Excel version)](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/1586823275/KPI%20Dashboard%20Product%20Details%20Template%20-%20MAKE%20A%20COPY.xlsx?inst-v=ced1f4dd-e997-4aa2-9ae8-2cebe369b42f)
- [x] Complete worksheet as instructed
- [x] Link your completed spreadsheet here: ______https://docs.google.com/spreadsheets/d/1UddxdmoRA-TNvk2DmFCwU_Puz_HRyHYGGm3WEpyePbc/edit?usp=sharing
- [x] Check your sharing settings to make sure the Analytics team will be able to access it
- [x] Add your team label to follow progress

**Additional Info**

- Please use the [KPI Framework](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/Analytics%20Playbook/va-gov-platform-analytics-kpi-framework.pdf) for more information on the metrics used in the KPI dashboards. 
- If you need any analytics support, read through the [How to request Analytics support](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guidelines.1586823275.html#Analyticscustomersupportguidelines-4.RequestaKPIDashboardinDomo).
- If you do not have Domo access, please [request access here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+access-request&template=analytics-request-google-analytics-domo-access.md&title=Request+access+to+Google+Analytics+and%2For+Domo).

**Comment by christy-tongty** [comment]
Adding @GitSamJennings for visibility.

**Comment by michelle-dooley** [comment]
@christy-tongty - we will review and get back to you with timinig.

**Comment by christy-tongty** [comment]
Hi @michelle-dooley, just wanted to follow up to see if team has an ETA for this request? Thank you.

**Comment by michelle-dooley** [comment]
HI @christy-tongty - we are working on it now and should have it completed very soon.

**Comment by michelle-dooley** [comment]
@christy-tongty the education benefits application 1990 landing page has been added to your dashboard. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdXFRIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bb9b1d04e3fbbf92b2f3ebee839ab8f2da7927e2/image.png)

**Comment by christy-tongty** [comment]
@michelle-dooley It looks like the landing page campaign name (22-1990-landing-from-22-0994) isn't showing up on the DOMO dropdown list. Mind checking for us please? Thank you!
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/109134728/de1aa947-bbdb-415f-9420-71a79fd052c8)

The campaign is showing tracking in [GA](https://analytics.google.com/analytics/web/#/report/content-event-pages/a50123418w177519031p176188361/_u.date00=20230911&_u.date01=20230911&_r.drilldown=analytics.pagePath:www.va.gov~2Feducation~2Fapply-for-education-benefits~2Fapplication~2F1990~2Fintroduction~2F&explorer-segmentExplorer.segmentId=analytics.campaign&explorer-table.plotKeys=%5B%5D&explorer-table.rowCount=10/), we would also like it to show up on DOMO dropdown list for our business line to easy access.

**Comment by michelle-dooley** [comment]
@christy-tongty - sorry about that had to update that filter, it is there now.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb21sIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--36b476fa80cd8aef6d7f498f0ba682b691f2109a/image.png)

**Comment by christy-tongty** [comment]
Thanks for adding! Looking good. @bevnobev @GitSamJennings
