### ISSUE TITLE
Staging Review - IA Feedback - Design system converted components: Memorable date, Select and Breadcrumbs

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#64283]
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- I'm a fan of all of these upgrades. Thanks for this work to standardize with USWDS!

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- **Should**: Update the [Sketch file for breadcrumbs](https://www.sketch.com/s/a52734dd-00d0-44f1-9c9e-ff4016130e5c/p/F30D6063-F45E-4AAE-A2F5-A26C3E5EA5A5/canvas) to reflect the new styles. Also take a look at the bottom example for mobile. Assuming these examples are for the same hypothetical page, would the return breadcrumb on mobile be `<- Level Three`?
- **Consider**: Creating written guidance for breadcrumb display on mobile - the only thing I'm seeing right now is the design pattern in the Sketch file.

**Comment by humancompanion-usds** [comment]
@erinrwhite - Sorry, I don't follow the ask on guidance for breadcrumb at mobile. Are you asking that we describe how the component responds at mobile viewport widths? We generally don't write written documentation on how the component behaves at different breakpoints. We could, but to-date we've relied on Storybook to show what happens in the canvas view for a component at different breakpoints. Including the Storybook examples in iframes in the guidance site means the user would have to resize the browser to be able to see it there (it's easier to go to Storybook and use the breakpoint dropdown in the canvas view). Is the ask for a narrative something the governance team needs or VFS teams need? Is this something we need systemically or just for this component? I agree the behavior at mobile can be a bit surprising.

You are absolutely correct, and it's a great catch, that at mobile the previous level is what should be depicted in Sketch/Figma. That is in fact how the USWDS component behaves:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc0NkIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--48669bfe160f111286c909112e804e0d9f196cb3/Screenshot%202023-09-14%20at%209.10.00%20AM.png)

**Comment by erinrwhite** [comment]
@humancompanion-usds thank you for the clarifying questions! I don't think this needs in-depth narrative, and doesn't require a systematic change to how we document components. "Written guidance" could be a brief note in the [Breadcrumbs page's "Usage" section](https://design.va.gov/components/breadcrumbs#usage). I see some small-screen-specific guidance in the Usage sections for [Back to top](https://design.va.gov/components/back-to-top) and [Button pair](https://design.va.gov/components/button/button-pair), so adding a note could be helpful for Breadcrumbs as well. Like you said, the behavior is a bit surprising. If this is doesn't align with how we should be using the Usage notes, feel free to ignore this recommendation. Updating the Sketch files will also communicate this clearly.

I just took another look at the [USWDS guidance](https://designsystem.digital.gov/components/breadcrumb/#breadcrumb-guidance:~:text=Usability%20guidance,-Consider%20alternatives%20to) and found some language that covers it as well in "Consider alternatives to wrapping" bullet:

> For example, a mobile-friendly breadcrumb may show only a page’s direct parent.

**Comment by humancompanion-usds** [comment]
Fixed in Sketch: https://www.sketch.com/s/bd089bc0-e3e3-4681-bf72-e6be22b433e4/p/F30D6063-F45E-4AAE-A2F5-A26C3E5EA5A5/canvas#Version
