### ISSUE TITLE
SOCKS access for [Fletcher Bonds]

### ISSUE THREAD

**Issue by fbonds** [department-of-veterans-affairs/va.gov-team#64292]
### Your Name

Fletcher Bonds

### Your Email

joseph.bonds@va.gov

### Your Role and Team

Health Enrollment, Software Engineer, Agile Six (Ad Hoc)

### Product Manager (PM) name and email

Heather Justice (heather.justice1@va.gov)

### Product Owner (PO) name and email

Patrick Batemen (Patrick.Bateman@va.gov)

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC9n9YqAxbFzo/wnVuz84pFI0uIWVdKTKFwIc7kHiAMYT+oANlIBil4LPpl7yj/DoAceo17GsPwK5oNd9dF0E4AfwoiD117pj917OTktnlb8xT8mNt+sWA6fPnps/qgdahHtrNGVf1MCVF/FrGYjXRL4ZfWt8xSPEAQpJIg3h4OYJuAYjZpBfyBPCsVanrW8x/s/Fgh8W5o9Yl4ijOfvLV78V/2gY5wsPOnKZIMI16QjVAi3A4+NO35gIkNbgwx/DunqM6hx4eCfkH7dxt+enR15mxfPG/FQsmxZgLMaIR5Hyc6/v5QvQvJY1YhXP/QyHYvW3m5g9TMJM6xcAlakqQZJ0qHUGgWJefpJYM0M3NwcauXRwOxmW155/rgMEWgM7XduV4Z9CcBDL5nYB0G7IeNIxaeTxjv0DBF9Bm1kTzn5IRlDTy/Ru2MAAD4poy2DtiqOeHB5MuidKOTPi3ZPwttoe0h1PyFeDFt72cKL1tPzw7peO+P57IEVPWOjYJuQS0= fletcherbonds@fletcherbonds-VPQ32RX60F

### E-QIP Transmittal Confirmation

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/9326800/695708e8-82f0-4c21-a937-4b0d6bd36d7a)

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by ben-allen-oddball** [comment]
Is this request to replace your existing certificate or add an additional?

**Comment by ben-allen-oddball** [comment]
I see an ssh key has already been added.  Related ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/63038

**Comment by ben-allen-oddball** [comment]
Closing as duplicate ticket opened.
