### ISSUE TITLE
Investigate adding support for using `vets-api` in automated `vets-website` tests

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#643]
# Problem
- `vets-website` currently mocks `vets-api` end points for it's automated tests

# Goal
- add support for running integration tests with `vets-api`

# Artifact 
- Example for running tests against `vets-api` in jenkins 

# Notes
- Integration tests with `vets-api` should mostly cover happy path tests to avoid brittle tests / maintenance overhead

**Comment by U-DON** [comment]
There are two distinct steps involved with integrating the TestCafe tests in Jenkins:

1. We should create a configurable job to create a review instance (with Betamocks enabled for vets-api) and run the TestCafe E2E tests. The job might not necessarily produce a persistent "review instance"; the website and API only need to run as long as necessary for the tests to complete and can shut down afterwards.

2. Once we're confident that it can be included in our production deploy process, we can start to invoke the configurable E2E test job as part of the prerelease job for release.

Prior to the Jenkins setup, there are a couple things to consider cleaning up:
* Settle on the npm command nomenclature for running the tests.
* Configure the test runner.
* Provide the command an option to print the results to a presentable format for Jenkins.
