### ISSUE TITLE
Adding [Marian Adly] to DSVA Slack

### ISSUE THREAD

**Issue by cbrizen** [department-of-veterans-affairs/va.gov-team#64310]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

<Marian Adly has a Slack account that needs to be transitioned to a different email address>

Are you requesting to add an individual as a:

- Full member

- What channel(s) do they need to be added to?
- long-covid-leadership
- long-covid-public
- long-covid-team

Marian Adly is the primary stakeholder and product owner for the Long COVID initiative.

## Sample Descriptions 
- Please add [_marian.adly@va.gov_] as a full member.
- Please change the status of [_slack username_] from [_current status_] to [_desired status_]

**Comment by LEHigley** [comment]
marian has been a member of this slack workspace for 2+ years
