### ISSUE TITLE
Qualitative Data Request - Family/caregiver content pages

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#64322]
### Data Type Requested

User Surveys

### Date Range Start

08-17-2022

### Date Range End

08-16-2023

### Product Name(s)

Benefit hubs

### Product Description

We are currently looking into moving all family member/caregiver content out of the individual Veteran benefits hubs and placing them under the existing family member benefits page to build a more robust family/caregiver experience.  We are looking for insights where family members or caregivers are struggling to find information on benefits for themselves, as well as tasks that they need to do. 

### Survey URL(s), key term(s), case category or type

Intercept survey - rating of 1 or 2 only
Feedback survey  - Answered "No" to "Were you able to do your task today?" only

Must include at least one key term in open ended question - family, caregiver, dependent, spouse, or survivor
URLs:
- https://www.va.gov/family-member-benefits
- https://www.va.gov/health-care/family-caregiver-benefits
- https://www.va.gov/disability/dependency-indemnity-compensation
- https://www.va.gov/education/survivor-dependent-benefits
- https://www.va.gov/pension/survivors-pension
- https://www.va.gov/health-care/get-reimbursed-for-travel-pay/
- https://www.va.gov/resources/the-pact-act-and-your-va-benefits/

### File Delivery Format

All in one file, on one tab

### VA Email Address(es)

michelle.northuis@va.gov

### Add Assignee and Labels

If not already done so, please ensure @ianMcCullough-ob is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by newworld2616** [comment]
Hi, I have sent the data request, please verify if you received it. Thank you!

**Comment by mnorthuis** [comment]
Received data, however I input the dates incorrectly - the start date should be 8/17/2022, I'm requesting 1 year worth of data. 

Also wanted to confirm that the data is filtered by the overall rating I specified and the key words provided.

**Comment by newworld2616** [comment]
Sorry about missing it, I will look into this and get back to you.

**Comment by newworld2616** [comment]
Hi, I have shared the data, please verify when you received it. Let me know if you have any questions. Thank you!

**Comment by mnorthuis** [comment]
Can you explain the format of the file?  Is the feedback data and intercept data in the same sheet but different columns?  Does this mean that the same visitor/person took both?  Or are they independent and I can split the file?

**Comment by newworld2616** [comment]
Both data are on the same sheet, as you requested, however, I marked one of
the box yellow just to make it easier to determine which one is which. I
labeled with the survey names. Let me know if it helps.
