### ISSUE TITLE
Analytics KPI dashboard update request for Governance Team

### ISSUE THREAD

**Issue by it-harrison** [department-of-veterans-affairs/va.gov-team#64328]
# Request an update to your KPI Dashboard  

## What this form is for

Use this ticket template to request an update to your existing KPI dashboard. To request a new product be added to our dashboards, please use [Request a New Standardized KPI Dashboard template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&template=analytics-request-kpi-dashboard.md&title=Analytics+KPI+dashboard+request+for+%5BTeam%5D).

### Expected delivery timelines

Once you’ve submitted this ticket template, your KPI dashboard update request will be pulled into the Analytics team’s workflow the following Wednesday during Platform Sprint Planning or Refinement. We expect to deliver your completed dashboard within the next sprint. 

## Instructions for the VFS team
First, tell us what type of change you need to make:

- [ ] Change basic product info
- [ ] **Forms**: funnel changes
- [ ] **Content**: Add or remove pages included
- [x] Other_____________________________

Governance Team makes use of the data set "BQ - Governance Github tickets". We would like to request two changes:
* we need the "milestone" added to the BQ data set - Governance Team has added milestones to all historical Collab Cycle tickets and is adding them to new tickets
* we would like the "BQ - Governance Github tickets" data set to be renamed to "BQ - Staging Review issue tickets"

Next, use the original [KPI request template](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit#gid=981224988) or [(downloaded Excel version)](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/1586823275/KPI%20Dashboard%20Product%20Details%20Template%20-%20MAKE%20A%20COPY.xlsx?inst-v=ced1f4dd-e997-4aa2-9ae8-2cebe369b42f) you filled out to update your information. If you are not able to find that spreadsheet, reach out to the Analytics team on #vfs-platform-support for a new spreadsheet that reflects what we currently have on file.

- [ ] Make a copy of the [Google Sheet](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit#gid=981224988) [(or download Excel version)](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/1586823275/KPI%20Dashboard%20Product%20Details%20Template%20-%20MAKE%20A%20COPY.xlsx?inst-v=ced1f4dd-e997-4aa2-9ae8-2cebe369b42f)
- [ ] Complete worksheet as instructed
- [ ] Link your completed spreadsheet here: ______
- [ ] Check your sharing settings to make sure the Analytics team will be able to access it
- [ ] Add your team label to follow progress

**Additional Info**

- Please use the [KPI Framework](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/Analytics%20Playbook/va-gov-platform-analytics-kpi-framework.pdf) for more information on the metrics used in the KPI dashboards. 
- If you need any analytics support, read through the [How to request Analytics support](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guidelines.1586823275.html#Analyticscustomersupportguidelines-4.RequestaKPIDashboardinDomo).
- If you do not have Domo access, please [request access here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+access-request&template=analytics-request-google-analytics-domo-access.md&title=Request+access+to+Google+Analytics+and%2For+Domo).

**Comment by shiragoodman** [comment]
@holdenhinkle FYI

**Comment by rmtolmach** [comment]
Thanks for the heads-up @shiragoodman!  

You might already be aware, but in order for issues to show up on the [CoP Zenhub board](https://app.zenhub.com/workspaces/platform-cop-backlog-6359535e384ff5a473132130/board), they need to be tagged with both the `platform-cop-backend/frontend/devops` label _and_ the `platform-cop` label. 

But in regards to the actual ticket... 😄 I don't think updating data sets in Domo is something we do on Backend 🤔 (I don't think I have a Domo account). I could definitely be wrong, so let me bring it to our CoP meeting on Wednesday. In the meantime, do you know, @michelle-dooley? Is adding things to the BG data set something your team does or has Backend done this in the past?

**Comment by michelle-dooley** [comment]
@rmtolmach and @shiragoodman we need support in order to get Milestone added to the GH data that is pulled in for this, we do not currently own that configuration.  We are working on identifying who that is and if they can work with Phil to take this ownership over going forward.  I will let you know as I learn more on timing for that.

**Comment by it-harrison** [comment]
@michelle-dooley closing this ticket because Governance team will attempt to complete this work itself.
