### ISSUE TITLE
Contact Center Review for Veteran Facing Forms - Form 21-0845

### ISSUE THREAD

**Issue by PSIEBENLIST** [department-of-veterans-affairs/va.gov-team#64380]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 
## Description
Digitizing Form 21-0845 - Authorization to Disclose Personal Information to a Third Party

### Launch Date
Tentatively week of September 11th, 2023

### Version Number
Version 1

### Product Guide
[*Please provide product guide link*](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/21-0845/Contact%20Center%20Guide-%2021-0845.pages)

### Product Video
*Please provide product video link*

### Product Video Transcript
*Please provide product video transcript link*

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
Thanks @PSIEBENLIST! I'll let you know if I have any questions before submitting this for VEO review.

**Comment by starlow00** [comment]
The guide looks good; sending it to VEO for review.

**Comment by PSIEBENLIST** [comment]
Thanks!

**Comment by starlow00** [comment]
No changes from VEO. Copy attached. 
[VA Form 21-0845 auth info disclosure 3rd party SRT 08312023.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/12542758/VA.Form.21-0845.auth.info.disclosure.3rd.party.SRT.08312023.docx)
