### ISSUE TITLE
Add user attributes to SiS callback logs

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#64386]
We need the ICN and user UUID (CSP ID) added to the SiS callback logs. Example of logs [here](https://vagov.ddog-gov.com/logs?query=signinservice%20signincontroller%20callback%20&cols=%40remote_ip.geoip.country.name%2C%40payload.user_uuid%2C%40named_tags.remote_ip%2C%40payload.sso_cookie_contents.patientIcn&event=AgAAAYo87feectjZqgAAAAAAAAAYAAAAAEFZbzg3ZjlnQUFBMGtRZjM5aS1OOVFBNAAAACQAAAAAMDE4YTNjZWUtMDM2OS00NjAzLWJiZmYtZmQ2OWVlYzE0ZDI0&index=&messageDisplay=inline&storage=online_archives&stream_sort=time%2Cdesc&viz=stream&from_ts=1689879326000&to_ts=1690484126000&live=true) which show as of 28AUG23 that we do not have either attribute listed in the callback log.

Request from Login.gov adoption team and BDPR team for these values.

**Comment by bramleyjl** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/13659
