### ISSUE TITLE
SOCKS access for Isaac Gallup

### ISSUE THREAD

**Issue by IGallupSoCo** [department-of-veterans-affairs/va.gov-team#64387]
### Your Name

Isaac Gallup

### Your Email

igallup@thesocompany.com

### Your Role and Team

QA Engineer on Platform Tech Team 4

### Product Manager (PM) name and email

Joseph Tice - joe.tice@oddball.io

### Product Owner (PO) name and email

Bill Chapman - William.W.Chapman@omb.eop.gov

### Access Type Requesting

platform

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCrtn5HaM0bw0epO5SC+8j1rXcMG3u5gbON7rTA9dQFLhn4g+vw2Gsqj9qrua0tzthTk1osOm7VqHXRTclau28BpTOgtZqOz6/g6lC24r4YZYCxA9u2qMhhi3+5GBDmLhdMMbWwzO7W/1UcfljF4XWqvsoLjY+Ht42I6QBx0AN6a0xm2wXPnJyNmQhP2CjWd01HFc0lfeTLQvSHdxab+y8UTZrdg/UsNv3HYMApSUfQnCMI6pzcxbGHyL0UYgDLeCPVVvEzcZdEyRXYuW4A+gavVji0u+XGbI6mBLAZw5xrDpAF5yO+DZNxd4VdtjoT/nd9Qb2dijarIMSutJaY/rtGDiR8q6qETHLK+NLiaYUcJx/8AwFG58qiWj4vF11mWo4ewZdTiyKeu/6cZfNcvGdd0Q7oEDPp27twzs5/piVVl1IWaL+hTh8OjglB5HN0OEhx0OqU82lGubgfw9kJwX/hKOetMiUKniv7TfH2zlx03JWCGlKQhD9FgByqgvglUt0= isaacgallup@Isaacs-MBP.attlocal.net

### E-QIP Transmittal Confirmation

<img width="1176" alt="Screenshot 2023-08-28 at 11 30 06 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/142249919/a975c1b3-e150-48a8-a46c-19fdf6d49086">
<img width="1145" alt="Screenshot 2023-08-28 at 11 30 00 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/142249919/9d3fdcc7-3a3b-4a60-bef0-7a3642ad72ea">

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by ben-allen-oddball** [comment]
Closed two weeks ago.  Cleanup this ticket.

**Comment by IGallupSoCo** [comment]
![Image](https://github.com/user-attachments/assets/06286bed-d87b-4fa8-abbb-23071810cb60)
