### ISSUE TITLE
Remove past rates from current "protected disability rates" page

### ISSUE THREAD

**Issue by strelichl** [department-of-veterans-affairs/va.gov-team#64398]
## Issue Description

The [protected disability rates for 2021](https://www.va.gov/pension/protected-pension-rates/past-rates-2021/) has the older past rates at the bottom of the page. Our practice has been to keep past rates only on the current rates pages and remove them when creating a new past rates page. So we need to update the past rates page by removing those past rates.

---
## Tasks
- [x] Remove past rates from [protected disability rates for 2021](https://www.va.gov/pension/protected-pension-rates/past-rates-2021/) page
 - [x] Publish (Megan)

## Acceptance Criteria
- [x] Updated past rates page is live
---

**Comment by megzehn** [comment]
removed and validated. closing!
