### ISSUE TITLE
Vets-api terminal access for Matthew Christianson

### ISSUE THREAD

**Issue by mchristiansonVA** [department-of-veterans-affairs/va.gov-team#64397]
### Your Name

Matthew Christianson

### Your GitHub handle (terminal access is managed through GitHub)

mchristiansonVA

### Your dsvagovcloud AWS user name (if applicable)

matthew.christianson

### Team, Role, and Company of the target individual

Team Dash, Software Engineer, Ad Hoc

### Product Manager (PM) name and email

Kayla Watanabe

### Product Owner (PO) name and email

Janet Coutinho

### COR Name (leave "None" if you listed an AWS user name above)

None

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

None

### Please confirm if you are on the VFS Team Roster or Platform Team Roster

- [X] [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Please confirm E-QIP Transmittal/Adjudication. This could be a screenshot of your Transmittal/Adjudication email, a link to another request where you've submitted this proof (i.e. AWS/SOCKS), etc.

- [X] I have attached proof that I have either transmitted my E-QIP survey or previously received a favorable decision (by including in "Additional Notes" section below)

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### Additional Notes

<img width="1493" alt="Screenshot 2023-08-28 at 1 22 01 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/95487885/644ce4a8-e356-42ea-8627-73be05d796bc">

### Additional resources for Support Engineer

- [ ] For users on a VFS team but not in the VFS Team Roster, they must start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] Instructions for handling requests [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access) - Support Only

**Comment by lindsay-insco** [comment]
Found in VFS Roster 

eQIP Transmittal notice included here

For access to `prod` the team is asking that the requester provide a specific task that cannot be done in a lower environment or through a different process. The purpose is to track and cases that require production access via tooling and process improvements. Can you please provide some more insight about why you need production access please?

**Comment by BillChapmanUSDS** [comment]
Access Approved as per current policy.

**Comment by lindsay-insco** [comment]
@mchristiansonVA You've been given access to Production limited to 6 months, expiring 03/14/24. Please set a reminder for yourself to return to this Issue and re-request access within 1 week of the expiration date. You'll receive 1 reminder with a 72 hour window to respond. Failure to do so will result in lost access and will require you to fill out a new request.

**Comment by lindsay-insco** [comment]
Slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1694723943675799)

**Comment by lindsay-insco** [comment]
@mchristiansonVA Your vets-api terminal Production access has expired.

Would you like to request an extension? You have 72 hours to respond, or your
access will be revoked and you will need to fill out a new request

**Comment by lindsay-insco** [comment]
@mchristiansonVA it has been 72 hours with no response. Vets-API access has been removed.

If you need continued access please fill out a new request [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=external-request%2Cplatform-tech-team-support%2Cops-access-request&template=vetsapi-argo-terminal-access.yaml&title=Vets-api+terminal+access+for+%5Bindividual%5D)
