### ISSUE TITLE
Salesforce Reporting - Number of overdue Tier 2 cases (outside of SLA)

### ISSUE THREAD

**Issue by Kimberley2023-CSM** [department-of-veterans-affairs/va.gov-team#64390]
Create a report for leadership to display the Number of overdue Tier 2 cases (outside of SLA).

**Comment by Kimberley2023-CSM** [comment]
@edpearson20 can you take a look at the report below and provide feedback.  I have also sent an email with the report link on the VA side for your review.

Tier 2 - SLA status | Salesforce

**Comment by clantosswett** [comment]
Hi all - is there any update on this ticket and can the link to the report be shared here in Zenhub? @edpearson20 @Kimberley2023-CSM. Thanks!

**Comment by Kimberley2023-CSM** [comment]
@edpearson20 can you put the report link in this ticket so I can review it?  I know on our call earlier this week, you stated you built another report from scratch.

**Comment by ATMiddleton** [comment]
Hey 
@Ervin D. Pearson II
 I just mentioned you the in three ZH tickets I created for the reports that Chante wanted.  Will you add the report links to those tickets so Chante, Anita, and I can review tomorrow during our Leadership sync?
I have included those ZH tickets below.
https://app.zenhub.com/workspaces/contact-center-62cdd9546ec1530018209672/issues/gh/department-of-veterans-affairs/va.gov-team/64390
https://app.zenhub.com/workspaces/contact-center-62cdd9546ec1530018209672/issues/gh/department-of-veterans-affairs/va.gov-team/64392
https://app.zenhub.com/workspaces/contact-center-62cdd9546ec1530018209672/issues/gh/department-of-veterans-affairs/va.gov-team/64393

**Comment by manalo-soco** [comment]
@ATMiddleton @Kimberley2023-CSM 
VACX T2 Overdue SLA Cases (Not T3) | Salesforce
[](https://va.lightning.force.com/lightning/r/sObject/00OOE000000Jnd12AC/view?queryScope=userFolders
)

**Comment by Kimberley2023-CSM** [comment]
Report complete!
