### ISSUE TITLE
Salesforce Reporting - Cases that mention ID.me verification issues

### ISSUE THREAD

**Issue by Kimberley2023-CSM** [department-of-veterans-affairs/va.gov-team#64393]
Create a report for ID.me displaying Cases that mention ID.me verification issues.

**Comment by clantosswett** [comment]
Hi all - is there any update on this and can the link to the SF report be shared here in Zenhub? @edpearson20 @Kimberley2023-CSM. Thanks!

**Comment by Kimberley2023-CSM** [comment]
@edpearson20 can you put the report link in this ticket so I can review it?  I know on our call earlier this week, you stated you built another report from scratch.

**Comment by ATMiddleton** [comment]
@edpearson20 is building the report to include a custom formula to include data over 30 days.

**Comment by manalo-soco** [comment]
@ATMiddleton @Kimberley2023-CSM   fr: @edpearson20

VACX Cases - ID.Me (CTRL+F Keyword) | Salesforce
https://va.lightning.force.com/lightning/r/Report/00OOE000000Jndu2AC/view?queryScope=userFolders

**Comment by Kimberley2023-CSM** [comment]
Report complete!
