### ISSUE TITLE
Salesforce Reporting - Number of Tier 3 cases over 30 days old

### ISSUE THREAD

**Issue by Kimberley2023-CSM** [department-of-veterans-affairs/va.gov-team#64392]
Create a report for leadership displaying Number of Tier 3 cases over 30 days old.

**Comment by clantosswett** [comment]
Hi all - is there any update on this ticket? @edpearson20 @Kimberley2023-CSM. Thanks!

**Comment by Kimberley2023-CSM** [comment]
@edpearson20 can you put the report link in this ticket so I can review it?  I know on our call earlier this week, you stated you built another report from scratch.

**Comment by manalo-soco** [comment]
@ATMiddleton @Kimberley2023-CSM  fr @edpearson20 

VACX T3 Cases Over 30 Days (FILTER DATE) | Salesforce
https://va.lightning.force.com/lightning/r/Report/00OOE000000JndL2AS/view?queryScope=userFolders

Notes from @edpearson20:  

This is a formula value that we would used in the field, but I do not have access to Object Manager (Salesforce Administration) to do so.
TODAY() - Date/Time_Opened__c

List view filter would equal...
Days_Since_Opened__c > 30

**Comment by Kimberley2023-CSM** [comment]
The report was updated while on a call with Ervin yesterday to be able to include the correct fields.  No formula needed as previously noted.
