### ISSUE TITLE
[Research/Design] 10-10EZR: Discovery--EZR Form Flow Desk Research

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#64412]
As a Veteran, I would like to update the information that the VA has for me so that I can make sure all of my information is correct, that I get any VA notifications or information, and so that I don't have to pay co-pays if I don't have to.

- [x] Conduct Desk Research on how Veterans want to be presented with, and update their Health Information
- [ ] Look into desk research to see if there are any other types of information where Veterans are presented with their data on file and have to confirm or change (e.g. Check-In)
- [ ] Share findings with team
- [ ] Discuss findings with Patrick
- [ ] **Success: We determine if any other team/research sessions have encountered this issue and how they handled it.**

**Comment by jessicastump** [comment]
Adding links to the past discovery work, there might be jumping off links in these :) 

- [EZR - initial discovery ](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1684943221068/4b11f2d1902d05f12f53468263a561c2d5a460a9?sender=uadf1ed7fe7c76f0914967329)
- [PG/Financial Disclosure](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1687381992402/ac027de3375351079c9cbc93d1662510ffd3cb1a?sender=uadf1ed7fe7c76f0914967329)

**Comment by jessicastump** [comment]
Here is the other Mural discovery board if useful here - [the UX touchpoints / links to the EZR](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1692890274951/df867bfc9103c8d9bd2e9e334a914cbdcaa11000?sender=uadf1ed7fe7c76f0914967329) - ticket 63746

Some additional desk research links:
- [Research findings for pattern](https://design.va.gov/patterns/help-users-to/know-how-their-information-is-updated#research-findings) know how info is updated
- [Research findings for pattern check personal info](https://design.va.gov/patterns/help-users-to/check-personal-information#research)

**Comment by hdjustice** [comment]
Decision has been made on EZR Form flow. Closing!
