### ISSUE TITLE
Documentation Bot Auto Responder Improvements

### ISSUE THREAD

**Issue by jknipes** [department-of-veterans-affairs/va.gov-team#64414]
Description:

This ticket is designed to route the proper documentation links to the documentation bot topics listed here: https://docs.google.com/spreadsheets/d/1TItdfPMH_TiXEhgMKEqxIW2e5EaMKy4cHaBhaeQ7drU/edit?pli=1#gid=1990856050

The user should see:

- Topic 31 (Automated Tests) [link this document](https://depo-platform-documentation.scrollhelp.site/developer-docs/debugging-unit-tests) 
- Topic 1 (PR Reviews) Link to these documents: [Pull request best practices](https://depo-platform-documentation.scrollhelp.site/developer-docs/pull-request-best-practices) , [Submitting pull requests for approval](https://depo-platform-documentation.scrollhelp.site/developer-docs/submitting-pull-requests-for-approval), [Support overview ](https://depo-platform-documentation.scrollhelp.site/support/support-overview#Supportoverview-Supportrequestpolicies)

**Definition of Done**:
Tasks are completed below.

**List of Tasks to Complete**:
- [x] Engineer adds the document to Support Bot Google Sheet
- [x] Engineer configures Bot to reference that sheet
- [x] Test to see User case is functional

**Comment by JoeTice** [comment]
Planning to prioritize this ticket for Sprint 35

**Comment by CBonade** [comment]
Made these updates to the sheet. When trying to test to see if the correct links show up, my request was handled by a backup support bot that doesn't have all the features. Will have to delay testing until the regular bot is back at it.

**Comment by CBonade** [comment]
https://dsva.slack.com/archives/CBU0KDSB1/p1695157168398579

https://dsva.slack.com/archives/CBU0KDSB1/p1695149012411599

Couple of slack threads showing the new links in action. Added keywords to my best guess of what would make them useful.

**Comment by jknipes** [comment]
Topic 1 recommended document [Support Overview](https://depo-platform-documentation.scrollhelp.site/support/support-overview#Supportoverview-Supportrequestpolicies) contains this callout, which is an important component of the intended result: 
![Screenshot 2023-09-26 at 12 59 24 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/131686965/24406ca1-0deb-4c5b-9872-219a8abf9a3b)
