### ISSUE TITLE
[SW] Staging Review - User flows and navigating, housing expenses (63676) (Post Launch)

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#64421]
During the Staging Review on 8/15/23 this post launch feedback was provided #63676

### Platform Issue
Your content does not support a necessary user flow or user scenario. 

### Issue Details
Missing step in user flow: the monthly housing expenses section does not have a summary view to allow users to review, update, and delete housing expenses, similar to the summary views for other types of expenses.

### VA.gov Experience Standard
[Category Number 03, Issue Number 10](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

### Platform Recommendation
Create a summary view for monthly housing expenses following the /household-expenses-values view to match the summary views for other types of expenses.

**Comment by josephrlee** [comment]
This is probably a question for @denisecoveyduc on why we didn't do this in the first place. I think I remember she had a reason for it. It wouldn't be a huge lift on the design side, but I'm not quite sure how much work it would be on the FE side. @Dr-Pongo would have to answer that. 

I think it'd be about a 3 from a design effort. 

cc: @Tom-Davis @HeatherRienks

**Comment by Dr-Pongo** [comment]
I'll have to look back through messages, but I think the final decision for this was ultimately based on what actually qualifies for this section. We have an other expenses page which allows for additional user input with the cards etc.

**Comment by HeatherRienks** [comment]
Need further discovery to weigh downstream impact.

**Comment by josephrlee** [comment]
FWIW, I did a little digging, and we have the [household expenses on the review page](https://github.com/department-of-veterans-affairs/vets-website/blob/9db6ec1418af2dff935772e799740f24f08b41e2/src/applications/financial-status-report/components/householdExpenses/HouseholdExpensesSummaryReview.jsx) already.

**Comment by josephrlee** [comment]
Hey @denisecoveyduc, wanted to follow up on this ticket. I recall we didn't add the housing expenses summary because of how it interacts with the paper form inputs. Can you provide any clarity on how to move forward with this ticket that came out of the last staging review? Thanks!

cc: @HeatherRienks @Tom-Davis

**Comment by HeatherRienks** [comment]
After initial chat, need to set up a separate call to discuss this further  :)

**Comment by HeatherRienks** [comment]
Per Design Sync on 9/25/23, @josephrlee will ask FE how box 18 on FSR is calculated (is it all combined? Rent, renter's insurance, etc.)?

And, should we add mini summary pages?

**Comment by denisecoveyduc** [comment]
9/26/23 update. Based on conversation [slack thread ](https://dsva.slack.com/archives/CPE4AJ6Q0/p1695685718654569?thread_ts=1695411215.570419&cid=CPE4AJ6Q0)it sounds like we may pull out the rent/mortgage payment question into a numerical input to avoid another mini summary. @josephrlee and @mgleo can provide more context.

**Comment by HeatherRienks** [comment]
Per 10/5 Design sync, @mgleo will mock up proposed changes and team will discuss.

**Comment by mgleo** [comment]
_Example for reference_

**Monthly Mortgage payment: $2,000
Breakdown:**

- Principal: $900
- Interest: $400
- Property tax: $200
   - CDD fee: $100
- Mortgage insurance (PMI): $240
- Homeowners insurance: $160

**Collected separately, not included in mortgage payment:**

- HOA fee: $400

**Comment by mgleo** [comment]
Slack conversation: https://dsva.slack.com/archives/CPE4AJ6Q0/p1696948544566919
Waiting on confirmation from stakeholder

**Comment by denisecoveyduc** [comment]
Hey all,  FYSA @mgleo @josephrlee 
The SMEs have come back with a few comments.  I will drop the same in the ticket for tracking purposes.

- They are ok with the way that the question is framed to Veterans. 
- They'd like the acronyms to be spelt out
- They want to ensure we are trying to avoid things being double counted. (example taxes or PMI)

So other than spelling out the acronyms we are ok to proceed with this.

@HeatherRienks @Tom-Davis I'd consider this one unblocked and ready to go.

**Comment by mgleo** [comment]
Hi @denisecoveyduc, here are the updated mockups. It seems PMI and CDD are usually referred to by their acronyms so I'm including the acronyms in parentheses. If this looks good to you, I can create a dev ticket for this to be implemented.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzFvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c251284070435e43684620511f3ab142ebe6d87e/housing--expenses.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzVvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b095755007aab20cce09ceead38b78b0f3754f14/other--expenses.png)

**Comment by denisecoveyduc** [comment]
Wow, what a mouthful. That sure adds a lot of copy in that section but I think that is great. Dev ticket it is! 👍🏼  
Thanks @mgleo

**Comment by mgleo** [comment]
Dev ticket for this work has been created: #68302
CC @denisecoveyduc @Tom-Davis @HeatherRienks @Dr-Pongo
