### ISSUE TITLE
[SW] Staging Review - User flows and navigating, heading hierarchy (63679) (Post Launch)

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#64423]
During the Staging Review on 8/15/23 this post launch feedback was provided #63679

### Platform Issue
Your page doesn't follow heading hierarchy. Headings aren't properly nested, and headings and/or labels aren't relevant to the page.

### Issue Details
In Step 2, after entering your work history when reviewing the entries as cards, the headings aren't nested properly. "Your work history" is an H3, so each card describing a work history entry should be nested beneath that. Instead, the heading for each card is an H3.

### VA.gov Experience Standard
[Category Number 02, Issue Number 04](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

### Other References
WCAG SC 1.3.1_A
WCAG SC 2.4.6_AA

### Platform Recommendation
Recommend the headings for each card be changed to H4s. This matches with similar occurences elsewhere in the product, so this looks like it was probably just a typo.

**Comment by josephrlee** [comment]
This is super easy. I can handle it, and it was a miss on my end when I worked on this a while back. Just need to [update the h3 in the card](https://github.com/department-of-veterans-affairs/vets-website/blob/6d89970e68a7f238a773521104ecbabd12708d97/src/applications/financial-status-report/components/employment/EmploymentHistorySummaryCard.jsx#L132) to an h4.

cc: @Tom-Davis @HeatherRienks
