### ISSUE TITLE
[SW] Staging Review - Outdated design components and patterns, wizard (63671) (Post Launch)

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#64427]
During the Staging Review on 8/15/23 this post launch feedback was provided #63671

### Platform Issue
Design components and patterns in use are outdated. 

### Issue Details
There is a wizard at the beginning of the form. I know this was talked about and changing the wizard is going to be implemented at a later date. I am adding this ticket for tracking purposes.

### VA.gov Experience Standard
[Category Number 04, Issue Number 08](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

### Other References
WCAG SC 3.2.4 AA

### Platform Recommendation
Go to one thing per page.

**Comment by josephrlee** [comment]
This will be a much larger lift, and I know it has its [own super epic created for it](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/48133). 

I think it'll be the next major chunk of work we tackle after we wrap up the Review page MVP work, according to conversations we've had with @denisecoveyduc. We'll need more time for discovery to estimate this properly. 

cc: @Tom-Davis @HeatherRienks  @mgleo

**Comment by HeatherRienks** [comment]
Per refinement mtg, we need to add all other Wizard Work tickets to Epic #48133. This ticket will remain open until all work is done!

cc: @josephrlee @mgleo @charlottecesana @Tom-Davis

**Comment by HeatherRienks** [comment]
Let's discuss this with @josephrlee and @mgleo

**Comment by HeatherRienks** [comment]
Closing this ticket as we are awaiting CAIA feedback; @josephrlee to create  a new ticket (#xxx)
