### ISSUE TITLE
[SW] Staging Review - Single-click destructive action (63680) (Post Launch)

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#64425]
During the Staging Review on 8/15/23 this post launch feedback was provided #63680

### Platform Issue
No VA.gov Experience Standard for the issue found.

### Issue Details
In each instance of the subtask pattern (eg. Your work history, Other sources of income, Your spouse's work history, Household assets,  and Utility bills are the instances I noticed), when reviewing the cards containing all of the information you've provided, the Delete button removes the card with a single click with no confirmation step, and with no message indicating that the action has occured. It's easy to imagine some scenarios where a user might accidentally trigger the Remove button and not realize that they did it. Screen reader users may hit the wrong key but think they hit [Tab]. A low-vision user on a touch device might pinch-to-zoom and accidentally tap the Remove button in the process, and not see the issue disappear.

Since users get an opportunity to review everything prior to submission, this is probably not a violation of experience standard 03.09 or WCAG 3.3.4. But I do think it's in the spirit of WCAG 3.3.4.

### VA.gov Experience Standard
[Category Number 00, Issue Number 00](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

### Platform Recommendation
Two recommended changes. See #56082 for an example of another team that's tackled this recently.

1. Some kind of status message that receives focus when an issue has been removed, similar to the background-only alerts in use when changing contact information. If a visible status message isn't practical, at least some aria-live update should be announced to screen reader users.
2. Some kind of intermediate confirmation step between a user clicking Delete and the issue actually being removed. A modal would be a good fit here.
```[tasklist]
### UX Tasks
- [x] Creat a list of all modals that need to custom content
- [x] Come up with modal copy and template
- [ ] Add modal design to Sketch and update all mini summary pages to include new pattern
```

**Comment by josephrlee** [comment]
We can use the work that [Supplemental Claims has done](https://sketch.com/s/d2416db4-9a4f-4919-abe4-20ba4bdcfd89/a/EeL8Vwq/play). It should be fairly easy from a design effort, but not sure how much of an engineering lift it will be. But since they've already [merged it in their codebase](https://github.com/department-of-veterans-affairs/vets-website/pull/23953), I'm guessing it won't be super hard.

I think the main lift will be figuring out the right content to put in the modal since each type of mini summary card has slightly different content (vehicles, employment, other income, expenses, etc.) 

From a design effort, I think it will be about 3 or so, @mgleo, do you think that's accurate?  

@Dr-Pongo will have a better estimate on the FE lift. 

cc: @Tom-Davis , @HeatherRienks

**Comment by mgleo** [comment]
Sounds right, biggest issue will be content for the modal.

**Comment by Dr-Pongo** [comment]
Yeah I'd say from an FE perspective, looking at a 5 for the initial implementation for the first summary page we do, and 1/2's for the remaining pages depending on the complexity

**Comment by Dr-Pongo** [comment]
@Tom-Davis @HeatherRienks, should we spin a separate FE ticket to separate the work?

**Comment by HeatherRienks** [comment]
This will be a FE and a Design ticket. Need to add task lists.
5 pts for FE
3pts for Design

**Comment by mgleo** [comment]
Hi @Dr-Pongo 
Thinking of simplifying this a bit. 
Can we pull the title/header of the card and display it on the modal? Here is an example of a user deleting their "Transportation and car expenses" card.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbFpVIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ff0f7ee8ffb23e5060b6732233cef97703d22af0/remove-transportation.png)

**Comment by josephrlee** [comment]
@Dr-Pongo here's a list of all the mini-summary pages we'll need to account for:

- Veteran work history
- Spouse work history
- Veteran other income
- Spouse other income
- Household assets
- Vehicles
- Other assets
- Monthly housing expenses
- Utility bills 
- Credit card bills
- Installment contracts
- Other living expenses

cc: @mgleo @HeatherRienks @Tom-Davis

**Comment by Tom-Davis** [comment]
@mgleo & @josephrlee are we complete on the design portion of this "split ticket and ready to let FE be assigned to it and take you two off?

@Dr-Pongo @HeatherRienks FYI

**Comment by mgleo** [comment]
@Tom-Davis I believe so. Sounds like @Dr-Pongo will do some exploration on whether it is possible to pull in titles and utilize the Supplemental Claim's modal code.

**Comment by HeatherRienks** [comment]
Per @Dr-Pongo @amponce will most likely be taking this ticket on from a FE perspective. Will roll into S108 - estimating about 5pts of work remaining.

**Comment by amponce** [comment]
@HeatherRienks @Tom-Davis: I wanted to provide a status update since I'll be out on Thursday and Friday.

I've set up the first destructive action modal for the Employment History Summary cards and have reviewed the styles and implementation with @josephrlee. I'll resume work on the modal on Monday after we return from our trip.

The draft PR can be found here:

https://github.com/department-of-veterans-affairs/vets-website/pull/25671

![modal-employment-history](https://github.com/department-of-veterans-affairs/va.gov-team/assets/3916436/51cf3255-b539-49a7-a03c-a79ecba5a16a)

**Comment by josephrlee** [comment]
Am asking @denisecoveyduc for feedback on different modal copy choices in [this slack thread](https://dsva.slack.com/archives/CPE4AJ6Q0/p1694819951842749).

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/1631062/1c8ebd7f-3dee-4d8c-ac3f-adc3b1ac87ec)

**Comment by josephrlee** [comment]
@amponce, here's the final version of the modal copy to use with my annotations! Let me know if you have any questions!

![Delete modal copy Final](https://github.com/department-of-veterans-affairs/va.gov-team/assets/1631062/e7cc7f9b-8d29-4243-b198-819f4897d392)

**Comment by josephrlee** [comment]
Thanks for the update @amponce!

**Comment by amponce** [comment]
Reviewed the modals with @josephrlee 

🚀 Modals Implemented:

✅ EmploymentHistorySummaryCard.jsx
✅ CreditCardBillSummary.jsx
✅ InstallmentContractSummary.jsx
✅ VehicleSummaryWidget.jsx
✅ UtilityBillSummary.jsx
✅  OtherIncomeSummary.jsx
✅  SpouseOtherIncomeSummary.jsx
✅  OtherAssetsSummary.jsx
✅  OtherExpensesSummary.jsx

🛠 In Progress:

A small issue remains with a memory leak on 4 of the summary pages, I have a fix but more testing is needed to ensure SW states are still working as expected.

**Comment by amponce** [comment]
<table border="1">
  <thead>
    <tr>
      <th colspan="3">Modals</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
        <img src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/3916436/b3716133-cd74-4422-ba45-6ca9c335e7c1" alt="CreditCardBillSummary" draggable="true">
        <br>CreditCardBillSummary
      </td>
      <td>
        <img src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/3916436/7d0ebb1e-b71b-4211-bbde-eb4ebaf17cb4" alt="EmploymentHistorySummary" draggable="true">
        <br>EmploymentHistorySummary
      </td>
      <td>
        <img src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/3916436/1d4c5f6e-cebf-4560-bed9-0fd96d12eaba" alt="InstallmentContractSummary" draggable="true">
        <br>InstallmentContractSummary
      </td>
    </tr>
    <tr>
      <td>
        <img src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/3916436/3eee5946-0c0b-4c86-af49-672bf9a6d936" alt="OtherAssetsSummary" draggable="true">
        <br>OtherAssetsSummary
      </td>
      <td>
        <img src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/3916436/2093eefb-3842-470e-93ea-91c1b298b6e6" alt="OtherExpenses" draggable="true">
        <br>OtherExpenses
      </td>
      <td>
        <img src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/3916436/959caa29-be30-4f03-b0da-b59f774f0fc3" alt="OtherIncomeSummary" draggable="true">
        <br>OtherIncomeSummary
      </td>
    </tr>
    <tr>
      <td>
        <img src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/3916436/d50440ed-6463-441b-a90c-4adc27474d7b" alt="SpouseEmploymentHistory" draggable="true">
        <br>SpouseEmploymentHistory
      </td>
      <td>
        <img src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/3916436/03f18ba1-0ac9-4e54-8e8c-be89496335c1" alt="UtilitySummaryCards" draggable="true">
        <br>UtilitySummaryCards
      </td>
      <td>
        <img src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/3916436/e19fff46-c785-4e52-a1aa-98e759ccc02c" alt="VehicleSummaryCards" draggable="true">
        <br>VehicleSummaryCards
      </td>
    </tr>
  </tbody>
</table>

**Comment by josephrlee** [comment]
Nice work @amponce!!!

**Comment by amponce** [comment]
The work is complete and the PR has been approved. Since we merged the cash in bank asset calculations today, I suggest we merge this on October 4th. This will allow some time monitor for bugs that might occur over the next 24 hours.

**Comment by amponce** [comment]
The destructive action modals have been merged to stage and the work is ready for review! @Tom-Davis @shiragoodman @HeatherRienks
