### ISSUE TITLE
[SW] Staging Review - Components or patterns don't align with guidelines, review page (63673) (Post Launch)

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#64428]
During the Staging Review on 8/15/23 this post launch feedback was provided #63673

### Platform Issue
Design components or patterns don't align with Design System guidelines.

### Issue Details
The review page does not have the edit buttons.

### Link, screenshot or steps to recreate
[Screenshot](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/staging-review-images/57105-Allison-040703.png)

### VA.gov Experience Standard
[Category Number 04, Issue Number 07](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

### Other References
WCAG SC 3.2.4 AA

### Platform Recommendation
Add the edit buttons in each review section and allow users to edit the information they entered. See the [design system](https://design.va.gov/templates/forms/review) for example.

**Comment by josephrlee** [comment]
@Tom-Davis, this is a dup of #63714 and should probably be closed. 

cc: @HeatherRienks
