### ISSUE TITLE
[SW] Staging Review - Outdated design components and patterns, start request (63670) (Post Launch)

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#64426]
During the Staging Review on 8/15/23 this post launch feedback was provided #63670

### Platform Issue
Design components and patterns in use are outdated. 

### Issue Details
After answering the correct question is the wizard, the user gets a green button with "Start your request now". Because this button navigates and since we have discussed button vs links, this should now be a green action link.

### Link, screenshot or steps to recreate
[Screenshot](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/staging-review-images/57105-Allison-040802.png)

### VA.gov Experience Standard
[Category Number 04, Issue Number 08](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

### Other References
WCAG SC 3.2.4 AA

### Platform Recommendation
Change the green button to a green action link.

**Comment by josephrlee** [comment]
I think this is a really simple fix. I can tackle it for both updating Sketch and the frontend code. 

cc: @Tom-Davis @HeatherRienks @Dr-Pongo
