### ISSUE TITLE
[Content organization] Your page doesn't follow heading hierarchy. Headings aren't properly nested, and headings and/or labels aren't relevant to the page. (02.04.01)

### ISSUE THREAD

**Issue by briandeconinck** [department-of-veterans-affairs/va.gov-team#64420]
[Copy of va.gov-cms#12080](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12080)

**Comment by CherylEvans** [comment]
@laflannery This ticket is correct. I will close 64838.

**Comment by laflannery** [comment]
Heading structure is correct, confirmed linked ticket is closed as well
