### ISSUE TITLE
[SW] Staging Review - Components or patterns don't align with guidelines, contact information (63675) (Post Launch)

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#64435]
During the Staging Review on 8/15/23 this post launch feedback was provided #63675

### Platform Issue
Design components or patterns don't align with Design System guidelines.

### Issue Details
On the contact information page, if the user chooses to edit their contact information the “Edit” links from the previous screen take the user to a relevant form for editing their information. On that edit page there are "Save" and "Cancel" and are the full width of the form. The [preferred name](https://design.va.gov/patterns/help-users-to/know-how-their-information-is-updated) of the button is "Update" and they should not be the full width unless they are viewing on a mobile device/small screen.

### Link, screenshot or steps to recreate
[Screenshot](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/staging-review-images/57105-Allison-040701.png)

### VA.gov Experience Standard
[Category Number 04, Issue Number 07](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

### Other References
WCAG SC 3.2.4 AA

### Platform Recommendation
Change the word "Save" to "Update" and make the buttons responsive.

**Comment by josephrlee** [comment]
Just chiming in on this ticket. I belive this was introduced when we started using the platform-level contact info code, @Dr-Pongo would have a better handle on it than me. I think this will be a FE fix, I added the FE label and will leave it to them to point.

**Comment by Dr-Pongo** [comment]
Yup! @josephrlee is correct, we are using a platform component, but after an initial check it looks like we may be able to passing a prop to include the text change, but the styling may be a platform level fix (that will affect any forms using the component, so we'll want to sus that out and make sure it's valid for everyone else. 

**Notes:** `ProfileInformationFieldController` prop `saveButtonText`

**Comment by mgleo** [comment]
@OptionSelect 
Correct styling: https://design.va.gov/storybook/?path=/docs/components-va-button-pair--update#update

Needs to be updated on 
- Contact info
   - Edit Mobile phone number
   - Edit Email address
   - Mailing address
