### ISSUE TITLE
Adjust Data layer push for search performance analytics

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#6443]
## What happened?
Feedback from @jonwehausen on [#5690](https://github.com/department-of-veterans-affairs/va.gov-team/issues/5690) on work done in [#4026](https://github.com/department-of-veterans-affairs/va.gov-team/issues/4026)

Whenever a search is performed, we want to do one dataLayer.push{('event': 'fl-search-results')}; , after ALL results have been returned. In other words, we want to do 1 push each time the loading indicator has disappeared and search results are returned.

## Steps to Reproduce
- URL: https://www.va.gov/find-locations

## Desired behavior
Perform dataLayer push once each time all new search results are returned

> dataLayer.push{(
>    'event': 'fl-search-results', //push once search results have been returned from API
> )};

## Acceptance Criteria
- [ ] _Describe the desired working behavior_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by jonwehausen** [comment]
Hi @mmiddaugh,

Thanks for creating this! @brangi Let's connect here and confirm this makes sense.
