### ISSUE TITLE
[SW] Staging Review - Components or patterns don't align with guidelines, benefits (63674) (Post Launch)

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#64434]
During the Staging Review on 8/15/23 this post launch feedback was provided #63674

### Platform Issue
Design components or patterns don't align with Design System guidelines.

### Issue Details
On the disability compensation and pension benefits card, if the user clicks "Edit" they get a "Cancel" and "Update" button pair. The buttons have chevrons. In our [design system](https://design.va.gov/components/button/button-pair#updatecancel) these buttons do not have chevrons.

### VA.gov Experience Standard
[Category Number 04, Issue Number 07](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

### Other References
WCAG SC 3.2.4 AA

### Platform Recommendation
Remove the chevrons within the buttons.

**Comment by josephrlee** [comment]
This looks like a pretty simple fix, I'm guessing it's a 1 pointer. [Code to edit is here](https://github.com/department-of-veterans-affairs/vets-website/blob/6d89970e68a7f238a773521104ecbabd12708d97/src/applications/financial-status-report/components/debtsAndCopays/EnhancedBenefitsEdit.jsx#L110).

I think we just need to remove the `iconLeft` and `iconRight` lines.

```
      <ButtonGroup
        buttons={[
          {
            label: 'Cancel',
            onClick: onCancel,
            secondary: true,
            iconLeft: '«',
          },
          {
            label: 'Update',
            onClick: onUpdate,
            iconRight: '»',
          },
        ]}
      />
```

**Comment by mgleo** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ3ZMIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3e3f579b565ca8b8fa9a43a9ac8b6f0000b50dce/Screenshot%202023-09-22%20at%2011.25.51%20AM.png)

**Comment by OptionSelect** [comment]
I have deleted the lines but am having trouble testing. Still working on this to prove fix worked.

**Comment by HeatherRienks** [comment]
@OptionSelect - any updates to share on this one?
