### ISSUE TITLE
[DA] 10-10EZ - Performance: Track increased traffic during special PACT Act enrollment period

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#64436]
## Background
[PACT Act Enrollment Period](https://www.va.gov/eastern-colorado-health-care/news-releases/pact-act-enrollment-period-for-combat-veterans-ends-sept-30/) 
Veterans who served in Iraq, Afghanistan and other post-9/11 combat zones may enroll in VA health care without first applying for VA benefits, a special enrollment period that ends Sept. 30, 2023.

We expect to see the traffic of 10-10EZ application submissions spike between now and 9/30/2023, and especially during the last week leading up to that end date.

- [ ]  Monitor the current trend of HCA submissions to validate the hypothesis.
- [ ]  Report back to team on the outcome of September's average submissions of 1010ez

## Acceptance Criteria
- Performance and volume of application submissions is monitored and urgent issues addressed, if any.

**Comment by hdjustice** [comment]
@luis-simauchi - here is the ticket we can use to monitor the traffic for the special enrollment period.

**Comment by luis-simauchi** [comment]
Monday Sept 4th update: 247 HCA submissions
HCA submissions are low for a Monday (typical mondays get ~500 submissions)
but this was a holiday so it is not surprising.

**Comment by luis-simauchi** [comment]
NOTE FROM LAUREN ALEXANDER on Friday

**Comment by luis-simauchi** [comment]
For awareness here's the schedule of communications going out for PACT for the next couple of weeks. Anticipate more user traffic short after these blasts of communications.
9/14 – E-mail (~250K)
9/18 – Mail posted (~430k) Hits mailboxes around the 20th)
9/18 – VetResources Superusers E-mail Sent (~1.5M)
9/20 – Text (>400K)
9/27 – Additional VetResources E-mail Sent (13M)
