### ISSUE TITLE
Staging review - design feedback -  for converted components: Button, Button Pair and Modal

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#64453]
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

-

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

### All

- I would recommend labeling each example with which version it is.

### Button Pair

- In the [design system](https://design.va.gov/components/button/button-pair#examples---v3), the left button seems to be cut off in the V3 example

### Modal

- In the [Sketch file](https://www.sketch.com/s/a52734dd-00d0-44f1-9c9e-ff4016130e5c/p/D10C68C1-35D7-4AB9-A020-BD7052EEDD1B/canvas) the primary button on the mobile screens is not full width of the content but the secondary button is. In [Storybook](https://design.va.gov/storybook/?path=/story/uswds-va-modal--default) it is the opposite. I checked [USWDS](https://designsystem.digital.gov/components/modal/) and they do not show an option with a primary and secondary button so I am not sure which is correct.
- The font family in Storybook is Merriweather, not Bitter

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/va.gov-team/64453?planning-poker) with Zenhub @babsdenney @danbrady @LWWright7

**Comment by Andrew565** [comment]
I checked everywhere in Storybook's modal examples, and the headline everywhere is rendering as Bitter, not Merriweather; I believe this ticket can be closed if that was the only remaining thing to address.

**Comment by caw310** [comment]
Large Modal in Storybook is using Merriweather not Bitter which needs to be fixed.

**Comment by caw310** [comment]
Button being cut off is still an issue in Storybook.

**Comment by babsdenney** [comment]
[Ticket to fix Large modal header and icon placement](https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/issues/gh/department-of-veterans-affairs/vets-design-system-documentation/2219)

**Comment by Andrew565** [comment]
This appears to be the culprit for the Button Pair being cut-off problem:
![Screenshot 2023-10-26 at 12 17 47 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/147893/9a94f46b-7b66-4597-8c73-f9a4fef665f6)

**Comment by caw310** [comment]
We will only work on button pair cut off issue.

**Comment by caw310** [comment]
MOving to next sprint
