### ISSUE TITLE
Vets-api terminal access for [Zac Yellowhorse]

### ISSUE THREAD

**Issue by zyellowhorse** [department-of-veterans-affairs/va.gov-team#64469]
### Your Name

Zac Yellowhorse

### Your GitHub handle (terminal access is managed through GitHub)

zyellowhorse

### Team, Role, and Company of the target individual

Teams DBEx 2, Non-Disability Benefits Exp, Dependents Exp. DevOps Engineer from Oddball

### Product Manager (PM) name and email

Austin Price austin.price@coforma.io

### Product Owner (PO) name and email

Matt Self matthew.self2@va.gov

### COR Name (leave "None" if you listed an AWS user name above)

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

Other - please specify in 'Additional Notes'

### Please confirm if you are on the VFS Team Roster or Platform Team Roster

- [X] [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Please confirm E-QIP Transmittal/Adjudication. This could be a screenshot of your Transmittal/Adjudication email, a link to another request where you've submitted this proof (i.e. AWS/SOCKS), etc.

- [X] I have attached proof that I have either transmitted my E-QIP survey or previously received a favorable decision (by including in "Additional Notes" section below)

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### Additional Notes

COR: Keith Riley [keith.riley@va.gov](mailto:keith.riley@va.gov)
VOR: Jeff Langworthy [jeff.langworthy@coforma.io](mailto:jeff.langworthy@coforma.io)

I need this access to investigate issues in vets-api. I need to be able to debug and review so that I can understand issues and bugs in vets-api.

E-QIP Transmittal Date Proof: https://github.com/department-of-veterans-affairs/va.gov-team/issues/59644

### Additional resources for Support Engineer

- [ ] For users on a VFS team but not in the VFS Team Roster, they must start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] Instructions for handling requests [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access) - Support Only

**Comment by lindsay-insco** [comment]
Found in VFS Roster

eQIP Transmittial provided

**Comment by BillChapmanUSDS** [comment]
Hey @zyellowhorse are you a full time Devops focused or SRE Engineer who would be expected to help out off hours? .  We can allow the extended (6 month) access for Devops and SRE engineers that are also expecting to provide firefighting support during incidents. 

However for engineers that are not full time Devops or SRE and are also working on the front end experience we are working to reduce production access. In this case the notes mention needing to be in production for debugging.  If you are primarily an application focused engineer can you give us a specific example of an issue you've needed to debug that required production access?  If you provide a specific example and add the access-justification-example provided label than @lindsay-insco  can give you 6 months access. 

Approved with guidance. If full time Devops engineer with off hours expectation,  give six months. IF not full time devops, give 6 months if specific example is provided. Without an update, give 3 months.

**Comment by lindsay-insco** [comment]
@zyellowhorse You've been given access to Production limited to 6 months, expiring 03/14/24. Please set a reminder for yourself to return to this Issue and re-request access within 1 week of the expiration date. You'll receive 1 reminder with a 72 hour window to respond. Failure to do so will result in lost access and will require you to fill out a new request.

**Comment by lindsay-insco** [comment]
Slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1694723704799189)
