### ISSUE TITLE
Minor adjustment to how Form5655Submission conceives of streamlined waivers

### ISSUE THREAD

**Issue by kjsuarez** [department-of-veterans-affairs/va.gov-team#64462]
Form5655Submissions store the `streamlined` status in a json blob stored as an encrypted string. Great for PII but terrible for making efficient queries about streamlined waivers. The problem is minor now because SW functionality is only 1 month old, but the more that we process the more difficult it will be to reason about them in code.

- [x] Add a jsonb column to Form5655Submission model column called 'public_metadata'
- [x] push to master, get deployed
- [x] (separate PR)
- [x] run script in stg/prod to update the column for existing SW submissions
- [x] Update FinancialStatusReportService to store streamlined data in the new column
- [x] Update Form5655Submission to add streamlined scope
- [x] Add specs

**Comment by HeatherRienks** [comment]
@kjsuarez - has this been merged? If so, pls feel free to move to "Closed" - thanks!
