### ISSUE TITLE
BE | Auth Exp | Verify code ownership

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#64468]
## Background
Verify ownership of Authenticated Experience backend code.

See ticket - https://github.com/department-of-veterans-affairs/va.gov-team/issues/63606

## Tasks
- [x] Review current code ownership list for the auth-exp team and make necessary updates.

## Acceptance Criteria
- [x] Notify platform support team when complete

**Comment by tpharrison** [comment]
@RachalCassity - This ticket is for reviewing the BE code ownership for the Auth Experience team. We plan on reviewing next week.  Hopefully we're not holding things up - let me know if we are.

**Comment by mtcA6** [comment]
likely to extend beyond sprint 19

**Comment by tpharrison** [comment]
Some obvious code-ownership updates have been made.  The rest can be addressed as they come up.
