### ISSUE TITLE
SOCKS access for Julia Young

### ISSUE THREAD

**Issue by young1205** [department-of-veterans-affairs/va.gov-team#64479]
### Your Name

Julia Young

### Your Email

julia.young@adhocteam.us

### Your Role and Team

Fullstack Engineer on Appointments (VAOS)

### Product Manager (PM) name and email

Jeff Roof (jeffrey.roof@adhocteam.us) 

### Product Owner (PO) name and email

Kay Lawyer (katherine.lawyer@va.gov) 

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDGkT5xklsy31eGyDTi/p3PgoclWH3eRIBgJ4xEemZLNKDiqygLGwZ21i5bgNQl/bXsb88V8gv7CTCxttVrp3bjNP+LS9ut0jY3rVyiywXW8WB4SE7IxIHm+HXWfcreuC/OV9On1wVRUbgLdq8rkMaFruiH1ST14ZpS1EpEcCw9W7zZ3G6zYn8rMSQNy3gEi5n7PZq1aCWrktuAeMj0kOOr7O26CfIUlnmfUK8Sa/wWOWJF9s9FwgplH2g0ghJXVQBFKEMyFz/M8FhlNEa/rcNRb28H1GhxM14qal69eY0JP0gXqLqHQ/PWpVqE3y88xH8fzbWQiPhg+GDhKYER/ySapaVNvJxq7lgeO+Sf1Oroo9Th/UJuG3/QJVlGFZwswQS6HQ++KwLAlHUK2v7/k4bzKxbDnNwJp82ZiwwaXQV7HD39GAZwedWFTjrIwYP6jy5qHg4kNnf0HctHrnaNKHrdpXDfgOevj7gj9HfaJN+ul+2rv+19JGkV2spTC1QmFeM= juliayoung@juliayoung-Q2QV2770CD

### E-QIP Transmittal Confirmation

<img width="946" alt="Screenshot 2023-08-29 at 12 23 08 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/2670134/317bd9c3-8582-4069-94c0-6d07ce9ec80b">

(As I completed my E-QIP for CMS - WDS in 2020 I do not have a record of the E-QIP Transmittal Confirmation, I do have a PIV card currently)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by ben-allen-oddball** [comment]
SOCKS access has been granted.
