### ISSUE TITLE
[Frontend] MDT- Submission Endpoint- API Integration

### ISSUE THREAD

**Issue by mojaray2k** [department-of-veterans-affairs/va.gov-team#6448]
## User Story:
As a frontend developer, I need to set up the plumbing of the submission endpoint for MDT form so that all the form data can successfully sent to the back end. 

## Tasks
- [ ] create a all the necessary actions, action creators, and reducers needed
- [ ] make sure the end point is connected to the form

## Acceptance Criteria:
- Form data should be successfully submitted to the backend from the front end.

**Comment by leahkeeler** [comment]
Moving to backlog - awaiting DLC API
