### ISSUE TITLE
EMIS Deprecation: Ensure documentation is up to date

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#64496]
### PROBLEM STATEMENT
We are updating all emis calls with vaprofile calls. Documentation needs to be updated to reflect these changes. 

### ADDITIONAL INFORMATION
An audit of documentation will be stored [here](https://docs.google.com/spreadsheets/d/1mRf9iMPusSdhjoJ7jRysyZG3u3FbBvaYDuz-5KK4-Ag/edit#gid=66081814)

### ACTION ITEMS
- [x] complete an audit to find all places where emis is referenced in developer documentation
- [x] update documentation

### DEFINITION OF DONE
- [x] an audit of the documentation is complete and linked above
- [x] documentation is updated

**Comment by holdenhinkle** [comment]
I reviewed the following sources for possible EMIS documentation:
- vets-api
- confluence
- platform dev docs

EMIS is not mentioned in any of the `.md` files in `vets-api`.

I identified 4 pages in Platform Docs and their source of truth in Confluence that need to be deleted or updated.

I identified several other pages in Confluence (which are not published in the Platform Docs) that need to be deleted or updated.

Here's the link to the spreadsheet (which is linked above) - https://docs.google.com/spreadsheets/d/1mRf9iMPusSdhjoJ7jRysyZG3u3FbBvaYDuz-5KK4-Ag/edit#gid=66081814

**Comment by rmtolmach** [comment]
Thanks for reviewing the docs Holden!

Level of Effort for updating the docs: low-medium. Most of the pages just mention eMIS in passing and those shouldn't be hard to update. The biggest lift is the one page all about emis that will probably need to be replaced/re-written with one for VA Profile.

**Comment by laineymajor** [comment]
Awaiting final review. Then will close.

**Comment by LindseySaari** [comment]
Documentation has been updated and the new VA Profile doc has moved into the External Integrations directory on Platform website
