### ISSUE TITLE
[Congressional] V10774264 - Veteran has issues logging in and has ticket numbers enclosed in the email's PDF attachment. Due 9/29/23

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#64511]
## Issue Description
_Veteran has issues logging in and has ticket numbers enclosed in the email's PDF attachment.
https://dvagov.sharepoint.com/:f:/s/DigitalExperiencePMOInternalFTC-PrivateOCTO-DEActions/EtK_RqAdTHJHhUN9Ii-Zf-8BN1hq5QF_vEQrYpXRj_lTDw?e=i7Zhk6

---
## Tasks
- [x] Review congressional correspondence
- [ ] Resolve issue 
- [ ] Notify Veteran and congressional correspondence channel of solution.

## Acceptance Criteria
- [ ] Veteran issue will be resolved or responded to with final answer to issue 
- [ ] Congressional Correspondence will receive details of the resolution 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by clantosswett** [comment]
Messaged Joe Niquette to see if he knows what might be the issue. Will conduct any necessary outreach once he's responded with initial guidance/questions.

**Comment by clantosswett** [comment]
Asked the veteran to provide screenshot of the error message they are seeing. It sounds like this is an IAM issue so will likely escalate to the IAM team once we have more information from the Veteran.

**Comment by clantosswett** [comment]
Sent a follow up message to the Veteran today (9/26) as we have not received a response yet.

**Comment by clantosswett** [comment]
No response from Veteran. Closing this issue as no further action can be taken.
