### ISSUE TITLE
Null Claim - Send to Central Processing on Failures

### ISSUE THREAD

**Issue by tblackwe** [department-of-veterans-affairs/va.gov-team#64538]
When 686/674 submissions fail, we should send the PDF of the claim to Central Processing so we ensure the claim is processed eventually.

As part of this, we should move the PDF upload to only occur IF AND ONLY IF we successfully establish claims. This will mark the final point of the 'Null Claim Universe' and give us an end date on what needs to be reprocessed. 

Currently our flow is:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ0pmIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8887ab756689825af50cf3a5c231f52398f1e07b/image.png)

New Path
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ3RmIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b590b8d1bf3e623d3c9dd97f579c495fdb8c2e0a/image.png)

If the Central Processing Claim fails, we need to raise an error in Sentry/Datadog and attempt to email the Veteran (using the existing DependentsApplicationFailureMailer logic)

[526EZ does this already](https://app.zenhub.com/workspaces/benefits-team-1-6138d7b57a2631001a4b7562/issues/gh/department-of-veterans-affairs/va.gov-team/50111)

Some Notes from Kyle:

>       `CentralMail::Service.new.upload(processor.request_body)`

> does pretty much everything you need and already exists. Just gotta make sure you pass it the right stuff, and that the logic on when to send and when not to is sound. (and rejigger the order, so it only uploads to eFolder if the claim submission is successful instead of doing both at the same time like currently)
> Like right now you do
> 
> `establish_claim.perform() # async job queued`
> `upload_to_eFolder.perform(doc) # async job queued`
> 
> itll need to I think be something like
> 
> `establish_claim.perform() # async job queued`
> 
> and then

> `if claim_established_successful?`
>   `upload_to_eFolder.perform(doc) # async job queued`
> `else`
>   ` send_to_central_mail.perform(doc)`
> `end`

> added into that establish job

**Comment by steele-lm** [comment]
For remaining claims that cannot be processed, we will be showing an alert to users letting them know their claim failed.
