### ISSUE TITLE
Enable Intent to File in production: 25% traffic

### ISSUE THREAD

**Issue by mchae-nava** [department-of-veterans-affairs/va.gov-team#64556]
## Issue Description
This is a timeboxed item to monitor traffic and issues via DataDog after directing 25% of users

https://vagov.ddog-gov.com/dashboard/ipg-v6d-c59/benefits---dbex---evss-to-lh-intent-to-file?from_ts=1692803125926&to_ts=1693407925926&live=true

## Tasks
- [ ] Use DD to monitor for anomalies
- [ ] If no anomalies within the agreed timebox, raise to 50%
- [ ] If any issues, rollback to 10% and create ticket to address

## Acceptance Criteria
- [ ] No anomalies and traffic raised to 50%

**Comment by sethdarragile6** [comment]
Moved to 50% today at 10:52 AM PST
