### ISSUE TITLE
[Epic] EVSS to LH Document Service Migration

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#64563]
Epic contains all stories needed for migrating Veteran Documents to LH

**Comment by NB28VT** [comment]
This epic has been replaced by a [new one](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/83837) but we will preserve some of the issues for documentation purposes

**Comment by lisacapaccioli** [comment]
> This epic has been replaced by a [new one](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/83837) but we will preserve some of the issues for documentation purposes

@NB28VT Does that mean we can close this Epic (even though there are tickets not completed on it)?
