### ISSUE TITLE
[Exploration] How can we better elevate personalized updates on My VA?

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#64569]
## Background

Integrating notifications into My VA via VANotify was a tool-driven solution to elevating important information on My VA and VA.gov. Now that we've determined that the VANotify path isn't viable, we have an opportunity to revisit the main problem notifications were trying to solve -- how do we get high-priority and timely information in front of users?

To help us think about this differently, I'd like us to ignore the current My VA design and give our brains space to start over. Let's put together some explorations of My VA that do the following:

- Totally ignores the current design (not because it's bad, but because I don't want it to hold back good ideas)
- Thinks about what is the most high priority information My VA communicates, and how we can more effectively elevate it
- Does not consider written notifications/a notification center as the only solution for elevating/prioritizing information.

Go wild. Let's have some fun and see how that reinvigorates how our brains are thinking about My VA.

## Tasks
- [x] Create explorations
- [x] Review with team and discuss what we can learn from these explorations

Not a task for the design folks, but the goal is for Samara/AJ to then be able to consider if there are lessons learned that we can incorporate into our larger strategy around notifications.

**Comment by andaleliz** [comment]
Hi @ajakabcin - this is exciting! Is the idea for us to figure out amongst ourselves how to tackle this? I assume so :) We are syncing as a group on Tuesday so that'd be a good opportunity for us to coordinate.

**Comment by ajakabcin** [comment]
hey @andaleliz - yes! I know @aagosto90 has some thoughts already so I think you all will coordinate next week, but let me know how I can support otherwise.

**Comment by aagosto90** [comment]
[Mural board used for exploration](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1693925852834/4769a4018a2c9100922306aef36bc8536298d20b?sender=ud5c82d652d231345efaf6060)
