### ISSUE TITLE
[spike] Document Upload Migration - Implementation

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#64564]
There are a few aspects to this ticket
1. Fix an inheritance problem that exists due to switching to LH
2. Refactor upload worker and associated tests to fork into EVSS or Lighthouse
3. Update everywhere where we need to change logic and update feature gate

**Summary For Inheritance:** 

When moving our document submission to Lighthouse, we can't use the SupportingEvidenceAttachment class currently referenced in the app/workers/evss/disability_compensation_form/submit_uploads.rb worker. This is because those attachments are associated with an uploader, SupportingEvidenceAttachmentUploader, which inherits from EVSSClaimDocumentUploaderBase and uses its CarrierWave logic. 

EVSSClaimDocumentUploaderBase is being replaced by LighthouseDocumentUploaderBase, which has Lighthouse API-specific document upload behavior.

Therefore, if we want to reference a Lighthouse-specific evidence attachment in the upload worker, we need to duplicate both SupportingEvidenceAttachment and SupportingEvidenceAttachmentUploader (the subclass of EVSSClaimDocumentUploaderBase), with LighthouseSupportingEvidenceAttachment and its associated  LighthouseSupportingEvidenceAttachmentUploader, which inherits from LighthouseDocumentUploaderBase.

**Summary for 2&3**

Acceptance Criteria:

- [x] Duplicate SupportingEvidenceAttachment and SupportintEvidenceAttachmentUploader with Lighthouse equivalents where the uploader inherits from LighthouseDocumentUploaderBase
- [x] Duplicate any associated tests
- [x] Refactor SubmitUpload worker to branch between LH and EVSS based on feature gate (build new service)
- [x] Add tests for LH codepath
- [ ] Update remaining branch points where LH logic will replace EVSS logic
- [ ] Address any locations where we don't yet know how to proceed

**Comment by NB28VT** [comment]
I'm actually going to suggest we do separate the flipper implementation and the inheritance fix into separate tickets or at the very least they will be separate PRs, I think the inheritance fix will be big enough from a diff standpoint to warrant its own PR with its own description of the issue. The flipper implementation will happen after

**Comment by NB28VT** [comment]
(Just adding notes ahead of our discussion meeting this afternoon)

- For the inheritance fix, we plan to simply copy paste old EVSS code to Lighthouse code, including code that is fairly old and some that appears to be untested. The time scope on this will be longer if the VA reviewer (perhaps rightly) pushes back on bad code or untested code. So something worth considering

**Comment by austinjprice** [comment]
@NB28VT  to add summary for 2 and 3

**Comment by austinjprice** [comment]
Question for team 1 @RakshindaAslam @mchae-nava from @NB28VT : In cases where the migration to Lighthouse requires copy pasting functionality from old EVSS code, have you been refactoring the code to improve to it improve/adding more tests, and/or have the VA/Platform reviewers been pushing back on us copy pasting old less than ideal code? And how have you been weighting that against urgency/timeline of migration?

**Comment by RakshindaAslam** [comment]
@sethdarragile6 @aurora-a-k-a-lightning - for your response

**Comment by austinjprice** [comment]
@NB28VT @SamStuckey @micahaspyr to determine if there is opportunity to split work

**Comment by NB28VT** [comment]
To reset planning here, summarizing the scope of all preliminary work on this project as I see it.

### Overview 
It's helpful to think of the "Document Upload Migration" as encompassing needed changes to:

1. All places in the Form 526 flow where veterans upload required forms they have filled out manually.
2. All places in the Form 526 flow where veterans upload medical records and supplemental evidence.
3. The point in the final Form 526 submssion job where we upload those veteran-supplied documents to Lighthouse.
4. The point in the Form 526 submission job where we upload the Form 526 output itself to Lighthouse.
5. The points in the Form 526 submission where we assemble and upload additional forms (Form 8940 and BDD instructions for example)


### Investigation 
- [X] Make changes to solve the inheritance problem Sam discovered (done in draft form in this [PR](https://github.com/department-of-veterans-affairs/vets-api/pull/1383) but not yet reviewed)
- [X] Refactor the main Form 526 attachments upload to EVSS to upload to Lighthouse when the switch is enabled (done in draft form in this [PR](https://github.com/department-of-veterans-affairs/vets-api/pull/1383) but not yet reviewed)
- [X] Review and comment on findings in Sam's early investigation PR https://github.com/department-of-veterans-affairs/vets-api/pull/13576
- [x] Use the Mural form flow to map all locations Veterans can upload supplemental documents, and understand what they do so we have context to test themn later.
- [x] Use that knowledge to develop list of backend changes needed to get those attachments working with the new Lighthouse submission
- [ ] Review the code and Seth's mapping of the upload flow to identify all additional forms we submit with a Form 526.
- [ ] Understand what those ancillary jobs are doing
- [ ] Draft a list of changes needed to update those jobs

### Testing Plan (not in this ticket's scope):
- [ ] Get familiar with working with the Lighthouse Sandbox API
- [ ] Determine if the uploads endpoint is available for testing yet
- [ ] Determine if we can use mocking tools such as VCR to test handling responses from Lighthouse
- [ ] Draft a plan for manually testing document uploads with Lighthouse
