### ISSUE TITLE
FE | Profile | Modal being triggered even when no edits have been made

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#64577]
## Background
We trigger a modal ([mock-up](https://www.sketch.com/s/59857eb5-d9f9-4145-99d3-d9a1de2d0655/a/pamAp4p)) when a user is editing a section, and then tries to enter edit mode for another section without saving or canceling their changes.  This modal is also being triggered even when the user hasn't made any changes, and it shouldn't.

If a user hasn't made any changes and clicks "edit" for another section, the behavior should be the same as if they had hit the cancel button without making changes.

This is happening in personal information, contact information, and direct deposit. You can check it out on staging with user 378 - click edit for a section, don't make changes, and then hit edit in another section.

## Tasks
- [x] update code so the modal isn't triggered if no changes have been made and the user attempts to edit another section

## AC
- [x] modal isn't triggered if no changes have been made and the user attempts to edit another section

**Comment by adamwhitlock1** [comment]
So i have this PR approved, but there are tests that are failing that are unrelated that are preventing me from merging this. I submitted a support request and will follow up as soon as that gets resolved.

https://dsva.slack.com/archives/CBU0KDSB1/p1694562357952859

**Comment by adamwhitlock1** [comment]
This is deployed to staging and ready to validate. @mtcA6 you can validate by opening any field on the contact info page for example and not make any changes and then click edit on another field section. You should see the open section close and the new section open to the 'edit mode' without the confirmation modal appearing.

Quick recording of doing this with the phone number fields:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcjZhIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ba326d104e1c030b5b9cdc24c1c0c206fa9c42f0/edit-no-changes.gif)
