### ISSUE TITLE
Access for Patrick Black

### ISSUE THREAD

**Issue by patrick-black-oddball** [department-of-veterans-affairs/va.gov-team#64575]
### COR Name

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Patrick Black

### Your Email

patrick.black@oddball.io

### Team, Role, and Company of the target individual

Reliability Team, Senior DevOps Engineer, Oddball inc

### Product Manager (PM) name and email

Amber Malcolm - amber@oddball.io

### Product Owner (PO) name and email

Bill Chapman - William.W.Chapman@omb.eop.gov

### Desired AWS Access

Standard DevOps permissions

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

<img width="2507" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/141665052/be2127e6-23ad-4265-8c9f-a133a3f6c3f3">

### Additional Notes

Ray Wang is the CDR

ongoing access required in support of DevOps role

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by ph-One** [comment]
Found on VFS Rosetr

**Comment by ph-One** [comment]
@BillChapmanUSDS

**Comment by ben-allen-oddball** [comment]
Access has been provisioned.

**Comment by ben-allen-oddball** [comment]
Reset password for user post provision.
