### ISSUE TITLE
Upgrade @Sarkis to multi-channel guest on DSVA Slack

### ISSUE THREAD

**Issue by aubreyarcangel** [department-of-veterans-affairs/va.gov-team#64584]
# Description
Sarkis Semerjian is an existing single-channel DSVA slack user. Please upgrade his account to a multi-channel user and add him to #medallia-collaboration

His email is sarkis.semerjian@va.gov

Sarkis Semerjian is our point of contact on the VSignals team and works with the Contact Center team to implement and manage our Medallia feedback tool on VA.gov

**Comment by LEHigley** [comment]
couldn't add to requested channel so made multi channel and added to general

**Comment by aubreyarcangel** [comment]
Thank you @LEHigley!
