### ISSUE TITLE
Enable Intent to File in production: 50% traffic

### ISSUE THREAD

**Issue by mchae-nava** [department-of-veterans-affairs/va.gov-team#64589]
## Issue Description
This is a timeboxed item to monitor traffic and issues via DataDog after directing 50% of users
Timebox: 1 week

https://vagov.ddog-gov.com/dashboard/ipg-v6d-c59/benefits---dbex---evss-to-lh-intent-to-file?from_ts=1692803125926&to_ts=1693407925926&live=true

## Tasks
- [ ] Use DD to monitor for anomalies
- [ ] If no anomalies within the agreed timebox, raise to 100%
- [ ] If any issues, rollback to 25% and create ticket to address

## Acceptance Criteria
- [ ] No anomalies and traffic raised to 100%

**Comment by sethdarragile6** [comment]
Moved to 50% today at 10:52am PST

**Comment by mchae-nava** [comment]
On hold until after the next PACT act deadline (9/30)

**Comment by alatempa24** [comment]
Team re-estimated based on effort during sprint planning 9/27/23
