### ISSUE TITLE
QA Standards - Veteran Facing Forms - Form 21-0972 Alternate Signer

### ISSUE THREAD

**Issue by it-harrison** [department-of-veterans-affairs/va.gov-team#64593]
#### VFS team name
Veteran Facing Forms

#### VFS product name
Form 21-0972 Alternate Signer

#### VFS feature name
Form 21-0972 Alternate Signer

#### Point of Contact/Reviewers
@it-harrison - Ian Harrison - QA
---
#### Regression Test Plan 
- [x] Standard has been met
- [ ] Standard has not been met
#### Test Plan
- [x] Standard has been met
- [ ] Standard has not been met
#### Traceability Reports 
- [ ] Standard has been met
- [x] Standard has not been met
#### E2E Test Participation
- [x] Standard has been met
- [ ] Standard has not been met
#### Unit Test Coverage
- Lines %: 55.21

- Functions %: 27.03

- Statements %: 54.64

- Branches %: 22.22

- [ ] Standard has been met
- [x] Standard has not been met
##### Explanation of failure to meet standard (if applicable): #####
All components (lines, functions, statements, and branches) should be greater than or equal to 75%.

### Bugs
The following bug was found during testing and is being reported here because it does not fall specifically within the Experience Standards or the QA Standards

At the "Sign VA claim forms as an alternate signer" step, in the "Your full name" input if a user enters 
* their name without spaces (e.g. "JohnSmith" instead of "John Smith") **OR**
* their name in upper-case when they had previously entered it in lower-case

Then no error message appears but the user cannot proceed.

https://github.com/department-of-veterans-affairs/va.gov-team/assets/8867779/01ccdf31-8ac9-4c64-9ca6-163b6c4bd57e

---
### VFS Guidance

- Close the ticket when your Product Owner determines that you have sufficiently met the QA Standards.
- If your team has additional questions or needs Platform help validating the issue, please comment on the ticket

### Platform directions
- Update "Issue Title" to be of the form "QA Standards - VFS Team - VFS Product"
- Add the VFS team, product name, and feature name
- Add your name, practice area, and GH handle under Point of Contact/Reviewers
- Complete the QA Standards section, making sure to include an "Explanation of failure to meet standard" for every Standard the product does not meet.
- Link to the Collaboration Cycle Request epic
- Add assignees: 
  - VFS PM
  - Yourself (optional)
- Add labels:
  - VFS team label
  - VFS product label
  - QA-standards label
  - launch-blocking label if the product has failed to meet a required QA Standard

**Comment by tbaker1026** [comment]
@it-harrison This has been fixed ok to close the QA ticket?

**Comment by it-harrison** [comment]
@tbaker1026 yes, absolutely.
