### ISSUE TITLE
Contact Center Review for Employee Experience Team - 21-526EZ, max rating education

### ISSUE THREAD

**Issue by amylai-nava** [department-of-veterans-affairs/va.gov-team#64605]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
*Please provide the name(s) of your product and a high-level description of your product.*

**Feature description**
The [#benefits-cft-employee-exp](https://dsva.slack.com/archives/C01BVF2A3V0) team is nearing the launch of a small feature we're piloting within the 21-526EZ product. The feature contains one line of text on the Rated Disabilities screen—You're already at the maximum rating for tinnitus—which will be displayed to a subset of users who have a 10% tinnitus rating. We'll be conducting A/B testing to assess the effectiveness of the education.

**Project context**
10% is the highest rating for tinnitus. However, Veterans who have a 10% rating for tinnitus can still submit a claim for increase if their condition has gotten worse. The majority of the time, these claims are not granted an increase. So, we're adding text that reminds Veterans they are already at the maximum rating for tinnitus within the 526 form (the same information they get in their decision letter) to evaluate the effectiveness it has on reducing the number of these types of claims that do not get granted. 

### Launch Date
*Please provide the launch or rollout date and details.*
- [link to launch plan](https://docs.google.com/document/d/1EcbIeiju10luMV2BjRobF1Lgr-uzpO0z80hPsTd2WiA/edit?usp=sharing)

### Version Number
*Please provide the version number of the guide and/or video.*
- [526 Product Guide, v2.1](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/disability/526ez/product/526ez%20Product%20Guide)

### Product Guide
*Please provide product guide link*
- [526 Product Guide, v2.1](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/disability/526ez/product/526ez%20Product%20Guide)

### Product Video
*Please provide product video link*
- N/A

### Product Video Transcript
*Please provide product video transcript link*
- N/A

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
No changes from VEO. Copy attached for future use/updates.
[526ez Disability Benefits Claims Product Guide v2.1 SRT 09052023.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/12562773/526ez.Disability.Benefits.Claims.Product.Guide.v2.1.SRT.09052023.docx)
