### ISSUE TITLE
Flipper UI access for [Evan Smith]

### ISSUE THREAD

**Issue by evansmith** [department-of-veterans-affairs/va.gov-team#64608]
### Your Name

Evan Smith

### Your GitHub handle (Flipper UI access is managed through GitHub)

evansmith

### Team, Role, and Company of the target individual

VFS Benefits and Claims Engineer - Oddball

### Please confirm if you are on the VFS Team Roster, Platform Team Roster or are a Federal User

- [X] [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [X] Lesser Environments (Dev/Staging/Sandbox)
- [X] Production (if requesting, justify prod access below)

### Reason for Production Access (If requested)

Recently developed a feature with the dependents_enqueue_with_user_struct flipper that is now on production.

**Comment by bdech** [comment]
Found in VFS Roster

**Comment by bdech** [comment]
Access to lower environments and prod granted.
