### ISSUE TITLE
Broken link for Collaboration Cycle Office Hours

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#64602]
### Description

On the [Collaboration Cycle FAQ](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/faqs) page, there are multiple mentions of "Collaboration Cycle Office Hours", however the link does not point to a working Calendly.
<img width="1120" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/142453186/af8c01d7-78c3-415f-91bb-09bd52fc21f1">

### Relevant URLs
The links are currently pointing to https://calendly.com/platform-office-hours/collaboration-cycle

I think they need to be updated to https://calendly.com/platform-office-hours/collaboration-cycle-office-hours?back=1&month=2023-08

### Which type of team are you on? (Platform team, VFS team, or Leadership)
VFS

**Comment by vbellissimo** [comment]
Hi @oddball-lindsay, thanks for flagging this. We're taking a look to update.

**Comment by torrirosine** [comment]
I have updated both locations with the correct link

**Comment by oddball-lindsay** [comment]
Thank you @torrirosine !

**Comment by vbellissimo** [comment]
These changes are now reflected live on the site. Closing this ticket now. Thanks again @oddball-lindsay
