### ISSUE TITLE
develop footer content for standard email template in GovDelivery

### ISSUE THREAD

**Issue by djmunoz1** [department-of-veterans-affairs/va.gov-team#64618]
As an email admin, I want email footer content that can persist on campaign emails so that Veterans see consistent footer messaging throughout the campaign.

AC:
- Review 'Current Default Content' (below)
- update to remove option to stop subscriptions (these are NOT marketing emails, these are early feature deprecation notices so Veterans should not be able to opt-out)
- Ensure we provide help content -- consider using some portion of 'Existing Email Content' (below)

DEF OF DONE:
- run internal review with UX team
- share content via Google Doc with PM (Dawn + Lauren) for follow up with Granicus
- Incorporate any feedback from PM

**Bkgrd:**
Current Default Content:
Update your subscriptions, modify your password or email address, or stop subscriptions at any time on your 'Subscriber Preferences Page. You will need to use your email address to log in. If you have questions or problems with the subscription service, please visit subscrberhelp.govdelivery.com.

Existing Email Content:
We’re here to help. Find out more about Login.gov and the changes that are coming to the sign-in process. 
Learn more about securely signing in with Login.gov
<https://www.va.gov/resources/signing-in-to-vagov/>

If you have trouble signing in, get answers to some commonly asked questions about signing in to VA.gov.
Learn more about signing in to VA.gov
< https://www.va.gov/resources/signing-in-to-vagov/>

If you still can’t sign in, call our MyVA411 main information line at 800-698-2411 (TTY: 711) and select 0. We’re here 24 hours a day, 7 days a week.

This service is provided to you at no charge by VA.gov Office of the CTO._

Resources:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBclJaIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--86409dfc4ac2d1c4129b9df92bba4c142e87276f/GovDelivery_Footer.png)

**Comment by CarlDickerson** [comment]
Updated content recommendations: https://docs.google.com/document/d/1m-pHE5wjIypNAH26oSujEqJApg9JD6ouLeQoOvZ8Zps/edit
