### ISSUE TITLE
Analytics Implementation or QA Support for: Profile | Authenticated Menu 

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#64617]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

</div>
</details>

### Required
- **Is this request for **Google Analytics implementation** or **QA**?**

     - [x] Google Analytics implementation ([current dashboard needs updated tracking codes to show the proper items](https://analytics.google.com/analytics/web/#/dashboard/jTwco5hFRBmuXcjZN9YSPA/a50123418w177519031p176188361/))
     - [ ] QA

- **Who is this request for?**

slack:accountexp-authex
team: profile 
We're adding two links to the authenticated menu
    
    
- **Provide the link(s) for Google Analytics implementation or QA**
  
    - [Insert link(s)] < not sure i follow, this ticket IS the request for the implementation 
    
- **When is the launch date?**
    - ASAP whenever this is completed 

- **What interactions need to be tracked?** 
    

    

[In this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63413), we created the appropriate dashboard but now we need the naming conventions updated and new links incorporated.  We've expanded the items in the authenticated menu by adding  "dependents" and "letters" as seen in the screenshot below:
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/29bcc7c2-18de-4809-879c-d6afbdd5d7cb)

Any logged in user in staging can view this updated menu. 

- We need new tracking codes for those two new items 
- We need the following updated to read 'My HealtheVet' instead of just 'My Health':
     - Navigation - User - My Health = My Health

### Optional
- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - [Insert test user]

- **Any additional comments**

    - [Insert comments]

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by michelle-dooley** [comment]
@mtcA6 - thanks for your submission, we will get back to you with timing.

**Comment by jestutt** [comment]
@mtcA6  When I check today, the only drop-down link missing a data layer event is "My HealtheVet". 

The event should look like the ones in the below screenshot with the "nav-user-section" collecting "my-health" or "my-healthevet". 


![Screenshot 2023-09-12 at 12 03 42 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/141653184/f89d3a3e-e23c-438e-a82b-8136e2616260)
