### ISSUE TITLE
configure ICNs into DataDog

### ISSUE THREAD

**Issue by djmunoz1** [department-of-veterans-affairs/va.gov-team#64628]
As a data admin I need ICN data added to DataDog so that I can report out on unique auth totals inclusive of SiS/mobile.

AC:
- engage Core Identity on what's needed to add ICN tracking to database
- determine whether changes can be made by LGA
- discuss potential timing

DEF OF DONE:
- document next steps in GH and share with PM (Dawn + Lauren)

Bkgrd:
If ICNs are added, it would also allow us to report on our test groups users who use SiS/mobile. It could also support unique authn totals for SiS, assuming it's not already being tracked.

**Comment by djmunoz1** [comment]
@sdickson-gt pls add Core ticket number for adding ICNs

**Comment by sdickson-gt** [comment]
ICN is now available on SiS logs

**Comment by sdickson-gt** [comment]
And Joe reported that they just went live yesterday wiht reporting of SiS unique/distinct totals.  Totals start point forward as of yesterday.  https://vagov.ddog-gov.com/dashboard/e3q-6kp-9r4/vagov-identity-stats-public?from_ts=1693418119468&to_ts=1693504519468&live=false&tile_focus=4273687015088790

**Comment by sdickson-gt** [comment]
#1 is done.  See https://va-gov.domo.com/page/923236635 and https://vagov.ddog-gov.com/dashboard/8i9-sn7-9ap/logingov-adoption-test-groups?from_ts=1688518560000&to_ts=1693875360000&live=false

**Comment by sdickson-gt** [comment]
For number 2, we are already reporting monthly "unique" SiS/mobile totals on the Login.gov Adoption Dashboard.  I think Joe was just pointing me to another dashboard that focused on SiS, but has same numbers.
Also...I've had it in my head that "unique" authentications meant "distinct count of users". Now, I'm thinking it means total authentications. Checking that with Joe and if so, whether DataDog does currently capture metrics for distinct count of users who authenticated in a time period.

**Comment by djmunoz1** [comment]
Unique means what you're saying @sdickson-gt   it doesn't mean total. That total auth is like the turnstyle count that counts everybody that passes through the door, no matter how many times. VA (Chris) wants to be able to see data in terms of distinct users for this credential adoption work.
