### ISSUE TITLE
improve accuracy of correlation and reporting data

### ISSUE THREAD

**Issue by djmunoz1** [department-of-veterans-affairs/va.gov-team#64624]
As an admin I need authentication reporting data that is as wholistic and accurate as possible so that I can understand and monitor trends.

AC:
- test using DataDog instead of MPI to pull Veteran email lists (i.e. Veterans with DSL + ID.me

**Comment by sdickson-gt** [comment]
Authentication Reporting:
- Authentication reporting includes unique user authentications for each of the distinct SSO federations SSOe and SiS. Unique SiS authentications are available in DataDog, as of beginning of September. 
- Regarding missing credentials, DataDog data goes back 6 months versus 2 years for Splunk/SSOe, so SSOe was used.

Email Lists
- Our ability to pull accurate user segments (organic and reactivation) have been improved to address the data quality issues in the MPI dataset exports: lastUsed date and missing credentials relating to ID.me as MFA.  Note: A prior request to get emails from VA.gov (potentially DataDog) was redirected to MPI.
