### ISSUE TITLE
Flipper UI access for [Zac Yellowhorse]

### ISSUE THREAD

**Issue by zyellowhorse** [department-of-veterans-affairs/va.gov-team#64636]
### Your Name

Zac Yellowhorse

### Your GitHub handle (Flipper UI access is managed through GitHub)

zyellowhorse

### Team, Role, and Company of the target individual

Teams DBEx 2, Non-Disability Benefits Exp, Dependents Exp. DevOps Engineer from Oddball

### Please confirm if you are on the VFS Team Roster, Platform Team Roster or are a Federal User

- [X] [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [X] Lesser Environments (Dev/Staging/Sandbox)
- [X] Production (if requesting, justify prod access below)

### Reason for Production Access (If requested)

DevOps Engineer responsible for managing code deployed by Disability Benefits, Non-Disability Benefits, and Dependents Benefits teams.

**Comment by bdech** [comment]
Found in VFS Team Roster

**Comment by bdech** [comment]
Access granted to lower environments and prod.
