### ISSUE TITLE
Draft banner for VA.gov

### ISSUE THREAD

**Issue by djmunoz1** [department-of-veterans-affairs/va.gov-team#64634]
Problem:
With the upcoming changes to the sign-in methods on VA.gov, we need to give Veterans plenty of advance notice and information as we can. There are many places where we can advertise the changes, including an interstitial page. How might we craft the best message for Veterans? How might we take full advantage of all of the ways we can communicate the change so Veterans create their new Login.gov accounts well ahead of time?

The banner should let Veterans and VA.gov users know that a change is coming. It should offer a glimpse into what to expect and reasons for the change. 

User Story
As a Veteran, I need to be reminded of changes to signing into VA.gov on all VA.gov pages by means of a banner, so that I migrate to using modern credentials to access VA.gov

AC
- [ ] Content of banner is a 3-5 sentence message explaining what the change is to sign in and when it's happening
- [ ] Content of banner includes working hyperlinks to create or start using a new sign in as well as FAQ page
- [ ] Banner's design is compliant with VA.gov Design System
- [ ] Banner has been reviewed and approved by Sitewide

**Comment by SophiaPhilipMO** [comment]
See [alert and promo banner](https://www.figma.com/file/8vobVoSl1UqLnXsni3rcvO/Login.gov-Adoption%3A-Design-Flows?type=design&node-id=3148%3A493&mode=design&t=jcYFYEuUE4V02Prt-1) to review content

**Comment by SophiaPhilipMO** [comment]
@lmorris3 updated language and ready for review to demo
