### ISSUE TITLE
[FE] Add Spanish Translations

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#64635]
## Tasks
- [ ] Add the following translated SPANISH content to the appropriate json file     
      -  [Q1 2024 - SPA-FINAL_2024-03-27_15-14-51.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/15011623/Q1.2024.-.SPA-FINAL_2024-03-27_15-14-51.pdf)
      - **NOTE: numbers 122 - 126 were not in the product at the time the info was sent to the State Department, so, the keys may not be what they are in the product now**
- [ ] Generate SPANISH screenshots for workflow documents to submit to the State Department

**Comment by brianseek** [comment]
@loripusey This isn't merged yet, but here are screenshots. 
[spanish.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzU2QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ba68fae5762bb3e653d161cf5fd85a04251d6a4a/spanish.zip)
Also one of the translations was still in english. This one: 
```
"this-claim-is-for-your-appointment": "$t(this-claim-is-for-your-appointment-claims, {\"count\": {{claims}} }) for your $t(this-claim-is-for-your-appointment-appointments, {\"count\": {{appointments}} }) on {{date, long}} at"
```
Results in a weird bit of Spanglish:
<img width="201" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0I2QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--10b5815e363752dc471e47039e0839c93873c901/Travel-claim--multiple-facilities--Complete-spanish.png" alt="Travel-claim--multiple-facilities--Complete-spanish.png" />

**Comment by brianseek** [comment]
this is the branch if you wanted to peep this on local before its merged: `check-in/64635/spanish-translations`

**Comment by brianseek** [comment]
this branch is now merged and should be validate-able on local and stage + prod soon

**Comment by loripusey** [comment]
I found some inconsistencies. I'll put them in a separate comment per inconsistency.

Missing this: 1. "complete-pre-check-in": "Complete el registro previo a la llegada",

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/86678742/22cb412a-80a3-4856-8cb2-6dcb2f6d366a)

**Comment by loripusey** [comment]
Pre-Check-in - should be this: "remember-to-bring-your-insurance-cards-with-you": "Recuerde llevar consigo sus tarjetas de seguro. El día de la cita, le enviaremos un mensaje de texto cuando sea el momento de registrarse.",

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/86678742/f84f14f6-b543-48c4-b506-fd091d58608a)

**Comment by loripusey** [comment]
This should be: 123. "claim": "Reclamaciones"

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/86678742/cd9e1f7f-690b-4e94-a800-ec3b5374a155)

**Comment by loripusey** [comment]
Back should be: 104. "back": "Atrás",

Also, Continue seems to be wrong as well.   "continue": "Continuar",

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/86678742/f12f314c-0ba8-43f6-a495-dc71458521f1)

**Comment by loripusey** [comment]
No 5 seems like it's missing the last part:  5. "this-must-be-true-youre-traveling-for-care": "<0>La siguiente afirmación debe ser cierta:</0> Viaja para recibir cuidado en un centro de salud de VA o viaja para recibir cuidado aprobado por VA en un centro de salud que no es de VA en su comunidad. < 0> Además, al menos de una de las siguientes afirmaciones también debe ser verdadera:</ 0>

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/86678742/f0969dcc-a170-47de-ba7a-3021ef75bb57)

**Comment by brianseek** [comment]
- number one must have gotten mangled in my merge. (PR fix incoming)
- the next one is a feature flag issue, I've fixed that locally and will send a new screenshot
- the continue/back buttons will need to get translation updates from the DS team (how do we usually do that?)
- the `claims` one has the wrong key, i've updated that (PR fix incoming)
- the last one here is being caused by a mangled text string, i've also updated that (PR fix incoming)

**Comment by brianseek** [comment]
@loripusey updated screenshots [spanish-4-22.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3FDQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6e299dde799cfeaecf064aa3ce8950b88d10f91b/spanish-4-22.zip)

**Comment by brianseek** [comment]
updates are merged

**Comment by loripusey** [comment]
Everything looks good exception one thing that the State Department missed. I'm going to go ahead and use my college-level Spanish to predict what the changes are so we can get them a screenshot to QA.

This is the key:  75. "this-claim-is-for-your-appointment": "$t(this-claim-is-for-your-appointment-claims, {\"count\": {{claims}} }) for your $t(this-claim-is-for-your-appointment-appointments, {\"count\": {{appointments}} }) on {{date, long}} at",

**This is what it should be:** 75. "this-claim-is-for-your-appointment": "$t(this-claim-is-for-your-appointment-claims, {\"count\": {{claims}} }) por su $t(this-claim-is-for-your-appointment-appointments, {\"count\": {{appointments}} }) en {{date, long}} a",

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/86678742/f5782b1e-5179-4f41-879d-1b291c357b26)

If you can make this last change and merge it I can grab a screenshot and get this off to the State Department.

**Comment by brianseek** [comment]
@loripusey This PR is in and will get a review tomorrow. I also added a translation for "and" to complete the rest of this block of text.
<img width="240" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOENJQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--425f3b1fa1f87503c1654ee45fbe2ac8bdc7f4e1/localhost_3001_my-health_appointment-travel-claim_complete.png" alt="localhost_3001_my-health_appointment-travel-claim_complete.png" />

**Comment by loripusey** [comment]
Thank you, everything's been validated. I'll send the QA info to the State Department. Closing this ticket.
