### ISSUE TITLE
Research Domo opportunities to map Platform KPIs/OKRs

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#6463]
## User Story or Problem Statement
How might we determine how we can use Domo internally on Platform ?

## Goal
Determine a way we might (or might not) be able to use Domo to track our own OKRs.

## Acceptance Criteria
- [x] Team watches OKR demo recording
- [ ] Schedule & conduct team brainstorming session
- [ ] Follow up with Domo CSMs on how we can track these - without the alpha OKR test
- [ ] Write up for how we might or might not be able to use Domo for OKR tracking

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by joanneesteban** [comment]
## Insights Resources
For Discovery

- Our current [Google Sheets](https://docs.google.com/spreadsheets/d/1Kv91DobU2sl1Y-vzicfIDZg8MtiX254tcYPiwU6VkWA/edit#gid=247582808) team KPI & OKR tracker
    - This is connected in Domo as `VSP Analytics & Insights KPIs/OKRs Tracker`. It should update weekly on Sundays.
- VSP's [Google Sheets](https://docs.google.com/spreadsheets/d/16ad3HohYHv5Z22XAhlwatomQBsfRRsV0I5Q4z0qrEB0/edit#gid=1225616757) OKR tracker

**Comment by joanneesteban** [comment]
*To Do:* Add Domo demo video to sensitive repo & link back to this ticket.

**Comment by joanneesteban** [comment]
Added video to sensitive repo: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/teams/vsp/teams/insights-analytics

**Comment by joanneesteban** [comment]
## Brainstorm Notes

- How can we include some of the OKRs dashboard features into our KPI dashboards? i.e. the human factor of setting 'how it's going' on the KPI tracker. Is there a tracker that we have where users can keep track of their updates? (@amycesal follow up )
- We should do a write up of the OKR tracker that Domo demo'd. (@joanneesteban follow up. Escalate the trial.)
- What is the KPI card? (@jonwehausen follow up)

**Comment by joanneesteban** [comment]
Bring these insights into the discovery sprint.

**Comment by jonwehausen** [comment]
### Follow-up on KPI Card Research

- From my understanding, KPI cards are no different than the cards we have already been making use of -- In the words of DOMO: "_KPIs are packaged with their most important summary data into boxes called KPI Cards. However, most Domo users simply refer to these kinds of Cards as "Cards" without attaching the term "KPI."_". In other words, they're the smaller version of our existing cards. See resources and examples below: 
  > [Understanding KPI Cards](https://knowledge.domo.com/Welcome/Domo_User_Interface/03Understanding_Cards#Understanding_KPI_cards)
  > [KPI Card Best Practices](https://knowledge.domo.com/Training/Self-Service_Training/Best_Practices_Resource_Guide/Best_Practices_for_Creating_KPI_Cards)

![image](https://user-images.githubusercontent.com/48527022/76646720-df288900-6531-11ea-96b3-0dfbdbdf0f82.png)
 
-  If we don't care about presenting cards in this particular format, there's not much there for us to make use of

### Alternate Idea
- In terms of articulating KPIs within our dashboards and getting users involved with the tool itself - a [poll card](https://knowledge.domo.com/Visualize/Adding_Cards_to_Domo/Poll_Cards/Adding_a_Poll_Card_to_Domo) may help engage our users and help measure our progress. I imagine this could be simplified to a simple checkbox

**Comment by joanneesteban** [comment]
## Updates

- Sensitive repo has [Insights notes & recommendation](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/vsp/teams/insights-analytics/domo-okr-demo.md)

- @amycesal do you have a follow up for
> How can we include some of the OKRs dashboard features into our KPI dashboards? i.e. the human factor of setting 'how it's going' on the KPI tracker. Is there a tracker that we have where users can keep track of their updates?

**Comment by joanneesteban** [comment]
Work is being done to track Platform tool usage. Closing this ticket.
