### ISSUE TITLE
[Sprint Goal] In Person Proofing - Proofing Agent flow through ID validation (front-end)

### ISSUE THREAD

**Issue by porta-antiporta** [department-of-veterans-affairs/va.gov-team#64646]
# Scope

While our team understands what platform we will deploy our proofing agent application, we will build out the front end of the proofing agent process in similar vein to #63454

# Constraints / Decisions
- Demo'd locally
- Uses updated prototype (via Login.gov design system)
- Full navigation (continue and back)
- Responsive

# Demo
- Demo flow with 3 scenarios
- VHIC
- Hawaii DL
- <state> State ID
- Demo'd Local

**Comment by lmorris3** [comment]
Closing - all work in this epic is complete.
