### ISSUE TITLE
NOD | V2 Launch Monitor 

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#64642]
## How to use this ticket
This is a daily checklist for monitoring the health of our release. Tasks for this ticket should be completed first thing at the beginning of each day, and reported to the internal team and key stakeholders. Below are the metrics used to gauge the health of the release. See these links for details on the [release and rollback plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Notice-of-Disagreement/Product/NOD_V2_Release_Plan.md), and [incident monitoring plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Supplemental-Claims/engineering/Incident-Response-Plan.md).

### Step 1: Check the monitoring dashboards for release health

- [ ] Engineering: Post the FE and BE error metrics for the previous day, including the type of error and intervention needed.
- [ ] Product: Check Medallia feedback by submitting a [qualitative data request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jwoodman5%2C+ianMcCullough-ob&labels=VSP-contact-center%2Ccc-data-request&template=qualitative-data-request.yml&title=Qualitative+Data+Request)

#### Dashboards
[NOD Dashboard in DataDog](https://vagov.ddog-gov.com/dashboard/tvp-imf-tb7/benefits-notice-of-disagreement?refresh_mode=sliding&view=spans&from_ts=1707842761257&to_ts=1708447561257&live=true)
[Launch Monitoring (V1 v. V2)](https://vagov.ddog-gov.com/s/f327ad72-c02a-11ec-a50a-da7ad0900007/9uf-rzc-3s6). 
[NOD Domo Dashboard](https://va-gov.domo.com/page/447193050)

**Are users abandoning the form disproportionately between V1 and V2?**
- [Form completion - filter by funnel version](https://va-gov.domo.com/page/447193050)

**Is the error rate showing any spikes?**
- [NOD form submission error alert](https://vagov.ddog-gov.com/monitors/159230)
- [NOD/SC evidence submission error alert](https://vagov.ddog-gov.com/monitors/159449).

**Is the contestable issues endpoint working?**
- [NOD - Get Contestable Issues API traffic anomaly check](https://vagov.ddog-gov.com/monitors/172710?view=spans)
- [NOD - Get Contestable Issues - Error rate](https://vagov.ddog-gov.com/monitors/202306?view=spans)

**Is submission traffic proportionate to the typical submission rate on a given day?**
- [NOD - Overall Claim Submission traffic is low](https://vagov.ddog-gov.com/monitors/168196?view=spans)
- [NOD - Overall Claim Submission API traffic anomaly check](https://vagov.ddog-gov.com/monitors/172997?view=spans)
- [NOD - Overall Claim Submission - Errors](https://vagov.ddog-gov.com/monitors/165264?view=spans)
- [Traffic on NOD submission endpoint greater than or equal to 12 submissions / day](https://vagov.ddog-gov.com/monitors/159231).

**Is evidence submission proportionate to the typical submission rate on a given day?**
- [NOD/SC - Evidence Upload to Lighthouse - Permanent Errors](https://vagov.ddog-gov.com/monitors/168064?view=spans) 
- [NOD and SC Evidence traffic is low](https://vagov.ddog-gov.com/monitors/159450?view=spans)
- [NOD and SC Evidence traffic anomaly check](https://vagov.ddog-gov.com/monitors/169739?view=spans)
- [Traffic on NOD/SC evidence submission endpoint greater than or equal to 100 uploads / day](https://vagov.ddog-gov.com/monitors/159450).

**Do our evidence uploads match Lighthouse's count?**
- [NOD - Evidence Uploads to Lighthouse API traffic anomaly check](https://vagov.ddog-gov.com/monitors/173040?view=spans)
- [NOD - Evidence Upload to S3 API traffic anomaly check](https://vagov.ddog-gov.com/monitors/172998?view=spans) 

_Alerts will be automatically posted in the `#benefits-decision-reviews-notifications` Slack channel, and sent to team members via email. Eugene and Sade will be responsible for triaging these alerts daily._

## Step 3: Update the enablement team and LH Banana Peels team 
- [ ] Product: Craft an update with input from engineering, share with PO and LH Banana Peels team.
- [ ] Product: Check for opportunities to expedite the release.
- [ ] Product: Communicate any changes in the release plan to the stakeholders above and update the release plan.

## Step 4: Confirm when release period is officially closed 
- [ ] Product: At the end of the observation period, get buy-in from PO and LH Banana Peels team before increasing the release.

**Comment by saderagsdale** [comment]
- Robin and Rocio will conduct the canary. @Mottie 
- 25% increments, a few days apart

**Comment by saderagsdale** [comment]
Need to update logging links, KPIs @saderagsdale @data-doge

**Comment by saderagsdale** [comment]
Needs KPIs for NOD production validation. Devs will chat tomorrow.

**Comment by data-doge** [comment]
Note: The changes in V2 will only affect the submit action, which we are already monitoring and sending alerts for in our NOD dashboard. So we are all good to go for this ticket, once launched.

**Comment by saderagsdale** [comment]
@data-doge can you tag me when the KPIs we're monitoring for the release are listed and linked in the ticket?

**Comment by saderagsdale** [comment]
@data-doge just waiting for updated KPIs for this one.

**Comment by data-doge** [comment]
Sorry for the delay on this @saderagsdale - just updated KPIs in the PR description.

**Comment by saderagsdale** [comment]
Need to update the analytics for this. @saderagsdale will reach out to platform

**Comment by HeatherWidmont** [comment]
@data-doge to send another batch of UUIDs to Tim

**Comment by data-doge** [comment]
I'll send that batch of UUIDs to Tim tomorrow - ran out of time today

**Comment by saderagsdale** [comment]
Sade will add links from release plan draft.

**Comment by saderagsdale** [comment]
Eugene and Sade will update with new monitor links (as needed).

**Comment by saderagsdale** [comment]
Need to add S3 auditing for parity.

**Comment by data-doge** [comment]
@saderagsdale Made just one update to ticket desc:
> Traffic on NOD/SC evidence submission endpoint greater than or equal to ~150~ **100** uploads / day.  [Tracked via this DataDog alert](https://vagov.ddog-gov.com/monitors/159450).

Our monitor was too sensitive and was giving too many false positives, so I changed the evidence submission threshold to 100 / day.

**Comment by HeatherWidmont** [comment]
Dialed back down to 0% due to an issue on the LH side, may dial back up today. Just tested a fix from LH so we'll see what they say

**Comment by HeatherWidmont** [comment]
Back up to 25% as of yesterday afternoon, monitors look pretty good so far

**Comment by anniebtran** [comment]
Julie [gave us the OK](https://dsva.slack.com/archives/C5AGLBNRK/p1710527172825299?thread_ts=1710522048.572769&cid=C5AGLBNRK) to increase to 50% 🎉

**Comment by anniebtran** [comment]
Increased to 50% 👍

**Comment by HeatherWidmont** [comment]
At 100%, things are looking good
