### ISSUE TITLE
Iterate on Proofing agent process flow (Storyboard)

### ISSUE THREAD

**Issue by porta-antiporta** [department-of-veterans-affairs/va.gov-team#64649]
# Use Case

As a stakeholder, I want to understand the storyboard that my proofing agents will need to do, so I can detail the work to potential volunteers.

As a designer, I want to understand the steps a proofing agent must do, so that I can understand how to design those screens.

# Context

We have a high level flow diagram for proofing agent that was reviewed with VA POs, Login.gov, and NIST. There are quite a bit of steps to be covered in this part of the process as well as understanding when does a proofing agent do what, when exactly and knowing when to go to the proofing app vs. identity toolkit.

This story sets up the skeleton that will allow for higher fidelity mockups 

# Acceptance criteria

Storyboard that:
- [x] What is the starting point for the Proofing Agent?
- [x] Includes PIV authentication
- [x] Includes Resolution, Validation, Verification
- [x] Clearly calls out when proofing agent asserts a step has been completed
- [x] Distinction (in time) of when an event occurs on proofing app vs. identity toolkit

**Comment by skirkman16** [comment]
captured the details of the verifier flow in the verifier flow + sitemap [here](https://app.mural.co/t/innovationboards1199/m/innovationboards1199/1692994115776/5b6e2c85cd304e3d011dbddf2eec0bfe158f4ca8?sender=u99cd1ac4f5c240d8dffd4204)
