### ISSUE TITLE
Develop February & March Contact Center report

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#6464]
## User Story or Problem Statement
How might we show what users are calling in about for VA.gov?

## Goal
Create Feb and March Contact Center reports.

## Acceptance Criteria
- [x] Create Feb contact center report
- [x] Create March contact center report
- [x] Share out reports in #vfs-analytics
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by clantosswett** [comment]
Chante will complete any remaining February issues and then will set up time with Kimberley to train and complete February report. 

Kimberley will document report creation training and then use documentation to complete March report.

**Comment by Kimberley2019** [comment]
Once the March report is completed, it is my goal to meet with the rest of the Analytics team to see if any portion of the report can be automated in any way.  This will be a future Sprint objective.

**Comment by Kimberley2019** [comment]
February Report is complete.

**Comment by Kimberley2019** [comment]
March Report is complete.  Please see link below.

https://drive.google.com/file/d/162Cn_srmNNQ3d7X62HIOOTdVrm2HSwQN/view?usp=sharing

**Comment by Kimberley2019** [comment]
Shared on 5/4/2020.
