### ISSUE TITLE
High fidelity mockup - Proofing agent authentication

### ISSUE THREAD

**Issue by porta-antiporta** [department-of-veterans-affairs/va.gov-team#64650]
# Use Case

As a proofing agent I need to authenticate to the proofing app so that I validate that I can be a proofing agent

# Context

In #64649 we outlined the proofing agent flow. This story focuses on high fidelity mockup of the authentication.
Note that Login.gov already supports a method where the user is forced to authenticate with their PIV.

# Acceptance criteria

- [x] High fidelity mockup of authentication

**Comment by skirkman16** [comment]
It would be nice to have a visual of the screen where a user must use their PIV to sign in for presentation purposes. All screens (for veteran and PA) were taken to a high fidelity prototype this sprint.

**Comment by skirkman16** [comment]
Intake flow was updated alongside the proofing agent flow. prototype is [here](https://www.figma.com/proto/PfrWKmxiQ5RjChwx6I18QE/IPP-Prototypes?page-id=360%3A6586&type=design&node-id=381-19237&viewport=1049%2C-787%2C0.25&t=JF9dUs5VOQ848s2s-1&scaling=scale-down&starting-point-node-id=361%3A6914&mode=design) and screens are [here](https://www.figma.com/file/PfrWKmxiQ5RjChwx6I18QE/IPP-Prototypes?type=design&node-id=360%3A6586&mode=design&t=uQmFZvoCjxZuRH45-1)

**Comment by porta-antiporta** [comment]
@skirkman16 u can see the PIV only login screen if you select the `HSPD12 only` sign in option in the [sample app](https://int-identity-oidc-sinatra.app.cloud.gov/). Seems to have broken since yesterday so posted in the Login.gov shared DSVA slack channel on status. Once that's fixed you can grab a screenshot from there.

**Comment by porta-antiporta** [comment]
@skirkman16 it was a mistake on my part. the dev/integration environment at Login.gov is working fine. 
This will be a bit lengthy but here goes.  So an application can ask Login.gov to authenticate a user and that mandates that user present their PIV as part of that authentication.  Now, when the app (say like our proofing app) sends the user to Login.gov, they see the usual login screen where the user can sign in with _either_ their username/password or their PIV (`Sign in with government employee ID`):


<img width="629" alt="Screenshot 2023-09-26 at 2 20 41 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/16668007/10f96098-94ac-47e0-9bf1-cab74e7a3e54">


It's important to note that a PIV can be associated to at most 1 Login.gov account (in each environment int, prod, staging). So unlike a phone which can be the MFA for multiple Login.gov accounts, a PIV has a 1:1 association in an environment. i.e. I can use the same PIV to associate to a dev Login.gov account and a prod Login.gov account, but I can't use that same PIV to associated to 2 dev accounts.

`Sign in with government employee ID` will prompt the user to present their PIV and enter the PIN. This assumes the user has associated their PIV (i.e. configured it as an MFA) to their Login.gov account. If after entering the PIN, Login.gov detects the PIV has not been associated to an account, Login.gov will prompt them to create an account or log in using a different MFA at first, then associate the PIV.

Now if the user enters their username/password we have a couple scenarios, the user has a PIV associated to their Login.gov or they don't have a PIV associated to their Login.gov account. 

If they have a PIV associated, they will be prompted to present their PIV as their MFA and the screen looks like this:

![Screenshot 2023-09-22 at 1 45 50 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/16668007/2d668815-e4a2-45ca-88b0-72429c8841cf)

If they don't have a PIV associated, they will be asked to associate their PIV to their account after entering username, and that screen looks like this:

![Screenshot 2023-09-22 at 2 57 43 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/16668007/76172a0c-300b-48d6-9fe8-f9ee364c93ab)


So regardless of the path, to reach this point, the user has presented a PIV as part of logging into their Login.gov account. When doing so Login.gov extracts attributes the `x.509` certificate from the PIV and will send those back. The [x.509 subject](https://developers.login.gov/attributes/) has an attribute is unique to each federal employee / contractor. We'd have to see a sample response to confirm, but it is either the `x.509.subject.CNAME` (common name) or the distinguished name field. (I believe the distinguished name _includes_ the CNAME).  This is the unique identifier we can use to provision who is allowed to use the application or not. When a PIV expires for an employee and a new PIV is issued, this CNAME stays the same as it tracks to the unique individual.

**Comment by porta-antiporta** [comment]
@moanu404 @sdickson-gt (and rahul eventually) see ^^ when it comes time to managing access to specific PIV holders.
