### ISSUE TITLE
Sidekiq Admin UI access for Mark Chae

### ISSUE THREAD

**Issue by mchae-nava** [department-of-veterans-affairs/va.gov-team#64655]
### Your Name

Mark Chae

### Your GitHub handle (Sidekiq Admin UI access is managed through GitHub)

mchae-nava

### Your dsvagovcloud AWS user name (if applicable)

Mark.Chae

### Team, Role, and Company of the target individual

Disability Experience, Nava

### COR Name

Jennifer O'Day

### Please confirm if you are on the VFS Team Roster or Platform Team Roster

- [X] [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Sidekiq UI Access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### If PRODUCTION ACCESS is required, confirm/complete ONE of the following

- [ ] I have an AWS Username and it is listed in [here](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf)
- [X] I currently have access to vets-api Production Terminal via ArgoCD
- [ ] I've attached a screenshot of my E-QIP Transmittal Notice E-mail (Drag or Copy/Paste in Additional Notes Section below)

**Comment by bdech** [comment]
Found in VFS Roster

[E-QIP transmittal](https://github.com/department-of-veterans-affairs/va.gov-team/issues/57835)

**Comment by bdech** [comment]
@mchae-nava You've been granted access to all environments, with access to Production limited to 6 months, expiring, 02/29/24

**Comment by bdech** [comment]
Slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1693498982005279)

**Comment by mchae-nava** [comment]
@bdech Thank you!

**Comment by bdech** [comment]
@mchae-nava Your Sidekiq UI Production access has expired.

Would you like to request an extension? You have 72 hours to respond, or your 
access will be revoked and you will need to fill out a new request.

**Comment by bdech** [comment]
No response, production access revoked.
