### ISSUE TITLE
Update the Health Care Application (HCA) to use new endpoint behavior

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#6466]
We need to update the HCA's ConfirmationPage component to poll the new `GET /v0/health_care_applications/:id` endpoint to see if the submission has completed. We will also need to pass the new `async_all` param to the existing POST endpoint.

> Details of the backend changes are [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/5596#issuecomment-593573625).

The 526 form's [`ConfirmationPoll` component](https://github.com/department-of-veterans-affairs/vets-website/blob/8d728b44d48db4881fa47b984b49841b3ac3af7c/src/applications/disability-benefits/526EZ/components/ConfirmationPoll.jsx) could serve as a good example of a confirmation page that polls an async submission endpoint.

Also keep in mind we need to poll with the `data.id` we get back from the initial form submission. https://github.com/department-of-veterans-affairs/va.gov-team/issues/5596#issuecomment-594293098

**Comment by bradl3yC** [comment]
This is on hold until we can groom / discover further.

**Comment by Samara-Strauss** [comment]
On hold until we can get some design.

**Comment by mshea0606** [comment]
"success" = the application was sent to the service, doesn't mean it was approved
"failed" = means it wasn't sent
"pending" = when the submission is sent from the frontend to the backend it's pending,
while the backend waits for a response from the HCA API then it will change to either success or failed

**Comment by Samara-Strauss** [comment]
Is this work done? I know we don't have design for this work yet. Are you creating a new ticket to document what needs to happen after we have design?
