### ISSUE TITLE
Discovery: Linting Steps in CI are taking unusual amounts of time

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#64701]
# Description
We have seen linting steps in Vets Website CI taking ~10 minutes (previously 20-30) to complete. Linting should take seconds. We need to investigate the root cause of long-running linting steps in CI.

Since this ticket was originally created, it seems that linting has come back down to about 7 or 8 minutes to complete in a few workflows that I checked. This still seems a bit long. Let's dig into what is happening in the linting step and see if we can come up with a plan to get it back down to a minute or two.

# Acceptance Criteria
- [x] Research for the cause of the long-running linting step, and a recommendation for reducing the time it takes is available in a Confluence document in the PRT space linked to this ticket

**Comment by pjhill** [comment]
Linting is taking between 7 and 8 minutes in `main` at the moment. This is still fairly long, but it is down from 20 minutes. It's probably still worth investigating speeding up linting.

**Comment by ericboehs** [comment]
Might check if eslint is parallelizing and on a maximal size runner (e.g. 16 core).

**Comment by pjhill** [comment]
* 7m 35s linting -- https://github.com/department-of-veterans-affairs/vets-website/actions/runs/9405664936/job/25907371442
* 7m 32s linting -- https://github.com/department-of-veterans-affairs/vets-website/actions/runs/9404705838/job/25904201688
* 7m 32s linting -- https://github.com/department-of-veterans-affairs/vets-website/actions/runs/9390173585/job/25859379649

**Comment by pjhill** [comment]
Document created here as well as a proposed set of steps to attempt to improve performance.

https://vfs.atlassian.net/wiki/spaces/PRT/pages/3240427559/Linting+Discovery
