### ISSUE TITLE
AWS access for Evan Ubiera

### ISSUE THREAD

**Issue by eubiera** [department-of-veterans-affairs/va.gov-team#64715]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### E-QIP Transmittal Date

- [ ] Check this box if you have an E-QIP transmittal date.

### Your Name

Evan Ubiera

### Your Email

evan.ubiera@va.com

### Team, Role, and Company of the target individual

Developer

### Product Manager (PM) name and email

Alina Murphy, alina.murphy@va.gov

### Product Owner (PO) name and email

Luciana Morais, luciana.morais@va.gov

### Desired AWS Access

I need to renew my access to the AWS parameter store. I had credentials that seem to have expired. 

### Access Expiration

04-12-25

### E-QIP Transmittal Confirmation

<img width="701" alt="EQIP-confirmation" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/117054459/769b1c29-1e21-41bc-93a4-ae294ab76b22">

### Additional Notes

I work with the Virtual Agent/Chatbot team and need to edit and configure our parameter store as part of daily work. 

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by eubiera** [comment]
@Kshitiz-devops likewise, others on our team also have expired access.

Shall I use this ticket to request team-wide access? Id so, what do you need from us for that?

**Comment by BillChapmanUSDS** [comment]
@eubiera  an individual ticket should be filed for each individual request, these currently serve as our individual documentation. Extension approved as per current policy.

**Comment by eubiera** [comment]
Thanks @BillChapmanUSDS 
Should my previous credentials still aplly?

**Comment by ph-One** [comment]
I reached out and was able to restore access for @eubiera . @eubiera , please reopen and comment on this ticket and/or reach out to me if what you've been provided does not meet your required permission level.
