### ISSUE TITLE
Write an E2E test to confirm Find Forms search functionality

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#6473]
We need an E2E test written for our Find Forms search work so that we can confirm its functionality continues to work as the code base continues to change. An "E2E test" is a test that spawns a browser then automates the interaction with it, so that we can programmatically type input and click the search button. 

### Acceptance criteria
-  [ ] A dedicated E2E test for Find Forms search is executed during CI

**Comment by ncksllvn** [comment]
@AkucherGCIO I mentioned this work the other day - just wrote this issue for it

**Comment by MickinSahni** [comment]
2020-03-18 PW Standup
* Now that page is in prod, we can include in typical CI process to make sure it's looked at each time

**Comment by MickinSahni** [comment]
2020-03-20 PW Standup
- Postponing this ticket until new design is implemented (designs/ticket pending creation)

**Comment by MickinSahni** [comment]
Unblocked now as redesigns complete, moving into sprint 18

**Comment by MickinSahni** [comment]
2020-04-06 PW Standup
- PR merged
- Nick to drop in screenshot of CI running with new tests

**Comment by ncksllvn** [comment]
Screenshot from CI executing the test -

![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/a7599d6c-0e2d-4bb6-b554-1d043f26132d)
