### ISSUE TITLE
VAOS FE Generic Alert Message for Pending list - HSRM/VVS/VSP is down (Update)  

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#64770]
## Description
In production, the following systems that could potentially be down are VSP, VVS and/or HSRM. When any of the systems are  unavailable, the frontend will display a generic message to the user that their appointments may be unavailable to view.

The backend service is returning an error in the response body for VSP (sample below): 
```
"system": "VSP",
"status": "500",
"code": 10001,
"message": "Could not fetch appointments from Vista Scheduling Provider",
"detail": "icn=1013120820V528557, startDate=2023-01-08T00:00Z, endDate=2024-03-08T00:00Z"

```

This work will focus on the Pending list page. 

## Acceptance Criteria

- [ ] Given VSP system is down 
        When the user views their pending appointment 
        Then the application will display an alert message 
        And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/homepage.md) 

- [ ] Given VVS system is down 
        When the user views their pending appointment 
        Then the application will display an alert message 
        And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/homepage.md) 

- [ ] Given HSRM system is down 
        When the user views their pending appointment 
        Then the application will display an alert message 
        And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/homepage.md) 

- [ ] Given VSP and VVS systems are down 
        When the user views their pending appointment 
        Then the application will display an alert message 
        And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/homepage.md) 

- [ ] Given VSP and HSRM systems are down 
        When the user views their pending appointment 
        Then the application will display an alert message 
        And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/homepage.md) 

- [ ] Given VVS and HSRM systems are down 
        When the user views their pending appointment 
        Then the application will display an alert message 
        And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/homepage.md) 

- [ ] Given VSP, VVS and HSRM systems are down 
        When the user views their pending appointment 
        Then the application will display an alert message 
        And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/homepage.md) 

-----------

- [ ] Copy is changed in design spec
   - Old copy: We're working to resolve this issue.  To manage an appointment that is not shown in this list, contact the facility at which it was scheduled.
   - Updated copy: We're working to resolve this issue.  To manage an appointment request that is not shown in this list, contact the facility at which it was requested.
- [ ] Copydocs updated. 
### Example (mobile view)

Default view of the alert message: 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcUZoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3b85ad068ab2a0ba8f7c853b21e8e8d679c2eb60/Screenshot%202023-09-01%20at%2012.58.13%20PM.png)

User will click on the dropdown to expand the message: 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcUpoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--30c5134c9ea61440ac15e941769b3324a6216a4b/Screenshot%202023-09-01%20at%2012.58.21%20PM.png)

### Design Assets
[Figma File - Design Spec](https://www.figma.com/file/9ZOtrJqv7Ze4ptVHMtE1iJ/Alert-users-when-VAOS-can't-display-appointments?type=design&node-id=1009%3A61&mode=design&t=aBdjA0i9Jcaueo7M-1)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by ldelacosta** [comment]
@young1205 - please have @JRRoof and UX team validate this ticket when it's ready in staging. Thanks!

**Comment by jenniemc** [comment]
@ldelacosta, Just to to clarify that only requests cannot be fetched but appointments are fetch-able when error code 10001 is returned from the backend? I ask because this ticket only address pending appointments. There is not a ticket that addresses upcoming appointments in the ready queue so i'm assuming 10001 error only impacts requests.

**Comment by ldelacosta** [comment]
@jenniemc - we completed the work to update the upcoming list (here's the[ FE ticket](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/55068) for reference) @ryanshaw was the dev for the work. We can ask him to confirm. 

I'm assuming there's error code being returned from the BE for each status (Upcoming, Pending or Past).
