### ISSUE TITLE
[Other - Accessibility] Problematic pattern with disabled button. (00.00.2)

### ISSUE THREAD

**Issue by briandeconinck** [department-of-veterans-affairs/va.gov-team#64785]
#### VFS team name
Veteran Facing Forms

#### VFS product name
Form 21-0845 Authorization to Disclose Personal Information to Third Party

#### Point of Contact/Reviewers
Brian DeConinck - @briandeconinck - Accessibility

*For more information on how to interpret this ticket, please refer to the [Anatomy of a Staging Review issue ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Anatomy-of-a-Staging-Review-Issue-ticket.2060320997.html) guidance on Platform Website.

---

### Platform Issue
No VA.gov Experience Standard for the issue found.

### Issue Details
On [/authorization-to-disclose/disclosure-information-organization-representatives](https://staging.va.gov/authorization-to-disclose/disclosure-information-organization-representatives), after clicking "Add another representative" to add a second organization representative, the "Add a representative" button becomes disabled. Disabling buttons is problematic for accessibility -- they become difficult for low vision users to identify, they're removed from the tab order for keyboard users (which also makes them difficult to find for screen reader users), and they can be confusing for users with cognitive disabilities, since a disabled state alone doesn't communicate any information about why they're disabled. Once disabled, the button is followed by a "You’ve entered the maximum number of items allowed" message, but that message is likely to be missed by screen reader users since it's not in an `aria-live` region.

### Link, screenshot or steps to recreate

https://github.com/department-of-veterans-affairs/va.gov-team/assets/6844775/3f639ccb-aa59-4d29-9b07-ec9d1fd95aea

### VA.gov Experience Standard
[Category Number 00, Issue Number 00](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

### Platform Recommendation
I think this can be resolved by simplifying the interaction. My proposal:
- In the instructions, change "List one or more people from the organization who we can share your information with" to "List up to two people from the organization who we can share your information with." That indicates up front what the upper limit is.
- Change the button text to "Add a second representative." That reinforces the expectation that you're adding either one or two names and matches the behavior of the button since it can only be used to add one additional name.
- After the button is clicked, hide it or remove it from the DOM entirely rather than disabling it.
- Don't include the "You've entered the maximum number of items allowed" message at all. 

---

### VFS Guidance

- Close the ticket when the issue has been resolved or validated by your Product Owner
- If your team has additional questions or needs Platform help validating the issue, please comment on the ticket
- Some feedback provided may be out of scope for your iteration of the product, however, Platform's OCTO leadership has stated that all identified issues need to be documented and it is still your responsibility to resolve the issue.
- If you do not believe that this Staging Review issue ticket is the responsibility of your team, comment below providing an explanation and who you believe is responsible. Please tag the Point of Contact/Reviewers. Governance team will research and will follow up.

**Comment by tlei123** [comment]
We're replacing the list-n-loop with to 2 text-fields, via #644779.
