### ISSUE TITLE
Midpoint Review - Design Feedback - GI Bill Comparison Tool, Specialized Mission Filter

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#64798]
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- Matt is out today, our feedback will be in at EOD Tuesday or Wednesday so he has time to review.
- Love the presentation and clear filters!
- Be sure to test around what users think is supposed to happen with the search and apply filters buttons. Do they know they can click apply filters and it will search? Do they think they need to click both search and apply filters? Same questions for when they change the filters.
- On the results page, there are additional filters to the left in the first column. What happen if I change those and click update results? Do I need to click search or apply filters at the top? Test with users around those questions too. The filters on the top vs the left column feel very different from each other.
- After searching the results appear very far down the page. Test with users around if they see those results or if they prefer to see them further up the page.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

-

**Comment by humancompanion-usds** [comment]
### Accordion width issue
There is a bug here that should be addressed. The Accordion drawer face width is being overriden to fix the width of the button:
![Screenshot 2023-09-05 at 12 16 34 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/52176351/bf71ffff-46d8-4abb-86c5-4dc653f8054a)

![Screenshot 2023-09-05 at 12 17 20 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/52176351/b227a9eb-77d3-4c6a-8799-b5cbc044f71b)

That style is too broad and is applying to the button in Accordion as well. It should not.

### Text issue
Between the 480px and 1024px breakpoints the h1 and intro-text have no outer page gutter and run into the sides of the viewport.

### Filters not automatically applied
Ideally, pending a11y agreement, filters would be applied automatically. Having to click search again or apply filters is problematic. Having those button clicks/selection also trigger applying filters is fine, but ideally changes would reflect immediately. That's a common user expectation (i.e. [Jakob's Law](https://lawsofux.com/jakobs-law/)).

**Comment by arianaadili** [comment]
I'm closing this ticket now, as I realized I hadn't done so earlier. I've included a screenshot of the current production state, which addresses the concerns raised in this ticket.
![screencapture-va-gov-education-gi-bill-comparison-tool-2024-08-09-09_23_25](https://github.com/user-attachments/assets/883b0b2f-f2ab-4935-88af-8c90061fed92)
