### ISSUE TITLE
Qualitative Data Request - Homepage

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#64805]
### Data Type Requested

User Surveys

### Date Range Start

08-01-2023

### Date Range End

08-31-2023

### Product Name(s)

VAgov Homepage

### Product Description

VA.gov Homepage 

### Survey URL(s), key term(s), case category or type

www.va.gov/ (query parameters okay)

### File Delivery Format

All in one file, on one tab

### VA Email Address(es)

wesley.rowe@va.gov

### Add Assignee and Labels

If not already done so, please ensure @ianMcCullough-ob is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by newworld2616** [comment]
Hi @wesrowe. I have sent the requested data to you VA email. Please verify, if you received the file. Let me know if you have any questions. Thank you!

**Comment by wesrowe** [comment]
Received, thank you for the quick turnaround! By the way, I assume this is Sarifa – your github handle is pretty opaque. ;-)

**Comment by newworld2616** [comment]
Yes, it is :)
No problem at all.

**Comment by newworld2616** [comment]
Received!

**Comment by newworld2616** [comment]
Received!
