### ISSUE TITLE
Improve `remove_form_delimiters` function

### ISSUE THREAD

**Issue by kjsuarez** [department-of-veterans-affairs/va.gov-team#64808]
`fsr = Form5655Submission.find('08a07feb-5965-4652-a6b9-c3681446a56b')`

The above Prod submission demonstrates a hole in the `remove_form_delimiters` regex. Make the change necessary to catch the new line (\n) character present in this submission's form.

**Comment by HeatherRienks** [comment]
Per VBS/ VODA Sync on 9/1/23, we shared with the VBS team (Varun) that we would be making this code change and will notify the group once deployed.

**Comment by ScottyRJames** [comment]
Rolled over to S110 due to needing to test agains VBS API in lower environment and have their team confirm the change
