### ISSUE TITLE
After Visit Summary Link Unavailable - Past Appointment Details Page 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#64819]
## Description
We will need to notify the Veteran that the After Visit Summary link is not available when the appointment response is not returning the link to the frontend (UI) 

---

## Acceptance Criteria
Background: the `va_online_scheduling_after_visit_summary` toggle is on

Given the user is on the Past list
When the user clicks on the Details link and the response for the after visit summary link triggers an failure alert 
Then display the description notifying the Veteran that the After Visit Summary link is unavailable 
And page design matches the [design spec](https://www.figma.com/file/os1DFf0nwxBGnNt45ToeDD/Add-After-Visit-Summary-%7C-Appointments-FE?type=design&node-id=2012%3A35642&mode=design&t=pHGt62uQWnZlANJS-1)

### Technical Spec (vets-api) 
- [ ] vets-api will return a new `avsPath` field in the appointment response that will contain the AVS link
- [ ] if no AVS link is available, the `avsPath` field will be empty
- [ ] if an error response is received from AVS, then the `avsPath` field will contain the error detail

### Design Assets
[Design spec](https://www.figma.com/file/os1DFf0nwxBGnNt45ToeDD/Add-After-Visit-Summary-%7C-Appointments-FE?type=design&node-id=2012%3A35642&mode=design&t=pHGt62uQWnZlANJS-1)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by ldelacosta** [comment]
@young1205 - please have the UX team validate this ticket when it's ready cc: @JRRoof @outerpress

**Comment by simiadebowale** [comment]
@ldelacosta - Corey is working on creating a mock for one of Judy's past assignments so we can validate this

**Comment by ldelacosta** [comment]
Minor issue @Simi Adebowale. `Please update this text We're sorry. We've run into a problem.` to `We're sorry. We've run into a problem.`
<img width="1830" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzVKQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--77b8953e0687173204fad79365dbb71e32784a34/Screenshot%202024-02-09%20at%204.44.47%20PM.png" alt="Screenshot 2024-02-09 at 4.44.47 PM.png" />

**Comment by ldelacosta** [comment]
The changes look good. UX team - could you please double check and let me know if we're good to close. 

<img width="1551" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemhUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--572ae9052fb452395b336547a024fd24658caac7/Screenshot%202024-02-13%20at%208.48.12%20AM.png" alt="Screenshot 2024-02-13 at 8.48.12 AM.png" />

**Comment by melissa-lefevre** [comment]
Looks good. Thanks for catching the apostrophe @ldelacosta !

**Comment by Cieramaddox** [comment]
@melissa-lefevre The alert you're referring to is for when the entire details page cannot be retrieved. 

In terms of the red background color, you're right. We use they gray background [here](https://design.va.gov/components/alert#error-alert:~:text=to%20indicate%20success.-,Error%20alert,-View%20va%2Dalert) is the design system.

**Comment by simiadebowale** [comment]
Due to uswds change, alerts no longer have grey backgrounds. https://design.va.gov/storybook/?path=/docs/uswds-va-alert--default
cc: @melissa-lefevre @Cieramaddox

**Comment by Cieramaddox** [comment]
Thanks @simiadebowale I thought I saw that, but couldn't find it.

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket.
