### ISSUE TITLE
Vets-api terminal access for Maurice Okumu

### ISSUE THREAD

**Issue by Maurice-Okumu** [department-of-veterans-affairs/va.gov-team#64824]
### Your Name

Maurice Okumu

### Your GitHub handle (terminal access is managed through GitHub)

Maurice-Okumu

### Team, Role, and Company of the target individual

VA -Virtual Agent Chatbot Team, Developer, Thoughtworks

### Product Manager (PM) name and email

Zinal Patel, zinal.patel@thoughtworks.com

### Product Owner (PO) name and email

Nathalie Rayter , nathalie.rayter@va.gov

### COR Name (leave "None" if you listed an AWS user name above)

Cecila Lee

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

Liberty IT -  Michael G. Lovejoy

### Please confirm if you are on the VFS Team Roster or Platform Team Roster

- [X] [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Please confirm E-QIP Transmittal/Adjudication. This could be a screenshot of your Transmittal/Adjudication email, a link to another request where you've submitted this proof (i.e. AWS/SOCKS), etc.

- [X] I have attached proof that I have either transmitted my E-QIP survey or previously received a favorable decision (by including in "Additional Notes" section below)

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### Additional Notes

As a developer in the Chatbot team, given we have endpoints in the vets-api, I need ArgoCD terminal access
[EQIP Transmittal confirmation](https://user-images.githubusercontent.com/74667197/261336857-49b61989-b735-4baa-a499-d0b3d88258ef.png)

### Additional resources for Support Engineer

- [ ] For users on a VFS team but not in the VFS Team Roster, they must start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] Instructions for handling requests [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access) - Support Only

**Comment by bdech** [comment]
found in VFS Team Roster

**Comment by bdech** [comment]
@Maurice-Okumu You’ve been granted access to the 'dev', 'staging', and 'sandbox' environments.

Here's some additional documentation for the [Vets API on EKS](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-TerminalAccess)

Access to 'prod' is pending approval by OCTO. Can you please provide a description of your duties for access to production?

**Comment by Maurice-Okumu** [comment]
Good morning.
As a developer in the Chatbot team, I might need to test out the
Settings.YAML changes using the Rails Console.

**Comment by BillChapmanUSDS** [comment]
Access Approved as per current policy.

**Comment by bdech** [comment]
@Maurice-Okumu You've been given access to Production limited to 6 months, expiring 03/14/24. Please set a reminder for yourself to return to this Issue and re-request access within 1 week of the expiration date. You'll receive 1 reminder with a 72 hour window to respond. Failure to do so will result in lost access and will require you to fill out a new request.

**Comment by bdech** [comment]
Slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1694721394439909)

**Comment by Maurice-Okumu** [comment]
Thank you

**Comment by bdech** [comment]
@Maurice-Okumu Your Vets API Terminal Production access has expired.

Would you like to request an extension? You have 72 hours to respond, or your 
access will be revoked and you will need to fill out a new request.

**Comment by bdech** [comment]
no response, production access revoked.
