### ISSUE TITLE
[UX][Design] DS v3 #3: Update slim alerts to v3 in Production pages

### ISSUE THREAD

**Issue by cgednalske** [department-of-veterans-affairs/va.gov-team#64829]
## Tasks

- [ ] Update slim alerts to v3 in Production pages

## AC

- [ ] Alerts are updated in Production Sketch pages

**Comment by loripusey** [comment]
[Design System bugs](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues?q=is%3Aissue+is%3Aopen+label%3Acomponent-bug-v3)

**Comment by ytsaoca** [comment]
After talked to @benbrasso-agile6  and @cgednalske , we decided to put this ticket back to Backlog and wait for platform team tell us that we need to switch.

**Comment by benbrasso-agile6** [comment]
We're going to create another DS v3 component ticket to work on

**Comment by cgednalske** [comment]
Two more DS v3 component tickets (split in case mutliple people work on them):

[Additional info component](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65566)
[Buttons](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65567)

**Comment by loripusey** [comment]
As of 9/26/23, we need to wait for platform team tell us that we need to switch.

**Comment by benbrasso-agile6** [comment]
@loripusey this one is good to go

**Comment by benbrasso-agile6** [comment]
validated
