### ISSUE TITLE
Incorrect heading level for spotlight section on health services page

### ISSUE THREAD

**Issue by CherylEvans** [department-of-veterans-affairs/va.gov-team#64838]

**Comment by CherylEvans** [comment]
This ticket was recreated from VAMC Facility Accessibility Audit EPIC 12060 - department-of-veterans-affairs/va.gov-cms#12060VAMC Facility Accessibility Audit Ticket # [12080](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/gh/department-of-veterans-affairs/va.gov-cms/12080)

**Comment by laflannery** [comment]
Wouldn't this be a duplicate of the issue already created in the team repo here? [#64420](https://github.com/department-of-veterans-affairs/va.gov-team/issues/64420)

**Comment by CherylEvans** [comment]
@laflannery This ticket was recreated in error. Reference Ticket [64420](https://app.zenhub.com/workspaces/department-of-veterans-affairsvagov-team-62447fb44deeed001392c57f/issues/gh/department-of-veterans-affairs/va.gov-team/64420) as the correct ticket. Closing as a duplicate of 64420.
