### ISSUE TITLE
VAMC Directions links SHOULD include sr-only text to indicate specific location

### ISSUE THREAD

**Issue by CherylEvans** [department-of-veterans-affairs/va.gov-team#64844]

**Comment by CherylEvans** [comment]
This ticket was recreated from VAMC Facility Accessibility Audit EPIC 12060 - department-of-veterans-affairs/va.gov-cms#12060VAMC Facility Accessibility Audit Ticket # [12085](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/gh/department-of-veterans-affairs/va.gov-cms/12085)

**Comment by laflannery** [comment]
Closed because the linked ticket was resolved and completed on 7/18
