### ISSUE TITLE
[Components and pattern standards] Design components or patterns don't align with Design System guidelines. (04.07.02)

### ISSUE THREAD

**Issue by CherylEvans** [department-of-veterans-affairs/va.gov-team#64842]

**Comment by CherylEvans** [comment]
This ticket was recreated from VAMC Facility Accessibility Audit EPIC 12060 - department-of-veterans-affairs/va.gov-cms#12060VAMC Facility Accessibility Audit Ticket # [12088](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/gh/department-of-veterans-affairs/va.gov-cms/12088)

**Comment by laflannery** [comment]
Closing because the related ticket is closed and we are now using the v3 pagination component
