### ISSUE TITLE
Remove white space within visual focus indicator on Operating Status

### ISSUE THREAD

**Issue by CherylEvans** [department-of-veterans-affairs/va.gov-team#64851]

**Comment by CherylEvans** [comment]
This ticket was recreated from VAMC Facility Accessibility Audit EPIC 12060 - department-of-veterans-affairs/va.gov-cms#12060VAMC Facility Accessibility Audit Ticket # [12023](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/gh/department-of-veterans-affairs/va.gov-cms/12023)

**Comment by laflannery** [comment]
Closing this ticket because the linked ticket was resolved and closed on 12/29/2022.
