### ISSUE TITLE
[Internal testing] Test EKS 1.27 internally on our new clusters

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#64869]
## Description
We would like to test EKS 1.27 on our new clusters to see what is breaking

## Resources 
- Artifacts - i.e., issues, documentation, code, etc. - that help explain what's needed to work on this issue

## Acceptance Criteria
- [ ] EKS is upgraded to 1.27
- [ ] results are documented
- [ ] stories are created to address issues

## Refinement Guidance - Check the following before working on this issue: 
- [ ] _Team label assigned ("platform-tech-team-2")_
- [ ] _Epic assigned (if needed)_ 
- [ ] _Estimated (points assigned)_
- [ ] _Sprint assigned (once planned)_
- [ ] _Team member(s) assigned_
- [ ] _Understands how this work aligns with the overall platform_

**Comment by ph-One** [comment]
Performing rough testing of some Vets API manifests from their helm chart. I've submitted a PR for getting their HPA into a state that is compatible with both current (1.23) and new (1.27) versions of EKS.

**Comment by npeterson54** [comment]
Moving out of sprinti due to AL1 priorities

**Comment by ph-One** [comment]
Vets API is currently running on 1.28. We are working through IAM, but otherwise looks good. Closing.
