### ISSUE TITLE
Update the Start Scheduling button to an action link 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#64864]
## Description
We are looking to improve the user experience in the application. We are trying to see which action type is used more or preferred by the Veteran. We will update the button to an action link for the `Start scheduling` workflow. 

**Current design:** 
<img width="227" alt="Screenshot 2023-09-05 at 11 46 32 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/90797205/c1263bb7-44f5-4421-8e08-c9ea7aa45dbc">

---

## Acceptance Criteria
Background: the `va_online_scheduling_start_scheduling_link` toggle is on

Given the user is authenticated to the Appointments tool 
When the user lands on the Appointments landing page
Then the user will see the updated link to `Start scheduling` workflow
And page design matches the [design spec](https://www.figma.com/file/FkNvnuYunT4tyAzQnCNM6l/Start-Scheduling-CTA?type=design&node-id=1522-22348&mode=design&t=LjpGGAGpkiGNXhFl-0)

Given the user is authenticated to the Appointments tool 
When the user lands on the Appointment landing page and clicks on the `Start scheduling` link
Then an event will trigger `vaos-start-scheduling-link` in UA (Universal Analytics) 

_note:_ a separate ticket will be created for GA4 migration (Ticket #63341)

### Design Assets
[Figma file](https://www.figma.com/file/FkNvnuYunT4tyAzQnCNM6l/Start-Scheduling-CTA?type=design&node-id=1522-22348&mode=design&t=LjpGGAGpkiGNXhFl-0)

<img width="226" alt="Screenshot 2023-09-05 at 11 46 23 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/90797205/7de18921-cffb-46d6-8631-2e0963efc860">

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by ldelacosta** [comment]
@young1205 - when this is ready in staging, please notify @JRRoof and UX team to validate the changes. 

Deployment plan: Once the changes are good and ready to be launched, Jeff will turn the toggle on to 50% users. We will compare the usage of the button vs. link.

**Comment by Cieramaddox** [comment]
Need the action link toggle turned on in order to validate

**Comment by Cieramaddox** [comment]
This has been validated by the UX team
