### ISSUE TITLE
Identity Curriculum Initial Draft

### ISSUE THREAD

**Issue by porta-antiporta** [department-of-veterans-affairs/va.gov-team#64877]
Context:
As a support service for Veterans, there should be a resource available to support staff to understand the context and implementation of Identity and Identity Toolkit.

Acceptability Criteria: 
- [x] Update transcript from Identity Lecture and include Granicus and GovDelivery info
- [x] Porta addresses clarifying comments
- [x] Create Mural modeling curriculum format 
- [x] Porta and Phil meet on Friday, 9/8 to review and update Mural in preparation for Identity workshop

Definition of Done:
Transcript reflects complete content to be covered in curriculum and includes labeled sections to build out content. 
Mural version of transcript that is reviewed and edited for workshop presentation

**Comment by SophiaPhilipMO** [comment]
Schedule weekly cadence moving forward
