### ISSUE TITLE
[CST] Update claim details breadcrumbs

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#64883]
## Background
In order to make the claim details pages more accessible, we should update the breadcrumbs to specify which page the user is currently on

## Context
New breadcrumbs should read:
* Status of compensation claim
* Files for compensation claim
* Overview of compensation claim

## Tasks
- [ ] Update breadcrumbs to match the pattern specified above

## Acceptance Criteria
- [ ] The breadcrumbs on the claim details pages indicate which of the tabs the Veteran is currently on

**Comment by HeatherWidmont** [comment]
@jerekshoe are we good to close this?
