### ISSUE TITLE
Prevent closed claims with documents needed from bubbling up

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#64880]
It was discovered (in staging at least) that claims that are complete my still have the `documentsNeeded` flag set to true. If this is the case, it means closed claims bubble up to the top of the list among other, open claims that truly do need more evidence.

**Comment by HeatherWidmont** [comment]
@kjduensing will come back & fix this, but its not a major priority right now (he's currently working on sprint goals)
