### ISSUE TITLE
[FE] [BE] Design Implementation for Displaying List of Appointments

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#64893]
## Implementation Resources
Link to the [Slack thread](https://dsva.slack.com/archives/C022AC2STBM/p1692893127087559) with mobile oath, client registration, and MAP VAOS service instructions

## Tasks
- Read & become familiar with the documentation above
- Design Implementation for this Epic, including
    - Create authentication service to get token
        - Meet with the MAP folks however many times is necessary to design the implementation 
    - Use token to initiate data (hopefully works first time)
    - Make sure we’re not storing secret data
    - Implement design (etc etc etc)
    - Pull list of appointments
    - Display list of appointments

**Comment by brianseek** [comment]
updated doc: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/decisions/all-appointments-fetch.md

**Comment by brianseek** [comment]
Stephen gave an update that things are moving behind the scenes and is going to update us soon.

**Comment by loripusey** [comment]
@brianseek is this ticket done? can we close it?
