### ISSUE TITLE
Slack profile fields

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#64895]
### Description
"What I do" is no longer the name of the field. It is now called, "Title"

<img width="353" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/71330581/6fef97a3-3e53-4b59-a101-07ce994d6788">

### Relevant URLs

https://depo-platform-documentation.scrollhelp.site/getting-started/slack-profile

### Which type of team are you on? (Platform team, VFS team, or Leadership)
Platform Governance

**Comment by vbellissimo** [comment]
Thanks @shiragoodman 

cc @naomimarcussen, making this content update, FYI.

**Comment by naomimarcussen** [comment]
Nice catch @shiragoodman!
