### ISSUE TITLE
Create document for MHV login option changes

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#64904]
MHV is going to remove option 2 and 3 from their website in December. We need to writeup a document which describes the implications of this occurring.

**Comment by aparsley** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcGRzIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e173c6cabf74136b5e0e0d7b832ab0b60ff6fc44/Screenshot%202023-09-05%20at%201.29.24%20PM.png)



https://www.myhealth.va.gov/mhv-portal-web/web/myhealthevet/user-login?redirect=/mhv-portal-web/web/myhealthevet/home

**Comment by APorter-Clarity** [comment]
@joeniquette needs more context. Lets talk about in refinement

**Comment by parkerbees** [comment]
This is no longer relevant with MHV deprecation now officially coming; closing as cancelled.
