### ISSUE TITLE
[FE] Enable Travel for all Wilkes-Barre Facilities

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#64900]
## Locations
[Wilkes-Barre locations](https://www.va.gov/wilkes-barre-health-care/locations/)
https://veteran.apps.va.gov/facilities/v2/facilities/693/clinics

## Tasks
- Verify with Mark how to identify all Wilkes-Barre facilities
- Enable Travel for all Wilkes-Barre Facilities

**Comment by brianseek** [comment]
update is merged
