### ISSUE TITLE
[CRITICAL - Null Claim ] - Update 674 Submission Logic

### ISSUE THREAD

**Issue by tblackwe** [department-of-veterans-affairs/va.gov-team#64918]
Given a Veteran submits a claim
When it is ONLY a 674 submission
Then we should execute the Submit674 logic without Submit686C

It was discovered that in the case that a Veteran only selects the option 'Add a child 18 to 23 years old who’ll be attending school (VA Form 21-674)' , then no 686 EP is created and only a PDF is uploaded. There is an alert to the Veteran that says in some cases they should also 'Add a child or children under 18 and unmarries' but the majority of claims are submitted as 674 only.
As of 2023-09-03 111k 674 claims have been submitted, with 86k being 674 only (no other changes) 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa3B0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f93bee93f348a21b6c0c111bf8071c5f6e4251be/image.png)

The code has a conditional to prevent 686 EP submissions if the claim is only for 674. However, the 674 submission process is nested inside of 686, so this results in no claim being submitted. A PDF is submitted but no EP is created to support it.

We will update our logic to submit 674 individually when it is the only form. I expect 2 downstream effects from this change

1. An ~75% increase in the number of 674 claims being submitted. All 674 claims are currently set to be manually processed by VSRs. 
2. VSRs will not have all the information needed if a Veteran submits a 674 for a dependent that was never added through 686C

**Comment by evansmith** [comment]
This is merged into master and has been tested and verified on staging. Screenshot showing an independent 674 submission and a 686c-674 submission. 
![Screenshot 2023-09-07 at 4 12 43 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/1820743/2bb0aee4-5661-4406-8310-97ebec4d7e1f)
