### ISSUE TITLE
Midpoint Review - Content Feedback - Benefits Management Tools, Claim Status Tool, Improve Evidence Request/Submission Experience

### ISSUE THREAD

**Issue by CherylEvans** [department-of-veterans-affairs/va.gov-team#64919]
## VFS actions
- [x] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [x] Comment on this ticket:
  - [x] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [x] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [x] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [x] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- I recommend working with Sitewide CAIA to refine your content. All feedback applies to Mobile and Desktop versions.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

### Must

- dld-m1 copy 6 -> It looks like there are multiple fonts used for text -> they should be the same for the text under the headings.
- dld-m1 copy 6 -> The guidelines for uploading a file might confuse the non-tech savvy user.
- dld-m1 copy 4 -> What we're doing section uses "sighted" language.
- dld-m1 copy 4 -> Typo misspelling of "elegible." Should be "eligible."

### Should

- dld-m1 copy 9 -> Request for Buddy Statement -> There is a lot of user guidance buried in the content -> This is a lot of text (guidance) for the user to absorb and follow. I recommend breaking this up into a bulleted list.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBamh0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b76f759a011869d21126a450f40b69b559f31d5f/58828_Cheryl_1_Break%20up%20instructional%20text_Screenshot%202023-09-05%20at%201.20.43%20PM.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBanB0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5c01206909085538954e720ac3ed39077e94a9b8/58828_Cheryl_1_Different%20fonts%20and%20confusing%20upload%20instructions_Screenshot%202023-09-05%20at%2012.32.58%20PM.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBanh0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5fb1fdc8fdb8b63ddcc5842324e653db3a678426/58828_Cheryl_1_Sighted%20language_Screenshot%202023-09-05%20at%2012.30.13%20PM.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBajF0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3b37d99ab001f60a27cd405cfa466031b75a9627/58828_Cheryl_1_TYPO%20Spelling_Screenshot%202023-09-05%20at%2012.25.49%20PM.png)

**Comment by skylerschain** [comment]
@CherylEvans Is there a recommended replacement for the sighted language? We have two examples in the design: 

"View overview of the process"
"View details" (on claim card)

**Comment by CherylEvans** [comment]
@skylerschain I recommend consulting with CAIA for different "sighted-language" option alternatives.

**Comment by skylerschain** [comment]
Ok will do - I am looking to schedule a final content review with them so I will note that as one of the things to discuss. 

The rest of the "must" feedback should be addressed - latest spec is [here](https://www.sketch.com/s/98e35645-34eb-40cf-80c1-6c4952943584/p/B9C46ABC-36AD-4CA8-9896-55762FC6912E/canvas#Version) – so I'm going to close this ticket.
