### ISSUE TITLE
[FE]: 10-10EZ: Fix typo on confirmation page

### ISSUE THREAD

**Issue by davidakennedy** [department-of-veterans-affairs/va.gov-team#64937]
## Description
During usability testing of the new Household section, a veteran noticed a typo on the confirmation page. The first sentence under "What to do if you have questions now" says "If we haven't contact you within a week...". It should read "If we haven't contacted you within a week..."

## Screenshot(s)
![Screenshot 2023-09-06 at 1 14 19 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/6738544/de15eaea-f8f7-4187-bf4d-2b2b7bfec3f7)

## Tasks
- [x] Update copy to correct typo
- [ ] Validate with Design/PM once corrected

## Acceptance Criteria
- Information sentences flow correctly and are free of typos

**Comment by longmd** [comment]
@hdjustice / @davidakennedy , here is a screenshot of the updated text copy.

<img width="420" alt="Screenshot 2023-09-07 at 2 47 50 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/6738544/b308f9b6-8583-490c-895d-bfdacec37a26">

**Comment by hdjustice** [comment]
Fabulous!  Thanks @longmd
