### ISSUE TITLE
Midpoint Review - IA Feedback - Benefits Management Tools, Claim Status Tool, Improve Evidence Request/Submission Experience

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#64935]
## VFS actions
- [x] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [x] Comment on this ticket:
  - [x] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- Thanks for bringing this through the Collab Cycle! 

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- **Must**: Doublecheck and/or consider user testing the breadcrumbs. Questions I have: is there an intermediary view between "Check your claims and appeals" and "Status" or "Files"? And, does the current breadcrumb accurately represent the page? Our standard is to match the page's H1, current breadcrumb, and first part of the page `<title>` that appears before the "| Veterans Affairs". These will need to align to pass staging review.
- **Must**: Because the link to "How to file a Claim" from the [Buddy Statement submission page](https://www.sketch.com/s/98e35645-34eb-40cf-80c1-6c4952943584/a/1VLZban) could interrupt the user flow, it should open in a new window, per [feedback from Sara from the Design Intent](https://github.com/department-of-veterans-affairs/va.gov-team/issues/61562).
- **Should**: On the wireframe for [dld-m1 copy 8](https://www.sketch.com/s/98e35645-34eb-40cf-80c1-6c4952943584/a/RydnP5x) the CTA within the alert box should use active language. Within this alert container we should be directing folks to take corrective action. So the CTA there might be something like "Submit Buddy Statement". For other CTAs I +1 @CherylEvans's feedback to avoid use of sighted language where possible.

**Comment by skylerschain** [comment]
Hey @erinrwhite thanks for the feedback.

1. For the breadcrumbs, the goal is to align the breadcrumb for Status | Files | Overview with the unique content of each of those tabs. The H2 is what is changing in these cases, not the H1. The breadcrumb will match the first part of the page title as you mention. You can see more detail on that in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/61696).
2. I'll make sure to specify with engineering that the link should open in a new tab. We removed the icon because I was told it wasn't necessary/preferred to do that. I believe that was the a11y perspective, although I could be wrong. I can add it back in – just let me know.

**Comment by erinrwhite** [comment]
@skylerschain 

1. **Breadcrumbs:** Thank you for the link to the CAIA ticket! This is helpful background for me. I see that [you noted there are some technical constraints](https://github.com/department-of-veterans-affairs/va.gov-team/issues/61696#issuecomment-1724031027) on what this breadcrumb can be. If possible please liaise with @kristinoletmuskat for a followup as I know y'all have discussed page title and breadcrumbs in detail. Ideal scenario, those breadcrumbs are a little bit more descriptive than "Status" "Files" "Overview" despite the limitations.

2. **New tab indicator:** This is one of several instances recently that's signaled to me that we could stand to clarify our guidance on indicators for links that open in new windows/tabs. The design system guidance [notes when links should open in new tabs/windows](https://design.va.gov/components/link/#behavior) but not **how** that behavior should be communicated to users. Though we don't have specific guidance now, I recommend using the new window icon alongside a screen reader announcement that the link opens in a new window, which is the approach other teams have been using. Thanks for staying in conversation with us about this! Paging @briandeconinck as we have talked about this a bit and he likely has more to say.

**Comment by skylerschain** [comment]
Thanks Erin. 

1. I'll chat with Kristin about the breadcrumbs one last time before we ship this to see if there's something more descriptive we can say for breadcrumbs.
2. I'll add the icon back to this link to show that it will open in a new tab. 

I'll leave this ticket open for a couple days in case @briandeconinck has any additional thoughts and then will close.
