### ISSUE TITLE
[FE] Fix and improve cypress test for next of kin additional info

### ISSUE THREAD

**Issue by wullaski** [department-of-veterans-affairs/va.gov-team#64962]
- [ ] Add a cypress test for day of next of kin additional information
- [ ] Fix and improve cypress tests for additional information on pre-check-in

This should use the `NextOfKin.openAdditionalInfo` method first
```
    it('Displays additional info', () => {
      NextOfKin.validateAdditionalInfo.dayOf();
      cy.injectAxeThenAxeCheck();
    });
```
There's a few problems with this:
- dayOf is being used for a pre-check-in test but it has the correct text for it to pass
- dayOf should have the correct text
- There should be a test for dayOf
- use the preCheckIn method for the existing pre check in test
- both of these should use `is.visible` and `contain.text`
```
 validateAdditionalInfo = {
    dayOf: () => {
      cy.get('div[data-testid="additional-info"]').should(
        'contain.text',
        'If this isn’t your correct information, select No and a staff member can help you update your information on the day of your appointment.',
      );
    },
    preCheckIn: () => {
      cy.get('div[data-testid="additional-info"]').should(
        'contain.text',
        'If this isn’t your correct information, select No and a staff member can help you update your information on the day of your appointment.',
      );
    },
  };
```

**Comment by loripusey** [comment]
@wullaski can you point this before planning today?

**Comment by wullaski** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/64962?planning-poker) with Zenhub @brianseek @lee-delarm6
