### ISSUE TITLE
Vets-api terminal access for Kevin Duensing

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#64999]
### Your Name

Kevin Duensing

### Your GitHub handle (terminal access is managed through GitHub)

@kjduensing

### Your dsvagovcloud AWS user name (if applicable)

Kevin.Duensing

### Team, Role, and Company of the target individual

Benefits Management Tools, Fullstack SWE, Ad Hoc LLC/Coforma

### Product Manager (PM) name and email

Jacob Worrell, jacob.worrell@adhocteam.us

### Product Owner (PO) name and email

Emily Theis, emily.theis@va.gov

### COR Name (leave "None" if you listed an AWS user name above)

None

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

None

### Please confirm if you are on the VFS Team Roster or Platform Team Roster

- [X] [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Please confirm E-QIP Transmittal/Adjudication. This could be a screenshot of your Transmittal/Adjudication email, a link to another request where you've submitted this proof (i.e. AWS/SOCKS), etc.

- [X] I have attached proof that I have either transmitted my E-QIP survey or previously received a favorable decision (by including in "Additional Notes" section below)

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [ ] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### Additional Notes

**Adjudication proof**: <img width="1443" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/462039/30d05256-b6a9-4f54-a49a-e1ce27ca0f73">

**Prod access justification**: 
A service we work with only accepts user ICNs. We only log user UUIDs. To be able to debug an issue effectively, I need prod access in order to get the ICNs associated with some users for which I only have the user UUID. With ICNs now being considered PII, it is inappropriate for me to simply log the the users' ICNs.

Thank you

### Additional resources for Support Engineer

- [ ] For users on a VFS team but not in the VFS Team Roster, they must start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] Instructions for handling requests [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access) - Support Only

**Comment by bdech** [comment]
Found in VFS Team Roster

**Comment by bdech** [comment]
@BillChapmanUSDS for visibility

**Comment by BillChapmanUSDS** [comment]
Access approved as per current policy.

**Comment by bdech** [comment]
Youve been granted access to `Production` limited to 6 months, expiring 03/14/24. Please set a reminder for yourself to return to this Issue and re-request access within 1 week of the expiration date. You'll receive 1 reminder with a 72 hour window to respond. Failure to do so will result in lost access and will require you to fill out a new request.

**Comment by bdech** [comment]
Slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1694720694959629)

**Comment by bdech** [comment]
@kjduensing Your Vets API Terminal Production access has expired.

Would you like to request an extension? You have 72 hours to respond, or your 
access will be revoked and you will need to fill out a new request.

**Comment by bdech** [comment]
no response, production access revoked.
