### ISSUE TITLE
BE | Profile | Contact Information | Discovery: Investigate 6-line Address Issue

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#65004]
## Background
VA.gov interfaces with a system called SHARE that's limited to a 6-line address, so it will take a lengthy foreign address from VA.gov profile and shorten it to 6 lines, which breaks the integrity of the address.

See thread for more details:
https://dsva.slack.com/archives/C909ZG2BB/p1694011940734879

## Tasks
- [ ] Investigate VA Profile address validation API to find any rules related to this issue.

**Comment by tpharrison** [comment]
@mtcA6 I don't see any rules related to 6-line addresses, but I'm also not sure what is meant by "6-line".  Does this mean "6 fields" - in other words, there are only 6 fields available for storing an address?

The VA Profile API accepts over 30 different fields when adding or updating addresses.  Here are some of the fields related to an address:
- addressLine1
- addressLine2
- addressLine3
- cityName
- stateCode
- zipCode5
- zipCode4
- county
- provinceName
- intPostalCode
- countryName

Let's discuss to make sure we're on the same page.

**Comment by mtcA6** [comment]
I think it's the character length 

6x20
https://dsva.slack.com/archives/C0NGDDXME/p1694453008795499?thread_ts=1692372658.738959&cid=C0NGDDXME

**Comment by mtcA6** [comment]
@tpharrison mentioned you on that slack thread and sent a request for more info

**Comment by mtcA6** [comment]
There hasn't been movement. I'm going to close this out. If it continues to be an issue we'll hear something about it i suspect

**Comment by mtcA6** [comment]
@ACParker89 closed one of tom's blocked tickets
