### ISSUE TITLE
Create Job to update status in SuS

### ISSUE THREAD

**Issue by rileyanderson** [department-of-veterans-affairs/va.gov-team#65000]

**Comment by joeniquette** [comment]
before this is closed, we need to decide what we are going to do if the call isnt successful after a certain number of attempts. We should document a possible manual reconcilation process. 

Proposal is to somehow make it so the user is presented with the ToU again of we cant get the call to go through, but the real issue behind this is why cant the call go through. Making the user do it again doesnt resolve this.

**Comment by joeniquette** [comment]
before this is closed, we need to decide what we are going to do if the call isnt successful after a certain number of attempts. We should document a possible manual reconcilation process. 

Proposal is to somehow make it so the user is presented with the ToU again of we cant get the call to go through, but the real issue behind this is why cant the call go through. Making the user do it again doesnt resolve this.
