### ISSUE TITLE
[QA] Claim cards functional tests in Test Rails

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#65006]
## Steps

- [ ] Use cases for regression plan identified (product/engineering)
- [ ] Use cases for functional test plan identified (product/design/engineering)
- [ ] Use cases for regression plan created w/ steps in TestRails
- [ ] Use cases for functional test plan created w/steps in TestRails
- [ ] All tests run
- [ ] All reports/tickets created. 

## Acceptance Criteria

- [ ] Regression Test plan created in TestRails
- [ ] Functional Test plan created in Test Rails
- [ ] All tests are run at least once
- [ ] Coverage for References Report created in Test Rails
- [ ] Summary Defects Report Created with associated Epic and tickets

**Comment by HeatherWidmont** [comment]
We should be unblocked - moving this back into In Progress @jacobworrell
