### ISSUE TITLE
SOCKS access for Patrick Vinograd

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/va.gov-team#65016]
### Your Name

Patrick Vinograd

### Your Email

patrick.vinograd@va.gov

### Your Role and Team

Engineering Director, VES Portfolio

### Product Manager (PM) name and email

n/a

### Product Owner (PO) name and email

Bill Chapman

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCHqz4ujSbXFXsQab5JGnWKektqSiO2YLvC6U79io+z9LMEShl5E365TB6We8pKH+q3aS4Pze9ILRzvV2UUXAdJj2pDm2Y9NhmcPtJpDqA00GCbTN1Pb7/0Q9SR2MER68Wk4no6ezXWKiwN5Ofx1CVRa1PwQce2nRr8akk8uICK0pFhx798KM5zqmjMC8fkF8BY/l9o7R72ohNZwnKJjLm1MPhCitCeOP3+QAXgM69LKrb8QOE4iaA1QFbaOtukTPp0lU/gSQQiTlNKIPMXV+zMQb0SR0s1DMavIoYh/XIfmII62zk/EUwujGba2KcFY8QvV6LoxNAygMhrB585nI5U8AT5WQEB4/LNEwvZhq28fr3g5m0oBboUGxGGNImyGZ5GJRVIKus3tqPrzWmzgV51+hiuu5wMFz/O8sGqiis3C3DxJlzxFNL/dJsWgcQ1NjyYzesogC0wucUy217ZzaLqsV2C8yKDJtp8JZrd0CXAH8eH2wGvz+ZD52onEM5rfJ0= patrick.vinograd

### E-QIP Transmittal Confirmation

I don't have access to E-QIP anymore (completed it ~8 months ago) but I am a fully credentialed permanent employee of VA, with a PIV and a completed background check. If there's an alternate way of confirming that let me know. 

I am consulting with the VA.gov Health Portfolio and Platform teams on a few different projects. 

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by patrickvinograd** [comment]
Confirming I have been added to the VFS roster now, per https://github.com/department-of-veterans-affairs/va.gov-team/issues/65031

**Comment by rmtolmach** [comment]
✅ access granted. Give it about 5 min and then run `vtk socks setup` again. Docs if ya need 'em: https://depo-platform-documentation.scrollhelp.site/getting-started/accessing-internal-tools-via-socks-proxy
