### ISSUE TITLE
FE | Disability Rating EVSS>LH | Check in advance if a user should even query for Dis.Rating

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#65019]
## Background 
To reduce the number of GETS we're sending through vets-api , the FE could check to see if we should even ping the BE and prevent us from sending unnecessary traffic to the BE

## Tasks 
- [ ] using the claims object from the user endpoint to determine if we should hit the disability rating endpoint 

## Acceptance Criteria 
- [ ] we're no longer generating unnecessary traffic (eg. non-veteran would never have a disability rating, LOA1 user) in the BE with a bunch of 403s

**Comment by mtcA6** [comment]
@adamwhitlock1 @tpharrison thanks for discussing these 403 errors. Please add in the tasks y'all need to make this check happen so we can reduce the noise there in data dog. I've tentatively got this in sprint 21 or 22 or so

**Comment by tpharrison** [comment]
@mtcA6 @adamwhitlock1 
User-claims data informs the FE which endpoints it should call.  Currently, the rating-info claim is set to EVSS policy.  I need to switch this to use the Lighthouse policy.  I'll open a ticket for this.

**Comment by mtcA6** [comment]
is this something I can test? @adamwhitlock1

**Comment by adamwhitlock1** [comment]
@mtcA6 Yes! To validate this, we will need to log into a user that doesn't have a rating and also then check  a user that does have on. Users to validate with are:

No rating / should not request rating_info
vets.gov.user+8@gmail.com

Has rating / should request rating_info
vets.gov.user+202@gmail.com

I think the easiest way to test that the endpoint is not requested for a user is to open the network tab of the devtools when the profile loads and make sure that the endpoint is not being requested.

the endpoint we are looking for is `rating_info`.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWRoQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a5519e8c6198196f75ceb9ca0b953fc815cd3f08/Screenshot%202023-10-23%20at%2010.37.24%E2%80%AFAM.png)

**Comment by mtcA6** [comment]
Tested w/the users you recommended and logged in with my own profile and this worked the way you detailed above.
