### ISSUE TITLE
Update Advanced Support Best Practices (DataDog Access Section)

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#65028]
## Description 
Update the DataDog Access section of the Advanced Support Best Practices doc here: https://vfs.atlassian.net/wiki/spaces/PTST/pages/2630353240/Advanced+Ticket+Support+Best+Practices#Datadog-access

To match the process on the Platform Site.

---

## Definition of Done
Complete the tasks below.
---

## Tasks 

- [x] Update the DataDog Access section of the Advanced Support Best Practices doc here: https://vfs.atlassian.net/wiki/spaces/PTST/pages/2630353240/Advanced+Ticket+Support+Best+Practices#Datadog-access. To match the process on the Platform Site.

--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by lindsay-insco** [comment]
https://vfs.atlassian.net/wiki/spaces/PTST/pages/2761326593/Advanced+Ticket+Support+Best+Practices+Tier+1#Datadog-access - update here
