### ISSUE TITLE
[BE] 10-10EZ - Performance testing: Work with Platform team on Connection Pool issue

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#65026]
## Background
During load testing, [an issue was found](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/engineering/Load%20Testing/10-10EZ%20Load%20Testing%20report.md#issues-discovered-during-testing):
- When >30 simultaneous connections are made to the file upload api, the postgres error "FATAL:  remaining connection slots are reserved for non-replication superuser connections" occurs. File uploads will fail until the load decreases to the point where the postgres connections are no longer maxed out.
     - The connection pool multiplied by the number of servers and threads that the application is running is overloading the max connections allowed by the postgres database server 
     - (this is what I think is happening but I'm not 100% sure it's the cause).
 
## Tasks
- [ ] Work with Platform to confirm that the connection pool issue is the cause of the maxed out connections
- [ ] Work with Platform to make the needed change (this may be different, based on the findings from the confirmation task above)
     - Change the connection pool variable so that the total number of application connections is less than the max connections allowed by postgres, then run the load test again and see if errors still occur.
     - 

## Acceptance Criteria
- Work with Platform team to resolve the issue that causes overloads during load testing of the application

**Comment by lihanli** [comment]
the platform team said they will look into this issue
https://github.com/department-of-veterans-affairs/devops/pull/13436#issuecomment-1726259973
