### ISSUE TITLE
Sprint 36 Unplanned Work

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#65039]
Please add all unplanned work for Sprint 36 here with a very brief description of the work for our records. Thanks, team!

**Comment by HeatherWidmont** [comment]
Oops, I just realized you already created a ticket @saderagsdale. I added a bit more detail to[ the one I just created](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65048), do you mind if we close this one?
