### ISSUE TITLE
Connect Github to Domo

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#6504]
## User Story or Problem Statement
How might we connect Domo with Github so that we can track and visualize support epics and tickets?

## Goal
Work with Domo to connect that platform to Github.

## Background
We have been trying to connect Github to Domo in the Facility Locator MVP #5001 . We are not using this as a dependency to release the Beta, however, we want to eventually connect them and will continue to communicate with Domo to complete this task.

## Acceptance Criteria
- [ ] Continue communications with Github & Domo
- [ ] Determine how to connect Github to Domo
- [ ] Document how to connect Github to Domo
- [ ] Share out findings with the team & Platform (the other Platform teams will be interested in this)

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by joanneesteban** [comment]
@jonwehausen 

Currently:
- 2 separate support requests with Domo
- 1 with Github

**Comment by jonwehausen** [comment]
Full Github enterprise support ticket can be found here: https://enterprise.githubsupport.com/hc/en-us/requests/585026?page=1

**Conclusion: We are now able to retrieve issue data for the VA.gov-team repository!** 🎆 

Further notes: 
- This dataset is named "[Live] VA.gov-team Repository Issues"
- This dataset can be reused for other Github Dataset use cases. 
- I attached a small ETL to filter down specifically for the issues identified within Facility Locator KPIs as _known issues_ needing to track. Also included a table mockup visual and placed on Facility Locator Product Success Tool MVP
![image](https://user-images.githubusercontent.com/48527022/78781494-56eda600-796e-11ea-9f36-d4374c6520f1.png)
