### ISSUE TITLE
[Letters Generator to Lighthouse] Update LH generate endpoint call

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#65047]
In order to fix the bulk of the errors we're seeing when downloading `benefit_summary_dependent` letters, Lighthouse is working on improving the generate endpoint to accept both the Veteran's and the logged-in User's ICNs. 

We need to update our code to send both of these identifiers.

In order to do that, we should:
- [ ] Get LH a few ICN pairs (dependent + sponsor) so they can test their endpoint
- [ ] Test
- [ ] Deploy
- [ ] Release

**Comment by HeatherWidmont** [comment]
@kjduensing & @samcoforma to sync today or tomorrow to pair on this

**Comment by HeatherWidmont** [comment]
Ran into a blocker yesterday with testing, should be resolved now & will be continued today. @kjduensing to schedule time with @samcoforma today for pairing

**Comment by HeatherWidmont** [comment]
@kjduensing passing this over to @samcoforma

**Comment by HeatherWidmont** [comment]
@jerekshoe will review, merge, & then monitor
