### ISSUE TITLE
SOCKS access for [Kit Lykos]

### ISSUE THREAD

**Issue by KitLykos** [department-of-veterans-affairs/va.gov-team#65041]
### Your Name

Kit Lykos

### Your Email

kit.lykos@civicactions.com

### Your Role and Team

Accelerated Publishing, VA DevOps Engineer

### Product Manager (PM) name and email

Tim Cosgrove tim.cosgrove@agile6.com

### Product Owner (PO) name and email

Erika Washburn Erika.Washburn@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKnNmCikrd61Z13HlEFTQd1L86+2nRqxzoItSJrSQx0i paige@fardreamer.net

### E-QIP Transmittal Confirmation

![E-QIP Transmittal Confirmation](https://github.com/department-of-veterans-affairs/va.gov-team/assets/140734297/84754060-c115-4c59-81db-70f8a897aea7)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by ben-allen-oddball** [comment]
Socks access provisioned.

**Comment by flooose** [comment]
I'm confused. Why was this issue closed three weeks ago and now there is a total of 3 addtional PRs attached to it?

**Comment by KitLykos** [comment]
I got a new computer because the old one was so flakey. It's my fault. :-/

**Comment by flooose** [comment]
Ok, updated ssh key has been merged. Give it about 10 minutes. Good luck!

**Comment by KitLykos** [comment]
Thank you, this should be the last time for a long time hopefully!
