### ISSUE TITLE
Organize Advanced Support Best Practices Doc

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#65046]
## Description 
Organize this document: https://vfs.atlassian.net/wiki/spaces/PTST/pages/2630353240/Advanced+Ticket+Support+Best+Practices

Into role based categories for ease of use.

---

## Definition of Done
Tasks completed below.

---

## Tasks 

- [ ] Organize into more intuitive buckets for easy finding. 

--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by alyssagallion** [comment]
Sending to @bdech since he organized it a bit!

**Comment by bdech** [comment]
I spent some time re-organizing the structure for how the information is presented. I decided to break down tasks by community of practice. I kept all of the access requests together under one umbrella, and left other misc. items as is.

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/135037265/c5d7a2f3-af9c-48c6-ad0e-91f607f81ed9)

**Comment by alyssagallion** [comment]
Complete!
