### ISSUE TITLE
Make SubmitForm686cJob and SubmitForm674Job idempotent

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#65052]
## Issue Description

Form 686c submission can fail for any number of reasons. Some failures (e.g. 503s or 504s from BGS) are intermittent and should be retried until they succeed. However, these jobs are not idempotent. Running them multiple times will result in duplicate requests, records, emails, etc. We need to ensure that there are no consequences to retrying these jobs. That is the aim of this ticket.

~~Technical discovery is required to provide a complexity estimate. Given the number of BGS requests we're making, I have a feeling that this could get complicated. My preliminary estimate is an 8.~~

In `lib/bgs/form686c.rb` and `lib/bgs/form674.rb`, the `Vnp` creations can occur any number of times (per conversations with RBPS). The call to `BenefitClaim.new` is the only call that needs to be successful for our claim to be established.

If the `VnpVeteran`, `VnpRelationships`, or `VnpBenefitClaim` creations fail, the request can be rerun without negative impact.
Once `BenefitClaim.new` has successfully resolved, and we can catch & log any excepctions that occur afterwards, marking the job complete. Meaning, we need to wrap `vnp_benefit_claim.update`, `prep_manual_claim`, `bgs_service.create_note`, and  `bgs_service.update_proc` logic in a rescue block and log any relevant information before proceeding as a success. Estimating as a 3. 

---
## Tasks
- [ ] Wrap `vnp_benefit_claim.update`, `prep_manual_claim`, `bgs_service.create_note`, and  `bgs_service.update_proc` logic in a rescue block and log any relevant information before proceeding as a success

## Acceptance Criteria
- [ ] Can retry these jobs without consequence.
---

**Comment by sortizsh** [comment]
assign to Tyler when he's back

**Comment by tblackwe** [comment]
@evansmith can you do some KT to @tfink419 and I on this ticket? We need to move forward with the original plan to make all request idempotent on our end.

**Comment by tblackwe** [comment]
@tfink419 updated requirements and unblocked the ticket, we can discuss any questions on slack
@evansmith can you sanity check us?
