### ISSUE TITLE
Add link to Sidekiq docs page

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#65069]
### Description
The platform tools page https://depo-platform-documentation.scrollhelp.site/getting-started/platform-tools lists Sidekiq, but only links to the generic website [Sidekiq.org](https://sidekiq.org/) instead of the Platform specific page https://depo-platform-documentation.scrollhelp.site/developer-docs/sidekiq-ui-access

### Relevant URLs
- https://depo-platform-documentation.scrollhelp.site/getting-started/platform-tools
- https://depo-platform-documentation.scrollhelp.site/developer-docs/sidekiq-ui-access

### Which type of team are you on? (Platform team, VFS team, or Leadership)
Leadership

**Comment by torrirosine** [comment]
This page has been updated to include the platform specific page link.
