### ISSUE TITLE
Analytics KPI dashboard update request for [Authenticated Experience My VA]

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#65061]
# Request an update to your KPI Dashboard  

## What this form is for

Use this ticket template to request an update to your existing KPI dashboard. To request a new product be added to our dashboards, please use [Request a New Standardized KPI Dashboard template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&template=analytics-request-kpi-dashboard.md&title=Analytics+KPI+dashboard+request+for+%5BTeam%5D).

### Expected delivery timelines

Once you’ve submitted this ticket template, your KPI dashboard update request will be pulled into the Analytics team’s workflow the following Wednesday during Platform Sprint Planning or Refinement. We expect to deliver your completed dashboard within the next sprint. 

## Instructions for the VFS team
First, tell us what type of change you need to make:

- [ ] Change basic product info
- [ ] **Forms**: funnel changes
- [ ] **Content**: Add or remove pages included
- [X] Other: update existing "Total GET events by type and outcome" widget

Next, use the original [KPI request template](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit#gid=981224988) or [(downloaded Excel version)](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/1586823275/KPI%20Dashboard%20Product%20Details%20Template%20-%20MAKE%20A%20COPY.xlsx?inst-v=ced1f4dd-e997-4aa2-9ae8-2cebe369b42f) you filled out to update your information. If you are not able to find that spreadsheet, reach out to the Analytics team on #vfs-platform-support for a new spreadsheet that reflects what we currently have on file.

- [ ] Make a copy of the [Google Sheet](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit#gid=981224988) [(or download Excel version)](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/1586823275/KPI%20Dashboard%20Product%20Details%20Template%20-%20MAKE%20A%20COPY.xlsx?inst-v=ced1f4dd-e997-4aa2-9ae8-2cebe369b42f)
- [ ] Complete worksheet as instructed
- [ ] Link your completed spreadsheet here: ______
- [ ] Check your sharing settings to make sure the Analytics team will be able to access it
- [ ] Add your team label to follow progress

**Additional Info**

- Please use the [KPI Framework](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/Analytics%20Playbook/va-gov-platform-analytics-kpi-framework.pdf) for more information on the metrics used in the KPI dashboards. 
- If you need any analytics support, read through the [How to request Analytics support](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guidelines.1586823275.html#Analyticscustomersupportguidelines-4.RequestaKPIDashboardinDomo).
- If you do not have Domo access, please [request access here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+access-request&template=analytics-request-google-analytics-domo-access.md&title=Request+access+to+Google+Analytics+and%2For+Domo).

**Comment by ajakabcin** [comment]
The "Total GET events by type and outcome" widget needs to be updated following our work to migration the claim status widget from EVSS to Lighthouse. The GETs are pulling in correctly in GA (see our dashboard [here](https://analytics.google.com/analytics/web/?authuser=0#/dashboard/DRqBrmiyTD6l8L75rei0fw/a50123418w177519031p176188361/_u.date00=20230815&_u.date01=20230821/) - it says Sandbox but it's prod data) - see the bottom right widget "Benefits". Everything is pulling in fine, just need the domo widget updated. Thank you! 
![Screenshot 2023-09-06 at 3 57 07 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/45603961/a3dd63fb-3209-42aa-9f41-294dba19ba9e)
![Screenshot 2023-09-06 at 3 59 05 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/45603961/ffb813db-2b8e-467b-8b1b-4645e7296bd5)

**Comment by michelle-dooley** [comment]
@ajakabcin - want to make sure I am following the ask, you just need us to add the event actions in the Benefits widget of the GA report to those that are populating the Domo dashboard, correct? I assume we keep the old ones for the history we just need the new ones added for post migration.  Correct?

**Comment by ajakabcin** [comment]
@michelle-dooley correct!

**Comment by michelle-dooley** [comment]
@ajakabcin we will add this to our sprint starting tomorrow.  Can you tell me which of those api_type categories on the Domo report these new API Get requests go into?

**Comment by ajakabcin** [comment]
Hey @michelle-dooley these are get requests for Claims :)

**Comment by michelle-dooley** [comment]
@ajakabcin the updates are complete. Let me know if you have any questions otherwise we will close this ticket.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3NFQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--08d5c8f60b68565ba2fd7bfc1174c9e3b7782384/image.png)
