### ISSUE TITLE
Sidekiq Admin UI access for [Michael Chelen]

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#65073]
### Your Name

Michael Chelen

### Your GitHub handle (Sidekiq Admin UI access is managed through GitHub)

@mchelen-gov

### Your dsvagovcloud AWS user name (if applicable)

Mike.Chelen

### Team, Role, and Company of the target individual

CTO Office Engineers

### COR Name

Other - please specify in 'Additional Notes'

### Please confirm if you are on the VFS Team Roster or Platform Team Roster

- [ ] [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Sidekiq UI Access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### If PRODUCTION ACCESS is required, confirm/complete ONE of the following

- [X] I have an AWS Username and it is listed in [here](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf)
- [ ] I currently have access to vets-api Production Terminal via ArgoCD
- [ ] I've attached a screenshot of my E-QIP Transmittal Notice E-mail (Drag or Copy/Paste in Additional Notes Section below)

### Additional Notes

COR: N/A, VA employee
Sidekiq UI access: Production launch preparedness

**Comment by bdech** [comment]
@mchelen-gov I know you were switching roles recently but to keep with protocol can you provide a screenshot of your E-QIP transmittal? I know you have AWS access but, I was unable to locate an E-QIP screenshot under your older access requests.

**Comment by bdech** [comment]
@mchelen-gov You've been granted access to `dev`, `staging`, `sandbox`. Access to prod has been approved by Platform leadership limited to 6 months expiring 03/07/24. Please set a reminder for yourself to return to this Issue and re-request access within 1 week of the expiration date. You'll receive 1 reminder with a 72 hour window to respond. Failure to do so will result in lost access and will require you to fill out a new request.

**Comment by bdech** [comment]
Slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1694183876986059)

**Comment by mchelen-gov** [comment]
> Hey @mchelen-gov, Your Sidekiq UI Production access has expired.
> 
> Would you like to request an extension? You have 72 hours to respond, or your 
> access will be revoked and you will need to fill out a new request.

@bdech Thanks for the ping! Let's go ahead and extend for now, and I'll review to see if this is needed going forward.
P. S. Very happy to see this access expiration process in place!

**Comment by bdech** [comment]
@LindseySaari @ericboehs can one of you please give us a :thumbsup: to extend their access?

**Comment by bdech** [comment]
support slack reminder [here](https://dsva.slack.com/archives/C06CY71PCAX/p1710250153514199)
