### ISSUE TITLE
[SW] Analytics 2/2 - Collect launch stage & post launch data to support the release plan (Post Launch)

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#65075]
### Overview
We need to report metrics on the launch phases and post launch windows. For SW we will have 2 tickets – the dates technically overlap as we launched mid-day, so if we can dial in the reports to as close to the actual release time that would be great.

[SW Release plan](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/62316)

### Data

**Post Launch Metrics 2 (Month one 8/30/23 – 9/30/23)**

- Number of unique users: [Enter Data]
- Any issues with VA handling/processing?: Yes, No, N/A
- Types of errors logged: [Enter Data]
- Any changes necessary based on the logs, feedback on user challenges, or VA challenges? Yes, No, N/A
- If yes, what: DATA, N/A

**Comment by kjsuarez** [comment]
Follow on to #65074

**Comment by kjsuarez** [comment]
- Number of unique users: ~3800
- Any issues with VA handling/processing?: Yes
- Types of errors logged: 
    - `BackendServiceException: {:status=>500, :detail=>nil, :code=>"VA900", :source=>nil}`
    - `BackendServiceException: {:source=>"VaNotify::Service", :code=>"VANOTIFY_400"}`
- Any changes necessary based on the logs, feedback on user challenges, or VA challenges? No
- If yes, what: n/a
