### ISSUE TITLE
[SW] Analytics 1/2 - Collect each launch stage & post launch data to support the release plan (Post Launch)

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#65074]
### Overview
We need to report metrics on the launch phases and post launch windows. For SW we will have 2 tickets – the dates technically overlap as we launched mid-day, so if we can dial in the reports to as close to the actual release time that would be great.

[SW Release plan](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/62316)

### Data

**Data for stage A 10% (8/21/23 – 8/23/23)**

- Number of unique users: DATA
- Were any downstream service affected by the change?: Yes, No, N/A
- Types of errors logged: DATA
- What changes (if any) were necessarily based on the logs? Yes, No, N/A

**Data for stage B 25% (8/23/23 – 8/25/23)**

- Number of unique users: DATA
- Were any downstream service affected by the change?: Yes, No, N/A
- Types of errors logged: DATA
- What changes (if any) were necessarily based on the logs? Yes, No, N/A

**Data for stage C 50% (8/25/23 – 8/30/23)**

- Number of unique users: DATA
- Were any downstream service affected by the change?: Yes, No, N/A
- Types of errors logged: DATA
- What changes (if any) were necessarily based on the logs? Yes, No, N/A

**Data for stage D 100% (8/30/23)**

- Were any downstream service affected by the change?: Yes, No, N/A
- Types of errors logged: DATA
- What changes (if any) were necessarily based on the logs? Yes, No, N/A

**Post Launch Metrics 1 (Week one 8/30/23 – 9/6/23)**

- Number of unique users: DATA
- Any issues with VA handling/processing?: Yes, No, N/A
- Types of errors logged: DATA
- Any changes necessary based on the logs, feedback on user challenges, or VA challenges? Yes, No, N/A
- If yes, what: DATA, N/A

**Comment by ScottyRJames** [comment]
Data for stage A 10% (8/21/23 – 8/23/23)

- Number of unique users: ~30
- Were any downstream service affected by the change?: Yes, Huron
- Types of errors logged: 
    - `BackendServiceException: {:status=>500, :detail=>nil, :code=>"VA900", :source=>nil}`
- What changes (if any) were necessarily based on the logs? Yes
    - Huron requested nil for `streamlined` field to account for users with the flag off

Data for stage B 25% (8/23/23 – 8/25/23)

- Number of unique users: ~55
- Were any downstream service affected by the change?: Yes, VBS/Huron file transfer
- Types of errors logged:
    - `BackendServiceException: {:status=>500, :detail=>nil, :code=>"VA900", :source=>nil}`
    - Downstream issue with VBS from nil `streamlined` field
- What changes (if any) were necessarily based on the logs? Yes
    - Revert nil change

Data for stage C 50% (8/25/23 – 8/30/23)

- Number of unique users: ~233
- Were any downstream service affected by the change?: No
- Types of errors logged: 
    - `BackendServiceException: {:status=>500, :detail=>nil, :code=>"VA900", :source=>nil}`
    - `No such file or directory @ rb_sysopen - tmp/pdfs/5655_b119e499-8e61-41ec-8000-69353043cb64_final.pdf`
- What changes (if any) were necessarily based on the logs? None

Data for stage D 100% (8/30/23)

- Were any downstream service affected by the change?: No
- Types of errors logged:
    - `BackendServiceException: {:status=>500, :detail=>nil, :code=>"VA900", :source=>nil}`
- What changes (if any) were necessarily based on the logs? None

Post Launch Metrics 1 (Week one 8/30/23 – 9/6/23)

- Number of unique users: ~899
- Any issues with VA handling/processing?: Yes
- Types of errors logged: 
    - `BackendServiceException: {:status=>500, :detail=>nil, :code=>"VA900", :source=>nil}`
- Any changes necessary based on the logs, feedback on user challenges, or VA challenges? No
- If yes, what: n/a

**Comment by Tom-Davis** [comment]
@HeatherRienks @ScottyRJames I have this data inserted into the [Release Ticket](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/62316) and closing this, we can close the release ticket once 2/2 is complete.
