### ISSUE TITLE
[FSR] Analytics - Collect each launch stage & post launch data to support the release plan (Post Launch)

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#65079]
### Overview
We need to report metrics on the launch phases and post launch windows. For the FSR Enhancements – the dates technically overlap as we launched mid-day, so if we can dial in the reports to as close to the actual release time that would be great.

[FSR Release plan](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/59807)

### Data Needed

**Data for stage A 10% (7/5/23 – 7/10/23)**

- Number of unique users: DATA
- Were any downstream service affected by the change?: Yes, No, N/A
- Types of errors logged: DATA
- What changes (if any) were necessarily based on the logs? Yes, No, N/A

**Data for stage B 25% (7/10/23 – 7/12/23)**

- Number of unique users: DATA
- Were any downstream service affected by the change?: Yes, No, N/A
- Types of errors logged: DATA
- What changes (if any) were necessarily based on the logs? Yes, No, N/A

**Data for stage C 50% (7/12/23 – 7/13/23)**

- Number of unique users: DATA
- Were any downstream service affected by the change?: Yes, No, N/A
- Types of errors logged: DATA
- What changes (if any) were necessarily based on the logs? Yes, No, N/A

**Data for stage D 100% (7/13/23)**

- Were any downstream service affected by the change?: Yes, No, N/A
- Types of errors logged: DATA
- What changes (if any) were necessarily based on the logs? Yes, No, N/A

**Post Launch Metrics 1 (Week one 7/13/23 – 7/20/23)**

- Number of unique users: DATA
- Any issues with VA handling/processing?: Yes, No, N/A
- Types of errors logged: DATA
- Any changes necessary based on the logs, feedback on user challenges, or VA challenges? Yes, No, N/A
- If yes, what: DATA, N/A

**Post Launch Metrics 2 (Month one 7/13/23 – 8/13/23)**

- Number of unique users: DATA
- Any issues with VA handling/processing?: Yes, No, N/A
- Types of errors logged: DATA
- Any changes necessary based on the logs, feedback on user challenges, or VA challenges? Yes, No, N/A
- If yes, what: DATA, N/A

**Comment by HeatherRienks** [comment]
FE & BE to sync up to discuss how to pull metrics.

**Comment by kjsuarez** [comment]
**Data for stage A 10% (7/5/23 – 7/10/23)**

- Number of unique users: ≈10
- Were any downstream service affected by the change?: No
- Types of errors logged: 
  - `No such file or directory @ rb_sysopen - tmp/pdfs/5655_b119e499-8e61-41ec-8000-69353043cb64_final.pdf`
- What changes (if any) were necessarily based on the logs? None, issue could not be reproduced reliably.

**Data for stage B 25% (7/10/23 – 7/12/23)**

- Number of unique users: ≈10
- Were any downstream service affected by the change?: No
- Types of errors logged: None
- What changes (if any) were necessarily based on the logs? None

**Data for stage C 50% (7/12/23 – 7/13/23)**

- Number of unique users: ≈5
- Were any downstream service affected by the change?: No
- Types of errors logged: None
- What changes (if any) were necessarily based on the logs? No

**Data for stage D 100% (7/13/23)**

- Number of unique users: ≈15
- Were any downstream service affected by the change?: No
- Types of errors logged: None
- What changes (if any) were necessarily based on the logs? No

**Post Launch Metrics 1 (Week one 7/13/23 – 7/20/23)**
- Number of unique users: ≈170
- Any issues with VA handling/processing?: Yes
- Types of errors logged: 
  - `BackendServiceException: {:source=>"VaNotify::Service", :code=>"VANOTIFY_400"}`
- Any changes necessary based on the logs, feedback on user challenges, or VA challenges? Yes
- If yes, what: Minor changes to requests to VaNotify service to prevent client side errors.

**Post Launch Metrics 2 (Month one 7/13/23 – 8/13/23)**

- Number of unique users: ≈3275
- Any issues with VA handling/processing?: Yes
- Types of errors logged: 
  - `BackendServiceException: {:source=>"VaNotify::Service", :code=>"VANOTIFY_400"}`
- Any changes necessary based on the logs, feedback on user challenges, or VA challenges? Yes
- If yes, what: Minor changes to requests to VaNotify service to prevent client side errors.
