### ISSUE TITLE
BE | Profile | Lighthouse | Handle 502 HTML Errors

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#65093]
## Background
When Lighthouse is returning a 502 error in HTML format which results in a parsing error.  [Here is an example](http://sentry.vfs.va.gov/organizations/vsp/discover/platform-api:e4c4efe5d4764fcabb629c67de5ec843/?display=default&environment=production&field=url&field=error.value&field=timestamp&name=Errors+by+URL&query=event.type%3Aerror+external_service%3Aveteran_verification%2Fservice&sort=-timestamp&statsPeriod=1h&widths=-1&widths=-1&widths=-1).

## Tasks
Update parsing to handle HTML response for:
- [x] Direct Deposit
- [x] Rating Info

## Acceptance Criteria
- [x] Add spec to test parsing
- [ ] Test in staging (might not be able to simulate)

**Comment by mtcA6** [comment]
@tpharrison are you working on this in this sprint?

**Comment by tpharrison** [comment]
I wasn't planning on it.  I just noticed this error occurring with rating info (not direct deposit).  It's fairly infrequent and I want to reach to the benefits disability team first since they are the code owners.
