### ISSUE TITLE
Prometheus Data Retention

### ISSUE THREAD

**Issue by omgitsbillryan** [department-of-veterans-affairs/va.gov-team#651]
## User Story
As a va.gov engineer or product owner, I'd like metrics to go back further than 2 weeks, so that I can have a better understanding of past performance.

## Background Context
There’s 4 Prometheus environments: `dev`, `staging`, `prod`, & `utility`. The `utility` environment keeps data for 1 year and selectively replicates some data from the other environments over to it for longer-term storage. That selective list can be found here: https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/prometheus/rules/job.rules

[More reading from slack thread](https://dsva.slack.com/archives/C7S6EA0ES/p1563825988001600)

## Other Considerations
- As of `1.8.2` (our current version), Prometheus is not good at storing high cardinality data for long periods of time, so performance and disk size may be issues. 
- [Upgrading prometheus](https://github.com/department-of-veterans-affairs/va.gov-team/issues/162) may help with disk size and performance problems, but isn't strictly necessary for us to increase data retention time.

## Acceptance Criteria 
Discovery - answer the following questions:
- [ ] do we want to store **all** metrics for longer or are there only a specific few we are interested in?
- [ ] how much does upgrading prometheus help us?
- [ ] RFC written for implementation plan (optional)

Implementation
- [ ] all (or some) metrics are stored in Prometheus for time period longer than 2 weeks (time period TBD)

**Comment by ricetj** [comment]
@omgitsbillryan Is this the same as the work we have here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/162

**Comment by johnpaulashenfelter** [comment]
Likely solved by Domo and Bigquery and the analytics team

**Comment by jbritt1** [comment]
Is this work still relevant? Can this ticket be closed if not?

**Comment by jbritt1** [comment]
CC @jhouse-solvd

**Comment by joanneesteban** [comment]
@jhouse-solvd thanks for tagging! This data is going to be tracked via Datadog, right? We don't have this in BigQuery. Right now, the only metric that we consistently grab is the "monthly system availability" from [this Grafana dashboard](https://grafana.vfs.va.gov/d/eyZN2O_Mk/ww-uptime-report?orgId=1). We grab the "last month" of data to share with the Office of Management & Budget every month.

**Comment by jhouse-solvd** [comment]
@joanneesteban - yes, this data will be captured with the DataDog agent, and published to the DataDog UI 

when we dig into the "product quality narrative" in the future, we can discuss data retention aka "how long should we keep metrics?" for given products/audiences. 

Closing.
