### ISSUE TITLE
API timeout research part 2 

### ISSUE THREAD

**Issue by SamStuckey** [department-of-veterans-affairs/va.gov-team#65102]
Complete documentation of our 3rd party API endpoints (relative to the 526 flow) and document their internal / external timeouts

[Document with output](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/engineering_research/endpoint_timeout_discovery.md)

**Comment by austinjprice** [comment]
There are a few outstanding API timeouts that still need to be doucmented but this can be closed until those particular end points are prioritized
