### ISSUE TITLE
FE | CICD | Isolated App builds, removing cross app dependencies for Profile in the PLATFORM code - PT 3

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/va.gov-team#65114]
## Issue Description
To speed up the CI pipeline and make our app less reliant on others, we should remove cross app imports. They are listed here: 
https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/cross-app-import-report

Slack thread here: https://dsva.slack.com/archives/C909ZG2BB/p1655235269599459

More information on this process can also be found here: https://depo-platform-documentation.scrollhelp.site/developer-docs/isolated-application-builds

INITIAL DISCOVERY DOC:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/engineering/discovery/isolated-app-builds.md

In the discover doc there lists out the specific files that need to be updated. This ticket is to update the PLATFORM specific files.

This will no doubt be the largest and most complex ticket in regards to getting the personalization app folder to be added to the isolated app builds process.

 This is part 3 of 3ish parts.

- [x] src/platform/forms/save-in-progress/ApplicationStatus.jsx
- [x] src/platform/site-wide/mega-menu/tests/megaMenu.cypress.spec.js~
- [x] /platform/user/profile/vap-svc/actions/transactions.js~
- [x] src/platform/user/profile/vap-svc/components/ContactInformationFieldInfo/ContactInformationUpdateSuccessAlert.jsx
- [x] src/platform/user/profile/vap-svc/components/ProfileInformationFieldController.jsx
- [x] src/platform/user/profile/vap-svc/containers/AddressValidationModal.jsx~
- [x] src/platform/user/profile/vap-svc/containers/AddressValidationView.jsx~
- [x] src/platform/user/profile/vap-svc/tests/selectors.unit.spec.js

For most of these file, they import form Profile, so we will need to move files into the platform code, so that nothing is imported outside of platform for these instance. This may end up making it necessary to move more files depending on the implications and complexity of fixing the dependency tree around this.

Since this is the last task, then we should be able to add personalization to the isolated app builds list once this is complete.

## Front end tasks
- Remove cross app imports from platform
  - Copy/Move imported code into our app where applicable
  - Move code into platform if it is heavily used and is more utility based in nature
- Ensure tests build
- Personalization app added to isolated app build list

## Acceptance Criteria
- [x] Profile cross app imports are resolved
- [x] All test pass

**Comment by adamwhitlock1** [comment]
still WIP with holiday haven't finished up work on this, probably need another day or two to get PR in.

**Comment by adamwhitlock1** [comment]
One PR for the remaining work has been merged, it relocates the Save In Progress form data into the platform based code.

This does require a documentation change, which I have put in a ticket for as well: https://github.com/department-of-veterans-affairs/va.gov-team/issues/73344

The last PR for this work is also currently in review.

**Comment by adamwhitlock1** [comment]
Okay, I have merged all the work that isolates this app. I have one final PR open that adds the personalization apps to the isolated app builds list, and that will officially trigger the CI/CD to treat our apps as isolated:

https://github.com/department-of-veterans-affairs/vets-website/pull/27510

**Comment by mtcA6** [comment]
🎉 that's very exciting.... interested to hear later if this is helping!!!!

**Comment by adamwhitlock1** [comment]
https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/cross-app-import-report

The report now lists our app as officially 'isolated' so yay!

<img width="875" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkRXQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d306131ad8410f366cff7ce3e135b6e32784f800/Screenshot%202024-01-17%20at%203.04.10%E2%80%AFPM.png" alt="Screenshot 2024-01-17 at 3.04.10 PM.png" />

I spooled up a branch and pushed a few changes to evaluate the time it takes for the CI/CD pipelines to run, but its not as great an improvement as I would have liked to see.

Past commits have taken 47+ minutes  to run and this last commit took 29 minutes. Thats certainly better than nothing, but I was really hoping for sub 15 minutes or something... sigh. Oh well I'll take what I can get, we can close this out now.

**Comment by mtcA6** [comment]
Bummer, not lightning fast but still that's 15 fewer minutes 💃🏻

Should we explore other options?

**Comment by adamwhitlock1** [comment]
At this point, I think we are at a decent place. One area we _could_ look into is how to make certain e2e tests faster since they are slower than the unit tests usually, but not sure it's worth it.

Lets call it good for now, and if I get fed up with long wait times again we can revisit.
