### ISSUE TITLE
FE | CICD | Isolated App builds, removing cross app dependencies for My VA - PT 2

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/va.gov-team#65116]
## Issue Description
To speed up the CI pipeline and make our app less reliant on others, we should remove cross app imports. They are listed here: 
https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/cross-app-import-report

Slack thread here: https://dsva.slack.com/archives/C909ZG2BB/p1655235269599459

More information on this process can also be found here: https://depo-platform-documentation.scrollhelp.site/developer-docs/isolated-application-builds

INITIAL DISCOVERY DOC:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/engineering/discovery/isolated-app-builds.md

In the discover doc there lists out the specific files that need to be updated. This ticket is to update the My VA specific files. This is part 2 of 3ish parts.

- dashboard/components/apply-for-benefits/ApplyForBenefits.jsx
- dashboard/components/apply-for-benefits/SavedApplications.jsx

## Front end tasks
- Remove cross app imports from My VA
  - Copy/Move imported code into our app where applicable
  - Move code into platform if it is heavily used and is more utility based in nature
- Ensure tests build

## Acceptance Criteria
- [x] My VA cross app imports are resolved
- [ ] All test pass

**Comment by mtcA6** [comment]
@ajakabcin lets talk about this tomorrow if you have a few minutos?

**Comment by mtcA6** [comment]
@adamwhitlock1 what's the size for this?

**Comment by DanielMiller-agile6** [comment]
test

**Comment by adamwhitlock1** [comment]
@allisonlu We merge these changes and nothing broke so yay! Can you validate that this work is done? Then I can close it out and move onto pt 3 next sprint.

**Comment by allisonlu** [comment]
lookin good! validated
