### ISSUE TITLE
SOCKS access for [Fletcher Bonds]

### ISSUE THREAD

**Issue by fbonds** [department-of-veterans-affairs/va.gov-team#65111]
### Your Name

Fletcher Bonds

### Your Email

joseph.bonds@va.gov

### Your Role and Team

Senior QA Engineer 10-10 team

### Product Manager (PM) name and email

Heather Justice heather.justice@adhocteam.us

### Product Owner (PO) name and email

Patrick Bateman patrick.bateman@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDzjJte9+cK6tK3IvlM399OmwaaemNpsdoJf5C5y44vKLwXRlY78LSB7+RgCz2adY7xvOfYsvG84dOP5vysUSPz882PvTQD98sHPH8LDoATztpYaxkj9K8SoWZcJWkRjP1QmmrFT1rxeka9tnzdjduK/ofrmU66wePXkt9C5r1apYAdFdrLjpFqrQiUGkUtrGEPHpxmJ+eDVsc81PdzePG/jwWzBLnegcmGBjIXogsFyIA1t46mlOMDBnv79w6g41VYBaJ6TM79nv1pffyTuWr4+0kF9miwaWgdB8bu9m+wlGuzqtQaH0/zJqMLlIHGleWF/7Vbb5kwJVjbBF7eFQPY3z8iP/lOoxRkPsAmAXbArEvDiMZRbybIPaD+Prmp/Uz1cfrWrNnrORcWqITGc9r+rhNoVXisYTwxcxcbl+GiZsfvd7MVsairie8la5W7yZnSFe+wlKbPcIJ5xkol7nBEmxWAF+rtHzyZJiIydUlOrHkmoVtUebgMmSPRZKrmBI8= fletcherbonds@fletcherbonds-VPQ32RX60F

### E-QIP Transmittal Confirmation

[Ad Hoc, LLC Mail - Transmittal Notice--Bonds, Joseph (Agile Six Applications, Inc).pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/12550639/Ad.Hoc.LLC.Mail.-.Transmittal.Notice--Bonds.Joseph.Agile.Six.Applications.Inc.pdf)

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by ben-allen-oddball** [comment]
SOCKS access reprovisioned.
