### ISSUE TITLE
Reference - Produce Inventory for eMASS

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#65129]
A priority task has been given to to team members on Reliability Team and Lights Team, the task exists on the Security Board, which due to restrictions on the board itself, cannot be directly added to the board.

Instead, we're creating a reference to the ticket here, to track this task on our team board.

https://github.com/department-of-veterans-affairs/platform-security/issues/295

**Comment by JoeTice** [comment]
Sprint 34 Update - In Progress, Eric and Hector are collaborating on this and continue to work on completing the list

**Comment by JoeTice** [comment]
Sprint 36 Update - In Progress, Eric and Hector are collaborating on this and continue to work on completing the list. Work will continue/complete in Sprint 37

**Comment by ericboehs** [comment]
I've got a list of software with versions and presented it to Ken. Awaiting his response. If there is additional work around this. I'll open another issue if so.
