### ISSUE TITLE
get access to Login.gov Design System

### ISSUE THREAD

**Issue by djmunoz1** [department-of-veterans-affairs/va.gov-team#65138]
AC:
- follow up with Carrie McGrath re: access to Design System
- escalate with Tom until complete

DEF OF DONE:
- Kirk receives link to design system
- drop the link in this ticket

**Comment by skirkman16** [comment]
No access yet - last correspondence was with Carrie on 9/18. The latest prototype has been created using USWDS components.

**Comment by skirkman16** [comment]
I put the link to download the design system in our Google Drive: https://drive.google.com/drive/folders/1e9mfP4Y1oZn3lWdcA3DjFsu8nAIszFQO

**Comment by skirkman16** [comment]
Figma link: https://www.figma.com/file/Bj0ufGx4PqDRuqLNF8XVpA/2023-10-VA_Request-LGDS_Design_Assets?type=design&node-id=0%3A1&mode=design&t=fK3XlLGlVbDBaVRR-1
