### ISSUE TITLE
review revised DOMO dashboard walkthrough

### ISSUE THREAD

**Issue by djmunoz1** [department-of-veterans-affairs/va.gov-team#65139]
As a data admin, I need to clearly understand what key questions are being answered by the current data dashboard so that I can identify gaps and understand opportunities to refine the presentation of data.

AC:
- get metrics from strategic roadmap
- discuss metrics with Tom for affirmation
- meet to determine if/how those metrics can be uncovered with existing data
- document gaps and opportunities

DEF OF DONE:
- store doc in GH

**Comment by SophiaPhilipMO** [comment]
Closing due to communication campaign pause and SSiT no longer owning comm campaign
