### ISSUE TITLE
Audit: On This Page component

### ISSUE THREAD

**Issue by kristinoletmuskat** [department-of-veterans-affairs/va.gov-team#65141]
Problem: Across the site, we have inconsistent use of the On This Page component. Sometimes it is used, and sometimes it isn't. We'd like to develop standards around use of the On This page component, and implement the standards across the site.

Work: Conduct a cross-site audit of the 'On This Page' component, noting where it is used and where it isn't, and how effective it seems to be. 

Note: def talk about these first with Mikki before starting. Need to reference the US web design system when we take on components like this -- document how that is documented in the US system and make sure we use it in that way.

Progress notes:

- Working in this draft audit Google sheet [On This Page component audit 9.2024](https://docs.google.com/spreadsheets/d/1uHGoaykeblwob_n-9pPi84OXmuOhZwKOANACUE5xUls/edit?usp=sharing) for the moment.
- Tabs for audit and for questions/observations
- Reviewing [VADS On This Page](https://design.va.gov/components/on-this-page) and [USWDS In-Page Navigation](https://designsystem.digital.gov/components/in-page-navigation/) components as part of wider standard

**Comment by scjwalker** [comment]
The audit is complete, and the draft guidance is with Mikki for OCTO feedback.

**Comment by kristinoletmuskat** [comment]
Added to capacity tracker!
