### ISSUE TITLE
Mask Logged PII Data

### ISSUE THREAD

**Issue by tblackwe** [department-of-veterans-affairs/va.gov-team#65153]
When we send a DependentsApplicationFailureMailer email a log message is generated that contains the payload.args which contains the SSN of the veteran. is it possible to mask or remove that? 

https://vagov.ddog-gov.com/logs?query=%40payload.mailer%3ADependentsApplicationFailureMailer%20%40message_content%3A%22DependentsApplicationFailureMailer%23build%3A%20processed%20outbound%20mail%20in%204.1ms%22%20%40request_id%3A70aeaa60-50c8-4ea5-8b54-b339fba6eb45&cols=host%2Cservice%2C%40exception.cause.cause.cause.message%2C%40exception.message&event=AgAAAYpwmD9XkhNwuwAAAAAAAAAYAAAAAEFZcHdtRkVkQUFCaWR2STEySzhUakFCVQAAACQAAAAAMDE4YTcwOTktNzI2NS00NTcxLTliYTQtMWNhNmNjNDQ5YmY2&index=%2A&messageDisplay=inline&storage=online_archives&stream_sort=time%2Cdesc&viz=stream&from_ts=1686333852624&to_ts=1694109852624&live=true

**Comment by steele-lm** [comment]
Closing. Failure email will no longer be sent given that backup submission process in in place.
