### ISSUE TITLE
Add consent cookie

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#65150]

**Comment by joeniquette** [comment]
Cookie (to be added by sign-up service after user completes consent):
 Name=CERNER_CONSENT
 Content="ACCEPTED"
 Expires=2 minutes
 path="/"
 domain= .eauth.va.gov

**Comment by bosawt** [comment]
We need to confirm and make sure that a user can't manually edit this cookie. Right now it seems likely since there is no signature

**Comment by joeniquette** [comment]
this is completed
