### ISSUE TITLE
Store SLO's & SLIs in Product Outline

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#6516]
## User Story or Problem Statement
Our current SLO's and SLI's are stored in Grafana and we need them to be exposed in a more centralized manner.

## Goal
Create a table that can be viewed outside of Grafana.  For now we will store them in a table in the product outline for this project.

## Tasks
- [x] Create a table that defines the SLOs & SLIs in the product outline

**Comment by LindseySaari** [comment]
[Product outline table](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/request-timing(SLO)/request-timing.md#external-service-slos-for-request-times-per-service)

[Additional Hackmd notes](https://hackmd.io/lqvunvJ_TyegF2kQH3I82w?view)
