### ISSUE TITLE
Flipper UI access for [Sean Midgley]

### ISSUE THREAD

**Issue by Midge-dev** [department-of-veterans-affairs/va.gov-team#65185]
### Your Name

Sean Midgley

### Your GitHub handle (Flipper UI access is managed through GitHub)

@Midge-dev

### Team, Role, and Company of the target individual

Frontend Engineer for Non-disability Benefits Experience

### Please confirm if you are on the VFS Team Roster, Platform Team Roster or are a Federal User

- [X] [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [X] Lesser Environments (Dev/Staging/Sandbox)
- [ ] Production (if requesting, justify prod access below)

**Comment by bdech** [comment]
Found in VFS Roster

**Comment by bdech** [comment]
@Midge-dev You've been granted access to lesser environments.
