### ISSUE TITLE
Adding [Brittany Clausen] to DSVA Slack

### ISSUE THREAD

**Issue by bryan-riley-va** [department-of-veterans-affairs/va.gov-team#65196]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

<describe the request>  Looking to add Brittany Clausen (brittany.clausen@va.gov) to DSVA slack.  She currently has a user but it is a multi-channel user and needs to be a standard user (same type of user as Bryan Riley for example).

Are you requesting to add an individual as a:

- Full member
- Single guest
- Multi-channel
- Switching from single-channel to multi-channel?
- What channel(s) do they need to be added to?  Once in DSVA we will add her to the channels she needs.

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.   

MHV developer that could be working on VA.gov MHV products

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add [brittany.clausen@va.gov] as a single-channel guest to [_channel name_].
- Please add [_insert email_] as a multi-channel guest to these channels: [_channel names_].
- Please add [_insert email_] as a full member.
- Please change the status of [_slack username_] from [_current status_] to [_desired status_]

**Comment by LEHigley** [comment]
showing as a user already

**Comment by brittanyclausen** [comment]
As stated above "She currently has a user but it is a multi-channel guest user and needs to be a standard user (same type of user as Bryan Riley for example)".  Please reopen this ticket as the issue has not been resolved.  Thank you.

**Comment by brittanyclausen** [comment]
@bryan-riley-va How do I get this resolved?!?  I still don't have access to the channels I need because I'm still showing as Multi-Channel Guest.
