### ISSUE TITLE
SOCKS access for Daniel Schiavone

### ISSUE THREAD

**Issue by schiavo** [department-of-veterans-affairs/va.gov-team#65190]
### Your Name

Daniel Schiavone

### Your Email

daniel.schiavone@civicactions.com

### Your Role and Team

Backend Engineer, Accelerated Publishing

### Product Manager (PM) name and email

Tim Cosgrove Product Manager m.cosgrove@agile6.com

### Product Owner (PO) name and email

Erika Washburn Erika.Washburn@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCzz9IhYKpONb8xtQzttIXLVPr7ald66WsgG5rmOgrocXQeRycGy8/erGFPBGKYKI2/5sasTzPwxXZ6RLpjlPWPgli1sUS9xefcFlv6sOGM+h9yAMPBF9MMKGmt5GEFwTH2cuOrgHser/ThHoMn4i9CBo8uE0lvQR0NbUs8ilJqoCwINGTLDRNHAp6mrznM8jG/CVhziE2HvPFmemENkwW2sSUmOg67ovyS1n7is16aWKlsdcF6+Oy3iPX8R1SpnLQfY2YspGxbvYcn2Dwu+tkHrwG+aq8kyxcMWqxyw1linZLWEFM5WbT+ZQXLMQ1wyNM132LnigOlBTQUomC/cNmf/IvbHBwHny0d7nb0s33y9aqT4bgm8nJ1T8hIdwtO+snwqOzNlR6VinBrVLsruReNvygDM85/ROnceCr0m+eyoT1+1/+6jznjp87NSIHUK9M31w0rwBucXVIM/8CMdYVx4hgHih9oTtT22TgDO12LmL8lWKSMVU5QlBBDIbLZiOM= schiavo@angelica

### E-QIP Transmittal Confirmation

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/7717261/0836eb02-659c-4617-a642-98717c6964f2)

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by schiavo** [comment]
Still pending approval

**Comment by ben-allen-oddball** [comment]
SOCKs access has been provisioned.

**Comment by schiavo** [comment]
Thanks
