### ISSUE TITLE
Define Report Template

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#6520]
Define what the dashboard will look like and start building it out

**Comment by LindseySaari** [comment]
[Mock reporting template here](https://docs.google.com/document/d/1Vx1GQsm1n0ZgXOyaP6bO5kyBVI04nAwcpzZG6V_jQdM/edit?ts=5e6ffec8#)
Notes on how and what we would like to report are defined in the google document comments

**Comment by kfrz** [comment]
sum by (endpoint) (rate(api_external_http_request_duration_seconds_sum{service="EVSS/Letters"}[1h])) / sum by (endpoint) (rate(api_external_http_request_duration_seconds_count{service="EVSS/Letters"}[1h]))

This will give us an average latency for haproxy requests over time but we cannot aggregate to determine number of requests < a given percentile.

However, if we want to calculate the percentage of requests served within a given duration (say, 500ms), we would need to average pre-calculated quantiles:

> However, aggregating the precomputed quantiles from a summary rarely makes sense. In this particular case, averaging the quantiles yields statistically nonsensical values.
