### ISSUE TITLE
Sign Out All Devices button - Usability Testing

### ISSUE THREAD

**Issue by charlye-bluetiger** [department-of-veterans-affairs/va.gov-team#65208]
### Usability Testing: Sign Out All Button

Usability test the option for Veterans to sign out of all devices to ensure the flow is intuitive and that Veterans understand the implications of performing such an action. We'll test both the MVP of a single "sign out of all devices" button as well as individual device sign out buttons with Veterans prior to being implemented.

#### Acceptance Criteria

- [x] Collab Cycle [Research review ](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/432)
   - [x] Submit ticket
   - [x] Make any revisions based on feedback
   - [x] Approved for recruitment kickoff
- [x] Set up [note taking document](https://app.mural.co/t/oddball4265/m/oddball4265/1697479225159/6a0d168b0c9bd95ad422a5250349bd8ecf71aa04?sender=ub6d328e737d4511e3f063904)
- [x] Invite note takers and observers
   - [x] Send invites
- [x] Pilot study
   - [x] Schedule pilot
   - [x] Conduct pilot
- [x] Conduct sessions
   - [x] Complete sessions for the desktop cohort
   - [x] complete session for the mobile cohort

#### Context
Copied over from a comment on the FE ticket

charlye-bluetiger
commented on Mar 15
Logout of all devices button needs to be included for a security requirement
Envs:
Staging - SiS exists on all
Production - only flagship VA.gov only on mobile
QUESTION to be answered: Where would users prefer to see “log out” (of everything)?
Potential placement:
￼
SSOe users should not see this option
Eventual goal to deprecate IBM solution across the board
Staggered migration of user sessions to leverage Identity’s SiS
Timing for logout
SSOe 15 minute increments for keep alive, logout after 30 minutes
SiS 5 minutes refresh, logout after 30 minutes
Timing:
Single sign on to access all VA sites e.g. MyHealtheVet, eBenefits, VA.gov
Logout of all sessions

Acceptance Criteria
- [x]  Reviewed by UX Team
- [ ]  Reviewed by PMs
- [x]  Documentation has been updated

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by claytonzook** [comment]
We've moved over assistive tech items from this ticket onto a new ticket that we can move forward with in the future - Sign Out of All Devices Research - Assistive Tech
