### ISSUE TITLE
Analytics KPI dashboard update request for Governance Team

### ISSUE THREAD

**Issue by it-harrison** [department-of-veterans-affairs/va.gov-team#65204]
# Request an update to your KPI Dashboard  

## What this form is for

Use this ticket template to request an update to your existing KPI dashboard. To request a new product be added to our dashboards, please use [Request a New Standardized KPI Dashboard template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&template=analytics-request-kpi-dashboard.md&title=Analytics+KPI+dashboard+request+for+%5BTeam%5D).

### Expected delivery timelines

Once you’ve submitted this ticket template, your KPI dashboard update request will be pulled into the Analytics team’s workflow the following Wednesday during Platform Sprint Planning or Refinement. We expect to deliver your completed dashboard within the next sprint. 

## Instructions for the VFS team
First, tell us what type of change you need to make:

- [ ] Change basic product info
- [ ] **Forms**: funnel changes
- [ ] **Content**: Add or remove pages included
- [x] Other_____________________________

Governance team is requesting two small tweaks to its existing BQ dataset:
* for the "milestone" column, instead of turning the entire payload into a string, we would like to extract only the `number` property on the object and use that as the milestone.
* we would like to update the name of the `BQ - Governance Github tickets` dataset to `BQ - Staging Review issue tickets`

Next, use the original [KPI request template](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit#gid=981224988) or [(downloaded Excel version)](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/1586823275/KPI%20Dashboard%20Product%20Details%20Template%20-%20MAKE%20A%20COPY.xlsx?inst-v=ced1f4dd-e997-4aa2-9ae8-2cebe369b42f) you filled out to update your information. If you are not able to find that spreadsheet, reach out to the Analytics team on #vfs-platform-support for a new spreadsheet that reflects what we currently have on file.

- [ ] Make a copy of the [Google Sheet](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit#gid=981224988) [(or download Excel version)](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/1586823275/KPI%20Dashboard%20Product%20Details%20Template%20-%20MAKE%20A%20COPY.xlsx?inst-v=ced1f4dd-e997-4aa2-9ae8-2cebe369b42f)
- [ ] Complete worksheet as instructed
- [ ] Link your completed spreadsheet here: ______
- [ ] Check your sharing settings to make sure the Analytics team will be able to access it
- [ ] Add your team label to follow progress

**Additional Info**

- Please use the [KPI Framework](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/Analytics%20Playbook/va-gov-platform-analytics-kpi-framework.pdf) for more information on the metrics used in the KPI dashboards. 
- If you need any analytics support, read through the [How to request Analytics support](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guidelines.1586823275.html#Analyticscustomersupportguidelines-4.RequestaKPIDashboardinDomo).
- If you do not have Domo access, please [request access here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+access-request&template=analytics-request-google-analytics-domo-access.md&title=Request+access+to+Google+Analytics+and%2For+Domo).

**Comment by michelle-dooley** [comment]
@it-harrison - I changed the name of the dataset as requested. For milestone that is how the data is loading/coming in. I thought Shira said you guys would do the transformation of that long string into what you need from it. If you cannot do that let us know where specifically within that string the number property you need is and we can see if we can pull out.

**Comment by it-harrison** [comment]
@michelle-dooley we don't need the whole string just a part of it that is unique. The property that is unique is `number` which is a unique number GH assigns to each milestone. Thanks!

**Comment by it-harrison** [comment]
@michelle-dooley just for reference, this is the property I mean (number is a very generic property name):
<img width="611" alt="Screenshot 2023-09-11 at 11 30 25 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/8867779/5fa638c8-5233-45cd-b1e4-b48b7027a60f">

**Comment by michelle-dooley** [comment]
Thanks @it-harrison - I will review with @dorseypa1 and see what we can do to assist.

**Comment by it-harrison** [comment]
Hi @michelle-dooley @dorseypa1 just wondering the status of tweaking the "milestone" column. Thanks!

**Comment by dorseypa1** [comment]
> Hi @michelle-dooley @dorseypa1 just wondering the status of tweaking the "milestone" column. Thanks!

H Ian, this ticket is next in the queue.  I'll be starting on it this afternoon.

**Comment by it-harrison** [comment]
Hi @dorseypa1 just checking up on this ticket - we are hoping to close the issue that depends on this ticket before the end of the sprint. Thanks!

**Comment by michelle-dooley** [comment]
@it-harrison just QA'd the query and data is coming through as expected in our test dataset, @dorseypa1 just needs it add it your dataset and we should be good to. Hopefully be end of day.

**Comment by michelle-dooley** [comment]
@it-harrison a new milestone_number field as been added to your dataset. We leave the original milestone string in there as well in case you need something else out of it sometime. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ0hjIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6c25b1c5970363c404267281e447e441a052649f/image.png)
