### ISSUE TITLE
Vets-api terminal access for [Chapley Watson]

### ISSUE THREAD

**Issue by jadon1979** [department-of-veterans-affairs/va.gov-team#65212]
### Your Name

Chapley Watson

### Your GitHub handle (terminal access is managed through GitHub)

@jadon1979

### Your dsvagovcloud AWS user name (if applicable)

Chapley.Watson

### Team, Role, and Company of the target individual

1010-ez, Software Developer, Agile6

### Product Manager (PM) name and email

Heather Justice heather.justice@adhocteam.us

### Product Owner (PO) name and email

Patrick Bateman patrick.bateman@va.gov

### COR Name (leave "None" if you listed an AWS user name above)

None

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

None

### Please confirm if you are on the VFS Team Roster or Platform Team Roster

- [X] [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [X] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Please confirm E-QIP Transmittal/Adjudication. This could be a screenshot of your Transmittal/Adjudication email, a link to another request where you've submitted this proof (i.e. AWS/SOCKS), etc.

- [X] I have attached proof that I have either transmitted my E-QIP survey or previously received a favorable decision (by including in "Additional Notes" section below)

### ArgoCD terminal access requested for the following environments

- [X] sandbox
- [X] dev
- [X] staging
- [x] production (if requesting, justify prod access in 'Additional Notes' section)

### Additional Notes

https://user-images.githubusercontent.com/730997/254624086-bf4aca6c-7a1d-43a5-87cd-7a44ed6a86fb.png

I need production access so that I can get access to the rails console and debug production bug issues.  Currently, there's an issue with the 1010EZ failing submission due to a schema failure and I need to see the submission form data to track what caused the failure and then work on making sure it doesn't happen again.

### Additional resources for Support Engineer

- [ ] For users on a VFS team but not in the VFS Team Roster, they must start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] Instructions for handling requests [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access) - Support Only

**Comment by bdech** [comment]
Found in VFS Roster

**Comment by bdech** [comment]
@jadon1979 You’ve been granted access to the `dev`, `staging`, and `sandbox` environments.

Here's some additional documentation for [Vets API on EKS](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-TerminalAccess) that may help.

**Comment by bdech** [comment]
@jadon1979 Access to `prod` is pending approval by OCTODE, and we'll update you as 
soon as it's available.

**Comment by bdech** [comment]
E-QIP is contained in the link under "Additional Notes".

**Comment by BillChapmanUSDS** [comment]
Access provided, approved as per current process.  6 months.

**Comment by bdech** [comment]
@jadon1979 You've been granted access to `Production`, 
with access to Production limited to 6 months, expiring 05/6/24.

Please set a reminder for yourself to return to this Issue and 
request an extension within 1 week of the expiration date. You'll 
receive 1 reminder with a 72 hour window to respond. Failure to 
respond will result in your access being revoked and will require 
you to fill out a new request.

**Comment by bdech** [comment]
Slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1699292294326499)

**Comment by AnthonyWFlowers** [comment]
Hi @jadon1979, your access has expired.
Would you like to request an extension? You have 72 hours to respond, or your access will be revoked and you will need to fill out a new request.

**Comment by AnthonyWFlowers** [comment]
Greetings @jadon1979 your access has expired, if you require this access again please fill out another request [Here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=external-request%2Cplatform-tech-team-support%2Cops-access-request&template=vetsapi-argo-terminal-access.yaml&title=Vets-api+terminal+access+for+%5Bindividual%5D)
