### ISSUE TITLE
Usability Documentation of SSOe

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#6523]
Document that usability testing indicates that the new changes we're making (SSOe implementation) enable users to do what they need to do. This may reference prior research given our tight timeline.

### SSO Launch
**- [ ] Propose UAT/beta testing approach for SSOe launch current sprint**
- [ ] Document user flows for sign up & sign in with all 3 credential types "new ticket"
- [x] Cross-reference user flows with SSOe to identify potential pain points for users "
- [x] Discuss potential pain points with team and partners; develop solves as needed
- [x] Document pain points and or known shortcomings of the solution for future team awareness 

### Post Launch
- [ ] Write end user-facing discussion guide for future use

**Comment by ambikaroos** [comment]
test comment

**Comment by bridgethapner** [comment]
Started a research plan for UAT/usability testing session for Outbound SSOe here. It's a work in progress.
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/sso/ux-research/SSOe-testing-plan.md

**Comment by marriej** [comment]
This ticket has been closed in favor of #7859
