### ISSUE TITLE
Design System Staging Review - Accessibility Feedback - Accordion, Process List and Privacy Agreement

### ISSUE THREAD

**Issue by briandeconinck** [department-of-veterans-affairs/va.gov-team#65235]
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

-

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

### Accordion
- **Consider:** I'd love to see a more explicit callout in the accessibility guidance about setting the appropriate heading level for the accordion items. We sometimes get VFS teams coming through the Collab Cycle that pick a heading level that doesn't really fit into the page hierarchy. Otherwise the component looks great!

### Process List
- **Must:** Big concern here is around using color alone to indicate the status of each step. I think the visual affordance of the checkmark is probably fine for sighted users to distinguish between the completed and not-completed steps. For screen reader users, I'd recommend:
   - When an item has prop `checked`, insert `sr-only` text at the beginning of the heading that says "Completed:" or something similar
   - When an item has prop `active`, insert `sr-only` text at the beginning of the heading that says "Current step:" or something similar
   - When an item has prop `pending`, insert `sr-only` text at the beginning of the heading that says "Pending:" or something similar
- **Must:** Pending items are `gray-light` (#aeb0b5), which against a white background has a contrast ratio of 2.17:1. There are probably scenarios where a user will want to read what the pending steps are (if not, why include them at all?) and that contrast level will exclude at least some low vision users. If we can bump that up to `gray-medium` (#757575) that gets us to 4.6:1, which meets WCAG AA requirements.
- **Should:** As I said above, I think the checkmark is sufficient for sighted users to distinguish between completed and not-completed --- but that still leaves color as the only way to differentiate default, active, and pending. I suspect that these distinctions are less important than the distinction between completed and not-completed, but it's still information that may be lost for low vision users.
   
   I'll pitch two possible approaches for solving this:
   - Rather than using `sr-only` text as recommended above, just make that visible text for everyone. This could just be plain heading text, it could be a tag, it could be an eyebrow above the heading, etc. Text on a page is the super-boring solution to most accessibility issues!
   - Adjust the visual display of the step counter. I've included a quick-and-dirty idea here that I think would be sufficient --- active filled in, pending dashed border, default as-is. But I'll gladly defer to actual designers. I'm assuming this is also something that would require some conversations with the USWDS folks.
   
![step-indicator-explorations](https://github.com/department-of-veterans-affairs/va.gov-team/assets/6844775/62bbe4b7-a804-4f75-a5a9-490dd20d4f5f)

### Privacy Agreement
- **Consider:** Definitely not a must, but I'll always encourage making the `sr-only` text visible and ditching the icon for cognitive load.

**Comment by caw310** [comment]
Will work on the Musts for process list.

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/va.gov-team/65235?planning-poker) with Zenhub @Andrew565 @ataker @harshil1793 @it-harrison @jamigibbs @micahchiang @nickjg231 @powellkerry @rmessina1010

**Comment by caw310** [comment]
Will make the design color change to Process list in Figma when that component is created.
