### ISSUE TITLE
[Congressional] V10823124 - Online Accounts issue (Rep. Peters) Due 10/11/23

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#65236]
## Issue Description
Veteran is having technical issues with all of his VA.gov accounts including apps. Veteran is not able to access any letters to download, active claims do not show up under the Active Section and the closed claims are not accurate. Veteran works for Defense Logistics Agency and tried to use a Secure Connection using a CAC and that did not work either. This includes access to VA.gov, MyHealthyVet and eBenefits. Veteran has provided screenshots and has tried to resolve this matter on his own, only to be told “We are not able to duplicate the problem.” This has been going on for more than a year and Veteran needs assistance with getting their online accounts straightened out.
---
## Tasks
- [x] Review congressional correspondence
- [ ] Resolve issue 
- [ ] Notify Veteran and congressional correspondence channel of solution.

## Acceptance Criteria
- [ ] Veteran issue will be resolved or responded to with final answer to issue 
- [ ] Congressional Correspondence will receive details of the resolution 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by clantosswett** [comment]
In reviewing this issue, it sounds like this veteran was one of the users who experience the dependency status update issue. I have contacted a few folks from the benefits portfolio to determine next steps and once we have clarity on that, we will begin any necessary outreach to inform the Veteran.

**Comment by clantosswett** [comment]
This needs to be reviewed by the correct benefits team for investigation. I tagged Emily Theis on slack to begin that process.

**Comment by clantosswett** [comment]
Emily Theis reviewed the issue and provided guidance that the user was likely impacted by the dependency claim issue but that they submitted a claim on 9/09 which should now be established and visible in their account. I contacted the Veteran to provide this update and will wait to hear back from them that they are now able to see this information in their account.

**Comment by clantosswett** [comment]
The veteran responded and said that the claims were not the issue but that instead he couldn't see two decision letters on his va.gov account. I am going to forward the issue to EVSS to see if they can determine why this is happening and will escalate to a VFS benefits if they can't find a resolution.

**Comment by Kimberley2023-CSM** [comment]
Reached out to veteran for a Shadow call with Emily Theis and team.  Awaiting a response.

**Comment by Kimberley2023-CSM** [comment]
Heard back from the Veteran today and he has confirmed receipt of the invite and his attendance.
