### ISSUE TITLE
Cerner redirect follow-up - improve content

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#65260]
## Task Description
This tightens up the single-facility state for both the static landing page and in-app alert. Changes are content only:

**Static landing page:**
* Remove bullet/changes content when showing a single facility

**On appointments list:**
* Changes heading to align with landing page
* Adds a sentence to provide more context 

## Notes and References
This is a collaborative effort and needs layers of approval:
- Kay (brought up the issue initially)
- Kristen
- Laura Willworth
- Review with Joel Calumpong (secure messaging) and Misty-Milliron-Grant (Mobile content)
- Final approval from Coulton Bunney

## Acceptance Criteria
- [ ] Design file with content changes

## Deliverables
- [Landing Page Template](https://www.figma.com/file/iqjkZx2EbrZu6leL6YfN45/Cerner-Handoff?type=design&node-id=1902%3A9452&mode=design&t=SHNZdAhW29aMP2bI-1)
- [Landing page content matrix](https://www.figma.com/file/iqjkZx2EbrZu6leL6YfN45/Cerner-Handoff?type=design&node-id=1902%3A9457&mode=design&t=SHNZdAhW29aMP2bI-1)
- [Appointment List Template](https://www.figma.com/file/iqjkZx2EbrZu6leL6YfN45/Cerner-Handoff?type=design&node-id=1902%3A9455&mode=design&t=SHNZdAhW29aMP2bI-1)

**Comment by outerpress** [comment]
@Cieramaddox I'm handing this off to you. Next steps are:
* Get sign off from Coulton. I pinged him in [this slack thread](https://dsva.slack.com/archives/C03CGTDLTFF/p1693415565710399). Kristen can help with this.
* After that, @JRRoof can tell you what the priority is on this for updating the in-app message, and help socialize this with the public websites team for the SLP message.

Thank you!

**Comment by Cieramaddox** [comment]
Alright, we got the go ahead from Coulton. @JRRoof We're ready to rock and roll!
