### ISSUE TITLE
Request Custom Survey

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#65283]
### Survey Type Requested

Feedback

### Product Name(s)

Health Questionnaires (BHL and eScreening)

### Product Description

Behavioral Health Labs (BHL) and eScreening allow for customizable and standardized health forms, screeners, and questionnaires to be sent to the patient to collect responses asynchronously.

### Product URL(s)

These products aren't technically part of VA.gov, but they are part of the digital Veteran ecosystem.

### Launch Date

10-01-2023

### PRA Approval

Yes

### Custom Survey Questions

Where is the PRA approved list? There was no link where it says the link should be. I did review the Medallia User Survey Overview page and we are interested in some of those questions, but also some others. However, we would like to talk to your group about our options.

Were you about to complete your task today?
- Yes
- No

What is your overall satisfaction with this experience?
- 1 = Very dissatisfied
- 5 = Very satisfied

What was your understand of what was being asked of you throughout the process?
- Whatever 5 point Likert scale is approved

How easy or difficult was it to complete this experience?
- Whatever 5 point Likert scale is approved

Information about signing up for a longer interview with link to OCTO user research sign up form.

**Comment by kristenmcconnell** [comment]
We met with VEO this morning to kickoff this project. We have next steps to work with them next week to finalize questions.

**Comment by clantosswett** [comment]
@kristenmcconnell thanks for this update. It sounds like you all are working directly with VEO to implement this custom survey. Do we need to keep this issue open for tracking purposes or can we close since this team will not be providing implementation?

**Comment by kristenmcconnell** [comment]
You can close this ticket. We have made a lot of progress working directly with VEO.
