### ISSUE TITLE
FE | Profile | Remove VAModal React component from VAPServiceEditModal

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/va.gov-team#65289]
## Issue Description
Micah Chiang contacted us with an inquiry into deprecating the usage of the `Modal` react component in [VAPServiceEditModal](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/user/profile/vap-svc/components/base/VAPServiceEditModal.jsx#L106). 

[Here is the slack thread for context.](https://dsva.slack.com/archives/C053JC66YHF/p1694189661801899)

## Front end tasks
- Mini discovery to determine whether the VAPServiceEditModal can be removed altogether or if we should just migrate to the web component version `va-modal` in the current component. A search revealed that it looks like this component and several others may actually be old and _could_ potentially be deleted altogether.
- Remove component or migrate to va-modal web component
- Update unit tests and e2e tests around this work

## Acceptance Criteria
- [x] Deprecated react VaModal removed
- [x] Unit tests pass
- [x] E2E tests cover current code and regression
- [x] End-to-end tests show 0 violations.

**Comment by adamwhitlock1** [comment]
This is in PR and has one approval. I am waiting till after the 30th / pact act deadline to merge this as to not cause any potential issues, mostly just because it is 1000 LOC change.

We can roll this over as effectively a 0 or 1 pt ticket

**Comment by mtcA6** [comment]
are you able to merge this today/tomorrow? do you need me or @Dottifacilities @Dottisea to check? (tagging both dotti accounts that I see not sure which one is correct)

**Comment by adamwhitlock1** [comment]
This PR has been approved by all responsible codeowners and will be merged after todays daily deploy as I don't want to just push to prod on a friday.

**Comment by adamwhitlock1** [comment]
@micahchiang the PR for this has been merged and I will close this now.

**Comment by micahchiang** [comment]
@adamwhitlock1 - Thank you sir! Doing this was incredibly helpful to the design system team. We really appreciate it!
