### ISSUE TITLE
[SSO Launch] Availability & Monitoring; Alerts

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#6528]
- [x] Define availability 
- [x] Document this in product outline
- [x] Add health check monitor
- [x] Set up necessary alerts for team to find and investigate issues

**Comment by ericbuckley** [comment]
The changes made in the vets-api to support SSOe authentication (v1) have duplicated the same metrics being gathered in the current ID.me implementation (v0).  When an authentication request starts, the controller emits an [api.auth.new stat](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/controllers/v1/sessions_controller.rb#L27-L28) and upon completion it emits an [successful api.auth.saml_callback stat](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/controllers/v1/sessions_controller.rb#L178-L181) or [failure api.auth.saml_callback stat](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/controllers/v1/sessions_controller.rb#L182-L189).

The stats gathered here represent the same user authentication states that we are collecting in the v0 implementation, and thus allow us to reuse the existing [ID.me](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/prometheus/rules/external_service.rules.j2#L100-L106), [DS Logon](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/prometheus/rules/external_service.rules.j2#L108-L115) and [MHV](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/prometheus/rules/external_service.rules.j2#L117-L124) prometheus alert rules to monitor availability/failure rates.

**Comment by marriej** [comment]
Product Outline updated with above.
