### ISSUE TITLE
BE | Profile | Direct Deposit | Potential email notification issue

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#65299]
## Background
We're seeing the following message in our logs...

_Job arguments to VANotifyDdEmailJob do not serialize to JSON safely. This will raise an error in Sidekiq 7.0. See https://github.com/mperham/sidekiq/wiki/Best-Practices or raise an error today by calling `Sidekiq.strict_args!` during Sidekiq initialization._

Sidekiq is used to process background jobs for VA.gov.  Email notifications are sent whenever a user updates their direct deposit information.  Sending emails is a background job handled by Sidekiq.  We are currently using Sidekiq 6.5.7.

## Tasks
- [x] Fix serialization prior to 7.0 upgrade (unsure of upgrade plans)

## Acceptance Criteria
- [ ] Verify that the warning is no longer showing up in our logs when an update is made.
  - [ ] Staging
  - [ ] Production

**Comment by mtcA6** [comment]
@tpharrison is this related to EVSS> LH or just a general Direct Deposit issue?

**Comment by tpharrison** [comment]
Just related to DD.

**Comment by tpharrison** [comment]
Did a little research and [found this article](https://keygen.sh/blog/how-to-change-the-signature-of-a-sidekiq-job/).

**Comment by mtcA6** [comment]
That's not how i expected sidekiq to be spelled...
