### ISSUE TITLE
SOCKS access for Patrick Black

### ISSUE THREAD

**Issue by patrick-black-oddball** [department-of-veterans-affairs/va.gov-team#65307]
### Your Name

Patrick Black

### Your Email

patrick.black@oddball.io

### Your Role and Team

DevOps Engineer - Reliability Team

### Product Manager (PM) name and email

Amber Malcolm

### Product Owner (PO) name and email

amber@oddball.io

### Access Type Requesting

platform

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDGBzJLwPgYbomG9Eh/lyd6pUczfn2bNlzvP4A9b5V8krSE39rArv4nxfIzymfPj+cOtksisGgipyXyCrnS/sd0QmXXgfC35W2tMT7IWvpYiek9/C0qcKVxpX8XBH+iTyaVSEKXcgj2YFoaAoomn/1B+iuw1iECStIYQa8/ON0SB3gxyYHkrZ8m+Mtt3eLDNldRRJ28rvciB9l2OzkicDSXDfJnzot1me0I7TUzGu7YxL6kVR39q3H4XmIVRttvfIxizJgCdxnBHstSTEoc4bQzM9wLdU+ZEoNbMjOTQzAZbzpNS4pStc2A8xU7PKThq/Mzf5u8gSQz8X5r8NCdtyqUPfyaFYOsQCS5rPuBU7P+eea+ga0ZpOTUvWNcP7U7C3JobdwhaoIOG5FQE+dvbDHxdsxdL6OTHzu/woLpIifSHShMXAVqjtnipFRShexk7J3a1ifwWx15ZgRXt9WGUmOgUu6YlNokKm8izEKjZ4IoRXSi441gjk/ahraM9dJHWSs= patrickblack@Patricks-MacBook-Pro.local

### E-QIP Transmittal Confirmation

<img width="943" alt="Screenshot 2023-09-11 at 1 03 36 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/141665052/2451b2ac-c8c9-471f-abe9-8feff2873369">

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by patrick-black-oddball** [comment]
Please look for me under the Reliability Team

**Comment by patrick-black-oddball** [comment]
I am on the Platform team - apologies if the wrong team was selected in the ticket. https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster

**Comment by ben-allen-oddball** [comment]
SOCKs access has been provisioned.
