### ISSUE TITLE
Create Health Check for SFTP

### ISSUE THREAD

**Issue by flooose** [department-of-veterans-affairs/va.gov-team#65313]
We [currently don't have any monitoring](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/application/README.md#monitoring) for SFTP connections, [although we do have errors from time to time](https://dsva.slack.com/archives/CBU0KDSB1/p1694430712845429) that we'd like to understand better.

Per @LindseySaari there is a Spool file that is sent to Central Mail server (?) that fails periodically. There is a retry function that attempts to resend the file if it fails. The team needs visibility into why it fails, so that a fix can be put in place to keep the failure from happening.

**Comment by jennb33** [comment]
8/14 update: per @flooose the Health Check has been created, and he is completing documentation for the work.

**Comment by flooose** [comment]
This monitor already exists in the standard [forward proxy monitors](https://vagov.ddog-gov.com/dashboard/ae4-qch-6vw/forward-proxy?fromUser=false&fullscreen_end_ts=1723569412765&fullscreen_paused=false&fullscreen_refresh_mode=sliding&fullscreen_section=overview&fullscreen_start_ts=1723483012765&fullscreen_widget=8979994292561720&refresh_mode=sliding&view=spans&from_ts=1723482987800&to_ts=1723569387800&live=true). It's name is "tims_back", but it took some research to verify that this is the correct monitor because the [TIMS team _uses_ the SFTP server](https://dsva.slack.com/archives/CBU0KDSB1/p1723554969503269?thread_ts=1694430712.845429&cid=CBU0KDSB1), but the TIMS service and the SFTP server are not the same thing. The following steps were taken to get clarity on this:
1. We used the VA [inventory of services](http://vaww.ea.oit.va.gov/enterprise-architecture/va-systems-inventory/) to clear up any confusion between PITC and TIMS, the former being a whole data center, while the latter is a traditional web service.
2. We used the profile page for the TIMS service in this list to determine where TIMS is hosted.
3. We used the IP address listed for SFTP in the forward proxy config to match it to a row in the [table that matches them to data centers](https://github.com/department-of-veterans-affairs/devops/tree/master/docs/System-Locations.md#L20). According to the table, the SFTP server is in a different location than TIMS.

In doing the above, we were able to determine that the "tims_back" healthcheck is actually a healthcheck for the SFTP server. The two services exist in two separate locations."
