### ISSUE TITLE
Error handling when calling SuS API

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#65315]
## Problem Statement
SuS API and/or IAM provisioning may not respond in a timely manner when a user attempts to login to VA online services and benefits through the VA.gov USiP.
## Solution

- When a user logs in and vets-api attempts to check SuS api for terms of use and cerner provisioning related items and vets-api does not get a positive response back from the SuS api, VA.gov MUST show the user the ToU page.
- If a user is attempting to access My VA Health (Cerner) and we do not get a positive response from the SuS API we must redirect the user to an error page which indicates that either Cerner is having issues or they are not eligible to access cerner. We should already have an error page that lists similar to this but it may not cover "sus api didnt respond and you attempted to access Cerner and we cant send you there unless we know for a fact that you are eligible"

**Comment by bosawt** [comment]
We will not be currently blocking auth based on responses from Sign Up Service with our current flows, so I think this is tentatively good for now
