### ISSUE TITLE
Vets-api terminal access for Lihan Li

### ISSUE THREAD

**Issue by lihanli** [department-of-veterans-affairs/va.gov-team#65323]
### Your Name

Lihan Li

### Your GitHub handle (terminal access is managed through GitHub)

lihanli

### Your dsvagovcloud AWS user name (if applicable)

Lihan.Li

### Team, Role, and Company of the target individual

1010 health apps, Backend Engineer, Ad hoc

### Product Manager (PM) name and email

Heather Justice heather.justice@adhocteam.us

### Product Owner (PO) name and email

Patrick Bateman patrick.bateman@va.gov

### COR Name (leave "None" if you listed an AWS user name above)

None

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

None

### Please confirm if you are on the VFS Team Roster or Platform Team Roster

- [X] [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Please confirm E-QIP Transmittal/Adjudication. This could be a screenshot of your Transmittal/Adjudication email, a link to another request where you've submitted this proof (i.e. AWS/SOCKS), etc.

- [X] I have attached proof that I have either transmitted my E-QIP survey or previously received a favorable decision (by including in "Additional Notes" section below)

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### Additional Notes

I would like access to all environments in order to diagnose any problems that may occur with my team's backend APIs. I previously had access to all environments before the eks migration. Thanks!

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/830084/eabfce5b-f9cb-4355-8163-6dd54472e73b)

### Additional resources for Support Engineer

- [ ] For users on a VFS team but not in the VFS Team Roster, they must start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] Instructions for handling requests [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access) - Support Only

**Comment by bdech** [comment]
Found in VFS Team Roster

**Comment by bdech** [comment]
You’ve been granted access to the `dev`, `staging`, and `sandbox` environments.

Here's some additional documentation for [Vets API on EKS](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-TerminalAccess) that may help.

**Comment by bdech** [comment]
Access to `prod` is pending OCTODE approval.

**Comment by bdech** [comment]
@BillChapmanUSDS for visibility

**Comment by BillChapmanUSDS** [comment]
Access approved as per current policy

**Comment by bdech** [comment]
@lihanli You've been given access to `Production` limited to 6 months, expiring 03/14/24. Please set a reminder for yourself to return to this Issue and re-request access within 1 week of the expiration date. You'll receive 1 reminder with a 72 hour window to respond. Failure to do so will result in lost access and will require you to fill out a new request.

**Comment by bdech** [comment]
Slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1694720210773279)

**Comment by bdech** [comment]
no response, production access revoked.
