### ISSUE TITLE
[SSO Launch] Create Phased Release Plan

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#6533]
VSP Template: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/release-plan-template.md

Note that moderated release speaks to our ability to do UAT with real users, #6526

**Comment by marriej** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/sso/staging-review/release-plan.md
