### ISSUE TITLE
EVSS Maintenance Windows comms with support

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#65336]
### ACTION ITEMS
- [ ] Ensure EVSS was able to delay the maintenance window -- checking with Bill

### DEFINITION OF DONE

https://dsva.slack.com/archives/C05Q1A58Y1L/p1694463028819559?thread_ts=1694440132.581139&cid=C05Q1A58Y1L

**Comment by LindseySaari** [comment]
Have a calendar invite for this on Thursday to review the maintenance windows
