### ISSUE TITLE
[SSO Launch] Request and Complete Security Review

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#6534]
VSP process to request review: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#privacy-and-security-review

**Meeting Scheduled for March 26 3pm PST/6pm EST.**
https://github.com/department-of-veterans-affairs/va.gov-team/issues/6823
Artifacts Required due 3/24:

- [ ] An architecture diagram, showing involved systems + data flows
- [ ] Description of any new publicly-exposed endpoints (vets-api or otherwise)
- [ ] Description of any new interactions with dependent services (i.e. vets-api --> ???)
- [ ] Description of any other security hotspots you're concerned about / want extra attention on

Topics that VSP will ask us to speak to:
- [ ] Users' private data is safe, including not logging PII
- [ ] Feature doesn't introduce new vulnerabilities
- [ ] Playbook exists on most likely failure modes and how to respond quickly to issues

**Comment by marriej** [comment]
Security review complete. See #7299 for after actions
