### ISSUE TITLE
Request access to Domo

### ISSUE THREAD

**Issue by tayism** [department-of-veterans-affairs/va.gov-team#65355]
# Request Google Analytics and/or Domo access

## What this form is for
Use this template to request access to Google Analytics and/or Domo. Please complete steps 1 & 2 below. 

## 1. Access Requirements 
Please check the analytics tool(s) you need access to:
- [ ] Google Analytics
- [x] Domo
- [ ] (Platform Teams only) BigQuery

I will need edit access, particularly to [this page](https://va-gov.domo.com/auth/index?redirectUrl=%2Fpage%2F256231568)

 
---

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by tayism** [comment]
@ChristineYoungZA ah -- I think my teammate invited me yesterday, but I only have access to "Buzz" and not any dashboards from what I can see.

Is there a higher level of access I could be granted? Thanks.

**Comment by ChristineYoungZA** [comment]
Hey @tayism I changed your permissions from Social to Member. Please let me know if your are still not able to access the dashboards.

**Comment by tayism** [comment]
@ChristineYoungZA it works perfectly now. Thanks so much!
