### ISSUE TITLE
SOCKS access for [Robert Perea-Martinez]

### ISSUE THREAD

**Issue by Robperea** [department-of-veterans-affairs/va.gov-team#65363]
### Your Name

Robert Perea-Martinez

### Your Email

robert.perea-martinez@adhocteam.us

### Your Role and Team

Product Manager on Team Firefly - Benefits Documents API

### Product Manager (PM) name and email

robert.perea-martinez@adhocteam.us

### Product Owner (PO) name and email

Janet Coutinho,  janet.coutinho@va.gov

### Access Type Requesting

viewers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC5J7JsfNupVPvkNrL4PlH+XHSniI/MV27idc5a+DtXGhbpFTBAedcfZ0AcL3Za9VntLBgoiIfNeyOv5bRRPA1kKL6SzVDwklTplH61gn9NSfrCNa8nOINZO53U2IuAg72fEca/0V02ZuK5QD6X67bdxsvRDRy1zcsF+t8285uRWpajOkKpjPkXPpkTBX2bAcP6Qq8+6KrQdYWKT3iFFRB9fScLYhzmgToSZO+uGAhbs+DihntpcN85dEeUn23cM1ZX1mR/2RXHSA7eAMM4zunnTPph9v/PzkgwwYjNSxsGzn+pXfe/B3f+YPe2y2qaGH2ORKz0418OvMBzpuJRupI6Zt8QThBcScyR4xKk/GHiruP8YAqD3TRZ04UgNzjI4mUTCVSBzOMz4bWVaTRjlLSWQQsAGiUC/0q8pNTen8ZYNqSIrGnCHufC6pz7LPPM1HO9RpST3+UioZ2hlxqxzM0yuU9sgaAChjf8Zt8p4N3UmoXiUrHIrEKmbHjXQuyT6CU= robertperea-martinez@robertperea-martinez-C02GL0XF0KPF

### E-QIP Transmittal Confirmation

<img width="1182" alt="Screenshot 2023-09-11 at 6 33 58 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/46360557/7de2be1f-d826-4a0c-b57a-ecefbc185687">

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by ben-allen-oddball** [comment]
Re provisioned socks access.
