### ISSUE TITLE
[UX] Placeholder for add group pre-check-in scenarios to Design page

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#65360]
Will fill out

Based on [Priority 4](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/02263A22-DB44-4877-A22A-EE8F5C33FDA9/canvas)

**Comment by loripusey** [comment]
@benbrasso-agile6 I'm going to move this to Priority 4 epic

**Comment by benbrasso-agile6** [comment]
Guess I should try to fill out this description
