### ISSUE TITLE
Business intake form for Benefits - dependency failures

### ISSUE THREAD

**Issue by emilytheis** [department-of-veterans-affairs/va.gov-team#65376]
## Your Details
1.  **Emily Theis**
​
2.  **Business Line**
    Benefits
​
## Notification Details
1.  email
​
2.  **Please describe your use case.**
Over the past few years, a number of dependency claims submitted on va.gov failed to establish -- either the claim data or the PDF uploaded to VBMS (claims adjudication software). An OIT/VBA team is working together to remediate these past cases, and we'll need VA Notify's help communicating to affected Veterans to ensure theme their application is being reviewed. This is very similar to the recent remediation project for missed 526 disability compensation claims.

3.  **What actions can the user take based on the notification they receive?**
I expect the notification to be similar to what was sent for 526 -- an FYI, no immediate action needed. 
​
4.  **What is the desired business outcome?**
Assurance that past errors on va.gov are being reviewed and every Veteran's attempt will be made whole. 
​
5.  **What system will kick off the notification? Please note the system should be inside the VA or have an ATO.**
I'm not sure!
​
6.  **What will trigger the notification?**
VBA deciding to send the batch notification
​
7.  **Provide sample content per notification type, if you have it.**
VBA currently working on the letter notification, happy to share it 
​
8.  **Has a Privacy Officer (PO) seen and approved the content? If not, do you know who your PO is?**
Not yet

9.  **Would you prefer to provide contact information for the recipients or would you rather VA Notify look this up for you by Veteran ID? If by ID, please let us know what identifier is used in your system.**
We can provide it. We have SSN at minimum, but may be able to provide more depending what you need. 
​
10.  **Do you currently capture communication preferences related to this notification? If so, please describe.**
No
​
11.  **What is the anticipated volume of notifications per day, week, month?**
Expected ~50k, possibly in batches
​
12.  **When does this notification need to be in production?**
No firm timeline, but there's an active "code yellow" to remediate these issues, so I expect when the letter content is ready and VBA has confirmed the list of affected Veterans, folks will be eager to move forward this fall.

**Comment by mjones-oddball** [comment]
I saw a note that Kyle is OOO, returning on the 19th

**Comment by mjones-oddball** [comment]
@emilytheis Hi, just checking in to see if this intake is still active. Would you like to kick off onboarding?

**Comment by mjones-oddball** [comment]
@emilytheis I'm going to move this to Icebox since there hasn't been any movement on it since September 2023. If that changes and you want to re-engage please just reply back!

**Comment by steele-lm** [comment]
@mjones-oddball I think this ticket can be closed bc it's now covered by this new request #95478

**Comment by mjones-oddball** [comment]
@steele-lm thanks for the update! Closing as duplicate
