### ISSUE TITLE
[SSO Launch] Request Staging Review

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#6537]
VSP process: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#staging-review

Artifacts required:

- [x] [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/sso/README.md)
- [ ] [Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/sso/staging-review/release-plan.md) 
- [ ] Test Plan in TestRail w/ test results
- [ ] Coverage for References and Summary(Defects) reports in TestRail for QA practice area review
- [ ] [Accessibility Test Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/sso/staging-review/accessibility-plan.md)

**Comment by marriej** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/6925

**Comment by marriej** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/sso/staging-review
