### ISSUE TITLE
CRUD Actions for Atlas users

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#65381]
### User Story
As a member of the governance team, I want to have CRUD (Create, Read, Update, Delete) functionality for managing Atlas Users and their associated members and roles in the UI so that I can easily maintain team information without relying on the VFS Roster spreadsheet and maintaining current spreadsheet functionality in the rails app.

### Acceptance Criteria

- [ ] Create: Admins should be able to create a new Users under ProductDirectory through a form in the UI.
- [ ] Read: Admins and users should be able to view a list of all Users in ProductDirectory.
- [ ] Update: Admins should be able to update the details of existing Users through the UI.
- [ ] Delete: Admins should be able to delete a User from ProductDirectory.
- [ ] When creating a ProductDirectory::Team, there should be a dropdown of existing Github Teams to associate with.
- [ ] Implement appropriate unit and integration tests to cover new functionality.

### Definition of Done
 **All Acceptance Criteria are met.**

- [ ]  Unit and Integration tests are written and pass successfully.
- [ ]  Code has been reviewed and approved by peer reviewers.
- [ ]  Functionality has been manually tested to ensure it meets the user story requirements.
- [ ] Additional Notes
- [ ] The governance team will be using this feature as a replacement for the VFS Roster spreadsheet, so it's important that it is both robust and user-friendly.

**Comment by RachalCassity** [comment]
This was just created today (9/12)

**Comment by RachalCassity** [comment]
Move to next sprint please

**Comment by laineymajor** [comment]
This will be done very soon; just after the RSpec work
