### ISSUE TITLE
[SSO Launch] Contact Center communications

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#6538]
The Contact centers need 2-4 weeks to review all changes made to the user experience on VA.gov, so that if Veterans call with questions, they can offer the right guidance.

Process for updating the contact center: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/call-center/request-contact-center-review.md

- [x] Set up initial call with Chante to see what is needed
- [x] Create product guide
- [ ] Create product video
- [ ] File issue for review, following instructions from link above

**Comment by marriej** [comment]
Product Guide (in progress):
https://docs.google.com/document/d/1gG6Ph1xvAYJ9Ith6RA5_F7i-ujYECX0U6j_NfQx-T-U/edit

**Comment by marriej** [comment]
Product guide sent to Chante (via Slack), no further action required.
