### ISSUE TITLE
MVP - Add terms of use logs

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#65408]
Currently have logs with `TermsOfUseAgreement ` and some relevant data, but we'll need additional logs. 

Will need to clarify exactly what info we need from the additional logs and where

**Comment by bosawt** [comment]
We have logs for accepting/declining terms of use, and we have logs when we have exhausted retries with the Sign up Service which we can use to generate reports for them.

@joeniquette  Any other logs we need?

**Comment by joeniquette** [comment]
closing this ticket as we have a ticket for each of the two remaining tasks
