### ISSUE TITLE
FE | Editing-as-a -subtask | Letters should not be allowed for phone number fields

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#65410]
## Issue Description

Current validation rules permit letters in the phone number input. We need to correct this with some regex to prevent alpha characters but permit numeric and some symbol characters (eg. `(` , `)`, `-` )

## Front end tasks
- Add validation for letters in the phone number field - specifically mobile number for the edit as a subtask, but this will also apply to other phone number fields as well.

## Acceptance Criteria
- [x] Phone number field doesn't allow saving with letters or invalid characters present besides - ( ) and numbers

**Comment by mtcA6** [comment]
Adam asked on 9/14 standup about the language we're using for the error message for the in-line validation rule. Adam is going to check in the code to see if there is some sort of verbiage out there that mirrors what we need. 

We created the below ticket and will add this in as unplanned work to the current sprint but will not pick this up unless Adam is unable to find suitable language in the system already. 
- Design | Editing-as-a-subtask | In line validation error message

**Comment by mtcA6** [comment]
Guidance from content is to phrase the warning: "Enter a 10-digit phone number"

**Comment by adamwhitlock1** [comment]
I spent some time trying different things, and it seems to boil down to a few validation cases that I can't get past.

just entering 10 digits is doable, and showing an error for any letters AND any other symbols including ( ) - works, but then causes the issue that it doesn't allow those extra symbols.

I seem to get a regex validation pattern to work for numbers and dashes, but when I try to accept parens as well then it seems to fail to validate altogether.

I will roll this over to next sprint, but wonder if we could just accept numbers, or numbers and - only?

**Comment by mtcA6** [comment]
@adamwhitlock1 think this will be completed ahead of staging review Friday?

**Comment by adamwhitlock1** [comment]
This ticket can now be validated @Samara-Strauss, @Dottifacilities, and @mtcA6 

Steps I used to validate in staging:

- Log in with a staging user like 202
- View the url: https://staging.va.gov/profile/edit?fieldName=mobilePhone&returnPath=%2Fprofile%2Fnotifications
- Add a letter to the field for the mobile phone, verify that you cannot save the field with a letter or any character other than `- ( ) spaces` or numbers in the field
- Verify that when you add a letter and attempt to cancel the edit, that you see a modal confirming that the user indeed wants to cancel the in progress edits.

**Comment by Samara-Strauss** [comment]
Validated with user 226! 
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/34068740/cf292924-3bbe-446a-85fb-66b800b589fe)

I recommend that @Dottifacilities still validate this ticket, as it would be good practice to get used to our products and what they can do!

**Comment by adamwhitlock1** [comment]
@Dottifacilities were you able to take a look at this to validate? Should be good to close this ticket, but just double checking?
