### ISSUE TITLE
Follow Up on Removal of COR Section on AWS Access Requests

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#65438]
This initiative was created out of the research done in this ticket: https://app.zenhub.com/workspaces/platform-tech-team-support-634ebbcc35e2bc0015b382fd/issues/gh/department-of-veterans-affairs/va.gov-team/61515

On hold until we receive further information from Clint (some meetings needed).

**Comment by alyssagallion** [comment]
Follow up with Clint to identify if this will be nixed.

**Comment by bdech** [comment]
Spoke with Clint on this. We are going to close this out. There are some security concerns regarding removing COR from these access requests.
