### ISSUE TITLE
Letters App: Fix layout when no address is on file for the user

### ISSUE THREAD

**Issue by ndsprinkle** [department-of-veterans-affairs/va.gov-team#6544]
## What happened?
In the letters app on the confirm address page, the UI for when there isn't an address on file for the user displays some contradictory and confusing information. The screenshot below demonstrates this. It may be as simple as removing the text below the information message, but the front end engineer who works on this should still meet with a designer to discuss.

![image](https://user-images.githubusercontent.com/53942725/75924093-56746380-5e34-11ea-8df3-83bed979b036.png)

## Steps to Reproduce
- URL: https://staging.va.gov/records/download-va-letters/letters/confirm-address

## Acceptance Criteria
- [ ] The UI is reworked for when users do not have an address on file to remove contradictory information

**Comment by kevinstachura** [comment]
Spoke with @ndsprinkle about this ticket - I recommended we remove the text beneath the alert box. For the text _within_ the alert box, I recommended we link the words 'update your address' to the user's profile so they know where they can go to remedy the issue.
