### ISSUE TITLE
IA Guidance: Document standards for benefit hub page template

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#65451]
We need to establish standards for the existing benefit hub page template. 

The short term goal of this work is to document the general standards and guidance we use to determine what content and links belong on the benefit hub pages, and where they belong.  As well as guidance around how we decide if something should be added or removed.  

An initial draft of this was done several years ago in Moqups, and a screenshot of that information has been moved into Mural to start the process. 

https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1694550504118/9ab9423b7a907602411017fd5a5fbff952ebc8bd?sender=u2aba00c97ab77c6ec1573123

For each section of the template, we need to establish
- a definition of each section, including whether it is required/optional, what constraints the section has, what elements should be included, and any other general information
- what content/links belong in the section and what does not
- what order should the content/links be in and how information should be prioritized
- any accessibility considerations with the features/functionality of the section

Final information should then be reviewed for placement within the design system, so [the template page on design.va.gov](https://design.va.gov/templates/hub) will need to be reviewed. 

Sources of information that can be used
- IA hub audits
- analytics
- [content placement criteria](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/content-strategy-ia-collaboration/content-placement-criteria/content-placement-criteria-v1.md)

Note:  This will establish a current state for this template.  There is intention to evolve this for other work, and this will help establish what we are currently working with and where we think we need to evolve.  

We will need to review the final information with various OCTO leads before implementing in the design system. 
```[tasklist]
### Tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/74090
```

**Comment by kristinoletmuskat** [comment]
Pulled this in and documented first pass here: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1694550504118/9ab9423b7a907602411017fd5a5fbff952ebc8bd?sender=ua641db233dc545173f8d9816

**Comment by kristinoletmuskat** [comment]
Blocked by Mikki getting feedback from Beth/Danielle/Matt Dingee.

**Comment by kristinoletmuskat** [comment]
Opening because need to add; 

Also want to create a rubric for how we determine things that appear
Page views, but also other things like stakeholder or veteran journey importance
Because some tools are one and done, others are continuous, which would impact the analytics

**Comment by kristinoletmuskat** [comment]
Link to draft of proposed changes to VADS page: https://docs.google.com/document/d/1Ojr6OCIH3CGWG-auQf7N2Gk-D2_eaI1g0fpSoLpv0jg/edit

@erinrwhite and @mnorthuis this is ready for your initial review.

**Comment by mnorthuis** [comment]
@kristinoletmuskat I started reviewing this, got through the first spoke.  The general changes I have made so far are mostly related to:
- Removed reference to the content placement criteria for now to avoid links to git hub, but eventually we will have an IA/site organization section on VADS that we can refer to where appropriate.
- Removed references to the foundations section, which seems less applicable to me than the actual component used.  I believe when this was first created we didn't have a lot of components. 
- Modified content to follow our writing guidelines - i.e. identity first language, removing "the" from in front of VA, etc.   We could ask an editor to help with some of this when we are done. 

Take a look and let me know if the changes make sense. Hopefully you can follow those through the other sections.

**Comment by kristinoletmuskat** [comment]
@mnorthuis just went through and made the suggested edits!

@erinrwhite I believe this is ready for your initial review! Feel free to leave comments directly in the doc.

**Comment by erinrwhite** [comment]
@kristinoletmuskat looking good! I made a few small formatting changes. For the spoke section guidelines, since we are including these bullets in each spoke, can we elevate this guidance on the page and say that it applies to the entire page?

**Comment by kristinoletmuskat** [comment]
Hey @mnorthuis and @erinrwhite , I've reviewed and addressed all of the feedback so far. We got an a11y review on our initial proposal in Mural, but might be worth getting another one, plus a content review for style? Do those sound like the next steps to you?

**Comment by mnorthuis** [comment]
@kristinoletmuskat Added a few minor comments.  Let's create supporting images similar to what's used in the forms section of templates.  We can get design assistance if needed.

**Comment by kristinoletmuskat** [comment]
@mnorthuis I made updates based on your last round of comments. Do you mean a single image for the whole VADS page that's the same as the one I created in the WIP, but using the visual style of the one on [this page](https://design.va.gov/templates/forms/how-to-apply)? The forms template has a different image for each of the 4 pages in a form flow, and each of those images is a different type (2 different types of annotated screenshot and 1 wireframe).

**Comment by mnorthuis** [comment]
@kristinoletmuskat Finished reviewing and simplified a few things along the way.  Take a look and let me know if there are questions/feedback.  Once all changes are accepted/modified, let me know, I want to review this with a few OCTO peers next.

**Comment by kristinoletmuskat** [comment]
Just adding a note that we finalized a draft and Mikki is currently reviewing with OCTO

**Comment by mnorthuis** [comment]
Hub template guidance is good to go and final is attached below.  Please add a mobile view of the hub page along with the desktop with the same numbered call-outs.  Thank you!

[hub-template-standards.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3poQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8d47927b76d00d4d39ee721979af9d655ea648b9/hub-template-standards.docx)

**Comment by mnorthuis** [comment]
Next step is for @kristinoletmuskat to create a mobile view to add to this and for @erinrwhite to create a PR.   

@erinrwhite please reach out to @kristinoletmuskat and @samw-va if you need assistance moving this out of word and into markdown.

**Comment by kristinoletmuskat** [comment]
Hello! Here is the mobile version with callouts

![Image](https://github.com/user-attachments/assets/240ef35c-0f26-4245-aa07-70df4bc5640a)

**Comment by erinrwhite** [comment]
Hi team, I have the draft page updated on my machine and I'm not quite sure about best placement for the mobile screenshot. It's very long, and I *could* align it left or right alongside the content but it seems a bit hacky. Recommendations welcome. @mnorthuis @kristinoletmuskat 

![Image](https://github.com/user-attachments/assets/d16145f9-2059-4615-b552-fd8af6b47168)

**Comment by mnorthuis** [comment]
I think we should direct a question to the design system team on how they want screenshots like this to be handled.  We need to include mobile view but I don't want to have to scroll for an hour to get to the guidance.   @erinrwhite can you ask the DST their thoughts?

**Comment by erinrwhite** [comment]
[Pull request submitted](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/3481)!

I ended up breaking up the mobile screenshot into three chunks, to correspond with the sections (intro, spokes, right rail). Design as pictured below. Over to @mnorthuis for approval.

![Image](https://github.com/user-attachments/assets/ee5c103e-f0eb-4386-af2a-19ea453f8053)

**Comment by mnorthuis** [comment]
PR was merged 12/3.   

@kristinoletmuskat if you want to do a final glance on VADS for this one go for it, otherwise this work is done!
