### ISSUE TITLE
VCR Retro & Future Guidance on Platform Website

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#65497]
Problem statement
VCRs were helpful, but there were also a number of issues. If we use them again, we want to be sure we have lessons learned documented.

Action items:
- [x] Rebecca, Ryan, and Lindsey meet to discuss areas of improvement
- [x] Rebecca document in confluence

DoD
- [ ] Page is published on Platform website and linked here

**Comment by laineymajor** [comment]
Work will continue on this during our part 2 of the double sprint.

**Comment by rmtolmach** [comment]
Document started for VCR guidance: https://vfs.atlassian.net/wiki/spaces/~121859534/pages/2893611114/VCR+tips

Meeting set for tomorrow with Lindsey and Ryan.

**Comment by rmtolmach** [comment]
Met with Lindsey and Ryan to work on the document. 

Next steps: polish it up and make it ready for the Platform website! I'll get another review and then I'll place it in the Developer Docs section of the platform website. In the Backend section.

**Comment by rmtolmach** [comment]
✅ I made edits to the document and moved it in the the Developer docs Confluence space. The doc can still be reviewed and edited and _if_ it passes all of the content checks at 3pm today, it will be published. I will close this ticket once the page is published to the platform website.

**Comment by rmtolmach** [comment]
🎉 page was published! It lives here: https://depo-platform-documentation.scrollhelp.site/developer-docs/vcr-debugging

And can be edited in the future here: https://vfs.atlassian.net/wiki/spaces/pilot/pages/2893611114/VCR+debugging
