### ISSUE TITLE
Datadog access request steps are circular

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-team#65507]
### Description
https://depo-platform-documentation.scrollhelp.site/developer-docs/get-access-to-datadog

These 2 steps seem to be a hoopsnake:
* Users request access to Datadog from DOTS through Jira DevOps
* Users receive an invite to [DOTS Okta](https://dots-va.okta.com/)

As a VFS team member (not on Platform), you can't get into JIRA Devops to make the request, if you're not already invited to DOTS okta. 

Thread with Dave Conlon / Adrian Rollett re: workarounds: https://dsva.slack.com/archives/C52CL1PKQ/p1694537162096629

I don't know the right way to get into Datadog, and can't provide any insight on exactly how this content should change. Someone will need to work with the Platform owners of Datadog in order to figure that out. 

### Which type of team are you on? (Platform team, VFS team, or Leadership)
VFS

**Comment by jilladams** [comment]
Workaround that worked before also here: https://app.slack.com/client/T03FECE8V/C01U8EYHSEM/thread/C01U8EYHSEM-1692294886.936219

**Comment by jilladams** [comment]
atinuke.ogunbiyi@va.gov has provided some users with access to workaround this issue, and I've asked for clarification about the process for VFS teams here: https://dsva.slack.com/archives/C01U8EYHSEM/p1694635099302999

**Comment by jilladams** [comment]
Attempting a Platform support request based on a tip from Nathan Peterson: https://dsva.slack.com/archives/CBU0KDSB1/p1695142851536839.  If that works, docs should probably be updated to point VFS users to this route to access.

**Comment by vbellissimo** [comment]
Hi @jilladams thank you for helping us put these pieces together and flagging. I'm asking around within Platform to navigate how to get this sorted out.

**Comment by jilladams** [comment]
Based on https://dsva.slack.com/archives/CBU0KDSB1/p1695316147717339?thread_ts=1695142851.536839&cid=CBU0KDSB1, you will need to talk to @little-oddball  to figure out what the approved Platform process is to get new users access who are VFS teams. I'm outside of the Plat team, so I don't know the answer there.

**Comment by laucon** [comment]
@jilladams After talking to Clint and getting his approval, I put this note into the document. Hopefully that will work as a good temporary solution until OCTODE can fix the hoopsnake. It should be deployed Wednesday at 3:30pm. :) 
<img width="1345" alt="Screenshot 2023-10-03 at 3 56 52 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/14806304/e43059b9-422b-40fa-92f6-48b8e5434d07">

**Comment by vbellissimo** [comment]
@jilladams We will be closing this ticket as part of the short-term solution noted above and creating a backlog item to update the instructions once Platform is able to get more updated information from the VA about the Datadog access process in general.
