### ISSUE TITLE
FE | Direct Deposit | Update field order and address a11y issue

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/va.gov-team#65506]
## Issue Description
Change order of fields in direct deposit to be

Account type (as radio instead of select input)
Routing number
Account number
Where can I find these numbers? Additional info accordion

Wrap the fields in a div that includes a role and aria-label like this:

``` html
<div role="group" aria-label="Edit bank account for disability compensation and pension benefits">
```

More context in [this original ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19961).

Once this is up on a branch, then review with CAIA to validate.

## Front end tasks
- Ensure the page is styled according to design spec. 
- Ensure the back end data from API is displayed in local and review instance
- Ensure unit tests are available. 
- Ensure your code changes are covered by E2E tests
- Run axe checks using the Chrome or Firefox browser plugin
- Test for color contrast and color blindness issues
- Zoom layouts to 400% at 1280px width
- Test with 1 or 2 screen readers
- Navigate using the keyboard only

## Acceptance Criteria
- [ ] Designer comments on this issue to approve page styling 
- [ ] Unit tests pass
- [ ] E2E tests cover current code and regression
- [ ] End-to-end tests show 0 violations.
- [ ] The data returned matches API response (for given user or scenario)
- [ ] All axe checks pass
- [ ] All color contrast checks pass
- [ ] All zoom testing passes
- [ ] All keyboard checks pass 
- [ ] All screenreader checks pass

**Comment by mtcA6** [comment]
on our planning call on 9/13 we discussed working this ticket with #64204

**Comment by adamwhitlock1** [comment]
@mtcA6 this is ready to validate with CAIA folks. I will reach out to them tomorrow, but if you would like to double check my work on staging you can see the field order changed and the radio button group was also added. This applies to both comp/pen direct deposit and the education direct deposit forms.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzFxQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e9082475540fb4bde0cd02260caa9a900f1d53ec/Screenshot%202023-10-24%20at%205.45.01%20PM.png)

**Comment by mtcA6** [comment]
@adamwhitlock1 don't forget to invite @andaleliz to the meeting w/CAIA, hoping this allows us to close out that aged body of work!

**Comment by adamwhitlock1** [comment]
@andaleliz I met with Eli from CAIA while you were out last week, but I can fill you in on our meeting. Overall this is much improved and we can close this out now!

**Comment by andaleliz** [comment]
@adamwhitlock1 that's so great to hear, thanks for the update! So stoked to hear this is improved, and we can close this out. Thanks for your work on this!
