### ISSUE TITLE
Business intake form for [Benefits, NOD failures]

### ISSUE THREAD

**Issue by pshahVA** [department-of-veterans-affairs/va.gov-team#65509]
## Your Details
1.  Sade Ragsdale
​
2.  **Business Line**
    Benefits Crew
​
## Notification Details
1.  **Notification type**
    email
​
2.  **Please describe your use case.**
  There was an error on the NOD (VA form 10182) during a deployment that caused an error when certain veterans tried to submit that form.  The error was that the page was stuck, and could not move forward.  
​
3.  **What actions can the user take based on the notification they receive?**
  Take them to a link to fill out the form again.
​
4.  **What is the desired business outcome?**
  Veterans that wanted to submit an appeal can file for one on va.gov.
​
5.  **What system will kick off the notification? Please note the system should be inside the VA or have an ATO.**
    The VA.gov decision review team.
​
6.  **What will trigger the notification?**
    (ex., clicking submit, status updates for claims, appointment reminders, new services available)
    I think the decision review team will have to run a job that iterates through all the names.
​
7.  **Provide sample content per notification type, if you have it.**
    Please note we collaborate with all of our users on their content to ensure it meets standards.
​Not yet. 
8.  **Has a Privacy Officer (PO) seen and approved the content? If not, do you know who your PO is?**
    (ex., PO has seen the content but it is not approved)
Not Yet.
​
9.  **Would you prefer to provide contact information for the recipients or would you rather VA Notify look this up for you by Veteran ID? If by ID, please let us know what identifier is used in your system.**
    (ex., VAPROFILEID, PID, BIRLS, ICN, etc.)
We will have ICN for most records. We will have some records that only have an SSN (we can't find the ICN, or they may not be Veterans)
​
10.  **Do you currently capture communication preferences related to this notification? If so, please describe.**
    (ex., opt in for claim status updates via email or text)
​No
11.  **What is the anticipated volume of notifications per day, week, month?**
​Probably a 1-2 time batch of around 3500 records.
12.  **When does this notification need to be in production?**
We would like do do this in the next 2 weeks if possible.

**Comment by saderagsdale** [comment]
@bevnobev Hey Beverly! For this work:

- Can we test in a lower environment? (I think the answer is **yes** but wanted to check)
- Does VA Notify throw an error for undelivered emails?
- Can we track email status after sending (similar to how Survey Monkey works)?
- When the copy is ready, should we send it directly to you via email or this ticket?

**Comment by bevnobev** [comment]
Hey Sade! @saderagsdale 

> Can we test in a lower environment? (I think the answer is yes but wanted to check)
Yes.  When you are ready you can point your lower env to our staging environment.  We need to send you an api key, through encrypted email, so let me which of your engineers should receive the api key

> Does VA Notify throw an error for undelivered emails?
We don't through an error but we provide a delivery status for each email.  You can find out more [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-notify/README.md)

> Can we track email status after sending (similar to how Survey Monkey works)?
You can track open rates thru GA.  If the content will contain a link to a page on va.gov, we can track click throughs from the email to the page using Domo. Not sure if this answers your questions.  If not, can you elaborate more on email status?

> When the copy is ready, should we send it directly to you via email or this ticket?
We have a SSUI where you can enter your copy.  Let me know which team members need access and we can set you up.

**Comment by saderagsdale** [comment]
@bevnobev Hi Beverly! Can we download a report of hard bounce emails, so we know exactly which users don't have valid email addresses? If so, is this something we need to setup in advance of scheduling email notifications?

**Comment by bevnobev** [comment]
Happy New Year @saderagsdale The only way to know which email addresses failed/bounced is to setup callbacks for the notifications.  That will give you near real time data, and reason codes for the failures.  VA Notify does not keep Veteran data, so without callbacks, we can tell you how many notifications failed/bounced but not the email addresses associated with the failures.  It's January, so please correct me if I'm wrong @mjones-oddball

**Comment by mjones-oddball** [comment]
@bevnobev You're correct! When a successful notification API request is made, VA notify responds with a notification ID. After that occurs, we attempt to deliver the notification to the Veteran. That same notification ID will be present in the status callback so the business can trace back status updates to a particular Veteran in their system if desired.

**Comment by saderagsdale** [comment]
@bevnobev @mjones-oddball Thank you for the deets! How can we set up callbacks for this notification event, such that we:

1. Know the status of the email once sent
2. Know which Veteran + email addresses are returning a hard bounce, meaning the email is invalid
3. Can download a report that includes Veteran identifier, email address, email status (success, not opened, hard bounce, etc.)

**Comment by GitSamJennings** [comment]
@saderagsdale for setting up your Service in VA Notify, would you mind if we made the name more general, maybe your team's name, in order to account for any other notifications that you or your team may request in the future?

**Comment by saderagsdale** [comment]
@mjones-oddball Thanks! Also, apologies. I should have provided better context. Since this is for a Code Yellow, we'll need to be able to download a list of the emails that return a hard bounce, so we know which Veterans did not receive the email. Is that something I can see and download in Domo?

@GitSamJennings Thanks! `Benefits Decision Review` is good for the Service name. Can you name the notification template `Code Yellow: NOD Extension Request Instructions` so that it provides better context?

**Comment by mjones-oddball** [comment]
@saderagsdale Here's a sample of the data provide in our delivery status callbacks, which I know your team is looking into: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-notify#sample-information-included-in-callbacks

VA Notify itself doesn't store and track Veteran data, it's only used in the delivery of the notification. However, we do provide data during delivery status callbacks which your team could store and report on. Does that make sense? CC @bevnobev

**Comment by saderagsdale** [comment]
@mjones-oddball @bevnobev maybe, let me play that back to you to confirm: The callback URL can pull the delivery statuses and email addresses that return a hard bounce, but we need to setup a way to store and download that data because it cannot be done through Domo, is that accurate?

**Comment by mjones-oddball** [comment]
@saderagsdale Very close! Think of it like closing the loop on a notification. So you wouldn't be pulling from a url, VA Notify would be pushing updates to your URL.

Workflow Overview:
- The system you use to trigger the email request will receive a notification ID at that time VA Notify accepts the request.
- VA Notify then attempts to look up the Veteran and deliver the notification
- Delivery statuses will be sent back to the URL your team provides in realtime
- Your team can store that data and determine the best way to provide the report you're looking for.

**Comment by saderagsdale** [comment]
@mjones-oddball Thanks for the details! As long as we are actually getting back the emails that returned a hard bounce I think we can work out how to turn it into a report. I'll make the devs aware so we can plan around how to pull the data.

**Comment by saderagsdale** [comment]
@mjones-oddball Hey Melanie! Once the credentials are in staging and production, how do we work with you to upload the content, and test delivery and the callback URL?

**Comment by mjones-oddball** [comment]
Hi @saderagsdale your team can log into the Staging Portal to create email notification template(s) whenever you're ready. Your engineers will use the corresponding template ID (visible when you view the email template in portal) in their notification trigger code to send the email request to the Notification API. When their trigger code is ready they can test sending notifications in Staging and delivery status updates will automatically send to the URL that was provided. 

Something to note: there is a test send feature in portal which is great for sending yourself an email to check how the content looks, however, that will not trigger a status callback like a true test send using the Notification API.

Once you're all tested and ready to prep for launch, you can promote the template from Staging to Production directly from the Staging Portal site where you created the template :) This is a new feature we released last year to make that launch process as easy as possible. There are different service and template IDs in Production (which your engineers will need) and all of this is visible in the portal when you view your templates.

**Comment by mjones-oddball** [comment]
@dfong-adh I received your support request. Can you clarify what help you're looking for regarding the privacy officer review?
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/99204969/b019deed-fccf-4645-8514-1cc8bcafefa8)
CC @saderagsdale @bevnobev

**Comment by saderagsdale** [comment]
@mjones-oddball @dfong-adh We've covered that step already. I'll check in with Derek.

**Comment by saderagsdale** [comment]
@mjones-oddball I think we're all done with this one! Notifications have gone out and we got a list of failed deliveries.
