### ISSUE TITLE
[RevProxy] Discovery around moving revproxy to AL2

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#65525]
## Description
Need answers to the following questions:
- Are all the same packages used to configure/install revproxy in AL2?
- How much of the current revproxy process can be leveraged?
- What kind of testing should be considered at the image/app level? (make it run right in the instance)
- What does a migration look like for each environment?

## Resources 
- https://github.com/department-of-veterans-affairs/vsp-platform-revproxy

## Acceptance Criteria
- [x] Identify required packages and configurations that are installed in AL1
- [x] Identify Build, Release, Deploy for revproxy-vagov
- [x] Identify a networking level testing strategy
- [x] Identify a migration plan (How will we get a functioning AL2-backed revproxy out there)
- [x] Create stories for the effort

## Refinement Guidance - Check the following before working on this issue: 
- [x] _Team label assigned ("platform-tech-team-2")_
- [x] _Epic assigned (if needed)_ 
- [x] _Estimated (points assigned)_
- [x] _Sprint assigned (once planned)_
- [x] _Team member(s) assigned_
- [x] _Understands how this work aligns with the overall platform_

**Comment by hgbarreto** [comment]
## Revproxy-vagov Overview - Current State
  ### Build
    1. Find bake VPC then bake ami (tries to find encryped one first)
    2. Launch a base instance (bake_instance) 
    3. Update and provision instance (upgrade packages, basic configs, adding VA certs?)
    4. Install Beats, Bigfix, Prometheus
    5. Install App specific items (OpenResty, Datadog?)
    6. Generate AMI (stop bake instance, register ami + tag, terminate bake instance, cleanup up old ami)

  ### Build

  Jenkinsfile - https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/Jenkinsfiles/builds/ami-build
  Build - https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/build/create.yml

  #### Configs

- Base OS - https://github.com/department-of-veterans-affairs/devops/tree/master/ansible/build/roles/common/base-os
- Beats - https://github.com/department-of-veterans-affairs/devops/tree/master/ansible/build/roles/common/beats
- Bigfix - https://github.com/department-of-veterans-affairs/devops/tree/master/ansible/build/roles/common/bigfix
- Awslogs - https://github.com/department-of-veterans-affairs/devops/tree/master/ansible/build/roles/common/awslogs/tasks
- Promtail - https://github.com/department-of-veterans-affairs/devops/tree/master/ansible/build/roles/common/promtail
- Prometheus(node_exporter) - https://github.com/department-of-veterans-affairs/devops/tree/master/ansible/build/roles/prometheus
- Revproxy-vagov - https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/build/roles/revproxy-vagov/tasks/main.yml
- Datadog - https://github.com/department-of-veterans-affairs/devops/tree/master/ansible/build/roles/datadog

### Release    
Release - https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/release/create.yml

**Comment by hgbarreto** [comment]
Testing will begin straight into dev.
Rollback plan is to manually run the BRD workflows to push out revproxy
