### ISSUE TITLE
[task] SC | Request to Increase Rate Limit

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#65537]
## Value Statement
**_As a_** developer
**_I want to_** request a rate limit increase
**_So that_** users have the ability to send more requests in a given amount of time.

---
## Background Context
[Link to Sentry error](http://sentry.vfs.va.gov/organizations/vsp/issues/198994/?environment=production&project=4&project=3&query=SupplementalClaimsController&statsPeriod=14d)

## AC
- Drop in rate limit errors shown through Sentry

**Comment by saderagsdale** [comment]
@kylesoskin Can you add any additional details needed for this?

**Comment by kylesoskin** [comment]
Reaching out about this today

**Comment by saderagsdale** [comment]
@kylesoskin can you drop any details about how long it would take to get another key here? Also curious to know the urgency to prioritize this.
