### ISSUE TITLE
Create endpoint for MAP STS that returns MAP token as long as you are a SiS STS authenticated entity

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#65558]

**Comment by dickdavis** [comment]
## Requirements

We need to implement an endpoint that allows for authenticated services to obtain a MAP token from the Secure Token Service (STS) through a call to `vets-api`.

## Context

Some services external to `vets-api` require a mobile application platform (MAP) token for completing authenticated requests to **[WHAT SERVICE?]**. One example of this is the chatbot service, which needs a MAP token for **[WHAT REASON?]**.

## Design

* What is the URL path of the endpoint?
* What is the appropriate HTTP verb?
* What parameters are required?
* How should the response data be structured?

## References

Service-to-service authentication is implemented as a controller concern [here](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/controllers/concerns/sign_in/authentication.rb#L39)

One example of a service-to-service authentication scheme can be found [here](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/controllers/sign_in/client_configs_controller.rb)

The service for request MAP tokens from STS is implemented [here](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/map/security_token/service.rb#L11)

**Comment by bosawt** [comment]
Just wanted to mention that I reviewed this and as far as I can tell it's accurate and a good place to start with.

I haven't thought too deeply about the errors specifically but the only feedback I might have is just if there's any sense in separating 'invalid bearer token' from 'expired bearer token' (currently both will be invalid here). Sometimes a service will wait until they see the token is expired before attempting to refresh/recreate the token
