### ISSUE TITLE
SOCKS access for Erin White

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#65560]
### Your Name

Erin White

### Your Email

erin.white@adhocteam.us

### Your Role and Team

Information Architect on Platform Governance Team

### Product Manager (PM) name and email

Shira Goodman <shira.goodman@oddball.io>

### Product Owner (PO) name and email

Matthew Dingee <matthew.dingee@va.gov>

### Access Type Requesting

platform

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCiS48kvTwkMtfmJnwUHQeem3nkzsaLQavGpo7G6/YlctrnBzvvJc63CxloBlLxQ7cwkbEM/Kspu8Wo6TjFUUF3SdkX+GMe/EQDYTw94MNWfUyuWOxZPh2jdsqamkfX9Zl49zI4dFUgnX2e7VVpoj7wHDOUUa4H7e/nq7hk4SObA26NHH+yKInDPhORgvo5Wm36Lof3WnCDW7pBFRjOr/k0FUtCHUwX72N06XJToCdnvO2+Wq9NvBv25ZukJjFQfADSPtPs9QhvVwHHDKkFvFLn3kj4Sv282zOlOpLOihErZlulguaaSzBvxA0HsOs6VZq2mFT2SXkjI6wJvcFKIBRsRtRPztQw4R1yyeezwQ7Mv7WoveccuG63KZatrFPdieAI+6VJyLn92F2HBWHKFcHrfcFkbwaSQPIwbInFes2BAjWncjlwAi/yyK3ZI+hWCNcSMYt5Mgn60PtC330N8vT2/pM08hlziS0cC20zpg04OmADgz8D/VePFsRhyT+LSE8= erinwhite@erinwhite-FVFGH0PG0KPF

### E-QIP Transmittal Confirmation

![Eapp-transmittal-Erin-White](https://github.com/department-of-veterans-affairs/va.gov-team/assets/755248/dcab2cec-117a-4c8c-b212-8c47178d83b5)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by ph-One** [comment]
Completed
