### ISSUE TITLE
[Design, FE] 10-10EZ - Return the failed state messaging in-application and on Confirmation page back to the original messaging

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#65565]
## Background
During the final week or so before the PACT Act 9/30 enrollment deadline, we updated the failure state on the Confirmation page and in-application error messaging to include specific instructions for users who are trying to meet the 9/30 deadline (#65524).

Now that the deadline has passed, we want to return the messaging to its original state.

## Tasks
- [x] Revert [PR #25840](https://github.com/department-of-veterans-affairs/vets-website/pull/25840) used to create temporary messaging in #65524
 
## Acceptance Criteria
- Failure state error messaging within the 10-10 EZ application, as well as on the Confirmation page, have been replaced with the original content.

**Comment by longmd** [comment]
Confirming that the content updates have been applied successfully:
![Screenshot 2023-10-02 at 12 43 19 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/6738544/d2122339-c50c-4dcc-a64a-49790a0baf65)

**Comment by hdjustice** [comment]
Awesome!! 
Can you confirm these changes are applied to:
- Need Help section
- Confirmation page error
- General system error
- Pagerduty message

**Comment by longmd** [comment]
They have been applied to all those spots! Just don't really have a way of forcing all those to occur to get screenshots.

**Comment by hdjustice** [comment]
no worries! Just checking, thank you @longmd
