### ISSUE TITLE
SOCKS access for Tyler Spangler

### ISSUE THREAD

**Issue by tyler-spangler6** [department-of-veterans-affairs/va.gov-team#65561]
### Your Name

Tyler Spangler

### Your Email

tyler.spangler@agile6.com

### Your Role and Team

Data Engineer, Contention Classification

### Product Manager (PM) name and email

Yurena Garcia - yurenagarcia@navapbc.com

### Product Owner (PO) name and email

Jennifer Bertsch - jennifer.bertsch@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQChfX0DxLUKnHPXtcVEwYmtw1+12ufOGuMq2noo04TrZOyRZzh38z4nzCxOOBRXTcuAxec/FmnW64rcwv4E08qoyYv4r/X0zBM/yCFAwGpoFsxS1WpD0DieY82kbfwAIEO5cqESbRIsFOKL00pRdwSTCJNKijrYKV2vdgEsvKcMmkIgJiWwT3E96L43+dslaHQoPvllJkEBAYQoG8B7lyPLxjfGZ/WIwdVR25G7oQ4G1T4Mvu5/VIPCMJzqs3SoEahk3958k0ybc+Q1807j7wQ95j8WczyTndU82OVJlLOOxkt7iQzJwo+buBXzXWGReZV/WGsRcoRmFi0pt7pXXeADvf3u9vRdB/72p63jssMfrn8qH4CMh5u/WmvRbxFtqJn/U4DVm8gdWYmHuqgQejAbGXYGYol89Qh1vV+BQ8rvljoIIj9iI5eahOVW2tZYxCm/611u+g++bbsnXxyMH/Yu/5FaXByvpBPaQSxDLaYmbH3d11sBI0tGmAB5HFDJWlU= tylerspangler@Tyler-Spangler.local

### E-QIP Transmittal Confirmation

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/142833783/d529e7de-b854-42ea-8770-11e811164a47)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by ph-One** [comment]
Completed
