### ISSUE TITLE
create technical diagram for IPP

### ISSUE THREAD

**Issue by djmunoz1** [department-of-veterans-affairs/va.gov-team#65572]
AC
- setting up time with dev + Porta to draft a diagram for BE interactions on IPP 

DEF OF DONE:
- documented draft in Mural/LucidChart

**Comment by rdvyas** [comment]
Working with MO engineering team and researching in the VA.gov GH environment the team was able to come up with the following diagram outlining the Current State of VA.gov environment and the supporting services. This is an abstraction of the environment. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcS9FIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--af48a7ad70c5e5099c9026016c7d63a1aefe111b/image.png)

**Comment by rdvyas** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcmpFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f8dd731e46dd088515335c701acfa1c37a3c17cc/VA.gov_Topology_DRAFT.png)

Closing ticket as complete.

**Comment by rdvyas** [comment]
Also came up with future state diagram where we have included the IPP application and 3 options for deploying the application. Also diagramed a simple representation of the IPP application and the various integrations included with the application. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcjdvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--02cfd16d91e18876336434f743bdae4190d1256c/Screenshot%202023-09-27%20at%2010.00.28%20AM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBci9vIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2b42d7904b92e61549fbae5eec55d614a9be31eb/Screenshot%202023-09-27%20at%209.33.34%20AM.png)
