### ISSUE TITLE
Contact Center Review - Create video

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#6558]
Create a Product Video (with audio) that steps through the primary user flows.
Create a transcript of the audio from the Product Video. The transcript must be a Word document or a PDF.
Remember your Product Video will be uploaded to the VA Youtube channel. It will be unlisted but visible to people with the URL.

**Comment by mr0sari0** [comment]
This task has been completed in https://github.com/department-of-veterans-affairs/va.gov-team/issues/6557
