### ISSUE TITLE
[UX] Determine scope and PCI role in researching/implementing past appointments for travel reimbursement

### ISSUE THREAD

**Issue by cgednalske** [department-of-veterans-affairs/va.gov-team#65592]
The team is interested in exploring travel reimbursement for past appointments. Kristen is starting a scope document about implementing and testing past appointments for travel reimbursement.

[Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1694530929649/38caa40c4c6f70516ff2c784b4ff1b5514490e75?sender=ua2ec2e34eb6128f3375e0207)

## Tasks
- [ ] Work with Kristen to narrow down the scope and determine PCI's role
- [ ] Document results
- [ ] Create f/u tickets

**Comment by benbrasso-agile6** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/65592?planning-poker) with Zenhub @cgednalske @kellysmith1008 @ytsaoca @zach-park
