### ISSUE TITLE
[Design] Create Wireframe for Upcoming Appointments Progress Loading Indicator

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#65614]
## User Story
The call the retrieve the upcoming appointments will take place after the new landing page loads. Therefore, we need a progress indicator for the fact that the upcoming appointments are loading.

Work with FE to get the different loading indicators and their messaging. The UI part of this might be somewhere in the design system. So, we probably don't need to change the UI, just check the content. 

## Tasks
- [ ] Create final mockups with callouts 
- [ ] Decide: Should a content and accessibility review be part of this ticket or separate tickets due to scope?

## Acceptance Criteria
- [ ] UI review meeting with product/UX team for feature capabilities
- [ ] UI review meeting with engineering for layout and callouts (can be the same meeting as above)
- [ ] Wireframe available on Sketch Cloud
- [ ] If the wireframes applies to an error state or text message, then update the [GitHub source of truth](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/design/text-and-error-messages.md) documentation.

**Comment by benbrasso-agile6** [comment]
Start with content, then designer can mock up

**Comment by kellysmith1008** [comment]
So after UX sync today and meeting with Ya-ching, we decided that we don't need a mockup to send to John, we can just send him the [documentation and content](https://docs.google.com/document/d/1meFuLT4AsQpQ70oWIl-VUjlxM0O4R6V_EOIQSD_HIUc/edit) for the loading states. If we have time this sprint we will mock up the loading states and document them in git. If not, we'll keep this work in the back of our mind and create a ticket to do the work when appropriate.
