### ISSUE TITLE
create lighthouse dev account

### ISSUE THREAD

**Issue by djmunoz1** [department-of-veterans-affairs/va.gov-team#65613]
VROs have deployed their product to Lighthouse and is a possible landing spot for where our IPP app might live. 
Purpose: review and understand lighthouse infra

AC:
- find the documentation for creating a Lighthouse dev account on Lighthouse site
- sign up for dev account if possible 
- research and get understanding of how we might build on the platform

DEF OF DONE:
- dev account is created and access info shared in ticket

**Comment by sdickson-gt** [comment]
An API key for sandbox is provided by selecting an API to use: https://developer.va.gov/explore.

There are a list of 21 currently available APIs for patient health and benefits.

**Comment by rdvyas** [comment]
Tremendous amount of useful information to be found on these API docs. I think some of the integrations that stand out are the following:

Address validation : https://developer.va.gov/explore/api/address-validation
Location API: https://developer.va.gov/explore/api/va-facilities

I have updated the [IPP_Technical_Approach] (https://docs.google.com/document/d/15Wl6scS9ku8lO3v9QqeQM_zN9GzxCP-nfGWtIr_SqWc/edit) with this information. 

This ticket can be closed, further tickets to explore the specific APIs will be created.
