### ISSUE TITLE
Documentation - Launch new tooling solution

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#6561]
Documentation - Launch new tooling solution

### Problem Statement

Currently, VSP and VFS teams are using GitHub for documentation (primarily in `va.gov-team` and `va.gov-team-sensitive`). Using GitHub as a documentation site causes a series of pain points, including (but not limited to): no collaborative editing, no WYSIWYG, no redirects when files are moved or names are changed, no customizable navigation beyond folder structure, no feedback loop. 

How might we implement a new tooling solution that is better able to support our documentation needs and enable VFS teams to find what they need to build great products on VA.gov?

## VSP Objective (Q1 & Q2 2020)

O1: Any volume of simultaneous customers have a delightful, self-service, end-to-end experience using the Platform to build on VA.gov.

## Measuring Success (KRs/KPIs)

TBD

## Details and Notes

We will be examining off-the-shelf tooling solutions: 
- Confluence
- Slab
- Others

### Goal(s)

- Determine the best documentation tooling solution to meet our needs on VSP and VFS.
- Create implementation plan.
- Implement the new tooling solution.

### Assumptions and Hypotheses

We **assume** that VSP Content & IA team should be heavily involved in supporting VFS teams in migrating documentation to a new tooling solution. 
We **assume** that GitHub is not sufficient to meet our needs as a documentation site.
We **hypothesize** that if we provide VFS teams with a robust documentation tool, paired with clear standards and expectations, they will create and maintain their own documentation.

**Comment by vbellissimo** [comment]
Cancelling/old task.
