### ISSUE TITLE
[FE] Use the Same Facility Identifier that BTSSS Uses to Determine if Veteran has Already Submitted a Travel Claim for a Specific Day and Facility

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#65628]
## Background
In a team meeting on 9/13/2023 with Kay & Shawn & Mark, it was decided that we should use the same identifier that BTSSS uses to determine if a claim has already been filed for a specific Veteran on a specific day for a specific facility. Currently we use the Facility Name and, according to Mark, BTSSS uses Sta6a (from HRM & Vista).   

## Tasks
- Use the Same Facility Identifier that BTSSS Uses to Determine if a Veteran has Already Submitted a Travel Claim for a Specific Day and Facility

**Comment by loripusey** [comment]
@wullaski so this is in production now?

**Comment by wullaski** [comment]
@loripusey yes it is
