### ISSUE TITLE
Add Pull Request Review Policy to Documentation 

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#65637]
## Description 
The goal of this ticket is to add the Pull Request Review policy to any documentation including the Platform Orientation.

---

## Definition of Done
_What must be done to officially complete this task?_

---

## Tasks 

- [x] Add to the Platform Orientation slide
- [x] Add other places to add the blurb too here and check them off

--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by jknipes** [comment]
Added SLA to Orientation slide

**Comment by jknipes** [comment]
@alyssagallion please review [this verbiage for addition to other documentation on PR Reviews](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2761326593/Advanced+Ticket+Support+Best+Practices+Tier+1#PR-Review-Requests)

**Comment by alyssagallion** [comment]
Added to all documentation.
