### ISSUE TITLE
identify potential verifiers for pilot

### ISSUE THREAD

**Issue by djmunoz1** [department-of-veterans-affairs/va.gov-team#65635]
As a veteran, I want to be able to go to a VA facility and have a VA staff member assist me so that I can verify my identity for a secure sign in credential. 

AC:
- discuss location variables with research team (multiple cities, single city and multiple locations)
- confirm with VHRC site volunteer staff
- share verifier criteria

DEF OF DONE:
- names of identity verifiers have been identified for us to pursue

**Comment by lmorris3** [comment]
@SophiaPhilipMO this was in the backlog - if it's a dupe, we can close with that comment. If not, we can edit the dod/ac and move to review.

**Comment by SophiaPhilipMO** [comment]
MHV Coordinators will be recruited through the partnering Virtual Health Resource Center site

Criteria:
Available at selected VHRC site during scheduled Veteran sessions
Participate in pre-pilot call and orientation call
Have an active PIV card with access to:
VA.gov
Login.gov
Identity Toolkit
Has used Identity Toolkit
Complete requested tasks prior to and during the duration of the Pilot:
Pre-pilot calls
Available during scheduled sessions
Complete surveys

**Comment by SophiaPhilipMO** [comment]
Verifiers identified at Fayetteville, AR and Long Beach, CA
