### ISSUE TITLE
PACT ACT Quick Look

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#65652]
- Link to Dashboards
- - Links to predefined log filtering
- Explain what it means to have a bit of a puma backlog
- Alerts to look for and what channels
- Explain HPA
- Explain the bulkheads

**Comment by LindseySaari** [comment]
Information here. This is started https://vfs.atlassian.net/wiki/spaces/TT1/pages/2770272299/PACT+Act+Second+Cohort+Information and we will continue to add information throughout the sprint

**Comment by LindseySaari** [comment]
Ongoing ... will keep this open until near end of sprint
