### ISSUE TITLE
Discovery: VA SOCKS

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#65665]
# Description
We need to analyze the possible impact of moving the underlying AMI for the VA SOCKS proxy from AL1 to AL2.

# Acceptance Criteria
- [x] We know what areas of the VA SOCKS proxy's functionality are likely to be impacted by a migration to AL2
- [x] We know the level of effort it will take to adapt VA SOCKS proxy and or the AL2 base image to achieve baseline VA SOCKS proxy functionality

**Comment by pjhill** [comment]
VA SOCKS role in `devops` -- https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/build/roles/va-socks/tasks/main.yml

**Comment by pjhill** [comment]
VA SOCKS build role wants the following:
* https://github.com/fail2ban/fail2ban
* https://yum-info.contradodigital.com/view-package/installed/bind/

**Comment by pjhill** [comment]
VA SOCKS release role in `devops` -- https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/release/config/va-socks.yml

**Comment by pjhill** [comment]
va-socks-utility.yml -- https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/va-socks-utility.yml

**Comment by ben-allen-oddball** [comment]
Creating Repos "PSO Socks Proxy"  PSO is an acronym for Platform Security Operations.  Peter and I felt it was important for "Products or deployments" not reference the name, such as PRT, of the team that owns it.  Team names change as well as ownership of deployments.

**Comment by ben-allen-oddball** [comment]
Creating Repos "PSO Socks Proxy"  PSO is an acronym for Platform Security Operations.  Peter and I felt it was important for "Products or deployments" not reference the name, such as PRT, of the team that owns it.  Team names change as well as ownership of deployments.

**Comment by ben-allen-oddball** [comment]
Creating Repos "PSO Socks Proxy"  PSO is an acronym for Platform Security Operations.  Peter and I felt it was important for "Products or deployments" not reference the name, such as PRT, of the team that owns it.  Team names change as well as ownership of deployments.

**Comment by pjhill** [comment]
Given that the scope of this ticket is discovery, we should break off the work we are logging here and finish this out under an implementation ticket or set of tickets that describe the plan we came up with in the design document.
