### ISSUE TITLE
Design low-fidelity proposals for secondary navigation component

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#65677]
## User Story
As a UX practitioner working on the MHV to VA.gov transition and overall experience, I want to lean on the results of the competitive analysis and documentation of problems with existing navigation to inform an improved design for health portal secondary navigation.

## Description
In previous tickets, the team evaluated the existing side navigation/ secondary navigation patterns on VA.gov and documented issues they present for the MHV on VA.gov health portal (#65055). We also conducted a competitive analysis of other side navigation patterns that can inform a direction for an improved, redesigned secondary navigation. (#65308)

Now, we need to abstract the best layouts and interaction patterns from the competitive analysis (keeping in mind the documented problems with previous components & needs for this experience) to give some structural guidance to designers to then come up with several proposals for an improved navigation component. 

## Impacted Artifacts
- [Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1696390421791/1ae40bf619944122de124da6340f91b48f643274?sender=uf94a77a19aaf687331c09367)
- [Sketch file](https://www.sketch.com/s/f9050748-823b-4245-98c9-e9738c15a271/p/C4A4156A-68C7-4FCB-B6AF-063A204C3D8B/canvas)

## Tasks
- [ ] IA & design collaborate to draw up some lo-fidelity examples using IA's structural guidance
- [ ] Get design team feedback on these components

## Acceptance Criteria
- The team has design proposal(s) that incorporate findings from navigation research analysis & competitive analysis

**Comment by LynneJohnson224** [comment]
@jonathanjnelson @keithcheung828 @fmccaf1 can you please add a story point value to this ticket?
