### ISSUE TITLE
Validate DMC code changes in FSR generation API (Due by: 10/10/23)

### ISSUE THREAD

**Issue by HeatherRienks** [department-of-veterans-affairs/va.gov-team#65690]
## Issue Description

Per Jeff Chant at DMC: 

"DMC ITD has made some code changes to fix vulnerabilities in the FSR generation API. There is no impact on functionality with this change. We have tested this in our environment and everything is working fine.

Since it is a code change, DMC is asking us to test/validate the functionality from the debt portal side. The changes are currently available for testing in the Stage/Pre-Prod environment."

DMC and VODA agreed to complete this work in Sprint 109 (starting 9/27/23).

---
## Tasks
- [x] Validate functionality in Stage and Pre-Prod environments.

## Acceptance Criteria
- [x] Confirmed changes made by DMC should not affect Debt Portal.

**Comment by HeatherRienks** [comment]
@ScottyRJames emailed Jeff Chant (DMC) -awaiting response.

**Comment by ScottyRJames** [comment]
Testing against DMC preprod environment has been completed and we've validated their changes should not affect our portal for either the FSR generation or debt letter get endpoints. 

DMC will notify us when the changes will be released to production (2-3 weeks from now) so we can keep track with our monitoring tools for any issues.
