### ISSUE TITLE
Request access to Google Analytics and/or Domo

### ISSUE THREAD

**Issue by fmccaf1** [department-of-veterans-affairs/va.gov-team#65693]
# Request Google Analytics and/or Domo access

## What this form is for
Use this template to request access to Google Analytics and/or Domo. Please complete steps 1 & 2 below. 

## 1. Access Requirements 
Please check the analytics tool(s) you need access to:
- [ ] Google Analytics
- [ ] Domo
- [ ] (Platform Teams only) BigQuery

None of these. I'm seeking access to GA4 (MHV national portal data). I believe I do not currently have access because when I go to [this link](https://analytics.google.com/analytics/web/?authuser=0#/report-home/a50123418w177519031p184624291) I get an error: 

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/106624475/85539b48-e6e6-40e3-a718-1e94f0dbcfed)

## 2. User Email Address to Receive Access 
**Due to privacy concerns, please do not put your email in this ticket.** Instead please use `/support` on the DSVA Slack channel [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support), select `Analytics` in the "I need help from" dropdown, and then add in the `Summary of request` section: 
 1. This issue's link 
 2. Emails that need access

_Please note: For Google Analytics, if the user has a VA.gov email address or does not yet have a Google account, they will need to create one by visiting [this link](https://accounts.google.com/signup/v2/webcreateaccount?continue=https%3A%2F%2Faccounts.google.com%2FManageAccount&gmb=exp&biz=false&flowName=GlifWebSignIn&flowEntry=SignUp). Once at that link, VA.gov users and external users with email accounts that are not Google based should select the option "Use my current email address instead"._

_Please list any additional requirements, if any (i.e. edit access). If you are requesting BigQuery access, please share if you will be hooking up an API._

_Once you receive access, you should receive a confirmation email directly from Google or Domo._

 
---

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by michelle-dooley** [comment]
@fmccaf1 - you do have access to the VA.gov account which is where that link takes me. I do not see any MHV for GA4, if one exists it is not managed by this team. Can you show me a screen shot of the property you are trying to click on before you get that message?

**Comment by fmccaf1** [comment]
@michelle-dooley thanks for getting back to me. The link was provided to me by Anne Costello, from ByLight, who has access to the GA4 for MHV. This is the url she sent me: https://analytics.google.com/analytics/web/?authuser=0#/p382953115/reports/intelligenthome?params=_u..nav%3Dmaui

I'll reach back out to her and let her know that VA platform doesn't manage this one

**Comment by michelle-dooley** [comment]
Yeah I can't access that link either. I am going to close this ticket. Please reach out if there is anything else we can do to asssit.
