### ISSUE TITLE
Remove inherited proofing functionality

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#65692]
This code no longer is used and it's broken since changes have been made in our system, so it's no longer useful

## vets-api Removals
- [x] remove functionality - https://github.com/department-of-veterans-affairs/vets-api/pull/17417
- [ ] remove `vets-website` related mock data - https://github.com/department-of-veterans-affairs/vets-website/pull/30845
- [x] remove `vsp-infra-application-manifests` configurations
  - [x] https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/2975
  - [x] https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/2976
- [ ] migration to drop `inherited_proof_verified_user_accounts` table
- [x] remove inherited proofing values from AWS ParameterStore
  ```
  /dsva-vagov/vets-api/dev/logingov_inherited_proofing_redirect_uri
  /dsva-vagov/vets-api/staging/logingov_inherited_proofing_redirect_uri
  /dsva-vagov/vets-api/prod/logingov/inherited_proofing_redirect_uri
  ```

**Comment by bramleyjl** [comment]
The main removal of `vets-api` code has landed on `main`, once I confirm it is off of production I'll remove the related configuration code.

**Comment by parkerbees** [comment]
moved to Jira, closing
