### ISSUE TITLE
Adding [Kyle Henson] to DSVA Slack

### ISSUE THREAD

**Issue by Eallan919** [department-of-veterans-affairs/va.gov-team#65706]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

Please add Kyle Henson to DSVA slack as he supports the CEDAR VA.gov IIR Product Teams program under Jeff Barnes as VAPO

Are you requesting to add an individual as a:

- Full member

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

We aim to complete slack requests within 24hrs.

## Sample Descriptions 

- Please add [[kyle.henson@oddball.io](mailto:kyle.henson@oddball.io)] as a full member.

**Comment by eunicegar** [comment]
Complete.
