### ISSUE TITLE
SOCKS access for [Michelle Dooley]

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#65734]
### Your Name

Michelle Dooley

### Your Email

michelle.dooley@oddball.io

### Your Role and Team

Product Manager

### Product Manager (PM) name and email

Michelle Dooley michelle.dooley@oddball.io

### Product Owner (PO) name and email

Erika Washbrun erika.washburn@va.gov

### Access Type Requesting

platform

### Public SSH Key
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDqHfv3FD1Sya+oxsp+UHvmGLc81a80KqLp3ms8prW48LePfB6xa08eN2SOIWgMOuijpNczsucd5S4pU8ZQOuZfzKTlQLj0Aaw9XxFwenWRABY/Z1Mu2umKj3HkYYj86E2sazUEL7Tqshpiv99Xx3vNE4mOQo0SxEUBfJU+uan6uqg9nM1/bcH2rLxZU1jlINtzLimBlATPvCDW3hr/hKTKVj01UXUE6abVxVXmsaxGSyDgKy5BGFy6WKgVvn/0/tGTuYRZxL5zIWcF64XWoqFeT9AlFh7LAzD/rS/0PFm6NfNkKz+n4K15FHGcTLO72eQ4rLkFT9gvgfBY5HgR870OQmWwnWM8+0Em42fcZT3lwVr9smLaG1HLXi0N/fyLHJv7hbQFdVbBU7muPBfoXc+ZvTYeTXi0buFAp+BmDKqJcGbJEhxq+debDkhr2gsv3TcElzS6OMZ2Z9q9oTD6LhlGoVdZyVsVoltxthyV9h2UvgGYVI/5Wm3JzbJi+2sydWc= michelledooley@TABLET-OSBQDLV1

### E-QIP Transmittal Confirmation

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/93597659/6cdccb0c-beca-4a6c-bc3c-4523f9cdcc2a)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by michelle-dooley** [comment]
AAAAB3NzaC1yc2EAAAADAQABAAABgQDqHfv3FD1Sya+oxsp+UHvmGLc81a80KqLp3ms8prW48LePfB6xa08eN2SOIWgMOuijpNczsucd5S4pU8ZQOuZfzKTlQLj0Aaw9XxFwenWRABY/Z1Mu2umKj3HkYYj86E2sazUEL7Tqshpiv99Xx3vNE4mOQo0SxEUBfJU+uan6uqg9nM1/bcH2rLxZU1jlINtzLimBlATPvCDW3hr/hKTKVj01UXUE6abVxVXmsaxGSyDgKy5BGFy6WKgVvn/0/tGTuYRZxL5zIWcF64XWoqFeT9AlFh7LAzD/rS/0PFm6NfNkKz+n4K15FHGcTLO72eQ4rLkFT9gvgfBY5HgR870OQmWwnWM8+0Em42fcZT3lwVr9smLaG1HLXi0N/fyLHJv7hbQFdVbBU7muPBfoXc+ZvTYeTXi0buFAp+BmDKqJcGbJEhxq+debDkhr2gsv3TcElzS6OMZ2Z9q9oTD6LhlGoVdZyVsVoltxthyV9h2UvgGYVI/5Wm3JzbJi+2sydWc= michelledooley@TABLET-OSBQDLV1

**Comment by flooose** [comment]
@michelle-dooley I believe we took care of this last week, so I'm closing it.
