### ISSUE TITLE
Adding [Peter Egan] to DSVA Slack

### ISSUE THREAD

**Issue by Eallan919** [department-of-veterans-affairs/va.gov-team#65731]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

Please add Peter Egan to slack as he supports the VA.gov IIR Product Teams Program (CEDAR) under Jeff Barnes. 

Are you requesting to add an individual as a:

- Full member

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

We aim to complete slack requests within 24hrs.

## Sample Descriptions 

- Please add [[peter.egan@oddball.io](mailto:peter.egan@oddball.io) as a full member.

**Comment by JeffBarnesUSDS** [comment]
Invite sent

**Comment by oddballpete** [comment]
Confirmed Receipt and initial sign in complete
