### ISSUE TITLE
Documentation support - Platform doesn't use email

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#65742]
### Request type

- [X] Writing new documentation
- [X] Updating previously published documentation
- [ ] Reviewing recently written, never-before-published drafts

### Number of docs

1

### Subject matter expert

not sure

### Approvals

probably not

### Embedded media

- [ ] Screenshot(s)
- [ ] Diagram(s)
- [ ] Video(s)

### Audience

- [X] Developers
- [X] Designers and researchers
- [X] Product managers
- [X] Other

### Anything else?

Platform doesn't use email. This is something that's communicated in the General Orientation session, however I'm unsure if it's mentioned anywhere on the Platform Website. The reason I bring this up now is bc I've had Product Managers message me on Slack so they can ask for the Governance team and/or Platform email address for sending/sharing information.

I don't think this is a huge problem, but it would be nice for VFS teams to see that email is not in use by Platform (or  it's only for event scheduling) and it would be nice for Platform folks to point to this page (or section of a page) if/when email is requested in the future.

**Comment by laucon** [comment]
@shiragoodman We were thinking about putting this message on [Platform Tools](https://depo-platform-documentation.scrollhelp.site/getting-started/platform-tools) under Getting Started since that document gets a lot of views, I think. I created [this draft](https://vfs.atlassian.net/wiki/spaces/PWD/pages/2781773862/Platform+tools+copy) where I added the yellow box right underneath the blue box (the blue box already exists, but the yellow box is new.) What do you think?
<img width="1792" alt="Screenshot 2023-09-27 at 11 47 51 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/14806304/c8ed83ce-8fd3-43ed-8463-bb4114ea53f0">

**Comment by laucon** [comment]
@shiragoodman I'm looking over my own draft. Do you think I should write an exception for scheduling meetings or is just saying "we don't use email" fine? Also, should I mention that Platform members also use github as well as slack? I wanted to add this as a separate block from the other one to make it stand out. But I could also cut the github line from box 1 and place it in box 2. Or keep it as one single box. These are just ideas I'm having.

**Comment by shiragoodman** [comment]
lol @laucon you read my mind! I read the first draft and the only thought I had was regarding exceptions for scheduling meetings. I don't think it's necessary to state we use Github as well as Slack.  They find that out pretty early when completing Platform Orientation. Maybe just clarify the current yellow box message to specify email is only used for scheduling meetings, and not used for communication.

**Comment by laucon** [comment]
@shiragoodman I wanted to check with you on the wording. How is [this](https://vfs.atlassian.net/wiki/spaces/PWD/pages/2781773862/Platform+tools+copy)? :) 
<img width="1792" alt="Screenshot 2023-09-28 at 11 48 10 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/14806304/28924ac4-c51a-495f-9d5f-6375761c616b">

**Comment by laucon** [comment]
@shiragoodman I guess I'm sort of using this github ticket to think out loud a little bit. lol. I also came up with this alternative wording. Do you have a preference between wording 1 or wording 2?
<img width="1792" alt="Screenshot 2023-09-28 at 11 51 45 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/14806304/e61458f5-8e9b-4f0a-b41e-e65fe2a5e3ab">

**Comment by laucon** [comment]
@shiragoodman and feel free to give me any other feedback you have. :)

**Comment by shiragoodman** [comment]
I think either sounds good @laucon . The only comment I have is whether or not we need to capitalize NOT. I feel like the warning style is probably enough and the emphasis on NOT is probably not needed. However that's up to you and your team

**Comment by laucon** [comment]
Great. In that case, I'm gonna go with message version 2 and make "not" lowercase. Thanks!

**Comment by laucon** [comment]
We should deploy this today.

**Comment by laucon** [comment]
This is now done.

**Comment by shiragoodman** [comment]
Thank you @laucon and the Platform Content team!
