### ISSUE TITLE
[Congressional] V10858248 - Issues with logging into va.gov (Rep. Fallon) Due 10/6/2023

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#65769]
Veteran's son/caregiver is having issues with logging into va.gov.

V10858248 - Issues with logging into va.gov (Rep. Fallon) 

https://dvagov.sharepoint.com/:f:/s/DigitalExperiencePMOInternalFTC-PrivateOCTO-DEActions/EpdSSshGHLVIuxdDS1NuLa8BjjLyENEtmcWOFz-3qtYgJA?e=Fk6Ejv 

https://va.lightning.force.com/lightning/r/Case/500OE0000015HuBYAU/view

https://dsva.slack.com/archives/C02BS78NYRM/p1695059302183859 

The constituent's letter states "I am caring for my 93-year-old veteran father and was recently told we have to submit things via eBenefits.va.gov website that is not currently working properly. Part of that process is to submit a valid ID and they do not accept his military ID nor his driver's license because it has expired. They will accept a state ID but I cannot take my father from this home because he is on hospice and has dementia to get said id. I called the phone number that I was referring to and was on hold on two different occasions for over 30 minutes and it was disconnected each time. He currently receives a pension but medical expenses have increased and I'm attempting to submit them but can get no further than the mail submission. I have full power of attorney as well as medical power of attorney. I am also his fiduciary for his pension."
---
## Tasks
- [ ] Review congressional correspondence
- [ ] Resolve issue 
- [ ] Notify Veteran and congressional correspondence channel of solution.

## Acceptance Criteria
- [ ] Veteran issue will be resolved or responded to with final answer to issue 
- [ ] Congressional Correspondence will receive details of the resolution 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by clantosswett** [comment]
There are no details about the veteran or the veteran son who created the inquiry therefore no investigation can happen as well as no follow up.

**Comment by Kimberley2023-CSM** [comment]
I am going to attempt to use the email address listed in documentation surrounding this matter.

**Comment by Kimberley2023-CSM** [comment]
Contacted Brenda from HRC to assist with possible remote proofing. 

Contacted Veteran's son for additional details.

Received a response from the son.  His father passed away on August 22, 2023.  States he is working with Mr. Petty from the courthouse. 

Unsure of how to move forward with issue.  Reached out to Vicci C for guidance.

**Comment by Kimberley2023-CSM** [comment]
Beth from HRC advised an ID.me or Login.gov account can no longer be created and if further assistance is needed to contact VBA regional office.

Correspondence to Veteran son sent.

**Comment by Kimberley2023-CSM** [comment]
https://dsva.slack.com/archives/C02BS78NYRM/p1697126700430079?thread_ts=1695059302.183859&cid=C02BS78NYRM

https://dsva.slack.com/archives/C02BS78NYRM/p1697126755238969?thread_ts=1695059302.183859&cid=C02BS78NYRM

Case closed per Vicci.  See Slack link above.
