### ISSUE TITLE
How might we ensure that veterans only see appeals decision letters that have been approved to be mailed

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#65770]
## Background

Blocking the release of appeal decisions showing up in DDL is the need for those decisions to be approved to be sent out. Currently, once the letter hits the e-folder, we'll pull it into DDL if we filter on that doc ID, but it is often the case that someone at VBA needs to review those letters before they get sent in the mail. We want to avoid the scenario in which a letter gets downloaded, but then the veteran finds out later it's an invalid decision. 

## Technical approach
** 48 hour lag time**
We are going to filter out letters where the `receivedAt` date is less than 48 hours in the past. We chose 48 hours because the `receivedAt` date doesn't include a time component and we have to be able to guarantee that the `receivedAt` date is _at least_ 24 hours in the past.

## Some approaches that have been proposed

- Delaying the letter from showing in the application for an arbitrary period of time such as 24 hours. 
- Creating a new doc ID for approved letters and recreating the doc with that id somehow

## Technical Discovery

- [x] Identify possible solution approaches that can be handled by the CST application only
- can be between 24 and 48 hour timebox, but not more specific than that.
- [x] Identify possible solution approaches that would take coordination across multiple teams
- [x] Provide a rough level of effort assessment for each approach
- [x] Provide recommendations on which approaches seem fruitful considering desirability, viability, and feasibility. 

## Acceptance Criteria

- [x] We allow at least 24 hours between the letter hitting the e-folder and then hitting DDL

**Comment by samcoforma** [comment]
@jacobworrell @jerekshoe 

> Delaying the letter from showing in the application for an arbitrary period of time such as 24 hours.

This seems like the solution we can actually pull off.

> Creating a new doc ID for approved letters and recreating the doc with that id somehow

I'm not sure how we could do this idea, so my thinking is we go with the arbitrary delay idea. Thoughts?

**Comment by samcoforma** [comment]
@jacobworrell If we go with the delay solution, is there a consensus yet on how long the delay should be?

**Comment by HeatherWidmont** [comment]
@samcoforma & @jerekshoe to sync in today's Eng huddle to discuss

**Comment by HeatherWidmont** [comment]
@jerekshoe will review & merge
