### ISSUE TITLE
SOCKS access for [Ari Perez]

### ISSUE THREAD

**Issue by ariperez** [department-of-veterans-affairs/va.gov-team#65787]
### Your Name

Ari Perez

### Your Email

ari@coa.solutions

### Your Role and Team

CMS - DevOps

### Product Manager (PM) name and email

Berni Xiong, berni.xiong@agile6.com

### Product Owner (PO) name and email

Erika Washburn, Erika.Washburn@va.gov

### Access Type Requesting

drupal_developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCtYnVlGEjhWo14fNZml7ejcb9kvZSsN8vARzIdpNILvlyVEpYDjLX9g61ke0CJGKakGFVVpNqOKMNVIlZ43nOCuAfguaQI7lhB3vIuqfo3n5KLriTqWr0czB+3wVCRA6FjgHLdVuWCPnrEoXfX4G5R+mQ8NqbdBUs3tVrskIa/9JZLbQvSgKnRzQWZmOvyN4bNx4aOZiJzmAJZvZAKOtM4MGkgfY4N0oP9mvfLwKpRUbNFE6WvRssVDxKvSCYyHMPpfuQvb3sE2AYQ4tlYh08K1AjVJWcLQQFUBytBHWPlI0FamAvqLF3g//wUQWzT4nkclACJh8lQq1Mz/RJZdDWZ2M5Ty8tws/up3wDHiQwU7SYoJRYGEh5G7WBRTFRrQEOTSDzn5V4ZvbTE32GLj+F3CfzcXaWz2Ke+s8vGIEKmYnVtBZeDm5s8nk9tQm7MK56RykEKLIwtyt9fxicJ+9APm75a5bBA68w+sTO9MlP/FrGJYhVUN6mbwGdB6Lxfjx8= ariperez@Aris-Mac-Studio.local

### E-QIP Transmittal Confirmation

<img width="927" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/2553469/b1f67350-3fb1-4be8-a337-3d3dc5b0a19f">

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by ph-One** [comment]
Completed
