### ISSUE TITLE
Sidekiq Admin UI access for [Thomas Blackwell]

### ISSUE THREAD

**Issue by tblackwe** [department-of-veterans-affairs/va.gov-team#65794]
### Your Name

Thomas Blackwell

### Your GitHub handle (Sidekiq Admin UI access is managed through GitHub)

tblackwe

### Your dsvagovcloud AWS user name (if applicable)

Thomas.Blackwell

### Team, Role, and Company of the target individual

Benefits-Disability Tech Lead - Coforma

### COR Name

Jennifer O'Day

### Please confirm if you are on the VFS Team Roster or Platform Team Roster

- [X] [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Sidekiq UI Access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### If PRODUCTION ACCESS is required, confirm/complete ONE of the following

- [X] I have an AWS Username and it is listed in [here](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf)
- [X] I currently have access to vets-api Production Terminal via ArgoCD
- [ ] I've attached a screenshot of my E-QIP Transmittal Notice E-mail (Drag or Copy/Paste in Additional Notes Section below)

### Additional Notes

I need lower tier access to validate changes made to sidekiq jobs are operating correctly

I need access to production to assist with debugging issues and alerts that we are seeing on a regular basis. cc @va-albers

**Comment by lindsay-insco** [comment]
Found in VFS Roster

eQIP transmittal notice [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60005) AWS access as well.

**Comment by lindsay-insco** [comment]
@tblackwe You've been granted access to all environments, with access to Production limited to 6 months, expiring, 03/18/24

**Comment by lindsay-insco** [comment]
Slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1695070828268819)

**Comment by tblackwe** [comment]
Please expire that access. I hope to never need it again :D

**Comment by bdech** [comment]
sounds good haha.

**Comment by bdech** [comment]
Production access removed.
