### ISSUE TITLE
Audit breadcrumbs on React apps

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#6582]
During this ticket, https://github.com/department-of-veterans-affairs/va.gov-team/issues/6381, we discovered and fixed some inconsistencies with the breadcrumbs on React apps, including -

1. https://staging.va.gov/burials-and-memorials/application/530
1. https://staging.va.gov/education/opt-out-information-sharing/opt-out-form-0993
1. https://staging.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/vettec-high-tech-program/apply-for-vettec-form-22-0994
1. https://staging.va.gov/education/apply-for-education-benefits/application/1990
1. https://staging.va.gov/education/apply-for-education-benefits/application/1990E
1. https://staging.va.gov/education/apply-for-education-benefits/application/1990N
1. https://staging.va.gov/education/apply-for-education-benefits/application/1995
1. https://staging.va.gov/education/apply-for-education-benefits/application/549
1. https://staging.va.gov/health-care/apply/application
1. https://staging.va.gov/pension/application/527EZ
1. https://staging.va.gov/records/get-veteran-id-cards/apply

Although we improved the breadcrumbs, we aren't certain of their correctness. These applications are sort of strange, in that as React apps, the breadcrumbs aren't configured in Drupal and are instead hard-coded in the front-end code. Additionally, some of the forms retain paths from Vets.gov days, so the parent directories don't have any pages.

### Acceptance criteria
- [x] Issues with breadcrumbs on React apps have been identified

**Comment by mnorthuis** [comment]
@ncksllvn There are a couple that are incorrect.  The applications technically are not nested under the "How to apply" pages, they are at the same level in the IA, however many of them were brought over with incorrect URL structures so its hard to tell.    I have listed the 2 that are incorrect below. 

The education applications are all technically incorrect, but I'd like to leave them right now until we do the work on the wizards. 

URL | Correct breadcrumb
--- | ---
https://staging.va.gov/health-care/apply/application | Home > Health care > Apply for VA health care
https://staging.va.gov/pension/application/527EZ | Home > Pension benefits > Apply for a Veterans Pension

**Comment by kelsonic** [comment]
Unassigned Nick but this is still a problem @brianalloyd

**Comment by mnorthuis** [comment]
I'll pull this into my queue to review...

**Comment by mnorthuis** [comment]
Reviewed these and identified 4 of them that could be updated now and a few others that can wait until the wizard work in Education is done.  

1. ~https://staging.va.gov/burials-and-memorials/application/530~ OK
1. ~https://staging.va.gov/education/opt-out-information-sharing/opt-out-form-0993~ OK
1. ~https://staging.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/vettec-high-tech-program/apply-for-vettec-form-22-0994~ OK FOR NOW - IA for this likely needs to be updated, moving to use the full H1 in the last segment will create a very long breadcrumb that wraps, and this essentially matches what other education benefits have currently.  Will leave this for now.
1. ~https://staging.va.gov/education/apply-for-education-benefits/application/1990~ This will be fixed once we move the wizard, then we can remove "How to apply" from the breadcrumb.
1. ~https://staging.va.gov/education/apply-for-education-benefits/application/1990E~ This will be fixed once we move the wizard, then we can remove "How to apply" from the breadcrumb.
1. ~https://staging.va.gov/education/apply-for-education-benefits/application/1990N~ This will be fixed once we move the wizard, then we can remove "How to apply" from the breadcrumb.
1. ~https://staging.va.gov/education/apply-for-education-benefits/application/1995~ OK
1. https://staging.va.gov/education/apply-for-education-benefits/application/5495 <br> **This one should be changed to** [Home](https://www.va.gov) > [Education and training](https://www.va.gov/education/) > [Change your GI Bill school or program](https://www.va.gov/education/change-gi-bill-benefits/) > Change your dependent benefits VA Form 22-5495
1. https://staging.va.gov/health-care/apply/application <br>**This one should be changed** remove "How to apply" from path
1. https://staging.va.gov/pension/application/527EZ <br>**This one should be changed** remove "How to apply" from path
1. https://staging.va.gov/records/get-veteran-id-cards/apply <br> **This one should be changed to**  [Home](https://www.va.gov/) > [Records](https://www.va.gov/records/) > [Types of Veteran ID cards](https://www.va.gov/records/get-veteran-id-cards/) > [How to apply for a Veteran ID Card](https://www.va.gov/records/get-veteran-id-cards/vic/) > Request a printed Veteran ID Card

**Comment by brianalloyd** [comment]
Thanks @mnorthuis we'll move this into scope for action.  Appreciate the follow up in support.

**Comment by kelsonic** [comment]
Hey @mnorthuis the PR is linked above, but one of these breadcrumbs look really long, is that desired?

![image](https://user-images.githubusercontent.com/12773166/136065044-380c17bf-1722-40ea-8938-1a0994c68ecd.png)

**Comment by mnorthuis** [comment]
Yes, that is fine...it is not ideal, but that is the valid breadcrumb.  Thank you!

**Comment by kelsonic** [comment]
PR merged, will go out with the daily tomorrow 🙂
