### ISSUE TITLE
BQ Auto Run Set Up

### ISSUE THREAD

**Issue by GitSamJennings** [department-of-veterans-affairs/va.gov-team#65823]
# Request an update to your KPI Dashboard  

## What this form is for

We want to have the query automatically ran and results sent to us daily for review. This would be helpful, as we are manually running and reviewing. This query helps us identify potential errors in notifications.

### Expected delivery timelines

There's no hard deadline but we would appreciate it being set up as soon as the Analytics team can pull it into their sprints.

## Instructions for the VFS team
First, tell us what type of change you need to make:

- [x] Run the following each weekday in BigQuery https://console.cloud.google.com/bigquery?sq=86772881199:217968ad8db140eba72cd94c7b3b6c4c
- [x] Export results  
- [x] Send daily to oitoctovanotify@va.gov

**Additional Info**

**Comment by michelle-dooley** [comment]
@GitSamJennings we will review and get back to you with timing.

**Comment by GitSamJennings** [comment]
@michelle-dooley we are seeing the export in our shared email but it is missing the name of the template and it is titled 'BBQ'. 
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/132367046/ea91d44c-cc56-43d8-a8c9-d5d3e2503823)

**Comment by michelle-dooley** [comment]
@dorseypa1 can you take a look ^^

**Comment by dorseypa1** [comment]
I used the query provided for the report, https://console.cloud.google.com/bigquery?sq=86772881199:217968ad8db140eba72cd94c7b3b6c4c, so the template_name is directly from that query.  @GitSamJennings, Which field from the table has the value you would like?

**Comment by dorseypa1** [comment]
@GitSamJennings, never mind about the template_name, I found the issue.  tomorrows run should show correctly

**Comment by GitSamJennings** [comment]
Thanks for updating that! There's one more thing. Today's date is coming through as yesterday's:
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/132367046/384a510c-7660-4d91-8ce0-46e53a3778ca)

**Comment by dorseypa1** [comment]
It is most likely a timing issue.  I'm guessing that the dataset refresh did not complete before the scheduled report started.  I'll adjust the timings of both

**Comment by dorseypa1** [comment]
Today's run of the report seems correct.  @GitSamJennings , can you confirm that it looks correct? 
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/117392065/4ceef7f7-ef68-4b72-a0e2-511e50bba724)

**Comment by GitSamJennings** [comment]
We received two yesterday but we did not receive one today. The content in what you shared looks correct but we have yet to receive it.

**Comment by dorseypa1** [comment]
I manually sent the second file yesterday to make sure you had it since the auto run had a timing issue.   @michelle-dooley , did you receive the emailed report?

**Comment by dorseypa1** [comment]
@GitSamJennings , I will resend today's file manually, but it seems like Michelle also received the scheduled version, so can you make sure the email wasn't sent to the spam folder for oitoctovanotify@va.gov ?

**Comment by GitSamJennings** [comment]
I just received the manual resend of the file. However, I am not seeing the scheduled version anywhere, including the spam folder.

**Comment by michelle-dooley** [comment]
Closing ticket as this work is complete.

**Comment by GitSamJennings** [comment]
Can you please reopen this @michelle-dooley, as there are still discrepancies? It seems to be a day behind what BigQuery returns, even though "today's date" is correct. We are thinking this may be a Domo timing issue. cc @bevnobev and @mjones-oddball

**Comment by dorseypa1** [comment]
I agree it is probably a timing issue of when the paltform_notify tables
update completes and when the Domo data set load starts.  I don't have any
information on the platform_notify processing so I don't know when
processing kicks off or how long it usually takes to complete.  If you can
share that information it would be helpful.  For the time being I will push
the Domo load and the subsequent report send back an hour.

**Comment by mjones-oddball** [comment]
@dorseypa1 @michelle-dooley I don't recall the exact times. I think it was after 10 AM though I'm not sure why because BQ updates overnight. Is it possible to move the Domo data refresh earlier in the morning, like 6 am or something?

**Comment by dorseypa1** [comment]
I refreshed the Domo data set manually at around 9:30AM and then it matched
the BQ data exactly so I moved the Domo refresh back so that it will run at
10:00 AM CST and the report will be sent at 11:00 AM CST.  Let's see if
tomorrow's report matches with BQ.
