### ISSUE TITLE
[Github Runners] GithubRunnersLambdaFailing

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#65849]
## Description
Between the time it takes to list out all of the ASG's EC2's and the trigger to remove the EC2, the EC2 could already be in a terminating state. If the instance is already terminating, we need to ignore it instead of throwing an error

## Notes
- https://us-gov-west-1.console.amazonaws-us-gov.com/lambda/home?region=us-gov-west-1#/functions/gha-runner-cleanup?tab=code
- https://github.com/department-of-veterans-affairs/devops/blob/master/scripts/github-runner-cleaup/lambda_function.rb

**Comment by ph-One** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdnJKIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6097aec6102812ec2b183ba381e1e4cecc4690a1/image.png)

**Comment by ph-One** [comment]
```	2023-08-01T08:06:40.080-04:00

Copy
{
    "errorMessage": "The instance i-0833686536bbd570e is not in InService or EnteringStandby or Standby.",
    "errorType": "Function<Aws::AutoScaling::Errors::ValidationError>",
    "stackTrace": [
        "/var/runtime/gems/aws-sdk-core-3.131.4/lib/seahorse/client/plugins/raise_response_errors.rb:17:in `call'",
        "/var/runtime/gems/aws-sdk-core-3.131.4/lib/aws-sdk-core/plugins/checksum_algorithm.rb:111:in `call'",
        "/var/runtime/gems/aws-sdk-core-3.131.4/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:16:in `call'",
        "/var/runtime/gems/aws-sdk-core-3.131.4/lib/aws-sdk-core/plugins/idempotency_token.rb:19:in `call'",
        "/var/runtime/gems/aws-sdk-core-3.131.4/lib/aws-sdk-core/plugins/param_converter.rb:26:in `call'",
        "/var/runtime/gems/aws-sdk-core-3.131.4/lib/seahorse/client/plugins/request_callback.rb:71:in `call'",
        "/var/runtime/gems/aws-sdk-core-3.131.4/lib/aws-sdk-core/plugins/response_paging.rb:12:in `call'",
        "/var/runtime/gems/aws-sdk-core-3.131.4/lib/seahorse/client/plugins/response_target.rb:24:in `call'",
        "/var/runtime/gems/aws-sdk-core-3.131.4/lib/seahorse/client/request.rb:72:in `send_request'",
        "/var/runtime/gems/aws-sdk-autoscaling-1.80.0/lib/aws-sdk-autoscaling/client.rb:5801:in `set_instance_protection'",
        "/var/task/lambda_function.rb:125:in `block in lambda_handler'",
        "/var/task/lambda_function.rb:29:in `each'",
        "/var/task/lambda_function.rb:29:in `lambda_handler'"
    ]
}```

**Comment by npeterson54** [comment]
In the devops repo

**Comment by ph-One** [comment]
Closed by https://github.com/department-of-veterans-affairs/devops/pull/13678/files

**Comment by ph-One** [comment]
CloudWatch logs for reference https://us-gov-west-1.console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#logsV2:log-groups/log-group/$252Faws$252Flambda$252Fgha-runner-cleanup/log-events/2024$252F10$252F22$252F$255B$2524LATEST$255D35fe39302adb427b8d7056abfe0e34c9
