### ISSUE TITLE
ITF Async Spike

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#65857]
Investigate technical options and land on proposal

Next steps:

1. Review with Emily and get feedback for scope and determine if technical

Acceptance criteria:

1. Research technical ability to implement async ITF queue
2. Generate open questions about technical and policy decisions needed to be considered
3. Close out questions and/or offload open questions

Note: Implementation will be handled in separate tickets and go through full collab cycle including UX and design

**Comment by SamStuckey** [comment]
Resulting Document complete with front end and back end PRs.  Note that given that this is a spike, this is not tested, but is rather intended for discussion about the feasibility of this implementation

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/engineering_research/ITF_async_proposal.md
