### ISSUE TITLE
Create Veteran journey map drafts and sketches for accessing healthcare

### ISSUE THREAD

**Issue by skirkman16** [department-of-veterans-affairs/va.gov-team#65862]
Seek out inspiration from external examples and capture the desired user journey in a visual model or sketch. The drafts of the visuals will be reviewed, combined, and iterated upon before they are presented alongside the VA roadmap. 
 
## Tasks

- [x] Research examples
- [x] Create drafts and sketches and link them to ticket

## Acceptance Criteria

- [x] Share out murals with the team for internal feedback

**Comment by skirkman16** [comment]
Murals will be shared Friday morning 9/22

**Comment by MOStudioCarolyn** [comment]
Met 9/26 to review Mural https://app.mural.co/t/innovationboards1199/m/innovationboards1199/1695041576761/a482dba6ff5d97bc0af7bbcd8893ba41dcea3f03?sender=u1e2c263656ad89ecadb41603 
Will meet 9/28 to cocreate
