### ISSUE TITLE
Pull out Wireframes into Own Sketch Page

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#65868]
## Tasks
- Pull out [Wireframes ](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/AZPZPVR)into the 45-minute Sketch page
- Use this page - Design - [Send out 45 min check in text](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/0D0F05D2-2122-4599-9378-E03EEE32DB88/canvas#Version)

**Comment by benbrasso-agile6** [comment]
https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/v/7r7ej8/p/0D0F05D2-2122-4599-9378-E03EEE32DB88/canvas/#Version

Done

@kellysmith1008 is working on the second part of this Epic, which is https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/65869

No rush though. 

Tossing this in validate. @kellysmith1008 Mind validating it for me?

**Comment by kellysmith1008** [comment]
@benbrasso-agile6 Do you think it's worth pulling the artboards for the 45-minute text message with the mobile app information included? If not, that's ok, just a thought. If you want to include them, they're in the 62955 feature in the sketch file. Otherwise looks good and it's the correct text message

**Comment by benbrasso-agile6** [comment]
Thanks. That's not a bad thought and reminder. Let me take a look real quick.

**Comment by benbrasso-agile6** [comment]
Added/updated

Closing 

https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/v/7r7ej8/p/0D0F05D2-2122-4599-9378-E03EEE32DB88/canvas/#Version
