### ISSUE TITLE
Remove Flipper for  Null Claim - 674 Only Submission

### ISSUE THREAD

**Issue by tblackwe** [department-of-veterans-affairs/va.gov-team#65866]
Remove the `:dependents_submit_674_independently` flipper established by [64918](https://app.zenhub.com/workspaces/benefits-dependents-experience-6459139e7d64bf0015f6af13/issues/gh/department-of-veterans-affairs/va.gov-team/64918)

**Comment by sortizsh** [comment]
Use this as the same ticket to clean up the flippers for https://github.com/department-of-veterans-affairs/va.gov-team/issues/65400
