### ISSUE TITLE
Identity and document all Benefits Management tools use of Sidekiq jobs

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#65870]
## Background

As request from Code Yellow / CTO we are performing an audit of all Sidekiq jobs as reliable and fault aware.

First step is to document all cases where all our applications are using Sidekiq.

## Acceptance criteria:

- [x] Identify and document in Github all Benefits Management Tools Sidekiq jobs

**Comment by jerekshoe** [comment]
**Update:** I talked to Steve Albers and got the spreadsheet he is using. I updated it with the most up-to-date info that I have on this teams Sidekiq jobs and sent it back to him. I will discuss with him on Monday (10/23) and make sure that he doesn't see any issues before closing this issue
