### ISSUE TITLE
Request access to Google Analytics and/or Domo

### ISSUE THREAD

**Issue by risatrix** [department-of-veterans-affairs/va.gov-team#65873]
# Request Google Analytics and/or Domo access

## What this form is for
Use this template to request access to Google Analytics and/or Domo. Please complete steps 1 & 2 below. 

## 1. Access Requirements 
Please check the analytics tool(s) you need access to:
- [ x] Google Analytics
- [x ] Domo
- [x ] (Platform Teams only) BigQuery

_ If you are requesting BigQuery access, please share if you will be hooking up an API._

Unsure. I am collaborating with Megan Kelly on VES Measurement work, and need the same permissions she has.

_Once you receive access, you should receive a confirmation email directly from Google or Domo._

 
---

### Definition of Done
- [ ] Provide access to user
- [ ] Ensure user received email confirmation

**Comment by ChristineYoungZA** [comment]
Thanks @risatrix access has been granted to Domo and GA. Michelle Dooley can you provide access to Big Query?

**Comment by michelle-dooley** [comment]
BQ access granted.
