### ISSUE TITLE
Contact Center Review for VA Health and Benefits App - Proof of Veteran status feature - Updated Product Guide 7.2

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va.gov-team#65883]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
VA Flagship App also know as the VA Health and Benefits App is adding a new feature call Proof of Veteran statues.  This feature is planned to be released in the mobile app on 10/10. 

This feature required the Product Guide to be updated. The following changes were made to the VA: Health and Benefits App guide:
- Add Proof of Veteran status - page 12 (new content)
- Updated all the existing home page images to reflect addition of Proof of Veteran status
- Updated all the existing Profile page images to reflect addition of Proof of Veteran status
- Updated formatting when handling images throughout the guide for consistency 
- Updated the page numbers for the entire guide as it was outdated 
- Added images to Payments section as they were missing (new content)
- Added images to Secure Messages as they were missing (new content)

Proof of Veteran status feature overview:

- Users will find this feature in their name tag under their branch of service called “Proof of Veteran status”. When users tap “Proof of Veteran Status” they will be taken to a scrollable page that provides details that the Veteran can display to prove they are a Veteran. This can be used to receive non-VA privileges like discounts on memberships, purchases, etc. that merchants allow. 
- While similar to Veteran Identification Card (VIC), this is not part of that program. Veterans who are dishonorably discharged will not see this feature and it does not entitle the user to any VA benefits. This can also be found through the nametag feature on the Profile page.

### Launch Date
10/10/23

### Version Number
VA Mobile App Product Guide 7.2

### Product Guide
[VA Mobile App Product Guide 7.2.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/12662749/VA.Mobile.App.Product.Guide.7.2.docx)

### Product Video
NA

### Product Video Transcript
NA

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
Hi Adam (@bischoffa). The changes/additions to the draft look good. I will forward to VEO for their review.

**Comment by starlow00** [comment]
No changes from VEO. Updated draft attached for future use/updates.

[Uploading... VA.Mobile.App.Product.Guide.7.2 SRT 09252023.docx]

**Comment by starlow00** [comment]
[VA.Mobile.App.Product.Guide.7.2 SRT 09252023.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdURxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3aab2845f27d85c68cef0d8f6df26564a43593e4/VA.Mobile.App.Product.Guide.7.2%20SRT%2009252023.docx)
