### ISSUE TITLE
Adding Abbie Burton to DSVA Slack

### ISSUE THREAD

**Issue by haivi** [department-of-veterans-affairs/va.gov-team#65895]
Please re-activate Abbie Burton as a 

- Full member

- What channel(s) do they need to be added to?
#long-covid-public
#long-covid-team
#long-covid-leadership

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.
Abbie Burton will be the Product Manager supporting the Long COVID team / Marian Adley under the DTC contract.

We aim to complete slack requests within 24hrs.

## Sample Descriptions 

- Please add abbie.burton@thoughtworks.com as a full member.

**Comment by burtonabbie** [comment]
Hello, It looks like this ticket was closed, but my account is still deactivated when I try to log in 

<img width="613" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/115190165/7aadcb48-4f8c-444a-9e08-d31f78c05a38">
