### ISSUE TITLE
Veterans Appeal Status incorrect 

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#659]
### Status

In Progress
[ Case Flow Issue](https://github.com/department-of-veterans-affairs/caseflow/issues/11705)

### Severity Analysis

Unclear to the severity of this issue

### User Impact 

Unclear at the moment, because the issue resides in caseflow there has yet to be a user impact analysis.

### Description

- A call center rep is reporting a discrepancy on an appeal that she is seeing on va.gov.  She is reporting that there are a number of claims she does not recall ever making, in addition there is an appeal that she is unaware of, and a decision (granting the appeal) to that appeal.
- She also reports multiple callers reporting appeal decisions that are incorrect from years prior.

### Further Details

After further investigation there has been an issue discovered in CaseFlow where:
If something has an "A" disposition, that means that the Veteran filed an appeal, but VBA granted it in full before it reached the Board. So appeals with an "A" disposition never get to the Board, and should never display as having a Board decision, or as having a pending VA Form 9.

### Proposed Solution

[Case flow ticket](https://github.com/department-of-veterans-affairs/caseflow/issues/11705)

![SnipImage 2.jpg](https://images.zenhubusercontent.com/5d0d04b74cffae4475d77c10/da006d49-da46-4b15-b55a-e0de14825fbe)

![SnipImageV2.jpg](https://images.zenhubusercontent.com/5d0d04b74cffae4475d77c10/6cdd03d4-74b9-4ff6-86c5-ec4097ae337e)

![SnipImage 3.jpg](https://images.zenhubusercontent.com/5d0d04b74cffae4475d77c10/12f99796-a77a-41c6-95ff-60c2540d6c51)

**Comment by alexpappasoddball** [comment]
Alex to figure out how to get a user to demonstrate the issue.

**Comment by alexpappasoddball** [comment]
Currently working with Andrea Schneider on this issue.  I have reached out to Todd Unger who is the call center lead to see if the rep would be willing to walk us through exactly what they are seeing on their account so we can better understand/document the issue that is happening.

Waiting to hear back from Todd....

**Comment by alexpappasoddball** [comment]
@AZSchneider Here are the answer to the questions asked to the call center rep:

Q: Is she currently recieveing benefits:
A: "Yes, I am receiving benefits."

Q: when you get a caller referring to an appeal that got granted, how do you determine if that appeal is accurate and if the appeal status is even correct?  Is there something you do to verify it?
A: No, we have no access to any records here at the WHVA hotline. I transfer them to the national call center at 1.800.827.1000.

**Comment by pkarman** [comment]
The veteran has one legacy appeal, no longer active, with a NOD date of 28 Oct 2010. The Caseflow status API returns that single legacy appeal.

**Comment by alexpappasoddball** [comment]
From Premal:

This is the issue
If something has an "A" disposition, that means that the Veteran filed an appeal, but VBA granted it in full before it reached the Board. So appeals with an "A" disposition never get to the Board, and should never display as having a Board decision, or as having a pending VA Form 9.

**Comment by alexpappasoddball** [comment]
As far as the Triage team goes, the issue has been identified and the issue has been logged with the appropriate team for resolution (ticket linked in the Status and Proposed Solution sections) therefore this ticket will now be closed.
