### ISSUE TITLE
Backup plan when no one on CC touchpoint call can record

### ISSUE THREAD

**Issue by briandeconinck** [department-of-veterans-affairs/va.gov-team#65904]
## User Story
_"As the Governance team member on support, I want to know how to claim hosting permissions in Zoom, so that Collab Cycle touchpoint meetings can proceed smoothly."_

Assignee:
Peer Reviewer:

## Description
At the 9/19/2023 Midpoint Review, Shira was out of office and Allison was called away for a family situation about five minutes before the meeting was scheduled to begin. Since Shira and Allison are the two Oddball members of the team and the two people with host/co-host permissions on all our touchpoint meetings, no one else in the meeting had permission to start the recording.

In this instance, Allison was able to briefly join to kick off the recording and then leave. But in the future, the meeting moderator should have a clear backup plan for what to do next.

Four candidate backup plans:
1. Ping Naomi or Peter, two other Oddball folks who have co-host powers and can kick off the recording. Wait for them to join before beginning the meeting.
2. Use the [host key](https://support.zoom.us/hc/en-us/articles/205172555-Using-your-host-key) to claim host permissions. Need to investigate to see if this is actually a solution. If it is, Shira can save the host keys for each CC timeslot in Confluence.
3. Everyone bails to another Zoom meeting launched by the moderator, who then records on their Zoom account. (Lots of moving parts to get everyone to the right meeting though.)
4. We don't worry about recording and just make sure everything that's said makes it into the written feedback.

At 9/25/2023 refinement meeting, team decided to look into option 2 above. If that is not a feasible path, we will pursue option 3. 

## Impacted Artifacts
- Design Intent - Moderator Responsibilities
- Midpoint Review - Moderator Responsibilities
- Staging Review - Moderator Responsibilities
- Zoom information for Collab Cycle meetings (possibly)

## Tasks
- [ ] _Placeholder task_

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] _Placeholder AC_

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [ ] Ticket has user story, description, tasks, and acceptance criteria
- [ ] Ticket has been sized 
- [ ] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [ ] Ticket has been assigned to appropriate initiative or quarterly epic
- [ ] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
no back up plan needed. if no one is on the call to record, we won't be able to record. Ticket can be closed.
