### ISSUE TITLE
Add Container and Sequence diagrams for Authenticated check-in flow

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#65907]
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/engineering/architecture-diagrams

**Comment by randomsync** [comment]
added here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/architecture-diagrams/sequenceDiagram_full_auth_checkInExp.md
