### ISSUE TITLE
[CHIP] Update CHIP to Set eCheckInStarted Status when Reminder Link Clicked & Veteran has Authenticated

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#65910]
## Background
Currently, when the Veteran texts "check in" to 53079 and receives a check-in link back, we go ahead and set the eCheckinStarted status so that the clinical staff will know that the Veteran has started the check-in process. However, now that we are sending a link to the Veteran via text 45 minutes before their appointment, the Veteran will no longer need to text "check in" to 53079 and we need a way to let clinical staff know that the Veteran has started the check-in process.

The group has decided (see [Slack thread](https://dsva.slack.com/archives/C022AC2STBM/p1695051805611999?thread_ts=1695048379.114739&cid=C022AC2STBM)] that when the Veteran clicks the link from the 45-minute text reminder AND authenticates, we will set the eCheckInStarted status, but only if it has not already been set (i.e. is null).

**If the eCheckInStarted status has not already been set, set it when Veteran authenticates successfully in the day-of check-in application**
    - NOTE: I don't think it matters whether they texted "check in" or clicked the reminder link; when they authenticate in the Check-in application, we check to see if the eCheckInStarted has been set; if it has, we don't touch it, if it hasn't we set it at this point; if they texted "check in" then it would have already been set, if they came in through the reminder link then we will set it now

## Tasks
- Add CHIP endpoint to set eCheckInStarted status

## Acceptance Criteria
- [ ] Deployed to staging
- [ ] Tested on staging

**Comment by brianseek** [comment]
closing ticket, work is in pre-release 3.4.0 https://github.com/department-of-veterans-affairs/chip/releases/tag/v3.4.0
