### ISSUE TITLE
[a11y attend meeting] Design Intent: Accredited Representation Management - Launching an MVP 9/25/2023

### ISSUE THREAD

**Issue by sara-amanda** [department-of-veterans-affairs/va.gov-team#65938]
## Design Intent

- Date: Sept. 25, 2023
- Time: 3:30 - 4 p.m. 
- Location: No zoom link yet in Collab Cycle Calendar (as of 9/20/2023) - `check back`
- Notes: [CAIA Notes](https://docs.google.com/document/d/1eZQBR1KHnhkQWVO_ExnmphGoxf2p1YEa1aSKeARHXv8/edit?usp=sharing)

**Comment by sara-amanda** [comment]
## Creating Issues from Tasklists in GitHub
- Converting a tasklist item to an issue in GitHub does not carry over any assignees, labels or project fields. 
- The following were added to this issue, as a test of the task list to issue feature: 
    - [x] **Labels**: `sitewide accessibility ``sitewide CAIA`
    - [x] **Projects**: Sitewide CAIA (upon saving - GHP fields can be edited/updated, such as open date, priority, estimates, etc.)

cc: @coforma-jamie @ohgreatkate @coforma-terry

**Comment by ohgreatkate** [comment]
created notes template from previous design intent calls and linked above.
