### ISSUE TITLE
Sidekiq Review (Code Yellow)

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#65940]
We need to fill out the information listed in this ticket for these two jobs:

- Form526ConfirmationEmailJob app/workers/form526_confirmation_email_job.rb
- CentralMail::SubmitForm4142Job in file app/workers/central_mail/submit_form4142_job.rb (526)

https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/1273

Please answer the following Questions:
Does your team own all of the Jobs listed in this request? Please list any that you do not believe you own, or suggest missing items that you do.

Non-Disability Benefits Experience Team (Laura Steele):
VRE::Submit1900Job app/workers/vre/submit1900_job.rb
Disability Benefits Experience 2 (Austin Price):
Form526ConfirmationEmailJob app/workers/form526_confirmation_email_job.rb
Of the jobs listed, which are involved in a veteran-facing workflow?

For veteran facing jobs, what happens if they fail? Is the veteran notified? If so, how?

Please provide links to any existing dashboards, monitors and alerts for these background jobs

For each job, please note any ways it has failed in the past. (Temporary failures resolved by retries do not need to be included) Can it still fail in this manner?

**Comment by austinjprice** [comment]
Still waiting for response from Steve if other jobs need to be considered, but lets get the questions answered for these two

**Comment by NB28VT** [comment]
@austinjprice should we list our findings in this ticket or in the CY team's [one](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/1273)?

**Comment by austinjamesprice** [comment]
The og CY one please
