### ISSUE TITLE
[FSR] Discovery of Review error handling

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#65950]
## Ticket creation

<details><summary>Ticket requirements</summary>

### Required to be "Ready"
- [x] Description
- [x] Add Labels
- [x] Attach to an Epic
- [x] Estimate Points
- [x] Testing defined
- [x] Acceptance criteria
</details>

## Description

This is a discovery ticket to identify the following:
- How do we ensure our downstream services are receiving/processing submissions?
- What changes do we need to make (if any) in our current process to be alerted when issues arise?
- In the event an issue occurs, how are we capturing the impacted Veterans and what are we doing to ensure those submissions are processed correctly?
- When capturing the impacted Veterans, make a list of personal info that we would like (Define if it is PII).

## Testing
- [X] N/A if non development work
- [ ] Testing passed and documented in this ticket

Testing procedure:

## Acceptance criteria

- [x] Items in the description are defined and completed [here.](https://docs.google.com/document/d/1ocvuWGciMVwvEEhXp13hjrPrvI1icl6AccgOVOU3Xuw/edit)
- [x] Draft code change ticket - add follow on ticket to #65397

**Comment by HeatherRienks** [comment]
Will start a Google doc to collaborate async on this.
