### ISSUE TITLE
SOCKS access for [Jamie Klenetsky Fay]

### ISSUE THREAD

**Issue by coforma-jamie** [department-of-veterans-affairs/va.gov-team#65969]
### Your Name

Jamie Klenetsky Fay

### Your Email

jamie.klenetsky@coforma.io

### Your Role and Team

A11y specialist on CAIA

### Product Manager (PM) name and email

Terry Nichols terry.nichols@coforma.io

### Product Owner (PO) name and email

Danielle Thierry danielle.thierry@va.gov

### Access Type Requesting

viewers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC5bYu0XaQC+82rLAj/zlbTvnW1YUba1Ge5RlDT0LxoWE2ZsGXpShRok+gedccA1n5LBZ9FQua33YOXM9ro4sS6ZAPPAtOaixOyMpKgcsJQrC+quqakTIdIrzE/GuKy+uYuovnBy5SwAku/WH64B8UJU2Uo4gdmmjaO7Ul+RZAG+ArJN4y6/6QdjxoUbVw/KjNgAGr3bgYyWHf59H34VXHrjuvCIZlSBCoUkuQ8cokdG2uhhECUXw74/33CwwjXOdtgFO+fB1Y7sGo1C82xP4A4TYT8IyHrjURDkWwDAWvnKtPxZegHud+povBDFtYs/+EAQOsHJ0KUjig5U3akNBPD5OcxA0f+DRX2dyM2TkO6MSpf3i7NyGQ84SldgCPPXCeQSzjePJzpFFm3Bd6ySdN176djVwJoHg7+l9Bebbu4aKeKzLJM81gJ8HgjaKnGFfxu7LqPKscXAhUxRg7DMRpoJkURwWJuhxfu3P4qmsQcH4ISVUEa534DPnyPoyCcBqU= jamieklenetskyfay@Coforma-VF7HWXF54C-Jamie-Klenetsky-Fay.local  

### E-QIP Transmittal Confirmation

![20230920_125506](https://github.com/department-of-veterans-affairs/va.gov-team/assets/135633989/19e18574-6ebd-4c26-bbc5-da14fc7c289b)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by ph-One** [comment]
Done
