### ISSUE TITLE
Compile full list of Sidekiq jobs related to the 526 ez applicatoin

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#65965]
As part of Code Yellow request for information we need to identify all sidekiq jobs related to 526. 

See here for partially compiled list:

[sidekiq_jobs.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbDI5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--42252b9f373bd2f540b883f3d637c7d5d96a265b/sidekiq_jobs.xlsx)

Acceptance Criteria:
- [ ] Review excel and mark jobs owned by 526 team
- [ ] Add outstanding jobs not listed
- [ ] Send to Steve Albers

**Comment by shaunburdick** [comment]
Completed during Code Yellow work.
