### ISSUE TITLE
Critical: Correct url for Current Veteran Copay Rates link on MHV landing page

### ISSUE THREAD

**Issue by fmccaf1** [department-of-veterans-affairs/va.gov-team#65960]
## Issue Description
It was discovered yesterday that an important link on the MHV landing page is leading to the wrong location.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZzI5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--aa05c19e5fa180dc87bced1e3752697340b10e23/Screenshot%202023-09-20%20at%2012.06.02%20PM.png)

The link should point to the following url: https://www.va.gov/health-care/copay-rates/

Image of the page this should link to: 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZys5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--781d7c080ac9a3d0b9738213006cfd7fca94584c/image.png)

## Acceptance Criteria
- [x] Ensure that link now points to the correct page on VA.gov (2023 copay rates)

**Comment by fmccaf1** [comment]
@radavis Here's the ticket for the wrong link mentioned during standup today. This is a critical link for users, so it's important that this is addressed asap.

**Comment by radavis** [comment]
This change will roll out with the 3PM daily release, tomorrow. We didn't quite get it merged before the 3PM window, today. 

If we want these changes in production sooner than Sep 21 @ 3-4PM Eastern, I need to look into how to initiate a manual deploy. 

Let me know if this timeframe works or not.

**Comment by LynneJohnson224** [comment]
@jzucadi @radavis can you please add a story point value?

**Comment by radavis** [comment]
Verified changes are live in staging. Changes were deployed to production on Friday of last week.

Unable to verify this change via DataDog as no one has clicked the link: https://vagov.ddog-gov.com/rum/sessions?query=%40application.id%3A1f81f762-c3fc-48c1-89d5-09d9236e340d%20%40action.name%3A%2Acopay%2A%20%40type%3Aaction&cols=&viz=stream&from_ts=1693079523000&to_ts=1695671523000&live=true
