### ISSUE TITLE
GIDS: Add feature flag / prod flag support

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#6598]
As a developer, I need to add feature flag / prod flag support to GIDS so that we can avoid a backlog of pull requests to deploy to production.

## Acceptance Criteria:
1. Feature flag / prod flag support is available to be used for GIDS
2. Crosswalk Partial Matches and Ipeds Orphans are not available in Production

## Supporting Artifacts
1. Original research story (path forward included in the comments): https://github.com/department-of-veterans-affairs/va.gov-team/issues/5755

**Comment by zurbergram** [comment]
https://github.com/rubyconfig/config#accessing-the-settings-object

A `config/settings.local.yml` file overrides any non *.local.yml file

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/602
https://github.com/department-of-veterans-affairs/devops/pull/6500

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by desireeturner** [comment]
Confirmed that feature behind prod flag is not showing in production with EDU. This can be closed.
