### ISSUE TITLE
Update ADFS Contacts

### ISSUE THREAD

**Issue by anthonycastaneda** [department-of-veterans-affairs/va.gov-team#65992]
### Description
Afroz Kokan and JD Parham no longer support ADFS.  The new contacts are:
Sheldon Wright, Sheldon.Wright@va.gov
Anthony Castaneda, Anthony.Castaneda@va.gov

### Relevant URLs
https://depo-platform-documentation.scrollhelp.site/developer-docs/active-directory-federation-services

### Which type of team are you on? (Platform team, VFS team, or Leadership)
ADFS Engineering, Authentication Services

**Comment by laucon** [comment]
Fixed. Thanks! We'll likely publish this at 3:30pm Eastern today.
