### ISSUE TITLE
[task] DR | Document Sidekiq jobs

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#65990]
Note from Steve: Hello Sade! For this Code Yellow stability project we have a request: provide a list of our sidekiq jobs.

They specifically asked us about the jobs in a couple of tickets, but I think there are others they forgot to assign to us:
department-of-veterans-affairs/va.gov-team-sensitive#1273
department-of-veterans-affairs/va.gov-team-sensitive#1268

**Comment by kylesoskin** [comment]
@saderagsdale @data-doge Both these are assigned to other teams, and also do not have any jobs owned by us in them? Are there other tickets from Bill with our jobs in it to claim ownership over and describe?

**Comment by kylesoskin** [comment]
# WIP

DecisionReview::SubmitUpload

DecisionReview::Form4142Submit

**Comment by kylesoskin** [comment]
Sent to Steve to facilitate delivery to Bill C. Closing.
