### ISSUE TITLE
SOCKS access for James Zaccardo

### ISSUE THREAD

**Issue by jzucadi** [department-of-veterans-affairs/va.gov-team#65997]
### Your Name

James Zaccardo

### Your Email

james.zaccardo@adhocteam.us

### Your Role and Team

SWE FEBE

### Product Manager (PM) name and email

Lauren Ernest 

### Product Owner (PO) name and email

Patrick Bateman 

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDBlvq9NUu3VG9Kfkr1UILWGBsW72Hga7iiKEraLbg57CSpzelyG2h3tl6HNQ8Co5EktGT5h9oMTvXGmcU47YRLE+WaR/SZISmELnn8O2BCA/7X9Ux71ighKhGD16lijRj5KEYiLaeFLFVG8YXUvmnKRUbdrDTbWXWEBbJRxOVf3JWbjztOuSIk8g4HYVU3CrtIoWyKEuge+7E/mKN1nC8lhVQfEfIEVP7h+69NpRlXBt21RQFcvhAaPL4lw72wIm767ZfnBTBD8zPdEtRjmsmmGqJkMjQAWdG2AsZYsse2rRXs/6XPDbm1ZT0F+6pzoOxrr+GfXhi72KF9lRWuAiq8v7wwHMXSRuYE5ZGdDFy0lSd4ZZ+8EeOCiKEeuQoGdC8w86DmwqhThjsPHptQMx8D45jJCgaJbJ/NM9C0t7F3M6lJs2/DP5g/pn/ZRBDG4BJ7A2VSB6SJ8GKkGF97adEWPdwD1Wh2rBoY4pXncwEPWKwq0eHRjdMhi4We/cNSnBM= james.zaccardo@jameszaccardo-Q3LW64400Q

### E-QIP Transmittal Confirmation

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/7745936/72ceacc7-5feb-409f-bbb8-57fddf4c71d5)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by ph-One** [comment]
Completed
