### ISSUE TITLE
Referencing design.va.gov on Web Governance site

### ISSUE THREAD

**Issue by jaredcunha-usds** [department-of-veterans-affairs/va.gov-team#66]
## On the homepage
https://www.va.gov/web/index.cfm

There's a reference to the USWDS, but I think we can change this reference Formation and design.va.gov. It'll likely need to be reworded. The governance site does NOT need to be rebuilt with formation.
<img width="1478" alt="Screen Shot 2019-05-08 at 1 15 09 PM" src="https://user-images.githubusercontent.com/25435289/57394384-69c28e00-7193-11e9-9b2c-f4068482bcac.png">

## Building and Managing VA Websites
https://www.va.gov/web/management/index.cfm
Under the building and management page, I think we can add a section for "design system"
![Screenshot_2019-05-08 VA Web Governance](https://user-images.githubusercontent.com/25435289/57394778-5ebc2d80-7194-11e9-9b40-0c068b92adcb.png)
 
## web standards page
https://www.va.gov/web/standards/web-standards.cfm
Though when I see the term "web standards," it's not this type of content. I tend to think of the semantic web.

https://www.va.gov/web/standards/styles-bootstrap.cfm
Maybe better to use Formation instead of Bootstrap here? For one, VA does NOT use Bootstrap on new VA.gov. Maybe we can update the copy to indicate that bootstrap is only used on teamsite pages? Then for other pages on VA.gov, please see design.va.gov?

## Resources
https://www.va.gov/web/resources/index.cfm
Can we add a link here?

**Comment by jenniferlee-dsva** [comment]
Adding places for potential cross-linking for content style guide as well. 

https://www.va.gov/web/management/content-writing.cfm
The resources section seems like an appropriate place to link to the VA.gov content style guide. 
VA.gov content style guide [LINK https://design.va.gov/content-style-guide/]
  

https://www.va.gov/web/management/content-plain-language.cfm
This page also has a resources section that could link to the VA.gov style guide.

And here as well: 
https://www.va.gov/web/management/content-formatting.cfm

And on this page: https://www.va.gov/web/standards/styles.cfm
Maybe a bullet point or some verbiage could be added, linking to the content style guide.
Example: “For content that lives on VA.gov, follow the voice, tone, and language standards in the VA.gov content style guide.”
