### ISSUE TITLE
[FE] My VA LOA1 updates: Content correction in Benefit App Drafts section

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#66009]
## Background
When a user has no benefit application drafts to show we're supposed to display the following text (per [FE documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/my-va-small-initiatives/LOA1-experience-updates/LOA1-FE-documentation.md#if-a-user-does-not-have-any-applications-in-progress-to-show)):

> You have no benefit application drafts to show.

But on staging right now we're showing:

> You have no applications in progress.

![Screenshot 2023-09-20 at 4 20 18 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/45603961/b71094cd-f695-457b-9193-6bf9c7dac791)

## Tasks
- [ ] Correct copy to match FE documentation

## Acceptance Criteria
- [ ] Content is updated to read: You have no benefit application drafts to show.

**Comment by allisonlu** [comment]
@ajakabcin 

Ready for validation on staging with any LOA1 user!

**Comment by ajakabcin** [comment]
Perfect  - thank you!
