### ISSUE TITLE
Intake: Search proofing site

### ISSUE THREAD

**Issue by porta-antiporta** [department-of-veterans-affairs/va.gov-team#66021]
# Use case

As a Veteran who has opted to proof in person, I am told where I should go so that I can complete identity verification in person

# Context

For the pilot, this page is mostly a placeholder as we likely will have 1 - 2 sites and we will just hardcode those.  

In a future story (once we know where our sites will be), we will have to understand how to limit showing IPP to say Veterans who are not in the proximity of the pilot site.

For now, would implement this story using hardcoded addresses. The value would be to integrate Google Maps (or some other geolocation API) to render the map.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdkRDIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--08ee31ecc90f657d3fa6a60556101aec63babde1/Search%20proofing%20site.png)

# Precondition

None

# Acceptance Criteria / DoD
- [ ] Page is rendered with mock data
- [ ] Landing page implementation includes mobile friendly rendering of the webapp
- [ ] Unit test coverage meets thresholds

**Comment by rdvyas** [comment]
Using the following mock ups as the basis for our implementation:
https://www.figma.com/file/PfrWKmxiQ5RjChwx6I18QE/IPP-Prototypes?type=design&node-id=336-1075&mode=design&t=Qxtp7ZKrEPlMjwdJ-0

We are implementing the following screen:

Steps to recreate:
1. External User is directed to this screen after selecting continue on Intake screen.
2. External User will enter in their zipcode (full address or city accepted?)
3. Application will make a call out to Mapping API to determine location nearest
4. External User will be presented with at least 2 locations nearest to them 
5. External User will select Location most convenient to them 
6. Once a selection has been made the user has option to Select the 'Continue' button (this should be greyed out prior to selecting a facility)
7. Use will select Continue and be directed to 'Confirm your selection' screen

User Interaction Analytics to Capture:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcWJwIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8950b67177bad937bdaae0ba18a05031f65dcc00/image.png)
