### ISSUE TITLE
Intake: Landing page

### ISSUE THREAD

**Issue by porta-antiporta** [department-of-veterans-affairs/va.gov-team#66020]
# Use case

As a Veteran who has opted to proof in person, I am aware of what is needed so that Iam able to complete the process the first time around.

# Context

At this point, the Veteran has chosen to proof in person, and selected VA's in person proofing and are now in our app, at the Landing page.

[Landing page](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdlhDIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d2152a872a953c1cef423b49bfd5420203187eef/Landing%20Page.png)

# Precondition

- The Veteran has authenticated into their Login.gov account and Login.gov has sent the Veteran to us along with the Veteran's UUID and email.

# Acceptance criteria/DoD

- [x] Proofing application has implemented the landing page

**Comment by rdvyas** [comment]
Using the following mock ups as the basis for our implementation:
https://www.figma.com/file/PfrWKmxiQ5RjChwx6I18QE/IPP-Prototypes?type=design&node-id=336-1075&mode=design&t=Qxtp7ZKrEPlMjwdJ-0

We are implementing the following screen:

Steps to recreate:
1. External user has already navigated to Login.gov site and created an IAL1 account. They have been presented with the option of doing Remote or In Person Proofing. 
2. External user selects In Person Proofing and is directed to the Intake: Landing Page noted below. 
3. External user will review Information Text and then click Continue and be directed to "Choose a nearby site" screen of the wizard. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaW5wIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--60d39f9628058d2ef15966751925bb67f10d9607/image.png)

We need to establish where the data will live for this portion as we need to track timestamps and other user interation metrics.

**Comment by rdvyas** [comment]
1. Screen: https://www.figma.com/file/PfrWKmxiQ5RjChwx6I18QE/IPP-Prototypes?type=design&node-id=336-1075&mode=design&t=Qxtp7ZKrEPlMjwdJ-0
2. Integrations
3. State
4. Persistance/Database

**Comment by moanu404** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/25701/files

PR with the frontend development progress

**Comment by moanu404** [comment]
[Uploading... image.png]

**Comment by moanu404** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdm5yIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1bc722b47cd421fb12d15fd0015e0a887652aba6/image.png)
