### ISSUE TITLE
Content review of the disability ratings page from Benefits team 1

### ISSUE THREAD

**Issue by uxgary** [department-of-veterans-affairs/va.gov-team#66049]
## About your team

- Team name: 
-	OCTO-DE product owner: **Premal Shah**
-	Product manager: **Jacob Worrell**
-	Designer: **Gary Homidas**
- Accessibility specialist: 
- Content writer: 
-	Slack channel: [#benefits-portfolio](https://dsva.slack.com/channels/benefits-portfolio)
 
### Describe what you need in a few sentences:
We're updating the Disability ratings page to address accessibility concerns. We also wanted to include additional information that maybe helpful to all veterans. Things we've included are as follows: 

-  A link to the VA math formula video - Veterans who want to know how the VA came up with the combined disability rating can visit the youtube video.
- A definition of what "total and permanent disability" means - In cases where veterans are deemed totally and permanently disabled, we want to display a tag that shows this status. We decided to add the definition on the page so veterans know what it means and what qualifies them. 

We would like a CAIA member to review/modify content as needed. Also provide feedback if this is an ideal place to a link to VA math video.

### Which are you doing?
- [ ] **Launching a new** page, tool, form, or app
- [X] **Making changes** to an existing page, tool, form, or app

### Types of Support
What areas does your team need support in? Check all that apply.
#### Content
- [ ] Collaboration on content written by your team’s dedicated content writer 
- [X] Collaboration on content if your team does not have a dedicated content writer

#### Accessibility
- [ ] Accessibility review of wireframes and/or prototypes
- [ ] Accessibility issue (general request)
- [ ] Accessibility PDF review request
- [ ] Accessibility user research support ([submit a separate, additional request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name))
- [ ] DST component or pattern 
- [ ] Something else 
#### IA
- [ ] User Flows
- [ ] Page placement
- [ ] URLs
- [ ] Breadcrumbs and Left Nav placement
- [ ] Redirects
#### Multilingual content
- [ ] Translating content
 
## Timeframe
_We guide and work alongside teams across nearly every OCTO digital product. We also work with partners across VA to lead content migration and manage all unauthenticated content on VA.gov. And we're always working to expand the VA.gov content style guide and our IA and accessibility documentation. We need to prioritize all intake requests based on our overall workload and VA and OCTO priorities._

_Tell us about your product's timeline. And we'll work with you to meet timeline needs as best we can._

### Have you worked with CAIA before? 
  - [X] Yes
  - [ ] No

### What's your team’s next step and its timing?
As soon as possible

- **Our next step is** ....
- **Provide date if available**: xx/xx/xxxx

#### Timing for your next step: 
  - [ ] Next week
  - [ ] This month
  - [ ] Next month
  - [ ] This quarter
  - [ ] Next quarter
  - [ ] 6 months
  - [ ] 1 year

### Is this timing related to a specific event or Congressionally mandated deadline?
  - [ ] Yes
  - [ ] No

### If you're conducting research, when is that starting? 
**Provide date if available:** xx/xx/xxxx
  - [ ] Next week
  - [ ] This month
  - [ ] Next month
  - [ ] This quarter
  - [ ] Next quarter
  - [ ] 6 months
  - [ ] 1 year

### Will you release this new product incrementally (for example, release to 25% of users to start)? 
  - [ ] Yes
  - [X] No
 
**Note**: _If you checked yes, we’ll reach out to discuss details about the content in the react widget (we use these widgets to display entry points for new products to a certain percentage of users who visit our static pages)._

### When do you expect to launch your product to 100% of users?
  
*Please provide an estimated date so our team can create other relevant tickets.*
- **We expect to launch our product to 100% of users on:** xx/xx/xxxx
  As soon as available.

### Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [X] No

### If no ...
- Skip to the _supporting artifacts_ section, below.
 
#### Please provide the link to your Collaboration Cycle ticket: 
- **Ticket (number)**: 
- **Collab. Cycle Ticket Opened (date)**: xx/xx/xxxx
 
#### Please check all of the phases in the Collaboration Cycle you have completed: 
- [ ] Design Intent
- [ ] Midpoint Review
- [ ] Staging
 
##### Design Intent
- [ ] Accessibility
- [ ] Content
- [ ] IA
- [ ] Translation
- [ ] Already completed, no assistance needed
- [ ] Unknown at this time
##### Midpoint
- [ ] Accessibility
- [ ] Content
- [ ] IA
- [ ] Translation
- [ ] Already completed, no assistance needed
- [ ] Unknown at this time
##### Staging
- [ ] Accessibility
- [ ] Content
- [ ] IA
- [ ] Translation
- [ ] Already completed, no assistance needed
- [ ] Unknown at this time
  
## Supporting artifacts
*Please provide links to supporting artifacts as available.*
- **Product outline**:
- **User flows**:
- **Prototype or mockups**: [Sketch file](https://sketch.com/s/6186e45f-d6cb-4c59-aa84-60dbe4482be4)
- **If this is in Sketch, which version or specific page should we focus on?** New design
- **Content source of truth**: [current page in Staging](https://staging.va.gov/disability/view-disability-rating/rating?postLogin=true)
- **Research plan:**
- **Any epics/issues that may be helpful**:
- **Link to testing accounts** (please do not paste them in this ticket): 

### Have you already worked with someone from OCTO leadership?
- [ ] Danielle
- [X] Beth
- [ ] Mikki
- [ ] Martha

### How do you plan to work with us on this request?
- [ ] I’ll take this to Beth or Danielle’s office hours.
- [ ] I’d like to schedule time to talk about this.
- [X] Let’s work async and meet as needed.
- [ ] Schedule a kick-off call with your team and CAIA for your project **(Recommended)**

 
### Accessibility Help in Slack
The [#accessibility-help channel](https://dsva.slack.com/archives/C8E985R32) in the DSVA Slack, is also available to you as a resource. Everyone is welcome to ask questions or get help from our a11y (accessibility) specialists. Tag `@Terry Nichols` to get a11y help asap.

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag `@Terry Nichols`.**

- If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
- If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)
 
 - If you are creating an [experimental design,](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) please [also contact the DST. ](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)

- If you are requesting [a11y support for user research,](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name) please complete this form, next.

**Comment by katherine-fung** [comment]
Hi @uxgary @jacobworrell @pshahVA, 

Thanks for these mockups. I have some clarifying questions as I conduct the content review.  

- In the section "Things to know about your VA rating," will the paragraph starting with "Based on your service-connected conditions, you might qualify as permanently and total disabled..." only appear for people with 100% combined ratings? If someone has a less than a 100% combined rating, what will this section say? 

- For the section "Conditions VA determined aren't service-connected," can you please explain what types of conditions this section should show? I ask because VA only assigns disability ratings to service-connected conditions. 

- Who will the "permanent and total disability" tag show for? Veterans who have a 100% combined rating for static conditions, and Veterans who have had a 100% combined rating for more than 20 years? 

- Will there also be tags that say either "total disability" or "permanent disability" if someone's disability is not both permanent and total? 

- For my own understanding, in the mockup, we say that the Veteran may qualify as permanently and totally disabled. But only one of their conditions is static, with a 70% disability rating. The other condition has a 30% rating, but is not static. If the Veteran has only had these disability ratings for 5 years, for example, does this mean the Veteran currently has a total disability and not a permanent one? But if the combined rating has stayed 100% for 20 years, it would be considered permanent?

- Can you share any other information about the user story that would be helpful as I review the content? For example, do we know if Veterans find the "Learn about VA disability ratings" section at the bottom of the screen helpful?

Thanks in advance for clarifying this information!

**Comment by uxgary** [comment]
Hey @katherine-fung these are great questions. I actually had a brief discussion with the team. We will be making some updates. I will ping you soon.

**Comment by uxgary** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2dUQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a28f9915e83c23e086696818ffed554427340cfb/Disability%20rating-new.jpeg)

@katherine-fung We've reevaluated the concept and decided our initial pass will be to resolve the accessibility issue as it pertains to the ticket. Afterwards, we'll plan out features for adding tags and content surrounding permanent and total disability ratings. 

That being said, I'm not sure if there's anything for you to edit in the attached concept, but please give it a look at let us know if anything "jumps out at you". Thank you again.

**Comment by katherine-fung** [comment]
Thanks @uxgary! I just have one question about the "100% combined disability rating" header. 

The page menu at the top of the screen has jump links that usually pull from the headers. The jump link for the combined disability rating section says "Your combined disability rating"

Would we program the jump link text ("Your combined disability rating") to be different than the section header ("100% combined disability rating"). If so, that's fine, just wanted to check on the relationship and technical aspect there.

**Comment by uxgary** [comment]
Thank you again. I just confirmed with the engineers. They will make so that the jump link still reads "Your combined disability rating".

**Comment by katherine-fung** [comment]
Thanks @uxgary. Sorry for all the back and forth - I just spoke with an accessibility expert on the CAIA team. They recommend making the header match the jump link text. They said it's best practice in most cases, including this one. 

Their recommendation is this: 

[jump link text] Your combined disability rating 
... 
[H2] Your combined disability rating 

Your combined disability rating is [dynamic number]%. 

This rating doesn't include any conditions from claims that we're still reviewing. You can check the status of your disability claims, decision reviews, or appeals online.

[link to CST] Check the status of your claims, decision reviews, or appeals online

**Comment by uxgary** [comment]
It's ok @katherine-fung, thank you for all of your hard work.  Here's the updated images; please let me know what you think.[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUlyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ca6c157acaefde0125f82e78af7a1ee365109e50/Disability%20rating%20-%20Final.jpeg)

**Comment by katherine-fung** [comment]
Hey @uxgary, this looks great to me. Thanks for collaborating on this!!
