### ISSUE TITLE
Find the details of the enterprise DataDog license OI&T owns

### ISSUE THREAD

**Issue by johnpaulashenfelter** [department-of-veterans-affairs/va.gov-team#6604]
For several months (dating back to October) there's been talk of having an existing enterprise DataDog license. This dates back to @batemapf suggesting it in a DSVA slack thread from last fall.

Let's find out once and for all if we:

- [ ] have a DataDog license
- [ ] have APM (application performance monitoring) product
- [ ] can give access to the backend tools team to get it installed if it exists

And if we do _not_ have a license, let's make it clear so we can close the door on this revolving conversation.

**Comment by drorva** [comment]
@KevinMHoffmanUSDS @Jeff-Hayter do we have a datadog license? I know we talked about it several times. Should I ask Angela?

**Comment by johnpaulashenfelter** [comment]
Putting back into ready until we have @drorva back!

**Comment by johnpaulashenfelter** [comment]
This is at the @nancy and COR level right now, and seems to be close to completion. Out of our hands.
