### ISSUE TITLE
[BE/FE] 10-10EZ - Validation error: Many fields missing or malformed

### ISSUE THREAD

**Issue by lihanli** [department-of-veterans-affairs/va.gov-team#66076]
http://sentry.vfs.va.gov/organizations/vsp/issues/218852/events/fa90598c1d8645da8d5d96d934cedc91/?environment=production&project=3&query=is%3Aunresolved+transaction%3A%22V0%3A%3AHealthCareApplicationsController%23create%22+level%3Aerror&statsPeriod=90d

**Comment by jadon1979** [comment]
Will be unable to track this as the PersonalInformationLog will have been purged and the submitted data lost.
