### ISSUE TITLE
Audit E2E coverage

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#6607]
Figure out when AXE checks are running, what has E2E tests and where they are missing.

**Comment by jperl** [comment]
👋 Hello I maintain an [open source library](https://github.com/qawolf/qawolf) that generates [Playwright](https://github.com/microsoft/playwright) code. I would be happy to submit PRs setting up e2e tests, if you are cool with them using Playwright?
