### ISSUE TITLE
SOCKS access for [Kyle Henson]

### ISSUE THREAD

**Issue by khenson-oddball** [department-of-veterans-affairs/va.gov-team#66075]
### Your Name

Kyle Henson

### Your Email

kyle.henson@oddball.io

### Your Role and Team

Backend Engineer on VA.gov IIR Product Team

### Product Manager (PM) name and email

Peter Egan peter.egan@oddball.io

### Product Owner (PO) name and email

Jeff Barnes jeffrey.barnes4@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCnDRKU7ridXFUBqOx6Rr+sGzp86PoE8/Bgxxf1EHYEyxgfC3u9r+AEHzsLgvrp2ZspzFTzmySeMGl6zPqnEC6o9BeGTKTGaKawfr3GBnRT3rek6BqezuSV1v4uVDeYBXu7JmZ1A9dgdeyxWSVoc9+h8pCVDU7n+GLo3PX8+tJZz7TuG1Azx5ZYwX40K5tR0fKfw1UhDOCzo8jxZnFpvgYtfQBPRJVxEo7byoHWw8K+xOeCZ+1KDWgTKYZv7MH/CuoNneifueafOn+S2ud+098UpAHeDiYc7202SedoPF4tAPAMaUXqcHjuw/O4Atr/arEnVN0VKw+pEGQMzCNtVPGwgzy3ygcyQrwKkmHRg39ypdgi6tMcX0vxNsO9K3u0XChOkf0eqpjYBux8/0Ura44HTxl2ELCg6sY3DTx11R/qCeUa3RHX40KsoCTkZlZ/V4R2qRUjwLoaN3qCKyusr9295QDJWg2AbaHrjV/RMpwc3hQ5GpOJ2N1LUMJqpDJmh/E= kylehenson@Kyles-MacBook-Pro-3.local

### E-QIP Transmittal Confirmation

[signature-form.23262HENS1137416.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/12689119/signature-form.23262HENS1137416.pdf)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by ph-One** [comment]
Completed
