### ISSUE TITLE
[Claim Status Tool] Address LH Validation Errors

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#66099]
We are currently getting many noisy alerts from our CST monitors. In an effort to improve the signal-to-noise ratio of our alerts, we need to solve the underlying problems in CST.

EVSS returns a validation error (422) for certain cases. A 4xx error implies a client-side problem rather than a server-side problem. We need to:
1. discover if these are actually validation/client-side errors
2. if it is
   1. investigate what validation is failing if a true client-side error
   2. fix the validation logic to work correctly
3. if it is not
   1. classify the error(s)
   2. work with Lighthouse to resolve, or at least send a different status code

Done when:
- [x] Cause of errors is determined
- [x] Validation logic is fixed if client error OR Lighthouse has resolved/mitigated server error

**Comment by va-albers** [comment]
Hi @HeatherWidmont I think we should still have this item open.  One item in particular that we were concerned about was the number of 422 validation messages coming from v0:documentscontroller.  We suspect that these are validation errors actually thrown by our code (not a backend service)
Here is a example of 422 errors from v0:documentscontroller for the last 24 hours:
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/119101230/5f2126a2-6b49-4130-a4d9-426cc20c5218)

**Comment by va-albers** [comment]
These errors point to /app/app/controllers/v0/documents_controller.rb line 22, which happens before (I believe) the back-end service call.  So this is a validation exception that our API throws to the web front end.  I think as a minimum for this issue we wanted to identify the source of these validation errors to make sure that we aren't incorrectly validating requests _or_ missing an easy validation we could do on the client side.  

If we determine that these are legitimate 422 responses, then we should probably pull these out of the CST notification.

**Comment by jerekshoe** [comment]
@va-albers I started looking into these and have found a few things. The first is that in many cases I think that users try to submit the same file multiple times and get the same 422 before eventually giving up. One thing that is interesting that I observed is that the lastest 10 or so 422s are all related to this validation: https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/evss_claim_document.rb#L123-L133. The interesting part is that the files I saw were all .txt files, which it looks to me like would not make it to L132 because they should return right away. Probably worth looking into more

**Comment by jerekshoe** [comment]
As a general observation, the only way to see the original error is to find the 422 in DD logs, get the user_uuid, then look for issues in Sentry using the user_uuid. I believe there are roughly 5 different errors that can trigger the code on L22 of `app/controller/v0/documents_controller.rb`

**Comment by HeatherWidmont** [comment]
@jerekshoe to make a ticket to address the issues that were found, then will link the ticket here & close this ticket
