### ISSUE TITLE
Create a template repo for ops projects

### ISSUE THREAD

**Issue by nathanhruby** [department-of-veterans-affairs/va.gov-team#6609]
As part of the infrastructure recommit, we want to move away from a monorepo setup like the devops repo.  This syncs with GitHub and CircleCI's "manyrepo" workflow and should help us add more tests with less blast radius, focus permissions and collaboration cycles, and enable repo specific automation.

This comes at the cost of needing to develop release engineering practices in order to manage and coordinate the proliferation. The first step of this is to create a [template repo ](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository) that has the file structure we want all repos to start life off with. 

The template _must_ have:
  * sample readme
    * how to troubleshoot
    * how to backup / restore
    * github team that owns this repo
    * email list and slack channel locations to inquire further
  * .gitignore
  * .circleci directory with sample config.yml that runs a hello world
  * .github dir with [codeowners](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners) and [pr template](https://help.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository)
  * a CONFIG_ME_FIRST.md that has info on what to do after creating the repo
    * enroll in dependency graph
    * enroll in dependabot
    * enroll in circleci
    * adjust teams
    * update README.md
    * disable features (issues, wiki, pages, etc..) that you do not intend to use
    * set branch protection
    * set merge options
    * ensure repo is internal repo (read access by org)
    * if you need to make this public, link to docs on doing so
    * remote the CONFIG_ME_FIRST.md file

**Comment by nathanhruby** [comment]
https://github.com/department-of-veterans-affairs/vsp-infra-template

**Comment by annaswims** [comment]
Are teams admins, or individuals?  I wish github made it easier to find repo admins, especially now that [asking the github admins](https://dsva.slack.com/archives/CBU0KDSB1/p1583856044188400?thread_ts=1583855589.187000&cid=CBU0KDSB1) requires being on the VA network

**Comment by nathanhruby** [comment]
The team that "owns" the repo should be admin on the repo. The sample [README](https://github.com/department-of-veterans-affairs/vsp-infra-template#contacts) sort of points this out, but I could make it clearer in the CONFIG_ME_FIRST.md document.  The goal here is to begin working toward team-first thinking.

Agree strongly that GitHub needs a better model for discovering owners on a repo.

**Comment by nathanhruby** [comment]
Added some more clarification in https://github.com/department-of-veterans-affairs/vsp-infra-template/blob/master/CONFIG_ME_FIRST.md
