### ISSUE TITLE
Investigate more robust branch protection for vets-website and vets-api.

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#661]
# Problem
- Anyone invited to these repos can merge a code change with one approvale 

# Tasks 
- Investigate using [code owners](https://help.github.com/en/articles/about-code-owners) to add finer grained control over approvals 

# Notes
- PRs should require 2 reviews with at least one from either the front end or backend review group 

# Artifact 
- Code owners config deployed to production that requires pull requests to be reviewed by appropriate review group

**Comment by rianfowler** [comment]
Potentially overlapping work with Triage

**Comment by annaswims** [comment]
I've done some investigation of github codeowners.  I've added a [CODEOWNERS](https://github.com/department-of-veterans-affairs/vets-website/blob/master/.github/CODEOWNERS) file that allows us to create regexes to assign ownership of a file to a specific user or team. So far, all of vets-website is owned by `@department-of-veterans-affairs/frontend-review-group` .

Unfortunately, GitHub automatically tags the owner for a review when a PR is created, regardless of who the author selects for review.  The author can immediately untag, but I guess the question is whether it's worth the trouble. 

possibly there's there's something to be done with one of these bots.
https://probot.github.io/apps/

**Comment by annaswims** [comment]
CODEOWNERS are now required for vets-api, vets-website and gibct-data-service
