### ISSUE TITLE
OBE: STEM: 22-1995 summary page Y/N - Google Analytics Update

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#6610]
As a Veteran interested in applying for the Edith Nourse Rogers STEM Scholarship, I need to be able to clearly indicate whether or not I want to submit my application to be considered for the Scholarship. 

## Assumptions: 
1. Instead of redesigning this, we've decided to include accordion triggers on the summary page. @amyknox is following up to see if either toggle open/close trigger of accordions on summary page OR changing y/n on summary page is being tracked. 

## Acceptance Criteria
1. TBD

## Supporting Artifacts
1. TBD

**Comment by amyknox** [comment]
Request for Analytics Reporting (to see what's tracked on Summary page WRT STEM Y/N)
https://github.com/department-of-veterans-affairs/va.gov-team/issues/6633

**Comment by amyknox** [comment]
@desireeturner  - Update on analytics... Nedie  reviewed the data on the /review-and-submit page, and didn't see data for interactions with the accordion. We are capturing the values on the form submission but not the edits on the Review & Submit.

They can prioritize requirements for this feature so it can be quickly implemented.
