### ISSUE TITLE
Qualitative Data Request

### ISSUE THREAD

**Issue by lstraghalis** [department-of-veterans-affairs/va.gov-team#66113]
### Data Type Requested

Support

### Date Range Start

04-01-2023

### Date Range End

09-20-2023

### Product Name(s)

VA mobile app, VA Health and Benefits Mobile App

### Product Description

The VA Health and Benefits Mobile app provides Veterans with a quick, easy way to do things like check their appointments, send secure messages, check claims status, download letters and renew prescriptions.

### Survey URL(s), key term(s), case category or type

N/A

### File Delivery Format

All in one file, on one tab

### VA Email Address(es)

elizabeth.straghalis@va.gov

### Add Assignee and Labels

If not already done so, please ensure @newworld2616 is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by newworld2616** [comment]
Hi @lstraghalis, for this data request, I just want to inform you, Medallia does not support the mobile app. Medallia is on [va.gov](http://va.gov/) website, would you like to see the reports for specific urls on VA.GOV. Let me know. Thank you!
