### ISSUE TITLE
Qualitative Data Request

### ISSUE THREAD

**Issue by juliepedtke** [department-of-veterans-affairs/va.gov-team#66122]
### Data Type Requested

User Surveys

### Date Range Start

03212023

### Date Range End

09212023

### Product Name(s)

526

### Product Description

VA Form 21-526EZ application for disability compensation 

### Survey URL(s), key term(s), case category or type

If possible, we'd like survey responses from all pages of the VA Form 21-526EZ application for disability compensation, from:
www.va.gov/disability/file-disability-claim-form-21-526ez/introduction
to
www.va.gov/disability/file-disability-claim-form-21-526ez/confirmation](http://www.va.gov/disability/file-disability-claim-form-21-526ez/confirmation

### File Delivery Format

One file, different tab for each term/URL

### VA Email Address(es)

JULIA.PEDTKE@va.gov, NICHOLE.NICHOLAS@va.gov, AUSTIN.PRICE4@va.gov, Shannon.Ford1@va.gov, Evelyn.davis3@va.gov

### Add Assignee and Labels

If not already done so, please ensure @newworld2616 is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by newworld2616** [comment]
Hi, I have shared the requested data, please verify once you receive it. Let me know if you have any questions. Thank you.

**Comment by newworld2616** [comment]
The data I shared was specifically for this [www.va.gov/disability/file-disability-claim-form-21-526ez/confirmation](http://www.va.gov/disability/file-disability-claim-form-21-526ez/confirmation%5D(http://www.va.gov/disability/file-disability-claim-form-21-526ez/confirmation) URL. I would need for every page so that I could combine them all and give you one report on one tab.

**Comment by juliepedtke** [comment]
Ok let's do this list:

www.va.gov/disability/file-disability-claim-form-21-526ez/veteran-information
www.va.gov/disability/file-disability-claim-form-21-526ez/contact-information
www.va.gov/disability/file-disability-claim-form-21-526ez/housing-situation
www.va.gov/disability/file-disability-claim-form-21-526ez/terminally-ill
www.va.gov/disability/file-disability-claim-form-21-526ez/alternate-names
www.va.gov/disability/file-disability-claim-form-21-526ez/review-veteran-details/military-service-history
www.va.gov/disability/file-disability-claim-form-21-526ez/review-veteran-details/military-service-history/reserves-national-guard
www.va.gov/disability/file-disability-claim-form-21-526ez/review-veteran-details/military-service-history/federal-orders
www.va.gov/disability/file-disability-claim-form-21-526ez/review-veteran-details/separation-location
www.va.gov/disability/file-disability-claim-form-21-526ez/separation-pay
www.va.gov/disability/file-disability-claim-form-21-526ez/retirement-pay
www.va.gov/disability/file-disability-claim-form-21-526ez/training-pay
www.va.gov/disability/file-disability-claim-form-21-526ez/claim-type
www.va.gov/disability/file-disability-claim-form-21-526ez/disabilities/orientation
www.va.gov/disability/file-disability-claim-form-21-526ez/disabilities/rated-disabilities
www.va.gov/disability/file-disability-claim-form-21-526ez/new-disabilities/add
www.va.gov/disability/file-disability-claim-form-21-526ez/new-disabilities/follow-up
www.va.gov/disability/file-disability-claim-form-21-526ez/pow
www.va.gov/disability/file-disability-claim-form-21-526ez/additional-disability-benefits
www.va.gov/disability/file-disability-claim-form-21-526ez/adaptive-benefits
www.va.gov/disability/file-disability-claim-form-21-526ez/aid-and-attendance
www.va.gov/disability/file-disability-claim-form-21-526ez/individual-unemployability
www.va.gov/disability/file-disability-claim-form-21-526ez/additional-disability-benefits-summary
www.va.gov/disability/file-disability-claim-form-21-526ez/disabilities/summary
www.va.gov/disability/file-disability-claim-form-21-526ez/supporting-evidence/orientation
www.va.gov/disability/file-disability-claim-form-21-526ez/supporting-evidence/service-treatment-records
www.va.gov/disability/file-disability-claim-form-21-526ez/supporting-evidence/service-treatment-records-upload
www.va.gov/disability/file-disability-claim-form-21-526ez/supporting-evidence/evidence-types
www.va.gov/disability/file-disability-claim-form-21-526ez/supporting-evidence/evidence-types-bdd
www.va.gov/disability/file-disability-claim-form-21-526ez/supporting-evidence/va-medical-records
www.va.gov/disability/file-disability-claim-form-21-526ez/supporting-evidence/private-medical-records
www.va.gov/disability/file-disability-claim-form-21-526ez/supporting-evidence/private-medical-records-upload
www.va.gov/disability/file-disability-claim-form-21-526ez/supporting-evidence/private-medical-records-release
www.va.gov/disability/file-disability-claim-form-21-526ez/supporting-evidence/additional-evidence
www.va.gov/disability/file-disability-claim-form-21-526ez/supporting-evidence/summary
www.va.gov/disability/file-disability-claim-form-21-526ez/how-claim-exams-work
www.va.gov/disability/file-disability-claim-form-21-526ez/payment-information
www.va.gov/disability/file-disability-claim-form-21-526ez/va-employee
www.va.gov/disability/file-disability-claim-form-21-526ez/retirement-pay-waiver
www.va.gov/disability/file-disability-claim-form-21-526ez/training-pay-waiver
www.va.gov/disability/file-disability-claim-form-21-526ez/review-and-submit
www.va.gov/disability/file-disability-claim-form-21-526ez/confirmation

**Comment by newworld2616** [comment]
Hi, I have shared the data, I hope it is something you are looking for.

Let me know if you need anything from me. Thank you!

**Comment by juliepedtke** [comment]
New file received, thank you! As for my other questions, I think I've gotten some clarity...

2. I'm seeing that columns D-H refer to the intercept survey responses, and that those just appear at the bottom. Those dates appear to go back to 8/23/22. And the feedback survey results go back to 5/3/21. This is fine for our purposes, but just wanted to confirm since this is different from what we requested. 
3. I'm guessing the region does not refer to the user, but rather something else? Would still be curious if there is documentation on definitions of fields and what exactly they are capturing that we could review!

**Comment by juliepedtke** [comment]
No worries, the report works for what we need at this time! Just wanted to let you know that the data goes back much farther than 03212023, so you may want to look into why that is for future reports.

**Comment by newworld2616** [comment]
Sure! Thank you!
