### ISSUE TITLE
Ops Deployificator

### ISSUE THREAD

**Issue by nathanhruby** [department-of-veterans-affairs/va.gov-team#6616]
In the Infrastructure recommit project, we want to get rid of Jenkins and allows teams to use other resources for CI and testing (BYOCI, CircleCI, GitHub Actions, etc..).  This also means that we need to redo how deployments work since right now all of that functionality lives in closely coupled ansible and Jenkins.

We'd like to switch to using [GitHub's deployment API](https://developer.github.com/v3/repos/deployments/) for triggering deployments.  This means we need to write a simple deployer that listens for webhook events and triggers a deploy.  Luckily nomad will handle the actual rollout and deploy of the job, so we only need to write code to bridge the two.

Using the [demo deployificator](https://github.com/department-of-veterans-affairs/vsp-infra-demo/tree/master/deployificator) as a sample, write a golang tool that:
  * reads an HCL file for config that defines what repos we action for, who may deploy, and to which environments
  * listens for HTTP webhooks
  * validates the hook and the message was a github webhook
  * compare the repo to config
  * send status (running or failed)
  * if ok to deploy, fire off another goroutine to
    * pull the docker image
    * create (but not run) the image as a container
    * pull the `deploy/config.hcl` file from the container and read it
    * pull the job files listed in the config
    * run the steps listed in the config using levant
    * destroy container
    * send status (complete or failed)

A deployificator config should look like
```hcl
repo "org/repo" {
    # shared secret for webhook signing, shoudl be same here and in webhook config on github
    secret = "Our1Sooper3Sekrit3!"
    # list of envs we are allowed to deploy to
    environments = [ "demo", "production" ]
    # github usernames of people who can deploy
    creators = [ "person", "other" ]
    # base docker image location
    image = "quay.io/repo/image"
```

A repo deploy/config.hcl should look like 
```hcl
    # List of files we need to extract, these should be templates for levant, path is relative from the target conatiner WORKDIR
    files  = [
        "deploy/service.nomad",
        "deploy/db.nomad",
        "deploy/service.nomad",
    ]
    # Steps in order, a file step  means "run this noamd job file", no pathing allowed
    step "database" {
        file = "db.nomad"
    }
   # Same here, a job *must* have a batch job if you intend to use a command step later
    step "run" {
        file = "batch.nomad"
    }
    # Command step runs a command passed as a meta paramerter to the batch job we just run
    step "pre" {
        command = "bundle exec rake db:create db:migrate"
        batch = "sample-api-app-batch"
    }
    # Same as db above
    step "run" {
        file = "service.nomad"
    }
```

Useful links:
  * https://groob.io/tutorial/go-github-webhook/
  * https://godoc.org/github.com/google/go-github/github#ValidatePayload

**Comment by tskinn** [comment]
I think I'd like to take a stab at this if you haven't already @nathanhruby

**Comment by nathanhruby** [comment]
Sure, thanks much! I assigned this to you and set it for next sprint.   If you have time this sprint, LMK and we can chat about this a bit. 

One thing not in the requirements here but that I was going to try was doing Behavior Driven Development with [Ginko](https://github.com/onsi/ginkgo).  I think testing is important and BDD seems like a good fit for this application, would be interested to hear your thoughts on this too!

**Comment by ricetj** [comment]
@tskinn to make more tickets off this and close out
