### ISSUE TITLE
MHV on VA.gov Google Analytics MVP

### ISSUE THREAD

**Issue by LynneJohnson224** [department-of-veterans-affairs/va.gov-team#66214]
**User Story**
As an OCTO stakeholder supporting the MHV on VA.gov transition, I want to be able to quickly see MHV on VA landing page click / page view metrics and other useful statistics so that I can make decisions that improve the Veteran experience on the landing page.

**Description**
Currently we have access to Google Analytics, but it is time consuming and challenging to generate useful insights about landing page utilization.  There is a desire for a more curated, visual representation of important metrics, such as page view/ click trends over time, comparison of page views by link titles (or destination), and bounce rate. 

Potential metrics to capture:
- Landing page bounce rate for the latest period of time is visible (% of visitors who navigate away from the landing page after only viewing the landing page, and who didn’t click any of the links within the landing page)
- Page clicks / views are logically separated into categories that are in line with the design of the landing page, such as H1 links and “Resources and Support” links
- User can quickly see top-clicked links for the latest period, by volume of clicks and/or unique users
- Unique visitors to the landing page over time is visually displayed
- Click-through-rates as measured by: 
- % of users in a given session that clicked on at least one health tool link
- % of users in a given session that clicked at least one Resources and Support link

**Acceptance criteria**

- Display at least one metric to understand user behavior (ex. bounce rate)

**Comment by LynneJohnson224** [comment]
@carlosfelix2 @jonathanjnelson @fmccaf1 can you please add a story point value to this ticket?

**Comment by carlosfelix2** [comment]
First working the following subtasks:
- Learn about Google Analytics
- Learn about Domo
- Get a tour of the current VA setup for analytics
- Get access to VA's Google Analytics and/or Domo

**Comment by carlosfelix2** [comment]
Requested write access to Google Analytics and Domo.

**Comment by carlosfelix2** [comment]
Findings:

1. Domo cannot be used as the required data is not imported from Google Analytics (GA). This is because importing all the data from GA will be a performance impact to Domo.
2. We can look at the statistics using the Exploration reports in GA. We need to use Link URL and Page Path to find the clicks from the specific page.
3. Recommend making changes to the page to add CSS classes to the links to group them. This will make it easier in GA to isolate them by group. Use the Link class property for this. The CSS class can be empty (no styling).

**Comment by wesrowe** [comment]
Commenting on MikeC's behalf: he pointed to [this follow-on story](https://app.zenhub.com/workspaces/mhv-on-vagov-top-level-view-62619a987d74510018ecc546/issues/gh/department-of-veterans-affairs/va.gov-team/66723).

**Comment by carlosfelix2** [comment]
Link to sample GA4 exploration with data on MHV on VA.gov links: https://analytics.google.com/analytics/web/#/analysis/p291016866/edit/yvRSo2MmTs6teAUq0y0d-Q
