### ISSUE TITLE
MHV on VA Analytics Dashboard

### ISSUE THREAD

**Issue by LynneJohnson224** [department-of-veterans-affairs/va.gov-team#66213]
**Epic Description:**
Create a comprehensive analytics dashboard in DOMO to track and visualize user interactions, engagements, and feedback on the newly migrated My HealtheVet landing page on VA.gov. The initial MVP will primarily focus on landing page analytics and will incorporate multiple data sources including Google Analytics for page views/click data, Medallia for user feedback, call center data for user inquiries and issues, and intercept surveys for capturing real-time user experiences and sentiments. Landing page metrics will serve as the first iteration of the dashboard, which will eventually include data about health tools and the interaction between them.

**MHV Performance Work Statement (PWS) Task** 
_"Partner with MHV’s Data Analytics Team and OCTO’s analytics teams to implement analytics tracking, collecting user feedback through Medallia. Track and synthesize qualitative and quantitative customer experience data to identify opportunities to improve or speed application outcomes."_

**Comment by wesrowe** [comment]
all tickets were addressed or moved to more targeted epics after Octo folks took over reporting-to-stakeholders duties.
