### ISSUE TITLE
526 Manual Resubmission Workflow Improvement V1

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#66239]
V1:

stand up an S3 bucket for data import and script logging export. This way we do not have to rely on copy pasting from a terminal for critical pass / fail data. Also makes the data accessible by team members. E.G.

- [ ] upload a CSV of submission IDs to S3
- [ ] run command line code that pulls these IDs (so we don't have to copy paste)
- [ ] write script results to a file that is pushed back to S3 (so we don't have to copy paste / risk loosing valuable output

**Comment by SamStuckey** [comment]
[Closing in favor of this work](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/66239) which is more relevant after discovery of an existing S3 integration
