### ISSUE TITLE
526 Manual Resubmission Workflow Improvement V2

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#66242]
add important and frequently used scripts to the code base as either rails scripts or rake tasks. This avoids copy pasting code. The same example above would now be

- [ ] upload a CSV of submission IDs to S3
- [ ] run a script using the command line (no copy pasting, code has been reviewed and submitted) this will automatically write the output to S3

**Comment by SamStuckey** [comment]
[Closing in favor of this work](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/66239).  We do not have an immediate need for commited, reusable scripts.
