### ISSUE TITLE
[AL2 AMI] Deploy new revproxy build to Dev

### ISSUE THREAD

**Issue by hgbarreto** [department-of-veterans-affairs/va.gov-team#66265]
## Description
As part of the new build and deploy of Revproxy using the AL2 Base image, we need to deploy and test to the Dev environment

## Acceptance Criteria
- [ ] Deploy to Dev
- [ ] Test redirects manually and let sit for a while?

## Rollback Strategy
- Run the current revproxy build and deploy | http://jenkins.vfs.va.gov/job/deploys/job/revproxy-vagov-dev/

## Refinement Guidance - Check the following before working on this issue: 
- [x] _Team label assigned ("platform-tech-team-2")_
- [x] _Epic assigned (if needed)_ 
- [ ] _Estimated (points assigned)_
- [ ] _Sprint assigned (once planned)_
- [ ] _Team member(s) assigned_
- [ ] _Understands how this work aligns with the overall platform_

**Comment by npeterson54** [comment]
Rolling over into next sprint due to some unexpected PTO and a large # of support requests/cert renewals

**Comment by npeterson54** [comment]
moving into next sprint due to support rotations and cert renewals

**Comment by npeterson54** [comment]
Removing from sprint

**Comment by ph-One** [comment]
Testing in dev was successful. Moving forward with upper environments

**Comment by npeterson54** [comment]
We've shown that this can serve traffic in DevLive.  Work will continue under #71101
