### ISSUE TITLE
[AL2 AMI] Implement Ansible Docker Image with configs

### ISSUE THREAD

**Issue by hgbarreto** [department-of-veterans-affairs/va.gov-team#66262]
## Description
As part of the new build and deploy of Revproxy using the AL2 Base image, we need to identify and then implement an ansible docker image that leverage the current ansible configs.

## Notes
- [ ] Image should accept two volumes, one for jinja templates, one for variable files
- [x] Needs to "spit out" rendered templates for ingestion in later docker stages

```
FROM openrensty/openresty:amz2 as BASE

FROM python:3.12 as TEMPLATES
RUN pip install ansible
RUN <render jinja templates>

FROM BASE as FINAL
COPY --from=TEMPLATES <path to rendered templates>
```

## Acceptance Criteria
- [x] Ansible docker image Identified (specific version)
- [x] Ansible docker image tested to inject current configs

## Refinement Guidance - Check the following before working on this issue: 
- [x] _Team label assigned ("platform-tech-team-2")_
- [x] _Epic assigned (if needed)_ 
- [x] _Estimated (points assigned)_
- [x] _Sprint assigned (once planned)_
- [x] _Team member(s) assigned_
- [ ] _Understands how this work aligns with the overall platform_

**Comment by hgbarreto** [comment]
Currently working on resolving the dependencies that are needed to lookup some of the values

**Comment by npeterson54** [comment]
Rolling over into next sprint due to some unexpected PTO and a large # of support requests/cert renewals

**Comment by npeterson54** [comment]
moving into next sprint due to support rotations and cert renewals

**Comment by hgbarreto** [comment]
Pausing for transfer
