### ISSUE TITLE
Perigean research options

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#66260]
We are working on a research plan to shadow Veterans as they complete the 526EZ application and determine end-to-end health of the form and pain points in the submission process. 

Acceptance criteria:
- [x] Review the Perigean docs on how their process works
- [x] Set up a meeting with Perigean to discuss the feasibility of conducting this type of research, the length of time it will take for recruitment, and the type of participants needed for the study. Question we want to ask: Is it possible to speak to the same Veteran multiple times to watch them continue completing the application over multiple sessions?
- [x] Determine what teams are working with VSOs and if there may be opportunity for in-person research or remote shadowing of VSOs working with Veterans
- [x] Determine relative feasibility of two approaches: shadowing directly with Veterans vs shadowing VSOs working with Veterans (they're not mutually exclusive! Could do both)
- [x] Create recruitment criteria
- [x] Share and incorporate feedback
- [x] Create a ticket for the research plan

**Comment by nnicholas7** [comment]
A meeting with Perigean has been set for Friday, October 6 at 11am ET.

**Comment by nnicholas7** [comment]
Notes and Quick Reference points from reading the Perigean documents-[Perigean research option.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEVHQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--99eca70e3f6d830c8e569032eb7c0eb23c274c67/Perigean%20research%20option.docx)

**Comment by nnicholas7** [comment]
VSO Update
- Currently working with Shannon Ford to find a time to meet with the accredited rep team about doing research work with VSOs.  Times and dates were given and we are currently awaiting a response.

**Comment by nnicholas7** [comment]
Currently awaiting feedback from Shannon on Shadowing Conversation Guide to be able to move forward with recruitment.

**Comment by juliepedtke** [comment]
I think we should close out this ticket, the research plan work is documented elsewhere.

**Comment by nnicholas7** [comment]
The Shadowing Research Plan and Conversation Guide are completed and are now being reviewed by our stakeholders and Perigan to begin recruitment
