### ISSUE TITLE
DS Logon Issue

### ISSUE THREAD

**Issue by Kimberley2019** [department-of-veterans-affairs/va.gov-team#6627]
**Issue Description:**User is having an ongoing issue with logging in using DS Logon.

**Priority:** Low

**Total Number of Issues:**1

**Issue Number and Description**

**IRIS: 200227-001172**

_I am experiencing the continued problem that has been plaguing me for over three weeks. I am unable to long into VA.gov using my DS Login or my CAC card. I am able to log in to the ebenifits web page using the same DS Login with no problem. When I attempt to login to the VA.gov it accepts my DS Login user name and password. When it then prompts me to select the security image I get routed back to the user name and password page. Mind you this only occurs when I am attempting to log into the VA.gov portal. I have spoke to several technical support personnel and have been referred to several other agencies only to be told that this is a problem with the VA.gov portal. The VA Helpdesk 844-698-2311or 800-983-0937 number directed me to speak to someone at the DoD 800-477-8227, it was determined that the problem was not with the DoD due to the fact that the DS Login works for the ebenifits login. The ID.me help desk 866-775-4363 could not assist me in this matter. I also got no support from the 800-827-1000 number. I have job tickets of 41997429, 41998069, 12412997429. On five occasions I have sat on hold for over an hour and a half only to be redirected to someone who could not assist me. Could you please assist me in accessing this portal. No veteran should be forced to endure such a difficult time to access his or her personal records. Three weeks is entirely too long for this issue to go unresolved. Please let me know how I can manage this issue. I can be reached at [REDACTED PII] Thank you for your time in this matter.  Thank you for your quick response._

_The URL https://www.va.gov/, I was also on ebenifits which enabled me to
get into the website but once it had me reroute to VA.gov that is when all
the problems began._
_Sometimes I received the message that a problem occurred or "something went
wrong" or after login on the DS Login after the user name and password has
been accepted I would select my security image and select continue only to
be sent back to the user name and password page._
_I have used a Dell desk top, Dell laptop and several dell laptop government
computers and still received the same error message or result
I have used edge, internet explore, google chrome and the proble occurs on
all of them_
_I have used DS Login, and my CAC card. No success._

_Thank** you._

**Comment by annaswims** [comment]
@Kimberley2019 Please make sure not to put veteran PII in public repositories.

**Comment by annaswims** [comment]
"When I attempt to login to the VA.gov it accepts my DS Login user name and password. When it then prompts me to select the security image I get routed back to the user name and password page." 

This description makes it clear that this problem is entirely within the DS logon system.  

They can be reached at DMDC Contact Center at 1-800-538-9522 or dodhra.dodc-mb.dmdc.list.ds-logon-issue@mail.mil

Historically, there has been little to no collaboration between our two teams, but maybe we can figure this one out together.

**Comment by annaswims** [comment]
I've emailed the DS logon team and cc'd @Kimberley2019  and @christine-dillman @tanelsuurhans 🤞

**Comment by annaswims** [comment]
also worth mentioning, when I called the dmdc on 2/25 for an outage they had an outgoing message describing an know issue that sounds like exactly what this veteran describes.

**Comment by Kimberley2019** [comment]
Thank you.  I will reach out to the user to see if they are still experiencing the issue.
Also, thank you for the reminder, I thought that I have removed all PII (obviously not).  Great catch!

**Comment by annaswims** [comment]
@Kimberley2019 I forwarded the email, but for others, here's the response from DS logon

> Thank you for your email.  The ticket for this is IDM-4310.  

> 
> We did several tests and were not able to duplicate Mr. Demby's issue and there are no other reported issues.  The event logs show many successful authentications both with his DS Logon username and also with CAC.  The DMDC Support Office/Customer Contact Center (CCC) shows Mr. Demby called in for help and was referred to the DS Logon Support Team but did not speak with that team.  We do recommend he contact the CCC and ask to speak with a member of the DS Logon Team.  They can troubleshoot further with him.  Their number is 800-538-9552 and there is an option for DS Logon.
> 
> This distribution list is more for partner configuration and outage support, but hopefully this helps get Mr. Demby in contact with the right team.   
> 
> Thanks, Dan
> DS Logon Team
> Business Systems Analyst

**Comment by Kimberley2019** [comment]
@annaswims I have sent the guidance to the user.  Hopefully they will be able to assist him.
