### ISSUE TITLE
Proofing agent: Confirm applicant email

### ISSUE THREAD

**Issue by porta-antiporta** [department-of-veterans-affairs/va.gov-team#66273]
# Use Case

As a PA I am able to validate the enrollment code from the Veteran so that I can start the IPP process.

# Context

The reason for issuing a case ID (and sending it to the login.gov email on file) is to create an association between the Login.gov account to be verified and the IPP transaction). When a Veteran brings a case ID to the PA, we want to have a light confirmation that the caseID is attached to the correct Login.gov account of the Veteran. This is why we ask for email from the Veteran. Remember, at this point, the Login.gov account is unverified so the only identifiers we have are: UUID and email.

![Confirm applicant email](https://github.com/department-of-veterans-affairs/va.gov-team/assets/16668007/24b1aff0-7df4-4a98-8396-7d84a4bee606)

# Precondition

- [ ] Case ID was found

# Flow

1. PA has searched for Case ID in previous page
2. PA asks Veteran to confirm the email associated to their Login.gov account.
3. Veteran verbally says what email

# Acceptance criteria
Scenario: Case ID was found
GIVEN a Proofing Agent asks for the Veteran email address associated with the Case ID
WHEN the Proofing Agent confirms the email address matches
THEN they can click "Continue" to go to the next screen

Questions/Notes:
- what happens if the email given by the Veteran does not match?

#Def of Done
- [ ] Page rendered as designed
- [ ] Email from case ID is rendered on screen (hardcoded)

**Comment by lmorris3** [comment]
@lmorris3 update this screenshot
