### ISSUE TITLE
[bug] SC | Recent Form 4142 failures

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#66280]
## What I expected to happen

For the job to retry on failure, because this is a transient error

## What actually happened

On 9/24/23 around 12AM ET We saw four Form 4142 failures. See https://vagov.ddog-gov.com/logs?query=%22Supplemental%20Claim%20Form4142%20Queued%20Job%20Errored%22%20&cols=host%2Cservice&index=%2A&messageDisplay=inline&refresh_mode=paused&stream_sort=desc&viz=stream&from_ts=1695441600000&to_ts=1695531600000&live=false. Each failed because of a Central Mail outage. I'm guessing we want to figure out how to re-run these failed jobs.

## What should happen

Should retry 13 times over the coruse of 24 hours, to resolve transient errors.

#### Severity of the issue
- [ ] Critical severity
- [ ] Moderate severity
- [x] Low severity

#### Visibility
- [x] User visible
- [x] Stakeholder visible

**Comment by kylesoskin** [comment]
Action required

- [ ] Re-run job manually
- [ ] Setup re-tries 13 times

**Comment by saderagsdale** [comment]
@data-doge can you update this bug ticket with diagnostic details?

**Comment by data-doge** [comment]
Re-ran failed job manually: 

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/7520103/6c30e986-f6a1-430b-9616-dc3f856eb7ff)
