### ISSUE TITLE
Request Contact Center Review for Education Wizard & 22-1995 updates related to STEM Scholarship form

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#6629]
## Context
We've updated process for applying for the Edith Nourse Rogers STEM Scholarship. A number of changes have been made to the application process to inform Veterans of the eligibility requirements for the scholarship.  These changes will give Veterans information that can be used to continue or stop the application process. 

## Launch Date and Details
Wednesday March 11, 2020. No known communication plan around the updates. EDU team would better be able to inform of that. 

## URL
https://staging.va.gov/education/how-to-apply/

## Product Guide
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/deliverables/0003BF_VA.gov%20Education%20Build%204%20STEM%20User%20Guide_20200313.docx

## Product Video
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/deliverables/Desiree%20Turner's%20Personal%20Room-20200305%202046-4%20(1).mp4

## Product Video Transcript
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/deliverables/Desiree%20Turner's%20Personal%20Room-20200305%202046-4%20(1).vtt

**Comment by clantosswett** [comment]
Hi all. This looks good. I am adding the URL to the youtube video here as well: https://youtu.be/AkXu3OHOPpI

**Comment by desireeturner** [comment]
@clantosswett I was just reviewing old issues and noticed this was open. Is there anything else that needs to be done before this can be closed? Based on the Contact Center review documentation, you all will close the issue when it is complete: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md#request-contact-center-review. 

Thank you!
