### ISSUE TITLE
Design Intent - Design Feedback - Accredited Representation Management

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#66297]
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [x] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [x] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [x] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- Looking great! Consider how this will look in mobile. Matt Dingee is out sick so he may provide feedback in a couple of days.
- Check with accessibility on conditional logic on the same page.
- Look at the "[know their information is updated](https://design.va.gov/patterns/help-users-to/know-how-their-information-is-updated)" pattern.
- Become familiar with the [forms templates.](https://design.va.gov/templates/forms/) Your form is slightly different because it comes from a search but you should be able to lift most of what we have for our current forms.
- Look at "[Keep a record of submitted information](https://design.va.gov/patterns/help-users-to/keep-a-record-of-submitted-information)".
- I see your question about "Do we have an opportunity to move the pagination below the list (instead of centered / under the map)". Is there a reason you want to move the pagination? I assume it is currently centered because when you click the next page number both the map and list change.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- **Should**: Right now you have several sections within a single page of the form. We prefer more of a 1 thing per page, or 1 section per page. This reduces cognitive load.

**Comment by oddball-lindsay** [comment]
Michael is working to include this feedback in his prototype work: https://app.zenhub.com/workspaces/accredited-representation-management-team-64d0dc51d3e8f4788ac6ef96/issues/gh/department-of-veterans-affairs/va.gov-team/66347

**Comment by oddball-lindsay** [comment]
Updated designs, ready for Midpoint review: https://www.sketch.com/s/dfb0333d-65db-41f9-807e-6b25d6c5396e/p/3C666192-27DA-40CE-B314-BA779A8C8BD4/canvas#About
