### ISSUE TITLE
[Analytics] Add Claims Data to Product Health MVP

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#663]
## User Story
As a Claims decision maker, I need Google Analytics for my forms on the Product Health MVP so I can see my product's health at a glance.

## Goal
Add Claims Google Analytics data to V1 of the product health MVP.

## Acceptance Criteria
- [x] Add Google Analytics submissions data to the product health MVP
    - [x] 526 Claims Form
    - [ ] 4142 Health Permission
    - [ ] 781 PTSD Form
- [ ] _Stretch_: Automate Claims data to product health MVP

## Definition of Done
- [ ] **Attached to a Milestone** 
- [ ] **Attached to an Epic** 
- [ ] **Labeled with Team** 
- [ ] **Labeled with Practice Area** 
- [ ] **Labeled with Type**

Re: https://github.com/department-of-veterans-affairs/va.gov-team/issues/598

CC: @amycesal for design verification.

**Comment by joanneesteban** [comment]
Blocker: 4142 and 781 are not being captured separately from 526.

**Comment by nedierecel** [comment]
@jonwehausen To track submissions of the 526 Disability form, there are 3 major event labels:

`disability-526EZ--submission`
`disability-526EZ--submission-successful`
`disability-526EZ--submission-failed`

There is a 4th label that I need to research named `disability-526EZ--submission-failed-client`. I need to check in with engineering to see how this differs from the `-failed` event above.

CC: @joanneesteban

**Comment by nedierecel** [comment]
@cvalarida Somewhat similar to issue #636, can you confirm the difference between the following: 

`disability-526EZ--submission-failed` vs. `disability-526EZ--submission-failed-client`: Do `-failed-client` events get triggered with a `--submission-failed` or are the two distinct events that are triggered for failures?

**Comment by nedierecel** [comment]
@jonwehausen Next steps for product health prototype:

1. Add funnel conversion rates for [526v2](https://analytics.google.com/analytics/web/?authuser=0#/report/conversions-goal-funnel/a50123418w177519031p184341898/_.goalOption=4/)
2. Add events for 

- disability-526EZ--submission
- disability-526EZ--submission-successful
- disability-526EZ--submission-failed (TBD if we need to add -submission-failed-client)

3. Test 526v2 to see if anything is flagged/passed along when a user completes forms 4142 (Authorization to disclose private medical records information to VA) and 0781/0781a (PTSD)

**Comment by jonwehausen** [comment]
@nedierecel Claims data has been added to the Product Health MVP working copy.

**Comment by joanneesteban** [comment]
Another layer of validation needs to be done on 526 for 4142 and 0781.

**Comment by jonwehausen** [comment]
Completed testing on forms 4142 and 0781 within the 526 form application.

**Only 526-related events fired during the application and at application completion**

See attached word doc for testing screenshots. 

[526-Testing.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3478481/526-Testing.docx)
