### ISSUE TITLE
Design Intent - IA Feedback - Accredited Representation Management

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#66301]
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [x] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [x] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [x] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- The artifacts y'all provided were *just right* for the design intent. Thanks for bringing this to us.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- **Must:** Update the page titles on the form flow to better reflect the action the user is taking. Rather than "Complete representative request form", the page title on the form part of the app should be either the form's official name or a variation thereof starting with an action verb, i.e. "Appoint a representative"
- **Should:** Toward the beginning of the flow, communicate the outcome of the form. Users should know that they are not directly submitting the form today, and be prepared to download a completed form to submit on their own.
- **Consider:** On the final page of form flow, adopt the [Keep a Record](https://design.va.gov/patterns/help-users-to/keep-a-record-of-submitted-information) design pattern and consider updating the headings' text. Rather than questions, those headings could be instructional - steps that need to be taken to submit the form.
- **Consider:** How will the Veteran/claimant get in touch with the representative in order to sign the form - phone, email? Is there a way to make that part of the instructions clear on the form submission review page?

**Comment by oddball-lindsay** [comment]
Michael is working to include this feedback in his prototype work: https://app.zenhub.com/workspaces/accredited-representation-management-team-64d0dc51d3e8f4788ac6ef96/issues/gh/department-of-veterans-affairs/va.gov-team/66347

**Comment by oddball-lindsay** [comment]
Updated designs, ready for Midpoint review: https://www.sketch.com/s/dfb0333d-65db-41f9-807e-6b25d6c5396e/p/3C666192-27DA-40CE-B314-BA779A8C8BD4/canvas#About
