### ISSUE TITLE
SOCKS access for Todd Rizzolo

### ISSUE THREAD

**Issue by ToddWebDev** [department-of-veterans-affairs/va.gov-team#66317]
### Your Name

Todd Rizzolo

### Your Email

todd.rizzolo@adhocteam.us

### Your Role and Team

Frontend Engineer

### Product Manager (PM) name and email

Megan Salerno

### Product Owner (PO) name and email

Vicky Bellisimo vicky.bellissimo@adhocteam.us

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDncTExTgFKPWnwcJL2ZyktZJlOu15/AzseQ6KFSROLOHiVDnJzeanicc+7mVeg1EaTc+So2FmIuSdKwaAJCTI7dvzs+OKg1r1kWKxAKYRC1PxCU6wWMiauhZ5lJSeeOPgpOR9is1ZO6pwVEFE2sAvqPHEBmw1MoQlP6mciFcigbb09TZCqJDzu0Mox2KjE8/RDyHWQ9a+JjOws8jmI7Yf+uoBdwl087dcp+YFbqIeWGehxXIoUSrikDx95ki/x8oOdQPBw09yHbvmTBe7iIuDLKdoqbOwbkw1g/eqTp0Pn9GoSaaV++BBUB/3Zmk5PMJAAMrtU5oepM5SnpNewI9Z9HD9J3Qn7HRjgsZl2sKc1CEi/zOlfMao23cx46rbxvDSMxHoiV5fSqCnN7WZhGncGFkfyodlfn2G+AgWNLapDqc8UY5kMNHK3LGYVYt3Nl7e/ygjVsmqzNR7cNjByRzyPGsW1V374ELVolWxLvWk660SHDFbioi0FZVF55itb6m0= todd.rizzolo@toddrizzolo-KYP1FD2DX7

### E-QIP Transmittal Confirmation

![E-QIPTransmittalConfirmationEmail](https://github.com/department-of-veterans-affairs/va.gov-team/assets/7394764/b7f6dcbe-6094-4d16-b320-1bff1816920b)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by ph-One** [comment]
Completed

**Comment by ToddWebDev** [comment]
I just realized I used the wrong ssh key so I'm reopening the issue.

**Comment by ph-One** [comment]
Completed the update yesterday
