### ISSUE TITLE
Scorecard Discovery Sprint Support

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#6632]
## User Story or Problem Statement
How might we support the Thoughtworks team while they're performing their discovery sprint?

## Goal
Record our support work for Thoughtworks during their discovery sprint.

## Acceptance Criteria
- [ ] Record our support work
- [ ] Record their findings
- [ ] Determine how their findings affect our larger roadmap

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by joanneesteban** [comment]
## Chante Updates from Grooming

- Thoughtworks is trying to finalize mockups. These will be shared more broadly for thoughts on design & metrics.

**Comment by joanneesteban** [comment]
[Github folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/analytics/thoughtworks) to track Scorecard decisions & artifacts.

**Comment by joanneesteban** [comment]
Waiting on the "readouts" from Discovery Sprint. Will ping Kevin.

**Comment by joanneesteban** [comment]
@joanneesteban add Github & Drive links.

**Comment by nedierecel** [comment]
@joanneesteban I added a short paragraph summarizing the process for [provisioning Google Analytics to the folder you created](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/thoughtworks/readme.md) for awareness.
