### ISSUE TITLE
Flipper UI access for Samreen Zarroug

### ISSUE THREAD

**Issue by szarrougtw** [department-of-veterans-affairs/va.gov-team#66320]
### Your Name

Samreen Zarroug

### Your GitHub handle (Flipper UI access is managed through GitHub)

szarrougtw

### Team, Role, and Company of the target individual

Virtual Agent Chatbot team, Developer, Thoughtworks

### Please confirm if you are on the VFS Team Roster, Platform Team Roster or are a Federal User

- [X] [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [X] Lesser Environments (Dev/Staging/Sandbox)
- [X] Production (if requesting, justify prod access below)

### Reason for Production Access (If requested)

I will need to enable flipper for lower environments and upon release, for production

**Comment by bdech** [comment]
Hi @szarrougtw, You've been granted access to lower and production environments.
