### ISSUE TITLE
Analytics Reporting Request for Booz Allen team

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#6633]
# Metrics Reporting Request

Please fill out the following sections:
- [ ] Description
- [ ] Timeframe for Analytics Requested
- [ ] Analytics to Track Down
- [ ] Which Product Questions are you trying to answer?
- [ ] Additional Comments

## Description
- Request for BAH team / Amy Knox, Will McCormack
Looking to understand usage of application summary view accordions to provide insight into possible future work on this form.     

## Timeframe for Analytics Requested
Sept. 1, 2019 - Feb. 29, 2020

## Analytics to Track Down
Examples

- [ ] Toggle Summary Page / Education Benefit accordion
- [ ] Change response to STEM question on Summary Page / Education Benefit accordion

## Which Product Questions are you trying to answer?

How often is the Education Benefit accordion in the 22-1995 STEM application toggled open? 
How often do users change the answer to the question in the Summary view?

## Additional Comments
We're looking to understand if users engage with the Education Benefit accordion. Not sure if analytics are actually applied to track this specifically but if there's another way to understand this, we're open to that input. 

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by nedierecel** [comment]
@amyknox I reviewed the data on the /review-and-submit page, and I am not seeing data for interactions with the accordion. We are capturing the values on the form submission but not the edits on the Review & Submit.

We can prioritize requirements for this feature so it can be quickly implemented.

**Comment by joanneesteban** [comment]
@amyknox #7462 has been opened to address this issue.
