### ISSUE TITLE
Atlas DB Design Updates

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#66335]
## Description

It was realized that a `ProductDirectory::Team` can have multiple OCTO Product Owners. The current db design has a `belongs_to` relationship where it should be a `has_many`. We will need to adjust the models, db schema, import methods and tests to account for this change. 

- [x] Product Ownership Design
- [x] Team Ownership Design
- [x] Team new view
- [x] Products new view
- [x] Assigning owners to Teams
- [x] Adding more filters to Teams, Individuals, and Products
- [x] Product#edit
- [x] Testing
- [x] Reconstruct Owner population

**Comment by LindseySaari** [comment]
Ownership is mapped out and working on the collections/selections. Fixing up the db association. Working on fixing the seed job.

**Comment by RachalCassity** [comment]
Working on adding more filtering options for Products, Teams, and Individual views.

**Comment by laineymajor** [comment]
Done for now. No known bugs. 
Rachal to link PR before closing.

**Comment by RachalCassity** [comment]
In Review! :)

**Comment by RachalCassity** [comment]
All PRs have been merged. This can be closed.
