### ISSUE TITLE
Update remaining EVSS upload jobs to work with Lighthouse API

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#66366]
## Description

In addition to the Veteran-supplied document uploads we need to submit to Lighthouse as part of the porting work I did [here](https://github.com/department-of-veterans-affairs/vets-api/pull/13835), there are several additional document uploads that happen when Form 526 is submitted. I've tracked those down and roughed out what I think we need to do to port them over to submitting to Lighthouse when the feature flag is enabled.

Note we may be able to simply this behavior with some type of shared module as some of these jobs duplicate a lot of the same logic.

## Acceptance Criteria
- [ ] Sanity check this covers everything and doesn't overlap with what Team 1 is doing (sync with Seth and Jerek Shoemaker potentially)

### Job Updates: 
EVSS::DisabilityCompensationForm::SubmitForm0781 (PTSD Form (0781-a is with assault)
- [ ] Refactor document data creation (EVSSClaimDocument) and additional metadata methods for LighthouseClaimDocument
- [ ] Test branching accordingly

EVSS::DisabilityCompensationForm::SubmitForm8940 (Unemployability - TBD if we need to do this)
- [ ] Untangle get_docs method and what needs to change there
- [ ] Refactor document data creation (EVSSClaimDocument) and additional metadata methods for LighthouseClaimDocument
- [ ] Test branching accordingly

EVSS::DisabilityCompensationForm::UploadBddInstructions(Static document that we always send as part of the bundle)
- [ ] Refactor document data creation (EVSSClaimDocument) and additional metadata methods for LighthouseClaimDocument
- [ ] Test branching accordingly

- [ ] Figure out if `EVSS::DisabilityCompensationForm::SubmitForm526Cleanup` needs to be updated, this is related to `EVSS::IntentToFile::ResponseStrategy` and its unclear how tied to EVSS that is

**Comment by NB28VT** [comment]
Blocked pending completion of polling solution

**Comment by sortizsh** [comment]
pick up polling again after LH upload, then this can be completed.

**Comment by NB28VT** [comment]
TODO: SPLIT THESE INTO THE OTHER TICKETS IN THIS EPIC
