### ISSUE TITLE
IA Request Submit 686 (Add/Remove Dependents)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#6636]
## Required Inputs:
- Link to [**product outline**](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/README.md) 
- [**Link to mockup**](https://xd.adobe.com/view/fef8a415-74b4-45a9-6b5f-da956acd75d9-88c9/)
- [**Link to research readout/results**](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/research-design/686-form-gating-0220/686-usability-analysis.md)
- Link to [**research history masterlist**](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-history.md#february-2020)

## Information Architecture Worksheet (Optional)
Provide the following information, as available, to support the final information architecture of your product.

**SEO Keywords**
- Enter a list of keywords used by your target audience when they talk about or search for your content:
**686
686c
21-686c
Form 21-686c
dependent
dependents
add dependents
add a dependent
add spouse
add child
add stepchild
674
21-674
Form 21-674
marriage
report a marriage
divorce
report a divorce**

**Proposed site map/page structure** (if more than one page)
- This will most likely live very close to the View Dependents feature being built in tandem.  Relevant info from that might be helpful: [**View Dependents IA Review ticket**](https://github.com/department-of-veterans-affairs/va.gov-team/issues/4545) and [**final IA Recommendation for View Dependents**](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/ebenefits-view-dependents.md)

**Suggested URL(s)**
**- Based on previous discussions, this might make sense?** 

Page | URL | Breadcrumb
--- | --- | ---
Add or Remove Dependents static page | www.va.gov/add-remove-dependents | Home > Add or remove your dependents
Add or Remove Dependents tool | www.va.gov/add-remove-dependents/dependents | Home > Add or remove your VA dependents

**Suggested entry points**
- What is the primary entry point for users to find your new content/tool - consider benefit hub pages, top nav, left nav, footer, profile/account, home page, etc.
**We are currently moving this towards the disability hub but it has been discussed that this will most likely exist off the VA.gov root.**

**Crosslinking opportunities**
- What additional related areas of the site would links to your content/tool be helpful?
**Any area of the site that can give context to what benefits are available and the requirements therein.**  [**Family member benefits**](https://www.va.gov/family-member-benefits/) **came up quite a bit in usability sessions where Veterans were asked where they might find more information.**

**Redirects/canonical tags**
- Will existing pages/tools need to be redirected or canonicalized?
**Most likely, yes.  It is anticipated that we will want to redirect traffic from the EBN urls and will need to engage with the EBN technical team to achieve that.**

## Definition of Done
- [ ] Issue is created, tagged and assigned to Content and IA team
- [ ] Required information above is complete and optional information provided where available
- [ ] IA reviews information and provides final feedback/recommendation on ticket
- [ ] Requesting team closes issue upon implementation
- [ ] Requesting team member complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

**Comment by mnorthuis** [comment]
Final IA for your review.  This documentation includes some changes to the previously defined IA for the View dependents functionality - reference this combined IA documentation for both efforts. Please reach out with any questions. 

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/ebenefits-dependents.md

This issue can be closed at  your discretion.

**Comment by shiragoodman** [comment]
@jason-gcio can this be closed out?
