### ISSUE TITLE
Update Veteran-uploaded document infrastructure to work with changes made to submit uploads

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#66365]
## Description

After reviewing the 526 form flow from a UI perspective I've located all of the points where a Veteran can upload documents. We save these documents and then later retrieve them to submit alongside a Form 526 submission in submit uploads (which I already updated for Lighthouse [here](https://github.com/department-of-veterans-affairs/vets-api/pull/13835)).

I have also verified that all of these points upload to the same backend endpoint, and we only need to make changes in one place to prepare these uploads for submission in submit uploads.

For reference, the places where Veterans can/are required to upload documents include:
- VA Form 21-8940 (unemployability - TBD if this is used)
- Unemployability supporting documents (medical records, SSA disability determination) (unemployability - TBD)
- VA Form 21-4192 Request for Employment Information (Vet downloads, sends to past employer, returned and uploaded) (unemployability - TBD)
- VA Form 21-0781 Claim for Service Connection for Post-Traumatic Stress Disorder 
- VA Form 21-0781a Claim for Service Connection for Post-Traumatic Stress Disorder Secondary to Personal Assault
- PTSD supporting documents (SAFE report, divorce documents)
- Supporting Evidence: private medical records
- Supporting Evidence: Service Treatment Uploads
- BDD Additional Evidence

**Comment by NB28VT** [comment]
Initial implementation completed in https://github.com/department-of-veterans-affairs/vets-api/pull/13835/commits/cb9e719882284ae63a68801ba0b6fc56b6163af2; will have reviewed with other changes later in the project.
