### ISSUE TITLE
Verify Endpoint Availability

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#66364]
## Description

Before we get too far into porting over 526 EVSS document upload code to Lighthouse we should verify we can test with their sandbox and their upload endpoint is currently available for testing.

## Acceptance Criteria
- [x] Set up local environment for working with Lighthouse sandbox using [provided doc](https://developer.va.gov/explore/api/benefits-documents/client-credentials) **SAM WARNING: WARNING!!! Don't generate your keys from this step in the Repo ^^^ they should be protected like ssh keys**
- [x] Verify their document upload endpoint is even active in sandbox
- [ ] Determine if we can get a document all the way to a staging user's eFolder (unlikely in sandbox)
- [ ] Sync with Team 1 re: experience working with Lighthouse sandbox what are its limitations?
- [ ] Potentially establish a source at Lighthouse for coordinating/verifying assumptions about document upload
- [ ] Determine if we can use Lighthouse sandbox in its current state to record/mock API responses for automated tests (e.g. VCR fixtures)

- [ ] Follow instructions for working with 

## Links

* [Lighthouse document upload endpoint doc](https://developer.va.gov/explore/api/benefits-documents/docs?version=current)
* [Lighthouse sandbox setup](https://developer.va.gov/explore/api/benefits-documents/client-credentials)

**Comment by austinjprice** [comment]
Saving previous title for reference: "Investigate status of Lighthouse endpoint, set up my testing environment, start working with their sandbox" - Updated to: "Verify Ability Endpoint Availability"

**Comment by NB28VT** [comment]
Was able to start pinging this endpoint with a LH test user my LH sandbox creds and a faked upload and getting validation responses with a local file. However, there are some assumptions about the mime type that the mobile team's code is based around, so still getting some errors back from the API there.

```ruby
document_data = LighthouseDocument.new(
  file_name: "test_doc.txt",
  document_type: "L015",
  claim_id: 1,
  file_number: 1
)
user_icn = "1012667145V762142"
file_contents = File.read("/Users/nathanburgess/ProjectWork/test_doc.txt")
require 'lighthouse/benefits_documents/worker_service'
BenefitsDocuments::WorkerService.new(user_icn).upload_document(file_contents, document_data)
```
I've elected to move on for now, it will be clearer how well the mobile team's upload infrastructure melds with the 526 flow when we can test end to end with everything, including S3 and some of the file conversion/massaging infrastructure that exists around file uploads. I can get around some of that with the above but not all the way there.

**Comment by NB28VT** [comment]
Moving this to in review, the remaining items are mostly related to rollout/testing, which will come later in the project. As mentioned above I was able to interact with the endpoint
