### ISSUE TITLE
Midpoint Review - Content Feedback - AE Profile, Profile Hub 62839

### ISSUE THREAD

**Issue by BSmolensky** [department-of-veterans-affairs/va.gov-team#66371]
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.-

---
**Design Tasks** 
- [x] update the content with out best guess ahead of usability testing
- [ ] attend office hours and confirm the content 
- [x] reassign to FE when ready 

**FE Tasks** 
- [x] update code when we've got the new content 
---

## Thoughts/Questions
This project looks solid. The text is clear and easy to understand. Great work! There are, however, a few areas for improvement. Please reference my comments below.

## Feedback
This content feedback applies to both the desktop and mobile versions. 

### Must
>Personal Information: 

- Issue: The second sentence is an incomplete sentence. 
- Suggestion: Please make that second sentence a complete sentence. 
- Please reference VA Design Systems [Content Principles](https://design.va.gov/content-style-guide/content-principles) section for additional assistance. Continue working with CAIA. 

>Contact Information: 

- Issue: The instructions are confusing. "Address" is too ambiguous a term. "Contact" is a confusing term to use before email address. 
- Suggestions: Please differentiate between mailing and physical addresses and clean up the verbiage associated with email.
- Please reference VA Design Systems [Plain Language](https://design.va.gov/content-style-guide/plain-language/) section for additional assistance. Continue working with CAIA.

>Account Security:

- Issue: "account setup" seems to suggest that the user can "set up" their account here. 
- Suggestion: Please clarify the purpose of this section of the menu. 
- Please review VA Design Systems Plain Language section, specifically the [Use simple words and terms section](https://design.va.gov/content-style-guide/plain-language/use-simple-words-and-terms), for additional assistance. Continue to work with CAIA. 

### Notes:
Thank you again for your great work and the opportunity to review it. Please continue to work with CAIA to maximize the effectiveness of your efforts.

**Comment by BSmolensky** [comment]
@shiragoodman - You have now been pinged!

**Comment by shiragoodman** [comment]
Thank you for the follow up, @andaleliz ! After the call, @BSmolensky talked a bit about whether these 3 items should've been classified as "must" items, so I'm glad you spoke with Danielle and landed on a solution that works for Profile.

**Comment by BSmolensky** [comment]
The final wording looks great! Glad you were able to find a solution that works for everyone. Sorry if there was any confusion. It was a pleasure to work with you team and I look forward to seeing you all again soon. Have a great rest of your week.

**Comment by adamwhitlock1** [comment]
@Samara-Strauss  and @Dottifacilities I have updated the content and it is live on staging now to validate.

Here is what it looks like now:

[Uploading... Screenshot 2023-10-06 at 9.23.19 AM.png]

**Comment by adamwhitlock1** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHNTQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cac8b8ae387b6ed4dc8fb367f367e2355b5f4377/Screenshot%202023-10-06%20at%209.23.19%E2%80%AFAM.png)

**Comment by Samara-Strauss** [comment]
Validated with user 226! I recommend @Dottifacilities validate as well to get to know our products. So it's clear, this is what the copy should be for everything:

**Personal information**

Review your legal name, date of birth, and disability rating. And manage your preferred name and gender identity.

**Contact information**

Manage your addresses, phone numbers, and the email address we'll use to contact you.

**Account security**

Review your sign-in and account information.

**Comment by adamwhitlock1** [comment]
@Dottifacilities I think we can close this one out if you can validate as well?

**Comment by Dottifacilities** [comment]
Validated!
