### ISSUE TITLE
[BE] Update Sequence Diagrams

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#66370]
## Tasks
- Update the Authentication portion of this [Sequence Diagram](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/architecture-diagrams/sequenceDiagram_checkInExp.md) to show new check-in steps logic

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/86678742/14af8d8d-80d8-4892-83c8-5680c503c5eb)

- Update this [CHIP Diagram](https://github.com/department-of-veterans-affairs/chip/blob/master/docs/Initiate-Checkin-Flow.md)

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/86678742/b6301d40-8fe5-46b0-b7bd-e6d9bfde2ea9)

**Comment by randomsync** [comment]
Updated here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/architecture-diagrams/sequenceDiagram_checkInExp.md
