### ISSUE TITLE
Create Suite of Unit Tests for Unit Test Allow List

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#66375]
# Description
Complete the suite of unit tests required to cover 80% of the lines of code contained in the unit test allow list system.

# Acceptance Criteria
- [ ] 80% of the lines of code contained within the unit test allow list scripts is tested by unit tests

**Comment by IGallupSoCo** [comment]
At the time of writing, I have 83.76% line coverage for the workflow scripts.
