### ISSUE TITLE
Research: Discovery convo (Danielle Thierry)

### ISSUE THREAD

**Issue by aplatt-coforma** [department-of-veterans-affairs/va.gov-team#66390]
## Goals
_What outcome(s) do we want to see?_ 
Learn what has been done, known outcomes from what was done and any additional information that will help determine our next steps, scope and/or outcomes. 

## To Do Tasks
- [x] Setup calls ASAP with **Danielle Thierry**: understand how they approached outreach for toxic exposure outreach program
- [x] Setup discussion guide
- [x] Use brief/Slack mining to gather context (where applicable) for the conversation
- [x] Document learnings 
- [x] Update ticket with link to documentation created
- [ ] Prioritize learnings to enable next set of tasks

## Support Docs
- [Project Brief](https://docs.google.com/document/d/1pnZ_ar6E2dBoZSYHnXdp2d7PTvizOTui/edit)
- [Slack Mining](https://docs.google.com/document/d/1FJXX19ZEVeOFvKt-AqkKzjbYb-E63N0BWkoDOgo1s4Q/edit)

**Comment by buddhima-coforma** [comment]
- Emily W - let's decide on her conversation after we speak with Alex
- Danielle T - added a point above to get a discussion guide going

**Comment by djones2113** [comment]
Dropping [discussion guide](https://docs.google.com/document/d/1mAxoLYaviXvccxbN6eD3WPSEd8f4GqTmrubHZ19QAAA/edit) for tomorrow's conversation with Danielle here

**Comment by djones2113** [comment]
FYI: I'm separating this ticket into two separate tickets (one for Danielle and one for Emily)

**Comment by djones2113** [comment]
Closing this ticket as next steps related to learnings from this convo will be reflected in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/67366)
