### ISSUE TITLE
Spike: Initiate discovery convo with VA Data/Eng SME

### ISSUE THREAD

**Issue by aplatt-coforma** [department-of-veterans-affairs/va.gov-team#66391]
## Goals
_What outcome(s) do we want to see?_ 
Learn what has been done, known outcomes from what was done and any additional information that will help determine our next steps, scope and/or outcomes. 

## To Do Tasks
- [x] Setup calls ASAP with ~~**Nick Bastien** from VBA PA&I~~ Alex Prokop who wrote the query to find the potential target cohort
~~Setup calls ASAP with **Matt Braoita's replacement**: has access to VHA's cancer cube. We believe a join was made with Nick's query to get the total of potential target. _Note: Jen B. can provide name of Matt's replacement to contact_.~~
- [x] Use brief/Slack mining to gather context (where applicable) for the conversation
- [x] Document learnings 
- [x] Update ticket with link to documentation created
- [x] Prioritize learnings to enable next set of tasks

## Support Docs
- [Project Brief](https://docs.google.com/document/d/1pnZ_ar6E2dBoZSYHnXdp2d7PTvizOTui/edit)
- [Slack Mining](https://docs.google.com/document/d/1FJXX19ZEVeOFvKt-AqkKzjbYb-E63N0BWkoDOgo1s4Q/edit)

**Comment by jenniferbertsch** [comment]
FYI re Matt Braoita/cancer cube:  we don't need to research this.  Cancer cube just reads data from other VHA sources that were incorporated in the query that generated the cohort.

**Comment by christiejibaraki** [comment]
[Notes/questions ](https://docs.google.com/document/d/1yCBBRu-K9RfSwRggRxVhYjC6BZT-Z9-SqllIVV1NY6w/edit?usp=sharing)to prep for discussion

**Comment by djones2113** [comment]
[Here is our (in progress) discussion guide](https://docs.google.com/document/d/1k9kwRUWz8Sq2EYzPnMvkzVH7r1ng4i5ZPDpWU3IdfVA/edit#heading=h.76u3wumnb1mm) for tomorrow's discovery conversation with Alex Prokop

**Comment by christiejibaraki** [comment]
Recording of convo with Alex Prokop can be found [here](https://drive.google.com/drive/folders/1kZU5oGF-RcC6BaxV_nspYXdCjSDj61hl?usp=drive_link)
