### ISSUE TITLE
Update appointment confirmation details page text.

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#66396]
## Description
We want to update the `View your appointments` and `New appointment` text and links.

These changes should be reflected in the:

- VA Request confirmation details page.
- CC confirmation details page.
- VA Booked confirmation page.

## Expected Design.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdXZkIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--86aa89a2550c896648f3ccb25a378cfa5f6f4205/Screenshot%202023-09-27%20at%2012.06.43%20AM.png)

## Actual (Live) Design.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdGZkIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--41833bb57d600beb2eb9d449ca7346d5c6e3db4b/Screenshot%202023-09-26%20at%2011.25.07%20PM.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdG5kIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0c1dcbfa13d5adb2df988276877f3461c544c741/Screenshot%202023-09-26%20at%2011.26.16%20PM.png)

---

## Acceptance Criteria

- [ ] `View your appointments` text should say `Review your appointments`
- [ ] `New appointment` text should say `Schedule a new appointment`
- [ ] page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/appointment-details.md)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by JRRoof** [comment]
Validated in Staging

<img width="1008" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEp1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c5baf12e1b9b1dd9969bad5cf26818291c3cdb40/image.png" alt="image.png" />
