### ISSUE TITLE
Proofing agent : Authenticate ID (mock up between 2 types of ID)

### ISSUE THREAD

**Issue by porta-antiporta** [department-of-veterans-affairs/va.gov-team#66397]
# Use case:

As a PA I am guided as to how to validate the authenticity of the photo ID presented so that there is increased confidence in the in person proofing process

# Context:

This story is a bit of a stub as we don't yet know whether there will be an API we can pull from identity document providers or if we have to build our own guidance for the pilot. What we do know is that VHIC is not supported by any provider that we've spoken to.

Also for this story, we are discussing physical IDs, mobile IDs will be a separate story

![Authenticate photo ID](https://github.com/department-of-veterans-affairs/va.gov-team/assets/16668007/80a20cb5-2456-46f7-a298-f88bd20b8e09)

# Precondition:

PA has asked Veteran for the evidence

# Flow:

- [ ] PA Selects document type
- [ ] Accepted document type is Drivers License, State ID, or VHIC
- [ ] If Drivers License or State ID is selected, PA is prompted for State or US Territory
- [ ] Upon selecting VHIC or DL/State ID and State/US Territory, the proofing app renders guidance for PA to check.
- [ ] For this story, will only support retrieving VHIC or Maryland drivers license.
- [ ] Proofing agent can toggle between the two

# Acceptance criteria:
- [ ] ID Types supported and additional fields needed to be dynamically rendered
    - [ ] VHIC
        - [ ] Year 
    - [ ] State ID
        - [ ] State
        - [ ] Expiration date
        - [ ] DOB
    - [ ] Driver's license
        - [ ] State
        - [ ] Expiration date
        - [ ] DOB   
- [ ] After completion of selections
        - [ ] If VHIC and year > 2014 render this
        - [ ] If DL and Hawaii and year issued is >= 2015, < 2020 render this
        - [ ] If State ID and Alabama and year issued is > 2020 render this 

Questions/Notes:
- which flow are we going with for the ID type selection?

**Comment by porta-antiporta** [comment]
@skirkman16 See above some points about selection combinations between document types that would be needed.

**Comment by porta-antiporta** [comment]
@lmorris3 would you have time to research:
- VHIC that has expiration date, photo
- Maryland (or Kentucky) DL and security features (can likely find it on DMV site for the state _or_ state bureau of Alcohol control)

It'd give the team some mock content to show what the guidance would look like.

**Comment by lmorris3** [comment]
@porta-antiporta I'd be happy to. I'll share what I find.

**Comment by lmorris3** [comment]
Link to Mural with research findings: https://app.mural.co/t/innovationboards1199/m/innovationboards1199/1695820153034/32f3e6c4093009c2efd77322120d2f069af2c981?sender=uea69eca39541ca1a0bea5755

**Comment by SophiaPhilipMO** [comment]
Decision made on 11/22 
Auto-populate “select id type” field with selection in following screens
Depending on ID type selected, data fields appear that enable type in to find specific state if drivers license or custom field for VHIC, creates potential for expanding ID options

Future decision point needing to be addresses prior to pilot: How we check IDs; if we integrate DocumentChecker or some other tool, for example) and that could change the flow a bit. Possible need to find a workaround (such as linking to a lookup tool, or even manually distributing some kind of booklet with state ID types at the pilot site) suggested by @lmorris3

**Comment by lmorris3** [comment]
Closing this as complete - mockups between two IDs have been created. Still looking into a document checker - part of another story.
