### ISSUE TITLE
[Discovery] Meet with Unauthenticated Experience Leads for Product Health Tool

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#664]
## User Story
As VSP Leadership, I need access to product health tools and GA data on all of the active VFS products so I can make informed decisions about product improvement in one place.

## Goal
Meet with all active VFS product leads and determine data points that need to be added.

## Acceptance Criteria
For each product:
- [ ] Meeting template with conversation guide/questions to be asked
- [ ] Set up meeting with product lead
- [ ] Meet with product lead
- [ ] Determine which other stakeholders, if needed, we should speak to
- [ ] Determine data points to be added

## Definition of Done
- [ ] **Attached to a Milestone** 
- [ ] **Attached to an Epic** 
- [ ] **Labeled with Team** 
- [ ] **Labeled with Practice Area** 
- [ ] **Labeled with Type**

**Comment by nedierecel** [comment]
@joanneesteban Please see the conversation guide for the product line meetings. May you redline my questions below (knowing we have only :30)?  

*Measuring Success*
- What KPIs are you currently using to gauge success?
- What sources do you use to pull these KPIs? 
- Who is responsible for retrieving these metrics?
- What gaps exist currently with pulling these metrics?

*Communicating Success*
- How do you currently communicate metrics to stakeholders? (e.g. Excel files, PowerPoint decks, other)
- How frequently do you communicate metrics to stakeholders?
- What features would be high priority for you in a dashboard (e.g. downloading as PDF, automation, web-accessible)?

*Impacting Success*
- How do you incorporate metrics into your product planning/iterations? 
- How would a dashboard help you iterate faster?

**Comment by joanneesteban** [comment]
@nedierecel Thank you for the conversation guide! To cut down for time:

_Measuring Success_

- What KPIs are you currently using to gauge success?
- What sources do you use to pull these KPIs?
- Who is responsible for retrieving these metrics?
- What gaps exist currently with pulling these metrics?
- _Which forms are you hoping to track?_

~_Communicating Success_~

~- How do you currently communicate metrics to stakeholders? (e.g. Excel files, PowerPoint decks, other)~
~- How frequently do you communicate metrics to stakeholders?~
~- What features would be high priority for you in a dashboard (e.g. downloading as PDF, automation, web-accessible)?~

_Impacting Success_

- How do you incorporate metrics into your product planning/iterations?
~- How would a dashboard help you iterate faster?~

And we can ask the other questions if we have more time or we can reach out for a future conversation  when we get further along in the process.

**Comment by joanneesteban** [comment]
Next Steps:
- [ ] Speak with Lisa about MHV items, Logins, Dashboard
- [ ] Speak with Andrea about Appeals
- [ ] Stretch: Chris, Jen Lee, Andy L: Unauthenticated experiences

**Comment by joanneesteban** [comment]
Duplicated issue.
