### ISSUE TITLE
Proofing agent : Assert authentication of ID

### ISSUE THREAD

**Issue by porta-antiporta** [department-of-veterans-affairs/va.gov-team#66400]
# Use case:

As a PA I am asked to attest what evidence was presented so that our application has a record of it for future auditing processes.

# Context:

After a PA has authenticated photo ID, they attest what evidence was provided and that they checked the photo ID for authenticity.

![Photo ID asserted](https://github.com/department-of-veterans-affairs/va.gov-team/assets/16668007/766c66bf-6e42-4813-bc16-acfc147fc529)

# Precondition:

Guidance on how to check ID was presented.

# Flow:

- [ ] PA has validated photo ID
- [ ] PA asserts the document types provided by Veteran
- [ ] If Veteran provided VHIC or that their address isn't the one on the photo ID, PA asserts Veteran provided another piece of evidence with current mailing address.
- [ ] PA asserts they validated photo ID

# Acceptance criteria:

- [ ] Upon confirmation, proofing app keeps a record of: 
    - [ ] the assertions
    - [ ] document types provided
    - [ ] associated case ID
    - [ ] Proofing agent ID

**Comment by porta-antiporta** [comment]
@skirkman16 pls see above for additional assertions to be saved.

**Comment by SophiaPhilipMO** [comment]
Possibly a duplicate of [ticket 66397](https://app.zenhub.com/workspaces/logingov-adoption-team-632280b31e745000136a61fc/issues/gh/department-of-veterans-affairs/va.gov-team/66397)

**Comment by lmorris3** [comment]
closing - this is complete
