### ISSUE TITLE
Remove Atlas App SOCKS proxy barrier

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#66401]
### Background:
After recent internal discussions, it has been highlighted that all use cases for the Roster spreadsheet weren't entirely considered. While the majority of users utilize the roster in a read-only mode, placing the new Atlas app behind the SOCKS proxy restricts access for individuals without SOCKS access. Offering a SOCKS-less read-only view could potentially address the needs of researchers and PMs who are in search of people.

### Considerations (from discussion with Andrea):
- Researchers often refer to the roster for recruiting usability testing participants. 
- The true replacement of the roster with the Atlas app, while it remains behind SOCKS, seems impractical unless:
   1. We are open to granting SOCKS access to everyone.
   2. We aim to train all non-technical individuals on SOCKS.
   3. We ensure robust documentation is available to assist the support team in guiding folks through access issues.
- Having been around for 4 years, many of us haven’t required SOCKS access for everything, and a survey on SOCKS access among individuals on the VFS and Platform roster might reveal a significant number without such access.
- Currently, we mandate individuals requesting certain access levels (including SOCKS) to verify their presence on the VFS roster first. What would be the approach moving forward?
- Is there a well-thought-out release plan for updating all platform website documentation, confluence, and ticket templates referring to the old roster?

### Action Items:
- [ ] Explore the feasibility of providing a SOCKS-less read-only view of the Atlas app to cater to all user types.  (Let's explore what it takes to create a new domain for atlas vs the vfs subdomain)
- [ ] Conduct a survey or gather data to understand the extent of SOCKS access among current roster users.
- [ ] Draft a release plan for updating references from the old roster to the Atlas app across platform documentation, confluence, and ticket templates.

### Acceptance Criteria:
- A SOCKS-less read-only version of the Atlas app is made available, or a concrete plan is outlined to address the SOCKS proxy barrier issue
- A release plan is developed for updating all references and guides concerning the roster.
- Feedback from different user types (researchers, PMs, etc.) is collected and considered in the proposed solution.

**Comment by RachalCassity** [comment]
Alternatives for ATLAS Authorization have been published in Confluence: https://vfs.atlassian.net/wiki/spaces/TT1/pages/2782101510/Alternatives+for+ATLAS+Authorization

**Comment by LindseySaari** [comment]
TT4 looks to have done some research around what it takes for an application to NOT live behind SOCKS. This could include things like  coordination with the VA, WASA scans, paperwork.

We should also revisit the use cases and user stories for the spreadsheet.

**Comment by LindseySaari** [comment]
A valuable point came up during the discussion regarding the Atlas SOCKS issue. Anything housed under the *.vfs subdomain, including Atlas, is accessible on the VA network (e.g., via CAG, AVD, GFE). The question arises - do the users or use cases encountering the SOCKS barrier have VA network access? If so, this would provide an alternative pathway for users to access Atlas through the VA Network, and eliminate the necessity for SOCKS, rendering it accessible to anyone with VA network access.

Additionally, we may be able to route requests at the revproxy layer to the application. We could possibly
 just mount it at api.va.gov/atlas

**Comment by LindseySaari** [comment]
We're working on routing `dev.va.gov/atlas` to platform-codeowners.vfs.va.gov currently via revproxy routing rules. In the meantime though, Atlas is available on the VA network (e.g. through CAG, AVD, etc) as we work through getting this publicly available.
