### ISSUE TITLE
FSR 5655 event update

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#66410]
## Issue Description
We need to update the fsr-5655 submission event label/action to prevent double firing/counting while still maintaining the detail they need about the submission type (debt, copay, combo. 

[slack convo for reference](https://dsva.slack.com/archives/C01S78V4AUA/p1695317796931579)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbExoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f395bfbec63f248dc6c66ab5c8b6c32db7282ae5/image.png)

---
## Tasks
- [x] submission events updates

## Acceptance Criteria
- [x] No longer double counting fsr-5655-submission--successful
---

**Comment by jestutt** [comment]
@michelle-dooley Who do we need to check with before consolidating the two success events?

**Comment by michelle-dooley** [comment]
Hey @jestutt - Heather Rienks is the product manager, I would reach out to her and explain the change we need to make and why.

**Comment by michelle-dooley** [comment]
removed the reference to Forms - Debt Management.
