### ISSUE TITLE
Create "How to" Video for " GA data layer inspector tool for VFS teams to self serve

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#66415]
## Issue Description

We get a lot of questions in office hours that can be answered with the data layer inspector however most teams are eithe unaware of it or don't know how to use it. We are going to create a 'how to' use data layer inspector video that will be shared with VFS teams so they may better self serve themselves with more basic tracking questions.

---
## Tasks
- [ ] Create the video

## Acceptance Criteria
- [ ] Publish the video
---

**Comment by johnny-jesensky-adhoc** [comment]
We covered this as part of our GA4 Training series -- recording has been uploaded to our Slack Canvas. Closing out this ticket.
