### ISSUE TITLE
Health Page Static Content Migration (CMS -> vets-website)

### ISSUE THREAD

**Issue by hinzed1127** [department-of-veterans-affairs/va.gov-team#6642]
Based on outcomes from #5804, CMS static content for the following `health-care` subroute pages need to be migrated to `vets-website application code:

 - `/refill-track-prescriptions/`
- `/schedule-view-va-appointments/`
- `/view-test-and-lab-results/`
- `/get-medical-records/`
- `/secure-messaging/`

To ensure proper content remains displayed, the following updates need to happen in sync with one another: 

1. content is removed from CMS and deployed for the aforementioned pages
2. pages/content are added to `vets-website`

**Comment by hinzed1127** [comment]
Similar to the account_id changes being split out on the api side, I'm going to split this up into tickets per page. 

Since this requires parallel changes in the CMS and vets-website, doing a first pass of that migration with the scheduling page will hopefully get most conversation happening there and then the subsequent pages can quickly follow suit

**Comment by christine-dillman** [comment]
Closing.  This ticket should have moved to the Health Website Pages.
