### ISSUE TITLE
Spike: Review data that was previously pulled

### ISSUE THREAD

**Issue by aplatt-coforma** [department-of-veterans-affairs/va.gov-team#66429]
## Goals
Gain understand on how the data was pulled and how we can potentially use it for our project. 

"...We found 44,414 prostate cancer results and 2,983 breast cancer results. More details of the VHA query at Active Cancer Query Notes.docx" - see brief for logic summary

Establish access to data necessary for veteran selection and outreach (if needed)

Use ""VHA medical data and VBA service history records to proactively reach out to Veterans"

## To Do
- [x] Understand how the data was pulled, and what the data looks like
- [x] Understand accuracy, completeness, newness, false positives/negatives of data. List any issues and potential blockers
- [x] Establish access to VHA data

~Nick Bastien is a resource~
Alex Prokop is a resource. Nick Bastien helps with PA&I data specifically.

## Supporting docs:
[Project Brief](https://docs.google.com/document/d/1pnZ_ar6E2dBoZSYHnXdp2d7PTvizOTui/edit)

**Comment by aplatt-coforma** [comment]
@christiejibaraki - Attached are the query notes that Jen shared in Slack.
[Active Cancer Query Notes.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/12751536/Active.Cancer.Query.Notes.pdf)

**Comment by christiejibaraki** [comment]
notes on getting vha cdw access: https://docs.google.com/document/d/12ppf4NbL1pe7gnq_U1S-ndx1tz-I1f-7ubhjiZbZqyg/edit?usp=sharing

notes on getting contact info: https://docs.google.com/document/d/1PbybYNclec3fVUMlMlfvnGzk1Raujdc9fK36jgTVGGo/edit?usp=sharing

**Comment by christiejibaraki** [comment]
I can query VHA CDW using the notes linked above [Active Cancer Query Notes.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/12751536/Active.Cancer.Query.Notes.pdf)

**Comment by christiejibaraki** [comment]
[Notes on the data sources](https://docs.google.com/document/d/1yCBBRu-K9RfSwRggRxVhYjC6BZT-Z9-SqllIVV1NY6w/edit#heading=h.1hah8ntw8t1x)
