### ISSUE TITLE
[FE] Enable Travel Feature for VISN 6

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#66423]
## Description
We need to enable the travel feature for all of VISN 6.

## Tasks
- Get the correct list of facilities from Mark
- Add the list those allowed access to the travel feature
- Merge/Release to production on October 9th

**Comment by brianseek** [comment]
Update: Turning on 657GB 10/30 and 657GA 10/31. VISN 6 will be full roll out but with a soft date of 11/15

https://dsva.slack.com/archives/C022AC2STBM/p1698354472550379?thread_ts=1698352035.909109&cid=C022AC2STBM

https://dsva.slack.com/archives/C022AC2STBM/p1698352621599379?thread_ts=1698352035.909109&cid=C022AC2STBM
