### ISSUE TITLE
Search not working on client documentation website

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#6643]
Search should show a dropdown list of documents with matching tags on the client documentation site.

**Comment by billfienberg** [comment]
I’m not sure how/why, but the Gatsby search seems to have fixed itself. 

![gatsby-search-started-working.gif](https://images.zenhubusercontent.com/5dcadfa162b0b700019b1427/18f0b25c-a9a8-4c43-a203-1af34b4e6495)
