### ISSUE TITLE
SOCKS access for [Tommasina Miller]

### ISSUE THREAD

**Issue by tommasina-va** [department-of-veterans-affairs/va.gov-team#66451]
### Your Name

Tommasina Miller

### Your Email

tommasinamiller@navapbc.com

### Your Role and Team

Software Engineer on Benefits Disability Experience team

### Product Manager (PM) name and email

Rakshinda Aslam - rakshinda.aslam@agile6.com

### Product Owner (PO) name and email

Emily Theis - emily.theis@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDpbBZLbFYE0Mssh8hPBhrt5HtlExGbj8kXBbVKr3W3C4pIYXrxRZDXdqu1xAY7cTg/SufY8uQ9F1E1wJBTpRCATseCFPwY8sgcjWiCCPSW+O7gnEKUi5G8Ak3HPhFGwwY9JXDXqeouli2hJhppKzbPasQUEJmt2C4z0cZUpYBbHhaBf1LIC8gAF7pStYjKNQ79WBEhKbo2h+sPTRdHf1dukVxdw/Z4OqEW8MGoMARlxdRKq+rqDbegR1evfjNvrymce6GKtYPN8RFWwAOP3Hg3zGGFg+o0zH8UqkhPVLTy6eGCdfVrD8N2/9XmRTxxo6LQGFPxJoO6oIxglrmEDD5gqKhAFFVq8c56O5TEOMMlASG6/qQam6FTuYNUpq2jtnrQrL9Ui+ImSk9dzfJ+aerwR3ZFO11kD0rKYDOnRGoqrar3pKrThmArRSt4EhpOoHxVYL3vv4DMCuvlH/UX6u3U3tESv/K6VLyWAeq9tZe18iveeK3Qwhu1oin5UQSdXo0= tommasinamiller@Tommasinas-MacBook-Pro.local

### E-QIP Transmittal Confirmation

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/144388524/0127d425-2276-4b32-a64c-46c0dc0fa161)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by ph-One** [comment]
Completed
