### ISSUE TITLE
[BE] 10-10EZ: Discovery--Does EZ API have EC and NoK?

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#66468]
As a Veteran, I would like to be able to update my NoK and EC on the EZR form so that I make sure the VA has up to date information in case something happens.

- [ ] Determine if NoK and EC are in EZ API
- [ ] If they are, see what information they contain (Name, address, Phone, primary/secondary, etc.)
- [ ] **Success: We know whether or not the EZ API currently supports EC and NoK**

**Comment by lihanli** [comment]
<ns0:associations>
         <ns0:association>
            <ns0:address>
               <ns0:city/>
               <ns0:country/>
               <ns0:line1/>
               <ns0:state/>
               <ns0:zipCode/>
            </ns0:address>
            <ns0:contactType/>
            <ns0:familyName/>
            <ns0:givenName/>
            <ns0:middleName/>
            <ns0:relationship/>
         </ns0:association>
</ns0:associations>

contactTypes:

1	Primary Next of Kin
2	Other Next of Kin
3	Emergency Contact
4	Other emergency contact

all fields required except for middle name

**Comment by lihanli** [comment]
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/830084/82f38dad-c8d8-4725-b2fa-e005e965d0e5)
