### ISSUE TITLE
AWS access for [Tywande Barnes]

### ISSUE THREAD

**Issue by tynyttie** [department-of-veterans-affairs/va.gov-team#66474]
### COR Name

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative Name

Other - please specify in 'Additional Notes'

### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Tywande Barnes

### Your Email

tywande.barnes@va.gov

### Team, Role, and Company of the target individual

MHV medical records, software engineer, acommsolutions

### Product Manager (PM) name and email

Lichelle Bain lichelle.bain@va.gov

### Product Owner (PO) name and email

Patricia Henry Patricia.Henry@va.gov

### Desired AWS Access

Requesting access so I can run a local tunnel to the fwdproxy, so that I can access upstream services from my local vets-api instance. I believe this requires the SSMApplicationLowerEnvironmentAccess policy, and to be added to the existing IAM group dsva-vfs-developers.

### Access Expiration

on going

### E-QIP Transmittal Confirmation

![Screenshot 2023-09-27 at 3 14 11 PM (2)](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8038703/1d8e4d0f-1243-463f-804a-2f398d88f890)

### Additional Notes

COR: Sean Good
Vendor Onboarding Representative: Kenneth Brown
Access Expiration: Need ongoing access to upstream data APIs in lower environments for VFS development activity

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by flooose** [comment]
Hi @tynyttie could you please add your COR and "Vendor Onboarding Representative Name"?

**Comment by mmoyer-va** [comment]
Hi @flooose -- The "Additional Notes" section of Ty's ticket contains his COR and Vendor Onboarding Representative.

> COR: Sean Good
> Vendor Onboarding Representative: Kenneth Brown

**Comment by flooose** [comment]
Oh, sorry, I got confused. 

Still though, I do have a question about your "Desired AWS Access"

> Requesting access so I can run a local tunnel to the fwdproxy, so that I can access upstream services from my local vets-api instance. I believe this requires the SSMApplicationLowerEnvironmentAccess policy, and to be added to the existing IAM group dsva-vfs-developers.

This sounds to me like @tynyttie already has AWS access and just needs to be granted more, but I don't see them in [iam_users.tf](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf)

**Comment by mmoyer-va** [comment]
No worries! I do not believe that Ty has an AWS account. He would need both the account and the desired access.

**Comment by mmoyer3** [comment]
@flooose I should have tagged you in my previous comment. Just wondering if there have been any updates here.

**Comment by jknipes** [comment]
Found in VFS Roster

**Comment by barbarello** [comment]
In Atlas

**Comment by ph-One** [comment]
Closing. User has been added to AWS and contacted with follow-on details
