### ISSUE TITLE
Enable Resident clinics for VA self-scheduling

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#6647]
# Stakeholder input:
## High Level User Story / Problem / Opportunity
When Veterans are scheduling an appointment, I want to Veteran to schedule with Resident physician instead of Attending physician because approx 80% of veterans are seen by their Resident doctor. 

- In a medical facility, the physician who has the major responsibility for a patient's care is called the attending physician. A resident physician is supervised by an Attending physician
- Each PACT has at least one Attending physician and potentially multiple resident physicians
- For PACT, need to understand if current configuration in VistA allows for this

## Goals / Outcomes
- Is the goal to decrease time in scheduling process for Scheduling managers? *Need input*

## Stakeholder AC Score:
_(Calculations made [here](https://docs.google.com/spreadsheets/d/1fuGBtMRYTze0Z8_fvw4EmqiSVOwjC1ZIv8E5JECL2o0/edit#gid=836967960))_

---
# Next iteration of Epic after initial Stakeholder input:
## Hypothesis or Bet
**If** _we make this change_ **then** _we expect this to happen_.

### What must be true in order for you to consider this epic complete? 

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## (Optional) Supporting Documentation
_Link to Additional Implementation artifacts- requirements based on policy, data, system-related needs_

## Issues to create within this Epic

```
- If discovery needed, create Discovery/Research Epic
- If no discovery needed, break epic into corresponding stories and tasks
```

## How to configure this issue
- [ ] **Labeled with `roadmapOCC` and `VAMF` and `vaos`**
- [ ] **Add Epic to VAOS-R Roadmap Project in Github - must do this in GH, not Zenhub**

**Comment by laurenernest** [comment]
Documented here for reference later https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/product/future-work-requests-ideas.md
