### ISSUE TITLE
Design Intent - Accessibility Feedback - Benefits Non-Disability, Pension 527EZ, Form Reactivation

### ISSUE THREAD

**Issue by briandeconinck** [department-of-veterans-affairs/va.gov-team#66475]
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- Just to repeat what I said at the meeting: Great user flows! Just mapping all of that out is a huge accomplishment, let alone building the product!

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- **Should:** Wherever possible, try to use a "one thing per page" approach rather than any sort of conditional display of information or form fields. There are a handful of situations where conditionally revealing new things makes sense, but usually breaking things into separate pages helps with cognitive load (keeps focus on a particular task) and avoids some tricky assistive technology interactions.
- **Consider:** Since this is a long and complicated workflow with a heavy cognitive load overall, it may be worth exploring mid-flow interruptions to tell users what they've done, what's coming next, and what they'll need for that next part. (eg. "You've now finished, X and Y. Next up is Z, which should take about 10 minutes. You'll need...") I don't know for sure if it's going to add value, but I feel like it's worth exploring and maybe testing with users. Note that since there's no existing pattern around this, you'll want to bring it through the [experimental design process](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns).
- **Should:** I promised to share some list-and-loop examples from various products, but the [multiple responses pattern](https://design.va.gov/patterns/ask-users-for/multiple-responses) page includes enough variations to hopefully give you something to dig into. From the user flow I think the [multi-page variation](https://design.va.gov/patterns/ask-users-for/multiple-responses#how-to-design-and-build---multi-page) and the [add item variation](https://design.va.gov/patterns/ask-users-for/multiple-responses#how-to-design-and-build---add-item) might be most interesting to you --- but you know your product better than me, so I might be totally off on that.

**Comment by fiorella-io** [comment]
@briandeconinck What is the maximum amount of fields you would suggest we have per page? Should we break an address that could have 7 fields (country, street address lines 1 and 2, city, state, zip code)? Can we keep similar fields together (eg. Service start and end dates)?
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/91498500/aa2d0c71-cfe8-4dcf-b0b0-02b67ee4a91b)

**Comment by mayacoforma** [comment]
@vbellissimo 
The design intent phase of the collaboration cycle occurred while Fiorella was working on the pension form. My understanding was that she had, for the most part, incorporated those suggestions before passing the task on. Could you please clarify what is expected of me for this task?

**Comment by vbellissimo** [comment]
@mayacoforma We can sync up with @steele-lm and @fiorella-io on this at a later time. If your understanding is right that she's incorporated the suggestions above to the designs already, I don't believe think this is priority. It also looks like the suggestions from here are "should" and "consider", not "must". We're only focusing on any feedback that would have been a "must" for the MVP relaunch of the form.

**Comment by vbellissimo** [comment]
Moving this back to Icebox

**Comment by fiorella-io** [comment]
Since the feedback was labeled as "Consider" and not "Must", I did not incorporate this feedback. Just wanted to let you all know.

**Comment by aplatt-coforma** [comment]
@gmaciolek reviewed this and recommends we wait until after assess the usability study findings to try and address this ticket. Keeping it lower in the backlog.

cc @buddhima-coforma

**Comment by gmaciolek** [comment]
@buddhima-coforma and @matt4su I think we can close this one out and incorporate this feedback into our solutions for the work that will come out of usability testing

The supporting documents work addresses part of the first "Should" bullet item, but I think the full scope of what's being suggested here involves reconsidering our approach anywhere we're conditionally revealing things. I don't disagree, but I don't think we need to prioritize it as a standalone effort.

I love the consider recommendation here, but I don't think it's a higher priority than other items we're considering. 

I'll be sure to reference the multi response pattern documentation in future design updates to see if there's something there that might support prioritized UX changes.

**Comment by aplatt-coforma** [comment]
Per Gretchen's note from 3/26 I'm closing this ticket.
