### ISSUE TITLE
SOCKS access for Richard Davis

### ISSUE THREAD

**Issue by dickdavis** [department-of-veterans-affairs/va.gov-team#66485]
### Your Name

RIchard Davis

### Your Email

richard.davis@bylight.com

### Your Role and Team

Backend Engineer on VSP Identity

### Product Manager (PM) name and email

Mike King

### Product Owner (PO) name and email

Tom Black

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCwppASPeocztd1rf8aJZW2Fuuv+LRJDUCg67ICYj70XtWWPVGYkMbzmlRv1ltDwJu83kowLmY4EWn6nNfdYTmOWnL61gVay9q4DTiP7KFRX5M0UsQhYjcLEBuJ/HThJYKMSA8fHPwQyzzNBsywwNxHvKntwea49EW/eSVklFaAJjUlbmqHVOW4IX4G+8zwCX3uoM9qnMlJbAPS7g8kpMQ5vay13J5vemOP+3ttYhpnnPMTvb9Q52ARpVd23wO8RnJhtCuTCVhwl8MJSNjne4h1vm3rOGrN1aweI4oeTG9YE64c7VegeyAfOd906GlMa51TFdKZE7C67r5bRiWph55A6F+ZL8k1xLgJebsA55YaP4yGPqPqTb8yDi+Pv4R2qpFKJ650UUNVpVMBVVxTQjt6kQTH0EDNEk55tpViYiTdYYtwPU6gSasLLgE7ESo6QRNW+c1O5nDPMSKsevYt5yCz8D6n9qIhxVgkT2o/uTcJNWO6rqNzPKIxwKOCXYHuBGM= dickdavis@K97YWFW54X

### E-QIP Transmittal Confirmation

![Screenshot 2023-09-27 at 4 03 36 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/10838930/b24b1676-c4b1-40bb-92be-08c01fa47983)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by ph-One** [comment]
SOCKS access completed
