### ISSUE TITLE
Analytics Implementation or QA Support for [Public Websites - Datadog UX monitoring in Benefit Hubs]

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#66481]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

</div>
</details>

### Required
- **Is this request for **Google Analytics implementation** or **QA**?**

     - [ ] Google Analytics implementation
     - [ ] QA
     - [x] **DATADOG – this ticket is meant to explore a Datadog UX monitoring implementation**. Desired functionality includes heatmaps and robust user flow visualizations.

- **Who is this request for?**

    - Public Websites
    
    
- **Provide the link(s) for Google Analytics implementation or QA**
  
    - Benefit Hubs (e.g., /heath-care – all visible in the megamenu)
    
- **When is the launch date?**
    - already live

- **What interactions need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked_
    
  - We want to set up Datadog on all pages in the Benefit Hubs.

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by wesrowe** [comment]
@michelle-dooley, I created this issue to bring you in on early discussions of leveraging Datadog's RUM (Real User Monitoring) analytics capabilities. This is not an implementation request, it's more of a discovery request.

Cc @jilladams.

**Comment by wesrowe** [comment]
Just viewing Datadog's RUM data within DD's dashboard is our initial proposal.

**Comment by michelle-dooley** [comment]
@wesrowe datadog is a dev ops tool, our team does not manage it or create dashboards within it. We have discussed bringing datadog data into Domo to further enhance our standardized and other custom dashboards but there is no timing around that.

**Comment by wesrowe** [comment]
Datadog has a portfolio of tools. I think they were originally focused on devops. But now they have a complete UX monitoring toolset, RUM (real user monitoring), that is completely UX-oriented. Similar to Hotjar.

**Comment by michelle-dooley** [comment]
So I am unclear on what the ask from Analytics & Insights team is?

**Comment by wesrowe** [comment]
@davidconlon @DanielleThierryUSDSVA, it sounds like Platform Analytics has Datadog RUM on their roadmap but has not scheduled it. Do you have any additional questions for Michelle?

**Comment by wesrowe** [comment]
Closing, can re-open if stakeholders come up with questions later.
