### ISSUE TITLE
Refactor specs that fail under the parallel tests gem

### ISSUE THREAD

**Issue by kreek** [department-of-veterans-affairs/va.gov-team#665]
## User Story
As a developer I want all specs to pass using the parallel tests gem so that the TDD development cycle is faster.

## Acceptance Criteria
Some rspec examples in the following specs fail under the parallel tests gem:

## Detail
```
spec/controllers/v0/vic/profile_photo_attachments_controller_spec.rb
spec/jobs/transactional_email_analytics_job_spec.rb
spec/jobs/vic/submission_job_spec.rb
spec/jobs/vic/submission_job_spec.rb
spec/lib/vic/service_spec.rb
spec/request/preneeds/burial_forms_request_spec.rb
spec/request/swagger_spec.rb
spec/uploaders/evss_claim_document_uploader_spec.rb
```
The specs share state and need to refactored so they're properly set up and torn down and the sprint. They share in common either creating/deleting files or running background jobs. One fix was to wrap a test helper with a mutex.syncronize so that access to files is locked per thread. Other tests probably do to much in that they are more integration tests than unit tests and we should mock and stub behavior not directly related to the subject's behavior.

**Comment by annaswims** [comment]
parallel tests gem  draft pr here https://github.com/department-of-veterans-affairs/vets-api/pull/3169
