### ISSUE TITLE
Access for Derek Dyer

### ISSUE THREAD

**Issue by digitaldrk** [department-of-veterans-affairs/va.gov-team#6650]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your name.
   > Derek Dyer
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > vsa-eBenefits, Backend Engineer, GovernmentCIO
- What is the **public** SSH key?

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC+ADUUaZPBID2dCMiJx6LEzquwnLKABk8KEw4y+cEbRri3X0Q76wvKS037/T1EuObbKycuqd7O1LM4gy1QKUuMguvVAoZkOfnuGBvaI2OGEONl/WxsXgwU+uBCEuPiS5t0/zasGiclsz4+d9lTgVb7XNYUqH6ZBHwzCJly/zGvdk0VWVZ9rSmvak6pHkQwpTCeDtjRrKwRMo0zcp1M0XGOgDb24Ja7mtx2QS01wyErYFzEkXWbB31RyvSdcyNpWwiB8k2HJuXpqqj4eXGJmL0om4DmI8RbnA+bceNvAL8rKMgQAKPEne5cGmvDF5mHCR0jrj5ALChZxLXLE1LPAtip derekdyer@Usrmonitors-MacBook-Pro.local
```

- [Grant AWS Console access?]
> YES
> Our infrastructure is hosted in and makes use of services in AWS GovCloud. This account is shared amongst many different teams; changes made to resources in this account will affect many services. You will need access to AWS for troubleshooting, log file review and to apply changes to the running instances and services.

FYI:  @department-of-veterans-affairs/vsp-operations

**Comment by ricetj** [comment]
@Jeff-Hayter 
User: Derek Dyer
COR: Mary O'Toole

**Comment by jbritt1** [comment]
SOCKS access granted. @digitaldrk, please continue with the guide for establishing a connection to SOCKS proxy.

**Comment by kathleencrawford** [comment]
@ricetj Derek has successfully submitted his e-QIP, can you please let us know if anything else is needed for AWS access?  Thanks!

FYI @short000

**Comment by jbritt1** [comment]
I can grab this if all is approved / good to go @ricetj

**Comment by Jeff-Hayter** [comment]
@jbritt1 Approved for AWS.

**Comment by jbritt1** [comment]
On it.

**Comment by kathleencrawford** [comment]
Thank you @jbritt1 !

**Comment by jbritt1** [comment]
User created, will send a DM via Slack with first time login instructions / credentials momentarily.
