### ISSUE TITLE
Make corrections to CODEOWNERS (FE)

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#66504]
## Background
**NOTE:** This is related to the vets-website repo
There were recent changes to vets-api CODEOWNERS (ticket [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65783)) which prompted us to reevaluate the way that we handle GitHub teams for both frontend and backend. We ended up creating 2 new GitHub teams for our squad (`benefits-management-tools-fe` and `benefits-management-tools-be`). We need to update the CODEOWNERS file to cover the files that our team owns

## Tasks
- [x] Update CODEOWNERS to properly reflect which folders our team owns

## Acceptance Criteria
- [x] CODEOWNERS properly reflects which folders are owned by our team

**Comment by HeatherWidmont** [comment]
@jerekshoe is this something that @kjduensing should review, or the Platform team?

**Comment by jerekshoe** [comment]
Platform has to review it before it can be merged. I can add him as a reviewer if he wants to review it
