### ISSUE TITLE
CH 36 documentation of error handling and async jobs

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#66515]
## Issue Description
Create a sequence diagram and/or document the flow of the CH 36 form from submission all the way till it kicks off the sidekiq job. 

---
## Tasks
You can follow [this](https://github.com/department-of-veterans-affairs/vets-website/blob/0a86d7dc98a09725c0cf8e4e462ad95d947de088/src/applications/disability-benefits/686c-674/documentation/674.md) example.

Here is the claims controller:
https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/controllers/v0/education_career_counseling_claims_controller.rb

Feel free to throw in a diagram if it helps.

**Comment by mjknight50** [comment]
Documentation for sidekiq completed and was [merged](https://github.com/department-of-veterans-affairs/vets-website/pull/25835)

**Comment by mjknight50** [comment]
Closing this piece of the overall work
