### ISSUE TITLE
[MVP] Discovery for setting up Datadog, including access for team member

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#66512]
## Issue Description

As a new Pension team, we need to identify what logging and monitoring data points we can measure as part of the Pension form relaunch, so that we know what steps to take to set it up when we're able to.

Examples:
- Number of submissions
- Number of in progress
- Avg time to complete
- Failed submissions to Sidekiq

Other examples to consider as documented by NDB team:

- When a claim submission upload has failed (set up in retry; set up for 14 times)
- When a claim submission upload has succeeded (set up in retry; set up for 14 times)
- When a claim submission upload has exhausted (set up in retry; set up for 14 times)
- When a claim submission upload has begun
- When a claim attachment upload has failed
- When a claim attachment upload has succeeded
- All logs include user id and claim submission id.
- Attachment upload logs should also include the attachment id

**Note:**
- Pending access to tools such as Datadog, to explore some of the other examples listed above

**Observations to date:**
- ID is not being captured

**Ideas/Open Questions:**
- Refactor to pass user ID but risky if multiple forms use this sidekiq job (logging user ID before job starts)
- Question If we move to Lighthouse Benefits Intake API, should we wait to set this up?

**Should we log the following? / Reach out to Steve Albers**
-- Log Use ID
-- When a claim attachment upload has failed
-- When a claim attachment upload has succeeded

---

## Acceptance Criteria
- Understand to the extent that we can what it would take to set up logging and monitoring the performance of the Pension form via Datadog and/or any other applicable systems to prepare the set up for Pension relaunch.

**Comment by mjknight50** [comment]
@vbellissimo To be clear, this is just discovery on this ticket?

**Comment by vbellissimo** [comment]
@mjknight50 Yes, let's treat it as **just** discovery.

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/66512?planning-poker) with Zenhub @mjknight50 @TaiWilkin @ToddWebDev

**Comment by mjknight50** [comment]
@TaiWilkin Can you please pick this up and work with @vbellissimo on it?

**Comment by vbellissimo** [comment]
Logs exist that capture:

- when an attachment submission has **begun**
- when an attachment submission has **failed**
- when an attachment submission has **succeeded**

The user ID is logged where possible (outside of the sidekiq job)

**Comment by TaiWilkin** [comment]
See additional DataDog investigation notes [here](https://docs.google.com/document/d/1a9hJI8vDmPSGW7wlYRT3G-Ao3qBG48vOt92f6iAVNbs/edit?usp=sharing)
