### ISSUE TITLE
Redirect Request: VetSuccess on Campus page (Careers/Employment)

### ISSUE THREAD

**Issue by lunascoop** [department-of-veterans-affairs/va.gov-team#6652]
### Instructions
- Requests for redirects need to be submitted **AT LEAST** 2 weeks in advance.  Some redirects take significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation of the redirect to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.
- It is your responsibility to notify VA stakeholders of pending redirect.  

### Description
*This is a detailed description of the request. It should include background information and reason for the request.*

### Requestor team info
*Indicate what team and who the primary contact on that team is*

### Implementation date
Date new URL(s) will be live: *03/03*

Please indicate when the redirect(s) needs to be implemented"
- [ ] On the same date the new URLs launch
- [ ] Can happen within 1-5 business days after new URLs launch
- [x] Other - Please indicate timing : 7 days after URLs have been vetted

**The requesting team is responsible for notifying the group working on this issue if the target date changes. They are also responsible for ensuring the destination URLs are implemented correctly and live at the time the redirects are deployed.**

### Redirects needed

Current URL  |  Redirect Destination (new URL)
---  |  ---
https://www.benefits.va.gov/vocrehab/vsoc.asp | https://www.va.gov/careers-employment/vetsuccess-on-campus/

### Definition of done
- [x] Above information is provided and issue is tagged and assigned appropriately - *@ requesting team*
- [ ] All appropriate VA stakeholders are notified of pending redirect - *@ requesting team*
- [ ] Redirect request is vetted and documented and implementation plan is clear - *@ Content & IA team*
- [ ] Request is assigned to appropriate team for implementation - *@ Content & IA team*
- [ ] Implementation team completes work - *@ Implementation team*
- [ ] Implementation pushed live and redirect is validated in production - *@ all*
- [ ] Ticket is closed - *@ requesting team*

**Comment by mnorthuis** [comment]
@lunascoop These two pages do not appear to be in parity with one another.  Are there updates to our page planned?

**Comment by lunascoop** [comment]
@mnorthuis From what I understand in ticket #3198, the updates to the Vetsuccess page has gone live. And the stakeholders have approved the updates (@AnneHurley comment in the ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/3198#issuecomment-595386343). 
Also here's a screenshot of the last email correspondence:
<img width="1139" alt="Screen Shot 2020-03-10 at 10 10 36 AM" src="https://user-images.githubusercontent.com/42546515/76320848-99608c00-62b7-11ea-9d1b-64619218a74a.png">

**Comment by mnorthuis** [comment]
@lunascoop @AnneHurley Did we resolve this one?  I don't believe we will be redirecting the legacy page, so can we close the issue?

**Comment by lunascoop** [comment]
We can close it since we won't be redirecting this page.
