### ISSUE TITLE
Environment save issue with Pension form

### ISSUE THREAD

**Issue by aplatt-coforma** [department-of-veterans-affairs/va.gov-team#66531]
## Background
Reported to Thomas Blackwell. 

There are two fields for Pensions that are being saved successfully in the lower environments but are not being saved in Production. 
Has been thoroughly tested in LINKTEST

## Acceptance Criteria:

- [ ] Work with (team X?) to look at submission to see where the failure is happening on submission or receiving endpoint.
- [ ] If failure is our side, please fix

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/66531?planning-poker) with Zenhub @mjknight50 @TaiWilkin @ToddWebDev

**Comment by mjknight50** [comment]
@tblackwe I'm confident that we will take care of this in our testing, but I do have a couple of questions:
1.  Which fields?
2. Why would a field be saved in one environment but not another?   Different code?

**Comment by vbellissimo** [comment]
@aplatt-coforma @mjknight50 can we close this ticket since this was logged before we deactivated?

**Comment by mjknight50** [comment]
Whatever this was capturing seems irrelevant now.
