### ISSUE TITLE
GIS Mapping Integration on Intake

### ISSUE THREAD

**Issue by rdvyas** [department-of-veterans-affairs/va.gov-team#66543]
As part of the Intake process an External User will have to choose a site to perform the IPP. There is a screen noted below where a person will look up facilities based on their Zip Code:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcGZxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--13898b1a0f701a2ad2a026e3eb160a3a7b91cd0d/image.png)

https://developer.va.gov/explore/api/va-facilities

DEF of DONE:
- evaluate GIS services
- decide which service is appropriate for which platform

**Comment by sdickson-gt** [comment]
- will need to update the underlying VA datasources to add new service type, e.g. "Other/IPP" and implement processes to maintain it.  See following example facility response: https://github.com/department-of-veterans-affairs/lighthouse-facilities/tree/master/facilities
- will need to leverage a map service separately

**Comment by rdvyas** [comment]
Seems that these are the types of facilities that we can return:
Health facilities (vha)
Benefits facilities (vba)
Cemeteries (nca)
Vet Centers (vc)

@skirkman16 @SophiaPhilipMO We need to identify which location types will have Proofing Agents in the future, maybe not so important for Pilot, but neccesary after.

**Comment by rdvyas** [comment]
We have identified a GIS service for the facility lookup functionality. Closing as completed.
