### ISSUE TITLE
AWS Console Access for Eric Buckley

### ISSUE THREAD

**Issue by ericbuckley** [department-of-veterans-affairs/va.gov-team#6654]
# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Dan Navarra
- Please provide your name.
   > Eric Buckley
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VA Startup, Sr Engineer, Ad Hoc

- [Grant AWS Console access?]
  > Yes
  >  access to debugging info via AWS logs and ability to run ad hoc database queries via Rails console, in staging (and/or production on as needed basis)

**Comment by ericbuckley** [comment]
ping @department-of-veterans-affairs/vsp-operations

**Comment by ricetj** [comment]
@Jeff-Hayter 
User: Eric Buckley
COR: Dan Navarra

**Comment by Jeff-Hayter** [comment]
@ricetj  Approved for AWS.

**Comment by jbritt1** [comment]
First time login credentials / instructions provided via Slack DM.
