### ISSUE TITLE
IPP - Create Data Flow Diagram for User Screens

### ISSUE THREAD

**Issue by lmorris3** [department-of-veterans-affairs/va.gov-team#66558]
Understanding the Initial data model for IPP App related persistance.

Acceptance criteria:

Draft IPP data model draft
Draft IPP data dictionary
Share draft with login.gov

**Comment by porta-antiporta** [comment]
Created a [MURAL diagram](https://app.mural.co/t/innovationboards1199/m/innovationboards1199/1696132486784/5380060251df1fa678171112f818d00800fe6582?sender=u1cdf5efd431a84e736d31400) to show types of data and flow that can serve as input int he the artifacts in the AC

**Comment by rdvyas** [comment]
Both data flow and data dictionary first drafts are located below. We will continue to update as we get more information. 

data flow: https://app.mural.co/t/innovationboards1199/m/innovationboards1199/1696563943931/654bbd3139e9de1dd4ca0c679a77c9d7286565ac?sender=ubaed9022e894858e004b6707

data dictionary:
https://docs.google.com/spreadsheets/d/1jCMZ1r84r0DQL2-GxQObHHJkxMUV6rixwO9n9haWhzE/edit#gid=0

Marking tickets as closed
