### ISSUE TITLE
Usability Research Identity Dashboard

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#66550]
### Description 
The purpose of this work is to ensure the Identity Dashboard our team is creating, is user friendly and offers the needed and desired features

The Identity Dashboard is a collection of applications to be used by VA employees and contractors.
 - Client config - a landing page where other VA application teams can register their applications to create an integration with Sign in Service or the Unified Signin Page (USiP). The page will look and act very similar to how the developer client page looks for login.gov. (See image below here)
 - BDPR Dashboard - A collection of information which will serve to assist the BDPR with investigations.
 - MPI Search - A tool which allows authorized users the ability to lookup user information of a user within MPI.
Outstanding question: do we have some kind of separation of environment lookups. It's probably ok to allow any engineer the ability to lookup staging and below, but only a select few should be able to do the same on prod.
 - Admin Portal/User management - An application used to create teams, manage users, and applications within the identity dashboard. This page will serve as the single admin app for all of the Identity dashboard components.
 - Performance Dashboard - A collection of information scoped to selected audiences to allow application teams and VA employees with the ability to monitor the authentication performance and stability of their integration with Sign in Service.
 - Documentation Portal - A collection of pages and links to all of the documentation for Sign in Service and its supporting components.
 
Expanding into the management of more products. We need a solution which allows us to track and make change requests available to external teams.
Formalize our service offerings to encourage application teams to adopt our services over commercial offerings.
One thing that this completes is the current lack of an integration and documentation portal.

### UX Tasks
- [x] sync with John/Ian/ to find out which milestones are completed
   -  As of Oct 2 BDPR monitoring section is mostly setup (Ian), Teams page (Riley) and Client Config page (Afia) are being worked on
   -  Everything else is basically placeholder
- [ ] gain access to the completed sections (BLOCKED - FE/BE are currently making changes to the way sign in works)
   - note: there is a work around in current state, Oct 4, where you can add a cookie in browser
- [ ] get a decision on where ID Dash fits in with Product priorities and decide what is most beneficial to research with users
 - [ ] begin research planning, including brainstorming things like
    - is it better to have a single test or test sections that are ready? Focus test on only one section at a time, although some overlap across sections is likely
    - make Figma prototype ([or update current one](https://www.figma.com/file/rw8kJXf4VKliimoMpsEy4Q/Identity-Dashboard-(initial)?type=design&node-id=23-309&mode=design&t=WCt8xJgtaCfFs50d-0)?) vs using coded prototype?

#### Documentation
- Secondary research on similar type dashboards [mural link](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1698945644920/b3e505ca319cf9ede814eeb75826f363e0c2a651?sender=u4dc1c26b5a09e4d460e45806)

#### Acceptance Criteria
- [ ] Reviewed by UX Team
- [ ] Reviewed by PMs
- [ ] Documentation has been updated
- [ ] Put published research in drive

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by asg5704** [comment]
@claytonzook not sure if this should be closed or not since the dashboard will become dead in the water for the frontend.

**Comment by claytonzook** [comment]
Since we are not moving forward with FE work on this product for the foreseeable future, we'll close this ticket
