### ISSUE TITLE
AWS access for Steven Cruz [Platform DevOps]

### ISSUE THREAD

**Issue by stoiven** [department-of-veterans-affairs/va.gov-team#66557]
### COR Name

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### E-QIP Transmittal Date

- [ ] Check this box if you have an E-QIP transmittal date.

### Your Name

Steven Cruz

### Your Email

steven.cruz@oddball.io

### Team, Role, and Company of the target individual

Platform IST, DevOps Engineer, Oddball Inc

### Product Manager (PM) name and email

Nate Peterson, nate.peterson@adhocteam.us

### Product Owner (PO) name and email

Aparna Nittala, Aparna.Nittala@omb.eop.gov

### Desired AWS Access

`vsp-operations` permissions and access

### Access Expiration

Ongoing

### E-QIP Transmittal Confirmation

![Screen Shot 2023-10-05 at 6 51 09 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8263883/c21273c4-c0a8-46e0-9421-5e3ee1a75b68)

### Additional Notes

COR - Gang Wang `Gang.Wang@va.gov`

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [ ] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [x] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by ph-One** [comment]
Found on Platform Roster

**Comment by ph-One** [comment]
Approving, as this is non-production level access

**Comment by ph-One** [comment]
@BillChapmanUSDS AWS Access for Platform IST team member Steven Cruz

**Comment by BillChapmanUSDS** [comment]
After discussion with @ph-One this is a production request, they are a devops team member and that is the current justification. They already have lower environment access. Just waiting on EQIP verification.

**Comment by JonathanKamensUSDS** [comment]
This is approved once confirmation of eQIP transmittal is received. No need to circle back with OCTODE when that happens.

**Comment by ph-One** [comment]
Closing. This was completed last week
