### ISSUE TITLE
SOCKS access for Joel Njanga

### ISSUE THREAD

**Issue by barbarello** [department-of-veterans-affairs/va.gov-team#66565]
### Your Name

Joel Njanga

### Your Email

joel.njanga@adhocteam.us

### Your Role and Team

DevOps Engineer ,  Infrastructure Services Team

### Product Manager (PM) name and email

Nate Peterson, nate.peterson@adhocteam.us

### Product Owner (PO) name and email

Aparna.Nittala , Aparna.Nittala@omb.eop.gov

### Access Type Requesting

platform

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC5hAOs78yfzmQGvdI4HsiiImBA3nATPQ5WBGFQ8NasEPUBcTjSTsLcJGteleCXfA02oURYCgqg8doaHSquzr6rnUYwv/HBl7EFeQx95wi5uzDFBR1Eb7WDG7bdssFeiZeDM8tVFt51Zjtkj96PJgOFQKGPpu3Oq+FK0UV4u9Bs2wlP1uwXOf6lSYJExQDkTqOd0XFd8Sa8bPIeP2puXvuP8ch8FWbERfiRJiS6GRWfRnV5TZybHms1OdhqpSSqc62+s4WSvKDAJK6pxCqS6G7XKd0ws6R3HFosOU5G3mrxoIhA5cy9J9p2FasFBJo0VQJyIUqngPheVyJRZK3sRpJXmFPi+tmOKA32WWewaU0iYxx8o1OglOwq2cGWHwRm8EdsExx4alCSwaL7zrnQcQ2cgDUnWekWEanOPjHWsp2OSF7z/HBJir8Mo0VTZPBDZzNw47OMuNyMs0EGYaP7Mo0brKnxURMBXmOezS2y8zSKGlhKKDUQAr3Hvkw57hkyJgU= joelnjanga@Joels-MBP

### E-QIP Transmittal Confirmation

<img width="787" alt="Screenshot 2023-09-11 at 12 07 03 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/5070341/f3319fde-2c53-4697-9c40-26c0d2fe5254">

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by ph-One** [comment]
Completed
