### ISSUE TITLE
Accessibility Testing for Sitewide CAIA, Medical Device Reordering Tool, new CPAP supplies static entry page

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#66564]
### Product information

- [X] Team name, product name, and feature name have been added to the title of this issue.
- [X] Team label, product label and feature label (if applicable) have been added to this issue.

### Who completed the use of color and color contrast test?

@eli-oat 

### Use of color and color contrast checks

- [x] All text of 20px or smaller has a 4.5:1 contrast ratio to its background (or better)
- [x] All text of 20px or larger has a 3:1 contrast ratio to its background (or better)
- [x] Non-text elements have a 3:1  contrast ratio to their background and to neighboring elements (or better)
- [x] Color is not the only way to distinguish links from other text (eg. links are underlined)
- [x] Any charts, maps, infographics, and tables convey all information without only relying on color
- [x] Content does not refer to color, especially when providing user instructions (eg. "Click the blue button")

### How did color testing go?

This is a Drupal page using a set template, so color contrast is controlled and consistent across pages.

### Who completed the axe scans?

@eli-oat 

### axe checks

- [x] Each page has been scanned using axe (results shared below)
- [ ] axe is integrated into your end-to-end testing

### axe DevTools scan results

<img width="548" alt="Screenshot 2023-09-28 at 3 28 01 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/3342274/491c9661-33b6-49fb-8484-e2a7ec09f686">

NOTE: I'd normally provide an export, not just a screenshot, but because I am working from within Citrix I didn't wanna have to exfiltrate the axe scan report from the VA network. 

### How did axe testing go?

No issues found. 

### Who completed the content zoom and reflow test?

@eli-oat 

### Content zoom and reflow checks

- [x] All page elements are readable and usable at 200% zoom
- [x] All page elements are readable and usable at 300% zoom
- [x] All page elements are readable and usable at 400% zoom

### How did content zoom and reflow testing go?

Using Google Chrome, through Citrix running within a MacBook Pro with a `3024×1964` display, reflow and zoom testing went well. Because this is a fairly standard Drupal page I wasn't worried about reflow, but, given that this was tested through Citrix on a hi-dpi screen, I'd note that this may act differently on lower-def screens. 

### Who completed the keyboard navigation test?

@eli-oat 

### Keyboard navigation checks

- [x] Each link, button, form input, checkbox, radio button, select menu, and custom element can receive keyboard focus
- [x] Each link, button, form input, checkbox, radio button, select menu, and custom element responds to expected keys
- [x] All elements under focus have a visible focus indicator
- [x] The order of [Tab] stops made sense and was appropriate for completing tasks

### How did keyboard testing go?

Because time was limited, I didn't go deep, but, a cursory test found no issues. The page is relatively simple, so I think we're good to proceed.

**Comment by eli-oat** [comment]
@briandeconinck I'm the tester for this. 

A few quick notes, we had limited time to test this, and it was my first time testing through Citrix, so I wasn't as cozy as I'd normally be.
