### ISSUE TITLE
IPP Pilot - Create a list of analytics to track

### ISSUE THREAD

**Issue by skirkman16** [department-of-veterans-affairs/va.gov-team#66569]
Do we need to set analytics for the PIlot?

**Comment by rdvyas** [comment]
May not be the right place, but found this documentation on VA.gov site about setting up Google Analytics:

https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/getting-started-with-platform-analytics-insights

**Comment by lmorris3** [comment]
@skirkman16 wondering what the goal is for this story? I would think we could include analytics in some of the other stories, rather than dedicate a story to creating a list of metrics. Thoughts?

**Comment by SophiaPhilipMO** [comment]
@lmorris3 the context of this ticket would be dev identifying feasible places to collect analytics during the studies. This could be discussed during the next dev/design sync

**Comment by skirkman16** [comment]
Come up with what we are using analytics for and what behaviors we want to identify and track

**Comment by lmorris3** [comment]
done.
