### ISSUE TITLE
Midpoint Review - Design Feedback - Form 20-10206 FOIA / PA Request

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#66575]
## VFS actions
- [x] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [x] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- If you can, implement the "[Know your information is updated](https://design.va.gov/patterns/help-users-to/know-how-their-information-is-updated)" pattern.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

-

**Comment by rachelshearerux** [comment]
Based on this [platform guidance](https://design.va.gov/patterns/help-users-to/know-how-their-information-is-updated#when-not-to-use-this-pattern), we did not incorporate this feedback in the final design because this form will not update their VA.gov profile.
