### ISSUE TITLE
BE | Lighthouse | Code-owner Assignments

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#66570]
## Background
I'd like to remove this line in the `CODEOWNERS` file...

```
lib/lighthouse @department-of-veterans-affairs/lighthouse-banana-peels
```

... and replace it with more granular assignments:
```
lib/lighthouse/auth @department-of-veterans-affairs/vfs-authenticated-experience-backend
lib/lighthouse/benefits_claims @department-of-veterans-affairs/benefits-management-tools-be
lib/lighthouse/benefits_documents @department-of-veterans-affairs/benefits-management-tools-be
lib/lighthouse/benefits_reference_data
lib/lighthouse/charon <--
lib/lighthouse/direct_deposit @department-of-veterans-affairs/vfs-authenticated-experience-backend
lib/lighthouse/facilities <--
lib/lighthouse/letters_generator @department-of-veterans-affairs/benefits-management-tools-be
lib/lighthouse/service_exception.rb @department-of-veterans-affairs/vfs-authenticated-experience-backend
lib/lighthouse/veteran_verification @department-of-veterans-affairs/dbex-trex @department-of-veterans-affairs/benefits-management-tools-be 
lib/lighthouse/veterans_health <--
```

Please assign your team to the appropriate directories.  

@jerekshoe and @aurora-a-k-a-lightning Please add your team to `direct_deposit` and `service_exception.rb`.

Also, feel free to add  `vfs-authenticated-experience-backend` in cases where you want the team as a backup reviewer. 

Once everything has been assigned, I'll make the changes and include everyone on the PR.

**Comment by jerekshoe** [comment]
@tpharrison I added `<--` to the ones I don't think belong to any of the teams included on this ticket

**Comment by jerekshoe** [comment]
@tpharrison I think it's fine to leave my team off of `direct-deposit` since I'm in your GH team already
