### ISSUE TITLE
Midpoint Review - IA Feedback - Form 20-10206 FOIA / PA Request

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#66583]
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- This is a complex form made simpler. Nice work.
- I second the two user flow issues @briandeconinck identified on the intro screen (how to get people down the page to the "start" button) and the identity verification page (routing folks to the PDF form if they can't/don't wish to do the identify verification).

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- **Consider:** If users leave the form flow to verify their identity, will they eventually be sent back to the form? The ID verification process seems like a pretty complex flow **and** if using the referring link to route folks back to the form is possible, that would be a big win.
- **Consider:** On the [disability exam details](https://www.sketch.com/s/314e6dbf-5b4a-422d-beb1-0ad599fc3af1/a/uuid/5BEEEEBF-6ECD-427A-83EB-68AFAEECC0E9) question, would users be able to enter only a year and not a month? Most folks might remember the year but not the month. If possible, consider indicating that folks can fill out MM/YYYY or just YYYY.

**Comment by rachelshearerux** [comment]
> Consider: If users leave the form flow to verify their identity, will they eventually be sent back to the form? The ID verification process seems like a pretty complex flow and if using the referring link to route folks back to the form is possible, that would be a big win.
- We've incorporated this feedback in the final flow. Users will be redirected with a referral link that anchors folks to the H2 "Start your form" once they've finished the verification process.

> Consider: On the disability exam details question, would users be able to enter only a year and not a month? Most folks might remember the year but not the month. If possible, consider indicating that folks can fill out MM/YYYY or just YYYY.
- Unfortunately the component didn't support partial validation, so we've made the dates entirely optional and new hint-text now tells them "It's OK to estimate"
