### ISSUE TITLE
AWS access for Herbert Joseph

### ISSUE THREAD

**Issue by IdeaTrail** [department-of-veterans-affairs/va.gov-team#66585]
### COR Name

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative Name

Other - please specify in 'Additional Notes'

### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Herbert Joseph

### Your Email

herbert.joseph@va.gov

### Team, Role, and Company of the target individual

Developer

### Product Manager (PM) name and email

Greg.kirk@va.gov

### Product Owner (PO) name and email

sean.good@va.gov

### Desired AWS Access

Requesting the SSMApplicationLowerEnvironmentAccess policy, and to be added to the existing IAM group dsva-vfs-developers

### Access Expiration

04/15/2023

### E-QIP Transmittal Confirmation

<img width="951" alt="HerbertJosephEquipConfirmation" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/130765376/e68ad0fd-d260-4e16-9ad1-5731ad42ddb3">

### Additional Notes

COR Sean Good
Vendor onboarding representative: Raquel Robertson

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by ph-One** [comment]
Found on VFS Roster

**Comment by ph-One** [comment]
Approving. Non-production access.

**Comment by ph-One** [comment]
Closing. User has been added to AWS and contacted with follow-on details
