### ISSUE TITLE
AWS access for Richard Davis

### ISSUE THREAD

**Issue by dickdavis** [department-of-veterans-affairs/va.gov-team#66590]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### E-QIP Transmittal Date

- [x] Check this box if you have an E-QIP transmittal date.

### Your Name

Richard Davis

### Your Email

richard.davis@bylight.com

### Team, Role, and Company of the target individual

VSP Identity, By Light Professional IT Services Inc

### Product Manager (PM) name and email

Mike King

### Product Owner (PO) name and email

Tom Black

### Desired AWS Access

I need access as part of my responsibilities on the VSP Identity team. Please mirror my permissions to that of other team members (Riley Anderson, John Bramley, Trevor Brosaw).

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

![Screenshot 2023-09-27 at 4 03 36 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/10838930/f60f426c-a046-41dc-ba7d-4ff56454930d)

### Additional Notes

I need this because it is required to access AWS in order to manage services we are rolling out.

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by hgbarreto** [comment]
User confirmed to be in [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)

**Comment by hgbarreto** [comment]
Approval needed: @department-of-veterans-affairs/operations-aws-approvers 
`group_memberships    = ["adhoc-vetsgov-ssm-prod", "dsva-vfs-developers", "force-MFA", "vsp-identity"]`

**Comment by hgbarreto** [comment]
Continue to wait for approval
@department-of-veterans-affairs/operations-aws-approvers

**Comment by BillChapmanUSDS** [comment]
Hi @dickdavis  as part of our current process to limit production access in the future by removing obstacles that require it in the first place we are asking that anyone requesting production access provides a specific example of a task they need that access for. If you provide a specific example we are giving 6 months access without any judgement of the reason but it should be specific,  like "service A often fails and we need to do this exact thing to track it down".  Thanks.  Adding an example and the access-justification-example-provided tag is sufficient to gain approval.

**Comment by JonathanKamensDVA** [comment]
@dickdavis ping

**Comment by dickdavis** [comment]
I haven't ran into a need for AWS access yet to fulfill my responsibilities, so I'll wait for such an instance to occur before requesting access again. I'll close this request for now and open a new request later if needed.
