### ISSUE TITLE
Design Intent - Accessibility Feedback - MHV, Next of Kin & Emergency Contact

### ISSUE THREAD

**Issue by briandeconinck** [department-of-veterans-affairs/va.gov-team#66591]
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- This all looks great!
- Not an accessibility issue, but note that the additional info component at the top of the Contact Info page contains information on how VA uses that info. Since this is a new use case, that component will need to be updated to match. Just don't want it to get lost in the shuffle!

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- **Should:** Reiterating Matt's feedback in #66561, I think the headings on the new fields might be a little long for screen reader users to parse when navigating by heading, especially in comparison to what's already on the page. Would be great to trim them a bit.

**Comment by mtcA6** [comment]
this launched
