### ISSUE TITLE
Vets-api terminal access for Adrian Rollett

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#66592]
### Your Name

Adrian Rollett

### Your GitHub handle (terminal access is managed through GitHub)

@acrollet

### Your dsvagovcloud AWS user name (if applicable)

Adrian.Rollett

### Team, Role, and Company of the target individual

Health Care Applications, Engineer, OCTO

### Product Manager (PM) name and email

Alexanderson, Lauren <Lauren.Alexanderson@va.gov>

### Product Owner (PO) name and email

Alexanderson, Lauren <Lauren.Alexanderson@va.gov>

### COR Name (leave "None" if you listed an AWS user name above)

None

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

None

### Please confirm if you are on the VFS Team Roster or Platform Team Roster

- [X] [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Please confirm E-QIP Transmittal/Adjudication. This could be a screenshot of your Transmittal/Adjudication email, a link to another request where you've submitted this proof (i.e. AWS/SOCKS), etc.

- [X] I have attached proof that I have either transmitted my E-QIP survey or previously received a favorable decision (by including in "Additional Notes" section below)

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [ ] production (if requesting, justify prod access in 'Additional Notes' section)

### Additional Notes

I need this access for lower environment debugging. Not able to find the e-qip transmittal but I have this proof of clearance:

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/101649/1d22d740-a218-48c7-aff3-8cf17962550a)

### Additional resources for Support Engineer

- [ ] For users on a VFS team but not in the VFS Team Roster, they must start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] Instructions for handling requests [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access) - Support Only

**Comment by IsaiahMW1** [comment]
@acrollet You’ve been granted access to the dev, staging, and sandbox environments.
