### ISSUE TITLE
[FE] Add refresh timer to upcoming appointments call

### ISSUE THREAD

**Issue by wullaski** [department-of-veterans-affairs/va.gov-team#66619]
Implement needsRefresh for the useGetUpcomingAppointments hook so it doesn't call the endpoint every time the view loads.

**Comment by loripusey** [comment]
@wullaski re-evaluate if we need this ticket or something else
cc: @brianseek

**Comment by brianseek** [comment]
This work is complete but will likely roll over to make related tests have better coverage and to get a good review.

**Comment by brianseek** [comment]
1 point left of effort on this one.

**Comment by brianseek** [comment]
@wullaski moving this to closed since there is nothing for others to validate on the feature branch
