### ISSUE TITLE
Access for Karl Brown

### ISSUE THREAD

**Issue by karlbrown-va** [department-of-veterans-affairs/va.gov-team#6661]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Courtney Bethea @CourtneyBethea
- Please provide your name.
   > Karl Brown
- Please provide the name of your team, your role on that team, and the name of the company you work for.
  > Team: @thoughtworks 
  > Role: Technical Principal
  > Company: ThoughtWorks
  > I am part of a team at ThoughtWorks that is working with the CTO's office to update va.gov/scorecard. I have a PIV card that I was granted in January 2020. I am requesting access to the SOCKS proxy and Jenkins / Prometheus / Grafana so we can 
  > - Modify / update Jenkins job configs
  > - Kick off Jenkins jobs
  > - Review Prometheus data, some of which is imported into the scorecard
  > - Review Grafana data for the scorecard
  
  > If you have any questions or concerns please let me know, or reach out on slack on #va-scorecard-refresh
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Internal%20Tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC50I2Wgtc1Y2HYNbMTzrgVieC1HhQO7Ss/OQsoyBI/YiE8UXPTmqaqFt1peWHXM6wZg7x/IP9O7e0C6wNrpmX5oKexYajHpulX0np7w0+Kci6XPaZSxudZEu1rGSYMUTpz2w4LnzxzL4oFehJDyend2O5GTtyKhLKfyHFbVudGKBxPn65fk1s/RaNL3/T1EI6ZN9kjjyolenZIMoEQo23ROEWqe9rwEBF7c5Pi7cuuQwXeaEoCj1QHiPo7Y/P4iSLt6f6uZRbb6F37t3uSo3iTACyJjBUjIun94OKKdrezlLHZxqPVGFan+CzU1Hl9BkXRR2juPjlD/RhZRovA/B2B karl.brown1@va.gov
```

- [Grant AWS Console access?]
  > NO
  > At least for now we don't think we need this.

**Comment by karlbrown-va** [comment]
@department-of-veterans-affairs/vsp-operations please review

**Comment by jbritt1** [comment]
SOCKS access granted. @digitaldrk, please continue with the guide for establishing a connection to SOCKS proxy.
