### ISSUE TITLE
[BUG] Fix content for need help on .../complete pages in check in 

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#66618]
## Description 

The travel Yes and No pages need help content looked good. 

But, need to check the Need Help content on the confirmation pages. E.g., https://staging.va.gov/health-care/appointment-check-in/complete/38999-530

All content AFTER the sentence that finishes with "... emergency room." should be removed.

Example (just looking at the need help content in this sketch page) - https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/bLomb40

Screenshot from stg: 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ2Z3IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--aafd6f0c16fd5da30c2456f67a102966ddc5f546/Screenshot%202023-09-28%20at%203.21.29%20PM.png)

## Tasks

- [ ] Fix bug associated with incorrect content in Need Help on confirmation pages. Should include/check all variations of .../complete page. E.g., completed travel, couldn't file travel, couldn't check in, etc.

**Comment by benbrasso-agile6** [comment]
## Description 

The travel Yes and No pages need help content looked good. 

But, need to check the Need Help content on the confirmation pages. E.g., https://staging.va.gov/health-care/appointment-check-in/complete/38999-530

All content AFTER the sentence that finishes with "... emergency room." should be removed.

Example (just looking at the need help content in this sketch page) - https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/bLomb40

Screenshot from stg: 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ2Z3IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--aafd6f0c16fd5da30c2456f67a102966ddc5f546/Screenshot%202023-09-28%20at%203.21.29%20PM.png)

## Tasks

- [ ] Fix bug associated with incorrect content in Need Help on confirmation pages. Should include/check all variations of .../complete page. E.g., completed travel, couldn't file travel, couldn't check in, etc.

**Comment by benbrasso-agile6** [comment]
@lee-delarm6 same thing here, any screenshot from local of new update?

**Comment by lee-delarm6** [comment]
<img width="1034" alt="Screenshot 2023-10-17 at 2 01 15 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/135059743/9629da3d-9091-461f-815f-371b0015acf8">

**Comment by benbrasso-agile6** [comment]
@lee-delarm6 doesn't look correct, please take a look at the content in this file - https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/bLomb40

You sure you grabbed a screenshot from the correct page?

**Comment by lee-delarm6** [comment]
I don't have the travel enabled on this one, will take a different screenshot

**Comment by lee-delarm6** [comment]
<img width="455" alt="Screenshot 2023-10-17 at 4 05 17 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/135059743/6f757ef4-9966-4de2-9b58-136819a07ab0">

@benbrasso-agile6 Sorry, here is the travel help content with the update (the update was chopping off everything past "emergency room." last line)

**Comment by benbrasso-agile6** [comment]
np LGTM
