### ISSUE TITLE
QA Standards - Health Modernization (vfs-mhv-medical-records) - Medical Records

### ISSUE THREAD

**Issue by it-harrison** [department-of-veterans-affairs/va.gov-team#66622]
#### VFS team name
Health Modernization (vfs-mhv-medical-records)

#### VFS product name
Medical Records

#### VFS feature name
Medical Records (Comprehensive Domains)
#### Point of Contact/Reviewers
@it-harrison - Ian Harrison - QA

---
#### Regression Test Plan 
- [x] Standard has been met
- [ ] Standard has not been met
#### Test Plan
- [x] Standard has been met
- [ ] Standard has not been met
#### Traceability Reports 
- [x] Standard has been met
- [ ] Standard has not been met
#### E2E Test Participation
- [x] Standard has been met
- [ ] Standard has not been met
#### Unit Test Coverage
- Lines %: 74.72

- Functions %: 77.01

- Statements %: 74.37

- Branches %: 52.20

- [x] Standard has been met
- [ ] Standard has not been met
##### Explanation of failure to meet standard (if applicable): #####

All categories must have greater than or equal to 75% coverage.

---
### VFS Guidance

- Close the ticket when your Product Owner determines that you have sufficiently met the QA Standards.
- If your team has additional questions or needs Platform help validating the issue, please comment on the ticket

### Platform directions
- Update "Issue Title" to be of the form "QA Standards - VFS Team - VFS Product"
- Add the VFS team, product name, and feature name
- Add your name, practice area, and GH handle under Point of Contact/Reviewers
- Complete the QA Standards section, making sure to include an "Explanation of failure to meet standard" for every Standard the product does not meet.
- Link to the Collaboration Cycle Request epic
- Add epic's milestone
- Add assignees: 
  - VFS PM
  - Yourself (optional)
- Add labels:
  - VFS team label
  - VFS product label
  - QA-standards label
  - launch-blocking label if the product has failed to meet a required QA Standard

**Comment by bryan-riley-va** [comment]
Now over 87%
