### ISSUE TITLE
Backend Orientation - October 2023

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#66634]
## User Story
As a Platform team member supporting Platform Orientation, I want to host, record, transcribe and share the Backend Orientation session so that VFS team members are able to be easily oriented to the VA.gov Platform. 

## Description
Platform is responsible for hosting the Platform Orientation sessions once every quarter. These sessions are recorded and shared on Platform Website.

The Backend Orientation for FY24-Q1 is October 4 at 4:00pm ET.

## Impacted Artifacts
[Orientation Host/Zoom Host Guidance](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2656731745/Orientation+Host+Zoom+Host+Guidance)

### Zoom host (Clint)
- [x] Ensure Zoom settings are set according to the guidance: [Orientation Host/Zoom Host Guidance](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2656731745/Orientation+Host+Zoom+Host+Guidance) / Before you start your session / Zoom settings
- [x] After the session has been hosted, forward the Zoom recording to the Instructor/Session host
### Instructor/ Session host (Lindsey)
- [x] Review the guidance in the [Orientation Host/Zoom Host Guidance](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2656731745/Orientation+Host+Zoom+Host+Guidance) for During your orientation session
- [x] Host the orientation session as scheduled
### All the other stuff (Rebecca)
- [x] Download mp4 and vtt files from Zoom recording
- [x] Clean up the transcript
- [x] Upload recording and transcript to YouTube
- [x] Change visibility of previous recording to Private (if applicable)
- [x] Update video link on Platform Website

## Acceptance Criteria
- [x] The live Accessibility Orientation for the quarter has taken place
- [x] VFS team members are able to view the latest recording of the orientation session

**Comment by LindseySaari** [comment]
Orientation complete, but @rmtolmach  will be updating the transcript and uploading once complete

**Comment by rmtolmach** [comment]
✅ done! new video is linked here: https://vfs.atlassian.net/wiki/spaces/GS/pages/2133393543/Orientation+Sessions and will be published to the platform website on the 10th.
