### ISSUE TITLE
GIDS: Reduce the time required for institutions search by ID endpoint

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#6664]
As a developer, improve the performance of the institutions search by ID API Endpoint, so that appropriate improvements can be made to improve performance and stability of the application.

## Acceptance Criteria
1. The time required for institutions search by ID endpoint has been reduced. 

## Supporting Artifacts
1. Proposed solution can be found in the comments of the related research story here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/6281

**Comment by ksantiagomorgan6** [comment]
Story Changes
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/604

DB Migration 
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/603

**Comment by sonntag-adam** [comment]
Testing passes QA.

**Comment by sonntag-adam** [comment]
In staging. Closing story.
