### ISSUE TITLE
[Other - Accessibility] Unnecessary information announced by screen readers. (00.00.1)

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#66642]
#### VFS team name
MHV

#### VFS product name
MHV Medical Records

#### VFS feature name
Allergies

#### Point of Contact/Reviewers
Brian DeConinck - @briandeconinck - Accessibility

*For more information on how to interpret this ticket, please refer to the [Anatomy of a Staging Review issue ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Anatomy-of-a-Staging-Review-Issue-ticket.2060320997.html) guidance on Platform Website.

---

### Platform Issue
No VA.gov Experience Standard for the issue found.

### Issue Details
On /medical-records/allergies, each allergy link has an `aria-label` that includes the date entered: `[allergen] on [date]`. Associating a date with the visible link text using an `aria-label` is a really good technique when you have multiple instances of the same item, like multiple doses of an immunization that took place on different dates. But it seems unlikely that someone is going to have multiple instances of the same allergy, and the date is reflective of something administrative (when it was logged) rather than something relevant to the user (when something occurred). I think most screen reader users are going to be able to still navigate through the screens effectively, but the dates in the `aria-label` may cause some confusion.

### Link, screenshot or steps to recreate
Example code:
```
<a class="vads-u-margin--0" 
     aria-label="ATORVASTATIN/EZETIMIBE on September 13, 2023" 
     href="/my-health/medical-records/allergies/3214">
          ATORVASTATIN/EZETIMIBE
</a>
```

### VA.gov Experience Standard
[Category Number 00, Issue Number 00](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

### Platform Recommendation
Unless there's actual patient data that would suggest the need to differentiate between multiple instances of an allergy, I think you can remove the `aria-label` entirely here and just have plain link text. This date differentiator is still likely to be valuable in other medical records domains, but it's not useful here.

---

### VFS Guidance

- Close the ticket when the issue has been resolved or validated by your Product Owner
- If your team has additional questions or needs Platform help validating the issue, please comment on the ticket
- Some feedback provided may be out of scope for your iteration of the product, however, Platform's OCTO leadership has stated that all identified issues need to be documented and it is still your responsibility to resolve the issue.
- If you do not believe that this Staging Review issue ticket is the responsibility of your team, comment below providing an explanation and who you believe is responsible. Please tag the Point of Contact/Reviewers. Governance team will research and will follow up.

**Comment by BobbyBaileyRB** [comment]
There's a possibility that allergy records might have repeating instances, that is why we are associating a date with the visible link text using an aria-label.

I would like to confirm this with @coultonbunney-usds before closing this ticket.

**Comment by bryan-riley-va** [comment]
Can be closed/verified by Bobby
