### ISSUE TITLE
MHV Secure Messaging on VA.gov - Content Dashboard Update

### ISSUE THREAD

**Issue by AnneCostello** [department-of-veterans-affairs/va.gov-team#66651]
# Request an Edge Case KPI Dashboard

## What this form is for

Use this ticket template to request a new edge case KPI dashboard on Domo for your product. Edge case dashboards are for products that fall outside of the scope of our standardized KPI dashboards (Forms, Content, and Search).

If you are unsure what type of dashboard your product qualifies for, please check the [Eligibility Dashboard](https://va-gov.domo.com/page/1550814739) on Domo.

### Expected delivery timelines

The Analytics team will notify you once this ticket has been pulled into a sprint. Please note that these dashboards will require additional data and design discovery and will take additional time to deliver. You can also reach out for updates on this ticket.

## Instructions for the VFS team

In order to pull the correct data for your product, we need your help to define what pages and events to include, in addition to basic product info. For edge cases, we also ask for product outlines or other resources that will help us understand success for your product and define metrics: 

- [x] Make a copy of [this Google Sheet](https://docs.google.com/spreadsheets/d/1TSynjEUrOrm_HfLxb2NAPDXxnn7wyy1bSEb2RruC67Q/edit#gid=0) (or download Excel version).
  - [x] Fill out product information basics.
  - [ ] If a part of your product involves any sort of linear process/funnel for which you want to be able to measure conversions, please include it in the "Forms" tab of the template.
  - [x] All other pages associated with your product for which you'd want to track visits and engagement should be added to the "Content" tab.
- [x] Link to your completed spreadsheet here: attached directly
[KPI Dashboard Product Details - MHV Secure Messages on VA.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/12769916/KPI.Dashboard.Product.Details.-.MHV.Secure.Messages.on.VA.xlsx)
- [x] Check your sharing settings to make sure the Analytics team will be able to access it.
- [x] Answer the questions in the **VFS-provided information** section below.
- [x] Add links to the **VFS-provided information** section below.
- [x] Add your team label to this ticket to follow its progress.

### Product questions
Help us understand your product better by answering the following questions:

1. **What does your team consider a completed task?** A read message, a submitted message.
2. **Who is your product's main user base?** Veterans
3. **Why does your product require an edge case?** My HealtheVet is classified as an edge case on the VA.gov KPI Dashboard Eligibility page.
4. **Does this product currently have a Domo dashboard?** No

### Product resources
Add links to product outlines, feature information, or any other resources you think would help us better understand your product and OKRs below. Feel free to also type background information into this section directly. The more context you're able to provide, the fewer questions we'll need to ask you before getting started!

- [Secure Messaging Product Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/secure-messaging/product/VA.gov%20Product%20Guide_Secure%20Messaging%20on%20VAgov%5B73%5D%20(1).docx)
- [Data Collection and Analysis Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/secure-messaging/analytics/data-collection-and-analysis.md)

**Additional info**

- Please use the [KPI Framework](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/Analytics%20Playbook/va-gov-platform-analytics-kpi-framework.pdf) for more information on the metrics used in the Standard KPI dashboards.
- For additional info, read through the [How to Request a KPI Dashboard Documentation](https://depo-platform-documentation.scrol

lhelp.site/analytics-monitoring/Analytics-customer-support-guidelines.1586823275.html#Analyticscustomersupportguidelines-4.RequestaKPIDashboardinDomo).
- If you do not have Domo access, please [request it here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+access-request&template=analytics-request-google-analytics-domo-access.md&title=Request+access+to+Google+Analytics+and%2For+Domo).

**Comment by michelle-dooley** [comment]
The [Content Dashboard](https://va-gov.domo.com/page/426422632) filtered to your pages will provide this information. We will update the query to ensure those pages/events will be included.

**Comment by ChristineYoungZA** [comment]
Hello @AnneCostello is it possible to get a complete list of the URLs for the content dashboard including the ones provided above?
