### ISSUE TITLE
Implement CAIA changes on Burial Review Page and Widget

### ISSUE THREAD

**Issue by sortizsh** [department-of-veterans-affairs/va.gov-team#66666]
CAIA changes are located within the Sketch files for the Review pages and Widget: 
Review Page (authenticated)https://www.sketch.com/s/12d1e8d4-7495-44b9-a16d-ab27be429ff6/a/4oEQqQJ
Review Page (no draft claim)https://www.sketch.com/s/12d1e8d4-7495-44b9-a16d-ab27be429ff6/a/elb5Y52
Widget How to apply (authenticated)https://www.sketch.com/s/12d1e8d4-7495-44b9-a16d-ab27be429ff6/a/DEVOlOk
Widget How to apply (unauthenticated)https://www.sketch.com/s/12d1e8d4-7495-44b9-a16d-ab27be429ff6/a/mPM2J2V

Original ticketed work: 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/63626

Please have Fiorella and Laura sign off

**Comment by steele-lm** [comment]
Closing. Covered in #67566
