### ISSUE TITLE
GIDS: Query optimization in institution_builder

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#6666]
As a developer, I need to improve the performance of the institution_builder queries in order to enhance the performance and stability of the application.

## Acceptance Criteria:
1. Institution_builder queries have been optimized. 

## Supporting Artifacts:
1. Research story to inform this story can be found here https://github.com/department-of-veterans-affairs/va.gov-team/issues/6293

**Comment by delli-gatti-michael** [comment]
PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/605

**Comment by delli-gatti-michael** [comment]
local testing complete

**Comment by delli-gatti-michael** [comment]
Changes are now live in staging. Closing this issue
