### ISSUE TITLE
[BE] SPIKE: Plan Implementation to Integrate with MAP

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#66679]
## Background
We need to plan the Implementation to Integrate with MAP - the intent of this ticket it to have enough figured out so that we can complete the backend work to integration with MAP & fetch upcoming appointments and handle any errors

## Tasks
- Create sequence diagrams 
- Create implementation tickets

**Comment by lee-delarm6** [comment]
- Generate RSA key pair for MAP using vets-api, new function
- Register for `on-behalf-of` functionality in mobile-oauth-sts (MAP?)
  - Requires 3 items:
    - `authorized_grant_types` should contain `client_credentials`
    - `client_authentication_methods` should contain `private_key_jwt`
    - `jwt_public_key` set to PEM formatted public key of the RSA key/pair
    - Example: ```json
      {
        "client_id": "1234",
        "client_name": "Client",
        "authorized_grant_types": [
        "client_credentials"
        ],
        "client_authentication_methods": [
        "private_key_jwt"
        ],
        "jwt_public_key": ""
        }
      ```
- Create request for `on-behalf-of` token request using our JWT key, this will be another vets-api function (JWT must be signed by key provided at registration)
- JWT Generation steps listed in doc `mobile-oauth-on-behalf-of.md`
- Create service call from `vets-api` to `/token` endpoint `https://veteran.apps.va.gov/sts/oauth/v1/token`, refer to doc above for exact request contents
- Handle the response, doing any data transformation necessary and send to front-end (or consumer of data)

**Comment by lee-delarm6** [comment]
Tickets are:
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/67717
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/67716
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/67715
