### ISSUE TITLE
REMINDER: Review, Update, Fix, and Log Offending Cypress Tests

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#66680]
## Tasks
- Check https://depo-platform-documentation.scrollhelp.site/developer-docs/currently-disallowed-unit-test-specs-on-va-gov
- Review, Update, Fix, and Log Offending Tests
- Log any action taken in this internal sheet https://docs.google.com/spreadsheets/d/1tqsbBonIbSSq3enPQcd-yg0KSzSBp38TRD3D_tKq3qU/edit#gid=0

**Comment by brianseek** [comment]
cleaned up two flaky tests. Updated sheet but had issues with the script that removes tests from the bad list. Here is the prod support ticket: https://dsva.slack.com/archives/CBU0KDSB1/p1698419839262219

Should get cleared up over night tonight 10/30

**Comment by loripusey** [comment]
@brianseek @wullaski now that we have been using this ticket for a while, do we think that it is still a 3 pointer?
