### ISSUE TITLE
[Terraform] Ignore IAM User Tags for AWS Access Keys

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#66685]
When adding a description to an AWS Access Key, it's stored as a tag on the AWS user. Terraform wants to remove these, and it gets annoying. These types of tags need to be ignored. These keys have a known prefix, which should help make it easier to ignore, https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_identifiers.html#identifiers-unique-ids

## Notes

- https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf
- github.com/department-of-veterans-affairs/terraform-aws-vsp-iam-user is the module

---

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdmIxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ac5c5f5e61471ffbd4c50cc37681ba39876ae872/image.png)

---

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdXIxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--22c8857e1039965b326129c506ea5f3a6e8c0c08/image.png)

**Comment by npeterson54** [comment]
Rolling over into next sprint due to some unexpected PTO and a large # of support requests/cert renewals
