### ISSUE TITLE
Update YR FE implementation with new design spec

### ISSUE THREAD

**Issue by kelsonic** [department-of-veterans-affairs/va.gov-team#6668]
# Description

The design spec has changed recently and we should update `vets-website` to reflect those changes.

## Acceptance Criteria

- [x] Implement updated design spec https://vsateams.invisionapp.com/share/P4W04QPWHTK#/screens
- [x] Investigate and drop a comment here: vets-api, number of students and contribution amount not correctly being retrieved from GIDS (other query params seem to be working)

**Comment by MickinSahni** [comment]
2020-03-16 PW Standup
* Considering planned for Sprint 17
* PR opening today

**Comment by MickinSahni** [comment]
2020-03-18 PW Standup
* Yesterday: have YR data in dev now
* Today+: update design

**Comment by MickinSahni** [comment]
2020-03-20 PW Standup
- PR opened this morning  - https://github.com/department-of-veterans-affairs/vets-website/pull/11956
- Follow-up stuff
  - GIDS endpoint doesn't have per page, fixed at 30 instead of 10 <-- new ticket for sprint 18
  - vets-api, number of students and contribution amount not correctly being retrieved from GIDS (other query params seem to be working) <-- not a new ticket
  - country dropdown design, not sure what unique ids are for non-US countries. complication-don't have access to GIDS in prod <-- new ticket for sprint 18

**Comment by kelsonic** [comment]
Fixed: `vets-api, number of students and contribution amount not correctly being retrieved from GIDS (other query params seem to be working)`, query params being sent to `vets-api` were camelcase instead of snake case.

**Comment by kelsonic** [comment]
PR is up to fix the `per_page` pagination functionality on the new GIDS endpoint! https://github.com/department-of-veterans-affairs/gibct-data-service/pull/623

Thank you @jholton! 🎉

**Comment by MickinSahni** [comment]
> PR is up to fix the `per_page` pagination functionality on the new GIDS endpoint! [department-of-veterans-affairs/gibct-data-service#623](https://github.com/department-of-veterans-affairs/gibct-data-service/pull/623)

@kelsonic does that mean we can cross out the first item from this list?: https://github.com/department-of-veterans-affairs/va.gov-team/issues/6668#issuecomment-601772101

**Comment by kelsonic** [comment]
@MickinSahni It does! Just validated the PR since it's been merged and we now have `per_page` pagination functionality! 🎉

**Comment by MickinSahni** [comment]
2020-03-23 PW Standup
- @MickinSahni: create a ticket for country dropdown design, not sure what unique ids are for non-US countries. complication-don't have access to GIDS in prod
   - need YR program source CSV from GIDS prod likely from Matt Self (tag him in that)
   - thinking this new one will be part of Sprint 18 (once it's created)
