### ISSUE TITLE
[FE] SPIKE: Understand New Unit Tests Platform Standards

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#66681]
## Background
[slack thread](https://dsva.slack.com/archives/C03R5SBELQM/p1695907328789349)

## Tasks
- Understand New Unit Tests Platform Standards
- Document New Unit Tests Platform Standards
- Create a report of our current unit test coverage
- Determine if we need an ongoing ticket for unit tests to review & fix (similar to this [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/66680))

**Comment by brianseek** [comment]
New standards are pretty much the same as before but with a higher percentage of coverage required 

- QA5 will require 80% or higher unit test coverage (increased from 75%).
- QA5 will be enforced as a launch-blocking issue. Products that do not have 80% or higher unit test coverage will not be allowed to launch on VA.gov.

This doesn't change our current approach to unit testing. But we do need to keep our standards for testing up. We do need to take immediate action to get our functions up to at least 80% from the current 77.03%

Latest report for check-in: 
- 82.51% Statements 1227/1487
- 80.86% Branches 638/789
- 77.03% Functions 255/331
- 82.54% Lines 1206/1461

Full report attached: [coverage.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFVwQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--49f5da1677805af5e2bce0cc5b3405d5005388c6/coverage.zip)

I don't think an on-going ticket will be required.

Here is a ticket to increase coverage of functions:

**Comment by brianseek** [comment]
@loripusey here are the results of this spike ^ ^ one ticket that should get prioritized to get us into compliance in the Functions category

**Comment by loripusey** [comment]
I've added the FE ticket to the next sprinkles

**Comment by brianseek** [comment]
closing spike
