### ISSUE TITLE
Flipper UI access for Tyler Spangler

### ISSUE THREAD

**Issue by tyler-spangler6** [department-of-veterans-affairs/va.gov-team#66690]
### Your Name

Tyler Spangler

### Your GitHub handle (Flipper UI access is managed through GitHub)

tyler-spangler6

### Team, Role, and Company of the target individual

Contention Classification, Data Engineer, agile6

### Please confirm if you are on the VFS Team Roster, Platform Team Roster or are a Federal User

- [X] [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [X] Lesser Environments (Dev/Staging/Sandbox)
- [X] Production (if requesting, justify prod access below)

### Reason for Production Access (If requested)

Require access to edit feature flags for the contention classification team.

**Comment by bdech** [comment]
Found in VFS Roster

E-QIP [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65561)
