### ISSUE TITLE
Access for Filip Fafara

### ISSUE THREAD

**Issue by ffafara-tw** [department-of-veterans-affairs/va.gov-team#6670]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Courtney Bethea @CourtneyBethea
- Please provide your name.
   > Filip Fafara
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Team: @thoughtworks 
  > Role: Tech Lead
  > Company: ThoughtWorks
  > I am part of a team at ThoughtWorks that is working with the CTO's office to update va.gov/scorecard. I have a PIV card that I was granted in January 2020. I am requesting access to the SOCKS proxy and Jenkins / Prometheus / Grafana so we can 
  > - Modify / update Jenkins job configs
  > - Kick off Jenkins jobs
  > - Review Prometheus data, some of which is imported into the scorecard
  > - Review Grafana data for the scorecard
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Internal%20Tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDGVymy9Tl70BDvMcbRGTBCsxuHqk6I8NbuxlaOGQlfSAqnUiUCUtfesavrfCSGGcKvya8AdgLRn6RJOLUCwC/MV9Hjt+dPHVePiVVT7xvQi6DBCb2pl10dIsLSvo9DwEW3EIUV7hcNaTQ8tynHTy7+HkB/xcZrP4dB3LnULSl2htTsuPMHfIaBVtmgGV6zTeN1ylaHW10PWCYKVJzYJiZJduaXy+rCjGf64zAJB5GN1YKTLpdE0KrSgNFuXWnC0lyffBg/ylLkHqgeKPFV8ev881YNHng7NTqN6RBVNU4CF5jZoz5a1tl+jNqwGoqCmtjzbgsRP+nMrKGZiufzHgZK8Lfn0qK4VM70tM64WZcFFroSW4zqotCZAyfISfNYosDL0XuR+WdFg8yJJXS/4x2/ECEYQdASfiawQ4sJqWkMpnDfjEoHEk3HisOPIrIdK8U0HZrhQgljNyzlomlYvIOiWCoZlV9vzXSwpLEUjmhedCI8wKTstj06MbWIotcPAeyC1pG9lOIjZ1+CVprzSNHJ/H/izL2mZzEzgPYIKxM8nLR0qwAHtElTOjipKbQP2dn2cDrs0q5TmSCEw6gk3J6I+4Ha5zYpGFOFVBca/OpCpovXj68EzjakFef9dBIf6wdQRLXXEBJfdzFdtvE+wV1CDWsVzjUUDkmdqKSVtJ4H/Q== filip.fafara@thoughtworks.com
```

- [Grant AWS Console access?]
  > NO

**Comment by jbritt1** [comment]
SOCKS access granted. @ffafara-tw, please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.

**Comment by ffafara-tw** [comment]
I'd like to reopen this issue and request access to AWS Console.

**Comment by jbritt1** [comment]
AWS Access:
User: Filip Fafara
COR: Courtney Bethea
Approver: @Jeff-Hayter

**Comment by ffafara-tw** [comment]
What is the next step?
Are we waiting for @Jeff-Hayter to approve?

**Comment by jbritt1** [comment]
That is correct

**Comment by Jeff-Hayter** [comment]
@jbritt1 Approved for AWS access.

**Comment by jbritt1** [comment]
User created and first time login credentials provided.
