### ISSUE TITLE
SOCKS access for Mary Goodhart

### ISSUE THREAD

**Issue by mgoodhart5** [department-of-veterans-affairs/va.gov-team#66704]
### Your Name

Mary Goodhart

### Your Email

mary.goodhart@docme360.com

### Your Role and Team

DevOps Engineer - VES Developer Experience

### Product Manager (PM) name and email

Danielle Baranowski - danielle.baranowski@oddball.io

### Product Owner (PO) name and email

Patrick Vinograd - patrick.vinograd@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDDLhkJ06bVyblyEEaUym9WC60vcYKvcpJWlJtTy25WdZtVn9KybVtpSyTemz+551eJafosuxf+5bmmVx3NzbkP1yDYJC3qtGpO+K+dhl8QQHMjRbtvkJycMyEnp6HSkUGUe8RSv69JaFQDx5HIxo1X7Gmk9zocb9I1nQGdfQsIvc7oGMg3artgiwVbZYXzbkPuujTEpXdd8vVniLmEqTbJnOfbHbL+SZfge0m8yBHgr498gLwx3SBRFzXkFInRnbW0GWbJKHC+GzLV7Remk5esMZFjoFhfO00jQPt/fGCaybsLZNCWrEwC2BhGt8cOZLRynC81y9qZWrT2FUKHXbqhFVgtGhC27Pq52CgI9rUXb9MXCNBRGKTNisIrs83A7OBntz/16a09YgAE6umH5Aqj0bF38nA7fNoCjoz/CDHDCKct3UyQjfjf4+jEXFuABlHF0w7IxWvenZHPUvDUTobXAn6eh09f4B/sQwGq5DYMy+kyUi2rbI22fpuPQnYXW+k= conejomalo@conejomalo

### E-QIP Transmittal Confirmation

<img width="772" alt="Screenshot 2023-10-02 at 8 55 30 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/40919519/00028059-76f2-4873-bdc0-b76c900d80e5">

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by rmtolmach** [comment]
✅ access granted! Give it about 10 min and then run`vtk socks setup` again. Docs for troubleshooting if you need them: https://depo-platform-documentation.scrollhelp.site/getting-started/accessing-internal-tools-via-socks-proxy
