### ISSUE TITLE
Access for Marisa Hoenig

### ISSUE THREAD

**Issue by marisahoenig** [department-of-veterans-affairs/va.gov-team#6671]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Courtney Bethea @CourtneyBethea
- Please provide your name.
   > Marisa Hoenig
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Team: @thoughtworks
Role: Developer
Company: ThoughtWorks
I am part of a team at ThoughtWorks that is working with the CTO's office to update va.gov/scorecard. I have a PIV card that I was granted in January 2020. I am requesting access to the SOCKS proxy and Jenkins / Prometheus / Grafana so we can:

> - Modify / update Jenkins job configs
> - Kick off Jenkins jobs
> - Review Prometheus data, some of which is imported into the scorecard
> - Review Grafana data for the scorecard
If you have any questions or concerns please let me know.

- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Internal%20Tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCy+PyB/93ihtty/KG5KL9UHem13CHmHtuLQydC8ghKsIbf/k2+uMGsjvdQ2mJFU5r77mLtCVZNuOT1j7AYJrssqmTvKe9w6xJiK+eUYldpqLvCW6EgXVAAnKVildRrjm39I4co57aEYdryYtRzoOz07rGdBJ+l8aZRFrID4vy6P2opul4YOw6wyJoOH7q28/Si8B8z/hKPsVr1m64WcHHicdugkD9WSy2e5rkp6Bfc+szopDCbor2yywq0NOJiogEHvrynGzSC/EPBuY4OWw7er/E2IizvwA02PLrO2DcGQaRNkIU4C6+zzsvbYWzRp9iKdmdio4oib3QpcDQEgnwf73v0vA48ni+PZzk1ryiqSEoOJXTE6aNfjQ1EqKp658ORU8NILsF9Oa3sAnGhka8Fw3FgrhM9cNohqSfomwCeKAVvBCecPaYjSpH+wk/6LS4V3RyzN5Rpw4Rkw1mGZpsS4wcjaoweWaTv3UUOBlEyEL3oKz+F+bCbvnOR3RWvLIvCTy4V9WnJj8lAUn1j9Cn/IaeYWF1wN8UULXJuXNbF91yBeoGDXjVQ7ecV0AEobDWhaUDQ1Qj8pLbGjiqPufCJervBDt/qdtjHQHzfSLVpRKi59heKUET3L+IILg+QTUXKrdfs2O5WgD/9dzkFwRhuLlYoKJCk3BzDiRfaImKVDw== marisa.hoenig@thoughtworks.com
```

- [Grant AWS Console access?]
  ~NO~
  ~At least for now we don't think we need this.~ -> Requesting access now!

**Comment by marisahoenig** [comment]
@department-of-veterans-affairs/vsp-operations please review

**Comment by jbritt1** [comment]
SOCKS access granted. @marisahoenig, please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.

**Comment by marisahoenig** [comment]
Reopening to request AWS Console Access

**Comment by jbritt1** [comment]
### AWS Approval

User: Marisa Hoenig
COR: Courtney Bethea
Approval needed: @Jeff-Hayter

**Comment by Jeff-Hayter** [comment]
@jbritt1 Approved.
