### ISSUE TITLE
CMS [COGNITION]: Content SHOULD not be cut off; IE11 accordion content is not flowing into columns

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#6672]
#  [508-defect-3 ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-3)

**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

Please see screenshot below. Content **SHOULD** not be cut off. In IE11, under Compensation heading, when the accordion for "Find addresses for other benefit types" is opened the content shown displays in a single row, resulting in a horizontal scroll that may not be readily obvious, especially for older users and those with cognitive considerations. Checking the same component in Chrome, the content appears in columns and does not exceed the width of the show/hide accordion heading.

## Point of Contact

**VFS Point of Contact:** Jennifer

## Acceptance Criteria

As an IE11 user, I want to open "Find addresses for other benefits types" accordion and see the content without a horizontal scroll.

## Environment

* Operating System: Windows 10
* Browser: IE11
* Server destination: production

## Steps to Recreate

1. Enter `https://www.va.gov/decision-reviews/supplemental-claim/` in browser
2. Navigate to Compensation heading
3. Open the accordion for "Find addresses for other benefits types" 
4. Verify that the content currently results in a horizontal scroll

**Note:** The same issue happens on https://www.va.gov/decision-reviews/higher-level-review/

## Possible Fixes (optional)

`flex-wrap` has partial support in IE11, and may be the culprit here. It may be necessary to swap to a `display: inline-block` approach.

## WCAG or Vendor Guidance (optional)

* [Can I use flex-wrap?](https://caniuse.com/#search=flex-wrap)

## Screenshots or Trace Logs

![vsa-pw-ie-hz-scroll-bug](https://user-images.githubusercontent.com/57469/76234229-ce110c80-61ff-11ea-84a5-f0d9d872197f.png)

**Comment by kelsonic** [comment]
Since this will require an update to the design system should we assign this ticket to VSP? 🙂CC @ncksllvn @jenstrickland

**Comment by jenstrickland** [comment]
As I understand it (and verified in the browsers), the design changed since this issue ticket was documented, and the addresses are now presented in a single column rather than multiple columns.

This issue was addressed in an update.

![Screen Shot 2020-05-12 at 12 45 18 PM](https://user-images.githubusercontent.com/57469/81721983-b7c93c00-944e-11ea-9519-1cc5746bb0f8.png)
