### ISSUE TITLE
AWS access for [Kyle Henson]

### ISSUE THREAD

**Issue by khenson-oddball** [department-of-veterans-affairs/va.gov-team#66736]
### COR Name

Eunice Garcia

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Kyle Henson

### Your Email

kyle.henson@oddball.io

### Team, Role, and Company of the target individual

VA.gov IIR Product Team, Software Engineer, Oddball

### Product Manager (PM) name and email

Peter Egan peter.egan@oddball.io

### Product Owner (PO) name and email

Jeff Barnes jeffrey.barnes4@va.gov

### Desired AWS Access

Could I please have read/write access to the parameter store path /dsva-vagov/performance_dashboard and to S3 to read uploaded files from the dsva-vetsgov-scorecard-dev, dsva-vetsgov-scorecard-staging, and dsva-vetsgov-scorecard-prod buckets. Thank you!

### Access Expiration

Ongoing

### E-QIP Transmittal Confirmation

![Screenshot 2023-10-02 at 12 45 51 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/145150351/408e17b1-f141-470e-885c-4b0d3dffc3a8)

### Additional Notes

I need this access because I am a new software engineer working on the Platform Dashboard project and need to be able to obtain the project secrets and data.

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by little-oddball** [comment]
User is on VFS team roster

**Comment by JonathanKamensUSDS** [comment]
In @BillChapmanUSDS's absence I'm handling these access requests, and I'm still learning the ropes, so I beg your indulgence as I ask some questions about this request to help get myself up to speed. In particular:

* What secrets are in /dsva-vagov/performance_dashboard, and are secrets from dev, staging, and prod commingled there (or are the same secrets used for all environments)?
* Why is prod access in particular required here?
* If the access request is approved, then how will it be implemented (e.g., what groups will the user be added to, etc.), and what _other_ access, if any, will the user be granted as a result of how the access is implemented?

Thanks!

jik

**Comment by Eallan919** [comment]
Hi @JonathanKamensUSDS thank you for taking the time to review! 

To your first point, we just got write access to the repo yesterday so still learning more about how everything was previously set up. 

To your second point, the new VA.gov IIR CEDAR team is locating orphaned products on VA.gov and bringing them up to speed to current VA standards across the board.  The Performance dashboard is our first product to tackle, so we need to be able to make update. The product has not been maintained in 3+ years.  We might have to debug items in production, etc. 

To your third point, pinging @little-oddball for an assist.  What I can share is that this is new territory for our team so we aren't quite sure what else we will need access to at this time. 

I hope that helps!

**Comment by JonathanKamensUSDS** [comment]
Requested access provisionally approved, with two caveats:

1. Can we circle back in three months once the team has a better understanding of what's where and evaluate what prod access is still needed at that time?
2. @little-oddball can you answer my third question above or refer me to someone who can? I am guessing that we're not going to give them access only to the specific requested resources, but rather add them to a group that has access to those resources and other things as well. If I'm right, then I'd like it to be documented in the ticket what they were given access to.

**Comment by khenson-oddball** [comment]
Hey Jonathan, yes, I think it could make sense to circle back in three months to assess prod access that is still needed.

**Comment by little-oddball** [comment]
@JonathanKamensUSDS - Here is some follow up on the 2 items above.

1. When providing access to Prod the Platform team typically time boxes this to a 6 month lease and then review and determine if further access is needed. 
2. One of the current challenges we have is how fine-grained the access roles we have are. There are a couple access routes we have / that we can go but I would like @ph-One to weigh in on specifics with the items being requested.

**Comment by ph-One** [comment]
> * What secrets are in /dsva-vagov/performance_dashboard, and are secrets from dev, staging, and prod commingled there (or are the same secrets used for all environments)?

@JonathanKamensUSDS 

What is in the Parameter Store at this path is used by a service account. For those reasons I've separated out this access and am not sure it's appropriate to hand out -- secret keys, github tokens, etc., all for the Performance Dashboard Service Account/automation, and not values that you would expect a user to access

**Comment by ph-One** [comment]
>* If the access request is approved, then how will it be implemented (e.g., what groups will the user be added to, etc.), and what other access, if any, will the user be granted as a result of how the access is implemented?

@JonathanKamensUSDS 

I have implemented IAM in such a way that there are three User Groups:

1. S3 access to dev, staging, and sandbox buckets
2. S3 access to prod bucket
3. Parameter Store access

**Comment by JonathanKamensDVA** [comment]
>I have implemented IAM in such a way that there are three User Groups

Thank you, this sounds good to me.

>What is in the Parameter Store at this path is used by a service account. For those reasons I've separated out this access and am not sure it's appropriate to hand out -- secret keys, github tokens, etc., all for the Performance Dashboard Service Account/automation, and not values that you would expect a user to access.

Two questions:

1) Are the contents of the parameter store sufficiently small that you can enumerate and describe specifically what all of the items in it are for? Not in this ticket, please, let's put that in a more private location. I think that information would be helpful to @Eallan919 and @khenson-oddball in determining whether they need access to any of it, and if so, explaining why.

I don't want to deny needed access, but at the same time I want to make sure we understand (and document) what we're granting access to and why it's needed.

2) Are there secrets in the parameter store that are shared between production and non-production environment? If so, then I'd like to suggest that we should be treating the recent Sidekiq cred leak incident as a call-to-action to eliminate such credential sharing. If it's too much to do now then can we get it into the DevOps backlog to be prioritized with other work?

**Comment by Eallan919** [comment]
Agreed! @JonathanKamensDVA we can re-visit in a couple months 
@little-oddball FYSA

**Comment by khenson-oddball** [comment]
@little-oddball I have received the Slack DM with login info for AWS and have confirmed that I can access the S3 buckets for the Performance Dashboard. Are there any next steps for this?

**Comment by little-oddball** [comment]
@khenson-oddball - If you are all good, we can close the ticket. :)

**Comment by khenson-oddball** [comment]
I think there was discussion of possible Parameter Store access. Is that something that is still in the works? It looks like I do not have that access currently.

**Comment by little-oddball** [comment]
@khenson-oddball - that looks to be a discussion that is meant to occur outside of this ticket. @JonathanKamensDVA is the param store and on-going conversation?

**Comment by JonathanKamensDVA** [comment]
I have not been looped into discussions outside of this ticket. I believe the ball is in @ph-One's court on both of the questions enumerated [above](#issuecomment-1764962684).

**Comment by ph-One** [comment]
Closing. I've been in close contact with @khenson-oddball , as well as other IIR team members. We have worked through privileges and they are all set. Kyle currently has access to all of the non-production resources that he needs. If more privileges are required, please let us know @khenson-oddball

**Comment by khenson-oddball** [comment]
Thank you everyone for helping with this!
