### ISSUE TITLE
Redirect Request: Appointments

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#66741]
### Instructions
- Requests must be submitted **AT LEAST** 2 weeks in advance.  Some requests take a significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders as appropriate.  

### Type of request
- [ ] We are retiring or taking down a page and need to redirect the URL (complete redirect section)
- [X] We are changing the URL of an existing page (complete redirect section)
- [ ] We need a custom vanity URL (complete vanity URL section)

### Implementation date
When does this request need to be live?
Choose one:
- [X] On a specific date, connected to a program or publishing requirement. **DATE: October 4th 2023**
- [ ] Any day prior to a deadline/latest possible date. **DEADLINE:** 
- [ ] Any day after an earliest possible date. **EARLIEST DATE:**
- [ ] During a specific date range: ***EARLIEST DATE TO LATEST DATE:***
- [ ] No hard timing requirements, publish when possible.

### Redirects 
Current URL  |  Redirect Destination or New URL
---  |  ---
/health-care/schedule-view-va-appointments/appointments <br>**must include all child pages**| /my-health/appointments
/health-care/schedule-view-va-appointments/new-appointment <br>**must include all child pages** | /my-health/appointments/schedule/type-of-care
/my-health/appointments/schedule | /my-health/appointments/schedule/type-of-care

### Vanity URLs 
Vanity URL  |  Landing page
---  |  ---
requested URL | landing page URL

**Link to campaign landing page request issue:**

### Process, Roles and Responsibilities
- [ ] Requesting team: Above information is provided
- [ ] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [ ] IA: Request is vetted and documented and implementation plan is clear 
- [ ] IA: Request is assigned to appropriate team for implementation 
- [ ] Implementation team: Work is complete
- [ ] Implementation team: Validated in production
- [ ] Requesting team: Validates everything is correct in production and closes ticket

**Comment by mnorthuis** [comment]
@jilladams this one just came through, I'm looking it over and will let you know when its been approved.  This is part of the appointments launch this Wednesday.  Can you speak to whether your team can get this done by then?

**Comment by simiadebowale** [comment]
@jilladams @mnorthuis - I already have a PR open for the dev work. Let me know if that helps

**Comment by jilladams** [comment]
Yes, probably doable. We will need Platform's help to do an out of band deploy, so the timing to get these live will depend on their availability. 

Please let us know when the app will be live in prod, in order to redirect to it.

**Comment by simiadebowale** [comment]
@jilladams -  I was under the impression that changes to the DevOps repo for redirects get deployed on Wednesday at 10am? That was why we chose that day for deployment.

**Comment by jilladams** [comment]
Oh - yes, if we can get the details in time for our team to make the code changes during business tomorrow (Tues) and get it merged, it will ship on Wed. (Most of my engineers are CT or PT.) But if not: OOB deploy for redirects isn't a big deal, if we need to do that.

**Comment by jilladams** [comment]
Oh!! @simiadebowale I misunderstood earlier and thought you meant you had PR for the app to merge, but I see now you have the actual redirects implemented. So our team will really just be code reviewing that PR. No problem.
