### ISSUE TITLE
AWS access for [Ari Perez]

### ISSUE THREAD

**Issue by ariperez** [department-of-veterans-affairs/va.gov-team#66773]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Agile Six - Anthony M. Arashiro

### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Ari Perez

### Your Email

ari@coa.solutions

### Team, Role, and Company of the target individual

CMS

### Product Manager (PM) name and email

Berni Xiong

### Product Owner (PO) name and email

Erika Washburn

### Desired AWS Access

As part of the CMS Devops, I need aws access to work with self-hosted runners that run our GitHub action workflows.  

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

<img width="1161" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/2553469/560e4ab4-2a19-490f-9c75-0c4af1b8264a">

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by hgbarreto** [comment]
Approval needed: @department-of-veterans-affairs/operations-aws-approvers for "CMS-insfrastructure" group

**Comment by BerniXiongA6** [comment]
Hi @mchelen -- looks as though we'll need your approval on this request. @ariperez is doing DevOps on CMS Team, and has been cleared by VA. Could you help him to get approved for AWS access? cc: @EWashb

**Comment by mchelen-gov** [comment]
@BerniXiongA6 Thanks for the ping, this AWS request is approved on behalf of OCTO.

@hgbarreto Can you link me to the current internal docs for AWS approval? I want to check if `https://github.com/orgs/department-of-veterans-affairs/teams/operations-aws-approvers` or other groups need updating.

**Comment by hgbarreto** [comment]
@mchelen-gov  
[AWS Access Request](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request)
[Access Policy](https://vfs.atlassian.net/wiki/spaces/~63618f93fc0cc7a600b041f2/pages/2706112528/Temporary+AWS+Access+Policy)

**Comment by ph-One** [comment]
Closing. User has been added to AWS and contacted with follow-on details
