### ISSUE TITLE
Business intake form for Specialty Care Long COVID Digital Screening

### ISSUE THREAD

**Issue by madlyPIF** [department-of-veterans-affairs/va.gov-team#66780]
## Your Details
1.  Marian Adly
​
2.  **Business Line**
    Health - Send clinical wellness checks to digitally screen and guard against deterioration and meet Joint Commission requirements for program evaluation. 
​
## Notification Details
1.  **Notification type**
    Text/SMS
​
2.  **Please describe your use case.**
    To support clinicians across VA Medical Centers to digitally screen COVID-survivors among VHA enrollees and identify those who have not made a full recovery and are candidates for Long COVID care.  After Veterans have received mental health care in the VA,   

These messages fall within the wellness checkups as defined in the Standard Operating Policy for Delivering Personalized Notifications via Text Messages - 3. c. i. “Health care communication, including communication about appointment and exam confirmations and reminders, wellness checkups, hospital pre-registration instructions, pre-operative instructions, lab results, post-discharge follow-up intended to prevent readmission, prescription notifications, and home healthcare instructions.” 
​
3.  **What actions can the user take based on the notification they receive?**
   User Veteran can fill out a digital health screening for Long COVID and submit back to clinician via BHL Touch.  
​
4.  **What is the desired business outcome?**
    Desired outcomes include fewer skipped appointments and less burden on primary care to help patients receive the appropriate level of care for ease of diagnosing and referral to Long COVID care.  Additionally this will support wellness reporting as well as enhanced access to care.  This will yield to fewer skipped appointments, increased coordination in care needs, as well as targeted outreach to under-served Veterans for care needs.   
    
5.  **What system will kick off the notification? Please note the system should be inside the VA or have an ATO.**
    System that will kick off notification is BHL which is inside VA and have supported clinicians for nearly 12 years, has an existing ATO and has permission for write back to CPRS/VistA and Cerner.  Clinicians identify and initiate distributions from COVID patient panels.   

6.  **What will trigger the notification?**
    Clinicians will identify and send to the Veterans digital screens.  The screening is sent to any Veteran with a COVID positive test or ICD10 indicating COVID diagnosis. 
​
7.  **Provide sample content per notification type, if you have it.**
    Please note we collaborate with all of our users on their content to ensure it meets standards.

LONG COVID VA GOV: 

To provide personalized care following the COVID pandemic, your VA provider would like to know how you are doing.  Please visit [link] to answer their questions.  

If you already completed this survey, please disregards this message.

Reply STOP to end messages.

​
8.  **Has a Privacy Officer (PO) seen and approved the content? If not, do you know who your PO is?**
   Privacy Officer is Stephania Griffith, JD.  Stephania Griffin is Privacy Officer and has been supporting the team since August 2022 in reviewing and approving all content.   
   
9.  **Would you prefer to provide contact information for the recipients or would you rather VA Notify look this up for you by Veteran ID? If by ID, please let us know what identifier is used in your system.**
    Yes, the system currently does look up patient information by Veteran ID using ICN and other qualifiers important to clinicians.  Workflow is already in place and has been operational since November 2022.  
​
10.  **Do you currently capture communication preferences related to this notification? If so, please describe.**
No, should fall under wellness checkup.  
​
11.  **What is the anticipated volume of notifications per day, week, month?**
~5000 per week​

12.  **When does this notification need to be in production?**
 11/1/2023 or sooner.

**Comment by mjones-oddball** [comment]
In Oct 2023, BHL was exploring adding this message `VA BHL GOV: Your VA Provider wants you to complete a short health questionnaire, so they can provide personalized care following the COVID pandemic. ((URL))` and sending through the existing short code. However, I do not see this template in their service. Moving to closed. Please re-engage if VA Notify support is needed.
