### ISSUE TITLE
AWS access for Kyle Chamberlin

### ISSUE THREAD

**Issue by tw-kyle** [department-of-veterans-affairs/va.gov-team#66783]
### COR Name

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative Name

GovernmentCIO - Kimberly O. West

### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Kyle Chamberlin

### Your Email

kyle.chamberlin@va.gov

### Team, Role, and Company of the target individual

Live Agent, Tech Lead, GovCIO

### Product Manager (PM) name and email

Yevgeny Dreyband / yevgeny.dreyband@va.gov

### Product Owner (PO) name and email

Ian Santarinala / ian.santarinala@va.gov

### Desired AWS Access

Same as Helene McCarron, Seth Schwartz, and Omar Carey

### Access Expiration

12/12/2023

### E-QIP Transmittal Confirmation

<img width="974" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/110405547/a73b61aa-dce3-4982-8efb-e6c691fea9b5">

### Additional Notes

COR Name: Mary O’Toole

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by tw-kyle** [comment]
Bump

**Comment by hgbarreto** [comment]
User condirmed to be in [VFS Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)

**Comment by ph-One** [comment]
Closing. User has been added to AWS and contacted with follow-on details
