### ISSUE TITLE
[Discovery] Data Availability from Call Centers

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#668]
## User Story
As a product decision maker, I need data reflecting my customer's voice so I can understand my product's UX and product health.

## Goal
Meet with system SMEs and discover how the tools work and what data can be retrieved from those products for the product health prototype.

## Acceptance Criteria
- [ ] Set up meeting with SME
- [ ] Meet with SME
- [ ] Document how the product functions (where the data comes from, how it's recorded, any available APIs, etc.)
- [ ] Document relevant data points

## Definition of Done
- [ ] **Attached to a Milestone**
- [ ] **Attached to an Epic** 
- [ ] **Labeled with Team** 
- [ ] **Labeled with Practice Area**
- [ ] **Labeled with Type**

**Comment by joanneesteban** [comment]
Discovery Questions (ongoing):

- What Call Center data can we currently access?
  - Who owns the data?
  - Who can access the data?
  - Where does each data source live?
  - What do the outputs look like? What do we have to derive ourselves?

- What call center data do you expect to obtain within the next 6 months?

- What are the current gaps in call center data?

- How would you expect the call center data to be aggregated into one tool?

- How would you expect the call center data to be used by product teams?

- Is there anything else that the Insights team should know that would help add Call Center data to the product health tool?

**Comment by amycesal** [comment]
A couple of more basic questions that would help me:
- What data is collected from call centers?
- How is the data collected?

**Comment by amycesal** [comment]
### Notes from the call
* What Call Center data can we currently access?
> - Amalgamation of data
> - 2 systems,
>      - Iris,
>          - Can export data and run results
>     - Microsoft dynamics
>          - Issues that people submit from sign in form
>          - tracks: browser, account login type (IDme, etc…), actual issue
>     - Vets.gov had a call center, and tagged by issue, and sent over a spreadsheet
> - NCC (benefits, non-health, non education)
> - Education call center
> - Member services call center (health related) with specific call centers, like prescriptions 
> - Quantitative data: Quick resolution, vs, longer resolution time. 
> - Qualitative data (transcriptions? Listening calls?)

* What call center data do you expect to obtain within the next 6 months? 
> - Eventually White House call center will tag issues with topic and sub topic 
* What are the current gaps in call center data?
>     * Inability to track by issue types and topic and sub- topic 
>     * The amount of data we’re getting
