### ISSUE TITLE
Evaluate and improve downtime notification process for apps

### ISSUE THREAD

**Issue by U-DON** [department-of-veterans-affairs/va.gov-team#6681]
## Background

There are some checks we can perform regarding the status of apps. Those include making requests to:
- `backend_statuses` for the statuses of external services that the apps depend on
- `maintenance_windows` for the scheduled downtimes of those external services

The former is used to report unscheduled downtimes when a service goes down unexpectedly. The latter is used to report scheduled downtimes, where we already know that a service will be down at a specific time and have created a maintenance window in preparation.

Finally, there is a JSON file of global (API) maintenance windows cached to S3.

The API pulls data from PagerDuty for all of these.

## Objective

Consolidate the various existing downtime checks, sources being checked, and handling of the results, and make it reusable and clear and easy to use.

## Design

We should be able to wrap apps into an `AppStatus` (just to throw out a name) container that does the following series of checks and renders accordingly:
- See if there is a global downtime in progress.
- See if any external dependencies have a scheduled downtime with expected end time.
- If there are no scheduled downtimes, check if any of those dependendencies are down.
- Render the content as usual if everything is up and running.

### Consolidate maintenance windows into one source.

- Global maintenance windows are cached to a JSON file in S3
- All other maintenance windows are cached in a DB and retrieved through an API request

Ideally all of the data would live in the S3 bucket since we need to access at least the global maintenance windows when the API is down.

### Custom downtime messaging should be easy and straightforward

We have a `render` prop that can be passed to the current downtime components.

There's also a way to pass down custom messaging when scheduling maintenance windows for PagerDuty services.
- Currently it's by including in the description something like, "USER MESSAGE: <My custom message here.>".
- That's just being parsed by the API job that caches the maintenance windows, so we can change the format however we'd like.

We should consider the best way to combine these ideas into a simple mechanism for configuring custom downtime messages.

### Confirm the relevance of a few untracked PagerDuty services

There are some potentially relevant PagerDuty services that we aren't tracking in the API or website.
- Component: Identity|Authentication
- Component: Education Benefits
- Component: GI Bill Comparison Tool (GIBCT|GIDS)

We should confirm whether these are still useful in general and in the context of displaying downtime messages in the FE. If they are useful for reporting downtimes in apps, we should map those in the BE so they can become available to the FE.

It's not clear if there's a benefit to distinguishing between internal and external dependencies when it comes to showing downtime messages in the FE. We're mostly tracking external services so far in the FE (`global` represents the API, which is internal), but be sure to keep in mind the appropriate organization, phrasing, naming, etc. when making these changes.

### Potential BE refactor

The API is running three separate jobs to cache PagerDuty data.
- `ExternalServicesStatusJob` to populate data for `backend_statuses` (running every minute) 
- `MaintenanceWindowRefresh` to populate data for `maintenance_windows` (running every 30 minutes)
- `GlobalDowntimeCache` to upload global downtimes to S3 (running every hour)

They are all pulling from the same source with different frequencies. Consider consolidating some. Maintenance windows and global downtimes will naturally combine if we decide to cache all of it to S3. It might be useful to keep fetching the statuses of external services (just a simple "up or down?") separately with high frequency in order to get real-time status.

**Comment by rianfowler** [comment]
Might be good to require all calls to vets-api to be wrapped in an ops toggle. This is would be a nontrivial amount of work but could be useful when we run into issues similar to last night. It took 40+ minutes to get a minor fix out to disable an endpoint call. 

More on ops toggles: https://www.martinfowler.com/articles/feature-toggles.html#CategoriesOfToggles

**Comment by rmessina1010** [comment]
Expired. Closing.
