### ISSUE TITLE
[BE] Update DataDog vets-api dashboard to include metrics for 45-minute reminder

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#66835]
## Background
We are going to need a way to capture metrics for knowing how many Veterans complete check-in by clicking the reminder message versus texting "check in" to 53079.

Here are the metrics we need to capture:
- How many Veterans used the 45-minute reminder & completed check-in
- How many Veterans used the 45-minute reminder & DID NOT completed check-in
- How many Veterans used the text "check in" & completed check-in
- How many Veterans used the text "check in" & DID NOT completed check-in

## Tasks
- Update DataDog vets-api dashboard to include metrics for 45-minute reminder

**Comment by loripusey** [comment]
@kanchanasuriya where are we with this one? We are in the 3rd sprint with this one.
cc: @anita-halici

**Comment by loripusey** [comment]
@randomsync can you help @kanchanasuriya move this one along?

**Comment by randomsync** [comment]
added a datadog dashboard for these metrics: https://vagov.ddog-gov.com/dashboard/gjx-4i9-de3. will add the new filter for veteran vs vetext initiated once it starts reporting

**Comment by randomsync** [comment]
The dashboard here: https://vagov.ddog-gov.com/dashboard/gjx-4i9-de3 has been updated and is starting to show data
