### ISSUE TITLE
Midpoint Review - IA Feedback - AE Profile, Profile Hub

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#66834]
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- Woohoo, goodbye hubless spoke model of the profile pages! Thanks for leading this work to make the profile more usable for Veterans.
- I am excited to see navigation/IA questions in the research plans.
- You asked "how many cards is too many" on the profile page. I agree with Matt that we haven't gotten to the max number yet, _and_ that 10 is probably the max here. If we want to rely on [70-year-old cognitive research](https://en.wikipedia.org/wiki/The_Magical_Number_Seven,_Plus_or_Minus_Two) for some guidance, we'd have a max list size of 9 items. Design-wise, 10 would be two even columns on desktop view. Alternately, the list could be 9 items with the 10th item being a "Need help?" card as an exit valve for folks if they are overwhelmed, confused, or stressed and just need to talk to a human.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- **Must**: The first segment of the title tag should match the H1 - whatever the page title ends up being.
- **Consider**: More on the page title, and a summary of discussion from the call - the H1 for the page is "Profile", but the first segment of the title tag is "Your Profile" which might actually be a clearer title for these sets of pages. **And** using "Your" in the title will result in some conflicting pronoun use at the most likely entry points for this page - My VA and the auth menu, both of which use "My" instead of "Your" pronouns. Our [pronoun guidance](https://design.va.gov/content-style-guide/plain-language/use-pronouns) has evolved over the years and we will likely need to think about standardizing My/Your language across the site soon. That said, sticking with "Profile" for now is a great middle ground. If the team feels so inclined, including a question for research participants about the title of the page - "Profile", "Your Profile", "My Profile" - could help us build our research library around this topic in advance of any big My/Your title changes.

Thanks and happy researching!

**Comment by mtcA6** [comment]
@pamela-drouin check out the consider feedback we received, I'm inclined to say we should stick with `Profile`, if it's not too late and there is enough time maybe we add a question about Your Profile vs Profile. But I leave that up to you.

**Comment by pamela-drouin** [comment]
@mtcA6 -- @andaleliz and I chatted and agree the best thing to do for now is to update the title tag from "Your Profile" to "Profile" and stick with that for now until the larger My/Your question can be answered.

@erinrwhite thank you for your feedback! I am equally excited for the same reasons! 

As the researcher leading this study, I'm inclined to think it's likely that asking for participants' thoughts on whether to use possessive pronouns will likely generate a lot of opinions that might not actually help answer the question of what VA.gov should do across the board. I know CAIA has been talking about this inconsistency for a while, and I will definitely gather any feedback or insights with regard to this issue should it arise!
