### ISSUE TITLE
[Parameter Store] Add tags to Certificates

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#66864]
Certificates that are stored in AWS Parameter Store should be tagged for easy retrieval and scanning.

## Tasks
- [ ] Tag each certificate with `purpose: certificate`

**Comment by ph-One** [comment]
You can use these commands to list out all certificates and keys in parameter store. This should give you a jumping off point for which entries to tag

```
aws ssm describe-parameters --query "Parameters[].Name" \                                                         [15:36:39]
| jq -r '.[]' \
| xargs -I{} aws ssm get-parameter --with-decrypt --name {} \
| tee -a ~/bingo/ps-`date +%Y%m%d%s`.certs.json \
| jq -r '.Parameter | select(.Value | match("--BEGIN CERTIFICATE--")) | .Name '
```


```
aws ssm describe-parameters --query "Parameters[].Name" \                                                         [15:36:39]
| jq -r '.[]' \
| xargs -I{} aws ssm get-parameter --with-decrypt --name {} \
| tee -a ~/bingo/ps-`date +%Y%m%d%s`.keys.json \
| jq -r '.Parameter | select(.Value | match("--BEGIN RSA PRIVATE KEY--")) | .Name '
```

**Comment by barbarello** [comment]
pulling into sprint now that i have permissions for aws

**Comment by barbarello** [comment]
current work in branch https://github.com/department-of-veterans-affairs/devops/compare/feature/ps-secrets-tagging?expand=1

**Comment by npeterson54** [comment]
Rolling over into next sprint due to some unexpected PTO and a large # of support requests/cert renewals

**Comment by ph-One** [comment]
@barbarello Let's break this up into two separate tasks -- one for certificates, and one for keys

**Comment by ph-One** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/69333
