### ISSUE TITLE
Secondary navigation in MHV on VA.gov

### ISSUE THREAD

**Issue by LynneJohnson224** [department-of-veterans-affairs/va.gov-team#66863]
As a veteran, I need a seamless way to navigate between health apps so I can easily move through all of the health care related tasks that I need to complete.

**Comment by wesrowe** [comment]
Renamed epic after expansion of solution space beyond "secondary navigation"

**Comment by wesrowe** [comment]
This work is largely complete, including collab cycle, and follow-up tweaks are in the portal integration epic. Closing.
