### ISSUE TITLE
[UX] [Design] Update Production Sketch File for DS v. 3 Components

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#66871]
## Tasks
- Update the production Sketch files for these changes to the DS v. 3 components
    - Form components (i.e. last name & DOB)
    - Accordions
    - Info components

**Comment by zach-park** [comment]
@ytsaoca and @zach-park split the task per components:
- Ya-ching: Form components (i.e. last name & DOB) and Info components
- Zach: Accordions

**Comment by zach-park** [comment]
The form components (i.e. last name & DOB), info components, and accordions are ready for validation. @benbrasso-agile6 @cgednalske @ytsaoca

**Comment by zach-park** [comment]
@ytsaoca , I validated the memorable form components and additional info components. Overall, they look good except for a few minor tweaks. I tagged you with some comments in the sketch. Thank you!

**Comment by ytsaoca** [comment]
@zach-park Validated your parts. Also slacked you about the comments.

**Comment by zach-park** [comment]
Completed Ya-ching's part.

**Comment by benbrasso-agile6** [comment]
Is this all validated? @cgednalske did you want/need to validate?

**Comment by cgednalske** [comment]
@benbrasso-agile6 I did a little earlier this week and everything looked good. I just had a question about if we could somehow label the non-symbol accordions and such as v3 so we can be sure they're updated moving forward, and it looks like Zach found a solution for that 👍

**Comment by zach-park** [comment]
> Is this all validated? @cgednalske did you want/need to validate?

Yes, Ya-ching and I both validated. And it  would be great to get Christina to look them over again.
