### ISSUE TITLE
Identify Facilities and Facility IDs for GIS in Pilot

### ISSUE THREAD

**Issue by lmorris3** [department-of-veterans-affairs/va.gov-team#66878]
Problem:

For the IPP Veteran Intake application, Veterans need to be able to select a VA facility/site to go to for in-person identity proofing. How might we help Veterans select a location that is close to them? How might we show several options based on where they live so they can choose the facility that works best for them?

**Comment by mateoclarke** [comment]
We decided to use the 3 sites in Little Rock:
https://www.va.gov/find-locations/?page=1&address=Little%20ROck%2C%20Arkansas&facilityType=health&serviceType&latitude=34.746481&longitude=-92.289595&radius=38&bounds%5B%5D=-93.039595&bounds%5B%5D=33.996481&bounds%5B%5D=-91.539595&bounds%5B%5D=35.496481&context=Little%20Rock%2C%20Arkansas%2C%20United%20States
