### ISSUE TITLE
SOCKS access for Jaclyn Barrera

### ISSUE THREAD

**Issue by jaclyn-barrera** [department-of-veterans-affairs/va.gov-team#66877]
### Your Name

Jaclyn Barrera

### Your Email

jaclyn.barrera@thoughtworks.com

### Your Role and Team

Full Stack Engineer on VES Developer Experience

### Product Manager (PM) name and email

Jamie DeHaan

### Product Owner (PO) name and email

Patrick Vinograd

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC7Y25eo6ljChG5h73oV2tG25XtXj8p2+eCn/e2pUk3ULWwMIr59b/Vw0VCmt7kB3uTbE7vgg3F+wpkhJXyY7E+xekccoV5Na+Z4aw+Ggh0oPEEe4sd3YYoSWPgdU7qpjuXsT9BVG0/YZZEdO9hHbADy/19V+b7SUjoD2rLKbyuSXBIlMBe2Ov332A904wnT6VlnkjMtOhVWBFd/H2gmjI+r8tghKqvbOk/ble1HrenPp/TA1npwql3UBFjYciidJ15qixf70DJuwJRHY5bz+15zcbnyfYybZ2099Ip4mdSSvuTPgqPLVGvV3Ajhj0Zv3jqWkgv9IRg0qW5WLj06hHQaSKGdXua4sIBnqMvdAtuKCHqSktyPxgPohFGn/96GcSq2IT/D3igM/DayqvEa+yKCxcLdEbn7uuyo6m0Jv8HawMN9aAopEdQJAtT81P/qmy9EreE0hJxp0oyaR1Bxfj5IjNF/7gPcPSiEP+Z0f1uYuxoB0rKsQgsvHBPXTMVXO0= jaclynbarrera@Jaclyns-MBP-2

### E-QIP Transmittal Confirmation

<img width="955" alt="Screenshot 2023-10-04 at 11 47 46 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/98929574/f7c72245-4829-471a-81e7-24d9b0ce338a">

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by flooose** [comment]
Closing this because the associated PR has already been merged
