### ISSUE TITLE
Research / UX | Profile | Story Board for Using Military Information 

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#66894]
## Background
While our stakeholders have tasked us with expanding the military information available in the profile, this ticket is expressly focused on HOW veterans will use this data once it's in the profile.

While some forms may use auto-fill, it's important we consider how a veteran might use the military information when applying for benefits if the auto-fill feature isn't working for a particular form.

In other words, a story board exercise would help us consider how a veteran might step through the process of using their military information. eg. do we need an export button or a printer friendly screen. 

We should also consider, as part of this story mapping process, how other teams will be made aware of the existence of additional military information in the profile. This is just and idea but we may want to create an additional story map for institutional users that considers how the information in the profile may or may not be available to people in the call center, or in a healthcare setting. Does it matter? It may not but lets think through all of the angles here!

**Comment by Dottifacilities** [comment]
New info has pointed to need for tech discover and stakeholder convos instead of this
