### ISSUE TITLE
SOCKS access for Fazil Mammadov

### ISSUE THREAD

**Issue by fazilqa** [department-of-veterans-affairs/va.gov-team#66893]
### Your Name

Fazil Mammadov

### Your Email

fazil.mammadov@va.gov

### Your Role and Team

QA Automation tester

### Product Manager (PM) name and email

Bryan Riley

### Product Owner (PO) name and email

Lichelle Bain

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDC2stQh3KCGdOLdQVpRi3P+SIf3caOqFsViUN03WxQP7KnsBYDpD3gMswodrZiQiFd2fGf4JQVEclO/9DO/yLurnoBv39kUiy9aOTKBWfcZvoYeymMvIQGCV9onxeMLmRauhXKeLhi44YODDdldxrmmwoF7l81zoaO6nI5d9xglcQtWCQ7+x0jmN2Nptvx5J8d8ksvjc1uY1b5DjVYMhSkM4V9BY3ZTXZyQKAYv1gza1HUO9dvh6izOIZivP1oCZj0yfxMFf432vAm7KPZBDGx9+kdDOJ1pC/WYhnJ16RDuIyF+orKm59v5GSRTl3IDTvxcnnpY6w3bLJkjrZQ6pCAQiew+aRfx7pKFEeHQVi+YVP2k7M+mtXqikScZtT2msCCVSalPO8xA26e65xhaQuMua0DnbV7uaJhA/A6oFqs/cZp6tX8rsNQS2YJlW1b4wETPDo6FbIvlFJ0Dw3suaXae1u+3OttG6ZDaP9ZbMJIPEfVUO+lu8CZbV31GY2EFuU= fm@G9J4C69DP2

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.
<img width="1433" alt="Transmittal Notice" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/127263470/5c9fe09c-33ae-4d3e-9a37-ec33b6c7b559">

**Comment by flooose** [comment]
@fazilqa I've removed the PDF of your e-qip transmittal because the file contains your social security number and this is a public repository. Please submit a screenshot of the email you received instead.

**Comment by fazilqa** [comment]
thanks for the update. not sure what kind of email you want me to upload. anyhow attached the only one I had found on my inbox.

**Comment by flooose** [comment]
Hi @fazilqa, thank you. This screenshot indicates that your e-qip is still being processed by a first-level checker. After their checks are finished, they'll will move to the next step, which is the actual e-qip transmittal. At that point you should receive an email with the words "Transmittal Notice" in the subject.

**Comment by ph-One** [comment]
The key was merged and added 2 weeks ago. Closing.
