### ISSUE TITLE
[Design/Research] 10-10EZR: Discovery - Come up with proposed prototype tool for user research

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#66890]
As a Veteran looking to update my information, I would like an application that has been vetted by other Veterans so that I know it is designed to be as easy as possible to update my information online.

- [x] Look into CodePen for:
- [x] --USWDS V1 vs. V3
- [x] --How long it would take to come up with a prototype
- [x] Investigate UXPin license to determine if that would produce better research results
- [x] **Success: A recommendation for a research prototype tool and an estimated timeline for prototype**

**Comment by jessicastump** [comment]
A summary of findings here:

- Have access to a CodePen pro license and have been playing around with setup
- There are existing stylesheets / Pens other teams created that can be leveraged
- There is not a full header/footer, the templates use the simplified versions. Would need dev help maybe to get this setup
- There could potentially be other components/debugging that might be needed, some development/code help
- Overall, it seems like setting up the pages/Pens would take about 1 Sprint but there might be a need for dev help (not sure how to estimate that time)
- UXPin is not a route to explore, licensing and accessibility issues 

Even if not used for EZR, having CodePen setup and ready could be valuable in future work.

**Comment by jessicastump** [comment]
Closing this ticket with notes above and EZR meeting decision to continue on the plan to test in Production for the mvp EZR. 
Will open another ticket for CodePen template/stylesheets setup with FE help to work on as time permits in an effort to get this setup and a head start on the next initiative. 

cc @alexseelig
