### ISSUE TITLE
[Product] Iterate on KPI Setting Workshops

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#669]
## User Story
As a VSF product decision maker, I need to understand what KPIs are and how to set them so I can drive my product decisions based on data.

## Goal
Iterate on previous va.gov and CMS KPI setting workshops for usability.

## Acceptance Criteria
- [x] Iterate on the current KPI setting workshops
  - [x] New Presentation
  - [x] New Board/Sheet for in-person team work
- [x] Design input by Emily
- [x] Content input by Peggy
- [x] Create plan to document KPI workshop in Github

## Definition of Done
- [ ] **Attached to a Milestone**
- [ ] **Attached to an Epic** 
- [ ] **Labeled with Team** 
- [ ] **Labeled with Practice Area** 
- [ ] **Labeled with Type** 

## Resources
- [Insights KPI Workshop](https://docs.google.com/presentation/d/1jPMXClHQ5vR6U3Eyslf_Wup0Yfwuc3QVWX5AyBKKWFk/edit#slide=id.g33cc3b02a5_0_78)
- [Ben Barone's KPI Workshop](https://docs.google.com/presentation/d/1wsNrhFafzOiCOm124m0_dASSZzV33hlavR8OISmnh_Q/edit#slide=id.g520c73640d_0_167)
- [Ben Kutil's KPI Workshop](https://docs.google.com/presentation/d/1w5rKbJRUzUmaaebAd1ZzJAUqRtiYk8dXsab1AL_axog/edit#slide=id.g56336a60c9_0_956)
- [CMS Miro Board](https://miro.com/app/board/o9J_kxvIi6g=/)

**Comment by joanneesteban** [comment]
Iterated Workshop [here](https://docs.google.com/spreadsheets/d/1GrzeUfQOmOGNntdYrz2etsEXj5BtmwDitzCg4mN4QnM/edit#gid=1267800872)

Adding @emilywaggoner for design input and @peggygannon for content input.

**Comment by joanneesteban** [comment]
@emilywaggoner @amycesal @peggygannon 

Apologies, I should have been more clear - the workshop that we would be delivering is on the last tab of the sheet. I renamed it "Workshop" 
[KPI Workshop Google Doc](https://docs.google.com/spreadsheets/d/1GrzeUfQOmOGNntdYrz2etsEXj5BtmwDitzCg4mN4QnM/edit#gid=1267800872)

**Comment by peggygannon** [comment]
@joanneesteban I've reviewed and provided some edits in the google doc (last tab)!

**Comment by joanneesteban** [comment]
@peggygannon Thanks!

Our instructions to teams is also on the 3rd tab:

>>
Intro Page
--
 
KPI setting will be a part of your product development process.
We will meet with you to do the workshop to set your KPIs and have quarterly checkins to go over your results and identify if we need to change anything in the dashboard.
There is a preworkshop planning that your team will need to fill out beforehand.
There will be a KPI workshop, about 2 hours long, that will leverage the information that you pre-filled.
 
Once you fill this out, please store it in your product folder in Github.
We will incorporate whatever makes sense from this into the dashboard.

**Comment by joanneesteban** [comment]
Checking in on this (intro and workshop tabs), as we're looking to deliver the workshop to teams this week:

@peggygannon is content ready to go? 
@emilywaggoner @amycesal is design ready to go?

Thank you for your help!

**Comment by joanneesteban** [comment]
Workshop and workshop plan documented in [Github](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/Platform/Teams/Analytics%20and%20Insights/Welcome%20to%20Analytics/KPI%20Setting%20Protocol.md). 

Moving on to implementing the workshop! Thank you to everyone for your help on this!
