### ISSUE TITLE
Document Upload End Point Migration Sanity Check

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#66901]
At a high level, the core document upload migration work can summarized as:
- Updating the flow where veterans upload supplementary documents (ready for testing and review)
- Updating the Submit Uploads worker that submits those documents to submit to Lighthouse instead of EVSS (ready for testing and review)
- Updating the Form 0781/Form 0781a worker to the do the same (ready for testing and review)
- Updating the "BDD Instructions" upload worker to do the same (in progress)

However, there are some loose ends around the final "review and submit" flow that could need updates

This will entail:
- [x] Re-reviewing the end of the 526 upload flow code and any callbacks that may relate to EVSS
- [x] Sanity checking with Seth to make sure I'm keeping any changes within a scope that doesn't duplicate or mess with his backup submission migration work
- [x] Making any remaining changes before we call the Document Upload migration "done enough to start testing manually" so we can confirm we have all the pieces in place/catch any gotchas

**Comment by NB28VT** [comment]
Meant to close this last week, reasonably confident I've made the required changes in all of the right places, at least enough to start testing.
