### ISSUE TITLE
Terms of Use (TOU) UI iterations

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#66907]
### Description of UX Tasks
The TOU page needed to be engineered in a way that a user isn't fully signed in. Meaning if we continue to use the standard VA page header for TOU, users will sign in, come to the TOU which has the sign in button in the header instead of their name, likely causing many to wonder if their sign in failed. We want to take some time to consider modifications to the UI so we don't break users' expectations.

As part of this UI iteration, we want to consider and decide on whether to move the accept/decline buttons back to the top of the page.

Top options are either a modal or a full page that has a modified header

- [x] Sync with Collab cycle team about doing a 2nd Midpoint review - yes this is possible
- [x] Sync with Collab cycle design folks about going to a modal vs doing a standard page with a modified header
   - They prefer modal to be short on text and for quick decisions, not the best use case here
   - [Check-in team](https://www.sketch.com/s/a720996f-5ebb-4092-8e5d-8e3dcff50dc7/prototype/E50121F2-F405-46C7-9FE6-8505525F7010/a/E50121F2-F405-46C7-9FE6-8505525F7010) and [Forms team](https://www.sketch.com/s/a720996f-5ebb-4092-8e5d-8e3dcff50dc7/a/L0LVoDQ) have both done a simplified header, that may be a good option
 - [x] Sync with Check-in team and Forms team to get a better understanding of their modified headers 
    - From Check-in team - there aren't standard components for minimal header/footer, timing on DS team making this is TBD
        - Check-in team - FE Brian Seek can answer any questions about matching their design and their FE implementation
 - [x] Settle on design iterations
     - [x] Use this minimal header? yes modified version of this
     - [x] Use this minimal footer? not at this point, perhaps on another iteration
     - [x] Put buttons back at the top like in the original "terms and conditions" page? yes - Tom is ok with it, haven't heard not to from OGC
 - [x] Set a second Midpoint review, to go over these design changes
 - [x]  [Midpoint Review 2](https://app.zenhub.com/workspaces/collaboration-cycle-reviews-61d89e9e5f4c120011a0ad37/issues/gh/department-of-veterans-affairs/va.gov-team/60961)
 - [x] Assist FE with design modifications, as needed

#### Simplified Headers Used on VA.gov mobile version and desktop version
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNk1MQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--93157b39dd717d0c4d2a2174142ebf3a8a5cda1f/Screenshot%202023-10-05%20at%2011.18.19%E2%80%AFAM.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlVMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b48327a3ad85cbab004e17d763a123b121b0bad0/Screenshot%202023-10-05%20at%2011.17.51%E2%80%AFAM.png)
#### Acceptance Criteria
- [x] Reviewed by UX Team
- [ ] Reviewed by PMs
- [ ] Documentation has been updated
- [ ] Put published research in drive

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by charlye-bluetiger** [comment]
LGTM!
