### ISSUE TITLE
UX Spike: ITF Asynchronous Wording Update

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#66903]
During a recent volume increase of Veterans attempting to submit their application before the PACT Act deadline it was discovered that the ITF service was overwhelmed and blocking Veterans from continuing with their form. 

As part of mitigating this, it has been determined that we want to change the ITF creation to be asynchronous. I.e. if the Veteran gets to the point of the application where an ITF would be created, but the ITF service is unavailable, we should allow the user to continue but queue the ITF creation date-time and backfill as needed. 

This however, requires that we modify the language of the current ITF messaging. 

Current user flow:
1. Veteran navigates to 526 application
2. Veteran logs in
3. Veteran starts application
4. 526 calls ITF service and once it responds we show the result of the ITF service to the user
5. If ITF service is down, the Veteran will not see the ITF message and will be blocked from continuing

Proposed new flow:
1. Veteran navigates to 526 application
2. Veteran logs in
3. Veteran starts application
4. Veteran provided newly messaged ITF message regardless of ITF service availability
5. Veteran is able to continue with application

Acceptance criteria:
- [x] Mock up new ITF message that informs user of ITF information that does not require information coming from the ITF endpoint and aligns with how ITF is being set asynchronously 
- [x] Validate mock up with Octo Stakeholders and VBA to assure messaging is accurate, within policy and does not place any burden on the Veteran
- [x] Final approval from CAIA

**Comment by nnicholas7** [comment]
Update: Attend CAIA Office Hours on 12/12. I was able to get feedback on the header. CAIA suggested changing the header of the message to " We're checking or We're confirming...". CAIA need more time to think about language and tone being used in 1st paragraph of the design. They (Lily S, Katherine Fung, or Laura) will get back to us on Wednesday with feedback for the whole message.

**Comment by nnicholas7** [comment]
Sketch File for ITF Wording: https://sketch.com/s/c0480bf8-3e77-43dc-a097-65a0841bb418

**Comment by austinjprice** [comment]
@nnicholas7 to close out once final approval from CAIA

**Comment by nnicholas7** [comment]
Update: Received feedback from CAIA on content.  They provided the following revision:
Here's the revised copy:

[H2] We're confirming your Intent to File

When you start a claim for disability benefits online, we record your Intent to File. This sets a potential start date for your benefits. Your Intent to File date resets after one year.

**If you already have an Intent to File**, we'll continue to hold that date as the potential start date for your benefits.

**If you don't already have an Intent to File**, we'll use today as the potential start date for your benefits.

You don't need to do anything else to notify us of your Intent to File. You can continue to file your claim.

The updated language and Sketch file can be found here: https://sketch.com/s/c0480bf8-3e77-43dc-a097-65a0841bb418

**Comment by nnicholas7** [comment]
Updated Figma Link to content changes: https://www.figma.com/file/UwtB1FUdCQUPtUx7AtpRiB/526-ITF-Error-Message?type=design&node-id=0%3A1&mode=design&t=WJr06Vh4o0LgHrtE-1

Mural board link to ITF Asycn Flow: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1700602283685/fef07188052ef83487d76762990509d0619626d6?sender=u813bb40bd648bc2b58599242

**Comment by sortizsh** [comment]
let's sync with Micah and Sam to see if they have any background info on this project and where it stands
