### ISSUE TITLE
Update to Daily accessibility scan page

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-team#66911]
### Description
After discussion and confirming that I was the only one actively monitoring the Daily scan, we decided to turn this off. This was not delivering very consistent results and it was also failing consistently due to runners and such. The AP team will be building a new, more stable scan with the work they are doing. For now, I think the Daily scan page should be updated to reflect current status. A couple options:

- Remove the page entirely
- Add a notice/update on the page to indicate that it is currently not running. Something similar to:

> For technical reasons within content-build, the daily accessibility scan has been temporarily turned off. A new, more stable scan is being built and will be available once completed.

### Relevant URLs
Daily scan page: https://depo-platform-documentation.scrollhelp.site/developer-docs/daily-accessibility-scan-for-va-gov-static-content#Pagefooter-Helpandfeedback

### Which type of team are you on? (Platform team, VFS team, or Leadership)
I'm on the CMS Team which is both Platform and VFS team. PO is @EWashb

**Comment by vbellissimo** [comment]
Hi @laflannery , thank you for letting us know. Our team is taking a look and will be updating this soon.

**Comment by taylojill** [comment]
Hi there @laflannery I added a note with the update at the top of the page. Please review the attached pdf and let me know if this works. Once approved we will publish the updated page. 
cc @vbellissimo @alyssagallion 
[Copy of Daily accessibility scan for VA.gov static content-161023-131939.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3c3QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--891463bb41158ae4b913091af76e0be271957b26/Copy%20of%20Daily%20accessibility%20scan%20for%20VA.gov%20static%20content-161023-131939.pdf)

**Comment by laflannery** [comment]
Thanks @taylojill, this looks good to me!

**Comment by taylojill** [comment]
Paged updated, checked for launch blocking issues. Ready for deployment.
