### ISSUE TITLE
Usability Testing Prep - IA Feedback - BDD

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#6692]
IA Feedback for the upcoming BDD research:

1. In the first research task, when assessing where users will look for this content, please refrain from using "service member" in the question.  Possible rephrasing could be: 
  - You have heard of a program that allows ~active Service Members~ _you_ to apply to get benefits from the VA for a specific disability, prior to separation. The advantage of doing this is that you would receive payments sooner after separating from service. Someone told you that you could apply to this program on VA.gov.

2. Breadcrumb of how to apply page is inaccurate - if this will be a modification to the existing disability comp how to apply page, breadcrumb should be  Home > Disability benefits > How to file a claim

3.  If #2 is true, this page should also include the disability left hand nav similar to this page:  https://www.va.gov/disability/how-to-file-claim/

4. Breadcrumb of first page of application should be Home > Disability benefits > File for disability compensation

5. The initial page of the current 526 requires you to sign in (there is a blue button that says "Sign in to start your application", will they be able to complete this application without signing in? https://www.va.gov/disability/file-disability-claim-form-21-526ez/introduction

6. This page will need to be considered as part of your experience.  It may not need to be included in the research, but entry points from this page may need to be updated: https://www.va.gov/disability/how-to-file-claim/when-to-file/pre-discharge-claim/

**Comment by chrvalla** [comment]
Thank you for your helpful comments. The link on page/state 6 in the prototype
https://vsateams.invisionapp.com/d/main?origin=v7#/console/19488153/407963581/preview?scrollOffset=0
(Learn more about BDD....) will link to this page: 
https://www.va.gov/disability/how-to-file-claim/when-to-file/pre-discharge-claim/

I think I will include this in the usability testing, for context. 

I have asked Andrea about your comment 5. Will fix all the other issues today. 

Thank you again!

Best, Christian

**Comment by chrvalla** [comment]
Hello.  I have a question: in the New Claims (that we are basing BDD off), the breadcrumb on this page
https://www.va.gov/disability/how-to-file-claim/

the breadcrumb is -- Home > Disability benefits > File for increased disability

In the comment you suggested -- Home > Disability benefits > How to file a claim

Is the latter the one I should use?

Thank you!

**Comment by mnorthuis** [comment]
Yes, use the one I recommended, it appears production breadcrumb is incorrect, so I have a note to track that down.  Thanks for checking!

**Comment by chrvalla** [comment]
All of these changes have been implemented in the BDD prototype on 8th April 2020.
