### ISSUE TITLE
Document Upload Test Plan and Execution

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#66945]
## Overview

I'm confident I've addressed all known areas of the Form 526 flow connected to document uploads, and implemented an early verison of Lighthouse support for them.

However, as this is all essentially a process of discovery and there are several other systems involved/a sandbox and staging environment, the best way to go about preparing for a release is to start trying to test my changes and identify how we would create a more formal testing plan.

## Open Questions
- [ ] Are there any stakeholders we can talk to about testing who know what we need to verify to feel safe about launching this?
- [ ] Has the mobile team tested their flows manually end to end? What was their strategy?
- [ ] Can we get documents through end-to-end by testing locally?
- [ ] How close can we get to adequately testing this without a small and dangerous rollout to production?
- [ ] Are we at a stage where we can test an actual submission, along with the document uploads, or do we need to test these follow up jobs separately? Is that even possible?

## Acceptance Criteria (perhaps multiple sprints)
- [ ] Review scope of changes I'll be testing and what it takes to set up a manual test for each
- [ ] Review provided Lighthouse Sandbox users, staging users and testing setup/limitations
- [ ] Confirm a successful submission of each of these jobs should end up in an eFolder and we can access one in staging
- [ ] Get into VBMS/wherever we can view the eFolder
- [ ] Identify stakeholders who can provide context on the submission process/sanity check a testing plan
- [ ] Ask Team 1 if have any questions about working with sandbox
- [ ] Revisit automated testing: can we improve draft tests with VCR recordings? Can we handle error states?

**Comment by austinjprice** [comment]
@NB28VT Can we add acceptance criteria that can help scope this prior to planning

**Comment by NB28VT** [comment]
@austinjprice had a chance to think this through today, this should give us a roadmap to start with.

Note this may spread across sprints/co-assemble, and we may end up splitting tickets into three phases:
1. Discovery of just how we would go about testing all of this (this ticket)
2. Writing up a detailed testing plan with the help of stakeholders/research folks 
3. Executing that testing plan (sort of wrapped into the rollout plan)

**Comment by sortizsh** [comment]
closing this as the ticket needs to be reworked
