### ISSUE TITLE
Usability Testing Prep - Content review- BDD form 

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#6695]
## User story

VSP Content feedback on BDD section of 526EZ form  (Usability Testing Prep stage)

Template prototype we're reviewing: https://vsateams.invisionapp.com/share/Z8W8ACWN3UG#/

## Content feedback
High-level content feedback is documented below in the ticket. i've also made more granular edit recommendations (style, capitalization) in the mockup comments. 

Screen 1
**How to apply page**
--Is this first screen showing the "How to Apply" static page? If so, it's not matching the current live page now. (breadcrumbs, and other content is missing from this page)
--Also the Back and Continue buttons at the bottom of the screen make it seem like this page is part of the application. 

Screen 6 
**Introduction page** 
1. How does the BDD form integrate with the 526 form? Is the BDD form going to be a standalone form or integrated with the 526EZ? 

On the introduction page, step 1 "Prepare" talks more generally about filing a disability claim, but Step 2 "Apply" talks specifically about BDD. I think this can be confusing to users about where they are and how the two forms are related.

Also the header on the introduction page says "File for disability compensation", but the header on the next screen header is "File for Benefits Delivery at Discharge" 

Do we need to have a separate introduction page for the BDD or could we include a link from the current 526EZ introduction page that will take users to the BDD form? 

2. We shouldn't abbreviate service members (SM).. this should be spell out throughout. 

3. I recommend we link to this page either on static page or introduction page to give more information at BDD eligibility (https://www.va.gov/disability/how-to-file-claim/when-to-file/pre-discharge-claim/)

Where does this link [Learn more about Benefits Delivery at Discharge] go? 

4. Per intro page template (https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/content/form-introduction-page-template.md) 
This page is missing the Sign in message 
and 
**What if I need help filling out my application?** message
 An accredited representative, like a Veterans Service Officer (VSO) can [help you fill out your claim](https://www.va.gov/disability/get-help-filing-claim/).

5. CTA button should say "Sign in to start your application" as I believe users need to sign into to use the 566EZ form or anything related to disability benefits.  

6. Footer at bottom of the page isn't the most recent. 

**Screen 9**
How does this contact information screen interact with the current 526 contact screen? Is the BDD form going to live within the 526? If so, then I don't think we need another contact information screen. 

**Confirmation page screen**
I recommend a larger conversation about the confirmation page, depending on if the BDD form is a standalone form or if it will be part of the 526. 

If it's part of the 526, then we should consider using the current 526 confirmation page and adding information about the BDD process to that page, rather than create another confirmation page.

**Comment by chrvalla** [comment]
Hi Peggy

Thank you for your very helpful comments :)

I have made many of the changes you mentioned. 

With regards to comment 3 - the link is suppose to link to the page you mentioned. I think I will include this in the prototype. 

I will discuss the remaining points with Luke and Andrea. 

Best, 

Christian

**Comment by peggygannon** [comment]
Hi, @chrvalla here are additional content recommendations, based on our call yesterday 3/17. I've also added them to the update mockup

1. on the static File a disability claim page, update the CTA button to say: 
File a Benefits Delivery at Discharge claim

Update alert to say: 
**You may be eligible to file a Benefits Delivery at Discharge claim**
Based on your answers, you may be eligible to file a disability compensation claim through the Benefits Delivery at Discharge (BDD) program. This program allows service members to apply for compensation before they leave the military. 

[Learn more about the BDD program](https://www.va.gov/disability/how-to-file-claim/when-to-file/pre-discharge-claim/). 

2. on introduction page
Please update first paragraph to: 

**Benefits Delivery at Discharge program**
Service members who have an illness or injury that was caused—or made worse—by their active-duty service, can file a claim for disability benefits 180 to 90 days before they leave the military through the Benefits Delivery at Discharge (BDD) program.
[Learn more about the BDD program](https://www.va.gov/disability/how-to-file-claim/when-to-file/pre-discharge-claim/).

**Comment by chrvalla** [comment]
All of these changes have been implemented in the BDD prototype on 8th April 2020.
