### ISSUE TITLE
Research transition from Central Mail API to Lighthouse for Pension

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#66956]
## Issue Description

As a new Pension team,
we need to understand how to transition from Central Mail API to Lighthouse API,
so that when we relaunch the Pension form, it is using the recommended API approach.

_How might we start transitioning from Central API to Lighthouse API?_

Notes:

- Lighthouse is understood by the non-disability benefits team, but only place it exists is the 526 form.

---
## Tasks
- [ ] Research the current state of the Pension form using Central Mail API
- [ ] Research how might we transition from Central Mail API to Lighthouse 

## Artifacts

Not sure if this is what was intended, but with using the changes to 526 as a template, the approach is at least mapped out. There is some new functionality to implement in Lighthouse to replace all that CentralMail is doing - mostly surrounding claim DELETE and PDF creation.

https://github.com/department-of-veterans-affairs/vets-api/pull/14057/files

CentralMail-Lighthouse.md

**Comment by mjknight50** [comment]
@wayne-weibel is working on this

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/66956?planning-poker) with Zenhub @mjknight50 @TaiWilkin @ToddWebDev

**Comment by wayne-weibel** [comment]
Not sure if this is what was intended, but with using the changes to 526 as a template, the approach is at least mapped out.  There is some new functionality to implement in Lighthouse to replace all that CentralMail is doing - mostly surrounding claim DELETE and PDF creation.

[CentralMail-Lighthouse.md](https://github.com/department-of-veterans-affairs/va.gov-team/files/13079079/CentralMail-Lighthouse.md)

**Comment by vbellissimo** [comment]
Next steps: Have Matt take a look at this. Not on vets-website.
