### ISSUE TITLE
Address Validation modal does not handle failure to create address save transaction

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#6696]
Upon selecting an address from the Address Validation modal, a call to create the initial save transaction (to either POST or PUT `profile/addresses`) is made. If that call fails, the Address Validation modal does not present any sort of error message. Instead the modal just remains open with no indication that something went wrong.

![validation-error.gif](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/d938fd48-7d63-4358-a881-881de95cfa4f)

I tested this locally by mocking a failure response.

I added this to the `local-vet360.js`:

```
createTransactionFailure() {
  return asyncReturn(
    {
      errors: [
        {
          title: 'Service unavailable',
          detail: 'Backend Service Outage',
          code: '503',
          status: '503',
        },
      ],
    },
    1000,
  );
}
```
and used it in the `createTransaction()` method in the `transactions.js`:

`await localVet360.createTransactionFailure();`

## Expected behavior
We should show an error at the top of the Validation Modal, similar to how the Vet360EditModal uses a Vet360EditModalError if there was an error in creating the transaction request: https://github.com/department-of-veterans-affairs/vets-website/blob/534603f4db76c4f360ef1bd051a8f3d6de764438/src/platform/user/profile/vet360/components/base/Vet360EditModal.jsx#L127-L135

**Comment by Samara-Strauss** [comment]
@erikphansen is this something that needs to be completed before launch or implemented after launch? I am assuming we should launch with this functionality. Just taking inventory of what's left so we can set a launch date.

**Comment by erikphansen** [comment]
We should wait to launch until it's added. I'm gonna work on this after the demos. I already fixed it locally as part of my much larger refined profile save refinement so I suspect I'll have a PR up pretty quickly. But I do have a wall of meetings today. Anyway, it's next in my queue.

**Comment by Samara-Strauss** [comment]
Got it! Ok, just wanted to confirm. It's been added for sprint 17 (starting tomorrow). Thanks!

**Comment by erikphansen** [comment]
a PR for this has been merged. I'm gonna close this as it's not feasible to validate it in staging since it will only be shown if there's a server error.
