### ISSUE TITLE
Pre-survey for Proofing Agent Onsite Testing

### ISSUE THREAD

**Issue by lmorris3** [department-of-veterans-affairs/va.gov-team#66971]
Context
For the IPP pilot, SSiT needs to understand the awareness and comfort VA staff have prior to the start of the pilot to then understand the impact of the pilot on awareness and comfort

AC:
- [x] Word doc created
- [x] Thank you message explaining purpose of survey (to help improve this service and ease of use for VA staff which ultimately benefits Veterans), reminder they will take a post survey
- [x] Are you familiar with identity verification? 5 pt likert scale and text box for explanation
- [x] What is your level of confidence using application? 5 pt likert scale and text box for explanation
- [x] What is your level of confidence explaining purpose to Veterans of IPP service? 5 pt likert scale and text box for explanation
- [x] What was level of ease using application?5 pt likert scale and text box for explanation
- [x] How confident are you that you would be able to help a Veteran complete this service again? 5 pt likert scale and text box for explanation
- [x] How does this compare to other services you provide? Similar 5 pt likert scale and text box explanation
- [x] How confident are you that other VA staff could use this application and help a Veteran complete IPP? 5 pt likert scale and text box for explanation
- [x] Closing thank you message

**Comment by SophiaPhilipMO** [comment]
[Pre-Survey for VA Staff](https://docs.google.com/document/d/1GH4bp2LghJtMiRqBC8ScHVLbs6EXTwi_Sb_UqQR-eXg/edit)

**Comment by skirkman16** [comment]
Reviewed and left comments

**Comment by lmorris3** [comment]
Reviewed and commented on both pre- and post-surveys.

**Comment by SophiaPhilipMO** [comment]
Edits completed
