### ISSUE TITLE
Exit strategy for IPP Pilot On-Site Testing

### ISSUE THREAD

**Issue by skirkman16** [department-of-veterans-affairs/va.gov-team#66974]
Context
Research team needs exit strategies for key moments identified throughout pilot for VA staff or Veterans to ensure the participants experience no distress or harm during the pilot. 

User Story
As a Veteran/VA staff member, I should have support at any point in the pilot so that I do not experience distress at any point. 

AC:
- [x] Script for when Veteran does not bring required documentation
- [x] Script for when Veteran does not bring personal device to login to email
- [x] Script for when Veteran is not able to login to email
- [x] Script for when Veteran is frustrated but not overwhelmed and offering an option to pause or exit
- [x] Script for when Veteran is overwhelmed and offering an option to pause or exit
- [x] Script for when VA staff is frustrated but not overwhelmed and offering an option to pause or exit
- [x] Script for when VA staff is overwhelmed and offering an option to pause or exit
- [x] All strategies in [research plan](https://docs.google.com/document/d/14YplbTXAcj47wu71slKFMfqrhHnxH8SzllLa7N2cPkM/edit#heading=h.iqf7ky9mbrd0)

**Comment by lmorris3** [comment]
This is complete and can be reviewed and closed. @SophiaPhilipMO

**Comment by SophiaPhilipMO** [comment]
[Educational materials](https://docs.google.com/document/d/11fsQ-X5QqWzvzf-IbzJlDIuuWCyiqtyvEQ5JnC5JwTg/edit) for exit plan

**Comment by SophiaPhilipMO** [comment]
@CarlDickerson I was able to add a script to almost all scenarios, they need refinement in wording to ensure comfort is provided, clarity is given to the researcher on what to do next and if the back up plan seems feasible

**Comment by SophiaPhilipMO** [comment]
@lmorris3 ready for review

**Comment by lmorris3** [comment]
Reviewed and edited/commented!
