### ISSUE TITLE
Initial Draft of Literature Review

### ISSUE THREAD

**Issue by lmorris3** [department-of-veterans-affairs/va.gov-team#66970]
Context
As a Veteran, previous research has been reviewed to inform existing and new services for identity verification.

AC:
A literature review of LGA and non LGA research that informs the decision making around the development and implementation of the IPP pilot and prototype.

Definition of Done:
- [x] Initial draft of literature review
- [x] Examples featured from #66972 and #66976

**Comment by SophiaPhilipMO** [comment]
https://docs.google.com/document/d/1J5CF9aMbOL4AVEUfloYqbW7ZIYRWvEGVCMYU1ijXSm4/edit?usp=sharing
