### ISSUE TITLE
Draft Post-survey for Proofing Agent Onsite Testing

### ISSUE THREAD

**Issue by lmorris3** [department-of-veterans-affairs/va.gov-team#66973]
Context
For the IPP pilot, SSiT needs to understand the awareness and comfort VA staff have after the pilot sessions to then understand the impact of the pilot on awareness and comfort

AC:
- [x] Word doc created
- [x] Thank you message explaining purpose of survey (to help improve this service and ease of use for VA staff which ultimately benefits Veterans), reminder that these will be same questions as pre survey
- [x] Are you familiar with identity verification? 5 pt likert scale and text box for explanation
- [x] What is your level of confidence using application? 5 pt likert scale and text box for explanation
- [x] What is your level of confidence explaining purpose to Veterans of IPP service? 5 pt likert scale and text box for explanation
- [x] What was level of ease using application?5 pt likert scale and text box for explanation
- [x] How confident are you that you would be able to help a Veteran complete this service again? 5 pt likert scale and text box for explanation
- [x] How does this compare to other services you provide? Similar 5 pt likert scale and text box explanation
- [x] How confident are you that other VA staff could use this application and help a Veteran complete IPP? 5 pt likert scale and text box for explanation
- [x] Closing thank you message

**Comment by SophiaPhilipMO** [comment]
[Post Survey](https://docs.google.com/document/d/1yPuIwRH4MiKvtf-EEMRDC9f1Ql4Epi7UUnaYVUUURPY/edit)

**Comment by SophiaPhilipMO** [comment]
Edits completed
