### ISSUE TITLE
MHV landing page to 100% for everyone

### ISSUE THREAD

**Issue by LynneJohnson224** [department-of-veterans-affairs/va.gov-team#66985]
Placeholder:  Flip the feature toggle to "enabled for everyone" which is slightly different than "enabled for 100% of logged in users" (current setting). basically it allows unauthenticated users to reach the va.gov/my-health path where they theoretically would be asked to sign in. but we need to test out that assumption in staging.

**Comment by MikeC-A6** [comment]
I'm wondering if there is an opportunity to re-use the landing page content for unauth users similarly to how are leveraging it for auth users without a healthcare registration history. @wesrowe let's think about crafting a user story that captures something broader than this one, in a way that will allow us to think creatively about how to handle unauth users.

**Comment by wesrowe** [comment]
@MikeC-A6, do you think this story is worth doing, just to see what happens? (The "theoretical" part above.) 

Note: I asked the team via slack whether they have documented any flows that might lead to `/my-health/` without logging in first. (Aside from URL hacking.) If you have any context, please share.

**Comment by MikeC-A6** [comment]
@wesrowe I think a spike here might be useful.  Potential outcome: we have a recommendation as to if we should expose the my-health link in the header for unauth users on VA.gov, and if so, should we do it now?

**Comment by wesrowe** [comment]
Note: Wrote a discovery spike intended to include the question of the unauth header: #68427.

**Comment by wesrowe** [comment]
closing in favor of a broader unauth-landing-page ticket, #68427.
