### ISSUE TITLE
Vets-api terminal access for Michael Moyer

### ISSUE THREAD

**Issue by mmoyer-va** [department-of-veterans-affairs/va.gov-team#66983]
### Your Name

Michael Moyer

### Your GitHub handle (terminal access is managed through GitHub)

@mmoyer-va

### Your dsvagovcloud AWS user name (if applicable)

Michael.Moyer

### Team, Role, and Company of the target individual

MHV medical records, software engineer, By Light Professional IT Services

### Product Manager (PM) name and email

Lichelle Bain - lichelle.bain@va.gov

### Product Owner (PO) name and email

Patricia Henry - Patricia.Henry@va.gov

### COR Name (leave "None" if you listed an AWS user name above)

None

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

None

### Please confirm if you are on the VFS Team Roster or Platform Team Roster

- [X] [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Please confirm E-QIP Transmittal/Adjudication. This could be a screenshot of your Transmittal/Adjudication email, a link to another request where you've submitted this proof (i.e. AWS/SOCKS), etc.

- [X] I have attached proof that I have either transmitted my E-QIP survey or previously received a favorable decision (by including in "Additional Notes" section below)

### ArgoCD terminal access requested for the following environments

- [ ] dev
- [ ] staging
- [ ] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### Additional Notes

Prod Justification: I recently configured the fwdproxy for Medical Records app for the production environment. I would just like to verify that the configuration was successful via accessing the terminal and running "env" and "curl" commands. I would only need this access for a limited time. A week would be plenty.

<img width="903" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/87040148/571e2175-612e-428b-8bb8-9f64cc946fa1">

### Additional resources for Support Engineer

- [ ] For users on a VFS team but not in the VFS Team Roster, they must start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] Instructions for handling requests [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access) - Support Only

**Comment by IsaiahMW1** [comment]
@mmoyer-va You’ve been granted access to production

**Comment by jikamens** [comment]
This is approved. Please make sure to circle back weith Michael in a week to see if he is finished with the access. If so, please revoke it. If not, then an extension of up to another two weeks is approved, after which please circle back with OCTODE if he still needs access and we'll reevaluate. Thank you!

**Comment by IsaiahMW1** [comment]
@jikamens Thank you ! and No problem !, @mmoyer-va You’ve been granted access to the Production Environment.
