### ISSUE TITLE
686 Foreign Base Address Discrepancy

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#66996]
## Issue Description
_Additional validation was added to the downstream VBMS system that is causing null claims if the foreign address flag appears on the claim but the postal code entered does not match the range of foreign base codes._

---
## Tasks
- [ ] Update front-end error messaging based on this [Sketch file](https://www.sketch.com/s/870d13d5-a465-48a3-acc2-32682ba8f780)
- [ ] Add postal code validation. If the foreign address box is selected, the postal code entered must coincide with a APO/FPO/DPO postal code:
```
if (cityname is one of APO/FPO/DPO OR mlty_postal_type_cd is one of AA/AP/AE )
{    if mlty_postal_type_cd is AA, first three characters of zipCode should be 340 else reject transaction if mlty_postal_type_cd is AE, zipCode range should be (090-099) else reject transaction if mlty_postal_type_cd is AP, zipCode range should be (962-966) else reject transaction  }

```

Requirements update: If the Veteran has selected `My mailing address is outside the United States on a U.S. military base` then all 3 zip code validations should be applied. 

## Acceptance Criteria
- [ ] Error messaging appears to user
- [ ] Selecting the foreign address checkbox and entering in a non-APO/DPO/FPO postal code displays an error to the user and prevents submission
---

**Comment by evansmith** [comment]
@jstrothman @ajialeilani Should there be specific language in the validation for the zipcode requirement of: `{    if mlty_postal_type_cd is AA, first three characters of zipCode should be 340 else reject transaction if mlty_postal_type_cd is AE, zipCode range should be (090-099) else reject transaction if mlty_postal_type_cd is AP, zipCode range should be (962-966) else reject transaction  }` that isn't currently featured in the Sketch?

**Comment by jstrothman** [comment]
As background, the [Design System address pattern page error messages section](https://design.va.gov/patterns/ask-users-for/addresses#error-message-templates-for-addresses) doesn't have error messages specific to addresses outside the US.

The closest thing is: 
**When a postal code can’t be correct:**
Say ‘Please provide a valid postal code.’

I propose:
> Because your address is outside the United States on a military base, please provide an APO/FPO/DPO postal code."

@ajialeilani Would you ask CAIA? (I'm not sure if this needs a separate CAIA support ticket.)

**Comment by steele-lm** [comment]
@tblackwe I agree. Priority should be on preventing delays. I'll draft a follow-on ticket for the page split.

**Comment by steele-lm** [comment]
Separate address and contact info sections in #67568

**Comment by ajialeilani** [comment]
@evansmith @jstrothman Just want to confirm before passing on to CAIA - Is the messaging "Because your address is outside the United States on a military base, please provide an APO/FPO/DPO postal code." distinct from "If your mailing address is an AFO/FPO/DPO address, enter the postal code for the military base."? Is this the error message it would adapt/be added to? 
<img width="552" alt="Screen Shot 2023-10-13 at 11 28 57 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/127963233/6fba3a4f-f40b-4477-96d7-d6873c48da57">

**Comment by evansmith** [comment]
@ajialeilani The error message would be on the Postal Code but it would appear specifically when the format of the postal code didn't match the requirements once AA/AE/AP were chosen.

**Comment by jstrothman** [comment]
Sorry, now I'm confused. The error message @ajialeilani has in the mock seems like it should address the situation of when the AA/AE/AP is chosen, and we should use that as planned. @evansmith Should we talk in slack or by voice about why the error message in the mock doesn't address that situation?

**Comment by jstrothman** [comment]
@evansmith If we don't already handle postal code entries that start with APO AA/APO AE/FPO AP, I wonder if we should. I see that the [USPS explainer](https://pe.usps.com/text/pub28/28c2_010.htm) says these should be included

**Comment by evansmith** [comment]
@jstrothman I was able to add those validations for the respective AP/AE/AA formats. I can roll that back if we need to. For now if an AE code is entered for AP I'll display the error: "Because your address is outside the United States on a military base, please provide an APO/FPO/DPO postal code." (based on slack comments). Does that sound right?

**Comment by jstrothman** [comment]
@evansmith I get that the error message could be more specific to acknowledge when a person submits a valid code for a US military base in a different region, but I think we can start here.
