### ISSUE TITLE
[Design] QA Designs in Staging 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#6699]
QA Staging for adherence to Designs https://vsateams.invisionapp.com/share/6MVTG94WNH5#/screens

**Comment by rileyorr** [comment]
My notes from yesterday's meeting can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/meetings/20200324-mdt-staging-review.md). 
I've created all the tickets based off those notes. Feel free to reach out with any questions!
