### ISSUE TITLE
(Jamie) Discovery to identify stakeholders involved in claim processing & roles

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#67008]
## Issue Description
As a new Pension team,
I'd like to learn more about the network of job executors related to Pensions,
so that we can broaden the set of stakeholders to speak to for future research related to internal claims processing workflows

Next phase would be to (not part of this card):
- Create diagram depicting the backend process for processing Pension claims.
- Identify the stakeholders involved and determine a plan to recruit them.

---
## Tasks

- Determine the network of folks involved in the claims adjudication process based on what we already know (other teams' work)

## Artifacts

- Document any findings in respect of stakeholders involved in the claims processing workflow, and their roles.

**Comment by lilmashpotato** [comment]
I made a handful of connections with others at CoForma and Ad Hoc who have explored the claims process and have crafted blueprints and diagrams to document the players and processes. Both teams were documenting the medical claims process, but it's a good starting point to layer in Pensions to see where the differences are.

https://docs.google.com/document/d/11siXdoMmrcneplouXsSFhvAaNwyI1w3xvRV_6Y0jhzM/edit
