### ISSUE TITLE
Staging: Patient Should be Able to Direct Schedule

### ISSUE THREAD

**Issue by JRRoof** [department-of-veterans-affairs/va.gov-team#67002]
## Summary
_Patient is being put into the request flow when scheduling an appointment even though the clinic is configured to allow direct scheduling and the patient meets the requirements for direct scheduling_

## Specs
- Device: N/A
- Browser: N/A

## Steps to Reproduce Scenario 1
**Test User: Patientten.vaostest@id.me** 
Setup: CCM Cheyenne Audiology Set Yes Last Seen within 12 mos.  
           Patient has past audiology appointment:  Wht Audio Var2  10/26/2022@11:00  Checked Out

1. Go to: _https://staging.va.gov/my-health/appointments_
2. Select **Audiology and speech**
3. Select **VA medical center or clinic**
4. Select **Cheyenne VA Medical Center**

### Actual Result
_Veteran dropped into Request flow and not given option to direct schedule.
Backend calls show direct scheduling eligibility = true and returns a clinic that is configured for direct scheduling._

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVlOQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f14b3f7e481527064ad7469f9af92e3b4b0da180/image.png)

```
https://staging-api.va.gov/vaos/v2/eligibility?facility_id=983&clinical_service_id=audiology&type=direct

{
    "data": {
        "id": "a6e6",
        "type": "patient_metadata",
        "attributes": {
            "decisionDate": "2023-10-05T12:54:18.539867288Z",
            "clinicalServiceId": "audiology",
            "type": "direct",
            "eligible": true,
            "id": "a6e6"
        }
    }
}

https://staging-api.va.gov/vaos/v2/locations/983/clinics?clinical_service=audiology

{
    "data": [
        {
            "id": "570",
            "type": "clinics",
            "attributes": {
                "vistaSite": 983,
                "id": "570",
                "serviceName": "CHY C&P AUDIO",
                "physicalLocation": null,
                "phoneNumber": null,
                "stationId": "983",
                "stationName": "CHYSHR-Cheyenne VA Medical Center",
                "primaryStopCode": 203,
                "primaryStopCodeName": "AUDIOLOGY",
                "secondaryStopCode": 450,
                "secondaryStopCodeName": "COMP & PENS (C&P) EXAMS",
                "patientDirectScheduling": false,
                "patientDisplay": true,
                "char4": null
            }
        },
        {
            "id": "947",
            "type": "clinics",
            "attributes": {
                "vistaSite": 983,
                "id": "947",
                "serviceName": "CHY C&P AUDIO JAN",
                "physicalLocation": "C&P OFFICE",
                "phoneNumber": null,
                "stationId": "983",
                "stationName": "CHYSHR-Cheyenne VA Medical Center",
                "primaryStopCode": 203,
                "primaryStopCodeName": "AUDIOLOGY",
                "secondaryStopCode": 450,
                "secondaryStopCodeName": "COMP & PENS (C&P) EXAMS",
                "patientDirectScheduling": null,
                "patientDisplay": null,
                "char4": null
            }
        },
        {
            "id": "1014",
            "type": "clinics",
            "attributes": {
                "vistaSite": 983,
                "id": "1014",
                "serviceName": "Friendly Name Audiology",
                "physicalLocation": null,
                "phoneNumber": null,
                "stationId": "983",
                "stationName": "CHYSHR-Cheyenne VA Medical Center",
                "primaryStopCode": 203,
                "primaryStopCodeName": "AUDIOLOGY",
                "secondaryStopCode": null,
                "secondaryStopCodeName": null,
                "patientDirectScheduling": true,
                "patientDisplay": true,
                "char4": null
            }
        },
        {
            "id": "1022",
            "type": "clinics",
            "attributes": {
                "vistaSite": 983,
                "id": "1022",
                "serviceName": "TOR C&P LORI",
                "physicalLocation": null,
                "phoneNumber": null,
                "stationId": "983",
                "stationName": "CHYSHR-Cheyenne VA Medical Center",
                "primaryStopCode": 203,
                "primaryStopCodeName": "AUDIOLOGY",
                "secondaryStopCode": 450,
                "secondaryStopCodeName": "COMP & PENS (C&P) EXAMS",
                "patientDirectScheduling": null,
                "patientDisplay": null,
                "char4": null
            }
        },
        {
            "id": "1072",
            "type": "clinics",
            "attributes": {
                "vistaSite": 983,
                "id": "1072",
                "serviceName": "WHT HEARING AID LORI",
                "physicalLocation": "WHEATLAND",
                "phoneNumber": null,
                "stationId": "983",
                "stationName": "CHYSHR-Cheyenne VA Medical Center",
                "primaryStopCode": 203,
                "primaryStopCodeName": "AUDIOLOGY",
                "secondaryStopCode": 449,
                "secondaryStopCodeName": "FITTING & ADJSTMNTS 2ND ONLY",
                "patientDirectScheduling": null,
                "patientDisplay": null,
                "char4": null
            }
        }
    ]
}
````
### Desired Result
_Veteran dropped into Direct Schedule flow and Friendly Name Audiology displays to veteran for direct scheduling_

## Steps to Reproduce Scenario 2
**Test User: kidys.b.quankep@id.me** 
Setup: CCM Cheyenne Audiology Set Yes Last Seen within 12 mos.  
           Patient has past audiology appointment:  Chy Audiology             10/15/2021@08:00      Checked Out

1. Go to: _https://staging.va.gov/my-health/appointments_
2. Select **Audiology and speech**
3. Select **VA medical center or clinic**
4. Select **Fort Collins** (has clinics configured for direct scheduling)

### Actual Result
_Veteran dropped into Request flow and not given option to direct schedule.
Backend calls show direct scheduling eligibility = true and returns a clinic that is configured for direct scheduling._

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejBOQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c38e3eeb6e423dcb065385790e29d64b93601faf/image.png)

```
https://staging-api.va.gov/vaos/v2/eligibility?facility_id=983GC&clinical_service_id=audiology&type=direct

{
    "data": {
        "id": "5f2a",
        "type": "patient_metadata",
        "attributes": {
            "decisionDate": "2023-10-05T12:40:55.040306114Z",
            "clinicalServiceId": "audiology",
            "type": "direct",
            "eligible": true,
            "id": "5f2a"
        }
    }
}

https://staging-api.va.gov/vaos/v2/locations/983GC/clinics?clinical_service=audiology
 
{
    "data": [
        {
            "id": "945",
            "type": "clinics",
            "attributes": {
                "vistaSite": 983,
                "id": "945",
                "serviceName": "C&P BEV AUDIO FTC",
                "physicalLocation": "FORT COLLINS AUDIO",
                "phoneNumber": null,
                "stationId": "983GC",
                "stationName": "CHYSHR-Fort Collins VA Clinic",
                "primaryStopCode": 203,
                "primaryStopCodeName": "AUDIOLOGY",
                "secondaryStopCode": 450,
                "secondaryStopCodeName": "COMP & PENS (C&P) EXAMS",
                "patientDirectScheduling": true,
                "patientDisplay": true,
                "char4": null
            }
        }
    ]
}

```
### Desired Result
_Veteran dropped into Direct Schedule flow and Friendly Name Audiology displays to veteran for direct scheduling_

## Definition of Done
- [ ] Desired result is achieved and/or document decisions made
- [ ] Relevant documentation is updated

---
## How to configure this issue
- [ ] **Labeled with Team** (`vaos`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `design`, `product`)
- [ ] **Labeled with** `Bug`
- [ ] **Assigned to** Product for prioritization

**Comment by JRRoof** [comment]
We will need assistance from the SPL team to configure the test data.

**Comment by jenniemc** [comment]
### Scenario 1
**Could not reproduce issue. User is correctly dropped into the DS flow as expected.** 


VAS Setup: Cheyenne Audiology Set Yes Last Seen within 36 mos.
PatientTen > Audiology > Cheyenne VAMC
2 out of 6 clinics returned have `patientDirectScheduling` = `true`
Only Wheaton Audiology was visited in the past 36months

![Image](https://github.com/user-attachments/assets/334dbb68-f0bb-43d6-9e8a-92b59f5d1657)


### Scenario 2
**Could not reproduce issue. User not eligible for DS or Request because of there hasn’t been a recent visit in the last 12 months**


VAS Setup: Ft. Collins Audiology Set Yes Last Seen within 12 mos.
Kidys > Audiology > Ft. Collins

```
{
    "decisionDate": "2024-11-21T22:06:42.162855692Z",
    "clinicalServiceId": "audiology",
    "type": "direct",
    "eligible": false,
    "ineligibilityReasons": [
        {
            "coding": [
                {
                    "code": "patient-history-insufficient",
                    "display": "patient history requirements not met"
                }
            ]
        }
    ],
    "id": "13e0"
}
```

### Scenario 3
**User eligible for direct schedule but put into request flow because there were no clinics returned**


VAS Setup: Ft. Collins MOVE Program Set Yes Any Veteran (no history requirement).
Judy Morrison > MOVE Program >ft Collins

_User eligible for direct schedule_  

```
https://staging-api.va.gov/vaos/v2/eligibility?facility_id=983GC&clinical_service_id=moveProgram&type=direct
{
    "decisionDate": "2024-11-21T21:14:20.397196282Z",
    "clinicalServiceId": "moveProgram",
    "type": "direct",
    "eligible": true,
    "id": "fe62"
}
```

_But diverted into request flow because there were no clinics returned_

```
https://staging-api.va.gov/vaos/v2/locations/983GC/clinics?clinical_service=moveProgram
{
    "data": []
}
```


@cferris32  confirmed that the clinic api call are straight passes through from VAOS Service. 

Also posted a question in the [Appointment-Team slack](https://dsva.slack.com/archives/CMNQT72LX/p1732139527987759) for confirmation that there are no Ft. Collins clinic configured for direct schedule for the MOVE program

**Comment by jenniemc** [comment]
@outerpress, Ready for validation. I cannot reproduce the bugs. 

- In scenario 1, the user is correctly dropped into the direct schedule flow. 
- In scenario 2, the user is ineligible for direct schedule and  because there hasn’t been a recent visit in the last 12 months. 
- In scenario 3, the user is dropped into the request flow because there were no clinics returned.

**Comment by jenniemc** [comment]
Question to Marcy on slack to confirm why user was dropped in request flow:
>"Are any clinics configured for direct schedule for the MOVE Program at Ft. Collins?"

[Marcy's answer from slack](https://dsva.slack.com/archives/CMNQT72LX/p1732557957920949) confirming Scenario 3, "I don't have any clinics configured for Move @FTC" 

cc: @JRRoof

**Comment by jenniemc** [comment]
Close ticket
