### ISSUE TITLE
Appoint tool: Update landing page, draft introduction page, and review prototype

### ISSUE THREAD

**Issue by strelichl** [department-of-veterans-affairs/va.gov-team#67015]
### Background
The accredited representative management team is designing these new products:

**1. Check your accredited representative widget:** This will help Veterans check if they have an accredited representative.
**2. Find an accredited representative tool:** This will help Veterans find attorneys, claims agents, and Veteran Service Organizations (VSOs) that serve as accredited representatives. After using this tool, the Veteran will need to contact the attorney, claims agent, or VSO to ask if they're available and willing to representative them.
**3. Appoint an accredited representative tool:** This will help Veterans appoint an attorney, claims agent, or VSO as their accredited representative by pre-filling their Form 21-22 or Form 21-22a. After using this tool, the Veteran will need to print and sign their form. Then the accredited representative will need to sign the form. Then the Veteran or accredited representative will need to submit the form online, by mail, or in person.

The team is launching the find tool first. Then they'll launch the appoint tool and check widget.

### Deliverables
For this ticket, we're committed to these deliverables:

**1. Landing page:** We need to draft the phase 2 landing page.
**2. Introduction page:** We need to draft content for the appoint tool introduction page, following content patterns for a digitized form experience.
**3. Authenticated prototype:** We need to offer content recommendations for the appoint tool prototype, which will include the check widget.
**4. Unauthenticated prototype:** We need to offer content recommendations for the unauthenticated appoint tool prototype.

### Resources
- [Content source of truth folder](https://dvagov.sharepoint.com/:f:/s/SitewideCAIA/EpKqFTllvlxOkDwz2iFgveAB9PjkKVIrJu_TUAkQPbsU0g?e=4Z39yV) (VA SharePoint)

---
### Deliverable 1: Landing page
- [x] AP: Draft landing page design
- [x] KF: Edit
- [x] AP: Share Google document with product team

### Deliverable 2: Introduction page
- [x] AP: Draft introduction page design
- [x] KF: Edit
- [x] AP: Share with product team

### Deliverable 3: Authenticated prototype
- [x] AP, KF: Leave comments in CAIA GitHub document and Sketch screens
- [x] AP: Share with product team

### Deliverable 4: Unauthenticated prototype
- [x] AP, KF: Leave comments in Sketch screens
- [x] AP: Share with product team

---
## Acceptance Criteria
- [x] Content recommendations provided to product team

**Comment by katherine-fung** [comment]
Hi @aprocik1, I've reviewed the appoint introduction page: 

https://docs.google.com/document/d/1QRHXsvfw8YXCir83QoXzGw9mrOnGUlfd6RN9sSlKuew/edit

**Comment by aprocik1** [comment]
Hi @oddball-lindsay and @mtri! Here are the content deliverables for this ticket:

- **Landing page:** This page is ready for an accuracy review from your accredited representative stakeholders. I've reserved time this week to answer their questions and implement their feedback. Here's the [Google document](https://docs.google.com/document/d/1tIdX3Y444fxG16SCdwWdVssBb5vCbLDnVGMp32sCqiw/edit?usp=sharing). And here's the [Drupal preview](https://preview-prod.vfs.va.gov/preview?nodeId=62667). You have to be on the VA network to access the preview. Links don't work on preview pages.
- **Prototype:** We've drafted recommendations for both authenticated and unauthenticated experiences. We've also drafted recommendations for the introduction and confirmation pages. Our recommendations for those pages may change depending on your feedback. At this week's check in, we can align on those pages together. And then I'll finalize the content for your user testing. Here's the [Word document](https://dvagov-my.sharepoint.com/:w:/g/personal/anthony_procik_va_gov/ESBhwaJYiI9Hs6IMoWyVwGcBMr02J_DyJwzl1Xj6w9P9cg?e=pDE0mF).

Let me know if you have any questions! Thanks for your collaboration.

**Comment by oddball-lindsay** [comment]
Thanks @aprocik1 !  I made a copy of the Google doc landing page content and exported to a PDF for our reviewers to reference: [Representative Landing Page - For Review.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/13481651/Representative.Landing.Page.-.For.Review.pdf)

I cleaned it up a little by removing most of the design element mentions as I'm not sure if our reviewers will be familiar with those content denotations.

**Comment by oddball-lindsay** [comment]
@aprocik1 here are content collab opportunities based on our research study of the Appoint authenticated flow.  Also included are some ideas from the ARM team (we had a brainstorm after research findings were presented, to ideate on potential solutions).  We have our meeting tomorrow to review, discuss, and continue to ideate -- together this time!

**On the landing page, how might we inform Veterans about what representatives do, their differences, and the processes surrounding them?**
- Ideas included:
  - Numbered process list
  - Additional info components
  - Have a step before the Find a Rep CTA that links to the FAQ

**On the widget, how might we address Veterans unawareness that VA does NOT assign representatives and / or are confused why a representative’s there?**
  - Top idea was to place a disclaimer in widget linking to FAQ

**On the permissions pages, how might we provide additional context to help users understand the legal purpose of permissions?**
  - Top idea is to work with CAIA to find an eloquent way to provide legal reasons to Veterans
    - Will want to confirm wording with stakeholders

**How might we decrease drop-off on the review & final page by addressing non-digital submissions and improving user guidance?**
  - Top ideas included:
    - More clearly setting expectations earlier in the process, especially on the ‘Fill out your form …’ page
    - Swap the ‘Print Form’ button to ‘Download’, ‘Generate Form’, or another standard confirmation page option
    - Combine steps to have 1/ Print and sign and 2/ Representative sign and submit
      - With optional information on how to submit if your representative cannot do so

Also to consider: **Can we slim down the "form landing page"?**  Current mobile experience is all headers and feels a bit redundant.

**Comment by aprocik1** [comment]
Added to sprint tracker
