### ISSUE TITLE
Fix issue for Sign up Service updater job when common name is blank

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#67028]
# Tasks

- [x] add validation to TermsOfUse::Acceptor/Decliner for `common_name`
- [x] update SignUpServiceUpdaterJob to properly log job['name'] on a retries_exhausted failure

**Comment by bosawt** [comment]
This is what the error currently looks like when common name is blank:
https://vagov.ddog-gov.com/dashboard/52g-hyg-wcj/vsp-identity-monitor-dashboard?fullscreen_end_ts=1696541883807&fullscreen_paused=false&fullscreen_refresh_mode=sliding&fullscreen_section=edit&fullscreen_start_ts=1696455483807&fullscreen_widget=620843657299146&refresh_mode=sliding&from_ts=1696454477372&to_ts=1696540877372&live=true

**Comment by bosawt** [comment]
This is what the error currently looks like when common name is blank:
https://vagov.ddog-gov.com/dashboard/52g-hyg-wcj/vsp-identity-monitor-dashboard?fullscreen_end_ts=1696541883807&fullscreen_paused=false&fullscreen_refresh_mode=sliding&fullscreen_section=edit&fullscreen_start_ts=1696455483807&fullscreen_widget=620843657299146&refresh_mode=sliding&from_ts=1696454477372&to_ts=1696540877372&live=true

**Comment by bosawt** [comment]
We should probably put a check in `TermsOfUse::Acceptor`, and `TermsOfUse::Decliner`, and prevent a user from accepting or declining terms at all if they don't have a `common_name` (I'm not sure if this will happen on production, it seems to me there should be no verified users without a first/last name)

**Comment by bramleyjl** [comment]
I've verified that the ToU `Acceptor` & `Decliner` classes have the common_name validation in staging. I'm still looking for either more [`retries exhausted`](https://vagov.ddog-gov.com/logs?query=SignUpServiceUpdaterJob%20Retries%20exhausted%20&cols=host%2Cservice&index=%2A&messageDisplay=inline&refresh_mode=sliding&stream_sort=desc&viz=stream&from_ts=1698865754964&to_ts=1699470554964&live=true) or the new [`Name for user must be present`](https://vagov.ddog-gov.com/logs?query=%22Name%20for%20user%20must%20be%20present%22%20&cols=host%2Cservice&index=%2A&messageDisplay=inline&refresh_mode=sliding&stream_sort=desc&viz=stream&from_ts=1698865804812&to_ts=1699470604812&live=true) error.

**Comment by bramleyjl** [comment]
No `Name for user must be present` errors have occurred yet, however all of the new `retries exhuasted` include a proper common name.

The Sidekiq `class` is now properly included in retries exhuasted errors:
`[TermsOfUse][SignUpServiceUpdaterJob] Retries exhausted for TermsOfUse::SignUpServiceUpdaterJob`
