### ISSUE TITLE
Toxic Exposure: Prepare artifacts for staging review 

### ISSUE THREAD

**Issue by christinec-fftc** [department-of-veterans-affairs/va.gov-team#67022]
Prep for staging review as noted [here](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/staging-review). Provide the following artifacts in the collab cycle ticket

**Product artifacts**

- [x] Staging url
- [x]  Specify which pages are included in the review
- [x]  Staging test user information

**QA artifacts**
An artifact that corresponds to each standard in the QA Standards.

- [x] Regression test plan
- [x] Test plan
- [x] E2E tests (provide a link to the product’s code)
- [x] Code coverage (provide a link to the product’s code)

**Accessibility artifacts**
- [x] Completed accessibility testing artifact

## Acceptance Criteria
Engineering
- [ ] All artifacts above are prepared so the PM can submit the staging review ticket

Product/UX
- [ ] Coverage for References
- [ ] Summary(Defects) reports

**Comment by mchae-nava** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-526EZ-toxic-exposure.md

**Comment by mchae-nava** [comment]
Raw coverage report; will link a file where needed

<!doctype html>
<html lang="en">

<head>
    <title>Code coverage report for all-claims/pages/toxicExposure</title>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="../../../prettify.css" />
    <link rel="stylesheet" href="../../../base.css" />
    <link rel="shortcut icon" type="image/x-icon" href="../../../favicon.png" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <style type='text/css'>
        .coverage-summary .sorter {
            background-image: url(../../../sort-arrow-sprite.png);
        }
    </style>
</head>
    
<body>
<div class='wrapper'>
    <div class='pad1'>
        <h1><a href="../../../index.html">All files</a> all-claims/pages/toxicExposure</h1>
        <div class='clearfix'>
            
            <div class='fl pad1y space-right2'>
                <span class="strong">100% </span>
                <span class="quiet">Statements</span>
                <span class='fraction'>88/88</span>
            </div>
        
            
            <div class='fl pad1y space-right2'>
                <span class="strong">100% </span>
                <span class="quiet">Branches</span>
                <span class='fraction'>12/12</span>
            </div>
        
            
            <div class='fl pad1y space-right2'>
                <span class="strong">100% </span>
                <span class="quiet">Functions</span>
                <span class='fraction'>55/55</span>
            </div>
        
            
            <div class='fl pad1y space-right2'>
                <span class="strong">100% </span>
                <span class="quiet">Lines</span>
                <span class='fraction'>88/88</span>
            </div>
        
            
        </div>
        <p class="quiet">
            Press <em>n</em> or <em>j</em> to go to the next uncovered block, <em>b</em>, <em>p</em> or <em>k</em> for the previous block.
        </p>
        <template id="filterTemplate">
            <div class="quiet">
                Filter:
                <input oninput="onInput()" type="search" id="fileSearch">
            </div>
        </template>
    </div>
    <div class='status-line high'></div>
    <div class="pad1">
<table class="coverage-summary">
<thead>
<tr>
   <th data-col="file" data-fmt="html" data-html="true" class="file">File</th>
   <th data-col="pic" data-type="number" data-fmt="html" data-html="true" class="pic"></th>
   <th data-col="statements" data-type="number" data-fmt="pct" class="pct">Statements</th>
   <th data-col="statements_raw" data-type="number" data-fmt="html" class="abs"></th>
   <th data-col="branches" data-type="number" data-fmt="pct" class="pct">Branches</th>
   <th data-col="branches_raw" data-type="number" data-fmt="html" class="abs"></th>
   <th data-col="functions" data-type="number" data-fmt="pct" class="pct">Functions</th>
   <th data-col="functions_raw" data-type="number" data-fmt="html" class="abs"></th>
   <th data-col="lines" data-type="number" data-fmt="pct" class="pct">Lines</th>
   <th data-col="lines_raw" data-type="number" data-fmt="html" class="abs"></th>
</tr>
</thead>
<tbody><tr>
	<td class="file high" data-value="additionalExposures.js"><a href="additionalExposures.js.html">additionalExposures.js</a></td>
	<td data-value="100" class="pic high">
	<div class="chart"><div class="cover-fill cover-full" style="width: 100%"></div><div class="cover-empty" style="width: 0%"></div></div>
	</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="3" class="abs high">3/3</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="0" class="abs high">0/0</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="1" class="abs high">1/1</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="3" class="abs high">3/3</td>
	</tr>

<tr>
	<td class="file high" data-value="additionalExposuresDetails.js"><a href="additionalExposuresDetails.js.html">additionalExposuresDetails.js</a></td>
	<td data-value="100" class="pic high">
	<div class="chart"><div class="cover-fill cover-full" style="width: 100%"></div><div class="cover-empty" style="width: 0%"></div></div>
	</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="10" class="abs high">10/10</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="2" class="abs high">2/2</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="8" class="abs high">8/8</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="10" class="abs high">10/10</td>
	</tr>

<tr>
	<td class="file high" data-value="additionalExposuresSummary.js"><a href="additionalExposuresSummary.js.html">additionalExposuresSummary.js</a></td>
	<td data-value="100" class="pic high">
	<div class="chart"><div class="cover-fill cover-full" style="width: 100%"></div><div class="cover-empty" style="width: 0%"></div></div>
	</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="3" class="abs high">3/3</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="0" class="abs high">0/0</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="1" class="abs high">1/1</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="3" class="abs high">3/3</td>
	</tr>

<tr>
	<td class="file high" data-value="gulfWar1990Details.js"><a href="gulfWar1990Details.js.html">gulfWar1990Details.js</a></td>
	<td data-value="100" class="pic high">
	<div class="chart"><div class="cover-fill cover-full" style="width: 100%"></div><div class="cover-empty" style="width: 0%"></div></div>
	</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="10" class="abs high">10/10</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="2" class="abs high">2/2</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="8" class="abs high">8/8</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="10" class="abs high">10/10</td>
	</tr>

<tr>
	<td class="file high" data-value="gulfWar1990Locations.js"><a href="gulfWar1990Locations.js.html">gulfWar1990Locations.js</a></td>
	<td data-value="100" class="pic high">
	<div class="chart"><div class="cover-fill cover-full" style="width: 100%"></div><div class="cover-empty" style="width: 0%"></div></div>
	</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="3" class="abs high">3/3</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="0" class="abs high">0/0</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="1" class="abs high">1/1</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="3" class="abs high">3/3</td>
	</tr>

<tr>
	<td class="file high" data-value="gulfWar1990Summary.js"><a href="gulfWar1990Summary.js.html">gulfWar1990Summary.js</a></td>
	<td data-value="100" class="pic high">
	<div class="chart"><div class="cover-fill cover-full" style="width: 100%"></div><div class="cover-empty" style="width: 0%"></div></div>
	</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="3" class="abs high">3/3</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="0" class="abs high">0/0</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="1" class="abs high">1/1</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="3" class="abs high">3/3</td>
	</tr>

<tr>
	<td class="file high" data-value="gulfWar2001Details.js"><a href="gulfWar2001Details.js.html">gulfWar2001Details.js</a></td>
	<td data-value="100" class="pic high">
	<div class="chart"><div class="cover-fill cover-full" style="width: 100%"></div><div class="cover-empty" style="width: 0%"></div></div>
	</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="10" class="abs high">10/10</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="2" class="abs high">2/2</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="8" class="abs high">8/8</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="10" class="abs high">10/10</td>
	</tr>

<tr>
	<td class="file high" data-value="gulfWar2001Locations.js"><a href="gulfWar2001Locations.js.html">gulfWar2001Locations.js</a></td>
	<td data-value="100" class="pic high">
	<div class="chart"><div class="cover-fill cover-full" style="width: 100%"></div><div class="cover-empty" style="width: 0%"></div></div>
	</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="3" class="abs high">3/3</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="0" class="abs high">0/0</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="1" class="abs high">1/1</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="3" class="abs high">3/3</td>
	</tr>

<tr>
	<td class="file high" data-value="gulfWar2001Summary.js"><a href="gulfWar2001Summary.js.html">gulfWar2001Summary.js</a></td>
	<td data-value="100" class="pic high">
	<div class="chart"><div class="cover-fill cover-full" style="width: 100%"></div><div class="cover-empty" style="width: 0%"></div></div>
	</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="3" class="abs high">3/3</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="0" class="abs high">0/0</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="1" class="abs high">1/1</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="3" class="abs high">3/3</td>
	</tr>

<tr>
	<td class="file high" data-value="herbicideDetails.js"><a href="herbicideDetails.js.html">herbicideDetails.js</a></td>
	<td data-value="100" class="pic high">
	<div class="chart"><div class="cover-fill cover-full" style="width: 100%"></div><div class="cover-empty" style="width: 0%"></div></div>
	</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="10" class="abs high">10/10</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="2" class="abs high">2/2</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="8" class="abs high">8/8</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="10" class="abs high">10/10</td>
	</tr>

<tr>
	<td class="file high" data-value="herbicideLocations.js"><a href="herbicideLocations.js.html">herbicideLocations.js</a></td>
	<td data-value="100" class="pic high">
	<div class="chart"><div class="cover-fill cover-full" style="width: 100%"></div><div class="cover-empty" style="width: 0%"></div></div>
	</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="3" class="abs high">3/3</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="0" class="abs high">0/0</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="1" class="abs high">1/1</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="3" class="abs high">3/3</td>
	</tr>

<tr>
	<td class="file high" data-value="herbicideOtherLocations.js"><a href="herbicideOtherLocations.js.html">herbicideOtherLocations.js</a></td>
	<td data-value="100" class="pic high">
	<div class="chart"><div class="cover-fill cover-full" style="width: 100%"></div><div class="cover-empty" style="width: 0%"></div></div>
	</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="4" class="abs high">4/4</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="0" class="abs high">0/0</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="1" class="abs high">1/1</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="4" class="abs high">4/4</td>
	</tr>

<tr>
	<td class="file high" data-value="herbicideSummary.js"><a href="herbicideSummary.js.html">herbicideSummary.js</a></td>
	<td data-value="100" class="pic high">
	<div class="chart"><div class="cover-fill cover-full" style="width: 100%"></div><div class="cover-empty" style="width: 0%"></div></div>
	</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="3" class="abs high">3/3</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="0" class="abs high">0/0</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="1" class="abs high">1/1</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="3" class="abs high">3/3</td>
	</tr>

<tr>
	<td class="file high" data-value="specifyOtherExposures.js"><a href="specifyOtherExposures.js.html">specifyOtherExposures.js</a></td>
	<td data-value="100" class="pic high">
	<div class="chart"><div class="cover-fill cover-full" style="width: 100%"></div><div class="cover-empty" style="width: 0%"></div></div>
	</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="4" class="abs high">4/4</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="0" class="abs high">0/0</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="1" class="abs high">1/1</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="4" class="abs high">4/4</td>
	</tr>

<tr>
	<td class="file high" data-value="toxicExposureConditions.js"><a href="toxicExposureConditions.js.html">toxicExposureConditions.js</a></td>
	<td data-value="100" class="pic high">
	<div class="chart"><div class="cover-fill cover-full" style="width: 100%"></div><div class="cover-empty" style="width: 0%"></div></div>
	</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="2" class="abs high">2/2</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="0" class="abs high">0/0</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="0" class="abs high">0/0</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="2" class="abs high">2/2</td>
	</tr>

<tr>
	<td class="file high" data-value="toxicExposurePages.js"><a href="toxicExposurePages.js.html">toxicExposurePages.js</a></td>
	<td data-value="100" class="pic high">
	<div class="chart"><div class="cover-fill cover-full" style="width: 100%"></div><div class="cover-empty" style="width: 0%"></div></div>
	</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="14" class="abs high">14/14</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="4" class="abs high">4/4</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="13" class="abs high">13/13</td>
	<td data-value="100" class="pct high">100%</td>
	<td data-value="14" class="abs high">14/14</td>
	</tr>

</tbody>
</table>
</div>
                <div class='push'></div>
            </div>
            <div class='footer quiet pad2 space-top1 center small'>
                Code coverage generated by
                <a href="https://istanbul.js.org/" target="_blank" rel="noopener noreferrer">istanbul</a>
                at 2024-07-25T15:50:25.329Z
            </div>
        <script src="../../../prettify.js"></script>
        <script>
            window.onload = function () {
                prettyPrint();
            };
        </script>
        <script src="../../../sorter.js"></script>
        <script src="../../../block-navigation.js"></script>
    </body>
</html>

**Comment by christinec-fftc** [comment]
Typically all these artifacts would get added to the collab cycle ticket. I think it's this one [Collaboration Cycle for Disability Benefits Experience Team 1, 21-526EZ, Toxic Exposure Page#60140](https://app.zenhub.com/workspaces/disability-benefits-experience-team-1-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/60140)?

Here's a previous example for BDD SHA that may be helpful 
[Collaboration Cycle for [Benefits Disability Experience, Disability Comp Application (21-526 EZ), Add Self Assessment Part A form information to BDD workflow]#56612](https://app.zenhub.com/workspaces/disability-benefits-experience-team-1-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/56612
)

Also this ticket has product/ux testing as part of the AC. Don't know if we want to assign this ticket to @pacerwow and @mengA6 at this point instead of putting in review?

**Comment by mchae-nava** [comment]
Thanks for the example! I can add it to the collab cycle ticket! Want to make sure I did everything right first though. I will assign it to @mengA6 @pacerwow for review as well as any additional steps

**Comment by mengA6** [comment]
I think someone is planning to create a separate ticket for UX & Product testing, but here's this since I was midway through it when we made that plan.

Testing with vets.gov.user+54@gmail.com. I did this before Lighthouse changes, so just looking at the front end. 

issues found:

#### Test case: [Standard Claim with Toxic Exposure (all of 15B, 15C, 15D)](https://dsvavsp.testrail.io/index.php?/cases/view/79056&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=19004)

1. testrail step 4: got "[We can’t confirm if we have an intent to file on record for you right now](https://jmp.sh/7sDoPcG1)". Note: when I came back later and resumed my application, I saw the ITF on file. 
2. testrail step 6: Afghanistan was pre-selected as the country. Clicked "save" and got a validation error on the country field: "[you must select a valid option](https://jmp.sh/yCTIlBh4)". Changed country to Albania and clicked save. Dialog closed with no errors.
3. testrail steps 7 - 8: saw [homelessness question](https://jmp.sh/yCTIlBh4) and [High Priority Claims / terminally ill question](https://jmp.sh/NYAKF8EQ) before seeing any of these questions in steps 7-8. I think the testrail steps are just out of date. 
4. testrail steps 9-11: didn't see these steps, saw "[I'm filing a claim for](https://jmp.sh/cOqz0ocs)" question before seeing testrail step 12. I think the testrail steps are just out of date. chose "A new condition that's connected to my service".
5. testrail step 15: under "What is toxic exposure" learn more component > "Learn more about toxic exposure (opens in new tab)" link goes to https://www.va.gov/resources/the-pact-act-and-your-va-benefits/ . Expected it to go to https://www.va.gov/disability/eligibility/hazardous-materials-exposure/ per the [figma prototype](https://www.figma.com/proto/dBKlB23Hs2oa53euXcXmmK/526-toxic-exposure?page-id=1236%3A54775&node-id=1236-54788&viewport=-4593%2C-2947%2C0.62&t=1cWnsgigbvptGYRs-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=1236%3A54956&show-proto-sidebar=1). I might have missed a later conversation / decision about this if it was intentional to change that.
6. Thought we were putting the application ID in the [autosave component](https://design.va.gov/components/form/autosave), but the application ID appears in the text below the progress bar instead. [Screeenshot with staging vs figma](https://jmp.sh/VqIJ0Zoe)
7. (edge case and not launch blocking) testrail step 17: I initially filled in start and end dates for each location. continued to the "service after august 2, 1990" screen, clicked "edit locations and dates" and reset some dates back to null. I got field validation errors but was still able to submit. expected to not get a field validation error when setting the date back to null. [screen recording](https://jmp.sh/B3toG2Qg)
8. (not launch blocking) testrail step 20: was able to enter an end date that was **before** the start date. Expected validation to require that end date is either null or after start date. [Screenshot](https://jmp.sh/tqXjUqsF)
9. testrail step 26 (and also previous date range screens): it's showing hint text of "For example: January 19 2000". Did someone tell us to add this? Didn't expect to see it, and I don't think it adds anything helpful given that we have separate month, day, and year fields below. [Screenshot](https://jmp.sh/LsnNxVws)
10. testrail step 36: testrail steps are out of order. Saw "are you currently a VA employee" but not housing situation question here.
11. testrail step 37: testrail steps are out of order. Did not see terminally ill question here.

I didn't submit the application yet since the Lighthouse update is still pending.

**Comment by christinec-fftc** [comment]
Thanks for all the details and thorough testing @mengA6! Very much appreciated I'll try to triage each of the items here

1. testrail step 4: got "[We can’t confirm if we have an intent to file on record for you right now](https://jmp.sh/7sDoPcG1)". Note: when I came back later and resumed my application, I saw the ITF on file.
_Christine: New functionality from carbs. I can update the test case to note this might happen_ 
2. testrail step 6: Afghanistan was pre-selected as the country. Clicked "save" and got a validation error on the country field: "[you must select a valid option](https://jmp.sh/yCTIlBh4)". Changed country to Albania and clicked save. Dialog closed with no errors.
_Christine: This is odd. There shouldn't be any pre-selected locations or hazards. Did you start a brand new form or continue an existing saved form?_ 
3. testrail steps 7 - 8: saw [homelessness question](https://jmp.sh/yCTIlBh4) and [High Priority Claims / terminally ill question](https://jmp.sh/NYAKF8EQ) before seeing any of these questions in steps 7-8. I think the testrail steps are just out of date.
_Christine: Correct. I will fix_ 
5. testrail steps 9-11: didn't see these steps, saw "[I'm filing a claim for](https://jmp.sh/cOqz0ocs)" question before seeing  testrail step 12. I think the testrail steps are just out of date. chose "A new condition that's connected to my service".
6. testrail step 15: under "What is toxic exposure" learn more component > "Learn more about toxic exposure (opens in new tab)" link goes to https://www.va.gov/resources/the-pact-act-and-your-va-benefits/ . Expected it to go to https://www.va.gov/disability/eligibility/hazardous-materials-exposure/ per the [figma prototype](https://www.figma.com/proto/dBKlB23Hs2oa53euXcXmmK/526-toxic-exposure?page-id=1236%3A54775&node-id=1236-54788&viewport=-4593%2C-2947%2C0.62&t=1cWnsgigbvptGYRs-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=1236%3A54956&show-proto-sidebar=1). I might have missed a later conversation / decision about this if it was intentional to change that.
7. Thought we were putting the application ID in the [autosave component](https://design.va.gov/components/form/autosave), but the application ID appears in the text below the progress bar instead. [Screeenshot with staging vs figma](https://jmp.sh/VqIJ0Zoe)
8. (edge case and not launch blocking) testrail step 17: I initially filled in start and end dates for each location. continued to the "service after august 2, 1990" screen, clicked "edit locations and dates" and reset some dates back to null. I got field validation errors but was still able to submit. expected to not get a field validation error when setting the date back to null. [screen recording](https://jmp.sh/B3toG2Qg)
9. (not launch blocking) testrail step 20: was able to enter an end date that was before the start date. Expected validation to require that end date is either null or after start date. [Screenshot](https://jmp.sh/tqXjUqsF)
10. testrail step 26 (and also previous date range screens): it's showing hint text of "For example: January 19 2000". Did someone tell us to add this? Didn't expect to see it, and I don't think it adds anything helpful given that we have separate month, day, and year fields below. [Screenshot](https://jmp.sh/LsnNxVws)
11. testrail step 36: testrail steps are out of order. Saw "are you currently a VA employee" but not housing situation question here.
12. testrail step 37: testrail steps are out of order. Did not see terminally ill question here.

**Comment by mengA6** [comment]
We can consider the UX & Product portion of this ticket complete. We will continue additional testing in [Staging review artifacts testing#89411](https://app.zenhub.com/workspaces/disability-benefits-experience-team-1-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/89411).

**Comment by christinec-fftc** [comment]
fyi @mengA6 all items have been addressed. let's discuss at 16th min on monday or pair to make sure we're on the same page

**Comment by christinec-fftc** [comment]
fyi, [526 Minimal Test case](https://dsvavsp.testrail.io/index.php?/cases/view/37806&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=9795) has also been cleaned up and updated.
