### ISSUE TITLE
Research spike: Add link to the MHV landing page to order CPAP supplies

### ISSUE THREAD

**Issue by LynneJohnson224** [department-of-veterans-affairs/va.gov-team#67038]
## User story

As a Cartographers member, I need to understand how the addition of the CPAP ordering tool affects our current hearing aid supply ordering links, so that I can design an altered experience that serves both purposes.

As a user on the MHV landing page, I want to be able to access the CPAP supply ordering tool, so that I can easily order CPAP supplies without needing to message my health care provide.

## Acceptance Criteria

- Workflows for CPAP supply ordering and hearing aid supply ordering have been documented

**Comment by wesrowe** [comment]
Notes from refinement:
- Link to tool: https://staging.va.gov/health-care/order-hearing-aid-or-CPAP-supplies-form/introduction
- Do we need to link a user directly to the cpap ordering tool?
  - For UX and WCAG reasons, we should have a single combined link to the tool if the url is the same for both cpap and hearing aid supplies

**Comment by fmccaf1** [comment]
From what I can tell online, it looks like there are two completely separate forms for order CPAP devices / supplies and ordering hearing aid supplies (not hearing aids, but batteries, etc.):

CPAP: Form 2346b
https://www.va.gov/vaforms/va/pdf/VA2346b%20(electronic).pdf

Hearing aid supplies: Form 2346

However, everything else about the two supply-type processes seems to be the same in the following ways:
- One can only order online if you've ordered those items "from us" within the past 2 years
- Both can be ordered by phone from the same organization (VA Denver Logistics Center or DLC), using the same phone number (303-273-6200)
- If a user wants to order by mail, they must fill out the correct form, but send it to the same place (again, VA Denver Logistics Center) 

At this point, there are two separate pages for these two supply types in our Health Benefits Hub on VA.gov:
- [CPAP supplies](https://staging.va.gov/health-care/order-cpap-supplies/)
- [Hearing aid supplies](https://staging.va.gov/health-care/order-hearing-aid-batteries-and-accessories/)
But, much of the info on those two pages is the same
