### ISSUE TITLE
Create alerts for specific 10-10CG submission failures

### ISSUE THREAD

**Issue by kevinmirc** [department-of-veterans-affairs/va.gov-team#6703]
**Description**
We'll need to add alerting for when 10-10CG submissions fail with an unexpected error.

**Summary**
- [ ] Get allerted when error reaches sentry for `controller_name:caregivers_assistance_claim`
- [ ] See if we can set up an alert for our default logs (when we receive a log of "Attachment Dropped", get a notification). Can this be done in CloudWatch (or where ever our log destination is).

**Comment by kevinmirc** [comment]
Relates to: https://github.com/department-of-veterans-affairs/va.gov-team/issues/16875

**Comment by ala-yna** [comment]
Closed; errors are captured and the next step will be the new Sentry integration work.
