### ISSUE TITLE
SOCKS access for Napoleon Kernessant

### ISSUE THREAD

**Issue by GcioNapoleon** [department-of-veterans-affairs/va.gov-team#67036]
### Your Name

Napoleon Kernessant

### Your Email

napoleon.kernessant@va.gov

### Your Role and Team

Team Lead VFEP EDU [ GovCIO ]

### Product Manager (PM) name and email

darla.vannieukerk, darla.vannieukerk@va.gov

### Product Owner (PO) name and email

darla.vannieukerk, darla.vannieukerk@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMm80VJJkgvejynu1ErdpuiUMrfxwkp10j2DFWzd4yDX napoleon.kernessant@va.gov

### E-QIP Transmittal Confirmation

<img width="590" alt="Screenshot 2023-10-05 at 6 30 23 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/95312667/efb101a9-fba8-4509-b672-54d6d3eaecd8">

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by flooose** [comment]
Closing this because the PR for it has already been merged
