### ISSUE TITLE
QA Standards - Authenticated Experience - Profile - Notification Settings

### ISSUE THREAD

**Issue by it-harrison** [department-of-veterans-affairs/va.gov-team#67046]
#### VFS team name
Authenticated Experience - Profile

#### VFS product name
Notification Settings

#### VFS feature name

Default send functionality / Edit Mobile Phone Number Flow

#### Point of Contact/Reviewers

@it-harrison - Ian Harrison - QA
---
#### Regression Test Plan 
- [x] Standard has been met
- [ ] Standard has not been met
#### Test Plan
- [x] Standard has been met
- [ ] Standard has not been met
#### Traceability Reports 
- [ ] Standard has been met
- [x] Standard has not been met
##### Explanation of failure to meet standard (if applicable): #####
No Coverage for References present.
#### E2E Test Participation
- [x] Standard has been met
- [ ] Standard has not been met
#### Unit Test Coverage
- Lines %: 77.01 

- Functions %: 72.89 

- Statements %: 76.87

- Branches %: 64.87

- [ ] Standard has been met
- [x] Standard has not been met
##### Explanation of failure to meet standard (if applicable): #####
All categories must have at least 75% coverage.

---
### VFS Guidance

- Close the ticket when your Product Owner determines that you have sufficiently met the QA Standards.
- If your team has additional questions or needs Platform help validating the issue, please comment on the ticket

### Platform directions
- Update "Issue Title" to be of the form "QA Standards - VFS Team - VFS Product"
- Add the VFS team, product name, and feature name
- Add your name, practice area, and GH handle under Point of Contact/Reviewers
- Complete the QA Standards section, making sure to include an "Explanation of failure to meet standard" for every Standard the product does not meet.
- Link to the Collaboration Cycle Request epic
- Add epic's milestone
- Add assignees: 
  - VFS PM
  - Yourself (optional)
- Add labels:
  - VFS team label
  - VFS product label
  - QA-standards label
  - launch-blocking label if the product has failed to meet a required QA Standard

**Comment by mtcA6** [comment]
The standard changed after we deployed, closing this out.
