### ISSUE TITLE
Design intent Collaboration[campaign landing page template]

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#6704]
## Steps to complete Design Intent Collaboration
- [x] Product Manager or Designer: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in #design in Slack; tag @ Crystabel Reiter @ Emily
- [x] Crystabel and Emily to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [x] At least 2 days before scheduled meeting, you must provide list of artifacts below
- [x] VSP <> **requesting team** design intent collaboration meeting completed
- [x] Design experts leave feedback and relevant resources on this ticket
- [x] VFS designer acknowledge receipt of feedback/resources
- [x] VFS designer and all other requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please provide the following at least 2 days before the scheduled meeting_
- Link to product outline : https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/campaign-landing-page-templates/README.md
- Sketches: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/content/tier-2-content-IA-and-design/campaign-landing-page-templates/design-wip
- Lo-fi mockups - note these are now outdated; see Sketch files above.
- Content template requirements markup: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/campaign-landing-page-templates/campaign-lp-content-requirements-022420.pdf

## Meeting attendees from **requesting team**
- Designer(s) (required): **Ryan Thurlwell** @rtwell 
- Product Manager (optional): **Jennifer Lee, PO** @jenniferlee-dsva 
- DEPO design lead (required as applicable): **Ryan Thurlwell**

## Scheduling
Preferred dates or times: 
- Thu March 12 - so far free btn 9am - noon ET; 3pm - 4pm ET.
- Mon March 16 - so far free btn 9:30 am - noon ET.

## Additional Notes
Design experts will provide: 
- A list of relevant design components and patterns (with URLs)
- A list of existing applications or pages with similar execution or patterns with URLs in staging

During this collaboration point, you will receive feedback from the following practice areas: design, accessibility

**Comment by kevwalsh** [comment]
Please invite me and @beeyayjay to this!

**Comment by CrystabelReiter** [comment]
@jenniferlee-dsva Due to difficulty of scheduling, VSP practice areas have dedicated calendar blocks for reviewing to Tuesdays 11AM-12PM EST and Thursdays 1:30-2:30 PM EST. 

Do you have any availability for those times on 3/12 (1:30-2:30) , 3/17 (11:30) , or 3/19 (1:30-2:30)?

**Comment by CrystabelReiter** [comment]
Design intent collaboration has been scheduled for Wednesday 3/18 at 10:30 AM EST

**Comment by jenniferlee-dsva** [comment]
Hey @meganhkelley @CrystabelReiter @emilywaggoner - ryan and I have completed this, can you update the checkboxes above so we can close this ticket? 

FYSA @stephorkandatx @johnhashva
