### ISSUE TITLE
[CAIA Intake] VA Police transparency page placement within VAMCs

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-team#67055]
## About your team

- Team name: Sitewide Facilities
-	OCTO-DE product owner: Michelle Middaugh
-	Product manager: Jane Xiong
-	Designer: Jordan Wood
- Accessibility specialist: Laura Flannery
- Content writer: Dave Picket
-	Slack channel: #sitewide-facilities
 
### Describe what you need in a few sentences:
This is for the work described in Collaboration Cycle for Sitewide - Facilities, VA Medical Centers, Police Transparency #65082. This is legislatively-mandated police activity information on VAMC web pages that must be completed by December 29, 2023. This will be new content on the VA website so we'd like review and guidance.
</br>
</br>

### Which are you doing?
- [x] **Launching a new** page from existing VAMC pages
- [x] **Making changes** to existing pages (new page will link from existing VAMC pages)

### Types of Support
What areas does your team need support in? Check all that apply.
#### Content
- [ ] Collaboration on content written by your team’s dedicated content writer 
- [x] Collaboration on content if your team does not have a dedicated content writer
#### Accessibility
- [ ] Accessibility review of wireframes and/or prototypes
- [ ] Accessibility issue (general request)
- [ ] Accessibility PDF review request
- [ ] Accessibility user research support ([submit a separate, additional request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name))
- [ ] DST component or pattern 
- [ ] Something else 
#### IA
- [ ] User Flows
- [x] Page placement
- [ ] URLs
- [ ] Breadcrumbs and Left Nav placement
- [ ] Redirects
#### Multilingual content
- [ ] Translating content
 
## Timeframe
_We guide and work alongside teams across nearly every OCTO digital product. We also work with partners across VA to lead content migration and manage all unauthenticated content on VA.gov. And we're always working to expand the VA.gov content style guide and our IA and accessibility documentation. We need to prioritize all intake requests based on our overall workload and VA and OCTO priorities._

_Tell us about your product's timeline. And we'll work with you to meet timeline needs as best we can._
The Cleland Dole Act Sec 405 legislation enacted Dec. 29, 2022 requires within one year of enactment:
(e) (1) The Secretary shall publish on the internet website of each facility of the Department the following information with respect to the facility:

(A) Summaries and statistics covering the previous five-year period regarding—

(i) arrests made by and tickets issued by Department police officers;

(ii) prosecutions, ticketing, and other actions relating to such arrests;

(iii) the use of force and weapons discharge by Department police officers; and

(iv) complaints, investigations, and disciplinary actions regarding Department police officers.

(B) Contact information for employees of the Department and the public to directly contact the police force of the facility, including for an individual (or the representative, attorney, or authorized agent of the individual) to request information regarding the arrest, ticketing, detainment, use of force, or other police matters pertaining to that individual.

(2) The Secretary shall ensure that each police force of a facility of the Department is able to provide to an individual who contacts the police force pursuant to paragraph (1)(B) the information described in such paragraph

### Have you worked with CAIA before? 
  - [x] Yes
  - [ ] No

### What's your team’s next step and its timing?

- **Our next step is** Platform Design Intent meeting
- **Provide date if available**: 10/24/2023

#### Timing for your next step: 
  - [ ] Next week
  - [x] This month
  - [ ] Next month
  - [ ] This quarter
  - [ ] Next quarter
  - [ ] 6 months
  - [ ] 1 year

### Is this timing related to a specific event or Congressionally mandated deadline?
  - [x] Yes
  - [ ] No

### If you're conducting research, when is that starting? N/A
**Provide date if available:** xx/xx/xxxx
  - [ ] Next week
  - [ ] This month
  - [ ] Next month
  - [ ] This quarter
  - [ ] Next quarter
  - [ ] 6 months
  - [ ] 1 year

### Will you release this new product incrementally (for example, release to 25% of users to start)? 
  - [ ] Yes
  - [x] No
 
**Note**: _If you checked yes, we’ll reach out to discuss details about the content in the react widget (we use these widgets to display entry points for new products to a certain percentage of users who visit our static pages)._

  
### When do you expect to launch your product to 100% of users?
  
*Please provide an estimated date so our team can create other relevant tickets.*
- **We expect to launch our product to 100% of users on:** 12/18/2023
  
### Will this work be going through the Collaboration Cycle?
- [x] Yes 
- [ ] No

### If no ...
- Skip to the _supporting artifacts_ section, below.
 
#### Please provide the link to your Collaboration Cycle ticket: 
- **Ticket (number)**: #65082
- **Collab. Cycle Ticket Opened (date)**: 09/06/2023
 
#### Please check all of the phases in the Collaboration Cycle you have completed: 
- [x] Design Intent
- [ ] Midpoint Review
- [ ] Staging
 
##### Design Intent
- [ ] Accessibility
- [x] Content
- [x] IA
- [ ] Translation
- [ ] Already completed, no assistance needed
- [ ] Unknown at this time
##### Midpoint
- [ ] Accessibility
- [ ] Content
- [ ] IA
- [ ] Translation
- [ ] Already completed, no assistance needed
- [ ] Unknown at this time
##### Staging
- [ ] Accessibility
- [ ] Content
- [ ] IA
- [ ] Translation
- [ ] Already completed, no assistance needed
- [ ] Unknown at this time
  
## Supporting artifacts
*Please provide links to supporting artifacts as available.*
- **Product outline**: [VAMC Medical Centers product brief on Github](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/product/vamc-product-brief.md)
- **User flows**: [Sketch file](https://sketch.com/s/b48c905c-7c7f-46fb-9ae5-6020ff0e5174)
- **Prototype or mockups**:  [Sketch file](https://sketch.com/s/b48c905c-7c7f-46fb-9ae5-6020ff0e5174)
- **If this is in Sketch, which version or specific page should we focus on?** Design Intent
- **Content source of truth**: Police activity vendor Axon
- **Research plan:**
- **Any epics/issues that may be helpful**:
  - [Initiative brief on Github](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/police/readme.md#initiative-brief-va-police-transparency-wip)
  - [Sitewide Facilities epic](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14327)
- **Link to testing accounts** (please do not paste them in this ticket): 

### Have you already worked with someone from OCTO leadership?
- [ ] Danielle
- [ ] Beth
- [ ] Mikki
- [ ] Martha

### How do you plan to work with us on this request?
- [ ] I’ll take this to Beth or Danielle’s office hours.
- [ ] I’d like to schedule time to talk about this.
- [ ] Let’s work async and meet as needed.
- [x] Schedule a kick-off call with your team and CAIA for your project **(Recommended)**

 
### Accessibility Help in Slack
The [#accessibility-help channel](https://dsva.slack.com/archives/C8E985R32) in the DSVA Slack, is also available to you as a resource. Everyone is welcome to ask questions or get help from our a11y (accessibility) specialists. Tag `@Terry Nichols` to get a11y help asap.

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag `@Terry Nichols`.**

- If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
- If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jennymayoco%2C+jilladams%2C+RLHecht&labels=sitewide+CAIA%2C+Sitewide+IA%2C+Public+Websites%2C+VA.gov+frontend%2C+Redirect+request&projects=&template=redirect-request.md&title=Redirect+Request)
 
 - If you are creating an [experimental design,](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) please [also contact the DST. ](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)

- If you are requesting [a11y support for user research,](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name) please complete this form, next. 

```[tasklist]
### CAIA General Ticket Tasks
- [x] Set up Kickoff Meetings (Terry/Lily 11/1/2023
```

```[tasklist]
### Content tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/68949
```

```[tasklist]
### IA Tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/69003
```

**Comment by coforma-terry** [comment]
**CAIA Update:**

Kickoff meeting scheduled for Nov 1st - 12:30 - 12:45 PM ET.

[https://coformaco.zoom.us/j/85176281046?pwd=WWxhYXQ4L05zTGFLMFRnZ3JrMmczdz09](https://www.google.com/url?q=https://coformaco.zoom.us/j/85176281046?pwd%3DWWxhYXQ4L05zTGFLMFRnZ3JrMmczdz09&sa=D&source=calendar&ust=1698178478742506&usg=AOvVaw1JFN8cRpY20w3EHz58Lxv0)

**Comment by xiongjaneg** [comment]
@davidmpickett @thejordanwood @aklausmeier Could we review and discuss Kristin's comments at our next UX Refinement so we're prepared to discuss at the Nov. 1 kickoff? Thank you!

**Comment by davidmpickett** [comment]
> 2. In general, we think ya'lls plan of putting the "VA Police" detail page in the first level of the 'About' section makes sense!

I want to clarify that when @thejordanwood made these designs, we had not actually decided yet if these pages would live at the System level or Facility level. Since then, the conversation has actually gone in the opposite direction (one page per Facility) of what's reflected in the Sketch file (one page per System). Sorry for the confusion, that sidebar mockup was not supposed to be an official IA proposal.

I will be creating a more [detailed content model](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15756) as part of this upcoming sprint.

**Comment by davidmpickett** [comment]
> 3. We would love to take this opportunity to codify some rules around the order of pages in the 'About' section -- I added some stickies in the mural about this, but we're wondering how the order is currently determined? Could ya'll see if you can figure that our before our kickoff call?

The menus are managed in Drupal as drag & drop interfaces. The discrepancies in the order of items are likely due to these menus being created at different times during the VAMC upgrade process and there being no way to programmatically enforce a specific order. That being said, reordering the menu items to match a specified order is a possibility. These menus are only editable by Drupal admins so once they are cleaned up, they should be relatively stable.

Here are the possible L2 items in the ABOUT [VAMC SYSTEM] section of the menu. Programs and Research are only enabled for some VAMC systems.

- ABOUT [VAMC SYSTEM]
  - About us
  - Work with us
  - Contact us
  - Policies
  - VA Police 
  - Programs (if enabled)
  - Research (if enabled)
  
Let me know what your preferred order of these items is and I can spin up a ticket to have the 140 menus updated to match

![screencapture-training-qtpbfivdfzrlrlyiqwmanznaobpek1ca-demo-cms-va-gov-admin-structure-menu-manage-va-amarillo-health-care-2023-10-27-11_34_38](https://github.com/department-of-veterans-affairs/va.gov-team/assets/51967950/a80ca38d-143e-48d0-8e25-e0efa2e68ce0)

**Comment by davidmpickett** [comment]
> > 2. In general, we think ya'lls plan of putting the "VA Police" detail page in the first level of the 'About' section makes sense!
> 
> I want to clarify that when @thejordanwood made these designs, we had not actually decided yet if these pages would live at the System level or Facility level. Since then, the conversation has actually gone in the opposite direction (one page per Facility) of what's reflected in the Sketch file (one page per System). Sorry for the confusion, that sidebar mockup was not supposed to be an official IA proposal.
> 
> I will be creating a more [detailed content model](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15756) as part of this upcoming sprint.

Update on this item. Yesterday I discussed with our team two possible navigation options given the decision to have one page per facility
- [Option 1](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1698092447003/c969debf289d4e43e3cdd293d90053c2c137c338?wid=0-1698269210053) - nest the facility police pages under the individual facility page
- [Option 2](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1698092447003/c969debf289d4e43e3cdd293d90053c2c137c338?wid=0-1698275504458) - still have a system-level police page and nest the facility pages under that

Based on initial feedback from @mmiddaugh and the team yesterday, it seems like we are aligned on Option 2. @thejordanwood will be updating the sketch file to distinguish between the system-level index page and the facility-level data pages

**Comment by davidmpickett** [comment]
> 4. For VAMCs that have existing police data in the 'Prepare for your visit' accordions, we think there still might be a case for including some info about security there, but we'd love to work together to codify what goes in there and what doesn't go in there, and see if we can get some standards together. Ex: stuff about there being metal detectors and a bag search does seem to help you prepare for your visit. Or maybe info about those super cool police/mental health worker partnerships that some VAMCs have.

The 'Prepare for your visit' accordions are very blobby and hardening them is a [documented need](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8325). Unfortunately, I don't think any updates to those are in scope for MVP of the Police Transparency initiative.

Similarly, related to your note in Mural, we will not be migrating any content that is currently in Police Detail pages for MVP. However, we are setting ourselves up for that future possibility by creating a new Drupal content type for VAMC System Police pages.

**Comment by kristinoletmuskat** [comment]
Hey @davidmpickett, thanks so much for your detailed response! I was out last week to just catching up. We can chat about this during our CAIA sync tomorrow, and I can bring some of our open Qs back to Mikki on Thursday during our weekly sync.

I've also added some comments to your mural!

One more Q:
For the order of the 'about' section, are we able to get any data on the which links are most vs least used by veterans? I realize it will probably vary by system/facility, but I'm leaning towards that as a method to order them, and wondering if we could put some data behind it.

**Comment by davidmpickett** [comment]
> One more Q: For the order of the 'about' section, are we able to get any data on the which links are most vs least used by veterans? I realize it will probably vary by system/facility, but I'm leaning towards that as a method to order them, and wondering if we could put some data behind it.

This was easy to pull since the URLs are so consistent. Data in Google analytics pulled across all VAMC systems for Jan 1- Oct 30, 2023 for traffic to top-level pages (subpages excluded) in About Us.

- ABOUT [VAMC SYSTEM]
  - About us = 580k
  - Work with us = 880k
  - Contact us = 2,980k
  - Policies = 196k
  - Programs (if enabled) = 233k
  - Research (if enabled) = 53k 

[research.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/13222253/research.pdf)
[about-us.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/13222248/about-us.pdf)
[work-with-us.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/13222249/work-with-us.pdf)
[contact-us.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/13222250/contact-us.pdf)
[policies.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/13222251/policies.pdf)
[programs.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/13222252/programs.pdf)

**Comment by thejordanwood** [comment]
@kristinoletmuskat To answer your question from the kickoff meeting, this is what we're thinking for content on system and facility pages. 

- System-level page: general information about VA police, system-level contact info, & links to facility-level pages
- Facility-level pages: Contact information and data per facility, with definitions and explanations

I have a mockup on the Current page of [the Sketch file](https://sketch.com/s/b48c905c-7c7f-46fb-9ae5-6020ff0e5174) with an idea of how we can show this, although I do expect some of the content and design to change.

**Comment by mmiddaugh** [comment]
VA Police Service leadership encourages us to repurpose the content available on [VA Police (Department.va)](https://department.va.gov/about/va-police/) for the intro and FAQs needed for the VAMC VA Police pages. Hoping you can help us avoid duplication and negative SEO impact with some tweaks. 

<details>
<summary> Page intro </summary>

Proposed intro content:

>VA police officers ensure that VA Medical Centers and other VA health facilities are safe environments where Veterans and family members can receive care. 

Existing content from Department.VA page: 

> The VA Police are the armed and uniformed federal law enforcement service of the U.S. Department of Veterans Affairs (VA). VA Police are responsible for the protection of VA Medical Centers (VAMCs) and other facilities such as Community-Based Outpatient Clinics (CBOCs), Health Care Centers (HCCs), annexes, and other facilities operated by VA. The VA Police also serve VA’s National Cemetery Administration (NCA) and Veterans Benefits Administration (VBA), including locations in Puerto Rico and the U.S. Virgin Islands. The safety, security, and wellness of all who provide care and services is a leadership priority.
> 
> The primary role of the VA Police is to deter and stop crime, keep order, and investigate crimes that may have happened within the legal authority of the VA. Some cases are investigated by special agents from the VA Office of the Inspector General (OIG).
> 
> VA Police and police specialty positions, such as Criminal Investigators, get their authority legally from Title 38 of the United States Code (USC), Sections 901 and 902. Rules, regulations, and enforcement actions specific to the VA are written in Title 38 of the Code of Federal Regulations (CFR).
</details>

<details>
<summary> FAQs </summary>

Proposed FAQ content

> - Q: What services do the VA Police provide?
> - A: VA Police are armed and uniformed federal law enforcement officers who provide law enforcement and security services which benefit Veterans, their families, and their communities.  Services include crime prevention and investigation, maintaining law and order, vehicle and foot patrols, telecommunication services, and workplace violence prevention. 

> - Q: Do VA Police work with local law enforcement?
> - A: The VA Police and local law enforcement have agreements to establish the role of community agencies in responding to crimes that happen on VA property. VA Police and local law enforcement partners train together on skills and tactics such as active threat drills, crisis intervention training, disaster response, and more.

> - Q: Am I eligible to join the VA Police Force?
> - A: 90% of VA Police have a military background. VA Police is looking for qualified applicants to join its team. Candidates must have either criminal justice education, experience as a police officer, experience as a military police officer or a combination of education and experience. Visit `USAJOBS` to view current VA Police job announcements.
> Transitioning service members may be eligible for employment training, internship, and apprenticeship opportunities with VA police through the DoD SkillBridge program. For more information email Skillbridge.vapolice@va.gov. 

> - Q: Why are VA Police wearing body-worn cameras?
> - A: As a part of their mission to “protect those who served”, VA Police across the country will begin to use in-car and body-worn cameras by the end of 2023. This policy will increase the safety of VA facilities through the use of equitable, transparent, accountable, constitutional, and effective law enforcement practices. 

> - Q: How will my privacy be protected?
> - A: VA is committed to protecting the privacy of the Veterans, families, caregivers, and survivors we serve. All local VA Privacy Officers and VA Police Officers will attend extensive privacy training before officers begin using body-worn cameras.

(are we able to link to the Body worn FAQ - or other FAQ- on Department.va?)

**Comment by kristinoletmuskat** [comment]
Hey @davidmpickett , I have some answers for you on our open question re: the order of the 'about' section.  Here's the recommendation we'd like to make and why:

About Us
Programs (if enabled)
Research (if enabled)
Privacy and Policies
VA Police
Work with us
Contact us

Rationale: 
1. We want to reserve the top and bottom spots for the most important items for veterans, due to the [Primacy/Recency effects](https://www.interaction-design.org/literature/article/serial-position-effect-how-to-create-better-user-interfaces#:~:text=The%20Primacy%20Effect%3A%20Items%20that,the%20middle%20of%20a%20list.).  That would be Contact Us and About Us according to the metrics, and we think putting 'about' at the top and 'contact' at the bottom is a recognizable pattern.
2. The next highest link 'work with us' we think is not geared towards veterans looking for medical care, so we've listed that one below police and policies. 
3. We've added Privacy to 'Privacy and Policies' because that's how we refer to this type of content elsewhere on va.gov. Ex: https://www.va.gov/privacy-policy/

Lmk if you have any questions or additional thoughts! I think we feel strongest about the position of the About Us and Contact Us, compared to the stuff in the middle.

**Comment by davidmpickett** [comment]
Thanks @kristinoletmuskat. This all makes sense. I'll work on drafting follow up ticket(s) to implement these changes and link them here.

**Comment by kristinoletmuskat** [comment]
Hey @davidmpickett -- any reason not to close this ticket?

**Comment by davidmpickett** [comment]
Good to close! We got your guidance and create tickets on our side to update
