### ISSUE TITLE
FE | Profile | Notification settings| [Assistive tech and device support] Alert and status messages aren't announced without receiving focus. (11.22.1)

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#67069]
#### VFS team name
Authenticated Experience

#### VFS product name
Profile

#### VFS feature name
Notification settings > Editing as a subtask

#### Point of Contact/Reviewers
Brian DeConinck - @briandeconinck - Accessibility

*For more information on how to interpret this ticket, please refer to the [Anatomy of a Staging Review issue ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Anatomy-of-a-Staging-Review-Issue-ticket.2060320997.html) guidance on Platform Website.

---

### Platform Issue
Alert and status messages aren't announced without receiving focus.

### Issue Details
After successfully editing a phone number via the subtask pattern, I'm returned to the Notification Settings page with a success alert. However, as a screen reader user, I don't hear that success message when returning to the page, and instead have to go looking for it.

### VA.gov Experience Standard
[Category Number 11, Issue Number 22](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

### Other References
WCAG SC 4.1.3_AA

### Platform Recommendation
This is a good situation for using `role="alert"` on that success alert, or else sending keyboard focus to the alert.

---

### VFS Guidance

- Close the ticket when the issue has been resolved or validated by your Product Owner
- If your team has additional questions or needs Platform help validating the issue, please comment on the ticket
- Some feedback provided may be out of scope for your iteration of the product, however, Platform's OCTO leadership has stated that all identified issues need to be documented and it is still your responsibility to resolve the issue.
- If you do not believe that this Staging Review issue ticket is the responsibility of your team, comment below providing an explanation and who you believe is responsible. Please tag the Point of Contact/Reviewers. Governance team will research and will follow up.

**Comment by adamwhitlock1** [comment]
@mtcA6 This is ready to validate.

Probably the easiest way to look at this would be to update the mobile phone on staging, and when the user is redirected back to the notification settings, then you can inspect the alert and verify that it has the `role="alert"` now added to the component attributes _see screenshot_

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzZVQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6f9dcbd0709aabcb9af0fdb9bc66d30c50a8547a/Screenshot%202023-11-01%20at%209.46.02%E2%80%AFPM.png)

**Comment by mtcA6** [comment]
Tested w/user 202 and it worked as described 🕺
