### ISSUE TITLE
[Other - Accessibility] Unclear focus management. (00.00.1)

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#67073]
#### VFS team name
Authenticated Experience

#### VFS product name
Profile

#### VFS feature name
Notification settings > Default send functionality

#### Point of Contact/Reviewers
Brian DeConinck - @briandeconinck - Accessibility

*For more information on how to interpret this ticket, please refer to the [Anatomy of a Staging Review issue ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Anatomy-of-a-Staging-Review-Issue-ticket.2060320997.html) guidance on Platform Website.

---

### Platform Issue
No VA.gov Experience Standard for the issue found.

### Issue Details
When checking a "Notify me by" checkbox and the change is saved, it's not clear where keyboard focus goes. There's no visible focus indicator, focus isn't on the checkbox I just checked (since pressing [enter] doesn't uncheck it), and focus isn't on the success alert (since pressing [tab] doesn't move focus to the checkbox).

### VA.gov Experience Standard
[Category Number 00, Issue Number 00](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

### Platform Recommendation
My preference here would be:
- Focus moves to the success alert using `tabindex="-1"`
- There's a visible focus ring around the success alert

That ensures that the alert is read (you can probably remove `role="alert"` from it, but definitely test that!) and makes the checkbox the next tab stop --- so if I realize I didn't mean to check that box, I have an immediate opportunity to fix my mistake.

---

### VFS Guidance

- Close the ticket when the issue has been resolved or validated by your Product Owner
- If your team has additional questions or needs Platform help validating the issue, please comment on the ticket
- Some feedback provided may be out of scope for your iteration of the product, however, Platform's OCTO leadership has stated that all identified issues need to be documented and it is still your responsibility to resolve the issue.
- If you do not believe that this Staging Review issue ticket is the responsibility of your team, comment below providing an explanation and who you believe is responsible. Please tag the Point of Contact/Reviewers. Governance team will research and will follow up.

**Comment by adamwhitlock1** [comment]
@mtcA6 We can validate this now.

- log into staging
- update a notification setting checkbox
- verify that focus ring shows up on alert for save success and that hitting the tab key after a save moves focus to the previously saved checkbox.

**Comment by mtcA6** [comment]
Tested w/ user 202 and it worked as expected. Closing this ticket
