### ISSUE TITLE
STEM: Rogers STEM Scholarship eligibility page should display when the wrong benefit is selected

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#6707]
When applying for the STEM scholarship, a user is asked which benefit they will be using. To be eligible, the user must be using the Chapter 33 benefit. If the user selects any other benefit on the benefits selection page, they should receive a warning on the Rogers STEM Scholarship eligibility page that they are not eligible. Currently, if the user selects the wrong benefit, but is otherwise eligible, this page is not displayed.

Steps to reproduce
1. Begin the STEM application at https://staging.va.gov/education/apply-for-education-benefits/application/1995/introduction
2. Fill in all required fields on the Applicant Information page and click continue
3. Select any non-chapter 33 benefit and click continue
4. Select the Yes radio button for all questions and click continue

The Rogers STEM Scholarship eligibility page should display with the following information
```
- "X" next to Post-9/11 GI Bill beneficiary or Fry Scholarship recipient
- "√" next to Have used all your education benefits or are within 6 months of doing so
- "√" next to Are enrolled in a STEM undergraduate degree program, or have earned a STEM degree and are now pursuing a teaching certification
```

Currently, the page is skipped as if the user picked the correct benefit which could lead them to falsely believe that they are eligible.

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/11853

**Comment by delli-gatti-michael** [comment]
Local Testing complete

![Screen Shot 2020-03-10 at 10.45.32 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/a322ef0c-d7ff-4a58-965b-42f30928cf8c)

**Comment by delli-gatti-michael** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/11853

**Comment by delli-gatti-michael** [comment]
Bug fix is now in Staging. Closing this issue
