### ISSUE TITLE
Make FAQs in the CMS reusable: COPE in Drupal

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#6708]
## Make FAQs in the CMS reusable: COPE (create once, publish everywhere) in Drupal

This work rolls up to the larger 2020 effort to create a VA.gov learning center and learning center templates. It also aligns with larger efforts to templatize benefit hubs.

Learning center template product repo WIP/DRAFT:
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/content/tier-2-content-IA-and-design/learning-center-mvp

### Problem statement:
Today we create FAQ content ad hoc on a per page basis. 

Sometimes the information in that FAQ is applicable to other pages. However, there's no way to republish that same content in multiple places, so content authors either link to that FAQ page (acceptable but not ideal UX) or duplicate that FAQ on the new page (also not ideal). 

- The latter way creates multiple versions of the same content which then can get out of sync over time - no single source of truth. 
- It also becomes difficult to keep track of where that content needs to be updated when we receive updated/changed benefit information from SMEs. 

We anticipate this problem to grow as learning center and campaign landing pages come on board. In the future, we also want to be able to republish (without duplicating) helpful benefit-support FAQs inside the authenticated sessions (design, etc., TBD - but for example imagine a portion of an auth page that's generated with Drupal FAQs content). 

### Discovery needed: 

- Can FAQs be made into atomic COPE blocks of content (like our reusable alerts)? 
- Could this be done for not just content inside an FAQ accordion component, but for Q&A content as well? 
- What would the Drupal AX be like? 
- What FE and/or design work would need to happen to accomodate FAQs COPE?
- Can we use this existing list of IRIS call center FAQs (about 900 of them) as the starting point ~to 'migrate'~?  
https://iris.custhelp.va.gov/app/answers/list/session/L3RpbWUvMTU5MjUwMzQyMi9nZW4vMTU5MjUwMzQyMi9zaWQvZlVHOXBodlBUcVBva2dZU1NPcE9zSGV0VTRjTGJfUDdpeE9fbzQlN0UwRkVxXzhoUF8zdVQ3aUx1dU15TFkxTlVjQUhtREd5OHhUdkJ5Ql9uNzllZ05wZ1ZJNHRJanUySkNqcEJsOHgwYnIxZGRQX2RuZmwlN0VpbF9FQSUyMSUyMQ%3D%3D   <-- added 7/20
- Can we make each FAQ have a unique ID or URL that can be linked to whether it's in an accordion or on its own FE page? (Is this FE only?)  <-- question added 7/27

~@AkucherGCIO - I'd like this to be one of the backlog items that the new PW-assigned Drupal engineer works on.~  

FYSA @mnorthuis @kevwalsh  @chrisj-usds

**Comment by jenniferlee-dsva** [comment]
Beth Jacobson and Mickin have offboarded PW team.

**Comment by jenniferlee-dsva** [comment]
FYSA - @kevwalsh @oksana-c : I've updated the original ticket with IRIS call center FAQs info. 

IRIS is slated to be retired at the end of December. This could be a great place to start - real content that we might use to create COPE FAQs. 

@bethpottsVADEPO  - we would definitely need to audit these pages for content quality before publishing, so no worries - I am not suggesting we publish all of these IRIS content.

**Comment by jenniferlee-dsva** [comment]
@kevwalsh @oksana-c - Updated the original ^ -- crossed out 'to migrate.' Clarification we do not need to 'migrate' IRIS FAQs via scripting. This is achievable via content only workstream, the way we 'migrated' AMA decision reviews content. Thought you'd want to see however the depth/breadth of existing legacy stuff out there. 

If you advise that a CMS scripted migration is reasonable LOE for our MVP, great; if not, I prefer to not risk the high priority minimum items we need for launch (About, FAQs, Step by step, LC home, tags). COPE is def something that we can add and iterate on post MVP launch of account and profile section of LC.

**Comment by bethpottsVADEPO** [comment]
@jenniferlee-dsva I think it makes sense to get a content team member started on 1/ auditing for duplication and 2/ editing/content QA (grammar, style, plain language)--and for any other issues that might come up. Any reason to hold off on this work? Looks like this is what they'd be working with: https://iris.custhelp.va.gov/app/answers/list/session/L3RpbWUvMTU5MjUwMzQyMi9nZW4vMTU5MjUwMzQyMi9zaWQvZlVHOXBodlBUcVBva2dZU1NPcE9zSGV0VTRjTGJfUDdpeE9fbzQlN0UwRkVxXzhoUF8zdVQ3aUx1dU15TFkxTlVjQUhtREd5OHhUdkJ5Ql9uNzllZ05wZ1ZJNHRJanUySkNqcEJsOHgwYnIxZGRQX2RuZmwlN0VpbF9FQSUyMSUyMQ%3D%3D

**Comment by jenniferlee-dsva** [comment]
@kevwalsh @oksana-c - added a Q ^ in og ticket. It may be a FE template thing, but I thought it might have a CMS aspect, so including it in this epic for visibility. The ability to link users to a specific FAQ has been long desired and was especially helpful for call centers on the coronoavirus FAQs page before they had to go inside accordions. 

Being able to link ppl to a specific accordion FAQ would be something valuable both in and out of the LC. 

> 
- Can we make each FAQ have a unique ID or URL that can be linked to whether it's in an accordion or on its own FE page? (Is this FE only?)  <-- question added 7/27

**Comment by jilladams** [comment]
All epic tickets closed, closing.
