### ISSUE TITLE
CPCPAC Potential Failed FSR Submissions

### ISSUE THREAD

**Issue by HeatherRienks** [department-of-veterans-affairs/va.gov-team#67085]
## Description

Aleena Mirza (from Huron) reported the following on the VBS | VODA sync on 10/13/23:

I wanted to go ahead and provide you with the Transaction IDs of the veterans from CPCPAC whose data was populated onto the extract file at a later date than the VODA submission date. If you could please double check to make sure they were on the failed submission list that would be great. Thank you!

 
Transaction IDs:

"056ce5d5-230c-4bb7-a969-2bbbc83dd3ca"

"2bff97ec-5d82-4180-b6d1-464530bf80ad"

**Comment by kjsuarez** [comment]
Both of these submissions have a populated error message and a state of 'submitted'.
This implies that the submissions had failed at some point (hence the error message) but had later been successfully submitted. This backs up Aleena's observation of a timing discrepancy.

**Comment by HeatherRienks** [comment]
@kjsuarez - thanks - I will email Aleena to inform her!
