### ISSUE TITLE
Step miscount and inconsistent formatting

### ISSUE THREAD

**Issue by freeheeling** [department-of-veterans-affairs/va.gov-team#67093]
### Description
The guide includes Steps 1, 2 and 4, but not 3. In addition, the alignment of item 1 in Step 2 is not consistent with the other items in each step, and there appears to be a line break in item 3 of Step 2 as well as a missing period.

### Relevant URLs
- https://depo-platform-documentation.scrollhelp.site/support/getting-help-from-the-platform-in-slack

**Comment by vbellissimo** [comment]
Hi @freeheeling , thanks for flagging this. Our team will take a look to correct.

**Comment by taylojill** [comment]
Hello @freeheeling I'll be working on your request, and should have a draft for your review early next week. Thanks!
cc @johnny-jesensky-adhoc

**Comment by taylojill** [comment]
Hello @freeheeling I'll be working on your request, and should have a draft for your review early next week. Thanks!
cc @johnny-jesensky-adhoc

**Comment by taylojill** [comment]
Hello @freeheeling I attached a pdf showing my page updates. Please review and let me know if this works. Once approved, I'll get the updated page published on the Platform web site. Here's what I did:

- Converted the page content to a how-to template to correct formatting
- Corrected the step count
- Removed line break
- Added missing period
- Checked page for launch blocking issues

[PWD-Copy of Getting help from the Platform in Slack-301023-171750(1).pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/13208060/PWD-Copy.of.Getting.help.from.the.Platform.in.Slack-301023-171750.1.pdf)

cc @johnny-jesensky-adhoc

**Comment by freeheeling** [comment]
Hi, @taylojill – The only change I would suggest is wrapping "Step 3: Submit your request" into **Step 2**, eliminating Step 3 and making "1. Click the Submit button." in Step 3 the 5th listed item in Step 2 as everything currently listed in Step 2 pertains to the Slack support form. Otherwise, I think your updates meet expectations.

**Comment by taylojill** [comment]
Thanks @freeheeling! I'll make the updates and get the page published. 

cc @johnny-jesensky-adhoc

**Comment by taylojill** [comment]
Page updated and moved from draft to Support space. No launch blocking issues.
