### ISSUE TITLE
Design intent Collaboration [VA form search page]

### ISSUE THREAD

**Issue by rtwell** [department-of-veterans-affairs/va.gov-team#6710]
## Steps to complete Design Intent Collaboration
- [x] Product Manager or Designer: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in #design in Slack; tag @ Crystabel Reiter @ Emily
- [x] Crystabel and Emily to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [x] At least 2 days before scheduled meeting, you must provide list of artifacts below
- [x] VSP <> **requesting team** design intent collaboration meeting completed
- [x] Design experts leave feedback and relevant resources on this ticket
- [x] VFS designer acknowledge receipt of feedback/resources
- [x] VFS designer and all other requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts 
- Link to product outline: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/find-va-forms-redesign

- Design files located in the [product folder here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/find-va-forms-redesign/design)

### VA form search landing page - desktop
![image](https://user-images.githubusercontent.com/12564977/76319012-f3ac1d80-62b4-11ea-97dd-cbf808f8da30.png)

### VA form search landing page - mobile
![image](https://user-images.githubusercontent.com/12564977/76319139-22c28f00-62b5-11ea-83a4-950f48e81b91.png)

## Meeting attendees from **requesting team**
- Designer(s) (required): **Jennifer Lee** @jenniferlee-dsva, **Ryan Thurlwell** @rtwell 
- Product Manager (optional): **Aruna Kucherlapati** @AkucherGCIO 
- DEPO design lead (required as applicable): **Ryan Thurlwell** @rtwell 

## Scheduling
Preferred dates or times: Not Fridays or Thursdays from 12:30–2:30

## Additional Notes
A couple design notes:
- The main link in a search result title borrows the Hub link pattern as seen on any [hub page](https://www.va.gov/health-care/) **however there are some accessibility concerns with the current hub page implementation** as @jenstrickland has noted (insert github issue here). That said, we could both create a better version for this design and then refactor the hub page links with our shiny new Jen-approved implementation.
- As discussed in #6273 , we will not be adding file sizes to the `Download VA form XYZ (PDF)` link. 

During this collaboration point, you will receive feedback from the following practice areas: design, accessibility

**Comment by jenniferlee-dsva** [comment]
I updated ^ the name of the product, so this doesn't get conflated with search landing page templates (which we're also going to develop).

**Comment by 1Copenut** [comment]
VSP design accessibility feedback
---

**❗️ Must**

* Manage focus when users press Search. Ideally we would move focus to the "Showing results for `SEARCH TERM`"

  * It will be too much information read back if we use `aria-live` region

* Focus will need to be managed when we have pagination too. Probably set focus back to the same spot.

* "Apply online" button will need an aria-label or SR-only text to be clear to screen readers. For instance:

  ```html
  <a href="#">
  	<span aria-hidden="true">Apply online</span>
    <span class="sr-only"Apply online for 10-10072 Supportive Services for Veteran Families</span>
  </a>
  ```



**⚠️ Should**

* Download links should follow the [accessible pattern](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/152#issuecomment-553127340) VSA/VSP accessibility specialists collaborated on
* Consolidate language for the Go to... links. One says "Go to online tool", the other says "Apply online"
* List the number of results. Something like "Showing 5 results for 10-10"
* Ensure the horizontal rules are either lower borders on the cards or have an `aria-hidden="true"` attribute applied. These are stops for screen readers and generate cognitive noise.
* Current page in the breadcrumb should be bold
* Mobile version should include the back-by-one breadcrumb `< Home`



**✔️ Consider**

* Following the date format outlined in our [Dates and years](https://design.va.gov/content-style-guide/dates-and-numbers#dates-and-years) content section

**Comment by emilywaggoner** [comment]
We did not have any explicit design feedback, as everything looks good to go! The only item to note that we discussed during the meeting (but is not in the mockups), is that the pagination component will be used when these changes are built out. 👍

**Comment by meganhkelley** [comment]
Meeting completed 3/12

**Comment by jenniferlee-dsva** [comment]
Can this design intent ticket be closed?

**Comment by CrystabelReiter** [comment]
@jenniferlee-dsva Yup closed!
