### ISSUE TITLE
VaProfile caching strategy implementation

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#67106]
### Description

Updating all EMISRedis calls to a new EMISRedis VaProfile namespace.

- [ ] Removing calls to EMISRedis::MiltaryInformation
- [ ] Updating caching namespace to va-profile emis namespace
- [ ] Ensure all EMIS redis calls have been replaced
- [ ] Run rake command to ensure cache:
```
def veteran_cache
  count = 0
  veteran = 0
   namespace = '{{namespace}}'
   redis = $redis
   redis.scan_each(match: "#{namespace}:*") do |key|
     count += 1
     resp = Oj.load(redis.get(key))[:response]
     veteran += 1 if any_veteran_indicator?(resp.items.first)
   rescue
     puts "Couldn't parse #{key}"
   end

   puts "Total cached EMIS responses: #{count}"
   puts "Veterans: #{veteran}"
end
```

**Comment by laineymajor** [comment]
Recently started. Added caching, gave the PR to Lindsey for review. Testing today to get ready for the dev deploy on Monday (but not a hard req for the dev deploy)

**Comment by laineymajor** [comment]
In progress/on track. Ryan working to address comments in PR right now

**Comment by laineymajor** [comment]
Ryan currently working on this implementation. 
- [ ] Needs to build and test specs

**Comment by laineymajor** [comment]
Tests are fixed. Will push out changes today.

**Comment by LindseySaari** [comment]
Have been chatting with Ryan this morning and working through failing specs.

**Comment by laineymajor** [comment]
Ryan working on failing specs (from 28, down to 6 remaining specs failing)

**Comment by laineymajor** [comment]
Working on ID attribute specs that are failing

**Comment by laineymajor** [comment]
Gonna chat with Lindsey to finish this one out.
- The error seems to be getting more nested in the ID attributes.

**Comment by laineymajor** [comment]
The final failing spec is passing. Working on remaining cleanup issues. 
Ryan will test in a RI when these cleanup items are complete. Then can close!
*Reach out to Rebecca if having trouble ssh(ing) into the RIs.

**Comment by laineymajor** [comment]
ryan and rebecca working working on testing
modifying remaining specs

**Comment by laineymajor** [comment]
all tests are now passing!

**Comment by laineymajor** [comment]
ryan has a PR open for this one. addressing comments from rebecca and lindsey. will merge pr then test in staging!

**Comment by rjohnson2011** [comment]
Merged PR - https://github.com/department-of-veterans-affairs/vets-api/pull/14308
