### ISSUE TITLE
AWS access for [Zac Yellowhorse]

### ISSUE THREAD

**Issue by zyellowhorse** [department-of-veterans-affairs/va.gov-team#67126]
### COR Name

COR: "Cook, Laurene (Reney)" <Laurene.Cook@va.gov>

### Vendor Onboarding Representative Name

Other - please specify in 'Additional Notes'

### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Zac Yellowhorse

### Your Email

zac.yellowhorse@oddball.io

### Team, Role, and Company of the target individual

VA.gov Identity Team, DevOps Engineer from Oddball

### Product Manager (PM) name and email

Mike King Mike.King@oddball.io

### Product Owner (PO) name and email

Thomas Black thomas.black2@va.gov

### Desired AWS Access

This is an additional AWS Access request as I already have access. You can find my other access request here https://github.com/department-of-veterans-affairs/va.gov-team/issues/64473

I am requesting that I have my permissions copied from Vid Jovanovic who is another member on my team. I am also a Devops Engineer and will need this access to complete my work. 

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

The screen shot of my E-QIP can be found here https://github.com/department-of-veterans-affairs/va.gov-team/issues/64473

### Additional Notes

COR: "Cook, Laurene (Reney)" <Laurene.Cook@va.gov>

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [ ] Search for user in [Atlas](https://dev.va.gov/atlas)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in Atlas, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by flooose** [comment]
@BillChapmanUSDS the permissions he's now requesting include prod access. I will need your approval.

**Comment by ph-One** [comment]
User has been informed that they're additional access has been granted/processed. Closing.
