### ISSUE TITLE
Contact Center Review for Veteran Facing Forms - 40-0247

### ISSUE THREAD

**Issue by tbaker1026** [department-of-veterans-affairs/va.gov-team#67131]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
 Digitizing form 40-0247 Presidential Memorial Certificate

### Launch Date
 Tentative 10/23/2023

### Version Number
Version 1

### Product Guide
[*Please provide product guide link*](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/40-0247/Form%2040-0247%20Product%20Guide.docx)

### Product Video
*Please provide product video link*

### Product Video Transcript
*Please provide product video transcript link*

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
Upcoming, per @tbaker1026. Will be in an upcoming sprint, assignment TBA.

**Comment by ATMiddleton** [comment]
@starlow00 is awaiting additional information

**Comment by tbaker1026** [comment]
@ATMiddleton @starlow00 - This is going to staging review on Nov 30th.  Please let me know what additional information is needed.

**Comment by starlow00** [comment]
Hi, @tbaker1026. Thank you for the update. No additional info is needed; I will move this along ASAP.

**Comment by starlow00** [comment]
The draft looks good. Sent to VEO for their review.

**Comment by starlow00** [comment]
@tbaker1026, I do want to follow up with you on one point. The guide mentions that the PMC enables family and close friends of Veterans to apply for "one of two types of grants." However, the product guide doesn't elaborate on this. It would be worthwhile to give a general flavor for those grant types. Can you please assist? A brief description would work.

**Comment by tbaker1026** [comment]
@starlow00 sorry that was a copy and paste error - I removed language about the grants and updated it - new Product Guide

https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/40-0247/Form%2040-0247%20Product%20Guide%20(1).docx

**Comment by starlow00** [comment]
No worries, thanks @tbaker1026! I'll update and send it on today.

**Comment by starlow00** [comment]
Sent to VEO for review.

**Comment by starlow00** [comment]
No changes from VEO. Copy attached.
[Form 40-0247 Product Guide SRT 11212023.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHYrQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d99c033d6bcb9df076101a2a3d4a3adec1e49748/Form%2040-0247%20Product%20Guide%20SRT%2011212023.docx)
