### ISSUE TITLE
Long, unbroken comments break card layout

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#6713]
![VAOSR_LongComments_VAMCAddressDisplaysWonky.PNG](https://images.zenhubusercontent.com/599c94608f62dc7798c3b2cd/a9865474-5743-468a-8291-24f3ca816a82)

We should be able to address that by adjusting the flex grow/shrink values or setting the word-break or white-space properties.

**Comment by lenaecb** [comment]
@jenniemc - are we good to close this?

**Comment by jenniemc** [comment]
@lenaecb, Just closed the ticket.
