### ISSUE TITLE
Remove "enrollment and eligibility" content from footer of VAOS 

### ISSUE THREAD

**Issue by lalexanderson-dsva** [department-of-veterans-affairs/va.gov-team#6714]
## User Story or Problem Statement
- As a user, I do not want to be directed to call HRC for health care enrollment and eligibility questions, because they cannot answer those questions. 

## Goal
- Update the text in the footer around the HRC contact info. 

> For help scheduling a VA or Community Care appointment, **or if you have questions about enrollment or eligibility**... 

We need to remove enrollment and eligibility. 

---
## Tasks
- [ ] _Update footer to remove eligibility and enrollment text_

## Acceptance Criteria
- [ ] _Footer will only direct users to call HRC for help requesting/scheduling/canceling appointments. _
---

**Comment by peggygannon** [comment]
@lalexanderson-dsva @jbalboni  

Here is updated footer content: 

For help scheduling a VA or Community Care appointment, please call 877-470-5947 (if you have hearing loss, call TTY: 711). We’re here Monday-Friday, 8:00 a.m. to 8:00 p.m. ET. 

For questions about joining a VA Video Connect appointment, please call 866-651-3180 (if you have hearing loss, call TTY: 711). We’re here Monday-Saturday, 7:00 a.m. to 11:00 p.m. ET. 

[Leave feedback for this application]

If you want to use the old online scheduling tool, you can [go back to the old VA appointment tool] (https://veteran.mobile.va.gov/var/v4/)
