### ISSUE TITLE
Placeholder for other f/u from 66318

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#67168]

**Comment by benbrasso-agile6** [comment]
@cgednalske you're in charge of this ticket following the meeting on Tuesday

**Comment by benbrasso-agile6** [comment]
Decided we don't need this via decision in https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/66318
