### ISSUE TITLE
Accessibility Feedback for BDD usability testing prep #6623

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#6717]

**Comment by jenstrickland** [comment]
- Will the autosave notice be appropriate for this form?
- Additional conditions on 3 of 4 Disabilities - a lot of extra space before radios (will comment on Invision)
- Bulleted items on Summary of disabilities, spacing of bullet and text should align with design system (will comment on Invision)
- The option to Track the status of your claim or appeal seems it should probably be higher up on the page, near the confirmation notice, as it is likely to be missed on mobile and by screen reader users. (will comment on Invision)

**Comment by chrvalla** [comment]
Hi Jennifer

Thank you for your helpful comments. 

I will work on correcting these today. 

Best, Christian

**Comment by chrvalla** [comment]
All of these changes have been implemented in the BDD prototype on 8th April 2020.
