### ISSUE TITLE
SPIKE: How can we Measure & Report How Long it Takes to Complete Check-in (w/ and w/o travel) 

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#67177]
## Time boxed
2 days

## Background
IVC has asked us to measure and report to them how long it takes to complete check-in with and without travel.

Ask: Average length of time to do eCheck-in with and without travel.

## Assumptions
- Count only Vets **who get a successful completion of check-in** (i.e. failures or abandonments are not counted)
- Starting point should be when eCheckinStarted is set
- Ending point should be when eCheckinCompleted is set
- We will need to use DataDog to get this data
- We may need to use Excel to calculate min/max/avg

## Tasks
- Determine what work is necessary to measure how long it takes to perform check-in for Veterans where travel **IS NOT** enabled
     - Per individual user
     - Min across all users
     - Max across all users
     - Average across all users
-  Determine what work is necessary to measure how long it takes to perform check-in for Veterans where travel **IS** enabled and the Veteran successfully submits a claim to the BTSSS API (regardless if claim is accepted)
     - Per individual user
     - Min across all users
     - Max across all users
     - Average across all users
 - Create implementation tickets

**Comment by lee-delarm6** [comment]
@loripusey Didn't we decide to do this in datadog so we could capture the start and end between when a user had the text message? The spike at least, which I think this ticket is ( @brianseek )

**Comment by loripusey** [comment]
Yes, we did; if a SPIKE is not needed, we can turn this into a work ticket. I just don't know if there is additional information to think through for this effort or not.

**Comment by brianseek** [comment]
Notes: We will look into how check-in steps records this. Reach out to Adrian on datadog dashboard ideas.

I will pick this up and add implementation notes as soon as I have it.

**Comment by brianseek** [comment]
Result of this spike:
This data should already be stored in vista with in the check-in steps (thanks for pointing that out Kanchana!). There is a timestamp for each step. So we could propose that IVC get the data from the staff facing side.

If we decide to move forward with us doing the work. It would require logging custom metrics from CHIP into datadog. The idea would be to write a started timestamp into lorota, then on complete we would fetch that timestamp and record the delta with a custom metric. We would also want to add a tag for if travel was enabled and if travel was submitted. To get that info we would need to pass it from the frontend to the backend and finally to CHIP. This would take several tickets, but would need to start with a spike ticket focused on implementing the custom metrics in CHIP and seeing what we can do with it in datadog.

cc @loripusey

**Comment by loripusey** [comment]
I don't think vista has the information about whether it involved travel or not, so I think we will need to do the custom metrics. I created this [ticket ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/68147)to do this work next sprint.

**Comment by brianseek** [comment]
@loripusey sounds good. I will make some changes to convert the ticket into a metrics spike and create the other tickets that are blocked by the new spike.

**Comment by brianseek** [comment]
all new tickets including spike:

- 68147
- 68163
- 68165
- 68166
