### ISSUE TITLE
Access for Phil Herbert

### ISSUE THREAD

**Issue by philherbert** [department-of-veterans-affairs/va.gov-team#6719]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Bryan Broome
- Please provide your name.
   > Phil Herbert
- Please provide the name of your team, your role on that team, and the name of the company you work for.
  > Team: @thoughtworks 
  > Role: Developer
  > Company: ThoughtWorks
  > I am part of a team at ThoughtWorks that is working with the CTO's office to update va.gov/scorecard. I have a PIV card that I was granted in January 2020. I am requesting access to the SOCKS proxy and Jenkins / Prometheus / Grafana so we can 
  > - Modify / update Jenkins job configs
  > - Kick off Jenkins jobs
  > - Review Prometheus data, some of which is imported into the scorecard
  > - Review Grafana data for the scorecard
  
  > If you have any questions or concerns please let me know, or reach out on slack on #va-scorecard-refresh
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Internal%20Tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCslhyi0NcRiluxC8IzaNy/zwzIONNRo1NIAdVE77RRUsiclXRW9FJ7tR3RLtCA5x5s9E7lH7vcMwLkYiCDNQJk9DsdLYJSyi1e4C7Zy+WvefPAJYidSBf8kJpznmt9W7SY0pUtCy6AEuCacDiOE5C/KantjwNdNWB015PiqjH3mhSilZ9SPsrdyYCmKSaRVs9XD73ZKSm/MYQQ6gjRN4cHAXyVuWDR1vm3rRpXNdMiGZ6ShNHQ0Qcc9tjE3kNubZQgOtQgbyLLrgHxdSW51OSKauup+3L26RVEmjBwEeNzG1uGdOXEDOI2ql36EPPR9JquhfvMnDQSZQJ0lFtboflP philip.herbert@va.gov
```

- [Grant AWS Console access?]
  > YES

**Comment by philherbert** [comment]
@department-of-veterans-affairs/vsp-operations 

Please review! Thanks

**Comment by jbritt1** [comment]
SOCKS access granted. @philherbert, please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.

**Comment by CourtneyBethea** [comment]
Phil, I am the person that On-Boarded you but I do not grant access to the Application Below.  Please email Crystal Moultrie, she is your official COR that may give you access to these systems.

Thanks

CB

Courtney B. Bethea
PMP,  PMI-ACP, LSSBB, FAC-COR, FAC-P/PM, ITIL, BTS, CPO
IT Project Manager
Project Special Forces
Work Hours M-Th 6:00am – 4:30pm
PHONE: 732-757-7467

**Comment by philherbert** [comment]
Reopening, and changing my request to include AWS Console Access. Thanks!

**Comment by ffafara-tw** [comment]
**AWS Access:**
User: Phil Herbert
COR: Bryan Broome
Approver: @Jeff-Hayter

**Comment by Jeff-Hayter** [comment]
@ffafara-tw @jbritt1 Approved for AWS access.

**Comment by jbritt1** [comment]
First time login credentials provided privately to user.
