### ISSUE TITLE
Va Profile Veteran Status Caching Design Doc + Documentation

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#67191]
## Description

As part of the eMIS to Va Profile migration for veteran status info, we need to implement caching for performance improvement reasons. As part of the implementation, we should create a design doc detailing the caching strategy. This will be [complimentary to this ticket.](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/64549). Additionally, we don't have great documentation around caching standards in Vets API. This could additionally be part of the scope (or at least started).

**Comment by laineymajor** [comment]
This [template](https://vfs.atlassian.net/wiki/spaces/TT1/pages/2795372615/Caching+Strategy+Design+Document+WIP) might help... if not, let's archive it!

**Comment by laineymajor** [comment]
Ryan will start this as soon as done with other ticket. Will tag team with Lindsey.

**Comment by laineymajor** [comment]
Near complete but will circle back to this after moving the veteran_status work to dev...

**Comment by laineymajor** [comment]
Awaiting review from team, then will make edits (as needed) and close.

**Comment by LindseySaari** [comment]
Made edits and closing this ticket! Design doc done!
