### ISSUE TITLE
Accessibility Testing for Veteran Facing Forms - 21-0966

### ISSUE THREAD

**Issue by tbaker1026** [department-of-veterans-affairs/va.gov-team#67208]
### Product information

- [X] Team name, product name, and feature name have been added to the title of this issue.
- [X] Team label, product label and feature label (if applicable) have been added to this issue.

### Who completed the use of color and color contrast test?

@jeana-adhoc 

### Use of color and color contrast checks

- [x] All text of 20px or smaller has a 4.5:1 contrast ratio to its background (or better)
- [x] All text of 20px or larger has a 3:1 contrast ratio to its background (or better)
- [x] Non-text elements have a 3:1  contrast ratio to their background and to neighboring elements (or better)
- [x] Color is not the only way to distinguish links from other text (eg. links are underlined)
- [x] Any charts, maps, infographics, and tables convey all information without only relying on color
- [x] Content does not refer to color, especially when providing user instructions (eg. "Click the blue button")

### How did color testing go?

No issues

### Who completed the axe scans?

@jeana-adhoc 

### axe checks

- [x] Each page has been scanned using axe (results shared below)
- [x] axe is integrated into your end-to-end testing

### axe DevTools scan results

| Axe Results  | Page |
| ------------- | ------------- |
| No issues  | [Introduction](https://staging.va.gov/supporting-forms-for-claims/intent-to-file-a-claim-form-21-0966/introduction)  |
| No issues | [Preparer information](https://staging.va.gov/supporting-forms-for-claims/intent-to-file-a-claim-form-21-0966/preparer-identification) |
| No issues | [3rd Party Preparer name](https://staging.va.gov/supporting-forms-for-claims/intent-to-file-a-claim-form-21-0966/preparer-name) |
| No issues | [3rd Party Role](https://staging.va.gov/supporting-forms-for-claims/intent-to-file-a-claim-form-21-0966/third-party-preparer-role) |
| No issues | [Benefit selection (Veteran)](https://staging.va.gov/supporting-forms-for-claims/intent-to-file-a-claim-form-21-0966/benefit-selection-1) |
| No issues | [Benefit selection (Survivor)](https://staging.va.gov/supporting-forms-for-claims/intent-to-file-a-claim-form-21-0966/benefit-selection-2) |
| No issues | [Name & DOB](https://staging.va.gov/supporting-forms-for-claims/intent-to-file-a-claim-form-21-0966/personal-information)  |
| No issues | [Identification information](https://staging.va.gov/supporting-forms-for-claims/intent-to-file-a-claim-form-21-0966/identification-information) |
| No issues | [Mailing address](https://staging.va.gov/supporting-forms-for-claims/intent-to-file-a-claim-form-21-0966/mailing-address) |
| No issues | [Phone & Email](https://staging.va.gov/supporting-forms-for-claims/intent-to-file-a-claim-form-21-0966/phone-and-email-address) |
| No issues | [Veteran name & dob](https://staging.va.gov/supporting-forms-for-claims/intent-to-file-a-claim-form-21-0966/veteran-personal-information) |
| No issues | [Veteran identification information](https://staging.va.gov/supporting-forms-for-claims/intent-to-file-a-claim-form-21-0966/veteran-identification-information) |
| No issues | [Relationship to veteran](https://staging.va.gov/supporting-forms-for-claims/intent-to-file-a-claim-form-21-0966/relationship-to-veteran) |
| No issues | [Review page](https://staging.va.gov/supporting-forms-for-claims/intent-to-file-a-claim-form-21-0966/review-and-submit) |

All pages now have one new error that is out of the forms team control. But this ticket, https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15568 covers the issue.

### How did axe testing go?

The only issue is the one documented here https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15568, but it is on all pages.

### Who completed the content zoom and reflow test?

@jeana-adhoc 

### Content zoom and reflow checks

- [X] All page elements are readable and usable at 200% zoom
- [X] All page elements are readable and usable at 300% zoom
- [X] All page elements are readable and usable at 400% zoom

### How did content zoom and reflow testing go?

No issues

### Who completed the keyboard navigation test?

@jeana-adhoc 

### Keyboard navigation checks

- [ ] Each link, button, form input, checkbox, radio button, select menu, and custom element can receive keyboard focus
- [ ] Each link, button, form input, checkbox, radio button, select menu, and custom element responds to expected keys
- [ ] All elements under focus have a visible focus indicator
- [ ] The order of [Tab] stops made sense and was appropriate for completing tasks

### How did keyboard testing go?

Some issues were identified.

#### Introduction page/OMB Component (DST)
- **Ticket for the design system:** https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2207
  
The OMB component "View Privacy Act Statement" button (modal) is not behaving as expected. 
  - it is possible to tab backwards out of the modal
  - When you close the modal, focus does not return to the "View Privacy Act Statement" button and focus is lost

#### Focus (Forms-team)
- **Ticket for Forms team:** https://github.com/department-of-veterans-affairs/VA.gov-team-forms/issues/749

1. Focus is lost going from the introduction page to the first page in the form. What I observe is that when going from the intro page, to the first page of the form, the page loads at the bottom, and the focus is at the top on the "skip to content" link. Focus is not managed at all here. Focus should go to the h2: "Step 1 of 3: Your identity". There no sound in the video, but you can see the transcript of the screen reader. **Note:** I thought we had encountered this before in the PMC... [And Robert ended up doing this](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/utilities/ui/focus.js#L2) (Now, granted this might not have anything to do with the issue... just trying to provide some help_

https://github.com/department-of-veterans-affairs/va.gov-team/assets/117098918/b1794ed4-c4f5-455d-bc31-73039f041af7

<br /><br />

2. Focus is also lost when navigating to the confirmation page. Focus should go to the `H2` "You've submitted your... " or "You've already submitted your.."

<img width="400" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/117098918/1cf51507-b188-43a2-90f3-dc11e0763ad9">

#### Review page - Headings & aria-labels (Forms-team)
- **Ticket for Forms team:** https://github.com/department-of-veterans-affairs/VA.gov-team-forms/issues/750

There were a number of heading issues and aria-label issues with the review pages of all four stories. I've marked up PDFs to indicate what needs to be updated

- [Veteran - story 1.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/13267085/21-0966.Intent.To.File.A.Claim._.Veterans.Affairs.-.story.1.pdf)
- [Survivor - story 2.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/13267083/21-0966.Intent.To.File.A.Claim._.Veterans.Affairs.-.story.2.pdf)
- [3rd party for Veteran - story 3.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/13267082/21-0966.Intent.To.File.A.Claim._.Veterans.Affairs.-.story.3.pdf)
- [3rd party for Survivor - story 4.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/13267081/21-0966.Intent.To.File.A.Claim._.Veterans.Affairs.-.story.4.pdf)

Here is an example heading structure on the review page (this is wrong):
H2.  Step 6 of 6 Review Application
&nbsp;&nbsp; H3. Your identity
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; H4. Your identity
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; H4. Your name
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; H4. Your role
&nbsp;&nbsp; H3. Claimant's benefit selection
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; H4. Claimant's benefit selection
&nbsp;&nbsp; H3. Claimant's personal information
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; H4. Claimant's personal information
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; H4. Identification information
&nbsp;&nbsp; H3. Claimant's contact information
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; H4. Mailing address
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; H4. Phone and email address
&nbsp;&nbsp; H3. Veteran's personal information
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; H4. Veteran's name and date of birth
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; H4. Identification information
&nbsp;&nbsp; H3. Statement of truth        

In the PDFs I recommend this

Here is an example heading structure on the review page for story 4 - 3rd party for a survivor claimant:

**H2**.  Step 6 of 6 Review Application
&nbsp;&nbsp; **H3**. Your identity
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; **H4**. Form preparer
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; **Edit** aria-label="Edit Form preparer"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; **H4**. Your name
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; **Edit** aria-label="Edit Your name"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; **H4**. Your role
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; **Edit** aria-label="Edit Your role"
&nbsp;&nbsp; **H3**. Claimant's benefit selection
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ~~H4. Claimant's benefit selection~~
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; **Edit** aria-label="Edit Claimant's benefit selection"
&nbsp;&nbsp; **H3**. Claimant's personal information
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; **H4**. Name and date of birth
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; **Edit** aria-label="Edit Claimant's name and date of birth"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; **H4**. Identification information
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; **Edit** aria-label="Edit Clamant's identification information"
&nbsp;&nbsp; **H3**. Claimant's contact information
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; **H4.** Mailing address
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; **Edit** aria-label="Edit Claimant's mailing address"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; **H4.** Phone and email address
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; **Edit** aria-label="Edit Claimant's phone and email address"
&nbsp;&nbsp; **H3.** Veteran's personal information
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; **H4.** Name and date of birth
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; **Edit** aria-label="Edit Veteran's name and date of birth"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; **H4.** Identification information
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; **Edit** aria-label="Edit Veteran's identification information"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; **H4.** Claimant's relationship to the Veteran
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; **Edit** aria-label="Edit Claimant's relationship to the Veteran"
&nbsp;&nbsp; **H3.** Statement of truth     

This reduces redundancy in the heading structure, and structures each group similarly.

Also related to the review page:
Also, on the review page, the "Your benefit selection" edit button has an incorrect/incomplete aria-label. The edit button says, "Edit function(e){return Wx({formData:e})}, button"
<img width="450" alt="Screenshot 2023-11-04 at 10 45 43 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/117098918/48bb393a-2e52-4fc4-8357-194e07299660"><br /><br />
It should say "Edit Your Benefits selection"

#### For Design System
1. (* Required) on this page `/21-0966/pages/veteranBenefitSelection.js` is in the wrong font
<img width="450" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/117098918/6ef81c2c-b7ce-42e9-9361-b57823b3bd1b">

- **Ticket for the design system:** https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2251

#### Other concerns
1. I have a concern about a destructive action not being announced: If a user clicks edit to change their selection for "Your identity" the answers to the entire form are cleared out without notice. This was put into place because if they did select the wrong identity, the answers are presumably in the wrong pace throughout the form and we don't want users to submit incorrect data. However, currently, if a user is even *curious* about what that "edit" button does, there is no "cancel" there is no non-destructive option. Ideally, we should let them make their selection, and once they click "update" provide a modal that announces the destructive change, and puts they back at the start of the form if they approve the change. OR, we could not have a destructive element at all, and the user will need to verify on their own the changes to the form. 

2. I have a concern about authenticated experience not using prefill - we are using their ICN information to determine the ITF status, yet allowing the Veteran to input all new information that we probably already have available from Profile, shouldn't we be showing this information and allowing the Veteran to confirm this information?  Can we do prefill on the authenticated experience and use the prefill information to populate "YOUR" fields?  What could happen is someone fill out the form while logged in, but change the information to be for a different user, but it won't matter, because it's the profile information that's being submitted, not the information in the form fields that user is typing. Even the confirmation page says it's filled out by the filled out fields, but it's really submitted using the profile data if an ICN is present.

**Comment by jeana-adhoc** [comment]
This is not complete. There were a lot of tickets filed for the catch-all after I had done some basic testing. I'd like to wait until more of those fixes are on staging before I complete the testing.

**Comment by jeana-adhoc** [comment]
Restarting this work on 11/2/23

**Comment by jeana-adhoc** [comment]
Testing complete.

**Tickets for CMS related to this testing:**
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15568

**Tickets for the Design system related to this testing:**
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2207
- https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2251

**Tickets for the forms team related to this testing:**
- https://github.com/department-of-veterans-affairs/VA.gov-team-forms/issues/749
- https://github.com/department-of-veterans-affairs/VA.gov-team-forms/issues/750
