### ISSUE TITLE
Usability Testing Prep - Design review- BDD form

### ISSUE THREAD

**Issue by CrystabelReiter** [department-of-veterans-affairs/va.gov-team#6720]
### User story

VSP Design feedback on BDD section of 526EZ form (Usability Testing Prep stage)

Template prototype we're reviewing: https://vsateams.invisionapp.com/share/Z8W8ACWN3UG#/

### Design feedback

**Do:**

- **Page: How to File** - Remove the back/continue buttons from the bottom
- **Page: Contact Information** - There is a text alignment problem with the Country dropdown
- **On all form pages:** Make the interactive target include the labels in addition to the checkboxes and radio buttons [relevant pages: Military history, Disabilities > neck sprain, Additional Conditions, Review Applications privacy policy]
- **Page: Military history** - It looks like Arial or Helvetica is used for the "Most Recent Entry date" group label and input text - change back to source sans pro
- **Page: Disabilities**, Details about your condition - Change "Condition(s)" to "Condition" - we should be able to detect if they put one or multiple and adjust the language accordingly
- **On the Review Application screen**, make the interactive targets contain the entire gray box, not just the plus signs
- **Page: Review/Submit** - I didn't see the Forwarding Address screen in the flow but it appears here. Remove if it's not part of this form. [Question: is it?]
- **Page: Confirmation** - The blue  information callout box “Your request details” should be in bitter heading H3

**Try**
- **Page: Confirmation** - Adjust margin between breadcrumb and h1 (increase)

**Consider**
- **On Disabilities** > Neck Sprain > Explanation screen, try moving the text area to the left and removing the extra margin

**Comment by chrvalla** [comment]
Hello. Thank you for all your helpful comments. 

I have made all the adjustments you suggested. 

Best, 

Christian
