### ISSUE TITLE
Content review: Print styles template

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#6722]
## User story
VSP Content feedback on Print style template

Template prototype we're reviewing: https://vsateams.invisionapp.com/share/ATW7AI7QXCV#/screens/407225752

## Content feedback

Use of boldface: My recommendation is to only  boldface headers and subheaders

Content recommendations: 

- [x] Apply for health care screens
Veteran information subhead is repeated several times. Is there anyway to remove the subheads and just have the main Veteran information head? 

- [x] Hearing aid and batteries screen
Qty should be spelled out to Quantity.. I know this will be fixed once we update this in the actual form. 

- [x] More general feedback
Sounds like you're aiming to test this out with the Caregivers form. I recommend at the next Caregiver form checkpoint, we review the print screen for that form.

**Comment by rileyorr** [comment]
@jonathanjnelson has @peggygannon's feedback been incorporated so we can close this ticket?
