### ISSUE TITLE
Staging Review Design Review - Print Styles

### ISSUE THREAD

**Issue by CrystabelReiter** [department-of-veterans-affairs/va.gov-team#6723]
### User story

VSP Design feedback on print styles

Template prototype we're reviewing: https://vsateams.invisionapp.com/share/ATW7AI7QXCV

### Design feedback
This is awesome work and thanks for taking initiative in creating these!

**Try**
- Spelling out any abbreviations (ex: qty -> quantity) - may be more content feedback
- On the Review & Submit screens, it's clear which elements are bold - the data that the user input. It's less clear and consistent on the confirmation screens. For example - Submission date and conf number labels are bold, but not the data for those labels. Then the "For Jonathan Jacobsen" answer is bold along with the label. Try applying the same rule -- bold the data, not the label -- to these screens.

**Consider**
- Left-aligning all of the content -- aka removing all indentations
- On the Review and Submit screen, the Veteran Information heading is repeated 4 times. Consider using a different element to break up the content (if necessary) or find ways to reduce the repetition (may need consulting from devs to make sure that is possible -- and it's also a problem)

**Comment by rileyorr** [comment]
@jonathanjnelson has @CrystabelReiter's feedback been incorporated so we can close this ticket?

**Comment by jonathanjnelson** [comment]
Yes, sorry about that.
