### ISSUE TITLE
SOCKS access for Eric Tillberg

### ISSUE THREAD

**Issue by Thrillberg** [department-of-veterans-affairs/va.gov-team#67236]
### Your Name

Eric Tillberg

### Your Email

etillberg@pluribusdigital.com

### Your Role and Team

Senior Full Stack Engineer on Forms Team

### Product Manager (PM) name and email

Tricia Baker tricia.baker@oddball.io

### Product Owner (PO) name and email

Matthew Dingee matthew.dingee@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDTDtatQ4Lg+0jqZAAOkSzg+tdL7KK1yBkybNnCkaqVlAgHNXGZuiYDhUR6BPGvRyBr2oGCl2CdRgkYnk6b/nV/dMQtd2db4ZcC9guvMNZYyRYf9lGU5vlDJEZNSe5MzQMQDwTnidaNNBPtYjyIKWIpxnMuy44IGsyU0WxcHOwyHUb4tAaxwFbR1mSD9897a8YXsNgwhIxcufn8mgJ+13D1TqBm6HgJmWOOZLLjuyFPXkrwTC9j9Rxw2Ya0GpV7Jh9glIfnnVHRS5UyDId9ARqasZp7S6frgVcD15XZV9EuIfNiw8jvSU3CG1AI9ZE3qzwYWK5xcUYdEMct1DSW0mzIve9vHkUu8ftqG44DfwLLiCbkQg+JQ2AuXEJBgrhMyAh504AFvvsnfvI+k7lPrQE1mc3Vs/FTTE2rjIeFNcnMf1aGQKDSZYVUCbzq1o5ROW9jB0ErCFhKTfdpbWT81zFi5ReEGpGV63ngimWdkvrxQT0tCLojc/275siWyAIdvq0= erictillberg@erics-mbp.lan

### E-QIP Transmittal Confirmation

<img width="1053" alt="Screenshot 2023-10-10 at 2 49 23 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/10481391/f1792daa-e253-49bd-a7e3-eb18d2760ab3">

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by ph-One** [comment]
SOCKS access completed
