### ISSUE TITLE
[Design] OOUX Working Sessions & Planning

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#67238]
## Issue Description

**Meeting Agenda**
Preparing and running optional mini-OOUX learning sessions (Object Oriented User Experience) for the team. Planning on this being weekly and us working through the OOUX process together using the EZ/EZR forms! I want this to be a fun space for us to learn together.

I've put together [a slide deck](https://docs.google.com/presentation/d/1ZIoOl_Hsqzp-9cEZn_JAOh0-ZBqmh01PyUOvQZbc2vI/edit?usp=sharing) to walk us through the OOUX process. I'll add slides as we go, so consider it a living document that will change with time. Feel free to check it out and add comments/questions!

**Tentative Schedule**
**Session 1:** Intro to OOUX and noun-foraging exercise
**Session 2:** Getting into the ORCA process and noun consolidation

---

## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by katelyncai** [comment]
Most of the documentation for this ended up on [a duplicate ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/68443). Closing this out. We plan to revisit our OOUX sessions in the new year, possibly applying the process to our work on Registration.
