### ISSUE TITLE
Research: prep for conversations with SMEs about cohort review

### ISSUE THREAD

**Issue by buddhima-coforma** [department-of-veterans-affairs/va.gov-team#67246]
### Description
Schedule/facilitate conversations with SMEs about validating cohorts for outreach.
This is to inform the manual review of selected individuals, to ensure that the selected cohort has high likelihood of receiving presumptive benefits.

This is to account for what's known now, and not about what will be known once a claim is submitted (as factors can change at that point).

### Activities
- Conversation guide @djones2113 
- Conversation with Karla next week to learn how we could do this
- Work with identified partners to achieve this

**Comment by djones2113** [comment]
FYI I started a (mostly empty) [conversation guide](https://docs.google.com/document/d/1BwWRKIa3cKbWmF3gfAUMuK9PXTTWoADGFUQ_RUE4QZA/edit) for our call with Karla on Tuesday. Feel free to add anything to it!

**Comment by aplatt-coforma** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-proactive-64e7650c29bb1113de04a02a/issues/department-of-veterans-affairs/va.gov-team/67246?planning-poker) with Zenhub @christiejibaraki

**Comment by christiejibaraki** [comment]
I updated this ticket to reflect was done in the comments above (i.e. convos with Karla and Emily) but closing because this overlaps with #68903. Adding #70473 as the follow up to #68903..
