### ISSUE TITLE
[FE] Put 45-minute Content behind Pilot Feature 

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#67255]
## Tasks
- Use the new pilot feature utility
- Wrap the content in the new pilot feature utility
- Update tests
- Add the stations from [this thread](https://dsva.slack.com/archives/C022AC2STBM/p1698076388436609) to the pilot

**Comment by brianseek** [comment]
moving this to closed since there is nothing to validate beyond the code review
