### ISSUE TITLE
Adding Gus Schissler to DSVA Slack

### ISSUE THREAD

**Issue by huggins-va** [department-of-veterans-affairs/va.gov-team#67256]
Are you requesting to add Mark Augustine Schissler, Jr (Gus) an individual as a:
- **Multi-channel user to the following channels:**
-vaapi-apigee
-team-koala
-vaapi-consumer-support
-team-okapi
-vaapi-platform
-team-quokka
-team-cassowary
-api-facilities
-team-marmoset
-vaapi-auth
-team-pivot

Gus Schissler is the new Product Crew Lead for the Public API Platform Crew and will need access to all teams in the Public API Platform.

Gus does not have a Github account yet. 

Thank you,
Nora

**Comment by LEHigley** [comment]
need an email address

**Comment by LEHigley** [comment]
@huggins-va got this via email--please include in tickets in the future. thanks! 

email address is [Gus.schissler@adhocteam.us](mailto:Gus.schissler@adhocteam.us)
