### ISSUE TITLE
Design Intent - Design Feedback - Identity, Sign in Service, Sign out all devices

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#67253]
## VFS actions
- [x] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [x] Comment on this ticket:
  - [x] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [x] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [x] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [x] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- There is a section in Profile for connected devices. It is supposed to allow users to link things like FitBits. You may want to poke around in there and make sure you don't use the same verbiage. Make sure users are clear on connect4ed devices and logout. Everything is looking great so far!

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

-

**Comment by shiragoodman** [comment]
@charlye-bluetiger @joeniquette This is the message I received from @karlbrown-va when the Digital Health Platform project ended:

> The DHP project is sadly coming to a close. As you may know, there is a bit of code inside of vets-api /va-website that runs a Fitbit signup flow. It is possible that a team under Angela Gant-Curtis are interested in the code and infrastructure, so we've made a decision for now to pause the project while they explore what if anything they want to do with this infra. This means, no new jobs/functions will be started and all of our github daily jobs will be disabled, and we will  feature toggle off any DHP-related code on [VA.gov](http://va.gov/).

> At the same time we have put together a full shutdown plan which is linked below. This includes plans to remove all of the code from [VA.gov](http://va.gov/), and remove any S3 buckets once we determine how long we need to keep those things for.
> https://github.com/department-of-veterans-affairs/digital-health-platform-team/blob/main/docs/handover.md#shutdown-plan

I am uncertain if this impacts any connected devices in Profile, but thought I'd pass along in case it's information you need to know.

**Comment by charlye-bluetiger** [comment]
We'll make sure to ask about "connected devices" in our research.
