### ISSUE TITLE
API Helm Chart Discovery for Implementation 

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#67264]
From ticket
Discovery: Should we automate the packaging of the Vets API helm chart#64977

Action Items:
- [x] Review the following information and tutorials to familiarize with helm charts
- https://github.com/argoproj/argocd-example-apps?tab=readme-ov-file
- https://github.com/argoproj/argocd-example-apps/tree/master/guestbook
- https://www.youtube.com/watch?v=w51lDVuRWuk
- [x] Review previous discovery ticket #64977
- [x] Review EKS upgrade documentation and define areas that need to be updated in Helm Charts (the actual updating will be a different ticket)

**Comment by laineymajor** [comment]
@flooose are you waiting on info from patrick for this? If so, guessing we should move this to next sprint. Will not doing this right now create a blocker for something else?

**Comment by flooose** [comment]
It shouldn't create a blocker for anything. I was waiting on Patrick, but I think he's been bogged down with other things, which is why I've focused on the redis updates. I was planning on getting back to this today.

**Comment by laineymajor** [comment]
This will carryover to next sprint.

**Comment by LindseySaari** [comment]
This is paused in favor of higher prio items

**Comment by laineymajor** [comment]
KS reviewing links above and completing exercises.
