### ISSUE TITLE
Vets-api terminal access for [Charley Stran]

### ISSUE THREAD

**Issue by charleystran** [department-of-veterans-affairs/va.gov-team#67284]
### Your Name

Charley Stran

### Your GitHub handle (terminal access is managed through GitHub)

charleystran

### Your dsvagovcloud AWS user name (if applicable)

Charley.Stran

### Team, Role, and Company of the target individual

VES Developer Experience

### Product Manager (PM) name and email

Steve Kovaks steve.kovaks@va.gov

### Product Owner (PO) name and email

Patrick Vinograd patrick.vinograd@va.gov

### COR Name (leave "None" if you listed an AWS user name above)

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

None

### Please confirm if you are on the VFS Team Roster or Platform Team Roster

- [x] [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Please confirm E-QIP Transmittal/Adjudication. This could be a screenshot of your Transmittal/Adjudication email, a link to another request where you've submitted this proof (i.e. AWS/SOCKS), etc.

- [X] I have attached proof that I have either transmitted my E-QIP survey or previously received a favorable decision (by including in "Additional Notes" section below)

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [ ] production (if requesting, justify prod access in 'Additional Notes' section)

### Additional Notes

Attached is a screenshot which shows my favorable decision for my eqip. 
![MicrosoftTeams-image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/669540/56878611-bc16-4f0b-9ba0-ae31f7a484c9)

I am part of the Developer Experience team working on creating a better test user management experience. As part of those needs, I need access to be able to get on to boxes inside the VA network to test our calls to services that may not yet be mocked, or be able to pull down WSDL/XSD files . I do not need prod access, only lower level environments. 

COR is Grace Spence

### Additional resources for Support Engineer

- [ ] For users on a VFS team but not in the VFS Team Roster, they must start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] Instructions for handling requests [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access) - Support Only

**Comment by bdech** [comment]
Found in VFS Roster

**Comment by bdech** [comment]
@charleystran You’ve been granted access to the `dev`, `staging`, and `sandbox` environments.

Here's some additional documentation for [Vets API on EKS](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-TerminalAccess) that may help.
