### ISSUE TITLE
Explore: Hybrid Approach

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#67314]
Only if neither of points 1 and 2 are fruitful, we implement a go-between, as discussed earlier this week. Instead of having a sentry->slack connection, we have a sentry->go-between->slack connection. The go-between will 1. "shape" our data the way we want it, without PII 2. should be able to route to different channels to control "noise" levels. Since this approach has many points to consider, this ticket should also be exploratory in nature. We need to define, as well as possible, all goals of this exploratory work.

**Comment by jennb33** [comment]
Closing tickets due to decision to not move forward.
