### ISSUE TITLE
Refactor past appointment list e2e test

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#67323]
Refactor past appointment list e2e test (`src/applications/vaos/tests/e2e/flows/appointment-list.cypress.spec.js`) to verify what is currently in production. Feature flags should be set to match production settings. All unused feature flag settings should be removed as well.

---

## Acceptance Criteria
- [ ] No test is skipped
- [ ] Feature flags should be set to match production settings. All unused feature flag settings should be removed as well.
- [ ] past appointment list e2e tests to match the past appointment list in production.

## Definition of Done
- [ ] All acceptance criteria are met

---

**Comment by vbahinwillit** [comment]
Closed as fixed in [67282](https://github.com/department-of-veterans-affairs/vets-website/pull/26222)
