### ISSUE TITLE
Refactor EnrolledRoute unit test

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#67334]
Refactor  EnrolledRoute unit test (`src/applications/vaos/tests/components/EnrolledRoute.unit.spec.jsx`). Our current test is incompatible with web components. Let's figure out a way to test the component without searching the contents of the shadow DOM. Perhaps only confirm existence of loader tag?

---

## Acceptance Criteria
- [ ] Component is tested without searching contents of shadow DOM.

## Definition of Done
- [ ] All acceptance criteria are met

---

**Comment by JunTaoLuo** [comment]
Ah yes I did fix this as part of https://github.com/department-of-veterans-affairs/vets-website/pull/29713.
