### ISSUE TITLE
Discovery: Research ActiveRecord tables using PostGIS extension features

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#67333]
## Description

We have four (updated 2/5/2024 from two) ActiveRecord tables with geography columns for geospatial data, supported by the PostGIS extension. When upgrading Postgres, PostGIS adds an extra step. We should investigate if these columns are still in use; there's a chance the relevant endpoints have shifted outside of Vets API. If we don't require PostGIS anymore, eliminating it can streamline future Postgres upgrades.

The tables are as follows:
1. base_facilities
2. drive_time_bands
3. Veteran_organizations
4. Veteran_representatives

**Comment by jennb33** [comment]
@gia-lexa and @LindseySaari will be reviewing the one that could be deleted; others seem to be in use on their 1:1 today
