### ISSUE TITLE
Update the uniqueID from the dismissed banners to be more specific

### ISSUE THREAD

**Issue by AkucherGCIO** [department-of-veterans-affairs/va.gov-team#6734]
## Problem Statement
We need to update the uniqueID from the dismissed banners to be more specific than just the title to prevent people from not seeing future banners with the same title.
![image (3).png](https://images.zenhubusercontent.com/5e4d73c84ff78270a88d2ae8/19c85e6d-6e16-4505-a55c-504aa3a1acd4)

## Acceptance Criteria
- [ ] _Prevent users to not see banners with the same title in the future.
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ncksllvn** [comment]
We could use a combination of the banner's title and content in order to create a unique identifier. That's probably the easiest way.

**Comment by AkucherGCIO** [comment]
03/12/20 PW Standup
@AkucherGCIO - Create a ticket for feature flag this functionality.

**Comment by MickinSahni** [comment]
2020-03-16 PW Standup
* Validated in staging. Closing this out as well as related feature flag ticket #6824
