### ISSUE TITLE
Content for Board Appeal confirmation page & email from Benefits Decision Reviews

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#67354]
## About your team

- Team name: Benefits Decision Reviews
-	OCTO-DE product owner: Amy Lai
-	Product manager: Sade Ragsdale
-	Designer: Eileen Chi
- Accessibility specialist: DK
- Content writer: 
-	Slack channel: #benefits-decision-reviews
 
### Describe what you need in a few sentences:

</br>
</br>

We are updating the Board Appeal confirmation page and confirmation email. This is linked to the [PDF confirmation work](https://github.com/department-of-veterans-affairs/va.gov-team/issues/61023) we requested in June.

### Which are you doing?
- [ ] **Launching a new** page, tool, form, or app
- [x] **Making changes** to an existing page, tool, form, or app

### Types of Support
What areas does your team need support in? Check all that apply.
#### Content
- [ ] Collaboration on content written by your team’s dedicated content writer 
- [x] Collaboration on content if your team does not have a dedicated content writer
#### Accessibility
- [ ] Accessibility review of wireframes and/or prototypes
- [ ] Accessibility issue (general request)
- [ ] Accessibility PDF review request
- [ ] Accessibility user research support ([submit a separate, additional request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name))
- [ ] DST component or pattern 
- [ ] Something else 
#### IA
- [ ] User Flows
- [ ] Page placement
- [ ] URLs
- [ ] Breadcrumbs and Left Nav placement
- [ ] Redirects
#### Multilingual content
- [ ] Translating content
 
## Timeframe
_We guide and work alongside teams across nearly every OCTO digital product. We also work with partners across VA to lead content migration and manage all unauthenticated content on VA.gov. And we're always working to expand the VA.gov content style guide and our IA and accessibility documentation. We need to prioritize all intake requests based on our overall workload and VA and OCTO priorities._

_Tell us about your product's timeline. And we'll work with you to meet timeline needs as best we can._

### Have you worked with CAIA before? 
  - [x] Yes
  - [ ] No

### What's your team’s next step and its timing?

- **Our next step is** Midpoint review
- **Provide date if available**: xx/xx/xxxx

#### Timing for your next step: 
  - [ ] Next week
  - [x] This month
  - [ ] Next month
  - [ ] This quarter
  - [ ] Next quarter
  - [ ] 6 months
  - [ ] 1 year

### Is this timing related to a specific event or Congressionally mandated deadline?
  - [ ] Yes
  - [x] No

### If you're conducting research, when is that starting? 
**Provide date if available:** xx/xx/xxxx
  - [ ] Next week
  - [ ] This month
  - [ ] Next month
  - [ ] This quarter
  - [ ] Next quarter
  - [ ] 6 months
  - [ ] 1 year

### Will you release this new product incrementally (for example, release to 25% of users to start)? 
  - [ ] Yes
  - [ ] No
 
**Note**: _If you checked yes, we’ll reach out to discuss details about the content in the react widget (we use these widgets to display entry points for new products to a certain percentage of users who visit our static pages)._

  
### When do you expect to launch your product to 100% of users?
  
*Please provide an estimated date so our team can create other relevant tickets.*
- **We expect to launch our product to 100% of users on:** xx/xx/xxxx
  
### Will this work be going through the Collaboration Cycle?
- [x] Yes 
- [ ] No

### If no ...
- Skip to the _supporting artifacts_ section, below.
 
#### Please provide the link to your Collaboration Cycle ticket: 
- **Ticket (66135)**: https://github.com/department-of-veterans-affairs/va.gov-team/issues/66135
- **Collab. Cycle Ticket Opened (date)**: 09/20/2023
 
#### Please check all of the phases in the Collaboration Cycle you have completed: 
- [x] Design Intent
- [ ] Midpoint Review
- [ ] Staging
 
##### Design Intent
- [ ] Accessibility
- [ ] Content
- [ ] IA
- [ ] Translation
- [x] Already completed, no assistance needed
- [ ] Unknown at this time
##### Midpoint
- [ ] Accessibility
- [x] Content
- [ ] IA
- [ ] Translation
- [ ] Already completed, no assistance needed
- [ ] Unknown at this time
##### Staging
- [ ] Accessibility
- [ ] Content
- [ ] IA
- [ ] Translation
- [ ] Already completed, no assistance needed
- [x] Unknown at this time
  
## Supporting artifacts
*Please provide links to supporting artifacts as available.*
- **Product outline**: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Notice-of-Disagreement/Appeal-PDF-Download-Initiative%20Brief.md
- **User flows**: [User flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1691599300063/42cd59780f131a0a61b149f7df8aa9c7f8ae83f6?wid=0-1696512700602&outline=open)
- **Prototype or mockups**: [Whiteboard sketch or other lo-fi prototypes or wireframes](https://www.figma.com/file/BplQkEDZzD8NPPNmLrhvXv/Request-a-Board-Appeal-%2F-Notice-of-Disagreement-(VA-10182)?type=design&node-id=831%3A76228&mode=design&t=igxNySzyPuhKCkuM-1)
- **Email mockups**: [Mock email prototype](https://www.figma.com/file/BplQkEDZzD8NPPNmLrhvXv/Request-a-Board-Appeal-%2F-Notice-of-Disagreement-(VA-10182)?type=design&node-id=840%3A81126&mode=design&t=igxNySzyPuhKCkuM-1)
- **Content source of truth**: [Github](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Notice-of-Disagreement/design/sourceofcontenttruth.md) [Google docs](https://docs.google.com/document/d/1cJhU6XtAepRIRMCA_PecLHZQr2vGhrELr4Sesm6fHAU/edit?usp=sharing)
- **Research plan:** [Research folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/decision-reviews/Notice-of-Disagreement/Research/012024-accessible-submission-download)
- **Any epics/issues that may be helpful**: [[epic] DR | Downloadable Copy of Submission](https://github.com/department-of-veterans-affairs/va.gov-team/issues/71358)
- **Link to testing accounts** (please do not paste them in this ticket): 

### Have you already worked with someone from OCTO leadership?
- [ ] Danielle
- [x] Beth
- [ ] Mikki
- [ ] Martha

### How do you plan to work with us on this request?
- [x] I’ll take this to Beth or Danielle’s office hours.
- [ ] I’d like to schedule time to talk about this.
- [x] Let’s work async and meet as needed.
- [ ] Schedule a kick-off call with your team and CAIA for your project **(Recommended)**

 
### Accessibility Help in Slack
The [#accessibility-help channel](https://dsva.slack.com/archives/C8E985R32) in the DSVA Slack, is also available to you as a resource. Everyone is welcome to ask questions or get help from our a11y (accessibility) specialists. Tag `@Terry Nichols` to get a11y help asap.

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag `@Terry Nichols`.**

- If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
- If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jennymayoco%2C+jilladams%2C+RLHecht&labels=sitewide+CAIA%2C+Sitewide+IA%2C+Public+Websites%2C+VA.gov+frontend%2C+Redirect+request&projects=&template=redirect-request.md&title=Redirect+Request)
 
 - If you are creating an [experimental design,](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) please [also contact the DST. ](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)

- If you are requesting [a11y support for user research,](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name) please complete this form, next. 

```[tasklist]
### Content tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/82347
```

**Comment by bethpottsVADEPO** [comment]
@eileen-coforma When is midpoint review? The team is figuring out how to work this in among other priorities. Thanks!
cc: @katherine-fung

**Comment by katherine-fung** [comment]
Hi @eileen-coforma, 

Here are the content recommendations for the email copy: https://dvagov-my.sharepoint.com/:w:/g/personal/katherine_fung_va_gov/EcDXTeP0RZhHmCnTPL4YBJcBXh2i-GG8NtIWe522K4L0gA?email=EILEEN.CHI%40va.gov&e=V164qg

Let me know if you have any trouble accessing the Word doc. 

We made these changes: 
1. Removed directional language ("below") 
2. Changed instances of passive voice to active ("This link will remain active..." to "You can use this link..." / changed "... it's listed in our claim status tool") or removed instances of passive voice 
3. Updated contact info to say contact us online via Ask VA 
4. Updated signature line for VA style  
5. Updated copy to specify that you can download your "completed Board Appeal request" to avoid people thinking they can download a Board Appeal decision. Also added the word "request" to "check the status of your Board Appeal request"

**Comment by katherine-fung** [comment]
Hi @eileen-coforma, 

Here are the content recommendations for the email copy: https://dvagov-my.sharepoint.com/:w:/g/personal/katherine_fung_va_gov/EcDXTeP0RZhHmCnTPL4YBJcBXh2i-GG8NtIWe522K4L0gA?email=EILEEN.CHI%40va.gov&e=V164qg

Let me know if you have any trouble accessing the Word doc. 

We made these changes: 
1. Removed directional language ("below") 
2. Changed instances of passive voice to active ("This link will remain active..." to "You can use this link..." / changed "... it's listed in our claim status tool") or removed instances of passive voice 
3. Updated contact info to say contact us online via Ask VA 
4. Updated signature line for VA style  
5. Updated copy to specify that you can download your "completed Board Appeal request" to avoid people thinking they can download a Board Appeal decision. Also added the word "request" to "check the status of your Board Appeal request"

**Comment by katherine-fung** [comment]
Hi @eileen-coforma! Is this ticket ready to be closed?

**Comment by eileen-coforma** [comment]
For Supplemental Claims, there were the following changes to the feature box content. Do we want to continue this language pattern for the rest of the Decision Review confirmation for consistency?

Your information for this claim
Your name
NAME

Date you filed your claim
Month XX, XXXX

Issue(s) you'd like us to review
Issue
Issue

**Comment by eileen-coforma** [comment]
@bethpottsVADEPO Yes, what I wrote in the comment is the current feature box content on the Supplemental Claims. We haven't updated NOD yet, but we will with upcoming changes.

**Comment by katherine-fung** [comment]
Hi @eileen-coforma, should we keep this ticket open?

**Comment by eileen-coforma** [comment]
Hi @katherine-fung There has been a pivot for this feature. We may need your eyes on this after the user research is complete. Research is currently ongoing.

**Comment by eileen-coforma** [comment]
Can I assign myself to this ticket so I can keep track of it? I keep losing this :(

**Comment by eileen-coforma** [comment]
@katherine-fung We are ready to pick up this work again. I've updated the ticket to include links of the new iteration, and how we've pivoted. I'll also leave a note in the CAIA channel.

**Comment by aprocik1** [comment]
Wonderful, thanks @eileen-coforma. I just requested access to your Google doc from ap@bloomworks.digital. Two more questions:
- Are you requesting changes to this confirmation screen and email based on [these research findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Notice-of-Disagreement/Research/012024-accessible-submission-download/research-findings.md#key-findings)? If so, I don't think we need to schedule a kickoff meeting. We can review your research and follow up with clarifying questions asnyc.
- What does "within the month" mean? By the end of this month, so next Tuesday 4/30? Or within a month from now, so around the end of May?

**Comment by eileen-coforma** [comment]
@aprocik1 
- I've granted access to the Google doc.
- Yes, the changes are based on those research findings.
- Sorry for the vagueness of timeline. Best by May 7 or latest by May 21.

**Comment by aprocik1** [comment]
Hi @eileen-coforma, I know you're discussing your confirmation screen with Matt Dingee and the Forms team. I'm assuming your content and design may change as a result of those conversations, so we'll wait to hear from you again before beginning our work on this ticket. Thanks!

**Comment by eileen-coforma** [comment]
Hi @aprocik1, we met with the Forms team, there isn't any change on our design that would impact content, so feel free to start the review.

**Comment by aprocik1** [comment]
@eileen-coforma, Katherine and I have reviewed your content source of truth. Here's the link with our recommendations incorporated: https://docs.google.com/document/d/1cJhU6XtAepRIRMCA_PecLHZQr2vGhrELr4Sesm6fHAU/edit?usp=sharing

Let me know if you have any questions.

**Comment by eileen-coforma** [comment]
@aprocik1 Thank you. We'll be passing this along for stakeholder approval.

I have one minor feedback.
Can we tweak the print this page language to be more general, instead of "for a summary", to ", which includes a summary"? We would like to clarify the difference between saving a PDF vs printing.

**Comment by aprocik1** [comment]
Yup, that works. I just accepted your suggested edit.
