### ISSUE TITLE
FE | Profile | Maintenance | Update validation for invalid area code to include "123"

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#67378]
## Background
If you try to save `1234567890` as a phone number in any part of profile (contact info or subtask page), the UI displays a generic save alert that says "We’re sorry. We can’t update your information right now. We’re working to fix this problem. Try again later."
![Screenshot 2023-10-11 at 11 01 34 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/55992116/bbbedb82-284c-4d89-8820-28520cc8bb6a)
 

We should update the alert to use the same, more specific language we use when an invalid area code is used (already in prod), since no US area code starts with 1:
`We can’t make this update because we currently only support U.S. area codes. Please provide a U.S.-based phone number.`

## Tasks

- [ ] Update validation for `1234567890` so it matches what we do when other invalid area codes are entered

## AC

- [ ] Validation is consistent for all invalid area code entries

**Comment by mtcA6** [comment]
duplicate, we've fixed this already in sprint 21
