### ISSUE TITLE
Access for Saman Moshafi

### ISSUE THREAD

**Issue by saman-moshafi-va** [department-of-veterans-affairs/va.gov-team#6737]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Bryan Broome
- Please provide your name.
   > Saman Moshafi
- Please provide the name of your team, your role on that team, and the name of the company you work for.
  > Team: @thoughtworks 
  > Role: Developer
  > Company: ThoughtWorks
  > I am part of a team at ThoughtWorks that is working with the CTO's office to update va.gov/scorecard. I have a PIV card that I was granted in January 2020. I am requesting access to the SOCKS proxy and Jenkins / Prometheus / Grafana so we can 
  > - Modify / update Jenkins job configs
  > - Kick off Jenkins jobs
  > - Review Prometheus data, some of which is imported into the scorecard
  > - Review Grafana data for the scorecard
  
  > If you have any questions or concerns please let me know, or reach out on slack on #va-scorecard-refresh
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Internal%20Tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCnskS6Cg39gzH3JKVcLQvHAyOnv3Ysw4EDlvpJ6e/ldH1FOKH9mIMhQnzDGTFKUlA7DKpw+NxznPguzxmwlpgnJByiae1igDWV4foTGSirW2IqqM4y/VheZQXmtzKtdzbgB3O6VPVMMxrjtWOVsc9p4LMfVdqjWQiOjlmYv71vnm0dP4OcdXAXVK7zTgHkOsCyY6W+J1QvkCLMJdlukhlPqx1eUDYUBygPaLzwUxDj5yObVACQrymt7LtmPxXbujy+Dfp3XVG0pBuBtHwLHWwoTzcGHUQTV9CqvzMXD/JLUcTmRBwn7xErayHkn8rS9kywvQ/ssOrqvoIsfxTFavBp saman.moshafi@thoughtworks.com
```

- [Grant AWS Console access?]
  > YES

**Comment by saman-moshafi-va** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by jbritt1** [comment]
SOCKS access granted. @saman-moshafi-va, please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.

**Comment by karlbrown-va** [comment]
hi @jbritt1 Can you replace the existing key for Saman with the one noted above? Saman has lost his other private key.

**Comment by jbritt1** [comment]
New key configured on sock proxy machine(s). Closing this one up.

**Comment by saman-moshafi-va** [comment]
Re-opening as we need access to the AWS console; changed [Grant AWS Console access?] from No to YES

**Comment by ffafara-tw** [comment]
AWS Access:
User: Saman Moshafi
COR: Courtney Bethea
Approver: @Jeff-Hayter

**Comment by jbritt1** [comment]
> **AWS Access:**
> User: Saman Moshafi
> COR: Courtney Bethea
> Approver: @Jeff-Hayter

Thanks @ffafara-tw for catching this, not sure how I missed it.

**Comment by Jeff-Hayter** [comment]
@jbritt1 Approved for AWS access.

**Comment by jbritt1** [comment]
Will reach out to Saman directly with first time login credentials momentarily.

**Comment by jbritt1** [comment]
First time login credentials have been provided to this user privately.
