### ISSUE TITLE
Profile | FE | Editing as a subtask | Validation fix for phone fields

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/va.gov-team#67384]
## Issue Description
We added a character rule for validation, but are still having issues with length of phone number in validating phone numbers prior to field submission.

## Front end tasks
- Make sure characters and minimum length of 10 is met for phone field
- Add unit tests

## Acceptance Criteria
- [x] Validation passes
- [x] Unit tests pass

**Comment by adamwhitlock1** [comment]
@mtcA6 this is ready for validation, there was a minor bug that came up from allowing dashes and parentheses in the phone field, and this just fixes that bug.

To verify we just need to check that a user cannot attempt to update their phone number with any less than 10 numbers and that they see the appropriate for validation error and the form does not submit to the api.

https://user-images.githubusercontent.com/8332986/274401531-040c2fa9-c4fc-49de-8460-5aa2707aad6b.png

**Comment by mtcA6** [comment]
If a user doesn't use dashes then it provides the correct validation error. 

But if they do use dashes it gives a more generic error:
[Uploading... image.png]

**Comment by adamwhitlock1** [comment]
ugh yea that edge case is not fun, it passes the general character length rule, but doesn't check to see that 10 numerical digits are explicitly present. I have another fix I will have to put in for that.

**Comment by mtcA6** [comment]
Wanna create a new ticket for that and close this one out?

**Comment by adamwhitlock1** [comment]
I pushed a fix out for that and I think I checked various combinations of the edge case on staging. Thanks for finding that edge case. If you want to take a look and let me know then we could probably close this out.
