### ISSUE TITLE
[Design] -  "Personal Contact Info" : Modal to Edit-in-Place: Desktop

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#6739]
## Tasks
- [x] Update design to be Edit-in-place vs Modal.

## Acceptance Criteria
- [x] All fields have been updated

**Comment by tressaellen** [comment]
![pc 1](https://user-images.githubusercontent.com/58752772/77563185-c8f5c380-6e75-11ea-8833-2cb1e9c088c4.png)
![pc 4](https://user-images.githubusercontent.com/58752772/77563196-cd21e100-6e75-11ea-838f-5abb45a0a4f7.png)
![pc 14](https://user-images.githubusercontent.com/58752772/77563200-cf843b00-6e75-11ea-9c19-3c56bd8cd660.png)
