### ISSUE TITLE
[Design] - "Direct Deposit" : Modal to Edit-in-Place: Desktop

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#6740]
## Tasks
- [x] Update design to be Edit-in-place vs Modal.

## Acceptance Criteria
- [x] All fields have been updated

**Comment by tressaellen** [comment]
All states have been created. Here's a sampling.

![DD 1](https://user-images.githubusercontent.com/58752772/77563371-0c503200-6e76-11ea-8bdd-d74a166bb576.jpg)
![DD 2](https://user-images.githubusercontent.com/58752772/77563383-0f4b2280-6e76-11ea-86ae-c33fae692203.jpg)
