### ISSUE TITLE
[Design] - "Personal Contact Info" : Modal to Edit-in-Place: Mobile

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#6741]
## Tasks
- [ ] Update design to be Edit-in-place vs Modal.

## Acceptance Criteria
- [ ] All fields have been updated

**Comment by tressaellen** [comment]
I felt like having the buttons in the cards made everything a bit too heavy, so I went with the links. 

![Edit in Place 1](https://user-images.githubusercontent.com/58752772/76439371-27e51400-6371-11ea-8592-75d12d5be4a9.jpg)
<img width="190" alt="Edit in Place 2" src="https://user-images.githubusercontent.com/58752772/76439392-32071280-6371-11ea-939c-b032f259316c.png">
<img width="192" alt="Edit In Place 3" src="https://user-images.githubusercontent.com/58752772/76439395-33383f80-6371-11ea-8342-8c4e8e934730.png">

**Comment by Samara-Strauss** [comment]
This looks good to me! I really like this direction!!

**Comment by mshea0606** [comment]
@tressaellen Looks great to me. I think it looks really clean.

**Comment by sshein** [comment]
cool. I'm thinking maybe we should just do away with the "close" links. I like them because like I said users can open and close quickly, but I think they may cause too much confusion. e.g. what if a user changes their data then clicks "close"? would it save?  And it doesn't align with previous patterns anyway.

**Comment by tressaellen** [comment]
@sshein This makes sense - I'll nix the close links.

**Comment by Samara-Strauss** [comment]
+1 to @sshein's comment!

**Comment by tressaellen** [comment]
All states have been created, here's a sampling.

![mobile pc 13](https://user-images.githubusercontent.com/58752772/77563652-651fca80-6e76-11ea-8a38-a59826f68dd4.jpg)
![mobile pc 2](https://user-images.githubusercontent.com/58752772/77563637-60f3ad00-6e76-11ea-96e9-93defcc71af6.jpg)
![mobile pc 5 copy](https://user-images.githubusercontent.com/58752772/77563648-63560700-6e76-11ea-9bd3-2a2e77b43961.png)
