### ISSUE TITLE
SOCKS access for [Liz Townsend]

### ISSUE THREAD

**Issue by liztownd** [department-of-veterans-affairs/va.gov-team#67413]
### Your Name

Liz Townsend

### Your Email

liz.townsend@adhocteam.us

### Your Role and Team

Staff Software Engineer on Veteran Status Team

### Product Manager (PM) name and email

Matt Reilly - matt.reilly@adhocteam.us

### Product Owner (PO) name and email

Ryan Thurlwell - ryan.thurlwell@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDTFOoWPLaPrTfNsuXFjCLF8Gb1QcQC1PO/SXlrKAcWLpI6q5dHee6MvLabQ52u1NqcEOLFuBEZ5OkDQ+Zu7poVtZc5SL9N7RVCTfag9j4ACGTs0MBwV2r+K8ig8QZkBzLrhYacW8Of9h+dOETjieH3BfMoitJA3yncVz9P9Zlt3xCQS3bIxX+739xPDvOtaqV/YJgjYVV9KGMNR6Yrc7GwvfLkPgOpUyB6ahCILPUxapxn8NCuoGNq4kUcig3TWTRsiBcSaZOJJwAf0rtROU6zn44XmfZcjyYqzvEvJ/Jsl1+dUi1XwaSJz49hfkGlwdwfe8M+C0h8s9N0YzEqz/PMcV/pHuwC30a2aA5qlXI0+sL8A/19EgOtKM8UN0SiVDi/AXkcKQ99fKjPQBYfPjLFIRc2X1eXedJkVVmNTH+PDKvn/MF9Zh5H/DBXH6dJoWOck9Sjh2+080Iffx2a2Di6qez0hllBz2/A0bEH39YCgrx/rkWpC61ZOSiRPvhbKFE= liz.townsend@liztownsend-WC5X605W7M

### E-QIP Transmittal Confirmation

<img width="1073" alt="Screenshot 2023-10-17 at 3 17 15 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/72234279/bc4e7808-65e0-49b8-bac7-bd7b73241cf5">

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by flooose** [comment]
@liztownd do you have an email from the VA with the words "Transmittal Notice" in the subject. The screenshot you provided only shows us that you've _submitted_ your form. The actual "Transmittal Notice" comes after the VA has done an initial check of this form for completeness and transmitted it on your behalf.

**Comment by liztownd** [comment]
@flooose @barbarello Oddly enough, it _just_ came through. Attaching here, as I can't seem to update the original ticket with it.
<img width="1073" alt="Screenshot 2023-10-17 at 3 17 15 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/72234279/bc4e7808-65e0-49b8-bac7-bd7b73241cf5">

**Comment by ph-One** [comment]
pubkey added to SOCKS hosts. Closing.
