### ISSUE TITLE
[FE] Spanish Translation Bugs

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#67423]
## Background
The following feedback was received from the translators at the State Department. Refer to the QA [PDF ](https://github.com/department-of-veterans-affairs/va.gov-team/files/12883460/LS-2022-0118394-LQA-ST_Spanish_Q4_2023_2023-09-20_19-39-01.pdf) from the State Department if there are any questions.

## Bugs
- "at" needs to be changed to "en" when we are displaying the appointment next to the appointment type icon for in person appointments (see image below)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjh0QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--34d6841603e57f0ba15d61993dbf12658ab5950f/image.png)

- "en" needs to be changed to "a las" when displaying the date & time in the "when" section of the details page (see image below)

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/86678742/e7fbb534-94f1-49c8-aee9-b3f4e74aa7b5)

- Change "o su tiene" to "o si tiene" in the Need Help section

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/86678742/bf298896-057d-429c-af60-4bd42e7468a2)

**Comment by lee-delarm6** [comment]
The needs help section has been replaced with all new text and needs updates for the Spanish translations

**Comment by loripusey** [comment]
We will do translations quarterly, the updates to Needs Help will be picked up Q1 of 2024

**Comment by loripusey** [comment]
validated, closing
