### ISSUE TITLE
Add content for the Feature Toggle component and hook.

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/va.gov-team#67429]
### Description
I would like to add some documentation around a component and hook that was added to the platform code several months ago.

Here is a [link to the original post](https://dsva.slack.com/archives/C5HP4GN3F/p1680712065373399) where the basics of the usage of the component and hook are outlined, but I will copy the content here as well.

Accessing a feature toggle value through the `Toggler` component

1. Import the Toggler and then use the compound components to display and hide any child components based on the feature toggle value. The Toggler component includes the TOGGLE NAMES and Enabled/Disabled components, so just a single import is all that is needed:

``` js
import { Toggler } from 'platform/utilities/feature-toggles';

<Toggler toggleName={Toggler.TOGGLE_NAMES.someToggle}>
    <Toggler.Enabled>
        <p>Enabled</p>
    </Toggler.Enabled>

    <Toggler.Disabled>
        <p>Disabled</p>
    </Toggler.Disabled>
</Toggler>
```

2. Alternatively, you can use a High Order Component (HOC) to access the toggle value within the render props. This can be useful for use inside a Class Based Component, or if you need to do something other than just conditionally rendering based on the value.

``` js
<Toggler.Hoc toggleName={Toggler.TOGGLE_NAMES.someToggle}>
        {toggleValue => <p>{toggleValue ? 'Yay it is enabled' : 'Boo it is disabled'}</p>}
</Toggler.Hoc>
```

3. Using the useFeatureToggle hook. This hook returns a secondary hook useToggleValue along with the main list of toggles TOGGLE_NAMES. The useToggleLoadingValue hook can be useful to verify that the toggles have loaded before doing a certain action like requesting data from an api and thus preventing a race condition around the toggle state.

```js
import {useFeatureToggle} from 'platform/utilities/feature-toggles';

// inside a functional component we can now use the hook to access values as needed.
const { useToggleValue, useToggleLoadingValue TOGGLE_NAMES } = useFeatureToggle();

// boolean value to represent if toggles are still loading or not
const togglesLoading = useToggleLoadingValue()

// value of specific toggle
const toggleValue = useToggleValue(TOGGLE_NAMES.someToggle);

...
```

### Relevant URLs
https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide

This new content would go inside the section for the FE docs of the feature toggles, item 7/8 or make a new item in the list not sure what would be best.

### Which type of team are you on? (Platform team, VFS team, or Leadership)
I am on a VFS team Authenticated Experience / Profile, but had the code accepted from the platform team and in use for about 6 months now.

**Comment by vbellissimo** [comment]
Hi @adamwhitlock1 , thanks for flagging and providing this information! We will take a look for next steps to get this added to the site. Do you recall who specifically you talked to on the Platform about this code? I looked at the Slack thread you linked to but did not recognize anyone from there as part of Platform so wanted to double check. Thanks.

**Comment by laucon** [comment]
@adamwhitlock1 I want to add this, but I'm really confused where in the [document](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide) you want it to go.
This looks like it should be its own section and not inside any other section.

You suggested putting it, "inside section for the FE." What is FE. Is that frontend? It looks like we have 2 paragraphs that say "frontend": "Adding a new feature toggle (frontend)" and "Creating a toggle and turning it on or off (Frontend)" Maybe we could add the section you wrote after "Creating a toggle and turning it on or off (Frontend)"? Just an idea.

You also suggested item 7/8. I don't know if we should put an entire sub-process underneath step 7 within a larger process. That seems over-complicated. You also didn't specify if it should be 7 or 8.

I think this should be its own section somewhere on the page. But what do you think?

**Comment by adamwhitlock1** [comment]
@vbellissimo Here is [the original PR](https://github.com/department-of-veterans-affairs/vets-website/pull/23819) where the code was approved by Ray Messina.

@laucon Sorry for the confusion, yes FE means frontend, and I would be okay with however yall wanted to add it, but my thoughts on why it could go into [section 8 of the frontend steps](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretogglesguide-8.Usethefeaturetogglevaluetogateyournewbehavior) is that it is basically a potential replacement for steps 7 or 8 and could be used in place of a redux selector to gate frontend behavior in a simplified manner.

It could also just go in a new section after that step 8 as an alternative approach or something of that nature. Let me know if that clears things up and I'd also be happy to jump on a call to discuss any ideas further. Thank you!

**Comment by laucon** [comment]
@adamwhitlock1 Thank you! Now I understand. I can replace the current steps 7 and 8 with this.

**Comment by laucon** [comment]
FYI, I am still working on this, but it's taking a while. Thanks

**Comment by laucon** [comment]
@adamwhitlock1 My team wanted to have someone else check it for accuracy. Rebecca Tolmach was busy, so I had Ryan McNeil check it, even though he admittedly works more on backend than on front end stuff. However, I edited the document and it should be deployed at 3:30pm today. If there are any other changes that need to be made, just let my team know. :)

**Comment by laucon** [comment]
Now that it's been updated [here](https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide), I am going to close this. If you have more issues, feel free to send them to my team. :)
