### ISSUE TITLE
[Design] - "Direct Deposit" : Modal to Edit-in-Place: Mobile

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#6742]
## Tasks
- [x] Update design to be Edit-in-place vs Modal.

## Acceptance Criteria
- [x] All fields have been updated

**Comment by tressaellen** [comment]
![Mobile DD 2](https://user-images.githubusercontent.com/58752772/77563797-97c9c300-6e76-11ea-947b-d6cac6309251.jpg)
![Mobile DD 3](https://user-images.githubusercontent.com/58752772/77563807-9ac4b380-6e76-11ea-92b5-2a2f5c9a8f41.jpg)
