### ISSUE TITLE
Unit Test for Workflow: "Add a Student 18 to 23 Years Old (674) Part 2

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#6745]
## Goal
Write and complete a unit test for the workflow mentioned above.

## Considerations
- Implement items from previous unit test tickets.
- Use some existing unit test as a model.

## Acceptance Criteria
- [x] 80% coverage for the workflow has been achieved.

**Comment by micahchiang** [comment]
PR - https://github.com/department-of-veterans-affairs/vets-website/pull/11965

**Comment by micahchiang** [comment]
PR merged.
