### ISSUE TITLE
[Other] Content overflowing its container is hidden (Keyboard Controls)

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#67453]
#### VFS team name
Virtual Agent

#### VFS product name
Chatbot

#### VFS feature name
Prescription

#### Point of Contact/Reviewers
Ryan Smith - @rsmithadhoc - Accessibility

*For more information on how to interpret this ticket, please refer to the [Anatomy of a Staging Review issue ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Anatomy-of-a-Staging-Review-Issue-ticket.2060320997.html) guidance on Platform Website.

---

### Platform Issue
No VA.gov Experience Standard for the issue found.

### Issue Details
When tabbing to the "keyboard controls" section, it is cut off at the bottom.

### Link, screenshot or steps to recreate

<img width="729" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/100248909/1eeb68d3-48ae-4ede-b79c-92f9f28c492f">

### VA.gov Experience Standard
[Category Number 00, Issue Number 00](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

### Platform Recommendation
Make this content fit within the chatbot area or find another way to display this.

---

### VFS Guidance

- Close the ticket when the issue has been resolved or validated by your Product Owner
- If your team has additional questions or needs Platform help validating the issue, please comment on the ticket
- Some feedback provided may be out of scope for your iteration of the product, however, Platform's OCTO leadership has stated that all identified issues need to be documented and it is still your responsibility to resolve the issue.
- If you do not believe that this Staging Review issue ticket is the responsibility of your team, comment below providing an explanation and who you believe is responsible. Please tag the Point of Contact/Reviewers. Governance team will research and will follow up.

**Comment by Joy-Elizabeth** [comment]
Fixed when webchat version was updated.
