### ISSUE TITLE
Define recruitment criteria for IPP Pilot Usability Testing, Veterans

### ISSUE THREAD

**Issue by skirkman16** [department-of-veterans-affairs/va.gov-team#67460]
As UX Researchers and Designers, we need to define who we want to include from Veteran segments in our IPP usability tests and how we will recruit them through Perigean so that participants are representative of the intended end user population.

Tasks

- [x] Build recruitment criteria for IPP usability test for Veterans

Acceptance Criteria

- [x] Input recruitment criteria into research plan

**Comment by SophiaPhilipMO** [comment]
@lmorris3  @porta-antiporta please review criteria for Veterans in the usability test
