### ISSUE TITLE
VFS Roster Ownership Transition

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#67466]

**Comment by shiragoodman** [comment]
@alyssagallion There is some guidance on Confluence that explains the current process for handling [New VFS Team ](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2061959315/New+VFS+Teams)tickets and[ New VFS Team Member](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2041086016/New+VFS+team+members) tickets as part of [Platform Orientation. ](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1844838440/Platform+Orientation)

**Comment by alyssagallion** [comment]
Final stages, ensuring notifications are working.

**Comment by alyssagallion** [comment]
All work completed. Closing.
