### ISSUE TITLE
Storyboard Next Draft

### ISSUE THREAD

**Issue by MOStudioCarolyn** [department-of-veterans-affairs/va.gov-team#67472]
Design next iteration of hi fidelity storyboards

**Comment by skirkman16** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzlGQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a6496fe34c66765113c3a9b815a3c95a53774dad/Untitled_Artwork%204.png)
Example of next fidelity

**Comment by skirkman16** [comment]
@MOStudioCarolyn will aim to get storyboards by EOD tomorrow and @skirkman16 will get her half done by EOD Thursday. After sharing out, both designers will ask for how they would like to receive feedback. Storyboards can be used for the following applications: introducing concepts in meetings and presentations, accompanying written content (i.e. guides for help desk), justify help or support resources, support vision or items on the roadmap

**Comment by skirkman16** [comment]
@MOStudioCarolyn will aim to get storyboards by EOD tomorrow and @skirkman16 will get her half done by EOD Thursday. After sharing out, both designers will ask for how they would like to receive feedback. Storyboards can be used for the following applications: introducing concepts in meetings and presentations, accompanying written content (i.e. guides for help desk), justify help or support resources, support vision or items on the roadmap

**Comment by skirkman16** [comment]
Suggested tracing as an option for aligning on a style and speeding up the storyboarding process. Images were sourced from VA's Flicker which can be accessed through OIT Branding System. I will meet with Platform on 11/7 at their next design office hours to find out guidance on tracing and sketching. Discussions have also been initiated in the VA design slack channel. Sketches are updated in the [strategy roadmap mural ](https://app.mural.co/t/innovationboards1199/m/innovationboards1199/1695041576761/a482dba6ff5d97bc0af7bbcd8893ba41dcea3f03?sender=u99cd1ac4f5c240d8dffd4204)
