### ISSUE TITLE
Determine onsite research goals and parameters

### ISSUE THREAD

**Issue by skirkman16** [department-of-veterans-affairs/va.gov-team#67473]
For our pilot implementation, we need to determine how and where we will conduct our onsite research and what we will measure. Currently we have a general outline, but we should specify the plan for engaging with all participants and determine a start and endpoint of data collection.

Tasks

- [x] Meet and determine the start and endpoint of data collection
- [x] Define metrics of onsite 
- [x] Review PRA and determine method for pre and post questions

Later inclusions:

- Include recruitment criteria from GH ticket #67460
- Include sites from ZH ticket #60
- Risk assessment

Acceptance criteria

- [x] All teammates have reviewed onsite and details are ready to put into a research plan

**Comment by SophiaPhilipMO** [comment]
Veterans receive an email with their Case # when they elect ‘verify identity in person’ in the application
Receive Verify 9 Veterans for in-person proofing at the pilot site successfully within a 1 week period 
Veterans bring the correct materials for identity verification
Veterans have their Case # and/or their Case # can be retrieved by the Proofing Agent
Proofing Agents are able to complete all steps of the identity verification process
Veteran feedback is collected before and after their identity verification sessions with the Proofing Agents
Proofing Agent feedback is collected prior to the start of the pilot and at the pilot’s completion
Pain points in Veteran experience and flow are identified
Pain points in Proofing Agent experience and flow are identified
Attitudes and receptivity to in-person identity verification are collected for Veterans
Attitudes and receptivity to in-person identity verification are collected for VA Staff
[Pilot proposal](https://docs.google.com/document/d/1p_fGqtrLOz3UyINsNP0riSEGEWNbC9_FgJJ8A0G0kYg/edit)

**Comment by SophiaPhilipMO** [comment]
Start point of data collection for each session is when Veteran reconfirms consent and begins intake process.
End point of data collection is when Veteran ends session, including completing survey, anti fraud letter feedback, and received educational material.

**Comment by SophiaPhilipMO** [comment]
Start point of data collection for each VA staff's session is when VA staff takes pre-survey
End point of data collection for each VA staff session is when VA staff takes post survey
On no survey session, start point is when VA staff is connected to Veteran for proofing agent stage of application and ends, when VA staff directs Veteran to research team upon completion of Verification task

**Comment by SophiaPhilipMO** [comment]
@lmorris3 double check but I believe this ticket has been addressed, see comment history
