### ISSUE TITLE
Draft Login.gov IPP integration proposal

### ISSUE THREAD

**Issue by porta-antiporta** [department-of-veterans-affairs/va.gov-team#67482]
There will be a significant integration between the IPP application and Login.gov. We need to outline a plan to understand how this integration will work. Below is a link to a Data Flow diagram outlining interactions between IPP and Login.gov:

https://app.mural.co/t/innovationboards1199/m/innovationboards1199/1696563943931/654bbd3139e9de1dd4ca0c679a77c9d7286565ac?sender=ubaed9022e894858e004b6707

Acceptance Criteria:
- Document outlining the various Login.gov Integration options

Definition of Done:
- [x] Document that outlines all options that can be shared with Tom

**Comment by rdvyas** [comment]
Please see my first draft for this document below. I have tagged the various resources that were in the MO internal integration meeting:

[Login.gov Integration DRAFT](https://docs.google.com/document/d/1s4IEOMivJBQS5L78iddIQsozHwR-74VQNUF13ZWUB0E/edit#heading=h.q339wykocbzo)

**Comment by rdvyas** [comment]
Moving ticket to Review state.

**Comment by porta-antiporta** [comment]
Added my review comments. We should meet to discuss them. Proposing using our existing identity AMA meeting.

**Comment by porta-antiporta** [comment]
Added my review comments. We should meet to discuss them. Proposing using our existing identity AMA meeting.

**Comment by porta-antiporta** [comment]
Had quick sync with Hooper for feedback. Working with @rdvyas to update it prior to Login.gov IPP bi-weekly.

**Comment by porta-antiporta** [comment]
Updated doc reflecting discussion from IPP bi-weekly

**Comment by lmorris3** [comment]
Complete, closing.
