### ISSUE TITLE
[Design] Connected Accounts UI copy

### ISSUE THREAD

**Issue by careyotto** [department-of-veterans-affairs/va.gov-team#6748]
## Background
We need a content review for connected accounts screens on va.gov. See #6731 for details.

With connected accounts, Veterans can authorize a third-party app or site to access their sensitive data (like health records, veteran confirmation, etc.) in order to use the app or service. A Veteran authorizes access through the app flow, but must come here to VA.gov at a later date in order to revoke that access. None of the apps/sites can change a Veteran's data, but some may copy it over to their own servers or the Veteran's device. (Various use cases.) Disconnecting an account, doesn't mean a Veteran's account with the third-party app or site will be deleted. We want to message this as well, without scaring anyone too much.

With the UI copy, we're looking to balance making sure Veterans know what they have consented to, actively helping them manage their privacy by removing apps they no longer use, and also indicating there is value in using some of these apps/services. The idea of an FAQ page is an old one that we want to resurface to address some of this (linked to in the UI copy), where we want to also include a list of all apps/sites that are available to connect to and more info on how they use data, etc. FAQ type page will be under a separate ticket.

**Comment by careyotto** [comment]
@peggygannon Here is copy feedback from one of our product owners. Take it as suggestions, not mandates.

> 1. Instead of saying "You gave these third-party sites and apps access to some of your Veteran Profile data..." maybe would be better to just say "You gave these third parties access to some of your Veteran Profile data..."
> 
> 2. Not sure Veteran Profile data is the correct terminology to use, either. A user might interpret this to just mean general contact/account info, rather than something like their health data. Maybe should say something like "your personal VA data".
> 
> 3. The link to the right of each connected account says "view and edit". When expanded, it changes to "hide details". For consistency, rather than "view and edit" the link could say "show details". At the very least, should be "view/edit" rather than "view and edit", which just doesn't sound right. Also, the term edit is a bit misleading anyways, since the only "edit" that can be made is to disconnect the account.
> 
> 4. The pop-up dialogue to confirm disconnecting an account says "<app name> will no longer be able to access your Veteran data". This could also be cleaned up a bit, to state that the app will no longer be able to update your Veteran data. In some cases, like with Apple health, any data that's already been retrieved could remain (depending on how the app handles it), so users might want to be made aware of this distinction. I realize this distinction is made after the fact, so really just tweaking that verb on the confirmation screen might help.

Re: "View and edit" link - this is a change I proposed because I fear users may not understand they can disconnect/remove access by clicking something as passive sounding as "details" (which is what currently exists in production).

**Comment by careyotto** [comment]
@peggygannon @tressaellen Looking at Tressa's designs for other areas of Profile 2.0, I wonder if changing Connected Accounts links to "Edit" and "Close" would be best (rather than "Details" or "View and edit") - Curious your thoughts as I am less familiar with the bigger picture you're working with. Just want to make sure users understand how to remove access to their data. 
![image](https://user-images.githubusercontent.com/37549106/76443709-1a835600-6380-11ea-8c21-2ac20735e9aa.png)

**Comment by Samara-Strauss** [comment]
@careyotto I would recommend reaching out to Peggy and setting up a time to meet with her to discuss specific copy needs. This will make it easier for her to know what to work on.

Also, please provide screenshots in this ticket of each screen that needs copy, being sure to differentiate the copy that needs work from the copy that doesn't (so she's not writing copy for/renaming something that doesn't need it).  This will be helpful so we can confirm that everything that needs to be updated gets updated, and so it's easy for you/me/Tressa to review.

**Comment by careyotto** [comment]
@Samara-Strauss I reached out to Peggy the other day and she said she'd get in touch if she had any questions, after reviewing the ticket.

@tressaellen Please add screens here, once you are done iterating with the rough copy.

**Comment by peggygannon** [comment]
@careyotto 
Hello! I'm taking a look at this issue and have a few questions: 

How will the connected accounts content appear? as an alert? or will this messaging be part of a drop-down link from a user's profile page?

Let me know if there is any early design/mockups that are in progress,  so I have a better sense of how users will come upon this info. I see some screenshots in #6731, but I'm not sure which ones are the most recent design.

**Comment by tressaellen** [comment]
Hi @peggygannon I am working on these screens right now and will drop them in shortly

**Comment by careyotto** [comment]
@peggygannon

Outside of VA.gov, a Veteran can log into a third-party app and give consent to connect some of their VA data with it. Veteran goes through a bunch of steps to do that. This screen is an example of the final "authorize" screen a user will see before connecting to an app.
![image](https://user-images.githubusercontent.com/37549106/76569581-b096a980-6470-11ea-8514-0bc2ca005804.png)

Once they consented to access, VA.gov is the only place a Veteran has to remove an app’s access to their sensitive information, that they’ve previously connected to. Unless they ask the app developer to delete their account with them outright. Removing access just means the app can no longer see new data. It does not guarantee that the app doesn't keep records of previous data and interactions user has given them.

I believe Tressa is designing this Connected Accounts area to live with other account info, which makes sense to me.

**Comment by tressaellen** [comment]
@peggygannon  and @careyotto - sorry for the delay - I'm still working on the mocks, but I'll have them in by tomorrow and will ping you when they're done.

**Comment by tressaellen** [comment]
Hi @peggygannon and @careyotto here are the screens to review for Connected Accounts.  Everything that needs to be looked at in red and I've added some clarifying notes here. 

1. We ended up changing 'Account' back to 'Account Security', is that okay? 'Connected Accounts' needs to be re-visited.  It exists in other areas of VA but we'd like it to be as clear as possible for users.
5-6. These to screens are trying to achieve the same thing but we can't seem to get messaging right.  We like the design of screen 6 better than screen 5, but I'm not sure we can fit what we need to in the banner approach.  I'd love your input Peggy.

Please feel free to shoot me or Carey any additional questions or if you'd like to meet and go over things, I'd be happy to do that as well.  Thank you!

![Connected Accounts 1](https://user-images.githubusercontent.com/58752772/76659573-a7b6de00-652b-11ea-9454-dff14eae2319.jpg)
![Connected Accounts 2](https://user-images.githubusercontent.com/58752772/76659585-aeddec00-652b-11ea-9e3d-6d13869706e2.jpg)
![Connected Accounts 3](https://user-images.githubusercontent.com/58752772/76659590-b1404600-652b-11ea-89ff-b667b01e49fa.jpg)
![Connected Accounts 4](https://user-images.githubusercontent.com/58752772/76659594-b43b3680-652b-11ea-8824-893f54685f89.jpg)
![Connected Accounts 5](https://user-images.githubusercontent.com/58752772/76659596-b56c6380-652b-11ea-98c2-a9cf9e870118.jpg)
![Connected Accounts 6](https://user-images.githubusercontent.com/58752772/76659599-b7362700-652b-11ea-9433-6a6d16b31dd1.jpg)

**Comment by careyotto** [comment]
@peggygannon @tressaellen More context, as you chew on this. 

I just learned today that there is a thing called [VA Mobile](https://mobile.va.gov/), which has its very own app store. 

I will verify this with my PO on Monday. Current understanding is that since these are apps are developed by the VA, a Veteran need only log in with ID.me, DS Logon, My HealtheVet logins and the app automatically has access to their data. SO THEY WILL NOT SHOW UP IN CONNECTED ACCOUNTS.

However, my suspicion is from a user perspective, an app is an app and users may not make a distinction between a VA app and a third-party app unless we make it clear to them.

With this in mind, we may want to consider:

- emphasizing the third-party aspect of this area of their account

-  potentially, also referencing the VA mobile app store as a resource so the VA has one "apps you can use" voice. 

Would love your thoughts on this recent curve ball!

**Comment by peggygannon** [comment]
@tressaellen @careyotto sorry for the delay! Here is recommended content for the screenshots above. Let's discuss at our meeting on Monday to make sure the content I recommend works with the layout and user flow. 


First screenshot
**Connected accounts**
You don’t have any third-party applications or sites connected to your Veteran profile. If you set up a connected account it will show here on your profile. 

Have questions about connecting an account to VA.gov? 
[Get answers to Frequently Asked Questions](link URL tk)
[See the list of third-party applications](link URL tk)

 ------
 
Second screenshot
**Connected accounts**
You gave the below third-party applications and sites access to some of your Veteran profile. Your profile has your personal information so we recommend you disconnect any apps or sites you no longer use or trust. 

------

Third screenshot

**[Sample app] has access to your:**

------

Fourth screenshot/Disconnect message:

**Are you sure you want to disconnect this account?**

[Name of app] will no longer have access to your Veteran information and profile. To re-connect this app, go to [Sample app] and follow the steps to re-connect. 
Buttons
{Disconnect}

{Cancel}

------

Fifth screenshot

**You disconnected this account**
[[Sample app] has been disconnected and will no longer have access to your Veteran profile. 
This app might still have access to some information you gave them earlier. To delete this app, go to [Sample app] and delete. 

-----

Sixth screenshot
{Alert}
[Sample app] has been disconnected. This site will no longer have access to your Veteran information.

**Comment by careyotto** [comment]
Thank you, @peggygannon !

Talking points for Monday:

- Renaming section "Connected apps" vs. "Connected accounts"
- Empty state: "Get answers to Frequently Asked Questions" - why is this Title Case? On va.gov/sign-in-faq they use Sentence case...
- Empty state: "See the list of third-party applications" - What about something like: "Find apps to use" or "Explore third-party apps" instead?
- Re: "Veteran profile" -- I'm not sure if profile is the correct term to use. Some apps will have access to health data, but not everything else. Some will have access to service records, but not health. What does "your profile" mean to a Veteran? Would "your VA data" make more sense to users?
- Industry wide, I'm seeing the use of "apps and sites" more frequently than "applications and sites" and things like "the Apple app store" or "[VA mobile apps](https://mobile.va.gov/)"  -- curious your thoughts here for consistently using the long-form of the word. Can we mix it up and write more like humans talk?
- Review fifth screenshot copy together, this is a tricky one
- Review sixth screenshot copy together - this copy is not completely accurate. They may still have access to data (depends on the app). The only thing we can gaurantee is they can't get access to new data. Users may need to request the app permanently delete the data they already have if that's what they want to have happen. (There is a potential use case for a user disconnecting an account and not wanting what was cached to be deleted).

**Comment by Samara-Strauss** [comment]
@careyotto question for you — what profile data do these apps have access to? I imagine that would be a question of mine if I were a veteran, and I'd like to know the answer to it. I realize it may vary some between apps, but I think it would be helpful if we can give a broad definition (eg. "These apps may have access to your name, birth date, military history, etc...").

**Comment by careyotto** [comment]
@Samara-Strauss It varies from app to app. If user clicks "View more about [app]" link, widget expands to show exactly what information is shared for that particular app. Health or service records will be the most common types of data shared, but it may only be partial records.

**Comment by peggygannon** [comment]
Hello! @tressaellen @careyotto 

here is another pass at the content, based on our meeting on Monday. 
I've emphasized "third-party" more, as well as recommending a helper link "What's a third-party app?" to better distinguish this from VA Mobile Apps. 

One thing I was considering on this first screen, is do you think there is value in include a link to VA Mobile apps or a line of content explaining VA apps vs. third-party apps? Let me know your thoughts about this? 

-----

First screen shot

**Connected apps**
You don’t have any third-party apps or websites connected to your Veteran profile. If you connect a third-party app to your profile, it will have access to your Veteran data, like health and service records. Once you set up a third-party app, it will show here on your profile. 

{helper link} What is a third-party app? 
{helper text tk}copy tk if we think this is helpful to have? 


**Have questions about connecting an app to VA.gov?**
Get answers to frequently asked questions about how connected third-party apps work, what type of information these apps can see, and the benefits and risks of sharing your information.

[Get answers to frequently asked questions about connected apps](link URL tk)
[View available third-party applications](link URL tk)

OPTION:

 content about VA Mobile apps vs. third party ones?

[View available VA mobile apps](link to the VA Mobile app store?)

-------

Second screenshot

**Connected apps**
You’ve gave the below third-party apps and websites access to some of your Veteran data. Your data may have sensitive information so we recommend you disconnect access for any apps or sites that you no longer use or trust. 

{sample app} Apple HealthKit

Connected on [date]

Learn more about what information this app can see:

Apple HealthKit has access to your: 

-	e.g, , Health records

-       e.g, Service records

-----

Third screenshot
Disconnect modal

**Are you sure you want to disconnect this app?**
[Name of app] won’t be able to access your Veteran data anymore. This app will still have access to some information that you shared in the past. 
If you want to reconnect this app, you'll need to make that request through the app.   

{Buttons}
Disconnect
Cancel

--------
I recommend we use an informational alert box for the disconnect message

**This app has been disconnected**
[[Sample app] will no longer receive any new Veteran data about you. This app will still have access to some information that you shared in the past. If you want this app to no longer have access to any of your information, you’ll need to go to this app and request that it be deleted.

**Comment by careyotto** [comment]
@peggygannon Thanks for taking another pass at this. My feedback below:

> [View available third-party applications](link URL tk)OPTION:content about VA Mobile apps vs. third party ones?[View available VA mobile apps](link to the VA Mobile app store?)

Let's leave off for 1st party apps for now - I don't want to confuse users (first party don't display as a connected app) and I'm not in touch with that dpt. and don't know if they want to be linked to from here or not. For cover, we have a question about the differences between MyHealtheVet, VA Mobile App, and Connected third-party apps on the FAQs.

> Your data may have sensitive information so we recommend you disconnect access for any apps or sites that you no longer use or trust.

Feels like a run-on sentence. What about a comma between "...information, so..."  or breaking into 2 sentences? FYI, all apps that a Veteran connects to _will_ have sensitive data. If it wasn't sensitive, they wouldn't have to provide consent for us to share it.

> Learn more about what information this app can see:

I believe for accessibility, we need to be unique with each link name rather than repeating "learn more about this app" down the row. Also, some apps may do more than see. Language is something we need to fix upstream, because the bullet points below will be a mix of "verb + noun" and just "noun" until we do.

What do you think of saying **"Learn about [App Name] [carot icon]"** for the additional information link instead?

> Apple HealthKit has access to your:e.g, , Health records

NOTE: e.g. is a copy placeholder and not real content. The bullet point copy is controlled upstream in Okta.

> **Are you sure you want to disconnect this app?**
> [Name of app] won’t be able to access your Veteran data anymore. This app will still have access to some information that you shared in the past. If you want to reconnect this app, you'll need to make that request through the app.

This feels clunky, like we're trying to say too much in a modal confirmation msg. What do you think about nixing the second sentence (we can communicate this on the confirmation screen instead) and rewording the third sentence to more plain speak, like how a user would describe this action when talking to a friend? 

> **This app has been disconnected**
> [[Sample app] will no longer receive any new Veteran data about you. This app will still have access to some information that you shared in the past. If you want this app to no longer have access to any of your information, you’ll need to go to this app and request that it be deleted.

I'm worried this copy will mislead users into thinking their account is still connected, after disconnecting it. The term "access" may confuse people about connection rather than a saved copy. Instead of saying "This app will still have access" what about something more like, "This app may have saved some information you've shared in the past." Google phrases this as "The site or app won’t be able to access any more info from your Google Account, but you may need to request that they delete the data they already have." which reads really well to me. Would like to be able to be as clear with our users as they are with theirs.

Happy to hop on a call to noodle on the details, if that would be helpful.

**Comment by peggygannon** [comment]
Hello, @tressaellen and @careyotto Below are additional content and some followup questions. Thx.  

1. Screen 1

Question: Do you want to move forward with a helper link "what is a third-party app?" If so, i can provide content under that link. 

**Connected apps**
You don’t have any third-party apps or websites connected to your Veteran profile. If you connect a third-party app to your profile, it will have access to your Veteran data, like health and service records. Once you set up a third-party app, it will show here on your profile.

{helper link} What is a third-party app?
{helper text tk}copy tk

**Have questions about connecting an app to VA.gov?**
Get answers to frequently asked questions about how connected third-party apps work, what type of information these apps can see, and the benefits and risks of sharing your information.

[Get answers to frequently asked questions about managing connected apps](link URL tk)
[View available third-party applications](link URL tk)


-----

2. Screen 2

**Connected apps**
You gave the below third-party apps and websites access to some of your Veteran data. Your data has sensitive information, so we recommend you disconnect access for any apps or sites that you no longer use or trust.


Regarding this feedback:  *FYI, all apps that a Veteran connects to will have sensitive data. If it wasn't sensitive, they wouldn't have to provide consent for us to share it.*

Question on above feedback: Are you suggesting removing “sensitive” from the message? 


What do you think of saying "Learn about [App Name][carot icon]" for the additional information link instead?

--Yes, this is fine. 

Apple HealthKit has access to your:e.g, , Health records

NOTE: e.g. is a copy placeholder and not real content. The bullet point copy is controlled upstream in Okta.

--Yes, I put "e.g." as a placeholder. 

-----

3. Screen 3
Disconnect modal

**Are you sure you want to disconnect this app?**
[Name of app] won’t be able to access any more information from your Veteran data. You can reconnect this app at any time. To do this, go to the app and follow the steps to reconnect.   
{Buttons}
Disconnect
Cancel

regarding this feedback: *What do you think about nixing the second sentence (we can communicate this on the confirmation screen instead)*

I though part of this alert was to stress to the user that info they shared in past was still viewable by the app. If this is not essential to say here in this alert, then I'm ok with removing to condense alert. 


-------


4. Screen 4

Question: For this alert, is the action that the user needs to request the **connected app be deleted** from their account, or request that **past data** be deleted? 

last sentence might need to be tweaked based on answer to ^^


**This app has been disconnected**
[[Sample app] won’t be able to access any more information from your Veteran data. This app may have saved some information that you've shared in the past. To remove your past data, go to the app and follow the steps to delete the app from your account.

**Comment by careyotto** [comment]
Thank you, Peggy! I've taken another pass at this to tighten up some of the technical/data privacy implications. Please review. 

A few questions that came up, as I worked on this: 

- @peggygannon Re: your proposal for a "helper link" on screen 1, I'm intrigued. What do you have in mind for this? Would it compete too much with the gray box copy/links below it?
- I'm really struggling to find a "feel good" place for the copy on the disconnect modal. On one hand, it seems important to do double confirmation with users, because users can't undo this action from within VA.gov. But on the other hand, it is kind of annoying to ask, "Are you sure you want to disconnect, because you can reconnect at any time?" How we can bring some value here? What do y'all think of Option 2 below? @peggygannon @tressaellen 
- Do we need to be considering error state copy too? I don't know what those currently look like.

--------
`Screen 1 - EMPTY STATE `

**Connected apps** 
You don’t currently have any third-party apps or websites connected to your Veteran data, like health or service records. When you do, this is where you can manage them. 

_{helper link}_  What is a third-party app?
_{helper text tk}_ 

_{begin gray box}_ 
**Have questions about connected apps?**
Get answers to frequently asked questions about how connected third-party apps work, what types of information they can see, and the benefits of sharing your information.

Go to connected apps FAQs (link URL tk)
Find apps you can use (link URL tk) 
_{end gray box}_ 

---

`Screen 2 - FULL STATE`
**Connected apps**
You’ve given these third-party apps or websites access to some of your Veteran data, like health or service records. You can remove their access at any time by disconnecting the app. Disconnected apps can’t receive any new data from VA, but may still have access to information that was previously shared. 

_{begin app widget}_
**App Name**
Connected on Month DD, YYY
DISCONNECT (button)
Learn about [App Name][carot icon](link) 

**Apple HealthKit has access to your:**
- e.g. Health records
- e.g. Prescriptions

{gray box with FAQ and app directory links from Screen 1} 

------

`Screen 3 - Disconnect modal`

`OPTION 1:`
**Disconnect this app?**
[Name of app] won’t have access to new information about you from VA once you disconnect. You can reconnect through your [Name of app] settings.

Cancel (left button)
**Disconnect (right button)**

`OPTION 2:`
**Disconnect this app?**
[Name of app] won’t have access to new information about you from VA once you disconnect. This may impact the usefulness of the app.

Cancel (left button)
**Disconnect (right button)**

-----

`Screen 4 - Disconnect on-screen confirmation message
`
**This app has been disconnected**
[Name of app] won’t be able to access any new information about you from VA, but may still have access to information that was previously shared. To remove any stored data, contact [Name of app] and request permanent deletion.

**Comment by tressaellen** [comment]
Since we are starting usability sessions soon I'm just going to drop this copy in the designs and I'll update with approved copy after usability sessions.  Does that work @careyotto and @peggygannon ?

**Comment by Samara-Strauss** [comment]
@tressaellen we should only be testing approved copy.

@careyotto @peggygannon — I think Peggy should take one more pass at the copy, and unless there are truly concerning points of confusion, we should use that copy for testing. Most of what Peggy has included here has been about 99% of the way there, which means it's good enough to get in front of users to see if they have any questions.

**Comment by peggygannon** [comment]
@tressaellen @careyotto 
My recommendation for the helper link was to provide more context on Profile about what is a third-party app vs. a VA mobile app. I know you address this question in the FAQs. 
Might be good to see how this page tests before adding helper copy. 

I like OPTION 2 of the disconnect modal, as it tells user something rather then that they can reconnect.  With this rewritten message, however, we removed info on how people can reconnect. We might want to revisit this one again, if there are questions during user testing about reconnection.



-----

Screen 1 - EMPTY STATE

Connected apps
You don’t currently have any third-party apps or websites connected to your Veteran data, like health or service records. When you do, this is where you can manage them. 

{begin gray box}
Have questions about connected apps?
Get answers to frequently asked questions about how connected third-party apps work, what types of information they can see, and the benefits of sharing your information.

Go to connected apps FAQs (link URL tk)
Find apps you can use (link URL tk)
{end gray box} 

-----

Screen 2 - FULL STATE
Connected apps
You’ve given these third-party apps or websites access to some of your Veteran data, like health or service records. You can remove their access at any time by disconnecting the app. Disconnected apps can’t receive any new data from VA, but may still have access to information that you've previously shared. 

{begin app widget}
App Name
Connected on Month DD, YYY
DISCONNECT (button)
Learn about [App Name]carot icon

Apple HealthKit has access to your:

e.g. Health records
e.g. Prescriptions
{gray box with FAQ and app directory links from Screen 1} 

----
-----
Screen 3 - Disconnect modal

~OPTION 1:
Do you want to disconnect this app?
[Name of app] won’t have access to new information about you from VA once you disconnect. You can reconnect through your [Name of app] settings.~

~Cancel (left button)~
~Disconnect (right button)~


OPTION 2:
Do you want to disconnect this app?
[Name of app] won’t have access to new information about you from VA once you disconnect. This may impact the usefulness of the app.

Cancel (left button)
Disconnect (right button)

Screen 4 - Disconnect on-screen confirmation message
This app has been disconnected
[Name of app] won’t be able to access any new information about you from VA, but may still have access to information that was previously shared. To remove any stored data, contact [Name of app] and request permanent deletion.

**Comment by Samara-Strauss** [comment]
This looks good to me. Unless there are serious concerns from either @tressaellen or @careyotto — Tressa, let's use this copy for the prototype for testing so we can get this over the finish line. We can make improvements based on user feedback after that.
