### ISSUE TITLE
Fix date validation to prevent impossible dates

### ISSUE THREAD

**Issue by SamStuckey** [department-of-veterans-affairs/va.gov-team#67497]
From EVSS:

"The dev team has researched more than 100 of the 377 Null Pointer Exception errors in the batch from 9/9/2023. In all cases, the NPE was caused by a date field barfing on 31 for a month that only has 30 days in it."

The Null Pointer Exception referes to the following error from EVSS `getPdf`
`java.lang.NullPointerException`

This means that we are sending EVSS an impossible date.  After looking production failure records, the source of this bad date has been narrowed down to "Title 10 Activation".  e.g.
`{"title10Activation"=>{"title10ActivationDate"=>"2023-01-01", "anticipatedSeparationDate"=>"2023-11-31"},`

Additionally, it only seems to impact the `anticipatedSeparationDate` value.  

This implies that we are either
- not correctly validating this field in the user facing form
- doing some bad data transformation

## Acceptance criteria
1. fix the user facing validation
2. determine if (in the case this is not simple user error) if it's possible that we have been transforming data in one direction only, i.e. forward a day or backward a day, as this could inform our remediation solution

**Comment by austinjprice** [comment]
@SamStuckey new ticket created [Impossible Date Error](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/69455) and assigned to @zack
