### ISSUE TITLE
Create AL2-based Review Instance

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#67504]
# Description
Given that AL1 has reached end of life, we need to move all applications currently hosted on EC2 instances that are based on AL1 to the hardened version of the AL2 image that Platform recently created.

## Key Aspects
* At the time of the EC2 inventory snapshot there are 89 review instances running
* Review instances are already containerized

# Acceptance Criteria
- [ ] As review instances are created for PRs from `vets-website`, `content-build`, and `vets-api` they are created on a hardened AL2-based image

**Comment by ben-allen-oddball** [comment]
https://github.com/department-of-veterans-affairs/devops/pull/13588

**Comment by JoeTice** [comment]
SPRINT 38 UPDATE - Task is in progress, it is more complex and involved than initially accounted for, currently expect it will be completed in Sprint 39

**Comment by JoeTice** [comment]
Review Instances using the hardened AL2 image have been created, ongoing troubleshooting is continuing to drag on, so we will more clearly define that work for the next sprint in a new ticket.
