### ISSUE TITLE
[Congressional] V10933449 Due 11/2/2023 (Rep. Van Drew) 

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#67516]
## Issue Description
Veteran is unable to create a VA.gov login, and is unable to register on the Burn Pit Registry. Veteran's contact information is provided in the attached document.

https://dvagov.sharepoint.com/:f:/s/DigitalExperiencePMOInternalFTC-PrivateOCTO-DEActions/EoIV4LbqaItKr8S7YA52wJ4BLBSS_sg5sOUKGMneJyxbPQ?e=GI7Pev

---
## Tasks
- [x] Review congressional correspondence
- [ ] Resolve issue 
- [ ] Notify Veteran and congressional correspondence channel of solution.

## Acceptance Criteria
- [ ] Veteran issue will be resolved or responded to with final answer to issue 
- [ ] Congressional Correspondence will receive details of the resolution 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2023-CSM** [comment]
[Uploading... CTO Tracker.xlsx]

**Comment by Kimberley2023-CSM** [comment]
[CTO Tracker.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkkxQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--79987e4b605c6cb7ffe8491b029d2b48eb8d06c1/CTO%20Tracker.xlsx)

**Comment by Kimberley2023-CSM** [comment]
[Uploading... Copy of CTO Tracker.xlsx]

**Comment by Kimberley2023-CSM** [comment]
[Copy of CTO Tracker.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHBVQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--55121d27fde815088692092763a4671b6bf2d772/Copy%20of%20CTO%20Tracker.xlsx)

**Comment by Kimberley2023-CSM** [comment]
0/19:
EVSS identified a duplicate DEERS record as the root cause of the veteran’s login issue. They are working to resolve the duplicate and expect it will be completed tomorrow. Waiting on response.
Veteran responded advising they can sign into login.gov, and have no issue with identity. The issue is they cannot log into va.gov or any other portals due to the double DOD number not being updated in system.
Kimberley emailed Jeremy Haas (EVSS) to look into. Waiting on response.

**Comment by Kimberley2023-CSM** [comment]
FYI: 10/20: EVSS HD was able to get this issue resolved. They emailed veteran to advise them that the issue has been fixed, and asked them to confirm they are able to log-in. The veteran confirmed login was successful. Case closed.
