### ISSUE TITLE
[Content] Buggy Spokes on Education Page - Create Drupal Page for GI Bill Tool Widgets

### ISSUE THREAD

**Issue by AkucherGCIO** [department-of-veterans-affairs/va.gov-team#6752]
## Problem Statement
Clicking on Get Benefits on the Post 9/11 Statement of Benefits page reveals an empty accordion. The Manage and More spokes are showing only one or a couple child items each, and should actually be showing the content in the images below.
<img src="https://images.zenhubusercontent.com/5e4d73c84ff78270a88d2ae8/b7d67525-b344-4223-8ecb-c2e551aff5e3" width="200"><img src="https://images.zenhubusercontent.com/5e4d73c84ff78270a88d2ae8/f7f2d543-335b-42d5-9792-f6c9d8caa41f" width="200">

Refer to the bug for additional information: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/5396

## Acceptance Criteria
- [ ] Create a page at /education/gi-bill/post-9-11/ch-33-benefit and configure the side nav
- [ ] Create widget based on prelim work done in #6753

**Comment by RLHecht** [comment]
It appears this page has an anomaly that I'm not sure how to fix when bringing it into Drupal. There is an alert above the intro text, which I don't think can be done in Drupal. We have a react widget right under the intro already. @jenniferlee-dsva @ncksllvn @AkucherGCIO ![Screen Shot 2020-03-12 at 3.03.38 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/c96dc382-5ea7-4817-b772-c12c412eef74)

**Comment by jenniferlee-dsva** [comment]
Can we move it down below the intro text block?

**Comment by RLHecht** [comment]
@jenniferlee-dsva As long as it's OK that it's stacked above another widget. I'll try it and send the preview link when done.

**Comment by jenniferlee-dsva** [comment]
ewww. no, we can't stack an info alert on top of another info alert -- if that's what the widgets are. what's the URL of the live page - i may be able to suggest something if i can see the current content as a whole.

**Comment by RLHecht** [comment]
@jenniferlee-dsva https://www.va.gov/education/gi-bill/post-9-11/ch-33-benefit

**Comment by jenniferlee-dsva** [comment]
Hmm - I don't think we need that info alert. The same note text is already displayed right below the tool REACT component. Let's leave it off and we'll let Matt know about the Drupal constraints. 

Can't upload screenshot, so will Slack you. Sigh.

**Comment by ncksllvn** [comment]
I've been learning more about this logic...It works by -

1. The H1 heading is always shown
1. The data service status is checked to make sure it's available 
    1. While loading, the service-status banner is hidden, the intro text is hidden, and the CTA widget is hidden
    1. If the service status is found to be okay, we show the service-status banner saying it's available, then also show the intro text and CTA widget below that.
    1. If service status is found to be down, the service-status banner shows an error. The intro text and CTA are _not_ rendered.

So this is kind of a weird user flow compared to other tools. We may need to change this UX a bit. Particularly -

1 .The intro text should probably always be shown
1. We may want to combine the service-status banner with the CTA widget into a single banner

**Comment by RLHecht** [comment]
@jenniferlee-dsva @AkucherGCIO I built this page in Drupal minus the react widget for "Please sign in to check your GI Bill benefits," which I think @ncksllvn  needs to help me with. It's node Id 3007.  I can't configure the left nav yet because that can only happen before go-live.

**Comment by ncksllvn** [comment]
Yeah, need some product input to string this together...

The the data service is up, we should certain messaging that won't fit into the CTA widget, so we can't easily combine them into the same alert banner. Here's the possible message for the service-status banner -
- `The Post-9/11 GI Bill Benefits tool is available`;
- `The tool is available Sunday through Friday, 6:00 a.m. to 10:00 p.m. ET, and Saturday 6:00 a.m. to 7:00 p.m. ET.`;
- `The Post-9/11 GI Bill Benefits tool is down for maintenance`;
- `We’re sorry the tool isn’t available right now. The tool will be available again Sunday through Friday, 6:00 a.m. to 10:00 p.m. ET, and Saturday 6:00 a.m. to 7:00 p.m. ET. Please check back during that time.`;
- `The Post-9/11 GI Bill Benefits tool will be down soon for maintenance`;
- `The tool is available Sunday through Friday, 6:00 a.m. to 10:00 p.m. ET, and Saturday 6:00 a.m. to 7:00 p.m. ET. Please check back during that time.`;

**Comment by ncksllvn** [comment]
Although the tool's hours are shown below the CTA widget, so there's some redundancy - 

![image](https://user-images.githubusercontent.com/1915775/76636691-dcbd3380-651f-11ea-9d89-bd79c374495c.png)

**Comment by ncksllvn** [comment]
Here are the states with the status-check and CTA widgets combined -

### Service up
![image](https://user-images.githubusercontent.com/1915775/76640609-9d461580-6526-11ea-94b5-d427087e7dbe.png)

### Service down
![image](https://user-images.githubusercontent.com/1915775/76640837-0168d980-6527-11ea-8d85-d612240ca4a8.png)


### Service down soon (notice foot note)
![image](https://user-images.githubusercontent.com/1915775/76641024-4e4cb000-6527-11ea-8b5c-5a0a2849c239.png)

**Comment by jenniferlee-dsva** [comment]
Just catching up - per @ncksllvn 

> So this is kind of a weird user flow compared to other tools. We may need to change this UX a bit. Particularly -
> The intro text should probably always be shown

Yes - thought same thing.

> We may want to combine the service-status banner with the CTA widget into a single banner

Yes - if the tool isn't available, the sign in CTA should be totally replaced with (in the same widget) message about the tool hours and it being outside of the available window of time.  This is an odd kind of 'downtime' message. 
We should FYI  @peggygannon so she's aware this not-available-during-these-hours message. Not sure "down for maintenance" is the right language for this oddball. @ncksllvn - is that what appears today when the tool hours are in the not-available window?  

FYSA @RLHecht @MickinSahni

**Comment by jenniferlee-dsva** [comment]
@peggygannon ^ See above; please tb with me or Randi for details/Qs.

**Comment by ncksllvn** [comment]
>  @ncksllvn - is that what appears today when the tool hours are in the not-available window?

Yes it is! I just left the messaging alone. 

However, in the `Service down soon (notice foot note)` state, I changed the text of the foot note to explain the tool won't be available for much longer. Previously, it was showing a yellow warning banner, which would look weird with a warning banner plus the CTA widget below it (since the tool is still technical available, just not for long.) For the text of the foot note, I used what was previously in that warning banner.

**Comment by peggygannon** [comment]
@ncksllvn @jenniferlee-dsva Hello, so the background I have on this page is that this tool is down for maintenance at set times and we wanted to alert users to the times this tool IS available. This was in response to an influx of calls/emails from users trying to access it during it's "scheduled downtime." 

I think that footnote on the 3rd screenshot is not right (or some sort of bug)..

Do you think we could have just 2 states. . 
--CTA/sign in widget when tool is up
--Downtime message when tool is down for maintenance 

I'm not sure a "3rd" state if needed, as we list the tool hours in the footnote

**Comment by ncksllvn** [comment]
> Hello, so the background I have on this page is that this tool is down for maintenance at set times and we wanted to alert users to the times this tool IS available. This was in response to an influx of calls/emails from users trying to access it during it's "scheduled downtime."

It isn't necessarily _just_ checking the timeframe of the service. It appears to just be actaully checking the service's status to determine up/down time, but using the hours as a general guide. I think it's possible that the service be down at other random intervals too.

> I think that footnote on the 3rd screenshot is not right (or some sort of bug)..

There was a "warning" state before when we're about to exceed the operational hours. I borrowed the messaging from that and just dropped it as a foot note.

> I'm not sure a "3rd" state if needed, as we list the tool hours in the footnote

Sounds great! I'll make this update.

**Comment by ncksllvn** [comment]
### Service up
![image](https://user-images.githubusercontent.com/1915775/77078941-a96e1f00-69cd-11ea-911c-f8e15fccc603.png)

### Service down
![image](https://user-images.githubusercontent.com/1915775/77079155-f520c880-69cd-11ea-9c07-452465d32913.png)

**Comment by peggygannon** [comment]
@ncksllvn these updates look good to me.

**Comment by jenniferlee-dsva** [comment]
I love this. Simplify! And nav spokes fixed! Thank you @peggygannon and @ncksllvn and @RLHecht

**Comment by ncksllvn** [comment]
@RLHecht when you set this page up in Drupal, the widget ID you should use is `post-9-11-gi-bill-status`.  It should be similar to setting up the calculator on `/disability/about-disability-ratings/`.

**Comment by RLHecht** [comment]
@ncksllvn @jenniferlee-dsva I added the widget through Drupal and it's looking all right to me. @jenniferlee-dsva if you want to look at it in Drupal it's preview-prod.vfs.va.gov/preview?nodeId=3007 

I am not sure where it's supposed to lie in the left nav. @mnorthuis is this placement correct?

<img width="1308" alt="Screen Shot 2020-03-20 at 3 31 12 PM" src="https://user-images.githubusercontent.com/48728214/77199920-01854e00-6ac0-11ea-8d80-9a7047ac5c0b.png">

**Comment by mnorthuis** [comment]
@RLHecht It should be the same as the other pages in the hub, so that is correct placement.

**Comment by RLHecht** [comment]
I think all the work here should be done now. Just confirming I can set this page to publish @jenniferlee-dsva @ncksllvn

**Comment by ncksllvn** [comment]
Amazing! We have some coordination we need to do before we can publish unfortunately, outlined here, https://github.com/department-of-veterans-affairs/va.gov-team/issues/6756. But I think we can plan on making this happen tomorrow! CC: @MickinSahni

**Comment by jenniferlee-dsva** [comment]
So exciting! @RLHecht - could you be sure to let Matt Self know when this goes live? Thank you!

**Comment by MickinSahni** [comment]
@RLHecht 
Can you drop an estimate on this and add it to this sprint? 
Also, I assume this means we can close this ticket out too?

**Comment by RLHecht** [comment]
@ncksllvn I published this page. I'll let Matt know when it is live on the site. Moving to validate for now.

**Comment by RLHecht** [comment]
This page is now live and working. I let Matt know as well. Closing the ticket. FYSA @MickinSahni
