### ISSUE TITLE
[FE] Buggy Spokes on Education Page - Combine the status-check widget with the CTA widget

### ISSUE THREAD

**Issue by AkucherGCIO** [department-of-veterans-affairs/va.gov-team#6753]
## Problem Statement
The Post 9/11 Statement of Benefits page currently contains two widgets - a status-check widget to indicate whether the tool is online, offline, or is online but only for a limited time; and a standard CTA widget. For a simpler page presentation, we should combine these two widgets. 

The combined widget should then check the status of the tool's backend service, then render the CTA widget if the tool is available and an error message if not.

Refer to the bug for additional information: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/5396

## Acceptance Criteria
- [x] Combine the CTA widget with the status-check widget
- [x] CTA widget is shown when the service is available
- [x] An error alert box is shown when the service is unavailable
- [x] CTA widget is shown with a foot note indicating tool hours when the service's availability will change to unavailable soon

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by AkucherGCIO** [comment]
03/12/20 PW STandup
We have to check how routing is implemented by DevOps.  Configuration value needs to be checked.

**Comment by ncksllvn** [comment]
Cross-linking to content discussion - https://github.com/department-of-veterans-affairs/va.gov-team/issues/6752

**Comment by ncksllvn** [comment]
I think I need PO feedback on this. Based on the thread in #6752, it seems like we don't want to separate widgets on this tool page (a "status check" widget to show whether the tool is available, and a standard CTA widget.) It seems like the right idea it to combine - check the status of the tool, and then, if available, render the CTA widget. It would be kinda silly to show the CTA widget if the tool is unavailable anyway.

I think what we could combine the two widgets and ultimately produce these three states -

### Service up
![image](https://user-images.githubusercontent.com/1915775/76640609-9d461580-6526-11ea-94b5-d427087e7dbe.png)

### Service down
![image](https://user-images.githubusercontent.com/1915775/76640837-0168d980-6527-11ea-8d85-d612240ca4a8.png)


### Service down soon (notice foot note)
![image](https://user-images.githubusercontent.com/1915775/76641024-4e4cb000-6527-11ea-8b5c-5a0a2849c239.png)

**Comment by MickinSahni** [comment]
Reference

![image.png](https://images.zenhubusercontent.com/5e4d73c84ff78270a88d2ae8/b7d67525-b344-4223-8ecb-c2e551aff5e3)
![image.png](https://images.zenhubusercontent.com/5e4d73c84ff78270a88d2ae8/f7f2d543-335b-42d5-9792-f6c9d8caa41f)

**Comment by MickinSahni** [comment]
> ##Problem Statement
> Clicking on Get Benefits on the Post 9/11 Statement of Benefits page reveals an empty accordion. The Manage and More spokes are showing only one or a couple child items each, and should actually be showing the content in the images below.
> 
> Refer to the bug for additional information: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/5396
> 
> ## Acceptance Criteria
> * [ ]  Combine the CTA widget with the status-check widget


@ncksllvn can you double check that the acceptance criteria is accurate? i'll close out #6754 then

**Comment by ncksllvn** [comment]
@MickinSahni I updated the ticket title/description to align with our current approach. Feel free to close #6754

**Comment by MickinSahni** [comment]
2020-03-18 PW Standup
* Peggy to take a look and see if content of combined widgets is appropriate
* Have an open PR meanwhile that'll expose the combined widget for Drupal to consume

**Comment by MickinSahni** [comment]
2020-03-20 PW Standup
- once associated PR is merged, we'll be able to update in Drupal to create the new widget
- to validate, we'll drop a screenshot of local

**Comment by ncksllvn** [comment]
Merged, will go live today

**Comment by ncksllvn** [comment]
@MickinSahni I just realized that there's a really large visible different in the before/after of this work. 

The [Post-9/11 GI Bill Statement of Benefits](https://staging.va.gov/education/gi-bill/post-9-11/ch-33-benefit/) looks like this currently -

![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/3a167d04-ff42-4480-9a84-d00d08791b0c)

After deployment, the two widgets will be consolidated into one.

**Comment by MickinSahni** [comment]
> @MickinSahni I just realized that there's a really large visible different in the before/after of this work. I was for some reason caught up thinking about Drupal.

Yeah this ticket specifically refers to the work that'll make the combined widget available for Drupal to consume. Is that included in the PR? @ncksllvn

**Comment by ncksllvn** [comment]
Yep, same work!

**Comment by ncksllvn** [comment]
Updates are on Staging currently - 

![image](https://user-images.githubusercontent.com/1915775/77192602-2de69d80-6ab3-11ea-9390-b3b1c37e8c59.png)

**Comment by MickinSahni** [comment]
I see the combined

**Comment by MickinSahni** [comment]
2020-03-23 PW Standup
- Closing this out!
