### ISSUE TITLE
Define recruitment criteria for IPP Pilot On-site Testing for Veterans

### ISSUE THREAD

**Issue by SophiaPhilipMO** [department-of-veterans-affairs/va.gov-team#67548]
As UX Researchers and Designers, we need to define who we want to include in our IPP pilot onsite testing for Veterans and how we will recruit them through Perigean and MHV.

Tasks

- [x] Build recruitment criteria for on-site testing for Veterans

Acceptance Criteria

All Veterans must not have a verified Login.gov account
No more then 4 participants can have a Login.gov account (Answered “yes” to Q1)
No one can have a verified Login.gov account (Answered “Yes, and I have a verified Login.gov account” to Q2)
Veteran must be available to come in person to VHRC site
Veteran must be able to bring required documentation
Veteran must be able to bring personal smart device and access email at VHRC site
Participants with caregivers are able to participate but must be able to complete all research activities without caregiver support. 

Documented in [research plan](https://docs.google.com/document/d/14YplbTXAcj47wu71slKFMfqrhHnxH8SzllLa7N2cPkM/edit)

**Comment by lmorris3** [comment]
this ticket was in the backlog - is it a dupe? If not, this work is in progress/complete and can be reviewed and closed @SophiaPhilipMO

**Comment by SophiaPhilipMO** [comment]
@lmorris3 in progress but my understanding is these are the requirements:
- Veteran is not required to have a Login.gov account, verified or unverified
- Veteran must be available to come in person to VHRC site
- Veteran must be able to bring required documentation
- Veteran must be able to bring personal smart device and access email at VHRC site

**Comment by lmorris3** [comment]
Agree! I can update AC

**Comment by skirkman16** [comment]
Do we need to specify that the Veteran needs to come alone or can they be accompanied by a caretaker? Also for recruitment ease, should we just ask for Veterans who do not have Login.gov accounts so that one Veteran does not have multiple?

**Comment by skirkman16** [comment]
I included screener questions as well to accompany the recruitment criteria:
Screener Questions:


Do you have a Login.gov account?
Yes (if yes, please include no more than 4 participants with a Login.gov account)
No
Can you come in person to ___ VA Medical Center for a 2 hour research session between XX/XX/XXXX and XX/XX/XXXX?
Yes
No (if “No”, please exclude)
Can you bring one of the following identification documents and ensure that it is not expired?
State-issued driver’s license
State-issued identification card
Veteran Health Identification Card
Yes
No (if “No”, please exclude)
Can you bring a personal smart device on which you can access your personal email?
Yes
No (if “No”, please exclude)

**Comment by skirkman16** [comment]
Copied screener questions over to a comment under ticket [#77729](https://app.zenhub.com/workspaces/logingov-adoption-team-632280b31e745000136a61fc/issues/gh/department-of-veterans-affairs/va.gov-team/77729)

**Comment by SophiaPhilipMO** [comment]
Reviewed

**Comment by lmorris3** [comment]
Reviewed.
