### ISSUE TITLE
Define recruitment criteria for IPP Pilot Onsite Testing Proofing Agents

### ISSUE THREAD

**Issue by SophiaPhilipMO** [department-of-veterans-affairs/va.gov-team#67549]
As UX Researchers and Designers, we need to define who we want to include in our IPP Pilot onsite testing for Proofing agents and how we will recruit them through MHV so that we have participants that most realistically represent the anticipated end users.

Tasks

- [x] Build recruitment criteria for on-site testing for proofing agents
- [x] Discuss recruitment criteria with Perigean and Robyn Singleton or Shane Strassberg

Acceptance Criteria

- [x] Share out finalized recruitment with team and include in research plans

Notes on finalized criteria
- Available at selected VHRC site during scheduled Veteran sessions
- Participate in pre-pilot call and orientation call
- Have an active PIV card with access to:
- VA.gov
- Login.gov
- Identity Toolkit 
- Has used Identity Toolkit
- Complete requested tasks prior to and during the duration of the Pilot:
- Pre-pilot calls
- Available during scheduled sessions
- Complete surveys

**Comment by skirkman16** [comment]
We need to meet with Shane first to determine our backup plans for getting Veterans verified. This will help us decide what population we will need to recruit for this study.

**Comment by lmorris3** [comment]
@SophiaPhilipMO this was in the backlog - it's work that's been in progress for some time so may have a duplicate story associated with it. We can either close this or move to review and complete.

**Comment by SophiaPhilipMO** [comment]
@lmorris3 finalized criteria:
Notes on finalized criteria

Available at selected VHRC site during scheduled Veteran sessions
Participate in pre-pilot call and orientation call
Have an active PIV card with access to:
VA.gov
Login.gov
Identity Toolkit
Has used Identity Toolkit
Complete requested tasks prior to and during the duration of the Pilot:
Pre-pilot calls
Available during scheduled sessions
Complete surveys
