### ISSUE TITLE
Test Hardened AL2 Jumpbox

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#67545]
# Description
Now that the JumpBox hosting has moved over to instances based on the hardened AL2 AMIs, we need to verify that all functionality is still good. We will re-run the existing test plan from TestRail for this latest version of JumpBox.

# Acceptance Criteria
- [ ] The test plan has been executed and results recorded separately from the previous test run
- [ ] Defects have been reported and resolved or marked as won't fix

**Comment by IGallupSoCo** [comment]
My first pass with this particular test was successful.
https://dsvavsp.testrail.io/index.php?/runs/view/4931&group_by=cases:section_id&group_order=asc
