### ISSUE TITLE
Qualitative Data Request - Burials and Memorials - User Surveys

### ISSUE THREAD

**Issue by barron-charles** [department-of-veterans-affairs/va.gov-team#67558]
### Data Type Requested

User Surveys

### Date Range Start

10-13-2020

### Date Range End

10-13-2023

### Product Name(s)

Burials and memorials - Scheduling a burial

### Product Description

The Apply for burial in a VA national cemetery (Form 40-4962) currently isn't located on VA.gov and is in the process of being created and then implemented. It will be used by Veterans and other beneficiaries to apply to determine if they're eligible for burial at a VA national cemetery at their time of need. We need to determine if there is any survey data feedback from users for people regarding scheduling burials.

### Survey URL(s), key term(s), case category or type

The current websites applicable can be seen below:

1. Schedule a burial: (https://www.va.gov/health-care/schedule-view-va-appointments/)
- People looking to schedule a burial

2. Eligibility for burial in a VA national cemetery: (https://www.va.gov/burials-memorials/eligibility/)
- People looking to be eligible for burial

### File Delivery Format

One file, different tab for each term/URL

### Word Cloud

Yes

### VA Email Address(es)

charles.barron1@va.gov

### Add Assignee and Labels

If not already done so, please ensure @newworld2616 is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by newworld2616** [comment]
Hi, I have received the same request twice, please verify if the second ticket was created accidently. Thank you.

**Comment by ccruzgra** [comment]
@newworld2616 Charlie put in a request for a different system. This one is for the Medallia user surveys.

**Comment by barron-charles** [comment]
Hey @newworld2616, yes seconding what Cindy mentioned, the other one #67557 is for MyVA411.

**Comment by newworld2616** [comment]
Hey, I spoke with my team, it seems MyVA411 is coming from different source, it will not be available on Medallia. This form is designed for Medallia URL's only. Sorry for the inconvenience.

**Comment by barron-charles** [comment]
@newworld2616 For the links above with Schedule a burial and Eligibility for burial in a VA national cemetery, the Feedback information is unable to be retained versus MyVA411?

**Comment by newworld2616** [comment]
I understand, however, Medallia only captures the survey's that received on VA.gov itself from the Veterans. MyVA411 is available on Salesforce. I reached to my manager if I could be able to find the way to share that report with you.

**Comment by barron-charles** [comment]
Thank you! We really appreciate that.

**Comment by newworld2616** [comment]
Hi, I have shared the burial report in 2 emails via SharePoint on your VA email. Please verify once you receive them. Thank you.

**Comment by barron-charles** [comment]
@newworld2616 We've got them and the files are in solid shape.

**Comment by newworld2616** [comment]
Great! Thank you for the confirmation!
