### ISSUE TITLE
[Content] Buggy Spokes on Education Page - Configure the Post 9/11 widgets in Drupal

### ISSUE THREAD

**Issue by AkucherGCIO** [department-of-veterans-affairs/va.gov-team#6755]
##Problem Statement
Clicking on Get Benefits on the Post 9/11 Statement of Benefits page reveals an empty accordion. The Manage and More spokes are showing only one or a couple child items each, and should actually be showing the content in the images below.
![image.png](https://images.zenhubusercontent.com/5e4d73c84ff78270a88d2ae8/b7d67525-b344-4223-8ecb-c2e551aff5e3)
![image.png](https://images.zenhubusercontent.com/5e4d73c84ff78270a88d2ae8/f7f2d543-335b-42d5-9792-f6c9d8caa41f)

Refer to the bug for additional information: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/5396

## Acceptance Criteria
- [ ] _Configure the Post 9/11 widgets in Drupal
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by RLHecht** [comment]
@ncksllvn I don't see these widgets as options in the Drupal menu. Is this something you need to work on before I can do anything? Wondering if this ticket should be assigned to you.

**Comment by RLHecht** [comment]
Pretty sure this ticket can be closed since the work was done in the other buggy spoke ticket. Just confirming @ncksllvn

**Comment by ncksllvn** [comment]
@RLHecht Ah yep, this is done!
