### ISSUE TITLE
SOCKS access for [individual]

### ISSUE THREAD

**Issue by schiavo** [department-of-veterans-affairs/va.gov-team#67553]
### Your Name

Daniel Schiavone

### Your Email

daniel.schiavone@civicactions.com

### Your Role and Team

Backend engineer on Accelerated Publishing

### Product Manager (PM) name and email

Tim Cosgrove Product Manager m.cosgrove@agile6.com

### Product Owner (PO) name and email

Erika Washburn Erika.Washburn@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCw7IAhYXhAf4DgiZG+qLRmZ5dZZiuzKU0Be2HZzR1LSC/TZJeJPE2ii+ywt2OZlxwCaPAVZjJlpfax+FaiVuKEPUtLD9Ki/baERzyaXtjkE5Z42pWYXTUBw+BtnRg8m4bZwRj1e/4sROfEWL+TBWsgiXscCplQ5ND0B1DZfs7u/aTM5wt6XVCprY8gd1OlOlBT3ylNy/Zq4u1hhjtTq6wnsnWp3NSZO8GFKVC3RG1K3Jj/e5BQawP2C0N1T5IiY2LgpB2TzMxBXv+pSfbcTenDpfJMbXXOdc1dF6Eh4mR78Y5lNCIAiA30g0GgXTcTRGnZwVsdjnp/uSPpOfdi5q8/rxSmkAbtGZvPQrz5N1ad4MhGdUvoQyqRPTbZ7Rah0/QLPdy1qNJdAmLGLeKLxmv/QnzFjyeHJDkU4SG0SdjeIRcDJGUxO4XmefQs0snrKFd+CC9wgNkLqG7Lw2BKO5iM9OxmLMug98KdtxHWpwmpMGSszL0hbsl2agdW5ueLX18= schiavo@angelica

### E-QIP Transmittal Confirmation

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/7717261/f1762295-c6bb-491c-8c04-3f16ada26372)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by ph-One** [comment]
pubkey updated on SOCKS hosts. Closing.
