### ISSUE TITLE
Qualitative Data Request - Burials and Memorials - MyVA411

### ISSUE THREAD

**Issue by barron-charles** [department-of-veterans-affairs/va.gov-team#67557]
### Data Type Requested

Support

### Date Range Start

10-13-2020

### Date Range End

10-13-2023

### Product Name(s)

Burials and memorials - Scheduling a burial

### Product Description

The Apply for burial in a VA national cemetery (Form 40-4962) currently isn't located on VA.gov and is in the process of being created and then implemented. It will be used by Veterans and other beneficiaries to apply to determine if they're eligible for burial at a VA national cemetery at their time of need. We need to determine if there is any call center data for people calling in asking for help or seeking assistance scheduling burials.

### Survey URL(s), key term(s), case category or type

The current websites applicable can be seen below:

1. Schedule a burial: (https://www.va.gov/health-care/schedule-view-va-appointments/)
- People looking to schedule a burial

2. Eligibility for burial in a VA national cemetery: (https://www.va.gov/burials-memorials/eligibility/)
- People looking to be eligible for burial

### File Delivery Format

One file, different tab for each term/URL

### Word Cloud

Yes

### VA Email Address(es)

charles.barron1@va.gov

### Add Assignee and Labels

If not already done so, please ensure @newworld2616 is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by newworld2616** [comment]
Hi I have shared the requested data please verify once you receive it. Thank you!

**Comment by barron-charles** [comment]
Hey @newworld2616, I verify I have received it. Thanks!
