### ISSUE TITLE
[Launch] Publish /education/gi-bill/post-9-11/ch-33-benefit from Drupal with fixed sidebar

### ISSUE THREAD

**Issue by AkucherGCIO** [department-of-veterans-affairs/va.gov-team#6756]
We're rearchitecting the tool page for the [GI Bill Statement of Benefits](https://staging.va.gov/education/gi-bill/post-9-11/ch-33-benefit/) to be a Drupal page instead of a React component, so that its content and sidebar can be configured in Drupal. The launch will require a Drupal publish, vets-website merge and deployment, and a DevOps merge and deployment.

Related tickets:
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/6752
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/6753
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/6754

### Launch day requirements
- [x] In vets-website repo, update the application's [manifest.json](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/post-911-gib-status/manifest.json#L5) and routes by adding `/main` to the path and removing the intro-page.
- [x] In devops repo, update the [route](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/vars/react_routes.yml#L40) by adding `/main` to the path
- [x] Publish the Drupal page at `/education/gi-bill/post-9-11/ch-33-benefit/` with a configured sidebar

### Acceptance criteria
- `/education/gi-bill/post-9-11/ch-33-benefit/` is a Drupal page with a configured sidebar

**Comment by MickinSahni** [comment]
- Drupal page ready for launch
- Nick prepping for launch (no date specified)

**Comment by MickinSahni** [comment]
From #6752 
> Amazing! We have some coordination we need to do before we can publish unfortunately, outlined here, #6756. But I think we can plan on making this happen tomorrow! 

Sweet. This ticket is associated with the next sprint, but if we think it can be all wrapped up by tomorrow end of day then let's do it @ncksllvn

**Comment by ncksllvn** [comment]
@jenniferlee-dsva  This is all done and working great, but there's a side effect I hadn't considered. The tool landing page has its sidebar as configured in Drupal, but the tool itself doesn't have the sidebar.

<details>

<summary>Tool landing page(/education/gi-bill/post-9-11/ch-33-benefit/)</summary>

![image](https://user-images.githubusercontent.com/1915775/77470108-89cc6180-6de6-11ea-8031-cecc0ed8676c.png)

</details>

<details>
<summary>Tool (/education/gi-bill/post-9-11/ch-33-benefit/status)</summary>

![image](https://user-images.githubusercontent.com/1915775/77470294-cc8e3980-6de6-11ea-8ff2-6bb9183cf18b.png)

</details>

This is the same UX as the rest of our applications - a tool landing page written in Drupal that leads to a full React app - but still, this side effect hadn't occurred to me. Is this okay? Or should we consider our options for getting a sidebar on that page as well?

**Comment by jenniferlee-dsva** [comment]
@ncksllvn If I'm following you... the tool landing page is our unauthenticated content page. And the second page is the authenticated tool page that you land on after signing in. 

This is typical for our other authenticated apps, so this is fine. Thank you for checking!

**Comment by ncksllvn** [comment]
Awesome, thank you! It looks like the width of the authenticated tool needs to be reduced a bit (it looks like full-page width right now) so I'm addressing that now.

**Comment by MickinSahni** [comment]
2020-03-25 PW Planning
- Validated and closing out
