### ISSUE TITLE
SOCKS access for Jonathan Kamens

### ISSUE THREAD

**Issue by jikamens** [department-of-veterans-affairs/va.gov-team#67586]
### Your Name

Jonathan Kamens

### Your Email

Jonathan.Kamens@va.gov

### Your Role and Team

OCTO Platform Security Lead

### Product Manager (PM) name and email

Ray Wang

### Product Owner (PO) name and email

Ray Wang

### Access Type Requesting

platform

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDFRybYcFTGuhB97bEt9xwaeJ3bqmJdxiTdqbStyngGQP70q88Tt/SooCXFvJ4oDLG0mXpvaA82i9UV54Yztz2awO8tLMXtxdYXjiMmaLpBad5ePDJSxLAhHjfKLltLQzsGGkZgrTK1omASVYLU8f7b6jd8gFnGQkKPC9Ale3v5Q4KTs4fzbl4O33BJkieY5H80Tj4yOlDFsgv/aIgfqwVoaSFBoFDdWCHzkxy1vStZbjBpQdRG7D6ilj4hfueckCn1fLeQ1Csi4VeQVHyTxfSwwFDezgooTnOv1c4JEJl2m9U8woKEH8TludkWVeRb3lzBsxmevYoKN+SEOyW6d1/e8338JF/T8Nb9j3edhySJRHbxRa1pctjzNVP9BRokDTrvqzDka9aPTZYhWtHkl1uAisaopUO6CHSnC4BiotmUx+PB5nsiL6CQBc8SUERNYADaj/cKyXTne46D61bixRvnQr8UdEREbtcvQhI91NpNZ9lstFu+bRxk/MlJlUndsjk= jik@jik5.kamens.us

### E-QIP Transmittal Confirmation

N/A I'm a fed govt employee already cleared to work (as evidenced by the fact that I have a va.gov email address which isn't issued until background check is adjudicated).

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by JonathanKamensDVA** [comment]
Darn it, I filed this from the wrong account. My DVA Github account is @JonathanKamensDVA.

**Comment by JonathanKamensDVA** [comment]
Closing since submitted from wrong Github account.
