### ISSUE TITLE
Google Tag Manager/Google Analytics Clean Up

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#6759]
## High Level User Story/ies
As a Google Analytics specialist, I need to update GA/GTM backlog items so I can more accurately and more quickly support teams building GTM into their applications.

## Hypothesis or Bet
**If** _we update filters, datalayer implementations, etc._ **then** _we expect to more accurately and quickly implementation GTM_.

### What must be true in order for you to consider this epic complete? 

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

Tasks from the attached issues are completed, & a summary is documented.

## How to configure this issue
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)

**Comment by jonwehausen** [comment]
Closing as historical epic.
