### ISSUE TITLE
Flipper UI access for Sebastian Caso

### ISSUE THREAD

**Issue by s-caso** [department-of-veterans-affairs/va.gov-team#67598]
### Your Name

Sebastian Caso

### Your GitHub handle (Flipper UI access is managed through GitHub)

s-caso

### Team, Role, and Company of the target individual

MEB team Seneca Resources

### Please confirm if you are on Atlas, Platform Team Roster or are a Federal User

- [X] [Atlas](https://dev.va.gov/atlas)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [X] Lesser Environments (Dev/Staging/Sandbox)
- [X] Production (if requesting, justify prod access below)

### Reason for Production Access (If requested)

I am a developer that will implement feature flags and will need the ability to turn them on and off.

**Comment by bdech** [comment]
Verified in Atlas

**Comment by bdech** [comment]
Hi @s-caso You've been granted access to production and lower environments.
