### ISSUE TITLE
SOCKS access for Michael Marchand (VANotify)

### ISSUE THREAD

**Issue by MarchandMD** [department-of-veterans-affairs/va.gov-team#67621]
### Your Name

Michael Marchand

### Your Email

michael.marchand@docme360.com

### Your Role and Team

rails engineer

### Product Manager (PM) name and email

Melanie Jones - Melanie.Jones@oddball.io

### Product Owner (PO) name and email

Beverly Nelson - Beverly.Nelson@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQClRia8Z6eMxtso9tgeBy1L88zwhV9N0BD14kCHhUE2RptjznkyHrPUY0VFLxLQKushNUv6zZNoPJNago993R349GhqA9K/MrcW6POVcS9f+5IHKQbXd0glxIog6ZDrx9ERHzCE++nFoVa3IzlsM9R0cNHk0JKGMYYGlL3Pgbn42DJ6m9CZxNjzITinlD9N6x7h0kNC+7ZVug9axUgGyuqSCGqlMzWJ18T3jmCZwB5CYCfZylnfUNns+8JHLoEXNEjsbv3YAjN7oEXQhCRgMBZf1JOxAQBLYCqcg2+qRrfq91EG+8oSepUwrsW8cWd/BxeFkMgUjzBCFaAvOmoJXKEsgWeuzLs6m8EVxgsJPZThIXc4IqnPXWR2KNIQSAGclkKksRQMaI9zdr3TU+4scL/WTACaswl7tYDAHpf8nh5CYP3h1eIGenbcPs12MJk/N3LgtIig1ZFAw1kB7KWUjE35dkTjcM+7A/4tldldp6SUteb1poh0PaMCoG65yYSrIh8= michaelmarchand@Michaels-MacBook-Pro-2.local

### E-QIP Transmittal Confirmation

<img width="813" alt="Screen Shot 2023-10-13 at 3 08 05 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/35391349/f2010085-34fa-4e42-9c49-c0e64ede883f">

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by ph-One** [comment]
pubkey added to SOCKS hosts. Closing.
