### ISSUE TITLE
Break Up Mockups into Workflow Specific Files

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#6762]
## Goal
Using one large mockup between Design and Frontend is starting to become cumbersome and it would be easier if they were more discrete and specific to each workflow.

## Tasks
- Breakup the mockups into smaller files so that changes can be found quickly and clearly
- A centralized hub has been created that acts as a table of contents for all the mockups

## Acceptance Criteria
- [x] Links to the new workflow mockups are shared with the team

**Comment by sporeboy** [comment]
Github page set up to track latest Add Dependents mockups: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/features/view-update-dependents/research-design

Mockups broken into discrete files with dedicated XD links.
