### ISSUE TITLE
Discovery to prepare for collaboration cycle mid-point review

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#67635]
## Issue Description
As a new Pension team getting ready to incorporate feedback from CAIA into designs,
We need to understand how to prepare for upcoming Mid-Point review,
So that we can predict and prevent any potential blockers for the next phase of the collaboration cycle touchpoint that will be required.

Question about research/testing:
- When does user testing usually happen?

Notes:

- Julie to cover collaboration cycle during daisy share & WoW

---
## Task ideas
- Product to schedule meeting with Governance team, Shira Goodman.
- Document any process recommendations and/or concerns.
-- When should we go to mid-point review?
-- What do we need to have available at this point?
-- What should we be concerned about?
- Share any insights from meeting with rest of the Pension team.

## Acceptance Criteria
- We will have as much information as we can to prevent any blockers by the time we attend our mid-point review
- We will know when in the design/build phase we should schedule a mid-point review

**Comment by aplatt-coforma** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/67635?planning-poker) with Zenhub @vbellissimo

**Comment by vbellissimo** [comment]
**What’s the difference between Governance Team & CAIA team?**

- CAIA works more collaboratively, than Governance team
- Governance is more point in time, during collaboration cycle touchpoints
- Governance will always create Github tickets for any findings and tuck them under the “Collab Cycle kickoff” epic in GitHub
- Treat the Governance Team’s Design Intent touchpoint as a kickoff for a baseline on Content, Accessibility & IA feedback; CAIA is invited to Design Intent for don’t always go to them; But they are trying to standardize so that CAIA uses the Design Intent as their kickoff for their more thorough review
- Lean on CAIA collaboration, they might provide more in-depth feedback (which is what we’re already doing)
- Unsure how CAIA handles feedback; sounds like they also create Github tickets for us once their feedback is officially submitted?

**Prepare for Midpoint Review**

- Incorporate CAIA feedback into designs including content/accessibility considerations
- Ensure new pages have mobile designs

**Schedule/attend Midpoint Review**
**Prepare for Staging Review/Addressing accessibility issues**

- Incorporate any defect-0 and defect-1 identified by CAIA (still waiting on this)
- We can start an internal accessibility review of our own
- Do engineers have an automated way of scanning for accessibility issues? - Yes, Brian DeConnick does the auto scans after we do our internal reviews
- Sidenote: Our engineer (Todd) did an internal accessibility review already using Governance team’s accessibility specialist’s (Brian DeConnick) checklist on Platform website; Brian will then complete an automated scan of his own and review Todd’s findings
- When we get to Staging Review - we need to be sure anything that was labeled a “must” during other touchpoints (Design Intent, Midpoint Review, etc.) needs to be addressed at this point

**Schedule/attend Staging Review**

**What about engineering-specific touchpoint?**
- No backend engineering support/touch points from Governance

**What about mobile friendliness?**

- From an accessibility perspective, we encourage to design mobile-first
- If we don’t provide mobile designs during collaboration cycle touchpoint, governance will probably call us out on it

**To do:**

- New VFS team template: fill this out for our team-level profile: https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=analytics-insights%2C+governance-team%2C+platform-orientation&template=new-vfs-team.md&title=New+VFS+Team+%5BInsert+team+name+here%5D
