### ISSUE TITLE
Define recruitment criteria for IPP Pilot Usability Testing, Proofing Agents

### ISSUE THREAD

**Issue by SophiaPhilipMO** [department-of-veterans-affairs/va.gov-team#67644]
As UX Researchers and Designers, we need to define who we want to include from Proofing Agent segments in our IPP usability tests and how we will recruit them through Perigean and MHV so that participants are representative of the intended end user population.

Tasks

- [x] Build recruitment criteria for IPP usability test for Proofing Agents
- [ ] Discuss recruitment criteria with Perigean and Robyn Singleton or Shane Strassberg

Acceptance Criteria

- [ ] Share out finalized recruitment with team and include in research plans

**Comment by SophiaPhilipMO** [comment]
@lmorris3  @porta-antiporta please review criteria for proofing agents in the usability test

**Comment by lmorris3** [comment]
@SophiaPhilipMO these look good to me
