### ISSUE TITLE
Health checks from HA proxy adjustment

### ISSUE THREAD

**Issue by luis-simauchi** [department-of-veterans-affairs/va.gov-team#67652]
Our health check interval from the haproxy.conf.j2 is defaulted at 2 secs
This is too busy for monitoring purposes, the suggestion was to bump it up to 5 mins (J. Faulkner has his DT synthetics run every 5 mins) 

file in github:
https://github.com/department-of-veterans-affairs/devops/blob/b18a661a13b44336895d1aff798d701cfca39b8d/ansible/deployment/config/fwdproxy/haproxy.conf.j2#L131

## Tasks
- [x] Make a time interval change in line 131 from 2 secs to 5 mins.

**Comment by jadon1979** [comment]
https://github.com/department-of-veterans-affairs/devops/pull/13662
