### ISSUE TITLE
Improve search input behavior

### ISSUE THREAD

**Issue by cosu419** [department-of-veterans-affairs/va.gov-team#67650]
## Issue Description
The location/rep inputs on the search page could be improved for demoing purposes. Should more closely simulate the proposed UI design. 

## Acceptance Criteria
- [x] Use controlled inputs for search

**Comment by holdenhinkle** [comment]
BUG:
If you enter text in the search field and click 'search', a summary of the search and results appears, like this:

> Showing 1 - 10 of 15 results for "Veteran Service Organization (VSO)" near "ny, ny"

If you then type something else in the search field, the area in the search results summary string updates as you type. It should only update when the user clicks 'Search' again.
