### ISSUE TITLE
[Security] - Investigate and resolve GH alerts

### ISSUE THREAD

**Issue by brandonrapp** [department-of-veterans-affairs/va.gov-team#6766]
Github admins reached out to VSP regarding a series of GH alerts that need attention.  [[Ticket](https://github.com/department-of-veterans-affairs/transition-to-GitHub/issues/711)]

It has several [vulnerabilities](https://github.com/department-of-veterans-affairs/vets-website/network/alerts) which I wanted to make sure that you are aware of. I also wanted to offer my assistance as a GitHub Engineer to help you work through these vulnerability alerts.

Goals:

- [x] Identify alerts that are client facing and resolve those first
- [x] Figure out if we need to address the other issues
- [x] Create a triage plan in work tracking tool (JIRA, GitHub Issues, etc.)
- [x] If the vulnerability is acknowledged as will not fix, you can mark that in GitHub vulnerabilities page by clicking dismiss.
- [x] Monitor email alerts for new security vulnerabilities and assign a first responder.
  - Link to the ticket - https://github.com/department-of-veterans-affairs/transition-to-GitHub/issues/711#issuecomment-592175354 
   - You can set the notifications for security alerts as shown below
![75486085-bbc1e380-5960-11ea-989f-a53cad5d03d5](https://user-images.githubusercontent.com/53306579/76438235-1dd30d80-6391-11ea-9a01-c9da4ca15fdc.gif)

**Comment by jhonnyoddball** [comment]
A [Github alert log](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/frontend/github-alerts-log.md) was created to keep track of these alerts

**Comment by brandonrapp** [comment]
Thanks for the hard work @jhonnyoddball - I am going to close this out!
