### ISSUE TITLE
Evaluate feasibility of moving from carrierwave to ActiveStorage

### ISSUE THREAD

**Issue by johnpaulashenfelter** [department-of-veterans-affairs/va.gov-team#6768]

**Comment by erluti** [comment]
need to move away from apivore also, as it's not been maintained to work with Rails 6

**Comment by erluti** [comment]
ActiveStorage doesn't support multiple s3 buckets.  Multiple uploaders in our codebase are using different s3 buckets, including different access keys.
Rails 6.1 has [merged a PR](https://github.com/rails/rails/pull/34935) that includes support for different storages for attachments.

**Comment by erluti** [comment]
Helpful link for moving from carrierwave to activestorage https://medium.com/epfl-extension-school/moving-from-carrierwave-to-activestorage-in-a-rails-app-31f13e3ff37d

**Comment by johnpaulashenfelter** [comment]
Closing since we know the answer for Rails 6 is no, spinning up another for Rails 6.1
