### ISSUE TITLE
Add unit test coverage for ConfirmedAppointmentDetailsPage/index.jsx

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#67687]
## Description
Add unit test coverage for `vaos/appointment-list/components/ConfirmedAppointmentDetailsPage/index.jsx`

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEk5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c879f62c3b625cf9931ed743300e4f51d2a517d3/Screenshot%202023-10-16%20at%201.18.23%20PM.png)

---

## Acceptance Criteria
- [ ] file coverage for Branches, functions, lines and statements is 100%

## Definition of Done
- [ ] All acceptance criteria are met

**Comment by JunTaoLuo** [comment]
Closed as obsolete in favor of the new approach in https://github.com/department-of-veterans-affairs/va.gov-team/issues/89844.
