### ISSUE TITLE
Claim Status Tool - Build Object Map in Trello

### ISSUE THREAD

**Issue by kristinoletmuskat** [department-of-veterans-affairs/va.gov-team#67692]
Here is the object map: https://github.com/orgs/department-of-veterans-affairs/projects/1098/views/1

**Comment by kristinoletmuskat** [comment]
- [ ] Migrate discovery object map into github projects location
- [ ] Add values, screenshots, and open questions to object map
- [ ] Create object guides for objects
- [ ] Add object guides to object map
- [ ] Review with teams

**Comment by kristinoletmuskat** [comment]
![Image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/122126772/2b6d9485-35da-4e85-a0df-6ee99fbe2377)

**Comment by laurwill** [comment]
Hi @kristinoletmuskat , I'm changing the title to say Trello instead of GH, just FYI

**Comment by coforma-jamie** [comment]
@kristinoletmuskat is there a specific Trello account we should use for this?

**Comment by kristinoletmuskat** [comment]
Today we met and did a debrief / discussed next steps here: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1685651799860/5650343beef05a9a54338afb385bef5cdd189485?wid=0-1708542663029

As a next step we're going to create a summary of top findings re: structural/foundational problems uncovered and opportunities to fix them, and present that to OCTO before going to product team. I'm going to close out this ticket and create a new one.
