### ISSUE TITLE
[Support] Implement Cross-Domain Tracking on ID.me

### ISSUE THREAD

**Issue by nedierecel** [department-of-veterans-affairs/va.gov-team#677]
## User Story
As a personalization stakeholder, I want to see the funnel exits in the ID.me registration or authentication flow. Currently, this is only tracked to ID.me's GA account and not to VA.gov. This is an extension of an issue on VFT: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/12262

## Goal
_What outcome(s) do we want to see?_

## Acceptance Criteria
- [ ] _What needs to happen or be created?_

## Definition of Done
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by joanneesteban** [comment]
@jonwehausen Check with Lisa for Personalization prioritization.

**Comment by nedierecel** [comment]
@bsmartin-ep This is an iceboxed issue that might not be relevant given the changes to SSO. In any case, there is a [previous issue that has more detail](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/12262), if you'd like more context.
