### ISSUE TITLE
MVP: Home page

### ISSUE THREAD

**Issue by cosu419** [department-of-veterans-affairs/va.gov-team#67705]
## Product Outline
[MVP Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/mvp.md)

## High Level User Story
As a user searching for a representative, I need to be able to understand the steps I'll be taking to appoint a representative.

## Hypothesis or Bet
**If** _we provide a detailed overview for the steps to appoint a representative_, **then** _users will be able to make more informed decisions, which will lead to higher user satisfaction_.
  
## Definition of done
- If a user is logged in, display the existing representative (if available) and provide guidance on how to change that representative
- Functioning on both desktop and mobile
- Passed all QA tests including edge cases, performance, and security tests
- Accessibility features implemented and verified via testing
- User documentation updated
- Monitoring and analytics set up to track key performance metrics

**Comment by oddball-lindsay** [comment]
CAIA is managing the landing page that will contain entry points into our Find and Appoint tools.
