### ISSUE TITLE
Vets-api terminal access for Sean Midgley

### ISSUE THREAD

**Issue by Midge-dev** [department-of-veterans-affairs/va.gov-team#67711]
### Your Name

Sean Midgley

### Your GitHub handle (terminal access is managed through GitHub)

@Midge-dev

### Team, Role, and Company of the target individual

Non-disability benefits experience

### Product Manager (PM) name and email

Laura Steele laura.steele@coforma.io

### Product Owner (PO) name and email

Matt Self matthew.self2@va.gov

### COR Name (leave "None" if you listed an AWS user name above)

None

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

None

### Please confirm if you are on the VFS Team Roster or Platform Team Roster

- [X] [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Please confirm E-QIP Transmittal/Adjudication. This could be a screenshot of your Transmittal/Adjudication email, a link to another request where you've submitted this proof (i.e. AWS/SOCKS), etc.

- [X] I have attached proof that I have either transmitted my E-QIP survey or previously received a favorable decision (by including in "Additional Notes" section below)

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [ ] sandbox
- [ ] production (if requesting, justify prod access in 'Additional Notes' section)

### Additional Notes

For testing a new endpoint for RES system so that we can complete a redirect. Currently assisting in testing

https://github.com/department-of-veterans-affairs/va.gov-team/issues/65386

### Additional resources for Support Engineer

- [ ] For users on a VFS team but not in the VFS Team Roster, they must start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] Instructions for handling requests [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access) - Support Only

**Comment by IsaiahMW1** [comment]
Found in VFS Roster

**Comment by IsaiahMW1** [comment]
@Midge-dev Can you please provide a screenshot of your E-QIP transmittal, or some form of favorable adjudication?

**Comment by IsaiahMW1** [comment]
@Midge-dev  https://github.com/department-of-veterans-affairs/va.gov-team/issues/62982  Did you possibly put this ticket in by mistake ? you were already granted access attached previous ticket
