### ISSUE TITLE
Auth discovery

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#67719]
A proper and sound AuthZ/AuthN experience is critical to the long-term success of the omnichannel Travel Pay API, and thus a feature we need to start incorporating now. It is also a significant unknown for building out a generic API.

Artifacts:
- [x] Sequence diagram of probable auth flow
- [ ] Flow chart of auth flow
- [ ] Questions/Notes trail (can be included as comments on this issue)

Done when:
- [x] Seq diagram created/uploaded to github product directory
- [ ] Flow chart created github product directory
- [ ] High priority questions answered

**Comment by kjduensing** [comment]
Simplified Sequence Diagram of proposed auth flow: https://github.com/department-of-veterans-affairs/va.gov-team/blob/btsss-auth-diagram/products/health-care/beneficiary-travel/engineering/auth-seq-diagram.md

note this file is not yet in the main branch

**Comment by kjduensing** [comment]
This API is meant to be generic yet internal - can we rely on the sign-in service (SiS) to perform generic enough auth, or is it too tightly integrated with vets-api?

**Comment by kjduensing** [comment]
Will likely have to set up some sort of service account, as described here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Sign-In%20Service/auth_flows/service_account.md#service-account-authentication

**Comment by kjduensing** [comment]
Setting up a service account, reliance on the SiS, and other processes will be important to document for a future playbook.

**Comment by kjduensing** [comment]
@i4dm-va-jpatterson, we chatted briefly about moving the call to `/introspect` up to when the client requests a token from the Travel Pay API. To me, it's slightly more secure to call `/introspect` on every request to the endpoint to prevent revoked tokens from continuing to be valid (e.g. if a Veteran logs out, it doesn't revoke the token provided to vets-api by the travel pay api). 

I know it's a balance though - what were your thoughts again on how this affects performance?

**Comment by i4dm-va-jpatterson** [comment]
@kjduensing, my thoughts are: validation of the token every time - yes; introspection every time - no.  I do agree that we want to validate the token on every call to a Travel Pay endpoint, for that very reason.  However, I don't think we need to introspect on every call; that can be done once per Travel Pay token generation.  I'm assuming that introspection is a much more expensive call than token validation, so I think we'd want to avoid doing that on every endpoint request.

If the validation of the token fails, then the Travel Pay token can be invalidated as well, and the user would be forced to log in and generate a new token.  I don't think we're looking at a "one token to rule them all" scenario.  Each call to a Travel Pay endpoint would need to provide both an auth token and a Travel Pay token, and the Travel Pay API would validate both tokens.

**Comment by kjduensing** [comment]
> I don't think we're looking at a "one token to rule them all" scenario.

Agreed. Ok great, thanks for your input. Feel free to drop any other comments/questions on the diagram here!
