### ISSUE TITLE
JWT token endpoint access (after token registered)

### ISSUE THREAD

**Issue by lee-delarm6** [department-of-veterans-affairs/va.gov-team#67717]
- JWT Generation steps listed in doc `mobile-oauth-on-behalf-of.md` in our email
- Create service call from `vets-api` to `/token` endpoint `https://veteran.apps.va.gov/sts/oauth/v1/token`, refer to doc above for exact request contents
    - i.e. Create controller

https://github.com/department-of-veterans-affairs/va.gov-team/issues/66679

**Comment by loripusey** [comment]
Replacing with more detailed tickets; closing
