### ISSUE TITLE
[COPY-EDIT] Review content of "HEALTH SERVICE LIBRARY" Document for plain language and reusable content [COPY-EDITOR]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#6771]
## User Story or Problem Statement
As a Veteran Web user, I need a need a plain language description of services in all "Health Services" web selections for ALL Health Care System website, so I can quickly understand the services and service location for my needs.

## Goal
_Efficient and clear content describing local Work With US Page?_

## Objectives or Key Results this is meant to further
- _Reduced word count and improved plain language._
_Where copy is stored and where it will be placed for review_

##Resources
[Health Service Library Document](https://drive.google.com/drive/folders/1UIS7kL2oAdwJ7fd5ghN0U_AMpyFQEBlI)
[VAMC Share Drive](https://drive.google.com/drive/folders/1w6O8JZ42Jkp1Sa9QOt9Lv4R9WjJFEp3O)

## Tasks
_The steps that must be complete before hand off to PAO/Product Lead review_
- [ ] Review all current Health Services for standardized and plain language content.  Consolidate if required, throw out any unusable content and keep all bullet points that can be used across the VAMC systems.
- [ ] Provide approved and final document to have team work from.

## Acceptance Criteria
_The steps that must be complete before hand off to PAO/Product Lead review_
* Review all current Health Services for standardized and plain language content.  Consolidate if required, throw out any unusable content and keep all bullet points that can be used across the VAMC systems.
* Provide approved and final document to have team work from.

**Comment by LouCarlozo63** [comment]
On it! :)
