### ISSUE TITLE
Generate RSA key for vets-api access to MAP services

### ISSUE THREAD

**Issue by lee-delarm6** [department-of-veterans-affairs/va.gov-team#67713]
Generate RSA key for vets-api access to MAP Vaos

This is required to setup attachment for MAP access requests later on. Any RSA key generation should do (512). Refer to `mobile-oauth-on-behalf-of.md` for more info

This ticket is just for generating (and storing) the key somewhere useful (TBD)

**Comment by loripusey** [comment]
I think this is a duplicate, closing
