### ISSUE TITLE
Atlas: File Deletion Automation

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#67725]
https://adhoc.slack.com/archives/C045LCF8WU8/p1697488987616479?thread_ts=1697488706.406479&cid=C045LCF8WU8

- [x] Create File Removal in Repo
- [x] Create CronJob in manifest repo

**Comment by RachalCassity** [comment]
PR: https://github.com/department-of-veterans-affairs/platform-atlas/pull/189

**Comment by RachalCassity** [comment]
Cron job PR: https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/2361/files

**Comment by RachalCassity** [comment]
Awaiting PR approvals 🎉
