### ISSUE TITLE
API Export

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#6773]
## Problem Statement
How might we provide feedback to data owners about data quality? 

## Goal
Identify latest data available via vets-api

## Objectives or Key Results this is meant to further
OBJECTIVE 2: Deliver meaningful facility information 

---
## Tasks
-[ ] Export data provided by vets-api for VHA, VBA, NCA, Vet Centers

**Comment by darkbushido** [comment]
Generated a csv after running the sync jobs
[VaFacilities::CsvSerializer](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/va_facilities/lib/va_facilities/csv_serializer.rb)

```
require 'va_facilities/csv_serializer'

file = File.open('tmp/facilities.csv', 'wb')
file << VaFacilities::CsvSerializer.to_csv(BaseFacility.all)
file.close
```
