### ISSUE TITLE
[UX] [Content] Write action link text for file a BT claim for appts list

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#67737]
## Tasks

- [ ] Write action link text for file a BT claim for appts list and provide to Ya-ching

For reference in [sketch](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/1238ECAD-399B-44ED-BEFF-F6F523D5CFE6/canvas):

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNG8vQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b7a6a0a2d933855b0ef6bab89b46de0c7f07300a/Screenshot%202023-10-16%20at%206.57.14%20PM.png)

## AC

- [ ] Review with UX team. Christina needs it for CodePen. Ya-ching needs it for her design work.

**Comment by kellysmith1008** [comment]
Note to self when starting this ticket - I really like the {x days to file} idea that Ben highlights in the mobile app annotation in sketch. I want to twirl that around in my head for a bit - just placing that idea here to remind me later

**Comment by benbrasso-agile6** [comment]
Twirl away, I like the idea too. As this scales up to work with the Appointments on VA.gov design (meaning, they have more page elements than we do), it might be hard to squeeze into the appt list page. Definitely easier on the detail page. The Appointments team will be our "consultants" as far as, "is this going to work on [desktop for Appointments on VA.gov designs](https://www.figma.com/file/JpGM8LGBCqAlL8qh3DmFk8/Home-Page-Redesign?type=design&node-id=5359-95479&mode=design&t=1zZpwcDt36TMRxLW-0)?"

Their (Appointments / VAOS) approach is very much, keep the appt list simple, which was also the decision when deciding to  not include After Visit Summary on the appt list page.

**Comment by benbrasso-agile6** [comment]
Actually... now that I'm thinking about what Brian said today... I don't even know if we can do this... taking this to Slack...

**Comment by benbrasso-agile6** [comment]
@kellysmith1008 https://www.figma.com/file/JpGM8LGBCqAlL8qh3DmFk8/Home-Page-Redesign?type=design&node-id=5630-28991&mode=design&t=OclESQ5exAsthUod-0

**Comment by benbrasso-agile6** [comment]
I feel like this one, we need to talk to VAOS and Kristen again about. I.e., whether to even include an action in the list or not. I know Ciera was exploring design ideas. cc @cgednalske

**Comment by cgednalske** [comment]
Update: In VAOS and Check-in discussions, it was decided that, along with statuses, CTAs would not be included on the appointments list for the mvp. This also aligns with the Appointment integration approach AVS is currently following by including prompts on the details page only. 

Note: Appointments continues to look into how different CTAs (for pre-check-in and travel, for example) might be incorporated, so this may change. 

@kellysmith1008 will let you decide what we need to do with this - if we want to find out more about VAOS work with CTAs or close it out

**Comment by kellysmith1008** [comment]
@cgednalske Yeah, I think we can close it out. I want to stay as consistent as possible, so if CTAs are not included for mvp then we should follow suit. And in that case, I think "File a travel reimbursement claim" as the link works just fine. I'll wait to hear from you for confirmation, but as long as you're on board with this too, I'll close the ticket :) 
@ytsaoca I should ask you as well if you want me to leave this ticket open until you get the mockup finished or if you're good if I close it?

**Comment by benbrasso-agile6** [comment]
Think we can close
