### ISSUE TITLE
Bug - MHV Loa1 user is prompted for terms of use

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#67748]

**Comment by bosawt** [comment]
johnservice mhv user both on SSOe and SiS staging.va.gov is being asked to complete tou when they likely shouldnt be.

**Comment by bramleyjl** [comment]
Show ToU to anyone who has an icn/mhv_icn, even if they're LoA1

**Comment by bramleyjl** [comment]
Per @joeniquette saying that MHV LoA1 users that possess ICNs should go through ToU acceptance, I authenticated with this user on staging & looked up their account, `johnservice` user does have an ICN on their account:
```ruby
[#<Account:0x00007f6b94b5ea80
  id: 2581,
  uuid: "ecdbcfbe-1640-4276-8988-15fda467f494",
  idme_uuid: "615d5a1fee3a4b55a64a3a90f6b6859f",
  icn: "1013572359V541856",
  edipi: "2110114055",
  created_at: Fri, 22 Oct 2021 19:53:05.194716000 UTC +00:00,
  updated_at: Mon, 14 Nov 2022 18:56:38.392622000 UTC +00:00,
  sec_id: nil,
  logingov_uuid: nil>]
```
