### ISSUE TITLE
Bug - MHV Loa1 user shown terms of use for SiS, not for SSOe

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#67749]

**Comment by bosawt** [comment]
uncorrtest2 mhv user is an loa1 user. When using ssoe they dont get shown tou but when you login through sis you see tou.

**Comment by joeniquette** [comment]
for MHV accounts that have an ICN but appear to be LOA1 its ok to show them ToU. So the real question is why does it differ when sis or ssoe is used. Both should act the same.

**Comment by dickdavis** [comment]
Confirmed issue was limited to the user in the ticket, implying an issue with the user data; the user was previously verified but changed to unverified at a later time, which is not something that can happen in production environment.

Added missing coverage for LOA1 users in the sessions controller spec to ensure functionality is behaving as expected and that future regressions are caught.
