### ISSUE TITLE
Bug - sign in 2 browsers at once - TOU work around

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#67750]

**Comment by bosawt** [comment]
bug? sign into Alfredo via IDme (line 6 on mvi sheet). Accept TOU on Chrome, sign into Safair. Go to TOU page on Chrome and selelct "decline" > Signed out of Chrome, continue to be signed in on Safari even when moving pages | NEXT sign out and back in on Safair I do get the TOU page again

**Comment by rileyanderson** [comment]
This should be resolved with frontend adding logout for SiS. The issue was on `Decline and sign out` it was attempting to logout with SSOe even if SiS was being used so the session was not getting destroyed.
https://github.com/department-of-veterans-affairs/vets-website/pull/26257
