### ISSUE TITLE
Business intake form for Mail Automation Services (MAS)

### ISSUE THREAD

**Issue by kimdonna** [department-of-veterans-affairs/va.gov-team#67776]
## Your Details
1.  **Kim Donna**
​
2.  **VBA, Office of Business Integration (OBI), Mail Automation Services (MAS)**
    (ex., claims, health, etc.)
​
## Notification Details
1.  **Email**
    (email, text/SMS, or both)
​
2.  **We would like to send emails to applicants submitting requests for Pre-Need Eligibility for Burial Benefits and also an email to notify of status of request.**
    (This is your chance to tell us an overview of your plans.)
​
3.  **What actions can the user take based on the notification they receive?** View message only.
    (ex., view secure messages, fill out a survey, schedule an appt, etc.)
​
5.  **What is the desired business outcome?** reduce duplicative submissions, provide status update of pending requests
    (ex., fewer skipped appointments, less call center volume, etc.)
​
6.  **What system will kick off the notification? Please note the system should be inside the VA or have an ATO.** Mail Automation Services (MAS) VBAAP,
    (ex., BVA hearing reminders are kicked off from Caseflow)
​
7.  **What will trigger the notification?** MAS will send data to VANotify upon receipt of an application in the Centralized Mail Portal and as it goes through the automation process.
    (ex., clicking submit, status updates for claims, appointment reminders, new services available)
​
8.  **Provide sample content per notification type, if you have it.** Pending from LoB (National Cemetery Administration NCA)
    Please note we collaborate with all of our users on their content to ensure it meets standards.
​
9.  **Has a Privacy Officer (PO) seen and approved the content? If not, do you know who your PO is?** Will mirror current existing VA.gov automated email notifications, LoB will obtain this approval.
    (ex., PO has seen the content but it is not approved)
​
10.  **Would you prefer to provide contact information for the recipients or would you rather VA Notify look this up for you by Veteran ID? If by ID, please let us know what identifier is used in your system.** TBD with LoB
    (ex., VAPROFILEID, PID, BIRLS, ICN, etc.)
​
11.  **Do you currently capture communication preferences related to this notification? If so, please describe.** Will be based on provided email address on application
    (ex., opt in for claim status updates via email or text)
​
12.  **What is the anticipated volume of notifications per day, week, month?** TBD
​
13.  **When does this notification need to be in production?** TBD

**Comment by bevnobev** [comment]
@kimdonna Thanks for filling out the intake request so quickly.  FYI, when the form is filled out on va.gov, VA Notify sends an email confirmation.  See below.
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/74934207/5d5ca830-685b-4036-bed0-04fdccd1c134)

**Comment by kimdonna** [comment]
Thank you for that information, we are in communication with the VA.gov folks in this effort; however we are wanting to mirror that process for applications received via Centralized Mail Portal and Fax.

V/R,
Kim Donna
Senior Program Analyst
Veteran Benefits Administration
Office of Business Integration (20C)
T: 202.701.0756

***@***.***

From: Beverly Nelson ***@***.***>
Sent: Tuesday, October 17, 2023 11:18 AM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Donna, Kim A., VBAVACO ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Business intake form for [Business or team] (Issue #67776)


@kimdonna<https://github.com/kimdonna> Thanks for filling out the intake request so quickly. FYI, when the form is filled out on va.gov, VA Notify sends an email confirmation. See below.
[Image removed by sender. image]<https://user-images.githubusercontent.com/74934207/275906020-5d5ca830-685b-4036-bed0-04fdccd1c134.png>

-

**Comment by mjones-oddball** [comment]
Met 11/2 to kickoff. Working with Nick to get a list of team members to be onboarded to the self service portal and domo.
