### ISSUE TITLE
[BE] 10-10EZR: Create Logging for EZR form

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#67787]
As a team member, I would like to have logging for the new EZR online form so that if something goes wrong I can see what happened and make improvements. 

- [ ] Create logging
- [ ] Copy logging from EZ (unless not applicable, e.g. "email failed to send")
- [ ] **Success: EZR errors are logged**

**Comment by jadon1979** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/14290
