### ISSUE TITLE
[BE/Data] 10-10EZR: Alerts for EZR

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#67792]
As a team member, I would like to receive alerts for when the EZR fails/there are issues so that I know when things aren't working and I can work to fix them.

- [x] Create email alerts from Datadog
- [ ] Create dashboard in DD that displays everything like for the EZ
- [ ]

**Comment by jadon1979** [comment]
https://vagov.ddog-gov.com/dashboard/kjp-9wp-u47/10-10ezr?refresh_mode=sliding&from_ts=1698687972770&to_ts=1698691572770&live=true

**Comment by hdjustice** [comment]
Reviewed Datadog dashboard, and it seems to suit our needs for our MVP launch!  Nice job @jadon1979
