### ISSUE TITLE
Business intake form for NEPEC-BHL

### ISSUE THREAD

**Issue by kreynolds-va** [department-of-veterans-affairs/va.gov-team#67816]
## Your Details
1.  **Your Name**
​
Rani Hoff

2.  **Business Line**
​
Health - Send clinical wellness checks to guard against deterioration and meet Joint Commission requirements for program evaluation.

## Notification Details
1.  **Notification type**
​
Text/SMS

2.  **Please describe your use case.**
​
Because of the nature of mental illness, which can be chronic and/or episodic, it is important for VA to keep in touch with Veterans after starting or ending a course of mental health treatment. We are proposing to send clinical assessments of mental health symptoms and functioning to Veterans who have received mental health care to check on their health and guard against deterioration. The information gathered through these checks can also be used to meet Joint Commission requirements that mental health programs must collect data on the effectiveness of services.

These messages fall within the wellness checkups as defined in the Standard Operating Policy for Delivering Personalized Notifications via Text Messages - 3. c. i. “Health care communication, including communication about appointment and exam confirmations and reminders, wellness checkups, hospital pre-registration instructions, pre-operative instructions, lab results, post-discharge follow-up intended to prevent readmission, prescription notifications, and home healthcare instructions.”

3.  **What actions can the user take based on the notification they receive?**

They can follow a link to fill out wellness checkups via BHL Touch.

4.  **What is the desired business outcome?**
​
There are two desired outcomes. The first is to ensure that if Veterans deteriorate, that information can be transmitted to an appropriate clinician who can respond to the Veteran’s needs.  Second, effectiveness data can assist programs with making changes to services that are not showing to be effective.

5.  **What system will kick off the notification? Please note the system should be inside the VA or have an ATO.**
​
NEPEC houses a database in CDW that identifies those Veterans who should be sent clinical measures. BHL can connect directly to the NEPEC database and kick off the notifications to VA Notify.

6.  **What will trigger the notification?**
​
In the case of inpatient programs, notification triggers will be a discharge from the program.  In the case of outpatient mental health programs, notification triggers will either be a discharge from the program or the completion of a round of treatment.

7.  **Provide sample content per notification type, if you have it.**
​
NEPEC VA GOV: Because of your recent VA treatment, the VA would like to check in with you about your current mental well-being. If interested, please press the link for more information. <URL>

8.  **Has a Privacy Officer (PO) seen and approved the content? If not, do you know who your PO is?**
​
There has been no review.

9.  **Would you prefer to provide contact information for the recipients or would you rather VA Notify look this up for you by Veteran ID? If by ID, please let us know what identifier is used in your system.**
​
Yes, we would prefer VA Notify to look up contact information by Veteran ID.

10.  **Do you currently capture communication preferences related to this notification? If so, please describe.**
​
No, we do not currently capture communication preferences related to this notification.

11.  **What is the anticipated volume of notifications per day, week, month?**
​
5,000/week

12.  **When does this notification need to be in production?**

12/1/2023

**Comment by mjones-oddball** [comment]
Hi @kreynolds-va I might be misunderstanding, but this sounds like it pairs well with the MBC use case. Is there a reason why you don't want to use the same contact info and preference strategy for these follow-up wellness checks?

**Comment by kreynolds-va** [comment]
Dr. Hoff,

Can you please answer Melanie's question below regarding the request for a NEPEC specific short code?

"this sounds like it pairs well with the MBC use case. Is there a reason why you don't want to use the same contact info and preference strategy for these follow-up wellness checks?"
Thank you,

Kent



From: Melanie Jones ***@***.***>
Sent: Friday, October 20, 2023 11:02 AM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Reynolds, Kent S. ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Business intake form for NEPEC-BHL (Issue #67816)


Hi @kreynolds-va<https://github.com/kreynolds-va> I might be misunderstanding, but this sounds like it pairs well with the MBC use case. Is there a reason why you don't want to use the same contact info and preference strategy for these follow-up wellness checks?

-

**Comment by kreynolds-va** [comment]
The message will not be coming from their provider directly, but after care has been completed. We don't want to confuse Veterans and potentially mislead them into thinking that their provider is sending things directly to them.  I hope that makes sense but let me know.

Best,
Rani

Rani A. Hoff, PhD, MPH (she/her/hers)
Director, Northeast Program Evaluation Center (NEPEC)
Office of Mental Health and Suicide Prevention (11OMHSP)
Department of Veterans Affairs Central Office
Professor of Psychiatry
Yale University School of Medicine
Ph 203-584-8344 (cell)

PANDA dashboard
[A panda munching on ***@***.***<https://vaww.visn1.portal.va.gov/connecticut/nepec/default.aspx>

From: Reynolds, Kent S. ***@***.***>
Sent: Friday, October 20, 2023 1:26 PM
To: 'department-of-veterans-affairs/va.gov-team' ***@***.***>; department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Mention ***@***.***>; Hoff, Rani A. (she/her/hers) ***@***.***>
Subject: RE: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Business intake form for NEPEC-BHL (Issue #67816)

Dr. Hoff,

Can you please answer Melanie's question below regarding the request for a NEPEC specific short code?

"this sounds like it pairs well with the MBC use case. Is there a reason why you don't want to use the same contact info and preference strategy for these follow-up wellness checks?"
Thank you,

Kent



From: Melanie Jones ***@***.******@***.***>>
Sent: Friday, October 20, 2023 11:02 AM
To: department-of-veterans-affairs/va.gov-team ***@***.******@***.***>>
Cc: Reynolds, Kent S. ***@***.******@***.***>>; Mention ***@***.******@***.***>>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Business intake form for NEPEC-BHL (Issue #67816)


Hi @kreynolds-va<https://github.com/kreynolds-va> I might be misunderstanding, but this sounds like it pairs well with the MBC use case. Is there a reason why you don't want to use the same contact info and preference strategy for these follow-up wellness checks?

-

**Comment by mjones-oddball** [comment]
@kreynolds-va Will their provider get to see their responses in case they need to follow-up on their wellness? Or is this a questionnaire to rate the care they received?

**Comment by kreynolds-va** [comment]
Dr. Hoff,

Can you please answer Melanie's question below?

Thank you,

Kent



From: Melanie Jones ***@***.***>
Sent: Monday, October 23, 2023 10:44 AM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Reynolds, Kent S. ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Business intake form for NEPEC-BHL (Issue #67816)


@kreynolds-va<https://github.com/kreynolds-va> Will their provider get to see their responses in case they need to follow-up on their wellness? Or is this a questionnaire to rate the care they received?

-

**Comment by kreynolds-va** [comment]
Both.  If a measure indicates that somebody is in crisis or has significantly deteriorated we will forward that information to clinicians who can act on it. We already have a robust mechanism in place for doing this that has worked very well for six or seven years.

Best,
Rani

Best,
Rani

Rani A. Hoff, PhD, MPH (she/her/hers)
Director, Northeast Program Evaluation Center (NEPEC)
Office of Mental Health and Suicide Prevention (11OMHSP)
Department of Veterans Affairs Central Office
Professor of Psychiatry
Yale University School of Medicine
Ph 203-584-8344 (cell)

PANDA dashboard
[A panda munching on ***@***.***<https://vaww.visn1.portal.va.gov/connecticut/nepec/default.aspx>

From: Reynolds, Kent S. ***@***.***>
Sent: Monday, October 23, 2023 11:56 AM
To: 'department-of-veterans-affairs/va.gov-team' ***@***.***>; department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Mention ***@***.***>; Hoff, Rani A. (she/her/hers) ***@***.***>
Subject: RE: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Business intake form for NEPEC-BHL (Issue #67816)

Dr. Hoff,

Can you please answer Melanie's question below?

Thank you,

Kent



From: Melanie Jones ***@***.******@***.***>>
Sent: Monday, October 23, 2023 10:44 AM
To: department-of-veterans-affairs/va.gov-team ***@***.******@***.***>>
Cc: Reynolds, Kent S. ***@***.******@***.***>>; Mention ***@***.******@***.***>>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Business intake form for NEPEC-BHL (Issue #67816)


@kreynolds-va<https://github.com/kreynolds-va> Will their provider get to see their responses in case they need to follow-up on their wellness? Or is this a questionnaire to rate the care they received?

-

**Comment by mjones-oddball** [comment]
@kreynolds-va Are ya'll available on 1/17 or 1/18 between 3 and 4 pm ET for a 30 minute sync to chat about requirements and next steps for NEPEC? CC @bevnobev

**Comment by mjones-oddball** [comment]
Use case was launched by BHL on 2/8/2024
