### ISSUE TITLE
Ramp up profile forms to 50%

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#6781]
## Tasks
- [ ] Ramp up profile forms to 50%
- [ ] Monitor Google Analytics to ensure everything stays consistent

Relevant Google Analytics views:
- https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.rowStart=0&explorer-table.rowCount=25&_r.drilldown=analytics.eventLabel:profile-transaction/
- https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.rowStart=0&explorer-table.rowCount=25&_r.drilldown=analytics.eventLabel:profile-deleted/
- https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.rowStart=0&explorer-table.rowCount=25&_r.drilldown=analytics.eventLabel:profile-edit-failure/
- https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.rowStart=0&explorer-table.rowCount=25&_r.drilldown=analytics.eventLabel:profile-saved/

**Comment by erikphansen** [comment]
I flipped it to 50% of users on Thursday, March 12, 2020 at 11:01 AM ET

**Comment by erikphansen** [comment]
Update Friday, March 13, 2020 11:54 AM ET: so far no indication that having the new forms rolled out to 50% of users has an noticeable impact on contact info updates. Numbers for March 12 are more or less in line with a normal Thursday. I'll continue to monitor over the weekend and plan to ramp up to 100% on Tuesday assuming things continue to look good. @Samara-Strauss @mshea0606 feel free to take a look at the numbers yourself!

**Comment by Samara-Strauss** [comment]
Sounds good to me! Thanks for the update!

**Comment by mshea0606** [comment]
@erikphansen Thanks for the update!
