### ISSUE TITLE
Review Prior Research & Learn How to Conduct Research at VA

### ISSUE THREAD

**Issue by jefflbrauer** [department-of-veterans-affairs/va.gov-team#67826]
https://depo-platform-documentation.scrollhelp.site/research-design/research-at-va

**Comment by StevenStraily** [comment]
I completed my initial review and came up with a list of relevant prior research with justifications.
Here is a link to a Google document with that research: [(https://docs.google.com/document/d/1lRgzV_LUVbhxhjKNwmq37YwEl98jeAop/edit?usp=sharing&ouid=115089626870218731585&rtpof=true&sd=true)]

**Comment by baltes** [comment]
@StevenStraily Unless there are objections we'll close this as part of wrapping up sprint 6. 

@dhill802  @marywang2
