### ISSUE TITLE
Forms Library Discovery

### ISSUE THREAD

**Issue by jefflbrauer** [department-of-veterans-affairs/va.gov-team#67827]
https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-getting-started-with-the-forms-li

**Comment by StevenStraily** [comment]
I have completed an initial review of the documentation.

This is largely going to be a developer task for duplication in onboarding. It wouldn't hurt for Researchers/Designers with a technical background or desire to learn the technical side to have a look as well, though.
