### ISSUE TITLE
Update disability ratings tables for 2020

### ISSUE THREAD

**Issue by AnneHurley** [department-of-veterans-affairs/va.gov-team#6783]
Request from VBA/Sandy Tadeo to update disability ratings benefits tables:
https://www.va.gov/disability/compensation-rates/veteran-rates/

From Sandy:
Use these rates:

[2020 disability compensation tables update screenshot]
(https://github.com/department-of-veterans-affairs/va.gov-team/files/4319873/2020.disability.compensation.tables.updates.docx)

 
**What is status of legacy page?**

**Comment by AkucherGCIO** [comment]
03/12/20 PW Standup
Effort will take all of today.

**Comment by AnneHurley** [comment]
https://prod.cms.va.gov/node/986/edit 

@AkucherGCIO @RLHecht and @jenniferlee-dsva  FYSA. I am moving the dialogue to the main ticket capturing all these pages. It's ready for copyedit.

**Comment by AnneHurley** [comment]
Now that this is part of #6833, I think we can close this @AkucherGCIO

**Comment by MickinSahni** [comment]
> Now that this is part of #6833, I think we can close this @AkucherGCIO

Hey @AnneHurley, can you confirm that #6833 acceptance criteria, etc. is updated with any items from this ticket? I can close this out then.

**Comment by AnneHurley** [comment]
@MickinSahni @lunascoop  Yes this ticket and the related one ^ have been completed and tickets can be closed.

**Comment by MickinSahni** [comment]
2020-03-16 PW Standup
* Closing out as work's complete
