### ISSUE TITLE
SPIKE: Investigate on stale setECheckInCalled status

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#67840]
## Tasks
- Investigate on stale setECheckInCalled status
- Create remedy ticket(s)

**Comment by kanchanasuriya** [comment]
As part of 45 minute text reminder feature implementation work, vets-api calls `CHIP/set-e-check-in-started` API when **setECheckInCalled** field in lorota set with `false`. Currently, **setECheckInCalled** field in lorota stays false even after calling CHIP/set-e-check-in-started API in 45 minute text reminder workflow. 

This causes vets-api calling CHIP/set-e-check-in-started API more than once in edges cases like,
1. When a veteran reloads the check-in page 
2. When a veteran comes for a second appointment later in the day & uses the same check-in link.

Couple of impacts,
1. CHIP/set-e-check-in-started API called more than once unnecessarily and adding latency
2. Metrics on CHIP/set-e-check-in-started API calls would have an offset in the event of above-edge scenarios

As the impact seems to be negligible, we are moving forward with stale **setECheckInCalled** field in lorota.
