### ISSUE TITLE
Facility Locator accessibility research 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#6784]
## User Story 
As a Veteran using assistive devices, I want Facility Locator to be functionally accessible to me so that I can search for a location to  meet my needs.

## Objectives or Key Results this is meant to further
OBJECTIVE 3: Deliver a usable and accessible experience

## Goals of research
Understand how Veterans expectations for search results differ for users of assistive devices, including:

## Acceptance Criteria
[ ] Approved research plan which requests recruitment of 5+ participants who access VA.gov using assistive devices

[ ] Approved conversation guide

**Comment by jenstrickland** [comment]
👏  Please let me know if I may be of assistance!
