### ISSUE TITLE
Spike: VANotify understand comms options and requirements

### ISSUE THREAD

**Issue by buddhima-coforma** [department-of-veterans-affairs/va.gov-team#67842]
### Description 
As PB team, we need to understand how to activate and utilize communication tools so that we can reach out to selected veteran cohort

### Criteria
- Know how to initiate communication and what's needed to do so
- Learn lead time to submit ticket request
- Discover any options and criteria we need to be aware of when communicating
- Know if messages went through or not + re-try mechanisms

### Definition of done
- Know enough to execute later. Document findings for later. Outline any nuances, gaps, risks and issues.
- Demo post-standup or async -> get feedback from necessary parties -> generate follow up tasks if any -> close ticket

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-proactive-64e7650c29bb1113de04a02a/issues/department-of-veterans-affairs/va.gov-team/67842?planning-poker) with Zenhub @mjknight50 @wayne-weibel @danlim715

**Comment by mjknight50** [comment]
![image (1)](https://github.com/department-of-veterans-affairs/va.gov-team/assets/3513353/aa6ae52b-0a9b-4c86-b2b5-002dc5a215a3)

**Comment by mjknight50** [comment]
More findings from Christie:
https://dsva.slack.com/archives/C054Q2SKJ59/p1697738845002829?thread_ts=1697650504.255779&cid=C054Q2SKJ59

**Comment by mjknight50** [comment]
I have requested access to VA Notify

**Comment by mjknight50** [comment]
Utilizing the VA Notify system is a straight-forward process.  After completing the intake ticket, I was given a service ID and API key.  I then downloaded the Postman collection that was provided and tried out some scenarios.

Sending an email is straightforward once you have the ID and key.  

`POST https://staging-api.va.gov/vanotify/v2/notifications/email`
Body:
```
{
    "template_id": "{{email-template-id}}",
    "email_address": "matt.knight@coforma.io",
    "personalisation": {
        "name": "Matt",
        "service": "Proactive"
    }
}
```
The service returns:
```
{
    "billing_code": null,
    "content": {
        "body": "Hello Matt\n\nThis is a generic email for you to be able to test your Proactive requests.\n\nBest,\nVA Notify",
        "subject": "A Generic Email Subject"
    },
    "id": "174bdac8-0ea7-4167-88f8-08aca19bdd7e",
    "reference": null,
    "scheduled_for": null,
    "template": {
        "id": "df6b212b-cd35-44d6-80c7-3bfe84bb3078",
        "uri": "https://staging-api.va.gov/services/725bbdd4-5a6e-4688-8678-fae4323ef3a3/templates/df6b212b-cd35-44d6-80c7-3bfe84bb3078",
        "version": 1
    },
    "uri": "https://staging-api.va.gov/v2/notifications/174bdac8-0ea7-4167-88f8-08aca19bdd7e"
}
```

Using the id returned, I can then query the status:
GET https://staging-api.va.gov/vanotify/v2/notifications/174bdac8-0ea7-4167-88f8-08aca19bdd7e

```
{
    "billing_code": null,
    "body": "Hello Matt\n\nThis is a generic email for you to be able to test your Proactive requests.\n\nBest,\nVA Notify",
    "completed_at": "2023-11-17T14:49:50.988771Z",
    "cost_in_millicents": 0.0,
    "created_at": "2023-11-17T14:49:47.296462Z",
    "created_by_name": null,
    "email_address": "matt.knight@coforma.io",
    "id": "174bdac8-0ea7-4167-88f8-08aca19bdd7e",
    "line_1": null,
    "line_2": null,
    "line_3": null,
    "line_4": null,
    "line_5": null,
    "line_6": null,
    "phone_number": null,
    "postage": null,
    "postcode": null,
    "provider_reference": "010a018bddc2699c-89445a78-1a06-4589-9103-10775a285bb4-000000",
    "recipient_identifiers": [],
    "reference": null,
    "scheduled_for": null,
    "segments_count": 0,
    "sent_at": "2023-11-17T14:49:47.791038Z",
    "sent_by": "ses",
    "sms_sender_id": null,
    "status": "delivered",
    "status_reason": null,
    "subject": "A Generic Email Subject",
    "template": {
        "id": "df6b212b-cd35-44d6-80c7-3bfe84bb3078",
        "uri": "https://staging-api.va.gov/v2/template/df6b212b-cd35-44d6-80c7-3bfe84bb3078/version/1",
        "version": 1
    },
    "type": "email"
}
```

This tells me if the email was delivered.

New templates can be created by logging into  https://staging.notifications.va.gov/ while on the VA network.
![Screenshot 2023-11-17 at 10 08 53 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/3513353/9f5a60f6-d560-4b97-b881-46b434597fdd)
