### ISSUE TITLE
[IE11] Request for homepage banner configuration sometimes failing

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#6785]
I can't seem to replicate this, but according to our [monitoring](http://sentry.vfs.va.gov/vets-gov/website-production/issues/71873/?query=is%3Aunresolved), the request for the homepage banner's configuration from GitHub sometimes fails on Internet Explorer 11. The error report doesn't have many details, besides `Network request failed`, so there isn't much to go off of. Potentially, this could mean some users don't see the homepage banner on page load sometimes. 

I can't seem to replicate this using an emulator - the homepage banner always renders for me - but my best guess of what happening is that it fails because the request is cross-domain, from va.gov to github.com. A fix for this is difficult to say - we load the banner configuration off of GitHub from the browser so that any potential deployment issues (Drupal issues or otherwise) are non-blocking for publishing the banner, and to create something closer to real-time updates.

Ideally, this banner configuration would come from Drupal, but Drupal isn't equipped to publish a banner to the homepage yet. Another potential fix is that we could create an endpoint on the API that provides the data for the homepage banner. 

### Acceptance criteria
- [ ] Monitoring issue no longer seen by users on IE11

**Comment by ncksllvn** [comment]
Context from CMS team about why publishing a homepage banner via Drupal is a difficult tech task - https://dsva.slack.com/archives/CDHBKAL9W/p1583182202120300

**Comment by ncksllvn** [comment]
I think we saw this issue from a team member today, https://dsva.slack.com/archives/C52CL1PKQ/p1585834852389600.

@MickinSahni I think we should try grabbing this really soon. The issue description really just describes the problem, but a fix could be -

1. Create an API route for getting the homepage banner's content
    - That API route should load the config directly out of vagov-content with a Redis cache
1. Update the FE to use this new API route

**Comment by MickinSahni** [comment]
2020-04-08 PW Sprint 19 Planning
- Not sure if network related or time-out issue
- Suspecting cross-domain configs/requests
- Note: works on page reload

**Comment by MickinSahni** [comment]
2020-04-09 PW Standup
- Merged in a fix
  - Since the homepage banner isn't in Drupal, it's not a long-term solution (until it's supported by Drupal)

**Comment by ncksllvn** [comment]
Fix just went live that removes the dynamic behavior in exchange for a static template on the template. There are drawbacks to this, but this is a blanket solution since we can't narrow down when this happens and we can't create a good dynamic solution without a Drupal implementation of the homepage banner.

**Comment by ncksllvn** [comment]
Also - this issue description proposed using the API for loading the homepage banner, but I don't think that we're at the right time to do that without having Drupal supporting the data. It would be a weird idea to have the GitHub file passed to the API to the browser.
