### ISSUE TITLE
GIDS: Archive Tab is inaccessible in production

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#6786]
When attempting to view the archives page in production, the user receives an error message.

1. Log in to GIDS
2. Click Archives tab

Historic GIDS versions should be displayed, but the user receives the following error message
![image001.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/3bf62d73-404c-4424-8697-d83a9c569ae1)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/608

**Comment by zurbergram** [comment]
This now works in production after changes in https://github.com/department-of-veterans-affairs/gibct-data-service/pull/601 were deployed to production

**Comment by zurbergram** [comment]
Issue was with a preview version whose user was deleted, after deploying https://github.com/department-of-veterans-affairs/gibct-data-service/pull/601 to production issue was resolved.

https://github.com/department-of-veterans-affairs/gibct-data-service/pull/608 will prevent this issue from occurring again

**Comment by zurbergram** [comment]
```
vs = Version.all.select{|v| v.user.nil?}

vs.count
# => 2

[#<Version:0x000000000661b6a0
  id: 192,
  user_id: 13,
  number: 127,
  production: false,
  created_at: Thu, 08 Feb 2018 00:54:23 UTC +00:00,
  updated_at: Thu, 08 Feb 2018 00:54:23 UTC +00:00,
  uuid: "31e5545d-b5ce-4f4b-bb2c-0248d728e2b8",
  completed_at: nil>,
 #<Version:0x000000000661ade0
  id: 199,
  user_id: 13,
  number: 133,
  production: false,
  created_at: Fri, 23 Feb 2018 03:35:06 UTC +00:00,
  updated_at: Fri, 23 Feb 2018 03:35:06 UTC +00:00,
  uuid: "8fc20ede-0426-47c9-ae84-a4addc3fa7d9",
  completed_at: nil>]
```

Both versions from Feb 2018.  Both reference user_id of 13.  There is currently no user with an ID of 13.
