### ISSUE TITLE
AWS access for Adam King

### ISSUE THREAD

**Issue by AdamKing0126** [department-of-veterans-affairs/va.gov-team#67871]
### COR Name

Eunice Garcia

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Adam King

### Your Email

adam.king@oddball.io

### Team, Role, and Company of the target individual

VA IIR, Senior Software Developer, Oddball

### Product Manager (PM) name and email

Peter Egan peter.egan@oddball.io

### Product Owner (PO) name and email

Jeff Barnes jeffrey.barnes4@va.gov

### Desired AWS Access

Could I please have read/write access to the parameter store path /dsva-vagov/performance_dashboard and to S3 to read uploaded files from the dsva-vetsgov-scorecard-dev, dsva-vetsgov-scorecard-staging, and dsva-vetsgov-scorecard-prod buckets. Thank you!

### Access Expiration

Ongoing

### E-QIP Transmittal Confirmation
![Screenshot 2023-10-18 at 9 30 22 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/7659922/e5e23dc2-077b-4b74-a46a-609d5bbbff7b)

### Additional Notes

I need this access because I am a new software engineer working on the Platform Dashboard project and need to be able to obtain the project secrets and data.

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by JonathanKamensDVA** [comment]
Approved for handling the same way as Kyle's access (#66736).

**Comment by ph-One** [comment]
Closing. User has been added to AWS and contacted with follow-on details
