### ISSUE TITLE
Research: Discovery convo (Joshua Will)

### ISSUE THREAD

**Issue by djones2113** [department-of-veterans-affairs/va.gov-team#67891]
What outcome(s) do we want to see?
Learn what has been done, known outcomes from what was done and any additional information that will help determine our next steps, scope and/or outcomes.

To Do Tasks
- [x] Setup call with Joshua
- [x] Setup discussion guides
- [x] Use brief/Slack mining to gather context (where applicable) for the conversation
- [x] Document learnings
- [x] Update ticket with link to documentation created
- [x] Update research backlog with learnings (as needed)
- [x] Prioritize learnings to enable next set of tasks

**Comment by djones2113** [comment]
There are two action items that came out of this first call with Josh:

1. Follow up with Josh to see if there is an overlap with our work in the automation space. I assume that this is something we can bring up during our weekly with Josh @buddhima-coforma?
2.  Reach out to Daniel Hoover who works with OBI and mail automation side of the team. I'm not sure when it makes most sense to do this, but I assume this is a next step for @christiejibaraki? I can help support if needed/relevant

**Comment by christiejibaraki** [comment]
I don't think I would/should reach out to the mail automation team. I would defer to Karla and the octo folks on how we should interact with mas. What was the context for reaching out to Daniel Hoover?

**Comment by djones2113** [comment]
That makes sense, and it sounds like this is another question we could ask Karla/Josh in our weekly sync tomorrow. Reaching out to Daniel Hoover was Josh's suggestion in response to finding out what overlap there may be with our work in the automation space.
