### ISSUE TITLE
Daily Recurring Qualitative Data Request

### ISSUE THREAD

**Issue by AnneCostello** [department-of-veterans-affairs/va.gov-team#67893]
### Data Type Requested

Support

### Date Range Start

11-03-2023

### Date Range End

11-03-2025

### Product Name(s)

MHV Secure Messaging on VA.gov

### Product Description

MHV Secure Messaging on VA.gov is a messaging tool that Veterans use to communicate with their healthcare providers.

### Survey URL(s), key term(s), case category or type

Secure Messaging on VA.gov: va.gov/my-health/secure-messages

We would like any issues that pertain to the new experience on VA.gov, **not** issues with the existing (myhealth.va.gov/secure-messaging)

*Could we please receive these daily?  

### File Delivery Format

All in one file, on one tab

### Word Cloud

Yes

### VA Email Address(es)

anne.costello@va.gov, jane.carnock@va.gov

### Add Assignee and Labels

If not already done so, please ensure @newworld2616 is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by newworld2616** [comment]
Hi @AnneCostello, we can only pull data on or before 1-/18/2023 data's on Medallia. Sorry for the inconvenience.

**Comment by AnneCostello** [comment]
I'm not sure I understand. Can you clarify?

**Comment by newworld2616** [comment]
The requested date is 
Date Range Start
11-03-2023

Date Range End
11-03-2025
Medallia data is available on or any date before 1-/18/2023.

This form is for Intercept and Feedback survey from VA.gov.

**Comment by newworld2616** [comment]
I will discuss this with my manager, and I will try to see if I can pull those data from different source which supports Tier II/Tier III data and MyVA411 data.

**Comment by AnneCostello** [comment]
<img width="955" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/116298030/a11506d8-a0ed-4efe-9ce5-d5cc5617f8af">
I uploaded a screenshot of the top of the form.  Thanks for checking with your manager! :)

**Comment by newworld2616** [comment]
Sure, make sense. Thank you for sharing the screenshot. I will be in touch.

**Comment by newworld2616** [comment]
Sorry one more thing could you give me the date that is before 10/18/2023 then once we find out the solution how to share the requested data for MyVA411 then I will share it everyday.

**Comment by newworld2616** [comment]
Hi @AnneCostello, we have created the report, I will start sending the report daily starting: 11-03-2023 / 11-03-2025. Let me know if you have any questions.

**Comment by AnneCostello** [comment]
Sorry I didn't see your previous comment until now. Is it still needed or are we all set?

**Comment by newworld2616** [comment]
I don't think so, we are good.

**Comment by AnneCostello** [comment]
Hello, Sarifa!
I just want to clarify that we will be receiving the My411 and Tier II and Tier III data, correct? We have so many different data sources set up I want to make sure we captured them all. Thanks for all your help with this!

cc: @janieTC-USDS

**Comment by newworld2616** [comment]
I believe, I did share that data with you for MYVA411 Tier II and Tier III data.

**Comment by AnneCostello** [comment]
Thanks for all your help with this, Sarifa! There are so many data sources, I feel like I may lose track.

Can you help with access to Vsignals data?

**Comment by newworld2616** [comment]
Where does Vsignal data would be available, never heard of it before?

**Comment by AnneCostello** [comment]
My understanding is that it is from surveys that are emailed to Veterans after appointments. In a Slack message with Anita on 10/18 she stated that your team works with VSignals data, but I haven't received a response about how we request that data.

**Comment by newworld2616** [comment]
I will discuss with her and get back to you.

**Comment by newworld2616** [comment]
Hey @AnneCostello, I spoke with the team, VSignals data is Medallia data, it's the other name for Medallia.

**Comment by AnneCostello** [comment]
Seriously? Oh my goodness. I read that VSignals data is collected from emails sent to Veterans post appointment. Can you confirm or correct this?

Also - is the data marked by its source? I am curious if responses are different based on if a Veteran is asked for feedback (Intercept) versus those who volunteer it with the Feedback button.

**Comment by newworld2616** [comment]
Hi @AnneCostello, our data  is separate, and we only have access to Digital ([VA.gov](http://va.gov/)) collected data. You would need to reach out to VEO, they might help you for VSignals data.

**Comment by newworld2616** [comment]
Good morning, MYVA411 has no values for now. I will continuously monitor, once I start seeing the data. The data share will be daily.

**Comment by newworld2616** [comment]
Good morning, I have shared the MYVA411 data.

**Comment by newworld2616** [comment]
Hi @AnneCostello, no data available for MYVA411...

**Comment by newworld2616** [comment]
HI! I have shared the data.

**Comment by janieTC-USDS** [comment]
Hi Sarifa,

Morning! I see the MYVA411 report data. Is there also new data for the Medallia data we've been getting daily?

Thank you!
Janie

From: Sarifa Khalilulah ***@***.***>
Sent: Thursday, November 9, 2023 8:19 AM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Carnock, Janie Tankard ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Qualitative Data Request (Issue #67893)


HI! I have shared the data.

-

**Comment by newworld2616** [comment]
Good morning, I have shared the data for Medallia.

**Comment by janieTC-USDS** [comment]
Great, yes I see it now. Thank you!

From: Sarifa Khalilulah ***@***.***>
Sent: Thursday, November 9, 2023 10:08 AM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Carnock, Janie Tankard ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Qualitative Data Request (Issue #67893)


Good morning, I have shared the data for Medallia.

-

**Comment by newworld2616** [comment]
Of course!

**Comment by newworld2616** [comment]
Hi, I have shared MYVA411 data.

**Comment by starlow00** [comment]
Awaiting information.

**Comment by AnneCostello** [comment]
Hi Sarifa!
Thank you a million times over for your daily data emails. They have been a tremendous help! 

Could you please add these two ladies to the daily emails as well?
lichelle.bain@va.gov
melissa.ashton@va.gov

**Comment by newworld2616** [comment]
Hi @AnneCostello. No problem. Sure, I will add them as well. Thank you!

**Comment by AnneCostello** [comment]
Thanks! You're the best!

From: Sarifa Khalilulah ***@***.***>
Sent: Tuesday, December 19, 2023 1:21 PM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Costello, Anne M. (by Light Professional It Services, Llc) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Qualitative Data Request (Issue #67893)


Hi @AnneCostello<https://github.com/AnneCostello>. No problem. Sure, I will add them as well. Thank you!

-

**Comment by newworld2616** [comment]
Thank you!

**Comment by newworld2616** [comment]
Closing this ticket, since we already have one ticket for secure messaging. This ticket is duplicate.
