### ISSUE TITLE
CH 31 | Correct Title on MyVA Tile

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#67904]
## Issue Description
_When the tile for a draft application appears within a Veteran's MyVA profile, the title for the in-progress Chapter 31 form contains redundant wording. Original work to add the tile is https://github.com/department-of-veterans-affairs/va.gov-team/issues/64603._

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUpOQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--85a57ec452f3f9e3a6ce0159f1d42014ca9e0879/image.png)

---
## Tasks
- [ ] Correct the tile title to read: Application for Veteran Readiness and Employment Benefits

## Acceptance Criteria
- [ ] The tile within the "benefit application drafts" section in MyVA for an in-progress Chapter 31 claim reads: Application for Veteran Readiness and Employment Benefits 
---

**Comment by zack** [comment]
oops!
