### ISSUE TITLE
Spike: options for pre-filling forms

### ISSUE THREAD

**Issue by buddhima-coforma** [department-of-veterans-affairs/va.gov-team#67910]
### Description
As a veteran, when I arrive at form 526, I want it to be pre-filled with my information that the VA already has, so that I don't have to re-enter information 

### Criteria
- Explore potential options of using existing technology (ie: saving form progress feature?)
- Outline potential tech that would have to be developed and would work with VA services/infrastructure (ie: deep-linking?)

### DoD
- Know enough to be able to execute later
- Document options. Outline any nuances, risks etc.
- Demo post-standup or async -> get feedback from necessary parties -> generate follow up tasks if any -> close ticket

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-proactive-64e7650c29bb1113de04a02a/issues/department-of-veterans-affairs/va.gov-team/67910?planning-poker) with Zenhub @danlim715 @mjknight50 @wayne-weibel

**Comment by jenniferbertsch** [comment]
Hi - I see this one is listed in Sprint 6 on the Mural list.  Just want to confirm we are addressing it in this sprint?  Do we think pre-fill is an option for the MVP?  Or is this just research to understand the level of effort?  Thanks.

**Comment by buddhima-coforma** [comment]
This is just technical research to understand options and level of effort. Separate from deciding if we do it or not.

**Comment by mjknight50** [comment]
@wayne-weibel Can you please run with this one?  This is for our current sprint and needs to be wrapped up by November 7th.  Please provide a simple demo of a pre-filled form that we can show to stakeholders.
