### ISSUE TITLE
Bug - non-VA.gov USiP clients aren't redirected back to original app if ToU not accepted

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#67930]
For USiP clients that technically don't have Terms of Use enabled, the va.gov after-auth enforcement still blocks `/user` route from being called. This results in these clients being logged out before being redirected back to the original application, even though they should not have to deal with Terms of Use

**Comment by asg5704** [comment]
I believe this item is completed by https://github.com/department-of-veterans-affairs/vets-website/pull/26282

Can we close @bosawt?
