### ISSUE TITLE
526 EZ Strategy to Handle Downstream Outages

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#67938]
Currently the 526 EZ application relies on a number of down stream systems that may go down for various reasons including planned maintenance or unplanned problems. As a joint team (DBEX team 1, team 2 and Octo) we need to determine a strategy that can help reduce the impact to the Veteran. These strategies could include:

1. How to improve the experience when systems are down
2. How to reduce the time systems are down for planned maintenance
3. How to reduce impact through monitoring playbooks for when systems are down unexpectedly 

Next steps:
1. Identify all downstream systems that are required for successful submission
2. Gather data around current impact to Veteran, including historically known down time
3. Identify proposals for improving each and share broadly for feedback

Acceptance criteria:
1. Once feedback received, create a formal proposal and ticket work

**Comment by austinjprice** [comment]
Place holder for when fixable errors have been addressed how do we improve overall Veteran Experience for errors that are out of our control. E.g. downstream system are out. This would need discovery to identify which errors are causing the most pain and improvement to how we message to the Veteran.

**Comment by tblackwe** [comment]
this effort continues to evolve, well beyond scope of this ticket. closing in favor of a dozen other tickets.
