### ISSUE TITLE
Intake - Update Proofing screens with Login.gov styled prototypes

### ISSUE THREAD

**Issue by porta-antiporta** [department-of-veterans-affairs/va.gov-team#67952]
# Use case
As a Veteran traversing from Login.gov to VA, I want the experience to be as seamless as possible so that I am not confused when going from Login.gov to VA.

# Context

We are going to revisit the theme from VA.gov to Login.gov.

# Acceptance criteria
- [x] All proofing agent screens updated with Login.gov theme
- [x] Responsive
- [x] Able to navigate back and forth between Intake screens

**Comment by skirkman16** [comment]
@SophiaPhilipMO

**Comment by skirkman16** [comment]
https://www.figma.com/file/PfrWKmxiQ5RjChwx6I18QE/IPP-Prototypes?type=design&node-id=942%3A7835&mode=design&t=YHvYpnDeiOR0nKRc-1
Page 10/25 - Proofing Screens

**Comment by SophiaPhilipMO** [comment]
@CarlDickerson
