### ISSUE TITLE
BUG - CC API appears to return an error we've never seen before

### ISSUE THREAD

**Issue by saneshark** [department-of-veterans-affairs/va.gov-team#6795]
## What happened?
We received the following upstream error from CC API:

For patient ICN <FILTERED>, geocoding information (updated 2019-11-13T23:30:06Z) is out of date against residential address (updated 2020-03-11T20:37:06Z)

More details are available here: http://sentry.vfs.va.gov/vets-gov/platform-api-production/issues/106982/?query=vaos

## Specs:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)
- Test User _(if applicable)_:

## Steps to Reproduce
- URL:
- Test User _(if applicable)_:

## Desired behavior
The result should have been successful.

## Acceptance Criteria
- [ ] Ideally we need the result to be successful. Its not clear yet why this happens or what type of messaging we can communicate to the user when this error is encountered.

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by saneshark** [comment]
Per conversation on slack @davem-va said:

> Yes this means that the veteran address changed and VHA has not yet updated their geocoding. Lauren's aware of this corner case. Vets 360 team was working with E&E and PSSG teams to close this gap but didn't see it come to closure
>PSSG updates geocodes 2x daily

Trying to determine if there is a vet-360 ticket already tracking this and can just link to that and follow-up when that work is complete. My understanding is that this effort might be on hold due to covid-19 changes -- moving this ticket to backlog for now.

**Comment by saneshark** [comment]
I think we need to get a better handle on this error before July 6 when CC is re-enabled.

**Comment by saneshark** [comment]
I actually haven't seen this error in a very long, but thats also probably because CC is disabled. VAMF doesn't have logging going back far enough to be able to help triage issue unfortunatley. It's going to have to be something we monitor once we've enabled feature toggles again I think.

**Comment by lenaecb** [comment]
Pulling in to Sprint 24 to evaluate if this is/has happened
