### ISSUE TITLE
Pension | Foreign Military Base Address Discrepancy

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#67959]
## Issue Description
_Users are incorrectly entering addresses associated with military bases overseas where they select the foreign address checkbox yet enter a zip code that does not match the acceptable range of foreign base postal codes. These discrepancies can cause delays in claim processing._

---
## Tasks
- [ ] Update front-end error messaging based on this [Sketch file](https://www.sketch.com/s/870d13d5-a465-48a3-acc2-32682ba8f780)
- [ ] Add postal code validation. If the foreign address box is selected, the postal code entered must coincide with a APO/FPO/DPO postal code:
```
if (cityname is one of APO/FPO/DPO OR mlty_postal_type_cd is one of AA/AP/AE )
{    if mlty_postal_type_cd is AA, first three characters of zipCode should be 340 else reject transaction if mlty_postal_type_cd is AE, zipCode range should be (090-099) else reject transaction if mlty_postal_type_cd is AP, zipCode range should be (962-966) else reject transaction  }

```

Requirements update: If the Veteran has selected `My mailing address is outside the United States on a U.S. military base` then all 3 zip code validations should be applied. 

## Acceptance Criteria
- [ ] Error messaging appears to user
- [ ] Selecting the foreign address checkbox and entering in a non-APO/DPO/FPO postal code displays an error to the user and prevents submission
---

**Comment by aplatt-coforma** [comment]
Assigning this to myself to retest staging with the relaunched form.

**Comment by gmaciolek** [comment]
Error message text:
This postal code is within the United States. If your mailing address is within the United States, uncheck the checkbox "I receive mail outside of the United States or on a U.S. Military base." If your mailing address is an AFO/FPO/DPO address, enter the postal code for the military base.

Screenshot of what error message should look like:
<img width="554" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1dZQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9ea5228e17f4e1ebd08b9aba62e541149224c6fa/Screenshot%202024-02-28%20at%2010.31.40%20AM.png" alt="Screenshot 2024-02-28 at 10.31.40 AM.png" />

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/67959?planning-poker) with Zenhub @danlim715 @mjknight50 @TaiWilkin @ToddWebDev @wayne-weibel @scottsdevelopment
