### ISSUE TITLE
Update Support Best Practices Templates

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#67973]
## Description 
This ticket will document the work that was done to update templates in this document: https://vfs.atlassian.net/wiki/spaces/PTST/pages/2426241154/Support+Best+Practices

## Definition of Done
All steps are completed below.

---

## Tasks 

- [x] Add the [x] templates to the Support Best Practices page
- [x] Add steps to find templates in the doc

--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by bdech** [comment]
Access Request templates have been added to Support Best Practices Doc. 

Section can be found under "Providing a Solution for a Ticket/Solution Types", labeled "Other Response Templates"

https://vfs.atlassian.net/wiki/spaces/PTST/pages/2426241154/Support+Best+Practices#Other-Response-Templates[hardBreak]

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmxVQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6a18a26a53d4478595af5b54ae794bb870dfb3ea/image.png)
