### ISSUE TITLE
Add link to the MHV landing page to order CPAP supplies

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#67985]
## User story

As a user on the MHV landing page, I want to be able to access the CPAP supply ordering tool, so that I can easily order CPAP supplies without needing to message my health care provide.

Follows [research spike](https://github.com/department-of-veterans-affairs/va.gov-team/issues/67038). 

URL to add: www.va.gov/health-care/order-cpap-supplies/

## Tasks
- [x] Design mock-up with link added @fmccaf1 (and whoever else wants to join me in Sketch)
- [ ] [Pull request](https://github.com/department-of-veterans-affairs/vets-website/pull/26370) with requested changes @radavis

**Comment by fmccaf1** [comment]
This one is a little tricky (not so simple as just adding a link) because we need to make some design choices here...[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0ZwQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--449f4c0c1ac812e49ddf6a15ff94253f0786cd1b/Screenshot%202023-10-24%20at%203.38.59%20PM.png)


So we need to solve some issues and get a mock-up to help with implementation.

**Comment by fmccaf1** [comment]
Here's what I'm thinking... expand the final 2 boxes (seems to me they must remain the same height) and make space for the additional link. When I did that, I created link text, "Order CPAP supplies," and realized that then all three links would read "Order ..." so changed up some more text. Curious to hear others' thoughts. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGRxQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a0e5da14a52f7d872f04fdee5a4632690d9a6c45/VA-MHV-Home-Oct-2023.png)

**Comment by wesrowe** [comment]
@fmccaf1, I like your changes. Does the design system allow nouns as link text? I have a little hunch that the old links were complete sentences for a reason. But I'm not an expert on the DS.

Nice idea to reduce the box header down to a single line on desktop.

**Comment by radavis** [comment]
Screenshot of change in local development:

![Screenshot 2023-10-25 at 10-52-39 MyHealtheVet on VA gov Veterans Affairs](https://github.com/department-of-veterans-affairs/va.gov-team/assets/1299034/85ff5840-c7bb-4ad4-bd64-8f823076fc9e)

**Comment by fmccaf1** [comment]
Great point @wesrowe. Teammates in our channel suggested the same thing, that we probably need that verb "order" in the text of these links.

Here's a redesign with that in consideration: 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2h2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9edbfa3ef84ecd46c541cebc0751b452297c8a95/VA-MHV-Home-Oct-2023.png)
