### ISSUE TITLE
[Analytics] VEO July Metrics Request

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#680]
## nUser Story
As a VEO user, I need monthly analytics for Education, Burials, and Claims so I can report on this data to internal stakeholders.

## Goal
Provide monthly data for June in visualization
Provide links to Jack Yang within Google Analytics
Acceptance Criteria
  Monthly Data
  Visualize Data
## Definition of Done
  Attached to a Milestone (when will this be completed?)
  Attached to an Epic (what body of work is this a part of?)
  Labeled with Team (product support, analytics-insights, operations, triage, tools-improvements)
  Labeled with Practice Area (backend, frontend, devops, design, research, product, ia, qa, analytics, call center, research, accessibility, content)
  Labeled with Type (bug, request, discovery, documentation, etc.)

**Comment by nedierecel** [comment]
@amycesal I updated the metrics on the Vets.gov/VA Metrics Google sheet through 8/1/2019.

@joanneesteban For your visibility, as we pull longer date ranges for VEO or other needs, we will hit Google Analytics' sampling within the user interface. This is important to note for our Blue Sky dashboard approach. There are a few options for solving sampling:

1. Recommended: We can enable BigQuery as the data warehouse. This will store up to 13-months of historical data or 10MM hits.
2. Short-Term or for as-needed reports: We can use a feature called Custom Tables, however, this only pulls data for 30 days prior.

Resources:
-  [Backfilling GA360 Data into BigQuery](https://support.google.com/analytics/answer/3416092?hl=en)
- [Custom Tables](https://support.google.com/analytics/answer/2774517?hl=en)

**Comment by joanneesteban** [comment]
@amycesal added metric: 

CSAT for the last 6 months (02/01/2019 - 07/31/2019): **57.1**

**Comment by joanneesteban** [comment]
@amycesal 

[Foresee Satisfaction Questionaire 8.1.19.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3486737/Foresee.Satisfaction.Questionaire.8.1.19.xlsx)

**Comment by joanneesteban** [comment]
With added Foresee data (but needs design fix).

[Metrics_08.01.19.pptx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3486742/Metrics_08.01.19.pptx)

**Comment by nedierecel** [comment]
@amycesal @joanneesteban For the new metrics that were requested, we can pull logins but will have a gap on how we are recording account creation data within Google Analytics:

1. IDme - Prior to January 2019, new account registrations were recorded with successful logins. This was documented in this ticket within the [vets.gov repo](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/16298). It may be better to pull these metrics from ID.me reports. 

2. MHV and DSLogon - From my visibility, there are a few areas within the Modernized tools that a user can create an account, but I believe this mostly happens outside of the Modernized tools. For this reason, these metrics are not included here.

**Comment by joanneesteban** [comment]
@amycesal These are Nedie's additions:

Unique Logins (DSLogon, IDme, MHV) - Pre vs. Post-Relaunch | 2515506 | 9,612,359 | 282.12%
-- | -- | -- | --
Unique ID.me Register Success | Not tracked separately pre-relaunch | 281,154 |  
  |   |   |  
Metrics for Modernized Tools | June 2019 | July 2019 | Percentage Increase
Unique Logins (DSLogon, IDme, MHV) | 1,379,033 | 1,544,706 | 12.01%

**Comment by amycesal** [comment]
<img width="571" alt="Screen Shot 2019-08-09 at 12 55 12 PM" src="https://user-images.githubusercontent.com/1656046/62798872-f5a2c980-baa4-11e9-94d0-7b6b7adc0ce8.png">
Is this accurate?

**Comment by amycesal** [comment]
[Metrics_08.01.19.pptx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3487536/Metrics_08.01.19.pptx)

^ Updated PPT

**Comment by joanneesteban** [comment]
Metrics sent to Lacey on 8/9/19. Thank you to everyone for your help on this delivery.

[Metrics_08.01.19 (2).pptx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3492749/Metrics_08.01.19.2.pptx)
