### ISSUE TITLE
VRE | Improper use of fieldset and duplicative <legend>

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#68021]
## Issue Description
_CAIA feedback in #64361._

### Staging or Production Link
- [Staging Link](https://staging.va.gov/careers-employment/vocational-rehabilitation/apply-vre-form-28-1900/start)

### Prototype Link
- [Mural User Flows](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1684161597392/5c1f8869cf5d03b792c8b82cf19b39dc26c486c2?sender=u0e8ac1d6d7681bb7e1b80558)

### Test Users
- vets.gov.user+24@gmail.com
- [staging test user repository](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv)

### Details
On [step 2 of the form](https://staging.va.gov/careers-employment/vocational-rehabilitation/apply-vre-form-28-1900/additional-information), the "What's your level of education?" and "Are you moving in the next 30 days?" fields are contained within a `<fieldset>` with the `<legend>` "Additional information":
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/135633989/2a25a5f7-e0bf-43b2-9f34-6290d4ab58fb)

There are two issues with this:
1. These fields don't need to be within a `<fieldset>`. There's only 1 "Additional information" page on this form, and these two questions aren't related to each other, so this extra layer of grouping is superfluous and leads to the second issue:
2. `<legend>Additional Information</legend>` is duplicative of the "Step 2 of 4: Additional Information" heading. A screen reader user would hear something like this: `Heading level 2, Step 2 of 4: Additional information. ... Additional information, group.` This adds more for the SR user to have to parse through unnecessarily.
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/135633989/c93ea38d-5d16-4887-8d55-30978ea69a8d)

### Reproduction steps
1. [Go to the form](https://staging.va.gov/careers-employment/vocational-rehabilitation/apply-vre-form-28-1900/start)
2. Click "Apply for Veteran Readiness and Employment with VA Form 28-19003" and sign in
4. Fill out the form until you get to [this page](https://staging.va.gov/careers-employment/vocational-rehabilitation/apply-vre-form-28-1900/additional-information)
5. Inspect the "Additional Information" `<legend>` above the "What's your level of education?" field. You can also use a screen reader like VoiceOver or NVDA to hear what it sounds like.

### References, articles, or WCAG support
[When to use a fieldset and legend](https://accessibility.blog.gov.uk/2016/07/22/using-the-fieldset-and-legend-elements/#:~:text=When%20to%20use%20a%20fieldset%20and%20legend), from gov.uk

---
## Tasks
- [ ] Take the "education" and "moving" fields out of their grouping `<fieldset>`; remove the `<legend>`. The page will look like this, in pseudocode:

```
<heading>
Step 2 of 4: Additional information
</heading>
....

<select component>
What's your level of education?
..... 
</select>

<radio button component>
Are you moving in the next 30 days?
..... 
</radio>
```

## Acceptance Criteria
- [ ] "education" and "moving" fields removed from their grouping `<fieldset>`
- [ ] `<legend>`removed
---

**Comment by Midge-dev** [comment]
Commented here https://github.com/department-of-veterans-affairs/va.gov-team/issues/64361

**Comment by steele-lm** [comment]
Closing: This issue has been fixed because we've separated both questions into different pages and steps in the updated designs, and it would no longer wrongly group both questions into the same <fieldset> value
