### ISSUE TITLE
CF: Update CF content on Search Results page

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#6803]
As a Veteran searching for institutions using the GI Bill Comparison Tool, I need to know what types of caution flags the institutions I'm considering have so that I can make the best decision about my education choices.

## Assumptions: 
1. There will be a follow on story to this to update final approved content. 
2. This story should be reviewed by a member of the UX team prior to completion for feedback.
3. This story is listed as blocked by #6854 but it can be reworked later to utilize the updated data.
4. This story is to be completed behind a production flag so it is visible on the staging environment.

## Acceptance Criteria: 
1. When search results are displayed for schools that contain caution flags that are NOT for school closings: 
a. The caution flag is displayed with a header that says either "This school has a cautionary warning" or "This school has cautionary warnings". 
b. The caution flag includes brief subtext below the header that describes the caution flag in more detail.
c. If a school has multiple caution flags then subtext bullets are included below that describe each of the caution flags. 
d. If there are multiple caution flags, they are displayed in alphabetical order based on first letter of the flag subtext that is displayed.
![Screen Shot 2020-03-12 at 10.09.58 AM.png](https://images.zenhubusercontent.com/5b645f6fe2255460d8f0b032/4168de89-b56f-4ebe-97a8-b0ad83a3c32c)
2.  When search results are displayed institutions with a school closing:
a. The caution flag is displayed with a header that states: "A campus is closing soon"
b. The caution flag includes a brief subtext below the header that describes the caution flag in more detail: "A campus at this school will be closing soon"
3. When an institution has both a school closing and caution flags both are displayed in separate alerts with the school closing above the caution flag: 
![Screen Shot 2020-03-12 at 4 57 34 PM](https://user-images.githubusercontent.com/41790951/76566188-9c5ba800-6482-11ea-9716-0359984bc6c0.png)

## Supporting Artifacts
1. Prototype: https://bahdigital.invisionapp.com/share/N5IAD8MHTC9 *updated 3/16
2. Content: [https://app.zenhub.com/files/133843125/5aa8c713-13e2-46c7-8825-527928af4349/download](https://app.zenhub.com/files/133843125/5aa8c713-13e2-46c7-8825-527928af4349/download)
a. Note that there is a caution flag noting that there is an upcoming closure ("upcoming campus closure") that is NOT a school closing. So, in this scenario there may be a caution flag for upcoming closure WITHOUT a school closing.

**Comment by zurbergram** [comment]
Caution flag and reason are set at
- https://github.com/department-of-veterans-affairs/gibct-data-service/blob/master/app/models/institution_builder.rb#L172
- https://github.com/department-of-veterans-affairs/gibct-data-service/blob/master/app/models/institution_builder.rb#L263
- https://github.com/department-of-veterans-affairs/gibct-data-service/blob/master/app/models/institution_builder.rb#L352
- https://github.com/department-of-veterans-affairs/gibct-data-service/blob/master/app/models/institution_builder.rb#L378
- https://github.com/department-of-veterans-affairs/gibct-data-service/blob/master/app/models/institution_builder.rb#L398

Used at
- https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/gi/components/vet-tec/VetTecProgramSearchResult.jsx#L63
- https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/gi/components/search/SearchResult.jsx#L61

<img width="1648" alt="Screen Shot 2020-03-13 at 10 53 22 AM" src="https://user-images.githubusercontent.com/1094999/76632464-a977a600-6519-11ea-97c5-328d69a08705.png">
[Institutions_profile.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4330158/Institutions_profile.xlsx)

**Comment by delli-gatti-michael** [comment]
PR:
https://github.com/department-of-veterans-affairs/vets-website/pull/11919

**Comment by delli-gatti-michael** [comment]
Local Testing complete

**Comment by delli-gatti-michael** [comment]
Changes are now in Staging. Awaiting UI/UX team review

**Comment by delli-gatti-michael** [comment]
![Screen Shot 2020-03-19 at 9.08.57 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/3bf59419-1d84-4803-a1c0-fb7b9d6a364c)

**Comment by delli-gatti-michael** [comment]
TestRail Test Case:
https://dsvavsp.testrail.io/index.php?/cases/view/389

**Comment by delli-gatti-michael** [comment]
Now present in staging. Closing this issue
