### ISSUE TITLE
Content request to support VA health chat on VAMC pages from Sitewide-Facilities 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#68030]
## About your team

- Team name: Sitewide-Facilities
  - OCTO-DE product owner: Michelle Middaugh
  - Product manager: Jane Xiong
 
### Describe what you need in a few sentences:
Content support is needed for 
- link labels on VAMC pages which will direct Veterans to VA health chat to complete one or more tasks. VA health chat is not rolled out nationwide and all core services are not available where VA health chat is available, we need labels which will support Veteran understanding for how it can be used at a specific facility. The content will be added by field staff with clear guidance from VHA DM
- possible program page which can provide necessary context and details in facilities with multiple core services available

### Which are you doing?
- [ ] **Launching a new** page, tool, form, or app
- [x] **Making changes** to an existing page, tool, form, or app

### Types of Support
What areas does your team need support in? Check all that apply.
#### Content
- [x ] Collaboration on content written by your team’s dedicated content writer (VA health chat team may have someone who can provide content for review by CAIA)
- [x ] Collaboration on content if your team does not have a dedicated content writer
#### Accessibility
- [ ] Accessibility review of wireframes and/or prototypes
- [ ] Accessibility issue (general request)
- [ ] Accessibility PDF review request
- [ ] Accessibility user research support ([submit a separate, additional request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name))
- [ ] DST component or pattern 
- [ ] Something else 
#### IA
- [ ] User Flows
- [ ] Page placement
- [ ] URLs
- [ ] Breadcrumbs and Left Nav placement
- [ ] Redirects
#### Multilingual content
- [ ] Translating content
 
## Timeframe
_We guide and work alongside teams across nearly every OCTO digital product. We also work with partners across VA to lead content migration and manage all unauthenticated content on VA.gov. And we're always working to expand the VA.gov content style guide and our IA and accessibility documentation. We need to prioritize all intake requests based on our overall workload and VA and OCTO priorities._

_Tell us about your product's timeline. And we'll work with you to meet timeline needs as best we can._

### Have you worked with CAIA before? 
  - [x] Yes
  - [ ] No

### What's your team’s next step and its timing?

- **Our next step is** ....
- **Provide date if available**: xx/xx/xxxx

#### Timing for your next step: 
  - [ ] Next week
  - [ ] This month
  - [ ] Next month
  - [ ] This quarter
  - [ ] Next quarter
  - [ ] 6 months
  - [ ] 1 year

### Is this timing related to a specific event or Congressionally mandated deadline?
  - [ ] Yes
  - [ ] No

### If you're conducting research, when is that starting? 
**Provide date if available:** xx/xx/xxxx
  - [ ] Next week
  - [ ] This month
  - [ ] Next month
  - [ ] This quarter
  - [x ] Next quarter - possibly
  - [ ] 6 months
  - [ ] 1 year

### Will you release this new product incrementally (for example, release to 25% of users to start)? 
  - [ ] Yes 
  - [x] No
 
**Note**: _If you checked yes, we’ll reach out to discuss details about the content in the react widget (we use these widgets to display entry points for new products to a certain percentage of users who visit our static pages)._

  
### When do you expect to launch your product to 100% of users?
  
*Please provide an estimated date so our team can create other relevant tickets.*
- **We expect to launch our product to 100% of users on:** xx/xx/xxxx
  
### Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [x] No

### If no ...
- Skip to the _supporting artifacts_ section, below.
 
#### Please provide the link to your Collaboration Cycle ticket: 
- **Ticket (number)**: 
- **Collab. Cycle Ticket Opened (date)**: xx/xx/xxxx
 
#### Please check all of the phases in the Collaboration Cycle you have completed: 
- [ ] Design Intent
- [ ] Midpoint Review
- [ ] Staging
 
##### Design Intent
- [ ] Accessibility
- [ ] Content
- [ ] IA
- [ ] Translation
- [ ] Already completed, no assistance needed
- [ ] Unknown at this time
##### Midpoint
- [ ] Accessibility
- [ ] Content
- [ ] IA
- [ ] Translation
- [ ] Already completed, no assistance needed
- [ ] Unknown at this time
##### Staging
- [ ] Accessibility
- [ ] Content
- [ ] IA
- [ ] Translation
- [ ] Already completed, no assistance needed
- [ ] Unknown at this time
  
## Supporting artifacts
*Please provide links to supporting artifacts as available.*
- **Product outline**:
- **User flows**:
- **Prototype or mockups**:
- **If this is in Sketch, which version or specific page should we focus on?**
- **Content source of truth**:
- **Research plan:**
- **Any epics/issues that may be helpful**:
- **Link to testing accounts** (please do not paste them in this ticket): 

### Have you already worked with someone from OCTO leadership?
- [x] Danielle
- [ ] Beth
- [ ] Mikki
- [ ] Martha

### How do you plan to work with us on this request?
- [ ] I’ll take this to Beth or Danielle’s office hours.
- [ ] I’d like to schedule time to talk about this.
- [x] Let’s work async and meet as needed.
- [ ] Schedule a kick-off call with your team and CAIA for your project **(Recommended)**

 
### Accessibility Help in Slack
The [#accessibility-help channel](https://dsva.slack.com/archives/C8E985R32) in the DSVA Slack, is also available to you as a resource. Everyone is welcome to ask questions or get help from our a11y (accessibility) specialists. Tag `@Terry Nichols` to get a11y help asap.

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag `@Terry Nichols`.**

- If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
- If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jennymayoco%2C+jilladams%2C+RLHecht&labels=sitewide+CAIA%2C+Sitewide+IA%2C+Public+Websites%2C+VA.gov+frontend%2C+Redirect+request&projects=&template=redirect-request.md&title=Redirect+Request)
 
 - If you are creating an [experimental design,](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) please [also contact the DST. ](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)

- If you are requesting [a11y support for user research,](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name) please complete this form, next. 

```[tasklist]
### Content tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/68291
```

```[tasklist]
### CAIA tasks
- [x] CAIA introduction sync scheduled with @strelichl and @coforma-terry 11/1 at 12pm EDT
```

**Comment by mmiddaugh** [comment]
## Needed

**Link labels for VA health chat at facilities where only one type of service is available**
- we suggest the link label should be specific to that task and point to health chat, to avoid creating inaccurate Veteran expectations and propose these labels as a place to start
   - Use VA health chat to make an appointment
   - Use VA health chat to request a prescription or ask a prescription-related question (this may be too lengthy for the proposed location)
   - Use VA health chat to talk to a health care provider about a non-urgent health issue
   - Use VA health chat to reschedule or cancel your appointment

**Link label for VA health chat at facilities where more than one type of service is available (or if availability depends on the facility)**
- we suggest the link label could be more general, like "Learn more about VA health chat". 
- in this case, it might be appropriate to point to a Programs page where more context/details can be provided and then linking to the VA health chat from there (although this requires an extra click)

    The labels described above will be added by local editors to the 
     - In the Spotlight on the system home page (below the Manage your health online box) -> i.e., [Wilmington health care](https://www.va.gov/wilmington-health-care/)
     - In the spotlight on the health service page at the system level -> i.e., [Wilmington health care health services page](https://www.va.gov/wilmington-health-care/health-services/) 
        - we have a known defect in this area which the team will work to resolve

**Content to be added to a VA health chat program page at the health care system level where more context and details can be provided before linking to the VA health chat**
- an example page already in production : [Wilmington health care VA health chat program page](https://www.va.gov/wilmington-health-care/programs/va-health-chat/)
- @lalexanderson-dsva will you please provide recommended content for this type of page or point us to someone who can?

**Comment by laurwill** [comment]
Hi @mmiddaugh ,

After looking at the placement for these links, I wonder if a very simple VA health chat program page would be the best option for all facilities, even those that only offer a single use case for the app.

The In the spotlight box appears just under the **Manage your health online** section, where we include links to use secure messaging, refill prescriptions, and schedule and manage health appointments. It may be confusing to include 2 links close to each other with same main CTA like "Refill and track your prescriptions" and "Use VA health chat to refill prescriptions."

![Image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/104158104/1d515d8d-bab1-4581-8023-1bdc9b9dadd1)

If we go with a single, constant link like "Learn how to use VA health chat," we could avoid the overlap with the existing links on the page. And if a location only offers a single feature in the health chat app, we could make that clear in the page content. That would also make it easier to add to the list of health chat features at a location, if they plan to expand use of this app in the future.

What do you think of that approach?

**Comment by mmiddaugh** [comment]
I think it's brilliant - thank you for helping us to avoid layering additional confusion! It will also age better - no need to update it once the implementation matures and more uses become available at the location. 
How should we proceed with the VA health chat page?

**Comment by mmiddaugh** [comment]
@laurwill I created the attached [VA Health Chat content for VAMC pages - draft.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUgzQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--55d22a42968a7a57509b8ab60af8ee04f651afd1/VA%20Health%20Chat%20content%20for%20VAMC%20pages%20-%20draft.docx) document based on input from a VA health chat SME to give us a place to start. Definitely needs your content expertise and suggestions.

**Comment by laurwill** [comment]
Thanks @mmiddaugh ! This is great — we'll start from this content and get a version ready to send back to the health chat SME you're working with.

**Comment by laurwill** [comment]
Hi @mmiddaugh , I made some [suggested edits in tracked changes](https://dvagov-my.sharepoint.com/:w:/g/personal/laura_willwerth_va_gov/EfTZTJoeePtOjxJxEAwKix8B-ZcVms4tmkTBjrqe-gKKrQ?e=esvTwQ) and left a few questions for you (or possibly for the SME) in the doc. Let me know what you think!

**Comment by mmiddaugh** [comment]
Thanks @laurwill - I responded to all your comments

**Comment by laurwill** [comment]
Thanks @mmiddaugh ! The tracked changes got a bit much, so I saved a [clean version here](https://dvagov-my.sharepoint.com/:w:/g/personal/laura_willwerth_va_gov/ET5-SiSSt85ChxdH3OXrY7sB70b5uJSvpnb5ZN7szohjsg?e=SCcKSe) to share with health chat SMEs. I addressed some comments to the SME there — feel free to add any others you think would be helpful.

I'm OOO for the next 2 weeks and most of CAIA is OOO the week of 12/25, but if you want to send this back to your SME for accuracy review and copy me, I can help reconcile any feedback in early January. And if you need content support in the meantime, please reach out in our sitewide CAIA channel. Thank you!

**Comment by laurwill** [comment]
Hi @mmiddaugh , did you already send the suggested content to the health chat SMEs, or would you like me to do that now? Just let me know who to include and I'll be happy to send directly. Thank you!

**Comment by mmiddaugh** [comment]
Closing this as we are working through VHA DM on a Campaign landing page and have identified a location for links (to use in assessing success while we learn more and can determine contextually relevant opportunities)
