### ISSUE TITLE
Customer Satisfaction and Data Support 

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#68055]
## Product Outline
https://vfs.atlassian.net/wiki/spaces/Contact/pages/2799337688/Customer+Satisfaction+and+Data+Support+Product+Outline

The approach suggests combining all Veteran Support data collection resources (Salesforce and Medallia) to determine if there are parallels in user pain points while establishing new procedures that allow VFS teams to request custom surveys to get direct product feedback and make data driven product improvements VA wide.  Creating stronger hypotheses for A/B testing can increase user survey engagement and gather better measurable results.  The popularity of custom surveys can lead to better informed product decisions and user satisfaction.
## High Level User Story/ies

As a Veteran, I need to provide feedback on my usage of the VA.gov web portal, and as VFS team member, I need to view user pain points, so I can develop solutions. 

## Hypothesis or Bet
If we can combine the feedback from Salesforce and Ask VA, we provide a comprehensive view of all user feedback and can use this data to develop improvement solutions. 

## OKR
_Which Objective / Key Result does this epic push forward?_

### What must be true in order for you to consider this epic complete? 

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `Console-Services`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by clantosswett** [comment]
@ATMiddleton I'm wondering if this is still relevant? Should we close this?

**Comment by clantosswett** [comment]
Tickets associated to this epic have been completed. Closing this.
