### ISSUE TITLE
SPIKE: Determine Impacts to Current User Flow & Functionality

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#68081]
## Background
When Veteran submit a travel reimbursement claim via the BTSSS portal, they must agree to the following terms before they are allowed to submit their claim. We need to add this to the eCheck-in workflow and possibly consider moving the travel portion to after the Veteran has completed check-in so that it does not continue to add to the time it takes for them to check-in.

[Slack thread](https://dsva.slack.com/archives/C022AC2STBM/p1697811766776369)

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/86678742/07ed5aeb-6a3d-42e4-bbbb-2348486d1d65)

## User Story
As a Veteran, I need to be able to agree to the terms for submitting a travel reimbursement claim so that I can understand what is required of me in order to submit the claim.

## Questions to answer
We need to determine the impacts to our current eCheck-in user flow when we add the requested "agree to terms" feature when a Veteran chooses to file a travel reimbursement claim.
- Should we move the travel questions to after the Veteran has completed check-in
- How are we going to add the new terms and allow the Veteran to agree to them or not
- What will be impacts if the Veteran does NOT agree to the terms, such as 
    - Messages on the completion page
    - User flow
    - Other?

**Comment by benbrasso-agile6** [comment]
I set up spike meeting. Will create Mural for collaboration during spike meeting.

**Comment by benbrasso-agile6** [comment]
Just posted progress in other ticket: https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/68083#issuecomment-1791552271

**Comment by benbrasso-agile6** [comment]
Ready for validation @cgednalske @ytsaoca @zach-park @kellysmith1008 

https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1698872826836/7e242e73ef37ecc7d6b398b550a7a3943e1b95fa?sender=u37bb983bd3fc3cc00c7d3286
