### ISSUE TITLE
[UX] Create New User Flow

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#68083]
## Background
When Veteran submit a travel reimbursement claim via the BTSSS portal, they must agree to the following terms before they are allowed to submit their claim. We need to add this to the eCheck-in workflow and possibly consider moving the travel portion to after the Veteran has completed check-in so that it does not continue to add to the time it takes for them to check-in.

[Slack thread](https://dsva.slack.com/archives/C022AC2STBM/p1697811766776369)

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/86678742/07ed5aeb-6a3d-42e4-bbbb-2348486d1d65)

## User Story
As a Veteran, I need to be able to agree to the terms for submitting a travel reimbursement claim so that I can understand what is required of me in order to submit the claim.

Here is the [spike mural we did to decide on the userflow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1698872826836/7e242e73ef37ecc7d6b398b550a7a3943e1b95fa?sender=u37bb983bd3fc3cc00c7d3286). The first option is recommended. 

Create updated user flow in the [travel userflow Sketch file](https://www.sketch.com/s/42a478e7-cb38-49e5-9500-9b21182873da/p/8AD30A0A-3193-4B09-9616-70C9F1AC8A61/canvas). 

## Tasks
- [ ] Update userflow or add documentation to the existing user flow

**Comment by benbrasso-agile6** [comment]
@ytsaoca I'm going to create a quick summary of our analysis and decision, share with UX team to validate, then we'll share out to CIE team for some validation/sharing...

Then, you'll be able to work creating the userflow. cc @zach-park @cgednalske @kellysmith1008

**Comment by benbrasso-agile6** [comment]
@ytsaoca all set for you. I updated the tasks with our spike decision. 

https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1698872826836/7e242e73ef37ecc7d6b398b550a7a3943e1b95fa?sender=u37bb983bd3fc3cc00c7d3286

**Comment by benbrasso-agile6** [comment]
Validated. @ytsaoca I made a couple quick edits. But, you got it all correct, nice work!

Do you want to also circulate it in this slack thread for everyone else to review: https://dsva.slack.com/archives/C02GXKL8WM6/p1699036690348419

**Comment by benbrasso-agile6** [comment]
FYI @kellysmith1008 @cgednalske

**Comment by benbrasso-agile6** [comment]
https://www.sketch.com/s/42a478e7-cb38-49e5-9500-9b21182873da/a/vRrvEb8

**Comment by benbrasso-agile6** [comment]
https://www.sketch.com/s/42a478e7-cb38-49e5-9500-9b21182873da/a/vRrvEb8

**Comment by benbrasso-agile6** [comment]
One comment, not related to this userflow... but, I wonder if even the "Submit" button should/could be "Submit and check in" or something like that, especially when a Veteran goes from Appt list > skips demos > Do you want to file for travel reimbursement? > Review page (Submit) > You're check in

So, would it be helpful to have that "Submit" button include more context about check in is about be completed too? 

Related conversation happened here in Sketch - https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/EexxJwq?annotation=6bf0febc-d2b6-46c4-b4e9-c9dedcb5e66d
