### ISSUE TITLE
Back button is requiring data to be valid on calendar page

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#6808]
The back button on the calendar page seems to only work when a date/time has been chosen, but you should be able to go back whenever you want.

1. Select care type, 
2. Select VA Medical Center, 
3. Select Appt location (I chose one that drops me into request), select continue.  
4. Calendar displays.  
5. Select a date.  
6. Hit back button.  

Expected response, user is  returned to previous page.  
Actual response: nothing happens,  user remains on current page.  Note if I select back before selecting a date the back button works.

**Comment by narin** [comment]
This will be resolved when [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/11784) gets merged.

**Comment by lenaecb** [comment]
@narin - are we good to close this?

**Comment by narin** [comment]
@lenaecb Need to make a tiny suggested change, get it passed through Jenkins, merge and validate on staging before we can close this.

**Comment by narin** [comment]
Merged and validated in staging
