### ISSUE TITLE
Analytics KPI dashboard update request for Debt Team - Form 5655 FSR

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#68094]
# Request an update to your KPI Dashboard  

## What this form is for

Use this ticket template to request an update to your existing KPI dashboard. To request a new product be added to our dashboards, please use [Request a New Standardized KPI Dashboard template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&template=analytics-request-kpi-dashboard.md&title=Analytics+KPI+dashboard+request+for+%5BTeam%5D).

### Expected delivery timelines

The Analytics team will notify you once this ticket has been pulled into a sprint. 

## Instructions for the VFS team
First, tell us what type of change you need to make:

- [ ] Change basic product info
- [x] **Forms**: funnel changes
- [x] **Content**: Add or remove pages included
- [ ] Other_____________________________

Next, use the original [KPI request template](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit#gid=981224988) or [(downloaded Excel version)](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/1586823275/KPI%20Dashboard%20Product%20Details%20Template%20-%20MAKE%20A%20COPY.xlsx?inst-v=ced1f4dd-e997-4aa2-9ae8-2cebe369b42f) you filled out to update your information. If you are not able to find that spreadsheet, reach out to the Analytics team on #vfs-platform-support for a new spreadsheet that reflects what we currently have on file.

- [x] Make a copy of the [Google Sheet](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit#gid=981224988) [(or download Excel version)](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/1586823275/KPI%20Dashboard%20Product%20Details%20Template%20-%20MAKE%20A%20COPY.xlsx?inst-v=ced1f4dd-e997-4aa2-9ae8-2cebe369b42f)
- [x] Complete worksheet as instructed
- [x] Link your completed spreadsheet here: 
[https://docs.google.com/spreadsheets/d/1ZlwjHdCAZZLp2k7QRX0Bf0xsEBr98W_UYUW_rjW7Hlk/edit?usp=sharing](https://docs.google.com/spreadsheets/d/1ZlwjHdCAZZLp2k7QRX0Bf0xsEBr98W_UYUW_rjW7Hlk/edit?usp=sharing)
Updated version is on Tab: **V4 10/20**
- [x] Check your sharing settings to make sure the Analytics team will be able to access it
- [x] Add your team label to follow progress

**Additional Info**

- Please use the [KPI Framework](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/Analytics%20Playbook/va-gov-platform-analytics-kpi-framework.pdf) for more information on the metrics used in the KPI dashboards. 
- If you need any analytics support, read through the [How to request Analytics support](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guidelines.1586823275.html#Analyticscustomersupportguidelines-4.RequestaKPIDashboardinDomo).
- If you do not have Domo access, please [request access here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+access-request&template=analytics-request-google-analytics-domo-access.md&title=Request+access+to+Google+Analytics+and%2For+Domo).

**Comment by mgleo** [comment]
@michelle-dooley 
FSR form has 3 paths depending on the users answers (Full FSR, Short Streamlined Waiver, Long Streamlined Waiver). ([See Mural for a more detailed overview](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1678973946956/6f3bb65fe1ccc2b9d3bc38cd24cd09e74d18d778?sender=ua78f969c4cddcbfe56b27885))
I am marking everything that every path sees as **not** optional. 
We also have another consideration that we have some duplicate pages such as _/contact-information_ and _/current-contact-information_. We still need to support users who started the form before our enhanced version was launched but those older pages will be deleted at some point in the future. For now both duplicate pages are marked as optional.

Let me know if there is another way we should format the spreadsheet.

**Comment by michelle-dooley** [comment]
@mgleo I sorted your worksheet so I could see duplicate urls and now I cannot get it to go back b/c there are not step numbers to sort on. I understand that are a couple different flows so depending on which way you go the "step #" may be different (i.e. one flow it is step 4, another flow it is step 5) but we need a unique step number and name for the set up to work. Could you update your worksheet and add step numbers. The numbers may not be the exact step number based on the flow they go through but they will be consecutive and unique and I assume you will know path based on urls you see flow through. And as far a duplicate urls you will need to determine which step number to map them too, it won't work if we have the same url assigned to 2 different steps.

**Comment by mgleo** [comment]
Hi @michelle-dooley, just resorted the spreadsheet.
Thanks for your assistance on this!
This is complicated for our form because we have so many variables. 
Off the top of my head there is:

- Short SW path
- Long SW path
- Full FSR path
- Whether they’re on the non-enhanced version or enhanced version
- Whether they select that they are married
- Whether they select that they have dependents
- Whether they have had a job within the past 2 years
- Any question where they don’t select anything, they will not see the value input page or summary page

Are there examples from other teams that have been able to add steps with this many variables?

**Comment by michelle-dooley** [comment]
@mgleo the funnel is based on url so you can't have the same url assigned to different step numbers and names (it doesn't know the difference). There are duplicate urls for spouse information, dependents and transition page. I suggest we assign the unique url to the first step number it may appear. I updated the worksheet noting my suggestions for how to manage. [5655 Funnel](https://docs.google.com/spreadsheets/d/1ZlwjHdCAZZLp2k7QRX0Bf0xsEBr98W_UYUW_rjW7Hlk/edit#gid=2026375727). Let me know what you think about proceding this way.

**Comment by michelle-dooley** [comment]
So can you update the [funnel](https://www.va.gov/performance-dashboard/) the way you want to see it if different from how I have it set up? Ultimately it is just a count of the pageviews for each of those pages, what number you call in in the sequence is arbitrary you just have to have 1:1 (can't have same url point to step 4 and 10 for example b/c it won't know to determine which it is.

**Comment by mgleo** [comment]
Hi @michelle-dooley, We spoke with Jamie and Christine yesterday during office hours and understand the funnel a bit better now. Can we proceed with updating the funnel with V4 the way it is now? Thank you!

**Comment by michelle-dooley** [comment]
@mgleo as requested the updated version 4 of the form has been added to the dashboard. Let me know if you have any questions or need anything further. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmJaQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ffd777a446eb809a7b045cc820c78ddcaeb4ab12/image.png)
