### ISSUE TITLE
What should we do with the Design System?

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#681]
Discuss the plan/approach for owning/ maintaining / iterating on VA Design System (now that Jared, previous owner at DSVA, has left the team)
Potentially start knowledge transfer? Or maybe next sprint depending upon how full this team already is? 

## Definition of Done
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by caw310** [comment]
Closing as this is about 3 yrs old and there is a dedicated team working on the Design System.
