### ISSUE TITLE
[CST] Veterans receiving an error that they don't have a Participant ID in MPI

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#68111]
## Background
I received a list of call center cases related to the Claim Status Tool with descriptions of the issues being reported. I found that there were a few of them that were returning an error from the LH Benefits Claims that mentioned that the Veteran did not have a participant ID in MPI. We should work with the call center team / LH team to resolve this issue.

## Context
This is the error returned from LH Benefits Claims:
```
"Unable to locate Veteran's Participant ID in Master Person Index (MPI). " \
            'Please submit an issue at ask.va.gov or call 1-800-MyVA411 (800-698-2411) for assistance.'
```

## Tasks
- [x] Ask Kimberley if she can get more information regarding if the call center is able to action on this issue

## Acceptance Criteria
- [ ]

**Comment by jerekshoe** [comment]
**Update:** I heard back from Kimberley and she said that this is not an issue that her team can fix, but that they should be able to forward these cases to the EVSS service desk and they should be able to deal with them.

I also asked Alex to see if he could have Kayla find out how it was decided that the error message LH Benefits Claims returns should indicate that the Call center should be called in these instances. He messaged back saying that Chante was the one that told them to direct Veterans to the call center in these instances. I may have to reach out in the vsp-contatct-center-support channel to get clarification.

**Comment by HeatherWidmont** [comment]
@jerekshoe & @jacobworrell discuss with Lighthouse in weekly sync next Wednesday

**Comment by HeatherWidmont** [comment]
@jerekshoe to make a ticket to add error messaging for people to call the call center. Once that ticket is made we will close this ticket.

**Comment by HeatherWidmont** [comment]
@jerekshoe following up here, was the above mentioned ticket made?

**Comment by HeatherWidmont** [comment]
@jerekshoe to create the ticket today

**Comment by HeatherWidmont** [comment]
@jerekshoe to create the ticket today

**Comment by jerekshoe** [comment]
New ticket is here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/75720
