### ISSUE TITLE
Move service catalog into source control and provide a mechanism for updating it in Datadog

### ISSUE THREAD

**Issue by zachgoldfine44** [department-of-veterans-affairs/va.gov-team#68112]
We've been creating service catalog entries in the Datadog UI, which is a fine way to get started, but we should export it as YAML, add it to vets-api source control, and then create a mechanism for it to be pushed to Datadog when updated (e.g. via Github Action on merges to main). 

Having it in machine-readable format will also allow us to build additional validations like making sure that all controllers/jobs are associated with an extant service, by checking against what's present in the YAML file.

## Definition of done
- [x] Export service catalog entries as YAML
- [x] Add YAML to vets-api source control
- [x] Create a programmatic mechanism for entries to be pushed to Datadog when updated (e.g. via Github Action on merges to main)

**Comment by zachgoldfine44** [comment]
Does this need to be a part of code yellow or can it be done after?

**Comment by zachgoldfine44** [comment]
Patrick S: No way to export service catalog out of Datadog as yaml, only csv. Need someone w/ permissions to make Patrick S an API key with scope that enables this. 

(Steve, Bill, Aparna have admin)

Aparna can make and share API key.

**Comment by zachgoldfine44** [comment]
@lexicalninja Any updates to share?

**Comment by mattpointzxer0** [comment]
Still in progress, update on Monday.

**Comment by zachgoldfine44** [comment]
Update: verifying. Aiming for draft PR later this week.

**Comment by lexicalninja** [comment]
Draft PR is up

**Comment by mattpointzxer0** [comment]
Patrick S: This should be finalized Monday, with the validations in their own PR.

Bill: Reach out to Platform in slack and cc: @BillChapmanUSDS for admin help.
