### ISSUE TITLE
[CST] LH Benefits Claims API returning 422 with generic error

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#68130]
## Background
I found a case from a group of call center cases that were sent to me where the Veteran is getting a 422 with a generic error when visiting the claims status tool. We should determine what is causing the issue and what steps need to be taken to fix the issue

## Tasks
- [ ] Send Veteran information to LH so they can investigate

## Acceptance Criteria
- [ ]

**Comment by jerekshoe** [comment]
**Update (10/31):** I sent the information over on the Veteran who was experiencing the issue to the LH Benefits Claims team. They said they will look into it, waiting to hear back currently

**Comment by HeatherWidmont** [comment]
@jerekshoe & @jacobworrell will follow up in weekly sync with LH next Wednesday

**Comment by jerekshoe** [comment]
**Update (12/1):** Kayla reached out and informed me that this is related to an issue with the way that the claims themselves are set up (seems that the claim itself doesn't have a participant ID). There shouldn't be any changes needed on our end and it sounds like BGS should be fixing these so they don't continue to occur. We should keep an eye out for this issue popping up again, but I believe we can close this for the time being
