### ISSUE TITLE
Implement automation of "completed" tickets

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#68156]
## User Story
As a Governance team member, I want the "completed" tickets to be created and closed automatically so that I don't have to spend time while on-support manually creating and closing them.

Assignee: @it-harrison 
Peer Reviewer: @briandeconinck 

## Description
In ticket #64525, Governance team member @it-harrison proposed an automated solution for the creation of the "Completed" tickets within the Collaboration Cycle. The "completed" tickets are created after each Governance owned touchpoint in the Collab Cycle (Kickoff, Design Intent, Midpoint, and Staging Review) to indicate to Platform and OCTO leadership within the sprint report and via the quarterly Collaboration Cycle ongoing support initiative that the review took place. They are created manually, which is time consuming and burdensome.

The purpose of this ticket is to implement an automated solution using Github Actions to automate the creation and closure of the ticket. The trigger for this event will be the addition of the associated touchpoint label on the Collaboration Cycle Request ticket. 

## Impacted Artifacts
[Collaboration Cycle Kickoff - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1749286928/Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities)
[Design Intent - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1748336706/Design+Intent+-+Scheduling)
[Design Intent - After the Meeting](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2775253404/Design+Intent+-+After+the+Meeting)
[Midpoint Review - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/1821442052/Midpoint+Review+-+Scheduling)
[Midpoint Review - After the Meeting](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2790686759/Midpoint+Review+-+After+the+Meeting)
[Staging Review - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808348923/Staging+Review+-+Scheduling)
[Staging Review - After the Meeting](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2808447023/Staging+Review+-+After+the+Meeting)
Explainer doc (aka github actions working doc)

### Kickoff
- [x] Test the solution on the kickoff process first
- [x] Currently in kickoff, there is no step for the Governance team member to add a `kickoff` label, or `CC-kickoff` label, so after testing, ensure this step is added
- [x] Kickoff completed ticket must include the following:
   - Title:  `Completed: Kickoff - VFS team name - VFS Product/feature`
   - Body of ticket: `This ticket is for Platform tracking purposes only. There is no VFS action needed.`
   - Labels: `governance-team` more if needed!
   - Sprint: The Sprint in which the Kickoff took place. eg `Oct 26 - Nov 7, 2023`
   - Milestone:  Search for the Collab Cycle Request ticket’s issue number. eg `1219`
   - Estimate: `1`
   - Epic(s): 1) The VFS team's Collaboration Cycle Request ticket (search by issue number) eg `#67510` and 2) The Governance teams Collaboration Cycle Support epic (currently for FY24-Q1, Oct-Dec, eg `#66816`)
- [x] Test/validate by adding new kickoff label to dummy tickets (you can also create dummy epics and/or dummy milestones)
- [x] Once Github actions solution is working as expected, submit for peer review
- [x] After peer review, edit Colab Cycle Kickoff - Moderator responsibilities doc to reflect new process
- [x] Create Github Actions working doc in Collaboration Cycle folder in Confluence to include specific details about how the Github actions is set up, parameters, etc. for future maintenance, if needed

### Design Intent
- [x] Repeat the same kickoff steps for the Design Intent
- [x] Adding the design-intent label is currently a step in the Design Intent - Scheduling guidance. This step will need to be removed and added to the Design Intent - After the meeting guidance
- [x] Update the Github actions reference doc

### Midpoint Review
- [x] Repeat the same Design Intent steps for the Midpoint Review
- [x] Adding the midpoint-review label is currently a step in the Midpoint Review - Scheduling guidance. This step will need to be removed and added to the Midpoint Review - After the meeting guidance
- [x] Update the Github actions reference doc

### Staging Review
- [x] Repeat the same Midpoint Review steps for the Staging Review
- [x] Adding the staging-review label is currently a step in the Staging Review - Scheduling guidance. This step will need to be removed and added to the Staging Review - After the meeting guidance
- [x] Update the Github actions reference doc

## Peer Review
_To be completed by peer reviewer_
- [x] User story and acceptance criteria are met

## Acceptance Criteria
- [x] We have implemented a solution to automate the creation of the "completed" ticket for Kickoff
- [x] We have implemented a solution to automate the creation of the "completed" ticket for Design Intent
- [x] We have implemented a solution to automate the creation of the "completed" ticket for Midpoint Review
- [x] We have implemented a solution to automate the creation of the "completed" ticket for Staging Review
- [x] All of our operational guidance has been updated to reflect the change in our process
- [x] We have created a new operational doc detailing the specifics of the Github Actions for kickoff, DI, MPR and SR

## Team Notification
- [ ] Slack post on #platform-governance-team
- [x] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [x] Ticket has user story, description, tasks, and acceptance criteria
- [x] Ticket has been sized 
- [x] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [x] Ticket has been discussed as a team at Planning
- [x] Ticket has been assigned to appropriate initiative or quarterly epic
- [x] Ticket has been assigned to a Sprint
- [x] Ticket has been moved to the Planned pipeline in the Governance team board
- [x] Ticket as an assignee and peer reviewer

**Comment by it-harrison** [comment]
@briandeconinck I have implemented a solution for this ticket in the following two files:
* [GHA workflow](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/workflows/create-cc-completed-ticket.yml)
* [node script](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/scripts/github-actions/create-cc-completed-ticket.js) the workflow calls

To test: choose a CC-Request ticket in "Awaiting Design Intent" then add one of the following labels:
* cc-kickoff (new)
* design-intent
* midpoint-review
* staging-review

When the workflow finishes check the "Closed" pipeline on Gov Team board to verify that the ticket was created as specified. When you are done you can take off the "sprint" and "epic" and "milestone".

**Comment by it-harrison** [comment]
This ticket will carry-over for QA-ing since the implementation was completed at the end of the sprint.

**Comment by briandeconinck** [comment]
Initial reactions: This is great! I love this so much, and I'm eager to see all the docs updated so we can use this!

A couple of things to look at:
- I created a fresh CC ticket to test with, and accidentally did a stress test on the workflow because I didn't add all of the [headings to the ticket body that get parsed](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/scripts/github-actions/create-cc-completed-ticket.js#L43). That resulted in:
   - "Run failed" emails sent to me, which is great. Just want to verify that I received the failure emails because I'm the one who triggered the script by adding the `cc-kickoff` email and not because I created the ticket (which would mean VFS PMs would be getting those messages anytime the run failed). Pretty sure it's because I triggered the script.
   - "Completed" tickets were created but didn't get the milestone or epic added and didn't get closed. (See #69698 as an example). Wondering if there's a way we can address this, like if there's any missing information don't create the ticket or delete the ticket if it's already been created.
   - For kickoff in particular, we'll want to make sure the docs are really clear on the ordering of steps (like, definitely don't add `cc-kickoff` until you're done editing the ticket!)
   - This does introduce an edge case where a VFS team accidentally removes something important from their ticket body and the script fails. That's probably not going to happen often, but it might be worth adding some troubleshooting note to our docs to check for that.
- For teams that repeat touchpoints, we'll need to make sure there's a clear workflow for generating multiple iterations of completed tickets. On my test ticket, removing `staging-review` and then adding it again successfully generated a second "completed" ticket for staging. We'll just need to document that as the process.
   - In the past we've also used the [2ndStaging](https://github.com/department-of-veterans-affairs/va.gov-team/issues?q=is%3Aopen+is%3Aissue+label%3A2ndStaging) label, so we could probably capture repeat touchpoints that way too... although it would be a pain to create a bunch of extra labels for this. (What if a team needs four staging reviews for some reason?)

**Comment by it-harrison** [comment]
Updates to existing docs:
* [Collaboration Cycle Kickoff - Moderator Responsibilities](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2841313281/Copy+of+Collaboration+Cycle+Kickoff+-+Moderator+Responsibilities+-+68156)
* [Design Intent - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2841313318/Copy+of+Design+Intent+-+Scheduling+68156)
* [Design Intent - After the Meeting](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2841313348/Copy+of+Design+Intent+-+After+the+Meeting+-+68156)
* [Midpoint Review - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2841575425/Copy+of+Midpoint+Review+-+Scheduling+68156)
* [Midpoint Review - After the Meeting](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2841313367/Copy+of+Midpoint+Review+-+After+the+Meeting+-+68156)
* [Staging Review - Scheduling](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2841313390/Copy+of+Staging+Review+-+Scheduling+68156)
* [Staging Review - After the Meeting](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2841575450/Copy+of+Staging+Review+-+After+the+Meeting+-+68156)

**Comment by shiragoodman** [comment]
@it-harrison overall this looks great! However, I'd still recommend you wait for @briandeconinck 's feedback as he'll likely do a more thorough and complete review than me. 

I added a comment to the explainer doc and to the kickoff doc.

**Comment by briandeconinck** [comment]
@it-harrison this all looks good to me! 

About @shiragoodman's comment on the kickoff doc: I actually like the way it's ordered now, as opposed to moving the label task to Step 4. My main worry would be forgetting to do the CC point tracker step after the "completed" ticket is created.

But if some day we can stop doing the CC point tracker step, then that's an easy consolidation that can happen.

**Comment by shiragoodman** [comment]
@briandeconinck I'm okay with whatever the team wants to do. Maybe we keep it as a separate step for now and merge later on once we've built the habit.

@it-harrison Once the changes are published, please be sure to post on our #platform-governance-team Slack channel, tagging the team, so they're aware of the changes. Let me know if you need help determining where the explainer doc should live in Confluence.

**Comment by it-harrison** [comment]
All documentation has been published. The GHA is active. Closing.
