### ISSUE TITLE
Draft Conversation Guide for IPP Pilot Proofing Agent Usability Test

### ISSUE THREAD

**Issue by SophiaPhilipMO** [department-of-veterans-affairs/va.gov-team#68160]
# Problem:
A script is needed for the usability test for proofing agents to guide them through the In-Person Proofing application Veteran facing screens as well as assess attitudes and receptivity to the service. 

# User Story:
As a Proofing Agent, I need to be able to understand and easily use the in-person proofing application so that I can help a Veteran verify their identity in-person. 

# Acceptance Criteria:
- [x] Conversation guide features questions directly relating to content in the PA facing screens
- [x] Conversation guide features screenshots of screens
- [x] Conversation Guide features OCTO research compliant introduction and exit strategies

# Def of Done
- [ ] Conversation Guide completed and uploaded to GH

**Comment by skirkman16** [comment]
Josie and @skirkman16 have made edits to the [conversation guide draft](https://docs.google.com/document/d/1L5sfv0LrxtDJlQCEgjQGv14dXFuKE1Kh_7DCMTtS2E4/edit)

**Comment by SophiaPhilipMO** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/login.gov-adoption/research/IPP%20Usability%20Testing/Proofing%20Agent%20Facing%20Screens_IPP%20Usability%20Testing/IPP%20Usability%20Test_Proofing%20Agents_Research%20Plan.md
