### ISSUE TITLE
Draft Conversation Guide for IPP Pilot Veteran Intake Screens Usability Test

### ISSUE THREAD

**Issue by SophiaPhilipMO** [department-of-veterans-affairs/va.gov-team#68162]
# Problem:
What problem will this solve (ideally, this is a problem for a customer or end-user)? Who is this conversation guide for? How will it be used?

# User Story:
As a UX researcher/designer, I want to have a conversation guide so that it is clear what will happen during the IPP pilot usability testing with Veterans. 

# Acceptance Criteria:
- [x] What does a successful conversation guide look like? What are the elements?
- [ ] 

# Def of Done
- [x] Conversation Guide completed and included in #66977
- [x] Reviewed and approved by leads

**Comment by skirkman16** [comment]
Conversation guide is drafted [here](https://docs.google.com/document/d/1vdOd8fo5kL1Lb364sWdIU52dlYi5X-D01lv-jSMySmA/edit) and has been reviewed and revised by design team

**Comment by SophiaPhilipMO** [comment]
@sleggewie @lmorris3 for review

**Comment by sleggewie** [comment]
I reviewed and left comments for consideration.

**Comment by lmorris3** [comment]
Reviewed and added comments. This looks great - very thorough.

**Comment by SophiaPhilipMO** [comment]
All edits incorporated
