### ISSUE TITLE
Access for Bryan Schofield

### ISSUE THREAD

**Issue by bschofield-va** [department-of-veterans-affairs/va.gov-team#6817]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Crystal Moultrie
- Please provide your name.
   > Bryan Schofield
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Lighthouse, Deputy Chief Engineer, Liberty IT Solution
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Internal%20Tools.md#create-ssh-public-key) for instructions. (Example below)

Already provided: https://github.com/department-of-veterans-affairs/devops/pull/6511

- [Grant AWS Console access?]
  >  NO

Notes: 
Work was done out order on my mistake. Thank you for the support.
https://github.com/department-of-veterans-affairs/devops/pull/6511

**Comment by jbritt1** [comment]
This was handled by https://github.com/department-of-veterans-affairs/devops/pull/6511, but we are retroactively getting this in for the full paper trail. Thanks @bschofield-va for getting this in!
