### ISSUE TITLE
Sidekiq metric issue with Datadog gem

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#68173]
After upgrading [the dogstatsd-ruby gem](https://github.com/DataDog/dogstatsd-ruby), metrics for the Sidekiq integration suddenly stopped. Dependabot updated this automatically [in this PR](https://github.com/department-of-veterans-affairs/vets-api/pull/13802). After rolling back to `5.6.0`, metrics started to roll back in. [Official issue opened here](https://github.com/DataDog/dogstatsd-ruby/issues/287) in the repo.

For the meantime, we've [pinned dogstatsd-ruby to 5.6.0 ](https://github.com/department-of-veterans-affairs/vets-api/blob/master/Gemfile#L61) and we should follow up and track any movement surrounding the issue in the dogstatsd-ruby repo. Pinning versions won't allow any future automated updates to the gem via dependabot.

**Comment by RachalCassity** [comment]
dogstatsd 5.6.1 was deployed to prod
