### ISSUE TITLE
Add new content to FAQ page

### ISSUE THREAD

**Issue by marriej** [department-of-veterans-affairs/va.gov-team#6819]
As a user, I want to read more about what SSO is and understand how it relates to my usage of and security on VA.gov.

- [ ] UX take first stab at an SSO FAQ
- [ ] VSP content team review
- [ ] Add to the VA FAQ page located here: https://www.va.gov/sign-in-faq/. This page will be linked to from the SSO comms modal (#5828).

**Comment by bridgethapner** [comment]
First pass at SSO FAQ:

[Signing in to VA.gov section] 

### What is single sign on?
In April 2020, VA.gov introduced single sign on (SSO). Now when you sign into VA.gov we'll also sign you into MyHealtheVet, eBenefits, and other VA sites. This means you will not have to sign in again when navigating to another VA site once you have signed in here on VA.gov.

**With a single sign on, you can:**
-  Track and manage your VA benefits and services with just one username and password
-  Switch between VA sites without having to sign in each time
