### ISSUE TITLE
Postgres to 14.4 in Prod

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#68217]
This should follow a similar process to what was followed for dev, staging, and sandbox (especially sandbox).
Here is the step by step action plan https://docs.google.com/document/d/1e0vDu0ALNuKpCr1rsAQHo3JgEDHGTUfBI0vCmJw8cK4/edit#heading=h.8nmathttd1gn

## Description
Do the appropriate testing locally and in dev to decide which version of postgres we would like to upgrade to as per:
- https://app.zenhub.com/workspaces/platform-cop-backlog-6359535e384ff5a473132130/issues/gh/department-of-veterans-affairs/va.gov-team/51598

## Action Items
[FOLLOW THIS PLAN
](https://docs.google.com/document/d/1e0vDu0ALNuKpCr1rsAQHo3JgEDHGTUfBI0vCmJw8cK4/edit?usp=sharing)
- [ ] postgis migration
- [ ] Maintenance window
- [ ] upgrade postgres
- [ ] testing in the prod environment
a) create snapshot
b) drop extension
c) upgrade rds/pg
d) soon after upgrade, do another redeploy

## Acceptance Criteria

- [ ] database upgraded and tested in prod
  - https://github.com/department-of-veterans-affairs/va.gov-team/issues/51598

**Comment by laineymajor** [comment]
@Kshitiz-devops to see if he has access to connect to prod

**Comment by laineymajor** [comment]
**For the maintenance window:**
Do we have any idea what our options here are? 
- there is an automated (Amazon) weekly maintenance window set for Monday, but that's too soon for us
- we can set a time and communicate that

Can we put up a banner for sites in vets-api that are affected by this? 
Can we choose the maintenance window whenever we want? 
- yes
- 
If not, who determines this?

**Comment by laineymajor** [comment]
**For the maintenance window:**
Do we have any idea what our options here are? 
- there is an automated (Amazon) weekly maintenance window set for Monday, but that's too soon for us
- we can set a time and communicate that

Can we put up a banner for sites in vets-api that are affected by this? 
Can we choose the maintenance window whenever we want? 
- yes
- 
If not, who determines this?

**Comment by LindseySaari** [comment]
@flooose Please link the slack questions here. 

Need to answer these questions before proceeding. 
1) Who will do the testing after prod has upgraded
2) Look into upgrade window (1-4 am?)

Run this by Clint to see if there are any issues with the timeframe or window that we select.

**Comment by laineymajor** [comment]
What cron jobs will fire during the 5 min maintenance window?

If a job fails, will it kick back to the retry queue? Can we adjust the cron temporarily for those jobs?
- jobs can get queued at any point... not necessarily a cron scheduled thing
- can we know for sure that we can disable jobs via cron job?
- research the retry

@lainey Schedule meeting to discuss remaining questions re postgres upgrade
- Lindsey
- Kshitiz
- Chris
- Kyle
- Eric

**Comment by laineymajor** [comment]
KS discussed multiple options with Eric. 
- DMS (mostly for migrations)
- RDS proxy (not available for this)

**Comment by flooose** [comment]
-   My concerns with this is that we don't have clarity on the following topics:
    1.  taking the database offline while vets-api continues to run
    2.  taking the database offline while sidekiq continues to run
    3.  is it possible to take one, the other or both offline?
        -   what are the ramifications of taking redis offline while a
            job is running?
        -   can we stop redis?
        -   can we pause sidekiq?

**Comment by laineymajor** [comment]
Upgrade timeline:

- va.gov and api.va.gov in maintenace mode 
- Puma/sidekiq scaling down (1-2 mins ago)
- Pods finished scaling. 0 processes running (~30 seconds ago)
- DB Snapshot started (2:16a)
- Snapshot finished in 6 mins. PostGIS extension upgrade starting.
- PostGIS extension upgrade was completed some time ago.
- RDS Maintenance started (patches) at 2:35a
- Patches finished 2:46a. Upgrading engine 2:50a
- Engine still upgrading. Showing 14.4 in RDS UI.
- RDS automated upgrade snapshot creation in progress 
- Automated snapshot running for 15 minutes now. 3:07:16
- Automated snapshot completed 3:12
- in_progress_form count confirmed consistent courtesly by Kshitiz
- DB available 3:19
- Performing terraform sync. DB retention being reset to 7 days. TODO: set back to 31
- Terraform applied. DB available again.
- Scaling Puma/Sidekiq back up.
- Commands run in terminal and returned expected info `bundle exec rails console` 
 `InProgressForm.first.form_data (returns an encrypted object)` `MaintenanceWindow.first (returns unencrypted object)`
- Puma/Sidekiq became available after we scaled pods to 10. HPA was attached and picked up after that (~15 minutes ago)
- http://platform-api.vfs.va.gov/v0/search?query=benefits and http://platform-api.vfs.va.gov/v0/status confirmed working.
ActiveRecord::Base.connection.execute('SELECT version()').first
Showed 14.4
/sidekiq UI was unavailable as it needed to auth with GitHub which redirected to api.va.gov (maintenance)
- Maintenance mode is being disabled via PR now (3:51ET)
- Upgrade complete. va.gov and api.va.gov now accessible. (3:56amET)
-
