### ISSUE TITLE
Feature flag dismissible banner

### ISSUE THREAD

**Issue by kelsonic** [department-of-veterans-affairs/va.gov-team#6824]
# Description

The functionality to dismiss a banner should only be present on non-prod environments until we get more acceptance from stakeholders.

## Acceptance Criteria

- [ ] Hide the dismissible banner functionality behind a feature flag.

**Comment by MickinSahni** [comment]
2020-03-16 PW Standup
* Validated in staging and closing out (as well as related #6734)
* will need a follow-on ticket to remove the feature flag in prod cc @MickinSahni
