### ISSUE TITLE
Add and test check-in app addition for va-maintenance-banner

### ISSUE THREAD

**Issue by lee-delarm6** [department-of-veterans-affairs/va.gov-team#68250]
We saw that the va-maintenance banner appears on the pre-check-in page on prod due to a data hydration issue. We are going to add it to a list of components loaded in a different manner and test on review environment to see if this fixes the issue

![Screenshot 2023-10-24 at 8 11 34 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/135059743/371af2c2-2935-4ffc-a8c6-4e15a301c398)

**Comment by loripusey** [comment]
@lee-delarm6 is this in the current sprint? If so, please move it
