### ISSUE TITLE
[Deactivation] (CAIA) Pension | Update Copy to Mention QuickSubmit

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#68257]
## Issue Description

As a user attempting to apply for Pension benefits online,
I need to know what my options are when choosing to submit via PDF,
so that I can decide whether I want to mail my PDF form or submit it electronically via their system.

As a Pension team,
we need to ensure users attempting to apply for Pension benefits online know about the "QuickSubmit" path to upload a PDF version of their form electronically,
so that they can decide whether they want to use that to submit their claim or not.

Other info:
Using "QuickSubmit" would allow a path for Veterans to still submit all-digitally. It already exists, we'd just be helping them find it. It would also allow us to frame "deactivation" as more of a "digital redirect" and give us time to build the updated online submission version of the form.

---
## Tasks
- [ ] Update any verbiage on existing Pension deactivation designs that let veterans know that while the Pension online form is temporarily unavailable, they can still:
- Use "[QuickSubmit](https://eauth.va.gov/accessva/?cspSelectFor=quicksubmit)" as a path where Veterans can still upload the PDF version of the 527 form
- QuickSubmit is a feature supported by a team in VBA within a product called AccessVA that requires separate login. 
- Provide a link to QuickSubmit within the verbiage.

## Acceptance Criteria
- Any widgets and/or communications already drafted, within the form flows already identified, will be updated to communicate that while Pension form is temporarily unavailable, the veteran has the option to use QuickSubmit as an option to submit a PDF form digitally.

**Comment by katherine-fung** [comment]
Hi @vbellissimo, my team has updated the proposed copy for the "How to apply" page for pension, for the form deactivation. 

Can your team run this by stakeholders and get approval? This is the unauthenticated version. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMW1NQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--512ac32cac62d5dde3e0dcdf9afcd0e57dcb92e3/Screen%20Shot%202023-10-31%20at%204.07.56%20PM.png)

**Comment by vbellissimo** [comment]
@katherine-fung , I may be totally missing this, but are you mentioning the "quicksubmit" part anywhere on there?

**Comment by katherine-fung** [comment]
Oh gosh @vbellissimo - I'm sorry. I need to send you an updated image tomorrow. I updated it in Drupal, but not in Sketch (where I took the screenshot).

**Comment by katherine-fung** [comment]
Hi @vbellissimo, 

Here are the correct screenshots of the info alert and the instructions for how to submit your form. Let me know if you have any questions! CAIA hasn't been in contact with the stakeholders, so we'll need your team to get approval for this copy. (Sorry again about posting the wrong screenshot yesterday - I deleted it from the comment above to avoid confusion.)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeCtRQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d71399d4e6e3691b24ea0447967bac6707c9044a/Screenshot%20%28331%29.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUNRQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5e7c1b393b1e8000d9009483845522adc8017578/Screenshot%20%28332%29.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUdRQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--81a3b060d0688d327aa1b37423eafe87926bcf4a/Screenshot%20%28333%29.png)

**Comment by vbellissimo** [comment]
@jstrothman @emilytheis  can you take a look at the above referencing quicksubmit for the "[how do i apply](https://www.va.gov/pension/how-to-apply/)" page and let me know if you have any feedback? Specifically the "upload your form online" section.

**Comment by aplatt-coforma** [comment]
@vbellissimo should this ticket be added to our current sprint? Noticed its in progress but no sprint tag.

**Comment by katherine-fung** [comment]
Thanks @vbellissimo. If the stakeholders are good with the language, we can apply or tweak it for the other scenarios.

**Comment by vbellissimo** [comment]
@katherine-fung Understood. If you don't mind, you can provide that on this ticket as well. I'll keep you posted on stakeholder feedback.

**Comment by emilytheis** [comment]
My primary comment is that now that we're offering quicksubmit option, which is online,  I would be interested in tweaking the header copy on this screenshot since it still implies you can't submit online. Its sort of a technicality about what online means. Perhaps instead:

Heading: We're updating our online application
While we're working on the application, you have two options....

![Screenshot (331)](https://github.com/department-of-veterans-affairs/va.gov-team/assets/1208781/74e895d8-c7fe-4103-8943-31beaeaaa9b3)

**Comment by jstrothman** [comment]
@katherine-fung Per @emilytheis 's point, maybe:
Heading: The PDF form is the only computer option for applying right now

Separately, I wonder if it's confusing to mention `2 options` in the alert and `4 ways` below that.
`While we're working on the application, you have 2 options`
and then
`You can apply in one of these 4 ways`

Maybe instead of "We're updating..." we just have one sentence:
"While we're updating on online application, your options are:" (apply now or wait)
and keep the `4 ways` wording

**Comment by jstrothman** [comment]
"Computer option" is too weird. How about for the heading:
"The PDF form is the only option for applying right now"

**Comment by katherine-fung** [comment]
Hey @Midge-dev, 

I'm posting the mockups for the 3 states of the widget here. Also posting a Word doc with copy that shows where the links should direct to. 

Word doc with copy: [widget states for how to apply for pension.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTJpQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--774a59cc00b4f8b7982485874a96af93cae2ece2/widget%20states%20for%20how%20to%20apply%20for%20pension.docx)

**Pre-deactivation state (widget content is boxed in purple):**

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTZpQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--16c2899ac18c90cc970a5d289962d0322105fdd7/pension%20widget%20before%20deactivation.png)

**unauth deactivation state  (widget content is boxed in purple):**

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMStpQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a2ebbe67bde06ed52ac0649f518aebb01612b9b9/unauth%20deactivation%20-%20pension%20how%20to%20apply.png)

**auth deactivation state  (widget content is boxed in purple):**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkNpQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b61581f167064b5a7bcfc158859c051d94a11bda/auth%20deactivation%20-%20pension%20how%20to%20apply.png)

**Comment by mayacoforma** [comment]
@vbellissimo 
 I have clarifying question around these two tasks: #68731 and [#68257](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/gh/department-of-veterans-affairs/va.gov-team/68731)? Did Katherine and I work on duplicate tasks last week? Was the intention for us to work together on this? I already sent my version of the deactivation form and email to Julie S. and CAIA for review.

**Comment by vbellissimo** [comment]
This card is related to this: https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/gh/department-of-veterans-affairs/va.gov-team/69454 and it was completed. Closing this now, as well.
