### ISSUE TITLE
Review [Getting Started With VA.gov Forms]

### ISSUE THREAD

**Issue by sshein** [department-of-veterans-affairs/va.gov-team#6826]
Hi all - this is not urgent so feel free to wait on this until you've had normal team reviews. But wanted to put my "Getting Started with VA.gov forms" doc through a review with you all. 

Link can be found here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/getting-started-with-va.gov-forms.md

## Meeting attendees from **requesting team**
Shawna Hein

**Comment by joanneesteban** [comment]
Thanks for the write up, @ss0ss ! Platform Analytics also has documentation for adding analytics for forms [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/data-dictionary-form-events.md).

**Comment by pjhill** [comment]
It may be worth mentioning that there exist some e2e test helpers for testing forms.  The helpers exist [here](https://github.com/department-of-veterans-affairs/vets-website/tree/master/src/platform/testing/e2e/form-tester), but I don’t know of any documentation describing how best to use them.  The code is fairly nicely commented though.  There may be some documentation on how to use it somewhere that I’m not aware of.

I do not have any guidance for manually verifying form functionality, but I would be happy to create some if that is deemed worthwhile.

**Comment by 1Copenut** [comment]
Engineers will need to build comprehensive e2e tests for these form views, and that includes axe checks for every page. Ideally, these happen just before navigating away from a page, not immediately after loading the page. That way we get a good feel for all the content, and hidden content like progressive questions are surfaced.

**Comment by vbellissimo** [comment]
Cancelling/old task.
