### ISSUE TITLE
Fix Confluence admin issues

### ISSUE THREAD

**Issue by laucon** [department-of-veterans-affairs/va.gov-team#68273]
## Info
Work with Andrea to change thew admin settings so every Platform team member can move documents from Developer Docs to Platform Drafts and back again

## Acceptance Criteria
- [x] All members of the content team can move, and edit pages in Conflunece

**Comment by johnny-jesensky-adhoc** [comment]
Need to create a new card, that will allow other other individuals to make edits within Confluence. Lauren to create a new ticket.

**Comment by johnny-jesensky-adhoc** [comment]
Lauren worked with Andrea to ensure the Platform Content Team were all bumped up to Admins, so we have permissions to move documents - marking this as Done.

https://adhoc.slack.com/archives/C02LYB7QXS5/p1698765319057089
