### ISSUE TITLE
Sidekiq Admin UI access for Richard Davis

### ISSUE THREAD

**Issue by dickdavis** [department-of-veterans-affairs/va.gov-team#68286]
### Your Name

Richard Davis

### Your GitHub handle (Sidekiq Admin UI access is managed through GitHub)

@dickdavis

### Team, Role, and Company of the target individual

VSP Identity, Backend Engineer, By Light Professional IT Services

### COR Name

Cecila Lee

### Please confirm if you are on the VFS Team Roster or Platform Team Roster

- [X] [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Sidekiq UI Access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### If PRODUCTION ACCESS is required, confirm/complete ONE of the following

- [ ] I have an AWS Username and it is listed in [here](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf)
- [ ] I currently have access to vets-api Production Terminal via ArgoCD
- [X] I've attached a screenshot of my E-QIP Transmittal Notice E-mail (Drag or Copy/Paste in Additional Notes Section below)

### Additional Notes

![Screenshot 2023-10-24 at 11 25 20 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/10838930/5ea33492-65d7-4930-b62b-2e809452528c)

**Comment by jknipes** [comment]
@dickdavis per [the original Slack request ](https://dsva.slack.com/archives/CBU0KDSB1/p1698163850370379) you have been given ongoing access to Sidekiq in `staging` `dev` and `sandbox`
