### ISSUE TITLE
Sentry error in eligibility.js

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#6828]
JS error: http://sentry.vfs.va.gov/vets-gov/website-production/issues/106684/?query=is%3Aunresolved%20source%3Avaos

**Comment by lenaecb** [comment]
Currently only happened once. Lower priority.

**Comment by jbalboni** [comment]
Some staging examples of this: http://sentry.vfs.va.gov/vets-gov/website-staging/issues/108864/?query=is%3Aunresolved
