### ISSUE TITLE
Access Management - User Management Approach using GitHub teams

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#683]
## User Story and Problem Statement
As a VFS or VSP team member, I want to see an easy, fast, and secure access onboarding experience with little to no manual steps, so that I can quickly get the tools I need to start helping Veterans on VA.gov.

### High Level User Story/ies or Description
The process for access is very manual and time-intensive for both VSP Operations and the users requesting access. Right now, to get access, a user needs to follow instructions and fill out a ZH issue. Then VSP Operations will manually process each request. Depending on the type of access, DEPO may need to approve the request. Additionally, the process of auditing users on VA.gov is time-consuming and unclear, because VSP Operations needs to check with each team to verify if a user is active. This process is very cumbersome for all parties involved.

Now we want to create a clearer process to better help organize teams, so users can see where they are in the access process. Finally, once that process is in place we will work to address the task of automating access on VA.gov.

How might we have a better structure user management, so that auditing team membership, granting and automating team access can be easy Va.gov.

### Pain Point being addressed
The time it takes to get access
Transparency during the access process
Manual and time-intensive
Auditing is time-consuming and slow

### Assumptions and Hypotheses

We **hypothesize** that **if** we use a have a standard, streamline, and self-service access process for all teams, **then** they will be able to have more control over their access needs and start building on VA.gov faster.

### OKR
O1: Teams have efficient experiences using the platform to build impactful products for Veterans, where their expectations are exceeded.

### Success metrics 
- [VSP KR] Increase in customer NPS
- [VSP KR] Reduction in volume of “non-human-needed” support requests month over month from VFS teams
- All VSP and VFS users should be on a Verified GitHub team.
- Platform time spend on access requests (decreases)
- Time it takes for auditing (decreases)
- No legacy users on the Platform

## We will know we're done when
- All VSP and VFS teams are organized via GitHub teams, all new teams are added to GitHub teams as a part of orientation, and DEPO does that task.

### Additional Details/Notes (optional)
We will be working with Product support and Leadership to ensure this will be in place.

### Artifacts
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/vsp_user_management_approach/product_outline.md

### Communication
- Team that owns this super epic: VSP Operations
- Teams contributing to this super epic: Ops, Leadership, Product Support

**Comment by wyattwalter** [comment]
- get github teams created
- audit of current group membership in git
- sync up current user list in git with users in github teams
- ansible updates to pull list of users/keys from a given team
- configure deployments to use new key list
- update documentation, demos, etc
- phase out old list and delete keys from git

**Comment by ricetj** [comment]
Some work was started here: https://github.com/department-of-veterans-affairs/devops/pull/5383

**Comment by ricetj** [comment]
This work is started now and will be continued in the next few sprints

**Comment by ricetj** [comment]
This work is going to be rescoped due to the work that is happening under the Infrastructure overhaul.

**Comment by ricetj** [comment]
Due to the lack of personal, we deprioritized this work to focus on getting processes in place to organize teams. We will be rolling back the changes we made on VSP and taking on this work later as part of the Infra Overhaul.

**Comment by drorva** [comment]
Scheduled a meeting with DEPO to discuss on 6/1/20

**Comment by drorva** [comment]
@gunsch FYI

**Comment by drorva** [comment]
Talked to DEPO, and we're good to go on this.
One change we agreed on in the meeting is that DEPO COR, Contracting Officer Representative, people like Jeff Hayter and Mary O'Toole who are in charge of contracts, be the ones in charge of adding/removing people from the teams. They know better than the product owner the status 9f different people.

The next step, I believe is to figure out the team levels and permissions, and then start looking at actual implementation.

**Comment by Jeff-Hayter** [comment]
Sorry to interject,  but I have to disagree with this approach @drorva .  Putting the responsibility on a COR will slow things down immensely. That's one of the reasons we're revisiting this and the access process.  I can only speak for Mary and myself, but keeping track of who joining or leaving a specific team isn't something we would have time to do.  I'm happy to discuss this separately as I don't think we were part of that DEPO conversation.

**Comment by drorva** [comment]
@Jeff-Hayter following on the conversation we had today, let me know if you're OK with COR doing this, or feel like the Product Owner should do it. I'm OK either way.

**Comment by Jeff-Hayter** [comment]
@drorva Yes, I do the the Product Owner makes more sense in terms of managing who has access to their team(s).  If they later decide to delegate that responsibility to a COR that's fine and should be allowed.

**Comment by drorva** [comment]
@Jeff-Hayter, OK, we'll go with that, at least for now.
@KevinMHoffmanUSDS, @chrisj-usds @JeffBarnesUSDS, FYI, change to what we agreed to in the meeting.

**Comment by drorva** [comment]
@ricetj yes, let's go ahead.

**Comment by jhouse-solvd** [comment]
@ricetj - Can you drop a quick note as to next steps / status of this one?

**Comment by ricetj** [comment]
We can connect on this, but status is that product support now has the ability to grant repo access via vets.gov-write team. As for rolling this out to other teams, this hasn't happened and was going to be a part of the Sentry 10 (some of the teams) rollout. There is still questions around if there is an MOU that is needed for this to happen as well.

**Comment by jhouse-solvd** [comment]
@ricetj or @gunsch - Do we know if all of the teams in GitHub were already created? 

Is there a definitive list of what those should be, etc? Asking because we are wanting to understand if this phase/task of the wider project can be closed... 

If not, if you could let me know what is the next step, that would be awesome. BE tools is looking to leverage GH teams for access to Sentry 10, during Q4, if possible. 

Thank you!

**Comment by ricetj** [comment]
@jhouse-solvd no teams were not created, the idea there was use Sentry 10 as a way to get some of the team up and running. Feel free to grab some time on my calendar to chat more about this.

**Comment by jbritt1** [comment]
Is this work still relevant? Or has this path become a bit more obsolete? Can we update this in the event it is still needed / a priority or close it if it is not?

**Comment by jhouse-solvd** [comment]
@jbritt1 - There is still a lot of relevant information in here that can likely be groomed and migrated into a more up-to-date initiative. It's assigned to me, so I'll take care of it. Thanks for the nudge! ;)

**Comment by jhouse-solvd** [comment]
There is currently some clean-up happening around GitHub teams. When and if a larger initiative is decided, we will re-scope and define new criteria accordingly. 

Closing.
