### ISSUE TITLE
Analytics Implementation or QA Support for View Dependent

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#6830]
# Analytics Implementation or QA Request

## What this form is for
Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets. 

## Description
- Is this request for Google Analytics implementation or QA?
  - **Google Analytics**  
   
  
- Who is this request for?
    - **@cohnjesse** 
    _Provide any relevant contact information and link this issue to the insights team on the DSVA Slack Channel: `#VFS-Platform-Support`._
    
- What team/project is this work for?
    _this adds context for the data_
  - **The View Dependents feature moving from eBenefits to VA.gov** 
    - **`#vsa-ebenefits` Team**
    
- Provide the Domain where Google Analytics needs to be implemented
    - **https://staging.va.gov/view-change-dependents/view](https://staging.va.gov/view-change-dependents/view)**
    - **No PII**
    - **va.gov**
- Please provide any upcoming deadlines or important milestones
  - **This will most likely launch with "Add or remove your dependents" which is still in development to be launched**
  -   **Aiming for end of April**

- Typical Website Interactions to Track
  - *Conversions - Understanding the User Flow:* _Provide URLs that are part of the application from introduction page to successful form completion; conditional pages that are visible depending on an applicant's answer should be marked accordingly._
  - **Landing: [https://staging.va.gov/view-change-dependents/](https://staging.va.gov/view-change-dependents/)**
  - **Actual Tool page: [https://staging.va.gov/view-change-dependents/view](https://staging.va.gov/view-change-dependents/view)**
  - **Learn more about adding or removing dependents (two places): [https://www.va.gov/view-change-dependents](https://www.va.gov/view-change-dependents)**
_This page will house info like what should I bring into this form, who is eligible, and the login button if not already authenticated_
  - **Button to add or remove dependents: [https://staging.va.gov/view-change-dependents/add-remove-form-686c/](https://staging.va.gov/view-change-dependents/add-remove-form-686c/)**
  - **Get help filing a claim: [https://www.va.gov/claim-or-appeal-status/](https://www.va.gov/claim-or-appeal-status/)**
  - **Phone number for questions: [tel:800-827-1000](tel:800-827-1000)**

- Sample Users when authentication is required _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_
    - **Provided with `mvi-staging-users.csv`**

- Test Users to replicate the event _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_
  - **`10@g` - none found**
  - **`12@g` - none on award, 4 not on award**
  - **`16@g` - none found**
  - **`55@g` - none found**
  - **`228@g` - none on award, 2 not on award**

- Certain conditions/responses that need to be reviewed
  - **Unknown**

- Additional Comments
  - **It should be noted that there are no staging users with dependents on their awards**
  - **These links and pages are in the disability hub but will eventually be moved to the root and that part of the url will be removed.**
  - **[All the mockups](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/features/view-update-dependents/research-design)**

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by nedierecel** [comment]
@jonwehausen Threading you here if you can please coordinate the Discovery call for View Dependents.

**Comment by jonwehausen** [comment]
## Datalayer Requirements
@jason-gcio @cohnjesse 

## Developer notes
- The `error-key` is open for the level of granularity you all need - we would just like to request the error number be the first portion the error-key - for example `error-key: 500 internal error` 

### API Request Events
Description of API Event | Datalayer Request
------------ | -------------
Successful load of view dependents | `dataLayer.push({`<br>`'event': 'disability-view-dependents-load-success'`<br>`});`
Failure to load dependents | `dataLayer.push({`<br>`'event': 'disability-view-dependents-load-failed',`<br>` 'error-key': '500 internal error'})`<br>`});`

### Navigation(button) Events
Description of Interaction | Screenshot | Datalayer Request
------------ | ------------- | -------------
Click on 'Add or change dependents on your VA benefits' |![image](https://user-images.githubusercontent.com/48527022/78361246-149b2200-7586-11ea-8bac-1216206e7a6a.png) |`dataLayer.push({`<br>`'event': 'cta-default-button-click'`<br>`});`
Click on 'Add or change dependents' | ![image](https://user-images.githubusercontent.com/48527022/78361445-69d73380-7586-11ea-94d3-92cf549601b4.png)|`dataLayer.push({`<br>`'event': 'cta-default-button-click'`<br>`});`
Click on 'Add or remove a dependent' |![image](https://user-images.githubusercontent.com/48527022/78361614-ae62cf00-7586-11ea-9e7c-bf10d8f9f3a9.png) |`dataLayer.push({`<br>`'event': 'cta-primary-button-click'`<br>`});`

## Existing tracking: 
- ✅ We already have existing tracking for clicks on telephone numbers
- ✅ Per our call, rather than implement tracking on static links, we can provide a page flow report that dictates seeking help (hopping from /view-dependents to /get-help-filing-a-claim)

**Comment by jason-gcio** [comment]
@jonwehausen - I think that last green button is from an old layout.  Also, we should be homogenous with the use of "change" and not remove.  Can you tell where that green button came from?

**Comment by jason-gcio** [comment]
@jonwehausen - Thanks for clarifying on that green button above, that's really helpful (so many buttons!).  Those other two  blue buttons are from the landing page that we are asking help from Public Websites to create for us...should we simply let the dev know over there?
cc: @cohnjesse

**Comment by bsmartin-ep** [comment]
@jonwehausen -

Any thoughts on how you want the `cta-default-button-click` event tracked?

We currently have a tag, trigger, and lookup table for `cta-primary-button-click`:

Tag | Lookup
-- | --
![image](https://user-images.githubusercontent.com/62304138/81116710-d8940d80-8ef3-11ea-851f-5fc17ddfbf73.png) | ![image](https://user-images.githubusercontent.com/62304138/81116779-f6fa0900-8ef3-11ea-8523-55902c873df4.png)

### I can either...

1. Make the `Primary CTA Button Click` tag into a generic `CTA Button Click` tag and add the `default` button into that.

2.  Duplicate the structure of the `Primary CTA Button Click` tag and keep the `default` button separate.

**Comment by jonwehausen** [comment]
Hi @bsmartin-ep ,

Great question! Let's move forward with option 2 you laid out. 

Mirror the structure contained for primary button for default button. 

Thank you sir!

**Comment by bsmartin-ep** [comment]
Sounds good @jonwehausen.  A first pass...

https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000286

Should we update the Event Actions from...

`Button CTA - {{Click Text}}`

to...

`Primary Button CTA - {{Click Text}}`
or
`Button CTA - Primary - {{Click Text}}`

**Comment by jonwehausen** [comment]
### QA Testing - WORK IN PROGRESS
 
Description of Interaction | DL Screenshot | Tag Screenshot | Test Status
------------ | ------------- | ------------- | -------------
_Loaded a test user with **no** dependents | ![image](https://user-images.githubusercontent.com/48527022/81737889-d0455080-9466-11ea-8e0f-b385c808a33e.png) | ![image](https://user-images.githubusercontent.com/48527022/81738008-f79c1d80-9466-11ea-9cbc-6f9010011abc.png) | ✔️ **PASSED**
_Loaded a test user **with** dependents configured_ | N/A | N/A

**Comment by bsmartin-ep** [comment]
@jason-gcio / @jonwehausen -

Have the staging URLs changed?  These are 404ing for me...

Landing: https://staging.va.gov/disability/view-dependents
Actual Tool page: https://staging.va.gov/disability/view-dependents/dependents

**Comment by jason-gcio** [comment]
Ah yes, they did I think: https://staging.va.gov/view-change-dependents/view/
Eventually these will be:
Static landing (Drupal): https://www.va.gov/view-change-dependents (Ticket via PubWeb)
View dependents: https://www.va.gov/view-change-dependents/view
Online form application: https://www.va.gov/view-change-dependents/add-remove-form-686c/

**Comment by bsmartin-ep** [comment]
## WIP - Datalayer QA

Interaction | Data Layer
--- | ---
![image](https://user-images.githubusercontent.com/62304138/82262260-907edd00-992e-11ea-9f01-e9cb0cc6b28b.png) | ![image](https://user-images.githubusercontent.com/62304138/82262311-a8eef780-992e-11ea-8c12-7cdc5437a942.png)

**Comment by jonwehausen** [comment]
Hi @cohnjesse ,

We want to follow-up on Brian's QA finding above, we would like to request the current `cta-default-button-click` be changed to `cta-primary-button-click` for the **green** "Add or remove a dependent" button.

**Comment by jonwehausen** [comment]
@bsmartin-ep & @bmcgrady-ep we're waiting on appropriate test users with active dependents to test the 'disability-view-dependents-load-success' event.

**Comment by joanneesteban** [comment]
Adding the `blocked` label until we receive test users for staging.

**Comment by bmcgrady-ep** [comment]
Hi @jason-gcio just following up on this request. Do you have any test users we can use for staging? We need test users with active dependents to test the dependents-load-success' event.

**Comment by bmcgrady-ep** [comment]
## WIP - Datalayer QA

Interaction | Screenshot | Data Layer | Pass?
:-- | --- | --- | ---
'disability-view-dependents-load-success' event | 
![image](https://user-images.githubusercontent.com/66263904/89080458-bf0d3100-d33d-11ea-926e-fb2fa5cba2a6.png)
 | 
![image](https://user-images.githubusercontent.com/66263904/89080389-85d4c100-d33d-11ea-8162-6be99a73d34b.png)
 |     **:heavy_check_mark: &nbsp;PASS**

**Comment by jonwehausen** [comment]
## QA Testing
- This testing was performed using test user +271

Description of Interaction | DL Screenshot | Test Status
------------ | ------------- | -------------
Successful load of view dependents | ![image](https://user-images.githubusercontent.com/48527022/89560216-ad67d580-d7e4-11ea-9dba-afe638a3f1bd.png) | ✔️ **PASS**
Successfully found file gate | ![image](https://user-images.githubusercontent.com/48527022/89560392-ec962680-d7e4-11ea-956f-aab0baad5984.png) | ✔️ **PASS**
Click of primary button "Add or remove dependent" from https://staging.va.gov/view-change-dependents/view | ![image](https://user-images.githubusercontent.com/48527022/89560672-66c6ab00-d7e5-11ea-96c0-8f7868912b65.png) | ❌ **DOES NOT PASS** <br><br> **`event` should be adjusted to `'cta-primary-button-click'**

@jason-gcio We will want to have one of your dev resources change the event name for that last test case to be `cta-primary-button-click`. Also, if we have a test user we know for sure has no dependents configured, we can get the `disability-view-dependents-load-failed` event validated. Thank you sir!

**Comment by jason-gcio** [comment]
Great, thanks @jonwehausen! You can use **vets.gov.user+EBN1@gmail.com** to get one with no dependents.
@micahchiang / @cohnjesse - do we need a ticket to add that last event name?

**Comment by jonwehausen** [comment]
Thanks @jason-gcio ! I edited my comment above that shows validation for the `disability-view-dependents-load-failed` event, this looks good! 

@bsmartin-ep When you have a moment, can you stage the tagging for: 
- Successful load
- Failed Load
- Add lookup table entry for primary button, can use "Add or Remove Dependents" in the Event Action

Thanks!

**Comment by bsmartin-ep** [comment]
@jonwehausen -

I created this workspace:  https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000349

---------
- Successful load
- Failed Load

What do you see these tags needing outside the default we're triggering right now...

Category|Action|Label
--|--|--
API Calls|Forms - Disability|disability-view-dependents-load-success
API Calls|Forms - Disability|disability-view-dependents-load-failed

-----------
- Add lookup table entry for primary button, can use "Add or Remove Dependents" in the Event Action

Thoughts on adding this via a Default Value of the `{{Click Text}}`?  Or maybe using the `JS - Generic - Button Click Text Null Check` variable like the _Default CTA_ buttons do?

![image](https://user-images.githubusercontent.com/62304138/89600674-98b12f00-d830-11ea-8b73-3e29997aac66.png)

I'll `^` the other regex while I'm in here as well.

**Comment by jonwehausen** [comment]
@bsmartin-ep Thanks for this documentation. 

### Successful / Failed Load
- We can maintain the existing taxonomy you have above, the label here is descriptive enough to identify what occurred and the category reflects the API Calls


### Lookup Table
- Good call, yes let's go ahead and add in the default value or use the generic click text null handler as well.

**Comment by bsmartin-ep** [comment]
@jonwehausen -

Updated to use `JS - Generic - Button Click Text Null Check` as a default `Event Action` in case we ever want to dataLayer something in there.

Just to refresh my memory, we aren't making any changes to the `Event Action` to differentiate between Primary and Default CTA buttons?  Relying on the `Event Label` for that?

Data Layer|Tag
---|---
![image](https://user-images.githubusercontent.com/62304138/89970023-d7c2f400-dc25-11ea-8201-09c5825944cf.png)|![image](https://user-images.githubusercontent.com/62304138/89970143-2d979c00-dc26-11ea-9ec2-e08777bc5c22.png)

**Comment by joanneesteban** [comment]
@jonwehausen @bsmartin-ep bumping this issue.

**Comment by jonwehausen** [comment]
@cohnjesse We would like to request to adjust the event name here be adjusted to correspond with the design system primary button component. **The full event name should be `cta-primary-button-click`**

![image](https://user-images.githubusercontent.com/48527022/93211524-59c7a080-f72f-11ea-800d-bbbd035f0f39.png)

**Comment by jonwehausen** [comment]
### Final QA  Round

Description of Interaction | Screenshot of Interaction | DL Screenshot | GTM Screenshot | Test Status
------------ | ------------- | ------------- | ------------- | -------------
Clicked on button for Add or remove a dependent | ![image](https://user-images.githubusercontent.com/48527022/93395477-fbd8ad00-f843-11ea-825f-ba5e2ea3bf6c.png) | ![image](https://user-images.githubusercontent.com/48527022/93397059-c41f3480-f846-11ea-9320-8219e69902f6.png)  | ![image](https://user-images.githubusercontent.com/48527022/93396825-49eeb000-f846-11ea-8df0-72320c21abf8.png) | ✔️ **PASS**
Failed to load view dependents | ![image](https://user-images.githubusercontent.com/48527022/93396910-80c4c600-f846-11ea-8afe-0bbd67930743.png) | ![image](https://user-images.githubusercontent.com/48527022/93397090-da2cf500-f846-11ea-8fe5-eecfd3fb250a.png) | ![image](https://user-images.githubusercontent.com/48527022/93397438-9ab2d880-f847-11ea-8b14-34d246fb58df.png) | ✔️ **PASS**
