### ISSUE TITLE
Review findings regarding Lighthouse & determine transition value for MVP relaunch

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#68306]
## Issue Description
**User story:**
As a new Pension team,
we need to understand how to transition from Central Mail API to Lighthouse API,
so that when we relaunch the Pension form, it is using the recommended API approach.

**Notes:**
Lighthouse is understood by the non-disability benefits team, but only place it exists is the 526 form.

**Open questions:**
What is the current state of the Pension form using Central Mail API?
How might we start transitioning from Central API to Lighthouse API?

**This is a follow on task from #66956**

---
## Tasks
- [ ] Review the following information gathered by Wayne regarding how to implement Lighthouse to replace Central Mail

**Notes from Wayne:**
Not sure if this is what was intended, but with using the changes to 526 as a template, the approach is at least mapped out. There is some new functionality to implement in Lighthouse to replace all that CentralMail is doing - mostly surrounding claim DELETE and PDF creation.

- https://github.com/department-of-veterans-affairs/vets-api/pull/14057/files
- CentralMail-Lighthouse.md

- [ ] Determine whether we would need to transition to Lighthouse as part of "mvp" relaunch of Pension, due to any dependencies listed within the "mvp" criteria as listed in [this document.](https://docs.google.com/document/d/1nOFRiDiLbz8O5FSWd5WMrtTZuFd1Jv0wxm-l7V90lvg/edit)

**mvp features criteria:**

- Updating ITF date to date_created rather than date_submitted (this could be done now)
- Adding missing fields
- Addressing A11y defect-0 and defect-1 accessibility issues on pages that are getting updated
- Adding logging and monitoring
- Alerting VA.gov and VBA of failed submissions

## Acceptance Criteria
- We will have a baseline understanding of whether we should transition from Central Mail API to Lighthouse as part of the "mvp" Pension relaunch.
- If needed, document pros/cons on decision on whether we need to transition to Lighthouse as part of mvp or wait for a "future state" relaunch of Pension form.

**Comment by emilytheis** [comment]
To clarify, Lighthouse Benefits Intake API is used both for the backup submission process for 526 as well as the 686c/674 backup submission as of this week! So there should be a model to follow from either/both of those teams!

**Comment by mjknight50** [comment]
Closing this ticket and moving to implementation of the API change:
https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/gh/department-of-veterans-affairs/va.gov-team/69023
