### ISSUE TITLE
Access for Beth Jacobson

### ISSUE THREAD

**Issue by beeyayjay** [department-of-veterans-affairs/va.gov-team#6831]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your name.
   > Beth Jacobson
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > va.gov cms team, engineer, Agile 6
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Internal%20Tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBT0QQ2i3mIBocP2ZtYYK2iTRjNUX07xvaXsI23x5kXuQ3rlNNrneHdZal+QmXiQ134Bdxmx6yvOfhCFbr6VwTLwAmRubUbG9FyD1+xPrimSVHRA8VSOw0E2wTc2wrOWougaklCafxpfpDrnvfFzhKoo4NapK6Pga/ywyanOJfEnyqp62A1M1NKi9FSb6M0FeyhUS1b0pTt/RdzbHW27MvAnWI8G1LXXBA2UMFOFgQnW3EwS5lhg6NO276UCh+O1Jekcyv3b1venGw0LeDaWC154exoX9L7In0SW5zggPjL8opvE7L+uovbqddERrRsK2sUs7h6uIBiFK2VxJHeYAt bethjacobson@Beths-MacBook-Pro.local
```

- [Grant AWS Console access?]
  > NO
 
@department-of-veterans-affairs/vsp-operations

**Comment by tskinn** [comment]
@beeyayjay you should now have access to the SOCKS proxy. If you run into problems reach out in slack.

**Comment by beeyayjay** [comment]
All good. Thanks!
