### ISSUE TITLE
Access for Kelly Lein

### ISSUE THREAD

**Issue by kellylein** [department-of-veterans-affairs/va.gov-team#6832]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Crystal Moultrie
- Please provide your name.
   > Kelly Lein
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > I am the Product Manager of a development team on the Lighthouse program.  I work for Ad Hoc.
- [if requesting SSH key authorization] What is the **public** SSH key?  

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC4MY07Nzpejap1vosciHnsj0pENzxhfPXjECm0+NZCnFUDZ1FP3BwV6ZBWdgvkrJOTILTW9g2aWHEQ7SSUTgml1OGOKyN4iuDeAe8cfBknscXBJfRaxvsPso6fvUEPgxkHRd5FHMRJvO8gFpc47OWpoyo1NseatvVFqtUp8PswbCbNxeFHCCAxEz7tQxF/XGZgFKBGMDmNFUU4cQgH+DGBb9ic8tmvdoeBHQKXIpvy6sNWhoCR0aNkC1sgD8Rnv3Mc7V8qOked5VsurCDm9BO9VVTQtNPRXnBpinN9Z+3DSzz6rwtTGogmAlm7g6reZQLMq86xUlMxmzFfsmcjJ40R kellylein@Kelly-Leins-MBP.hotspot

- [Grant AWS Console access?]
  > NO
  >  Please give a brief description for why you are requesting AWS access.

**Comment by kellylein** [comment]
@department-of-veterans-affairs/vsp-operations please review

**Comment by tskinn** [comment]
@kellylein you should now have access to the SOCKS proxy. If you run into problems setting it up reach out in slack in vfs-platform-support
