### ISSUE TITLE
Back link in VA request calender page not going to the previous page

### ISSUE THREAD

**Issue by jenniemc** [department-of-veterans-affairs/va.gov-team#68338]
## Summary
When going through the VA request flow at the Calendar page, the back button does not go back to the previous page

## Specs
In staging environment 

## Steps to Reproduce

- Log in id.me as Patient999 and make an Eye care appt> Optometry > VA medical center > Cheyenne Va Medical Center > I need a different clinic (to enter request flow) 

- At the calendar page, I select `Back` button 

### Actual Result
Goes to the “Choose the type of care you need” page while the URL displays `https://staging.va.gov/my-health/appointments/schedule/va-request/clinic`
### Desired Result
It should go to the Choose a VA clinic page with the URL `https://staging.va.gov/my-health/appointments/schedule/clinic`
## Definition of Done
- [ ] When going through a VA request flow, the back button at the calender page should bring user back to the Choose a VA clinic page

---
## How to configure this issue
- [ ] **Labeled with Team** (`vaos`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `design`, `product`)
- [ ] **Labeled with** `Bug`
- [ ] **Assigned to** Product for prioritization

**Comment by JRRoof** [comment]
Validated in Staging
