### ISSUE TITLE
Service Flow Discovery

### ISSUE THREAD

**Issue by StevenStraily** [department-of-veterans-affairs/va.gov-team#68337]
Do discovery research on the service flow for 1010D to identify different touchpoints, responsible parties, processes, potential gaps, and redundancies on the service level. This should also be accompanied by a Service Blueprint Artifact in the team's Mural folder.

**Comment by StevenStraily** [comment]
The scope of this is massive, and some brief stakeholder interviews will be required. I will try to have what information I can track down and make an educated guess on in the artifact by the end of Sprint 4, but that may even slide to 5, and it may not be "complete" until later. I also need to add the User Journey Map as a blocker/prerequisite to this, as this artifact can't exist appropriately without it.

**Comment by baltes** [comment]
Closing this out as a representation of the first round of stakeholder interviews.
