### ISSUE TITLE
CT: Optimize Comparison Tool Autocomplete

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#6834]
As a Veteran using the Comparison Tool, I need autocomplete in the comparison tool to provide enhanced predictive search results, so that I can better find the institutions I'm interested in. 

## Assumptions
1. This work will be utilizing a review instance for testing.
2. The performance of the tool is maintained. 
3. This work will be completed behind a prod flag so that upon merge it is only available on staging. 

## Acceptance Criteria: 
1. Autocomplete query will search for text within the field not just the start of the field.
2. Autocomplete query will utilize fuzzy search to provide partial matches for misspellings.

## Supporting Artifacts
1.  Use cases: TBD

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/616

**Comment by desireeturner** [comment]
This implementation results in a significant negative impact from a performance perspective and therefore has been taken off of our PI commitment list. Closing this story as OBE.
