### ISSUE TITLE
Flipper UI access for Richard Davis

### ISSUE THREAD

**Issue by radavis** [department-of-veterans-affairs/va.gov-team#68350]
### Your Name

Richard Davis

### Your GitHub handle (Flipper UI access is managed through GitHub)

@radavis

### Team, Role, and Company of the target individual

MHV on VA.gov Cartography Team, Software Engineer, Agile Six

### Please confirm if you are on Atlas, Platform Team Roster or are a Federal User

- [X] [Atlas](https://dev.va.gov/atlas)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [X] Lesser Environments (Dev/Staging/Sandbox)
- [ ] Production (if requesting, justify prod access below)

### Reason for Production Access (If requested)

Requesting access so that we may conduct User Research (specifically for [this issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/66602)) in staging and gate features by email address.

**Comment by bdech** [comment]
Confirmed in Atlas

**Comment by bdech** [comment]
Hi Richard, you've been granted access to lower environments.
