### ISSUE TITLE
[SSO Launch ]Enter Test Cases into TestRail

### ISSUE THREAD

**Issue by marriej** [department-of-veterans-affairs/va.gov-team#6835]
This will need to be a team effort. Test cases can be found here:
https://docs.google.com/spreadsheets/d/1V4iQ1qtpDh_w0_Lruo13d7U6xi-qpCktFEkOe3pHyeQ/edit#gid=0
**Once you have entered a test case into TestRail shade the corresponding row with Ad Hoc green color**

[general QA documentation for the platform is available here:](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/README.md)
[Information about the artifacts that we recommend VFS teams create is here:](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md)
[TestRail examples and user guides from a VSP context are available here:](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/testrail/README.md)
[Browsers +SauceLabs login info:](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/cross-platform-testing-plan.md)
[Browser testing instructions:](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/manual-testing/cross-browser-manual-testing.md)

Please see TestRail user documentation here:
[General QA documentation for the platform](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/quality-assurance) 

TestRail:
https://dsvavsp.testrail.io/index.php?/dashboard
login: alexis@adhocteam.us
pswd: See OnePassword

Note: This is required for Staging Review before launch

**Comment by ericbuckley** [comment]
which environment should all these tests be performed on?

**Comment by ambikaroos** [comment]
@ericbuckley I believe the thinking with these test cases was that they'd be performed in staging, right @patrickvinograd ?
