### ISSUE TITLE
CT: Design documentation for Section 103

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#6836]
As a developer supporting Section 103 enhancements, I need to establish a design document so that all parties involved are on the same page with regard to technical design. 

## Assumptions
1. NA

## Acceptance Criteria: 
1. Proposed design for Section 103 has been documented on GitHub and linked to this story.

## Supporting Artifacts
1. The following information was received from the Education Benefits team regarding Section 103 
and the Comparison Tool: 
- Schools which have requirements in place additional to the provision of a COE, should be advised of the following:
    - Neither a school (or an approval authority on its behalf) are required to provide VA a weblink to their school website or specific language on their school website which identifies the “additional requirements.” Rather a note on the VA Comparison Tool will inform students to contact the school’s School Certifying Official to inquire about any additional requirements.
   - Despite the above, all requirements must be available to a student in written form upon request (either in a regularly updated catalogues or other reference material, or the school website).

**Comment by zurbergram** [comment]
See https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/data/Institutions_profile.csv

For UI/UX design, should be on an institution's profile page
