### ISSUE TITLE
VAOS log when jti can not be determined

### ISSUE THREAD

**Issue by kreek** [department-of-veterans-affairs/va.gov-team#6837]
We would presumably have the JTI from the request in most circumstances I would think. The only time it's absolutely necessary to get it from the response instead of the request is in the UserService call since there our request would not have a JTI.

**Comment by saneshark** [comment]
We would presumably have the JTI from the request in most circumstances I would think. The only time it's absolutely necessary to get it from the response instead of the request is in the UserService call since there our request would not have a JTI.

**Comment by lenaecb** [comment]
@saneshark to check in on this and potential close out

**Comment by lenaecb** [comment]
@grossb1 @saneshark - is this issue ready to be closed out? any testing we need?

**Comment by saneshark** [comment]
Funny you ask, it looks like the previous PR got closed without getting merged. @grossb1 is going to open a new PR and I'll approve and merge, but yeah this is ready to be closed as soon as the real PR is merged.

**Comment by saneshark** [comment]
Also I do not know why I parrotted what Alastair said up above. I think I meant to quote him and point out that even with UserService we would have it in the request, but it just wouldn't be in the header. Instead it would be in the request body.
