### ISSUE TITLE
[UX] 10-10 EZR Notifications: Discovery - Notifications for EZR

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#68379]
As a Veteran, I would like to be notified when I need to update my information so that I make sure the VA has accurate information on me and so that I ensure I get all of the benefits which I have earned. 

- [x] Desk Research: Do desk research to learn about what Veterans have said about updating info with notifications in past research
- [x] Comparative research: Look for examples of other systems that send notifications for Veterans to change/update information 
- [x] VA Notify/Vet Tech Team: Meet with teams working on notifications to better understand the work they're doing and get their input on how we could implement this
- [x] Determine what we will need to notify Veterans about (e,.g. financial info, private insurance, Medicare, etc.)
- [x] **Success: Create a Mural/visual for what we need to notify the Veteran about and our options for how we could do it.**

**Comment by katelyncai** [comment]
Started [documenting this work](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1698266698151/d82092b38107a883cc3975d9ea21deaf4fb0739a?sender=ube02cc3d1108083a94f75471) on a new discovery board in the EZR Mural space.
