### ISSUE TITLE
SOCKS access for [individual]

### ISSUE THREAD

**Issue by Sanjay-Gupta-VA** [department-of-veterans-affairs/va.gov-team#68371]
### Your Name

Sanjay Gupta

### Your Email

sanjay.gupta1@va.gov

### Your Role and Team

QA Engineer VA.gov on MR

### Product Manager (PM) name and email

Bryan Riley bryan.riley@va.gov

### Product Owner (PO) name and email

Bresha Lipscomb bresha.lipscomb@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDFLx9dhepX+B7c6qC3OSryzbdezix6y0yMQZgWl/wBRuF6AtbwsQzZMit4Eve2DXcXiVEx8cGv1WDLjGfDyYzSCTAsr5Hk3WgJOQaWWqDX77go3m1Has7OyUyAygMV5+BmuKw5VTq38hfo50tumpnM4pb4ElnxZn66ScsYjRddHb9cJln+a0uwraWeVZxsy8SHYMYBIBgOGUeCPxB58NwsduMTC6r7VxO1HtMmFJroqfhbMDy6mdknrLRirhBLE8vk5fAlcpvesPruPGxKlUbXdvapKXlMcj2H3ivB+bH/cN7Kn1I2m24UHWK8GKm98YyaL4Q0/sPIvXTNNaNkuPkxcRsacBz2vNzMFGPETMiQARbvI+P9BwV75gyWgtwABFyG3T+WFBkGEdsvnKrIWoh3hgcbHVQIimKaN7KosoXGgg7VC/sj9h2FgXsuoVmVzuOB+RnyqWhRNZnLdOZN+VXeyNrBPu20cJDE2vjMQSh4HJwGq0woCBqbN8oezjDdoTk= sguptahe@he-lp-7B3L533

### E-QIP Transmittal Confirmation

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/121257973/1c2adebc-8e4d-462b-9c4d-3265e65ad378)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by hgbarreto** [comment]
Access granted ✅

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Reach out in #vfs-platform-support if you have any trouble.
