### ISSUE TITLE
Add unit test coverage for CanceledAppointmentsList.jsx

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#68387]
## Description
Add unit test coverage for `CanceledAppointmentsList.jsx`

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFp3QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ba968ab647c1b7f57e3aefab7eb1a5d5081f9092/Screenshot%202023-10-25%20at%201.35.03%20PM.png)

---

## Acceptance Criteria
- [ ] file coverage for Branches, functions, lines and statements is 100%

## Definition of Done
- [ ] All acceptance criteria are met

**Comment by JunTaoLuo** [comment]
We no longer need to add tests since the functionality has been removed in https://github.com/department-of-veterans-affairs/vets-website/pull/29383
