### ISSUE TITLE
Copy help from Lighthouse API for connected accounts

### ISSUE THREAD

**Issue by careyotto** [department-of-veterans-affairs/va.gov-team#6838]
### Background
The Lighthouse API team is working with the Authenticated Experience team on improvements to the Connected Accounts user experience, while they do their Profile 2.0 work. As part of this work, we've identified a strong need for FAQs and a list of third-party apps and sites that Veterans can connect their personal data to.

We need help from the Public Websites team to make this happen.

Would like:
- IA help for URLs and deciding whether this content should be 1 URL or 2.
- Copy help to review content
- Analytics on URLs see how users are using these new pages

* **Is the request related to a VA.gov tool? Provide a brief description of the tool or functionality:**  
   * Connected Accounts is an area of a Veteran's account settings on VA.gov. With apps/sites that use certain Lighthouse APIs, a Veteran can connect some of their VA data to the app using an OAuth flow initiated by the app. The only way a Veteran can revoke this access is by logging into VA.gov, finding their Connected Accounts area in their account settings, and disconnecting the app. 

   * Individual apps can use a Veteran's data in different ways. Some just look at it, some copy it over to their own servers or the Veteran's device, etc. FAQs would be a great way to help a Veteran understand the values and risks of connecting their account, what to do if they feel unsure about something they see, instructions on how to revoke their consent, etc.

   * Having a public list of apps that a Veteran can connect to would help them learn about these resources that are available to them and also be a one-stop show for each apps privacy policy, terms of service, etc. 

* **Provide links to any available collateral: product briefs/outlines, wireframes, prototypes, user research synthesis:** 
   * [Design for Connected Accounts (WIP) ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6731)
   * [Previous FAQ concept for Connected Accounts that was never launched. ](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/15871)The needs and context of this content have expanded since this ticket was closed. Would like to use this as a starting point.
   * Wireframes/prototypes coming. Would like to start a conversation with your team first.
   * staging.va.gov use test uesr +1 to see the current experience

### Request Type
*Select all applicable and provide details behind your request* 

- [x] **Content support for authenticated app/tool.** Note: Support is provided only for VSA apps teams that do not have its own dedicated content writer. In addition to the generic information above, please share:
   * Word document with draft if available, or link to the URL where the draft content appears:
      * < link > TBD
   * Provide design context: (Example: Is this content in a user flow, an in-line error message, tool tip, field label?)
      * < design context > See links above
   * Scope: How many screens? (Or messages, etc.) 
      * < scope > FAQ page from previous ticket + a few more questions added to this
      * < scope > Page that shows a list of available apps (Design/Copy TBD). Once structure is agreed upon, we need this page to be easily updatable by the Lighthouse API team as we onboard new API Consumers.
     
- [x] **Content support for a static public website page**
   * Is this to update existing static content? 
      * < y/n > No
   * Does this need a new static tool landing page? (The content team may propose a different approach in consultation with IA.)
      * < y/n > Not sure what you are asking. 
   * Provide a list of URL/s that need to be reviewed or updated. 
      * < URL list > N/A. There were previous URLs decided upon in ticket above, but they were never built. Not sure why.
   * If it's a small copy section, list what the new info should be and what it is replacing.
      * < list of new info > Working on this.

- [ ] **New URL or Redirect Requests**
   * Have you vetted this request by the VSP IA team?
      * < y/n. if not, submit URL and redirect requests first to @ Mikki Northuis on VSP IA.) Lighthouse worked with Mikki on the old FAQ ticket that never launched. Will loop them in that this has resurfaced now.
      
   
- [ ] **Implementation of REACT sign in widgets**
   * Full spec including different states and behaviors
      * < link to spec >
     
- [ ] **Other**
   * Please describe in detail
      

### Desired/target implementation date
*What is the ETA for the launch or date when request needs to be completed (for instance, for a user research session or eBenefits migration)? Our team's capacity will determine which sprint the work falls into.*

* <Desired/target implementation date> Authenticated Experience is targeting early May for Profile 2.0 launch and needs these URLs for that. Please coordinate with @mshea0606 and cc @careyotto for exact details.

### Requestor info
*Indicate what team and who the primary contacts are on your team* 
- Team name: Lighthouse API
- DEPO product owner: Dave Mazik
- UX Lead: Carey Otto @careyotto 
- Product/team Slack channel: DSVA Slack #api-coordination (this isn't used much because Lighthouse has it's own Slack workspace)

Lighthouse coordinating with Authenticated Experience for this. They will not design/own the FAQ and app list designs, but they will like to them from the account pages.
- Team name: Authenticated Experience
- DEPO product owner: Samara Strauss
- Product Manager: Matt Shea @mshea0606 
- Designer: Tressa Furner
- Product/team Slack channel: DSVA Slack Workspace #vsa-authd-exp

--- 
#### Acceptance Criteria
- [x] follow-up with requestor to address any lingering questions/concerns
- [x] If necessary, create epic/tickets as needed for the Public Websites team to implement

#### Definition of Done
* Request ticket is closed and implementation tickets created as needed

**Comment by MickinSahni** [comment]
Hey @lunascoop can you take a look at this and determine what if anything we need to do?

**Comment by lunascoop** [comment]
It seems that the URL has been determined per this ticket [#15901](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/15901). It is https://www.va.gov/connected-accounts-faq/

Hi @careyotto can we schedule some time to review the design and discuss the expanding FAQ content? Perhaps @mnorthuis should be included for IA recommendations for this and the third party apps list.

**Comment by careyotto** [comment]
@lunascoop Absolutely! My calendar is up to date, west coast hours.
carey.otto@adhocteam.us

**Comment by careyotto** [comment]
@lunascoop To clarify, the URL for the FAQ was determined in  [#15901](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/15901), but it was never implemented and our use case has changed since then.

I would also like copy-edit help with the new FAQ content.

Additionally, we want to add a third-party app directory URL and need IA help for the URL.

**Comment by lunascoop** [comment]
@careyotto I am unable to view your calendar. I am trying to find it from my GovernmentCIO email account scooper@governmentcio.com.

**Comment by careyotto** [comment]
@lunascoop - sorry about that. calendar should be visible now.

**Comment by lunascoop** [comment]
@careyotto @mnorthuis I've reviewed both calendars and will tentatively schedule a kickoff meeting for noon EST tomorrow. Let me know if that won't work.

**Comment by careyotto** [comment]
App directory rough draft design: 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/6866

FAQ rough draft copy, design to mimic sign-in-faqs:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/6864

Authenticated Experience EPIC around connected accounts:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/6814

cc: @lunascoop @mnorthuis

**Comment by MickinSahni** [comment]
2020-03-26 PW Standup
- adding to sprint 18 (unplanned)

**Comment by MickinSahni** [comment]
2020-03-27 PW Standup
- Reviewing copy/documentation and making edits
- Updated title to reflect content-only focus (IA request in another ticket for Mikki to vet)
- We'll close out this ticket once we have follow-on ticket(s) for us to implement content changes **if necessary**. Otherwise this ticket will be the end of PW involvement.

**Comment by MickinSahni** [comment]
2020-03-30 PW Standup
- Sending content draft for Peggy to review
- May need to alter the AC if we're able to wrap up our content work this sprint (otherwise, AC will remain to create any subsequent tickets we'll need)

**Comment by lunascoop** [comment]
Hi @peggygannon here is my review of the lighthouse FAQ copy.
[Connected.apps.FAQs.for.Profile.2.0_SC.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4411330/Connected.apps.FAQs.for.Profile.2.0_SC.docx)

**Comment by careyotto** [comment]
**Re: removal of: _"Third-party services are created by developers that aren’t VA."_**
From user comments about the launch of Apple's health app, there seems to be confusion from some Veterans about who makes these apps. Comments like, "Why didn't the VA design for android?", etc. I'm not sure if we need to be explicit that third-party doesn't equal VA, but maybe it would be in best interests to. What are your thoughts?

**Re: removal of _"It is up to each app developer, which device and operating system they support."_** 
Same comment as above. Probably okay to remove this, was just trying to mitigate the "why doesn't VA support XXX" concerns with this sentence.

**Comment by MickinSahni** [comment]
2020-04-01 PW Standup
- Selina dropped doc here and shared with Peggy, waiting for input

**Comment by lunascoop** [comment]
> **Re: removal of: _"Third-party services are created by developers that aren’t VA."_**
> From user comments about the launch of Apple's health app, there seems to be confusion from some Veterans about who makes these apps. Comments like, "Why didn't the VA design for android?", etc. I'm not sure if we need to be explicit that third-party doesn't equal VA, but maybe it would be in best interests to. What are your thoughts?
> 
> **Re: removal of _"It is up to each app developer, which device and operating system they support."_**
> Same comment as above. Probably okay to remove this, was just trying to mitigate the "why doesn't VA support XXX" concerns with this sentence.

@careyotto I updated those two issues in the attached doc.
[Connected.apps.FAQs.for.Profile.2.0_SC.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4422949/Connected.apps.FAQs.for.Profile.2.0_SC.docx)

**Comment by MickinSahni** [comment]
2020-04-03 PW Standup
- Updated copy per Carey's feedback and waiting for input from Peggy and/or Carey

**Comment by MickinSahni** [comment]
2020-04-06 PW Standup
- removing from this sprint into Ready until finalized

**Comment by peggygannon** [comment]
Hello @lunascoop @careyotto  Here are some content recommendations from me. Let me know if you want to discuss/review together. 

Take 2: Sorry, I can't upload this doc to Zenhub (says it's too big). I've uploaded the doc with my recommendations to Selina via slack.

**Comment by lunascoop** [comment]
[Connected.apps.FAQs.for.Profile.2.0_SC.pgreview.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4446895/Connected.apps.FAQs.for.Profile.2.0_SC.pgreview.docx)
Uploading on behalf of @peggygannon

**Comment by careyotto** [comment]
Thank you, @peggygannon and @lunascoop ! Answers to your questions and comments below:

`Get answers to common question about third-party connected websites and applications.  `
I've never heard it termed "third-party connected websites..." before and am not sure its a real thing. It is more common to see either "connected third-party websites and applications" or "third-party websites and applications you can connect to."

You have a comment in `What are the benefits of connecting to a third-party app?` that you suggest removing this question because it is not Veteran facing language. Can you explain what you mean here? I don't understand.

Regarding comment about "this list" link on `How do I connect my VA data to an app?` - was thinking that would like back to the app directory page that lists all the apps available. At the bottom of that would be an embedded video tutorial.

`I'm a developer and want to build an app for Veterans. Where do I start?`
Your comment to move it out makes sense, trust your content org on this one. We have evidence of Veterans requesting access to our APIs through the developer portal and the working assumption is they might also be software developers. So we wanted to address the question here.

`My app’s health records are inaccurate or out ofdate. What should I do?`
- might have a typo between "of" and "date" in the question
- I'm not sure where I got that phone number from -- I copied the entire sentence from somewhere. Let me verify with Lighthouse customer support specialist on this one.

**Comment by careyotto** [comment]
@peggygannon So glad you asked this question. With regards to:

> **Is your data inaccurate?** 
> To change your information, please call MyVA311 for help: 844-698-2311 (TTY: 711). Or visit a VA facility near you and ask a staff member for help.

**MyVA311** is a general help line for Veterans. The actual number is 1-844-MYVA311 (698-2311). I don't know if the TTY:711 bit is accurate, but assuming so. Agree with you that maybe we can phrase this to be less confusing. Here is more info on the program, if you're interested.
https://www.va.gov/COMMUNITYCARE/docs/news/MyVA311-FAQs.pdf

**Comment by lunascoop** [comment]
Content weekly discussion 04/20/2020

Re: the FAQs page: Further discussion is needed to determine if this page should live behind the authenticated experience or unauthenticated (public). The content of the page currently includes topics/questions that are high-level and suitable for general audiences, and app developers who do not have logon credentials for authentication. As for the app developer-based questions, they do not seem appropriate for the FAQ page (per @peggygannon @mnorthuis), and may be suited for the Lighthouse page or a Learning Center-based page that is in the development stages.

A meeting w/ @DanielleThierryUSDSVA @careyotto @peggygannon @mnorthuis @lunascoop is needed to discuss this further.

**Comment by careyotto** [comment]
Also, FAQ will be linked to from the App Directory, which is a public page.

**Comment by peggygannon** [comment]
@lunascoop Hello! Can you upload the latest version of the FAQ content, that includes Carey's responses to our earlier edits? 

Per our sync meeting yesterday, we agreed that I would do another pass of this. 

cc @DanielleThierryUSDSVA

**Comment by lunascoop** [comment]
Hi @peggygannon here's an updated draft based on yesterday's meeting and Carey's above feedback/explanation.
[Connected.apps.FAQs.for.Profile.2.0_SC.pgreview.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4624556/Connected.apps.FAQs.for.Profile.2.0_SC.pgreview.docx)

**Comment by DanielleThierryUSDSVA** [comment]
**Note:** Converting this to an epic and adding https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/10207 as an issue to capture current work.

**Comment by peggygannon** [comment]
@DanielleThierryUSDSVA @lunascoop can this issue be closed, since work is now being tracked in 10207?

**Comment by DanielleThierryUSDSVA** [comment]
@peggygannon Yes! Thank you.
