### ISSUE TITLE
Add unit test coverage for BackendAppointmentServiceAlert.jsx

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#68386]
## Description
Add unit test coverage for `BackendAppointmentServiceAlert.jsx`

[Uploading... Screenshot 2023-10-25 at 1.32.16 PM.png]

---

## Acceptance Criteria
- [ ] file coverage for Branches, functions, lines and statements is 100%

## Definition of Done
- [ ] All acceptance criteria are met

**Comment by JunTaoLuo** [comment]
Closed as obsolete in favor of the new approach in https://github.com/department-of-veterans-affairs/va.gov-team/issues/89844.
