### ISSUE TITLE
[Data] Alerts & Monitoring - Analyze 10/24/23 Errors

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#68395]
- [x] Determine why we say the spike in health check failures from the FwdProxy around 2100 on 10/24/23
- [x] Determine why there are differences in time signatures
- [x] Propose any fixes 
- [ ] **Success: We know what happened and what to do about it**

**Comment by luis-simauchi** [comment]
J. Faulker:
"seeing some DB connection errors right around midnight, that is probably what it was, looking at it now"

ConnectionDeadSQLException:
		IO Error: Got minus one from a read call

**Comment by luis-simauchi** [comment]
roughly 25 instances of 503s calls that got impacted back that, and it was b/w 00:00 and 00:07

**Comment by luis-simauchi** [comment]
failed connections to the oracle RDS for sure.
timing feels possibly like an automated update on the DB side, though now just wildly guessing. Also observed — though never confirmed by AWS support — what look like brief network outages b/w things even in the same VPC.

perhaps a kind of rolling update maybe, it wasn't totally down but there is surely a large group of failed connects in about a 5 min period, but other connections still working at same time.

**Comment by luis-simauchi** [comment]
J. Faulker:
"gonna open aws support ticket to see if they can explain this to me if they were doing something last night"

**Comment by luis-simauchi** [comment]
follow up; 
The spike in errors came back around the same time last night as well
[Uploading... DD_10_26_HCA_controller.PNG]

**Comment by luis-simauchi** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXQzQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e76c1504c243fbebb96f3f6283ffe18abaf7a96e/DD_10_26_HCA_controller.PNG)
