### ISSUE TITLE
Both tools: Draft FAQ resources and support page

### ISSUE THREAD

**Issue by strelichl** [department-of-veterans-affairs/va.gov-team#68394]
### Background
The accredited representation management (ARM) team is designing these new products:

- **Check your representative (CYR) widget:** This will help Veterans check if they have an accredited representative.
- **Find a representative (FAR) tool:** This will help Veterans find attorneys, claims agents, and Veteran Service Officers (VSO) that serve as accredited representatives. After using this tool, Veterans will need to contact the attorney, claims agent, or VSO to ask if they're available and willing to representative them.
- **Appoint a representative (AAR) tool:** This will help Veterans appoint an attorney, claims agent, or VSO as their accredited representative by pre-filling their Form 21-22 or Form 21-22a. After using this tool, Veterans will need to print and sign their form. Then the accredited representative will need to sign and submit the form online, by mail, or in person.

The ARM team is launching the FAR tool (and this FAQ page) before the AAR tool and CYR widget.

### Resources
- [Draft FAQ page](https://prod.cms.va.gov/resources/va-accredited-representative-faqs) (Drupal)
- [Content source of truth folder](https://dvagov.sharepoint.com/:f:/s/SitewideCAIA/EpKqFTllvlxOkDwz2iFgveAB9PjkKVIrJu_TUAkQPbsU0g?e=F7yosj) (SharePoint)

### Deliverable: FAQ page
We need to publish the FAQ page on the same day as the FAR tool landing page.

- [x] AP: Draft page design
- [x] AP: Add page to Drupal
- [x] KF: Edit
- [x] AP: Share Drupal preview with Beth
- [x] BP: Review
- [x] AP: Incorporate edits
- [x] AP: Share Drupal preview with SMEs
- [x] AP: Incorporate edits
- [x] AP: Share Drupal preview with product team
- [x] MZ / ST: Copyedit and publish

## Criteria
- [x] The FAQ page is published

**Comment by aprocik1** [comment]
@katherine-fung, I moved our FAQ content into Drupal, so we can start to visualize this page. Here's the [link](https://prod.cms.va.gov/resources/va-accredited-representative-and-vso-faqs).

I don't have a preference if you want to make edits in Drupal or the Google document. Thanks for working on this with me!

**Comment by katherine-fung** [comment]
Hey @aprocik1, I've made a few minor tweaks, and updated the Drupal preview with the info from the SME about how to end representation. 

http://preview-prod.vfs.va.gov/preview?nodeId=63990

**Comment by aprocik1** [comment]
@bethpotts, here's the Drupal [backend](https://prod.cms.va.gov/resources/va-accredited-representative-and-vso-faqs) and [preview](https://preview-prod.vfs.va.gov/preview?nodeId=63990) for your review. Feel free to make direct edits in Drupal, or we can discuss them in a meeting if you'd prefer. Thanks - all feedback is welcome and appreciated!

**Comment by jfinnerty13** [comment]
Some questions that came up from users in our [latest study](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/accredited-representation-management/research/2024-01-ARM-appointarep-usertest) @aprocik1 (final report coming)

- What’s the difference between representatives and which option is best for me?
- If I assign a new representative do I now have two assigned to me?
- What situations would I want to replace my representative?
- Why aren’t the 21-22 and 21-22a a single form?
- If you self-filed, does your claim transfer to your representative when you appoint them?
- Is this form (the 21-22) a power of attorney?

**Comment by aprocik1** [comment]
Note: We're hoping for SME feedback by EOD today 2/16. The goal is to publish this page alongside the launch of the FAR landing page and tool.

**Comment by aprocik1** [comment]
Update: I received feedback from Jonathan Taylor and made updates to content in this document: https://dvagov.sharepoint.com/:w:/s/SitewideCAIA/EWIryLeYYUNLoYZp6Eoc9HcBYkSkZzLQo8gCKfBk0weXDw?e=ikVU9l

I'll update Drupal tomorrow and share the preview with the product team.

**Comment by aprocik1** [comment]
Update: We're holding on publishing this page due to SME feedback. We need to review the information from SMEs before working through another round of reviews and revisions. I've updated relevant CAIA team members, the product team, and SMEs about this change in plans.

**Comment by aprocik1** [comment]
@megzehn, this page is ready for you to copyedit. I'm not expecting anymore feedback from the product team or SMEs, but I want to wait a few more days for any final recommendations. Do you have time at the end of this week or early next week to publish this page?

Here's the Drupal link: https://prod.cms.va.gov/resources/va-accredited-representative-faqs

**Comment by megzehn** [comment]
Update: I'm holding on a copy edit until @aprocik1 aligns with stakeholders on some more changes.

**Comment by aprocik1** [comment]
@megzehn, this page is ready for you to copyedit. I'm not expecting anymore feedback from the product team or SMEs, but I want to wait a few more days for any final recommendations.

Do you have time to copyedit this page? And then I'll follow up with the greenlight on Thursday for you to publish it?

Here's the Drupal link: https://prod.cms.va.gov/resources/va-accredited-representative-faqs

**Comment by megzehn** [comment]
FAQ page is live.

I also shared this with the support team since it's a new R&S page and added it under the Disability section on the R&S landing page. Moving to validate!
