### ISSUE TITLE
[Call Center] Test Account for Call Center Agents

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#684]
## User Story
As a Call Center agent, I need access to a VA.gov test account so I can accurately guide a user who is on VA.gov and trying to accomplish a task.

## Goal
Provide WHH agents with test accounts so they can provide better service to the veterans and users calling in and asking for help. 

## Acceptance Criteria
- [ ] WHH agents have access to a test account(s) that reflect what a veteran would see if they were signed into their LOA3 VA.gov account.
- [ ] WHH agents have the information necessary to sign in and use these test accounts. 

## Definition of Done
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by joanneesteban** [comment]
Try posting in #vfs-platform support.

**Comment by joanneesteban** [comment]
Chante to follow up with David Bao on best solution.

**Comment by clantosswett** [comment]
### Top Level Requirements for VA.gov Test Accounts for Call Center Agents

1. *Environment reflects the functionality and navigation on production:* Agents will be using these test accounts to help users navigate VA.gov tools. If there is discrepancy  between what an agent sees and what the user sees, this will cause problems.
2. *There should be at least one test account for each _type_ of VA.gov account:* The VA.gov experience differs based on the type of account a user has. Agents should have the ability to sign into different versions of VA.gov accounts based on the situation of the user they are assisting. Here is a list of the types of accounts needed:

_DS Logon_
-LOA1 Account
-LOA3 Account with successful MVI records matching
-LOA3 Account with unsuccessful MVI records matching

_My HealtheVet_
-LOA1 Account
-LOA3 Account with successful MVI records matching
-LOA3 Account with unsuccessful MVI records matching

_ID.me_
-LOA1 Account
-LOA3 Account with successful MVI records matching
-LOA3 Account with unsuccessful MVI records matching

3. *A set of test accounts for each agent is not necessary:* So long as there is no impact on functionality if multiple people are using the same test account, there is not a need to create separate test accounts for each agent. We will also encourage agents to create their own test accounts, realizing that their account might not reflect what a user is looking at.

**Comment by clantosswett** [comment]
@leahbannon and @nedierecel  I tried to capture what is needed for call center test accounts. Let me know if you have any questions or anything else you might want to add to this. Thanks!

**Comment by joanneesteban** [comment]
Waiting on DSVA to determine how to move forward.
