### ISSUE TITLE
Add unit test coverage for UpcomingAppointmentsList.jsx

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#68402]
## Description
Add unit test coverage for `UpcomingAppointmentsList.jsx`

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmx3QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5022004aed4f2af00c54a2ba58769947d4c19557/Screenshot%202023-10-25%20at%201.55.05%20PM.png)

---

## Acceptance Criteria
- [ ] file coverage for Branches, functions, lines and statements is 100%

## Definition of Done
- [ ] All acceptance criteria are met

**Comment by ryanshaw** [comment]
Closing this, it will be handled in https://github.com/department-of-veterans-affairs/va.gov-team/issues/55085
