### ISSUE TITLE
Add unit test coverage for ScheduleNewAppointment.jsx

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#68401]
## Description
Add unit test coverage for `ScheduleNewAppointment.jsx`

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmR3QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c8f23c3198fe4bfedb3b37c8c05c91000ff717ef/Screenshot%202023-10-25%20at%201.54.12%20PM.png)

---

## Acceptance Criteria
- [ ] file coverage for Branches, functions, lines and statements is 100%

## Definition of Done
- [ ] All acceptance criteria are met

**Comment by JunTaoLuo** [comment]
Closed as obsolete in favor of the new approach in https://github.com/department-of-veterans-affairs/va.gov-team/issues/89844.
