### ISSUE TITLE
SOCKS access for Emily Gullo

### ISSUE THREAD

**Issue by emily-gullo** [department-of-veterans-affairs/va.gov-team#68418]
### Your Name

Emily Gullo

### Your Email

emily.gullo@adhocteam.us

### Your Role and Team

Lead Engineer on Fast Track Claims

### Product Manager (PM) name and email

Stephen Smythe stephen.smythe@agile6.com

### Product Owner (PO) name and email

Zach Goldfine zachary.goldfine@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDLgOEQBbE9YNPfvm1i/L/BVKZldkCPkOuiYozAE1i+H4jr81NvnYSAXgXczkAR4+wVKhx/jnrBhSTPONsiDmzcINdplfwxQ0lHXpKG0SOgpNwHu7V31xBmjC+uYhS5E6XdusrO7PZAFdRw7QS2niMCjNt+uECT3oVwnUb/oZfRkeeTis9NqYfcBMeZX0hI0QwRwSz+LPKOI9MxZdC7eQhmdZM+BKauQLkcmOnztU8PnCpJjuk+8Qu9gDVmv9+QGiT+BiqzfyrXga8XQoyh5/EmvNSkxebbiiQvAPW0VYDOVNVZc/6YDgTWPOX62g0yvkAs0kvoC8CPY5qCDb51vRlzxiWHx6I6IKJ1S2DiEiaOhk5xTRat+JXNF+YcNRF5hfwWI7DEXxosrZLfjqN0nMEAp2/5zjLi+ZovVw6CFjj6pTJ1m8OAjKt+KG5ayPedNRDpVwjt+Dx7LXcrSP6+5PIHhio8C26/PbDVaYIFYko9BTa8CtSup4d3LVxsc/JJAHc= emily.gullo@emilygullo-MQ4FL94GH3

### E-QIP Transmittal Confirmation

<img width="1114" alt="Screenshot 2023-10-26 at 8 32 25 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/148817676/2ad4dbf6-ed8f-4ce6-b38d-8b49547e4cbd">

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by hgbarreto** [comment]
@emily-gullo Access granted ✅
