### ISSUE TITLE
Access for Oksana Cyrwus

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-team#6842]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your name.
   > Oksana Cyrwus
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Sr. Software Engineer on the AgileSix cms team.
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Internal%20Tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC+mM7zEJZZNEx5ZYHyjMEga98voe3PjFEO45glKRWf7DTEWKuJIY3dBi0aavklF/ZyRH72jd6fKnLnFwxbLir8dwVSLd8OooYUEVkUZ1ysBKftXsMurQxGAL8dnlMojCeDTsz3ioNUOg3i7ojjQznJnxyR+aEjqDos+K985tC9gHDw4t2kKX0xm+PDjneTyGmn0qXJQ+oL9QpTnQIjDODdrD3Ns0afC+nHpAEXw4JSa6/QwSqQmzFNWMTVlNk4ih++m+ndPij4pQVmRSfEzg5g9Yi2lvAeIuClSsZftlf34OWudCmXHIdl+5l5m668cPElJkqDOUeQQriQuupERvsSrxrwxqUVfNa5yG/okEqXlfrqphs+qDGbdlidaf3MrHoSFWGIWZa6RQs0oae5XvPuBhH73nGiVpjthdHgdI20IxHX0zykTQ3C4Jqb6AlZ6ka52yhCUbfE9807U9oN/Fr1qOMHudf9Fv9UJPSOZn4Nuze5LpzgCh6eitkAFwO+Ekbu+miZVYI7GXT42E9V7aVZqtA01vgZKxzhXQA+UM+igemiMENdyuElZzdwmRYa0gNq91F/Zv+nJvSye+H1LDTpNcQMHVzInIzAnCYit97lFbNHbe7foStHSukoWeb39qiF22c+nsh0E7GKcCmShIYb7mKp92i/A7alfjZ4QpgZ1w== oksana.cyrwus@agile6.com
```

- [Grant AWS Console access?]
  > NO
  >  Please give a brief description for why you are requesting AWS access.

**Comment by oksana-c** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by jbritt1** [comment]
SOCKS access granted. @oksana-c, please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.

**Comment by oksana-c** [comment]
thank you @jbritt1
