### ISSUE TITLE
Populate Ask VA entries in spreadsheet/service catalog/monitors

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/va.gov-team#68420]
Auditing all API routes surface an additional tier 1 service - Ask VA. 

It's been added to the CY Feature spreadsheet, and a service catalog has been created but it needs the following:

- [ ] A Datadog team defined (and updated in service catalog entry)
- [ ] A Dashboard
- [ ] All three expected tier 1 monitors.

**Comment by mattpointzxer0** [comment]
Added to spreadsheet as Tier 2

**Comment by patrickvinograd** [comment]
Ask VA was demoted to tier 2 - it's in the service catalog but its monitors can be set up along with all other tier 2 features
