### ISSUE TITLE
Strategy spike: UX strategy for links below the boxes (esp. non-VAgov)

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#68426]
### User story

As an authenticated user, I want the non-tool links on the MHV landing page to be few, within the MHV on VAgov experience when possible, and task-oriented, so that I am able to learn about and increase my engagement with VA services with minimal cognitive load.

As a Cartographer, I want to limit the paths that take users back to MHV Classic, so that Veterans are more likely to adopt VA.gov.

As a Cartographer, I want to reduce the number of links on the landing page, so that Veterans find it easier to complete the task they need to do with lower cognitive load.

### Notes

- Per Kaitlin [thread](https://dsva.slack.com/archives/C0581MN69TJ/p1720807967522709?thread_ts=1720807561.930489&cid=C0581MN69TJ), things to understand about each link:
1) the importance of the content
2) are there plans to migrate that content to VAgov?
3) is there similar content that lives on VAgov that we should be linking to instead?
- also consider:
  - does it fit the landing page's purpose of task enablement?
  - in a way, analytics are a way for users to tell us whether a link fits the LP's purpose or not(?)
- Note that DD actions are not available for these links as of 7/12/24; use GA4 for usage data (or check #88256 for the DD fix)

## Acceptance criteria

- Documented current usage the non-tool links area in the current landing page, using analytics data as appropriate
- Categorized links based on criteria that would be useful for organizing links and/or identifying for removal from the landing page (e.g., see Kaitlin criteria above)
- Share with Kaitlin for feedback
- Ticketed next step as appropriate

**Comment by MikeC-A6** [comment]
@wesrowe The user story sort of implies a solution for non-tool links. "_based on what VA knows about me_" suggests to me that we have already landed on a strategy of personalized links, which I don't think we have landed on that.

**Comment by wesrowe** [comment]
Dependency discussed in Sprint 18 planning: dependency on collecting some GA data after #66723 is merged.

**Comment by wesrowe** [comment]
Prioritization note: in the first few days of data (12/1-4, includes a weekend) about .06% of landing page visitors clicked a link in the first column of R&S links (health benefits).

**Comment by wesrowe** [comment]
Closing this due to its vagueness. The topic should come up again.

**Comment by katbrinkley** [comment]
[Link to analysis spreadsheet](https://docs.google.com/spreadsheets/d/1yyRCN3ILcjCIUKu4MaNXdu2Thq4rmtH2FMdy5Ck_oBQ/edit?usp=sharing)

**Comment by katbrinkley** [comment]
Update: Reviewed by @fmccaf1 and @jonathanjnelson, added updates from feedback. Closing.
