### ISSUE TITLE
Discovery spike: replace outbound links on landing page with destinations in modernized VAgov

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#68425]
### User story
> _Describe the audience/user and value / outcome desired._

As an authenticated user of the MHV Landing Page, I want links to keep me within the modernized VAgov website when possible so that I am assured of an experience that is coordinated, consistent, and ready for the sunsetting of the MHV National Portal.

## Acceptance criteria

- 

## Tasks

- [ ]

**Comment by MikeC-A6** [comment]
@wesrowe Suggested story revision:
As a Cartography team member, I want to understand if there are any constraints to removing links from the MHV Landing page that route a user outside of the VA.gov ecosystem so that we can make decisions as to if and when we do this.

**Comment by wesrowe** [comment]
@MikeC-A6 – Skipping ahead a bit, we might not be able to identify constraints prior to taking an action and seeing what happens.  I could pitch a thin-slice, empirical approach to this as: identify a link we think most likely to need changing, propose it, see if constraints emerge. We can discuss further here or in refinement.

**Comment by wesrowe** [comment]
Dupe/overlap to #68426. Closing.
