### ISSUE TITLE
Create Repo for Proofing Application

### ISSUE THREAD

**Issue by porta-antiporta** [department-of-veterans-affairs/va.gov-team#68452]
# Context
Given we will consider a separate experience, application from VA.gov, need our own repository for our work.

# Acceptance Criteria
- [x] Public repo created in VA GH org
- [x] Write Access permissions sorted 
- [x] Skeleton Hello world application from LHDI example in repo

**Comment by rdvyas** [comment]
Created repo in VA GH here:
https://github.com/orgs/department-of-veterans-affairs/teams/vfs-in-person-identity-proofing

**Comment by rdvyas** [comment]
I have reviewed this with the Dev team and they concur with my changes. 

Closing ticket.
