### ISSUE TITLE
SOCKS access for [individual]

### ISSUE THREAD

**Issue by Khoa-V-Nguyen** [department-of-veterans-affairs/va.gov-team#68460]
### Your Name

Khoa Nguyen

### Your Email

khoa.nguyen@oddball.io

### Your Role and Team

Backend Engineer on AskVA

### Product Manager (PM) name and email

[ruchi.shah@thoughtworks.com](ruchi.shah@thoughtworks.com)

### Product Owner (PO) name and email

[becky.phung@va.gov](mailto:becky.phung@va.gov)

### Access Type Requesting

developers

### Public SSH Key
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDEvVccQt5sv7aAeEOe+PKKAhoOmXvL8cwjuFMp3HLdt+fjlYyf0Ra8PJACVeZTibS1sDj12CPVGl+LPFL+DB6mv+0qVvYwyoBHDk4C+x37qQkO6nELK9+SExGR+AByyBlB4Xfo18+BBPVUuDH+k6rd0DTTj5yKyjEmFVhx1YH7cGqZDuIK15BEA7LpMo7xCwcdoTbWybPekqfsqZ/RXyBsfftnMYJGrFQmGx3DtiV3luySyWvHn797vqkCPBsedJz86XTelgph51cx9jqs6QiOtZCArUe7Q7f37g/H1bV8kTbvM4UIPbPYtSdSrK+NRJlQbwhjbXw+1qhS+lt1bczF7mvGXAbod1MTPtWIJS3CSn0XAjKCORLORclrQ5nY6IvYOCxi9HBBKo692ly4Jq2J7v6DOaWq342pAFGAVM9ur+pRsNphTHOQ5e+IRPGqOiQT0M/eOQ8b6fP3qleNh2P/ufedlYUhd6fRVzTi+DI7M1AWUsVWbAto2XIwAccXMMs= omegaeye@Khoas-Air
```
### E-QIP Transmittal Confirmation

<img width="1037" alt="Screenshot 2023-10-26 at 10 38 39 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/134089461/474d9060-ad08-4e95-9d97-216077434d41">

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by hgbarreto** [comment]
@Khoa-V-Nguyen Access granted ✅

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Reach out in #vfs-platform-support if you have any trouble.
