### ISSUE TITLE
Add "prompt" options SiS `/authorize` flow

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#68467]
## Issue Description
- In order to support new SiS clients and non-end user authentications, the SiS `/authorize` flow must be updated to accommodate different "prompt" options. `login`, forcing end-user authentication, will remain the default behavior of SiS, other prompt options will include assuming a user is already authenticated in order to generate a new auth on behalf of their client. 
- [LucidChart diagrams](https://lucid.app/lucidchart/019651c5-ed2b-498f-b86c-82e9cd6e64a6/edit?invitationId=inv_3e97d411-9ae2-4fe3-b39c-efc7aee513e2&page=0_0#)

---
## Spike Tasks/Research
- [ ] What is preferred OpenID way to create new session from `prompt=none` auth?
- [ ] What object should `/authorize` take to confirm user is already authed?
  - `vagov_access_token`, `vagov_refresh_token`, or some new token
- [ ] How do logouts work with auto-auth logout?
- [ ] How does login.gov log out (requires end user to accept prompt) work with auto-auth logout?
- [ ] How do we prevent 'revoke_all' from removing mobile sessions when logging out of web?
  - field on OAuthSession, `sso_enabled` - sessions without wouldn't be auto-logged out 

## SiS Update Tasks
- [ ] change SiS /authorize to accept 'prompt param'
 - [ ] login - default, user must log in to authenticate
 - [ ] none - assumes user is already authenticated, use access/refresh token to "piggyback" log in
 - [ ] consent - prompts end user for consent before a new auth for the client is created

**Comment by bosawt** [comment]
I created an epic and copied these to ciekts: https://app.zenhub.com/workspaces/identity-5f5bab705a94c9001ba33734/issues/gh/department-of-veterans-affairs/va.gov-team/68498

So I'm gonna close this
