### ISSUE TITLE
DOTS request URL is outdated on Request access to tools

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/va.gov-team#68470]
### Description

On the page about requesting access to tools, the link to "DOTS request" is linking to the obsolete max.gov JIRA site. The new DOTS service desk URL is https://jira.devops.va.gov/servicedesk/customer/portal/1

This is definitely the case for the "requesting access to Mural" instructions, but that entire page should be scrubbed for references to the old DOTS request site. 

### Relevant URLs
https://depo-platform-documentation.scrollhelp.site/getting-started/request-access-to-tools#Requestaccesstotools-Mural

### Which type of team are you on? (Platform team, VFS team, or Leadership)
Leadership

**Comment by johnny-jesensky-adhoc** [comment]
Hi @patrickvinograd, thanks for flagging this. We've been seeing a few requests on this page recently, so will be sure to make the change to the URL, and review for other instances as well.

We will be in touch once the change is live.

**Comment by taylojill** [comment]
Hi @patrickvinograd I'll be working on your request. I will check and update all links on the page, and have it ready for deployment on Monday 11/6/23. Thank you!

cc @johnny-jesensky-adhoc
