### ISSUE TITLE
SOCKS access for [Rakesh]

### ISSUE THREAD

**Issue by rakeshmaurya563** [department-of-veterans-affairs/va.gov-team#68471]
### Your Name

Rakesh Kumar Maurya

### Your Email

rakesh.maurya@va.gov

### Your Role and Team

QA, va.govSM

### Product Manager (PM) name and email

Bryan.Riley@va.gov

### Product Owner (PO) name and email

Patricia.Henry@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCzeTHTXddiuutNy+FxkethBv/02JNgAAJe5NdsRLemeQM0BJ9Idb5I1+TfD0nj/OnuVSNuBQmNwrLxb3hQZJ4uQzuZUWLb2l09EsSnEQphozMUtOnft71fxuUJtWUwE8FixRCgsXTsKkIxGKL5g7tADU24mJXErpRHdSEu8vJXNiNOjn7W0ZUeFkeuSKpxYbUjet74QwQiKdZ2TXHAOg6IKV7ozSzZEkO0Tg8qmgY4+wJ4vxz13JinlP0WNg0fOKZCj96bZhlRrEM0uXgVysetXtS6CDeS4N66/rQslY3d6aEuh1bgDHEHpWeY9jvLzggLNnq5wzwgILSQnjMKcIYLouUnBeCjtiP+EM52f0sRkr1DI0/v8kVgQRMyG3/btRt8xS3UthjXgJkXOh14bK/ic8cbvUSVptislEne601YUJLqdWmyOQbTwkzxWRiPm+iNezdjcVBk7j7TxjUOg3TTX9ewRwYzys83Ipu4bI5sUYxM8hSHXshVvK5FtEyvdA0= OITBALMAURYR@LRC-LT584335+rakesh.maurya@va.gov

### E-QIP Transmittal Confirmation

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/125288357/caafbb20-290e-4624-a652-39de50160f4c)

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by hgbarreto** [comment]
@rakeshmaurya563 Access granted ✅

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Reach out in #vfs-platform-support if you have any trouble.
