### ISSUE TITLE
SOCKS access for Robert Bailey

### ISSUE THREAD

**Issue by BobbyBaileyRB** [department-of-veterans-affairs/va.gov-team#68487]
### Your Name

Robert Bailey

### Your Email

Robert.m.bailey@bylight.com

### Your Role and Team

Accessibility specialist for MHV Products

### Product Manager (PM) name and email

bryan.riley@va.gov

### Product Owner (PO) name and email

Patricia.Henry@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC0bIMtp0wuxZiyYawoEnuRZbKV16CgwAuivVbgl9oYe0wi3fSV7o0aINUARss8TNUXiW0c4KJxkYza29aNiXvT/KC2/XiobBNxpMgqHGlzvTrGNuf4auaKWguu1ZuzhbbAPOaArqlKZB8ZBGj4YpyV/l16vr4bUUSOYxEHq0KcSoacX+zyYskW1hog4HqFpNEzfcgaStCUbUM2U+z5geJ9y7/ZHV2OhEOW93UMJsLmFcmSN316fbNWVT4tEE8hT8dFqvi7GoS0PSGEvkOqd1T5WDk3EyOTLwGDdW8RvLibr0XvU8mzAYDT50AfSp2XX9nsUA2E3d5FpyJy2teNaX1kb6CHBe2L71iT0gorU7PYEHXOc2ZB1PnCWFx6i3cFg7CB8Nd6V1T2iOL6uLRSOoTAxzULc1AY/ce4xXGYitYfEow6NGg11D7sxYj2r5gotJuZtLlkOuRCePs6mt193vhsIuSfeoH++hSET6KVES/Q7sIwGWwkoBMgdV53Wtxsh7U= bobbybailey@C02CHAKFMD6R

### E-QIP Transmittal Confirmation

![Screenshot 2023-10-26 at 2 56 04 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/102695954/55bca6a8-8070-4cd8-8108-d0e0647fc592)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by hgbarreto** [comment]
@BobbyBaileyRB - Access granted ✅

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Reach out in #vfs-platform-support if you have any trouble.
