### ISSUE TITLE
CT: Update "Learn more about these warnings" modal on profile page

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#6848]
As a user of the GI Bill Comparison Tool, I need to understand all of the caution flags an institution can have so that I can make the best decision regarding how to use my education benefits. 

## Assumptions
1. This work will be completed behind a prod flag so that upon merge it is only available on staging. 

## Acceptance Criteria:
1. In the "Cautionary information" section of the Profile Page, a user selects the "Learn more about these warnings" link. 
a. A modal appears and includes following link to "Suspension of VA Benefits to Five Schools for Deceptive Practices", which is included above "heightened cash monitoring" in the modal: https://www.benefits.va.gov/gibill/comparison_tool/about_this_tool.asp#phoenix
![Screen Shot 2020-03-13 at 1.34.11 PM.png](https://images.zenhubusercontent.com/5b645f6fe2255460d8f0b032/1ee8745f-ab52-4a01-8fd5-5cfb3acdae57)

## Supporting Artifacts
1. NA

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/11930

Can be tested on vets-website branch `bah-caution-modal`

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-03-19 at 9.48.23 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/dea6dd06-4355-4116-8be9-1037ede72012)

**Comment by sonntag-adam** [comment]
Does not show in production build

**Comment by sonntag-adam** [comment]
In staging. Testing passes QA
https://dsvavsp.testrail.io/index.php?/runs/view/218&group_by=cases:section_id&group_order=asc
