### ISSUE TITLE
Research use of Lighthouse Benefits Intake API on 526 Form

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#68483]
## Issue Description

**Message from Emily:**
`Lighthouse Benefits Intake API` is used both for the backup submission process for 526 as well as the 686c/674 backup submission as of this week! So there should be a model to follow from either/both of those teams!

**User story**
As a new Pension team,
we need to research how the teams for 526 and 686c/674 forms set up 'Lighthouse Benefits Intake API' as a backup submission process,
so that we can determine if we can follow a similar model for the 527 Pension form.

---
## Tasks ideas
- Investigate documentation available to study how teams for 526 and 686c/674 forms set up 'Lighthouse Benefits Intake API' as a **_primary_** submission process; [More information on this API here](https://developer.va.gov/explore/api/benefits-intake).
- Start an assessment on whether this is a model we can follow for the 527 Pension form

## Acceptance Criteria
- We will have a basic understanding on how 'Lighthouse Benefits Intake API' was set up as a backup submission process for the 526 Form enough to determine whether we can follow the same model for the 527 Pension form. 
- Document a baseline assessment on to use transition the Pension form to use the 'Lighthouse Benefits Intake API' as a **_primary_** submission process; [More information on this API here](https://developer.va.gov/explore/api/benefits-intake).

**Comment by emilytheis** [comment]
To clarify, I think LH benefits intake would be the **_Primary_** submission avenue for pension, replacing the central mail API. even though it's the "backup" option for 526, 686/674. Those other forms have a different primary submission model (they submit as data through middlware services like EVSS and BGS) that we don't have. but suggesting that those other teams will probably be useful for setting up the lighthouse benefits intake api generally! The engineers would be Thomas Blackwell or Sam Stuckley.

**Comment by wayne-weibel** [comment]
The 526 form would actually be the next stage/evolution of the refactor - 526 is using [BenefitsClaim API](https://developer.va.gov/explore/api/benefits-claims) (I believe) and is reassembling the form data to match the lighthouse format.  More applicable is the change from 686c/674, which wraps the generated CentralMail documents and Form metadata in an upload to BenefitsIntake.
