### ISSUE TITLE
Staging GIDS: Styling missing when accessing GIDS dashboard

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#6849]
Navigate to https://staging.va.gov/gids/dashboards
Observe

![Screen Shot 2020-03-13 at 1.16.27 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/7fff5ec9-a833-4d0c-8193-ec9e29346d45)

**Comment by hughes-dustin** [comment]
branch: bah-remove-es6-syntax
PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/610

**Comment by sonntag-adam** [comment]
Testing passes

**Comment by sonntag-adam** [comment]
In staging. Closing bug
