### ISSUE TITLE
SPIKE: How does login.gov log out (requires end user to accept prompt) work with auto-auth logout?

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#68502]
## Resources Used

* Login.gov [`logout` documentation](https://developers.login.gov/oidc/logout/)
* [OpenID Connect RP-Initiated Logout 1.0](https://openid.net/specs/openid-connect-rpinitiated-1_0.html)

### id_token_hint

Login.gov makes use of Relying Party/RP(client)-initiated logout. In the specifications above there are repeated references to an `id_token_hint` value as a means to secure the connection between the client requesting logout & Login.gov

> `id_token_hint`: RECOMMENDED. ID Token previously issued by the OP to the RP passed to the Logout Endpoint as a hint about the End-User's current authenticated session with the Client. This is used as an indication of the identity of the End-User that the RP is requesting be logged out by the OP.

This parameter is suggested as being able to serve as an alternative to requesting the end user to confirm a logout

> When an id_token_hint parameter is present, the OP MUST validate that it was the issuer of the ID Token. The OP SHOULD accept ID Tokens when the RP identified by the ID Token's aud claim and/or sid claim has a current session or had a recent session at the OP, even when the exp time has passed. If the ID Token's sid claim does not correspond to the RP's current session or a recent session at the OP, the OP SHOULD treat the logout request as suspect, and MAY decline to act upon it.

> At the Logout Endpoint, the OP SHOULD ask the End-User whether to log out of the OP as well. Furthermore, the OP MUST ask the End-User this question if an id_token_hint was not provided or if the supplied ID Token does not belong to the current OP session with the RP and/or currently logged in End-User. If the End-User says "yes", then the OP MUST log out the End-User.

### Login.gov implementation

The current Login.gov implementation of the RP-initiated logout standard does not include the `id_token_hint` parameter; the 3 parameters Login.gov accepts are `client_id`, `post_logout_redirect_uri`, and `state`. The Login.gov specs explicitly state that it will prompt the end user for confirmation.

> Note that, as per the spec, Login.gov will display a Logout confirmation screen to users on logout; users will need to click a button to complete the logout process. This protects against forged logout request attacks. If the user does not click the button, they will not be redirected back to your application.

Login.gov does return an ID token with session information in its [token response](https://developers.login.gov/oidc/token/#token-response), but would need to update their Logout endpoint to accomodate it for promptless logout.

**Comment by bramleyjl** [comment]
Slack conversation with `va-login-partners`: https://dsva.slack.com/archives/C01CLV49YMB/p1700160343723929
