### ISSUE TITLE
SPIKE: How do we prevent 'revoke_all' from removing mobile sessions when logging out of web?

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#68503]
Probably something like this:
* field on OAuthSession, sso_enabled - sessions without wouldn't be auto-logged out

**Comment by rileyanderson** [comment]
## Proposal
For mobile or any other clients that want to persist a session even when logging out of web:
- Add a boolean column, `persisted_sessions, default: false` to `client_configs` 
- Add a boolean column, `persisted,  default: false` to oauth_sessions
  - Should we add an index or partial index to this?
- Accept an optional param, `revoke_persisted` in `SignInController#revoke_all_sessions`
-  Change `SignIn:: RevokeSessionsForUser` to accept a `revoke_persisted: false` param
  - If `revoke_persisted` param is passed and true all user sessions will be revoked
  - If `revoke_persisted` param is false, all non_persisted are revoked
