### ISSUE TITLE
Tests Rails access

### ISSUE THREAD

**Issue by bmatos312** [department-of-veterans-affairs/va.gov-team#68529]

**Comment by bmatos312** [comment]
https://dsva.slack.com/archives/CBU0KDSB1/p1698417655780299

**Comment by bmatos312** [comment]
Before answering the below questions, please verify with your supervisor if you already have an account for your team. 

Do you know if someone on your team currently has a test rails account as they are limited.

- It sounds like you're interested in a shared account. Is that right?

- Will you be the maintainer of the shared account?

- Should I link the account to the email in your Slack profile (their.email@email.com)?

- Are there any existing projects in TestRail for your team, or should I create a new project for you all?

**Comment by rakeshmaurya563** [comment]
It sounds like you're interested in a shared account. Is that right?--- I prefer to have my own account, not shared
Will you be the maintainer of the shared account?-N/A
Should I link the account to the email in your Slack profile ([their.email@email.com](mailto:their.email@email.com))?- Yes
Are there any existing projects in TestRail for your team, or should I create a new project for you all?- [VA.gov](http://va.gov/) - Secure Messaging

**Comment by bmatos312** [comment]
@rakeshmaurya563 Can you verify with your Supervisor that your team does not have an account yet as we are limited on licenses and need to make sure its team based.

**Comment by rakeshmaurya563** [comment]
Dimitar A. Tzvetanov

**Comment by bmatos312** [comment]
Dimitar Tzvetanov
  [2:48 PM](https://dsva.slack.com/archives/D0636CVKSTC/p1698432492289719)
Hi Brenden. I have an account and we have a project - I believe it's [VA.gov](http://va.gov/) - SM





[2:48](https://dsva.slack.com/archives/D0636CVKSTC/p1698432502348429)
Or something close to that
[2:49](https://dsva.slack.com/archives/D0636CVKSTC/p1698432558620929)
Do you mind explaining what exactly a shared account is? What are the limitations of having a shared account vs. a regular account?

**Comment by bmatos312** [comment]
@rakeshmaurya563 Hello Rakesh, I spoke with Dimitar and he currently has an account. We are limited to the amount of accounts we can give out. You would either have to have him share his credentials with you securely of course. Or have him run queries for you in lieu of you not having an account.
