### ISSUE TITLE
GIDS: Add the 103 info to institution builder

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#6852]
## Assumptions
1. The content of the file has a 1-1 relationship to facility code
2. This story should utilize the prod flag/feature flag recently implemented in GIDS (#6598) to be tested by EDU. 

## Acceptance Criteria:
1. Section 103 file has been successfully uploaded to GIDS
2. Provide the ability to download the csv of the uploaded file
3. DB table includes all of the fields included in the file.
4. Before going live, a Prod Flag/Feature Flag is utilized for the changes associated with this story (#6598). 

## Supporting Artifacts:
1. [https://app.zenhub.com/files/133843125/8f6c15ee-5773-4eee-9fe1-d5f1fef76ffc/download](https://app.zenhub.com/files/133843125/8f6c15ee-5773-4eee-9fe1-d5f1fef76ffc/download)

**Comment by hughes-dustin** [comment]
DB Changes:
  branch: bah-6852-db-changes

**Comment by hughes-dustin** [comment]
branch: bah-6852
PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/615

**Comment by hughes-dustin** [comment]
prod flags:

**Comment by delli-gatti-michael** [comment]
Local Testing Passes

TestRail Test Case:
https://dsvavsp.testrail.io/index.php?/cases/view/377

**Comment by delli-gatti-michael** [comment]
Functionality is now present in Staging. Closing this issue
