### ISSUE TITLE
[Update Platform Tools > Request Access to Tools]:

### ISSUE THREAD

**Issue by raquelou** [department-of-veterans-affairs/va.gov-team#68538]
### Describe the problem

When going through the onboarding process I reached the step in the process where I needed to request access to tools. I found that I could not access the optimal sort login credentials list. The documentation described that I should: 

1. Submit a request to access the GitHub sensitive repo in the #platform-support Slack channel.

2. Contact the group owner from the list below(Shane Strassberg) in the #research-ops Slack channel with your request to get the Optimal Workshop login credentials.

<img width="756" alt="Screenshot 2023-10-27 at 12 32 15 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/148793348/f9824482-5047-4ff4-ba54-f1c6de9dca97">

When I did step 3b I was told I was not supposed to reach out to Shane. If this is not what is supposed to be done it should be removed from the onboarding.

### Who will benefit

All people onboarding who need access to optimal sort who do not have access to the optimal sort login credentials list.

### Describe your idea

Remove this step from the platform tools > request access to tools onboarding checklist:

2. Contact the group owner from the list below(Shane Strassberg) in the #research-ops Slack channel with your request to get the Optimal Workshop login credentials.

### Provide evidence

The current process is sending people onboarding on the wrong path.

### Platform Mission

- [ ] Keeps these products and services available, stable, and secure.
- [ ] Ensures they are consistent and meet high standards of quality in Veteran-centered user experience and technical approach.
- [X] Provides shared tools, software, support, and technical infrastructure to accelerate their development.
- [ ] Other

**Comment by johnny-jesensky-adhoc** [comment]
Hi @raquelou, thanks for flagging this. We've been seeing a few requests on this page recently, so will look to make the needed changes on this section.

We will be in touch once the change is live.

**Comment by taylojill** [comment]
I sent a message to Naomi via our Slack platform-content channel asking that she review and advise on the customer's request.

**Comment by taylojill** [comment]
I updated the page based on an update from Naomi. The update provides clarification and should satisfy the request. I checked page for launch-blocking issues, ready to deploy.

**Comment by johnny-jesensky-adhoc** [comment]
Hi @raquelou  - thanks again for flagging this request. This page has been updated with some clearer instructions. Let us know if you have any questions.

FYI @taylojill

**Comment by steel36** [comment]
This item was completed.  Moving to Done.
