### ISSUE TITLE
CT: Add the 103 info to institution builder

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#6853]
## Assumptions
This cannot be complete until the section 103 file (#6852) has been uploaded.

## Acceptance Criteria:
1. When a new preview of the file is generated, the 103 flag will be set for each institution in accordance with the new version of the file.
2. When requesting institution profile information from GIDS, this flag is present.

## Supporting Artifacts:
1. Sample file: [https://app.zenhub.com/files/133843125/5595827c-9fe9-40a1-a113-3a9177f549b9/download](https://app.zenhub.com/files/133843125/5595827c-9fe9-40a1-a113-3a9177f549b9/download)

**Comment by hughes-dustin** [comment]
This was completed in work from [story 6852](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/6852).

**Comment by delli-gatti-michael** [comment]
Tested with #6852. This functionality is already in Staging. Closing this issue

Example Institution: https://staging.va.gov/gi-bill-comparison-tool/profile/35000827
