### ISSUE TITLE
Investigate integration between Domo and GovDelivery

### ISSUE THREAD

**Issue by sdickson-gt** [department-of-veterans-affairs/va.gov-team#68533]
## Issue Description
_Understand what and how govdelivery metrics can be accesses and integrated into Domo Dashboard for LGA campaigns?_

---
## Tasks
- [ ] _Define which govdelivery metrics are desired_
- [ ] _Investigate options to integrate Domo and Govdelivery to automate data pul._

## Acceptance Criteria
- [ ] _Documented options_

**Comment by sdickson-gt** [comment]
Govdelivery API documentation on metrics for deliverability and reporting: https://developers.govdelivery.com/api/tms/tutorial/deliver-report/

Domo doesn't have an OOTB connector for Govdelivery.  Some initial thoughts for options include: build a connector in Domo, develop a script to connect to Govdelivery and use Domo Workbench, or ...

**Comment by sdickson-gt** [comment]
Link above for TMS is apparently a distinct Govdelivery TMS product which we are not using.  There is govdelivery API documentation https://support.granicus.com/s/article-group/a8C4w000000XcOdEAK/govdelivery-api?language=en_US

However, there isn't an API for the reports.  All I'm seeing is that the reports can be manually exported to a CSV, which could then be imported into Domo.

**Comment by lmorris3** [comment]
@sdickson-gt would you consider this "done"? If we've identified next steps, we can create a separate story for those. This was mostly a discovery ticket.
