### ISSUE TITLE
[MVP] Step 1 Claimant/Vet Info: Unauthenticated experience, Add warning message

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#68557]
## Note
Part of the larger effort to update the existing 527EZ form to add missing fields/info and remove depreciated fields.

## Description
On Step 1 Applicant Information page

Add yellow warning alert after the Application Information intro sentence and before the first question on the page.

As shown on the designs

## User Story
As a Pension team,
we want to let the visitor applying for VA Pension benefits know the form is long and advise them to sign in before they get started,
so they do not lose any information if they decide they want to finish it at another time.

As a visitor applying for VA pension benefits,
I want to be aware of how long the form is and what to do in case I cannot finish filling it out immediately,
so that I know what my options are and can avoid saving a lot of work in progress.

## Designs
- https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/808DE591-9C8D-40A2-940E-BC4B935D0121

## Acceptance Criteria
**For Unauthenticated experience:**

- On Step 1 | Application Information page, a new yellow warning is added before the page's first question. It says:

This application is 7 steps long and it contains several substeps per step. We advise you sign in to save your progress.

**Note:** You can sign in after you start your application. But you'll lose any information you already filled in.

- The phrase "sign in to save your progress" portion is hyperlinked to [**PROVIDE LINK HERE/ASK MAYA IF THIS SHOULD LINK TO: https://www.va.gov/?next=loginModal**]

## Tasks
[Software Development Tasks](https://docs.google.com/document/d/1vtn5co_YzGl1cFRNrIBAdjf53dmfH4_EXBWK8C5mU9Y/edit?usp=sharing)

- [x] Front-end work @ToddWebDev 

## Review

- [x] Designer (Maya) has signed off on pages in staging

## Artifacts
- [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/527EZ-reactivation-initiative-brief.md)
- [User flow in Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683826730324/61b509f935adaa2acf2f7769a5ba911726a7b237?sender=u9d01ee38af217e4877e75660)
- [Prototypes in Sketch](https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/p/E0D78F34-9E6A-4CAC-943F-B9D658197368/canvas)
- [Spreadsheet of deleted form fields](https://docs.google.com/spreadsheets/d/1PTXxO6mFH2ZUK6XxX7iCCQb-NoSvhB5P/edit?usp=sharing&ouid=104362113771391164792&rtpof=true&sd=true)
- [Content source of truth/PDF form](https://www.vba.va.gov/pubs/forms/VBA-21P-527EZ-ARE.pdf)
- [Link to testing accounts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/form-deactivation/527EZ-staging-test-accounts-accessible.md)
- [Link to staging](https://staging.va.gov/)

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/68557?planning-poker) with Zenhub @ToddWebDev @TaiWilkin @mjknight50

**Comment by TaiWilkin** [comment]
I think that this will not require any back-end work; the front-end should already know if the user is authenticated or not.

**Comment by ToddWebDev** [comment]
@TaiWilkin I can confirm that no backend work is required

**Comment by ToddWebDev** [comment]
@vbellissimo @mayacoforma This work meets the acceptance criteria and design requirements as referenced in the designs. Can we move this task to complete?

**Comment by mayacoforma** [comment]
@ToddWebDev The yellow alert looks fine, but some of the questions on this page have been broken into seperate pages.
The yellow alert appears satisfactory; however, certain questions on this page have been divided onto separate pages. I have included screenshots for reference. I seek guidance from @vbellissimo  on whether addressing this issue should be included in the current task's scope or considered for future tasks. Thank you!

 [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUhhQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--141663825d18610615aa7254387660b989fa073d/State%201-%20%20Claimant%20is%20authenticated.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVBhQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d28419cf5d57791faee19cf9b1bca44c773462ed/State%201-%20%20Claimant%20is%20authenticated.%202.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVRhQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5928f4642a617185d9df9517ec130e1c5c36becc/State%201-%20%20Claimant%20is%20authenticated.%203.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWJhQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c25040e1dfd8d63414e29adbf624498e56aff7bd/State%201-%20Enter%20mailing%20address%2C%20email%20address%2C%20and%20phone%20number..png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWZhQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4ec908a0c5b6be7a67d3fca57391c6cdf37a0ef4/Form%20527%20-%20States%20and%20Substeps%20-%20%22MVP%22%20-%20%20008%20%28Web%29%20Substep%203%20%20Enter%20email%20address%2C%20telephone%20number%20%28s%29.png)

**Comment by mayacoforma** [comment]
@ToddWebDev The yellow alert looks fine, but some of the questions on this page have been broken into seperate pages.
The yellow alert appears satisfactory; however, certain questions on this page have been divided onto separate pages. I have included screenshots for reference. I seek guidance from @vbellissimo  on whether addressing this issue should be included in the current task's scope or considered for future tasks. Thank you!

 [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUhhQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--141663825d18610615aa7254387660b989fa073d/State%201-%20%20Claimant%20is%20authenticated.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVBhQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d28419cf5d57791faee19cf9b1bca44c773462ed/State%201-%20%20Claimant%20is%20authenticated.%202.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVRhQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5928f4642a617185d9df9517ec130e1c5c36becc/State%201-%20%20Claimant%20is%20authenticated.%203.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWJhQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c25040e1dfd8d63414e29adbf624498e56aff7bd/State%201-%20Enter%20mailing%20address%2C%20email%20address%2C%20and%20phone%20number..png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWZhQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4ec908a0c5b6be7a67d3fca57391c6cdf37a0ef4/Form%20527%20-%20States%20and%20Substeps%20-%20%22MVP%22%20-%20%20008%20%28Web%29%20Substep%203%20%20Enter%20email%20address%2C%20telephone%20number%20%28s%29.png)

**Comment by ToddWebDev** [comment]
@mayacoforma @vbellissimo These requested changes will be easiest to implement and track as a new tasks.

**Comment by vbellissimo** [comment]
@ToddWebDev @mayacoforma Thank you both.

@ToddWebDev, let's move to complete and I am making a note for a potential follow on task to break up the questions in their own pages. I'll discuss this with Emily and Julie!
