### ISSUE TITLE
GIDS: Research allowing GIDS to handle ES6 or adding a rubocop to keep ES6 out

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#6855]
## Acceptance Criteria: 
1. Research findings related to either allowing GIDS to handle ES6 or adding a rubocop to keep ES6 out have been captured on this story and a follow on story has been entered if applicable. 

## Supporting Artifacts

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/618

**Comment by sonntag-adam** [comment]
Merged, closing story.
