### ISSUE TITLE
[BE] Update schema for maxLength Value for address city fields 

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#68558]
As a team member, I would like to reduce the maxlength for city address in the schema so that the schema is the source of truth and we don't need to make edits on the front end.

- Change city address max length from 51 to 30 characters
- Test
- **Success: city maxlength is 30 characters and consistent with FE**

**Comment by hdjustice** [comment]
if this is complete, it can be closed.  Thanks!
