### ISSUE TITLE
[MVP] Step 1 Claimant/Vet Info: Add new question, Add VA File Number

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#68553]
## Note
Part of the larger effort to update the existing 527EZ form to add missing fields/info and remove depreciated fields.

## Description
On the Step 1 Applicant Information page

Add new form field:
 'Have you filed any type of VA claim before?' as shown in the designs

## User Story
As a veteran applying for VA pension benefits,
I want to be able to provide information about my previous VA claims,
so that I can receive the appropriate assistance.

## Designs
- https://www.sketch.com/s/75b363db-6be8-4b7e-8655-8f12f1ea5554/a/ZVdyVa7
- https://www.sketch.com/s/75b363db-6be8-4b7e-8655-8f12f1ea5554/a/JAMDAx5

## Acceptance Criteria
- On the application forms fist chapter and page, there will be a new field inbetween the Social Security Number field and the Date of Birth field
- It will be labeled “Have you filed any type of VA claim before?” with options for “Yes” and “No.”
- If the user selects “Yes,” an additional field labeled “VA File Number” will appear.
- The form will allow for a Veteran whose file number is different than their SSN to enter both. _This field will be optional for the user._
- The “VA File Number” field should have validation to ensure it follows the correct format.
- The field responses to this question should be saved so that it can be submitted.

## Tasks
[Software Development Tasks](https://docs.google.com/document/d/1vtn5co_YzGl1cFRNrIBAdjf53dmfH4_EXBWK8C5mU9Y/edit?usp=sharing)
- [x] Front-end work @ToddWebDev 
- N/A Back-end work @TaiWilkin (Note from Todd: No back end work needed as long as this is deployed after the pension benefits form is 'deactivated' on PROD. We can update vets-json-schema's separately as we start to make more updates.)

## Review
- [x] Designer (Maya) has signed off on pages in staging

## Artifacts
- [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/527EZ-reactivation-initiative-brief.md)
- [User flow in Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683826730324/61b509f935adaa2acf2f7769a5ba911726a7b237?sender=u9d01ee38af217e4877e75660)
- [Prototypes in Sketch](https://www.sketch.com/s/75b363db-6be8-4b7e-8655-8f12f1ea5554)
- [Spreadsheet of deleted form fields](https://docs.google.com/spreadsheets/d/1PTXxO6mFH2ZUK6XxX7iCCQb-NoSvhB5P/edit?usp=sharing&ouid=104362113771391164792&rtpof=true&sd=true)
- [Content source of truth/PDF form](https://www.vba.va.gov/pubs/forms/VBA-21P-527EZ-ARE.pdf)
- [Link to testing accounts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/form-deactivation/527EZ-staging-test-accounts-accessible.md)
- [Link to staging](https://staging.va.gov/)

**Comment by emilytheis** [comment]
dropped this in slack but Sharing here re: acceptance criteria -- we basically want to allow for a Veteran whose file number is different than their SSN to enter both. Most Veteran File numbers are the same as their SSNs, but some have a different file number. that's why the sketch shows the additional file number field as optional.

**Comment by ToddWebDev** [comment]
## Screenshots
_Note: This field is mandatory for UI changes (non-component work should NOT have screenshots)._

### Mobile
| Before | After | Yes | No | Error | Valid |
| ------ | ----- | ----- | ----- | ----- | ----- |
|![pension-app-prefilled-old(iPhone SE)](https://github.com/department-of-veterans-affairs/vets-website/assets/7394764/189830d1-cfc2-4250-9396-05024613d006)|![pension-app-prefilled(iPhone SE)](https://github.com/department-of-veterans-affairs/vets-website/assets/7394764/8fb23cf4-191c-4c1e-beb5-a8ea4fe6e0ca)|![pension-app-va-file-claimed-yes(iPhone SE)](https://github.com/department-of-veterans-affairs/vets-website/assets/7394764/0ef5a8fe-be62-4ee0-93dd-4847f6d4ea13)|![pension-app-va-file-claimed-no(iPhone SE)](https://github.com/department-of-veterans-affairs/vets-website/assets/7394764/c5330ac0-b434-433d-a6cb-fb13091e82cd)|![pension-app-va-file-number-error(iPhone SE)](https://github.com/department-of-veterans-affairs/vets-website/assets/7394764/c02aa091-e95b-4929-a94a-e76cab4cbe59)|![pension-app-va-file-number-valid(iPhone SE)](https://github.com/department-of-veterans-affairs/vets-website/assets/7394764/34fe730e-4762-4f9f-acc8-838192f55e53)

### Desktop
| Before | After | Yes | No | Error | Valid |
| ------ | ----- | ----- | ----- | ----- | ----- |
|![pension-app-prefilled-old](https://github.com/department-of-veterans-affairs/vets-website/assets/7394764/6667c1b3-a9a3-41f4-ac7a-155d078763be)|![pension-app-prefilled](https://github.com/department-of-veterans-affairs/vets-website/assets/7394764/6ae42bd4-5275-4469-9984-da0c4cee6034)|![pension-app-va-file-claimed-yes](https://github.com/department-of-veterans-affairs/vets-website/assets/7394764/0723c3b7-409c-4304-9377-2c694d129621)|![pension-app-va-file-claimed-no](https://github.com/department-of-veterans-affairs/vets-website/assets/7394764/0a89f317-a1c6-40b7-ba2e-013eb668ff0f)|![pension-app-va-file-number-error](https://github.com/department-of-veterans-affairs/vets-website/assets/7394764/7efb8055-f409-464c-a426-3cf5cb8737f3)|![pension-app-va-file-number-valid](https://github.com/department-of-veterans-affairs/vets-website/assets/7394764/d0153ff9-915c-44ab-8ff2-43f811e61e59)

**Comment by vbellissimo** [comment]
Hi @mayacoforma, wanted to give you a heads-up that @ToddWebDev has recently finished this task. Please take a look and review for sign off when you have a chance. Thank you!

**Comment by mayacoforma** [comment]
@vbellissimo Sure, I'll add this to my to-do list.

**Comment by mayacoforma** [comment]
@vbellissimo 

I'd like to highlight a couple of dependencies that might hinder my ability to complete this task:

1. I would need to complete the design updates for the engineering handoff in order to effectively cross-check with the designs.
2. Our design review process typically doesn't happen incrementally, screen by screen, like this. We usually focus on ensuring consistency across the entire end-to-end user experience. I recommend conducting a more holistic review once both the design and front-end work are completed, rather than taking the incremental approach we're currently considering.

**Comment by mayacoforma** [comment]
@ToddWebDev 

Following a thorough review of this segment with Katherine, we propose several revisions:

**Social Security Field:**

- Revise the text.
- Adjust the format and apply a mask to the social security number.

VA File Number:

- Revise the text.
- Include hint text.
- Adjust the format and apply a mask to the social security number.

@emilytheis 

Kindly examine the mockup and inform us if you believe we have fulfilled the specified requirements. Thank you!

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWFqQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1cefbca94e51d757d6c10e3a909370b7b8f65cd6/Yes%20-%201.0.png)

**Comment by wayne-weibel** [comment]
The additional fields are present; "VA File Number" only visible with "Yes" selected.  Validation exists for the new (optional) field.  Values are retained during form navigation.

- There is no mask being applied to the VA File Number
- If 'filed before' is toggled after entering the VA File Number, the entered value is no retained

**Comment by ToddWebDev** [comment]
@mayacoforma Is this the correct screenshot? 

- The Social Security number field hint says 'example, 123 45 6789' with a comma
- The VA file number field label has been changed to include a description (this will raise accessibility issues)
- The Va File number field hint says 'example, 123 45 6780 C' with a comma and a trailing C

**Comment by vbellissimo** [comment]
Waiting for feedback from @mayacoforma 

This will have to wait for Pension deactivation before it merges.

**Comment by mayacoforma** [comment]
@ToddWebDev @vbellissimo When I was going over the designs with Julie, she seemed unclear as to why we added this question and so I took it out of the designs. It was something that was in the designs the non disability team handed off to us. @vbellissimo Do you have context on the logic behind this? I'll start a thread in Slack with you and Laura to discuss.

**Comment by vbellissimo** [comment]
@ToddWebDev The context I have is based off the most updated version of the PDF form, [which is this one](https://www.vba.va.gov/pubs/forms/VBA-21P-527EZ-ARE.pdf). See page 8 of that PDF. The SSN and VA file number are separated on it. I think this is the route we should take to ensure it matches the PDF form.

@jstrothman @emilytheis let us know if you disagree with this.

**Comment by ToddWebDev** [comment]
@vbellissimo @mayacoforma The completed work on the FE meets the acceptance criteria of this ticket. Can we move this task to done based on that? If we want to make additional changes to the content and structure of this page I would recommend creating a new task to track it.

**Comment by vbellissimo** [comment]
@ToddWebDev Yes, let's move on from this and create a new task to correct any deviation from this. Thanks!
