### ISSUE TITLE
Adding Don Shin to DSVA Slack

### ISSUE THREAD

**Issue by HeatherRienks** [department-of-veterans-affairs/va.gov-team#68555]
# Description
Please add Don Shin, new Agile Six Full Stack Engineer on CHAMPVA team to DSVA Slack as a Full Member.
don.shin@agile6.com

He should be added to #vfs-all-teams, #vfs-change-announcements and any other pertinent Engineering and VFS general channels for new team members.

Thanks!

**Comment by HeatherRienks** [comment]
Hi @LEHigley  Just wanted to follow up on this request for Don. Thank you!

**Comment by eunicegar** [comment]
Done.
