### ISSUE TITLE
Adding Michael Clement to DSVA Slack

### ISSUE THREAD

**Issue by HeatherRienks** [department-of-veterans-affairs/va.gov-team#68554]
# Description

Please add Michael Clement, new Ad Hoc Front End Engineer on CHAMPVA team to DSVA Slack as a Full Member.
michael.clement@adhocteam.us

He should be added to #vfs-all-teams, #vfs-change-announcements and any other pertinent Engineering and VFS general channels for new team members.

Thanks!

**Comment by HeatherRienks** [comment]
@LEHigley - @lkoenigsberg and @KevinMHoffmanUSDS - Please hold off on Slack access; we are still awaiting favorable clearance!

**Comment by HeatherRienks** [comment]
@LEHigley @lkoenigsberg @KevinMHoffmanUSDS - Michael Clement has been favorably SAC adjudicated. Please grant him access to DSVA Slack. Thanks!

**Comment by eunicegar** [comment]
Done. Please close request.
