### ISSUE TITLE
[MVP] Step 2 Military Info: Add new question, Service Number

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#68564]
## Note
Part of the larger effort to update the existing 527EZ form to add missing fields/info and remove depreciated fields.

## Description
On the Step 2 Military history

Add new required form field:
'Service number' as shown in the designs

## User Story

As a Pension team,
we want to require the user to enter their "Service Number" for each "Service Period" they provide,
so can associate it with each Service Period on their claim submission.

As a user applying for VA pension benefits,
I want to be able to see where and when I'm required to provide my "Service Number",
so that I can fill out the form as efficiently as possible.

## Designs

- https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/3F3BF229-5859-40C2-9EE7-11A1E5961353
- https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/E38047A8-C234-4D69-B218-33C65FE11B79

## Acceptance Criteria

- On Step 2, Military history section, a "Service Number" field will be added as an additional question.
- It will be placed after the "Service end date" question and before "Add another service period" button.
- It will be labeled "Service number".
- Field will be required and requirement is shown to the user.
- If user chooses to enter an additional service period, they will have the same required question in the same placement.
- If the user does not enter anything within "Service Number" they will see an error that shows them it is a required field in order to save or continue.
- The “Service Number” field should have validation to ensure it follows the correct format.
- The field responses to this question should be saved so that it can be submitted.

## Tasks
- [x] Front-end work @ToddWebDev 

## Review
- [ ] Designer (Maya) has signed off on pages in staging

## Artifacts
- [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/527EZ-reactivation-initiative-brief.md)
- [User flow in Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683826730324/61b509f935adaa2acf2f7769a5ba911726a7b237?sender=u9d01ee38af217e4877e75660)
- [Prototypes in Sketch](https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/p/E0D78F34-9E6A-4CAC-943F-B9D658197368/canvas)
- [Spreadsheet of deleted form fields](https://docs.google.com/spreadsheets/d/1PTXxO6mFH2ZUK6XxX7iCCQb-NoSvhB5P/edit?usp=sharing&ouid=104362113771391164792&rtpof=true&sd=true)
- [Content source of truth/PDF form](https://www.vba.va.gov/pubs/forms/VBA-21P-527EZ-ARE.pdf)
- [Link to testing accounts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/form-deactivation/527EZ-staging-test-accounts-accessible.md)
- [Link to staging](https://staging.va.gov/)

**Comment by steele-lm** [comment]
@vbellissimo This came up in the burial design intent review: There is a [military service history API](https://developer.va.gov/explore/api/veteran-service-history-and-eligibility) that we might be able to (eventually) leverage to automatically pull in service information. We have a [spike scheduled ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/68092)to look into leveraging it and we can share our findings!

**Comment by vbellissimo** [comment]
Thanks for the heads up @steele-lm .

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/68564?planning-poker) with Zenhub @mjknight50 @TaiWilkin @ToddWebDev

**Comment by ToddWebDev** [comment]
The pension benefits form automatically saves your progress as you fill it out, including additional service periods. When the veteran selects 'Add another service period' the form will continue to auto-save. The exception is when you 'Edit' an existing service period. In that case you need to manually save the changes with the 'Update' button. Adding a manual 'Save' button to a new service period would be a deviation from the existing pattern and may potentially require some significant refactoring. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWFZQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e8b3defb1f0f7cd8cd064eb8abd08f4a090ea13f/pension-military-history-service-periods.gif)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWVZQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aed4941734dda30f4d354b8e0f7b3397d0eec9ff/pension-military-history-edit-service-period.gif)

**Comment by vbellissimo** [comment]
@ToddWebDev That makes sense. I wonder if @fiorella-io 's designs did not account for that existing functionality you pointed out. Let's point this out to Maya and let her know.

**Comment by vbellissimo** [comment]
@mayacoforma

**Comment by ToddWebDev** [comment]
Thank you @vbellissimo

**Comment by mayacoforma** [comment]
@ToddWebDev Yes, we don't need the save button.

**Comment by mayacoforma** [comment]
@ToddWebDev @vbellissimo 
I conducted quality assurance on this task, and I couldn't find the newly added input field for the service number in staging. Is this task placed in the correct swim lane?

**Comment by ToddWebDev** [comment]
@mayacoforma this work is now on stage for review

**Comment by emilytheis** [comment]
This field should be titled "Military Service Number" -- not sure if that got mixed up in transition, but that was CAIA's plain language guidance! Otherwise looks good!

**Comment by ToddWebDev** [comment]
@emilytheis I'll open a  separate PR to update the default label text from 'Service number' to 'Military service number' in the FE web component pattern for service numbers and reference the VA design system service history form label guidance.
https://design.va.gov/content-style-guide/form-labels

**Comment by mayacoforma** [comment]
@ToddWebDev 
This appears to be in good order. Could you please kindly adjust the label to reflect "Military Service Number" in alignment with the VA content guide? Your cooperation is greatly appreciated. Thank you!

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenZpQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a66f6102b9bd126fa4cabda3a841d4a96d995aeb/Form%20527%20-%20%20States%20and%20Substeps%20-%20%22MVP%22%20-%20%20004%20%28Web%29%20Substep%201-%20%20Enter%20Claimant%E2%80%99s%20service%20period.png)

**Comment by mayacoforma** [comment]
@ToddWebDev This looks good to me. Thanks!
