### ISSUE TITLE
[MVP] Step 2 Military Info: Remove questions

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#68561]
## Note
Part of the larger effort to update the existing 527EZ form to add missing fields/info and remove depreciated fields.

## Description
On Step 2 Military history

Remove the following questions:
- Did you serve in a combat zone after 9/11/2001?
- Reserve and National Guard. Are you currently on federal active duty in the National Guard? (Step 2.2)
- Have you received any type of severance or separation pay?
- Pay type
- Amount

As shown on the designs

## User Story
As a Pension team,
we want to remove unnecessary questions about the veteran's military info,
so that we can better align the form questios to match the PDF version.

## Designs
- https://www.sketch.com/s/75b363db-6be8-4b7e-8655-8f12f1ea5554/v/0olEw0/p/316E2F85-A392-40B8-9DF2-B0178C7CA260/canvas

## Acceptance Criteria

The following questions will be removed from Step 2 Military Info section:
- Did you serve in a combat zone after 9/11/2001?
- Reserve and National Guard. Are you currently on federal active duty in the National Guard? (Step 2.2)
- Have you received any type of severance or separation pay?
- Pay type
- Amount

## Tasks
[Software Development Tasks](https://docs.google.com/document/d/1vtn5co_YzGl1cFRNrIBAdjf53dmfH4_EXBWK8C5mU9Y/edit?usp=sharing)

- [x] Front-end work @ToddWebDev 

## Review
- [ ] Designer (Maya) has signed off on pages in staging

## Artifacts
- [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/527EZ-reactivation-initiative-brief.md)
- [User flow in Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683826730324/61b509f935adaa2acf2f7769a5ba911726a7b237?sender=u9d01ee38af217e4877e75660)
- [Prototypes in Sketch](https://www.sketch.com/s/75b363db-6be8-4b7e-8655-8f12f1ea5554)
- [Spreadsheet of deleted form fields](https://docs.google.com/spreadsheets/d/1PTXxO6mFH2ZUK6XxX7iCCQb-NoSvhB5P/edit?usp=sharing&ouid=104362113771391164792&rtpof=true&sd=true)
- [Content source of truth/PDF form](https://www.vba.va.gov/pubs/forms/VBA-21P-527EZ-ARE.pdf)
- [Link to testing accounts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/form-deactivation/527EZ-staging-test-accounts-accessible.md)
- [Link to staging](https://staging.va.gov/)

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/68561?planning-poker) with Zenhub @mjknight50 @TaiWilkin @ToddWebDev

**Comment by mayacoforma** [comment]
@ToddWebDev This looks good to me. Thank you!
