### ISSUE TITLE
Naming conventions for automated checks 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#6858]
# Overview 

As the number of automated checks increases, scanning and understanding what each of them do becomes more difficult. 

![Screen Shot 2020-03-13 at 15.08.35.png](https://images.zenhubusercontent.com/5a5d4c174b5806bc2bc2db50/761a675c-4de1-4236-aaac-2e582f71b3bb)

## Tasks 

- come up with a naming convention for the tasks that groups them 
- rename the workflows  

## Notes 

- talk to the BE group about the tasks they have 
- maybe group by VSP: or required reviews: 
- maybe use common verbs like "run eslint", "run unit tests" or "validate code styles"

**Comment by rianfowler** [comment]
maybe review naming conventions with content and IA

**Comment by rianfowler** [comment]
cc @dbru fyi

**Comment by meganhkelley** [comment]
Good idea but blocked by migration to GitHub Actions
