### ISSUE TITLE
SOCKS access for [Tai Wilkin]

### ISSUE THREAD

**Issue by TaiWilkin** [department-of-veterans-affairs/va.gov-team#68589]
### Your Name

Tai Wilkin

### Your Email

tai.wilkin@coforma.io

### Your Role and Team

Fullstack Engineer on Pension and Proactive Benefits

### Product Manager (PM) name and email

Anh Platt, anh.platt@coforma.io

### Product Owner (PO) name and email

Emily Theis, Emily.theis@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDOSjejPiVL/lcHTz7EMOovhkfWbXGoFZrEMMArc8d6Q14VXNR4Yszn0ynzkPNFFz2iN1GEZmZKnGimXKvUud4RiOeKuoQ0D70FvpqKXvHd87iSWFFAZPICk+iMkOq2E0wLxSXQtcD8HaxFmVwDgwS5mJFXCKqtalU85Knacfc62zwWyf2oyfn8OECb6CB/vr1VoPq3NlkXINq/BsUxIVGQHyji7oF98BWidHyEAxeHtm03DdcUETuL3zZyYQgYOJj+lN34Rf/V1LiD378igRfDMD2/o/P2MI7Lls7WjCc/Wolhf7/c7i+zmUhMpHUP9bGzucfpk0mJloH7TNuKTS3+QUOjiLet8n+71IVuXza/b6WP3QOmoCCojbLsyJeDWq9iT/1U0a5revhC117WMohzIJbcp/m+vopsqL3iTwfljH08IsWcb4xTcJOHvpA9vVndVJk/7Ky+H0OnNNajKiMzbA37MXUqwloyFTrBcScKCuYqCK2RqqL95u9NKyhuc28=

### E-QIP Transmittal Confirmation

<img width="997" alt="Screenshot 2023-10-27 at 10 05 55 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/21046714/44b721aa-9f3f-4d2a-89a6-619e715acb8b">

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by hgbarreto** [comment]
@TaiWilkin Access granted ✅

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Reach out in #vfs-platform-support if you have any trouble.
