### ISSUE TITLE
Personalization IA Research

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/va.gov-team#686]
Goals
- Contribute expertise to research strategy and methodology
- Participate in studies
- Participate in synthesis and make recommendations

Definition of Done
- research is complete
- readout w/recommendations is shared in End of Sprint Demo
- actual document w/recommendations shared in Slack

**Comment by mnorthuis** [comment]
Held intro meeting with Samara and Lisa on 7/30 to discuss current card sort that is already in progress, scope of their focus within personalization at this time and how IA can help/be involved through process. 

- Personalization team will include IA reps during kick-off of new research and in synthesis/read outs so we can collaborate on impacts and recommendations
- Discussed the scope of the work at this time, which does not include caretakers/family/dependend proxy users
- Personalization team will reach out to IA if there's questions around Optimal tools and if they need support/review of test approach and synthesis

Current card sort is expected to be complete this week and synthesis done by end of sprint.

**Comment by mnorthuis** [comment]
Worked with Samara on analyzing results.  She has completed analysis and recommendations and shared them out.  Closing issue.
