### ISSUE TITLE
Adjust Confluence settings so everyone can move documents

### ISSUE THREAD

**Issue by laucon** [department-of-veterans-affairs/va.gov-team#68610]
## Info
Work with Andrea to change thew admin settings so everyone within Platform can move documents in Confluence.

## Acceptance Criteria
- [x]  All members of the Platform crew can move, and edit pages in Conflunece

**Comment by johnny-jesensky-adhoc** [comment]
Admin access granted for all Platform crew, resolving permissions issues - moving this to Done.

https://adhoc.slack.com/archives/C02LYB7QXS5/p1698769925927049
