### ISSUE TITLE
[spike] Research improving babel and its packages - vets-website

### ISSUE THREAD

**Issue by acald-creator** [department-of-veterans-affairs/va.gov-team#68616]
Requirements:

- [ ] Update `babel-loader` to latest in order to be used in `v18` - will need a separate ticket in the future to change node engine to `v18`

`babel-loader` at its current version `"babel-loader": "^8.2.2"` will not work in `v18` and above. This package needs to be updated.

- [ ] Remove `babel-core`, no longer needed
- [ ] Replace `@babel/env` and `@babel/react` with `@babel/preset-env` and `@babel/preset-react`
- [ ] Replace `@babel/plugin-proposal-class-properties` with `@babel/plugin-transform-class-properties`
- [ ] Replace `@babel/plugin-proposal-export-namespace-from` with `@babel/plugin-transform-export-namespace-from`
- [ ] Replace `@babel/plugin-proposal-json-strings` with `@babel/plugin-transform-json-strings`
- [ ] Replace `@babel/plugin-proposal-nullish-coalescing-operator` with `@babel/plugin-transform-nullish-coalescing-operator`
- [ ] Replace `@babel/plugin-proposal-numeric-separator` with `@babel/plugin-transform-numeric-separator`
- [ ] Replace `@babel/plugin-proposal-optional-chaining` with `@babel/plugin-transform-optional-chaining`

Upgrade `@babel/core` to above `v7.8.0` in order to remove
- [ ] `@babel/plugin-syntax-dynamic-import`
- [ ] `@babel/plugin-syntax-import-meta`

Remove also
- [ ] `babel-plugin-dynamic-import-node` because it is replaced with `@babel/plugin-syntax-dynamic-import` and included in `@babel/preset-env@2020`
- [ ] Remove `babel-plugin-lodash` - package has been archived: https://github.com/lodash/babel-plugin-lodash
- [ ] Remove `babel-plugin-transform-class-properties` - included in `@babel/preset-env@2022`

**Comment by acald-creator** [comment]
Move to backlog, will take a look if and when `vets-website` move out of `node@14` to `node@18`

**Comment by acald-creator** [comment]
Updating that I have a separate repo testing with using `swc-loader` and `babel-loader` as a backup, but as conversions happen, majority of the code is being compiled with `swc-loader`

**Comment by parkerbees** [comment]
Moved to Jira. Closing.
