### ISSUE TITLE
Resolve Participant Null Error

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#68621]
## Issue Description
_Research done in #67526. This issue is caused by participant_id being nil on the User (through MVI and Profile). It appears that participant_id is nullable. Solution is to put a check in the get_dependents method that looks for participant_id's existence before calling ` service.claimant.find_dependents_by_participant_id(participant_id, ssn) `._

---
## Tasks
- [ ] Add a check in the get_dependents method that looks for participant_id's existence before calling ` service.claimant.find_dependents_by_participant_id(participant_id, ssn) `

## Acceptance Criteria
- [ ] Check prevents call if participant_id is missing.
---

**Comment by evansmith** [comment]
@steele-lm @tblackwe I believe this one will be handled by this PR: https://github.com/department-of-veterans-affairs/vets-api/pull/14272
