### ISSUE TITLE
Access for Jennifer Strickland

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#6863]
# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your name.
   > Jennifer Strickland
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VSA Accessibility Specialist, Ad Hoc
- [if requesting SSH key authorization] What is the **public** SSH key? 

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDHJB3vMR4cwnvrhUALc21GSxMdBxMMJQNZ6z6cft7r+I3z49PlZDCUg3AeXowS/nx/87yZgwiyPLdqltu/Eu09mwm3NPfksbNXLnTcBQGLEup6wbCQizadoYHZm0iLrcFkMW+M7ibVsxA2IPaNU1BE0aQU5mAns3hPLfmxLzpZtrrQjZL8v2Jnv6RWS/jecdrK4ZHnV4NDDebR+o1tUJPdgUHfLKvOM2kQEddiyio5cxEJ7JObgwkTPvRawRMU1aXcJlH0rlUn6KjCeRt0MbYHYzSIhCb+fOaQyxNyEtaEd0T1MkrwqjwAcfiYuii4MQY2zRPMg2O99ZfR00NDm1Q5IGSnxTXFy2sK/kDJozPPCtL9Elfx3vPAG4rtJa+3Jo1/htXRM3ELmykIshkQNO54aYfF/Qhl1sLxYtcFGcfF1lrXeSJhFalbbUzDg8O0c+OA1zxded+iz+Unul5PS1xLK6cL9gEcJHQe4JlXdmsFQtsw5B5014ZsAFzEAFcCqZa4utAgdzgt7DFxxgowtF8SZ10pcIT5xP7ozsAqNwU4pXzx00fNZ1Xr6au9w8UDY4bBVB4XNm5yFd+GUmwT+urg133qs8j20vx8toO9xpYX4JdFfHdkqUybC5abyxT7xRHRSpoteUtZMPYyhMB75At5GnNkFqdRQkJHqE8gEmcVww== jennifer.strickland@adhocteam.us
```

- [Grant AWS Console access?]
  > No

**Comment by jenstrickland** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by tskinn** [comment]
@jenstrickland You should have access now. Reach out in slack if you have any issues.

**Comment by jbritt1** [comment]
New pubkey: `ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDbYuEhNrbB7WWyXHy5xX+XFs2k4L+V7AzXC3fjmWTAjHwar8AvS7tzPg+WrZ/8hsxRhAfDLpnRsaO5o7Y/nuoxTk904nPuZ/i17UfY3JtsRRMNYm12PhmJYFISs9oXIoqWIHpcZeFINPnAMSzzTR7WVBa3JEdpsTxRzEc72JlziYeJGrrsnn7z4uyqxSWTLFcUb6RU7pZKEa7jUYHFy5HE1xiMMU8Hzb3ph2MoWmeJrTTEEWNE+xIKwl3xMMq0nxonDl15jEewAk5WNMhf0vvOOpQJouqrhv/JZGBHZ08QcdHiXG30VP/iks4h43qnrBLa8/jY9nd5w8AAjRovL7rB jenniferstrickland@Ad-Hoc-laptop.local`
