### ISSUE TITLE
Create a Sidekiq job to pull in the OGC XLS/CSV file

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#68646]
## Issue Description
Create a Sidekiq job to pull in the OGC XLS/CSV file, parse it and update the address fields and email field in the existing veteran_representative records and the address fields in existing veteran_organizations records.  The address_fields are needed to return geo search results for representatives and organizations.

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_

**Comment by oddball-lindsay** [comment]
our approach to account for possible PII: 
grab the excel file, "sanitize" or delete unnecessary data (accreditation dates, person who managed accreditation and DB IDs) that may be potentially PII and only surface data that is publicly available (already being served in the OGC tool)

**Comment by holdenhinkle** [comment]
Grab the .xlsx file from GitHub

Parse the sheets called 
Attorneys
Agents
Representatives

Reps are
Attorneys
Agents

Orgs are
Representatives

Attorneys => ​​Veteran::Service::Representative (veteran_representatives table)
Number => representative_id (string)
POA => poa_codes (array or strings)

Agents => Veteran::Service::Representative (veteran_representatives table)
Number => representative_id (string)
POA => poa_codes (array or strings)

Representatives => ​​Veteran::Service::Organization (veteran_organizations table)
VSO_POA => POA
Add leading zeros to VSO_POA in .xlsx file
Remove ' from POA in veteran_organizations

(more to come...)

**Comment by oddball-lindsay** [comment]
Test thoroughly on own repo, then will get a token to interact with the private repo.

**Comment by holdenhinkle** [comment]
PR - https://github.com/department-of-veterans-affairs/vets-api/pull/14632/files

**Comment by holdenhinkle** [comment]
I need a review from another team (like ours) for this PR - https://github.com/department-of-veterans-affairs/vets-api/pull/14640

Blocked on that^

**Comment by holdenhinkle** [comment]
Other than that^, this code is ready to test once that PR is merged and I can pull it into this branch -  https://github.com/department-of-veterans-affairs/vets-api/pull/14632/files

Need to set GitHub secret to be able to pull in the file. I'll test that locally first. Not sure how to test validating addresses with Lighthouse address validator yet because it has to be hit from within the va network. Will think about this.

Hopefully I'll get this finished up on Monday.

**Comment by holdenhinkle** [comment]
Org data beings used (this is the PR where Jon added additional columns to the orgs table) - https://github.com/department-of-veterans-affairs/vets-api/pull/14274/files

```
  create_table "veteran_organizations", id: false, force: :cascade do |t|
    t.string "poa", limit: 3
    t.string "name"
    t.string "phone"
    t.string "state", limit: 2
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["poa"], name: "index_veteran_organizations_on_poa", unique: true
  end
```

Sample org data:
```
  {
    "Organization Name": "Wisconsin Department of Veterans Affairs",
    "POA": "'030",
    "Org Phone": "1-800-947-8387",
    "Org City": "Madison",
    "Org State": "WI",
    "Representative": "Walsh, Robert",
    "Rep City": "Sturgeon",
    "Rep State": "WI",
    "Rep Zip": "'54235",
    "Registration Num": "53984"
  },
```

The following would be the same for each org (it wouldn't matter if we had an org record for each "Registration Num") so we wouldn't be introducing any changes to services that use the orgs table:
- Name
- Phone
- State

**Comment by holdenhinkle** [comment]
Verifying that address 1 with org name is validated correctly:

```
irb(main):001:0> json_data = "{\"request_address\":{\"address_pou\":\"RESIDENCE/CHOICE\",\"address_line1\":\"Orrick, Herring
ton & Sutcliffe\",\"address_line2\":\"1152 15th Street, NW\",\"address_line3\":\"NULL\",\"city\":\"Washington\",\"state_prov
ince\":{\"code\":\"DC\"},\"zip_code5\":\"20005\",\"zip_code4\":\"\",\"country_code_iso3\":\"US\"},\"type\":\"representative\
",\"id\":39255,\"email_address\":\"NULL\"}"
irb(main):004:0> data = JSON.parse(json_data)
=> 
{"request_address"=>
...
irb(main):005:0> address_data = data['request_address']
=> 
{"address_pou"=>"RESIDENCE/CHOICE",
...
irb(main):006:1*     def build_validation_address(address_data)
irb(main):007:2*       VAProfile::Models::ValidationAddress.new(
irb(main):008:2*         address_pou: address_data['address_pou'],
irb(main):009:2*         address_line1: address_data['address_line1'],
irb(main):010:2*         address_line2: address_data['address_line2'],
irb(main):011:2*         address_line3: address_data['address_line3'],
irb(main):012:2*         city: address_data['city'],
irb(main):013:2*         state_code: address_data['state_province']['code'],
irb(main):014:2*         zip_code: address_data['zip_code5'],
irb(main):015:2*         zip_code_suffix: address_data['zip_code4'],
irb(main):016:2*         country_code_iso3: address_data['country_code_iso3']
irb(main):017:1*       )
irb(main):018:0>     end
=> :build_validation_address
irb(main):020:1*       validation_service = VAProfile::AddressValidation::Service.new
irb(main):021:1*       validation_service.address_suggestions(validation_address)
irb(main):022:0>     end
irb(main):023:0> validation_address = build_validation_address(data['request_address'])
=> 
#<VAProfile::Models::ValidationAddress:0x00007f4c0b2f28e0
...
irb(main):024:0> validation_address
=> 
#<VAProfile::Models::ValidationAddress:0x00007f4c0b2f28e0
 @address_line1="Orrick, Herrington & Sutcliffe",
 @address_line2="1152 15th Street, NW",
 @address_line3="NULL",
 @address_pou="RESIDENCE/CHOICE",
 @address_type=nil,
 @city="Washington",
 @country_code_fips=nil,
 @country_code_iso2=nil,
 @country_code_iso3="US",
 @country_name=nil,
 @county_code=nil,
 @county_name=nil,
 @created_at=nil,
 @effective_end_date=nil,
 @effective_start_date=nil,
 @geocode_date=nil,
 @geocode_precision=nil,
 @id=nil,
 @international_postal_code=nil,
 @latitude=nil,
 @longitude=nil,
 @province=nil,
 @source_date=nil,
 @source_system_user=nil,
 @state_code="DC",
 @transaction_id=nil,
 @updated_at=nil,
 @validation_key=nil,
 @vet360_id=nil,
 @zip_code="20005",
 @zip_code_suffix="">
irb(main):025:0> response = validate_address(validation_address)
=> 
#<VAProfile::AddressValidation::AddressSuggestionsResponse:0x00007f4c0b07d128
...
irb(main):026:0> response
=> 
#<VAProfile::AddressValidation::AddressSuggestionsResponse:0x00007f4c0b07d128
 @response=
  {:addresses=>
    [{:address=>
       {:address_line1=>"1152 15th St NW",
        :address_type=>"DOMESTIC",
        :city=>"Washington",
        :country_name=>"United States",
        :country_code_iso3=>"USA",
        :county_code=>"11001",
        :county_name=>"District Of Columbia",
        :state_code=>"DC",
        :zip_code=>"20005",
        :zip_code_suffix=>"1723"},
      :address_meta_data=>
       {"confidence_score"=>98.0,
        "address_type"=>"Domestic",
        "delivery_point_validation"=>"STREET_NUMBER_VALIDATED_BUT_MISSING_UNIT_NUMBER",
        "non_postal_input_data"=>["Orrick, Herrington & Sutcliffe"]}}],
   :validation_key=>-1916071727}>
irb(main):027:0> 
```

**Comment by holdenhinkle** [comment]
PR - https://github.com/department-of-veterans-affairs/vets-api/pull/14632

Done.

**Comment by holdenhinkle** [comment]
PRs to add github secret:

- https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/2435
- https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/2436

**Comment by holdenhinkle** [comment]
Closing this out. I'm going to make some followup tickets.

**Comment by oddball-lindsay** [comment]
Due to rate limiting in Staging, there is a huge queue of retries so Holden is retrying manually.
