### ISSUE TITLE
IA Request [Connected Accounts FAQs]

### ISSUE THREAD

**Issue by careyotto** [department-of-veterans-affairs/va.gov-team#6864]
## Background
There was a previous ticket for FAQ url for Connected Accounts that was never implemented. Since then, our needs have changed. We (ie. Lighthouse API and Authenticated Experience teams) want to link to this content from within a Veteran's account settings. Lighthouse may also decide to use this link in the original OAuth screens, as originally designed, when we revisit these screens later this year.

## Related tickets
- Request for [Copy and IA help from Lighthouse API for connected accounts #6838]([url](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6838))
- [Epic] Connected Accounts Updates #6814 
- Previous IA work done on this issue: Determine IA for Connected Accounts FAQ [#15901 ](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/15901)

## Required Inputs:
- Link to product outline ([template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md))
- Link to or attach prototype or mockups
- Link to research readout/results ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/synthesis/how-to-do-research_synthesis.md))
- Link to [reseach history masterlist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-history.md) showing that you have added your research to the list as applicable
- Link to or attach final content including H1s (if separate from prototype/mockup)

## Information Architecture Worksheet (Optional)

Provide the following information, as available, to support the final information architecture of your product.

**SEO Keywords**
- SUGGESTIONS - PLEASE ADD/EDIT AS YOU SEE FIT: 
Connected apps, Connected accounts, connecting accounts, manage your apps, third-party access, connected services, apps and websites, removing access, removing an app, Sharing your information with other websites

**Proposed site map/page structure** (if more than one page)
- Provide link or image of proposed page structure

**Suggested URL(s)**
- Previous team decided va.gov/connected-accounts-faq/. However, design team for Profile 2.0 are considering re-naming this area from 'connected accounts' to 'connected apps' (or something like that).

**Suggested entry points**
- Account settings, connected accounts screens
- List of apps page (WIP)

**Crosslinking opportunities**
- We'd like to also create a page that lists all of the apps and websites available to connect to and cross-link FAQ there. 
- TBD whether y'all will want to also bring connected accounts FAQs into here: https://www.va.gov/sign-in-faq/

**Redirects/canonical tags**
- N/A

## Definition of Done
- [ ] Issue is created, tagged and assigned to Content and IA team
- [ ] Required information above is complete and optional information provided where available
- [ ] IA reviews information and provides final feedback/recommendation on ticket
- [ ] Requesting team closes issue upon implementation
- [ ] Requesting team member complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

**Comment by careyotto** [comment]
Here is a rough draft of the content, ready for copy review. UI design will mimic https://www.va.gov/sign-in-faq/

[Connected apps FAQs for Profile 2.0.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/4372618/Connected.apps.FAQs.for.Profile.2.0.pdf)

[Connected apps FAQs for Profile 2.0.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4372619/Connected.apps.FAQs.for.Profile.2.0.docx)

**Comment by mshea0606** [comment]
closing this ticket to create combined ticket - IA Request [Third-party app directory ]+[Connected Accounts FAQs url] #7889

**Comment by mshea0606** [comment]
closing this ticket to create combined ticket - IA Request [Third-party app directory ]+[Connected Accounts FAQs url] #7889
