### ISSUE TITLE
Investigate lack of traffic to MedicalCopaysController#send_statement_notifications

### ISSUE THREAD

**Issue by kjsuarez** [department-of-veterans-affairs/va.gov-team#68655]
## Issue Description
We haven't received a call to MedicalCopaysController#send_statement_notifications since October 26th.
This ticket tracks the work of investigating why.

[Datadog traffic logs](https://vagov.ddog-gov.com/dashboard/shm-nr4-75f/debt-resolution-vets-api?fullscreen_end_ts=1698692112482&fullscreen_paused=false&fullscreen_refresh_mode=sliding&fullscreen_section=overview&fullscreen_start_ts=1696100112482&fullscreen_widget=3388158155579294&refresh_mode=sliding&from_ts=1698081814388&to_ts=1698686614388&live=true) show that the issue is not internal to our system, the endpoint just hasn't been hit since the 26th. Errors would show up [here](http://sentry.vfs.va.gov/organizations/vsp/issues/?environment=production&project=3&query=transaction%3AV0%3A%3AMedicalCopaysController%23send_statement_notifications&statsPeriod=14d)

**Comment by kjsuarez** [comment]
On October 30th we were alerted to an absence of traffic to the `MedicalCopaysController#send_statement_notifications` endpoint since Oct 26th. I reached out to VBS who are responsible for hitting this endpoint and they responded that we (debt resolution) hadn't sent them any copay statements and this was the reason for the lack of traffic. Later that day traffic started to return, so if there is an issue at all it is intermittent.

**Comment by HeatherRienks** [comment]
Per VBS mtg, this was expected; closing ticket.
