### ISSUE TITLE
migrate vets-api Elasticache into VAEC

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#6865]
## User Story or Problem Statement

The Elasticache (Redis) cluster for vets-api is the last thing that we're aware of existing in the old dsva-vetsgov-prod VPC. We'd like to migrate this out to complete that migration and remove the resources there.

Would like to do this live if possible so there's no downtime for Veterans and families. We have both Sidekiq and caches sharing the same cluster. We can have two clusters existing at the same time, so the two functions can migrate independently if that ends up being helpful.

## Goal

Redis cluster migrated into the "vagov" networks (VAEC) and out of the "vetsgov" networks (non-VAEC) so we can tear down the old VPC for prod.

## Acceptance Criteria

- [ ] vets-api is exclusively using a Redis cluster in the "vagov" networks in all environments
- [ ] old Redis clusters are terminated and subnet groups removed from Elasticache

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by wyattwalter** [comment]
Looks like staging and sandbox were already moved by Lighthouse folks. I don't think any work was done to test a migration path as sandbox just started there and I don't know the exact story on staging, but I got asked about how they might do prod after staging was done.

**Comment by johnpaulashenfelter** [comment]
@omgitsbillryan dug into this a bit w/ @wyattwalter yesterday and it doesn't seem like we can just move subnets like the Postgresql move. That means we potentially have to dump/restore data which adds a fair bit of complexity around getting sidekiq workers coordinated to drain the old redis and not duplicate the newer one

There's also now a related task to upgrade to Redis 5.0.x which is independent of this move _but_ the current cluster in VAEC is 5.0, so seems sensible to move to 5.0 first. I'll get some tickets coordinated.

**Comment by omgitsbillryan** [comment]
The strategy we've settled on is to duplicate only the "vets-api user data". "Utility data" such as breakers and rack attack rate limiting data, will simply be allowed to die and regenerate itself once using solely the vagov elasticache. For more context, see the [PR conversation](https://github.com/department-of-veterans-affairs/vets-api/pull/4210#discussion_r423078423).

**Comment by alexpappasoddball** [comment]
Reminder to break this ticket out into smaller chunks of work.  Let me know if you need any help @omgitsbillryan

**Comment by omgitsbillryan** [comment]
This ticket is mostly complete and is now in a holding pattern. We must wait 30 days for our dual-redis setup to properly copy over existing data in real time. [At the end of those 30 days, we can officially make the swtich](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9848)
