### ISSUE TITLE
IA Request [Third-party app directory a Veteran can connect to]

### ISSUE THREAD

**Issue by careyotto** [department-of-veterans-affairs/va.gov-team#6866]
## Background:
 Lighthouse API and Authenticated Experience teams want to link to an up-to-date list of **third-party apps** and services a Veteran can connect their VA data to. This content will need to be easy for the Lighthouse team to update, as we onboard new API consumers. There is a potential future use case of using this same content on developer.va.gov

For full context, there is also a [VA mobile](https://mobile.va.gov/) app store for VA apps that another dpt. owns. We are not planning on listing these apps on our page of third-party apps and services. Open to discussing it if you have a different point of view on this.

## Related tickets
- Request for [Copy and IA help from Lighthouse API for connected accounts #6838]([url](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6838))
- [Epic] Connected Accounts Updates #6814 

## Required Inputs:
- Link to product outline ([template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md))
- Link to or attach prototype or mockups
- Link to research readout/results ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/synthesis/how-to-do-research_synthesis.md))
- Link to [reseach history masterlist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-history.md) showing that you have added your research to the list as applicable
- Link to or attach final content including H1s (if separate from prototype/mockup)

## Information Architecture Worksheet (Optional)

**SEO Keywords**
- 

**Proposed site map/page structure** (if more than one page)
- Pagination to allow for growth

**Suggested URL(s)**
- 

**Suggested entry points**
- Connected accounts area a Veteran's profile settings
- [Connected accounts FAQ page](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6864) (WIP)

**Crosslinking opportunities**
- [Connected accounts FAQ page](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6864) (WIP)
- developer.va.gov

**Redirects/canonical tags**
- 

## Definition of Done
- [ ] Issue is created, tagged and assigned to Content and IA team
- [ ] Required information above is complete and optional information provided where available
- [ ] IA reviews information and provides final feedback/recommendation on ticket
- [ ] Requesting team closes issue upon implementation
- [ ] Requesting team member complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

**Comment by careyotto** [comment]
Here's a work-in-progress draft of what this App Directory page would look like. Design piggybacks off the Profile 2.0 Connected Accounts design Authenticated Experience is currently working on. This page would link to from there and also the proposed connected app FAQ page.

![App Directory - view more about app](https://user-images.githubusercontent.com/37549106/77377904-d144e600-6d31-11ea-9c10-af521875a2dd.png)

**Comment by careyotto** [comment]
**Design reviewers:** Would love your nerdy design thoughts on the "additional info" app widget in these designs. What's in the mock doesn't feel quite there. 

@tressaellen and I want to land on something that will work equally well here and on the [connected apps page](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6478#issuecomment-601813400). Have been exploring swapping out the fonts, aligning copy to the link, sticking with the design library's "additional info" link style, and other small tweaks.

**Comment by meganhkelley** [comment]
Hey @careyotto the Information Architecture request ticket (this one) is only seen and used by Mikki (VSP's IA). I'm pasting your comment over onto #7290 which is where designers will review!

**Comment by mshea0606** [comment]
closing this to combine into ticket... IA Request [Third-party app directory ]+[Connected Accounts FAQs url] #7889
