### ISSUE TITLE
[Design, FE] 10-10EZR - V2 form: SHOULD feedback - Content change on Veteran Information

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#68668]
## Background
During Midpoint review, we received [SHOULD feedback on the Veteran Information pages](https://github.com/department-of-veterans-affairs/va.gov-team/issues/68507).  

>Veteran Information
>- Address Expanded Page: Improper Sentence Structure: In the expanded field, the sentence is not formatted correctly. According to the style guide, the conditional clause should begin the sentence. In this case, the sentence should begin: “If you live on a military base outside the country…”

The update to the Additional Information accordion could read: "If you live on a military base outside the country, the United States will automatically be chosen."

## Tasks
- [x] DESIGN - Update design content for the Additional Info accordion on the Veteran's Address page
     - The update suggestion above is not concrete. Feel free to explore better options 
- [ ] Frontend - Update the UI content for the Additional Info accordion on the Veteran's Address page

## Acceptance Criteria
- The SHOULD Content feedback item has been addressed

**Comment by aliyahblackmore** [comment]
**Tracking the response to feedback here:**

**Noting that my recommendation is that updates happen before staging. 1010 team will determine if this will be feasible given their timelines - may have to happen V2.**

- Address Expanded Page: Improper Sentence Structure: In the expanded field, the sentence is not formatted correctly. According to the style guide, the conditional clause should begin the sentence. In this case, the sentence should begin: “If you live on a military base outside the country…” _We can make this update. I’ve included a comment in sketch for their team. They’ll make this update. [This is a link to the sketch comment](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/a/elo2bEj?annotation=7eda874c-552c-42a5-9c67-6543e30b60d2)._

**Comment by jessicastump** [comment]
This was noted in this [UX QA ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/69651)
- [Sketch link](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/a/elo2bEj)

**Comment by longmd** [comment]
@jessicastump / @aliyahblackmore , this sentence is hard coded into the forms library for this pattern. If you wish for this content to be corrected, you would need to go through Matt Dingee and his group for the proper updates.

**Comment by aliyahblackmore** [comment]
Thanks for letting us know, Matt!

@jessicastump since this is hard coded in the design system, let's leave this as it is for MVP. Thoughts?

If so, I'll adjust my above comment on their feedback to reflect that this is hard coded in the design system and note that I'll start a conversation with Danielle about updating this in the design system.

**Comment by jessicastump** [comment]
Yes, @aliyahblackmore - this was for a future v2 anyways. 
With this insight from @longmd - should this ticket be closed?

**Comment by aliyahblackmore** [comment]
@jessicastump not sure if you're asking me or if the above comment in for Heather, but I think that we can close this out! 


I just adjusted my above comment to note that the sentence in the additional info component is hard coded and that we'll can plan to chat more about an update to the design system ahead of V2. I'll start the design system conversation with Danielle.

**Comment by hdjustice** [comment]
Thank you @aliyahblackmore @jessicastump and @longmd !  Closing
