### ISSUE TITLE
[BE] Implement Response class

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#68697]
As a Veteran, I would like to see all my appointments when checking in.

Tasks:
- Create Response class that takes the get_appointments response and serializes it into a json response
- (TBD: still need to see the format of the response from appointments service)

**Comment by lee-delarm6** [comment]
A check to `https://veteran.apps.va.gov/vaos/v1/` fetchAppointments shows this as a success schema

`{
  "data": [
    {
      "id": "string",
      "identifier": [
        {
          "system": "string",
          "value": "string"
        }
      ],
      "kind": "clinic",
      "status": "proposed",
      "serviceTypes": [
        {
          "coding": [
            {
              "system": "string",
              "code": "string",
              "display": "string"
            }
          ],
          "text": "string"
        }
      ],
      "serviceCategory": [
        {
          "coding": [
            {
              "system": "string",
              "code": "string",
              "display": "string"
            }
          ],
          "text": "string"
        }
      ],
      "reasonCode": {
        "coding": [
          {
            "system": "string",
            "code": "string",
            "display": "string"
          }
        ],
        "text": "string"
      },
      "description": "Anesthesia consultation related to the procedure-CARDIOLOGY-1.2.6",
      "priority": 0,
      "patientIcn": "string",
      "locationId": "string",
      "clinic": "string",
      "practitioners": [
        {
          "identifier": [
            {
              "system": "string",
              "value": "string"
            }
          ],
          "name": {
            "family": "string",
            "given": [
              "string"
            ]
          },
          "address": {
            "type": "postal",
            "line": [
              "string"
            ],
            "city": "string",
            "state": "string",
            "postalCode": "string",
            "country": "string",
            "text": "string"
          }
        }
      ],
      "start": "2023-12-04T15:36:51.109Z",
      "end": "2023-12-04T15:36:51.109Z",
      "minutesDuration": 0,
      "slot": {
        "id": "jlgMGRZ",
        "start": "2023-12-04T15:36:51.109Z",
        "end": "2023-12-04T15:36:51.109Z"
      },
      "created": "2023-12-04T15:36:51.109Z",
      "requestedPeriods": [
        {
          "start": "2023-12-04T15:36:51.109Z",
          "end": "2023-12-04T15:36:51.109Z"
        }
      ],
      "contact": {
        "telecom": [
          {
            "type": "email",
            "value": "string"
          }
        ]
      },
      "preferredTimesForPhoneCall": [
        "Morning"
      ],
      "preferredLocation": {
        "city": "string",
        "state": "string"
      },
      "cancelationReason": {
        "coding": [
          {
            "system": "string",
            "code": "string",
            "display": "string"
          }
        ],
        "text": "string"
      },
      "comment": "string",
      "preferredLanguage": "string",
      "cancellable": true,
      "patientInstruction": "string",
      "telehealth": {
        "url": "string",
        "atlas": {
          "siteCode": "string",
          "confirmationCode": "string",
          "address": {
            "streetAddress": "string",
            "city": "string",
            "state": "string",
            "zipCode": "string",
            "country": "string",
            "latitutde": 0,
            "longitude": 0,
            "additionalDetails": "string"
          }
        },
        "group": false,
        "vvsKind": "string"
      },
      "extension": {
        "desiredDate": "2023-12-04T15:36:51.109Z",
        "ccLocation": {
          "practiceName": "string",
          "address": {
            "type": "postal",
            "line": [
              "string"
            ],
            "city": "string",
            "state": "string",
            "postalCode": "string",
            "country": "string",
            "text": "string"
          },
          "telecom": [
            {
              "system": "email",
              "value": "string"
            }
          ]
        },
        "ccRequestedCancellation": true,
        "hsrmTaskId": "string",
        "hsrmConsultId": "string",
        "vistaStatus": [
          "string"
        ],
        "ccTreatingSpecialty": "string",
        "modality": "string",
        "patientHasMobileGfe": true,
        "preCheckinAllowed": true,
        "eCheckinAllowed": true
      }
    }
  ],
  "failures": [
    {
      "system": "string",
      "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "status": "string",
      "code": 0,
      "traceId": "string",
      "message": "string",
      "detail": "string"
    }
  ]
}`
