### ISSUE TITLE
[BE] Add configuration to devops repos

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#68699]
Add configuration to devops repos, including private key and other settings

**Comment by loripusey** [comment]
@randomsync is this something Nate or Eric can do?
cc: @ndouglas

**Comment by ndouglas** [comment]
I asked about this [here](https://dsva.slack.com/archives/C02G6AB3ZRS/p1709651842670599?thread_ts=1709651831.977679&cid=C02G6AB3ZRS), but I think Gaurav said Kanchana had already taken care of it. Maybe this is a candidate for closure?

**Comment by loripusey** [comment]
closing, if this is not done please re-open @randomsync
