### ISSUE TITLE
[BE] Implement Controller

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#68698]
As a Veteran, I would like to see my upcoming appointments when checking in.

Tasks:

- Add route for `GET /appointments`
- Implement AppointmentsController
- Check that an authorized session exists
- Make a call to appointments, facilities, clinics and provider services to get the data and return the response
- Handle exceptions and return error as necessary

**Comment by kanchanasuriya** [comment]
Just waiting for the mockdata PR to get merged.  Will close it by EOD.
