### ISSUE TITLE
[BE] Implement get_appointments method in service class

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#68696]
As a Veteran, I would like to see all my appointments when checking in.

Tasks:
- Implement get_appointments method
- check if token exists. If not, make a call to token endpoint to retrieve the token (see TravelClaim#submit_claim method)
- for each appointment in the response, get the facility timezone and add a `local_start_time` field by converting the UTC time to local facility time

**Comment by randomsync** [comment]
seems like this will have a dependency on facilities service, since for each appointment, we'd have to get the facility for it's timezone and convert the appt start time from UTC to local

**Comment by loripusey** [comment]
Moving back to the backlog; @randomsync please make notes in the ticket on where you left off

**Comment by randomsync** [comment]
I've added some code for VAOS appointments service and #get_appointments method, include a base service and a configuration class. Here's the PR: https://github.com/department-of-veterans-affairs/vets-api/pull/15283

What needs to be done:
1. rspecs for base and appointments service
2. controller code and rspecs (lookup and validate session by uuid, instantiate appointment service by the check_in session object and call get_appointments) #68698
3. base service will need to be updated to take in session object instead of patient_icn, will need a icn lookup method in redis_client
4. other tasks as the tickets have already been created: pulling facilities, clinics data, putting it all through a serializer and returning response

**Comment by loripusey** [comment]
@kanchanasuriya can you validate and close this before planning today please?
cc: @anita-halici

**Comment by loripusey** [comment]
@lee-delarm6 ^^^^
