### ISSUE TITLE
Update Travel MSA & Veteran FAQs

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#68701]
## Background
[Slack thread](https://dsva.slack.com/archives/C022AC2STBM/p1698759185696349)

## Tasks
- Make the updates to the MSA FAQ & the Veteran FAQ (if appropriate) based on Kay's comments in the following PDF.

[FAQ How to file travel pay (003)_KL edits.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/13217408/FAQ.How.to.file.travel.pay.003._KL.edits.pdf)

**Comment by kellysmith1008** [comment]
@loripusey I completed most of the suggested edits today - there are 2 remaining that I'm going to ask Kay for input on:
- What she means by her first comment of adding what this looks like to BTSSS staff
- Rewriting it from first person to third person. 

I'm including a copy here for you to look at as well. I did find some additional areas where content had been repeated in the version she provided for us, so I made sure to remove that too. I'll ping her in the check-in-experience slack channel unless there's a better channel I should use?
[FAQs_Travel_Reimbursement_November_2023.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0tZQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--92dca408b8967b2eef64545aca8bda1bd6b4215b/FAQs_Travel_Reimbursement_November_2023.docx)

**Comment by loripusey** [comment]
Looks good so far.

**Comment by kellysmith1008** [comment]
Thanks! Posted in the [slack thread](https://dsva.slack.com/archives/C022AC2STBM/p1698759185696349) for Kay to review as well.

**Comment by kellysmith1008** [comment]
We received approval from Kay and Mark in slack (same thread as above) on this version @benbrasso-agile6 Can you upload this into the sharepoint file again? Then I think this ticket can be closed. Thanks!
[FAQs_Travel_Reimbursement_November_2023.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOSsyQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--71c4cb677a3d4877ebb94df1d1db5683e569e325/FAQs_Travel_Reimbursement_November_2023.docx)

**Comment by benbrasso-agile6** [comment]
https://dvagov-my.sharepoint.com/:w:/g/personal/benjamin_brasso_va_gov/EWWhR8tBk_5KkwvbK504sSkBKowqlwy0CTlpbU264XFWlQ?e=nSuWQ4

@kellysmith1008

**Comment by kellysmith1008** [comment]
Thanks Ben!! I appreciate you! I'm going to close this ticket :)

**Comment by benbrasso-agile6** [comment]
For clarity, I didn't send that link to anyone or anything. Just dropped it in here for you!
