### ISSUE TITLE
Determine a solution to the Lighthouse-returns-2XX-but-actually-fails problem

### ISSUE THREAD

**Issue by Thrillberg** [department-of-veterans-affairs/va.gov-team#68700]
https://dsva.slack.com/archives/C044AGZFG2W/p1698428346629329

The Lighthouse Benefits Intake API can respond to a request with a 2XX status but still fail later on. This failure ends up being silent to the client (`vets-api`) and we've apparently dropped some form submissions due to this. The task here is to track down a solution. At the moment it appears that polling Lighthouse may be the way this is handled elsewhere but I'd like to explore other possibilities, too.

**Comment by Thrillberg** [comment]
Steve Albers is on the case and will get back to me.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2lLQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bae74462a886fb7691bfaacf05bcc0d7c620dffd/Screenshot%202023-10-31%20at%2011.56.04%20AM.png)

**Comment by Thrillberg** [comment]
@tbaker1026 Update on this:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMk9aQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--87f0d6601dcd59beb21db97f8fc17884a0f72973/Screenshot%202023-11-02%20at%2011.34.11%20AM.png)

Overall doesn't sound like much has been done so far, and certainly nothing firmly established. Do we want to look at Thomas' manual process and try to replicate that? Ideally, we'd have something automatic rather than manual but I'm not sure how urgent this is. (And even more ideally it wouldn't rely on polling but would let us receive calls from Lighthouse to notify us)

**Comment by Thrillberg** [comment]
Here's an update of where we are. Earlier this week we had a large meeting across several teams to try to get on the same page about this. Results that are relevant to us:
- Sam Stuckey of Benefits & Claims will write a bulk polling script (draft here: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/benefits/scripts/526/benefits_intake_polling.md)
- Thomas Blackwell of Benefits & Claims will help me resubmit failed submissions next week. (Along with Steve Albers)

**Comment by Thrillberg** [comment]
@tbaker1026 Can we close this issue? I feel like we have this much more under control than we did when we wrote the issue :)

**Comment by tbaker1026** [comment]
@Thrillberg closing
