### ISSUE TITLE
Create a Poster Version that Includes Information about Submitting a Travel Claim During Check-in

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#68734]
## Background
In the PCI Pilot meeting on 10/31, the group asked to have a poster version that includes information that the Veteran can submit a travel reimbursement claim as part of the check-in process.

## Tasks
- Create a new poster version (one for US & one for Philippines) that includes information about submitting a mileage-only travel claim
    - Please coordinate with Kay to add this information.

NOTE: Kay also mentioned the possibility of eventually handing ownership of the posters over to the communications team.

**Comment by kellysmith1008** [comment]
Zach and I are working on the content and location ideas now, bringing in UX as needed in the [sketch file](https://www.sketch.com/s/9798426e-bba3-46dd-9d87-73d77dcf6599/p/AB7A3870-3FC1-4DE0-8291-0D06211ECA6E/canvas)

**Comment by zach-park** [comment]
@benbrasso-agile6 @kellysmith1008 , poster variations (3) are ready for review:
https://www.sketch.com/s/9798426e-bba3-46dd-9d87-73d77dcf6599/p/AB7A3870-3FC1-4DE0-8291-0D06211ECA6E/canvas#Version

**Comment by benbrasso-agile6** [comment]
I like 1 and 3. Maybe show both to Kay. But, see what Kelly says first in the morning.

**Comment by kellysmith1008** [comment]
I like number 3 the best, but agree maybe show 1 and 3 to Kay.

**Comment by benbrasso-agile6** [comment]
@zach-park this ready to be sent to Kay in slack soon? Just wanted to mention since it's marked as high-priority. TY!

**Comment by benbrasso-agile6** [comment]
Who's doing the posting in slack?

**Comment by benbrasso-agile6** [comment]
I would just start a new post in #check-in-experience for "Updates to Poster for Travel" and tag Kay

**Comment by zach-park** [comment]
> I would just start a new post in #check-in-experience for "Updates to Poster for Travel" and tag Kay

Posted: https://dsva.slack.com/archives/C022AC2STBM/p1699547321530379

**Comment by benbrasso-agile6** [comment]
Waiting on Kay

**Comment by loripusey** [comment]
We are no longer maintaining posters, closing this. If Kay has suggestions, she will pass them along to the team that will now be maintaining these.
cc: @zach-park @benbrasso-agile6
