### ISSUE TITLE
[UX] [Design] Create wireframe for scenario when checkbox isn't selected

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#68746]
## Description 

Need to figure out the UI solution for, on the Review claim page, what appears when the checkbox is not selected and the user attempts to submit the form. 

I believe the most updated guidance is here: 

I think we'd want to follow the guidance on row "Required form field is empty" of [Feedback messages - VA.gov Design System](https://design.va.gov/content-style-guide/error-messages/feedback)

So, we're creating a submission not complete wireframe for this [Review page](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/el82YJW?annotation=cb30a969-2d52-4a49-8d72-2b0efb1d395a&utm_medium=email&_hsmi=210989272&_hsenc=p2ANqtz-_c_awnwFLTKcfHfOARWnvnPTzjEY09q2DYOd2hHfa5JQLU3QtG163ItGkVn_T0VbyhaBZyCUPJSU3S9G16LhiWUZmhkw&utm_source=hs_email#Comment)

[USWDS Story book](https://design.va.gov/storybook/?path=/docs/uswds-va-statement-of-truth--default#stories)
[VA library sketch file](https://www.sketch.com/s/a52734dd-00d0-44f1-9c9e-ff4016130e5c/p/EB404E82-9D9D-4D3F-BEDC-00D323499F1D/canvas)

NOTE: we need the Veteran to continue checking-in regardless of whether they agree to the terms of agreement or not

## Tasks

- [ ] Create wireframe and add to [Review Page in sketch](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/6517BA8C-BADD-478E-9380-4F59F467423F/canvas)
- [ ] Run by #platform-design-system if needed or #veteran-facing-forms

## AC 

- Wireframe completed, validated and approved by VA governance

**Comment by zach-park** [comment]
Yes, working on it today. :)

**Comment by zach-park** [comment]
@benbrasso-agile6 @kellysmith1008 , ready for review:
Note: There are two options: https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/0F0F5A52-BB73-4D8E-AA4C-7AA8E389AF15/canvas

**Comment by benbrasso-agile6** [comment]
v2 works for me, nice job zach
