### ISSUE TITLE
CF: Analytics 

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#6876]
- [x] Identify metrics for success
- [x] Evaluate with DEPO / EDU
- [x] Work with DEPO analytics team to implement

**Schedule Analytics Request meeting (30 minutes) with VSP team and include the following applicable information:** 
- [ ] Objectives and definitions of success (e.g. a specific user interaction or final URL) for the product are documented. 
- [ ] Authenticated user logins for testing are captured as necessary; when applicable do not put staging credentials in your va.gov-team ticket; store or reference them in a .md file in the va.gov-team-sensitive repository
- [ ] The URL(s) for your product including any unauthenticated landing pages that precede the start of the tool. For example, if your product is a multi-step veteran-facing tool, please provide the full path of URLs along noting any conditional logic that would take users to a different branch of URLs for the tool
- [ ] All of the above content has been shared with the VSP team in advance of the meeting

**Comment by amyknox** [comment]
Ask DEPO about
- click through on CF message
- click through to school page

**Comment by amyknox** [comment]
Slack Q&A w VFS analytics

> We’re working on Caution Flags on within the GI Bill Comparison Tool. We’re including a general “View details below” jumplink in the Caution Flag at the top of the institution profile page.  (Sample profile page with caution flags here https://staging.va.gov/gi-bill-comparison-tool/profile/31000143)
>
> The jumplink leads to the “Cautionary information” accordion and the full content of the caution flag, often with a link to the school or another external source with more info.  (In the live version the link opens a modal, that functionality is being retired)
>
> Tracking each of these interactions on a per-school basis seems excessive since the numbers would be quite small but general, aggregated info on whether these links are used would be helpful.
>
> Curious if we could track general use of this caution flag jumplink at the top of profile pages?
>
> And if we could track aggregated clicks out of the Comparison Tool on the external links in the “Cautionary information” accordion?

Per Jon

> Yes both of those items are possible. I would recommend us putting direct tracking on the 'View cautionary information about this school' link click at the top to signify the user jumped inside the "Cautionary Information" accordion . For the embedded links within the "Cautionary Information" accordion, looks like they're mostly set to head to benefits.va.gov/gibill we can certainly get tracking on these as well if they would be helpful. @Brian Martin and I would connect on the best event syntax there for those clicks.


Work with Darrell, as Product Mgr, to submit analytics request
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#analytics-request

**Comment by amyknox** [comment]
@dneel-bah @desireeturner - think we need to carry this over due to new VSP Collab / Analytics Request... we have to submit a story AND meet with VSP Analytics to review.

**Comment by amyknox** [comment]
@dneel-bah to submit once dependencies (6805, 7151 and 7263) are cleared.

**Comment by desireeturner** [comment]
@dneel-bah is waiting on #7743 to submit this.

**Comment by dneel-bah** [comment]
Submitted analytics request #8001.
