### ISSUE TITLE
Wrong GA event sent when clicking the new 'Start scheduling' action link

### ISSUE THREAD

**Issue by vbahinwillit** [department-of-veterans-affairs/va.gov-team#68760]
## Summary
When the 'va_online_scheduling_start_scheduling_link' feature flag is turned on and user clicks the 'Start scheduling' action link, the wrong GA event is generated. This is due to the coding logic being behind the wrong feature flag.

## Specs
- Device: All
- Browser: Chrome

## Steps to Reproduce
**Test User:** 
Any user

**Prerequisites**
Turn on 'va_online_scheduling_start_scheduling_link' feature flag
Turn off 'va_online_scheduling_breadcrumb_url_update' feature flag

1. Go to: https://stage.va.gov/my-health/appointments
2. Click 'Start scheduling' action link
3. Open Chrome Developer Console and type 'window.dataLayer' to view GA events
4. Verify 'vaos-start-scheduling-link' event exist

### Actual Result
The 'vaos-schedule-appointment-button-clicked' event exist and the 'vaos-start-scheudling-link' event does not. 

### Desired Result
The 'vaos-start-scheudling-link' event should exist and the 'vaos-schedule-appointment-button-clicked' event should not.

## Definition of Done
- [ ] Desired result is achieved and/or document decisions made
- [ ] Relevant documentation is updated

---
## How to configure this issue
- [ ] **Labeled with Team** (`vaos`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `design`, `product`)
- [ ] **Labeled with** `Bug`
- [ ] **Assigned to** Product for prioritization

**Comment by JRRoof** [comment]
Tested - correct event is being triggered.
