### ISSUE TITLE
CT: Infinite Spinner: Content	

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#6877]
Draft / identify relevant content for all instances of spinner

**Comment by amyknox** [comment]
**We’ve run into a problem**
We’re sorry. Something went wrong on our end. Please try again or check back soon.

{ button on all pages except GIBCT landing page }

**Comment by desireeturner** [comment]
@amyknox I've added this content to #6662. Thanks!
