### ISSUE TITLE
Integrate Content Review ROE into onboarding and review w/By Light

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/va.gov-team#688]
Definition of Done
- [x]  Content ROE doc has thumbs up from DSVA and Prod Dev Support
- [x] Content ROE doc is linked to from Onboarding collateral
- [ ] Meeting has happened w/By Light to go over Content expectations
- [ ] Have idea of what ongoing interactions should look like for doing content reviews

**Comment by peggygannon** [comment]
**7/25/19 update** 
Content review document shared with DSVA (Leah and Patrick) and Product Dev support PM (Leah)

**Comment by peggygannon** [comment]
**7/30/19 update:** DSVA (Leah and Patrick) and Andrea from Product support have provided feedback/approval on Content review doc.

**Comment by peggygannon** [comment]
@rroueche Hi, Rachael, I think we can close this one. The last bullet on Def. of Done is being tracked in another issue (https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/693)

If you agree, then I'll close it out.
