### ISSUE TITLE
[FE] 10-10EZR - Standalone form: Increase Unit Test coverage to 80% or more

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#68801]
## Background
As part of the [Platform QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-unit-test-coverageUnitTestCoverage), we must have 80% or higher Unit Test coverage.  If this standard is not met, it is considered launch-blocking.

At this time, we are below 80% for functions and statements.  We want to create an automated way to check for unit test coverage and see where the gaps are.

## Tasks
- [x] Create and run unit tests to ensure we are meeting/exceeding the 80% standard for all four criteria (Lines, Functions, Branches, Statements)
 
## Acceptance Criteria
- We have an automated tool to help us stay at or above the 80% Unit Test coverage, and the EZR now meets that standard.

**Comment by longmd** [comment]
@hdjustice , worked some big magic to pull this one off... 

![screencapture-file-Users-matthewlong-Documents-Projects-vets-website-coverage-index-html-2023-11-10-17_13_24](https://github.com/department-of-veterans-affairs/va.gov-team/assets/6738544/6fd981bc-d19e-4a83-820b-86fd0598afdf)

**Comment by hdjustice** [comment]
Wow @longmd that is amazing!
