### ISSUE TITLE
[FE][BE] Staging validation for Appointments Service Integration

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#68803]

**Comment by brianseek** [comment]
test failed resulting in this ticket: https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/89875

**Comment by brianseek** [comment]
closing this, we can make a new ticket for testing when we are ready again.
