### ISSUE TITLE
SOCKS access for Michael Clement

### ISSUE THREAD

**Issue by michaelclement** [department-of-veterans-affairs/va.gov-team#68829]
### Your Name

Michael Clement

### Your Email

michael.clement@adhocteam.us

### Your Role and Team

Frontend Engineer on CHAMPVA

### Product Manager (PM) name and email

Heather Rienks - Heather.rienks@va.gov

### Product Owner (PO) name and email

Premal Shah - Premal.shah@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDjyAFebY7hY801TtDefIVaGyQg4U/y0p9bUxDggA7W5uzN1Vi4SHJNPuCeNQGhN9GhJPdmUgQ69Em4TvTRBRqrKXyX5AHgTa41763+qekn5PeMvCl7AvD1LPzB5y7pjzOtxzktgq1auaMEyRh8nDvBwCdxRN5tUtde33kBEsjC8kl1f/EJVchpuW1nZOZ4h21lWSS9b6xZk7XenaBcucQeROa3r2jbyaixWTTUjGdBBC37AZwFHoJzuEIJK7BqloySwQ+hQf8cs8p1X58WyzNabU2XGb4++NodDhUtnPobYiLzY6FG/+daWMU3cRddreZUUI/EGZ6XpY/0Z0F8D5oMXbIDboNQbe4VFCJ+yAuTMRrpjQLIFBcOJtMgmGiniWby0uZ1hu4Y3FLpspiL7+OcFvsq0AdIGgHtEfO7mh/iEJCbDmnpvAFQG4XEe0bWuBwSMSvYT9lo7ooRNvzmgiALsbAcPp1NldMS5nQwzQNp5ViTQfCdQh5fyMVY9c+eMBs= michael.clement@michaelclement-M6W4MVNJJ7

### E-QIP Transmittal Confirmation

I do not have an E-QIP transmittal notice because I had a previous background investigation in place prior to being hired on. I have attached the email stating that fact below. Additionally, I have been favorably SAC adjudicated at this point.

![transmittal_notice](https://github.com/department-of-veterans-affairs/va.gov-team/assets/18408628/d1cec678-3820-43d1-8cb0-b01c202d4c61)

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by hgbarreto** [comment]
@michaelclement Access granted ✅

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Reach out in #vfs-platform-support if you have any trouble.
