### ISSUE TITLE
[BE] Implement ClaimsToken class

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#68824]
As a Veteran, I would like to see all my appointments when checking in.

The claims token class will provide the signed assertion claims to the client class to be used for token call

Tasks:
- Create ClaimsToken class
- Add sign_assertion method to provide a signed assertion with claims and the RSA key

**Comment by loripusey** [comment]
According to @randomsync , we don't need this anymore, closing
