### ISSUE TITLE
SOCKS access for Hasan Yusuf Ahmed

### ISSUE THREAD

**Issue by hasahmed2** [department-of-veterans-affairs/va.gov-team#68835]
### Your Name

Hasan Yusuf Ahmed

### Your Email

hahmed@ironarchtech.com

### Your Role and Team

Full Stack Developer on Veteran Digital ID Team

### Product Manager (PM) name and email

Matt Reilly matt.reilly@adhocteam.us

### Product Owner (PO) name and email

Ryan Thurlwell ryan.thurlwell@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDNcmSFUSWVOPVvGpfCgtxKU1/iivOi/xk2sup2sr+JHQ15subMtisuU6u5lA4qXwMcWBrJj0ANuLU/g0RWvpnu7BUtnc9Ynb8xOd+zIj+6XfCo7b6ZlUZ7uhBkKEU7kEXxDUXtB5YeTn2CZrCaYA6G2oSUi1Krz2zNjAwBuWbFafapWqoz9ua09jkid7vxgDvf9S4Eb/p23XCB6QtXk9/Ko1qy+SeRUyOGu0aeLcfkuZ4ZbXHkeSnUwS0VFQwcHznedjF+ZfvbNlfHdDgIX2olJvmPjDPQronbibZ8YuwaL7vdGdazso/qPnHNtuaXkmk9GeBu4suZbKXhx3mkVX+9pci1cwP2lzROgZ6s+B2/no441xgldCh19gFvsvbCqIEMuZ6v9yCAQB3jKCjTmJ+hN1rnu2Kg5xuGhAdbsPDBUhXhi/dA62isvpbbaW1E8vblT6aYQcCU3zdgHjBGIpbJTR9j9mWPWbr1Ai+UWQFMqh9FkhxmQkCDefbxfm7dv58= hasan@LAPTOP-PF3X39PA

### E-QIP Transmittal Confirmation

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/148818278/62defe28-fdab-4e50-a5f0-19969990c8a0)

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by hgbarreto** [comment]
@hasahmed2 Access granted ✅

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Reach out in #vfs-platform-support if you have any trouble.
