### ISSUE TITLE
Login.gov Onboarding : Ensure developers have access to integration dashboard

### ISSUE THREAD

**Issue by porta-antiporta** [department-of-veterans-affairs/va.gov-team#68844]
# Context

Now that we have reviewed the onboarding documentation, we should now access the Login.gov integration [dashboard](https://dashboard.int.identitysandbox.gov). 

Everyone on the team should have access to this dashboard (dev, design, product). If not, ping @lmorris3 to add you.

So within the dashboard we have configured a team for our team. That team in the dashboard can now create "apps" capturing integrations at will.

This dashboard is used to configure: 
- what type of application ours is (i.e. IAL1 or IAL2)
- upload our public cert for encrypting the authentication response so that only we will be able to decrypt it.
- endpoints etc

This story is to ensure everyone developing code for the IPP applications accesses the dashboard.

# Acceptance Criteria
- [ ] Log into the dashboard using the Login.gov account you created in `int` in the previous onboarding story
- [ ] Confirm you are able to see the team and create an application
- [ ] Create a public / private cert and upload the public cert to the dashboard
- [ ] Delete application if you so wish

## Questions
- does everyone need to complete this? Or who?
- if so, please provide step-by-step instruction for how to setup an account

**Comment by skirkman16** [comment]
Added Josie to the dashboard

**Comment by porta-antiporta** [comment]
Re: Questions: 
- who needs to complete : any engineer working on integrating Login.gov to our applications will need to complete this. given we are the LGA team, however, everyone should be familiar on how to setup a Login.gov account.

- to setup an account :  Recommend going to [integration dashboard](dashboard.int.identitysandbox.gov) and clicking sign-in and following the prompts.

**Comment by mateoclarke** [comment]
- [x] Log into the dashboard using the Login.gov account you created in `int` in the previous onboarding story
- [x] Confirm you are able to see the team and create an application
- [x] Create a public / private cert and upload the public cert to the dashboard
- [ ] Delete application if you so wish

**Comment by mateoclarke** [comment]
I connected with Anu via Slack and she said she's good on the above tasks.

@rdvyas, were you able to login or do you need help troubleshooting? Lmk so we can close out this issue.
