### ISSUE TITLE
Create list of remaining errors after historical + modern rerun

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#68840]
For any historical errors: 507 remaining plus any "modern failures" occurring between Jan 9 2023 and Oct 31 2023 create a list of remaining submissions grouped by error and next steps:

AC:
1. Create spreadsheet of remaining submissions
2. For each submission provide error / reason.
3. As part of this ticket we need to determine best way to compare remaining historical errors with recent catastrophic errors. Need to work with VA to determine data needs. 
4. combine with master list of 526, 686 CY failure list and add next steps for each

**Comment by SamStuckey** [comment]
CLOSING: This work has been better captured in multiple tickets, and most of this was probably handled in the audit. However, if there are any stragglers to capture, [that work is better represented in this ticket](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/85076)
