### ISSUE TITLE
Develop a sign in page for proofing agent application

### ISSUE THREAD

**Issue by porta-antiporta** [department-of-veterans-affairs/va.gov-team#68847]
## Problem

Proofing Agents will need to authenticate to access the PA application. 

Proposed Solution: 

Proofing Agent will sign in to Identity Toolkit separately. Proofing Agent will go to a landing page on our app that has a sign in page. Login.gov has a setting that will force them to use their PIV to sign in. There's a field called acsr (set to hspv12 value). We can use a similar landing page for PAs as for Veterans - application has a "Sign in with Login.gov"

Questions:
- do we treat this as one application, role based? Or two apps? Recommend treat this as two applications
- 

## Acceptance Criteria
GIVEN I am authorized to perform Proofing Agent duties for Veterans
WHEN I enter the IPP Proofing Agent url on my machine
THEN I will see the IPP Proofing Agent application
AND a "Sign in with PIV" button/link
WHEN I click that link
THEN I will see the Login.gov "acsr" (set to hspv12 value) that requires my PIV to sign in
WHEN I enter my PIV and my PIN
THEN I will return to the IPP application home page
AND I will be signed in as a Proofing Agent

url: - url: ... ... /in-person-proofing/proofing (can refine this based on where the application is hosted/splits off)

Mockup:

<img width="1125" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFBQQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5de148e071d8daac405daa4153e47e62632e878d/PA%20Landing%20Option%201.png" alt="PA Landing Option 1.png" />

**Comment by lmorris3** [comment]
@mateoclarke @moanu404 Designs are complete. This is ready for development.

**Comment by skirkman16** [comment]
https://www.figma.com/file/PfrWKmxiQ5RjChwx6I18QE/IPP-Prototypes?type=design&node-id=2576%3A2274&mode=design&t=jmtCXKjl8dE8c7q9-1 See 'IPP Landing Pages' for designs

**Comment by mateoclarke** [comment]
This is complete and demoed to VA stakeholders on 3/13. Will be merged with PR https://github.com/department-of-veterans-affairs/va-in-person-identity-proofing/pull/36
