### ISSUE TITLE
Process authentication response

### ISSUE THREAD

**Issue by porta-antiporta** [department-of-veterans-affairs/va.gov-team#68846]
# Context

Now that we've been able to properly compose the authentication request, it's time to process the authentication response. Unlike the authentication request which is triggered from the client, the authentication response is done fully on the back end via JWT exchange over a TLS connection.

Much of the encryption / signing is reversed.
1. Login.gov will sign the response with their private cert so we can confirm it's a legitimate message
2. WIll have to retrieve JWT from back end
3. Login.gov will encrypt the payload with our public cert (which we uploaded in the dashboard) so its protected from eavesdropping.

# Acceptance criteria
- [ ] Able to retrive JWT response from API endpoint
- [ ] Able to parse out UUID from JWT response
- [ ] Able to parse out email from JWT response

**Comment by mateoclarke** [comment]
Completed with https://github.com/department-of-veterans-affairs/va-in-person-identity-proofing/pull/30
