### ISSUE TITLE
Develop an Intake "Sign In" page for Veterans

### ISSUE THREAD

**Issue by porta-antiporta** [department-of-veterans-affairs/va.gov-team#68842]
## Context

Given we want _only_ recruited Veterans to see IPP, we cannot rely on Login.gov implementing the opt-in to IPP page as that will be available to any user hitting Login.gov from va.gov. That handoff provides the UUID/email to our intake application.

Instead, we will have a user "authenticate" into the intake application. By doing so we know that the user has authenticated into their Login.gov (IAL1) account from which Login.gov will send UUID/email.

So in order to do so, we need a sign in page/link for the intake flow.

Proposed solution: have a url to our intake application that shows a "sign in with Login.gov" button or link. They would go to the Login.gov sign in/create account page (login.gov automatically sends the user back to our application with the UUID).

## Acceptance criteria
GIVEN a Veteran has received a link to our application for the pilot
WHEN they click the link
THEN they see a page with a "sign in with Login.gov" button/link
WHEN they click the button/link
THEN they are taken to the Login.gov sign in/create account page
WHEN they enter a valid username and password
AND click Sign In
THEN they will return to the IPP application
AND the UUID will be passed from Login.gov to the IPP application
AND they will be on the Veteran intake home screen

- Veteran can access a url to our application with a direct link to Login.gov sign in/create account page
- Veteran can sign in to an IAL1 account (or create one) from the url
- UUID is passed to our intake application
- url: ... ... /in-person-proofing/intake

Notes/Questions:
- how will we send the Veteran the url? From Perigean in an email?
- What if the user creates an account on Login.gov instead of signing in to an existing? Will this still work?

Mockup:
<img width="1161" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWhDQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1dceb010f70f6f2a2e559b7c1cb28e1696968610/Intake%20Option%204.png" alt="Intake Option 4.png" />

**Comment by lmorris3** [comment]
@skirkman16 this is what we need for pilot, though it's separate from the flow once we're into the post-pilot, MVP phase
