### ISSUE TITLE
Compose authentication request

### ISSUE THREAD

**Issue by porta-antiporta** [department-of-veterans-affairs/va.gov-team#68845]
# Context

Now that we have access to the integration dashboard, it's time to compose an authentication request to Login.gov from our application

Key things to consider:
- We will need to sign our request with our private cert (from the public/private pair) so that Login.gov can confirm it's a legitimate request from an application registered in the dashboard
- We will then need to encrypt information using Login.gov's public certificate (link available in developer.login.gov)
- The authentication request will have an acr_value of `IAL1` (remember intake application only needs UUID/email)
- Who/how will the NONCE be generated?

# Acceptance Criteria

**Comment by mateoclarke** [comment]
These requirements are included in this PR demoed to Tom on 2/14:
https://github.com/department-of-veterans-affairs/va-in-person-identity-proofing/pull/30
