### ISSUE TITLE
Login.gov Onboarding for IPP: Review documentation and sample apps

### ISSUE THREAD

**Issue by porta-antiporta** [department-of-veterans-affairs/va.gov-team#68843]
# Context

Login.gov has an integration dashboard designed to facilitate integration between applications. This exchange is described at a high-level at developer.login.gov.

Login.gov also has a [sample application](https://int-identity-oidc-sinatra.app.cloud.gov/) who's [codebase is open source](https://github.com/18F/identity-oidc-sinatra), from which we could borrow / understand code flows that work.

This story is to get folks to review this documentation in preparation for integrating our application.

# Acceptance Criteria

- [ ] Reviewed developer.login.gov intro and OIDC tab
- [ ] Create a login.gov account in the int environment using the sample app (this will be used for later stories in this epic)
    - [ ] Create those login.gov accounts with your MO or Greenthreads email
- [ ] Confirmed they see the code base of the sample application and can see where the Login.gov integration related code is

**Comment by mateoclarke** [comment]
- [x] Reviewed developer.login.gov intro and OIDC tab
- [x] Create a login.gov account in the int environment using the sample app (this will be used for later stories in this epic)
- [x] Confirmed they see the code base of the sample application and can see where the Login.gov integration related code is: https://github.com/18F/identity-oidc-sinatra/blob/main/app.rb
