### ISSUE TITLE
AWS access for [Tai Wilkin]

### ISSUE THREAD

**Issue by TaiWilkin** [department-of-veterans-affairs/va.gov-team#68857]
### COR Name

Eunice Garcia

### Vendor Onboarding Representative Name

Other - please specify in 'Additional Notes'

### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Tai Wilkin

### Your Email

tai.wilkin@coforma.io

### Team, Role, and Company of the target individual

VADS Pension and Proactive Benefits, Engineer, Coforma

### Product Manager (PM) name and email

Vicky Belissimo, vicky.bellissimo@adhocteam.us

### Product Owner (PO) name and email

Emily Theis, emily.theis@va.gov

### Desired AWS Access

[dsva-vfs-developers and dsva-vagov-developers](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf) look like the correct groups, but please see "Additional Notes" for my use case and advise if alternative permissions are more appropriate

### Access Expiration

12/31/2023

### E-QIP Transmittal Confirmation

<img width="997" alt="Screenshot 2023-10-27 at 10 05 55 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/21046714/0547f7fa-3ba3-4bf1-a69e-e6ea3b1ca863">

### Additional Notes

VOR Jeff Langworthy

I'm attempting to [add a new external service](https://depo-platform-documentation.scrollhelp.site/developer-docs/adding-a-new-external-service-integration) for VR&E. As part of this, I will need to access the forward proxy instance (which I believe is in AWS) and to add a new API key to the AWS parameter store in various environments. 

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by hgbarreto** [comment]
User found in [VFS Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)

**Comment by hgbarreto** [comment]
@TaiWilkin - I have reached out to via slack to hand over the AWS credentials.

**Comment by hgbarreto** [comment]
AWS credentials have been sent to user. Closing
