### ISSUE TITLE
Make Alerts Dismissible per Wireframes

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#68866]
## Wireframes
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0dSQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--590db430177254b4922e49a556fa948183fec53e/image.png)

## Tasks
- Make Alerts Dismissible per Wireframes

**Comment by cgednalske** [comment]
@brianseek @wullaski here's the [dismissible alert UX spike ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/57894) with more background on that decision in the the comments

**Comment by brianseek** [comment]
@loripusey / @cgednalske / @benbrasso-agile6 this is merged into the unified branch and is ready for validation. See screen cap below
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTN4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c0179e2b8d85480a4658f643b05ca6eae2c5e86e/dismiss-alert.gif)

**Comment by benbrasso-agile6** [comment]
Nice @brianseek 

Comma after 21

`21, 1:53:pm`

**Comment by brianseek** [comment]
@benbrasso-agile6 that is not part of the scope of this ticket but I will tag @wullaski to see if that can fit in another existing ticket or if it needs a new one.

**Comment by loripusey** [comment]
@benbrasso-agile6 can you just create a bug ticket in the same Epic?

**Comment by benbrasso-agile6** [comment]
https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/70340
