### ISSUE TITLE
Research: Create and finalize conversation guide

### ISSUE THREAD

**Issue by djones2113** [department-of-veterans-affairs/va.gov-team#68867]

**Comment by djones2113** [comment]
[Working draft of conversation guide is here](https://docs.google.com/document/d/1j2_rH0OS_l3WVK9Irfpq9MyhGGHW5Un8gpZweM6V-N4/edit)

**Comment by gmaciolek** [comment]
I've reviewed and given feedback on the conversation guide.
I also created PDF versions of the original and modified letter to be used in research sessions:

Letter PDF links:
[short version (modified)](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmVUQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3295055731a763c06a8a56a75099f147bffafa80/Proactive%20Benefits%20Letter%20-%20short%20version%20-%20clean%20copy%20for%20research.pdf)
[longer version (original)](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmFUQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7c82024d5806d58da533b6582e040980fb91f7fa/Proactive%20benefits%20letter%20-%20longer%20version%20-%20clean%20copy%20for%20research.pdf)

**Comment by djones2113** [comment]
This has been submitted and approved!
