### ISSUE TITLE
Business intake form for VA Northeast Ohio Healthcare Systems- 5 digit short code for Environment of Care

### ISSUE THREAD

**Issue by Onequa** [department-of-veterans-affairs/va.gov-team#68861]
Your Details
1.	Onequa Brown

2.	Quality Management Consultant
(ex., claims, health, etc.)

Notification Details
1.	Notification type Both
(email, text/SMS, or both)

2.	Please describe your use case. The purpose of this request is to be provided a 5 digit code for emails and text messages. I would like to post this throughout the medical facility. In a perfect world the code would also be synced with a QR code end users can scan and mimic the same results. I would love if the code could mimic a 5 digit hotline extension where end-users can also leave voicemails. The 5 digit code will be used at all CBOCs and our main facility. The end-users would be everyone- Veterans, family, visitors, contractors, students, staff, etc.
The code will be used to communicate environmental concerns. I would like them to text the number regarding a dirty floor, stained ceiling tile, blocked fire extinguisher, free standing oxygen, no supplies, no soap, etc. Any concerns related to Logistics, EMS. Engineering, Safety, all services.
(This is your chance to tell us an overview of your plans.)

3. What actions can the user take based on the notification they receive? So the app will be completely end user driven. The end user will text "EOC" to the 5 digit number. The number will respond back either confirming it is ok to text (if necessary) or with a generic phrase "Thank you for allowing us to keep our facility safe and clean, please reply with the exact location of your improvement request and the closest room number. Please tell us exactly what we can do to improve our appearance. Please dial 911 for all emergencies, Suicide & Crisis Line 988"
Once the end user responds another message will be sent out "Thank you for contacting VA Northeast Ohio Healthcare Systems Quality Management Department. Be sure to include the exact location and closet room number.
(ex., view secure messages, fill out a survey, schedule an appt, etc.)

4. What is the desired business outcome? The desired out will be an clean and safe environment for Veterans and staff, continued compliance with Joint Commission Standards and OIG recommendations. We will increase the number of individuals reporting deficiencies and this will give the facility an opportunity to improve as many environmental deficiencies they can before surveys.
(ex., fewer skipped appointments, less call center volume, etc.)

5. What system will kick off the notification? Please note the system should be inside the VA or have an ATO. The notification will be end user driven. When the end user scans the code the notification will initiate.
(ex., BVA hearing reminders are kicked off from Caseflow)

6. What will trigger the notification? The end user scanning the QR code or texting the 5 digit extension.
(ex., clicking submit, status updates for claims, appointment reminders, new services available)

7. **Provide sample content per notification type, if you have it.**So the app will be completely end user driven. The end user will text "EOC" to the 5 digit number. The number will respond back either confirming it is ok to text (if necessary) or with a generic phrase "Thank you for allowing us to keep our facility safe and clean, please reply with the exact location of your improvement request and the closest room number. Please tell us exactly what we can do to improve our appearance. Please dial 911 for all emergencies, Suicide & Crisis Line 988"
Once the end user responds another message will be sent out "Thank you for contacting VA Northeast Ohio Healthcare Systems Quality Management Department. Be sure to include the exact location and closet room number
Please note we collaborate with all of our users on their content to ensure it meets standards.

8. Has a Privacy Officer (PO) seen and approved the content? If not, do you know who your PO is? No, my privacy officer is Joseph Picklo
(ex., PO has seen the content but it is not approved)

9. Would you prefer to provide contact information for the recipients or would you rather VA Notify look this up for you by Veteran ID? If by ID, please let us know what identifier is used in your system. No contact information required. The notification will be driven by the end user
(ex., VAPROFILEID, PID, BIRLS, ICN, etc.)

10. Do you currently capture communication preferences related to this notification? If so, please describe. No
(ex., opt in for claim status updates via email or text)

11. What is the anticipated volume of notifications per day, week, month? 100-200 calls per week

12. When does this notification need to be in production? Next week?

**Comment by mjones-oddball** [comment]
We met in November 2023 to discuss this use case. VA Notify was not able to support the request as it does not fit our service model.
