### ISSUE TITLE
Adding 'certreminders' app to DSVA Slack

### ISSUE THREAD

**Issue by vidjovanovic** [department-of-veterans-affairs/va.gov-team#68862]
# Description

I am looking to add an app to the DSVA Slack workspace called 'certreminders.' I have already created the app and the scope and tested it locally and am looking to push it to DSVA. I have submitted a request via the app portal, and am creating a ticket here for further visibility.

<describe the request>

The app's purpose is to send out an automated reminder to the #vagov-identity-cert-reminders channel whenever one of our certs will expire within 45 days, and to continuously remind us until it is updated. There will be a bot created 'certremindersbot' that will join only the #vagov-identity-cert-reminders channel in order to send out these reminders.

**Comment by LEHigley** [comment]
@CoryTrimmUSDS what do you think here?

**Comment by joeniquette** [comment]
Work completed in 66926
