### ISSUE TITLE
Form Dashboard Update - Add [10-10 Health Apps - 10-10EZR standalone form]

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#68871]
# Google Analytics Implementation or QA Request

## What this form is for

We are building the 10-10EZR form on VA.gov.  It is currently a paper form, and we are providing the capability to complete and submit online.
[Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/10-10EZR%20Form/10-10EZR%20Product%20Brief%20(standalone%20form).md)

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

</div>
</details>

### Required
- **Is this request for **Google Analytics implementation** or **QA**?**

     - [x] Google Analytics implementation
     - [ ] QA

- **Who is this request for?**

    - 10-10 Health Apps
    
    
- **Provide the link(s) for Google Analytics implementation or QA**

     - va.gov/my-health/update-benefits-information-form-10-10ezr/introduction
     - va.gov/my-health/update-benefits-information-form-10-10ezr/veteran-information/personal-information
     - va.gov/my-health/update-benefits-information-form-10-10ezr/veteran-information/mailing-address
     - va.gov/my-health/update-benefits-information-form-10-10ezr/veteran-information/home-address
     - va.gov/my-health/update-benefits-information-form-10-10ezr/veteran-information/contact-information
     - va.gov/my-health/update-benefits-information-form-10-10ezr/household-information/marital-status
     - va.gov/my-health/update-benefits-information-form-10-10ezr/household-information/spouse-personal-information
     - va.gov/my-health/update-benefits-information-form-10-10ezr/household-information/spouse-additional-information
     - va.gov/my-health/update-benefits-information-form-10-10ezr/household-information/spouse-financial-support
     - va.gov/my-health/update-benefits-information-form-10-10ezr/household-information/spouse-contact-information
     - va.gov/my-health/update-benefits-information-form-10-10ezr/household-information/dependents
     - va.gov/my-health/update-benefits-information-form-10-10ezr/household-information/dependent-information
     - va.gov/my-health/update-benefits-information-form-10-10ezr/household-information/veteran-annual-income
     - va.gov/my-health/update-benefits-information-form-10-10ezr/household-information/spouse-annual-income
     - va.gov/my-health/update-benefits-information-form-10-10ezr/household-information/deductible-expenses
     - va.gov/my-health/update-benefits-information-form-10-10ezr/insurance-information/medicaid-eligibility
     - va.gov/my-health/update-benefits-information-form-10-10ezr/insurance-information/medicare-part-a-enrollment
     - va.gov/my-health/update-benefits-information-form-10-10ezr/insurance-information/medicare-part-a-effective-date
     - va.gov/my-health/update-benefits-information-form-10-10ezr/insurance-information/policies
     - va.gov/my-health/update-benefits-information-form-10-10ezr/review-and-submit
     - va.gov/my-health/update-benefits-information-form-10-10ezr/confirmation

    
- **When is the launch date?**
    - Week of 11/27/2023

- **What interactions need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked_
    
     - va.gov/my-health/update-benefits-information-form-10-10ezr/introduction
     - va.gov/my-health/update-benefits-information-form-10-10ezr/veteran-information/personal-information
     - va.gov/my-health/update-benefits-information-form-10-10ezr/veteran-information/mailing-address
     - va.gov/my-health/update-benefits-information-form-10-10ezr/veteran-information/home-address
          - Home Address is conditional based on when the Veteran indicates their address is NOT the same as mailing on the Mailing address page
     - va.gov/my-health/update-benefits-information-form-10-10ezr/veteran-information/contact-information
     - va.gov/my-health/update-benefits-information-form-10-10ezr/household-information/marital-status
     - va.gov/my-health/update-benefits-information-form-10-10ezr/household-information/spouse-personal-information
            - Spouse info is conditional based on when the Veteran indicates Married or Separated on the Marital Status page
     - va.gov/my-health/update-benefits-information-form-10-10ezr/household-information/spouse-additional-information
          - Spouse additional info is conditional based on when the Veteran indicates Married or Separated on the Marital Status page
     - va.gov/my-health/update-benefits-information-form-10-10ezr/household-information/spouse-financial-support
          - Spouse financial support is conditional based on when the Veteran indicates Married or Separated on the Marital Status page, and when the Veteran indicates the spouse does NOT live with them
     - va.gov/my-health/update-benefits-information-form-10-10ezr/household-information/spouse-contact-information
          - Spouse contact info is conditional based on when the Veteran indicates Married or Separated on the Marital Status page
     - va.gov/my-health/update-benefits-information-form-10-10ezr/household-information/dependents
     - va.gov/my-health/update-benefits-information-form-10-10ezr/household-information/dependent-information
          - Dependent info is conditional based on when the Veteran indicates they have a dependent on the Dependents page
     - va.gov/my-health/update-benefits-information-form-10-10ezr/household-information/veteran-annual-income
     - va.gov/my-health/update-benefits-information-form-10-10ezr/household-information/spouse-annual-income
          - Spouse income is conditional based on when the Veteran indicates Married or Separated on the Marital Status page
     - va.gov/my-health/update-benefits-information-form-10-10ezr/household-information/deductible-expenses
     - va.gov/my-health/update-benefits-information-form-10-10ezr/insurance-information/medicaid-eligibility
     - va.gov/my-health/update-benefits-information-form-10-10ezr/insurance-information/medicare-part-a-enrollment
     - va.gov/my-health/update-benefits-information-form-10-10ezr/insurance-information/medicare-part-a-effective-date
          - Medicare Part A Effective Date is conditional based on when the Veteran indicates they have Medicare on the Medicare Part A Enrollment page
     - va.gov/my-health/update-benefits-information-form-10-10ezr/insurance-information/policies
     - va.gov/my-health/update-benefits-information-form-10-10ezr/review-and-submit
     - va.gov/my-health/update-benefits-information-form-10-10ezr/confirmation

### Optional
- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

[vets.gov.user+12@gmail.com](mailto:vets.gov.user+12@gmail.com)
[vets.gov.user+15@gmail.com](mailto:vets.gov.user+15@gmail.com)
[vets.gov.user+38@gmail.com](mailto:vets.gov.user+38@gmail.com)
[vets.gov.user+228@gmail.com](mailto:vets.gov.user+228@gmail.com)

- **Any additional comments**

    - This is a new form built on VA.gov, we are looking to get the DOMO form data set up

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by hdjustice** [comment]
cc @luis-simauchi @alexseelig @emily-brown34

**Comment by hdjustice** [comment]
Yes, that is right.

**Comment by michelle-dooley** [comment]
@hdjustice we added 10-10EZR to the dashboard. There is not much data since you have not launched yet. I will make a note to QA again after your 11/27 launch.  Let me know if you have any questions. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1haQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ce0b187cd0c5518f6c9f0286fc87ac05ea5b7c90/image.png)

**Comment by hdjustice** [comment]
This is great, thank you @michelle-dooley !
