### ISSUE TITLE
AWS access for Teja Naraparaju

### ISSUE THREAD

**Issue by tejans24** [department-of-veterans-affairs/va.gov-team#68873]
### COR Name

Jennifer O'Day

### Vendor Onboarding Representative Name

Agile Six - Anthony M. Arashiro

### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Teja Naraparaju

### Your Email

teja@coa.solutions

### Team, Role, and Company of the target individual

Cross Benefits Crew - VRO, Engineer, Coa Solutions

### Product Manager (PM) name and email

Diana Griffin, dianagriffin@navapbc.com

### Product Owner (PO) name and email

Zachary Goldfine, zachary.goldfine@va.gov

### Desired AWS Access

AWS services related to vets-api

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

<img width="1383" alt="Screenshot 2023-11-01 at 12 54 21 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/1976755/91cc7fa7-9da0-46a1-a657-0ce24ba88d25">

### Additional Notes

VRO is working on Data Visibility initiative: https://github.com/department-of-veterans-affairs/abd-vro/wiki/VA.gov-Data-Visibility-Initiative to get 526EZ data into VRO platform

Tech Spec: https://github.com/department-of-veterans-affairs/abd-vro/wiki/Data-Visibility-MVP-Tech-spec

We would like send data from vets-api application layer to an s3 bucket on LHDI platform (which VRO exists in) by running a job in `vets-api` . We are working with LHDI to work on creating cross account resource access using IAM. We would love to get access to AWS and also work with the VFS platform team help support this effort. We need AWS account ids for dev, staging and eventually prod to provide to LHDI to start the process of enabling this (also requested by LHDI). We haven't yet started the development effort and are planning ahead to resolve these account access permission issues and see if there are any bottlenecks.

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by hgbarreto** [comment]
User found in [VFS Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)

**Comment by hgbarreto** [comment]
@tejans24  - With regards to your desired access, are you looking for the basic developer access?
Is there a teammate or peer that already has access that we can copy from?

**Comment by tejans24** [comment]
Hi @hgbarreto, what are the other options other than basic developer access? My intent is to be able to do what I need to get done on VFS for the project I mentioned in the description.

**Comment by hgbarreto** [comment]
User was given credentials.
