### ISSUE TITLE
SOCKS access for Daniel Lim

### ISSUE THREAD

**Issue by danlim715** [department-of-veterans-affairs/va.gov-team#68875]
### Your Name

Daniel Lim

### Your Email

daniel.lim@adhocteam.us

### Your Role and Team

Full Stack Engineer

### Product Manager (PM) name and email

Buddhima Kurukulasuriya - buddhima.kurukulasuriya@coforma.io

### Product Owner (PO) name and email

Bertsch, Jennifer E. <Jennifer.Bertsch@va.gov>

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDZJ9QmxUCKDGRkbhM3+oULoJkYvYZk3WTU91IMWhY8R6ZNMAsQ5Gu5a/3txfV3Y+1n0Pt6ZGFARJpq0ItDTj/CA5AGqMt4FUQLO7+a2cBLdsgV0RAPkAf5e6HgyYzgmuNNiNFeD1dCYyW2Wz2+w1pgWia4KAeUpwHmA03A1no0BAhlV77ezB/jhH1JTElcZ+k74Go+n7/m9i0hfq1so7z0BjuBHRAaXoRDKZkKe66ignyO1JrDDcJJ09tCW4/n52vvFXu9pJTtnB5cJE2jZUm/miFT2lgx24bN0QCOjjgMU8IJ3Z1cLJgXaXXarf+ZwjRh1LJPzNJn+RqQwb13oN9jD6FMmU7OV8K/w4DFdgw1yj9iOYD8Bn54qOubsKKIdoWFVAkptr/QweTASEnumftSi+WaldnYmjVxubRizIZeyDkSjMSN5jcQi+9ZO8VZKUSLeoBjmnkbKsGDOMt8b9FG17Zh4UOgGw+LM5aqYwsaBIchDtHT9LJQSr+jazdOSBM= daniel.lim@daniellim-NWV75233YC

### E-QIP Transmittal Confirmation

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/54864006/24dfed14-9ed1-4c0e-a813-4ec364110c8b)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by hgbarreto** [comment]
@danlim715 Access granted ✅

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Reach out in #vfs-platform-support if you have any trouble.
