### ISSUE TITLE
Proofing Agent - Progress Bar

### ISSUE THREAD

**Issue by lmorris3** [department-of-veterans-affairs/va.gov-team#68888]
## User Story
As a Proofing Agent, I would like to see my progress as I go through the application so I know how much I have completed and what my next step will be.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGFUQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--628fd561d651e45b41ee314a22b6bfd725c37dd0/Wireframe%20-%203.1.png)

## Acceptance Criteria
GIVEN I have logged in to the Proofing Agent Application
WHEN I am viewing a screen
THEN I will see a progress bar indicating which step I am on, the steps I have completed and the steps that are next

Notes:
- the progress bar is not clickable (right?); I cannot use it to move around in the application

**Comment by mateoclarke** [comment]
This is implemented but with the default USWDS styling. The associated PR with work to resolve the styling to match the mockup in Figma which used the Login.gov design library.
