### ISSUE TITLE
Proofing Agent - Fill in Information Page

### ISSUE THREAD

**Issue by lmorris3** [department-of-veterans-affairs/va.gov-team#68882]
## User Story
As a Proofing Agent, I need to complete the required Veteran Information so that I can complete identity proofing for the Veteran.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1NTQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--281ceb99faeaeb7efbacf0886f7da61562c89731/Wireframe%20-%204.png)

## Acceptance Criteria
GIVEN I have completed the Validate ID step
WHEN I continue from that screen
THEN I see a page with the following fields:

- Social Security Number
- First Name, Middle Name, Last Name
- ID Type (can select either Driver's License or VHIC)
- ID Number
- Date of Birth
- Street Address
- City
- State
- Zip
- Urbanization (Puerto Rico only)

AND all fields except Middle Name, Second Address are required
WHEN I complete the fields
THEN I can click Continue to go to the next screen

Error handling:
- Continue is not active until all required fields complete
- Progress bar is separate story

Notes/Questions:

Out of Scope:
- we can come back around to error handling to smooth this out, would like to show where the PA has not completed the required field when they click "Continue" and some fields missing
- Validating specific fields for format (i.e. Street Address is not in address form) - will come back around to full form validation in a later iteration

**Comment by SophiaPhilipMO** [comment]
@moanu404 remove urbanization data field, ticket [#70677 ](https://app.zenhub.com/workspaces/logingov-adoption-team-632280b31e745000136a61fc/issues/gh/department-of-veterans-affairs/va.gov-team/70677)for tech debt of data architecture needed for Puerto Rico addresses
