### ISSUE TITLE
Please Remove Rebecca Bartolo from DSVA Slack

### ISSUE THREAD

**Issue by bradjohnson92008** [department-of-veterans-affairs/va.gov-team#68892]
# Description
Please remove Rebecca Bartolo from DSVA slack.  Rebecca will be leaving the Diffusion Marketplace Team on 11/2/2023.
Rebecca is a Design Specialist who works for Skylight Digital a sub contractor on the Diffusion Marketplace team.

**Comment by LEHigley** [comment]
i'm not seeing her in slack--what's the email address?

**Comment by bradjohnson92008** [comment]
becca@skylight.digital  - Thank you.  Maybe she is not in there... I assumed she was.  If not sorry for the inconvenience.
