### ISSUE TITLE
Research: Conduct user veteran research sessions per research plan

### ISSUE THREAD

**Issue by aplatt-coforma** [department-of-veterans-affairs/va.gov-team#68894]
### User Story
As a PB researcher, I want to conduct the research with veterans as outlined by the research plan

### Notes:
Final research plan was created and approved with ticket: #68126 
Target sessions are to start 11/14 until 11/21

### AC:
- [ ] Execute the research plan and conduct the session with identified veterans

**Comment by djones2113** [comment]
Research sessions have been completed as of 11/20
