### ISSUE TITLE
AWS access to Parameter Store expired or has become disabled

### ISSUE THREAD

**Issue by eubiera** [department-of-veterans-affairs/va.gov-team#68900]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Evan Ubiera

### Your Email

evan.ubiera@va.com

### Team, Role, and Company of the target individual

Developer

### Product Manager (PM) name and email

zinalpatel@va.gov

### Product Owner (PO) name and email

Luciana Morais, luciana.morais@va.gov

### Desired AWS Access

I need access to the AWS parameter store to support our chatbot application.

### Access Expiration

04-12-25

### E-QIP Transmittal Confirmation

<img width="701" alt="EQIP-confirmation" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/117054459/2d841171-379d-4ba2-9e1b-cdf1e7cc1ac3">

### Additional Notes
I'm seeing this error message pop up when I attempt to create an entry in the parameter store.

<img width="1364" alt="Screenshot 2023-11-01 at 2 37 50 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/117054459/b71ef6f2-719a-410b-a925-52edc6a1ff84">

_No response_

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [X] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by hgbarreto** [comment]
Reached out to user to discuss possible troubleshooting ideas.

**Comment by hgbarreto** [comment]
User was able to reach param store. Closing
