### ISSUE TITLE
Data: Create subset file for Emily Wilson to manually review

### ISSUE THREAD

**Issue by aplatt-coforma** [department-of-veterans-affairs/va.gov-team#68903]
### User Story
As a PB team, we want to create a small subset of our target cohort for manual review by Emily Wilson.

### Notes: 
With ticket #67244  we would have pulled a fresh set of cohorts and received additional data from PA&I. In this ticket, we want to prepare a small subset of target veterans and send it to Emily Wilson for review.

### AC

- [x] Outline selection criteria for the sample that we're requesting a review of
- [x] Exploratory analysis of cohort data to understand what fields might be useful for generating sample
- [x] Repeat analysis after receiving pa&i service/claim history data
- [x] Create a file of 40-50 records for review
- [x] Create individual files for reviewers, send to Emily

For post review work: #70473

**Comment by christiejibaraki** [comment]
started [doc](https://docs.google.com/document/d/16-_Q8XryEQbTVawabzrcD7oWBfSjTY_qc_lm3Bx6R08/edit?usp=sharing) to think about how to sample the data for review

**Comment by christiejibaraki** [comment]
started a repo for the exploratory analysis of the cohort data: https://github.com/department-of-veterans-affairs/proactive-benefits-cohort-data-processing

**Comment by christiejibaraki** [comment]
[notebook](https://github.com/department-of-veterans-affairs/proactive-benefits-cohort-data-processing/blob/main/notebooks/1-eda/A-cji-vha-active_cancer_diagnosis.ipynb) for analysis of vha (only) data

**Comment by christiejibaraki** [comment]
Sent Emily W an email to learn more about the manual review process and align on our goals for the review

**Comment by christiejibaraki** [comment]
Not sure who added this task related to updating #67246 ( @buddhima-coforma ?), but I don't think I understand the goal of #67246 or how scheduling it relates to what I'm doing. It seems redundant with the review

**Comment by christiejibaraki** [comment]
This is the guide that reviewers will use
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3Y0QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6571318ef76bb44eca05c085c87a97c6df011c8a/Screenshot%202023-11-21%20at%205.22.28%20PM.png)

**Comment by christiejibaraki** [comment]
These are the fields i propose to send to Emily
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3o0QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2929e57e5e5b7b55fa3f3d9ff6c4aca9e2abd854/Screenshot%202023-11-21%20at%205.22.50%20PM.png)
