### ISSUE TITLE
[BE/FE] 10-10EZR - V2 form: Create BE and FE schema for EC/NoK

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#68917]
As a Veteran, I would like to update my Next of Kin and Emergency Contact so that if something happens to me the VA knows who to contact and who to provide support to. 

- [x] Determine what data fields are currently in the API
- [x] Confirm data fields we'll be building with UX/FE
- [x] Design and build updated schema for FE and backend
- [x] Build schema for the following fields:
- [x] -- Emergency Contact Name
- [x] -- EC #
- [x] -- Next of Kin name
- [x] --NoK Address
- [x] --NoK relationship 
- [x] --Nok Phone #
- [x] Use the [10-10 EZR paper](https://www.va.gov/vaforms/medical/pdf/va%20form%2010-10ezr.pdf) form as a reference
- [ ] We'll have a story for building for EZ as well
- [x] **Success: we have EC/NoK schema to plug into FE and API **

**Comment by lihanli** [comment]
lihan li
  8:20 AM
does the enrollment system api support updating the veteran's emergency contact and next of kin information?


Joshua Faulkner
  8:21 AM
yes


lihan li
  8:22 AM
what should we put in the request to update those fields?


Joshua Faulkner
  8:22 AM
from a 1010 post to the voa service?


lihan li
  8:22 AM
yes

Joshua Faulkner
  8:38 AM
```
<ns0:associations>
         <ns0:association>
            <ns0:address>
               <ns0:city/>
               <ns0:country/>
               <ns0:line1/>
               <ns0:state/>
               <ns0:zipCode/>
            </ns0:address>
            <ns0:contactType/>
            <ns0:familyName/>
            <ns0:givenName/>
            <ns0:middleName/>
            <ns0:relationship/>
         </ns0:association>
</ns0:associations>
```
8:39
contactTypes:
8:39
1 Primary Next of Kin
2 Other Next of Kin
3 Emergency Contact
4 Other emergency contact


lihan li
  8:39 AM
ok thanks
8:40
which of those fields are required?


Joshua Faulkner
  8:41 AM
all of them except for middle name
:+1:
1

8:42
relationships:
8:42
BROTHER
SISTER
SON
STEPCHILD
UNRELATED FRIEND
WARD
WIFE
CHILD-IN-LAW
DAUGHTER
EXTENDED FAMILY MEMBER
FATHER
GRANDCHILD
HUSBAND
MOTHER
NIECE/NEPHEW

**Comment by jadon1979** [comment]
Spoke to Faulkner and there is in fact a phone field
`<ns0:primaryPhone/>`

**Comment by jadon1979** [comment]
https://github.com/department-of-veterans-affairs/vets-json-schema/pull/811/
