### ISSUE TITLE
Design: Ideation for landing page UX

### ISSUE THREAD

**Issue by aplatt-coforma** [department-of-veterans-affairs/va.gov-team#68910]
**Description**
We're exploring the possibility of including a landing page on VA.gov as part of the proactive outreach user journey. We'll use insights from research and other technical/timing considerations to make a final decision, but the purpose of this ticket is to continue ideation on what information a landing page could include that would support a smooth user experience and clarify expectations for Veterans.

**Work to be done:** 
- Create a Sketch file in VA Workspace
- Draft low-fidelity content outlines exploring different approaches for varying levels of detail on the landing page (2-3 versions)
- Optional: create CodePen prototypes for each version

**Resources:** 
- [PB Outreach Journey Map MURAL](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1696612899202/80df54e376713147c4b515584fb06b22eff278b6?sender=u7ebefd98ade29ab3794a2544)
- [Pact Act Wizard research report](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1696612899202/80df54e376713147c4b515584fb06b22eff278b6?sender=u7ebefd98ade29ab3794a2544), [prototype](https://www.surveymonkey.com/r/KKVHSFV), and [slide deck](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pact-act-wizard/research/Research%20Readout%20for%20PACT%20Act%20Wizard%20usability%20testing--VA%20UX%20Sync.pdf)
- [VA Content Style Guide](https://design.va.gov/content-style-guide/)
- [PACT Act information on VA.gov](https://www.va.gov/resources/the-pact-act-and-your-va-benefits/)
- Other PACT Act Communications?
- [Disability benefits information and form on VA.gov](https://www.va.gov/disability/)

**Acceptance Criteria:** 
- [x] unauthorized landing page drafted
- [ ] landing page draft reviewed by internal team members (Daniela, Buddhima = required. Others optional.)

**Comment by aplatt-coforma** [comment]
@gmaciolek - here's a ticket for you to use as the next step for your design work. Please fill it in before refinement tomorrow. Feel free to retitle as well. 
cc @buddhima-coforma

**Comment by gmaciolek** [comment]
I've added a "[Landing page discovery scratchpad](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1696612899202/80df54e376713147c4b515584fb06b22eff278b6?wid=0-1699645764450)" area to my MURAL with notes and considerations for a landing page. I also started drafting content in a Google doc: https://docs.google.com/document/d/1dwXB93K4s6oRNtr3JKzO2djKRcEuN7UnAmD4lDsQocM/edit?usp=sharing

**Comment by gmaciolek** [comment]
Updating acceptance criteria for this one because I think it's too early to spend time on aligning/deciding on whether or not to build a landing page. Plan to talk through the flow with/without landing page after research insights are synthesized and shared. 

That said, the "[Landing page discovery scratchpad](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1696612899202/80df54e376713147c4b515584fb06b22eff278b6?wid=0-1699645764450)" has been updated with a draft of a landing page and where it would fit within the overall user flow for filing a claim online.
