### ISSUE TITLE
508-defect-4 [COLOR, COGNITION]: CONSIDER changing background of map attribution

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#6892]
# [508-defect-4](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-4)

```diff
! Leaflet-Mapbox issue, possibly
```

**Feedback framework**
- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

**This is a relatively minor thing to consider.** Currently, Mapbox's attribution is placed in a transparent background layered over the map. Depending on where the user focuses the map, it may be hard to distinguish the text of the attribution. Relatively 'textured' areas of the map increase the contrast issues. 

**Consider** making the background white or moving the attribution to just below the map instead of an overlay, since there are places the attribution overlays that do not meet contrast requirement of 4.5:1 for WCAG 2.0 Level AA for normal text. In mobile view, the text is especially small, and the contrast issue is really tough. See screenshots for examples of challenges our users may encounter, and recognize many have vision considerations such as low-vision and colorblindness.

## Point of Contact

**VFS Point of Contact:** Jennifer

## Acceptance Criteria

As a low vision user, I want to read the content of the website without any color contrast issues that may confuse.

## Environment

* Operating System: all
* Browser: all
* Server destination: production

## Steps to Recreate

1. Enter `https://www.va.gov/find-locations` in browser
2. Navigate to a destination with lots of water, greenery, and streets (such as Port St Lucie, FL)
3. Observe the text of the attribution and map, links on blue or green
4. Perform the same check using a mobile device

## Possible Fixes (optional)

For the `<div class="leaflet-control-attribution leaflet-control…"`, adjust the CSS to make the background 100% white, or move the attribution to just below the map. As a side consideration, the attribution text on mobile may be smaller than the design system minimum requirements.

```diff
<!-- current styling -->
.leaflet-container .leaflet-control-attribution {
    background: #fff;
!    background: hsla(0,0%,100%,.7);
    margin: 0;
}
<!-- possible fix -->
.leaflet-container .leaflet-control-attribution {
    background: #fff;
+    background: hsla(0,0%,100%,1);
    margin: 0;
}
```

### hsla(0,0,100%,.7)
![hsla- 7](https://user-images.githubusercontent.com/57469/76768580-97904000-6771-11ea-91ce-96e2475fdc35.png)

### hsla(0,0,100%,1)
![hsla-1](https://user-images.githubusercontent.com/57469/76768604-9fe87b00-6771-11ea-8930-e5a46be824ba.png)

## WCAG or Vendor Guidance (optional)

* [WCAG 2.0 and Link Colors](https://webaim.org/blog/wcag-2-0-and-link-colors/)

## Screenshots or Trace Logs

![Screen Shot 2020-03-16 at 10 25 11 AM](https://user-images.githubusercontent.com/57469/76768570-92cb8c00-6771-11ea-9ed8-2c8c50de8f9b.png)

### mobile examples
![IMG_6596](https://user-images.githubusercontent.com/57469/76769249-914e9380-6772-11ea-9d9b-d2064b4e0aeb.PNG)
![IMG_6595](https://user-images.githubusercontent.com/57469/76769251-914e9380-6772-11ea-9c27-9cab514bce7d.PNG)
![IMG_6594](https://user-images.githubusercontent.com/57469/76769252-914e9380-6772-11ea-9fdc-530cadab5a98.PNG)
![IMG_6593](https://user-images.githubusercontent.com/57469/76769254-91e72a00-6772-11ea-89c3-abec30f8f834.PNG)
![IMG_6592](https://user-images.githubusercontent.com/57469/76769257-91e72a00-6772-11ea-87b1-d41468729a37.PNG)

**Comment by mmiddaugh** [comment]
The attribution has significantly improved with our version upgrade. This issue is ready for validation by @joshkimux @tlei123 whenever you are able

**Comment by joshkimux** [comment]
@mmiddaugh Was the attribution removed? I followed the steps to recreate it, but nothing appears for me. Was it replaced by the information icon?

Also, while testing on mobile (in devtools), the search button can block out a good chunk of the page. Would it be possible to place it above or below the map as opposed to directly on top of it? (see video)

https://user-images.githubusercontent.com/14154792/103007174-f2c14100-4500-11eb-954a-ed446490cf68.mov

**Comment by mmiddaugh** [comment]
As Josh noted, Mapbox attribution is a different experience following the upgrade. I will move his feedback about the button in mobile into a new issue and close this one.
