### ISSUE TITLE
Research feasibility of removing opt-in flag

### ISSUE THREAD

**Issue by jimcconnelly** [department-of-veterans-affairs/va.gov-team#68952]
**Definition**
Opt-in to service: A service which currently allows a user to opt-in to use a new MHV related service. The components were built in a way which allows them to be repeated and customized to allow any app to have an individually tracked opt-in or out service.

**Backstory**
MHV team asked us to create this solution, then publicize it to other teams, to see if any want to leverage.

**To-Do**
Find out if MHV or any other team is actually using it.  If so, yay! If not, remove the code.

**Comment by parkerbees** [comment]
Moved to Jira. Closing.
