### ISSUE TITLE
[BE] Discovery Work for MAP API and Appointments Service

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#68980]
We got the token endpoint working manually (through python code) and now need to confirm that the code they (Appointments team) provide in vets-api can be used.

Tasks:
- All: Review the code in vets-api under `/lib/map/security_token`
- @lee-delarm6 setup a call with Joe Niquette and Trevor Bosaw and walk through the check_in objectives and their code
- All: Try using the Service class under `/lib/map/security_token` using rails console with SSH tunnel to hit their SQA endpoints and confirm we can use the class and token
- All: Suggest changes if necessary to their code

**Comment by lee-delarm6** [comment]
Call setup for Friday Nov 3rd, code has been reviewed, service class was loosely tested locally via @randomsync , @kanchanasuriya , @lee-delarm6 

Last item remains to suggest changes after meeting (will likely occur same time)
