### ISSUE TITLE
Vets-api terminal access for Andrew Rodiek

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#68997]
### Your Name

Andrew Rodiek

### Your GitHub handle (terminal access is managed through GitHub)

@Dr-Pongo

### Team, Role, and Company of the target individual

Benefits debt resolution, front end engineer, Govcio

### Product Manager (PM) name and email

Tom Davis, thomas.davis@govcio.com

### Product Owner (PO) name and email

Denise Coveyduc, denise.coveyduc@va.gov

### COR Name (leave "None" if you listed an AWS user name above)

Jennifer O'Day

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

None

### Please confirm if you are on the VFS Team Roster or Platform Team Roster

- [X] [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Please confirm E-QIP Transmittal/Adjudication. This could be a screenshot of your Transmittal/Adjudication email, a link to another request where you've submitted this proof (i.e. AWS/SOCKS), etc.

- [X] I have attached proof that I have either transmitted my E-QIP survey or previously received a favorable decision (by including in "Additional Notes" section below)

### ArgoCD terminal access requested for the following environments

- [ ] dev
- [X] staging
- [ ] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### Additional Notes

[SOCKs access approval](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47330)

Requesting access to assist our BE team while we search and get a new team member up to speed. Mostly looking for cross training and using terminal to query forms and to help alleviate some of the busywork we send back. Requesting staging as well for testing purposes

### Additional resources for Support Engineer

- [ ] For users on a VFS team but not in the VFS Team Roster, they must start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] Instructions for handling requests [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access) - Support Only

**Comment by bdech** [comment]
Found in VFS Team Roster

**Comment by bdech** [comment]
@Dr-Pongo I looked through your old access requests but was unable to locate an E-QIP transmittal notice. I know you've been working on The Platform for some time but we do require a screenshot of E-QIP. Can you please provide a screenshot of your E-QIP, or some favorable adjudication? You can normally locate this transmittal in your email by searching 'E-QIP', or your COR should be able to provide a screenshot. 

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/135037265/d73db74d-0a02-40ec-b781-46d2671f9b2f) is an example of a transmittal notice

**Comment by bdech** [comment]
@Dr-Pongo Can you please attach your E-QIP transmittal notice, or some form of favorable adjudication?

**Comment by bdech** [comment]
Closing out due to no response.

**Comment by Dr-Pongo** [comment]
Hey @bdech is it alright if I open a new request once I find the correct documents?

**Comment by bdech** [comment]
Yea absolutely. When you find the correct documents, reopen this ticket, and attach it here.

**Comment by Dr-Pongo** [comment]
Hey @bdech I was able to get the following screenshot which shows Background Investigation/Adjudication History from our VA Onboarding Team. Will this work?
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/25368370/d3fb3689-ef4b-4772-b3ed-2390721b072f)

**Comment by bdech** [comment]
@Dr-Pongo @gh_username You’ve been granted access to the `staging` environment.

Here's some additional documentation for [Vets API on EKS](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-TerminalAccess) that may help.

**Comment by Dr-Pongo** [comment]
Hey yeah! Trying to get some cross team training to help alleviate some busy work from our back end engineer(s). Mostly running queries on in-progress Financial Status Report forms for troubleshooting and analytic purposes.

**Comment by bdech** [comment]
Thanks @Dr-Pongo. Your access to production is pending OCTODE approval.

**Comment by HeatherRienks** [comment]
@bdech - is there anything you need for approval? Our PO (@denisecoveyduc) is currently out of the office, do you need approval from an OCTO-DE Product Owner?

If so, @mattpointzxer0 may be able to assist

**Comment by mattpointzxer0** [comment]
@bdech if all platform security requirements including an acceptable justification have been provided, then I provide approval on OCTO's behalf.

**Comment by bdech** [comment]
@Dr-Pongo You've been granted access to `Production`, access limited to 6 months. Your production access will expire on 05/22/24. Please set a reminder for one week prior to expiration to request and extension.  

Take care,

**Comment by bdech** [comment]
Platform Support slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1700670333967259)

**Comment by bmatos312** [comment]
@Dr-Pongo Hello Andrew, I'm reaching out to see if you need an extension as your time is almost up for access to the vets api terminal?

**Comment by HeatherRienks** [comment]
@bmatos312 - yes, please extend @Dr-Pongo :)

**Comment by bdech** [comment]
@LindseySaari @ericboehs can one of you please give us a :thumbsup: to extend their Vets-API Terminal access?

**Comment by bdech** [comment]
support slack reminder [here](https://dsva.slack.com/archives/C06CY71PCAX/p1717087789306449)

**Comment by Dr-Pongo** [comment]
@bdech Heyo! Just within the 1 week of expiration! I'd like to request an extension please! (going to leave this as a comment and let y'all handle the reopening of issue if necessary!)

**Comment by bmatos312** [comment]
@LindseySaari @ericboehs Hello, can either of you 2 give me a thumbs up for renewal of access here when you get a moment?

**Comment by bdech** [comment]
support slack reminder [here](https://dsva.slack.com/archives/C06CY71PCAX/p1732219552861329)

**Comment by bdech** [comment]
Thank you for setting up a reminder and letting me know.

**Comment by bdech** [comment]
@LindseySaari @ericboehs can one of you please give us a :thumbsup: to extend their access?

**Comment by bdech** [comment]
@Dr-Pongo your Production access has been extended for 6 months, expiring 11/22/25.

Please set a reminder for yourself to return to this Issue, reopen it, and request an extension within 1 week of the expiration date. You'll receive 1 reminder with a 48 hour window to respond. Failure to respond will result in your access being revoked and will require you to fill out a new request.

**Comment by bdech** [comment]
support slack reminder [here](https://dsva.slack.com/archives/C06CY71PCAX/p1747768925876469)
