### ISSUE TITLE
Fix for broken-link-checker throwing errors for links to files that contain spaces in their name

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#690]
CMS editors upload files into the CMS that contain spaces in their file names. This should be totally fine. However, the broken link checker throws an error when we try to link to that file. The reason is this -

File Name: `Example File.pdf`
Link HREF: `Example%20File.pdf`

We need to decode the link HREF before comparing the HREF to the file name in order for these to match.

**Comment by ncksllvn** [comment]
This _should_ be fixed in the `metalsmith-broken-link-checker` plugin, but I don't know how active the owner of that module is. I did open a PR though - https://github.com/davidxmoody/metalsmith-broken-link-checker/pull/19

If we don't hear back soon, we'll consider other options.

**Comment by ncksllvn** [comment]
I also opened a PR into vets-website that commits a local version of the broken link checker. I definitely do not want to go that route, but I used that PR to verify the problem was as this issue describes. For reference - https://github.com/department-of-veterans-affairs/vets-website/pull/10472.

**Comment by gunsch** [comment]
cc @rianfowler @cvalarida

**Comment by ncksllvn** [comment]
@gunsch Does this make more sense as a platform ticket?

**Comment by gunsch** [comment]
@ncksllvn can I leave that to you and @rianfowler to figure out? I'm not sure where it's a better fit.

**Comment by ncksllvn** [comment]
I'm going to revise this to be _replacing_ the Metalsmith broken link checker. Reasons being -

1. This is a core part of our website validation, yet most of the logic itself is abstracted into a plugin and thereby not flexible. We've already had to have special handling to account for lazy-loaded images
2. The module is unmaintained
3. The module has a valid issue with failing to translate encoded URLs to file paths
4. Rewriting it gives us an opportunity to vastly improve output

Working on this now.

**Comment by Karak888** [comment]
@rianfowler are you able to work with @ncksllvn to help validate this?  Thanks!

**Comment by rianfowler** [comment]
This has been validated. We can close this issue.
