### ISSUE TITLE
Research and possibly remediate happy path failures around form.serviceInformation.servicePeriods

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#69011]
Research and possibly remediate happy path failure 
- [x] form.serviceInformation.servicePeriods[].activeDutyBeginDate
  - [Datadog Link](https://vagov.ddog-gov.com/logs?query=%40named_tags.class%3A%22EVSS%3A%3ADisabilityCompensationForm%3A%3ASubmitForm526AllClaim%22%20%40level%3Aerror%20%40payload.submission_id%3A%282451685%20OR%202470506%20OR%202503871%20OR%202512520%20OR%202535470%20OR%202535501%29%20&cols=host%2Cservice%2C%40payload.error_message%2C%40payload.submission_id&context_event=AY2JIxEsAAB1aZOJsTXH6QAn&index=%2A&messageDisplay=inline&refresh_mode=paused&storage=online_archives&stream_sort=time%2Cdesc&viz=&from_ts=1698811200000&to_ts=1707414600000&live=false)
- [x] form.serviceInformation.servicePeriods.refdataservice.errorResponse
  - [Datadog Link](https://vagov.ddog-gov.com/logs?query=%40named_tags.class%3A%22EVSS%3A%3ADisabilityCompensationForm%3A%3ASubmitForm526AllClaim%22%20%40level%3Aerror%20%40payload.submission_id%3A%282438724%20OR%202456930%20OR%202457720%20OR%202457818%20OR%202457926%20OR%202458408%20OR%202458415%20OR%202458446%20OR%202458592%20OR%202468621%20OR%202475270%20OR%202485951%20OR%202492786%20OR%202492804%20OR%202501728%20OR%202508355%20OR%202524834%20OR%202535780%20OR%202550971%20OR%202557973%20OR%202564196%20OR%202565530%20OR%202567520%20OR%202573752%29%20&cols=host%2Cservice%2C%40payload.error_message%2C%40payload.submission_id&context_event=AY2JIxEsAAB1aZOJsTXH6QAn&index=%2A&messageDisplay=inline&refresh_mode=paused&storage=online_archives&stream_sort=time%2Cdesc&viz=&from_ts=1698811200000&to_ts=1707414600000&live=false)

## Acceptance Criteria
- [x] Determine root cause of errors
- One of the following
  - [ ] New ticket created to fix issue
  - [x] PR Opened to Fix issue
  - [ ] Comments on this ticket describing why it is not fixable at this time

**Comment by freeheeling** [comment]
**Message:** `{"key"=>"form526.serviceInformation.servicePeriods[0].activeDutyBeginDate", "severity"=>"ERROR", "text"=>"The active duty start date cannot be prior to the claimants 13th birthday"}`

**Comment by freeheeling** [comment]
`form526.serviceInformation.servicePeriods.refdataservice.errorResponse`

**Message:** [{"key"=>"form526.serviceInformation.servicePeriods.refdataservice.errorResponse", "severity"=>"ERROR", "text"=>"The Reference Data Service was unable to verify the branch of service for the claimant returned an error response"}]}

**Comment by freeheeling** [comment]
Based on the content of a [Update service period validation](https://github.com/department-of-veterans-affairs/vets-api/pull/14047) PR from last October, it seems like, to match the validation found on the EVSS side, the activeDutyBeginDate should not fall **on** or before a veteran's 13th birthday. I've reached out to whom I believe is the author of that PR to inquire about possible documentation. 

I would interpret the UI error message, "Your start date must be after your 13th birthday", to mean **on** the 13th birthday would **not** be valid. Although, the error response from EVSS, "The active duty start date cannot be prior to the claimants 13th birthday", might be interpreted as the start date could be on or after the 13th birthday.

**Comment by freeheeling** [comment]
Confirmation received from Michael Harlow:
> According to [EVSS form526 validation rules](https://confluence.devops.va.gov/pages/viewpage.action?spaceKey=VAExternal&title=Form526+Validation+Rules), a claim is **invalid** if the earliest  `activeDutyBeginDate` is on or before the 13th birthday, so the online form validation should be revised to match that.

I will make the necessary update.

**Comment by freeheeling** [comment]
Regarding `form526.serviceInformation.servicePeriods.refdataservice.errorResponse`, according to Michael Harlow:

> This error happens when EVSS is unable to reach Lighthouse to verify the claimant's branch of service is valid. EVSS caches the BOS list from LH for 15 minutes, so not all claims require LH to be available. There's currently nothing VA.gov can do prior to submission to prevent this error.

My questions were then:
1. Is BOS something updated with regularity?
2. Because vets-api currently does not retry to submit a claim when encountering this error, would instead configuring retries for the same submission ultimately not fail this validation? 
3. Are other Reference Data Service errors the same situation where EVSS is unable to reach LH to verify attributes, for example:
- the classification code for the disability...
- the separation location code...
- the mailing address country...
- the change of address country...

Could these also be resolved by configuring submission retries if a "Reference Data Service was unable to verify" error is received?

**Comment by freeheeling** [comment]
[Draft PR](https://github.com/department-of-veterans-affairs/vets-website/pull/29364) to remediate `activeDutyBeginDate` error submitted for review

**Comment by freeheeling** [comment]
Update to remediate `activeDutyBeginDate` error deployed to prod.
<img width="1045" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWFQQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f8bc418905254bfd065d52c92504aa9ca0d78b74/Screenshot%202024-04-24%20at%203.47.10%E2%80%AFPM.png" alt="Screenshot 2024-04-24 at 3.47.10 PM.png" />
<img width="1045" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVdQQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2c921340924fd72b79c0e5e49731af4526e232e6/Screenshot%202024-04-24%20at%203.46.46%E2%80%AFPM.png" alt="Screenshot 2024-04-24 at 3.46.46 PM.png" />

**Comment by freeheeling** [comment]
[Draft PR](https://github.com/department-of-veterans-affairs/vets-api/pull/16558) to retry `refdataservice.errorResponse`messages in review.

**Comment by freeheeling** [comment]
Reviewed and am satisfied with the updates made when initially drafting the PR to reclassify Reference Data Service errors as retryable. Submitted a support ticket to request `department-of-veterans-affairs/lighthouse-dash` code owner review, which is currently holding up merging.

**Comment by freeheeling** [comment]
Deployed to prod 5/15/24. Will check [DD logs](https://vagov.ddog-gov.com/logs?query=%40named_tags.class%3A%22EVSS%3A%3ADisabilityCompensationForm%3A%3ASubmitForm526AllClaim%22%20%40level%3Aerror%20%40payload.error_message%3A%22%7B%5C%22messages%5C%22%3D%3E%5B%7B%5C%22key%5C%22%3D%3E%5C%22form526.serviceInformation.servicePeriods.refdataservice.errorResponse%5C%22%2C%20%5C%22severity%5C%22%3D%3E%5C%22ERROR%5C%22%2C%20%5C%22text%5C%22%3D%3E%5C%22The%20Reference%20Data%20Service%20was%20unable%20to%20verify%20the%20branch%20of%20service%20for%20the%20claimant%20returned%20an%20error%20response%5C%22%7D%5D%7D%22%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice%2C%40payload.error_message%2C%40payload.submission_id&context_event=AY2JIxEsAAB1aZOJsTXH6QAn&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=online_archives&stream_sort=time%2Cdesc&viz=&from_ts=1715208504397&to_ts=1715813304397&live=true) to confirm success over next week. `status` for any occurrence of `{"key"=>"form526.serviceInformation.servicePeriods.refdataservice.errorResponse", "severity"=>"ERROR", "text"=>"The Reference Data Service was unable to verify the branch of service for the claimant returned an error response"}` should be a `retryable_error`.

**Comment by freeheeling** [comment]
Last recorded in error [in DD from last 15 days](https://vagov.ddog-gov.com/logs?query=%40named_tags.class%3A%22EVSS%3A%3ADisabilityCompensationForm%3A%3ASubmitForm526AllClaim%22%20%40level%3Aerror%20%40payload.error_message%3A%22%7B%5C%22messages%5C%22%3D%3E%5B%7B%5C%22key%5C%22%3D%3E%5C%22form526.serviceInformation.servicePeriods.refdataservice.errorResponse%5C%22%2C%20%5C%22severity%5C%22%3D%3E%5C%22ERROR%5C%22%2C%20%5C%22text%5C%22%3D%3E%5C%22The%20Reference%20Data%20Service%20was%20unable%20to%20verify%20the%20branch%20of%20service%20for%20the%20claimant%20returned%20an%20error%20response%5C%22%7D%5D%7D%22%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice%2C%40payload.error_message%2C%40payload.submission_id&context_event=AY2JIxEsAAB1aZOJsTXH6QAn&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=online_archives&stream_sort=time%2Cdesc&viz=&from_ts=1715014987019&to_ts=1716310987019&live=true) was 5/13, 2 days before error handling updates were made.

I recommend checking logs for at least the next 2 weeks to confirm updates have intended effect.
