### ISSUE TITLE
Research PDF generation 

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#6901]
## User Sotry

Given that a user wants to download a PDF version of their 10-10CG application
And that the business wants to see a PDF of the form attached to the online application submission
I want to begin researching whether that functionality has been implemented on VA.gov
So that we can better estimate the workload involved on adding this function to our Phase 1 rollout.

## Acceptance Criteria
Research documented in Github
Tickets created in Backlog

**Comment by kevinmirc** [comment]
**PDF Generation Docs**: https://github.com/department-of-veterans-affairs/va.gov-team/issues/6901

**Workload:**
- **Boilerplate**
- [ ] Add blank PDF to `lib/pdf_fill/forms/pdfs/*` (maybe version it?)
- [ ] Add the new class to the map in `lib/pdf_fill/filler.rb:8`
- [ ] Create a `PdfFill::Forms::Form1010cg` in `lib/pdf_fill/forms/*`
- **Transformer**
- [ ] Map the claim props to to the PDF fields in `PdfFill::Forms::Form1010cg`
- **Testing**
- [ ] Add a `pdf_fill/forms/form1010cg_spec.rb` suite.
- [ ] Add tests for any custom business logic implemented.

**Considerations**
- How would we pass the form back to the client? Would we send the raw data or a link to where it's hosted. What would be the size of the payload for the former?

**Followup Tickets**
- Send PDF version of the submission to CARMA
Need to discuss the data contract. This will be done in a separate request and via an async job.
