### ISSUE TITLE
Change ITF logic

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#69022]
## Tasks
Pull the `createdAt` value from the `InProgressForm` table and insert it into a new column within `SavedClaim` table that represents the ITF before we delete `InProgressForm`

## Acceptance Criteria
- [ ] Above steps are completed and the form is still working correctly.

**Comment by mjknight50** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/69022?planning-poker) with Zenhub @danlim715

**Comment by aplatt-coforma** [comment]
Duplicate ticket @vbellissimo

**Comment by vbellissimo** [comment]
duplicate to #69157
