### ISSUE TITLE
Analytics KPI dashboard update request for [Sitewide Content, Accessibility, and Information Architecture (CAIA)]

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#69037]
# Request an update to your KPI Dashboard  

## What this form is for

Use this ticket template to request an update to your existing KPI dashboard. To request a new product be added to our dashboards, please use [Request a New Standardized KPI Dashboard template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&template=analytics-request-kpi-dashboard.md&title=Analytics+KPI+dashboard+request+for+%5BTeam%5D).

### Expected delivery timelines

The Analytics team will notify you once this ticket has been pulled into a sprint. 

## Instructions for the VFS team
First, tell us what type of change you need to make:

- [ ] Change basic product info
- [ ] **Forms**: funnel changes
- [x] **Content**: Add or remove pages included
- [ ] Other_____________________________

Next, use the original [KPI request template](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit#gid=981224988) or [(downloaded Excel version)](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/1586823275/KPI%20Dashboard%20Product%20Details%20Template%20-%20MAKE%20A%20COPY.xlsx?inst-v=ced1f4dd-e997-4aa2-9ae8-2cebe369b42f) you filled out to update your information. If you are not able to find that spreadsheet, reach out to the Analytics team on #vfs-platform-support for a new spreadsheet that reflects what we currently have on file.

- [ ] Make a copy of the [Google Sheet](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit#gid=981224988) [(or download Excel version)](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/1586823275/KPI%20Dashboard%20Product%20Details%20Template%20-%20MAKE%20A%20COPY.xlsx?inst-v=ced1f4dd-e997-4aa2-9ae8-2cebe369b42f)
- [ ] Complete worksheet as instructed
- [ ] Link your completed spreadsheet here: ______
- [ ] Check your sharing settings to make sure the Analytics team will be able to access it
- [ ] Add your team label to follow progress

**Additional Info**

- Please use the [KPI Framework](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/Analytics%20Playbook/va-gov-platform-analytics-kpi-framework.pdf) for more information on the metrics used in the KPI dashboards. 
- If you need any analytics support, read through the [How to request Analytics support](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guidelines.1586823275.html#Analyticscustomersupportguidelines-4.RequestaKPIDashboardinDomo).
- If you do not have Domo access, please [request access here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+access-request&template=analytics-request-google-analytics-domo-access.md&title=Request+access+to+Google+Analytics+and%2For+Domo).

**Comment by michelle-dooley** [comment]
@RLHecht - can you please provide the list of urls that need to be added.

**Comment by RLHecht** [comment]
Here you go:

/resources/about-our-va-community-care-network-and-covered-services/
/resources/are-service-dogs-allowed-in-va-facilities/
/resources/ask-va-replaces-iris-and-the-gi-bill-help-portal/
/resources/can-i-be-buried-in-arlington-national-cemetery/
/resources/can-i-get-a-loan-through-my-va-life-insurance-policy/
/resources/can-i-get-a-replacement-gi-bill-benefit-certificate-of-eligibility/
/resources/can-i-get-free-health-care-and-prescriptions-as-a-veteran/
/resources/can-i-plan-ahead-for-my-burial-in-a-va-national-cemetery/
/resources/change-your-address-on-file-with-va/
/resources/choosing-a-decision-review-option/
/resources/choosing-between-urgent-and-emergency-care/
/resources/claim-status-tool-faqs/
/resources/combat-related-special-compensation-crsc/
/resources/commissary-and-exchange-privileges-for-veterans/
/resources/compare-va-education-benefits/
/resources/connected-apps-faqs/
/resources/copay-exemptions-for-american-indian-and-alaska-native-veterans/
/resources/covid-19-testing-at-va/
/resources/creating-an-account-for-vagov/TOTAL
/resources/deciding-how-much-life-insurance-to-get/
/resources/decision-reviews-faqs/
/resources/direct-deposit-for-your-va-benefit-payments/
/resources/does-va-cover-nursing-home-assisted-living-or-other-long-term-care/
/resources/ds-logon-faqs/
/resources/eligibility-for-community-care-outside-va/
/resources/evidence-to-support-va-pension-dic-or-accrued-benefits-claims/
/resources/find-apps-you-can-use/
/resources/get-a-premium-my-healthevet-account/
/resources/getting-a-gi-bill-extension/
/resources/gi-bill-and-other-va-education-benefit-payments-faqs/
/resources/gi-bill-wave-faqs/
/resources/government-headstones-and-markers-faqs/
/resources/helpful-va-phone-numbers/
/resources/how-are-pension-benefits-and-disability-compensation-different/
/resources/how-can-i-stay-informed-about-covid-19-vaccines-at-va/
/resources/how-can-i-verify-my-identity-on-vagov-if-i-live-outside-the-us/
/resources/how-do-i-change-my-name-in-my-deers-record/
/resources/how-do-i-get-college-credits-for-my-military-service/
/resources/how-to-change-direct-deposit-information-for-va-benefits/
/resources/how-to-change-your-address-in-your-vagov-profile/
/resources/how-to-change-your-legal-name-on-file-with-va/
/resources/how-to-check-in-with-your-smartphone-for-some-va-appointments/
/resources/how-to-check-your-va-claim-appeal-or-decision-review-status-online/
/resources/how-to-download-and-open-a-vagov-pdf-form/
/resources/how-to-file-a-va-travel-reimbursement-claim-online/
/resources/how-to-find-out-if-you-should-get-a-higher-tsgli-payment/
/resources/how-to-get-community-care-referrals-and-schedule-appointments/
/resources/how-to-get-free-language-assistance-from-va/
/resources/how-to-get-help-with-concerns-at-a-va-health-facility/
/resources/how-to-get-your-medical-records-from-your-va-health-facility/
/resources/how-to-report-the-death-of-a-veteran-to-va/
/resources/how-to-set-up-direct-deposit-for-va-travel-pay-reimbursement/
/resources/how-va-education-benefit-payments-affect-your-taxes/
/resources/how-we-determine-your-percentage-of-post-911-gi-bill-benefits/
/resources/how-we-determine-your-post-911-gi-bill-coverage/
/resources/how-your-reason-for-withdrawing-from-a-class-affects-your-va-debt/
/resources/in-state-tuition-rates-under-the-veterans-choice-act/
/resources/life-insurance-if-you-have-preexisting-conditions/
/resources/managing-your-vagov-profile/
/resources/montgomery-gi-bill-refunds/
/resources/my-healthevet-faqs/
/resources/my-healthevet-on-vagov-what-to-know/
/resources/non-compensable-disability/
/resources/onet-interest-profiler-career-assessment/
/resources/presumptive-cancers-related-to-burn-pit-exposure/
/resources/privacy-and-security-on-vagov/
/resources/reimbursed-va-travel-expenses-and-mileage-rate/
/resources/reimbursement-of-non-va-prescriptions-or-medical-expenses/
/resources/request-a-discharge-upgrade-or-correction/
/resources/requesting-a-replacement-government-headstone-or-marker/
/resources/separation-health-assessment-for-service-members/
/resources/should-i-create-a-logingov-or-idme-account-to-sign-in-to-vagov/
/resources/signing-in-to-vagov/
/resources/submitting-a-financial-status-report-va-form-5655/
/resources/the-pact-act-and-your-va-benefits/
/resources/the-veterans-health-information-exchange-vhie/
/resources/va-covid-19-debt-relief-options-for-veterans-and-dependents/
/resources/va-debt-management/
/resources/vas-duty-to-assist/
/resources/va-tier-1-copay-medication-list/
/resources/verifying-your-identity-on-vagov/
/resources/verify-school-enrollment-for-dea-benefits/
/resources/veteran-identification-card-vic-faqs/
/resources/vetext-for-va-health-care-reminders-and-updates/
/resources/waivers-for-va-benefit-debt/
/resources/what-does-burial-in-a-va-national-cemetery-include/
/resources/what-if-i-cant-sign-in-to-vagov-because-my-password-doesnt-work/
/resources/what-if-i-dont-want-a-fiduciary-anymore/
/resources/whats-a-veteran-health-id-card-vhic-and-how-do-i-get-one/
/resources/what-your-claim-status-means/
/resources/what-your-decision-review-or-appeal-status-means/
/resources/will-i-have-to-pay-back-the-gi-bill-benefits-i-used-if-i-fail-a-class/
/resources/your-civil-rights-and-how-to-file-a-discrimination-complaint/
/resources/your-intent-to-file-a-va-claim/

**Comment by michelle-dooley** [comment]
@RLHecht - we have added these urls to the Content Dashboard and are in the process of final QA.

**Comment by RLHecht** [comment]
thank you so much!

**Comment by michelle-dooley** [comment]
Good morning @RLHecht - we have add the 'Resources & Support' pages to the [Content Dashboard](https://va-gov.domo.com/page/426422632). You just need to select from the 'product' filter at the top of the page. If you want to to isolate a specific url you can do that through the 'product_url' filter also at top of page. Please let me know if you have any questions. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTBaQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e304b4838981596a521da5ac63a5ab1a5d707941/image.png)

**Comment by RLHecht** [comment]
Thanks so much! This will be really helpful for our team as we are looking more into R&S and any content changes we may need to make. I'll let you know if I run into any issues when I review for November's metrics.

**Comment by RLHecht** [comment]
@michelle-dooley I'm able to see resources and support on the dashboard but not sure I see the information for the good/bad survey results. Is this something we're able to add?

![Screenshot 2023-12-05 at 11 28 47 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/48728214/a227421a-9f81-477d-884c-708f24a19899)

**Comment by michelle-dooley** [comment]
Hi @RLHecht - currently the only survey data on the dashboard is for the intercept survey that is across all pages. Since this question in specific to the /recoures/ sections only it does not make sense to add to this standardized dashboard.  However you can get that information from a [GA report]( https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p184624291/explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.eventAction%22,%22RE%22,%22Radio%20Button%20-%20How%20do%20you%20rate%22,0%5D%5D&explorer-table.secSegmentId=analytics.pagePath&explorer-table.rowStart=0&explorer-table.rowCount=500)

<img width="1581" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTAwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a2434912a41e7d9842fd2ebf5e6658a6f457861d/image.png" alt="image.png" />
