### ISSUE TITLE
Update disability rates main page to remove "2019" from headline and intro

### ISSUE THREAD

**Issue by AnneHurley** [department-of-veterans-affairs/va.gov-team#6904]
Need to update this page 

https://www.benefits.va.gov/compensation/rates-index.asp
^ which also needs to be redirected 

https://prod.cms.va.gov/node/989/edit
@RLHecht  I've updated the prod link above, but we still need to do the redirect. 
@lunascoop  - apologies this isn't a full separate redirect request though I believe you have this page in an earlier request - let me know and thanks.

**Comment by RLHecht** [comment]
This page has been published. Should I move to validate or is the redirect on this ticket too? @lunascoop ?

**Comment by lunascoop** [comment]
@RLHecht there is no redirect for this ticket.

**Comment by RLHecht** [comment]
Moving this page to validate and will close when live on the site.

**Comment by MickinSahni** [comment]
2020-03-18 PW Standup
* Just need to validate before closing

**Comment by RLHecht** [comment]
This is live on the site but in search results it's still showing 2019 info. @MickinSahni do you know who to ask to update this?![Screen Shot 2020-03-18 at 11.38.46 AM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/6ad7001d-be15-4368-86cc-fe6ad64cb4bd)

**Comment by MickinSahni** [comment]
2020-03-19 PW Standup
- Metadata is all updated, but still seeing persisting text in the on-site search results
 We'll doublecheck about the metadata/keep an eye on this but will close out
