### ISSUE TITLE
Reverse engineer CSV file from a modern VA.gov static table

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#6905]
#6907 Reverse engineer CSV file from a modern VA.gov static table 

**Problem:** 
Currently static tabular information is extremely manual and tedious to maintain and keep up-to-date. The information content team receives from SMEs do not map to the Veteran-centered modern organization of tables. 

**See attached example of rates information that stakeholders use to update table data:**
[example-pension-rates-raw-table.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4340359/example-pension-rates-raw-table.docx)

**Question/solution to investigate:** 
**1/** Is it possible to reverse engineer our static table content into a CSV file, so we can provide a CSV export of our static table information (mainly rates info) to SMEs? 

- This would allow us to - going forward -  have them maintain yearly updates and changes in an easy to use spreadsheet, 
- which we can then simply upload to Drupal to push out the updated rates via our modern FE table layout and org. 
- Ideally, we would want to be able to do this automated, rather than the content team manually creating CSV files from static tables, if there's a simple way to script the reverse-engineering.

 
**2/** Is it possible to maintain table information as a CSV upload via Drupal? Desired outcome is to have SMEs update tabular information like rates or contact info in a CSV file, upload it to Drupal (or have the cotent team upload it), and have that data populate our FE tables on content pages. 
- (With YR data, it wasn't possible bc of the quantity of data - 6,000+ rows of data points -- but most of the rates related tables have much less data points. See examples of table data pages below.)

__Examples of our modern VA.gov rates table pages:__
https://www.va.gov/pension/veterans-pension-rates/
https://www.va.gov/pension/survivors-pension-rates/
https://www.va.gov/burials-memorials/veterans-burial-allowance/
https://www.va.gov/disability/compensation-rates/veteran-rates/
https://www.va.gov/disability/compensation-rates/special-monthly-compensation-rates/
https://www.va.gov/disability/compensation-rates/special-benefit-allowance-rates/
https://www.va.gov/disability/compensation-rates/birth-defect-rates/
https://www.va.gov/housing-assistance/home-loans/funding-fee-and-closing-costs/#va-funding-fee-rate-charts

__Example of a legacy table:__
https://www.benefits.va.gov/vocrehab/vsoc.asp 

FYSA @MickinSahni (and @kevwalsh - for the PW Drupal engineer who will join? I'm assuming this is 'product' level Drual work, not 'global' AX.)

## Acceptance Criteria
- [ ] TBD
- [ ] TBD

**Comment by jenniferlee-dsva** [comment]
Hmm - Not sure why I can't add this as "backlog" or "icebox" to our PW team board. I'd like to make sure this is something we look at with the new PW Drupal engineer we're supposed to get.

**Comment by jenniferlee-dsva** [comment]
^ removed artysmith - I think I was trying to @ aruna

**Comment by beeyayjay** [comment]
>2/ Is it possible to maintain table information as a CSV upload via Drupal?

You can do that already: 
![Edit_Benefits_detail_page_VA_pension_rates_for_Veterans___VA_gov_CMS.png](https://images.zenhubusercontent.com/5d7908d1fb288f0001ceb853/c5c190aa-52fe-4104-a374-a56a6b9b4b0b)

>1/ Is it possible to reverse engineer our static table content into a CSV file, so we can provide a CSV export of our static table information (mainly rates info) to SMEs?

That shouldn't be too difficult. Maybe something like this mockup?
![Screen Shot 2020-04-03 at 6.18.33 PM.png](https://images.zenhubusercontent.com/5d7908d1fb288f0001ceb853/54a156b4-d481-4c5d-9eb8-9d798a7b3166)
The Export accordion would contain a download button.

**Comment by jenniferlee-dsva** [comment]
Following the ^. @beeyayjay that would be tremendous.

**Comment by jenniferlee-dsva** [comment]
Summary of our call and the initial solution ideas we can start exploring deeper. 

**RE managing historic VA.gov rate pages – will start when we transition from 2020 to 2021:** 
•	Beth’s idea is to simply clone the current (2020) page in Drupal; we should be able to change the URL of the 2020 historic page, so that we can link to it from the evergreen “current” rates page. 
•	Per Mickin’s point re do we really want to replicate the VBA legacy model of forever maintaining historic years – we can raise this issue again with VBA and propose max 3 years, and retire/redirect historic pages older than that to point to the ‘current’ info URL. 
•	Need to explore/confirm: IA impact; historic rate page URL pattern with @mnorthuis 

**RE ongoing maintenance of rates tables:** 
•	CSV import/upload function already exists in Drupal. It is for each unique table on a page however, and does not map to all the data in all the tables on a page (i.e., treating all the tabular data as one data set). 
•	To treat all the tabular data on a page as one data set that maps to the FE would require custom coding. This custom coding would be extremely bespoke for every type of rates information we have. Not a good solution. 
•	Possible in-between solution: Recreate each table on a page as individual worksheets in a spreadsheet; provide the combined spreadsheet to SMEs to update rates and send back to content team; content person uploads each worksheet in the spreadsheet as a csv file into Drupal for the specific table. 
This is still somewhat manual, but less than today and provides a more sustainable way of letting SMEs make rate updates ‘directly’ in a more usable format than today; it also removes the step of the content person manually entering text in each data field in the CMS table interface. 
•	To explore/confirm: How hard would it be to provide an export functionality in addition to the import feature that already exists? @beeyayjay (E.g., So that Drupal is always the source of truth for the baseline updates – for example, if we or SMEs lose the spreadsheet we send them, there’s an export way to recreate spreadsheet worksheets for each table.)

**Comment by jenniferlee-dsva** [comment]
**Next steps:** 
Jen sync on ‘to confirm/explore’ items above with Mikki and Beth.

**Comment by jenniferlee-dsva** [comment]
**Per content weekly deep dive into rates tables, we'll need a ticket (perhaps for each page or hub?) to:** 

1/Manually create a CSV file for rates. Each table on a page needs to be represented by a worksheet tab in a consolidated CSV file. We will share this file with SMEs for them to update rate information going forward. 
- This work is not needed in the immediate short term, but we will need to provide SMEs with this and provide walkthrough/initial briefing in late Q3 or very EARLY Q4. 
- Because most rates switch over in December 1, we'll want to share this with SMEs as early as possible, especially if they spend time leading up to December 1 to work on rates info - we want to replace their existing method with this new process so they don't have to duplicate work. 


2/Create the export functionality referenced above. This ticket is already created here: [#7942 ](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/7942)

FYSA @johnhashva  and @daniellethierryusdsva
