### ISSUE TITLE
Adding Brian Wilke to DSVA Slack

### ISSUE THREAD

**Issue by HeatherRienks** [department-of-veterans-affairs/va.gov-team#69053]
Please add Brian Wilke new Copilot UX Researcher/Designer on CHAMPVA team to DSVA Slack as a Full Member.
brian.wilke@copilot.llc

He should be added to #vfs-all-teams, #vfs-change-announcements and any other pertinent UXR and VFS general channels for new team members.

**Comment by HeatherRienks** [comment]
@eunicegar and @pshahVA - FYI

**Comment by eunicegar** [comment]
Done
