### ISSUE TITLE
Alert when commits aren't deployed to dev or staging

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#69087]
### Problem
When commits don't get deployed to dev or staging, this is because some CI check has failed on the k8s branch. We need some kind of automated alerts for this scenario. Otherwise we will miss these failures until someone notices them and then we're scrambling to fix it.

### Questions
- Which metric should we alert on?
- Where should the alerts be sent to?

### Acceptance Criteria
- [ ] Alert is created for CI check failure in vets-api k8s

**Comment by ericboehs** [comment]
Done. https://github.com/department-of-veterans-affairs/vets-api/pull/14398
