### ISSUE TITLE
Adding Jeff Wang to DSVA Slack

### ISSUE THREAD

**Issue by HeatherRienks** [department-of-veterans-affairs/va.gov-team#69113]
Please add Jeff Wang new Ad Hoc Full Stack Engineer on CHAMPVA team to DSVA Slack as a Full Member.
jeff.wang@adhocteam.us

He should be added to #vfs-all-teams, #vfs-change-announcements and any other pertinent Engineering and VFS general channels for new team members.

Thanks!

**Comment by HeatherRienks** [comment]
@pshahVA and @eunicegar - FYI

**Comment by eunicegar** [comment]
Invite sent!
