### ISSUE TITLE
Fix 526EZ Keyboard-Only Cypress Test

### ISSUE THREAD

**Issue by zack** [department-of-veterans-affairs/va.gov-team#69129]
The cypress test to test keyboard-only navigability of 526EZ is flaky and has been turned off. We need to figure out why it's flaky, fix the tests, and turn it back on.

**Comment by tblackwe** [comment]
FYI @austinjprice @NB28VT 

Zack had some bandwidth, I asked him to take a look at the 526 flaky test in hopes we can get it resolved without deleting.

**Comment by steele-lm** [comment]
@zack Can this issue be closed on the non-disability board?

**Comment by zack** [comment]
this can be closed everywhere
