### ISSUE TITLE
Content for POA Documentation

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#6912]
Given that a user with POA may fill out the 10-10CG as their Veteran's delegate
I want to generate the content that will be used to request POA documentation and signature
So that those individuals can submit online 10-10CG applications.

**Comment by psanders86** [comment]
# Deck 1 of 3: Existing Drupal page 
### Note that this page is owned by Public Websites
New content is in * italics * 

#### How do I get these benefits?
You’ll need to apply to get these benefits. To apply, fill out an Application for the Program of Comprehensive Assistance for Family Caregivers (VA Form 10-10CG). You’ll need health care coverage information for both the primary family caregiver and the Veteran. In addition, you’ll need the following for the Veteran, the primary family caregiver and any secondary family caregivers:
* Address
* Phone number
* Email address
* Social Security number or tax identification number

You’ll have to complete a new 10-10CG application each time you add a caregiver.

*You can complete this joint application or have a power of attorney or representative complete the form. Your power of attorney or representative will have to submit legal proof with this application showing they are allowed to act on your behalf.*

You’ll get a confirmation message after submitting the form. You can print this for your records.

If you’re not enrolled in the VA’s health care system, or if you are active duty and undergoing a medical discharge, you’ll first need to submit an application for VA health care benefits (VA Form 10-10EZ).

# Deck 2 of 3: Subway map on intro page
New content is in *italics * 

#### 2. Apply

You can complete this joint application or have a power of attorney or representative complete the form. 
You’ll get a confirmation message after submitting the form. You can print this for your records.

*Your power of attorney or representative will have to submit legal proof with this application showing they are allowed to act on your behalf. *

**What is power of attorney?**
[expanded learn more] 
Power of attorney is an authorization for someone to act on the Veteran’s or service member's behalf when completing this form.
[expanded learn more]

**Who can be a representative?**
[expanded learn more] 
A representative can be a Veteran’s or service member’s: 
* Court-appointed legal guardian
* Special guardian
* Holder of durable power of attorney for health care
* Another designated health care agent
[/expanded learn more] 
----------------------------


# Deck 3 of 3: Review and signature page 
New content is in * italics * 

#### Veteran or service member statement of truth ####
I certify that I give consent to the individual(s) named in this application to perform personal care services for me upon being approved as primary and/or secondary family caregivers in the Program of Comprehensive Assistance for Family Caregivers. 

* Are you signing this document as a legal power of attorney or authorized representative? *

* [Radio options] Yes; No *

[Text input] Veteran or Service member’s full name

[Checkbox] I certify the information above is correct and true to the best of my knowledge and belief.[/Checkbox]

[/Signature box]

* [Text input]Power of attorney/representative’s full name * 

* [Checkbox] I certify the information above is correct and true to the best of my knowledge and belief.
[/Checkbox] * 

* [/Signature box] *
