### ISSUE TITLE
Flipper UI access for Swapna Krishnankutty

### ISSUE THREAD

**Issue by swapna-tw** [department-of-veterans-affairs/va.gov-team#69148]
### Your Name

Swapna Krishnankutty

### Your GitHub handle (Flipper UI access is managed through GitHub)

swapna-tw

### Team, Role, and Company of the target individual

VA Chatbot, QA, Thoughtworks Inc.

### Please confirm if you are on Atlas, Platform Team Roster or are a Federal User

- [x] [Atlas](https://dev.va.gov/atlas)
- [X] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [X] Lesser Environments (Dev/Staging/Sandbox)
- [ ] Production (if requesting, justify prod access below)

**Comment by bdech** [comment]
Confirmed user in Atlas

**Comment by bdech** [comment]
@swapna-tw You've been granted access to lesser environments.
