### ISSUE TITLE
[Deactivation] Pull the ITF, "created_at" values for Pension forms in-progress

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#69157]
## Issue Description
**Context from Emily found on [this Slack thread](https://dsva.slack.com/archives/C05MS96P6P2/p1699038895349839?thread_ts=1699037849.121969&cid=C05MS96P6P2):**

_And Dan, sounds like we'll need to pull that `CreatedAt` value as soon as next week for anyone with in-progress authenticated 527 forms, since we'll be [moving forward with deactivation](https://dsva.slack.com/archives/C05MS96P6P2/p1699037700349819). 

Let me know if you have any concerns about that timeline or want backup, friends from non-disability team are good helpers there (such as 
@Thomas Blackwell)_

---
## Acceptance Criteria
Pull the following information from in-progress authenticated 527 forms:
- created_at
- user_uuid
- user_account_id
- expires_at

**From Emily:**

- `created_at `and the user related IDs should be sufficient.
- The other thing we need is some kind of Veteran ID that is useful to VBA, which is usually File Number or SSN.
- Alternate good option could be Participant ID or EDIPI.
- Hopefully we store one or more of those for Pension.

(the va.gov user uuid is basically only useful to us; there are many Veteran IDs but some or more/less useful to different offices with different data)

- [ ] In-progress data with IDs for batch ITF creation will be provided to Emily

**Comment by vbellissimo** [comment]
@danlim715 reviewing

**Comment by mjknight50** [comment]
I think this was completed by @tblackwe
