### ISSUE TITLE
[QA] 10-10EZR: Write and Collate EZR Use Cases

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#69154]
As a Veteran, I would like to be able to add, update, and remove information from my VA record so that I make sure my information is up to date and I can get the care and information that I need.

- [x] List out all the use cases we need
- [x] Work with team to see what use cases we already have
- [x] Write use cases where needed
- [x] Delegate team members to write use cases as needed
- [x] Edit test cases as needed (e.g. if they're for EZ but there is a slight difference with EZR)
- [x] Update test cases to reflect use cases
- [x] **Success: We have a complete set of use and test cases to run tests against**

**Comment by fbonds** [comment]
USE CASES

1. As a Veteran, I want to Continue my form
    1. Resume form where I left off
2. As a Veteran, I want to Start a new form
    1. If I started a form already, I’ll be prompted as to whether or not I want that previous form to be overwritten
    2. My new form will display my information (full name, SSN, DoB, Gender)
3. As a Veteran, I want to verify my stored information
4. As a Veteran, I want to Update my stored information
5. As a Veteran, I want to change my address (mailing & home)
6. As a Veteran, I want to change my phone & email address
7. As a Veteran, I want to change my marital status
8. As a Veteran, I want to change my Spouse information (name, SSN, DoB, DoM
9. As a Veteran, I want to update my living situation with my spouse
10. As a Veteran, I want to update my Spouse address who doesn’t live with me.
11. As a Veteran, I want to add/remove a Dependent
12. As a Veteran, I want to update my Dependents info (name, relationship, SSN, DoB, Date of dependence)
13. As a Veteran, I want to Cancel adding a dependent
14. As a Veteran, I want to update the educational expenses of my college age dependent.
15. As a Veteran, I want to update my dependents additional info (disability, residence, income)
16. As a Veteran, I want to remove my dependent(s)
17. As a Veteran, I want to add additional dependents
18. As a Veteran, I want to update my income info (Gross, Net, Other)
19. As a Veteran, I want to update my spouses income info (Gross, Net, Other)
20. As a Veteran, I want to document my medical expenses (Non-reimbursable, college, funeral/burial)
21. As a Veteran, I want to update my Medicaid eligibility 
22. As a Veteran, I want to update my Medicare enrollment
23. As a Veteran, I want to update my other Medical Insurance information
24. As a Veteran, I want to cancel adding Medical Insurance info
25. As a Veteran, completing my EZR form, want to Review the changes I’ve made
26. As a Veteran, completing my EZR form, want to Edit the changes I’ve made
27. As a Veteran, I want to confirm the legitimacy of the information I’ve provided
28. As a Veteran, I want to submit my EZR form

**Comment by emily-brown34** [comment]
@fbonds can you please link the testing document you are using for these and test steps? i don't see the updated cases here: 
https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-1010EZR-Update-health-care-benefits.md

**Comment by fbonds** [comment]
Use cases compete (thanks @hdjustice!) 
https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-1010EZR-Update-health-care-benefits.md

Test cases updated to new Use cases:
https://dsvavsp.testrail.io/index.php?/runs/view/4976&group_by=cases:section_id&group_order=asc
