### ISSUE TITLE
[Team] 10-10EZR: Collate existing Use Cases for EZR

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#69155]
- [x] Find existing use cases we can use for EZR
- [x] Look in 10-10EZ Test Cases and documentation
- [x] Check Collab Cycle tickets
- [x] Go through Household section work
- [x] Send to @fbonds to collate 
- [x] **Success: We pull all existing use cases that are applicable to EZR**

**Comment by hdjustice** [comment]
done - [Use cases here](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-1010EZR-Update-health-care-benefits.md)
