### ISSUE TITLE
Adding [Christian Stutzman] to DSVA Slack

### ISSUE THREAD

**Issue by jsimonVA** [department-of-veterans-affairs/va.gov-team#69182]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

<describe the request>

Are you requesting to add an individual as a:

- Full member - Add as a full member
- Single guest
- Multi-channel
- Switching from single-channel to multi-channel?
- What channel(s) do they need to be added to? - will join teams once account is created.

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

User works on the vye_team as a frontend developer. I am the lead developer for this team and need Christian to gain access to slack to reach out to the platform team as needed to complete his tasks.

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add [_insert email_] as a single-channel guest to [_channel name_].
- Please add [_insert email_] as a multi-channel guest to these channels: [_channel names_].
- Please add [_insert email_] as a full member.
- Please change the status of [_slack username_] from [_current status_] to [_desired status_]

**Comment by LEHigley** [comment]
@jsimonVA who are you requesting to add?

**Comment by jsimonVA** [comment]
Good Morning,
The request was for Christian Stutzman but he has since been granted access. We can close this out.


[Logo  Description automatically generated with medium confidence]<http://govcio.com/>
Jarred Simon
Software Programmer 4

Phone (405) 4430002
Email ***@***.******@***.***> | ***@***.******@***.***>
About<https://governmentcio.com/about>   |   Services<https://governmentcio.com/services>   |   Careers<https://governmentcio.com/careers>   |   LinkedIn<https://www.linkedin.com/company/governmentcio/>


From: Lacey Higley ***@***.***>
Sent: Monday, November 20, 2023 6:50 PM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Simon, Jarred C. (governmentcio Llc) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Adding [Christian Stutzman] to DSVA Slack (Issue #69182)


@jsimonVA<https://github.com/jsimonVA> who are you requesting to add?

-
