### ISSUE TITLE
Update broken Get help header link

### ISSUE THREAD

**Issue by laucon** [department-of-veterans-affairs/va.gov-team#69187]
Johnny noticed that the Get Help link on the front of the Platform website is broken, so we need to fix it.

- [x] Play around to see how to fix the link
- [x] Input the correct link
- [x] Deploy

## Acceptance Criteria:

- [x] _Get Help_ button on Platform website has been tested, and sending users to the correct link

**Comment by johnny-jesensky-adhoc** [comment]
Tested this on Tuesday, November 7th. Confirmed it is working - fix has been implemented. Moving this to _Done_.

FYI @laucon
