### ISSUE TITLE
SOCKS access for Don Shin

### ISSUE THREAD

**Issue by cloudmagic80** [department-of-veterans-affairs/va.gov-team#69199]
### Your Name

Don Shin

### Your Email

don.shin@agile6.com

### Your Role and Team

Backend engineer

### Product Manager (PM) name and email

heather.rienks@agile6.com

### Product Owner (PO) name and email

premal.shah@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDUbV8PqNf9MqlUTRoxBmU1XXbO2kfl7hGTMTXEGxshCepuwebsSlavPllPwe8sspO4JsLO6IJF/j4W6c98I8fhv5pM9X0ad269Ml5NZRAlQ6nP/8nsDaKUnZ1ZG4AcD/zEge+CmkihZkMg4LjMOSrQ6Dz1oD0NAGk0ety5B1XE0lKRZLomRqLJxRzH0JiKlDqDpW9Yv4/gSZjGOUje61OyMR9wInrD8i1BUKEULcyG0ls74tPf+AKksk8z7cJ7qmwlIEuj0FoBV9WMkpUakCs3WgpfAGl3AQGQwMOzUYG4umQtxb3B9s69zAo7Prb3qI+CiLim6pLt9xo+u+N/tGdZyP3vWRP0UNqzVIUAwLfJwlRL/k2HHioxVfEhoFTZ8v7BsTmTEjIIer7DeZs6zF7HUEGzFBUuCkBajIM6JSqLjye9xpHQDM61XwcH1w/rM9r6YsTCOeDxTjIysFSISvatrYpc6KXWVlj5PAVI/10bpLFYqrO21B33Vtdwr0TA+6E= donshin@MacBook-Pro

### E-QIP Transmittal Confirmation

I don't have it.

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by hgbarreto** [comment]
@cloudmagic80  Access granted ✅

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Reach out in #vfs-platform-support if you have any trouble.
