### ISSUE TITLE
[Discovery] Extant Experience

### ISSUE THREAD

**Issue by carafrissell1** [department-of-veterans-affairs/va.gov-team#69193]
Collect an overview of past work done in the Travel Pay space.  The goal of the overview is to enable the team to identify gaps in knowledge and what questions are still unresolved...

Steps include:

- [x] Sync with OCTO UX Lead Kristen McConnell 
- [x] Review previous work by 18F
- [x] Sync with Check-in team and get up to speed on their work and the questions its answering 
- [x] Review Appointment team's past research 
- [x] Sync with Mobile team to review what they did and why 
- [x] Identify teams teams to collaborate with going forward

**Comment by micahtaylor** [comment]
Closing as we're met the AC in the steps. Just noting that we still are planning to define where best to keep our findings.
