### ISSUE TITLE
Truncation cuts off too much information on desktop

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#69191]
## Task Description
When all data is present, type of care and provider are truncated in desktop view. This work provides Veterans a desktop view that shows more data.

## Notes and References
Solutions discussed:
- Use current Tablet view layout for Desktop view
- Remove truncation on desktop and let words wrap

Consider future states where we might add even more data to the list.

## Acceptance Criteria
- [x] Update specs for Upcoming and Past appt list view 

## Deliverables
- [Design Specs](https://www.figma.com/design/dnfMEuJi3EiK2Tub51oD6f/Remove-truncation-on-appt-list-(desktop-view)-%7C-Appointments-FE?node-id=0-1&t=7lgH0BpVcnbjBsSk-1)

**Comment by outerpress** [comment]
@Cieramaddox I think you said you had some design files for this - could you link them in the ticket if so? Thanks!

**Comment by Cieramaddox** [comment]
@outerpress Linked specs in the ticket.

**Comment by outerpress** [comment]
Dev work happening in #89119

**Comment by outerpress** [comment]
Dev work is complete, closing
