### ISSUE TITLE
Find more broken links to Getting help from Slack document

### ISSUE THREAD

**Issue by laucon** [department-of-veterans-affairs/va.gov-team#69204]
- [x] Find more documents that contain broken links to the archived version of the Getting help from the Platform in Slack document.
- [x] Edit [External Integrations](https://vfs.atlassian.net/wiki/spaces/pilot/pages/640909834/External+Integrations) 
- [x] Deploy

## Acceptance Criteria:
- [x] Page containing link to archived Slack page --> https://depo-platform-documentation.scrollhelp.site/developer-docs/external-integrations has been successfully deployed to Platform website.

**Comment by johnny-jesensky-adhoc** [comment]
This has been validated on Tuesday, November 7th - moving to _Done_.
