### ISSUE TITLE
IA Request: Decision Review Pages

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#6920]
What this is: Work with VSP Information Architecture experts to finalize the IA of Decision Reviews and legacy appeals content on VA.gov

## Required Inputs:
- Link to product outline: [AMA Follow-up Changes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/AMA%20Follow%20Up/AMA%20Follow%20Up%20Product%20Outline.md#appeal-modernization-process-ama--follow-up-changes-outline)
- Link to or attach prototype or mockups: https://app.moqups.com/Rnc4BDEKrA/view/page/a5e3c0342
- Link to research readout/results: N/A. No research being done at this time.

## Information Architecture Worksheet (Optional)

Provide the following information, as available, to support the final information architecture of your product.

**SEO Keywords**
- Enter a list of keywords used by your target audience when they talk about or search for your content

**Proposed site map/page structure** (if more than one page)
-(https://images.zenhubusercontent.com/5d41d21a6db71633490a2764/443872c5-49a3-4a48-8e61-784fa5e3fe1c

**Suggested URL(s)**
- Provide suggested URLs and any background or rationale

- [ ] Change url for https://www.va.gov/disability/file-an-appeal/ to one that reflects it's now the Manage a legacy VA appeal page

- [ ] Change url for https://www.va.gov/decision-reviews/multiple-party-claims/ to reflect new page title: Contested claims

- [ ] Correct breadcrumb at https://www.va.gov/disability/file-an-appeal/board-of-veterans-appeals/

**Suggested entry points**
- What is the primary entry point for users to find your new content/tool - consider benefit hub pages, top nav, left nav, footer, profile/account, home page, etc.

**Crosslinking opportunities**
- What additional related areas of the site would links to your content/tool be helpful?

**Redirects/canonical tags**
- Will existing pages/tools need to be redirected or canonicalized?

## Definition of Done
- [ ] Issue is created, tagged and assigned to Content and IA team
- [ ] Required information above is complete and optional information provided where available
- [ ] IA reviews information and provides final feedback/recommendation on ticket
- [ ] Requesting team closes issue upon implementation
- [ ] Requesting team member complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

**Comment by mnorthuis** [comment]
@lwalsh617 IA recommendations are available here: 
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/websites-decision-reviews.md

There are 2 open questions:
1) Will the legacy Board of Appeals page be retired or need to be moved along with the other legacy content
2) Placement of link to decision reviews on the home page - for this I am waiting for some info from analytics. 

We will finalize this after the collab meeting Friday.

**Comment by jenniferlee-dsva** [comment]
I have the same #1 question above about the legacy Board appeals page. @lwalsh617 did you get SME confirmation about that page. We removed the link to that page in the last phase of updates, per their request. We need to remove and redirect it or consolidate it with the DR Board page. 

@mnorthuis - Thank you for the IA recommendation. Super clear to understand. Only one question - from where else should we link to the new DR hub landing page? I think we determined that it is the new appeals process for multiple types of benefit claims but that Disability is the primary one. Should we link to it from other hubs or perhaps same places that currently link to check status?

**Comment by lwalsh617** [comment]
@jenniferlee-dsva @mnorthuis -- I didn't get SME feedback, so will call it out the following when we send out Drupal preview links:
![image](https://user-images.githubusercontent.com/53535663/77773188-a2738c00-701f-11ea-9315-e4b6265d7701.png)

**Comment by mnorthuis** [comment]
@jenniferlee-dsva I didn't add it to any other hubs yet because I wasn't sure if it was ready to go that broadly.  When we first launched the DR content we intentionally did not reference it in any other hubs until we would have time to speak with each LOB.  If this is ready to go global across all hubs, let me know, and I will add entry points as appropriate.

**Comment by lwalsh617** [comment]
@jenniferlee-dsva @mnorthuis -- Following up on Mikki's question ^. Are we adding entry points before we can send IA to SMEs for review? Would like to send IA along with decision-review-page Drupal preview links to SMEs tomorrow morning (with a note that we're looking for them to flag any inaccuracies as we're launching on Friday). Thank you!
FYSA @MickinSahni

**Comment by lwalsh617** [comment]
@mnorthuis - Per today's grooming call, can you go ahead and recommend placement of decision-review-hub-page links across other hubs and/or wherever we have track status links, etc? We can then send each LOB owner an FYSA email that it will go live if they raise no objections. Thank you!
@MickinSahni FYSA

**Comment by mnorthuis** [comment]
@lwalsh617 I wasn't on the grooming call, is the request to add a link to decision reviews in every core benefit hub? What about service member and family member hubs?  I don't know enough about the process as it pertains to each benefit type or what they can appeal to know for sure if its appropriate for each benefit.

**Comment by mnorthuis** [comment]
@lwalsh617 Just following up on this, do we have an indication on which Benefit types having the links to decision reviews is appropriate?

Also, do we have answers to questions regarding the legacy Board of Appeals page?

**Comment by lwalsh617** [comment]
@mnorthuis I have a draft email ready to go with the questions about the board appeals pages and which benefit hubs require a link to the decision reviews hub page, along with links to Drupal preview pages. Am hoping to send today after stand up. Let me know if you have any other questions/clarifications you want to add. Thanks!
[AMA sme email DRAFT.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4462138/AMA.sme.email.DRAFT.docx)

**Comment by lwalsh617** [comment]
@mnorthuis - Per the SME feedback, here are the hubs that require links to the decision reviews hub page:
![image](https://user-images.githubusercontent.com/53535663/79462999-45d41300-7fc6-11ea-822d-a53116c45c35.png)

**Comment by mnorthuis** [comment]
@lwalsh617 Let's handle the above request separately and close this issue.

**Comment by mnorthuis** [comment]
Remaining tasks handled in new issues, primary IA work complete.  Closing issue.
