### ISSUE TITLE
Decision Reviews Pages:  Update Drupal Node IDs

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#6922]
## Drupal Node ID updates

After Decision Review pages have been moved from GitHub to Drupal (per ticket 6798) please update the Node IDs on these pages: 

- [x] VA decisions reviews and appeals https://www.va.gov/decision-reviews/
- [x] After you request a decision review https://www.va.gov/decision-reviews/after-you-request-review/
- [x] File a Supplemental Claim with new evidence  https://www.va.gov/decision-reviews/supplemental-claim/
- [x] Request a Higher-Level Review https://www.va.gov/decision-reviews/higher-level-review/
- [x] Request a Board Appeal https://www.va.gov/decision-reviews/board-appeal/
- [x] After a Board Appeal ... https://www.va.gov/decision-reviews/board-appeal/after-board-appeal-decision/
- [x] Multiple party contested claims https://www.va.gov/decision-reviews/multiple-party-claims/
- [x] Fiduciary claims https://www.va.gov/decision-reviews/fiduciary-claims/
- [x] Insurance claims https://www.va.gov/decision-reviews/insurance-claims/
- [x] FAQs https://www.va.gov/decision-reviews/faq/
- [x] Get help with... https://www.va.gov/decision-reviews/get-help-with-review-request/
- [x] Board hearings with a VLJ https://www.va.gov/decision-reviews/board-appeal/veterans-law-judge-hearing/

      
  

--- 
#### Next steps
- [x] Node IDs added

#### Definition of Done
* Request ticket is closed and implementation tickets created as needed

**Comment by RLHecht** [comment]
Adding in Jen's Word doc for changes to be updated in each of the Drupal pages after her first review:[Uploading... AMA-preview-pg-jl-comments-032420.docx ]

**Comment by lwalsh617** [comment]
[ama-preview-pg-jl-comments-032420.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4381995/ama-preview-pg-jl-comments-032420.docx)
Testing! I think Jen's doc did not upload previously because the file name had cap letters. Here it is without caps.

**Comment by MickinSahni** [comment]
2020-03-26 PW Standup
- All Drupal node ids are in 
- Remaining: incorporate time frame language per Jen's feedback

**Comment by MickinSahni** [comment]
2020-03-27 PW Standup
- Closing this out as node ids have been updated
