### ISSUE TITLE
[QA] 10-10EZ - eMIS Deprecation: Regression testing

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#69236]
## Background
eMIS is being deprecated, and any teams that call eMIS for Military information will need to migrate to using VA Profile.  Any code that calls eMIS needs to be updated to call VA Profile.

Since our work migrated to VA Profile earlier this year, we have no further changes to make.  However, we do have to run some regression testing to ensure there have been no impacts.

> There are certain prefill values that we need teams to specifically test... they are outlined in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/64879#issuecomment-1739929634). If you have questions or comments, please tag > [@Rebecca Tolmach](https://dsva.slack.com/team/U02SN5US7LK) in the [#-emis-deprecation](https://dsva.slack.com/archives/C03LT909K1A) channel.

>Reminder: the feature flipper is military_information_vaprofile. It's ON in [dev](https://dev-api.va.gov/flipper/features) and [staging](https://staging-api.va.gov/flipper/features) and OFF in prod. Feel free to turn it off and on as needed in dev and staging BUT NOT Prod :smile: thank you!

## Tasks
- [ ] Complete regression testing in Staging, specifically focusing on the Military Info pre-fill
- [ ] Tag Lainey Trahan, Lindsey Hattamer and Heather Justice, once the testing is completed

## Acceptance Criteria
- Regression testing is completed successfully

**Comment by hdjustice** [comment]
There are certain prefill values that we need teams to specifically test... they are outlined in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/64879#issuecomment-1739929634). If you have questions or comments, please tag 
[@Rebecca Tolmach](https://dsva.slack.com/team/U02SN5US7LK)
 in the [#-emis-deprecation](https://dsva.slack.com/archives/C03LT909K1A) channel.

**Comment by jadon1979** [comment]
@laineymajor @hdjustice @LindseySaari
