### ISSUE TITLE
rotate prod MPI Cert

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#69258]
Instructions here: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/edit/master/teams/vsp/teams/Identity/Documentation/Security/Rotate_certs.md

Prod cert needs to be rotated before the end of this week.

**Comment by vidjovanovic** [comment]
Reached out to Shawn Carter to coordinate cert rotation. Looked over repos and assessed what needs to be changed.
