### ISSUE TITLE
Remove old appointment list code

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#69255]
## Description
This ticket is for the old Appointment List Components cleanup. The new appoinment list is live in prod so we want to cleanup the old appointment list components that are no longer used/needed

---

## Acceptance Criteria
- [ ] Cleanup all unused Appointment list components.
- [ ] Cleanup all associated unit and end to end tests.

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by ldelacosta** [comment]
Closing out this ticket. No issues reported. cc: @simiadebowale
