### ISSUE TITLE
rotate ssoe-sp dev and staging certs

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#69259]
Instructions can be found here: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/edit/master/teams/vsp/teams/Identity/Documentation/Security/Rotate_certs.md

Should be done by the 17th of November.

**Comment by jhouston0** [comment]
Heres the gameplan:
1. All three devops engineers should be present for both cert rotations
2. @vidjovanovic will rotate dev certs
3.  @zyellowhorse will do staging

**Comment by jhouston0** [comment]
First working session for Dev certs is 11/15/23 at 1300 EST

**Comment by vidjovanovic** [comment]
Reached out to Shawn Carter to coordinate cert rotation. Looked over repos and assessed what needs to be changed.
