### ISSUE TITLE
Create recommended notification settings and user preferences for CircleCI, Sentry, and GitHub

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#6926]
# Overview

VSP integrates with several third party tools and each of these tools has its own set of configuration options. Often the default options do not offer the optimal experience for VSF engineers.

## Goal

- Document recommended user preferences for all third party tools 

## Potential tasks

- Recommend setting email notifications in Circle under User Settings > Notification settings > Email Preferences by Organization to "Branches I've pushed to" 
- Recommend turning on browser notifications for Circle
- Determine recommended settings for sentry and github.

**Comment by rianfowler** [comment]
cc @dbru FYI

**Comment by kfrz** [comment]
@rianfowler super nitpicky, but to be clear, this is for notification and user preferences, not application configuration, correct?

Maybe we want the issue title to clarify preferences over configuration if that's the case.

**Comment by rianfowler** [comment]
@kfrz done thanks for the recommendation.

**Comment by rianfowler** [comment]
This should include recommendations for scheduled reminders: https://github.com/settings/reminders/department-of-veterans-affairs

You'll need to work with a slack admin to turn this on.
