### ISSUE TITLE
Design Intent - Design Feedback - Iterate Innovate Run, Performance Dashboard, NA

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#69270]
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

-

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- **Must**: Look at the guidance for [additional info component guidance](https://design.va.gov/components/additional-info#when-to-consider-something-else), specifically around the amount of content. Most of your additional info components have too much content. If you do keep this component, use the [coded component in Storybook](https://design.va.gov/storybook/?path=/docs/uswds-va-additional-info--default).

**Comment by raquelou** [comment]
We looked into the additional info component and considered different ways of communicating the information currently in the additional info component. We determined that the current implementation was the best for now. We are switching the design over to the coded component found in storybook.
