### ISSUE TITLE
[Deactivation] Campaign URLs for Pension Deactivation Email

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#69288]
## Issue Description
Slack thread: https://dsva.slack.com/archives/C05MS96P6P2/p1699309847562729

In order to track the analytics, are you able to either create (if they haven’t been yet) or share with me the URLs with the UTM campaign associated to them from VA Notify portal? (edited) 

---
## Tasks
- [x] Create UTM campaign associated tracked URLs for the following URLs to be used on the Pension Deactivation Email:

- https://www.va.gov/pension/how-to-apply/#how-do-i-apply
- https://www.va.gov/pension/application/527EZ/introduction
- https://www.va.gov/pension/how-to-apply/

- [x] Provide tracking URLs to either Vicky and/or Sean to incorporate into deactivation email build.

Thomas and Vicky discussed using  campaign name of `2023pensions` or `2023pensiondeactivation`

URLs requests are based off this email mockup from CAIA:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDJwQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c8d1e33258cb7b1c65288260a61d8be34ef3ca9b/Screenshot%20%28350%29.png)
and

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDZwQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e94b2b39528315afb9eb5ca524b4db76fa623829/Screenshot%20%28349%29.png)

## Acceptance Criteria
- We will have all the necessary tracked URLs from VA Notify
- Engineering building the email template will have the tracked URLs to incorporate into the email.

**Comment by tblackwe** [comment]
`[Find out how to submit a PDF form](https://www.va.gov/pension/how-to-apply/#how-do-i-apply?utm_source=VANotify&utm_medium=email&utm_campaign=2023pensiondeactivation)`

`[Sign in to VA.gov to refer to your saved information](https://www.va.gov/pension/application/527EZ/introduction?utm_source=VANotify&utm_medium=email&utm_campaign=2023pensiondeactivation)`

`[Learn more about how to apply for VA pension benefits](https://www.va.gov/pension/how-to-apply/?utm_source=VANotify&utm_medium=email&utm_campaign=2023pensiondeactivation)`
