### ISSUE TITLE
SOCKS access for Gregg Puhala VFEP Sustainment Team

### ISSUE THREAD

**Issue by GcioGregg** [department-of-veterans-affairs/va.gov-team#69281]
### Your Name

Gregg Puhala

### Your Email

gregg.puhala@va.gov

### Your Role and Team

Ruby on Rails Developer VFEP Sustainment Team

### Product Manager (PM) name and email

Darla van Nieukerk Darla.vanNieukerk@va.gov

### Product Owner (PO) name and email

Darla van Nieukerk Darla.vanNieukerk@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC6E5/4jHoQUePARR6Z5cGsWE01OmAgE8zkMFK07gGc6oxak27tRm7kVWK0CfMA261KcdSO+O6AgcVGt2Gx9HNEd8wx6r2zX2zBdenEY5RMDbH7xjdrW0nlXMJC9jNbSLTepaouwK8pcAh4/dFK6p9GEOJ1ktPf6xppPQX784prded2EXVI8JHOY8ybw4+efABNCIf3vUXv6/FWoN47iMwgqqUY64OZ3SfyVhK6nLMxSBBZdr9FWbdBi7sGTZZIc7iMsqLQvkUG/pQLG2WQvR7JJ6/LQy6PQxaF9oY6yr1X8oEI1FaQ1M11e/EfL8R0dtBFqncfdNcW1o92aMKhcXOlgkzuOPz5PbnqgZXVzrx6k0UMoCLIZjBkODY6055qL4k3etY3EfyWzX9Qg/yAjBEPBnL++mg3MD3x4cbU+Q74ICp+pLddNCamEMUAe7aMrfTC+s+iDhXtCYkf/ZMhqskpw0TfL7sJrlzwcQog/l328U/aLZ/aPzkOuLvYkbeEWO0= gregg@VA-Machine

### E-QIP Transmittal Confirmation

Can't find it, but I've had access to the system for over a year now.

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by hgbarreto** [comment]
@GcioGregg Access granted ✅

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Reach out in #vfs-platform-support if you have any trouble.
