### ISSUE TITLE
Adding [Holly Hansen] to DSVA Slack

### ISSUE THREAD

**Issue by Eallan919** [department-of-veterans-affairs/va.gov-team#69309]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

Please add Holly Hansen to DSVA slack as a full time member as she is supporting Ask VA (AVA) Integration under CEDAR!

Are you requesting to add an individual as a:

- Full member

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

We aim to complete slack requests within 24hrs.

## Sample Descriptions 

- Please add [holly.hansen@thoughtworks.com] as a full member.

**Comment by Eallan919** [comment]
@LEHigley howdy! Is it possible to get this approved? We are running into a few blockers and this would help us greatly! Please let me know if you need anything from me.

**Comment by beckyphung** [comment]
@LEHigley Hi Lacey! Could you please approve this request to add Holly to the DSVA Slack? We haven't been able to Slack her for the past couple of days and work is ramping up. Thank you :)
