### ISSUE TITLE
VA Profile character of discharge codes are different from eMIS

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#69312]
### Problem
The `discharge_types` method in `id_card_attributes.rb` pulls the character of discharge code. These codes differ from eMIS to VA Profile. This caused a bug in the VIC form when we accidentally released the changes to prod. Other forms that use this code check to make sure it's an acceptable value. 

### Questions
1. We are returning the character of discharge code that comes from eMIS and these values seem to be acceptable (current implementation). With VA Profile, there are more character of discharge codes that can be returned (see table below). What do we do with these (`DVN`, `DVU`, etc.)?
    1. Is there any use for these tri-character codes? 
    2. Should we just ignore these values (i.e. not pass them on in the VIC application)?
2. What are the acceptable values for the veteran ID card application (VIC)?
3. How do we test the VIC form in lower environments?
----

### Research
**Background**
When we merged PR https://github.com/department-of-veterans-affairs/vets-api/pull/14205 without wrapping the `discharge_types` code from `id_card_attributes.rb` in the feature flipper, that code was in production for about 24 hours. During that time, some veterans reported that they were getting the wrong character of discharge code for the VIC form. This was reported [in this Slack thread](https://dsva.slack.com/archives/C03LT909K1A/p1698431721264129).

**Research notes**
- In `military_information.rb`, we also get this discharge code to pass along to other forms. We check to make sure the code we get is among an approved list of codes, or else we return `nil`.
- In eMIS, the attribute is `discharge_character_of_service_code`
- In VA Profile, the attribute is `character_of_discharge_code`
- In both of them, the attribute lives inside an array of military service episodes sorted by date aka `service_episodes_by_date`. That means a veteran can have multiple character of discharge codes. 
- What are the options for what the discharge code can be for VA Profile and for eMIS? See tables below:

**_VA Profile_**
| Code | Name                                             | Honorable Service Indicator |
| ---- | ------------------------------------------------ | --------------------------- |
| A    | Honorable                                        | Y                           |
| B    | Under honorable conditions (general)             | Y                           |
| D    | Bad conduct                                      | N                           |
| E    | Under other than honorable conditions            | N                           |
| F    | Dishonorable                                     | N                           |
| H    | Honorable (Assumed) - GRAS periods only          | Y                           |
| J    | Honorable for VA Purposes                        | Y                           |
| K    | Dishonorable for VA Purposes                     | N                           |
| Y    | Uncharacterized                                  | Z                           |
| Z    | Unknown                                          | Z                           |
| DVN  | DoD provided a NULL or blank value               | Z                           |
| DVU  | DoD provided a value not in the reference table  | Z                           |
| CVI  | Value is calculated but created an invalid value | Z                           |
| VNA  | Value is not applicable for this record type     | Z                           |

**_eMIS_** _(sourced from [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/engineering/2018-prefill-docs/emis-integration/emis-documents/va-sat-4.6-dd-051216.xlsm))_
| Code | Name                                                      | Honorable Service Indicator |
|------|-----------------------------------------------------------|-----------|
| A    | Honorable                                                 |           |
| B    | Under honorable conditions (general)                      |           |
| D    | Bad conduct                                               |           |
| E    | Under other than honorable conditions                     |           |
| F    | Dishonorable                                              |           |
| H    | Under honorable conditions (absence of a negative report) |           |
| J    | Honorable for VA Purposes (Administrative use by VA only) |           |
| K    | Dishonorable for VA Purposes (Administrative use by VA only) |         |
| Y    | Uncharacterized                                           |           |
| Z    | Unknown                                                   |           |

In the current (eMIS) implementation, any of the codes in the eMIS table above could be returned. There is no data or string validation to make sure it's a recognized code. When we cut over to VA Profile, there was also no data/string validation being done so values like `DVN` were being returned, which was not expected. _**I'm assuming all of the eMIS codes were valid and acceptable.**_  

### Acceptance criteria
- [ ] The VIC form gets the right information.

**Comment by rmtolmach** [comment]
Here's an idea on how to handle the three character codes from VA Profile:
- https://github.com/department-of-veterans-affairs/vets-api/pull/14450

**Comment by laineymajor** [comment]
@rjohnson2011 to review for awareness

**Comment by laineymajor** [comment]
We need to know:
DO YOU WANT US TO JUST MAKE THIS WORK WITH EXISTING EMIS VALUES?
We need an SME from VIC to help answer this question... reach out to Joe Valentine.
- what do you want us to return when we get one of the unknown values?

**Comment by rmtolmach** [comment]
> what do you want us to return when we get one of the unknown values?

Heard back from Joe. Joe is not in a position to make that decision. The meeting to discuss this is Nov. 28. This is after the pre-Thanksgiving deadline that was set, so that will need to be communicated to the eMIS team.

**Comment by laineymajor** [comment]
Lainey to reach out and indicate the nov 28 meeting is later than what we would like, but if that's what they want, we can go with it.

**Comment by laineymajor** [comment]
Would prefer to keep the returned data as close to the formatting of emis as possible.

**Comment by laineymajor** [comment]
This will carryover to next sprint or until we get the answers from VIC.

**Comment by rmtolmach** [comment]
Summary of decision made during the VIC Data call:
If one of the following codes is returned, send an empty string to VIC in its place. 
- DVN
- DVU
- CVI
- VNA 

In addition, if no manual testing solutions are found, we can plan to be in close communication with Meilssa and Molly about when we turn the feature flipper on for this and they can let us know if they see anything fishy and we can turn it off.

**Comment by LindseySaari** [comment]
Working with the VIC team to roll this out to prod. They've accepted the fact that this cannot be tested in lower envs, and will watch for "bad data"

**Comment by rmtolmach** [comment]
We turned the flipper on in prod for six hours on Friday 12/1. No problems were seen. It's on again today and VIC team will again monitor applications that come in for bad data. How long will we need to do this before we leave it on for good? 24 hours? That would be Wednesday afternoon.

**Comment by rmtolmach** [comment]
We left the flipper on overnight so VIC has been getting character of discharge codes from VA Profile for > 35 hours. We are calling this DONE! :tada: :tada:
