### ISSUE TITLE
Add unit test coverage for AppointmentColumn.jsx

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#69347]
## Description
Add unit test coverage for `AppointmentColumn.jsx` path: `src/vaos/appointment-list/components/AppointmentsPageV2`

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK092QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7d16bd26faac1ac4a7d4c987e9c06d94911763d5/Screenshot%202023-11-07%20at%2012.48.30%20PM.png)

---

## Acceptance Criteria
- [ ] file coverage for Branches, functions, lines and statements is 100%

## Definition of Done
- [ ] All acceptance criteria are met

**Comment by JunTaoLuo** [comment]
We can probably close this issue now. There's no visible changes to validate since it's a testing only ticket.

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket.
