### ISSUE TITLE
Documentation support

### ISSUE THREAD

**Issue by tommasina-va** [department-of-veterans-affairs/va.gov-team#69342]
### Request type

- [X] Writing new documentation
- [ ] Updating previously published documentation
- [ ] Reviewing recently written, never-before-published drafts

### Number of docs

1

### Subject matter expert

Tommasina Miller

### Approvals

I'm not sure

### Embedded media

- [X] Screenshot(s)
- [ ] Diagram(s)
- [ ] Video(s)

### Audience

- [X] Developers
- [ ] Designers and researchers
- [ ] Product managers
- [ ] Other

### Anything else?

I found the documentation on making a form field optionally required helpful, but I needed a lot of help to figure out how to make a form field fully optional since that required vets-json-schema and vets-api updates. Here's a start to that documentation:

#### vets-json-schema
- If you want to make a form field optional, first open a PR in `vets-json-schema` and remove the field from the required property in your application's specific schema. You’ll have to remove it twice: once from the schema JSON file, and once from the schema JavaScript file. (You’ll also increment the package.json version.)

<img width="241" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/144388524/01d85e51-6dd6-4592-a763-dbaa60a75d59">

- Important notes: if you are using a regex pattern to validate a field and you wish to make that field optional, you’ll need to adjust the regex in `vets-json-schema`to accept an empty string, or else the user won’t be able to advance without fulfilling the pattern required by the regex even though the field won’t be marked as required.

<img width="265" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/144388524/4f828a8c-af42-4892-9d4d-9a7a3b4e5253">

#### vets-website
- Second, make your changes in `vets-website.`
    - To test your changes locally, you can update your package.json and yarn.lock to point to the commit SHA of your `vets-json-schema` commit, and update the version referenced in the yarn.lock, and then `yarn install`.

<img width="822" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/144388524/410bbe8d-8382-46f3-9817-ca7583dbdb47">

#### vets-api
- Third, make a PR for `vets-api` that references the new `vets-json-schema` version in the `gemfile.lock`.

<img width="464" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/144388524/9726511f-ebff-461e-802e-c0df6527d389">

#### Tips and Testing
- You’ll want to try to merge your PRs as closely together as possible so that the schema version matches across backend and frontend. One tip is to merge after the production deploy for the day so you can have a longer period of time to test on Staging.

- Testing notes:
    - For making a field optional, you’ll want to remove it from any “minimal” tests in vets-website and the schema specs in vets-json-schema to make sure that the tests work without the field.

**Comment by johnny-jesensky-adhoc** [comment]
Hi @tommasina-va, thank you for submitting this request. the Platform is taking a look for next steps. We will be sure to provide updates to this within the ticket.

**Comment by taylojill** [comment]
Hi there @tommasina-va, I'll be working on your documentation support request. Can you send me a link to the existing documentation on making a form field optionally required? I'd like to take a look at it. Thank you!

cc @johnny-jesensky-adhoc

**Comment by taylojill** [comment]
Hi @tommasina-va I'm following up on your request for documentation support. Please let me know where the existing documentation lives on the Platform web site. I'd like to review and determine how and where to incorporate your new content. Thank you! Link to Platform web site: [https://depo-platform-documentation.scrollhelp.site/](url)

cc @johnny-jesensky-adhoc

**Comment by taylojill** [comment]
Hi @tommasina-va I'm following up regarding your support request. Please let me know where the existing documentation lives on the Platform web site. I'd like to review and determine how and where to incorporate your new content. Thank you! Link to Platform web site: [https://depo-platform-documentation.scrollhelp.site/](url)

cc @johnny-jesensky-adhoc

**Comment by taylojill** [comment]
Draft page sent to requestor via Platform content channel in Slack. Waiting for feedback.

**Comment by taylojill** [comment]
Content approved with one minor change. Page will be updated, moved to IA, reviewed for launch-blocking issues, and prepared for deployment.
