### ISSUE TITLE
Add unit test coverage for AppointmentListItem.jsx

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#69349]
## Description
Add unit test coverage for `AppointmentListItem.jsx` path: `src/vaos/appointment-list/components/AppointmentsPageV2`

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2V2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c2be158c54d5beb24f9b4d20deb52357f4f27a2e/Screenshot%202023-11-07%20at%2012.52.20%20PM.png)

---

## Acceptance Criteria
- [ ] file coverage for Branches, functions, lines and statements is 100%

## Definition of Done
- [ ] All acceptance criteria are met

**Comment by JunTaoLuo** [comment]
Closed as obsolete in favor of the new approach in https://github.com/department-of-veterans-affairs/va.gov-team/issues/89844.
