### ISSUE TITLE
Add unit test coverage for AppointmentFlexGrid.jsx

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#69353]
## Description
Add unit test coverage for `AppointmentFlexGrid.jsx` path: `src/vaos/appointment-list/components/AppointmentsPageV2`

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0d2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--955d2cfa18702feb1dc3dd1b0655075b061a8254/Screenshot%202023-11-07%20at%2012.57.03%20PM.png)

---

## Acceptance Criteria
- [ ] file coverage for Branches, functions, lines and statements is 100%

## Definition of Done
- [ ] All acceptance criteria are met

**Comment by JunTaoLuo** [comment]
Closed as obsolete in favor of the new approach in https://github.com/department-of-veterans-affairs/va.gov-team/issues/89844.
