### ISSUE TITLE
Add unit test coverage for AppointmentColumn.jsx

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#69351]
## Description
Add unit test coverage for `AppointmentColumnLayout.jsx` path: `src/vaos/appointment-list/components/AppointmentsPageV2`

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1d2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--45216f09f0143d328a5e72e6a96c217a09bed6fb/Screenshot%202023-11-07%20at%2012.50.10%20PM.png)

---

## Acceptance Criteria
- [ ] file coverage for Branches, functions, lines and statements is 100%

## Definition of Done
- [ ] All acceptance criteria are met

**Comment by JunTaoLuo** [comment]
Closed as obsolete in favor of the new approach in https://github.com/department-of-veterans-affairs/va.gov-team/issues/89844.
