### ISSUE TITLE
Address scalability of ETL for the monthly MPI data export

### ISSUE THREAD

**Issue by sdickson-gt** [department-of-veterans-affairs/va.gov-team#69365]
## Issue Description
The processing time for handling ETL is not scaling.  It is now taking 2+ hours to process the monthly import.

---
## Tasks
- [x] Investigate alternatives to improve ETL processing for the MPI export, e.g. considering Domo partitions

## Acceptance Criteria
- [ ] Documented design alternatives

**Comment by lmorris3** [comment]
@sdickson-gt is this still relevant or is the work being handled through other tickets on the board?

**Comment by sdickson-gt** [comment]
This is resolved and completed a few months back under a separate ticket.
