### ISSUE TITLE
Add unit test coverage for PastAppointmentsListV2/index.jsx

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#69364]
## Description
Add unit test coverage for `PastAppointmentsListV2/index.jsx` path: `vaos/appointment-list/components/PastAppointmentsListV2/index.jsx`

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHF3QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--035854fe893438965572bbf0e0dc0f5bff930d12/Screenshot%202023-11-07%20at%201.17.01%20PM.png)

---

## Acceptance Criteria
- [ ] file coverage for Branches, functions, lines and statements is 100%

## Definition of Done
- [ ] All acceptance criteria are met

**Comment by JunTaoLuo** [comment]
Closed as obsolete in favor of the new approach in https://github.com/department-of-veterans-affairs/va.gov-team/issues/89844.
