### ISSUE TITLE
Add unit test coverage for AppointmentsPageV2/index.jsx

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#69361]
## Description
Add unit test coverage for `AppointmentsPageV2/index.jsx` path: `src/vaos/appointment-list/components/AppointmentsPageV2/index.jsx`

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEd3QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--87bf3e91849b950ce98d95f121eb2dc866b366d5/Screenshot%202023-11-07%20at%201.11.30%20PM.png)

---

## Acceptance Criteria
- [ ] file coverage for Branches, functions, lines and statements is 100%

## Definition of Done
- [ ] All acceptance criteria are met

**Comment by JunTaoLuo** [comment]
Closed as obsolete in favor of the new approach in https://github.com/department-of-veterans-affairs/va.gov-team/issues/89844.
