### ISSUE TITLE
FE | Maintenance Period Alerts | Build for using the new alert

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#69386]
## Background
[use the alert that was created here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/69212) and the [feature toggle here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/69383) to ensure we can turn off access to the sections of the profile that will be impacted by the outage 11/18-19
Dependency 0n 69212
## Tasks 

- show alert on main profile page
- show alert on direct deposit page
- how would multiple outages work? figure out how that could be displayed and toggled for multiple pages and comment on this ticket/document the workflow if possible.

## Acceptance Criteria 
- [x] we can enable the feature toggle and see the alert displayed on the first page of the profile and the impacted pages (in this case the direct deposit C&P, Edu, and payments sections of the profile, ie. all of the direct deposit tab) <<<

**Comment by adamwhitlock1** [comment]
I updated the time today to the new end time, so this should be good to validate and close out

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFBoQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--94f743076cfdf7131ef525826e43eb86a601e3c1/Screenshot%202023-11-16%20at%2012.15.34%E2%80%AFPM.png)
