### ISSUE TITLE
FE | Maintenance Period Alerts | Feature Toggle

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#69383]
## Background 
We have a maintenance period 11/18-19/2023 that we need to quickly stand up this alert that advises users to an outage 

## Tasks

- add feature toggle to FE. toggle will be called `	auth_exp_vba_downtime_message` 
- build base functionality to display on the profile main page as well as direct deposit page
- add tests for toggling the display of the alert
- bonus: investigate how this could be further reused to indicate an outage on any profile page, and how that might look in the code

## Acceptance Criteria 
- [x] we've got a functioning feature toggle that can be used for the short term goal of turning on the alert for the system outage that's occurring the weekend of 11/18 and can be reused for our longer term solution

**Comment by adamwhitlock1** [comment]
this is done and active on staging along with the actual alert. Good to validate / close now
