### ISSUE TITLE
BE | Maintenance Period Alerts | Build for short term alert

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#69387]
## Background 
We have a maintenance outage that is immanent on 11/18-19 and this ticket should support any backend work that's needed to ensure we're ready for that outage.

## Acceptance Criteria 
- [x] backend work is installed and ready ahead of the outage on 11/18

**Comment by tpharrison** [comment]
@mtcA6 Is this to add a feature flag?  I'm not sure what else to do here...let's discuss in planning.

**Comment by mtcA6** [comment]
Adam mentioned needing to wire things up, I think in reference to the pager system(was it pager duty?), I made a separate feature flag ticket.

**Comment by adamwhitlock1** [comment]
After discussing with Allison we decided on going with a single feature toggle for all of the authenticated experience team. She has already submitted and merged the PR for this, so I will not need to work this ticket.

PR: https://github.com/department-of-veterans-affairs/vets-api/pull/14494

**Comment by mtcA6** [comment]
dup
