### ISSUE TITLE
Review new Content Review ROE with VSA Teams

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/va.gov-team#694]
Definition of done
- [ ] Meet with VSA Teams PMs to go over Content Review ROE
- [ ] document findings and feedback from that meeting to recommend for doc iteration

VSA teams:
- Authenticated Experience: PM Justin Pickett 8/13 meeting
- Global-UX.  PM: Kara Kemahli 8/16 meeting
- Benefits-memorial. PM: Yana Roy 8/22 meeting
-  eBenefits. TK

**Comment by peggygannon** [comment]
**8/22/19 update** Have met with the following PMs and reviewed the Content ROE. 

- Justin Picket. Authenticated Experience PM. 8/13 meeting
- Kara Kemahli Global-UX PM. 8/16 meeting
- Yana Roy Benefits-memorial PM. 8/22 meeting

Their questions and feedback are documented here: 
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/Practice%20Areas/Content/content-ROE-insights.md
