### ISSUE TITLE
Completed: Design Intent - Veteran Facing Forms - Document Evidence Submission/20-10208

### ISSUE THREAD

**Issue by it-harrison** [department-of-veterans-affairs/va.gov-team#69404]
This ticket is for Platform tracking purposes only. There is no VFS action needed.

**Comment by shiragoodman** [comment]
@it-harrison was this a test? I don't think the Design Intent for this product has happened yet.

**Comment by it-harrison** [comment]
@shiragoodman yes, just checking the workflow works (it does!)

**Comment by shiragoodman** [comment]
@it-harrison can we rename the title and remove the `governance-team` label when you and @briandeconinck are finished testing? It still technically shows up in our tracking reports bc of the label. Just want to make sure that I don't double count it or refer to it on accident. Thank you!
