### ISSUE TITLE
Incorrect link for logging in locally in Setting up your local frontend environment

### ISSUE THREAD

**Issue by ataker** [department-of-veterans-affairs/va.gov-team#69406]
### Description

In the backend part of [Setting up your local frontend environment](https://depo-platform-documentation.scrollhelp.site/developer-docs/setting-up-your-local-frontend-environment#Settingupyourlocalfrontendenvironment-Step4:Backendandinternaltoolssetup) the link for [Local test account login instructions](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/accessing-staging.md) goes to instructions on how to login on staging, not locally. 

### Which type of team are you on? (Platform team, VFS team, or Leadership)
Platform

**Comment by johnny-jesensky-adhoc** [comment]
Hi @ataker, thank you for submitting this request. the Platform is taking a look for next steps. We will be sure to provide updates to this within the ticket.

**Comment by johnny-jesensky-adhoc** [comment]
@ataker, This page has been updated and is now live on the Platform Website. Thanks again for flagging this, and for working with us to get this fixed!

FYI @BSmolensky
