### ISSUE TITLE
Design Intent - IA Feedback - Iterate Innovate Run, Performance Dashboard

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#69418]
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- I believe I speak for the entire Governance Team when I saw we are **so excited** that y'all are here and working to bring projects into better alignment with our current standards. We appreciate you!
- The Sitewide Facilities team is [working on a police data dashboard project](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65082), and it might be helpful to touch base with them about how they are using design system components for this build. 

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- **Must**: Update the page `<title>` tag to match our [formatting standards for page titles](https://design.va.gov/content-style-guide/seo#title-tags). Typically for unauthenticated pages it's `Page H1` | Veterans Affairs.
- **Must**: Incorporate the [Breadcrumb component](https://design.va.gov/components/breadcrumbs) above the H1
- **Must**: Some `h3`'s and `h4`'s are in all caps. Please ensure heading text is not coded in all-caps - let css text-transform do the work.
![Screenshot 2023-11-07 at 4 21 59 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/755248/3b08b1af-31bf-42a0-9ad3-2f020cd5b395)

**Comment by raquelou** [comment]
@erinrwhite I want to verify that the breadcrumb for the performance dashboard should say "Home > Performance Dashboard" even though it technically lives in the footer and not on the homepage, correct?

**Comment by mcommons10** [comment]
Feedback has been implemented, closing this ticket!
