### ISSUE TITLE
Team QA | Profile Hub | QA Testing

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#69415]
## Background
We need to run QA for the Hub and we'll use this ticket 

- [spreadsheet](https://docs.google.com/spreadsheets/d/1NfYZh4LFTVw8ZFbiv9AVkLipvxdzwwD7lKv3t7V8QMo/edit#gid=0)

## Acceptance Criteria 
- [x] qa has been completed and we've created and tickets needed to resolve QA bugs

**Comment by mtcA6** [comment]
@pamela-drouin @tpharrison @adamwhitlock1 @ACParker89 @andaleliz have any of you ever had success logging in with a MHV account (via CAG)? I'm trying to complete test 14c to log in w a MHV user and having issues getting in. 

cc: @Samara-Strauss

**Comment by pamela-drouin** [comment]
@mtcA6 I have not attempted to do so!

**Comment by andaleliz** [comment]
@mtcA6 yes - MHVZACK is the only user that works for me.  Make sure you use the link at the top of [this page](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mhv-lower-env-test-accounts.md), and pay attention to the `mhv-syst` part of the URL. I think sometimes when you click the login button, it takes you to a prod page, and you have to manually point it back to the staging environ before you sign in.

If that ends up working with you, it might be helpful to add those steps to the doc.

**Comment by mtcA6** [comment]
@andaleliz that worked! I was being very unscientific and was randomly selecting different users and those just weren't working they kept having a 2fa error or some random redirect errors. Thanks!!!!

**Comment by andaleliz** [comment]
@mtcA6 yay, I'm glad that worked for you!

>those links the breadcrumbs don't update.

Do you mean that when a person lands on one of those pages, the breadcrumbs _don't_ include profile or where they actually just came from? If so, then that is to be expected. The breadcrumbs on our site aren't actually "breadcrumbs" that could help you find your way back. They're more like a...family tree to show you how the page you're on is related to it's parents :)
