### ISSUE TITLE
Vets-api terminal access for Corey Ferris

### ISSUE THREAD

**Issue by cferris32** [department-of-veterans-affairs/va.gov-team#69420]
### Your Name

Corey Ferris

### Your GitHub handle (terminal access is managed through GitHub)

cferris32

### Your dsvagovcloud AWS user name (if applicable)

Corey.Ferris

### Team, Role, and Company of the target individual

Appointments Team, Backend Software Engineer, Ad Hoc LLC

### Product Manager (PM) name and email

Jeff Roof - jeff.roof@adhocteam.us

### Product Owner (PO) name and email

Kay Lawyer - katherine.lawyer@va.gov

### COR Name (leave "None" if you listed an AWS user name above)

None

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

None

### Please confirm if you are on the VFS Team Roster or Platform Team Roster

- [X] [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Please confirm E-QIP Transmittal/Adjudication. This could be a screenshot of your Transmittal/Adjudication email, a link to another request where you've submitted this proof (i.e. AWS/SOCKS), etc.

- [X] I have attached proof that I have either transmitted my E-QIP survey or previously received a favorable decision (by including in "Additional Notes" section below)

### ArgoCD terminal access requested for the following environments

- [ ] dev
- [X] staging
- [ ] sandbox
- [ ] production (if requesting, justify prod access in 'Additional Notes' section)

### Additional Notes

Attached is a screenshot of the email I received confirming the completion and favorable determination of my E-QIP process.
<img width="1461" alt="Screenshot 2023-11-07 at 4 09 54 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/14044335/4d599410-c0d6-414a-8990-c06d8fcfedb9">

### Additional resources for Support Engineer

- [ ] For users on a VFS team but not in the VFS Team Roster, they must start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] Instructions for handling requests [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access) - Support Only

**Comment by IsaiahMW1** [comment]
Found in VFS Team Roster

**Comment by IsaiahMW1** [comment]
@cferris32 Access has been granted to the staging environments.

Here's some additional documentation for the [Vets API on EKS]
(https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-TerminalAccess)
