### ISSUE TITLE
Set up VRO locally

### ISSUE THREAD

**Issue by gabezurita** [department-of-veterans-affairs/va.gov-team#69427]
Set up VRO locally, focusing on the aspects relevant to our usage.

For more details, see: https://github.com/department-of-veterans-affairs/abd-vro/wiki/Local-Setup

**Comment by williamphelps13** [comment]
Blocker was not having this in my zsh shell: export DOCKER_DEFAULT_PLATFORM=linux/amd64

[Private Zenhub Image]z(https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXdWQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e84f31b0965ed2fb806a6c50b9ea5e091159e409/Screenshot%202023-11-28%20at%203.19.40%E2%80%AFPM.png)

Key commands: 
- source scripts/bip-service.sh
- ./gradlew svc-bip-api:integrationTest
