### ISSUE TITLE
Design Intent - IA Feedback - Disability Benefits Experience Team 1, 21-526EZ, New Military Service History Fields and Question

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#69423]
## VFS actions
- [x] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [x] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [x] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- This revised flow makes sense - thanks for bringing it to us.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- **Consider:** the wording of a couple of labels on the [Reserves unit screen](https://www.sketch.com/s/ccdb20f1-b049-4f6c-8ac7-0a64f6dd9757/a/uuid/80E3250E-E47D-435A-8A9D-61E64FFAE292) could potentially be a blocker for folks. Is it "Current or last assigned name of unit" or is it "Name of current or last assigned unit"?
![Screenshot 2023-11-07 at 4 33 12 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/755248/2e1f832c-cce3-4483-94b6-9341fcd06e32)

- **Consider:** On the [Homelessness question](https://www.sketch.com/s/ccdb20f1-b049-4f6c-8ac7-0a64f6dd9757/a/uuid/39A8A905-388F-400A-8AC8-56F6265D84F4), consider including a "Why is this important?" additional info component, similar to the component on the question about terminal illness. I recognize this is out of the team's scope but wanted to log it as a suggestion.
![Screenshot 2023-11-07 at 4 30 08 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/755248/e2af32ff-9a4b-4bee-baf5-be75ead351e6)

**Comment by Kate-allbee** [comment]
Getting confirmation on the copy note above. 

As per the homelessness note, this is a great flag! and also, we talked about this being out of scope for this particular ticket, but would love to revisit in the future.

**Comment by Kate-allbee** [comment]
[Confirmed](https://dsva.slack.com/archives/C053UDWMH7U/p1701981277420909) we're going with 
Name of current or last assigned unit
and also changing copy in phone number to be similar "Phone number of current or last assigned unit"

**Comment by Kate-allbee** [comment]
Updated the mocks to have that corrected copy for those fields.
Updated the links in the collab cycle tickets to reflect the correct (working) sketch link.
