### ISSUE TITLE
[BE, Data] 10-10EZ - Monitoring & Alerts: Reduce 10-10EZ retries and add an alert

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#69422]
## Background
The 10-10EZ follows the basic [retries timetable](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/engineering/Retries%20table.md), allowing up to 24 retries, however the timeframe spans over 20 days, which is too long before we would start triaging the root cause of submission failures.  

As part of the efforts to improve monitoring and alerts across VA.gov and specifically with the 10-10EZ Health Care application, we want to reduce our response time to application submissions that fail all retries.  We also need to add an alert before all the retries fail, so that we might start our investigations earlier.

## Tasks
- [x] Reduce the 10-10EZ retries from a total of 24 to a total of 14
- [x] Add an alert that sends a message to our #health-tools-1010-apm channel, when a submission reaches 10 retries without success

## Acceptance Criteria
- The 10-10EZ application will have monitoring and alerts to notify the team earlier of total retry submission failures

**Comment by emily-brown34** [comment]
waiting on PR (24 hour window)
