### ISSUE TITLE
Display the Clinic Location information to the user on the appointment details page

### ISSUE THREAD

**Issue by JRRoof** [department-of-veterans-affairs/va.gov-team#69444]
## Description
On the appointment details page, the veteran does not currently see the clinic location {physicalLocation} only clinic name.
After the veteran books an appointment, the veteran will see the clinic location {physicalLocation} on any of the appointment detail pages, if the data exists.  Update the page content on all versions of the appointment details page with the clinic location information {physicalLocation}.

NOTE: This feature needs to be controlled by the `va_online_scheduling_physical_location` feature toggle

---

## Acceptance Criteria
Background: the `va_online_scheduling_physical_location` toggle is on

Given a veteran direct schedules a new appointment of type VA In-person, Claim Exam, or VA VVC at VA
When they view the confirmation details
Then the confirmation page includes the location of the clinic
And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/appointment-details.md#va-in-person---confirmed) 
And page design matches the [design spec](https://www.figma.com/file/lEEJG6Hqkfw4f1dMA5cDAs/Add-clinic-location-%7C-Appointments-FE?type=design&node-id=408%3A7150&mode=design&t=l69MBgOqpjR2oAxF-1)

Given a veteran is viewing their upcoming appointments of type VA In-person, Claim Exam, or VA VVC at VA
When they view the details of an upcoming appointment
Then the appointment details page will include the location of the clinic
And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/appointment-details.md#va-in-person---upcoming)
And page design matches the [design spec](https://www.figma.com/file/lEEJG6Hqkfw4f1dMA5cDAs/Add-clinic-location-%7C-Appointments-FE?type=design&node-id=408%3A7147&mode=design&t=l69MBgOqpjR2oAxF-1)

Given a veteran is viewing their past appointments of type VA In-person, Claim Exam, or VA VVC at VA
When they view the details of a past appointment
Then the appointment details page will include the location of the clinic
And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/appointment-details.md#va-in-person---past)
And page design matches the [design spec](https://www.figma.com/file/lEEJG6Hqkfw4f1dMA5cDAs/Add-clinic-location-%7C-Appointments-FE?type=design&node-id=408%3A7148&mode=design&t=l69MBgOqpjR2oAxF-1)

Given a veteran is viewing their canceled appointments of type VA In-person, Claim Exam, or VA VVC at VA
When they view the details of a canceled appointment
Then the appointment details page will include the location of the clinic
And page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/appointment-details.md#va-in-person---canceled)
And page design matches the [design spec](https://www.figma.com/file/lEEJG6Hqkfw4f1dMA5cDAs/Add-clinic-location-%7C-Appointments-FE?type=design&node-id=408%3A7149&mode=design&t=l69MBgOqpjR2oAxF-1)

## Design Assets
[Design File](https://www.figma.com/file/lEEJG6Hqkfw4f1dMA5cDAs/Add-clinic-location-%7C-Appointments-FE?type=design&node-id=408%3A8530&mode=design&t=l69MBgOqpjR2oAxF-1)
Page structure guide [Copy Doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/appointment-details.md)

## Example Designs
[Appointment Confirmation](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3l5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--07f010d2e3057c1f531479d2d7693d4a03c4f7c7/image.png)

[Upcoming Appointment](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFN5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0684dad6420edf684ba48246a2908ca22a2ab7cb/image.png)

[Past Appointment](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGF5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0cf0a0564c6b48f3a7034507b797951e65c59435/image.png)

[Canceled Appointment](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGV5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3205174668f8d884a422098e38e43fc0917a9bc3/image.png)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by JRRoof** [comment]
Replaces Github issue [#32593](https://github.com/department-of-veterans-affairs/va.gov-team/issues/32593)

**Comment by JRRoof** [comment]
Blocked until Github issue [#69402](https://github.com/department-of-veterans-affairs/va.gov-team/issues/69402) is completed.

**Comment by Cieramaddox** [comment]
@ldelacosta @JRRoof Design links have been updated.

**Comment by jenniemc** [comment]
@JRRoof @ldelacosta @simiadebowale , 

This is ready for validation. Please note at this time detailed phone appt also displays the physical location. There is currently a pull request in the works to [hide physical location for phone appt](https://github.com/department-of-veterans-affairs/vets-website/pull/28404). Will update you all once it is pushed into staging. 

To begin validation, enable the toggle flag `va_online_scheduling_physical_location` in staging for Judy Morrison. Login as judy morrison in staging:
	•	Upcoming detailed appointment May 16, Mental Health id: 206603
	•	Cancelled detailed January 30 2024 appointment id: 201354
	•	Past detailed February 2, 2024 7pm MT appointment id: 206552
	•	Phone details , cancelled 3/11/24 11:AM PHONE appointment id: 167525

To create a direct schedule appointment:
	1	select Audiology
	2	Facility: Dayton VMAC
	3	Clinic: AUDIOLOGY CONSULTANT-2 (AM)

**Comment by jenniemc** [comment]
@JRRoof @ldelacosta @simiadebowale ,

The ticket to hide physical location for phone appointment is merged into staging. To validate, please login as judy morrison. In the upcoming appointments list, click details link for 3/11/24 11AM - Cancelled phone appointment id: 167525

**Comment by ldelacosta** [comment]
Validated the changes in staging. UX team will review the work. 

<img width="1107" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3ZDQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1891f96edc0ac9b330c62a1b0398aa8b3e9d97b6/Screenshot%202024-03-07%20at%204.11.47%20PM.png" alt="Screenshot 2024-03-07 at 4.11.47 PM.png" />

Phone appointments has clinic location suppressed: 
<img width="1026" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1BDQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--30802e6ace1f072fec559aae91516526b5d5692c/Screenshot%202024-03-07%20at%204.23.16%20PM.png" alt="Screenshot 2024-03-07 at 4.23.16 PM.png" />

**Comment by Cieramaddox** [comment]
UX has validated this ticket and its good to go! @ldelacosta

**Comment by outerpress** [comment]
@Cieramaddox @ldelacosta this is looking good to me!

**Comment by ldelacosta** [comment]
There are no issues to report. We will send out a release note for this work before turning on the feature toggle. cc: @JRRoof
