### ISSUE TITLE
CF: Update prototype based on content refinements

### ISSUE THREAD

**Issue by ccruzgra** [department-of-veterans-affairs/va.gov-team#6944]

**Comment by ccruzgra** [comment]
Content was updated in existing prototype: https://bahdigital.invisionapp.com/share/N5IAD8MHTC9

@amyknox if the updates check out, this story can be closed.

**Comment by ccruzgra** [comment]
Once I get confirmation that the prototype updates are good to go, I will create a duplicate prototype if it's needed for external stakeholders.

**Comment by amyknox** [comment]
@ccruzgra - is this wrapped up? If so, feel free to close this story.
