### ISSUE TITLE
Flipper UI access for Micah Frazier

### ISSUE THREAD

**Issue by micahaspyr** [department-of-veterans-affairs/va.gov-team#69443]
### Your Name

Micah Frazier

### Your GitHub handle (Flipper UI access is managed through GitHub)

@micahaspyr

### Team, Role, and Company of the target individual

Team Umbrella, Full Stack Engineer at Oddball

### Please confirm if you are on Atlas, Platform Team Roster or are a Federal User

- [X] [Atlas](https://dev.va.gov/atlas)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [X] Lesser Environments (Dev/Staging/Sandbox)
- [X] Production (if requesting, justify prod access below)

### Reason for Production Access (If requested)

I need access to roll out features slowly on va.gov via vets-website and vets-api

**Comment by bdech** [comment]
Confirmed user in Atlas.
