### ISSUE TITLE
Design Intent - Content - Collaboration Cycle for [Iterate Innovate Run, Performance Dashboard, NA] #67917

### ISSUE THREAD

**Issue by rferguson13** [department-of-veterans-affairs/va.gov-team#69442]
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts
Hello! Normally, content doesn’t do a Design Intent review, but we decided to make an exception in this case since this page hasn't gone through the Collaboration Cycle. I recommend working with CAIA to update and develop content for this page. You can follow these steps to submit an intake request: [Sitewide Content, Accessibility, and Information Architecture (CAIA) intake request](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/sitewide-content-and-ia-intake-request). 

A couple of things to keep in mind when reading this feedback:
- I approached this review as if this was a regular VFS page. I know the audience for this dashboard is OCTO, but since any user can see it, I’ve reviewed it as if it’s a more traditional veteran-facing page.
- I approached this review as if it’s a midpoint review, since this page did not go through the Collaboration Cycle in the past. It looks like there’s a lot of changes to make, but I think some small changes applied across the page will make a big difference. Not all of this content needs to be changed by the time you do a midpoint review, but it should be addressed by the time you do a staging review. If any of my feedback is out of scope, please tell me.

### Must
- Throughout the page, the user finds the term “logged in.” According to the [Style Guide](https://design.va.gov/content-style-guide/word-list#s) (under “S” in the word list), we must use the term “sign in” (or “signed in”). Please revise all instances of “logged in” to be “signed in” to fit with the Style Guide. 
- Throughout the page, the user encounters inconsistent capitalization (e.g. Health Care vs. health care, etc.) and capitalization use that differs with the Style Guide. Please review the [capitalization rules](https://design.va.gov/content-style-guide/capitalization) in the Style Guide and revise the page accordingly. When in doubt, use sentence capitalization as the standard (including headers). If you’re unsure about a specific word or service, please refer to the [word list](https://design.va.gov/content-style-guide/word-list#v).
-  “VA.gov at a glance” metrics definitions - When the user reads the “How is this measured?” dropdown under the “VA.gov at a glance” section, they find the following definition: “Logged In Users: The total count of all users who have logged in to VA.gov over the last 12 months, using ID.me or MyHealtheVet or DS Logon.” This sentence doesn’t use serial commas correctly. According to the Style Guide, writers should use [serial (Oxford) commas when making a list.](https://design.va.gov/content-style-guide/punctuation) Please revise this sentence using serial commas.
- "VA.gov at a glance" and "VA.gov service" metrics definitions - When the user reads the “How is this measured?” dropdown under the "VA.gov at a glance" and "VA.gov service" sections, they find the following definition: “User Satisfaction: A monthly average user satisfaction score based on the feedback responses from users within the various service lines on VA.gov.” This sentence is not written in [plain language](https://design.va.gov/content-style-guide/plain-language/), which is against the Style Guide. Please revise so the sentence is written clearly in plain language. There are several ways that the writer could rewrite this definition. For example, the definition could be: “User satisfaction: An average monthly score that measures satisfaction based on a user’s feedback for different VA.gov services.”
- "VA.gov at a glance" metrics definitions - When the user reads the “How is this measured?” dropdown under the "VA.gov at a glance" section, they find the following definition: “Successful transactions: The total count…health appointments scheduled, claims status checked, benefit…” The way that “claim status check” is worded is grammatically incorrect and inconsistent with the other items on the list. Please revise for consistency and grammar, e.g. “claim statuses checked.”
- "VA.gov service" metrics definitions - When the user reads the “How is this measured?” dropdown under the "VA.gov service" section, they find the following definition: “Total Users: The count of total users to the various service lines such as Health Care, Education, Pension, etc. on VA.gov for the last 30 days.” This definition isn’t written in [plain language](https://design.va.gov/content-style-guide/plain-language/) and doesn’t use correct [capitalization](https://design.va.gov/content-style-guide/capitalization). Please revise so the definition is written in plain language with correct capitalization.
- "VA.gov service" dashboards - In the "VA.gov service" section, the user finds mini dashboards that have the phrase: “[Percentage change] compared to prior year period.” This sentence is not written in [plain language](https://design.va.gov/content-style-guide/plain-language/), which is against the Style Guide. Please revise so the sentence is written clearly in plain language. There are several ways the writer could do this. For example, the sentence could be: “[Percent change] compared to last year.”
- "VA.gov service" dashboards - In the "VA.gov service" section, the user finds mini dashboards that have the phrase: “Usage data from previous 30 days.” This sentence is not written in [plain language](https://design.va.gov/content-style-guide/plain-language/), which is against the Style Guide. Please revise so the sentence is written clearly in plain language. There are several ways the writer could do this. For example, the sentence could be: “Data is from the previous 30 days.”
### Should
- Under each of the page's headings, the user finds the question: “How is this measured?” which leads a dropdown filled with term definitions. To keep this consistent with other dropdown titles used throughout VA.gov, please revise to make the text a statement. There are many ways the writer could do this. For example, they could write: “How this is measured.”
### Consider
- Throughout the page, the user encounters the word “transactions'' multiple times. While the definition is given, it’s hidden in a dropdown. I would consider a better word to use to capture this data point or change the UI to clearly direct the user to the definition.
- "VA.gov at a glance" table - When the user views the table in the “VA.gov at a glance” section, the “User satisfaction” shows a percentage from “last month,” but the other two statistics cover the last 12 months. Consider revising this so the three statistics are consistent in their timeframe.
- “Successful transaction” vs. “transaction” - In each dropdown, the user finds definitions for “successful transactions” and “transactions.” How are “successful transactions” different from “transactions”? The current definitions for each term aren’t significantly different. Please revise so these terms are clearer to the user. There are many ways that the writer could do this. For example, the definitions in each dropdown could be the same. Or, if there is a major difference between a “successful transaction” and a “transaction,” each definition should be distinct and explain the difference. 
## Notes
Thank you for the opportunity to review your project. Please submit an intake request to work with CAIA to maximize the effectiveness of your efforts. If you have any questions for me, please let me know.

**Comment by raquelou** [comment]
Suggested "must" changes have been implemented to the performance dashboard. Some of the consider suggestions will be visited in the design rewrite.
