### ISSUE TITLE
[Accessibility] Review stand alone login page for screen reader usability

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#6945]
Talked to VSP accessibility team today and learned there are opportunities to improve the standalone login page re how it will work with screen readers. 

- [ ] Schedule meeting with VSP accessibility team/async wireframe review (met 3/17) 

Jennifer is the Accessibility Specialist working on this. 
- [ ] document recommendations for the SSO page
- [ ] share with Trevor to review

Link to stand-alone sign-in page on staging: https://staging.va.gov/sign-in/

**Comment by bridgethapner** [comment]
Next steps: Confirming how VSP Accessibility Specialists bill to work on this effort

**Comment by jenstrickland** [comment]
@bridgethapner Here's the a11y specs for the sign-in page, per our conversation. [20200405-SSO-specs.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/4435266/20200405-SSO-specs.pdf)

**Comment by bridgethapner** [comment]
Thank you @jenstrickland! I appreciate your help and guidance. 

I have a potentially silly question - In the areas where you specify an < h2 > should be used, does that mean the < h2 > style from the VA.gov design library **must** be used? Or could we find a way to have a different type style be read as < h2 > on this page only? cc @hinzed1127 in case you can provide any insight here. 

I ask because the < h2 > stye is big and looks visually unbalanced on "Sign in with an existing account" and "Don't have those accounts?". I don't think it's a big deal but if possible I'd like to make these two lines smaller if and only if we can do that and not compromise screen reader usability. 

For reference, here is the new page using the correct type styles: 

![#6420 - Standalone signin page Copy@1x.png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/aae1405c-b0bf-43f3-b190-0ffdbaec01ab)

**Comment by jenstrickland** [comment]
Not silly at all. There are [utility classes in the design system](https://design.va.gov/design/typography#headings) that can make headings look like other styles. Look at the font size utility link. So, the designer would say, this is an h2 with h3 styling, for example.

**Comment by bridgethapner** [comment]
@jenstrickland Ah, interesting! Thank you so much! 

It looks like we can keep the visual design as-is and implement the changes through front-end work. @hinzed1127 I opened #7767 to track the front-end work. I will leave this ticket open for now in case you have any questions for Jen.

**Comment by marriej** [comment]
See #7767 for additional work.
