### ISSUE TITLE
[Bug] [Tech Discovery] User says appeal is with judge, but CST says it isn't

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#69460]
## Situation

User claims their appeal is with a judge and it has been verified, but CST says it's not with a judge.

We need to identify the field in question producing that info to the vet. 

## Open questions

- [x] What are the specific requests to CaseFlow for how to investigate what is happening with this user?

**Comment by jerekshoe** [comment]
I confirmed that their appeal updated to show that it was with a judge shortly after they reported their issue to the call center. I'm thinking we can close this one?

**Comment by jerekshoe** [comment]
@jacobworrell do you think we can close this?
