### ISSUE TITLE
Content edit: COVID-19 public health page and media page 

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#6946]
## User story

As a Veteran, I want to know how VA is responding to coronavirus and get answers to my questions. 
As a member of the media, I want to how about VA cases and how VA is tracking and communicating them. 

Page in question
Peggy to provide content support and review for this page that is being redesigned: 

https://www.publichealth.va.gov/n-coronavirus/?utm_source=Homepage&utm_campaign=Coronavirus

**Comment by peggygannon** [comment]
@lalexanderson-dsva @artsymartha68 

Here are the first drafts of content recommendations for: 

**Public Health front door page content:**
[https://app.zenhub.com/files/133843125/2403e31f-fa5f-4a14-9e14-04c66863427e/download](https://app.zenhub.com/files/133843125/2403e31f-fa5f-4a14-9e14-04c66863427e/download)



 **Public Health media page:**
[https://app.zenhub.com/files/133843125/82a46b95-9014-468f-817f-f1947e71bd49/download](https://app.zenhub.com/files/133843125/82a46b95-9014-468f-817f-f1947e71bd49/download)

cc @meganhkelley

**Comment by artsymartha68** [comment]
Latest visual design comps (awaiting confirmation from TeamSite experts to see if we can style the large CTA action links. We definitely prefer to have actual text instead of 'pictures of text'.

[CoronavirusUpdatedContentv5.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/4355798/CoronavirusUpdatedContentv5.pdf)

[CoronavirusMediaUpdatedContentv2.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/4355805/CoronavirusMediaUpdatedContentv2.pdf)

**Comment by artsymartha68** [comment]
New main page comp with TeamSite button styling from Jenny 
[CoronavirusUpdatedContentv6.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/4356099/CoronavirusUpdatedContentv6.pdf)

**Comment by peggygannon** [comment]
Thanks, @artsymartha68 the layout is looking good. And I think this page is ready for routing! 

Sorry, but I have two more edits, (it's really hard to edit via slack). these can wait until you make other updates.  

1. Can we remove VA from this sentence: 
To learn more about our efforts, what to do if you have a VA medical appointment, or how
to contact your health care provider, please read our COVID-19 ~VA~ FAQs for Veterans. 

2. Can we remove VA from this media button language

Go to ~VA~ COVID-19 media page

**Comment by artsymartha68** [comment]
No problem @peggygannon - I'm a stickler too :)
Here is the update with your edits.
[CoronavirusUpdatedContentv7.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/4356296/CoronavirusUpdatedContentv7.pdf)

**Comment by peggygannon** [comment]
Thank you, @artsymartha68 ! updates look good.
