### ISSUE TITLE
Military Info Testing

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#69473]
This ticket is for testing https://github.com/department-of-veterans-affairs/vets-api/pull/14327
Add testing notes to this issue.

Steps to test with a mock user in staging:
1. Log onto staging as a [mock user](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv) 
2. Take the ICN for that user, and in the rails console in Argo staging do: `UserAccount.find_by(icn: <icn>).user_verifications.where.not(idme_uuid: nil).last.idme_uuid`
3. Take that idme_uuid, and do: `User.find(<idme_uuid>)` and you’ll have a user object you can interact with.

You can also NOT use a user and check attributes using this: `FormMilitaryInformation.new`.

### Validation
- [ ] Look over [Confluence doc](https://vfs.atlassian.net/wiki/spaces/~121859534/pages/2834366470/Ticket+69473) and make sure things look good. 
- [ ] Determine if there's anything that was missed in testing.

**Comment by rmtolmach** [comment]
I'm adding my findings to Confluence. The large blocks of text were easier to format there.
https://vfs.atlassian.net/wiki/spaces/~121859534/pages/2834366470/Ticket+69473

**Comment by laineymajor** [comment]
looking into 1 final error

**Comment by rmtolmach** [comment]
The error ended up being related to Flipper (we think). And the flipper ended up being unnecessary, so we removed it in https://github.com/department-of-veterans-affairs/vets-api/pull/14537.

Testing notes are in the confluence ticket linked in my previous comment.
