### ISSUE TITLE
Flipper UI access for [Tai Wilkin]

### ISSUE THREAD

**Issue by TaiWilkin** [department-of-veterans-affairs/va.gov-team#69476]
### Your Name

Tai Wilkin

### Your GitHub handle (Flipper UI access is managed through GitHub)

TaiWilkin

### Team, Role, and Company of the target individual

Pensions, Engineer, Coforma

### Please confirm if you are on Atlas, Platform Team Roster or are a Federal User

- [X] [Atlas](https://dev.va.gov/atlas)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [X] Lesser Environments (Dev/Staging/Sandbox)
- [ ] Production (if requesting, justify prod access below)

**Comment by bdech** [comment]
confirmed in VFS Team Roster.

**Comment by bdech** [comment]
@TaiWilkin You've been granted access to lower environments. Have a great day!
