### ISSUE TITLE
Content audit for education hub migration

### ISSUE THREAD

**Issue by strelichl** [department-of-veterans-affairs/va.gov-team#69485]
## Description

We're migrating Veteran-facing content to VA.gov from this legacy education service hub: www.benefits.va.gov/gibill/

The first phase of this work is to complete an audit. We're using this [audit spreadsheet](https://dvagov-my.sharepoint.com/:x:/g/personal/danielle_thierry_va_gov/ETgKoe5t2QhDnCv3PQxaL-0BA0T8IHnkM1uXV1zawD-5mA?e=uM0nDb) to do so.

### Step 1: Prepare
- [x] AP: Use Semrush to generate a list of unique URLs within the education service hub on the legacy site
- [x] AP: Place the list of unique URLs in column B of the audit spreadsheet

### Step 2: Audit
- [x] DB: Complete column A in the audit spreadsheet
- [x] DB: Complete columns C-H in the audit spreadsheet
- [x] AP: Move 404, non-action, and redirect URLs into their own tabs in the audit spreadsheet

### Step 3: Synthesize
- [x] AP: Complete column I in the audit spreadsheet
- [x] BP, DT: Answer questions in column I in the audit spreadsheet
- [x] DB: Complete columns J-M in the audit spreadsheet
- [x] AP: Complete columns V-AB in the audit spreadsheet

### Step 4: Understand
- [x] CAIA: Host audit kickoff meeting with stakeholders
- [x] Stakeholders: Complete columns P-T in the audit spreadsheet

### Step 5: Finalize
- [x] AP, DB: Complete columns N-O in the audit spreadsheet
- [x] BP, DT: Review columns N-O in the audit spreadsheet
- [x] Stakeholders: Review columns N-O in the audit spreadsheet

## Acceptance Criteria
- [x] The audit is complete
- [x] New tickets have been created to actualize our migration recommendations

**Comment by aprocik1** [comment]
Hey @d-beyer! I used SEMrush to crawl the [education service hub on the legacy site](www.benefits.va.gov/gibill/) to generate a full list of URLs. Then I did some Excel magic to generate a unique list of URLs, and copied them into our [content audit spreadsheet](https://dvagov-my.sharepoint.com/:x:/g/personal/danielle_thierry_va_gov/ETgKoe5t2QhDnCv3PQxaL-0BA0T8IHnkM1uXV1zawD-5mA?e=F3gpvi), starting in row 6.

There are 237 unique URLs that need to be audited for this migration project. You should have everything you need to get started, but feel free to follow up with questions. Thanks for your collaboration on this!

**Comment by d-beyer** [comment]
Update: @aprocik1 and I finished reviewing the pages, inputting basic information about them, organizing the sheet, and coming up with questions for Beth and Danielle before sharing the audit with stakeholders.

**Comment by aprocik1** [comment]
Add to the sprint tracker
