### ISSUE TITLE
Copy of UX Spike: Asynchronous ITF Creation

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#69490]
During a recent volume increase of Veterans attempting to submit their application before the PACT Act deadline it was discovered that the ITF service was overwhelmed and blocking Veterans from continuing with their form.

As part of mitigating this, it has been determined that we want to change the ITF creation to be asynchronous. I.e. if the Veteran gets to the point of the application where an ITF would be created, but the ITF service is unavailable, we should allow the user to continue but queue the ITF creation date-time and backfill as needed.

Scenarios:

Axioms:
1. Never block start of filling out a form (for technical or UX reasons)
2. Never stop a user from submitting a form (for technical or UX reasons)
3. What information does the Veteran need around ITF and when to ensure they don't stop themselves at point due to ITF confusion

Acceptance criteria:

- [x] Diagram out current state for ITF communication at beginning, middle, end
- [x] 2. Capture ideas from discussions and slack channels as stickies 
- [x] 3. Mock up different language options depending if ITF is down or available

    a. Simplest: never show actual ITF date and or current ITF 
    b. Slightly more complex: Show iTF date or current itf if available or use pattern a if not available
         1. does this include the link pattern?
    c. most complex: Show ITF date or current ITF regardless of availability 

note: is there ever a situation where we would know if there isn't a current itf and were comfortable telling them we created a new one.

**Comment by nnicholas7** [comment]
11/8/23: Worked with Julie to create an ITF Async Flow.  This flow maps out three options for ITF Async creation and also includes some lo-fi mock-ups and messaging.  Met with Austin and Sam to chat about flow and make sure we are on the same page about the flow.
 ITF Async Flow- https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1686768383603/3f4415dd2ddb71bbd104ebefd92a2c7b553ad792?wid=0-1698765294378 (Mural)

Next steps: Meet with Shannon to get her feedback on the flow options.

**Comment by nnicholas7** [comment]
Update: Attend CAIA Office Hours on 12/12.  I was able to get feedback on the header.  CAIA suggested changing the header of the message to " We're checking or We're confirming...".  CAIA need more time to think about language and tone being used in 1st paragraph of the design.  They (Lily S, Katherine Fung, or Laura) will get back to us on Wednesday with feedback for the whole message.

**Comment by austinjprice** [comment]
@austinjprice to move content related comments to content ticket, then close out since we have landed on an approved approcha

**Comment by nnicholas7** [comment]
Update: Attended CAIA Office Hours and was able to get the following message for the ITF Async Message:
[H2] We're confirming your Intent to File

When you start a claim for disability benefits online, we record your Intent to File. This sets a potential start date for your benefits. Your Intent to File date resets after one year.

**If you already have an Intent to File**, we'll continue to hold that date as the potential start date for your benefits.

**If you don't already have an Intent to File**, we'll use today as the potential start date for your benefits.

You don't need to do anything else to notify us of your Intent to File. You can continue to file your claim.

The message has been updated in the Sketch file and awaiting async review from Shanoon.

Sketch file: https://sketch.com/s/c0480bf8-3e77-43dc-a097-65a0841bb418
