### ISSUE TITLE
Rewritten legacy content + IA Support

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/va.gov-team#695]

**Comment by peggygannon** [comment]
Some issues that Peggy is helping Jen Lee close out with the website rewriting and legacy editing work: 

- [ ] https://github.com/department-of-veterans-affairs/vets.gov-team/issues/16095#issuecomment-511583623

- [ ] https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19363#issuecomment-514817358

- [ ] https://github.com/department-of-veterans-affairs/vets.gov-team/issues/15513#event-2493776873

- [ ] https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19080

**Comment by peggygannon** [comment]
Closing. All the above issues have been resolved/closed.
