### ISSUE TITLE
Revise PACT Act wizard content based on usability testing

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#69514]
Danielle to review results of usability testing and update content as needed.

**Comment by DanielleThierryUSDSVA** [comment]
@jilladams Here's an issue to add as a blocker. I'm hoping to get to this before I head out to the offsite!

**Comment by FranECross** [comment]
@DanielleThierryUSDSVA I think you've completed all tasks on this ticket? If so, I'll go ahead and close. Thanks!

**Comment by FranECross** [comment]
Content updates provided by Danielle and implemented. Another ticket will be created (or exists) for any stakeholder feedback.
