### ISSUE TITLE
Create list of all Pension 527 claims

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#69519]
## Issue Description
More info on this slack thread: https://dsva.slack.com/archives/C05MS96P6P2/p1699464738020539

We need to pull a list of all Pension 527 claims,
so that VBA stakeholders can compare to the number of claims they've actually received,
so that they can gauge how many claims have been "lost"

---
## Tasks
- [x] Create a list of all Pension 527 claims. Criteria should include:
- Submission Date
- VA.gov Saved Claim ID
- Veteran Participant ID
- Central Mail Submission ID

- [x] Provide list to OCTO (Emily Theis)

**Script already created by Thomas to do this:** https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/benefits/scripts/pensions/pensions_all_claims.rb

## Acceptance Criteria
- We will have pulled a list of all Pension 527 form claim submissions and provided to OCTO

**Comment by tblackwe** [comment]
script created https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/benefits/scripts/pensions/pensions_all_claims.rb
