### ISSUE TITLE
Adding Daniel Miller to DSVA Slack

### ISSUE THREAD

**Issue by Dottifacilities** [department-of-veterans-affairs/va.gov-team#69520]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

Please add daniel.miller@agile6.com as a full member.

Daniel is joining the Authenticated Experience MyVA team as a full stack developer. They will need access to, and the ability to communicate within, many of the DSVA slack channels where development teams collaborate over the VA ecosystem.

**Comment by KevinMHoffmanUSDS** [comment]
His account has been reactivated. Thanks for tagging me in and for your patience around our offsite week.
