### ISSUE TITLE
Adding Prince Owusu to DSVA Slack

### ISSUE THREAD

**Issue by huggins-va** [department-of-veterans-affairs/va.gov-team#69535]
Please add Prince Owusu as a multi-channel user to the following channels:

- vaapi-platform
- team-honeybadgers-support 

Prince Owusu is new DevOps engineer and needs access to perform his job requirements

owusu_prince@bah.com

Thank you!

**Comment by LEHigley** [comment]
i couldn't add to either channel so just invited to general
