### ISSUE TITLE
Develop Training Materials for Benefits Hub

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#6954]
## User Story or Problem Statement

How might we develop training materials on the VA.gov benefits hub application that will prepare VEO call center agents to handle these technical issues?

## Goal

Training content that can be used to prepare VEO call center agents to handle VA.gov technical issues related to benefits applications.

## Acceptance Criteria
- [x] Create benefits hub application product guide
- [x] Create pre-needs application product guide

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by joanneesteban** [comment]
@clantosswett to QA the self-service guide and pass off to the team for self-service.

**Comment by clantosswett** [comment]
These are both complete! It's a miracle. They are attached here and will be sent to Todd Unger and team today:

[Benefit.Hubs.Product.Guide.4.29.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4551868/Benefit.Hubs.Product.Guide.4.29.docx)
[Benefit.Hubs.Product.Guide.4.29.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/4551870/Benefit.Hubs.Product.Guide.4.29.pdf)
[Pre-need.Burial.Application.Product.guide.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4551872/Pre-need.Burial.Application.Product.guide.docx)
[Pre-need.Burial.Application.Product.guide.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/4551880/Pre-need.Burial.Application.Product.guide.pdf)

**Comment by joanneesteban** [comment]
Sweet! Closing this issue. Thanks, Chante!
