### ISSUE TITLE
DR | Update Confirmation Page Design for all forms

### ISSUE THREAD

**Issue by rocio-desantiago** [department-of-veterans-affairs/va.gov-team#69550]
## Value Statement
**_As a_**  Designer/Engineer
**_I want to_** update the confirmation page for both 996 and 10182 so that it resembles the most recent and approved updates that 995 received.
**_So that_** the confirmation page for each form has all the updates/approval from the content team.

## Background Context

- Even though Code Climate's rating was addressed, other inconsistencies were caught due to 995 having recently had a makeover. Since 995 had a functional component and 996/10182 both had class components (an older way of writing components in React) Code climate didn't catch the other parts of the code with probable duplication.

## Out of scope

* Other apps/forms not in Decision Reviews

## Design Tasks

- [x] Update source of truth for 996/10182 to match 995's
    - [x] Higher-Level Review (996) [Source of truth](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/higher-level-review/design/content-source-of-truth.md#request-a-higher-level-review-18) | [Design](https://www.sketch.com/s/96420652-15b7-45bb-80c5-5454dcd4b3c6/a/JAympqk)
    - [x] Notice of Disagreement (10182) [Source of truth](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Notice-of-Disagreement/design/sourceofcontenttruth.md#request-a-board-appeal-19) | [Design](https://www.sketch.com/s/0424c51d-7818-43ea-8821-6de91eb7ab27/a/8V5Q2O8)
- [x] Update mock designs for 996/10182 to match 995's

## Engineering Tasks (Upon confirmation of Design tools updated)

- [ ] Functions moved into a existing components folder
- [ ] Unit tests updated (if applicable)
- [ ] Monitor Datadog and Sentry to confirm changes don't cause unforeseen errors in forms submission activity.

## Definition of Ready 

- [x] Have access to decision reviews folder (src/applications/appeals/{appName}/utils) in vets-website repository 
  > 995 - Supplemental Claims (src/applications/appeals/995/containers/ConfirmationPage.jsx)
  > 996 - Higher Lever Review (src/applications/appeals/996/containers/ConfirmationPage.jsx)
  > 10182 - Notice of Disagreement (Board Appeal) - (src/applications/appeals/10182/containers/ConfirmationPage.jsx)

## Definition of Done

- [ ] Functionality not changed
- [ ] Source of Truth updated
- [ ] Design mock ups updated
- [ ] Confirmation Pages for each form look identical (aside from the form names)

**Comment by eileen-coforma** [comment]
Ticket has been updated with designs and CSoT updates

**Comment by HeatherWidmont** [comment]
@rocio-desantiago to put this through the estimation process (using the new google sheets estimation) & will refine the ticket further before beginning work

**Comment by HeatherWidmont** [comment]
@rocio-desantiago is working on the test plan spreadsheet & will start this afterwards

**Comment by HeatherWidmont** [comment]
@rocio-desantiago to discuss further with @eileen-coforma in the parking lot today

**Comment by rocio-desantiago** [comment]
Confirmed that there are content updates underway. 
Some small changes to also include in this ticket:
* Update the button for supplemental claims to an action link per VA design standards/requirements.
* Update Note after action link to: ```Note: It may take 7 to 10 days for your Name of Form request to appear online.```
* Add Note to Supplemental Claims

**Comment by HeatherWidmont** [comment]
Rocio is updating one form at a time

**Comment by HeatherWidmont** [comment]
Rocio is working on one of the last forms, hoping to get it in by tomorrow. The last day of the code freeze is today, but its unclear what time it ends. We will look into if there is still a code freeze

**Comment by rocio-desantiago** [comment]
Per this updated [page](https://depo-platform-documentation.scrollhelp.site/developer-docs/deployment-policies) and this slack [thread](https://dsva.slack.com/archives/CE4304QPK/p1703174497369149), looks like release freeze dates ended yesterday. There was clarification on calling it a release freeze instead of a release freeze :D We're good now.

**Comment by HeatherWidmont** [comment]
Merged but not available in staging yet. If its available tomorrow the team will validate in the parking lot tomorrow

**Comment by Mottie** [comment]
Updates now available in staging.

**Comment by HeatherWidmont** [comment]
Validated in parking lot last week, closing.
