### ISSUE TITLE
Contact Center Review for Veteran Facing Forms, Form 21-0966 Intent to File a Claim

### ISSUE THREAD

**Issue by tbaker1026** [department-of-veterans-affairs/va.gov-team#69552]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
*Digitizing form 21-0966 Intent to File a Claim.*

### Launch Date
*Beginning of December*

### Version Number
*Please provide the version number of the guide and/or video.*

### Product Guide
[Product Guide](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/21-0966/Form%2021-0966%20Product%20Guide%20(1).docx)
[Workflow](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/21-0966/IntenttoFileWorkflow.png)

### Product Video
*Please provide product video link*

### Product Video Transcript
*Please provide product video transcript link*

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
On track for completion Monday, 11/13.

**Comment by starlow00** [comment]
Hi @tbaker1026. The draft looks good and is almost ready to submit to VEO for their review. I do have a couple of questions related to images, and they're marked by comments in the attached draft. Could you please take a look? A couple of image replacements are likely required.
[Form 21-0966 ITF Product Guide SRT 11132023 (1).docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHJVQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d660db4a5cf5f06050350aea05efc34de1614b86/Form%2021-0966%20ITF%20Product%20Guide%20SRT%2011132023%20%281%29.docx)

**Comment by tbaker1026** [comment]
@starlow00 Updated Screenshots 
https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/21-0966/Form%2021-0966%20ITF%20Product%20Guide%20SRT%2011132023%20(1)%20(1).docx

**Comment by starlow00** [comment]
Sent for VEO review.

**Comment by tbaker1026** [comment]
@starlow00 - we made a change to the Product Guide.  Now when the Veteran logs in, we check if they already have an intent on file, if yes we allow them to select another benefit to create another Intent.  See Veteran Story - only one that changed  
https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/21-0966/Form%2021-0966%20Product%20Guide%20(2).docx

**Comment by starlow00** [comment]
Thanks, @tbaker1026. I will take a look as soon as possible.

**Comment by starlow00** [comment]
Draft looks good, sending to VEO for review.

**Comment by starlow00** [comment]
There are no changes from VEO. A working copy is attached; please use it for future additions.

[Form 21-0966 ITF Product Guide SRT 03252024.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXNjQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--400dc19fccbffe6006a96304340353346d573093/Form%2021-0966%20ITF%20Product%20Guide%20SRT%2003252024.docx)
