### ISSUE TITLE
Get support tickets (from Vets, from VSRs) related to claims evidence

### ISSUE THREAD

**Issue by RivkaCGates** [department-of-veterans-affairs/va.gov-team#69567]

**Comment by jenniferbertsch** [comment]
First round of tickets are here: 
 https://dvagov.sharepoint.com/sites/vaabdvro/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2Fvaabdvro%2FShared%20Documents%2FClaims%20Evidence%2FTier%202%2D3%20Disability%20Claims%20Tkts%20Nov%202023&viewid=3fa7a9bb%2D3d4e%2D44c2%2Db93f%2D629268a08e72

I haven't had time review/sort, so it might be that after looking at these 50, we will want to make a more specific ask for additional tickets.
