### ISSUE TITLE
Schedule an SEP walkthrough

### ISSUE THREAD

**Issue by RivkaCGates** [department-of-veterans-affairs/va.gov-team#69574]
"Stakeholder Engagement Portal" - a current system, featured development stopped about 10 years ago, and usage is very low. It's the only system the VA has for reps to log in to right now, and a small fraction of reps use it. Our goal is to replace SEP. 

SEP uses EVSS APIs, and so SEP is blocking getting rid of EVSS.

[See user guide](https://www.sep.va.gov/sep/ecms-proxy/document/sep/dynamic-content/sep/assets/downloads/SEP_User_Guide_February2016.pdf).

See SEP: https://www.sep.va.gov/sep/web/guest/sep

There is a plan to turn off SEP at the end of 2025. SEP has some features related to our work, where reps can see pending representation requests and approve/reject those requests for appointment/PoA.

**Comment by uxrebecca** [comment]
Our best option might be to get a VSO who actually uses SEP to walk us through. Lesley could help with this.

**Comment by RenataKeck** [comment]
First walkthrough scheduled for 11/29 at 12pm ET. Recorded will be uploaded to Sharepoint afterward. 

Subsequent SEP walkthrough from a VA perspective TBD.
