### ISSUE TITLE
Finalize Research Roadmap

### ISSUE THREAD

**Issue by RivkaCGates** [department-of-veterans-affairs/va.gov-team#69573]
Draft already in progress - https://docs.google.com/document/d/16nbBE3YAXEPyiLMQ3g8E9165UyBKPpqrKlSzyahhnTk/edit

**Comment by RivkaCGates** [comment]
A concern - the research roadmap as it's laid out now doesn't match the product roadmap. Can we discuss?

**Comment by RenataKeck** [comment]
@RivkaCGates here is the [updated roadmap](https://docs.google.com/document/d/1Ksk88KhZcXFJxySHNC9icoacRUoISJznsGb0VfFSqX0/edit). I have a second ticket in Zenhub to update this as we get out to March/April to refine with more detail.

**Comment by RivkaCGates** [comment]
Only note here is it's late June/Early July for launch
