### ISSUE TITLE
Deploy Proofing Agent app to LHDI QA Environment

### ISSUE THREAD

**Issue by lmorris3** [department-of-veterans-affairs/va.gov-team#69590]
# Context

Update deployment of Hello World to be our application

# Acceptance Criteria
- [ ] Pipeline updated to deploy FE architecture
- [ ] Deploy Proofing Agent app to LHDI QA
- [ ] Design/Product can access app in QA

**Comment by rdvyas** [comment]
@lmorris3 is this a dup of #68456 ?

**Comment by lmorris3** [comment]
Yep!

**Comment by lmorris3** [comment]
closing, duplicate
