### ISSUE TITLE
Create Process for WHH Training Guide Self-Service

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#6959]
## User Story or Problem Statement
How might we make WHH training guides self-service for VFS teams?

## Goal
Create documentation and guidelines for VFS self-service for WHH product guides.

## Acceptance Criteria
- [x] Create documentation in GH
- [x] Potentially add in visualization??
- [ ] Communicate with Collab Cycle
- [x] Communicate with VFS teams
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by joanneesteban** [comment]
Oh! Did SSO create their product guide themselves, @clantosswett ?https://dsva.slack.com/archives/CNCEXNXK4/p1584542665002200

**Comment by Kimberley2019** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/contact-center/self-service-product-guide-template.md

**Comment by joanneesteban** [comment]
Thanks for adding, @Kimberley2019 ! 

A couple notes:

- Can you add that teams should begin with a table of contents? As well as the format that teams should have this in (Word). 

- Please also add links to examples that teams can reference:
    - [Education 22-1990 Product Guide](https://github.com/department-of-veterans-affairs/va.gov-team/files/4245065/Education.22-1990.Product.guide.docx)
    - [GI Bill Comparison Tool Product Guide](https://github.com/department-of-veterans-affairs/va.gov-team/files/4245076/GI.Bill.Comparison.Tool.Product.guide.docx)
    - [Pension Application Product Guide](https://github.com/department-of-veterans-affairs/va.gov-team/files/4346350/Pension.Application.Product.guide.docx)

@clantosswett - would you like to have VFS teams create their own product guides moving forward?

FYI we've added a self-service guide for teams to create their own Product Guides for Contact Center trainings, @andreahewitt-odd @meganhkelley

**Comment by Kimberley2019** [comment]
Hi @joanneesteban I will attempt to add a product guide in as an example into the GitHub documentation.  

@clantosswett and I discussed this last week during on of our meetings and the goal is to have teams create their own product guides moving forward, using the template that I created.

Also, it would be great for ALL product guides to live in one location so that individuals don't have to visit multiple folders to find.  The Contact Center folder would be a great housing location to keep all product guides.  Of course they can house them in their own folder, but it would be conducive to keep them in one centralized location.  And what better place than the Contact Center folder?  Your thoughts?

**Comment by joanneesteban** [comment]
@Kimberley2019 completely agree! The product guides should all live in one place - within the Platform facing Contact Center folder should work (but I'd check with Content/IA about storing PDFs/Word docs).

**Comment by joanneesteban** [comment]
@clantosswett to QA.

@joanneesteban to make sure it's a part of the collab cycle.

**Comment by clantosswett** [comment]
This looked great. I made some edits to it for clarity. @Kimberley2019 feel  free to review and close this when you think it is done. Thank you!

**Comment by Kimberley2019** [comment]
Thank you for the edits @clantosswett , great as ususal.
@joanneesteban Can you tell me what/who the Collab Cycle is, not sure how to share this out to them.  
Also, I was thinking that the best place to post the document was the VSF- all-teams channel.  Could a reminder of the document also be mentioned during the next ToT?

**Comment by joanneesteban** [comment]
Made some grammar edits, but otherwise good to go.

**Comment by joanneesteban** [comment]
I also added a link to our contact center documentation that the collab cycle refers to.

**Comment by Kimberley2019** [comment]
Updated location of the Product Self Service Guide.

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md

**Comment by Kimberley2019** [comment]
Shared out in the #vsf-all-teams slack channel on 4/22/2020.

Good Morning Team,
The link below is the documentation for how to self service product guides.  VFS teams should use this template as a guide for describing the use and functionality of a new tool or a significant update to an existing tool or feature.

Please slack #vsp-contact-center-support if you have any additional questions or comments regarding this document.

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md

**Comment by Kimberley2019** [comment]
@joanneesteban and/or @clantosswett can you please share with the Collab Cycle and ToT?
