### ISSUE TITLE
Get page use analytics (GA)

### ISSUE THREAD

**Issue by RivkaCGates** [department-of-veterans-affairs/va.gov-team#69614]
- [ ] [Request access to GA](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/analytics-customer-support-guide#Analyticscustomersupportguide-1.RequestaccesstoGoogleAnalytics) (requires VA email)
- [ ] Add to team sharepoint for review

**Comment by uxrebecca** [comment]
Once onboarded, we can apply for access through Platforms.

**Comment by smythe5** [comment]
This is the ticket template that needs to be filled out for a new VFS team - https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=analytics-insights%2C+governance-team%2C+platform-orientation%2C+new-vfs-team&projects=&template=new-vfs-team.md&title=New+VFS+Team+%5BInsert+team+name+here%5D

**Comment by smythe5** [comment]
Harold - I can help, but I also think we will need VA PO help.

**Comment by RenataKeck** [comment]
Analytics request will happen 11/21

**Comment by hdbaines** [comment]
Assigned to @uxrebecca who will assist reaching out to Lisa

**Comment by uxrebecca** [comment]
Wonder if we can get analytics on this page too: https://www.benefits.va.gov/vso/.

**Comment by uxrebecca** [comment]
[See Slack thread ](https://dsva.slack.com/archives/C0643ADPP60/p1703192436989819)with info from Lesley and Jannelle.

**Comment by uxrebecca** [comment]
I followed the instructions and created a Google account associated with my rebecca.blakiston@va.gov email account. Others on the team who want Analytics access will also need to do this, which I'll mention in Slack. The next step is for product manager to make a Github ticket: @RivkaCGates can you do this when you have a moment? 

[See instructions.](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/analytics-customer-support-guide#Analyticscustomersupportguide-1.RequestaccesstoGoogleAnalytics)

In the meantime I'll look at relevant Analytics the ARM team has already pulled and create a Google doc.

**Comment by uxrebecca** [comment]
Here's [a Google Doc](https://docs.google.com/document/d/1-dAF5SdCSj52bNo8oVss5JVPBu96kC_2-fmDvorVe14/edit) to track what we know so far. I pulled from a couple Slack threads to get us started.

**Comment by RivkaCGates** [comment]
On it, but do we want everyone on the team to get set first so I do this
once?

**Comment by uxrebecca** [comment]
Yes, that makes sense to me. Could be an agenda item for the Wednesday
meeting just to confirm who needs/wants access? It might just be the
researchers that need access but I'm not sure.

**Comment by uxrebecca** [comment]
Mentioned at today's standup and people will indicate on Slack if they need/want access and then create VA accounts. I gave a deadline of this Friday and then we can make the formal request.

[See Slack thread](https://dsva.slack.com/archives/C05SUUM4GAW/p1703867020755639).

**Comment by RivkaCGates** [comment]
Request made.
