### ISSUE TITLE
Refine Mockups for "View Payments"

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#6962]
## Goal
After receiving feedback from others (and possibly after Design Intent Review), we want to refine our mockups to reflect a closer approximation to a final version that can be built by engineers.

## Considerations
- Intro/landing page should be useful in transition
- Include mobile versions, considering tables (should this be a separate ticket?)

## Tasks
- Address content and layout
  - Copy needs to be un-Loremed
- Ensure functionality is still in place per the Epic

## Acceptance Criteria
- [x] All feedback has been addressed in the latest mockup and shared with the team

**Comment by sporeboy** [comment]
The initial View Payments concept mockups are here: https://xd.adobe.com/view/5f609803-b045-428a-510e-1754e404af3e-2951/
