### ISSUE TITLE
[BE] 10-10EZR: Fix Submission Issue

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#69634]
As a Veteran, I would like to submit my updated information so I make sure the VA has all of my information correct.

- [x] Fix 500 submission error
- [x] Talk to @fbonds about errors he's seeing
- [x] **Success: We are no longer getting submission errors**

**Comment by lihanli** [comment]
sentry log for the error: http://sentry.vfs.va.gov/organizations/vsp/issues/237297/?environment=staging&project=3&query=is%3Aunresolved+controller_name%3Aform1010_ezrs&statsPeriod=14d

**Comment by fbonds** [comment]
When I attempt to submit any EZR update, this is what I see in the UI:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkMvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bd447999019476705ee81a9ad31076160f7e4b2a/image.png)
