### ISSUE TITLE
Switch to using system list from profile

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#6964]
We can switch to using the system list in the profile, instead of the vaos systems endpoint. This will save us an api call and also give us access to the `isCerner` flag for each system.

**Comment by jbalboni** [comment]
This is somewhat dependent on this PR getting merged: https://github.com/department-of-veterans-affairs/vets-api/pull/4021

If we merge before that PR, then we need to filter out some incorrect entries in the facility array.

**Comment by jbalboni** [comment]
@lenaecb I'd like to try to do this ticket this sprint, if that's ok. It's preparation for the new Cerner messaging/offboarding.

**Comment by lenaecb** [comment]
Ok, sounds good @jbalboni
