### ISSUE TITLE
Support secondary nav research sessions (Sprint 19)

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#69659]
### User story

As a Cartographers team member, I want to provide note-taking support and/or conduct sessions in the study of the existing VAgov mobile secondary navigation menu, so that I can help ensure the completion of the study.

## Acceptance criteria

- Attended study sessions as a note-taker or facilitator, as needed

## Tasks

- [ ]

**Comment by sterkenburgsara** [comment]
Update: research sessions wrapped up on 11/22. Both @Jenny-yw and @LoisLewisUSDS began research synthesis the week of 11/27.
