### ISSUE TITLE
[FSR 3.0 - PI1/24] FSR/SW Form data lifecycle & Code cleanup

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#69652]
### Description
As part of the President's initiative to support Veterans experiencing financial hardship we are simplifying the process for claiming medical debt forgiveness by streamlining the request process and offering instant determination for Veterans who meet the criteria.

The 3.0 work will consist of the discovery items identified in the post MVP/2.0 release.

Initial Epics to be under this Super Epic may include the items below - still TBD.

## Product Outline
The FSR experience needs to be updated for a few reasons - this scope includes:

- Research & Design
- FE 5655 form data lifecycle (Code Cleanup A)
- FE/BE Logic Shift
- FE Post Logic Shift (Code Cleanup B)

## Definition of done

- [x] Team has identified a path forward to update the to a 3.0 version aligning with current application and design requirements. 

### Scope of release:

All current identified work not included for the MVP or 2.0 release.

### Out of Scope:

Newly identified work that comes out of current research and enhancement requests. All that should still be collected and placed under a 4.0 Epic.

### Additional Details/Notes (optional):
*Any other relevant information about this project not already listed above*

**Comment by HeatherRienks** [comment]
@Tom-Davis  - per FE Sync on 11/13/23, reminder to create 2 new Epics for PI24:
-Design Development
-Implementation
