### ISSUE TITLE
Update IPP Stakeholder Map

### ISSUE THREAD

**Issue by skirkman16** [department-of-veterans-affairs/va.gov-team#69658]
Our service blueprint needs to be updated since we have progressed on IPP with user flows and prototypes

Tasks

- [x] Update service blueprint
- [x] Share out internally for review

Tasks

- [x] Stakeholder map is ready for external visibility
- [x] Stakeholder map is shared out with PO

**Comment by skirkman16** [comment]
Starting off by putting a list of stakeholders and details into a [spreadsheet](https://docs.google.com/spreadsheets/d/1GPpUctwR9DY9Ec3L_lJqw4o4mQqQBq-7EGiw1oj6h6c/edit#gid=0). this information will be pulled into a visual afterwards.

**Comment by SophiaPhilipMO** [comment]
https://miro.com/blog/stakeholder-mapping/

**Comment by SophiaPhilipMO** [comment]
Updated with PO input [here](https://app.mural.co/t/innovationboards1199/m/innovationboards1199/1699473133499/f5ff16622fee3d8943d77d2bd2b182862c589b60?sender=u8b2bd1f5eec8aeeb5ca99521) @lmorris3 and @skirkman16 pulling into review for you both to see if we can demo
