### ISSUE TITLE
Docs update: Cerner is acquired by Oracle and now called Oracle Health

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-team#69661]
### Description
Cerner has been acquired by Oracle and is now called Oracle Health. (Slack from Lauren Alexanderson: https://dsva.slack.com/archives/C0190MTGNUE/p1699551530805749)

https://depo-platform-documentation.scrollhelp.site/developer-docs/how-to-opt-in-to-drupal-as-the-source-of-truth-for needs to be updated as a result. 

SharePoint doc on VA with suggested copy updates: 
https://dvagov.sharepoint.com/:w:/r/sites/SitewidePublicWebsites/Shared%20Documents/Healthcare%20widgets/How%20to%20opt-in%20to%20Drupal%20as%20the%20source%20of%20truth%20for%20Oracle%20Heallth-related%20apps%20and%20widgets.docx?d=wb599260e31e0477998c08d515fe4aff4&csf=1&web=1&e=f5FhPk

These changes are just to the doc where my team owns this data integration, but not the bigger picture of Cerner integrations at large. (Lauren Alexanderson owns that.)

Our code level use of `isCerner` hasn't changed yet, so if you all do this work now, we'll likely file a follow up ticket for later to update code level mentions.

### Relevant URLs
https://depo-platform-documentation.scrollhelp.site/developer-docs/how-to-opt-in-to-drupal-as-the-source-of-truth-for

### Which type of team are you on? (Platform team, VFS team, or Leadership)
VFS - Sitewide Public Websites

**Comment by johnny-jesensky-adhoc** [comment]
Hi @jilladams - thank you for flagging this. The Content Team will take a look, and move towards making the necessary updates. We'll be sure to provide any updates in this ticket.

**Comment by taylojill** [comment]
Hi @jilladams I'm working on your document update request. I've attached a pdf of the changes I made, and it includes 3 comments/questions. Please review and let me know what you think. Also, we don't own the SharePoint doc and cannot make changes.
Here's what I did:
1. Added an information box regarding the name change and future changes at the beginning of the document. Is this worded correctly?
2. Changed all Cerner references to Oracle Health, with the exception of code use/mentions.

My questions/comments relate to:
- Recommendation to remove sentence with link to 404 error in GitHub.
- Should I make the name changes in the "How this data point is managed in Drupal" section, before parenthesis?
- I made the name change in the "list of selectors" descriptions.

cc @johnny-jesensky-adhoc 
[PWD-Copy of How to opt-in to Drupal as the source of truth for Oracle Health-related apps and widgets.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFhoQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b2571fcb0f51d854040d558e5f0494c166b5ac06/PWD-Copy%20of%20How%20to%20opt-in%20to%20Drupal%20as%20the%20source%20of%20truth%20for%20Oracle%20Health-related%20apps%20and%20widgets.pdf)

**Comment by jilladams** [comment]
Thanks!

1. Info box looks great
2. Corrected url for the 404: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/healthcare-widget-support/how_to_set_up_vamc_cerner_within_va_health_care_portals.md
3. Re: the "How this data is managed by Drupal" options for Vista, Cerner, Converting to Cerner, -- those are actual field descriptions / selection options in the Drupal CMS, so we shouldn't update that in the docs til our team can prioritize updating them in the CMS itself, timing tbd:
![Screenshot 2023-11-16 at 12 04 59 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/85581471/fe372370-4cb5-4fa1-9630-7df020ccaecd)

![Screenshot 2023-11-16 at 12 03 56 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/85581471/9a4ba739-0603-41b8-849e-378c05d5ad0d)

**Comment by taylojill** [comment]
Hi @jilladams! Thank you! I'll update the page and get it deployed/published on Monday 11/20. Have a great weekend!

**Comment by taylojill** [comment]
Page updated and checked for launch-blocking issues. Ready for deployment.
