### ISSUE TITLE
Feature flag Community Care and turn off for all users

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#6966]
As a CC provider I am minimizing the F2F appointments I have with patients during the current COVID-19 pandemic so Veterans should not be able to request CC appointments with me. 

## Acceptance Criteria:
- User cannot make community care requests for any care type
- Existing community care functionality will be placed behind feature toggle
- Community Care-only care types cannot be viewed in 'Choose type of care' (is that only Podiatry?)

**Comment by jbalboni** [comment]
This is currently all working except for the last bullet. Podiatry is the only CC only type of care we have, and you can't go any further with it, but it's still visible.

**Comment by jbalboni** [comment]
Change for podiatry is merged, putting this back in current sprint for now.
