### ISSUE TITLE
Sign Out of All Devices Research - Assistive Tech 

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#69677]
### Description of UX Tasks

Since we conducted the first round of research on a Figma prototype, we decided to wait for a coded prototype to conduct usability testing with assistive tech users.

- [ ] ask FE to create a coded prototype
- [x] [a11y research ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/67511)
   - [x] Open [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/67511) 
   - [ ] discuss setting up research for screen reader
   - [ ] make any adjustments needed to prototype

#### Acceptance Criteria
- [ ] Reviewed by UX Team
- [ ] Reviewed by PMs
- [ ] Documentation has been updated
- [ ] Put published research in drive

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kingbmike** [comment]
@claytonzook Assuming I can close this ticket?

**Comment by claytonzook** [comment]
@kingbmike sorry, just catching this. I don't see any issue with us closing this ticket
