### ISSUE TITLE
Address Initial 686 Error Handling

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#6968]
## Goal
At either each endpoint or group of endpoints, we will need error handling in place to better address errors gracefully as they occur. 

## Considerations
- An error could be `temporary` or an error could be `fatal`.
- We need to retry calls and report if errors are `temporary` or persist data and report an error if it is `fatal`.
- We need to report all errors to Sentry and tag errors appropriately with helpful data like call name, data, and severity (`temporary`/`fatal`)
- What are the different types of errors that can occur
- Where in the process do they need to be placed
- Where can these be monitored
- @kathleencrawford has a GFE with EVSS error handling code. We can use that as a guide.
- There is a base `backend_service_exception` class that looks helpful. It has Sentry errors and a param attribute for including form data. We could inherit from this.
- **This can act as an mini-Epic, and may make other tickets**

## Tasks
- Accrue list of possible errors from BGS (error pattern for 500’s, 400’s, etc.) and document them
- Categorize list of errors as `fatal` or `temporary`.
- Add  business logic for `fatal`/`temporary` errors per call
- Add tests to ensure error handling is working as expected
- **Possible issues**
  - Data validation on submit to do our best to submit a valid 686
    - If data is not valid ex. missing required fields or state name vs state code, quickly return a helpful message to the user alerting the about this to mitigate errors in backend.
  - May need to add refinement to how BGS/LIghthouse gem returns errors

## Acceptance Criteria
- [x] Error handling has been initialized and is ready for further iteration

**Comment by digitaldrk** [comment]
After reviewing EVSS code, we feel good about our approach.

All of the VNP calls are easy. They “always” work so long as required fields are populated.

If a VNP call fails before `insertBenefitClaim`, we have a few options. We can re-do the whole thing (this is default in jobs) or we can add retries. Not /quite/ sure what the best approach is but both are super easy to implement. We’ll think about it, maybe the solution will reveal itself as we refactor

The tough one is `insertBenefitClaim`. This call is finicky and can only happen successfully so many times (9).  So far there are 3 known errors that can occur with `insertBenefitClaim`.

1. GUIEXXX’s
2. Max number of submissions
3. Duplicate Benefit Claims found
4. 404 (anomally)

These are all fatal, we would likely retry in the event of the first but that’s optimistic. On the second, we would bail.

If we were able to successfully submit an `insertBenefitClaim`, but failed after that for some reason, we would attempt to rescue and update the proc to ‘ready’.
