### ISSUE TITLE
Prod Dev Support collaboration on how Onboarding documentation plays into the ideal repo IA

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/va.gov-team#697]
Definition of done
- Met w/Prod Dev Support
- Updated deck of recommended IA per ^ findings
- Shared w/DSVA for review / approval

**Comment by mnorthuis** [comment]
8/7/2019 - Draft repo structure was distributed to various members of the Product Dev Support team, DSVA and other VSP team members for feedback. 

![image.png](https://images.zenhubusercontent.com/59ca6a73b0222d5de4792f1d/09935230-4cda-4b28-b6c7-835a0aff8ed7)

**Comment by mnorthuis** [comment]
Many revisions since the structure shared above.  Meeting scheduled on 8/12 and 8/13 to continue discussions and refine.

**Comment by mnorthuis** [comment]
Final high level repo structure reviewed and approved by prod support team and vsp leadership.  closing issue.
