### ISSUE TITLE
Out-of-box dashboard & key data views in GA

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#6970]
We need to be able to more quickly assess performance of current VAOS rollout efforts. Having both an out-of-box GA dashboard and key collection views will help us answer key rollout questions. In the future we'll use this as a baseline for a Product Health Report. 

## Questions to answer with GA dashboard:
- How many users accessed the app?
- Usage: defined by "actions completed"
  - How many total appointments have been made?
      - Of those total appointments, how many were:
            - VA requests
            - CC request
            - Self-schedule
- What was the conversion rate? _[(Conversion = Requested (VA & CC) + direct-scheduled appointments / new appointment starts)]_
       - What was the conversion rate per appointment type:
            - VA requests
            - CC requests
            - Self-schedule
- For Self-schedule - what is the breakdown per care type? (in Kay's doc, it's called "Speciality Usage")
- For VA request - what is the breakdown per care type? (in Kay's doc, it's called "Speciality Usage")
- For CC request - what is the breakdown per care type? (in Kay's doc, it's called "Speciality Usage")
- Total # of Cancellations
- Device type used to access VAOS

## Questions to answer with GA Funnels:
- Per appointment type (VA request, CC request, Self-Schedule)
       - How many users started the flow, finished the flow? Those that didn't finish, why/what happened?
       - Where are there bottlenecks/failure points in the conversion process?

## AC:
- Total number of users who have access the VAOS tool
- Total # of Conversions
- Total # of Successful Conversions (Success defined in this situation as submitting with error/failure)
- Total # of Failed Conversions (Failed defined in this situation as submitting but failing/encountering error)
- Total # of Cancellations
- Total # of Cancellations Successful
- Total # of Cancellation Failed
- Total # of Appointment VA Requests Attempts
    - Total # of Appt VA Request Successful
    - Total # of Appt VA Request Failed
- Total # of Appointment CC Requests Attempts
    - Total # of Appt CC RequestsSuccessful
    - Total # of Appt CC Requests Failed
- Total # of Direct Schedule Attempts
    - Total # of Direct Schedule Successful
    - Total # of Direct Schedule Failed
- Funnel goals - Goal being successful submission; want to understand dropoff rate and where dropoff
    - Funnel for VA Requests
    - Funnel for CC Request
    - Funnel for Direct Schedule
- Errors
    - Errors are system - why?
    - Errors are human - why?

**Comment by joanneesteban** [comment]
## Info for Insights

- Goal Date for GA Dashboard: 3/31/20

@lenaecb Thanks for meeting with us earlier! Would you be able to prioritize top performance stories for VAOS?

We would suggest leaving the funnel conversion out because it is better visualized in the funnel report on GA/please continue to leverage the funnel conversion report that Narin has been using.

**Comment by lenaecb** [comment]
@joanneesteban - I have update the story to split out priority for dashboard and for the funnels via questions to answer. Is that what you are looking for?

@narin - what are your thoughts about the errors and showing that in the dashboard? I haven't been able to make sense of what the error are telling us but I assume those errors will give us some idea of the dropoff rate during the schedule process. Thoughts?

**Comment by jonwehausen** [comment]
[Current Dashboard Template](https://analytics.google.com/analytics/web/template?uid=mYlX1F5eSV2NXT93eoHTcw) - **_Work In Progress!_**

@nedierecel Could I request your assistance on a few items: 
- Where did we settle in [this thread](https://github.com/department-of-veterans-affairs/va.gov-team/issues/5983) on our error tracking methodology? 
- Can we surfacing a comprehensive conversion rate today broken down by appointment type under our current paradigm and GA dashboard limitations? (va requests, cc request, direct)
- Few other clarifications on our tracking methods I'd like to validate

**Comment by nedierecel** [comment]
@jonwehausen Confirming I received and that we can talk through this at our 2pm.

- There are ineligibility errors and API errors (the latter will be surfaced as a `vaos-error` event).
- Yes, each type of request is included in the event label, so we should be able to calculate that accordingly. For this implementation, we didn't surface it as custom metrics.
- Sure - other items are still being worked through in #7093 re: custom dimensions

**Comment by lenaecb** [comment]
@jonwehausen @nedierecel - I know your priorities shifted some last week due to COVID-19 needs. Do you have timeline when the dashboard might be stood up? I am trying to understand if we can lend a hand here from our team too. 

Thanks!

**Comment by jonwehausen** [comment]
Hi @lenaecb ,

Thanks for understanding our priority has shifted. Currently, we are able to provide the majority of metrics you have requested, the ones we are currently having snags with are: 
- Funneling -- which we had discussed during our call, there isn't a great way to surface these within a GA dashboard. If your team is comfortable continuing to use the Funnel Visualization report, we can ignore this. 
- Successful requests by care type -- should ultimately be resolved with #7093 changes
- Conversion rate by care type -- this is something we can provide under two options:
  - A: Surface within the GA dashboard, but will require additional configuration work on our part. Would like to loop-in @bsmartin-ep for bandwidth if we decide to go this route.   
  - B: Within DOMO down-the-line without any additional configuration work. 

Let us know your thoughts!

**Comment by lenaecb** [comment]
@jonwehausen - how do you access the working dashboard? 

Funneling - we can continue with existing, but I'd like to walk through this with someone as I am trying to help tell the story of where folks are dropping and our hypothesis as to why.

Success requests - i think @narin is going to look into it today?

Conversion rate - this really depends on the startup time needed for DOMO. It also might get addressed a bit with the funnel flow. Thoughts? I think if we create one more flow for all requests, that might suffice. cc: @narin

**Comment by jonwehausen** [comment]
Hi Lenae, 

May you see if by going to the Health Care Modernized Content view > Dashboards if you see a dashboard title "VAOS Key Data (WIP)?" This is where the current dashboard can be found.  

![image](https://user-images.githubusercontent.com/48527022/77950323-4fefd500-7296-11ea-825f-62dbef8b1248.png)

- Funneling -- 👍 
- Success Rates -- 👍 
- Conversion rate -- The issue is with the limitation around getting to a specific conversion rate for each appointment type (va requests, direct, community care). I would say both options proposed are around the same level of time / effort...so if we are unable to get to developing a DOMO dashboard for a while (cc: @joanneesteban), this may be worth our time in making the configuration adjustment to surface in the GA dashboard. 

cc: @joanneesteban

**Comment by jonwehausen** [comment]
### Following up from our discussion today - 4.2.2020
- In order to accurately deliver on a conversion rate by care type, and with the understanding there be various clicks a user may take to enter into the path for each type, we would like to request events be added at each starting point. 
- From there, we will be able to setup a custom funnel that will lead to a more accurate conversion rate for each care type
- @lenaecb In addition, this will give us greater flexibility in trying to determine why a user may have dropped off. 

@nedierecel Would you mind reviewing and determining if in alignment with your convention? 

### VA Request
```javascript
dataLayer.push{(
   'event': 'vaos-request-path-started',
   'flow: 'va-request'
)};
```
### CC Request
```javascript
dataLayer.push{(
   'event': 'vaos-request-path-started',
   'flow: 'cc-request'
)};
```
### Direct Request
```javascript
dataLayer.push{(
   'event': 'vaos-request-path-started',
   'flow: 'direct'
)};
```

@narin Following Nedie's sign-off we can begin on implementing these items.

**Comment by nedierecel** [comment]
@jonwehausen There's a slight difference in the naming prefixes. Here's the [convention in GA showing submissions and successes for reference](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p184318975/explorer-segmentExplorer.segmentId=analytics.eventLabel&explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.eventLabel%22,%22RE%22,%22vaos-.*-submission%22,0%5D,%5B0,%22analytics.eventLabel%22,%22PT%22,%22cancel%22,1%5D%5D/).

Prefix Structure
`vaos-direct` - VA Direct Scheduling
`vaos-community-care` - Community Care
`vaos-request` - VA Request

#### Suggestions: 
- VA Request
`dataLayer.push{(
   'event': 'vaos-request-path-started')};`

- Community Care
`dataLayer.push{(
   'event': 'vaos-community-care-path-started')};`

- Direct Request
`dataLayer.push{(
   'event': 'vaos-direct-path-started')};`

**Comment by jonwehausen** [comment]
@nedierecel Thanks for second set of eyes. I've updated my comment [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6970#issuecomment-608077208) to reflect your suggestions. 

@narin We are ready to move forward with these 3 events where appropriate.

**Comment by narin** [comment]
@jonwehausen I've added those events the code is on staging and I think got released to production as well.  Feel free to move this ticket back to "In progress" while the rest of the dashboard is worked on.

**Comment by jonwehausen** [comment]
@narin Thank you sir, we will give that a test and get back with you!

**Comment by narin** [comment]
@nedierecel @jonwehausen @bsmartin-ep: 

The dashboard looks like it's coming along.  @lenaecb noticed that for [this date range](https://analytics.google.com/analytics/web/?authuser=0#/dashboard/vyFZNBY9SvOlE7yiscjfhA/a50123418w177519031p184318975/_u.date00=20200324&_u.date01=20200408/), there are only 8 events under the Type of Care widget even though there were 100+ successful requests. 

I'm wondering if this could be related to the work I did to clear out the custom dimensions?  Happy to hop on a call to discuss.

**Comment by bsmartin-ep** [comment]
@lenaecb / @narin -

Looking into this now.  It does appear _Type of Care_ isn't being recorded for many submissions, but I don't think it started with out update last week (to clear out errant data layer values).

1. Narin is acquiring production test credentials for me.  I ran through a scheduling on staging and I see my results in the Top Events report.
2. This is something I can test in production, but have the changes to VAOS for COVID changed the procedure in a way where this value would not be collected in time?
3.  Out of curiosity, why are you filtering by _VAOS Flow_ in this widget?  I didn't see other with a similar filter.

![image](https://user-images.githubusercontent.com/62304138/78904763-04ce8280-7a4b-11ea-9694-262c6dbf21c9.png)
 
cc @jonwehausen

**Comment by jonwehausen** [comment]
@bsmartin-ep In your testing of the _Type of Care_ could you also test the 3 new `path-started` events and document results here for validation.

**Comment by bsmartin-ep** [comment]
Preliminary tests on staging @jonwehausen:

Path | Path Event | Success Event | Status
---   | --- | --- | ------------- 
Direct Request      | ![image.png](https://images.zenhubusercontent.com/5e73c8e4b62b077da52f1c14/fc1e77e8-e716-4e4d-ba81-7b5b2f79d1e4) | ![image.png](https://images.zenhubusercontent.com/5e73c8e4b62b077da52f1c14/f3c06657-5b5a-4c23-a7bb-67017adde119) | ✅ **PASSED**
VA Request  | ![image.png](https://images.zenhubusercontent.com/5e73c8e4b62b077da52f1c14/39371bd7-1889-4c61-8916-9fc22b477639) | ![image.png](https://images.zenhubusercontent.com/5e73c8e4b62b077da52f1c14/cd1254ea-fc5f-4959-b36d-c026665b91fc) | ✅ **PASSED**
Community Care  | TBD | TBD | TBD

Per Narin:
"Community care isn’t enabled on staging yet.  Working on that as well.  As soon as it’s up I’ll send a script for it"

**Comment by lenaecb** [comment]
Attached Qs and some feedback[https://app.zenhub.com/files/133843125/77542e45-7e43-4f75-93d6-340e50493fe0/download](https://app.zenhub.com/files/133843125/77542e45-7e43-4f75-93d6-340e50493fe0/download)

**Comment by jonwehausen** [comment]
Questions answered from above feedback: 
[VAOS Feedback.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4477294/VAOS.Feedback.docx)

_Questions still pending we're working thru_

**Comment by jonwehausen** [comment]
### Custom Funnels 
@lenaecb Please use these custom funnel reports in order to see your conversion rate by each schedule type (va request, cc request, direct):

Couple things to note: 
- Please let us know if you're unable to change the date range now
- These are user based funnels, meaning the conversion rate is calculated as it relates to a specific user
- Please be sure you select the "**Health Care Modernized View**" in the VA.gov - Production property 

- [All Appointments](https://analytics.google.com/analytics/web/template?uid=xMkfeVAvTCSwIQvOf-xOkQ)
- [VA Requests](https://analytics.google.com/analytics/web/template?uid=LxHjvHV5SEe2d-dU6t3OTw)
- [CC Requests](https://analytics.google.com/analytics/web/template?uid=WAIaDjaQReuzRTE6tF94Jg)
- [Direct Requests](https://analytics.google.com/analytics/web/template?uid=pgKI7t14S32e3gGdPUKSQg)

**Comment by lenaecb** [comment]
@jonwehausen @joanneesteban - looks like for this ticket we're still trying to figure out if the goal funnel will work for us, is that true?

I commented in this ticket #8031 that we want to do a little iteration on our funnels to segment users that we believe are trigger our eligibility events to see how many users drop out of the flow after that event is triggered. I would assume we'd want a separate ticket for that work since it's out of scope for this ticket.

**Comment by lenaecb** [comment]
Met all AC. Moving away goal funnel to custom funnels based on VAOS needs.
