### ISSUE TITLE
Replicate EVSS Functionality

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#6971]
_This ticket might become a mini-Epic to track these_
## Goal
There are several functions that EVSS is currently handling that may need to be recreated and rebuilt into BGS, like "PDF Creation and storage to eFolder."  These need to be triaged and scoped by the BE.

## Tasks
- Write a list of all external functions that EVSS currently provides to support the 686 submission process 
  - For example, we have a ticket for PDF Creation
- Establish what is needed to move or what is not part of the optimal process
  - For example, there might be some notification functions that are not necessary that would not be moved
  - Is there an email function that needs rebuilt?

## Acceptance Criteria
- [x] Define and document this list in a *.md file in GitHub

**Comment by kathleencrawford** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/engineering/686-evss-submission-steps.md
