### ISSUE TITLE
Analytics Implementation or QA Support for Covid-19 FAQ

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#6972]
# Analytics Implementation or QA Request

## What this form is for
Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets. 

> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

## Description
- Is this request for Google Analytics implementation or QA?
Google Analytics implementation

- Who is this request for?

    - @clantosswett @jenniferlee-dsva @lalexanderson-dsva 
    _Provide any relevant contact information and link this issue to the insights team on the DSVA Slack Channel: `#VFS-Platform-Support`._
    
- What team/project is this work for?
    
    - Cross team but driven by public websites team
    
- Provide the Domain where Google Analytics needs to be implemented
    
    - www.va.gov/coronavirus-veteran-frequently-asked-questions/

- Please provide any upcoming deadlines or important milestones
    
    
    - Goal is to launch this ASAP. Earliest would be this afternoon (3/18)Wednesday 3/18

- Typical Website Interactions to Track

    - *Conversions - Understanding the User Flow:* _Provide URLs that are part of the application from introduction page to successful form completion; conditional pages that are visible depending on an applicant's answer should be marker accordingly._

The page will be linked from the following pages: 
    
- The VA.gov homepage COVID-19 OPIA banner message
- VHA public health page: https://www.publichealth.va.gov/n-coronavirus/?utm_source=VA%20Alert&utm_medium=Banner&utm_campaign=Coronavirus&utm_content=link%20to%20VA%20Public%20Health%20page
- Other VAMC website pages: TBD
- OPIA’s social media COVID-19 messages: TBD
- My HealtheVet: TBD
    
    - *Other User Interactions*: _Provide details on other interactions and metrics, like click to help text links, that are helpful in understanding user behavior._
    
    - Can we please track clicks on all the links featured on this page. See preview page for list of links and let me know if you need me to list these out: http://preview-prod.vfs.va.gov/preview?nodeId=3014

- Sample Users when authentication is required _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - [Provide sample users or link to user information here]

- Test Users to replicate the event _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - [Provide test users or link to user information here]

- Certain conditions/responses that need to be reviewed

    - [Provide conditions/responses here]

- Additional Comments

    - [Add any comments or questions for the Insights team here (if applicable).]

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
Site has launched - staged a generic tag to fire on **ALL** link clicks on https://www.va.gov/coronavirus-veteran-frequently-asked-questions/. 

In some cases, we already have tracking pre-built and there will be overlap / redundancy with this new tag -- this tag will simply add redundancy and capture those elements currently not tracked. 

Event Action Syntax: Navigation - COVID - {{Click Text}} - {{Click URL}}

Workspace with tag staged: https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000245

Example of Tag Fire: 
![image](https://user-images.githubusercontent.com/48527022/77110092-61fe8780-69fb-11ea-9708-1434184e5a21.png)

@nedierecel would you like to do a quick gut-check before we deploy?

**Comment by jonwehausen** [comment]
Tag described above has been deployed!

@clantosswett @joanneesteban @jenniferlee-dsva @nedierecel

**Comment by nedierecel** [comment]
@jonwehausen Confirming I have reviewed the COVID page and see the link tracking. As you already noted, tracking is already in place for outbound links, login, and expander text.
