### ISSUE TITLE
Time zone abbreviation too long

### ISSUE THREAD

**Issue by JRRoof** [department-of-veterans-affairs/va.gov-team#69729]
## Background/Request
The new appointment list was designed for time zones to abbreviated as 3 characters.  When a time zone exceeds 3 characters it causes the UI to wrap unexpectedly.  This is currently happening for the Alaskan time zone which is being abbreviated to AKDT and AKST.

[Example screen shot](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3JFQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a7854264d15ef880b3f36b8340d8257c1d43b668/image.png)

### Goal
Determine what will be required to remove the D and S from these abbreviations.  Time zone should always display as AKT.  Also, determine if there are any other scenarios in which the time zone exceeds 3 characters.

### Requirements to Consider
None

---

## Tasks
- Answer the following questions:
  - Q:  What needs to be changed in order to shorten the Alaskan time zone abbreviation to AKT?
  - Q:  Are there other scenarios where the time zone abbreviation could exceed 3 characters?
 
## Time Box
_ hours

## Definition of Done
- Tasks are complete
- Research and recommendations are documented in this ticket

---

**Comment by ldelacosta** [comment]
This has been fixed. No issues to report. Closing out the ticket. 

<img width="668" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejg1QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e0e72d96759b94ff22dbbb8f85f522e3f0dfec1d/image%20%289%29.png" alt="image (9).png" />

cc: @JRRoof

**Comment by JRRoof** [comment]
<img width="668" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGc1QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1b56abe6fbdd7eb2c9cdf0c69302457034403f69/image.png" alt="image.png" />
