### ISSUE TITLE
[FE] 10-10EZR - Standalone form: QA Finding - Insurance Required fields verification failing on Submission

### ISSUE THREAD

**Issue by fbonds** [department-of-veterans-affairs/va.gov-team#69731]
Whenever I try a submit with insurance information, I receive error: "We're Sorry.  Some information in your form is missing or invalid.  I've tried with policy number, with group number and with both specified.  I always get the error.  If I remove the insurance information, I don't get the error.  It unclear what's triggering this.  All labelled required fields have a value.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0RGQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1c069f3f388b20623a4cd7f0b15ef4548642d80e/Screenshot%202023-11-10%20at%207.53.51%E2%80%AFAM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0xGQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--06523d2327e8437a9dd0841da7dc1867441a8ce5/Screenshot%202023-11-10%20at%207.54.05%E2%80%AFAM.png)

**Comment by hdjustice** [comment]
Using Test User 38, I also experience the same issue.

**Comment by hdjustice** [comment]
@longmd for awareness

**Comment by hdjustice** [comment]
@longmd for awareness

**Comment by longmd** [comment]
@hdjustice , this is the issue Josh and I were working on yesterday. We have identified the issue and Josh is going to have a fix ready on Monday.

**Comment by hdjustice** [comment]
Fabulous, thank you
