### ISSUE TITLE
Research methodology information missing?

### ISSUE THREAD

**Issue by ALogsdon3** [department-of-veterans-affairs/va.gov-team#69738]
### Description
On the Planning moderated studies page, one of the bullets in the Research plan sections says, "What methodology will you use? (More on that below.)" 
I don't see any information below that section (or elsewhere in the Research at VA documentation) that addresses research methodology. 

### Relevant URLs

https://depo-platform-documentation.scrollhelp.site/research-design/planning-moderated-studies#Planningmoderatedstudies-Researchplan

### Which type of team are you on? (Platform team, VFS team, or Leadership)
Sitewide-Facilities

**Comment by johnny-jesensky-adhoc** [comment]
Hi @ALogsdon3 - thank you for flagging this. The Content Team will take a look, and move towards making the necessary updates. We'll be sure to provide any updates in this ticket.

**Comment by taylojill** [comment]
Message sent to Naomi (SME) via Slack. I requested content to update the page.

**Comment by taylojill** [comment]
I received an update from Naomi. I incorporated the content and sent her a pdf copy for approval.

**Comment by taylojill** [comment]
The new content has been approved. The page is ready for deployment/publishing. Here's what I did:
1. Added a Research methodologies section at the bottom of the page.
2. Included a hyperlink for additional information [https://methods.18f.gov/](url)
3. Reviewed page for launch-blocking issues, no issues found.

cc @ALogsdon3 @johnny-jesensky-adhoc
