### ISSUE TITLE
Add user types to Representative Serializer

### ISSUE THREAD

**Issue by jvcAdHoc** [department-of-veterans-affairs/va.gov-team#69742]
Currently, there is no way to know from the api response if a representative is an attorney or a claim agent. The front end should have the request type in state, but this could be useful information in the future.

**Comment by oddball-lindsay** [comment]
We are removing Claims Agents and are not sure when/if they will be added back as a rep type.  

That said, we are introducing Veteran Service Officers.  This might still be needed, but to now differentiate between Veteran Service Officers and Attorneys.
