### ISSUE TITLE
[MVP] Apply for Veterans Pension Page: Copy Updates

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#69745]
## Note
Part of the larger effort to update the existing 527EZ form to add missing fields/info and remove depreciated fields.

## Description
On the Apply for Veterans Pension page, 
for both the Not Authenticated & Authenticated versions of the page,
update the content and links,
as shown on the designs.

## User Story
As a Pension benefits VA team,
we need to update the Prepare section of the copy on the Apply for Veterans Pension page,
so that users know about the additional forms applicants might need to submit based on their situation.

## Designs
- Not authenticated: https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/FCD0E156-01C7-482A-A5DD-D8EA76ABCC02
- Authenticated: https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/9B8C1C76-51A9-4573-AD92-2743CD682F8D
- User returns to unsaved application: https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/D8C01197-EE3E-4E37-881E-8E8D0B27986E
- User returns to saved application: https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/7F33507E-D12F-4ECD-B6F0-B5ACDF2423C0
- Different user states: https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/v/lPWvbo/p/6571319D-6329-4249-B0A7-E39DA9DA31F4/canvas?posX=-7079.559633531698&posY=-10359.878879157197&zoom=0.10954540967941284

## Acceptance Criteria
The intro page section of the 527EZ (Apply for Veterans Pension page), will have updated copy and and links within the Prepare section,
as shown on the designs.

_Formatting is not provided. Please reference design files for formatting._

**Copy for the Prepare section is as follows.** 

`Follow these steps to apply for a Veterans pension`

`Prepare`

`To fill out this application, you will need this information:`

`Your Social Security number or VA file number (*Required)`
`Your military history (*Required)`
`Your marital status and prior marital history`
`Information about your spouse's prior marriage`
`Information about your dependent children`
`Your employment history`

`You'll also need this information:`

`Financial information about you and your dependents (*Required)`
`Your military history (*Required)`

`If you have special circumstances for your medical care, you may also need these additional forms:`

`Statement of Medical Care: Care Worksheets at the end of this pension benefits form that must be completed by an administrator or licensed medical professional`
`Claim for Special Monthly Pension ([VA Form 21-2680)](https://www.vba.va.gov/pubs/forms/vba-21-2680-are.pdf)`
`Claim for Medical Nursing Home and/or $90.00 Rate Reduction Request ([VA Form 21-0779](https://www.vba.va.gov/pubs/forms/VBA-21-0779-ARE.pdf))`
`Claim for Fiduciary Assistance ([VA Form 21-2680](https://www.vba.va.gov/pubs/forms/vba-21-2680-are.pdf))`

`Apply`

`Complete and submit the pension benefits application form.`

**Copy for Not authenticated:** 

`Sign in now to save time and save your work in progress`

`Here's how signing in now helps you:`
`We can fill in some of your information for you to save you time.`
`You can save your work in progress. You'll hae one year from when yo ustart or make updates to your application to come back and finish it.`
`Note: You can sign in after you start your application. But you'll lose any information you already filled in.`
`Sign in to start your application`
`Start your application without signing in`

**Copy for Authenticated:** 

`Note: Since you're signed in to your account, we can prefill part of your application based on your account details. You can also save your form in progress and come back later to finish filling out.`

**Copy for User resumes unsaved application:** 

`Your application is in progress and was last saved on [date here]`
`You can continue applying now, or come back later to finish your application.`
`You application will expire on [date here].`

**Copy for User resumes saved application:** 

`Your Veterans pension benefits application has been saved.`
`Last saved on [date here]`
`Your application will expire on [date here]`
`If you're on a public computer, please sign out of your account before you leave so your information stays secure.`

## Tasks
[Software Development Tasks](https://docs.google.com/document/d/1vtn5co_YzGl1cFRNrIBAdjf53dmfH4_EXBWK8C5mU9Y/edit?usp=sharing)

- [x] Front-end work @ToddWebDev 

## Review
- [ ] Designer (Maya) has signed off on pages in staging

## Artifacts
- [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/527EZ-reactivation-initiative-brief.md)
- [User flow in Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683826730324/61b509f935adaa2acf2f7769a5ba911726a7b237?sender=u9d01ee38af217e4877e75660)
- [Prototypes in Sketch](https://www.sketch.com/s/75b363db-6be8-4b7e-8655-8f12f1ea5554)
- [Spreadsheet of deleted form fields](https://docs.google.com/spreadsheets/d/1PTXxO6mFH2ZUK6XxX7iCCQb-NoSvhB5P/edit?usp=sharing&ouid=104362113771391164792&rtpof=true&sd=true)
- [Content source of truth/PDF form](https://www.vba.va.gov/pubs/forms/VBA-21P-527EZ-ARE.pdf)
- [Link to testing accounts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/form-deactivation/527EZ-staging-test-accounts-accessible.md)
- [Link to staging](https://staging.va.gov/)

**Comment by ToddWebDev** [comment]
@vbellissimo
In the design there appears to be three links included within the parenthesis on these three items:
- Claim for Special Monthly Pension (VA Form 21-2680)
- Claim for Medical Nursing Home and/or $90.00 Rate Reduction Request (VA Form 21-0779)
- Claim for Fiduciary Assistance (VA Form 21-2680)

If these are links, can we please include the link details in the acceptance criteria? Please include each url, whether they should open in a new tab, or download a pdf in the browser.

**Comment by vbellissimo** [comment]
@mayacoforma @katherine-fung Do either of you know which pages these 3 links should go to? And if they should open as new tabs?

![Screenshot 2023-11-15 at 12 00 20 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/106613300/2a737110-f004-4a44-a610-c3fbbbadab9e)

**Comment by mayacoforma** [comment]
@vbellissimo @ToddWebDev @katherine-fung I've updated the copy to include links to these forms: 

https://www.vba.va.gov/pubs/forms/vba-21-2680-are.pdf
https://www.vba.va.gov/pubs/forms/VBA-21-0779-ARE.pdf

@katherine-fung I have a question about the copy:

Claim for Special Monthly Pension ([VA Form 21-2680)](https://www.vba.va.gov/pubs/forms/vba-21-2680-are.pdf)
Claim for Fiduciary Assistance ([VA Form 21-2680](https://www.vba.va.gov/pubs/forms/vba-21-2680-are.pdf))

Are these supposed to be the same form?

**Comment by katherine-fung** [comment]
I looked at the PDF form and can confirm those 2 are supposed to be the same form. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1hhQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--59932e7e75f4cd05046b446a636cfc3a54ffc72b/Screenshot%20%28356%29.png)

**Comment by mayacoforma** [comment]
@katherine-fung Thank you!

@ToddWebDev All these links should open on a separate tab. They open the PDF directly.

**Comment by mayacoforma** [comment]
@ToddWebDev @katherine-fung I've observed some differences between the latest copy in the sketch file and what's on staging. I've attached screenshots. 

STAGING
<img width="641" alt="Staging" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/144955233/252d1ac0-b7a7-487f-ac06-eb0fff53de3c">

SKETCH
<img width="736" alt="Sketch" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/144955233/c5e21649-dc41-4fa8-865b-0c9d9a122157">

**Comment by katherine-fung** [comment]
Thanks @mayacoforma. @ToddWebDev  I'm confirming that the copy in staging should change to say "You'll have one year from when you start or make updates to your application to come back and finish it."

(Slack thread for reference: https://app.slack.com/client/T03FECE8V/C05MS96P6P2)

**Comment by mayacoforma** [comment]
Conducted QA and approved.
