### ISSUE TITLE
[MVP] Step 3: Create new page and questions for Claimant not determined disabled

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#69748]
## Note
Part of the larger effort to update the existing 527EZ form to add missing fields/info and remove depreciated fields.

## Description
On Step 3, Health and employment: medical care,
create a new page and questions for Claimant not determined disabled,
as shown on the designs.

## Description
On Step 3, Health and employment information
create a new page(s) for Enter social security disability payments,
as shown on the designs.

## User Story
As a veteran under the age of 65 seeking a pension benefit, I aim to determine my eligibility by confirming whether I receive Social Security disability payments or I plan to submit supplementary medical evidence along with my application to substantiate my disability, ultimately aiming for approval to receive my pension.

##Screen Flow
https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/Wd3jGLq

## Task Prototype 
Form 527 - Step 3 of 7 - Health and Employment Prototype / Medical Care / Social Security Disability Prototype: 
https://sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/aM8mwd5/play

## Step Prototype
Form 527 - Step 3 of 7 - Health and Employment Prototype: https://sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/L4Mpad5/play

## Acceptance Criteria
**Validation scenarios**
If the user answers "No" to Do you currently receive Social Security disability payments? (*Required)?
they will see a warning message that says:
`You'll need to provide medical evidence with this application`,
as shown on the designs

**New page:**
On Step 3 health and employment: medical care,
create a new page, as shown on the designs.
On this page, add a required radio button question question:
`Social Security disability`
`Do you have a medical condition that prevents you from working? (*Required)`
`Yes`
`No`

**Validation scenarios**
If the user answers "Yes" to Do you have a medical condition that prevents you from working (*Required)?,
add a warning message that says:
`You'll need to provide medical evidence with this application`,
as shown on the designs

## Tasks
[Software Development Tasks](https://docs.google.com/document/d/1vtn5co_YzGl1cFRNrIBAdjf53dmfH4_EXBWK8C5mU9Y/edit?usp=sharing)

- [x] Front-end work @ToddWebDev 

## Review
- [ ] Designer (Maya) has signed off on pages in staging

## Artifacts
- [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/527EZ-reactivation-initiative-brief.md)
- [User flow in Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683826730324/61b509f935adaa2acf2f7769a5ba911726a7b237?sender=u9d01ee38af217e4877e75660)
- [Prototypes in Sketch](https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/p/988EBB71-6E9D-4099-A2BC-4BB61551E38F/canvas)
- [Spreadsheet of deleted form fields](https://docs.google.com/spreadsheets/d/1PTXxO6mFH2ZUK6XxX7iCCQb-NoSvhB5P/edit?usp=sharing&ouid=104362113771391164792&rtpof=true&sd=true)
- [Content source of truth/PDF form](https://www.vba.va.gov/pubs/forms/VBA-21P-527EZ-ARE.pdf)
- [Link to testing accounts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/form-deactivation/527EZ-staging-test-accounts-accessible.md)
- [Link to staging](https://staging.va.gov/)

**Comment by vbellissimo** [comment]
@ToddWebDev Here are similar copy edits to match to the latest design files. Looks like it's header(s) changes and info alert boxes:

- Receive SS disability payments? https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/97087177-C5E9-4EB7-A9B7-A488DE9E5207
- If answered yes: https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/B4A4044D-2E0B-4975-94BD-871ED4AE4F25
- If answered no: https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/0FB35D0F-2180-4178-B398-A0B95710BCF2
- Do you have a medical condition that prevents you from working? https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/66A4554D-5F41-430A-B99D-F0486C5C64DC

@mayacoforma do you know what the "info alert" acceptance criteria should be if they answer "yes" on the SS disability payments question? This is shown as the green box alert on the design. Can you provide to Todd?

**Comment by mayacoforma** [comment]
@ToddWebDev, I can't locate this question in the staging environment. Am I overlooking something?

**Comment by mayacoforma** [comment]
Conducted QA and approved.
