### ISSUE TITLE
[MVP] Step 3: Create new page and questions for Enter nursing home status

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#69750]
## Note
Part of the larger effort to update the existing 527EZ form to add missing fields/info and remove depreciated fields.

## Description
On Step 3, Health and employment: medical care,
create a new page for Enter nursing home status,
as shown on the designs.

## User Story
As a veteran seeking a pension benefit, I aim to determine my eligibility by confirming whether I receive Social Security disability payments or I plan to submit supplementary medical evidence along with my application to substantiate my disability, ultimately aiming for approval to receive my pension.

## Screen Flow
https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/pY7qkYR

## Task Prototype 
Form 527 - Step 3 of 7 - Health and Employment Prototype / Medical Care / Nursing Home Status
https://sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/Wd3jep8/play

## Step Prototype
Form 527 - Step 3 of 7 - Health and Employment Prototype: https://sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/L4Mpad5/play

## Acceptance Criteria
**New page:**
On the new page, add a required radio button question:
`Disabilities/medical information`
`Do you live in a nursing home? (*Required)`
`Yes`
`No`

**Validation scenarios:**
If this questions is answered as "yes" to Do you live in a nursing home? (*Required),
follow steps found on ticket [#69751](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/gh/department-of-veterans-affairs/va.gov-team/69751)

If this questions is answered as "no" to Do you live in a nursing home? (*Required),
skip to page/question about Special Monthly Pension found on ticket #69752

## Tasks
[Software Development Tasks](https://docs.google.com/document/d/1vtn5co_YzGl1cFRNrIBAdjf53dmfH4_EXBWK8C5mU9Y/edit?usp=sharing)

- [x] Front-end work @ToddWebDev 

## Review
- [ ] Designer (Maya) has signed off on pages in staging

## Artifacts
- [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/527EZ-reactivation-initiative-brief.md)
- [User flow in Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683826730324/61b509f935adaa2acf2f7769a5ba911726a7b237?sender=u9d01ee38af217e4877e75660)
- [Prototypes in Sketch](https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/p/988EBB71-6E9D-4099-A2BC-4BB61551E38F/canvas)
- [Spreadsheet of deleted form fields](https://docs.google.com/spreadsheets/d/1PTXxO6mFH2ZUK6XxX7iCCQb-NoSvhB5P/edit?usp=sharing&ouid=104362113771391164792&rtpof=true&sd=true)
- [Content source of truth/PDF form](https://www.vba.va.gov/pubs/forms/VBA-21P-527EZ-ARE.pdf)
- [Link to testing accounts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/form-deactivation/527EZ-staging-test-accounts-accessible.md)
- [Link to staging](https://staging.va.gov/)

**Comment by vbellissimo** [comment]
@ToddWebDev Minor update that came in from CAIA this week, can you update one of the headers on this to match the design of this file, instead? https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/AA3FFBD3-8684-48C1-98BE-FBE4AB1F741E

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHZnQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8e27594fc286dc02226a919a81e3dd02f30d1194/Screenshot%202023-11-16%20at%2010.11.53%20AM.png)

**Comment by ToddWebDev** [comment]
@vbellissimo Yes, I'll include this update in the PR

**Comment by vbellissimo** [comment]
@ToddWebDev Thank you. I also caught that the header that says `Health and employment information` was shortened from `Health and employment information: medical care`.

That's all I think for this. I'm going through all the tickets you're working on right now to ensure we don't miss recent content updates provided. Thank you.

**Comment by ToddWebDev** [comment]
@vbellissimo I'll include this change too.

**Comment by mayacoforma** [comment]
QAed and approved.
