### ISSUE TITLE
[MVP] Step 3: Create 2 new pages and questions for Claimant lives in nursing home

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#69751]
## Note
Part of the larger effort to update the existing 527EZ form to add missing fields/info and remove depreciated fields.

## Description
On Step 3, Health and employment: medical care,
create 2 new pages for when Claimant lives in nursing home,
as shown on the designs.

## User Story
As a veteran seeking a pension benefit, I aim to determine my eligibility by confirming whether I receive Social Security disability payments or I plan to submit supplementary medical evidence along with my application to substantiate my disability, ultimately aiming for approval to receive my pension.

## Screen Flow
https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/pY7qkYR

## Task Prototype 
Form 527 - Step 3 of 7 - Health and Employment Prototype / Medical Care / Nursing Home Status
https://sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/Wd3jep8/play

## Step Prototype
Form 527 - Step 3 of 7 - Health and Employment Prototype: https://sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/L4Mpad5/play

## Acceptance Criteria
**New page 1:**
Create 1st page, to add a radio button question:
`Disabilities/medical information`
`Does Medicaid cover all or part of your nursing home costs?`
`Yes`
`No`

**Validation scenarios**
If the user answers "no" to Does Medicaid cover all or part of your nursing home costs?,
They will see new question found on the next page listed on this ticket.

If the user answers "yes" to Does Medicaid cover all or part of your nursing home costs?,
skip to page/question: Are you claiming special monthly pension? shown on ticket [#69752](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/gh/department-of-veterans-affairs/va.gov-team/69752)

**New page 2:**
Create 2nd page, to add a radio button question:
`Disabilities/medical information`
`Have you applied for Medicaid?`
`Yes`
`No`

**Validation scenarios**
If the user answers "Yes" to Have you applied for Medicaid?,
add a gray warning message that says:
`You'll need to submit a Request for Nursing Home Information in Connection with Claim for Aid and Attendance (VA Form 21-0779). An official from your nursing home must complete the form. We'll ask you to upload this form at the end of this application. Or you can send it to us by mail.`
as shown on the designs

If the user answers "No" to Have you applied for Medicaid?,
the gray warning box **_will not_** appear. The user will move on to the next page/question for: Are you claiming special monthly pension? shown on ticket [#69752](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/gh/department-of-veterans-affairs/va.gov-team/69752)

**Match copy:**
Ensure all copy, including headers, questions wording and buttons match the designs.

## Tasks
[Software Development Tasks](https://docs.google.com/document/d/1vtn5co_YzGl1cFRNrIBAdjf53dmfH4_EXBWK8C5mU9Y/edit?usp=sharing)

- [ ] Front-end work @ToddWebDev 

## Review
- [x] Reviewed by @vbellissimo; findings added to comments below.

## Artifacts
- [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/527EZ-reactivation-initiative-brief.md)
- [User flow in Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683826730324/61b509f935adaa2acf2f7769a5ba911726a7b237?sender=u9d01ee38af217e4877e75660)
- [Prototypes in Sketch](https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/p/988EBB71-6E9D-4099-A2BC-4BB61551E38F/canvas)
- [Spreadsheet of deleted form fields](https://docs.google.com/spreadsheets/d/1PTXxO6mFH2ZUK6XxX7iCCQb-NoSvhB5P/edit?usp=sharing&ouid=104362113771391164792&rtpof=true&sd=true)
- [Content source of truth/PDF form](https://www.vba.va.gov/pubs/forms/VBA-21P-527EZ-ARE.pdf)
- [Link to testing accounts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/form-deactivation/527EZ-staging-test-accounts-accessible.md)
- [Link to staging](https://staging.va.gov/)

**Comment by vbellissimo** [comment]
@ToddWebDev We may want to put this on in our "blocked" column on the board for now.

@mayacoforma @katherine-fung 

There seem to be a lot of comments on the latest designs for these two questions, as of yesterday.

See the comments on these files:
- Does medicaid cover all or part of your nursing home costs? https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/D3289E82-71D9-452C-8350-1696F4D3F31B
- Have you applied for Medicaid? https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/27F9AF01-052F-42AF-939F-8773808A98EF

@katherine-fung Can you let us know your thoughts on how we could combine these two questions based on this comment? https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/p/6571319D-6329-4249-B0A7-E39DA9DA31F4/canvas?annotation=d6f88412-1c41-4d09-8ac1-1d7e6d5f40a7

The reasoning for this request is to help the data mapping into the new PDF question format:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMS9nQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--80a8a3e575daa0bd6a575541c994f998e6a064ed/Screenshot%202023-11-15%20at%203.16.04%20PM.png)

**Comment by ToddWebDev** [comment]
@vbellissimo I'm happy to move this back to the sprint backlog for more refinement if we're still unsure of the implementation.

**Comment by vbellissimo** [comment]
@ToddWebDev This ticket should now be unblocked. You can disregard the comment above this one.

After speaking with Emily and Julie yesterday, we decided that these two pages/questions will remain separated into their own pages. The validation for each of these questions should be followed as described in the body of this ticket. If you have any questions, please ping Maya and I.

Thank you.

**Comment by vbellissimo** [comment]
**Vicky's note about PDF mapping:**

- If the user selects "Yes" to `Does Medicaid cover all or part of your nursing home costs?` on the online form, the PDF mapping will marked as "Yes" on 4D.
- If the user selects "No" to `Does Medicaid cover all or part of your nursing home costs?` on the online form, but answers "Yes" to `Have you applied for Medicaid?` on the online form, the PDF mapping will marked as "Yes" on 4D.

- If the user selects "No" to either `Does Medicaid cover all or part of your nursing home costs?` or `Have you applied for Medicaid?` on the online form, the PDF mapping will marked as "No" on 4D.

cc @danlim715 for awareness in PDF mapping.

**Comment by vbellissimo** [comment]
@ToddWebDev Is there a reason this warning info box is not the gray, like the one in the Sketch files? Are you using a better, suggested design component?

Other than that, the new questions looks good and so does the answer logic. Thank you!

<img width="1141" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVExQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--be96e2a43b9a64e539cae5f42c6cf238b900fcde/Screenshot%202023-12-05%20at%204.52.13%E2%80%AFPM.png" alt="Screenshot 2023-12-05 at 4.52.13 PM.png" />

**Comment by vbellissimo** [comment]
@ToddWebDev Is there a reason this warning info box is not the gray, like the one in the Sketch files? Are you using a better, suggested design component?

Other than that, the new questions looks good and so does the answer logic. Thank you!

<img width="1141" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVExQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--be96e2a43b9a64e539cae5f42c6cf238b900fcde/Screenshot%202023-12-05%20at%204.52.13%E2%80%AFPM.png" alt="Screenshot 2023-12-05 at 4.52.13 PM.png" />
