### ISSUE TITLE
[MVP] Step 3: Create 2 new pages and questions for Federal medical center status

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#69755]
## Note
Part of the larger effort to update the existing 527EZ form to add missing fields/info and remove depreciated fields.

## Description
On Step 3 Health and employment information,
create 2 new pages for Federal medical center status,
as shown on the designs.

## User Story
As a veteran seeking a pension benefit, I aim to strengthen my claim by documenting the Federal treatment facilities where I've received medical care for my disability. This information will serve as supporting evidence, facilitating the process of obtaining the pension benefit I am entitled to.

##Screen Flow
https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc

## Task Prototype 
Form 527 - Step 3 of 7 - Health and Employment Prototype / Medical Care / VA Medical Centers:
https://sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/JAyRkYk/play

## Step Prototype
Form 527 - Step 3 of 7 - Health and Employment Prototype: https://sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/L4Mpad5/play

## Acceptance Criteria
**New page 1:**
Create 1st new page, add a required radio button question:
`Treatment from federal medical facilities`
`Have you received treatment from any non-VA federal medical facilities within the past year? (*Required)`
`Examples of federal medical facilities include military bases and prisons.`
`Yes`
`No`

**Validation scenarios**
If the user answers "yes",
they will see the new page with new question as follows...
as shown on the designs

**New page 2:**
Create 2nd new page, add a required short text answer question:
`Federal medical facilities`
`Enter all non-VA federal medical facilities where you've received treatment within the past year.`
`Federal medical center (*Required)`

**Validation scenarios**
Once the user enters a Federal medical center, they are able to see the ability to "Add another federal medical center" option.
as shown on the designs

**Match copy:**
_Ensure all copy, including headers, questions wording and buttons match the designs._

## Tasks
[Software Development Tasks](https://docs.google.com/document/d/1vtn5co_YzGl1cFRNrIBAdjf53dmfH4_EXBWK8C5mU9Y/edit?usp=sharing)

- [x] Front-end work @ToddWebDev 

## Review
- [ ] Designer (Maya) has signed off on pages in staging

## Artifacts
- [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/527EZ-reactivation-initiative-brief.md)
- [User flow in Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683826730324/61b509f935adaa2acf2f7769a5ba911726a7b237?sender=u9d01ee38af217e4877e75660)
- [Prototypes in Sketch](https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/p/988EBB71-6E9D-4099-A2BC-4BB61551E38F/canvas)
- [Spreadsheet of deleted form fields](https://docs.google.com/spreadsheets/d/1PTXxO6mFH2ZUK6XxX7iCCQb-NoSvhB5P/edit?usp=sharing&ouid=104362113771391164792&rtpof=true&sd=true)
- [Content source of truth/PDF form](https://www.vba.va.gov/pubs/forms/VBA-21P-527EZ-ARE.pdf)
- [Link to testing accounts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/form-deactivation/527EZ-staging-test-accounts-accessible.md)
- [Link to staging](https://staging.va.gov/)

**Comment by mayacoforma** [comment]
@ToddWebDev I noticed a few minor copy updates needed. 

Please add a period after "prisons"

<img width="745" alt="Screenshot 2023-11-29 at 9 41 59 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/144955233/c161f117-61b9-4172-9450-cd3b8a4eb400">


Please update the copy to say "Enter all non-VA federal medical facilities...."
<img width="803" alt="Screenshot 2023-11-29 at 9 42 14 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/144955233/0522ef17-6f98-4fb6-928f-45ce20a8266c">


Thanks!

**Comment by mayacoforma** [comment]
Conducted QA and approved.
