### ISSUE TITLE
[MVP] Step 3: Create new page, question and validation for Enter special monthly pension status

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#69752]
## Note
Part of the larger effort to update the existing 527EZ form to add missing fields/info and remove depreciated fields.

## Description
On Step 3, Health and employment information,
create new page for Special monthly pension,
as shown on the designs.

## User Story
As a veteran in search of pension benefits, my goal is to assess my eligibility by verifying if I qualify for a special monthly pension based on disabilities such as amputation, loss of limb function, or total blindness. Ultimately, my objective is to secure approval to receive the pension benefit.

## Screen Flow
https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/r9x7KVq

## Task Prototype 
Form 527 - Step 3 of 7 - Health and Employment Prototype / Medical Care / Special monthly pension: https://sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/Wd3j5QK/play

## Step Prototype
Form 527 - Step 3 of 7 - Health and Employment Prototype: https://sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/L4Mpad5/play

## Acceptance Criteria
**New page:**
On the new page:
`Special monthly pension`

Add a required radio button question:
`If you have certain health needs or disabilities, you may be eligible for additional pension. We call this special monthly pension (SMP).`

`You may be eligible for SMP if you need the regular assistance of another person, have severe visual impairment, or are generally confined to your immediate premises.`

`Are you claiming special monthly pension? (*Required)`

`Yes`
`No`

**Validation scenarios**
If the user answers "yes" to Are you claiming special monthly pension?,
add a warning message that says:

`You'll need to submit an Examination for Household Status or Permanent Need for Regular Aid and Attendance (VA Form 21-2680).`
`Make sure every box is complete and has a signature from a physician, physician assistant, certified nurse practitioner (CNP), or clinical nurse specialist (CNS).`
`We'll ask you to upload this form at the end of this application. Or you can send it to us by mail.`
`Get VA Form 21-2680 to download.`

The link to download the form will open as a separate tab to this page: https://www.vba.va.gov/pubs/forms/vba-21-2680-are.pdf

If the user answers "no" to Are you claiming special monthly pension?, they will not see the warning copy and will move on to the next page/question for Treatment from a VA Medical Center as shown on ticket #69942

**Match copy:**
_Ensure all copy, including headers, questions wording and buttons match the designs._

## Tasks
- [ ] Front-end work

## Review
- [x] Designer (Maya) has signed off on pages in staging

## Artifacts
- [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/527EZ-reactivation-initiative-brief.md)
- [User flow in Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683826730324/61b509f935adaa2acf2f7769a5ba911726a7b237?sender=u9d01ee38af217e4877e75660)
- [Prototypes in Sketch](https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/p/988EBB71-6E9D-4099-A2BC-4BB61551E38F/canvas)
- [Spreadsheet of deleted form fields](https://docs.google.com/spreadsheets/d/1PTXxO6mFH2ZUK6XxX7iCCQb-NoSvhB5P/edit?usp=sharing&ouid=104362113771391164792&rtpof=true&sd=true)
- [Content source of truth/PDF form](https://www.vba.va.gov/pubs/forms/VBA-21P-527EZ-ARE.pdf)
- [Link to testing accounts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/form-deactivation/527EZ-staging-test-accounts-accessible.md)
- [Link to staging](https://staging.va.gov/)

**Comment by vbellissimo** [comment]
@TaiWilkin Just wanted to highlight that I added more information to the body of this ticket about validation if the answer is "no" to this question. If you have any questions, please ping Maya and I. Thank you.

**Comment by mayacoforma** [comment]
@ToddWebDev This looks good, thank you!
