### ISSUE TITLE
[MVP] Step 3: Add new fields for Current employment

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#69758]
## Note
Part of the larger effort to update the existing 527EZ form to add missing fields/info and remove depreciated fields.

## Description
On Step 3, Health and employment information,
add 2 new required fields for Current employment:
- What kind of work do you currently do?
- How many hours per week do you work on average?
as shown on the designs.

## User Story
As a veteran under 65 years old who is currently employed  seeking a pension benefit, I aim to input my present employment status and enumerate any existing jobs to furnish comprehensive evidence for an upfront evaluation of my claim.

##Screen Flow
https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/bLKDloo

## Task Prototype 
Form 527 - Step 3 of 7 - Health and Employment Prototype / Medical Care / Current Employment:
https://sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/vRrj4zn/play

## Step Prototype
Form 527 - Step 3 of 7 - Health and Employment Prototype: https://sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/L4Mpad5/play

## Acceptance Criteria
**Validation scenarios**
If the user answers "Yes" to Are you currently employed (*Required)?
they will see the following question on a separate page:

**Current employment page, new required questions with required short open text fields**
`What kind of work do you currently do? (*Required)`
`How many hours per week do you work on average? (*Required)`

_These questions will be placed in that order, before the "Job Title" question/field._

**Validation scenarios**
If the user has more than 1 current employer, they are able to see the ability to "Add another job" option,
as shown on the designs.

**Match copy:**
_Ensure all copy, including headers, questions wording and buttons match the designs._

## Tasks
- [x] Front-end work

## Review
- [x] Reviewed by @vbellissimo; findings added to comments below.

## Artifacts
- [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/527EZ-reactivation-initiative-brief.md)
- [User flow in Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683826730324/61b509f935adaa2acf2f7769a5ba911726a7b237?sender=u9d01ee38af217e4877e75660)
- [Prototypes in Sketch](https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/p/988EBB71-6E9D-4099-A2BC-4BB61551E38F/canvas)
- [Spreadsheet of deleted form fields](https://docs.google.com/spreadsheets/d/1PTXxO6mFH2ZUK6XxX7iCCQb-NoSvhB5P/edit?usp=sharing&ouid=104362113771391164792&rtpof=true&sd=true)
- [Content source of truth/PDF form](https://www.vba.va.gov/pubs/forms/VBA-21P-527EZ-ARE.pdf)
- [Link to testing accounts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/form-deactivation/527EZ-staging-test-accounts-accessible.md)
- [Link to staging](https://staging.va.gov/)

**Comment by ToddWebDev** [comment]
Here are some options to validate the 'How many hours per week...' field value:

https://design.va.gov/components/form/number-input#examples
 - a number input where any integer can be entered
 - a number input within a maximum value (e.g. Enter a number less than 168)

**Comment by ToddWebDev** [comment]
The 'What kind of work do you currently do?' field seems well suited for a hint or example of the expected type of answer. (Example: Construction) This example will prompt the veteran to keep their answer short and succinct rather than possible writing a long description. Maybe we can even rename it, 'What type of work do you currently do?'

**Comment by vbellissimo** [comment]
@ToddWebDev I tested the new fields and validation and they look good.

However, when going through the form flow, I did not encounter the question/page for `Are you currently employed (*Required)?`. Do you have any idea if it exists already or why that is?

Thanks!

<img width="920" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWsxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8c40b00bbe89b16c5c4531fa65c24f487714a9af/Screenshot%202023-12-05%20at%204.57.58%E2%80%AFPM.png" alt="Screenshot 2023-12-05 at 4.57.58 PM.png" />


<img width="920" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWcxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--33093b1de83bf96d206b2c3a6acd0835d471271f/Screenshot%202023-12-05%20at%204.58.09%E2%80%AFPM.png" alt="Screenshot 2023-12-05 at 4.58.09 PM.png" />

**Comment by mayacoforma** [comment]
![Screenshot 2023-12-06 at 9 53 00 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/144955233/ccd24ebf-9463-4d8d-9566-587d62f1b527)]

@ToddWebDev Julie S. mentioned that the VA design system doesn't offer disabled buttons for accessibility reasons. I checked the design system documentation (https://design.va.gov/components/button/) and confirmed. The way we are handling this in other parts of the form's design is to remove the button entirely and display an alert that they exceeded the max number of list / loop options. I've attached a screenshot example. 

![Screenshot 2023-12-06 at 9 58 14 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/144955233/ef4f244c-582d-426a-9483-c749deda67c0)

CC: @vbellissimo @aplatt-coforma

**Comment by ToddWebDev** [comment]
@mayacoforma Thank you for the feedback. @vbellissimo Can we get a new ticket so that we can update and track this issue?

**Comment by vbellissimo** [comment]
@ToddWebDev @mayacoforma Good morning. Just wanted to let you know I created this new task to correct this. It's currently in our "product backlog": [[MVP] Step 3: Correct button for multi-entry for Current Employment #71638](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/gh/department-of-veterans-affairs/va.gov-team/71638)
