### ISSUE TITLE
[MVP] Step 3: Match question wording and copy for Are you 65 years old or older?

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#69757]
## Note
Part of the larger effort to update the existing 527EZ form to add missing fields/info and remove depreciated fields.

## Description
On Step 3 Health and employment information,
ensure question matches the designs for:
Are you 65 years old or older?
as shown on the designs.

## User Story
As a veteran pursuing a pension benefit, my objective is to determine whether I fall into the age bracket of over or under 65. If I am found to be over 65, I expect to be automatically recognized as disabled, bypassing inquiries about my current employment status.

## Step Prototype
Form 527 - Step 3 of 7 - Health and Employment Prototype: 
https://sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/QDyqmz8/play

## Acceptance Criteria
Ensure the following page copy and question matches the designs:

**Question**
`Age`
`Are you 65 years old or older? (*Required)`
`Yes`
`No`

**PLEASE NOTE**
See this Video of designer explain logic flow for this question: https://drive.google.com/file/d/1QEI_uVSHTWEw5jCDTJgO1OcZnnp9WZU3/view

If they are **_not_** 65 years old or older, they will be prompted employment questions later in the form flow.

**Match copy:**
_Ensure all copy, including headers, questions wording and buttons match the designs._

## Tasks
- [x] Front-end work

## Review
- [x] Content review on staging

## Artifacts
- [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/527EZ-reactivation-initiative-brief.md)
- [User flow in Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683826730324/61b509f935adaa2acf2f7769a5ba911726a7b237?sender=u9d01ee38af217e4877e75660)
- [Prototypes in Sketch](https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/p/988EBB71-6E9D-4099-A2BC-4BB61551E38F/canvas)
- [Spreadsheet of deleted form fields](https://docs.google.com/spreadsheets/d/1PTXxO6mFH2ZUK6XxX7iCCQb-NoSvhB5P/edit?usp=sharing&ouid=104362113771391164792&rtpof=true&sd=true)
- [Content source of truth/PDF form](https://www.vba.va.gov/pubs/forms/VBA-21P-527EZ-ARE.pdf)
- [Link to testing accounts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/form-deactivation/527EZ-staging-test-accounts-accessible.md)
- [Link to staging](https://staging.va.gov/)

**Comment by ToddWebDev** [comment]
At this point in the form the veteran has been required to enter their birth date so we can derive whether they are 65 years old or not.

**Comment by jstrothman** [comment]
@ToddWebDev I just came here to ask about using the DOB here to determine whether they are 65 or older--let's keep the question but prefill it. /cc @mayacoforma

**Comment by aplatt-coforma** [comment]
Content verified:
- checked the default state of the 65 older question for when birthdates were older and younger than 65
- checked the flow for when older than 65, no current employment questions were asked 
- checked the flow for when younger than 65, current employment questions were asked. 
<img width="878" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTlBQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--46364d10d24ce2f35b08ae3806ec43514999f695/Screenshot%202023-12-07%20at%209.06.27%E2%80%AFAM.png" alt="Screenshot 2023-12-07 at 9.06.27 AM.png" />

**Comment by aplatt-coforma** [comment]
Moving to completed in sprint. Thanks Tai!
