### ISSUE TITLE
[Design] COVID-19 My VA alert: Mock up alert for the dashboard

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#6976]
## Background

Epic #6974

We need to show an alert that links patients to an existing VA health chat tool on the My VA dashboard. This alert should only show for patients with access to this tool, which is currently patients that go to hospitals in VISNs 8 and 23 (VISN = Veterans Integrated Service Network = essentially a group of VA hospitals).

## Alert specs

**Design**

- This alert should appear on the top of users' My VA dashboard under the main heading for that page
- I think the "blue" alert should work, but let me know if you think the yellow one is better for this

**What this alert needs to include**

- Patients can use health chat app to ask their doctors questions about COVID-19
- They can use this tool on their desktop, or download mobile apps for their phone
- A link to this page to access the tool https://mobile.va.gov/app/va-health-chat

Since we should be able to determine who should see this alert based on information in the code, we shouldn't need to mention that only users at certain facilities can use this tool. BUT we might want to consider it. If we do, the easiest thing would be to say it's available to people at certain facilities, and to go [to go here](https://mobile.va.gov/app/va-health-chat) to determine if they are at an eligible facility.

## Tasks

- [ ] Design alert
- [ ] Get copy (note: we'll need final approval from stakeholders on copy, so there might be some back and forth)

## Acceptance criteria

- [ ] The alert is designed and final copy has been approved.

**Comment by tressaellen** [comment]
Here's the first pass - I'm happy to work whoever on copy. 

![VA Health Chat.jpg](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/a1a28f70-0a31-4ac4-b2ad-76a7100b0fc1)

**Comment by Samara-Strauss** [comment]
Good start! I think we can further finesse when we have feedback from stakeholders.

One request before I share this out — can you update that link and make it a button instead? Something like "Get the VA Health Chat app" should do for now.

**Comment by tressaellen** [comment]
Sure thing!

![VA Health Chat](https://user-images.githubusercontent.com/58752772/77001152-52eddb80-690e-11ea-9659-a8039189e42e.jpg)

**Comment by Samara-Strauss** [comment]
This has been sent around to the stakeholder group for feedback on what content to include. Once we are sure what details need to be included, we can bring in someone to work on the final copy.

**Comment by Samara-Strauss** [comment]
Alright! First round of feedback:

- We should change the verbiage around "doctors" — people could end up talking to a number of different health care professionals (probably) depending on availability, questions, need. So we should instead say something about "health care professionals" instead of mentioning a specific role.
- Let's also mention that this service is available at no-cost to any veterans who receive health care at the VA.

**Comment by tressaellen** [comment]
<img width="759" alt="Screen Shot 2020-03-18 at 1 03 35 PM" src="https://user-images.githubusercontent.com/58752772/77007631-5dfa3900-6919-11ea-894b-e3e712888520.png">

**Comment by Samara-Strauss** [comment]
NVM — we have been asked to use the term "VA Staff". These notes were helpful:

> I think we should avoid specifying the types of staff that are part of VA Health Chat since it varies from site to site. The language that’s used on mobile.va.gov says in part: “The VA Health Chat App provides easy, online access to chat with VA staff when you have minor health questions and more.”  The ‘and more’ is explained on the page with examples such as schedule an appointment or refill a prescription.

**Comment by Samara-Strauss** [comment]
ALSO — for whoever works on copy — Jen Lee has instructed us to refer to the app as "VA health chat" instead of "VA Health Chat" per our VA.gov style guidelines.

**Comment by Samara-Strauss** [comment]
Also from Jen:

> On the new coronavirus Veteran FAQs page, we are referring to the chat as “health chat” and “VA health chat” or “our health chat tool.”
>  
> Try health chat (limited availability). You may be able to use our health chat if your primary VA health facility is part of the VA health chat pilot. See if you’re eligible to use health chat

**Comment by Samara-Strauss** [comment]
Consolidating copy needs here. This alert needs to include:

- Veterans can use the health chat app to ask questions related to COVID-19
- They may be talking to a variety of health care professionals. Based on convos with stakeholders, I believe the term we should use is "VA staff"
- This tool is available at "no-cost" (stakeholders were very insistent about "no-cost" vs. "free") to veterans who receive health care at the VA.
- (CTA) A link to the page to access the tool https://mobile.va.gov/app/va-health-chat

Note: This tool is only available to veterans in VISNs 8 and 23 and will only be shown to these veterans.

<img width="759" alt="My VA health chat alert" src="https://user-images.githubusercontent.com/34068740/77079298-31542900-69ce-11ea-9c75-c732251c70a8.png">

**Comment by jenniferlee-dsva** [comment]
@Samara-Strauss 

**Use health chat to get answers to your health questions**
If you have questions about COVID-19 or general health concerns, you can use our new VA health chat tool to chat with a VA staff person. It's available at no-cost to any Veteran who receives health care at VA. You can use health chat on desktop or as a mobile app.

**[Button] Learn more about VA health chat**

**Comment by Samara-Strauss** [comment]
@jenniferlee-dsva thank you for this! We JUST got additional feedback in from a stakeholder that we should mention there may be wait times — people may send a message and may not hear back instantly depending on availability of staff. Here's what she said:

> I also want to clarify that the staff we have dedicated to VA Health Chat are not also actively answering calls.  They are assigned one responsibility at a time, as to do both would lead to poor outcomes.  The point being, however, that we have X number of employees, and it is how we dedicate those resources to support Veteran access to virtual care.  If the VA Health Chat volume continues to grow, we will need to have longer chat wait times or take others off answering phones to address it.

I think we should mention this in the alert. How about something like this? I've modified your copy above to reflect wait times:

**Use health chat to get answers to your health questions**

If you have questions about COVID-19 or general health concerns, you can use our new VA health chat tool to chat with a VA staff person. Send a message to staff at your facility, and they'll get back to you when they are available. Please note that your facility may be receiving many messages and it may take them time to reply.

This tool is available at no-cost to any Veteran who receives health care at VA. You can use health chat on desktop or as a mobile app.

**[Button] Learn more about VA health chat**

**Comment by jenniferlee-dsva** [comment]
Ug. Can we not message them at the time inside the chat app if there are wait times? Why pre-message them here? Mixed signals - use it; but don't use it. Also 'get back to you when we're available' is terrible. I recommend including that note here ONLY if they cannot display it in the actual TOOL experience when (and only when) there's a wait time. If for some reason they can't do that inside the app itself, we can pre-message here, but can we move it down, say below the button - just not part of the main body of the message, so the hierarchy is clear.

**Use health chat to get answers to your health questions**

If you have questions about COVID-19 or general health concerns, you can use our new VA health chat tool to chat with a VA staff person. It's available at no-cost to any Veteran who receives health care at VA. You can use health chat on desktop or as a mobile app.

[Button] Learn more about VA health chat

**Note:** Some VA facilities may be receiving many messages, and it may take them time to reply via chat.

**Comment by tressaellen** [comment]
Here's a screenshot with the updated copy - let me know if you need any more changes.

<img width="738" alt="Screen Shot 2020-03-19 at 9 34 27 AM" src="https://user-images.githubusercontent.com/58752772/77097242-53957900-69c5-11ea-9b7f-74355c9ca5c0.png">

**Comment by jenniferlee-dsva** [comment]
^ I'm good with above. But defer to Samara for final go.

**Comment by Samara-Strauss** [comment]
@jenniferlee-dsva @tressaellen I am SO sorry for the delay — I've spent the last three hours fighting with my VA Mac. Anyway, that's just to explain my delay. We've got a couple other pieces of information that I think are relevant to this alert:

- First, we learned that we can only filter the users who see this by parent facility, but not by clinic, and [this list is a list of clinics](https://mobile.va.gov/app/va-health-chat). This is Erik's explanation from Slack, which I think helps to clarify what I'm talking about:

> So, for example, Viera VA is listed under Georgia. That is code 675GA. Our API might tell us that the veteran is a patient in 675, but there are a total of 7  facilities that fall under 675.
> 
> so given what I know now, we could show the alert if the API says they are a patient at 675. But they might be a patient at 675GD Deltona or 675GF Clermont, which are not on that list of facilities. So we could be showing the alert to patients who aren't supposed to see it

- So the TL;DR is that we need to adjust our messaging to say that some people may have access to this tool, but they should confirm if their facility is listed on this page https://mobile.va.gov/app/va-health-chat to confirm whether they have access.
- Second, we found out health chat is only covered "8 hours a day, Monday through Friday." Unclear to me if that is regular business hours or not, but I will try to track this down. So not only may people not get an immediate reply, they're only going to get a reply during business hours. This seems like a terrible experience to me, but I think they still want us to advertise this tool because it's the only alternative to jamming the phone lines. So, we should figure out how to manage this.

Given all this, how's something like this?

**Use health chat to get answers to your health questions**

If you have questions about COVID-19 or general health concerns, you may have access to the new VA health chat tool to chat with a VA staff person. It's available at no-cost to any Veteran who receive care [at these facilities](https://mobile.va.gov/app/va-health-chat). If health chat is offered at your facility, VA staff are available Monday through Friday during regular business hours. You can use health chat on desktop or as a mobile app.

[Button] Learn more about VA health chat

**Note**: Some VA facilities may be receiving many messages, and it may take them time to reply via chat.

**Comment by jenniferlee-dsva** [comment]
I've called out TBC text like the hours of availability. 

**You may be eligible to use health chat as part of our pilot**

If you have questions about COVID-19 or general health concerns, you may be able to chat with a VA staff person, on desktop or as a mobile app. Health chat is available at no-cost, `8:00 a.m. to 5:00 p.m. ET, Monday through Friday,` to any Veteran whose VA facility is part of the pilot.  

[Button] Learn more about VA health chat

Note: Some VA facilities may be receiving many messages, and it may take them time to reply via chat.

**Comment by jenniferlee-dsva** [comment]
Perhaps if the widget has the ability to display available days/hours dynamically per VISN, that could be a dynamic string of text in the alert.

**Comment by Samara-Strauss** [comment]
That's a good idea — and I did just get word that VISN 23 has different hours: 7:30 – 4:30 local time, M-F.

Let me ask Erik about this.

**Comment by Samara-Strauss** [comment]
> Perhaps if the widget has the ability to display available days/hours dynamically per VISN, that could be a dynamic string of text in the alert.

Erik confirmed that he is able to do this!

So, we should be good on copy pending any stakeholder feedback. I'm going to wait to circulate until we hear from them that they do indeed want us to advertise this to veterans. In the meantime, closing this ticket. We can reopen or open a new ticket if we need to revisit copy.

**Comment by Samara-Strauss** [comment]
Update: VISN 8 no longer wants to be part of this alert, so it will just be VISN 23. @tressaellen — can you send me a screenshot of the latest version of the alert so I can pass it along to stakeholders for approval? Also, can you please change the times in the screenshot to match VISN 23's hours? I hadn't shared them yet here, but they are 7:30 – 4:30 M – F. Thanks!

**Comment by tressaellen** [comment]
Here's the screenshot. 

<img width="740" alt="Screen Shot 2020-03-24 at 11 04 29 AM" src="https://user-images.githubusercontent.com/58752772/77466558-4e6a6c80-6dbf-11ea-8209-efad56d75b7f.png">

**Comment by Samara-Strauss** [comment]
@tressaellen can you please add "p.m." after "4:30"?

**Comment by tressaellen** [comment]
<img width="735" alt="Screen Shot 2020-03-24 at 11 24 26 AM" src="https://user-images.githubusercontent.com/58752772/77468142-10bb1300-6dc2-11ea-9f57-0e7dc4a3715a.png">

**Comment by Samara-Strauss** [comment]
Thank you! Sending this off for review.

**Comment by Samara-Strauss** [comment]
Closing. Copy was approved!
