### ISSUE TITLE
[FE] 10-10EZR - Standalone Form: QA Finding - Contact information field issues

### ISSUE THREAD

**Issue by fbonds** [department-of-veterans-affairs/va.gov-team#69778]
my-health/update-benefits-information-form-10-10ezr/veteran-information/contact-information has two field related issues (see screenshot)

Issue 1: Home phone number is a required field, but not listed as such.  It appear optional until you try continue without providing it.

Issue 2: Email address displays the regex error if improperly formatted instead of a user friendly error describing a valid email address.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHJMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b296efef8eee3b38833252083d00af5088026298/image.png)

### Expected behavior
- Issue 1 - Home phone number is optional and should not trigger an error when there is no data in the field
- Issue 2 - The error message for the Email address field should be descriptive of the actual format

**Comment by longmd** [comment]
Just a note here: The edits to the phone number fields have taken place as part of #69651 . The pending PR will address the error message in the email field.

**Comment by longmd** [comment]
@fbonds , you are free to double check this one for the Email pattern and will notify you on the other ticket when phone number is ready to be validated.

**Comment by longmd** [comment]
@fbonds , you are now also free to double check and sign off on the phone number fields.
