### ISSUE TITLE
[FE] COVID-19 My VA alert: Build alert for the dashboard

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#6977]
## Background

Epic #6974

We need to show an alert that links patients to an existing VA health chat tool on the My VA dashboard. This alert should only show for patients with access to this tool, which is currently patients that go to hospitals in VISNs 8 and 23 (VISN = Veterans Integrated Service Network = essentially a group of VA hospitals).

## Design

TBD in #6976

## Specs

- (**Pending confirmation**) This alert should only show to users that [go to these facilities](https://mobile.va.gov/app/va-health-chat).

## Tasks

- [ ] Build alert

## Acceptance criteria

- [ ] Alert is built and shows to users in at [these facilities](https://mobile.va.gov/app/va-health-chat).

**Comment by erikphansen** [comment]
@mshea0606 @Samara-Strauss This work was merged in as part of https://github.com/department-of-veterans-affairs/vets-website/issues/11952. It can be viewed on staging with test user judy.morrison@id.me. That test user will see the alert on their My My VA Dashboard with "fallback" hours of 9-5 since that user is not a patient in either VISN 8 or VISN 23, but are instead a patient in one of the special test-only facilities, 983 or 984.

**Comment by Samara-Strauss** [comment]
@erikphansen so just to confirm — for people who are actually in VISNs 8 and 23, they'll see these hours that we talked about in #6975 :

- VISN 8: 8:00 a.m. to 4:00 p.m. Monday through Friday
- VISN 23: 7:30 a.m – 4:30 p.m Monday through Friday

If so, we're good to go! We can close this an open a ticket to push to production when we're ready.

**Comment by erikphansen** [comment]
@Samara-Strauss Correct! I know you're not a coder but this is pretty clear to read I think :) https://github.com/department-of-veterans-affairs/vets-website/blob/9d09c1f5e3515735fa12256ef46c3c0467ff0310/src/applications/personalization/dashboard/covid-19.jsx#L153-L164

**Comment by Samara-Strauss** [comment]
@erikphansen back in 2012, I tried to do a javascript course on Codecademy. Needless to say, I didn't make a career switch to being a developer, BUT the one thing I learned about was if/else statements. So, proudly, I can read that code 😃 It looks great. I'm gonna close this an open a ticket/add it to the epic to launch to prod when we are ready.
