### ISSUE TITLE
ToU bug - DSLogon user auto signed out

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#69782]
Investigate why a test dslogon user is being auto logged out after accepting terms, [here is ](https://dsva.slack.com/archives/C03DY3FN7HQ/p1699624441327279?thread_ts=1696541395.629659&cid=C03DY3FN7HQ)the thread discussing it.

Check with Rachael to see if they can login normally (not through tou), if they can try to determine what about their user attributes is causing the issue here.

This may only be an issue with this specific test user, as other dslogon test users seem to work as of 1058 ET 13NOV23.

**Comment by bosawt** [comment]
@joeniquette Any reason to keep this open?
