### ISSUE TITLE
Adding Marcia Ortiz to DSVA Slack

### ISSUE THREAD

**Issue by BerniXiongA6** [department-of-veterans-affairs/va.gov-team#69790]
# Description

Please add Marcia Ortiz as a full member in DSVA Slack. She is a new Senior Product Manager (Friends From the City) and has joined the CMS Team. 

She'll require visibility into multiple channels. If we could start by adding her to this Slack channel, our team will make sure to add her to the other channels as she's getting acclimated to the team: #sitewide-cms-platform

Email: marcia@cityfriends.tech
GitHub handle: maortiz-27-80

Started on 11/7/2023. Received SAC adjudication on 11/8/2023.

Thank you!

**Comment by EWashb** [comment]
Added to slack.
