### ISSUE TITLE
Roll out keyboard user e2e test

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#6979]
As an accessibility expert on VSP, I want all teams to know about how to use the new helpers in the keyboard e2e test suite.

**Comment by 1Copenut** [comment]
@Clark-W-Griswold Adding you for visibility, and because I saw the PR was approved. 🎉 

I *also* noticed a comment change in one of the helpers, but I'll tackle that as a small, standalone PR. This one has gone on long enough, let's ship this thing.
