### ISSUE TITLE
Adding Bo Altes to DSVA Slack

### ISSUE THREAD

**Issue by HeatherRienks** [department-of-veterans-affairs/va.gov-team#69806]
Please add Bo Altes new Agile Six Product Manager on CHAMPVA team to DSVA Slack as a Full Member.

bo.altes@agile6.com

He should be added to #vfs-all-teams, #vfs-change-announcements and any other pertinent VFS general channels for new team members.

Thank you!

**Comment by HeatherRienks** [comment]
This has been completed. Thank you @pshahVA!

**Comment by pshahVA** [comment]
approved and added
