### ISSUE TITLE
SOCKS access for [William Phelps]

### ISSUE THREAD

**Issue by williamphelps13** [department-of-veterans-affairs/va.gov-team#69807]
### Your Name

William Phelps

### Your Email

will@coa.solutions

### Your Role and Team

Software Engineer on Benefits - Claims Evidence

### Product Manager (PM) name and email

Rivka Gates rivka.gates@agile6.com

### Product Owner (PO) name and email

Jessica Bertsch jennifer.bertsch@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCnsrCiEuPBInGtuWvtCwPOXBm+0MVtwOl7+DWbaCwI1DD8LU9vPpSm5UkNQt6AXn0jRPjzNhAIBYHjESxhaUq/vb5zXB3s28JJL+QTXfasrIQgIM398KBZC1aV2qxuv7m4T66GZvZGhpc31HQ16wrnloT+FkjxpFTQNPTUY9zxoHJypcOu6c7hwqVWQm18aVrRPfNrKYF+qBC1D6BZm/PyAGxsGKWkX+xfv02pZXz4/MmkGJuyJkMkj7k7X9WNvHLYnQzZMbCXzcF5eqGDWznWySdU3ovTKU7zTlNcd0bI8Fezel/xwmXRTc85mFjeEVO99jo6gyucPMrwNY0vmrZtTUOli8R+y3BNViEThzu8AOW3SBnxgQyifpPGqk7tstouq1mw+jp/CQ7GDehGH3md0f8W354sDy0tel5eHrTVM6u6rLqnn1OShkdel+fn/YxvmW6VfnXnR8suYOzrh/Yt4xJ3LWfeI5zyZIzW7Qc/VVC9HCAsLGRYDw9TsJWtMOc= williamphelps@Williams-MacBook-Pro.local

### E-QIP Transmittal Confirmation

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/22990386/a7176850-5d18-419c-a8a1-41b8888f8f16)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by flooose** [comment]
You should be good to go here.
