### ISSUE TITLE
Identify if we need to add rate limits to our endpoints

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#69818]
As we prepare for our [Privacy, Security, Infrastructure Readiness Review ](https://app.zenhub.com/workspaces/accredited-representation-management-team-64d0dc51d3e8f4788ac6ef96/issues/gh/department-of-veterans-affairs/va.gov-team/68572)there is a question of how to mitigate threats to any new endpoints.  Our solution would be to [add a rate limit to the AccreditedRepresentativesController](https://app.zenhub.com/workspaces/accredited-representation-management-team-64d0dc51d3e8f4788ac6ef96/issues/gh/department-of-veterans-affairs/va.gov-team/69679), but it seems odd that there aren't global rate limits for endpoints.  

Before we proceed with adding rate limits, this ticket is to identify if rate-limiting is setup for all valid endpoints on vets-api (through Nginx or something similar) or if we need to configure it ourselves in `config/initializers/rack_attack.rb`.

**Comment by holdenhinkle** [comment]
I chatted with Lindsey Hattamer - a senior backend engineer on platform - about this.

Then I created this ticket - https://dsva.slack.com/archives/CBU0KDSB1/p1699911661987239

**Comment by holdenhinkle** [comment]
Kyle A. Matheny
  6 minutes ago
it wouldn't hurt to throw in the traefik attributes for tuning, but i would probably keep them pretty darn high, and tune them over time


Holden Hinkle
  5 minutes ago
Okay, cool. Are there docs for doing that? Or an example?


Kyle A. Matheny
  4 minutes ago
https://doc.traefik.io/traefik/middlewares/http/ratelimit/
doc.traefik.iodoc.traefik.io
Traefik RateLimit Documentation - Traefik
Traefik Proxy's HTTP RateLimit middleware ensures Services receive fair amounts of requests. Read the technical documentation.
