### ISSUE TITLE
Adding Camron Martinez to DSVA Slack

### ISSUE THREAD

**Issue by huggins-va** [department-of-veterans-affairs/va.gov-team#69810]
Please add Camron Martinez as a multi-channel user to the following channels: 
api-benefits-claims
team-ninjapigs

Camron is onboarding team Ninja Pigs as the new APM

Thank you!
Nora

**Comment by LEHigley** [comment]
need an email address

**Comment by huggins-va** [comment]
martinez_camrom@bah.com

**Comment by LEHigley** [comment]
could only add to general
