### ISSUE TITLE
Adding Hiedi Arzomand to DSVA Slack

### ISSUE THREAD

**Issue by huggins-va** [department-of-veterans-affairs/va.gov-team#69822]
Please add Hiedi Arzomand as a multi-channel user to the following channels:
api-health
team-shanktopus

Hiedi is onboarding team Shanktopus as the new part-time SWE 

Thank you!
Nora

va email: hiedi.arzomand@va.gov
work email: arzomand_hiedi@bah.com

**Comment by LEHigley** [comment]
couldn't add to team shanktopus so just did api health

also only added va email
