### ISSUE TITLE
User flow through Form 10-10D 

### ISSUE THREAD

**Issue by rachaelpenfil** [department-of-veterans-affairs/va.gov-team#69830]
Map ideal user flow through 1010-D in [Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1699626384950/0c08ecfa00d0c8010851902152ad5d8b4d9b84e5?sender=u3844370d13a440a7859d3526).

Note any outstanding questions or comments as they arise.

Deliverable: completed user flow, with any relevant questions and notes.

Definition of done:
- Drafted user flow through 10-10D is complete in Mural.

**Comment by rachaelpenfil** [comment]
First draft of user flow has been completed, including eligibility criteria. 

As of 11/21/23, blocked: waiting for answers to stakeholder questions.

**Comment by baltes** [comment]
User flow updated in Mural

**Comment by pshahVA** [comment]
Can I see this mural?
