### ISSUE TITLE
Qualitative Data Request

### ISSUE THREAD

**Issue by lmorris3** [department-of-veterans-affairs/va.gov-team#69837]
### Data Type Requested

Support

### Date Range Start

06-01-2023

### Date Range End

10-31-2023

### Product Name(s)

Login.gov Adoption

### Product Description

Login.gov Adoption is an effort to drive adoption of modern sign in credentials, namely, Login.gov.

### Survey URL(s), key term(s), case category or type

Call center data from June, 2023 - October, 2023 to help identify any changes in traffic patterns over time, specifically of interest are the months of July and August, when our email advising of upcoming sign-in changes was sent. 

### File Delivery Format

All in one file, on one tab

### Word Cloud

Yes

### VA Email Address(es)

lauren.morris3@va.gov

### Add Assignee and Labels

If not already done so, please ensure @newworld2616 is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by newworld2616** [comment]
Good morning, could you provide me the URL so that I can pull the data. Thank you.

**Comment by lmorris3** [comment]
Hi, thanks for working on this! We're looking for the MyVA411 Call Center data between June, 2023 and Oct, 2023, so I'm not sure there is an associated url. We're looking for the number of calls and details about the reason the person called (if calls are grouped into categories or topics). Does that help?

**Comment by newworld2616** [comment]
The data should include login issues right?

**Comment by lmorris3** [comment]
Yes, it would be helpful to see that.

**Comment by newworld2616** [comment]
I have shared the data, let me know if you have any questions.

Thank you!
