### ISSUE TITLE
[Spike] Document empty/error state logic for VA Video Care at a VA location appointment

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#69847]
## Background/Request
Product and UX wants to know how VAOS is currently displaying missing data on details pages. We'll use the information to add and update those patterns in the details page redesign.

We also want to understand the field names and data calls for each data point so we can map these and align with other teams who display appointment data.

### Goal

Document the situations where VAOS doesn't display data, or displays an error state when data is missing from VA in-person appointment details pages. (This does not apply to the list view). Also, capture technical information about the data calls.

### Requirements to Consider

For each data field that can show on the details page of a **VA Video Care at a VA location appointment** please provide:
- The services or endpoints that are being called to retrieve the data.
    - The technical name of the field in the data call.
- The logic or error (if any) that triggers missing data states.
- Screenshots of the missing data states.

---

## Tasks
- Answer the following questions for each data point (noted in the table that follows):
  - What (if any) logic is in place to handle situations where the data point can’t be displayed to the user?
     - Note if logic is for an error state or other situation.
     - Please provide screenshots of the details page in each state where data is missing.
     - Please the services or endpoints that are being called to retrieve the data.
     - Please provide the field name used in the data call.

Data points to review for VA In-person booked appointments: 

- Appointment Date and Time      
- Type of Care 
- Modality                
- Provider Name  
- Facility Name             
- Facility Address                            
- Facility Phone Number          
- Veteran Reason For Appointment 

## Time Box
8 hours

## Definition of Done
- Tasks are complete
- Research and recommendations are documented in this ticket

---

**Comment by jenniemc** [comment]
### Endpoints that are being called to retrieve data:

- From appointment list: `/vaos/v2/appointments?_include=facilities,clinics&start={today-120}&end={today+1}&statuses[]=proposed&statuses[]=cancelled` and `/vaos/v2/appointments?_include=facilities,clinics&start={today-30}&end={today+395}&statuses[]=booked&statuses[]=arrived&statuses[]=fulfilled&statuses[]=cancelled`
- From appointment details page: `/vaos/v2/appointments/${id}?_include=facilities,clinics,avs`

### Technical name of the field in the data call.
Display Name | Source Field Name | Null State
--- | --- | ---
Appointment date and time |  `appt.localStartTime`  |   start time is alway populated
Type of care |    `appt.serviceType`  |   if null, do not display anything
Modality | N/A |  N/A
Provider name |  `appt.practitioners[0].name.given, family`  |  if null, do not display anything
Facility name | `appt.location.attributes.name`  or  `facilityData[locationId].name`  |    if null, display “Facility details not available” and a link to "Find facility information" 
Facility address  |  `appt.location.attributes.physicalAddress` or  `facilityData[locationId].address`  |    if null, display “Facility details not available” and a link to "Find facility information" 
Clinic Name | `appt.extension.friendlyName` or `appt.extension.serviceName`  |  if null, display "Not Available"
Clinic Location | `appt.physicalLocation` |   if null, display "Not Available"
Facility phone number | `appt.extension.clinic.phoneNumber` or `appt.location.attributes.phone.main` or `facilityData[locationId].telecom[0]value`  |  The priority order is (1) Clinic phone with extension then (2) Facility phone. If neither of the numbers are available then display the VA Main phone `800-698-2411`
Veteran reason for appointment | N/A | N/A

_NOTE:_
Modality are not returned in the confirmed appointments. Modality are only returned for VA requests.
Veteran reason for appointment are not return for telehealth appointments

### Example JSON appointment object returned from API call
```
{
    "id": "001",
    "type": "Appointment",
    "attributes": {
        "locationId": "983",
        "localStartTime": "2025-09-22T09:00:00.000-06:00",
        "physicalLocation": "PHYSICAL LOCATION TESTING",
        "practitioners": [
            {
                "name": {
                    "family": "VALOCATION",
                    "given": [
                        "VIDEO"
                    ]
                }
            }
        ],
        "serviceType": "foodAndNutrition",
        "status": "booked",
        "telehealth": {
            "atlas": null,
            "vvsKind": "CLINIC_BASED"
        },
        "extension": {
            "patientHasMobileGfe": true,
            "clinic": {
                "physicalLocation": "PHYSICAL LOCATION TESTING",
                "phoneNumber": "500-500-5000",
                "phoneNumberExtension": "1234"
            }
        }
    }
}
```
### Screenshots of the missing data states
Full State | Empty Type of care, Provider name, Clinic name, Clinic location | Empty Type of care, Provider name and Facility information
--- | --- | ---
 ![Image](https://github.com/user-attachments/assets/10258f05-a2bb-4541-94ff-f94ef3e2789e)     |    ![Image](https://github.com/user-attachments/assets/47e3a0dd-9885-459e-83f5-875234eee57c)   |  ![Image](https://github.com/user-attachments/assets/e6051c89-83a9-476d-82af-efc1ce2da87f)

**Comment by jenniemc** [comment]
@outerpress , Ready for validation

**Comment by jenniemc** [comment]
@outerpress, Modality is updated. Ready for validation

**Comment by outerpress** [comment]
Validated, thanks @jenniemc ! You can feel free to close

**Comment by outerpress** [comment]
Oh, and I documented this info [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/feature-reference/appointment-types/va-video-care-at-a-va-location.md#empty-states-and-alerts)

**Comment by jenniemc** [comment]
Validated and documented. Closed ticket.
