### ISSUE TITLE
[Spike] Document empty/error state logic for VA Video Care at home appointment

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#69846]
## Background/Request
Product and UX wants to know how VAOS is currently displaying missing data on details pages. We'll use the information to add and update those patterns in the details page redesign.

We also want to understand the field names and data calls for each data point so we can map these and align with other teams who display appointment data.

### Goal

Document the situations where VAOS doesn't display data, or displays an error state when data is missing from VA in-person appointment details pages. (This does not apply to the list view). Also, capture technical information about the data calls.

### Requirements to Consider

For each data field that can show on the details page of a **VA Video Care at home appointment** please provide:
- The services or endpoints that are being called to retrieve the data.
    - The technical name of the field in the data call.
- The logic or error (if any) that triggers missing data states.
- Screenshots of the missing data states.

---

## Tasks
- Answer the following questions for each data point (noted in the table that follows):
  - What (if any) logic is in place to handle situations where the data point can’t be displayed to the user?
     - Note if logic is for an error state or other situation.
     - Please provide screenshots of the details page in each state where data is missing.
     - Please the services or endpoints that are being called to retrieve the data.
     - Please provide the field name used in the data call.

Data points to review for VA In-person booked appointments: 

- Appointment Date and Time      
- Type of Care 
- Modality                
- Link to Join URL
- Provider Name                  
- Facility Address                            
- Facility Phone Number          
- Veteran Reason For Appointment 

## Time Box
8 hours

## Definition of Done
- Tasks are complete
- Research and recommendations are documented in this ticket

---

**Comment by JunTaoLuo** [comment]
We retrieve the appointment information using one of the following calls:

- From appointment list: `/vaos/v2/appointments?_include=facilities,clinics&start={today-120}&end={today+1}&statuses[]=proposed&statuses[]=cancelled` and `/vaos/v2/appointments?_include=facilities,clinics&start={today-30}&end={today+395}&statuses[]=booked&statuses[]=arrived&statuses[]=fulfilled&statuses[]=cancelled`
- From appointment details page: `/vaos/v2/appointments/${id}?_include=facilities,clinics,avs`

Data points:

| Role | Section name | Source field name | Empty state logic |
| - | - | - | - |
| Link to Join URL | How to join | `appt.telehealth.url` | This link is only displayed for upcoming appointments from 30 minutes before the start time to 4 hours afterwards. If this is unavailable, it will display "Please contact your facility for help joining this appointment." along with the facility or clinic phone number. |
| Preferred date and time | When | `appt.localStartTime` | Start time always populated |
| Type of Care | What | `appt.serviceType` | Do not display if not available |
| Provider Name | Who | appt.practitioners[0].name | Do not display if not available |
| Facility Name | Need to make changes/Scheduling Facility | `facilityData[locationId].name` or `appt.location.attributes.name` | For upcoming appointments, display "Facility not available" if not available. For past/cancelled appointments, do not display if not available. The heading is "Need to make changes" for upcoming appointments and "Scheduling Facility" for past/cancelled appointments |
| Facility Address | Need to make changes/Scheduling Facility | `facilityData[locationId].physicalAddress` or `appt.location.attributes.physicalAddress` | For upcoming appointments, display "Facility not available" if not available. For past/cancelled appointments, do not display if not available. The heading is "Need to make changes" for upcoming appointments and "Scheduling Facility" for past/cancelled appointments |
| Clinic Name | Need to make changes/Scheduling Facility | `appt.friendlyName` or `appt.serviceName` | Display "Clinic not available" if not available. The heading is "Need to make changes" for upcoming appointments and "Scheduling Facility" for past/cancelled appointments |
| Phone number | Need to make changes/Scheduling Facility | `facilityData[locationId].phone.main` or `appt.location.attributes.phone.main` or `appt.extension.clinic.phoneNumber` | Phone number priority: 1. Clinic phone number, 2. Facility phone number, 3. VA phone number. The heading is "Need to make changes" for upcoming appointments and "Scheduling Facility" for past/cancelled appointments |

Note that we don't display "Modality" and "Veteran Reason For Appointment". These may have become obsolete after this ticket was filed. There are also a few other details we do display that weren't covered in the original ticket including "Facility Name" and "Clinic Name"
 
 
### Screenshots

| Upcoming | Past | Cancelled | Empty state | 
| - | - | - | - | 
| ![Image](https://github.com/user-attachments/assets/82000d01-b302-43af-baf6-6fa90bbd13b2) | ![Image](https://github.com/user-attachments/assets/abf301f0-d63b-4da5-a91a-56cf94f29a32) | ![Image](https://github.com/user-attachments/assets/bdb03047-ac5d-496a-8425-d40c277d4ffa) | ![Image](https://github.com/user-attachments/assets/9bd1cf45-5681-4591-9ec0-fca59aeac0ce) |

**Comment by outerpress** [comment]
UX team will review

**Comment by outerpress** [comment]
@JunTaoLuo @JRRoof I added this info to the[ feature reference](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/feature-reference/appointment-types/va-video-care-at-home.md), this spike is good to go

**Comment by JunTaoLuo** [comment]
Sounds like Jeff delegated the power of closing tickets after tickets have been validated so I'm closing this one 😄 .
