### ISSUE TITLE
Form 10-10D Prototype draft - Jamie Fiore

### ISSUE THREAD

**Issue by rachaelpenfil** [department-of-veterans-affairs/va.gov-team#69842]
BLOCKED until we have Figma access.

Deliverable:
- Figma prototype
- Prep work for prototype - get environment set up
- Identify a "template" from existing forms
- "Site map" style

Definition of done:
- Environment is set up
- Map out "breaks" in the form

**Comment by baltes** [comment]
Closed as duplicate
