### ISSUE TITLE
Begin content design and language simplification - Jamie Fiore

### ISSUE THREAD

**Issue by rachaelpenfil** [department-of-veterans-affairs/va.gov-team#69843]
If we're not able to get access to Figma, we will use va.gov's content design system to simplify language in Form 10-10D.

**Comment by baltes** [comment]
@jamiefiore @rachaelpenfil Proposing that we close this and create a new issue for any specifics that need to be worked on.

@dhill802

**Comment by rachaelpenfil** [comment]
@baltes I think that makes sense. This is on pause anyway.
