### ISSUE TITLE
[Spike] Document empty/error state logic for Claim exam appointment

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#69854]
## Background/Request
Product and UX wants to know how VAOS is currently displaying missing data on details pages. We'll use the information to add and update those patterns in the details page redesign.

We also want to understand the field names and data calls for each data point so we can map these and align with other teams who display appointment data.

### Goal

Document the situations where VAOS doesn't display data, or displays an error state when data is missing from VA in-person appointment details pages. (This does not apply to the list view). Also, capture technical information about the data calls.

### Requirements to Consider

For each data field that can show on the details page of a **Claim exam appointment** please provide:
- The services or endpoints that are being called to retrieve the data.
    - The technical name of the field in the data call.
- The logic or error (if any) that triggers missing data states.
- Screenshots of the missing data states.

---

## Tasks
- Answer the following questions for each data point (noted in the table that follows):
  - What (if any) logic is in place to handle situations where the data point can’t be displayed to the user?
     - Note if logic is for an error state or other situation.
     - Please provide screenshots of the details page in each state where data is missing.
     - Please the services or endpoints that are being called to retrieve the data.
     - Please provide the field name used in the data call.

Data points to review for VA In-person booked appointments: 

- Appointment Date and Time      
- Type of Care  
- Facility Name
- Facility Address
- Clinic Name
- Facility Phone Number          

## Time Box
8 hours

## Definition of Done
- Tasks are complete
- Research and recommendations are documented in this ticket

---

**Comment by JunTaoLuo** [comment]
We retrieve the appointment information using one of the following calls:

- From appointment list: `/vaos/v2/appointments?_include=facilities,clinics&start={today-120}&end={today+1}&statuses[]=proposed&statuses[]=cancelled` and `/vaos/v2/appointments?_include=facilities,clinics&start={today-30}&end={today+395}&statuses[]=booked&statuses[]=arrived&statuses[]=fulfilled&statuses[]=cancelled`
- From appointment details page: `/vaos/v2/appointments/${id}?_include=facilities,clinics,avs`

Data points:

| Role | Section name | Source field name | Empty state logic |
| - | - | - | - |
| Preferred date and time | When | `appt.localStartTime` | Start time always populated |
| Type of Care | What | `vaos.apiData.serviceCategory.[first].text` | Do not display if not available. Note that the field on the appointment will return `COMPENSATION & PENSION` which is translated into the friendly name "Claim exam" in the source code |
| Provider Name | Who | `appt.practitioners[0].name` | Do not display if not available |
| Facility Name | Where to attend/Where/Scheduling Facility | `facilityData[locationId].name` or `appt.location.attributes.name` | The heading is "Where to attend" for upcoming appointments and "Where" for past/cancelled appointments. A potential duplicate "Scheduling Facility" section is also displayed for past/cancelled appointments. When not available, display "Facility details not available" and display a link to find or view facility information. |
| Facility Address | Where to attend/Where | `facilityData[locationId].physicalAddress` or `appt.location.attributes.physicalAddress` | The heading is "Where to attend" for upcoming appointments and "Where" for past/cancelled appointments. When not available, display "Facility details not available" and display a link to find or view facility information. |
| Clinic Name | Where to attend/Where | `appt.friendlyName` or `appt.serviceName` | Display "Clinic not available" if not available. The heading is "Where to attend" for upcoming appointments and "Where" for past/cancelled appointments |
| Phone number | Need to make changes/Scheduling Facility/Where/Where to attend | `facilityData[locationId].phone.main` or `appt.location.attributes.phone.main` or `appt.extension.clinic.phoneNumber` | Phone number priority: 1. Clinic phone number, 2. Facility phone number, 3. VA phone number. The heading is "Need to make changes" and "Where to attend" for upcoming appointments and "Where" and "Scheduling facility" for past/cancelled appointments. This seems odd and maybe we need to remove some duplicates here. |
 
 
### Screenshots

| Upcoming | Past | Cancelled | Empty state | 
| - | - | - | - | 
|  |  |  |  |

**Comment by JunTaoLuo** [comment]
This is ready for UX review @outerpress

**Comment by outerpress** [comment]
This is validated and captured in the feature reference [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/feature-reference/appointment-types/claim-exam.md#empty-states-and-alerts) @juntaoluo , thanks!
