### ISSUE TITLE
[Spike] Document empty/error state logic for VA Video Care at an ATLAS location appointment

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#69850]
## Background/Request
Product and UX wants to know how VAOS is currently displaying missing data on details pages. We'll use the information to add and update those patterns in the details page redesign.

We also want to understand the field names and data calls for each data point so we can map these and align with other teams who display appointment data.

### Goal

Document the situations where VAOS doesn't display data, or displays an error state when data is missing from VA in-person appointment details pages. (This does not apply to the list view). Also, capture technical information about the data calls.

### Requirements to Consider

For each data field that can show on the details page of a **VA Video Care at an ATLAS location appointment** please provide:
- The services or endpoints that are being called to retrieve the data.
    - The technical name of the field in the data call.
- The logic or error (if any) that triggers missing data states.
- Screenshots of the missing data states.

---

## Tasks
- Answer the following questions for each data point (noted in the table that follows):
  - What (if any) logic is in place to handle situations where the data point can’t be displayed to the user?
     - Note if logic is for an error state or other situation.
     - Please provide screenshots of the details page in each state where data is missing.
     - Please the services or endpoints that are being called to retrieve the data.
     - Please provide the field name used in the data call.

Data points to review for VA In-person booked appointments: 

- Appointment Date and Time      
- Type of Care 
- Modality                
- Provider Name  
- ATLAS Location Name             
- ATLAS Location Address                            
- Appointment Code
- Facility Phone Number          
- Veteran Reason For Appointment 

## Time Box
8 hours

## Definition of Done
- Tasks are complete
- Research and recommendations are documented in this ticket

---

**Comment by JunTaoLuo** [comment]
We retrieve the appointment information using one of the following calls:

- From appointment list: `/vaos/v2/appointments?_include=facilities,clinics&start={today-120}&end={today+1}&statuses[]=proposed&statuses[]=cancelled` and `/vaos/v2/appointments?_include=facilities,clinics&start={today-30}&end={today+395}&statuses[]=booked&statuses[]=arrived&statuses[]=fulfilled&statuses[]=cancelled`
- From appointment details page: `/vaos/v2/appointments/${id}?_include=facilities,clinics,avs`

Data points:

| Role | Section name | Source field name | Empty state logic |
| - | - | - | - |
| Appointment Code | How to join | `appt.telehealth.atlas.confirmationCode` | Confirmation code always populated for this type of appointment |
| Preferred date and time | When | `appt.localStartTime` | Start time always populated |
| Type of Care | What | `appt.serviceType` | Do not display if not available |
| Provider Name | Who | `appt.practitioners[0].name` | Do not display if not available |
| ATLAS Location | Where to attend/Where | `appt.telehealth.address` | Do not display if not available. The heading is "Where to attend" for upcoming appointments and "Where" for past/cancelled appointments |
| Facility Name | Need to make changes/Scheduling Facility | `facilityData[locationId].name` or `appt.location.attributes.name` | For upcoming appointments, do not display if not available. For past/cancelled appointments, display "Facility details not available" and link to "Find facility information" if not available. The heading is "Need to make changes" for upcoming appointments and "Scheduling Facility" for past/cancelled appointments |
| Facility Address | Need to make changes | `facilityData[locationId].physicalAddress` or `appt.location.attributes.physicalAddress` | Display "Facility not available" if not available. This section is only displayed for upcoming appointments |
| Clinic Name | Need to make changes | `appt.friendlyName` or `appt.serviceName` | Display "Clinic not available" if not available. This section is only displayed for upcoming appointments |
| Phone number | Need to make changes/Scheduling Facility | `facilityData[locationId].phone.main` or `appt.location.attributes.phone.main` or `appt.extension.clinic.phoneNumber/phoneNumberExtension` | Phone number priority: 1. Clinic phone number, 2. Facility phone number, 3. VA phone number. The heading is "Need to make changes" for upcoming appointments and "Scheduling Facility" for past/cancelled appointments |

Note that we don't display "Modality" and "Veteran Reason For Appointment". These may have become obsolete after this ticket was filed. There are also a few other details we do display that weren't covered in the original ticket including "Facility Name" and "Clinic Name"
 
 
### Screenshots

| Upcoming | Past | Cancelled | Empty state | 
| - | - | - | - | 
| ![Image](https://github.com/user-attachments/assets/894570b3-ac69-4adc-b89f-1bd5e8e076ab) | ![Image](https://github.com/user-attachments/assets/707c70b1-de0f-4c21-8925-1bf45488a0fe) | ![Image](https://github.com/user-attachments/assets/8db098b9-b9b8-46e5-8115-9049f2943f0c) |   |

**Comment by ldelacosta** [comment]
@outerpress - this ticket is ready for you to review.

**Comment by outerpress** [comment]
Documented in our feature reference [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/feature-reference/appointment-types/va-video-care-at-atlas-location.md#empty-states) @ldelacosta

**Comment by ldelacosta** [comment]
No additional analysis needed. Closing out the ticket.
