### ISSUE TITLE
[CAIA Intake] Disability Benefits - Employee Experience Team: 21-526EZ, Max CFI - CAIA Support Request

### ISSUE THREAD

**Issue by carodew** [department-of-veterans-affairs/va.gov-team#69856]
## About your team

- Team name: Disability benefits employee experience 
-	OCTO-DE product owner: @jenniferbertsch 
-	Product manager: @amylai-nava 
-	Designer: @carodew @KimLadin @ChristineRoseSteiffer 
- Accessibility specialist: 
- Content writer: @carodew 
-	Slack channel: #benefits-employee-experience-design
 
### Describe what you need in a few sentences: 

We are working on an intervention to help dissuade Veterans from applying for to increase benefits (A claim for increase, or CFI) for tinnitus when they are already receiving the maximum amount of benefits. We have a few specific requests for the CAIA team: 

1. In our design concept, we have an additional page, outside of the online 526 flow, that provides more information about what it means to submit a CFI when you're already at the maximum. We need help figuring out where this page should live in the information architecture of va.gov, as well as best practices for having people access this information from within the 526 flow). 
2. We would like some review of the content of this more info page for consistency with style guide. It's worth noting that this tested well in our discovery research, so we would want to balance any new changes with what seemed to work for users. 
3. (potentially) accessibility assistance on modifications to a checkbox tile to allow us to show the a link to the new information within the tile. 
</br>

### Which are you doing?
- [ ] **Launching a new** page, tool, form, or app
- [X] **Making changes** to an existing page, tool, form, or app

### Types of Support
What areas does your team need support in? Check all that apply.
#### Content
- [ ] Collaboration on content written by your team’s dedicated content writer 
- [X] Collaboration on content if your team does not have a dedicated content writer
#### Accessibility
- [x] Accessibility review of wireframes and/or prototypes
- [ ] Accessibility issue (general request)
- [ ] Accessibility PDF review request
- [X] Accessibility user research support ([submit a separate, additional request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name)) 
    - [x] #69999 **Created**
        - [x] Research Ticket `Started` c/o @sara-amanda 
        - [ ] Update this ticket as time allows (see task list in ticket)
- [ ] DST component or pattern 
- [ ] Something else 
#### IA
- [X] User Flows
- [X] Page placement
- [X] URLs
- [ ] Breadcrumbs and Left Nav placement
- [ ] Redirects
#### Multilingual content
- [ ] Translating content
 
## Timeframe
_We guide and work alongside teams across nearly every OCTO digital product. We also work with partners across VA to lead content migration and manage all unauthenticated content on VA.gov. And we're always working to expand the VA.gov content style guide and our IA and accessibility documentation. We need to prioritize all intake requests based on our overall workload and VA and OCTO priorities._

_Tell us about your product's timeline. And we'll work with you to meet timeline needs as best we can._

### Have you worked with CAIA before? 
  - [ ] Yes
  - [X] No (Caveat: I got ad hoc content feedback via office hours, but have not had anything more extensive) 

### What's your team’s next step and its timing?

- **Our next step is** to finalize our designs for usability testing in CodePen, including people who use AT
- **Provide date if available**: January 29th - Feb 2nd

#### Timing for your next step: 
  - [X] Next week
  - [X] This month
  - [X] Next month
  - [ ] This quarter
  - [ ] Next quarter
  - [ ] 6 months
  - [ ] 1 year

### Is this timing related to a specific event or Congressionally mandated deadline?
  - [ ] Yes
  - [X] No

### If you're conducting research, when is that starting? 
**Provide date if available: 
  - [ ] Next week
  - [x] This month
  - [ ] Next month
  - [ ] This quarter
  - [ ] Next quarter
  - [ ] 6 months
  - [ ] 1 year

### Will you release this new product incrementally (for example, release to 25% of users to start)? 
  - [X] Yes
  - [ ] No
 
**Note**: _If you checked yes, we’ll reach out to discuss details about the content in the react widget (we use these widgets to display entry points for new products to a certain percentage of users who visit our static pages)._

  
### When do you expect to launch your product to 100% of users?
  
*Please provide an estimated date so our team can create other relevant tickets.*
- **We expect to launch our product to 100% of users on:** TBD
  
### Will this work be going through the Collaboration Cycle?
- [X] Yes 
- [ ] No

 
#### Please provide the link to your Collaboration Cycle ticket: 
- **Ticket (number)**: #69299
- **Collab. Cycle Ticket Opened (date)**: 11/06/2023
 
#### Please check all of the phases in the Collaboration Cycle you have completed: 
- [X] Design Intent `Tuesday, November 14, 2023 at 3:30PM ET`
- [x] Midpoint Review `Friday, January 19, 2024 at 11:30AM ET`
- [ ] Staging
 
##### Design Intent
- [ ] Accessibility
- [ ] Content
- [ ] IA
- [ ] Translation
- [X] Already completed, no assistance needed
- [ ] Unknown at this time
##### Midpoint
- [X] Accessibility
- [X] Content
- [X] IA
- [ ] Translation
- [ ] Already completed, no assistance needed
- [ ] Unknown at this time
##### Staging
- [ ] Accessibility
- [ ] Content
- [ ] IA
- [ ] Translation
- [ ] Already completed, no assistance needed
- [X] Unknown at this time
  
## Supporting artifacts
*Please provide links to supporting artifacts as available.*
- **Product outline**: [Sharepoint](https://dvagov.sharepoint.com/:w:/s/vaabdvro/EfmEWJOyv2JGmv6KIuooApABES5611G3_SHkuIWR4JumRA?e=ezeWOW) 
- **User flows**: https://sketch.com/s/4319cad9-d81b-4b8e-8339-d4150fbd5274 (Page: Platform team feedback) 
- **Prototype or mockups**: [Codepen](https://codepen.io/team/a6it/live/KKEMGGE)
- **If this is in Sketch, which version or specific page should we focus on?** (Page: Platform team feedback) 
- **Content source of truth**: Codepen
- **Research plan:** [Github link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/abd-vro/2024-01-Max-CFI-Refinements/2024-01-Max-CFI-Refinements-Research-Plan.md)
- **Conversation Guide:** [GitHub link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/abd-vro/2024-01-Max-CFI-Refinements/2024-01-Max-CFI-Refinements-Conversation-Guide.md)
- **Previous research synthesis** https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1698183162672/82f141d730ea00f0c984bbf41cc3efe1d7867827?sender=carolyn1198
- **Any epics/issues that may be helpful**: 
- **Link to testing accounts** (please do not paste them in this ticket): 

### Have you already worked with someone from OCTO leadership?
- [ ] Danielle
- [X] Beth (briefly via office hours) 
- [ ] Mikki
- [ ] Martha

### How do you plan to work with us on this request?
- [ ] I’ll take this to Beth or Danielle’s office hours.
- [ ] I’d like to schedule time to talk about this.
- [ ] Let’s work async and meet as needed.
- [X] Schedule a kick-off call with your team and CAIA for your project **(Recommended)**

 
### Accessibility Help in Slack
The [#accessibility-help channel](https://dsva.slack.com/archives/C8E985R32) in the DSVA Slack, is also available to you as a resource. Everyone is welcome to ask questions or get help from our a11y (accessibility) specialists. Tag `@Terry Nichols` to get a11y help asap.

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag `@Terry Nichols`.**

- If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
- If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jennymayoco%2C+kristinoletmuskat%2C+strelichl%2C+FranECross&labels=sitewide+CAIA%2C+Sitewide+IA%2C+Public+Websites%2C+VA.gov+frontend%2C+Redirect+request&projects=&template=redirect-request.md&title=Redirect+Request)
 
 - If you are creating an [experimental design,](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) please [also contact the DST. ](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)

- If you are requesting [a11y support for user research,](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name) please complete this form, next. 

## Kick off meeting recording
[Recording Link](https://coformaco.zoom.us/rec/share/98UU1Grc6e6YqF8uFGBhvE2ks513RBbYIulL8-zqWhM4sIuBwEvEyuRRWmm6Lnzs.IMq4FNNjnJBlU0ZH) 11/29
Passcode: +yIFnX6v)

[Follow up meeting](https://coformaco.zoom.us/rec/share/SMjDd49CW_dMk4oCx2wCY0UNYJPOQ6cSYIbAbiYdF59xZJgsJ08k8pmyAbexScKu.voI758Ug13usFrVd) 12/6
Passcode: YLU*T96e

```[tasklist]
### CAIA Ops Tasks
- [x] **Schedule Disability Benefits** - Employee Experience Team `21-526EZ` Kickoff Call (@coforma-terry or @strelichl ) KO Scheduled by Terry for: Wednesday, November 29: 12:45PM – 1PM
- [x] **Pre-Kickoff Meeting:** [hold] Pre-kickoff: Disability Benefits - 526EZ on Wed., Nov. 29, from 11:30am – 12:00pm
- [x] Kickoff [Internal CAIA Notes](https://docs.google.com/document/d/1XM7ETNmg2VfDIQclTyxJUctIhmyZry4_w3icS1nGkIE/edit#heading=h.yjn5gwt2wdmh)
- [ ] **Kickoff Deliverable Started** by @sara-amanda - [Deliverable Needs Completed](https://github.com/department-of-veterans-affairs/va.gov-team/edit/master/teams/CAIA/meeting-notes/2023-11-Kickoff-Meeting-Notes-Disability-Benefits-Employee-Experience-Team-21-526EZ-MAX-CFI.md) @coforma-terry or @strelichl `TBD - may just add notes to ticket`
- [x] Kickoff Follow-Up Call 12/6/2023 (Wednesday) at 1:30 p.m. ET - scheduled on 11/30/2023 by @coforma-terry
```

```[tasklist]
### a11y Tasks
- [x] [a11y attend meeting] CAIA Kickoff Call `11/29/2023 12:45 PM-1:00 PM EST` @strelichl
- [x] [a11y attend meeting] CAIA Kickoff Follow-Up Call `12/6/2023 1:30 PM-1:00 PM EST`
- [x] **Reach out** via slack channel [#benefits-employee-experience-design](https://join.slack.com/share/enQtNjE4NTgzNzMyOTU3NS05ZDBhMGY0OGQ3ODI1OTUyZjZmMTAwYmI0Y2E2NjM0ZDU0YzQ5M2Y4ZDFiY2Y0NzVmM2MzZDUwZDdiNjhjOWMz) (FYI - it appears to be #benefits-employee-exp-design) to partner on midpoint and staging prep.
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/74019
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/69999
- [ ] [a11y Support] Disability Benefits Employee Experience: **Midpoint Review Prep**
- [ ] [a11y Support] Disability Benefits Employee Experience: **Staging Review Prep**
- [ ] [a11y Support] Disability Benefits Employee Experience: **Share Feedback**
- [ ] [a11y attend meeting] Disability Benefits Employee Experience: **Watch Design Intent** [Design Intent recording link](https://oddball-io.zoom.us/rec/share/usaUDAoY_M4Fb7_QnBCFqjN_e02puu89ENHEAEGSo1q-VFMicxkolh7KB1gATqCo.wC1oqXFGNB7D_Y51); Passcode: `$6#7E=1i` **Zoom Meeting:** Tuesday, November 14, 2023 at 3:30PM ET
- [ ] [a11y attend meeting] Disability Benefits Employee Experience: **Watch Midpoint**
```

```[tasklist]
### IA Tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/70750
- [ ] [IA Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1701808829216/178998265b5996341a48a0b7c499292188b223fb?sender=u9e99e829c39911c821b39988)
```

```[tasklist]
### Content tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/71240
```

**Comment by coforma-terry** [comment]
Tagging @aprocik1 and @katherine-fung for visibility. Let's make sure to include them on any syncs also :)
Thanks!

**Comment by carodew** [comment]
Do you have content already drafted in a Google or Word document?
* Nope, we wrote it all in Sketch (For better or worse) 
When content will be ready: 
* I'm hoping we'll have a more final decision on what version we're going with later today, but I suspect it will be Option C: Link to external page
Ideal date for content recommendations: 
* Will get back to you on this!

**Comment by ChristineRoseSteiffer** [comment]
Hi @aprocik1! A quick update/request from our team for the content recommendations - could you have edits back to us by EOD Wednesday, December 13th? We have a stakeholder meeting the next day and we'd love to present those recommendations to them to get feedback. Let us know if that will work - thanks!

**Comment by aprocik1** [comment]
@carodew and @ChristineRoseSteiffer, thanks for following up. We'll try our best to offer content recommendations by EOD 12/13. That deadline may depend on a couple clarifying questions we plan to ask in tomorrow's kickoff follow up meeting. I can't make it, but @katherine-fung will be there to discuss.

**Comment by carodew** [comment]
Hi all, I noticed some confusion about what parts of the sketch file we're focusing on, _and_ the Sketch file has a new page (since the time I created this ticket) that's probably the best source of truth. Please look at the page "Platform team feedback" – and specifically the callouts for CAIA in purple. Apologies for any confusion (I had hoped to go over this in our kick off meeting but we ran out of time!)

**Comment by kristinoletmuskat** [comment]
Here's the link to the IA thinking mural: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1701808829216/178998265b5996341a48a0b7c499292188b223fb?sender=ua67f17f1c416a96ea04d2476

The next step for this is to add the official recommendations into github, which I'll put in this ticket. Then, after usability testing and once we're getting ready for launch, the content team will work to implement the crosslinks and inform relevant stakeholders for those pages about the addition of crosslinks. 

Note: regardless of if we go with option A, B, or C in the sketch for the final design, we'll likely still want a resources and support page on max schedular ratings, so we can link to it from other pages. lmk if anyone has questions or disagrees!

**Comment by kristinoletmuskat** [comment]
And here is the link to the [IA spec doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/max-schedular-rating-526.md) (our official documentation in github for the plan).

We can update this with more info after user research!

**Comment by kristinoletmuskat** [comment]
Closing because this initiative went through staging
