### ISSUE TITLE
AWS access for Evan Smith

### ISSUE THREAD

**Issue by evansmith** [department-of-veterans-affairs/va.gov-team#69878]
### COR Name

Jennifer O'Day

### Vendor Onboarding Representative Name

Other - please specify in 'Additional Notes'

### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Evan Smith

### Your Email

evan.smith@oddball.io

### Team, Role, and Company of the target individual

Benefits and Claim Dependents Exp, Software Engineer, Oddball

### Product Manager (PM) name and email

Austin Price austin.price@coforma.io

### Product Owner (PO) name and email

Matt Self Matthew.Self2@va.gov

### Desired AWS Access

I am on the VA Benefits team and will be making features and bugfixes, along with investigating issues, to the vets-api and vets-website repos.

I need access to debug and investigate issues in those environments, and also need all permissions needed to develop on the platform.

Access requested should be ongoing as issues that need resolved/debugged could come and go at anytime.

I also need access for when I am filling in for @tblackwe in case I need to run re-submissions for PDFs.

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/1820743/8dd2b527-54b9-4cb9-a339-44a5e5852a61)

### Additional Notes

VOR: Jeff Langworthy [jeff.langworthy@coforma.io](mailto:jeff.langworthy@coforma.io)

Updated issue from: https://github.com/department-of-veterans-affairs/va.gov-team/issues/60174

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by JonathanKamensDVA** [comment]
Need clarification: is production access being requested here? That's not stated explicitly anywhere. I also don't see an explicit explanation for why it would be needed, though reading between the lines, I'm guessing that perhaps "investigating issues... in those environments" is referring to production. Please clarify? Thanks.

**Comment by evansmith** [comment]
@JonathanKamensDVA Apologies, I am requesting production access. There are re-submissions for PDFs that I could sometimes run if @tblackwe is out of office.

**Comment by JonathanKamensDVA** [comment]
Approved.

**Comment by ph-One** [comment]
@evansmith I've elevated your privs to meet the needs of your request / tasks. Please open a new ticket if you need further modifications
