### ISSUE TITLE
[MVP] Step 3: Create new page and fields for Previous employment

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#69871]
## Note
Part of the larger effort to update the existing 527EZ form to add missing fields/info and remove depreciated fields.

## Description
On Step 3, Health and employment information,
create new page for Previous employment,
as shown on the designs.

## User Story
As a veteran under 65 years old who is not currently employed  seeking a pension benefit, I aim to input my most recent job(s) to furnish comprehensive evidence for an upfront evaluation of my claim.

##Screen Flow
https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/bLKDloo

## Task Prototype 
Form 527 - Step 3 of 7 - Health and Employment Prototype / Medical Care / Current Employment:
https://sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/vRrj4zn/play

## Step Prototype
Form 527 - Step 3 of 7 - Health and Employment Prototype: https://sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/L4Mpad5/play

## Acceptance Criteria
**Validation scenarios**
If the user answers "No" to Are you currently employed (*Required)?
they will see the following new page/question:

**New page:**
On the new page, the required date and short open text fields:

`When did you last work? (*Required)`
_Month/Day/Year format_

`What kind of work did you do? (*Required)`
_Short-open field text answer_

`How many hours per week did you average? (*Required)`
_Short-open field text answer_

`What was your job title? (*Required)`
_Short-open field text answer_

**Match copy:**
_Ensure all copy, including headers, questions wording and buttons match the designs._

## Tasks
- [x] Front-end work

## Review
- [x] Content/spelling/field validation was reviewed and signed off on pages in staging

## Artifacts
- [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/527EZ-reactivation-initiative-brief.md)
- [User flow in Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683826730324/61b509f935adaa2acf2f7769a5ba911726a7b237?sender=u9d01ee38af217e4877e75660)
- [Prototypes in Sketch](https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/p/988EBB71-6E9D-4099-A2BC-4BB61551E38F/canvas)
- [Spreadsheet of deleted form fields](https://docs.google.com/spreadsheets/d/1PTXxO6mFH2ZUK6XxX7iCCQb-NoSvhB5P/edit?usp=sharing&ouid=104362113771391164792&rtpof=true&sd=true)
- [Content source of truth/PDF form](https://www.vba.va.gov/pubs/forms/VBA-21P-527EZ-ARE.pdf)
- [Link to testing accounts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/form-deactivation/527EZ-staging-test-accounts-accessible.md)
- [Link to staging](https://staging.va.gov/)

**Comment by aplatt-coforma** [comment]
New fields are present
<img width="559" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmsxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--90e9a50630463ad2c15734d218dcb9657a4e6804/Previous%20Employment.png" alt="Previous Employment.png" />
Able to add additional previous employment.
<img width="530" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnMxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--56b95c9946a48ab31e599d000f0f1c76e2852ad6/Additional%20Previous%20employment.png" alt="Additional Previous employment.png" />
Required error
<img width="553" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNncxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8679cfe2e5d6cd0129ec0c0f007a41676d287636/Require%20fields.png" alt="Require fields.png" />

**Comment by aplatt-coforma** [comment]
Closing as complete
