### ISSUE TITLE
Look into issues with the scheduling tool not being able to initiate check-in

### ISSUE THREAD

**Issue by wullaski** [department-of-veterans-affairs/va.gov-team#69888]
Issues:

- Initiate check-in was getting a 502/503 error from vetext staging endpoint `https://staging.api.vetext.va.gov/api/vetext/pub/chip/initiate-checkin-data/530/39085`
- initiate pre-check-in was failing as well

**Comment by wullaski** [comment]
The vetext staging server was down and was restarted and that resolved the majority of the issues. There is still an issue with cancelled appointments. Thread here: https://dsva.slack.com/archives/C02G6AB3ZRS/p1699981162527899

**Comment by loripusey** [comment]
@wullaski so, this issue is resolved, but does the problem with cancelled appointments cause a problem in production?

**Comment by wullaski** [comment]
I'd like to look into it. Hopefully this is just an issue with the way the staging tool works.

**Comment by loripusey** [comment]
Can you point this then and I'll pull it into our new sprint?

**Comment by loripusey** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/69888?planning-poker) with Zenhub @wullaski

**Comment by wullaski** [comment]
Synced on this and investigated error caused by scheduling, cancelling and rebooking at the same clinic, same time. The issue is with how vetext fetches all appointments for that user that day and if there is a cancelled appointment at the same place and time as a valid appointment then the 404 error is thrown. This could be on purpose as they would like the veteran to go to the MSA in these situations.

A work around for the scheduling tool would be to book an appointment at a different clinic when this issue arises. We can also surface a better error message as part of this ticket
