### ISSUE TITLE
Adding Jonathan VanCourt to DSVA Slack

### ISSUE THREAD

**Issue by huggins-va** [department-of-veterans-affairs/va.gov-team#69898]
Please add Jonathan Vancourt as a multi-channel user to: 
- api-benefits-claims
- team-dash 

Jonathan Vancourt is a new SWE onboarding to support team Dash. 

Thank you,
Nora

**Comment by LEHigley** [comment]
need an email

**Comment by LEHigley** [comment]
added to general couldn't add to other chanels
