### ISSUE TITLE
Platform Atlas - Sorting Columns

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#69912]
Enable all columns to be sortable

**Comment by RachalCassity** [comment]
PR has been merged.

**Comment by laineymajor** [comment]
The changes implemented do not work. Columns are not sorting.[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3p2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--44197a9af93b494e64a270ebe0c1e73d722629f7/Screenshot%202023-11-20%20at%2010.25.44%20AM.png)

**Comment by RachalCassity** [comment]
@laineymajor Which columns are not sorting?

**Comment by RachalCassity** [comment]
@LindseySaari @laineymajor Thanks for testing.

Fixed in this PR, https://github.com/department-of-veterans-affairs/platform-atlas/pull/234
