### ISSUE TITLE
Design Intent - Design Feedback - Employee Experience Team, 21-526EZ, Max CFI

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#69924]
## VFS actions
- [x] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [x] Comment on this ticket:
  - [x] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [x] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [x] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [x] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- Work with content on makign sure it is super clear how rare it is for people to get more on their max rating.
- 

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- **Must**: Be sure to use the correct [expandable alert styling](https://design.va.gov/components/alert-expandable) (no left border)
- **Must**: Review your additional info components and make sure they do not have too much content. Review the [guidance](https://design.va.gov/components/additional-info#when-to-consider-something-else).
- **Must**: If you are going to use [icons](https://design.va.gov/foundation/icons#feedback) with text make sure they are black.
- **Must**: Remove blue bottom border under the Tinnitus on Step 2. Currently our [headers](https://design.va.gov/foundation/typography#headings) do not have bottom borders.
- Consider: You could break up the content in the "What does this mean" text and use accordions or even just put it in 1 accordion. Be careful about navigating to a new tab outside the form flow. Testing has shown that some users do not know how to get back in the form flow so if you do this make sure you test it and consider using a simplified header.

**Comment by allison0034** [comment]
Hi @carodew , the simplified header is actually called the minimal header. You can view it on [Storybook](https://design.va.gov/storybook/?path=/docs/components-va-minimal-header--default).

**Comment by carodew** [comment]
Gotcha, neat! is your suggestion that we use the simplified header within the entire 526EZ flow, or use it on the external information page when Veterans navigate there directly from the 526 flow, or both? Thx! (I've been out sick, sorry for the delayed reply)

**Comment by allison0034** [comment]
@carodew it would only be something to consider, it would def help if you link the user outside of the form, in a new tab, that way they do not navigate away from the form. Here is our [guidance on usage](https://design.va.gov/components/header/header-minimal#usage), it is fairly new.

**Comment by carodew** [comment]
See #74026

I'm going to try to swap this out in the prototype prior to usability testing, but either way we will be inheriting the header/footer that the entire 526EZ form is using. I believe those are the standard ones. the Disability Benefits Experience team is aware of this feedback and would be in charge of swapping the header/footer to the minimal versions.
