### ISSUE TITLE
Phone number display for VHA Facility Detail page

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#6993]
## What happened?
Phone number appears to be listed twice: once as link for auto-dialer and one as routine display for "Main phone number". 

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/bd27aed6-0d1d-45aa-bd46-01f179f5a00d)

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/aefd1e08-6a2e-475a-b2bb-c7f8dd68e22d)

## Specs:
- Browser: Chrome

## Steps to Reproduce
- URL: https://www.va.gov/find-locations/facility/vha_436QB

1. View Facility Detail page for Plentywood VA Clinic. 
2. Observe two phone numbers 

## Desired behavior
Facility Detail page should not list a phone number more than once without labels to aid in understanding. 
The phone number output should be in this format (and only once):
`<a href="tel:7035551212" aria-label="7 0 3. 5 5 5. 1 2 1 2.">(703) 555-1212</a>`
The addition of the aria-label with the number spaced out like that makes screen readers spell out each number instead of "seven-hundred-and-three five-hundred-fifty-five minus one-thousand-two-hundred-and-twelve". 

## Acceptance Criteria
- [ ] The Facility Detail page displays the accurate main phone number for Plentywood VA Clinic only once. 
- [ ] The Facility Detail page displays the accurate mental health phone number for Plentywood VA Clinic only once, if available in API. 
- [ ] Phone numbers are labeled as Main or Mental health as appropriate. 
- [ ] Displayed phone numbers are linked as appropriate for accessibility. 

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by mmiddaugh** [comment]
Per @jenstrickland :

> The CMS ought to be able to do this programmatically. I just wrote this ticket so that Trevor will add it to the design system documentation: https://github.com/department-of-veterans-affairs/va.gov-team/issues/6997

will keep this issue open for tracking.

**Comment by jenstrickland** [comment]
@mmiddaugh To clarify, the ticket I wrote for Trevor to add to the design system will not update the CMS. The CMS templates are owned by the teams that maintain them, so your devs would implement this change in the templates for the facilities.

**Comment by mmiddaugh** [comment]
This is not part of CMS. This info comes from Facilities API and within the Facility Locator Detail page.

**Comment by jenstrickland** [comment]
@1Copenut are you able to help with this situation? 🙏

**Comment by mmiddaugh** [comment]
Closing this issue as we'll be ensuring all phone numbers function as links in [#8063](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8063)
