### ISSUE TITLE
[MVP] Step 3: Match all questions and copy to designs for VA medical center pages

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#69942]
## Note
Part of the larger effort to update the existing 527EZ form to add missing fields/info and remove depreciated fields.

## Description
On Step 3, Health and employment: medical care,
ensure all copy, including questions for pages related to VA medical centers is matching the Sketch files,
as shown on the designs.

## User Story
As a veteran seeking a pension benefit, I aim to strengthen my claim by documenting the VA treatment facilities where I've received medical care for my disability. This information will serve as supporting evidence, facilitating the process of obtaining the pension benefit I am entitled to.

##Screen Flow
https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/JAyRk87

## Task Prototype 
Form 527 - Step 3 of 7 - Health and Employment Prototype / Medical Care / VA Medical Centers:
https://sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/vRrjpgn/play

## Step Prototype
Form 527 - Step 3 of 7 - Health and Employment Prototype: https://sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/L4Mpad5/play

## Acceptance Criteria
**For all pages:**
`Disabilities/medical information`

**For page 1:**
`Have you received treatment from a VA medical center? (*Required)`
`Yes`
`No`

**For page 2:**
`Enter all VA medical centers where you have received treatment`
`VA medical center (*Required)`
`Add another VA medical center`

**For page 3:**
_Same as above_

## Tasks
[Software Development Tasks](https://docs.google.com/document/d/1vtn5co_YzGl1cFRNrIBAdjf53dmfH4_EXBWK8C5mU9Y/edit?usp=sharing)

- [x] Front-end work @ToddWebDev 

## Review
- [ ] Designer (Maya) has signed off on pages in staging

## Artifacts
- [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/527EZ-reactivation-initiative-brief.md)
- [User flow in Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683826730324/61b509f935adaa2acf2f7769a5ba911726a7b237?sender=u9d01ee38af217e4877e75660)
- [Prototypes in Sketch](https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/p/988EBB71-6E9D-4099-A2BC-4BB61551E38F/canvas)
- [Spreadsheet of deleted form fields](https://docs.google.com/spreadsheets/d/1PTXxO6mFH2ZUK6XxX7iCCQb-NoSvhB5P/edit?usp=sharing&ouid=104362113771391164792&rtpof=true&sd=true)
- [Content source of truth/PDF form](https://www.vba.va.gov/pubs/forms/VBA-21P-527EZ-ARE.pdf)
- [Link to testing accounts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/form-deactivation/527EZ-staging-test-accounts-accessible.md)
- [Link to staging](https://staging.va.gov/)

**Comment by vbellissimo** [comment]
@ToddWebDev does not look like any major changes other than minor copy edits to match header(s), etc.

- Have you received treatment from a VA medical center? https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/D18DD03A-5EFB-4DD1-AFBB-A029BC91CEEB
- Enter all VA medical centers where you have received treatment: https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/D9E9AF01-21C8-4AE1-8E9E-93FF9C7216EF
- Add multiple centers: https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/FB5D1C48-A7C1-4BE1-9897-12228FF4EFCC

**Comment by mayacoforma** [comment]
@ToddWebDev Looks good, thank you!
