### ISSUE TITLE
Spike: Update metrics plan

### ISSUE THREAD

**Issue by buddhima-coforma** [department-of-veterans-affairs/va.gov-team#69954]
Following on from #68985 (metrics overview) and #67367 (Spike)

### Goal
Conclude on how we will measure progress for PB - including where the data will come from, where it can be viewed, and what we need to do next to get there.

### AC
- Each title in 'metrics spec' sheet indicates potential metrics below it. Feel to use them or propose different ones, as long as we get to measure what's intended. https://docs.google.com/spreadsheets/d/1Zt3PfQBN1kMquxYP3u7s1pu7Hq1D5wydcPmvm2DLTrk/edit#gid=1133106940
- Change format and fields of document where needed. 
- By completing the doc, be able to propose a view to access metrics, may it be a spreadsheet or dashboard etc
- Propose follow up tickets if anything needs to be built

**Comment by mjknight50** [comment]
Specifically, I will be looking at:

data source
source type
have access

**Comment by wayne-weibel** [comment]
I added a proposed tracking schema to the spreadsheet
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFloQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a55999e481a564042d7c2738995e4ba5ad517f93/Proactive%20Tracking.jpeg)

**Comment by buddhima-coforma** [comment]
#71317 is the correct follow on ticket
