### ISSUE TITLE
[MVP] Step 4 Household info: Create new page and question for What's your marital status and match copy

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#69959]
## Note
Part of the larger effort to update the existing 527EZ form to add missing fields/info and remove depreciated fields.

## Description
On Step 4 of Household information,
create a new page for `What's your marital status?` question
match copy for the 3 pages (marital status, current spouse's name, current marriage info)
as shown on the designs.

## Designs
- What's your marital status? https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/250536E4-5D8D-4FAB-A247-2774DA785BC0
- Copy changes: https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/403A7F72-F846-4E78-89EF-2028ED768AC2
- Copy changes: https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/44F9CB9A-1F25-4EC7-B0FC-4AAB2AD95F63
-  Screen flow: https://www.sketch.com/s/94592459-f741-45a0-9432-efd685b9a1d5/a/OeYljd2
- Household information section 'end-to-end' prototype: https://sketch.com/s/94592459-f741-45a0-9432-efd685b9a1d5/a/dgvkRbE/play
## Acceptance Criteria

**New page:**
Create 1 new page,
In this page, add the following required radio button question:

`What's your marital status? (*Required)`
`Married`
`Never married`
`Separated`
`Widowed`
`Divorced`

**Validation info:**

If they answer "Married" or "Separated", they will see the next two pages:
- Current spouse's name, as [shown on this page](https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/403A7F72-F846-4E78-89EF-2028ED768AC2)
- Current marriage information, as [shown on this page](https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/44F9CB9A-1F25-4EC7-B0FC-4AAB2AD95F63)

If they answer "Separated", in addition to the pages above, they will also see:
- new page/question for: Reason for separation, as listed on #69960
- new page/question for: Financial support for your spouse, as listed on #69961
- new page/question for: Current spouse's marital history, as listed on #69962

If they answer "Never Married", the next page/question the user sees will be: Dependent children, as [shown on this page](https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/ABF37E14-AABD-4307-84D5-30458EAF004B).

**Match copy:**
Ensure all copy, including headers, questions and buttons match the designs for all 3 pages:
- What's your marital status? https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/250536E4-5D8D-4FAB-A247-2774DA785BC0
- Match all copy for Current spouse's name page: https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/403A7F72-F846-4E78-89EF-2028ED768AC2
- Match all copy for Current marriage information: https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/44F9CB9A-1F25-4EC7-B0FC-4AAB2AD95F63

## Tasks
[Software Development Tasks](https://docs.google.com/document/d/1vtn5co_YzGl1cFRNrIBAdjf53dmfH4_EXBWK8C5mU9Y/edit?usp=sharing)

- [x] Front-end work

## Review
- [ ] Designer (Maya) has signed off on pages in staging

## Artifacts
- [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/527EZ-reactivation-initiative-brief.md)
- [User flow in Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683826730324/61b509f935adaa2acf2f7769a5ba911726a7b237?sender=u9d01ee38af217e4877e75660)
- [Prototypes in Sketch](https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/p/6571319D-6329-4249-B0A7-E39DA9DA31F4/canvas)
- [Spreadsheet of deleted form fields](https://docs.google.com/spreadsheets/d/1PTXxO6mFH2ZUK6XxX7iCCQb-NoSvhB5P/edit?usp=sharing&ouid=104362113771391164792&rtpof=true&sd=true)
- [Content source of truth/PDF form](https://www.vba.va.gov/pubs/forms/VBA-21P-527EZ-ARE.pdf)
- [Link to testing accounts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/form-deactivation/527EZ-staging-test-accounts-accessible.md)
- [Link to staging](https://staging.va.gov/)

**Comment by mayacoforma** [comment]
@vbellissimo Reviewed and refined this task.
