### ISSUE TITLE
[MVP] Step 4 Household info: Match question wording for 7 questions under Dependent children details

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#69967]
## Note
Part of the larger effort to update the existing 527EZ form to add missing fields/info and remove depreciated fields.

## Description
On Step 4 of Household information,
ensure the 7 following existing questions are worded the same as the designs:

1. Do you have any dependent children?: https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/ABF37E14-AABD-4307-84D5-30458EAF004B
2. Dependent child's information: https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/5D33F08C-EACB-46CC-B912-40E66D7C3A59
3. Multi-entry for dependent child's info: https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/E725C83E-6CAB-4E90-9819-5E4C40368320
4. Dependent place of birth: https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/D63E827F-625F-4B76-BB89-01630188B7EF
5. Dependent SSN: https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/FEDA5EE6-EA19-4525-98F6-0ED0ACA62AED
6. Relationship to dependent: https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/2B7A1792-E345-45B7-BB60-721548B14643
7. Dependent's student status: https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/95434B71-4BF5-4388-8CBB-B9A0142E438F

**PLEASE NOTE: The design files provided on this ticket show 1 question per page. However, the task is to simply ensure the questions' wording and surrounding copy match the designs. DO NOT CREATE A NEW PAGE TO SEPARATE QUESTIONS INTO THEIR OWN PAGES.**

## Designs
1. Do you have any dependent children?: https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/ABF37E14-AABD-4307-84D5-30458EAF004B
2. Dependent child's information: https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/5D33F08C-EACB-46CC-B912-40E66D7C3A59
3. Multi-entry for dependent child's info: https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/E725C83E-6CAB-4E90-9819-5E4C40368320
4. Dependent place of birth: https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/D63E827F-625F-4B76-BB89-01630188B7EF
5. Dependent SSN: https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/FEDA5EE6-EA19-4525-98F6-0ED0ACA62AED
6. Relationship to dependent: https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/2B7A1792-E345-45B7-BB60-721548B14643
7. Dependent's student status: https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/95434B71-4BF5-4388-8CBB-B9A0142E438F

Screen flow: https://www.sketch.com/s/94592459-f741-45a0-9432-efd685b9a1d5/a/OeYljd2
Prototype: https://sketch.com/s/94592459-f741-45a0-9432-efd685b9a1d5/a/dgvkRbE/play

## Acceptance Criteria

**Match questions' wording and surrounding copy for the 7 questions provided above:**
- Ensure all copy for existing questions match the designs.

## Tasks
[Software Development Tasks](https://docs.google.com/document/d/1vtn5co_YzGl1cFRNrIBAdjf53dmfH4_EXBWK8C5mU9Y/edit?usp=sharing)

- [ ] Front-end work

## Review
- [ ] Content review in staging

## Artifacts
- [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/527EZ-reactivation-initiative-brief.md)
- [User flow in Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683826730324/61b509f935adaa2acf2f7769a5ba911726a7b237?sender=u9d01ee38af217e4877e75660)
- [Prototypes in Sketch](https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/p/6571319D-6329-4249-B0A7-E39DA9DA31F4/canvas)
- [Spreadsheet of deleted form fields](https://docs.google.com/spreadsheets/d/1PTXxO6mFH2ZUK6XxX7iCCQb-NoSvhB5P/edit?usp=sharing&ouid=104362113771391164792&rtpof=true&sd=true)
- [Content source of truth/PDF form](https://www.vba.va.gov/pubs/forms/VBA-21P-527EZ-ARE.pdf)
- [Link to testing accounts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/form-deactivation/527EZ-staging-test-accounts-accessible.md)
- [Link to staging](https://staging.va.gov/)
- Household information prototype: https://sketch.com/s/94592459-f741-45a0-9432-efd685b9a1d5/a/dgvkRbE/play

**Comment by vbellissimo** [comment]
@wayne-weibel I'm going to chime in here but the answer should be, no, do not remove them. There is another frontend task that is similar to this one that @zack is working on, and it includes these two questions you asked about:

- [[MVP] Step 4 Household info: Match question wording for 6 questions under Dependent children details #69972](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/gh/department-of-veterans-affairs/va.gov-team/69972)

**Comment by aplatt-coforma** [comment]
Verified that content looks good. Learned that the question for `Is your child in school?` only is shown if the child is between 18-23 yrs old. 
<img width="460" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBME9BQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--96d00928c817dba2a3aff6a7779af193a7722562/screencapture-staging-va-gov-pension-application-527EZ-household-dependents-children-information-0-2023-12-21-15_14_58.png" alt="screencapture-staging-va-gov-pension-application-527EZ-household-dependents-children-information-0-2023-12-21-15_14_58.png" />
