### ISSUE TITLE
[MVP] Step 4 Household info: Create new page and question for Financial support for your spouse and match copy

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#69961]
## Note
Part of the larger effort to update the existing 527EZ form to add missing fields/info and remove depreciated fields.

## Description
On Step 4 of Household information,
create a new page for Financial support for your spouse question and match copy,
as shown on the designs.

## Designs
- Financial support for your spouse: https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/D4C86BAA-7974-4E75-910C-884B2DD557F8
- Screen flow: https://www.sketch.com/s/94592459-f741-45a0-9432-efd685b9a1d5/a/OeYljd2
- Household information prototype: https://sketch.com/s/94592459-f741-45a0-9432-efd685b9a1d5/a/dgvkRbE/play

## Acceptance Criteria

**New page:**
Create 1 new page,

`Financial support for your spouse`

In this page, add the following required number field:

`How much do you contribute each month to your spouse's support? (*Required)`
_Dollar/number entry field_

**Validation info:**
The next page/question they see will be: Current spouse's marital history, as listed on #69962

**Match copy:**
Ensure all copy, including headers, questions and buttons match the designs.

## Tasks
[Software Development Tasks](https://docs.google.com/document/d/1vtn5co_YzGl1cFRNrIBAdjf53dmfH4_EXBWK8C5mU9Y/edit?usp=sharing)

- [ ] Front-end work

## Review
- [ ] Content review in staging

## Artifacts
- [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/527EZ-reactivation-initiative-brief.md)
- [User flow in Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683826730324/61b509f935adaa2acf2f7769a5ba911726a7b237?sender=u9d01ee38af217e4877e75660)
- [Prototypes in Sketch](https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/p/6571319D-6329-4249-B0A7-E39DA9DA31F4/canvas)
- [Spreadsheet of deleted form fields](https://docs.google.com/spreadsheets/d/1PTXxO6mFH2ZUK6XxX7iCCQb-NoSvhB5P/edit?usp=sharing&ouid=104362113771391164792&rtpof=true&sd=true)
- [Content source of truth/PDF form](https://www.vba.va.gov/pubs/forms/VBA-21P-527EZ-ARE.pdf)
- [Link to testing accounts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/form-deactivation/527EZ-staging-test-accounts-accessible.md)
- [Link to staging](https://staging.va.gov/)

**Comment by aplatt-coforma** [comment]
Checked for content and next page flow.
<img width="1212" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXRDQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--be0719922d283683e3ab501052995d93dd9f1b4c/Screenshot%202023-12-07%20at%204.20.06%E2%80%AFPM.png" alt="Screenshot 2023-12-07 at 4.20.06 PM.png" />


<img width="1026" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWxDQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--065104dc71345b12dc89ecdf86e671bb2bb240a9/Screenshot%202023-12-07%20at%204.20.14%E2%80%AFPM.png" alt="Screenshot 2023-12-07 at 4.20.14 PM.png" />
