### ISSUE TITLE
Identify and implement form data to PDF mappings in the back end 10-7959A

### ISSUE THREAD

**Issue by cloudmagic80** [department-of-veterans-affairs/va.gov-team#69977]

**Comment by cloudmagic80** [comment]
Complete the mapping file with how each property maps to a fillable field in the PDF
 Add a sample JSON payload in the back end for tests
 For non-fillable fields in the PDF, either regenerate the PDF to make them fillable or stamp the data using an x, y coordinate
 Add tests for the new model in the spec/ folder of the module
 Create vets-api pull request for internal and platform approval
 Merge pull request

**Comment by marywang2** [comment]
@cloudmagic80 is this the same ticket as [this](https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/72803)? Can I close this one?

**Comment by cloudmagic80** [comment]
modules/ivc_champva/spec/requests/v1/uploads_spec.rb

**Comment by cloudmagic80** [comment]
[Uploading... cbadb8dc-e1ac-4e09-aca8-20d874130867_vha_10_7959a-tmp.pdf]

**Comment by baltes** [comment]
@cloudmagic80 it looks like the attachment above might not have finished uploading. can you add when you get a moment?
