### ISSUE TITLE
[MVP] Step 4 Household info: Create expandable section for Dependent's disabilities and match copy

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#69970]
## Note
Part of the larger effort to update the existing 527EZ form to add missing fields/info and remove depreciated fields.

## Description
On Step 4 of Household information,
on the page with question Is your child seriously disabled?,

- create a new expandable section,
- and match question wording and copy,

as shown on the designs.

## Designs
- Example 1: https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/87DA1F68-0264-4CA5-A2D1-E6BBF0764C06
- Example 2: https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/2EEF8702-3B85-4DBF-8F82-4B9D59854E06

Screen flow: https://www.sketch.com/s/94592459-f741-45a0-9432-efd685b9a1d5/a/OeYljd2
Prototype: https://sketch.com/s/94592459-f741-45a0-9432-efd685b9a1d5/a/dgvkRbE/play

## Acceptance Criteria

**Create new expandable section**
On the question: Is your child seriously disabled?, add new expandable section.

When section is collapsed, the copy shown will be:
`What do we mean by "seriously disabled"?`

When the section is expanded, the copy shown will be:
`A child is seriously disabled if they developed a permanent physical or mental disability before they turned 18 years old. A seriously disabled child can't support or care for themselves. `

**PLEASE NOTE: The design files provided on this ticket show 1 question per page. However, the task is to simply ensure this question's expandable copy and question wording and surrounding copy match the designs. DO NOT CREATE A NEW PAGE TO SEPARATE THIS QUESTION INTO ITS OWN PAGE.**

## Tasks
[Software Development Tasks](https://docs.google.com/document/d/1vtn5co_YzGl1cFRNrIBAdjf53dmfH4_EXBWK8C5mU9Y/edit?usp=sharing)

- [x] Front-end work

## Review
- [x] Content review 

## Artifacts
- [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/527EZ-reactivation-initiative-brief.md)
- [User flow in Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683826730324/61b509f935adaa2acf2f7769a5ba911726a7b237?sender=u9d01ee38af217e4877e75660)
- [Prototypes in Sketch](https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/p/988EBB71-6E9D-4099-A2BC-4BB61551E38F/canvas)
- [Spreadsheet of deleted form fields](https://docs.google.com/spreadsheets/d/1PTXxO6mFH2ZUK6XxX7iCCQb-NoSvhB5P/edit?usp=sharing&ouid=104362113771391164792&rtpof=true&sd=true)
- [Content source of truth/PDF form](https://www.vba.va.gov/pubs/forms/VBA-21P-527EZ-ARE.pdf)
- [Link to testing accounts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/form-deactivation/527EZ-staging-test-accounts-accessible.md)
- [Link to staging](https://staging.va.gov/)
- Household information prototype: https://sketch.com/s/94592459-f741-45a0-9432-efd685b9a1d5/a/dgvkRbE/play

**Comment by aplatt-coforma** [comment]
Content looks good. It's show on the same page as when collecting the dependent info.
<img width="582" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenRIQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b73701a25974f8e931c0e852a7f498c4d6027358/Screenshot%202023-12-08%20at%201.56.49%E2%80%AFPM.png" alt="Screenshot 2023-12-08 at 1.56.49 PM.png" />
<img width="730" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenhIQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e985fa3888d34a18f45f6c74c40d2711a6b43130/Screenshot%202023-12-08%20at%201.56.41%E2%80%AFPM.png" alt="Screenshot 2023-12-08 at 1.56.41 PM.png" />
