### ISSUE TITLE
[DRY RUN: 10-7959C] - Generate the back end form model and mapping in the simple_forms_api module

### ISSUE THREAD

**Issue by michaelclement** [department-of-veterans-affairs/va.gov-team#69983]
[Step 4 (back end): Generate the back end form model and mapping in the simple_forms_api module](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Engineering/Form%20Digitization%20development%20guide.md#step-4-back-end-generate-the-back-end-form-model-and-mapping-in-the-simple_forms_api-module)

**Comment by cloudmagic80** [comment]
Completed. I've done it locally only. I haven't uploaded to github yet
