### ISSUE TITLE
[CAIA A11y Research]: Disability Benefits - Employee Experience Team: 21-526EZ, Max CFI (January 2024 EOM)

### ISSUE THREAD

**Issue by sara-amanda** [department-of-veterans-affairs/va.gov-team#69999]
# Project Overview

> [!NOTE]
> **High-Level Overview**: Disability Benefits - Employee Experience Team
> - **Initial Kickoff**: Nov. 29, 2023 at 11:30 a.m. ET
> - **Status**: Moved from `Blocked` to `In Progress` on January 18, 2024
> - **Research Timeframe**: January 24 - February 2, 2024
> - **Pilot**: Completed January 24, 2024 (#74019)
> - **Research Sessions:** January 24 to February 6`
> - **Assistive Tech Users**: `3` AT Users
> - **Artifacts Available**: 1/24/2024
> - **Testing Environment:** `CodePen`
> - **Assistive Tech Being Used**: `VoiceOver`, `Fusion` and `Screen Magnification`
> - **Task Lists**:  [See task lists for next steps/definition of done](https://github.com/orgs/department-of-veterans-affairs/projects/929/views/27?pane=issue&itemId=44743139#:~:text=reveal%20supporting%20artifacts-,Next%20Steps,-Disability%20Benefits%3A%2021) for  Disability Benefits - Employee Experience Team and CAIA A11ys

## CAIA Assignee(s)
- Jamie
- Sara
- Evan

## About the Employee Experience Team

- Team name: Disability benefits employee experience
- OCTO-DE product owner: @jenniferbertsch
- Product manager: @amylai-nava
- Designer: @carodew @KimLadin @ChristineRoseSteiffer
- Accessibility specialist:
- Content writer: @carodew
- **Slack channels:** 
    - **Primary Channel:** [#benefits-employee-experience-design](https://dsva.slack.com/archives/C03C8661PAP)
    - **Research Study Channel**: [2024-01-max-cfi-refinements](https://dsva.slack.com/archives/C06EC9LHRSP)

## Background Info. 

<details><summary>Toggle to reveal background information</summary>

> We are working on an intervention to help dissuade Veterans from applying for to increase benefits (A claim for increase, or CFI) for tinnitus when they are already receiving the maximum amount of benefits. We have a few specific requests for the CAIA team:

> In our design concept, we have an additional page, outside of the online 526 flow, that provides more information about what it means to submit a CFI when you're already at the maximum. We need help figuring out where this page should live in the information architecture of va.gov, as well as best practices for having people access this information from within the 526 flow).
> We would like some review of the content of this more info page for consistency with style guide. It's worth noting that this tested well in our discovery research, so we would want to balance any new changes with what seemed to work for users.

> (Potentially) Accessibility assistance on modifications to a checkbox tile to allow us to show the a link to the new information within the tile.

</details>

<details><summary>Toggle to reveal additional team information from Research Ticket Intake</summary>

### Do you have an accessibility champion?

No, we don't have a champion (yet)

### Calendar checking

- [ ] Based on this calendar, confirm we have specialists who can support your study in your desired timeframe
- [ ] Confirm you are filing this support ticket at least 1 week in advance of said timeframe, so we have enough heads up to provide support

### Have you reviewed the CAIA capacity calendar?

- [ ] Yes, we have reviewed the CAIA capacity calendar and can confirm specialists are available to support in our research timeframe

</details>

## Research Sessions

<details><summary>Toggle to reveal research sessions, testing schedules, and participant AT details </summary>

Per Intake Ticket: #69856: 

> Our next step is to finalize our designs for usability testing in CodePen, including people who use AT 
Provide date if available: usability testing dates are from Monday, January 29th - Friday, February 2nd

### Timeframe

- **Pilot Session**: 1/24/2024 #74019
- **Timeframe**: 1/24/2024 - 2/2/2024

### Length of sessions

- **Session length:** `pending` minutes
- **Buffer time between sessions:** `pending` minutes
- **Maximum sessions per day:** `pending`

###  Testing Schedule

P# | Sessions | Time Slots (ET) | CAIA A11ys Available | Notes
------------------|------------------|--------------|--------------|--------------
P# | Jan. 24, 2024 |  3:30 p.m. **_Pilot Session_** | @coforma-jamie | ✅  **Completed**
P1  | ~Jan. 30, 2024~ **_Rescheduled for_** Jan. **31**, 2024 | 10:30 a.m. - 12 p.m. | @sara-amanda and @EvanAtCoforma | ❌ **No** **Show**
P4 | Jan. 31, 2024 | 12 p.m. to 1:30 p.m. | @EvanAtCoforma | ✅  **Completed**
P7 | Feb. 2, 2024 | 9 a.m. - 10:30 a.m. | @sara-amanda and @EvanAtCoforma ` @coforma-terry | ❌ **No** **Show**
P11 | Feb. 6, 2024 | `ADDED` 9:00 - 10:30am EST | @sara-amanda and @coforma-jamie | `❌ **Participant** **Canceled**
P12 | Feb. 6, 2024 | `ADDED` 4:00 - 5:30pm EST | @sara-amanda and @EvanAtCoforma | `TBD` 

### Device & AT Combinations

CAIA A11Ys will be looking for information along the lines of the following. We realize that some of this information will not be available until the day of the session. 

**Participant Number** | Date of Research | **Assistive Tech** | **Skill Level** | **Operating System** | **Browser** |**Device Type** |
|------------------------|------------------|--------------------|-----------------|----------------------|-------------|-------------|
| _P 1_                   | ~01/30/2024~ **_Rescheduled_** 01/31  ❌ **NO SHOW** ❌       |   **Voice Over**        | **Intermediate**      |  Windows PC or Apple  `TBD`  | Chrome, Safari, Firefox, etc.  `TBD`    | Desktop, Mobile or Tablet `TBD` |
| _P 4_                   | 01/31/2024         |   **Fusion**        | **Intermediate**     |  Windows PC or Apple  `TBD`  | Chrome, Safari, Firefox, etc.  `TBD`    | Desktop, Mobile or Tablet `TBD` |
| _P 7_                   | 02/02/2024   ❌ **No** **Show** ❌      |   **Native iOS software (magnifier)**        | **Intermediate**     |  **Apple**   | **Safari (assumed)**    | Desktop, Mobile or Tablet `TBD` |
| P11                   | `NEW` 02/05/2024       ❌ **Participant** **Canceled** ❌   |   'Zoom magnifier'        | Intermediate     |  `TBD`   | `TBD`   | Desktop, Mobile or Tablet `TBD` |
| P12                 | `New` 02/06/2024                   |  TalkBack               |  Advanced                    | Android `which version TBD`           | `TBD`         | Mobile |

- **Consideration**: You can also consider asking participants more specific AT and device combinations. 
- **For instance:** TalkBack on Samsung Galaxy 8, or VoiceOver on iPad with magnification.

</details>

## Supporting artifacts

<details><summary>Toggle to reveal supporting artifacts</summary>

- [Product outline - in GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/abd-vro/2024-01-Max-CFI-Refinements/Max%20CFI%20Product%20Brief.md) 
- [User flows - Page: Design explorations]( https://sketch.com/s/4319cad9-d81b-4b8e-8339-d4150fbd5274)
- Prototype or mockups: [Codepen](https://codepen.io/team/a6it/live/KKEMGGE)
- If this is in Sketch, which version or specific page should we focus on?
- Content source of truth: Codepen
- Research plan: [GitHub link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/abd-vro/2024-01-Max-CFI-Refinements/2024-01-Max-CFI-Refinements-Research-Plan.md)
- Conversation Guide: [GitHub link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/abd-vro/2024-01-Max-CFI-Refinements/2024-01-Max-CFI-Refinements-Conversation-Guide.md)
- [Previous research synthesis](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1698183162672/82f141d730ea00f0c984bbf41cc3efe1d7867827?sender=carolyn1198) 
- Any epics/issues that may be helpful: Collab Cycle Ticket 11/06/2023  #69299
- Link to testing accounts (please do not paste them in this ticket): `NA`
</details>

## Next Steps

```[tasklist]
### Disability Benefits: 21-526EZ, Max CFI Next Steps
- [x] **11/15/2023: DONE via CAIA:** Post a link to this ticket in the [sitewide-content-accessibility-ia](https://dsva.slack.com/archives/C01K37HRUAH) Slack channel and `tag @Terry Nichols`.
- [x] **Provide Testing Dates to CAIA** Testing dates are from Monday, January 29th - Friday, February 2nd
- [x] **Follow-up with CAIA** re: Scheduling Testing Sessions with AT Participate in research `start date: Jan 29` and `end date: Feb 2`
- [x] Your team's researchers and observers read through [platform guidance on research with assistive technology users](https://depo-platform-documentation.scrollhelp.site/research-design/research-assistive-technology-sessions)
- [x] CAIA Specialists (listed in the assignee section of this ticket) are assigned to your research, be sure to add the respective a11y specialist(s) to your **session calendar invites** (include the Zoom or Teams link). Also invite the CAIA
- [x] Provide CAIA a11y specialists your participant details such as: skill level, operating system, assistive tech used, browser and device
```

```[tasklist]
### CAIA A11y Next Steps
- [x] 11/15/2023 Create a11y Research Support Ticket (this ticket 69999)
- [x] 11/15/2023 Move ticket to Backlog
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/74019
- [x] Update A11y [CAIA Capacity Calendar](https://calendar.google.com/calendar/u/0/embed?src=c_f982350fc73a8162a1088ab14d00dd37335b2b559a60d6b67eb8021416f81c2a@group.calendar.google.com&ctz=America/Chicago) with holds for user research sessions with AT, when dates become available.
- [x] **Remove holds on A11y** [**CAIA Capacity Calendar**](https://calendar.google.com/calendar/u/0/embed?src=c_f982350fc73a8162a1088ab14d00dd37335b2b559a60d6b67eb8021416f81c2a@group.calendar.google.com&ctz=America/Chicago) and replace with invitations from project team (or Perigean)
- [x] Create [CAIA notes document](https://docs.google.com/document/d/1YfIzQ5H67OmwDAc77TEUQykOSFBB6nigR0ZPaRF-lT8/edit?usp=sharing) c/o Jamie
- [x] **Divvy user research session support with CAIA A11ys** - based on availability and technology available to support (See table above with session dates, times and available a11ys.)
- [x] **Review research folder and assets** [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/abd-vro/2024-01-Max-CFI-Refinements/2024-01-Max-CFI-Refinements-Research-Plan.md) and [Conversation Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/abd-vro/2024-01-Max-CFI-Refinements/2024-01-Max-CFI-Refinements-Conversation-Guide.md)
- [x] Added Design Resources to Raw Notes Doc `1/31/2024`
- [x] **Participate in research** `1/30/2024` and `2/2/2024`
- [x] Update the [CAIA notes document](https://docs.google.com/document/d/1YfIzQ5H67OmwDAc77TEUQykOSFBB6nigR0ZPaRF-lT8/edit?usp=sharing) during the sessions
- [x] **Sync with CAIA A11ys** on research findings (meeting)
- [x] **Create/update the CAIA A11y Research Deliverable** This is dependent on the number of study participants CAIA supports. If minimal, A11Ys may share feedback only in the feedback Mural or this ticket.
- [x] **Share the completed deliverable** with the project team via Slack: **Primary Team Slack:** [#benefits-employee-experience-design](https://dsva.slack.com/archives/C03C8661PAP). **Research Study Channel:** [2024-01-max-cfi-refinements](https://dsva.slack.com/archives/C06EC9LHRSP) and Ticket
```

**Comment by sara-amanda** [comment]
Happy 2024, @amylai-nava ! Just checking in to see if timing for this research will be end of January 2024. I wanted to make sure we have holds on our CAIA a11y calendar, on the dates you may need our assistance with Assistive Tech sessions. Thanks so much! Will look for an update and/or invites to sessions. Take care! 

@coforma-terry @coforma-jamie

**Comment by ChristineRoseSteiffer** [comment]
Hi @sara-amanda ! We submitted our research tickets and have planned to complete this study between Monday, January 29th - Friday, February 2nd. Let me know who I should add onto the invites once we start getting them from Perigean. Thanks! @amylai-nava

**Comment by sara-amanda** [comment]
@ChristineRoseSteiffer do you know what time your pilot session will be on Jan. 24, 2024?

**Comment by sara-amanda** [comment]
## Ticket Updates

- [x] Updated ticket to include slot schedule based on the timeframe we have the holds. 'pending invites'
- [x] Added the device information that a11ys will be looking for. 
- [x] Updated the pilot information
- [x] Updated the need for the research plan and conversation guide, pending availability 
- [x] Updates made to Next Steps/Task Lists

cc: @coforma-terry @coforma-jamie

**Comment by ChristineRoseSteiffer** [comment]
Hey team - I updated the ticket to include a link to the product brief in GitHub, as well as the specific AT sessions/tech to be used. Hope this is helpful! Thanks.

**Comment by sara-amanda** [comment]
## Ticket Updates
- [x] **Adding channel to ticket:** [2024-01-max-cfi-refinements](https://dsva.slack.com/archives/C06EC9LHRSP) 
- [x] **Pivoting Study Date for P1:** from 1/30 to 1/31 due to participant. 
- [x] **Table Updates:** Ticket updated to reflect the date change in the tables. 
- [x] **Calendar Updated:** hold added and updated to reflect the change in date.
- [x] **Accepted**: New invite from Perigean 1/31 at 10:30 a.m. 
- [x] **a11y Raw Notes Doc updated** Now reflects the change in participant. Also added key a11y items to watch for, based on pilot discussion with @coforma-jamie 
- [x] Updated task list for a11ys as well in this ticket

@coforma-terry @EvanAtCoforma

**Comment by sara-amanda** [comment]
## Potential Additional Session

### Monday (2/5) or Tuesday (2/6)
> Just a head's up to y'alls team that since we have struggled this study with no-shows and cancellations, **_we are attempting to schedule one more AT sessions either Monday or Tuesday next week_**. We will let y'all know as soon as possible if that gets scheduled! Thanks for everyone's flexibility as we navigate this.  - @ChristineRoseSteiffer 

**Source**: [accessibility-help DSVA Slack Channel](https://dsva.slack.com/archives/C8E985R32/p1706809408045229?thread_ts=1705512765.800649&cid=C8E985R32)

### a11y Capacity

I went ahead and put holds on our [CAIA A11y Capacity Calendar](https://calendar.google.com/calendar/embed?src=c_f982350fc73a8162a1088ab14d00dd37335b2b559a60d6b67eb8021416f81c2a%40group.calendar.google.com&ctz=America%2FNew_York) for those two days. Additionally, I updated the two tables in the body of the ticket. 

> [!NOTE]
> We also have two user testing sessions on Monday and one session on Tuesday from another study, as an aside. Check the [CAIA A11y Capacity Calendar](https://calendar.google.com/calendar/embed?src=c_f982350fc73a8162a1088ab14d00dd37335b2b559a60d6b67eb8021416f81c2a%40group.calendar.google.com&ctz=America%2FNew_York) for more information.

cc: @coforma-terry @EvanAtCoforma @coforma-jamie

**Comment by sara-amanda** [comment]
## Ticket Updates
- [x] Updated [ticket table](https://github.com/department-of-veterans-affairs/va.gov-team/issues/69999#:~:text=per%20day%3A%20pending-,Sessions,-Testing%20Schedule) to reflect today's no show ❌ 
- [ ] `pending` potential additional session on 2/5 or 2/6
- [ ] `pending` any rescheduled sessions

cc: @coforma-terry @EvanAtCoforma @coforma-jamie
