### ISSUE TITLE
Draft a Product Success Tool for eBenefits KPIs

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#6999]
## User Story or Problem Statement
How might we present KPI dashboarding for the eBenefits team?

How might we expand the KPI version of the Product Success Tool & what does that effort look like?

## Goal
Gather the eBenefits KPIs and OKRs and begin to look at analytics and design requirements for KPI dashboarding on Domo.

## Acceptance Criteria
- [ ] VSP has KPIs and OKRs retrieved from eBenefits
- [ ] VSP understands process to retrieve data for eBenefits KPIs

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jonwehausen** [comment]
Reassigning to Jason as I'm sure will get taken care of with dashboarding standardization at some point
