### ISSUE TITLE
[FE][CHIP] Integrate data into datadog metrics and dashboards for release

### ISSUE THREAD

**Issue by lee-delarm6** [department-of-veterans-affairs/va.gov-team#70002]
Combining logic form previous tickets and the spike on datadog metrics, pass in the real data and create the datadog dashboards for use in prod

(prior tickets for reference) 
https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/68147

https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/68163

**Comment by loripusey** [comment]
validated
