### ISSUE TITLE
GIDS: Remove prod flag for crosswalk dashboard widget & updated GIDS header

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#7002]
## Description
As a developer, I need to remove the prod flag for the dashboard widget, so the functionality is available in the production environment.

## Acceptance Criteria
1. The functionality implemented in #6663 is available in production. 

## Assumptions
1. This story will also test the functionality implemented in #6598. 

## Screenshots

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/619

**Comment by dmccurdybah** [comment]
Can be tested on gibct-data-service branch `issue-dash`

**Comment by sonntag-adam** [comment]
Shows in production build
![Screen Shot 2020-03-19 at 12.49.40 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/cb991183-ec03-4be2-a0ca-3e900201482c)

**Comment by sonntag-adam** [comment]
Merged closing story, testing passes QA.
