### ISSUE TITLE
GIDS: Cleanup GIDS Caution Flag data

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#7003]
## Acceptance Criteria: 
1. Columns `caution_flag` and `caution_flag_reason` are no longer set during preview generation

## Notes
1. Dev needs to search in `app/models/institution_builder.rb` for `BAH Caution Flag Cleanup`
2. Switch `caution_flag_reason` converter to return a CSV string value of `caution_flags` reason values
3. Create `caution_flag` method that returns whether `count_of_caution_flags` is greater than 0

**Comment by dneel-bah** [comment]
This story is on hold until further notice.

**Comment by desireeturner** [comment]
07/15: This can be closed as OBE based on the work being done in #10883
