### ISSUE TITLE
Design Feedback for Intake Screens

### ISSUE THREAD

**Issue by skirkman16** [department-of-veterans-affairs/va.gov-team#70033]
Tasks
- [ ] Ensure that all content from Figma is updated to screens in dev environment
- [x] ~Padding for card: 64, 32, 64, 32 (top, right, bottom left)~ @mateoclarke 
    - _clarified in Slack that the intention is to match the spacing on login.gov which is 80 L/R and 64 Top/Bottom, no action needed_
- [x] Padding for all elements within the cards: 32 (top, bottom) @mateoclarke 
- [ ] Body text: 16 regular Public Sans @moanu404 
- [ ] H1 text: 40 bold Public Sans @moanu404 
- [ ] H2 text: 24 bold Public Sans @moanu404 
- [x] Home screen and verify in-person screen: Ensure that bolded text is replicated @mateoclarke 
- [x] Home screen: In-Person Identity Verification header; "person" needs to be capitalized @mateoclarke 
- [x] Home Screen: List first card as "State-Issued ID or VHIC so it reflects the way the identifications have been listed in the description. @mateoclarke 
- [x] Home Screen: "Proof of address", capitalize "address" @mateoclarke 
- [x] Home Screen: Under Confirmation Case Number card, adjust language to the following: Once you complete the steps here to register for In-Person Identity proofing, a confirmation case number will be created and emailed to you. This case number will be valid for 10 days. You will need to share it when you come in-person to verify your identity at a VA Medical Center. You can write your case number down, print the email, or show it from your mobile device. If you go to a VA Medical Center after the 10 days have passed, the case number will no longer be valid and you will need to sign in to your Login.gov account and repeat the process to register for In-Person Identity Proofing again. @mateoclarke 
- [x] Home Screen: If you decide not to verify your identity in-person, you may close this window at any time. No hyphen between in person as it's an adverb here. @mateoclarke 
- [ ] Home screen: Determine consistent case number format
- [ ] Select site screen: Ensure that only map and zipcode search bar are visible upon entry. After user types in zipcode then site options appear. Site options should be consistent no matter what zipcode is typed in. @moanu404 
- [ ] Select site screen: Markers don't show on the map when you select a site. @moanu404 
- [ ] Verify in Person Screen: The "in" in the header should be capitalized @moanu404 
- [ ] Verify In Person Screen: A proof of your current address if you plan on presenting your VHIC. Remove "A" and capitalize proof @moanu404 
- [ ] Verify In Person Screen: A copy of your case number and instructions on what to bring to the verification site you selected have been sent to the email address you provided. @moanu404 

Acceptance criteria
- [ ] All tasks have been met and are implemented

**Comment by SophiaPhilipMO** [comment]
@skirkman16  and @lmorris3 

I adjusted the language as follows for the Home screen, can you review. I think we need to more clearly articulate what we mean by process as it's unclear what we are referring to:
Under Confirmation Case Number card, adjust language to the following: Once you complete the steps on Login.gov, a confirmation case number will be created and emailed to you. The case number that will be valid for 10 days and you will need to present it when you come in-person to verify your identity at a VA Medical Center. You can write this number down, print the email, or show the email from your mobile device. Should you not be able to locate your case number when you come to a VA Medical Center _within_ the 10 day window, a VA staff member will be able to look up the email you used to find your case number. If you go to a VA Medical Center _after_ the deadline, your information will not be saved and you will need to restart the process.

**Comment by SophiaPhilipMO** [comment]
@skirkman16 when did they provide their email address? Is it when they logged in with their IAL1?

Verify In Person Screen: A copy of your case number and instructions on what to bring to the verification site you selected have been sent to the email address you provided.

**Comment by lmorris3** [comment]
@SophiaPhilipMO are you referring to [this wireframe](https://www.figma.com/file/PfrWKmxiQ5RjChwx6I18QE/IPP-Prototypes?type=design&node-id=1118%3A5646&mode=design&t=R7JTEWy9OAL2BpXe-1)? I agree with you about clarifying some of the wording and maybe shortening the sentences so there is one direction per sentence. I would suggest a couple of further edits, maybe: Once you complete the steps on Login.gov, a confirmation case number will be created and emailed to you. The case number will be valid for 10 days. You will need to say or show it when you come in-person to verify your identity at a VA Medical Center. You can write this number down, print the email, or show the email from your mobile device. If you go to a VA Medical Center after the 10 days have passed, the case number will no longer be valid and you will need to restart the process.

**Comment by SophiaPhilipMO** [comment]
@lmorris3 yes and adjustments work great. I am wondering if instead of process we might write "If you go to a VA Medical Center after the 10 days have passed, the case number will no longer be valid and you will need to restart the process and create a new case number.

**Comment by lmorris3** [comment]
@SophiaPhilipMO will they know how to "create a new case number," though? Would they equate it with the entire process or would they think there is a way to simply generate a new case number? Could we say "this" process or maybe "the process of selecting in-person identity proofing."? We may be verging on wordiness, though.

**Comment by CarlDickerson** [comment]
@lmorris3 @SophiaPhilipMO I like these edits, I think we need just a little more clarification on "the steps on Login.gov" and "the process." It's a little longer, but for clarity, I might revise to: 
Once you complete the steps here to register for In-Person Identity proofing, a confirmation case number will be created and emailed to you. This case number will be valid for 10 days. You will need to share it when you come in-person to verify your identity at a VA Medical Center. You can write your case number down, print the email, or show it from your mobile device. If you go to a VA Medical Center after the 10 days have passed, the case number will no longer be valid and you will need to sign in to your Login.gov account and repeat the process to register for In-Person Identity Proofing again.

**Comment by SophiaPhilipMO** [comment]
@lmorris3 based on today's convo, let's go with Carl's suggested content

**Comment by SophiaPhilipMO** [comment]
@mateoclarke Padding clarification:
Update padding to reflect padding on Login.gov
For example:
<div class="grid-container padding-y-4 tablet:padding-y-8 card">

**Comment by moanu404** [comment]
https://themostudio.slack.com/archives/C03UP9MHKBN/p1701291310928039
