### ISSUE TITLE
Failed test: View percent of vets-api reviews completed in 48 hours

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#7004]
There is no visualization for "percent of PRs reviewed within 48 hours" for either **vets-api** or **vets-website**.

T1418: View percent of vets-api reviews completed in 48 hours
https://dsvavsp.testrail.io/index.php?/tests/view/1418

**Comment by shiragoodman** [comment]
@pjhill T3?

**Comment by pjhill** [comment]
> @pjhill T3?

This was a defect related to the backend review process dashboard that Product Support team made quite a long time ago. I'm not sure where this should live, or if we should just close it because this dashboard has been overcome by events.

**Comment by shiragoodman** [comment]
i vote for the latter... closing now.
