### ISSUE TITLE
Contact Center Review for [10-10 Health Apps - 10-10EZR standalone form]

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#70045]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
- We have built an online form of the 10-10EZR - Update VA health care information.  This form only exists in paper form today.
- The form mirrors a majority of the 10-10EZ Veteran health care application, such as Veteran info, Spouse/Dependent info and Insurance info. 
- This is an authenticated-only form.  Users who are not logged into VA.gov cannot access this form.

### Launch Date
We are looking to launch at the beginning of December for a small percentage of authenticated Veterans to monitor through the end of the year.  We will then start to increase the percentage of Veterans who can access the form.

### Version Number
This guide will be Version 1, first edition for this online form.

### Product Guide
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/10-10EZR%20Form/10-10EZR%20Health%20Benefits%20update%20form%20Product%20guide%20-%20Draft%2011-15-23.docx

### Product Video
*Please provide product video link*

### Product Video Transcript
*Please provide product video transcript link*

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
Draft looks good. Sent to VEO for review.

**Comment by starlow00** [comment]
No changes from VEO. Guide attached.[10-10EZR Health Benefits update form Product guide Draft 111523 SRT 11222023.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2tpQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6ad33c23ab908633901dafd99ac6806cf302e720/10-10EZR%20Health%20Benefits%20update%20form%20Product%20guide%20Draft%20111523%20SRT%2011222023.docx)

**Comment by hdjustice** [comment]
Thank you @starlow00 !  Have a great year-end and year-beginning!
