### ISSUE TITLE
Analyze user feedback from Medallia surveys for past 6 months

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#70048]
### User story

As a Cartographers team member, I want to analyze the qualitative survey responses we received from the past 6 months, so that we can learn from it.

### Notes

- The survey response export is available on our [team sharepoint](https://dvagov.sharepoint.com/:x:/r/sites/oitmhvonvagovcartographyteam/Shared%20Documents/Qualitative%20feedback/medallia%20export%20-%20MHV%20landing%20page%20-%201%20nov%202023.xlsx?d=w3960dfdc34304abc8d2d9a125d55b537&csf=1&web=1&e=Ff7ahn)

## Acceptance criteria

- Saved lightweight analysis of both quant and qual survey responses in Sharepoint
- Documented any insights in this ticket or new ticket(s) if appropriate

## Tasks

- [ ]

**Comment by sterkenburgsara** [comment]
Documentation / lightweight analysis[ in GitHub here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/landing-page/research/Medallia-feedback-analysis.md).

**Comment by sterkenburgsara** [comment]
@wesrowe I'm not sure there are clear follow-on tickets to create here based on lightweight analysis. We could discuss whether the overall rating in Medallia could inform a similar KPI for the transition (e.g. do we think that the same ratio of users having a good v. bad experience will stand? Deviate by some %?).

**Comment by wesrowe** [comment]
@sterkenburgsara, 

re no obvious follow-on tickets: no problem. sounds like no users had specific bugs with the landing page.

re "overall rating" – what I've heard is that MHV stakeholders are proud of a satisfaction score (in the 70s?), and we will want to measure the equivalent and track to it. There might be a clue in the VAgov dashboard in Domo. The very first card in the "All VA.gov dashboard" is Avg satisfaction score. It has been in the low 50s % for the last year or so, actually used to be a bit higher a couple years ago.

Your analysis was really complete, I thought! Thanks for the thorough job. The one thing missing is the average scores for the two surveys (somewhere between 1 and 5). Is that easy to grab? 

Note for later: we'll need to figure out how the % c-sat score is calculated – it might be similar to an element of your analysis, where you counted 4s and 5s as good/high scores.

**Comment by wesrowe** [comment]
this can close

**Comment by sterkenburgsara** [comment]
@wesrowe interesting re: score in the high-70s, I will peek at that, but it is not what we are seeing for these surveys. Tests are laid out somewhat differently, but yes - I was trying to bubble up a CSAT score, basically. There is no "overall score" metric for the second survey, but I can try to average the #s that do exist quickly if you're looking for that. 

Thanks for your edits!

**Comment by sterkenburgsara** [comment]
@wesrowe we are missing the last month-ish of data from Medallia. Happy to recalculate if we can get that & see if it nudges the CSAT closer to #'s you're seeing in Domo.
