### ISSUE TITLE
Vets-api terminal access for William Phelps

### ISSUE THREAD

**Issue by williamphelps13** [department-of-veterans-affairs/va.gov-team#70066]
### Your Name

William Phelps

### Your GitHub handle (terminal access is managed through GitHub)

williamphelps13

### Team, Role, and Company of the target individual

Benefits Claims Evidence, Software Engineer, Coa Solutions

### Product Manager (PM) name and email

Rivka Gates rivka.gates@agile6.com

### Product Owner (PO) name and email

Jessica Bertsch jennifer.bertsch@va.gov

### COR Name (leave "None" if you listed an AWS user name above)

Eunice Garcia

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

None

### Please confirm if you are on the VFS Team Roster or Platform Team Roster

- [X] [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Please confirm E-QIP Transmittal/Adjudication. This could be a screenshot of your Transmittal/Adjudication email, a link to another request where you've submitted this proof (i.e. AWS/SOCKS), etc.

- [X] I have attached proof that I have either transmitted my E-QIP survey or previously received a favorable decision (by including in "Additional Notes" section below)

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [ ] production (if requesting, justify prod access in 'Additional Notes' section)

### Additional Notes

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/22990386/5dde3098-37d1-453d-86a4-12c1fd69d889)

### Additional resources for Support Engineer

- [ ] For users on a VFS team but not in the VFS Team Roster, they must start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] Instructions for handling requests [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access) - Support Only

**Comment by williamphelps13** [comment]
Hey @jknipes! No rush here but just checking to make sure I didn't miss any fields here

**Comment by jknipes** [comment]
Found on VFS Roster

**Comment by jknipes** [comment]
@williamphelps13 you have been granted access to the `dev` `staging` and `sandbox` environments.
Here is some documentation for [Vets Api on EKS] https://depo-platform-=documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-TerminalAccess
