### ISSUE TITLE
Create Test Plan

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#70071]
To enter the Staging Review portion of the Collaboration cycle, we need to provide QA documentation including a ~"Regression Test Plan" and a~ "Test Plan".  

Below are the definitions of these two plans, from Platform's [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-regression-test-planRegressionTestPlan) documentation:

> ~**Regression Test Plan**~
> ~VFS teams can create a Regression Test Plan under the Test Runs & Results tab of TestRail. For an example regression plan, see the [VSP-Facility Locator regression plan](https://dsvavsp.testrail.io/index.php?/plans/view/149). VFS Teams not using TestRail are still expected to share a Regression Test Plan at the Collaboration Cycle Staging Review.~
>
> **Test Plan**
> VFS teams can create a Test Plan under the Test Runs & Results tab of TestRail. For an example regression plan, [see the Cross-Browser Search test plan](https://dsvavsp.testrail.io/index.php?/plans/view/30). VFS Teams not using TestRail are still expected to share a Test Plan at the Collaboration Cycle Staging Review.

Our Find a Representative product does not require authentication and is a brand-new product so there's nothing to revert to.  **In Staging Review, governance confirmed that we do not need a Regression Test Plan.**

**We do, however, need a Test Plan**
There is this note "Teams not using TestRail are still expected to share a Test Plan."

**Comment by cosu419** [comment]
Test plan created for following test cases on both mobile and desktop:

Geolocation
Basic search flow
Sorting
Pagination
Updating query params
Deep linking behavior
Directions + phone link behavior
Search results header display

Will continue to add more subtle cases, but this encompasses the critical functionalities
