### ISSUE TITLE
Qualitative Data Request for Sitewide Facilities Team

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-team#70092]
### Data Type Requested

User Surveys

### Date Range Start

07-01-2023

### Date Range End

09-30-2023

### Product Name(s)

Facility Locator, VA Medical Centers, Vet Centers

### Product Description

- The Facility Locator is an unauthenticated search tool which can be used to find VA facilities and services.
- Modernized VAMC websites are comprehensive facility pages designed to meet the needs of Veterans, their families, and caregivers. The pages provide the location details needed to prepare a Veteran to visit and easy access to top tasks and digital health tools.
- Vet Centers are community-based counseling centers that provide a wide range of counseling, outreach, and referral services to eligible Veterans, active duty service members, and their families.

### Survey URL(s), key term(s), case category or type

https://www.va.gov/find-locations
All VA Medical Center modernized websites (all ending in -health-care)
All Vet Center modernized websites (all ending in -vet-center)

### File Delivery Format

All in one file, on one tab

### Word Cloud

No

### VA Email Address(es)

jane.xiong@va.gov, suzanne.middaugh@va.gov

### Add Assignee and Labels

If not already done so, please ensure @newworld2616 is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by newworld2616** [comment]
Hi, I have shared the requested data, please verify once you receive it. Thank you!

**Comment by xiongjaneg** [comment]
@newworld2616 Hi, Sarifa, I did get the spreadsheet of responses for https://www.va.gov/find-locations

I need responses for all VA Medical Centers and Vet Centers. Do I need to provide the URLs of each of the hundreds of facilities or is there an easier way for you to identify them based on the common ending of their URLs?

All VA Medical Center modernized websites (all ending in -health-care)
All Vet Center modernized websites (all ending in -vet-center)

**Comment by newworld2616** [comment]
Yes, I would need all the URL's please.

**Comment by xiongjaneg** [comment]
Here are the VAMC urls. We're working on getting the list of Vet Center urls. Thanks for your patience.
[VAMC urls.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/13382815/VAMC.urls.xlsx)

**Comment by xiongjaneg** [comment]
Here are the Vet Center urls. Thank you!
[Filter by Directory (Full) vetcenters.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/13382936/Filter.by.Directory.Full.vetcenters.xlsx)

**Comment by newworld2616** [comment]
Thank you so much for the files, just would like to confirm both files have different URL's?

**Comment by xiongjaneg** [comment]
Yes, confirming both files have different URL's. Thanks.

**Comment by newworld2616** [comment]
Thank you, I will start working on them

**Comment by newworld2616** [comment]
One more question,  could you confirm the date please?

**Comment by xiongjaneg** [comment]
Yes, for calendar 2023 3rd quarter, so July 1, 2023 to September 30, 2023. Thank you! (This will likely be a quarterly request from me so I don't know if that helps you set up shortcuts for the future, but just in case.)

**Comment by newworld2616** [comment]
Good morning, I have shared the requested data, please verify once you receive the data.

**Comment by xiongjaneg** [comment]
Thank you. The data has been received. I appreciate the quick turnaround on a LOT of data.

**Comment by newworld2616** [comment]
Of course!

**Comment by newworld2616** [comment]
Received!
