### ISSUE TITLE
[UX/FE] 10-10 EZR: Discovery/Content/Dev - Determine correct verbiage for Dependent Expenses

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#70095]
As a Veteran, I would like to understand what expenditure information I need to provide the VA so that I make sure I get the benefits that I have earned. 

- [x] [Review thread with Aliyah ](https://dsva.slack.com/archives/C05QKRZGHFS/p1700065135333929)about difference between Dependent verbiage on PDF vs. site
- [x] Ask HEC about whether the question on EZ and EZR PDF should be the same or different
- [x] Meet with Shana (Alex did this) to discuss issue
- [ ] Report back to team on Shana discussion (Alex)
- [ ] Work with Aliyah to determine how we can take draft verbiage and 1) make it clear to Veteran, 2) cite the correct verbiage as needed
- [ ] If needed: Discuss with Patrick/HEC folks to discuss how to handle this (we may not need this)
- [ ] Update EZR (we'll have a separate story to update EZ)
- [ ] Push to Prod
- [ ] **Success: Verbiage around what expenses we're asking for is clear for Veterans**

**Verbiage provided by Shana (this is still in draft): **“(1) EXPENSES PAID BY THE VETERAN OR SURVIVING SPOUSE FOR COLLEGE, VOCATIONAL REHABILITATION OR TRAINING THAT THE VETERAN OR SURVIVING SPOUSE IS PURSUING.  (2) EXPENSES PAID BY A CHILD WITH REPORTABLE INCOME FOR COLLEGE, VOCATIONAL REHABILITATION OR TRAINING BEING PURSUED BY THE CHILD”****

**Comment by jessicastump** [comment]
[Sketch link to visual capture](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/p/CC64075A-E4A1-4BAD-A283-D3C75F4BEFF9/canvas) of current state and issue

**Comment by jessicastump** [comment]
Email recap from email:

Good afternoon,

Thank you Alex for bringing this to our attention.  It has taken some time for us to review and research what the appropriate language should be for both forms. We have received approval to move forward with the following language:

 
10-10EZ

Current: section IV-2G: EXPENSES PAID BY YOUR DEPENDENT CHILD FOR COLLEGE, VOCATIONAL REHABILITATION OR TRAINING (e.g., tuition, books, materials)
Suggested: EXPENSES PAID BY YOUR DEPENDENT CHILD WITH REPORTABLE INCOME FOR COLLEGE, VOCATIONAL REHABILITATION OR TRAINING (e.g., tuition, books, materials)
 

10-10EZR

Current: section IV-14: EXPENSES PAID BY YOU FOR YOUR DEPENDENT CHILD FOR COLLEGE, VOCATIONAL REHABILITATION OR TRAINING (e.g., tuition, books, materials)
Suggested: EXPENSES PAID BY YOUR DEPENDENT CHILD WITH REPORTABLE INCOME FOR COLLEGE, VOCATIONAL REHABILITATION OR TRAINING (e.g., tuition, books, materials)
 
Both forms - Definitions of terms used on this form: want to add

Reportable Income: The minimum amount of gross income required to file a Federal income tax return according to the Internal Revenue Code of 1954 Section 6012(a).

**Comment by jessicastump** [comment]
The updated flow ([Sketch Link](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/a/Ee9739v) - Figma one coming soon) discussed during 1010 design sync 12/11.
"Reportable income" is addressed by draft version "Did/will your dependent file a federal tax return for the year 2022?" 
Other changes are flow/logic based
