### ISSUE TITLE
[MVP] Step 3: Match question wording and copy for Are you currently employed?

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#70097]
## Note
Part of the larger effort to update the existing 527EZ form to add missing fields/info and remove depreciated fields.

## Description
On Step 3 Health and employment information,
ensure question matches the designs for:
Are you currently employed?
as shown on the designs.

## Designs
- Currently employed question: https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/394FDAB4-7CFC-4F7F-BCA3-5B294E5D291D
- User flow view: https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/v/4rRVG3/p/6571319D-6329-4249-B0A7-E39DA9DA31F4/canvas?posX=-51728.28689508955&posY=-40924.48158331645&zoom=0.12801407277584076

## Acceptance Criteria
Ensure the following page copy and question matches the designs:

**Question**
`Current employment`
`Are you currently employed? (*Required)`
`Yes`
`No`

**Validation scenarios**
If the user answers "yes" to Are you currently employed?,
they will see the next questions on a separate page as described on ticket [#69758](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/gh/department-of-veterans-affairs/va.gov-team/69758)

If the user answers "no" to Are you currently employed?,
they will see new questions on a separate page as described on ticket [#69871](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/gh/department-of-veterans-affairs/va.gov-team/69871)

**Match copy:**
_Ensure all copy, including headers, questions wording and buttons match the designs._

## Tasks
- [x] Front-end work

## Review
- [ ] Designer (Maya) has signed off on pages in staging

## Artifacts
- [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/527EZ-reactivation-initiative-brief.md)
- [User flow in Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683826730324/61b509f935adaa2acf2f7769a5ba911726a7b237?sender=u9d01ee38af217e4877e75660)
- [Prototypes in Sketch](https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/p/988EBB71-6E9D-4099-A2BC-4BB61551E38F/canvas)
- [Spreadsheet of deleted form fields](https://docs.google.com/spreadsheets/d/1PTXxO6mFH2ZUK6XxX7iCCQb-NoSvhB5P/edit?usp=sharing&ouid=104362113771391164792&rtpof=true&sd=true)
- [Content source of truth/PDF form](https://www.vba.va.gov/pubs/forms/VBA-21P-527EZ-ARE.pdf)
- [Link to testing accounts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/form-deactivation/527EZ-staging-test-accounts-accessible.md)
- [Link to staging](https://staging.va.gov/)

**Comment by mayacoforma** [comment]
@ToddWebDev I couldn't locate this question in the staging environment. Am I overlooking something?

**Comment by mayacoforma** [comment]
@ToddWebDev I wasn't able to locate this question in staging, am I missing something?

**Comment by ToddWebDev** [comment]
@mayacoforma This will be on stage later today. Since we don't have a sprint column to clearly delineate when an item is in stage and ready for 'design review', I'll have to continue to manually tag you here when an item is deployed to stage after it has been technically reviewed and merged.

**Comment by aplatt-coforma** [comment]
Confirm new field is there<img width="739" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXcxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7710f5d8ae02a68e76908e5604fa4493aa66525b/Current%20Employment%20field.png" alt="Current Employment field.png" />
Also seeing the field error message when not selected
<img width="725" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTQxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c25ae00fa5f742d9742cd870e96233fa91c856b2/Required%20error.png" alt="Required error.png" />

**Comment by aplatt-coforma** [comment]
Closing ticket.
