### ISSUE TITLE
New VFS team for Product Directory

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#70105]
## User Story
As a new VFS team, we would like to be included in the Product Directory, so that other teams have contact and project information about our work.

---

## Additional information

- Product Name: Beneficiary Travel Self-Service System (BTSSS) Migration (aka BTSSS on VA.gov)
- OCTO Product Owner: Kay Lawyer (Eng Lead: Mark Dewey, Design Lead: Kristen McConnell)
- OCTO Crew: Health Tools
- VFS Product Manager: Ayush Chakravarty
- Product Link (where is the code located in vets-website for the app): N/A
- Product Outline: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/beneficiary-travel/product-outline-btsss.md

---
## How to configure this issue
- [x] **Labeled with 'platform-cop'** 
- [x] **Labeled with Practice Area** (`platform-cop-backend`, `platform-cop-frontend`, `platform-cop-devops`)

**Comment by ayush-chak** [comment]
Hi there! Just following up on this - anything we can do to get ourselves added?
