### ISSUE TITLE
Cancel Modal for Cerner site(s) from Appointment homepage

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#7011]
As a Veteran, I need to be redirected to my "My VA Health" portal to cancel appointments that are at registered Cerner sites (ex - Columbus or Spokane) from the VAOS Appointments homepage. 

---
## Acceptance Criteria
- [x] When user clicks 'cancel' for Cerner-site appointments, "Cancel modal" alerts user that appointment cannot be canceled in VAOS and that user must cancel in their My VA Health Portal
- [x] Add Button that says "Go to My VA Health" that directs user to their My VA Health Portal
- [ ] This specific cancel modal and button should show for all Cerner sites' appointments only
- [ ] User should still be able to cancel non-Cerner site appointments in VAOS
- [ ] Add event tracking to the "Go to My VA Health" button to track usage

**Comment by rtwell** [comment]
@peggygannon this will need your expertise

![image](https://user-images.githubusercontent.com/12564977/77327835-1ba67280-6cf2-11ea-8f89-540f1343cec0.png)

**Comment by peggygannon** [comment]
@lenaecb @rtwell here is my content recommendation for this message and one question:


Question, will users need to sign in again to go to My VA Health? 

I feel like this **SHOULD** know this by now, but I wanted to clarify again if single sign on will apply to Cerner as well? 
 
------

**You can't cancel this appointment on the VA appointments tool**
To cancel this appointment, please go to [My VA Health].

{Buttons}
Go to My VA Health

Go back to VA appointments

**Comment by jbalboni** [comment]
@peggygannon I believe the plan is no, they won't have to sign in again.

**Comment by lenaecb** [comment]
@peggygannon - I am with Jeff, my understanding is that they shouldn't need to sign-in again. The SSOe team will have inbound SSOe completed prior to Cerner going live is my understanding.

**Comment by peggygannon** [comment]
@lenaecb @jbalboni OK, thanks for confirming!  I wanted to make sure the message I wrote above ^^is accurate.
