### ISSUE TITLE
Research into sending alerts to gov sensitive repo for image vulnerabilities 

### ISSUE THREAD

**Issue by zyellowhorse** [department-of-veterans-affairs/va.gov-team#70119]
Whenever we get a image vulnerabilities from Sign In Service we would like to get the details of the issue and have an issue created in the gov sensitive repo so it can be addressed. 

- look into see if there is a way to get the vulnerability detailed description of the issue from AWS
- look into a way to automatically create issues 
- define format of how should the issues look like and what information should be included

**Comment by parkerbees** [comment]
Moved to Jira. Closing.
