### ISSUE TITLE
Vets-api terminal access for Derrick Ellerbie

### ISSUE THREAD

**Issue by dellerbie** [department-of-veterans-affairs/va.gov-team#70112]
### Your Name

Derrick Ellerbie

### Your GitHub handle (terminal access is managed through GitHub)

@dellerbie

### Team, Role, and Company of the target individual

Lighthouse Team Dash, Engineer, Agile Six

### Product Manager (PM) name and email

Kayla Watanabe, kayla.watanabe@adhocteam.us

### Product Owner (PO) name and email

Janet Coutinho, janet.coutinho@va.gov

### COR Name (leave "None" if you listed an AWS user name above)

Cecila Lee

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

Agile Six - Anthony M. Arashiro

### Please confirm if you are on the VFS Team Roster or Platform Team Roster

- [X] [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [X] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Please confirm E-QIP Transmittal/Adjudication. This could be a screenshot of your Transmittal/Adjudication email, a link to another request where you've submitted this proof (i.e. AWS/SOCKS), etc.

- [X] I have attached proof that I have either transmitted my E-QIP survey or previously received a favorable decision (by including in "Additional Notes" section below)

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### Additional Notes

Would like to obtain access to all environments.

I have filed AWS access request, https://github.com/department-of-veterans-affairs/va.gov-team/issues/70111

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/534756/a5234d8d-599c-449d-9662-97628a20347e)

### Additional resources for Support Engineer

- [ ] For users on a VFS team but not in the VFS Team Roster, they must start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] Instructions for handling requests [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access) - Support Only

**Comment by IsaiahMW1** [comment]
Found in VFS Team Roster

**Comment by JonathanKamensDVA** [comment]
Perhaps I am missing something, but I don't see any explanation here for why the production access is required. Please provide a justification so we can approve it. Thanks.

**Comment by IsaiahMW1** [comment]
@dellerbie Good morning, Can you please provide more information/explanation on why it is justifiable for the need of prod access ?
