### ISSUE TITLE
Pension Log Update for DataDog Dashboard, Part 2

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#70118]
## Issue Description

_Continuation of tickets:_
#69027
#66512
#64938

_Already done on previous tickets:_
- The user ID is logged where possible (outside of the sidekiq job)
- Logs exist that capture:
-- **when an attachment submission has begun**
-- **when an attachment submission has failed**
-- **when an attachment submission has succeeded**

## Acceptance Criteria
- [x] Set up Datadog logs that capture:
- **Number of submissions**
- **Number of submissions in-progress**
- **Average time to complete**
- **Failed submissions to Sidekiq**
- **Tracking new logs in Datadog**

**Comment by TaiWilkin** [comment]
@vbellissimo Yes, we've completed all of this. I think there will eventually be more work on logging / monitoring, but I think all the work we have currently lined up is done.

**Comment by vbellissimo** [comment]
Thanks, @TaiWilkin !
