### ISSUE TITLE
Adding Mike Eng to DSVA Slack

### ISSUE THREAD

**Issue by alatempa24** [department-of-veterans-affairs/va.gov-team#70126]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

<describe the request>

Please add Mike Eng (mike.eng@agile6.com) as a full member to DSVA Slack. They are a new UX Designer on the ABD Apps contract and need access to Slack to work on the project team.

Please add them to these channels:
#benefits-disability      
#benefits-portfolio
#design 
#benefits-onboarding
#benefits-disability-design

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add [_insert email_] as a single-channel guest to [_channel name_].
- Please add [_insert email_] as a multi-channel guest to these channels: [_channel names_].
- Please add [_insert email_] as a full member.
- Please change the status of [_slack username_] from [_current status_] to [_desired status_]

**Comment by LEHigley** [comment]
invited 4 days ago
