### ISSUE TITLE
Spike: VA profile available data

### ISSUE THREAD

**Issue by aplatt-coforma** [department-of-veterans-affairs/va.gov-team#70121]
### Summary
As we look into potentially pre-filling some fields in the 526 form, determine what kind of data can be retrieved from VA Profile.  

### Acceptance Criteria
- Identify all data that can be retrieved from a VA profile
- Share with Product
- Define next steps/create ticket if any

**Comment by mjknight50** [comment]
cc @wayne-weibel

**Comment by mjknight50** [comment]
There are several facets of the VA Profile API.
https://dvagov.sharepoint.com/sites/OITEPMOVAPROPUB

- Profile API
- Contact Information API
- Health Benefits API
- Ratings & Awards API
- Demographics and Gender

The focus of this ticket is on the profile API which pulls the data from MPI (Master Person Index)

**Comment by mjknight50** [comment]
[VA Profile Intake Request Document.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/13515604/VA.Profile.Intake.Request.Document.docx)
