### ISSUE TITLE
Vets-API in New Version EKS Cluster

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#70146]
### PROBLEM STATEMENT
EKS is being upgraded in production, therefore we need to test vets-api in the new EKS cluster to ensure things are working as expected.

This is not the testing piece. This is a dependency to BEGIN testing.

### ADDITIONAL INFORMATION
Sync with the infra team on this and take notes here... (space holder for now)

### ACTION ITEMS
- [x] Adjust kubernetes resources to get the deployment up and running
- [x] Update helm charts as needed 
- [x] Review EKS release notes for any changes, deprecations, and new features

**Comment by laineymajor** [comment]
@rmtolmach to sync with Lindsey to get started (once next sprint begins)

**Comment by laineymajor** [comment]
In progress. Many additional settings with the new upgrade.

**Comment by RachalCassity** [comment]
Unfortunately, we do not have the rights to create the Secrets client needed for the new AWS upgrade. I believe that infra will have to complete this. Once they have a new client setup, the external secrets can be upgraded. This is out of our realm.

**Comment by LindseySaari** [comment]
Rachal is working through the setup to utilize the new resources/config

**Comment by RachalCassity** [comment]
Vets-api-dev has successfully deployed (on our end). Devops has been notified to look at the cpu/node issue.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGtvQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--392df7595db37856c30c36c0eb4adc12eb5f9574/image.png)

**Comment by RachalCassity** [comment]
Documentation was added here: https://vfs.atlassian.net/wiki/spaces/TT1/pages/2857009343/Upgrading+ExternalSecrets+to+New+EKS+Cluster
