### ISSUE TITLE
Request Subdomain

### ISSUE THREAD

**Issue by emily-gullo** [department-of-veterans-affairs/va.gov-team#70145]
- [x] Confirm name to be requested
- [x] Gather project information
- [x] Gather technical information
- [x] [Submit request](https://vaww.va.gov/webregistry/index.cfm)
- [x] Record request link

- https://dsva.slack.com/archives/CBU0KDSB1/p1704825736947899

**Comment by nihil2501** [comment]
@nihil2501 testing

**Comment by nihil2501** [comment]
@emily-gullo Is this done? Is there any linkable or screenshottable output?

**Comment by hdbaines** [comment]
representative.va.gov is the subdomain we agreed on, I will submit a new request for this

**Comment by hdbaines** [comment]
Here's the request - https://vaww.va.gov/webregistry/index.cfm?action=search&template=site_detail&web_id7173
