### ISSUE TITLE
vets-api User model refactor

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#70140]
## Issue Description
The `User` model in vets-api should be updated to be DRYer and easier for non-Identity developers to navigate and understand.

## Back end tasks
- [ ] investigate User model & come up with proposed refactors
- [ ] consolidate UserIdentity vs MPI-backed attributes
- [ ] enable attribute caching

**Comment by parkerbees** [comment]
Moved to Jira. Closing.
