### ISSUE TITLE
New content strategy for REAP messaging

### ISSUE THREAD

**Issue by AnneHurley** [department-of-veterans-affairs/va.gov-team#7015]
Rethink the REAP messaging now that this program is over, and those benefits folded in to the GI Bill.

Should talk to stakeholders re new messaging.
https://www.va.gov/education/other-va-education-benefits/reap/

**Comment by DanielleSoCompany** [comment]
Hi @AnneHurley. I was just creating tickets for the education rewriting restart and had flagged REAP as outdated. Saw you had an issue on this here. Can you let me know if you've started the conversation with the education SMEs around this? Thanks!

**Comment by AnneHurley** [comment]
@DanielleThierryUSDSVA Not yet - we just wrote up the ticket to capture the fact that we wanted to do it.

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @AnneHurley. Just adding a note here that when we have this conversation with SMEs, we should also think about how to handle the REAP rates page. We have a page on REAP rates in our original rewriting strategy, but it's not needed in the same way now, of course. So we'll need to think about how to handle that. Also a @mnorthuis question (Mikki, we can sync on this as part of education rewriting restart). Thanks!

**Comment by mnorthuis** [comment]
@DanielleSoCompany One option, depending on how we structure this rates parent page, it may be that it just references REAP and links to the final 3 years in PDF form?
https://www.va.gov/education/benefit-rates/
