### ISSUE TITLE
Adding Jamie Fiore to DSVA Slack

### ISSUE THREAD

**Issue by HeatherRienks** [department-of-veterans-affairs/va.gov-team#70164]
Please add Jamie Fiore new Ad Hoc UX Researcher/Designer on CHAMPVA team to DSVA Slack as a Full Member.
jamie.fiore@adhocteam.us

See should be added to #vfs-all-teams, #vfs-change-announcements and any other pertinent UXR and VFS general channels for new team members.

**Comment by HeatherRienks** [comment]
@pshahVA - FYI

**Comment by pshahVA** [comment]
approved (took care of it)
