### ISSUE TITLE
Adding Rachel Eiting to DSVA Slack

### ISSUE THREAD

**Issue by HeatherRienks** [department-of-veterans-affairs/va.gov-team#70165]
Please add Rachel Eiting new Copilot Front End Engineer on CHAMPVA team to DSVA Slack as a Full Member.
rachel.eiting@copilot.llc

She should be added to #vfs-all-teams, #vfs-change-announcements and any other pertinent Engineering and VFS general channels for new team members.

**Comment by HeatherRienks** [comment]
@pshahVA - FYI

**Comment by pshahVA** [comment]
approved (I did it since so many folks are at the offsite)
