### ISSUE TITLE
Handling Cerner-only Veterans on VAOS Appts Homepage

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#7017]
As a Veteran registered to only Cerner sites, I need to be redirected to my "My VA Health" portal to schedule any of my appointments. 

## Acceptance Criteria
- [ ] Update "Schedule Appointment Button" on Appointment homepage to "Go to My VA Health" and redirect user to their Cerner portal
- [ ] Update top-level copy to say something like:
**Need to schedule an appointment?**
Use your "My VA Health" portal to schedule a VA appointment. 
Button: [Go to My VA Health]
(@peggy please give you thoughts on content)

(In future - We will need to reconsider the top level text based on how we want to handle messaging of 'upcoming appointments' for full Cerner sites)

**Comment by peggygannon** [comment]
@lenaecb I have a few followup questions, so I understand what we need to say:

Is this content meant for Cerner users who might navigate to the Appointments landing page without first going through the Scheduling page? 

It's my understanding that users who are registered at a Cerner-only site, won't necessarily see the Appointment home page, as the "Cerner" alert on the authenticated Scheduling page that will direct users to My VA Health

**Comment by jbalboni** [comment]
@peggygannon Yes, that's my understanding. We can't guarantee no one will get into the app, even though they should get redirected in the scheduling page.

**Comment by jbalboni** [comment]
We would also probably want to update this state:

![Screen Shot 2020-03-25 at 10.23.29 AM.png](https://images.zenhubusercontent.com/599c94608f62dc7798c3b2cd/64061a8c-71a8-4c96-9241-ba16dacbc28d)

**Comment by lenaecb** [comment]
@peggygannon - for some time, Cerner-only users will still be able to get into VAOS to see upcoming appointments that were booked prior to their site going live with Cerner. This is just an interim state. They will also soon be able to see their past appointments prior to Cerner in VAOS as well. Not ideal, but best way for us to handle this interim time.

**Comment by peggygannon** [comment]
Hello, @lenaecb @jbalboni Here are my content recommendations. 

One question, do we need to say "request" an appointment for the Cerner sites? or can users directly schedule? 

**Need to schedule an appointment?**
You can schedule a VA appointment through My VA Health. 

{button} Go to My VA Health


**OR** if we need to say "request" for Cerner sites, then let's use this one: 

**Need to schedule an appointment?** 
You can send a request to schedule a VA appointment through My VA Health. 

-----

**Upcoming appointments**

{box}
**You don't have any appointments**      (note, please remove the period from the header here)

If you need to schedule a VA appointment, go to My VA Health. 

{link} Go to My VA Health

**Comment by jbalboni** [comment]
@peggygannon I think they direct schedule? That would be a question for @lalexanderson-dsva.

**Comment by jbalboni** [comment]
![Screen Shot 2020-03-26 at 12.58.46 PM.png](https://images.zenhubusercontent.com/599c94608f62dc7798c3b2cd/b03530ce-8977-4248-a854-ee920250084c)

**Comment by peggygannon** [comment]
@jbalboni Looks good. thank you
