### ISSUE TITLE
Auth Exp Team Onboarding: Alex Parker

### ISSUE THREAD

**Issue by Dottifacilities** [department-of-veterans-affairs/va.gov-team#70180]
**Background**
Welcome! We can use this ticket to track onboarding to the authenticated experience team.

**Platform Onboarding**
Please complete the tasks in the Platform Onboarding Ticket #70179 as well as the Team Onboarding Tasks here in this ticket - Note that in order to complete some tasks in this ticket you may need to complete tasks in the Platform onboarding ticket first

**Team Onboarding Tasks**
Intro to Authenticated Experience team members
Please schedule a short chat with each of these folks. You can schedule individual chats or talk to people in groups if you think that makes sense:

  - [ ] Dotti Cummings (Delivery Manager/Scrum Master)
  - [ ] Samara Strauss (Auth experience product owner, interim Profile Product Manager)
  - [ ] AJ (My VA Product Manager - Ana Jakabcin))
  - [ ] TBD (Designer/Researcher)
  - [ ] Liz Lantz (Designer/Researcher)
  - [ ] Pam Drouin (Designer/Researcher)
 - [ ]  Adam Whitlock (Frontend developer)
  - [ ] Allison Lu (Frontend developer)
  - [ ] Tom Harrison (Backend developer)

**Review Product Documentation**
The Authenticated Experience team is currently organized into two product teams: My VA (dashboard), and Profile (section). Here are some helpful documents to review. It would also help if you log into staging (more info at the bottom of this ticket) and check it out for yourself to get a sense of these products.

My VA

va.gov-team/products/identity-personalization/profile
/README.md

 My VA roadmap
Profile

 Profile product outline
 Profile goals and roadmap
Read up on current/recent projects
The general structure of our documentation is that we keep an overarching product outline and then individual project outlines within for initiatives or versions/phases of work on those larger products. Here are the projects we currently have going on the My VA team.

My VA
Current

 Small Initiatives
 Dot Indicator
 BE enhancements
Previous ~year

 My VA Audit Improvements
 Payment Information V2
 Onsite Notifications
Additional resource documentation
My VA

 My VA use case documentation
 Onsite notifications use case documentation
Profile

 Personalization and profile comparative analysis
Profile is comprised of 7 products/sections:

 Personal information product outline
 Contact information product outline
 Military information
 Direct deposit product outline
 Notification preferences product outline
 Account security
 Connected apps
Log into staging
Profile
You can use the following info to get into staging:

Go to VA.gov.

You can sign into staging with most (staging users) to view the profile. Feel free to pick any user, but if you want a specific user, try user 81. Please do not edit or update their profile, however.
Once you are logged in click the menu that has the user's name in the upper right of the navigation. You'll see a link to the profile in the menu.
My VA
You can use the following info to get into staging:

Go to Staging.va.gov. and click sign in (upper right corner)
Select the ID.me option
Enter credentials for staging user 36 (Staging user info can be found here in the sensitive repo. Note that the user number refers to the number in the test user email, not the row number of the table.)
Click sign in
Accept terms
Click continue until you're signed in and automatically redirected to My VA
Optional demos
My VA

 If it would be helpful, any of the My VA team members can walk you through how each feature works.
Profile

 If it would be helpful, any of the profile team members can walk you through how each feature works.

**Comment by ACParker89** [comment]
@ ACParker89
