### ISSUE TITLE
Investigate Transaction ID for VBA debt

### ISSUE THREAD

**Issue by HeatherRienks** [department-of-veterans-affairs/va.gov-team#70183]
## Issue Description

Request from VBA: 
Can you tell me if this Veteran has a VBA debt?  I am hoping they started the application prior to the update where it displays VBA in the comments, because we have gone through all paths and this person should have been approved.

The Transaction ID is - `41b48960-e840-4d5d-9fb1-485c184a3bf4`

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by HeatherRienks** [comment]
@denisecoveyduc - Let's discuss the priority of this ticket.

cc: @Tom-Davis

**Comment by kjsuarez** [comment]
Based on the Form5655Submission metadata, this submission does not have any debts, only a single copay.

**Comment by HeatherRienks** [comment]
Thank you! I have let Mike Dewey know.

**Comment by kjsuarez** [comment]
Mike got back to me with followup questions. Specifically- how was this FSR not submitted as streamlined even though it qualifies. The answer (already reported to Mike in an email thread) is that this Submissions form does not have the streamlined feature flag turned on. Recall that there are a set of InProgressForms created before this feature was 100% released which are still active today.
