### ISSUE TITLE
Fix broken link in starter app generator

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#702]
## Problem
The starter app generator outputs a link to https://github.com/department-of-veterans-affairs/vets-website/blob/master/docs/GeneratorOptions.md, which doesn't exist right now.

## Possible solutions
- Un-delete the file (removed in [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/10055))
- Point the link to the original document (assuming it was a duplicate like that PR says)

**Comment by timwright12** [comment]
Chatted with @cvalarida about this, seems like it's been fixed. Closing out.
