### ISSUE TITLE
Adding Mary Wang to DSVA Slack

### ISSUE THREAD

**Issue by HeatherRienks** [department-of-veterans-affairs/va.gov-team#70203]
Please add Mary Wang new Ad Hoc Product Manager on CHAMPVA team to DSVA Slack as a Full Member.

mary.wang@adhocteam.us

She should be added to #vfs-all-teams, #vfs-change-announcements and any other pertinent VFS general channels for new team members.

Thank you!

**Comment by HeatherRienks** [comment]
@pshahVA - FYI

**Comment by pshahVA** [comment]
completed
