### ISSUE TITLE
CF: Indicate school closed when closure date is in the past on Search Results

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#7020]
As a user of the comparison tool, I want to see the most accurate cautionary information as it relates to school closings so that I can make the best decision regarding how to use my education benefits. 

## Assumptions
1. This functionality will be behind a prod flag so that it is only available on staging. 

## Acceptance Criteria: 
1. When the school closure date associated with a school closing flag passes, the language on the Search Results page is updated to state: 
Header: "School closed"
Subtext: "School has closed"

Supporting Artifacts: 
1. Prototype: https://bahdigital.invisionapp.com/share/N5IAD8MHTC9

**Comment by hughes-dustin** [comment]
GIDS:
  Branch: bah-7020
  PR: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/624

vets-website:
 Branch: bah-7020
 PR:

**Comment by delli-gatti-michael** [comment]
### Local Testing Results:

#### Flags are showing as expected for regular schools
![Screen Shot 2020-03-23 at 1.32.22 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/ea439e8a-44f6-4896-9152-feb6b8e418ba)

#### All Vettec institutions are shown the same regardless of the date
![Screen Shot 2020-03-23 at 2.16.17 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/961dd7d6-4ce6-4595-b52a-8d936b43cb36)

**Comment by delli-gatti-michael** [comment]
Local Testing complete

**Comment by delli-gatti-michael** [comment]
TestRail Test Case:
https://dsvavsp.testrail.io/index.php?/cases/view/410

**Comment by hughes-dustin** [comment]
new branch: bah-7020-2
new PR: https://github.com/department-of-veterans-affairs/vets-website/pull/12026

**Comment by delli-gatti-michael** [comment]
Round 2 of local testing complete

**Comment by delli-gatti-michael** [comment]
Fix for the period that should not be there is included in this PR for story #7294:
https://github.com/department-of-veterans-affairs/vets-website/pull/12037

**Comment by delli-gatti-michael** [comment]
Latest changes now present in staging. Closing this issue
