### ISSUE TITLE
Vets-api terminal access for Holden Hinkle 

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#70215]
### Your Name

Holden Emmerson Hinkle

### Your GitHub handle (terminal access is managed through GitHub)

@holdenhinkle

### Your dsvagovcloud AWS user name (if applicable)

Holden.Hinkle

### Team, Role, and Company of the target individual

Accredited Representation Management, Lead Engineer, Oddball, Inc.

### Product Manager (PM) name and email

Danielle Baranowski, danielle.baranowski@oddball.io

### Product Owner (PO) name and email

Zach Goldfine, zachary.goldfine@va.gov

### COR Name (leave "None" if you listed an AWS user name above)

None

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

None

### Please confirm if you are on the VFS Team Roster or Platform Team Roster

- [X] [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Please confirm E-QIP Transmittal/Adjudication. This could be a screenshot of your Transmittal/Adjudication email, a link to another request where you've submitted this proof (i.e. AWS/SOCKS), etc.

- [X] I have attached proof that I have either transmitted my E-QIP survey or previously received a favorable decision (by including in "Additional Notes" section below)

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [ ] sandbox
- [ ] production (if requesting, justify prod access in 'Additional Notes' section)

### Additional Notes

I want to be able to run 'rails console' and in dev and staging and to be able to submit curl requests to Lighthouse within the va network.

E-QIP Transmittal
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/9326247/46b91fb5-5580-47fa-bd26-9a39e9ee775a)

### Additional resources for Support Engineer

- [ ] For users on a VFS team but not in the VFS Team Roster, they must start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] Instructions for handling requests [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access) - Support Only

**Comment by IsaiahMW1** [comment]
Found in VFS Team Roster

**Comment by IsaiahMW1** [comment]
Access has been granted to the dev and staging environments.

Here's some additional documentation for the [Vets API on EKS]
(https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-TerminalAccess)

**Comment by holdenhinkle** [comment]
Thank you @IsaiahMW1 !
