### ISSUE TITLE
Run status polling script on all backup submissions

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#70213]
We need to verify that no back up submissions are being lost to silent failures:

Per Emily: 

"A possible silent failure point has been identified in our backup process.  We have been sending backup submissions with the assumption that acceptance by the API meant success.  However, we are now being told that is not the case.  Before we can consider a backup submission 'accepted' we need to query the 'polling API' provided by central mail.  This can provide pass / fail information on the backup submissions, which for now we need to consider all as 'pending'
"

AC:
1. Identify any silent errors in the back up process caused by polling issue in API
2. Review submissions and prioritize spike for root cause

**Comment by SamStuckey** [comment]
[link to related docs (for polling)](https://developer.va.gov/explore/api/benefits-intake/docs?version=current)

**Comment by SamStuckey** [comment]
[Script that does this but has a problem with hitting the rate limit](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/benefits/scripts/526/backup_submission_status_getter.md)

alternatively, the [/status/report endpoint](https://dsva.slack.com/archives/CDRSFMWFL/p1700254057813269?thread_ts=1700253832.634649&cid=CDRSFMWFL) was recommended by LH team
