### ISSUE TITLE
[FE/QA] 10-10EZR: Erase Participant submitted data

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#70228]
During the EZR MVP UAT Research, Participant P7 submitted the EZR with dummy data. We will need to erase it if it got into the enrollment system.

P7 entered the following dummy data:
- Spouse SSN
- Financial Information
- Medicare Part A
- Health Insurance 

This is what happened at the Review Page
1. He checked the "I Confirm" check box.
2. He pressed the "Submit Form".
3. The Review Page reloaded, showing the "I Confirm" checkbox unchecked.
4. He checks the "I Confirm" checkbox again (without pressing anything else).
5. The page loads to the Confirmation Page, indicating a successful submission.

We attempted to wipe the filled information
1. The participant navigates to the INTRO Page and then clicks on the “Start your health benefits update form”.
2. From the Veteran Info, Phone and Email Address page; P7 clicked on the “Finish this Form later” link
3. The website redirects P7 to the Form-Saved page. From there, P7 clicked on “Start a new form” and “Yes” to “Are you sure you want to start over”

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd252QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f8a8a9a1c968de29ffef76799ff6d65d2edbd1d4/P7-Submission.mp4)

**Comment by hdjustice** [comment]
Is this still needed?
