### ISSUE TITLE
Maintain list scroll position when returning from details page

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#70227]
## Description

In any appointments list, users often click into the details page and back to the list.  Currently clicking "< Back to [List name] returns the user to the top of the list page.

This change would return the user to the page at the scroll position where they had left it.

---

## Acceptance Criteria
Background: the `toggle` toggle is on

Given a user is on the Appointments page 
When they click a details link
And return to the Appointments page using the descriptive back link or browser back button
Then the Appointments page is scrolled to the position it was at when the user clicked the details link

Given a user is on the Past appointments page 
When they click a details link
And return to the Appointments page using the descriptive back link or browser back button
Then the Appointments page is scrolled to the position it was at when the user clicked the details link

Given a user is on the Pending appointments page 
When they click a details link
And return to the Appointments page using the descriptive back link or browser back button
Then the Appointments page is scrolled to the position it was at when the user clicked the details link

### Design Assets
None

## Definition of Done
- [x] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by outerpress** [comment]
Works great @jenniemc ! Validated on web (MacBook/Chrome) and mobile (Android/Chrome)  @ldelacosta

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket.
