### ISSUE TITLE
[UX] 10-10EZR: User without "Pending" or "Enrolled" Status EZR error mesage

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#70234]
As a Veteran, I would like to know why I cannot access the EZR because I do not have one of the necessary statuses and thus know I need to update my information elsewhere or enroll.

- [x] Come up with design and verbiage for users trying to access EZR online that are **not** "Enrolled," "pending_mt" or "pending_other"
- [x] Reference how we handle this for EZ
[- [ ] Reference conversation with PM/FE/QA](https://dsva.slack.com/archives/C05Q6411HPF/p1700253283476569)
- [x] Determine if there are any specific instructions already in place--e.g. "we need your DD214" that we can leverage
- [ ] For MVP, we can come up with a blanket "your status is not eligible to update information online, please call or reference....." and we can get into more specific notifications later (or not depending on how easy this would be)
- [ ] UX team review and content review
- [ ] Send designs and verbiage to FE and QA ([see their ticket here](https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/70225))
- [ ] **Success: we have designs for what happens when a user with a "non-approved" status visits the online EZR form, and those designs/verbiage are send to FE and QZ**

**Comment by jessicastump** [comment]
[Link to the EZ error messages ](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683651181051/e0f47b9aaefbf78a3942df3028525cdc4336caff?wid=0-1683663569830&outline=open)for pending state, the MT reason list financial disclosure as the reason and is a valid use case for the EZR.

**Comment by jessicastump** [comment]
An update post-design sync on 11/20 and follow up questions: 

1. Can mvp be for only enrolled and v2 will be the adding alerts/paths for those in pending status? (design sync ?)
2. Should the EZ alerts for pendingMT direct Veterans to the EZR in the future? (thought of after the calls)
3. Starting of the [sketch canvas](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/p/FB19F709-9950-450D-B984-1A79D282CA1A/canvas) with the ez reference pulled in as a starting point
4. Need to talk through call to action language as this is a mental model switch for those in pending status
5. Needs content review which wouldn't happen until next week

Also noting this could potentially impact the introduction page content.

**Comment by jessicastump** [comment]
- [Working draft](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/a/lROM7bz) for review. 
- [Slack convo thread link](https://dsva.slack.com/archives/C05QKRZGHFS/p1700264394191749)

**Comment by jessicastump** [comment]
@alexseelig 
Adding a summary here and where we landed.
[Alerts Messaging & Status Paths](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/v/LQ0wY5/a/kKGbqAR) (shows all alerts based on status in the EZR and where they are placed)


For the pendingMT status (that includes both users who need to update their financials for that year, users who submitted their EZ but need to add financials, and those who have lost some eligibility and now require means testing) will see a warning alert in place of the prefill alert and have an action link into the EZR.
- [Desktop Sketch design](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/a/Wd37vYg)
- [Mobile Sketch design](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/a/3oE7ZnD)


This shows on the EZR introduction page.

**Comment by jessicastump** [comment]
Will review early next week at Monday Design sync and then async review with Aliyah so this can go on to FE/QA.

**Comment by jessicastump** [comment]
After planning we talked about this be a post-MVP but soon v1.1 type of update and consider all statuses and not just pendingMT. 
A starting point is [diagramed here](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/a/kKGbqAR) and in content review, but I still think we need to confirm all statuses are accounted for,

**Comment by katelyncai** [comment]
This ticket has evolved past it's original purpose. Closing this out and will revisit this issue for v2 of EZR.
