### ISSUE TITLE
[UI Scaffold] Discovery

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#70249]
## Description
A UI scaffold/placeholder is an iterative representation of the UI we intend to build. It allows the product team to experiment with different technologies, demo approaches during sprint review, provide async updates to stakeholders.

We need to figure out what it takes to deploy a scaffold/placeholder to staging on VA.gov in order to being iterating.

Note: Daniel Cloud has done something like this before.

## Risks
- If this requires going through the collab cycle, it could delay deploying the scaffold

## User Story
As a _____, I _____, so that _____.

## Acceptance Criteria
- [ ] Documented list of criteria for deploy something like this to staging

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---
## How to configure this issue
- [ ] **Attached to an Epic**

**Comment by laurenernest** [comment]
I created the Scaffolding development epic that tickets can be attached to. #70478
I also created the feature toggle ticket #70489

**Comment by hinzed1127** [comment]
[This page](https://depo-platform-documentation.scrollhelp.site/developer-docs/creating-a-new-application) is a good outline of the initial scaffolding required to render an app on VA.gov. By my reading of it (see [this section](https://depo-platform-documentation.scrollhelp.site/developer-docs/creating-a-new-application#Creatinganewapplication-Goingtoproduction)), it will automatically be hidden in prod and present in dev/QA environments. I don't believe feature toggles are necessary for a standalone page until after we've got something visible on prod, but we'll want them for testing out connections, namely:
- appointments pages
- claims pages
- wherever else we might integrate.


I plan on validating this with some quick work in `vets-website` and then we should be good to close this

**Comment by kjduensing** [comment]
I believe the generator will get us a frontend app that goes out with the daily deploy (if prod - staging goes right after merge).

Just to jot it down here, if we want to go to prod upon merge, we'll need to follow the steps to isolate the application (should be easy if new) and add it to the allow list.

https://depo-platform-documentation.scrollhelp.site/developer-docs/isolated-application-builds

**Comment by kjduensing** [comment]
I would also like to revisit as a team why we're doing the scaffold in the first place. Sounds like we're leaning toward an integration-heavy approach rather than a standalone approach. Just want to be clear what we tell people our reasons for doing this work are.

**Comment by hinzed1127** [comment]
Draft PR of UI scaffolding up at https://github.com/department-of-veterans-affairs/vets-website/pull/27195
