### ISSUE TITLE
[For on-going Reference] Resiliency Planning - VAOS

### ISSUE THREAD

**Issue by saneshark** [department-of-veterans-affairs/va.gov-team#7025]
- [ ] **Identify single points of failure:** look for team members that have sole responsibility for a task, or have sole access to a system. Have them cross-train another team member immediately, and document that training while they're at it.

- [ ] **Update documentation:** review and update manuals, runbooks, and incident response processes.

- [ ] **Identify manual processes:** we do a lot of work by rote – updating files, triaging tickets, reviewing alerts – that may fall by the wayside if we're offline. Document the manual work, who is responsible, who their backup is, and, if possible, how to automate or delay it.

- [ ] **Get business owner approval to continue operations:** get whoever needs to sign off on deployments, fixes, etc to give you blanket approval to continue normal operations in the case that they become unavailable. 

- [ ] **Identify time-specific processes:** document any pressing deadlines or integrations, so you're at least aware of what will be impacted in the case of a disruption. (this is a good task for a product manager-type person to do). Delay deadlines and deliverables if possible, otherwise flag them as at-risk for being missed

- [ ] **Preemptively cancel meetings:** make any meetings like one-on-ones or sprint planning optional to all attendees. Work with the assumption that people will participate if they can. if there's not a quorum for a meeting, cancel it and move on. 

- [ ] **Default to asynchronous, written communication (memos, reports, Slack-ups, etc)** that is supplemented with video/phone/Slack discussion, not the other way around. Promulgate policy, updates, and status in written form first, then follow up with a call or video conference to discuss it. With disparate, unpredictable schedules, we cannot assume concurrent availability of team members.

- [ ] **Set delivery expectations early:** If deliverables will be at risk, broadcast to stakeholders early and clearly. When planning future work, be conservative and plan for limited staff and partner availability.

- [ ] **Prioritize ruthlessly:** Make sure you and your team have a clear sense of what absolutely needs to get done to ensure production stability and additional deliverables, and adjust schedules to front-load the most critical items.

- [ ] **Set and share working schedules:** Encourage people to broadcast when they are and are not working, and respect their boundaries. Family life disruptions may mean longer delays for people to respond to questions in Slack or email; be patient and understanding that team members may not respond immediately, if at all. Adjust team schedules to optimize for maximum coverage (i.e. at least one person from the team is available during business hours) or maximum collaboration (i.e. all of the team is concurrently available for a shorter period of time) as necessary.

**Comment by JRRoof** [comment]
Old item, no longer relevant.
