### ISSUE TITLE
[QA] 10-10EZR: Reproduce Research User not having submitted data go to ES (Health Insurance, Financial info)

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#70259]
As a Veteran, I would like my financial information and insurance information I submit online to be updated in VES so that I am not just sending information into a void. 

- [x] Work with Josh F to determine why Friday's test user (initials AB) Medicare Part A went through, but not their new insurer or their financial information
- [x] Go through submission with our new test user (#[070264](https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/70264)) and submit insurer and financial info and work with JF to figure out if the updates are made in VES.
- [x] Link to video recording of user: [Private ZenHub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd252QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f8a8a9a1c968de29ffef76799ff6d65d2edbd1d4/P7-Submission.mp4)
- [x] Screenshots of the Review Page with Financial Info and Insurance Info:
<img width="454" alt="Screenshot 2023-11-21 at 6 55 52 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/117132709/e0385053-b790-4df9-a94c-343d0273f333">

<img width="460" alt="Screenshot 2023-11-21 at 6 56 14 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/117132709/d77a60b4-c111-45c8-84ae-e988f876d630">

<img width="470" alt="Screenshot 2023-11-21 at 6 56 48 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/117132709/d7851b78-11d6-4fff-8145-842d752e9cd9">

<img width="483" alt="Screenshot 2023-11-21 at 6 59 57 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/117132709/193630ed-04d8-46ad-857a-ab3329b692cc">

- [ ] **Success: We reproduce the issue the research participant had on Friday**

*This is not necessarily all encompassing of the test scenarios

**Comment by fbonds** [comment]
attached video is 21 seconds long and only shows user clicking agreement checkbox and submittal success.  Will follow up with Hieu.

**Comment by fbonds** [comment]
Results were twofold:
1. No repro of the failure to transmit Insurance info.  In my test that worked.
2. Transmission of financial data is not working.

**Comment by hdjustice** [comment]
Tests have been completed today - all successful as expected
