### ISSUE TITLE
[QA] 10-10EZR: Edit test users for EZR testing

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#70264]
As a user with below 50% disability, I would like to know that when I submit my information that it goes into the Enrollment System and updates my Priority Group so that I know I'm not just submitting data into a void.

- [x] Come up with list of users for different EZR scenarios (see list below)
- [x] --Lihan suggested vets.gov.user+11@gmail.com (but we don't know if they're enrolled)
- [x] Reach out to the Disability Team and ask if they can create a new user or modify an existing user to have the above requirements ([#benefits-disability](https://join.slack.com/share/enQtNjIwOTA3OTY5Nzg0Ny0zOGVlZjdhMDFiNmFhMDQzNTJlNjFkZWVkYzE3YmFjZWJlMmJlOTkzYzcwMGVkOTBlYzQ1Y2NiYTgzZWRkMjcw))
- [x] We will use this to test 1) user research user who submitted dummy data on Friday that didn't make it into VES (10% Disability), and 2) If an Enrolled user submits financial information for the first time this year, is a Means Test automatically run?
- [x] Identify which test accounts (e.g. 11, 121) we would like changed and what of their info we would like changed
- [x] Send list of changes to Emily Theiss
- [x] Review to make sure 
- [x] **Success: We have a test users needed to test different EZR scenarios**

**List of EZR Test User Requirements (to send to Emily Theiss**

1. Enrolled user below 50% Disability (user 11 has been suggested)
2. User with pending MT below 50% Disability
3. User with pending_other with below 50% disability

**Comment by fbonds** [comment]
Requesting as follows:

We’d like the following changes made to the named accounts:

1. <50% disability Jaime Lee Brooks, SSN: 796186272, vets.gov.user+12@gmail.com
2. <50% disability and status of “pending_mt”
	Allan Butler, SSN: 796127023, vets.gov.user+15@gmail.com
3. <50% disability and status of “pending_other”
	Pauline E Foster, SSN: 796330625, vets.gov.user+38@gmail.com

@alexseelig, please remove references to vets.gov.user+11@gmail.com.  That user is not enrolled and cannot access EZR.

**Comment by fbonds** [comment]
tagging you @alexseelig so you see these comments.  thanks
