### ISSUE TITLE
[QA] 10-10EZR: Is Means Test automatically triggered when user submits online EZR w/ financial info for first time in calendar year?

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#70267]
As a Veteran, I would like my financial information to be reviewed when I submit it for the first time in a calendar year so that I know I'm not paying co-pays when I don't have to based on my income and expenses.

- [x] User new user with disability <50% and enrolled to submit financial info
- [x] Work with Josh F. to determine if this automatically triggers a Means Test in VES
- [x] **Success: Determine if a Means Test is automatically triggered when a user submits their financial info for the first time in a calendar year**

*This is not necessarily the entirety of the test case

**Comment by fbonds** [comment]
@alexseelig we need to close this ticket.  Per JF there is no "triggering"

Ref his comment: "i don't know why you guys all keep using that term 'trigger a means test', that is not a thing. what happens when EZR is submitted is unknown for most of these scenarios, it has been dormant for a decade and has not been changed anytime recently."

**Comment by hdjustice** [comment]
We found that Joshua F can remove financial disclosure data from ES so that when we enter new financials in the EZR submission, a means test is completed.  
A bug was found during testing this scenario, which has to be prioritized by the Member services (HEC) team before we can continue testing.

**Comment by hdjustice** [comment]
all non-financial related data can be updated. Only when there are no financials on record/no means test on record, will the form allow the user to enter financials, spouse/dependents information. Then a means test is done automatically
