### ISSUE TITLE
Schema Change - Semicolon in Address Lines

### ISSUE THREAD

**Issue by tfink419** [department-of-veterans-affairs/va.gov-team#70276]
Result of research done in #67522. When a semicolon is entered into the address line, it causes a claim error.

### Tasks
- Handle semicolon in address lines on veteran information form
- This will likely be handled in the **vets-json-schema** repo
  
Field:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXp3QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--64ca025db9008bf5feed0771fd3f7dce8257da8f/Screenshot%202023-11-20%20at%2011.40.52.png)

### Acceptance Criteria
- User can not enter semicolon's into address lines and proceed on form
- The backend should also validate this using the schema

**Comment by steele-lm** [comment]
Validate we are using the current form system component for address inputs. Robin Garrison can confirm.

**Comment by steele-lm** [comment]
@tfink419 @tblackwe This ticket was written a while ago, so I wanted to confirm the best solution:
- Do we allow the user to enter a semicolon and then strip it out post-submission? Or,
- Do we alert the user to an invalid character and stop them from proceeding until they remove it?
