### ISSUE TITLE
Ensure Datadog actions are present to track user flows on MHV landing page

### ISSUE THREAD

**Issue by carlosfelix2** [department-of-veterans-affairs/va.gov-team#70285]
### User story

As a Cartographers team member, I want to be able to track user's clicks as Datadog "actions," so that their journeys can be tracked with funnels.

### Notes
- ~The links on the landing page are not generating Actions by default, but they _**should**_ per an email exchange with DD support (Wes has email)~
- UPDATE: on 3/19/24 Wes was able to see the default actions. Either something changed or it was user error in the past. The only remaining task/AC is to review naming conventions for clarity

Possible tasks
- Review action naming conventions within DD funnel tool for clarity
- Check secure message codebase to see if some of their more complex actions were given custom names (e.g. `click on Messages Inbox Compose message Manage folders`)

<img width="255" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/4054752/d6cffe97-5b18-47f5-8edf-118232c7fe8f">

## Acceptance criteria

- ~Discovered what is necessary to get default and custom Actions tracked when links are clicked~
- Ensured DD actions are tracked and named clearly for all links on landing page, including those in conditional alerts

**Comment by wesrowe** [comment]
Note: I have a support thread going with DD to get a few questions answered:

1. Why can't configure funnels with all the Views we want, e.g. across "applications" (e.g., SM, landing page)
2. Why aren't the links on the landing page automatically generating Actions in DD RUM?

**Comment by wesrowe** [comment]
Re actions in RUM (number 2 above):
>For Browser RUM, "click" actions will be generated by default - if you notice that these are missing, the issue may be due to the RUM SDK being initialized after certain scripts/packages/clients/etc: https://docs.datadoghq.com/real_user_monitoring/browser/troubleshooting/#missing-data 

> 
> Can you please share how you instrumented the RUM SDK here? 
>  
> If you're looking for other actions, I would recommend configuring custom actions to be sent as follows: https://docs.datadoghq.com/real_user_monitoring/browser/tracking_user_actions/#send-custom-actions
>  
> Best,
> 
> Danny Serrano | Solutions Engineer

**Comment by wesrowe** [comment]
update: I went into DD and confirmed the default actions are being tracked. The AC around naming conventions seems to be met – the actions are exactly the wording of the link text. The only potential issue I see is that links with the same link text on different pages may be hard/impossible to tell apart when building a funnel. E.g., right now "click on Inbox" is (almost certainly) the "Inbox" link on the landing page; but it's easy to confuse this action with "click on Go to your inbox", which is most likely in the SM tool.

**Comment by wesrowe** [comment]
can close
