### ISSUE TITLE
[DISCOVERY] Vets-API rate limiting

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#70286]
### Summary
The question of rate limiting was brought up [in this Slack thread](https://dsva.slack.com/archives/C0460N83Y9G/p1699911063511949). Vets-api has some rate limiting happening in [our rack-attack config](https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/initializers/rack_attack.rb) but more could be done by using rack-attack or by using Traefik (as suggested in the Slack thread) by adding something to [ingress_route.yaml](https://github.com/department-of-veterans-affairs/vets-api/blob/parent-helm-charts/chart/templates/ingress_route.yaml) (see [traefik docs](https://doc.traefik.io/traefik/middlewares/http/ratelimit/))

### Questions to answer
1. Do we as Platform engineers want to expand rate limiting in vets-api? 
2. What are the upsides and downsides (see chatgpt section below for ideas)?
3. If we do, should global rate limiting happen in the manifest repo (by Traefik) or should it be done by the rack-attack gem in the Rails layer?

### Acceptance Criteria
- [x] Write up findings in Confluence.
- [x] Write followup ticket to get findings reviewed by other members of Backend COP.

----
### Extra info from ChatGPT 
I asked ChatGPT what we might want to consider when implementing rate-limiting. It gave me the 11 items below. **They don't all need to be considered for this ticket**, but they might help with the discovery and scoping of the task.

Rate limiting is essential for protecting your API from overuse, whether unintentional or malicious, such as in Denial-of-Service (DoS) attacks. Here are some important considerations:

1. **Understanding the API's Capacity and Usage Patterns**: 
   - Determine if there's monitoring set up to assess the typical and peak usage patterns of your API.
   - Understand the API's capacity and how much traffic your infrastructure can handle without degradation.

2. **Setting Rate Limits**:
   - Determine appropriate limits based on typical usage and capacity. This could be in terms of requests per second, minute, hour, or day.
   - Consider different limits for different types of users or endpoints. For example, write operations might be more limited than read operations.

4. **User Communication**:
   - Clearly communicate rate limits in your API documentation.
   - Provide headers in API responses that inform users of their current rate limit status, like `X-RateLimit-Limit`, `X-RateLimit-Remaining`, and `X-RateLimit-Reset`.

5. **Dynamic Rate Limiting**:
   - Implement more sophisticated, dynamic rate limiting based on real-time data, user behavior, and system health.
   - Consider higher limits for trusted or premium users.

6. **Graceful Handling of Rate Limit Exceeding**:
   - Ensure your API responds with appropriate HTTP status codes (typically `429 Too Many Requests`) when a user exceeds their rate limit.
   - Provide meaningful error messages explaining the reason for the rate limit and when the user can try again.

7. **Security Considerations**:
   - Protect against DoS attacks and abuse while ensuring legitimate users are not adversely affected.
   - Monitor for unusual traffic patterns that might indicate abuse or attacks.

8. **Performance Impact**:
   - Consider the performance impact of the rate limiting mechanism itself, ensuring it doesn’t introduce significant latency.

9. **Scalability and Flexibility**:
   - Your rate limiting strategy should be scalable and adaptable to changes in user behavior and infrastructure.

10. **Compliance and Legal Considerations**:
   - Be aware of any legal or compliance issues related to data access or user treatment, especially in APIs that handle sensitive or personal data.

11. **Testing and Monitoring**:
    - Regularly test the rate limiting system to ensure it works as expected and adapts to changing conditions.
    - Monitor the effectiveness of rate limits and adjust as necessary.

12. **Fallback Strategies**:
    - Have a plan for handling legitimate cases where the rate limit might impede critical operations.

**Comment by laineymajor** [comment]
Complete :)
