### ISSUE TITLE
Header and Footer Injection for VA Public Health Site

### ISSUE THREAD

**Issue by KevinMHoffmanUSDS** [department-of-veterans-affairs/va.gov-team#7028]
## User Story or Problem Statement
As a visitor to the public health website of the VA, I need the regular site header and footer so I can connect to the rest of the VA.

## Goal
Header and footer injection on http://www.publichealth.va.gov/

Staging: https://vaww.w2k8.internet.staging.va.gov/PUBLICHEALTH/

## Tasks
- [ ] Add both sites to the whitelist for header footer injection. 

## Acceptance Criteria
- [ ] Header and footer injection on http://www.publichealth.va.gov/

**Comment by KevinMHoffmanUSDS** [comment]
@ricetj @rianfowler This is related to our larger body of Covid-19 work. If you could prioritize someone getting this done quickly, we'd appreciate that. cc @chrisj-usds

**Comment by chrisj-usds** [comment]
One note of detail. 

We'd like to test this on their staging location first to see what rendering problems there are, and how difficult those might be to remedy. 

If there are none or they're straightforward(-ish) to fix, then I'll get the go ahead to push from staging to prod.

**Comment by KevinMHoffmanUSDS** [comment]
@chrisj-usds Thanks! Just to be clear for all parties, the injection code has already been added to staging, correct?

**Comment by chrisj-usds** [comment]
That is my understanding, yes. (On both staging and prod, I'm told.)

**Comment by KevinMHoffmanUSDS** [comment]
Thanks!

**Comment by chrisj-usds** [comment]
Any news to share on this?

**Comment by KevinMHoffmanUSDS** [comment]
Update from @rianfowler:
We pushed the ops changes needed for it last night. I’ll be working on the FE changes this morning. 
I don’t know if we can test in their staging environment. We were never able to do that if I remember correctly but I can set it up so they can test it in prod before it goes live

**Comment by KevinMHoffmanUSDS** [comment]
@chrisj-usds This should go into production today at 3pm assuming there are no CSS issues revealed.

**Comment by KevinMHoffmanUSDS** [comment]
Adding this link for the next brave soul that encounters this issue. https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/architecture/teamsite

**Comment by chrisj-usds** [comment]
Hang on.... I'm very specifically not wanting it to go into production right immediately!
What I wanted to see was how it worked on the staging site, and if there were any rendering issues that needed to be addressed. (There usually are.) That is a giant site with many pages, and we don't want to break anything.

**Comment by rianfowler** [comment]
Couple of things to note:
- When this was built during WBC, we added a way into the header injection to test it in production behind a flag. We've used this for the last couple of rollouts.
- I think we tried to test this in the Teamsite staging environment during WBC but couldn't get it to work. We can revisit this, though.

**Comment by rianfowler** [comment]
The change is up on staging so you can test it with these instructions: 

1. Navigate to https://publichealth.va.gov
2. Open console (F12) 
3. Run the following in the console: 

```
document.cookie = "proxyRewrite=true;"
```
_Most browsers echo the statement when it works_

4. Navigate to https://www.publichealth.va.gov/?targetEnvironment=vagovstaging

_Since this is on just on staging right now we need to tell the injection script to point there. After the daily prod rollout the query param won't be necessary_

## Chrome

![Screen Shot 2020-03-20 at 12 20 39](https://user-images.githubusercontent.com/4998130/77183824-51a2e700-6aa5-11ea-8e43-e1845ac08ec7.png)

![publichealth](https://user-images.githubusercontent.com/4998130/77183281-79de1600-6aa4-11ea-8abe-95791626dd1b.gif)

## IE11 on Browserstack

![Screen Shot 2020-03-20 at 12 21 04](https://user-images.githubusercontent.com/4998130/77183855-56679b00-6aa5-11ea-8a71-1b1f24c751ca.png)


![publichealthIE11](https://user-images.githubusercontent.com/4998130/77183400-a2fea680-6aa4-11ea-9e5c-29e71d257b7b.gif)

**Comment by rianfowler** [comment]
Merge [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/11962) when we're ready to push this to prod.

**Comment by brandonrapp** [comment]
We will wait for @chrisj-usds to give the final go ahead before merging!

**Comment by KevinMHoffmanUSDS** [comment]
Look at those videos! Just look at them. They are awesome.

**Comment by meganhkelley** [comment]
Hi @chrisj-usds cc: @KevinMHoffmanUSDS should we go ahead and merge this? Thanks!

**Comment by meganhkelley** [comment]
Hi there @chrisj-usds and @KevinMHoffmanUSDS can you please confirm that this should be merged? Thanks!

**Comment by chrisj-usds** [comment]
Wow. I completely forgot this was hanging out there. 
Let me check in with our partners in OPIA if this is a "go". It's still in staging I guess?

**Comment by meganhkelley** [comment]
Hey @chrisj-usds ! This work was looped in with another series of header/footer injections that we are also waiting for direction on: https://github.com/department-of-veterans-affairs/va.gov-team/issues/5086#issuecomment-626763680

@jholton can you describe the current status of the PRs in that linked list? Are those all in staging currently?

**Comment by meganhkelley** [comment]
Ack sorry @jholton wrong tag — @jhonnyoddball see above

**Comment by jhonnyoddball** [comment]
@chrisj-usds the changes are up in staging and can be tested using [these instructions](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7028#issuecomment-601788895)

The list of all the new hostnames is [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/5086#issuecomment-626763680)

**Comment by meganhkelley** [comment]
Moving this to backlog until we have further direction from DEPO cc @jenniferlee-dsva @KevinMHoffmanUSDS @chrisj-usds @hampshire100

**Comment by timwright12** [comment]
@meganhkelley Should we pick this back up?

**Comment by jhonnyoddball** [comment]
@laineymajor I'm not sure if this is something that needs to be done. We will need to check with DEPO.

**Comment by jhonnyoddball** [comment]
Expired. Closing
