### ISSUE TITLE
Google Analytic reports for users that are registered with a facility

### ISSUE THREAD

**Issue by carlosfelix2** [department-of-veterans-affairs/va.gov-team#70282]
### User story
As a Product Manager in the MHV ecosystem, I need to be able to easily build reports on user flows that and segment them by the user's registration status (if the user is registered at one or more facilities), so that I can report on user journeys to stakeholders.

### Notes
- This story is different than #70281 in that we want a property in Google Analytics that explicitly shows if a user is registered or not to a facility for any page visited, regardless if it is the MHV landing page or not.
  - **Wes: clarification** – are we sure that the analysis enabled by the segmentation of #69057 is not going to meet a critical analysis need? This facility-registration use case is the case that was selected for that story
- This story can be implemented by adding a custom GA property/dimension to Google Analytics and set it to their registration status. This could be set at login or when revisiting the site.
- There is a risk that segmenting users by this property can exclude users if they register at a later time. Consideration should be taken as to the scope of the property/dimension. E.g. perhaps a session scope is the way to go. Note that a user scope has a higher risk of having the user register at a later time (data in the property/dimension is overwritten within a scope).
- Any additions to custom GA properties/dimensions should be FIRST discussed with the Analytics team. Note we have team members with write access that can add the property if needed.
- Will this new property by for GA3 or GA4? Both?

## Acceptance criteria
- Determine what, if any, custom properties/dimensions are needed.
- If a new custom property/dimension is needed, provide the information to the Analytics team and get approval.
- If approval is received, add the properties/dimensions to GA.
- If approval is received, implement the necessary changes to log the data into the new custom property/dimension.

**Comment by wesrowe** [comment]
We can see now in GA4 thanks to alert render events
