### ISSUE TITLE
Set up Figma access

### ISSUE THREAD

**Issue by RenataKeck** [department-of-veterans-affairs/va.gov-team#70291]
Extended details about each step in Figma migration can be found on the [Platform Website](https://depo-platform-documentation.scrollhelp.site/research-design/how-to-move-your-work-from-sketch-to-figma) (see also: [#platform-design-system](https://dsva.slack.com/archives/C01DBGX4P45/p1702322526760389) Slack channel)
- [x] Receive invitation to Figma (note: all users with Editor access in Sketch will automatically be sent an invitation to Figma). 
- [x] Prepare Sketch file, including archiving all comments
- [x] Download Sketch files
- [x] Find new project in Figma
- [x] Import Sketch file into Figma
- [ ] Set custom thumbnails
- [x] Enable VA design library
- [ ] Clean up file
- [x] Invite the rest of the team

**Comment by uxrebecca** [comment]
While we're waiting both Renata and I got Sketch access.

**Comment by RenataKeck** [comment]
Emails have been sent out to the team for access to our files. Direct link [here](https://www.figma.com/file/C3sdnDf8anVqXVdmiCWwq8/%F0%9F%9A%A7-Accredited-Rep-Facing?type=design&node-id=0%3A1&mode=design&t=5J0tyHhIb4TA1DKh-1). 

Refraining from cleaning up the current file as there was discussion of archiving it.
