### ISSUE TITLE
Research planning: Internal SME Interviews

### ISSUE THREAD

**Issue by RenataKeck** [department-of-veterans-affairs/va.gov-team#70297]
Planning for interviewing subject matter experts within the VA, as recommended by stakeholders.

Deliverable: [SME Research Plan](https://docs.google.com/document/d/1i7SGMj0ishpbNZ1tRYY_ZKZL_I9hHiQm6JXUnwT-oT4/edit).

Acceptance criteria:

- [x] Research goals validated
- [x] List of SMEs prioritized
- [x] Interview questions written per SME interview
- [x] Conversation guides written per SME interview

**Comment by uxrebecca** [comment]
I'm working on a [research plan here](https://docs.google.com/document/d/1i7SGMj0ishpbNZ1tRYY_ZKZL_I9hHiQm6JXUnwT-oT4/edit).

**Comment by uxrebecca** [comment]
Update:
- Research goals 90% done. Lesley has reviewed. Just waiting for Rivka to see if we want to keep this goal in there: "Understand the current state for appointing power of attorney to a VSO using Form 21-22."
- First SMEs prioritized and interviewed: Melissa, Laurie, and Marty. Also removed the ARM team from the list. We still need to prioritize the rest of the list when Lesley is back from PTO. I think we might want to interview Brandi Taylor and Alejandro Mendiola next and then a couple of people from the Lighthouse team.
- Wrote interview questions for our first two interviews and have drafts of questions for the rest which will refine once we've prioritized.
- Conversation guides written for both interviews and notes are now uploaded in Sharepoint.

**Comment by uxrebecca** [comment]
Update: sent invitations to our two VBA colleagues (Brandi and Alejandro). Have a more informal coffee chat with Melinda from Lighthouse, but we might extend this or do a more formal session since she's the person that Kayla recommended with speak with.
