### ISSUE TITLE
Access for Nathaniel Johnson (new ssh key)

### ISSUE THREAD

**Issue by NateJohnson-BAH** [department-of-veterans-affairs/va.gov-team#703]
My ssh keys somehow got deleted or moved or something. I re-created them, and need my public key added again for access to VA internal tools. Thank you. 

#Description
- Please provide your Contracting Officer's Representative (COR) name.
   > ??
- Please provide your name.
   > Nathaniel Johnson

- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > BAH-charleston

- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Internal%20Tools.md#create-ssh-public-key) for instructions.
  > ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDCi79+4UGXMF7ckDEj+GqGnHuB/j95B3zxXmRP6IE4L9kQPGriewQzAv8iVQiwzUf6f05RquuwD8GDsQLHfeoGLMWuvy4JarDLgo+7CjahAcaubNYe+BulJtqkPaxv+UDzkeqxuNheQZPmXaeH+Vp/6rR1bLyiq84NkbQL3yP1UDcLYbrgr6SYkBPuJB2k2geCFnEaqrVr2/SD63G/nxLTNOq3pbhY6+gOqM18tFGJ7SLAW7/0zY4oIMTyoDem12BG3oZz6P13TagmDBcchse6jU8L+MZVUOiSqvo/ZzxD1DB/Aqz9pTqMhRZ6ht1NcI1slf+Ve2WopWosQ8yHeJQ9 nathanieljohnson@C02T87F2H03Q.local

- [Grant AWS Console access?]
  > NO

**Comment by NateJohnson-BAH** [comment]
@department-of-veterans-affairs/vsp-operations I have managed to delete or lose my ssh keys. I have since re-created them in an attempt to regain access to internal tools. Please let me know if you need anything else from me, thank you.

**Comment by tskinn** [comment]
Your key has been updated.
