### ISSUE TITLE
[Incomplete] Review prior research - Kara

### ISSUE THREAD

**Issue by RenataKeck** [department-of-veterans-affairs/va.gov-team#70307]
- [x] Add questions as you go to the [Claims Evidence - Open Questions doc](https://docs.google.com/document/d/14kgbh_CclsTsbg81lM1W2IBKi_ooNW76o7AW-NaGlh4/edit#heading=h.d4jxmmpec8n1)
- [x] [Improving Evidence in Disability Claims] (https://drive.google.com/drive/folders/1SF3Jdr0g4nVcejXqDWcqjw89VSRB-pxK)<- Read through the resources under the Next Steps. Some of those overlap with the links I've shared below. 
- [x] [Criteria for selecting contentions to fast track](https://app.mural.co/t/nava4113/m/nava4113/1623700197686/c6175205686de33eb4aea4a319f88faa33b88fd5?wid=0-1644435518079&sender=ua71936780d8bc9a2d2b29830)
- [x] [526 Form Flow Active (Mural)](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1686768383603/3f4415dd2ddb71bbd104ebefd92a2c7b553ad792?sender=ua71936780d8bc9a2d2b29830)
- [x] [**EE Idea Vetting RICE - June 2023**](https://docs.google.com/spreadsheets/d/1Sb0eJwyq2eUBjwBB5Y3nAXhNrXcgZO7tqVx_o1r_MVc/edit#gid=0)
- [x] [VSR Research for Claims Fast-Tracking Ideation](https://docs.google.com/document/d/1SSJ87rYRG0DuRYbTSqz9TUuhTNqh_dxUlpUwCCTG6EI/edit#heading=h.4gddj35qseyt)
- [x] [**Claims Fast Tracking Crew Problem Space**](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1684352754931/fc8a7fd10083442790a6fdfceaed111ef2472ecf?sender=ua71936780d8bc9a2d2b29830)
- [x] [EP400/multi-issue claim](https://app.mural.co/t/departmentofveteransaffairs9999/m/gsa6/1642095217957/64c2b15a618318973bc36179880686d2b6220277?sender=ua71936780d8bc9a2d2b29830)
- > assumption: this is being worked on ("reduce the burden of EP400s"). If so, by who? 
- > how does evidence differ in the context of a multi-issue claim?
- > what is the frequency of multi-issue claims (vs single)?
- [x] [Claims Establishment - Discovery Research](https://github.com/department-of-veterans-affairs/lighthouse-ux/blob/master/Benefits%20and%20Appeals%20Research/2019-08-Claims-Establishment-Discovery-Research/Claims%20Establishment%20Discovery%20-%20Research%20Presentation%20-%20September%202019%20-%20UPDATED.pdf) 
- [x] ["The Manual" - what VSR/RVSRs use to adjudicate a claim](https://www.knowva.ebenefits.va.gov/system/templates/selfservice/va_ssnew/help/customer/locale/en-US/portal/554400000001018/content/554400000073398/M21-1-Adjudication-Procedures-Manual-Table-of-Contents) <- don't read this whole thing, really just a good place to dive in deeper to understanding points in the journey of a claim
- > Who uses this? 
- > How do they actually use it? 
- > What does their process look like (are there places they start, what's helpful, what's not helpful)?
- > Have their been efforts to redesign this / make it more digestible?
- [x] [The PACT Act and your VA Benefits](https://www.va.gov/resources/the-pact-act-and-your-va-benefits/) <- another quick skim; this is going to be the bulk of all claims, it's like 90% of disability claims right now.
- [x] [ABD Design and Research Index](https://docs.google.com/document/d/1On6dxbygCR0-tQWyUF0sF8v6A3TrHGbxVnfaUM40-iU/edit#heading=h.ajia8sm4jjwm) <- focus on foundational/early research and PACT Act, at least for now. Look at final reports and Mural boards. If you have time, skim other types of claims. 
- [x] >>> Contention Classification - VSR Shadowing 1 & 2 (recommended by Sudeepti) [[Link](https://docs.google.com/document/d/1On6dxbygCR0-tQWyUF0sF8v6A3TrHGbxVnfaUM40-iU/edit)]
- [x] [What makes ratings criteria objective? ](https://drive.google.com/file/d/1v-qDnVUq7dPcGlU-osa-sbxxkq8LN-31/view)<- skim this. Discusses how The Manual translates to ratings scores on disability claims. when we talk about enough/sufficient evidence, think about how the ratings criteria could be linked to evidentiary data.
- > Who is "Paul" & what is his role?
- > Is it the RVSR who is in charge of rating?
- > How are ratings connected to evidence today?
- [x] [Brief: recommended contentions for rapid ready decision in 2022](https://drive.google.com/file/d/1zQEMc2mzjqyLJrP-PTX4IiVY4BtZvx2v/view) <- read through, same as prior link. 
- > The info under "General operational and technical implications for adding
contentions" could be helpful when understanding potential technical constraints for our team
- [x] [Evaluating next contentions for RRD ](https://app.mural.co/t/nava4113/m/nava4113/1639419931630/e7287d1ac62e6fa52356a447bcfae86356143d56?wid=0-1639598087492&sender=ua71936780d8bc9a2d2b29830)
- [x] [Title 38, Chapter I Part 4](https://www.ecfr.gov/current/title-38/chapter-I/part-4) <- More background to skim

**Comment by hdbaines** [comment]
Add Kara New Ticket- add bullet about walkthroughs of prior research artifacts with VA/Enabling Team
(https://docs.google.com/document/d/1SSJ87rYRG0DuRYbTSqz9TUuhTNqh_dxUlpUwCCTG6EI/edit#heading=h.4gddj35qseyt) @gabezurita
