### ISSUE TITLE
[FE] Fix details links on landing page

### ISSUE THREAD

**Issue by wullaski** [department-of-veterans-affairs/va.gov-team#70311]
Details links on the new landing page go to a complete page when clicked.  They should go to a details view for that appointment.

The issue is that the details component is looking in the appointments payload and not the upcoming appointments payload, so there is no match to show details.

Possible solutions:
 - Search in both payloads (which one has priority if appointment exists in both?)*
 - add a unique path for upcoming appointments detail pages

*Brian prefers this solution, but keep in mind he is pretty dumb

**Comment by brianseek** [comment]
Moving to closed since there is nothing for UX or product to validate on this bug fix
