### ISSUE TITLE
Feature flag self-schedule and turn off for all users

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#7031]
VA Leadership has directed VAOS teams to turn off self-scheduling for VA appointments for the next 90 days. 

## AC:
- [ ] User cannot self-schedule VA appointments
- [ ] Place self-scheduling for VA appointments behind feature flag
- [ ] Test to ensure self-scheduling flow is not accessible within VAOS by Veterans

**Comment by jbalboni** [comment]
This works like I would expect. Users are always routed to the request flow, no DS related eligibility requests are made.
