### ISSUE TITLE
Design System Staging Review - IA Feedback - Minimal Header

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#70313]
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

Thanks, y'all - I'm excited to see this move into production! Hoping we see teams adopting it soon.

Looking forward to hearing the readout from the forms team about their research on this.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

### Must
- Update the "View guidance for the Minimal header component in the Design System" link in the [storybook file](https://design.va.gov/storybook/?path=/docs/components-va-minimal-header--default) to go to [the proper guidance page](https://design.va.gov/components/header/header-minimal)

### Should
- Add missing views in Sketch: desktop view with subheader; tablet views

### Consider 
- Mention/link to guidance about using the mobile/task-based breadcrumbs, rather than standard breadcrumbs, for apps using the minimal header.
- Mention checkin explicitly as an example use case for "An experience outside of the VA.gov site-wide information architecture" - I think it'll be helpful to have the example.
- Are there instances when the subheader would be anything but the official title of the form? This guidance could be clarified a bit more.

**Comment by caw310** [comment]
Closing as the must issue is fixed
