### ISSUE TITLE
[MVP] Step 1 Applicant Info: Add new question for mailing address

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#70329]
## Note
Part of the larger effort to update the existing 527EZ form to add missing fields/info and remove depreciated fields.

## Description
On the Step 1 Applicant Information page:

Add a new question for: `I receive mail outside of the United States on a U.S. military base`

This question will include expandable supporting copy.
When collapsed, the copy will be:
`Learn more about military base addresses`

When expanded, the copy that shows underneath will be:
`The United States is automatically chosen as your country if you live on a military base outside of the country.`

This new question will be shown _**before**_ the `Country` question/field.

## Designs

- Question unchecked: https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/AB41C46A-E35D-4E6E-9022-90EAAB6C76A5
- Question checked: https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/F31E37AB-40A4-49FF-A9AD-10B32A4FB7AE
- Use flow view: https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/v/myZ4d9/p/6571319D-6329-4249-B0A7-E39DA9DA31F4/canvas?posX=-14769.077524610599&posY=-26090.72803282807&zoom=0.2173890918493271

## Acceptance Criteria

- The new question will be added as shown on the designs.

## Tasks
- [ ] Front-end work

## Review

- [x] Reviewed by @vbellissimo; findings added to comments below.

## Artifacts
- [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/527EZ-reactivation-initiative-brief.md)
- [User flow in Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683826730324/61b509f935adaa2acf2f7769a5ba911726a7b237?sender=u9d01ee38af217e4877e75660)
- [Prototypes in Sketch](https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/p/6571319D-6329-4249-B0A7-E39DA9DA31F4/canvas)
- [Spreadsheet of deleted form fields](https://docs.google.com/spreadsheets/d/1PTXxO6mFH2ZUK6XxX7iCCQb-NoSvhB5P/edit?usp=sharing&ouid=104362113771391164792&rtpof=true&sd=true)
- [Content source of truth/PDF form](https://www.vba.va.gov/pubs/forms/VBA-21P-527EZ-ARE.pdf)
- [Link to testing accounts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/form-deactivation/527EZ-staging-test-accounts-accessible.md)
- [Link to staging](https://staging.va.gov/)

**Comment by ToddWebDev** [comment]
Developer Note: The 'addressNoMilitaryUI' schema in [addressPattern](https://github.com/department-of-veterans-affairs/vets-website/blob/04533beb8760e39fcdf957a1280c23e92e90192c/src/platform/forms-system/src/js/web-component-patterns/addressPattern.jsx) meets the acceptance criteria. It's also referenced [here](https://design.va.gov/patterns/ask-users-for/addresses#examples)

**Comment by TaiWilkin** [comment]
@mayacoforma I have a question about the warning message ("Postal code is within the US...") from the designs. As Todd mentioned above, there's a component that already exists for an address form with a military base checkbox. In this component, when the address is in the US or is a military base, the postal code input doesn't attempt to determine whether it's a US ZIP code or not; it just returns a validation warning if the code isn't five digits. I did some digging into military base ZIP codes, and it does look like they're 5-digit numerical codes as well. 
I could attempt to create a custom solution and warning, but I would need some more information on how to tell if a code belongs to a military base or not, and I'm not sure that the extra time spent makes sense when the existing component does at least a basic validation. What are your thoughts on how to proceed?

**Comment by mayacoforma** [comment]
@TaiWilkin Certainly, Tai, your question is quite insightful. Sometimes, there may be inconsistencies between the VA sketch components and the VA design system. In such cases, our approach is to consistently prioritize the latest components found at https://www.va.gov/ over the mockups. No custom creations are necessary for this situation.

**Comment by vbellissimo** [comment]
@TaiWilkin , is there a reason the copy in staging differs from the Sketch files? Is it because you're following the Design System approach instead?

<img width="882" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3cxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8a8bb1c35559f2fd1f1b2c5313cb1618c807fadc/Screenshot%202023-12-05%20at%204.25.33%E2%80%AFPM.png" alt="Screenshot 2023-12-05 at 4.25.33 PM.png" />

**Comment by TaiWilkin** [comment]
@vbellissimo No, I had overridden it with a new label, but it looks like that broke when I updated the imports and I missed it. I'll add a commit with a fix to my current PR - it should just be a couple lines of code to re-implement it.

**Comment by vbellissimo** [comment]
@TaiWilkin, sounds good... thanks for catching that and fixing :D
