### ISSUE TITLE
CT: Restore the distance learning filter

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#7032]
As someone interested in using their education benefits in a distance learning program, I need to be able to search specifically for those programs so that I can more easily find relevant institutions. 

Assumptions: 
1. These changes will be placed behind a prod flag so that they are only available on staging when merged into the master branch. 

## Acceptance Criteria:
1. The following filters are available in the non vettec search results:
     - Online Only
     - Distance Learning
2. The following programs are available in the Veteran programs section of the profile:
     - Online Only
     - Distance Learning

## Supporting Artifacts:
1. ![AC1](https://user-images.githubusercontent.com/48260534/70912264-94a27980-1fe1-11ea-963a-4b7ff72f648e.png)
2. ![AC2](https://user-images.githubusercontent.com/48260534/70912261-94a27980-1fe1-11ea-97ff-0608e26e7c6d.png)

Notes: 
1. Story we are reverting is #4275. 
2. PR we are reverting is https://github.com/department-of-veterans-affairs/vets-website/pull/11334

**Comment by dneel-bah** [comment]
Closing this as OBE due to redesign effort (epic #13502)
