### ISSUE TITLE
[Data/Dev] 10-10EZR: Set up Datadog alerts for EZR

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#70332]
As a Veteran, I would like the 10-10 team to be notified if there is a problem with my EZR submission so that I know it will be fixed and I will be able to update my information online. 

- [x] Create DD alerts for EZR
- [x] Use EZ as the baseline for creating alerts
- [ ] Add anything in that might be unique to EZR
- [x] Sign up the team for these alerts
- [x] Test alerts (work with QA/Dev as needed)
- [ ] **Success: We get DataDog alerts if something goes wrong with EZR**

**Comment by luis-simauchi** [comment]
to replicate/emulate the alert set up we have in place for the 1010EZ today, we will need to create 3 alerts monitors. 

controller error rate is above 5%
submission has failed with no retries left
volume of submissions are anomalous low or high

**Comment by luis-simauchi** [comment]
Chapley has already created a monitor of the controller error rate is above 5%
Moving on to the other two monitors needed for EZR

**Comment by luis-simauchi** [comment]
metrics to key off for EZR monitors:
- vets_api.statsd.api_1010ezr_submit_form_fail
- vets_api.statsd.api_1010ezr_validation_error
- vets_api.statsd.api_1010ezr_failed_wont_retry
- vets_api.statsd.api_1010ezr_submit_form_total
- vets_api.statsd.api_1010ezr_submission_attempt
