### ISSUE TITLE
[MVP] Step 1 Applicant Info: Add new question for email

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#70330]
## Note
Part of the larger effort to update the existing 527EZ form to add missing fields/info and remove depreciated fields.

## Description
On the Step 1 Applicant Information page,
under the Email address and phone number section,

Add a new required field for: `Email`

This new question will be shown _**before**_ the `Telephone number` question/field.

## Designs

- Question: https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/420716D9-6B5D-4570-8B1D-88BAC8CE67A3
- Use flow view: https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/v/myZ4d9/p/6571319D-6329-4249-B0A7-E39DA9DA31F4/canvas?posX=-20261.51106241541&posY=-26119.918519188897&zoom=0.23347553610801697

## Acceptance Criteria

- The new question will be added as shown on the designs.
- Ensure all copy, including headers, questions and buttons match the designs for all 3 pages:

## Tasks
- [ ] Front-end work

## Review
- [x] Reviewed by @vbellissimo; findings added to comments below.

## Artifacts
- [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/527EZ-reactivation-initiative-brief.md)
- [User flow in Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683826730324/61b509f935adaa2acf2f7769a5ba911726a7b237?sender=u9d01ee38af217e4877e75660)
- [Prototypes in Sketch](https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/p/6571319D-6329-4249-B0A7-E39DA9DA31F4/canvas)
- [Spreadsheet of deleted form fields](https://docs.google.com/spreadsheets/d/1PTXxO6mFH2ZUK6XxX7iCCQb-NoSvhB5P/edit?usp=sharing&ouid=104362113771391164792&rtpof=true&sd=true)
- [Content source of truth/PDF form](https://www.vba.va.gov/pubs/forms/VBA-21P-527EZ-ARE.pdf)
- [Link to testing accounts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/form-deactivation/527EZ-staging-test-accounts-accessible.md)
- [Link to staging](https://staging.va.gov/)

**Comment by ToddWebDev** [comment]
Developers Note: The current form has this page in the 'Additional Information' chapter on the last step of the form. We can just move the 'contactInformation' page from this chapter to the 'Applicant Information' chapter at the beginning of the form to get started with this task. The mailing address can be removed and added to it's own page for #70329 as well.

**Comment by ToddWebDev** [comment]
Developers Note: We can switch to these web component patterns:
- [emailPattern](https://github.com/department-of-veterans-affairs/vets-website/blob/d216c67b485bff962bd6470f20fe700b67c2b97e/src/platform/forms-system/src/js/web-component-patterns/emailPattern.jsx)
- [phonePattern](https://github.com/department-of-veterans-affairs/vets-website/blob/8c5b9c5e8099e1c603b243d55788f294c551d399/src/platform/forms-system/src/js/web-component-patterns/phonePattern.jsx)

**Comment by vbellissimo** [comment]
@TaiWilkin looks great. Thank you!

<img width="897" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzgxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--65f563cca5fc2fdc8fd99c6590dfdbcefa5edbd2/Screenshot%202023-12-05%20at%204.30.37%E2%80%AFPM.png" alt="Screenshot 2023-12-05 at 4.30.37 PM.png" />

<img width="897" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEkxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2b00b46ffe363b215b865873c91ee33ce9de3d06/Screenshot%202023-12-05%20at%204.32.17%E2%80%AFPM.png" alt="Screenshot 2023-12-05 at 4.32.17 PM.png" />
