### ISSUE TITLE
[FE] [Bug] Add comma to success alert content

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#70340]
## Description

Wireframe: https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/mPEjZRV

Within the success alert, need comma after 21

`21, 1:53:pm`

## Tasks
- [ ] [FE] **_insert frontend work_**
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations (readme and use cases)

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by loripusey** [comment]
@wullaski can we get a screenshot to validate against?

**Comment by loripusey** [comment]
validated against the english translation json file
