### ISSUE TITLE
Discovery for Implementation of new Military Service Questions 

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#70344]
## Issue Description
The 526ez and ancillary paper form gets updated when necessary. This ticket covers the following change required on the digital 526ez form on va.gov to make it sync with the paper version.

Scope of ticket is to understand and document how to implement these changes for displaying and accepting data for these military service questions in the 526ez flow and page:
- Question 20C on paper form to the online form: "Did you serve in a combat zone since 9-11-2011?
- Questions 21D and 21E on paper form to the online form for unit info:
  - 21D Current or last assigned name and address of unit
  - 21E Current or assigned phone number of unit

https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/64450

Acceptance Criteria
- Creation of FE and BE tickets for implementation of these new fields
- Map the new fields to LH submit API
- Discover if EVSS accepts these fields

**Comment by sethdarragile6** [comment]
Based on the [research](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1701124875509/58c65d832c28069a9597f34d0bdf57632318e981?sender=ufe55a1a25f3f25394be01959) from Christine, some workarounds are feasible to implement these changes without having to ask EVSS to change anything. On the question of whether or not it's wise to implement this before submit work is finished, it's my opinion that it is _not_- at least from the backend perspective. Lighthouse's submit endpoint is not quite live yet, and will probably need some iterations post-live to get to its final working state. Better to let the smoke clear than add fuel to the fire, in short. That said, frontend work that does NOT involve schema changes should still be doable. 

Regarding the "splitting up" of different types of addresses... I believe we should refrain from this, considering that there is only one unit address to populate on the form. This is normally Lighthouse's M.O.: "not on paper form? not on our API", which I generally agree with. Unless there is some internal logic LH would require to more correctly populate this field, there is no need to send an "address type". The service member's current/mailing addresses were also reduced to one address set each for the same reason.

**Comment by christinec-fftc** [comment]
Related tickets
[Add combat zone question#70758](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/70758)

**Comment by christinec-fftc** [comment]
Updated FE placeholder stories with latest info from the mocks. 
Move Unit Name field #71374
Add unit address and phone #71376

Also added a toggle cleanup story
Remove toggle  #71875
