### ISSUE TITLE
Review secondary research presentation - Oren

### ISSUE THREAD

**Issue by RenataKeck** [department-of-veterans-affairs/va.gov-team#70347]
Requires Sharepoint access; [recording link](https://dvagov.sharepoint.com/:v:/r/sites/vaabdvro/Shared%20Documents/Accredited%20Representative%20Facing/Past%20Research/AR_secondaryresearch_preso.mp4?csf=1&web=1&e=LOdxR0)

**Comment by hdbaines** [comment]
Iceboxed until Oren gets the correct access
