### ISSUE TITLE
Update isolated application builds howto page

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#70343]
### Description

The command `yarn cy:run --spec src/platform/site-wide/mega-menu/tests/megaMenu.cypress.spec.js --env app_url=YOUR_APP_URL` has an incorrect path and should be changed to the following:

`yarn cy:run --spec src/platform/site-wide/mega-menu/tests/cypress/megaMenu.cypress.spec.js --env app_url=YOUR_APP_URL`

In addition, I think it would be helpful to give more information about what YOUR_APP_URL should be. (the `rootUrl` property of your application in the registry.json file in content-build)

### Relevant URLs

https://depo-platform-documentation.scrollhelp.site/developer-docs/how-to-add-your-application-to-the-allow-list

### Which type of team are you on? (Platform team, VFS team, or Leadership)

OCTO engineer

**Comment by johnny-jesensky-adhoc** [comment]
Hi @acrollet, thank you for flagging this. Our team will take a look, and update the path you specified. We'll provide updates in this ticket. Thanks!

**Comment by laucon** [comment]
@acrollet perfect. I added that and it will be deployed today at 3:30. Once it's deployed, I will close this ticket.

**Comment by laucon** [comment]
@acrollet Here is the updated page: https://depo-platform-documentation.scrollhelp.site/developer-docs/how-to-add-your-application-to-the-allow-list. This is done. :)

**Comment by acrollet** [comment]
🚀 thank you!
