### ISSUE TITLE
[CST] Add 'Submitted on X' subheader to claim details page

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#70361]
## Background
We would like to add a subheading to the claim details page that indicates when the claim was submitted

## Design / Prototype
https://www.sketch.com/s/98e35645-34eb-40cf-80c1-6c4952943584/a/pYAlVOG

## Tasks
- [ ] Add subheading to claim details pages

## Acceptance Criteria
- [ ] Claim details pages have a subheading indicating when the claim was submitted

**Comment by HeatherWidmont** [comment]
Peri is working on this, we're waiting for her to get access

**Comment by HeatherWidmont** [comment]
@samcoforma will review this
