### ISSUE TITLE
Adding Michael Kinnunen to DSVA Slack

### ISSUE THREAD

**Issue by smythe5** [department-of-veterans-affairs/va.gov-team#70374]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

Are you requesting to add an individual as a:

- Full member - Yes
- Single guest
- Multi-channel
- Switching from single-channel to multi-channel?
- What channel(s) do they need to be added to? sitewide-public-websites

Please add michael.kinnunen@civicactions.com as a Full member. He is a Drupal engineer on the Sitewide Public Websites team.

We aim to complete slack requests within 24hrs.
CC @jilladams

**Comment by jilladams** [comment]
Hi folks! I know we're digging out post holiday - nudging in case you can get Michael added to Slack early this week. Thanks!
