### ISSUE TITLE
[PDF Mapping] Map online form fields to new PDF for Section 4: Pension Info

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#70388]
## Issue Description
This is in Step 3 of online form: https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/p/6571319D-6329-4249-B0A7-E39DA9DA31F4/canvas

New online form fields list: https://docs.google.com/document/d/1eyL42-PtY6xxWc1-luTwekSNnK6InI_Rs6aN1I7SDVk/edit?usp=sharing

New PDF form we're mapping to: https://www.vba.va.gov/pubs/forms/VBA-21P-527EZ-ARE.pdf
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODMrQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--94e78357a07a021be7aaeaec5ab0aa8507478e8e/Screenshot%202023-11-22%20at%201.07.40%20PM.png)

**NOTE: Add the list of PDFtk keys relevant to this section**

**Front-end tickets:**
-  #69746 [MVP] Step 3: Create new page and questions for Enter Social Security Disability details
-  #69748 [MVP] Step 3: Create new page and questions for Claimant not determined disabled
-  #69755 [MVP] Step 3: Create 2 new pages and questions for Federal medical center status
-  #69942 [MVP] Step 3: Match all questions and copy to designs for VA medical center pages
-  #69750 [MVP] Step 3: Create new page and questions for Enter nursing home status
-  #70097 [MVP] Step 3: Match question wording and copy for Are you currently employed?
-  #69758 [MVP] Step 3: Add new fields for Current employment
-  #69871 [MVP] Step 3: Create new page and fields for Previous employment
-  #69752 [MVP] Step 3: Create new page, question and validation for Enter special monthly pension status
-  #69757 [MVP] Step 3: Match question wording and copy for Are you 65 years old or older?
-  #69751 [MVP] Step 3: Create 2 new pages and questions for Claimant lives in nursing home
---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/70388?planning-poker) with Zenhub @mjknight50 @danlim715 @wayne-weibel @TaiWilkin
