### ISSUE TITLE
[BE] 10-10EZR: Financial Info not showing up in VES

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#70381]
Repro steps:
1. User is enrolled and below 50% (test user 11 here)
2. User submits new annual income and expenditures for themselves and dependents in online 10-10EZR
3. Check with Josh F to see if info submitted is reflected in VES
3. Expected: Info is updated in VES
**4. Current: Financial Information is not changed in VES**

AC:
- [x] Determine cause of issue
- [x] Come up with fix for issue
- [ ] Test fix with QA and Josh F.
- [ ] Deploy to Prod

**Comment by lihanli** [comment]
@longmd what's a required field in the financial info section?

**Comment by longmd** [comment]
@lihanli you can use `veteranGrossIncome`.
