### ISSUE TITLE
[PDF Mapping] Map online form fields to new PDF for Section 3: Service Info

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#70387]
## Issue Description
This is Step 2 of online form: https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/p/6571319D-6329-4249-B0A7-E39DA9DA31F4/canvas

New online form fields list: https://docs.google.com/document/d/1eyL42-PtY6xxWc1-luTwekSNnK6InI_Rs6aN1I7SDVk/edit?usp=sharing

New PDF form we're mapping to: https://www.vba.va.gov/pubs/forms/VBA-21P-527EZ-ARE.pdf
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGYrQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bd91233d1f35750a885da3dbbad667756372cde4/Screenshot%202023-11-22%20at%201.03.16%20PM.png)

**NOTE: Add the list of PDFtk keys relevant to this section**

**Front-end tickets:**
-- #70331 [MVP] Step 2 Military Info: Match exiting questions to new design wording and copy
-- #68564 [MVP] Step 2 Military Info: Add new question, Military service Number
-- #70331 [MVP] Step 2 Military Info: Match exiting questions to new design wording and copy 
-- #68561 [MVP] Step 2 Military Info: Remove questions

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/70387?planning-poker) with Zenhub @mjknight50 @danlim715 @wayne-weibel @TaiWilkin
