### ISSUE TITLE
[MVP] Step 5 Financial info, net worth: Create new page and question for Estimate total value of your assets

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#70408]
## Note
Part of the larger effort to update the existing 527EZ form to add missing fields/info and remove depreciated fields.

## Description
On Step 5 of Financial Information: net worth,

- create a new page for the `Estimate the total value of your assets` question
- Include blue info box with expandable copy
- match all copy to designs

## Designs
- Main page example: https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/FF88CCC4-AA2D-4A1F-9CA9-58BA7AED24CB
- Blue info copy example: https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/9634AEA9-F65B-4466-B480-8FA736A31F1D
- Prototype: https://sketch.com/s/94592459-f741-45a0-9432-efd685b9a1d5/a/0AdzDLA/play
- Wireflows: https://www.sketch.com/s/94592459-f741-45a0-9432-efd685b9a1d5/a/JArmY2e

## Acceptance Criteria

**New page:**
Create 1 new page under: `Income and assets`

`We need to know if you and your dependents have over $25,000 in assets.`

In this page, add the following dollar/number field:

`Estimate the total value of your assets`

The blue box copy will be:
What are assets?

When expanded, the blue box copy will be:
`Assets are all the money and property you or your dependents own.
`
`Don't include the value of your primary residence or personal belongings such as appliances and vehicles you or your dependents need for transportation.`

**Validation info:**

The next page/question will be Did you, your spouse or your dependents transfer any assets in the last 3 calendar years?, as shown on #70410

**Additional validation info not shown on the Sketch file, [based on this Slack thread](https://dsva.slack.com/archives/C05MS96P6P2/p1702408922279719):**

_If they enter a number greater than $25,000_ - show them a similar alert that says:

`You answered that you have more than $25,000 in assets.`
`You'll need to submit an Income and Asset Statement in Support of Claim for Pension or Parents' Dependency and Indemnity Compensation (VA Form 21P-0969)`
`We'll ask you to upload this form online later. Or you can mail it to us.`
`Get VA Form 21P-0969 to download`

In addition, the next page/question should be: Did you, your spouse or your dependents transfer any assets in the last 3 calendar years?, as shown on #70410

**Match copy:**
Ensure all copy, including headers, questions and buttons match the designs.

## Tasks
[Software Development Tasks](https://docs.google.com/document/d/1vtn5co_YzGl1cFRNrIBAdjf53dmfH4_EXBWK8C5mU9Y/edit?usp=sharing)

- [ ] Front-end work

## Review
- [ ] Content review in staging

## Artifacts
- [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/527EZ-reactivation-initiative-brief.md)
- [User flow in Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683826730324/61b509f935adaa2acf2f7769a5ba911726a7b237?sender=u9d01ee38af217e4877e75660)
- [Prototypes in Sketch](https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/p/6571319D-6329-4249-B0A7-E39DA9DA31F4/canvas)
- [Spreadsheet of deleted form fields](https://docs.google.com/spreadsheets/d/1PTXxO6mFH2ZUK6XxX7iCCQb-NoSvhB5P/edit?usp=sharing&ouid=104362113771391164792&rtpof=true&sd=true)
- [Content source of truth/PDF form](https://www.vba.va.gov/pubs/forms/VBA-21P-527EZ-ARE.pdf)
- [Link to testing accounts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/form-deactivation/527EZ-staging-test-accounts-accessible.md)
- [Link to staging](https://staging.va.gov/)

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/70408?planning-poker) with Zenhub @mjknight50 @TaiWilkin @ToddWebDev @zack

**Comment by mayacoforma** [comment]
@vbellissimo Reviewed and refined this task.

**Comment by mayacoforma** [comment]
Reviewed and refined.

**Comment by vbellissimo** [comment]
Added additional validation info to the body of this ticket, [based on this Slack thread](https://dsva.slack.com/archives/C05MS96P6P2/p1702408922279719):
