### ISSUE TITLE
Adding Devi Hill to DSVA Slack

### ISSUE THREAD

**Issue by HeatherRienks** [department-of-veterans-affairs/va.gov-team#70406]
Please add Devi Hill new Agile Six Delivery Manager on CHAMPVA team to DSVA Slack as a Full Member.

devi.hill@agile6.com

She should be added to #vfs-all-teams, #vfs-change-announcements and any other pertinent VFS general channels for new team members.

Thank you!

**Comment by HeatherRienks** [comment]
@pshahVA -FYI

**Comment by pshahVA** [comment]
approved.

**Comment by HeatherRienks** [comment]
Closing ticket as this has been completed!
