### ISSUE TITLE
[MVP] Step 5 Financial info, net worth: Create new page and question for Over 25k in assets

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#70403]
## Note
Part of the larger effort to update the existing 527EZ form to add missing fields/info and remove depreciated fields.

## Description
On Step 5 of Financial Information: net worth,

- create a new page for the `Do you and your dependents have over $25,000 in assets?` question
- Include blue info box with expandable copy
- Include gray warning copy if they answer "yes"
- match all copy to designs

## Designs
- Main page example: https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/g1JzlGM
- Blue info copy example: https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/9634AEA9-F65B-4466-B480-8FA736A31F1D
- Gray warning box example: https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/842E89CD-56B0-44B7-B0C4-48A64C036456
- Prototype: https://sketch.com/s/94592459-f741-45a0-9432-efd685b9a1d5/a/0AdzDLA/play
- Wireflows: https://www.sketch.com/s/94592459-f741-45a0-9432-efd685b9a1d5/a/JArmY2e
## Acceptance Criteria

**New page:**
Create 1 new page under: `Income and assets`

`We need to know if you and your dependents have over $25,000 in assets.`

In this page, add the following radio button question:

`Do you and your dependents have over $25,000 in assets?`
`Yes`
`No`

The blue box copy will be:
What are assets?

When expanded, the blue box copy will be:
`Assets are all the money and property you or your dependents own.
`
`Don't include the value of your primary residence or personal belongings such as appliances and vehicles you or your dependents need for transportation.`

**Validation info:**

If they answer "Yes", they will see the gray box warning copy as shown on the designs:
`You'll need to submit an Income and Asset Statement in Support of Claim for Pension or Parents' Dependency and Indemnity Compensation (VA Form 21P-0969)`

`Get VA from 21P-0969 to download`

Link to 21P-0969; will open as a new tab: https://www.vba.va.gov/pubs/forms/VBA-21P-0969-ARE.pdf

If they answer "yes", the next page/question will be Did you, your spouse or your dependents transfer any assets in the last 3 calendar years? as shown on #70410

If they answer "no", the next page/question will be Estimate the total value of your assets as shown on #70408

**Match copy:**
Ensure all copy, including headers, questions and buttons match the designs.

## Tasks
[Software Development Tasks](https://docs.google.com/document/d/1vtn5co_YzGl1cFRNrIBAdjf53dmfH4_EXBWK8C5mU9Y/edit?usp=sharing)

- [ ] Front-end work

## Review
- [ ] Someone on the Pension team will review/QA

## Artifacts
- [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/527EZ-reactivation-initiative-brief.md)
- [User flow in Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683826730324/61b509f935adaa2acf2f7769a5ba911726a7b237?sender=u9d01ee38af217e4877e75660)
- [Prototypes in Sketch](https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/p/6571319D-6329-4249-B0A7-E39DA9DA31F4/canvas)
- [Spreadsheet of deleted form fields](https://docs.google.com/spreadsheets/d/1PTXxO6mFH2ZUK6XxX7iCCQb-NoSvhB5P/edit?usp=sharing&ouid=104362113771391164792&rtpof=true&sd=true)
- [Content source of truth/PDF form](https://www.vba.va.gov/pubs/forms/VBA-21P-527EZ-ARE.pdf)
- [Link to testing accounts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/form-deactivation/527EZ-staging-test-accounts-accessible.md)
- [Link to staging](https://staging.va.gov/)

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/70403?planning-poker) with Zenhub @mjknight50 @TaiWilkin @ToddWebDev @zack

**Comment by mayacoforma** [comment]
@vbellissimo Reviewed and refined this task.

**Comment by mayacoforma** [comment]
Reviewed and refined.
