### ISSUE TITLE
[UX/FE/BE/QA] 10-10EZR: Do NOT let user submit second CY EZR

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#70411]
As a Veteran, I would like to know if I cannot submit another MT online because it won't be reviewed so that I can look at a hardship exemption or contact someone to help me.

- [ ] UX: Come up with design and verbiage to notify user that they have already submitted a means test, link them to hardship (I might just link to the [Hardship page](https://www.va.gov/health-care/pay-copay-bill/financial-hardship/) and not bother talking about all the different hardship forms) and give them the hotline #
- [ ] UX: Check verbiage and design with Kristen and Aliyah
- [ ] BE: come up with a way to signal that a user has already submitted an EZR with financial info for that calendar year ([Josh Drumm did some work on this ticket #69489](https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/69489))
- [ ] BE: If they've already submitted an MT for this year, notify FE
- [ ] FE if they've already submitted a means test, display error message
- [ ] QA: Test to make sure this error appears with a user who has already submitted a means test
- [ ] Deploy to Prod
- [ ] **Success: User cannot submit financial information for more than the first time with the online EZR**

**Comment by longmd** [comment]
@alexseelig , is this needed any longer?
