### ISSUE TITLE
[MVP] Step 5 Financial info, net worth: Create new page and question for Did you transfer any assets?

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#70410]
## Note
Part of the larger effort to update the existing 527EZ form to add missing fields/info and remove depreciated fields.

## Description
On Step 5 of Financial Information: net worth,

- create a new page for the `Did you, your spouse, or your dependents transfer any assets in the last 3 calendar years?` question
- Include blue info box with expandable copy
- Add copy to provide examples of money transfers
- Add gray warning box if they answer "No"
- match all copy to designs

## Designs
- Main page example: https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/A19CC325-9959-42A7-B723-E7ACEDA130B5
- Blue info copy example: https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/9634AEA9-F65B-4466-B480-8FA736A31F1D
- Gray warning box example: https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/6EF173E6-455D-48DE-B676-56BABBAE310C
- Prototype: https://sketch.com/s/94592459-f741-45a0-9432-efd685b9a1d5/a/0AdzDLA/play
- Wireflows: https://www.sketch.com/s/94592459-f741-45a0-9432-efd685b9a1d5/a/JArmY2e

## Acceptance Criteria

**New page:**
Create 1 new page under: `Income and assets`

In this page, add the following radio button question:

`Did you, your spouse or your dependents transfer any assets in the last 3 calendar years?`
`Yes`
`No`

Add copy to provide examples of transferring assets: - **SEE COMMENT IN SKETCH FOR THIS; PLEASE REACH OUT TO KATHERINE FUNG/MAYA FOR INFO ON PLACEMENT**

`You transferred assets if you made any of these transactions: `
`- You gave away money or property`
`- You sold a home that isn’t your primary residence `
`- You purchased an annuity`
`- You put money or property into a trust`

The blue box copy will be:
What are assets?

When expanded, the blue box copy will be:
`Assets are all the money and property you or your dependents own.`

`Don't include the value of your primary residence or personal belongings such as appliances and vehicles you or your dependents need for transportation.`

**Validation info:**

If they answer "Yes", they will see the gray box warning copy as shown on the designs:
`You'll need to submit an Income and Asset Statement in Support of Claim for Pension or Parents' Dependency and Indemnity Compensation (VA Form 21P-0969)`

`Get VA from 21P-0969 to download`

Link to 21P-0969; will open as a new tab: https://www.vba.va.gov/pubs/forms/VBA-21P-0969-ARE.pdf

The next page/question will be Did you, your spouse or your dependents own your home (also known as your primary residence)?, as shown on #70413

**Match copy:**
Ensure all copy, including headers, questions and buttons match the designs.

## Tasks
[Software Development Tasks](https://docs.google.com/document/d/1vtn5co_YzGl1cFRNrIBAdjf53dmfH4_EXBWK8C5mU9Y/edit?usp=sharing)

- [ ] Front-end work

## Review
- [ ] Content review in staging

## Artifacts
- [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/527EZ-reactivation-initiative-brief.md)
- [User flow in Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683826730324/61b509f935adaa2acf2f7769a5ba911726a7b237?sender=u9d01ee38af217e4877e75660)
- [Prototypes in Sketch](https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/p/6571319D-6329-4249-B0A7-E39DA9DA31F4/canvas)
- [Spreadsheet of deleted form fields](https://docs.google.com/spreadsheets/d/1PTXxO6mFH2ZUK6XxX7iCCQb-NoSvhB5P/edit?usp=sharing&ouid=104362113771391164792&rtpof=true&sd=true)
- [Content source of truth/PDF form](https://www.vba.va.gov/pubs/forms/VBA-21P-527EZ-ARE.pdf)
- [Link to testing accounts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/form-deactivation/527EZ-staging-test-accounts-accessible.md)
- [Link to staging](https://staging.va.gov/)

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/70410?planning-poker) with Zenhub @mjknight50 @TaiWilkin @ToddWebDev @zack

**Comment by aplatt-coforma** [comment]
@katherine-fung @mayacoforma - I'm a bit uncertain on the content verification for this change. Here's a screenshot of the change on Staging. Can you confirm this is correct?
<img width="604" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDkxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2507e288f8e9388282d4031718f3e56683d26f59/Screenshot%202023-12-19%20at%203.12.15%E2%80%AFPM.png" alt="Screenshot 2023-12-19 at 3.12.15 PM.png" />
