### ISSUE TITLE
SOCKS access request for Maruf Ahmed.

### ISSUE THREAD

**Issue by marufahmedva** [department-of-veterans-affairs/va.gov-team#70415]
### Your Name

Maruf Ahmed

### Your Email

maruf.ahmed@va.gov

### Your Role and Team

Test Engineer, MHV va.gov Medical Record Team

### Product Manager (PM) name and email

Bryan Riley, bryan.riley@va.gov

### Product Owner (PO) name and email

Bresha Lipscomb, Bresha.Lipscomb@va.gov

### Access Type Requesting

developers

### Public SSH Key
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCissgFfSEhS20RPubwpo9V1FeS9LXz9Lecj+eV0zF9sRlP3yPtmOs2rNqJWEkQ4aoHAtbEK+GCqhjNN1x2Mte387tAeCEheVxtKhxIaWLfsJFrfRP40KoDJY6SUM72mtEXYI3NGaXTcsyjBDDJ9dQ6LPx16BavY2/9AQmOTqS9+9JrMP41SSGw0zky/mjiR7cUFySsRKhrmFdpSmotDZKR/ohheJf7uzy7iW3VGR8mpqQ748BjtgMnTx1rKuCDWzPQcx/vLOfifglbwrOqoWHi1e3qmxAuMRjdWCsEfoZoihS+f34ujmgaRUAhG6FvkUVc+uYIqS8I3+PBKYToZtn/6l3MKg/qS2kqlSDyyC7pBkm9LJ4Hd1xvr3S4oqet3qO3C8IBOFIlIJcjqrq7gEJ6jx539Jh0orJPELKQoyFSggGY2Ukolq4JtXHAH41ae/NYewu6IDUw9uAmT7rebDWm9mNSPWRtBEgT9SPaoDaP21TWBdqebUW3YZkRKoDehuBaLAIzTH5WsGd8oMaBbpZZ7IJE2pcv+xuiTXmCB5LB342aLUJYMYG+T0TKUG7+Vl+54yed7aNdJOl12iCmZ5RRb7XKJX+lfxQQP1TmMW7aJ8DkUrj6eQoaUOGi3dYuX2ZsaROGgDWXGTNBH5wW3ciJmSukY56ZHPNTUtI7ry1HYQ== VHAMASTER+vhaiswahmedm@VACOLTAHMEDM3

### E-QIP Transmittal Confirmation

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/149001014/bd92fd97-b086-4d64-8c95-a1911aedc3a4)

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by jknipes** [comment]
e-QIP screenshot added

**Comment by marufahmedva** [comment]
Hello, Any update ?

**Comment by Efe-Oddball** [comment]
@marufahmedva  Access granted ✅

Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Reach out in #vfs-platform-support if you have any trouble.
