### ISSUE TITLE
[MVP] Step 5 Financial info, net worth: Create new page and question for What's the value of the land more than 2 acres?

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#70425]
## Note
Part of the larger effort to update the existing 527EZ form to add missing fields/info and remove depreciated fields.

## Description
On Step 5 of Financial Information: net worth,

- create a new page for the `What's the value of the land that's more than 2 acres?` question
- Include hint text
- match all copy to designs

## Designs
- Main page example: https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/D160C17B-50FA-40FB-B5B1-8F7DB2512420
- Prototype: https://sketch.com/s/94592459-f741-45a0-9432-efd685b9a1d5/a/0AdzDLA/play
- Wireflows: https://www.sketch.com/s/94592459-f741-45a0-9432-efd685b9a1d5/a/JArmY2e

## Acceptance Criteria

**New page:**
Create 1 new page under: `Income and assets`

In this page, add the following dollar/number question/field:
`What's the value of the land that's more than 2 acres?`

Add hint text below:
Don't include the value of the residence or the first 2 acres.

**Validation info:**

The next page/question will be: Is the additional land marketable?, as shown on #70428

**Match copy:**
Ensure all copy, including headers, questions and buttons match the designs.

## Tasks
[Software Development Tasks](https://docs.google.com/document/d/1vtn5co_YzGl1cFRNrIBAdjf53dmfH4_EXBWK8C5mU9Y/edit?usp=sharing)

- [x] Front-end work

## Review
- [ ] Content review in staging

## Artifacts
- [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/527EZ-reactivation-initiative-brief.md)
- [User flow in Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683826730324/61b509f935adaa2acf2f7769a5ba911726a7b237?sender=u9d01ee38af217e4877e75660)
- [Prototypes in Sketch](https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/p/6571319D-6329-4249-B0A7-E39DA9DA31F4/canvas)
- [Spreadsheet of deleted form fields](https://docs.google.com/spreadsheets/d/1PTXxO6mFH2ZUK6XxX7iCCQb-NoSvhB5P/edit?usp=sharing&ouid=104362113771391164792&rtpof=true&sd=true)
- [Content source of truth/PDF form](https://www.vba.va.gov/pubs/forms/VBA-21P-527EZ-ARE.pdf)
- [Link to testing accounts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/form-deactivation/527EZ-staging-test-accounts-accessible.md)
- [Link to staging](https://staging.va.gov/)

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/70425?planning-poker) with Zenhub @mjknight50 @TaiWilkin @ToddWebDev @zack

**Comment by mayacoforma** [comment]
@vbellissimo Reviewed and refined this task.

**Comment by aplatt-coforma** [comment]
Content looks good. 
<img width="879" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUoxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3151a594b79b924acec9397da671c474bb986454/Screenshot%202023-12-19%20at%203.19.29%E2%80%AFPM.png" alt="Screenshot 2023-12-19 at 3.19.29 PM.png" />

**Comment by aplatt-coforma** [comment]
The page show after is the "Do you, your spouse, or your dependents receive income?" instead of the expected "Is the additional land marketable?". That ticket is still in code review so probably the reason why. Will add to the issues list to verify later.
