### ISSUE TITLE
[UX] 10-10EZR: Scenarios, Designs, and messaging for no two MTs in one CY

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#70439]
As a user, I would like to be notified when I cannot submit another Means Test (financial info) online so that I don't enter information that is never looked at and so that I am aware of other resources such as hardship exemptions. 

- [x] Come up with all scenarios in which a user cannot submit another MT
- [x] Come up with design and verbiage to notify user that they have already submitted a means test, link them to hardship (I might just link to the [Hardship page](https://www.va.gov/health-care/pay-copay-bill/financial-hardship/) and not bother talking about all the different hardship forms) and give them the hotline #
- [x] Check verbiage and design with Kristen and Aliyah
- [x] Review any technical constraints with Devs
- [x] **Success: We have designs and verbiage alerting users that they cannot submit their financial info again online**

**Comment by jessicastump** [comment]
Some possible scenarios:

**Comment by jessicastump** [comment]
Will review early next week at Monday Design sync and then async review with Aliyah so this can go on to FE/QA.

**Comment by jessicastump** [comment]
[An update](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/a/kKGbqAR) after this week's meetings, still pending content & final reviews.

**Comment by jessicastump** [comment]
Posting here where we landed/the latest as of Monday 12/4 mid-day.
1. The alert design and content (has been reviewed by @aliyahblackmore but we are waiting to here confirmation on the sentence "You can only share your household financial information once each year. "
2. BE working on final testing for API piece

Alert for Intro Page:
<img width="625" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFF1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--74a9d99c3efc6b22d0f4efd88415159513327748/MTx2-IntroPageAlert.png" alt="MTx2-IntroPageAlert.png" />

Alert at start of household section (the rest of this section is skipped) 
<img width="625" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFl1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2cd5be8fabd62256f6fd51c51d97081772f0e831/MTx2-HouseholdSectionAlert.png" alt="MTx2-HouseholdSectionAlert.png" />

cc @longmd

**Comment by aliyahblackmore** [comment]
@jessicastump I just made updates to the alert content based on the reply from our copy editor. 

I used italics to show what I changed! [Link to sketch screen](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/a/kKGbqAR)

**Comment by jessicastump** [comment]
[Sketch link](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/v/3zPnqj/a/kKGbqAR) updated and images below:


![Group 10](https://github.com/department-of-veterans-affairs/va.gov-team/assets/98367393/c77d24ea-662d-4ea2-b770-6fb310094be7)

---

![Group 6](https://github.com/department-of-veterans-affairs/va.gov-team/assets/98367393/e37f8efa-d8da-4220-a3f8-dc6b627a80e1)

@longmd Closing this ticket and content/design half is ready for development. 

@alexseelig Side note that is not a task in this ticket: The source of truth docs (Mural errors, Mural wireflow, content doc, Sketch file) will all need to be updated too.

**Comment by jessicastump** [comment]
Did not mean to close with that last comment --- but moving to Validate instead of in progress.

Links to Sketch source of truth docs below:
1. Intro page with alert - [desktop](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/a/3oJeQ0z)
2. Start of household section with alert - [desktop](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/a/oMVr2G3)

**Comment by jessicastump** [comment]
Updated source of truth docs, so NOW I will close the ticket with this comment :) 
1. Sketch file - [Introduction page](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/p/34F1F294-5E1D-46C1-ADE6-AC6C398E2130/canvas) and [Household Financial Information section](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/p/3B1847D9-15A8-4526-A264-F00F656EDAC6/canvas)
2. [Mural user flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1694028488812/91947e4f4f9f8536af5a6609e54fced964d3505f?sender=uadf1ed7fe7c76f0914967329)
3. [Mural error messaging audit](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1694028526633/a5d8eba28e3acaba46de92e99fb8013fd1a56d3d?sender=uadf1ed7fe7c76f0914967329)
4. [Github Error Matrix](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/10-10EZR%20Form/10-10EZR-ErrorMatrix.md)
