### ISSUE TITLE
Review VSR shadowing videos - Will

### ISSUE THREAD

**Issue by RenataKeck** [department-of-veterans-affairs/va.gov-team#70437]
Assigned videos are roughly 1 hour each, 2 hours total for this ticket. If you so choose, I have suggested optional videos from each study that provide a contrasting use case from the video you were assigned to watch. 

All recordings are in Sharepoint and will require favorable adjudication. The links below will take you to a Google Doc with links to the video recordings, research plan and final reports.

[VSR Shadowing 1](https://docs.google.com/document/d/1On6dxbygCR0-tQWyUF0sF8v6A3TrHGbxVnfaUM40-iU/edit#heading=h.1clw4b5ayx74)

- [x] V3
- [x] Optional: CA1
- [x] Add any questions or observations from videos that may inform next steps into the [Open Questions](https://docs.google.com/document/d/14kgbh_CclsTsbg81lM1W2IBKi_ooNW76o7AW-NaGlh4/edit?usp=sharing) doc

[VSR Shadowing 2](https://docs.google.com/document/d/1On6dxbygCR0-tQWyUF0sF8v6A3TrHGbxVnfaUM40-iU/edit#heading=h.9p0vbpqeyef0)

- [x] VSR8
- [x] Optional: VSR12
- [x] Add any questions or observations from videos that may inform next steps into the [Open Questions](https://docs.google.com/document/d/14kgbh_CclsTsbg81lM1W2IBKi_ooNW76o7AW-NaGlh4/edit?usp=sharing) doc

**Comment by williamphelps13** [comment]
All interesting and insightful interviews of VSRs working in the VBMS. Continuing to watch these interviews would help to let the content and the software become more and more familiar and second nature.
