### ISSUE TITLE
[Incomplete] Review VSR shadowing videos - Kara/Design

### ISSUE THREAD

**Issue by RenataKeck** [department-of-veterans-affairs/va.gov-team#70435]
All recordings roughly 1 hour long and are stored in Sharepoint, and will require favorable adjudication. The links below will take you to a Google Doc with links to the video records, research plan and final reports. 

**If you do not have Sharepoint access yet**: review the Mural with data analysis as well as the findings report from each study, and add questions to the Open Q's doc.

[VSR Shadowing 1](https://docs.google.com/document/d/1On6dxbygCR0-tQWyUF0sF8v6A3TrHGbxVnfaUM40-iU/edit#heading=h.1clw4b5ayx74)

- [ ] Claims Assistant
- [ ] V1
- [ ] Add observations, questions, and takeaways to the team [Shadowing doc](https://docs.google.com/document/d/1XyLBlt61vqzzi1xo89D1RCTX2Uu3HVn4SksPybqeQqM/edit)

[VSR Shadowing 2](https://docs.google.com/document/d/1On6dxbygCR0-tQWyUF0sF8v6A3TrHGbxVnfaUM40-iU/edit#heading=h.9p0vbpqeyef0)

- [ ] VSR-11
- [ ] VSR-12 (just first 20-30min)
- [ ] Optional: VSR-7 (I found the contrast between VSR-7, 11 and 12 to provide a nice rounded view of different use cases, however, no need to watch all of them entirely!)
- [ ] Add observations, questions, and takeaways to the team [Shadowing doc](https://docs.google.com/document/d/1XyLBlt61vqzzi1xo89D1RCTX2Uu3HVn4SksPybqeQqM/edit)

**Comment by hdbaines** [comment]
Currently Blocked - Kara needs SharePoint Access

**Comment by karafaithsanchez** [comment]
Status: This task was not completed before the project ended. For the next team that picks this up - you can view the videos in the links above.
