### ISSUE TITLE
Review VSR shadowing videos - Gabe

### ISSUE THREAD

**Issue by RenataKeck** [department-of-veterans-affairs/va.gov-team#70436]
Assigned videos are roughly 1 hour each, 2 hours total for this ticket. If you so choose, I have suggested optional videos from each study that provide a contrasting use case from the video you were assigned to watch. 

Note that all recordings are in Sharepoint and will require favorable adjudication. The links below will take you to a Google Doc with links to the video recordings, research plan and final reports. 

[VSR Shadowing 1](https://docs.google.com/document/d/1On6dxbygCR0-tQWyUF0sF8v6A3TrHGbxVnfaUM40-iU/edit#heading=h.1clw4b5ayx74)

- [x] V1
- [ ] Optional: CA1
- [ ] Add any questions or observations from videos that may inform next steps into the [Open Questions](https://docs.google.com/document/d/14kgbh_CclsTsbg81lM1W2IBKi_ooNW76o7AW-NaGlh4/edit?usp=sharing) doc

[VSR Shadowing 2](https://docs.google.com/document/d/1On6dxbygCR0-tQWyUF0sF8v6A3TrHGbxVnfaUM40-iU/edit#heading=h.9p0vbpqeyef0)

- [x] VSR-7
- [ ] Optional: VSR-12 (RK: VSR-12 and VSR-7 have wildly different styles when accessing additional tools or systems to go through claims. I think at least watching the start of VSR-12 to get a sense for the diversity of use cases is worthwhile)
- [x] Add any questions or observations from videos that may inform next steps into the [Open Questions](https://docs.google.com/document/d/14kgbh_CclsTsbg81lM1W2IBKi_ooNW76o7AW-NaGlh4/edit?usp=sharing) doc

**Comment by hdbaines** [comment]
Blocked until Gabe Gets access
