### ISSUE TITLE
Vets-api terminal access for Annie Tran

### ISSUE THREAD

**Issue by anniebtran** [department-of-veterans-affairs/va.gov-team#70449]
### Your Name

Annie Tran

### Your GitHub handle (terminal access is managed through GitHub)

@anniebtran

### Team, Role, and Company of the target individual

Benefits Decision Reviews, Senior Software Engineer, Coforma

### Product Manager (PM) name and email

Sade Ragsdale, sade@coforma.io

### Product Owner (PO) name and email

Zach Goldfine, zachary.goldfine@va.gov

### COR Name (leave "None" if you listed an AWS user name above)

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

Other - please specify in 'Additional Notes'

### Please confirm if you are on the VFS Team Roster or Platform Team Roster

- [X] [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Please confirm E-QIP Transmittal/Adjudication. This could be a screenshot of your Transmittal/Adjudication email, a link to another request where you've submitted this proof (i.e. AWS/SOCKS), etc.

- [X] I have attached proof that I have either transmitted my E-QIP survey or previously received a favorable decision (by including in "Additional Notes" section below)

### ArgoCD terminal access requested for the following environments

- [ ] dev
- [X] staging
- [ ] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### Additional Notes

I would like access to production to investigate/triage error alerts and other issues with benefit appeals forms as we currently only have one backend engineer on the decision reviews team (@data-doge) who has access to production. Also would like to have access to staging for testing purposes as well.

COR: Keith Riley
VOR: Jeff Langworthy

EQIP Transmittal:
<img width="1084" alt="Screenshot 2023-11-09 at 3 05 03 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/14334046/f5b6a7e0-4880-49df-85be-4d7a6f4430c2">

### Additional resources for Support Engineer

- [ ] For users on a VFS team but not in the VFS Team Roster, they must start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] Instructions for handling requests [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access) - Support Only

**Comment by bdech** [comment]
Verified in VFS Team Roster

**Comment by bdech** [comment]
@anniebtran You’ve been granted access to the `staging` environments.

Access to `Production` is pending OCTODE approval.

Here's some additional documentation for [Vets API on EKS](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-TerminalAccess) that may help.

**Comment by JonathanKamensDVA** [comment]
Approved.

**Comment by bdech** [comment]
@anniebtran You've been granted access to `Production` with access limited to 6 months, expiring 05/29/24. Please return to this request one week prior to expiration to request an extension.

**Comment by bdech** [comment]
support slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1701270575716259)

**Comment by lindsay-insco** [comment]
@anniebtran Your Vets API Terminal Production access has expired.

Would you like to request an extension? You have 72 hours to respond, or your
access will be revoked and you will need to fill out a new request

**Comment by anniebtran** [comment]
@lindsay-insco Yes, I would like an extension please! Thank you!

**Comment by lindsay-insco** [comment]
@anniebtran Your Production access has been extended until 03/12/25. Please set a reminder for yourself to return to this Issue and re-request access within 1 week of the expiration date. You'll receive 1 reminder with a 72 hour window to respond. Failure to do so will result in lost access and will require you to fill out a new request.

**Comment by lindsay-insco** [comment]
Slack reminder [here](https://dsva.slack.com/archives/C06CY71PCAX/p1726151970576209)
