### ISSUE TITLE
[FE/QA] 10-10EZR: Disabled household section for users with financial data on file

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#70452]
As a user, I would like to be notified when I cannot submit another Means Test (financial info) online so that I don't enter information that is never looked at and so that I am aware of other resources such as hardship exemptions.

- [x] Utilize financial info value from the enrollment status API response to hide household pages when the value is set to `false`
- [x] Utilize financial info value from the enrollment status API response to show financial info & hardship alert when the value is `false`
- [x] Utilize financial info value from the enrollment status API response to show alert page at the start of the household section when the value is `false`
- [x] Write test cases to make sure second MT user cannot access or submit financial info
- [x] Write test cases for the alerts
- [x] **Success: We prevent a user who has already has a means test on file for the previous year from entering financial info, we tell them why and give them other resources to pursue**

## Related Issue(s)
- UX Story -- [70439](https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/70439)
- BE story -- [70440](https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/70440)

**Comment by jessicastump** [comment]
Here is the [link to the UX ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/70439) piece of this

**Comment by jessicastump** [comment]
Sorry @longmd ! There was an error in the Sketch file I just found when checking this out in staging. I didn't update the last content change from Aliyah correctly. There shouldn't be "only" twice in the last sentence of the first paragraph. . It should be:
_You can share your household financial information only once each year._

**Comment by longmd** [comment]
@jessicastump , this has been taken care of with the submit transformer bugfix PR.
