### ISSUE TITLE
Comparative Analysis

### ISSUE THREAD

**Issue by RenataKeck** [department-of-veterans-affairs/va.gov-team#70463]
**Problem**
We need to understand what tools representatives currently use to support the PoA process and claims management for Veterans. A larger goal of our work is to reduce the number of disparate tools that representatives need to use to complete critical tasks. Understanding these touchpoints will inform the maturity of the MVP pre-launch as well as post-launch work.

**Output**
- A spreadsheet of systems used alongside SEP (how and why they're used), as well as tools VSOs use instead of SEP. Documentation should identify essential tasks the SEP replacement will need, along with essential connections to other systems. 
- Updated current state map that identifies where in the process specific tools are used (VSOfficer-specific). 

**Resources**
- Some existing competitive analysis has been added to the [existing research Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1695929155059/a302158eccec694ec7089bd6a02954421721987d?wid=0-1691767758950)

Based on open questions from Sprint 4 as well as discussions with folks, some directions to explore include:
- [x] Check repository/with VA design leads if VEO did an analysis (or VBA partners)
- [x] Systems used at [benefits intake](https://github.com/department-of-veterans-affairs/lighthouse-ux/blob/master/Benefits%20and%20Appeals%20Research/2020-01-Benefits-Intake-API-Discovery-Readout/2020-01-Benefits-Intake-API-Discovery-Research-Readout-Report.pdf) 
- [x] Review [VetPro](https://vetpro.us/our-software/) and [TylerTech](https://www.tylertech.com/solutions/health-human-services/disability-benefits/veterans-benefits), there may be walkthroughs those systems on YouTube or on their websites. There is also an interview with [Tyler Tech](https://github.com/department-of-veterans-affairs/vets-contrib/blob/master/teams/benefits-team/Research/External/2019%20Benefits%20Intake/benefitsintakeVetraSpec.md) and [VetPro](https://github.com/department-of-veterans-affairs/vets-contrib/blob/master/teams/benefits-team/Research/External/2019%20Benefits%20Intake/benefitsintakeVetPro.md) in Github.
- [x] How [eBenefits](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/research/discovery/research-findings.md) is used
- [x] Identify any other relevant or equivalent systems to look at that address the same needs (there is a diagram for how [future state of POA flow](https://lucid.app/lucidchart/cdc067c7-0300-4fb8-af4d-09d6facf6194/view?page=SPiqDHIZuCjf#) will work)
- [ ] Review [Quick Submit](https://dvagov.sharepoint.com/:f:/r/sites/vaabdvro/Shared%20Documents/Accredited%20Representative%20Facing?csf=1&web=1&e=KA2luS) (19:00 timestamp in this video; requires Sharepoint access) and Centralized Mail Portal
- [x] [POA tools and task flow](https://github.com/department-of-veterans-affairs/lighthouse-ux/tree/master/Benefits%20and%20Appeals%20Research/2021-04-Power-of-Attorney-Experience-with-VSOs)
- [x] [Digits-2-Digits](https://github.com/department-of-veterans-affairs/lighthouse-ux/blob/master/Benefits%20and%20Appeals%20Research/2022-05-Disability-Compensation-Claims-Discovery/2022-10-VSO-DisabilityCompClaims526EZ-Report.md)
- [x] Tools used by [law offices](https://github.com/department-of-veterans-affairs/vets-contrib/blob/ec60f4a26b21ea0b41801c4d12f3e5a5aea35b24/lighthouse/benefits-team/Upload/Research/Document_Submission_HHS-LAW_research_summary.md) (N.B. this research is old)

**Acceptance criteria**
- Spreadsheet that lists all the tools, who owns them (VS vs. third party), who uses them, and what people use them for (aka what step in the current state map).
- Updated current state map that includes all the tools and where they are used along the process

**Comment by RenataKeck** [comment]
This should be less of a formal competitive analysis than cataloging the various systems VSOs use either alongside SEP (and why), as well as what they use **instead** of SEP (and why).

**Comment by uxrebecca** [comment]
In a [research report related to POA](https://github.com/department-of-veterans-affairs/lighthouse-ux/tree/master/Benefits%20and%20Appeals%20Research/2021-04-Power-of-Attorney-Experience-with-VSOs), Caseflow and Share were mentioned as part of VA's system of records (in addition to VBMS), so we might want to learn what these are as well.

**Comment by uxrebecca** [comment]
Another tool, this one mentioned in the VSO accreditation journey, is Vetraspec. VSOrgs set up access to Vetraspec for VSOs as the last step once they are accredited. Might be an internal system to the orgs?

**Comment by uxrebecca** [comment]
And the journey for VetPro users attached here.<img width="866" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2Q1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--65f44f18f064ab061d37a16d1facedb170891bda/VetPro%20users%20claims%20journey.png" alt="VetPro users claims journey.png" />
