### ISSUE TITLE
Service blueprint format 

### ISSUE THREAD

**Issue by carafrissell1** [department-of-veterans-affairs/va.gov-team#70485]
## Description
Identify and select a template structure to base the service blueprint off of.
Options Micah and Cara corralled are [here](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1699982406540/e8113761121fe49fd2174854b37113e7e630c264?sender=ucbacbd1daef36939e8aa2288).  
Next: waiting to hear from VES team about their new playbook for service blueprint.

## Definition of Done
- [ ] Format/template selected

---
## How to configure this issue
- [ ] **Attached to an Epic**

**Comment by micahtaylor** [comment]
[Waiting on the VES team](https://dsva.slack.com/archives/C05UTPZRZFY/p1701281688745519)

**Comment by micahtaylor** [comment]
[VES template found here](https://www.figma.com/files/890005620661584027/project/172403768/VA-CX-Catalog-v1.0?fuid=930579565053635540)
We will be giving feedback to the VES team on template usage. We will likely keep our collaboration in Mural and may only use this Figma file for finished assets.
