### ISSUE TITLE
Document different screens in submission process 

### ISSUE THREAD

**Issue by carafrissell1** [department-of-veterans-affairs/va.gov-team#70481]
## Description
Go through and document as many screens related to the submission process for the 3 currently supported  digital (remote?) methods of submissions: Appointments, Checkin, online and organize them in one place so that they can be used in the service blueprint.  Ideally this will provide a foundation for the Veteran part of the Service blueprint.  

## Definition of Done
- [x] Document/Mural containing all the process screens 
- [x] Identify what if any parts of the Vet process we cannot access at the moment
- [x] Identify next steps 

---
## How to configure this issue
- [ ] **Attached to an Epic**

**Comment by micahtaylor** [comment]
[Current portal screens here](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1699982406540/e8113761121fe49fd2174854b37113e7e630c264?wid=0-1701179302588)

**Comment by carafrissell1** [comment]
Working Mural here: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1699982406540/e8113761121fe49fd2174854b37113e7e630c264?sender=ucbacbd1daef36939e8aa2288

**Comment by micahtaylor** [comment]
Next steps are to identify a thematic roadmap
