### ISSUE TITLE
[UX] [Analytics] Add widget in GA Dashboard to pull in button and link selects on Review Page

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#70484]
## Tasks

- [x] Add widget in GA Dashboard to pull in button and link selects on Review Page

## AC

- [x] Data is aggregating in GA Dashboard

**Comment by benbrasso-agile6** [comment]
Wait I think I fixed it lol

**Comment by loripusey** [comment]
@benbrasso-agile6 FYI, this is being released today 12/7

**Comment by benbrasso-agile6** [comment]
https://dsva.slack.com/archives/C022AC2STBM/p1702313486980419
