### ISSUE TITLE
[spike] DR | undefined method `key?' for "(...)":String error

### ISSUE THREAD

**Issue by anniebtran** [department-of-veterans-affairs/va.gov-team#70518]
## What happened?

We were notified in our [error alerts Slack channel](https://dsva.slack.com/archives/C05UPRR0HK3/p1700662243110059) of several errors that had this message:

```
undefined method `key?' for "(...)":String error
```

This occurred around the same time as a [timezone error](https://github.com/department-of-veterans-affairs/va.gov-team/issues/70429) but does not appear to be related as it's happening to veterans in timezones that were not affected by the updated timezone schema. As of 11/22, 35 veterans have been affected by this error.

## What do we need to know?
We aren't sure what the root cause of this error is because it didn't affect all Supplemental Claims submissions in production and we haven't been able to replicate it in the staging environment. According to the [Sentry trace](http://sentry.vfs.va.gov/organizations/vsp/issues/239839/events/051593c3d69d4496923b0e8af63f14e4/?environment=production&project=3&query=undefined+method+%60key%3F%27+for+%22%28...%29%22%3AString&statsPeriod=14d), it seems to be coming from the [`#validate` call from `JSONSchemer` ](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/decision_review_v1/service.rb#L423). 

**What we've tried in order to debug the error / what we do know**:
- We tried running the same code (line 423 of that service file) that caused the error, with the same schema and json, in production, and it worked fine.
- This error can be triggered locally by replacing one of the schema objects (I used `timezone`, but it might work with others) in the JSON returned by `VetsJsonSchema::SCHEMAS.fetch 'SC-CREATE-RESPONSE-200_V1'` with a string. So in my example that I used, originally `schema['definitions']['timezone']` equals `{'type' => 'string', 'enum'=> [...]}` where `[...]` is an actual array (not the string we see in the error message) — I replaced that whole object with a random string and then ran `errors = JSONSchemer.schema(schema).validate(json).to_a` and it caused a similar error:

```
[12] pry(#<Decisierrors = JSONSchemer.schema(schema).validate(json).to_a
NoMethodError: undefined method `key?' for "test":String
```
- This was only happening to some veterans and not others. This has left those affected veterans with Supplemental Claim submissions in a partial state, as the error was raised before we hit the code that submits their evidence uploads to Lighthouse

## Action items
- [ ] Figure out how to replicate the error / why it's happening (submit platform ticket)
- [ ] Determine next steps for affected veterans (any necessary communications) and how to handle the submissions that made it through to Lighthouse
  - [ ] Figure out how/whether CMP/Lighthouse deals with duplicate submissions
- [ ] Write and run a script to submit un-submitted evidence uploads.

## Slack threads and background context
- Link to Slack [thread 1](https://dsva.slack.com/archives/C05FCEH2NRG/p1700687205319819).
- Link to Slack [huddle thread between the DR engineers](https://coforma.slack.com/archives/C05V2EGH493/p1700669654341269)
- Another [thread amongst DR engineers](https://coforma.slack.com/archives/C05V2EGH493/p1700683637679109)
- [Link to spreadsheet with more info on affected veterans (no PII, shared with Eugene and Sade)](https://docs.google.com/spreadsheets/d/1vH04ksQufBWuV7zkIwSBd0ijZq8iCJOUNsIhm0f86hE/edit?usp=sharing)

## Definition of Ready 
- [ ] Timebox is defined
- [ ] Nature of the issue defined

## Definition of Done
- [ ] Document any parts of code that can't be covered due to library limitations
- [ ] We know if this can be logged, and add L&M if possible

## Out of scope
- Coding solution

**Comment by saderagsdale** [comment]
@anniebtran will reach out to platform to open the discussion.

**Comment by saderagsdale** [comment]
@anniebtran Can you point me to the thread we said we wanted to start with platform for the SC bug? Also want to add it to the bug ticket.

**Comment by anniebtran** [comment]
@saderagsdale 

1. Here's the [thread](https://dsva.slack.com/archives/CBU0KDSB1/p1701445693703579)
2. and 3. — I'll grab that info for ya and put the list of affected claims/evidence files in a spreadsheet

**Comment by anniebtran** [comment]
@saderagsdale I've shared the spreadsheet with you and @data-doge but also updated the description of this ticket with a link to it as well. I've highlighted the instances where the veteran still has their In-Progress form and can just try resubmitting. 

But you'll also notice that I also highlighted about 3 veterans who had submissions that partially went through (i.e. their form submission went through, but their evidence submissions did not), and will need some additional steps to get their submission complete. Other folks may be more aware of other workarounds, but unfortunately, I don't think we have access to the evidence upload file data like we did with NOD. I poked around the `AppealsApi::SupplementalClaim` data model and `form_data` did not include any upload info (which makes sense [given the code structure](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/controllers/v1/supplemental_claims_controller.rb#L23)). So I'm not confident that we'll be able to automate this work with a script... unless we can find another way to connect uploads with their claims. Otherwise, I'm not sure what other steps we could take before asking the veteran to upload their evidence again (if that's possible).

**Comment by data-doge** [comment]
An update here: two more instances of this error for HLR. https://dsva.slack.com/archives/C05UPRR0HK3/p1701800255220879

**Comment by saderagsdale** [comment]
I'll connect with Zach G and ask to spin up an email with VBA.

**Comment by anniebtran** [comment]
Met with @data-doge to catch them up on this before I head out for some time off, but just to summarize:

The remaining work here is to address the veterans in the spreadsheet, which we're waiting to hear back about in terms of whether the VA will resolve missing evidence from SC submissions or if we need to handle that on our end. 

I don't _think_ there's a way for us to submit the evidence on behalf of the veteran because I don't think the upload data is persisted in the Lighthouse records in the same way as it was when we had issues with NOD v2. So we would have to find another way to connect the records, or ask the veterans to submit their evidence.

**Comment by saderagsdale** [comment]
@anniebtran Remediation can be a separate task from the spike. I've already tee'd up the convo with Zach and Cory.

**Comment by saderagsdale** [comment]
I sent an email to VBA (Alejandro Mendelioflores) asking them to let us know what claim data they need to tackle these.
