### ISSUE TITLE
CANCELLED TASK - Step 5 Financial info, net worth: Create new page and question for Do you have more than 4 sources of income?

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#70535]
## Note
Part of the larger effort to update the existing 527EZ form to add missing fields/info and remove depreciated fields.

## Description
On Step 5 of Financial Information: net worth,

- create a new page for the `Do you, your spouse, and your dependents have a total of more than 4 sources of income?` question
- Include grey warning copy if they answer "yes"
- match all copy to designs

## Designs
- Main page example: https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/548B49E5-BBEF-4632-B920-FCA0D75EE2E0
- If they answer "yes": https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/BD26FB1E-D088-4DCD-8A8F-3BE3903450BF
- Prototype: https://sketch.com/s/94592459-f741-45a0-9432-efd685b9a1d5/a/0AdzDLA/play
- Wireflows: https://www.sketch.com/s/94592459-f741-45a0-9432-efd685b9a1d5/a/JArmY2e

## Acceptance Criteria

**New page:**
Create 1 new page under: `Income and assets`

In this page, add the following radio button question/field:
`Do you, your spouse, and your dependents have a total of more than 4 sources of income?`
`Yes`
`No`

**Validation info:**

If they answer "Yes", add a grey warning copy box that says the following:
`You'll need to submit an Income and Asset Statement in Support of Claim for Pension or Parents' Dependency and Indemnity Compensation (VA Form 21P-0969). Report only your Social Security income in this section.`

`We'll ask you to upload this form at the end of this application. Or you can mail it to us.`

`Get VA from 21P-0969 to download.`

Link to 21P-0969; will open as a new tab: https://www.vba.va.gov/pubs/forms/VBA-21P-0969-ARE.pdf

For either answer, the next page/question will be to the new Gross Monthly Income section of questions (Pending design decision) - **CHECK WITH VICKY/MAYA ON THIS VALIDATION**

**Match copy:**
Ensure all copy, including headers, questions and buttons match the designs.

## Tasks
[Software Development Tasks](https://docs.google.com/document/d/1vtn5co_YzGl1cFRNrIBAdjf53dmfH4_EXBWK8C5mU9Y/edit?usp=sharing)

- [ ] Front-end work

## Review
- [ ] Designer (Maya) has signed off on pages in staging

## Artifacts
- [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/527EZ-reactivation-initiative-brief.md)
- [User flow in Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683826730324/61b509f935adaa2acf2f7769a5ba911726a7b237?sender=u9d01ee38af217e4877e75660)
- [Prototypes in Sketch](https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/p/6571319D-6329-4249-B0A7-E39DA9DA31F4/canvas)
- [Spreadsheet of deleted form fields](https://docs.google.com/spreadsheets/d/1PTXxO6mFH2ZUK6XxX7iCCQb-NoSvhB5P/edit?usp=sharing&ouid=104362113771391164792&rtpof=true&sd=true)
- [Content source of truth/PDF form](https://www.vba.va.gov/pubs/forms/VBA-21P-527EZ-ARE.pdf)
- [Link to testing accounts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/form-deactivation/527EZ-staging-test-accounts-accessible.md)
- [Link to staging](https://staging.va.gov/)

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/70535?planning-poker) with Zenhub @mjknight50 @TaiWilkin @ToddWebDev @zack

**Comment by vbellissimo** [comment]
PDF mapping question:

<img width="700" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXc1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f01f8e1e1af57de53dcdaf7f9c371752590534bb/Screenshot%202023-12-06%20at%209.37.37%E2%80%AFAM.png" alt="Screenshot 2023-12-06 at 9.37.37 AM.png" />
