### ISSUE TITLE
[FE] Address validation: Analytics fix

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#7054]
## Background

[Our analytics for address validation](https://analytics.google.com/analytics/web/?authuser=0#/dashboard/iu8jeYo2RHGNcjQhmx2sjQ/a50123418w177519031p176188361/) are currently showing more addresses suggestions used than address suggestions provided, which is obviously impossible. According to @bradl3yC:

> When we show the modal and provide no suggestions and they click `Use this address` its still counting as a address suggestion used when it should not.  This is because we check the selectedAddressId and if its not userEntered - it counts as a yes.  For some reason, the previous code to make it say userEntered when there are no suggestions is gone and it was defaulting to null - which qualifies as a true when we just check it against a string of userEntered :-./

## Tasks

- [ ] Clean up analytics to differentiate between when a suggestion is used and when someone overrides/saves/

## Acceptance Criteria

- [ ] Analytics are correctly differentiating between when users select a suggested address and when they use override.

**Comment by jonwehausen** [comment]
@bradl3yC Thanks for identifying the underlying issue here! Keep me posted on when this makes its way to staging and if we have a test address to reproduce this scenario and we can verify if there will need to be any changes on our front.

**Comment by jonwehausen** [comment]
Thanks again for clearing this up brad! 

Confirming this as the test scenario -- an invalid address where the modal still shows, but no suggestion is provided. When the user clicks 'Use this Address', `'no'` is now populating for ```profile-addressSuggestionUsed```. This was tested for both Home and Mailing address. 
![image](https://user-images.githubusercontent.com/48527022/77205172-a9077e00-6aca-11ea-8188-c91d6cc7e687.png)
![image](https://user-images.githubusercontent.com/48527022/77205303-f84dae80-6aca-11ea-865c-8953a71fd5c8.png)

@Samara-Strauss Confirming this is a scenario we want to count as an "override", correct?

**Comment by Samara-Strauss** [comment]
@jonwehausen! Yes, that is correct but not totally the full story. Yes, when there is no suggestion and someone selects "Use this address", they are overriding. BUT they can also override when there IS a suggestion if they select the original address and not the suggested address, like so:

![7  Scenario 1: Override; Suggestions_Override selected](https://user-images.githubusercontent.com/34068740/75388049-50213d00-58b2-11ea-84cd-da25c4b6d128.png)

**Comment by jonwehausen** [comment]
Great, thanks for confirming! And yes -- we will be squared away in your scenario above as well.

**Comment by jonwehausen** [comment]
Hi @Samara-Strauss,

Please use this most updated [template ](https://analytics.google.com/analytics/web/template?uid=N-V2gGQzQkO-eRCfVuFq5Q) for your metrics moving forward. 

We have corrected the override issue and are now explicitly calling out within the dashboard above. 

Let us know if you have any more questions / concerns.

**Comment by Samara-Strauss** [comment]
Great! Thanks for this!

Question — When did the fix go live to correctly differentiate between suggestions and overrides? The numbers are still wonky so I want to make sure I can test that the fix actually did work by isolating the data from the date the fix went out.

**Comment by bradl3yC** [comment]
This was merged Friday and is not in production yet.  It should go into
production today.

**Comment by Samara-Strauss** [comment]
Thanks, @bradl3yC. If this issue looks like we've fixed it by Wednesday (giving a full 24 hours of data on Tuesday to determine this), then we can close out this ticket. But let's leave it open until then just in case.

**Comment by mshea0606** [comment]
@jonwehausen Hey Jon! As we discussed earlier it would be great if you could include "count of save errors" data from the former state of updating address info related in the new Address Validation dashboard. This would allow us to see the impact/drop in "save errors" as a result of address validation.  @Samara-Strauss

**Comment by Samara-Strauss** [comment]
@mshea0606 did you go to the new link? This info appears to already be on there. https://analytics.google.com/analytics/web/importing/?authuser=0&utm_source&utm_medium&utm_term&utm_content&utm_campaign#importing/a50123418w177519031p176188361/%3F_.objectId%3DN-V2gGQzQkO-eRCfVuFq5Q%26_.selectedProfile%3D/

<img width="1051" alt="Screen Shot 2020-03-23 at 11 46 24 AM" src="https://user-images.githubusercontent.com/34068740/77335038-ffa7ce80-6cfb-11ea-8c08-895b356a64dc.png">

**Comment by mshea0606** [comment]
@Samara-Strauss Jon mentioned we could bring in those same data tiles in addition to what already exist  but for pre- address validation launch date range  (so we can compare pre-post launch numbers)

**Comment by Samara-Strauss** [comment]
@mshea0606 for what time period would the pre-data be?

**Comment by jonwehausen** [comment]
Hi @Samara-Strauss and @mshea0606,

Thanks for your patience and notes here. 

@Samara-Strauss -- Regarding your question [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7054#issuecomment-602673857), following post-launch testing there was an additional tweak we published out yesterday (3/22) afternoon to improve the accuracy of the numbers of validations needed around when a user clicks "edit" after already receiving a validation.  This was causing the Validations Needed number to inflate. This was not impacted by @bradl3yC work at all and was solely a correction on our end --This has since been corrected. 

@mshea0606 -- Happy to set the "pre" launch data to the duration of your choice. Per our conversation, sounds like we want this to be 30 days prior. 

For you both -- Since there is a limit on having only 12 elements on the dashboard at a time (good analytics restriction unfortunately), I'll need to refactor to include the pre launch data. @Samara-Strauss or @mshea0606 Is there anything on the current dashboard that is unnecessary we can remove in order to make room for the pre-launch data?

**Comment by Samara-Strauss** [comment]
Tbh I don't think pre-launch data is necessary enough to jump through those hoops. Everything we have there now is helpful, and we can easily adjust the date to get the "pre" metrics.

**Comment by mshea0606** [comment]
@Samara-Strauss @jonwehausen Agreed

**Comment by joanneesteban** [comment]
@Samara-Strauss - let us know if you need anything else!

**Comment by Samara-Strauss** [comment]
Looks like everything has been fixed! I isolated the data from Tuesday to today, so a full 24+ hours since the fix launched on Monday. Thank you for this! Closing this ticket 😃 

<img width="293" alt="Screen Shot 2020-03-25 at 11 07 09 AM" src="https://user-images.githubusercontent.com/34068740/77551519-d799a600-6e88-11ea-89de-bb2e96ad45f2.png">
