### ISSUE TITLE
CONSIDER: [CMS-Editorial_UE] Improve the "Edit Link" URL function to show fully qualified url instead of NODE [CMS]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#7055]
## User Story or Problem Statement
As PAO/CMS editor, I need to have a clear and easy to understand editorial experience,  so I can best maintain and support my System and facility web experience.

## Goal
_Clarify and create a easy to use and understand editorial user experience on all CMS pages_

## Objectives or Key Results this is meant to further
- _Improve self organization and clarification of editorial descriptions and use_

## Resources - Tools - Documentation
[CMS Staging Environment](https://staging.cms.va.gov/)
[CMS Prod Environment](https://prod.cms.va.gov/)

## Tasks
_Write Intro content for the following Facilities:_
- [ ] Have ADD LINK tool in WYSIWYG and editor tool show actual fully qualified URL instead of internal NODE.  (e.g.:  ADD LINK allows drop down with content and owner, then only Node is shown)

![Add_Link_URL_DD1.jpg](https://images.zenhubusercontent.com/5dae20cd6a7fc5000106eec0/792a6195-c14c-4a50-a23f-0deb7838febf)

![Add_Link_Node2.jpg](https://images.zenhubusercontent.com/5dae20cd6a7fc5000106eec0/ba5014cb-7534-4025-8307-8ff4bacd7daf)

## Acceptance Criteria
_Confirm all have been reviewed and documented in Content Approval Process folder on Google Drive_
* ADD LINK will show same name chosen in drop down or the fully qualified URL, to improve understanding of what was chosen.

**Comment by davidmpickett** [comment]
Not actionable per @swirtSJW. This is core functionality of Link field type
