### ISSUE TITLE
CANCELLED TASK - Step 5 Financial info, expenses: Create new page and question for Child's expenses/provider 1: start & end dates

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#70564]
## Note
Part of the larger effort to update the existing 527EZ form to add missing fields/info and remove depreciated fields.

## Description
On Step 5 of Financial Information: expenses,

`[_autofill with child name_]'s care expenses`

- create a new page for the new required questions/fields:
-- Provider start date
-- Provider end date
-- No end date checkbox option
- match all copy to designs

## Designs
- Main page example: https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/a/uuid/782A6E43-F862-42BC-B0AE-35B9F58760F3
- User flow view: https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/v/myZ4d9/p/6571319D-6329-4249-B0A7-E39DA9DA31F4/canvas?posX=-115025.29934943122&posY=-56767.604331742&zoom=0.10149698704481125

## Acceptance Criteria

**New page:**
Create 1 new page: `[_autofill with child name_]'s care expenses`

Add the following sub header:
[_auto fill with name of provider entered prior_]

Add the required question/field:
`Provider start date (*Required)`
_Month/Day/Year format_

Add the required question/field:
`Provider end date (*Required)`
_Month/Day/Year format_

Add the checkbox for:
`No end date`

**Validation info:**

The next page/question will be to: Child's care expenses/[_provider 1 entered_] How much do you pay?, as shown on #70565

**Match copy:**
Ensure all copy, including headers, questions and buttons match the designs.

## Tasks
[Software Development Tasks](https://docs.google.com/document/d/1vtn5co_YzGl1cFRNrIBAdjf53dmfH4_EXBWK8C5mU9Y/edit?usp=sharing)

- [ ] Front-end work

## Review
- [ ] Designer (Maya) has signed off on pages in staging

## Artifacts
- [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/527EZ-reactivation-initiative-brief.md)
- [User flow in Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683826730324/61b509f935adaa2acf2f7769a5ba911726a7b237?sender=u9d01ee38af217e4877e75660)
- [Prototypes in Sketch](https://www.sketch.com/s/eef97a50-994f-4b3b-ad81-1dc7d3e3b0fc/p/6571319D-6329-4249-B0A7-E39DA9DA31F4/canvas)
- [Spreadsheet of deleted form fields](https://docs.google.com/spreadsheets/d/1PTXxO6mFH2ZUK6XxX7iCCQb-NoSvhB5P/edit?usp=sharing&ouid=104362113771391164792&rtpof=true&sd=true)
- [Content source of truth/PDF form](https://www.vba.va.gov/pubs/forms/VBA-21P-527EZ-ARE.pdf)
- [Link to testing accounts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/form-deactivation/527EZ-staging-test-accounts-accessible.md)
- [Link to staging](https://staging.va.gov/)

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/70564?planning-poker) with Zenhub @mjknight50 @TaiWilkin @ToddWebDev @zack
