### ISSUE TITLE
VA Profile Veteran Status and Military Information prod rollout

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#70590]
Staging testing for the eMIS to VA Profile migration has gone well and it's time to turn on the flippers in prod. When we turn on the flippers, we want to monitor logs and set up alerting so we can validate (or not) that the rollout is going smoothly. 

👀 Where to look:
- Datadog APM [save-in-progress](https://vagov.ddog-gov.com/apm/services/save-in-progress/operations/rack.request/resources?env=eks-prod&panels=qson%3A%28data%3A%28%29%2Cversion%3A%210%29&resources=qson%3A%28data%3A%28visible%3A%21t%2Chits%3A%28selected%3Atotal%29%2Cerrors%3A%28selected%3Atotal%29%2Clatency%3A%28selected%3Ap95%29%2CtopN%3Aall%29%2Cversion%3A%211%29&summary=qson%3A%28data%3A%28visible%3A%21t%2Cerrors%3A%28selected%3Acount%29%2Chits%3A%28selected%3Acount%29%2Clatency%3A%28selected%3Alatency%2Cslot%3A%28agg%3A95%29%2Cdistribution%3A%28isLogScale%3A%21f%29%2CshowTraceOutliers%3A%21f%29%2Csublayer%3A%28slot%3A%28layers%3Aservice%29%2Cselected%3Apercentage%29%29%2Cversion%3A%211%29&topGraphs=latency%3Alatency%2Chits%3Acount%2Cerrors%3Acount%2CbreakdownAs%3Apercentage&view=spans&start=1701643167218&end=1701729567218&paused=false).
  - [x] Look for: Any change in error rate? Any new errors?
- Datadog [in-progress-forms](https://vagov.ddog-gov.com/logs?query=service%3Avets-api%20env%3Aeks-prod%20%40http.url_details.path%3A%2A%5C%2Fv0%5C%2Fin_progress_forms%2A%20&cols=host%2Cservice&index=%2A&messageDisplay=inline&refresh_mode=sliding&stream_sort=desc&view=spans&viz=stream&from_ts=1701631589216&to_ts=1701717989216&live=true) logs.
  - [x] Look for: Are there any errors? Is there any PII in the logs?
- Search Sentry for [prefill:va_profile_prefill_military_information](http://sentry.vfs.va.gov/organizations/vsp/issues/?query=is%3Aunresolved+prefill%3Ava_profile_prefill_military_information&statsPeriod=14d) tag.
  - [x] Look for: Any errors?
- Search Sentry for [prefill:vaprofile_military](http://sentry.vfs.va.gov/organizations/vsp/issues/?environment=production&query=is%3Aunresolved+prefill%3Avaprofile_military&statsPeriod=14d)
  - [x] Look for: Any errors? YES 🔴 
- "VAProfileError" OR "IDCardAttributeError" [filtered logs](https://vagov.ddog-gov.com/logs?query=service%3Avets-api%20env%3Aeks-prod%20%28%22VAProfileError%22%20OR%20%22IDCardAttributeError%22%29%20&cols=host%2Cservice&index=%2A&messageDisplay=inline&refresh_mode=sliding&stream_sort=desc&viz=stream&from_ts=1701806944497&to_ts=1701810544497&live=true)
  - [x] Look for: Any errors?
- [controller:v0/id_card_attributes](https://vagov.ddog-gov.com/metric/explorer?graph_layout=multi&start=1702478772744&end=1702565172744&paused=false#N4Ig7glgJg5gpgFxALlAGwIYE8D2BXJVEADxQEYAaELcqyKBAC1pEbghkcLIF8qo4AMwgA7CAgg4RKUAiwAHOChASAtnADOcAE4RNIKtrgBHPJoQaUAbVBGN8qVoD6gnNtUZCKiOq279VKY6epbINiAiGOrKQdpYAEwGIFCeGE4a+NoAxkrIIOoIulmWgWZxyhgAbjDIlYgaThjyEAB0GgieGlAtTRBO2hhZANb9JmbtwFlShThoaDq1AAwA9NBOWRjaUI0IhRAARgSaAAQUx3AilchwQxoAtPLaOFA8PQ1TeCIIABQAlCA8AC6VFc7jwmFC4VBqnBGBiZQSAOBIHaWHmMhA8gw812uRRcA8XwgWSSaFEcCcckUygyZKgpPJTnoTGUIjcHjQAP4EHsmCwlIUeLJIiUQJ4fBR8jJCAAwlJhDAUCJwWgeEA). This is a smilar [datadog metric](https://vagov.ddog-gov.com/logs?query=service%3Avets-api%20env%3Aeks-prod%20%40payload.controller%3A%22V0%3A%3AIdCardAttributesController%22%20&cols=host%2Cservice&index=%2A&messageDisplay=inline&refresh_mode=sliding&stream_sort=time%2Cdesc&viz=stream&from_ts=1702066214386&to_ts=1702671014386&live=true)
  - [x] This metric stopped after veteran status was turned on. So make sure there are requests coming in.

**Comment by rmtolmach** [comment]
1. ✅ Save-in-progress APM looks unchanged. The errors being tracked there are not new. 
2. ✅ There are no error in the in-progress forms logs. Lots of info-level messages. Most attributes were `FILTERED` (booleans look like they're not filtered, but that is not new). For the 10-10 form, the field `va_compensation_type` is listed in the form data params during a time when the military_info flipper was on and off and before and after https://github.com/department-of-veterans-affairs/vets-api/pull/14824 was merged).
3. :x: Sentry for `prefill:va_profile_prefill_military_information` tag. YES, there are a few errors affecting < 20 people.

**Comment by laineymajor** [comment]
This should be closed by end of this sprint.

**Comment by rmtolmach** [comment]
All metrics look good. Closing 🎉
