### ISSUE TITLE
[MVP] Step 4 Household Info: Remove Type of Marriage field from Veteran's Spouse's Former Marriage

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#70596]
## Note
Part of the larger effort to update the existing 527EZ form to add missing fields/info and remove depreciated fields.

## Description
On Step 4 of Household Information,

Remove the following questions:
- Type of marriage

From the **_veteran's spouse's prior marriages (not from their own prior marriages)_**

As shown on the designs

## User Story
As a Pension team,
we want to remove unnecessary questions about the **_veteran's spouse's prior marriages (not from their own prior marriages)_**,
so that we can better align the form questions to match the new PDF version.

## Acceptance Criteria

The following question/field will not exist in Spouse's former marriage set of questions:
- Type of marriage

## Tasks
[Software Development Tasks](https://docs.google.com/document/d/1vtn5co_YzGl1cFRNrIBAdjf53dmfH4_EXBWK8C5mU9Y/edit?usp=sharing)

- [ ] Front-end work

## Review
- [ ] Someone on the Pension team will review/QA

## Artifacts
- [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/527EZ-reactivation-initiative-brief.md)
- [User flow in Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683826730324/61b509f935adaa2acf2f7769a5ba911726a7b237?sender=u9d01ee38af217e4877e75660)
- [Prototypes in Sketch](https://www.sketch.com/s/75b363db-6be8-4b7e-8655-8f12f1ea5554)
- [Spreadsheet of deleted form fields](https://docs.google.com/spreadsheets/d/1PTXxO6mFH2ZUK6XxX7iCCQb-NoSvhB5P/edit?usp=sharing&ouid=104362113771391164792&rtpof=true&sd=true)
- [Content source of truth/PDF form](https://www.vba.va.gov/pubs/forms/VBA-21P-527EZ-ARE.pdf)
- [Link to testing accounts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/form-deactivation/527EZ-staging-test-accounts-accessible.md)
- [Link to staging](https://staging.va.gov/)

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/70596?planning-poker) with Zenhub @mjknight50 @TaiWilkin @ToddWebDev @zack

**Comment by TaiWilkin** [comment]
@vbellissimo I believe we already removed this - here's the current staging view for veteran's spouse's former marriages: <img width="350" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzlpQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1db342563a11d268688dc2b72309c337c94f2e12/Screenshot%202023-12-14%20at%204.55.56%E2%80%AFPM.png" alt="Screenshot 2023-12-14 at 4.55.56 PM.png" />

**Comment by vbellissimo** [comment]
@TaiWilkin that makes sense, if the new design didn't have it to begin with. Okay, thank you for flagging!

**Comment by vbellissimo** [comment]
I'll move this to the completed column.
