### ISSUE TITLE
audit and remove unused github teams

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#706]
Adit github teams for va.gov/vets.gov.  There are several teams that look like they are no longer used and contain people who are not part of any department-of-veterans-affairs contracts any more. 

These teams might be able to go
https://github.com/orgs/department-of-veterans-affairs/teams/vets-gov-engineers/members
https://github.com/orgs/department-of-veterans-affairs/teams/ad-hoc-non-vets-gov-devops/members

and a list of people I know or guess are no longer part of VA contracts or  https://github.com/orgs/department-of-veterans-affairs/teams/ad-hoc-general
Graham Smith  gcs272
Claire Hsu  cehsu
Kaitlin Devine  kaitlin
Kristin  Kristin215
Lindsay Ferris  ljoelle
Melanie Gershman  melaniegershman
Mike Eng  mrengy
nagaborra ??
sprayaga4 ??
Stacy Linn  stacyhlinn
va-dittrich ??

**Comment by ricetj** [comment]
@ricetj to check in

**Comment by FranECross** [comment]
Closing due to age and inactivity. More than likely obsolete. Can reopen if needed in the future, or a new ticket created.
