### ISSUE TITLE
Data quality audit - VSO info on VA.gov - Rivka

### ISSUE THREAD

**Issue by uxrebecca** [department-of-veterans-affairs/va.gov-team#70600]

**Comment by RivkaCGates** [comment]
@uxrebecca can I get a comment on this with what was done?

**Comment by uxrebecca** [comment]
Renata, Rivka, and I attended the data quality audit meeting with ARM to review database entries and identify which data was accurate and which was outdated. There is no more work to do on our part related to this.

(This is the ticket assigned to @RivkaCGates but there are also two resolved tickets assigned to @uxrebecca #70597 and @RenataKeck)
