### ISSUE TITLE
User-types follow-on, and document in github

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#70609]
### User story
As a cartography team member, I want to share the output of user-type data analysis work done in an earlier sprint on GitHub so that it is visible to other teams if relevant to their work, and it could potentially inform a larger health portal-wide data dashboard. 

## Description
This ticket is follow-on UX "tech debt" to add our findings from ticket #67679 to Github.

_from comment on #67679_
>Will create a follow on story that addresses application of user types to the MHV tools and exposes documentation on GitHub

A document [has already been started here ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/landing-page/analytics-user-segmentation.md) but was not finished. 

## Acceptance criteria

- User types documentation is summarized and [added to Github here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/landing-page/analytics-user-segmentation.md).

## Tasks
- [x] Look at [Google doc](https://docs.google.com/document/d/1RqBUNmtjbynDTWpSsNyECX2_eN0bGp0SL3c_YLwSzto/edit#heading=h.vtecmxpstkp6) and [Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1699380640123/50db0eabbcc3e40bb9bee48d20c3d1ee763f3816?sender=uf94a77a19aaf687331c09367)
- [x] Summarize findings into a GitHub page

**Comment by keithcheung828** [comment]
[Github page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/landing-page/analytics-user-segmentation.md) has been updated.
