### ISSUE TITLE
Adding Olateju (TJ) Shafe to DSVA Slack

### ISSUE THREAD

**Issue by huggins-va** [department-of-veterans-affairs/va.gov-team#70617]
Please add Olateju Shafe to DSVA Slack as a multichannel user to: 
email: shafe_olateju@bah.com

- vaapi-platform and
- team-honeybadgers-support 

Olateju is a senior DevOps engineer onboarding onto Lighthouse team Honey Badgers (and new DI team) and needs access to perform his daily assignments. 

thank you!

**Comment by LEHigley** [comment]
couldn't add to either, invited to general
