### ISSUE TITLE
Update typo on this page

### ISSUE THREAD

**Issue by tommasina-va** [department-of-veterans-affairs/va.gov-team#70625]
### Description

<img width="581" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/144388524/60b21da2-aceb-4117-ace3-1616f98bb9de">

MVICorpDB appears to be a typo, and should be "MVI and CorpDB"

### Relevant URLs

https://depo-platform-documentation.scrollhelp.site/developer-docs/partner-services-upstream-services

### Which type of team are you on? (Platform team, VFS team, or Leadership)
VFS team

**Comment by taylojill** [comment]
Typo corrected. No launch blocking issues, ready to deploy.

**Comment by taylojill** [comment]
Typo corrected. No launch blocking issues, ready to deploy.

**Comment by johnny-jesensky-adhoc** [comment]
Hi @tommasina-va, fully closing the loop on this - [this fix](https://depo-platform-documentation.scrollhelp.site/developer-docs/partner-services-upstream-services) is now live. Thanks again for flagging this!

FYI @taylojill
