### ISSUE TITLE
[QA] 10-10EZR: Test Scenarios 11/27

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#70627]
As a Veteran, I would like to update my information online and have it be saved by the VA so that I don't have to mail in a paper form to make changes to my data.

**AS Note 11/27**: these are by no means exhaustive, but these are test cases I've compiled over the last week to test different hypotheses, issues, and fixes we've come across.

- [x] Come up with user information to test (e.g. Disability Rating, Financial amounts, dummy insurance, etc.)
- [x] Write Test Cases
- [x] Run Tests
- [x] Determine if changes are made in VES (where applicable)
- [x] **Success: We have tested all of the below scenarios **

**General E2E:**

- [x] Financial data goes through to VES (Fix #[70381](https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/70381)) (less than 50% disability)
- [x] Insurance info goes through to VES (less than 50% disability) ]
- [x] Insurance and financial and Medicare go through to VES at same time (less than 50% disability, repeating what user research user did, outlined in #[70228](https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/70228))

**Means Test (all for users with Disability <50%):**

- [x] Submitting just FY financials triggers MT 
- [ ] Different financials amounts  triggering MT - Not Valid
- [ ] Different financial inputs and deductibles (e.g. Spouse income, education expenses, burial expenses) trigger MT - Not Valid
- [ ] Submitting just new Dependent, no financials, triggers MT - Not valid
- [ ] Submitting Dependent expenses triggers MT - not valid
- [ ] Does removing Dependent triggers MT? - Not Valid
- [x] Look into other things that could trigger MT? - MT is done only when entering new financials when there are none present/no means test on file 

**Statuses:** (Adding statuses has been descoped from MVP, so if we've already testing that an Enrolled user can access the EZR and an unenrolled user cannot, then we can mark these as done)

- [x] Enrolled can enter
- [x] Unenrolled cannot enter

**2MT (Two means test in one calendar year):**

- [x] 2MT user cannot see/enter financials–gets alerts 
- [ ] What happens if a second means test is submitted? (hopefully not possible) (**Blocked-not sure how to test this?**) - Not Valid

**Content and Layout**

- [x] STG Review typos/content fixes (Fixes for #[70296](https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/70296))
- [x] STG review layout (fixes for #[70306](**https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/70306**))
- [x] STG review screen reader (fixes for #[70306](**https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/70306**))
- [x] “Education expenses” verbiage tweak (Blocked #70873 )

**Comment by hdjustice** [comment]
Scenario 1 with test user 40 - Successful
- Submitted with income $34000
- Not married, no dependents, no deductibles, no insurance

**Comment by hdjustice** [comment]
Scenario 2 with test user 40 - Successfull
- Submitted with
     - Never married
     - No dependents
     - $15k gross
     - $15k farm/business
     - $4k other
     - $1,000 medical ded
     - $1,500 college ded
     - $2,000 funeral/burial ded
     - No Medicaid or Medicare
     - 1 Insurance policy

**Comment by hdjustice** [comment]
Scenario 4 with test user 40 - Successful
Rx test completed
Copay test completed - Exempt due to low income (means test!)

- Never Married
- No dependent
- $15,000 gross income
- $0 farm/business income
- $0 other income
- $500 medical ded
- $0 college ded
- $0 funeral/burial ded
- Medicaid No
- Medicare No
- Insurance No

**Comment by hdjustice** [comment]
Scenario - No Financial data submitted, Insurance information submitted (financials exist already - Means test already run for previous year)
     - Test user 40 - **UNSUCCESSFUL** - Only Private Insurance populated for user in ES
          - Spouse pages skipped
          - Dependents pages skipped
          - Income/Deductibles pages skipped
          - Medicaid - Yes
          - Medicare - Yes, Eff date and 11 digit claim number M1234567890 added
          - Insurance Policy entered - A987654
     - Expected Results:
          - Rx test and Copay test not run, previous test on record
          - Insurance info added/updated

**Comment by hdjustice** [comment]
Scenario - High Income - Spouse, Dependent, Financial & Insurance data submitted when financials DO NOT exist (Means test not yet run for previous year)
- Test users 40 - **UNSUCCESSFUL** - Medicare Eff Date and Claim number did not populate in ES
     - Married, add spouse
     - Dependent, add child
     - Gross Income $15,000
     - Net Farm/business income $15,000
     - Other income $5,000
     - Spouse income $25,000
     - Medical deductible $1,000
     - College deductible $1,500
     - Funeral/burial deductible $2,000
     - Medicaid - NO
     - Medicare - Yes, Eff date 11/1/2020 and 11 digit claim number M1234567890 added
     - Insurance - No
    
#### Expected Results:
- Rx test run, non-exempt - test user is over the income limit for Rx concessions. 
- Copay test run, non-exempt - test user is over the income limit
- Spouse is added to record
- Dependent is added to record
- Medicare added to record
- Private Insurance previously existing is retained
#### Actual Results:
- Rx test run, non-exempt - test user is over the income limit for Rx concessions. 
- Copay test run, non-exempt - test user is over the income limit
- Spouse is added to record
- Dependent is added to record
- **Medicare NOT added to record**
- Private Insurance previously existing is retained

**Comment by hdjustice** [comment]
Our team is looking into the issue, seems to be on the frontend.

**Comment by hdjustice** [comment]
all non-financial related data can be updated.  Only when there are no financials on record/no means test on record, will the form allow the user to enter financials, spouse/dependents information.  Then a means test is done automatically
