### ISSUE TITLE
LHDI: Complete Onboarding Request for SecRel

### ISSUE THREAD

**Issue by lmorris3** [department-of-veterans-affairs/va.gov-team#70630]
- [x] Complete onboarding request for SecRel

Mural link https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1684963245734/426a066d466aad4b985d0c6fdc1887ef18cd6a8d?sender=uea69eca39541ca1a0bea5755

**Comment by rdvyas** [comment]
https://github.com/department-of-veterans-affairs/lighthouse-tornado-secrel-pipeline-onboarding/issues/650

**Comment by rdvyas** [comment]
We have completed the onboarding to the SecRel pipeline. This was done via a GitHub ticket that went through the process. This is noted in the following link:

https://github.com/department-of-veterans-affairs/lighthouse-tornado-secrel-pipeline-onboarding/actions/runs/7479300189

Closing ticket as SecRel onboarding is complete.
