### ISSUE TITLE
Adding Syd Hoeper to DSVA Slack

### ISSUE THREAD

**Issue by dhill802** [department-of-veterans-affairs/va.gov-team#70659]
Please add Syd Hoeper new Ad Hoc UX Researcher/Designer on CHAMPVA team to DSVA Slack as a Full Member.
[syd.hoeper@adhocteam.us](mailto:syd.hoeper@adhocteam.us)

They should be added to #vfs-all-teams, #vfs-change-announcements and any other pertinent UXR and VFS general channels for new team members.

**Comment by dhill802** [comment]
@eunicegar - FYI

**Comment by LEHigley** [comment]
theyr'e showign as a member
