### ISSUE TITLE
[UX][Content] AUDIT: Audit production and unified check-in headings

### ISSUE THREAD

**Issue by kellysmith1008** [department-of-veterans-affairs/va.gov-team#70673]
In doing research for a different issue, I discovered that there is a suggested heading character count in our design content standards. In this ticket, I'll audit the headings in our production and unified check-in workflows to determine which headings are ok and which may need tweaking if there's time. In a separate ticket, I'll address updating that content, and this audit may result in multiple tickets to break down the work if needed. No need for a frontend ticket from this ticket. 
Content guidance: 
- Try to keep page titles to 52 characters maximum, with spaces. Use the primary SEO keyword in the page title. On VA.gov, page titles use the H1 tag.
- Try to keep section and subsection titles to 70 characters maximum, with spaces.
- We allow a little more character count for sections and subsections than page titles. But in general, sections become hard to scan when they’re too long. Eliminate unnecessary details or nuance in section and subsection titles, and address them with more depth in the paragraph copy.
- A good rule of thumb is to hide all the text on a page, except the page title, section titles, subsection titles, and the primary CTA. If someone can still figure out what they need to do on that page or what that page is about, it’s a good sign that the page and section titles are working well.

## Tasks
- [ ] Review all H1 headings and make a list of those that are > 52 characters for production and unified Sketch files

**Comment by loripusey** [comment]
@kellysmith1008 the team decided to boil this effort down to just H1 headings and only finding those that exceed 52 characters

**Comment by kellysmith1008** [comment]
[Audit is complete for production and Unified Priority 1](https://docs.google.com/spreadsheets/d/1NYuMI0VCjNLXPo44swXmy-VjTdMtt_17cwK8KPmNdRk/edit?usp=sharing)
Unified: 5 headings need updating
Check-in Production: 4 headings need updating
Pre-check-in Production: 1 heading needs updating

3 of the total updates needed *may* have already been completed just not reflected in designs as they are 2 sentence headings in design but we are not using 2 sentence headings in the design system. Headings under 52 characters that are 2 sentences aren't required to be updated as part of this ticket, but could be lumped into the work in subsequent tickets to clean up all h1s in one task.

**Comment by kellysmith1008** [comment]
@loripusey @benbrasso-agile6 Could you take a look at the spreadsheet and let me know if there's a different way you'd like me to present this information?

**Comment by benbrasso-agile6** [comment]
Looks awesome! Do you want to stub out a ticket to update the h1 content for production (as a starting place)? Or, how do you want to split up the work?

**Comment by loripusey** [comment]
@kellysmith1008  Go ahead and create a ticket to update the H1s that need it (per your spreadsheet); we will also need a ticket to update the Sketch files (1 or 3 tickets, whatever is needed) cc: @benbrasso-agile6

**Comment by benbrasso-agile6** [comment]
We could do them in the same ticket, Kelly. Or separate. Doesn't really matter to me. 

Feel free to close this ticket when you're ready, Kelly. Nice work!

**Comment by kellysmith1008** [comment]
Can do - I'll work on the tickets this afternoon and copy them here too - then I'll close the ticket
Thanks!

**Comment by kellysmith1008** [comment]
[Update the h1s ticket for front end](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/72266) created and added to the Adhere to VA Content Guidelines for heading character counts epic. Closing this ticket - I'll update the content in the sketch files.
