### ISSUE TITLE
Replace date fields using input with select elements

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#70682]
It was discovered that some dates in the 526 application are coming through with an XX in the date field such as the obligationTermOfServiceDateRange causing a failure at the both primary and backup path after submission and resulting in need for fail safe processing. 

To fix this we are recommending to replace all date pickers so that input elements are replaced with select elements

Acceptance criteria:

1. Identify all date fields in the 526 flow that are using input element
2. Update date field to use the select element
3. Ensure change does not introduce impossible dates such as Feb 31st

**Comment by freeheeling** [comment]
@austinjprice – I didn't discover any other instances, besides the obligationTermOfService from and to date day field, that appeared to have this issue. The only instance where the problematic web component, VaMemorableDateField, was being utilized within benefits-disability was on this single page. From my review of the form flow and pass through the UI, all other Day fields appear to be utilizing a dropdown select that evaluates for valid dates (whether they be past, present or future, but not XX).
