### ISSUE TITLE
Separate Pension and Burial Failure Log

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#70696]
## Issue Description
_Pension and burial currently share a Central Mail failure log, which makes it difficult to determine which claims failed._

---
## Tasks
- [ ] Separate pension and burial failure log to denote which claim failed

## Acceptance Criteria
- [ ] Updated DataDog log
---

**Comment by vbellissimo** [comment]
The online 527 Pension form has migrated to the Lighthouse Benefits Intake API as part of the MVP relaunch for January 2024. Logging and monitoring has been set up separately for this form. Closing this, as it should no longer part of the Central Mail failure log.
