### ISSUE TITLE
Create a working case number (DB & FE)

### ISSUE THREAD

**Issue by mateoclarke** [department-of-veterans-affairs/va.gov-team#70703]
This issue expands the scope of one task from [this issues](https://github.com/department-of-veterans-affairs/va.gov-team/issues/70033). This is a full stack ticket but could be broken into the backend and frontend tasks separately.

- Stand up a case number table in a working DB
- Define and use consistent number/string formatting for the case ID
- Replace the hard-coded case number strings in both the intake and proofing app
- Create the action in the intake app that creates a new case number and assigns it to a user's appointment

**Comment by rdvyas** [comment]
During our team meeting we discussed this ticket. A major component of this ticket is the db table holding this information. @moanu404 has started this work and it looks near completion. 

The final step is updating the action in the UI so that the case number is generated.
