### ISSUE TITLE
LoROTA Security Issue

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#70710]

**Comment by brianseek** [comment]
Flagged all three scans as false positives. Moving on to working on dependbot PRs

**Comment by brianseek** [comment]
@wullaski I have a new lorota release currently deployed to stage. To validate this, do some normal check-in/pre-check-ins out on stage and lookout for any issues validating your user or fetching data. It looks like my history re-write did end up pushing commit hash changes to tags ¯\_(ツ)_/¯ so you will see some craziness when viewing the diff for this release. But viewing the commits themselves should reveal the changes which are just two dependbot updates.

**Comment by randomsync** [comment]
not sure what part in frontend the request to `v0/user` is being made, but it's not part of our app

**Comment by wullaski** [comment]
I don't see anything in our app maybe it's a call coming from the header.

**Comment by loripusey** [comment]
@brianseek does this one still need validating?
