### ISSUE TITLE
Qualitative Data Request

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#70714]
### Data Type Requested

User Surveys

### Data Source Type

Medallia

### Date Range Start

05/01/2023

### Date Range End

11/30/2023

### Product Name(s)

Claim Status Tool

### Product Description

The claim status tool is where veterans go to see the status of their claims and appeals, especially used for disability claims and appeals specifically.

### Survey URL(s), key term(s), case category or type

va.gov/track-claims

### File Delivery Format

One file, different tab for each term/URL

### Word Cloud

Yes

### VA Email Address(es)

jacob.worrell@va.gov

### Add Assignee and Labels

If not already done so, please ensure @newworld2616 is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by newworld2616** [comment]
Hi, I have shared the requested data, please verify once you receive it. Thank you!

**Comment by newworld2616** [comment]
Data Sent!
