### ISSUE TITLE
[FE] Add Refresh Button

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#70720]
## Summary
We currently have a refresh button and an automatic refresh timer in production that will update the check-in status for those appointments that are displayed. We need to include this feature in the Unified Experience.

## Wireframes

- [Priority 1 Sketch Page](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/868762F3-8E8F-4E23-B0DA-34C1783F0A03/canvas)

Example: 

<img width="330" alt="Screenshot 2023-12-19 at 3 58 09 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/101129355/24270b4e-fb6d-49aa-8ec3-f14bd98395cc">

## Tasks
- Add the refresh button to the Appointment List page
- When the refresh button is clicked
    - Re-retrieve today's appointment(s) 
    - Change the display of check-in status in the Task cards based on the retrieval
    - Change the display of check-in status in the Appointment list based on the retrieval
- When the automatic refresh timer goes off
    - Re-retrieve today's appointment(s) 
    - Change the display of check-in status in the Task cards based on the retrieval
    - Change the display of check-in status in the Appointment list based on the retrieval

**Comment by brianseek** [comment]
@loripusey / @benbrasso-agile6 / @cgednalske / @zach-park refresh button is in on our branch and ready to validate. To run locally pull this branch `git checkout check-in/61390/unified-release-2` then `git pull`

also see screenshot
<img width="674" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGUwQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8c91b8f0b10cad0607ace24d6107ad08225d344e/Screenshot%202024-05-03%20at%2010.41.44%E2%80%AFAM.png" alt="Screenshot 2024-05-03 at 10.41.44 AM.png" />

**Comment by zach-park** [comment]
@brianseek (Cc: @benbrasso-agile6 @cgednalske ), looks nice. Thank you!
--
(A side note for Brian, please note my other comment about the divider in #69903.)
