### ISSUE TITLE
Burial | Map form fields to new pdf

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#70721]
## Issue Description

[Figma Design Files](https://www.figma.com/file/jpJQSCKiGegacdW4RH5uQB/Burial-530-Redesign-MVP?type=design&node-id=174%3A43726&mode=design&t=C9b2ViKgeHHOCRbQ-1)

Fiorella compiled the following references:
- [530-Fields-to-be-deleted.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/13531721/530-Fields-to-be-deleted.xlsx)
- [527_530 va.gov differences.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/13531722/527_530.va.gov.differences.xlsx)

New PDF that online form fields will be mapped to is [here](https://www.vba.va.gov/pubs/forms/VBA-21P-530EZ-ARE.pdf).

Word version of pdf:
[VA Form 21P-530EZ.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/14102006/VA.Form.21P-530EZ.docx)

**Related front-end tickets:**
- [Burial Updates | Step 1: Claimant Info](https://github.com/department-of-veterans-affairs/va.gov-team/issues/71045)
- [Burial Updates | Step 2: Veteran Info](https://github.com/department-of-veterans-affairs/va.gov-team/issues/71102)
- [Burial Updates | Step 3: Military History](https://github.com/department-of-veterans-affairs/va.gov-team/issues/71104)
- [Burial Updates | Step 4: Benefits Section](https://github.com/department-of-veterans-affairs/va.gov-team/issues/71106)
- [Burial Updates | Step 5: Additional Info and Doc Upload](https://github.com/department-of-veterans-affairs/va.gov-team/issues/71112)
- [Burial Updates | Step 6: Review](https://github.com/department-of-veterans-affairs/va.gov-team/issues/71111)

Follow-on Ticket to connect new FE form fields to pdf #71046

---
## Tasks
- [ ] Map existing form fields to new pdf

## Acceptance Criteria
- [ ] New version of burial 530EZ pdf displays existing online form data

**Comment by steele-lm** [comment]
Some of the fields within the latest pdf version of the form are missing field names, and they may need to be added to allow the pdf to be fillable from vets-api. The pension form team did something similar, so they may be a good resource.

**Comment by sortizsh** [comment]
Blocked, need information from Emily. Need unencrypted version of PDF where fields are defined.

**Comment by steele-lm** [comment]
@evansmith and @sortizsh  [The direction from Emily](https://dsva.slack.com/archives/C057W3N9K2S/p1706635562044639?thread_ts=1706558873.032579&cid=C057W3N9K2S) was to proceed with the pdf and Word doc of the form that we have. She mentioned that the pdf was most likely poorly done and missing field names. She also mentioned that the pension team had encountered a similar situation.

**Comment by steele-lm** [comment]
530 pdf needs formatting updates to allow VA.gov to write to certain fields (e.g., checkboxes). The pdf is locked and cannot be edited, so Derek Uttley (VBA) suggested we reach out to Nancy Kessinger at OMS to submit our change order. @evansmith is compiling a list of changes to send.

**Comment by sortizsh** [comment]
coordinate with Pension team on minimal, maximal, overflow
