### ISSUE TITLE
AWS access for Marc Heusser

### ISSUE THREAD

**Issue by mheusgit** [department-of-veterans-affairs/va.gov-team#70730]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Marc Heusser

### Your Email

marc.heusser@adhocteam.us

### Team, Role, and Company of the target individual

Team Quokka, Software Engineer, Ad Hoc

### Product Manager (PM) name and email

Alayna Abel (alayna@adhocteam.us)

### Product Owner (PO) name and email

Peter Tebbenhoff (peter.tebbenhoff@va.gov)

### Desired AWS Access

Please copy permissions of Quokka member Christine Kies

### Access Expiration

July 2024

### E-QIP Transmittal Confirmation

![eqip](https://github.com/department-of-veterans-affairs/va.gov-team/assets/89038375/3b39453e-332f-48a5-afaf-eaf4972c55bc)

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by ben-allen-oddball** [comment]
User found in VFS Team Roster.

**Comment by ph-One** [comment]
@mheusgit  Access updated based on permissions of Christine Kies.

**Comment by jhouse-solvd** [comment]
@ph-One - Thanks, Kyle! As the inbound PM for this team (Team Quokka on Lighthouse), I can tell you that your support is much appreciated.

**Comment by mheusgit** [comment]
Have not been able to confirm access yet.  Team is reporting that in the past a message was provided in Slack by DevOps containing followup details

**Comment by mheusgit** [comment]
@ph-One Was a new account created or was a old one restored?  I didn't get followup information of how to use this new access

**Comment by jhouse-solvd** [comment]
Marc still needs support. Re-opening to ensure he gets the access needed. 

Cc: @ph-One

**Comment by mheusgit** [comment]
I was able to login to AWS DSVA both the console and command line.  This ticket can be closed now

**Comment by jhouse-solvd** [comment]
Closing per @mheusgit confirmation above. 

Thank you!
