### ISSUE TITLE
[BE] Don't report 401 exceptions from LoROTA to Sentry

### ISSUE THREAD

**Issue by randomsync** [department-of-veterans-affairs/va.gov-team#70746]
Currently, all 401 responses from LoROTA get logged as Exceptions in Sentry. This creates a lot of noise, as these errors are due to users entering invalid auth parameters and there isn't any reason to log these in to Sentry as errors: http://sentry.vfs.va.gov/organizations/vsp/issues/?environment=production&project=3&query=team%3Acheck-in&statsPeriod=24h

These errors are also reported in DataDog and result in a high error rate in patient_check_in and check_in services: https://vagov.ddog-gov.com/services?env=%2A&lens=Performance&page=1&sort=-fave%2C-requestRate&start=1701199371871&end=1701202971871

## Tasks
- Return the error to frontend but not Sentry

**Comment by kanchanasuriya** [comment]
Validated 401 Lorota exceptions are ignored in sentry by monitoring logged issues for the past 48 hours.

However, there are a few sets of 401 issues logged in sentry for endpoints `PatientCheckinsController#create` & `SessionsController#show` with the failure response from CHIP (like the one below) will continue to be logged and monitored as they are real failure messages.

`
Unmapped VA900 (Backend Response: { status: 401, message: Could not retrieve a token from LoROTA) }
`
