### ISSUE TITLE
update to documentation migration from vets.gov-team to va.gov-team repo

### ISSUE THREAD

**Issue by mengA6** [department-of-veterans-affairs/va.gov-team#70747]
### Description
This page has the following content under a "product"  heading:

> Please store your [VA.gov](http://va.gov/) Product documentation in the [va.gov-team repo product folders](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products). As of November 2019, we're in the process of copying select legacy documentation from the vets.gov-team repo to supplement va.gov-team; expect to see additional content and updates to links as this work continues through January 2020

Is there an update to the status of this documentation migration? Or do the dates just need to be updated? Or maybe that content about the migration should just be removed if it's no longer relevant.

### Relevant URLs
https://depo-platform-documentation.scrollhelp.site/getting-started/welcome

### Which type of team are you on? (Platform team, VFS team, or Leadership)
VFS

**Comment by mengA6** [comment]
…Or maybe that content about the migration should just be removed if it's no longer relevant

**Comment by johnny-jesensky-adhoc** [comment]
Hi @mengA6, good catch and thank you for flagging this! Our team will take a look and see what changes/edits are needed for this section. We'll provide further updates in this ticket.

**Comment by laucon** [comment]
@mengA6 We're gonna hunt down the person who can tell us how to edit this sentence. But I wanted to ask you, do you know who might know this information about this out-of-date sentence? If you don't, that's fine. We can try and find out who knows about it. But I wanted to ask you first. Thanks! And thanks for pointing this out. We really appreciate it. :)

**Comment by laucon** [comment]
@mengA6 We've researched and edited the document and we'll probably deploy the edit today at 3:30pm. Thank you for pointing this out. We really appreciate it. :)

**Comment by johnny-jesensky-adhoc** [comment]
Updates on this page are now live - moving this to _Done_. @mengA6  Thanks for the flag!

FYI @laucon
