### ISSUE TITLE
AWS access for Jaclyn Barrera

### ISSUE THREAD

**Issue by jaclyn-barrera** [department-of-veterans-affairs/va.gov-team#70742]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Jaclyn Barrera

### Your Email

jaclyn.barrera@thoughtworks.com

### Team, Role, and Company of the target individual

VES Developer Experience, Full Stack Engineer, Oddball/Thoughtworks

### Product Manager (PM) name and email

Danielle Baranowski - danielle.baranowski@oddball.io

### Product Owner (PO) name and email

Patrick Vinograd - patrick.vinograd@va.gov

### Desired AWS Access

EC2 Read for fwd-proxy, 
Read/Write for Secrets Manager Parameter Store for our deployments sensitive values. Similar to this https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-Stepstocreateanewsecretvalue:
Permissions needed to accomplish this https://github.com/department-of-veterans-affairs/devops/tree/master/terraform#making-changes on behalf of VES Developer Experience-

### Access Expiration

8-31-2025

### E-QIP Transmittal Confirmation

![Screenshot 2023-11-28 at 2 57 57 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/98929574/a7c99695-97a1-4e76-9aec-6a6f930806be)

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by ph-One** [comment]
Pending how testing goes with https://github.com/department-of-veterans-affairs/va.gov-team/issues/70743

**Comment by flooose** [comment]
Finished in the context of this [PR](https://github.com/department-of-veterans-affairs/devops/pull/13889/files)
