### ISSUE TITLE
Revision in drupal disability rates pages

### ISSUE THREAD

**Issue by AnneHurley** [department-of-veterans-affairs/va.gov-team#7074]
Disability rates tables pages need to be updated to 2020 rates in Drupal.
Those pages that need link to historic rates, need links to the past three years, PDFs ok, at bottom of pages. 

This page has been updated: 
https://www.va.gov/disability/compensation-rates/veteran-rates/
**The need for this page** is to get the historic version of the page, for 2019, and work with Howie to grab all info inside accordions to create a spreadsheet/pdf for 2019 historic rates. This will be a process we'll use going forward for every rates page.

These pages still need to be updated in Drupal, then redirected. 

**1. Special Monthly Compensation**
This page in Drupal with 2019 rates https://www.va.gov/disability/compensation-rates/special-monthly-compensation-rates/
Needs to be updated with rates from this page,
https://www.benefits.va.gov/COMPENSATION/resources_comp02.asp

**2. Special Benefit Allowance**
This page in Drupal with 2019 rates https://www.va.gov/disability/compensation-rates/special-benefit-allowance-rates/

Needs to be updated with rates from this page,
https://www.benefits.va.gov/compensation/special_Benefit_Allowances_2019.asp

**3. Birth Defects Allowance**
This page in Drupal with 2019 rates https://www.va.gov/disability/compensation-rates/birth-defect-rates/

Needs to be updated with rates from this page: 
https://www.benefits.va.gov/compensation/sb2019.asp

Related issues:
Update links **from** the following pages to the current special benefits rates tables:
1. Automobile modification benefits overview: https://www.va.gov/disability/eligibility/special-claims/automobile-allowance-adaptive-equipment/  -- currently links to 2017 rates: https://www.benefits.va.gov/COMPENSATION/special_Benefit_Allowances_2017.asp
2. Clothing allowance: https://www.va.gov/disability/eligibility/special-claims/clothing-allowance/ -- currently links to 2018 page: https://www.benefits.va.gov/COMPENSATION/special_Benefit_Allowances_2018.asp

To this page first 
https://www.benefits.va.gov/COMPENSATION/special_Benefit_Allowances_2019.asp

And then, when the below page is updated, to this page:

https://www.va.gov/disability/compensation-rates/special-benefit-allowance-rates/ 

NOTE: Medal of Honor rate doesn't have a separate page so that will be updated on the main special claims page in Drupal

## Acceptance Criteria
- [ ] All rates are updated and pages published

**Comment by AnneHurley** [comment]
@RLHecht  The special monthly compensation page in Drupal is ready for your eagle eye, including new math: https://prod.cms.va.gov/node/991/edit 

Note: One figure on the TeamSite page has an extra digit so have emailed Sandy Tadeo for the correct figure, which I'll input when I get it.

**Comment by AnneHurley** [comment]
Updated:
1. Special Monthly Compensation
This page in Drupal with 2019 rates https://www.va.gov/disability/compensation-rates/special-monthly-compensation-rates/
Needs to be updated with rates from this page,
https://www.benefits.va.gov/COMPENSATION/resources_comp02.asp

this is updated and ready to be pushed live. Will submit new redirect to @lunascoop

**Comment by AnneHurley** [comment]
**2. Special Benefit Allowance**
This page in Drupal with 2019 rates https://www.va.gov/disability/compensation-rates/special-benefit-allowance-rates/

Has been updated with rates from this page,
https://www.benefits.va.gov/compensation/special_Benefit_Allowances_2019.asp

This is updated and live. Will submit new redirect to @lunascoop

**Comment by AnneHurley** [comment]
Update links **from** the following pages to the current special benefits rates tables:
1. Automobile modification benefits overview: https://www.va.gov/disability/eligibility/special-claims/automobile-allowance-adaptive-equipment/  -- currently links to 2017 rates: https://www.benefits.va.gov/COMPENSATION/special_Benefit_Allowances_2017.asp
2. Clothing allowance: https://www.va.gov/disability/eligibility/special-claims/clothing-allowance/ -- currently links to 2018 page: https://www.benefits.va.gov/COMPENSATION/special_Benefit_Allowances_2018.asp

To this page first 
https://www.benefits.va.gov/COMPENSATION/special_Benefit_Allowances_2019.asp

And then, when the below page is updated, to this page:

https://www.va.gov/disability/compensation-rates/special-benefit-allowance-rates/ 

NOTE: Medal of Honor rate doesn't have a separate page so that will be updated on the main special claims page in Drupal

These pages and links are updated and live. Will create new redirect for @lunascoop

**Comment by AnneHurley** [comment]
Updated:
3. Birth Defects Allowance
This page in Drupal with 2019 rates https://www.va.gov/disability/compensation-rates/birth-defect-rates/

Has been updated with rates from this page:
https://www.benefits.va.gov/compensation/sb2019.asp

https://prod.cms.va.gov/node/993/edit

@RLHecht Ready for your review. Will add this to the redirect list for @lunascoop

**Comment by RLHecht** [comment]
@AnneHurley The birth defects allowance page has been reviewed and is now published.

**Comment by lunascoop** [comment]
@RLHecht @AnneHurley @MickinSahni I recommend that this ticket just capture a "Revise in drupal disability rates pages and the other ticket(s) (#7120 and #7202) capture the redirect efforts.

**Comment by AnneHurley** [comment]
@lunascoop  Sounds good

**Comment by RLHecht** [comment]
@AnneHurley and I checked the rates agains the legacy page for the Special Monthly Compensation page. Once we have one final number from Sandy it is ready to be published.

**Comment by MickinSahni** [comment]
2020-03-26 PW Standup
- they're all done, most are published. one page is waiting for stakeholder feedback and then that can be published (already reached out to stakeholder, Jen)
- Bringing into Sprint 18 (unplanned)
- @AnneHurley can you confirm the estimation on this item? wondering if 21 is a typo

**Comment by RLHecht** [comment]
@AnneHurley The final page is now published. Moving to validate and will close after tomorrow's deploy.  FYSA @MickinSahni

**Comment by MickinSahni** [comment]
> @RLHecht @AnneHurley @MickinSahni I recommend that this ticket just capture the "Revise in drupal disability rates pages" efforts and the other ticket(s) (#7120 and #7202) capture the redirect efforts.

👍 Updated

**Comment by MickinSahni** [comment]
2020-03-27 PW Standup
- SMC page ready to go live with next push (later today) and validated

**Comment by RLHecht** [comment]
Validated. Closing issue.
