### ISSUE TITLE
FE | Auth Menu | Remove Toggle and Clean Up the Code

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#70769]
## Background 
Now that we've launched the Auth Menu changes we need to remove the toggle we created for this work 

`show_authenticated_menu_enhancements`

## Acceptance criteria 
- [ ] toggle is removed and the code has been cleaned up and is continuing to work in production without issues (PM/PO to spot check)

**Comment by mtcA6** [comment]
@adamwhitlock1 do you need me to validate this in prod/staging? or is the PR stuck?

**Comment by adamwhitlock1** [comment]
The PR was merged today after some wrestling with CI/CD. It can be validated now.

**Comment by adamwhitlock1** [comment]
Validation is basically just checking that the menu links for dependents and letters still show up and everything works as expected. I have check in prod fore my account as well as staging for a couple test accounts.
