### ISSUE TITLE
Analytics Implementation for MHV on VA.gov landing page – va-alert rendered event

### ISSUE THREAD

**Issue by carlosfelix2** [department-of-veterans-affairs/va.gov-team#70772]
# Google Analytics Implementation or QA Request

### Required
- **Is this request for **Google Analytics implementation** or **QA**?**

     - [x] Google Analytics implementation
     - [ ] QA

- **Who is this request for?**
    - MHV on VA.gov landing page team
     
- **Provide the link(s) for Google Analytics implementation or QA**
    - /my-health
    
- **When is the launch date?**
    - Already launched

- **What interactions need to be tracked?**
    - Need to track when a user is shown content that states they are not registered with a health facility. 

### Optional
- **If applicable, what test users are needed?** 
    - No new test users needed. There are existing staging users that with the proper data to show the content.

- **Any additional comments**

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by michelle-dooley** [comment]
@carlosfelix2 - can you please send screen shots of what you are wanting to track. When I go in this is what I see and I am unclear on what content you are referring to? Is there a test user you can provide for me to walk through the flow?

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXNaQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6b8ef57bbd6796fe319e073004fb96d82faac916/image.png)

**Comment by carlosfelix2** [comment]
@michelle-dooley Here is the screenshot as requested. The content we want to track is that alert in the page.

![staging va gov_my-health](https://github.com/department-of-veterans-affairs/va.gov-team/assets/63804190/f34f467e-1175-47b0-bd9e-c9cd0895033e)

You can access this content by logging in to staging with the user `vets.gov.user+3@gmail.com` and visiting `/my-health'.

**Comment by michelle-dooley** [comment]
Thanks. We will review and get back to you with any further questions.

**Comment by wesrowe** [comment]
@michelle-dooley, can you share expectations around this request? In the months since we made the request, our alert portfolio has grown and more teams are adopting our component.

I'm also curious what your implementation might look like based on the request. I was imagining a new event, perhaps optional, added to `va-alert` upon rendering. (It currently only has an event on the CTA link inside.) Thank you.

**Comment by jestutt** [comment]
@wesrowe @johnny-jesensky-adhoc Is the new Analytics and Insights PM. 

I DM'd you on Slack -- Could you provide "more teams are adopting our component"? Curious since the only components I know are the design systems.

I remember talking to @carlosfelix2 about this but can't remember now if the event was to track that the alert loaded on the page or that it was actually appeared in the browser window. If you can remind me, I can send over what you need to implement for the datalayer push event.

**Comment by wesrowe** [comment]
Thanks for the info – hi @johnny-jesensky-adhoc! 👋 

"our component" – I meant our implementation of the design system alert, dealing with specific authenticated experience use cases. E.g., the one included in the screenshot above, and others like it. We're not creating competitors for va-alert!

As far as the implementation, I can't tell the difference between the two options you mentioned: 
> track that the alert loaded on the page or that it was actually appeared in the browser window

Maybe Carlos can answer that one.

**Comment by wesrowe** [comment]
@jestutt, I should mention a desired requirement for this analytics event that might not have been captured above. It would be very helpful for the "va-alert rendered" event to indicate which alert it is. Ideally this would be configurable for the implementing team by passing in a parameter. For example, we have a va-alert we call the "Verify your identity" alert, which alters some of its content based on which authentication service the user signed in with. We would want to be able to segment va-alert analytics based on the authentication method.

**Comment by jestutt** [comment]
@wesrowe @carlosfelix2 Here's a dataLayer event template for an alert box render/load that follows the component's click event template.

```
'event': 'nav-alert-box-load'
'action': 'load'
'alert-box-headline': //populate with the heading_1
'alert-box-status': //populate with the alert status, seems more like alert type - normally info, warning, continue
```

Wes, for the wish list item you've described, does it matter that the component link click event doesn't have a separate space to pass thru this information? The FE could easily add a 'alert-box-version' parameter that could define the authentication service versions in your example or for other versioning opportunities.

**Comment by wesrowe** [comment]
Thank you, @jestutt. I don't quite know what do you mean by "wish list item"... I believe the scheme/parameters you listed will work well for our "loaded" need. Regarding the link click event, it might be nice for that to include the link destination. I'm not sure what I would do with `alert-box-version`.

**Comment by jestutt** [comment]
@wesrowe [Your comment with a desired requirement](https://github.com/department-of-veterans-affairs/va.gov-team/issues/70772#issuecomment-2035596846) is what I referred to as a "wish list item". Sorry if that was confusing.

Also, it would be very nice if any of the Design System components with a link click event captured the link URL but don't at the moment. I believe that's something that's been identified for future updates. 

Note that if the existing tracking events on the components do not track how you need something tracked, you can turn off the tracking setting and add your own custom event in it's place. That way you have the accessibility and other benefits that comes from using the components but the tracking better aligns to your specific needs.

**Comment by radavis** [comment]
Hi, @jestutt! I'm working on implementing this ask. Does the following change to vets-website look right to you and your team? https://github.com/department-of-veterans-affairs/vets-website/pull/29505

**Comment by jestutt** [comment]
@wesrowe @radavis  Updated the Event Action in GTM for nav-alert-box-load:
<img width="873" alt="Screenshot 2024-05-02 at 4 08 38 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/141653184/5e8bfa16-24c5-46df-8573-3a9b4e0a4ac0">

The reason why the clicking on the links didn't fire an event is due to the `va-alert` component's analytics options being disabled -- see `disable-analytics=true` in the highlighted line on the right. 
![Screenshot 2024-05-02 at 4 00 19 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/141653184/cd17347c-c48c-42a0-ab83-0a4c6f93ab09)

cc @johnny-jesensky-adhoc

**Comment by radavis** [comment]
@jestutt Thanks for the info! I'll remove the `disable-analytics` prop on that instance of the `<va-alert>`. [staging.va.gov/my-health](staging.va.gov/my-health) is currently using a [`recordEvent()` call](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/mhv-landing-page/components/UnregisteredAlert.jsx#L9-L14) to add to the `window.dataLayer`.

I would like to add this functionality to all of the `<va-alert />` web components, and I have a PR up which I _think_ makes the necessary changes. If you have a moment, please take a look and leave some feedback: https://github.com/department-of-veterans-affairs/vets-website/pull/29505

**Comment by johnny-jesensky-adhoc** [comment]
Going to close this ticket out for the work needed from our team on this for sprint reporting purposes . Feel free to pass any additional questions to our vfs-analytics Slack channel, or in 'Office Hours' -- moving this to _Done_.

<img width="997" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/147662408/1635361c-89f8-4a8d-a9c2-84860f0b6cb5">


FYI @jestutt
