### ISSUE TITLE
Update links & rates on special benefits rates pages 

### ISSUE THREAD

**Issue by AnneHurley** [department-of-veterans-affairs/va.gov-team#7077]
Related issues:
Update links from the following pages to the current special benefits rates tables:
1. Automobile modification benefits overview: https://www.va.gov/disability/eligibility/special-claims/automobile-allowance-adaptive-equipment/ -- currently links to 2017 rates: https://www.benefits.va.gov/COMPENSATION/special_Benefit_Allowances_2017.asp
2. Clothing allowance: https://www.va.gov/disability/eligibility/special-claims/clothing-allowance/ -- currently links to 2018 page: https://www.benefits.va.gov/COMPENSATION/special_Benefit_Allowances_2018.asp

To this page first to update all quickly
https://www.benefits.va.gov/COMPENSATION/special_Benefit_Allowances_2019.asp

And then, when the below page is updated, to this page:

https://www.va.gov/disability/compensation-rates/special-benefit-allowance-rates/

## Acceptance Criteria
- [x] Update rates 
- [x] Update links where applicable

NOTE: Medal of Honor rate doesn't have a separate page so that will be updated on the main special claims page in Drupal

This is related to #7074

**Comment by AnneHurley** [comment]
@RLHecht  Automobile page with updated link ready for your review and publish:
https://prod.cms.va.gov/node/893/edit

**Comment by AnneHurley** [comment]
@peggygannon  and @mnorthuis  Question from last year - do either of you know why we decided to link from the Automobile benefit and Clothing allowance benefit to the legacy pages?

We have created a single page of these rates + Medal of Honor, and I'd think it would be better to just direct all users to this page, after I've updated it: https://www.va.gov/disability/compensation-rates/special-benefit-allowance-rates/

Will update correct legacy links for those two pages ^ till I hear from you.

**Comment by AnneHurley** [comment]
@RLHecht  2nd special rates page, clothing allowance, updated with new rate and updated link to correct legacy page, ready for your review.

https://prod.cms.va.gov/node/895/edit

**Comment by AnneHurley** [comment]
@RLHecht  The special allowances rates page is updated:
https://prod.cms.va.gov/node/990/edit

For your review and publish.

Welcome your thoughts too about whether we can avoid linking from automobile and clothing allowances info pages to the legacy page, and instead link to this updated page.

**Comment by RLHecht** [comment]
@AnneHurley , the automobile and clothing allowance pages have now been updated to link to our 2020 special allowance rates page. These pages are published. I also published your updates to the 2020 special allowance rates page. If there's nothing more on this ticket, should it be moved to validate?

**Comment by AnneHurley** [comment]
@RLHecht Yes, move to validate. Will send the updated rates page link to Sandy and Adrianne. thanks

**Comment by RLHecht** [comment]
Confirmed on live site. Closing ticket @MickinSahni @AnneHurley
