### ISSUE TITLE
Refactor SessionsController

### ISSUE THREAD

**Issue by rileyanderson** [department-of-veterans-affairs/va.gov-team#70799]
## Issue Description
The `SessionsController` was inherited and has become super bloated. The goal of this task is to identify and refactor this controller and related components to follow rails best practices.

## Backend tasks

- [ ] Identify and move parts that could be broken out into concerns
- [ ] Identify and fix parts that should be refactored to follow rails best practices
- [ ] Ensure that ssoe login still functions as expected

**Comment by parkerbees** [comment]
Moved to Jira. Closing.
