### ISSUE TITLE
[UX] Discuss Options for Displaying Check-in Status for Today's Appointments in the Appointments List

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#70796]
## Tasks
- Discuss Options for Displaying Check-in Status for Today's Appointments in the Appointments List

**Comment by brianseek** [comment]
@loripusey what are the details for this ticket?

**Comment by loripusey** [comment]
According to the Sketch files, it is to display the check-in status that we currently display in production. @benbrasso-agile6 chime in if this is incorrect.

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/86678742/4eb29e4b-8fbc-4e69-ae08-030c239a043a)

**Comment by benbrasso-agile6** [comment]
I mean it's correct, but I think we wanted to push that out of Priority 1 since we don't know if we can manipulate the data from the VAOS service. Right?

**Comment by benbrasso-agile6** [comment]
And if that winds up being true, we will want to talk about this together, e.g., what appts are we going to show under the To Do heading. I think I left a comment somewhere recently about only showing upcoming under the To Do heading. It requires more group thinking if Priority 1 doesn't include any manipulation of appts within the VAOS service appts.

**Comment by loripusey** [comment]
I don't think not knowing whether we can maniupulate the data is a reason to push it out. We currently have this feature in production. I would like to use this ticket to attempt to match up the appts from the 2 sources and see if we can add this information. My fear is that we will get sidelined with other projects and if we don't do it in Priority 1, I'm not sure we will make it back here.

**Comment by benbrasso-agile6** [comment]
Sounds good to me.

**Comment by benbrasso-agile6** [comment]
The different action links and statuses (this ticket) in the upcoming appts list page are located in priority 1 - https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec

**Comment by loripusey** [comment]
@wullaski let's talk about this at eng sync and possible create a spike ticket first

**Comment by benbrasso-agile6** [comment]
@loripusey what's the expectation for this ticket? (no rush) This to just set a meeting with engineers to discuss?

**Comment by loripusey** [comment]
Let's start there to figure out how we can move this feature forward to show the check-in status.

**Comment by benbrasso-agile6** [comment]
Should I set up a meeting with all FE engineers? Is that the next step? (Although, this is for our next sprint, not current one.)

**Comment by loripusey** [comment]
Sure

**Comment by benbrasso-agile6** [comment]
At our meeting, we decided that engineers will get further down the path of identifying if displaying statuses for MAP appts is problematic. And, we decided that if it does become problematic, UX has a direction on how to still utilize the appt list, but not include statuses. https://www.figma.com/file/QSEOAUVGrCqSb4qR21hgPI/Task-Card-Collection-%7C-Check-in?type=design&node-id=7-484&mode=design&t=ye9CnY9bkTahHhAY-0
