### ISSUE TITLE
Identity - Load testing solution

### ISSUE THREAD

**Issue by rileyanderson** [department-of-veterans-affairs/va.gov-team#70800]
## Issue Description
We need a solution to run load tests on our identity components. Research and choose  a way to accomplish this using resources we have access too. This should be something that is intuitive and only accessable by identity-team

## Backend tasks
- [ ] Research and identify a solution
- [ ] Implement solution (add more tasks here or create new ticket once solution has been identified)

**Comment by parkerbees** [comment]
Moved to Jira. Closing.
