### ISSUE TITLE
Prepare designs about Gross Monthly Income options for VBA

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#70838]
## Issue Description
As a Pension team,
**we need to prepare workflows and designs of different form flow options for the Gross Monthly Income section of the Pension form,**
so we can present this to VBA stakeholders and we can make a decision on how to design/build the form flow for this section.

Form flow options we've discussed as a team found here: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1697736525149/26590ab628618a5e2b86232397286eab8e7f8a1d?wid=0-1700517250175

## Acceptance Criteria
- We will have a "cleaned up" version of the user flows we've documented as Options 2 & 3, as shown on the Mural board linked above.
- We will have at least 1 higher-fidelity design of Options 2 & 3 available to frame our conversation with VBA stakeholders.

**Comment by aplatt-coforma** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/70838?planning-poker) with Zenhub @mayacoforma

**Comment by mayacoforma** [comment]
@vbellissimo @aplatt-coforma 
Kindly examine the Sketch file and provide comments if any revisions are required. Your feedback by early Monday would be appreciated, allowing sufficient time for updates before Tuesday's meeting.

Option 1:
Flow Diagram
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1luQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9907444c7f6bd8f797a16c0a90643fe96594257c/Option%201.png)

Prototype
https://sketch.com/s/94592459-f741-45a0-9432-efd685b9a1d5/a/kKRjaQA/play

Option 2:
Flow Diagram
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2duQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2295ddccf609ad9d88fd9207119f2dbbc3eb9b3e/Option%202.png)


Prototype
https://sketch.com/s/94592459-f741-45a0-9432-efd685b9a1d5/a/y9z1gQK/play

**Comment by vbellissimo** [comment]
Hi @mayacoforma thanks for sharing these.

I think for your Option 2, there still may need to be 1 more question that asks: `Who pays the income?`, so I think the order of the questions could be:

- What type of income? (radio button)
- - Social security
- - Interest/dividend
- - Civil service
- - Pension/retirement
- - Other (also add an open text field)
- Who receives this income? (short text field?)
- Who pays the income? (short text field)
- What is the monthly amount of income received? (number/dollar field)

Similar to the PDF fields:
![Screenshot 2023-12-01 at 2 11 57 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/106613300/cc1cd6cc-38b6-47bf-a924-dc7d76176ce8)

**Comment by vbellissimo** [comment]
Some thoughts on your Option 1:

I like the idea that if they max out 4 sources of Social Security Income, they see that warning to go to the other form.

If they have fewer than 4 sources of Social Security income, they should see the next question: Do you, your spouse, or your dependents receive income from other sources?
- Yes
- No

_If yes_, they would see a similar page to the one for Option 2 (as described in comment above)

Once they max out 4 sources of income (regardless of whether SS or other type, they see that warning again to go to the other form.
