### ISSUE TITLE
BE | Profile | Contact information | international postal code (Canada) numbers getting cut off on save 

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#70831]
## Background
When updating the mailing address for `vets.gov.user+226` on staging, I noticed that I'm able to enter, and seemingly save, the post code `L7E 2X5`, which according to google is the post code for Bolton (the city in the users profile).  However, when it goes back to the read mode, and I subsequently try to edit again, only the first 3 characters are saved. This happens if I enter it with or without spaces.

It seems like we should look into this to determine if something is wonky with the logic, or if we need to update the field label/hint text to make limitations more clear to people.  It's possible we don't need to do anything but figured we should check it out.

To reproduce:
1. Log into staging.va.gov/profile/contact-information with `vets.gov.user+226`
2. Click `edit` for the mailing address
3. Enter `L7E 2X5` into the `international post code` field at the bottom of the form
4. Hit save
5. Review the reflected information on the page above the `update saved` alert

> [!Note]
> This issue was not replicated when attempting this with an address from Santiago, Chile or from Amsterdam, Netherlands.

### Payload sent to VA Profile's Address Validation Service V2
Payload contains the full ZIP - see screenshot 

![image](https://github.com/user-attachments/assets/b8b666fe-7d2b-429b-9ed4-689c2e4a3e15)

### Response 
Response from the service only contains the first three characters of the zip code - see screenshot 

![image](https://github.com/user-attachments/assets/ac14a9a0-964c-4d4e-9040-8a44090fddcb)

## AC

- [ ] We've determined whether or not this is an issue we need to fix.

**Comment by adamwhitlock1** [comment]
This is a good question. I thought it would save a longer postal code, but maybe there is something wonky going on. I'll investigate

**Comment by andaleliz** [comment]
Thanks @adamwhitlock1! International post codes are a mystery to me. I [googled the zip codes for Bolton, Ontario](https://www.google.com/search?q=bolton+ontarios+post+code&sca_esv=586359844&rlz=1C5GCEM_en&ei=-5hnZYbUIL6mmtkPjaqV6As&ved=0ahUKEwjGvdCwgOqCAxU-kyYFHQ1VBb0Q4dUDCBA&uact=5&oq=bolton+ontarios+post+code&gs_lp=Egxnd3Mtd2l6LXNlcnAiGWJvbHRvbiBvbnRhcmlvcyBwb3N0IGNvZGUyBhAAGBYYHjILEAAYgAQYigUYhgMyCxAAGIAEGIoFGIYDSKc4UNUDWKo3cAl4AJABBZgBgQOgAaI0qgEJMC4xMS43LjEwuAEDyAEA-AEBqAIKwgILEAAYgAQYogQYsAPCAgsQABiJBRiiBBiwA8ICCxAuGIAEGIoFGJECwgIXEC4YgAQYigUYkQIYsQMYgwEYxwEY0QPCAgoQABiABBiKBRhDwgILEC4YgAQYxwEY0QPCAgUQABiABMICCxAAGIAEGLEDGIMBwgIaEC4YgAQYigUYkQIYlwUY3AQY3gQY4ATYAQHCAhEQLhiABBixAxiDARjHARjRA8ICDhAAGIAEGIoFGLEDGIMBwgIOEC4YgAQYigUYsQMYgwHCAhYQABgDGI8BGOUCGOoCGLQCGIwD2AECwgIIEAAYgAQYsQPCAgUQLhiABMICJhAuGIAEGIoFGJECGLEDGIMBGMcBGNEDGJcFGNwEGN4EGOAE2AEBwgINEC4YgAQYigUY5QQYQ8ICChAuGIAEGIoFGEPCAg4QLhiABBixAxjHARjRA8ICDhAuGIAEGIoFGJECGLEDwgIXEC4YgAQYigUYkQIYxwEYrwEYmAUYmgXCAg0QLhiABBiKBRixAxhDwgIIEC4YgAQYsQPCAgsQLhiABBixAxiDAcICCxAuGIAEGMcBGK8BwgIdEC4YgAQYigUYkQIYsQMYlwUY3AQY3gQY4ATYAQHCAhoQLhiABBiKBRiRAhixAxjHARivARiYBRiaBcICDRAuGLEDGIAEGIoFGEPCAhcQLhiABBiKBRixAxiDARjHARivARiYBcICKRAuGIAEGIoFGJECGLEDGMcBGK8BGJgFGJoFGJcFGNwEGN4EGOAE2AEBwgILEC4YrwEYxwEYgATCAg0QABiABBiKBRixAxhDwgIQEAAYgAQYigUYsQMYgwEYQ8ICEBAuGIAEGIoFGLEDGIMBGEPCAhQQLhiABBixAxiDARjHARivARiYBcICCxAAGIAEGIoFGLEDwgIQEC4YgwEYsQMYgAQYigUYQ8ICFBAuGIMBGK8BGMcBGLEDGIAEGJgFwgIZEC4YgAQYigUYQxiXBRjcBBjeBBjgBNgBAcICCBAuGLEDGIAEwgIXEC4YsQMYgAQYlwUY3AQY3gQY4ATYAQHCAg0QLhiABBgNGLEDGLEDwgIHEAAYgAQYDcICDRAuGIAEGA0YxwEYrwHCAhkQLhiABBgNGLEDGJcFGNwEGN4EGOAE2AEBwgIHEC4YgAQYDcICFhAuGIAEGA0YlwUY3AQY3gQY4ATYAQHCAg0QLhgNGK8BGMcBGIAEwgIIEAAYCBgeGA3CAgcQIRigARgKwgIIECEYFhgeGB3iAwQYASBBiAYBkAYEugYGCAEQARgUugYECAIYCg&sclient=gws-wiz-serp), and I see there is such a thing as a `forward sortation area`, which is all that's getting saved.  I have no idea if that's all that's needed, or if that applies to all countries, or what.  But maybe that google search will be helpful in some way 🤷‍♀️

**Comment by mtcA6** [comment]
Closign this out, this is a BE issue on the VA Profile side and they're going to work to correct this. The BE is returning an abbreviated zip code from the address validation service
