### ISSUE TITLE
[spike] DR | Investigate "File name too long" issue for evidence uploads

### ISSUE THREAD

**Issue by anniebtran** [department-of-veterans-affairs/va.gov-team#70856]
## What happened?

We were notified in our [error alerts Slack channel](https://dsva.slack.com/archives/C05UPRR0HK3/p1701231307812069) of [6 SC evidence submission errors](https://vagov.ddog-gov.com/logs?query=%40named_tags.class%3A%22DecisionReview%3A%3ASubmitUpload%22%20%40named_tags.jid%3A43dc9e34e547e415a3a84bb7%20&cols=host%2Cservice%2C%40named_tags.jid&index=%2A&messageDisplay=inline&refresh_mode=paused&stream_sort=desc&view=spans&viz=stream&from_ts=1701227760000&to_ts=1701231360000&live=false) (the original attempt + job retries) — it appears to have only affected 1 veteran.

The veteran had 1 successfully created `AppealSubmissionUpload` record for the evidence upload, however, the Lighthouse upload id on that record is `nil`. If we drill into the data further and look at the `decision_review_evidence_attachment.file_data`, it includes a _really_ long file name which is shown in [the Sentry log (if you scroll past the first error)](http://sentry.vfs.va.gov/organizations/vsp/issues/240332/?environment=production&project=3&query=user.id%3A%22eaf24270318b4faa8fbf09abff2bc2af%22&statsPeriod=24h). Looking up the `AppealsApi::EvidenceSubmission` records for this SC submission results in 6 records (the SubmitUpload job was tried 6 times in total) but for all of them, the `file_data` is `nil` and `status` is `expired`. You can reference Eugene's message in the DR engineer thread linked below for more details on what they found while exploring in the prod console

## What do we need to know?
We're hoping to figure out what next steps are for the veteran and what approach to take to handle this issue if it ever arises in the future.

## Action items

- [x] If possible, fix this issue for this individual Veteran
  - [ ] Talk to Jerek / Sam and see whether you can upload evidence to a already submitted SC via the CST. (If we can, then Kimberley can just ask Veteran to resubmit with shorter filename).
  - [ ] If we can't submit via CST, then reach out to Zach G, Steve A, and Bill C about prod console update of filename.
- [x] Plan for how to fix the problem going forward
  - [x] Create a ticket to cover development tasks

## Slack threads and background context
- Link to Slack [thread between the DR engineers](https://coforma.slack.com/archives/C05V2EGH493/p1701262793588309)

## Definition of done
- [x] Action items above are completed
- [x] Separate ticket for code work and designing the error message is added to the backlog

## Out of scope
- Coding solution

**Comment by data-doge** [comment]
Note for @data-doge: 
- Check in with @saderagsdale about how late SC evidence uploads are handled by VA.
- Pick up in next sprint (before holidays start).

**Comment by Mottie** [comment]
Started a [Slack conversation](https://dsva.slack.com/archives/CKUCFQAHJ/p1702403055217589). Lighthouse responded with:
> this is happening in your `DecisionReview::SubmitUpload` job. Let us know if you find a submission ID, but I don't think a request hit the Decision Reviews API.

**Comment by anniebtran** [comment]
With some help from Michel, we found that the error is coming from `put_supplemental_claim_upload` where we open a Tempfile:

```
content_tmpfile = Tempfile.new(file_upload.filename, encoding: file_upload.read.encoding)
```

which you can actually see in the 2nd stack trace on the Sentry log (under `Errno::ENAMETOOLONG`). So this is an error on the `vets-api` end, but we could try to enforce a filename character limit on the frontend to prevent it from happening in the future. We'd have to double check but I think the limit might be 255 characters — you should be able to test it locally in a Rails console

**Comment by saderagsdale** [comment]
@anniebtran I think that satisfies the spike portion of this, thank youuu!  

For the last task in the definition of done, wondering what the Veteran will see if we throw a FE error message? Want to ensure it's actionable. cc @eileen-coforma

**Comment by saderagsdale** [comment]
- @anniebtran to check if this SC is included in the sheet we sent to VBA
- @saderagsdale @anniebtran write ticket for the work

**Comment by anniebtran** [comment]
Confirmed that this user is included in the [spreadsheet that we sent to VBA](https://docs.google.com/spreadsheets/d/1vH04ksQufBWuV7zkIwSBd0ijZq8iCJOUNsIhm0f86hE/edit#gid=841601837) 👍

**Comment by saderagsdale** [comment]
@anniebtran I can see from [this thread](https://dsva.slack.com/archives/CKUCFQAHJ/p1702403055217589) that we determined it to be a backend issue. Can we make a ticket for the code work and close this one?

**Comment by saderagsdale** [comment]
@saderagsdale  making a note for myself to ask about this tomorrow in refinement so we can delete any dupe tickets.

**Comment by data-doge** [comment]
This spike is done. Followed up on [individual Veteran](https://github.com/department-of-veterans-affairs/va.gov-team/issues/70856#issuecomment-1894417296) and created follow-up [bug ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/75029). Closing.
