### ISSUE TITLE
Update Google Map API token to MO Studio account

### ISSUE THREAD

**Issue by mateoclarke** [department-of-veterans-affairs/va.gov-team#70858]
Currently, we're using the Google Cloud Console "Maps Javascript API" to render map tiles for the IPP public intake app. This ticket is to formally request we establish a MO Studio Google Cloud Console account so that devs can administrator app tokens and other services. _I don't want to be using my personal credit card by the time we're giving access to this app to private testers and other colleagues._

This is the page where I have a "Maps API Key" created: https://console.cloud.google.com/google/maps-apis/credentials?authuser=1&project=mo-ipp

![Screenshot 2023-11-29 at 8 16 29 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/5697474/e6bfed71-ab1a-4621-94ea-986d5b91b2c7)

Once we have a new API key, I can rotate the keys and update these files as needed:
- [ ] [ProofingMap component](https://github.com/mo-studio/VA-in-person-identity-proofing/blob/9825239abf9b433c3c1918594e901c7ab58a5a31/app/src/components/intake/ProofingMap.jsx#L6)
- [ ] [.env file](https://github.com/mo-studio/VA-in-person-identity-proofing/blob/9825239abf9b433c3c1918594e901c7ab58a5a31/app/.env.development#L8)

**Comment by rdvyas** [comment]
I have completed this request and updated to use MO resources for this service.

**Comment by mateoclarke** [comment]
New followup issue here:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/71427
