### ISSUE TITLE
[UX, FE] 10-10EZ: Update expenses questions flow and verbiage

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#70857]
As a Veteran, I would like a clear explanation of expenses for my dependents so that I know that information I need to enter.

- [x] Tweak plain language verbiage for Dependent expenses (by income earning dependent)
- [x] Design new flow for questions about Dependent expenses ([Reference Jessica's illustrations](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/p/CC64075A-E4A1-4BAD-A283-D3C75F4BEFF9/canvas))
- [x] Sync with approved EZR version (content and HEC approved plain language and flow)
- [x] Update design files in Figma
- [x] Build it
- [x] Test
- [x] Release to Prod
- [x] **Success: EZ verbiage and flow is updated to reflect the changes**

**Comment by jessicastump** [comment]
Good afternoon,

Thank you Alex for bringing this to our attention.  It has taken some time for us to review and research what the appropriate language should be for both forms.  We have received approval to move forward with the following language:

 

10-10EZ

Current: section IV-2G: EXPENSES PAID BY YOUR DEPENDENT CHILD FOR COLLEGE, VOCATIONAL REHABILITATION OR TRAINING (e.g., tuition, books, materials)
Suggested: EXPENSES PAID BY YOUR DEPENDENT CHILD WITH REPORTABLE INCOME FOR COLLEGE, VOCATIONAL REHABILITATION OR TRAINING (e.g., tuition, books, materials)
 

10-10EZR

Current: section IV-14: EXPENSES PAID BY YOU FOR YOUR DEPENDENT CHILD FOR COLLEGE, VOCATIONAL REHABILITATION OR TRAINING (e.g., tuition, books, materials)
Suggested: EXPENSES PAID BY YOUR DEPENDENT CHILD WITH REPORTABLE INCOME FOR COLLEGE, VOCATIONAL REHABILITATION OR TRAINING (e.g., tuition, books, materials)
 

Both forms - Definitions of terms used on this form: want to add

Reportable Income: The minimum amount of gross income required to file a Federal income tax return according to the Internal Revenue Code of 1954 Section 6012(a).

**Comment by jessicastump** [comment]
temporary [Sketch link of flow](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/a/Ee9739v) here... new Figma link and screens with content draft coming soon. 
cc @katelyncai

**Comment by jessicastump** [comment]
The [updated flow](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/a/Ee9739v) discussed during 1010 design sync 12/11.
"Reportable income" is addressed by draft version "Did/will your dependent file a federal tax return for the year 2022?" 
Other changes are flow/logic based

**Comment by jessicastump** [comment]
[Figma link can be found here](https://www.figma.com/file/UljiHam46o5DItC5iDgmPd/10-10EZ?type=design&node-id=0-12040&mode=design&t=iiQ14oMym9DsMYzV-0); status on the EZR side is the content review/updates are complete and this is being sent to HEC for an accuracy check for EZR MVP.

**Comment by jessicastump** [comment]
The [Figma link](https://www.figma.com/file/UljiHam46o5DItC5iDgmPd/10-10EZ?type=design&node-id=0-12040&mode=design&t=iODG0acXkIOKbQGu-0) has been updated to reflect the EZR/HEC approval version in the mobile screens.

**Comment by longmd** [comment]
@jessicastump , can you double check me on the content updates in staging? I think I have everything matching the Figma file. But want to make sure nothing changed in any additional info components or anything.

**Comment by jessicastump** [comment]
Thank you for flagging this for a double check @longmd!! Yes, it does match what is in the design files and I double checked it does match what is in the EZR design files and staging too, but.... I think we have a typo in both places :( Book should be plural "book**s**".
