### ISSUE TITLE
Adding Jonathan VanCourt to DSVA Slack

### ISSUE THREAD

**Issue by jvcAdHoc** [department-of-veterans-affairs/va.gov-team#70864]
# Description

Hi, I've been in the DSVA slack for a few months and was re-invited earlier this week as a multi-channel guest. This happened as part of the onboarding process for Lighthouse - I will be temporarily embedded on Lighthouse Dash, but remain on my original contract.

This kicked me out of all of the channels I was in and prevents me from rejoining them. Can I have my account permissions restored to their previous state?

I'm not sure what permission level I had before, but I could browse and join channels as well as others could invite me to channels without being an admin.

emaiil: jonathan.vancourt@adhocteam.us
position: Software Engineer III
team: Accredited Representation Management - Find a Representative
  * currently embedded on Lighthouse Dash

**Comment by dabaranowski** [comment]
In case it's needed for reference, original ticket to have John added to DSVA Slack was [17986](https://github.com/department-of-veterans-affairs/github-user-requests/issues/17986). He is still on that contract, and should still be a full member.

**Comment by LEHigley** [comment]
i'll readd as a full member. not sure who the right person to give this guidance to is, but if you're onboarding to a different team and already have slack access, please make sure they know that and do not request to invite you in a different way.
