### ISSUE TITLE
LHDI: Complete SDE Risk Survey and Threat Model Diagram

### ISSUE THREAD

**Issue by lmorris3** [department-of-veterans-affairs/va.gov-team#70878]
- [x] Application Security Assessors kick-off cal
- [x] Complete the Initial SD Elements (SDE) Risk Survey and Threat Model Diagram
- [x] Confirm a list of SDE countermeasures for your team to manage

Mural Link: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1684963245734/426a066d466aad4b985d0c6fdc1887ef18cd6a8d?sender=uea69eca39541ca1a0bea5755

**Comment by rdvyas** [comment]
Complete these steps:

https://laughing-adventure-wllepqe.pages.github.io/Getting-access/SD-Elements-risk-survey-and-threat-model/

**Comment by rdvyas** [comment]
Meeting with Application Security Assessor, Yarden Alfonso on Friday 1/19 to start the following task:

- SD Risk Survey
- Confirm list of SDE countermeasures

**Comment by lmorris3** [comment]
@rdvyas all steps are complete - is this finished and ready to close?

**Comment by rdvyas** [comment]
All steps are complete. We have established cadence with cATO team and we have an initial list of SDElements countermeasures.
