### ISSUE TITLE
Map current state of the VSO Journey (1/3)

### ISSUE THREAD

**Issue by RenataKeck** [department-of-veterans-affairs/va.gov-team#70874]
**Problem:**
Existing research does not clearly identify the journey for a VSO to become accredited and access the SEP system to support Veterans and their survivors. 

**Plan:**
Creating a high-level map of the current state will enable the entire ARF team to identify gaps and pain points that can be addressed in the MVP. 

**Output:**
- A rough mockup of the VSO journey (from accreditation to accessing the SEP system and when a Veteran contacts them) in [this mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1701101229797/15c7e1a5a9d426a998eb634408ff1dd3f4f9bdd1?sender=ua71936780d8bc9a2d2b29830).
- - Data should be pulled from prior research as well as any interviews with VSOs. This is a nice-to-have, not an essential artifact for this phase of work and should be _low fidelity_. 
- When completed, move ticket to Review and assign to another member of the Design Research team to review

**Resources:**
- [Current state 526EZ](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1668618955851/7e30bcfeea62d33f7bdc104cf3234e7a48804d2c?invited=true&sender=ua71936780d8bc9a2d2b29830) (Mural)
- [AR background research](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1695929155059/a302158eccec694ec7089bd6a02954421721987d?sender=ua71936780d8bc9a2d2b29830) (Mural)
- [VSO Journey: Compensation Claims](https://drive.google.com/file/d/1hmEVsuTzFk6fyYPSS70t0_7yuHV6fMx6/view)
- [Auto-establishment of 21-22a in VBMS is important for VSO's ability to serve Veterans](https://github.com/department-of-veterans-affairs/lighthouse-ux/blob/master/Benefits%20and%20Appeals%20Research/2022-05-Disability-Compensation-Claims-Discovery/2022-10-VSO-DisabilityCompClaims526EZ-Report.md) (GitHub)
- [SEP Walkthrough with DAV](https://dvagov.sharepoint.com/:v:/s/vaabdvro/Ee3gR_HqQ45CnY4OO5URNgYBJ-4haXSIx60F8Mmwz0MzPw?e=uJTLu9&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D) (Sharepoint)
- [VSO interviews](https://dvagov.sharepoint.com/sites/vaabdvro/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=QIRHZa&cid=866978cd%2D2497%2D496e%2Dadae%2D42c02258162e&FolderCTID=0x01200073ECFC0A16DB51439C06C6FDC0E92947&id=%2Fsites%2Fvaabdvro%2FShared%20Documents%2FAccredited%20Representative%20Facing%2FPast%20Research%2FRecordings&viewid=3fa7a9bb%2D3d4e%2D44c2%2Db93f%2D629268a08e72) (Sharepoint).
- [SEP Demo](https://dvagov.sharepoint.com/:v:/r/sites/vaabdvro/Shared%20Documents/Accredited%20Representative%20Facing/Research/SEP%20Demos/SEP%20Demo%20with%20CTO-20231208_111227-Meeting%20Recording.mp4?csf=1&web=1&e=a3abDH) (Sharepoint) with the VEO team behind the tool. Note that these are SMEs we will be interviewing ([Link to research plan in Google Doc](https://docs.google.com/document/d/1i7SGMj0ishpbNZ1tRYY_ZKZL_I9hHiQm6JXUnwT-oT4/edit)). 

**Acceptance criteria:**
- Output has been completed in Mural, reviewed, and free from errors
- Questions or unknowns in the VSO journey have been documented within the current state map

**Comment by hdbaines** [comment]
Will be assigned to @karafaithsanchez and should be pulled into next sprint after onboarding

**Comment by uxrebecca** [comment]
I was hoping to review this today but got caught up in other pressing things (listening session prep, SME interview summary). So I guess we should roll it? I can get to it tomorrow @RivkaCGates

**Comment by RivkaCGates** [comment]
okay - will do

**Comment by RenataKeck** [comment]
@karafaithsanchez comments have been added.
