### ISSUE TITLE
LHDI: SD Elements Survey - cATO

### ISSUE THREAD

**Issue by lmorris3** [department-of-veterans-affairs/va.gov-team#70877]
Work with cATO App Assessor who will support customers with cATO-related processes throughout the system's

SD Elements Survey
- [x] App Assessor should reach out and schedule meeting with customer for cATO
- [x] Establish Working Agreement with Application Security Assessors

Results
[ ] Establish lines of communication 
[ ] Establish Working Agreement with Application Security Assessors

Link to Mural: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1684963245734/426a066d466aad4b985d0c6fdc1887ef18cd6a8d?sender=uea69eca39541ca1a0bea5755

**Comment by rdvyas** [comment]
Application Assessor will reach out once the SecRel onboarding has been initiated.

**Comment by rdvyas** [comment]
Meeting is setup with cATO assessor Yarden Alfons for Friday 1/19 to begin security analysis steps of our application. This includes creating an SD Elements survey and establishing lines of communication.

**Comment by rdvyas** [comment]
Closing ticket as we have met with cATO Assessor and established a weekly meeting cadence.
