### ISSUE TITLE
Future state map of POA flow

### ISSUE THREAD

**Issue by RenataKeck** [department-of-veterans-affairs/va.gov-team#70875]
#### What’s the problem
As a team we must understand the flow that we are designing for, from a user (VSOfficer) perspective. 

#### What’s the solution or plan to address the problem

- **Detailed Plan**: This process flow will be a "best guess" for the steps that a VSOfficer would take when making a decision on a POA request. Using ARM’s future state flows as a jumping off point, _we will develop 2 sets of steps that begin where theirs left off (1- based on their MVP of paper only and 2- their stretch goal of the POA being submitted digitally)_ and end at the point where the VSOff now has access to the Veteran’s records. The information we will include, if applicable, is the VSOff’s actions, Veteran actions, physical/digital artifacts generated by these actions, and data sources (incoming and outgoing).

- **Expected Output:** The output will be a multi-step process flow documented in our Current / Future State [Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1701101229797/15c7e1a5a9d426a998eb634408ff1dd3f4f9bdd1?sender=ucd326fb05b27d09e40350092). 

- **Fidelity**: This will be the same level of fidelity (at the very least) similar to ARM's current vs future state flows [here](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1707330855297/0fda8fc4b9a433032e6ef600a44c37f526a52190?sender=ucd326fb05b27d09e40350092).

### Acceptance Criteria
- [x] Task flow should identify questions that need to be answered in forthcoming research as well as design opportunities for the prototype.
- [x] The artifact is created in Mural.
- [ ] Reviewed and signed off by design.
- [ ] Reviewed and signed off by Rivka.

**Comment by hdbaines** [comment]
Changing to an epic @RenataKeck and @uxrebecca to pair on it

**Comment by RenataKeck** [comment]
Epic created, this ticket now reflects first draft of the future state flow (to be followed by final artifact).

**Comment by RenataKeck** [comment]
@karafaithsanchez  when you have the time, please update the description for this ticket (sibling ticket to 72077, currently in New Issues).
