### ISSUE TITLE
[UX] 10-10EZR: Update expenses questions flow and verbiage

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#70873]
As a Veteran, I would like a clear explanation of expenses for my dependents so that I know that information I need to enter.

**AS Note: We can bring this into multiple stories, just wanted to jot this down before I forgot what we discussed.**

- [x] Tweak plain language verbiage for Dependent expenses (by income earning dependent)
- [x] Design new flow for questions about Dependent expenses ([Reference Jessica's illustrations](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/p/CC64075A-E4A1-4BAD-A283-D3C75F4BEFF9/canvas))
- [x] Migrate designs to Figma
- [x] Review with Aliyah
- [x] Review with HEC team
- [x] Once approved, update all source of truth documentations (Figma, github content, Mural userflow)
- [x] **Success: EZ verbiage and flow is updated to reflect the changes Shana sent us**
**AS Note: We'll have a separate story for EZ and for Spouse thing**

**Comment by jessicastump** [comment]
Email recap from email:

Good afternoon,

Thank you Alex for bringing this to our attention. It has taken some time for us to review and research what the appropriate language should be for both forms. We have received approval to move forward with the following language:

10-10EZ

Current: section IV-2G: EXPENSES PAID BY YOUR DEPENDENT CHILD FOR COLLEGE, VOCATIONAL REHABILITATION OR TRAINING (e.g., tuition, books, materials)
Suggested: EXPENSES PAID BY YOUR DEPENDENT CHILD WITH REPORTABLE INCOME FOR COLLEGE, VOCATIONAL REHABILITATION OR TRAINING (e.g., tuition, books, materials)

10-10EZR

Current: section IV-14: EXPENSES PAID BY YOU FOR YOUR DEPENDENT CHILD FOR COLLEGE, VOCATIONAL REHABILITATION OR TRAINING (e.g., tuition, books, materials)
Suggested: EXPENSES PAID BY YOUR DEPENDENT CHILD WITH REPORTABLE INCOME FOR COLLEGE, VOCATIONAL REHABILITATION OR TRAINING (e.g., tuition, books, materials)

Both forms - Definitions of terms used on this form: want to add

Reportable Income: The minimum amount of gross income required to file a Federal income tax return according to the Internal Revenue Code of 1954 Section 6012(a).

**Comment by jessicastump** [comment]
The sketch link to the draft flow is in comments above. @katelyncai  is working on the Figma move-over and the [link is here](https://www.figma.com/file/tggcJk382w9yQ0ElwKfh3N/10-10EZR?type=design&node-id=0-8373&mode=design&t=6SaqoM7ObzQmZgB0-0). 
Noting: We have not reviewed this yet with content (and/or HEC)

cc @mkerns1 and @alexseelig
