### ISSUE TITLE
[Discovery] Logged-in homepage: Stakeholder interviews — Schedule interviews

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#7088]
## Background

Epic #7085

We will be conducting stakeholder interviews for the logged-in homepage discovery per our [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/logged-in-homepage/2.0-redesign/discovery-and-research/research-needs.md#stakeholder-interviews). 

## Tasks

- [ ] Schedule interviews with stakeholders.

## Acceptance criteria

- [ ] Interviews with all required stakeholders are scheduled.

**Comment by Samara-Strauss** [comment]
@sshein

**Comment by andaleliz** [comment]
Reached out to all stakeholders - 7 of 15 scheduled.  Will wait to reach out to John Hashimoto until 4/10 as he is still onboarding to the team.

**Comment by andaleliz** [comment]
Reminder set to reach out to Jen Lee in 2 weeks for scheduling.  Have not heard back from Charles W so also setting a reminder to reach back out to him at that same time (both are deep in COVID work).  All other sessions scheduled.

**Comment by Samara-Strauss** [comment]
Great! All of that sounds good to me. Totally expected that some folks would be too busy with COVID work right now to talk. Otherwise, super excited we have all the other calls scheduled!

**Comment by andaleliz** [comment]
[Created another issue ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7644) to cover the interviews we know we can't schedule until end of next week. All other interviews scheduled.
