### ISSUE TITLE
RSpec Cleanup - Appointments

### ISSUE THREAD

**Issue by cferris32** [department-of-veterans-affairs/va.gov-team#70880]
Our vets-api test coverage has expanded a lot post-V2, so this work is to clean up and pair down any areas of the specs we deem fit while still retaining the same effective coverage. 

This ticket is to track the appointments service and request specs.

AC:
[ ] - cleanup opportunities (if any) are identified
[ ] - related PR for cleanup (if applicable)

**Comment by Bren22va** [comment]
Work is included in other initiatives, so redundant ticket.
