### ISSUE TITLE
RSpec Cleanup - MFS

### ISSUE THREAD

**Issue by cferris32** [department-of-veterans-affairs/va.gov-team#70881]
Our vets-api test coverage has expanded a lot post-V2, so this work is to clean up and pair down any areas of the specs we deem fit while still retaining the same effective coverage. 

This ticket is to track the MFS specs.

AC:
[X] - cleanup opportunities (if any) are identified
[X] - related PR for cleanup (if applicable)

**Comment by ajmagdub** [comment]
updated MFS RSpecs
