### ISSUE TITLE
Spike Java Error (gov.va.wss.partner.veteranrecord.ws.client.VeteranRecordWsClientException)

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#70912]
Research and possibly remediate backup path failure 
- gov.va.wss.partner.veteranrecord.ws.client.VeteranRecordWsClientException

[Datadog query](https://vagov.ddog-gov.com/logs?query=%40payload.error_message%3A%2Agov.va.wss.partner.veteranrecord.ws.client.VeteranRecordWsClientException%2A%20&cols=host%2Cservice%2C%40payload.error_message%2C%40payload.submission_id&context_event=AY2JIxEsAAB1aZOJsTXH6QAn&event=AgAAAY11-jFfGngSjgAAAAAAAAAYAAAAAEFZMTEtamdSQUFCYVlEbWh6MlNqZUFBRAAAACQAAAAAMDE4ZDc2MDctMzNiZi00NDNmLTkyNzItNzUyNjUxYzYyYjZj&index=%2A&messageDisplay=inline&refresh_mode=paused&storage=online_archives&stream_sort=time%2Cdesc&viz=&from_ts=1698811200000&to_ts=1707414600000&live=false)

## Acceptance Criteria
- [ ] Determine root cause of errors
- One of the following
  - [ ] New ticket created to fix issue
  - [ ] PR Opened to Fix issue
  - [ ] Comments on this ticket describing why it is not fixable at this time

**Comment by freeheeling** [comment]
```
{"messages"=>[{"key"=>"gov.va.wss.partner.veteranrecord.ws.client.VeteranRecordWsClientException", "severity"=>"FATAL", 
....
....
{"key"=>"form526.serviceInformation.reservesNationalGuardService.obligationTermOfServiceToDate.IsNotValid", "severity"=>"ERROR", "text"=>"Invalid value: 2008-04-XX"}]}
```
Possible duplicate error to invalid 'obligationTermOfServiceToDate' error.

**Comment by freeheeling** [comment]
[This event](https://vagov.ddog-gov.com/logs?query=%40payload.error_message%3A%2Agov.va.wss.partner.veteranrecord.ws.client.VeteranRecordWsClientException%2A%20&cols=host%2Cservice%2C%40payload.error_message%2C%40payload.submission_id&context_event=AY2JIxEsAAB1aZOJsTXH6QAn&index=%2A&messageDisplay=inline&refresh_mode=paused&sort=time&storage=online_archives&stream_sort=time%2Cdesc&view=spans&viz=&from_ts=1708066800000&to_ts=1708153140000&live=false), which is returned in the query for this investigated error, is peculiar as the `Form526Submission` record retrieved from the payload was last updated 12/17/21 and has no job statuses logs. The payload's `saved_claim_id` also does not match that on the `Form526Submission` record itself.

**Comment by freeheeling** [comment]
I inspected the job status logs of the 10 most recent instances of the `gov.va.wss.partner.veteranrecord.ws.client.VeteranRecordWsClientException` error message after searching `@payload.error_message:*gov.va.wss.partner.veteranrecord.ws.client.VeteranRecordWsClientException*` in Datadog. The error triggers the `retryable_error_handler`, and in 8 of the 10 cases the `SubmitForm526AllClaim` job eventually succeeded in as few as 1 or as many as 10 retries, with varying error messages being returned on subsequent retry attempts. Therefore, I don't think remediation is necessary for this particular error as it's likely the result of a temporary failure downstream and the job eventually succeeds.

The other 2 error events were for submissions that were last updated 12/17/21, neither of which had job status logs related to `SubmitForm526AllClaim` jobs, and payload `saved_claim_id` values that did not match the corresponding `Form526Submission` records. I'm not quite sure what to make of primary path errors logged for these dated submissions, but looking back a year there are a handful interspersed in the log records.
