### ISSUE TITLE
FIDO 1FA exploration

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#70922]
### Description of UX Tasks

Continue to explore how FIDO keys fit into VA's authentication experience

- [ ] Explore use cases where FIDO/FIDO2 makes the most sense for veterans, and where it won't be beneficial
- [ ] Follow up with LIG - how is passwordless sign in prioritize, metrics on MFA Fido usage
- [ ] Answer the questions
   - do we move forward with passwordless without CSPs? 
      - does that just mean another sign in method when we are trying to remove some?
      - What role can we play, if any, in encouraging CSPs to move forward with this?
      - how do we encourage veterans to use FIDO as a passwordless solution to increase security?
      -  Cognitive effort vs physical effort (when replacing PW) - is there a similar shift with MFA SMS to FIDO? Or is it just one physical for another?

#### Documentation
- [FIDO & FIDO2 and Passkeys.md](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Research/Secondary%20research/FIDO%20%26%20FIDO2%20and%20Passkeys.md)  - documentation from previous ticket
- [Fido Alliance Journey Map](https://fidoalliance.org/enterprise-journey-map/)
- [FIDO research](https://ieeexplore.ieee.org/abstract/document/9152694) which includes about user acceptance/willingness to use. 
   - Note: also the participants here were from a college campus, so it could be worth verifying with our veteran participants

#### Acceptance Criteria
- [ ] Reviewed by UX Team
- [ ] Reviewed by PMs
- [ ] Documentation has been updated
- [ ] Add finalized research to Github

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by parkerbees** [comment]
Closing, as this isn't on the roadmap for the near future. Can pull this out of Zenhub in future if needed.
