### ISSUE TITLE
Make SSOe-based login work with review instances

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/va.gov-team#7092]
Review instances are a developer facility that lets them see their work-in-progress code deployed to a private instance in the staging environment. Current non-SSOe sign-in works, but  requires some trickery to route the SAML callback to the correct instance instead of just staging-api.va.gov - there is a mechanism where the revproxy routes to the right instance using the RelayState parameter.

@omgitsbillryan has context on what additional steps were needed to make this work. 

We need to make this mechanism work for SSOe-enabled login. 
- Ensure that RelayState is preserved as expected during SSOe SAML round trip.
- Figure out if we can re-use the same IAM SAML app configuration that staging.va.gov uses, or if we need a second one with different metadata/entityID/etc. If we need a separate one, work with the IAM team to get that configured. Other than callback URL, I'd guess the configuration should be the same on their end.
- Update revproxy and review instance configuration as needed. (This item needs elaboration).

**Comment by patrickvinograd** [comment]
This ticket has context and helpful links about what was involved in getting the ID.me-based SAML flow working for review instances:

https://github.com/department-of-veterans-affairs/va.gov-team/issues/5090

**Comment by patrickvinograd** [comment]
I just sent an email to the IAM team requesting two additional consumer configurations in lower environments:

1. Move localhost config from SSOe PINT to INT (since PINT is unstable)
2. Add an additional configuration in SQA for review instances. 

Assuming they are on board with that, we can then do the same revproxy interception to route requests to individual review instances.

**Comment by ericbuckley** [comment]
I noticed on the review instances that [environment.BUILDTYPE](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/utilities/environment/index.js#L44) evaluates to "localhost", so we'll probably have to make some changes to make sure the correct keepalive endpoint is used if we want to use inbound on review instances.

**Comment by patrickvinograd** [comment]
Devops PR enables routing of the SAML callback to individual review instances using RelayState:
https://github.com/department-of-veterans-affairs/devops/pull/7271

IAM team is working on enabling this secondary configuration in SQA.

**Comment by patrickvinograd** [comment]
For now, we're not going to tackle inbound SSO for review instances. Two things would need to be resolved for that to work:
- Per Eric's above comment, the review instances evaluate as localhost environments so would attempt to use the mock keepalive endpoint.
- Even if we fix the above, CORS would likely be an issue as the origin for these instances is a "vetsgov-internal" domain and the SSOe servers are not going to allow cross-origin requests from that domain. 

Both can be fixed, but inbound isn't essential for review instances. If needed, the mock keepalive can be triggered via query parameters.

**Comment by patrickvinograd** [comment]
Eric also pointed out that the conditional linking to MHV is based on the buildtype, and will not point at the expected eauth.va.gov subdomain without additional work.

**Comment by patrickvinograd** [comment]
One additional PR needed but otherwise this is working in staging.

**Comment by patrickvinograd** [comment]
This is working in review instances. 

Feature flag still defaults to off, but see https://github.com/department-of-veterans-affairs/va.gov-team/issues/13449 for discussion of changing that default.
