### ISSUE TITLE
Regression test + implement redirects Lighthouse Legacy Forms Search (prod item, launch item)

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#7095]
## User Story or Problem Statement
Given the legacy VA Forms Search needs to persist
I want to ensure the new Find VA Forms implementation/redirects does not affect the Lighthouse forms process
so that form data continues to be made available. 

## Questions
-  What blockers exist on this ticket? What does this ticket block?

## Objectives or Key Results this is meant to further
- Objective 2 - Decrease time users spend waiting for an outcome

## Tasks
- [ ] Test the Lighthouse x Find VA Forms in local [or higher if possible]

## Acceptance Criteria
- [ ] Data scraped via the Lighthouse x Find VA Forms process continues to be saved

**Comment by MickinSahni** [comment]
Let's confirm that an approach hasn't already been developed for how we might handle this via: 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/4981

**Comment by kelsonic** [comment]
Are there any action items here for @ncksllvn or me? Not quite sure what this ticket's describing atm

**Comment by MickinSahni** [comment]
> Are there any action items here for @ncksllvn or me? Not quite sure what this ticket's describing atm

the intent of this ticket is to ensure our redirects from `/vaforms` to `/find-forms` doesn't affect the scraping process. that said, i found this ticket previously completed strategy ticket #4981. 

can we confirm whether we're good to go to implement redirects? this [last comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/4981#issuecomment-580924794) suggests we might have steps to complete

**Comment by ncksllvn** [comment]
Hm, so we talked about not redirecting the explicit `/vaforms/search_action.asp` path to use it for scraping, but that's the top Google result when I search "va forms", so I think we do need to include that :thinking:

**Comment by ncksllvn** [comment]
I implemented a dev-only redirect pattern back during https://github.com/department-of-veterans-affairs/va.gov-team/issues/5163 that seems to work. I pointed the vets-api script that scrapes `/vaforms/` at dev.va.gov/vaforms/ and it worked okay so I think we are set. I opened a PR for launching redirects into production here, https://github.com/department-of-veterans-affairs/devops/pull/6819.

**Comment by MickinSahni** [comment]
@stephorkandatx we could prob convert this ticket to "implement redirects in prod" or something and put it on-hold until we're ready to implement.

**Comment by stephorkandatx** [comment]
"blocked" until we enter launch

**Comment by stephorkandatx** [comment]
I did not intend for this one to be 'closed'. It is blocked, and will be able to move through once we are ready for redirects

**Comment by ncksllvn** [comment]
I think we can close this now @MickinSahni?

**Comment by MickinSahni** [comment]
> I think we can close this now @MickinSahni?

Closing as a "won't do" makes sense to me since this is captured in other places
