### ISSUE TITLE
[BE] [Request] Don't use "k" to represent thousand; can we use the actual number? 

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#70962]
## Description 

In the [Check In (Travel Claims) DD Dashboard](https://vagov.ddog-gov.com/dashboard/5pd-req-u6d/check-in-travel-claims?refresh_mode=paused&from_ts=1700110800000&to_ts=1701320340000&live=false), can we use the actual number instead of shortening it to "1k?" 
<br>
<img src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2NpQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cd785ce28bd681df2cce7412707d7d7897e425dc/Screenshot%202023-11-30%20at%204.54.17%E2%80%AFPM.png" width="260">

## Task

- [ ] Updated metric in dashboard 

## AC

- [ ] Metrics are updated

**Comment by loripusey** [comment]
I made the changes if you want to validate @benbrasso-agile6

**Comment by benbrasso-agile6** [comment]
TY LG
