### ISSUE TITLE
Implement Mobile-friendly Find VA Forms Search

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#7097]
## User Story or Problem Statement
Given we want Find VA Forms available on as many platforms as possible
I want to implement an iterated Find VA Forms Search design
so that it's available on mobile devices.

Note: Original designs found here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/6273#issuecomment-601890900

--- 
## Questions
- What happens if there are no results?
  - Implemented already!
     - <img src="https://user-images.githubusercontent.com/13204473/77570042-8a75fe00-6ea1-11ea-9483-b6eedd28e886.png" width="100px">
- What about service down? And malformed request? 
  - Don't need anything for malformed request
  - Service down - @MickinSahni open a separate one and get content from Jen 

---
## Tasks
- [ ] Implement mobile-friendly version of Find VA Forms search - [assignee]

## Acceptance Criteria
- [x] New iteration of Find VA Forms Search design is implemented
  - Not happening in this version: link to detail pages, online tool field, related to field

---
## Designs

**Notes:** 
- This is different from the iterated designs here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/6273. The designs here were reviewed by platform/accessibility and are to be used: https://github.com/department-of-veterans-affairs/va.gov-team/issues/6710
- Also, this iteration of design/implementation will not include: links to online tools, related to, form detail link 

### Large screen
<img src="https://user-images.githubusercontent.com/12564977/76319012-f3ac1d80-62b4-11ea-97dd-cbf808f8da30.png" width="250px">
### Small screen
<img src="https://user-images.githubusercontent.com/12564977/76319139-22c28f00-62b5-11ea-83a4-950f48e81b91.png" width="250px">

**Comment by MickinSahni** [comment]
Hi @jenstrickland, we're anticipating working on this in this coming sprint. 

Did you have any feedback on Ryan's designs? 

I saw [he tagged you](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6273#issuecomment-601890900) a few days ago but wasn't sure if there wasn't anything there that will require a major deviation on our part.

**Comment by jenstrickland** [comment]
Hi @MickinSahni, feedback was provided in the collaboration cycle checkpoint, https://github.com/department-of-veterans-affairs/va.gov-team/issues/6710, although Ryan added his designs to the ticket mentioned in your comment.

**Comment by MickinSahni** [comment]
> Hi @MickinSahni, feedback was provided in the collaboration cycle checkpoint, #6710, although Ryan added his designs to the ticket mentioned in your comment.

Hi Jen, we wanted to confirm that you've had a chance to review the new designs we're implementing as part of this ticket based on [Ryan's message](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6273#issuecomment-601890900).

**Comment by jenstrickland** [comment]
Yes, I reviewed all of Ryan's new designs in #6710.

**Comment by ncksllvn** [comment]
@rtwell It might not be a big deal, but this redesign does lose the sorting functionality that the current table-based design provides by clicking a column header.

**Comment by ncksllvn** [comment]
@jenstrickland Styling aside, what would recommend as the markup for each search result? 

![image](https://user-images.githubusercontent.com/1915775/77934475-232fc380-727e-11ea-9b75-73c71c92c3ee.png)

I'm thinking it's a good use case for a `<dl>` -

```html
<dl>
  <dt class="sr-only">Title</dt>
  <dd>{form.title}</dd>
  <dt>Revision date:<dt>
  <dd>{form.revisionDate</dd>
  <dt class="sr-only">Download link</dt>
  <dd>{form.downloadLink}</dd>
</dl>
```

Maybe that element should also be used for the form number in the left column?

**Comment by jenstrickland** [comment]
Thanks for checking! 

I provided comments earlier in the design process in this ticket-comment, https://github.com/department-of-veterans-affairs/va.gov-team/issues/6273#issuecomment-595416862.

Here's some adjustment to the description list markup. I recommend each item is an `<li>` as part of an `<ol>`. Preferably, the results could also be coded as a table using a responsive technique that retains `display: table` and the other display properties of a table. That way screen reader users may traverse the content in table mode. At least using the `<dl>` works to traverse in headings mode.

```html
<dl>
  <dt><dfn>Form#</dfn> <a href="#">Form Title</a></dt> 
      // if the > is not a background image, 
      // be sure to add aria-hidden="true" 
      // and role="presentation" to it
      // so screen readers don't say 'right angle bracket' constantly
  <dd><dfn>Revision date:</dfn> {form.revisionDate</dd>
  <dd><dfn>Related to:</dfn> {form.relatedData}</dd>
  <dd><a href="#" download="#">{form.downloadLink}</a></dd>
</dl>
```

Let me know if there are any questions!

**Comment by rtwell** [comment]
@ncksllvn  yep, we are aware. ultimately until we can fix the logic of the search itself, lots of this functionality is kinda lost or misleading.

**Comment by ncksllvn** [comment]
Hm, the images in this issue description show the form number in a left column, the images here show the form number inline with the form title - https://github.com/department-of-veterans-affairs/va.gov-team/issues/6710.

@rtwell which is correct? I've been working off of this issue alone.

**Comment by ncksllvn** [comment]
This will be live tomorrow 🎉

**Comment by jenstrickland** [comment]
When it's live, will it be behind a feature flag, so it can go through staging review?

**Comment by ncksllvn** [comment]
The [production page](https://www.va.gov/find-forms/) is behind authentication (using secret credentials, not ID.me), so staging review can really happen at any point. It's live, but not user-facing or launched publicly. But no, this isn't feature flagged.

**Comment by ncksllvn** [comment]
But it is on staging now if you want to check it out - https://staging.va.gov/find-forms

**Comment by jenstrickland** [comment]
Would you please ping me tomorrow regarding the secret credentials? ㊙️

**Comment by MickinSahni** [comment]
2020-04-01 PW Standup
- mobile designs on staging, getting feedback from jennifer

**Comment by jenstrickland** [comment]
For the section, "Top tasks for frequently downloaded VA forms":

Each of the info cards (File a VA disability claim, Apply for the GI Bill and…, Apply for VA health care…, has a link "Read more >". Each of these links should be distinguished individually. For example:

### Current code
```html
<a class="vads-u-display--block vads-u-padding-top--1 vads-u-text-decoration--none" href="/disability/file-disability-claim-form-21-526ez">
    <span>
        Read more
        <i class="fa fa-chevron-right vads-facility-hub-cta-arrow"></i>
    </span>
</a>
```

### Potential fix
```diff
    <span>
        Read more
+        <span class="sr-only">about disability claim form 21-526EZ</span>
        <i class="fa fa-chevron-right vads-facility-hub-cta-arrow"></i>
    </span>
</a>
```

**Comment by ncksllvn** [comment]
Thanks @jenstrickland, moving back to In Progress

**Comment by jenstrickland** [comment]
If it's okay, since this is an ad hoc review of work in progress, that will be the extent of my check for today. I need to get back to the spot check review for the AMA Phase 2 effort to try to help the team launch as y'all plan.

**Comment by jenstrickland** [comment]
For each of the download links, if it's possible to add the download attribute that would be helpful, as well.

**Comment by ncksllvn** [comment]
Latest improvements should be in staging

**Comment by MickinSahni** [comment]
2020-04-02 PW Standup
- Validated this in staging (screenshot below) 
- @jenstrickland we'd ideally open new tickets for any additional feedback. considering we have incorporated some accessibility feedback within this ticket, could you confirm there aren't any "MUSTs" remaining? 

![image](https://user-images.githubusercontent.com/13204473/78268403-24f3c400-74d6-11ea-8c8c-984e26c085b8.png)

**Comment by jenstrickland** [comment]
@ncksllvn @MickinSahni — just checked with an axe browser scan, and it looks good. 

When this goes through the [Full Accessibility and 508 Office Audit](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md#full-accessibility-and-508-office-audit) I'll do a more attentive scan.

**Comment by MickinSahni** [comment]
Sweet. Nice work, team @jenstrickland @ncksllvn @rtwell
