### ISSUE TITLE
[Blocked] Allow dismissible homepage banners in PROD

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#7098]
## User Story or Problem Statement
Given that we've received approval for users to dismiss banners in prod, 
I want to remove the associated feature flag that's preventing this functionality.

---
## Tasks
- [ ] Toggle feature flag in prod

## Acceptance Criteria
- [ ]  Users can dismiss va.gov banners in prod

## Reference

Functionality currently in staging:
<img src="https://user-images.githubusercontent.com/13204473/77276224-76a77d80-6c90-11ea-9c9c-a0c385319958.png" width="300px">

**Comment by brianalloyd** [comment]
Completed via different ticket and initiative. closing.
