### ISSUE TITLE
[Frontend] Form 40-10007 Modifications

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#7099]
VA Form 40-10007 https://www.va.gov/burials-and-memorials/pre-need/form-10007-apply-for-eligibility/applicant-information 

Add the following “burden” statement at the bottom of each application step page:
 

Respondent Burden: This information is collected in accordance with section 3507 of the Paperwork Reduction Act of 1995. Accordingly, we may not conduct or sponsor, and you are not required to respond to a collection of information unless it displays a valid OMB number. We anticipate the time expended by individuals who complete this form will average 20 minutes per response, including the time to review instructions, search existing data sources, gather the necessary data, and complete and review the collection of information. Your response is voluntary and not required to obtain or retain benefits to which you may be entitled. Send comments concerning the accuracy of this burden estimate, including suggestion for reducing this burden or any other aspect of this collection of information to the VA Clearance Officer (005R1B), 810 Vermont Avenue, NW, Washington, DC 20420. Please DO NOT send claims for, or correspondence regarding benefits to this address.

 

Change “Place of Birth” to “Place of Birth (City, State, or Territory)” on page two of the application.
 

Change “Gender (*Required)” to “Sex (* Required) (Information will be used for statistical purposes only)” 
 

Add a question for race/ethnicity (see attached question 8). 
 

Race/Ethnicity (*Required) (Select one or more) (Information will be used for statistical purposes only)” 

 

American Indian or Alaska Native

Black or African American

Hispanic or Latino

Native Hawaiian or Pacific Islander

White

**Comment by bradl3yC** [comment]
This is closed for now until we regroup on how to move forward with ethnicity changes
