### ISSUE TITLE
What should we call the FDG space?

### ISSUE THREAD

**Issue by steel36** [department-of-veterans-affairs/va.gov-team#70992]
## Purpose
We know from our [own internal standards](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2210660360/How+to+Service+Design+Your+Tool+Service#1.-Make-it-easy-to-find-your-service) that naming is very important and we have put work into [how to name surveys](https://vfs.atlassian.net/wiki/spaces/SDT/pages/2878537775/Guidance+How+to+name+surveys+for+Platform+research)

## Tasks
- [x] Consider name options
- [x] Discuss w/ team
- [x] Document choice
  
## Acceptance Criteria
- [x] choice documented

**Comment by twoangstroms** [comment]
Tagging @mjknight50

**Comment by steel36** [comment]
Adding this here so that the work is linked: https://vfs.atlassian.net/wiki/spaces/SDT/pages/3033104426/Naming+the+FDG+space+on+the+Platform+Site
