### ISSUE TITLE
(TEST) [Consistency] User encounters design components that are inconsistent or confusing.

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#71007]
_Need help?_ [_How to read staging review tickets_](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Anatomy-of-a-Staging-Review-Issue-ticket.2060320997.html)

## Product Information
**Team:** Test VFS Team
**Product:** Test Product
**Feature:** Test Feature

## Findings details
**VA.gov Experience Standard - issue:** User encounters design components that are inconsistent or confusing.
**VA.gov Experience Standard - category:** Consistency
**Launch-blocking:** No
**Collab Cycle Reviewer:** @allison0034 (Design)

### Description

On Step 1, the address block left border is 7px and is not using the component in Storybook. The address block left border should be 3px.

## Recommended action

Use the [address block component](https://design.va.gov/storybook/?path=/docs/components-address-block--default-story) in Storybook.

## References

- **WCAG Success Criteria:** N/A
- **Modality:** N/A
- **Design System Component:** [Address block ](https://design.va.gov/components/address-block)
- **Design System Pattern:** N/A
- **Content Style Guide:** N/A
- **Context:** N/A
- **Accessibility Defect Severity:** N/A

---

### Next Steps for the VFS Team

- Close the ticket when the issue has been resolved or validated by your Product Owner
- If your team has additional questions or needs Platform help validating the issue, please comment on the ticket
- Some feedback provided may be out of scope for your iteration of the product, however, Platform's OCTO leadership has stated that all identified issues need to be documented and it is still your responsibility to resolve the issue.
- If you do not believe that this Staging Review issue ticket is the responsibility of your team, comment below providing an explanation and who you believe is responsible. Please tag the Point of Contact/Reviewers. Governance team will research and will follow up.

**Comment by it-harrison** [comment]
@erinrwhite should this issue be closed and labels removed?

**Comment by erinrwhite** [comment]
@it-harrison thank you!! closing
