### ISSUE TITLE
Disability | Implement Unique Lighthouse API Key

### ISSUE THREAD

**Issue by tblackwe** [department-of-veterans-affairs/va.gov-team#71022]
Dependents, Disability, and SimpleForms currently use the same API key for document submission, creating a tracking issue within the Lighthouse team. They have asked us to implement unique keys per form

Acceptance Criteria:
 - [ ] Staging env Key assigned by Lighthouse Team
 - [ ] Prod env Key assigned by Lighthouse Team
 - [ ] Key added to AWS for lower tiers
 - [ ] Key added to AWS for production
 - [ ] Keys updated in devops repo Settings definition
 - [ ] Disability Specific API key passed to Benefits Intake Service

**Comment by sortizsh** [comment]
Lighthouse told us not to proceed with this. Each ATO must have their own key and they do not want a single ATO having keys
