### ISSUE TITLE
Shared button group refactor 

### ISSUE THREAD

**Issue by amponce** [department-of-veterans-affairs/va.gov-team#71026]
## Issue Description
Due to increased usage of the shared button group and some custom logic that was introduced to support various lengths of text a cleanup of the shared component is needed in order to reduce complexity

## Front end tasks
- Ensure the page is styled according to design spec. 
- Ensure the back end data from API is displayed in local and review instance
- Ensure unit tests are available. 
- Ensure your code changes are covered by E2E tests
- Run axe checks using the Chrome or Firefox browser plugin
- Test for color contrast and color blindness issues
- Zoom layouts to 400% at 1280px width
- Test with 1 or 2 screen readers
- Navigate using the keyboard only

## Acceptance Criteria
- [ ] Designer comments on this issue to approve page styling 
- [ ] Unit tests pass
- [ ] E2E tests cover current code and regression
- [ ] End-to-end tests show 0 violations.
- [ ] The data returned matches API response (for given user or scenario)
- [ ] All axe checks pass
- [ ] All color contrast checks pass
- [ ] All zoom testing passes
- [ ] All keyboard checks pass 
- [ ] All screenreader checks pass

**Comment by HeatherRienks** [comment]
Per SP, need to discuss as a FE team; not a quick fix. Moving to backlog; will focus on transition page work.

**Comment by amponce** [comment]
PR that has fallen behind https://github.com/department-of-veterans-affairs/vets-website/pull/26955
