### ISSUE TITLE
Covid-19 Redirect Requests

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#7104]
## Acceptance Criteria
- [ ] Redirects are implemented and validated as outlined in the table below

---
### Requestor team info
Public Websites

### Implementation date
Canonical urls are already live at: 
- https://va.gov/coronavirus
- https://va.gov/coronavirus-veteran-frequently-asked-questions/

Please indicate when the redirect(s) needs to be implemented"
- [ ] **On the same date the new URLs launch**
- [ ] **Can happen within 1-5 business days after new URLs launch**
- [x] **Other - Please indicate timing :** as soon as vetting is complete

#### Redirects for existing FAQ page
URL  |  Redirect Destination (new URL)
---  |  ---
`/coronavirus-veteran-faq/` | `/coronavirus-veteran-frequently-asked-questions/`
`/coronavirus-veteran-faqs/` | `/coronavirus-veteran-frequently-asked-questions/`
`/veteran-coronavirus-faq/` |  `/coronavirus-veteran-frequently-asked-questions/`
`/veteran-coronavirus-faqs/` |  `/coronavirus-veteran-frequently-asked-questions/`
`/veteran-faq-coronavirus/` |  `/coronavirus-veteran-frequently-asked-questions/`
`/veteran-faqs-coronavirus/` |  `/coronavirus-veteran-frequently-asked-questions/`
`/coronavirus-faq-veteran/` |  `/coronavirus-veteran-frequently-asked-questions/`
`/coronavirus-faqs-veteran/` |  `/coronavirus-veteran-frequently-asked-questions/`

#### Redirects for existing VA Public Health Coronavirus page
URL  |  Redirect Destination (new URL)
---  |  ---
`/covid/` | `https://www.publichealth.va.gov/n-coronavirus`
`/covid-19/` | `https://www.publichealth.va.gov/n-coronavirus`

---

### Open Questions
- Q: What's the best approach to handle special characters in any of the variations above i.e. if there are missing or alternative characters are inadvertently used?
  - A: @mnorthuis  

---
### Definition of done
- [x] Above information is provided and issue is tagged and assigned appropriately - *@ requesting team*
- [x] All appropriate VA stakeholders are notified of pending redirect - *@ requesting team*
- [x] Redirect request is vetted and documented and implementation plan is clear - *@ Content & IA team*
- [x] Request is assigned to appropriate team for implementation - *@ Content & IA team*
- [ ] Implementation team completes work - *@ Implementation team*
- [ ] Implementation pushed live and redirect is validated in production - *@ all*
- [ ] Ticket is closed - *@ requesting team*

**Comment by mnorthuis** [comment]
I added a couple more to round out the plural "faqs" scenario and 1 to represent "covid-19".  These are good to go.

**Comment by MickinSahni** [comment]
Thanks, @mnorthuis. 
Couple follow-up questions:
- What's the best approach to handle special characters in any of the variations above i.e. if somebody omits a `-` or alternative characters are inadvertently used?
- Do we need wildcard variations to account for anything people might place before/after the `/` in a given url e.g. `/coronavirus-veteran-faq/update` or `/covid-19/questions`?

**Comment by mnorthuis** [comment]
@MickinSahni If we want to make sure we capture all of those variations, then we need them here.  If we are unsure, we should set up some analytics to watch for variations that create 404s coming in and we can add more to this list if something becomes recurring...we can't possibly capture all variations though. 

For the terms added after the trailing slash, work with Nick and Kelson to make sure our redirects are greedy and capture anything after it.  We should be good on those though...

**Comment by MickinSahni** [comment]
> @MickinSahni If we want to make sure we capture all of those variations, then we need them here. If we are unsure, we should set up some analytics to watch for variations that create 404s coming in and we can add more to this list if something becomes recurring...we can't possibly capture all variations though.

This is related to the special characters, right?

> For the terms added after the trailing slash, work with Nick and Kelson to make sure our redirects are greedy and capture anything after it. We should be good on those though...

Gotcha 👍

**Comment by mnorthuis** [comment]
@MickinSahni Yes, that comment is regarding the special characters and/or misspellings.

**Comment by MickinSahni** [comment]
Thanks for vetting, @mnorthuis. Moving this over to Public Websites board for implementation. cc @jenniferlee-dsva

**Comment by ncksllvn** [comment]
@mnorthuis I'm looking at the `Redirects for existing VA Public Health Coronavirus page` section. Those are calling for a redirect to `/coronavirus` which also redirects. Is that correct?

**Comment by mnorthuis** [comment]
@ncksllvn So sorry, didn't catch that one.  I have updated above with the actual final landing page so we don't have multiple jumps.  Thank you for catching!

**Comment by kelsonic** [comment]
PR merged @mnorthuis! 🎉

**Comment by MickinSahni** [comment]
Validated the above url tables as well as a couple wildcard tests:
- `http://va.gov/veteran-coronavirus-faqs/adfsdf`
- `http://va.gov/covid/va/test/`

**Comment by jenniferlee-dsva** [comment]
Hello - Is this already live? I just tried a live test with `va.gov/faq-coronavirus-veteran` ,  and it did not redirect to the canonical page https://www.va.gov/coronavirus-veteran-frequently-asked-questions/

**Comment by jenniferlee-dsva** [comment]
Oh - I see Mikki's comment above. If we want to track for additional variations from list above, I'm fine with that. It was just random that I tested with a version that wasn't on the list!

**Comment by MickinSahni** [comment]
PR to address greedy redirects for `/covid/*`
https://github.com/department-of-veterans-affairs/devops/pull/6561
