### ISSUE TITLE
[DUPLICATE] Discovery: Replacing standard layout with representative specific layout

### ISSUE THREAD

**Issue by emily-gullo** [department-of-veterans-affairs/va.gov-team#71055]
- [ ] Speak with designers on whether we desire this design
- [ ] Speak with Platform Team if the above desired design requires clarity

Hard product constraint from [product vision document](https://dsva.slack.com/files/U04R9D4EWA2/F064QKE15HS/representative-facing_tools_-_product_vision-2.pdf):

> **Representative-facing tools should remain in the VA.gov technical ecosystem, but appear to users as a separate product**
> 
> Lighthouse research shows that representatives, especially those who are also Veterans, are sometimes confused by [logging in to VA.gov for representative tasks](https://github.com/department-of-veterans-affairs/lighthouse-ux/tree/master/Develo[…]0OAuth%20and%20Connected%20Apps%20Research%20Report_with%20VSOs). VA should create a distinct front door for representative-facing tools, potentially by creating a new VA.gov subdomain with a separate login page. Representative.va.gov, rep.va.gov, or a more brandedsounding alternative are both potentially viable options (Vso.va.gov, while more succinct, seems to exclude attorney and agent users). Under the hood, however, representative-facing tools should leverage the infrastructure, processes, and systems created for VA.gov.

**Comment by nihil2501** [comment]
pre-refinement note: Should this describe some deliverable? If it is documentation, what kind of documentation would we like this to be? Is discussion in this issue sufficient?

**Comment by nihil2501** [comment]
This is captured in https://app.zenhub.com/workspaces/accredited-representative-facing-team-65453a97a9cc36069a2ad1d6/issues/gh/department-of-veterans-affairs/va.gov-team/71682
