### ISSUE TITLE
Spike standalone application

### ISSUE THREAD

**Issue by emily-gullo** [department-of-veterans-affairs/va.gov-team#71056]
- Spike empty standalone application in `vets-website`
    - `/rep` path with [existing new application strategy](https://depo-platform-documentation.scrollhelp.site/developer-docs/creating-a-new-application#Creatinganewapplication-Manualsetup) rather than subdomain
        - note: Subdomain research
            - [Zenhub link](https://app.zenhub.com/workspaces/accredited-representative-facing-team-65453a97a9cc36069a2ad1d6/issues/gh/department-of-veterans-affairs/va.gov-team/71050)
            - #71050

**Comment by nihil2501** [comment]
note from refinement: precisely enumerate deliverable e.g. `navigate to staging.gov.va/rep and see hello world`

**Comment by nihil2501** [comment]
[Draft PR](https://github.com/department-of-veterans-affairs/vets-website/pull/27019) cc @emily-gullo

**Comment by nihil2501** [comment]
Tentatively assigning this to myself because I did some work on this, although that was done in advance of the normal ticketing lifecycle.

**Comment by nihil2501** [comment]
@emily-gullo Let me know if you need help running this locally. During development, I removed the "logged in" oriented component so I could see a "hello world" kind of component that I temporarily added and just verify that my development workflow was effective.
