### ISSUE TITLE
Explore quantitative data about sign in - ROLL

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#71051]
### Description of UX Tasks
Use Google Analytics, Data Dog to uncover insights and identify areas for further qualitative analysis to improve sign-in for Veterans. Pull data and visualize in order to add persuasion and validity to our storytelling around issues.

This is fairly open ended at this point. Look at the data and see what comes about

#### Product notes
Nothing specific we're looking for from a product perspective, just looking for trends

#### Acceptance Criteria
- [ ] Reviewed by UX Team
- [ ] Reviewed by PMs
- [ ] Documentation has been updated
- [ ] Add finalized research to Github

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by parkerbees** [comment]
Per conversation with Clayton: when the big E2E research was reviewed, there wasn't a look into DD/GA, so there is still value in this; would need to be further refined before working

**Comment by parkerbees** [comment]
Moved to Jira for Sprint 3. Closed.
