### ISSUE TITLE
Account for use case: registered but no MHV account (incl. 403 error)

### ISSUE THREAD

**Issue by radavis** [department-of-veterans-affairs/va.gov-team#71057]
## User story

As a Cartographers team member, I want to make sure that users with a facility registration but no MHV account have no unnecessary API calls that would result in console errors, to reduce noise and make errors that actually impact user experience easier to notice.

As a user with a facility registration but no MHV account, I would like if possible to not have a confusing experience if I click a tool link on the MHV landing page, so that I'm not confused.

### Notes
- See slack messages for context and recommendation from Patrick:
  - [Slack message](https://dsva.slack.com/archives/C0581MN69TJ/p1701462629688059)...
  - And this [slack message](https://dsva.slack.com/archives/C0581MN69TJ/p1701463021687639)

<details><summary>Details of UX (not part of this ticket)</summary>

- Both are for a subtle use case I don't think we've really looked at: a user who: (1) has a medical record at a facility; and (2) does not have an MHV account. Today we are showing them the full landing page with tool links. However, if/when they click through to an MHV National Portal tool, they will be asked to register for an MHV account – that UX where they are dropped without explanation into a very long form.
- The potentially-confusing experience (getting sent to the MHV account creation form without explanation) is a temporary situation. Once the account creation API is launched, MHV accounts will be created in the background before the user has a confusing experience. ETA on that: Spring 2024.
  - We still need to figure out if these 403 errors will persist beyond the launch of the account-creation API (in mid-2024)
- Consider the case for Oracle-only users – should there be a different experience for them?
  - Sara/IA rec: don't ever link Oracle-only users to MHV NP
</details>

Possible tasks:
- [ ] Ticketed any next steps, including a more robust framework for API call management if appropriate
- [ ] If appropriate, ticketed design of a temporary UX patch to inform this user type about tool usage

## Acceptance Criteria
- User with a facility registration but no MHV account doesn't generate 403 errors (simple approach)

**Comment by wesrowe** [comment]
refinement notes:
- left as both dev & ux for now, may need to split
- do we need to log anything to datadog? probably not

**Comment by jzucadi** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/28115/checks?check_run_id=22061290215
