### ISSUE TITLE
Yellow Ribbon Desktop Tweaks

### ISSUE THREAD

**Issue by kelsonic** [department-of-veterans-affairs/va.gov-team#7105]
# Description

There are a few items that need tweaking on `/education/yellow-ribbon-participating-schools` to be pixel-perfect on desktop devices.

## Acceptance criteria
- [x] Shrink first paragraph width to reflect the [design](https://vsateams.invisionapp.com/share/P4W04QPWHTK#/screens/405236342).
- [x] Update `<h1 />` on search results page to `Yellow Ribbon school search results`.
- [x] Lowercase the `W` in `School Website` label on the YRP cards.
- [x] Change `Unknown` to `Not provided` on the YRP cards.

**Comment by MickinSahni** [comment]
2020-03-23 PW Standup
- Ready to be validated as soon as it's deployed [this afternoon]
