### ISSUE TITLE
20-10206 - Remove the Suffix from name pattern

### ISSUE THREAD

**Issue by rachelshearerux** [department-of-veterans-affairs/va.gov-team#71062]
In step 2 of 20-10206, remove "Suffix" from the Your name and date of birth step. The PDF doesn't ask for it, and we wouldn't have anywhere to map if a user selected an option. 

Definition of Done
- [x] Remove Suffix from name pattern
- [x] Confirmed in staging

Support Documentation
screenshot of mockup:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBellvQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4a22c25650af4149b35a067f6c94a3f696773d8f/Screenshot%202023-12-01%20at%205.52.29%E2%80%AFPM.png)

**Comment by jeana-adhoc** [comment]
Confirmed in staging!
