### ISSUE TITLE
Yellow Ribbon mobile responsiveness

### ISSUE THREAD

**Issue by kelsonic** [department-of-veterans-affairs/va.gov-team#7106]
# Description

The [new Yellow Ribbon pages](https://va.gov/education/yellow-ribbon-participating-schools/) does not currently match the [design spec](https://vsateams.invisionapp.com/share/36W0CAZHJ2U#/screens/405289291) on mobile.

Staging is here:  https://staging.va.gov/education/yellow-ribbon-participating-schools/

## Acceptance Criteria
- [ ] Match the [design spec](https://vsateams.invisionapp.com/share/36W0CAZHJ2U#/screens/405289290) for all new Yellow Ribbon program pages.

**Comment by kelsonic** [comment]
Design has updated again. Need to complete new design before implementing mobile responsive spec. CC @MickinSahni

**Comment by MickinSahni** [comment]
2020-04-03 PW Standup
- Pulled this into Sprint 18

**Comment by MickinSahni** [comment]
2020-04-06 PW Standup
- working on this

**Comment by MickinSahni** [comment]
Validated in staging!
