### ISSUE TITLE
20-10206: Add validation for A-number

### ISSUE THREAD

**Issue by rachelshearerux** [department-of-veterans-affairs/va.gov-team#71065]
In step 3 of 20-10206, users who have self-identified as non U.S. citizens have the option to provide an A-number or a VA file number. To prevent downstream automation errors, we need to help users understand what's required of them and validate the response. 

We need to ensure that A-numbers are 8 or 9 digit characters and users don't include any characters (commonly the A-number begins with an A). 

Just like SSN and VA file number, we will not require an A-number if they provide a VA file number. 

**Documentation**
- [Source of truth](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/20-10206%20FOIA%20PA%20Request/source-of-truth.md#12-of-14---additional-information)
- [Sketch](https://sketch.com/s/314e6dbf-5b4a-422d-beb1-0ad599fc3af1)

Definition of done
- [ ] Add help text to A-number that reads: Only numbers are allowed. If your A-number is "A12345678," enter "12345678"
- [ ] Add error validation if a user includes a non-numerical character: Enter a valid 8 or 9 digit A-number (only numbers are allowed)
- [ ] Confirm in staging

Screenshot from sketch:
<img width="934" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlVvQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aee787979ce22afdc3e298090751830c7ee89fb6/Screenshot%202023-12-01%20at%207.03.36%E2%80%AFPM.png" alt="Screenshot 2023-12-01 at 7.03.36 PM.png" />

**Comment by rachelshearerux** [comment]
It's possible that some folks may have A-numbers that are fewer than 8 characters. To reduce cognitive load on the user here, it would be helpful to the user to accept shorter strings and pad the beginning of the string with zeros when we map to the PDF. 

cc @tbaker1026 @Thrillberg

**Comment by tbaker1026** [comment]
<img width="812" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjFIQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--953dcfcac4eaa3f495a1929344da7ca9e21906d7/2023-12-08_15-11-51.png" alt="2023-12-08_15-11-51.png" />

<img width="766" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjVIQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--39991f47d105fdd3ebf9c214d042987d3189c0c6/2023-12-08_15-12-29.png" alt="2023-12-08_15-12-29.png" />
