### ISSUE TITLE
20-10206: Update mailing address pattern to match design

### ISSUE THREAD

**Issue by rachelshearerux** [department-of-veterans-affairs/va.gov-team#71064]
In step 5 of 20-10206, where a user provides their contact information, the street address should 
 
Documentation
- [Source of truth](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/20-10206%20FOIA%20PA%20Request/source-of-truth.md#12-of-14---additional-information)
- [Sketch](https://sketch.com/s/314e6dbf-5b4a-422d-beb1-0ad599fc3af1)

Definition of done
- [x] Update the field label for Street 2 to "Apartment or unit number"
- [x] Remove Street 3
- [ ] Confirm in staging

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGdvQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cd3cf9208a3e56bacf11eb916150110670423bcb/Screenshot%202023-12-01%20at%206.20.45%E2%80%AFPM.png)

**Comment by jeana-adhoc** [comment]
Confirmed in staging
