### ISSUE TITLE
Full Accessibility & 508 Office Audit: STEM updates to the Education Benefits Wizard & Form  22-1995

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#7107]
## Steps to complete the Full Accessibility & 508 Audit: 
- [x] Product Manager: create issue and fill in feature name in the title and other bolded information appropriately
- [ ] Practice area reviewers create sub-issues attached to this one with feedback for your team on *feature name*
- [ ] **Requesting team** completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)
- [ ] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

### Access information for the tool or feature in staging 
Education Benefits Wizard: https://www.va.gov/education/how-to-apply/
Form 22-1995: https://www.va.gov/education/apply-for-education-benefits/application/1995

### Education Benefits Wizard Test Plan:
- STEM Wizard Accessibility Test - TestRail.pdf

### Form 22-1995 Test Plan: 
- [1995 STEM Form Accessibility Test - TestRail (1).pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/4370386/1995.STEM.Form.Accessibility.Test.-.TestRail.1.pdf)

## Additional Notes
As part of this review, VSP will send your product to VA's 508 office for approval (as applicable)

**Comment by 1Copenut** [comment]
@desireeturner I've completed the full audit with assistive devices based on your test plan and our previous testing during the staging review. The STEM update has been sent to the VA 508 office for their quick test. I'll move this issue to the Review/QA swimlane until I hear back from the VA.

Thank you for providing the test plan and clear instructions. It made the effort go very smoothly.

**Comment by 1Copenut** [comment]
@desireeturner The VA 508 office got back to me on this item. No issues so I'll move it to closed. Thank you!
