### ISSUE TITLE
21-4142: Add date stamp to upper right for resubmit

### ISSUE THREAD

**Issue by Thrillberg** [department-of-veterans-affairs/va.gov-team#71085]
<img width="1226" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFVzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dcf4faa6c800f261b066599ff384894a3cda317b/image.png" alt="image.png" />

This is what is looks like on the 526
<img width="1196" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFlzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--305829abaef64c346e163ece543fd71b0fc6473e/image.png" alt="image.png" />

**Comment by tbaker1026** [comment]
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL281QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--49304dbdf9657712318c653b5bdbc06d770b5a95/2023-12-06_07-56-14.png" alt="2023-12-06_07-56-14.png" />

@Thrillberg I think we can close this one.
