### ISSUE TITLE
System design: BTSSS vets-api component diagram

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#71089]
## Description
It is becoming more likely that the user-facing features of BTSSS will exist across multiple applications on VA.gov. We need to design the backend so that frontend integration with vets-api is easy to discover, resilient, and practical

## User Story
As a frontend engineer, I would like to be able to easily discover and integrate with the BTSSS controller(s) so that I can quickly and safely develop feature for Veterans.

## Acceptance Criteria
- A [component diagram]() that shows the high level system design of the BTSSS product backend on vets-api

## Definition of Done
- All acceptance criteria are met
- Documentation shared on Github

**Comment by kjduensing** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/beneficiary-travel/engineering/component_vagov_travel_pay.png

**Comment by kjduensing** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/beneficiary-travel/engineering/component_vagov_travel_pay_integrated.png

**Comment by hinzed1127** [comment]
These look good. I'll just document a couple of follow-up comments/questions discussed in standup.

On the integrated approach diagram:
- Rewording "hypothetical example controller" to be more explicit that it represents "0 to N" more controllers with travel pay integrations

On the dedicated approach diagram:
- Rewording Travel Pay Service to be more explicit about it being a centralized place that other controllers (appointments, claims status, etc) would make any necessary calls to
- Similarly, in the assumed components box, highlighting the fact that – if I'm understanding things correctly – that adapter/component for appointments would be utilized by both the appointments controller and our travel pay service, much like how we'd expect other controllers to call our travel pay service


In general, though, the diagrams make sense, and I lean towards the dedicated approach, with the hope that that it keeps the travel pay logic more modular and self-contained.
