### ISSUE TITLE
[Reps][21-22] Usability test - Research planning

### ISSUE THREAD

**Issue by RenataKeck** [department-of-veterans-affairs/va.gov-team#71091]
The Accredited Representation Management team will be doing user testing on the 21-22 flow with unauthenticated users, specifically attorneys and claims agents. 

### Plan 
Because user research with these users is relevant to ARF research for the SEP replacement, ARF Design/Research has been asked to support this study by drafting the research plan and assisting with recruitment, moderation and notetaking. 

Note that ARF will be responsible for recruitment for this study. Recruitment should be built out as part of overall [participant management plan](https://app.zenhub.com/workspaces/accredited-representative-facing-team-65453a97a9cc36069a2ad1d6/issues/gh/department-of-veterans-affairs/va.gov-team/72064). 

### Output
- [x] Draft usability test research plan, created in Google Docs and uploaded to GitHub
- [x] Move to review and tag assign to Rebecca
- [x] ARM review completed, move to DONE and tag Rivka for final review
- [x] After Rivka review, notify Janelle in ARM OCTO Slack channel.

### Timing
1/8 send Unauth user test to team for review
1/16 submit Unauth user test to research review
1/22 Unauth recruitment begins
1/29 - 2/9 Unauth interviews

### Resources
- [Canvas view](https://www.sketch.com/s/a75e9329-dae9-4984-867e-451d6e2fa836/p/34CE53F2-4035-4059-92F5-17A79EA6B344/canvas)
- [Desktop view](https://www.sketch.com/s/a75e9329-dae9-4984-867e-451d6e2fa836/prototype/D69D63F0-5499-463F-B09E-782973BC590D/a/D69D63F0-5499-463F-B09E-782973BC590D)
- [Mobile view](https://www.sketch.com/s/a75e9329-dae9-4984-867e-451d6e2fa836/prototype/F73AB584-E113-4572-8AFA-7761671C7752/a/F73AB584-E113-4572-8AFA-7761671C7752)
- [Authorized user research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/research/2024-01-ARM-appointarep-usertest/research-plan.md)
- [Authorized user conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/research/2024-01-ARM-appointarep-usertest/conversation-guide.md)
- [VA Platform research checklist](https://depo-platform-documentation.scrollhelp.site/research-design/research-checklist#Researchchecklist-Writingyourresearchplan)
- [VA Platform conversation guide guidance](https://depo-platform-documentation.scrollhelp.site/research-design/research-checklist#Researchchecklist-Writingyourconversationguide)

### Acceptance criteria
- Output checklist completed
- All portions of the research plan template have been completed, are edited for clarity, conform to the [goals of the research study](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/research/2024-01-ARM-appointarep-usertest/research-plan.md), and the [research checklist](https://depo-platform-documentation.scrollhelp.site/research-design/research-checklist#Researchchecklist-Writingyourresearchplan). 
- All research planning documentation has been uploaded to the correct folder on GitHub (link forthcoming).

**Comment by RenataKeck** [comment]
Update to timeline:
1/8 Draft unauth user test to ARM team for review
1/16 Update documentation based on ARM feedback
1/18 Submit for collaboration cycle research review
1/22 Collaboration cycle research review done, update to reflect feedback
1/23 - 1/30 Start recruitment
1/25 Complete pilot session
2/7 - 2/16 Conduct interviews
2/19 - 3/01 Analysis and reporting
3/04 Final presentation

**Comment by RenataKeck** [comment]
Link to the research plan is [here](https://docs.google.com/document/d/1q3aYyF3xM8EO9XVQ8YT0Yrk7MjM7jfp7DZfXZmnQ25M/edit?usp=sharing). @uxrebecca ready for your review. 

Will confirm where on GitHub to upload the draft once it's been reviewed. For the time being, assume it should stay in Google Docs until ARM team has provided feedback.

**Comment by uxrebecca** [comment]
I completed my review and made a few comments @RenataKeck
