### ISSUE TITLE
[Reps][21-22] Usability test - Schedule test sessions

### ISSUE THREAD

**Issue by RenataKeck** [department-of-veterans-affairs/va.gov-team#71094]
This is a placeholder ticket for everyone moderating as part of the ARM user testing study. The person assigned to this ticket is responsible for ensuring that all sessions with users are scheduled and tracked in the session tracker.

### Output
- [ ] Contact and confirm session signups (send Zoom invite to research team + ARF calendar)
- [ ] Create temporary channel in OCTO Slack for research study
- [ ] Create and manage a Canvas in OCTO Slack for notetaker/observer signups
- [ ] Create and complete test session status tracker
- [ ] Move to DONE when all interviews have been scheduled

### Resources
- [Research Plan](link)
- [Test session status tracker](link)
- [Recruitment plan](link)
- [Participant panel](link)

### Acceptance criteria
- Interviews are all scheduled
- Status tracker doc has been filled out completely

**Comment by karafaithsanchez** [comment]
We didn't end up doing this work in partnership with ARM. If there is assistance needed from us in the future, we will create a new ticket. Closing for now.
