### ISSUE TITLE
Search results don't update if criteria is updated on results page

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#7109]
## What happened?
Search results don't update after country is updated on results page and another search is conducted.

School website links should be lowercase for readability.

## Specs:
- Device: Macbook
- Browser: Chrome
- Test User _(if applicable)_: n/a

## Steps to Reproduce
1. Visit https://staging.va.gov/education/yellow-ribbon-participating-schools
2. Select United States
3. Select Colorado
4. Search
5. Select - Select - for country
6. Search
7. Observe that only schools in CO still appear, expected behavior is all schools appear

## Acceptance Criteria
- [x] If the `country` field is changed, the `state` and `city` fields should be cleared.
- [x] School website links should be lowercase for readability.

## Note: 
- this is separate from the "duplicate" cards issue. do we differentiate by program id? 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by MickinSahni** [comment]
2020-03-26 PW Standup
- PR merged, validated. Closing
