### ISSUE TITLE
Update form section flow to match design: Your contact information

### ISSUE THREAD

**Issue by rachelshearerux** [department-of-veterans-affairs/va.gov-team#71090]
Based on Finding 2 from the Minimal Form Header Usability test, users expected the stepper component to reflect incremental progress on each new page-load. 

In VA Form 20-10206, the form will include 9 base steps, with an additional 5 pages where users enter additional information if they select certain record types: 

1: Requester information
2. Your name and date of birth
3. Your identification information
4. Your mailing address
5. Your contact information
6. Records
7 (conditional). Disability exam details
8 (conditional). Financial record details
9 (conditional). Life insurance benefit details
10 (conditional). Compensation and/or pension details
11 (conditional). Benefit record details
12. Additional information
13. VA regional office
14. Review

**Documentation:**
- [Source of truth](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/20-10206%20FOIA%20PA%20Request/source-of-truth.md) 
- [Sketch](https://www.sketch.com/s/314e6dbf-5b4a-422d-beb1-0ad599fc3af1) 
- [Minimal Form Header research findings: Finding 2](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/research/2023-09-form-header-usability-testing/research-findings.md#finding-2-users-are-confused-by-the-relationship-between-a-section-and-a-given-page:~:text=Finding%202.%20Users%20are%20confused%20by%20the%20relationship%20between%20a%20section%20and%20a%20given%20page.)

**Definition of done:**
- [x] Update the step indicator so that the phone # and email address page shows a unique label of "Your contact information" and is followed by step 6, "Records"
- [x] Ensure that the review page shows a dedicated accordion for "Your contact information"
- [x] Confirm in staging

**Comment by jeana-adhoc** [comment]
Confirmed in staging

<img width="677" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3RIQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1ea7914840c695f098046eb8e8f3e49d479ba705/image.png" alt="image.png" />
