### ISSUE TITLE
[MVP] Update, finalize designs for Step 5 "gross monthly income"

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#71098]
## Issue Description
As a Pension team,
**we need to update the designs found in Step 5 of the online form pertaining to "Gross Monthly Income",**
so that they encompass any fields pertaining to Section 9 [of the PDF form](https://www.vba.va.gov/pubs/forms/VBA-21P-527EZ-ARE.pdf),
so that they ensure the best user experience,
and so that they match decisions made with OCTO and VBA

---
## Tasks
- [ ] Update the "Gross Monthly Income" subsection of Step 5 on the online form, so that they follow decisions made in partnership with OCTO-DE and VBA stakeholders; This will use "Approach 3" discussed with OCTO and VBA on Dec 5.
- [ ] Update [Step 5 in Sketch](https://www.sketch.com/s/94592459-f741-45a0-9432-efd685b9a1d5/p/6571319D-6329-4249-B0A7-E39DA9DA31F4/canvas#Comment) to include the changes done for Gross Monthly Income.

## Acceptance Criteria
- We will have completed updating the pending designs for Step 5 of the online Pension form to handoff to product and engineering. The subsection in particular is: Gross Monthly Income

**Comment by mayacoforma** [comment]
Note from meeting with Vicky: we can book-end this task unless there is feedback from the Stakeholders tomorrow.
