### ISSUE TITLE
[RevProxy,GHA] OpenResty Update Testing in Staging

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#71107]
## Description
Anytime we rebuild OpenResty we need to test it.  This needs to be automated through Github Actions

## Notes
- We need parity with what we have setup today 

## Acceptance Criteria
- [ ] OpenResty is verified by GitHub actions anytime they are updated

**Comment by npeterson54** [comment]
moving into the next sprint due to the PII issue that came up and took resources
