### ISSUE TITLE
[RevProxy,GHA] VA Certificate Testing in Staging

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#71110]
## Description
Anytime we rebuild the VA cert image we need to test it.  This needs to be automated through Github Actions

## Notes
- We may have to update our script that pulls down all the VA certs  
- We need parity with what we have setup today 

## Acceptance Criteria
- [ ] VA certs are verified by GitHub actions anytime they are updated

**Comment by stoiven** [comment]
https://github.com/department-of-veterans-affairs/vsp-platform-va-certs repo
