### ISSUE TITLE
[Tier 3]: User Claims Issue

### ISSUE THREAD

**Issue by Kimberley2019** [department-of-veterans-affairs/va.gov-team#7113]
**Issue Description:** User is experiencing issues when attempting to submit and/or view claims.  Keeps getting error message, which are included in the descriptions below.  Images were unable to be viewed.

**Priority:** Medium

**Total Number of Issues:** 1

**Issue Number and User Description:**02526097
Case Notes

Veteran states that he is having an issue with VA.gov not having everything to do with his disability claim. Veteran states that he tried to submit a second form to combine his claims, but he is unable to get the claim to submit. Veteran states that when he clicks the "submit" button he gets an error that the system is unable to submit the claim, to check his internet connection, and to contact the NCC if the problem persists. Veteran stated that he spoke with the NCC multiple times, that the referred him to eBenefits, who referred him to DEERS, who referred him back to eBenefits, who referred him to ID.me. Veteran states that nobody is willing to "own the problem" and help to correct it. Veteran needs the problem with his VA.gov/eBenefits account fixed so that his claims can be properly submitted and combined.

 
Device used is Samsung Galaxy Note 9 (so Android).

Account is Va.Gov with Id.Me

Same result below on all browsers.

URL: 
https://www.va.gov/disability/file-disability-claim-form-21-526ez/review-and-submit

**Comment by AZSchneider** [comment]
@Kimberley2019 I can reach out to the veteran and set up a call. What's the best way to get the veteran's contact info?

**Comment by Kimberley2019** [comment]
Let me get that information for you.  Hold please.

**Comment by Mottie** [comment]
When we meet with this user, can we try to get them to use a desktop or laptop instead of an android or iOS device? It'll make it easier to troubleshoot

**Comment by Kimberley2019** [comment]
This ticket has been resolved.  The Veteran sent in a very nice message about the assistance he received from the team.
Way to go team!
