### ISSUE TITLE
Analytics KPI dashboard request for IVC Team

### ISSUE THREAD

**Issue by rachaelpenfil** [department-of-veterans-affairs/va.gov-team#71131]
# Request a New Standardized KPI Dashboard

## What this form is for

Use this ticket template to request a new standardized KPI dashboard on Domo for your product. To make updates to a product already on a standardized dashboard, please use the [Request an Update to your Standardized KPI Dashboard template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=michelle-dooley&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&template=analytics-request-update-kpi-dashboard.md&title=Analytics+KPI+dashboard+update+request+for+%5BTeam%5D).

Standardized dashboards are currently available for Forms, Content, & Search products only. To see if you should request a standardized dashboard, check [Should I request a standardized KPI dashboard](https://docs.google.com/presentation/d/16mRcslbkWtW44rlsfQGXZnHtQ3GoLjn6GpFnd3Gvva8/edit#slide=id.p). If you’re not sure which dashboard(s) your product(s) qualify for, check the [Eligibility Dashboard](https://va-gov.domo.com/page/1550814739).

If your VA.gov product is not eligible for a standardized dashboard, you may be able to request an “edge case” dashboard. Please reach out to the Platform Analytics & Insights team on #vfs-platform-support for more information on this process.

### Expected delivery timelines

The Analytics team will notify you once this ticket has been pulled into a sprint. 

## Instructions for the VFS team
In order to pull the correct data for your product, we need your help to define what pages and events to include, in addition to basic product info. We’ll need a filled out [KPI request template](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit#gid=981224988) before we can pull this ticket into our sprint.

*NOTE: If you do not have Google access, you can download an Excel version of the template [here](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/1586823275/KPI%20Dashboard%20Product%20Details%20Template%20-%20MAKE%20A%20COPY.xlsx?inst-v=ced1f4dd-e997-4aa2-9ae8-2cebe369b42f).*

- [x] Make a copy of the [Google Sheet](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit#gid=981224988) [(or download Excel version)](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/1586823275/KPI%20Dashboard%20Product%20Details%20Template%20-%20MAKE%20A%20COPY.xlsx?inst-v=ced1f4dd-e997-4aa2-9ae8-2cebe369b42f)
- [x] Complete worksheet as instructed
- [x] Link your completed spreadsheet here: [Form 10-10D as of December 4, 2023] (https://docs.google.com/spreadsheets/d/1rHeOC0KjCAWOdAzTOaRUkYdR5FxCaCXRvlai6bsAjaQ/edit#gid=0)
- [x] Check your sharing settings to make sure the Analytics team will be able to access it
- [ ] Add your team label to follow progress

**Additional Info**

- Please use the [KPI Framework](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/Analytics%20Playbook/va-gov-platform-analytics-kpi-framework.pdf) for more information on the metrics used in the Standard KPI dashboards. 
- If you need any analytics support, read through the [How to request Analytics support](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guidelines.1586823275.html#Analyticscustomersupportguidelines-4.RequestaKPIDashboardinDomo).
- If you do not have Domo access, please [request access here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+access-request&template=analytics-request-google-analytics-domo-access.md&title=Request+access+to+Google+Analytics+and%2For+Domo).

**Comment by michelle-dooley** [comment]
@rachaelpenfil can you please share access to the google sheet.

**Comment by michelle-dooley** [comment]
@rachaelpenfil can you please share access to the google sheet.

**Comment by michelle-dooley** [comment]
@rachaelpenfil thanks for sharing. Is this form live and if not when will it launch? Also can you please provide all the sub-page urls (we need all form funnel urls, intro to submit/confirmation).

**Comment by rachaelpenfil** [comment]
@michelle-dooley This form is not live yet, we are currently in the very early stages of the digitization effort. We are trying to understand who is accessing this page/downloading the PDF application today, so that we can refine our use research efforts.

**Comment by michelle-dooley** [comment]
@rachaelpenfil so you just want to know how many people are currently downloading the form to get a sense of demand? Here are some GA reports that can provide some insight. Once the form is live we can get it added to the  [Forms dashboard](https://va-gov.domo.com/page/447193050). Does that help or is there something more you are looking for at this time?

[CHAMPVA events GA report](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.filter=CHAMPVA&explorer-table.secSegmentId=analytics.pagePath&explorer-table.advFilter=%5B%5B0,%22analytics.eventAction%22,%22RE%22,%22CHAMPVA%22,0%5D%5D) 
[find form 1010d pageviews report](https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/explorer-table.filter=10-10d~2F&explorer-table.plotKeys=%5B%5D)
[champva page views](https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/explorer-table.filter=10-10d~2F&explorer-table.plotKeys=%5B%5D)

<img width="1584" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVk2QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--125f7a1fe4e1b32051ace9505a7306c7a1b0df02/image.png" alt="image.png" />

<img width="1551" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBek02QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aa443714ae986b267483c6089622b6b8cdd7a558/image.png" alt="image.png" />

<img width="1583" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelE2QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--63dffeb3c33999c820691a84941800f953a455b8/image.png" alt="image.png" />

**Comment by rachaelpenfil** [comment]
@michelle-dooley I requested access to GA, but I can't seem to open any of those links. Do you know why that might be?

**Comment by michelle-dooley** [comment]
@rachaelpenfil - sorry I just saw this, not sure what happened to your request but I didn't see you in GA so I just added you. See if you can open now.

**Comment by Blivaditis** [comment]
@rachaelpenfil could you share the linked document with me? We are planning on pulling this request in and after reading up on some of the history I was curious if the form is live, if it is live would you'd like it added to the VA.gov forms dashboard?

**Comment by rachaelpenfil** [comment]
Hi @Blivaditis - document shared. The form isn't live yet, but we would like to add it to the dashboard when it is.

**Comment by Blivaditis** [comment]
Thank you for that, when do you plan and launching the form?

**Comment by Blivaditis** [comment]
@rachaelpenfil is this version one?

**Comment by marywang2** [comment]
@Blivaditis it may be a while before we launch the form to production as we are still figuring out the back end integration. It will be going to staging very soon - would you be able to work with staging urls or does the form need to be live? cc @baltes

**Comment by Blivaditis** [comment]
@marywang2 Its not an issue whatsoever, when you get closer to launch and decide on a launch date let me know!

**Comment by ChristineYoungZA** [comment]
@Blivaditis and @johnny-jesensky-adhoc I think we close this one and have them open a new one when the team is ready.
