### ISSUE TITLE
CT: Nulls on caution flag for search results

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#7114]
Visit https://staging-api.va.gov/v0/gi/institution_programs/search
Observe null values for "caution_flag"

**Comment by zurbergram** [comment]
Sample insert query to get data into local for testing

```
insert into caution_flags values (99999999, 2359106, 37, 'test', 'test2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
```

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/625

**Comment by zurbergram** [comment]
http://localhost:4000/v0/institution_programs/

**Comment by sonntag-adam** [comment]
No longer null
![Screen Shot 2020-03-23 at 3.13.13 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/b9a764ec-0ab4-484d-be8a-96df5e9366e5)

**Comment by sonntag-adam** [comment]
Merged. Closing bug
