### ISSUE TITLE
Analytics Implementation or QA Support for MHV on VA.gov landing page

### ISSUE THREAD

**Issue by jzucadi** [department-of-veterans-affairs/va.gov-team#71140]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

</div>
</details>

### Required
- **Is this request for **Google Analytics implementation** or **QA**?**

     - [x] Google Analytics implementation
     - [ ] QA

- **Who is this request for?**

    - MHV on VA.gov landing page team
    
    
- **Provide the link(s) for Google Analytics implementation or QA**
  
    - /my-health
    
- **When is the launch date?**
    - Already launched

- **What interactions need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked_
    
    - Need to track the domain URL of all of the links in the hublink section. 

<img width="705" alt="Screenshot 2023-12-04 at 1 11 43 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/7745936/3cb7cf5d-a204-4ba5-8297-aa88e2300e43">

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

**Comment by jestutt** [comment]
@jzucadi  GTM event tag has been updated to capture the `destination-domain` datalayer variable at the end of the Event Action
<img width="682" alt="Screenshot 2023-12-13 at 1 16 15 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/141653184/d0a465b9-4d6b-4bd7-9d72-00149b17e167">
