### ISSUE TITLE
Get the 526ez form working on localhost - Jesse [Blocked]

### ISSUE THREAD

**Issue by gabezurita** [department-of-veterans-affairs/va.gov-team#71141]
To explore claims evidence from an engineering perspective, engineers within the CE team will need to get the 526ez form working in both localhost and staging.

This work will also eventually make it possible.

### Dev Notes
valid staging and localhost users for the form are:
vets.gov.user+1@gmail.com
vets.gov.user+228@gmail.com

The 526ez localhost URL (with a ?oath=false param):
http://localhost:3001/disability/file-disability-claim-form-21-526ez/introduction?oauth=false

If you run into issues with `idme` in localhost, [this thread](https://dsva.slack.com/archives/CBU0KDSB1/p1679076878010989) is relevant

### AC
Get the 526ez form running in both localhost and staging. Share any blockers or findings in [#benefits-claims-evidence-engineering](https://dsva.slack.com/archives/C068CLY53JQ)

**Comment by RivkaCGates** [comment]
@gabezurita should this even be in this board?

**Comment by RivkaCGates** [comment]
@gabezurita I think so @emily-gullo @nihil2501 ?

**Comment by nihil2501** [comment]
@gabezurita I have gotten `vets-website` and `vets-api` working locally.
