### ISSUE TITLE
[AL2 AMI] Get test coverage to 95% (goal)

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#71144]
## Description
Currently at 90.4% goal is to get as close to 95% as possible.

## Resources 
- [CIS Amazon Linux 2 Controls Checklist v1.0.0](https://dvagov.sharepoint.com/:x:/r/sites/OITBCM/Approved_Baselines/CIS-Amazon-Linux-2-Controls%20Checklist-v1.0.0.xlsx?d=wa633e639d08e4eb493d35b44fb4f865b&csf=1&web=1&e=fSf8mz)
- [Rules Checklist](https://dvagov-my.sharepoint.com/:x:/r/personal/hector_barreto_va_gov1/Documents/SCCD-Checklist-Nov2023.xlsx?d=w5aa5eb7cafbc488cb0d89bd87124dace&csf=1&web=1&e=m1AjgZ)

## Acceptance Criteria
- [x] Determine any false positives
- [ ] Gather information in order to submit an exception ticket

## Refinement Guidance - Check the following before working on this issue: 
- [x] _Team label assigned ("platform-tech-team-2")_
- [x] _Epic assigned (if needed)_ 
- [ ] _Estimated (points assigned)_
- [x] _Sprint assigned (once planned)_
- [x] _Team member(s) assigned_
- [x] _Understands how this work aligns with the overall platform_

**Comment by npeterson54** [comment]
Pulling into sprint a day early!

**Comment by hgbarreto** [comment]
## SSCD Score
Currently sitting at SSCD Score range of 91-91.5%

## False Positives
If false positives are found during an investigation of BigFix findings, a General Request ticket can be opened from the VA network. 
Submitted request RITM10782752 requesting remeditaion of 10 findings we flagged as false positive.

**Comment by hgbarreto** [comment]
Submitted an incident referring to the request. Closing the Story since we are only waiting for a response from the VA side.
INC30604532
