### ISSUE TITLE
User flow through Form 10-10D

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#71157]
This issue covers updates to the user flow for 10-10d to reflect what we've learned since the last pass.

**Comment by marywang2** [comment]
Risk - not yet in the VA design system (in figma).

**Comment by pshahVA** [comment]
Is this the latest [user flow](https://www.figma.com/file/aDA1zJmVYRH8eDC776B4KR/Sharable-User-Flow-10-10d?type=whiteboard&node-id=0-1&t=UL0VPNeheC9fZ7aJ-0)

**Comment by baltes** [comment]
@pshahVA I believe so. @syd-hoeper  or @jamiefiore, can you confirm?

**Comment by syd-hoeper** [comment]
@baltes @pshahVA Yes, that's the latest one -- I just cleaned up that file so it's more obvious which one it is
