### ISSUE TITLE
SOCKS access for [Rachel Eiting]

### ISSUE THREAD

**Issue by reiting** [department-of-veterans-affairs/va.gov-team#71155]
### Your Name

Rachel Eiting

### Your Email

rachel.eiting@copilot.llc

### Your Role and Team

Frontend Engineer

### Product Manager (PM) name and email

Devi Hill, devi.hill@agile6.com

### Product Owner (PO) name and email

Premal Shah, premal.shah@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC+90Ky396VMasyDCVLNVeICL+2pqZ5RTMUy9/clFhrEf611gMKz4y80g3D1zLrJwR639Br0v6dx33zQwUqu1mA/ZRbSiGoKJvin40s73sU3b1MFhRU6LBCTd3X8PaCwEP3q1f4uDnGc1WMsCr/ny9kMNVxkF17d9eC68VkdkFS4W3v8JhbXrt05qHlU5OFV/2FEK1UvjKmvnrTO19voUxbWCl8SvVxxHMvq3muiJCwfojLKouJdyOniVcvnRUHPVg0XMmH8BPxYq/uUvNFmxI+i81C9RqYFoWKeeSMM42hYGuEL7qBrJh+rrZh0RnbfuzDPuENIi6HnvZYCm+OZpt1jHy8YiPIOc4WqjoKjFVSF1r3bs951Zg0+3x48DP7HCCfmcm1ODDE1P4HfNsWhdpORd/HvXdwXxIMCErL4BbyodjxeO9o6SyFAshkgldSJoZ6xdzAdmmdVh3yjqXFeQNquEeWZ0kAz5LY0iABRMxSSjyDnrSFDehX0VXdEslkqxs= racheleiting@Rachels-MacBook-Pro.local

### E-QIP Transmittal Confirmation

I do not yet have my e-qip transmittal confirmation

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by ph-One** [comment]
> I do not yet have my e-qip transmittal confirmation

@reiting Once you have that, please attach it here and @ me so that I can complete the request. Only takes a few minutes, but we need the EQIP transmittal confirmation first.
