### ISSUE TITLE
Updates to "Type of accredited representative" section

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#71167]
Our accessibility partner Jamie has provided some feedback to the "Type of accredited representative" section":

1. The “type of accredited representative” field has some screen reader-only text in the legend, but its pretty redundant. Right now, Chrome reads out "Type of accredited representative  **_select your representative type_** star required." We can get rid of the "select your representative type", shown in the code screenshot below, as it's redundant to include in the screen reader.
   1. <img width="308" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTB1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--86594ebeacc57776fd155bc634aabf26ccc2b341/image.png" alt="image.png" />
2. We don’t need `header-aria-describedby="Select your Representative type:"` or `aria-label="Type of accredited representative required"` on the radio component as they’re duplicative of what’s already been added to the `<legend>`.
3. ~Consider updating these elements to use the v3 design (was there a reason why we did not use v3 originally?)~

Original Slack discussion: https://dsva.slack.com/archives/C05L6HSJLHM/p1701718216660509?thread_ts=1701271694.454669&cid=C05L6HSJLHM

### Tasks
- [x] Update the "Type of accredited representative" field so screen readers no longer include "select your representative type"
- [x] Remove duplicative aria header description and label

**Comment by cosu419** [comment]
The v3 radio options do not fire a callback method on select. Recommendation from FE devs was to use the old version.
