### ISSUE TITLE
Midpoint Review - Content - VYE Team, Verify Your Enrollment

### ISSUE THREAD

**Issue by rferguson13** [department-of-veterans-affairs/va.gov-team#71186]
## VFS actions
- [x] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [x] Comment on this ticket:
  - [x] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [x] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [x] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [x] Close the ticket when all feedback has been addressed.

## Thoughts

Overall, nice work! This is looking pretty good. My biggest piece of feedback is to make sure that content is in [plain language](https://design.va.gov/content-style-guide/plain-language/) and presented in a way that's easy to follow, e.g. shorter subheadings. If you have any questions, please don't hesitate to ask.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

### Must
- All pages - The user encounters subheadings that are long and packed with information. Subheadings should be broken up and shortened. Please revise by shortening the subheadings or exploring other ways to display that information. There are several ways the writer could do this. For example, they could have a shorter subheading and then use paragraph formatting to present more information. 
- Verify school enrollment > "If you’re using..." - On the first page, the user finds a subheading that has a lot of information about where they can verify their enrollment. This is a lot of information and each sentence tells the Veteran a different directive. This should have paragraph breaks or bullets to make it easier to scan and gives clearer direction for next steps.
- Verify School Enrollment page - The subheading at the top doesn’t match the rest of the page. The user is told that if they have Montgomery GI benefits, they can verify their enrollment on WAVE. However, when they scroll down the page, the sign-in doesn’t say WAVE - it looks like VA.gov. Does that take them to WAVE? Please revise so the wording is clearer and provides a clear action for the user to take.
- Verify school enrollment > For Montgomery GI Bill benefits > Other ways to verify your enrollment - Under the section titled “For Montgomery GI Bill Benefits,” the user finds a subheading that reads “Other ways to verify…for Post-9/11 GI Bill benefits.” Please revise so the subheadings and information match the section they’re in. In this case, the subheading should be: “Other ways…For Montgomery GI Bill benefits.”
- Landing page - Verify - Desktop - The user finds the subheading: “If you have an active benefit award for the Montgomery GI Bill you’ll need to…” There is a missing comma between “Bill” and “you’ll.” Please revise so the sentence is: “...Montgomery GI Bill, you’ll need…”
- Landing page - Verify - Desktop - The second sentence of the subheading, “Active records are those with activity in the last 12 months,” is unclear since “active records” is not used elsewhere in the flow. What is meant by “active records”? Please revise and clarify. You could also remove it - does it need to be in the subheader?
- Landing page - Verified - Once the user has verified their enrollment, but it hasn’t been processed yet, they’re given this message: “Verifications are processed on the business day after submission. Payment is projected to be deposited within 3-5 business days.” This is not written in [plain language](https://design.va.gov/content-style-guide/plain-language/). Please revise using simpler words and terms. There are several ways the writer could do this. For example, they could write: “Verifications are processed the next business day after submission. Your payment will be sent in about 3-5 business days.”

### Should
- Verification success - When a Veteran has successfully verified their enrollment, they receive the message: “Your verification will be submitted for processing during the next regular business day.” This is very wordy and potentially confusing - they’ve successfully verified their enrollment, but the text says the verification will be submitted the next business day. This should be revised so it’s clear to the user what the next step is and what they can expect. There are several ways the writer could do this. For example, they could rephrase the sentence to be: “Your verification has been submitted and will be processed the next business day. Your payment will be deposited in about 3-5 business days.”

### Consider
- On the landing page, it may be beneficial to use accordions for each section. It’s a lot of information to scroll through and some of it is repetitive (especially between the Post-9/11 GI Benefits and the Montgomery GI Bill benefits sections). 
- Your monthly enrollment verifications > What if I notice an error in my enrollment information? > If the user finds an error, this is the direction they’re given: “If you notice a mistake, it’s best if you reach out to your SCO soon.” Consider revising to give clearer directions and emphasize the urgency of the situation. There are several ways the writer could do this. For example, the directive could be: “If you notice a mistake, reach out to your SCO as soon as possible.”

## Notes
Thank you for the opportunity to review your work. Please continue to work with CAIA to take this content to the next level.

**Comment by cassidy-beach** [comment]
**Must 1:** Subheadings have been broken up and shortened. See attached photo. 
**Must 2:** The subheadings were shortened and provides clear directives. See attached photo. 
**Must 3:** The subheadings at the top of the page now match the rest of the subheadings. They must sign in to verify their school enrollment. When the user scrolls to Montgomery GI Bill benefits they must sign into their VA.gov account to access their information and verify their school enrollment. The new version is clearer. See attached photo.
**Must 4:** The subheading now says "For Montgomery GI Bill benefits." See photo for **Must 3**. 
**Must 5:** Change has not been made yet. 
**Must 6:** Change has not been made yet. 
**Must 7:** Change has not been made yet. 
Should 1: Change has not been made yet. 
**Consider 1:** Change has not been made yet. 
**Consider 2:** Change has not been made yet.
![71186 Must 1](https://github.com/department-of-veterans-affairs/va.gov-team/assets/143453442/74ea3a01-692e-47a2-9d02-09bb7a8d35f0)
![71186 Must 2](https://github.com/department-of-veterans-affairs/va.gov-team/assets/143453442/2f253f5e-834d-4d1f-9008-1f0fd2e19172)
![71186 Must 3](https://github.com/department-of-veterans-affairs/va.gov-team/assets/143453442/62f76c22-02d7-4043-9e8a-0fcb7506220c)

**Comment by cassidy-beach** [comment]
**Must 7:** Language discussing deposit dates has been simplified. It now says "Payments for this month were deposited on February 2nd, 2024 and February 9th, 2024." The actual dates of deposit will be listed. See attached photo. 
**Should 1:** Language discussing deposit dates has been simplified. It now says "Payments for this month were deposited on February 2nd, 2024 and February 9th, 2024." The actual dates of deposit will be listed. See attached photo. 
**Consider 1:** We are not going to make this change. 
**Consider 2:** If a user's information is incorrect they receive a notification to contact their School Certifying Official to submit Form 22-8979. See attached photo. 
![71186 Consider 2](https://github.com/department-of-veterans-affairs/va.gov-team/assets/143453442/dd195c69-558c-42c4-a29f-a82e09eb6a9c)
![71186 Should](https://github.com/department-of-veterans-affairs/va.gov-team/assets/143453442/8764c695-5116-4aa0-b8d4-f5683c93b4bd)

**Comment by cassidy-beach** [comment]
**Must 5:** Completed in VYE-310 - Make design changes in accordance with CAIA accessibility and content requirements and VYE-311 - Implement design changes in code 
**Must 6:** Completed in VYE-310 - Make design changes in accordance with CAIA accessibility and content requirements and VYE-311 - Implement design changes in code
