### ISSUE TITLE
[epic] NOD | Infinite loop bug prevented users from accessing the form

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#71191]
## What happened?

On May 23, 2023, a feature flag, and code to disable the submit button was added to the Notice of Disagreement form at 1:50 PM ET. This introduced a bug that prevented roughly ~3,152 users from accessing the form between July 27th - September 1st. We were notified on August 31st in this [Slack thread](https://dsva.slack.com/archives/C5AGLBNRK/p1693505338029709).

## Next steps

- ✅ Deploy a [hotfix](https://github.com/department-of-veterans-affairs/va.gov-team/issues/64802)
- ✅ Gather list of affected Veterans
- ✅ (in progress) Release the NOD V2 form with "Reason for extension request" fields
    * ✅ Regression testing
    * ✅ E2E testing
    * ✅ Approval
    * ✅ Release
- ✅ Print copy of notification letter is mailed to Veterans & their POAs
    * ✅ Get [draft content](https://dvagov.sharepoint.com/:w:/r/sites/vaabdvro/Shared%20Documents/Decision%20Reviews/NoD%20errors%20-%20Comms%20to%20Veterans.docx?d=we190d63de79546c39a1d1f67c50c4c36&csf=1&web=1&e=EGxlDF) approved for email and letters
    * ✅ Get a privacy officer assigned to review content
    * ✅ Get privacy officer approval
    * ✅ eFolder creation
    * ✅  Bo Yang (VBA) to send POA data in text and excel file type
    * ✅ (Cory) If we don't find the missing data for the Veterans without a file number, remove the Veteran records with incomplete info from the file Bo sent
    * ✅ (Cory) Pull final record of all deceased Veterans 
    * ✅ (Julie) Create copy for letter to survivors of deceased Veterans 
    *  ✅ (Sade w/ enablement team support) Send information necessary for ADG to create a letter feed (deadline)
    * ✅ Notification letter is added to Veterans' eFolder
- ✅ Email is sent to Veterans - [VA Notify ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65509)
    * ✅ Setup callbacks to show us who (if any) emails return a hard bounce
- ✅ Business lines give sign-off on the overall plan, including letters, return mail, and guidance for appeal processors.
- ✅ Complete a [post-mortem](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Postmortems/2023/2023-05-24-notice-of-disagreement-outage.md)
- ✅ (Sade) Confirm remediation is complete with PO

**Comment by saderagsdale** [comment]
Update on content from Julie:

The [print letter](https://dvagov.sharepoint.com/:w:/r/sites/vaabdvro/Shared%20Documents/Decision%20Reviews/2023-07%20to%20-09%20NOD%20errors/NOD%20notification%20letter%20in%20template.doc?d=wd6f7c8247f954c46968eaac5ef200122&csf=1&web=1&e=x0yfC9) and [draft email](https://dvagov.sharepoint.com/:w:/r/sites/vaabdvro/Shared%20Documents/Decision%20Reviews/2023-07%20to%20-09%20NOD%20errors/DRAFT%20VANotify%20email.docx?d=w6300a1880ee542d6ac0f788049c586b1&csf=1&web=1&e=OzXDbF) are in SharePoint.

**For the print letter:**

- We accepted the Board's edits to Danielle's edits
- I edited the how to submit online to reflect the actual field names they can put their affirmation statement in & the characters cap on the "what you disagree with" field. (The extension field only works for this purpose for people who've reached the deadline.)
- I need to tell the Board I did this and ask them to tell me if they have concerns (I removed "I affirm" and changed date formatting :scream:)
- I'm waiting on Mandel who works on print (returning from vacay tmw) to answer:

1. In the template, what do #'s 2, 4, & 5 refer to? (I think 4 or 5 is the VA File Number. )
2. Are any of 2, 4, or 5 optional?
3. When we provide the template, how should we indicate variables? e.g. Can we write [Full Veteran name], and then refer to "Full Veteran name" in the data file?

**For the email:**

- I need to ask Content if there's a preference for using friendly link text or full URL. I see both in VA Notify.

**Comment by jstrothman** [comment]
The questions above have all been resolved. Letter links are unchanged:
* [NOD infinite loop issue - VA Notify email.docx](https://dvagov.sharepoint.com/:w:/r/sites/vaabdvro/Shared%20Documents/Decision%20Reviews/2023-07%20to%20-09%20NOD%20errors/Infinite%20loop%20-%20VANotify%20email.docx?d=w6300a1880ee542d6ac0f788049c586b1&csf=1&web=1&e=vwXe4V) 
* [NOD notification letter in template.doc](https://dvagov.sharepoint.com/:w:/r/sites/vaabdvro/Shared%20Documents/Decision%20Reviews/2023-07%20to%20-09%20NOD%20errors/NOD%20notification%20letter%20in%20template.doc?d=wd6f7c8247f954c46968eaac5ef200122&csf=1&web=1&e=WBrEYK)

**Comment by jstrothman** [comment]
3124 emails were sent on 3/28, and the list of ~2% of Veterans who didn't receive the email due to invalid/old email addresses was shared with A. DeChiara from the Board.

The hard copy letters were sent to pre-sort for mailing on Friday March 29, 2024.  Electronic e-folder copies were sent to ADG for upload into the veteran’s e-folder on 4/2.
