### ISSUE TITLE
[dev task] NOD | Confirm that BVA received claims and evidence

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#71195]
## Background Context
We want to confirm that our fix and the evidence we sent have made each of the ~48 affected claims whole.

## Tasks
- [ ] Send claim and evidence data to BVA in their desired format
- [ ] Confirm claim wholeness

**Comment by data-doge** [comment]
Sent updated spreadsheet to Bo at BVA, and gave some additional context. Just waiting to hear back now.

**Comment by saderagsdale** [comment]
@data-doge I followed up on the email and asked the enablement team to be a squeaky wheel in [this](https://dsva.slack.com/archives/C5AGLBNRK/p1702923557189419) thread.

**Comment by saderagsdale** [comment]
Spoke with BVA today - their ask is to confirm with CMP that the claim and evidence associations are accurate.

**Comment by HeatherWidmont** [comment]
Met with Bo & some of his BVA coworkers to answer questions about what exactly we wanted from BVA & how to connect evidence uploads to what their seeing. @data-doge & @saderagsdale to sync about this in the parking lot today

**Comment by saderagsdale** [comment]
Desired outcome: Confirm if file existence in VBMS means that it went through CMP. Confirm that Evidence files are accurately associated with the claims.

- @data-doge  will reach out to CMP for questions about confirming data went through the right channels (Tim Wagner, Katherine King)
- @data-doge may ask Bo if file name works
- We can also check tables Eugene found for audit trail for statuses

**Comment by HeatherWidmont** [comment]
Sade reached out to CMP & Eugene will hold off on reaching out to Bo until hearing back from CMP

**Comment by eileen-coforma** [comment]
Still waiting to hear back from Bo

**Comment by HeatherWidmont** [comment]
@saderagsdale will double check the email thread to see if we've gotten a response

**Comment by HeatherWidmont** [comment]
@saderagsdale heard back from Jacob, & he said they are unable to see the participant ID. Jacob to schedule time with the vendor to review the sheet that Eugene created. She asked Jacob the next steps for scheduling.

**Comment by HeatherWidmont** [comment]
Tentatively scheduled for tomorrow

**Comment by data-doge** [comment]
I spoke with LH (see [Slack](https://dsva.slack.com/archives/CKUCFQAHJ/p1705008045451319)) and learned what GUIDs I need to send to EMMS/CMP to help them find our evidence uploads in their systems. I updated the spreadsheet Sade previously shared with Jacob, and emailed Jacob. Just waiting to hear back now.

**Comment by HeatherWidmont** [comment]
@saderagsdale just checking in, have you heard back from the CMP folks?

**Comment by HeatherWidmont** [comment]
@saderagsdale is setting up a meeting on Friday with Jacob, someone from the BVA, & Eugene to confirm that the appeals & evidence are properly stored

**Comment by saderagsdale** [comment]
Our next task is to send a writeup of how appeals and evidence were mapped with the BVA intake team. @data-doge should I make a separate ticket for this?

**Comment by HeatherWidmont** [comment]
@data-doge said yes about sending a writeup of how appeals & evidence were mapped with the BVA intake team. They will come back to this after finishing the "pull email" work

**Comment by data-doge** [comment]
I think we can close this ticket, and I'll draft a separate ticket for the write-up work before sprint planning tomorrow.
