### ISSUE TITLE
Update Redis 6.2 Plan

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#71209]
### PROBLEM STATEMENT
In its current version, Redis has reached EOL. To continue receiving support, redis needs to be upgraded to 6.2.
After completing the postgres upgrade recently, we learned of a number of ways to improve he planning and upgrade process. This improvements need to be documented in the [redis upgrade plan](https://vfs.atlassian.net/wiki/spaces/PPT/pages/2806808593/Redis+Update) and well socialized with relevant parties.

### ACTION ITEMS
- [x] review PG [retro](https://easyretro.io/publicboard/pl0f6ivhDjZcj5sjPDTP7mDtDxs2/6c602fa0-b190-4618-88c3-1979a1aafc6e)
- [x] update plan per retro
- [x] socialize plan with relevant parties (slacks and/or meetings)

### DEFINITION OF DONE
- [ ] plan is updated and linked here

**Comment by flooose** [comment]
## Additional steps from Retro

- [ ] Finalize "script" and distribute to appropriate parties
- [ ] Update "script" to reflect the possibility of individual failures in the upgrade, i.e. we have multiple clusters and any one of them could fail

**Comment by laineymajor** [comment]
Will be testing the scaling in dev today per @flooose 
If testing goes well, move to staging for the actual upgrade.

**Comment by laineymajor** [comment]
Contining to run into problems with apple m1 architecture + terraforms. Will work with Kshitiz to compare and fix.

**Comment by laineymajor** [comment]
This should be done end of sprint. Completing upgrade in lower envs THEN might have a few updates to the plan.
