### ISSUE TITLE
Redirect Request - Special disability payments (auto, clothing, Medal of Honor)

### ISSUE THREAD

**Issue by AnneHurley** [department-of-veterans-affairs/va.gov-team#7120]
### Description
*This is a detailed description of the request. It should include background information and reason for the request.*

### Requestor team info
Sandy Tadeo, VBA
@AnneHurley 
@lunascoop 

### Implementation date
Date new URL(s) will be live: *enter date new pages/URLs will be live*

Please indicate when the redirect(s) needs to be implemented"
- [ ] On the same date the new URLs launch
- [ ] Can happen within 1-5 business days after new URLs launch
- [x] Other - Please indicate timing :  As soon as is convenient - the new VA.gov page/s are already live. 

**The requesting team is responsible for notifying the group working on this issue if the target date changes. They are also responsible for ensuring the destination URLs are implemented correctly and live at the time the redirects are deployed.**

### Redirects needed

Current URL  |  Redirect Destination (new URL)
---  |  ---
*https://www.benefits.va.gov/compensation/special_Benefit_Allowances_2019.asp* | *https://www.va.gov/disability/compensation-rates/special-benefit-allowance-rates/*

### Definition of done
- [x] Above information is provided and issue is tagged and assigned appropriately - *@ requesting team*
- [ ] All appropriate VA stakeholders are notified of pending redirect - *@ requesting team*
- [x] Redirect request is vetted and documented and implementation plan is clear - *@ Content & IA team*
- [ ] Request is assigned to appropriate team for implementation - *@ Content & IA team*
- [ ] Implementation team completes work - *@ Implementation team*
- [ ] Implementation pushed live and redirect is validated in production - *@ all*
- [ ] Ticket is closed - *@ requesting team*

**Comment by mnorthuis** [comment]
This redirect is vetted and documented and can be implemented when ready.

**Comment by lunascoop** [comment]
@MickinSahni @mnorthuis @AnneHurley closing this ticket as this redirect, along with others, is covered in ticket #7202.

**Comment by MickinSahni** [comment]
sweet. prepending a 'dupe' on it
