### ISSUE TITLE
VAOS Vets API Log When ICN is Missing

### ISSUE THREAD

**Issue by ajmagdub** [department-of-veterans-affairs/va.gov-team#71210]
VAOS Service reported receiving bad URLs when requesting appointment list, **/vaos/v1/patients//appointments**.  It is isolated to mobile app request, an a probable cause is missing ICNs (though it is reported that that shouldn't be happening). See this Slack thread for context: [Thread](https://vappgteam.slack.com/archives/C023EFZPX4K/p1701709945144419?thread_ts=1701705739.474269&cid=C023EFZPX4K).

This ticket is to add temporary Vets API logging for instances where the ICN is missing when appointment list requests are made. 

Once the data is collected for a couple of days remove the logging.

**Comment by ajmagdub** [comment]
Over the past six days, we have been keeping a record of the missing ICNs. We have noticed that these missing ICNs coincide with the bad URL that VAOS Services had been experiencing. Most of the time, there were no more than two to three missing ICNs per day. However, there was a brief period yesterday, December 11 at 8:00 PM MT, that lasted for about 10 minutes, during which Vets Web encountered a lot of 403s being returned. The Mobile app also saw some instances of missing ICNs and malformed URLs during this time.

**Comment by ajmagdub** [comment]
The required information has been collected. Logging is no longer necessary. Removed logging from Vets API.

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket.
