### ISSUE TITLE
Fetching list of appointments is returning a 500 error occasionally

### ISSUE THREAD

**Issue by saneshark** [department-of-veterans-affairs/va.gov-team#7122]
Sentry issue: http://sentry.vfs.va.gov/vets-gov/platform-api-production/issues/106679/events/6043227/

When fetching appointments for example:

/appointments/v1/patients/REDACTED_ICN/appointments?endDate=2021-03-22T06%3A00%3A00Z&pageSize=0&startDate=2020-03-22T06%3A00%3A00Z&useCache=false

We're encountering a 500 error saying something like: An error occurred (ID: e947a92b-a14f-4874-8c63-79a28f298396)

There have only been a few occurrences of this, but we should check Kibana to see whats causing this.

**Comment by lenaecb** [comment]
@saneshark - is this the same as #7123?

**Comment by saneshark** [comment]
No, this one is related to fetching appointments whereas the other one is appointment requests.

The last known occurrences were April 7, with 4 incidents. In total, there have only been 8 or 9 occurrences, so again it's probably not a super high priority but worth keeping an eye on.

**Comment by lenaecb** [comment]
@saneshark - what's the update on this? still happening?

**Comment by saneshark** [comment]
I have opened a VAOS-R ticket: https://issues.mobilehealth.va.gov/browse/VAOSR-749

It's not being tracked and Larry and his team will be looking into this. Will provide update possibly as early as tomorrow.

**Comment by saneshark** [comment]
Latest update is that this is somehow related to CDW service being unable to fetch clinics. More to come.

**Comment by lenaecb** [comment]
The plan is for them to add more logging for this CDW error. So, putting into 'blocked' since this isn't resolved until we have more logging.

**Comment by saneshark** [comment]
This issue appears to have been resolved.
