### ISSUE TITLE
Appointment Request is returning a 500 error

### ISSUE THREAD

**Issue by saneshark** [department-of-veterans-affairs/va.gov-team#7123]
Sentry Issue tracking: http://sentry.vfs.va.gov/vets-gov/platform-api-production/issues/107837/events/?query=vaos

There were quire a few occurrences of this error and it seems to have MAYBE resolved itself, but its still a worthwhile exercise to track down what caused the 500 error in Kibana.

A POST request to: /var/VeteranAppointmentRequestService/v4/rest/appointment-service/patient/ICN/REDACTED_ICN/appointments

appears to be returning a 500 error response.

Ticket with BE team -- https://issues.mobilehealth.va.gov/browse/VAOSR-567

**Comment by lenaecb** [comment]
@saneshark - can you confirm that this did in fact resolve itself?

**Comment by saneshark** [comment]
Last known event was April 4, with 1 occurrence. Prior to that the last known events were March 17 and appear to have coincided with known issues VAMF was experiencing.

I wouldn't say we should close it, but its certainly not very high priority based on number of occurrences.

**Comment by lenaecb** [comment]
A ticket was opened up with the MACM team to do some investigation of the 500s and AppointmentRequest -- https://issues.mobilehealth.va.gov/browse/VAOSR-567

**Comment by saneshark** [comment]
There might be a follow-up action based on those findings so lets keep this open, but blocked by VAOSR-567 for now.

**Comment by jbalboni** [comment]
I have not seen one of these since the fix from https://app.zenhub.com/workspace/o/department-of-veterans-affairs/vets-website/issues/12674 went into the FE.

FE error group: http://sentry.vfs.va.gov/vets-gov/website-production/issues/119897/?query=is%3Aunresolved%20source%3Avaos

There are a still a couple errors post the fix in that group, but they're 401 errors, not 500s.

**Comment by saneshark** [comment]
Closing being tracked on Jira.
