### ISSUE TITLE
Flipper UI access for [Chapley Watson]

### ISSUE THREAD

**Issue by jadon1979** [department-of-veterans-affairs/va.gov-team#71244]
### Your Name

Chapley Watson

### Your GitHub handle (Flipper UI access is managed through GitHub)

@jadon1979

### Team, Role, and Company of the target individual

1010-ez, Software Developer, Agile6

### Please confirm if you are on Atlas, Platform Team Roster or are a Federal User

- [ ] [Atlas](https://dev.va.gov/atlas)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [X] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [X] Lesser Environments (Dev/Staging/Sandbox)
- [X] Production (if requesting, justify prod access below)

### Reason for Production Access (If requested)

We currently have 1-2 individuals who can toggle features in prod.  This is an issue for several reasons including time-off scheduling for the holidays.  I need access to be able to flip features when requested.

**Comment by bdech** [comment]
E-QIP found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65212)

**Comment by bdech** [comment]
@jadon1979 You've been added to both `lesser` and `production` environments.
