### ISSUE TITLE
CT: Remove prod flag for #6662

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#7124]
As a developer, I need to remove the prod flag for the updates to the timeout error message on Comparison Tool so that they are available in the production environment.

## Assumptions:
1. EDU has reviewed and signed off on the changes as of [TBD].
2. UX has reviewed and signed off on the changes as of 03/20.

## Acceptance Criteria:
1. The functionality in #6662 is available in the production environment.

## Supporting Artifacts:
1. N/A

**Comment by sonntag-adam** [comment]
Shows in a production build.

**Comment by sonntag-adam** [comment]
Merged. Closing story
