### ISSUE TITLE
VAOS vets-api Log clinic stop codes returned for Direct scheduling.

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#71272]
## Description
When the vets-api endpoint `vaos/v2/locations/{id}/clinics?clinical_service={typeOfCare}` is called, we want to log the clinic primary and secondary stop codes pairs returned.

<img width="1109" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEUwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fc03eb960c1498945523833ba48ed874dbbc2bc1/Screenshot%202023-12-05%20at%202.11.06%20PM.png" alt="Screenshot 2023-12-05 at 2.11.06 PM.png" />

<img width="1037" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVkwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--18a919ca35c51a493ffb6d0c151da888e9b090eb/Screenshot%202023-12-05%20at%202.18.32%20PM.png" alt="Screenshot 2023-12-05 at 2.18.32 PM.png" />

<img width="1051" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTAwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5662e899e7330ec33c436241f6068c15addeb873/Screenshot%202023-12-05%20at%202.19.22%20PM.png" alt="Screenshot 2023-12-05 at 2.19.22 PM.png" />

<img width="1626" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0EwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--14ff5c57107601a25b1f0c19595f636e8473d422/Screenshot%202023-12-05%20at%202.20.01%20PM.png" alt="Screenshot 2023-12-05 at 2.20.01 PM.png" />

**Comment by ajmagdub** [comment]
"I have attached the raw data from the clinic's stop code logging for your reference."[clinic_stop_codes.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdy9YQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5d71f0cc45288670ea2dd91bdb945d19cde66ff2/clinic_stop_codes.xlsx)

**Comment by ajmagdub** [comment]
None of the Primary Secondary pairs showed up in the collected logs.

Below is the Secondary Stop code's that showed up in the logs.

| Primary Stop Code | Primary Stop Code Name | Secondary Stop Code | Secondary Stop Code Name | # out of 647,759 records |  
| ------- | ------ | -------- | --------- | ----------- | 
| 372 |	WEIGHT MGMT & MOVE! PROG - IND |	117|	NURSING (2ND ONLY) | 2 |
| 373 |	WEIGHT MGMT & MOVE! PROG - GRP |	117|	NURSING (2ND ONLY) | 7 |
| 407 |	OPHTHALMOLOGY|	117 |	NURSING (2ND ONLY) | 2 |
| 408 |	OPTOMETRY |	117 |	NURSING (2ND ONLY) | 20 |
| 502 |	MENTAL HEALTH CLINIC - IND |	117 | NURSING (2ND ONLY) | 13468 |
| 502 |	MENTAL HEALTH CLINIC - IND |	117 |	NURSING (2ND ONLY) | 810 |
|502|	MENTAL HEALTH CLINIC - IND|	136|	TELE POST DEPLOY PT SITE| 3 |
|123|	NUTRITION/DIETETICS-INDIVIDUAL|	179|	RT CLIN VID CARE HOME| 542 |
|124|	NUTRITION/DIETETICS-GROUP|	179|	RT CLIN VID CARE HOME| 1512|
|203|	AUDIOLOGY|	179|	RT CLIN VID CARE HOME| 12228|
|203|	AUDIOLOGY|	179|	RT CLIN VID CARE HOME| 3|
|372|	WEIGHT MGMT & MOVE! PROG - IND|	179|	RT CLIN VID CARE HOME| 389|
|373|	WEIGHT MGMT & MOVE! PROG - GRP|	179|	RT CLIN VID CARE HOME| 767|
|407|	OPHTHALMOLOGY|	179|	RT CLIN VID CARE HOME| 128 |
|408|	OPTOMETRY|	179|	RT CLIN VID CARE HOME | 327|
|502|	MENTAL HEALTH CLINIC - IND|	179|	RT CLIN VID CARE HOME| 264120|
|502|	MENTAL HEALTH CLINIC - IND| 183|	PEER SPECIALIST| 5060|
|502|	MENTAL HEALTH CLINIC - IND|	184|	CARE/CASE MANAGER| 914|
|211|	PM&RS AMP CLINIC|	185|	NURSE PRACTITIONER| 1|
|407|	OPHTHALMOLOGY|	185|	NURSE PRACTITIONER| 1|
|502|	MENTAL HEALTH CLINIC - IND|	185|	NURSE PRACTITIONER| 14978|
|502|	MENTAL HEALTH CLINIC - IND|	186|	PHYSICIAN ASSISTANT| 2255|
|502|	MENTAL HEALTH CLINIC - IND|	187|	CLINICAL NURSE SPECIALIST| 430|
|407|	OPHTHALMOLOGY|	188|	FELLOW/RESIDENT| 41|
|408|	OPTOMETRY|	188|	FELLOW/RESIDENT| 493|
|502|	MENTAL HEALTH CLINIC - IND|	188|	FELLOW/RESIDENT| 15159|
|123|	NUTRITION/DIETETICS-INDIVIDUAL|	189|	S&F HOME NON VA PROV SITE| 5|
|143|	SLEEP STUDY|	189|	S&F HOME NON VA PROV SITE| 42|
|203|	AUDIOLOGY|	189|	S&F HOME NON VA PROV SITE| 166|
|372|	WEIGHT MGMT & MOVE! PROG - IND|	189|	S&F HOME NON VA PROV SITE| 2|
|502|	MENTAL HEALTH CLINIC - IND|	189|	S&F HOME NON VA PROV SITE| 20|
|372|	WEIGHT MGMT & MOVE! PROG - IND|	371|	HT SCREENING| 42|
|502|	MENTAL HEALTH CLINIC - IND|	371|	HT SCREENING| 2|
|203|	AUDIOLOGY|	440|	TELE FIT & ADJUST PROV SITE| 173|
|203|	AUDIOLOGY|	440|	TELE FIT & ADJUST PROV SITE| 945|
|502|	MENTAL HEALTH CLINIC - IND|	444|	C&P VIA CVT PT SITE| 84|
|502|	MENTAL HEALTH CLINIC - IND|	445|	C&P VIA CVT PROV SITE| 266|
|502|	MENTAL HEALTH CLINIC - IND|	446|	IDES VIA CVT PT SITE| 25|
|502|	MENTAL HEALTH CLINIC - IND|	447|	IDES VIA CVT PROV SITE| 13|
|502|	MENTAL HEALTH CLINIC - IND|	490|	TELETRANSPLANT PT SITE| 108|
|502|	MENTAL HEALTH CLINIC - IND|	644|	NC RTCV TELECARE PT LOC| 1562|
|502|	MENTAL HEALTH CLINIC - IND|	645|	NC RTCV TELECARE PRV LOC| 600|
|502|	MENTAL HEALTH CLINIC - IND|	699|	CVT EMERGENCY CONSULT| 4|
|502|	MENTAL HEALTH CLINIC - IND|	701|	BP EVAL| 28|
|502|	MENTAL HEALTH CLINIC - IND|	707|	SMOKING CESSATION| 75|
|502|	MENTAL HEALTH CLINIC - IND|	708|	TELE SMOKE CESS PROV SITE|  18|
|502|	MENTAL HEALTH CLINIC - IND|	713|	GAMBLING ADDICTION (2ND ONLY)| 5|
|123|	NUTRITION/DIETETICS-INDIVIDUAL|	714|	OTHER ED IND| 7|
|203|	AUDIOLOGY|	714|	OTHER ED IND| 10|
|502|	MENTAL HEALTH CLINIC - IND|	714|	OTHER ED IND| 21|
|123|	NUTRITION/DIETETICS-INDIVIDUAL|	719|	MHV SECURE MESSAGING| 110|
|124|	NUTRITION/DIETETICS-GROUP|	719|	MHV SECURE MESSAGING| 4|
|203|	AUDIOLOGY|	719|	MHV SECURE MESSAGING| 734|
|372|	WEIGHT MGMT & MOVE! PROG - IND|	719|	MHV SECURE MESSAGING| 117|
|373|	WEIGHT MGMT & MOVE! PROG - GRP|	719|	MHV SECURE MESSAGING| 17|
|407|	OPHTHALMOLOGY|	719|	MHV SECURE MESSAGING| 59|
|408|	OPTOMETRY|	719|	MHV SECURE MESSAGING| 993|
|502|	MENTAL HEALTH CLINIC - IND|	719|	MHV SECURE MESSAGING| 7710|
|124|	NUTRITION/DIETETICS-GROUP|	720|	OTHER ED GRP| 2|
|203|	AUDIOLOGY|	720|	OTHER ED GRP| 160| 
|373|	WEIGHT MGMT & MOVE! PROG - GRP|	720|	OTHER ED GRP| 35|
|502|	MENTAL HEALTH CLINIC - IND|	721|	OEND ED IND| 26| 


@ldelacosta The data collected should be reviewed, and logging should be removed if it is no longer necessary.

**Comment by ajmagdub** [comment]
I referenced the wrong GH ticket in the PR.  The Stop code logging is still in place.

**Comment by ldelacosta** [comment]
@ajmagdub - could we get the latest logging for this work. Please let us know when it's ready for review.

**Comment by ajmagdub** [comment]
@ldelacosta here's the latest logging
[2024-02-23-stop-codes.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3FJQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8b06a381f57de769e2d8ebb14afef4ae7314e58e/2024-02-23-stop-codes.xlsx)

**Comment by ajmagdub** [comment]
^^ miss-reference this ticket in the above PR. Stop code logging still in place.

**Comment by ajmagdub** [comment]
Merged changes to stop logging, will go into production on 02/28 Vets API deployment.

**Comment by ajmagdub** [comment]
Changes to remove stop code logging are in production with no issues.

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket. cc: @JRRoof
