### ISSUE TITLE
Work with MHV medications teams to move about-medications page, then remove component from MHV landing page app

### ISSUE THREAD

**Issue by dcloud** [department-of-veterans-affairs/va.gov-team#71276]
## Description

Per [[EPIC]: Move landing page to isolated app build #70837](https://github.com/department-of-veterans-affairs/va.gov-team/issues/70837), we wanted to opt in to app isolation. To expedite this, we _temporarily_ absorbed the `/mhv/about-medications` page, but that page needs to be removed from the MHV landing page app.

*Note*: Migration to Drupal was explored, but the page is behind authentication, and Drupal only supports public pages

### User story

As a Cartographers team member, I want the medication teams's content page to live outside of the landing page app, enabling that team to update their content easily and without dependency on Cartographers

## Acceptance criteria

- Redirects in place for `/my-health/about-medications` to new URL
- Medications app serves the medications landing page
- Medications code is removed from mhv-landing-page app

## Tasks

- [ ]

**Comment by wesrowe** [comment]
Medications team did this work last week and we merged our app-isolation PR on 12/22. Closing.
