### ISSUE TITLE
SOCKS access for [Sean Midgley (desktop work machine)]

### ISSUE THREAD

**Issue by Midge-dev** [department-of-veterans-affairs/va.gov-team#71280]
### Your Name

Sean Midgley

### Your Email

sean.midgley@oddball.io

### Your Role and Team

Frontend Engineer - Non-Disability Experience

### Product Manager (PM) name and email

Laura Steele laura.steele@coforma.io

### Product Owner (PO) name and email

Emily Theis emily.theis@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDTlbYGcaCt8UNu5KlVI94PEtp3HHjk0iV6uHchZKIaJNCIec91IDGSeKDErD0Ua7FdHETRI6MSZqsYlEFkAQZquqtz42FexqyZfN9hivjCnhR4M6pgP1QZRoiOz9s8RrYL6wWzNWO02K5WHFK4IX5yy0Zq6Xm1JD9E959IkoTWM0qDVK1w15qVn6CyYxlACdnjoyJHSIt7sLP1W/yXArBCXHsMao/xiGnKcfnT2eDUyoTNu3z21aNIkN6OywREepNdehUFuUBWJaExIraP9vvZvm1JGCWwfgPzDG5L/N/yBMyIpBWWfwIpn+9WzwagtWUL9pLOjKxrzrVyeUL4LFQHB1Apeu04R8kGn7vNkuTx8RFkjmrESoq+fL5OAKGkSNLqRcEvariTbp8fEkWmn+IqDriTOAFsxt9zXEOfA5afDt9YwioP1JgYpbiDZQRXTS5ipv/jF2B1BHD07ZBaPUzXZyEhgoPsN/QGjWK0rOTss2qweeqfZuImkUPpYtwog7M= midge@blackRock-dev

### E-QIP Transmittal Confirmation

<p>Unable to login to EQIP Account but was able to find the submission receipt</p>
<img width="1007" alt="Screenshot 2023-06-01 at 9 26 09 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/57480791/840a9bb2-c05d-4f85-8f16-57e9ec3988ec">
<img width="1022" alt="Screenshot 2023-06-01 at 9 26 37 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/57480791/62906703-ab81-40be-81ef-d4483921285c">

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by Midge-dev** [comment]
Note: This is another request for my Desktop work machine

**Comment by ph-One** [comment]
Appended new key to existing key. Closing.
