### ISSUE TITLE
[SCREENREADER]: Facility locator is not announcing the current page when there are more than one page of results

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#713]
## Issue
The page numbers are not announcing the current page to assistive device users. They're also not announcing themselves as links because we don't have an `href` attribute on each link. I'd like to improve these links by refactoring the markup a bit. Screenshot and code example attached below.

## Audit Finding
* Note 9, Defect 3

## Acceptance Criteria
* As a screen reader user, I want the current page of results to announce as the current item.
* I also want the other page result links to announce themselves as links.

## Environment
* Windows 10
* IE11 + JAWS
* https://staging.va.gov/find-locations/ (Searched for "Salt Lake City", Community Care, Nurse Practitioner)

## Possible Fixes (optional)
```html
<!-- I'd like to add real URLs so the pages announce as links -->
<div class="va-pagination-inner">
  <ul>
    <li>
      <a aria-current="true" aria-label="Load page 2" class="va-pagination-active" href="real-href-of-links">2</a>
    </li>
    <li>
      <a aria-label="Load page 2" class="va-pagination-active" href="real-href-of-links">2</a>
    </li>
    <li>
      <a aria-label="Load page 3" class="va-pagination" href="real-href-of-links">3</a>
    </li>
  </ul>
</div>
```

## WCAG or Vendor Guidance (optional)
* [Name, Role, Value: Understanding SC 4.1.2](https://www.w3.org/TR/UNDERSTANDING-WCAG20/ensure-compat-rsv.html)
* [Using the aria-current attribute - Tink.UK](https://tink.uk/using-the-aria-current-attribute/)

## Screenshots or Trace Logs
![Screen Shot 2019-07-26 at 2.39.54 PM.png](https://images.zenhubusercontent.com/5ac217b74b5806bc2bcd3fc8/7e995750-e7e0-4982-a87c-0abb52e49613)

**Comment by 1Copenut** [comment]
After discussing breadcrumbs with the VA 508 office, we are going to keep the `aria-current` attribute on proper `<a>` tags, not on list items. We all feel this is the right approach, to have current page links available.

**Comment by mmiddaugh** [comment]
Will keep track of this during UX redesign/MVP

**Comment by mmiddaugh** [comment]
Moved this acceptance criteria to [#4324] and will close this.
