### ISSUE TITLE
Project Kickoff - Estimate Your Benefits Update

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#7132]
## Steps to complete Project Kickoff
- [x] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in #vfs-platform-support in Slack; tag @ Megan Kelley @ AndreaHewitt
- [x] Andrea and Megan will schedule meeting with VSP reviewers and **VA.gov Education** attendees (as listed below)
- [x] VSP <> **VA.gov Education** kickoff meeting completed
- [x] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please bring the following to the kickoff meeting_
- [Link to rough draft of product outline ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/estimate-your-benefits/product-outline.md)
- Explanation of the problem space
- Any other artifacts you have so far
- You **do not** need to prepare a presentation

## Meeting attendees from **requesting team**
- Product Manager (required): **Darrell Neel**
- DEPO Product Lead (required): **Matt Self**
- Entire VFS team (recommended): 
**Will McCormack
   Desiree Turner
   Dan Shawkey
   Amy Knox
   Darla Van Nieukerk
**

## Scheduling
Preferred dates or times: 
03/31:
- 10 - Noon
- 2:30 - 3:30

**Comment by meganhkelley** [comment]
Scheduled 3/31 @ 11 am ET (stacked w/ #7131)

**Comment by mnorthuis** [comment]
Noting that no IA work is needed for this work effort since it is updates to an existing tool that do not impact overall site structure.

**Comment by dneel-bah** [comment]
Project Kick off Collab point completed.
