### ISSUE TITLE
[CST to Lighthouse] Add lighthouse to list of required services

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#71326]
## Background
We use a series of access policies on the backend to restrict who can call our endpoints. This is mostly to avoid situations where we know that errors will occur if the user doesn't meet the criteria for calling the downstream systems (BGS, EVSS, Lighthouse, etc.). We can specify which of these systems the logged-in user needs to have access to in order for them to access our applications. The Claims Status Tool currently grants access to the application to users that meet the requirements to access EVSS or Caseflow, but not to those who have access to Lighthouse. We need to add Lighthouse to the list of required services.

**Note:** This will probably only help a small percentage of users, most users who should be able to access the Claim Status Tool should already be able to

## Value Proposition
* Users who are not able to view claims in the Claim Status Tool because their account is not configured correctly may be able to access the application and view their claims
  * EVSS has more stringent requirements than Lighthouse does, so it is possible that the call to Lighthouse for a list of claims / claim details would succeed where the one to EVSS wouldn't

## Context
This is the [relevant code](https://github.com/department-of-veterans-affairs/vets-website/blob/9daf982/src/applications/claims-status/containers/ClaimsStatusApp.jsx#L137-L144) in `src/applications/claims-status/containers/ClaimStatusApp.jsx`:
```jsx
<RequiredLoginView
      verify
      serviceRequired={[
          backendServices.EVSS_CLAIMS,
          backendServices.APPEALS_STATUS,
      ]}
      user={user}
>
```

We need to add `backendServices.LIGHTHOUSE` to the array passed via the `serviceRequired` prop

**Note:** from looking at [the code](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/user/authorization/components/RequiredLoginView.jsx#L51-L55) for the `RequiredLoginView` component, it appears that users will be able to access the application as long as they have access to AT LEAST one of the services in the list

## Tasks
- [ ] Add `backendServices.LIGHTHOUSE` to the list of required services

## Acceptance Criteria
- [ ] Lighthouse is listed as one of the required services in the Claim Status Tool

**Comment by HeatherWidmont** [comment]
Peri will be working on this ticket, she will review the ticket today

**Comment by HeatherWidmont** [comment]
@samcoforma will review this today

**Comment by jerekshoe** [comment]
I tested this with my production account and the change looks good to me. Great work!
