### ISSUE TITLE
Midpoint Review - Design Feedback - Veteran Facing Forms - form 20-10208

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#71337]
## VFS actions
- [x] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- It would be great to get user testing around that multiple files upload. There is some concern that if they get the warning alert if they do not upload the right amount of files, they make think they did something wrong.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- Should: Order the list of file types. Work with CAIA on content on that order (likely alphabetical). 
- Matt Dingee: I am little confused that we should put related forms in numerical order, I don't think people care too much but it's fine.
- Matt Dingee: I hear that people may not associate the type of form with the form that is uploaded with the current pattern but it seems odd that stake holders would not find that useful. You could use the "What kind of file is this" and change the "other" to let users know they can upload multiple files. Is that a good practice to upload multiple files? We could encourage them not to. Just something to think about.

**Comment by emcruer** [comment]
File types are in alphabetical order; changed the numerical order per the stakeholder's request. Considering upload file type with stakeholder input. 
Moving files to Figma.
