### ISSUE TITLE
[MVP] Step 5 Financial information, income: Create new page and 4 questions for Add an income source, and multi-entry

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#71345]
## Note
Part of the larger effort to update the existing 527EZ form to add missing fields/info and remove depreciated fields.

## Description
On Step 5 of Financial Information: income,

- Create a new page for the new `Add an income source` questions, 4 total
- Include multi-entry option for the same questions
- Include supporting copy that provides examples
- Match all copy to designs

## Designs
- Page examples and user flow: https://www.sketch.com/s/94592459-f741-45a0-9432-efd685b9a1d5/p/CB1B994B-E80B-4F35-AC2E-5E73661CD0B1/canvas

## Acceptance Criteria

**New page:**
1 new page is created under Step 5 of form, this lives under the Financial information: income section.

**Copy and questions for this page:**

Add a sub header that states `Gross Monthly Income`
`We want to know more about the gross monthly income you, your spouse, and your dependents receive.`
`List the sources of income for you, your spouse, and your dependents.`

**Expandable copy:**
When collapsed, the copy shown says: `What is income?`
When expanded, the copy below will show:
`Your income is how much you earn. It includes our Social Security benefits, investment and retirement payments, and any income your spouse and dependents receive.`

Add another sub header that states `Add an income source`

**First question:**
Add the following required radio button question/field:
`What type of income?`
`Social Security`
`Interest or dividend income`
`Retirement income`
`Pension income`
`Other income` - _This option will also have a short text field_

**Second question:**
Add the following required short text question/field:
`Who receives this income? (*Required)`
`Enter your name, or the name of your spouse or one of your dependents.` - _Hint text_

**Third question:**
Add the following required short text question/field:
`Who pays this income? (*Required)`
`Enter the name of a government agency, a company, or another organization.` - _Hint text_

**Fourth question:**
Add the following required dollar/number question/field:
`What's the monthly amount of income? (*Required)`

Add a button for: `Add another income source`

**Please note:** If they have additional income sources, they will the list loop, multi-entry functionality available, as shown on the designs.

**Validation info:**
If they have additional income sources, they will the list loop, multi-entry functionality available, as shown on the designs.

Once they finish adding any additional income sources, the next page/question will be: Did you pay any unreimbursed care expenses?, as shown on https://github.com/department-of-veterans-affairs/va.gov-team/issues/71726

**Match copy:**
Ensure all copy, including headers, questions and buttons match the designs.

## Tasks
[Software Development Tasks](https://docs.google.com/document/d/1vtn5co_YzGl1cFRNrIBAdjf53dmfH4_EXBWK8C5mU9Y/edit?usp=sharing)

- [ ] Front-end work

## Review
- [ ] Someone else on team signed off on pages in staging

## Artifacts
- [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/527EZ-reactivation-initiative-brief.md)
- [User flow in Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683826730324/61b509f935adaa2acf2f7769a5ba911726a7b237?sender=u9d01ee38af217e4877e75660)
- [Prototypes in Sketch](https://www.sketch.com/s/94592459-f741-45a0-9432-efd685b9a1d5/p/CB1B994B-E80B-4F35-AC2E-5E73661CD0B1/canvas)
- [Spreadsheet of deleted form fields](https://docs.google.com/spreadsheets/d/1PTXxO6mFH2ZUK6XxX7iCCQb-NoSvhB5P/edit?usp=sharing&ouid=104362113771391164792&rtpof=true&sd=true)
- [Content source of truth/PDF form](https://www.vba.va.gov/pubs/forms/VBA-21P-527EZ-ARE.pdf)
- [Link to testing accounts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/form-deactivation/527EZ-staging-test-accounts-accessible.md)
- [Link to staging](https://staging.va.gov/)

**Comment by vbellissimo** [comment]
**PDF mapping notes:**

The answer to these questions will map to these fields in the new PDF fields in Section 9:
<img width="899" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkk1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7ed3170230446f8e9e339eea03fa953601f32a12/Screenshot%202023-12-06%20at%2010.20.09%E2%80%AFAM.png" alt="Screenshot 2023-12-06 at 10.20.09 AM.png" />

If there are more than 4 sources total reported by the user, the PDF mapping logic should answer "yes" to question 9G on the new PDF form:
<img width="700" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmM1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d0260b6fbed66ca3c85e2ba04dc74c51bdc41275/Screenshot%202023-12-06%20at%209.37.37%E2%80%AFAM.png" alt="Screenshot 2023-12-06 at 9.37.37 AM.png" />

**Comment by aplatt-coforma** [comment]
Content looks correct.
<img width="532" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemQxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--01b84921c1dc2447b99d1e658136816256b5a58b/Screenshot%202023-12-19%20at%202.52.57%E2%80%AFPM.png" alt="Screenshot 2023-12-19 at 2.52.57 PM.png" />

**Comment by aplatt-coforma** [comment]
I did see a page ordering issue.
As noted in the ticket, the next page should be "Did you pay any unreimbursed care expenses?" page but currently it goes to the direct deposit page. Will add to bug list for triage.
