### ISSUE TITLE
[MVP] Step 5 Financial information, income: Create new page and question for Do you receive income?

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#71341]
## Note
Part of the larger effort to update the existing 527EZ form to add missing fields/info and remove depreciated fields.

## Description
On Step 5 of Financial Information: income,

- create a new page for the `Do you, your spouse, or your dependents receive income?` question
- Include supporting copy that provides examples
- match all copy to designs

## Designs
- Page examples and user flow: https://www.sketch.com/s/94592459-f741-45a0-9432-efd685b9a1d5/p/CB1B994B-E80B-4F35-AC2E-5E73661CD0B1/canvas

## Acceptance Criteria

**New page:**
1 new page is created under Step 5 of form, this lives under the Financial information: income section.

Page sub header states `Gross Monthly Income`

In this page, add the following required radio button question/field:
`Do you, your spouse, or your dependents receive income? (*Required)`

`Your income is how much you earn. It includes your Social Security benefits, investment and retirement payments, and any income your spouse and dependents receive.`

`Yes`
`No`

**Validation info:**
_If they answer yes_, the next page/question will be: Add an income source, as shown on #71345

_If they answer no_, the next page/question will be:  Did you pay any unreimbursed care expenses?, as shown on #71726

**Match copy:**
Ensure all copy, including headers, questions and buttons match the designs.

## Tasks
[Software Development Tasks](https://docs.google.com/document/d/1vtn5co_YzGl1cFRNrIBAdjf53dmfH4_EXBWK8C5mU9Y/edit?usp=sharing)

- [ ] Front-end work

## Review
- [ ] Someone else on team signed off on pages in staging

## Artifacts
- [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/527EZ-reactivation-initiative-brief.md)
- [User flow in Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683826730324/61b509f935adaa2acf2f7769a5ba911726a7b237?sender=u9d01ee38af217e4877e75660)
- [Prototypes in Sketch](https://www.sketch.com/s/94592459-f741-45a0-9432-efd685b9a1d5/p/CB1B994B-E80B-4F35-AC2E-5E73661CD0B1/canvas)
- [Spreadsheet of deleted form fields](https://docs.google.com/spreadsheets/d/1PTXxO6mFH2ZUK6XxX7iCCQb-NoSvhB5P/edit?usp=sharing&ouid=104362113771391164792&rtpof=true&sd=true)
- [Content source of truth/PDF form](https://www.vba.va.gov/pubs/forms/VBA-21P-527EZ-ARE.pdf)
- [Link to testing accounts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/form-deactivation/527EZ-staging-test-accounts-accessible.md)
- [Link to staging](https://staging.va.gov/)

**Comment by vbellissimo** [comment]
Hi @TaiWilkin . I saw that you're working on this. Wanted to let you know that I added more info to the form flow validation.

_If they answer no_, the next page/question will be:  Did you pay any unreimbursed care expenses?, as shown on #71726

**Comment by aplatt-coforma** [comment]
Content looks good.
<img width="638" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEoxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4d0a158a01aed178750753834c5ccb5ea65398dc/Screenshot%202023-12-19%20at%202.57.55%E2%80%AFPM.png" alt="Screenshot 2023-12-19 at 2.57.55 PM.png" />

**Comment by aplatt-coforma** [comment]
If Yes is selected the form correctly flows to the "Add an income source" page but if No is selected, it goes to the direct deposit page instead of the "Did you pay any unreimbursed care expenses?" page as noted in the ticket. I'll add it to the bug list page.
