### ISSUE TITLE
Change copy on Appts homepage under the "Create a new appointment" header

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#7136]
We need to update the copy on the View Appts homepage where the 'Create a New Appointment' CTA is located. 

Change this copy "Schedule an appointment at a VA medical center, clinic, or Community Care facility."
![Screen Shot 2020-03-23 at 5.15.23 PM.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/46a92e4a-ab97-4d6d-a3e4-974f2ceb586b)

**Update copy to:**
**Send a request to schedule an appointment at a VA medical center or clinic.**

**Comment by lenaecb** [comment]
@peggygannon - can you confirm my suggested copy above? We found one more small spot in the app that needs updating.

**Comment by peggygannon** [comment]
@lenaecb @jbalboni Please see below for recommended copy. I wanted to keep "schedule" in the sentence b/c the CTA button right below it says "Schedule" 

Send a request to schedule an appointment at a VA medical center or clinic.

**Comment by lenaecb** [comment]
Thanks @peggygannon 

I have updated the ticket with this feedback
