### ISSUE TITLE
Remove eMIS Health Check from fwdproxy after Transition to VA Profile

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#71378]
## Description

After our recent meeting with the eMIS team and transitioning traffic from eMIS to VA Profile via Vets API, we observed a significant drop in traffic. However, it's noted that there are still residual calls being made to eMIS from va.gov. It's suspected that these calls might be originating from our health check mechanism in the fwdproxy.

As part of the final phase of our migration to VA Profile, we should consider removing the eMIS health check from the fwdproxy configuration. This action is crucial to prevent any unintended eMIS calls post-migration and to ensure a clean cut-over to the VA Profile system.

### Action Items

- [x] Investigate the current eMIS health check calls in the fwdproxy to confirm their origin.
- [x] Plan the removal of the eMIS health check from the fwdproxy configuration.
- [x] Implement the changes in the fwdproxy configuration to remove the eMIS health check.
    - Refer to the current health check configuration in the fwdproxy: [fwdproxy config](https://github.com/department-of-veterans-affairs/devops/blob/de5e40f89807e895f2f5042059ac46c81fbb1b61/ansible/deployment/config/fwdproxy-vagov-prod.yml#L153-L164).
- [x] Conduct thorough testing post-removal to ensure no unintended impacts on system functionality.
- [x] Monitor the system post-removal for any unexpected behavior.

### Acceptance Criteria

- The eMIS health check is fully removed from the fwdproxy configuration.
- No residual eMIS calls are observed post-removal.
- The system maintains stable operation and performance post-change.

**Comment by rmtolmach** [comment]
In a screenshot Fred shared with us, the path that was still being called when we turned the flipper on in prod was `/VIERSService/eMIS/v1/MilitaryInformationService?wsdl`, which is the `check_path` listed in the fwdproxy config. I have PR https://github.com/department-of-veterans-affairs/devops/pull/13779 to remove it, but I will check with the devops CoP to confirm.

_note: once we're completely done with eMIS, we'll want to remove the entire fwdproxy config for emis. I will add that to a ticket or create a new ticket._

**Comment by rmtolmach** [comment]
PR is merged. I will have Fred check emis calls to dev and staging after 4:15pm, which is when the fwdproxy deploy usually finishes.

**Comment by laineymajor** [comment]
dev and staging are done
sandbox will go out around 4:00 today

to our devops friends.. can we deploy this to sandbox now?
- we should check with kyle (he has a number of monitors set) --- @rmtolmach to checkin (cc Chris)

**Comment by laineymajor** [comment]
This can be closed once we get confirmation from Fred.
We will also need to do this for prod.

**Comment by laineymajor** [comment]
Need to wait until we are able to do this for prod before closing. Waiting until EOD Monday... then will review for closing.

**Comment by rmtolmach** [comment]
PR for prod eMIS health check removal: https://github.com/department-of-veterans-affairs/devops/pull/13811

This health check is specifically for the `MilitaryInformationService`. Since the military information is calling VA Profile, this health check is ready to be deprecated.

**Comment by laineymajor** [comment]
Waiting until end of the day (and confirmation from Fred) before closing.

**Comment by rmtolmach** [comment]
Screenshot from Fred. You can see all connections are at zero after the fwdproxy deploy this morning. Times in the graph are central time.
<img width="1541" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXB0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--73c993989b8639c6a489c80d96e82014504b3adc/Screenshot%202023-12-18%20at%2011.37.30%20AM.png" alt="Screenshot 2023-12-18 at 11.37.30 AM.png" />
