### ISSUE TITLE
[Code Yellow] Pass along locations for controllers in Sidekiq jobs

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#71383]
## Issue Description

---
## Tasks
- [ ] Matt to pass along locations for controllers in Sidekiq jobs
- [ ] Reach out to Steve Albers for clarification on this request.

**Comment by mjknight50** [comment]
This was already covered in https://github.com/department-of-veterans-affairs/va.gov-team/issues/71382
