### ISSUE TITLE
[Code Yellow] Review of watch tower alerts for Code Yellow

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#71382]
## Issue Description
- 30-minute meeting with Steve Albers about this

---
## Tasks
- [x] Schedule 30-minute meeting with Steve Albers about this. **Meeting is scheduled for Friday, Dec. 8**
- [x] Document any meeting takeaways

**Comment by vbellissimo** [comment]
**3 monitors, watch tower alerts set up for Pension in Datadog:**
1. Pension errors
2. Pension traffic is low
3. Sidekiq exhaustion for Central Mail Submit claim job

**Will these become too noisy? We can revisit this.**
- **Watch tower officer should be looking at @benefits-alerts-notification for alerts.** Use this Slack channel to review alerts

**For Sidekiq exhaustion for Central Mail Submit claim job:**
- End of December, beginning of January 2024 we will revisit if we've captured things properly.
- We will need to re-set this up that will be using Lighthouse Benefits Intake API
- No alerts have ever set off for this monitor; Pension form is offline?
- When form goes live, if these alerts go off, watch officer will look in Slack and ping the team about any issues.
- If monitors are going off too much, and it's non-actionable time, we should revisit and adjust the monitors.

cc @mjknight50 @TaiWilkin feel free to add any notes you'd like on here. Thanks.

**Comment by mjknight50** [comment]
Just reviewed this ticket and confirmed that it looks good.
