### ISSUE TITLE
Remove reference to CC in VAOS sign in widget

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#7138]
## User story

We need to update the VAOS sign in widget to remove references of Community Care appointments. 

-------

UPDATED sign-in widget copy below: 

{box copy}
Go to the VA appointments tool to view, schedule, or cancel your appointment online 
You'll be able to manage and see all your appointments in one place on VA.gov. You can also schedule or cancel some VA appointments online.
{button} Go to your VA appointments(schedule-view-va-appointment/appointment)

**Comment by rtwell** [comment]
lgtm!

**Comment by lenaecb** [comment]
Looks good!
