### ISSUE TITLE
Configure CodeQL on new repo

### ISSUE THREAD

**Issue by mateoclarke** [department-of-veterans-affairs/va.gov-team#71397]
This task comes from the VA code scanning team. They created a PR for us to fill in some blanks:

https://github.com/department-of-veterans-affairs/va-in-person-identity-proofing/pull/3#pullrequestreview-1766654755

**Comment by mateoclarke** [comment]
A related issue that was created on our repo:
https://github.com/department-of-veterans-affairs/va-in-person-identity-proofing/issues/5

**Comment by lmorris3** [comment]
Closing this ticket - created erroneously (issue resolved with onboarding). Code QL is currently running.
