### ISSUE TITLE
Design | Enhanced Military Information | Updated Lo-Fi Mocks

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#71403]
## Background
We had a [call with VA Profile ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/military-information/2023-enhanced-military-information/meeting-notes/2023-12-06-data-sync.md)around the data quality we're seeing returned from VADIR.

[In our mural we've layed out some lo-fi designs ](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1697125319596/c13810c02c96a58a4b6b72288c6b9a8d617f711a?sender=uaa72d11015d3f7c704a64191)and should refresh those designs to display our latest understanding of the world:

### What we should show:
- Enhance the Branch of service/dates served section to reflect duty status (active, reserve etc)
     - example w/two branches with active and inactive examples under both and reserve period for one of them (dealer's choice!) 
- show military occupation 
     - 2 occupations (dealers choice, 2 as a min)
- show deployment location(s) and dates (again dealer's choice lets play around w/the quantities of locations) 
     - Account for cases where we have none of this information available for a record

### What we should remove:
- military unit, unfortunately the data quality isn't great in the BE. 
- deployment project text and dates 

### Things we'll need to unravel 
- how do multiple periods of service across multiple branches appear
- multiple occupations 
- handling all the DVU's and explaining missing data elements

#### curious to see different layouts to think about what it might look like to toggle between branches of service: 
question here is, if i was in the navy and then later in the army i wouldn't want to see my service locations combined across the periods of service because that would break apart some of the context

Given a user with multiple branches of service, 
When they open the screen 
Then display two separate sections

Given a user with multiple branches of service, 
When they open the screen 
Then display tabs for each 

^^^ just two ideas, totally open for whatever ideas you have 

## Acceptance Critera 
- [ ] new mocks in our [mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1697125319596/c13810c02c96a58a4b6b72288c6b9a8d617f711a?sender=uaa72d11015d3f7c704a64191) that give us some additional options to talk about given the updated [MVP data elements](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/military-information/2023-enhanced-military-information/enhanced-military-info-mvp.md#mvp-data-elements)

**Comment by andaleliz** [comment]
@mtcA6 this must've come out of planning after I left, thanks for writing it up. I have a few questions:

>2 occupations

How did we land on the number 2? Was there any discussion about which two? One example of prod data we looked at had 23 entries.

>question here is, if i was in the navy and then later in the army i wouldn't want to see my service locations combined across the periods of service because that would break apart some of the context

The military info page is already set up to separate periods of service and branches. Is there something about the existing layout that the team sees as problematic for this?  For an MVP, it makes sense to me to build upon the structure we already have in place where possible, and I think in this case it could be as simple as displaying the countries associated with each period of service as children of that period of service somehow.

> new mocks in our mural board that give us some additional options to talk about given the updated MVP data elements

☝️ That is from the AC.  What are you hoping the outcome will be once we talk about them?

Thanks!

**Comment by andaleliz** [comment]
@mtcA6 thanks for helping me understand your thinking behind the ticket.  The progress we've made so far doesn't really change the lo-fi mock-ups/explorations we've already done very much.

I'd still recommend adding a button to reveal details to our current page ([shown here](https://www.sketch.com/s/fc96664a-1c62-40ed-9fcd-90218c54e775/v/llrqOv/a/mPwDY3k)) and then putting the MOS and locations in the revealed detail view ([shown here](https://www.sketch.com/s/fc96664a-1c62-40ed-9fcd-90218c54e775/a/mP0k2rL)).  I updated the detail view to show what it will look like based how we've updated the MVP data elements.

That approach won't work well if we learn that all the places we're seeing repetition are actually unique instances. In that case, I think we'll need a link instead of a button and a dedicated page for each period of service.  That's far more complicated though, and we don't have enough information to justify that exploration right now.

Closing this out since the mocks have been updated with the new MVP data points.

**Comment by mtcA6** [comment]
@andaleliz you included units in the mocks can we remove that? I have other questions as well, will share those soon


![Image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/a94782ba-4a67-46e5-b6c6-a174d287d829)

**Comment by andaleliz** [comment]
Adding a note here, Travis and I chatted via DM and clarified which screens were updated to remove units.  The mock-ups for this ticket do not include units.

**Comment by mtcA6** [comment]
Added a [section to the mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1697125319596/c13810c02c96a58a4b6b72288c6b9a8d617f711a?wid=21-1702319072538) and worked through it with Alex; can you share access with her, I tried and cannot, she's working on VA Mural access but you as the owner should be able to grant her a6 email edit access while that process plays out. 

I'm keen to have all of us (FE, BE, Design, Product) collaborate and discuss the designs. I'm interested in hearing any FE considerations or BE insights based on the data, or thoughts that might come up about how to structure the API given the designs etc etrc etc.

I'm going to share that section of the mural ahead of our call tomorrow so we can collaborate in person.

**Comment by andaleliz** [comment]
@mtcA6 I'm having a delayed reaction to your comment - sorry I didn't catch this earlier.  

>I'm keen to have all of us (FE, BE, Design, Product) collaborate and discuss the designs. I'm interested in hearing any FE considerations or BE insights based on the data, or thoughts that might come up about how to structure the API given the designs etc etrc etc. I'm going to share that section of the mural ahead of our call tomorrow so we can collaborate in person.

I thought our call today was to prep for the meeting with Melissa, but what you're suggesting sounds more like a working session or almost a workshop kind of thing.  Should we set up a separate time to go through this collaboration session you're hoping for?

**Comment by andaleliz** [comment]
@mtcA6 is it OK to close this out now?
