### ISSUE TITLE
Fix missing required fields on add-child workflow

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#7141]
## Goal
When working on the add-child workflow we missed a few required fields and we need to make these fields required.

## Considerations
- [Mockup](https://xd.adobe.com/view/0430be78-21b6-46e2-68b0-586c650d77c8-7201/screen/7177f4d5-995e-4906-ad80-1d7fe4e9e08e/Apply-Dependents-Add-Child-2)
- [Slack Convo](https://adhoc.slack.com/archives/DMJHVAEBB/p1585002206034400)
- The function used for ui:required for first name, last name, and for the address fields shouldn’t be based off of whether or not the chapter is required, and instead be based off of the yes/no ("Does child live with you?") question asked initially on the page.
- Other fields that need to be made required:

```
In child-place-of-birth.js: childPlaceOfBirth.city, childStatus, childPreviouslyMarried, and childPreviouslyMarriedDetails.reasonMarriageEnded, and childPreviouslyMarriedDetails.otherReasonMarriageEnded
```
reasonMarriageEnded can be the same as the field above it:
```
'ui:required': (formData, index) =>
              formData.childrenToAdd[`${index}`].childPreviouslyMarried ===
              'Yes',
```
and then `otherReasonMarriageEnded` needs to be required based on the answer to `reasonMarriageEnded`

## Tasks
- [ ] Update the required fields

## Acceptance Criteria
- [ ] The fields are updated and a PR has been successfully merged

**Comment by jason-gcio** [comment]
🎉
