### ISSUE TITLE
Update LOA3 error component on intro page

### ISSUE THREAD

**Issue by rachelshearerux** [department-of-veterans-affairs/va.gov-team#71425]
Users who are authenticated at LOA1/LOA2 when they land on the intro page need to understand they cannot request their records until their identity is verified.

Another team helped to [flag an experimental design component](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2284) that's recommended to communicate with folks who are authenticated but still need to verify their identity to achieve LOA3. 

<img width="1806" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejA4QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--94b862480bace9dd0ab636380b4dc0b8f1831f6d/LOA3%20error%20Change.png" alt="LOA3 error Change.png" />

---
**Definition of Done:**
- [x] Update the component to '[sign-in-or-tool-prompt](https://design.va.gov/storybook/iframe.html?id=components-va-alert--sign-in-or-tool-prompt&viewMode=docs#sign-in-or-tool-prompt)'
- [x] H3: You'll need to verify your identity to request your records
- [x] Body: We need to make sure you’re you — and not someone pretending to be you — before we can give you access to your personal  information. This helps to keep your information safe, and to prevent fraud and identity theft. **This one-time process takes about 5-10 minutes.**
- [x] CTA: { Primary action link } Verify your identity
- [x] URL target: https://www.va.gov/verify. After they're verified, the page should redirect them back to the intro page where they can then start the request:
`        <a
          href={`/verify?next=${pathname}`}
          className="verify-link vads-c-action-link--green"
        >
          Verify your identity to start your request
        </a>`
- [x] confirm in staging

**Docs**
-[ Source of truth](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/20-10206%20FOIA%20PA%20Request/source-of-truth.md)
- [Sketch](https://www.sketch.com/s/314e6dbf-5b4a-422d-beb1-0ad599fc3af1/v/4Z94zz/p/D2736869-8F0B-4244-AB27-F7EBFDE853EB/canvas/)
- [Experimental design ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2284)
- [Storybook component](https://design.va.gov/storybook/?path=/docs/components-va-alert--sign-in-or-tool-prompt#sign-in-or-tool-prompt)

**Comment by tlei123** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-website/pull/27092) opened.

**Comment by tlei123** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-website/pull/27092) merged &mdash; changes should be in Staging by ~4:45 PM ET.

**Comment by tlei123** [comment]
@tbaker1026 @rachelshearerux @jeana-adhoc , changes are now [in Staging](https://staging.va.gov/records/request-personal-records-form-20-10206/introduction), ready for validation.

**Comment by rachelshearerux** [comment]
Looks great to me, @tlei123, thank you! 

<img width="557" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzliQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0eae9da194ca56120e37fe8cb8bc6dbbd90c9ef2/Screenshot%202023-12-13%20at%205.25.22%E2%80%AFPM.png" alt="Screenshot 2023-12-13 at 5.25.22 PM.png" />

This is a note just for the sake of documentation: since the content for LOA3 has been back and forth this last week - this is not the final state. We intend to update content per feedback from SWCAIA, the details are all captured [here](https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team/71919).
