### ISSUE TITLE
Access for Clarence Maeng

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-team#7143]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your name.
   > Clarence Maeng
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > CMS, Delivery Manager, Agile Six
- [if requesting SSH key authorization] What is the **public** SSH key?

```
ssh-rsa
AAAAB3NzaC1yc2EAAAADAQABAAABAQDItR+LhN3TI7PT3bpXnu8LMOPJSJc96zvzwjOR6E8ghVuWjgAkiec+bjKijXBFJqX3M9bOWfJoAZfuyXn0CSrYiQn0m00o8NE7ZoKuUDSEw7Y8EzRtlx0xaCHWp+ldbN23b1/5krJepcnqRnt8i4fy8lp8845xwmZ5UEWXGOy3lZ1QYc1zZS9IFULEr01VB3NHTnsj8WX50GGqHZ/w/eBYiXensvM4ipE6l7ccK07IRV+689TRe4+pO0/bah6PgYTNQFkKaYPweR125ejYLAZrjUN4czjOr2GO+4pcr/0D2Rr5Z/SyZ+j4gQksh/JFOhx7t9K040BX6YxiI9NpECD5 cjmaeng@Agile6-A33
```

- [Grant AWS Console access?]
  > NO
  >  Please give a brief description for why you are requesting AWS access.

**Comment by benniemosher** [comment]
PR has been merged. https://github.com/department-of-veterans-affairs/devops/pull/6569

**Comment by ricetj** [comment]
> PR has been merged. [department-of-veterans-affairs/devops#6569](https://github.com/department-of-veterans-affairs/devops/pull/6569)
> 
> @ricetj should I move this to completed or wait to verify it worked?

Nope, we can close if the job ran and point them to the next piece of the docs on the config.
