### ISSUE TITLE
Add separation between search results and "Need help?"

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#71433]
As advised by Design, it's best to have a line separating our search results from the "Need help?" section below, regardless of if those search results include pagination.

Current state:
<img width="1833" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVU4QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c84d6eda40410942dc77525fe993e021defbb465/image.png" alt="image.png" />

Design recommendation:
<img width="1681" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVE4QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0b76a6ed83e9e04100f2c1c9450255a35a6bb9df/image.png" alt="image.png" />

### Tasks

- [ ] Add a line to separate the search results from the "Need help?" section below

**Comment by cosu419** [comment]
I understand that there should be a line after the last result of a non-paginated list. For paginated results, should there be two lines? One after the last result, one after the pagination controls? Wondering if it looks awkward to use the same <hr> element for delineating individual results as well as for delineating page sections. 

Can style the lines differently, or push the footer down a bit for better separation.

Option 1:
<img width="1186" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVYwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--275de5edfa1475ffcd10411c0676ab658fe781bb/image.png" alt="image.png" />

Option 2
<img width="1162" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVowQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5d215eb0477aaf7d5f69a8ed1262de09dec4d50a/image.png" alt="image.png" />

**Comment by oddball-lindsay** [comment]
@mtri check out the options above - what would you advise? (need to view in Zenhub for images to render)

**Comment by mtri** [comment]
@cosu419 Is it possible to just always have a line after the final result? No line is needed after the pagination:

<img width="1780" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmw0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a31fb7a5eaa36a0b628f701bbf90742f1e26a571/Screenshot%202023-12-20%20at%209.01.00%20AM.png" alt="Screenshot 2023-12-20 at 9.01.00 AM.png" />


& can we style the line the same way as on the facility locator? It looks like the grey is slightly lighter in that tool. That should help a bit too. Color of the line would go from #aeb0b5 to #d6d7d9.
