### ISSUE TITLE
Accessibility feedback for Profile 2.0 Usability Testing Prep

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#7144]
**Please note:** VSA and VSP feedback is provided separately below in this review.

**Feedback framework**
- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## VSA feedback
```diff
! Will supplement when the Connect Apps screens are added. 
! Please let us all know in a comment on the epic.
```

### Must
1. Focus management - Where is focus after the profile info is updated?
1. Context change - It is confusing when the mobile sub nav is updated, and there is no update onscreen. Since this is an existing design system component, I don’t think we can do anything. Ideally, I’d like to see an update such as “Profile Menu > Direct Deposit” appear in the closed view. For accessibility, we **must** have a context change notification — does that already exist for the component?

### Consider
1. The mobile data presentation with the Edit link beneath the info is easier for proximity. **Consider** having address all on one line, with Edit beneath on desktop.
1. Under Mobile number the checkbox for “We’ll send VA health care appt text…” seems confusing from the user POV. Consider the user POV for this interaction.
1. Research plan

    1. Consider asking for half enlisted, half officer service background
    1. Consider requesting 3 participants with 70% disability rating, at least one with identified cognitive disabilities (such as TBI, PTSD, etc)
    1. I was initially curious about the ask for a person of color, as I usually go about it through other methods, but upon reflection I believe I understand the goal. I love the dedication to ensuring inclusion. Thank you! It's so important. 

### Must
* Label the `Edit` and `Update` buttons with descriptive labels for assistive technology. There are two ways to do this. I prefer the second option because it translates when users change language using their browser, but am okay with the first, because we're only supporting English at this time.

  ```html
  <button aria-label="Edit mailing address">
    Edit
  </button>
  ...
  <button>
    <span aria-hidden="true">Edit</span>
    <span class="usa-sr-only">Edit mailing address</span>
  </button>
  ```
* Provide an `aria-hidden="true"` on the green check so it's not a tab stop for screen readers.

### Should
* Define what kind of structure you're thinking for the profile "sections". They're not quite cards, but not quite tables either. I'm thinking they could be description lists, maybe something like:

  ```html
  <dl>
    <dt>Mailing address</dt>
    <dd>
    	<div>
        1234 Anywhere Drive,
        Anytown, MA 00000
      </div>
      <button aria-label="Edit mailing address">Edit</button>
    </dd>
  </dl>
  ```
* Make the phone numbers links in the "What if my military information doesn't look right?" Learn more accordion on Military information view.
* Review alt text for the check routing number, account number, check number with research participants. This will heavily affect partial, low, or non-sighted users, so I want to make sure we get this right.
* Identify how and when you'd like the alert box messages to announce themselves. The alerts for military information not being available and/or information updates taking a long time could be `role="alert"` so they announce to screen readers immediately, if they warrant that kind of attention. I'll leave it up to the design team for the right aural experience.

### Consider
* Switching order of the user name "banner" and the breadcrumbs. This service icon, name and branch, feel like a `<section>` that needs to be its own landmark in the HTML structure. It's also somewhat disjointing to have the dark blue, band of white for breadcrumbs, then the band of dark gray.
* Moving the "Learn More" accordions right underneath their respective header. For instance on Military Information, moving "What if my military information doesn't look right" directly under the Service awards header. That feels like a better fit to let users self-direct an answer before committing to editing their information, then finding the learn more after.
* Consider moving the checkbox for sending or not sending text messages to the mobile address into the `Edit` form. Having one form element in a page of read-only elements could be unexpected.

## Definition of done
1. Acknowledge each feedback item with decisions made
2. VSA Accessibility Specialist will close ticket

**Comment by andaleliz** [comment]
This is no longer relevant and can be closed.
