### ISSUE TITLE
[Analytics] [FE] Append GA event with a 45MR param in check in

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#71440]
## Description 

The goal is to be able to track click events in check in, separately, based on how the user initiated the check in process. Therefore, we can use the same click events that we have now to represent when a Veteran initiates from texting "check in," and the 45 MR could use a pattern that appends something to the GA event. E.g., API Request - day-of-get-current-session-dob - started - 45MR

This would allow us to know why the 45 MR flow has a lower percent check in success rate. 

- How many times did someone start ID verification from a 45MR? 
     - Current: API Request - day-of-get-current-session-dob - started
- How many times did someone succeed ID verification from a 45MR? 
     - Current: API Request - day-of-get-current-session-dob - success
- How many times did someone fail ID verification from a 45MR? 
     - Current: API Request - day-of-get-current-session-dob - failed 
- How many times did someone succeed (API check in request) in a check in from a 45 MR? 
     - Current: API Request - check-in-user - success
- How many times did someone fail (API check in request) in a check in from a 45 MR? 
     - Current: API Request - check-in-user - failed
- How many times did someone select Yes or No to contact info for 45 MR? 
     - Current: nav-check-in-yes-to-demographic-information-clicked
     - Current: nav-check-in-no-to-demographic-information-clicked
- How many times did someone select Yes or No to emergency contact info for 45 MR? 
     - Current: nav-check-in-yes-to-emergency-contact-clicked
     - Current: nav-check-in-no-to-emergency-contact-clicked
- How many times did someone select Yes or No to NOK info for 45 MR?
     - Current: nav-check-in-yes-to-next-of-kin-clicked
     - Current: nav-check-in-no-to-next-of-kin-clicked
- How many times did someone select Agree to These Terms or File Later for 45 MR? 
     - nav-check-in-agree-to-these-terms-review-claim-clicked (feel free to adjust) 
     - nav-check-in-file-later-review-claim-clicked (feel free to adjust) 

## Tasks

- [ ] Hook up GA events to API calls and button clicks

**Comment by loripusey** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/71440?planning-poker) with Zenhub @brianseek

**Comment by wullaski** [comment]
- How many times did someone start ID verification from a 45MR? 
     - Current: API Request - day-of-get-current-session-dob - started
- How many times did someone succeed ID verification from a 45MR? 
     - Current: API Request - day-of-get-current-session-dob - success
- How many times did someone fail ID verification from a 45MR? 
     - Current: API Request - day-of-get-current-session-dob - failed 
     
@benbrasso-agile6 These events won't be possible since we don't know if the veteran came from a 45MR text until we make the call to get the appointments.

**Comment by loripusey** [comment]
@benbrasso-agile6 do you want to validate this?

**Comment by benbrasso-agile6** [comment]
Will do

**Comment by benbrasso-agile6** [comment]
@wullaski @brianseek how do I test this? Do we know if the 45MR will send for staging? I mean, I tried it, and I didn't receive anything. Thoughts on how to verify? Want to show screenshots of the actions from console?

**Comment by benbrasso-agile6** [comment]
Will consider this validated for now. I'll have to revalidate once I create the widget in GA once travel is turned back on.
