### ISSUE TITLE
[MVP] Step 6 Direct deposit and upload docs: Make sure Contact Info is no longer in this step

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#71443]
## Note
Part of the larger effort to update the existing 527EZ form to add missing fields/info and remove depreciated fields.

## Description
Step 6 of the form should be for the user to:
- enter direct deposit information
- aid/attendance/housebound benefit info (read only)
- upload supporting documents

During prior updates done to the form flow, the **Contact Information** that lived in this step was moved to Step 1 of the form.

**We need to make sure that the Contact Information that was moved to Step 1 of the form is no longer repeated on this step of the form (Step 6).**

## Designs
_- None available at the moment for Step 6. If in doubt, please double check with Maya Carroll on this._

## Acceptance Criteria

- Step 6 of the form will no longer ask the same Contact Information questions/fields that were shown already on Step 1 of the form.

## Tasks
[Software Development Tasks](https://docs.google.com/document/d/1vtn5co_YzGl1cFRNrIBAdjf53dmfH4_EXBWK8C5mU9Y/edit?usp=sharing)

- [ ] Front-end work

## Review
- [ ] Someone else on team signed off on pages in staging

## Artifacts
- [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/527EZ-reactivation-initiative-brief.md)
- [User flow in Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683826730324/61b509f935adaa2acf2f7769a5ba911726a7b237?sender=u9d01ee38af217e4877e75660)
- [Prototypes in Sketch](https://www.sketch.com/s/94592459-f741-45a0-9432-efd685b9a1d5/p/CB1B994B-E80B-4F35-AC2E-5E73661CD0B1/canvas)
- [Spreadsheet of deleted form fields](https://docs.google.com/spreadsheets/d/1PTXxO6mFH2ZUK6XxX7iCCQb-NoSvhB5P/edit?usp=sharing&ouid=104362113771391164792&rtpof=true&sd=true)
- [Content source of truth/PDF form](https://www.vba.va.gov/pubs/forms/VBA-21P-527EZ-ARE.pdf)
- [Link to testing accounts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/form-deactivation/527EZ-staging-test-accounts-accessible.md)
- [Link to staging](https://staging.va.gov/)

**Comment by TaiWilkin** [comment]
@vbellissimo I reviewed this section and it appears that we've already removed the Veteran's contact information request from Chapter 6.

**Comment by vbellissimo** [comment]
Thanks, @TaiWilkin ! I'll move this over to the completed column.
