### ISSUE TITLE
[MVP] Implement/confirm claim submission date appears on Pension PDF form

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#71456]
## Issue Description

We need to confirm (and/or implement if it's not happening already) that we populate the following 2 PDF form fields with the **date the online form was submitted (not the date it was created)**. 
- **The VA date stamp field.** Found in the upper right corner, before Section I of the PDF form. See [page 8 of the PDF](https://www.vba.va.gov/pubs/forms/VBA-21P-527EZ-ARE.pdf).
- **The signature line field.** Found in Section XII of the PDF form. See [page 14 of the PDF](https://www.vba.va.gov/pubs/forms/VBA-21P-527EZ-ARE.pdf).

**Please note:** the date should be the date the form was _**submitted**_, not the date the form was created

**Date stamp field:**

<img width="942" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDFBQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--116ad65e8c1db9583909535abc37cf6edadfd762/Screenshot%202023-12-07%20at%2011.21.27%E2%80%AFAM.png" alt="Screenshot 2023-12-07 at 11.21.27 AM.png" />

**Signature field:**

<img width="942" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDVBQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--446dfcf1361983a0e32a4196c246d06d7b278a13/Screenshot%202023-12-07%20at%2011.22.18%E2%80%AFAM.png" alt="Screenshot 2023-12-07 at 11.22.18 AM.png" />

Additional example from Emily
![MicrosoftTeams-image (17)](https://github.com/department-of-veterans-affairs/va.gov-team/assets/3513353/7b84ca79-38d1-4ae0-bb3d-bae0ec6695f9)

---
## Acceptance Criteria
- [ ] Confirm the date the form was submitted (claim submission date) populates to the "VA Date Stamp" field on the Pension PDF
- [ ] Confirm the date the form was submitted (claim submission date) populates to the "Date Signed" 12C field on the Pension PDF
- [ ] Ensure all submitted claims receive date stamps

**Comment by danlim715** [comment]
The date stamp is generated as per the attached sample document. The signed_at date implementation will be part of the section 12 data mapping ticket.

[sample_stamp.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBME9ZQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5a065f50ea49d1dac519380fc54c59dbfc545866/sample_stamp.pdf)
