### ISSUE TITLE
[Assistive tech and device support] UI components initiate a change of context when they receive user input. (11.13.1)

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#71472]
#### VFS team name
Accredited Representation Management Team

#### VFS product name
Find a Representative (MVP)

#### Point of Contact/Reviewers
Brian DeConinck - @briandeconinck - Accessibility

*For more information on how to interpret this ticket, please refer to the [Anatomy of a Staging Review issue ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Anatomy-of-a-Staging-Review-Issue-ticket.2060320997.html) guidance on Platform Website.

---

### Platform Issue
UI components initiate a change of context when they receive user input.

### Issue Details
When sorting the results, the results are sorted and focus immediately moves to the "Showing..." message as soon as a user makes their selection. This includes when a keyboard user tabs to the dropdown and arrows down through the options (without opening the dropdown first).

This is a change of context that users might not be expecting --- especially screen reader users who may be used to arrowing through dropdowns without specifically opening the dropdown first. (The advantage to opening a dropdown first is being able to see all of the options.) 

### VA.gov Experience Standard
[Category Number 11, Issue Number 13](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

### Other References
WCAG SC 3.2.2_A

### Platform Recommendation
Trigger the sort function using a Sort button after the dropdown. It's an extra step, but it makes the action deliberate and prevents an accidental change of context.

---

### VFS Guidance

- Close the ticket when the issue has been resolved or validated by your Product Owner
- If your team has additional questions or needs Platform help validating the issue, please comment on the ticket
- Some feedback provided may be out of scope for your iteration of the product, however, Platform's OCTO leadership has stated that all identified issues need to be documented and it is still your responsibility to resolve the issue.
- If you do not believe that this Staging Review issue ticket is the responsibility of your team, comment below providing an explanation and who you believe is responsible. Please tag the Point of Contact/Reviewers. Governance team will research and will follow up.

**Comment by mtri** [comment]
This has been updated in the new version of design.
