### ISSUE TITLE
SecRel Onboarding

### ISSUE THREAD

**Issue by lmorris3** [department-of-veterans-affairs/va.gov-team#71489]
To Dos:

- [x] Add va-tornado-svc GitHub user account to repo (Must have admin access)
- [x] Add lhdibot GitHub user account to repo (Must have admin access)
- [x] Submit GitHub Ticket
- [x] Pull request is created by team Tornado should be modified as necessary and then be merged in
- [ ] Pipeline configurations (optional)
- [ ] Gate Checks (optional)

Acceptance Criteria:

- [ ] A pull request is created by team Tornado
- [ ] The pull request should be merged with the necessary changes
- [ ] Access to SecRel Tools
- [ ] Aqua and Snyk scans should occur in GitHub Actions

**Comment by rdvyas** [comment]
MO worked with LHDI Owls team to complete the Onboarding to SecRel. This is noted in the ticket below:

https://github.com/department-of-veterans-affairs/lighthouse-tornado-secrel-pipeline-onboarding/actions/runs/7479300189
