### ISSUE TITLE
AWS access for [Kyle Henson]

### ISSUE THREAD

**Issue by khenson-oddball** [department-of-veterans-affairs/va.gov-team#71483]
### COR Name

Eunice Garcia

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Kyle Henson

### Your Email

kyle.henson@oddball.io

### Team, Role, and Company of the target individual

VA IIR, Software Developer, Oddball

### Product Manager (PM) name and email

Peter Egan peter.egan@oddball.io

### Product Owner (PO) name and email

Jeff Barnes jeffrey.barnes4@va.gov

### Desired AWS Access

Could I please have read/write access to the Production GIBCT Data Service (GIDS) Parameter Store paths. Thank you!

### Access Expiration

09/14/2024

### E-QIP Transmittal Confirmation

<img width="1138" alt="E-QIP Transmittal Confirmation" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/145150351/f923ce33-366b-407f-8c61-62a1f4c8996a">

### Additional Notes

I am on the new VA.gov Iterate, Innovate, and Run team, which is a program that is tasked with identifying and evaluating projects that may not have ownership and could use some development attention. Yellow Ribbon has been identified as such a project and we are hoping to try and understand more about the data before starting to make improvements to the project.

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by ph-One** [comment]
Found on VFS Roster

**Comment by ph-One** [comment]
I refactored the IIR Project Team's IAM and confirmed lower-level access to GIDS Parameter Store paths. Waiting on production approval before adding GIDS prod.

**Comment by BillChapmanUSDS** [comment]
Access Approved as per policy.
