### ISSUE TITLE
IPP - Conduct SME Interviews

### ISSUE THREAD

**Issue by lmorris3** [department-of-veterans-affairs/va.gov-team#71482]
We are scheduling and conducting SME interviews the weeks of Dec 4th and Dec 11th.

Planning 5 interviews, each approx 1 hr. Synthesis to follow.

**Comment by SophiaPhilipMO** [comment]
[Note taking Mural](https://docs.google.com/spreadsheets/d/1p9Smp4WetGc1XRo2MTDs_PZpf3bF431v081ZV10Mis4/edit#gid=0)

**Comment by SophiaPhilipMO** [comment]
[SME interview Schedule](https://docs.google.com/spreadsheets/d/1p9Smp4WetGc1XRo2MTDs_PZpf3bF431v081ZV10Mis4/edit#gid=0)
