### ISSUE TITLE
Update DEA and Fry Scholarship pages

### ISSUE THREAD

**Issue by aprocik1** [department-of-veterans-affairs/va.gov-team#71497]
### Background
We want to update the [DEA](https://www.va.gov/education/survivor-dependent-benefits/dependents-education-assistance/) and the [Fry Scholarship](https://www.va.gov/education/survivor-dependent-benefits/fry-scholarship/) pages to highlight the either / or relationship between the benefits. 

This ticket is to track work that stems from recent updates to the [VA education benefits for survivors and dependents](https://www.va.gov/education/survivor-dependent-benefits/) page. Review [ticket 66165](https://github.com/department-of-veterans-affairs/va.gov-team/issues/66165#issue-1909256318) to learn more about that update.

### Deliverables
On this ticket, we're working toward these deliverables:

**1. DEA page:** We want to move the H2 "What if I qualify for both..." to immediately below the featured content box. 
**2. Fry Scholarship page:** We want to add the H2 "What if I qualify for both..." immediately below the featured content box. As a result, we want to remove the subway map and redesign the content in steps 1 and 2.

### Resources
- [DEA page](https://prod.cms.va.gov/education/survivor-dependent-benefits/dependents-education-assistance) (Drupal)
- [Fry Scholarship page](https://prod.cms.va.gov/education/survivor-dependent-benefits/fry-scholarship) (Drupal)

---
### Deliverable 1: DEA page
- [x] AP: Update page in Drupal
- [x] AP: Publish page

### Deliverable 2: Fry Scholarship page
- [x] AP: Update page in Drupal
- [x] BP: Continue this work in the education service audit

---
## Acceptance Criteria
- [x] Updated DEA page is live on the site
- [x] Updated Fry page will be completed by BP

**Comment by aprocik1** [comment]
@bethpotts, here's the Drupal [backend](https://prod.cms.va.gov/node/951/latest) and [preview](https://preview-prod.vfs.va.gov/preview?nodeId=951) for your review. Feel free to make direct edits in Drupal, or we can discuss them in a meeting if you'd prefer. Thanks - all feedback is welcome and appreciated!

**Comment by aprocik1** [comment]
I moved this ticket to blocked because Cinda and Jodi haven't responded to my emails on 1/17 and 1/29. I'll follow up with Beth to determine next steps.

**Comment by bethpottsVADEPO** [comment]
@aprocik1 I think you can close this ticket now since I'm absorbing the work you started here into my accuracy audit of these pages.
