### ISSUE TITLE
Content review of 526 ITF error message

### ISSUE THREAD

**Issue by strelichl** [department-of-veterans-affairs/va.gov-team#71506]
## Issue Description

Nichole Nicholas from the Benefits & Claims team is currently designing an Intent to File MVP Improvement message.  This message would be a new page added to the 526 application and appear when the ITF endpoint was unavailable.  The purpose of this message is to inform users the ITF endpoint is down, but allow them to continue with their application process.
In the Sketch file there are several options they have drafted for review.  They are looking for feedback on tone and understanding of the message.

They'll join office hours Tuesday 12/12

![Screenshot 2023-12-05 at 10 21 10 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/140766198/df0304b3-dd2c-4caf-a6fa-514f6d836768)

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_

**Comment by katherine-fung** [comment]
Hi @nnicholas7! Thanks for bringing us this question during office hours. 

Here's the copy we're proposing:

**Comment by juliepedtke** [comment]
Just chiming in to say we might have a question or two coming your way... please keep open for now and we should get back to you by EOD!

**Comment by nnicholas7** [comment]
Thanks for this feedback! A few questions for you...
- We got [guidance](https://dsva.slack.com/archives/C01K37HRUAH/p1691591562394279) from Beth that we should capitalize Intent to File where it refers to the form/date vs the concept. Do these edits look right based on that?
- I haven't seen it referred to an Intent to File _date_ elsewhere on [VA.gov](http://va.gov/) - an ITF always includes a date, but it's also linked to the Veteran's ID in the record - so suggesting a tweak on that.
- It's important that the "expiration" isn't seen as blocking them from submitting after that date. What if we instead said it resets after one year? It only resets when they come back to work on their application, but I think that wording might get the idea across. Alternatively, we could say it expires after one year, but they could still create a new one after that.
- It's important that folks feel confident continuing their application, and don't interpret this as a need to step away, wait for it to be confirmed, then come back later. Ok if we add the final sentence at the end? Or, any other ideas for how to address this concern?
- "Reserve" feels a little formal. Might we say hold and record instead?
> [H2] We're confirming your Intent to File
>
> When you start a claim for disability benefits online, we record a potential start date for your benefits. This is called your Intent to File. Your Intent to File date resets after one year.
>
> If you already have an Intent to File, we'll continue to hold that date for you.
>
> If you don't already have an Intent to File, we'll use today as your Intent to File date.
>
> You don't need to do anything else to notify us of your Intent to File. You can continue to file your claim.

**Comment by katherine-fung** [comment]
Hi @nnicholas7, 

Thanks for raising these questions. I based the language off the resources and support article on[ intent to file](https://www.va.gov/resources/your-intent-to-file-a-va-claim/) on va.gov. Beth just shared some background with me that there are changes to the style guide that haven't made it to this page yet. So we can ahead and cap "Intent to File" in this alert, and change it in the resources and support article at some point. 

Here's the revised copy: 

[H2] We're confirming your Intent to File

When you start a claim for disability benefits online, we record your Intent to File. This sets a potential start date for your benefits. Your Intent to File date resets after one year.

**If you already have an Intent to File,** we'll continue to hold that date as the potential start date for your benefits.

**If you don't already have an Intent to File,** we'll use today as the potential start date for your benefits.

You don't need to do anything else to notify us of your Intent to File. You can continue to file your claim.

**Comment by nnicholas7** [comment]
Hi @katherine-fung ! 
Happy Friday! Thank you so much for your help. We like the revised copy and will update out Sketch file.

**Comment by coforma-terry** [comment]
Closing for now
