### ISSUE TITLE
Midpoint Review - IA Feedback - Public Websites, VA.gov, Federal Standardized Header/Footer

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#71505]
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

Thanks for bringing this through to us! This is a massive change. Overall it's a net positive for VA.gov and I'm excited to see us on the leading edge for implementing updates to the standard federal header/footer.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

_Given the high level of visibility and wide reach for this project, all of my feedback is "consider" feedback._

### Mobile view

Y'all have probably talked through all of these concepts ad nauseam.

 - Should "Sign in"/"Sign out" be [buttons](https://design.va.gov/components/button/) since they perform an action?
 - The [Authenticated submenu within the mobile flyout](https://www.sketch.com/s/4558672b-741f-4d59-84f0-796020d3ef57/a/4oEPA1J) might benefit from having a different design treatment in the mobile dropdown. It's a different type of menu - a utility menu rather than an site navigation menu. Would a different type of design for that menu element provide helpful differentiation? Maybe something similar to the desktop treatment for this menu. 
<img width="97" alt="Screenshot 2023-12-07 at 3 58 15 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/755248/8eb8dc19-71e6-4583-ac66-f3e17955525f">

### "USA Government" section

I agree 100% with the [open questions/suggestions](https://www.sketch.com/s/4558672b-741f-4d59-84f0-796020d3ef57/a/j4Me1ao) about the new USA header and am hoping that user research gives some clarity on next steps.

Putting on my librarian hat, the new USA banner presents some concerns from an information literacy perspective. The current USA government banner asserts government sites' legitimacy in at least three ways:
<img width="442" alt="Screenshot 2023-12-07 at 2 11 22 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/755248/a2c39d5b-4063-4318-a790-a252ad54146a">
 - It is uses a globally recognized visual symbol for the USA (our flag).
 - It spells out with words that this is a legitimate website.
 - It includes more information about why it's a legitimate website, which allows the user to verify themselves that the site is legit.

<img width="301" alt="Screenshot 2023-12-07 at 2 51 03 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/755248/8e8fbc74-6c86-441e-8033-1c5415451d83">

The new banner does none of these three things, which I believe presents a credibility issue. The USA logo is new and might have a trademark symbol, which could look out of place and potentially untrustworthy to users. During a time of easily manufactured disinformation *and* widespread distrust in government, I think it'd be useful to spell out that this website is legitimate, at least as an interim solution as this new design rolls out more widely.

### Text/placement of Veterans Crisis Line link - desktop

I am guessing that a high-level decision was made to move the Crisis Line link down the page a bit. The link is still highly visible, which is essential. Its placement alongside the header's megamenu navigation on desktop makes it look like more of an informational/page link than an action link that’ll help a user take a next step to get help. This could be something to test or ask about with users. Adding the "talk" action verb back into the link text could be helpful to indicate that it's a task link, rather than an information link.

**Comment by FranECross** [comment]
@jordan @aklausmeier @DanielleThierryUSDSVA @cindymerrill CAIA "IA" feedback. Who should this ticket be assigned to? Thanks! cc @jilladams

**Comment by aklausmeier** [comment]
@erinrwhite I appreciate your shared sentiment on missing the official government website language. The answer we got from OFCIO:

> As a Federal government, we need to rely on browsers, mobile apps, and iOS/Android UI design to communicate that a website is .gov or .mil and that it’s HTTPS. Anything we do on our own websites can easily be spoofed vs. a browser checking that a website is HTTP, has a valid certificate, and is .gov or .mil.

We will be testing the auth menu in multiple research phases and collaborating with AuthExp team, more so in phase 3.

VCL has definitely been discussed in design iterations. We will need to keep a close eye on analytics when launched and an ear out for feedback during research. 

No changes needed prior to research, closing ticket.

**Comment by erinrwhite** [comment]
Thank you for escalating my feedback and sharing the response from the CIO! Hoping research brings some clarity on next steps.
