### ISSUE TITLE
PMC: Update H2 stepper label and add H3 to step 2: Identification information

### ISSUE THREAD

**Issue by rachelshearerux** [department-of-veterans-affairs/va.gov-team#71508]
During staging review, we were asked to adjust H3s and stepper labels for consistency throughout. 

On step 2, we'll change the label in the stepper to "Identification information" and specify whose in the page-H3

<img width="598" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMU5CQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fc3462f9dac3ff41a92977f925ae949bf06abe03/Screenshot%202023-12-07%20at%202.48.36%E2%80%AFPM.png" alt="Screenshot of the updated stepper label and page H3" />

--- 

**Definition of done**
On Step 2, where the requester provides a SSn or VA file number for the Veteran or Reservist:
- [x] Update the stepper label to "Identification information"
- [x] Add H3: "Veteran's or Reservist's identification information
- [x] Ensure the accordion header on the review page reflects the stepper label "Identification information"
- [ ] Confirm in staging

Docs: 
- [Sketch](https://sketch.com/s/e570369e-2610-4b06-a65a-dbfb61b450f4)
- [Source of truth](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/40-0247/source_of_truth.md)
- [Collab cycle ticket](https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team/70905)

**Comment by tlei123** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-website/pull/27159) opened.

**Comment by tlei123** [comment]
PR merged &mdash; changes should be in Staing by tmrw (Wed) ~4:45 PM ET.

**Comment by rachelshearerux** [comment]
Looks great - thanks! 
<img width="1116" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2VEQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c27d1f3a76dbae423799028142697563178fbeb9/Screenshot%202023-12-22%20at%2012.04.02%E2%80%AFPM.png" alt="Screenshot showing the new H3 on step 2" />
