### ISSUE TITLE
Content updates for download and print files

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#71514]
Laura to assess content needs here by 12/18.

**Comment by laurwill** [comment]
@alexiawunder can you drop latest screenshots or links here for this assessment?

**Comment by coforma-terry** [comment]
Hey @alexiawunder - do you have an update on the screen shots? Many thanks!

**Comment by laurwill** [comment]
Chatted with @alexiawunder , we will wait for devs to confirm what the print option will include for medications. Then I'll adjust or add content as needed.
