### ISSUE TITLE
CF: Mapping Caution Flag Content (Profile Page)

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#7151]
As a Veteran searching for institutions using the GI Bill Comparison Tool, I need to know what types of caution flags the institutions I'm considering have so that I can make the best decision about my education choices.

## Assumptions: 
1. This story covers the back end data structure and mapping to provide data points for subsequent display on the front end.
2. This work will be behind a prod flag so that it is only available on staging. 
3. The UI of this story is covered in #6805 (Profile Page) and #6803 (Search Results Page)

## Acceptance Criteria: 

1. On the Search Results page, caution flag content is displayed as follows based on the xls file linked in supporting artifacts as Caution Flag Content: 
a. Caution Flag Title maps to Cell E6 or E7, based the number of warnings.  If 1, E6, if multiple, E7. 
b. Caution Flag Description maps to Column F 

2. On the Profile Page in the Institution Summary section at the very top of the page, caution flag content is displayed as follows based on the xls file linked in the supporting artifacts as Caution Flag Content
a. Caution Flag Title maps to Cell E6 or E7, based the number of warnings.  If 1, E6, if multiple, E7. 
b. Caution Flag Description maps to Column F 

3. On the Profile Page in the Cautionary Information section in the middle of the page, caution flag content is displayed as follows based on the xls file linked in the supporting artifacts as Caution Flag Content
a. Caution Flag Title maps to Column F
b. Caution Flag Description maps to Column G
c. Any applicable link text is found in Column H
d. Any applicable link is found in Column I

## Questions
1. Do we need to include acceptance criteria that is specific to the flexibility we want to build in should we want to display different content for the same flag type (as discussed on the call)

## Supporting Artifacts: 
1. Prototype: https://bahdigital.invisionapp.com/share/N5IAD8MHTC9#/screens
a. Note that this version of the prototype includes notations that signify content mapping described in the acceptance criteria
2. Caution Flag Content: [Caution Flag Copy for Review v.2.0.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4376665/Caution.Flag.Copy.for.Review.v.2.0.xlsx)

## PRs
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/633
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/630
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/634

**Comment by zurbergram** [comment]
Settlement copy in CSV is not `Post 9/11 GI Bill (CH33) not Approved at this institution` but is actually `Post 9/11 GI Bill (CH33) not Approved at this location`

**Comment by zurbergram** [comment]
Settlement copy in CSV is not `Flight Program - Suspended for 85/15 violation (Suspended for 85/15 violation – Flight Program)` but is actually `Flight Program - Suspended for 85/15 violation`

**Comment by zurbergram** [comment]
`Denial of Recertification Application to Participate in the Federal Student Financial Assistance Program` and
`Denial of Recertification Application to Participate in the Federal Student Financial Assistance Programs Issued by Department of Education` have the same mapping to title/description/link

**Comment by zurbergram** [comment]
`Federal Trade Commission Filed Suit for Deceptive Advertising; Potential Suspension of VA Benefits to Five Schools for Deceptive Practices goes into effect on May 9, 2020.` appears to be one flag so 

instead of
the 2 below i’m seeing the 1 above
- `Federal Trade Commission Filed Suit for Deceptive Advertising`
- `Potential Suspension of VA Benefits to Five Schools for Deceptive Practices goes into effect on May 9, 2020.`

There’s also a `Federal Trade Commission Filed Suit for Deceptive Advertising; Settlement reached on May 26, 2015`
so it looks like the flag is Federal Trade Commission Filed Suit for Deceptive Advertising with additional information afterwards

**Comment by zurbergram** [comment]
There is no generic Settlement 
- `SRP   DESCRIPTION     Caution Flag SRP Subheads (list items);      PP Cautionary info accordion Heading      3/17`
- `Profile   Page / Cautionary info           Caution Flag Description - 3/17`
- `Link   text - if applicable.  Placed at the   end of the Description.`
- `Link   (or linking instructions)`

for settlement caution flags that fall outside of defined `existing copy` mappings

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/7440

**Comment by zurbergram** [comment]
Here are the all the descriptions/copy/reasons from the settlement csv uploaded into staging by Brian Grubb on 3/30

- "Post 9/11 GI Bill (CH33) not Approved at this location"
- "Denial of Recertification Application to Participate in the Federal Student Financial Assistance Programs Issued by Department of Education"
- "Loss of Title IV Participation, Settlement with U.S. Government, Upcoming Campus Closure (Details Posted on Institution Website), Assigned receiver has motioned court for an emergency closure of compus. Immenent closure is a distinct possible"
- "Settlement with U.S. Government, Upcoming Campus Closure (Details Posted on Institution Website)"
- "Upcoming Campus Closure (Details Posted on Institution's Website)"
- "Settlement reached with the Federal Trade Commission (FTC)"
- "Assigned receiver has motioned court for an emergency closure of campus. Imminent closure is a distinct possibility."
- "Settlement reached with States Attorney General"
- "Loss of Title IV Participation, Settlement with U.S. Government"
- "Flight Program - Suspended for 85/15 violation"
- "Federal Trade Commission Filed Suit for Deceptive Advertising; Potential Suspension of VA Benefits to Five Schools for Deceptive Practices goes into effect on May 9, 2020."
- "Federal Trade Commission Filed Suit for Deceptive Advertising; Settlement reached on May 26, 2015"
- "Settlement with U.S. Government, Upcoming Campus Closure (Details Posted on Institution Website), Assigned receiver has motioned court for an emergency closure of compus. Immenent closure is a distinct possible"
- "Denial of Recertification Application to Participate in the Federal Student Financial Assistance Program"
- "Settlement with U.S. Government"
- "Settlement with U.S. Government, Upcoming Campus Closure (Details Posted on Institution's Website)"
- "Loss of Title IV Participation, Settlement with U.S. Government, Assigned receiver has motioned court for an emergency closure of campus. Imminent closure is a distinct possibility."
- "Settlement with U.S. Government, Assigned receiver has motioned court for an emergency closure of compus. Immenent closure is a distinct possible"
- "There may be a potential lapse in program approval for Ashford University. VA may be forced to stop making benefit payments unless Ashford continues to show a good faith effort to seek approval in California. The State Attorney General filed a lawsuit against Ashford University for engaging in unlawful business practices, and litigation is pending."
- "Loss of Title IV Participation, Settlement with U.S. Government, Assigned receiver has motioned court for an emergency closure of compus. Immenent closure is a distinct possible"
- "Loss of Title IV Participation, Assigned receiver has motioned court for an emergency closure of compus. ImmInent closure is a distinct possible"

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/630/

**Comment by delli-gatti-michael** [comment]
![Screen Shot 2020-04-06 at 2.13.35 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/cffaa8b5-be7b-4ce6-ae5a-a6c5a3f32293)

---

![Screen Shot 2020-04-06 at 3.04.12 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/faf60f5e-074f-47ea-89cb-7a2d3f682ea9)
![Screen Shot 2020-04-06 at 3.04.32 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/c539dfb0-edad-43fd-a0bf-d096b26c1771)
![Screen Shot 2020-04-06 at 3.04.47 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/d797d984-c61f-4bb9-867e-f6516d879161)
![Screen Shot 2020-04-06 at 3.05.02 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/cfe5933d-8496-4a2a-80ec-768ddb73b095)
![Screen Shot 2020-04-06 at 3.05.26 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/2bec5a98-794e-409a-bc47-a7d328dcd942)

**Comment by delli-gatti-michael** [comment]
local testing complete

**Comment by delli-gatti-michael** [comment]
TestRail Test Case:
https://dsvavsp.testrail.io/index.php?/cases/view/460

**Comment by delli-gatti-michael** [comment]
Closing story, fixes will be completed in https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/7743
