### ISSUE TITLE
PMC: Update H3 on step 5 (requester's personal informaion)

### ISSUE THREAD

**Issue by rachelshearerux** [department-of-veterans-affairs/va.gov-team#71517]
During staging review, we were asked to adjust H3s and stepper labels for consistency throughout.

On step 5, change the H3 "tell us about yourself"; and include help text below that is wrapped by a legend to ensure the descriptive text gets picked up by a screenreader

<img width="669" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGhCQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--47ca96dd22dd6a3354d9fcc0776bb3f24654e685/Screenshot%202023-12-07%20at%203.31.04%E2%80%AFPM.png" alt="Screenshot of step 5 header changes" />

---

**Definition of done**:
- [x] Edit the H3 to "Tell us about yourself" 
- [x] Include help text below "We’ll use this information in case we need to follow up with you about the request."
- [x] Wrap the text below in a Legend
- [x] Confirm in staging

Docs:
- [Sketch](https://www.sketch.com/s/e570369e-2610-4b06-a65a-dbfb61b450f4/a/GoYYwA8)
- [Source of truth](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/40-0247/source_of_truth.md)
- [Collab cycle ticket](https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team/70905)

**Comment by tlei123** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-website/pull/27155) opened.

**Comment by tlei123** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-website/pull/27155) merged &mdash; changes should be in Staging by ~4:45 PM ET.

**Comment by tlei123** [comment]
@rachelshearerux  , changes now [in Staging](https://staging.va.gov/burials-memorials/memorial-items/presidential-memorial-certificates/request-certificate-form-40-0247), ready for validation.

**Comment by rachelshearerux** [comment]
Looks good! 

<img width="473" alt="Screenshot showing the updated h3 on step 5" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/139145471/3e5ac337-d440-46e4-8f37-f676240ac064">
