### ISSUE TITLE
PMC: Update H2 stepper label and H3 on step 3 (file upload step)

### ISSUE THREAD

**Issue by rachelshearerux** [department-of-veterans-affairs/va.gov-team#71511]
During staging review, we were asked to adjust H3s and stepper labels for consistency throughout.

On step 3, we'll change the label in the stepper to "Supporting documentation" and change the H3 to "Upoad the Veteran's or Reservist's files (preferably DD214)

<img width="241" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmxCQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--82a90eb398e5595a6805476d47e0da9cc195e4b6/Screenshot%202023-12-07%20at%203.05.59%E2%80%AFPM.png" alt="Screenshot of the changes to step 3 showing a new header and new stepper-label" />

---
Definition of done
On Step 3, where the requester uploads documentation for the Veteran or Reservist:

- [x] Update the stepper label to: "Supporting documentation"
- [x] Edit H3 to: "Upload the Veteran's or Reservist's files (preferably DD214)"
- [x] Ensure the accordion header on the review page reflects the stepper label: "Supporting documentation"
- [ ] Confirm in staging

Docs:
- [Sketch](https://www.sketch.com/s/e570369e-2610-4b06-a65a-dbfb61b450f4)
- [Source of truth](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/40-0247/source_of_truth.md)
- [Collab cycle ticket](https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team/70905)

**Comment by tlei123** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-website/pull/27158) opened.

**Comment by tlei123** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-website/pull/27129/files) merged &mdash; changes should be in Staging by ~4:45 PM ET.

**Comment by tlei123** [comment]
@rachelshearerux , changes now [in Staging](https://staging.va.gov/burials-memorials/memorial-items/presidential-memorial-certificates/request-certificate-form-40-0247), ready for validation.

**Comment by rachelshearerux** [comment]
LGTM
<img width="1031" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTZEQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--07c23c1fde8cb590f7cf0ead9791104668f93405/Screenshot%202023-12-22%20at%201.22.24%E2%80%AFPM.png" alt="Screenshot of updated H3" />
