### ISSUE TITLE
PMC Content change: change "decedent" to "deceased in statement of truth

### ISSUE THREAD

**Issue by rachelshearerux** [department-of-veterans-affairs/va.gov-team#71522]
During staging review of the statement of truth, we were asked to update the content in the statement of truth to follow plain-language standards

We'll update the statement of truth to refer to the "deceased" rather than the "decedent"

<img width="1069" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3RCQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5ecf2fc1314c06ac7e09aa81918df8590bbb5103/Screenshot%202023-12-07%20at%204.08.52%E2%80%AFPM.png" alt="Screenshot of the statement of truth showing 'deceased' highlighted twice" />

---
Definition of done:
- [ ] In the statement of truth component on the review page, change both mentions of "decedent" to "deceased"
- [ ] Confirm in staging

Docs:
- [Sketch](https://www.sketch.com/s/e570369e-2610-4b06-a65a-dbfb61b450f4/v/bvbL7z/p/137CB9E0-F42C-4D9A-BB5A-682427517A34/canvas?posX=-26533.560027480922&posY=-1380.0424436007997&zoom=0.27210989594459534) 
- [Source of truth](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/40-0247/source_of_truth.md)
- [Collab cycle ticket](https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team/70899)

**Comment by tlei123** [comment]
Closing this.  Already fixed [in Staging](https://staging.va.gov/burials-memorials/memorial-items/presidential-memorial-certificates/request-certificate-form-40-0247).

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/587583/74803be1-cd25-43ea-b9de-abff0babffa2)

**Comment by tlei123** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-website/pull/27150) opened.

**Comment by tlei123** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-website/pull/27150) merged &mdash; changes should be in Staging by Friday ~4:45 PM ET.

**Comment by tlei123** [comment]
@rachelshearerux , changes are now [in Staging](https://staging.va.gov/burials-memorials/memorial-items/presidential-memorial-certificates/request-certificate-form-40-0247), ready for validation.

cc @tbaker1026 @jeana-adhoc

**Comment by rachelshearerux** [comment]
Perfect, thanks! 

<img width="1056" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTJEQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--64f51bdbf332d52e058d8b044deded1bb4470e2a/Screenshot%202023-12-22%20at%201.20.23%E2%80%AFPM.png" alt="Screenshot of statement of truth showing updated content" />
