### ISSUE TITLE
PMC: Swap H3 and field label on Step 8: Certificates

### ISSUE THREAD

**Issue by rachelshearerux** [department-of-veterans-affairs/va.gov-team#71520]
During staging review, we were asked to adjust H3s and stepper labels for consistency throughout.

On step 8, swap the field label and H3

<img width="691" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUpCQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d5d803c2045c16ad8c711d413c3e9eb35e414a68/Screenshot%202023-12-07%20at%203.45.43%E2%80%AFPM.png" alt="Screenshot of changes to H3 and field label on page 8" />

---
Definition of done:
- [x] Update the H3 to: How many certificates should we send to this address?
- [x] Update the field label to: Number of certificates (*Required)
- [ ] Confirm in staging

Docs:
- [Sketch](https://www.sketch.com/s/e570369e-2610-4b06-a65a-dbfb61b450f4/v/eGblnz/p/137CB9E0-F42C-4D9A-BB5A-682427517A34/canvas?posX=-19988.80483975808&posY=-5228.017843021395&zoom=0.2760891318321228)
- [Source of truth](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/40-0247/source_of_truth.md)
- [Collab cycle ticket](https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team/70905)

**Comment by tlei123** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-website/pull/27153) opened.

**Comment by tlei123** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-website/pull/27153) merged — changes should be in Staging by ~4:45 PM ET.

**Comment by tlei123** [comment]
@rachelshearerux , changes now [in Staging](https://staging.va.gov/burials-memorials/memorial-items/presidential-memorial-certificates/request-certificate-form-40-0247), ready for validation.

**Comment by rachelshearerux** [comment]
LGTM - ty! 
<img width="1106" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1dEQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--064f4620b580c78df99523f7dffb80d474544cd2/Screenshot%202023-12-22%20at%2012.02.23%E2%80%AFPM.png" alt="Screenshot showing the updated H3 and field label for the number of certificates" />
