### ISSUE TITLE
PMC: Content change - update request type options

### ISSUE THREAD

**Issue by rachelshearerux** [department-of-veterans-affairs/va.gov-team#71521]
Update the options on Step 4: Request type 

<img width="557" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlZCQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a41e7d25d662babbd19ce788f6f6c9572fa5645f/Screenshot%202023-12-07%20at%203.57.28%E2%80%AFPM.png" alt="Screenshot 2023-12-07 at 3.57.28 PM.png" />

---
Definition of done:
- [x] Update the radio button options: 
- Option 1: Yes, this is my first time requesting a certificate for this Veteran or Reservist.
- Option 2: No, I either need to replace a Presidential Memorial Certificate or request more copies
- [x] Capitalize Presidential Memorial Certificate
- [x] Confirm in staging

Docs:
- [Sketch](https://sketch.com/s/e570369e-2610-4b06-a65a-dbfb61b450f4)
- [Source of truth](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/40-0247/source_of_truth.md)
- [Collab cycle ticket](https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team/70902)

**Comment by tlei123** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-website/pull/27151) opened.

**Comment by tlei123** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-website/pull/27151) merged — changes should be in Staging by ~4:45 PM ET.

**Comment by tlei123** [comment]
@rachelshearerux , changes now [in Staging](https://staging.va.gov/burials-memorials/memorial-items/presidential-memorial-certificates/request-certificate-form-40-0247), ready for validation.

**Comment by rachelshearerux** [comment]
Looks good to me 👍
<img width="576" alt="Screenshot of step 4 showing the updated radio button options" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/139145471/9c72597b-575e-444b-9abd-305c49e0b6ab">
