### ISSUE TITLE
Usability Testing Prep - Public Websites  [AMA Phase 2]

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#7153]
## Steps to complete Usability Testing Prep: 
- [x] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in #vfs-platform-support in Slack; tag @ Megan Kelley @ AndreaHewitt
- [x] Andrea and Megan to schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [ ] At least 2 days before scheduled meeting, you must complete list of artifacts below
- [ ] VSP <> **requesting team** review meeting completed
- [ ] Practice area reviewers create sub-issues attached to this one with feedback for your team on **AMA Phase 2**
- [ ] Public Websites completes attached feedback tickets based on definition of done included in each practice area feedback ticket (may differ for each practice area, please refer to attached tickets for further instruction)
- [ ] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please provide the following artifacts at least 2 days before scheduled meeting_
- Link to product outline  - [AMA Follow Up](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/AMA%20Follow%20Up/AMA%20Follow%20Up%20Product%20Outline.md)
- Link to or attach prototype or mockups 
  - https://app.moqups.com/Rnc4BDEKrA/view/page/a5e3c0342
- Link to or attach artifact with copy (if separate from prototypes/mockups) 
  - [Latest edits to Drupal pages](https://github.com/department-of-veterans-affairs/va.gov-team/files/4389384/decison-review-drupal-edits-032620.docx)
- Hub page copy deck 
[decision-reviews-hub-page_copy-v1.5.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4395112/decision-reviews-hub-page_copy-v1.5.docx)
- Drupal anomalies and recommendations 
[decision-review-page-anomalies-and-recommendations_031620.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4395114/decision-review-page-anomalies-and-recommendations_031620.docx)

- ~Link to research plan ([template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-plan-template.md)) and script ([template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/conversation-guide-template.md))~
- Link to regression test plan ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#regression-test-plan)) (if there isn't already a regression test plan for this feature in TestRail) _for QA practice area review_
- Link to test cases/test plan in TestRail ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/qa-artifacts.md#test-plan)) (even if just a draft) _for QA practice area review_

## Meeting attendees from Public Websites
- Product Manager (required): Mickin Sahni
- DEPO product lead (required): Jen Lee
- Anyone else from your team who significantly contributed to the artifacts provided (required): Laura Walsh

## Scheduling
Preferred dates or times: Friday, 3/27 2p ET and after

## Additional Notes: 
During this collaboration point, you will receive feedback from the following practice areas: design, accessibility, content, QA, and optional: information architecture (IA), product

**Comment by andreahewitt-odd** [comment]
Scheduled for Friday, March 27⋅3:00 – 4:00pm ET

**Comment by pjhill** [comment]
I have not seen any test plan artifacts posted to the ticket.  I dug through TestRail a bit, but I haven't been able to find any test cases related to what I'm seeing in the product outline.  Are there any QA artifacts currently available for review?

**Comment by MickinSahni** [comment]
Updated with latest copy deck. 

@pjhill, our conclusion was that user stories/AC would be sufficient from a QA perspective. I [added those here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6421#issuecomment-604175380). Is more necessary?

**Comment by tlei123** [comment]
@MickinSahni , per out Usability Testing Prep mtg, I'll start converting the linked tickets' user-stories into TestRail test-cases, pinging you on #vsa-public-websites DSVA Slack-channel if I have questions/problems.

@pjhill , I'll ping you on #vsp-product-support channel if/when I have questions/problems.

**Comment by meganhkelley** [comment]
Group met today to regroup as there was still confusion on the scope of this work and how it should be integrated with the VSP Collaboration Cycle.

Notes & decisions: 
IA - already involved!
QA - Context was helpful! Tze and Peter are going to keep in touch as they work on this and collaborate with Mickin as needed 
Accessibility — V1 audit complete! V2 - accessibility will review in staging
Content — Megan to check with Peggy 
Design — if this is using existing templates, let’s skip the current collaboration review and pick it up in staging! 

*Pending update from content (Peggy), this collaboration point is complete.*

**Comment by peggygannon** [comment]
Hello all, I'm ok with doing my next content review during staging.

**Comment by lwalsh617** [comment]
I added Drupal preview links to the top of the ticket.
