### ISSUE TITLE
Midpoint Review - Content - Public Websites, VA.gov, Federal Standardized Header/Footer

### ISSUE THREAD

**Issue by rferguson13** [department-of-veterans-affairs/va.gov-team#71532]
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts

Overall, this is looking good from a content perspective. 

### Should
- Under the “Information for” section of the footer, most of the links are plural except “Business.” Consider revising so the link is “Businesses.” However, it’s not entirely clear what kind of resources that link will connect to, so perhaps more context should be added. For example, if it links to resources that will help a Veteran start a business, then the footer link should be “Starting a business”.
- The “information for” footer section header is written a little bit differently from the rest of the footer section headers. This should be revised so it matches the writing style of the others. There are several ways the writer could do this. For example, the section header could be revised to "Resources" or "Information."
- “Contact us online through Ask VA” - This link text should be shortened to match the style of the other links in the section. None of the other links call out the communication medium, so specifically mentioning that "Ask VA" is online feels redundant. This should be revised so the link text is more direct. There are several ways the writer could do this. For example, the link text could be: "Contact us through Ask VA" or just "Ask VA."
- Under “More Resources,” the “Your VA welcome kit” link should be moved to the first spot (above Forms). Since it’s a welcome kit, Veterans may want to start there and it being at the top of that section will help with exposure.

### Consider
- Consider moving the “VA outreach events” link to the “Connect with us” section. Thematically, it may be a better fit there, since outreach is about connection. 
- There are quite a few links in the footer - is there a way to consolidate or create a hub page to link to? A user may be potentially overwhelmed by all the footer options. Consider streamlining or removing some links from the footer section.

## Note
Thank you for the opportunity to review your work. Please continue working with CAIA on content. If you have any questions, please let me know.

**Comment by FranECross** [comment]
@jordan @aklausmeier @DanielleThierryUSDSVA @cindymerrill CAIA "Content" feedback. Who should this ticket be assigned to? Thanks! cc @jilladams

**Comment by aklausmeier** [comment]
TY, content including link labels have not been finalized yet. We are working directly with @DanielleThierryUSDSVA  and @mnorthuis for final content.

**Comment by aklausmeier** [comment]
No MUST feedback so no blocker for research.
