### ISSUE TITLE
Update or replace active_model_serializers gem

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#71543]
### Description
We currently use a fork of `active_model_serializers` and it must be updated to remove our dependency on the [deprecated](https://github.com/beauby/jsonapi) gem, `jsonapi`. A solution may be using the original repo or a different solution all together. We should investigate which method makes more sense and implemented

### Tasks
- [ ] Determine which solution makes more sense
- [ ] TODO

### Acceptance Criteria
- [ ] vets-api has implemented solution released to production

**Comment by ericboehs** [comment]
Completed last week.
