### ISSUE TITLE
Setting up front-end env

### ISSUE THREAD

**Issue by kjsuarez** [department-of-veterans-affairs/va.gov-team#71557]
As the team moves towards a more full-stack approach to development, Kevin needs to get his frontend environment in proper working order. Before we can identify what aspect of the frontend business logic can be moved to the backend, we must have backend developers who fundamentally understand the business logic taking place on the frontend.

- Get frontend environment working (fix user login)
- Gain a more complete understanding of what business logic the frontend manages. For example, 'does this user qualify for a streamlined waiver' that's business logic.

**Comment by amponce** [comment]
Happy to work though this with you if you need any setup assistance
