### ISSUE TITLE
Content audit of public SEP website

### ISSUE THREAD

**Issue by uxrebecca** [department-of-veterans-affairs/va.gov-team#71561]
**Description**

Understanding the current content, information architecture, and menu labeling will (along with task flows) solidify our understanding of the existing state. This will help us ensure we aren't removing useful functionality/information when we design the new system and will help us identify areas for future design opportunity. 

This audit can be lightweight and simple using a spreadsheet such as Google Sheets. 

**Resources**
- Site to audit: [SEP Website.](https://www.sep.va.gov/sep/web/guest/sep)
- [Audit spreadsheet](https://docs.google.com/spreadsheets/d/1o_S209XatHW9hh6r39AX_nLVYmjTgpwUZFZd4ol7758/edit?usp=sharing)

**Acceptance criteria**

- [x] Completed spreadsheet that includes columns: Page Title, URL, Primary Audience, Content Summary
- [x] Brief list of findings including number of pages and audience(s) represented

**Comment by RenataKeck** [comment]
@uxrebecca please update success criteria/doneness

**Comment by uxrebecca** [comment]
Added success criteria ✅

**Comment by uxrebecca** [comment]
@RivkaCGates I think this is ready to pull into Product backlog to try and do in the next sprint.

**Comment by uxrebecca** [comment]
I worked on this today and completed the spreadsheet and added to this doc with overall, high level findings from the audit: https://app.zenhub.com/workspaces/accredited-representative-facing-team-65453a97a9cc36069a2ad1d6/issues/gh/department-of-veterans-affairs/va.gov-team/72873
