### ISSUE TITLE
Completed: Midpoint Review - Public Websites - Header & Footer

### ISSUE THREAD

**Issue by it-harrison** [department-of-veterans-affairs/va.gov-team#71564]
This ticket is for Platform tracking purposes only. There is no VFS action needed.

**Comment by FranECross** [comment]
@shiragoodman @it-harrison I believe your feedback is in the four tickets you created/linked to the main ticket?

[Midpoint Review - Content - Public Websites, VA.gov, Federal Standardized Header/Footer#71532](https://app.zenhub.com/workspaces/collaboration-cycle-reviews-61d89e9e5f4c120011a0ad37/issues/gh/department-of-veterans-affairs/va.gov-team/71532)
[Midpoint Review - Design Feedback - Public Websites, VA.gov, Federal Standardized Header/Footer#71494](https://app.zenhub.com/workspaces/collaboration-cycle-reviews-61d89e9e5f4c120011a0ad37/issues/gh/department-of-veterans-affairs/va.gov-team/71494)
[Midpoint Review - IA Feedback - Public Websites, VA.gov, Federal Standardized Header/Footer#71505](https://app.zenhub.com/workspaces/collaboration-cycle-reviews-61d89e9e5f4c120011a0ad37/issues/gh/department-of-veterans-affairs/va.gov-team/71505)
[Midpoint Review - Accessibility Feedback - Public Websites, VA.gov, Federal Standardized Header/Footer#71524](https://app.zenhub.com/workspaces/collaboration-cycle-reviews-61d89e9e5f4c120011a0ad37/issues/gh/department-of-veterans-affairs/va.gov-team/71524)
