### ISSUE TITLE
Use of behavioral analytics tools to identify trends

### ISSUE THREAD

**Issue by joshmatulonis** [department-of-veterans-affairs/va.gov-team#71598]

**Comment by parkerbees** [comment]
@claytonzook / @charlye-bluetiger do you know what this ticket was meant to entail? If so I can move to backlog; if not we can close this out. Thx.

**Comment by joshmatulonis** [comment]
Hey Parker!
The ticket was meant for me to use GA, Domo, and PowerBi, among other
available tools and data sources, to aid in understanding users, validating
studies, and determining knowledge gaps for further exploration. It's an
ongoing neverending story for research but the ticket may be marked as
completed/closed out.
Thank you,
Josh
