### ISSUE TITLE
Implement dashboard mockup

### ISSUE THREAD

**Issue by nihil2501** [department-of-veterans-affairs/va.gov-team#71609]
Mockup can be found [in this Sketch](https://www.sketch.com/s/e1d6898a-a709-4a4f-a09b-ea0ac2a960a2) in the panel titled "Rep VA Dashboard" (as of 2023-12-08).
Now [in this Figma](https://www.figma.com/file/C3sdnDf8anVqXVdmiCWwq8/%F0%9F%9A%A7-Accredited-Rep-Facing?type=design&node-id=0-1&mode=design&t=GQVKUtEZFakl28Jw-0) (as of 2023-01-04, I believe we now have parity).
<img width="485" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0JIQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--963ea13066d2dd411092f80b7c8345678ce48a32/Screenshot%202023-12-08%20at%203.49.31%20PM.png" alt="Screenshot 2023-12-08 at 3.49.31 PM.png" />
(appearance as of 2023-12-08)

**Comment by nihil2501** [comment]
<img width="485" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0JIQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--963ea13066d2dd411092f80b7c8345678ce48a32/Screenshot%202023-12-08%20at%203.49.31%20PM.png" alt="Screenshot 2023-12-08 at 3.49.31 PM.png" />
(appearance as of 2023-12-08)

**Comment by nihil2501** [comment]
[Draft PR](https://github.com/department-of-veterans-affairs/vets-website/pull/27019)

**Comment by emily-gullo** [comment]
@RivkaCGates [Here](https://staging.va.gov/?next=%2Frepresentatives%2F), will add to the PR/Ticket

**Comment by RivkaCGates** [comment]
@emily-gullo that's taking me to the VA.gov staging homepage it looks like?

**Comment by emily-gullo** [comment]
@RivkaCGates That's correct, it's been pushed to staging via the standard va.gov build process.

**Comment by RivkaCGates** [comment]
no, it's the PACT act page, not the mockup I see above
