### ISSUE TITLE
Update LOA3 identity content on intro page

### ISSUE THREAD

**Issue by rachelshearerux** [department-of-veterans-affairs/va.gov-team#71604]
The intro page description of LOA3 identity verification requirements needs to be updated based on recommendations from the identity team. 

The first paragraph below the H2 "What to know before filling out this form" should now read:

>To manage certain tasks and information on VA.gov, like requesting personal records or changing your direct deposit information, you’ll need to log in with an account where you’ve provided some personal information to verify your identity. We recommend using ID.me or Login.gov accounts for identity verification.

<img width="1444" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGxHQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--60cf7d9e647b76b0ab1a65b2b4463050fad367e8/New%20LOA3%20Copy.png" alt="Screenshot of new LOA3 copy.png" />

---

- [x] Intro page for all users (unauthenticated or not) should include the content from above
- [ ] Confirm in staging

Docs:
- [Source of truth](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/20-10206%20FOIA%20PA%20Request/source-of-truth.md#:~:text=If%20you%20want%20to%20request%20your%20records%20through%20this%20online%20form%2C%20you%E2%80%99ll%20need%20to%20sign%20in%20to%20your%20account.%20You%E2%80%99ll%20need%20to%20log%20in%20with%20an%20account%20where%20you%E2%80%99ve%20provided%20some%20personal%20information%20to%20verify%20your%20identity.%20We%20recommend%20using%20ID.me%20or%20Login.gov%20accounts%20for%20identity%20verification.)
- [Sketch](https://www.sketch.com/s/314e6dbf-5b4a-422d-beb1-0ad599fc3af1/a/bLZO0R5#Version)

**Comment by jeana-adhoc** [comment]
@rachelshearerux - Can you confirm this is in staging, and if it's correct we can close the ticket. Otherwise let me know if there are additional updates.

**Comment by rachelshearerux** [comment]
Thank you Jeana, I see the change! We're expecting feedback from CAIA on this content, so I'll close and re-open when we hear back from them.
