### ISSUE TITLE
QA Feedback for Profile 2.0 [Usability Testing Prep]

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#7160]
## VSP QA feedback on Profile 2.0 [Usability Testing Prep]

**Regression Test Suite Artifacts:**
https://dsvavsp.testrail.io/index.php?/suites/view/5&group_by=cases:section_id&group_order=asc

**Manual Functional Test Suite Artifacts:**
Not available

## Feedback
**Regression Tests:** 
1. The core set of manual regression tests may be sufficient. Tze has stubbed out a larger set of regression tests for Profile functionality.  If possible please finish creating the expanded set of manual regression tests.
1. Existing E2E automated tests provide some regression coverage (17 assertions).  Please clarify what kind of coverage these assertions provide as part of TestRail or as part of a written test plan.

**Manual Functional Tests:**
1. Manual functional test cases are not created at the time of this meeting.  Although this product appears to be primarily a "lift and shift" effort at the moment, it appears that a minor reorganization of the information presented may be underway. If my assumption of reorganization is correct then it is prudent to create manual functional test cases that verify the information has moved to the new and correct location on the page.

## Definition of Done
- [ ] Acknowledge each item of feedback with a decision
- [ ] VSP QA will close ticket after reviewing feedback decisions

**Comment by mandifrances** [comment]
Closing based on feedback from @pjhill
