### ISSUE TITLE
LOA3 change: Add content to sign-in component for unauthenticated users

### ISSUE THREAD

**Issue by rachelshearerux** [department-of-veterans-affairs/va.gov-team#71605]
The identity team reviewed our content and recommends including LOA3 account guidance in the sign-in component so that users who may have multiple accounts select a Login.gov or ID.me.

The new content should read:
> You’ll need to log in with an account where you’ve provided some personal information to verify your identity. We recommend using **ID.me** or **Login.gov** accounts for identity verification.

We'll also make this clear in the intro page content under the first H2

<img width="1444" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0ZHQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cc702baa5720ea0b404f552ec3c90a2ccdd1735a/New%20bullet%20in%20sign-in%20component.png" alt="New bullet in sign-in component.png" />

---
Definition of done:
- [x] Sign in component for unauthenticated users includes a 3rd bullet with the content listed above
- [ ] Confirm in staging

Docs:
- [Sketch](https://www.sketch.com/s/314e6dbf-5b4a-422d-beb1-0ad599fc3af1/v/GQz7oL/a/bLZO0R5#Version)
- [Source of truth](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/20-10206%20FOIA%20PA%20Request/source-of-truth.md#:~:text=%7B%20blue%20informational%20alert%20%7D)

**Comment by tlei123** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-website/pull/27095) opened.

@tbaker1026 @jeana-adhoc , i took this one on because it required some customization to append a list-item the previously-baked-in bullet-list.

**Comment by jeana-adhoc** [comment]
Good call! Let me know if there's anything else I can do to help.

**Comment by tlei123** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-website/pull/27095) merged &mdash; changes should be in Staging by ~4:45 PM ET.

**Comment by tlei123** [comment]
@tbaker1026 @rachelshearerux @jeana-adhoc , changes are now [in Staging](https://staging.va.gov/records/request-personal-records-form-20-10206/introduction), ready for validation.

**Comment by rachelshearerux** [comment]
Thank you so much, @tlei123 ! 

<img width="555" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0ZjQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e48d8b9b6f5f6e6b5be17f15dcd26acfc2420216/Screenshot%202023-12-13%20at%205.28.29%E2%80%AFPM.png" alt="Screenshot 2023-12-13 at 5.28.29 PM.png" />

I'm going to close this ticket, we've confirmed that the content related to the unauthenticated experience will not be present when we're done with testing.

This is a note just for the sake of documentation: since the content for LOA3 has been back and forth this last week - this is not the final state. We intend to update content per feedback from SWCAIA, the details are all captured [here](https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team/71919).
