### ISSUE TITLE
Help prepare VFS teams for Figma

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#71646]
## User Story
_"As a (persona), I (want to), (so that)."_

Assignee:
Peer Reviewer:

## Description
Platform will be retiring Sketch as a tool in February 2024. The tool will be replaced with Figma. 

The purpose of this ticket is to review Platform Governance documentation for Platform Orientation and Collaboration Cycle to ensure any references to Sketch are removed. We are uncertain at this time if we will be adding new references to Figma.

Follow up with Naomi to see if she's updating VFS-facing documentation on Platform Website.

### Notes from call with Naomi 12/13/2023

Opportunity to enforce and encourage use of Figma.

DST will be creating/updating:

- annotation library - will point at CVS Health annotation library. it's a bit big, so we may need to add some additional instructions. Need a11y specialist to review.
- ~~user flow~~ (note from Allison 12/14: CAIA will dictate user flows. not going to put in Figma)
- component library - will get done 1st
- example library (shows mobile and desktop, error states, accessibility concerns, etc. However don't want to get in the habit of "you have to do this.") - how folks will QA components with us - 2nd

With Figma, it will be very easy for Governance to see who is using DS components out of the box. Don't really have patterns at this time. Other teams had previously been using Figma. Trying to encourage teams to use our Figma design library. How might we encourage that behavior?

We have comm that we are not paying for the Sketch licenses.. they need to transition their work. Sketch licenses expire Feb 22 (comm Feb 16th for wiggle room). 

Follow up in January to see what we see. Are teams moving fast enough?

Accessibility annotations in Figma? Checks file against WCAG SC.
   - Per Brian, there is minimal WCAG checks in Figma

Plugins? Add ons. Some may be free. There are some a11y tools that people have used before.

Content - unsure if CAIA is going to be bringing style guide guidance into Figma at all.

## Impacted Artifacts
Governance team operational documentation for Collab Cycle
Collab Cycle request template for VFS and for DST

## Tasks
- [ ] _Placeholder task_

## Peer Review
_To be completed by peer reviewer_
- [ ] User story and acceptance criteria are met

## Acceptance Criteria
- [ ] _Placeholder AC_

## Team Notification
- [ ] Slack post on #platform-governance-team
- [ ] Presentation at Weekly Initiative Meeting
- [ ] No notification needed

### Refinement
- [ ] Ticket has user story, description, tasks, and acceptance criteria
- [ ] Ticket has been sized 
- [ ] Once all above items are checked, add the 'Ready' label.
### Planning
_If this ticket is picked up from the Backlog mid-sprint, connect with Shira to ensure the below items are completed correctly_
- [ ] Ticket has been discussed as a team at Planning
- [ ] Ticket has been assigned to appropriate initiative or quarterly epic
- [ ] Ticket has been assigned to a Sprint
- [ ] Ticket has been moved to the Planned pipeline in the Governance team board
- [ ] Ticket as an assignee and peer reviewer

**Comment by shiragoodman** [comment]
@humancompanion-usds @naomimarcussen this ticket started out as us removing references to Sketch (which has been completed per ticket #73142) and sort of transformed into a places for taking notes on how Governance team might be able to help VFS teams transition to Figma. I believe we decided that no additional help from Governance re: Figma was necessary at this time, but I wanted to turn it over to the 2 of you before I close this ticket. Please let me know if you have any questions.

**Comment by humancompanion-usds** [comment]
I agree. You can close this.

**Comment by naomimarcussen** [comment]
Yup, you can close.
