### ISSUE TITLE
[MVP] Apply for Veterans Pension Page: Update copy from 60 days to "one year"

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#71647]
## Issue Description
Follow up task from review/QA of ticket #69745

## User Story
As a user about to fill out the Pension form,
**I need to know that I will have one year from when I start the form or make updates to it to come back and finish it,**
so that I know the timeframe to finish the form before the information I provided is no longer saved in progress.

## Designs
Page and grey info box found on this file: https://www.sketch.com/s/94592459-f741-45a0-9432-efd685b9a1d5/a/uuid/FCD0E156-01C7-482A-A5DD-D8EA76ABCC02

---
## Tasks
On the Pension form's "[Apply for Veterans Pension benefits](https://staging.va.gov/pension/application/527EZ/introduction)" page,
on the "Sign in now to save your work in progress" grey info box,

- [ ] Update the copy to match the Sketch design files, as shown on the design.

**The copy should be:**

`Sign in now to save time and save your work in progress`

`Here's how signing in now helps you:`

`We can fill in some of your information for you to save you time.`
`We can save your work in progress. You'll have one year from when you start or make updates to your application to come back and finish it.`

`Note: You can sign in after you start your application. But you'll lose any information already filled in.`

`Sign in to start your application`
`Start your application without signing in`

## Acceptance Criteria
- [ ] The user will see on the Apply page of the form, that they have one year (not 60 days) to come back and finish the form, in order to save their work in progress.

**Comment by aplatt-coforma** [comment]
Verified the text changes. It was updated to only say:

> You can save your work in progress. You’ll have one year from when you start your application to come back and finish it.

<img width="368" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzEwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fe14b957ac2b80896a2e3e5492c2c5cc147bbb8a/screencapture-staging-va-gov-pension-application-527EZ-introduction-2023-12-19-13_17_49.png" alt="screencapture-staging-va-gov-pension-application-527EZ-introduction-2023-12-19-13_17_49.png" />
