### ISSUE TITLE
[MVP] Step 1 Applicant Info: Correct checkbox copy for mail outside of the US

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#71650]
## Issue Description
Follow up task from review/QA of ticket #70329

## Designs
- Design on the page: https://www.sketch.com/s/94592459-f741-45a0-9432-efd685b9a1d5/a/uuid/AB41C46A-E35D-4E6E-9022-90EAAB6C76A5

---
## Tasks
On Step 1 for Applicant Information...

- [ ] update the checkbox copy that currently says "I live on a United States military base outside of the U.S., to the following copy:

`I receive mail outside of the United States on a U.S. military base`

**Note:** Please leave the supporting copy below it that expands/collapses.

## Acceptance Criteria
- On Step 1 for Applicant Information, the checkbox under the Mailing address" page will show the same copy as the design file in Sketch.

**Comment by aplatt-coforma** [comment]
Looks good on staging
<img width="809" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEJPQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--79d85477201ee2f33d17281ef048f7162db2c096/Screenshot%202023-12-11%20at%203.47.36%E2%80%AFPM.png" alt="Screenshot 2023-12-11 at 3.47.36 PM.png" />
