### ISSUE TITLE
FAR search results: first pages are cut off

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#71657]
We are noticing that the first pages of search results are cut off on the mobile staging experience.  In this screenshot, the first page available is `3` and there is no way to scroll to the left to access pages `1` and `2`.

<img width="630" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzFMQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--504d4a4156c4fd9d1233af7d4874398a12512b9e/image.png" alt="image.png" />

### Steps to Reproduce
1. Open https://staging.va.gov/get-help-from-accredited-representative/find-rep/ on mobile
2. Enter 94605 in the location
3. Select "Attorney" for the rep type
4. Search, scroll to the bottom to see pagination

**Comment by cosu419** [comment]
PR approval pending for fix that set `max-page-list-length={7}` on pagination component
