### ISSUE TITLE
Adding Paul Malinowski paul.malinowski@docme360.com to DSVA Slack

### ISSUE THREAD

**Issue by melissagoshorn** [department-of-veterans-affairs/va.gov-team#71663]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

- Please add paul.malinowski@docme360.com as a full member

**Comment by melissagoshorn** [comment]
Hi! I wanted to request an update on this slack request.

**Comment by LEHigley** [comment]
resent invitation this am
