### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#71672]
### Name

Ben Brasso

### Email

ben.brasso@agile6.com

### Role

Designer / Researcher

### Team

Check In

### Product Manager (PM) name

Lori Pusey (Contractor), Kay Lawyer (OCTO)

### Additional Notes

Project under MHV on VA.gov

**Comment by benbrasso-agile6** [comment]
Bump up to Editor access please @andreahewitt-odd

**Comment by benbrasso-agile6** [comment]
TY

**Comment by naomimarcussen** [comment]
Just bumped you up. You should have edit access now. Jenny Wang has also been helping get the projects setup and is transferring ownership of those to OCTO leads, so there may be a bit of a delay on that.
