### ISSUE TITLE
Qualitative Data Request (Financial Status Report/FSR, October, November, December 2023 only)

### ISSUE THREAD

**Issue by charlottecesana** [department-of-veterans-affairs/va.gov-team#71675]
### Data Type Requested

User Surveys

### Data Source Type

Medallia

### Date Range Start

10/01/23

### Date Range End

12/11/23

### Product Name(s)

Enhanced Financial Status Report Form 5655

### Product Description

This form is for Veterans or service members who need help with debt related to VA benefit overpayments or health care copays.

### Survey URL(s), key term(s), case category or type

I am submitting a new request with the full list of URLs. We realized that the previously requested URLs were an incomplete list. Please see the full URL list below. I will submit another request for older data. 

www.va.gov/manage-va-debt/request-debt-help-form-5655/introduction
www.va.gov/manage-va-debt/request-debt-help-form-5655/veteran-information
www.va.gov/manage-va-debt/request-debt-help-form-5655/all-available-debts
www.va.gov/manage-va-debt/request-debt-help-form-5655/contact-information
www.va.gov/manage-va-debt/request-debt-help-form-5655/current-contact-information
www.va.gov/manage-va-debt/request-debt-help-form-5655/edit-mobile-phone
www.va.gov/manage-va-debt/request-debt-help-form-5655/edit-email-address
www.va.gov/manage-va-debt/request-debt-help-form-5655/edit-mailing-address
www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-information
www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-name
www.va.gov/manage-va-debt/request-debt-help-form-5655/dependents-count
www.va.gov/manage-va-debt/request-debt-help-form-5655/dependent-ages
www.va.gov/manage-va-debt/request-debt-help-form-5655/employment
www.va.gov/manage-va-debt/request-debt-help-form-5655/employment-question
www.va.gov/manage-va-debt/request-debt-help-form-5655/employment-records
www.va.gov/manage-va-debt/request-debt-help-form-5655/enhanced-employment-records
www.va.gov/manage-va-debt/request-debt-help-form-5655/employment-work-dates
www.va.gov/manage-va-debt/request-debt-help-form-5655/gross-monthly-income
www.va.gov/manage-va-debt/request-debt-help-form-5655/deduction-checklist
www.va.gov/manage-va-debt/request-debt-help-form-5655/deduction-values
www.va.gov/manage-va-debt/request-debt-help-form-5655/employment-history
www.va.gov/manage-va-debt/request-debt-help-form-5655/income/:index
www.va.gov/manage-va-debt/request-debt-help-form-5655/benefits
www.va.gov/manage-va-debt/request-debt-help-form-5655/your-benefits
www.va.gov/manage-va-debt/request-debt-help-form-5655/edit-benefits
www.va.gov/manage-va-debt/request-debt-help-form-5655/social-security
www.va.gov/manage-va-debt/request-debt-help-form-5655/social-security-records
www.va.gov/manage-va-debt/request-debt-help-form-5655/additional-income
www.va.gov/manage-va-debt/request-debt-help-form-5655/additional-income-records
www.va.gov/manage-va-debt/request-debt-help-form-5655/additional-income-checklist
www.va.gov/manage-va-debt/request-debt-help-form-5655/additional-income-values
www.va.gov/manage-va-debt/request-debt-help-form-5655/other-income-summary
www.va.gov/manage-va-debt/request-debt-help-form-5655/add-other-income
www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-information
www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-name
www.va.gov/manage-va-debt/request-debt-help-form-5655/enhanced-spouse-employment-question
www.va.gov/manage-va-debt/request-debt-help-form-5655/enhanced-spouse-employment-records
www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-employment-work-dates
www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-gross-monthly-income
www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-deduction-checklist
www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-deduction-values
www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-employment-history
www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-employment
www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-employment-records
www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse/income/:index
www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-benefits
www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-benefit-records
www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-social-security
www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-social-security-records
www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-additional-income
www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-additional-income-records
www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-additional-income-checklist
www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-additional-income-values
www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-other-income-summary
www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-add-other-income
www.va.gov/manage-va-debt/request-debt-help-form-5655/dependents
www.va.gov/manage-va-debt/request-debt-help-form-5655/dependents-count
www.va.gov/manage-va-debt/request-debt-help-form-5655/dependent-records
www.va.gov/manage-va-debt/request-debt-help-form-5655/dependent-ages
www.va.gov/manage-va-debt/request-debt-help-form-5655/cash-on-hand
www.va.gov/manage-va-debt/request-debt-help-form-5655/cash-in-bank
www.va.gov/manage-va-debt/request-debt-help-form-5655/skip-questions-explainer
www.va.gov/manage-va-debt/request-debt-help-form-5655/monetary-assets
www.va.gov/manage-va-debt/request-debt-help-form-5655/monetary-asset-checklist
www.va.gov/manage-va-debt/request-debt-help-form-5655/monetary-asset-values
www.va.gov/manage-va-debt/request-debt-help-form-5655/real-estate-assets
www.va.gov/manage-va-debt/request-debt-help-form-5655/real-estate-asset-records
www.va.gov/manage-va-debt/request-debt-help-form-5655/enhanced-real-estate-assets
www.va.gov/manage-va-debt/request-debt-help-form-5655/enhanced-real-estate-asset-records
www.va.gov/manage-va-debt/request-debt-help-form-5655/vehicles
www.va.gov/manage-va-debt/request-debt-help-form-5655/vehicle-records
www.va.gov/manage-va-debt/request-debt-help-form-5655/your-vehicle-records
www.va.gov/manage-va-debt/request-debt-help-form-5655/vehicles-summary
www.va.gov/manage-va-debt/request-debt-help-form-5655/recreational-vehicles
www.va.gov/manage-va-debt/request-debt-help-form-5655/recreational-vehicle-records
www.va.gov/manage-va-debt/request-debt-help-form-5655/other-assets
www.va.gov/manage-va-debt/request-debt-help-form-5655/other-asset-records
www.va.gov/manage-va-debt/request-debt-help-form-5655/other-assets-checklist
www.va.gov/manage-va-debt/request-debt-help-form-5655/other-assets-summary
www.va.gov/manage-va-debt/request-debt-help-form-5655/add-other-asset
www.va.gov/manage-va-debt/request-debt-help-form-5655/expenses-explainer
www.va.gov/manage-va-debt/request-debt-help-form-5655/household-expenses-checklist
www.va.gov/manage-va-debt/request-debt-help-form-5655/household-expenses-values
www.va.gov/manage-va-debt/request-debt-help-form-5655/utilities
www.va.gov/manage-va-debt/request-debt-help-form-5655/utility-records
www.va.gov/manage-va-debt/request-debt-help-form-5655/utility-bill-checklist
www.va.gov/manage-va-debt/request-debt-help-form-5655/utility-bill-values
www.va.gov/manage-va-debt/request-debt-help-form-5655/utility-bill-summary
www.va.gov/manage-va-debt/request-debt-help-form-5655/add-utility-bill
www.va.gov/manage-va-debt/request-debt-help-form-5655/repayments
www.va.gov/manage-va-debt/request-debt-help-form-5655/repayment-records
www.va.gov/manage-va-debt/request-debt-help-form-5655/credit-card-bills
www.va.gov/manage-va-debt/request-debt-help-form-5655/your-credit-card-bills
www.va.gov/manage-va-debt/request-debt-help-form-5655/credit-card-bills-summary
www.va.gov/manage-va-debt/request-debt-help-form-5655/installment-contracts
www.va.gov/manage-va-debt/request-debt-help-form-5655/your-installment-contracts
www.va.gov/manage-va-debt/request-debt-help-form-5655/installment-contracts-summary
www.va.gov/manage-va-debt/request-debt-help-form-5655/other-expenses
www.va.gov/manage-va-debt/request-debt-help-form-5655/other-expenses-checklist
www.va.gov/manage-va-debt/request-debt-help-form-5655/other-expenses-values
www.va.gov/manage-va-debt/request-debt-help-form-5655/other-expenses-summary
www.va.gov/manage-va-debt/request-debt-help-form-5655/add-other-expense
www.va.gov/manage-va-debt/request-debt-help-form-5655/skip-questions-explainer
www.va.gov/manage-va-debt/request-debt-help-form-5655/option-explainer
www.va.gov/manage-va-debt/request-debt-help-form-5655/resolution-option/:index
www.va.gov/manage-va-debt/request-debt-help-form-5655/resolution-comment/:index
www.va.gov/manage-va-debt/request-debt-help-form-5655/resolution-waiver-agreement/:index
www.va.gov/manage-va-debt/request-debt-help-form-5655/resolution-comments
www.va.gov/manage-va-debt/request-debt-help-form-5655/bankruptcy-history
www.va.gov/manage-va-debt/request-debt-help-form-5655/bankruptcy-history-records
www.va.gov/manage-va-debt/request-debt-help-form-5655/enhanced-bankruptcy-history-records
www.va.gov/manage-va-debt/request-debt-help-form-5655/review-and-submit
www.va.gov/manage-va-debt/request-debt-help-form-5655/confirmation

</google-sheets-html-origin>[www.va.gov/manage-va-debt/request-debt-help-form-5655/introduction](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/introduction)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/veteran-information](http://www.va.gov/manage-va-debt/request-debt-help-form-5655//veteran-information)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/all-available-debts](http://www.va.gov/manage-va-debt/request-debt-help-form-5655//all-available-debts)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/contact-information](http://www.va.gov/manage-va-debt/request-debt-help-form-5655//contact-information)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/current-contact-information](http://www.va.gov/manage-va-debt/request-debt-help-form-5655//current-contact-information)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/edit-mobile-phone](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/edit-mobile-phone)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/edit-email-address](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/edit-email-address)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/edit-mailing-address](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/edit-mailing-address)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-information](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-information)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-name](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-name)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/dependents-count](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/dependents-count)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/dependent-ages](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/dependent-ages)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/employment](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/employment)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/employment-question](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/employment-question)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/employment-records](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/employment-records)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/enhanced-employment-records](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/enhanced-employment-records)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/employment-work-dates](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/employment-work-dates)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/gross-monthly-income](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/gross-monthly-income)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/deduction-checklist](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/deduction-checklist)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/deduction-values](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/deduction-values)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/employment-history](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/employment-history)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/income/:index](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/income/:index)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/benefits](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/benefits)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/your-benefits](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/your-benefits)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/edit-benefits](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/edit-benefits)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/social-security](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/social-security)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/social-security-records](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/social-security-records)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/additional-income](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/additional-income)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/additional-income-records](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/additional-income-records)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/additional-income-checklist](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/additional-income-checklist)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/additional-income-values](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/additional-income-values)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/other-income-summary](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/other-income-summary)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/add-other-income](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/add-other-income)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-information](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-information)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-name](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-name)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/enhanced-spouse-employment-question](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/enhanced-spouse-employment-question)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/enhanced-spouse-employment-records](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/enhanced-spouse-employment-records)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-employment-work-dates](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-employment-work-dates)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-gross-monthly-income](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-gross-monthly-income)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-deduction-checklist](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-deduction-checklist)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-deduction-values](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-deduction-values)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-employment-history](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-employment-history)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-employment](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-employment)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-employment-records](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-employment-records)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse/income/:index](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse/income/:index)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-benefits](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-benefits)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-benefit-records](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-benefit-records)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-social-security](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-social-security)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-social-security-records](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-social-security-records)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-additional-income](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-additional-income)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-additional-income-records](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-additional-income-records)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-additional-income-checklist](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-additional-income-checklist)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-additional-income-values](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-additional-income-values)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-other-income-summary](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-other-income-summary)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-add-other-income](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/spouse-add-other-income)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/dependents](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/dependents)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/dependents-count](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/dependents-count)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/dependent-records](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/dependent-records)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/dependent-ages](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/dependent-ages)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/cash-on-hand](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/cash-on-hand)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/cash-in-bank](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/cash-in-bank)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/skip-questions-explainer](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/skip-questions-explainer)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/monetary-assets](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/monetary-assets)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/monetary-asset-checklist](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/monetary-asset-checklist)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/monetary-asset-values](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/monetary-asset-values)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/real-estate-assets](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/real-estate-assets)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/real-estate-asset-records](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/real-estate-asset-records)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/enhanced-real-estate-assets](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/enhanced-real-estate-assets)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/enhanced-real-estate-asset-records](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/enhanced-real-estate-asset-records)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/vehicles](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/vehicles)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/vehicle-records](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/vehicle-records)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/your-vehicle-records](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/your-vehicle-records)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/vehicles-summary](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/vehicles-summary)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/recreational-vehicles](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/recreational-vehicles)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/recreational-vehicle-records](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/recreational-vehicle-records)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/other-assets](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/other-assets)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/other-asset-records](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/other-asset-records)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/other-assets-checklist](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/other-assets-checklist)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/other-assets-summary](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/other-assets-summary)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/add-other-asset](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/add-other-asset)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/expenses-explainer](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/expenses-explainer)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/household-expenses-checklist](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/household-expenses-checklist)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/household-expenses-values](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/household-expenses-values)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/utilities](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/utilities)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/utility-records](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/utility-records)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/utility-bill-checklist](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/utility-bill-checklist)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/utility-bill-values](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/utility-bill-values)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/utility-bill-summary](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/utility-bill-summary)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/add-utility-bill](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/add-utility-bill)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/repayments](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/repayments)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/repayment-records](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/repayment-records)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/credit-card-bills](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/credit-card-bills)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/your-credit-card-bills](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/your-credit-card-bills)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/credit-card-bills-summary](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/credit-card-bills-summary)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/installment-contracts](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/installment-contracts)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/your-installment-contracts](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/your-installment-contracts)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/installment-contracts-summary](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/installment-contracts-summary)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/other-expenses](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/other-expenses)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/other-expenses-checklist](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/other-expenses-checklist)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/other-expenses-values](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/other-expenses-values)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/other-expenses-summary](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/other-expenses-summary)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/add-other-expense](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/add-other-expense)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/skip-questions-explainer](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/skip-questions-explainer)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/option-explainer](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/option-explainer)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/resolution-option/:index](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/resolution-option/:index)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/resolution-comment/:index](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/resolution-comment/:index)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/resolution-waiver-agreement/:index](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/resolution-waiver-agreement/:index)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/resolution-comments](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/resolution-comments)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/bankruptcy-history](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/bankruptcy-history)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/bankruptcy-history-records](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/bankruptcy-history-records)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/enhanced-bankruptcy-history-records](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/enhanced-bankruptcy-history-records)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/review-and-submit](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/review-and-submit)
[www.va.gov/manage-va-debt/request-debt-help-form-5655/confirmation](http://www.va.gov/manage-va-debt/request-debt-help-form-5655/review-and-submit)

### File Delivery Format

One file, different tab for each term/URL

### Word Cloud

Yes

### VA Email Address(es)

charlotte.cesana@va.gov, denise.coveyduc@va.gov, megan.crigger@va.gov, joseph.lee9@va.gov

### Add Assignee and Labels

If not already done so, please ensure @newworld2616 is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by newworld2616** [comment]
Hi, I have shared the requested data, please verify once you receive it. Also, I shared one more document that has list of URL's that are not available on Medallia. Thanks!

**Comment by charlottecesana** [comment]
Hi @newworld2616 thanks for the update, I have received the file. I didn't receive the other document with the list of unavailable URLs. Which are those?
Also, I would like to make the same request for the same URLs in this request with dates 1/1/2023 - 10/1/2023. Would you like me to make a separate ticket for this request? Thank you!

**Comment by newworld2616** [comment]
Hi, Thank you for confirming, I will use the same request.

**Comment by newworld2616** [comment]
Data Sent!
