### ISSUE TITLE
Inform third-party/POA requesters about how to submit requests for someone else

### ISSUE THREAD

**Issue by rachelshearerux** [department-of-veterans-affairs/va.gov-team#71699]
We are not supporting PA requests unless the signature matches the name of the LOA3 authorized applicant. 

It's possible that a third-party or power of attorney might have LOA3 authentication, but those requests are routed to FOIA, and the preferred path is for third-parties to submit FOIA requests through the existing process. 

On step 1, users will identify as a first-party U.S. citizen or non-U.S. citizen requester. 

Below those fields, we will repeat the 'Additional info' that clarifies how third-parties should complete their request

<img width="649" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlJOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d38a320bff5ab0d418e7a05df8ee602d0ce79562/Screenshot%20of%20additional%20info%20component%20on%20step%201.png" alt="Screenshot of additional info component on step 1.png" />

---

Definition of done:
- [ ] Include additional info (the same as the intro page): How do I request personal records for someone else?
- [ ] The body of the additional info includes a link to submit a [FOIA request](https://www.va.gov/FOIA/index.asp), and explains the different requirements for folks to make sure they're authorized as a third-party or power of attorney
- [ ] Confirm in staging

Docs: 
- [Sketch](https://www.sketch.com/s/314e6dbf-5b4a-422d-beb1-0ad599fc3af1/a/5nWPJwP)
- [Source of truth](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/20-10206%20FOIA%20PA%20Request/source-of-truth.md)

**Comment by jeana-adhoc** [comment]
@rachelshearerux - I think this is ready for your review on staging.

**Comment by rachelshearerux** [comment]
LGTM! 
<img width="580" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWRiQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--acc79b40029b52968ecc7d4f0c0e49b435646c1f/Screenshot%202023-12-13%20at%202.42.38%E2%80%AFPM.png" alt="Screenshot 2023-12-13 at 2.42.38 PM.png" />
