### ISSUE TITLE
Adding Alex Peguero-Cruz to DSVA Slack

### ISSUE THREAD

**Issue by huggins-va** [department-of-veterans-affairs/va.gov-team#71695]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

Please onboard Alex Peguero-Cruz as a: 

- Multi-channel user to:
- team-honeybadgers-support
- vaapi-delivery-infrastructure

Alex is a new DevOps engineer on the Lighthouse program, team Honey Badgers and New DI. 
Alex.pugero-cruz@adhocteam.us

Thank you!

**Comment by LEHigley** [comment]
couldn't add to either channel so just added to general

**Comment by LEHigley** [comment]
my invite bounced--is this the right email? @huggins-va

**Comment by huggins-va** [comment]
@LEHigley correct email is: alex.peguero-cruz@adhocteam.us 

I apologize for the typo!

**Comment by LEHigley** [comment]
couldn't add to the channels but invited to general
