### ISSUE TITLE
PA Request: Add character count for fields mapping to "Remarks"

### ISSUE THREAD

**Issue by rachelshearerux** [department-of-veterans-affairs/va.gov-team#71707]
VA Form 20-10206 instructs users to include additional helpful information about the records they're seeking, all mapping to an area on the PDF that supports ~450 characters.

To ensure that all user-generated content maps correctly, we'll include max-character counts for additional-info inputs (not including disability exam dates) that map to the same place (question 20 on the PDF).

<img width="716" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL05OQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c44cda7afea2441ffd282e653a437bdb8bd70122/Screenshot%202023-12-11%20at%205.04.34%E2%80%AFPM.png" alt="Screenshot showing a text-input with hint text below stating '40 characters allowed'" />

---
Definition of done
- [x] Add max character count to Financial records details (40 characters allowed)
- [x] Add max character count to Life insurance policy number (25 characters allowed)
- [x] Add max character count to Additional records information (335 characters allowed)
- [x] Confirm validation works as expected
- [ ] Confirm in staging

Docs:
- [USWDS component](https://designsystem.digital.gov/components/character-count/) (per the Design System Team's [guidance](https://dsva.slack.com/archives/C01DBGX4P45/p1702321865054929)) 
- [Sketch](https://www.sketch.com/s/314e6dbf-5b4a-422d-beb1-0ad599fc3af1/a/x0dPLam#Version)

**Comment by rhasselle-oddball** [comment]
should be available in staging when this shows that it is: https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/

**Comment by rachelshearerux** [comment]
Looks great on my end, @rhasselle-oddball tysm for jumping on these! 

<img width="491" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2xiQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--346201064cc4d01b39d08625d25c2d8500520775/Screenshot%202023-12-13%20at%205.20.40%E2%80%AFPM.png" alt="Screenshot 2023-12-13 at 5.20.40 PM.png" />
