### ISSUE TITLE
PA Request: Add character count for "Other compensation and/or pension record" field

### ISSUE THREAD

**Issue by rachelshearerux** [department-of-veterans-affairs/va.gov-team#71708]
VA Form 20-10206 instructs users to include additional helpful information about the type of comp and/or/pen records they're seeking, mapping to a small area on the PDF that only supports 40 characters.

To ensure that user-generated content maps correctly, we'll include a max-character count below the field and validate user data. 

<img width="198" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3BOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5a46fa37f57a99bbe490189de42c960c6a870be6/Screenshot%202023-12-11%20at%205.09.06%E2%80%AFPM.png" alt="Screenshot of text-input with hint-text below the field" />

---
Definition of done
- [ ] Add max character count to 'Describe the compensation and/or pension records you'd like to request(40 characters allowed)
- [ ] Confirm validation works as expected
- [ ] Confirm in staging

Docs:
- [USWDS component](https://designsystem.digital.gov/components/character-count/) (per the Design System Team's [guidance](https://dsva.slack.com/archives/C01DBGX4P45/p1702321865054929)) 
- [Sketch](https://www.sketch.com/s/314e6dbf-5b4a-422d-beb1-0ad599fc3af1/a/ZVRxab3)

**Comment by rhasselle-oddball** [comment]
should be available in staging when this shows that it is: https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/

**Comment by rachelshearerux** [comment]
Looks awesome - ty!

<img width="486" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3BiQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6da9c11ccfd937d6867a8ab5b1ce2c6db2b39c53/Screenshot%202023-12-13%20at%205.21.30%E2%80%AFPM.png" alt="Screenshot 2023-12-13 at 5.21.30 PM.png" />
