### ISSUE TITLE
PA Request: Add character count for "Other benefit record" field

### ISSUE THREAD

**Issue by rachelshearerux** [department-of-veterans-affairs/va.gov-team#71709]
VA Form 20-10206 instructs users to include additional helpful information about the type of benefit records they're seeking, mapping to a small area on the PDF that only supports 40 characters.

To ensure that user-generated content maps correctly, we'll include a max-character count below the field and validate user data. 

<img width="193" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzVOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--473304fe7bfd7f721143e6673e4b268c10127735/Screenshot%202023-12-11%20at%205.12.45%E2%80%AFPM.png" alt="Screenshot showing a text-input with hint-text below the field" />

---
Definition of done
- [x] Add max character count to 'Describe the benefit records you'd like to request (75 characters allowed)
- [x] Confirm validation works as expected
- [x] Confirm in staging

Docs:
- [USWDS component](https://designsystem.digital.gov/components/character-count/) (per the Design System Team's [guidance](https://dsva.slack.com/archives/C01DBGX4P45/p1702321865054929)) 
- [Sketch](https://www.sketch.com/s/314e6dbf-5b4a-422d-beb1-0ad599fc3af1/a/vRy2o04)

**Comment by rhasselle-oddball** [comment]
should be available in staging when this shows that it is: https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/

**Comment by rachelshearerux** [comment]
Looks good!

**Comment by rachelshearerux** [comment]
LGTM!
