### ISSUE TITLE
Update pending appointment page copy

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#71716]
## Description
Update the pending appts page copy to help clarify request process.

---

## Acceptance Criteria

Given a user is on the pending appointments page: ```https://staging.va.gov/my-health/appointments/pending```
When they have any number of active requests.
Then page content matches the [copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/homepage.md#pending-appointments:~:text=H1%20Pending%20appointments-,PAGE%20CONTENT,-%2D%20These%20appointment) 
And page design matches the [design spec](https://www.figma.com/file/UhAKGzqeH8vTQ1zuI6U99S/Clarify-request-empty-state-content-%7C-Appointments-FE?type=design&node-id=1380-2261&mode=design&t=KFDA0UzbAKEqIstk-4)

### Design Assets
[Design spec](https://www.figma.com/file/UhAKGzqeH8vTQ1zuI6U99S/Clarify-request-empty-state-content-%7C-Appointments-FE?type=design&node-id=1380-2261&mode=design&t=KFDA0UzbAKEqIstk-4)
All spec copy is FPO. Use copy in copy doc.

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by outerpress** [comment]
@JRRoof @Cieramaddox here's the dev ticket to cover design ticket #60855

**Comment by ldelacosta** [comment]
Validated the changes in staging. UX team to confirm. 

<img width="1563" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWJ0QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1bca119d461040a79785995f9072afd785316aa0/Screenshot%202024-03-18%20at%205.13.34%20PM.png" alt="Screenshot 2024-03-18 at 5.13.34 PM.png" />

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket.
