### ISSUE TITLE
Empty state link to schedule appointment broken

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#71713]
## Summary
The "Schedule an appointment" links in empty states lead to the home page instead of the scheduling flow.

## Specs
- Device: Mac/Laptop
- Browser: Chrome

We observed this in user research sessions and then confirmed on staging, so it's likely any browser/device.

## Steps to Reproduce
**Test User:** Any with no upcoming appointments, or pending appointments, or past appointments:

- Upcoming: TBD
- Pending: Ben Morgan
- Past: Use Granath Woolever, select April-June 2023

1. Log in and navigate to: https://staging.va.gov/my-health/appointments/
2. Review the empty state message for upcoming, pending, or past appointments
3. Click the "schedule an appointment" link at bottom of empty state messae (see screenshot)

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1JPQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b7d9a5a99f215a1c584e045f6ca8f62e78015976/Screenshot%202023-12-11%20at%205.19.39%E2%80%AFPM.png" alt="Screenshot 2023-12-11 at 5.19.39 PM.png" />

### Actual Result
_Describe what happened that was unexpected or undesired; including screenshots is encouraged_
Clicking the link to "schedule an appointment" returns the user to the main appointments page. 

* Staging URL is: `https://staging.va.gov/my-health/appointments/new-appointment`
* It should lead to the start of the scheduling flow `https://staging.va.gov/my-health/appointments/schedule/type-of-care`

### Desired Result
Clicking "schedule an appointment" should lead to the scheduling flow.

## Definition of Done
- [ ] Desired result is achieved and/or document decisions made
- [ ] Relevant documentation is updated

**Comment by outerpress** [comment]
FYI @marcynadeau in case you already have a ticket for this.

**Comment by JRRoof** [comment]
Blocked by Github issue [#72066](https://github.com/department-of-veterans-affairs/va.gov-team/issues/72066)

**Comment by ldelacosta** [comment]
@outerpress - if you can validate this bug ticket.

**Comment by outerpress** [comment]
Looks good! I tested with `vets.gov.user+0@gmail.com` and the empty state links all open the scheduling flow. @ldelacosta

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket.
