### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by BlakeOrgan** [department-of-veterans-affairs/va.gov-team#71715]
### Name

Blake Organ

### Email

blake.organ@civicactions.com

### Role

Product Designer

### Team

VFS CMS

### Product Manager (PM) name

Marcia Ortiz

**Comment by naomimarcussen** [comment]
Hi! You should have edit access now. There's a project placeholder for you called CMS Platform. Amanda Klausmeier is the owner of that project and can invite you in. 

Let me know once you're in or if you're still having trouble.

**Comment by BlakeOrgan** [comment]
I'm in! Thank you!
