### ISSUE TITLE
Qualitative Data Request (Combined Debt Portal - February 2023 - present)

### ISSUE THREAD

**Issue by charlottecesana** [department-of-veterans-affairs/va.gov-team#71710]
### Data Type Requested

User Surveys

### Data Source Type

MyVA.411

### Date Range Start

02/01/23

### Date Range End

12/11/23

### Product Name(s)

Combined Debt Portal

### Product Description

Combined Debt Portal on va.gov is there to help Veterans understand why they have debt, what the status of their debt is, and what steps they need to take to resolve their debt. The portal includes both benefit overpayments as well as medical copays. Veterans are also able to complete and submit an online Financial Status Report (VA Form 5655) to request that their debt be waived.

### Survey URL(s), key term(s), case category or type

https://www.va.gov/manage-va-debt/summary/
https://www.va.gov/manage-va-debt/summary/debt-balances
https://www.va.gov/manage-va-debt/summary/debt-balances/details/${selectedId}
https://www.va.gov/manage-va-debt/summary/debt-balances/letters
https://www.va.gov/manage-va-debt/summary/copay-balances
https://www.va.gov/manage-va-debt/summary/copay-balances/${selectedId}/detail

### File Delivery Format

One file, different tab for each term/URL

### Word Cloud

Yes

### VA Email Address(es)

charlotte.cesana@va.gov, denise.coveyduc@va.gov, megan.crigger@va.gov, joseph.lee9@va.gov

### Add Assignee and Labels

If not already done so, please ensure @newworld2616 is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by newworld2616** [comment]
Hi I have shared the requested data, however 2 URL's I was not able to find them on the Medallia site. 
[https://www.va.gov/manage-va-debt/summary/debt-balances/details/$
[https://www.va.gov/manage-va-debt/summary/copay-balances/${selectedId}/detail]
Please, let me know once you receive the file. Thank you.

**Comment by charlottecesana** [comment]
Hello, I have received the file. Thank you for the fast turnaround @newworld2616

**Comment by mgleo** [comment]
Hi @newworld2616,
Do you know where comments may be stored on pages with custom IDs in the URLS _${selectedId}_? 
There are working blue Feedback buttons on the pages (see screenshots below). 

Screenshot for
**https://www.va.gov/manage-va-debt/summary/debt-balances/details/${selectedId}**

<img width="969" alt="debt-detail" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/5553542/0c6651cc-94d9-4348-ab68-34ab87f63ec0">


Screenshot for
**https://www.va.gov/manage-va-debt/summary/copay-balances/${selectedId}/detail**

<img width="969" alt="copay-detail" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/5553542/fa43a9ff-65e0-41ae-83a1-a80d4d54f4be">

**Comment by newworld2616** [comment]
Thank you for confirming!
