### ISSUE TITLE
[MVP] Step 5 Financial information, expenses: Create new page and 7 new questions for Add an unreimbursed care expense & multi-entry

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#71727]
## Note
Part of the larger effort to update the existing 527EZ form to add missing fields/info and remove depreciated fields.

## Description
On Step 5 of Financial Information: expenses,

- Create a new page for the new `Add an unreimbursed care expense` questions, 7 new questions
- Include multi-entry option for the same questions

## Designs
- Lo-fi mockup [available in MURAL here](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1702306770345/6a3909358396e0ee7fc0f5d411a7944a9e59e29f?wid=1-1702308504770) shown as the V2 In-home care or care facility flow.
- Sketch prototype of this 2-step flow w/list loop: https://www.sketch.com/s/94592459-f741-45a0-9432-efd685b9a1d5/prototype/4C69E169-BE3A-4F60-9515-27A4542D04DE/a/4C69E169-BE3A-4F60-9515-27A4542D04DE

## Acceptance Criteria

**New page:**
1 new page is created under Step 5 of form, this lives under the Financial information: expenses.

Page sub header: `Add an unreimbursed care expense states`

**Questions/fields for this page:**

**First question:**
Add the following required radio button question/field:
`Who received care? (*Required)`
`Veteran`
`Veteran's spouse`
`Veteran's child` Enter the veteran's child - _This option will also have a short text field_

**Second question:**
Add the following required short text question/field:
`What's the name of the care provider? (*Required)`

**Third question:**
Add the following required radio button question/field:
`Who provided the care? (*Required)`
`Care facility`
`In-home care attendant`

**Fourth question:**
Add the following dollar & number question/fields (NOT required):
`If this is an in-home care provider, what is the rate per hour?`
$ Rate per hour - _This a dollar/number field_
Hours worked per week - _This is a number field_

**Fifth question:**
Add the following required date fields:
`Care start date` MM/DD/YYYY
`Care end date` MM/DD/YYYY
Add checkbox for `No end date`

**Sixth question:**
Add the following required radio button question/field:
`How often were the payments? (*Required)`
`Once a month`
`Once a year`
`One-time`

**Seventh question:**
Add the following required dollar/number question/field:
`How much was each payment? (*Required)`

Add a button for: `Add another care expense`

**Please note:** If they have additional care expense sources, they will see the list loop, multi-entry functionality available, as shown on the designs.

**Validation info:**
If they have additional care expense sources, they will see the list loop, multi-entry functionality available, as shown on the designs.

Once they finish adding any additional care expense sources, the next page/question will be: Did you pay any medical or other unreimbursed expenses? , as shown on #71728

**Match copy:**
Ensure all copy, including headers, questions and buttons match the designs.

## Tasks
[Software Development Tasks](https://docs.google.com/document/d/1vtn5co_YzGl1cFRNrIBAdjf53dmfH4_EXBWK8C5mU9Y/edit?usp=sharing)

- [ ] Front-end work

## Review
- [ ] Someone else on team signed off on pages in staging

## Artifacts
- [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/527EZ-reactivation-initiative-brief.md)
- [Content source of truth/PDF form](https://www.vba.va.gov/pubs/forms/VBA-21P-527EZ-ARE.pdf)
- [Link to testing accounts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/form-deactivation/527EZ-staging-test-accounts-accessible.md)
- [Link to staging](https://staging.va.gov/)

**Comment by vbellissimo** [comment]
For PDF mapping purposes...

- These questions will map to Section 10 of the PDF form. 10B(1) through 10D(6).
- If they enter more than 3 expenses for this section, the data should be allowed as additional info at the bottom of the PDF

**Comment by jstrothman** [comment]
Per Slack thread, instead of adding a "No end date" checkbox, we'll make "Care end date" not required and infer no end date for the pdf.

Legend: Care end date
Hint: Leave blank if there's no end date
[Date fields]

**Comment by aplatt-coforma** [comment]
Content looks good.<img width="622" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWgxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4641ff8a414d2f67d8bd61f897b5ff5105e25a94/Screenshot%202023-12-19%20at%203.25.51%E2%80%AFPM.png" alt="Screenshot 2023-12-19 at 3.25.51 PM.png" />
<img width="276" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXAxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e6d327fcb9d6be310c3f88ae905c3259a8284c9d/screencapture-staging-va-gov-pension-application-527EZ-financial-care-expenses-add-2023-12-19-15_25_57.png" alt="screencapture-staging-va-gov-pension-application-527EZ-financial-care-expenses-add-2023-12-19-15_25_57.png" />

Form pages after are correct.
