### ISSUE TITLE
Adding additional DSVA Slack channels for Derrick Ellerbie 

### ISSUE THREAD

**Issue by huggins-va** [department-of-veterans-affairs/va.gov-team#71724]
Please add Derrick Ellerbie
derrick.ellerbie@agile6.com
derrick.ellerbie@va.gov

add to the following channels:
api-benefits-claims
team-dash

Derrick Ellerbie is a SWE funded through Accredited Representative Management Program and also embedded on Team Dash (Lighthouse program). 

Thank you!

Are you requesting to add an individual as a:

- Full member
- Single guest
- Multi-channel
- Switching from single-channel to multi-channel?
- What channel(s) do they need to be added to?

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add [_insert email_] as a single-channel guest to [_channel name_].
- Please add [_insert email_] as a multi-channel guest to these channels: [_channel names_].
- Please add [_insert email_] as a full member.
- Please change the status of [_slack username_] from [_current status_] to [_desired status_]

**Comment by LEHigley** [comment]
@huggins-va wasn't clear to me if it should be full member or multi channel so just doing multi channel. please specify that in the future. i also could only add to team dash
