### ISSUE TITLE
Yellow ribbon search results display count not updating correctly

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#7173]
## What happened?
If you conduct a search in the yellow ribbon tool and go to page 2 or beyond, and then update the search, the `Displaying x of xx results` number is incorrect.  It's displaying the page number in front of the first digit.

## Specs:
- Device: Macbook
- Browser: Chrome

## Steps to Reproduce
- URL: https://staging.va.gov/education/yellow-ribbon-participating-schools/
1. Go to the URL and just press search without entering anything
2. View the results, navigate past page 1 via the pagination.  I clicked on page 6, randomly
3. Scroll up and enter a search term. I used `Cambridge`
4. Check out the `Displaying X results` text. It'll say `11-8 of 8 results` if you clicked on page 2, or `21-8 of 8 results` if you clicked on page 3, etc

## Desired behavior
The `Displaying x of xx results`  should reflect the correct number of cards that are displaying

## Acceptance Criteria
- [ ] The `Displaying x of xx results` reflects the correct number of cards that are displaying

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by kelsonic** [comment]
The source of this problem was not resetting `page` in Redux back to `1` on a new search.

**Comment by MickinSahni** [comment]
2020-04-01 PR Standup
- Waiting to be deployed and then will validate

**Comment by MickinSahni** [comment]
Validated. Now resetting page results to start back at 1. 

![image](https://user-images.githubusercontent.com/13204473/78269651-e232eb80-74d7-11ea-9fd2-79e7f547e8b0.png)
