### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#71737]
### Name

Eileen Chi

### Email

eileen.chi@coforma.io

### Role

Designer

### Team

Appeals - Benefits Decision Review

### Product Manager (PM) name

Sade Ragsdale

### Additional Notes

I have Figma workspace edit access, but I don't have access to edit to within the 'Appeals' project folder.

**Comment by naomimarcussen** [comment]
You should have editor access now.

**Comment by eileen-coforma** [comment]
I have editor access for the workspace, but not for this specific project: https://www.figma.com/files/project/176170255/Appeals?fuid=1141788357697076960

I can't import or create files within the project.

**Comment by naomimarcussen** [comment]
Hi! Are you able to import and create files in your project now?

**Comment by eileen-coforma** [comment]
Yes, thank you!

**Comment by naomimarcussen** [comment]
Great!
