### ISSUE TITLE
[MVP] Step 5 Financial information, expenses: Create new page and 6 new questions for Add a medical or other unreimbursed expense & multi-entry

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#71730]
## Note
Part of the larger effort to update the existing 527EZ form to add missing fields/info and remove depreciated fields.

## Description
On Step 5 of Financial Information: expenses,

- Create a new page for the new `Add a medical or other unreimbursed expense` questions, 7 new questions
- Include multi-entry option for the same questions

## Designs
- Lo-fi mockup [available in MURAL here](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1702306770345/6a3909358396e0ee7fc0f5d411a7944a9e59e29f?wid=1-1702308504770) shown as the V2 Medical, last illness, and/or burial expenses flow.
- Sketch prototype of 2-step form flow with list loop: https://www.sketch.com/s/94592459-f741-45a0-9432-efd685b9a1d5/prototype/9FF7DBED-F0E4-4286-B1BA-BDD4F0F903E0/a/9FF7DBED-F0E4-4286-B1BA-BDD4F0F903E0

## Acceptance Criteria

**New page:**
1 new page is created under Step 5 of form, this lives under the Financial information: expenses.

Page sub header: `Add a medical or other unreimbursed expense`

**Questions/fields for this page:**

**First question:**
Add the following required radio button question/field:
`Who was the expense for? (*Required)`
`Veteran`
`Veteran's spouse`
`Veteran's child` Enter the veteran's child - _This option will also have a short text field_

**Second question:**
Add the following required short text question/field:
`Who received the payment? (*Required)`

**Third question:**
Add the following required short text question/field:
`What was the payment for? (*Required)`

**Fourth question:**
Add the following required date fields:
`What was the date of the payment?`
MM/DD/YYYY

**Fifth question:**
Add the following required radio button question/field:
`How often were the payments? (*Required)`
`Once a month`
`Once a year`
`One-time`

**Sixth question:**
Add the following required dollar/number question/field:
`How much was each payment? (*Required)`

Add a button for: `Add another unreimbursed expense`

**Please note:** If they have additional medical or other expense sources, they will see the list loop, multi-entry functionality available, as shown on the designs.

**Validation info:**
If they have additional medical or other expense sources, they will see the list loop, multi-entry functionality available, as shown on the designs.

Once they finish adding any additional medical or other expense sources, the next page/question will go to Step 6 of the form flow, which is for Direct deposit and document upload.

**Match copy:**
Ensure all copy, including headers, questions and buttons match the designs.

## Tasks
[Software Development Tasks](https://docs.google.com/document/d/1vtn5co_YzGl1cFRNrIBAdjf53dmfH4_EXBWK8C5mU9Y/edit?usp=sharing)

- [ ] Front-end work

## Review
- [ ] Someone else on team signed off on pages in staging

## Artifacts
- [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/527EZ-reactivation-initiative-brief.md)
- [Content source of truth/PDF form](https://www.vba.va.gov/pubs/forms/VBA-21P-527EZ-ARE.pdf)
- [Link to testing accounts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/form-deactivation/527EZ-staging-test-accounts-accessible.md)
- [Link to staging](https://staging.va.gov/)

**Comment by vbellissimo** [comment]
For PDF mapping purposes...

- These questions will map to [Section 10 of the PDF form](https://www.vba.va.gov/pubs/forms/VBA-21P-527EZ-ARE.pdf). 10E(1) through 10J(6).
- If they enter more than 6 expenses for this section, the data should be allowed as additional info at the bottom of the PDF

<img width="565" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2xVQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eabf7e6cd739a363ab48eaf008810416866f2502/Screenshot%202023-12-12%20at%203.59.23%E2%80%AFPM.png" alt="Screenshot 2023-12-12 at 3.59.23 PM.png" />

**Comment by vbellissimo** [comment]
@danlim715 just sending a note to please double check against the copy provided on the Sketch prototype: https://www.sketch.com/s/94592459-f741-45a0-9432-efd685b9a1d5/a/4ov13Mq/play Sketch prototype should be the source of truth for this task. Thank you!

**Comment by danlim715** [comment]
@vbellissimo I just noticed this, but was this work already completed as part of [this other ticket](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/gh/department-of-veterans-affairs/va.gov-team/71727)?

**Comment by vbellissimo** [comment]
@danlim715 no, that ticket you pointed to is a different new page from this one.
