### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by keithcheung828** [department-of-veterans-affairs/va.gov-team#71749]
### Name

Keith Cheung

### Email

keith.cheung@agile6.com

### Role

UX Designer

### Team

MHV Team (Agile Six)

### Product Manager (PM) name

Patrick Bateman

**Comment by naomimarcussen** [comment]
Hi! I just sent you an invite. Let me know once you've created an account and I'll bump you up to editor.

**Comment by naomimarcussen** [comment]
I made you an editor so you should be good to go now. Let me know if you have any issues getting into your project.
