### ISSUE TITLE
BE | Maintenance Period Alerts | Identify All Notification Avenues

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#71748]
## Background 
We need to identify all of the areas where we would be notified of outages so we can use this to update pager duty each week with the appropriate maint. windows. 

If possible, consolidate these in one central location? Can we be notified of these? 

## Tasklist 
- [x] Identify list of external services (BGS, Lighthouse, VA Profile, etc.)
     - [ ] ~~BGS (BIS)~~
     - [x] VA Profile (added to email distro list)
     - [x] Lighthouse (status updates are now sent to #accountexp-authexp-alerts channel)

## Acceptance Criteria 
- [x] We have a list of where to locate downtime windows

This story is identifying services and mapping them to FE components (builds upon #72281)

**Comment by tpharrison** [comment]
- Reached out to Mike Richards at VA Profile and asked to be added to the distro list for outage notifications.
- Submitted a request to Lighthouse to request maintenance window alerts be sent to our #accountexp-authexp_alerts slack channel.

**Comment by tpharrison** [comment]
Closing this out.  If BGS replies, I will update.
