### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by jamiefiore** [department-of-veterans-affairs/va.gov-team#71744]
### Name

Jamie Fiore

### Email

jamie.fiore@va.gov

### Role

UX Designer

### Team

Integrated Veteren Care (IVC)

### Product Manager (PM) name

Premal Shah

**Comment by naomimarcussen** [comment]
Just sent an invite. Let me know when you've created an account and I'll bump you up to editor.

**Comment by jamiefiore** [comment]
Thank you @naomimarcussen. I just created my account.

**Comment by naomimarcussen** [comment]
Great! Just made you an editor.

**Comment by jamiefiore** [comment]
Thank you!
