### ISSUE TITLE
Analytics Implementation or QA Support for Public Websites [Find VA Forms Search]

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#7174]
# Analytics Implementation or QA Request
 
## Description
- **Is this request for Google Analytics implementation or QA?**
Google Analytics implementation (and Foresee?) 

- **Who is this request for?**
    - @jenniferlee-dsva , @MickinSahni 
    
- **What team/project is this work for?**
  - Public Websites 

- **Provide the Domain where Google Analytics needs to be implemented**
  - https://www.va.gov/find-forms
    
- **Please provide any upcoming deadlines or important milestones**
  - We're soft launched in prod already and currently implementing a more mobile-friendly design. - Mid-April (4/17)
     
- **Typical Website Interactions to Track**

    - PDF Downloads - for all form search results e.g. https://www.va.gov/find-forms?q=health
    - Top Tasks: 
      1. https://www.va.gov/disability/file-disability-claim-form-21-526ez
      2. https://www.va.gov/education/apply-for-education-benefits/application/1990
      3. https://www.va.gov/health-care/apply/application
    - Manage your VA and other information online:
      1. https://www.va.gov/change-your-va-direct-deposit-and-contact-information
      2. https://www.va.gov/change-address
      3. https://www.va.gov/records/get-military-service-records
      4. https://www.va.gov/records
    - More information
      1. https://www.va.gov/life-insurance/options-eligibility
      2. https://www.esd.whs.mil/Directives/forms/
      3. VaFormsManagers@va.gov 

- **No authentication** however, see Public Websites team for creds to get behind soft launch auth

- **Certain conditions/responses that need to be reviewed** - n/a

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by MickinSahni** [comment]
@joanneesteban if it's helpful, this would be a higher priority request than our other Yellow Ribbon analytics request #7199

**Comment by jonwehausen** [comment]
### Notes from Mickin and I's Slack Conversation
1) Launch date has been moved to Mid-April
2) Would like a GA dashboard to support this request
3) Looking for baseline metrics for va.gov/vaforms

**Comment by MickinSahni** [comment]
> #### Notes from Mickin and I's Slack Conversation
> 1. Launch date has been moved to Mid-April
> 2. Would like a GA dashboard to support this request
> 3. Looking for baseline metrics for va.gov/vaforms
> 
> cc: @MickinSahni @joanneesteban

Thanks, Jon. I probably should've mentioned 2) somewhere in the request. Sorry about that. Bc this is a [high-trafficked portion of the site](https://va.gov/vaforms) that the VA is trying to improve, a long-lasting dashboard + 3) is prob in our best interests.

**Comment by jenniferlee-dsva** [comment]
^ To above list, could we also add: https://www.gsa.gov/reference/forms ?  We link to this site from the error message. 

We want to see how many ppl really are looking for external forms on VA forms search; stakeholders are convinced it is legions. If data shows true, we'll make this link part of normal body content. 

I think Nedie provided baseline data when we began this work quite awhile ago. You should be able to find it as a closed ticket in the epic even.

**Comment by MickinSahni** [comment]
Didn't know that! Thanks!

https://www.va.gov/find-forms?q=fdasff241df
 
<img src="https://user-images.githubusercontent.com/13204473/78176005-ccff8380-7429-11ea-991c-d079aa4c6337.png" width="300px">

**Comment by jonwehausen** [comment]
### Datalayer Requirements

### READ ME - Developer Notes
- Dynamically populate the DL variable ```featured-content-header``` with the header for each blue box

Interaction | Screenshot | Datalayer Requirements
------------ | -------------  | -------------
Clicks on Top Tasks blue featured content (Read more) | ![image](https://user-images.githubusercontent.com/48527022/78290004-09e27d80-74f1-11ea-90d5-e3febfb78904.png) | ```dataLayer.push({```<br>```'event':'nav-featured-content-link-click',``` <br>```'featured-content-header': 'File a VA disability claim'```<br>```});``` | 
Clicks on links within "Manage your VA and other information online" section | ![image](https://user-images.githubusercontent.com/48527022/78290306-8e350080-74f1-11ea-9702-69cafc30c25f.png) | ```dataLayer.push({```<br>```'event':'nav-header-link'```<br>```});``` | 
Clicks on links within "More information" list | ![image](https://user-images.githubusercontent.com/48527022/78290447-c2102600-74f1-11ea-8939-d19081ef3ab1.png) | ```dataLayer.push({```<br>```'event':'nav-linkslist'```<br>```});``` |

**Comment by jonwehausen** [comment]
### Existing tracking
@MickinSahni @jenniferlee-dsva 

✅ We currently have tracking on the PDF downloads that are returned following a search
✅ The clicks to "GSA Forms Library" are also currently tracked as outbound link clicks

**Comment by MickinSahni** [comment]
Associated ticket for Public Websites team implementation: https://github.com/department-of-veterans-affairs/va.gov-team/issues/7691

**Comment by jonwehausen** [comment]
### DL Testing

@MickinSahni @bsmartin-ep 
Tested at: https://staging.va.gov/find-forms?q=health

Description of Interaction | Screenshot | Status
------------ | ------------- | ------------- 
Click on each of the blue featured context box | ![image](https://user-images.githubusercontent.com/48527022/79363699-385f5000-7f16-11ea-891a-0160ddaffb41.png) | ✅ **PASSED**
Click on links within the "More Information" section | ![image](https://user-images.githubusercontent.com/48527022/79363906-85432680-7f16-11ea-995a-9f01fe0e856e.png) | ❌ **DOES NOT PASS** <br> - @MickinSahni I believe we settled on these clicks being tracked as `nav-linkslist` -- [per ticket here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7691)
Clicks on links within the "More Information" grey box | ![image](https://user-images.githubusercontent.com/48527022/79364067-cb988580-7f16-11ea-9c58-1c54fb53e736.png) | ✅ **PASSED**

**Comment by jonwehausen** [comment]
@bsmartin-ep For the featured content (blue boxes), can I task you with cleaning up the Event Action taxonomy as it relates to these clicks. Keep in mind this is used in other places so we'll want to account for when we have a `featured-content-header` and when we dont. 

Let's touch base on your solution / update.

**Comment by bsmartin-ep** [comment]
@jonwehausen -

Here are the linkslist changes to dynamically pull the header...

https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000265

**Comment by jonwehausen** [comment]
### Google Analytics Dashboard
cc: @MickinSahni @stephorkandatx 

- Please find our WIP GA dashboard for find va forms [here - Titled Find Forms Dashboard (WIP Prototype)](https://analytics.google.com/analytics/web/#/a50123418w177519031p176188361/report/dashboard)

**Comment by stephorkandatx** [comment]
@jonwehausen we have queued up the work necessary to have tracking for the "Manage your VA and other information online" section. As mentioned in our review, it is currently not trackable and not included on the dashboard. 

When our work is complete, would you want me to update this ticket to request the section added to the dashboard or a new ticket? 

FYSA here is the ticket for our work - https://github.com/department-of-veterans-affairs/va.gov-team/issues/8177

**Comment by jonwehausen** [comment]
Hi @stephorkandatx ,

Yes please let us know when your work around this is complete. Feel free to link the 8177 ticket here as well. 

Thanks, 
Jon Wehausen

**Comment by stephorkandatx** [comment]
Hi @jonwehausen the work for #8177 is complete

**Comment by bsmartin-ep** [comment]
@stephorkandatx -

I'm seeing `nav-linkslist` events on staging, so I think we're good...

![image](https://user-images.githubusercontent.com/62304138/81110217-3c650900-8ee9-11ea-9e1a-1f4dacfa3d32.png)

Let us know if you need a custom report or something to display all of these dimensions.

**Comment by stephorkandatx** [comment]
Thank you!
