### ISSUE TITLE
Box.com discovery

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#71754]
What's the story with Box.com and how might its implementation at the VA be useful for our work?

**Acceptance criteria**
- We have an understanding of how we would transmit files/data to Box.com
- We have an understanding of what happens once files or data are sent there
- We understand at a high level how to use Box.com appropriately (security, etc)
- We have an understanding of how to monitor this integration
- We have an understanding of how to test this integration
- We have our understanding of the above documented for future reference

**Comment by pshahVA** [comment]
Hey, I'm not sure how much time we want to spend on this, as I'm thinking that I'm hoping that we can directly write to an s3 bucket, bypassing box.

**Comment by baltes** [comment]
@pshahVA We can hang onto this for now but I'll create a new one for S3 and we can move that higher in prioritization.
