### ISSUE TITLE
Design Feedback: Usability Testing Prep - Auth Experience -- [Profile 2.0]

### ISSUE THREAD

**Issue by CrystabelReiter** [department-of-veterans-affairs/va.gov-team#7175]
**User story:**
VSP design feedback on Auth Experience -- [Profile 2.0]

Template prototype we're reviewing: 
Desktop prototype  https://vsateams.invisionapp.com/share/FJW9OGY2B9A
-Mobile prototype (same as above): https://vsateams.invisionapp.com/share/34WJ8JOCMAB

**Do:**

- Minor inconsistencies in spacing on the Personal and contact information page: Table headings ("Addresses, Phone numbers, Email address") are slightly off center vertically compared to the table headings on the other pages - this is also the case on the Direct Deposit page

- On the Military Information, there are a few typos in the  Additional info component: ("Veterance", "DEfence")

- Direct Deposit flow: Account type isn't marked as required on edit screen but is on the error screen. Assuming it should be marked required here.

- The placeholder contents for Routing number and Account number are addresses - change them to fake data types that match the input

- "We're sorry" message on Bank Information screen - change to "Warning" alert type instead of info alert type (reference: https://design.va.gov/patterns/messaging-dictionary#system-messaging)

- On all screens on mobile: Switched header to authenticated header (it currently says "Sign in")

**Try**

- On the desktop “edit address” page, the bottom of the title cards seem cut off (Addresses, Phone numbers, and email address)

- Alignment with the title of the card is a little off on some pages -- On the Personal and Contact Information pages (Addresses, Phone numbers, and Email Address seems off) and on the direct deposit information (Bank information seems off)

**Definition of Done**

- [x] Incorporate the **Do** feedback, and let us know on this ticket when they are updated mockups to check out

- [x] Leave any comments for feedback you decide _not_ to take

Emily or Crystabel will close the ticket once those things are all set. Thank you Tressa!

**Comment by tressaellen** [comment]
Hi @CrystabelReiter  - I've updated the mocks in invison - let me know if you have any other feedback!

**Comment by CrystabelReiter** [comment]
Hi @tressaellen  This looks great. The hotspots seem off in the military information section on the desktop, but other than that, this looks ready to go!
