### ISSUE TITLE
Update One-Pager with Content and Dates

### ISSUE THREAD

**Issue by lmorris3** [department-of-veterans-affairs/va.gov-team#71752]
## Problem

We created a flyer or "one-pager" at the request of MHV coordinators as something that can be printed and distributed at VA facilities to help spread the word about the move to secure sign in credentials. Now that the effort is getting relaunched, we need to make some updates to the document.

## User Story

As a Veteran, I need to know about changes coming to sign in methods so I can start using the newer, more secure sign in options and don't lose access to my benefits. 

## Acceptance Criteria

- include ID.me where Login.gov is mentioned (i.e. Login.gov and ID.me are the recommended secure sign in options)
- include the legacy sunset date in the messaging - December 31, 2024.
- update illustrations to use approved Veteran-facing symbols (not illustrations of people)

**Comment by SophiaPhilipMO** [comment]
See Figma from Josie - https://www.figma.com/file/8vobVoSl1UqLnXsni3rcvO/Login.gov-Adoption%3A-Design-Flows?type=design&node-id=511%3A2931&mode=design&t=4GFfVyxZ0YDU9Bti-1

**Comment by skirkman16** [comment]
Final approved draft [1 Pager v5.4.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmFXQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6222e6464f4322c9cfee3509688a9f192ba04192/1%20Pager%20v5.4.pdf)
