### ISSUE TITLE
[Contact Center User Feedback] URL for COVID-19 Feedback

### ISSUE THREAD

**Issue by Kimberley2019** [department-of-veterans-affairs/va.gov-team#7176]
**Issue Description:** User provided feedback on current COVID-19 URL, which is included in the description below.  Unsure if any modifications can be made from users suggestions, but wanted to pass along in case there were.

**Priority:** Low

**Total Number of Issues:** 1

**Issue Number and User Description:** IRIS 200319-000052 

_Dear VA,_

_I am writing to make a request for two small improvements to a web page on the VA's website. This web page has the title ""Novel Coronavirus Disease (COVID-19)"". This web page is located at this URL: ""https://www.publichealth.va.gov/n-coronavirus/index.asp""._

_This web page lists (among other things) the number of known Veteran patients with a COVID-19 diagnosis, in each of those VA sectors where there has been at least one known Veteran COVID-19 diagnosis. The page also lists the number of known Veteran deaths that are related to COVID-19._

_The VA web page described above does not tell in which VA sector the death(s) have occurred. Also, the names used for some of the VA sectors it lists do not make it easy to tell where the sector is located. One sector's name (""NOLA"") is just an acronym, and I found it rather difficult to figure out exactly where that sector is._

_I request that the VA include the sector names for the locations where the Veteran deaths related to COVID-19 have occurred. I also request that the sector names be improved, so that it will be easier for us to know where the sectors are located. Just by adding a state designation to the sector name, such as ""Togus, ME"", instead of just ""Togus"", would help a great deal._

_Thank you for your consideration in this matter, and thank you very much for providing us this web page."_

**Comment by joanneesteban** [comment]
@clantosswett @Kimberley2019 @joanneesteban - Regroup to see where this should be placed (not a Tier 3 issue, but a user suggestion).

**Comment by Kimberley2019** [comment]
@joanneesteban You are correct.  It is not a Tier 3 issue, but good feedback none the less.  Maybe it would be beneficial to present to the VSP- Operations channel or the VSP Product Support channel.
Of course I do not mind sending it to another group, I just want to ensure I am sending it to the correct group (VSF vs VSP).

**Comment by Kimberley2019** [comment]
Lauren Alexanderson stated: There is a new access to care site:
https://www.accesstocare.va.gov/Healthcare/COVID19NationalSummary

Try to send this back to the individual that sent the original feedback.

**Comment by Kimberley2019** [comment]
This link has been provided to the user.
