### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by syd-hoeper** [department-of-veterans-affairs/va.gov-team#71761]
### Name

Syd Hoeper

### Email

syd.hoeper@adhocteam.us

### Role

Senior Designer

### Team

IVC Forms (CHAMPVA)

### Product Manager (PM) name

Devi Hill, Mary Wang, Bo Altes

**Comment by naomimarcussen** [comment]
Just sent an invite. Let me know once you've created an account and I'll bump you up to editor.

**Comment by syd-hoeper** [comment]
Just joined under my existing Figma account using ***@***.***

Thanks!

**Comment by naomimarcussen** [comment]
Great! You're now an editor. :)
