### ISSUE TITLE
Prototype for usability testing

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#71769]
Create prototype as part of the user research work so that it can be put in front of users for feedback. 

Acceptance criteria:
- end to end user flow is mapped out in VA figma
- form 10-10d content only
- show unauthenticated and authenticated paths(?)
- error states and conditional states noted
- leverage design system and existing patterns
- follows accessibility standards
- intended to meet needs for research review, also needed for [midpoint review ](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)

Dependency: 
- Figma access

**Comment by brian-wilke** [comment]
This ticket should probably be in Sprint 8. (Sprint 6 is too soon)

**Comment by syd-hoeper** [comment]
WIP: https://www.figma.com/file/Rnq4uKAlSUnVPD31fViTcj/10-10d-Prototype?type=design&node-id=228%3A94731&mode=design&t=YzfSlqo80v95kkCf-1

**Comment by syd-hoeper** [comment]
Figma link, ready for pass off: https://www.figma.com/file/Rnq4uKAlSUnVPD31fViTcj/10-10d-Prototype?type=design&node-id=508-73596&mode=design
