### ISSUE TITLE
[BE] Create simple DD dashboard for check ins and initiated check ins for Jeff Lowe]

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#71779]
## Background
We are being asked to create a new Data Dog dashboard; please refer to this [Slack thread](https://dsva.slack.com/archives/C022AC2STBM/p1702057770226089?thread_ts=1701792397.579879&cid=C022AC2STBM)

Please ask any clarifying questions in the slack thread.

## Tasks
- Create new Data Dog dashboard per the slack thread
    - Dashboard needs to be "public" or at least accessible by Jeff Lowe, Kay Lawyer, Kristen McConnell, Stephen Barrs, & Mark Dewey & the team.
- Post a link to the new dashboard in the slack thread

**Comment by lee-delarm6** [comment]
https://tevi.ddog-gov.com/dashboard/cg3-fj4-vnz?refresh_mode=sliding&from_ts=1702060250000&to_ts=1702665050000&live=true

All set and passed by Kay. They said they will respond if other people want more data points
