### ISSUE TITLE
Design for COVID-related changes in facility availability

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#7177]
### User Story
As a Veteran, I need to know when the hours of operations for a facility have been impacted by an emergency so that I can adjust my plan to visit. 

## Goals
Determine a method for alerting veterans to changes in facility availability during emergency situations

## Current use cases: 
Due to COVID 19:
- Some facilities are not open for physical visitation but may be able to provide assistance by phone or other method (ie: Benefits)
- [Funeral policies may have changed](https://www.cem.va.gov/alerts.asp)
- Availability may have been impacted nationally across a Facility type or may be subject to municipal/state shelter in place policy
- Display should be available down to level of facility sub-type at a minimum (if not at the facility level)

## Potential use cases: 
If possible, design component might be reusable for other emergencies (ie: flooding at cemetery) or even events (ie: high need blood drive in certain area). 

## Tasks
[ ] Create low fidelity prototype for possible immediate implementation, based on COVID-19 need
[ ] touch base with Ryan Thurlwell for insight into other similar work in development across VA.gov system

Acceptance Criteria
[ ] Low fidelity prototype or mock-up 
[ ] Request for Design Collaboration meeting 
[ ] Alert/Banner/Display is available for at facility sub-type level at a minimum

**Comment by mmiddaugh** [comment]
Examples for context: 
From https://www.benefits.va.gov/washington/

![image](https://user-images.githubusercontent.com/55411834/77458432-c9ce1d00-6dc3-11ea-9899-2805db63dd4f.png)

And from NCA: https://www.cem.va.gov/cems/nchp/alexandriava.asp

![image](https://user-images.githubusercontent.com/55411834/77458526-ef5b2680-6dc3-11ea-829e-c19be335cb11.png)

**Comment by mmiddaugh** [comment]
@arickalewis1 as discussed in Slack, please plan for designs to incorporate "operating status" and "operating notes". 

![image (27)](https://user-images.githubusercontent.com/55411834/78078139-d83dab00-7366-11ea-9748-23fa51431d39.png)

**Comment by arickalewis1** [comment]
Attaching screenshots of operating status implementation for facility cards and detail pages 
<img width="781" alt="Screen Shot 2020-04-02 at 2 26 24 PM" src="https://user-images.githubusercontent.com/54509359/78295152-444c1a80-74f1-11ea-8392-02cddecaf502.png">
<img width="241" alt="Screen Shot 2020-04-02 at 2 26 33 PM" src="https://user-images.githubusercontent.com/54509359/78295159-47dfa180-74f1-11ea-9702-492fdd1e61bd.png">
