### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by gmaciolek** [department-of-veterans-affairs/va.gov-team#71782]
### Name

Gretchen Maciolek

### Email

gretchen.maciolek@va.gov

### Role

Designer

### Team

Pension and Proactive Benefits

### Product Manager (PM) name

Buddhima Kulakurusuriya

**Comment by naomimarcussen** [comment]
Hi! Just sent an invite. Once you accept that and create an account let me know and I'll get you edit access and make sure you're in the project folder you need.

**Comment by naomimarcussen** [comment]
You're now an editor. :)
