### ISSUE TITLE
[BE] 10-10EZR V2: Background job freezes submission screen

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#71784]

**Comment by jadon1979** [comment]
The ezr_async flipper flag is turned off.  Enabling this should fix the issue.

**Comment by jadon1979** [comment]
Verified that this does indeed work now properly on staging.  I have left ezr_async turned on for staging.  When we are ready, and this is deployed to prod, then we need to turn ezr_async on for prod.  The next set of stories will involve removing the ezr_async feature flag from vets-website and vets-api.

@hdjustice

**Comment by hdjustice** [comment]
@alexseelig - FYI Chapley's comment on this ticket

> Verified that this does indeed work now properly on staging. I have left ezr_async turned on for staging. When we are ready, and this is deployed to prod, then we need to turn ezr_async on for prod. The next set of stories will involve removing the ezr_async feature flag from vets-website and vets-api.
