### ISSUE TITLE
[FE] COVID-19 My VA alert: Remove VISN 8 from My VA health chat alert

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#7179]
## Background

Epic #6974; Original build #6977

We just find out that VISN 8 no longer wants to participate in the health chat pilot, so we need to remove their facilities from the list of facilities that would trigger the health chat alert on the My VA dashboard. VISN 23 has confirmed they are still moving forward with the alert.

## Tasks

- [ ] Remove VISN 8 facilities from the list of facilities that will trigger the health chat alert on the My VA dashboard.

## Acceptance criteria

- [ ] The health chat alert only shows to patients in VISN 23.

**Comment by erikphansen** [comment]
closing this. I did the work but there isn't a real way to validate it on staging since our staging users are not patients in VISN8 so we can't prove that the banner no longer appears for them.
