### ISSUE TITLE
[FE] 10-10EZR: Update expenses questions flow and verbiage

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#71795]
As a Veteran, I would like a clear explanation of expenses for my dependents so that I know that information I need to enter.

- [x] See [designs/wireframes for new flow](https://www.figma.com/file/tggcJk382w9yQ0ElwKfh3N/10-10EZR?type=design&node-id=0-8373&mode=design&t=6SaqoM7ObzQmZgB0-0)
- [x] Use conditional logic where if anything more than $0 is entered they get education expenses
- [x] Education Expenses is now last step
- [x] Update verbiage for Dependent Expenses
- [ ] Test
- [ ] Release to Prod behind feature toggle (work with other devs)
- [ ] **Success: EZR verbiage and flow is updated**
**AS: We will have a story for all conditional logic post-MVP**

**Comment by mkerns1** [comment]
PR for verbiage updates: https://github.com/department-of-veterans-affairs/vets-website/pull/27193.

**Comment by hdjustice** [comment]
Validated that the conditional logic and updated content have been implemented per the design
<img width="572" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUIwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f8f5d67d07fe8342f904ad1ea4549e97e0abbc78/image.png" alt="image.png" />

**Comment by hdjustice** [comment]
Note that the spacing between the questions is being fixed now and will be implemented asap
