### ISSUE TITLE
 QA Feedback for Left Nav [Usability Testing Prep] 

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#7180]
## VSP QA feedback on Left Nav [Usability Testing Prep]

**Regression Test Suite Artifacts:**
Not available

**Manual Functional Test Suite Artifacts:**
https://dsvavsp.testrail.io/index.php?/suites/view/7&group_by=cases:section_id&group_order=asc&group_id=62

## Feedback
**Regression Tests:** 
1. Not available at this time.  Please create manual test cases or provide details on the automated E2E coverage that applies to this product.

**Manual Functional Tests:**
1. Typo in test case name "Navigattion"
1. Are there any user stories from which you are drawing the verifications for the Navigation test case?  If so, please link to the story in GitHub as a "Reference".
   <img width="885" alt="References" src="https://user-images.githubusercontent.com/52456633/77460653-c47acd80-6dd7-11ea-8ed7-bfb7096e0de3.png">

1. Are there any other functional changes being made as part of this release?  The only items being addressed are navigational elements?
1. Given that the focus of this change is on design, it may be prudent to make more specific verification statements about **how** the left nav elements are rendered.

## Definition of Done
- [x] Acknowledge each item of feedback with a decision
- [x] VSP QA will close ticket after reviewing feedback decisions

**Comment by mmiddaugh** [comment]
**Links to improved test plans:**
[Left Nav Test plan](https://dsvavsp.testrail.io/index.php?/plans/view/225) 
[Left Nav Mobile Test plan](https://dsvavsp.testrail.io/index.php?/plans/view/232) 

**Regression Tests:** 
1. Both test plans now contain a regression test case for expected page content to be loaded. 

**Manual Functional Tests:**
1. Typo has been addressed
2. Github issue has been linked as "Reference"
3. Steps to validate functional changes (such as left menu behavior: expanding in mobile or menu item as link to page) have been incorporated into the test cases. 
4. Test cases for each have been significantly improved with more specific expectations about rendering. 
- [Left Nav Test plan](https://dsvavsp.testrail.io/index.php?/plans/view/225) created with browser configurations
- [Left Nav Mobile Test plan](https://dsvavsp.testrail.io/index.php?/plans/view/232) created with mobile configurations

I'd love additional feedback on these as this was my first experience creating tests in TestRail and a "new-to-me" product.  @pjhill

**Comment by pjhill** [comment]
@mmiddaugh I love it!  Thanks for working on this.  Some feedback --

- Regarding references, the "References" field automatically assumes that you are going to be referring to va.gov-team repo issues, so all you need to enter there is the ticket number (7212) from that repository.  I've edited [this](https://dsvavsp.testrail.io/index.php?/tests/view/1630) test case to correctly reference just "7212", so you can see what it looks like.  I'll leave the others to you to fix if you want to.  I recommend linking this way since the way you have them linked right now is sending me to 404.  Also, if you just link with a number you will get a spiffy popup when you mouse over the reference as well.

- Creating two distinct test plans, one for desktop and one for mobile seems like the right call to me.  You have slightly different test steps for verifying desktop vs. mobile experiences.  You have also correctly created a test run for each environment configuration you will be testing.  Great!

- Screen shots built into the test steps are great!  The only downside is that if the design changes you will need to go back and update the screen shots for these test cases. Personally, I think it is worth it.

- It looks like for your [Desktop Navigation](https://dsvavsp.testrail.io/index.php?/tests/view/1630) test case you have multiple actions in a single test step.  I recommend taking only one action in each step.  It's ok to verify more than one thing for each step, but try not to take more than one action in each step.

Thanks again for working on these test cases.  I hope that you will find it adds to your overall project health.

**Comment by mmiddaugh** [comment]
Thanks @pjhill for the help on linking to Github. I have separated the steps with multiple actions into individual steps and also added a test case for the Focus state. 

Where is the best place to reference automated unit tests once those are defined?

**Comment by pjhill** [comment]
At the moment, unit test results are not integrated into TestRail.  I'm working on getting that integration added to VSP's backlog in hopes that it can be worked in the near term.  For now, unit test, automated test, and load test results must be interpreted independently from manual test results.

**Comment by pjhill** [comment]
Feedback acknowledged and discussion resolved
