### ISSUE TITLE
S43: [Mariah on Repeat 🎤🎄]

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#71808]
## Sprint Goals

- Complete letter feed process for the infinite loop bug
- Complete regression testing for NOD
- Kickoff baseline monitoring work for Supplemental Claims (TBD: if capacity allows)
- Kickoff prototype for "Downloadable Copy of an Appeal" accessibility testing

---

## Team Capacity
- Velocity average (past three sprints): 10
- Target velocity: 11

PTO:
- Annie 12/13 - 1/1
- Robin 12/18, 12/22 - 12/29
- Heather 12/21 - 1/1
- Sade: 12/20-1/2
- Eugene 12/25 - 1/2 (returns 1/9)
- Rocio 12/25 - 1/1
- Eileen 12/25 - 1/1
- Ruben 12/25 - 1/1
- Derek 12/25, 1/1

## Reference documentation

- [High-level Roadmap](https://docs.google.com/presentation/d/18rYnaYCjp2L2cm8HdYmXsg1_Pz7KI_X0vNRkmT5AqEk/edit#slide=id.g2804f61cf5f_0_0)
- [Tactical Roadmap (WIP)](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1702419283589/39d0d78778b8a35a2a02b48496d665d86ec3c5a2?sender=ud80be02ce240061eb0f35352)
- [Planning and Prioritization Board](https://github.com/orgs/department-of-veterans-affairs/projects/1026/views/1?filterQuery=)
- [Defect Board](https://github.com/orgs/department-of-veterans-affairs/projects/876/views/1?visibleFields=%5B%22Title%22%2C%22Assignees%22%2C46447480%2C46447511%2C46447563%2C%22Labels%22%5D)
- [Story Estimator](https://docs.google.com/spreadsheets/d/1ae9fpz_ThZycIWjmBBMSEuGRGqsvRSz3/edit#gid=1440877167)
- [Velocity Planner ](https://docs.google.com/spreadsheets/d/1i7pVgf2XQxuRkIbuhHC5dckx2RlZt87n/edit#gid=880321098)

**Comment by HeatherWidmont** [comment]
Just a reminder to everyone - this will be a 3 week sprint which ends on 1/2/24

**Comment by saderagsdale** [comment]
@data-doge will update story estimator
@saderagsdale will add risks and assumptions

**Comment by HeatherWidmont** [comment]
I identified the problem with the velocity planner & fixed it which bumped up our target velocity this sprint from 9 to 11. After discussing with Sade & Eugene, it was decided to move forward with the plan the team agreed on during sprint planning.

**Comment by saderagsdale** [comment]
@HeatherWidmont @data-doge @eileen-coforma @rubensun @Mottie @rocio-desantiago hey all - can you add your PTO to the team capacity section under "PTO"?
