### ISSUE TITLE
Investigate solution to govdelivery-tms gem that is blocking Faraday

### ISSUE THREAD

**Issue by ryan-mcneil** [department-of-veterans-affairs/va.gov-team#71802]
### Description
The [govdelivery-tms gem](https://rubygems.org/gems/govdelivery-tms/versions/3.0.0) is blocking the [Faraday update](https://github.com/department-of-veterans-affairs/va.gov-team/issues/71538). `govdelivery-tms` is dependent on the `faraday-middleware` gem, which was deprecated in Faraday 2+, so the gem must be updated accordingly before we can Proceed. This may be blocking the Rails upgrade as well because of active-support dependencies

We are currently in talks with Bill Chapman to determine which direction we'll go:
* Request non-VA team to update their gem (hasn't been touched in 3+ years)
* We submit our own pull request to their [repo](https://github.com/Granicus/govdelivery-tms-ruby)/we're made codeowners
* We work the repo and maintain it separately

### Tasks
- [ ] Once info is available from Bill, determine which of the above solutions makes the most sense to pursue.

### Acceptance Criteria
- [ ] Create a follow up ticket to complete the work determined above

Blocking:
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/71538

**Comment by ericboehs** [comment]
Done
