### ISSUE TITLE
Investigate pros/cons of moving our code to our own module

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#71814]
The team is curious about moving our code to our own module, it seems like this will set us up for faster/more efficient work in the future. 

This ticket is to dive into this concept of moving our code to our own module and outline the pros/cons.  From there, we can make a call on if we want to proceed with moving our code (early estimate is this will take 1-2 weeks to do).

**Comment by holdenhinkle** [comment]
I've had several discussions with Jon and Alex Prokop about this. It's evident that we need to proceed, especially considering the need to establish our own representative, organization, and related tables. This step is vital, not only to avoid entangling our code with another module but also to ensure a single source of truth for our representative and organization data. Currently, we rely on OGC data as the primary source, supplemented by physical and email address information from the Trexler File. Ideally, we should solely use the Trexler File. Additionally, this move will prevent reliance on code that may become obsolete in the future.
