### ISSUE TITLE
Support rep type for Veteran Service Officers 

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#71815]
We would like to include individual Veteran Service Officers in the search results for Find a Representative.  This ticket is to update the backend, so that it can support the rep type of "Veteran Service Officer".

We'll also need to implement new search query to return new type of results, including a new serializer which will return the JSON results

**Comment by oddball-lindsay** [comment]
@holdenhinkle you may want to wait until @cosu419 has completed https://github.com/department-of-veterans-affairs/va.gov-team/issues/71816

**Comment by oddball-lindsay** [comment]
There is a bug, but want to first define how we will display the org data

**Comment by oddball-lindsay** [comment]
For VSOfficer searches, return all organizations.  Alphabetizing could be helpful.

If the search string matches an org, continue to return all orgs.  We can consider highlighting the searched org in some way, as design recommends.  This could be a visual distinction, or present the searched org first.

**Comment by holdenhinkle** [comment]
Merged
