### ISSUE TITLE
VLM-413 - Reuse the va.gov header(Veterans Crisis Line) and footer on the VLM website

### ISSUE THREAD

**Issue by jcosta-gcio** [department-of-veterans-affairs/va.gov-team#7182]
The VLM team needs assistance in adding our domain name(s) to the vets-website whitelist to use the header(VA crisis) and footer from va.gov see the details bellow.
 
VLM Website: https://www.vlm.cem.va.gov/ 

Below is the json that we will need to add to https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/proxy-rewrite/proxy-rewrite-whitelist.json
 
{
               "hostname": "www.vlm.cem.va.gov",
               "pathnameBeginning": "/",
               "cookieOnly": false
},
{
               "hostname": "dev.vlm.cem.va.gov",
               "pathnameBeginning": "/",
               "cookieOnly": false
},
{
               "hostname": "sqa.vlm.cem.va.gov",
               "pathnameBeginning": "/",
               "cookieOnly": false
},
{
               "hostname": "demo.vlm.cem.va.gov",
               "pathnameBeginning": "/",
               "cookieOnly": false
},
{
               "hostname": "uat.vlm.cem.va.gov",
               "pathnameBeginning": "/",
               "cookieOnly": false
},
{
               "hostname": "preprod.vlm.cem.va.gov",
               "pathnameBeginning": "/",
               "cookieOnly": false
}

src/applications/proxy-rewrite/proxy-rewrite-whitelist.json

**Comment by jcosta-gcio** [comment]
This is a Cross team issue for VLM and the va.gov team, this issue is referenced in Jira stories VLM-413, VLM-702 and VLM-700 approved by VLM - James LaPaglia(va)

**Comment by rianfowler** [comment]
Looks like www.vlm.cem.va.gov has a very different header than what the header injection script supports. Some work would need to be done to expand support for this site. Please escalate this to @KevinMHoffmanUSDS if that's needed.  

cc @brandonrapp

**Comment by MickinSahni** [comment]
@jenniferlee-dsva adding to your radar

**Comment by jcosta-gcio** [comment]
The VLM endpoints need to be added to the whitelist so that we can leverage va.gov js scripts to include the VA crisis functionality and the va.gov footer as per our clients request.

At his point we are requesting the following resources at run time once the whitelist work have been completed and we actually have access to the resources we will verify if all this resources are indeed needed:

```<link rel="stylesheet" href="https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/styleConsolidated.css" />
<script type="text/javascript" src="https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/polyfills.entry.js"></script>
<script type="text/javascript" src="https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/vendor.entry.js"></script>
<script type="text/javascript" src="https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/proxy-rewrite.entry.js"></script>
<script type="text/javascript" src="https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/js/vendor/uswds.min.js"></script> 
```

**Comment by rianfowler** [comment]
frontend tasks for header: 

- add support for configuring signin behavior using the proxy-rewrite config to support 
  - displaying no signin
  - changing the url that the signin points to
- **time permitting** we should break the CSS overrides into a separate file. 
  - Currently, we bundle several CSS overrides that are teamsite specific into the header injection CSS. If we want these scripts to easier to drop into other sites, we should separate these and leave the CSS reconciliation to the team owners. (most of the problems on teamsites were overly broad selectors overriding the header css)
  - this will need to be coordinated with the teamsite admin. recommend breaking this into a couple of steps: 
    - create a new teamsite specific CSS override that doesn't alter the current `stylesConsolidated.css`
    - add the new CSS override to the teamsite templates and verify they're working
    - remove the teamsite specific CSS from `styleConslidated.css`

**Comment by stephorkandatx** [comment]
@jcosta-gcio or @rianfowler : is there a request for the PW team to do some of this work, or has that plan shifted?

**Comment by kelsonic** [comment]
@MickinSahni can we close this?
