### ISSUE TITLE
Contact Center Review for Veteran Facing Form - 20-10206

### ISSUE THREAD

**Issue by tbaker1026** [department-of-veterans-affairs/va.gov-team#71823]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
*Form 20-10206 - Request your personal records

### Launch Date
*Beginning of January
Please provide the launch or rollout date and details.*

### Version Number
*Version 1

### Product Guide
[Product Guide](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/20-10206%20FOIA%20PA%20Request/Form%2020-10206%20Product%20Guide%20(3).docx)

[Workflow](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/20-10206%20FOIA%20PA%20Request/PrivacyAct.png)

[LOA3 workflow](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/20-10206%20FOIA%20PA%20Request/LOA3verified.png)

### Product Video
*Please provide product video link*

### Product Video Transcript
*Please provide product video transcript link*

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
Hi @tbaker1026. I'm looking at the Overview section for this guide and I'm wondering if the form is still going to be for both FOIA and Privacy Act requests, as well as Presidential Memorial Certificates. In other words, are there changes being made to what can be requested with this form?

**Comment by starlow00** [comment]
Actually, @tbaker1026, now that I'm looking at it, the Presidential Memorial Certificate appears to be tied to a request with Form 40-0247. So I'm wondering if it should even be mentioned in this product guide for 20-10206.

**Comment by tbaker1026** [comment]
@starlow00 sorry about that copy and paste error - here is the correct guide (removed language around Presidential Memorial Certificat) - [https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/20-10206%20FOIA%20PA%20Request/Form%2020-10206%20Product%20Guide%20(3).docx](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/20-10206%20FOIA%20PA%20Request/Form%2020-10206%20Product%20Guide%20(3).docx) - updated guid above as well

**Comment by starlow00** [comment]
Draft looks good. Sent to VEO for their review.

**Comment by starlow00** [comment]
No changes from VEO. Guide attached.
[VA Form 20-10206 Product Guide.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEY3QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--207686cd06c3e71473441f5ca2bcc5db409b70e9/VA%20Form%2020-10206%20Product%20Guide.docx)
