### ISSUE TITLE
Identity Dashboard, BDPR Dashboard - Audit concepts and create a glossary

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#71839]
### Description of UX Tasks
In order to make sure that content is understandable across all the products within the Identity Dashboard, we want to audit the concepts and language in the currently built out portions of the BDPR Dashboard within the Identity Dashboard (i.e. not the DataDog Dashboard)

#### Possible Tasks
- Content audit ID dash for concepts and terms that could user further explanation
- Create glossary that will allow VFS teams to better understand these

#### Documentation
- 

#### Acceptance Criteria
- [ ] Reviewed by UX Team
- [ ] Reviewed by PMs
- [ ] Documentation has been updated
- [ ] Add finalized research to Github

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by asg5704** [comment]
@claytonzook Because Identity Dashboard is dead in the water. I believe this ticket should be closed.

**Comment by claytonzook** [comment]
Agreed, closing this ticket
