### ISSUE TITLE
CF: Styling and content do not match UX prototype

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#7183]
## What happened?
There is some content and ui spacing/layout that do not match the prototype for #6803 

## Specs:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)

## Steps to Reproduce
- URL: https://staging.va.gov/gi-bill-comparison-tool/

## Desired behavior
See attached screenshots and excel for reference to below items.
This work is done behind a flag so that it is only available in the staging environments and below.

## Acceptance Criteria
- [x] Item # 4 in Supporting Artifact # 1 is addressed.
- [x] Item # 5 in Supporting Artifact # 1 is addressed.
- [x] Item # 6 in Supporting Artifact # 1 is addressed.
- [x] Item # 7 in Supporting Artifact # 1 is addressed.
- [x] Item # 8 in Supporting Artifact # 1 is addressed.
- [x] Item # 9 in Supporting Artifact # 1 is addressed.

## Supporting Artifacts:
1. UX Feedback Document
[CF SRP reviewed on 03.23.20.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4377109/CF.SRP.reviewed.on.03.23.20.xlsx)

AC 4:
<img width="471" alt="ID 4" src="https://user-images.githubusercontent.com/48260534/77462641-ca25e280-6dda-11ea-8f13-af0a35fcfcd0.png">

AC5:
<img width="1253" alt="ID 5b @1201px display width" src="https://user-images.githubusercontent.com/48260534/77462642-cb570f80-6dda-11ea-8362-08d30b5a08c5.png">
<img width="1246" alt="ID 5a @1200px display width" src="https://user-images.githubusercontent.com/48260534/77462648-cc883c80-6dda-11ea-9f57-c4bbe8efda4f.png">

AC6:
<img width="417" alt="ID 6b - Bulleted lists in Sketch Pattern Library" src="https://user-images.githubusercontent.com/48260534/77462651-cd20d300-6dda-11ea-97b0-18dc44f0da97.png">
<img width="757" alt="ID 6a - Bulleted lists alert" src="https://user-images.githubusercontent.com/48260534/77462652-cdb96980-6dda-11ea-9493-24976a186386.png">

AC7:
<img width="746" alt="ID 7" src="https://user-images.githubusercontent.com/48260534/77462654-cdb96980-6dda-11ea-8cc0-e1a08a43ccca.png">

AC8:
<img width="775" alt="ID 8" src="https://user-images.githubusercontent.com/48260534/77462656-cdb96980-6dda-11ea-934f-b0aa73ceaadc.png">

AC9:
<img width="751" alt="ID 9a - Unordered List margin-top" src="https://user-images.githubusercontent.com/48260534/77462657-ce520000-6dda-11ea-90cd-a11ffc891a38.png">
<img width="293" alt="ID 9b - Suggested value for UL margin-top" src="https://user-images.githubusercontent.com/48260534/77462659-ce520000-6dda-11ea-9628-e5cdaef0a784.png">

**Comment by delli-gatti-michael** [comment]
# AC4: 
![Screen Shot 2020-03-26 at 10.50.24 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/f570f0b8-ff38-4c17-8ab0-1daa5fc92001)

# AC5: (Screenshot at 768 px wide)
![Screen Shot 2020-03-26 at 10.55.18 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/eaf2e429-85c0-46e2-9700-8a0f73dc2456)

# AC6:
![Screen Shot 2020-03-26 at 10.50.24 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/e8f5c77a-4751-4deb-8b77-91b18831678c)

# AC7:
![Screen Shot 2020-03-26 at 11.02.04 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/2810dc08-fb10-4646-8147-1ba4e4314b56)

# AC8: (2 px above and 2px below)
![Screen Shot 2020-03-26 at 11.05.12 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/1323a278-2f75-4e3d-851f-189ded613663)

# AC9: 
![Screen Shot 2020-03-26 at 11.12.27 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/2a706cd3-ff8d-4aee-a31b-6fe941b9b29e)

**Comment by delli-gatti-michael** [comment]
PR:
https://github.com/department-of-veterans-affairs/vets-website/pull/12006

**Comment by ccruzgra** [comment]
@delli-gatti-michael thanks for sharing the updates! These updates look great. Just have two observations:

AC4: I'm seeing this for the closing alerts in staging search results, which is different than the image you posted: 
![Screen Shot 2020-03-26 at 2.42.46 PM.png](https://images.zenhubusercontent.com/5b55212f6dabc3393a2dbe50/2761ac52-421c-4704-bab4-125233701a97)

AC7: I'm still seeing some of the institution names w/ extra padding. Some look good and others are like this:
![Screen Shot 2020-03-26 at 2.35.48 PM.png](https://images.zenhubusercontent.com/5b55212f6dabc3393a2dbe50/45e1a657-1ada-40e6-94eb-bb1918403c60)

**Comment by elder-joseph** [comment]
@ccruzgra I see why # 7 is happening, the changes that Dustin checked in need the `        className="vads-u-margin-top--0p5"` to be consistent with the changes I made in 7183.

**Comment by delli-gatti-michael** [comment]
Fixes now present in staging. Closing this issue
