### ISSUE TITLE
Discovery - Appointment Requests

### ISSUE THREAD

**Issue by saneshark** [department-of-veterans-affairs/va.gov-team#7184]
**This will include:**
- Appointment Messages

Create discovery documentation using this template -- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/engineering/discovery/FHIR/template.md

While you are working through this discovery doc, please add WIP to doc header

FHIR Resource list -- http://hl7.org/fhir/dstu2/resourcelist.html

**Comment by jbalboni** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/engineering/discovery/FHIR/appointment_request.md
