### ISSUE TITLE
Reduce check in attempts when appt has passed

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#71850]
## Description 

There are a lot of attempts to check in after the check in window. I.e., Veterans are selecting the check in link in their text after the check in window has passed.

How can we reduce this pain point of Veterans attempting to check in, and having a bad experience. E.g., their path is verifying their ID, and then getting to the general error page. "We couldn't check you in. We're sorry. Something went wrong on our end. Check in with a staff member." 

https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/_u.dateOption=last30days&explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.pagePath:www.va.gov~2Fhealth-care~2Fappointment-check-in~2Ferror%3Ferror=cant-retrieve-check-in-data/

<img width="500" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHBaQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--717622238975e5627418ea32e6811944e8b88343/Screenshot%202023-12-13%20at%2010.58.26%E2%80%AFAM.png" alt="Screenshot 2023-12-13 at 10.58.26 AM.png" />

**Comment by loripusey** [comment]
@benbrasso-agile6 I am closing this epic but will add it to the Ideas area of our priorities board (see my note in slack about cleaning up our backlog)
