### ISSUE TITLE
CF: Add filter to exclude institutions with cautionary warnings from the search results

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#7185]
As a Comparison Tool user, I need to be able to exclude institutions with caution flags so that I can only look at schools without warnings in the search results.

## Assumptions:
1. This work is done behind a flag so that it is only available in the staging environments and below.

## Acceptance Criteria
1. A filter is available on the search results screen that meets the following criteria:
     a. It is available on the traditional search results page.
     b. It is available on the VET TEC search results page.
     c. When selected, it removes institutions with caution flags from the search results page
     d. When de-selected, it displays institutions with caution flags on the search results page that meet all other search criteria.
     e. It has a Learn More Link to display additional content to the user.
2. When clicking on the Learn more link (1e), the following information is displayed:

> **Cautionary warnings**
> 
> When Caution Flags are displayed for an institution, they indicate VA or other federal agencies like the Department of Education or Department of Defense have applied increased regulatory or legal scrutiny to this program.  Before enrolling in a program, VA recommends potential students should consider these cautionary warnings.
> 
> To learn more about Caution Flags, [visit the About this Tool page](https://www.benefits.va.gov/gibill/comparison_tool/about_this_tool.asp#caution).

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/share/N5IAD8MHTC9#/screens)
2. Screenshots:
<img width="292" alt="cautionary_warnings_filter" src="https://user-images.githubusercontent.com/48260534/77464250-46212a00-6ddd-11ea-95e6-c1d11eeba71b.png">
<img width="606" alt="cautionary_warnings_learn_more_content" src="https://user-images.githubusercontent.com/48260534/77464254-47525700-6ddd-11ea-84a6-b969d0f8cff6.png">

**Comment by ksantiagomorgan6** [comment]
database migration pr: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/636

backend changes pr: https://github.com/department-of-veterans-affairs/gibct-data-service/pull/635

front end changes pr: https://github.com/department-of-veterans-affairs/vets-website/pull/12107

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-04-03 at 12.28.30 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/2cd1e922-9f06-4231-8759-8ee949535303)
##
![Screen Shot 2020-04-03 at 12.28.59 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/80c50d17-9073-48ba-af4b-6eb8b4695411)

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-04-03 at 1.10.04 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/dbb16622-24d4-4add-9bc8-146f1b28e1a2)
##
![Screen Shot 2020-04-03 at 1.10.29 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/6e5c1a02-b7c1-4d5e-8472-7d217d89d981)

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-04-03 at 1.12.04 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/8c618ef3-5bd0-442d-a92b-115234d83e30)
##
![Screen Shot 2020-04-03 at 1.12.28 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/6259072b-072c-4b9a-9c7c-699d9909c66f)

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-04-03 at 1.12.55 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/ebe29e1a-ca6a-41ba-920d-38739f41de0b)
##
![Screen Shot 2020-04-03 at 1.13.49 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/98a1ee15-9c09-48f5-8c25-399d67c28476)

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/263&group_by=cases:section_id&group_order=asc

**Comment by sonntag-adam** [comment]
In staging. Closing story.
