### ISSUE TITLE
[MVP] Step 6: Update copy on 3 pages

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#71855]
## Note
Part of the larger effort to update the existing 527EZ form to add missing fields/info and remove depreciated fields.

## Description
On Step 6, replace the existing copy found on the following 3 pages:
- Aid and Attendance and Housebound Benefits
- Document upload
- Fully developed claim program

Please note that existing headers, links, button copy, and more may have changed, based on the new copy provided in the Google document.

## Designs
- Documentation with copy changes found in [this Google document](https://docs.google.com/document/d/1wU62yEmM45_iEv8mzTz_W_Bor5g0HOUpagEfbur4VfQ/edit?usp=sharing).

## Acceptance Criteria

**Match copy:**
Ensure all copy, including headers and buttons are updated to match the copy provided in the Google document.

## Tasks
[Software Development Tasks](https://docs.google.com/document/d/1vtn5co_YzGl1cFRNrIBAdjf53dmfH4_EXBWK8C5mU9Y/edit?usp=sharing)

- [ ] Front-end work

## Review
- [ ] Someone else on team signed off on pages in staging

## Artifacts
- [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/527EZ-reactivation-initiative-brief.md)
- [Content source of truth/PDF form](https://www.vba.va.gov/pubs/forms/VBA-21P-527EZ-ARE.pdf)
- [Link to testing accounts](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/form-deactivation/527EZ-staging-test-accounts-accessible.md)
- [Link to staging](https://staging.va.gov/)

**Comment by zack** [comment]
@vbellissimo the current document upload page (page 2 in the google doc) has some conditional logic for extra text regarding children (school aged or disabled child of the veteran). Are we removing this?

**Comment by vbellissimo** [comment]
@zack thank you for flagging this. I did not know this and this may be helpful to keep. Can you show a screenshot?

@katherine-fung @jstrothman

**Comment by zack** [comment]
<img width="852" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzE2QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--40e3e97a7221e30feb3896d9f9a09d3dd86f3723/image.png" alt="image.png" />

**Comment by katherine-fung** [comment]
Hi @zack and @vbellissimo, thank you for flagging this! 

I think we should keep the conditional logic that tells people about some of the additional forms they need to submit. 

I've updated the Google doc to add one sentence to the copy, which will lead into the existing conditional logic. 

Please let me know if you have any questions. Thanks! 
<img width="780" alt="Screen Shot 2023-12-21 at 10 19 52 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/105367381/e1631d0b-60d5-4fb6-b5db-3c4527067b53">

**Comment by vbellissimo** [comment]
Checked this against the Word document noted in staging and seeing all the changes in staging now.
