### ISSUE TITLE
[Design] 10-10CG Figma Migration: Work to migrate Sketch designs to Figma

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#71863]
## Background
As we reach the end of the Sketch license, the VA.gov Platform and OCTO-DE leadership has decided to move from using Sketch to Figma as a design platform.

We need to migrate existing Sketch designs over to Figma before 2/16/2024
Any new designs being worked on, as of December, should be created in Figma.

## Tasks
- [x] Follow [provided directions](https://depo-platform-documentation.scrollhelp.site/research-design/how-to-move-your-work-from-sketch-to-figma) to migrate existing 10-10CG Sketch designs to Figma

## Acceptance Criteria
- All Sketch designs will be migrated to, and accessible in, Figma

**Comment by jessicastump** [comment]
After we chatted in design sync - agree to close this ticket and move on to #73916?

**Comment by aagosto90** [comment]
Yes! @jessicastump I'll close it now
