### ISSUE TITLE
[Design] 10-10EZ Figma Migration: Work to migrate Sketch designs to Figma

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#71861]
## Background
As we reach the end of the Sketch license, the VA.gov Platform and OCTO-DE leadership has decided to move from using Sketch to Figma as a design platform.

We need to migrate existing Sketch designs over to Figma before 2/16/2024  
Any new designs being worked on, as of December, should be created in Figma.

## Tasks
- [ ] Follow [provided directions](https://depo-platform-documentation.scrollhelp.site/research-design/how-to-move-your-work-from-sketch-to-figma) to migrate existing 10-10EZ Sketch designs to Figma

## Acceptance Criteria
- All Sketch designs will be migrated to, and accessible in, Figma

**Comment by jessicastump** [comment]
I've done the initial step of uploading the sketch file into Figma and marking with the icons

**Comment by IMHieuVo** [comment]
We completed the Main Flow, with a few things to note: 
- Waiting for Platform to release the simple wireframe components.
- A few components are not currently available in Figma, those items are noted next to the associated screens.
- There are also works that are not a part of the Main Flow but need to be reserved (Document icon Jessica mentioned above), so we'll have to create Sketch Screenshots for them (different ticket).
