### ISSUE TITLE
[UX] 10-10EZR: Migrate EZR Designs from Sketch To Figma

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#71860]
As a designer, I would like to migrate my designs from Sketch to Figma because Figma is better.

- [x] Move EZR designs to Figma
- [x] Update components in Figma as needed
- [x] Enjoy how much better it is
- [x] Get used to Figma
- [ ] **Success: All our EZR designs are in Figma now!**

**Comment by IMHieuVo** [comment]
We completed the Main Flow, with a few things to note: 
- Waiting for Platform to release the simple wireframe components.
- A few components are not currently available in Figma, those items are noted next to the associated screens.
- There are also works that are not a part of the Main Flow but need to be reserved, so we'll have to create Sketch Screenshots for them (different ticket).
