### ISSUE TITLE
CT: Fix spacing in Search Results Filters

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#7186]
As a developer I need to fix the spacing on the CT Search Results institutions filter so that it meets the DEPO styling standards.

## Assumptions:
1. This work is done behind a flag so that it is only available in the staging environments and below.

## Acceptance Criteria
1. The spacing between "Institution details" subhead and "Type of institution" label is reduced so that it matches the spacing between the "Keywords" subhead and "City, school, or employer" label.
2. The spacing for the first header in filter fields is lined up with the first search results card. This includes vettec search results filter. 

## Supporting Artifacts:
1. N/A

**Comment by hughes-dustin** [comment]
branch: bah-7186
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/12004

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-03-26 at 9.09.53 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/16222d79-89d8-4f87-9adb-115296737b7e)

**Comment by sonntag-adam** [comment]
Production build
![Screen Shot 2020-03-26 at 9.25.27 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/4cbe766c-427b-4362-bfc4-e4b87de77916)

**Comment by sonntag-adam** [comment]
@amyknox @ccruzgra @JLynnJ changes are in staging.  https://staging.va.gov/gi-bill-comparison-tool/search?category=school&name=test

**Comment by ccruzgra** [comment]
@sonntag-adam This checks out for ux!

**Comment by sonntag-adam** [comment]
Testing passes QA. Closing story.
https://dsvavsp.testrail.io/index.php?/runs/view/238&group_by=cases:section_id&group_order=asc
