### ISSUE TITLE
SOCKS access for Christian Burk

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-team#71870]
### Your Name

Christian Burk

### Your Email

christian.burk@civicactions.com

### Your Role and Team

Backend Engineer on VA Sitewide 

### Product Manager (PM) name and email

Jane Xiong

### Product Owner (PO) name and email

Michelle Middaugh

### Access Type Requesting

automation_external

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC4nZkSLaOdgxP4os8tm4cFUtIe0brubmzusAvCGONSq9AoTz5XMVvqYEsNu651CKxlLQ6sgJJOwPpHu2bukC9GvqsqNIU0AwakiNKbEidZrw9p69ktFIaVMEZkG5jjoZVw7lEEWspRfUr5+EgQdVnfVJbSnOMZtXBeM9UehDbVvTT9FY4oGcATIwUYFVmBQ0ASh6ws8PYZWxTIcf0aD55vM/QLdaX3OsUyn3/+NsLGtloTPt1/qrn49AMKu0qTpnSuckP7Q0yrKxN8s68FqX7rNklKQdhnqdWTzc2hoXvnWxYgfa86Z7/FAEyxABAEpg74HZqBTGE/SAsj0cu5Rd5CJ4eg1O3sw/IblYUCNkaa57f5vzBxel6dqILWHnN+XGoqdcEu6CiZ22vBr9bCWGL07Ahfzx/CrOrp6CO+MXexU2iBD0bHl6iC1sv6FZlES+IR2Epjx+LGQq3PgDROgJdL7gJs54+W62zLFxIlfqP/oJ48LTH4eMx48zhutX0H/qk= christian.burk@macbook-pro.lan

### E-QIP Transmittal Confirmation

![Screenshot 2023-12-13 at 11 25 40 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/766573/a13a902c-5150-44e5-9d62-e9a1d15808a0)

### User must exist in a roster before SOCKS access can be granted

- [x] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by ph-One** [comment]
@omahane Are you wishing to add this as an additional pubkey for SOCKS usage, or would you like us to replace your current pubkey with this one?

Current pubkey: https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/roles/dsva-config/files/authorized_keys/christian.burk%40civicactions.com

**Comment by flooose** [comment]
Ping @omahane. If you can give us an answer to [this comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/71870#issuecomment-1860616884), we can proceed with this.

**Comment by patrick-black-oddball** [comment]
@omahane - any answer to the above?

**Comment by omahane** [comment]
Thanks for looking into this. I do not want to replace my public key. I would like an additional one.

**Comment by patrick-black-oddball** [comment]
@omahane - we'll need you to submit a cert with a different email address (update this ticket with the email address and new cert. We can only have one cert per email address. Many people use their va.gov email address.

**Comment by hgbarreto** [comment]
@omahane - reaching out via slack

**Comment by hgbarreto** [comment]
User reports that this is no longer needed.
