### ISSUE TITLE
Add timestamp to VHA PDF

### ISSUE THREAD

**Issue by kjsuarez** [department-of-veterans-affairs/va.gov-team#71883]
VBS want box 37B of their FSR to contain a timestamp instead of a date. 
- Confirm with the Sharepoint team (andrea.hugo@va.gov, brian.fuller9@va.gov, richard.crist@va.gov) that this change will not cause issues
- Change the value of this box for the VHA  PDF specifically
- Notify Denise when it goes to production so she can notify Mike Dewey

**Comment by HeatherRienks** [comment]
@denisecoveyduc - is this an issue that we should take on in Sprint 117?

cc: @Tom-Davis

**Comment by denisecoveyduc** [comment]
@HeatherRienks Can be but doesn't need to be.
