### ISSUE TITLE
AWS access for Sam Raudabaugh

### ISSUE THREAD

**Issue by raudabaugh** [department-of-veterans-affairs/va.gov-team#71890]
### COR Name

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative Name

Other - please specify in 'Additional Notes'

### E-QIP Transmittal Date

- [ ] Check this box if you have an E-QIP transmittal date.

### Your Name

Sam Raudabaugh

### Your Email

samuel.raudabaugh@va.gov

### Team, Role, and Company of the target individual

Benefits Portfolio, Engineering Lead, VA

### Product Manager (PM) name and email

Zach Goldfine, zachary.goldfine@va.gov

### Product Owner (PO) name and email

Jennifer Bertsch, Jennifer.Bertsch@va.gov

### Desired AWS Access

Particularly I need access to read-only query the production CloudWatch/S3 historical logs for research and to assist in issue resolution.  Benefits teams I support work with the `vets-api` and `vets-website` repos. 

Access requested should be ongoing as issues that need resolved/debugged occur repeatedly. 

Prior benefits portfolio team members requested access through the following:
```
group_memberships = ["dsva-vagov-developers", "force-MFA"]

"adhoc-vetsgov-ssm-prod"
```

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

n/a

### Additional Notes

I do not have a COR, as I'm a federal employee.

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [ ] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [x] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by flooose** [comment]
@zachgoldfine44 or @jenniferbertsch in lieu of a PIV card verification or other type of identification, could you verify that this is a member of your team?

**Comment by jenniferbertsch** [comment]
Yes. Sam is a federal employee member of our team.  Thx.

**Comment by flooose** [comment]
Adding "Awaiting Approval" because of requested access to SSM in production.

@jenniferbertsch, @zachgoldfine44 you'll need to provide @BillChapmanUSDS justification for this. If lower level access is sufficient to start with, I can prepare a pull request.

**Comment by JonathanKamensDVA** [comment]
Approved.

**Comment by patrick-black-oddball** [comment]
Sam is on the VFS Team roster

**Comment by flooose** [comment]
@patrick-black-oddball I believe you can go ahead and process this access request. I had previously added the label "Awaiting Approval" because the person was requesting prod access. @JonathanKamensDVA has since approved this issue and with the user being in the VFS Team roster, you should be good to go.
