### ISSUE TITLE
Getting a 404 when trying to follow links to the analytics customer support guide.

### ISSUE THREAD

**Issue by Becapa** [department-of-veterans-affairs/va.gov-team#71916]
### Description
All of the links that are supposed to point to the customer support guide on the "Getting started with Platform Analytics & Insights" page are giving a 404 error.

### Relevant URLs
Getting started page: https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/getting-started-with-platform-analytics-insights
Customer Support Guide being linked to: https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guidelines.1586823275.html

### Which type of team are you on? (Platform team, VFS team, or Leadership)
VFS team

**Comment by johnny-jesensky-adhoc** [comment]
Hi @Becapa, thanks for flagging this. This page underwent some updates today, though we just pushed a change that looks like it corrected the link. I'm able to see that the [Customer Support Guide](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/analytics-customer-support-guide) link is working now from my end.

Are you able to try again and see if you are still seeing the 404?

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/147662408/278a5592-af76-4906-af07-f0e5610f058f)

**Comment by Becapa** [comment]
@johnny-jesensky-adhoc Yep! It looks good. Thanks!

**Comment by johnny-jesensky-adhoc** [comment]
Great, I'll close this then. Thanks!
