### ISSUE TITLE
PA Request: CAIA content updates to intro page

### ISSUE THREAD

**Issue by rachelshearerux** [department-of-veterans-affairs/va.gov-team#71919]
After this [experimental ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2284) was raised to the design system, we were asked to adjust previously-reviewed content to align better with how other teams have spoken about identity-verification in other areas of VA.gov. 

We received some edits from the identity team which have been incorporated, but now we need to make a (final) update based on feedback from SWCAIA. They took a look at the content provided by the identity team and have 4 requests for changes on the intro page:

### 1. Update the first paragraph below the H2 "What to know before filling out this form: 

| Before | After |
| :--- | :--- |
| If you want to request your records through this online form, you’ll need to sign in to your account. To manage certain tasks and information on VA.gov, like requesting personal records or changing your direct deposit information, you’ll need to log in with an account where you’ve provided some personal information to verify your identity. We recommend using ID.me or Login.gov accounts for identity verification. | If you want to request your records through this online form, you’ll need to sign in to your account. You’ll need to verify your identity, so we encourage you to use a **Login.gov** or **ID.me** account. | 

### 2. Add a new paragraph below the H2 "Start your request"

| Before | After |
| :--- | :--- |
| _No content before the sign-in component_ | Note: You’ll need to sign in with a verified **Login.gov** or **ID.me** account or a Premium **DS Logon** or **My HealtheVet** account. If you don’t have any of those accounts, you can create a free **Login.gov** or **ID.me** account now. | 

### 3. Remove the third bullet from the sign-in component

| Before | After |
| :--- | :--- |
| You’ll need to log in with an account where you’ve provided some personal information to verify your identity. We recommend using ID.me or Login.gov accounts for identity verification. | Standard sign-in component for an authenticated-only experience | 

### 4. Update the second H2 to more accurately use the plural "Type**_s_**"

| Before | After |
| :--- | :--- |
| What type of information can I request? | What types of information can I request? | 

<img width="319" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3BiQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ae92d52735c6c2a2c461892c2c597a92510d0644/12-13%20CAIA%20updates.png" alt="12-13 CAIA updates.png" />

---
Definition of done:
- [x] Update the paragraph below the first H2
- [x] Update the 2nd H2 to reflect plural "Types"
- [x] Add the new paragraph below the third H2 "Start your request"
- [x] Remove the third bullet from the sign-in component
- [x] Confirm in staging

Docs
- [Sketch](https://www.sketch.com/s/314e6dbf-5b4a-422d-beb1-0ad599fc3af1/a/3oJLZVG#Version)
- [Source of truth](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/20-10206%20FOIA%20PA%20Request/source-of-truth.md)

**Comment by tlei123** [comment]
@rachelshearerux @jeana-adhoc , FYI re. removal of that 3rd custom bullet-point...

We'll still have the option going forward to customize the sign-in component's bullet-list.  I'm keeping the new `SignInHelpList` _property_ that I added to SaveInProgressIntro component, and just turning that option off in our form-config to remove the bullet-content.

Tag me here if you have any further questions/concerns

**Comment by tlei123** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-website/pull/27142) opened.

**Comment by tlei123** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-website/pull/27142) merged, but missed today's scheduled deploy.  Changes should be in Staging by tmrw (Fri) ~4:45 PM ET.
