### ISSUE TITLE
Request manual QA services for SSO-Login

### ISSUE THREAD

**Issue by marriej** [department-of-veterans-affairs/va.gov-team#7195]
Requesting manual QA services from the VSP Product Support team.

Team Name: SSO-Login
Test Cases (include product URL and credentials): https://dsvavsp.testrail.io/index.php?/suites/view/30&group_by=cases:section_id&group_order=asc

Requesting support week of April 2nd or prior if available.

**Comment by marriej** [comment]
@pjhill we had to move our Staging review to Friday to meet the Cerner deadline, any possibility you might be free to assist with testing tomorrow? Thanks.

**Comment by pjhill** [comment]
I'm happy to help however I am able to.  Would you like to get together for thirty minutes to an hour tomorrow to discuss how I can best assist you with getting what you need done for staging review?

**Comment by marriej** [comment]
Thanks i'm free tomorrow morning until noon EST. would you have some time then?

**Comment by pjhill** [comment]
I'm still waiting on CAG access request to be resolved.  I'm going to give ESD a call this morning with a request for an update.

**Comment by marriej** [comment]
Hi @pjhill any updates on your access? Testing will be picking up this week and next.

Thanks.

Alexis

**Comment by pjhill** [comment]
When last I got through to help desk they had no update on me for my CAG request ticket.  I will try to get on the phone with them again today, but for the moment I am still without CAG.
