### ISSUE TITLE
Find 'untouched' submission IDs 

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#71954]
This ticket outlines first step in audit process which will help us identify if any failed submissions have yet to be sent to the VA for review

- [ ] - Step 1: Decide which sources of information are used for audit - which submission ids did we try to remediate through the batch or back up process:
   - [ ] - Lists of what was sent in each batch (excel)
   - [ ] - S3 which we use to send files / contention data
   - [ ] - Has Backup path id 
   - [ ] - Compare and consolidate lists
- [ ] - Step 2: 
    - [ ] - Identify any submission id that did not succeed happy path first time and in not in the unified list above (e.g. total miss)

**Comment by sortizsh** [comment]
blocking - needs insight and clarify from Emily

**Comment by SamStuckey** [comment]
[This is now captured in the more comprehensive and up to date ticket here](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/80624). I recommend closing pending @emilytheis or @tblackwe saying it's ok

**Comment by sortizsh** [comment]
We've favoring this other ticket, closing this one [80624](https://github.com/department-of-veterans-affairs/va.gov-team/issues/80624)
