### ISSUE TITLE
Design Feedback: Pre-Usability Review [Left Nav]

### ISSUE THREAD

**Issue by emilywaggoner** [department-of-veterans-affairs/va.gov-team#7196]
## User Story

VSP Design feedback on Left Nav redesign

Prototype we're reviewing: 
- [Desktop](https://github.com/department-of-veterans-affairs/va.gov-team/issues/1874#issuecomment-595797269)
- [Mobile](https://github.com/department-of-veterans-affairs/va.gov-team/issues/1874#issuecomment-601907235)

**Do**
- Incorporate yellow halo focus state to "active/on-click state"
- In the "You are there/section open" state, change the text color from blue to neutral (black), and potentially the vertical bar highlight color to neutral (black) as well, reserving blue only to denote interaction. While it's true that across VA.gov, blue is used for more than just interactivity, within the context of the left nav, it's a small but effective distinction we should make. This will help avoid reintroducing a previous pain point of the left nav, which was that users were confused by the "active state" that appeared interactive, and frequently mistakenly clicked on it, not realizing they were already on that page.

**Try**
- Incorporate some kind of slight motion into the hover state 

---
## Definition of done
- [x] Incorporate the **Do** feedback, and let us know on this ticket when there are updated mockups to check out
- [x] Leave any comments for feedback you decide _not_ to take

Emily or Crystabel will close the ticket once those things are all set. Thanks Ryan!

**Comment by rtwell** [comment]
![image](https://user-images.githubusercontent.com/12564977/77478232-09146200-6df4-11ea-943d-c64e8a33c395.png)

![image](https://user-images.githubusercontent.com/12564977/77478298-20534f80-6df4-11ea-86b6-ee8e4525aaae.png)

![image](https://user-images.githubusercontent.com/12564977/77478347-39f49700-6df4-11ea-9f9a-deb4648cd01f.png)

**Comment by mmiddaugh** [comment]
Feedback for the following have been incorporated into Ryan's designs as above and in [#7212](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7212):

- Focus state to be consistent with styling across VA.gov for both hover and "on" states
- When a left nav menu item is selected, the text color will change from default blue to $color-primary-darker with a border box and vertical left bar highlight in $color-primary-darker

At this time, no motion will be incorporated into the hover state
