### ISSUE TITLE
Communication Campaign Design System

### ISSUE THREAD

**Issue by SophiaPhilipMO** [department-of-veterans-affairs/va.gov-team#71971]
Context
Create a 5 page guide on elements of communication campaign that have been decided, assets to use, timeline and associated offices that have approved.

User Story

AC
December 31st, 2024
As of, now by
How we talk about Login.gov and ID.me
Who has signed off

**Comment by lmorris3** [comment]
Closing, will not create this (work is being done in parallel by Sitewide/CAIA - no need to duplicate)
