### ISSUE TITLE
2024 IA Audit - Sign in widgets

### ISSUE THREAD

**Issue by kristinoletmuskat** [department-of-veterans-affairs/va.gov-team#71976]
Goal: we made this awesome guidance for sign-in widgets, but we want to go back through all of the uses of sign in widgets and determine where we need to make changes

As part of this work, we should create standards for this.

Mikki thinks we have the audit done, we just need to figure out what comes next.

**Comment by kristinoletmuskat** [comment]
Note, we identified that a bunch of flows are using incorrect patterns - ex: showing buttons when we should be showing action links, using the wrong color button/action link. Ex: order hearing aids, apply for veteran ID card, change your address

**Comment by jennymayoco** [comment]
We're done with the audit work and are tracking the standards in [this Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1697213811994/ac7d62d5057d551a31a09571ba9efbceb8026e67?wid=0-1709666935421&sender=u79ee90295fdb006d7f463212)

We can create a new ticket to track any incorrect button/action links
