### ISSUE TITLE
[Development] HLR: Add JSON validation to decision review create endpoint

### ISSUE THREAD

**Issue by SMLuthi** [department-of-veterans-affairs/va.gov-team#7197]
## Purpose
Update 6/29: Discussed during meeting with dev team, we don't want to use this endpoint to cache or even pull the schema since it is overly prescriptive.  Robin has been using a modified schema based on their schema to simplify our end. We need to explore whether this is the right way to go or whether we want to talk to LH about their schema so we end up with the same one on both ends.

The lighthouse team has updated their submission endpoint for the decision review process. We will want to validate the json payload we are submitting to them after the FE has submitted the form data to us. To facilitate this, the lighthouse team will expose a GET schema endpoint from their api which we can use for json validation purposes.

https://dev-developer.va.gov/explore/appeals/docs/decision_reviews?version=current
https://github.com/department-of-veterans-affairs/vets-json-schema/blob/master/dist/20-0996-schema.json

## What we need to do
Pull their latest schema and compare against what we have in vets-json-schema.  Make a smart decision about whether we keep "our" version.

## Def of Done
- [ ] Create new endpoint for GET HLR schema for decision review service
- [ ] Add redis caching for the schema
- [ ] Validate FE json form payload to schema and raise appropriate validation error(s)

**Comment by SMLuthi** [comment]
The lighthouse team responsible for HLR is making more changes to their APIs endpoint(s). Therefore, we should hold off making updates to our integration until this is finalized.

**Comment by luke-gcio** [comment]
Now that @edmangimelli is on the  team he wants to chat to Robin about the approach.

**Comment by edmangimelli** [comment]
Double-checked some things in vets-api (double-checked with Cameron Testerman too), and spoke with Robin Garrison again this morning:

vets-api is /not/ using the same HLR schema as vets-website.
Robin says vets-website doesn't actually use the schema in vets-json-schema

**Comment by edmangimelli** [comment]
PR in vets-json-schema needing review

**Comment by edmangimelli** [comment]
needing a review from a code owner

**Comment by edmangimelli** [comment]
PR approved

**Comment by edmangimelli** [comment]
PR merged

**Comment by edmangimelli** [comment]
another PR
https://github.com/department-of-veterans-affairs/vets-json-schema/pull/490
