### ISSUE TITLE
SPIKE | Discovery on JSON to PDF Mapping

### ISSUE THREAD

**Issue by tblackwe** [department-of-veterans-affairs/va.gov-team#71987]
For Burials refresh (and Dependents in future), we need to understand how to manipulate the PDF creation from the JSON saved by the Front End

Similar work is being done by the Pensions team, and we can review their PR here:
https://github.com/department-of-veterans-affairs/vets-api/pull/14702

Understanding how to accomplish this will allow us to size Burial tickets:
#70721
#70722
#70723
#70724
#70725
#70727
#70728
#70729

AC
- [ ] Simple write up outlining the places within vets-api that will need to be updated/written to successfully create a new version of the PDF.
- [ ] Suggested estimates for Burial Tickets

**Comment by sortizsh** [comment]
You can talk to Dan Lim or Scott Gorman on the Pension team if you have any questions, as they have already implemented this. Their info is in the PR at the top

**Comment by sortizsh** [comment]
Evan will send radio button info to Tyler, Tyler please assign story points to the above tickets @tfink419
