### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by samcoforma** [department-of-veterans-affairs/va.gov-team#71994]
### Name

Samuel Cormier

### Email

sam.cormier@coforma.io

### Role

Full Stack Engineer

### Team

Benefits Management Tools

### Product Manager (PM) name

Jacob Worrell

**Comment by naomimarcussen** [comment]
Invite has been sent to sam.cormier@coforma.io. To gain access to the Benefits Management Tools project, reach out to Julie Strothman.
