### ISSUE TITLE
Adding Austin Smith to DSVA Slack

### ISSUE THREAD

**Issue by HeatherRienks** [department-of-veterans-affairs/va.gov-team#71996]
Please add Austin Smith, new GovCIO Back End Engineer on Debt Resolution team to DSVA Slack as a Full Member.
austin.smith@govcio.com

He should be added to #vfs-all-teams, #vfs-change-announcements and any other pertinent Engineering and VFS general channels for new team members.

Thank you!

cc: @denisecoveyduc

**Comment by EWashb** [comment]
User has been added.
