### ISSUE TITLE
Improve External service Integration page

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#71990]
### Description

I think that the page at https://depo-platform-documentation.scrollhelp.site/developer-docs/adding-a-new-external-service-integration could stand to be fleshed out a bit from the perspective of a new developer in the VA.gov ecosystem. In particular:

- add more information about why outbound requests should (must?) be routed via the fwdproxy
- add a basic explanation of the network architecture, linking out to more detailed resources
- improve the configuration link in the `AddinganewExternalServiceIntegration-ForwardProxy` section to be to where the configuration is added

I think this will likely need collaboration/help from the backend and devops CoPs - I'd be happy to review changes if that's helpful, but I'm not the best person to ask for help developing the updated content. Thanks for all your work on the site!

### Relevant URLs

- https://depo-platform-documentation.scrollhelp.site/developer-docs/adding-a-new-external-service-integration
- https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/engineering/TechnicalArchitectureOverview.md

### Which type of team are you on? (Platform team, VFS team, or Leadership)

OCTO engineer

**Comment by johnny-jesensky-adhoc** [comment]
Hi @acrollet, thank you for this feedback. We'll work to get this page updated, and will follow-up with you down the road to review the changes.

We'll provide further updates in this ticket!

**Comment by jknipes** [comment]
Work completed, closing this ticket as _Done_
