### ISSUE TITLE
Service history - Benefit applications - design.va.gov documentation

### ISSUE THREAD

**Issue by jaredcunha-usds** [department-of-veterans-affairs/va.gov-team#72]
Review of information type of pattern versus information collection. Veterans need to very if period of service is missing or incorrect.

Here are some points. These bullet points are not in any particular order.
- Data is typically pre-filled for login
- Show stack of flats (eg. Branch, Date)
- May have other info (eg. character of discharge) but we hide that in the “review” view.

You may submit your write-up as a comment on this issue. Happy to help if you have any questions.

**Comment by caw310** [comment]
This is over 3 yrs old. There is a service history pattern on design.va.gov.
