### ISSUE TITLE
Vets-api terminal access for  Aaron Ponce

### ISSUE THREAD

**Issue by HeatherRienks** [department-of-veterans-affairs/va.gov-team#72029]
### Your Name

Aaron Ponce

### Your GitHub handle (terminal access is managed through GitHub)

@amponce

### Your dsvagovcloud AWS user name (if applicable)

Aaron.Ponce

### Team, Role, and Company of the target individual

Debt Resolution, Front End Engineer, Agile Six

### Product Manager (PM) name and email

Tom Davis, thomas.davis@govcio.com

### Product Owner (PO) name and email

Denise Coveyduc, denise.coveyduc@va.gov

### COR Name (leave "None" if you listed an AWS user name above)

Jennifer O'Day

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

Agile Six - Anthony M. Arashiro

### Please confirm if you are on the VFS Team Roster or Platform Team Roster

- [X] [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Please confirm E-QIP Transmittal/Adjudication. This could be a screenshot of your Transmittal/Adjudication email, a link to another request where you've submitted this proof (i.e. AWS/SOCKS), etc.

- [X] I have attached proof that I have either transmitted my E-QIP survey or previously received a favorable decision (by including in "Additional Notes" section below)

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [x] production (if requesting, justify prod access in 'Additional Notes' section)

### Additional Notes

Requesting this access for Aaron Ponce to assist with supporting requests from VHA when investigating/troubleshooting issues with Veterans submitting FSR form 5655.

RE: eQIP approval, see ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/59700#issuecomment-1601186183
If additional information is needed,such as a screenshot, happy to provide.

### Additional resources for Support Engineer

- [ ] For users on a VFS team but not in the VFS Team Roster, they must start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] Instructions for handling requests [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access) - Support Only

**Comment by HeatherRienks** [comment]
![AaronPone eQIP proof 12 15 23- ticket 72029](https://github.com/department-of-veterans-affairs/va.gov-team/assets/85908655/4a806685-f370-4838-b548-ac44c43019d6)

**Comment by HeatherRienks** [comment]
Please advise if any additional is needed.

**Comment by bdech** [comment]
verified in VFS Roster

**Comment by bdech** [comment]
@HeatherRienks I followed the link you provided to E-QIP transmittal. Ryan made a list of users who WITH E-QIP confirmation, and users WITHOUT E-QIP confirmation. 

Can you please provide a screenshot of Aaron's E-QIP transmittal or some form of favorable adjudication? I see the screenshot you provided has favorable decisions, but it doesn't provide a name associated to those decisions. Thanks!

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/135037265/ce46089a-9aef-4996-89c8-331ae278ef76)

**Comment by HeatherRienks** [comment]
@bdech - please see attached and advise if this will suffice. Thanks!
![72029- detailed proof for Aaron Ponce](https://github.com/department-of-veterans-affairs/va.gov-team/assets/85908655/a547db4d-d7d6-4064-b134-9c4b387e93bb)

**Comment by bdech** [comment]
Thank you @HeatherRienks , that's perfect.

**Comment by bdech** [comment]
@amponce You’ve been granted access to the `dev`, `staging`, and `sandbox` environments. Access to `prod` is pending approval by OCTODE, and we'll update you as soon as it's available.

Here's some additional documentation for [Vets API on EKS](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-TerminalAccess) that may help.

**Comment by JonathanKamensDVA** [comment]
Approved.

**Comment by bdech** [comment]
@amponce You've been granted access to `Production`, 
with access to Production limited to 6 months, expiring 06/18/24.

Please set a reminder for yourself to return to this Issue and 
request an extension within 1 week of the expiration date. You'll 
receive 1 reminder with a 72 hour window to respond. Failure to 
respond will result in your access being revoked and will require 
you to fill out a new request.

**Comment by bdech** [comment]
support slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1703005386383749)

**Comment by bdech** [comment]
@amponce Your Vets-API Terminal Production Access has expired.

Would you like to request an extension? You have 72 hours to respond, or your
access will be revoked and you will need to fill out a new request.

**Comment by HeatherRienks** [comment]
@bdech - please extend access for @amponce :)

What else do we need to do for another 6 month extension?

Thank you!

**Comment by bdech** [comment]
That's all I needed thank you.

**Comment by bdech** [comment]
@LindseySaari @ericboehs can one of you please give us a :thumbsup: to extend their access?

**Comment by bdech** [comment]
@amponce Your Vets-API Terminal Production access has been extended for 6 months, expiring 12/18/2024. Please set a reminder for yourself to return to this Issue and re-request access within 1 week of the expiration date. You'll receive 1 reminder with a 72 hour window to respond. Failure to do so will result in lost access and will require you to fill out a new request.

**Comment by amponce** [comment]
Will do, thank you!

**Comment by bdech** [comment]
Support slack reminder [here](https://dsva.slack.com/archives/C06CY71PCAX/p1718735735643169)

**Comment by GWright321** [comment]
@amponce Your Vets-API Terminal Production Access has expired.

Would you like to request an extension? You have 72 hours to respond, or your
access will be revoked and you will need to fill out a new request.

**Comment by HeatherRienks** [comment]
FYI @dhill802

**Comment by amponce** [comment]
Hi @GWright321 thanks for letting me know. I would like to extend my access please 🙏

**Comment by GWright321** [comment]
@LindseySaari @ericboehs can one of you please give us a 👍 to extend their access?

**Comment by GWright321** [comment]
@amponce  your Production access has been extended for 6 months, expiring 06/30/25.

Please set a reminder for yourself to return to this Issue and request an extension within 1 week of the expiration date. You'll
receive 1 reminder with a 48 hour window to respond. Failure to respond will result in your access being revoked and will require you to fill out a new request.

**Comment by GWright321** [comment]
Support Slack reminder [here](https://dsva.slack.com/archives/C06CY71PCAX/p1735570338281129)

**Comment by AnthonyWFlowers** [comment]
@amponce  Your Vets API Terminal Production access has expired.

Would you like to request an extension? You have 72 hours to respond, or your access will be revoked and you will need to fill out a new request.

**Comment by HeatherRienks** [comment]
@AnthonyWFlowers - please extend access for @amponce . Thank you!

**Comment by AnthonyWFlowers** [comment]
@LindseySaari @ericboehs can one of you please give us a :thumbsup: to extend their access?

**Comment by AnthonyWFlowers** [comment]
@amponce your Production access has been extended for 6 months, expiring 1/1/26.

Please set a reminder for yourself to return to this Issue, reopen it, and request an extension within 1 week of the expiration date. You'll receive 1 reminder with a 48 hour window to respond. Failure to respond will result in your access being revoked and will require you to fill out a new request.
