### ISSUE TITLE
Legacy redirects for disability rates pages

### ISSUE THREAD

**Issue by AnneHurley** [department-of-veterans-affairs/va.gov-team#7202]
### Description
*These disability rates tables pages were initially redirected on March 10th in ticket [#6087](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6087), and were reverted due to outdated information in tickets #6833, and #6902 . The content has since been updated with the correct 2020 information and redirects need to be re-implemented.*

**_Update 04/30/20_**: The scope of work has expanded and resulted in this ticket being converted into an epic. ALL legacy historical rates pages will be redirected to the new Drupal current rates page. Additionally, legacy historical rates pages need to be PDF'd and linked appropriately in the Historical rates section of each disability rates page. To track this effort, a redirect ticket has been created for each disability rates page:

- Veterans disability compensation rates
- VA special monthly compensation rates
- VA special benefit allowances rates
- birth defect compensation rates 

The redirect for this legacy URL is being tracked in a separate ticket.
Current URL | Redirect Destination (new URL)
---  |  ---
*https://www.benefits.va.gov/compensation/rates-index.asp* |  https://www.va.gov/disability/compensation-rates/

**Stakeholders:** VBA - Sandy Tadeo, Adrianne

Related ticket: #7074

**Comment by AnneHurley** [comment]
@mnorthuis @lunascoop  Wasn't sure if I needed to create a whole new redirect ticket for these pages, which we did recently, then undid the redirects. Let me know if you see anything missing.

Note that I still need to tweak these pages' content to add latest historic rate chart link at the bottom, but otherwise pages are either live already or are ready to be, then redirects.

**Comment by AnneHurley** [comment]
https://www.benefits.va.gov/COMPENSATION/special_Benefit_Allowances_2019.asp 

Needs to redirect to:

https://www.benefits.va.gov/COMPENSATION/special_Benefit_Allowances_2019.asp

**Comment by mnorthuis** [comment]
@AnneHurley Can you clarify what redirects this ticket covers?

#7120 Covers https://www.benefits.va.gov/COMPENSATION/special_Benefit_Allowances_2019.asp
This is mentioned in the top description and your comment above which has it redirecting to itself.  

Can you update the original description with the URLs that need to be redirected please?

**Comment by AnneHurley** [comment]
@mnorthuis  and @lunascoop  Since these URLs are a group that actually *were* redirected previously, I think it'd be better for Selina to list out the URLs or connect to the right other ticket. This is new territory, redirected, un-redirected tickets - don't want to confuse things if possible. Selina, can you make that list here if we need them?

**Comment by lunascoop** [comment]
@mnorthuis @AnneHurley I did update the initial comment to reflect that the redirects of these URLs needs to be re-implemented. The existing URL list looks fine, only that https://www.benefits.va.gov/COMPENSATION/special_Benefit_Allowances_2019.asp is also covered in ticket #7120. I will close out that ticket and use this ticket to capture all disability rates page redirects.

**Comment by MickinSahni** [comment]
2020-03-27 PW Standup
- likely slot for Sprint 19

**Comment by AnneHurley** [comment]
@lunascoop @mnorthuis @jenniferlee-dsva @MickinSahni @beeyayjay 

Per my email today: 
The pages below are all updated and live. The sole piece missing from each is the previous year’s historic rates table link at the bottom. Other previous years rates *are* available. I had thought we were not going to hold up the redirect just for one historic table/URLs per page, once thisyear's rates have all been updated.
 
Beth, it sounds like you could do the cloning of the 2019 rates somewhat quickly? And if so we can add those links to the bottom of each page . If that is what is holding up the redirects I would love to get that done quickly and off our plates 😊
 
A.
 
1.	Main disability rate tables page: https://www.va.gov/disability/compensation-rates/veteran-rates/
2.	Special monthly compensation rates tables: https://www.va.gov/disability/compensation-rates/special-monthly-compensation-rates/
3.	Special benefit allowance rates: https://www.va.gov/disability/compensation-rates/special-benefit-allowance-rates/
4.	Birth defects benefit rates: https://www.va.gov/disability/compensation-rates/birth-defect-rates/
 
Meanwhile – This page on the legacy/TeamSite: https://www.va.gov/disability/compensation-rates/veteran-rates/
 
You’ll see that the links on that ^ page are in fact linked to the VA.gov/Drupal pages above. I don’t know if we had a plan for this specific page to be redirected or not, but note that if people navigate to this page from the Benefits.va.gov home page, they will then be sent to our new pages.

**Comment by AnneHurley** [comment]
@lunascoop  - This is one of the tickets related to these four pages/redirects. We also need to look at #7120 per @mikki comment above. And if there are any others, we should combine them. Can you let me know when you have time to chat about how to streamline/consolidate these? thx

**Comment by lunascoop** [comment]
@AnneHurley this is the only ticket remaining for the disability rates pages redirects.

**Comment by AnneHurley** [comment]
@RLHecht  I'm going to work on cloning the historic rates for the table/s available for each. At most of our VA.gov pages it will be just one previous year, as we didn't migrate the pages till last year. So the older pages will need to remain the older links, perhaps, until after a couple of years all previous three years of pages will be in Drupal. Will slack you.

**Comment by AnneHurley** [comment]
@RLHecht Final cloned disability rates page ready for your review:

Current birth defects compensation page: 
https://prod.cms.va.gov/node/993/edit

New cloned Historical 2019 rates page: 
https://prod.cms.va.gov/node/5062/edit

Note - on this page we had only 2 previous years' rates. The "effective 2018/historical 2019" rates were linking to a TeamSite page, but I swapped in the cloned URL. And then I added the 3rd previous year, so we have consistent 3 years on each page.

**Comment by lunascoop** [comment]
Hi @mnorthuis we are ready to move forward with scheduling the redirect as the historic rates for the pages have been cloned. Let me know if it is ok to proceed. I'm not sure if these URLs still need to go through the vetting process.

FYSA: @stephorkandatx @AnneHurley @ncksllvn @kelsonic

**Comment by jenniferlee-dsva** [comment]
@AnneHurley 
RE: 
> So the older pages will need to remain the older links, perhaps, until after a couple of years all previous three years of pages will be in Drupal. 

Actually, those older pages need to be PDF'd and linked to from our current 2020 page, per summary here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/legacy-rates/README.md#product-outline. 

This was the 'hard cut off' approach that we decided on for legacy page historic rate pages going back to those 2 years. 

So for example - on the Veteran rates page: https://www.va.gov/disability/compensation-rates/veteran-rates/
**The legacy history rate pages for** 

- 2018 rates: https://www.benefits.va.gov/COMPENSATION/resources_comp0117.asp
- 2017 rates: https://www.benefits.va.gov/COMPENSATION/resources_comp0116.asp

should be PDF'd and uploaded GH and linked to from our 2020 page; AND redirected to the 2020 page.

**Comment by AnneHurley** [comment]
@jenniferlee-dsva  - Yep - I'd been thinking of our earlier consideration to let the TS pages "die out naturally." I'll work on PDF'ing these pages and uploading into GH. @RLHecht FYSA

**Comment by AnneHurley** [comment]
[Effective Dec 2016 Historic rates-disability.pdf]
(https://github.com/department-of-veterans-affairs/va.gov-team/files/4548151/Effective.Dec.2016.Historic.rates-disability.pdf)
[Effective Dec 2017 Historic rates-disability.pdf]
(https://github.com/department-of-veterans-affairs/va.gov-team/files/4548153/Effective.Dec.2017.Historic.rates-disability.pdf)

**Comment by AnneHurley** [comment]
Historic rates PDFs for main disability compensation rates page: https://www.va.gov/disability/compensation-rates/

[Rates effective December 2017]
(https://app.zenhub.com/files/133843125/a8b9866f-d5ef-48dd-9f22-58a7fd17c57e/download)
[Rates effective December 2016]
(https://app.zenhub.com/files/133843125/a8d8e428-602b-4e6c-82c9-4441a119da25/download)

**Comment by AnneHurley** [comment]
Historic rates PDFs for main disability compensation rates page: https://www.va.gov/disability/compensation-rates/

[Rates effective December 2017]
(https://app.zenhub.com/files/133843125/a8b9866f-d5ef-48dd-9f22-58a7fd17c57e/download)
[Rates effective December 2016]
(https://app.zenhub.com/files/133843125/a8d8e428-602b-4e6c-82c9-4441a119da25/download)

**Comment by AnneHurley** [comment]
Historic rates PDFs for special monthly compensation rates:
https://www.va.gov/disability/compensation-rates/special-monthly-compensation-rates/

[Effective Dec 2016 - Historic rates - SMC]
(https://app.zenhub.com/files/133843125/91276aff-1fd1-4598-bc3c-1920df13107a/download)
[Effective Dec 2017 Historic rates - SMC]
(https://app.zenhub.com/files/133843125/f5b9cdbf-ccdd-4f16-b4ec-9fbadaf1eec1/download)

**Comment by AnneHurley** [comment]
Historic rates PDFs for special benefit allowance rates: https://www.va.gov/disability/compensation-rates/special-benefit-allowance-rates/

[placeholder]

**Comment by AnneHurley** [comment]
Historic rates PDFs for birth defects benefit rates: https://www.va.gov/disability/compensation-rates/birth-defect-rates/

[placeholder]

**Comment by AnneHurley** [comment]
@lunascoop @mnorthuis  Want to make sure we capture the legacy redirects mentioned above:

So for example - on the Veteran rates page: https://www.va.gov/disability/compensation-rates/veteran-rates/
The legacy history rate pages for

2018 rates: https://www.benefits.va.gov/COMPENSATION/resources_comp0117.asp
2017 rates: https://www.benefits.va.gov/COMPENSATION/resources_comp0116.asp

should be PDF'd and uploaded GH and linked to from our 2020 page; **AND redirected to the 2020 page.**

Each historic page that's being PDF'd will also need its URL redirected to the main 2020 respective rates page.

**Comment by mnorthuis** [comment]
Thanks @AnneHurley.   

@lunascoop I have a file of legacy URLs that need to be redirected, and there are about 15-20 for each type of rate. Can you and @ncksllvn decide how you want to handle these - should I update the top of this issue with all 70+ URLs or do we want to start a clean ticket for each rate type (i.e. all the veteran comp rates pages are in one ticket, all the special monthly allowance rates in another, etc. )

**Comment by lunascoop** [comment]
@jenniferlee-dsva @DanielleThierryUSDSVA should we hold off on these redirects until we can find a solution for the PDF hosting issue? Per my conversation with @AnneHurley I understand that:
- The legacy historic rates pages have been PDF'd but there's a hosting issue w/Drupal. Until that is resolved, we cannot link the _Effective rates for 2018, etc._ (in the Historic rates section) to their respective PDF'd rate page.

- The current legacy rates pages should also be redirected to their respective main benefit rates page (ex: https://www.benefits.va.gov/COMPENSATION/resources_comp0217.asp to https://www.va.gov/disability/compensation-rates/special-monthly-compensation-rates/). If this is done before the PDF hosting issue is resolved, wouldn't this cause a looping issue? Ex: A user clicks the [Rates effective December 1, 2017](https://www.va.gov/disability/compensation-rates/special-monthly-compensation-rates/) link (in the Historic rates section) and the page will essentially refresh itself.

Also per @mnorthuis [comment above](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7202#issuecomment-621408462), I think we should start a clean ticket for each rate type to capture the 70+ URLs and the added historic rate pages.

**Comment by AnneHurley** [comment]
@kelsonic  Here are the historic disability rates PDFs that need to be uploaded into GH media file:

1. For this page: https://www.va.gov/disability/compensation-rates/
[disability-rates-2017]
(https://app.zenhub.com/files/133843125/325aadc3-fb74-4128-a759-de89e2217f81/download)
[disability-rates-2018]
(https://app.zenhub.com/files/133843125/42ded996-9f0c-4866-92a5-5a9c19df3cf2/download)
@mnorthuis 
@RLHecht FYSA

**Comment by kelsonic** [comment]
Thanks @AnneHurley! There are many comments on this thread and I just want to make sure that we keep the original ticket description up-to-date. Could you verify that the ticket's description + acceptance criteria are still valid?

**Comment by AnneHurley** [comment]
@kelsonic - fair enough. I'll list the rest of the PDFs in the comment above - 4 groups of 2 each - and reiterate what the acceptance criteria are for these 4 pages. I think the @lunascoop  and @mnorthuis  task for 70 additional URLs to redirect should be its own ticket. What do you think, @lunascoop  and @DanielleThierryUSDSVA ?

I believe we can still proceed w/o the other legacy URLs mentioned, but someone can correct me if I'm wrong. thx!

**Comment by lunascoop** [comment]
@kelsonic @AnneHurley I agree that this ticket is getting too long (and will likely get longer and more complicated). I recommend converting this to a Redirect rates pages epic and creating a ticket for redirects associated with each disability rates page. @stephorkandatx is that ok?

**Comment by RLHecht** [comment]
@AnneHurley should the PDF work be put in the PDF ticket instead of this one?  https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/8408

**Comment by stephorkandatx** [comment]
@lunascoop @kelsonic @RLHecht I am converting this to an Epic & will create tickets for each disability rates page.

**Comment by AnneHurley** [comment]
@RLHecht I think it should be kept in here as part of these four pages' redirect requirements, and also added to the PDF ticket which I'll do now. Broader question is, should the PDFs for each type of page live in both the overall PDF ticket *and* their respective rates/redirects tickets? Or at least link?

**Comment by mnorthuis** [comment]
@AnneHurley @lunascoop @stephorkandatx 
All - this was originally a redirect ticket, and I'm not sure what work is remaining to do here - it somehow turned into a creating a PDF ticket?   Can you please review this ticket and determine if there is additional work to be done or if this can be closed?

**Comment by lunascoop** [comment]
@mnorthuis The redirects for the rates pages still need to be implemented. But before that can happen, the last three last years of legacy rates pages for each main rates page needs to be PDF'd, and their links in the Historic rates section pointed to the matching PDF. If redirects are implemented before this happens it will create a looping issue and the links on those pages will essentially route back to the current page. We have a meeting w/Jen Strickland tomorrow to review our PDF's from an accessibility point of view. From there, I believe we'll decide on a strategy to move forward and implement the redirects.

**Comment by mnorthuis** [comment]
All of the rates pages redirects are handled in separate tickets - these are all marked as ready to go once the PDFs are complete.  What is this ticket for?
Special comp - #8626
Special allow - #8627 
Birth defect - #8624
Veteran rates - #8622

**Comment by lunascoop** [comment]
We converted this ticket into an epic. Those tickets are now housed inside this epic.

**Comment by mnorthuis** [comment]
Ha!  My bad.  Got it.  Removing my assignment from this one.

**Comment by lunascoop** [comment]
The redirects is these tickets have gone live and are validated. Closing epic and updating stakeholders.
