### ISSUE TITLE
Determine if there is a Pattern for In-App System Down Messages

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#72046]
## Description
On 12/15, the BTSSS API was down. Mark made the decision to disable the travel feature flag for all users to prevent Veteran confusion. We need to explore if there is a pattern in the VA for when a subsystem on which an individual application feature relies is down or inaccessible for some period of time. We currently have a way to trigger a maintenance window & banner that we use when the main feature (i.e. check-in or pre-check-in) is down because of upstream dependencies, but when the BTSSS API is down, a Veteran can still do the main task (i.e. checking in) but would not be able to submit a travel claim. We need to discover if there is a standard VA way to let Veterans know that, while they can still check in, they will not be able to submit a travel claim because the BTSSS system is unavailable.

[Slack thread](https://dsva.slack.com/archives/C02UP02HHGX/p1702652442804269)

## Tasks
- [x] Determine if there is a pattern for in-app system down messages
- [x] Identify page or pages the component belongs on

**Comment by cgednalske** [comment]
Throwing some examples from other teams in here so they're all in one place and on hand:

### DS guidance

- [DS alert page guidance](https://design.va.gov/components/alert#warning-alert):

  - <img width="974" alt="Screenshot 2023-12-15 at 9 44 44 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/79372956/acc2c820-c8fd-46d5-9349-53d94e830de9">

- [Unscheduled downtime DS guidance](https://design.va.gov/content-style-guide/error-messages/system#unscheduled-downtime-notifications) (maintenance related, but can be used for reference)


### Examples used by other teams:

- **MyVA**
  - <img width="750" alt="Screenshot 2023-12-15 at 9 36 11 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/79372956/46408347-3d54-40b4-8bc3-70817f4e11d6">

- **Profile**
  - <img width="406" alt="Screenshot 2023-12-15 at 9 39 15 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/79372956/4fc76122-3b4e-46e1-9e2d-5199e7e45bc9">
  - <img width="371" alt="Screenshot 2023-12-15 at 9 38 45 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/79372956/687f5115-a137-44a3-9510-c38ac304e3b4">
  - <img width="478" alt="Screenshot 2023-12-15 at 9 38 03 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/79372956/8ea68d27-13d3-48c8-8864-113282bcd5e1">

**Comment by benbrasso-agile6** [comment]
Feels like this could be closed because it's solved

**Comment by loripusey** [comment]
@benbrasso-agile6 have we done the third task or do you want to wait to do that when we do a wireframe?

**Comment by benbrasso-agile6** [comment]
I think we can flesh out tasks 2 and 3 in this ticket. Task 1 seems completed. 

Then do the design and content in the next ticket.

**Comment by benbrasso-agile6** [comment]
@ytsaoca I created a page in Figma to demonstrate where the warning alert appears in the app and on the page. Do you want to go ahead and add the warning alert into each of those three frames on this page https://www.figma.com/file/sK2vIx6giAynNqUFR0l4Wx/Check-in-Production-%7C-Check-in?type=design&node-id=36%3A325&mode=design&t=udjtkFQEAj6BFxG3-1

Kelly will work on the content next week for the warning alert when she is back.
