### ISSUE TITLE
Minor vision upgrade of Vets-api Postgres DB to 11.6

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#7204]
## User Story or Problem Statement
We need to upgrade Vets-api's DBs to 11.6

## Goal
_Upgrade DBs from 11.5 to 11.6_

## Acceptance Criteria
- [x] _Dev is 11.6_
- [x] _Staging is 11.6_
- [x] _Prod is 11.6_

---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jbritt1** [comment]
Going to plan staging for Monday 3/30.
