### ISSUE TITLE
SOCKS access for Marcia Ortiz

### ISSUE THREAD

**Issue by maortiz-27-80** [department-of-veterans-affairs/va.gov-team#72048]
### Your Name

Marcia Ortiz

### Your Email

marcia@cityfriends.tech

### Your Role and Team

Product Manager - CMS 

### Product Manager (PM) name and email

Marcia Ortiz marcia@cityfriends.tech

### Product Owner (PO) name and email

Erika Washburn Erika.Washburn@va.gov

### Access Type Requesting

viewers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCcwY0xAujsvKkoYBswQPFLA706Wq5Xblr6r5ufdn/HBGbICGbVqxhIZ6MMOeDPJlvOsWLZkitVA5g2OJztcjdjezpWEdsrbgjLulfqXgtxT0uuroGR2vH11Rl17WLF10aMzxr8hUSn5w0JdUyTZeMrPetRXcdduBfDByf8QAMi/60usfkQsSv/Nb6heQ5YUIi3WfHy25NRVgDlj36kqF9ndpcIQT9ClZS04s8v3fVRdf2P/BEoiBoxPuazN9p/jMVuDeNbt0/VXun5t1WAi+nrYzhg72VMnH71yz4b5c2rbNcH3P3FOJ+pvXhciAOfV/LfrY/IijPBoIBNCWit+I+YWhGz1QmJNwcvXnnfxUDd20b0TQep9pRoH/sXieRgLlDID+sU6UDDczGVGYaBE3S4pYZaoHFRE+uvkjJZ6FZ16sF1BO6FxiDEz3mczVCaPKgNdKPzDX60s0f52dFH9FdymQPg7A++35JTUzHHdWwEMqiAq4OaeAjcWgIHI4K0U+s= marcia@marcias-MacBook-Pro

### E-QIP Transmittal Confirmation

![Transmittal-Notice-Ortiz-Marcia-Agile-Six-Applications-Inc-marcia-cityfriends-tech-cityfriends-tech-Mail](https://github.com/department-of-veterans-affairs/va.gov-team/assets/97988039/d762bf1f-32b8-40b4-8dd3-2d1a7f36e6bc)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by ph-One** [comment]
SOCKS access completed
