### ISSUE TITLE
Design | Figma migration | Update VA design system components once fixed

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#72085]
## Background
When migrating Sketch files to Figma, we noticed some components in the design system had a bug.  The buggy components have our content in place and are placed next to the appropriate frame, ready to move in once the DST applies their fixes.

We need to update our Figma files once those fixes are in place.  Since the fix tickets are in a different repo, we can't add them as blockers through Zenhub, but we can track them here:

**Components**

- Summary (featured content) [bug ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2298)
- Slim error alert  [bug ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2339)

## Tasks
Update the library/components in the following files:

- [x] Connected apps
- [x] Personal info
- [x] Contact info
- [x] Notification settings
- [x] Direct deposit
- [x] Account security
- [x] Profile hub
- [x] Military information

## AC
- Figma files align to what we see in storybook for the available components.

**Comment by andaleliz** [comment]
@mtcA6 fyi I am going to pick this up and start working on it.

**Comment by andaleliz** [comment]
While going through this, I checked on the guidance for addresses from the design system. They've updated it and there are changes to our form as a result. I've mocked them up and annotated them [on a separate page](https://www.figma.com/file/bFdl7MEIda4ExZIQuot84r/Profile---Contact-Information?type=design&node-id=262-5134&mode=design), and I think this should probably have a dedicated FE ticket as a result @mtcA6 @adamwhitlock1

**Comment by andaleliz** [comment]
All of the files are updated, but I can't close this out yet due to an outstanding bug w/ the modal buttons in personal information and the editing as a subtask page. I've reached out to the DS and I'm going to give them a day or two to respond. If they don't, I think I'll still close this ticket out as it's pretty minor and I can leave a comment to explain to anyone who peeks at the files what is going on.

**Comment by andaleliz** [comment]
They still haven't gotten back to me - going to leave this open until the end of the sprint but will close Tuesday if I don't hear by then.

**Comment by mtcA6** [comment]
@andaleliz great approach.

Do we need to spin up another ticket to toss in the backlog and we can come back to that in a few weeks?

**Comment by andaleliz** [comment]
@mtcA6 nah, I don't think so - I have a feeling it'll be a 2 minute fix once they respond to me. I set a reminder on my message to them to reach back out to them before the end of the sprint, and if it happens after the fact it'll probably take more time to create/monitor tickets than to just implement whatever fix they propose.

**Comment by andaleliz** [comment]
Dan got back to me today and helped me troubleshoot. We're all good to go.
