### ISSUE TITLE
Vets-api terminal access for Brandyn Sullins

### ISSUE THREAD

**Issue by HeatherRienks** [department-of-veterans-affairs/va.gov-team#72095]
### Your Name

Brandyn Sullins

### Your GitHub handle (terminal access is managed through GitHub)

@OptionSelect

### Your dsvagovcloud AWS user name (if applicable)
n/a

### Team, Role, and Company of the target individual

Debt Resolution, Front End Engineer, GovCIO

### Product Manager (PM) name and email

Tom Davis, thomas.davis@govcio.com

### Product Owner (PO) name and email

Denise Coveyduc, denise.coveyduc@va.gov

### COR Name (leave "None" if you listed an AWS user name above)

Jennifer O'Day

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

Agile Six - Anthony M. Arashiro

### Please confirm if you are on the VFS Team Roster or Platform Team Roster

- [X] [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Please confirm E-QIP Transmittal/Adjudication. This could be a screenshot of your Transmittal/Adjudication email, a link to another request where you've submitted this proof (i.e. AWS/SOCKS), etc.

- [X] I have attached proof that I have either transmitted my E-QIP survey or previously received a favorable decision (by including in "Additional Notes" section below)

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### Additional Notes

Brandyn needs access to assist in troubleshooting FSR - Form 5655 submissions for Veterans.

### Additional resources for Support Engineer

- [ ] For users on a VFS team but not in the VFS Team Roster, they must start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] Instructions for handling requests [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access) - Support Only

**Comment by HeatherRienks** [comment]
![Brandyn Sullins T2 adjudication - ticket 72095](https://github.com/department-of-veterans-affairs/va.gov-team/assets/85908655/dfc223b2-1043-47cd-8e31-42674ee0bb10)

**Comment by IsaiahMW1** [comment]
@HeatherRienks @OptionSelect The screenshot provided does show favorable adjudication and dates. It doesn't provide a name, Can you please show the screenshot with name provided when you get a chance please?

**Comment by HeatherRienks** [comment]
@IsaiahMW1 - please see attached and advise if this will suffice. Thanks!
![72095 - detailed proof for Brandyn Sullins](https://github.com/department-of-veterans-affairs/va.gov-team/assets/85908655/6453b55c-206e-4ea1-96e4-e84d84a9b901)

**Comment by IsaiahMW1** [comment]
@HeatherRienks  Access has been granted to the dev, staging, and sandbox environments. 
Access for user for prod needs approval by OCTODE.
Here's some additional documentation for the [Vets API on EKS]
(https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-TerminalAccess)

Here's some additional documentation for the [Vets API on EKS]
(https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-TerminalAccess)

**Comment by IsaiahMW1** [comment]
Access for user @HeatherRienks  for prod has been approved by OCTODE and you have been granted access.

**Comment by lindsay-insco** [comment]
@OptionSelect Your Vets API Terminal Production access has expired.

Would you like to request an extension? You have 72 hours to respond, or your
access will be revoked and you will need to fill out a new request.

**Comment by HeatherRienks** [comment]
@lindsay-insco - yes, please extend for @OptionSelect. Thank you for this note!

**Comment by lindsay-insco** [comment]
@LindseySaari @ericboehs can one of you please give us a 👍 to extend their Vets-API Terminal access?

**Comment by HeatherRienks** [comment]
@lindsay-insco - just confirming that @OptionSelect 's access will not be affected. Thank you!

**Comment by lindsay-insco** [comment]
Access for @OptionSelect not needed at this moment. Production access removed. If production access is required again, please fill out a new ticket.
