### ISSUE TITLE
AWS access for Kanchanadevi Suriyamoorthy

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#72136]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Agile Six - Anthony M. Arashiro

### E-QIP Transmittal Date

- [ ] Check this box if you have an E-QIP transmittal date.

### Your Name

Kanchanadevi Suriyamoorthy

### Your Email

ksuriyamoorthy@kindsys.us

### Team, Role, and Company of the target individual

Check In Experience Team, Software Engineer, Kind Systems

### Product Manager (PM) name and email

Lori Pusey, lori.pusey@agile6.com

### Product Owner (PO) name and email

Lori Pusey, lori.pusey@agile6.com

### Desired AWS Access

I need access to AWS Parameter Store in dsvagov cloud AWS account.

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

<img width="712" alt="Screen Shot 2023-12-18 at 9 57 22 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/89944361/55362710-ecd3-4106-b311-b9f668e071cb">

### Additional Notes

I need access to store secret keys & IV values for encrypting data in vets-api backend server

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by hgbarreto** [comment]
group membership required - `adhoc-vetsgov-ssm-prod`
@department-of-veterans-affairs/operations-aws-approvers  - User is requesting access to parameter store.

**Comment by JonathanKamensDVA** [comment]
Forgive me if this is a dumb question... I assume we have separate parameter stores and secrets managers for production vs. non-production accounts. If so, then I would expect the secrets and parameters in production accounts to be populated by the platform devops team rather than by VFS software engineers. Is that not how things are typically done?

**Comment by flooose** [comment]
@hgbarreto are you sure prod access is being requested here. The request is only mentioning parameter store in general. @kanchanasuriya could you give us clarity on this, if lower-level access is sufficient.

@JonathanKamensDVA iirc _setting_ the secrets is generally done by the devops team, independent of the environment. This request says nothing about **write** access either. Do you know something that I don't, or are you just asking out of general curiosity?

**Comment by JonathanKamensDVA** [comment]
@flooose, like you, I was just trying to understand whether this was indeed a production access request.

**Comment by kanchanasuriya** [comment]
@flooose We used to have access to production for adding secrets in paramstore.  Please let me know if there is any change in the process.  Otherwise, looking for regaining access to staging & production to add secrets in paramstore

**Comment by JonathanKamensDVA** [comment]
@kanchanasuriya I am not sure about this please let me do a bit of digging and get back to you. Might be next week, there are people I'd like to check in with about this who are out this week.

**Comment by JonathanKamensDVA** [comment]
Let's approve this production access for the next three months and then we'll revisit. We're having a discussion about how we want to handle prod parameter store / secrets store access moving forward, but in the meantime that should not interfere with @kanchanasuriya's ability to get their work done.

**Comment by little-oddball** [comment]
@patrick-black-oddball - Looks like this person previously had access and this is a "renew" so no need for updated documentation.

**Comment by ph-One** [comment]
@kanchanasuriya is this access still needed? I can grant you developer access, which should give you the access you need

**Comment by ph-One** [comment]
> @kanchanasuriya is this access still needed? I can grant you developer access, which should give you the access you need

Looks like you are already a part of the developers group. Do you have the access you need -- can we close this ticket?

**Comment by kanchanasuriya** [comment]
Thank you for checking.  Closing the ticket as I have access now.
