### ISSUE TITLE
[BE] - Figure out which facilities endpoint to use

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#72147]
## Summary
There exists two facilities API endpoints: 
https://veteran.apps.va.gov/facilities/v2/facilities/
https://developer.va.gov/explore/api/va-facilities/docs?version=current

This ticket is to figure out which one to use along side the VASO appointments endpoint.

## Tasks
- [ ] [BE] Determine best endpoint
- [ ] [BE] Get API key for correct endpoint if needed

**Comment by kanchanasuriya** [comment]
After the discussion VAOS team, https://veteran.apps.va.gov/facilities/v2/facilities/ is the right endpoint to use for fetching facilities info.
