### ISSUE TITLE
Burial | List of Error Messages

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#72140]
## Issue Description
_As a designer or content reviewer, I need to understand what all the error messages are within the Burial 530EZ form, so I can create a complete user experience._

---
## Tasks
- [ ] Find all the error messages within the online Burial 530EZ form

## Acceptance Criteria
- [ ] List of error messages provided to Fiorella

**Comment by steele-lm** [comment]
@fiorella-io I created a ticket for the error messages, but please add any additional detail you might need.

**Comment by sortizsh** [comment]
Sean is working on a list now, and will send to Fiorella when it's complete
