### ISSUE TITLE
[Cert renewal] Cert renewals

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#72141]
## Description
Renew the following certs

## Resources 
- Team huddle
- https://vfs.atlassian.net/wiki/spaces/OT/pages/1644625921/SSLMate+Renew+or+Obtain+Publicly+Signed+SSL+Certificates

## Acceptance Criteria
- [x] www.va.gov
- [ ] preview.va.gov
- [x] dev-preview.va.gov
- [x] design.va.gov

## Refinement Guidance - Check the following before working on this issue: 
- [x] _Team label assigned ("platform-tech-team-2")_
- [x] _Epic assigned (if needed)_ 
- [ ] _Estimated (points assigned)_
- [x] _Sprint assigned (once planned)_
- [x] _Team member(s) assigned_
- [x] _Understands how this work aligns with the overall platform_

**Comment by ph-One** [comment]
www.va.gov INC30575682

**Comment by ph-One** [comment]
design.va.gov : https://yourit.va.gov/nav_to.do?uri=incident.do?sys_id=0898463d1b733d50f48a8627624bcbe9 (INC30887829)

**Comment by ph-One** [comment]
preview.va.gov and dev-preview.va.gov are not used anywhere. Their certificates have been renewed and their keys updated in Parameter Store, but since this domain is not currently active, there are no actions to take with the certificates themselves.
