### ISSUE TITLE
EKS testing placeholder

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#72142]

**Comment by npeterson54** [comment]
Moving into next sprint, this will be an ongoing effort with the product team

**Comment by ph-One** [comment]
IAM work needs done for Elasticache

**Comment by ph-One** [comment]
Worked with Chris and Kshitiz surrounding some ways to test Vets API in the EKS 1.28 (vetstest) cluster

**Comment by npeterson54** [comment]
Closing out for sprint
