### ISSUE TITLE
[QA] 10-10EZR: Test Insurance not going through issue (71804)

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#72162]
- [ ] Ask Matt L what, other than insurance, is impacted by this bug
- [ ] Write Test cases or [utilize existing ones](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/10-10EZR%20Form/End-2-End%20Testing/Test%20cases%20with%20ES.md)
1. Go to EZR
2. - Submit updated Insurance information and Medicare and Medicaid information
3. - Submit EZR form
4. - Check with JF to make sure info has gone through
- [x] Test contact info (email & home phone), marital status, medicaid eligibility and medicare enrollment
Run tests and make sure it works with JF
- [x] Ensure this doesn't impact a user's ability to go through form with Screen Reader
- [x] **Success: All info goes into VES when submitted on EZR**

**Matt's Note on Root Cause:
Root cause of this issue stems from data structure updates that were performed to meet accessibility conflict with the data structure of the prefill data. This was causing new values that were input into the form to not overwrite prefill values that were already in the form data with the same key name.
The solution is simply to reformat the prefill data when it comes into the form to meet the structure created by the forms library.
Additionally, it should be noted this was an issue across multiple values, including contact info (email & home phone), marital status, medicaid eligibility and medicare enrollment. This issue also prevented prefill data from being populated on those pages to begin with.**

**Comment by fbonds** [comment]
All tests pass.  Medicare, Medicaid, Private Insurance and contact info update on back end when sent through EZR.  No impact found to screen reader accessibility.
