### ISSUE TITLE
[QA] 10-10 EZR: Test staggered rollout content widget

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#72187]
As a team member, I want to make sure that only 10% of visitors to the EZR static page can access the online EZR so that I can conduct a staggered rollout and make sure that if there are any bugs, they're caught quickly and don't impact too many people. 

- [ ] Write test cases to test user story #[71934](https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/71934)
- [ ] Verify that content for online EZR appears ~10% of the time
- [ ] Make sure content matches the content in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65056#issuecomment-1860930074)
- [ ] Verify that the other 90% you do not see the content for online EZR
- [ ] Make sure that you can sign in and do the online EZR when it appears
- [ ] Work with Matt L as needed
- [ ] **Success: 10% of users see the online EZR content**

**Comment by hdjustice** [comment]
Closing - Aliyah & Copy editor tested static page - functionality working as expected.  At this time, we are not testing the feature toggle/widget functionality.  There is a small copy change needed and we will monitor traffic.
