### ISSUE TITLE
[Letters] Log discrepancies in the number of eligible letter types to DataDog

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#72180]
## Background
We have been getting reports of discrepancies between the number of letter types that EVSS indicates that the Veteran is eligible for vs the number of letter types that Lighthouse indicates the Veteran is eligible for. In order to help diagnose the issue, we need to add a way to send a log to DataDog when there is a discrepancy between the number of eligible letters that are returned. We should also verify what letter type

## Considerations
**DataDog log**
- We should log the number of discrepancies between the lists of eligible letters returned by EVSS and Lighthouse. In order to indicate whether Lighthouse or EVSS returned more letter types, it makes sense to:
  - Prepend a + (plus) when Lighthouse returns more letter types (eg. +5 if LH returns 5 more letter types)
  - Prepend a - (minus) when EVSS returns more letter types (eg. -3 if EVSS returns 3 more letter types)
- It would also be beneficial to log the letter types that both services return as well so that we don't have to manually retrieve both lists in prod
- If we give it a @payload.message_type` of something like `lh.letters_generator.count_discrepancy`, then we should be able to easily create a monitor that alerts whenever a log with that message_type is sent to DataDog

**New Controller**
- We should name it something like `letters_generator_discrepancies` and it should only have an `index` method
- This controller should return an empty array or nil

**DataDog Monitors**
This is the monitor that was used for Rated Disabilities
- https://vagov.ddog-gov.com/monitors/172081

## Open Questions

- Should we log not only the magnitude but also the absolute counts from EVSS and Lighthouse? 

### Backend
- [x] Create new feature toggle named `letters_check_discrepancies`
- [x] Create new controller that calls both EVSS and Lighthouse letters services (index method only)
- [x] Add new route for the new controller (index route only)
- [x] Log discrepancy count and returned letter types for both EVSS and Lighthouse to DD when discrepancies are detected
- [x] Create specs for this new controller

### Frontend
- [x] Integrate new feature toggle with platform code so it's in the list of feature toggles in the redux store
- [x] Call the new discrepancies controller when the feature toggle is enabled

## Acceptance Criteria
- [x] We are logging the magnitude of the difference between the list of eligible letters returned by Lighthouse and EVSS to DataDog
- [x] The log includes the eligible letter type names returned by both services
- [x] A feature toggle has been created to allow us to turn this functionality on and off / control the number of users that are opted into this feature
- [x] There is a controller that calls both services to get the lists of eligible letters and logs to DataDog when there are discrepancies between the lists
- [x] When the controller sends a log to DataDog, there is a monitor in DataDog that will send an alert to our slack channel

**Comment by HeatherWidmont** [comment]
cc @samcoforma for visibility. This one may be next in priority if we finish sprint goals - need to verify with Jacob

**Comment by HeatherWidmont** [comment]
@samcoforma & Peri to pair to finish the unit tests today & try to get it merged so they can start collecting data to set up a dashboard on DD

**Comment by HeatherWidmont** [comment]
@samcoforma & @pmclaren19 to pair to review the feedback that Jerek left. Goal is to get the BE merged today - FE will be a bit delayed because it needs to be reviewed by Platform

**Comment by HeatherWidmont** [comment]
@samcoforma will check if its on the servers today, if so he will turn on the feature flag for 1% of the people & when enough have come in he will turn the feature flag off & start making the DD dashboard

**Comment by samcoforma** [comment]
Changed last acceptance criteria item from "When the controller sends a log to DataDog, there is a monitor in DataDog that will send an alert to our slack channel" to "We have an easy way to view what gets logged via a dashboard" after conversation with the team. We're only doing this logging for a short time, so the slack monitoring felt like overkill.
