### ISSUE TITLE
Review Questions for Stakeholders (686)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#7219]
## Goal
Gain clarification from stakeholders on various issues 

## Tasks
- Refine questions and let Steve know its ok to schedule

## Acceptance Criteria
- [x] Questions are ready for stakeholders

**Comment by sporeboy** [comment]
Revisions made to question posted in Slack thread. OK to proceed.

**Comment by jason-gcio** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/discovery/stakeholders/686-workflow-questions.md
