### ISSUE TITLE
SPIKE | Determine Feasibility of skipping retries for certain error types

### ISSUE THREAD

**Issue by tblackwe** [department-of-veterans-affairs/va.gov-team#72204]
In 6896/674 submissions, there are some errors that will never succeed, regardless of how many retry attempts we perform

- Invalid Zip Code
  - [Datadog Link](https://vagov.ddog-gov.com/logs?query=%40named_tags.class%3A%28%22BGS%3A%3ASubmitForm686cEncryptedJob%22%20OR%20%22BGS%3A%3ASubmitForm674EncryptedJob%22%29%20-status%3A%28warn%20OR%20info%29%20%40message_content%3A%28%22insertBenefitClaim%3A%20Invalid%20zipcode.%22%29%20&cols=host%2Cservice&index=%2A&messageDisplay=inline&refresh_mode=paused&sort=time&stream_sort=desc&view=spans&viz=stream&from_ts=1701579600000&to_ts=1702789140000&live=false)
- ORA errors
  - [Datadog Link](https://vagov.ddog-gov.com/logs?query=%40named_tags.class%3A%28%22BGS%3A%3ASubmitForm686cEncryptedJob%22%20OR%20%22BGS%3A%3ASubmitForm674EncryptedJob%22%29%20-status%3A%28warn%20OR%20info%29%20%40message_content%3AORA-%2A%20&cols=host%2Cservice&index=%2A&messageDisplay=inline&refresh_mode=paused&sort=time&stream_sort=desc&view=spans&viz=stream&from_ts=1701579600000&to_ts=1702789140000&live=false)
- Max EP Errors
  - [Datadog Link](https://vagov.ddog-gov.com/logs?query=%40named_tags.class%3A%28%22BGS%3A%3ASubmitForm686cEncryptedJob%22%20OR%20%22BGS%3A%3ASubmitForm674EncryptedJob%22%29%20-status%3A%28warn%20OR%20info%29%20%40message_content%3A%22%28ns0%3AServer%29%20StandardDataWebServiceBean--%3EfindBenefitClaimTypeIncrement--%3EMaximum%20number%20of%20EPs%20reached%20for%20this%20bnftClaimTypeCd.%22&cols=host%2Cservice&index=%2A&messageDisplay=inline&refresh_mode=paused&sort=time&stream_sort=desc&view=spans&viz=stream&from_ts=1701579600000&to_ts=1702789140000&live=false)
- Incident Flashes
  - [Datadog Link](https://vagov.ddog-gov.com/logs?query=%40named_tags.class%3A%28%22BGS%3A%3ASubmitForm686cEncryptedJob%22%20OR%20%22BGS%3A%3ASubmitForm674EncryptedJob%22%29%20-status%3A%28warn%20OR%20info%29%20%40message_content%3A%22GUIE50041%26FABusnsTranRule%28CFABUSNS_TRAN%29%20Failed%20with%20Exception%21%21%20%20FILE%3A%20FABTInterfaceCreator.cpp%20%20LINE%3A%20354This%20update%20is%20being%20elevated%20for%20additional%20review%20due%20to%20an%20Incident%20Flash%20associated%20with%20this%20Beneficiary%3A%20-%20An%20unexpected%20error%20was%20encountered.%20%20Please%20contact%20the%20System%20Administrator.%20Error%20is%3A%20GUIE50041%26FABusnsTranRule%28CFABUSNS_TRAN%29%20Failed%20with%20Exception%21%21%20%20FILE%3A%20FABTInterfaceCreator.cpp%20%20LINE%3A%20354This%20update%20is%20being%20elevated%20for%20additional%20review%20due%20to%20an%20Incident%20Flash%20associated%20with%20this%20Beneficiary%3A.%22&cols=host%2Cservice&event=AgAAAYxvNdz7ux2iIAAAAAAAAAAYAAAAAEFZeHZOZU5CQUFDWHFRVzNWcVZPS3dBVQAAACQAAAAAMDE4YzZmMzgtMTdhZC00ZjJkLWEwNzMtNTk2NTMxOTEzYjA2&index=%2A&messageDisplay=inline&refresh_mode=paused&sort=time&stream_sort=desc&view=spans&viz=stream&from_ts=1701579600000&to_ts=1702789140000&live=false)
- External ID too long
  - [Datadog Link](https://vagov.ddog-gov.com/logs?query=%40named_tags.class%3A%28%22BGS%3A%3ASubmitForm686cEncryptedJob%22%20OR%20%22BGS%3A%3ASubmitForm674EncryptedJob%22%29%20-status%3A%28warn%20OR%20info%29%20%40message_content%3A%2AEXTERNAL_UID%2A%20&cols=host%2Cservice&index=%2A&messageDisplay=inline&refresh_mode=paused&sort=time&stream_sort=desc&view=spans&viz=stream&from_ts=1701579600000&to_ts=1702789140000&live=false) 

This ticket will determine the feasibility of skipping retries on the above errors 

AC:
- [ ] In comments, document how to *programmatically* determine that each of the above errors occurred 
  
- [ ] Ticket created to implement above approach OR
- [ ] Determine that it is not feasible

**Comment by tfink419** [comment]
All the errors end up at the rescue within the 686c and 674 sidekiq jobs but they occur somewhere in the `lib/bgs` code and they then eventually get reraised with a different message at `lib/bgs/exceptions/bgs_errors.rb` raise_backend_exception method. On researching how to access the previous error message I've discovered there is a method on the base Ruby Exception class called `cause` that allows the previous error to be referenced and the message from that filtered. I've tested this locally and it appears within the rescue of the job `e.cause.message` can be checked and the messages filtered based on this.
