### ISSUE TITLE
1010-D Backend Implementation

### ISSUE THREAD

**Issue by cloudmagic80** [department-of-veterans-affairs/va.gov-team#72225]
Acceptance criteria
- Automatically generated PDF stored in a temporary file

**Comment by cloudmagic80** [comment]
[vha_10_10d-tmp.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2VEQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2064fe7d4af6a14f1b29c29006864c3250a27ca3/vha_10_10d-tmp.pdf)

The attached is the generated pdf file from the 1010D implementation directly from the front end

**Comment by cloudmagic80** [comment]
All backend for 1010D work is already in production.

**Comment by baltes** [comment]
Looks great, thanks Don. Closing this issue.
