### ISSUE TITLE
Research Spike: 1010-D Pega/Daper migration from Benefits Intake API

### ISSUE THREAD

**Issue by cloudmagic80** [department-of-veterans-affairs/va.gov-team#72222]
Currently, all digital forms use the benefits intakes api for pdf transmissions.  API first provides an upload location and unique submission identifier, and then accepts a payload consisting of a document in PDF format, zero or more optional attachments in PDF format, and some JSON metadata. We try to validate (optional) the zipcode,fileNumber, veteranFirstName, veteranLastName and businessLine fields before submission according to their description in the DocumentUploadMetadata model and use the 'businessLine' attribute for the most efficient processing.

Questions we have are:
1. If the Benefits API provides an upload location for PDF submissions, why do we need to create another system that does the same thing?

2. How will we validate the PDF submissions? For the Benefits API, we use zipcode,fileNumber, veteranFirstName, veteranLastName and businessLine fields before submission according to their description in the DocumentUploadMetadata model and use the 'businessLine' attribute for the most efficient processing.

3. What will be the Authentication and Authorization method for the api endpoint?

4. Will there be a sandbox environment?

5. Can we have test data?

6. Are there any file size limits for the PDF and attachments?

7. We will need a return receipt, for messages example: received, processing, success, or vbms. If the document status is error, VA has not received the submission and cannot honor the submission date as the date of receipt.

8. Will there be any status caching?

**Comment by baltes** [comment]
@cloudmagic80 Do you have answers captured somewhere for the questions above?

**Comment by baltes** [comment]
Open questions carried over to #72804 after clarification that we won't be using the benefits API
