### ISSUE TITLE
Edit button on Forms Review page should be right aligned

### ISSUE THREAD

**Issue by jeana-adhoc** [department-of-veterans-affairs/va.gov-team#72220]
## Issue Description
In [staging review for 20-10206](https://github.com/department-of-veterans-affairs/va.gov-team/issues/72159) our review page was flagged because on sections where we don't have an `h4` the edit button, the edit button floats to the left. The h4 is useful for forms that have multiple pages per step, but many of our forms are simple, and have only one page per step, and that 'step' is also the h3 of the accordion, so having it also as an `h4` would cause redundant headings.

Screenshot from 20-10206:
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/117098918/d04c73b5-1078-49b4-9203-f40c11651d1e)

## What we expect:
<img width="634" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/117098918/03ae01b7-aece-479f-9245-364ecb0c6476">

## Impact:
This is impacting all forms on production that currently don't have h4s on their review page

## This seems to be a regression issue connected to work done here:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/64149
https://github.com/department-of-veterans-affairs/vets-website/pull/25744

**Comment by Mottie** [comment]
Fix has been merged! Please feel free to close after you've verified the change in staging.

**Comment by jeana-adhoc** [comment]
This has been fixed! Thank you @Mottie !

<img width="647" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/117098918/428e334b-303a-427e-ac3f-ec04235b6d61">
