### ISSUE TITLE
[Development] HLR: Add SSN to header for Decision Review Lighthouse requests

### ISSUE THREAD

**Issue by SMLuthi** [department-of-veterans-affairs/va.gov-team#7223]
# Purpose
The Lighthouse team has deemed it protocol that certain data needs to be included in the request headers instead of the request json body. 

## What we need to do
Currently, we do not include the veterans social security number, now we want to include this in the header of the request(s) we send to the decision review lighthouse API. Lighthouse team should be asked to see exactly what this header variable is called/should look like as well as if its required for EVERY request we make to them, or just for the POST higher level reviews.

The new variable will be named `X-VA-SSN`

Note: This should follow ticket #7197 since we need to update the POST endpoint and rewrite vcr cassettes.

## Def of Done
- [ ] Add SSN to decision review service request headers

**Comment by annaswims** [comment]
completed in https://github.com/department-of-veterans-affairs/vets-api/pull/4443
