### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by janieTC-USDS** [department-of-veterans-affairs/va.gov-team#72250]
### Name

Janie Tankard Carnock

### Email

jane.carnock@va.gov

### Role

Product Manager

### Team

MHV on VA.gov - Secure Messaging

### Product Manager (PM) name

Myself / Lauren Alexanderson

**Comment by naomimarcussen** [comment]
Invite has been sent.

**Comment by naomimarcussen** [comment]
Invite has been sent.
