### ISSUE TITLE
Datadog access request - process change

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/va.gov-team#72256]
### Description
This process was previously managed by the DOTS team, but was recently changed to go through ECC. The instructions in yourIT are out of date [here](https://depo-platform-documentation.scrollhelp.site/developer-docs/get-access-to-datadog). I've attached an instruction pdf I'm using with my team for Okta and Datadog requests in case it's useful. 
[Monitoring Access.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/13719163/Monitoring.Access.pdf)

Link to announcement in DSVA slack: https://dsva.slack.com/archives/C01U8EYHSEM/p1702415385865849?thread_ts=1702410565.047609&cid=C01U8EYHSEM

Copy below:
ANNOUNCEMENTS
Please be informed that the DOTS team is no longer responsible for Datadog and will not be resolving Datadog requests. Please follow the steps below showing the new process for your Datadog requests:
How to Submit a ServiceNow Ticket for DataDog Requests

The steps below show how to submit new monitoring requests, or, updates to existing monitoring (requests to the ECC group. This group is now responsible for ALL Datadog issues such as adding or modifying users roles Enterprise monitoring, dashboards, or alerts for an Application Service, or to add or remove services, network devices, or administering other equipment to/from monitoring tasks.

- Go to the ServiceNow Portal at [ECC (Enterprise Command Center) Monitoring Services - your IT Service Portal (](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fyourit.va.gov%2Fva%3Fid%3Dsc_cat_item%26sys_id%3D4cdf488b1ba4fcd412979796bc4bcb74&data=05%7C01%7C%7Ccb701e4e7fc944b6041308dbeacea9aa%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C638361945550254440%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=sJfq3j8vnXwdtuQrfY%2FBaRttaqyOpKA6X17O8TMK9ug%3D&reserved=0)[va.gov](http://va.gov/)[)](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fyourit.va.gov%2Fva%3Fid%3Dsc_cat_item%26sys_id%3D4cdf488b1ba4fcd412979796bc4bcb74&data=05%7C01%7C%7Ccb701e4e7fc944b6041308dbeacea9aa%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C638361945550254440%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=sJfq3j8vnXwdtuQrfY%2FBaRttaqyOpKA6X17O8TMK9ug%3D&reserved=0)
    - Complete the HelpDesk form.
    - Use the drop down to select the application option where available
    - Follow the remaining steps as applicable
- You can attach any supporting documents such as a list of servers using the “paperclip” in the lower right-hand corner of the form.
- Someone on the Monitoring Design Team will contact you to discuss your requirements.
- To check the status of your ticket/request you can go to https://yourit.va.gov/va and click on your name in the upper right corner of the screen.

### Relevant URLs
https://yourit.va.gov/va?id=sc_cat_item&sys_id=4cdf488b1ba4fcd412979796bc4bcb74

### Which type of team are you on? (Platform team, VFS team, or Leadership)
VA Notify

**Comment by johnny-jesensky-adhoc** [comment]
Hi @mjones-oddball, thank you for flagging this, and for providing that PDF document! It's very helpful to reference. Yes, we recently learned of the change in process, and will be making some updates to a few pages.

- [Get Access to Datadog](https://depo-platform-documentation.scrollhelp.site/developer-docs/get-access-to-datadog)
- [Troubleshooting Access to Datadog](https://depo-platform-documentation.scrollhelp.site/developer-docs/troubleshooting-access-to-datadog)

We will provide further updates in this ticket.

**Comment by johnny-jesensky-adhoc** [comment]
Hi @mjones-oddball, I just wanted to provide a quick update on this - I have been using the PDF you provided to make some changes/edits to our official documentation on Datadog access. I am currently reviewing them with an engineer to make sure the steps are clear and accurate before we make any of the changes live.

I will continue to provide updates on this ticket, and will let you know when the new docs are live. Please feel free to reach out if you have any questions. Thanks!

**Comment by johnny-jesensky-adhoc** [comment]
Hi @mjones-oddball, we have updated the [documentation on gaining access to Datadog](https://depo-platform-documentation.scrollhelp.site/developer-docs/get-access-to-datadog) on the Platform Website. Thank you for providing these instructions and attached PDF - they were very helpful!

Please let us know if you have any questions. Closing this ticket.

FYI @jknipes

**Comment by mjones-oddball** [comment]
Hi @johnny-jesensky-adhoc Thank you! My only note of feedback is that you might want to update the hosting location section to be more generic. The requestor would need to know what datadog application they are requesting access to and to list that and/or any others they may need access to. Totally fine to use vanotify and the others as examples, but they'll all be named by product.

```
Hosting Location:

Request access to the vanotify-va-datadog application. If you need access to other apps (e.g. vetext-va-datadog, vagov-va-datadog, vagov.ddog-gov, etc.), you can list those as well.
```

**Comment by johnny-jesensky-adhoc** [comment]
Hi @mjones-oddball - thank you - feedback noted! We'll look to revisit that guidance so it is a bit clearer. Thanks.

FYI @jknipes
