### ISSUE TITLE
Wave 2: Backend Docs

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#72267]
From Johnny on Content Team:
I've specifically grouped these pages into 5 groups based on where they are in IA, that can hopefully, (potentially), be assigned to the same person.
 - [x] 2a - Supporting Code 
 - [x] 2b - Running Vets API Locally
 - [x] 2c - Tools & Debugging
 - [x] 2d - Backend Standards + Architecture
 - [x] 2e - Misc
I've updated the [dev docs audit spreadsheet ](https://docs.google.com/spreadsheets/d/1PPhlba7PiCTWkJUWKHxH36rck0lfKtBSjSpqrCCBxv0/edit#gid=306322713)with this information, that also has the links to each of the pages. Is this a helpful format? I know weren't able to connect this week to talk through this, so if it's easier to track these in separate Zenhub tickets with specific AC, I'm also happy to create those.

**Questions**
(Resolve any launch-blocking issues identified by the Content team)
Is this info still accurate and up-to-date? Including screenshots, code blocks, etc.
Is this info still relevant?
Is there any info missing that should be added?
Does this page still make sense to live where it is in the IA?
Does any content need to be retired and/or archived?

**Comment by LindseySaari** [comment]
I have started on the 2a documentation. They mostly just need introductions.

**Comment by LindseySaari** [comment]
2b is nearly complete. Writing some follow up tickets for the backend CoP and I will check the box.
