### ISSUE TITLE
[MVP] Perform API meta data validation

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#72276]
## Issue Description
As a Pension team relaunch the online form,
we need to ensure that the form's meta data maps to the Lighthouse Benefits Intake API we're migrating to properly,
so that we can identify and correct any issues.

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- As a team, we will validate and identify any issues regarding the meta data mapping to the Lighthouse Benefits Intake API

**Comment by wayne-weibel** [comment]
https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team/70638

https://dsva.slack.com/archives/C053U7BUT27/p1703793393620849
