### ISSUE TITLE
Sections duplicated on Mock users and data helper functions page

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#72272]
### Description

The sections starting with the `Test Data: cy.syncFixtures(fixtures)` heading appear to be duplicated.

Update: as I look at this page further, it appears to be entirely out of date - the `cy.syncFixtures` helper mentioned no longer seems to exist. I think a member of the frontend CoP should probably review and update the page for currency.

### Relevant URLs

https://depo-platform-documentation.scrollhelp.site/developer-docs/mock-users-and-data-helper-functions

### Which type of team are you on? (Platform team, VFS team, or Leadership)

OCTO engineer

**Comment by johnny-jesensky-adhoc** [comment]
Hi @acrollet, thanks for flagging this. We've added this to our team's backlog, and will connect with some engineers who can help determine how to best update this page.

We appreciate the information on this, and will provide further updates in this ticket. Thanks!

**Comment by jknipes** [comment]
Work was completed on ticket [72432](https://app.zenhub.com/workspaces/department-of-veterans-affairsvagov-team-62447fb44deeed001392c57f/issues/gh/department-of-veterans-affairs/va.gov-team/72432). Moving to _Done_
