### ISSUE TITLE
Create High Level Thumbnail View for Educational and Career Counseling (CH36)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#7230]
## Goal
A journey map is a handy thing to have for understanding how a feature works.  

## Tasks
- [x] Based on the walkthrough, create a high level thumbnail view of the workflow and Veteran user experience

## Acceptance Criteria 
- [ ] A high level view of the feature is saved in the feature folder

**Comment by sporeboy** [comment]
Initial pass at current feature flow and possible IA here: https://xd.adobe.com/view/f2e4cdec-1fa1-42ab-5cbf-e2a3c74c6663-84d5/

**Comment by sporeboy** [comment]
MD doc is ready for review here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-CH36-VRE-counseling/research-design/ch36-vre-user-flows.md
