### ISSUE TITLE
[FE] 10-10EZR: Cross-train Matt K. on EZR

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#72313]
As a team member, I would like to cross-train Matt K on EZR so that we're not solely reliant on Matt L. and so that we can get more EZR FE work done.

**AS Note: These are some high level ideas I have, but I'm open to more ideas and other ways of doing this**
- [x] Walk MK through the code base
- [x] Walk MK through the EZR app (if he hasn't done so in depth already)
- [x] Pick a story for MK to work on
- [x] Pair on the story with MK
- [x] Have MK do a code review of a different story to familiarize himself with the code
- [x] **Success: MK feels more comfortable coding for EZR**

**Comment by longmd** [comment]
@mkerns1 , [can you review this PR?](https://github.com/department-of-veterans-affairs/vets-website/pull/27380) to satisfy the code review for this ticket?
