### ISSUE TITLE
[FE] 10-10EZR: EZR Staggered Rollout April 11th-18th 2024

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#72312]
As a user, I would like to be able to see the online EZR and update my information so that I don't have to call the hotline or print out and mail in a form to update information.

- [x] Roll out EZR at 10% on 12/20
- [x] If 10% is successful, rollout at 25% on 1/2/24
- [x] #73111
- [x] Take Two!
- [x] 10% rollout 1/10/24
- [x] 10% Rollout again 3/5/24
- [x] Rollout EZR to 25% on April 11th alongside TERA Questions (100%)
- [x] Rollout EZR to 50% 4/12 AM (TERA will always be 100%)
- [x] Rollout EZR to 100% 4/18
- [x] **Success: Rollout of EZR with TERA Questions that ends up in a 100% rollout**

**Comment by mkerns1** [comment]
We successfully ramped up to 100% on Thursday April 18th! It was a seamless and stable rollout. This ticket can be closed now.
