### ISSUE TITLE
AWS access for [Lee Delarm]

### ISSUE THREAD

**Issue by lee-delarm6** [department-of-veterans-affairs/va.gov-team#72319]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Agile Six - Anthony M. Arashiro

### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Lee Delarm

### Your Email

lee.delarm@agile6.com

### Team, Role, and Company of the target individual

Check-In Team, Senior Software Engineer, Agile6

### Product Manager (PM) name and email

Lori Pusey, lori.pusey@agile6.com

### Product Owner (PO) name and email

Kay Laywer, katherine.lawyer@va.gov

### Desired AWS Access

I need vets-api, vets-website, and CHIP AWS access to be able to monitor and review logs, to edit and update deployments (especially around CHIP), to restart servers, and to fix and maintain production issues. I work on the Check-In team, so vets-website does not need to be all access, but CHIP lambdas probably should be, and vets-api somewhere in the middle since we control a lot of modules there

### Access Expiration

ongoing

### Additional Notes

You can contact me on slack on the Office of CTO @ VA under my name Lee Delarm, or email lee.delarm@agile6.com. Similar AWS permissions as Brian Sleek on our team would be preferable (I'm not sure how much CHIP access he has though)

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by flooose** [comment]
@lee-delarm6 two things:

1. I've removed the image of your eqip transmittal because it had your social security number in it :/
2. The image wasn't valid either. We need an screenshot/image of an email with the words "Transmittal Notice" in the subject. Submitting your eqip is a two-step process. The image that you had pasted above was confirmation that _you_ had submitted your eqip. What we're interested in though is step two, when the VA submits the document on _your behalf_ to the next part of the process.

Let us know if you have any questions.

**Comment by flooose** [comment]
I made the same mistake with my AWS access request, so I know how it feels :)

We've made a change to our issue template now, in hopes of avoiding this in the future.
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/123168/3507036a-c8d7-4f30-b457-a547503df88b)

**Comment by lee-delarm6** [comment]
I don't have an email with Transmittal Notice in the title, possibly because I went through Booz Allen? (Agile6 is/was subcontract) I have an email that shows Booz Allen has submitted my e-qip to the VA, stating the VA has all control of the process from there. Scott Mason was the one who submitted me on that. I've got other emails that say when I've been approved for VA access and things, but did a couple searches in both my VA and work emails with nothing for that headline

**Comment by lee-delarm6** [comment]
![Screenshot 2024-01-03 at 10 22 16 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/135059743/025f7345-3b40-41ee-916f-3ec84d30a949)

Here's the closest thing I've got I think. A co-worker showed me what the email should look like and I don't have that one

**Comment by flooose** [comment]
Hmm, did you have to fill out the e-qip though?

**Comment by ph-One** [comment]
@lee-delarm6 
- Logging, monitoring, and alerts are sent to and managed in Datadog
- All deployments are managed through Jenkins or GitHub Actions, there are no servers to restart as we deploy blue/green with autoscaling groups (proxies) and/or replicasets by way of Helm in Kubernetes (Vets API)
- There are very few Lambda's in our AWS, are you sure VA.gov Platform is the AWS account you need access to?

**Comment by ph-One** [comment]
@lee-delarm6 

Some resources that may be of interest & meet your ask:
- Vets API Helm Chart: https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps/vets-api
- Vets API Parent Chart: https://github.com/department-of-veterans-affairs/vets-api/tree/parent-helm-charts/chart
- GitHub Teams for accessing ArgoCD / Deployments in EKS: https://github.com/orgs/department-of-veterans-affairs/teams?query=vets-api

**Comment by patrick-black-oddball** [comment]
completed
