### ISSUE TITLE
[MVP] Step 5: Update form flow page order

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#72330]
## Issue Description
Ensure and/or update the page order for Step 5 according the list below.

Please note that some pages may be visible or hidden depending on answers to previous questions.

---
## Tasks
- [ ] Update the form flow pages/question(s) for Step 5 in this order:

1. Do you and your dependents have over $25,000 in assets?
2. Estimate the total value of your assets
3. Did you, your spouse, or your dependents transfer any assets in the last 3 calendar years?
4. Do you, your spouse, or your dependents own your home (also known as your primary residence)?
5. Is your home located on a lot of land that's more than 2 acres (or 87,120 square feet)?
6. What's the value of the land that's more than 2 acres?
7. Is the additional land marketable?
8. Do you, your spouse, or dependents receive income?
9. Add an income source (list loop)
10. Do you, your spouse, or your dependents pay recurring care expenses that aren't reimbursed?
11. Add an unreimbursed care expense (list loop)
12. Do you, your spouse, or your dependents pay medical or other expenses that aren't reimbursed?
13. Add a medical or other unreimbursed expense (list loop)

## Acceptance Criteria
- [ ] When a user starts Step 5 of the Pension form, they will experience the order of pages/question(s) in the order listed above.

**Comment by aplatt-coforma** [comment]
@ToddWebDev  @vbellissimo In testing this I found 2 issues: 
1. step #7 "Is the additional land marketable?" was never shown during my testing. Is there a conditional logic that shows that question?
2. step #13 "Add a medical or other unreimbursed expense"  was never shown then I selected Yes to the previous question of "Do you, your spouse, or your dependents pay medical or other expenses that aren't reimbursed?". 

I have 1 question about the details in this ticket. Is step #13 suppose to be a list loop similar to step #9 and 11? The ticket does not say that but I think it is suppose to be a list loop as well. 

Leaving this ticket in this design review column for your review of my above comments when you return after the holidays. Thanks!

**Comment by aplatt-coforma** [comment]
Video that shows the missing #7 "Is the additional land marketable?"

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1dFQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ae7e37141f462ac67388b2e0ec8bf04596eb32b3/Screen%20Recording%202023-12-22%20at%204.37.38%E2%80%AFPM.mov)

**Comment by aplatt-coforma** [comment]
Video showing the missing step #13 "Add a medical or other unreimbursed expense"

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2FFQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eb3e8afa585b8d23a4a4494d9f437948736f48d0/Screen%20Recording%202023-12-22%20at%204.38.56%E2%80%AFPM.mov)

**Comment by vbellissimo** [comment]
@aplatt-coforma @ToddWebDev great questions Anh and thanks for checking this.

- **step #7 "Is the additional land marketable?"**: It looks like this is still in the "review/qa" column on our board. @danlim715 worked on it and perhaps it has not made it to staging yet. See ticket #70428.
- **step #13 "Add a medical or other unreimbursed expense" was never shown then I selected Yes to the previous question of "Do you, your spouse, or your dependents pay medical or other expenses that aren't reimbursed?"**: Similar to above, it looks like this piece of the flow is still in the "in progress" column on our board. @danlim715 also worked on it and looks like it has not made it to staging yet either. See ticket #71730.
- **Is step #13 suppose to be a list loop similar to step #9 and 11? The ticket does not say that but I think it is suppose to be a list loop as well**: yes, good catch. This is also supposed to be a list loop. I just edited the body of the ticket to be sure it's clear.

**Comment by ToddWebDev** [comment]
@vbellissimo is correct. Since the tasks for 7 and 13 are not completed, they are not yet on stage. I included a note on the pull request to clarify this, however the pull request details are not visible on this zenhub issue. 

Note: These pages are not yet included
7 - Is the additional land marketable?
13 - Add a medical or other unreimbursed expense

**Comment by vbellissimo** [comment]
@ToddWebDev Just making a note here that I'm waiting for the pending pages/questions mentioned in the comment above to merge onto staging environment and show in this flow, before I officially this task.
