### ISSUE TITLE
[MVP] Step 5: Remove redundant/old pages from form flow

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#72332]
## Issue Description
We need to remove from the new Pension form flow, pages that are replaced by new pages/questions.

---
## Tasks
- [x] Remove the following pages from Step 5 of the form flow:

1. Financial information: financial/net-worth
2. Monthly income: financial/monthly-income 
3. Expected income: financial/expected-income 
4. Other expenses: financial/other-expenses 
5. Spouse net worth: financial/net-worth/spouse
6. Spouse monthly income: financial/monthly-income/spouse
7. Spouse expected income: financial/expected-income/spouse
8. Spouse other income: financial/other-expenses/spouse 
9. Dependents net worth: financial/net-worth/dependents/:index
10. Dependents monthly income: financial/monthly-income/dependents/:index 
11. Dependents expected income: financial/expected-income/dependents/:index 
12. Dependents other income: financial/other-expenses/dependents/:index 

**Screenshots of these pages found here:** https://docs.google.com/document/d/11VWC8Y8fEu2eImtb9cH73IRmoMzZbpuQuOt9EphugfM/edit?usp=sharing

## Acceptance Criteria
- [ ] Pages in Step 5 of the Pension form flow that have been replaced by new pages/questions created will be removed, so that we do not ask redundant questions to the user.

## Other Info
**Related, follow-on task for this:** [MVP] Step 5: Update form flow page order #72330

**Comment by aplatt-coforma** [comment]
Verified that these pages are indeed removed. There are some issues that are not matching the flow diagrams that Maya's has created but I'll note those in the flow testing tickets.
