### ISSUE TITLE
Flipper UI access for [Daniel Miller]

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#72338]
### Your Name

Daniel Miller

### Your GitHub handle (Flipper UI access is managed through GitHub)

 DanielMiller-agile6

### Team, Role, and Company of the target individual

Authenticated Experience My VA, full stack dev, Agile 6

### Please confirm if you are on Atlas, Platform Team Roster or are a Federal User

- [ ] [Atlas](https://dev.va.gov/atlas)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [X] Lesser Environments (Dev/Staging/Sandbox)
- [X] Production (if requesting, justify prod access below)

### Reason for Production Access (If requested)

Daniel needs this access to manage feature flags in lower and production environments

**Comment by bdech** [comment]
Found in VFS Roster

E-QIP found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/71627)

**Comment by bdech** [comment]
@DanielMiller-agile6 You've been granted access to `Production` and `Lesser` environments.
