### ISSUE TITLE
Apply card with icon component to VA in person appointment details pages

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#72349]
## Description
This adds the [appointment card with icon component](https://design.va.gov/components/card#appointment-large-with-icon) to VA in person appointment details pages. 

**Note:** the Check-in team has built this component, but it hasn't been added to storybook yet. Please discuss with them before working on this ticket. A new ticket may be needed to add the component to storybook before work starts.

## Acceptance Criteria
Background: the `va_online_scheduling_appointment_details_redesign` toggle is on

Given the user is on the details page for a [VA In-person appointment](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/feature-reference/appointment-types/va-in-person.md)
Then appointment card with icon component wraps around the page content
And the [icon](https://design.va.gov/storybook/?path=/docs/uswds-va-icon--icons) in the component is `location_city`.

Given the user is on the details page for a [VA In-person vaccine appointment](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/feature-reference/appointment-types/va-in-person-vaccine.md)
Then appointment card with icon component wraps around the page content
And the [icon](https://design.va.gov/storybook/?path=/docs/uswds-va-icon--icons) in the component is `location_city`.

Given the user is on the details page for a [claim exam appointment](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/feature-reference/appointment-types/claim-exam.md)
Then appointment card with icon component wraps around the page content
And the [icon](https://design.va.gov/storybook/?path=/docs/uswds-va-icon--icons) in the component is `location_city`.

### Design Assets

[Design spec](https://www.figma.com/file/wQy9CVKBu1yRmBWLFk05Ll/Add-Icon-Card-to-Details-Pages-%7C-Appointments-FE?type=design&node-id=1-39&mode=design).
All design spec copy is For Placement Only. This ticket only adds the appointment card with icon component.

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by JRRoof** [comment]
Blocked until Github issue [#72660](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/72660) is completed

**Comment by ldelacosta** [comment]
UX team will validate.

**Comment by Cieramaddox** [comment]
@ryanshaw [Here](https://docs.google.com/presentation/d/1JThrDl6Cj9n5N1tGmcq032BH0MwF9ETExjo6-FacFCs/edit?usp=sharing) are some of the things I noticed while validating the appt details redesign work. 
Let me know if we need to sync on some of this.

**Comment by ldelacosta** [comment]
Closing out the ticket. We will validate the end to end flow when the following tickets are done: 
- #80690
- #79086
- #79364
- #81271
- #72652
- #72653


cc: @outerpress @melissa-lefevre @Cieramaddox
