### ISSUE TITLE
Adding Olivia Capone to DSVA Slack

### ISSUE THREAD

**Issue by sstrassberg** [department-of-veterans-affairs/va.gov-team#72352]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

<describe the request>

Are you requesting to add an individual as a:

- Multi-channel

Olivia is a Booz-Allen-Hamilton contractor for VEO. She will need to be added to an upcoming research study Slack channel that hasn't been created yet.

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add olivia.capone@va.gov as a multi-channel guest.

**Comment by LEHigley** [comment]
@sstrassberg olivia is showing as a full member already--shoudl that be changed?

**Comment by sstrassberg** [comment]
@LEHigley I wouldn't change it if she already is full member.
