### ISSUE TITLE
Adding Lauren Locraft to DSVA Slack

### ISSUE THREAD

**Issue by sstrassberg** [department-of-veterans-affairs/va.gov-team#72351]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

<describe the request>

Are you requesting to add an individual as a:

- Multi-channel

Lauren is a Booz-Allen-Hamilton contractor for VEO. She will need to be added to an upcoming research study Slack channel that hasn't been created yet.

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add lauren.locraft@va.gov as a multi-channel guest.

**Comment by sstrassberg** [comment]
@LEHigley Lauren emailed me on 12/29 that she hasn't received an invite to Slack. Can you check the status?

**Comment by LEHigley** [comment]
this should be done now
