### ISSUE TITLE
Conditionalize MHV base URL to be eauth-enabled URL when SSOe cookie is present

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/va.gov-team#7237]
Various parts of vets-website link out to MHV. For MHV to accept an SSOe session, we need to link to the "standard junction" URL instead of the regular www.myhealth.va.gov URL. (The standard junction is actually an SSOe proxy URL that passes traffic on to MHV). 

The base standard junction URL for that is something like https://eauth.va.gov/mhv-portal-web/eauth (or "sqa.eauth or int.eauth for lower environments).

Looks like the MHV link outs that would represent a logged in user state are pretty well contained to a couple places:
* `src/platform/site-wide/cta-widget/helpers.js` that calculates the URL for all CTAs.
* `src/applications/validate-mhv-account/constants.js` which has a hard-coded URL for linking the user from the My Health page after doing account validation/upgrade. This could potentially be refactored to use the same mhvBaseUrl method as the CTA widget helper.

Also need to verify the paths to all the "deep links" to specific MHV features in the standard junction pattern and make sure there's no other part of the URL that needs updating per-environment.

### Acceptance Criteria:
- When a user has an SSOe session, they are linked to the MHV eauth URL, allowing them to be logged in via SSOe.
- When a user does not have an SSOe session, for the near term we can link to the regular MHV URL to preserve the "shared cookie" mechanism.

The "non-SSOe" use case should go away once we fully roll out SSOe, in which case we can probably link all signed-in users to the eauth MHV URL, but we should check with the MHV team about their desires there (in ase e.g. a user has an SSOe session but doesn't have an MHV ID, we may want different behavior).

**Comment by patrickvinograd** [comment]
For the most part the substitution is straightforward, a url like
`https://www.myhealth.va.gov/mhv-portal-web/download-my-data`
becomes
`https://eauth.va.gov/mhv-portal-web/download-my-data`

HOWEVER, it looks like deep-linking to one of those features under the eauth standard junction domain does not work unless you link to `https://eauth.va.gov/mhv-portal-web/eauth` first - i.e. it seems like that landing page establishes the MHV session from the supplied IAM headers. If you navigate straight to `download-my-data`, the user lands there but does not show as logged in. 

Put out query to MHV team. They are capable of deep linking with the MHV-VA.gov shared cookie, so it seems plausible they can fix that under the standard junction paradigm.
Alternatively (but less desirable) if they can provide a "next hop" mechanism where we link to `mhv-portal-web/eauth?next=/mhv-portal-web/download-my-data` and effect deep linking that way, we can live with that.

**Comment by patrickvinograd** [comment]
Here  is the list of all the destinations that VA.gov links to:

```
https://www.myhealth.va.gov/mhv-portal-web/home
https://www.myhealth.va.gov/mhv-portal-web/download-my-data
https://www.myhealth.va.gov/mhv-portal-web/web/myhealthevet/refill-prescriptions
https://www.myhealth.va.gov/mhv-portal-web/secure-messaging
https://www.myhealth.va.gov/mhv-portal-web/appointments
https://www.myhealth.va.gov/mhv-portal-web/web/myhealthevet/scheduling-a-va-appointment
(auto-redirects to https://www.myhealth.va.gov/mhv-portal-web/schedule-or-cancel-a-va-appointment-online)
https://www.myhealth.va.gov/mhv-portal-web/labs-tests
```

**Comment by patrickvinograd** [comment]
From Barry Egbert, MHV does support a query-param based deep-linking mechanism, and they support the following 4 targets currently:

> https://eauth.va.gov/mhv-portal-web/eauth?deeplinking=download_my_data, Redirects to web context: /web/myhealthevet/download-my-data
https://eauth.va.gov/mhv-portal-web/eauth?deeplinking=prescription_refill, Redirects to web context: /web/myhealthevet/rx-refill
https://eauth.va.gov/mhv-portal-web/eauth?deeplinking=appointments, Redirects to web context: /web/myhealthevet/appointments
https://eauth.va.gov/mhv-portal-web/eauth?deeplinking=secure_messaging, Redirects to web context: /web/myhealthevet/secure-messaging

Comparing that to what we need, it looks like we have 5 out of 6 use cases covered, with some caveats:

```
/mhv-portal-web/home ==> /mhv-portal-web/eauth
/mhv-portal-web/download-my-data ==> /mhv-portal-web/eauth?deeplinking=download_my_data
/mhv-portal-web/web/myhealthevet/refill-prescriptions ==> /mhv-portal-web/eauth?deeplinking=prescription_refill
/mhv-portal-web/secure-messaging ==> /mhv-portal-web/eauth?deeplinking=secure_messaging
/mhv-portal-web/appointments ==> /mhv-portal-web/eauth?deeplinking=appointments
* If we can live with a single appointments target vs. current distinction between "view appointments" and "schedule appointments" targets
```
The one endpoint that is not accounted for:
```
/mhv-portal-web/labs-tests ==> ???
```

Awaiting response from MHV team about whether they can add that as a deep link target. 

In the meantime, we should implement the conditional target URL mechanism in the frontend.

**Comment by hinzed1127** [comment]
moving this to blocked until we get final confirmation from the MHV team on outstanding questions, namely the "labs and testing" link

**Comment by marriej** [comment]
Removing the block. Created ticket #8447 to capture the remaining work (labs & testing). Please move forward with he rest of the work associated with this ticket.

**Comment by hinzed1127** [comment]
This has been merged. Since #8283 captures the rest of the work, closing this ticket.
