### ISSUE TITLE
[COGNITION]: Reading order SHOULD provide context between form and results

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#7239]
# [508-defect-2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)

**Feedback framework**
- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

- After entering search criteria and the Search button, focus remains on the Search button. 
- Reading order goes to the first of the search results, without any introduction to provide context. 
- There **should** be an `h2` such as  “Showing 1-10 of N results" for example before the list of result results. 

 
## Point of Contact

**VFS Point of Contact:** Jennifer

## Acceptance Criteria

- As a screen reader user, I want to understand the context of the content I am hearing.
- As a user, I want to understand the context of the content I am reading.

## Environment

* Operating System: all
* Browser: all
* Screenreading device: any
* Server destination: staging and production

## Steps to Recreate

1. Enter `https://staging.va.gov/find-locations` in browser
2. Start screenreading device listed in Environment
3. Navigate to the search field, enter parameters and select Search
4. Verify that the search results are read without any introduction

## Possible Fixes (optional)

- Add an `<h2>` before the search results, “Showing 1-10 of N results"
- Focus should move from the Search button to this heading upon onInput, as indicated in ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/7240

## WCAG or Vendor Guidance (optional)

* [W3C Understanding WCAG 2.0 - Change on Request](https://www.w3.org/TR/UNDERSTANDING-WCAG20/consistent-behavior-no-extreme-changes-context.html)

## Screenshots or Trace Logs

![Screen Shot 2020-03-25 at 5 31 15 PM](https://user-images.githubusercontent.com/57469/77660773-2100f880-6f50-11ea-9ecb-69d02b02808c.png)

**Comment by mmiddaugh** [comment]
@jenstrickland, this issue can be resolved once the focus/workflow is addressed as described in [#7240]

**Comment by mmiddaugh** [comment]
Focus has been added to the AC for [#7555](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7555)

**Comment by mmiddaugh** [comment]
@jenstrickland this is ready for validation at your convenience

**Comment by jenstrickland** [comment]
Validated 🎉
