### ISSUE TITLE
[SCREENREADER]: Upon Submit, focus MUST move to the context change notification

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#7240]
# [508-defect-1 :exclamation: Launchblocker](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-1)

**Feedback framework**
- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

- After entering search criteria and the Search button, focus remains on the Search button. 
- Upon returning search results focus **must** be on the heading indicating the search results instead of remaining on the Search button.

## Point of Contact

**VFS Point of Contact:** Jennifer

## Acceptance Criteria

As a screen reader user, I want to understand that upon submitting the form there is a context change.

## Environment

* Operating System: all
* Browser: all
* Screenreading device: all
* Server destination: staging and production

## Steps to Recreate

1. Enter `https://staging.va.gov/find-locations` in browser
2. Start screenreading device listed in Environment
3. Enter search criteria and submit the form
4. Verify that focus, as indicated by the yellow box, remains on the Search button

## Possible Fixes (optional)

Focus should move from the Search submit button to the `<h2>` indicated in ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/7239.

## WCAG or Vendor Guidance (optional)

* [W3C Understanding WCAG 2.0 - Change on Request](https://www.w3.org/TR/UNDERSTANDING-WCAG20/consistent-behavior-no-extreme-changes-context.html)

## Screenshots or Trace Logs

![Screen Shot 2020-03-26 at 11 19 58 AM](https://user-images.githubusercontent.com/57469/77663714-c2d61480-6f53-11ea-9778-00e8a8221154.png)

**Comment by mmiddaugh** [comment]
The search results subhead is currently hidden due to inaccurate results count [#6775]. This issue will be addressed when the root cause is resolved and the summary is restored.

**Comment by jenstrickland** [comment]
Would it be possible to have a temporary heading Introducing the search results, without the X–Y of Z? On submit, there's a heading that says, Search Results.

**Comment by mmiddaugh** [comment]
Focus has been added to the AC for [#7555](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7555)

**Comment by mmiddaugh** [comment]
@jenstrickland this is ready for your validation, please.

**Comment by jenstrickland** [comment]
Validated.
