### ISSUE TITLE
SME Interviews - Moderation

### ISSUE THREAD

**Issue by RenataKeck** [department-of-veterans-affairs/va.gov-team#72417]
This is a placeholder ticket for everyone moderating as part of the SME interviews study. The person assigned to this ticket is responsible for ensuring that all moderators complete the sub-tasks associated with this ticket and that documentation is properly stored. 

### Output
**Before an interview**
- [ ] Confirm SME interview questions are correct and entered into the notetaking template.

**After an interview**
- [ ] Upload recording of the interview is uploaded to Sharepoint
- [ ] Notify wider team in OCTO Slack

### Resources
- [Research Plan](https://docs.google.com/document/d/1i7SGMj0ishpbNZ1tRYY_ZKZL_I9hHiQm6JXUnwT-oT4/edit#heading=h.6bzy3gqtzk9b)
- [Note taking template](https://docs.google.com/document/d/1uq_yFBmt_Ez15346L6Qt1IbKPPU20LvIp8-FCmwU9ps/edit#heading=h.6bzy3gqtzk9b)
- [Interview status tracker](https://docs.google.com/spreadsheets/d/1YlTSzOZuwftcGDaF2aT8L-IENtgFLLl7lSvhgeHfopw/edit#gid=0)
- [Sharepoint folder](https://dvagov.sharepoint.com/sites/vaabdvro/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2Fsites%2Fvaabdvro%2FShared%20Documents%2FAccredited%20Representative%20Facing%2FResearch%2FSME%20Interviews&FolderCTID=0x01200073ECFC0A16DB51439C06C6FDC0E92947)
- [Debrief Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1703711843524/8b8d7ec4bb7297f82cf692eb1e823024bd5c6acb?sender=ua71936780d8bc9a2d2b29830)

### Acceptance criteria
- Notes for all SME interview sessions are recorded and added to the appropriate Sharepoint folder

**Comment by uxrebecca** [comment]
I moderated the first two interviews and uploaded the recordings to Sharepoint; also shared in Slack.
