### ISSUE TITLE
Veteran status info on Military Information page

### ISSUE THREAD

**Issue by matt4su** [department-of-veterans-affairs/va.gov-team#72419]
As a Veteran I want a download button and associated copy on the Military Information page so that I may trigger the download process to save my Veteran Status info locally.

Acceptance Criteria:
1. Military Information Page displays Copy with the same verbiage, style and layout as designed in Figma. https://www.figma.com/file/UwSvhj9Yn5trM5L5W3UgH0/VA-Status---Wireframes?type=design&node-id=793-4306&mode=design&t=bdVz5NHax0h4z645-4
2.  Link to print and download Veteran status card as a PDF (actual functionality in a separate ticket)
3. Mobile cross promotion component with links to the VA Health and Benefits app on the Apple App or Google Play stores.
4. Request your Military Records (DD214) component is displayed below Mobile cross promotion component.
5. Page shall meet VA accessibility standards
Note that eligibility logic for display (or not) of Veteran Status information on Military Information page is addressed in another story.

**Comment by hasahmed2** [comment]
Dev notes:
- Include an anchor 'jump-link' so when we link to the page we can have the browser scroll to the download button
- 16px font size for copy (consult style guide)
