### ISSUE TITLE
SME Interviews - Notetaking

### ISSUE THREAD

**Issue by RenataKeck** [department-of-veterans-affairs/va.gov-team#72418]
This is a placeholder ticket for everyone notetaking as part of the SME interviews activity. The person assigned to this ticket is responsible for ensuring that all notetakers complete the sub-tasks associated with this ticket and that documentation is properly stored. 

### Output
**Before an interview**
- [x] Ensure notetaker has been identified for the session
- [x] Ensure the notetaker has made a clean copy of the note taking template and has updated the header information

**After an interview**
- [x] Confirm the notetaker has cleaned up their notes and uploaded it to the appropriate Sharepoint folder

**End of study**
- [x] Confirmed all notes from the study are in the Sharepoint folder

### Resources
- [Research Plan](https://docs.google.com/document/d/1i7SGMj0ishpbNZ1tRYY_ZKZL_I9hHiQm6JXUnwT-oT4/edit#heading=h.6bzy3gqtzk9b)
- [Note taking template](https://docs.google.com/document/d/1uq_yFBmt_Ez15346L6Qt1IbKPPU20LvIp8-FCmwU9ps/edit#heading=h.6bzy3gqtzk9b)
- [Interview status tracker](https://docs.google.com/spreadsheets/d/1YlTSzOZuwftcGDaF2aT8L-IENtgFLLl7lSvhgeHfopw/edit#gid=0)
- [Sharepoint folder](https://dvagov.sharepoint.com/sites/vaabdvro/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2Fsites%2Fvaabdvro%2FShared%20Documents%2FAccredited%20Representative%20Facing%2FResearch%2FSME%20Interviews&FolderCTID=0x01200073ECFC0A16DB51439C06C6FDC0E92947)
- [Debrief Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1703711843524/8b8d7ec4bb7297f82cf692eb1e823024bd5c6acb?sender=ua71936780d8bc9a2d2b29830)

### Acceptance criteria
- Notes for all SME interview sessions are cleaned up and stored in the appropriate Sharepoint folder

**Comment by uxrebecca** [comment]
Janelle took notes in the first interview and Renata in the second. Both have been uploaded to Sharepoint. I've assigned Renata to this ticket since they are helping with many of the notetaking tasks, though this is a team effort!

**Comment by RivkaCGates** [comment]
Can we get a link to the notes?

**Comment by RenataKeck** [comment]
@RivkaCGates as soon as I have access to CAG again, I'll add the link inline and tag you.

**Comment by RivkaCGates** [comment]
@uxrebecca or @karafaithsanchez can you do this since Renata can't right yet?

**Comment by uxrebecca** [comment]
All the notes (both Sharepoint and GDrive versions) are linked from [the tracker in Google Drive](https://docs.google.com/spreadsheets/d/1YlTSzOZuwftcGDaF2aT8L-IENtgFLLl7lSvhgeHfopw/edit#gid=0).

**Comment by RivkaCGates** [comment]
Thanks - next time please make sure it's either in the ticket or in the comments. Makes it trackable.
