### ISSUE TITLE
Midpoint Review - IA Feedback - Accredited Representation Management: Appoint a Representative + Representative Status Widget MVPs

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#72421]
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- Our team has really loved working with y'all on these products - thanks for engaging with the collab cycle so actively!
- I like the legalese in the accordions, fwiw. I think it overwhelms most folks, and for people who are curious, the language is still available.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

### Must

- **Page title:** The `H1` and breadcrumb for the current page should align, and also match the first segment of the `title` tag before `| Veterans Affairs` as well.

- **Breadcrumb consistency** - On the team's find a rep product, you're using the [V3 Breadcrumb Component](https://design.va.gov/components/breadcrumbs#examples---v3) (the big difference from V1 is that the current page is linked). It would be good to be consistent and use the new component on both products.

- **Relationship to static pages/entry points:** At staging review we will need to see updates to the static pages that are entry points to this app and the Find a Rep app. How does the intro page in your sketch file relate to the [existing get help page](https://www.va.gov/disability/get-help-filing-claim/)?

### Should

- **Headings on intro screen should convey order of operations** - seconding Design and Content to recommend that the heading structure on the intro page be made more scannable, reflecting clearly that this is a multi-step form process: fill it out here, then mail it in or upload it. This could be an opportunity to mirror the [process list](https://design.va.gov/components/process-list) design pattern on the confirmation page.
  - It needs to be made very clear from scanning the headings that this form generates a filled form that then needs to be submitted.

### Consider
- **Gender on intro screens:** On the intro screens where users are confirming their information, it's displaying gender. I think this drew my eye because y'all are displaying `gender identity` instead of `gender` like most forms. Either way: is this information needed for this form, and if not, can it be removed? I am also going to follow up with the design system team about the [communicate information that is on file](https://design.va.gov/patterns/help-users-to/know-how-their-information-is-updated#communicate-information-that-is-on-file) pattern, which only says in an image caption, "The user is shown personal information that is on file **and will be used as part of the application process**." (emphasis mine)
- **Intro page - clarify current rep can be replaced:** On the [intro page](https://www.sketch.com/s/a75e9329-dae9-4984-867e-451d6e2fa836/a/r9xR7eE) it's not immediately clear from scanning that the current rep can be replaced. I think it's because the `Check your current rep` section is separated from the CTA to appoint a rep by the `Find a rep` section. I think there are a few potential solutions here:
  - Move the `Check your current accredited representative` section down inside of the `Appoint an accredited representative` section
  - Update the `Appoint an accredited representative` header to "Appoint **or replace** an accredited representative"
  - Update the CTA text as well - "Fill out your form to appoint **or replace**..."

![Screenshot 2023-12-19 at 1 37 53 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/755248/621f0f8b-1ef0-44e6-bc6c-7a7295fe5f2a)

**Comment by oddball-lindsay** [comment]
> **Relationship to static pages/entry points**: At staging review we will need to see updates to the static pages that are entry points to this app and the Find a Rep app. How does the intro page in your sketch file relate to the [existing get help page](https://www.va.gov/disability/get-help-filing-claim/)?

@erinrwhite The plan is for that existing get help page to redirect to our landing page, and the landing page will have our Rep Status Widget embedded along with links to both Find a Rep and Appoint a Rep products.  

We also plan to redirect these pages to the landing page:
1. https://www.va.gov/decision-reviews/get-help-with-review-request/
2. https://benefits.va.gov/vso/index.asp - currently identifying stakeholders to approve this redirect

-----

With this in mind, at Staging Review I'm not sure if it'd make sense to review these three pages as there won't be any updates/edits -- they'll simply be redirected to our landing page.

**Comment by erinrwhite** [comment]
I appreciate this detail @oddball-lindsay - we won't need to see those entry pages at staging review if there are no changes. It sounds like y'all are working with CAIA on redirects and updating links across the site. Thank you!
