### ISSUE TITLE
[CST] Remove EP290 claims from CST

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#72453]
## Value Statement

VA stakeholders have asked us to remove claims with this EP code because CST is not supposed to support this claim type. 

## Acceptance Criteria

- [ ] Suggest to enablement team that LH is the right team to make these changes.

**Comment by jstrothman** [comment]
Related [Slack thread](https://dsva.slack.com/archives/C04KHCT3ZMY/p1703088142183279)

**Comment by jerekshoe** [comment]
Are we the ones that should be doing this? This seems more like a LH thing to me

**Comment by jacobworrell** [comment]
@jerekshoe let's talk today in our follow up refinement session.
