### ISSUE TITLE
Midpoint Review - Design Feedback - Accredited Representation Management: Find a Representative MVP (round 2)

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#72451]
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- Great work!
- Work with content on "Flag inaccuracy " and make sure it is easily understood.
- Modals aren't always the best on mobile. Make sure you limit the content and test with the long list.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- **Should**: If you do not want to display the "how can each representative help me?" in an open card, you could separate the content into 2 additional info components. I know we discussed accordions but they do not seem to flow as well. If you break the content up you could place 2 additional info components ("How can a Veteran Service Office help me?" and "How can an attorney help me?") above the "Type of representative". By breaking the content up, you will stay within the guidelines for additional info components. That would also help with scrolling on the page. So something like this:
### Search for a representative
 How can a Veteran Service Officer help me? ⌄
How can an Attorney help me? ⌄
Type of representative (*Required)
⊙  Veterans Service Officer
⊙  Attorney

- **Should**: I do not know that users will see the alert notifying them that some information may be outdated. Since it is not relative until they have the search results, consider having it appear after the user searches, above the results but below the actual form. This will also help users to focus on 1 primary task at a time. Searching first and then notifying the VA of outdated info.
- **Should**: Per [our guidance](https://design.va.gov/components/button/#behavior), it is preferred to inly use 1 primary button on a page. If the user gets no search results, they get another primary button telling them to increase the search radius. You could try a couple of things:
  - Move the search radius option into the form itself rather than in the results.
  - Remove the Increase search radius button and instead show the search radius select box even when there are no results. Keep the text in the results body telling them to increase the search radius.
- **Consider**: The search radius has options every 50 miles, that seems like a lot and a bit overwhelming. Consider different intervals. I often see 50 miles, 100 miles, 500 miles and then all. That can make it easier to choose.

**Comment by oddball-lindsay** [comment]
@allison0034 can you share more about why you recommend this particular placement?  I like the additional component concept, but in my mind it makes sense to keep these components connected to the radio options. Something like:

> Type of representative (*Required)
> ⊙ Veterans Service Officer
> How can a Veteran Service Officer help me? ⌄
> ⊙ Attorney
> How can an Attorney help me? ⌄

**Comment by oddball-lindsay** [comment]
Ah just saw Brian's comment in https://github.com/department-of-veterans-affairs/va.gov-team/issues/72555 which answers my question :)

>The goal is to give users the chance to encounter that context before making their choice, instead of making their choice and then having to backtrack.
