### ISSUE TITLE
[DDL] BE: Log letter types downloaded to DataDog

### ISSUE THREAD

**Issue by samcoforma** [department-of-veterans-affairs/va.gov-team#72469]
## Issue Description
We want to modify DDL vets-api endpoint to include letter type number in URL for logging purposes.
## Back end tasks
- Modify DDL download route to accept letter doctype as part of its path
- Experiment with using a query parameter for this

## Questions and Assumptions to confirm
- [ ] GA (dependent) ticket depends on changing the URL 
- [ ] Is GA able to track using the new URL structure in the way we want?

## Acceptance Criteria
- [ ] URL logged to DataDog contains letter doctype number
- [ ] Unit tests pass
- [ ] Should be searchable in DataDog using this pattern: _/v0/claim_letters/184\:*_

**Comment by jerekshoe** [comment]
> - [ ] Should be searchable in DataDog using this pattern: _/v0/claim_letters/184\:*_
Changed this acceptance criteria to this:
- [ ] Should be searchable in DataDog via @payload.parameters.document_type
