### ISSUE TITLE
[Reps][21-22] Usability test - Notetaking

### ISSUE THREAD

**Issue by RenataKeck** [department-of-veterans-affairs/va.gov-team#72475]
This is a placeholder ticket for everyone notetaking as part of the ARM user testing activity. The person assigned to this ticket is responsible for ensuring that all notetakers complete the sub-tasks associated with this ticket and that documentation is properly stored. 

### Output
**Before a test session**
- [ ] Ensure notetaker has been identified for the session
- [ ] Ensure the notetaker has made a clean copy of the note taking template and has updated the header information

**After an interview**
- [ ] Confirm the notetaker has cleaned up their notes and uploaded it to the appropriate Sharepoint folder

**End of study**
- [ ] Confirmed all notes from the study are in the Sharepoint folder

### Resources
- [Research Plan](link)
- [Note taking template](link)
- [Sharepoint folder] (link TBD)

### Acceptance criteria
- Notes for all user test session notes are cleaned up and stored in the appropriate Sharepoint folder

**Comment by karafaithsanchez** [comment]
We didn't end up doing this work in partnership with ARM. If there is assistance needed from us in the future, we will create a new ticket. Closing for now.
