### ISSUE TITLE
[QA] 10-10EZR V2: Create Test cases for EC/NoK

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#72470]
- [x] Meet with UX and walk through designs
- [x] Meet with BE to understand how data works
- [x] Write initial test cases/outline/use cases 

**Note** 1/3/2024 Split ticket since we will be blocked for an unknown amount of time.  New ticket #72844

**Comment by fbonds** [comment]
Met w/ Hieu for UX discussed design and logic path
https://www.figma.com/file/tggcJk382w9yQ0ElwKfh3N/10-10EZR?type=design&node-id=0-11540&mode=design

**Comment by fbonds** [comment]
NoK/EC use cases draft document created in github.  (actual editing occurring offline, will update when complete)
https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-1010EZR-next-of-kin-emergency-contact.md

**Comment by fbonds** [comment]
Completed use cases, created test cases/test run in TestRail (documented in Use Cases).  

@alexseelig I used Original brief link for product outline.  Per Heather we need an initiative brief when you're back.

**Comment by hdjustice** [comment]
Note 1/3/2024 Split ticket since we will be blocked for an unknown amount of time. New ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/72844
