### ISSUE TITLE
Investigate MCP controller incident on 2023-12-20 

### ISSUE THREAD

**Issue by kjsuarez** [department-of-veterans-affairs/va.gov-team#72477]
An incident was triggered by one of our controller monitors do to a spike in error responses from our MCP controller. Impact appears minimal but we should conduct further monitor manually to make sure the error is not persistent.

https://vagov.ddog-gov.com/incidents/103/timeline

**Comment by HeatherRienks** [comment]
No following incidents per @kjsuarez
