### ISSUE TITLE
[BE] 1010EZR: Discovery: How does EC/NoK data behave in ES?

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#72487]
- [x] Figure out if there is a way to test EC/NoK in VES without a frontend
- [x] See if we can edit test users to send EC/NoK
- [ ] See if there are any other teams pulling this data (Health Appointment?)
- [x] Talk to Faulkner
- [ ] **Success: We determine if there is a way to figure out how EC/NoK behaves in VES without a frontend**

**Comment by JoshingYou1** [comment]
As of 12/29/23, Nok/EC data is not being accepted by ES. A ticket has been created by Josh F. to hopefully resolve the issue
