### ISSUE TITLE
Manual review check can be avoided

### ISSUE THREAD

**Issue by bkjohnson** [department-of-veterans-affairs/va.gov-team#7248]
## What happened?

A PR in `vets-website` can be made in a way that will prevent the manual review automated check from scanning it.

## Steps to Reproduce
- Make commits to a local branch that include changes which should trigger a manual review, i.e. disabling ESlint
- Push the branch up
- Without pushing any more commits, open a PR
- Notice that the check runs for the branch, but not the PR

## Desired behavior
Each PR should have the manual review automated check run over the actual changed code before a PR can be merged.

## Acceptance Criteria
- [ ] Every PR must have the manual review check run before it is merged

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by rianfowler** [comment]
is this still an issue @bkjohnson

**Comment by timwright12** [comment]
Seems like this is not triggering on draft PRs

**Comment by bkjohnson** [comment]
Yes - it's still an issue as far as I'm aware.

**Comment by timwright12** [comment]
Ran some tests in content-build with GHA, based on the information below it seems like the github actions release will fix this issue.

Testing with Github Actions in content-build

**Scenario 1:**
Open PR with linting disabled

**Result 1:**
Manual check ran
Issue reported into the UI

**Scenario 2:**
Made update in an open PR that disables linting

**Result 2:**
Manual check ran
Issue reported into the UI

**Scenario 3:**
Open Draft PR with lint disabled

**Result 3:**
Manual check ran
Issue reported into the UI

**Scenario 4:**
Made update in an open Draft PR that disables linting

**Result 4:**
Manual check ran
Issue reported into the UI

**Comment by timwright12** [comment]
Doesn't appear to be a problem anymore since we released github actions. Closing this one out https://github.com/department-of-veterans-affairs/vets-website/commit/a9b9f4ae3eec8c730df00263692028f8706c9819
