### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#72482]
### Name

Kanchanadevi Suriyamoorthy

### Email

ksuriyamoorthy@kindsys.us

### Role

Developer

### Team

Check In Experience Team

### Product Manager (PM) name

Lori Pusey

**Comment by naomimarcussen** [comment]
Invite has been sent.

**Comment by kanchanasuriya** [comment]
Thank you for the invite.  I have access now.
