### ISSUE TITLE
Create designs for Step 4 form flow

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#72496]
## Issue Description
As a Pension team,
we need designs for Step 4 of the form flow and pages of the Pension MVP relaunch,
so that we can use as a reference amongst our team and to provide to the Platform team for staging review.

---
## Tasks
- [x] Create designs for a holistic view of the form flow and pages for Step 4 of the Pension form. For the marriage information, leverage [what we've documented in this Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1697736525149/26590ab628618a5e2b86232397286eab8e7f8a1d?wid=29-1703173367057).

## Acceptance Criteria
- We will have high-fidelity designs of the form flow and pages for Step 4 of the Pension form.

**Comment by mayacoforma** [comment]
@vbellissimo Hi Vicky, we have mockups and prototypes available for step 4. Is this task a duplicate or could it be archieved?

**Comment by vbellissimo** [comment]
Hi @mayacoforma I don't think you have another card for the same thing on the board. Can you move this card to the appropriate column? Probably the "completed in sprint" column.

**Comment by mayacoforma** [comment]
@vbellissimo 

Here's the prototype for step 4: https://sketch.com/s/2d7a1c64-78f0-4454-bb7d-0c5e08f5cced/a/zy3y3yo/play

Movinf this to 'completed in sprint'
