### ISSUE TITLE
[EPIC] Outreach and Events 508 Audit

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#725]
This will be the epic we use to house all findings from the Outreach and Events 508 audit.

Original issue ticket: https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/issues/31#event-2489511649

/cc @peterhill-oddball

**Comment by peterhill-oddball** [comment]
@1Copenut 
- Completed Axe analysis of page and discovered one issue.
- Completed traversal of page with keyboard.

**Comment by laflannery** [comment]
Closing as there are no issues attached to this epic

**Comment by laflannery** [comment]
@FranECross I accidently moved this in our board but now that I opened it, are we able to close it, I don't see any open tickets in here?

**Comment by FranECross** [comment]
@laflannery Agree! Closing.
