### ISSUE TITLE
Replace deprecated `iconv` library

### ISSUE THREAD

**Issue by johnpaulashenfelter** [department-of-veterans-affairs/va.gov-team#7250]
Task:
Replace deprecated `iconv` with `ActiveSupport::Inflector.transliterate()`

Background:
As part of the CircleCi migration, an issue came up with the `iconv` library and the default service `LANG` environment variable. While its straightforward enough to solve (ensure `LANG=en-us.UTF-8` is set on the server), it demonstrates clearly that there's some non-application configuration and cross-platform issues that can be surprising. (cf https://makandracards.com/makandra/9483-normalize-characters-in-ruby)

The iconv library is only used in `app/workers/education_form/forms/base.rb` and the failing specs were `spec/jobs/education_form/forms/va1990_spec.rb` and ``spec/jobs/education_form/forms/va5490_spec.rb`

A quick attempt to use the ActiveSupport transliterate() found that the defaults in ActiveSupport do *not* completely cover the use cases in our test suite. These tests are old, the authors have moved to other projects so there's not a ton of history but it looks like a large portion of the specs look for handling Microsoft quote/apostrophe character conversions properly, which should be able to be handled in the in18n transliteration configuration per the makandracard article

```
de:
  i18n:
    transliterate:
      rule:
        Ä: 'Ae'
        Ö: 'Oe'
```

The `iconv` library was removed in Ruby 1.9.3, so between that deprecated dependency and the locale/env specific variation in underlying iconv implementations, moving to a more portable, and Rails-y solution makes sense.

**Comment by erluti** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/4460

**Comment by erluti** [comment]
Merged PR, no longer using iconv.  Potentially will have to revisit transliteration if the form consumers find issues.
