### ISSUE TITLE
[FE] My VA: Write FE unit test for personalization/dashboard/tests/helpers

### ISSUE THREAD

**Issue by allisonlu** [department-of-veterans-affairs/va.gov-team#72514]
## Background
After completing an audit of FE unit tests on My VA, we found several that were missing. This ticket is to address unit tests for `personalization/dashboard/tests/helpers.js`

## Coverage (12/21/2023)
![Screenshot 2023-12-21 at 2 55 55 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8542413/4517f762-5110-449c-b63e-8086e040223a)
![Screenshot 2023-12-21 at 2 56 09 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8542413/1257fb07-5613-4e40-b60d-ce86da999ba3)

## Tasks
- [ ] Write FE unit test for `helpers.js`

## Acceptance Criteria
- Unit tests are written and running 
- `/tests/` has >80% coverage

## Resources
- FE unit tests audit: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/QA/fe-unit-test-audit.md

**Comment by allisonlu** [comment]
@ajakabcin 

keeping this as 2 points for sprint 29

**Comment by allisonlu** [comment]
@adamwhitlock1 @DanielMiller-agile6 

can you help me validate? 🎷🦜

(although i may delete this function soon)

1. run `yarn test:coverage --app-folder personalization/dashboard --coverage-html`
2. navigate to `/vets-website/coverage/dashboard/tests/helpers/index.html`
3. confirm that you see the following: 
![Screenshot 2024-02-14 at 11 44 16 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8542413/f0fa2559-dc79-42ab-b806-6b67d65212c2)

**Comment by adamwhitlock1** [comment]
![Screenshot 2024-02-14 at 10 01 20 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8332986/e78c8f3a-d846-489a-a667-24c714915a15)

Validated.

I would totally be okay if we deleted that `shouldMockApiRequest` function 💚
