### ISSUE TITLE
Access for Jordana Mello

### ISSUE THREAD

**Issue by jordanamello** [department-of-veterans-affairs/va.gov-team#7251]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your name.
   > Jordana Mello
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VFS-CMS, Agile Six Applications, Inc
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa  AAAAB3NzaC1yc2EAAAADAQABAAABAQC/CJhJFxUtNxdVJGpaGDvVl40gjI5GV4q04vQBpjWtkK3De9e6a3cNcwnHoDQry7l9oiGUYGDRJ4OukGUK76NItAm+kox1bdnultkS9AO+5kmleNNsA/fR2mYkrsGXYHbVXVxFuAQzJOuO3UjdoEBOamcyCzaTlV0ecsfVC+qM6hG4OkAryxLtyZem1AE58pd0kzkPHfkJrA7oeoXy/ibLKuj+FZbhpZvcPduzWn4D1CyQPpNn8O/JW1PuPrRGW0O+vqmCs4fFOo80g2HC0dovOqKjC/0TWouqlqSMfRfHXYuV0RxtaFhewuSxmCXshZfY3nMLGkmIbcRTFCu8qrTL jordana.mello@Agile6.com
```

- [Grant AWS Console access?]
  > NO
  >  Please give a brief description for why you are requesting AWS access.

**Comment by jbritt1** [comment]
SOCKS access granted. @jordanamello, please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.
