### ISSUE TITLE
Midpoint Review - IA Feedback - Accredited Representation Management: Find a Representative MVP (round 2 of 2)

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#72513]
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- I really appreciate your team's work! Thanks for bringing me a search interface to review - that's a nice holiday gift for an IA.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

### Must

- **Clarify heading structure on the intro page** - this is the same as my [feedback from the Appoint a rep midpoint this week](https://github.com/department-of-veterans-affairs/va.gov-team/issues/72421#:~:text=Headings%20on%20intro%20screen%20should%20convey%20order%20of%20operations). Sounds like this will be addressed with the newest content from CAIA!
- **Breadcrumbs** - a previous iteration of this design used the [V3 breadcrumb component](https://design.va.gov/components/breadcrumbs#examples---v3); please standardize which breadcrumb component is used across both components (Find and Appoint) of the ARM app.

### Should

- **"Flag inconsistency" link** - I agree with the Content feedback that this link/button text should match the language used on the rest of the page. "Flag issue" seems good!
- **Visibility of search results section**: When reviewing the mobile prototype it was not immediately obvious to me once I clicked search that there were results showing below. I think there are a couple of ways to mitigate this:
  - Scroll the viewport and move focus down to the search results section
  - Adding a heading tag at the top of the search results section (could just be an h2/h3 that says "Search results"). This change would help with scannability and comprehension on all viewports, not just mobile.
- **Null results - show filters if possible**: Thank you for including the null results view! I think it would be helpful to display the search radius and sort dropdowns every time after running a search, including when there are null results. This creates continuity and also allows the user a more fine grained way to expand the search when they have zero results.
- **Null results "Increase search radius" button**: I agree this button is not _quite_ the solution, but it's almost there! If there is a way to auto-expand the search to find the nearest results, and notify the user that the radius has been expanded, that could be helpful. I like the idea of giving users a one-tap option for expanding results - so if it's not this button, maybe it's an action link that says "Search within 100 miles" "Search within 200 miles" etc.

### Consider

- **Placement of blue info box**: - I agree it'd make sense to place this info box further down the page closer to search results.
- **Search radius dropdown values**: - Thank you for showing the dropdowns for the search radius distances! If there is any wiggle room, it might be useful to include numbers smaller than 50, and remove some of the more specific values that are over 200. For users living in more urban spaces, they might want values less than 50 (10, 25?) and for very rural users, it might not matter whether the search radius is 200 miles, 250 miles, or 300 miles - instead, needing to specify that level of fidelity might be frustrating. Attaching some samples below:

**WebMD doctor search**
![Screenshot 2023-12-21 at 1 28 34 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/755248/f43f79dc-19b4-4042-863b-cd30d0417761)

**Warby Parker**
![Screenshot 2023-12-21 at 2 48 53 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/755248/a6474811-1080-4d7d-9588-fb6f7a83292e)

**Comment by oddball-lindsay** [comment]
> Breadcrumbs - a previous iteration of this design used the [V3 breadcrumb component](https://design.va.gov/components/breadcrumbs#examples---v3); please standardize which breadcrumb component is used across both components (Find and Appoint) of the ARM app.

Looks like [Staging](https://staging.va.gov/get-help-from-accredited-representative/find-rep/?address=oakland%2C%20ca&lat=37.804456&long=-122.271356&page=5&per_page=10&sort=distance_asc&type=attorney&name) has v3, so this is for the design file only.
