### ISSUE TITLE
Analytics New KPI dashboard request & KPI dashboard update request for [Profile]

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#72519]
# Request a New Standardized KPI Dashboard or an Update to an Existing Dashboard
## What this form is for

Use this ticket template to request a new standardized KPI dashboard or an update to an existing KPI dashboard on Domo for your product. 

**Tell us what you need done:**
- [ ] [New Dashboards](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/analytics-request-kpi-dashboard.md#for-new-dashboards)
- [x] [Updates to Existing Dashboards](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/analytics-request-kpi-dashboard.md#for-updates-to-existing-dashboards)

Standardized dashboards are currently available for [Forms](https://va-gov.domo.com/page/447193050?userId=853813555), [Content](https://va-gov.domo.com/page/426422632), & [Search](https://va-gov.domo.com/page/1964748112) products only. To see if you should request a standardized dashboard, check [Should I request a standardized KPI dashboard](https://docs.google.com/presentation/d/16mRcslbkWtW44rlsfQGXZnHtQ3GoLjn6GpFnd3Gvva8/edit#slide=id.p). If you’re not sure which dashboard(s) your product(s) qualify for, check the [Eligibility Dashboard](https://va-gov.domo.com/page/1550814739).

If your VA.gov product is not eligible for a standardized dashboard, you may be able to request an “edge case” dashboard. Please reach out to the Platform Analytics & Insights team on #vfs-platform-support for more information on this process.

### Expected delivery timelines

The Analytics team will notify you once this ticket has been pulled into a sprint. 

## For New Dashboards

In order to pull the correct data for your product, we need your help to define what pages and events to include, in addition to basic product info. We’ll need a filled out [KPI request template](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit#gid=981224988) before we can pull this ticket into our sprint.

- [ ] Make a copy of the [Google Sheet](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit#gid=981224988)
- [ ] Complete worksheet as instructed
- [ ] Link your completed spreadsheet here: ______
- [ ] Check your sharing settings to make sure the Analytics team will be able to access it
- [ ] **Add your team label to follow progress**

## For Updates to Existing Dashboards 

First, tell us what type of change you need to make:

- [ ] Change basic product info
- [ ] **Forms**: funnel changes
- [ ] **Content**: Add or remove pages included
- [x] Other 
 
### could you help us add the survey results to the profile domo dashboard? hoping to have the same thing that we have on the MyVA dashboard added to the Profile Board - ideally this should be broken down by each page of the profile. 

Next, use the original [KPI request template](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit#gid=981224988) you filled out to update your information. If you are not able to find that spreadsheet, reach out to the Analytics team on #vfs-platform-support for a new spreadsheet that reflects what we currently have on file.

**If you cannot locate your original worksheet you can create a new one:**
- [ ] Make a copy of the [Google Sheet](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit#gid=981224988)
- [ ] Complete worksheet as instructed
- [ ] Link your completed spreadsheet here: ______
- [ ] Check your sharing settings to make sure the Analytics team will be able to access it
- [ ] **Add your team label to follow progress**

**Additional Info For Both Options**

- Please use the [KPI Framework](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/Analytics%20Playbook/va-gov-platform-analytics-kpi-framework.pdf) for more information on the metrics used in the Standard KPI dashboards. 
- If you need any analytics support, read through the [How to request Analytics support](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guidelines.1586823275.html#Analyticscustomersupportguidelines-4.RequestaKPIDashboardinDomo).
- If you do not have Domo access, please [request access here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+access-request&template=analytics-request-google-analytics-domo-access.md&title=Request+access+to+Google+Analytics+and%2For+Domo).

**Comment by mtcA6** [comment]
cc: @Samara-Strauss chatted w/Michelle during office hours and she said she can make the survey magic appear on our dashboard similar to the MyVA dashboard.

**Comment by Samara-Strauss** [comment]
Idk if you all talked about this, but it would be helpful to see scores by page for the profile. Historically, I know direct deposit has had strong feedback, so I'd like to be able to differentiate between high and low performing tools.

**Comment by mtcA6** [comment]
> Idk if you all talked about this, but it would be helpful to see scores by page for the profile. Historically, I know direct deposit has had strong feedback, so I'd like to be able to differentiate between high and low performing tools.

no I did not, knew there was something I was forgetting.

**Comment by michelle-dooley** [comment]
@Samara-Strauss and @mtcA6 we will add this to our current sprint and reach out with any questions.

**Comment by michelle-dooley** [comment]
@mtcA6 and @Samara-Strauss - the survey cards have been added to the Profile dashboard as requested.

**Comment by Samara-Strauss** [comment]
Hey @michelle-dooley, I have some questions:

1. Are these intercept or feedback survey results?
2. For which profile URLs do these results apply? There are multiple profile URLs (below), and I'd like to be able to see survey results by tool.
  - `/profile`
  - `/profile/personal-information`
  - `/profile/contact-information`
  - `/profile/military-information`
  - `/profile/direct-deposit`
  - `/profile/notifications`
  - `/profile/account-security`

**Comment by michelle-dooley** [comment]
Hey @Samara-Strauss 

1. This is the intercept survey same as what is reported on MyVA dashboard. We can add a cards though for Feedback survey too.
2. This is for all pages under /profile/. We can create a table that breaks it out by page if you like, apologize for missing that part.
3. Also wanted to mention the [CSAT dashboard](https://va-gov.domo.com/page/1545882322) we have been working on with Dave. If you filter 'Directory' to profile you can see break out by page that may be of interest. There is also a section toward the bottom with Feedback survey responses.

**Comment by Samara-Strauss** [comment]
>This is the intercept survey same as what is reported on MyVA dashboard. We can add a cards though for Feedback survey too.

For the profile, the feedback survey is much more helpful. Could you please add that?

> We can create a table that breaks it out by page if you like, apologize for missing that part.

Yes, please! And thank you.

> Also wanted to mention the [CSAT dashboard](https://va-gov.domo.com/page/1545882322) we have been working on with Dave. If you filter 'Directory' to profile you can see break out by page that may be of interest. There is also a section toward the bottom with Feedback survey responses.

Thank you for letting me know!

**Comment by johnny-jesensky-adhoc** [comment]
Hi @Samara-Strauss, we've gone ahead and added the requested table at the bottom of the dashboard for the Feedback survey. Please let us know if you have any questions, or need additional assistance from our team. Thanks!

FYI @ChristineYoungZA

**Comment by Samara-Strauss** [comment]
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/34068740/e2be1a95-ce53-412e-b416-e3872eafea99)

Thank you!! This is perfect and exactly what we need. To confirm -- is this Feedback survey scores?

**Comment by johnny-jesensky-adhoc** [comment]
Hi @Samara-Strauss, that is correct. This table pulls from Medallia data!

FYI @Blivaditis, @ChristineYoungZA
