### ISSUE TITLE
SOCKS access for Jeff Schmidt

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-team#72524]
### Your Name

Jeff Schmidt

### Your Email

Jeff.Schmidt@civicactions.com

### Your Role and Team

Devops Engineer, Accelerated Publishing Team

### Product Manager (PM) name and email

Tim Cosgrove, tim.cosgrove@agile6.com

### Product Owner (PO) name and email

Erika Washburn, Erika.Washburn@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPHL68TrmInfBCLkWkZaRWGIwNa4JNNj3Trd/aceMlbo jeff.schmidt@civicactions.com

### E-QIP Transmittal Confirmation

Scott Mason confirmed that the VA is accepting my prior clearance from 06/03/2022:
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/95797077/f68bec3e-e4b9-44da-98ad-18908774e675)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by jschmidt-civicactions** [comment]
I'm not sure if this ticket is monitored but I think I needed to provide a different ssh key for SOCKS access.
