### ISSUE TITLE
AWS access for Jeff Schmidt

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-team#72526]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Other - please specify in 'Additional Notes'

### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Jeff Schmidt

### Your Email

Jeff.Schmidt@civicactions.com

### Team, Role, and Company of the target individual

Accelerated Publishing, Devops Engineer, CivicActions

### Product Manager (PM) name and email

Tim Cosgrove, tim.cosgrove@agile6.com

### Product Owner (PO) name and email

Erika Washburn, erika.washburn@va.gov

### Desired AWS Access

Jeff will need to
* create new S3 buckets and manage existing ones
* manage EC2 instances and ASGs for same
* add items to param store
* apply changes via Terraform

His permissions should match Tanner Heffner and Tim Cosgrove, both also on Accelerated Publishing team.

### Access Expiration

April 30, 2024

### E-QIP Transmittal Confirmation

Scott Mason confirmed that the VA is accepting my prior clearance from 06/03/2022:
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/95797077/13bcd81e-aaee-4b4a-809c-6e1e532b28ff)

### Additional Notes

Jeff's onboarding representative is Scott Mason, Booz Allen Hamilton. mason_scott@bah.com

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [ ] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by flooose** [comment]
@jschmidt-civicactions is requesting admin access, so I'm adding "Awaiting Approval"

**Comment by flooose** [comment]
User found in Atlas (formerly VFS Team Roster)

**Comment by EWashb** [comment]
@flooose can we get an update on this request?

**Comment by flooose** [comment]
@EWashb it's awaiting approval. I've rotated off of support, but @patrick-black-oddball should be able to complete it, once he's approved.

**Comment by EWashb** [comment]
thanks @flooose the rotations go by quickly. I appreciate you!

**Comment by flooose** [comment]
No Problem :)

BTW, I did just add the "Awaiting Approval" label. Somehow I missed that the other day 🙈

**Comment by jschmidt-civicactions** [comment]
Thanks @flooose, how long will the approval for @patrick-black-oddball take?

**Comment by patrick-black-oddball** [comment]
@department-of-veterans-affairs/operations-aws-approvers - just tagging the group that approves these tickets. Will be able to complete after this approval happens

**Comment by olivereri** [comment]
Possibly @JonathanKamensDVA ? That group only as one user and it's @mchelen who isn't on the Platform anymore. We're going round in circles here.

**Comment by JonathanKamensDVA** [comment]
This is approved.
Just a reminder that prod access for devops engineers doesn't require approval from govt side. See current policy at https://vfs.atlassian.net/l/cp/3PWXmtke .

**Comment by patrick-black-oddball** [comment]
Completed
