### ISSUE TITLE
Adding Bryan Alexander to DSVA Slack

### ISSUE THREAD

**Issue by dhill802** [department-of-veterans-affairs/va.gov-team#72539]
# Description

Please add Bryan Alexander new Ad Hoc Full Stack engineer on IVC Forms (CHAMPVA) team to DSVA Slack as a Full Member.
[bryan.alexander@adhocteam.us](mailto:bryan.alexander@adhocteam.us)

Bryan should be added to #vfs-all-teams, #vfs-change-announcements and any other pertinent Engineering and VFS general channels for new team members.

**Comment by dhill802** [comment]
FYI - @eunicegar, @pshahVA

**Comment by pshahVA** [comment]
I took care of it.
