### ISSUE TITLE
[spike] NOD | Review page disagreement duplicating

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#72542]
## What happened? 

**Describe what went wrong**: 

On Review and Submit page, when there's more than one disagreement... typing into the Something Else field for the second disagreement triggered a duplication of the first disagreement.

**Add the steps to reproduce the bug**:
This bug may be inconsistent. I was able to replicate it 3 times.
1. Add 2 issues and disagreements
2. Hit review and submit page
3. Click edit on the first disagreement (this is buggy, another ticket opened for it)
4. Remove selection (get error)
5. Click edit on the second disagreement
6. Type something in the 'something else' field
7. First disagreement starts to duplicate with every keystroke

**Add a screen recording or photo**:

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlNEQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cb041f2207423b0cd2216171ee988a362a7f3d60/disagreement-duplication.mp4)

## How severe is the problem?
- [ ] **Critical**: User is block or significantly hindered from submitting the form, data is lost, or claim and evidence test coverage is missing. Fix ASAP. 
- [x] **Moderate**: User is not blocked, but the happy path is interrupted. Fix after critical bugs.
- [ ] **Minor**: Cosmetic bugs and minor language inconsistencies. Defer to a later sprint. 

## What is the desired behavior?

1. When a user does makes edits to the disagreements on the review page, the **visual** result is to have the data updated for review and submit.

## Definition of Done

- [ ] Acceptance criteria reviewed and approved by product or design
- [ ] Unit test (or other test coverage) added if possible
- [ ] Logging and monitoring in place

**Comment by saderagsdale** [comment]
@eileen-coforma will check if this is still happening

**Comment by eileen-coforma** [comment]
@Mottie Bad news, it's still happening. Followed the exact steps and was able to duplicate.

**Comment by Mottie** [comment]
Good news! I was a much more simple fix than I thought. I'll have a PR open today!

**Comment by eileen-coforma** [comment]
Validated during parking lot
