### ISSUE TITLE
NOD | Board review error message inconsistent

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#72543]
## What happened? 

**Describe what went wrong**: 
There are two different error messages for the same error.

When a user doesn't select a board review option, on the board review option pages it shows:  Choose a Board review option to proceed

If a user somehow reaches the review and submit page, and the board review option is not select, upon edit, it shows inline error: Please select a valid option

If you hit back to get to the board review option and try to continue without a selection, it displays: Please select a valid option

The second error message is ambiguous and inconsistent.

**Add the steps to reproduce the bug**:
1. Reach review and submit page
2. Using save-in-progress menu, remove value in "boardReviewOption"
3. Replace
4. Reload Save in progress page
5. Continue your request
6. Open Board review option accordion
7. Hit edit
8. Try to update page
9. Click back
10. Click continue without selecting an option

**Add a screen recording or photo**:

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnlDQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--10b7bdc375646ebceaf727c8ab8a627684eea159/2023-12-22%2010-25-31.mp4)

## How severe is the problem?
- [ ] **Critical**: User is block or significantly hindered from submitting the form, data is lost, or claim and evidence test coverage is missing. Fix ASAP. 
- [ ] **Moderate**: User is not blocked, but the happy path is interrupted. Fix after critical bugs.
- [x] **Minor**: Cosmetic bugs and minor language inconsistencies. Defer to a later sprint. 

## What is the desired behavior?

1. _When a user does fails to select a board review option, the **visual** result is to show an error message that's direct and consistent no matter where they are in the form: Choose a Board review option to proceed._
2. _When a user does X, the **backend** result is y._
3. _When a user does X, the **event logging** result is y._

## Definition of Done

- [ ] Acceptance criteria reviewed and approved by product or design
- [ ] Unit test (or other test coverage) added if possible
- [ ] Logging and monitoring in place

**Comment by rocio-desantiago** [comment]
It is not possible for a user to deselect a radio button on any browser.
This bug is only possible by using the `save-in-progress` menu which is not available to Veterans while filling out the form.
For that reason, I think we can close this.

**Comment by HeatherWidmont** [comment]
To discuss with @eileen-coforma in the parking lot when she returns

**Comment by HeatherWidmont** [comment]
@rubensun will review to gain context & see if he can support

**Comment by rubensun** [comment]
@rocio-desantiago, I'm following your logic. I cannot recreate the bug without access to the `save-in-progress` menu.
That said, I wonder where this copy resides and why it provides a generic response. If we have extra capacity, it might be worth investigating. 

For now, I would agree — we can probably close this.

**Comment by rubensun** [comment]
via @rocio-desantiago - generic error message generated from platform code, typically this would be overridden on our end.
