### ISSUE TITLE
NOD | Redirect when restarting the form

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#72540]
## What happened? 

**Describe what went wrong**: 
When a user gets past the extension page, and decides to restart the form using 'finish this form later' link and 'start new request' it redirects to the 'request an extension' page, instead of restarting the form. If the user proceeds with the form, they'll get errors in the review and submit page. The veteran information is missing.

**Add the steps to reproduce the bug**:
1. Proceed with the form as normal, reach the review and submit page
2. Click "finish this request later'
3. Click 'start a new request'
4. Click 'yes' on the starting over modal
5. Get redirected to the 'request an extension' page with the alert.

**Add a screen recording or photo**:

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzZDQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--10c8d51229949d1659365204d78c06a9b9a1cb28/2023-12-22%2010-31-30.mp4)

## How severe is the problem?
- [x] **Critical**: User is block or significantly hindered from submitting the form, data is lost, or claim and evidence test coverage is missing. Fix ASAP. 
- [ ] **Moderate**: User is not blocked, but the happy path is interrupted. Fix after critical bugs.
- [ ] **Minor**: Cosmetic bugs and minor language inconsistencies. Defer to a later sprint. 

## What is the desired behavior?

1. _When a user does tries to start a new form, the **visual** result is form data is erased and the user starts at the beginning of the form._
2. _When a user does X, the **backend** result is y._
3. _When a user does X, the **event logging** result is y._

## Definition of Done

- [ ] Acceptance criteria reviewed and approved by product or design
- [ ] Unit test (or other test coverage) added if possible
- [ ] Logging and monitoring in place

**Comment by HeatherWidmont** [comment]
@Mottie will finish with the final PR today

**Comment by HeatherWidmont** [comment]
There were issues with GitHub this morning so there was a slight delay. @anniebtran will review this today

**Comment by HeatherWidmont** [comment]
@eileen-coforma will test tomorrow & the team will test in the parking lot when its available in staging

**Comment by Mottie** [comment]
The fix is now available in staging for testing.

**Comment by eileen-coforma** [comment]
Tested with User 233 (Cara) on Safari, and error is still happening.

**Test steps**
1. Start form from My VA (form starts on choose a board review option)
2. Reach review and submit
3. Click finish this request later
4. Click start new form
5. Get redirected to 'Request an Extension'

@Mottie

**Comment by HeatherWidmont** [comment]
Team will review together in the parking lot today

**Comment by Mottie** [comment]
Moving this ticket back to in progress

**Comment by eileen-coforma** [comment]
Validated on Safari with user 233 (Cara). Bug has been fixed.

What's happening:
- Proceed through form
- Reach review and submit
- Finish this request later
- Start new request
- Brought back to first page of the form with information cleared

@Mottie Is there a way to validate that the redirect and alert still works as intended for SIP forms started before the update, and past the extension page?

**Comment by HeatherWidmont** [comment]
Will review in parking lot tomorrow
