### ISSUE TITLE
Vets-api terminal access for Drew Fisher

### ISSUE THREAD

**Issue by cilestin** [department-of-veterans-affairs/va.gov-team#72568]
### Your Name

Drew Fisher

### Your GitHub handle (terminal access is managed through GitHub)

@cilestin

### Your dsvagovcloud AWS user name (if applicable)

Drew.Fisher

### Team, Role, and Company of the target individual

Engineering Crew Lead, Lighthouse Benefits & Appeals APIs @ Ad Hoc

### Product Manager (PM) name and email

Andrew Ramos, ramos_andrew@bah.com

### Product Owner (PO) name and email

Janet Coutinho, janet.coutinho@va.gov

### COR Name (leave "None" if you listed an AWS user name above)

None

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

None

### Please confirm if you are on the VFS Team Roster or Platform Team Roster

- [X] [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Please confirm E-QIP Transmittal/Adjudication. This could be a screenshot of your Transmittal/Adjudication email, a link to another request where you've submitted this proof (i.e. AWS/SOCKS), etc.

- [X] I have attached proof that I have either transmitted my E-QIP survey or previously received a favorable decision (by including in "Additional Notes" section below)

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### Additional Notes

I will need ongoing access as I am one of the on-call production support personnel for the Lighthouse Benefits & Appeals APIs. Since I oversee multiple API teams, being able to quickly help any of those teams with their support issues is vital.

In my [previous access request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/56716) I submitted my proof to Jeffrey Hayter (jeffrey.hayter@va.gov) - my eQIP transmission date was on Tue, Nov 24, 2020.

### Additional resources for Support Engineer

- [ ] For users on a VFS team but not in the VFS Team Roster, they must start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] Instructions for handling requests [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access) - Support Only

**Comment by IsaiahMW1** [comment]
Found in VFS Team Roster

**Comment by IsaiahMW1** [comment]
@cilestin Access has been granted to the dev, staging, and sandbox environments.
Access for user for prod needs approval by OCTODE.
Here's some additional documentation for the [Vets API on EKS]
([https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-TerminalAccess)

**Comment by IsaiahMW1** [comment]
Good afternoon @cilestin I see you are currently a member of the following environments. are you having an error logging into these environments.

**Comment by cilestin** [comment]
@IsaiahMW1 apologies, I had been told my access was revoked and didn't think to double check before opening the ticket. I do have access, but I'm not sure now what the new expiration date might be.

**Comment by IsaiahMW1** [comment]
@LindseySaari @ericboehs  can one of you please give us a 👍  to extend their access please?

**Comment by IsaiahMW1** [comment]
@cilestin your ArgoCD/vets-api Production access has been extended for 3 months, expiring 3/27/24. Please set a reminder for yourself to return to this Issue and re-request access within 1 week of the expiration date. You'll receive 1 reminder with a 48 hour window to respond. Failure to do so will result in lost access and will require you to fill out a new request.

**Comment by IsaiahMW1** [comment]
Slack reminder [Here](https://dsva.slack.com/archives/C02RLAUM2LV/p1703775636399939)

**Comment by lindsay-insco** [comment]
@cilestin Your Vets API Terminal Production access has expired.

Would you like to request an extension? You have 72 hours to respond, or your
access will be revoked and you will need to fill out a new request

**Comment by lindsay-insco** [comment]
@cilestin it has been 72 hours with no response. Vets-API access has been removed.

If you need continued access please fill out a new request [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=external-request%2Cplatform-tech-team-support%2Cops-access-request&template=vetsapi-argo-terminal-access.yaml&title=Vets-api+terminal+access+for+%5Bindividual%5D)
