### ISSUE TITLE
AWS access for Eric Tillberg

### ISSUE THREAD

**Issue by Thrillberg** [department-of-veterans-affairs/va.gov-team#72567]
### COR Name

Laurene "Reney" Cook

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Eric Tillberg

### Your Email

etillberg@pluribusdigital.com

### Team, Role, and Company of the target individual

Forms, Full Stack Engineer, Pluribus Digital

### Product Manager (PM) name and email

Tricia Baker tricia.baker@oddball.io

### Product Owner (PO) name and email

Matthew Dingee mdingee@va.gov

### Desired AWS Access

I'd like SSM Access to lower environment instances. I believe membership in the dsva-vfs-developers group is sufficient.

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

<img width="1043" alt="Screenshot 2023-12-26 at 9 14 33 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/10481391/472fce3c-afab-40d6-b674-547ab95e12c6">

### Additional Notes

I'm requesting this access so that I can integrate the simple forms API with the SASHSA system to implement form 26-4555. We want to make API calls but the API is only accessible on the VA network.

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [ ] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by flooose** [comment]
User found in Atlas (formerly VFS Team Roster)

**Comment by flooose** [comment]
User is not requesting prod access so according to our current policy, access is being granted.

**Comment by Thrillberg** [comment]
May I also have access to view buckets (to match Jacob Penner's access)? Thank you!

**Comment by barbarello** [comment]
@Thrillberg closing this issue based on your latest comment in  https://dsva.slack.com/archives/CBU0KDSB1/p1727118620291489?thread_ts=1727109062.017089&cid=CBU0KDSB1
