### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by rachaelpenfil** [department-of-veterans-affairs/va.gov-team#72577]
### Name

Rachael Penfil

### Email

rachael.penfil@adhocteam.us

### Role

Design Lead, Accessibility SME

### Team

IVC Forms

### Product Manager (PM) name

Premal Shah

### Additional Notes

I will need edit access, since I create designs and annotations.

**Comment by naomimarcussen** [comment]
Invite has been sent. Let me know when you create your account and I can make you an editor.

**Comment by naomimarcussen** [comment]
Saw that you created an account and I bumped you up to editor. You should be good to go now. :)
