### ISSUE TITLE
Flipper UI access for [Vanson Samuel (binq)]

### ISSUE THREAD

**Issue by binq** [department-of-veterans-affairs/va.gov-team#72583]
### Your Name

Vanson Samuel

### Your GitHub handle (Flipper UI access is managed through GitHub)

@binq

### Team, Role, and Company of the target individual

Backend Developer

### Please confirm if you are on Atlas, Platform Team Roster or are a Federal User

- [X] [Atlas](https://dev.va.gov/atlas)
- [X] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [X] Lesser Environments (Dev/Staging/Sandbox)
- [x] Production (if requesting, justify prod access below)

### Reason for Production Access (If requested)

Need to enable the VYE feature for UI development in staging

**Comment by bdech** [comment]
confirmed in Atlas
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/135037265/7ebbae89-88a1-4785-8b94-f5a30f75df23)

**Comment by binq** [comment]
![Screenshot 2023-12-27 111038](https://github.com/department-of-veterans-affairs/va.gov-team/assets/37637/55fe6937-b10b-4f9f-bd79-9f7f493bbad0)

**Comment by bdech** [comment]
@binq You've been granted access to lesser environments.

**Comment by binq** [comment]
We are about to launch VYE to prod, and I'll need access to enable/disable the API as needed.

**Comment by davidpetras** [comment]
@binq you have been granted access to Production.
