### ISSUE TITLE
Content & Design Discovery for adding VVC and CVT Support

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#72581]
Each appt modality has specific instructions for contacting and making changes to an appt and instructions for preparing for the appointment. This content is displayed on error pages and accordions that are on error and success pages. Often, for example, an accordion could have instructions for more than 1 modality. Now that we're adding VVC and CVT, having instructions for 4 different types of appts could be a bit unruly. 

The goal of this epic is to identify if switching to modality-agnostic messaging would be beneficial and possible (from a content and engineering perspective, e.g., talk to engineers about the proposed changes to content on specific pages or accordions). 

[Modality Content Matrix](https://www.figma.com/file/th4V0mCvPbKYLCDgaZjovw/Telehealth-%7C-Check-In?type=design&node-id=7%3A484&mode=design&t=J3IxGrMQTaWsuVpj-1)

**Comment by loripusey** [comment]
@benbrasso-agile6 can I close this epic, are we done with this discovery?

**Comment by benbrasso-agile6** [comment]
I'd say, yes. 

For documentation purposes, there was a potential follow on change, but I think that it could be covered as a new epic or CIE Tech & Design Debt. But, just documenting here to not lose track of it: https://github.com/department-of-veterans-affairs/va.gov-team/issues/74107#issuecomment-1954349467

cc @cgednalske

**Comment by loripusey** [comment]
ok, closing
