### ISSUE TITLE
PMC content update - Review page - Content no longer matches Step 2

### ISSUE THREAD

**Issue by rachelshearerux** [department-of-veterans-affairs/va.gov-team#72585]
We've made these changes already to Step 2 - Supporting documentation, and now we need to update the content on the review page for consistency. 

**Updated content:**
> We don’t require that you submit anything with this form. But to speed up the process, we encourage you to submit military records or discharge documents if they’re available.   
>
> We prefer that you upload the Veteran’s or Reservist’s DD214.   
>
> Guidelines for uploading a file:  
	• 	You can upload a .pdf, .jpg, .jpeg, or .png file
	• 	Your file should be no larger than 20MB

| Before | After|
| :--- | :--- |
| <img width="526" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzJJQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--461609e4c38d110caaf7bb8717cf5f1070c3a550/Current%20screenshot.png" alt="Current screenshot.png" /> | <img width="738" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUdKQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--38cdb9bb24b0e90d4a13839aca4c6b4465a6bba4/Screenshot%202023-12-27%20at%202.06.47%E2%80%AFPM.png" alt="Screenshot 2023-12-27 at 2.06.47 PM.png" />
 | 

---
Definition of done
- [x] Update the body content to match what exists on the form step
- [ ] Confirm in staging

---
Documentation:
- [Figma](https://www.figma.com/file/U95x4PNKGVtA25aBvBdzrO/40-0247---Presidential-Memorial-Certificate?type=design&node-id=5%3A34657&mode=design&t=rmr8A32gmwpaZJAA-1) (!)
- [Collab cycle ticket](https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team/70906)

**Comment by tlei123** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-website/pull/27302) opened.

**Comment by tlei123** [comment]
@rachelshearerux , change is now in [Staging](https://staging.va.gov/burials-memorials/memorial-items/presidential-memorial-certificates/request-certificate-form-40-0247), ready for validation.
