### ISSUE TITLE
PMC content update - Review page and File upload - Remove text

### ISSUE THREAD

**Issue by rachelshearerux** [department-of-veterans-affairs/va.gov-team#72593]
Per feedback from staging review, we need to remove the word "documents" from the body content where form fillers have the optional to upload files. 

The content exists in two places:
- Step 3: Supporting documentation
- Review page - Accordion 3 "Supporting documentation": when editing

**Updated content:**
> We don’t require that you submit anything with this form. But to speed up the process, we encourage you to submit military records or discharge documents if they’re available.   
>
> We prefer that you upload the Veteran’s or Reservist’s DD214.   
>
> Guidelines for uploading a file:  
	• 	You can upload a .pdf, .jpg, .jpeg, or .png file
	• 	Your file should be no larger than 20MB
>
> { secondary button } Upload file

| Before | After|
| :--- | :--- |
| <img width="540" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeldKQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e335b84a8465ef882225d5c7a4504f7b60865a32/Before.png" alt="Before.png" /> | <img width="486" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejJKQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2b2af1009c12bcfcdb58e147e4a306af2ebe1794/After%20%283%29.png" alt="After (3).png" /> | 

---
Definition of done
- [ ] Step 3: "Upload documents" no longer shown above 'Upload file' button
- [ ] Review page:  "Upload documents" no longer shown above 'Upload file' button when editing accordion 3, "Supporting documentation"
- [ ] Confirm in staging

---
Documentation:
- [Figma](https://www.figma.com/file/U95x4PNKGVtA25aBvBdzrO/40-0247---Presidential-Memorial-Certificate?type=design&node-id=5%3A34657&mode=design&t=rmr8A32gmwpaZJAA-1) (!)
- [Collab cycle ticket](https://app.zenhub.com/workspaces/vagov-product-team-forms-634853151f5c6000165942bc/issues/gh/department-of-veterans-affairs/va.gov-team/70906)

**Comment by tbaker1026** [comment]
Duplicate
