### ISSUE TITLE
[Congressional] V11206125 Due 2/5/2024 - Rep Horsford

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#72592]
## Issue Description
_Veteran's caregiver is having issues with a VA-FSC application. The caregiver has not been paid since August and needs to have her bank account information changed. She is verified with ID.me but the verification keeps using her government credentials when attempting to verify.
---
## Tasks
- [x] Review congressional correspondence
- [x] Resolve issue 
- [x] Notify Veteran and congressional correspondence channel of solution.

## Acceptance Criteria
- [x] Veteran issue will be resolved or responded to with final answer to issue 
- [x] Congressional Correspondence will receive details of the resolution 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2023-CSM** [comment]
Email sent to user providing contact info for ID.me and for direct deposit modifications.  Our team can do neither.

**Comment by Kimberley2023-CSM** [comment]
No response from the Veteran, just sent a follow up email.

**Comment by Kimberley2023-CSM** [comment]
Reached out to Veteran today via phone call.  Made contact and issue is resolved.  She has received 4 checks and currently awaiting payment from December.

This case is CLOSED! :closed_sign:

P.S.  She did mention another possible issue but it sounds like she has an issue with the medical facility/hospital where a non approved surgery took place.  I informed her in the follow up email I sent to feel free to provide some detail and we will assist in getting it to the correct department.
