### ISSUE TITLE
Consolidate on-boarding docs into one place

### ISSUE THREAD

**Issue by accbjt** [department-of-veterans-affairs/va.gov-team#726]
On-boarding docs are confusing because they are located in multiple places and when you open a link it doesn't open in another tab. This is confusing for users and they do not know where they are in the process. I had someone think they were done with their local setup but they were not. This is because our docs don't flow well and do not live in one place. We need to have our on-boarding docs be in one place and flow correctly when going through them.

**Comment by andreahewitt-odd** [comment]
This should organically happen when we do the repo migration.
