### ISSUE TITLE
Update page content

### ISSUE THREAD

**Issue by twoangstroms** [department-of-veterans-affairs/va.gov-team#72605]
### Description
We have updated some processes that require updates in content to this page. 

The old content:

"How to Use the new Portal:
There are two main pathways to get to the portal:

1. Since you’re here, you can use [this link](https://dj540s05.optimalworkshop.com/questions/30da98e492625eb82c077b4b2a6d800c); bookmark it for convenience.
2. Alternately, you can get to the Platform Feedback Portal from the #vfs-platform-support channel in Slack. Navigate to the Give Feedback to Platform bookmark (see images below). You may not be able to see this part of Slack if your Slack window is too narrow, so widen your Slack window if you need to.
3. Click on the bookmark, which will open the Portal survey page in your browser.
4. Fill the survey out and submit!

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/62673202/379bd36d-ccf7-434c-bbc2-2d3ebe787264)

Bookmark in #vfs-platform-support channel

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/62673202/29caa350-a460-4966-9e69-afd06da19fb7)

Additional info on hover"

should be updated to

"How to Use the new Portal:

1. Navigate to the #vfs-platform-support channel in Slack and find the Platform Feedback bookmark (see images below). You may not be able to see this part of Slack if your Slack window is too narrow, so widen your Slack window if you need to.
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/62673202/482bdeb1-0ed7-4042-a1c3-c4dbfd929f03)
2. Click on the bookmark, which will open the Portal survey.
3. Fill the survey out and submit!

(Note that once you have clicked on the Bookmark, whether or not you completed the survey, you will have access to summoning the Portal through the slash command “/portalfeedback”. This is not obvious.)

### Relevant URLs

Content to copy: https://vfs.atlassian.net/wiki/spaces/SDT/pages/2645753888/Platform+Feedback+Portal+explanatory+page
Page to update: https://depo-platform-documentation.scrollhelp.site/support/give-feedback-about-platform-products-or-services

### Which type of team are you on? (Platform team, VFS team, or Leadership)
Platform team: Service Design

**Comment by johnny-jesensky-adhoc** [comment]
Hi @twoangstroms, thanks for getting this into our queue. The Platform Content Team will take a look, and work to get this updated. 

Will keep you updated in this ticket. Thanks!

**Comment by johnny-jesensky-adhoc** [comment]
Hi @twoangstroms, I was taking a look at this ticket this morning, and it looks there were [some edits made](https://depo-platform-documentation.scrollhelp.site/support/give-feedback-about-platform-products-or-services) to this page over the last week.

We appreciate you going ahead and making these changes proactively. Do you need any additional content support on this page?

If not, I'll look to close this out.

**Comment by twoangstroms** [comment]
Hi Johnny,

Thanks! We might be making one addition of text and image (with caption and alt text) but I can do that through the Confluence process. 


Dan Turner

Sr. UX Designer II, Ad Hoc
***@***.***

￼

**Comment by johnny-jesensky-adhoc** [comment]
Sounds great - I'll close this out then. Thanks!
