### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by rakeshmaurya563** [department-of-veterans-affairs/va.gov-team#72604]
### Name

Rakesh Kumar Maurya

### Email

rakesh.maurya@va.gov

### Role

QA Engineer 

### Team

va.gov SM team

### Product Manager (PM) name

Bryan D Riley

### Additional Notes

To perform my task

**Comment by naomimarcussen** [comment]
Invite has been sent to rakesh.maurya@va.gov
