### ISSUE TITLE
SPIKE: Determine if Both Veteran & Provider Appointments Must Be Marked as Checked-in when the Veteran Checks In

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#72620]
## Background
It is our understanding that there are 2 VistA appointments for a Veteran CVT appointment, one for the Veteran to show up at a facility for a telehealth appt and one for the Provider. It was mentioned in the distant past that when a Veteran checks in for their CVT appointment that both the Veteran appointment and Provider appointment must be marked as "check in complete". We need to verify if this is true.

## Tasks
- Verify that we only want to display the patient appointment (not the provider) appointment for Pre-Check-in & Check-in 
- Determine if Both Veteran & Provider Appointments Must Be Marked as completed Pre-Check-in when the Veteran completed Pre-Checks In
- Determine if Both Veteran & Provider Appointments Must Be Marked as Checked-in when the Veteran Checks In
- Verify our method of verification of these appointments
- Could we test this is Staging?
- Determine how we can test this (in Staging or Production)
- **Create a GitHub document that details our plans for handling CVT appointments in Pre-Check-in & Check-in** 
    - **Get Kay to approve it**
    - **Get Shawn to approve it**

**Comment by brianseek** [comment]
Doc started: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/discovery/cvt-appointments/modalities-plan.md

**Comment by brianseek** [comment]
@loripusey see my doc in the last comment. That is where I am at with my understanding of all this. This is what I will show in Monday's meeting. Let me know if you have questions, also feel free to make changes or add things.
