### ISSUE TITLE
CF: Indicate school closed when closure date is in the past on Profile Page

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#7263]
As a user of the comparison tool, I want to see the most accurate cautionary information as it relates to school closings so that I can make the best decision regarding how to use my education benefits. 

## Assumptions
1. This functionality will be behind a prod flag so that it is only available on staging. 

## Acceptance Criteria: 
1. When the school closure date associated with a school closing flag passes, the language on the Institution Summary at the top of the Profile Page states: 
Header: "School closed"
Subtext: "School has closed."
2. When the school closure date associated with a school closing flag passes, the language on the Cautionary Information Accordion in the middle of the Profile page states:
Header: "School has closed"
Subtext: “This school has closed. <link>Visit the school's website to learn more</link>"

Supporting Artifacts: 
1. Prototype: https://bahdigital.invisionapp.com/share/N5IAD8MHTC9 *updated 3/16

**Comment by hughes-dustin** [comment]
branch: bah-7263
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/12048

**Comment by delli-gatti-michael** [comment]
Local testing complete

![Screen Shot 2020-03-31 at 11.59.38 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/d051d8cd-66b6-4c24-937f-5c7fccbc45f1)

![Screen Shot 2020-03-31 at 11.59.51 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/e3a84906-36a0-4163-a321-f2cbb56a7186)

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/244&group_by=cases:section_id&group_order=asc
