### ISSUE TITLE
Old breadcrumb showing on alert page

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#72649]
## Summary
_Describe what went wrong_

## Specs
- Device: 
- Browser: 

## Steps to Reproduce
**Test User: Judy Morrison** 

1. Login as Judy Morrison
2. Go to: _https://staging.va.gov/my-health/appointments_
3. Trigger the pagerduty alert (see screenshot under _Actual Result_)
4. Note the breadcrumb is _Home > Health care > Schedule and manage health appointments > Appointments_

### Actual Result
_Describe what happened that was unexpected or undesired; including screenshots is encouraged_

The old breadcrumb is showing.

<img width="719" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzZMQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c5be0e735b11746d8241881b16598990942aaa87/image.png" alt="image.png" />

### Desired Result
_Describe what was supposed to happen; reference existing Github issue that contains a solution if possible_

The breadcrumb should be `VA.gov home > My HealtheVet > Appointments`

## Definition of Done
- [ ] Desired result is achieved and/or document decisions made
- [ ] Relevant documentation is updated

---
## How to configure this issue
- [ ] **Labeled with Team** (`vaos`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `design`, `product`)
- [ ] **Labeled with** `Bug`
- [ ] **Assigned to** Product for prioritization

**Comment by JRRoof** [comment]
Not sure what triggers this message, but it's not PagerDuty.  The PagerDuty maintenance message looks like this:
<img width="1012" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMG1NQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d4c771ab24227483f3d81be925ffd2bd10bde2f0/image.png" alt="image.png" />

**Comment by JRRoof** [comment]
Also need to make sure the the Google Analytics events are still being triggered for the breadcrumb links when this page is displayed.

**Comment by outerpress** [comment]
@vbahinwillit If it helps, the error was spotted on the morning of 12/28 while accessing the app. [Here's the Slack thread where it came up.](https://dsva.slack.com/archives/C03CGTDLTFF/p1703777322781399)

**Comment by simiadebowale** [comment]
This is happening whenever the feature flag api call returns an error or empty response. We can take out the breadcrumbs feature flag since it's live in PROD now. that should fix this intermittent issue.

**Comment by simiadebowale** [comment]
@ldelacosta - this is ready for validation

**Comment by outerpress** [comment]
Hi @simiadebowale @ldelacosta I'm trying to figure out how to validate this one. Was the solution to remove a feature flag? Or was there a UI update?

**Comment by ryanshaw** [comment]
I believe this was resolved with [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/27973) -- which removed the feature flag. @simiadebowale can confirm.

**Comment by outerpress** [comment]
@ldelacosta this looks good to me! Thank you
