### ISSUE TITLE
10-10d midpoint review

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#72642]
Prototype
[research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/champva/1010D/research/users/10-10d%20Midpoint%20Review/Research%20Plan.md)
[conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/champva/1010D/research/users/10-10d%20Midpoint%20Review/Conversation%20Guide.md)

**Comment by jamiefiore** [comment]
Here's the link to the [Figma file](https://www.figma.com/file/HVQQBvkS9DJlNVehCwva4m/10-10d-Midpoint-Review?type=design&node-id=0%3A1&mode=design&t=O1kQPCQnOHsRqQPy-1) for MidPoint:
