### ISSUE TITLE
Apply card with icon component to VA telehealth details pages

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#72653]
## Description
This adds the [appointment card with icon component](https://design.va.gov/components/card#appointment-large-with-icon) to VA telehealth appointment details pages. 

**Note:** the Check-in team has built this component, but it hasn't been added to storybook yet. Please discuss with them before working on this ticket. A new ticket may be needed to add the component to storybook before work starts.

**Dev Notes:**
The Check-in team has built their appointments card using a collection of design system components and html. We can reference their code [here](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/check-in/components/pages/AppointmentDetails/index.jsx)

---

## Acceptance Criteria
Background: the `va_online_scheduling_appointment_details_redesign` toggle is on

Given the user is on the details page for a [VA video care at a home appointment](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/feature-reference/appointment-types/va-video-care-at-home.md)
Then appointment card with icon component wraps around the page content
And the [icon](https://design.va.gov/storybook/?path=/docs/uswds-va-icon--icons) in the component is `videocam`.

Given the user is on the details page for a [VA video care on GFE appointment](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/feature-reference/appointment-types/va-video-care-on-gfe.md)
Then appointment card with icon component wraps around the page content
And the [icon](https://design.va.gov/storybook/?path=/docs/uswds-va-icon--icons) in the component is `videocam`.

---

Given the user is on the details page for a [VA video care at a VA location appointment](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/feature-reference/appointment-types/va-video-care-at-a-va-location.md)
Then appointment card with icon component wraps around the page content
And the [icon](https://design.va.gov/storybook/?path=/docs/uswds-va-icon--icons) in the component is `location_city`.

Given the user is on the details page for a [VA video care at ATLAS location appointment](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/feature-reference/appointment-types/va-video-care-at-atlas-location.md)
Then appointment card with icon component wraps around the page content
And the [icon](https://design.va.gov/storybook/?path=/docs/uswds-va-icon--icons) in the component is `location_city`.

---

Given the user is on the details page for a [VA phone appointment](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/feature-reference/appointment-types/va-phone.md)
Then appointment card with icon component wraps around the page content
And the [icon](https://design.va.gov/storybook/?path=/docs/uswds-va-icon--icons) in the component is `phone`.

### Design Assets

[Design spec](https://www.figma.com/file/wQy9CVKBu1yRmBWLFk05Ll/Add-Icon-Card-to-Details-Pages-%7C-Appointments-FE?type=design&node-id=1-39&mode=design).
All design spec copy is For Placement Only. This ticket only adds the appointment card with icon component.

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by JRRoof** [comment]
Blocked until Github issue [#72660](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/72660) is completed

**Comment by ryanshaw** [comment]
@outerpress I believe the video icon is called `videocam` not `video_appointment`. Just need confirmation.

**Comment by outerpress** [comment]
@ryanshaw oh yep, you're right. I'll update the ticket with the correct reference. Thanks!

**Comment by outerpress** [comment]
@ryanshaw @ldelacosta it looks like Upcoming and Canceled vid appointments are using the calendar icon, those should be using the videocam icon. See screenshots [here](https://www.figma.com/design/q1lq0bwvDMCg6RADZddYMX/Details-Pages-Specs-(WIP)-%7C-Appointments-FE?node-id=3270-46137&t=2R7K1FJveMamp1wK-4), or look at Judy Morrison's appts on July 12 and Aug 14th.

**Comment by ldelacosta** [comment]
Bug ticket will be created. @ryanshaw @outerpress

**Comment by outerpress** [comment]
@ldelacosta sounds good, everything else looks good here

**Comment by outerpress** [comment]
Upcoming and Past icons are GTG @ldelacosta @ryanshaw 

<img width="642" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlEyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a4fa0637f6b22be303005efeaa072ddd847075a0/Screenshot%202024-06-04%20at%2010.18.56%E2%80%AFAM.png" alt="Screenshot 2024-06-04 at 10.18.56 AM.png" />

<img width="640" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmcyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--349b4c75fc4c78d720791970099db6c179b4d6c6/Screenshot%202024-06-04%20at%2010.17.57%E2%80%AFAM.png" alt="Screenshot 2024-06-04 at 10.17.57 AM.png" />
