### ISSUE TITLE
Apply card with icon component to community care appointment details pages

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#72652]
## Description
This adds the [appointment card with icon component](https://design.va.gov/components/card#appointment-large-with-icon) to community care details pages. 

**Note:** the Check-in team has built this component, but it hasn't been added to storybook yet. Please discuss with them before working on this ticket. A new ticket may be needed to add the component to storybook before work starts.

**Dev Notes:**
The Check-in team has built their appointments card using a collection of design system components and html. We can reference their code [here](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/check-in/components/pages/AppointmentDetails/index.jsx)

## Acceptance Criteria
Background: the `va_online_scheduling_appointment_details_redesign` toggle is on

Given the user is on the details page for a [community care appointment](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/feature-reference/appointment-types/community-care.md)
Then appointment card with icon component wraps around the page content
And the [icon](https://design.va.gov/storybook/?path=/docs/uswds-va-icon--icons) in the component is `calendar_today`.

### Design Assets

[Design spec](https://www.figma.com/file/wQy9CVKBu1yRmBWLFk05Ll/Add-Icon-Card-to-Details-Pages-%7C-Appointments-FE?type=design&node-id=1-39&mode=design).
All design spec copy is For Placement Only. This ticket only adds the appointment card with icon component.

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by JRRoof** [comment]
Blocked until Github issue [#72660](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/72660) is completed

**Comment by Cieramaddox** [comment]
@ldelacosta This has been validated by UX

**Comment by ldelacosta** [comment]
No issues to report. Closing out the tickets.
