### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by ytsaoca** [department-of-veterans-affairs/va.gov-team#72654]
### Name

Ya-ching Tsao

### Email

yaching.tsao@civicactions.com

### Role

Product Designer

### Team

Mobile Check-In team

### Product Manager (PM) name

Lori Pusey

**Comment by naomimarcussen** [comment]
Invite sent to yaching.tsao@civicactions.com. Once you create an account, I can make you an editor.

**Comment by ytsaoca** [comment]
Hi @naomimarcussen,

Thanks for your quick response! I've joined the Figma team.

**Comment by naomimarcussen** [comment]
You now have editor permissions. :)

**Comment by ytsaoca** [comment]
Hi @naomimarcussen,
I found that I have edit access to some files but not include those check-in files, such as Check-in Production. Can you help me solve thie issues or who can I reach out to for this? Thanks!
<img width="796" alt="Screenshot 2023-12-28 at 12 52 11 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/90633685/97c95524-0f30-4d35-857c-d98ecb2132b6">

**Comment by naomimarcussen** [comment]
You'll need to be invited into the project and file. The project is owned by Kristen McConnell and the file looks to be owned by Ben Brasso. Just ask both of them to invite you in and you should be good. Note that it might take about 15 min for the change to take affect.
![Screenshot 2023-12-28 at 5 47 47 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/56055287/435c34e8-4663-469e-be0f-8471d31df69b)
![Screenshot 2023-12-28 at 5 47 20 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/56055287/06891275-457d-4f19-8496-37c5a4b4f65d)

**Comment by naomimarcussen** [comment]
Well, looks like I was able to invite you into the project. So, you'll just need to reach out to Ben to invite you in with 'can edit' permissions.

**Comment by ytsaoca** [comment]
I can access them. Thank you! @naomimarcussen
