### ISSUE TITLE
Create backend functionality (endpoint+table) to support user reports of Inaccurate Data

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#72661]
## Background
As a way to solve for inaccurate data in our Find a Representative product, we are allowing users to report/flag inaccurate data, including address, phone, email and "other" (which is partnered with a text entry field).

## Tasks
- [x] Investigate how we might restrict unauthenticated users from reporting the same data multiple times 
- [x] Create new endpoint to handle post requests that contain flagged data for a specific representative

**Comment by oddball-lindsay** [comment]
Because we're also allowing unauth users to report, the team has decided to first examine reports before proceeding to hide any contact information.  So just focus on collecting report information and displaying in a Domo Dashboard.

Domo Dashboard specifics are being defined here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/73251

**Comment by holdenhinkle** [comment]
PR for app code - https://github.com/department-of-veterans-affairs/vets-api/pull/15183

**Comment by holdenhinkle** [comment]
PR for db migration - https://github.com/department-of-veterans-affairs/vets-api/pull/15207

**Comment by oddball-lindsay** [comment]
PR for migration: something is going on, related to CI but not sure if it's something we can act on.  Will look into it.

**Comment by holdenhinkle** [comment]
To run tests locally and to hit the endpoint, I need to add `skip_before_action :verify_authenticity_token` to the controller. But Trevor says I shouldn't do that if the endpoint is being consumed by the frontend (vets-website). I'm trying to figure out how to set the CSRF token in the request in the rspec tests so they pass.

Holden Hinkle
  [2:03 PM](https://oddball.slack.com/archives/D06F7S66FLP/p1706209425802669)
Hi Trevor, How are you? I checked with Rachal about this and she suggested that I ask you.
Here’s a PR to create a new POST endpoint that doesn’t require auth - https://github.com/department-of-veterans-affairs/vets-api/pull/15183
There’s a warning about skip_before_action :verify_authenticity_token, but I had to skip this (at least locally) to be able to hit the endpoint. If you search vets-api for it, there are quite a few controllers (~25) that also skip it. Is this okay? Or is there another pattern I should use?


Trevor Bosaw
  [2:05 PM](https://oddball.slack.com/archives/D06F7S66FLP/p1706209552719939)
is this an endpoint that the frontend uses?


Holden Hinkle
  [2:05 PM](https://oddball.slack.com/archives/D06F7S66FLP/p1706209558585579)
Yeah


Trevor Bosaw
  [2:06 PM](https://oddball.slack.com/archives/D06F7S66FLP/p1706209562639589)
ah you can't skip it then
[2:06](https://oddball.slack.com/archives/D06F7S66FLP/p1706209575081029)
how are you testing it?
[2:06](https://oddball.slack.com/archives/D06F7S66FLP/p1706209579203059)
By just sending curls against it?


Holden Hinkle
  [2:06 PM](https://oddball.slack.com/archives/D06F7S66FLP/p1706209600573159)
Using Insomnia
[2:06](https://oddball.slack.com/archives/D06F7S66FLP/p1706209608432259)
And the request tests fail (they fail when I don’t skip :verify_authenticity_token) (edited) 
[2:08](https://oddball.slack.com/archives/D06F7S66FLP/p1706209701442759)
(sorry - in standup right now)


Trevor Bosaw
  [2:11 PM](https://oddball.slack.com/archives/D06F7S66FLP/p1706209879657659)
what I'd do is, go on the frontend for the stack you're testing (so if testing locally then localhost:3001 with the FE server up), then mess around until you find a url that hits the backend, then in the network tab tab do 'copy as curl'. for example:
curl 'https://staging-api.va.gov/v0/feature_toggles?&cookie_id=ydr51hf832wo4n74az3nb' \
-X 'GET' \
-H 'Accept: */*' \
-H 'Sec-Fetch-Site: same-site' \
-H 'Accept-Encoding: gzip, deflate, br' \
-H 'Accept-Language: en-US,en;q=0.9' \
-H 'Sec-Fetch-Mode: cors' \
-H 'Host: staging-api.va.gov' \
-H 'Origin: https://staging.va.gov/' \
-H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15' \
-H 'Referer: https://staging.va.gov/' \
-H 'Connection: keep-alive' \
-H 'Cookie: _ga_CSLL4ZEK4L=GS1.1.1706209598.1.0.1706209676.0.0.0; _ga_XVFLDXP6P4=GS1.1.1706209598.1.0.1706209676.0.0.0; TS01de8f7b=0119a2687f32e6fff3c4ce9a8041b4c2f8302769ee211bf7e87f12c30ebe47a71444333d1bd5a757f31fc14cfd5a66e7c318505dd6; api_session=vQqz5lb8USej4A2MbFdCOm6DuuaIaCIZhx6IJjf%2B%2BF2qTt9cBFDujWksX7PDfUcHHc7h2MV9HkGBbLX5UxgE4pQqJmfPuSs4ItQ4n1NHxhaH%2FvjV10lIwmZphnGqPe3F78iK4QkvRMen2adGEFVq1lfRQBkYX8fLy00JFymK%2BlkqECZ0sBbTi9IYy1FLTxHDIw5MhylRLpm0pUdEwYvJk4ehg6bXeyQD42dtT0PLGICJuK%2BFytmJBVGMYZmTc%2F7TpqOay4zLgkCd2xWzixs%2Bw%2BdXpEtJwRRYVgBJiDEXiJQNlj5dJVtH%2FlnK7g%3D%3D--ToqkVipKpwyZMCmx--ub809oioFtRRuOdzC%2FXAQg%3D%3D; _ga=GA1.1.1008786072.1706209599; _ga_D865094XJS=GS1.2.1706209598.1.0.1706209598.0.0.0; _ga_primary=GA1.2.1008786072.1706209599; _ga_primary_gid=GA1.2.269671628.1706209599; _gid=GA1.2.634777069.1706209599' \
-H 'Sec-Fetch-Dest: empty' \
-H 'X-CSRF-Token: 4AWvOaTI_tyX8Mfstm-RyfPZJiqutO9wUymgZUjRklRqj_87A_HBIDhwdF_RSWMPD3D_ieuAhNChwqeBweowRg'





[2:11](https://oddball.slack.com/archives/D06F7S66FLP/p1706209891840749)
Then basically just replace the url with your controller
[2:11](https://oddball.slack.com/archives/D06F7S66FLP/p1706209898148889)
that'll give you a working csrf token, etc (edited)

**Comment by holdenhinkle** [comment]
This is in review
