### ISSUE TITLE
Add Feature Toggle for Appointment Details Redesign

### ISSUE THREAD

**Issue by JRRoof** [department-of-veterans-affairs/va.gov-team#72660]
## Description
Add a feature toggle named `va_online_scheduling_appointment_details_redesign` to Staging and Production

---

## Tasks
- Add `va_online_scheduling_appointment_details_redesign` feature toggle

## Acceptance Criteria: 
- [ ] The toggle is created for VAOS

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] [Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/product/feature_toggles.md) is updated

---

**Comment by ldelacosta** [comment]
The toggle has been added. Closing out the ticket. <img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlFDQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a1c1af4d4304afc4915a9edb95636837ff2710aa/Screenshot%202024-03-22%20at%2010.58.20%20AM.png" alt="Screenshot 2024-03-22 at 10.58.20 AM.png" />
