### ISSUE TITLE
[BUG] [FE] Adjust "no" demo GA event values for 45MR 

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#72662]
## Task

- [ ] Need the "no" demo GA event values adjusted. E.g., don't include "emergency-contact" twice. Should be 

> nav-check-in-no-to-demographic-information-45MR-clicked|nav-check-in-no-to-emergency-contact-45MR-clicked|nav-check-in-no-to-next-of-kin-45MR-clicked

<br/>
<img width="500" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkdNQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3410d0607abe3f99f2c6f37bd7d51c657ff1b31e/Screenshot%202023-12-28%20at%203.46.47%E2%80%AFPM.png" alt="Screenshot 2023-12-28 at 3.46.47 PM.png" />

**Comment by brianseek** [comment]
@benbrasso-agile6 I've combined this with the other bug. Closing this ticket
