### ISSUE TITLE
Onboarding to VSP Ops

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#7267]
## Overview 
Welcome to the platform and more particularly the VSP Operations team.  This ticket is a checklist and guide to try and improve the onboarding process and get you up to speed. 

If you have any question please reach out to TJ. 

### Access to what you need
- [x] [Getting setup](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/orientation/request-access-to-tools.md#request-access-to-tools)
- [x] Share your calendar with VSP; vsp-team.group@adhocteam.us

### Understanding VSP and where we sit
- [x] [Overview of VSP](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/orientation/Welcome%20to%20VSP.md#welcome-to-the-veteran-facing-services-platform)
- [x] [Getting to know VSP](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/vsp-team-member-onboarding.md)
- [x] [Overview Presentation of VSP](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/VSP%20Mission%2C%20Objectives%2C%20Roadmap%2C%20and%20OKRs%20-%207-23-19.pdf)

### VSP Operations
High level:
- [x] [High level info of the team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsp/teams/operations#operations)
- [x] [Team charter](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/operations/operations-team-charter.md#operations-team-charter)
- Meet the members of the team
  - [x] Wyatt
  - [x] Nathan
  - [x] Taylor
  - [x] Jeremy
  - [x] Bennie
  - [x] Faith 
  - [x] TJ

More details on our work: 
- [x] [Infra Overview](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/engineering/infrastructure#infrastructure)
- [x] [VSP Onboarding](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/operations/onboarding.md)
- [x] [Infra Recommit work](https://zoom.us/rec/share/2ZNFJaH52m9LU53I5ErgfYkOPovnT6a8hCRL-adYzEau_n2EWFjjhxcTFs9H2591)
- [x] [Daytime oncall role](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/operations/daytime-oncall-support-role.md)
 - [x] Talk with TJ about Sprint Objects 
- When creating an issue in GH, make sure to use the “Standard Issue Template”

### Overviews 
- [x] [VA Network Overview](https://dsva.slack.com/archives/CJYRZK2HH/p1568982910041200)
- [x] [Our current BRD overview](https://zoom.us/rec/play/usUrd-6s_z83HdHGuQSDBaUrW47ue6ysg3Udr_NYyku2VHJXMwegb7BBardDXyrOvVEQ0Rn8j_5pt9Op?autoplay=true&startTime=1570553770000)
 - [x] https://github.com/department-of-veterans-affairs/vsp-infra-demo
- [x] [Ansible Overview](https://zoom.us/rec/play/uMB7druurjI3S9GWsASDC_d7W9S0Jvms0Ccd8vMJzEqwBXRRO1D3ZrQRM-brWsd8PNfawPVTesdwLrG7?autoplay=true&startTime=1571860777000)
- [x] [Grafana overview](https://zoom.us/rec/play/uZR_I--o_zo3GdDH4gSDBqd7W426J_qs2ylL-_ZeyEy8BnRVZwKkZ7MWZOAtXA9N7YhPyRvLuov228GF?autoplay=true&startTime=1573063037000)
- [x] [Overview of Service Now](https://zoom.us/rec/play/vJModuGupm43HdeW5QSDVqArW9W6L_6s1nAb-aUNnknhWnEBOlGnNeERMeLqy001uOwCdfqvWAk6x2e-?autoplay=true&startTime=1584040023000)

**Comment by jsev-io** [comment]
Completed
