### ISSUE TITLE
[BUG] [FE] Check if 45MR GA event is appending correctly and fix no value for E-contact

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#72671]
## Description 

I created an appt in the stage scheduling tool. Placed the UUID in my browser. Therefore, I wouldn't expect GA events to be appended with "-45MR-" but they were. Did we implement it backwards? Or, are the "-45MR-" GA events firing because I used neither text "check in" to XXXX or selected the 45MR text message? 

Example of appt on stg

<img width="600" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHVNQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cf85113d9b09b1ef3bdcd6e8193937693b931b91/Screenshot%202023-12-28%20at%205.04.21%E2%80%AFPM.png" alt="Screenshot 2023-12-28 at 5.04.21 PM.png" />

## Tasks

- [ ] Determine if 45MR GA event param is working as intended for check in
- [ ] Need the "no" demo GA event values adjusted. E.g., don't include "emergency-contact" twice. Should be 

> nav-check-in-no-to-demographic-information-45MR-clicked|nav-check-in-no-to-emergency-contact-45MR-clicked|nav-check-in-no-to-next-of-kin-45MR-clicked

<br/>
<img width="500" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkdNQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3410d0607abe3f99f2c6f37bd7d51c657ff1b31e/Screenshot%202023-12-28%20at%203.46.47%E2%80%AFPM.png" alt="Screenshot 2023-12-28 at 3.46.47 PM.png" />

**Comment by brianseek** [comment]
@benbrasso-agile6 this has been merged and should be good to validate on stage soon

**Comment by benbrasso-agile6** [comment]
Sounds good, will validate tomorrow

**Comment by benbrasso-agile6** [comment]
Staging seems to be down atm. Will try again once it's resolved.

**Comment by benbrasso-agile6** [comment]
validated on stg
