### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#72679]
### Name

Lori Pusey

### Email

lori.pusey@agile6.com

### Role

Product Manager

### Team

Modernized Check-in (a.k.a. Check-in Experience [CIE])

### Product Manager (PM) name

Katherine Lawyer

### Additional Notes
**Our team's files will be in MHV - Unified Appointments Team** 
Need to be able to view Figma files
Need to be able to create, reply to, and resolve comments

**Comment by naomimarcussen** [comment]
Invite has been sent.

**Comment by loripusey** [comment]
Got it thank you.
