### ISSUE TITLE
Design/FE | Profile | General Maintenance | Profile Hub Breadcrumbs Revision

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#72681]
## Background 
We have breadcrumbs in the profile hub and it turns out we might not need it on the root page `va.gov/profile`

<@U051AMXDEGP> I learned yesterday that _typically_ <http://VA.gov|VA.gov> does not use breadcrumbs on a root level page, since it is so easy for people to get back to the homepage. We have one on the profile hub page, and I’m surprised this didn’t come up during collab cycle for that page. Could you help us figure out if that’s something we should take off the page or not?

[Slack Message](https://dsva.slack.com/archives/C909ZG2BB/p1703791724462089?thread_ts=1703791724.462089&cid=C909ZG2BB)

## Acceptance criteria 
- [ ] we've determined if we should remove or keep the breadcrumbs on the profile hub page
     - [ ] if keep close the ticket 
     - [ ] if remove, update and remove the breadcrumbs, have PM and PO test to confirm no negative impacts

**Comment by mtcA6** [comment]
@adamwhitlock1 didn't you just work on updating the breadcrumbs? Do we still need this ticket now that you've revised the breadcrumbs?

**Comment by adamwhitlock1** [comment]
This ticket is still needed I updated a bug in the breadcrumbs logic, but didn't know about this one.

**Comment by mtcA6** [comment]
I feel like we should point back to My VA. 

![Image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/acc99edf-e85d-478a-9236-fca69b929589)

On the sub pages do we drop VA.gov too? 

![Image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/666deb2c-b3c5-406b-a56d-9a3d9a024dcc)

**Comment by mtcA6** [comment]
Checked w CAIA they [pointed to the usability and content sections of the design system documentation](https://design.va.gov/components/breadcrumbs)

Specifically:

- **Include one, include all**. If you use a breadcrumb for one page in a hierarchy, always use a breadcrumb for all pages within that hierarchy.
- **Use “VA.gov home” as the default home crumb title.** This component will default to “VA.gov home” for the first crumb. This is the preferred content for this crumb. Deviation from this should only be done with express permission from CAIA.

[See slack thread](https://dsva.slack.com/archives/C01K37HRUAH/p1715881412669009)
