### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by LoisLewisUSDS** [department-of-veterans-affairs/va.gov-team#72686]
### Name

Lois Lewis

### Email

lois.lewis2@va.gov

### Role

Researcher

### Team

MHV on VA.gov, IVC

### Product Manager (PM) name

Kevin Hoffman

### Additional Notes

I had access but now I can't login using my va email with single signon

**Comment by naomimarcussen** [comment]
Sent another invite to lois.lewis2@va.gov. Let me know if that works.
