### ISSUE TITLE
[Support] Analytics Bug - Navigation Zone One Bringing in Null Value

### ISSUE THREAD

**Issue by nedierecel** [department-of-veterans-affairs/va.gov-team#727]
## What happened?
- Within GA, there is a navigation item that is bringing in a null value:

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/554e5aad-3a0a-4a7e-bd0d-bdd00cce0c52)

- Original ticket: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/17396

## Steps to Reproduce
- URL: [Review Google Analytics report](https://analytics.google.com/analytics/web/?authuser=0#/report/content-event-events/a50123418w177519031p184624291/explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.eventCategory:Interactions,analytics.eventAction:Navigation%20-%20Zone%20One%20-/)
- GTM: Review **Navigation Action Lookup** tag to see RegEx rules
- On VA.gov homepage, review the structure of dataLayer events to see that all links in the screenshot have an associated `nav-path` sent with the event.

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/cad0dc6c-eecd-4b35-92d2-ea2b27e1775e)

## Desired behavior
- The `nav-path` should be brought into the Event Action instead of a blank value. 

### Analytics team
- [ ] Issue is corrected within Google Tag Manager (GTM)
- [ ] Analytics-Insights validates
- [ ] Analytics-Insights publishes changes
### Public Websites
- [ ] Event is captured to GTM only when the event actually occurs

--- 
## Definition of Done
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by nedierecel** [comment]
@ncksllvn I wanted to put this on your radar as a low-priority bug. Within Google Analytics reporting, there is an item bringing in a null value for the `nav-path` dataLayer variable.

I checked all of the Zone 1 links, and they all appear to have the `nav-path` variable. Is there anything that might be firing a null `nav-path` value when the browser is resized? For context, [please see this comment from Bill](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/13952#issuecomment-431981997) when we ran into another issue during the WBC launch.

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/59128d6e-f94a-48c3-9b41-61c9d28597ab)

**Comment by nedierecel** [comment]
@bsmartin-ep I wanted to surface this other bug that is occurring for you to help troubleshoot. Please see issue summary/task description that displays an empty value.

All of the Zone One links should follow a format like so:
_Navigation - Zone One - ->/disability/how-to-file-claim_

**Comment by bsmartin-ep** [comment]
@nedierecel - I can recreate this by clicking the whitespace between the navigation links on the homepage.  I think we can fix this by updating the JavaScript at the bottom of the page to make sure it's an actual link that is being clicked.

```
for (var i = 0; i < hubLinksList.length; i++) {

    hubLinksList[i].addEventListener('click', function (e) {
            var linkData = e.target.dataset;

            recordEvent({
                event: 'nav-zone-one',
                'nav-path': linkData.navPath,
            });
        }
}
```

...changes to...

```
for (var i = 0; i < hubLinksList.length; i++) {
    hubLinksList[i].addEventListener('click', function (e) {
        if (e.target.tagName === "A") {
            var linkData = e.target.dataset;

            recordEvent({
                event: 'nav-zone-one',
                'nav-path': linkData.navPath,
            });
        }
    });
}
```

**Comment by nedierecel** [comment]
Hello @ncksllvn - Lower priority for the team, but please let me know if this issue should be addressed by the Public Websites team. This is an extra event that is being recorded to Google Analytics when users are clicking the whitespace in Homepage Zone One links. Thanks!

**Comment by ncksllvn** [comment]
@nedierecel , good question, I think our team can grab it. I'll add our team label and we should pick it up soon!

**Comment by ncksllvn** [comment]
CC: @MickinSahni

**Comment by MickinSahni** [comment]
> @nedierecel , good question, I think our team can grab it. I'll add our team label and we should pick it up soon!

Hey @ncksllvn putting this in next sprint and also added a `needs-grooming` label on it as there might still be some questions to answer in planning mañana.

**Comment by ncksllvn** [comment]
Just to confirm, does this example event look correct?

```js
dataLayer.push({
    event: 'nav-zone-one',
    'nav-path': 'Disability->/disability/how-to-file-claim'
});
```

**Comment by MickinSahni** [comment]
2020-03-26 PW Standup
- In progress

**Comment by bsmartin-ep** [comment]
@nedierecel -  In reference to @ncksllvn's comment, is this event supposed to have the section heading?

```
dataLayer.push({
    event: 'nav-zone-one',
    'nav-path': 'Disability->/disability/how-to-file-claim'
});
```

**Comment by ncksllvn** [comment]
The work is now merged and visible on Staging. We'll have time tomorrow to change or revert it if something goes wrong, but otherwise it'll go to prod during the daily.

**Comment by nedierecel** [comment]
@bsmartin-ep Correct, we currently do not include the section heading. 

@ncksllvn We're okay to omit so we can keep data consistent.  

_Screenshot: Production Data showing Zone One interactions_
![image](https://user-images.githubusercontent.com/24525739/77765458-abab2b80-7014-11ea-9972-6245dbbd5853.png)

**Comment by ncksllvn** [comment]
It looks like the section heading was omitted in the first place due to a bug in the code, so I just fixed that during this update. But I'll update again to remove references to the section heading so that it's consistent.

**Comment by MickinSahni** [comment]
2020-03-27 PW Standup
- New tweaks in an open PR

**Comment by ncksllvn** [comment]
Hey @nedierecel, can you confirm this is working okay?

**Comment by bsmartin-ep** [comment]
Looks good to me @nedierecel and @ncksllvn

**Comment by MickinSahni** [comment]
Great! Closing this sprint item out.
