### ISSUE TITLE
Create IVC CHAMPVA Module molded from SimpleFormsAPI

### ISSUE THREAD

**Issue by cloudmagic80** [department-of-veterans-affairs/va.gov-team#72706]
User Story: Currently, the IVC backend files are in the Simple Forms API directory. Since we are not using SimpleForms, we will need to create IVC-Champva folder directory. 

Acceptance criteria: All IVC Forms work EXACTLY as they do currently but on a different module

- Create new module within `/lib/modules/` by duplicating `simple_forms_api`
- Update Gemfile to add new module
- Mount the new module's routes in routes.rb
- Rename to `ivc_champva`
-- Rename controller and remove SimpleForm logic
-- Create new services if necessary
-- Update specs

Note: Let @michaelclement and @reiting what the new route will be so they can update vets-website

**Comment by balexandr** [comment]
I'll hold off on my refactor of UploadsController ticket if we are going to be using our own controller ant some point

**Comment by balexandr** [comment]
@baltes I updated the description with what I noticed digging around in the vets-api involving simple_forms_api and what we might possibly need to do to duplicate and rename for our benefit.

**Comment by balexandr** [comment]
This is currently waiting for platform review and support

**Comment by balexandr** [comment]
This has been merged into master
