### ISSUE TITLE
Contact Center Review for AE Profile - Profile Hub

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#72702]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
*Please provide the name(s) of your product and a high-level description of your product.*

VA.gov Profile

### Launch Date
*Please provide the launch or rollout date and details.*
We launched the profile hub in mid december 

### Version Number
*Please provide the version number of the guide and/or video.*
version 7

### Product Guide
*Please provide product guide link*

Can be [found here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/product/product-guides.md)
Or attached here:
[VAgov.Profile.ContactCenterGuide.v7.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/13795201/VAgov.Profile.ContactCenterGuide.v7.docx)

### Product Video
*Please provide product video link*
n/a

### Product Video Transcript
*Please provide product video transcript link*
n/a

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
The review will be complete at the beginning of the sprint on 1/28.

**Comment by starlow00** [comment]
There are no changes from VEO. The working document of v7 is attached. Please use it for future version adjustments.
[VA.gov Profile v7 SRT 01292024.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFlmQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--24fe6cb575c9b2d707594f57ad9f1e0dd3fe3635/VA.gov%20Profile%20v7%20SRT%2001292024.docx)
