### ISSUE TITLE
STEM: Create STEM Scholarship Feature Flag

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#7271]
As a developer, I need to create a feature flag that can be used to turn on and off STEM scholarship application related functionality so that it can be delivered to production in a timely manner.

## Assumptions:
1. Feature flag for STEM form will need be available in both vets-api and vets-website repos.

## Tasks
1. Follow feature flags documentation to create front-end STEM feature flag.
2. Follow feature flags documentation to create back-end STEM feature flag.

## Acceptance Criteria
1. The STEM Scholarship feature flag is created and available in all environments.

## Supporting Artifacts: 
1. Feature Flag documentation: https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/

**Comment by hughes-dustin** [comment]
Vets-website:
 branch: bah-7271
 PR: https://github.com/department-of-veterans-affairs/vets-website/pull/12062

vets-api: 
 branch: bah-7271
 PR: https://github.com/department-of-veterans-affairs/vets-api/pull/4068

**Comment by hughes-dustin** [comment]
vets-api PR will need to be submitted before the vets-website PR.

**Comment by delli-gatti-michael** [comment]
![Screen Shot 2020-03-31 at 1.27.10 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/82583b0f-2eaf-4ab5-b298-8902a38ed2fc)

**Comment by delli-gatti-michael** [comment]
local testing complete

**Comment by delli-gatti-michael** [comment]
The `edu_benefits_stem_scholarship` feature flag is now showing at [staging-api.va.gov/flipper/features](url) & [api.va.gov/flipper/features](url). Closing this issue
