### ISSUE TITLE
FSR Status Bar - Research & Design

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#72716]
### Description
As part of the President's initiative to support Veterans experiencing financial hardship we are simplifying the submission process.

This enhancement is to provide a status bar to reflect how far a veteran is in filing out the FSR.

Initial Epics to be under this Super Epic may include the items below - still TBD.

## Product Outline
The FSR experience needs to be updated for a few reasons - this scope includes:

- Research & Design

## Definition of done
- Design and Front End sync on technical implementation of design
- [ ] Required
- [ ] Not Required
>
- [ ] Team has identified a path forward to add an FSR Status Bar aligning with current application and design requirements. 

### Scope of release:

All current identified work not included for the MVP or 2.0 release.

### Out of Scope:

Newly identified work that comes out of current research and enhancement requests. All that should still be collected and placed under a 4.0 Epic.

### Additional Details/Notes (optional):
*Any other relevant information about this project not already listed above*

**Comment by HeatherRienks** [comment]
Work has been completed
@Tom-Davis
