### ISSUE TITLE
STEM: Remove STEM Scholarship question from 22-1995 workflow and submission

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#7272]
As a veteran looking to update my benefits, I should not have to answer unnecessary questions about the STEM scholarship application in order to update my benefits.

## Assumptions:
1. This work is completed behind a ~feature flag (#7271)~ prod flag.  (Changed due to form pages not being removable via feature flag.
2. This work is not enabled in production until the new STEM OMB form is available in production.
3. There are feature flags in vets-api, so we should be able to implement the updates to the spool files behind a feature flag. 

## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
1. STEM Scholarship Application questions are not included in the 22-1995 workflow.
   - The STEM questions
   - The readonly view on the "Review Application page"
2. The 22-1995 spool file does not include STEM Scholarship Application submissions.
3. The YTD Report does not include 22-1995 STEM information

## Supporting Artifacts:
1. [22-1995 Workflow with STEM](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/VA%20Form%2022-1995%20with%20STEM%20Process%20Flow%20122419%20v0.3.pdf)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/edu-benefits/1995/helpers.jsx#L22
https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/saved_claim/education_benefits/va1995s.rb#L6
https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/education_benefits_claim.rb#L120
https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/edu-benefits/1995/submitForm.js#L25

Just look for `1995s` in vets-api

**Comment by sonntag-adam** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/12120

https://github.com/department-of-veterans-affairs/vets-api/pull/4106

**Comment by sonntag-adam** [comment]
Testing follows 1995 workflow, no STEM questions appear and "Review Application page" page is read only.[https://app.zenhub.com/files/133843125/7cfcf83d-8930-462b-af08-4847f7517f18/download](https://app.zenhub.com/files/133843125/7cfcf83d-8930-462b-af08-4847f7517f18/download)

**Comment by sonntag-adam** [comment]
The spool file does not include STEM Scholarship Application submissions.

*INIT*
7272 DISABLED STEM 2

7272 DISABLED STEM 2
675893478
675893478
V1995

TEST
CH33
*START*
VA Form 22-1995
DEC 2016


            REQUEST FOR CHANGE OF PROGRAM OR PLACE OF TRAINING
      FOR VETERANS, SERVICEPERSONS & MEMBERS OF THE SELECTED RESERVE
                    -------------------------------------

                            APPLICANT INFORMATION
                            ---------------------

SSN: 675893478    VA File Number: N/A

Name:   7272 disabled stem 2 7272 disabled stem 2

Address:
TEST
TEST, SC, 29483
USA

Telephone Numbers:     Primary:
                       Secondary:

Email Address:  test@gmail.com
Preferred Method of Contact:

Direct Deposit:     Type of Account:
Name of Financial Inst.:
Routing/Transit #:    Account #:

                  TYPE AND PROGRAM OF EDUCATION OR TRAINING
                  -----------------------------------------

Type of Education or Training: College
Education or Career Goal:

New School or Training Establishment:
test


Current/Prior School or Training Establishment:


Date You Stopped Training:
Reason for Change:


                       ACTIVE DUTY SERVICE INFORMATION
                       -------------------------------

Date Entered   Date Separated     Service Component



          ENTITLEMENT TO AND USAGE OF ADDITIONAL TYPES OF ASSISTANCE
          ----------------------------------------------------------

For Active Duty Claimants Only. Are you receiving or do you anticipate
receiving any money (including but not limited to Federal Tuition Assistance)
from the Armed Forces or Public Health Service for the course for which you
have applied to the VA for Education Benefits?  If you receive such benefits
during any part of your training, check 'Yes.' Note:  If you are only applying
for Tuition Assistance Top-Up, check 'No' to this item.    N/A

For Civilian Employees of the U.S. Federal Government Only. Are you receiving
or do you anticipate receiving any money from your agency (including but not
limited to the Government Employees Training Act) for the same period for
which you have applied to the VA for Education Benefits? If you will receive
such benefits during any part of your training, check Yes.    N/A


                        MARITAL AND DEPENDENCY STATUS
           (For Applicants with Military Service Before Jan 1, 1977)
           ---------------------------------------------------------


N/A


      Certification and Signature of Applicant
Signature of Applicant                                               Date

      Certification for Persons on Active Duty
Signature/Title/Branch of Armed Forces Education Service Officer     Date

Electronically Received by VA:  2020-04-09
Confirmation #:  V-EBC-5

**Comment by sonntag-adam** [comment]
YTD report doesn't include 22-1995 STEM information. 


![Screen Shot 2020-04-10 at 7.57.05 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/5447d33a-80bd-427a-849a-4df90459a7fc)

**Comment by sonntag-adam** [comment]
All is behind the feature flag "edu_benefits_stem_scholarship	Enables STEM scholarship functionality"

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/280&group_by=cases:section_id&group_order=asc

**Comment by sonntag-adam** [comment]
In staging, 1995 form stem questions are removed, YTD submission does not have22-1995 STEM information and neither does spool file. Closing story.
