### ISSUE TITLE
[Discovery] Logged-in homepage: User research — Conduct interviews

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#7274]
## Background

Epic #7268

As part of the logged-in homepage discovery phase, we have decided to conduct user interviews/testing to help us better gauge user needs and expectations.

## Tasks

- [ ] Conduct user interviews

## Acceptance criteria

- [ ] All interviews have been completed

**Comment by andaleliz** [comment]
Completed 5/15/20
