### ISSUE TITLE
STEM: Create STEM Scholarship Application Infrasturcture

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#7275]
As a developer, I need to create the infrastructure to support the new OMB STEM Scholarship application so that it development can being once discovery and prototyping is complete.

## Assumptions:
1. This work is completed behind a feature flag (#7271)
2. This work is not enabled in production until the new STEM OMB form has successfully completed UAT.
3. The URL we create for this story will not be the final URL. Final URL will have to be approved by DEPO. The form name is currently 22-10203, so we can utilize the same form URL-naming we've used for other forms. 

## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
1. A copy of the 22-1995 is created in it's entirety.
2. The 22-1995 copy is accessible via a new URL/Route

**Comment by hughes-dustin** [comment]
branch: bah-7275
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/12102

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-04-06 at 12.09.49 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/c2bad9d4-fa9a-426f-9bb2-0fc82776d871)
##
![Screen Shot 2020-04-06 at 12.09.59 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/630de999-9a32-4f2e-86d4-295445092bf9)

**Comment by sonntag-adam** [comment]
In staging, closing story.
