### ISSUE TITLE
Adding [lisa.kahler@oddball.io] to DSVA Slack

### ISSUE THREAD

**Issue by Eallan919** [department-of-veterans-affairs/va.gov-team#72759]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

Please re-add Lisa Kahler to DSVA slack as she is Product Manager for IIR (CEDAR) TO 

Are you requesting to add an individual as a:

- Full member

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

We aim to complete slack requests within 24hrs.

## Sample Descriptions 

- Please add [[lisa.kahler@oddball.io](mailto:lisa.kahler@oddball.io) as a full member.

**Comment by LEHigley** [comment]
showing as a member
