### ISSUE TITLE
Midpoint Review - Design Feedback - Veteran Facing Forms - 20-10207

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#72766]
## VFS actions
- [x] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions
- Make sure you use v3 components where possible.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- **Must**: Take a look at your addition at info components. Per [our guidance](https://design.va.gov/components/additional-info#when-to-consider-something-else), you should not try to put multiple paragraphs inside Additional info. Link to another page, consider an [Accordion](https://design.va.gov/components/accordion), or shorten the content.
- Matt: Set a height on the "other" text box to allow more room.

**Comment by jeana-adhoc** [comment]
Follow up:
- We're [waiting on feedback on this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/72998) to find out how we should address the additional info component pattern we established for our team regarding more information for 3rd parties and POAs.
- We'll be adjusting the height of the text area via css for now.

**Comment by jeana-adhoc** [comment]
Closing this ticket as the issues have been addressed and will be incorporated as listed above.
