### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by dcloud** [department-of-veterans-affairs/va.gov-team#72769]
### Name

Daniel Cloud

### Email

daniel.cloud@adhocteam.us

### Role

FS Engineer

### Team

MHV Cartographers / my-health-CTO-HEALTH-TEAM my-health-INTEGRATION

### Product Manager (PM) name

Wesley Rowe

### Additional Notes

Seeking _Viewer-restricted_ role. Thank you!

**Comment by dcloud** [comment]
Misread PM as PO, corrected to "Wesley Rowe" as PM, not Patrick Bateman.

**Comment by naomimarcussen** [comment]
An invite has been sent.

**Comment by dcloud** [comment]
Received and accessed. Thank you!
