### ISSUE TITLE
Adding steven.long@adhocteam.us to DSVA Slack

### ISSUE THREAD

**Issue by Eallan919** [department-of-veterans-affairs/va.gov-team#72760]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

Please re-add Steven Long back into DSVA slack as he is an engineer on IIR (CEDAR) TO

Are you requesting to add an individual as a:

- Full member

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

We aim to complete slack requests within 24hrs.

## Sample Descriptions 

- Please add [[steven.long@adhocteam.us](mailto:steven.long@adhocteam.us) as a full member.

**Comment by LEHigley** [comment]
showing as a member
