### ISSUE TITLE
DEV Team Onboarding: Complete Lightkeeper/k8s Setup

### ISSUE THREAD

**Issue by rdvyas** [department-of-veterans-affairs/va.gov-team#72776]
As part of our ability to work in LHDI we need to setup a couple of toolsets:

1. Lightkeeper - LHDI CLI tooling, acts as a wrapper around specific LHDI services
2. kubectrl - kubernetes control plane, allows us to interact with k8s services (spin up VMs, dbs via RDS etc)

The steps to setup these tools are included in the link below:
https://laughing-adventure-wllepqe.pages.github.io/Getting-access/Onboarding-to-DI/

Below are some notes from Rahul's experience setting up these tools. There is a high likelyhood that the team will run into the same issues:
# Deployment
https://laughing-adventure-wllepqe.pages.github.io/Getting-access/Onboarding-to-DI/
1. Sertup PAT in GH: 
[Managing your personal access tokens - GitHub Docs](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens)
1. Set Env variable in PSH: `$env:AZURE_RESOURCE_GROUP = 'NewResourceGroup'`
2. Update install.ps1 with the following:
https://stackoverflow.com/questions/38005341/the-response-content-cannot-be-parsed-because-the-internet-explorer-engine-is-no
4. You may run into an issue trying to create the kubectrl config file. You may need to print the config to the commmand line and copy over instead of using the file porting command.

**Comment by SophiaPhilipMO** [comment]
Huddle scheduled
Have access to Vinay if any questions and Rahul help if needed

**Comment by moanu404** [comment]
Working session finished and lightkeeper onboarding is complete as outlined here https://laughing-adventure-wllepqe.pages.github.io/Getting-access/Onboarding-to-DI/ 

kubectl get namespaces now works
