### ISSUE TITLE
"Creating a new React widget" documentation feedback

### ISSUE THREAD

**Issue by cosu419** [department-of-veterans-affairs/va.gov-team#72786]
### Description
For a new VFS team, the documentation for [Creating a new React widget](https://depo-platform-documentation.scrollhelp.site/developer-docs/creating-a-new-react-widget) was somewhat confusing. The first step involves config on a markdown page, of which we have vanishingly few now. 

In case anyone sees fit to update the docs, here were my steps for creating a widget. Our team is new, so these steps should be reviewed for accuracy. 

### Creating a new React widget
1. Add widget of `widgetType: “my-widget-name”` to `src/applications/registry.scaffold.json`:   
```
{
    "appName": "My Application",
    "rootUrl": "/my-root-url",
    "widgetType": "my-widget-name"
}
```
2. Add `MY_WIDGET_NAME` type to `src/applications/static-pages/widgetTypes.js`. 
  `MY_WIDGET_NAME: 'my-widget-name',`
 
3. If it doesn't already exist, create `src/applications/static-pages/my-feature` for housing (and testing) component logic. Within `my-feature` you may define your own folder structure, but one common pattern is `my-feature/components/App`.
4. Add start up function to `src/applications/static-pages/my-feature/index.js`:
```
export default (store, widgetType) => {
  const root = document.querySelector(`[data-widget-type="${widgetType}"]`);
  if (root) {
    import(/* webpackChunkName: "my-widget-name" */
    './components/App').then(module => {
      const App = module.default;
      connectFeatureToggle(store.dispatch);

      ReactDOM.render(
        <Provider store={store}>
          <App />
        </Provider>,
        root,
      );
    });
  }
};
```
5. Import and run `createMyWidgetName` in `src/applications/static-pages/static-pages-entry.js`:
`createMyWidgetName(store, widgetTypes.MY_WIDGET_NAME);`

6.  The widget may be added as a mount point element in a static content page like so:
`<div data-widget-type="my-new-widget" id="someId"></div>`

NOTE: Generally the Sitewide CAIA team is responsible for adding react widgets to a Drupal page. They will need to be provided with the widgetType defined in Step 1. 

### Relevant URLs
https://depo-platform-documentation.scrollhelp.site/developer-docs/creating-a-new-react-widget

### Which type of team are you on? (Platform team, VFS team, or Leadership)
VFS team

**Comment by johnny-jesensky-adhoc** [comment]
Hi @cosu419, thanks for reaching out and for providing this feedback and suggested changes to this section. We'll connect with some engineers who can review this for accuracy, and then work to make any needed updates to this page on the Platform Website.

We'll provide further updates in this ticket. Let me know if you have any further questions - thanks!

**Comment by laucon** [comment]
@cosu419 I'm working on this and I have 2 questions.
1. Should this process be added to the other processes on [Creating a new React widget](https://depo-platform-documentation.scrollhelp.site/developer-docs/creating-a-new-react-widget) or should it replace a current process on that page?
2. What should this process be titled? The document itself is called "Creating a new React widget." Should this specific process also be called "Creating a new React widget?" I'm under the assumption that we should add this process to the [Creating a new React widget](https://depo-platform-documentation.scrollhelp.site/developer-docs/creating-a-new-react-widget) instead of creating a brand new document, but I'm not sure if that's correct.

**Comment by laucon** [comment]
@cosu419 Hello again. I talked with an engineer, Ryan Smith, who answered the questions I had above and checked your process and your code. I'll be able to edit the document on Monday and deploy shortly after. Thanks so much! We really appreciate your help with keeping this document up to date and we especially appreciate all the time you took to write out that process so thoroughly. :)

**Comment by cosu419** [comment]
Hey @laucon, just now catching up on this - glad you got the info you needed! Have a great weekend.

**Comment by laucon** [comment]
@cosu419 awesome, thank you. I edited the document and it should be deployed today at 3:30pm. If you have any additional edits to add after that, feel free to let us know. The document didn't really have an intro explaining exactly what the document was and what the document was trying to reach users to do. So I asked Ryan if he could provide that. But maybe you can provide that too. Can you sum up the process above in a sentence or two in terms of what it does or what you're showing users to do, exactly?

**Comment by cosu419** [comment]
Hey @laucon, +1 to that phrasing. Had I stumbled upon that description while I was searching through the documentation, it would have certainly clicked for me. I'll say it's accurate!

**Comment by laucon** [comment]
Awesome!
