### ISSUE TITLE
Planning for listening session with Marty and representives

### ISSUE THREAD

**Issue by uxrebecca** [department-of-veterans-affairs/va.gov-team#72787]
**Description**
Marty Caraway, VSO Liaison within VBA, let us know he is organizing a listening session with accredited representatives for January 23. Our understanding is the goal is to hear about concerns, which will help us prioritize our work. This is also an opportunity to build a participant/advisory panel with representatives from a variety of backgrounds.

Zach Goldfine was invited, and Marty said he would connect with Zach about how we can participate. 

**Acceptance criteria**

- [x] Confirm date, time, location for listening session
- [x] Confirm how we can/will participate (e.g. write questions, present on our work/share info about ARF so far)
- [x] Confirm who from ARF will be attending

**Comment by uxrebecca** [comment]
Marty got back to us quickly once I emailed him. Has been rescheduled to January 23rd and we are invited! Will be in Microsoft Teams. There are about 50 people on the invite list.

Title of meeting: VSO Listening Session- Technology Modernization

Description: 

VBA is excited to hear from our VSO, State, and private bar partners on current state of technologic tools and updates needed as we draw nearer to the sunsetting of Stakeholder Enterprise Portal.  Please be prepared to discuss your organizations dependency on SEP, critical functions it performs that need to duplicated and other tools your organizing would like VA to explore for system and advocacy efficiency.

**Comment by RivkaCGates** [comment]
Did this ever go into the backlog? This ticket isn't pointed. Please make sure I'm aware when things get pulled in, especially if they are just created.

**Comment by uxrebecca** [comment]
I tagged you on Slack about this yesterday and you said it was ok to pull in. [See Slack thread.](https://dsva.slack.com/archives/C05SUUM4GAW/p1704232273893179?thread_ts=1704222051.802039&cid=C05SUUM4GAW)

**Comment by RivkaCGates** [comment]
Apologies Rebecca - I was just confused since I didn't see it come through the backlog. All good. My apologies for the confusion.

**Comment by RivkaCGates** [comment]
suggestion on pointing? @uxrebecca @RenataKeck @karafaithsanchez

**Comment by uxrebecca** [comment]
Agreed, 3 seems reasonable. If we are being active participants/organizers we can probably break it up, but right now all we know is we're attending. I have an email out to Marty to ask about if he'd like us to present anything, introduce ourselves, etc.

**Comment by RivkaCGates** [comment]
I'm going to go ahead and point it that way

**Comment by uxrebecca** [comment]
I sent Marty and email last week with specific questions around recording the session, notetaking during the session, and how we could participate (presenting/facilitating feedback, etc.). He was out of office until today so hopefully will hear back soon.
