### ISSUE TITLE
Port over FE business logic (calculateIncome.js)

### ISSUE THREAD

**Issue by kjsuarez** [department-of-veterans-affairs/va.gov-team#72789]
As we approach FSR 3.0 the BE intends to take responsibility for as much FSR business logic as possible.

Port the logic in vets-website file _src/applications/financial-status-report/utils/calculateIncome.js_ into a service on the BE and expose it as an endpoint.

**Comment by HeatherRienks** [comment]
Per Austin, waiting on Platform to review (they mentioned it would be last week- still waiting)
