### ISSUE TITLE
SiS documentation improvements part 2

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#72793]
# Description
Slack thread: https://dsva.slack.com/archives/CSFV4QTKN/p1704927279688219

# Documentation Improvements
- [ ] reporting directory
- [ ] adding-new-app-environments
- [ ] errors improvements 
  - [ ] audit & update `vets-api` internal/general errors
    - [ ] csp specific?  
  - [ ] errors are all 400s - potential to update error codes to be more informative?
  - [ ] move full error descriptions to individual endpoint pages? duplicate?
  - [ ] errors to add
    - [ ] introspect
    - [ ] logout
    - [ ] revoke
    - [ ] revoke_all
 - [ ] auth_flow diagrams
   - [ ] private_key_jwt
     - [ ] sequence diagram
     - [ ] technical diagram
   - [ ] service_account
     - [ ] sequence diagram
  
# VA Identity Postman

- [ ] ssoe auth & token management in vets-api
- [ ] add ToU routes to vets-api
- [ ] error responses
- [ ] collection notes (mainly point to documentation)
- [ ] links to documentation & instructions within each request
- [ ] host online/postman web client identity postman collection?
- [ ] update SiS Postman guide document (postman.md)
- [ ] ability to hold different va_gov_access_tokens for SiS, vets-api, IDD

**Comment by parkerbees** [comment]
moved to jira, closing
