### ISSUE TITLE
[AXE-CORE]: Outreach materials -- heading semantics

### ISSUE THREAD

**Issue by peterhill-oddball** [department-of-veterans-affairs/va.gov-team#728]
## Issue

The following h3 element is not preceded by h2. 

`<h3 class="asset-body-header vads-u-margin-y--1" id="va-home-loan-guaranty-informat">
                      VA Home Loan Guaranty Information</h3>`

## Point of Contact

Peter Hill

## Acceptance Criteria

As a screen reader user, I want to have semantically correct ordering for the headings in order to navigate the page without issue.

## Environment

Windows 10 b1903
Chrome Version 75.0.3770.142
https://staging.va.gov/outreach-and-events/outreach-materials/

## Steps to Recreate
Axe analysis of: https://staging.va.gov/outreach-and-events/outreach-materials/

## Possible Fixes (optional)
Consider changing h3 elements to h2 elements instead and apply the same styling to h2s.

## WCAG or Vendor Guidance (optional)

None

## Screenshots or Trace Logs

N/A

**Comment by jefflbrauer** [comment]
@1Copenut This fix is now on staging. please go ahead and retest.
https://staging.va.gov/outreach-and-events

**Comment by 1Copenut** [comment]
Reviewed and verified on Staging. Moving to close.
