### ISSUE TITLE
Backend Orientation - January 2024

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#72808]
## User Story
As a Platform team member supporting Platform Orientation, I want to host, record, transcribe and share the Backend Orientation session so that VFS team members are able to be easily oriented to the VA.gov Platform. 

## Description
Platform is responsible for hosting the Platform Orientation sessions once every quarter. These sessions are recorded and shared on Platform Website.

The Backend Orientation for FY24-Q2 is January 24 at 4:00pm ET.

## Impacted Artifacts
[Orientation Host/Zoom Host Guidance](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2656731745/Orientation+Host+Zoom+Host+Guidance)

### Zoom host (Clint)
- [ ] Ensure Zoom settings are set according to the guidance: [Orientation Host/Zoom Host Guidance](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2656731745/Orientation+Host+Zoom+Host+Guidance) / Before you start your session / Zoom settings
- [ ] After the session has been hosted, forward the Zoom recording to the Instructor/Session host
### Instructor/ Session host (Rebecca)
- [x] Review the guidance in the [Orientation Host/Zoom Host Guidance](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2656731745/Orientation+Host+Zoom+Host+Guidance) for During your orientation session
- [ ] Host the orientation session as scheduled
### All the other stuff (Rebecca)
See **After your session** section of [Orientation Host/Zoom Host Guidance](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2656731745/Orientation+Host+Zoom+Host+Guidance)
- [ ] Download mp4 and vtt files from Zoom recording
- [ ] Clean up the transcript
- [ ] Upload recording and transcript to YouTube
- [ ] Change visibility of previous recording to Private (if applicable)
- [ ] Update video link on Platform Website

## Acceptance Criteria
- [ ] The live Accessibility Orientation for the quarter has taken place
- [ ] VFS team members are able to view the latest recording of the orientation session

**Comment by shiragoodman** [comment]
thanks for letting me know! This is good data to support ending the live sessions. Thanks again @rmtolmach !
