### ISSUE TITLE
GHA to seperate multiple environment modifications in Manifest Repo

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#72800]
Create a Github Action to separate production changes from lower environments. This will prevent a breaking change from going out to prod before testing in a lower environment. This also forces prod vs lower env PRs to b individual units and make sure the code from the lower environments don't cause anything to break before moving on to each higher environment.

**Comment by jennb33** [comment]
In Grooming & Pointing, it was determined that this work has already been completed [here](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/main/.github/workflows/force-separate-prod-vs-lower-env-prs.yaml) so this ticket can be closed.
