### ISSUE TITLE
Open technical discovery questions: 1010-D Pega/Daper migration from Benefits Intake API

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#72804]
Currently, all digital forms use the benefits intakes api for pdf transmissions.  API first provides an upload location and unique submission identifier, and then accepts a payload consisting of a document in PDF format, zero or more optional attachments in PDF format, and some JSON metadata. We try to validate (optional) the zipcode,fileNumber, veteranFirstName, veteranLastName and businessLine fields before submission according to their description in the DocumentUploadMetadata model and use the 'businessLine' attribute for the most efficient processing.

Questions we have are:
1. How will we validate the PDF submissions? 
2. What will be the Authentication and Authorization method for the api endpoint?
3. Will there be a sandbox environment?
4. Can we have test data? (To do: example of what we want here?)
5. Are there any file size limits for the PDF and attachments?
6. We will need a return receipt, for messages example: received, processing, success, or vbms. If the document status is error, VA has not received the submission and cannot honor the submission date as the date of receipt.
7. Will there be any status caching?

**Comment by marywang2** [comment]
@baltes do you want to make this one an epic - trying to sort through back end tickets.

**Comment by baltes** [comment]
Reassigning this to myself and converting to an epic.
