### ISSUE TITLE
January Medallia feedback report

### ISSUE THREAD

**Issue by charlottecesana** [department-of-veterans-affairs/va.gov-team#72815]
### Issue Description

Monthly reporting on Medallia satisfaction data.
Monthly reports can be found in [this folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/combined_fsr/research/medallia_reports)

### What work is necessary for this story to be completed?

- [x]  Request monthly data for FSR
- [x]  Request monthly data for the debt portal
- [x]  Review data reports
- [x]  Extract meaningful data to include in a report
- [x]  Document on Github

### What will be created or happen as a result of this story?

- [x]  Request data reports
- [x]  Review data reports
- [x]  Extract meaningful data to include in a report
- [x]  Report on Github for FSR
- [x]  Report on Github for the debt portal

**Comment by charlottecesana** [comment]
[Debt Portal and FSR Dec + January 2024 Medallia report ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/combined_fsr/research/medallia_reports/medallia-december-january-2024.md)is complete. 
Moved ticket to validate.

@denisecoveyduc @Tom-Davis @HeatherRienks

**Comment by Tom-Davis** [comment]
Closing as all work is complete.
