### ISSUE TITLE
Toxic Exposure: Add to submit (placeholder/notes)

### ISSUE THREAD

**Issue by christinec-fftc** [department-of-veterans-affairs/va.gov-team#72816]
Pending completion of LH submit endpoint and FE work, add in logic to handle TE data for submission.

## Logic to be added ##
- for any new conditions that were selected on the toxic-exposure-conditions page, `disabilities[n].isRelatedToToxicExposure` flag is set to `true` 
- if `disabilities[n].isRelatedToToxicExposure` is set for any new conditions, `toxicExposure` object is included in submit
- if veteran selects a TE condition, but does not fill out any of the TE questions, make sure we send empty object and submit does not fail LH validation
- use the selected radio button's labels from the `new-disabilities/add` page to set on the `disabilities[n].exposureOrEventOrInjury` ~OR `[n].secondaryDisabilities[m].exposureOrEventOrInjury`~
-if "I'm not sure" is selected on any pages, do not include in submission

**Gulf War (15B)**
- if veteran selects at least one gulf war location, set `gulfWarHazardService.servedInGulfWarHazardLocations` to `YES`. 
- if veteran selects 'None of these locations' set to 'NO'
- if veteran does not select any locations, leave the yes/no answer empty
- do not populate `gulfWarHazadService.serviceDates` (this will go in multiple exposures to preserve the location + dates association)
- for each location and optional date range, add to `toxicExposure.multipleExposures` 

**Herbicide (15C)**
- if veteran selects at least one herbicide location, set `herbicideHazardService.servvedInHerbicideHazardLocations` to `YES`. 
- if veteran selects 'None of these locations', set to `NO`
- if veteran does not select any locations, leave the yes/no answer empty
- do not populate `herbicideHazardService.serviceDates` or `herbicideHazardService.otherLocationsServed`
- for each location (including OTHER) and optional date range, add to `toxicExposure.multipleExposures` 

**Additional hazards (15D)**
-for any selected hazard(s), set in `additionalHazardExposures.additionalExposures` 
-for other exposure input text, set in `additionalHazardExposures.specifyOtherExposures`
-do not populate `additionalHazardExposures.exposureDates` or `additionalHazardExposures.specifyOtherExposures`
-for each hazard (including OTHER) and optional date range, add to `toxicExposure.multipleExposures` 

**Multiple Exposures (15E)**
-For overflow of 15B and 15C, do not populate `hazardExposedTo`
-For overflow of 15D, do not populate `exposureLocation`

## Tasks ##

- Modify 526 schema in `vets-json-schema`
- Handle data coming from FE and process/format according to LH spec for submit
- Unit Tests

## Acceptance Criteria ##
- Successful 526 submission with Toxic Exposure section
- TBD: Submission found in VBMS UAT with PDF filled out for TE

**Comment by christinec-fftc** [comment]
Relevant [slack thread](https://dsva.slack.com/archives/C02CQP3RFFX/p1704230272489469) with mocks/examples

**Comment by alatempa24** [comment]
closed as duplicate

**Comment by christinec-fftc** [comment]
This logic was implemented in various BE tickets. However, it was super helpful as a reference in one place and to make sure we didn't forget any of these items. It did its job 👍
