### ISSUE TITLE
DSLogon Downtime Banner Check

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#72814]
### User Story:
As an Identity Team Member, I want to understand how the DSLogon downtime banner works on VA.gov, specifically in relation to muting Datadog alerts during off hours. Additionally, I would like recommendations on how to ensure that the downtime banner is shown even if the alerts on Datadog are muted.

### Acceptance Criteria:
The document should provide a clear explanation of how the DSLogon downtime banner is triggered and displayed on VA.gov.
The document should address whether muting Datadog alerts during off hours affects the display of the downtime banner on VA.gov.
If muting Datadog alerts does prevent the downtime banner from being shown, the document should provide recommendations on alternative methods to ensure the banner is displayed.

### Concerns
1. Some engineers are still being paged when DSLogon is down during non-working hours. DSLogon is down quite often and there isn't anything VA.gov can do. As an understood work around, users can use one of the other three credentials. With this workaround we do not need to respond to a DSLogon outage that occurs outside of a planned deployment by VA.
2. We also must ensure users of VA.gov are informed that DSLogon is down by showing the downtime banner on the login modal when DSLogon is in fact down.

**Comment by parkerbees** [comment]
Moved to Jira. Closing.
