### ISSUE TITLE
CT: Update link in "Learn more about these warnings" modal on profile page

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#7281]
As a user of the GI Bill Comparison Tool, I need to understand all of the caution flags an institution can have so that I can make the best decision regarding how to use my education benefits. 

## Assumptions
1. This work will be completed behind a prod flag so that upon merge it is only available on staging. 
2. Production flag for this work is covered in #7280 
2. This work updates the work completed in #6848 which has not yet been released to production. 

## Acceptance Criteria:
1. In the "Cautionary information" section of the Profile Page, a user selects the "Learn more about these warnings" link. 
a. A modal appears and includes following link to "Suspension of VA Benefits to Five Schools for Deceptive Practices", which is included above "heightened cash monitoring" in the modal: https://www.benefits.va.gov/gibill/comparison_tool/about_this_tool.asp#suspension
![Screen Shot 2020-03-13 at 1.34.11 PM.png](https://images.zenhubusercontent.com/5b645f6fe2255460d8f0b032/1ee8745f-ab52-4a01-8fd5-5cfb3acdae57)

## Supporting Artifacts
1. NA

**Comment by sonntag-adam** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/12038

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/242&group_by=cases:section_id&group_order=asc

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-03-30 at 6.52.06 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/467dcf26-587d-4919-8bd3-d33dc88e5c8e) shows and navigates to https://www.benefits.va.gov/gibill/comparison_tool/about_this_tool.asp#suspension

**Comment by sonntag-adam** [comment]
Does not show in production build
![Screen Shot 2020-03-30 at 7.05.53 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/d5d7f165-37ca-4929-9a50-d7cbd11ca804)

**Comment by sonntag-adam** [comment]
In staging. Testing passes QA. Closing story.
