### ISSUE TITLE
Add an allDemographicsCurrentUUID Mock UUID for check-in

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#72829]
## Description 

When running app locally, would like to be able to run an an `allDemographicsCurrentUUID` mock UUID for check-in. 

## Tasks

- [ ] Create mock
- [ ] [Add to Git repo](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/check-in#check-in)

## AC

- [ ] Mock works
- [ ] Mock UUID added into Git repo

**Comment by loripusey** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/72829?planning-poker) with Zenhub @wullaski @brianseek

**Comment by loripusey** [comment]
@brianseek @wullaski can you point this one please?

**Comment by brianseek** [comment]
I added my poker estimate, but I'll let John set the actual points here since he already finished the work

**Comment by wullaski** [comment]
I added my estimate.

**Comment by loripusey** [comment]
validated
