### ISSUE TITLE
Midpoint review - Content - Veteran Facing Forms - 20-10207

### ISSUE THREAD

**Issue by rferguson13** [department-of-veterans-affairs/va.gov-team#72825]
## VFS actions
- [x] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [x] Comment on this ticket:
  - [x] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [x] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [x] Close the ticket when all feedback has been addressed.

## Thoughts
Overall, this looks really good! Mostly small typos and some consistency issues. Please let me know if you have any questions. 

### Must
- Page 1.2.2 - The user is asked to input their SSN or VA Insurance File Number. The capitalization for “Social Security number” and “VA Insurance File Number” is inconsistent across the different fields/explanations. Please revise so the capitalization is consistent and correct. For example, “Social Security” should have both words capitalized whereas “VA file number” is what is used in the [Design System](https://design.va.gov/patterns/ask-users-for/social-security-number).
- 2.2.2; 2.5.2; 3.2.2 - The user finds a field labeled “Social security number.” This capitalization is incorrect; “Security” should also be capitalized. Please revise so the field label is “Social Security number.”
- 1.3.1; 2.3.1; 3.3.1; 4.3.1 - The user is given a list of potential living situations. One of the options is: “In the next 30 days, I will lose my home…” There’s then a note in parentheses. There is no closing parenthesis at the end of the option. Please revise so there is a closing parenthesis after “motel.”
- 1.3.1 Mobile - The text of the mobile experience doesn’t match the text of the desktop experience. Please revise so that both these experiences match the desktop text. 
- 3.3.1; 4.3.1 - The user is given a list of potential living situations. The first option reads as: “The Veteran lives or sleeps } overnight in a place…” There is a random bracket in the text. Please revise by removing the bracket.
- 3.4.2. Mobile - The user is asked to input their phone number and email address. The H3 in the mobile app reads as “Veteran’s hone and email address.” Please revise the typo so the heading reads as: “Veteran’s phone and email address.”
- 1.5.1 - The user finds the following heading: “Which of these descriptions are true for you?” There is a noun/verb agreement error here. Please revise so the heading is: “Which of these descriptions is true for you?” 
- X.6.3.1 > What kind of evidence can I submit? - The user finds the following sentence: “Copy of medical evidence showing ALS also known as Lou Gehrig’s disease diagnosis.” This sentence is missing commas that enhance clarity. Please revise so the sentence reads as: “Copy of medical evidence showing ALS, also known as Lou Gehrig’s disease, diagnosis.
- X.6.4.1 > What kind of evidence can I submit? - The user finds examples of evidence they can submit. According to the information given, the user needs to submit both their military personnel records and medical evidence. According to the [Style Guide](https://design.va.gov/content-style-guide/bold-text), when a list has an “and, or” component, it should be bolded for clarity. Please revise by bolding the “and” at the end of the first bullet.
- X.6.5.1 > End of confinement - The user is asked to input their end of confinement date. However, the explanation currently reads as: “Tell us the dates…confinement began as a prisoner of war.” Please revise so the sentence reads: “...confinement ended as a prisoner of war.”
- X.6.5.1 > What kind of evidence can I submit? - The user finds two bullet points that outline the kinds of evidence that can be submitted. The end of the first bullet ends with the word “or.”  According to the [Style Guide](https://design.va.gov/content-style-guide/bold-text), when a list has an “and, or” component, it should be bolded for clarity. Please revise by bolding the “or” at the end of the first bullet.
- x.6.6.1 - The user finds the following sentence: “Do you have documentation you would like to submit as evidence of a Medal of Honor or Purple Heart Award?” “Award” shouldn’t be capitalized in this context. Please revise so the text reads as: “...Medal of Honor or Purple Heart award?”
- x.6.6.1 > What kind of evidence can I submit? - The user finds two bullet points that outline the kinds of evidence that can be submitted. The end of the first bullet ends with the word “or.”  According to the Style Guide, when a list has an “and, or” component, it should be bolded for clarity. Please revise by bolding the “or” at the end of the first bullet.
- 3.7.1; 4.9.1- The user can input the names and addresses of treatment facilities. These specific pages differ from the other pages in that it has the following sentence: “You may add up to five facilities.” Please revise so that all of the information is consistent across the different user stories (e.g. the claimant and the Veteran use cases). 

### Should
- 1.7.1 - The user finds a field with the following description: “Approximate beginning date of treatment.” This wording is slightly awkward and wordy, mostly because “beginning” is used instead of “start.” This should be revised so the field reads as: “Approximate start date of treatment.”

### Consider
- 1.2.2 - The user is asked to input some identification information - either an SSN or a VA file number. However, there are two fields under the VA file number prompt; one for the VA file number and the other for the VA Insurance file number. Consider adding “VA Insurance file number” to the explanation to avoid potential confusion. There are several ways the writer could do this. For example, they could write: “You must enter either a VA file number, a VA insurance file number, or a Social Security number.”
- 1.3.1; 2.3.1; 3.3.1 - The user can input their current living situation if none of the listed housing risks apply to them. However, there is a 100-character limit. A 100-character limit seems short to explain a housing risk. Consider expanding the character count so that the user can better describe their situation. 
- 0.0; 1.5.1; 2.7.1; 3.5.1 - The user finds a list of descriptions and is asked if any apply. One of the descriptions is “I’m a former prisoner of war.” Consider adding “(POW)” to the end of this description so it reads as “I’m a former prisoner of war (POW).”

## Notes
Thank you again for the opportunity to review your work. As stated above, if you have any questions about this feedback, please let me know. If you have additional content development needs for this form, please continue working with CAIA. Great work!

**Comment by jeana-adhoc** [comment]
These items have been updated in our [sketch](https://www.sketch.com/s/beba0073-a7e5-4aee-af97-593add9a93fb/p/A27922EE-9454-4E28-A70C-1512F5CAD1D9/canvas) and [source of truth](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/20-10207%20Priority%20Processing/source-of-truth-condensed.md) documents.
