### ISSUE TITLE
EYB: Research and Document Input Fields

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#7282]
As a developer, I need to research and document the variables and formulas used on the profile Estimate your benefits section so that the development team has a complete understanding of how the section works.

## Assumptions:
1. N/A

## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
1. Documentation is created outlining the inputs that affect each of the amounts listed in the EYB section (Supporting Artifact # 3)
     a. Amounts include: (include all amounts or screenshot of the section)

## Supporting Artifacts:
1. [Sample Documentation.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4389829/Sample.Documentation.xlsx)
2. Technical Research & Documentation:
[calculator_logic (1).txt](https://github.com/department-of-veterans-affairs/va.gov-team/files/4394279/calculator_logic.1.txt)
3. 
<img width="357" alt="EYB" src="https://user-images.githubusercontent.com/48260534/77920304-510c0c80-726c-11ea-93a7-804152243943.png">

**Comment by dmccurdybah** [comment]
Here's the list of fields and their related input fields.

[https://app.zenhub.com/files/133843125/a28a70d6-5e56-46ad-a6eb-44a391240520/download](https://app.zenhub.com/files/133843125/a28a70d6-5e56-46ad-a6eb-44a391240520/download)
