### ISSUE TITLE
Midpoint Review - IA Feedback - Veteran Facing Forms - 20-10207

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#72833]
## VFS actions
- [x] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- I really appreciate the thoughtfulness of options on the homelessness question. I hope that this is something we can add to our design system patterns library.
- Y'all laid out a complex flow really clearly. No showstoppers from me - thanks as always for your engagement with the collab cycle!

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

### Must

- **IA placement and breadcrumbs**: Please continue to work with Jenny in CAIA to clarify IA placement, potential entry points for this form, and what the breadcrumbs should display.
- **Click vs select language:** The [Other reasons for request screen](https://www.sketch.com/s/beba0073-a7e5-4aee-af97-593add9a93fb/a/uuid/024C9E45-A783-4306-B8D4-D2DA396E20F8) instructs users to click continue, but not all users will be using a mouse. The language should say “select” or something device-agnostic.
![Screenshot 2024-01-02 at 11 19 18 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/755248/a26c11ae-2cac-45c5-a2b4-3be0737a13e5)

- **Evidence submission pages: ULs in additional info components**: the text in the additional info components on the [evidence submission pages](https://www.sketch.com/s/beba0073-a7e5-4aee-af97-593add9a93fb/a/uuid/A60D1565-38FC-47EA-B74D-21C1D3997E86) should be UL's rather than typing out bullets. **Edited to add**: This is a limitation of Sketch and Jeana has indicated this'll be a `ul` in production.
![Screenshot 2024-01-02 at 11 37 27 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/755248/2892079f-76f3-4a92-b9bf-52a6ca92ae95) 

### Should

- **Phone number required?**: We chatted about this a bit on our call. Could it be a blocker for users if the Veteran does not have a phone number? This caught my eye because we are careful to ask Veterans if they have an address, but don't offer an out if they do not have a phone number. Should this information be required, or strongly suggested? If it doesn't need to be required, maybe we could add some language to the effect of, "If you include a phone number or email we can respond more quickly."
- **VA Insurance number required for all cases?**: for two of the four stories, the [veteran info screen](https://www.sketch.com/s/beba0073-a7e5-4aee-af97-593add9a93fb/a/uuid/F1B3227C-06BF-44D2-87C5-6319743161C0) does not ask for VA insurance file number, while in the two other stories, it does ask for the insurance file. Should it be appearing for all use cases?
- **Visibility of "none" option for homelessness question**: I am wondering about the visibility/ease of finding the "none of the above" option for the homelessness question. While I think the expanded detail in the revised answers is crucial, it might make the "None of these apply to me" option harder to find quickly. There are a couple of ways to approach a solution to this - just wanted to note it as a potential slow-down or blocker for Veterans or Claimants who are not experiencing issues with housing.

### Consider

- **Confirmation page - hyperlink homelessness help line** On the confirmation page, we helpfully list the phone number for the National Call Center for Homeless Veterans. If possible, please hyperlink it as we hyperlink phone numbers in the Need Help? section.
<img width="671" alt="Screenshot 2024-01-03 at 11 23 00 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/755248/e417ae67-8c5c-4eec-87d7-102b5cceca04">

**Comment by jeana-adhoc** [comment]
### Issues still pending:

- **Phone number:** We need to talk with our stakeholder to confirm what happens if there is NO contact information submitted in the form, then we can work with CAIA to write content to match that. But for now, we'll leave the phone number as required. But we're working towards trying to find a way to make the phone not required.
- **Breadcrumbs** We're still waiting on the IA spec from CAIA. The request was submitted sometime ago. Once I have that, I'll update sketch/figma.

### Updates Made:
**Insurance number**: We've simply removed it from the digitized process all together. It's not required and rarely used.
**None option on homeless question:** With moving the conditionally revealed question to its own page, this allows the 'none" option to be last, which I think is where you'd expect a "none of these" option to be. I'm also working with developers to have an error message so that if none and another option are checked, the user is notified that they must clear one of them to continue on.
**All other issues:** addressed as suggested.

**Comment by jeana-adhoc** [comment]
Closing this ticket as the issues have been addressed and will be incorporated as listed above.
