### ISSUE TITLE
[PM/Team] 10-10EZR - Failure Notifications: Coordinate with VA Notify to send submission failure emails to Veterans

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#72846]
## Background
We currently do not have anything set up to email Veterans when their application fails all submission retries.  We need to engage VA Notify to set up this function, as the target state system for emails to Veterans.

<details>
<Summary>Below are the questions that need to be completed in the Intake Ticket. (click here to expand)</Summary>

## Notification Details
1.  **Notification type**
     - email
​
2.  **Please describe your use case.**
     - For the 10-10EZR, we currently do not use any system to send emails to Veterans, informing them that their application was not submitted successfully, We would like to use VA Notify for the submission failure emails sent to Veterans.
​
4.  **What actions can the user take based on the notification they receive?**
    (ex., view secure messages, fill out a survey, schedule an appt, etc.)
​
5.  **What is the desired business outcome?**
     - Utilizing target state notification platform
​
6.  **What system will kick off the notification? Please note the system should be inside the VA or have an ATO.**
    (ex., BVA hearing reminders are kicked off from Caseflow)
​
7.  **What will trigger the notification?**
    (ex., clicking submit, status updates for claims, appointment reminders, new services available)
​
8.  **Provide sample content per notification type, if you have it.**
    Please note we collaborate with all of our users on their content to ensure it meets standards.
​
9.  **Has a Privacy Officer (PO) seen and approved the content? If not, do you know who your PO is?**
    (ex., PO has seen the content but it is not approved)
​
10.  **Would you prefer to provide contact information for the recipients or would you rather VA Notify look this up for you by Veteran ID? If by ID, please let us know what identifier is used in your system.**
    (ex., VAPROFILEID, PID, BIRLS, ICN, etc.)
​
11.  **Do you currently capture communication preferences related to this notification? If so, please describe.**
    (ex., opt in for claim status updates via email or text)
​
12.  **What is the anticipated volume of notifications per day, week, month?**
​
13.  **When does this notification need to be in production?**

</details>

## Tasks
- [ ] Gather data for each of the questions above
- [ ] Complete [VA Notify intake ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=bevnobev%2C+mjones-oddball&labels=vanotify-intake&template=VANotify-Business-Intake.md&title=Business+intake+form+for+%5BBusiness+or+team%5D) with the answers to those questions

## Acceptance Criteria
- VA Notify is engaged to start the process of sending our submission failures emails to Veterans

**Comment by coope93** [comment]
Some info that may be helpful for this work. We can add a new template in our existing `1010 Health Apps` service in VA Notify and use the same api_key as we are with the 1010 EZ form failure submissions. From there it should be very similar to how we are using the VANotify service in https://github.com/department-of-veterans-affairs/vets-api/pull/17061.
