### ISSUE TITLE
[QA] 10-10EZR Emergency Contact: TEST EC

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#72844]
As a Veteran, I would like to be able to 

- [x] Write test cases based on the working UI and designs
- [x] Complete testing
- [x] Document bugs and inform Engineers
- [ ] ~~Retest if needed~~ Ticket created for retest once the issues are fixed: [98344](https://github.com/department-of-veterans-affairs/va.gov-team/issues/98344)
- [x] Conduct regression testing
- [ ] ~~Conduct E2E testing with VES team~~ this cannot be done yet as the backend service is not ready yet
- **Success: EC on EZR is thoroughly tested and ready for Prod**
- 
**AS Note: We can break this into smaller stories if you'd like**

**Comment by allanto-ah** [comment]
@mkerns1 I found some initial issues, but not sure if you're aware of them already or not, but I'll list them here in their own comments

### Issue 1: The "Back" and "Continue" buttons in the EC page are smaller and not consistent with the rest of the form
![Image](https://github.com/user-attachments/assets/c947609f-bf9e-417d-8401-e3e7e0176562)

Example of "Back" and "Continue" buttons from other pages of the EZR form
![Image](https://github.com/user-attachments/assets/18eb8854-27f5-4f07-83fb-f5169aaf2151)

**Comment by allanto-ah** [comment]
### Issue 2: On the Review page, the "Review your emergency contacts" header is bigger than the other ones on this page
![Image](https://github.com/user-attachments/assets/73f03007-467b-4877-bb18-51a9e523f31a)

**Comment by allanto-ah** [comment]
### Issue 3: The form stepper at the top shows "NaN of" when I click on "Add another emergency contact" from the Review and Submit page

https://github.com/user-attachments/assets/899f2e8f-3771-4edc-bfde-f7dfe7da9026

**Comment by mkerns1** [comment]
Issue 1: I have created a Bug for the Forms System Team to investigate [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/98683).

Issue 2: I wasn't able to actually recreate this bug. 
![Image](https://github.com/user-attachments/assets/6e66314c-48a7-4ca6-be14-103d244b4cd0)

Issue 3: I have created a Bug of the Forms System Team to investigate [here](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3607).

**Comment by mkerns1** [comment]
Issue 1: Ticket created for this issue can you found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/98683).

Issue 2: Ticket created for this issue can you found [here](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3613).

Issue 3: Ticket created for this issue can you found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/98893).

**Comment by allanto-ah** [comment]
Initial QA has been completed in the RI environment. Issues can be seen in the comments above.

A new [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/98344) was created to re-verify once the issues have been fixed. Closing this ticket.
