### ISSUE TITLE
SOCKS access for Adam King (Oddball-IIR)

### ISSUE THREAD

**Issue by AdamKing0126** [department-of-veterans-affairs/va.gov-team#72850]
### Your Name

Adam King

### Your Email

adam.king@oddball.io

### Your Role and Team

backend engineer in IIR

### Product Manager (PM) name and email

Peter Egan peter.egan@oddball.io

### Product Owner (PO) name and email

Jeff Barnes jeffrey.barnes4@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDUIyvK1qLV4R5kkB1+5iFQHG1zL/sSz4bPsYbf2T8HGaNLmTSDGVqIpWP/TEv7myXk3R/uDCr/Zc+1o61O/IRpJdCW1pF7KJbCbNOmrCdnVs2D13oB+LWddPYb7xHi/WYXBj06LK6/Gdyqqo0xdFf4DkRLnzzvKwfB0G9nax1aKJQTFH0GArHEnF+itqluEszWOkBkle+zQxMsVzLsDRRPczz+Ka2np4lIjlJGgZXiyLNadtbqfZaS2Pm2DTbQi+wmcMAfh/t/nqFb1SrwtdN1ry2+DwQSsdCxmS0TTyXdgso3pj0MKYEEVlTJfIVsC3LtCqo9t2lRefdTahmgpzqLAw7fy8QjHaF0hH2xBvbo59HoJHGDQaf6NVbv2SOxDlw/HZvdC5RZLRFR5L65d+EzJdDSW8uV9FoFRk0VqKPcgGgUf6hA97FGtGSA5QOn+IJkkTAdIwZd7+GHkeudONbe+nB+mD0dnIXrRIhj5di6QNP1M7UCuo6eRLMmVwJl5nU= adamking@Adams-Air

### E-QIP Transmittal Confirmation

![Screenshot 2024-01-03 at 12 31 14 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/7659922/6a1485a4-e87d-49dc-9850-df31ce214412)
 

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by patrick-black-oddball** [comment]
completed
