### ISSUE TITLE
[FE] Check-In Error Page content updates - engineering

### ISSUE THREAD

**Issue by lee-delarm6** [department-of-veterans-affairs/va.gov-team#72858]
## User Story
As a user, I want to see new content on the **Check-In** for **Error Pages** that matches CCV/VCT/Phone updates.

## Wireframes
[Wireframes](https://www.figma.com/file/sK2vIx6giAynNqUFR0l4Wx/Production-%7C-Check-in?type=design&node-id=240-696&mode=design)

## Tasks
- [ ] Update the content on [to be filled when wireframes are done]
    
## Acceptance Criteria
- [ ] Work for the ticket tasks is complete
- [ ] Work matches wireframes or reasons why not added

**Comment by benbrasso-agile6** [comment]
@loripusey we no longer need this ticket. How do you want to deal with this?

**Comment by loripusey** [comment]
I'll take it out of the sprint and make a note in the sprint goals
