### ISSUE TITLE
[FE] Pre-Check-In Error Page content updates - engineering

### ISSUE THREAD

**Issue by lee-delarm6** [department-of-veterans-affairs/va.gov-team#72859]
## User Story
As a user, I want to see new content on the **Pre-Check-In** for **Error Pages** that matches CCV/VCT/Phone updates.

## Wireframes

- No matter the modality of the appt/appts for a pre-check-in LoROTA entry, the content on the error pages should always be the same. 
- What's changed? 
     - [Alert content in selects link day of before check in window](https://www.figma.com/file/sK2vIx6giAynNqUFR0l4Wx/Production-%7C-Check-in?type=design&node-id=1427-18440&mode=design&t=5Rj054u58M9UGxQU-4) 
     - [Alert content in selects link day of during check in window](https://www.figma.com/file/sK2vIx6giAynNqUFR0l4Wx/Production-%7C-Check-in?type=design&node-id=1427-18899&mode=design&t=5Rj054u58M9UGxQU-4)
     - [Alert content in selects link after LoROTA entry was deleted](https://www.figma.com/file/sK2vIx6giAynNqUFR0l4Wx/Production-%7C-Check-in?type=design&node-id=1427-19109&mode=design&t=5Rj054u58M9UGxQU-4)
     - [Alert content for generic error](https://www.figma.com/file/sK2vIx6giAynNqUFR0l4Wx/Production-%7C-Check-in?type=design&node-id=1427-20247&mode=design&t=5Rj054u58M9UGxQU-4)
     - Ensure _Find out how to check in on the day of your appointment_ is always present after the alert
     - The content in [How can I update my information accordion](https://www.figma.com/file/sK2vIx6giAynNqUFR0l4Wx/Production-%7C-Check-in?type=design&node-id=1412-11085&mode=design&t=5Rj054u58M9UGxQU-4) has been changed. 

## Tasks
- [ ] Update the content on [to be filled when wireframes are done]
    
## Acceptance Criteria
- [ ] Work for the ticket tasks is complete
- [ ] Work matches wireframes or reasons why not added

**Comment by loripusey** [comment]
@benbrasso-agile6 there are no error pages on these wireframe links, can you confirm/adjust?

**Comment by benbrasso-agile6** [comment]
[Error pages](https://www.figma.com/file/sK2vIx6giAynNqUFR0l4Wx/Production-%7C-Check-in?type=design&node-id=1427-18440&mode=design&t=nlqkWE4liQ2urvuc-4)

Might need to chat some through as these are getting updated, but I _think_ we have all the error scenarios. Again, we're moving to NOT HAVE modality specific error pages.

**Comment by brianseek** [comment]
@benbrasso-agile6 this is merged and ready for validation. It should be on stage soon or on local now with the latest from the `main` branch. Also see attached screenshots.[pre-check-in-errors-v3.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTVtQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ca2d66230501090b63ef9f550906c9a4ae547f42/pre-check-in-errors-v3.zip)

**Comment by loripusey** [comment]
Looks good. I do have a question though: the UUID error shows the message as a caution error (yellow) but the general error shows it as an error (red); is this intentional?

**Comment by brianseek** [comment]
that is a @benbrasso-agile6 question. The UUID not found is [yellow here](https://www.figma.com/file/sK2vIx6giAynNqUFR0l4Wx/Production-%7C-Check-in?type=design&node-id=1427-19109&mode=design&t=JDiJrMwVL0Uvjw2B-0) and general red

**Comment by benbrasso-agile6** [comment]
Will look in a few

**Comment by brianseek** [comment]
on the changes, should have an update soon

**Comment by brianseek** [comment]
@benbrasso-agile6 here are the updates. I probably won't be able to get another front-ender to sign off on the updates until tomorrow, but in the meantime here are the screenshots.[pre-check-in-errors-v4.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0puQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1fb9c1bc961fc19303be3592ffedfa8f2bcb9f47/pre-check-in-errors-v4.zip)

**Comment by benbrasso-agile6** [comment]
np, LGTM (this process is working well)

**Comment by benbrasso-agile6** [comment]
Will close this while you're waiting for pr review

**Comment by brianseek** [comment]
PR is merged
