### ISSUE TITLE
[SCREENREADER]: Search results SHOULD include semantic context

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#7285]
# [508-defect-2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)

**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

When a screen reader reads the content of the search results, it sounds like a wall of words, making it difficult to understand. This screenshot shows the words as they are read by the screen reader: 
<img width="595" alt="Screen Shot 2020-03-26 at 3 55 50 PM" src="https://user-images.githubusercontent.com/57469/77691149-cc26a780-6f7a-11ea-96d7-ca161ca3ce38.png">

The search results **should** be coded with semantic markup and supplemented with visually-hidden context so that screen reader users gain the context sighted users have from being able to see the content. 

## Point of Contact

**VFS Point of Contact:** _First name only. Delete if not applicable._

## Possible Fixes (optional)

```diff
<!-- current code -->
<div class="facility-result" id="ccp_1740661461">
  <div>
    <p><span><strong>1.7 miles</strong></span></p>
    <span>
        <div><p>RETAIL/WALK-IN CARE</p></div>
        <p><span><strong>MINUTECLINIC DIAGNOSTIC OF MAINE</strong></span></p>
    </span>
    <p><span>51 MARKET ST<br>SOUTH PORTLAND, ME 04106-3617</span></p>
  </div>
  <span><a href="https://maps.google.com?saddr=Current+Location&amp;daddr=51 MARKET ST, 
    SOUTH PORTLAND, ME 04106-3617" rel="noopener noreferrer" target="_blank" 
    style="text-decoration: underline;">Directions</a>
  </span>
  <div><div>866-389-2727 <br></div></div>
</div>

<!-- potential fix -->
<!-- as part of an ol -->
<li class="facility-result" id="ccp_1740661461">
  <dl>
    <dt>
        <dfn class="distance">
                <span class="sr-only>Distance from search location</span>
                1.7 miles
        </dfn>
        <dfn class="type">
                <span class="sr-only">Type of facility</span>
                RETAIL/WALK-IN CARE
        </dfn>
        MINUTECLINIC DIAGNOSTIC OF MAINE
    </dt>
    <dd>
       <address> 
              <span  class="street-address">51 MARKET ST</span>
              <span class="locality">SOUTH PORTLAND</span>, <abbr title="Maine">ME</abbr> 
              <span class="postal-code">04106-3617</span>
        </address> 
    </dd>
    <dd>
              <a class="directions" href="https://maps.google.com?
                  saddr=Current+Location&amp;daddr=51 MARKET ST, 
                  SOUTH PORTLAND, ME 04106-3617" rel="noopener noreferrer" target="_blank" 
                  style="text-decoration: underline;">
                        Directions <span class="sr-only">to MINUTECLINIC DIAGNOSTIC OF MAINE</span>
              </a>
    </dd>
    <dd>
              <dfn class="sr-only">Phone number</dfn>
              <a href="tel:8663892727" aria-label="8 6 6. 3 8 9. 2 7 2 7">866-389-2727</a>
    </dd>
  </dl>
</li>
```

Here are samples of what would be read by a screen reader with the potential fix markup:
<img width="607" alt="Screen Shot 2020-03-26 at 5 08 01 PM" src="https://user-images.githubusercontent.com/57469/77697119-a7cfc880-6f84-11ea-9f02-103bf25431ca.png">

<img width="608" alt="Screen Shot 2020-03-26 at 5 08 24 PM" src="https://user-images.githubusercontent.com/57469/77697136-aef6d680-6f84-11ea-8749-cd833e876be0.png">

## WCAG or Vendor Guidance (optional)

* [W3C - Using semantic elements to mark up structure](https://www.w3.org/TR/WCAG20-TECHS/G115.html)

* [W3C - Using ol, ul and dl for lists or groups of links](https://www.w3.org/WAI/GL/2016/WD-WCAG20-TECHS-20160105/H48)

* [W3C - Using text to convey information that is conveyed by variations in presentation of text](https://www.w3.org/WAI/GL/2016/WD-WCAG20-TECHS-20160105/G117)

## Screenshots or Trace Logs

![Screen Shot 2020-03-26 at 4 07 44 PM](https://user-images.githubusercontent.com/57469/77691827-f5940300-6f7b-11ea-9f76-2419cf0f2376.png)

**Comment by mmiddaugh** [comment]
@jenstrickland I believe this is a duplicate for https://github.com/department-of-veterans-affairs/va.gov-team/issues/5555. Can you please confirm? If so, will you please close this one? (#5555 is already groomed) 
Thank you!

**Comment by jenstrickland** [comment]
@mmiddaugh Yes, this is a duplicate. There's a slightly different approach in the potential fix of this issue, using the `<address>` element that may be of interest to your dev team.  cc @brangi
