### ISSUE TITLE
[FE] Pre-Check-In CVT & VVC Appointment and Icon content updates - engineering

### ISSUE THREAD

**Issue by lee-delarm6** [department-of-veterans-affairs/va.gov-team#72860]
## User Story
As a user, I want to see new content on the **Pre-Check-In** for **Appointments** that matches CCV/VCT/Phone updates including Icons.

## Wireframes
[CVT](https://www.figma.com/file/sK2vIx6giAynNqUFR0l4Wx/Production-%7C-Check-in?type=design&node-id=239-863&mode=design)
[VVC](https://www.figma.com/file/sK2vIx6giAynNqUFR0l4Wx/Production-%7C-Check-in?type=design&node-id=239-862&mode=design)

## Tasks
- [ ] Update the content on [to be filled when wireframes are done]
    
## Acceptance Criteria
- [ ] Work for the ticket tasks is complete
- [ ] Work matches wireframes or reasons why not added

**Comment by loripusey** [comment]
@wullaski is there a way to validate this locally with the mocks?
cc: @benbrasso-agile6

**Comment by loripusey** [comment]
@wullaski @lee-delarm6 @brianseek can someone attach wireframes so we can validate?
cc: @benbrasso-agile6

**Comment by benbrasso-agile6** [comment]
I think the screenshots were in the PR. Validation convo https://dsva.slack.com/archives/C02G6AB3ZRS/p1712777714327469

**Comment by benbrasso-agile6** [comment]
Only left, although, not specific to this ticket's AC, was to make sure we use "VA appointment" lowercase

**Comment by loripusey** [comment]
It is not lowercase; @wullaski can you fix that real quick and close this ticket?

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/86678742/e8573b57-f741-4862-886c-7d1609733ac0)

**Comment by wullaski** [comment]
@loripusey  Yes, I can create a PR for this.

**Comment by wullaski** [comment]
@benbrasso-agile6 you can use these ids to test. They are in the Readme.md in the root directory.
```
- cvtApptUUID = `f4b9f1a7-4e3d-4d0c-8b8c-3f9b3d0f9e9b`
- vvcApptUUID = `cc8bd49c-5ac8-4ad2-880a-b96645cdea64`
```

**Comment by loripusey** [comment]
Validated; but I think we need UX to look at something; will discuss in Sprint Review
