### ISSUE TITLE
[FE][CHIP] Check-In enabled for CVT appointments - engineering

### ISSUE THREAD

**Issue by lee-delarm6** [department-of-veterans-affairs/va.gov-team#72864]
## User Story
As a user, I want to **enable** CVT appointments for **Check-In** but not phone or VVC

## Tasks
- Filter to allow CVT appointments but NOT phone or VVC
- Relates to updating one appointment and not showing Provider appointment, but still checking in both upon user check-in
    
## Acceptance Criteria
- [ ] Work for the ticket tasks is complete
- [ ] Work matches wireframes or reasons why not added

**Comment by brianseek** [comment]
validated
