### ISSUE TITLE
SOCKS access for Steve Long

### ISSUE THREAD

**Issue by stevelong00** [department-of-veterans-affairs/va.gov-team#72868]
### Your Name

Steve Long

### Your Email

steven.long@adhocteam.us

### Your Role and Team

Software Engineer on IIR Product Team

### Product Manager (PM) name and email

Lisa Kahler lisa.kahler@oddball.io

### Product Owner (PO) name and email

Jeff Barnes jeffrey.barnes4@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCiOPwk2VgnMEQ6PkQp+aBHzYdyrpUeT1EIqtvDXd1hshNUgy2L2jWAqhKB+X5FPTYXbSE3NtGaJdKspHLKQFXpouRHoWZncay9+wb0wdsODmD2c/IEBENWjljc2VGnVDB8+L9uSU7y0QYBY9TdTCH/azsbBPn79VDufCz/E6kRkDVWHg/sQ4AVjZkl0jAOEpmIPfHedMNZvWfjel8/8v3gcZlnbQNqwu5ncbaTo8EqK7WtAw2C6g7/I8fhuUd0c3j9U7RJ351EPXCmmX3cSz+YDG0NuBqN/8jeMvTN6/XnVeCI8fhNaN1SqmaOZpHVr1haeMk+hutBOCmLDtyhGf6jn+Eeywtm4PiCSvTH1HU2r/fRaHuWD5XehCYSeQowJFnUBEZG8F8x+N5nEvibJxUdNh8ZjijTMPM4Zmm+ucAkNZZZnJuu+mvw5MRGPlbrsHG4bv4cfz52b1INQ3H/x6gvBr/MPRBKGHLqSEyaXOxdDvUmzEmpnA48Ea2biStYaAE= steve@Steves-Mac-mini.local
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCdZdjr9t/Hdgu6VBAdcZHXvUyEnebLgYf9LxDQjrBSV2TLhj/xKbKs7FzX7b++OakXcS79i9Je1KRgS7Z5qV5ZTp/j5vPVMIxg1vEBHj3DraEFEhuNLJFEcM9MpjSGJ1PB84+yOzUmErTSXnJDvfl7qNt7xXO4PRZdUGu4EUsl/Xt5wCO3KyjfzwBejJdZTwOb8F7Akw+4brf0EV4AvyEMw6/hX8nhNb5rQb838dHM+ybIsX8wCiQEcOL/dU80AgY3neqLouMsLk4f8AK0s86zHMBSA5Yvss+bmsyIGZR6Xc5+hqoIM6u+rEMDwSnVVPiUNfrp1Sm+tzNVLPU4YqzXQGPIxiUBatMZ+ubic4STe2Fnwm+QxAgVbWY4CYh334Z71WsdY7sKZln5maUp/bxQByTnM/gFc+FnnKmbrnD9KlcGmL7N6/DfhIxYFpZZB1O2KQxYV2HkTx0kYZBGnONM0EKK2zbkSMNQm5VLbU2wqbnacZaFIqQulhcNrsIq30c= steve@SteveLong-HP

### E-QIP Transmittal Confirmation

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/2211897/3baa3fc4-80f6-4fa5-9c78-5327f2ddea21)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by patrick-black-oddball** [comment]
access granted

**Comment by barbarello** [comment]
@stevelong00  Access granted with your new window key ✅ 

Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html 

Reach out in #vfs-platform-support if you have any trouble.
