### ISSUE TITLE
[FE] eCheck-In CVT Appointment and Icon content updates - engineering

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#72870]
## User Story
As a user, I want to see new content on the **eCheck-In** for **Appointments** that matches CVT updates including Icons.

## Wireframes
[Wireframes](https://www.figma.com/file/sK2vIx6giAynNqUFR0l4Wx/Production-%7C-Check-in?type=design&node-id=240-696&mode=design)

## Tasks
- [ ] Update the content on [to be filled when wireframes are done]
    
## Acceptance Criteria
- [ ] Work for the ticket tasks is complete
- [ ] Work matches wireframes or reasons why not added

**Comment by loripusey** [comment]
Add in the "blow out" of the experiment with Pre-Check-in so that we are loading all of the icons
@brianseek will work with John

**Comment by benbrasso-agile6** [comment]
@wullaski any screenshots?

**Comment by wullaski** [comment]
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/2982977/e53ef987-f6f8-4475-9cc3-a71df1cd21b4)
<img width="406" alt="Screenshot 2024-04-29 at 4 13 54 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/2982977/4400204c-dede-4f56-9567-e922bbb9090c">
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/2982977/c3c719f2-460e-4112-abd6-e4e373c3dea8)

**Comment by benbrasso-agile6** [comment]
Nice!
