### ISSUE TITLE
[SCREENREADER]: aria-live="polite" MUST be removed from the search results container

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#7288]
# [508-defect-0 :exclamation: Launchblocker](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-0)

**Feedback framework**
- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

Using JAWS or NVDA, once focus is in the search results, it is not possible to get out of that container. `aria-live="polite"` and `aria-relevant="additions text"` MUST be removed from the search results container.

## Point of Contact

**VFS Point of Contact:** Jennifer

## Acceptance Criteria
- As a screen reader user, I want to read the content of the page without getting stuck.
- As a keyboard user, I want to navigate the content of the page without getting stuck.

## Environment

* Operating System: Windows
* Screenreading device: JAWS + IE11 or NVDA + Firefox
* Server destination: staging, production

## Steps to Recreate
(It will be necessary to do this with Jennifer or Trevor, unless you have access to Windows + Firefox + [NVDA](https://www.nvaccess.org/download/).)
1. Enter `https://staging.va.gov/find-locations` in browser
2. Start screenreading device listed in Environment
3. Navigate to the search results while JAWS is reading content
4. Using keyboard only attempt to get out of the search results
5. Verify it's not possible 

## Possible Fixes (optional)

Remove `aria-live="polite"` and `aria-relevant="additions text"`

```diff
<!-- current code -->
! <div aria-live="polite" aria-relevant="additions text" class="facility-search-results">

<!-- potential fix -->
+ <div class="facility-search-results">
```

**Comment by mmiddaugh** [comment]
This one may make sense to handle along with [#5555]

**Comment by mmiddaugh** [comment]
@jenstrickland this is ready for review

**Comment by jenstrickland** [comment]
Validated, that the aria-live is removed from the code.
