### ISSUE TITLE
Flipper UI access for Sam Raudabaugh

### ISSUE THREAD

**Issue by raudabaugh** [department-of-veterans-affairs/va.gov-team#72887]
### Your Name

Sam Raudabaugh

### Your GitHub handle (Flipper UI access is managed through GitHub)

@raudabaugh

### Team, Role, and Company of the target individual

Benefits portfolio, Lead Benefits Engineer, VA federal employee

### Please confirm if you are on Atlas, Platform Team Roster or are a Federal User

- [ ] [Atlas](https://dev.va.gov/atlas)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [X] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [X] Lesser Environments (Dev/Staging/Sandbox)
- [ ] Production (if requesting, justify prod access below)

**Comment by IsaiahMW1** [comment]
Good morning @raudabaugh I'm not seeing you in Atlas or Platform Team Roster currently awaiting for Bill Chapman to respond with notification that you are indeed in the Federal User group.
