### ISSUE TITLE
Add metadata validation to Benefits Intake Service

### ISSUE THREAD

**Issue by tblackwe** [department-of-veterans-affairs/va.gov-team#72885]
In the Benefits Intake Service generate_metadata function 
https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/benefits_intake_service/service.rb

Add a call to the metadata validation library at  https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/simple_forms_api_submission/metadata_validator.rb

An example of a consumer of this validation can be found at
https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/simple_forms_api/app/controllers/simple_forms_api/v1/uploads_controller.rb

This validation will clean the passed metadata to align it with Benefits Intake metadata requirements defined at https://developer.va.gov/explore/api/benefits-intake/docs?version=current

**Comment by tblackwe** [comment]
In the Benefits Intake Service generate_metadata function 
https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/benefits_intake_service/service.rb

Add a call to the metadata validation library at  https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/simple_forms_api_submission/metadata_validator.rb

An example of a consumer of this validation can be found at
https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/simple_forms_api/app/controllers/simple_forms_api/v1/uploads_controller.rb

This validation will clean the passed metadata to align it with Benefits Intake metadata requirements defined at https://developer.va.gov/explore/api/benefits-intake/docs?version=current

**Comment by micahaspyr** [comment]
Works in the wild!  Putting this in done
