### ISSUE TITLE
SOCKS access for Austin Smith

### ISSUE THREAD

**Issue by asmithgovcio** [department-of-veterans-affairs/va.gov-team#72890]
### Your Name

Austin Smith

### Your Email

austin.smith@govcio.com

### Your Role and Team

Backend Engineer

### Product Manager (PM) name and email

Tom Davis
thomas.davis@govcio.com

### Product Owner (PO) name and email

Denise Coveyduc
denise.coveyduc@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCzMgejLssLU0rUd9qa9IBC5XJnl6tIO0RedAhkZQ4nJUm+bp6lOlu42bE5FkPBvG2lUAjCtdebdv2XuTiOFxS3NM60Eire9NaUkZPlucwnSRvlG4oSOdIoeBg09BS/2WTmxvQBT2BqOmI1btULEeFGt9nOh+NQdJtSWaCfrBuAhKYbyqZ7grJbJkDDeUXZOsQQg4Ax/wvaF5/uJ9PsJF9Gb1o7SbuGNEEHbDGhdx2HmGXMkgtfeXpXyQ/+oGnqmDMPD4R7unC/sknUv6TSmM7K+vUET7vXuXLIVIzJsnlPze0mJGBEY1DSIHMLqgsWZO8T2yUOqUwzhe7SILq58YEsQu1Ew644O7D3sb5EcZ9k660JiTOIw1ik7etTjdqJoRXtld0EjtN710fcXMu68W5e/JUcMm8oTas5bZcmYECpyA46vDVNcwMC9zKhoT2yD4g74TltnOCGtWuec9/kD7cYMlxo+WbJ6ASXYAdNgCuJ4dmz7E50b+8vm1CXiJ1gYRs= devaustinsmith@KWYMJ7YDX2.lan

### E-QIP Transmittal Confirmation

<img width="467" alt="Screenshot 2024-01-04 at 8 59 21 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/152525987/6a5ea422-79d5-4c23-a59f-29c4200f729a">

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by HeatherRienks** [comment]
What are the next steps?

**Comment by HeatherRienks** [comment]
@flooose - Hoping you can help advise on next steps to get access for @asmithgovcio. Much appreciated!

**Comment by flooose** [comment]
Hello @HeatherRienks. I just merged this and you should be good to go. 

Do be aware though, I've rotated out of support for the time being. If you all run into any problems with this, please reach out to the support team for the person who's currently in devops support rotation :)

**Comment by HeatherRienks** [comment]
Thank you @flooose !!
