### ISSUE TITLE
Address parameter search bug

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#7289]
## What happened?
Searches using "10301 New Guinea Rd Fairfax, VA 22032-3268” as the address parameter were returning search results in NJ and NY. Initially reported by the OCC, it was believed this was related to the 5 igit street address number being interpreted as a zip code. 

Additional testing revealed:
- other 5 digit street addresses had accurate search results. 
- The Fairfox address parameters also returned NJ and NY search results for VHA searches. 
- The coordinates for the address are 38.798479, -77.300885 but are being passed as -74.7, 40.1 to -73.3,41.1

> ttps://api.va.gov/v0/facilities/va?bbox[]=-74.77569580078126&bbox[]=40.10118506258701&bbox[]=-73.38867187500001&bbox[]=41.17245194931263&type=health&page=1&per_page=20

## Steps to Reproduce
- URL: https://www.va.gov/find-locations/?zoomLevel=9&page=1&address=10301%20New%20Guinea%20Rd%20Fairfax%2C%20VA%2022032-3268&facilityType=health&serviceType&location=40.64%2C-74.08&context=New%20York%2C%20New%20York%2010301%2C%20United%20States

## Desired behavior
The correct coordinates should be passed and results near the address should be returned. 

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by brangi** [comment]
merged
