### ISSUE TITLE
Update Central Mail Metadata Validation

### ISSUE THREAD

**Issue by tblackwe** [department-of-veterans-affairs/va.gov-team#72897]
The existing Central Mail metadata validation in 
https://github.com/department-of-veterans-affairs/vets-api/blob/8669335cf31ced169d1a0207e37690c2bada807c/lib/decision_review_v1/utilities/form_4142_processor.rb 

needs to be replaced with a shared library defined at 
https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/simple_forms_api_submission/metadata_validator.rb

This will move all the validation rules to a central location associated with the service, and not require each consumer to implement their own validation.

An example of a consumer of this validation can be found at
https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/simple_forms_api/app/controllers/simple_forms_api/v1/uploads_controller.rb

**Comment by tblackwe** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/15030#pullrequestreview-1804344326 adds a new us based flag for zip code validation

**Comment by freeheeling** [comment]
[Updates](https://github.com/department-of-veterans-affairs/vets-api/pull/15037) deployed to production Wed, Jan 10, 2024.
