### ISSUE TITLE
Update "VA mission, vision, and values" link in MegaMenu "About VA" section to "About VA"

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#729]
The "About us" page on VA.gov is somewhat difficult to find, because it isn't labeled as `About VA`. It's labeled as `VA mission, vision, and values`. This is an issue, because there are some regulations about required content on the "About us" page and it isn't clear where that page is.

We need to relabel the  `VA mission, vision, and values` to clarify that it is the `About VA` page.

**Comment by ncksllvn** [comment]
CC: @chrisj-usds  @andrewlewandowski @mnorthuis @Karak888

**Comment by ncksllvn** [comment]
This will be live today

**Comment by Karak888** [comment]
Thanks @ncksllvn!  I am lcosing this ticket.
