### ISSUE TITLE
Risk Assessment: Upgrade to Redis 6.2

### ISSUE THREAD

**Issue by flooose** [department-of-veterans-affairs/va.gov-team#72900]
## Description

Our infrastructure requires upgrades to ensure the latest security patches, performance improvements, and compatibility with existing systems. Before proceeding with the upgrade, a comprehensive risk assessment must be conducted to identify potential challenges and mitigate associated risks.

# Upgrade to Redis 6.2

## Abstract

Our Redis is hosted by AWS, which offers a robust and efficient upgrade path. While data loss is not likely, safeguards will be in place, in case problems with the upgrade do occur. For technical reasons, specific to our platform, these safeguards will require us to take the application offline.

### 1. **Review Upgrade Documentation:**

- [x] Thoroughly review the upgrade documentation for the target version.
- [x] Identify any breaking changes, deprecated features, or new requirements.

#### Assessment

The main source of information on the upgrade process comes from the AWS documentation for [Engine versions and upgrading](https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/VersionManagement.html)

We're upgrading three Elasticache Redis instances with two different versions, the lowest of which is version 5.0.6. AWS supports upgrading from this version directly to our desired version, with no downtime for read requests and only a few moments of downtime for write requests while the switch-over from the old to the new version occurs:

> Starting with Redis engine version 5.0.6, you can upgrade your cluster version with minimal downtime. The cluster is available for reads during the entire upgrade and is available for writes for most of the upgrade duration, except during the failover operation which lasts a few seconds.

### 2. **Environment Analysis:**

- [x] Assess the current environment and note any custom configurations or dependencies.
- [x] Identify potential compatibility issues with existing applications and services.

#### Assessment

Our current environment has no custom configurations. It simply has a reference to a AWS Redis endpoint, which won't change. Because [backward compatibility has always been a design principle of the Redis project](https://redis.com/blog/redis-7-generally-available/), compatibility issues shouldn't arise either. Our ruby clients for Redis are also not configured to interact with a specific version of Redis server, so no action will be necessary for our clients.

While AWS offers a robust and efficient upgrade path, technical specifics of our platform will require some level of downtime. The reason for this is that we're not 100% sure about the nature of the data in our Redis cluster. Should the upgrade fail and data loss occur, we don't know that our code will completely recreate the contents of the cluster. For this reason, we need to:

1. Make a backup of the Redis cluster prior to the upgrade
2. Prevent further writes to the Redis cluster between the creation of the backup and when the upgrade finishes.

This is achieved by scaling the vets-api pods down to 0, which will prevent disparities between the backed up data and the data that will ultimately be migrated to the upgraded cluster.

The backup requires around 15 minutes and the upgrade requires about 20 minutes.

Because of this required downtime, additional steps have to be taken for the upgrade in _production_. Specifically, the user-facing application has to warn the users of the platform about the upcoming maintenance window. If parts of the platform that aren't associated with vets-api are to stay online, additional warnings may be necessary in the UI. **How we communicate to the users, which parts of the application are functional and which are in a maintenance window, still needs to be determined.**

### 3. **Data Migration Strategy:**

- [x] Develop a strategy for migrating existing data to the upgraded Redis version.
- [x] Determine the impact on data integrity and performance during the migration.

#### Assessment

Data migration is managed by AWS as part of the upgrade process. It either succeeds or we have to roll back to the previous version. For this reason, prior to the upgrade, our EKS pods need to be scaled down to 0 and a backup has to be made of the Redis data. Should the upgrade fail, a new cluster with the old version of Redis has to be created and populated with data in the backup. See the rollback documentation in the [Redis Update](https://vfs.atlassian.net/wiki/spaces/PPT/pages/2806808593/Redis+Update#Rollback) documentation for detailed step for performing a rollback.

### 4. **Backward Compatibility:**

- [x] Evaluate backward compatibility with existing clients and connectors.
- [ ] Test key functionalities to ensure seamless integration with dependent systems.

#### Assessment

Our Redis clients are independent of the Redis server version, meaning the Redis server can be upgraded, independent of the clients.

### 5. **Security Implications:**

- [x] Perform a security review to identify and address any vulnerabilities in the current version.
- [ ] Ensure that the upgraded version complies with security best practices.

#### Assessment

[Beginning with Redis 6.0, AWS manages patch-version upgrades](https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/supported-engine-versions.html#redis-version-6.0), i.e. upgrades that involve security-related fixes, offering us security advantages that we don't currently have.

While AWS does not say what will happen if we fail to upgrade before the [End of Life](https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/deprecated-engine-versions.html) date, at a minimum, we can expect our version to stop receiving security upgrades. 

### 6. **Performance Testing:**

- [ ] Conduct performance tests to assess the impact of the upgrade on system performance.
- [x] Identify and address any performance bottlenecks that may arise.

#### Assessment

Performance bottlenecks should not arise. We have monitors in place to watch and verify this.

### 7. **Rollback Plan:**

- [x] Develop a comprehensive rollback plan in case unforeseen issues occur during the upgrade.
- [x] Ensure the team is prepared to revert to the previous version if needed.

#### Assessment

See the Rollback Plan documented in the [Redis Update documentation](https://vfs.atlassian.net/wiki/spaces/PPT/pages/2806808593/Redis+Update#Rollback). This has been tested in the lower environments.

## **Definition of Done:**

- [ ] A detailed risk assessment document is created and shared with the team.
- [ ] Mitigation plans are established for identified risks.
- [ ] Stakeholders are informed of potential impacts and mitigation strategies.
- [ ] Team members are briefed on the upgrade plan and associated risks.
- [ ] The risk assessment is approved by relevant stakeholders before proceeding with the upgrade.

## **Additional Notes:**

- This risk assessment is a critical step in ensuring a successful upgrade.
- Regular communication with the team and stakeholders is essential throughout the assessment process.
- Document all findings and decisions made during the risk assessment for future reference.

**Comment by LindseySaari** [comment]
Can we add some details here around what happens if we don't complete the upgrade before the EOL window, specifically the security vulnerabilities.

**Comment by flooose** [comment]
> Can we add some details here around what happens if we don't complete the upgrade before the EOL window, specifically the security vulnerabilities. @flooose

How about this under "Security Implications"?:

```
While AWS does not say what will happen if we fail to upgrade before the [End of Life](https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/deprecated-engine-versions.html) date, at a minimum, we can expect our version to stop receiving security upgrades.
```

**Comment by jennb33** [comment]
Per @flooose this ticket can be closed, as the Risk Assessment is complete. 
There was some questions that Jeff had brought up regarding compatibility, and Chris sent him the AWS information. Nothing since then.
