### ISSUE TITLE
Design an Intake "Sign In" page for Veterans

### ISSUE THREAD

**Issue by lmorris3** [department-of-veterans-affairs/va.gov-team#72902]
## Context

Given we want _only_ recruited Veterans to see IPP, we cannot rely on Login.gov implementing the opt-in to IPP page as that will be available to any user hitting Login.gov from va.gov. That handoff provides the UUID/email to our intake application.

Instead, we will have a user "authenticate" into the intake application. By doing so we know that the user has authenticated into their Login.gov (IAL1) account from which Login.gov will send UUID/email.

So in order to do so, we need a sign in page/link for the intake flow.

Proposed solution: have a url to our intake application that shows a "sign in with Login.gov" button or link. They would go to the Login.gov sign in/create account page (login.gov automatically sends the user back to our application with the UUID).

## Acceptance criteria
GIVEN a Veteran has received a link to our application for the pilot
WHEN they click the link
THEN they see a page with a "sign in with Login.gov" button/link
WHEN they click the button/link
THEN they are taken to the Login.gov sign in/create account page
WHEN they enter a valid username and password
AND click Sign In
THEN they will return to the IPP application
AND the UUID will be passed from Login.gov to the IPP application
AND they can continue to the next screen

- Veteran can access a url with a direct link to Login.gov sign in/create account page
- Veteran can sign in to an IAL1 account (or create one) from the url
- UUID is passed to our intake application

Notes/Questions:
- how will we send the Veteran the url? From Perigean in an email?
- What if the user creates an account on Login.gov instead of signing in to an existing? Will this still work?

**Comment by skirkman16** [comment]
1. Recruit veterans who need to create a modern credential.
2. Recruit the Veterans for a 1.5 appointment where they will create a Login.gov account onsite
	- who will oversee this?
	- who will a veteran go to if they have questions?(who has authorization?)

[diagram says click continue but we may not be able to intercept the Login flow]

3. Send each Veteran a link to navigate to our in person proofing application (as a standalone URL)
	- link does not live on Login.gov right now
	- make sure we recruit individuals with a smart device
4. Link takes the Veteran directly to the landing page of the in person application

**Comment by SophiaPhilipMO** [comment]
Questions raised by @mateoclarke : 
- Determine footer form and make standard across applications
- Create ticket to explore translatability for other languages
