### ISSUE TITLE
S44 [Exterminators 🐛]

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#72907]
## Sprint Goals

- Complete E2E testing and launch bug fixes for NOD v2 release
- Complete ADG letter feed setup
- Kickoff prototype for "Downloadable Copy of an Appeal" accessibility testing

---

## Team Capacity
- Velocity average (past three sprints): 9
- Target velocity: 16

PTO:
- Eugene: Returning 1/9
- DK: Possibly off, will check upcoming research sessions and confirm w/ Heather

## Sprint Risks and Assumptions
- The bug that affects Veterans differently is back, and may take up capacity. 

## Reference documentation

- [High-level Roadmap](https://docs.google.com/presentation/d/18rYnaYCjp2L2cm8HdYmXsg1_Pz7KI_X0vNRkmT5AqEk/edit#slide=id.g2804f61cf5f_0_0)
- [Tactical Roadmap (WIP)](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1702419283589/39d0d78778b8a35a2a02b48496d665d86ec3c5a2?sender=ud80be02ce240061eb0f35352)
- [Planning and Prioritization Board](https://github.com/orgs/department-of-veterans-affairs/projects/1026/views/1?filterQuery=)
- [Defect Board](https://github.com/orgs/department-of-veterans-affairs/projects/876/views/1?visibleFields=%5B%22Title%22%2C%22Assignees%22%2C46447480%2C46447511%2C46447563%2C%22Labels%22%5D)
- [Story Estimator](https://docs.google.com/spreadsheets/d/1ae9fpz_ThZycIWjmBBMSEuGRGqsvRSz3/edit#gid=1440877167)
- [Velocity Planner ](https://docs.google.com/spreadsheets/d/1i7pVgf2XQxuRkIbuhHC5dckx2RlZt87n/edit#gid=880321098)

**Comment by HeatherWidmont** [comment]
Velocity average has been updated
