### ISSUE TITLE
Design a sign in page for proofing agent application

### ISSUE THREAD

**Issue by lmorris3** [department-of-veterans-affairs/va.gov-team#72903]
## Problem

Proofing Agents will need to authenticate to access the PA application. 

Proposed Solution: 

Proofing Agent will sign in to Identity Toolkit separately. Proofing Agent will go to a landing page on our app that has a sign in page. Login.gov has a setting that will force them to use their PIV to sign in. There's a field called acsr (set to hspv12 value). We can use a similar landing page for PAs as for Veterans - application has a "Sign in with Login.gov"

Questions:
- do we treat this as one application, role based? Or two apps? Recommend treat this as two applications
- 

## Acceptance Criteria
GIVEN I am authorized to perform Proofing Agent duties for Veterans
WHEN I enter the IPP Proofing Agent url on my machine
THEN I will see the IPP Proofing Agent application
AND a "Sign in with Login.gov" button/link
WHEN I click that link
THEN I will see the Login.gov "acsr" (set to hspv12 value) that requires my PIV to sign in
WHEN I enter my PIV and my PIN
THEN I will return to the IPP application home page
AND I will be signed in as a Proofing Agent

**Comment by skirkman16** [comment]
For PA
1. Recruit PAs with computers that can allow them to open up a URL to our in person proofing application
2. Ask PAs to save the URL in a bookmark
3. URL takes the PA directly to the landing page which asks them to sign in with their PIV
[insert PIV screen after landing page]
4. After they sign in with PIV they can search for the Veteran’s case number
