### ISSUE TITLE
[DISCOVERY] Form526 Submission polling

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#72914]
With the migration to Lighthouse's API endpoint for submission, instead of receiving information during the submission process, the system will need to "poll" for information about the submission status to display to the user.

The goal is to gain an understanding and identify how we will implement polling to submit a 526 claim along with the documents and ancillary forms, as well as identify UI/UX updates.

**Comment by pacerwow** [comment]
@aurora-a-k-a-lightning can this be closed?
CC @mchae-nava
