### ISSUE TITLE
[KEYBOARD]: In Firefox Choose a VA facility type dropdown MUST be keyboard accessible

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#7291]
#  [508-defect-1 :exclamation: Launchblocker](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-1)

**Feedback framework**
- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

Using Firefox in Windows 10, the Choose a VA facility type dropdown is currently not traversable by keyboard alone. 

## Point of Contact

**VFS Point of Contact:** _First name only. Delete if not applicable._

## Acceptance Criteria

As a keyboard user, I want to navigate the options in the dropdown so I can choose what I want.

## Environment

* Operating System: Windows 10 (up to date)
* Browser: Firefox 74.0 (the latest)
* Screenreading device: NVDA
* Server destination: staging and production

## Steps to Recreate

1. Enter `https://staging.va.gov/find-locations` in browser
2. Start screenreading device listed in Environment
3. Navigate to the Choose a VA facility type dropdown using keyboard only
4. Attempt to traverse the options in the dropdown using keyboard only
5. Verify that it isn't possible to move through the options

## Possible Fixes (optional)

If possible, use a `<select>` element for this dropdown instead of:
```
   <button role="button" aria-expanded="false" aria-haspopup="true" 
      id="facility-dropdown-toggle" class="dropdown-option" tabindex="0" type="button">
      VA health
      <i class="fa fa-chevron-down dropdown-toggle"></i>
   </button>
```
The `<select>` element used for Choose a service type is navigable by keyboard.

Notes from Grooming: The [Design system](https://design.va.gov/patterns/form-templates)  includes form templates which handle this type of field as a dropdown, rather than a button.  There is a disagreement between the pattern library (which uses rounded corners) and the design system (which uses square corners). 

## Guidance

* [`<select>` pick your poison](https://www.24a11y.com/2019/select-your-poison/) — **Strongly recommended reading** 😄

**Comment by mmiddaugh** [comment]
@brangi to test before estimating

**Comment by mmiddaugh** [comment]
@jenstrickland, this is ready for your review

**Comment by jenstrickland** [comment]
Validated. This is so much better!
