### ISSUE TITLE
IPP Pilot Onsite Signage

### ISSUE THREAD

**Issue by lmorris3** [department-of-veterans-affairs/va.gov-team#72919]
Context
Need to create signage for pilot site to help Veteran and VA staff to know where the pilot testing is

User Story
As a Veteran, I need to be able to easily locate the testing area for the pilot through signage or with the assistance of VA staff who can also use signage so that I can participate.

- [x] Sign formatted for legal size paper dimensions
- [x] Sign formatted for A4 dimensions
- [x] Name of pilot
- [x] Location of pilot
- [x] Directions to location
- [x] How to get help if lost
- [x] Contact information if unable to locate
- [x] Includes VA OCTO logo
- [x] Includes Connected Care logo
- [x] Palette is high contrast
- [x] Mock ups are ready to review in Figma

**Comment by JKG199** [comment]
Mockups updated based on brainstorm session, content is still not finalized, but most AC's have been met. See revised mockups when you get a chance @SophiaPhilipMO. 

https://www.figma.com/file/sWaKEav2QibZZKxAkbULG7/IPP-Pilot-Material?type=design&node-id=145%3A11&mode=design&t=XtKnv3Tfc2ArVnHN-1

**Comment by SophiaPhilipMO** [comment]
@JKG199 dropped in comments on the right hand version

**Comment by JKG199** [comment]
@SophiaPhilipMO revised mockup ready for any additional comments in Figma for you. Also tagged you in a comment. 

https://www.figma.com/file/sWaKEav2QibZZKxAkbULG7/IPP-Pilot-Material?type=design&node-id=145%3A11&mode=design&t=3KPt7As90XrxaKa2-1

**Comment by SophiaPhilipMO** [comment]
Waiting on specific office space information

**Comment by SophiaPhilipMO** [comment]
Speciality Building 21, Lower Level- Room 110
@JKG199 I think we can simplify the signage further and write In-Person Proofing Pilot with Perigean in Specialty Building 21, Lower Level - Room 110

**Comment by JKG199** [comment]
Updates signage [here ](https://www.figma.com/file/sWaKEav2QibZZKxAkbULG7/IPP-Pilot-Material?type=design&node-id=145%3A11&mode=design&t=phV6Df1ToGACnIOF-1) titled as final draft for review. @SophiaPhilipMO feel free to review and share out!

**Comment by SophiaPhilipMO** [comment]
Sent signage to Fayetteville, AR team to review and give feedback by 5/13 before printing.

**Comment by SophiaPhilipMO** [comment]
Update to Baltimore site information. Waiting to confirm details with VA staff, emailed on 5/28
