### ISSUE TITLE
[Helm] Add framework for new systems apps

### ISSUE THREAD

**Issue by hgbarreto** [department-of-veterans-affairs/va.gov-team#72926]
## Description
Add framework for the following apps via helm charts 
- ArgoCD
- Trivy Operator
- Reloader
- Metacontroller

## Acceptance Criteria
- [ ] Go over adding frameworks with the team
- [ ] Add framework for ArgoCD
- [ ] Add framework for Trivy Operator
- [ ] Add framework for Reloader
- [ ] Add framework for  Metacontroller

## Refinement Guidance - Check the following before working on this issue: 
- [x] _Team label assigned ("platform-tech-team-2")_
- [ ] _Epic assigned (if needed)_ 
- [x] _Estimated (points assigned)_
- [ ] _Sprint assigned (once planned)_
- [ ] _Team member(s) assigned_
- [ ] _Understands how this work aligns with the overall platform_

**Comment by hgbarreto** [comment]
Placing back in backlog to work fwdproxy

**Comment by npeterson54** [comment]
Pulling out due to Grafana prioritites that need doing this sprint

**Comment by ph-One** [comment]
Broken into multiple tickets. Closing.
