### ISSUE TITLE
Schedule Proofing Agent Usability Tests

### ISSUE THREAD

**Issue by lmorris3** [department-of-veterans-affairs/va.gov-team#72920]

**Comment by SophiaPhilipMO** [comment]
Email scheduled for 1/5 to Susan Haidary

**Comment by SophiaPhilipMO** [comment]
Robyn Singleton scheduling UTs on the following dates:
Thurs, 2/29: 8am-12pm ET; 4 tests
Friday, 3/1: 8am-12pm ET, 4 tests
