### ISSUE TITLE
Minor Yellow Ribbon participating schools tool content updates

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#7293]
Please make the following edits:

- In the value for `Maximum Yellow Ribbon funding amount (per student, per year)`, please remove the decimal after the dollar amount, since all values are whole amounts. (The `.00` isn't necessary)
- Please add the word `benefits` (lowercase b) to the end of the string `All tuition and fees not covered by Post-9/11 GI Bill`
- Please lowercase the word `Benefits` in the label for the checkbox for the benefit amount filter.

Acceptance Criteria:
- [x] there are no decimal points for dollar amounts
- [x] all instances of the word benefits related to  Post-9/11 GI Bill are lower case
- [x] Change `All tuition and fees not covered by Post-9/11 GI Bill` to `All tuition and fees not covered by Post-9/11 GI Bill benefits`

Thanks!

**Comment by MickinSahni** [comment]
Adding `needs-grooming` label and placing in Ready until we're able to pickup

**Comment by kelsonic** [comment]
Pulling this into sprint, hope that's ok! @MickinSahni

**Comment by kelsonic** [comment]
PR is open 🙂

**Comment by MickinSahni** [comment]
2020-03-30 PW Standup
- Validated on staging! Moving to closed.
