### ISSUE TITLE
[Action] Integrate openscap scanning with Packer pipeline

### ISSUE THREAD

**Issue by barbarello** [department-of-veterans-affairs/va.gov-team#72937]
We would like to integrate security scanning for amazon linux 2 with packer builds so that the team would have the ability to check the build for security vulnerabilities without having to deploy it to production or wait days to find out whether a proposed security fix can be merged or not.   We would like for the scan results to be available at the end of the packer build.

**Comment by ph-One** [comment]
Closing. Duplicate of https://github.com/department-of-veterans-affairs/va.gov-team/issues/72939
