### ISSUE TITLE
CT: Alert margin should be 8px instead of 4px

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#7294]
On the search results page, the alerts are spaced too close

What it's currently set at
![Screen Shot 2020-03-27 at 8.43.18 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/006b7396-d05d-4bdc-b4ea-b6828f9ba6c9)

What it should be
![Screen Shot 2020-03-27 at 8.42.11 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/e3f933f6-4ab1-45da-a164-1fb5f358a140)

**Comment by sonntag-adam** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/12037

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-03-27 at 1.01.36 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/460ba37a-d6f7-4517-a4d3-8e4b7ace99f3)

**Comment by ccruzgra** [comment]
@delli-gatti-michael This checks out.

**Comment by delli-gatti-michael** [comment]
Fix is now present in staging. Closing this issue
