### ISSUE TITLE
Design | MHV | Notification Settings | Remove Newsletter Notification Preference

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#72952]
## Background 
We initially added MHV Newsletter as a notification preference in the profile, however, the newsletter preference isn't currently integrated with gov-delivery and would need significant amounts of additional work to enable the preference to fully function on va.gov. 

OCTO folks arrived at the conclusion that the newsletter preference isn't needed in the va.gov profile since users can unsubscribe to the newsletter directly from the email. 

##  Supporting artifacts 
[Slack thread where we discussed the need to remove the preference](https://dsva.slack.com/archives/C909ZG2BB/p1704302076904379)

<details><summary>Email Requesting End Date</summary>
<p>

![Image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/e10700e0-97b8-47ae-bacc-378d2aac6964)

</p>
</details> 

## Acceptance Criteria 
- [ ] We've updated the designs to remove mention of the newsletter preference, no FE actions needed 

`note:` when VA Profile formally end-dates the preference, this preference will no longer be visible in the FE and no FE code needs to be updated for that to happen

**Comment by mtcA6** [comment]
This is being taken care of as part of our figma migration story #71235

**Comment by andaleliz** [comment]
This has been removed from the mock-ups. I remeber a lot of back and forth about the content, so dropping a note here in case they do want to add it back:
- The preference lived in a section called "General VA information and updates"
- The notification name was "My HealtheVet bi-weekly newsletter"
- The checkbox label was "Subscribe by email"

<img width="336" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/55992116/07fd7754-731f-4683-8984-8f6542067f7f">
