### ISSUE TITLE
Step 4 Household Info/Former marriage info: Reorder 5 existing questions

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#72951]
## Info from business

This is to match the order of the questions on the screen about the Veteran's spouse's former spouse. For screenreader users, we also want the date of marriage and date marriage ended fields one right after the other.

## Issue Description

In Step 4 Household information / Former marriage information page, reorder the existing questions into this new order:

1. How did the marriage end? (*Required)
2. Date of marriage (*Required)
3. Date marriage ended (*Required)
4. Place of marriage (city and state or foreign country) (*Required)
5. Place marriage marriage (city and state or foreign country) (*Required)

<img width="543" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFdkQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0bb8a27cc2016e7ae9db6c830c7d8c42f6e48699/294015638-6503ad7b-bff8-4821-b94a-e5e07176ffdc.png" alt="294015638-6503ad7b-bff8-4821-b94a-e5e07176ffdc.png" />

## PDF form
- Maps to [question 6F on the PDF form](https://www.vba.va.gov/pubs/forms/VBA-21P-527EZ-ARE.pdf)
<img width="899" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeG1kQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5ec29bd0433c0d950cf26f12771e4011be5afffe/Screenshot%202024-01-04%20at%202.29.27%E2%80%AFPM.png" alt="Screenshot 2024-01-04 at 2.29.27 PM.png" />

---
## Tasks
- [ ] Reorder the existing questions found in prior marriage information page to the order listed above.

## Acceptance Criteria
- The 5 questions listed above will be reordered in the following order on the page:
1. How did the marriage end? (*Required)
2. Date of marriage (*Required)
3. Date marriage ended (*Required)
4. Place of marriage (city and state or foreign country) (*Required)
5. Place marriage marriage (city and state or foreign country) (*Required)

**Comment by vbellissimo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/72951?planning-poker) with Zenhub @danlim715 @scottsdevelopment @TaiWilkin @ToddWebDev @wayne-weibel

**Comment by aplatt-coforma** [comment]
Page is updated to match the requested ordering.
<img width="554" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTRVQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--391dfaaf71a8162c3336541ea520ac5417764a6f/Screenshot%202024-01-30%20at%209.53.23%E2%80%AFPM.png" alt="Screenshot 2024-01-30 at 9.53.23 PM.png" />
