### ISSUE TITLE
[BUG] [FE] Don't see events firing for the Review Page and 'submit-travel-pay-claim-45MR - success'

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#72961]
## Description

Don't see these GA Events firing: 

nav-check-in-yes-to-travel-review-45MR-clicked|nav-check-in-yes-to-travel-review-clicked

nav-check-in-no-to-travel-review-45MR-clicked|nav-check-in-no-to-travel-review-clicked

submit-travel-pay-claim-45MR - success

## Tasks

- [ ] Check and implement GA events

## AC

- [ ] Events are firing

**Comment by benbrasso-agile6** [comment]
I believe the Yes and No are working for the Review page. 

But, I don't think the 45MR event for a successful submission is working. I only see the default event, which should be used for the submissions from texting "check in." 

<img width="900" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVNuQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--25b45e8619f5d2482d6a9ddcdcf9ef95372eb492/Screenshot%202024-01-08%20at%209.53.19%E2%80%AFAM.png" alt="Screenshot 2024-01-08 at 9.53.19 AM.png" />

**Comment by benbrasso-agile6** [comment]
Those are the only two events I see firing that include "submit-travel-pay-". Should I be looking for a different event for the 45MR one? @wullaski

**Comment by wullaski** [comment]
@benbrasso-agile6 you are right. The code that logs the api success doesn't have the 45MR logic yet. I'll add that in as part of the PR.

**Comment by benbrasso-agile6** [comment]
saw one in prod
