### ISSUE TITLE
Request DOMO dashboard setup for Pension

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#72979]
## Issue Description
We need to request a DOMO dashboard, so that we can monitor web traffic once we go to production for the MVP relaunch of the Pension form.

Some other context:

- DOMO: Analytics team confirmed that there is NO current Pension form data set up anywhere in DOMO
- Google Analytics: There IS Pension form data set up in Google Analytics: https://analytics.google.com/analytics/web/#/report/content-event-pages/a50123418w177519031p176188361/explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.pagePath:www.va.gov~2Fpension~2F

---
## Tasks
- [ ] [Update this spreadsheet](https://docs.google.com/spreadsheets/d/1hopUPs_LcfXO8KHceJjYQD5ZKNSgnw-Ujefe_Ik8j3E/edit?usp=sharing) with all the updated form page URLs of the Pension form.
-- You can use staging environment to find permutations of the form, but...
-- I have found it easier to go through the form code from staging, [found in Github here](https://github.com/department-of-veterans-affairs/vets-website/blob/c48c331b660e814ee73034e5a83f7904244b2ebc/src/applications/pensions/config/form.js#L236C11-L236C15), highlighting the "path" found in each form, and updating the spreadsheet this way. It will also show the page titles.

- [ ] Request a Forms KPI DOMO dashboard from the Platform Analytics team by filling out [this analytics request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=michelle-dooley&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&projects=&template=analytics-request-and-update-kpi-dashboard.md&title=Analytics+New+KPI+dashboard+request+%26+KPI+dashboard+update+request+for+%5BTeam%5D).
- Request ticket: [Analytics New KPI dashboard request [Pension] #73162](https://github.com/department-of-veterans-affairs/va.gov-team/issues/73162)

Once the request is submitted, the Analytics team will log into BigQuery and then incorporate into DOMO dashboard.

**Comment by buddhima-coforma** [comment]
Submitted request https://github.com/department-of-veterans-affairs/va.gov-team/issues/73162
