### ISSUE TITLE
Step 4 Household info/dependent children who does not live with you: Move child address, custodian name & amount onto separate page

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#72994]
## Issue Description
<img width="534" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnVoQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0e7891ab40b3792d56e397dd1557f4a9c130a86d/Screenshot%202024-01-05%20at%2011.02.20%E2%80%AFAM.png" alt="Screenshot 2024-01-05 at 11.02.20 AM.png" />

Current version: In Step 4 of Dependent Children, if someone answers "No" to "Does your child live with you?", a set of 11 fields are revealed below within the same page:

Child's address:
- Country
- Street address
- Street address 2
- City
- State
- Postal code

Who do they live with?
- First name
- Middle name
- Last name
- Suffix

How much do you contribute per month to your child's support?
- Dollar number entry field

These are a lot of fields revealed at the same time and this practice goes against the latest accessibility recommendations to ensure if we use in-page conditional logic, we keep it to a minimum amount of fields (1-2?).

**We need to move the dependent child's information fields about their address, who they live with, and how much money the veteran contributes to their child support, onto a separate page, so that we don't come up against major accessibility concerns.**

---
## Acceptance Criteria
- [ ] The fields for Dependent Children information, if they do not live with them (as listed above), will be moved onto a separate page
- [ ] Ensure this new page only shows if they answer "No" to "Does your child live with you?"

---
## PDF mapping info
This maps to the following questions on the [PDF form](https://www.vba.va.gov/pubs/forms/VBA-21P-527EZ-ARE.pdf).
- 8P
- 8R
<img width="1075" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjZoQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b7610e38fe894d30b665c76ed999893d4360aecf/Screenshot%202024-01-05%20at%2011.05.09%E2%80%AFAM.png" alt="Screenshot 2024-01-05 at 11.05.09 AM.png" />

<img width="1074" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0NoQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--04b4343411cdad64e71466ca277e166ed847e552/Screenshot%202024-01-05%20at%2011.03.44%E2%80%AFAM.png" alt="Screenshot 2024-01-05 at 11.03.44 AM.png" />

**Comment by vbellissimo** [comment]
Hi @zack , correct. Thanks for double checking.

cc @mayacoforma @katherine-fung

**Comment by aplatt-coforma** [comment]
Content looks good. 
[screencapture-staging-va-gov-pension-application-527EZ-household-dependents-children-address-0-2024-01-10-16_54_09.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2EzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--12b92641e21b08cd10b9009058c90fc3bcb4207f/screencapture-staging-va-gov-pension-application-527EZ-household-dependents-children-address-0-2024-01-10-16_54_09.pdf)

**Comment by vbellissimo** [comment]
@aplatt-coforma @zack I'm actually still seeing these fields on the original page, below the "does your child live with you?" question.

<img width="777" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMG03QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b1d200d555e559c8e5a7d015f3a6a9a922aa8a07/Screenshot%202024-01-11%20at%209.25.35%E2%80%AFAM.png" alt="Screenshot 2024-01-11 at 9.25.35 AM.png" />

**Comment by aplatt-coforma** [comment]
Retested this with today's build and I am now seeing the question "Does the child live with you?" and the additional fields on separate pages.
<img width="872" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelM5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--62247eee728fd4c07ff11009aadcb23e7940b4c5/screencapture-staging-va-gov-pension-application-527EZ-household-dependents-children-inhousehold-0-2024-01-11-10_27_29.png" alt="screencapture-staging-va-gov-pension-application-527EZ-household-dependents-children-inhousehold-0-2024-01-11-10_27_29.png" />
<img width="529" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelc5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--35c452f4ba3f87e74906d2f3dc634b3f5ef93242/screencapture-staging-va-gov-pension-application-527EZ-household-dependents-children-address-0-2024-01-11-10_26_51.png" alt="screencapture-staging-va-gov-pension-application-527EZ-household-dependents-children-address-0-2024-01-11-10_26_51.png" />

**Comment by vbellissimo** [comment]
@zack @aplatt-coforma 

I'm flagging that when you answer "no" to "does "Does your child live with you?", the follow up page with the fields we separated onto a separate page are still showing up in staging.

Please ensure this new page with the fields for child's address, who they live with, and how much they contribute, shows **_only_** if they answer "No" to "Does your child live with you?".

**Comment by vbellissimo** [comment]
Related ticket, that seems like @TaiWilkin worked on, to remove "Your" from the fields asking for info about who the child lives with:

Step 4 household info: Update copy to remove "your" from Dependent Child/Who they live with Info #73291
