### ISSUE TITLE
Update designs for Step 4 dependent children section

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#72996]
## Issue Description
As a Pension team,
we need updated designs for Step 4 of the form flow related to Dependent Child(ren),
so that we can use as a reference amongst our team and stakeholders alike.

On Fri, Jan 5, we discussed as a group on how to update the UI for Step 4 / Dependent child(ren) section for the MVP relaunch of the form. 

---
## Tasks
- [ ] Create new designs of the form flow and pages for Step 4/Dependent Child(dren) of the Pension form [based on this document](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1697736525149/26590ab628618a5e2b86232397286eab8e7f8a1d?wid=59-1704397563384)

## Acceptance Criteria
- We will have high-fidelity designs of the form flow and pages for Step 4's Dependent Child(dren) section

**Comment by gmaciolek** [comment]
The form in production matches the flow described in [the MURAL document](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1697736525149/26590ab628618a5e2b86232397286eab8e7f8a1d?wid=59-1704397563384&sender=u7ebefd98ade29ab3794a2544), but the Figma files are not up-to-date.

I'd like to keep this open as a design ticket for myself. I need to update designs for the list/loop/multi-response patterns in the flow anyway. I could start with this one.

**Comment by gmaciolek** [comment]
Dependent children designs are [updated in Figma](https://www.figma.com/file/9JKK5Eo43uJWEr66JPiebc/Pension-Claim-Form-21P-527EZ?type=design&node-id=2031%3A58138&mode=design&t=z7ofhG2z9Fagu35q-1) to match production.
