### ISSUE TITLE
Figma access request -  Charlotte Cesana

### ISSUE THREAD

**Issue by HeatherRienks** [department-of-veterans-affairs/va.gov-team#73000]
### Name

Charlotte Cesana

### Email

charlotte@cityfriends.tech

### Role

Sr. Researcher

### Team

Debt Resolution 

### Product Manager (PM) name

Tom Davis

### Additional Notes

Charlotte needs view access please. She will not need to edit. Thank you!

**Comment by charlottecesana** [comment]
Thank you @HeatherRienks ! I also need edit access.

**Comment by naomimarcussen** [comment]
An invitation has been sent to charlotte@cityfriends.tech

**Comment by charlottecesana** [comment]
Hi @naomimarcussen, thank you for the quick follow up! I was wondering if I could get edit access?

**Comment by naomimarcussen** [comment]
Yup, I just granted you edit access. It may take a moment to go through :)

**Comment by charlottecesana** [comment]
Got it @naomimarcussen! Thank you again :)
