### ISSUE TITLE
Sanitize Yellow Ribbon data

### ISSUE THREAD

**Issue by kelsonic** [department-of-veterans-affairs/va.gov-team#7302]
# Description

The current Yellow Ribbon production CSV has 365+ unique values for the column `degree level`.

The current Yellow Ribbon production CSV has 870+ unique values for the column `division professional school`.

Ideally both of these columns would have a fixed number of unique values no greater than 5-20 so that:
1. we can start using the columns for filtering and
2. we can start showing the columns' data on the frontend without worrying about bad data.

## Resources

[Original Production Yellow Ribbon CSV](https://app.zenhub.com/files/33202667/9c9e0566-1e9f-4cc3-b8bd-f3616bd5566d/download)

[Upload future Production Yellow Ribbon CSV with updated `degree level` column]

[Upload future Production Yellow Ribbon CSV with updated `division professional school` column]

## Acceptance Criteria

- [ ] Update `degree level` column values to not have spelling inconsistencies.
- [ ] Update `division professional school` column values to not have spelling inconsistencies.

**Comment by kelsonic** [comment]
Updated the `degree level` column to just 7 unique values! 🎉 

[YellowRibbonProgramSource_GIDS_03252020 - YellowRibbonProgramSource_GIDS_03252020-updated-degree-level.csv.zip](https://github.com/department-of-veterans-affairs/va.gov-team/files/4394399/YellowRibbonProgramSource_GIDS_03252020.-.YellowRibbonProgramSource_GIDS_03252020-updated-degree-level.csv.zip)

**Comment by MickinSahni** [comment]
Adding as unplanned sprint 18

**Comment by kelsonic** [comment]
@jenniferlee-dsva Just to confirm, but from our conversation with @andaleliz on Friday it sounds like we will scrap this ticket. Or should we modify it to "Fix spelling/casing errors in YR data"?

**Comment by MickinSahni** [comment]
2020-03-30 PW Standup
- We're able to make spelling fixes and sent an updated version of the cleaned data to public websites channel and Brian Grubb
- Kelson to upload data here as well (and close-out assuming AC is ✔️)

**Comment by kelsonic** [comment]
[Yellow Ribbon production CSV with spelling fixes in `degree level` and `division professional school` columns.](https://github.com/department-of-veterans-affairs/va.gov-team/files/4403909/YellowRibbonProgramSource_GIDS_03252020.-.YellowRibbonProgramSource_GIDS_03252020.csv.zip)

**Comment by kelsonic** [comment]
All values over 40k:
```
40000
42000
43200
47000
50000
85000
99000
99999
100000
108150
123456.5
130680
500000
999999
9999999
99999999
```

**Comment by kelsonic** [comment]
We currently have this logic:

```js
  if (contributionAmountNum > 90000) {
    return 'All tuition and fees not covered by Post-9/11 GI Bill benefits';
  }
```

Asking for confirmation from the YR team what that `90000` value should be before validating/closing this ticket. CC @MickinSahni

**Comment by MickinSahni** [comment]
2020-04-01 PW Standup
- sent email to stakeholder re: max value, awaiting response
  - question is what the threshold is to display 'unlimited funding amount'
  - if we don't get an answer, we're moving forward with >90,000

**Comment by MickinSahni** [comment]
2020-04-02 PW Standup
- this cannot be closed quite yet. sounds like stakeholders want 99,999 as the ceiling 
- have a question out to @jenniferlee-dsva to confirm whether it makes sense to just show the raw data opposed to `All tuition and fees not covered by Post-9/11 GI Bill benefits`

**Comment by MickinSahni** [comment]
2020-04-06 PW Standup
- Keeping the "unlimited ceiling" as $90,000. 
  - @jenniferlee-dsva we sent Janice a list of schools that are over this ceiling so she can figure out what the ceiling should be. We are going to close this out, however, and create a follow-on ticket if necessary. That said -- we'd like to avoid last minute changes from folks so appreciate any guidance/tips you might have.

**Comment by jenniferlee-dsva** [comment]
^ - Clarification needed: is 90K or 99,999? The last round of slacks I saw indicated that Janice requested that only 99,999 should be transformed in the UI as `All tuition and fees not covered by Post-9/11 GI Bill benefits`

And we are waiting for her confirmation post-Kelson's email to her with example scenarios of schools that have data field values of more than 99,9999.   @kelsonic @MickinSahni (Can't seem to @John Hashimoto fysa)
