### ISSUE TITLE
Pull all emails for organic and reactivation

### ISSUE THREAD

**Issue by lmorris3** [department-of-veterans-affairs/va.gov-team#73071]
In preparation for the communication campaign, we need to have our email lists up to date and ready to load into GovDelivery.

Acceptance Criteria:
- pull email addresses for the following reactivation segments:
- MHV/DSL + ID.me
- MHV/DSL + Login.gov
- MHV/DSL + Login.gov and ID.me

- pull email addresses for organic segment:
- MHV/DSL only (no ID.me or Login.gov)

- indicate which segment each email address falls into
- send the email lists to Carl (carl@themostudio.com) and Lauren (Lauren@themostudio.com)

**Comment by sdickson-gt** [comment]
This is done and provided via VA Teams.

**Comment by lmorris3** [comment]
Completed - closing.
