### ISSUE TITLE
Make a spreadsheet to track content changes

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#7307]
Given that the program team has provided comments on the contents
I want to generate documentation to track the comments and which ones were implemented
So that we can build understanding of what changes are taking place and be able to reference the provided comments in the future.

**Comment by psanders86** [comment]
##### Highlighted fields were not changed

[https://app.zenhub.com/files/133843125/9210264f-9dc4-4b12-a6cd-94052da5888e/download]
