### ISSUE TITLE
"Join Appointment" button not enabled on appointment details page

### ISSUE THREAD

**Issue by JRRoof** [department-of-veterans-affairs/va.gov-team#73084]
## Summary
The “join appointment” video button *is not enabled on the appointment details page for user ½ hour before appointment time when user is in different time zone than facility.

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/97117349/6178c706-8d38-4da1-9f5e-8e410c472a43)

VAOS tester is in MST and the tester’s current time is 3:45 PM MST which is 5:45 EST (which falls within ½ hour before appointment time). The join appointment button should be enabled but is not.  Enabling button should be based off of current time at facility, not current time in user's time zone.

## Specs
- Device: Any
- Browser: Any

## Steps to Reproduce
**Test User:** brienne.b.ferrara@id.me
**Password:** Password1234!

1. User is in a different time zone than the facility associated with the video appointment.
2. Contact Marcy Nadeau to create appointment for troubleshooting and testing.

### Actual Result
"Join Appointment" button is not enabled 1/2 hour before appointment when user is in a different time zone than the facility of the appointment.

### Desired Result
"Join Appointment" button is enabled 1/2 hour before appointment regardless of the time zone the user is in.

## Definition of Done
- [ ] Desired result is achieved and/or document decisions made
- [ ] Relevant documentation is updated

---

**Comment by ldelacosta** [comment]
@JRRoof - this is ready to be tested in staging. If everything looks good, please close out the ticket.

**Comment by JRRoof** [comment]
Validated with Marcy that the button is now active prior to the appointment with an appointment in EST and a user in MST.
