### ISSUE TITLE
Add exhaustion queue handler to EVSS::DocumentUpload sidekiq job (app\sidekiq\evss\document_upload.rb)

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#73083]

**Comment by freeheeling** [comment]
@austinjprice This document upload job appears to be different than the job that handles uploads that are part of the form 526 submission process. If my understanding is correct, the `EVSS::DocumentUpload job` is used by the Claim Status Tool, in which new evidence may be uploaded for any initial claim, not only 526. `EVSSClaimService` even has a comment that `upload_document `will "upload file to s3 and enqueue job to upload to EVSS, used by **Claim Status Tool**". That is where `EVSS::DocumentUpload.perform_async` is called.

If that is in fact the case, adding an exhaustion queue will impact more than 526 and our team may not necessarily be the only/best team to determine the preferred implementation. I am, however, okay with devising a process similar to the one we currently have in place for form 526's ancillary jobs if it is still desired that I proceed. However, Steve Albers, mentioned that he will pass the request to Jacob Worrell and Jerek Shoemaker.

**Comment by freeheeling** [comment]
Moving to Done, unless it's later determined that we should fulfill this need.

**Comment by freeheeling** [comment]
@austinjprice Something that was puzzling was whether the [wrapper](https://github.com/department-of-veterans-affairs/vets-api/commit/4d8acb5b00a0ba06741ff051e56b102590e23ac7#:~:text=%2C%20%3Adocument_hash-,wrap_with_logging(,),-%23%20retry%20for%20one) inserted by @SamStuckey may need to be modified, if the job is utilized by the Claim Status Tool for a variety of claim types, and not specifically 526ez.
