### ISSUE TITLE
DBEX Team - Migrate Sketch files to Figma

### ISSUE THREAD

**Issue by mengA6** [department-of-veterans-affairs/va.gov-team#73099]
Sketch access will expire 2/16/24.

[Slack guidance for migration to Figma](https://dsva.slack.com/archives/C053UDWMH7U/p1702322980490389)

Figma: [Disability Benefits team](https://www.figma.com/files/project/176170217/Disability-Benefits?fuid=1316144381141327842)

**Comment by pacerwow** [comment]
Can this be closed?

**Comment by mengA6** [comment]
Yes, closing it now!
