### ISSUE TITLE
Clear stale results after a rating value is added, changed, or removed

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#731]
After a user submits their rating values into the calculator, the combined disability rating becomes visible in the bottom results panel, which currently only refreshes when the user again submits the form. This is a problem, because if the user's rating values are modified (by editing a rating value, adding or removing one), the results panel will still only reflect the combined disability rating from the last submit, which means this value is now stale and could be misleading to users.

We should explore -

1. Replacing the combined disability rating with dashes if the user submits the form then changes their rating values. 
2. Automatically hiding the results panel if the user submits the form then changes their rating values.

**Comment by rtwell** [comment]
My suggestion would be to replace both instances of the % (the large type "VA disability rating" as well as the smaller type in the paragraph below) with dashes as soon as a user a) adds or deletes a row, or b) changes a number (changing the description doesn't trigger). 

![image](https://user-images.githubusercontent.com/12564977/63348323-00702080-c327-11e9-9e44-4dff593deeb4.png)

**Comment by ncksllvn** [comment]
While doing this work, also update error messages here - https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19139#issuecomment-534742591

**Comment by ncksllvn** [comment]
The work here is done and will be on Staging in about ten minutes or so!

**Comment by Karak888** [comment]
@ncksllvn Are we still awaiting Validation or we are good to close?  please let me know, thanks!

**Comment by ncksllvn** [comment]
@Karak888 maybe you can validate? 😄 See the comment above, https://github.com/department-of-veterans-affairs/va.gov-team/issues/731#issuecomment-523002184, and test it out on the Disability Calculator.

**Comment by Karak888** [comment]
Closing this out as the work has been completed.
