### ISSUE TITLE
Design | Migrate Designs to Figma

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#73106]
## Issue Description
_The VA is migrating design artifacts from Sketch to Figma, so all artifacts need to be moved into Figma before access to Sketch is discontinued._

---
## Tasks
- [x] Move relevant design artifacts into Figma.

## Acceptance Criteria
- [x] All 686/674 design artifacts are in Figma.
---

**Comment by ajialeilani** [comment]
Completed font updates and updated covers, which you can see [here](https://www.figma.com/files/project/176499824/Dependents?fuid=1162589264693037465). 

Still some minor spacing issues in the military address file, which I'll correct alongside work on 686c/674 updates.
