### ISSUE TITLE
Contact Center Review for Pension Benefits Team - Pension 527ez Form Product Guide

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#73112]
# Request the Contact Center Review 

## Description
Hello. Our team will be re-launching the Pension Benefits 527ez form online by the end of this month (January 2024). It was deactivated in November 2023. We're providing some artifacts so the Contact Center team is aware of our relaunch.

### Product Guide & Video
- [Link to Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/527EZ-reactivation-initiative-brief.md), with more information.
- [Link to video walkthrough](https://dvagov.sharepoint.com/:v:/r/sites/vaabdvro/Shared%20Documents/Pension/pension%20staging%20screenshots/01-09-23-Final%20Staging%20Walkthrough.mp4?csf=1&web=1&e=hbZGBS) _Requires sharepoint access_

### Launch Date
[Link to Release Plan](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1704481084114/b171b0540054b2844cb7977dd7dd2dfb7aab9c48?sender=u9d01ee38af217e4877e75660); may still be evolving on exact dates of incremental volume release.

### Product Guide
[Link to updated Product Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pension/Pension%20527ez%20Form%20Product%20Guide%20Jan%202024.pages), revised January 2024

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by vbellissimo** [comment]
Just wanted to share a heads-up that I also just added a video walking through the form in staging in the body of this ticket.

**Comment by starlow00** [comment]
@vbellissimo Do you have the product guide in Word format? Pages doesn't always handle images well when I convert it to Word, and that appears to be the case here.

**Comment by starlow00** [comment]
@vbellissimo Actually, just Word, not RTF.

**Comment by vbellissimo** [comment]
Oh no, sorry about that! I don't have Word installed, unfortunately. I will ask someone in my team if they can convert to Word. I'll keep you posted.

**Comment by starlow00** [comment]
@vbellissimo Actually, don't worry about it this time. I think I see how I can manage; it will just require some image adjustments. For the future, though, if Word isn't available, use Rich Text Format. That plays better with Word :)

**Comment by starlow00** [comment]
Sent to VEO for review

**Comment by starlow00** [comment]
No changes from VEO. Current copy attached.
[Pension 21P-527EZ Form Product Guide Jan 2024.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjIrQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3006b1d9636890a287b3c797b7e049b4688015a1/Pension%2021P-527EZ%20Form%20Product%20Guide%20Jan%202024.docx)

**Comment by jstrothman** [comment]
Uploaded final to the products > pension > [product guide folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/pension/product-guide)
