### ISSUE TITLE
SOCKS access for Matthew Knight

### ISSUE THREAD

**Issue by mjknight50** [department-of-veterans-affairs/va.gov-team#73119]
### Your Name

Matthew Knight

### Your Email

matt.knight@coforma.io

### Your Role and Team

Engineer, VA Benefits Non Disability Benefits DSVA

### Product Manager (PM) name and email

Anh Platt, anh.platt@coforma.io

### Product Owner (PO) name and email

Emily Theiss, emily.theis@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCtJwaSXDxECVwtLu5akw4tru0WC+6vQAO1r7lDF7I1xUBfCJzvFnG6RGGPcJp/bHpF7TSWMUZmZ32eTI0Xrol6369F2YJQ1OB0BJBsbkaQHw5U6pIu5U3ZvIGnz6PzIn5Y0ZzmNDxV4AHF8ruode2hu8XYstGodT16R8BNpF166G4a6PUVt6zSKM9XsT5K8f6h8dzfHpp4Kj6oGT85uCPoaHVC2jPwMYrfMEucvBM+aFcqRU+vNi3QTLzX3VPs5+09U5Da5ccaLhzQUX0aFSDurBXG0L1+o9S9ioM+bgzUMKWsuaa5di3yn+x7HOV3d/A1AFk2Sx6wl+dYA1pUP4LPTJGdSv41o37kZvcZc8Iz8v5yoDqpPMYKKZTesjFMVaFl9RJih4lryjvKsMoHuC1HdF6MpRq77DtiXY/7GbQkzWsxYTs+Tz0dDn1KpaM3KPrZRJ0SX0FAf48VDkEFiAgH1Gtf8KtDv65XywAkAfxHcnYq+qfOExlD1WoSLWgLj8U= knight@Coforma-G2HK4K6K24-Matt-Knight.local

### E-QIP Transmittal Confirmation

[e-quip.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/13865117/e-quip.pdf)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by patrick-black-oddball** [comment]
Complete
