### ISSUE TITLE
Figma access request - Anastasia Jakabcin - Auth Experience My VA

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#73126]
### Name

Anastasia Jakabcin

### Email

ana@adhocteam.us

### Role

Product Manager

### Team

Authenticated Experience My VA

### Product Manager (PM) name

(myself)

**Comment by naomimarcussen** [comment]
An invite has been sent to ana@adhocteam.us.

**Comment by ajakabcin** [comment]
thank you!
