### ISSUE TITLE
Step 4: Update copy typo for Marital Status

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#73130]
## Issue Description
Update the Marital Status typo:

<img width="672" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVNxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0dc94cbd2fb0a004bc17f4d9957959c4d5dc34f7/Screenshot%202024-01-08%20at%204.07.04%E2%80%AFPM.png" alt="Screenshot 2024-01-08 at 4.07.04 PM.png" />

---
## Tasks
- [ ] On Step 4, Household information, please update the typo found from "Martial status" to "Marital Status".

**Comment by aplatt-coforma** [comment]
Content looks good
<img width="1127" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzIzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--72d629c8a1be8a68b76a9964656447d68a6a5c3f/Screenshot%202024-01-10%20at%204.49.21%E2%80%AFPM.png" alt="Screenshot 2024-01-10 at 4.49.21 PM.png" />
