### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by bevnobev** [department-of-veterans-affairs/va.gov-team#73132]
### Name

Beverly Nelson

### Email

beverly.nelson@va.gov

### Role

Everyone

### Team

VA Notify

### Product Manager (PM) name

Melanie Jones

### Additional Notes

I'm the product owner for VA Notify so a everyone role should be fine.

**Comment by naomimarcussen** [comment]
Hi! An invitation has been sent to beverly.nelson@va.gov.
