### ISSUE TITLE
Adding Joshua Jaggat to DSVA Slack

### ISSUE THREAD

**Issue by huggins-va** [department-of-veterans-affairs/va.gov-team#73135]
Please add Joshua Jaggat to DSVA Slack as a full member, multi-channel user. 
Joshua is new DevOPs engineer on PTEMS/Lighthouse program working on New DI team with Honey Badgers.

**Comment by LEHigley** [comment]
@huggins-va need an email address

**Comment by huggins-va** [comment]
joshua_jaggat@bah.com
