### ISSUE TITLE
Content review for new FSR form format

### ISSUE THREAD

**Issue by strelichl** [department-of-veterans-affairs/va.gov-team#73145]
## Issue Description

We recommended the team move the wizard to a new static page instead of using a subtask pattern within the form. We'll need to make sure the actual FSR form is still formatted correctly.

Edited 1/17 to reflect our kickoff conversation- please update if I'm not capturing it right!

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_

**Comment by aliyahblackmore** [comment]
**Updates:** 

- Laura and I synced on 1/10 and she’s getting more guidance from IA and Danielle on how we’ll need to approach wizard to subtask requests, as there are a few other wizard requests. Updates here TBD.
- Laura will cover this while I'm OOO and pull me in, if needed, when I'm back online next week.
- Laura is also confirming with the FSR product team when they'll need content.

**Comment by laurwill** [comment]
This is blocked until we get guidance from OCTO on how to proceed.

**Comment by laurwill** [comment]
Here's my proposed page structure to capture the wizard content on a new **Request help with VA debt** page. The structure may shift a bit as we draft, but this is the general idea. It's a long page, so we'll consider accordions, on this page component, etc, to help with scanability.

@DanielleThierryUSDSVA did you want to review this approach before we share with Denise and start drafting? (@kristinoletmuskat has approved for IA.)

# [H1] Request help with VA debt

Find out how to get help. 

## [H2] Health care copays

### [H3] Request help with health care copays

Link to existing page with FSR, payment plan, and exemption options
https://www.va.gov/health-care/pay-copay-bill/financial-hardship/ 

### [H3] Dispute copay charges

https://www.va.gov/health-care/pay-copay-bill/dispute-charges/ 

## [H2] Attorney fees and separation pay

By phone

## [H2] Rogers STEM program overpayments

### [H3] By email 
### [H3] By mail

## [H2] Vet Tec program overpayments

### [H3] By phone
### [H3] By email 
### [H3] By mail

## [H2] All other benefit overpayments

### [H3] Dispute the debt

#### [H4] Through Ask VA 
#### [H4] By mail

### [H3] Request a decision review about the decision that resulted in the debt

[Learn about decision review options](https://www.va.gov/decision-reviews/)

### [H3] Request debt relief (waiver or compromise offer)

If you’re a Veteran or service member, do online FSR.
Online FSR
If you’re a spouse or dependent, do PDF FSR.
PDF FSR

### [H3] Request a payment plan

#### [H4] If you need 5 years or less to repay
Phone 

#### [H4] If you need more than 5 years to repay
If you’re a Veteran or service member, do online FSR.
Online FSR
If you’re a spouse or dependent, do PDF FSR.
PDF FSR


**Note:** Other wizard content not represented here, that we’ll need to work in somewhere:

* If you did an FSR in past 6 months, you don’t need to do another one
* If you’re trying to make a payment (not request help with debt), go to the payment portal
* If you disagree with our decision on a waiver request, you can request a Board Appeal or ask the Committee of Waivers and Compromises to reconsider

**Comment by charlottecesana** [comment]
Hi @laurwill thank you for working on this! We are looking forward to connecting with your team to create the VA debt static informational page. I wanted to share a simplified [document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/combined_fsr/wizard/research/VA-debt-action-paths.md) our UX team created to outline the action paths a Veteran can take if they have VA debt. This is a simplified version of the information contained in the Wizard. We learned also from our research that there is a lack of awareness about what Veterans can do if they have VA debt, so this static page will be very important to convey their rights, obligations, and options. 
Thank you!
@mgleo @josephrlee @denisecoveyduc @Tom-Davis @HeatherRienks

**Comment by laurwill** [comment]
Hi @charlottecesana ,

Couple questions as we're drafting the new page. 
- The wizard says that if you've submitted an FSR in the past 6 months, you don't need to submit a new one unless your situation has changed. Does this mean that even if your situation doesn't change, you must submit a new FSR every 6 months to confirm your information?
- If you do need submit FSRs every 6 months, does the online form save your information from your last submission?

Thank you!

**Comment by mgleo** [comment]
Hi @laurwill, we have some people out this week but I'm working on finding the answer to your first question.
Once a user submits a form, their information is not saved for their next form submission but this may change in the future.

**Comment by HeatherRienks** [comment]
@laurwill - I am assisting @mgleo on the first question; we are still awaiting a response. Thanks!

**Comment by laurwill** [comment]
Thanks @denisecoveyduc !
What's the significance of the 6 month time period? Does it take us about 6 months to decide FSR requests, or is there some other reason this time period is important? 
If there's nothing special about changes in the last 6 months, we could instead say "If your financial situation changes or you receive a new debt letter from us, you can submit a new FSR with your updated information."

**Comment by laurwill** [comment]
Hi all, closing this ticket to consolidate and track all static page work related to FSR in this new ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/92685
