### ISSUE TITLE
Step 4: Update copy for employment button

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#73146]
## Issue Description
Update the current "Add another employment" button to "Add another job"

<img width="672" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXFxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d92100f9abae03c62722e89ef3fe875f0a439d79/Screenshot%202024-01-08%20at%204.07.36%E2%80%AFPM.png" alt="Screenshot 2024-01-08 at 4.07.36 PM.png" />

---
## Tasks
- [ ] On Step 4, Household information / Current employment, update the current "Add another employment" button to "Add another job"

**Comment by vbellissimo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/73146?planning-poker) with Zenhub @danlim715 @scottsdevelopment @TaiWilkin @ToddWebDev @wayne-weibel

**Comment by wayne-weibel** [comment]
this is related to https://github.com/department-of-veterans-affairs/va.gov-team/issues/73300
and will conflict/expand the change made there

**Comment by wayne-weibel** [comment]
The button on Previous Employment will also be updated with this change and the current setup

**Comment by aplatt-coforma** [comment]
Text looks good.
<img width="800" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMklVQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--baddb6fc87fee0fc14b0c8895f9161bca77b71a8/Screenshot%202024-01-30%20at%209.58.20%E2%80%AFPM.png" alt="Screenshot 2024-01-30 at 9.58.20 PM.png" />
