### ISSUE TITLE
Step 6 Additional info / Faster claim processing: Make question required

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#73152]
## Issue Description
<img width="672" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMytxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1400488ab251595ee008c7bdcbafce7bdb446103/Screenshot%202024-01-08%20at%201.52.46%E2%80%AFPM%20%281%29.png" alt="Screenshot 2024-01-08 at 1.52.46 PM (1).png" />

---
## Tasks
- [ ] Remove the parentheses and word "optional" from the question title
- [ ] Make the question required

**Comment by aplatt-coforma** [comment]
Content looks good.
<img width="947" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3UzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--305f814ee7de9b38e22f9405c160932fe9815282/Screenshot%202024-01-10%20at%204.47.35%E2%80%AFPM.png" alt="Screenshot 2024-01-10 at 4.47.35 PM.png" />
