### ISSUE TITLE
Create design to add existing signature component to the end of form

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#73157]
## Issue Description

Related to #73016

---
## Tasks
- [ ] Create design to add existing signature component to the end of form

**Comment by gmaciolek** [comment]
The Figma design for this page is a bit of a mess, but the statement of truth component is on there. I don't think updating this particular design is a high priority right now. 

I propose closing this ticket, but I do have a question for @katherine-fung: The Statement of truth component in the design system Figma library (and what we have implemented in production) includes the text, "I have read and accept the privacy policy" with the little icon at the end, indicating that the link opens in a new tab. I thought the guidance was to not use the icon and instead write out "(opens in new tab)"?

<img width="1232" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMW1KQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--48765f4b2de49d2faf35c426e59b503a8ffee79f/Screenshot%202024-02-25%20at%2012.32.08%20AM.png" alt="Screenshot 2024-02-25 at 12.32.08 AM.png" />

**Comment by gmaciolek** [comment]
@buddhima-coforma and @matt4su This ticket can be closed. The Statement of Truth component is included at the end of the form and Katherine answered my question somewhere in Slack. (It's OK to use the icon to indicate that a link opens in a new tab within certain approved design system components.)
