### ISSUE TITLE
Update designs for Type of marriage question

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#73159]
## Issue Description
Related to #72867

---
## Tasks
- [ ] Update design artifacts in Figma to match staging environment experience for the current Type of Marriage question.

**Comment by gmaciolek** [comment]
The design file needs a small update to show conditional text for type of marriage

**Comment by gmaciolek** [comment]
[Updated Figma designs for type of marriage question](https://www.figma.com/file/9JKK5Eo43uJWEr66JPiebc/Pension-Claim-Form-21P-527EZ?type=design&node-id=2202%3A71211&mode=design&t=z7ofhG2z9Fagu35q-1)
