### ISSUE TITLE
Drop node@v14 with node@v16 - vets-website

### ISSUE THREAD

**Issue by acald-creator** [department-of-veterans-affairs/va.gov-team#73166]
`vets-website` currently is on `node@v14`.

It has reached EOL on October 2020, and security support ended February 2023. See link for dates: https://endoflife.date/nodejs

- [ ] Change node engine to `">=16.20.2 <18"`
- [ ] Replace `v14` with `v16` in Dockerfiles and `.nvmrc`
- [ ] Check GitHub Actions to ensure that the build works correctly

**Comment by parkerbees** [comment]
Moved to Jira. Closing.
