### ISSUE TITLE
(Figma) Update designs for Military Service questions

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#73160]
## Issue Description
Update design artifacts in Figma to match staging environment experience for Military Service questions.

**Comment by gmaciolek** [comment]
A few small updates should be made to the Figma files for the Military service questions. I'd like to keep this one open as a design task for myself. Padding the time to clean up the designs while I'm in there.

**Comment by echin393** [comment]
[Link to Figma updates here.](https://www.figma.com/file/9JKK5Eo43uJWEr66JPiebc/Pension-Claim-Form-21P-527EZ?type=design&node-id=2030-24704&mode=design)
