### ISSUE TITLE
Replace node-sass with sass - vets-website

### ISSUE THREAD

**Issue by acald-creator** [department-of-veterans-affairs/va.gov-team#73167]
`node-sass` has recommended to move on to `dart-sass` / `sass`

Requirements:

- [ ] Remove `node-sass`
- [ ] Remove `npm rebuild node-sass` in `scripts`
- [ ] Add `sass` and upgrade `sass-loader` to use its latest API
- [ ] Run below to migrate to latest API from `sass`
	- [ ] `sass-migrator division **/*.scss`
	- [ ] `sass-migrator strict-unary **/*.scss`

**Comment by acald-creator** [comment]
Move to backlog for now

**Comment by parkerbees** [comment]
Moved to Jira. Closing.
