### ISSUE TITLE
Flipper UI access for [Kyle Henson]

### ISSUE THREAD

**Issue by khenson-oddball** [department-of-veterans-affairs/va.gov-team#73170]
### Your Name

Kyle Henson

### Your GitHub handle (Flipper UI access is managed through GitHub)

@khenson-oddball

### Team, Role, and Company of the target individual

VA.gov IIR Product Team, Tech Lead, Oddball

### Please confirm if you are on Atlas, Platform Team Roster or are a Federal User

- [X] [Atlas](https://dev.va.gov/atlas)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [X] Lesser Environments (Dev/Staging/Sandbox)
- [X] Production (if requesting, justify prod access below)

### Reason for Production Access (If requested)

My team and I will be implementing features that will be behind feature flags for various projects. Having Production access could allow us to test out our changes in production without needing the help of others to turn on and off.

**Comment by bdech** [comment]
Found in Atlas.

E-QIP found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/71483)

**Comment by bdech** [comment]
Hi @khenson-oddball , you have been granted access to production and lesser environments.
