### ISSUE TITLE
IPP - Case Number should populate on last screen

### ISSUE THREAD

**Issue by lmorris3** [department-of-veterans-affairs/va.gov-team#73174]
#### What I expected to happen

1. I sign in to the Proofing Agent Application
2. I advance to the final screen
3. I see all information, including Case Number, to review

#### What actually happened

1. I sign in to the Proofing Agent Application
2. I advance to the final screen
3. I do not see the Case Number in the "Case Number" field.

#### What _SHOULD_ happen

1. I sign in to the Proofing Agent Application
2. I advance to the final screen
3. The case number should populate in the "Case Number" field.

#### Screenshots or Supporting Evidence
<img width="480" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0N1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6549095f744564dcc5bea860ae9766073cfdd201/Screenshot%202024-01-04%20at%205.26.10%20PM.png" alt="Screenshot 2024-01-04 at 5.26.10 PM.png" />

#### Platform
Vercel

#### OS version and Browser version (if applicable)
Google Chrome

#### App version (build)
IPP Proofing Agent Application v1

#### Affected environment(s)
QA

#### Severity of the issue
- [ ] High severity
- [x] Medium severity
- [ ] Low severity

#### Visibility
- [x] User visible
- [x] Stakeholder visible

#### MR Approver
- TBD

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by moanu404** [comment]
Moving to icebox based on https://themostudio.slack.com/archives/C03UP9MHKBN/p1704830834117579 not necessary for Usability Testing but might need to verify the done-ness later on

**Comment by mateoclarke** [comment]
I think this should be marked complete with this PR from @moanu404 https://github.com/department-of-veterans-affairs/va-in-person-identity-proofing/pull/28
