### ISSUE TITLE
IPP - Calendar Picker not showing in DOB selection

### ISSUE THREAD

**Issue by lmorris3** [department-of-veterans-affairs/va.gov-team#73175]
#### What I expected to happen

1. I sign into the Proofing Agent application and advance through the screens to the "fill in information" page
2. I see a date picker next to the DOB field
3. I can click on the date picker icon to choose the DOB in a calendar view

#### What actually happened

1. I signed into the PA application and advanced through the screens
2. I see a DOB field but I do not see a DOB picker icon
3. If I click on the blank space next to the DOB field, the date picker calendar appears

#### What _SHOULD_ happen

1. I sign into the PA application and advance through the screens
2. I see a DOB field and I should see a calendar icon next to it
3. If I click on the blank space next to the DOB field, the date picker calendar should appear
4. I should be able to use the calendar to select the DOB

#### Screenshots or Supporting Evidence
<img width="549" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFd1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d88fbdf46ef122c64bdeb760b5900a89e63fd27e/Screenshot%202024-01-09%20at%208.59.10%20AM.png" alt="Screenshot 2024-01-09 at 8.59.10 AM.png" />

<img width="526" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGV1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--97154ecad2380e504dffe56794b268d1666f6465/Screenshot%202024-01-09%20at%208.59.18%20AM.png" alt="Screenshot 2024-01-09 at 8.59.18 AM.png" />

#### Platform
Vercel

#### OS version and Browser version (if applicable)
Google Chrome

#### App version (build)
IPP Proofing Agent Application v1

#### Affected environment(s)
QA

#### Severity of the issue
- [ ] High severity
- [ ] Medium severity
- [x] Low severity

#### Visibility
- [x] User visible
- [x] Stakeholder visible

#### MR Approver
- TBD

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mateoclarke** [comment]
Looks like this is an image rendering issue specific to the Vercel deployment. The same thing happens with the "+" and "-" icons on the accordions. Will investigate...

**Comment by mateoclarke** [comment]
Here is the commit where we addressed this issue:
https://github.com/department-of-veterans-affairs/va-in-person-identity-proofing/commit/a4e1b1b24993b9e670b491a00f5bc7b3b9f995e1
