### ISSUE TITLE
Hold Orientation for Steve, Kelly, and Jennifer (scheduled for Thursday, February 1st)

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#73186]
## Information

A Platform website/content orientation is done for every person joining the Platform program. This introduces them to our team, the Platform website, our support services and how to collaborate with us. Here's are some team documents with more information:

- [About Platform Content orientations](https://vfs.atlassian.net/wiki/spaces/CIT/pages/2488664654/Product+outline+-+Content+orientation+for+Platform+teams)
- [Agenda and roles](https://vfs.atlassian.net/wiki/spaces/CIT/pages/2481651920/Platform+Content+Team+Orientation+Agenda+Reminder+List)

## Roles
1-3: Brian
4-5: Lauren
6: Brian
7-9: Jill

## Acceptance Criteria
- [x] A Platform Content orientation will be held on **Thursday, February 1st** for the following:
- [x] Jennifer Brown
- [x] Steven Cumming
- [x] Kelly Argyros

**Comment by johnny-jesensky-adhoc** [comment]
@jknipes, because this is currently scheduled for _**Thursday, February 1st**_ - it will need to be pulled into Sprint 45, (1/31 - 2/14) - just don't want this to slip off your radar. The team should know how to run this meeting, but I would confirm with them who wants to handle the introduction - i.e. parts 1-3.

**Comment by jknipes** [comment]
Orientation presented, take-away documents shared with participants.
