### ISSUE TITLE
Midpoint Review - IA Feedback - Cartographers, MHV on VA.gov, MHV Secondary Navigation

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#73199]
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- I'm excited to see this go to testing! I am hoping the results of your research can inform a redesign of the `In this section` component.
- The "sense of place" concept is going to be a big deal for MHV and other hub-like apps within VA.gov (profile, maybe?). Looking forward to the research readout! 

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- **Consider - current page indicator on persistent nav:** As we chatted about on the call, think about whether we should indicate the current section the user is in (on the persistent nav design option) using an underline or some other highlight. If there's space for this in user testing, great! If not, totally understood.

**Comment by wesrowe** [comment]
Closing post-staging review.
