### ISSUE TITLE
Qualitative Data Request: Claim Status Tool

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#73202]
### Data Type Requested

User Surveys

### Data Source Type

Medallia

### Date Range Start

06-01-2023

### Date Range End

12-31-2023

### Product Name(s)

Claim Status Tool

### Product Description

The Claim Status Tool on VA.gov allows veterans to check the status of their claims. 

### Survey URL(s), key term(s), case category or type

We would like surveys submitted on the following URL: 

https://va.gov/track-claims/  

please provide the data on all sub URLS from the track-claims root, but especially: 

https://www.va.gov/track-claims/your-claims/
https://www.va.gov/track-claims/your-claim-letters/

### File Delivery Format

One file for each term/URL

### Word Cloud

Yes

### VA Email Address(es)

jacob.worrell@va.gov

### Add Assignee and Labels

If not already done so, please ensure @newworld2616 is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by newworld2616** [comment]
Hi, I have shared the requsted data. Please verify once you receive it. Thank you.

**Comment by newworld2616** [comment]
Data shared!
