### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by jenniferbertsch** [department-of-veterans-affairs/va.gov-team#73204]
### Name

Jennifer Bertsch

### Email

jennifer.bertsch@va.gov

### Role

Product Manager

### Team

Benefits Portfolio

### Product Manager (PM) name

Me (Zach Goldfine)

### Additional Notes

Thanks for your help!

**Comment by naomimarcussen** [comment]
An invite has been sent to jennifer.bertsch@va.gov.
