### ISSUE TITLE
Remove extraneous logging from `users_controller`

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#73207]
In the users controller there is a log wrapper that is creating extraneous logs:
```
    wrap_with_logging(
      :show,
      additional_class_logs: { action: 'Loading User' },
      additional_instance_logs: { user_uuid: %i[current_user account_uuid] }
    )
```
Also the `user_uuid` here is wrong (it is not `account_uuid`). We need to remove or remediate this logs to reduce the spam in Datadog

**Comment by bramleyjl** [comment]
I've messaged the developer who added the `wrap_with_logging` feature for additional information on the necessity of this logging and will suggest alternatives that allow us to remove it once I know more.
