### ISSUE TITLE
Spike: Research Google Analytics functionality (Security Review after-action)

### ISSUE THREAD

**Issue by marriej** [department-of-veterans-affairs/va.gov-team#7321]
Question from Anna after. our security and Privacy Review:

Currently, we pass a Google analytics id from the originating saml request to id.me. Will this functionality remain intact with SSOe in the middle.

**Comment by ericbuckley** [comment]
@annaswims a couple of weeks ago during our security review, you mentioned that a Google Analytics id was passed on to ID.me when we authenticate.  Is this value in the SAMLRequest or is it within another query parameter?

**Comment by ericbuckley** [comment]
At this time we **are** passing the `clientId` value to SSOe, however SSOe **does not** forward it to ID.me for Google Anayltics tracking.  I sent an email to the IAM team today asking if they could forward this query parameter.   It sounds like its not an easy change for them, but they didn't say "no" either.  I'll post more updates when they get back to me.

**Comment by marriej** [comment]
Request out to the IAM team (Craig Kisely) to look into the feasibility of copying the query parameters over to id.me.

**Comment by bsmartin-ep** [comment]
Following up from our meeting @marriej, we are definitely interested in GA integration with id.me.  It is currently set up to be tracked in our cross domain list, but not sending in any data.

Our support ticket for this, @joanneesteban:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/677

cc @jonwehausen

**Comment by bsmartin-ep** [comment]
Hi @marriej / @annaswims / @ericbuckley -

I wanted to follow up about this.  _Analytics-Insights_ definitely has an interest in cross-domain tracking on id.me.

Anything you need from us?  I expect a bit of testing and configuration on our end.

cc @jonwehausen / @joanneesteban

**Comment by christine-dillman** [comment]
Fixed by https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/13813
