### ISSUE TITLE
[Data] 10-10EZR: Discovery -- Come up with EZR metrics to track regularly

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#73238]
As a team member, I would like a regular update of 10-10EZR metrics so that I know how well the online EZR is working for Veterans.

- [x] Come up with "high level" metrics that give an "At A Glance" view (Similar if not the same as what we track [here](https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/72487))
- [x] Tracking the performance metrics for measuring successful launch of the EZR (error %, latency, uptime, etc...)
- [x] Come up with more in-depth/detailed online metrics to track EZR performance
- [x] Work with HEC to see what metrics we can get on the paper EZR, and determine if it's worth using those as a baseline (e.g. we see a reduction in the number of paper forms)
- [x] Complete the Dashboard Request ticket proving all the EZR form funnel urls for Google Analytics Dash
- [x] Determine the cadence with which we want to track these metrics
- [x] Come up with a way to present this to Alex, the team, and Patrick/Kristen
- [ ] **Success: We have a plan for tracking EZR metrics that tell us how well EZR is working**

AS Note: We'll have separate stories for compiling these metrics, this is just to come up with a plan

**Comment by luis-simauchi** [comment]
We Will use this rubric for EZR and add to it as the EZR evolves
current set up for CG & EZ:

**Form metrics**
Total Applications
Paper Applications (if possible, we get this info from HEC stakeholders emailed to us)
Online Applications (if possible, we get this info from HEC stakeholders emailed to us)
# of applications started
# of successful submissions
Average # of sessions to submission
Start to submission ratio

**Comment by luis-simauchi** [comment]
probably sprint-ly is best to start out if not monthly; given that the volume of the EZR is going to be much smaller than that of the EZ.

**Comment by luis-simauchi** [comment]
link to the EZR objectives github doc
https://github.com/department-of-veterans-affairs/va.gov-team/blob/398b1d5f34c78b9d1399c740c51b8f82aa3d61db/products/health-care/application/va-application/10-10EZR%20Form/EZR%20Release%20Plan.md#objective-provide-an-effortless-online-experience-for-veterans-to-update-their-information-for-health-care-benefits

**Comment by luis-simauchi** [comment]
Key Result #1: Increase % of Veterans who successfully update their health care benefits information online
Historical	Target	        Post-Launch 1 week	Post-Launch 1 month
Paper Submissions	        15,000 (estimated)	        4,000 (25%)	
Online Submissions	        NEW	                        11,000 (75%)

**Comment by luis-simauchi** [comment]
Key Result #2: Capture 75% of form submissions in a single session
		
Single-session submissions	
Historical	- NEW	
Target  - 75% of submitted forms (8,250)

**Comment by luis-simauchi** [comment]
Key Result #3: Reduce number of EZR form downloads from VA.gov

EZR PDF Downloads	
Historical	 - avg 10,400 monthly	
Target - 2,600 monthly (25%)

**Comment by luis-simauchi** [comment]
At Stage A: Canary I will fill out these metric results 

Results
Number of unique users: [FILL_IN]
Metrics at this stage (per your "success criteria"): [FILL_IN] a list that includes KPIs listed in the Rollout Planning section
Was any downstream service affected by the change?: [PICK_ONE]: yes | no | N/A
Types of errors logged: [FILL_IN]
What changes (if any) are necessarily based on the logs, feedback on user challenges, or VA challenges? [FILL_IN]

**Comment by luis-simauchi** [comment]
for presenting the info to Stakeholders and PMs as needed:

For the phasing period of the EZR itself - pushing folks to the github doc would be best as it is already structured / orginized for detailing the performance metrics:  va.gov-team/products/health-care/application/va-application/10-10EZR Form
/EZR Release Plan.md

For Alex I can input this / organize the info moving forward to the metrics sheet we manage for EZ / CG:
https://docs.google.com/spreadsheets/d/1T_iRon2SsOwL7cRSEyDIiRnC0Ci81FpVThAs2RgPyKY/edit#gid=308703392

And for Patrick B. / Kristen we can come up with a more robust dashboard view within GA or DD that they can reference when they want

**Comment by michelle-dooley** [comment]
Hello @luis-simauchi - We can add the EZR form to our [Forms Dashboard](https://va-gov.domo.com/page/447193050) can you please complete this [Dashboard Request ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=michelle-dooley&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&projects=&template=analytics-request-and-update-kpi-dashboard.md&title=Analytics+New+KPI+dashboard+request+%26+KPI+dashboard+update+request+for+%5BTeam%5D) proving all the EZR form funnel urls. That is what we need to begin this work.

**Comment by luis-simauchi** [comment]
will Do @michelle-dooley !

**Comment by luis-simauchi** [comment]
/my-health/update-benefits-information-form-10-10ezr/introduction/
/my-health/update-benefits-information-form-10-10ezr/veteran-information/personal-information/
/my-health/update-benefits-information-form-10-10ezr/veteran-information/date-of-birth/
/my-health/update-benefits-information-form-10-10ezr/veteran-information/mailing-address/
/my-health/update-benefits-information-form-10-10ezr/veteran-information/home-address/
/my-health/update-benefits-information-form-10-10ezr/veteran-information/contact-information/
/my-health/update-benefits-information-form-10-10ezr/household-information/financial-information-status/
/my-health/update-benefits-information-form-10-10ezr/household-information/marital-status/
/my-health/update-benefits-information-form-10-10ezr/household-information/spouse-personal-information/
/my-health/update-benefits-information-form-10-10ezr/household-information/spouse-additional-information/
/my-health/update-benefits-information-form-10-10ezr/household-information/spouse-financial-support/
/my-health/update-benefits-information-form-10-10ezr/household-information/spouse-contact-information/
/my-health/update-benefits-information-form-10-10ezr/household-information/dependents/
/my-health/update-benefits-information-form-10-10ezr/household-information/dependent-information/
/my-health/update-benefits-information-form-10-10ezr/household-information/veteran-annual-income/
/my-health/update-benefits-information-form-10-10ezr/household-information/spouse-annual-income/
/my-health/update-benefits-information-form-10-10ezr/household-information/deductible-expenses/
/my-health/update-benefits-information-form-10-10ezr/insurance-information/medicaid-eligibility/
/my-health/update-benefits-information-form-10-10ezr/insurance-information/medicare-part-a-enrollment/
/my-health/update-benefits-information-form-10-10ezr/insurance-information/medicare-part-a-effective-date/
/my-health/update-benefits-information-form-10-10ezr/insurance-information/policies/
/my-health/update-benefits-information-form-10-10ezr/insurance-information/policy-information/
/my-health/update-benefits-information-form-10-10ezr/confirmation/

**Comment by luis-simauchi** [comment]
EZR URLs
/my-health/update-benefits-information-form-10-10ezr/introduction/
/my-health/update-benefits-information-form-10-10ezr/veteran-information/personal-information/
/my-health/update-benefits-information-form-10-10ezr/veteran-information/date-of-birth/
/my-health/update-benefits-information-form-10-10ezr/veteran-information/mailing-address/
/my-health/update-benefits-information-form-10-10ezr/veteran-information/home-address/
/my-health/update-benefits-information-form-10-10ezr/veteran-information/contact-information/
/my-health/update-benefits-information-form-10-10ezr/household-information/financial-information-status/
/my-health/update-benefits-information-form-10-10ezr/household-information/marital-status/
/my-health/update-benefits-information-form-10-10ezr/household-information/spouse-personal-information/
/my-health/update-benefits-information-form-10-10ezr/household-information/spouse-additional-information/
/my-health/update-benefits-information-form-10-10ezr/household-information/spouse-financial-support/
/my-health/update-benefits-information-form-10-10ezr/household-information/spouse-contact-information/
/my-health/update-benefits-information-form-10-10ezr/household-information/dependents/
/my-health/update-benefits-information-form-10-10ezr/household-information/dependent-information/
/my-health/update-benefits-information-form-10-10ezr/household-information/veteran-annual-income/
/my-health/update-benefits-information-form-10-10ezr/household-information/spouse-annual-income/
/my-health/update-benefits-information-form-10-10ezr/household-information/deductible-expenses/
/my-health/update-benefits-information-form-10-10ezr/insurance-information/medicaid-eligibility/
/my-health/update-benefits-information-form-10-10ezr/insurance-information/medicare-part-a-enrollment/
/my-health/update-benefits-information-form-10-10ezr/insurance-information/medicare-part-a-effective-date/
/my-health/update-benefits-information-form-10-10ezr/insurance-information/policies/
/my-health/update-benefits-information-form-10-10ezr/insurance-information/policy-information/
/my-health/update-benefits-information-form-10-10ezr/confirmation/

**Comment by emily-brown34** [comment]
@hdjustice  to link dashboard ticket in this thread

**Comment by luis-simauchi** [comment]
@michelle-dooley  the Dashboard Request ticket has been created, thank you!

**Comment by luis-simauchi** [comment]
1-week results
Number of unique users: [55]
Post-launch KPI 1 - Online Submissions actual: [43]
Post-launch KPI 2 - Submission Failures actual: [4]
Post-launch KPI 3 - |Veteran Validation errors actual: [4]
Any issues with VA handling/processing?: [PICK_ONE]: no 
Types of errors logged: [ schema validation error,  nil class errors]
Any changes necessary based on the logs, feedback on user challenges, or VA challenges? [PICK_ONE]: no
If yes, what: [n/a]

**Comment by Blivaditis** [comment]
Hi Luis, did you fill out this[ google sheet  ](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit#gid=981224988). If you have not can you make a copy of the spreadsheet and complete all of the sections, then send the shared link back in this conversation.

**Comment by luis-simauchi** [comment]
I believe so yes

Here it is:

**Comment by luis-simauchi** [comment]
https://docs.google.com/spreadsheets/d/1Js8MvpjL_9nVb6PgVxN-_O81RFOoEhAU2NOQOpxuWgc/edit#gid=0

**Comment by Blivaditis** [comment]
Thank you!

**Comment by luis-simauchi** [comment]
@Blivaditis  please elaborate, what is BQ ? 
I know there is a 1010EZR form dashboard (new) stood up on DOMO, I was hoping to get one in GA.
form is currently live at a minimal 10% of possible traffic so we can set start date as of 1/15/2023
thanks!

**Comment by Blivaditis** [comment]
Hi Luis, I am specifically refine to the card 73844 which is linked to this issue requesting a dashboard for the 10-10EZR Form. The spreadsheet you created with the page paths is used to structure the data in BQ (big query) a data warehousing system. However the 10-10EZR is already housed in Domo under the name "10-10EZR Health Benefits" are these two forms the same? Additionally we load the data into BQ before the form is live that way we can tack the form from the start. Once that is done we are able to add the data into Domo and create a new dashboard.

**Comment by Blivaditis** [comment]
The 10-10EZR data should already be in google analytics.

**Comment by Blivaditis** [comment]
Are you requesting a dashboard for Google Analytics or for Domo? We do not do dashboard request for Google Analytics.

**Comment by luis-simauchi** [comment]
understood @Blivaditis  we will craft that GA dash we need for EZR on our side. CHeers
