### ISSUE TITLE
Address outstanding linter warnings on Find a Rep

### ISSUE THREAD

**Issue by cosu419** [department-of-veterans-affairs/va.gov-team#73240]
## Issue Description
There are still some code linter warnings for missing propTypes, dependency arrays, etc. 

---
## Tasks
- [ ] Address outstanding linter warnings on Find a Rep

## Acceptance Criteria
- [ ] No more warnings!

**Comment by cosu419** [comment]
Note: found that opening a vets-website subfolder directly in vscode causes multiple linter rules to be imported, which was throwing a lot of irrelevant errors that interfered with the usefulness of eslint extension warning highlighting (since virtually every component contained error highlighting for non-errors).

Solution is to open the entire vets-website directory in vscode.

**Comment by oddball-lindsay** [comment]
To solve it, it could involve a not-insubstantial change in find a rep page logic.  Estimate bumped up to reflect new complexity.

**Comment by cosu419** [comment]
All warnings have been addressed to the extent that they won't appear in PR reviews for example, but a handful of them are being ignored. Detailed [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/73679). Moving this ticket to Closed for now.
