### ISSUE TITLE
Create VA.gov platform ADR

### ISSUE THREAD

**Issue by nihil2501** [department-of-veterans-affairs/va.gov-team#73248]
## Objective
Capture the **technical** and **development lifecycle** rationale behind our choice to build the accredited representative facing site on the [VA.gov](VA.gov) platform including `vets-website` and `vets-api`.
## Background
Since ARF engineers have gained more familiarity with product requirements and the existing technology landscape, we have decided that it would be prudent to begin iterating on the site on the [VA.gov](VA.gov) platform in parallel to some degree of exploration of other architectural options.
### Development lifecycle rationale topics
_How this architectural decision affects the development lifecycle_
- Collaboration cycle
- Others?
### Technical rationale topics
_How this architectural decision facilitates product requirements_
- Authentication
- Reuse of [VA.gov](VA.gov) forms
- Presenting a distinct site
- Reuse of [VA.gov](VA.gov) domain modeling and associated service dependencies
## Resources
- [Slack conversation](https://dsva.slack.com/archives/C06ABHUNBRS/p1704479266926979) that spawned this task
- [Product vision](https://docs.google.com/document/d/17yZF0USxhFP6aCuy4QL-sf-fpBxUx7KwCoCDnvKIDNE/edit) that outlines high level constraints and goals of the site that motivate this decision
- [Early architectural brainstorm document](https://docs.google.com/document/d/1SECvAh6TZgCPEWLIF3h8oAusIoB7MmZiyeA5J1iS3dg/edit#heading=h.a1xc2ws1zujg) mentioning architectural options at a high level
- [Sign-In Service documentation](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity/Products/Sign-In%20Service)
- [vets-api](https://github.com/department-of-veterans-affairs/vets-api/) repository where domain modeling and associated services can be searched for
- [vets-website](https://github.com/department-of-veterans-affairs/vets-website) repository where [VA.gov](VA.gov) form applications like the 526 can be found
## Output
The ADR is created. It should link out to the Sign-In Service ADR as part of the decision ([creation ticket here](https://app.zenhub.com/workspaces/accredited-representative-facing-team-65453a97a9cc36069a2ad1d6/issues/gh/department-of-veterans-affairs/va.gov-team/73406)).
## Acceptance Criteria
- [ ] Signed off by @raudabaugh  
- [ ] Signed off by @amprokop

**Comment by RivkaCGates** [comment]
Can we get AC on this please

**Comment by nihil2501** [comment]
@gabezurita @amprokop We might want to pay special attention or even have a special section in this ADR that speaks to the new complexity the [VA.gov](VA.gov) platform would accrue by us building our new site there. Overall we want to have some sense of how principled and clean we can be about extending the platform beyond its original domain of Veterans. We also want to have some sense of how much extra burden our extension adds for people developing for the original domain of Veterans. The early ["where" doc](https://docs.google.com/document/d/1SECvAh6TZgCPEWLIF3h8oAusIoB7MmZiyeA5J1iS3dg/edit#heading=h.a1xc2ws1zujg) speaks a bit to these sorts of ramifications:
> The choice of platform for representative-facing tools will have significant, hard-to-reverse ramifications on engineering and product.
For example, we're already considering extensions to `Sign-In Service`, the `content-build` system, utilizing subdomains, extending forms, modeling delegation generally, etc.

I know we're eager to proceed in this direction, but I feel it is warranted to assuage, to some extent, the concerns about the complexity increase on the platform at this early stage. We could also potentially declare our choice to be somewhat experimental and aim to make our work more reversible while we develop it.

**Comment by nihil2501** [comment]
Another relevant [message](https://dsva.slack.com/archives/C06ABHUNBRS/p1704481584504909) that came from Bill Chapman.
