### ISSUE TITLE
Design Intent - Design Feedback - IVC Forms, 10-10d

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#73246]
## VFS actions
- [x] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [x] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [x] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- Thank you for mobile and wireframes! I am attaching an image of the most current UI for the intro page for forms (placement and content). We are updating the DS soon! Use v3 components. 

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- **Matt Dingee:** How is sponsor different than Veteran? I see the way you are using the progress indicator, if folks get confused about the indicator don't be surprised. If you want to create something that would be great. If you would like to suggest it, go thru the [experimental design process]
- **Must**: Use the [multiple responses pattern](https://design.va.gov/patterns/ask-users-for/multiple-responses) to build your applicant list.
- **Must**: Our [current pattern for reviewing the form](https://design.va.gov/templates/forms/review) is in a single page at the very end before the user submits the form. Use the signature and [statement of truth component](https://design.va.gov/storybook/?path=/docs/uswds-va-statement-of-truth--default). 
- **Should**: Use the [slim alert v3](https://design.va.gov/components/alert#examples---slim-alert---v3) for places where you have immediate feedback on the page instead of the standard alert.

**Comment by allison0034** [comment]
Most recent UI for form intro pages for applications.
![screencapture-va-gov-decision-reviews-supplemental-claim-file-supplemental-claim-form-20-0995-introduction-2024-01-09-15_06_05](https://github.com/department-of-veterans-affairs/va.gov-team/assets/72398073/e2a6e5ee-e7b7-48f0-b303-8c0a92eaa4da)

**Comment by syd-hoeper** [comment]
Question regarding "Must: Our current pattern for reviewing the form is in a single page at the very end before the user submits the form. Use the signature and statement of truth component."

Would someone be able to shed some light on the "signature" aspect of this? I have put everything on the same page, as requested, and am using the Statement of Truth component, but I'm not seeing anything specifically about a "signature". Is this a separate component, or is the SoT acting as the signature?

Thanks!

**Comment by syd-hoeper** [comment]
Here is the Figma file with the prototype where I've included updates from the Feedback section. Everything has been addressed except I'm still working on figuring out the "Sponsor" vs "Veteran" language thing, and waiting on a response to my comment above about the "signature" aspect regarding the Statement of Truth.

https://www.figma.com/file/Rnq4uKAlSUnVPD31fViTcj/10-10d-Prototype?type=design&node-id=228%3A94731&mode=design&t=dkmHL8wOH52Ddrk2-1

**Comment by allison0034** [comment]
Hi @syd-hoeper here is the [guidance](https://design.va.gov/patterns/ask-users-for/signature) around the signature info. Signature and Statement of Truth are really linked together. Does this help?

**Comment by syd-hoeper** [comment]
@allison0034 Yes it does, thank you so much!

**Comment by syd-hoeper** [comment]
Updates:
- Regarding "Should: Use the slim alert v3 for places where you have immediate feedback on the page instead of the standard alert." we ended up making the alert static, and therefor we were advised by Matthew Dingee that the Standard Alert would be the proper component here (see [this Slack thread](https://dsva.slack.com/archives/C01DBGX4P45/p1706134017305679))
- All other feedback has been incorporated and can be found on the screens and prototype on this Figma page: https://www.figma.com/file/Rnq4uKAlSUnVPD31fViTcj/10-10d-Prototype?type=design&node-id=508-73596&mode=design
