### ISSUE TITLE
Parse representatives sheet in Trexler File to support VSOfficers

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#73253]
## Background
Lingering task as we migrate our Find a Rep product to support VSOfficers

## Tasks
- [ ] Parse representatives sheet in Trexler File to support VSOfficers

**Comment by oddball-lindsay** [comment]
Additional work needed, to factor in empty cells (as opposed to skipping them)

**Comment by holdenhinkle** [comment]
PR - https://github.com/department-of-veterans-affairs/va.gov-team/issues/73253

**Comment by oddball-lindsay** [comment]
There was a class with mixed concerns, abstracting out code that parses the excel file.  Almost done, looking at some weird behavior before completing.

**Comment by holdenhinkle** [comment]
This is done. Submitting it for review.

**Comment by holdenhinkle** [comment]
This took longer than expected, so I'm changing this to a 5.
