### ISSUE TITLE
Consider validation to ensure dates are within an expected range

### ISSUE THREAD

**Issue by mengA6** [department-of-veterans-affairs/va.gov-team#73262]
Within a section like "Service locations after August 2, 1990", consider validation on dates people enter - to ensure that they are after August 2, 1990. 

Consider that this validation on a date screen might involve guiding someone to deselect the location (currently on a different screen) or change the date on the date screen.

From [Product-UX Sync 1/9/2024](https://docs.google.com/document/d/1HoVCQoW63SLDNMqlUedqM8IGNDyvWV-GbTtTmR2UT-A/edit#heading=h.cu2fdncg7dij)

**Comment by pacerwow** [comment]
Is this work here the same as [#84307](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/84307)? If so, move the details of this ticket to #84307 and I'll close this as a duplicate

**Comment by pacerwow** [comment]
@mengA6 can this be closed? If not, is this a duplicate (see prior comment).

**Comment by mengA6** [comment]
Yes, closing as a duplicate of [#84307](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/84307)
