### ISSUE TITLE
Midpoint Review - Accessibility Feedback - Sitewide - Facilities, VA Medical Centers, Police Transparency

### ISSUE THREAD

**Issue by briandeconinck** [department-of-veterans-affairs/va.gov-team#73271]
## VFS actions
- [x] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

-

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- **Must:** When choosing the police activity information to display, add a button after the three dropdowns that will trigger the action to display data, rather than having the action occur just from making a selection with the dropdowns. My expectation would be that focus moves when triggering the action (more on that below), and so triggering that focus change via a button avoids situations where a user is arrowing down through dropdown options and having their focus move unexpectedly before they've made their selections.
- **Coding:** When selecting the data to display, keyboard focus should move to the "[month and year] police activity at [system name]" heading. This ensures that screen reader users know something has happened --- by moving focus, that heading gets immediately announced to tell them what's now displayed, and the data they're looking for is the next thing they'll encounter.
   
   Likewise for the unhappy paths, keyboard focus should move to the first heading for the information that's generated. I don't think all of the unhappy paths include a message indicating what is/isn't available --- would be great to have something consistent across all the scenarios. But regardless, keyboard focus should move to the first relevant heading.

**Comment by xiongjaneg** [comment]
Thanks @briandeconinck!

**Comment by laflannery** [comment]
[Design files](https://www.sketch.com/s/b48c905c-7c7f-46fb-9ae5-6020ff0e5174/v/WQxGLn/) have been updated with a button to activate the filters the user has chosen. We have also added annotations to indicate the focus behavior after search is triggered. These updates and annotations can be seen in the [Unhappy path files](https://www.sketch.com/s/b48c905c-7c7f-46fb-9ae5-6020ff0e5174/p/BCF48D91-1495-4180-B794-F9A465CF1AD5/canvas) as well
