### ISSUE TITLE
[FE] 10-10EZR Emergency Contact: EC VIEW existing data

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#73277]
As a Veteran, I would like to update my Emergency Contact so that if something happens to me the VA knows who to contact and who to provide support to. 

- [ ] User can VIEW data (hardcoded data)
- [ ] Use [designs](https://www.figma.com/file/tggcJk382w9yQ0ElwKfh3N/10-10EZR?type=design&node-id=0%3A11540&mode=design&t=7wY1DLPcktLiXeHi-1) and API to build out FE
- [ ] Work with BE and UX to determine what (if any) fields are required and note them for users
- [ ] User can view the following fields:
- [ ] -- Emergency Contact Name 1
- [ ] -- EC # 1
- [ ] - EC 1 Address (Optional)
- [ ] --EC 1 Relationship (Optional, default to "Unrelated Friend")
- [ ] -- Emergency Contact Name 2
- [ ] -- EC # 2
- [ ] --EC 2 Address (Optional)
- [ ] --EC 2 Relationship (Optional, default to "Unrelated Friend")
- [ ] **Success: Emergency Contact data is viewable on EZR**

**Comment by JoshingYou1** [comment]
This ticket is being worked on in parallel with ticket #73279.
