### ISSUE TITLE
(Figma) Update warning alert in Dependent Child for child between 18-23 years old in designs

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#73289]
## Issue Description

Related Slack thread: https://dsva.slack.com/archives/C05MS96P6P2/p1704817646461429?thread_ts=1704484692.155699&cid=C05MS96P6P2

<img width="585" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2l4QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7d644ee094108a93846d13f55408259cf73d1c6a/Screenshot%202024-01-09%20at%206.38.37%E2%80%AFPM.png" alt="Screenshot 2024-01-09 at 6.38.37 PM.png" />

---
## Tasks
- [ ] Update design artifacts in Figma to match staging environment experience for the current alert that shows for the question "Is your child in school?"

**Comment by gmaciolek** [comment]
Figma file needs updating. Would like to keep this open.

**Comment by gmaciolek** [comment]
[Figma file updated to match production](https://www.figma.com/file/9JKK5Eo43uJWEr66JPiebc/Pension-Claim-Form-21P-527EZ?type=design&node-id=3362%3A7938&mode=design&t=X39wd1Q1cY7PVwGP-1)
