### ISSUE TITLE
Step 4 household info: Update copy for Spouse's former marriage

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#73287]
## Issue Description

Slack thread: https://dsva.slack.com/archives/C05MS96P6P2/p1704816010088909?thread_ts=1704484692.155699&cid=C05MS96P6P2

<img width="483" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnV4QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ae1de69a9cddcccee8ed648937a63042d8384100/Screenshot%202024-01-09%20at%206.27.42%E2%80%AFPM.png" alt="Screenshot 2024-01-09 at 6.27.42 PM.png" />

---

## Acceptance Criteria
- The existing copy in the gray alert, found under the Spouse's former marriage information page, will be updated with the following copy:

`We usually don't need to contact a former spouse of a Veteran's spouse. In very rare cases where we need information from this person, we'll contact you first.`

**Comment by vbellissimo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/73287?planning-poker) with Zenhub @danlim715 @scottsdevelopment @TaiWilkin @ToddWebDev @wayne-weibel

**Comment by aplatt-coforma** [comment]
Verified that text has been updated
<img width="1218" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVFVQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1c674b890f127d56615cfc3e483bac09c646eaa2/Screenshot%202024-01-30%20at%209.47.36%E2%80%AFPM.png" alt="Screenshot 2024-01-30 at 9.47.36 PM.png" />
