### ISSUE TITLE
Step 4 household info: Update copy for VA file number question for spouse information

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#73285]
## Issue Description

Slack thread: https://dsva.slack.com/archives/C05MS96P6P2/p1704749668578299?thread_ts=1704484692.155699&cid=C05MS96P6P2

<img width="686" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkd4QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6a2b788172a3a9fcaa0e9791111b0b9177def9d9/image.png" alt="image.png" />

---
## Tasks
- [ ] 

## Acceptance Criteria
-

**Comment by aplatt-coforma** [comment]
Change looks good
<img width="803" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3poQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bfa611e6f51905cfcbe7d1754742cc74c2090622/Screenshot%202024-01-19%20at%2010.50.24%E2%80%AFAM.png" alt="Screenshot 2024-01-19 at 10.50.24 AM.png" />
