### ISSUE TITLE
[FE/BE/UX] 10-10EZR: Discovery - Primary/Secondary EC 

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#73282]
As a Veteran, I would like to update my Emergency Contact so that if something happens to me the VA knows who to contact and who to provide support to. 

- [x] Figure out what happens when a primary contact is deleted in VES and there is a secondary contact
- [x] Determine how we should handle primary and secondary for the BE
- [x] Confirm with UX and PM about handling Primary/Secondary
- [x] **Success: We have a plan for how to handle primary/secondary EC that works for both our end users and VES**

**Comment by mkerns1** [comment]
After reviewing the List&Loop card label issue, we found that while it's possible to display "primary/secondary" text using the cardDescription variable, the main challenge is with the ArrayBuilder component. Currently, the form data doesn't flow between items in a way that informs other items when one is set as "primary." There is no mechanism in place to update the remaining items as "secondary."

Given this limitation, we will move forward with a Content-only update. Once the mock is updated, Hieu will demo it to the team.

**Comment by allanto-ah** [comment]
No QA at the moment as this is a discovery ticket. Closing
