### ISSUE TITLE
Update copy on Spouse's former marriage info page in designs

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#73286]
## Issue Description

Slack thread: https://dsva.slack.com/archives/C05MS96P6P2/p1704816010088909?thread_ts=1704484692.155699&cid=C05MS96P6P2

<img width="483" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMml4QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6f6e12b337beb92da846dd84b5169ff051e36adc/Screenshot%202024-01-09%20at%206.27.42%E2%80%AFPM.png" alt="Screenshot 2024-01-09 at 6.27.42 PM.png" />

---
## Tasks
- [ ] 

## Acceptance Criteria
-

**Comment by aplatt-coforma** [comment]
Duplicate for ##73287
We can close this since it is already fixed.
