### ISSUE TITLE
Step 4 household info: Update copy to remove "your" from Dependent Child/Who they live with Info

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#73291]
## Issue Description

Slack thread: https://dsva.slack.com/archives/C05MS96P6P2/p1704825370575819?thread_ts=1704484692.155699&cid=C05MS96P6P2

<img width="981" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3l4QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--28cd9d87732c3d9cbcdaf337ee99cf2b79e8be48/child-live-with-you-no.png" alt="child-live-with-you-no.png" />

---
## Tasks
- [ ] 

## Acceptance Criteria
-

**Comment by aplatt-coforma** [comment]
Looks good.
<img width="590" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFhSQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--616e9e7750d02a194af25c396ed70f01c2bc7a0e/Screenshot%202024-01-16%20at%205.50.51%E2%80%AFPM.png" alt="Screenshot 2024-01-16 at 5.50.51 PM.png" />
