### ISSUE TITLE
[MVP] Step 5 Gross Monthly Income: Make/fix questions to be required

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#73297]
## Issue Description

Slack thread: https://dsva.slack.com/archives/C05MS96P6P2/p1704835782407279?thread_ts=1704484692.155699&cid=C05MS96P6P2

Currently, the Gross Monthly Income page has questions that are required, but I'm able to proceed to the next page without filling the answer out.

This needs to be corrected so the veteran is not able to proceed to the next page without filling out the required questions/answers..

<img width="432" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDJ4QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1959f641e66021af1e6727ffac900f6cf8266c0c/Screenshot%202024-01-09%20at%206.59.49%E2%80%AFPM.png" alt="Screenshot 2024-01-09 at 6.59.49 PM.png" />

## Acceptance Criteria
- [ ] The user will not be able to proceed to the next page if they have not filled out the required questions/answers asked on the Gross Monthly Income page.

**Comment by aplatt-coforma** [comment]
Required fields are working as expected.
<img width="442" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekRDQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0043a852d32bb031ef2d2ff44a76a681bb2a89e0/screencapture-staging-va-gov-pension-application-527EZ-financial-income-sources-2024-01-12-08_52_38.png" alt="screencapture-staging-va-gov-pension-application-527EZ-financial-income-sources-2024-01-12-08_52_38.png" />
<img width="466" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekhDQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aa58f2a62a0d0fdc972883a0570c73a9d445bd5d/screencapture-staging-va-gov-pension-application-527EZ-financial-income-sources-2024-01-12-08_53_14.png" alt="screencapture-staging-va-gov-pension-application-527EZ-financial-income-sources-2024-01-12-08_53_14.png" />
