### ISSUE TITLE
Step 4 household info: Update copy for Dependent Child 18-23 years old alert

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#73290]
## Issue Description

Slack thread: https://dsva.slack.com/archives/C05MS96P6P2/p1704817646461429?thread_ts=1704484692.155699&cid=C05MS96P6P2

<img width="585" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOW5xQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--30fc87e9a15cc01dcb1754e94d3f0c751328acb4/Screenshot%202024-01-09%20at%206.38.37%E2%80%AFPM%20%281%29.png" alt="Screenshot 2024-01-09 at 6.38.37 PM (1).png" />

## Acceptance Criteria
- The existing gray alert found under the question "Is your child in school?", if answered "yes", should be updated with the following copy:

You'll need to submit a Request for Approval of School Attendance (VA Form 21-674).

We'll ask you to upload this form at the end of this application. Or you can send it to us by mail.

Get VA Form 21-674 to download (opens in new tab) - _link this sentence to https://www.va.gov/find-forms/about-form-21-674/_

**Comment by aplatt-coforma** [comment]
Looks good and links open in new window
<img width="1220" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGovQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--57e8832c917aac843f847bffbd3f7c497635f436/Screenshot%202024-01-25%20at%202.55.33%E2%80%AFPM.png" alt="Screenshot 2024-01-25 at 2.55.33 PM.png" />

**Comment by mayacoforma** [comment]
Looks good, but let's skip the header with the line. Also, could we update the header labeled "Information" with the dependents' name? Keep the subheader consistent with the H3 style for a smoother design.

<img width="634" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0VJQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--52859b1cd27c2ca85b1da4271890c1105f56c273/Header.jpg" alt="Header.jpg" />

**Comment by aplatt-coforma** [comment]
@vbellissimo -should we save @mayacoforma latest request for a fast follow ticket after MVP is launched?

**Comment by vbellissimo** [comment]
@aplatt-coforma @mayacoforma, Yes I think we should treat separately.

**Comment by aplatt-coforma** [comment]
Looks like @gmaciolek beat us to it. Here's the ticket to track the dependent header changes: #74449
[Dependent information header and padding issues](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/gh/department-of-veterans-affairs/va.gov-team/74449)
