### ISSUE TITLE
CANCELLED TASK - Update breadcrumb title throughout application

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#73303]
## Issue Description

Slack thread: https://dsva.slack.com/archives/C05MS96P6P2/p1704844174469309?thread_ts=1704484692.155699&cid=C05MS96P6P2

Expected behavior: Breadcrumb until you reach the review page should be Apply for Veterans Pension

<img width="852" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTJ4QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1bb301c970be5219c564265ec5afce74da9babd3/Screenshot%202024-01-09%20at%207.18.43%E2%80%AFPM.png" alt="Screenshot 2024-01-09 at 7.18.43 PM.png" />

## Acceptance Criteria
- The existing breadcrumb title found throughout the online form saying "Review pension benefits application" will be updated to "Apply for Veterans pension"

**Comment by zack** [comment]
@vbellissimo this would appear to be both superseded by (and contradicted by) https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/gh/department-of-veterans-affairs/va.gov-team/73985
