### ISSUE TITLE
IPP - Standardize Continue Button in PA app

### ISSUE THREAD

**Issue by lmorris3** [department-of-veterans-affairs/va.gov-team#73310]
#### What I expected to happen

1. I sign into the Proofing Agent application
2. I advance through the screens using the continue button
3. If I do not complete all steps on a screen or I leave required fields blank, then the Continue button cannot be clicked

#### What actually happened

1. I sign into the Proofing Agent application
2. I advance through the screens
3. Some Continue buttons are active and clickable even if I have not filled in all information, and some are not.
1. 
1. 

#### What _SHOULD_ happen

1. All Continue buttons should have the same functionality so it's not confusing during Usability Testing.
2. For now, we should make all Continue buttons inactive until all info is filled out.
3. Pages where we need to update this are: Validate ID page (allows user to move forward without selecting ID type); Fill in Information Page (allows user to move forward without an ID selection

#### Screenshots or Supporting Evidence
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/5697474/e82c339d-354b-4c88-871c-67f4d899b382)

#### Platform
Vercel

#### OS version and Browser version (if applicable)
Google Chrome

#### App version (build)
IPP Proofing Agent Application v1

#### Affected environment(s)
QA

#### Severity of the issue
- [ ] High severity
- [x] Medium severity
- [ ] Low severity

#### Visibility
- [x] User visible
- [x] Stakeholder visible

#### MR Approver
- TBD

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mateoclarke** [comment]
This was a little tricky to triage but I was able to reproduce. I think this only happens when you:
1. Make a selection under "Select ID type"
2. Then click the check for "Validated document" (This value is what we use to enable/disable Continue button) 
3. And then you go back to "Select ID type" and deselect your previous choice.

If you follow these steps, the button will be enabled but we don't have an ID Type selected.

**Comment by lmorris3** [comment]
Interesting, so if you go through this with a normal flow, the Continue button isn't active without an ID Type selected? If it's outside of a normal flow, I'm okay to leave this until post UT. (Unless you've already made changes that solve the issue.)

**Comment by mateoclarke** [comment]
Yeah, exactly.

Here's a screen capture:
https://github.com/department-of-veterans-affairs/va.gov-team/assets/5697474/3b2d5fba-9db2-41da-b4a4-54caa900e6b9
