### ISSUE TITLE
Step 6 Additional info/supporting documents page: Update copy & link for QuickSubmit

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#73319]
## Issue Description
On Step 6 on the Document upload page:
https://staging.va.gov/pension/application/527EZ/additional-information/document-upload

- Link to QuickSubmit currently opens in same window, taking the Veteran away from their filled out form in order to upload documents but before they've submitted their form.
- They wouldn't actually lose data unless not logged in, in which case potentially they would.
- Expected behavior, per the [design system on linking VA sub-domains](https://design.va.gov/content-style-guide/links#linking-to-external-sites): This link should open in a new tab and include the words "(opens in new tab)", i.e.:
`Go to AccessVA to use QuickSubmit (opens in new tab)`

<img width="500" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEcxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7b5d8e5e95bb5c221332c664cab2c697e0eddac5/Screenshot%202024-01-10%20at%2010.35.58%E2%80%AFAM.png" alt="Screenshot 2024-01-10 at 10.35.58 AM.png" />

## Acceptance Criteria
- [ ] The link to upload documents via AccessVA will open as a new tab and it will be clear to the reader that it opens as a new tab.

**Comment by aplatt-coforma** [comment]
Changes looks good. 
<img width="683" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3ZxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ccf54e7cf66d332306d009f57d74fc94feed65cf/Screenshot%202024-01-22%20at%203.37.53%E2%80%AFPM.png" alt="Screenshot 2024-01-22 at 3.37.53 PM.png" />
