### ISSUE TITLE
Access for Stan Gardner - VAMC-Upgrade team - GovernmentCIO

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#7331]
# Description
- Request: Please provide SOCKS proxy access as this is required to complete support work on VAMC-Upgrade product.  Access needed for: dev, staging, prod, CI environments and Jenkins.

- Please provide your Contracting Officer's Representative (COR) name.
   > **Mary O'Toole**
- Please provide your name.
   > **Stan Gardner**
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Team: VSA-VAMC-UPGRADE / VAMC-UPGRADE, 
   > Role:  Product Manager
   > Company: GovernmentCIO

```

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDeR0vE1b26kBYZ4/cOcbxQIWTc48gaI3121S13TEFhD/cF+gacgBgYwDXEV7vVTF4Uvf9qXJlFnVMnCxwCI1bfuL0mAima3aHVKLhDkjLmpElyvhxfnNNp782mrIZ/VvmCmWT2M0Rx4ZmcSaNVF2pXwrk5T34JLzr3p2J4tbThsJjSMrO2U0gBxTjeFhaUiXHxAtht1D1tSv/FHRETOKi8Fg+ngb4chT0k5NmNVejTvoOvPfjd5lMb6TML+xBJRgKjhx7UzK8JhxiT88/8Sr5dz0fRg4pYo7/mHZQfLf37ApfoblYku0fCcSrlF9RvZ7kC6Jw+GSYGgi74U19MfMWf79hbSf1xP2yt7hkN0LxHGF4+hARfk3HbGSvMyj5a9Ms8kUI3pes3MLpA/N7NHNUZPGOhFnnsV/8nfGUaTKrtixiux9UhIBGs8wWwDdmD0ax2oUPbIYHwz7fzO8i5hJsA1/j6XruHHcBBsMOMYxuiv6Adw9E8sWqrxkHG33ngnEk= Stan Gardner@DESKTOP-3K1D5GC
```

- [Grant AWS Console access?]
  > **NO**
  >  Please give a brief description for why you are requesting AWS access.

**Comment by jbritt1** [comment]
SOCKS access granted. @SgardnerPMP please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.

**Comment by jbritt1** [comment]
SOCKS access granted. @SgardnerPMP please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.

**Comment by SgardnerPMP** [comment]
Had to regenerate Key:

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCh1svGEti5DgB5I+r1m09yEWVObuLtxhdUqsDh5nkhPkvKQK04s31uE+xAI8eMsHSRSsJT27p+M4jU+18BAXPll6eKsFwLMCny+Yhc4bf6PfQ4jGu1eSdqIjWOT72GOJmoiW/Qb6u7/4VLPeKEWzhaecc/zlMFV9xRom4L49qaGpMA9GMFS4LYLt03WUXB+/dtdLI5PujyacmgP2lMRmVXL8DVO8BGKqrQR174fQrfpq6uBZx2nn3FuNF0KeUFuLDRtqao9bUxavsaqlINFb/eQ9pKWSmoEy7McG4Y8C9yJDd5LqywvHmWrFKT2gMRQ3yxrK1WnTCVFncsLr4Yr5Va5jtk8xMvySBEDerkJv8kpGaHFzt7J19mly9qiMn86HnbtPV7OQjWluRk3oSCbIteJ+C+iOzfDG5mE6OO59i+A8XTSmVgguiaBl4adUMMSKDk6rCk6EDKPXvEOP/6FAu35BKfkausJwbIBhtvydm0YyN9ogPdqwHVI0I2L/Ysf8E= Stan Gardner@DESKTOP-3K1D5GC

Thank you,

**Comment by jbritt1** [comment]
Key updated as requested. Please allow 5-10 minutes for the new configuration to deploy.
