### ISSUE TITLE
Analytics KPI dashboard request for Public Websites - The PACT Act

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-team#73326]
We will be delivering a new PACT Act experience soon and need to get baseline KPIs, and then monitor to hopefully see improvements in experience ratings. Thanks in advance!

**Comment by michelle-dooley** [comment]
Hello @FranECross - can you please provide some additional details on this request. For example when you "new PACT Act experience" what does that mean? Is that a new form funnel specific for the Pact Act users will flow through? If so I will need all those url(s) provided.

**Comment by FranECross** [comment]
@michelle-dooley Apologies for the vague details! I'll update today with better info.

**Comment by johnny-jesensky-adhoc** [comment]
Hi @FranECross, just wanted to check back in on this - are you able to add additional details to this ticket? In case it's helpful, we have some guidance on what we generally needed included on these kinds of requests [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=johnny-jesensky-adhoc&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&projects=&template=analytics-request-and-update-kpi-dashboard.md&title=Analytics+New+KPI+dashboard+request+%26+KPI+dashboard+update+request+for+%5BTeam%5D).

Let me know if you have any questions!

**Comment by FranECross** [comment]
@johnny-jesensky-adhoc Thanks so much for the follow-up! We learned last week that this project has been placed on hold, and that the stakeholders will be providing content changes and possible wizard-flow changes, too. In light of that, it's probably best to put this one on hold until all changes have been made and it's in prod (we thought it was going to be released a week or so ago). Please let me know if you'd rather that this just be closed/deleted and I can resubmit at a later date. Thanks again!
