### ISSUE TITLE
Adding Mitch Saltykov to DSVA Slack

### ISSUE THREAD

**Issue by emily-brown34** [department-of-veterans-affairs/va.gov-team#73325]
Please add Mitch Saltykov to DSVA Slack. mitch.saltykov@agile6.com

We are requesting that this individual be added as a full member and is added to the following channels:
1010-health-apps
 health-tools-1010-apm
 vecms-carma_vadotgov_development_external
 accessibility-ops
 vfs-change-announcements
 vfs-platform-support
 vfs-all-teams
 feedback-backchannel
 (PMs) team-of-teams-slide-collection
 (Design.research) design
 (Design.research) research-ops
 (Design.research) platform-design-system
 (Design.research) sitewide-content-ia
 (Frontend Engineers) vfs-frontend

Mitch is a full stack engineer working on the VA  Health Enrollment team and has been favorably adjudicated

**Comment by emily-brown34** [comment]
@LEHigley @KevinMHoffmanUSDS following up on this request!

**Comment by LEHigley** [comment]
added as a full member
