### ISSUE TITLE
Analytics KPI dashboard request for Public Websites - Discharge Upgrade Wizard

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-team#73328]
We will be releasing a new Discharge Upgrade Wizard experience soon, and need to get KPI baselines, and then monitor to hopefully see an improvement after release. Thanks in advance!

**Comment by michelle-dooley** [comment]
Hello @FranECross - can you please some more details on this request. Where is the Discharge Upgrade Wizard, what pages and/or events are you wanting to track within it?

**Comment by FranECross** [comment]
@michelle-dooley I'll get details added! Thanks!

**Comment by ChristineYoungZA** [comment]
Hi @FranECross wanted to follow up with this and see if this is still a need. If so, have you had a chance to get more details?

**Comment by FranECross** [comment]
@ChristineYoungZA Thanks so much for the follow-up! I'm going to close this as not needed at this time, and then create a new one when the project is near completion. We thought we'd be implementing by now, but had to pivot to other things. I appreciate you pinging me!
