### ISSUE TITLE
Requirement gathering and architecture change review on back end point (API endpoint) for PEGA

### ISSUE THREAD

**Issue by cloudmagic80** [department-of-veterans-affairs/va.gov-team#73330]
As we are changing from benefit intake to the new PEGA API solution, we need to understand what needs to change in our backend code. There will be multiple files and code that need changes . What file are those? What is the level of effort ?

**Comment by cloudmagic80** [comment]
We have not received information on where to store our generated PDF form files yet. Marking this effort as blocked

**Comment by baltes** [comment]
Closing this out, will reopen once there's an API connection to PEGA ready for implementation, and we don't know when that will be.
