### ISSUE TITLE
Draft IPP Walkthrough Doc for Usability Test with PAs

### ISSUE THREAD

**Issue by lmorris3** [department-of-veterans-affairs/va.gov-team#73334]
## Problem

Ahead of the Usability Tests of the Proofing Agent Application with MHV coordinators, Carnetta and Susan would like to preview the Application. Rather than sending it to them without guidance, let's create a walkthrough guide that gives them a complete picture of how this will function in a real world setting.

## User Story
As someone responsible for MHV coordinators, I want to preview the application that my coordinators will see during Usability Tests so I know what to tell them to expect.

## Acceptance Criteria
- walkthrough doc should be brief, a page or less
- walkthrough doc should include a brief summary of the Veteran Intake process to orient the user and 'set the stage' (i.e. The PA application is the administrative component to the Veteran Intake application...)
- walkthrough doc should include steps that a Proofing Agent takes (i.e. like a script)
- walkthrough doc should include sample Case Numbers, Names, DOBs, SSNs, and other form field info in correct formats and meeting criteria laid out in the application (for example, Case number is the correct number of characters)

Out of Scope:
- doc is not a testing guide, does not need to go into that much detail

**Comment by SophiaPhilipMO** [comment]
https://docs.google.com/document/d/18HQxdfJz9YVueK_ZTc--ydRq5e8sHdLAeabQRLNuixs/edit
