### ISSUE TITLE
[FE] Show Information for a Cancelled Appointment

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#73331]
## User Story
As a Veteran, I would like to know if an upcoming appointment has been cancelled so that I will know not to show up for that appointment.

## Wireframes
[Priority 1 Wireframes](https://www.figma.com/file/7Ib7RxiIC4QB53FDBO2a8c/Unified-check-in-%7C-Check-in?type=design&node-id=0-8045&mode=design&t=slq7cOhxwlKlPuSx-0)

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/86678742/362d8c10-85ef-4386-9a1b-2d806a0034fe)

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/86678742/7163d0ea-f93c-4ef2-8028-6caa21e668c1)

## Tasks
- [FE] Appointment List Page: Show strikethrough for a cancelled appointment plus del tag
- [FE] Details Page: Show information for a Cancelled Appointment

**Comment by loripusey** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Check-in-Experience-61fc23a2cb8a14001132e102/issues/department-of-veterans-affairs/va.gov-team/73331?planning-poker) with Zenhub @brianseek @loripusey

**Comment by brianseek** [comment]
There isn't enough information here to point

**Comment by loripusey** [comment]
sorry, I was doing a demo for the CES team on how to do Planning Poker in ZenHub, ignore the request

**Comment by benbrasso-agile6** [comment]
Last appt in the list shows the design for a [canceled appt in the appts list](https://www.figma.com/file/7Ib7RxiIC4QB53FDBO2a8c/Unified-check-in-%7C-Check-in?type=design&node-id=551-18563&mode=design&t=x2jp6lrunmWWXDdW-4)

I'll need to create the appt detail page version; can work on that. 

Any other questions?

**Comment by loripusey** [comment]
@wullaski was saying he didn't think we got cancelled appointments from VeText/CHIP; @brianseek can you confirm if we do or don't?

**Comment by benbrasso-agile6** [comment]
This isn't for VEText appts; this would be for MAP appts

**Comment by loripusey** [comment]
yes, I see that now that I look at the wireframe

**Comment by benbrasso-agile6** [comment]
I'm going to create a ticket for the detail page, realizing we don't have that. It would just be a copy from the Appts team. But, let me create a ticket for that. I think Zach should be able to complete that this sprint. Let me make the ticket first.

**Comment by benbrasso-agile6** [comment]
Actually, we already have the wireframe: [Canceled appt details page for a MAP appt](https://www.figma.com/file/7Ib7RxiIC4QB53FDBO2a8c/Unified-check-in-%7C-Check-in?type=design&node-id=0-3181&mode=design&t=x2jp6lrunmWWXDdW-4)

**Comment by loripusey** [comment]
The above wireframe is not in the Priority 1 area, so ignore it, I pasted the Priority 1 wireframes & screenshots above in the ticket description.

**Comment by benbrasso-agile6** [comment]
K, let me know if you need anything

**Comment by brianseek** [comment]
patient canceled: <img width="220" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnpHQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6372393883b24bcaa97998587d1a02e1967ab4e6/localhost_3001_health-care_appointment-check-in_appointment-details_0030-0001_lang%3Den.png" alt="localhost_3001_health-care_appointment-check-in_appointment-details_0030-0001_lang=en.png" />

**Comment by brianseek** [comment]
unspecified canceled: <img width="223" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjNHQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--25a055fa8ff0e5c4856dbb6750df752e68ce0871/localhost_3001_health-care_appointment-check-in_appointment-details_123456-983.png" alt="localhost_3001_health-care_appointment-check-in_appointment-details_123456-983.png" />

**Comment by loripusey** [comment]
LGTM

**Comment by benbrasso-agile6** [comment]
The canceled alert looks good. 

I think there was a recent ticket to update the info on the appt details page. For example, for in-person check in, the appointment information would look more like this: https://www.figma.com/file/sK2vIx6giAynNqUFR0l4Wx/Production-%7C-Check-in?type=design&node-id=1427-13250&mode=design&t=r3mVKRCifiBsYGsT-4

For example, no more heading style for "Phone" label.

**Comment by loripusey** [comment]
can you find the ticket? I'm not sure what you're talking about @benbrasso-agile6; closing this ticket as validated

**Comment by benbrasso-agile6** [comment]
This was the design ticket, let me see if I can find the FE ticket - https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/80939

FE - https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/80942

**Comment by benbrasso-agile6** [comment]
Maybe that's not part of the unified branch?

**Comment by brianseek** [comment]
yeah I think that stuff we will get in the next rebase
