### ISSUE TITLE
Apply card with icon component to request details pages

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#73343]
## Description
This adds the [appointment card with icon component](https://design.va.gov/components/card#appointment-large-with-icon) to VA and CC request details pages. 

**Note:** the Check-in team has built this component, but it hasn't been added to storybook yet. Please discuss with them before working on this ticket. A new ticket may be needed to add the component to storybook before work starts.

## Acceptance Criteria
Background: the `va_online_scheduling_card_icon` toggle is on

Given the user is on the details page for a [VA request](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/feature-reference/appointment-types/va-request.md)
Then appointment card with icon component wraps around the page content
And the [icon](https://design.va.gov/foundation/icons#appointments) in the component is `<i class="fas fa-calendar"></i>`.

Given the user is on the details page for a [community care **request**](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/feature-reference/appointment-types/community-care-request.md)
Then appointment card with icon component wraps around the page content
And the [icon](https://design.va.gov/foundation/icons#appointments) in the component is `<i class="fas fa-calendar"></i>`.

### Design Assets

[Design spec](https://www.figma.com/file/wQy9CVKBu1yRmBWLFk05Ll/Add-Icon-Card-to-Details-Pages-%7C-Appointments-FE?type=design&node-id=1-39&mode=design).
All design spec copy is For Placement Only. This ticket only adds the appointment card with icon component.

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by ldelacosta** [comment]
No need to implement. Closing out the ticket.
