### ISSUE TITLE
Update Save In Progress form documentation

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/va.gov-team#73344]
### Description
I just merged in a PR to centralize the data around Save In Progress forms:

https://github.com/department-of-veterans-affairs/vets-website/pull/27364

I need to make changes to this [section of the docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-how-to-set-up-save-in-progress-si)

![Screenshot 2024-01-10 at 10 57 10 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8332986/e36a0d98-c8e7-43b2-9409-079018af4327)

The second bullet should now refer to the `VA_FORM_IDS object in the /platform/forms/constants file` instead of `In the personalization dashboard helpers file` since the information now all resides in that file.

The secondary bullets should be updated as follows:

- `formBenefits` has been renamed to `FORM_BENEFITS`
- `formLinks` has been renamed to `FORM_LINKS`
- `trackingPrefixes` has been renamed to `TRACKING_PREFIXES`
- `sipEnabledForms` has been renamed to `SIP_ENABLED_FORMS`

The links present in the bullet points for these variables should also be updated to point to the respective line numbers within https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/forms/constants.js

Feel free to let me know if there is anything that is unclear about the changes, thanks!

### Relevant URLs
https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-how-to-set-up-save-in-progress-si

Ticket URL: https://github.com/department-of-veterans-affairs/va.gov-team/issues/65114

### Which type of team are you on? (Platform team, VFS team, or Leadership)

Authenticated Experience Teams (VFS), although the changes are in the Platform code and our code

**Comment by johnny-jesensky-adhoc** [comment]
HI @adamwhitlock1, thank you for flagging this, and appreciate the specific guidance on what needs updating. The Platform Content Team will review these changes, and will reach out if we have any further questions.

We will provide further updates in this ticket, and let you know when the changes have been deployed to the site. Thank you!

FYI @jknipes

**Comment by taylojill** [comment]
Hi @adamwhitlock1 - I'm a member of the Platform Content team and will be working on your request. I'll review it and check back with you soon! Thanks!

cc @jknipes

**Comment by taylojill** [comment]
Hi there @adamwhitlock1 - I updated the page as requested. Here's a link to the page in our draft space in Confluence: [https://vfs.atlassian.net/wiki/spaces/PWD/pages/3100082177/Draft+VA+Forms+Library+-+How+to+set+up+Save+In+Progress+SiP](url)
cc @jknipes
 
Please review and let me know if you approve, and I'll get the page published. Here's what I did...

1. The second bullet has been updated to: In the [VA_FORM_IDS object in the /platform/forms/constants file](https://github.com/department-of-veterans-affairs/vets-website/blob/bbd17c20a03e01ef22e5247a37d073ee10c47992/src/platform/forms/constants.js#L1), form information found in the formConfig should be added to the following objects:...
2. The secondary bullets have been renamed and links updated to:
[FORM_BENEFITS](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/forms/constants.js#L76) - property name imported from the VA_FORM_IDS object with a string value that briefly summarizes the form: [VA_FORM_IDS.FORM_21_526EZ]: 'disability compensation'

    [FORM_LINKS](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/forms/constants.js#L147) - property name imported from the VA_FORM_IDS object with a value that calls the function getAppUrl. The parameter passed to getAppUrl is the entryName of the application specified in the [registry.json file in the content-build repository](https://github.com/department-of-veterans-affairs/content-build/blob/8fd8cb2592dde48f90c7573cad222cf45b4fcb64/src/applications/registry.json#L207). Example: [VA_FORM_IDS.FORM_21_686C]: `${getAppUrl('686C-674')}/

    [TRACKING_PREFIXES](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/forms/constants.js#L209) - property name imported from the VA_FORM_IDS object with a string value that’s identical to the trackingPrefix property found in the formConfig of the form being worked on. Example: [VA_FORM_IDS.FORM_21_526EZ]: 'disability-526EZ-' and [corresponding trackingPrefix property in formConfig](https://github.com/department-of-veterans-affairs/vets-website/blob/46fc93d7f426c536e4a54176842c2e4b71ef74a5/src/applications/disability-benefits/all-claims/config/form.js#L140)

    [SIP_ENABLED_FORMS](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/forms/constants.js#L241) - property name imported from the VA_FORM_IDS object

**Comment by taylojill** [comment]
Page updated as requested, checked for launch blocking issues, ready for deployment - 4/23/2024
