### ISSUE TITLE
FE | MHV&DS Logon Retirement | February-March initial messaging (awareness + encouragement)

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#73357]
## Background 
DS logon and MHV credentials are being retired and we need to display alerts advising users to update to the alternative login options. 

We've worked to figure out the messaging in #73358 

We need to complete the FE work for the initial round of the messaging/awareness campaign about the credential retirement.

We should only display this for DS Logon and MHV users.

## Open questions [answered] 
- what page and what locations on that page should be answered by #73358
- can we work this story in the same sprint as #73358 or is that effectively a blocker? [ no we cannot work this at the same time, we need the answers from that story ] 
- can we use the same feature flag as the `#secure-sign-in-transition` team [ should be okay to move forward - a[sking about the toggle name here](https://dsva.slack.com/archives/C068QM7CCKG/p1707416499761189)] 

## Designs
- [figma file](https://www.figma.com/file/OmY3qqcBnK043nnnUvlsjh/%2373358---Auth-Exp-Credential-Retirement-Phase-1?type=design&node-id=1-2509&mode=design&t=YpRnnYjiw7Ufc97L-0)

### Maintenance work
While working on the account security page we should incorporate the outstanding issues that were called out in other tickets 
#### 2FA vs Multifactor authentication content change 
- #74053 < this ticket was closed because it was incorporated into #73358
#### misc content updates 
- #63079 
#### link text update to include your 
- #53574

## Acceptance Criteria 
- [ ] we've got deployable code behind a shared feature flag

**Comment by mtcA6** [comment]
I couldn't test with a DS Logon User but was able to confirm this was functioning as expected for MHV user. 

![Image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/52949cfb-1437-4d41-8e30-597d71118ab0)

**Comment by adamwhitlock1** [comment]
I can 'replicate' DS Logon in staging using some of my dev wizardry and verify that it is at least displaying when dslogon is the `signIn.serviceName`

![Screenshot 2024-02-29 at 8 47 06 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8332986/ae4dbd5b-bf95-475d-9ab9-457b7fbc2cbe)

**Comment by mtcA6** [comment]
Adam [confirmed the LOA1 state as well in this thread](https://dsva.slack.com/archives/C909ZG2BB/p1711055509295379)

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/000e5981-3309-4203-9940-9e598168d12c)
