### ISSUE TITLE
Vets-api terminal access for Austin Smith

### ISSUE THREAD

**Issue by HeatherRienks** [department-of-veterans-affairs/va.gov-team#73377]
### Your Name

Austin Smith

### Your GitHub handle (terminal access is managed through GitHub)

@asmithgovcio

### Team, Role, and Company of the target individual

Debt Resolution. Backend Engineer, GovCIO

### Product Manager (PM) name and email

Tom Davis, thomas.davis@govcio.com

### Product Owner (PO) name and email

Denise Coveyduc, denise.coveyduc@va.gov

### COR Name (leave "None" if you listed an AWS user name above)

Jennifer O'Day

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

Agile Six - Anthony M. Arashiro

### Please confirm if you are listed as a team member in Atlas or are listed in Platform Team Roster

- [x] [Team Member in Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [X] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Please confirm E-QIP Transmittal/Adjudication. This could be a screenshot of your Transmittal/Adjudication email, a link to another request where you've submitted this proof (i.e. AWS/SOCKS), etc.

- [X] I have attached proof that I have either transmitted my E-QIP survey or previously received a favorable decision (by including in "Additional Notes" section below)

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### Additional Notes

Austin needs access to assist in troubleshooting FSR Form 5655 submissions for Veterans.

Please see ticket #72890 (SOCKS access) which confirms EApp (eQIP) proof of adjudication.

Thanks!

### Additional resources for Support Engineer

- [ ] For users on a VFS team but not listed as a team member in Atlas, they must start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] Instructions for handling requests [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access) - Support Only

**Comment by HeatherRienks** [comment]
@asmithgovcio - FYI

**Comment by bdech** [comment]
Confirmed user in Atlas

Confirmed [E-QIP ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/72890)

**Comment by bdech** [comment]
@asmithgovcio You’ve been granted access to the `dev`, `staging`, and `sandbox` environments.

Here's some additional documentation for [Vets API on EKS](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-TerminalAccess) that may help.


cc: @HeatherRienks

**Comment by bdech** [comment]
Access to `prod` is pending approval by OCTODE, and we'll update you as soon as it's available.

**Comment by bdech** [comment]
Production Access Justification: Austin needs access to assist in troubleshooting FSR Form 5655 submissions for Veterans.

**Comment by bdech** [comment]
@asmithgovcio You've been granted access to `Production`
with access to limited to 6 months, expiring 07/11/24.

Please set a reminder for yourself to return to this Issue and 
request an extension within 1 week of the expiration date. You'll 
receive 1 reminder with a 72 hour window to respond. Failure to 
respond will result in your access being revoked and will require 
you to fill out a new request.

**Comment by asmithgovcio** [comment]
@bdech thank you

**Comment by bdech** [comment]
Support slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1704991330608589)

**Comment by lindsay-insco** [comment]
@asmithgovcio Your Vets API Terminal Production access has expired.

Would you like to request an extension? You have 72 hours to respond, or your
access will be revoked and you will need to fill out a new request.

**Comment by lindsay-insco** [comment]
It has been over 72 hours with no response. Production access has been removed for @asmithgovcio
