### ISSUE TITLE
Accessibility Testing for [Non-disability Benefits, Pension Benefits 21P-527EZ, Re-release (MVP)]

### ISSUE THREAD

**Issue by ToddWebDev** [department-of-veterans-affairs/va.gov-team#73379]
### Product information

- [X] Team name, product name, and feature name have been added to the title of this issue.
- [X] Team label, product label and feature label (if applicable) have been added to this issue.

### Use of color and color contrast checks

- [X] All text of 20px or smaller has a 4.5:1 contrast ratio to its background (or better)
- [X] All text of 20px or larger has a 3:1 contrast ratio to its background (or better)
- [X] Non-text elements have a 3:1  contrast ratio to their background and to neighboring elements (or better)
- [X] Color is not the only way to distinguish links from other text (eg. links are underlined)
- [X] Any charts, maps, infographics, and tables convey all information without only relying on color
- [X] Content does not refer to color, especially when providing user instructions (eg. "Click the blue button")

### How did color testing go?

Color contrast meets all requirements (exceptions in axe check comments)

### Who completed the axe scans?

@jstrothman 

### axe checks

- [X] Each page has been scanned using axe (results shared below)
- [X] axe is integrated into your end-to-end testing

### axe DevTools scan results

Hint color on "add another" pattern inaccessible on the following pages:
- [Spouse's former marriage](https://staging.va.gov/pension/application/527EZ/household/marital-status/spouse-marriages)
- [Gross monthly income](https://staging.va.gov/pension/application/527EZ/financial/income-sources)
- [Medical expenses](https://staging.va.gov/pension/application/527EZ/financial/medical-expenses/add)

### Who completed the content zoom and reflow test?

@jstrothman 
### Content zoom and reflow checks

- [X] All page elements are readable and usable at 200% zoom
- [X] All page elements are readable and usable at 300% zoom
- [X] All page elements are readable and usable at 400% zoom

### How did content zoom and reflow testing go?

success

### Who completed the keyboard navigation test?

@jstrothman and @gmaciolek 

### Keyboard navigation checks

- [X] Each link, button, form input, checkbox, radio button, select menu, and custom element can receive keyboard focus
- [X] Each link, button, form input, checkbox, radio button, select menu, and custom element responds to expected keys
- [X] All elements under focus have a visible focus indicator
- [X] The order of [Tab] stops made sense and was appropriate for completing tasks

### How did keyboard testing go?
We found a few issues:
- [Step 5 Gross Monthly Income: Fix accessibility issue/keyboard navigation for Gross Monthly Income list loop](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/gh/department-of-veterans-affairs/va.gov-team/73299)
- [Form elements inconsistent in receiving focus when an error message is displayed](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/gh/department-of-veterans-affairs/va.gov-team/73471)
- [Keyboard focus issue in Safari with VoiceOver enabled](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/gh/department-of-veterans-affairs/va.gov-team/73472)

**Comment by jstrothman** [comment]
[Accessibility testing artifact (Goog spreadsheet)](https://docs.google.com/spreadsheets/d/14lavdk8mmyqav7NJ_JpKW4yWtH7Ln-ekSdmsp511NUE/edit#gid=0)
