### ISSUE TITLE
Access for Edward Boehme - VAMC-Upgrade team - GovernmentCIO

### ISSUE THREAD

**Issue by EdwardBoehme05** [department-of-veterans-affairs/va.gov-team#7338]
•	Description:  Please provide SOCKS proxy access as this is required to complete support work on VAMC-Upgrade product.  Access needed for: dev, staging, prod,  CI environments and Jenkins.

•	 Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole

•	 Please provide your name.
   > Edward Boehme

•	 Please provide the name of your team, your role on that team, and the name of the company you work for.
Team:  VSA-VAMC-UPGRADE / VAMC-UPGRADE,  
Role:  Business Analyst, 
Company:  GovernmentCIO

•	[if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC19FUP5spSmSwxX3c9CemiX1oP31qswLUeY7jfrygCPIpEAGhar9rb8+F3wOB37yoGZ2csbmHTfw+dK0pl73ONcT7o6ec7yaXlGR2rOFMWQLD4lWISYJOoUNx1V6Z3ThqgU9s7Db3g4/tjnZkIi1+gN8mB7UQ+RqauZbQyPZPsCy8qixSesClrt9xwDuZ3j4WQwgEdjg92MHeYloBTNc/YdhRcVV5QfW5pg92wHM2nkkPauCiiSjIQvTGflLaZN7rNw7r5X6VFj3R/ph/0RESdVgcSxvRyFzpZQ+/6G5gXtk0ZsLDXusukNWtZxJk7ifv/hOiYcjKr3jOybxrcpx12rZdZ/gm8e2PeMRK+5NzfFf3UfGsBwrS8w6mi9CJeNqQaurcJDW0XRBzT05ByJNEppU/XnMS7JpJXLmUU5Dz4gTPTY/yKU2DXDUtccWphtagKG6kxT9oMKBPzXqgcdpoHa9uK5fmVZ1/NMlW+OUKpLdnEitSthOk9Nyhl+y25R30= 
Edward Boehme@DESKTOP-07SV3JD

•	[Grant AWS Console access?]
  > NO

**Comment by jbritt1** [comment]
For visibility: @vsp-operations

**Comment by jbritt1** [comment]
SOCKS access granted. @EdwardBoehme05 please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.
