### ISSUE TITLE
AWS access for Austin Smith

### ISSUE THREAD

**Issue by HeatherRienks** [department-of-veterans-affairs/va.gov-team#73385]
### COR Name

Jennifer O'Day

### Vendor Onboarding Representative Name

Agile Six - Anthony M. Arashiro

### Your Name

Austin Smith

### Your Email

austin.smith@govcio.com

### Team, Role, and Company of the target individual

Debt Resolution, Backend Engineer, GovCIO

### Product Manager (PM) name and email

Tom Davis, thomas.davis@govcio.com

### Product Owner (PO) name and email

Denise Coveyduc, denise.coveyduc@va.gov

### Desired AWS Access

Access to all resources related to vets-api project.

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

![Proof of adjudication - Austin Smith](https://github.com/department-of-veterans-affairs/va.gov-team/assets/85908655/58d8c8d4-1b9a-41a9-aae9-3a61061b8369)

### Additional Notes

Access should be maintained until Austin is no longer associated with the VFS contract.

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [x] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by HeatherRienks** [comment]
@asmithgovcio - FYI

**Comment by patrick-black-oddball** [comment]
Found in Atlas

**Comment by patrick-black-oddball** [comment]
waiting for response from Austin

**Comment by asmithgovcio** [comment]
@patrick-black-oddball what do you need from me on this ticket?

**Comment by patrick-black-oddball** [comment]
completed ...
