### ISSUE TITLE
[spike] NOD | Setup callback reporting for NOD email notifications

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#73397]
## Value Statement
**_As a_** Veteran who may have been unable to file an NOD after being unable to access VA.gov 
**_I want to_** get notified about next steps I can take if my email bounces
**_So that_** I understand how to file if my filing deadline is nearing or has passed. 

---
## Background Context
- Work with VA Notify ([ticket here] (https://github.com/department-of-veterans-affairs/va.gov-team/issues/65509))to create a callback report tracking Veteran emails that return a hard bounce.
- As part of onboarding they can work with our technical team to get the callbacks set up. They would just need us to provide a callback URL that utilizes a long-lived bearer token. This gets configured for your service (think of it like a notification template workspace), which they'll create in their self-service portal. Any notifications sent would produce delivery status callbacks. Our team can utilize this information to track and report on individual Veteran notification success. Note: Opens are not something they can share by notification/Veteran. That data is aggregated by the platform's Google Analytics and surfaced in a Domo dashboard.

## Tech Tasks
- [ ] Provide a callback url that utlizes a long lived bearer token

## Definition of Ready 

- [ ] We know who to reach out to (Beverly and Melanie from VA Notify)

## Definition of Done

- [ ] We know how to setup the callback reporting URL
- [ ] Ticket is created for the code work (or this one is used) (Code work ticket: #74832)

**Comment by saderagsdale** [comment]
- Ask VA notify: What data would VA Notify send to that callback URL?

**Comment by saderagsdale** [comment]
Eugene will start looking at Tech task noted above

**Comment by HeatherWidmont** [comment]
Derek is working on this. Messaged the VA Notify team about ?s about the tickets. Derek will add their response in the comments.

**Comment by dfong-adh** [comment]
> VA Notify uses bearer tokens for authenticating with services when making a callback. The bearer token can be any form that the called service endpoint accepts. These should be long-lived, but not permanent, bearer tokens.
Each service will have their own policy for updating a long-lived bearer token. Contact VA Notify if an updated bearer token is required to meet security policies.
We recommend not hardcoding acceptance of only a single bearer token, so bearer token updates are not disruptive.

Callback format:
```
"id":"6ba01111-f3ee-4a40-9d04-234asdfb6abab9c",  -- this is the notification id
"reference":null,  
"to":"",  -- this is the recipient's contact info
"status":"delivered",  -- this will specify the delivery status of the notification
"created_at":"2023-01-10T00:04:25.273410Z",  
"completed_at":"2023-01-10T00:05:33.255911Z",  
"sent_at":"2023-01-10T00:04:25.775363Z",  
"notification_type":"SMS",   -- this is the channel/type of notification
"status_reason": "", -- populated if there's additional context on the delivery status
"provider":"pinpoint"
```

**Comment by saderagsdale** [comment]
@dfong-adh What are the next steps to consider this spike complete?

**Comment by dfong-adh** [comment]
We will need to investigate further regarding PII (specifically the recipient's contact info being an email address). I will discuss this with Platform Security. Additionally, we will be reaching out to other teams that have already integrated with VA Notify regarding how to best implement the callback endpoint with bearer token authentication. Once I have this information I can create a ticket for coding work.

**Comment by saderagsdale** [comment]
@dfong-adh Can you drop some "next step" notes and a link to the ticket for the code work here? Once it's refined and ready, we can start working on it.

**Comment by dfong-adh** [comment]
Brief summary of the conversation with Platform Security:
* Storing PII (email addresses for the purposes of this ticket) is not a major concern for Platform Security as production tables already store that type of information
* Ensure that we are not duplicating efforts/existing code in creating a table to store email addresses + status

Next steps:
* Determine the policy regarding how frequently bearer tokens need to be changed
* Decide on callback url
* Implement bearer token authentication for callback endpoint (we can contact VA Notify for help if necessary)
* Provide callback url + bearer token to VA Notify team

Coding ticket: #74832
