### ISSUE TITLE
SOCKS access for [Rebecca Ferguson]

### ISSUE THREAD

**Issue by rferguson13** [department-of-veterans-affairs/va.gov-team#73403]
### Your Name

Rebecca Ferguson

### Your Email

rferguson@thesocompany.com

### Your Role and Team

Content on the Governance Team

### Product Manager (PM) name and email

Shira Goodman shira.goodman@oddball.io

### Product Owner (PO) name and email

Shira Goodman shira.goodman@oddball.io

### Access Type Requesting

platform

### Public SSH Key
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDbq7OTAvlWML3TnrxJTbLnthiJ/dTsEpxcyogyYjFYm9F8Fntuv7gTwevStmlHmeUte7icDqVDtXzGcgrlvVk9CJVnhl4nlANa9QxU8NYC4n7V4Ivpx/jg8DhKZ1S2YgCjgJnLsTzW0AgPP4GT3mKYrdMAtDBslqvgaWnLv9hf2MdkPfDd4zBycYZXpKZ534nOTnkCPgXjoP3JGWKzhILVV7kxGXSvnoixCwtXn3xDqK/AkDO53b9FS4Fre7R9saiXQz1GjFIJ5+H6TsCif37O1nV647yZnMfZjzPMwfw2ZtyZi8H0uul8dVtIL0fTlJ26xby76NrhDgNBjGptz86o1bvfXPVgMZHMHmJeQMPvOLeeJnc29YpzIIBrnGZC1/dDIFqsdDaYb10whQHN/yAGgrjmym3fW7yDp6XrGfqEegCt9EMEiBx8P9wy5JQN/hOxq98nyuWTyVB4vzWJwEYga1ld3bmVEEC0Yjh30zOTpIX06ZOLJqiAjpxetk59uuk= rebeccaferguson@Rebeccas-MBP

### E-QIP Transmittal Confirmation

<img width="1440" alt="Screen Shot 2024-01-12 at 9 26 59 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/146865799/6805da42-afad-4f72-be87-e96e2fc039df">

### User must exist in a roster before SOCKS access can be granted

- [x] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by patrick-black-oddball** [comment]
Completed

**Comment by rferguson13** [comment]
It should be closed! I have SOCKS access now.
