### ISSUE TITLE
Design system -- Improve Experience for VFS teams

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#7340]
**Painpoint:** VFS teams don't know when components are added to design system. VFS teams don't know how to request things are added to design system. VSP doesn't think everything in design system is accessible. Not everything across sketch, formation and react are consistent. 
**How will we solve the pain point:** Building a governance model. Auditing and fixing accessibility issues. Auditing and fixing inconsistencies. 
**The desired outcome:** A clear understanding of ownership and processes. A fully accessible design system. Consistency across the 3 pillars. 

### High Level User Story/ies

As VSP, I want the design system to be consistent across the sketch library, formation and the react library so that VFS teams can easily utilize it to build features/products/enhancements on VA.gov.

As a VFS team member, I want to know how to propose changes to the design system so that my suggestions fall into a queue instead of not being implemented.

As a VSP accessibility expert, I want to know that everything in the design system is accessible so that VFS teams can easily build accessible features. 

As a VFS team, I want to know when changes are made to design system so that I know what to utilize in there for future projects. 

As VSP, I want to know who owns design system so that we can get stakeholder buy-in to any major changes or initiatives we want to implement. 

### Problem Statement
Changes are often made to sketch library without being made in the react library or formation
VFS teams don’t know how to get changes to the design system implemented
Teams don’t know when changes are made to design system
There is no clear owner of design system -- Is it the design council? 
There aren’t functional examples in design system for VFS teams to work off of

## Measuring Success (KRs/KPIs)
KR2: Reduction in time it takes to perform a VSP review across 5/10 practice areas
KR1: Increase in customer NPS

### Goal(s)
Address all the problem statements above. Make sure there is process in place that everyone (VFS, VSP, DEP)  is aware of. 

### Assumptions and Hypotheses
We **assume** there are components in design system that aren’t accessible
We **assume** that there are inconsistencies across sketch, formation and the react library

We **hypothesize** that having a clear governance model for design system will give clarity to everyone across VFS teams, VSP and DEPO
We **hypothesize** that having clear processes around making changes to design system will increase customer NPS
We **hypothesize** that having functional examples of code in design system will allow VFS teams to build faster
We **hypothesize** that marketing changes to design system will make VFS teams feel more confident in their understanding of what should be utilized during different scenarios when building new features

## Areas for Discovery
We want to figure out what is the best governance model to use for design system
We want to audit for accessibility
We want to audit for consistency across formation, sketch library and the react library

**Comment by andreahewitt-odd** [comment]
Audit for accessibility
Audit for consistency across sketch/formation/react (are crystabel’s changes showing up anywhere else?)
Great governance model:
Create process for requesting changes
Create process for implementing changes (who is responsible for build?)
Create process for marketing changes to design system -- Release notes? Versions?
Clearly define who owns it
Create functional examples of code for VFS teams to use. (Either to copy/paste into their code or riff off of it to modify for their needs)

Potentially a Future Epic
Create a way to update components without breaking them across va.gov. (Reduce stress of bumping design system in vets-website -- More test coverage or something to make people not afraid to merge to vets-website and break something. Produce components that will spit out a warning or an error at build time.)

**Comment by mandifrances** [comment]
Here are the artifacts. 
VSP owned processes: https://docs.google.com/document/d/13WLc371RKHk0yvOpU_tz7fgWY7xwrzu0b--dWrQjif0/edit?usp=sharing
Design system governance flowchart: https://docs.google.com/drawings/d/1XlBCV0kHtQsmtrfqxk8_Ap7o_wEK8_F2kT3aMG50BLc/edit?usp=sharing

**Comment by 1Copenut** [comment]
Moving this to close with the design system council and team up and running.
