### ISSUE TITLE
Sidekiq Admin UI access for Austin Smith

### ISSUE THREAD

**Issue by HeatherRienks** [department-of-veterans-affairs/va.gov-team#73418]
### Your Name

Austin Smith

### Your GitHub handle (Sidekiq Admin UI access is managed through GitHub)

@asmithgovcio

### Team, Role, and Company of the target individual

Debt Resolution, Backend Engineer, GovCIO

### COR Name

Jennifer O'Day

### Please confirm if you are listed as a team member in Atlas or the Platform Team Roster

- [X] [Team member in Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [X] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Sidekiq UI Access requested for the following environments

- [ ] dev
- [ ] staging
- [ ] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### If PRODUCTION ACCESS is required, confirm/complete ONE of the following

- [ ] I have an AWS Username and it is listed in [here](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf)
- [X] I currently have access to vets-api Production Terminal via ArgoCD
- [ ] I've attached a screenshot of my E-QIP Transmittal Notice E-mail (Drag or Copy/Paste in Additional Notes Section below)

### Additional Notes

Austin needs this for his duties on the Debt Resolution team.

**Comment by HeatherRienks** [comment]
FYI @asmithgovcio

**Comment by bdech** [comment]
Confirmed in Atlas.

E-QIP can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/72890)

**Comment by bdech** [comment]
Access to `production` is pending approval by OCTODE, and we'll update you as soon as it's available.

**Comment by JonathanKamensDVA** [comment]
Approved.

**Comment by bdech** [comment]
@asmithgovcio You've been granted access to `Production`,
with access to Production limited to 6 months, expiring 07/12/24.

Please set a reminder for yourself to return to this Issue and
request an extension within 1 week of the expiration date. You'll
receive 1 reminder with a 72 hour window to respond. Failure to
respond will result in your access being revoked and will require
you to fill out a new request.

**Comment by bdech** [comment]
support slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1705076815523289)
