### ISSUE TITLE
VSP Collaboration Cycle — V2: Conduct User Research & Improve Scalability

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#7342]
### High Level User Story/ies
As a VFS team, I want to be able to use VSP's collaboration cycle without feeling like I'm being unnecessarily slowed down so that I can develop in an agile framework. 

As a VSP team member, I want to be able to use the collaboration cycle to make sure that features and products being launched are meeting the best practices of my practice area so that I can feel confident VA.gov will work for everybody. 

As DEPO, I want to be able to guide my team using my expertise and the resources I know of without feeling slowed down by processes that aren't valuable.

### Problem Statement 
Collaboration Cycle V1 was implemented as an attempt to consolidate all existing processes by practice area into one. We made many assumptions, some of which have been invalidated since V1 release, and knew we would need to iterate based on feedback. For example: we assumed that VFS teams were already following existing processes by practice area (and therefore that presenting all existing processes as part of the Collab Cycle would actually be _leaner_ for VFS teams) — that has been invalidated with qualitative data from VSP and VFS. For V2, we need to formally gather feedback on the Collab Cycle from VFS teams, VSP reviewers, and DEPO, so that we can evaluate where to make changes that will allow us to improve our "process-to-value" ratio. 

How might we iterate on the Collaboration Cycle to ensure that each collaboration point provides value to VFS teams? 
How might we iterate on the Collaboration Cycle to ensure that it does not leave practice areas out — such as engineering? 
How might we clarify VSP's expectations for which initiatives are expected to follow the Collaboration Cycle and how to enter into it?
How might we better track success of the Collaboration Cycle? 
How might we account for increasing automation of accessibility checks? 

### Hypothesis or Bet
- If we update the Collaboration Cycle to include more robust support earlier on in development, then we will alleviate the VFS/DEPO pain points around Staging Review and enable better outcomes for VA.gov.
- If we scale back parts of the Collaboration Cycle that aren't providing direct value (such as unnecessary meetings), then we will provide a higher "process-to-value" ratio.
- If we have a stronger go-to-market strategy with DEPO for V2, then we will see more positive sentiment and adoption of the Collaboration Cycle among VFS teams.

### OKR
O1: Teams have efficient experiences using the platform to build impactful products for Veterans, where their expectations are exceeded.
O1KR2: Increase in positive feedback from teams on the value of the platform quarter over quarter
O1KR3: Net reduction in time it takes to perform VSP review (collaboration cycle) across 5 practice areas

### Success metrics 
- Percentage of staging reviews that proceed without major intervention
- Number of VSP support requests related to Collaboration Cycle 
- Percent of team builds tracked in a compliance tracker
- Increase in affirmative response from VSP teammates on whether they feel customers are taking + acting on their feedback

### We will know we're done when...
We have addressed 3 themes of customer pain points and 3 themes of VSP pain points. We have introduced any launch blocking changes to DEPO customers and have a strong go-to-market strategy. 

### Additional Details/Notes (optional)
Ideas & areas for discovery: 
- Should we implement an actual process-to-value ratio? If we make meetings optional, a success criteria could be how many reviews proceed without meetings.
- Distinguish “reviews” (ensuring that VA.gov products have met minimum standards) from “support” (collaboration throughout development, actively _helping_ VA.gov products meet VSP standards)
- Identify minimum standards and levels of engagement for VFS teams to meet by practice area — now tracked in #10359 

### Artifacts
- [Collaboration Cycle product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/vsp-collaboration-cycle/product-outline.md)

### Communication
- Team that owns this super epic: Product Support
- Teams contributing to this super epic: Content & IA

**Comment by meganhkelley** [comment]
Updating super epic per new template for Q3 roadmapping, and capturing these notes here from the previous template: 

**Areas for Discovery**
Work with Service Design to solicit feedback from DEPO and VFS teams
Solicit feedback from reviewers
Determine how accessibility resources will handle collaboration points
Prioritize measurement of KPIs (maybe tracked separately?)
Change survey
Create content only changes flow
Potentially adjust QA artifacts (work with Peter and Tze)
Should we rename the templates? Prebuild, pre launch?
Determine if the collab cycle is too heavy
Determine if we need a dev intent checkin
Make changes re:integrating KPIs (?)

**Comment by meganhkelley** [comment]
Update at end of Sprint 29: 

- User research was completed 
- Reviewer retro was completed — [themes summary](https://docs.google.com/document/d/1DhfNJEbT2Y3auVymgllCyPpjQRIUGx83lZuzNCQCH4s/edit#heading=h.yne8ac3id2ab)
- Mandi (new VSP Product Support PM) is working with Kevin H to plan for initial iteration workshop (there's an [old brainstorm doc](https://docs.google.com/document/d/1H7Y50HkxY5eXflgcBFoWhhzzYVmNsUA8UYFZuz7osDE/edit) for these iteration workshops that lists the groups of reviewers we were thinking about)
- I am attending the VSA All Hands on 7/9 to present a brief update on Collaboration Cycle iterations
