### ISSUE TITLE
As an applicant, I need a copy of form 10-10d that I can interact with so that I can enter my information

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#73426]
If this is already complete, this can serve as a verification ticket and cover pushing the code to staging. This user story is meant to cover any foundational work so that a base page exists on staging so that we can view 10-10d WIP in a static location in the staging environment.

Acceptance criteria

Given a member of the IVC forms team 
- When they visit an established page for form 10-10d in staging
- Then they can see what's been deployed for the 10-10d front end

**Comment by michaelclement** [comment]
Visiting [staging](https://staging.va.gov/ivc-champva/10-10D/introduction), you can see the what's deployed 10-10d front-end so far.

**Comment by baltes** [comment]
reviewed on staging
