### ISSUE TITLE
Increase quality of test coverage

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#7343]
Enhance TestRail integration

- CI/CD pipeline pulls: logic in place to determine “If this build has appropriate manual test coverage that has been executed and passed in the past nn business days then proceed with build.”  Or, "If this build has a test run associated with it that is in a 'passed' state then proceed with build."
- CI/CD pipeline pushes: Automated test results, accessibility test results, and load test results to related TestRail projects to provide a unified understanding of test coverage for a product
- Enforce reference links within TestRail in order to require teams to document their user stories and create appropriate acceptance criteria.

**Comment by 1Copenut** [comment]
@andreahewitt-odd can we close this issue?

**Comment by pjhill** [comment]
I love all these idea still. I guess this would be the purview of the FE tools team?

**Comment by 1Copenut** [comment]
@pjhill Do we want to keep this one open and reassign it to our test team?

**Comment by pjhill** [comment]
> @pjhill Do we want to keep this one open and reassign it to our test team?

Yeah, this is a good candidate for test team work, IMO.

**Comment by shiragoodman** [comment]
added TTT label, removed Product Support

**Comment by pjhill** [comment]
This ticket has been converted to separate work items in our 2022 Q2 planning https://app.mural.co/t/adhocvetsgov9623/m/adhocvetsgov9623/1644952482334/f52fb52c30e3abe0413788dde0712227355c15f2?sender=peterhill4315, and will be converted to distinct issues in the future.
