### ISSUE TITLE
As an applicant, I need the ability to enter my sponsor information

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#73444]
If this is already complete, this can serve as a verification ticket and cover pushing the code to staging.

Acceptance criteria

Given a user in the process of completing form 10-10d
- When the user steps through the form
- Then the user sees the sponsor section of the form
- and the sponsor section includes all fields in the sponsor section of the paper form

**Comment by michaelclement** [comment]
This section is complete and pushed to staging.

**Comment by baltes** [comment]
reviewed on staging
