### ISSUE TITLE
As an applicant, I need the ability to enter my applicant information

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#73443]
If this is already complete, this can serve as a verification ticket and cover pushing the code to staging.

Acceptance criteria

Given a user in the process of completing form 10-10d
- When the user steps through the form
- Then the user can navigate to the applicant information section of the form
- and the user can enter information for at least one applicant
- and the user can complete all of the fields for the applicant information section currently on the paper form for at least one applicant

**Comment by michaelclement** [comment]
Initial applicant information section has been pushed to staging (see this [pull request](https://github.com/department-of-veterans-affairs/vets-website/pull/27462))

The file upload interface is in a [pull request awaiting platform approval](https://github.com/department-of-veterans-affairs/vets-website/pull/27502). Once that's pushed out then this ticket will be complete.

**Comment by michaelclement** [comment]
It should be noted that file uploads will be supported on the front end, but not on the back end yet. For that to work on staging we'll need to open a pull request to vets-api with updates to the backend controller.

**Comment by michaelclement** [comment]
Blocked while we wait for platform approval

**Comment by baltes** [comment]
reviewed on staging
