### ISSUE TITLE
As an applicant, I need the ability to enter my certification information

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#73445]
If this is already complete, this can serve as a verification ticket and cover pushing the code to staging.

Acceptance criteria

Given a user in the process of completing form 10-10d
- When the user steps through the form
- Then the user sees the certification section of the form
- and the section includes a field for each field currently on the paper form

Any specific requirements for digital signatures are out of scope for this user story.

**Comment by michaelclement** [comment]
[Pull request](https://github.com/department-of-veterans-affairs/vets-website/pull/27556) has been submitted, awaiting platform approval

**Comment by michaelclement** [comment]
PR merged and is deploying to staging.
