### ISSUE TITLE
As an applicant, I need the ability to save my progress

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#73447]
If this is already complete, this can serve as a verification ticket and cover pushing the code to staging.

Acceptance criteria

Given a user in the process of completing form 10-10d
- When the user leaves the form and comes back
- Then the user can resume without re-entering what has already been entered in the fields of the form

This story doesn't have to include save in progress for document uploads.

**Comment by michaelclement** [comment]
SIP added in [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/27524), currently blocked as we wait for platform approval.

**Comment by michaelclement** [comment]
<img width="902" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGpUQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c9b512ec01e77b09fd8117a688cb23136fa65a01/Screenshot%202024-01-17%20at%2008.36.43.png" alt="Screenshot 2024-01-17 at 08.36.43.png" />

<img width="845" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOG5UQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b2470e52871f923a4df37ecf042cdf9fb89bc35b/user_profile.png" alt="user_profile.png" />

**Comment by michaelclement** [comment]
Platform approved - PR merged

**Comment by baltes** [comment]
Reviewed for authenticated user on staging
