### ISSUE TITLE
IPP - Design a final screen for Veteran Intake Flow

### ISSUE THREAD

**Issue by lmorris3** [department-of-veterans-affairs/va.gov-team#73458]
**Problem** 
A question came up in Devign Sync around the end of the Veteran Intake flow. Do we need some kind of success screen or way to more formally "exit" the application? Where should Veterans go after they complete intake? (What were they in the middle of doing? Did the intake app open in a new window? What would be the most logical next step for them?)

How might we present the most important information to the Veteran in a final screen? How might we allow them to close the application easily and confidently?
For future iterations (MVP): How might we provide options that reflect the most logical next steps a Veteran would take? 

Questions:

- should participants keep their session with Login.gov active as they open up our intake flow?
- If so, do we need to have a success screen at the end of our intake flow and a permalink that sends them back to Login.gov? Do we add these components to the final screen instead?

**User Story**
As a Veteran, I need to know what to do next when I complete IPP Intake so I feel confident that I've made an appointment and I will be prepared for it.

**Acceptance Criteria**
GIVEN I am a Veteran who has completed IPP intake
WHEN I am viewing the last screen
THEN I clearly see the most important information about my upcoming appointment, including next steps
AND I see that I have completed all steps of the intake process

See Activity Diagram notes:

https://app.mural.co/t/innovationboards1199/m/innovationboards1199/1703788679467/65f5c546ca6d59dedcc63e2806d915e30aff3350?sender=uea69eca39541ca1a0bea5755

**Comment by skirkman16** [comment]
<img width="971" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTUwQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0fdbd99dba5941b89958a4c6b23f0913629b2158/Screenshot%202024-02-20%20at%209.10.15%20AM.png" alt="Screenshot 2024-02-20 at 9.10.15 AM.png" />
Draft [link](https://www.figma.com/file/PfrWKmxiQ5RjChwx6I18QE/IPP-Prototypes?type=design&node-id=2945%3A9122&mode=design&t=7lZvf9b3sN21rLT9-1) on page 'Prototype - In Person Pilot'

**Comment by skirkman16** [comment]
[Draft link](https://www.figma.com/file/PfrWKmxiQ5RjChwx6I18QE/IPP-Prototypes?type=design&node-id=2945%3A9122&mode=design&t=7lZvf9b3sN21rLT9-1)

**Comment by skirkman16** [comment]
Page 'Prototype - In Person Pilot'

**Comment by lmorris3** [comment]
@SophiaPhilipMO @CarlDickerson @lmorris3 ready for review

**Comment by SophiaPhilipMO** [comment]
@skirkman16 there are some edits @CarlDickerson and I have dropped in, let me know if you've been able to review.

**Comment by skirkman16** [comment]
Reviewed and resolved all comments on the screen. Final screen attached. <img width="935" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFNhQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--211b01af9da8ac847c4f1f313edeb68fbd6f04b2/Intake%20-%20Registration%20complete.png" alt="Intake - Registration complete.png" />
