### ISSUE TITLE
Sidekiq Admin UI access for Tom Harrison

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#73466]
### Your Name

Tom Harrison

### Your GitHub handle (Sidekiq Admin UI access is managed through GitHub)

@tpharrison

### Your dsvagovcloud AWS user name (if applicable)

tom.harrison

### Team, Role, and Company of the target individual

Backend Engineer

### COR Name

Rolanda Copeland

### Please confirm if you are listed as a team member in Atlas or the Platform Team Roster

- [X] [Team member in Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [X] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Sidekiq UI Access requested for the following environments

- [ ] dev
- [ ] staging
- [ ] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### If PRODUCTION ACCESS is required, confirm/complete ONE of the following

- [X] I have an AWS Username and it is listed in [here](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf)
- [X] I currently have access to vets-api Production Terminal via ArgoCD
- [ ] I've attached a screenshot of my E-QIP Transmittal Notice E-mail (Drag or Copy/Paste in Additional Notes Section below)

### Additional Notes

I need access to this because some of our BE services depend on Sidekiq jobs.  Having access to the Admin UI will help me troubleshoot issues with background jobs.

**Comment by bdech** [comment]
confirmed in Atlas

E-QIP confirmed in AWS [Access Request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/42776)

**Comment by bdech** [comment]
Access to `prod` is pending approval by OCTODE, and we'll update you as 
soon as it's available.

**Comment by bdech** [comment]
@tpharrison I know the VOR confirmed your E-QIP transmittal in your AWS access request I linked above, but are you able to provide a screenshot of your E-QIP transmittal?

**Comment by JonathanKamensDVA** [comment]
Aproved.

**Comment by bdech** [comment]
@tpharrison You've been granted access to `Production`, 
with access to Production limited to 6 months, expiring 07/12/24.

Please set a reminder for yourself to return to this Issue and 
request an extension within 1 week of the expiration date. You'll 
receive 1 reminder with a 72 hour window to respond. Failure to 
respond will result in your access being revoked and will require 
you to fill out a new request.

**Comment by bdech** [comment]
support slack reminder [here](https://dsva.slack.com/archives/C02RLAUM2LV/p1705076690102159)

**Comment by tpharrison** [comment]
@davidpetras Yes, I would like an extension.  Thanks!

**Comment by davidpetras** [comment]
@tpharrison  your Production access has been extended for 6 months,
expiring 01/13/25.

Please set a reminder for yourself to return to this Issue and 
request an extension within 1 week of the expiration date. You'll 
receive 1 reminder with a 48 hour window to respond. Failure to 
respond will result in your access being revoked and will require 
you to fill out a new request.

**Comment by tpharrison** [comment]
Will do!  Thanks!
