### ISSUE TITLE
IPP - Design list of ID types that are not accepted

### ISSUE THREAD

**Issue by lmorris3** [department-of-veterans-affairs/va.gov-team#73464]
Through usability testing with Veterans, it was revealed that Veterans could be confused about the ID types they are permitted to bring since ours are somewhat non-standard. How might we provide clarification about what ID types will be accepted and which ones will not?

User Story

As a Veteran, I need to know what ID type to bring to my Proofing Appointment so I can complete IPP without issues.

Acceptance Criteria

GIVEN I have accessed the Veteran Intake application and signed in to Login.gov
WHEN I am viewing the list of ID types I may bring
THEN I can clearly see which ID types are admissible and which ones are not

Verbiage:

Current 
<img width="439" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMU85QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ae374768820e028458e4b3b17b76b5b7f011d806/Screenshot%202024-01-11%20at%201.49.56%20PM.png" alt="Screenshot 2024-01-11 at 1.49.56 PM.png" />

**Comment by skirkman16** [comment]
ID's that come to mind plus ID's we explored in our [mural](https://app.mural.co/t/innovationboards1199/m/innovationboards1199/1695820153034/32f3e6c4093009c2efd77322120d2f069af2c981?sender=u99cd1ac4f5c240d8dffd4204):

- Passport
- VIC
- College ID
- Retiree/dependent ID cards
- DoD cards
- Disability cards
- Uniformed Services ID card
- Foreign identity documents

**Comment by skirkman16** [comment]
Next step write out descriptions ahead of MVP

**Comment by skirkman16** [comment]
Priority: Passport, VIC, College ID will not be accepted.

**Comment by skirkman16** [comment]
@lmorris3 will follow up with @porta-antiporta about DoD

**Comment by JKG199** [comment]
@skirkman16 @SophiaPhilipMO @lmorris3 here's the doc I started for the content! 
https://docs.google.com/document/d/14gVA1sexqozlCJeqz50GPFZ4rni1CmjOaGvQwR5YLrk/edit?usp=sharing

**Comment by skirkman16** [comment]
Added definitions for accepted and non-accepted forms of ID to the document. Added references for definitions and a list of non accepted IDs from USAccess for further consideration

**Comment by SophiaPhilipMO** [comment]
Updated[ doc](https://docs.google.com/document/d/14gVA1sexqozlCJeqz50GPFZ4rni1CmjOaGvQwR5YLrk/edit?usp=sharing) to remove VHIC from required to not accepted
