### ISSUE TITLE
Current state mapping: SME session, increase fidelity (2/3)

### ISSUE THREAD

**Issue by karafaithsanchez** [department-of-veterans-affairs/va.gov-team#73475]
**Problem**:
A lo-fi version of the current state journey for VSOs has been created [here](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1701101229797/15c7e1a5a9d426a998eb634408ff1dd3f4f9bdd1?sender=ucd326fb05b27d09e40350092). There are some questions still TBD and formatting that needs to be done, to more clearly understand the relationship between people, processes, and technology. 

**Plan**:
As part of increasing the fidelity of this journey map, this will also be converted into more of a Service Blueprint so that it can be an actionable artifact across disciplines (design, product, engineering). 
Ideally Design will work with a SME deeply knowledgeable about the current POA process and/or with VSOs, Attorneys and Claims Agents to get feedback on our Current State journey map and add any missing steps / workarounds.

1. Identify SME
2. Schedule 1 hr process mapping session
3. Incorporate feedback & convert to Service Blueprint

**Output**:
Hi-fi Service Blueprint documented in the [Current State / Future State Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1701101229797/15c7e1a5a9d426a998eb634408ff1dd3f4f9bdd1?sender=ucd326fb05b27d09e40350092) that is ready for iteration based on findings from user sessions. 

**Acceptance Criteria**:
- SME Session was conducted
- Blueprint created
- Any knowledge gaps or unanswered questions identified and incorporated into user session question set
- Reviewed by another designer

**Comment by karafaithsanchez** [comment]
Work with SME deeply knowledgeable about the current POA process and/or with VSOs, Attorneys and Claims Agents to get feedback on our Current State journey map and add any missing steps / workarounds.

**Comment by karafaithsanchez** [comment]
@RivkaCGates please take a look - hoping to bring this into the upcoming sprint

**Comment by karafaithsanchez** [comment]
@RenataKeck please review by EOD Tue. thank you!

**Comment by RenataKeck** [comment]
@karafaithsanchez moving to done, please address small comments when you pick up the next ticket for this artifact. Great work!
