### ISSUE TITLE
IPP - Discovery: PII Bundle Storage

### ISSUE THREAD

**Issue by lmorris3** [department-of-veterans-affairs/va.gov-team#73470]
Problem: Where are we going to store it?

Acceptance Criteria:

- Rahul to schedule meetings with Steve, LHDI, Joe Niquette (Core)
- Develop and document plan for how and where to store
- Share documented plan with Tom/relevant stakeholders (store on Github)
- 

Next steps:
- create ticket to implement PII bundle storage

**Comment by rdvyas** [comment]
We will not be storing the PII bundle based on our current plan. The intention was too send the PII bundle at some future point to update an account to IAL2 status, but given there is no timeline established to accomplish this, we have opted not to store this PII. 

As an alternative we have discussed creating the PII bundle in the future as we have the information to build out the payload, but that is best addressed in a separate discovery if and when we opt to include this feature.
