### ISSUE TITLE
ARF Design Onboarding - Kristen

### ISSUE THREAD

**Issue by karafaithsanchez** [department-of-veterans-affairs/va.gov-team#73477]
**Outcome**: 
Resources and research artifacts to review to help Kristen onboard to the ARF Team! 
Questions should be asked in the OCTO Slack channel. We recommend moving through this checklist in order, rather than hopping around. To the best of our ability, we have tried to provide context for the level of review needed for each item. 

As you're moving through the checklist, feel free to:
- Ask any questions in the OCTO Slack channel #benefits-representative-facing
- Add any open questions to [ARF Open Questions](https://docs.google.com/document/d/1qQjq5IEMGW4ZDPdDI22LuBY6JxFiuUzNgty4KqRX5q8/edit#heading=h.hc4r5od8cxww) (Google Doc)

-----------------------------------
**High-Level Project Overview**
- [x] **SKIM** [Visual Breakdown in Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1704209289585/904f4f60fccc4e9b015d92d97f19f37347614e6f?sender=ucd326fb05b27d09e40350092) of Product Brief and Accredited Representatives White Paper
**If preferred, review original documents:**
&nbsp;&nbsp;&nbsp;&nbsp; - [Accredited Representatives White Paper](https://dvagov.sharepoint.com/sites/vaabdvro/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=QIRHZa&cid=866978cd%2D2497%2D496e%2Dadae%2D42c02258162e&FolderCTID=0x01200073ECFC0A16DB51439C06C6FDC0E92947&id=%2Fsites%2Fvaabdvro%2FShared%20Documents%2FAccredited%20Representative%20Facing%2FAccredited%20Representatives%20on%20VA%2Egov%20Brief%20%28JQ%29%20%2D%20draft%2Epdf&viewid=3fa7a9bb%2D3d4e%2D44c2%2Db93f%2D629268a08e72&parent=%2Fsites%2Fvaabdvro%2FShared%20Documents%2FAccredited%20Representative%20Facing) (Sharepoint) - Note that there are links to prior research that are covered elsewhere in this ticket.
&nbsp;&nbsp;&nbsp;&nbsp; - [Product Brief](https://dvagov.sharepoint.com/:w:/r/sites/vaabdvro/_layouts/15/Doc.aspx?sourcedoc=%7B55B2D6F7-1D14-49A3-8018-B6F943EB0931%7D&file=Representative-facing%20tools%20-%20Product%20vision.docx&action=default&mobileredirect=true) (Sharepoint)

- [x] **READ** [What is an Accredited Representative?](https://www.benefits.va.gov/vso/) (VA.gov)
- [x] **SKIM/BOOKMARK** for later this [glossary of terms and their definitions](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/research/terminology-definitions.md) related to accredited representatives (GitHub)

**Background Research**

- [x] **WATCH** [Secondary research literature overview](https://dvagov.sharepoint.com/sites/vaabdvro/_layouts/15/stream.aspx?id=%2Fsites%2Fvaabdvro%2FShared%20Documents%2FAccredited%20Representative%20Facing%2FPast%20Research%2FAR%5Fsecondaryresearch%5Fpreso%2Emp4&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview) (Sharepoint). Covers what's been done on VSOs, gaps in knowledge. Note that this is an overview recording of [this report](https://github.com/department-of-veterans-affairs/va.gov-team/blob/fc4cf2841f56caea6bb66502b29a4ef1cf25abde/products/accredited-representation-management/research/2023-09-secondary-research/2023-09-secondary-research-accredited-representation-management.md) (GitHub). I would recommend starting with the recording and looking at the report or the Lighthouse research as needed to fill in knowledge gaps; a deep-dive is not necessary.
- [x] **SKIM/BOOKMARK** for later: [VEO/Lighthouse research on VSOs](https://github.com/department-of-veterans-affairs/lighthouse-ux/tree/master/Benefits%20and%20Appeals%20Research) (GitHub). Much of this is covered in the secondary literature review, and learnings have been added to in-progress research artifacts.

**Current State/SEP**

- [x] **SCAN** As you're moving through current state resources, feel free to add to/edit/leave comments in our [Current State Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1701101229797/15c7e1a5a9d426a998eb634408ff1dd3f4f9bdd1?sender=ucd326fb05b27d09e40350092). 
- [x] **REVIEW** [Personas](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1701101259400/65b0c7a81b3837794b36d55a3c1f6ab3629253f2?sender=ua71936780d8bc9a2d2b29830) (Mural) - VSOs only
- [x] **WATCH** [SEP Walkthrough with DAV](https://dvagov.sharepoint.com/:v:/s/vaabdvro/Ee3gR_HqQ45CnY4OO5URNgYBJ-4haXSIx60F8Mmwz0MzPw?e=uJTLu9&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D) (Sharepoint) - one of the 'big 6' VSOrgs
- [x] **WATCH** the [SEP Demo](https://dvagov.sharepoint.com/:v:/r/sites/vaabdvro/Shared%20Documents/Accredited%20Representative%20Facing/Research/SEP%20Demos/SEP%20Demo%20with%20CTO-20231208_111227-Meeting%20Recording.mp4?csf=1&web=1&e=a3abDH) (Sharepoint) with the VEO team behind the tool. Note that these are SMEs we interviewed ([Link to research plan in Google Doc](https://docs.google.com/document/d/1i7SGMj0ishpbNZ1tRYY_ZKZL_I9hHiQm6JXUnwT-oT4/edit)). 
- [x] **SCAN** SEP-specific [existing research](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1695929155059/a302158eccec694ec7089bd6a02954421721987d?sender=ua71936780d8bc9a2d2b29830) (Mural). Note that some of these resources overlap with the literature review and the recordings linked elsewhere in this ticket. The research reports about SEP are very interesting!
- [x] **EXPLORE** - Pull login credentials to [SEP and eBenefits](https://dvagov.sharepoint.com/:x:/r/sites/vaabdvro/_layouts/15/Doc.aspx?sourcedoc=%7BD10426C1-A013-4818-9B90-1A213E83DA01%7D&file=SEP%20Account%20For%20Testing.xlsx&action=default&mobileredirect=true) and explore on your own! (Sharepoint)
- [x] **WATCH** [SME Interview](https://dvagov.sharepoint.com/sites/vaabdvro/_layouts/15/stream.aspx?id=%2Fsites%2Fvaabdvro%2FShared%20Documents%2FAccredited%20Representative%20Facing%2FResearch%2FSME%20Interviews%2FMarty%20Caraway%20%2D%20recording%2Emp4&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview) with Marty Caraway, VSO liaison (Sharepoint)
- [x] **WATCH** [Accredited Representative listening session](https://dvagov.sharepoint.com/:f:/r/sites/vaabdvro/Shared%20Documents/Accredited%20Representative%20Facing/Research/01-23-24%20Representative%20Listening%20Session/Recording?csf=1&web=1&e=cRufIR) (Sharepoint) and **REVIEW** the [findings report](https://docs.google.com/document/d/10GwEHzdVfaBydnrtx9br9YnDaTlDlT7jvBMo28Xy0B4/edit#heading=h.5cqfkqo9cc9b) (Google Docs)
- [x] _if there's time_ **WATCH** at least 1 of these [earlier VSO interviews](https://dvagov.sharepoint.com/sites/vaabdvro/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=QIRHZa&cid=866978cd%2D2497%2D496e%2Dadae%2D42c02258162e&FolderCTID=0x01200073ECFC0A16DB51439C06C6FDC0E92947&id=%2Fsites%2Fvaabdvro%2FShared%20Documents%2FAccredited%20Representative%20Facing%2FPast%20Research%2FRecordings&viewid=3fa7a9bb%2D3d4e%2D44c2%2Db93f%2D629268a08e72) (Sharepoint). Notes are in the Existing Research Mural and there is a lot of overlap with these interviews and the walkthrough, so no need to go too in-depth

**Future State**

- [x] **REVIEW** the [design research roadmap](https://docs.google.com/document/d/1Ksk88KhZcXFJxySHNC9icoacRUoISJznsGb0VfFSqX0/edit#heading=h.m4rk6edp852v) (Google Docs)
- [x] **REVIEW** [initial wireframe concepts](https://www.figma.com/file/C3sdnDf8anVqXVdmiCWwq8/%F0%9F%9A%A7-Accredited-Rep-Facing?type=design&node-id=0%3A1&mode=design&t=5J0tyHhIb4TA1DKh-1) (Figma). Comment in file with questions/suggestions.

-----------------------------------
**Next Steps**

Depending on your preference / how you work best, feel free to add to the following **while** you're going through things above, or **after**. 

- [x] **ADD** to ideation of [Future state mapping](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1701101229797/15c7e1a5a9d426a998eb634408ff1dd3f4f9bdd1?sender=ua71936780d8bc9a2d2b29830) (Mural). You may want to look at the [Future State Mapping epic within ZenHub](https://app.zenhub.com/workspaces/accredited-representative-facing-team-65453a97a9cc36069a2ad1d6/issues/gh/department-of-veterans-affairs/va.gov-team/72043) and provide feedback on any missing tickets.

**Join ARF Design Research Activities**

- [x] Join weekly ARF Design meetings: ARF x VA Enablement (Mondays 12-12:45 Pacific)
- [x] Join the [Benefits Accredited Representative (BAR) Design Slack](https://dsva.slack.com/archives/C0643ADPP60) (OCTO workspace)
- [x] Join the BAR Design Sync (Fridays from 12-12:50pm Eastern), ask Lesley for an invite
- [x] Add to the [BAR Design Sync weekly agenda](https://docs.google.com/document/d/1q3viYPfg2SAtAiyujrnCDBQzJjtwC966aBGFidi3P0k/edit#heading=h.jvgk0qlnx3km) (Google Docs)

**Comment by kristen101606** [comment]
Onboarding is complete! (Though I'm still learning lots and continue to reference many of the above documents.) Thanks for putting this list of resources and tasks together, @karafaithsanchez.
