### ISSUE TITLE
Competitive Research Analysis: Phase II Rate Tool

### ISSUE THREAD

**Issue by UXCamG** [department-of-veterans-affairs/va.gov-team#73473]
## High Level User Story
As a Veteran Support team, I need  to understand our competitions use of the rate tool so I can  ensure that we are building a quality sustainable product 

## Goals
_What outcome(s) do we want to see?_ 
 3 countries with a rate tool on their resources and support pages 

## How to configure this issue
- [x] *Identify 3 major competitors*
- [x] Compare product features

**Comment by ATMiddleton** [comment]
@UXCamG will attach analysis

**Comment by UXCamG** [comment]
[Analysis ](https://1drv.ms/w/s!AhM7ym-CJ7FDkG88xP0w8PyE7OSU?e=Fc8bHr)

**Comment by ATMiddleton** [comment]
@UXCamG added analysis - Closed
