### ISSUE TITLE
Analytics Implementation or QA Support for [Benefits Non-Disability Experience - VR&E Orientation Slideshow]

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#73498]
# Google Analytics Implementation Request

### Please provide the following details for this request

- **Team Name**: Benefits and Claims | Non-Disability Experience

- **Product Name**: Vocational Rehabilitation & Education (VR&E aka Chapter 31 aka form 28-1900)

- **When is the launch date?**: We're addressing accessibility issues within the current form experience and a slideshow that appears as part of the form wizard was flagged as an issue. We also believe the slideshow interrupts user flow and presents information available elsewhere, so we'd like to remove it. There is no specific launch date.

- **Provide the link(s) for Product/Page urls**: [VR&E start page](https://www.va.gov/careers-employment/vocational-rehabilitation/apply-vre-form-28-1900/start). To view slide show, answer "Veteran", "yes", and "yes" to the three start wizard questions.
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/134541644/1a2dce42-b971-4ebb-a522-eb93d4d3de12)

- **What Events need to be tracked?**
    - We would like to understand how many visitors over the last 12 months have clicked the button to start the orientation slideshow.
    - Ideally, we'd like to correlate the number of button clicks with the number of visitors to the page, but let me know if that's not possible. (Ex: Over the last 12 months, xx% of unique visitors to the start page started the slideshow.)

- **If applicable, what test users are needed?** none

- **Any additional comments**: none

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by steele-lm** [comment]
@jestutt @johnny-jesensky-adhoc @Blivaditis Hey! I wanted to check in on the expected timeline for this request. We're working to schedule a meeting with our SMEs, and I wanted to wait to schedule until we better understand the usage of this slideshow component. Thanks!

**Comment by Blivaditis** [comment]
Hi Laura, the issue should be completed by early next week. Once the tracking is implemented we will let you know.

**Comment by Blivaditis** [comment]
Hi Laura, the request to track the slide show has been implemented and is working properly. You are able to find the metrics within Google Analytics. If you need any help navigating there please reach out! 
<img width="1894" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzhKQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f4d6d5f9b83bbc04ca20c70e1156f71e2fc1795f/Screenshot%202024-01-29%20at%209.35.54%20AM.png" alt="Screenshot 2024-01-29 at 9.35.54 AM.png" />
