### ISSUE TITLE
Setup/Synchronize test users between VA.gov staging and Travel Pay API Non-prod

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#73501]
## Description
VA.gov staging uses a limited set of test users (not associated to real people). In order for integration testing to go smoothly, especially once we start hitting authenticated endpoints, we must inform the APi team which users and corresponding use cases we'd like to test. This allows the API team to add the fake data to the appropriate database.

Note: it may be possible to have 1 user with all possible travel claim use cases.

## Acceptance Criteria
- [x] Users chosen - `speak to the VA.gov BTSSS team to get details on which user to use`
- [x] Use cases chosen - `no complex use cases right now`

## Demo
- Demoable? No
- Why? At this point, only selecting a user. Nothing tangible to show

## Definition of Done
- [x] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by kjduensing** [comment]
@micahtaylor @carafrissell1 Would you say this is a decent (simple) representation of all the claim statuses we'll be supporting?

- In Process
- Claim Submitted
- In Manual Review
- Denied
- Appealed
- Closed/No Payment
- Partial Payment
- On Hold
- Approved
- Submitted
- Fiscal Rescinded
- Paid
- Payment Canceled

**Comment by micahtaylor** [comment]
@kjduensing  It's what exists today but there are some that are challenging to users based on feedback.
Specifically `Fiscal Rescinded` and `On Hold`.

**Comment by kjduensing** [comment]
disorganized notes: https://docs.google.com/document/d/1f-qD679RpEsK3zXRJi8AwL6AVwHCQix6x8tBdaHcfoM/edit

**Comment by kjduensing** [comment]
Meeting scheduled to discuss integration/testing needs

**Comment by kjduensing** [comment]
From the meeting: we're all for the easy thing to start:
- Kurt will send over a list of users they use. We can cross ref that with our list of users
- It might be possible to create a fake entry in CRM and start there. Josh will look into that
- If nothing else works, we'll have to do it the hard way which will add time

Other topics:
- Tim will try to make Swagger doc the source of truth and hosted
- Josh will look into preprod access from our local machines.
