### ISSUE TITLE
QA Standards - Public Websites - PACT Act Wizard

### ISSUE THREAD

**Issue by it-harrison** [department-of-veterans-affairs/va.gov-team#73518]
### Status
[2024-07-25] [Fran C] I've started a test matrix and will prioritize getting it finished soon.

#### VFS team name
Public Websites

#### VFS product name
PACT Act Wizard

#### Point of Contact/Reviewers
@it-harrison - Ian Harrison - QA

---
#### Regression Test Plan 
- [x] Standard has been met
- [ ] Standard has not been met
#### Test Plan
- [x] Standard has been met
- [ ] Standard has not been met
#### Traceability Reports 
- [ ] Standard has been met
- [x] Standard has not been met
##### Explanation of failure to meet standard (if applicable): #####
no Traceability artifacts included

#### E2E Test Participation
- [x] Standard has been met
- [ ] Standard has not been met
#### Unit Test Coverage
- Lines %: 90.74

- Functions %: 88.43

- Statements %: 90.99

- Branches %: 79.19

- [x] Standard has been met
- [ ] Standard has not been met
##### Explanation of failure to meet standard (if applicable): #####
---
### VFS Guidance

- Close the ticket when your Product Owner determines that you have sufficiently met the QA Standards.
- If your team has additional questions or needs Platform help validating the issue, please comment on the ticket

### Platform directions
- Update "Issue Title" to be of the form "QA Standards - VFS Team - VFS Product"
- Add the VFS team, product name, and feature name
- Add your name, practice area, and GH handle under Point of Contact/Reviewers
- Complete the QA Standards section, making sure to include an "Explanation of failure to meet standard" for every Standard the product does not meet.
- Link to the Collaboration Cycle Request epic
- Add epic's milestone
- Add assignees: 
  - VFS PM
  - Yourself (optional)
- Add labels:
  - VFS team label
  - VFS product label
  - QA-standards label
  - launch-blocking label if the product has failed to meet a required QA Standard

**Comment by FranECross** [comment]
cc @jilladams

**Comment by FranECross** [comment]
@it-harrison Thank so much for this review! Regarding not meeting the Traceability Report standards, do you have an example we can look at? I actually thought the Traceability Report was optional/not a blocker for the Collab Cycle reviews, but will work with the developer to get one put together. Thank again! cc @jilladams @randimays

**Comment by FranECross** [comment]
@shiragoodman @it-harrison Question for you. The only item on this ticket 'not met' is the traceability matrix, which I understand is still optional (although good to have). I'm slowly but surely creating one (the PACT Act is extremely convoluted with many path options). BTW We will be using the PAW Mural flow diagram to QA. My question is: since we met all required standards, may I close this ticket? Thanks! cc @jilladams

**Comment by shiragoodman** [comment]
@FranECross yes, you can close the ticket! Thank you for checking.
