### ISSUE TITLE
As an applicant, I need to upload individual files so that I can provide supporting documentation for my application

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#73527]
If this is already complete, this can serve as a verification ticket and cover pushing the code to staging.

Acceptance criteria

Given a user in the process of completing form 10-10d
- When the user is required to provide additional supporting documents
- Then the user can upload a file as part of completing form 10-10d

**Comment by michaelclement** [comment]
@baltes I believe this is satisfied per these (and potentially other) PRs
- [Conditional files for child applicants](https://github.com/department-of-veterans-affairs/vets-website/pull/28084)
- [Conditional files for applicant related by marriage](https://github.com/department-of-veterans-affairs/vets-website/pull/28138)
- [Applicant medicare upload](https://github.com/department-of-veterans-affairs/vets-website/pull/28140)
- [Sponsor info file upload](https://github.com/department-of-veterans-affairs/vets-website/pull/27991)
- [File upload properties added to submission transformer](https://github.com/department-of-veterans-affairs/vets-website/pull/28113)
