### ISSUE TITLE
As an applicant, I need my supporting documents prepared for routing to the VA

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#73528]
Acceptance criteria

Given a user who has uploaded one or more documents in support of their form 10-10d
- When their form is submitted
- Then their form 10-10d is generated in a PDF
- and each supporting document can be passed to the VA as an individual file

We can assume all files can be PDFs, but we should be aware of other options in case other systems need something other than PDFs in the future.

If we're currently appending attachments to the application PDF, this story will cover breaking up those individual documents into separate files.

**Comment by cloudmagic80** [comment]
The VA applicant can upload their attachment in pdf, jpg, pneg, or img. We accept these 4 types of documents. The final product of the attachments will only be PDF.

**Comment by baltes** [comment]
Closing this as a duplicate of https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/76452
