### ISSUE TITLE
As an applicant, I need my supporting documents tied to my application

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#73529]
Acceptance criteria

Given a user who has uploaded one or more additional documents in support of form 10-10d
- When their form 10-10d is submitted
- Then their form 10-10d has a unique identifier
- and each of their supporting documents references their form 10-10d's unique identifier

**Comment by cloudmagic80** [comment]
@baltes We can send them a confirmation number. Do they want the confirmation number stamped to each of the pdfs? Do they also want an email?

**Comment by baltes** [comment]
@cloudmagic80  We'll have to get details from them but I would assume they'll need to see those identifiers in the metadata for each document so that it can be queried in their system.

**Comment by cloudmagic80** [comment]
Finished writing test cases. Ready for code review .

**Comment by cloudmagic80** [comment]
the unique identifier will be completed on ticket 75558

**Comment by baltes** [comment]
@cloudmagic80 I couldn't find 75558, is it on the board?
