### ISSUE TITLE
Collaborate with Analytics to help them launch Platform KPI Dashboard on Domo

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#7354]
## Description
The Backend Tools team will be assisting the Insights and Analytics team during their Design of the overall data structure for Domo.  Their current goal is to provide a Product success tool that will power app teams to monitor the performance of their apps, however there is a growing desire to leverage platform data sources to start thinking about, and potentially building a "Platform" dashboard that can be monitored by the VSP.  The exact metrics are currently unknown, but the idea of looking at the platform as a true "Product" that is measurable is becoming increasingly important.

Our goal (BE Tools) will be to identity what metrics are available to us through different means and come up with a prescription for how to centralize key elements to be exposed through our Data Warehouse and visualization tools.

Examples of this could include (but aren't limited to):
SLO Reports and data.  This data could be transfered to BigQuery (possibly in aggregation) to bigquery for a longer storage look back window.  Additionally the visualization would then be handled by Domo and its generation could be automated.

Data that is stored in Logs that is hard to get to that could be valuable could be aggregated and transferred  to a data warehouse.

## In Scope
Assisting during the design phase with recommendations on what data is available
Providing feedback on what we think are important metrics
Prioritizing any work to make data points available in a fashion that the Insights can consume (i.e. aggregation, building end points, etc)

## Out of Scope
Building any type of visual representation of data.

## Product Outline
[Link](https://docs.google.com/document/d/1GuuhRXT8-NjEHdFHysNg1VA1o89Qr0_Mkrg46Q8kBeI/edit#)

## High Level User Story/ies
As a developer on the BE Tools team, I need to provide support to the insights and analytics team during their planning phases so I can help determine what data points are available to expose from the different down stream "platform" systems.

## Hypothesis or Bet
If we provide the feedback around data point exposure now, we expect the Insights team will have greater success in providing valuable reports surrounding applications and the platform as a whole.

## OKR
Objective 4: All of the Platform's KPIs are easily measured and shared openly.

**Comment by kfrz** [comment]
## Notes & Errata

- https://prometheus.io/docs/operating/integrations/#remote-endpoints-and-storage

**Comment by LindseySaari** [comment]
## Approaches for Storage Options ^^ Related to above comment

### Approaches:
Thanos
Remote write 
Creating a snapshot — Question: where is prometheus data stored?
