### ISSUE TITLE
update cert rotation alerts

### ISSUE THREAD

**Issue by jhouston0** [department-of-veterans-affairs/va.gov-team#73558]
## Issue Description. 
The new requirement for cert rotation is to update cert alerts (regardless of env's) 30 days before the window hits. Please configure the cert alters to be at 60 days out and 45 days
---
## Tasks
- update cert alerts
## Acceptance Criteria
- [ ] cert slack alerts updated

**Comment by vidjovanovic** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/.github/workflows/certreminders.yml

<img width="1474" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNW9zQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--376b2a45b7efb92d5a8a802cb3e5a0aa477c0526/image.png" alt="image.png" />
