### ISSUE TITLE
CF: Utilize data mapping of caution flag content on the Search Results page

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#7356]
## Acceptance Criteria: 
As a Veteran searching for institutions using the GI Bill Comparison Tool, I need to know what types of caution flags the institutions I'm considering have so that I can make the best decision about my education choices.

## Assumptions: 
1. This story covers the back end data structure and mapping to provide data points for subsequent display on the front end.
2. This work will be behind a prod flag so that it is only available on staging. 
3. The UI of this story is covered in #6803 (Search Results Page)

## Acceptance Criteria: 
1. On the Search Results page, caution flag content is displayed as follows based on the xls file linked in supporting artifacts as Caution Flag Content: 
a. Caution Flag Title maps to Cell E6 or E7, based the number of warnings.  If 1, E6, if multiple, E7. 
b. Caution Flag Description maps to Column F 
![Screen Shot 2020-04-03 at 2.16.18 PM.png](https://images.zenhubusercontent.com/5b645f6fe2255460d8f0b032/ee885edd-4aef-4289-b945-984baf3fc08b)

## Supporting Artifacts: 
1. Prototype: https://bahdigital.invisionapp.com/share/N5IAD8MHTC9#/screens
a. Note that this version of the prototype includes notations that signify content mapping described in the acceptance criteria
2. Caution Flag Content: [Caution Flag Copy for Review v.2.0.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4376665/Caution.Flag.Copy.for.Review.v.2.0.xlsx)

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/12119

Can be tested on vets-website branch `search-flags`

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-04-07 at 11.47.32 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/be60b667-8860-4e56-b098-e8a1a0f545fe)
##
![Screen Shot 2020-04-07 at 11.48.00 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/414e26f4-e9cc-44a7-bceb-011936d3930b)

**Comment by sonntag-adam** [comment]
Does not show in production build

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/279&group_by=cases:section_id&group_order=asc&group_id=46

**Comment by sonntag-adam** [comment]
Closing story, fixes will be completed in https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/7743
