### ISSUE TITLE
[Other - Accessibility] Focus management for error states not consistent with other VA.gov forms. (00.00.1)

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#73579]
#### VFS team name
Public Websites

#### VFS product name
PACT Act Wizard

#### Point of Contact/Reviewers
Brian DeConinck - @briandeconinck - Accessibility

*For more information on how to interpret this ticket, please refer to the [Anatomy of a Staging Review issue ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Anatomy-of-a-Staging-Review-Issue-ticket.2060320997.html) guidance on Platform Website.

---

### Platform Issue
No VA.gov Experience Standard for the issue found.

### Issue Details
When you press Continue without making any selections, the error message is announced but keyboard focus remains on the Continue button. 

In other existing forms on VA.gov, when there's a validation error when a user presses Continue, focus moves back to the containing element of the field with the error with `tabindex="-1"`. (In the case of multiple errors, focus moves to the first field with an error.) That means after getting an error, your first tab stop is the input where you can correct the error.

A user expecting that behavior and pressing tab after hearing the error message on the PACT Act wizard would instead jump down to the feedback button, then have to shift+tab back to get back to the expected place. The actual impact for users is probably not huge (this is a pretty straightforward interaction, can't imagine a ton of users will ever even see the error message). But it's a potential point of friction, especially for screen reader users who might not have an intuition about where the feedback button is relative to the form and might be a little thrown off when they hear that instead of what they expected.

### VA.gov Experience Standard
[Category Number 00, Issue Number 00](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

### Platform Recommendation
Match the focus behavior for other forms on VA.gov. I think sending focus to the `fieldset` would give you a comparable experience and makes sense with how this is coded, but it's worth double-checking with a screen reader to verify that gets announced cleanly.

---

### VFS Guidance

- Close the ticket when the issue has been resolved or validated by your Product Owner
- If your team has additional questions or needs Platform help validating the issue, please comment on the ticket
- Some feedback provided may be out of scope for your iteration of the product, however, Platform's OCTO leadership has stated that all identified issues need to be documented and it is still your responsibility to resolve the issue.
- If you do not believe that this Staging Review issue ticket is the responsibility of your team, comment below providing an explanation and who you believe is responsible. Please tag the Point of Contact/Reviewers. Governance team will research and will follow up.

**Comment by randimays** [comment]
Validated successfully in staging (as PACT Act is not yet in prod). Closing!
