### ISSUE TITLE
New VFS Team Member Template Drew Connelly

### ISSUE THREAD

**Issue by drewconnelly** [department-of-veterans-affairs/va.gov-team#73589]
## Welcome and Introduction
Welcome to the Department of Veterans Affairs (VA) Veteran Facing Services (VFS) team!

As a new VFS team member, you will be working in the web ecosystem we call the VA.gov Platform (or "**The Platform,**" for short).  The tasks on this list are designed to get you up to speed on the role of Platform, making it easier for you to do your job.

Because the VA is a huge organization that serves millions, the Platform it runs on is equally big, complex and multilayered. Most people find that even learning the basics for their own practice area entails a significant learning curve.  The tasks on this checklist will help you acquire those basics as quickly and efficiently as possible.

## User Story
As a new VFS team member, I need to complete onboarding activities so I can successfully work on my project and support the VA.gov Platform.

## How to fill out this ticket
- [x] Add your name to the ticket title
- [x] Complete the Onboarding Checklist below
- [x] Under **Get set up for your practice area,** you only need to complete the items for your role
- [x] You can close this ticket when all items are completed in the Onboarding Checklist and the Platform Checklist

### Share your info with Platform
- [x] Complete the fields below:
 - Name: Drew Connelly
 - Pronouns (e.g. she/her): he/him
 - Role: Back-end Engineer
 - Email: drew@apothesource.com
 - GitHub handle*: drewconnelly
 - Start date: 1/12/2024
 - VFS Team: Unified Appointment Experience

*Providing your GitHub handle will allow Platform to provide you access to the necessary GitHub repos.

### General

- [x] For [General orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions#OrientationSessions-Generalorientation) sessions, either attend a live session (schedule via Calendly) or watch the latest recorded session.
- [x] Update your [Slack profile](https://depo-platform-documentation.scrollhelp.site/getting-started/slack-profile)
- [x] Watch [VA.gov overview video](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html#PlatformOrientation-Purpose) for an overview of VA.gov
- [x] Watch [VFS Orientation for Platform Website video](https://www.youtube.com/watch?v=yzl6nyLmqkA&ab_channel=PlatformCrew)
- [x] Watch the [Platform Support overview video](https://www.youtube.com/watch?v=iwIQU4XepNQ)
- [x] Review the [Getting help from the Platform in Slack guidance](https://depo-platform-documentation.scrollhelp.site/support/getting-help-from-the-platform-in-slack)
- [x] Review [Welcome](https://depo-platform-documentation.scrollhelp.site/getting-started/Welcome.1255276574.html) documentation
- [x] Review [Support Overview](https://depo-platform-documentation.scrollhelp.site/support/Support-overview.604012552.html) documentation
- [x] Review the guidance on [Submitting a feature request](https://depo-platform-documentation.scrollhelp.site/support/Submitting-a-feature-request.1938915400.html)
- [x] [Request Access to Tools](https://depo-platform-documentation.scrollhelp.site/getting-started/Request-access-to-tools.969605215.html)
- [x] Confirm that you have access to the [VA GitHub Organization](https://depo-platform-documentation.scrollhelp.site/getting-started/request-access-to-tools#Requestaccesstotools-GettingaccesstotheVAGitHuborganization)
   - **Note:** Membership in the VA Github Organization is a prerequisite for getting access to `vets.gov-write` and access to many commonly-used repositories. Platform will not be able to complete this task if you are not a member of the VA GitHub Organization.
### Norms and standards
- [x] Review guidance on the [Platform Satisfaction Survey](https://depo-platform-documentation.scrollhelp.site/support/platform-satisfaction-survey)
### Working on the platform
- [x] Review the [Platform Principles](https://depo-platform-documentation.scrollhelp.site/getting-started/platform-crew-principles)
- [x] Review the [GitHub Markdown Cheatsheet](https://help.github.com/en/categories/writing-on-github) to learn the syntax for formatting documents in GitHub
- [x] Review the [Digital Modernization Strategy](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-gov-relaunch-2018/va-gov-strategy/digitalmodernizationstrategy.pdf)
- [x] Review the [Web Brand Consolidation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-gov-relaunch-2018/va-gov-strategy/the-new-va.gov-briefing-2019-07.pdf) documentation
- [x] Review the [Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) documentation on Platform Website
- [x] Are you a Veteran? Consider adding your name to the [Veterans willing to help VA teams with product testing](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/team-veterans.md) document

#### Designers & Researchers
- [ ] Review the [Research and Design Guide on Platform Website](https://depo-platform-documentation.scrollhelp.site/research-design/index.html)
- [ ] Learn how we do [research at VA](https://depo-platform-documentation.scrollhelp.site/research-design/research-at-va)
- [ ] Watch the [getting started with design videos](https://depo-platform-documentation.scrollhelp.site/research-design/getting-started-with-design)
- [ ] Get oriented to the [Design System](https://design.va.gov/)
- [ ] Get oriented to the [Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/)
- [ ] For [Design orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions#OrientationSessions-Design&researchorientation) sessions, either attend a live session (schedule via Calendly) or watch the latest recorded session
- [ ] For [Accessibiliy orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions#OrientationSessions-Accessibilityorientation) sessions, either attend a live session (schedule via Calendly) or watch the latest recorded session

#### Front-end Engineers
- [ ] Review [frontend developer documentation](https://depo-platform-documentation.scrollhelp.site/developer-docs/Frontend-developer-documentation.687931428.html) on Platform Website
- [ ] [Confirm that You Can Log In as a Test User](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/accessing-staging.md)
- [ ] For [Front-end orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions#OrientationSessions-Front-endorientation) sessions, either attend a live session (schedule via Calendly) or watch the latest recorded session
- [ ] For [Analytics orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions#OrientationSessions-Analyticsorientation) sessions, either attend a live session (schedule via Calendly) or watch the latest recorded session
- [ ] For [Accessibiliy orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions#OrientationSessions-Accessibilityorientation) sessions, either attend a live session (schedule via Calendly) or watch the latest recorded session
- [ ] For [QA orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions#OrientationSessions-QAorientation) sessions, either attend a live session (schedule via Calendly) or watch the latest recorded session
- [ ] For [Design System/Forms Library orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions#OrientationSessions-Designsystem/formslibraryorientation) sessions, either attend a live session (schedule via Calendly) or watch the latest recorded session

#### Back-end Engineers
- [x] Review [backend developer documentation](https://depo-platform-documentation.scrollhelp.site/developer-docs/Backend-developer-documentation.1886289964.html) on Platform Website
- [ ] [Confirm that You Can Log In as a Test User](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/accessing-staging.md)
- [x] For [Back-end orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions#OrientationSessions-Back-endorientation) sessions, either attend a live session (schedule via Calendly) or watch the latest recorded session
- [x] For [QA orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions#OrientationSessions-QAorientation) sessions, either attend a live session (schedule via Calendly) or watch the latest recorded session

#### Product Managers & Delivery Managers
- [ ] [Schedule a PM intro via Calendly](https://calendly.com/collaboration-cycle/product-manager-intro) with Shira Goodman (Platform Governance Team PM).
- [ ] If your team is new, please complete the [New VFS Team ticket](https://depo-platform-documentation.scrollhelp.site/getting-started/guidance-for-new-teams-and-team-members#Guidancefornewteamsandteammembers-NewVFSteams). If you're joining an existing team, you can skip this step.
- [ ]  For [Analytics orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions#OrientationSessions-Analyticsorientation) sessions, either attend a live session (schedule via Calendly) or watch the latest recorded session
- [ ] For [Accessibiliy orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions#OrientationSessions-Accessibilityorientation) sessions, either attend a live session (schedule via Calendly) or watch the latest recorded session
- [ ] For [QA orientation](https://depo-platform-documentation.scrollhelp.site/getting-started/calendly-orientation-sessions#OrientationSessions-QAorientation) sessions, either attend a live session (schedule via Calendly) or watch the latest recorded session

### Off-boarding of teammates
- [ ] Review [process for when a teammate leaves](https://depo-platform-documentation.scrollhelp.site/getting-started/offboarding)

## Platform Checklist
The items in this checklist are for Platform to complete. If you are ready to close the ticket and the Platform Checklist section has not been completed, please reach out to Platform via the guidance provided in [Getting help from Platform in Slack](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).
- [x] New VFS team member has been added to the VFS Team Roster located in [Atlas](https://www.va.gov/atlas/)
- [x] New VFS team member has been added to the vets.gov-write GitHub team

**Comment by bdech** [comment]
@drewconnelly Can you please provide your VFS Team in towards the top of this ticket?
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/135037265/44b39d84-f54d-405e-bfb9-af1c0d0296fd)

**Comment by drewconnelly** [comment]
@bdech Done, I was waiting on confirmation of the official VFS Team Name.

**Comment by bmatos312** [comment]
Platform Checklist Complete

**Comment by anita-halici** [comment]
@bmatos312 since the checklist is complete does Drew is going to be added to VA git as a next step? I am trying to add them as contributors to the zenhub board, but not seeing them in the lookup.

**Comment by bmatos312** [comment]
@anita-halici Hello Anita, we are currently waiting for Brittany to get the new team form submitted as well as her github access to the VA. Once we have that complete we can work on getting them more access, but until then we cannot move forward. I've sent emails to her with both links that need to be completed and submitted.

**Comment by anita-halici** [comment]
@bmatos312  gotcha! Thank you for clarifying these steps to me. Following up on that.

**Comment by anita-halici** [comment]
@bmatos312  is this the form you have requested? https://github.com/department-of-veterans-affairs/va.gov-team/issues/74060

**Comment by bmatos312** [comment]
@anita-halici Hello Anita, Yes it is! let me work on this and I'll update you once I've got some more news.

**Comment by anita-halici** [comment]
@bmatos312 thank you. I appreciate your help with that! What we need the most at the moment is for BrittanySFowler get her access as soon as possible, so she can start recording backlog items in the zenhub board.

**Comment by bmatos312** [comment]
@anita-halici Hello Anita, I've created the team and commented on the ticket. I've added write access to them and Drew, and Brad are populating. Brittany's access may take another day for her to populate in zenhub via git. Let me know if you need anything else from the platform side!

**Comment by anita-halici** [comment]
@bmatos312  thank you!

**Comment by anita-halici** [comment]
@bmatos312 I tried again today to add them to the zenhub board - but noot seeing them in the user lookup.

**Comment by bmatos312** [comment]
@anita-halici Hello Anita, I can see Drew and Brad within zenhub but not Brittany. Do you know if Brittany has authenticated zenhub with her github account?

**Comment by bmatos312** [comment]
@anita-halici Yes if she hasn't authenticated her github account to zenhub it wont populate correctly. But just to confirm you can only not see her correct?

**Comment by anita-halici** [comment]
@bmatos312 All three Brittany, Drew Connally, Michael Ramirez

**Comment by bmatos312** [comment]
@anita-halici Strange, I am able to see them in assignees for zenhub when I search. Does it not show up for you as such? Let me know if you can see the pictures or not as well.

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/142250984/611283f0-0878-400c-8c57-251f12788be5)

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/142250984/9c5a8e0d-0c48-4b5c-8b6a-dc06a4475b5c)

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/142250984/227d3f06-09b8-4c23-b777-5658ef01c82e)

**Comment by anita-halici** [comment]
@bmatos312 ok I see them showing in the assignee field. I think we should be good. Thank you

**Comment by drewconnelly** [comment]
Confirmed that I can access internal tools via SOCKS proxy.
