### ISSUE TITLE
Flipper UI access for Adam King

### ISSUE THREAD

**Issue by AdamKing0126** [department-of-veterans-affairs/va.gov-team#73581]
### Your Name

Adam King

### Your GitHub handle (Flipper UI access is managed through GitHub)

@adamking0126

### Team, Role, and Company of the target individual

VA IIR, Senior Software Developer, Oddball

### Please confirm if you are on Atlas, Platform Team Roster or are a Federal User

- [x] [Atlas](https://dev.va.gov/atlas)
- [X] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [X] Lesser Environments (Dev/Staging/Sandbox)
- [X] Production (if requesting, justify prod access below)

### Reason for Production Access (If requested)

I don't have access to see if I am on the Platform Team Roster.  I'm not sure how to request access to be able to view that link.  If that's the next step, I'm happy to follow it.

I'm a developer, I am concluding work on a ticket which uses a feature toggle ([link](https://github.com/department-of-veterans-affairs/vets-api/pull/15075)) and need to be able to turn it on/off.

**Comment by bdech** [comment]
Hi @AdamKing0126 , you have been granted access to `production` and `lower` environments.
