### ISSUE TITLE
[MVP] Remove temporary "confirmation" page asking veterans name, DOB, etc. from end of form flow

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#73598]
## Issue Description

- There is a placeholder page at the end of the form flow with the fields from the beginning of the form (name, ssn, etc.)
- Right now, it shows up **_after_** the "Faster claim processing" page and **_before_** the "Review" application page.
- This was added for cypress testing purposes while we were not finished completing the true final page of the form flow (which is the Review page).
- Now that the Review page has been completed in staging, we need to remove the placeholder page.

<img width="510" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0RDQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6d754c199f44ee734675fe683e7fc0d94cd5eda7/Screenshot%202024-01-12%20at%202.42.25%E2%80%AFPM.png" alt="Screenshot 2024-01-12 at 2.42.25 PM.png" />

---
## Tasks
- [x] Remove the placeholder/temporary page at the end of the form flow with the fields from the beginning of the form (name, ssn, etc.)

## Acceptance Criteria
- Pension form flow will no longer show the temporary page at the end of the form flow with the fields from the beginning of the form (name, ssn, etc.)

**Comment by TaiWilkin** [comment]
Handled in https://github.com/department-of-veterans-affairs/vets-website/pull/27465
