### ISSUE TITLE
Step 4 Household info/Prior marriage info: Add "Other" answer option to How did the marriage end?

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#73619]
## Issue Description

On Step 4 of Household information, under the [prior marriage information page](https://staging.va.gov/pension/application/527EZ/household/marriages/0), on the existing question for "How did the marriage end?"

- Add a third answer option for "Other"
- Add a required short text field if the user selects this option, similar to the existing question found under the [veteran's spouse's former marriage information page](https://staging.va.gov/pension/application/527EZ/household/marital-status/spouse-marriages).

## Existing question found in staging
<img width="316" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkRUQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c511e8c1f41ca161e593d9c01d5088b8128f0c58/Screenshot%202024-01-17%20at%209.29.11%E2%80%AFAM.png" alt="Screenshot 2024-01-17 at 9.29.11 AM.png" />

## Design
<img width="642" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXJUQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--46ef772a975627014251b7e2bed2bb816bef2e19/Screenshot%202024-01-17%20at%209.25.54%E2%80%AFAM.png" alt="Screenshot 2024-01-17 at 9.25.54 AM.png" />

---
## Tasks
- [x] FE tasks
- [x] BE tasks - _Map this answer option to the PDF questions 7B & 7G_

## Acceptance Criteria
- The question "How did the marriage end?" found under the veteran's prior marriage information page will have a third answer option added for "Other" with a required short text field if they select this option.

## PDF mapping info
Maps to 7B & 7G on [PDF form](https://www.vba.va.gov/pubs/forms/VBA-21P-527EZ-ARE.pdf):

<img width="335" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFBRQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f1c520d354e2594cd6022fb7e2315a2ee9a17d94/Screenshot%202024-01-16%20at%204.16.26%E2%80%AFPM.png" alt="Screenshot 2024-01-16 at 4.16.26 PM.png" />

**Comment by wayne-weibel** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/15228
https://github.com/department-of-veterans-affairs/vets-website/pull/27603
