### ISSUE TITLE
Create Pension form usability testing plan

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#73620]
## Issue Description
As a Pension team,
we need to understand how veterans experience the new online Pension form on VA.gov,
so we can understand where user experience challenges exist.

---
## Tasks
- [ ] Review the Platform website for research guidance: https://depo-platform-documentation.scrollhelp.site/research-design/research-at-va
- [ ] Create research plan to test the usability of the online Pension form on va.gov

## Acceptance Criteria
- We will have gathered information to inform and created a usability testing plan for the relaunched online Pension form on va.gov

**Comment by Allexelaw** [comment]
Working DRAFT spreadsheet to uncover usability testing observations/questions the team has per section of the form was developed.  https://docs.google.com/spreadsheets/d/1oi5TlNSUYMEDdK8_6O30sdkLDNbpaNDuN_-UJMwXrew/edit#gid=0   The goal is to make sure that we are capturing information the team needs during usability testing to improve the form.  DRAFT research plan to be shared with research team today and shared more widely by end of week.

**Comment by Allexelaw** [comment]
Drafted a schedule for the usability study for the pension benefits form: Timeline estimate
Wed 1/24 share draft usability study research plan and usability questions.  Meet with Buddhima, Vicky, Daniela, Michael Brown and Anh to walk through research plan on 1/26 and align on goals. 
Week of 1/29: Incorporate comments on usability study plan. Draft conversation guide and share w/research
Week of 2/5: Conversation guide approved, prepare materials for Github. Familiarize and line up Enjoy HQ.  Identify pilot participant to submit w/research materials.
Week of 2/12: 2/12 Artifacts for research review are submitted 9 days before planned research day - Perigean will begin to recruit 2/20. 
Wed 2/21/24 Pilot Test 
Usability testing begins the week of 2/26 thru week of 3/4/24

**Comment by Allexelaw** [comment]
[Usability test of pension benefits form 527EZ with Veterans: Research Plan (https://docs.google.com/document/d/12rW0wNIpDc6nG9CHUQxqN8w8YzqanLl4PBnxn2KXeRs/edit) completed.  Drafting the conversation guide and reviewing with research this week.

**Comment by Allexelaw** [comment]
Drafted research conversation guide which is under review and will be reviewed by Julie Strotham week of 2/5.  Set up Github research folder under [product/pension/research] https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/pension/research and uploaded research-plan.md

**Comment by Allexelaw** [comment]
Research conversation guide completed, reviewed by Julie Strotham, uploaded to Github and shared with Shane Strassberg and Kevin Hoffman for review.

**Comment by Allexelaw** [comment]
Product/Pension/Research folder has been set up with sub-folders for research. Participants for research pilot have been scheduled for Tues 2/20 and Wed 2/21.  Meeting held with Perigean 2/12 to review screening criteria.  Perigean will begin recruitment of Veterans for research as of today.  Observing research by Appoint a Representative Form team this week to bring back lessons learned to pension research.

**Comment by Allexelaw** [comment]
First pilot test with a Veteran on usability study held on 2/20, 2nd one scheduled for today.  All research sessions are now scheduled for week of 2/26 and 3/4.  Creating sign up sheet for observers.
