### ISSUE TITLE
Flipper UI access for [Liz Townsend]

### ISSUE THREAD

**Issue by liztownd** [department-of-veterans-affairs/va.gov-team#73632]
### Your Name

Liz Townsend

### Your GitHub handle (Flipper UI access is managed through GitHub)

@liztownd

### Team, Role, and Company of the target individual

Veteran Status Team, Staff Software Engineer, Ad Hoc LLC

### Please confirm if you are on Atlas, Platform Team Roster or are a Federal User

- [x] [Atlas](https://dev.va.gov/atlas)
- [X] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [X] Lesser Environments (Dev/Staging/Sandbox)
- [X] Production (if requesting, justify prod access below)

### Reason for Production Access (If requested)

Will need access to Production Feature Flippers in order to toggle on/off/for certain percentages of people our team's feature flag (`profile_show_proof_of_veteran_status`) for a phased release. Hoping to release at least to Staging by end of next week (not sure how long the request takes to process).

**Comment by bdech** [comment]
Confirmed in Atlas

E-QIP Transmittal [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/67413)

**Comment by bdech** [comment]
Hi @liztownd, You've been granted access to `production` and `lower` environments.
