### ISSUE TITLE
[Letters] Basic DataDog logging, dashboards, and monitors for Letters endpoints

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#73634]
## Value Proposition

As a developer, I want basic logging, dashboards, and monitors for the Letters app, to help me gauge and report on the health and usage of the Letters app, and respond to errors and anomalies stemming therefrom.

## Background

The goal of this ticket is to create basic dashboards and monitors in DataDog, for the Letters app, that we can later iterate on (in https://github.com/department-of-veterans-affairs/va.gov-team/issues/73637).

## Considerations

- The StatsD logs listed below are likely provided by DataDog, as rack metrics.
- Don't worry about fine-tuning the monitors listed below. We can do that in https://github.com/department-of-veterans-affairs/va.gov-team/issues/73637. For this ticket, err on the side of over-inclusivity. Better to have false positives but no false negatives, than to have the opposite.

### Eligible letters endpoint
- Find or create StatsD logs for:
  - [x] Successes on the EVSS endpoint.
  - [x] Errors on the EVSS endpoint.
  - [x] Successes on the Lighthouse endpoint.
  - [x] Errors on the Lighthouse endpoint.
- Create or update widgets for the [Letters dashboard](https://vagov.ddog-gov.com/dashboard/86n-b39-hhn/benefits---management-tools---letters?refresh_mode=sliding&view=spans&from_ts=1697311710000&to_ts=1705091310000&live=true) visualizing:
  - [x] Each of the above StatsD logs.
  - [x] HTTP status codes on the endpoint.
  - [x] Latency on the endpoint.
  - [x] Error logs stemming from the endpoint.
- Find, create, or update the following [monitors](https://vagov.ddog-gov.com/monitors/manage?q=letters&order=desc) in DataDog, each one posting to `benefits-management-tools-notifications` Slack channel:
  - [x] Anomalous traffic volume (based on the combination of successful requests to the EVSS and LH endpoints).
  - [x] Low traffic volume (using a lower threshold based on historical lows over the past several months).
  - [x] Anomalous latency on the EVSS endpoint.
  - [x] Anomalous latency on the LH endpoint.
  - [x] High error count (using an upper threshold based on historical acceptable baseline error counts).

### Download letter endpoint

- Find or create StatsD logs for:
  - [x] Successes on the EVSS endpoint.
  - [x] Errors on the EVSS endpoint.
  - [x] Successes on the Lighthouse endpoint.
  - [x] Errors on the Lighthouse endpoint.
  - [ ] Letter type, regardless of EVSS/LH.
- Create or update widgets for the [Letters dashboard](https://vagov.ddog-gov.com/dashboard/86n-b39-hhn/benefits---management-tools---letters?refresh_mode=sliding&view=spans&from_ts=1697311710000&to_ts=1705091310000&live=true) visualizing:
  - [x] Each of the above StatsD logs.
  - [x] HTTP status codes on the endpoint.
  - [x] Latency on the endpoint.
  - [x] Error logs stemming from the endpoint.
- Find, create, or update the following [monitors](https://vagov.ddog-gov.com/monitors/manage?q=letters&order=desc) in DataDog, each one posting to `benefits-management-tools-notifications` Slack channel:
  - [x] Anomalous traffic volume (based on the combination of successful requests to the EVSS and LH endpoints).
  - [x] Low traffic volume (using a lower threshold based on historical lows over the past several months).
  - [x] Anomalous latency on the EVSS endpoint.
  - [x] Anomalous latency on the LH endpoint.
  - [x] High error count (using an upper threshold based on historical acceptable baseline error counts).

### Beneficiary endpoint

- Find or create StatsD logs for:
  - [x] Successes on the EVSS endpoint.
  - [x] Errors on the EVSS endpoint.
  - [x] Successes on the Lighthouse endpoint.
  - [x] Errors on the Lighthouse endpoint.
- Create or update widgets for the [Letters dashboard](https://vagov.ddog-gov.com/dashboard/86n-b39-hhn/benefits---management-tools---letters?refresh_mode=sliding&view=spans&from_ts=1697311710000&to_ts=1705091310000&live=true) visualizing:
  - [x] Each of the above StatsD logs.
  - [x] HTTP status codes on the endpoint.
  - [x] Latency on the endpoint.
  - [x] Error logs stemming from the endpoint.
- Find, create, or update the following [monitors](https://vagov.ddog-gov.com/monitors/manage?q=letters&order=desc) in DataDog, each one posting to `benefits-management-tools-notifications` Slack channel:
  - [x] Anomalous traffic volume (based on the combination of successful requests to the EVSS and LH endpoints).
  - [x] Low traffic volume (using a lower threshold based on historical lows over the past several months).
  - [x] Anomalous latency on the EVSS endpoint.
  - [x] Anomalous latency on the LH endpoint.
  - [x] High error count (using an upper threshold based on historical acceptable baseline error counts).

## Acceptance Criteria
- [x] Each of the widgets and monitors described above exist.
- [x] A link to the dashboard, and links to each monitor have been added to https://docs.google.com/document/d/1OoX2aF5JMJLa0KVQqOiatiZy5YIfhJgL2zdGesYxbbE/edit. 

## Definition of Ready
N/A.

## Definition of Done
- [x] Acceptance criteria met.

**Comment by samcoforma** [comment]
@samcoforma @data-doge note: we're going to move "Letter type, regardless of EVSS/LH" under #download into its own ticket.

**Comment by samcoforma** [comment]
@jerekshoe @pmclaren19 @jacobworrell @data-doge 

I've officially moved this ticket into Validate: [BMT Letters Monitoring Dashboar](https://vagov.ddog-gov.com/dashboard/86n-b39-hhn/benefits---management-tools---letters)

**Comment by HeatherWidmont** [comment]
@jacobworrell & @jerekshoe to validate in the parking lot next week

**Comment by HeatherWidmont** [comment]
@jacobworrell & @jerekshoe to validate today
