### ISSUE TITLE
CF: Final Staging Review - Content MVP, Internal

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#7365]
Review all UI & Content updates on Staging
Report issues to Dev team

**Comment by amyknox** [comment]
The merge doesn't appear to have happened.  Waiting on 

https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/7743

PR - https://github.com/department-of-veterans-affairs/vets-website/pull/12164
