### ISSUE TITLE
S45 [Snowmaggedon 🏂]

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#73651]
## Sprint Goals

Planning
- Prioritize quarterly focus areas for Decision Reviews
- Kickoff solution activities for NOD and SC upstream failures

Delivery
- Kickoff E2E testing for NOD v2 release
- Setup callbacks for tracking emails that return a hard bounce
- Complete remediation for: #70237

---

## Team Capacity
- Velocity average (past three sprints): 10
- Target velocity: 17

**PTO:**
- Rocio (1/18 - 1/19)
- Eileen (1/19)
- Robin (half day 1/19)

**Outages for awareness:** 
- DK (1/18 - 1/23)
- Heather (1/25 - 1/26)

## Sprint Risks and Assumptions
- Aiming to have NOD V2 released by or before 2/13

## Reference documentation

- [High-level Roadmap](https://docs.google.com/presentation/d/18rYnaYCjp2L2cm8HdYmXsg1_Pz7KI_X0vNRkmT5AqEk/edit#slide=id.g2804f61cf5f_0_0)
- [Tactical Roadmap (WIP)](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1702419283589/39d0d78778b8a35a2a02b48496d665d86ec3c5a2?sender=ud80be02ce240061eb0f35352)
- [Planning and Prioritization Board](https://github.com/orgs/department-of-veterans-affairs/projects/1026/views/1?filterQuery=)
- [Defect Board](https://github.com/orgs/department-of-veterans-affairs/projects/876/views/1?visibleFields=%5B%22Title%22%2C%22Assignees%22%2C46447480%2C46447511%2C46447563%2C%22Labels%22%5D)
- [Story Estimator](https://docs.google.com/spreadsheets/d/1ae9fpz_ThZycIWjmBBMSEuGRGqsvRSz3/edit#gid=1440877167)
- [Velocity Planner ](https://docs.google.com/spreadsheets/d/1i7pVgf2XQxuRkIbuhHC5dckx2RlZt87n/edit#gid=880321098)

**Comment by saderagsdale** [comment]
@HeatherWidmont Howdy - new sprint ready for velocity planning and PTO details.

**Comment by HeatherWidmont** [comment]
PTO outages have been added. I'll update the average & target velocity before planning tomorrow. I'm currently waiting on: 

- Eugene's estimated velocity to finalize the target velocity
- Tickets that may close after validation in the parking lot tomorrow to update average velocity

**Comment by HeatherWidmont** [comment]
**Update:** Tickets were validated & one closed in the parking lot. Average velocity has been calculated & added above. Still waiting on @data-doge's capacity to finalize the target velocity, but I'll check in with them after sprint review 😄

**Comment by HeatherWidmont** [comment]
Everything is updated!
