### ISSUE TITLE
FE | Profile | Maintenance | Save success alert has stray characters

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#73654]
## Background
I noticed that the save success alert in profile says `'Update saved.'` instead of `Update saved.`. The `'` characters should be removed from either side of the text.  I saw this on staging and prod, in a couple sections (which makes sense as I'm sure this is a shared component)

<img width="701" alt="Screenshot 2024-01-16 at 7 30 42 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/55992116/247c8f63-2e3c-4857-9abf-64e414b6dc69">

## Tasks

- [ ] Remove the `'` where needed

## AC

- [ ] We don't have stray characters in the success alert

**Comment by adamwhitlock1** [comment]
I just noticed this too. Very strange as that hasn't changed in a long time. I wonder if something with the design system component has been updated... I'll take a look.

**Comment by adamwhitlock1** [comment]
This was fixed during this PR https://github.com/department-of-veterans-affairs/vets-website/pull/27672

So I will close it now.

<img width="579" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0F5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4e7586bb9cb88e98dc8e8e7a867a131150766ce4/Screenshot%202024-02-06%20at%208.43.43%E2%80%AFAM.png" alt="Screenshot 2024-02-06 at 8.43.43 AM.png" />
