### ISSUE TITLE
Copyedit and publish updates to 3 R&S pages and 1 CLP

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#73664]
Danielle wrote updates to 3 R&S pages related to sign-in and identity, and 1 related CLP. These all related to the modern secure account transition work. These include reusable Q&As on live pages, so we'll need to review in the single Q&A nodes, as well as reviewing updates to the FAQ pages. We're waiting on final green light to publish, but can do all other steps now.

Approved content doc: https://dvagov.sharepoint.com/:w:/s/oitocto1/ESn7aYkJvJRKgeKi7Bec6PcBOSIV75uB1D-ALQ76uQyOug?e=CmgJKT

For each of these pages and updated single Q&As, we need to compare content to the approved doc, copyedit, and prepub. Don't publish yet. 

- Creating an account: http://preview-prod.vfs.va.gov/preview?nodeId=51915
- Signing in: http://preview-prod.vfs.va.gov/preview?nodeId=8222
- Verifying your identity: http://preview-prod.vfs.va.gov/preview?nodeId=8233
- Prepare for sign-in changes CLP: http://preview-prod.vfs.va.gov/preview?nodeId=63686

(The reusable Q&A feature in CLPs isn't working yet, so please proof those separately against the approved content.)

**Comment by laurwill** [comment]
Hi @megzehn , these content updates are ready for you! Please do all steps before publishing, but don't publish yet. The content in the Sharepoint doc has been through many levels of approval, so we don't want to suggest additional changes, just compare the pages to the doc for errors and omissions. (If you have style changes you want to suggest, we can track those for Danielle separately, to consider after these are live.)

And we may decide to publish some updates to single Q&As today that don't mention the upcoming sign-in changes, but I'll confirm that separately. 

Thank you so much, and let me know if you have any questions! 

cc @DanielleThierryUSDSVA

**Comment by laurwill** [comment]
Hi @megzehn , here's a list of Q&A nodes we can publish (and a list of those we should not publish until we get final approval). We'll also wait to publish the 3 R&S pages that contain the Q&As, and the CLP. 

Updated Q&As we can publish:
- Why should I create an account?
- What type of account should I create?
- How do I create a [Login.gov](http://login.gov/) account?
- How do I create an [ID.me](http://id.me/) account?
- How can I get help creating an account?
- How do I verify my identity online?
- How do I verify if i live outside the US?
- Can I use [Login.gov](http://login.gov/) without a US phone number?
- I don’t have a smartphone. How do I verify through [ID.me](http://id.me/)?
- What’s MFA and why does VA use it?
- How can I get more support from [Login.gov](http://login.gov/) or [ID.me](http://id.me/)?

We can publish these new Q&As as standalone nodes for now:
- What does it mean to verify and why do I have to do it?
- How does MFA differ from verification?
- Can I verify in person for [Login.gov](http://login.gov/)?
- Can I call VA to reset my [Login.gov](http://login.gov/) or [ID.me](http://id.me/) password?

Do not publish these Q&A nodes, wait for final approval:
- What’s changing for VA sign-in accounts?
- How do I sign in to [VA.gov](http://va.gov/)? (has a note about changes)
- Will I have to get MFA by 2024?
- Why will VA allow only 2 sign-in options?
- What if I don’t get a modern, secure account?
- What if I don’t want a [Login.gov](http://login.gov/) or [ID.me](http://id.me/) account?
- Can I still use DS Logon or MHV to sign in?
- Will this change affect DS Logon for DOD websites?

**Comment by megzehn** [comment]
I'll check these off as they get published!

- [ ] Why should I create an account?
- [ ] What type of account should I create?
- [ ] How do I create a [Login.gov](http://login.gov/) account?
- [ ] How do I create an [ID.me](http://id.me/) account?
- [ ] How can I get help creating an account?
- [ ] How do I verify my identity online?
- [ ] How do I verify if i live outside the US?
- [ ] Can I use [Login.gov](http://login.gov/) without a US phone number?
- [ ] I don’t have a smartphone. How do I verify through [ID.me](http://id.me/)?
- [ ] What’s MFA and why does VA use it?
- [ ] How can I get more support from [Login.gov](http://login.gov/) or [ID.me](http://id.me/)?

**Comment by laurwill** [comment]
Hi @megzehn , thanks for flagging the 2 Q&As on the signing in page that weren't included in the content doc. Danielle confirmed that we can update to match current style and terminology, copyedit and publish those changes. Here are the nodes, ready for you to publish whenever you have time to review:
- https://prod.cms.va.gov/node/8209
- https://prod.cms.va.gov/node/8211

**Comment by megzehn** [comment]
Great, thanks @laurwill! I reviewed and published those 2 nodes.

**Comment by laurwill** [comment]
That's right, Danielle will let us know when we can publish.

**Comment by laurwill** [comment]
We did this long ago! Closing :)
