### ISSUE TITLE
How might we solve the problem of a Veteran checking in before they get to the waiting room & being called back while they are not there

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#73667]

**Comment by loripusey** [comment]
@benbrasso-agile6 Kay wants us to go back to the drawing board on this one; @cgednalske was at the priorities meeting and has the info; here is a placeholder ticket for UX

**Comment by benbrasso-agile6** [comment]
Caught up briefly with @cgednalske. We'll fill this ticket out in the next few days.

**Comment by benbrasso-agile6** [comment]
Created a few tickets to replace this ticket. Going to chat it through more with @cgednalske tomorrow to make sure we're aligned on the approach, which we'll run by Lori, Kristen and Kay. 

https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/74008
https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/74010
https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/73965
