### ISSUE TITLE
Analytics Internal - New Landing Page Needed in DOMO for Benefits Dependent Experience in VA.gov Notify KPIs

### ISSUE THREAD

**Issue by GitSamJennings** [department-of-veterans-affairs/va.gov-team#73675]
# Request a New Dataset

## What this form is for

We are needing a new landing page in DOMO under VA.gov Notify KPIs for Benefits Dependent Experience and the url is https://www.va.gov/view-change-dependents/

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/132367046/09eeaf54-3499-44fc-a976-7eee02f4445d)

For more information about this process, please see the [How to request a new dataset](https://vfs.atlassian.net/wiki/spaces/AT/pages/2215576075/How+to+request+a+new+dataset) page under "QA Processes" in Confluence.

## Instructions for Analytics team member

- [ ] Make a copy of the [Dataset Request Form](https://docs.google.com/spreadsheets/d/1o1l80Y-6asoUP43eZGbOEV3FyTlTSpBsNRIqFiKIjT0/edit?usp=sharing)
- [ ] Complete request form as instructed
- [ ] Link your completed spreadsheet here: ______

**Comment by Blivaditis** [comment]
Hello, I took a look at the request and noticed there is already a landing page for adding/removing dependents which is tied to the page path www.va.gov/view-change-dependents/add-remove... There is no option to add https://www.va.gov/view-change-dependents/ as the landing path as there is no data connected to it in DOMO. How would you like me to proceed?

**Comment by GitSamJennings** [comment]
Can both urls will be tracked and aggregated on the landing page section of the VA Notify KPI dashboard, since they go to the same page, even though the urls are different even after a page load?

**Comment by Blivaditis** [comment]
The page path you linked to this ticket is a filterable option in Domo, I have five options of page paths to chose from.
<img width="552" alt="Screenshot 2024-01-24 at 10 02 46 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/151066815/8c4d5a1f-b7ed-4db3-9735-966c74a80495">
<img width="552" alt="Screenshot 2024-01-24 at 10 02 52 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/151066815/a06e4c6d-1105-44a8-a675-5600cd9212dd">

**Comment by Blivaditis** [comment]
I can add those additional pages to the landing page and group them into the add or remove defendants if that would help.

**Comment by johnny-jesensky-adhoc** [comment]
Hi @GitSamJennings, just wanted to follow-up on this card. Is what @Blivaditis suggested above an acceptable option here? Looks like there five paths we could add and group.

Please let us know. Thanks!

**Comment by GitSamJennings** [comment]
Yes, I think that would work. Thanks!

**Comment by johnny-jesensky-adhoc** [comment]
Hi @GitSamJennings, following up on this, we were able to add the following paths.

- ...686c/introduction/
- ...686c/introduction?next=/my-va/
- ...686c/introduction?next=loginmodal
- ...686c/introduction?postlogin=true

We were encountering a bug when trying to add the fifth.

...686c/introduction?next=loginmodal&postlogin=true

We may look to reach out to Domo, and try to get that one added once we have a better understanding of what is happening.

Let us know if there are any questions on this!

FYI @Blivaditis 

<img width="1894" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODRSQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--63d542fdf195e723e397b9f072917e431256bbc2/image.png" alt="image.png" />
