### ISSUE TITLE
Sidekiq Admin UI access for Jerek Shoemaker

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#73672]
### Your Name

Jerek Shoemaker

### Your GitHub handle (Sidekiq Admin UI access is managed through GitHub)

jerekshoe

### Your dsvagovcloud AWS user name (if applicable)

Jerek.Shoemaker

### Team, Role, and Company of the target individual

Benefits Management Tools, Software Engineer, Ad Hoc LLC.

### COR Name

Other - please specify in 'Additional Notes'

### Please confirm if you are listed as a team member in Atlas or the Platform Team Roster

- [X] [Team member in Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [X] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Sidekiq UI Access requested for the following environments

- [ ] dev
- [ ] staging
- [ ] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### If PRODUCTION ACCESS is required, confirm/complete ONE of the following

- [ ] I have an AWS Username and it is listed in [here](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf)
- [X] I currently have access to vets-api Production Terminal via ArgoCD
- [ ] I've attached a screenshot of my E-QIP Transmittal Notice E-mail (Drag or Copy/Paste in Additional Notes Section below)

### Additional Notes

COR - Keith Riley
Reason for access - I need to be able to view information on production Sidekiq Jobs that make it into the dead queue for debugging purposes

**Comment by bdech** [comment]
Access to `prod` is pending approval by OCTODE, and we'll update you as soon as it's available.

**Comment by jerekshoe** [comment]
Is there an estimate on how much longer it will take to get a decision on this? I'd like to be able to set expectations with my team

**Comment by bdech** [comment]
Hey @jerekshoe, OCTO normally checks pending access requests on a weekly basis. This may have been accidentally missed last week, I'm not entirely sure. I will include @JonathanKamensDVA here in the thread for awareness.

**Comment by JonathanKamensDVA** [comment]
Approved. Sorry for the delay.

**Comment by bdech** [comment]
@jerekshoe You've been granted access to Production, 
with access to Production limited to 6 months, expiring 07/22/24.

Please set a reminder for yourself to return to this Issue and 
request an extension within 1 week of the expiration date. You'll 
receive 1 reminder with a 72 hour window to respond. Failure to 
respond will result in your access being revoked and will require 
you to fill out a new request.

**Comment by bdech** [comment]
support slack [reminder](https://dsva.slack.com/archives/C06CY71PCAX/p1705961306658649)

**Comment by bdech** [comment]
@jerekshoe Your Sidekiq Admin UI Production access has expired.

Would you like to request an extension? You have 72 hours to respond, or your 
access will be revoked and you will need to fill out a new request.

**Comment by jerekshoe** [comment]
Yes, I would like an extension. Thanks!

**Comment by bdech** [comment]
@LindseySaari @ericboehs can one of you please give us a :thumbsup: to extend their access?

**Comment by bdech** [comment]
@jerekshoe your Production access has been extended for 6 months,
expiring 01/23/25.

Please set a reminder for yourself to return to this Issue and 
request an extension within 1 week of the expiration date. You'll 
receive 1 reminder with a 48 hour window to respond. Failure to 
respond will result in your access being revoked and will require 
you to fill out a new request.

**Comment by bdech** [comment]
support slack reminder [here](https://dsva.slack.com/archives/C06CY71PCAX/p1721757164959219)

**Comment by AnthonyWFlowers** [comment]
@jerekshoe  Your Sidekiq UI Production access has expired.

Would you like to request an extension? You have 72 hours to respond, or your access will be revoked and you will need to fill out a new request.

**Comment by jerekshoe** [comment]
Yes I would like to request an extension. Thanks!

**Comment by AnthonyWFlowers** [comment]
Slack reminder [here](https://dsva.slack.com/archives/C06CY71PCAX/p1738170739167949)

**Comment by AnthonyWFlowers** [comment]
@jerekshoe Your Sidekiq UI Production access has expired.

Would you like to request an extension? You have 72 hours to respond, or your access will be revoked and you will need to fill out a new request.
