### ISSUE TITLE
CF: Post-MVP Content Mapping Updates

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#7368]
Align content per EDU new inputs on Accreditation & HCM caution flags

**Comment by amyknox** [comment]
• BAH to draft plain-language version of the proposed text: 
Caution Flag Other- The Department of Veterans Affairs (VA) has concluded there is sufficient evidence to support a finding that the school has utilized advertising, sales, or enrollment practices which are erroneous, deceptive, or misleading either by actual statement, omission, or intimation in violation of 38 U.S.C. § 3696. Therefore, VA has taken action.

**Comment by amyknox** [comment]
**This school has a cautionary warning**

VA has taken action against this school

VA found enough evidence to conclude that this school has engaged in misleading, deceptive, or erroneous advertising, sales, or enrollment practices.
