### ISSUE TITLE
Toxic Exposure: Add "I'm not sure" to gulf war locations pages

### ISSUE THREAD

**Issue by christinec-fftc** [department-of-veterans-affairs/va.gov-team#73694]
## Issue Description
1. Add the "I'm not sure..." checkbox to the `gulf-war-1990` page and `gulf-war-2001`
- If "I'm not sure" and one or more locations is selected, nothing to do (it's as if not sure was not selected)
- Do not show a details page for "I'm not sure". 
- fyi, "I'm not sure" will be later ignored during back end submission
2. Add the "I'm not sure" checkbox to each of the details pages that display as a [view only field](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-how-to-include-view-only-data)
- same as above, will be ignored during back end processing

3. Add to summary page
- If a location does not have dates and has only "I'm not sure..." checkbox selected, display "I'm not sure of the dates"

In Scope:
- Gulf War 1990 pages
- Post 9/11 (Post 2001)

<img width="650" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTNQQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f455438c898290937893682d66ead77f054df503/image.png" alt="image.png" />

<img width="219" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL01CQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3595b22e1fb1f806aceae508d5e2ee5fb8dbb831/image.png" alt="image.png" />

## Front end tasks
- Ensure the page is styled according to design spec. 
- ~Ensure the back end data from API is displayed in local and review instance~
- Ensure unit tests are available. 
- Ensure your code changes are covered by E2E tests
- Run axe checks using the Chrome or Firefox browser plugin
- Test for color contrast and color blindness issues
- Zoom layouts to 400% at 1280px width
- Test with 1 or 2 screen readers
- Navigate using the keyboard only

## Acceptance Criteria
- [ ] Designer comments on this issue to approve page styling 
- [ ] Unit tests pass
- [ ] E2E tests cover current code and regression
- [ ] End-to-end tests show 0 violations.
- [ ] ~The data returned matches API response (for given user or scenario)~
- [x] All axe checks pass
- [ ] All color contrast checks pass
- [x] All zoom testing passes
- [x] All keyboard checks pass 
- [x] All screenreader checks pass

## Appendix
<details> 

 <summary>Ensure your code changes are covered by E2E tests (expand)</summary>
 
 - Add E2E tests if none exist for this addition/change. 
 
 - Update existing E2E tests if this code will change functionality. 
 
 - Include axe checks, including hidden content
 
</details>

<details> 

 <summary> Run axe checks using the Chrome or Firefox browser plugin (expand)</summary>
 
- Ensure no heading levels are skipped.

- Ensure all buttons and labeled inputs use semantic HTML elements.

- Ensure all buttons, labeled elements and images are identified using HTML semantic markers or ARIA roles.

- Ensure form fields have clearly defined boundaries or outlines.

- Ensure form fields do not use placeholder text. 

- Ensure form fields have highly visible and specific error states. 

</details>

<details> 

 <summary> Test for color contrast and color blindness issues (expand) </summary>
 - All text has appropriate contrast. 

</details>

<details> 

 <summary> Zoom layouts to 400% at 1280px width (expand)</summary> 
 - Ensure readability and usability are supported when zoomed up to 400% at 1280px browser width
 - Ensure no content gets focused offscreen or is hidden from view.
 
</details>

<details> 

 <summary> Test with 1 or 2 screen readers (expand)</summary> 
 
 - Ensure the page includes a skip navigation link. 
 
 - Ensure all links are properly descriptive. 
 
 - Ensure screen reader users can hear the text equivalent for each image conveying information. 

 - Ensure screen reader users can hear the text equivalent for each image button. 

 - Ensure screen reader users can hear labels and instructions for inputs. 
 
 - Ensure purely decorative images are not announced by the screenreader. 
 
</details>

<details> 

 <summary>Navigate using the keyboard only (expand)</summary> 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be reached with the tab key in a logical order. 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure all interactive elements can be reached with the tab key in a logical order 
 
 - Ensure all interactive elements can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure focus is always visible and appears in logical order.
 
 - Ensure each interactive element has visible focus state which appears in logical order.
 

</details>

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by michael-wojcik** [comment]
Grabbing this ticket to work on today

**Comment by michael-wojcik** [comment]
@christinec-fftc Question about the current issue description: Should the field in Step 1 also be a view-only field, as specified for the field in Step 2?

**Comment by christinec-fftc** [comment]
I'm not sure if you can set a view only field within a checkbox group using a web component pattern as I haven't done that before. Perhaps something you can do discovery on if trying to go that route.

**Comment by michael-wojcik** [comment]
Understood 👍 I'll do that discovery to see if it's possible to do that within a checkbox group. If not, we'll just have to make a note for the back-end team to ensure that the data ignored.

**Comment by michael-wojcik** [comment]
SITREP: Working on the new #3 additional requirement. Should have PR ready for review by EOD today

**Comment by michael-wojcik** [comment]
Draft PR: https://github.com/department-of-veterans-affairs/vets-website/pull/29975

Todo:
- Resolve merge conflicts
- Finish adding unit testing

**Comment by michael-wojcik** [comment]
Pushed another commit to correct the "I'm not sure" string on the location details pages

**Comment by michael-wojcik** [comment]
Yesterday, I updated the PR (https://github.com/department-of-veterans-affairs/vets-website/pull/29975) and it is ready to be merged. The only outstanding question is the one posted by @christinec-fftc that still needs feedback from @mengA6 and @Kate-allbee but perhaps can wait for a subsequent PR?

**Comment by michael-wojcik** [comment]
Additional scope added to ticket based on review yesterday (See https://github.com/department-of-veterans-affairs/vets-website/pull/29975#issuecomment-2137750547). Working to revise existing PR accordingly.
