### ISSUE TITLE
SOCKS access for Jane Xiong (SSH Key update)

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-team#73695]
### Your Name

Jane Xiong

### Your Email

jane@cityfriends.tech

### Your Role and Team

Product Manager, Sitewide Facilities

### Product Manager (PM) name and email

Jane Xiong, jane@cityfriends.tech

### Product Owner (PO) name and email

Michelle Middaugh, suzanne.middaugh@va.gov

### Access Type Requesting

viewers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDFyJ7y5Od9tWO0MzzbUKtpq/9lnxkrCNXgClqiBMyJvjTdWew0X3ncbgUB/XyztSy4+h1SFaKTk7CNVS2C+zpEeKtUqbQWPQKo9kH8OajNXvxnOeWdtYeJbx+KpubPJ4Tg2OnVdgPEpdzc8xBXgO1RQbOE8hfRGpGsEfW8kuo1T0mDH23dba60Y3P+0LirIif56U+/aw1cxWtMO6ZZWuBpAccG0zBOrx7isyhz8/nEGxD8ELD4nIcqGKPDPL3aL5aC97vaVOZAJIBchX6KQbVO7ZBwf1GfBjn7rMdYet3LFQ6B4nuwVm4YPvMLelZtSe/xEMnHKRiviib/LgEBbx4VSK7CPM9dfIwUsaxw0O04y1i95YOlbDBM8GLcy2OhoO2h555EIPoMNd5U8C3Wud4HHreTYk+XoexUWW4+UHkZI33vvU2PtLJUWdneklYnXWjZpYSNNuCE2Cz0jK0KPqokORLeSJJk9lxT0kTfSj+9WUV5H/BKi6HQaSMbk+QDzR8= janecityfriends@Janes-MBP.hsd1.mn.comcast.net

### E-QIP Transmittal Confirmation

<img width="1034" alt="transmittal" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/73648238/df2b662c-b9f6-4470-bd4c-f4514472a336">

### User must exist in a roster before SOCKS access can be granted

- [x] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by xiongjaneg** [comment]
There's this email too when I went to go get
<img width="1473" alt="Screenshot 2024-01-16 at 1 03 22 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/73648238/e2aa59b9-dab0-40e4-b4d8-4b51877204aa">
 my PIV card

**Comment by patrick-black-oddball** [comment]
thanks @xiongjaneg - your updated cert is all set
