### ISSUE TITLE
Engineering norms first draft

### ISSUE THREAD

**Issue by nihil2501** [department-of-veterans-affairs/va.gov-team#73705]
### Description
Finalize our engineering norms [first draft](https://docs.google.com/document/d/11Rc60zqzbDLQzHx0XVPIMt1EHJvtW4JVhfMnkO27l7g/edit) and include a specification around ADRs (likely just linking out to some external specification, ideas [here](https://dsva.slack.com/archives/C06ABHUNBRS/p1705012543777169?thread_ts=1705008375.749989&cid=C06ABHUNBRS)). Then we can place this in an engineering section of our team folder ([ticket to create that is here](https://app.zenhub.com/workspaces/accredited-representative-facing-team-65453a97a9cc36069a2ad1d6/issues/gh/department-of-veterans-affairs/va.gov-team/73702)).

### Acceptance Criteria
- [x] The engineering norms document exists in team Github folder
- [x] Schedule follow up norms meeting
- [x] Finished document is agreed upon by engineers

**Comment by RivkaCGates** [comment]
Question, one of the AC is that the doc exists in the team github folder. I didn't see it there. Did I miss it? Can we link it please? The link above goes to a gdoc. @gabezurita
