### ISSUE TITLE
GA4 - Authenticated Experience - Profile / My VA Custom events

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/va.gov-team#73743]
# Google Analytics Implementation Request

### Please provide the following details for this request

- **Team Name**

    - Authenticated Experience

- **Product Name**

    - Profile / My VA
      
- **When is the launch date?**
    - Already launched, but going over custom events:
    - See this ticket with the initial list that was created of custom events: https://github.com/department-of-veterans-affairs/va.gov-team/issues/72277

- **Provide the link(s) for Product/Page urls**
  
    - /profile /my-va

- **What Events need to be tracked?** 
  - We have evaluated all the existing custom events on the personalization application folders, and have compiled a list here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/engineering-docs/GA_Events_Inventory.md
  - I was told to create a ticket so that these events could be reviewed for the GA4 migration and if I update any of the events with any default/component built in events, I will also update the doc to reflect those changes.

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by michelle-dooley** [comment]
Thank you @adamwhitlock1 - we will review and get back to you with questions as we work through the GA4 migration.
