### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by kfink24** [department-of-veterans-affairs/va.gov-team#73768]
### Name

Laura Willwerth

### Email

laura.willwerth@va.gov

### Role

Managing Editor

### Team

Sitewide CAIA

### Product Manager (PM) name

Kaitlin Fink

### Additional Notes

I'd like to request we give Laura "editor" access as an experiment on working with content in Figma.  The MHV portal team has a lot of content needs and complexity across various teams.  Laura is the only content support across all of the teams and managing all those needs individually.  To streamline the process and save time for content, designers and developers we'd like to pilot editor access for her and see if it is worth it.

**Comment by naomimarcussen** [comment]
I've sent an invite to laura.willwerth@va.gov. Let me know once an account is created and I can bump her up to 'Full' (Figma now calls Editor seats Full seats). I'm happy to test out a new workflow. I'd love to check-in on this again in a few months to see how its working. :)

**Comment by kfink24** [comment]
Thank you @naomimarcussen !  Laura has created an account and ready to be bumped up to Full.  We will keep you updated on the workflow and if it is working well with content over the next few months!

**Comment by naomimarcussen** [comment]
Great! I see a few accounts for Laura. Does she prefer to log in with your company email or va.gov? It looks like she created an account with her company. Just want to clarify before I bump her up.

**Comment by naomimarcussen** [comment]
Great! I just gave her full access on her company email. I'd love to hear how the collaboration with teams goes.

I see she also has a gmail account that I'm going to have to remove for security reasons.
