### ISSUE TITLE
Adding Alexis Summers to DSVA Slack

### ISSUE THREAD

**Issue by huggins-va** [department-of-veterans-affairs/va.gov-team#73764]
# Description

Please add:
Alexis Summers 
summers_alexis@bah.com as Multi-channel user to the following channels:
api-facilities
team-marmoset
vaapi-alerts
vfs-platform-support
api-benefits-claims

Alexis is a new member on Team Marmoset on Lighthouse

Thank you! 

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add [_insert email_] as a single-channel guest to [_channel name_].
- Please add [_insert email_] as a multi-channel guest to these channels: [_channel names_].
- Please add [_insert email_] as a full member.
- Please change the status of [_slack username_] from [_current status_] to [_desired status_]

**Comment by LEHigley** [comment]
couldn't add to 
team-marmoset
api-benefits-claims
