### ISSUE TITLE
Content updates to Pension "how to apply" page

### ISSUE THREAD

**Issue by strelichl** [department-of-veterans-affairs/va.gov-team#73774]
## Issue Description

This page will need updates for the form reactivation.

Child ticket for #73034 but not linking for some reason!

---
## Tasks
- [x] Assess page changes
- [x] Update page
- [x] Stakeholder review
- [x] Copyedit
- [x] Publish

## Acceptance Criteria
- [x] Updated page is live
---

**Comment by katherine-fung** [comment]
When the pension form launches to 100% of users, I'll copy the content from the widget into Drupal, and remove the widget. 

I'll pass to Chelsea to copy edit and publish.

**Comment by katherine-fung** [comment]
I'll make these changes on Monday, 3/4 and pass them to Megan to copy edit.
