### ISSUE TITLE
Analogous digital exp research

### ISSUE THREAD

**Issue by karafaithsanchez** [department-of-veterans-affairs/va.gov-team#73770]
**Problem**:

How might we create a unique look and feel for our portal, especially since there are reps who will be using it who are also Veterans using va.gov. We've heard from many sources that if a rep wants it to be clear when they're working on their stuff vs another claimant's stuff. 

**Plan**:

This problem is not a new one. We know there are other B2B2C companies out there, including many outside of government, who have tackled similar challenges who we can draw inspiration from.
**Jina Ryu** (a VA fellow) is going to build out a research deck that documents 4-6 examples of digital experiences, highlighting how they distinguish the look and feel for both sets of users, if there are other UI/UX characteristics/attributes that help orient a user to what side of the experience they're in, and note anything else about the UX that maybe helps facilitate that collaboration, and helps a service provider understand the needs of their customer and provide them with the resources they need.
**Kara Sanchez** to oversee work is completed, providing guidance and fielding any questions along the way. This ticket should be sized for this part of the work.

**Output:**

Powerpoint deck (or similar) that documents 4-6 examples documenting details listed above.

**Acceptance Criteria:**

- Deck has been made and reviewed.
- Information is written/visualized in a way that is digestible and actionable so the designers can implement any aspects they see fit.

**Comment by karafaithsanchez** [comment]
@RivkaCGates sorry meant to tag you on this yesterday! please take a look - hoping to bring this into the upcoming sprint

**Comment by RivkaCGates** [comment]
Please link the deck @karafaithsanchez

**Comment by karafaithsanchez** [comment]
@RivkaCGates [here's the Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1706055266627/39f5acc50845504824cdd96abc676f4acb98184d?sender=ucd326fb05b27d09e40350092) where Jina populated all of her research
