### ISSUE TITLE
10-7959f-1 Design | User Flow

### ISSUE THREAD

**Issue by brian-wilke** [department-of-veterans-affairs/va.gov-team#73799]
To better understand what will be needed for the digitization of the registration from for the Foreign Medical Program

Create visual representation  of user flow for 10-7959-f-1

**Deliverable:**

Mural (or other whiteboard) of the current experience and how that would translate into a digitized experience.

**Assumptions:**
This program may or may not be able to participate PEGA depending on timing. So a print-ready version is also a possible outcome.

This program is only for veterans

**Unknown:**
Dependencies on eligibility
When an applicant might become aware of this program (do they have information available to them)

**Comment by marywang2** [comment]
The FMP forms (1 and 2) and any attachments/documents will go into PEGA (but I believe PEGA will not be ready for 2 until early March).

**Comment by marywang2** [comment]
[mural] (https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1705521134491/52690602ad9bb3ef8f9cbc82d48bd9698e63e83f?sender=u5b5b283ad7d33e12ab259320) in progress.

**Comment by brian-wilke** [comment]
This is the link to share with the Design Intent ticket.
https://www.figma.com/file/PzB1F5TYuBK5KQgPbuhAwH/10-7959f-1?type=design&node-id=1-18&mode=design
(this is specific to User Flow)

Moving this ticket to review
