### ISSUE TITLE
Maintenance Mode Enhancements for Revproxy

### ISSUE THREAD

**Issue by flooose** [department-of-veterans-affairs/va.gov-team#73797]
## Problem Statement

In its [current form](https://github.com/department-of-veterans-affairs/terraform-aws-vsp-revproxy/tree/v1.8.0), [terraform_aws_vsp_revproxy](https://github.com/department-of-veterans-affairs/terraform-aws-vsp-revproxy/tree/main) supports a simple form of maintenance mode, during which all traffic, api and web, is cut off at the revproxy, resulting in a maintenance page and/or a 503 HTTP response. Because our revproxy sits in front of our APIs **and** APIs that we do not own (e.g. Lighthouse), we need to be able to enable maintenance mode for web traffic, independent of api traffic.

## Acceptance Criteria

- [x] Maintenance mode can be enabled for both api **and** web with one variable 
- [x] Maintenance mode can be enabled for api with its own variable
- [x] Maintenance mode can be enabled for web with its own variable

**Comment by jennb33** [comment]
This is in progress per @flooose and it is in PR, pending Kyle's review and approval.

**Comment by jennb33** [comment]
This is pending a code review on the Featured Maintenance Mode Enhancements #10.

**Comment by jennb33** [comment]
Sandbox upgrade is complete and successful, @flooose is going to follow up on this ticket.
