### ISSUE TITLE
[Support] Image and PDF Downloads on Outreach and Materials Page Not Triggering Analytics Events

### ISSUE THREAD

**Issue by nedierecel** [department-of-veterans-affairs/va.gov-team#738]
## What happened?
Click events to track Image and PDF downloads previously worked on staging but not recording on Production

## Specs:
- Device: (e.g. iPhone 8, Macbook): N/A
- Browser: (e.g. Firefox, IE 11): N/A
- Test User _(if applicable)_: N/A

## Steps to Reproduce
- URL: Navigate to https://www.va.gov/outreach-and-events/outreach-materials/ then click on PDFs or Images
- Test User _(if applicable)_: N/A

## Desired behavior
Clicks on images or PDFs should trigger a Google Analytics event

## Acceptance Criteria
- [x] Fix identified in Google Tag Manager
- [x] Resolution is QAed 
- [ ] Change is published in Google Tag Manager

## Definition of Done
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by nedierecel** [comment]
A fix has been made in Google Tag Manager that removes some incorrect RegEx and is ready for Q/A.

**Comment by jonwehausen** [comment]
Confirmed fix is now operating as expected in production instance. 

### Image Download
![image.png](https://images.zenhubusercontent.com/5d234c844828605fd8bf8ede/9a6fcc7d-bcd4-460b-95eb-cc6793c4d822)

### PDF Download
![image.png](https://images.zenhubusercontent.com/5d234c844828605fd8bf8ede/5e122c4a-83d0-47bb-b67b-d84b4dcc17f4)

**Comment by jonwehausen** [comment]
Request to publish has been sent.

**Comment by nedierecel** [comment]
@jonwehausen The changes have been published to Production and reverified on https://www.va.gov/outreach-and-events/outreach-materials/
