### ISSUE TITLE
10-7959f-1 Design | Wireframes

### ISSUE THREAD

**Issue by brian-wilke** [department-of-veterans-affairs/va.gov-team#73803]
Leveraging the user flow in this [ticket](https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/73799) create the wireframes needed for a "happy path" of a complete registration into the FMP

Deliverable:

Figma wireframes.
- These should leverage the current patterns in the form library
- Available for design intent if required (this step maybe skipped on the way to mid-point review)

Assumptions:
This program may or may not be able to participate PEGA depending on timing. 
S,o a print-ready version is also a possible outcome.

This program is only for veterans

Unknown:
Dependencies on eligibility
When an applicant might become aware of this program (do they have information available to them)

**Comment by marywang2** [comment]
@brian-wilke whenever the artifacts (user flow/wireframe/research plan, etc.) are ready, they can be added to the design intent section of the collaboration cycle [ticket](https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/74178).

**Comment by brian-wilke** [comment]
We do have outstanding questions for here and the User flow in regards to the ability to skip an address. Multiple options are presented here for the Design Intent 

https://www.figma.com/file/PzB1F5TYuBK5KQgPbuhAwH/10-7959f-1?type=design&node-id=1-19&mode=design

(this is for wireframes specifically)

Moving to Review

**Comment by marywang2** [comment]
Awaiting design intent meeting 1/29.
