### ISSUE TITLE
Discovery: Google Cloud Storage

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#73802]
### Description: 
https://cloud.google.com/blog/products/networking/eliminating-data-transfer-fees-when-migrating-off-google-cloud

### Findings

**Comment by johnny-jesensky-adhoc** [comment]
Closing this as a duplicate of another ticket, https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/49506.
