### ISSUE TITLE
DISCOVERY [FwdProxy move tor AL2] Containerize/map out the skeleton for the move to AL2

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#73826]
## Description
_What details are necessary to understand the work that this issue is tracking?_

## Resources 
- Refer to the RevProxy move to AL2 as an example
- 
## Acceptance Criteria
- Create stories for the epic

## Refinement Guidance - Check the following before working on this issue: 
- [x] _Team label assigned ("platform-tech-team-2")_
- [x] _Epic assigned (if needed)_ 
- [ ] _Estimated (points assigned)_
- [x] _Sprint assigned (once planned)_
- [x] _Team member(s) assigned_
- [x] _Understands how this work aligns with the overall platform_

**Comment by hgbarreto** [comment]
## Overview
- [Whats is FwdProxy](https://vfs.atlassian.net/wiki/spaces/ECP/pages/2011004977/Explainer+-+Forward+Proxy)
## Processes
- [Adding a new External service Connection](https://depo-platform-documentation.scrollhelp.site/developer-docs/adding-a-new-external-service-integration)

**Comment by hgbarreto** [comment]
## Possible Storiescreation
- fwd proxy repo creation + Infra GHA setup
- Dockerfile creation
- TF creation - ECR image
- GH action copy pasta

**Comment by hgbarreto** [comment]
Stories created - Closing
