### ISSUE TITLE
CT-EYB: Review Calculator data inputs/outputs

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#7382]
Review early doc on calculator data (provided by dev)
Identify inputs / outputs

**Comment by amyknox** [comment]
Inputs / Outputs
https://app.zenhub.com/files/133843125/a28a70d6-5e56-46ad-a6eb-44a391240520/download

**Comment by JenLJ** [comment]
Data and metrics on calculator inputs with possible categories
File name: EYB_Traceability Matrix

https://boozallen.sharepoint.com/:f:/r/teams/benefitsintegrationplatform/ClaimsModernization/Shared%20Documents/Working%20documents/UX%20Assets/CT-Estimate%20Your%20Benefits?csf=1&web=1&e=6SRBc5
