### ISSUE TITLE
RevProxy AL2 Deployment Automation in Production

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#73823]
## Description
Enable life traffic.  

## Resources 
Terraform needs created to replicate the behavior in Jenkins

## Acceptance Criteria
- [ ]  We have deployment parity with what we have in AL1

## Refinement Guidance - Check the following before working on this issue: 
- [ ] _Team label assigned ("platform-tech-team-2")_
- [ ] _Epic assigned (if needed)_ 
- [ ] _Estimated (points assigned)_
- [ ] _Sprint assigned (once planned)_
- [ ] _Team member(s) assigned_
- [ ] _Understands how this work aligns with the overall platform_

**Comment by ph-One** [comment]
This should not have been included in the current sprint. We have all of the lowers done, but need to be certain that deploys remain stable until promoting to production. Moving to next sprint.

**Comment by ph-One** [comment]
Deploying at 9:30PM EST today

**Comment by ph-One** [comment]
Deployed at 9:30pm EST on June 25, 2024
