### ISSUE TITLE
CT-EYB: Create Calculator traceability document

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#7383]
Create document that tracks data inputs / outputs by institution type (IHL, VET TEC, employer)

**Comment by amyknox** [comment]
https://boozallen.sharepoint.com/:f:/r/teams/benefitsintegrationplatform/ClaimsModernization/Shared%20Documents/Working%20documents/UX%20Assets/CT-Estimate%20Your%20Benefits?csf=1&web=1&e=6SRBc5
