### ISSUE TITLE
Toxic Exposure: Gulf War Hazard 1990 Date Ranges

### ISSUE THREAD

**Issue by christinec-fftc** [department-of-veterans-affairs/va.gov-team#73848]
## Issue Description
- Implement checkbox and loop flow for the Gulf War Hazard 1990 question.
- For each location selected (except for "None of these locations" and "I'm not sure"), display a follow up page to ask for the approximate date range served in that location.
- None and I'm not sure checkboxes are out of scope for this story. Will be added in subsequent story/ies.
- Discovery on what type of automated tests we can add for this. Create follow up story if needed.

<img width="934" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzFVQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b1741a2e9eed2383f64b6393605f8842c30c11d3/image.png" alt="image.png" />

## Front end tasks
- Ensure the page is styled according to design spec. 
- ~Ensure the back end data from API is displayed in local and review instance~
- Ensure unit tests are available. 
- Ensure your code changes are covered by E2E tests
- Run axe checks using the Chrome or Firefox browser plugin
- Test for color contrast and color blindness issues
- Zoom layouts to 400% at 1280px width
- Test with 1 or 2 screen readers
- Navigate using the keyboard only

## Acceptance Criteria
- [ ] Designer comments on this issue to approve page styling 
- [ ] Unit tests pass
- [ ] E2E tests cover current code and regression
- [ ] End-to-end tests show 0 violations.
- [ ] ~The data returned matches API response (for given user or scenario)~
- [ ] All axe checks pass
- [ ] All color contrast checks pass
- [ ] All zoom testing passes
- [ ] All keyboard checks pass 
- [ ] All screenreader checks pass

## Appendix
<details> 

 <summary>Ensure your code changes are covered by E2E tests (expand)</summary>
 
 - Add E2E tests if none exist for this addition/change. 
 
 - Update existing E2E tests if this code will change functionality. 
 
 - Include axe checks, including hidden content
 
</details>

<details> 

 <summary> Run axe checks using the Chrome or Firefox browser plugin (expand)</summary>
 
- Ensure no heading levels are skipped.

- Ensure all buttons and labeled inputs use semantic HTML elements.

- Ensure all buttons, labeled elements and images are identified using HTML semantic markers or ARIA roles.

- Ensure form fields have clearly defined boundaries or outlines.

- Ensure form fields do not use placeholder text. 

- Ensure form fields have highly visible and specific error states. 

</details>

<details> 

 <summary> Test for color contrast and color blindness issues (expand) </summary>
 - All text has appropriate contrast. 

</details>

<details> 

 <summary> Zoom layouts to 400% at 1280px width (expand)</summary> 
 - Ensure readability and usability are supported when zoomed up to 400% at 1280px browser width
 - Ensure no content gets focused offscreen or is hidden from view.
 
</details>

<details> 

 <summary> Test with 1 or 2 screen readers (expand)</summary> 
 
 - Ensure the page includes a skip navigation link. 
 
 - Ensure all links are properly descriptive. 
 
 - Ensure screen reader users can hear the text equivalent for each image conveying information. 

 - Ensure screen reader users can hear the text equivalent for each image button. 

 - Ensure screen reader users can hear labels and instructions for inputs. 
 
 - Ensure purely decorative images are not announced by the screenreader. 
 
</details>

<details> 

 <summary>Navigate using the keyboard only (expand)</summary> 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be reached with the tab key in a logical order. 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure all interactive elements can be reached with the tab key in a logical order 
 
 - Ensure all interactive elements can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure focus is always visible and appears in logical order.
 
 - Ensure each interactive element has visible focus state which appears in logical order.
 

</details>

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by christinec-fftc** [comment]
Notes from our UI/UX review today @Kate-allbee , @mengA6 , @RakshindaAslam 
1. Review instances
christine: this pull request did generate a review instance that loads and I learned how to set the toggle, but there is an auth failure. Will ask if there's a way to fix this
<img width="1229" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFhhQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6112c591fb852051c992705c245dd8d913561694/image.png" alt="image.png" />


1. Date component has an error validation when trying to put in a future date. Could this be a valid scenario for BDD + question 15D hazard exposures?
<img width="587" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3JhQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0ccde9a34ab798fd2ecc8120ab2fba279eae9b3d/image.png" alt="image.png" />
--> Let's ask VBA if future date should be allowed

2. Page load is subtle between the date pages and they all look so similar. Let's look into where the focus is on the page. If not already, it should be on the h3 title
--> christine to investigate

3. If there is only one location, we are displaying '1 of 1'. Do we want to leave as is or drop the counts if there's only 1?
mike: we are doing this for post 9/11 designs. seems ok to keep
kate: no strong feelings either way

4. The H4 titles look to have a color `#323A45` which is not in the [color palette](https://design.va.gov/foundation/color-palette)?
christine: It looks like other pages are using `vads-color-base-darker #3d4551`. Should I set it to that @Kate-allbee @mengA6?
<img width="586" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUxhQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--337a2b1eeb3e81701ce4bf5c2af061f23a0a7f97/image.png" alt="image.png" />

5. Review and submit page
5.1 The current title from the mocks results in all sections in Review and Submit having the same title
<img width="584" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWZhQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fd8b63ab3e819f7ddf2794ba6d3ef7728a742985/image.png" alt="image.png" />

Kate: We changed this previously so they would be unique. Let's look into what happened.

5.2 Mike: Can we modify review and submit components?
christine: yes this is possible, but we discussed previously that we would try to mvp with minimal customization and iterate on it if needed.

6. Test/Verification steps are in the [pr](https://github.com/department-of-veterans-affairs/vets-website/pull/28454). Most welcome to any feedback on it.

**Comment by mengA6** [comment]
4. "The H4 titles look to have a color #323A45 which is not in the [color palette](https://design.va.gov/foundation/color-palette)?"

Looks as though the shared style in Figma isn't right. Use #1b1b1b, which is what shows up in the [Typography page](https://design.va.gov/foundation/typography). Per the [color palette](https://design.va.gov/foundation/color-palette), this is the same value for `vads-color-base` and `vads-color-base-darkest`, but it's probably best to use `vads-color-base`.

**Comment by mengA6** [comment]
5. Review and submit page
5.1 The current title from the mocks results in all sections in Review and Submit having the same title

We have the design ticket [Update Review & Submit screen for toxic exposure #78372](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/78372) to address this

**Comment by mengA6** [comment]
2. "Date component has an error validation when trying to put in a future date. Could this be a valid scenario for BDD + question 15D hazard exposures?"

We have the design ticket [Confirm whether we should allow future dates in date ranges for toxic exposure #78419](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/78419) to find an answer for this

**Comment by mengA6** [comment]
I think that's it for now - we would need to sort out the auth issue for further testing, right?

**Comment by christinec-fftc** [comment]
>2. Page load is subtle between the date pages and they all look so similar. Let's look into where the focus is on the page. If not already, it should be on the h3 title

@mengA6 @Kate-allbee I looked into this and the initial focus when arriving on the page is on the h2 "Step 2 of 5: Conditions". This is consistent with the rest of the pages of 526. I agree it could be better on the h3, however, if we want to change this we should do it throughout the form and not just for the TE pages. I should also note I tested this out on the [mock-form on staging](https://staging.va.gov/mock-form/contact-information) and it also had initial focus on the h2. So i think this is the default for the design system.

**Comment by RakshindaAslam** [comment]
Do we want to run this by the accessibility team? @mengA6 @Kate-allbee

**Comment by mengA6** [comment]
> Date component has an error validation when trying to put in a future date. Could this be a valid scenario for BDD + question 15D hazard exposures?

per [Confirm whether we should allow future dates in date ranges for toxic exposure#78419](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/78419)

David Reis [confirmed in 3/19/24 VBA sync](https://docs.google.com/document/d/1H9xgYJ-oAj3AWKtnzZxOI3xv_ayQKju03rkc36Emax8/edit#heading=h.5y9awfwjne3p) that we don't need to allow future dates.

**Comment by mengA6** [comment]
> Page load is subtle between the date pages and they all look so similar. Let's look into where the focus is on the page. If not already, it should be on the h3 title

I think the current behavior is not a deal breaker, but yes, I'll submit a CAIA intake request to ask about the accessibility about that, and perhaps what CAIA suggests can be a future enhancement

**Comment by christinec-fftc** [comment]
Feature request submitted to allow for optional month when using va-date
https://github.com/department-of-veterans-affairs/va.gov-team/issues/78778
