### ISSUE TITLE
Add additional-info component to not-verified alert

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#73841]
BLOCKED: as of 2/14, expect final content on 2/16

### User story

As a Veteran using an unverified account on the MHV landing page, I want to be offered additional information around verification, so that I can better understand alternatives to and rationale for the main "Verify your account" CTA.

### Notes

- Design is finalized as of 2/16 (see [CAIA ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/73401))
- There was some discussion of whether to make the new component an optional upgrade to the original component (which is e.g. shared by My VA), with the existing "learn more..." link as the fallback – _Daniel has context_

## FINAL CONTENT

Main alert content (revised from what's in Prod):
> [alert header] **Verify your identity to use your ID.me account on My HealtheVet**
>
> Our records show that you haven't verified your identity for your ID.me account. We need you to verify your identity for this account to help us keep your information safe and prevent fraud and identity theft.
> 
> ID.me will ask you for certain personal information and identification. This process often takes about 10 minutes.
> 
> [link] Verify your identity

Additional-info component:

>[additional-info toggle] If you have trouble verifying your identity
>
>[Get answers to common questions about verifying your identity](https://www.va.gov/resources/verifying-your-identity-on-vagov/)
>
>Or, if you have a Premium My HealtheVet account with a My HealtheVet user ID and password, you can sign out and then sign back in with that account to access My HealtheVet.

## Acceptance criteria

- A Veteran using an unverified account sees on the landing page both the "Verify" alert and an additional-info component below it
- Implemented component in the shared IdentityNotVerified component so other teams can leverage as an "additional info" option (alongside existing "learn more" link option from My VA)

**Comment by fmccaf1** [comment]
We received feedback from CAIA, and I updated the design with that content. [Here's a link to the Figma file.](https://www.figma.com/file/CAChU51fWYMZsgDR5RXeSc/MHV-Landing-Page?type=design&node-id=263%3A21521&mode=design&t=zfuT1XyZokPYutj6-1) which should be viewable by anyone who clicks the link.

If you just want to do what's easy and copy and paste the text, here it is:

> Verify your identity to use your ID.me account on My HealtheVet
> We need to make sure you’re you—and not someone pretending to be you—before we can give you access to your personal and health-related information. This helps us keep your information safe and prevent fraud and identity theft.
> 
> ID.me will ask you for certain personal information and identification. This one-time process often takes about 10 minutes.
> 
> [link] Verify your identity
> 
> If you have trouble verifying your identity [additional info]
> Get answers to common questions about verifying your identity
> 
> Or, if you have a Premium My HealtheVet account with a My HealtheVet user ID and password, you can sign out and then sign back in with that account to access My HealtheVet.

**Comment by wesrowe** [comment]
FYI, I added a new comment in the CAIA ticket proposing another tweak.

**Comment by wesrowe** [comment]
CAIA updated content, I think we're good to go here. I'll clarify the desired content in the ticket soon.

**Comment by jzucadi** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/28226

**Comment by LynneJohnson224** [comment]
The octo-identity team is requesting, in the PR, that the content is updated to include login.gov.

**Comment by wesrowe** [comment]
I can't quite tell if this was resolved by communication already. lmk if I actually need to step in here.
