### ISSUE TITLE
Sign-In Service: Technical kickoff with Identity team

### ISSUE THREAD

**Issue by nihil2501** [department-of-veterans-affairs/va.gov-team#73865]
### Description
[Conversation](https://dsva.slack.com/archives/CSFV4QTKN/p1704925918179709?thread_ts=1704304081.034039&cid=CSFV4QTKN) that lead to the action item of scheduling a technical kickoff. Alex is scheduling this meeting.

### Acceptance Criteria
- [x] Technical Kickoff scheduled
  - January 25th, 11AM Eastern 
- [ ] Meeting notes from the kickoff

**Comment by nihil2501** [comment]
**TODO:** determine `blocking` or `blocked-by` or `related` relationship with `Create Sign-In Service ADR` [#73406](https://app.zenhub.com/workspaces/accredited-representative-facing-team-65453a97a9cc36069a2ad1d6/issues/gh/department-of-veterans-affairs/va.gov-team/73406)

**Comment by nihil2501** [comment]
@cohnjesse I just repurposed this ticket to track the work of attending and note taking the meeting. I explained a little about the rationale and background documentation about "legacy" authentication. Since you are leading I assigned it to you.

**Comment by RivkaCGates** [comment]
@nihil2501 Can you please link the notes from the meeting.
