### ISSUE TITLE
CT-EYB: Working Session UI Follow-up

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#7387]
Refine 2-3 concepts for EYB
Discuss options w UX team
Update / refine

**Comment by ccruzgra** [comment]
3 prototypes for initial solutions:

GIBCT Estimate Benefits - Schools - v0.0: https://bahdigital.invisionapp.com/share/JFIADETXBAW#/screens/296035253 

GIBCT Estimate Benefits - VET TEC - v0.0:
https://bahdigital.invisionapp.com/share/NVIADERSPYE#/screens/296035258 

GIBCT Estimate Benefits - Schools - Mobile - v0.0
https://bahdigital.invisionapp.com/share/QTIADGY6DCV#/screens
