### ISSUE TITLE
GIBCT - Upgrade AWS Database servers: Upgrade postgres in PROD

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#73905]
## Issue Description
Upgrade AWS Database servers postgres in **PROD** environment

---
## Tasks
- [ ] Work from tickets [72347](https://github.com/department-of-veterans-affairs/va.gov-team/issues/72347), [73887](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/73887), [73890](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/73890) and [73897](https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/73897) is complete. 

## Acceptance Criteria
- [ ] That the postgres upgrade is complete, tested, and correct after testing.

**Comment by jennb33** [comment]
@Kshitiz-devops will be investigating communications plan and will add to this ticket
cc: @LindseySaari

**Comment by jennb33** [comment]
Per Noah:

- Any concerns after the Postgres upgrade in Staging Environment?
- Not so far, everything seems to be working fine
- When do we want to schedule the Postgres upgrade in Production Environment?
- I think any day from the 21st to the 27th should be fine
- How will communication be handled with stakeholders or other relevant parties outside of the DevOps and developer teams?
- We’ll handle whatever communications are needed with our user base. You can communicate to the whole team using the above group email. You can also use the slack channel govcio-vfep-team.
- Are there specific updates or milestones that need to be communicated to stakeholders?
- Date/time you are starting the process and contact us when you are finished so we can immediately shake out.
- Time to do the upgrade? Is there a specific time or date that minimizes disruption to users?
- Generally after business hours works. Note that if GIBCT is going to be completely offline, you might want to schedule it over a weekend in the middle of the night. I can be available to do whatever shakeout is needed if you go that route.
- What channels will be used to communicate updates, progress, and any issues related to the PostgreSQL upgrade?
- Team email above, slack channel govcio-vfep-team Teams group : VFEP Team.

**Comment by rmtolmach** [comment]
Kshitiz and Chris completed this last night 🎉
