### ISSUE TITLE
CT-103: Solution UI Comps

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#7391]
Rough in screens for new UI
Build screens
Build interactions

**Comment by ccruzgra** [comment]
GIBCT PL 115-407 Section 103 v0.0 initial mockup of profile page link and modal: 
https://bahdigital.invisionapp.com/share/7NIADE8GMJ2

**Comment by ccruzgra** [comment]
V0.1: https://bahdigital.invisionapp.com/share/7NIADE8GMJ2
