### ISSUE TITLE
Design Sign in Page/Modal Note

### ISSUE THREAD

**Issue by lmorris3** [department-of-veterans-affairs/va.gov-team#73923]
Problem:
The OCTO SSiT leads are concerned that an Alert Box on the USiP is too much change too quickly for Veterans. They also want to be able to utilize an Alert Box in the future when they need to increase the urgency to switch to modern sign in credentials. They have suggested utilizing the "note" template in the VA design system to add a note under the primary CTAs that DSL and MHV are only available until December 31, 2024. 

User Story:
As a Veteran I want to know about upcoming credential service changes so I can continue to access my benefits and other VA services online.

ACCEPTANCE CRITERIA:
GIVEN I am accessing VA.gov
WHEN I click "sign in" on either a mobile device, desktop, laptop, tablet, etc.
OR I click a link on a resource page
AND I am viewing either the sign in modal
OR the sign in page
THEN I see a note under the four CTA buttons with the following verbiage:
Notice: DS Logon and My HealtheVet will only be available until December 31, 2024. After that time, you will need to use a Login.gov or ID.me account to sign in.

Notes:

see design mock
needs to be implemented on the Sign In Page and Modal:
https://www.va.gov/sign-in/?application=mhv&to=home&oauth=false
https://www.va.gov/?next=loginModal
Audience: all users
Components should be pulled from VA design system:
Documentation Note: https://www.figma.com/file/5AjroXgMKLS7p1jj62Vgh9/VAOS---VA-Design-System?type=design&node-id=2626-4887&mode=design&t=CV5gLgGhmfLAST7e-0

Metrics to track:

initially, we will want to track clicks on the four different credentials (LGN, ID.me, DSL, MHV) as well as the two create account links (for LGN and ID.me)
Timing: this change does not have a reversion date. The intent is to increase the rate limit percentage to 100% however the change should be revertible in case unforeseen issues arise

**Comment by SophiaPhilipMO** [comment]
Submitted to Danielle for review
