### ISSUE TITLE
VSO authorization (permissions)

### ISSUE THREAD

**Issue by nihil2501** [department-of-veterans-affairs/va.gov-team#73949]
### Description
One of the first, big units of UX we want to get to work on for the site is Veteran Service Officer (VSOff) authorization. For instance, once a user is logged in, we want to determine that they are the kind of user our site serves (a VSOff) who is configured to access the features our site has. In particular, this is determined by checking with Office of the General Council (`OGC`) that the user is an accredited rep (`Registration Num`), as well as whether their Veteran Service Organization (VSOrg) has a power of attorney code (`POA` code) which is potentially found in `CorpDB`/`BGS`. The UX for this could check these preconditions and present options to rectify them when absent. Or if present, it could move them along to something like a dashboard. But we want to work with the product team to flesh out this UX flow around authorization.

### Notes
- **Now:** Decided to proceed with leveraging `Sign-In Service` (`SiS`) since we’re leveraging all of the [VA.gov](VA.gov) platform ([ADR](https://app.zenhub.com/workspaces/accredited-representative-facing-team-65453a97a9cc36069a2ad1d6/issues/gh/department-of-veterans-affairs/va.gov-team/73248))
  - Architectural decision record (ADR) is [forthcoming](https://app.zenhub.com/workspaces/accredited-representative-facing-team-65453a97a9cc36069a2ad1d6/issues/gh/department-of-veterans-affairs/va.gov-team/73406)
  - Technical kickoff with the identity team is [forthcoming](https://app.zenhub.com/workspaces/accredited-representative-facing-team-65453a97a9cc36069a2ad1d6/issues/gh/department-of-veterans-affairs/va.gov-team/73865)
- **Next:** `SiS` just handles authentication, so the next phase is about [authorization UX](https://docs.google.com/document/d/1gQOPIwLmuIMrDXvYEE08XjV3IQfh3jBEEbNN7KNIIJw/edit#heading=h.m2kg1txwk6zv) and then technical implementation. It involves finding or provisioning a user’s record of accreditation in `OGC` as well as an associated `POA` code for them in `CorpDB`.
  - Slating of this work as our [“First Application Slice” epic](https://app.zenhub.com/workspaces/accredited-representative-facing-team-65453a97a9cc36069a2ad1d6/issues/gh/department-of-veterans-affairs/va.gov-team/72901) is possibly forthcoming

### Technical implementation
- We'll need to figure out the backend modeling and services that deal with `OGC` and `CorpDB`/`BGS`
- How do we associate the logged in user to VSOs?

### Documentation
- [Authentication flow spec](https://docs.google.com/document/d/1gQOPIwLmuIMrDXvYEE08XjV3IQfh3jBEEbNN7KNIIJw/edit#heading=h.6rbev4qhc1ag) describes authorization stuff after it explains login
- [Kickoff meeting notes](https://docs.google.com/document/d/1eD97ncZStVWq-0rtbyhkB6OuA6TUWyvUuPSUwA9lrb4/edit)

### Acceptance Criteria
- [ ] Authorization epic is created (with a tech spec?)

**Comment by a6marinos** [comment]
This ticket is no longer relevant, please refer to following ticket for more up to date flow: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1714501321813/e46b8ede7bc0ba3e7b5361d59e86c929688e0857?sender=u44da4f823ec94118a7079396

**Comment by a6marinos** [comment]
This ticket is no longer relevant, please refer to following ticket for more up to date flow: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1714501321813/e46b8ede7bc0ba3e7b5361d59e86c929688e0857?sender=u44da4f823ec94118a7079396

**Comment by a6marinos** [comment]
This ticket is no longer relevant, please refer to following ticket for more up to date flow: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1714501321813/e46b8ede7bc0ba3e7b5361d59e86c929688e0857?sender=u44da4f823ec94118a7079396
