### ISSUE TITLE
BUG - MHV Option 3 ToU looping

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#73941]
From MHV engineer:

> We are seeing an issue with ToU this morning. I logged in with an ID.me account through MHV Option 3. MHV displayed a pop-up with a link to [VA.gov](http://va.gov/) ToU. I navigated to [VA.gov](http://va.gov/) ToU and hit Accept. I was navigated back to MHV. However, I still got the pop-up with the link to [VA.gov](http://va.gov/) ToU. When I checked the ToU status I found out that it was not Accepted. When we hit Accept, it appears that it doesn't register. The status continues to show as declined
Please note that everything seems to work fine when logging in through MHV Option 1.

#### What I expected to happen

1. User has declined terms or is a new user who hasnt accepted terms.
2. User logs in with an idme account through option 3 on MHV staging and accepts terms.
3. User logs in with an idme account through option 3 on MHV staging and does not see the ToU pop up after they had previously accepted ToU.
4. the user is logged in on MHV staging.
#### What actually happened

1. User has declined terms or is a new user who hasnt accepted terms.
2. User logs in with an idme account through option 3 on MHV staging and accepts terms.
2. when I logged in with an idme account through option 3 on mhv staging I was shown the ToU pop up even though I had already accepted terms.
3. I was not logged into MHV staging

#### Screenshots or Supporting Evidence
- more to follow

#### Platform
- staging MHV

#### OS version and Browser version (if applicable)
- Chrome, on CAG (need to test outside of CAG but with staging MHV this isnt easy)

#### Affected environment(s)
- for now only staging

#### Severity of the issue
- [x] High severity
- [ ] Medium severity
- [ ] Low severity

#### Visibility
- [ ] User visible
- [x] Stakeholder visible

#### MR Approver
- TBD

**Comment by ianmagenta** [comment]
After running through the steps above and speaking with @asg5704, I would suggest closing this ticket as this issue doesn't appear to be on our end.

**Comment by joeniquette** [comment]
I passed on the info to the MHV team
