### ISSUE TITLE
CT-103: Refine Solution UI

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#7394]
Update screens
Update interactions

**Comment by amyknox** [comment]
Adjust the language & update the prototype so that the response isn't "yes / no" but "yes and..."

**Comment by ccruzgra** [comment]
Content updates: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/Sec103/design/content/103-content-doc.md

New Sec 103 v0.2 prototype with content updates: https://bahdigital.invisionapp.com/share/7RIADHXPZFD
