### ISSUE TITLE
[VA.gov Experience Standards - Expand information available to VFS teams]: Release Plan

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#73957]
## Guidance

_This Release Plan Template is intended to help ensure your new Platform product or feature is ready for launch and will deliver the desired user outcomes._
* _In Phase 1, you will test your product to learn how it'll actually be used, what problems it might create, and then fix/adjust if necessary prior to going live._
* _In Phase 2, you will define the launch communications plan and post-launch KPIs. **You can close this ticket once you have completed Phase 2**._
* _Phase 3 is optional - you may use it to document post-launch results._

_Fill out the **Planning** sections to start, then the **Results** sections as you complete each phase of testing._

---

## Phase I: User Acceptance Testing
*Test real-world user scenarios to ensure your product or feature performs as expected.*

### Planning:

- **Desired date range or test duration:** January 18, 2024 - TBD. When 5 VFS teams have completed Staging Review
- **Desired number of users:** 5
- **The group(s) from which you'll recruit test users:** VFS
- **How you'll recruit test users:** When teams reach out to schedule a Staging Review, we'll ask if they'd like to participate in our pilot. All teams have the option to opt out.
- **How you'll give test users access to the product:** All SR findings tickets will apply the new VA.gov Experience Standards and will be documented in an updated github ticket. 
- **What "Success" criteria will you look at before launch?** [refer to the desired outcomes and KPIs in your product outline] The survey asks VFS teams the following questions:
   - "Are the new standards and findings tickets clear and actionable?"
   - "Does the process help team members understand impact on the Veteran user experience?"
   - "Does the staging review meeting help clarify findings?"
   - "Is the overall staging review process clear and actionable?"
- **How you'll measure your "Success" criteria?** Excluding the questions that ask about prior experience with the VA.gov Experience Standards and the questions that help us determine a VFS team members role on their team, all questions asked in the survey research are assessed on a 5 point likert scale. Ideally, the average score for all research participants will be ~4. If the average is below 4, we'll know that the mew VA.gov Experience Standards and/or the new Github template do not meet VFS team expectations.

### Results:

More detailed findings can be found in the Governance/Research space on Confluence - [2023-11: New experience standards (VFS teams): Research plan](https://vfs.atlassian.net/wiki/spaces/PPST/pages/2832498689/2023-11+New+experience+standards+VFS+teams+Research+plan)

- Number of users: 5 VFS teams 

- Results per your "Success" criteria:

- Number of bugs identified / fixed: 0 - while no bugs were identified, we did identify changes we'd like to make to the process based off of findings from the VFS research as well as our own team research. See below.

- Any UX changes necessary based on the logs, user feedback, or VA challenges? Yes, see below.

  - If yes, what: See [Implement changes to Experience Standards based on Pilot findings ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/70958)

### Planning:

- Desired launch date: April 24, 2024
- Actual launch date: April 22, 2024
- Post-launch KPI 1: N/A
- Post-launch KPI 2:
- Post-launch KPI 3: 

### 1-week results:

- Number of unique users: 
- Post-launch KPI 1 actual: 
- Post-launch KPI 2 actual: 
- Post-launch KPI 3 actual:
- Any issues with Platform handling/processing?: yes/no
  - If yes, what:
- Any UX changes necessary based on the logs, user feedback, or VA challenges? yes/no
  - If yes, what: 

### 1-month results:

- Number of unique users: 
- Post-launch KPI 1 actual: 
- Post-launch KPI 2 actual: 
- Post-launch KPI 3 actual: 
- Any issues with Platform handling/processing?: yes/no
  - If yes, what:
- Any UX changes necessary based on the logs, user feedback, or VA challenges? yes/no
  - If yes, what: 

## Post-launch Questions

*To be completed once you have gathered your initial set of data, as outlined above.*

1. How do the KPIs you gathered compare to your pre-launch definition(s) of "success"?
2. What qualitative feedback have you gathered from users or other stakeholders, if any?
3. Which of the assumptions you listed in your product outline were/were not validated?
4. How might your product evolve now or in the future based on these results?

**Comment by humancompanion-usds** [comment]
@shiragoodman - Do we have a go-live date planned yet for the new Experience Standards? Just updating my FY24 goals and want to accurately reflect when we think this will land. Thanks!

**Comment by shiragoodman** [comment]
@humancompanion-usds this sprint, we're working on [making changes to our process post-pilot](https://app.zenhub.com/workspaces/platform-governance-team-5f85b91c14d8df0018fac414/issues/gh/department-of-veterans-affairs/va.gov-team/70958). Once that work is done, we will begin planning for launch. All of the changes to VFS-facing guidance and operational guidance have already been made (excluding anything that needs to be changed post-pilot) and Erin has shared that the post-pilot changes should be complete by end of sprint. We can likely start the launch process at the start of the next sprint (April 11) with a plan to launch by end of sprint (April 24). 

I will work on getting this release plan updated with the pilot findings and can share our plan for launch.

Let me know what you think or if you have any questions. Thanks!
