### ISSUE TITLE
[Other - Accessibility] Helper text likely to be missed by screen reader users. (00.00.2)

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#73993]
#### VFS team name
Benefits Non-Disability

#### VFS product name
Pension 527EZ Digital Form

#### VFS feature name
Form Reactivation

#### Point of Contact/Reviewers
Brian DeConinck - @briandeconinck - Accessibility

*For more information on how to interpret this ticket, please refer to the [Anatomy of a Staging Review issue ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Anatomy-of-a-Staging-Review-Issue-ticket.2060320997.html) guidance on Platform Website.

---

### Platform Issue
No VA.gov Experience Standard for the issue found.

### Issue Details
On [Special monthly pension](https://staging.va.gov/pension/application/527EZ/medical/history/monthly-pension), there are two paragraphs of helper text that appear between the `legend` and the question label. For a screen reader user tabbing through the page, this helper text is going to get skipped entirely.

This helper text seems especially critical for this question, since it defines what VA means by "special monthly pension" and lays out eligibility criteria. And since one of those criteria is having a "severe visual impairment," it's important to make sure screen reader users hear this information.

This issue also occurs on:
- [Income and assets](https://staging.va.gov/pension/application/527EZ/financial/land-marketable), with the info alert explaining what it means for additional land to be marketable.

### VA.gov Experience Standard
[Category Number 00, Issue Number 00](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

### Platform Recommendation
The best pattern we've identified here is to group the helper text inside the `legend`, and then style it to look like "normal" text. It will end up looking something like:

```
<fieldset>
   <legend>
      <span class="some-class-name">Special monthly pension</span>
      <div class="some-other-class-name">
         <p>If you have...</p>
         <p>You may be eligible...</p>
      </div>
   </legend>
   <va-radio ... />
</fieldset>
```

---

### VFS Guidance

- Close the ticket when the issue has been resolved or validated by your Product Owner
- If your team has additional questions or needs Platform help validating the issue, please comment on the ticket
- Some feedback provided may be out of scope for your iteration of the product, however, Platform's OCTO leadership has stated that all identified issues need to be documented and it is still your responsibility to resolve the issue.
- If you do not believe that this Staging Review issue ticket is the responsibility of your team, comment below providing an explanation and who you believe is responsible. Please tag the Point of Contact/Reviewers. Governance team will research and will follow up.

**Comment by gmaciolek** [comment]
I tested the SMP page and the Income and assets > Total net worth page with VoiceOver on a Mac and the helper text was read aloud as expected on both pages.
