### ISSUE TITLE
Provide examples of Markdown

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#740]

**Comment by smoonpeyes** [comment]
@1Copenut This is an example ticket, correct? Can we close this?

**Comment by 1Copenut** [comment]
I think it was an actual issue the By Light team requested. I'll add a link and ping the Assignee.

**Comment by 1Copenut** [comment]
@danheverly I think this [Github guide on mastering Markdown](https://guides.github.com/features/mastering-markdown/) should work for the team to get up and running. IIRC, ZenHub honors all Github Markdown syntax. Should be 1:1.
