### ISSUE TITLE
Phone numbers with dashes cause submission error

### ISSUE THREAD

**Issue by aplatt-coforma** [department-of-veterans-affairs/va.gov-team#74013]
**Steps:**
1. start a pension form
2. in the phone number or mobile number field, enter a phone number that has dashes. e.g. 123-345-3456
3. complete the rest of the form
4. submit

Expected: form is submitted without error
Actual: error about regex is returned and the UI says we encountered a error connecting to va.gov
<img width="1566" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUxkQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9cce645db15abc0369cd8847fad745cb140cf4a4/Screenshot%202024-01-18%20at%202.23.35%E2%80%AFPM.png" alt="Screenshot 2024-01-18 at 2.23.35 PM.png" />

Notes: 
If I remove the dashes in the phone fields, then the form submits just fine.

**Comment by vbellissimo** [comment]
I think we can close this, right @aplatt-coforma ?
