### ISSUE TITLE
Vets-api terminal access for Casey Williams

### ISSUE THREAD

**Issue by caseywilliams** [department-of-veterans-affairs/va.gov-team#74016]
### Your Name

Casey Williams

### Your GitHub handle (terminal access is managed through GitHub)

@caseywilliams

### Your dsvagovcloud AWS user name (if applicable)

Casey.Williams

### Team, Role, and Company of the target individual

Team Banana Peels (Appeals), Lighthouse Benefits APIs, Ad Hoc, LLC

### Product Manager (PM) name and email

Michael Hobson (michael.hobson@adhocteam.us)

### Product Owner (PO) name and email

Janet Coutinho (janet.coutinho@va.gov)

### COR Name (leave "None" if you listed an AWS user name above)

None

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

None

### Please confirm if you are listed as a team member in Atlas or are listed in Platform Team Roster

- [ ] [Team Member in Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [X] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Please confirm E-QIP Transmittal/Adjudication. This could be a screenshot of your Transmittal/Adjudication email, a link to another request where you've submitted this proof (i.e. AWS/SOCKS), etc.

- [X] I have attached proof that I have either transmitted my E-QIP survey or previously received a favorable decision (by including in "Additional Notes" section below)

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### Additional Notes

My recently approved AWS access request is here, including a screenshot of my E-QIP transmittal email: https://github.com/department-of-veterans-affairs/va.gov-team/issues/72788

I'm a developer on the team maintaining the Appealable Issues, Legacy Appeals, Notice of Disagreements, Supplemental Claims, Higher-Level Reviews, and Appeals Status APIs for Lighthouse, and need production access to respond to customer support escalations.

### Additional resources for Support Engineer

- [ ] For users on a VFS team but not listed as a team member in Atlas, they must start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] Instructions for handling requests [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access) - Support Only

**Comment by lindsay-insco** [comment]
#72788 - AWS access request explicitly requested: 

> I need access to the rails console for vets-api in all environments so that I can help with questions from support. Currently, I seem to have access to the lower environments, but not production. For reference, my teammates are Kristin Brown, Michel McDonald, and Matt Kelly (although I am not sure that Matt has prod access himself).

Justification was approved by OCTODE 

@caseywilliams intended to place a VetsAPI Prod access request and selected wrong template. But also had prod access previously as evidenced in ticket #55656

**Comment by lindsay-insco** [comment]
User found in Atlas

**Comment by lindsay-insco** [comment]
@caseywilliams production access has been granted for 6 months, your access will expire 07/18/24. Please set a reminder for yourself to return to this Issue and re-request access within 1 week of the expiration date. You'll receive 1 reminder with a 48 hour window to respond. Failure to do so will result in lost access and will require you to fill out a new request

**Comment by lindsay-insco** [comment]
Slack reminder [here](https://dsva.slack.com/archives/C06CY71PCAX/p1705618524222669)

**Comment by bdech** [comment]
No response. Production access removed. If you would like to request production access, please fill out a new request.
