### ISSUE TITLE
[bug spike] SC upload failures (1/15/24)

### ISSUE THREAD

**Issue by anniebtran** [department-of-veterans-affairs/va.gov-team#74017]
## What happened?
On Jan 15th, we got an alert in our notifications channel about some evidence upload jobs (`DecisionReview::SubmitUpload`) failing permanently (retries exhausted). We were able to find the job ids for the evidence uploads that failed and some logs related to the failures (linked below).

Upon investigation, we were able to find the uploads that were not submitted to Lighthouse. We should be able to resubmit the evidence uploads by re-running the jobs on the AppealSubmissionUpload records associated with the user's AppealSubmission (they only have one, it's for SC, and is from Jan 15) that are missing Lighthouse ID references

## What do we need to know?
What caused the errors, how we can make these errors more easily visible for triaging.

## What we've tried in order to debug the error / what we do know
We tried to re-run the job manually for one of the AppealSubmissionUploads, but we were interrupted by an [incident on production](https://dsva.slack.com/archives/CE4304QPK/p1705613480487909) that restarted the pods and possibly [impacted the ability for the job to run properly](https://vagov.ddog-gov.com/logs?query=env%3Aeks-prod%20%40named_tags.jid%3A%228a96707b150b6ae9266c55ee%22%20&cols=host%2C%40named_tags.source%2C%40named_tags.jid%2C%40named_tags.dd.env%2C%40named_tags.user_uuid&index=&messageDisplay=inline&refresh_mode=paused&storage=hot&stream_sort=host%2Casc&viz=stream&from_ts=1705611600000&to_ts=1705615200000&live=false), so we will likely need to manually queue up the job again and finish the remaining uploads

## Action items
- [ ] Timebox investigation

## Slack threads and background context
- [Thread in DD alert notifications channel — includes the job ids](https://dsva.slack.com/archives/C05UPRR0HK3/p1705346531608389)
- [Context logs for the jobs' permanent errors](https://vagov.ddog-gov.com/logs?query=host%3Avets-api-sidekiq-%2A%20service%3Avets-api%20%22DecisionReview%3A%3ASubmitUpload%22%20&cols=host%2Cservice&context_event=AY0OkSRWAADoHEzLmVyQAAAn&event=&index=%2A&messageDisplay=inline&refresh_mode=paused&screenId=7xz-4n2-jvc&screenName=sidekiq-job-death-queue&storage=hot&stream_sort=time%2Cdesc&view=spans&viz=&from_ts=1705298400000&to_ts=1705384740000&live=false)
- [Sidekiq Job Death Queue (for future reference)](https://vagov.ddog-gov.com/dashboard/7xz-4n2-jvc/sidekiq-job-death-queue?refresh_mode=sliding&view=spans&from_ts=1705531133482&to_ts=1705617533482&live=true)

## Definition of Ready 
- [ ] Timebox is defined
- [ ] Nature of the issue defined

## Definition of Done
- [ ] Figure out what caused the error
- [ ] Determine ways to make the error more easily visible (not silent)

## Out of scope
- Coding solution

**Comment by anniebtran** [comment]
Slack thread started with Lighthouse [here](https://dsva.slack.com/archives/CKUCFQAHJ/p1705699549364859?thread_ts=1705698943.682639&cid=CKUCFQAHJ)

What we know after some investigation:
- There are `AppealSubmissionUploads` without LH IDs — makes sense because the error happened before we update these records with those IDs
- `AppealsApi::EvidenceSubmission` and `VBADocuments::UploadSubmission` records both get created on every job run/retry, so we at least know we're reaching this point in the [Lighthouse code](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/appeals_api/app/controllers/appeals_api/v2/decision_reviews/supplemental_claims/evidence_submissions_controller.rb#L26-L27) but are still trying to track down whether there are errors that aren't getting bubbled up before the `ensure` block with the `.close` gets called

**Comment by anniebtran** [comment]
Next step — ask Platform team to check if failed upload files exist in S3 and general info about them (e.g. size, etc). They can find the AppealSubmission via the user_uuid in [the "Evidence upload to Lighthouse job failures" logs](https://vagov.ddog-gov.com/dashboard/tvp-imf-tb7/benefits---notice-of-disagreement?refresh_mode=paused&view=spans&from_ts=1705345564000&to_ts=1705346764000&live=false), and from there get the AppealSubmissionUploads with `nil` Lighthouse IDs to figure out which uploads failed.

**Comment by anniebtran** [comment]
Update: Eugene got their AWS S3 access back and we checked to see if those failed uploads had files that still existed in the bucket, and unfortunately we didn't see them in there, so they must have gotten deleted somehow 🥴 Not sure what next steps should be on this

**Comment by anniebtran** [comment]
@saderagsdale not sure if you wanna follow up on this, but just wanted to make sure you're aware of this update ^

**Comment by saderagsdale** [comment]
Sade will add this to the mini-remediation list and share with VBA

**Comment by saderagsdale** [comment]
Discuss auditing process in bug triage.

**Comment by anniebtran** [comment]
Just confirming the status of this based on the question from standup — these files were not orphaned because there are `AppealSubmissionUpload` records that tie the files back to the appeal itself. The issue is that the files don't exist in our S3 bucket (from comment above) so we can't manually try to re-upload to Lighthouse.

**Comment by anniebtran** [comment]
@saderagsdale I know there was a note on Jan 29 that says you added it to the mini-remediation list — I wasn't sure where that was so just in case, I added the Supplemental Claim UUID for this incident to the Sharepoint file that had the SCs affected by the AWS outage (https://github.com/department-of-veterans-affairs/va.gov-team/issues/72199) and renamed the file to "Supplemental Claims with evidence upload issues"

**Comment by shaunburdick** [comment]
Will be handled by the overall remediation spike
