### ISSUE TITLE
Midpoint Review - Design Feedback - Employee Experience Team, 21-526EZ, Max CFI

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#74026]
## VFS actions
- [x] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [x] Comment on this ticket:
  - [x] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [x] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [x] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [x] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- Use v3 components like the progress bar. I understand you are not changing the whole form so you may want to sync with the team that may own that.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- Must: Love the checkbox tile! Your tile border is a light blue, however in the [design system](https://design.va.gov/components/form/checkbox#tile) we have color-gray-light rgb(169, 174, 177).
- Must: If you are going to use the minimal header, pair it with the [minimal footer](https://design.va.gov/components/footer/footer-minimal).

**Comment by erinrwhite** [comment]
@it-harrison Just ahead of our MPR this morning! I've updated the MPR script [in our documentation](https://vfs.atlassian.net/wiki/spaces/PPS/pages/2790424639/Midpoint+Review+-+During+the+Meeting+Synchronous) and on the [platform website page](https://vfs.atlassian.net/wiki/spaces/CC/pages/1781039167/Midpoint+review) (to be published this afternoon). Let me know if you have edits/concerns.

**Comment by RakshindaAslam** [comment]
- [x] Must: If you are going to use the minimal header, pair it with the [minimal footer] 
     -  No change necessary. 526 uses matching header and footer. This was accidentally mismatched in this prototype.

**Comment by carodew** [comment]
My understanding as well from @RakshindaAslam is that they already have tickets for exploring converting components to V3 across the 526 form. 

I have changed the border color of the checkbox tiles in the prototype and we can carry that over into production.
