### ISSUE TITLE
Add ICN to userverifier log

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#74033]
### Issue Description

The LGA team is looking for logs that can assist with tracking the sunsetting of DSLogon and MHV. One of the logs they want to use is userverifier. They need the ICN to be within this log as a field that can be parsed so they can match up against other existing accounts.

Please add the ICN value of the logged in user to the userverifier log if the value is available. I understand that these logs include non-verified users, its expected we will not get ICN for these logs. We just want the ICN available for logs that can show it.

Here is the value to search for in datadog for the log: `UserVerifier`. [Example of logs](https://vagov.ddog-gov.com/logs?query=userverifier%20&cols=host%2Cservice&event=AgAAAY0iVmENj7sStwAAAAAAAAAYAAAAAEFZMGlWbTlCQUFCbTN3WGRoOUVZOEFBcwAAACQAAAAAMDE4ZDIyNTYtOWQ5Yy00MjM2LWI2NGItMGE5N2Q3OGM4OThl&index=&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=time%2Cdesc&viz=stream&from_ts=1705516687490&to_ts=1705520287490&live=true).

Acceptance Criteria:
- When I open a log such as this one, I expect to see the ICN of the user:

![Image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/71290526/a03c333f-139b-4016-8785-883e19654b89)

**Comment by bramleyjl** [comment]
New User creation log has been updated to include the ICN in the payload

https://vagov.ddog-gov.com/logs?query=%22%5BLogin%3A%3AUserVerifier%5D%20New%20Va.gov%20user%22%20&cols=host%2Cservice&event=AgAAAY04VcaIAWni5AAAAAAAAAAYAAAAAEFZMDRWZHFNQUFEcklxU1BHaUdESlFBTAAAACQAAAAAMDE4ZDM4NTUtZjJkNy00YzVmLTlmMjQtNDY2OTYyODZhYjNl&index=%2A&messageDisplay=inline&refresh_mode=sliding&stream_sort=desc&viz=stream&from_ts=1706046171029&to_ts=1706047071029&live=true
