### ISSUE TITLE
Training for Fixing Production Configuration Issues 

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#74044]
**Background**
The incorrect settings were loaded into production. Vets-API’s secrets and environment variables are defined from a file, settings.local.yml. This file requires a specific configuration to properly load the environment variables. In this pull request, Rachal Cassity attempted to fix the configuration but some of the settings were incorrect. The pull request had over 2000 line modifications. The changes were reviewed and the changes seemed to be correct due to the amount of modifications.

This could have been prevented by having more reviewers in the pull request and teaching more engineers on how to handle manifest modifications.

**Training Action Items**
- [x] Explain how settings get condensed
- [x] How to find the pull request condensed the settings
- [x] Reverting the condensed settings
- [x] Reviewing production setting's pull requests

**Comment by RachalCassity** [comment]
On January 19th, 2024, training was held. Developers in the Platform Product Team plus Eric Boehs and Ryan McNeil were in attendence.

**Comment by jennb33** [comment]
@RachalCassity should we story point this at a "1" since it was training that was done in today's BE knowledge transfer meeting? Please confirm, thanks.
