### ISSUE TITLE
Remove fipper 

### ISSUE THREAD

**Issue by mjknight50** [department-of-veterans-affairs/va.gov-team#74046]
Unless you can think of a good reason to keep it, please remove the flipper for using Lighthouse API.  We will always be using Lighthouse from now on.

`use_lighthouse = Flipper.enabled?(:pension_claim_submission_to_lighthouse)`

from:
`vets-api/app/controllers/v0/pension_claims_controller.rb`

It should also be cleaned out of the flipper itself
/flipper/features/pension_claim_submission_to_lighthouse

**Comment by wayne-weibel** [comment]
https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretogglesguide-Removingold/unusedfeaturetoggles
