### ISSUE TITLE
Oracle transition alert for facilities switching before integration

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#74052]
SM product team requested alert content to tell Veterans that their facility is switching to My VA Health. North Chicago is switching on March 8, so we'll use this as a model for all of these messages. 
- This message will show in SM on [VA.gov](http://va.gov/) to patients at North Chicago facility only
- It will tell them that soon, they'll need to use My VA Health to send messages to care teams at North Chicago
- On March 8, we'll switch the message to the "post-transition" Oracle alert that already shows for Veterans with Oracle facilities
- Once SM on VA.gov launches the Oracle/MHV integrated inbox to phase 1, we'll stop showing these messages 

Example transition alert from MHV classic: 
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/104158104/895b9bce-ee2e-40ab-88fb-e2c20daaa956)

Existing "post-transition" Oracle alert in SM on VA.gov
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/104158104/49193091-1287-4d91-8643-4ad730a56e5c)

**Comment by laurwill** [comment]
Misty and I are pairing on this, since mobile will need similar alerts. We're drafting in [this Mural](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1706284632056/bd0898e9be89541a02ed5c50076ade10e7fe31ec?sender=u85a35f55e50d7c375c782462), but need to sync again and direct some questions to product team before sharing.

**Comment by laurwill** [comment]
Hi @underpaid1ntern , just updating here with the copy tweak we worked out over slack.

**[H1] Your health facility is moving to My VA Health**
**[Bold facility name]** is moving to our My VA Health portal.
Starting on **March 4**, you won't be able to use this My HealtheVet tool to send messages to care teams at this facility.
Starting on **March 9**, you can use the new My VA Health portal to send messages to these care teams.

**Comment by lichellebain** [comment]
When we insert the facility name, are you expecting North Chicago or Lovell Federal Health Care Center?

**Comment by laurwill** [comment]
Hi @lichellebain @underpaid1ntern @janieTC-USDS , here's suggested content for the T-5 version. This is similar to the approach for blocked and "no association" messaging we worked on recently.

**[H1] You can't send messages to some of your care teams right now**

We're moving data for **Lovell Federal Health Care Center** to our My VA Health portal. On **March 9,** you can start using My VA Health to send messages to care teams at this facility. 

To contact your care team now, call your facility.

Find your VA health facility [link to facility locator]

**Comment by janieTC-USDS** [comment]
great thanks @laurwill !

**Comment by laurwill** [comment]
Work is complete. Closing ticket.
