### ISSUE TITLE
New VFS Team Unified Appointment Experience

### ISSUE THREAD

**Issue by BrittanySFowler** [department-of-veterans-affairs/va.gov-team#74060]
## Welcome and Introduction
We are excited to welcome your team to VA.gov. As a new VFS team, this template should be completed by your teams Product Owner and/or Product Manager.

## User Stories
As the leader of a new VFS team, I need to share basic info about my team with Platform so that Platform teams can have knowledge of my team for future collaboration.

As the leader of a new VFS team, I need to ensure my team follows the instructions for new VFS team members so that they're aware of Platform policies and processes, and Platform is aware of who supports my team for future collaboration.

As the leader of a new VFS team, I need to ensure my teams product information is correct so that Platform can have an accurate list of VA.gov products.

As the leader of a new VFS team, I need to complete ATO orientation so that VA.gov continues to be a secured and approved application within the VA.

## New Team Info
Add your team's practice and contact information below.

- **Team Name:** Unified Appointment Experience

- **OCTO-DE Product Owner:** Kay Lawyer

- **VA Business Owner:**
   - [x] OCTO (Office of the CTO)
   - [ ] VHA (Veterans Health Administration)
   - [ ] VBA (Veterans Benefits Administration)
   - [ ] NCA (National Cemetery Administration)
   - [ ] VACO (Veterans Affairs Central Office)
   - [ ] Other. Please specify: ____________

- **Crew:**
   - [ ] Sitewide
   - [ ] Account Experience
   - [x] Health Tools
   - [ ] Benefit Tools
   - [ ] Lighthouse API

- **Github team name:** Appointments Oracle Health Integration

- **Github team label:** apps-oracle-health-integration

- **Team launch date:** 1/2/2024

- **Public slack channel:** there is only a private channel called "appointments-oracle-health-integration"

- **Other team names:**

- [ ] This information has been added.

## ToT (Team of Teams)
- [ ] Contact `@Julia Badillo` or `@Erica Robbins [GovCIO_VetsPS]` on the #team-of-teams-slide-collection channel to receive an invite to the Team of Teams meeting and the Team of Teams Agenda and Protocol for reference

## Introduce your team on slack
- [ ] Introduce your team on the #vfs-all-teams Slack channel. Include team name, Product Manager, Product Owner, what crew your team is on, and what products you're supporting on VA.gov.

## Platform Orientation for your team members
In addition to providing information to Platform and completing necessary tasks at the team level, there are also tasks that need to be completed at the individual level. As a team leader, you will need to:
- [x] Direct your team members to the guidance for [New VFS team members](https://depo-platform-documentation.scrollhelp.site/getting-started/Guidance-for-new-teams-and-team-members.2132803700.html#Guidancefornewteamsandteammembers-NewVFSTeammembers) on Platform Website
- [X] Ask all of your team members to complete the process

## Review and update your team's product information
- [ ] Go to the [VA Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory)
- [ ] Navigate to and select your team's product
- [ ] Review to make sure that all of your team's products are listed and assigned correctly
- [ ] If an edit to your team's product page needs to be made, see the [user guide](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory-user-guide)

## ATO (Authorization to Operate) orientation
- [ ] Post in the #platform-security Slack channel to request and schedule an ATO team orientation
- [ ] Confirm that the orientation has been completed

## Platform Checklist
The items in this checklist are for Platform to complete. If you are ready to close the ticket and the Platform Checklist section has not been completed, please reach out to Platform via the guidance provided in [Getting help from Platform in Slack](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).
- [x] New VFS Team has been added to the VFS Team Roster located in [Atlas](https://www.va.gov/atlas/)

**Comment by anita-halici** [comment]
@bmatos312  it is also Michael's is https://github.com/department-of-veterans-affairs/va.gov-team/issues/73703, and Devin: https://github.com/department-of-veterans-affairs/va.gov-team/issues/73588 (I was able to add Devin to zenhub).

**Comment by bmatos312** [comment]
@anita-halici Hello Anita, for Michael I can see him in zenhub, it may be because of his github handle. "rammic" Let me know if you still cannot see him!

**Comment by anita-halici** [comment]
@bmatos312 I still can't see him when i try to add him to the board

**Comment by anita-halici** [comment]
@bmatos312  would you share the direct link to their team page in git?

**Comment by anita-halici** [comment]
hi @bmatos312 are you able to point me to the location where this team can start storing their documentation ?

**Comment by bmatos312** [comment]
@anita-halici Hello Anita, I would reach out to their PM and if that doesn't resolve the issue then next best step would be to reach out to Jason Woodman.

**Comment by anita-halici** [comment]
thanks
