### ISSUE TITLE
[MVP] Ensure number values from web form aligning properly to PDF fields

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#74065]
## Issue Description

During our PDF generation testing, we discovered that both dollar amount number and regular number fields are mapping to the PDF left-aligned.

We need to ensure that the values from all number fields entered from the web form are mapped to the PDF as right-aligned.

## Example of how it's currently mapping to PDF:

---
## Acceptance Criteria
- [ ] Ensure that the values from all number fields entered from the web form are mapped to the PDF as right-aligned.

**Comment by aplatt-coforma** [comment]
Looks good on staging. here are a few examples of number on the generated PDF.
<img width="877" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkQ1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4de984e2e41f16e8feef4e53dc83fd342f332e63/Screenshot%202024-01-24%20at%205.06.02%E2%80%AFPM.png" alt="Screenshot 2024-01-24 at 5.06.02 PM.png" />
