### ISSUE TITLE
[Congressional] V11298984 Due 2/16/24 (Rep Crow)

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#74069]
## Issue Description
_The VA recently opened an account for the Veteran online. In that account both his first and middle name are misspelled. The system will not allow him to correct this himself.
Case Attachments: V11298984 - VA.gov and MyHealtheVet Issues (Rep. Crow)

https://dsva.slack.com/archives/C02BS78NYRM/p1705691422646979 
---
## Tasks
- [x] Review congressional correspondence
- [x] Resolve issue 
- [x] Notify Veteran and congressional correspondence channel of solution.

## Acceptance Criteria
- [x] Veteran issue will be resolved or responded to with final answer to issue 
- [x] Congressional Correspondence will receive details of the resolution 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2023-CSM** [comment]
January 19, 2024 Vicki C. sent an email to Jeremy Haas and cc you. He's responded advising an internal JIRA ticket has been created (ETSHD-2426) cc you to have him look into. EVSS is still working to correct data mismatch issues with MPI and DEERS. They expect to have all the data issues resolved likely in the next couple of business days, and will provide further updates to this issue as they become available.

**Comment by Kimberley2023-CSM** [comment]
January 22, 2024:  **Update:** The EVSS HD team was able to confirm the resolution with MPI and DEERS this morning, and we have now resolved the remaining issues that were outstanding with this veteran’s account. With these issues now resolved, EVSS is reaching out to the veteran this morning to request their confirmation.  Waiting on response from Veteran.

**Comment by Kimberley2023-CSM** [comment]
Jeremy from the EVSS team responded:
The EVSS HD has sent follow-up emails to this veteran, explaining the issue and resolution, as well as requesting a response back for three consecutive business days. We have not received any response from the veteran.  For this reason, I personally called the veteran this afternoon but was again unable to get in touch with them. I did leave a detailed voicemail identifying who I was, that his login issue should now be resolved, and the HD contact information while again requesting a response back from the veteran. Barring further request to contact the veteran, or any response from the veteran themselves, we will consider his issue resolved at the EVSS HD. Thank you.
This case is closed! :closed_sign:

**Comment by Kimberley2023-CSM** [comment]
Issue was confirmed as resolved be the EVSS team via a confirmation email received by the Veteran on 1/26/2024 @ 9:44AM.
