### ISSUE TITLE
[MVP] Update help text for phone number fields, change to say without dashes

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#74067]
## Issue Description

Currently, dashes entered in phone number fields  for US numbers (for 10 digit codes) are causing validation errors. We need to update the help text on all US phone number fields (for 10 digit codes) found on the form to clarify that they should **_not_** enter dashes within phone numbers.

---

## Acceptance Criteria

- [ ] Update the help text for all US phone number fields (for 10 digit codes)  on the form to not allow dashes between numbers. 

- [ ] The help text in parentheses should simply say (without dashes)

<img width="605" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzdpQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5a69bfd75dc36876fd3008eee5a7d221730cca2e/Screenshot%202024-01-19%20at%203.13.11%E2%80%AFPM.png" alt="Screenshot 2024-01-19 at 3.13.11 PM.png" />

**Comment by zack** [comment]
@vbellissimo can you please provide reproduction steps? I am not able to reproduce validation errors with dashes. Additionally, this entire component (the input, the error text, and the validation) comes untouched from Platform teams new web components, so if there is an issue we would need to file a ticket with them.


[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3puQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7ff3eb65a02ddd965b9558226e54ae3cac95fea9/phone-number-dashes.mp4)

**Comment by vbellissimo** [comment]
@zack good point. This is a summary of what we found out during testing, for more context:

- In testing for pension relaunch, we found that **users who have an extension attached to their phone number in their VA profile** aren't able to submit this form. The phone number they enter in the form itself is not used -- pre-fill logic pulls their profile phone number and appends their extension to that phone number -- causing it to fail our own 10-digits-only validation.
- A Veteran in this circumstance would get a confusing front-end error message that says it can't connect to [va.gov](http://va.gov/), but they aren't able to submit. So it's not a "silent submission failure" -- it's a confusing block they can never get past. However, the validation logic  involved is more global: beyond our own form, and not specific to what gets printed on a PDF.

- We decided:

-- the lack of ability to submit with a phone number in your extension is unfortunate and poor, but the logic driving it is used across enough other forms that we don't feel comfortable changing it in a rush -- we risk increasing submission errors or other cascading effects
-- We are making the assumption that extensions in primary contact phone numbers are somewhat uncommon and would have caused problems for the Veteran in other interactions and are not going to block the pension relaunch based on this bug. But it's not an acceptable pattern, so we'll scope a post-launch ticket to
--- Understand the pre-fill service better, and whether we should continue to leverage it and/or write back to it when a Veteran updates their phone number in the  pension form and/or simply populate the pension data with what's typed in the form itself.
--- Work with other teams who use the service to change the way extensions are handled

**Comment by vbellissimo** [comment]
@zack Here is a Slack thread with Emily about it: https://dsva.slack.com/archives/C05MS96P6P2/p1705696092333329

**Comment by vbellissimo** [comment]
@zack Another point for context, I believe this is only for US numbers, so I will update the AC on here for that.

**Comment by aplatt-coforma** [comment]
Verified that inputing dashes in phone numbers will still allow submissions without errors. 
I did observe that when entering ( or space characters, the UI displays the field warning 
> Please enter a 10-digit phone number (with or without dashes)
Probably will need to consider these characters when looking into long term solution/alignment.
