### ISSUE TITLE
[MVP] Step 5: Ensure data mapping from Who receives this income? question maps to PDF

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#74064]
## Issue Description

Related to #73161, we need to ensure that the recently updated question format in Staging for: Who receives this income?, found under the [Gross Monthly Income page](https://staging.va.gov/pension/application/527EZ/financial/income-sources), is mapping to the PDF accordingly.

## Example of existing question in staging:

<img width="413" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzdoQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0e016681f57ef0491e0c2af48cc9801c5ca9d939/Screenshot%202024-01-19%20at%202.32.38%E2%80%AFPM.png" alt="Screenshot 2024-01-19 at 2.32.38 PM.png" />

---
## Acceptance Criteria
- [ ] Ensure that the recently updated question format in Staging for: Who receives this income?, found under the Gross Monthy Income page, is mapping to the PDF accordingly. 
- [ ] Answers should map to 9H(1), 9I(1), 9J(1), 9K(1).
- [ ] Any answers submitted beyond the 4 entries allowed into the PDF question fields should be treated as Overflow data at the end of the PDF.

## Example of question(s) on PDF:
<img width="907" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3ZoQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--41df5e67c6bf7ff76a290559353c95eef017e027/Screenshot%202024-01-17%20at%2010.00.10%E2%80%AFAM.png" alt="Screenshot 2024-01-17 at 10.00.10 AM.png" />

**Comment by aplatt-coforma** [comment]
Looks good on stage
<img width="877" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlA1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3f083fe654b82c3eabecace456786bb210a53545/Screenshot%202024-01-24%20at%205.06.02%E2%80%AFPM.png" alt="Screenshot 2024-01-24 at 5.06.02 PM.png" />
<img width="1618" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlQ1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6af87fcaa768d7b1ce04675fd968f3061a641fbe/Screenshot%202024-01-24%20at%205.05.46%E2%80%AFPM.png" alt="Screenshot 2024-01-24 at 5.05.46 PM.png" />

**Comment by aplatt-coforma** [comment]
Reopening this issue. Friday's build seems to have reverted the fix for this ticket. Here's the current behavior with a submission for Friday.
<img width="1346" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWtGQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5b20c5c0433f4be3ee8e6b76ea9bbf9f11400590/Screenshot%202024-01-27%20at%207.10.56%E2%80%AFPM.png" alt="Screenshot 2024-01-27 at 7.10.56 PM.png" />

**Comment by aplatt-coforma** [comment]
Confirmed on staging while testing #74698
<img width="1532" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjhTQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dd5e9c14cab234794f971a9c4f9e4fbff8ff65cf/Screenshot%202024-01-30%20at%201.45.09%E2%80%AFPM.png" alt="Screenshot 2024-01-30 at 1.45.09 PM.png" />
