### ISSUE TITLE
[CST] Claim status header revision

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#74071]
## Value Proposition

As a veteran who finds themselves on the status tab, I want to see clear header description of what this page is for, so I understand what content I'm likely to see there and continue reading to identify important actions I might want to take or to understand my claim history better.

## Design

[Figma link](https://www.figma.com/file/F8U4wddaFouUPVd4mGBMDI/CST---Evidence-Submission---Spec?type=design&node-id=80-1335&mode=design&t=GdTIkr7Pq59HeLqd-0) (Look at section: "Core Screens")

<img width="463" alt="Screenshot 2024-01-24 at 5 03 56 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/95102058/bca8b0ac-65c5-45ff-bbd4-1a43aedfe2d2">

## Acceptance Criteria

- [x] Header section contains header text that introduces what the page is
- [x] A description is included that is succinct that explains what the page is for and what you can do on it
- [x] User can determine whether the claim is in progress or not
- [x] The claims last updated date is clearly visible
- [x] The header and description text are always above the other content.
- [x] Behind the cst_use_claim_details_v2 feature flag

**Comment by HeatherWidmont** [comment]
@jacobworrell to validate async today
