### ISSUE TITLE
[CST] Claim files header revisions

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#74073]
## Value proposition

As a veteran who finds themselves on the Files tab, I want to see clear header description of what this page is for, so I understand what content I'm likely to see there and continue reading to identify important actions I might want to take or to understand my claim history better.

## Design

[Figma link](https://www.figma.com/file/F8U4wddaFouUPVd4mGBMDI/CST---Evidence-Submission---Spec?type=design&node-id=80-1335&mode=design&t=tcQOG8xJc6F06f6w-4) (Look at section: "Core Screens")

<img width="471" alt="Screenshot 2024-01-24 at 5 05 49 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/95102058/905224b2-15b0-4898-90a2-b9759193adeb">

## Acceptance Criteria

- [x] Header section contains header text that introduces what the page is
- [x] A description is included that is succinct that explains what the page is for and what you can do on it
- [x] Behind the cst_use_claim_details_v2 feature flag

**Comment by HeatherWidmont** [comment]
@jacobworrell to validate today

**Comment by pmclaren19** [comment]
@jacobworrell this can be validated in Staging now.

**Comment by jacobworrell** [comment]
Validated!
