### ISSUE TITLE
[CST] Overview tab header and sub header

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#74074]
## Value proposition

As a veteran who finds themselves on the Overview tab, I want to see clear header description of what this page is for, so I understand what content I'm likely to see there and continue reading to identify important actions I might want to take or to understand my claim history better.

## Design

[Figma link](https://www.figma.com/file/F8U4wddaFouUPVd4mGBMDI/CST---Evidence-Submission---Spec?type=design&node-id=80-1335&mode=design&t=c3kTdSTTaBXBwc7V-0) (Look at section: "Core screens")

<img width="439" alt="Screenshot 2024-01-24 at 5 01 47 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/95102058/e819ed5f-da49-4b53-b8c9-4dc86c29dc26">

## Acceptance Criteria

- [x] Header section contains header text that introduces what the page is
- [x] A description is included that is succinct that explains what the page is for and what you can do on it
- [x] Behind the cst_use_claim_details_v2 feature flag

**Comment by HeatherWidmont** [comment]
Blocked due to pipeline issue. Once that is resolved Jacob will validate

**Comment by pmclaren19** [comment]
@jacobworrell this can be validated in Staging now.

**Comment by jacobworrell** [comment]
Validated!
