### ISSUE TITLE
[CST] Evidence request alert added to the additional evidence section of files tab

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#74076]
## Value Proposition

As a veteran who finds his way to the Files tab in CST, I want to see open requests for evidence, so that I'm reminded about exactly what I should/could submit on this page

## Background

Figma designs: https://www.figma.com/file/F8U4wddaFouUPVd4mGBMDI/CST---Evidence-Submission---Spec?type=design&node-id=0-809&mode=design

## Currently what happens
On the files 'Files tab' under the 'File Requests' header users can see all first party alerts (the alerts in yellow)  and second party alerts (the alerts in grey) 
![Screenshot 2024-01-17 at 2 28 09 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/141954992/54e79feb-70e0-49c1-adc4-c637791d57c9)
Also on the Files tab under the 'Additional evidence' header there is an alert with text
![Screenshot 2024-01-17 at 3 06 30 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/141954992/f72a4cce-d5b5-4f0c-8a87-001c24666b00)
<img width="956" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0xiQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6c763f88573d3abd0907c8d823e5a19a5e9ba65c/Screenshot%202024-01-18%20at%209.26.58%E2%80%AFAM.png" alt="Screenshot 2024-01-18 at 9.26.58 AM.png" />

## What we want to happen
When a user goes to the Files tab they no longer see the 'Files requests' header. 
All first and secondary alerts are now displayed under the 'Additional evidence' header. 
After the alerts, there is no longer a alert that says 'Please only submit additional evidence that supports this claim' and instead there is text.
![Screenshot 2024-01-17 at 3 09 06 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/141954992/911d5516-79d7-4694-8b94-93dec38d6869)
![Screenshot 2024-01-17 at 3 14 15 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/141954992/092aac80-917c-4f71-9c85-66e9b4b08b3a)

## Acceptance Criteria

- [x] Open requests for evidence can be found near the top of the page in the "additional evidence requests" section.
- [x] Primary evidence requests provide clarity to the veteran around what the type of evidence is, a description of the evidence, and a date the request is due when possible.
- [x] Secondary alert added under "Additional Evidence" makes clear when there is an optional third party request.
- [x] Primary alert shows when there is an open request for the veteran.
- [x] Secondary alert shows when the VA has an open third party request.
- [x] Evidence requests design approach is consistent with similar alerts for evidence requests found elsewhere in CST.
- [x] Previous versions of evidence alerts no longer show on the page
- [x] Behind cst_use_claim_details_v2 feature flag

**Comment by jacobworrell** [comment]
include pagination component

**Comment by HeatherWidmont** [comment]
Devs to review this in the parking lot today

**Comment by HeatherWidmont** [comment]
@pmclaren19 is this user story finished now & ready to close?
