### ISSUE TITLE
[IA - PI1/24] Debt Portal Information Architecture - Address sync update

### ISSUE THREAD

**Issue by Tom-Davis** [department-of-veterans-affairs/va.gov-team#74081]
### Description
As a Veteran, I want to experience a seamless clear and easy to follow information that aligns with all standard site styles and adheres to current accessibility standards.

This Epic will focus on the syncing of addresses in all accessible locations when updates are made via form submission or profile updates.

### Scope of release:

Update IA and hierarchy of information on the [Debt Portal](http://va.gov/manage-va-debt/).

### Out of Scope:

Non address updates.

### Additional Details/Notes (optional):
*Any other relevant information about this project not already listed above*

**Comment by denisecoveyduc** [comment]
@Tom-Davis FYI - closing this to remove from this epic and better structure going forward.
