### ISSUE TITLE
[MVP] After submission, a form in progress is still shown after logging in

### ISSUE THREAD

**Issue by buddhima-coforma** [department-of-veterans-affairs/va.gov-team#74080]
### Description
After successfully submitting a form on staging, I logged back in and noticed this.
The last saved time is around the time I submitted it.
Staging user: vets.gov.user+54@gmail.com

<img width="720" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWJpQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--29f99e29eaf5845b79495728b9e9bb1fc7411461/image.png" alt="image.png" />

### Expected behavior
- After a successful submission, do not show an in-progress form, as a user may think it didn't go through
- If there was an issue with submission, then it makes sense to show an in-progress form

**Comment by buddhima-coforma** [comment]
Closing this as the issue seems to have resolved itself

**Comment by danlim715** [comment]
@buddhima-coforma @vbellissimo If you're not seeing anymore random in progress forms after success submissions, can we close out this ticket due to inability to replicate issue in staging?
