### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by kevinshih613** [department-of-veterans-affairs/va.gov-team#74100]
### Name

Kevin Shih

### Email

kevin.shih@va.gov

### Role

UX Researcher

### Team

Lighthouse Bandicoot

**Comment by naomimarcussen** [comment]
Hi! An invite has been sent to [kevin.shih@va.gov](mailto:kevin.shih@va.gov). Once you create an account you'll have viewer-restricted access to look around.
