### ISSUE TITLE
Access for Kim Mueller-VAMC Upgrade team-GovernmentCIO

### ISSUE THREAD

**Issue by kimmueller1** [department-of-veterans-affairs/va.gov-team#7411]
# Description
- Request: Please provide SOCKS proxy access as this is required to complete support work on VAMC-Upgrade product. Access need for: dev, staging, prod, CI environments and Jenkins.
-Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your name.
   > Kim Mueller
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Team: VSA-VAMC-UPGRADE/VAMC-UPGRADE
Role: Content Writer
Company: GovernmentCIO
- ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDHKHJFW3nBiY3+g9vzXdQs6Ypfguf9hXVYG3SltnETVacmrvzjTHebHViy2gFuMkVthhDW/d/RfPgQGJFMZSdP+AJGEGaAZbo+2JWU7Rznd5fcSwXb3AtOI1ccTz/w75glWoInBoZuScPlNknTJasOx29sA74zUxdr+qhaJN/IxUo/7JbJV42x/SHa3ikr/Nrhwv//4zCIABvJ4h2YaD4rekkZ7lkYytmGuUL28Y7VWPU3SNzp5726R/iu/h5sDLNboH37E2j5crLWBJmWUoEytEyYxKHHaSK4zZ1m8X8C8N6atPZDa+XGnppDbGArCaG82oyoNYMkjvH01CGlSqCbdtvsaMBlZKtguxdiDLwSIw012w+5nl15zlSqjyKe5O3Try0vjuaFG7J1P8eFYdC8vp5S9o18y+j3Q6EG/Wb/08DN5hgRXwvgknsrgbks9a+FUbhKK1wkX4YNXuA421MnywgzHrkIghVSdIQTdPfSIKGN/AE4TPIoE3NrkCEH60c= Kim Mueller@DESKTOP-J1M6Q51

```

- [Grant AWS Console access?]
  > NO
  >  Please give a brief description for why you are requesting AWS access.

**Comment by jbritt1** [comment]
SOCKS access granted. @kimmueller1 please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.
