### ISSUE TITLE
Access for  Sundararaj Kumarasamy - VAMC-Upgrade team - GovernmentCIO

### ISSUE THREAD

**Issue by sundarka1** [department-of-veterans-affairs/va.gov-team#7412]
# Description
**Request: Please provide SOCKS proxy access as this is required to complete support work on VAMC-Upgrade product.  Access needed for: dev, staging, prod,  CI environments and Jenkins.**
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your name.
   > Sundararaj Kumarasamy
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Team: VSA-VAMC-UPGRADE / VAMC-UPGRADE
   > Role: Sr. Drupal Engineer 
   > Company: GovernmentCIO

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDPijOH5ZRy8Mf4GP9KevwAbOYcDhEFTndZYI9ggyCIKJpkIX/4JC/f+OHRr7Ows9MN8DVLl2dU4aO0GY5A4DP3koE3oF9J4m9hhrdB89lMIap9tuGrZgkUcF8KA+uFnWn1C+Tv3DE3esg0PGpI9V1hDpmVqawe6u+vmuIH3tKe/DdskMogTeJZt78XKqoMKeFBLvpmIT6xkP3nGsdsWyvc8wu33jqHkcIhbSiRL1Gq2KD7sOsVgwcMuVfIv3N0gC2lWKSv4f1Std0+e4d0cxuaXVYAC/KwhntXvtGiK1MkmR7mG+/YZ2Q5Yj6Z86FGZtAeXKp5otjKm4PdI2DZU88Z sundarkumarasamy@USRMonitors-MacBook-Pro.local

```

- [Grant AWS Console access?]
  > NO

**Comment by jbritt1** [comment]
SOCKS access granted. @sundarka1 please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.
