### ISSUE TITLE
SOCKS access for Andrew Rodiek

### ISSUE THREAD

**Issue by Dr-Pongo** [department-of-veterans-affairs/va.gov-team#74127]
### Your Name

Andrew Rodiek

### Your Email

andrew.rodiek@govcio.com

### Your Role and Team

Debt Resolution, Front End Engineer, GovCIO

### Product Manager (PM) name and email

Tom Davis, Thomas.Davis@govcio.com

### Product Owner (PO) name and email

Denise Coveyduc, denise.coveyduc@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDcosWxXm0ZR/ATYxvM39Q0jDd5QxldaqMyuC9wnhz4BlPv8f4qADtyhbuOhE4wOt5jCP4u2I0B6rY1+sAEIUh9f/K6CV8J41RWl4gud0Vj14Ck+8F0gtKYeTnKIK6gjhpBN/wZbCam+ZeZH/jHbNvgNcXz1l8ThENsa5i3zlBbpxWUCz72cd0KJy/dgb730zniMW5EvFuZrwrmSv0gVg5N8/Y31xpU53+6tkQ8szZCmYZwWH+z2Hg8HIcMEpbrd7xdfRbOTdVzyu01VtylQ0f1djmNiVfUo1MxkY5eoTCZsU/30NAM85IAnGVI7dv/iSwcYdMMFhXrE6vuMFNv/P4sOuU9y0YDkD8/p472X7Uy53txCD4zRrvf33bURWkcr1R6S4s56shN/DTMIkIpiBpTTmwDzMiQD19i9NVlGKmGcebjyDpd32bVT91VjSqcCwLB3T2DZ+j7Swt2fRtOPwnVXQ+Vkb400h4xKZsrpTUi/ymsSTu400paHL9IGsfMKy8= andrew.rodiek@fvfgn645q05n.lan

### E-QIP Transmittal Confirmation

[Linking previously approved request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/47330). I'm setting up a new work laptop 

### User must exist in a roster before SOCKS access can be granted

- [x] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by barbarello** [comment]
access granted

**Comment by barbarello** [comment]
@Dr-Pongo Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html 

Reach out in #vfs-platform-support if you have any trouble.
