### ISSUE TITLE
Update breadcrumb documentation to clarify that H1 should not be used on final crumb within multi-step forms

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-team#74133]
To learn more about contributing to the Design System or requesting new components, requesting changes to existing components, and reporting bugs, go here.
https://design.va.gov/about/contributing-to-the-design-system/

---
# Bug Report or Design System update

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened
During PACT Act Collab Cycle review it became clear that design system documentation for breadcrumbs could use an explicit statement for how final crumb should work within multi-step forms. 

* During content edits, CAIA had instructed to use the H1 for final crumb, per breadcrumb documentation that states "Each breadcrumb segment should match the H1 of the corresponding page. When writing H1s for a page, follow the content [styleguide for writing page titles](https://design.va.gov/content-style-guide/page-titles-and-section-titles)."
* Collab Cycle: identified during Staging Review that this is incorrect for multi-step forms: https://github.com/department-of-veterans-affairs/va.gov-team/issues/73577
* Thread with Mikki Northuis that confirms she's in discussion with DS about the guidance here, and confirmed a ticket would be useful: https://dsva.slack.com/archives/C52CL1PKQ/p1705588332902109

## What I expected to happen

Known exceptions to the rule are documented in the DS docs for breadcrumbs.

**Comment by humancompanion-usds** [comment]
Alright, I've read through the issues and the slack thread.

@mnorthuis - How is this for an update? 

The documentation currently says:
> **Each breadcrumb segment should match the H1 of the corresponding page.** When writing H1s for a page, follow the content styleguide for writing page titles.

I believe that is still accurate because my reading of that is, essentially, the text of each crumb should match the text of an h1 and not be an abbreviation or variation on that title. Perhaps that needs clarifying. So how about I clarify that and add the following to give us:

> * **Each breadcrumb segment should match the text of the title (h1) of the corresponding page.** Breadcrumb segment text must match the title (h1) text of a corresponding page and not be an abbreviation or variation of that title. When writing H1s for a page, follow the content styleguide for writing page titles.
> * **Use the title (h1) of the Introduction page as the text of the final breadcrumb for a multi-step form.** On a multi-step form the final crumb is frozen as the title of the Introduction page and should link back to the Introduction page. The breadcrumb works in concert with the Progress bar - Segmented component to provide context for a user is in a process and on the site.

Does that work? Thoughts?

**Comment by mnorthuis** [comment]
Yes, that works.  I think this should also tie into the title tags - Ithe browser title tags would follow the same logic in regards to always matching the title of the introduction page.

**Comment by humancompanion-usds** [comment]
Forgot to tag the issue in the PR but this change went out in here: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/2574
