### ISSUE TITLE
Convert SelectDate1Page unit test to Cypress test

### ISSUE THREAD

**Issue by vbahinwillit** [department-of-veterans-affairs/va.gov-team#74131]
## Description
This ticket is related to the unit test cleanup ticket #61858 . A number of test where skipped for later review. Upon review, it was determine that integration tests should be written as Cypress test due to the test setup being simpler.

---

## Acceptance Criteria
- [ ] The new Cypress test should capture all the existing unit test scenarios
- [ ] The old unit test should be deleted

### Design Assets
N/A

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket.
