### ISSUE TITLE
Middle name on confirmation page

### ISSUE THREAD

**Issue by gmaciolek** [department-of-veterans-affairs/va.gov-team#74149]
User story: As someone who submitted a Pension form, I want my middle name to be accurate or absent on the confirmation page

Description:
Middle name is an optional field, but if it's not provided, it shows as "Null" on the confirmation page.

AC
- If a user enters their middle name, the Confirmation page of the online Pension form will show this (instead of Null)
- If a user enters their middle name, the Confirmation page of the online Pension form will not show "Null" in place of it.

Screenshot:
<img width="525" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjNuQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--233ee1bd33a1ad83bc3f270a27bb9c5c6272773d/confirmation-screen-middle-name-issue.png" alt="confirmation-screen-middle-name-issue.png" />

**Comment by gmaciolek** [comment]
Note: This issue happens in the VA profile as well

<img width="1035" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODdwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a6092778ea2926c1d13f267c71ddfb6012d4b2a9/Screenshot%202024-01-22%20at%203.51.41%20PM.png" alt="Screenshot 2024-01-22 at 3.51.41 PM.png" />

**Comment by vbellissimo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/74149?planning-poker) with Zenhub @danlim715 @scottsdevelopment @TaiWilkin @ToddWebDev @wayne-weibel

**Comment by aplatt-coforma** [comment]
Looks good on staging
<img width="1226" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVpqQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7b5e1a03fb6c0773bd0761928ef702f9df8eda9a/Screenshot%202024-02-15%20at%2012.24.46%E2%80%AFPM.png" alt="Screenshot 2024-02-15 at 12.24.46 PM.png" />
