### ISSUE TITLE
Default web components to using version 3

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#74145]
## Description
The Design System team will be defaulting web components from `v1` to `v3` (see https://dsva.slack.com/archives/CBU0KDSB1/p1705946290867919)

## Tasks
- [ ] Ensure all Identity components & pages have the `uswds` prop set to true
- [ ] Take screenshots of the before and after.

**Comment by parkerbees** [comment]
moved to jira, closing here
