### ISSUE TITLE
Confirmation page UX improvements

### ISSUE THREAD

**Issue by gmaciolek** [department-of-veterans-affairs/va.gov-team#74150]
User story: As someone who submitted a Pension form, I want to know what will happen next and how I can find out the status of my claim

Description:
In the confirmation page, we say "We may contact you for more information or documents," but we don't say that you'll receive a letter in the mail [when/stating what?]

We also can tell the user that they can check the status of their Pension claim on VA.gov. Do we have a pattern for how we send people to the Claim Status Tool? (We can link to it, but there won't be anything there yet.) How should we vary this language for someone who's authenticated vs someone who isn't?

Tasks:
- [ ] Determine whether there's an existing pattern for sending people to the Claim Status Tool
- [ ] Research what letters are sent to the Veteran after they file their claim and what content is in each letter
- [ ] Draft new copy and update existing confirmation page design

AC:
- [ ] Updated design file created
- [ ] Design shared with CAIA for review (?)

Additional resources:
https://dsva.slack.com/archives/C06E83RNLQM/p1705702654804039

Screenshots:
<img width="525" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkRuQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--72e8c88624a8a8868a550057229b1dcb2f864a60/Screenshot%202024-01-19%20at%2011.03.42%20AM.png" alt="Screenshot 2024-01-19 at 11.03.42 AM.png" />

**Comment by katherine-fung** [comment]
Hi @vbellissimo @gmaciolek @mayacoforma, 

I've drafted copy for the confirmation page to address the tasks in this ticket: 
https://docs.google.com/document/d/10CvfMytOYDw27m3A4mRLORQbh9kAtRG_kOuGQad9rNk/edit 

I based the copy on the design system's pattern for helping users to ["keep a record of submitted information." ](https://design.va.gov/patterns/help-users-to/keep-a-record-of-submitted-information) If the confirmation page design is different from the pattern, feel free to use the parts of the draft copy that are relevant.  

- > In the confirmation page, we say "We may contact you for more information or documents," but we don't say that you'll receive a letter in the mail [when/stating what?]

Walter Olsen at VBA [said this in Teams chat](https://teams.microsoft.com/l/message/19:meeting_MWE3N2IxNDktNDFmZC00OWRmLThhYjItZDc0YTlmYzg5N2Rj@thread.v2/1706800829463?context=%7B%22contextType%22%3A%22chat%22%7D): "Claimants receive a notification letter once their claim is decided (denied or granted)."

Brianna Mullins also confirmed this information for Veterans, [in Teams chat](https://teams.microsoft.com/l/message/19:meeting_MWE3N2IxNDktNDFmZC00OWRmLThhYjItZDc0YTlmYzg5N2Rj@thread.v2/1706801749554?context=%7B%22contextType%22%3A%22chat%22%7D): "You don't need to do anything while you wait for a decision unless we send you a letter to ask you for more information. If we send you a request for more information, you’ll need to respond within 30 days of our request. If you don't respond within 30 days, we may decide your claim with the evidence that's available to us."

- > We also can tell the user that they can check the status of their Pension claim on VA.gov. Do we have a pattern for how we send people to the Claim Status Tool? (We can link to it, but there won't be anything there yet.) How should we vary this language for someone who's authenticated vs someone who isn't?

We have standard language for this that I've included in the draft copy. 

- Along with the mailing instructions on the confirmation page, we should add that Veterans can also send us their supporting documents using QuickSubmit. Terrence Minyard at VBA confirmed this in the [Teams chat](https://teams.microsoft.com/l/message/19:meeting_MWE3N2IxNDktNDFmZC00OWRmLThhYjItZDc0YTlmYzg5N2Rj@thread.v2/1706801153856?context=%7B%22contextType%22%3A%22chat%22%7D). 

I've included these instructions in the draft copy.

**Comment by vbellissimo** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/74150?planning-poker) with Zenhub @danlim715 @scottsdevelopment @TaiWilkin @ToddWebDev @wayne-weibel

**Comment by aplatt-coforma** [comment]
Verified confirmation changes update on staging. Looks good. 
<img width="495" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVNUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a7def74eacbc3b598ff8d4ce9f874a840ef9e212/screencapture-staging-va-gov-pension-application-527EZ-confirmation-2024-02-27-08_39_36.png" alt="screencapture-staging-va-gov-pension-application-527EZ-confirmation-2024-02-27-08_39_36.png" />
