### ISSUE TITLE
Add :appointments as a 'MAP Security token' client

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#74157]
We need to get a client id for staging from the MAP STS team, store it in our MAP integration, and call it when the MAP STS in vets-api is called with the `:appointments` application

**Comment by joeniquette** [comment]
We have the MAP components:
    "client_name": "VA.gov Appointments (Dev)"
    "client_id": "2ec6f5872c27669a"

    "client_name": "VA.gov Appointments (SQA)"
    "client_id": "74b3145e1354555e"

We now need to make an internal registration to map the client_id to the application identifier in the MAP STS (lib/map/security_token/service.rb)
