### ISSUE TITLE
Discovery - 526 and ancillary start and end

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#74164]
In preparation for submission state machine design lets determine the start and success definitions for each of the actions involved in the 526 submission that we believe are necessary for tracking in the submission state machine:

Acceptance criteria:
1. A spreadsheet with a line for each action that needs to be tracked
2. for each action define what constitutes the start of that action in context of 526 submissions
3. for each action define what we believe constitutes the fulfillment of vet api responsibility 
4. List of 'actions'

- 526 primary
- 526 backup - sam
- 526 failsafe - sam
- 4142
- 0781
- 0781a
- bdd
- flashes

nice to have actions:
- delete itf
- 1delete in progress
-

- [ ] Reach out to Emily and Steve about where we go from here

**Comment by NB28VT** [comment]
Deliverable document is [here](https://docs.google.com/spreadsheets/d/1BVYLMGfIhk6corq5Zqneg98aRaRD9qJ2XYI4h7hoYzA/edit#gid=0)

**Comment by austinjprice** [comment]
moving to review as I believe this work is completed

**Comment by NB28VT** [comment]
Extensively documented in flow diagrams in this Mural board on polling: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1704307770399/7ba4dac361cbc90633616ae0a476bf7ac0db94f2?sender=7005f734-f979-4663-a55f-b3bb9a067b84
