### ISSUE TITLE
Access for Lisa Trombley - VAMC-Upgrade team - GovernmentCIO

### ISSUE THREAD

**Issue by ltrombley** [department-of-veterans-affairs/va.gov-team#7416]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Request: Please provide SOCKS proxy access as this is required to complete support work on VAMC-Upgrade product.  Access needed for: dev, staging, prod,  CI environments and Jenkins.”
   > Mary O'Toole
- Please provide your name.
   > Lisa Trombley
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > : VSA-VAMC-UPGRADE / VAMC-UPGRADE,  Role: Analytics/Business Analyst, Company: GovernmentCIO
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
Lisa Trombley@DESKTOP-KE31G1C MINGW64 ~
$ cat ~/.ssh/id_rsa_vetsgov.pub
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDJRxImPZ62EmlP3h5q4BRR2wr9iSgnDaveFCCKSipExlrKg3fiqyoH/H7eGgg4+yf6nvlUCUaE62qsoKZladqqqNZlUnJQ9VPKDE3KEup625c1lGvcClODE5AQjCC0T+vNN3l6Pb3ryq6upYbWRJUgi67OVo0mMaLku+tQeX3ey9rHtn/oab4zVpcstoTI6sVZTxGzlty5cA/aNEjxOXyJAdjUzq1mQMoZ94EHKWNSFNccSU77EJ9YfAJAe4ESALnH8EWv0ZTrGMvFUKYEVBDBuSNkRQ8iljlOz0TABL8DKrbRRnM4+gjn6H9tAthQWjzkblNWYn8biI7ddWTEy+es9MWQUWdfSEwj1eT3XVfTIftOECJCkQ/Ezo7O7DUCF9UhD4DO7qlA+zHu3l+mPUc3eycAgENxure4lnq0EKorup7oHzuh0VT+xTM+GG5UkIE/sktAJ3q33DgtTlq5g0iZIPAuBmTBO1XTAXYyXf5hwWQtTU9XrhGTa3CWjThXRkM= Lisa Trombley@DESKTOP-KE31G1C

```

- [Grant AWS Console access?]
  > NO

**Comment by jbritt1** [comment]
SOCKS access granted. @ltrombley please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.
