### ISSUE TITLE
Default to accessible

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#7417]
How might we make it easier for cross-discipline team members to think about and incorporate accessibility-thinking into their day-to-day work?

Let's use this venue to capture ideas across disciplines.

**Comment by LouCarlozo63** [comment]
For Content writers, a "cheat sheet" is always useful, and/or samples of Content that reflect "pre accessibility" and "accessibility incorporated" thinking.

**Comment by sshein** [comment]
Let's circle up on this at our leads meeting on Wednesday and get an update from Paul on how the engineers took things at his weekly. Also linking this doc here. https://docs.google.com/document/d/18kW9BUbkrGliCeXSnVXaDVb91xx7FZNsIaVNa6czUTE/edit#
