### ISSUE TITLE
First pass at invalid permissions alert

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#74179]
**Description:**  Now that we have the dashboard page has been created we need to take a first pass at what happens in the dashboard UI when a VSO logs in and does not have the required permissions to accept Power or Attorney. This will not the the final version of this UI, this is just a first pass so that we can get components in place such as the [alert](https://design.va.gov/components/alert) and some generic messaging.

Currently this will be based on checking the file with all of the VSOs and seeing if this VSO has the POA code as this is enough for the MVP. This will be done in a back end task and wired up later so no need to wire this up for the sake of this ticket.

_Note: for the final version of this UI we will need a mockup or some direction from design_

**User Story or Problem Statement:**  As a VSO I want to know as soon as possible if I don't have the needed permissions to accept Power of Attorney so that I can get the permissions needed as soon as possible.

**Implementation Details:** Since this is just a first pass at creating this UI we will simply be adding an alert component with some basic messaging as follows -

<img width="1007" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHZwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d7b1b72457bd44e5cdc1ecf8f420cf3391e5e3fe/Screenshot%202024-01-22%20at%203.16.29%20PM.png" alt="Screenshot 2024-01-22 at 3.16.29 PM.png" />

**Prerequisites/Dependencies:** None

**Blockers:**None

**Acceptance Criteria:**  
Behind the feature flag, this invalid permissions alert shows up on the page

**Automated Testing:** We will need a 100% test coverage as reported by `yarn test:coverage-app {app-name}` 

**Accessibility (A11y) Testing:** Since this is a first pass and will not be public, A11y testing is not required

**Comment by RivkaCGates** [comment]
@cohnjesse to update

**Comment by nihil2501** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-website/pull/27857)
