### ISSUE TITLE
Midpoint Review - IA Feedback - Employee Experience Team, 21-526EZ, Max CFI

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#74174]
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

 - Thanks for bringing this through the collab cycle! I loved the Codepen prototypes, and the two different options.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

### Consider

**Using R&S page template design on informational page** With the purple prototype that links out to a separate informational page, it sounds like there is a strong inclination to house this page in the [Resources and Support](https://www.va.gov/resources/) section of VA.gov (which is a great call!). Heading into user testing, you might consider updating the mockup for this page to include some of the standard page elements that all R&S pages have (breadcrumbs, search box at top, related content and tags at bottom). For folks who have used VA.gov often this might be a recognized page pattern.

**Comment by carodew** [comment]
@erinrwhite We've since updated the informational page with the content from CAIA, which uses the R&S template.
