### ISSUE TITLE
SOCKS access for Steven Cumming

### ISSUE THREAD

**Issue by stevenjcumming** [department-of-veterans-affairs/va.gov-team#74175]
### Your Name

Steven Cumming

### Your Email

steven.cumming@adhocteam.us

### Your Role and Team

Backend Engineer on Platform Reliability Team

### Product Manager (PM) name and email

Joe Tice joe.tice@oddball.io

### Product Owner (PO) name and email

Bill Chapman William.Chapman7@va.gov

### Access Type Requesting

platform

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDEyP0GDFkdqihfHZvmdh00KkzzJqdDzPuQKDomLuGGI2GqKSbNgNFSoNI46XQGCVnoFU89p/XInm1e59n6KjleTSRKT9jay/5Xu2PxeCHbM7/Alv4mexh1u50+86CaB075u+Fp6S/zaElAR5W8aX2XNpM0P5oJGnu2Mv1BkaovYp/mmMqKuDkIM5iOD4UW6yaP/Dyxs9AtBh7g8WnYJ4cXltettLk4NVmV+TctW7qrX88iZljuCeaLQngBUfcmCRKlcDbiiQqb5FyI5PXWI1kYYat/Loi1FAuhjs3fLgjeQRLBIqa0adwEhPckxyLWj/btAjYiqNoiBQcd/yyj/z1WqhfWeHbt2D7isp7NmvYydcpXRXmcOP67AkHIE12HLfLJH9d9FtQapaQ7h/UfgeZo8XGBYMnn9mrud/VIQ6OnaesAp7mATqcJ3+uQjLEXY5mBspmpYePGJ3yaIcQi2lPsg1Auf9Ccq8qVOeJe/i54JQPKe0sawZRT/nBhQazF56E= steven.cumming@stevencumming-CR2FCPQ90D

### E-QIP Transmittal Confirmation

<img width="889" alt="Screenshot 2024-01-22 at 3 13 44 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/134282106/e47bc5bf-6422-4b88-bc76-295c67528848">

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by barbarello** [comment]
@stevenjcumming  Access granted ✅ 

Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html 

Reach out in #vfs-platform-support if you have any trouble.
