### ISSUE TITLE
Check VSR list for POA code

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#74183]
Description: For the sake of the MVP we need to check the VSO file output by [this job](https://github.com/department-of-veterans-affairs/vets-api/blob/867f456072ebecabe3eb884fa12517b942006905/modules/veteran/app/sidekiq/veteran/vso_reloader.rb#L1-L7) that lists all of the VSOs when a user logs in and make sure that based on the information in the VSO file that user has the permissions needed to access our app. 

User Story or Problem Statement: As a VSO I want to ensure that I have the permissions needed to accept power of attorney on behalf of a Veteran so that I can help them get the services and benefits they need.

Implementation Details: In Rails after the user logs in but before they access the VSO dashboard we need to check if they have the code for POA and return `true` which means they have the permissions to accept power of attorney for a Veteran. Once we have this code in place the front end will make a call to this code when the Dashboard loads and check the returned value of the code from this ticket.

Mockups/Designs: N/A

Blockers: None at this time

Specifications: Detail the technical specifications required.

Acceptance Criteria: Specify criteria for ticket completion, including:

Testing Criteria: We need to test that this code returns `true` if the VSO has the POA code in the VSO file and `false` if they don't

Automated Testing:This code will need 100% code coverage

Accessibility (A11y) Testing: N/A

Documentation:TBD

**Comment by a6marinos** [comment]
No longer relevant .
