### ISSUE TITLE
Implement sign-in button functionality on Landing page

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#74185]
Description: We need to enable the sign-in button on the Landing page to link to the unified sign in page at /sign-in

User Story or Problem Statement: As a VSO I want to be able to log into the VSO portal so that I can accept or reject Veteran requests for me to be their power of attorney.

Mockups/Designs: N/A

Prerequisites/Dependencies: None at this time

Blockers: None at this time

Acceptance Criteria:
- A sign in button on the landing page now links to the unified sign in page

Testing Criteria: We need to test that this sign in works as intended

Automated Testing: This requires 100% test coverage as provided by the command `yarn test:coverage-app {app-name}`

Accessibility (A11y) Testing: As long as the sign in process works as intended this should meet the same A11y standard that login on VA.gov does

**Comment by nihil2501** [comment]
Draft [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/28225)
