### ISSUE TITLE
Access for Khalea Lester - VAMC-Upgrade team - GovernmentCIO

### ISSUE THREAD

**Issue by lealester** [department-of-veterans-affairs/va.gov-team#7418]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Request: Please provide SOCKS proxy access as this is required to complete support work on VAMC-Upgrade product.  Access needed for: dev, staging, prod,  CI environments and Jenkins.
- Please provide your Contracting Officer's Representative (COR) name.
   > Mary O'Toole
- Please provide your name.
   > Khalea Lester
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   >
Team: VSA-VAMC-UPGRADE / VAMC-UPGRADE
Role: {Senior Business Analyst}
Company: GovernmentCIO
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC8Ro4vTjwCLg0T8Q3IPHUVSC3/AYtoIQy8aubeFAIGKP9wCxxCZre+KSDJaJvZFdc0K1J3YZQwhIL0lWEJURA1mkiab8m6vhUsiOcLUNi4J6/y3MUsiIQ8gQQpBZniolFdWrNC9WH8wv/JB5bcgEI1LLHOTkml2Fx3E7uIRySVFeeFLCC+z4Vrfw8PD5AyEs0UN1ucRhPUJgukVW4JnOA478naHv4O401nkHqW8Nei07MLOziqqJz0XxaLJimlXU2l2BPjOilfkk3rues94+1JGzTycKmTesHE1WQPiI4+ITmcfkfN7wmZcXo+DV3FCfArmBb7S336uThLOEryUXxB6qw2u0tCYKth8JH1ZZhZp8lcGv7e8x9J+7f1qq3V251Moia4PzOlIk4SxlMXL1ixWaLknxVH5fyqWaCDbdir89FFzb4vND9/E9gJnLBaGZOB0RprSDcTntvxClwNrXdU1KdcWJQSi81sx4FhTW0YJ8HOwUWTRDQtul9uf7EOUHU= Khalea Lester@DESKTOP-J2RM8FV
```

- [Grant AWS Console access?]
  > NO
  >  Please give a brief description for why you are requesting AWS access.

**Comment by jbritt1** [comment]
SOCKS access granted. @lealester please continue with [the guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy) to establish a connection to SOCKS proxy.
