### ISSUE TITLE
Access for BarryEgbert

### ISSUE THREAD

**Issue by barryegbert** [department-of-veterans-affairs/va.gov-team#742]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Gregory Kirk
- Please provide your name.
   > Barry Egbert
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > By Light
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Engineering/Internal%20Tools.md#create-ssh-public-key) for instructions.
  > ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDD7PGPfkrCKaYBn5+Eugse8zhspqMdcqSw7/roCqncP7Li2Hp2iohZjFC/KgVGqFot9Vrt+Z1J1k7J9YG5QV+zLf/WefvB1rT/pppHb8wuHQDbQxTAA3/v4CfxIVnxeR+BAuRveqItGzrrBGxCu/m3EQvZjHQ6rgrgO1KNvvIr7wM/ntlr0K5CsXmfTNWtU88iqM916yWq9oXIHAuY1cmREavaEGEVyVwJgn+93E3gFdIRLG1j+iFBTXgdy5PAsztxBPbqVc5WAyFBVcXhywZojESqbraTGzHPLQGEUWFMzO0S3Dcck5DuannZ1geEYBss5NHS/2Y4fsv2J1BTqNIsrBinNhubpflgPFnSK2lQkXoFXD75k1fNtMceQ57oelJR0P2Mo0ISVCZXCmeN9LEehLwKWk+8OWFxr9KELDZBFTJmL1fzRz/OTDuUhgkd5QvLXxBcXdgfN63x65hNWFrwJe2OC/Mp+uuiU1OUWc8s6lUHCEFIorhgGdQGPNNTJHxFCUdRaWIUVMkSUjb/V5wzq9nHz25BYt9glY4EKA504ICaCk/tmtbJwGHDDQ9zEmESKBuzJsg4Nd+v7MiKlBftr831jL93G1a3LQ5SeoRbASQLBi9U3ubygWXtaFIFkwhKvhDMBHcw9F9O18idg4CeVN2l6LrxTMa9y8+C/DQDCQ== barry.egbert@va.gov

- [Grant AWS Console access?]
  > YES
  > Our infrastructure is hosted in and makes use of services in AWS GovCloud. This account is shared amongst many different
  > teams; changes made to resources in this account will affect many services. You will need access to AWS for troubleshooting, 
  > log file review and to apply changes to the running instances and services.

**Comment by barryegbert** [comment]
@department-of-veterans-affairs/vsp-operations please review my request. Thanks!

**Comment by b00klegger** [comment]
@department-of-veterans-affairs/vsp-operations 
Assigned and working today

**Comment by b00klegger** [comment]
@department-of-veterans-affairs/vsp-operations testing comments

**Comment by b00klegger** [comment]
@Jeff-Hayter 
COR: Gregory Kirk
User: Barry Egbert

**Comment by b00klegger** [comment]
@barryegbert 
`ssh` key added to infrastructure. You should be clear to continue with onboarding and setting up SOCKS proxy access. 

AWS Console login will be sent separately; awaiting verification.

**Comment by Jeff-Hayter** [comment]
@b00klegger Confirmed, please grant access.

**Comment by b00klegger** [comment]
@barryegbert 
AWS account setup and login details provided separately. Please reopen issue and provide any details if difficulty logging in.
