### ISSUE TITLE
Remove flipper from database in production

### ISSUE THREAD

**Issue by mjknight50** [department-of-veterans-affairs/va.gov-team#74203]
We've removed a flipper from production but do not have access to the console to run this:
`Flipper.remove(:pension_claim_submission_to_lighthouse)`

This is not urgent and can be done anytime.

**Comment by tblackwe** [comment]
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/7817263/c4332d47-d5da-427e-89a7-578118fe1edd)
