### ISSUE TITLE
Create secure Sharepoint folder for participant PII

### ISSUE THREAD

**Issue by RenataKeck** [department-of-veterans-affairs/va.gov-team#74232]
Participant information must be kept secure on VA Sharepoint. The file in Sharepoint needs to include demographic and contact information pulled from the recruitment intake form, as well as columns for dates when the participant tested. This will be used to ensure we are not running consecutive tests with the same participants. 

**Output**

- [x] Export participant signups from Google Form as a .csv
- [x] Create a subfolder within the Accredited Rep Sharepoint for participant data, create a password for the folder (or make it invite-only for Design team)
- [x] Upload the participant information and clean up the file. If possible, password-protect the file
- [x] Share the password with the Design team and project leadership

**Resources**
- [Recruitment intake](https://docs.google.com/forms/d/1COC4LzpflQdz4D5UNcNXUv_ej6vdg7LeYlilxoBLlqo/edit)
- [Participant management doc](https://dvagov.sharepoint.com/:x:/r/sites/vaabdvro/Shared%20Documents/Accredited%20Representative%20Facing/Research/Recruiting/Accredited%20Representative%20Feedback.csv?d=wa913e187660045019f9e8465df5c49b6&csf=1&web=1&e=ajtyvJ)

**Acceptance criteria**
- Participant info file has been reviewed and is cleaned up
- Sharepoint subfolder and file are password-protected
- Passwords have been shared within the immediate team

**Comment by hdbaines** [comment]
most likely will need to pull into next sprint

**Comment by RenataKeck** [comment]
Folder and spreadsheet have been created, waiting on determination from enablement re: password protection.

**Comment by RivkaCGates** [comment]
@RenataKeck what was the decision on password from enablement? And can you toss a link to the folder in the comments.

**Comment by RenataKeck** [comment]
Folder is [here](https://dvagov.sharepoint.com/:f:/r/sites/vaabdvro/Shared%20Documents/Accredited%20Representative%20Facing/Research/Recruiting?csf=1&web=1&e=I5pUGL). A direct link to the password-protected participant spreadsheet and the intake form are in the main body of the ticket. I've included a PDF of our recruitment strategy document in the Sharepoint folder.
