### ISSUE TITLE
AWS access for [Annie Tran]

### ISSUE THREAD

**Issue by anniebtran** [department-of-veterans-affairs/va.gov-team#74238]
### COR Name

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative Name

Other - please specify in 'Additional Notes'

### Your Name

Annie Tran

### Your Email

annie.tran@coforma.io

### Team, Role, and Company of the target individual

Benefits Decision Reviews, Senior Software Engineer, Coforma

### Product Manager (PM) name and email

Sade Ragsdale, sade@coforma.io

### Product Owner (PO) name and email

Zach Goldfine, zachary.goldfine@va.gov

### Desired AWS Access

I joined the VA Benefits team 1 (Decision Reviews) a few months ago and need a [similar level of access](https://github.com/department-of-veterans-affairs/va.gov-team/issues/46302) to @data-doge (Eugene Lynch) in order to develop features and investigate bugs on the vets-api and vets-website apps. Thanks!

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/14334046/fe7bf66a-87f8-45eb-ae50-78660275da2d)

### Additional Notes

COR: Keith Riley
VOR: Jeff Langworthy

I will need ongoing access in order to help triage bugs

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [x] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [x] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [x] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [x] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by saderagsdale** [comment]
Requested Atlassian access to I can check the team roster.

**Comment by bdech** [comment]
Confirmed user in Atlas. E-QIP confirmed.

**Comment by HeatherWidmont** [comment]
@saderagsdale posted a ticket in platform support. @anniebtran to check to see if she has access

**Comment by saderagsdale** [comment]
Waiting for Keenan to update us. Might depend on his PIV access.

**Comment by anniebtran** [comment]
I've got access now 🙌  

Links to support threads for future reference:
- [Getting AWS account](https://dsva.slack.com/archives/CBU0KDSB1/p1707243503071179)
- [Troubleshooting turning on MFA/permissions issues](https://dsva.slack.com/archives/CBU0KDSB1/p1707752765186779)
