### ISSUE TITLE
[Product] Product Guide for Letters app for Call Center

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#74269]

**Comment by SilkeDannVA** [comment]
@jacobworrell to mark done

**Comment by jstrothman** [comment]
[Benefits Letters Product Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/product-guide/VA%20Benefits%20Letter%20Product%20Guide.docx)
