### ISSUE TITLE
Usability Prep review- Content review - Medical device reordering

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#7426]
## Usability Prep Review

VSP Content feedback on Medical reordering device form

Template prototype we're reviewing: https://vsateams.invisionapp.com/share/6MVTG94WNH5#/screens/403659915/comments

## Acceptance criteria

- [x]  Peggy provide content feedback
- [x]  Product team incorporates feedback into prototype or syncs with Peggy on any questions
- [x]  Peggy reviews prototype after content feedback has been incorporated

**Comment by peggygannon** [comment]
@becca my feedback is in the mockup. Let me know if you have any questions. Let me know when you've incorporated my recommendations, and I'll check the mockup again. 

Thanks.

**Comment by rebeccawalsh** [comment]
Hey @peggygannon - I think I updated the mockups with all of your content changes aside from leaving the additional info component for ineligible items. We heard everybody's feedback on this component's existence, and we will change it in the near future, but we think there will be greater user feedback that will make this smaller change null anyway. 

 Please take a look at the rest of the comments and let me know if we're good to go, but don't resolve the comments as we'll use them to update our GH pages and for development direction. Thank you!

**Comment by peggygannon** [comment]
Hi, @rebeccawalsh thank you. I just checked the mockup and all looks good.

I added 2 additional comments for you (one a question, and one a fix to a typo that I did.. sorry!)

I think the Usability Prep content review is complete and will close this issue.
