### ISSUE TITLE
Flipper UI access for Scott Regenthal

### ISSUE THREAD

**Issue by freeheeling** [department-of-veterans-affairs/va.gov-team#74265]
### Your Name

Scott Regenthal

### Your GitHub handle (Flipper UI access is managed through GitHub)

@freeheeling

### Team, Role, and Company of the target individual

Disability Experience 2 (team Carbs), Software Engineer, Oddball

### Please confirm if you are on Atlas, Platform Team Roster or are a Federal User

- [X] [Atlas](https://dev.va.gov/atlas)
- [X] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [X] Lesser Environments (Dev/Staging/Sandbox)
- [X] Production (if requesting, justify prod access below)

### Reason for Production Access (If requested)

Access needed to enable pre-existing `form526_backup_submission_force_offramp` feature on production in support of sending metadata along with a form 526 submission that indicates it needs to be off-ramped from automation. This helps the VBA OBI intake (mail portal) team appropriately route the form to a person.

**Note:** I am unable to access [Atlas](https://dev.va.gov/atlas) or [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster) to confirm whether I am listed on either. It appears that the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665), on which I am listed, used be included on this issue template.

**Comment by bdech** [comment]
Hey Scott, the VFS Team Roster was deprecated and replaced with Atlas. With that being said, I've confirmed you're in Atlas.

**Comment by bdech** [comment]
E-QIP found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/71263)

**Comment by bdech** [comment]
@freeheeling You've been granted access to `production` and `lesser` environments.
