### ISSUE TITLE
Eligibility Rules for Display of Veteran status

### ISSUE THREAD

**Issue by matt4su** [department-of-veterans-affairs/va.gov-team#74260]
As the VA I want the Veteran status info conditionally displayed on the Military information page based on eligibility rules so that I may manage who is provided access to discounts and non VA benefits

Acceptance criteria:
1.  Veteran must be honorably discharged
2.  Veterans discharge status must be known
3.  Veteran must have at least one period of service history
4.  When all eligibility criteria are met Veteran status info is displayed on the Profile/Military Information page on VA.gov
5.  When eligibility requirement are not met Veteran status info is not displayed on the Profile/Military Information page on VA.gov and there is no additional explanatory verbiage.
6.  When eligibility requirements are met we are able to measure the total, unique and returning users to the page.

**Comment by liztownd** [comment]
#6 is built into the site already, all page views are automatically counted.
