### ISSUE TITLE
Design consistent footer for IPP Intake application

### ISSUE THREAD

**Issue by skirkman16** [department-of-veterans-affairs/va.gov-team#74283]
**Problem:**

We will need updated footer content for the IPP applications. 

What content should be in the footer? (Do we need a footer?)

**User Story**
When I access the Veteran Intake app or the Proofing Agent application, I need to see a consistent footer with accurate information, so I am not confused and so I do not contact support numbers that cannot help me with the applications

<img width="1469" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3I5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eb92dc90355988b76270717b390606049c15413b/Screenshot%202024-01-25%20at%201.25.17%20PM.png" alt="Screenshot 2024-01-25 at 1.25.17 PM.png" />

**Acceptance Criteria:**
Pre-pilot
- remove any phone numbers for both Intake and PA
- remove email address for both Intake and PA
- ensure footer is the same on all screens for both Intake and PA

Notes:
- should use login.gov components, even if left empty
- can use VA.gov logo

Future considerations:
Post-pilot
- privacy policies
- support information

**Comment by skirkman16** [comment]
Login does not have any footer components that we can use but @JKG199 and I found a component in the VADS

**Comment by skirkman16** [comment]
<img width="1127" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHM2QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--728a43cfb63b39f2086fa791eaf0bab1ed73a76c/Screenshot%202024-02-07%20at%208.41.14%20AM.png" alt="Screenshot 2024-02-07 at 8.41.14 AM.png" />
Example of VADS footer component on our landing page

**Comment by SophiaPhilipMO** [comment]
https://www.figma.com/proto/PfrWKmxiQ5RjChwx6I18QE/IPP-Prototypes?page-id=2576%3A2274&type=design&node-id=2586-3102&viewport=523%2C541%2C0.17&t=0whsHtwcJdAqIWoo-1&scaling=scale-down

**Comment by SophiaPhilipMO** [comment]
https://design.va.gov/components/footer/footer-minimal

**Comment by SophiaPhilipMO** [comment]
Updating landing page with white background. Footer is good to go <img width="1125" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelZDQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d28600667c92ce704efc3877b279639fa3d58d4c/Intake%20Option%204.png" alt="Intake Option 4.png" />
