### ISSUE TITLE
VA Date Stamp at the top of PDF is missing

### ISSUE THREAD

**Issue by aplatt-coforma** [department-of-veterans-affairs/va.gov-team#74291]
Steps:
1. start an online Pension application
2. enter minimal info
3. submit the form
4. Grab the generated PDF and review the VA Date Stamp at the top of the PDF

Expected: Should display the same date that is shown at the end of the form for Date Signed
Results: The VA Date Stamp box is blank
<img width="1021" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVB3QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--85461b0c8d5f05c6624900705d744a50fa654387/Screenshot%202024-01-23%20at%2011.10.13%E2%80%AFAM.png" alt="Screenshot 2024-01-23 at 11.10.13 AM.png" />

**Comment by aplatt-coforma** [comment]
Linking https://github.com/department-of-veterans-affairs/va.gov-team/issues/71456 to this ticket. 
From past discussion here's the current behavior:

> date stamp is bottom left of every page, and "FDC Reviewed - va.gov Submission" is on the top right of every page. This behavior is default and I believe i sent this over to Emily already and received no complaints, so figured it was alright to proceed.

**Comment by emilytheis** [comment]
sorry for the confusion on this one @aplatt-coforma and @vbellissimo --you're right that the datestamp is at the bottom and i already said yes to that! okay to remove this from the launch-blocking bugs

**Comment by aplatt-coforma** [comment]
Thanks for the confirmation @emilytheis. Closing this ticket.
