### ISSUE TITLE
Possible broken connection to Vet360 API in lower environment(s)

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#743]
### Status

UNRESOLVED

### Severity Analysis

Probably sub-`sev 3`. Not urgent, but would be good to fix on our end to help future QA testing done by one of our partners.

### User Impact 

- *Who is the user impacted by this problem?*
QA testers on the Vet360 team.

- *How does this problem affect the user?*
QA testers are unable to test Vet360 changes that are deployed in their lower environments through VA.gov.

### Description

The Vet360 team will deploy a major release of their API in the immediate future (API consumers, like VA.gov, will not see any impact to API behavior). To verify that no functional regression had occurred, the Vet360 team deployed the major release in their INT environment and attempted QA testing in the corresponding VA.gov environment via dev.va.gov, per our [integration documentation](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/f1d9e9305d55bb528e208af5ad8f2da1f79b5a9f/Practice%20Areas/Engineering/Data/Data-Services/Vet360/README.md#environment-map). The Vet360 QA team was unable to verify that requests originating from VA.gov were making it through to their INT environment, preventing them from further testing.

### Steps to Reproduce

1. Connect with a Vet360 engineer. See the [#vet360](https://dsva.slack.com/messages/C7TE0PFTL) channel and ask them to monitor logs in their INT environment.
1. Log into dev.va.gov using ID.me staging credentials.
1. Navigate to [contact info section of Profile](https://dev.va.gov/profile/#contact-information).
1. Toggle an edit modal for one of the fields, change a value, and click `Update`.
1. Determine whether the request made it back to the Vet360 INT environment.

#### Expected Results

The request propagates from the client, to vets-api, and onward to int.vet360.va.gov where it is properly handled.

#### Actual Results

No request hits int.vet360.va.gov.

### Further Details
None available.

### Proposed Solution
Before anything else, verify that our DEV and their INT intended to be connected. If so, investigate a possible broken connection. If not, work with the Vet360 team to update our [documentation](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/f1d9e9305d55bb528e208af5ad8f2da1f79b5a9f/Practice%20Areas/Engineering/Data/Data-Services/Vet360/README.md#environment-map) as well as take the appropriate steps to establish a reliable method of Vet360-initiated integration testing with one of our lower environments.

**Comment by alexpappasoddball** [comment]
@kfrz Lets chat about this one when you get back Monday.  Heard back from tools and improvement and they don't think it falls under them so lets get some clarity and get this one a home.

**Comment by wyattwalter** [comment]
Looks like this was a result of us having hardcoded IPs in the forward proxy that pre-dated our connectivity in VAEC. The int.vet360.va.gov DNS response is now different. Because we didn't have the updated address, we also didn't notice that the health check on the migrated systems had also changed. I found that they needed a new header set that's not present for their `qa` or `www` as well. We'll need to change these over soon to avoid issues in our staging and prod, and coordinate what the header should be for those environments.

**Comment by wyattwalter** [comment]
@batemapf I believe this is resolved in dev now. I'm not sure who brought this up with you, but can you have them test again? If it doesn't work, we can setup some time to debug this as I believe it is correct that dev.va.gov is connected with their int environment.

**Comment by brandonrapp** [comment]
@alexpappasoddball - @wyattwalter investigated it a bit further and thinks that it makes sense for the operations team to handle this. I am going to move it over now.

**Comment by batemapf** [comment]
@lkoenigsberg the vet360 backend is fixed up in dev now if you'd like to test things out with the v360 team. if everything looks good and you don't need additional assistance, please close this ticket. thanks!

**Comment by Justin-Pickett** [comment]
@erikphansen or @lihanli can you take a look at this when you get a chance.

**Comment by Justin-Pickett** [comment]
@erikphansen  or @lihanli  can you take a look at this when you get a chance.

**Comment by lihanli** [comment]
```
$ curl https://internal-dsva-vagov-dev-fwdproxy-1893365470.us-gov-west-1.elb.amazonaws.com:4433/sba/info
<html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>

$ curl https://int.vet360.va.gov/sba/info
{"vet360-config":{"artifact":{"version":"1.0.6-SNAPSHOT","artifactId":"vet360-config","name":"vet360-config","description":"Vet360 Config Tools"},"build":{"branch":"development","timestamp":"2019-08-21 17:27:48","revision":"b117ac1e6418b2d0593dda5a3e32136e110569f8","buildServerBuildNumber":"268"}},"vet360-zuul-service":{"artifact":{"version":"2.2.0","artifactId":"vet360-zuul-service","name":"vet360-zuul-service","description":"Vet360 Zuul Service"},"build":{"branch":"development","timestamp":"2019-08-22 18:34:38","revision":"d0e716b96c7d2e02d8be2959fbb04fdeef7133d3","buildServerBuildNumber":"7"}},"mdm-cuf-core":{"artifact":{"version":"3.0.2","artifactId":"mdm-cuf-core","name":"mdm-cuf-core","description":"The Master Data Management (MDM) Common Update Framework (CUF) is the intended technique for updating, mastering and synchronizing data within the VA. The VA's MDM CUF is a modernized version of the CUF originally implemented and still in usage at the DoD, customized to address the unique needs of the VA. The MDM CUF Core is a collection of libraries, patterns, documentation, standards, etc. considered as product/framework that is intended to (1) kickstart development of data and data synchronization/mastering services within the VA and (2) ensure consistent implementations of such services."},"build":{"branch":"development","timestamp":"2019-08-22 17:47:51","revision":"cc6ae84d8cdab34f23708b4aebf65e8234e2d876","buildServerBuildNumber":"10"}}}

**Comment by tskinn** [comment]
This should be fixed with https://github.com/department-of-veterans-affairs/devops/pull/5489

**Comment by Justin-Pickett** [comment]
@erikphansen check and see if dev should be calling Vets360.

**Comment by erikphansen** [comment]
Gonna close this one now as https://github.com/department-of-veterans-affairs/va.gov-team/issues/1762 was created to wire up `dev.va.gov` to the backend and the work was done in https://github.com/department-of-veterans-affairs/vets-website/pull/10737
