### ISSUE TITLE
AWS Access for Service Integrated Teams 

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#7430]
When DevOps-alike team members from outside VSP need access to AWS, we give them the same role that VSP-Operations gets, which is effectively blanket admin on everything in the account.  This is more than they need and creates operational and security risk for VSP and the other projects that share this account.

We would like to limit this access to a reasonable amount of access for just that teams stuff, with a trend to no write access to AWS directly for most folks.  (Note that read access via the console is still very useful for most things, 

The easiest way to do this is to some tooling between the cloud the user in order to allow them to make changes and see the info they need.  Much of this we'll do with other efforts:
- Logging move away from cloud watch will remove a large number of folks who need aws access just for that
- Forcing all changes to teraform to be run through atlantis gives a singular change method and allows for others to affect change without needing aws write creds directly because atlantis mediates that
- Moving execution to containers gives us a separate access method to enter the runtime environment so cli access can be given without needing to access a aws node directly via ssm (and asg detachment)

That said, Service Integrated Teams (eg: those which have an additional serviced running on the VSP in addition to api+website) will still need additional touch access to their resources for debugging and support purposes.  

We need to come up with a pattern that allows these resources to be identified (tags?) and access given through an IAM policy and creds mediated though vault (possibly using dynamic roles as part of group identity).

**Comment by ricetj** [comment]
Need to come back to this after Infra recommit

**Comment by jbritt1** [comment]
I feel the goals here align well with what our future infrastructure will provide @jhouse-solvd, do you want to close this one in lieu of those initiatives? Or hold on to this one and make references between it and our ticket(s) around the new infrastructure that will likely hit these targets?

**Comment by jbritt1** [comment]
Bump @jhouse-solvd

**Comment by jbritt1** [comment]
Bump @jhouse-solvd

**Comment by jbritt1** [comment]
Bump @jhouse-solvd

**Comment by jhouse-solvd** [comment]
FYI, to comment on some of TJ's points above: 

- Ops has implemented centralized logging w/ Loki, which developers can access through Grafana
- Ops is in the process of moving to container orchestration using EKS, and re-designing code integration and deployment practices as part of this effort 
- there is a current iteration of an initiative to address user credentials, which will include a re-org of IAM security groups and policies, [HERE](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/19478)

This can be closed.
