### ISSUE TITLE
(UX) 10-10EZR: Design TERA questions and workflow

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#74303]
As a Veteran who slept next to burn pits in Iraq, I would like to be asked about my Toxic Exposure so that I can potentially get my priority group upgraded.

- [x] Review mock-ups Jessie sent (attached--attached EZ just for reference)
- [x] Determine what questions we would like to ask (e.g. 3. A-E)
- [x] Determine where in the EZR flow these questions should live
- [x] Design these questions and any helper text (e.g. helper text that lists all the countries)
- [ ] **Success: We have designs for the new TERA questions and we know where in EZR they will live**

[VA Form 10-10EZ.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1B3QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--39a62b7da1ef7d630d37b2b7bc26bb5c4bd3b44a/VA%20Form%2010-10EZ.pdf)
[VA Form 10-10EZR (5).pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1R3QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3931e63e5bcfe4bfa7796c9d2dad13677e8a91db/VA%20Form%2010-10EZR%20%285%29.pdf)

**Comment by katelyncai** [comment]
Other than final content tweaks or potential paper form changes (which we will monitor), this work is complete.
- [Designs](https://www.figma.com/file/tggcJk382w9yQ0ElwKfh3N/10-10EZR?type=design&node-id=1405%3A60260&mode=design&t=CYdJxSuv6Khdy4WJ-1) for MVP version of TERA on EZR
- [TERA data exploration](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1699473497914/86412743291c286587ff315e52549e98e06ba534?wid=197-1707324356004) on MURAL
