### ISSUE TITLE
[CST] Basic DataDog logging, dashboards, and monitors for CST endpoints

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#74308]
## Value Proposition

As a developer, I want basic logging, dashboards, and monitors for the Claim Status Tool (CST) endpoints, to help me gauge and report on the health and usage of the CST, and respond to errors and anomalies stemming therefrom.

## Background

The goal of this ticket is to create _basic_ dashboards and monitors in DataDog, for the CST, that we can later iterate on in https://github.com/department-of-veterans-affairs/va.gov-team/issues/74309. Additionally, we will create follow up tickets for more specific inquiries (e.g. tracking claim type - EP code pairs; tracking the most common kinds of tracked items).

## Considerations

- The StatsD logs listed below are likely provided by DataDog, as rack metrics.
- Many CST dashboards already exist, so to some extent, this ticket may involve finding what's already there and making small updates.
- Don't worry about fine-tuning the monitors listed below. We can do that in https://github.com/department-of-veterans-affairs/va.gov-team/issues/74309. For this ticket, err on the side of over-inclusivity. Better to have false positives but no false negatives, than to have the opposite.
- We will create follow up tickets for more specific inquiries (e.g. tracking claim type - EP code pairs; tracking the most common kinds of tracked items).

### GET benefit claims endpoint
- Find or create StatsD logs for:
  - [x] Successes on the Lighthouse endpoint.
  - [x] Errors on the Lighthouse endpoint.
- Create or update widgets for the CST dashboard(s) visualizing:
  - [x] Each of the above StatsD logs.
  - [x] HTTP status codes on the endpoint.
  - [x] Latency on the endpoint.
  - [x] Error logs stemming from the endpoint (which include identifying information that can be used to investigate errors and potentially flag them to the call center).
- Find, create, or update the following [monitors](https://vagov.ddog-gov.com/monitors/manage?q=letters&order=desc) in DataDog, each one posting to `benefits-management-tools-notifications` Slack channel:
  - [x] Anomalous traffic volume (based on successful requests to the LH endpoint).
  - [x] Low traffic volume (using a lower threshold based on historical lows over the past several months).
  - [x] Anomalous latency on the LH endpoint.
  - [x] High error count (using an upper threshold based on historical acceptable baseline error counts).

### GET appeals endpoint
- Find or create StatsD logs for:
  - [x] Successes on the endpoint.
  - [x] Errors on the endpoint.
- Create or update widgets for the CST dashboard(s) visualizing:
  - [x] Each of the above StatsD logs.
  - [x] HTTP status codes on the endpoint.
  - [x] Latency on the endpoint.
  - [x] Error logs stemming from the endpoint (which include identifying information that can be used to investigate errors and potentially flag them to the call center).
- Find, create, or update the following [monitors](https://vagov.ddog-gov.com/monitors/manage?q=letters&order=desc) in DataDog, each one posting to `benefits-management-tools-notifications` Slack channel:
  - [x] Anomalous traffic volume.
  - [x] Low traffic volume (using a lower threshold based on historical lows over the past several months).
  - [x] Anomalous latency on the endpoint.
  - [x] High error count (using an upper threshold based on historical acceptable baseline error counts).

### GET stem claims endpoint
- Find or create StatsD logs for:
  - [x] Successes on the endpoint.
  - [x] Errors on the endpoint.
- Create or update widgets for the CST dashboard(s) visualizing:
  - [x] Each of the above StatsD logs.
  - [x] HTTP status codes on the endpoint.
  - [x] Latency on the endpoint.
  - [x] Error logs stemming from the endpoint (which include identifying information that can be used to investigate errors and potentially flag them to the call center).
- Find, create, or update the following [monitors](https://vagov.ddog-gov.com/monitors/manage?q=letters&order=desc) in DataDog, each one posting to `benefits-management-tools-notifications` Slack channel:
  - [x] Anomalous traffic volume.
  - [x] Low traffic volume (using a lower threshold based on historical lows over the past several months).
  - [x] Anomalous latency on the endpoint.
  - [x] High error count (using an upper threshold based on historical acceptable baseline error counts).

### POST submit 5103
- Find or create StatsD logs for:
  - [x] Successes on the Lighthouse endpoint.
  - [x] Errors on the Lighthouse endpoint.
- Create or update widgets for the CST dashboard(s) visualizing:
  - [x] Each of the above StatsD logs.
  - [x] HTTP status codes on the endpoint.
  - [x] Latency on the endpoint.
  - [x] Error logs stemming from the endpoint (which include identifying information that can be used to investigate errors and potentially flag them to the call center).
- Find, create, or update the following [monitors](https://vagov.ddog-gov.com/monitors/manage?q=letters&order=desc) in DataDog, each one posting to `benefits-management-tools-notifications` Slack channel:
  - [x] Anomalous traffic volume (based on successful requests to the LH endpoint).
  - [x] Low traffic volume (using a lower threshold based on historical lows over the past several months).
  - [x] Anomalous latency on the LH endpoint.
  - [x] High error count (using an upper threshold based on historical acceptable baseline error counts).

### POST submit files
- Find or create StatsD logs for:
  - [x] Successes on the Lighthouse endpoint.
  - [x] Errors on the Lighthouse endpoint.
- Create or update widgets for the CST dashboard(s) visualizing:
  - [x] Each of the above StatsD logs.
  - [x] HTTP status codes on the endpoint.
  - [x] Latency on the endpoint.
  - [x] Error logs stemming from the endpoint (which include identifying information that can be used to investigate errors and potentially flag them to the call center).
- Find, create, or update the following [monitors](https://vagov.ddog-gov.com/monitors/manage?q=letters&order=desc) in DataDog, each one posting to `benefits-management-tools-notifications` Slack channel:
  - [x] Anomalous traffic volume (based on successful requests to the LH endpoint).
  - [x] Low traffic volume (using a lower threshold based on historical lows over the past several months).
  - [x] Anomalous latency on the LH endpoint.
  - [x] High error count (using an upper threshold based on historical acceptable baseline error counts).

### GET letters (DDL)
- Find or create StatsD logs for:
  - [x] Successes (VBMS)
  - [x] Errors (VBMS)
- Create or update widgets for the CST dashboard(s) visualizing:
  - [x] Each of the above StatsD logs.
  - [x] HTTP status codes on the endpoint.
  - [x] Latency on the endpoint.
  - [x] Error logs stemming from the endpoint (which include identifying information that can be used to investigate errors and potentially flag them to the call center).
- Find, create, or update the following [monitors](https://vagov.ddog-gov.com/monitors/manage?q=letters&order=desc) in DataDog, each one posting to `benefits-management-tools-notifications` Slack channel:
  - [x] Anomalous traffic volume.
  - [x] Low traffic volume (using a lower threshold based on historical lows over the past several months).
  - [x] Anomalous latency.
  - [x] High error count (using an upper threshold based on historical acceptable baseline error counts).

### GET download letter (DDL)
- Find or create StatsD logs for:
  - [x] Successes
  - [x] Errors
- Create or update widgets for the CST dashboard(s) visualizing:
  - [x] Each of the above StatsD logs.
  - [x] HTTP status codes on the endpoint.
  - [x] Latency on the endpoint.
  - [x] Error logs stemming from the endpoint (which include identifying information that can be used to investigate errors and potentially flag them to the call center).
- Find, create, or update the following [monitors](https://vagov.ddog-gov.com/monitors/manage?q=letters&order=desc) in DataDog, each one posting to `benefits-management-tools-notifications` Slack channel:
  - [x] Anomalous traffic volume.
  - [x] Low traffic volume (using a lower threshold based on historical lows over the past several months).
  - [x] Anomalous latency.
  - [x] High error count (using an upper threshold based on historical acceptable baseline error counts).
## Acceptance Criteria
- [x] Each of the widgets and monitors described above exist.
- [x] A link to the dashboard, and links to each monitor have been added to https://docs.google.com/document/d/1OoX2aF5JMJLa0KVQqOiatiZy5YIfhJgL2zdGesYxbbE/edit. 

## Definition of Ready
N/A.

## Definition of Done
- [ ] Acceptance criteria met.

**Comment by jerekshoe** [comment]
I would look at [this dashboard](https://vagov.ddog-gov.com/dashboard/uc8-jnr-zhm/benefits---claim-status-tool?refresh_mode=sliding&view=spans&from_ts=1706119728526&to_ts=1706134128526&live=true) to see if anything is covered by it already. I'll try and post some others as I find them

**Comment by data-doge** [comment]
Thanks @jerekshoe 🙏

**Comment by HeatherWidmont** [comment]
@samcoforma cleaning this up & sharing it with @jerekshoe today

**Comment by HeatherWidmont** [comment]
@samcoforma & @data-doge met to discuss how to quiet the noise

**Comment by HeatherWidmont** [comment]
Validation session this afternoon. After the discussion today, will switch over to the fine-tuning ticket

**Comment by HeatherWidmont** [comment]
@samcoforma & @data-doge to meet today to see if they can check all the boxes as a "final review"

**Comment by samcoforma** [comment]
Link to dashboard can be found here: https://docs.google.com/document/d/1OoX2aF5JMJLa0KVQqOiatiZy5YIfhJgL2zdGesYxbbE/edit

**Comment by HeatherWidmont** [comment]
@jerekshoe to validate this on Monday or Tuesday

**Comment by HeatherWidmont** [comment]
@jerekshoe will validate today
