### ISSUE TITLE
Request access to Google Analytics and/or Domo

### ISSUE THREAD

**Issue by goelsunaynaVA** [department-of-veterans-affairs/va.gov-team#74302]
# Request Google Analytics and/or Domo access

## What this form is for
Use this template to request access to Google Analytics and/or Domo. Please complete steps 1 & 2 below. 

## 1. Access Requirements 
Please check the analytics tool(s) you need access to:

**- [* ] Google Analytics**

**- [* ] Domo**

## 2. User Email Address to Receive Access 
**Due to privacy concerns, please do not put your email in this ticket.** Instead please use `/support` on the DSVA Slack channel [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support), select `Analytics` in the "I need help from" dropdown, and then add in the `Summary of request` section: 
 1. This issue's link 
 2. Emails that need access

_Please note: For Google Analytics, if the user has a VA.gov email address or does not yet have a Google account, they will need to create one by visiting [this link](https://accounts.google.com/signup/v2/webcreateaccount?continue=https%3A%2F%2Faccounts.google.com%2FManageAccount&gmb=exp&biz=false&flowName=GlifWebSignIn&flowEntry=SignUp). Once at that link, VA.gov users and external users with email accounts that are not Google based should select the option "Use my current email address instead"._

_Please list any additional requirements, if any (i.e. edit access). If you are requesting BigQuery access, please share if you will be hooking up an API._

_Once you receive access, you should receive a confirmation email directly from Google or Domo._

 
---

### Definition of Done
- [ ] Provide access to user

**Comment by Blivaditis** [comment]
Neither of those emails are linked to Google. On the ticket you submitted there are instructions on how to link existing accounts to google. Once the accounts are linked please let me know and I can provide access.

**Comment by goelsunaynaVA** [comment]
Hello,

Thank you for your reply. When go to link my account, I get the message that its already taken. Please see the screen shot below and advice accordingly.
Sunayna Goel

***@***.***

From: Blivaditis ***@***.***>
Sent: Wednesday, January 24, 2024 10:41 AM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Goel, Sunayna N. (liberty It Solutions, Llc) ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Request access to Google Analytics and/or Domo (Issue #74302)


Neither of those emails are linked to Google. On the ticket you submitted there are instructions on how to link existing accounts to google. Once the accounts are linked please let me know and I can provide access.

-

**Comment by Blivaditis** [comment]
Your email address is linked and I can give you access how ever the second email is still receiving errors.

**Comment by Blivaditis** [comment]
I Invited both emails to Domo and only yours to Google Analytics for the time being.

**Comment by Blivaditis** [comment]
Any updates on getting that email connected? If not I am going to close out the ticket.

**Comment by goelsunaynaVA** [comment]
Yes, it all worked out. Thanks.

Sunayna Goel

From: Basil Livaditis ***@***.***>
Sent: Thursday, February 15, 2024 2:16 PM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Goel, Sunayna N. (liberty It Solutions, Llc) ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Request access to Google Analytics and/or Domo (Issue #74302)


Any updates on getting that email connected? If not I am going to close out the ticket.

-
