### ISSUE TITLE
Investigate why Veterans Service Officers data is not appearing in Staging

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#74336]
## Summary
Over in https://github.com/department-of-veterans-affairs/va.gov-team/issues/73867 we processed the most recent Trexler File, however Staging is still throwing an error when searching for Veteran Service Officers.  

Per https://github.com/department-of-veterans-affairs/va.gov-team/issues/73253, we should be parsing the representatives sheet in the Trexler File to support VSOfficers

## Expected vs. Actual
**Expected**: Selecting rep type "Veterans Service Officers" returns search results of nearby VSOs

**Actual**: Selecting rep type "Veterans Service Officers" returns an error

## Steps to Reproduce
1. Select Type of accredited representative = Veterans Service Officers
2. Enter a location
3. Hit Search, error appears

## Examples
<img width="1011" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHp5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5ce735361770ce1a9a87780bb2006aceff43ada4/image.png" alt="image.png" />

**Comment by holdenhinkle** [comment]
It appears that the job didn't run. The code works 100%. I just ran it manually and it's updating all the records now:

<img width="1484" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMllSQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--48b83a85ec139bab7f26c006f332e893d50c3d65/image.png" alt="image.png" />

Also, this:
<img width="1989" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmdSQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--183c42d18e9d3b94d2740a30b2c8394215b1afed/image.png" alt="image.png" />

**Comment by holdenhinkle** [comment]
Yeah, it didn't run. It's because I changed the namespacing for the job.

It used to be `RepOrgAddresses`

But we dropped orgs and I updated the namespacing to `RepAddresses`

Updating the job now...

**Comment by holdenhinkle** [comment]
PR - https://github.com/department-of-veterans-affairs/vets-api/pull/15316
