### ISSUE TITLE
Accept claims agent as a type in the request and handle that in the search and response

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#74335]
## Background
When the frontend requests claims agents (https://github.com/department-of-veterans-affairs/va.gov-team/issues/74330) the backend will need to handle that request in the search and response

Some work was done here to remove claims agents previously, could be a helpful reference https://github.com/department-of-veterans-affairs/va.gov-team/issues/71816

## Tasks
- [x] Accept claims agent as a type in the request and handle that in the search and response

**Comment by holdenhinkle** [comment]
PR - https://github.com/department-of-veterans-affairs/vets-api/pull/15322

**Comment by holdenhinkle** [comment]
Done
