### ISSUE TITLE
[MVP] Ensure all data is mapping correctly to PDF for Section 10/Care Facility Expenses & Other Medical Expenses

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#74365]
## Issue Description
During testing, I entered 4 Care Expenses & 7 Other/Medical expenses. Some observations:

- The information entered onto the overflow section of the PDF was out of order one would expect when reading it.
- For example, some lines of information for Medical expenses where mixed in with the Care expenses. 

## Testing artifacts
- [OverflowTestJan23ReviewPage.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0QyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4b7d127851c8626a9e02acacc64ac9653a092edc/OverflowTestJan23ReviewPage.pdf)

- [OverflowTestJan23PDFgenerated.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0gyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5b0589e4a9d7fbade61c26acd1b981f36e5515f7/OverflowTestJan23PDFgenerated.pdf)

## Acceptance Criteria

- [ ] Ensure all Care Expenses & Other/Medical expenses are mapping to the Overflow section of the PDF in the order expected from the questions in PDF.

**Comment by aplatt-coforma** [comment]
Looks much better. Verified that all of the care expenses were group together and all of the medical expenses were grouped together.
<img width="1450" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHNVQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8ea74c47efe6373114c07ac12a4d931a6d298d39/Screenshot%202024-01-30%20at%209.35.50%E2%80%AFPM.png" alt="Screenshot 2024-01-30 at 9.35.50 PM.png" />
<img width="1116" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHdVQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--95c5aae0b68ad25670dcbb56de4fad8dd1996f72/Screenshot%202024-01-30%20at%209.34.09%E2%80%AFPM.png" alt="Screenshot 2024-01-30 at 9.34.09 PM.png" />
