### ISSUE TITLE
Design Team Norming

### ISSUE THREAD

**Issue by RenataKeck** [department-of-veterans-affairs/va.gov-team#74367]
This ticket is intended to capture discipline-specific team norming for Design. Once the Designer onboards, it will be important to capture norms around how we work. 

**Output**
- [x] Schedule design team norming session(s)
- [x] Create agenda
- [x] Synthesize [spreadsheet](https://docs.google.com/spreadsheets/d/1hAbY-_Y-1HbtHcxqJFak7UUkzGmpPw-3YQlYejr7URE/edit?resourcekey#gid=1033034737) from survey
- [x] Draft team agreements in[ this Google Doc](https://docs.google.com/document/d/1vrtstsGSlTdrEldgvsOVggdeS7uzhLFXtcB1eXFDq5M/edit#heading=h.3xvk0l2o3sch)

**Acceptance criteria**
Design team's agreement has been added to GitHub

**Comment by karafaithsanchez** [comment]
We're going to meet as a team one last time to review the spreadsheet, specifically where our strengths are and areas where we hope to grow as individuals and as a team.
