### ISSUE TITLE
Draft a Walk In Onboarding Flow

### ISSUE THREAD

**Issue by SophiaPhilipMO** [department-of-veterans-affairs/va.gov-team#74362]
Context
IPP requires digital set up prior to coming in person. Research shows that Veterans do true walk-ins and IPP must support that. 

User Story
As a Veteran, I need to be able to do identity verification without prior digital set up so that I can complete IPP verification.

Assumptions (We will build the flow with these assumptions in mind) 

- Veterans will have a smartphone 
- Veterans that do not have a smartphone or tech will be able to use VA issued Ipads 
- Veterans will have all required docs/forms of ID 

AC:
- [x] Create a flow featuring story map components that demonstrates what a feasible walk-in for IPP would look like

**Comment by skirkman16** [comment]
Conducted a sketching session with team on 4/8 where teammates drew out potential flows for Veterans who walk into a VA without a verification appointment but who wish to verify. Next step: synthesize sketches and add flow to service blueprint

**Comment by skirkman16** [comment]
@JKG199  started a walk on flow in figjam

**Comment by JKG199** [comment]
Draft/Ideation file [here](https://www.figma.com/file/iDO5LPOvRJXJVOyn12xpKZ/IPP-Walk-On-Flows-(SSIT-User-Flows)?type=whiteboard&node-id=0%3A1&t=B3ThSQGtCk2WV4sO-1)

**Comment by JKG199** [comment]
Updates on ideation file [here ](https://www.figma.com/board/g0vfLb9zKpvf1O5wPqKl6q/Future-State-Service-Blueprint?node-id=0%3A1&t=APQrr7w61h64MMe0-1)

**Comment by skirkman16** [comment]
@JKG199 and I met today to go over the flow and after discussing it we determined how to incorporate it into a future state service blueprint [here](https://www.figma.com/file/g0vfLb9zKpvf1O5wPqKl6q/Future-State-Service-Blueprint?type=whiteboard&node-id=66%3A722&t=RwQBuKIiRqLOAM80-1)
