### ISSUE TITLE
Covid 19 FAQs page: Copy check and Drupal updates

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#7436]
## Covid 19 FAQs page: Copy check and Drupal updates

Live URL: https://www.va.gov/coronavirus-veteran-frequently-asked-questions/
Preview URL: http://preview-prod.vfs.va.gov/preview?nodeId=3014

When ready, will attach Word doc with highlighted changes to validate Drupal page against, ~ Wednesday. 

## Acceptance Criteria 
1/ Add TOC links to FAQ categories. @RLHecht [done]
2/ Add FAQ category H2s. [done]
3/ Change question H2s to H3s. [done]
4/ Copy check and edit as needed. @RLHecht 

Please let @jenniferlee-dsva  know when complete and keep state in Draft until final go ahead from Joint Task Force. 

FYSA @MickinSahni @peggygannon @lalexanderson-dsva (Danielle doesn't have new GH handle yet)

[Coronavirus-FAQs_updates-033120-v3.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/4412148/Coronavirus-FAQs_updates-033120-v3.pdf)

**Comment by jenniferlee-dsva** [comment]
@RLHecht Would be great if you could check a couple of things while doing your final review: The appointments REACT widget and the mental health alert don't render now. I'm not sure why. 

Note - I didn't use the accordion checkbox for the q/a blocks for now.

**Comment by RLHecht** [comment]
@jenniferlee-dsva I copy edited this and made a few minor tweaks. I also deleted the Q&A "What should I do if my in-person disability exam was canceled?" I reached out to Kevin and Beth about the alert not showing up. The react widget is working higher up on the page though.

**Comment by MickinSahni** [comment]
Moving to sprint 18

**Comment by MickinSahni** [comment]
2020-04-02 PW Standup
- working through a preview bug, putting a blocker until this is resolved to the can be published
- might be more changes from stakeholders, but not much to do at the moment - @jenniferlee-dsva

**Comment by MickinSahni** [comment]
2020-04-03 PW Standup 
- Should be wrapped up today - Randi

**Comment by RLHecht** [comment]
This is validated on the live site. Closing ticket. FYSA @MickinSahni
