### ISSUE TITLE
[MVP] Ensure all data is mapping correctly to PDF for Section 7/Prior Marital History

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#74363]
## Issue Description
During testing, I entered 4 prior marriages to the web form. I also entered that my current spouse had 3 former marriages. Current spouse information looked correct. However, in the overflow section of the PDF generated

- For veteran's prior spouses, I did not see some of their information in the overflow such as their names.
- For veteran's current spouse's former marriages (3 of them), I did not see them mapped in the overflow at all.

## Testing artifacts
- [OverflowTestJan23ReviewPage.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0QyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4b7d127851c8626a9e02acacc64ac9653a092edc/OverflowTestJan23ReviewPage.pdf)

- [OverflowTestJan23PDFgenerated.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0gyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5b0589e4a9d7fbade61c26acd1b981f36e5515f7/OverflowTestJan23PDFgenerated.pdf)

## Acceptance Criteria

- [ ] Ensure all prior/former spouse names are mapping to the Overflow section of the PDF, when necessary.
- [ ] Ensure all spouses' former marriages are mapping to the Overflow section of the PDF, when necessary.
- [ ] Ensure all Prior Marriage information & Spouse's Former Marriage fields are mapping to the Overflow section of the PDF in the order expected from the questions in PDF.

**Comment by aplatt-coforma** [comment]
We need to reopen this ticket due to the following:
**Prior marriages is still missing:**
- Date of marriage
- Date marriage ended
- How did the marriage end?
_Additional suggestion is to start the overflow list with the spouse’s name, and then the rest of the fields that correspond to that person_

**Spouse’s prior marriages is also missing:**
- Date of marriage
- Date marriage ended
- How did the marriage end?
_Additional suggestion is to start the overflow list with the spouse’s name, and then the rest of the fields that correspond to that person_

**Comment by aplatt-coforma** [comment]
Prior marriages are now showing up in the overflow section grouped correctly.
<img width="1440" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDRVQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c27cce983c5cac74ea98fee14babf1085dab7583/Screenshot%202024-01-30%20at%209.41.31%E2%80%AFPM.png" alt="Screenshot 2024-01-30 at 9.41.31 PM.png" />
<img width="1522" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDhVQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6061ee03231504ecda06a5a547b199ba4077335d/Screenshot%202024-01-30%20at%209.43.03%E2%80%AFPM.png" alt="Screenshot 2024-01-30 at 9.43.03 PM.png" />
