### ISSUE TITLE
COVID 19 FAQs: Add link and teaser text to the FAQs from selected benefit detail pages

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#7437]
## COVID 19 FAQs: Add link and teaser text to the FAQs from selected benefit detail pages

1/ Write a standard link and teaser text that points to https://www.va.gov/coronavirus-veteran-frequently-asked-questions/

2/ On these selected benefit pages, add the link and teaser text to https://www.va.gov/coronavirus-veteran-frequently-asked-questions/ in a 'more/related' info component. 

3/ Selected benefit detail pages are: 
https://www.va.gov/disability/how-to-file-claim/when-to-file/pre-discharge-claim/
https://www.va.gov/health-care/secure-messaging/
https://www.va.gov/health-care/refill-track-prescriptions/
https://www.va.gov/health-care/schedule-view-va-appointments/ 
https://www.va.gov/health-care/health-needs-conditions/mental-health/
https://www.va.gov/burials-memorials/schedule-a-burial/
https://www.va.gov/burials-memorials/what-to-expect-at-military-funeral/

ice box for now - pending TBC items - for Danielle and Mickin to triage and assign. (Cannot @ Danielle yet, only old GH handle coming up.) 
ETA likely next week. 

## Acceptance Criteria
- [ ] TBD

**Comment by jenniferlee-dsva** [comment]
@MickinSahni - this is ready and the team can pull this in any time an opening is available. Thank you!

**Comment by stephorkandatx** [comment]
Update - we will not need to do this, as we are going to make the coronavirus banner global.
