### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by skirkman16** [department-of-veterans-affairs/va.gov-team#74370]
### Name

Sofia Kirkman

### Email

sofia@themostudio.com

### Role

UX Designer

### Team

Secure Sign in Transition Team

**Comment by naomimarcussen** [comment]
Hi! You already have an account for this email. Let me know if you need any help. :)

**Comment by skirkman16** [comment]
Thank you! I was just able to find it and access it

**Comment by naomimarcussen** [comment]
Excellent! Happy Figma'ing.
