### ISSUE TITLE
Income type card heading casing issue: Step 8 Financial information > Gross monthly income

### ISSUE THREAD

**Issue by gmaciolek** [department-of-veterans-affairs/va.gov-team#74375]
**Summary**
https://staging.va.gov/pension/application/527EZ/financial/income-sources
In the Financial information section, the page that allows you to add income sources, the card titles in the multi-response pattern are displaying as all caps, with words separated by underscores. Example: SOCIAL_SECURITY

**Expected behavior**
Card titles should display as sentence case headings, with words separated by spaces. Example: Social Security, Retirement

<img width="498" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmIyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f86d9a58ce2ebe17cd67ece3d1f6a6db1edba920/multi-response-card-edit-button-alignment.png" alt="multi-response-card-edit-button-alignment.png" />

**Acceptance Criteria**
> Generated by [Zenhub AI](https://www.zenhub.com/ai)

- [ ] **Card titles should not be displayed in all caps**
  - When I navigate to the Financial information section of the application
  - Then I should not see any card titles displayed in all caps
  - And the card titles should be displayed correctly, using sentence case headings, with words separated by spaces

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/74375?planning-poker) with Zenhub @mjknight50 @TaiWilkin @ToddWebDev @wayne-weibel

**Comment by ToddWebDev** [comment]
I addressed this issue already with previous work
