### ISSUE TITLE
Update SAH rates, information, links on Va.gov

### ISSUE THREAD

**Issue by AnneHurley** [department-of-veterans-affairs/va.gov-team#7438]
## User Story or Problem Statement
Need to make fixes per Housing stakeholders to SAH page on VA.gov:
https://www.va.gov/housing-assistance/disability-housing-grants/

From: VAVBAWAS/CO/WEBADMIN <WEBADMIN.VBACO@va.gov>
Date: Thu, Mar 19, 2020 at 4:12 PM
Subject: FW: WEBSITE ISSUE: LGY Websites have moved
To: Hurley, Anne (Ad Hoc, LLC) <Anne.Hurley@va.gov>
Cc: Zou, Kerri, VBAVACO <Guangrui.Zou@va.gov>, Lee, Jennifer Y. <Jennifer.Lee27@va.gov>, Mickin Sahni <mickin@adhocteam.us>, Selina Cooper <scooper@governmentcio.com>, Randi Hecht <rhecht@governmentcio.com>, Hooten, Adrianne, VBAVACO <Adrianne.Hooten@va.gov>, DiMartino, John P. VBAVACO <John.DiMartino@va.gov>
 
From: Latona, Jason, VBAVACO <Jason.Latona@va.gov> 
[https://app.zenhub.com/files/133843125/bb441e85-fa35-43a2-9345-7fe5e0705ad3/download](https://app.zenhub.com/files/133843125/bb441e85-fa35-43a2-9345-7fe5e0705ad3/download)[https://app.zenhub.com/files/133843125/f3e23961-dd16-4ca1-b4a9-79d764f8386b/download](https://app.zenhub.com/files/133843125/f3e23961-dd16-4ca1-b4a9-79d764f8386b/download)[https://app.zenhub.com/files/133843125/37a94f25-1e77-4950-89ba-fe65b9b3bef6/download](https://app.zenhub.com/files/133843125/37a94f25-1e77-4950-89ba-fe65b9b3bef6/download) 
These are the issues:
1.	Our Handbook for Design is no longer there for download: We need to add a link to the Handbook from here like we used to have prior to the migration. However Pamphlet 26-13 (SAH Handbook for Design) is no longer accessible on the WARMS site, it should be available here but we now get a 404 error: https://www.benefits.va.gov/homeloans/docs/vapamphlet_26-13.pdf. So I’m not sure where it link it to anymore. I did find it here in a Google search: https://www.benefits.va.gov/HOMELOANS/documents/docs/sah_handbook_for_design.pdf
 
2.	The FY20 grant amounts somehow reverted back to the FY19 rates when the site was migrated: This needs to reflect the FY20 rates as follows: See attachment for revisions
a.	SAH - $90,364
b.	SHA - $18,074
c.	TRA - $39,669 and $7,083
 
3.	The language incorrectly describes eligibility for the post 9/11 grant: I’ve personally rewritten this section on several occasions for Digital Services. Somehow it’s incorrect again. See attachment for revisions
 
On another note, Pamphlet 26-13 (SAH Handbook for Design) is no longer accessible on the WARMS site, it should be available here but we now get a 404 error: https://www.benefits.va.gov/homeloans/docs/vapamphlet_26-13.pdf

**Comment by AnneHurley** [comment]
@mnorthuis @lunascoop  This is the page in question: https://www.va.gov/housing-assistance/disability-housing-grants/

Page says it was updated in November 2019. Do either of you recall communications with the stakeholders/their review of the updated URLs?

**Comment by lunascoop** [comment]
@AnneHurley The legacy page was redirected to the URL (https://www.va.gov/housing-assistance/disability-housing-grants/) on Feb 25th. See the last line of the screenshot below:

<img width="1117" alt="Screen Shot 2020-03-31 at 2 20 30 PM" src="https://user-images.githubusercontent.com/42546515/78061324-10d78780-735b-11ea-940c-cfb04d081542.png">

**Comment by AnneHurley** [comment]
@RLHecht  Can you do a review of the changes to this page and let me know when you're done, so I can share the preview link with stakeholdesr:

Edit link is: https://prod.cms.va.gov/node/750/edit

Here's what changed:
1. Updated all numbers to current 2020 rates, listed above.
2. Changed all instances of FY19 to FY20.
3. Added what a fiscal year is, and revised some language in the "Note" in the top section about the cap on eligibility. I broke what the stakeholder sent into two sentences for readability so I will make sure to point that out specifically too.
4. Added text and a link under More Resources to the design handbook. See if you think that structure works - it looks a little strange to me above the list of the videos.

FYSA @jenniferlee-dsva  @lunascoop

**Comment by RLHecht** [comment]
@AnneHurley I reviewed your changes and made a few minor copy tweaks. The page is saved as a draft still.

**Comment by MickinSahni** [comment]
2020-04-01 PW Standup
- working on final edits before sending to Randi for publishing

**Comment by AnneHurley** [comment]
@RLHecht  Updated section at top listing eligibility, to change "one or both" lower extremities, to "one" per Jason/SME. 

This is ready for your copyedit & publish. Thank you!

**Comment by RLHecht** [comment]
@AnneHurley I reviewed that change and all looks good. Page is now set to publish.

**Comment by RLHecht** [comment]
These updates are now live on the site. Closing ticket. FYSA @AnneHurley @MickinSahni
