### ISSUE TITLE
Add list of pending 21-22 requests to accept/decline page with dummy data

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#74382]
**Description:** Since we know we need to allow a VSO to accept/decline 21-22 requests which will most likely take the form of some sort of list in the UI we should do a first pass at this. The details of what this page looks like are very much in flux so this first pass can just be the building of the basic list component and some dummy content. Alternatively if you want to check in with design and see what the direction they are going with this page is and implement a simplified version of it, that is ok too as a stretch goal.

**User Story or Problem Statement:** As a VSOrg: I need to be able to accept or decline a Veteran’s request for power of attorney (21-22) so that I can quickly get to work on the Veteran’s claims.

**Implementation Details:** Since this is such an early version of this component the engineer that picks this ticket up has some latitude for what they want to do here. The page should be built as a component inside /representatives/components/approve-deny and consist of a list component as well as list items.

**Mockups/Designs:** See rough wireframe in comments below. Follow up with Kara with any questions.

**Prerequisites/Dependencies:** The accept/decline page must be in place for this ticket

**Blockers:** The accept/decline page must be in place for this ticket

**Acceptance Criteria:**
- The accept/decline page now has a list of pending requests
- The components built in this ticket are tested to 100% coverage

**Automated Testing:** This must be tested to 100% coverage as detailed by the command `yarn test:coverage-app {app-name}`

**Accessibility (A11y) Testing:** Confirm that accessibility testing is completed.

**Documentation**: documentation will be completed in a subsequent ticket.

**Comment by karafaithsanchez** [comment]
<img width="500" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUlmQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--65cf02171d0d4d6422ecc5ff48ea373319456e16/POA%20Request%20page.png" alt="POA Request page.png" />
