### ISSUE TITLE
Increase font size of form page headings

### ISSUE THREAD

**Issue by gmaciolek** [department-of-veterans-affairs/va.gov-team#74383]
**Description**
The rendered font size for form page headings (the `schemaform-block-title`) is currently 18px. We'd like to increase the font size to 20px **on every form page with a subheading** for better content hierarchy.

Notes
In the sample mock forms patterns directory, these headings are an h3 in a legend and render at 20px. Example: https://staging.va.gov/mock-simple-forms-patterns/array-multiple-page-aggregate

**Example**
<img width="667" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTcyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0c8662e601cd02670f96717d4fe357c7fb857006/form-page-heading.png" alt="form-page-heading.png" />

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/74383?planning-poker) with Zenhub @mjknight50 @TaiWilkin @ToddWebDev @wayne-weibel

**Comment by aplatt-coforma** [comment]
Checked a few headings and looks good.<img width="1012" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNExJQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d794bb2813d40229be4c81e9813a897ae96e6b88/Screenshot%202024-03-08%20at%201.51.46%E2%80%AFPM.png" alt="Screenshot 2024-03-08 at 1.51.46 PM.png" />
