### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by SophiaPhilipMO** [department-of-veterans-affairs/va.gov-team#74380]
### Name

Sophia Philip

### Email

sophia@themostudio.com

### Role

Senior UX Researcher

### Team

Login.gov Adoption

### Product Manager (PM) name

Thomas Black

### Additional Notes

VA Email: sophia.philip@va.gov
Login.gov Adoption PO: Lauren Morris
Login.gov Adoption team also referred to as Secure Sign In Transition

**Comment by naomimarcussen** [comment]
Hi! An invite has been sent to [sophia@themostudio.com](mailto:sophia@themostudio.com).

**Comment by SophiaPhilipMO** [comment]
@naomimarcussen is it possible to adjust my settings to designer as I need to be able to edit prototypes as well (I wear two hats, researcher and designer). Please let me know what I can do for you to help with this adjustment. Thank you!

**Comment by naomimarcussen** [comment]
Hi! You now have full access to edit design files. :)

**Comment by SophiaPhilipMO** [comment]
Thank you!
