### ISSUE TITLE
Display preferred name in authenticated menu (header) and MHV landing page on first render

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#74398]
### User story

As an authenticated user, I want the authenticated menu (header) and MHV landing page to display my preferred name as soon as the page loads, so that I'm greeted right away and the page content doesn't shift down after the extra call to the back end returns.

### Notes

- Coordinate with AuthExp team to confirm the right place to put preferred name into state (we prefer root) – and that it doesn't need to be behind feature flag
- Check previous discussions (meeting, slack) about stakeholder concerns with having a different name in header (auth menu) and "welcome, Jess" on landing page
- Testing discussion
  - Adding to auth menu means working with the header – Public Websites owns it, and there are specific testing protocols required to make sure that the "injected VAgov header" doesn't get broken
  - Allison Lu of the AuthExp team has a lot of experience with this
  - **Code reviewers: add Micah Chiang (DST) and Randi Mays (PW).**
- Will need to add preferred name/demographics to the `/v0/user` Vets API service to load it at page start. Note demographics must be cached.
- Must be behind feature flag.
- Need to notify VA Profile before enabling this feature, so they are aware of the increased traffic and possible errors.

## Acceptance criteria
- VA Profile is notified well before enabling this feature, so they are aware of the increased traffic and possible errors.
- Preferred name for the menu header is behind a feature flag.
- Preferred name is available post-login to all applications through application state
- Authenticated menu displays the user's name (preferred if available) on first render
- Landing page welcome message renders with user's name (preferred if available) on first render (see personalization feature)
- Coordinated testing with code owners of the header and auth menu, including the Public Websites and Authenticated Experience teams, and met their requirements for testing the injected version of the VAgov header (which is used by other VAgov subdomains and is quite fragile)
- [DISCUSS:] Update nametag and auth menu documentation (requested by Profile team via Lynne)

**Comment by wesrowe** [comment]
[Slack thread](https://dsva.slack.com/archives/C52CL1PKQ/p1706830600078209) with Public Websites team about how to get this in without interfering with their work.

Good news: we may not have to worry about the fragile injected header and associated testing, as there is a plan to stop injecting react components and just have it be "flat" html (ie vanilla).

**Comment by wesrowe** [comment]
update from that slack thread: we're good to go! Design system team is going to work on the auth menu for the feder header, so we should add Micah Chiang as a reviewer. Also add Randi Mays from the PW team.

**Comment by radavis** [comment]
todo:

- [ ] add Preferred Name to serialized user at `/v0/user` within vets-api
- [ ] add Preferred Name to state in vets-website
- [ ] select Preferred Name within the Shared Header in vets-website

**Comment by carlosfelix2** [comment]
I think we should be updating the swagger files as part of this too.

**Comment by wesrowe** [comment]
I think it's confusing to keep this ticket in the Blocked column. The dependencies that have arisen to block completion of this work may change it (eg caching). So I'm going to move this back to the Backlog, and add a note that we should consider the WIP code when the dependencies have been completed.

**Comment by carlosfelix2** [comment]
Closing as we have a new set of issues in this same epic.
