### ISSUE TITLE
[MVP] Prod submission didn't make it to OBI

### ISSUE THREAD

**Issue by aplatt-coforma** [department-of-veterans-affairs/va.gov-team#74391]
Our submission yesterday on PROD was not received by our OBI partners.

LH guid: `ca36a31b-b1bd-4241-9619-c27e8a65153f`

**AC**
- Investigate what happened
- Fix for MVP relaunch

**Comment by TaiWilkin** [comment]
We think that the incorrect ID might have been sent over - asking LH to check again with a different ID.

**Comment by aplatt-coforma** [comment]
Determined the first LH GUID was incorrect. It should have been a0580ff9-6ca9-4c63-9994-555e4f3be1a6
From looking at our logs Matt was able to see that they most likely recieved it. 
`{"data":{"id":"a0580ff9-6ca9-4c63-9994-555e4f3be1a6","type":"document_upload","attributes":{"guid":"a0580ff9-6ca9-4c63-9994-555e4f3be1a6","status":"success","code":null,"detail":"","location":null,"updated_at":"2024-01-24T01:53:39.987Z","uploaded_pdf":{"total_documents":1,"total_pages":11,"content":{"page_count":11,"dimensions":{"height":11.0,"width":8.5,"oversized_pdf":false},"file_size":523384,"attachments":[]},"line_of_business":"PMC"}}}}`

**Comment by aplatt-coforma** [comment]
Moving to complete in stage. Can reopen this ticket if they still can't find the packet.
