### ISSUE TITLE
Proposal for improving alerting standards on Va.gov

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#744]
In order to support the successful growth of the platform, VSP needs to have improved alerting strategy, in order to better understand alerting and what should be alerting. 

@wyattwalter Feel free to update/ change

**Comment by wyattwalter** [comment]
Wrote up a new rubric for alerts and put that into the OnCall documentation folder. I think next we need to work through the list of rules to make sure they conform or are adjusted.

**Comment by ricetj** [comment]
Closing
