### ISSUE TITLE
Lighthouse REdiscovery

### ISSUE THREAD

**Issue by kjsuarez** [department-of-veterans-affairs/va.gov-team#74400]
We're supposed to work with the lighthouse team to source veteran payment history. Make contact with the Lighthouse team on the debt_payment_history slack channel and confirm a few things-

- Determine if Lighthouse has an API endpoint that returns payment information for a given veteran.
  - If so
    - Outline the details here
    - Request access to a lower environment
  - If not
    - Begin/resume(?) talks to have this endpoint built

**Comment by HeatherRienks** [comment]
Closing this dupe ticket. All efforts are tracked here:  #54319.
