### ISSUE TITLE
CT: Settlement caution flag reasons are displaying as a CSV value

### ISSUE THREAD

**Issue by zurbergram** [department-of-veterans-affairs/va.gov-team#7440]
## What happened?
View either URL below (second one if UI changes have been delivered to CT search results), settlement caution flag reasons are coming out as a CSV value

[Caution.Flag.Copy.for.Review.v.2.0.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4410309/Caution.Flag.Copy.for.Review.v.2.0.xlsx) references the settlement reasons (copy) as separate values for mapping to new copy

Additionally in https://github.com/department-of-veterans-affairs/gibct-data-service/blob/master/sample_csvs/settlement.csv there are rows with multiple caution flag copy from above spreadsheet in a single `settlement_description` column.
## Steps to Reproduce
- URL: https://staging.va.gov/gi-bill-comparison-tool/search?category=school&name=31017405 or https://staging-api.va.gov/v0/gi/institutions/31017405 

![Screen Shot 2020-03-31 at 12 24 14 PM](https://user-images.githubusercontent.com/1094999/78050686-9a328e00-734a-11ea-88b9-619413610acd.png)

Based on [settlement_flags-ux.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4429548/settlement_flags-ux.xlsx) it appears that settlement descriptions are being separated by both `,` and `;`

## Desired behavior
_Describe in detail what was supposed to happen; reference existing Github issue that contains a solution if possible_

## Acceptance Criteria
- [ ] _Describe the desired working behavior_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by zurbergram** [comment]
Here are the all the descriptions/copy/reasons with a "," in them from the settlement csv uploaded into staging by Brian Grubb on 3/30



- "Loss of Title IV Participation, Settlement with U.S. Government, Upcoming Campus Closure (Details Posted on Institution Website), Assigned receiver has motioned court for an emergency closure of compus. Immenent closure is a distinct possible"
- "Settlement with U.S. Government, Upcoming Campus Closure (Details Posted on Institution Website)"
- "Loss of Title IV Participation, Settlement with U.S. Government"
- "Federal Trade Commission Filed Suit for Deceptive Advertising; Potential Suspension of VA Benefits to Five Schools for Deceptive Practices goes into effect on May 9, 2020."
- "Federal Trade Commission Filed Suit for Deceptive Advertising; Settlement reached on May 26, 2015"
- "Settlement with U.S. Government, Upcoming Campus Closure (Details Posted on Institution Website), Assigned receiver has motioned court for an emergency closure of compus. Immenent closure is a distinct possible"
- "Settlement with U.S. Government, Upcoming Campus Closure (Details Posted on Institution's Website)"
- "Loss of Title IV Participation, Settlement with U.S. Government, Assigned receiver has motioned court for an emergency closure of campus. Imminent closure is a distinct possibility."
- "Settlement with U.S. Government, Assigned receiver has motioned court for an emergency closure of compus. Immenent closure is a distinct possible"
- "There may be a potential lapse in program approval for Ashford University. VA may be forced to stop making benefit payments unless Ashford continues to show a good faith effort to seek approval in California. The State Attorney General filed a lawsuit against Ashford University for engaging in unlawful business practices, and litigation is pending."
- "Loss of Title IV Participation, Settlement with U.S. Government, Assigned receiver has motioned court for an emergency closure of compus. Immenent closure is a distinct possible"
- "Loss of Title IV Participation, Assigned receiver has motioned court for an emergency closure of compus. ImmInent closure is a distinct possible"

**Comment by zurbergram** [comment]
Here are the all the descriptions/copy/reasons from the settlement csv uploaded into staging by Brian Grubb on 3/30

- "Post 9/11 GI Bill (CH33) not Approved at this location"
- "Denial of Recertification Application to Participate in the Federal Student Financial Assistance Programs Issued by Department of Education"
- "Loss of Title IV Participation, Settlement with U.S. Government, Upcoming Campus Closure (Details Posted on Institution Website), Assigned receiver has motioned court for an emergency closure of compus. Immenent closure is a distinct possible"
- "Settlement with U.S. Government, Upcoming Campus Closure (Details Posted on Institution Website)"
- "Upcoming Campus Closure (Details Posted on Institution's Website)"
- "Settlement reached with the Federal Trade Commission (FTC)"
- "Assigned receiver has motioned court for an emergency closure of campus. Imminent closure is a distinct possibility."
- "Settlement reached with States Attorney General"
- "Loss of Title IV Participation, Settlement with U.S. Government"
- "Flight Program - Suspended for 85/15 violation"
- "Federal Trade Commission Filed Suit for Deceptive Advertising; Potential Suspension of VA Benefits to Five Schools for Deceptive Practices goes into effect on May 9, 2020."
- "Federal Trade Commission Filed Suit for Deceptive Advertising; Settlement reached on May 26, 2015"
- "Settlement with U.S. Government, Upcoming Campus Closure (Details Posted on Institution Website), Assigned receiver has motioned court for an emergency closure of compus. Immenent closure is a distinct possible"
- "Denial of Recertification Application to Participate in the Federal Student Financial Assistance Program"
- "Settlement with U.S. Government"
- "Settlement with U.S. Government, Upcoming Campus Closure (Details Posted on Institution's Website)"
- "Loss of Title IV Participation, Settlement with U.S. Government, Assigned receiver has motioned court for an emergency closure of campus. Imminent closure is a distinct possibility."
- "Settlement with U.S. Government, Assigned receiver has motioned court for an emergency closure of compus. Immenent closure is a distinct possible"
- "There may be a potential lapse in program approval for Ashford University. VA may be forced to stop making benefit payments unless Ashford continues to show a good faith effort to seek approval in California. The State Attorney General filed a lawsuit against Ashford University for engaging in unlawful business practices, and litigation is pending."
- "Loss of Title IV Participation, Settlement with U.S. Government, Assigned receiver has motioned court for an emergency closure of compus. Immenent closure is a distinct possible"
- "Loss of Title IV Participation, Assigned receiver has motioned court for an emergency closure of compus. ImmInent closure is a distinct possible"

**Comment by desireeturner** [comment]
We're waiting on EDU to provide generic content to be displayed when these come through.

**Comment by zurbergram** [comment]
This was resolved by https://github.com/department-of-veterans-affairs/va.gov-team/issues/7578
