### ISSUE TITLE
[DA] 10-10EZ/EZR - Performance Monitoring: Create monitor on HTTP calls to es_backend at the fwd proxy

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#74405]
## Background
Due to HCA API Failures causing all 10-10EZ/EZR submission failures, we need to Implement a monitor on HTTP calls to es_backend at the fwd proxy

**Comment by luis-simauchi** [comment]
we are going to key off the following metric calculation:
sum:haproxy.server.http.responses.total{proxy:es_back,deployment_env:vagov-prod}.as_count()

with tag: 
code:5xx,proxy:es_back

**Comment by luis-simauchi** [comment]
Monitor is in place:
https://vagov.ddog-gov.com/monitors/193363?view=spans
