### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by MDomngz** [department-of-veterans-affairs/va.gov-team#74407]
### Name

Marisa Dominguez

### Email

marisa.dominguez@oddball.io

### Role

Sr UX Designer & Researcher

### Team

VA-CMS (platform)

### Product Manager (PM) name

Michelle Dooley

**Comment by naomimarcussen** [comment]
Hi! I just sent an invite to marisa.dominguez@oddball.io. Reply here once you follow that link and create and I'll bump you up to an editor. :)

**Comment by MDomngz** [comment]
Thank you - I've completed creating my oddball.io account

**Comment by naomimarcussen** [comment]
Great! You now have full access. You can get an overview of how we're using [Figma at the VA here](https://depo-platform-documentation.scrollhelp.site/research-design/designing-with-figma-at-va
).
