### ISSUE TITLE
[DA] 10-10EZ - Performance Monitoring: Look into 500s that appeared in staging

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#74411]
## Background
Look into 500s that appeared in staging, potentially adding alerts for staging errors like this

**Comment by jadon1979** [comment]
Many of these happened during the Savon gem update issue and were related to the duplicate schema entry causing the Soap requests to fail.  The others were due to intermittent timeouts when sending data to ES.
