### ISSUE TITLE
Add new PDF link on the Welcome Kit page

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#7442]
## Add new PDF link on the Welcome Kit page

ETA - by next Monday's daily deploy is fine. 

On this page: https://www.va.gov/welcome-kit/ 

@lalexanderson-dsva: 
please upload the PDF here. 

@peggygannon:  
- [x] 1 Write a new blurb for this COVID related 'quick start guide' PDF. (Please don't call it "Coronavirus Quick Start Guide" :-) )

@RLHecht : 
- [x] 2 Host the PDF in our GH repo. 
- [x] 3 Appropriately locate the new link on page. 
- [x] 4 Please FYSA @lalexanderson-dsva and Beth Lamb via email when Preview link is ready to publish. 

FYSA @MickinSahni

**Comment by lalexanderson-dsva** [comment]
Here is the file to upload: 

[https://app.zenhub.com/files/133843125/59294155-e0d4-48ee-b68e-dc7cc07af632/download](https://app.zenhub.com/files/133843125/59294155-e0d4-48ee-b68e-dc7cc07af632/download)

**Comment by peggygannon** [comment]
**4/2 update** blurb sent to Danielle for review.

**Comment by peggygannon** [comment]
@jenniferlee-dsva @lalexanderson-dsva 

Please see below for suggested blurb to the COVID-19 PDF for this page https://www.va.gov/welcome-kit. 

As far as placement on this page, I would recommend this goes right below the "Download your VA Welcome Kit"

**Download the latest information on VA and COVID-19**

Read our guide to find out how to use your VA benefits and services during this time. And learn about steps you can take to help protect yourself and others.  
[What you need to know about coronavirus (COVID-19)(PDF)](links to file upload https://app.zenhub.com/files/133843125/59294155-e0d4-48ee-b68e-dc7cc07af632/download)

**Comment by ncksllvn** [comment]
What should the file name be? `what-you-need-to-know-about-coronavirus.pdf`?

**Comment by RLHecht** [comment]
@ncksllvn That seems fine to me. @jenniferlee-dsva is that PDF name OK?

**Comment by jenniferlee-dsva** [comment]
So interesting... bc they've hijacked the Veteran coronavirus FAQ page name. Ug. Hold on...

**Comment by jenniferlee-dsva** [comment]
Okay. Please use this as the file name -- and we'll need to update the teaser link name to match. This will be somewhat weird for the PDF, but we just can't have this PDF hijack the name of the actual Veteran FAQs page. 

**Download our COVID-19 guide**
Read our guide to find out how to help protect yourself and others.
[Links and resources you can use to protect yourself and others (PDF)]  

File name: `links-and-resources-you-can-use-to-protect-yourself-and-others.pdf`

I don't even think we can say "the latest information" because this PDF may not be able to keep up with evolving situation.

**Comment by jenniferlee-dsva** [comment]
I'm sorry - I didn't bother reading the actual PDF before! My bad!

**Comment by ncksllvn** [comment]
PDF has been added - `www.va.gov/covid-19-links-and resources.pdf `will be available after today's daily

**Comment by ncksllvn** [comment]
Whoops, @jenniferlee-dsva should the file name have been `covid-19-links-and-resources.pdf`?  There's a space instead of a hyphen before `resources` in your original comment, and I copied the file name out of there

**Comment by MickinSahni** [comment]
2020-04-06 PW Standup
- Nick added and Randi to validate

**Comment by jenniferlee-dsva** [comment]
Good catch, yes, thank you @ncksllvn

**Comment by RLHecht** [comment]
This page is now updated on the live site and let Lauren know. Closing ticket. FYSA @MickinSahni
