### ISSUE TITLE
New VFS Team [Transition Experience]

### ISSUE THREAD

**Issue by YevgenyDreyband** [department-of-veterans-affairs/va.gov-team#74429]
## Welcome and Introduction
We are excited to welcome your team to VA.gov. As a new VFS team, this template should be completed by your teams Product Owner and/or Product Manager.

## User Stories
As the leader of a new VFS team, I need to share basic info about my team with Platform so that Platform teams can have knowledge of my team for future collaboration.

As the leader of a new VFS team, I need to ensure my team follows the instructions for new VFS team members so that they're aware of Platform policies and processes, and Platform is aware of who supports my team for future collaboration.

As the leader of a new VFS team, I need to ensure my teams product information is correct so that Platform can have an accurate list of VA.gov products.

As the leader of a new VFS team, I need to complete ATO orientation so that VA.gov continues to be a secured and approved application within the VA.

## New Team Info
Add your team's practice and contact information below.

- **Team Name:**
Transition Experience

- **OCTO-DE Product Owner:**
- Yevgeny Dreyband

- **VA Business Owner:**
   - [ ] OCTO (Office of the CTO)
   - [ ] VHA (Veterans Health Administration)
   - [ ] VBA (Veterans Benefits Administration)
   - [ ] NCA (National Cemetery Administration)
   - [ ] VACO (Veterans Affairs Central Office)
   - [X] Other. Please specify: VES

- **Crew:**
   - [ ] Sitewide
   - [X] Account Experience
   - [ ] Health Tools
   - [ ] Benefit Tools
   - [ ] Lighthouse API

- **Github team name:**
Transition Experience

- **Github team label:**

- **Team launch date:**

- **Public slack channel:**
#ves-transition

- **Other team names:**
VES Transition, Transition

- [ ] This information has been added.

## ToT (Team of Teams)
- [ ] Contact `@Julia Badillo` or `@Erica Robbins [GovCIO_VetsPS]` on the #team-of-teams-slide-collection channel to receive an invite to the Team of Teams meeting and the Team of Teams Agenda and Protocol for reference

## Introduce your team on slack
- [ ] Introduce your team on the #vfs-all-teams Slack channel. Include team name, Product Manager, Product Owner, what crew your team is on, and what products you're supporting on VA.gov.

## Platform Orientation for your team members
In addition to providing information to Platform and completing necessary tasks at the team level, there are also tasks that need to be completed at the individual level. As a team leader, you will need to:
- [x] Direct your team members to the guidance for [New VFS team members](https://depo-platform-documentation.scrollhelp.site/getting-started/Guidance-for-new-teams-and-team-members.2132803700.html#Guidancefornewteamsandteammembers-NewVFSTeammembers) on Platform Website
- [x] Ask all of your team members to complete the process

## Review and update your team's product information
- [ ] Go to the [VA Product Directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory)
- [ ] Navigate to and select your team's product
- [ ] Review to make sure that all of your team's products are listed and assigned correctly
- [ ] If an edit to your team's product page needs to be made, see the [user guide](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory-user-guide)

## ATO (Authorization to Operate) orientation
- [ ] Post in the #platform-security Slack channel to request and schedule an ATO team orientation
- [ ] Confirm that the orientation has been completed

## Platform Checklist
The items in this checklist are for Platform to complete. If you are ready to close the ticket and the Platform Checklist section has not been completed, please reach out to Platform via the guidance provided in [Getting help from Platform in Slack](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html).
- [x] New VFS Team has been added to the VFS Team Roster located in [Atlas](https://www.va.gov/atlas/)

**Comment by bdech** [comment]
@YevgenyDreyband Do you have the team launch date?

**Comment by YevgenyDreyband** [comment]
Hi Brandon, we're already underway but not sure if there's a formal launch date. This is my first time creating a new VFS team ticket so let me know what info I can provide.

**Comment by bdech** [comment]
I forgot to comment, but this team has been added to Atlas

**Comment by nkontrabecki** [comment]
Hi Brandon - Our team is getting closer to creating the Collaboration Request GitHub ticket. What additional information do you need for this ticket?

**Comment by bdech** [comment]
Forgot to close this out. Team was added in Atlas
