### ISSUE TITLE
Complete unified sign-in onboarding 

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#74439]
**Description**: In order for us to use the sign-in service we will need to make use of the Unified Sign In Page. For us to use the Unified Sign In Page we need to complete their onboarding which is simply filling out some information and providing it to them in a Slack thread. The information we need to provide to them is detailed in their [onboarding doc](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/vsp/teams/Identity/Product%20Documentation/Unified%20Sign%20in%20Page/onboarding.md). We can submit this to them in a Slack thread in the #vsp-identity channel.

**User Story or Problem Statement:** As a VSOfficer: I require a secure login system to verify my accreditation and identity in order to protect Veterans’ Personal Identifiable Information (PII) and Protected Health Information (PHI).

**Implementation Details:** N/A

**Mockups/Designs:** N/A

**Prerequisites/Dependencies:** N/A

**Acceptance Criteria**:
- The information noted above in the linked doc has been submitted to the Identity team

**Blockers:** N/A

**Comment by RivkaCGates** [comment]
@cohnjesse to add a bit more detail including AC

**Comment by RivkaCGates** [comment]
sounds good

**Comment by RivkaCGates** [comment]
has this been actively shared? @gabezurita
