### ISSUE TITLE
Fix `school_name_in_yr_database`

### ISSUE THREAD

**Issue by kelsonic** [department-of-veterans-affairs/va.gov-team#7443]
# Description

The `school_name_in_yr_database` has suddenly become full of `null` values following the uploading of the new production YR CSV. This needs to include the institution name.

## Screenshots

![image.png](https://images.zenhubusercontent.com/5d812458c75aaf0001c430f8/19cac76a-408b-4357-86bf-d188de4a50be)

## Acceptance Criteria

- [x] Replace `school_name_in_yr_database` with the Institution name in `gibct-data-service`.
- [x] Update `vets-api` Yellow Ribbon endpoint swagger docs with the new query params from GIDS.
- [x] Update `vets-website` request with the new query params.

**Comment by kelsonic** [comment]
Bumping this to a `5` since the `school_name_in_yr_database` query param will need to be updated to `name` in `gibct-data-service`, `vets-api`, and `vets-website`... @MickinSahni

**Comment by kelsonic** [comment]
All 3 PRs are up 🙂

**Comment by MickinSahni** [comment]
2020-04-03 PW Standup
- Validated locally
