### ISSUE TITLE
Add our app to unified sign-in page 

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#74440]
**Description:** Since we will be using the sign-in service we need to add our app to the Unified Sign In Service. To do this we need to add a small amount of configuration code to two files in the platform code detailed [in the documentation](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/teams/vsp/teams/Identity/Product%20Documentation/Unified%20Sign%20in%20Page#-adding-an-external-app-to-usip-vets-website).

**User Story or Problem Statement:** As a VSOfficer: I require a secure login system to verify my accreditation and identity in order to protect Veterans’ Personal Identifiable Information (PII) and Protected Health Information (PHI).

**Implementation Details:** This will be a small amount of configuration code added to two files in the platform code, `src/platform/user/authentication/constants.js` and `src/platform/user/authentication/usip-config.js`

**Mockups/Designs:** None needed

**Prerequisites/Dependencies:** Not at this time

**Blockers:** Not at this time

**Acceptance Criteria**
- The representatives app has been added to the Unified Sign In Page cofig

**Comment by nihil2501** [comment]
@gabezurita I think that we may have forgotten to specify localhost USiP config on our call with #vsp-identity. Would you check about that for us?

**Comment by hdbaines** [comment]
@gabezurita has the Identity Team reviewed the PR yet?
