### ISSUE TITLE
Dependent information header and padding issues

### ISSUE THREAD

**Issue by gmaciolek** [department-of-veterans-affairs/va.gov-team#74449]
**Description**
Need to update the heading styling and increase padding below the heading on the dependent information and address pages.

URLs: 

- https://staging.va.gov/pension/application/527EZ/household/dependents/children/information/0
- https://staging.va.gov/pension/application/527EZ/household/dependents/children/address/0

Currently, the heading is broken into 2 lines: an h4 for the dependent name and an h4 that says "Information" (see screenshot) 

**Updates requested:**
- If possible, we'd like to combine the 2 lines into one 20px heading (Question: Should this heading be an h3 in a legend? That's how I see this implemented in the [mock form patterns demo](https://staging.va.gov/mock-form-patterns/identification-information).)
- Heading text should be: [Dependent Name]'s information 
- Padding between heading and first form field should be about 32px. 

**Links and screenshots**
Design prototype: https://www.sketch.com/s/09ad2b07-2120-44fb-a5ce-aeb60085ca9e/a/oM5PZn2#Inspect

Screenshot:
<img width="611" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTc0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a23f47e8ac49d70e3e62f544b4e7e8bb7c26df2e/dependent-info-page-pension-form.png" alt="dependent-info-page-pension-form.png" />

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/74449?planning-poker) with Zenhub @mjknight50 @TaiWilkin @ToddWebDev @wayne-weibel

**Comment by TaiWilkin** [comment]
I think this will be fixed by https://github.com/department-of-veterans-affairs/vets-website/pull/28124 once it's merged
