### ISSUE TITLE
Register client config with vets-api for sign-in service

### ISSUE THREAD

**Issue by cohnjesse** [department-of-veterans-affairs/va.gov-team#74445]
**Description:** Since we are going to use the sign-in service we need to register our client configuration with `vets-website`. This is done within a file in `vets-website` and is detailed in both [the documentation for the registration](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Products/Sign-In%20Service/configuration/client_config.md) itself as well as [the documentation for Sign-in Service](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity/Products/Sign-In%20Service). The documentation is not super clear where this will need to go so the engineer that picks this up may need to start a Slack thread with the identity team for more details.

We will be using the [Proof Key for Code Exchange (PKCE)](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity/Products/Sign-In%20Service#proof-key-for-code-exchange-pkce) authorization flow 

**User Story or Problem Statement:** As a VSOfficer: I require a secure login system to verify my accreditation and identity in order to protect Veterans’ Personal Identifiable Information (PII) and Protected Health Information (PHI).

**Mockups/Designs:** N/A

**Prerequisites/Dependencies:** None at this time

**Blockers:** None at this time.

**Specifications:** Detail the technical specifications required.

**Acceptance Criteria:** 
- a client config for our app has been added to `vets-website`

Testing Criteria: This does not require testing

**Comment by nihil2501** [comment]
Submitted to identity [here](https://dsva.slack.com/archives/CSFV4QTKN/p1707347338329859?thread_ts=1706657017.726959&cid=CSFV4QTKN)
