### ISSUE TITLE
UX: integration of health tools and secondary nav with MHV landing page

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#74454]
### User story

As a Veteran, I want VAgov to let me use all four health tools without having to bounce back to the classic MHV website, so that I have the best chance of liking the new portal.

As a Veteran on MHV Classic, I want to stay on VAgov for 

### Notes
- All changes should be tied to one or several feature flags so we can carefully coordinate roll-out and can roll back if necessary
  - All functionality across tools should probably be on a single feature flag, if possible, so that we can roll out to a % of users.

> **Starter list of UX items suggested by Kaitlin:**
> - updating the links
> - exploring how we can communicate to landing page users about the MHV to [va.gov](http://va.gov/) transition and help them understand what exists on VAgov in this "try me " phase vs. what still remains on MHV classic
> - updating breadcrumb navigation within tools to connect tools back to the MHV LP
> - and anything else you all think needs to be done to make this transition successful

Possible tasks:

- identified what VADS component type(s) should be used to show content about the transition to Veterans
- Filed intake ticket with CAIA
- sub-tickets
  - big user flow diagram that captures use cases, changes across tools, a11y annotations, etc
  - nav design iteration, along with octo/OCC review
  - "loud" warning of leaving VAgov
  - landing page links/nav changes
  - user onboarding content updates on landing page (CAIA)
  - release planning (from UX/business perspective)

## Acceptance criteria

- Finalize secondary nav UX in Figma, including:
  - Secondary nav displays at top of any page under the `/my-health/` path for authenticated users with access to tools (registered, LOA3)
  - "Home" option improves upon the version ("My HealtheVet") that research participants didn't realize was clickable
  - Records option communicates that the user is leaving VAgov for national portal **(work with CAIA on content)**
    - from octo: _"as a user who clicks on a link that takes me back to the national portal, i want to know that i'm leaving VAgov and going somewhere else, so when i get there i'm not confused about where i am"_
  - Users without facility registration have a coherent experience
  - Users with non-LOA3 credentials have a coherent experience
- Added Figma link to [release planning document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/rollout/integration-with-nav-release-plan-2024.md)
- Designed a component that communicates to landing page users about the MHV to VAgov transition and help them understand what exists on VAgov in this "try me " phase vs. what still remains on MHV classic **(work with CAIA on content)**
  - from octo: _"as a user who is visiting the mhv on va.gov landing page for the first/second time, i want to know what's new on mhv on VAgov and why without having to seek out this information"_
- Documented all other UX changes on the landing page and tool pages that need to be made at launch for the integration to be successful
- Consulted with engineering to ensure feasibility
- A11y: specialist reviewed proposed UX to surface potential issues

**Comment by wesrowe** [comment]
@carlosfelix2, note that I repurposed this ticket to focus on the UX side of the integration, including secondary nav. I left an AC about engineering input on feasibility. But you can collect your implementation thoughts in the implementation ticket, #80401.

**Comment by carlosfelix2** [comment]
- Secure Messaging
  - Feature flag: `mhv_secure_messaging_to_va_gov_release`
  - When the flag is off: Users are redirected to `/health-care/secure-messaging`
  - Comments: The SM code has some leftover flags from the pilot days, so it can be confusing which flag to use. The flag `mhv_secure_messaging_cerner_pilot` incorrectly redirects to the same `manifest.rootUrl` giving a redirect loop, but this is not used.

**Comment by carlosfelix2** [comment]
Engineering research is attached above in the comments. Needs UX.

**Comment by radavis** [comment]
> All functionality across tools should probably be on a single feature flag, if possible, so that we can roll out to a % of users.

Based on this statement, we will need to create a new feature flag to gate access to the four tools.

**Comment by wesrowe** [comment]
### Chats from re-planning meeting:
Sara:
Tool teams devs also need to do these things:
* update breadcrumbs on landing pages to point to MHV landing page
* update all URLs to other tools to point to tools on VA.gov (not national portal)
* implement Cerner/OH gating for any users with an oracle facility in their profile that routes them to MyVA Health

Florence:
UX design:
Nav design and OCC readout
Link and routing updates 
Interstitial page for moving btwn national portal and MHV on VA.gov
Content updates on landing page re: medical records not available

Carlos and Sara:
Design
1. Secondary Nav design (potentially done? Or perhaps we need some updates?)
2. Identify landing page changes to point to MHV on VA.gov version of health tools
Implementation
1. Implement common secondary Nav components - 5p
2. Implement secondary Nav for Medical Records
3. Implement secondary Nav for Medications
4. Implement secondary Nav for Secure Messaging
5. Implement landing page changes to point to MHV on VA.gov version of health tools
6. Design interstitial page / content plan to communicate what goes back to national portal
7. Design light “onboarding” to explain to users what they can do on MHV on VA.gov, including content updates for landing page Medical Records 
8. I need a shared support ticket to manage the IA routing updates this necessitates with teams

**Comment by wesrowe** [comment]
ACs distributed to new tickets. closing.

**Comment by fmccaf1** [comment]
Sent 2ndary nav designs to Kaitlin for feedback just now.

**Comment by fmccaf1** [comment]
## Options for treating MR users who will have to leave VA.gov > National Portal to use the tool:
### 1. Exclude a "Records" link in the secondary nav.
To find the medical records app on the national portal, users will need to go to landing page (or VA.gov health benefit hub) and click a tool link.

a. When user clicks link to Records tool anywhere on VA.gov, they are confronted with a modal (pop-up), which notifies them they are leaving VA.gov and asking for confirmation.

b. When user clicks link to Records tool anywhere on VA.gov, they go to the Records tool on the national portal, and see an informational alert on that page, explaining that the VA.gov tool is coming soon.

### 2. Include a "Records" link in the secondary nav that is accessible from almost every page of MHV on VA.gov.

a. When user clicks on the Records link in the secondary nav, or on any Records link on VA.gov, they go to the Records tool on the national portal and see an informational alert on that page, explaining that the VA.gov tool is coming soon.

### Notes
My opinion is that our best option is 2a. We want the Records tool to be as easy to find as any other health tool. My hypothesis: the tool still being on the National Portal (and users not initially expecting that) will cause less UX issues than the tool being harder to find.
