### ISSUE TITLE
[FwdProxy to AL2] Initial vsp-platform-fwdproxy setup

### ISSUE THREAD

**Issue by hgbarreto** [department-of-veterans-affairs/va.gov-team#74465]
## Description
In order to begin the effort of moving FwdProxy to AL2 we need to create a repo 

## Resources 
- https://github.com/department-of-veterans-affairs/vsp-platform-revproxy/actions

## Acceptance Criteria
- [x] Repo Creation

## Refinement Guidance - Check the following before working on this issue: 
- [x] _Team label assigned ("platform-tech-team-2")_
- [x] _Epic assigned (if needed)_ 
- [ ] _Estimated (points assigned)_
- [ ] _Sprint assigned (once planned)_
- [ ] _Team member(s) assigned_
- [ ] _Understands how this work aligns with the overall platform_

**Comment by npeterson54** [comment]
Still a work in progress, continuing onto next sprint
