### ISSUE TITLE
[FwdProxy to AL2] Terraform for FwdProxy Deployment

### ISSUE THREAD

**Issue by hgbarreto** [department-of-veterans-affairs/va.gov-team#74467]
## Description
n order to complete the effort of moving FwdProxy to AL2 we need to build the FwdProxy Deployment IaC using Terraform. It will need to leverage the hardened base docker AMI and mimic the currently deployed FwdProxy infrastructure (ASGs, policies, SG, etc)

## Resources 
- https://github.com/department-of-veterans-affairs/vsp-platform-revproxy/tree/main/terraform

## Acceptance Criteria
- [ ] Build instance that leverages hardened base docker AMI and launches FwdProxy container
- [ ] Determine supplemental infra needed 
- [ ] Test + Document

## Refinement Guidance - Check the following before working on this issue: 
- [ ] _Team label assigned ("platform-tech-team-2")_
- [ ] _Epic assigned (if needed)_ 
- [ ] _Estimated (points assigned)_
- [ ] _Sprint assigned (once planned)_
- [ ] _Team member(s) assigned_
- [ ] _Understands how this work aligns with the overall platform_

**Comment by stoiven** [comment]
@hgbarreto for future reference, how do I check the latest hardened AMI? `ami-0f4ef271e6700ecd5` is what I used right now, but I just whatever I saw running in `prod`
