### ISSUE TITLE
[FwdProxy to AL2] Dockerfile creation for HA Proxy

### ISSUE THREAD

**Issue by hgbarreto** [department-of-veterans-affairs/va.gov-team#74466]
## Description
In order to complete the effort of moving FwdProxy to AL2 we need to create a stable Dockerfile that will add any needed prerequisites, render templates and combine it all into an Approved HAProxy Docker Image.

## Resources 
- https://github.com/department-of-veterans-affairs/vsp-platform-revproxy/tree/main/template-rendering

## Acceptance Criteria
- [x] Identify and load 2.X HAProxy Image into ECR
- [x] Design Dockefile build that leverages the current config file locations (need to minimize interference with current user processes)
- [x] Test locally or via GHA that the end Image has everything needed to function as our current FwdProxy instance does

## Refinement Guidance - Check the following before working on this issue: 
- [ ] _Team label assigned ("platform-tech-team-2")_
- [ ] _Epic assigned (if needed)_ 
- [ ] _Estimated (points assigned)_
- [ ] _Sprint assigned (once planned)_
- [ ] _Team member(s) assigned_
- [ ] _Understands how this work aligns with the overall platform_

**Comment by npeterson54** [comment]
moving into next sprint
