### ISSUE TITLE
Staging:  Community Care Request Comments and issues with NULL being appended messes with 250 char limit on comments

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#74480]
1. Log in to VAOS as the test user. 	brienne.b.ferrara@id.me
2. Navigate to the appointment page. 	http://staging.va.gov/my-health/appointments/
3. Click Start Scheduling.	Type of Care page opens. 
4. Select Podiatry and click Continue.	The Choose an appointment date and time page opens. 
5. Select a valid date (one that is not grayed out)	The AM/PM selection opens. 
6. Select AM or PM and click Continue. 	The What's the Closest City to you page opens
7. Verify that city is required. 	Please provide a response in red.
8. Select Dayton and click Continue.	The Request a Podiatry provider page opens. 
9. Do not select a provider. Click Continue.	The Preferred Language page opens. 
10. Select a language and click Continue.	The Reason for appointment page opens. 
11. Enter 250 characters in the Reason field and click Continue.  Note the character counter. Click Continue	The contact information page opens. 
12. Enter contact information as required and click Continue.	The review appointment details page opens. 
13. Verify that the information on the Review Details page is correct. Note the text entered in Reason earlier to compare with Actual results.	All information is correct
14. Click the Request Appointment button. 	
15. Verify that the request has been made. 	Your appointment request has been submitted message with details. 
 "We couldn’t schedule this appointment error message displayed.  
Developer tools show this error: 

    ""errors"": [
        {
            ""title"": ""Bad Request"",
            ""detail"": ""reasonCode.text: field must not exceed a length of 250"",
            ""code"": ""VAOS_400"",
            ""source"": {
                ""vamfUrl"": ""https://internal-dsva-vagov-staging-fwdproxy-1821450725.us-gov-west-1.elb.amazonaws.com:4463/vaos/v1/patients/1013120787V412913/appointments"",
                ""vamfBody"": ""{\""message\"":\""reasonCode.text: field must not exceed a length of 250\""}"",
                ""vamfStatus"": 400
            },
            ""status"": ""400"" "displayed

**Comment by marcynadeau** [comment]
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/62026291/a1b46b77-b3ba-4ea7-8470-c9d94603e69d)

**Comment by mshatalov-va** [comment]
This appears to have been fixed in Staging. Issue is not reproduceable, we are seeing expected results in testing.

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket.
