### ISSUE TITLE
Users get stuck if requests aren't supported and there are no matching clinics

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#7448]
When a user chooses a type of care and facility that supports direct scheduling and not requests, but the past appt history fetch fails or does not match any of the current clinics, a user will get stuck on the VA location page.

**Comment by narin** [comment]
@lenaecb @jbalboni According to our analytics, it looks like this has only happened once.  I've found where the user is getting stuck and this is what they see:

> <img width="686" alt="Screen Shot 2020-04-14 at 10 00 36 AM" src="https://user-images.githubusercontent.com/786704/79253970-dda3f680-7e38-11ea-940a-ab345d651987.png">

I'm not sure what copy we should be showing the user.  @jbalboni Even though the clinics support direct scheduling, we can't let them proceed without their past appointment history, correct? 

If that's the case, we could potentially show this existing error message, or come up with a new one:

> ![image](https://user-images.githubusercontent.com/786704/79254004-ed233f80-7e38-11ea-81ed-0376ce30c3ba.png)

**Comment by jbalboni** [comment]
What we do in other cases when primary care isn't supported, is we fall back to the request errors and show those. Since that's the more basic path.

In this case, I think if we moved the past clinic check to be called at the same time as the rest of the checks in `eligibility.js`, it would act like the other direct scheduling checks and fall back to request errors.

Like you said, this is pretty rare. And it won't happen at all until DS is enabled again.
