### ISSUE TITLE
Flipper UI access for Peri McLaren

### ISSUE THREAD

**Issue by pmclaren19** [department-of-veterans-affairs/va.gov-team#74499]
### Your Name

Peri McLaren

### Your GitHub handle (Flipper UI access is managed through GitHub)

pmclaren19

### Team, Role, and Company of the target individual

Benefits Management Tools & Decision Reviews, Software Engineer, Ad Hoc

### Please confirm if you are on Atlas, Platform Team Roster or are a Federal User

- [ ] [Atlas](https://dev.va.gov/atlas)
- [X] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [X] Lesser Environments (Dev/Staging/Sandbox)
- [ ] Production (if requesting, justify prod access below)

### Reason for Production Access (If requested)

Im doing code changes and I am unable to test my changes that have feature flags in Staging and upper envs

**Comment by lindsay-insco** [comment]
User found in VFS Roster

Access to Flipper lesser environments granted.
