### ISSUE TITLE
SOCKS access for [Vanson Samuel]

### ISSUE THREAD

**Issue by binq** [department-of-veterans-affairs/va.gov-team#74490]
### Your Name

Vanson Samuel

### Your Email

vanson.samuel@va.gov

### Your Role and Team

VFS/VYE (Verify Your Enrollment) - Backend Development (Ruby on Rails) [GovCIO/Decisive Point Consulting Group]

### Product Manager (PM) name and email

Darla van Nieukerk - Darla.vanNieukerk@va.gov

### Product Owner (PO) name and email

Jason Wolf - Jason.Wolf1@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC0iKPkzc395JqS2nZCeJPqf4XHn8NpdntUntp0PbYHetyincxMyi2xA/EvtQw6ADgqh5BG2vJnW7Q5NB0jiaiZUiZaSao3Vi2DHFIP1JOlX2jnZ0IoBRv4DhZ6KSqCTSaPhw03tnv6qwpfibr48qxbSdEpn4ndKSyNlzl84TTGrUrupKHiUUZXEhIeC+tME67Qgbc4lrn03XJsN/hQmf+toU/3bCnxijn2h6ywX+56dim2q94e7FJFZW6CNzSUh6vMbIAvnYmOS1HhR6Z2hIjiTcbJi+yC8LJw6GNoQZhxF/lriN8mbGgBOTdC/ipz9zRrpZfT+ea+5nWaqEXu4joom0QOv3+LttDYsM+RPWGSSo0oYT37yj/TbpPN0e0AYD9RodRex2ftOrtj8Zxi2xcCq4fzqTOF1kC4rxB6Hlg3IRy+qua8QCDo4S6pnWUHKgSqlDZZgIUms3p3KMft1fo9LR1BSaFxK2zX0v5tveEoXeg18Jo++wshOrjUtEwi6SU= vansonsamuel@DESKTOP-S2VB5IR

### E-QIP Transmittal Confirmation

![298747542-f22ec4d5-255d-4a1b-bbf0-86effe283d06](https://github.com/department-of-veterans-affairs/va.gov-team/assets/37637/74366df7-6150-4adb-9b0c-4df4aee20d01)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by barbarello** [comment]
@binq Access granted ✅ 

Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html 

Reach out in #vfs-platform-support if you have any trouble.
