### ISSUE TITLE
Station 562 follow up (Find trouble submissions)

### ISSUE THREAD

**Issue by kjsuarez** [department-of-veterans-affairs/va.gov-team#74495]
Context- In this ticket(add link) we found a submission for a station which the user had never been to. It was later discovered that some unknown number of VBS copay statements include the wrong station information. This can be seen by comparing the copay's station number to the 1st 3 digits of the copay's account number (they should match).

In an attempt to determine which FSR submissions have been effected by this issue, write a script which compares every copay FSR submission's reported station number with the stations associated with the given user. If the user has never been to this station there is an issue with that FSR submission.

**Comment by kjsuarez** [comment]
List of Submission IDs that meet the criteria:

> ["333f4701-834c-4534-aec2-37d51f4d8d2f",
> "ba08278b-0144-46ad-b924-b2916ee64e9a", 
> "93b85b1b-bedf-4868-9651-63e5f0821d02",
> "4bf1fccd-a2b9-4da1-8c93-d7f03cf9770f", 
> "00dd01a3-2f00-47b1-9b76-aeb853be99f1", 
> "1bea6307-75aa-47ef-a0c8-bd4a82ec9774",
> "0f2e3f0b-3715-4e39-af33-118e3ee6f325", 
> "8f83ef9d-8816-49b2-b291-d932dd4297dd",
> "047c0d74-4e02-491b-a719-90a5b9a3609b", 
> "cd17b59b-bb4e-4682-8ac1-82d2a09701aa"]

**Comment by kjsuarez** [comment]
List of Submission IDs I couldn't source an MPI profile for:

> ["be91af2b-e361-42c8-9aa2-fe2fcb2e16c0",
>  "ea7ca323-c281-45c2-b123-368c33b90136",
>  "359af9ac-6c30-4ee9-a33d-ce9eac8c35b4",
>  "21d060e5-f563-463f-976c-75df847ce966",
>  "31c22805-6890-4fe7-aa4b-2ceee02eccaa",
>  "83a7ceed-d27f-4944-8ae7-03b9b1c79b32",
>  "9a6e295c-6e72-45a2-94e3-f0944a38304c",
>  "d19f43e2-ee55-4173-9beb-d0ec20894a33",
>  "f7dc1dfa-84a7-4556-8694-647489bc28a1",
>  "f10a45a2-0fa2-4f91-85ea-49ee44d89a1a",
>  "57fe6e70-dd25-4acf-a636-e0ebef474991",
>  "d70c7afb-9b70-4c9c-9b9b-05ecb8c3a767",
>  "6764b52a-87a2-4f4b-9b96-89686d7e309a",
>  "d0586a19-ad06-4181-a741-b977e403acd2",
>  "418fd039-ca6f-49f4-9818-28d74089232e",
>  "471ebcfb-d203-44c1-a33a-9594f0b69132",
>  "55030853-d533-470d-a3f2-bd9333a4cf03",
>  "c551fc84-7574-4e63-bdef-2fd060bd8112",
>  "a80ac0ec-2628-470a-9f71-96ef5d2fc374",
>  "8639dc88-42bf-4b81-8642-b9ff07909fd3",
>  "0308da25-6c89-4042-9437-c954e8a0e5f1",
>  "b03713b8-cf27-4405-bd05-b707bd233e09",
>  "5c5f6e6b-5a80-49eb-8c35-6a2f5ec3c8a2",
>  "48143acb-f22d-45cd-ae6e-3eb55c71533d",
>  "b927c304-cf85-4993-81cb-080399e392b9",
>  "0c0b3f96-2074-413a-9eee-2230d13f118e",
>  "337a8d42-ba57-40d8-9ccb-f835ccb0341a",
>  "0b90c5e8-6b43-4fa8-8d45-9d2b31b1aeb3",
>  "0756b40f-7f73-4c5b-9e52-4bbb0b236162",
>  "509841f1-d746-4614-aa07-7a318477da3a",
>  "301c72fd-69a5-44ca-a183-1c8c710812c4",
>  "8901b082-2b1c-4687-b73d-3dca4e4fabd3",
>  "b4dd4814-e08b-4b88-8f40-40059b825721",
>  "b9bd2ebc-e4a5-47f7-8875-2ef1599fc8e4",
>  "41731212-976a-442e-9f28-c0a2fe397656",
>  "2265ecfb-f3b5-43c3-aeb4-5904d076f2b3",
>  "92753828-2857-465f-bc3d-cca3c2abab42",
>  "a24d6b58-ab2e-417d-b64b-55092d3a0134",
>  "9d434318-0e36-44a2-945d-3f51b7054210",
>  "4c9d2a9e-748a-43ac-a43d-8ffeda7ddd7f",
>  "ba217d39-dcd5-4967-8fba-20811738ba18",
>  "550ae59d-589a-4423-b7bb-0bfac2a5298b",
>  "4411ad8b-32a3-40f0-adbf-483aaf6be893",
>  "04689852-e32b-4e7d-85af-add242fa40eb",
>  "2314bacb-a2f8-4f8e-90ad-30391dc4fd9c",
>  "787a4d38-3d0a-4e7e-9c21-784316fec37a",
>  "94ea3c98-ecbf-4694-b653-7b97a3188a1b",
>  "7271e3ad-cef4-49ea-9102-920538e76d63",
>  "92c38138-f5d6-4da6-ad9b-c7549be3ab0f",
>  "3c73c66f-5550-4f9f-b8b7-3566f306358c",
>  "ec6faa83-16a5-4d29-a4a9-164ce8a125b2",
>  "41b48960-e840-4d5d-9fb1-485c184a3bf4",
>  "bae1b28c-db5e-498f-8ca1-12f23e7c797f",
>  "445f238b-0bad-40cd-acdb-0095f2d5c06a",
>  "638a5a6f-ae31-43f6-b540-3813af013ca0",
>  "5a6422b5-db75-4d86-b753-eed6d62ed6c2",
>  "e8f82a6e-7056-44bb-94d7-d14d231ace01",
>  "d8e323b9-9219-4ae5-bd33-6f5805946532",
>  "f9ecd382-9642-4733-959c-8ebc96aa0363",
>  "5c3e5ac5-cd15-4f51-93c4-c651b82a9478",
>  "d8d32e78-67c5-4c09-baba-387e9817b9af",
>  "628f1e30-5cf3-487e-aee0-0630eb56533a",
>  "a19eb2d6-f46a-40d2-954b-e012835ce00e",
>  "b9f7aa1d-5305-47e6-bda7-c952407b9a4b",
>  "a78e0dae-621d-49fc-89ff-df2d2135c77e",
>  "df679320-f8cd-4420-bec8-521a9f00de0f",
>  "69f281b8-92b7-4723-82b7-0232214686a0",
>  "e5e668a8-ef06-4dbd-a030-6bdba8c3526a",
>  "6c798b0a-12d2-45b5-a9e8-fc1ba1ae389d",
>  "233f3d53-9012-4613-824b-ec919a313e45",
>  "02841037-b2f6-43bf-9fb1-4d67bf33a63b",
>  "a114191e-30ac-470a-b1b3-a36b7dfa2c34",
>  "2ba56ae2-42cc-47eb-8692-50261b6bb6ca",
>  "a9ab2f80-cb3c-4262-af47-3ea622e39bff",
>  "276848fc-ead9-435d-b323-ebeefe7f3863",
>  "689c1a23-0a12-4fc8-8cd7-ffcbf95d2d11",
>  "cfa0802c-9b5a-430d-83e0-69b8904415e1",
>  "e2b529ff-b0b4-405f-ad31-23969e9615aa",
>  "b5758ce6-c131-4b63-8287-b34fb465cb27",
>  "4a23b041-9cc7-4643-8848-61321be859ef",
>  "cd2307ad-a3c0-4887-890f-7d27d6c70038",
>  "19fe3f4d-68b3-48af-9e2f-709055283d36",
>  "476f4102-5fb7-4c57-bfbe-aa433ff9a386",
>  "74baefc1-76e6-4388-98f0-28caf61cfa70",
>  "79fcbd30-df16-4e48-acb8-f15b2cdf3feb",
>  "8c5f4a3b-52a3-4744-9d57-805f01ef1ac9",
>  "3a63e995-adde-4a99-a157-a14307afcca1",
>  "da17c60a-c7e7-4212-8342-a530e27dac50",
>  "d9be8957-3dd0-4347-aa41-ccafdc7e59ce",
>  "ed5b33e8-f943-4f43-b5e0-3f2e33f40529",
>  "72a5497d-32cc-4ad1-a8f2-b4bfd0e52afb",
>  "3fb709f9-3210-443a-84b2-3aaa36e421e4",
>  "cd5f6d83-d1ea-46b8-ac11-c2b7db6be04d",
>  "a6b1d26c-0723-4a38-993b-45702ae10e26",
>  "f106eeb1-7bdf-4442-b2bf-de80d369afc3",
>  "1d363f3d-6ed1-494f-88a5-c4f8fb530bed",
>  "d6a7f7ee-52c9-4c2d-946d-b6f203be60f5",
>  "437a4cae-a7eb-49da-8795-0fef6a3b3c6f",
>  "698ce9cd-cf5f-4f3e-be61-f81d212259fc",
>  "6d6990a2-d5f1-4b3b-8c5b-5dcd4486a50e",
>  "0fa33e10-b36f-473b-b523-262ba1c314ff",
>  "59fc0865-d70e-4fd6-9dd0-5efc2409b147",
>  "46353f62-ea82-4377-a7fe-b8920ad5c60b",
>  "a7571962-f81e-47e6-ab84-2b2a8fa5d30e",
>  "6c4006a1-e34d-484d-aed6-ffd9d831d722",
>  "de90d063-ffc0-470d-84ee-87c10378a1bd",
>  "556fdda6-abbe-49fd-8805-3e0f8488ba76",
>  "be027817-cec1-4aa9-9003-9ae65f9e8a66",
>  "f7d8a860-12e6-466d-83e6-4682806b40b0",
>  "cb430c57-bfe1-42e5-a3ff-936e49ed8bc4",
>  "86aed7fb-12a3-4b3e-8f0b-d6aa74931e89",
>  "b6e928e5-80e0-4c4f-8174-c1d96b5031f6",
>  "73614dbd-9687-4bc7-84ca-709a3c1c0534",
>  "01cf562a-a181-4f28-9ac4-71de29aa4c6d",
>  "efbb1219-56bf-4ff5-a79a-0c1746dc37ce",
>  "ba6e23a2-1751-4c10-8859-e9d4f3d91942",
>  "abb604f0-7679-4edc-afee-5ea14f217750",
>  "458416d3-4500-46ac-a057-750e6ef26d72",
>  "dd7aa17a-0e5b-45e3-85cc-443806d9ba39",
>  "2760cbe3-4bd3-4712-bccb-d6c392110557",
>  "3cc8e6e0-dd5c-44a0-95d9-179ad29d74e2",
>  "775ea23c-64ca-49df-b4c5-1d4ea0d5bfff",
>  "4897b343-9528-40fe-a7ea-6fc29a1dc914",
>  "5d045b07-b4e5-4b91-98fb-74af251fe495",
>  "cd224da8-7fe5-4b4b-beac-0ce9552d6d19",
>  "f1f8f896-dad0-4406-9387-36e017afc348",
>  "cedafc43-a631-42e0-94de-45bebaf4f204",
>  "82123a79-d9a6-4177-b7b0-66ed0470f60f",
>  "921f9f5e-2e18-4532-b005-909abe627a8b",
>  "d7f53abf-2071-45da-9d0e-88f12b695dcd",
>  "ff266920-d578-4aed-aa53-c043b5bfdf77",
>  "9ce997c8-9b5d-4cc9-9716-51a9254035be",
>  "89f0c357-a099-485e-9aa2-97af59b18df6",
>  "1f30fc6c-22da-4028-9ca8-e5d38e858f0b",
>  "53f5c32a-e75a-4023-9841-a4f134bfdf92",
>  "901feb28-8ff6-48b5-80f0-984f1649665e",
>  "f760c7ed-3141-48e1-81db-bd76f21deda1",
>  "cacd4fed-3138-403d-827b-8f1b969bedf0",
>  "23e2a13d-1fcc-4694-81aa-908d1976a050",
>  "3323475a-46aa-4817-a9b5-8b81dbddb2f1",
>  "754ba045-ddd8-4277-b129-d83492e44f39",
>  "7ee37460-7a0a-4134-89c8-4ee31bf3ff87",
>  "ab399419-3a72-443f-8ab8-7596a991b160",
>  "69159915-b602-4609-a9d3-51e066d66984",
>  "ee18ea2c-9fc0-4f7a-b4a7-4a1542e790ad",
>  "46d62fd1-b660-41a1-9406-91c2270bbede",
>  "3420ceb9-bdb4-4bfa-960a-e2df79635524",
>  "2b6131de-340c-486d-bafc-cca5579b2366",
>  "116ee670-c637-4c1b-85fe-327669124e52",
>  "1dc63c36-ec24-417d-9da0-9b39993bb225",
>  "31eac46a-c003-4235-8da6-a3f4ddbcdb11",
>  "08befc37-add1-4b6d-a7de-1c3a5a1c3b38",
>  "4641a9e9-6086-4a32-8207-774f25f20310",
>  "3fe8ec0a-746a-400e-8992-1cf95361034a",
>  "08979d6e-dc83-43c5-9400-afb7e063c06a",
>  "b38f3f7f-ca0d-4a8c-802d-378260d6b50e",
>  "0a57be13-6f4e-4bf1-ba3f-833a6723b766",
>  "01b45788-876c-4d45-bb15-6f32f752752f",
>  "b69795f1-f731-4dba-a8ec-e828c4128a74",
>  "5fa4c157-6a77-4297-a9fd-ff9f24f373c7",
>  "5ee3072d-6c0a-4339-a3ea-a3fa4a26f7fc",
>  "8aaf1640-1267-4c8a-bb60-d2e6c182d72c",
>  "2d02180d-095e-41be-8313-b590b29b86f5",
>  "72437f3c-ef87-4077-a02d-087151ef1fdb",
>  "0c50485b-aee8-447c-bed1-e5e0a4516db9",
>  "a01a1567-c094-4072-9447-7c59548020e8",
>  "66d23fcd-686d-4ac8-b83a-26f9232e1189",
>  "d468aa7d-0fe3-46f1-8226-6e5c0decb58a",
>  "cb6934ea-33bb-4b35-bbc6-2267e11d0255",
>  "2192669e-2fd2-4c15-b49e-929deacacb13",
>  "409b0ed8-3ca3-4995-b0a3-4bdbf9dba623",
>  "b3b6df61-34ae-4bc9-a261-4b94d5a02e30",
>  "7f266d1d-b3f2-4f79-83e3-b999dd787b59",
>  "efb61610-3936-4f07-ac27-853ec5eec1eb",
>  "ad9227d8-677c-48a1-af99-505d34a976e9",
>  "1eb15f53-66c1-4780-94ce-24d344d26cc7",
>  "4dd35687-df4c-4214-931f-0630fb0c7893",
>  "87fe9e70-c542-41bc-97c2-df5e64943305",
>  "158943f6-b50e-42a1-a1eb-55d03d28f9f6",
>  "0cbfca8c-28d7-4375-a069-07fbb530e181",
>  "fa77e131-b1d2-44cd-8aed-98b1c807f7cf",
>  "8292ce92-e3b5-4e76-99f3-71b385cb5774",
>  "fe49c15b-bdef-49e3-85e6-0dce7f6b6e27",
>  "131a7cc6-889b-49e0-bcc4-9fb1b5d2e210",
>  "cd653c06-4578-4cd1-9e0f-06ed81c6b27b",
>  "8845a5a0-c246-4190-b950-75434e69bbb1",
>  "2ca62a18-83ce-4c9b-89d3-971ae754b068",
>  "e101936f-a4d3-47a1-82c0-3b3991146a3b",
>  "5b851765-b1a9-4791-a934-71856d22eded",
>  "a0581f60-3bd3-468d-9705-c0846fe7d72e",
>  "158a86d1-aea8-4e99-abc6-3906a76e53b2",
>  "1894f644-3b53-4196-8a1b-cb966d18fd00",
>  "a7b0386b-4f87-4c27-852a-03b5b3e75881",
>  "f91dc456-7b2a-4f9b-8d8c-f9cee0092307",
>  "30c70613-3d93-4be0-bc86-1370c7155f0b",
>  "59ec2577-c0ee-459b-9ef7-754e577299a6",
>  "a111fddb-41bb-41ae-98d2-52a5cb619798",
>  "e30dc48c-eec7-438e-a76c-b6de3b6f6c7a",
>  "771eac45-47f6-4da6-b8da-f25cb31cf265",
>  "11093596-9e98-4e85-b747-25c11fb601d2",
>  "0fe1ebea-eedd-40ef-b1e6-427d0c8636b5",
>  "edcb05ed-0ba6-4fbe-98ed-f07e95cf110e",
>  "1ff60640-3bb1-40ed-8e0e-8e9d22f575c8",
>  "2418b3b9-a22c-4da4-911e-a1cd352e95e3",
>  "f0199c70-2de0-457c-af0b-a8dc77de289e",
>  "27e84c84-5b9d-4f7c-bd04-0d0fb44c7d7c",
>  "bffe4069-9614-4f6d-8204-ecbd380e4a87",
>  "1cbaa6b3-9577-4b9d-80e7-41bf7f46ddf6",
>  "085ab6cd-d50a-4164-ac79-1a087c1db4d3",
>  "b1c4b2a0-d293-4875-8024-498a87abfef6",
>  "3800200d-cc95-4e99-8ea7-0714ffca4559",
>  "723d0d6d-f7b0-40b3-8371-4a23efbd404c",
>  "9e5b634d-df06-4177-9158-ce25addaf87f",
>  "c4c249ef-8e54-408e-923a-63eca4cca3af",
>  "545d7c00-3afe-472f-b7d9-076a6063c47c",
>  "d16ff194-08a3-49a7-8c9d-6f6f44dae3d0",
>  "8471f273-5503-433d-8427-39356f71fcc5",
>  "ce589463-dbad-417e-a351-4968facc5e53",
>  "f78bc260-c300-4f03-b0e7-835ddc7deb42",
>  "ad343a01-6e77-490a-8c39-3e9041e4d739",
>  "9e838d31-fb42-405f-ab36-8f0fe8587940",
>  "3856dd77-8ff1-4d0b-916d-cbc1853a0d18",
>  "28de0fae-f1e6-4c18-a210-8248ff83efd1",
>  "34699e8b-7528-49f6-99ae-fe8d7206dcb5",
>  "fee8d5cc-d93c-4972-bd64-3e6024b6ca91",
>  "74e0288f-d2d2-4d45-8190-8278ae82b02e",
>  "5fa5578c-2638-4ac8-a17a-7d85b1d0526f",
>  "e248f0a3-9e85-4eeb-a99c-67b981cbef86",
>  "d8fe4b4b-9791-448a-966f-0d652a1f677c",
>  "b3e2d2da-7ec9-410b-bb67-003f06cb3af5",
>  "95fff1cc-594d-4efb-956f-c48097a484b6",
>  "cedf917c-018d-4e17-a820-9800577d46fa",
>  "3580c292-2363-4cfc-b582-3a9d9796c362",
>  "fb1f13e1-e6c3-4117-be78-18c56b0b04e2",
>  "d7f84771-3edc-4c77-9949-1817bea03944",
>  "b65c91e1-cd90-4029-84ff-4ab813d69c7f",
>  "dc5739fc-f104-49d9-b11e-ec38507a8371",
>  "2e802801-8df2-465e-bf90-41b1493f826f",
>  "93e70eec-ed89-4747-8739-46bc3b27ab2c",
>  "85a32242-287d-4524-a8c4-76c45a452ca9",
>  "3f256727-7245-4fad-86f9-d4251fdbe61b",
>  "0459ac16-053b-42bd-904d-f1928bdd540d",
>  "672b2634-bad3-418c-ac70-e047de7dfa58",
>  "3ff991e5-d74d-4a1b-8c52-c8a290a454ee",
>  "46d3460e-05d1-4c0d-91ab-d64b7122a886",
>  "2b90777d-156a-4d19-a012-59b2d54e6646",
>  "60fd114a-a91e-4798-9bd5-fca2011d2248",
>  "6feaff8c-ef88-40d9-8904-b825679e3492",
>  "531c43ed-3cb8-4126-bff8-108a00b45058",
>  "b1ce16ba-8ef3-4dad-905f-ed22e3355249",
>  "75a700d5-2a34-40ab-b151-c2ce88dd2052",
>  "e8bee526-8b0b-4f65-a7b8-25d84538e23d",
>  "06c6a11e-5bcb-4919-b1d7-2dafc7417a49",
>  "55cfb7e6-cbff-4588-8e2c-e35e33514811",
>  "d439d20e-b131-4c1c-88f1-b368efe22d2b",
>  "70b855a7-f2b4-48ed-ba8e-051d428cde5f",
>  "338ccef1-ab71-4fe9-8b10-d92ca46f4c7a",
>  "755d4d33-506e-4197-8de7-5b423ee04235",
>  "100b77b7-6997-4c37-a09e-a5ff4c86041e",
>  "39d402a3-c4ae-4234-bf96-48d853ae8ced",
>  "befc2f74-091c-425c-a0d0-123a52ebfa42",
>  "50af8782-a4e7-406a-88bf-64e49362cd92",
>  "6ea8b524-5814-4a3e-a9fd-792bf0a0a25c",
>  "57e938ee-79be-4baa-9481-e27330c8eaf2",
>  "5584fbad-31d6-4172-b4e3-2a3f270b8554",
>  "0dafe81a-6f8c-493f-bca7-3caa19a264c5",
>  "00666932-2f85-4ef1-b42b-745aaee9755a",
>  "d4344ed1-d96b-4c54-a0bc-a2230e973c19",
>  "34437b04-5673-44a8-9c35-6edf140893a2",
>  "9514d918-97fb-4115-85d2-f59cdf543aa4",
>  "015cb4a5-91ec-43d3-bebd-ff185d70bc73",
>  "9459efc2-2b3f-433c-a6a8-b1bb1b6d2a21",
>  "a0ecc967-8c74-4565-9222-11104cd7f581",
>  "10b49898-04c5-4360-bd7c-e3a0d22a5578",
>  "fc7ade6e-55d0-4ad7-bd51-285695a06093",
>  "1217f2e9-8a44-4bcf-8f9b-4d0464ac3099",
>  "a8654d89-287c-4ce6-a84e-ad5a0dddc881",
>  "89703521-5afe-42b8-9a2a-a569b053c420",
>  "b2b36156-e184-4f6f-9efe-0fb9f204960c",
>  "2e7a98f2-f818-4cc0-b3c2-21ae1d746dde",
>  "dfd86235-1b37-4c4d-9252-9d6259553d76",
>  "c11a7a9a-f02b-422e-aefd-d473efbb6552",
>  "9a9e9387-c568-4d1e-9559-d4050e8dd266",
>  "ace1efe4-1d51-4eb9-9d71-e6e4b1a11b3e",
>  "dd3e6c00-3b1a-42e5-8694-76d54a903c82",
>  "a9b76178-cf39-47ae-8c34-dc50

70c8a751"]

**Comment by HeatherRienks** [comment]
Per Kevin: I was approached by Mike Dewey because a user submitted an FSR for a copay whose station the Veteran had never attended.

This is like a Veteran in Florida requesting debt relief for a copay from a California hospital.

It became clear that everything about the copay was legitimate, except for the station metadata.

The copay data we receive is parsed by VBS from large files containing thousands of copays.

VBS's parsing code contained a bug, in which the last copay on a given page would pull its station metadata from the first copay on the next page.

In this way a copay from station #100 for Veteran A could source its station data from a copay from station #600 for Veteran Z.

**Comment by kjsuarez** [comment]
Bad submissions correlated to bad copays
```
[{:submission=>"333f4701-834c-4534-aec2-37d51f4d8d2f",
  :id=>"6b6e6e79-eaf1-49d4-9946-18ff4a01a347",
  :acct=>"502",
  :station=>"520"},
 {:submission=>"ba08278b-0144-46ad-b924-b2916ee64e9a",
  :id=>"c0f15e3c-0661-463c-a3bb-8fae74aaa655",
  :acct=>"442",
  :station=>"517"},
 {:submission=>"93b85b1b-bedf-4868-9651-63e5f0821d02",
  :id=>"00b1b824-ed69-4fb8-a015-aba498120e3a",
  :acct=>"542",
  :station=>"562"},
 {:submission=>"4bf1fccd-a2b9-4da1-8c93-d7f03cf9770f",
  :id=>"6b6e6e79-eaf1-49d4-9946-18ff4a01a347",
  :acct=>"502",
  :station=>"520"},
 {:submission=>"00dd01a3-2f00-47b1-9b76-aeb853be99f1",
  :id=>"6b6e6e79-eaf1-49d4-9946-18ff4a01a347",
  :acct=>"502",
  :station=>"520"},
 {:submission=>"1bea6307-75aa-47ef-a0c8-bd4a82ec9774",
  :id=>"6b6e6e79-eaf1-49d4-9946-18ff4a01a347",
  :acct=>"502",
  :station=>"520"},
 {:submission=>"0f2e3f0b-3715-4e39-af33-118e3ee6f325",
  :id=>"ba2c7c53-3a7a-4028-b1ea-473fd603fd9a",
  :acct=>"549",
  :station=>"687"},
 {:submission=>"8f83ef9d-8816-49b2-b291-d932dd4297dd",
  :id=>"09d3d4f8-4b3c-4e3e-b1a5-2136f5afd312",
  :acct=>"657",
  :station=>"672"},
 {:submission=>"047c0d74-4e02-491b-a719-90a5b9a3609b",
  :id=>"8e614af1-00a3-47ae-be50-f61309c01167",
  :acct=>"650",
  :station=>"757"},
 {:submission=>"cd17b59b-bb4e-4682-8ac1-82d2a09701aa",
  :id=>"12ab8929-1195-42ed-ba8f-bde64cb2ffdb",
  :acct=>"632",
  :station=>"667"}]
```

**Comment by HeatherRienks** [comment]
VBS & VODA Devs met today (2/5/24) to discuss further. Kevin emailed Mike Dewey the 10 transaction ID's affected by the station parsing issue, including transaction ID along with the true station number and listed station number.
