### ISSUE TITLE
10-7959f1 - Generate the back end form model and mapping

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#74508]
## Issue Description
Build back end structure of the form in our module. ([Dev guide](https://docs.google.com/document/d/1aKlQWVXnulfCevejKu37y7cusNK5F8-C/edit#heading=h.gjdgxs) for reference).

---
## Tasks
- [ ]  Generate a model and mapping file for the form

**Comment by balexandr** [comment]
This is a duplicate of https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/73933
