### ISSUE TITLE
[spike] DR | Figure out how to unlock PDFs to avoid "Invalid PDF content, part content" errors.

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#74503]
## Value Statement
**_As a_** Veteran
**_I want to_** submit locked PDFs as evidence along with my NOD/SC, without issue
**_So that_** my appeal can be evaluated with all the information I believe is relevant.

---
## Background Context

[Roughly 27%](https://docs.google.com/document/d/1FDWa9v1ooG4L__RODnAYZtcqCt4La1azTyZ6vkEr6KA/edit#heading=h.bblqm56b9rpq) of the evidence submission errors we see downstream have the message: "Invalid PDF content, part content."  Locked PDFs cause this error. We already have code in place to identify and unlock locked PDFs, but somehow, locked PDFs are still making there way into S3.

The goal of this ticket is to determine how to more reliably identify and unlock all locked PDFs.

## Tech Tasks
- Time box (10 hrs)
- Look into the following:
  - [x] Conversation with EMMS to get their perspective.
  - [x] Whether there are any flaws in the existing PDF-unlocking code.
  - [x] How other teams or folks on the internet reliably unlock PDFs.
  - [x] How PDFs are locked, and whether there are different ways of locking PDFs.
  - [x] How PDFs are unlocked, and whether there are different way of unlocking PDFs.
  - [ ] Whether there are any substantive differences between successfully unlocked and uploaded PDFs, and PDFs that could not be unlocked.
  - [ ] Whether VA's version of PDFTK (which is out of date) has anything to do with this error.

## Definition of Ready 
- [x] Derek has pairing support for AWS S3 access

## Definition of Done
- [ ] Based on research done in this ticket, we have some educated guesses for how to resolve this error, and have follow-up implementation ticket(s).

**Comment by saderagsdale** [comment]
- Possible first step: See if our unlocking code is the problem. (@saderagsdale update ticket to reflect this task) If not...
- Next step: Pull in LH and an EMMS dev to find out the strictest limitations.

**Comment by saderagsdale** [comment]
Can be deferred until after NOD testing is complete. We need all hands on deck, and this sits lower in priority.

**Comment by HeatherWidmont** [comment]
Zach is scheduling time with someone from their team to work through how this is happening. In advance of that, we should check whether there are any flaws in the existing PDF-unlocking code

**Comment by HeatherWidmont** [comment]
@dfong-adh spent some time looking into the flow to figure out how the PDF unlock was working

**Comment by dfong-adh** [comment]
Summary of findings from yesterday:
pdftk does not support newer encryption methods - it fails with this error message: `pdftk.com.lowagie.text.exceptions.InvalidPdfException: unknown.encryption.type.r`

`qpdf` does support newer encryption methods and can unlock those pdfs.

**Comment by saderagsdale** [comment]
Waiting for confirmation to meet tomorrow with CMP/EMMS. Questions to ask CMP/EMMS dev:

- What is the password validation logic, and what's supported? (ex: newer encryption methods)
- How are we validating the size of the pages, PDF file size, user password vs. owner password.

**Comment by dfong-adh** [comment]
Additional info:
frontend detection of encrypted pdfs is done via https://github.com/department-of-veterans-affairs/vets-website/blob/c8afd394893038c06eafe18319868a10ffbc4738/src/platform/forms-system/src/js/utilities/file/checkIsEncryptedPdf.js#L11

**Comment by dfong-adh** [comment]
Notes from conversation with EMMS:
`Invalid PDF content, part content` error is downstream from EMMS - this is after the password check
PDFs are split up and processed by pages so errors can be caused by a specific page. Suggestion is to try to replicate errors by opening up the specific PDF pages in Adobe Acrobat.

Q: Any idea why the PDFs that Veterans upload to S3 would become blank upon uploading to S3? This is before we send anything to Lighthouse/CMP.
A: PDF layering/flattening can be potentially cause issues during processing (need more investigation with how PDFTK processes pdfs)

**Comment by dfong-adh** [comment]
Several PDFs we looked at today for the `Invalid PDF content, part content` error could not be opened in Adobe Acrobat Reader or Google Chrome. We checked the headers of the PDF files and they were different versions (PDF1.3, PDF1.7) so there's no trend of a specific version causing the errors.

**Comment by dfong-adh** [comment]
I've compiled a list of several PDFs with errors and one that needs a password. Working with @anniebtran to make a list of evidence issues so we can work with Kimberley regarding reaching out to veterans for the evidence files.

**Comment by saderagsdale** [comment]
@dfong-adh lets catch up before you reach out to the contact center

**Comment by HeatherWidmont** [comment]
@dfong-adh will create a follow up ticket
