### ISSUE TITLE
IPP - Design improvements for Veteran 'What to bring' screen 

### ISSUE THREAD

**Issue by lmorris3** [department-of-veterans-affairs/va.gov-team#74520]
**Problem:**

During Veteran Usability Tests, Veterans had a lot of questions about elements on the home page, including the accordion menus, the perception that the page was a form that they should input information into, what a case number was for, what ID types were not going to be accepted, etc. They found the information too small and observed that there were too many clicks on this screen.

How might we: 
- Improve the UI on the home screen so that Veterans do not think this is a form to fill out?
- Clarify the types of ID that are accepted and those that are not? (separate story)
- Reduce the amount of information on this page so that Veterans do not have to sift through so much?
- Reduce cognitive load on this first screen? (Use plain language to explain or describe ID types? Reduce the number of clicks a Veteran has to make on this screen? Remove references to Case Number or clarify when they'll get that - separate story?)
- Clarify the purpose of verification

Possible Solutions:
- redesign hierarchy to a more recognizable pattern
- don't hide definitions in an accordion, lay out all info
- consider a narrative format, rather than list
- consider reference to case number (do we need this here? is it confusing?)
- do we need this first screen? Why do we need to present so much information so early? Jump right to location selection with brief explanation of ipp (consider the person is coming from login.gov account setup)
- use larger font and less text/use icons to draw attention to most important info
- 

**User Story**
As a Veteran, I need to understand the in-person proofing service and what I will need to do so I know I want to proceed with in-person proofing (or I can change my mind and go back to remote).

**Acceptance Criteria**
GIVEN I have selected in-person proofing and signed in with login.gov
WHEN I view the first screen
THEN I see information about what to bring in a "card" format
AND I see the most important information in bold
AND the progress bar tells me I'm on the "What to bring" page
AND I can continue to the next screen to choose my location

Notes/Details

- [x] move blurb about not verifying in person to the "sign-in screen"
- [x] reduce amount of text in confirmation case number section
- [x] move blurb about "authentic and unexpired ID" to the top of the whole screen
- [x] consider using bold text for all important info
- [x] update progress bar step to say "what to bring" instead of "home"

**Comment by skirkman16** [comment]
Reference 
<img width="1197" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTcrQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c22180ba5fb00232b50a83fc1059ecf7a2c885d0/Screenshot%202024-01-25%20at%2010.54.37%20AM.png" alt="Screenshot 2024-01-25 at 10.54.37 AM.png" />

**Comment by SophiaPhilipMO** [comment]
Decision point - Following research synthesis need to review findings to clarify changes to be made that will impact flow.

**Comment by JKG199** [comment]
Ready for Review 
<img width="602" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeitHQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b13adacfdc56e2fe346ac6a4cbf771ae57f2e689/Screenshot%202024-02-23%20at%209.35.13%20AM.png" alt="Screenshot 2024-02-23 at 9.35.13 AM.png" />

**Comment by SophiaPhilipMO** [comment]
Reviewed and added comments @JKG199. Some suggestions, check off the boxes in the ticket once they are done so we know what you did or if you made adjustments that changed the decisions on what attributes to change.
I also recommend tagging people in comments when the ticket is ready for review otherwise we don't get notified you moved the ticket to review/qa

**Comment by JKG199** [comment]
<img width="620" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWFhQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--74c35ab6b9e4be02ce057b5dfea67a2a3a7c9ed7/Screenshot%202024-02-28%20at%203.25.33%20PM.png" alt="Screenshot 2024-02-28 at 3.25.33 PM.png" />
