### ISSUE TITLE
10-7959f-1 - Build Intro and Confirmation pages using forms-library 

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#74537]
As a user, I want to see the intro page for the form so that I know what the form is about. I also want to see the confirmation page so that I know my application has been submitted.

Build front end of the form using the forms-library:

[ ] Using template, finish the generated Introduction page
[ ] Using template, finish the generated Confirmation page

Acceptance criteria:
- intro page following [guidelines](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/content/form-introduction-page-template.md) 
- confirmation page following [guidelines](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/content/form-confirmation-page.md)
- use v3 components

**Comment by marywang2** [comment]
Waiting on tests to pass.

**Comment by marywang2** [comment]
Waiting for approval from platform team.

**Comment by reiting** [comment]
This has been approved and merged.
