### ISSUE TITLE
IPP - Compare Veteran Intake Application against VA A11y checklist

### ISSUE THREAD

**Issue by lmorris3** [department-of-veterans-affairs/va.gov-team#74531]
**Problem:**

In order to ensure our applications are accessible by Veterans who rely on screen readers and other assistive devices, we need to meet all a11y guidelines and standards.

Solution: VA has accessibility checklist - we'll start here to identify any remediations we need to make to the applications.

**Acceptance Criteria/Def of Done:**
- use the VA a11y checklist to scan the Veteran Intake Application
- identify all discrepancies between the Veteran Intake application and the checklist
- document all discrepancies
- use this: https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review

**Comment by lmorris3** [comment]
This can be broken down further - we could have a story to identify improvements, another to discover existing plugins, etc to resolve, and another to implement highest priority improvements. 

Decision is needed on long-term design system (VA vs. Login.gov)

**Comment by SophiaPhilipMO** [comment]
Reviewed requirements and identified which tests will be done for pilot 1 versus post-pilot
