### ISSUE TITLE
[CST][Bug] EVSS::RequestDecision silent failures

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#74549]
### Value statement
As a user of the CST
I want to be able to submit 5103 requests regardless of my status as a Veteran or not without them silently failing
so that I can exercise my option to expedite my claim decision

### Background
We are having seeing `EVSS::RequestDecision` Sidekiq jobs end up in the dead queue after exhausting their retries. From talking to EVSS it seems that these are related to the users who are initiating these requests not having File numbers. This indicates that they are non-Veterans and falls into the same category of failures as the `EVSS::DocumentUpload` failures

### Tasks
- [ ] Identify a path forward for preventing these silent failures

### Acceptance Criteria
- [ ] We are not seeing `EVSS::RequestDecision` jobs end up in the dead queue because of missing file numbers

**Comment by jerekshoe** [comment]
We are hoping at this point that moving to Lighthouse Benefits Claims for these requests will provide us a good path forward to fixing this issue. They have not finished developing this feature however, so we may have to wait for them to get that finished unless we come up with an interim solution

**Comment by HeatherWidmont** [comment]
LH said they will get it on their roadmap at some point, but they have a higher priority item to work on right now (POA). This will be first on their list after that
