### ISSUE TITLE
Copy/Messaging for Health Care Application (HCA) "status" section

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#7455]
Related ticket Update the Health Care Application (HCA) to use new endpoint behavior #6466 and #7457

## Background

We need to figure out how to communicate the following three statuses to people who submit the health care application:

- **Received**: The application has been successfully received by the backend database.
- **Not received**: The application failed to send and was not received by the backend database.
- **Pending**: The application has been sent by the frontend but we're still waiting on a response from the  backend database.

Some things to consider:

- We already have a confirmation page, so there may not be anything else to do for the "Received state.
- We should have some sort of communication that submission is in progress. Idk if we show a spinning animation or "this may take a few seconds" message, but we might want to consider this if we don't.
- If an application is still pending, what should VA.gov show? What should the user do? 
- If the application fails to send, what should VA.gov show? What should the user do? 

## Tasks
- [ ] Provide messaging/copy for each state

## Acceptance Criteria
- [ ] Messaging/copy has been approved by Peggy/Tressa

**Comment by Samara-Strauss** [comment]
Like #7457, this is no longer within the purview of our team. Removing our labels and assigning to health care team.

**Comment by julieadair1** [comment]
@jparker0425 - is this something we need to prioritize?
cc: @dillo
