### ISSUE TITLE
Screen reader checklist: Zoom "share screen" instructions incorrect after Zoom interface change

### ISSUE THREAD

**Issue by coforma-jamie** [department-of-veterans-affairs/va.gov-team#74557]
### Description
Zoom changed its share screen (and therefore, share sound) interface today (at least on MacOS):
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/135633989/5df95ea6-4b6c-40f6-8490-750fc62df69e)

The current Screen reader checklist says

> Tab or navigate past the “basic, advanced, and files” tab menu items and find “Share entire screen.” It should be the first item in the list of windows or applications to share. Use your space key to select it.

This is now incorrect. There doesn't appear to be a "Share entire screen" option - you start on the "Basic" tab, and the main desktop is selected by default. It also takes 10 tabs (from initial focus) to get to "Share sound", which might be worth adding to the screen reader section.

### Relevant URLs
[Research - Screen reader checklist](https://depo-platform-documentation.scrollhelp.site/research-design/screen-reader-checklist)

### Which type of team are you on? (Platform team, VFS team, or Leadership)
Sitewide CAIA

**Comment by coforma-jamie** [comment]
cc @briandeconinck

**Comment by jknipes** [comment]
HI @coforma-jamie, thank you for flagging this. We'll take a look, and will work to get any updates reflected on the website.
We will provide further updates in this ticket. Please feel free to reach out if there are any questions.

**Comment by taylojill** [comment]
Updated instructions provided by requestor, see https://github.com/department-of-veterans-affairs/va.gov-team/issues/75385
