### ISSUE TITLE
Remove widget on "download VA benefits" letter page

### ISSUE THREAD

**Issue by strelichl** [department-of-veterans-affairs/va.gov-team#74561]
## Issue Description

Removing React widget in favor of the mobile banner.

Background from Jill Adams:
> On the Download VA benefit letters page ([front-end](https://www.va.gov/records/download-va-letters/) // [CMS node](https://prod.cms.va.gov/node/471/edit)), there's a react widget (letters-mobile-cta ) that creates the alert in the pink square in the first screenshot below.
> Public Websites has shipped mobile banners that appear on several Benefit pages. The mobile banner points users to the mobile app, e.g. in the 2nd screenshot. So: we'd like to deprecate the React widget / alert in favor of the mobile banner. Do you have any objections to removing that widget? Once it's out of the CMS, we can deprecate the related code.

Note that the team was going to go ahead and remove that CTA themselves, but there are several draft tweaks on that CMS page, and wasn't certain about publishing those. So CAIA will make the edit to remove the React widget and its H2, in order to manage the draft changes on there that we've previously made.

---
## Tasks
- [x] Removed widget (Katherine)
- [x] Copyedit (Chelsea)
- [x] Publish (Chelsea)
- [x] Alert stakeholder

## Acceptance Criteria
- [x] Updated page is live
---

**Comment by katherine-fung** [comment]
Hi @chelsealevinson! I reverted the draft changes on this page, and removed the mobile app widget. 

This page is ready for copy edit. 

http://preview-prod.vfs.va.gov/preview?nodeId=471

After you copy edit and publish this page, we should revert to the draft from [05/02/2023 - 12:07 pm] and remove the mobile app widget from there, and save as draft. Let me know if you have any questions.  Thanks! 

cc @jilladams

**Comment by chelsealevinson** [comment]
Confirming I copy edited the changes and published this page. Do you want me to to go ahead and revert the draft and remove the widget, or will you handle that @katherine-fung ? Let me know!

**Comment by katherine-fung** [comment]
@chelsealevinson I reverted the draft and removed the widget. 

@jilladams fyi we've removed the mobile widget.
