### ISSUE TITLE
[Test Results] T1351 - Test case failed

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#7456]
## Test rail link
https://dsvavsp.testrail.io/index.php?/tests/view/1351
(Accidently ran the test case in General SSOe test cases, [here is the link to the Chrome test case](T1860))

## What happened?
Ran T1351 (Test Case 11) - failed step 2 (I opened mhv-syst.myhealth.va.gov and was not signed in).

## Specs:
Browser: Chrome on CAG 
Tester: Bridget

**Comment by ericbuckley** [comment]
@bridgethapner I have a feeling the problem is I put the wrong user in the test.  I don't think user 262 has an MHV account.  I'm trying to test with other credentials but my CAG browser is looked up at the moment, so I can't.  I'll post more information soon

**Comment by bridgethapner** [comment]
Thanks @ericbuckley. The [next test case passed](https://dsvavsp.testrail.io/index.php?/tests/view/1352&group_by=cases:section_id&group_order=asc&group_id=60) and I think 262 had to have an MHV acct for that one to pass, although I'm not sure.

**Comment by patrickvinograd** [comment]
This test case is defined incorrectly (based on new information). User needs to navigate to 
https://sqa.eauth.va.gov/mhv-portal-web/eauth 
to land on MHV home page or
https://sqa.eauth.va.gov/mhv-portal-web/eauth?deeplinking=secure_messaging
to land on a specific feature page (e.g. secure messaging in this case)

**Comment by bridgethapner** [comment]
Thanks @patrickvinograd. Edited the test case to reflect these updated links, ran it with 262, and it passed for both MHV homepage and deep link. Closing this ticket.
