### ISSUE TITLE
Create AWS bucket for testing (non production)

### ISSUE THREAD

**Issue by cloudmagic80** [department-of-veterans-affairs/va.gov-team#74588]
User story: In order to work with PEGA's new workflow system, they have asked our team to store pdfs into an S3 bucket. To test our code, we need to have a sample S3 bucket to make sure there is a 200 connection from our testing environment (localhost 3000). 

Definition of done: Create a sample S3 bucket, non VA. Then make sure there is a 200 (successful) connection from local host. Make sure files get uploaded. Test with postman.

**Comment by marywang2** [comment]
This was created, credentials given to Bo.
