### ISSUE TITLE
Refactor the uploads controller file in Simpleforms to upload pdfs into the new s3 bucket

### ISSUE THREAD

**Issue by cloudmagic80** [department-of-veterans-affairs/va.gov-team#74582]
As an engineer and user of VA.gov Health, when I fill out a form online like 7959-f, 1010D or 7959A, I would like to store the pdfs in AWS S3 so that in a future date, an analyst can review my forms.
Doing this will require to refactor the upload controller and other related files.

Definition of done: After this is completed, we should be able to bypass the benefits api and upload any pdfs to AWS s3 bucket that we provision.

**Comment by balexandr** [comment]
Moving ticket into Review as @cloudmagic80 checks out PEGA's AWS keys

**Comment by baltes** [comment]
Closing this, we can open a new one if needed for additional work.

**Comment by balexandr** [comment]
Yes, Don found an issue with end-to-end testing so we need a new ticket and a PR needs to be actually opened and merged into `vets-api`.
