### ISSUE TITLE
AWS access for Andres Rivera Toro

### ISSUE THREAD

**Issue by andresriveratoro** [department-of-veterans-affairs/va.gov-team#74597]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Andres Rivera Toro

### Your Email

andres.rivera@oddball.io

### Team, Role, and Company of the target individual

Team Okapi, Frontend Engineer, Oddball

### Product Manager (PM) name and email

Turi Clausell, turi.clausell@oddball.io

### Product Owner (PO) name and email

Dave Mazik, david.mazik@va.gov

### Desired AWS Access

I need similar permissions to my teammate `Giles Wells`

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

<img width="1130" alt="Screenshot 2024-01-26 at 09 44 22" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/36863582/e643b04c-8e51-488b-a176-2181af5057ab">

### Additional Notes

I will need ongoing access as part of the work on Okapi

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [ ] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by ph-One** [comment]
Account created and credentials sent to user
