### ISSUE TITLE
Team needs clarity on product requirements and scope

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#746]
* Need clarity on product scope and requirements. Clarice or Lisa might be the right persons to tag.
* Request the product requirements document
* Find out about any deadlines or mandates that might be relevant
* Find out about any marketing or promotional efforts in upcoming iterations

**Comment by smoonpeyes** [comment]
@lkoenigsberg This was a question from the By Light team during our Onboarding session today. Please let me know if there's someone else I need to tag.
