### ISSUE TITLE
Spike: check to see if VBA team's S3 bucket has capacity to host IVC files

### ISSUE THREAD

**Issue by cloudmagic80** [department-of-veterans-affairs/va.gov-team#74600]

**Comment by baltes** [comment]
@cloudmagic80 Let's close this one. Benefits intake API is not an option we're considering and we need to focus elsewhere.

**Comment by cloudmagic80** [comment]
@baltes I understand that Benefits API is not an option but what about just using their S3 bucket?

**Comment by marywang2** [comment]
Bo said no - closing.
