### ISSUE TITLE
[bug spike] SC | Validation error from Lighthouse `create` response

### ISSUE THREAD

**Issue by anniebtran** [department-of-veterans-affairs/va.gov-team#74606]
## What happened?
We've seen a couple of instances where veterans are submitting Supplemental Claims forms and run into a validation error when we validate the response we get from Lighthouse. This could be due to a recent change in vets-json-schema where we removed the `timezone` enum and replaced it with a less strict rule that [just requires that a `timezone` is present](https://github.com/department-of-veterans-affairs/vets-json-schema/blob/master/src/schemas/SC-create-request-body_v1/schema.json#L210-L212). 

The error in Sentry looks something like this:
```
{
  code: 109, 
  detail: {
    data_pointer: /data/attributes/formData/data/attributes/veteran, 
    ...
    description: JSON Schema for VA Form 20-0995
  }, 
  status: 422, 
  title: Validation error
}
```

We've actually seen this error [before](https://dsva.slack.com/archives/C05UPRR0HK3/p1704304966691279?thread_ts=1703787199.834109&cid=C05UPRR0HK3) and were lucky because they didn't have uploads, but unfortunately this time the veteran actually has uploads that didn't get submitted to Lighthouse with their form 😬 

## What we've tried in order to debug the error / what we do know
I went through a similar process to how I investigated the problem previously ^ and checked if the form submissions made it through to Lighthouse (`AppealsApi::SupplementalClaim` by using the veteran's ICN) and they have but the `form_data` doesn't include a timezone, which is why I suspect that's the source of the issue. 

## What do we need to know?
- Why do these Lighthouse `AppealsApi::SupplementalClaim` records not include `timezone` in the form data? Other (successful) records include a timezone.
- At which step is the timezone missing? Is it missing when the form is submitted from the frontend? Or is it just missing from Lighthouse's response for some reason?
- Would the presence of timezone in the form data affected by VPNs or remote desktops or anything? Seems like we're able to see timezone in DD logs, so not sure what else could result in a missing timezone.

## Action items
- [ ] Timebox investigation

## Slack threads and background context
- [Alerts channel thread (happened twice for the same user)](https://dsva.slack.com/archives/C05UPRR0HK3/p1706198240088599)
- [Sentry error](http://sentry.vfs.va.gov/organizations/vsp/issues/239836/events/01ba7cf2aa9a4f87bdbc4fd8abee1892/)
- [Alerts channel thread for the first instance of this problem from about a month ago](https://dsva.slack.com/archives/C05UPRR0HK3/p1703787199834109)

## Definition of Ready 
- [ ] Timebox is defined
- [ ] Nature of the issue defined

## Definition of Done
- [ ] Figure out what caused the error
- [ ] Make ticket(s) for any follow-up work

## Out of scope
- Coding solution

**Comment by shaunburdick** [comment]
@anniebtran hasn't seen these errors in a while, will check to see if they are still happening

**Comment by anniebtran** [comment]
Haven't seen any errors in the past few months related to the create response validation, so closing this. We can open a new ticket if it pops back up, but it could be that we've cleaned up the issue with our various bug fixes.
