### ISSUE TITLE
[Packer] Amazon CloudWatch Agent Implementation

### ISSUE THREAD

**Issue by hgbarreto** [department-of-veterans-affairs/va.gov-team#74601]
## Description
Need to implement a permanent solution to the EKS node /var/log and /var/log/audit directories causing problems when not log rotating correctly, or when too many rotations have taken place and disks fill.

_Solution has been identified as Amazon CloudWatch Agent_

## Resources 
[Example Slack Thread](https://dsva.slack.com/archives/C04CYC4LMU6/p1706279047239349
)
## Acceptance Criteria
- [ ] Verify logs are rotated correctly
- [ ] Increase disk partitions if necessary
- [ ] Verified to work

## Refinement Guidance - Check the following before working on this issue: 
- [x] _Team label assigned ("platform-tech-team-2")_
- [ ] _Epic assigned (if needed)_ 
- [x] _Estimated (points assigned)_
- [x] _Sprint assigned (once planned)_
- [x] _Team member(s) assigned_
- [ ] _Understands how this work aligns with the overall platform_

**Comment by ph-One** [comment]
Look into rotating logs based on size?

**Comment by ph-One** [comment]
Monitor used for watching disk partitions and mounts https://vagov.ddog-gov.com/monitors/98190?view=spans

**Comment by hgbarreto** [comment]
First part of the solution will be to ensure that these logs are captured in Cloudwatch.
Second part will be implement a logrotate config that prunes logs when needed.

**Comment by hgbarreto** [comment]
Core Issue:
	Log files are filling up on eks nodes causing issues. 
```
		- /var/log/messages
		- /var/log/audit/audit.log
```
	
Initial Solution:
	Logrotate configs that keep the capacity down.

Chain Problem 1:
	In order to delete logs on the OS, we need to make sure we capture these logs in the first place. Not currently happening with the new AMIs AND even if they are captured, it is not in Datadog or CloudWatch (Loki was deprecated).

Chain Problem 1 Solutions:
	Solution A - Install Amazon-CloudWatch Agent with configs to capture these logs appropriately. In order to configure log groups and stream names in a consistent manner, tags are needed to generate names. 
		Solution A Problem: Tags are usually queried using AWS CLI. Not only would it have to be installed in all of our instances but, it would need to have the correct priveleges across the board. Note that other forms of metadata do not provide the instance name we desire. (As far as our EC2 knows... hostname is IP-123-123-123-123.region.compute.internal) 
	Solution B - Capture with Datadog.
		Solution B Problem: Is DD the right place for out instance audit logs? This will definitely cause a bump in capacity along with perhaps exposing auditing information that not everyone needs to see?

**Comment by hgbarreto** [comment]
Pausing effort to work on Security priorities

**Comment by npeterson54** [comment]
rollilng over into next sprint

**Comment by hgbarreto** [comment]
Currently working through a curl issue in the new amazoncloudwatch shell script.

**Comment by hgbarreto** [comment]
Curl issues resolved - Need to add new policies to current and new roles:
- ec2DescribeTags
- (set of permissions to allow writing to amazon cloudwatch)

**Comment by hgbarreto** [comment]
Creating a new ticket for the Policies/Role creation and modification needed to have this new Amazon CloadWatch agent function as implemented.

**Comment by hgbarreto** [comment]
Created continuation Story - https://github.com/department-of-veterans-affairs/va.gov-team/issues/80088
