### ISSUE TITLE
Analytics Implementation for [22-1995] Accordion Summary Clicks

### ISSUE THREAD

**Issue by jonwehausen** [department-of-veterans-affairs/va.gov-team#7462]
# Analytics Implementation

## Description
- Implement accordion expand / collapse tracking on Form 1995 Summary page

![image](https://user-images.githubusercontent.com/48527022/78134223-c9e6a200-73ed-11ea-8431-b7bff98cbb23.png)

- Who is this request for?
    - Amy Knox
    
- URL where accordion tracking needs to be implemented
_https://staging.va.gov/education/apply-for-education-benefits/application/1995/review-and-submit_
    
## Acceptance Criteria
- [ ] Verify ```nav-accordion-expand``` event is pushed on **each** EXPAND click of the accordion on the summary page
- [ ] Verify ```nav-accordion-collapse``` event is pushed on **each** COLLAPSE click of the accordion on the summary page
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
@amyknox - Created this story to provide the tracking necessary for [your request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6633). We will need a dev resource form your team to implement the event according to the dataLayer needs below. 

### Datalayer Requirements
1) Click on ANY accordion to **expand** on the form summary page
```javascript
dataLayer.push({
   'event': 'nav-accordion-expand'
});
```

2) Click on ANY accordion to **collapse** on the form summary page
```javascript
dataLayer.push({
   'event': 'nav-accordion-collapse'
});
```

@bsmartin-ep Once Amy Knox's team is able to get the dataLayer in place - this should just be a validation/testing story on our part. You will find the pre-configured functionality for this within "Navigation Action Lookup" in Google Tag Manager.

**Comment by joanneesteban** [comment]
@amyknox - Hi! Checking in on this - do you have the event implemented for us to move forward with validation? Thanks!

**Comment by joanneesteban** [comment]
Hi @amyknox ! Wanted to check in on this to see if there's a follow up on the event implementation above? Once that's completed, we can validate & publish on our end.

**Comment by jonwehausen** [comment]
Hi @amyknox ,

Could our team get an update on getting the dataLayer put in for this request? If not critical anymore, we are happy to icebox.

**Comment by ksantiagomorgan6** [comment]
Pull request https://github.com/department-of-veterans-affairs/vets-website/pull/13098

**Comment by jonwehausen** [comment]
@ksantiagomorgan6 Thank you for this! There won't be any necessary GTM on our part and this can move to production at any time.

**Comment by sonntag-adam** [comment]
Local testing
![Screen Shot 2020-06-12 at 7.56.02 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/b76a7349-2bcd-4314-8d96-0fd4bda56d80)
##
![Screen Shot 2020-06-12 at 7.57.28 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/036aadfa-523e-4dc4-aefc-1a5fd139a644)

**Comment by jonwehausen** [comment]
Per conversation with Amy Knox [here](https://dsva.slack.com/archives/C1Q4294JJ/p1592240041178100),

We've concluded the accordion data is not valuable enough to warrant the 1-off customization for this form. Have decided to de-prioritize and close
