### ISSUE TITLE
SOCKS access for [Vanson Samuel]

### ISSUE THREAD

**Issue by binq** [department-of-veterans-affairs/va.gov-team#74623]
### Your Name

Vanson Samuel

### Your Email

vanson.samuel@va.gov

### Your Role and Team

VFS/VYE (Verify Your Enrollment) - Backend Development (Ruby on Rails) [GovCIO/Decisive Point Consulting Group]

### Product Manager (PM) name and email

Darla van Nieukerk - Darla.vanNieukerk@va.gov

### Product Owner (PO) name and email

Jason Wolf - Jason.Wolf1@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCiYx1PhmVXF5dyQB+Vf+WDAfOiKDy61PM1bQt6EyoV5JCS8SJysxVF0MIazxn/jTUhCxiEPn5emuR/Ekv/I7fjDqlEkJZOfsCY7LeRqyBqI+ZxJIcVi7GPIPYMtM7rhzD+mVsSGwOwbFcpOPWe1iCY0Hhce7nceZ2qqmy21ALIt7vSUmk63yfppu/rGgUvKtCTJ+bM52FlipX1HpUTBkXhKhH8uwDBHXMFuwfH4vpirsCi9ABVpIDCdSfPuA/DNTrcv+kdIQ5aQw7YlNimNUS3NT5Wy+vi0KfTmgSTOqnA0vedlxtPzGxc4Tg1hd4wmGZ5DYrz4+o+Mo/xoB0UsgtvLT5gSEC1Nn1eVseOC9okqvl3q3gcJmPJpSWn6jzLjJ/pduKBHjz8yYD7H2YZp1xgf3ecmGppfRCcQngv7+HCvA9jGbg5+kJZ5jY2SYlMQvcINw55HEJi1TZDQlR4yGI/chXpEGSrt4Kd5YBaztitTVJmaCiA38OWPNf77gUQk50= vansonsamuel@DESKTOP-S2VB5IR

### E-QIP Transmittal Confirmation

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/37637/e8322deb-c291-4fdf-9dcb-ff75d346ed67)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by barbarello** [comment]
@binq  Access granted ✅ 

Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html 

Reach out in #vfs-platform-support if you have any trouble.
