### ISSUE TITLE
[spike] DR | Programmatic discovery and handling of failed evidence submissions

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#74628]
## Value Statement
**_As a_** Veteran who has submitted evidence that, without my knowledge, fails to make it through all systems downstream of VA.gov.
**_I want_** such downstream systems to notify VA promptly upon such failures, via polling or webhooks
**_So that_** VA is immediately aware of such failures and can act upon them as it deems appropriate to ensure my evidence is considered along with my appeal.

---
## Background Context

We are currently made aware of downstream evidence submission errors on our NOD and SC forms through daily and weekly Lighthouse email reports. While convenient, unfortunately, these reports are separate from DataDog, which contains all our logs, dashboards, and monitors. Ideally, we would just use DataDog.

Along with its email reports, Lighthouse provides a status endpoint allowing us to "poll" the status of evidence submissions. By polling each evidence submission, we could become aware of and create logs (to send to DataDog) for failed evidence submissions. However, there are some problems with polling. For one, evidence can take a long time to fail. Anecdotally, we've heard it can take anywhere from minutes to days. IIRC, potentially even weeks. Which makes it at least somewhat difficult to determine limits or intervals for polling. Additionally, at a certain point, you can run into scalability issues. Though, I'm not sure that would be the case for our forms. We get approximately 5K evidence submissions per week across our forms. Depending on our polling interval, polling may be reasonable. We would have to think about it more.

Ideally, our downstream systems would build the ability to support status webhooks (like VANotify does), where the systems would send status updates, as they happen, to an endpoint provided by us. This would avoid all the complexities of polling, but would shift the burden to the downstream systems to affirmatively update us, which may be something they are unwilling or unable to do.

## Tech Tasks
- [ ] Brainstorm ideas

## Acceptance Criteria

- [ ] TODO

## Definition of Ready 

- [ ] TODO

## Definition of Done

- [ ] TODO

**Comment by shaunburdick** [comment]
Closing in favor of #84372
