### ISSUE TITLE
Update yellow ribbon search results to include degree + program, and new copy

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#7464]
Update the search results page to match new design spec shown on this screen:
https://vsateams.invisionapp.com/share/P4W04QPWHTK#/411695897_Results_-_All_Data___Historical_Rates

Please check with Jen/Anne as to where the historical rates PDF would come from that is linked from the results page

Acceptance criteria
- [ ]  Copy under h1 matches design spec
- [x] Helpful link section added to side bar and includes 3 links as shown in spec
- [x] degree and program shown on each card; labels use sentence casing

**Comment by MickinSahni** [comment]
2020-04-03 PW Standup
- PR opened for this and waiting for merge

**Comment by MickinSahni** [comment]
2020-04-06 PW Standup
- Validated
  - 
<img src="https://user-images.githubusercontent.com/13204473/78576969-63052680-77fb-11ea-8af9-9e3adc0a0faf.png" width="150px">

**Note: link to 2018-2019 page is a legacy page, but desiring it to be a PDF. Danielle to brainstorm on this as well**
