### ISSUE TITLE
Add Feature Toggle for clinic filtering

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#74659]
## Item Description
We want to put the clinic flag changes behind a flag to better coordinate deployment with `vaos-service` team.

---

## Tasks
- Add `va_online_scheduling_clinic_filtering` feature toggle

## Acceptance Criteria: 
- [ ] The toggle is created for VAOS

## Definition of Done
- [x] All acceptance criteria are met
- [x] [Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/product/feature_toggles.md) is updated

---

**Comment by ajmagdub** [comment]
va_online_scheduling_clinic_filtering toggle merged
