### ISSUE TITLE
Update Yellow Ribbon landing page to include new copy and link

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#7465]
Update copy on on landing page to match what's shown on in this design spec: https://vsateams.invisionapp.com/share/P4W04QPWHTK#/411695898_Landing_W_Historical_Information

Please work with Jen/Anne to determine where the PDF with historical rates will be.

## Acceptance criteria
- [x] Sentence above form fields reads `Search for schools participating in the current academic year by one or all of the terms below. `
- ~[x] Sentence below search button reads `Participating school information is for the current academic year. To view schools for the previous academic year, download the historical rates (PDF).`~
- [x] copy does not exceed 600px width

Reference: https://vsateams.invisionapp.com/share/P4W04QPWHTK

**Comment by MickinSahni** [comment]
2020-04-03 PW Standup
- PR merged for this ticket. Waiting to validate

**Comment by MickinSahni** [comment]
2020-04-06 PW Standup
- Hey @jenniferlee-dsva, we're moving this out of the sprint and adding a `needs-grooming` label. The new copy is there but there's an open discussion of:
  - whether the link should go to historical YR pages that may or may not be deprecated or should new versions be created, etc.
  - This was prompted from Janice's question of 'How will students who are taking summer classes AND students who are planning for the fall semester get access to up-to-date data?'
    - (Meanwhile, Brian/Tammy are ok with having only one school year's worth of data, link to post-meeting discussion is in Slack)

**Comment by kelsonic** [comment]
Can we get confirmation on this ASAP? I don't want this to be a blocker for launching if it doesn't need to be @MickinSahni

**Comment by MickinSahni** [comment]
Sprint 19 Planning
- PR merged
- MVP
  - What's the plan for legacy data? 
    - Have a call with Tammy H. (who prev. mentioned legacy rates aren't useful). 
    - All we might need is the upcoming year's rates e.g. for 2020-2021 (as a spreadsheet we'd convert to a PDF we'd link to) based on what GIDS folks send us. 
      - Open question: upcoming year's rates are useful

**Comment by MickinSahni** [comment]
2020-04-09 PW Standup
- Decision: Jen to to let stakeholders know we're not providing legacy nor future data

**Comment by kelsonic** [comment]
@MickinSahni decision is to include a future PDF (https://dsva.slack.com/archives/C52CL1PKQ/p1586529462326600?thread_ts=1586527905.318600&cid=C52CL1PKQ) but, as that's not provided yet, should I just omit that content?

**Comment by kelsonic** [comment]
If so, feel free to move this ticket into current sprint again! haha 🙃

**Comment by andaleliz** [comment]
@kelsonic I updated the prototype to reflect what I _believe_ is the latest version of how things should look for launch, based on our convo... https://vsateams.invisionapp.com/share/P4W04QPWHTK

**Comment by MickinSahni** [comment]
2020-04-13 PW Standup
- Validated on staging
