### ISSUE TITLE
Add clinic filtering flag to clinics call

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#74664]
## Item Description
We want to add the flag to the `vaos-service` clinics call to enable stop code filtering. 
Endpoints we want to add filtering to: `/vaos/v1/locations/?/clinics`
We only want to add this to the scheduling flow endpoint.
flag name: `enableStopCodeFilter`.
We want to pass this flag as `true` by default in `vets-api`, no additional work will be need in `vets-website`

---

## Tasks
- Changes should be behind the `va_online_scheduling_clinic_filtering` feature toggle

## Acceptance Criteria: 
- [x] The toggle is created for VAOS

## Definition of Done
- [x] All acceptance criteria are met

---

**Comment by ajmagdub** [comment]
@ldelacosta 
The Vets API code has been moved to staging. Once Paul Pearson moves the backend code to staging and staging's  Flipper flag is enabled, Marcy can begin testing.

**Comment by ajmagdub** [comment]
@ldelacosta 
Paul Pearson's VAOS Service changes are in staging, and the feature flag is enabled; Marcy can now test in staging.

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket.
