### ISSUE TITLE
Request Tracker (Request & Support Process)

### ISSUE THREAD

**Issue by jimcconnelly** [department-of-veterans-affairs/va.gov-team#74677]
### Issue Description
**User Story**
As an Identity Team member, I would like a way to track other team's requests so I can easily see the status of all of the requests and prioritize them.

**Why Are We Doing This?**
Being able to see all of our requests in the same place will enable us to properly manage and prioritize those requests. It also allows  team leads to make sure that requests do not fall off of the radar.

**Acceptance Criteria**
All of the tickets created by the Identity Slackbot are able to be seen grouped together, based up how they are labeled.

## Tasks
- [x] va.gov-team "identity-slackbot" label
- [x] view of zenhub with label filter

**Comment by jimcconnelly** [comment]
The more I think about it, the more I support the idea of a separate tracker for most requests, with the longer-term requests "graduating" to full product status (like, for example, ToU). Here are some of the things we could track with a Request tracker:

- Kind of request (bug fix, new work, etc)
- Requesting Team
- Priority
- Status

**Comment by jimcconnelly** [comment]
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkJpQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9da5451308191d541b4c677a03818ded66110338/Identity%20Team%20Request%20Tracker.png" alt="Identity Team Request Tracker.png" />

**Comment by bramleyjl** [comment]
An `identity-slackbot` label has been created in va.gov-team. [Here is a search for that label](https://github.com/department-of-veterans-affairs/va.gov-team/labels/identity-slackbot).

**Comment by bramleyjl** [comment]
[`identity-slackbot` label view](https://app.zenhub.com/workspaces/identity-5f5bab705a94c9001ba33734/board?labels=identity-slackbot&repos=133843125&useDefaultFilterLogic=false) in Zenhub.
