### ISSUE TITLE
Analytics Reporting Request for Monthly Metrics

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#7468]
# Metrics Reporting Request

## Description
Who is this request for?

- VEO (Lacey to Alita)
- Digital Modernization Council (Chris J)
- OMB (Chris J)
- OIT (Cam)
    

## Timeframe for Analytics Requested

Month of March 2020

## Analytics to Track Down

- VEO 13 Month Metrics Dashboard on Domo in PPT form
- OIT has added system status data

## Additional Comments
_Add any comments or questions for the Insights team here (if applicable)._

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by joanneesteban** [comment]
## Dates

Due to _Client_ before COB: (we should have the PPTs ready to QA before then):
- VEO: April 8th
- Digital Modernization Council: Second Wednesday of the month (April 8th)
- OMB Review: Second Wednesday of the month (April 8th)
- OIT: First Monday of the month (April 6)

## OIT Metrics

- Should delete slides for: Education, HCA, & Page Views
- **System Status:** 100% (this is technically for March 2-31 since it was pulled from the last 30 days, but that's fine). There should be a note that this number reflects the errors reported by the applications serviced by the VA.gov Platform.

**Note** - I added the system availability Grafana link to the dashboard so it's easier to grab next time, but feel free to move it around if I messed up the dashboard layout.

**Comment by amycesal** [comment]
OIT metrics ppt sent in Slack
