### ISSUE TITLE
Intake Form (Request & Support Process)

### ISSUE THREAD

**Issue by jimcconnelly** [department-of-veterans-affairs/va.gov-team#74683]
**User Story**
As an Identity team member, I would like an intake form in order for other teams to make requests of our team.

**Why Are Doing This?**
An intake form will standardize the request process, allowing us to have more control over monitoring and fulfilling those requests. And the answers in this form will auto-populate the tracker, as seen in https://github.com/department-of-veterans-affairs/va.gov-team/issues/76158

**Acceptance Criteria**
An intake form is built using slackbot, containing the following questions:

- What do you need from us?
   - Text Field
- What is the name of your team?
    - Text field
- What kind of request is it?
    - Drop-down, with the following items
       - PR Review
       - Data pull
       - Bug Fix
       - Help Request
       - Task Request
       - Feature Request
       - Other
          - If "Other" is chosen, then a text field is displayed for user to enter the kind of request.
- What is the name of the the requestor?
   - Text Field
- What is the Slack handle of the requestor?
   - Text Field
- What is the urgency of this request?
    -  Text Field
- Do you have any other comments?
   - Text field
 
- Make Request Button
   - Submits the form
      - If form is submitted properly, user is shown a modal that says: "Thank you, your form has been submitted. We will be in contact with you."
      - If form encounters an error, user is shown a modal that says: "We're sorry, we've encountered a problem,can you submit this again?"

**Comment by jimcconnelly** [comment]
![Image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/145713877/c46af19c-31a8-4071-b741-911d738ab805)

**Comment by kdmeg-bluetiger** [comment]
@jimcconnelly - I have a few questions about the form fields:

- Do we want "bug fixes" to collect any additional details about the issue? There is an authentication troubleshooting bot that @bramleyjl is working on that may (or may not) be relevant to these types of issues.
- After bug fixes, the [majority of requests are general questions](https://docs.google.com/spreadsheets/d/1f6fZjUplLmMvO7oqAMYjRa-GMsMNhPL6jaeLbAWqiFc/edit#gid=814251307). Do we want a "General question" category that routes to specific products we support (or "other")? 
- I wonder how this form would direct users to the SiS support process? Would we want to nest this under a category like "General questions" or make it its own field?

**Comment by jimcconnelly** [comment]
We decided to split this into three separate forms, so it is redundant.
