### ISSUE TITLE
[MVP] FE update to types of income list in Gross monthly income

### ISSUE THREAD

**Issue by aplatt-coforma** [department-of-veterans-affairs/va.gov-team#74698]
This list of income types for the question What types of income needs to be updated to match the PDF.

**Current list:** 
- Social Security
- Interest or dividend income
- Retirement income
- Pension income
- Other income

**Update to:**
- Social Security
- Interest or dividend income
- Civil Service
- Pension or Retirement income
- Other income

<img width="1864" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeW9GQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--58e903841c3d92559dec3c138c899fc7330b6be3/Screenshot%202024-01-27%20at%207.15.55%E2%80%AFPM.png" alt="Screenshot 2024-01-27 at 7.15.55 PM.png" />

**Testing notes:**
Make sure the selection in the FE maps correctly in the generated PDF

**Comment by aplatt-coforma** [comment]
@mayacoforma - can you please make sure the design files have the updated types of income list?

**Comment by mayacoforma** [comment]
@aplatt-coforma Will do!

**Comment by aplatt-coforma** [comment]
Fix looks good on staging!
<img width="1532" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNm9TQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--33d5af1c191efe8fd8358dab025324dffac6f87a/Screenshot%202024-01-30%20at%201.45.09%E2%80%AFPM.png" alt="Screenshot 2024-01-30 at 1.45.09 PM.png" />
