### ISSUE TITLE
Current job title is not mapped on PDF

### ISSUE THREAD

**Issue by aplatt-coforma** [department-of-veterans-affairs/va.gov-team#74699]
**Steps:**
1. Start a pension application
2. Enter minimal data until you get to the Employment
3. Select Yes currently employed
4. Enter all the information for the current employment (take note on what you entered)
5. Submit minimal data for the rest of the application

**Results:**
The job title is not found on the generated PDF

**Expected:**
Current job title mapped to the question "What was your job title?"
(NOTE: The question on the PDF form is past tense. The PDF does not have a field for the current job title so I'm not sure if the answer in the online form should be mapped to this particular field on the PDF.)

 <img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXNGQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4d5310cd4861c3c75850a889bc583373df219c3f/Screenshot%202024-01-27%20at%206.42.19%E2%80%AFPM.png" alt="Screenshot 2024-01-27 at 6.42.19 PM.png" />

**Comment by vbellissimo** [comment]
Here is the expected data mapping for both current and previous employment questions.

Slack thread with stakeholders: https://dsva.slack.com/archives/C05MS96P6P2/p1706540602761519?thread_ts=1706312629.113879&cid=C05MS96P6P2

<img width="653" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEVKQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3ea7386bb473217faba156b1e303896ef0c3373f/Screenshot%202024-01-29%20at%2010.16.00%E2%80%AFAM.png" alt="Screenshot 2024-01-29 at 10.16.00 AM.png" />

<img width="552" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeElKQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--94e426051851eea630e0ff4f4dee8967f61c2365/Screenshot%202024-01-29%20at%209.58.06%E2%80%AFAM.png" alt="Screenshot 2024-01-29 at 9.58.06 AM.png" />
