### ISSUE TITLE
Test BTSSS integration

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#74692]
### Issue Description

integration and swagger details were sent directly to Trevor and Riley as they contain an app key the BTSSS team doesnt want made available to the public.

Report back on issues or concerns with the integration

**Comment by bosawt** [comment]
Currently testing with the following cURL, getting an 'ICN is missing on the auth token' error:

`curl --location 'https://dev.integration.d365.va.gov/veis/api/btsss/travelclaim/api/v1/auth/access-token' --header 'BTSSS-API-Client-Number: 100001' --header 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6InFvcl9WZVBXZ214V3kzcjFkcGZzV3N3Mi16WSIsImtpZCI6InFvcl9WZVBXZ214V3kzcjFkcGZzV3N3Mi16WSJ9.eyJhdWQiOiI0YTc3NDc2Yy1jZWVkLTQ1ZGItYWQ3ZS1hYzJiYmJjNGY3MmEiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC9mN2M0OWUzNi05NzFiLTQyYzctYjI0NC1hODhlZWQ2YzBiZjYvIiwiaWF0IjoxNzEwNTM0MDg0LCJuYmYiOjE3MTA1MzQwODQsImV4cCI6MTcxMDUzNzk4NCwiYWlvIjoiNDJGZ1lFaVVpQTdZa24rRTlVN21UZS8rQko5MEFBPT0iLCJhcHBpZCI6IjU4ZDUwY2EzLWI5MjEtNGQ5Yi1hYzc2LTg5NjViZTJlYjgwYiIsImFwcGlkYWNyIjoiMSIsImlkcCI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0L2Y3YzQ5ZTM2LTk3MWItNDJjNy1iMjQ0LWE4OGVlZDZjMGJmNi8iLCJvaWQiOiJiYWJlNjhjYi04NzcxLTRlOTgtYjEyNS1iYWIxYTE3NDFmYTciLCJyaCI6IjAuQ3dNQU5wN0U5eHVYeDBLeVJLaU83V3dMOW14SGQwcnR6dHRGclg2c0s3dkU5eW9EQUFBLiIsInN1YiI6ImJhYmU2OGNiLTg3NzEtNGU5OC1iMTI1LWJhYjFhMTc0MWZhNyIsInRpZCI6ImY3YzQ5ZTM2LTk3MWItNDJjNy1iMjQ0LWE4OGVlZDZjMGJmNiIsInV0aSI6IjVTMDdNRG9Ia2thaWVGSGJ1b2tCQUEiLCJ2ZXIiOiIxLjAifQ.ifpnBeGS_Ql-0v3oGQb-XF5E6VwXZSvwDsfLbxkrkBk-7_VOCxlUBGOzCUjwu2H6SONBjFdexsxIMJSdCDJafTzacUqG7CQwXdOCZdK2La2N12DdxSy5ECtERjEzgkAuACVaws5VGR-CHZdQcgs2DXb6jTfGU-f5FbTRLj1JbBjTe1JVqfTCLiQsvMa3Ucx56GAPWatxZZLeVqYsiOjdbzj7mcQfRtOOeZd0e5EZ2uyLof0T7CppkL2VNxlLzv_KogRujpMVMbT6KoULosNgOG3u34NXV4o4ZXL1nIBwZd8LwwE0iymVMA4HKxnYmGz-U-e7r8n1yPv347iPFp7DYw' --header 'Ocp-Apim-Subscription-Key: 1234abcd' --header 'Content-Type: application/json' --data '{"authJwt": "eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL3N0YWdpbmctYXBpLnZhLmdvdiIsImF1ZCI6Imh0dHBzOi8vc3RhZ2luZy1hcGkudmEuZ292IiwianRpIjoiNDQxM2Y5YjAzY2U1NGRiNjEwNTBlZWU5MThlZjhiZDAiLCJzdWIiOiJmYWtlIiwiZXhwIjoxNzEwOTY2MzA1LCJpYXQiOjE3MTA1MzQzMDUsInZlcnNpb24iOiJWMCIsInNjb3BlcyI6ImZha2UiLCJzZXJ2aWNlX2FjY291bnRfaWQiOiJmYWtlIiwidXNlcl9hdHRyaWJ1dGVzIjp7ImljbiI6IjEwMTI4MjY2NjRWNjAzMDMzIn19.HxYayVhdq3dcypmaplIG0bqE7Je9K4uFbdylsC6cfJ1RgWEZ3DNXZPlHiwS25PA_oF3pPOqWeZlToAqkTZf4X2Iyb6Cagncc-ZgHkWcQbhP1AiUOvHmLFdUqStGWVue3ocxN_mcPbaQkDxYANLq270vFyj7KZSr6_sBY3b98hVr9bg_Op0JO3CuoQrbatxZgn8QTW5q844F1Xh8_fAY21SZnZr1lKw0-4XOQxdosPgBIAvEeThiTArV1sIILp5riUXD4Qf_thMW4cYgKh0FfI8GBEEAtq6RpEo9BcX-5AttIEffTksFq4ebvqBENgkkWYuZUZqfsgCOnr8d3iEGz_w"}'`

**Comment by bosawt** [comment]
Confirmed testing with the following cURL, with successful response (subscription key has been substituted with fake value):
```
curl --location 'https://dev.integration.d365.va.gov/veis/api/btsss/travelclaim/api/v1/auth/access-token' \
--header 'Ocp-Apim-Subscription-Key: 1234abcd' \
--header 'Content-Type: application/json' \
--header 'BTSSS-API-Client-Number: 100001' \
--header 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6InFvcl9WZVBXZ214V3kzcjFkcGZzV3N3Mi16WSIsImtpZCI6InFvcl9WZVBXZ214V3kzcjFkcGZzV3N3Mi16WSJ9.eyJhdWQiOiI0YTc3NDc2Yy1jZWVkLTQ1ZGItYWQ3ZS1hYzJiYmJjNGY3MmEiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC9mN2M0OWUzNi05NzFiLTQyYzctYjI0NC1hODhlZWQ2YzBiZjYvIiwiaWF0IjoxNzExNzQyOTM4LCJuYmYiOjE3MTE3NDI5MzgsImV4cCI6MTcxMTc0NjgzOCwiYWlvIjoiNDJGZ1lPaWNIYUE0VGFUOFJzWkZXZi9YajZiTUJBQT0iLCJhcHBpZCI6IjU4ZDUwY2EzLWI5MjEtNGQ5Yi1hYzc2LTg5NjViZTJlYjgwYiIsImFwcGlkYWNyIjoiMSIsImlkcCI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0L2Y3YzQ5ZTM2LTk3MWItNDJjNy1iMjQ0LWE4OGVlZDZjMGJmNi8iLCJvaWQiOiJiYWJlNjhjYi04NzcxLTRlOTgtYjEyNS1iYWIxYTE3NDFmYTciLCJyaCI6IjAuQ3dNQU5wN0U5eHVYeDBLeVJLaU83V3dMOW14SGQwcnR6dHRGclg2c0s3dkU5eW9EQUFBLiIsInN1YiI6ImJhYmU2OGNiLTg3NzEtNGU5OC1iMTI1LWJhYjFhMTc0MWZhNyIsInRpZCI6ImY3YzQ5ZTM2LTk3MWItNDJjNy1iMjQ0LWE4OGVlZDZjMGJmNiIsInV0aSI6IjNnTFNCcGp2MkVDREM1WkI1MU1CQUEiLCJ2ZXIiOiIxLjAifQ.qJFgedhFGXqhZIHMSFoThtatiNTCG0sjT4_5xK5GXWsdoCMYEIESPC1y2rej1yA5LNmz2HCd52qngM1CviAG1Qs1DPbA51Y1xInGRtowjfsVd__w0yq81HdYr1frN0-KM73OeCsnG69r9IgwGvIanJhhybvD1auZ8Du8VeOFJhZeHgPgZAh75grGe-McXii057YQjG3B_prJlC2sD0w0xZcBsUlchd4DusQCyvoBTLmD7bKuurarXb3eO89ybDzBxJKA4oJ9CyvZpUmZ0J1xi1BfMnHb3PeBsEEmP6u-ag327r4NtBfT2kRbro81yopqdgsA6BxqcQr9npMdUV4oJw' \
--data '{"authJwt": "eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL3N0YWdpbmctYXBpLnZhLmdvdiIsImF1ZCI6Imh0dHBzOi8vc3RhZ2luZy1hcGkudmEuZ292IiwianRpIjoiNDQxM2Y5YjAzY2U1NGRiNjEwNTBlZWU5MThlZjhiZDAiLCJzdWIiOiJmYWtlIiwiZXhwIjoxNzExNzQ5NTk3LCJpYXQiOjE3MTA1MzQzMDUsInZlcnNpb24iOiJWMCIsInNjb3BlcyI6ImZha2UiLCJzZXJ2aWNlX2FjY291bnRfaWQiOiJmYWtlIiwidXNlcl9hdHRyaWJ1dGVzIjp7ImljbiI6IjEwMTI4MjY2NjRWNjAzMDMzIn19.azV5cS3g0Mem4WD-gb7mdv9pun1QoGLys1bRSvvEsRBleCo2Zc0t9lLNuTKjDp2b_9ysISroFYURKpyCmWqAcdSJ9J7mRNP5K8Psm4IJsBXV5FbJ4VM7eg3YXocQRyXPAhlj3CuPpFlR1MwvN-d8OIfqdfLgc3OKdRZUJnZGI0pF2ZIifVdrVtJ6NPOjzdhoryEVJV7gqduXgm1QsjD-wdVbzz-PCbMtAemAy8E6UcC1QBNDkCQpX1Rax-oECD-Df6LrGIEb20DndghZ4idbsr0Y3JTWt9nHC3eXjkwJACjSNuMuGXkgeHBrh3nqMFmF3iU2dJnlLTolra_nWS6OVw"}'
```


Response:
```
{"correlationId":"853f80cd-a17e-4543-a0a2-8d617038f292","timeStamp":"2024-03-29T20:20:59.0859343Z","statusCode":200,"message":"Data retrieved successfully.","success":true,"data":{"accessToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBcGlDbGllbnROdW1iZXIiOiIxMDAwMDEiLCJDb250YWN0SUQiOiI1ZjRjNTU3MS1kNjJhLWVkMTEtYjgzYy0wMDFkZDgwNjk0NmQiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9naXZlbm5hbWUiOiJFVkVSRVRUIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvc3VybmFtZSI6IkhPUlRPTiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJFVkVSRVRUIEhPUlRPTiIsIklDTiI6Im5leXZkRkZ3OWRvWEwyTTNuQTVTR3FUeE9pLzNtLzZjanpZai9Xa3V4MVE9IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVmV0ZXJhbiIsIm5iZiI6MTcxMTc0MzY1OSwiZXhwIjoxNzExNzQ3MjU5LCJpc3MiOiJodHRwczovL3RyYXZlbGNsYWltYXBpLWRldi1idHNzcy5kZXZ0ZXN0LnZhZWMudmEuZ292IiwiYXVkIjoiaHR0cHM6Ly90cmF2ZWxjbGFpbWFwaS1kZXYtYnRzc3MuZGV2dGVzdC52YWVjLnZhLmdvdiJ9.kKrZ84EJ2QzoNW5oBwjn9yTz35KSzEfVWJq2oD36rEk"}}
```

**Comment by JonathanKamensDVA** [comment]
@bosawt can you please confirm that the tokens above (in the Authorization: headers in your tests) are test tokens that would not have been valid for production access at the time they were pasted into this ticket. Also, do you know whether these were long-lived or short-lived tokens?

**Comment by bosawt** [comment]
Yes these tokens were JWT with short lived expirations used to test the BTSSS dev stack. Non-production and were probably expired by time I posted the test comments
