### ISSUE TITLE
 FE: What’s the value of the land that’s more than 2 acres? is missing from Review page

### ISSUE THREAD

**Issue by aplatt-coforma** [department-of-veterans-affairs/va.gov-team#74701]
Steps:
1. Start a pension application
2. Enter minimal data until you get to the Financial Information > Income and assets > _Is your home located on a lot of land that’s more than 2 acres (or 87,120 square feet)?_
3. Enter YES
4. Next question is _What’s the value of the land that’s more than 2 acres?_
5. Enter some $ number
6. Proceed with the rest of the application with minimal data
7. Look at the review page under the Finanical Information page for the question _What’s the value of the land that’s more than 2 acres?_

Results: The question is missing
Expected: You should see _What’s the value of the land that’s more than 2 acres?_ below the question _Is your home located on a lot of land that’s more than 2 acres (or 87,120 square feet)?_

<img width="608" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTBGQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5fa2c9172e05ff74752f8947710aa83d7770c232/Screenshot%202024-01-27%20at%207.41.57%E2%80%AFPM.png" alt="Screenshot 2024-01-27 at 7.41.57 PM.png" />

**Comment by aplatt-coforma** [comment]
@TaiWilkin - Just tried testing this on staging and not seeing the changes. Is this one of the PRs that are caught in the pipeline?

**Comment by TaiWilkin** [comment]
> Is this one of the PRs that are caught in the pipeline?
Yes, unfortunately. I'll comment in here again once it goes through.

**Comment by TaiWilkin** [comment]
This is up on staging now
