### ISSUE TITLE
AWS access for Michael Clement

### ISSUE THREAD

**Issue by michaelclement** [department-of-veterans-affairs/va.gov-team#74708]
### COR Name

Eunice Garcia

### Vendor Onboarding Representative Name

Agile Six - Anthony M. Arashiro

### Your Name

Michael Clement

### Your Email

michael.clement@adhocteam.us

### Team, Role, and Company of the target individual

IVC Forms (CHAMPVA), Software Engineer, Ad Hoc

### Product Manager (PM) name and email

Bo Altes, bo.altes@agile6.com

### Product Owner (PO) name and email

Premal Shah, premal.shah@va.gov

### Desired AWS Access

The IVC Form team will be pushing the digitized forms to a S3 service. Bucket TBD but we all need accounts in AWS before we can be granted access to any bucket

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

I did not receive an E-QIP transmittal confirmation because a previous background investigation was still in force when I joined the company (Ad Hoc) in October 2023.

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [x] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by barbarello** [comment]
user is in Atlas

**Comment by barbarello** [comment]
checked his status in the system and have validated that he is active and in good standing

**Comment by barbarello** [comment]
Access granted and temporary credentials passed to user

**Comment by ph-One** [comment]
I see the AWS account and MFA are setup, as well as activity from the user. Closing as there is already access
