### ISSUE TITLE
Send form metadata to PEGA

### ISSUE THREAD

**Issue by cloudmagic80** [department-of-veterans-affairs/va.gov-team#74703]
PEGA analyst who are reviewing the uploaded PDF forms request they have metadata sent to AWS S3 along with the PDF form. We can propose that the metadata will include the form contents in JSON, but this could change in the future.

Definition of done: JSON data is produced when the form is completed and sent to AWS S3

For testing purposes in staging, avoid real data and stick to fake user info.

**Comment by dhill802** [comment]
@baltes Bryan will work on this story in Sprint. 11

**Comment by balexandr** [comment]
@marywang2 I spoke with Don on this and it seems like we will be updating the JSON wihch is used to populate the PDF itself. Can you confirm what the nomenclature should be for the file naming? i.e. `vha_10_10d_meta.json`.

**Comment by marywang2** [comment]
@balexandr do we know what the other forms teams are doing (is there a standard)? Otherwise I think what you are suggesting seems fine. Adding @baltes to see if you had any thoughts on this.

**Comment by marywang2** [comment]
@balexandr not sure how to review this one. @cloudmagic80 is this something you can help review?

**Comment by cloudmagic80** [comment]
@balexandr  I am doing end to end testing but I don't see the upload files in S3. Can you show me how the env file is setup? Thanks.

**Comment by cloudmagic80** [comment]
I've added Session Token variable. End to end testing passed!
