### ISSUE TITLE
Analytics Implementation to give Additional Context COVID FAQ Page

### ISSUE THREAD

**Issue by jonwehausen** [department-of-veterans-affairs/va.gov-team#7471]
# Analytics Implementation or QA Request

## Description
- Add additional context to COVID FAQ link clicks for the FAQ where the click occurred within
    
- What team/project is this work for?
    _COVID-19 Dashboard_
    
- Provide the Domain where Google Analytics needs to be implemented
    _https://staging.va.gov/coronavirus-veteran-frequently-asked-questions/_

## Acceptance Criteria
- [ ] Give additional context to Navigation - COVID events with the FAQ for where the click occurred
- [ ] QA has been completed for each FAQ
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
@bsmartin-ep Let's connect quickly at some point today to point.

**Comment by bsmartin-ep** [comment]
@jonwehausen - I added the extra CD (and Home page trigger) to this new workspace....

https://www.googletagmanager.com/start_preview/gtm?uiv2&id=GTM-WFJWBD&check_preview_status=1&gtm_auth=2hsOnODCLBLeBDieFeEMcQ&gtm_preview=env-826&gtm_debug=x

...and the new CD to GA....

https://analytics.google.com/analytics/web/#/a50123418w178298118p176884211/admin/custom-dimensions/m-content-dimensionsContent.rowShow=10&m-content-dimensionsContent.rowStart=70&m-content-dimensionsContent.sortColumnId=index&m-content-dimensionsContent.sortDescending=false&m-content.mode=EDIT&m-content.uid=LJBlYeD-S0WASwQaeuUSeA

Let me know how this looks.  And if you have any suggestions for naming since this is weird to describe - _COVID FAQ's Link's FAQ_ ???

**Comment by jonwehausen** [comment]
### QA Tests - 4.2.2020

Screenshot of Interaction | Tag QA | Status
------------ | ------------- | -------------
![whats_covid_interaction_click](https://user-images.githubusercontent.com/48527022/78300454-8717ed80-7505-11ea-8b64-c5adbfa67692.png) | ![whats_covid_tag](https://user-images.githubusercontent.com/48527022/78300507-9b5bea80-7505-11ea-9d40-0fa5e83b5c0c.png) | ✅ **PASSED**
![symptons_interaction_click](https://user-images.githubusercontent.com/48527022/78300617-c5ada800-7505-11ea-9aac-438bd78df8f0.png) | ![have_symptoms_tag](https://user-images.githubusercontent.com/48527022/78300660-d65e1e00-7505-11ea-90a6-c3ae358ea7bb.PNG) | ✅ **PASSED**
![deal_with_covid_interaction_click](https://user-images.githubusercontent.com/48527022/78301279-d9a5d980-7506-11ea-97c3-94038a069ea0.png) | ![deal_with_covid_tag](https://user-images.githubusercontent.com/48527022/78301488-238ebf80-7507-11ea-9402-0167202bf059.PNG) | ✅ **PASSED**
![tested_for_covid_interaction_click](https://user-images.githubusercontent.com/48527022/78301543-3608f900-7507-11ea-9cd8-70b6796e48ff.PNG) | ![can_i_be_tested_tag](https://user-images.githubusercontent.com/48527022/78301094-98adc500-7506-11ea-9652-99e8491075fb.PNG) | ✅ **PASSED**
![upcoming_appointment_interaction_click](https://user-images.githubusercontent.com/48527022/78301579-4f11aa00-7507-11ea-8c99-68b29141c6ff.png) | ![upcoming_appointment_tag](https://user-images.githubusercontent.com/48527022/78301719-81230c00-7507-11ea-9f12-712cae7a3e23.PNG) | ✅ **PASSED**
![reschedule_or_cancel_appointment_interaction](https://user-images.githubusercontent.com/48527022/78301879-c34c4d80-7507-11ea-9fcf-74eb1d4ca7f3.png) | ![reschedule_or_cancel_appointment_tag](https://user-images.githubusercontent.com/48527022/78301904-cf380f80-7507-11ea-9cd3-95579564de66.png) | ✅ **PASSED**
![tried_to_call_interaction](https://user-images.githubusercontent.com/48527022/78301947-e24adf80-7507-11ea-8741-9095f4d1b025.png) | ![tried_to_call_tag](https://user-images.githubusercontent.com/48527022/78301986-f858a000-7507-11ea-847e-70ffac6f4328.png) | ✅ **PASSED**
![refill_my_perscription_interaction_click](https://user-images.githubusercontent.com/48527022/78302028-0c9c9d00-7508-11ea-83c3-5f214d169f03.png) | ![refill_my_perscription_tag](https://user-images.githubusercontent.com/48527022/78302033-0f978d80-7508-11ea-9cad-ad1ae005bf59.png) | ✅ **PASSED**
![emergency_care_interaction_click](https://user-images.githubusercontent.com/48527022/78302110-2fc74c80-7508-11ea-83ba-3716bf06b15f.png) | ![emergency_care_tag](https://user-images.githubusercontent.com/48527022/78302122-335ad380-7508-11ea-9b16-fc7033f1d44d.png) | ✅ **PASSED**
![no_symptions_anxious_interaction_click](https://user-images.githubusercontent.com/48527022/78302185-4c638480-7508-11ea-8562-dd2634633058.png) | ![no_symptions_anxious_tag](https://user-images.githubusercontent.com/48527022/78302223-5eddbe00-7508-11ea-8f85-eeca6246bf9b.png) | ✅ **PASSED**

@bsmartin-ep Great job! Thanks for getting done so quickly. A couple tweaks I made: 
- Added a home button condition to {{JS - Generic - Click Text Null Check}} to include "Home VA Logo" when user clicks home logo
- There was an additional condition for click class = processed-content p a that I removed within the trigger "CL- COVID FAQ". Prior to not removing, there were a few clicks within each section that did not fire the tag. Once removed, they all worked but please let me know if there is another purpose behind that condition and we can discuss prior to publishing.

**Comment by bsmartin-ep** [comment]
Thanks for testing @jonwehausen .

> There was an additional condition for click class = processed-content p a that I removed within the trigger "CL- COVID FAQ". Prior to not removing, there were a few clicks within each section that did not fire the tag. Once removed, they all worked but please let me know if there is another purpose behind that condition and we can discuss prior to publishing.

Hmmm - I think without _some_ kind of filter, this will trigger for any link on this page.

I think I meant to use Click Element (not Click Class).  I added that to the trigger.  Anything not firing now?

**Comment by bsmartin-ep** [comment]
OK @jonwehausen  - I think this is working if you want to re-test.  I changed the _Page URL starts with_ to _Page Path starts with_ and made the above change to the CSS selector.

**Comment by jonwehausen** [comment]
Went thru another round of testing here! Looks great! Publishing and closing.
