### ISSUE TITLE
Update cache-control header to no-cache

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#7473]
## Overview 

VA.gov cache busts JS and CSS using a hashed filename that changes on every release. This requires an update to the static content every release to the reference in the script and link tags. 

## Goal 

- Verify that the `cache-control` header can handle cache busting of JS and CSS 

## Tasks 

- Follow [Pattern 2: Mutable content, always server-revalidated](https://jakearchibald.com/2016/caching-best-practices/)
  - replace `max-age` with `no-cache` in the `cache-control` header
- Deploy and validate 
  - On Firefox, Chrome, IE 11, and mobile Safari validate that following the initial page load, subsequent requests of JS and CSS assets result in a network request and a 304 Not Modified response 
  - Use Speed Curve to measure impact to homepage

**Comment by cvalarida** [comment]
ansible/deployment/roles/deploy-vets-website/files/vets-website-deploy.sh may be the place to do this.
