### ISSUE TITLE
4.2 Reprocessing with correct Ancillary signed at dates

### ISSUE THREAD

**Issue by SamStuckey** [department-of-veterans-affairs/va.gov-team#74738]
1. sync with tommasina about how to leverage her changes to do this
2. confirm w/ emily: we want to rerun the entire batch?
3. rerun it

**Comment by SamStuckey** [comment]
[Emily raising it in slack](https://dsva.slack.com/archives/C04KW0B46N5/p1706296800332739)

**Comment by SamStuckey** [comment]
UPDATE: the code changes that fix this bug are live, so this is probably as simple as pulling a fresh copy of the app to our task server and rerunning

TODO: get some example IDs from emily so i can test

**Comment by austinjprice** [comment]
need by Feb 2

**Comment by SamStuckey** [comment]
Potential Blocker: we may have a discrepancy between ancillary docs in VBMS and their representations in our DB.  Identified by crosschecking with David R's work sheet.  [More context here](https://dsva.slack.com/archives/C053U7BUT27/p1706729535721779?thread_ts=1706727152.783229&cid=C053U7BUT27)

**Comment by SamStuckey** [comment]
Pulling in the new code didn't fix the ancillary date problem, so I will probably need to cherry pick stuff from tommasinas code changes

**Comment by SamStuckey** [comment]
Pulling in the new code didn't fix the ancillary date problem, so I will probably need to cherry pick stuff from tommasinas code changes
