### ISSUE TITLE
Adding Kamel Purnell to DSVA Slack

### ISSUE THREAD

**Issue by huggins-va** [department-of-veterans-affairs/va.gov-team#74732]
Please add Kamel Purnell as a multi-channel user
work email: purnell_kamel@bah.com
VA email: kamel.purnell@va.gov
Channels: 

- Lighthouse-team-honeybadgers 

- lighthouse-delivery-platform-support 

Kamel Purnell is returning to support Lighthouse on team Honey Badgers as a DevOps Engineer. 

Thank you!

**Comment by LEHigley** [comment]
couldn't add to team channel
