### ISSUE TITLE
Complete zipCode metadata fix for foreign vets

### ISSUE THREAD

**Issue by SamStuckey** [department-of-veterans-affairs/va.gov-team#74741]
When a vet has a foreign address, their submissions metadata should include the value
`zipCode: '00000'`

Currently it does not.  This is causing submissions to error after they reach LH.  We are currently manually remediating these.

[This PR fixes this bug.  Finish it](https://github.com/department-of-veterans-affairs/vets-api/pull/15204)

**Comment by freeheeling** [comment]
Drafted PR [#15357](https://github.com/department-of-veterans-affairs/vets-api/pull/15357), but blocked by [failing Code Check](https://github.com/department-of-veterans-affairs/vets-api/actions/runs/7759248448/job/21162889205?pr=15357).

<img width="1288" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGtsQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--537cef57451fe6720e3e8cf294f023e7d3b83f72/Screen%20Shot%202024-02-02%20at%2010.52.28%20AM.png" alt="Screen Shot 2024-02-02 at 10.52.28 AM.png" />

**Comment by freeheeling** [comment]
Thomas provided guidance to help unblock the failing code check. PR [#15357](https://github.com/department-of-veterans-affairs/vets-api/pull/15357) posted for review.

**Comment by freeheeling** [comment]
Merged PR after receiving final approval. Will move to 'Done' once this afternoon's deploy is confirmed.

**Comment by freeheeling** [comment]
Moving to 'Done' with successful production environment deploy status at https://deploy-status-dashboard.fly.dev/apps/vets-api/deploy_status.
