### ISSUE TITLE
[Discovery] Appeals: Appeals Status Errors in Grafana are High and Need Investigation

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#7476]
## User Story or Problem Statement
How might we understand and plan on reducing appeals status errors?

1. What errors are VSA FE or BE related.
2. What errors are downstream from us but still involve how we package data (like the 526 issues between us and EVSS)
3. What different categories of errors are we seeing?

Example of errors:
![image.png](https://images.zenhubusercontent.com/5d54025346ffca000148e7f7/edf38a24-8b6d-4981-bc61-eabd41ac159c)

## Goal
Understand the different error types and how we can work to reduce them.

## Objectives or Key Results this is meant to further
Reduced number of errors.

## Acceptance Criteria
- [ ] Stories for future work

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by SarahJaine** [comment]
## Context
AppealsApp is instantiated from within vets-api as a separate module (`modules/appals_api`) which is served at endpoint `/v0/appeals`. Our team's applications make calls to this service, just as we do to other integrated services like MVI. The responses that we receive from this service are monitored. Visualization of the monitoring are available on a the [Appeals Status dashboard in Grafana](http://grafana.vfs.va.gov/d/000000035/appeals-status?orgId=1).

## Error detail
Sample week of errors, by error type.

### Upstream errors
These errors make up the bulk of the error total. 500 errors which indicate an outage with the upstream service. Unfortunately, these are outside of our application's control and indicate a problem with availability or stability of the upstream service (the AppealsApp or its dependencies.)
- 503 Service Unavailable
	- ~ 28k per week
	- Error is thrown in event of planned or unexpected service outage
- 504 Gateway Timeout
	- ~ 10k per week 
	- Error thrown for upstream timeout
- 502 Bad Gateway
	- ~ 200 per week
	- Error throw for Bad Gateway/invalid response

### Neutral errors
These errors, particularly the 404, make up a substantial part of our total error count. These errors don't indicate problems with the requests or the responding service.
- 404 Not found
	- ~ 22k per week
	- A 404 is thrown when the AppealsService can not find an appeal for the veteran. We routinely check for appeals, so the 404 here doesn't indicate a problem, just simply that the veteran hasn't started an appeal. You can think of this as a `null` response to a database search.
- 401 Unauthorized
	- ~ 3k per week
	-  Error is thrown when the user is not authenticated (logged in). This is similar to someone jiggling a handle before using a key to unlock a door. It doesn't indicate a problem, just that the user attempted to do something before logging into the service. My only concern here is that we're presenting users with an option they can't access. I'll investigate this further.

### Errors that would indicate problems
The errors below would indicate to me that there is a problem with the requests we're making to the AppealsApp. There were zero instances of these errors in grafana (which holds 15 days worth of data).
- 403 Forbidden / Bad API Token
	- 0 per week
	- Error thrown when we supply a bad API Token to the Appeals App.
- 422 Unprocessable Entity / Json Parse error
	- 0 per week
	- Error thrown when the data we submit to the AppealsApp is incorrectly formatted.
- 400 Bad Request / Missing SSN header
	- 0 per week
	- This would indicate that we're requesting the AppealApp but we're missing the user's required SSN in the header.
