### ISSUE TITLE
DR | Check if anything will break if we switch our form components to V3

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#74769]
## Background Context
This is a spike to check for incompatibilities and possible breaks associated with switching over to the design system's V3 components. 

---
## Tech Tasks
- [ ] compare a [v1 component (va-button)](https://design.va.gov/storybook/?path=/docs/components-va-button--primary) to a [v3 web component](https://design.va.gov/storybook/?path=/docs/uswds-va-button--primary) for every type we use
- [ ] Comment any risks and next steps in this ticket
- [ ] Refine user stories in the epic

## Definition of Ready 

- [ ] FE devs have access to resources needed to compare components

## Definition of Done

- [ ] Potential breaks are identified
- [ ] Work is refined in the user stories that are part of the epic
- [ ] Reviewed and approved by product and design as needed

**Comment by HeatherWidmont** [comment]
Closing this in favor of the tickets in [this epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/73812)
