### ISSUE TITLE
Enable ScheduleCernerPage.unit.spec.jsx skipped unit test

### ISSUE THREAD

**Issue by vbahinwillit** [department-of-veterans-affairs/va.gov-team#74765]
## Description
This ticket is related to the unit test cleanup ticket #61858. A number of test where skipped for later review. This ticket enables the ScheduleCernerPage.unit.spec.jsx skipped unit test.

---

## Acceptance Criteria
- [ ] All test scenarios should pass

### Design Assets
N/A

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket.
