### ISSUE TITLE
Fix the weekly polling script's 'Total Submission' value

### ISSUE THREAD

**Issue by SamStuckey** [department-of-veterans-affairs/va.gov-team#74768]
It seems like we might have given A bad number, or have some retries complicating things.

Per David:
Good morning Sam.  On your weekly error count email you had this line.... is this number correct?
- Total Number of auto-establish Failures: 320466
Is that an all time number, a misprint, or what is it?

This seems wrong, take a look

**Comment by SamStuckey** [comment]
UPDATE: the join I"m doing on between our timeboxed submissions and `form526_job_statuses` is adding rows that shouldn't be there.  Next steps are to correct this SQL bug

**Comment by austinjprice** [comment]
@tblackwe to reach out to ks
