### ISSUE TITLE
Discovery work: Learn how to update SOCKS GHA to check roster

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#74775]
## Description
Now that we are no longer updating the spreadsheet, we need to understand how to run a GitHub Action in order to have the roster checked whenever a SOCKS access ticket is opened. This ticket is for the discovery work and documentation to be completed in order to understand that. 

When a SOCKS access ticket is opened, a Github Action is run to check the roster. Since we will no longer be updating the spreadsheet, we will need to update this GHA to check the database OR disable it for the time being and make it a required manual check. We could add this as a feature during the next iteration.

## Tasks:
- [x] Research how to run GitHub action to check roster
- [x] Determine success criteria for test run
- [x] Document solutions

**Comment by LindseySaari** [comment]
The `product_directory_team_members` table has `first_name`, `last_name` and `github_username` fields. We will probably want to check these fields in whatever solution we decide to go with

**Comment by LindseySaari** [comment]
It seems that utilizing API tokens may be the best way to go. Utilizing the API routes from GitHub Actions isn't meant to be associated with a specific user, so a more general system for managing API tokens seems appropriate. I think we will want to query on github handle, to avoid any discrepancies in names in the onboarding ticket (e.g. nicknames, maiden names, typos, etc)

**Comment by LindseySaari** [comment]
I wrote up [the discovery doc here](https://vfs.atlassian.net/wiki/spaces/PPT/pages/2948530270/Discovery+SOCKS+Requests+Github+Action+verification+with+Atlas) and detailed two solutions. I think this ticket can be closed and we can move onto the implementation next.
