### ISSUE TITLE
Update list of Primary Submission Failures causes

### ISSUE THREAD

**Issue by tblackwe** [department-of-veterans-affairs/va.gov-team#74778]
To determine what failures we need to be addressing, we need to update the list of primary submission failures to ensure nothing has been added/fixed/made worse.

@SamStuckey has a script to accomplish this update, but it needs an update and then needs to be executed.
This ticket is to support that effort

The results should be added as comment to this ticket

https://docs.google.com/spreadsheets/d/11S2a-QpkZ0W46mvS9LR8-tBann6L864f/edit#gid=799319385

**Comment by SamStuckey** [comment]
COMPLETE: see attached report for last 3 months of errors (primary / backup)
[3-month-failure-report.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDA1QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cb81e0cef44698c72b13e396a84a820d93482142/3-month-failure-report.zip)

**Comment by tblackwe** [comment]
| **error message**                                                                                                                                                                                                          | **failure type** | **error count** | **last occurance**      | **last report update**    |
| -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------- | --------------- | ----------------------- | ------------------------- |
| **Validation error**                                                                                                                                                                                                       | backup           | 164             | 2024-02-03 16:07:19 UTC | 2024-02-07 15:17:36 +0000 |
| **Outage detected on EVSS/DisabilityCompensationForm beginning at**                                                                                                                                                        | backup           | 8               | 2024-01-19 15:22:03 UTC | 2024-02-07 15:17:36 +0000 |
| **Java Error (gov.va.wss.partner.veteranrecord.ws.client.VeteranRecordWsClientException)**                                                                                                                                 | backup           | 5               | 2023-11-17 22:16:43 UTC | 2024-02-07 15:17:36 +0000 |
| **unexpected token at '<?xml version="." encoding="UTF-"?><Error><Code>AccessDenied</Code><Message>Request has expired</Message><X-Amz-Expires></X-Amz-Expires><Expires>--T::Z</Expires><ServerTime>--T::Z</ServerTime><** | backup           | 5               | 2023-12-22 19:32:21 UTC | 2024-02-07 15:17:36 +0000 |
| **User uploaded file failed to process**                                                                                                                                                                                   | backup           | 3               | 2023-12-26 16:51:27 UTC | 2024-02-07 15:17:36 +0000 |
| **Net::OpenTimeout**                                                                                                                                                                                                       | backup           | 2               | 2023-12-02 22:32:23 UTC | 2024-02-07 15:17:36 +0000 |
| **undefined method \`gsub' for nil:NilClass**                                                                                                                                                                              | backup           | 2               | 2024-01-23 17:10:45 UTC | 2024-02-07 15:17:36 +0000 |
| **unexpected token at '<html><body><h> Gateway Time-out</h>The server didn't respond in time.</body></html>'**                                                                                                             | backup           | 1               | 2024-01-15 13:19:09 UTC | 2024-02-07 15:17:36 +0000 |
| **form.submit.establishClaim.serviceError**                                                                                                                                                                                | primary          | 839             | 2024-02-07 01:17:55 UTC | 2024-02-07 15:17:36 +0000 |
| **External service unavailable**                                                                                                                                                                                           | primary          | 732             | 2024-02-06 10:39:52 UTC | 2024-02-07 15:17:36 +0000 |
| **form.submit.noRetryError**                                                                                                                                                                                               | primary          | 390             | 2024-02-04 18:12:43 UTC | 2024-02-07 15:17:36 +0000 |
| **form.serviceInformation.reservesNationalGuardService.obligationTermOfServiceToDate.IsNotValid**                                                                                                                          | primary          | 162             | 2024-02-03 16:07:19 UTC | 2024-02-07 15:17:36 +0000 |
| **form.serviceInformation.reservesNationalGuardService.obligationTermOfServiceFromDate.IsNotValid**                                                                                                                        | primary          | 152             | 2024-02-03 16:07:19 UTC | 2024-02-07 15:17:36 +0000 |
| **form.treatments[].endDateIsNull**                                                                                                                                                                                        | primary          | 54              | 2024-02-01 17:42:56 UTC | 2024-02-07 15:17:36 +0000 |
| **form.submit.save.draftForm.MaxEPCode**                                                                                                                                                                                   | primary          | 51              | 2024-01-30 01:28:26 UTC | 2024-02-07 15:17:36 +0000 |
| **form.disabilities[].ratedDisability.isInvalid**                                                                                                                                                                          | primary          | 49              | 2023-11-16 00:33:16 UTC | 2024-02-07 15:17:36 +0000 |
| **form.serviceInformation.servicePeriods.refdataservice.errorResponse**                                                                                                                                                    | primary          | 24              | 2024-02-01 17:42:56 UTC | 2024-02-07 15:17:36 +0000 |
| **form.directDeposit.isNull**                                                                                                                                                                                              | primary          | 21              | 2024-01-24 18:12:58 UTC | 2024-02-07 15:17:36 +0000 |
| **form.disabilities[].name**                                                                                                                                                                                               | primary          | 21              | 2023-11-13 20:22:19 UTC | 2024-02-07 15:17:36 +0000 |
| **form.veteran.currentMailingAddress.refdataservice.errorResponse**                                                                                                                                                        | primary          | 21              | 2024-01-27 23:55:58 UTC | 2024-02-07 15:17:36 +0000 |
| **form.disabilities.Size**                                                                                                                                                                                                 | primary          | 19              | 2024-02-02 15:46:39 UTC | 2024-02-07 15:17:36 +0000 |
| **Outage detected on EVSS/DisabilityCompensationForm beginning at**                                                                                                                                                        | primary          | 16              | 2024-02-05 00:24:30 UTC | 2024-02-07 15:17:36 +0000 |
| **form.directDeposit.accountNumber.Size**                                                                                                                                                                                  | primary          | 14              | 2024-01-18 02:48:59 UTC | 2024-02-07 15:17:36 +0000 |
| **form.serviceInformation.refdataservice.errorResponse**                                                                                                                                                                   | primary          | 13              | 2024-02-02 01:11:58 UTC | 2024-02-07 15:17:36 +0000 |
| **PG::NotNullViolation: ERROR:  null value in column "form_submission_id" of relation "form_job_statuses" violates not-null constraint**                                                                                   | primary          | 9               | 2024-01-19 19:44:06 UTC | 2024-02-07 15:17:36 +0000 |
| **BackendServiceException: {:source:"EVSS::DisabilityCompensationForm::Service", :code:"EVSS"}**                                                                                                                           | primary          | 8               | 2024-02-04 19:57:19 UTC | 2024-02-07 15:17:36 +0000 |
| **form.serviceInformation.servicePeriods[].activeDutyBeginDate**                                                                                                                                                           | primary          | 6               | 2024-01-11 20:35:17 UTC | 2024-02-07 15:17:36 +0000 |
| **PG::NotNullViolation: ERROR:  null value in column "form_submission_id" violates not-null constraint**                                                                                                                   | primary          | 5               | 2023-11-17 22:16:43 UTC | 2024-02-07 15:17:36 +0000 |
| **Gateway timeout**                                                                                                                                                                                                        | primary          | 5               | 2024-01-27 16:12:41 UTC | 2024-02-07 15:17:36 +0000 |
| **no ICN passed in for LH API request.**                                                                                                                                                                                   | primary          | 5               | 2024-01-29 21:13:00 UTC | 2024-02-07 15:17:36 +0000 |
| **form.serviceInformation.TitlePastActiveDutyDate**                                                                                                                                                                        | primary          | 4               | 2024-01-03 13:43:43 UTC | 2024-02-07 15:17:36 +0000 |
| **Unprocessable Entity**                                                                                                                                                                                                   | primary          | 3               | 2024-02-07 01:17:55 UTC | 2024-02-07 15:17:36 +0000 |
| **form.treatments[].startDateIsNull**                                                                                                                                                                                      | primary          | 2               | 2024-01-06 08:50:58 UTC | 2024-02-07 15:17:36 +0000 |
| **java.lang.NullPointerException**                                                                                                                                                                                         | primary          | 2               | 2023-12-05 20:13:58 UTC | 2024-02-07 15:17:36 +0000 |
| **form.serviceInformation.reservesNationalGuardService.titleActivation.anticipatedSeparationDate.IsNotValid**                                                                                                              | primary          | 2               | 2023-12-05 20:13:58 UTC | 2024-02-07 15:17:36 +0000 |
| **end of file reached**                                                                                                                                                                                                    | primary          | 2               | 2024-02-07 05:37:01 UTC | 2024-02-07 15:17:36 +0000 |
| **form.serviceInformation.confinements[].confinementEndDate.Past**                                                                                                                                                         | primary          | 1               | 2023-11-29 17:14:18 UTC | 2024-02-07 15:17:36 +0000 |
| **org.springframework.context.NoSuchMessageException**                                                                                                                                                                     | primary          | 1               | 2024-01-20 16:33:27 UTC | 2024-02-07 15:17:36 +0000 |
| **form.disabilities[].isDuplicate**                                                                                                                                                                                        | primary          | 1               | 2024-01-27 23:55:58 UTC | 2024-02-07 15:17:36 +0000 |
| **EVSS_**                                                                                                                                                                                                                  | primary          | 1               | 2024-01-28 01:32:23 UTC | 2024-02-07 15:17:36 +0000 |
| **Bad Gateway**                                                                                                                                                                                                            | primary          | 1               | 2024-02-03 04:48:09 UTC | 2024-02-07 15:17:36 +0000 |
| **undefined local variable or method \`e' for #<BenefitsClaims::ServiceException:xff>**                                                                                                                                    | primary          | 1               | 2024-02-04 17:02:36 UTC | 2024-02-07 15:17:36 +0000 |
| **undefined local variable or method \`e' for #<BenefitsClaims::ServiceException:xfbcae>**                                                                                                                                 | primary          | 1               | 2024-02-05 02:19:11 UTC | 2024-02-07 15:17:36 +0000 |
