### ISSUE TITLE
Design Intent - Design Feedback - IVC Forms, FMP 10-7959f-1 FMP Registration

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#74805]
## VFS actions
- [x] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [x] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- Should: On the review page, add a link that goes back to the VA home page. Look at our [confirmation page](https://design.va.gov/templates/forms/confirmation) for an example.

**Comment by brian-wilke** [comment]
Updated this item in our post DI pages. Ok to review/close for now (may have more copy changes via CAIA)
