### ISSUE TITLE
Access for Brian Martin

### ISSUE THREAD

**Issue by bsmartin-ep** [department-of-veterans-affairs/va.gov-team#7481]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Jeffrey Hayter
- Please provide your name.
   > Brian Martin
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > VSP Analytics + Insights, Analytics Consultant, Empirical Path
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCeUnCa49iXlcBfSXj+9NY8fhmjZcUIKyPWR0Kg1NVH1cnqN8nENOGRZIaQEemTVaW4CwBGi9jFzxTlKY+hoMvPfQXALo4lLSPMKOCxCj6W3acJ3M0yOrGi/haYCclBJR+vrcJqPHIyWCG/1OdHU72nvOM7W9d1GalMf33sgMWiTQAmblBBDBoIFPzGwwW3QeT6mNTZozu3tnMYe/hmWrSkpCiYFrHPQZIYJSA0BqTY6+V6uztaAaqpcPndx/fCSqf0Q948yebzhmt6L61vNoAcge6tIQosHDK6pOysG3mOFpdYNdWHIEpDNK/B0Di4UJ74r5pG8kQHKAucyJS6Cxmt brian-ep@bsmartin-ThinkPad-X230
```

- [Grant AWS Console access?]
  >  NO
  >  Please give a brief description for why you are requesting AWS access.

**Comment by tskinn** [comment]
@bsmartin-ep you should be able to access the socks proxy now. Reach out in slack if you have any issues.
