### ISSUE TITLE
[Development] Update Form Expiration Dates for GI Bill and Form Updates

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#7482]
## User Story or Problem Statement
GI Bill form is showing expiration date in the past:

- GI Bill® School Feedback Tool
  - https://www.va.gov/education/submit-school-feedback/introduction
  - Showing 12/31/2018
  - Update to ??? (Can't find OMB 2900-0797 source to get the expiration date)
  - UPDATE: GI Bill is changing the form so this is split into a new ticket here:

We are waiting for additional info on whether this form is getting updated.

## Specs:
- Device: All
- Browser: All
- Test User: N/A

## Steps to Reproduce
Look at OMB date at the bottom of each page

- GI Bill® School Feedback Tool - https://www.va.gov/education/submit-school-feedback/introduction

## Desired behavior
The updated expiration date should be shown in the listed form

## Acceptance Criteria
Update form expiration date to match the actual forms
- [ ] GI Bill School feedback - ??
- [ ] Update form with minor field updates

**Comment by Mottie** [comment]
I see the expiration date has been updated to `01/31/2022` (still expired), but I believe this form is owned by the BAH team, so I'm going to close it and leave updating this up to them.
