### ISSUE TITLE
AWS access for Don Shin

### ISSUE THREAD

**Issue by cloudmagic80** [department-of-veterans-affairs/va.gov-team#74836]
### COR Name

Eunice Garcia

### Vendor Onboarding Representative Name

Agile Six - Anthony M. Arashiro

### Your Name

Don Shin

### Your Email

don.shin@agile6.com

### Team, Role, and Company of the target individual

CHAMPVA team

### Product Manager (PM) name and email

bo.altes@agile6.com

### Product Owner (PO) name and email

premal.shah@va.gov

### Desired AWS Access

The IVC Form team will be pushing the digitized forms to a S3 service. Bucket TBD but we all need accounts in AWS before we can be granted access to any bucket. I will need console and admin access and write access. 

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

<img width="1728" alt="eqip transmittal" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/99479640/f774af08-0480-447b-8c83-7519c8b3feff">

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [X] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by barbarello** [comment]
user in Atlas

**Comment by barbarello** [comment]
Access granted and temporary credentials passed to user

**Comment by cloudmagic80** [comment]
@barbarello  I can't create an S3 bucket because I don't have permissions. Here is the error:
Failed to create bucket
To create a bucket, the s3:CreateBucket permission is required.
To apply the Bucket owner preferred or Object writer setting for Object Ownership, the s3:PutBucketOwnershipControls permission is required.

**Comment by cloudmagic80** [comment]
@barbarello All we need is an AWS S3 bucket created. It is platform team that needs to create it for us. Do you know who in the platform team is the right contact?

**Comment by ph-One** [comment]
@cloudmagic80 Please submit a Support request in [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) for any S3 bucket creation. Closing this request as AWS access has been granted.
