### ISSUE TITLE
[Development] 526: Improve Error Logging by Using Unique Identifier Veteran Can Reference When Calling Help Desk

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#7483]
## User Story or Problem Statement
How might we improve the Call Center to VSA debugging process

### Problem
Bug tickets originating from the Help Desk often lack the context we need to investigate and resolve the issue. The logging and monitoring systems do not contain PII or other information that would help us find the exact transaction or exception that the user is experiencing.  Oftentimes, the only information we use to search the logs is a general time of day or an error message; search terms that yield thousands of results.

### Proposed solution: 
All errors that are reported to the user with help text directing the user to contact the service desk include an identifier unique to that user session and directs the user to include the report the identified to the help desk. The identifier is logged in Sentry, thereby allowing developers to find the exact error quickly. There are several ids peppering the logs that are possible candidates to be the id used for this: request_id, request_uuid, and transaction_id.  We need to investigate which one is most appropriate to this purpose, standardize its use, and communicate its renewed purpose to VSP. This change will need investigation and buy in from design/research, frontend and backend developers, and VSP.

## Goal
Understand the different error types and how we can work to reduce them.

## Objectives or Key Results this is meant to further
VSA will have a way to provide unique identifiers to the front end when errors are submitted.

## Acceptance Criteria
- [ ] VSP and VSA work is coordinated - additional stories for VSP created
- [ ] Front-end or back-end code is updated

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by luke-gcio** [comment]
## User Story or Problem Statement
How might we improve the Call Center to VSA debugging process

### Problem
Bug tickets originating from the Help Desk often lack the context we need to investigate and resolve the issue. The logging and monitoring systems do not contain PII or other information that would help us find the exact transaction or exception that the user is experiencing.  Oftentimes, the only information we use to search the logs is a general time of day or an error message; search terms that yield thousands of results.

### Proposed solution: 
All errors that are reported to the user with help text directing the user to contact the service desk include an identifier unique to that user session and directs the user to include the report the identified to the help desk. The identifier is logged in Sentry, thereby allowing developers to find the exact error quickly. There are several ids peppering the logs that are possible candidates to be the id used for this: request_id, request_uuid, and transaction_id.  We need to investigate which one is most appropriate to this purpose, standardize its use, and communicate its renewed purpose to VSP. This change will need investigation and buy in from design/research, frontend and backend developers, and VSP.

## Goal
Understand the different error types and how we can work to reduce them.

## Objectives or Key Results this is meant to further
VSA will have a way to provide unique identifiers to the front end when errors are submitted.

## Acceptance Criteria
- [ ] VSP and VSA work is coordinated - additional stories for VSP created
- [ ] Front-end or back-end code is updated

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by SarahJaine** [comment]
Summary for ticket:
**Error type:** After the user hits submit on form526, and error prevents the application from being submitted to EVSS. An user is directed to an error page with a message asking them to try again or call the help desk for assistance.
- For example, in staging, if the service member's separation date is >180 days before the submission date the BE sends the following error response to the FE:
`{“data”:{“id”:“”,“type”:“form526_job_statuses”,“attributes”:{“claimId”:null,“jobId”:“bb82e197d36f809fc14039e7”,“submissionId”:453,“status”:“non_retryable_error”,“ancillaryItemStatuses”:[]}}}`. Importantly, this error array contains the `subsmissionId`.
- The `subsmissionId` would be a good reference ID for calls to the service desk because:
1. It is unique to the application.
2. It is not PII.
3. BE engineers can find use the submission to look up the veteran and their application very easily and quickly with the help of a rake task that is already available.
- Unfortunately, no backend engineering work is available for this ticket.  I've written up a placeholder ticket for the front end instead.
