### ISSUE TITLE
10-7959f-1 - Build Veteran's Information page

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#74843]
As a user on va.gov, I want to enter my information so that I can be contacted after I register for the FMP program.

[wireframes](https://www.figma.com/file/PzB1F5TYuBK5KQgPbuhAwH/10-7959f-1?type=design&mode=design&t=OeOXjtTcLtw3Cj9G-0)

Acceptance criteria:
- display first name field with entry required
- display middle name field
- display last name field with entry required
- suffix is selectable from dropdown
- date of birth is set to required
  - month is selectable from dropdown
  - date and year can be entered into date of birth fields
- data is pre filled if user is signed in
- user can go forward or back to previous pages

Build front end of the form using the forms-library:
[ ] Using the JSON schema and design mockups, build out the chapters (using other simple forms)
[ ] Using the JSON schema, chapters, and design mockups, build out the pages (using other simple forms)
[ ] Update formConfig with the submitUrl, preSubmitInfo, transformForSubmit, footerContent and getHelp

**Comment by reiting** [comment]
Waiting for code review
