### ISSUE TITLE
10-7959f-1 - Build Contact Information page

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#74847]
As a user on va.gov, I want to enter my phone number and email address so that I can be contacted for the FMP program.

[Figma link as of 3/6](https://www.figma.com/file/PzB1F5TYuBK5KQgPbuhAwH/10-7959f-1?type=design&node-id=347-13608&mode=design)

Acceptance criteria:
- phone number can be entered in open text field (optional)
- email can be entered in open text field (optional)
- user can go forward or back to previous pages
- user data should be pre filled if signed in
- data validation and error messaging as appropriate
- use v3 components

Build front end of the form using the forms-library

[ ] Using the JSON schema and design mockups, build out the chapters (using other simple forms)
[ ] Using the JSON schema, chapters, and design mockups, build out the pages (using other simple forms)
[ ] Update formConfig with the submitUrl, preSubmitInfo, transformForSubmit, footerContent and getHelp

**Comment by reiting** [comment]
Waiting for review

**Comment by reiting** [comment]
@marywang2 this has been merged!
