### ISSUE TITLE
10-7959f-1 - Build home address page

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#74853]
As a user on va.gov, I want to enter my home address so that I can be contacted for the FMP program.

[wireframes](https://www.figma.com/file/PzB1F5TYuBK5KQgPbuhAwH/10-7959f-1?type=design&node-id=1-19&mode=design&t=OeOXjtTcLtw3Cj9G-0)

Acceptance criteria:
- country is selectable from dropdown (set to required)
- street address is text field (set to required)
- apartment or unit number is text field (optional)
- city is text field (set to required)
- state is selectable from dropdown (set to required)
- zip code is text field (set to required)
- address confirmation (with appropriate messaging)
- data is prefilled when user is signed in
- error messaging where appropriate
- use v3 components

Build front end of the form using the forms-library

[ ] Using the JSON schema and design mockups, build out the chapters (using other simple forms)
[ ] Using the JSON schema, chapters, and design mockups, build out the pages (using other simple forms)
[ ] Update formConfig with the submitUrl, preSubmitInfo, transformForSubmit, footerContent and getHelp

**Comment by reiting** [comment]
Waiting for platform approval.

**Comment by reiting** [comment]
Platform has approved and this PR is merged.
