### ISSUE TITLE
10-7959f-1 - Build review page

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#74868]
As a user on va.gov, I want to review the information that I entered so that I can make any changes before I submit for FMP.

[FIgma link as of 3/6](https://www.figma.com/file/PzB1F5TYuBK5KQgPbuhAwH/10-7959f-1?type=design&node-id=347-13608&mode=design)

Acceptance criteria:
- user can review completed sections
- statement of truth pattern with name field and checkbox (both required)
- v3 components
- user can submit (submit button) or go back to previous pages

Build front end of the form using the forms-library

[ ] Using the JSON schema and design mockups, build out the chapters (using other simple forms)
[ ] Using the JSON schema, chapters, and design mockups, build out the pages (using other simple forms)
[ ] Update formConfig with the submitUrl, preSubmitInfo, transformForSubmit, footerContent and getHelp

**Comment by reiting** [comment]
Waiting for review

**Comment by reiting** [comment]
@marywang2 this PR has been approved and merged!
