### ISSUE TITLE
10-7959f-1 Build mailing address page

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#74869]
As a user on va.gov, I want to enter my address so that I can be contacted for the FMP program.

[wireframes](https://www.figma.com/file/PzB1F5TYuBK5KQgPbuhAwH/10-7959f-1?type=design&node-id=1-19&mode=design&t=OeOXjtTcLtw3Cj9G-0)

Acceptance criteria:
- user is able to indicate if mailing address is the same as physical address (checkbox)
- country is selectable from dropdown (set to required)
- street address is text field (set to required)
- apartment or unit number is text field (optional)
- city (set to required)
- state is selectable from dropdown (set to required)
- zip code (set to required)
- address confirmation (with appropriate messaging)
- error messaging where appropriate
- data is prefilled when user is signed in
- use v3 components
- user can go forward or back to previous pages

Build front end of the form using the forms-library

[ ] Using the JSON schema and design mockups, build out the chapters (using other simple forms)
[ ] Using the JSON schema, chapters, and design mockups, build out the pages (using other simple forms)
[ ] Update formConfig with the submitUrl, preSubmitInfo, transformForSubmit, footerContent and getHelp

**Comment by reiting** [comment]
Waiting for review

**Comment by reiting** [comment]
@marywang2 this has been merged!
