### ISSUE TITLE
Create a Journey map

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#74885]
### Issue Description

several inputs will allow the creation of this journey map. The intent is to have a visual where both the Identity team and the application team will clearly understand what the process is to onboard with sign in service as well as understand the current progress that has been made. 

An example/secondary research will have been conducted before this to give an idea of what the final deliverable format may be.

**Comment by kdmeg-bluetiger** [comment]
- @joshmatulonis and I are [reviewing discussions from #vsp-identity to document conversations with other teams](https://docs.google.com/spreadsheets/d/1xYt-aQFEeXcd1EEA764xAd86dmOUN6Iayo8ii2GWL4c/edit?usp=sharing)
- [Started documenting user actions/questions/feelings from dependencies in this slide deck](https://docs.google.com/presentation/d/15_UifBR_aM5cR8sLEFg2SUYDBVymKbRhNjngGnxHMEw/edit?usp=sharing)

**Comment by kdmeg-bluetiger** [comment]
Ran workshop during backlog refinement time block:
- [Figjam file from team brainstorm](https://www.figma.com/file/WZgWwmO7kqz9SENlbzcddX/User-journey-map?type=whiteboard&node-id=1%3A219&t=3IYD280IP5bFg8gs-1)
- [Synthesis](https://docs.google.com/document/d/1pOjG54eNcNEG1HSfWvd7xavzuANom3kXOfIbfnZ5tfc/edit?usp=sharing)
