### ISSUE TITLE
Create an inventory of current solution options

### ISSUE THREAD

**Issue by acaruso-oddball** [department-of-veterans-affairs/va.gov-team#74884]
### Issue Description

Gather current SiS solutions. Resources may be available in github/google docs.

**Comment by kdmeg-bluetiger** [comment]
[Use cases](https://docs.google.com/presentation/d/1qio2zKB3KUV3Akw7gfKBVSgFbLT4LZijJn-2yc5nyTg/edit?usp=sharing) (slides 12-18):

- PKCE: cookie
- PCKE: API
- Private key JWT: cookie
- Private key JWT: API
- Private key JWT: service account

**Comment by bramleyjl** [comment]
Between the slides Megan linked above and the [`auth_flows`](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity/Products/Sign-In%20Service/Engineering%20Docs/auth_flows) section of the developer documents I think we have an inventory of SiS options.
