### ISSUE TITLE
Create list of questions to begin onboarding SiS

### ISSUE THREAD

**Issue by vidjovanovic** [department-of-veterans-affairs/va.gov-team#74882]
### Issue Description

These questions will be loaded into a slackbot

**Comment by kdmeg-bluetiger** [comment]
Hey @bramleyjl - since this ticket is related to [the flow chart diagram](https://github.com/department-of-veterans-affairs/va.gov-team/issues/74886), I'm sharing some relevant details from that work here:

- [Flow chart diagram](https://1787891.fs1.hubspotusercontent-na1.net/hubfs/1787891/Updated%20portfolio%202024/Task%20flow%20diagram%20(updated)%20(2).png)
- [Updates + questions about flow chart questions](https://docs.google.com/presentation/d/1qio2zKB3KUV3Akw7gfKBVSgFbLT4LZijJn-2yc5nyTg/edit?usp=sharing) (slides 19-22)

**Comment by vidjovanovic** [comment]
(From Megan's diagram) These will be used as a jumping off point for questions that will feed into the slackbot to generate an automated form.

SIS Auth questions:
Is the app hosted on vets-api  Is vets-api up to date?
  Will end users interact with your app?  
Is authentication facilitated by a frontend or a secure backend?  	

Frontend -  	
  If PKCE auth flow - Are you familiar with PKCE? 	
  Is your app used in a web browser 	
  Do we use unified sign in page? 	 	 	

Secure backend 	
  If private key JWT auth flow - is your app used in a web browser? 	
  Do we use unified sign in page?

**Comment by kdmeg-bluetiger** [comment]
Hey team! Just flagging the [updates to these initial onboarding questions](https://github.com/department-of-veterans-affairs/va.gov-team/issues/74886#issuecomment-1924457328) that I made last week. Let me know if you want to connect and discuss more!

**Comment by bramleyjl** [comment]
Here's my pseudo-code for the slackbot form, the highlighted text are links to documentation that the bot should return or other bot actions.

```
1. Is the client application hosted on vets-api?
	- Y - 1.a is vets-api up to date?
            * Y - next question
            * N - install vets-api & mock data - `link vets-api & mock data docs`
	- N - update vets-api & mock data - `link vets-api & mock data docs`
2. Do end users interact with the client application?
	- Y - set up client authentication
	- N - Set up service account authentication - `link to service acocunt auth docs`
3. Do you need to use our unified sign-in page
	- Y - set up unified sign-in page - `link to USIP docs`
        - N - next question
4. Is the client app used in a web browser?
	- Y - client is cookie auth - `slackbot notes cookie` 
	- N - client is api auth - `slackbot notes api`
5. is auth facilitated by a frontend or a secure backend?
	- Y - 5.a are you familiar with PKCE auth?
	    * Y - follow PKCE auth - `link [cookie|api guide]`
	    * N - direct to PKCE docs - `link PKCE documentation && [cookie|api] guide`
	- N - follow private key JWT auth - `link [cookie|api] guide`
```

Some questions about the following questions:
1. Is this question asking if the client currently auths through SSOe?
3. Do we have criteria for who needs to use USiP? How do clients know if they need it or not?

**Comment by kdmeg-bluetiger** [comment]
This looks great! To answer your questions:
- @joshmatulonis is reviewing FAQs to see if there are specific steps teams need to take if they're moving from SSOe to SiS. I think we'll have more insights on that after completing the journey map and getting feedback on considerations for that stage.
- The only criteria I know we can use to filter out who needs the USiP or not is whether the client application is used by end users (so client config only). We could add a 1-sentence explanation of what the USiP is and include a link to an example so teams can have a clear picture of it. A question I would have is whether USiP is something we want to _encourage_ more teams to use? And we can frame that question accordingly.

**Comment by dickdavis** [comment]
These questions have been adapted and incorporated into the relevant draft issue in the Github project template.
