### ISSUE TITLE
Deck with step by step of process

### ISSUE THREAD

**Issue by kingbmike** [department-of-veterans-affairs/va.gov-team#74893]

**Comment by kingbmike** [comment]
Need to create a deck that will outline the process step by step.

**Comment by kdmeg-bluetiger** [comment]
Draft of slides: https://docs.google.com/presentation/d/17JuRrXlMTNT1qLfDPLwWcuJKv5_n6wfN0ux6eB0Nsuw/edit?usp=sharing
