### ISSUE TITLE
Conduct IA and content reviews

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#749]
Will follow up to schedule this review appropriately.

**Comment by smoonpeyes** [comment]
I will schedule this with Peggy, Mikki, and myself. We will follow up with Clarice with recommendations.

**Comment by mnorthuis** [comment]
There is no IA feedback for this work.  Functionality is being added to an existing page and no IA changes are needed.

**Comment by lkoenigsberg** [comment]
@peggygannon , can you give a final content review and give us the go/no-go?

**Comment by peggygannon** [comment]
@lkoenigsberg I just gave this a final review on staging and the text notification content looks good. Thank you for checking back in.

**Comment by lkoenigsberg** [comment]
Thanks everyone, closing this ticket and tracking design sign-off in https://github.com/department-of-veterans-affairs/va.gov-team/issues/2331.
