### ISSUE TITLE
Find an example for the journey map

### ISSUE THREAD

**Issue by kdmeg-bluetiger** [department-of-veterans-affairs/va.gov-team#74904]
### Issue Description

Research types of journey maps to identify the best format for the journey may we need to create to fulfill our requirements

**Comment by vidjovanovic** [comment]
Considering we already have Lucidchart, we can continue using that platform to make our Journeymap. I think the best format would be something like [this](https://d2slcw3kip6qmk.cloudfront.net/marketing/blog/updates/customer-journey-map-example.png). From the SiS onboarding organizational board of ideas, we can create create different categories for stages of development.

Ex could be:

1. Plan out requirements
2. Initial Tasking for onboarding
3. Testing and Reviewing solutions

**Comment by vidjovanovic** [comment]
met with @kdmeg-bluetiger and @joshmatulonis and discussed planning for next steps on journey map. We will start listing out tasks on a powerpoint/google doc based on the dependencies on the Journey Map and we will build the final journey map on Figma.
