### ISSUE TITLE
Create document detailing how to add teams to IDD

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#74903]
### Issue Description

Documentation on adding teams and users with roles to Identity Dashboard - github doc

**Comment by dickdavis** [comment]
This document lives here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Products/Identity%20Dashboard/Identity_Dashboard/Managing%20Teams%20and%20Users.md

It serves as documentation for external teams requesting for us to update teams and users in Identity Dashboard. We can provide the wording as part of a slackbot that processes each of these request scenarios.
