### ISSUE TITLE
Create primer/start point

### ISSUE THREAD

**Issue by CaitHawk** [department-of-veterans-affairs/va.gov-team#74901]
### Issue Description

Create primer/start point - github doc (consider check list and video)

**Comment by kdmeg-bluetiger** [comment]
[Draft - WIP](https://docs.google.com/document/d/1zqZfoiebCeW4hvN8BP0ve8iR11LE4sgTwrEhZri1k_M/edit?usp=sharing)

**Comment by kdmeg-bluetiger** [comment]
**Need to finalize hosting/linking:**
- Work with @kingbmike to publish it on platform dev docs site on Identity page
- Publish doc on Github (either wiki or product pages)
- Link to it from Slack channels
