### ISSUE TITLE
Web form Q&A mapping to PDF testing

### ISSUE THREAD

**Issue by buddhima-coforma** [department-of-veterans-affairs/va.gov-team#74919]
## Goal
Ensure frontend questions and answers are mapped to PDF exactly so that all info entered by users make it across as intended to the PDF that's generated. 

We want to be proactive about ensuring there are no data mapping errors, and not wait til manual testing on staging to discover these. This is key for us to launch the form sooner.

## Tasks
- Update existing fixtures and/or create new fixtures to ensure the test data is thorough and accounts for different answers [Vicky, Anh, Scott]
- Periodically run test (daily?) until we get a process going [Anh, Scott]
- Get a process going to support FE and BE alignment: FE PR first -> BE works on PR based on FE PR -> both go through

## AC
- When any changes are made to the form, a check happens to verify that it is in alignment with the PDF
- Minimize form-to-PDF data mapping errors

**Comment by aplatt-coforma** [comment]
Matt is leading a discussion with devs on this topic on Monday and will create/created tickets for a boarder e2e effort. 
One already created is #72423 

Closing this ticket for now.
