### ISSUE TITLE
Create Zenhub design issue templates

### ISSUE THREAD

**Issue by williamphelps13** [department-of-veterans-affairs/va.gov-team#74915]
### Description
In order to expedite Zenhub design issue creation and to encourage consistency we need Zenhub design issue templates.

### Acceptance Criteria
  - [x] [Research Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/arf-des-research-issue.md) - can test in Zenhub Templates dropdown
  - [x] [Design Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/arf-des-design-issue.md) - can test in Zenhub Templates dropdown
  - [x] [Epic Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/arf-epic.md) - can test in Zenhub Templates dropdown
  - [x] Call out this Zenhub issue template capability in one of our team's practice documents - created /accredited-representative-facing/process/design-agreements.md and added a [Zenhub section ](https://github.com/department-of-veterans-affairs/va.gov-team/pull/75257/files)

**Comment by RivkaCGates** [comment]
@williamphelps13 did one of the designers sign off that this looks right? Otherwise I can and I'll close it.
