### ISSUE TITLE
Design | Create Burial Change Log for VBA

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#74929]
## Issue Description
_To help communicate form changes and gather feedback from the VBA, we need to create and post a design change log on VA SharePoint. This will allow VBA and OCTO stakeholders to see the specific change and provide feedback in a organized space._

These files need to be accessed from within Azure/Citrix:
- [Burial Sharepoint Folder for change log](https://dvagov.sharepoint.com/:f:/r/sites/vaabdvro/Shared%20Documents/Non-disability%20Benefits/Burial?csf=1&web=1&e=Z4LDJE)
- [Pension Sharepoint Folder (with examples)](https://dvagov.sharepoint.com/:f:/s/vaabdvro/ErQsGqy8_BFGsZD8WFpZKwABrkNHDwXAtZ4iju4BIaMSUw)

---
## Tasks
- [ ] Create design change log and upload to VA Sharepoint

## Acceptance Criteria
- [ ] Burial design change log
---

**Comment by fiorella-io** [comment]
I was finally able to get to VA! So the Pension doc looks like they labeled the steps and added screenshots for each. There is no additional content explaining what has changed. I can follow this template once I get a confirmation that all our changes have been from either @Midge-dev or @DLarson-Oddball and I can get a link to Github. I know we don't have a staging environment for Burial, so I'll work with them to get the screenshots and I'll add them to Sharepoint and share them with our SMEs

**Comment by fiorella-io** [comment]
I lost my temporary access. I only had it for 2 days. I'm not sure I can post these screenshots when they are ready until my new account gets created and my new PIV card get's issues and arrives.
