### ISSUE TITLE
[FE] Profile mailing address handles international addresses poorly

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#7493]
There seems to be three different bugs when working with international addresses in the Profile.

This ticket is for issue #1 below

1. The address validation modal shows only the street address(es) as the entered address; it fails to show the city, province, postal code, or country that the user entered. ( This ticket)

2. The address does not properly persist in VAProfile. The province does not come back on the `GET user` payload. This is either an issue with how our API talks to VAProfile or an issue with VAProfile itself. - [this work is on ticket #7524](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7524)

3. The profile fails to show the international postal code for an international address. - [this work is on ticket #7525](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7525)

Steps to reproduce:

1. Enter the following address: `building #402, APO, AP, 96343, Japan`
2. That sends the following payload to `address_validation` and gets the following response:
```
sent:
{
  "address": {
    "id": 104273,
    "addressLine1": "building #402",
    "addressType": "INTERNATIONAL",
    "city": "APO",
    "countryName": "Japan",
    "internationalPostalCode": "96343",
    "province": "AP",
    "addressPou": "CORRESPONDENCE",
    "countryCodeIso3": "JPN"
  }
}
response:
{
  "addresses": [
    {
      "address": {
        "addressLine1": "Building # 402",
        "addressType": "INTERNATIONAL",
        "countryName": "Japan",
        "countryCodeIso3": "JPN"
      },
      "addressMetaData": {
        "confidenceScore": 0.0,
        "addressType": "International"
      }
    }
  ],
  "validationKey": -2045670811
}
```
But **BUG 1:** the address validation modal shows the entered address as simply `building #402`
![image.png](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/e6017b14-2e2f-480a-87ab-3213f447c610)

3. Click `Use this address` button to save. That sends the following correct data to `PUT addresses`:
```
{
  "id": 104273,
  "addressLine1": "building #402",
  "addressType": "INTERNATIONAL",
  "city": "APO",
  "countryName": "Japan",
  "internationalPostalCode": "96343",
  "province": "AP",
  "addressPou": "CORRESPONDENCE",
  "countryCodeIso3": "JPN",
  "validationKey": -2045670811
}
```
And it saves. But **BUG 2** is that the following call to `GET user` shows that the saved address is not entirely correct, as it’s _missing the province_, which should be `AP`:
```
"mailingAddress": {
  "addressLine1": "building #402",
  "addressLine2": null,
  "addressLine3": null,
  "addressPou": "CORRESPONDENCE",
  "addressType": "INTERNATIONAL",
  "city": "APO",
  "countryName": "Japan",
  "countryCodeIso2": "JP",
  "countryCodeIso3": "JPN",
  "countryCodeFips": null,
  "countyCode": null,
  "countyName": null,
  "createdAt": "2019-10-04T17:52:48.000Z",
  "effectiveEndDate": null,
  "effectiveStartDate": "2020-04-01T16:37:06.000Z",
  "id": 104273,
  "internationalPostalCode": "96343",
  "province": null,
  "sourceDate": "2020-04-01T16:37:06.000Z",
  "sourceSystemUser": null,
  "stateCode": null,
  "transactionId": "450327be-0caf-4589-bede-a3d56122b7da",
  "updatedAt": "2020-04-01T16:37:13.000Z",
  "validationKey": null,
  "vet360Id": "139281",
  "zipCode": null,
  "zipCodeSuffix": null
},
```
4. And finally what shows up in the Profile under Mailing address is: `building #402, APO, Japan`. So **BUG 3** is the fact that the profile doesn’t show the international postal code.
![image.png](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/ac27d5e9-711a-4cbb-9153-1f6d0b9623ad)

**Comment by erikphansen** [comment]
@Samara-Strauss @mshea0606 I found these issues when messing with updating mailing addresses, trying to get a save failure since we are seeing so many mailing address save failures in Google Analytics. I couldn't make an update fail but found these other bugs instead.

**Comment by sanlouise** [comment]
@mshea0606  Can you please validate this ticket? Thank you!
