### ISSUE TITLE
AWS access for Rachel Eiting

### ISSUE THREAD

**Issue by reiting** [department-of-veterans-affairs/va.gov-team#74948]
### COR Name

Eunice Garcia

### Vendor Onboarding Representative Name

Agile Six - Anthony M. Arashiro

### Your Name

Rachel Eiting

### Your Email

rachel.eiting@copilot.llc

### Team, Role, and Company of the target individual

IVC Forms (CHAMPVA), Frontend Engineer, Copilot

### Product Manager (PM) name and email

Bo Altes, bo.altes@agile6.com

### Product Owner (PO) name and email

Premal Shah, premal.shah@va.gov

### Desired AWS Access

The IVC Form team will be pushing the digitized forms to a S3 service. Bucket TBD but we all need accounts in AWS before we can be granted access to any bucket

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

![Screenshot 2024-01-30 at 2 36 33 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/20195737/fc433882-739a-410e-9d31-bf32c96c43ba)

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [x] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by barbarello** [comment]
user is in Atlas

**Comment by barbarello** [comment]
user's e-qip transmittal notice is valid

**Comment by barbarello** [comment]
Access granted and temporary credentials passed to user
