### ISSUE TITLE
[Design] - 1010d Prototype for usability testing [Part 2 w/ file upload]

### ISSUE THREAD

**Issue by jamiefiore** [department-of-veterans-affairs/va.gov-team#74945]
### **Description**
Using the prototype handed off to engineering from [Prototype for usability testing #71769](https://github.com/department-of-veterans-affairs/va.gov-team/issues/71769), and research plan from [1010d User interview research plan](https://github.com/department-of-veterans-affairs/va.gov-team/issues/71445) create clickable prototype for 1010d form.

Acceptance criteria:
- end to end user flow is mapped out in VA figma
- form 10-10d content only
- show unauthenticated and authenticated paths(?)
- error states and conditional states noted
- leverage design system and existing patterns
- follows accessibility standards
- intended to meet needs for research review, also needed for [midpoint review ](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)

The prototype should identify:
- [ ] Standard patterns and components
- [ ] New patterns and flows
- [ ] Complicated patterns and flows
- [ ] Updated with file upload and current list and loop pattern

### **Definition of Done**
- [ ] Clickable mobile prototype (if applicable to test)
- [ ] Design review
- [ ] Accessibilty review
- [ ] Dev review

### **Assumptions**
- Using the file upload and list and loop patterns will allow applicants to easily submit each applicant's info and supporting docs 
- By supporting file upload processing times for the 1010d enrollments with decrease

### **Unknowns**
- How might we clearly identify and ease the burden of adding additional applicants with their individual required document. 

Dependency: 
- Figma access

**Comment by syd-hoeper** [comment]
Ready for handoff Figma file: [https://www.figma.com/file/LWfLUckNkxEz3fxXsxde93/10-10d---%5BDoc-Uploads%5D-Updates?type=design&node-id=127-88123&mode=design&t=FwnIcsW4ih2vytJ3-11](https://www.figma.com/file/LWfLUckNkxEz3fxXsxde93/10-10d---%5BDoc-Uploads%5D-Updates?type=design&node-id=127-88123&mode=design&t=FwnIcsW4ih2vytJ3-11)
