### ISSUE TITLE
[BE] 10-10EZR: Add TERA questions to EZR API--SEND (V1)

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#74953]
As a Veteran, I would like to be able to update the toxic situations I was exposed to so that I make sure I get the healthcare I need and have earned.

- [ ]  Work with VES sustainment team to determine their schema and requirements for TERA Questions for EZR (Alex and Emily can help facilitate) 
- [ ] Add "TERA Flag" for whether or not Veteran has TERA information to share (use EZ as a model)
- [x] Make sure EZR can **Send** the following Yes/No fields to VES and VES can receive them in the same way they're receiving EZ for the 3/5 launch:
1. DID YOU SERVE IN AN IONIZING RADIATION LOCATION AND PARTICIPATE IN ANY NUCLEAR TESTING, TREATMENTS, OR CLEAN UP? Y/N
2. DID YOU SERVE IN ANY OF THE FOLLOWING GULF WAR HAZARD LOCATIONS? Y/N
3. DID YOU SERVE IN ANY OF THE FOLLOWING HERBICIDE (e.g. Agent Orange) LOCATIONS? Y/N
- [ ] Use API to send data for the question  "HAVE YOU BEEN EXPOSED TO ANY OF THE FOLLOWING? (Check all that
apply)" and allow them to select multiple answers (including an "Other" with a blank text field) 
- [x] Send the following checked or not check responses to VES
1.ASBESTOS 
2. MUSTARD GAS
3. RADIATION 
4. SHAD (Shipboard Hazard and Defense)
5. MILITARY OCCUPATIONAL SPECIALTY (MOS) RELATED TOXIN
6. CONTAMINATED WATER AT CAMP LEJEUNE
7. Other (with blank text field)
8. From: To: date fields
- [ ] Send up to 100 character in the "other" text box (double check this number with EZ Devs and VES team) to VES
- [ ] Use API to send data for the question: "IF YOU WERE EXPOSED MULTIPLE TIMES, PLEASE PROVIDE ALL
ADDITIONAL DATES" question with only one "Location" fields and From/To date fields (mm/yyyy) (vets-api currently only supports one per comment below and [Slack Thread](https://dsva.slack.com/archives/C05Q6411HPF/p1710369502612459))
- [x] Test sending VES the data and make sure they can consume it 
- [x] **Success: EZR can Send all of the information for the new TERA questions**

[VA Form 10-10EZR (8).pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemVaQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--731ab8d9521c5a5e81c1913683c15b01905b693f/VA%20Form%2010-10EZR%20%288%29.pdf)
[TERA Designs](https://www.figma.com/file/tggcJk382w9yQ0ElwKfh3N/10-10EZR?type=design&mode=design)

**Comment by lihanli** [comment]
"Use API to send data for the question: "IF YOU WERE EXPOSED MULTIPLE TIMES, PLEASE PROVIDE ALL
ADDITIONAL DATES" question with multiple entries that include a "Location" fields and From/To date fields (mm/yyyy)" this isn't in the 1010EZ and the VES api doesn't support this question

**Comment by emily-brown34** [comment]
only one date will be provided, ability to enter multiple dates is NOT part of the expected functionality
