### ISSUE TITLE
As a 10-10D applicant, I need a button that lets me attach a file and see the file details

### ISSUE THREAD

**Issue by michaelclement** [department-of-veterans-affairs/va.gov-team#74954]
Users need to be able to upload supporting documents when they fill out 10-10D. Since we don't have a backend for this, we need a stopgap button that lets the user "upload" without errors but doesn't actually rely on a backend (i.e., the file does not get saved). 

This will allow researchers to run tests of the form flow despite the upload functionality not being fully implemented yet. The button should look and function like the real thing insofar as UI is concerned, but should not rely on a backend at all.

Acceptance Criteria

- [x] User can click an upload file button
- [x] File dialog opens and accepts a file from user's local computer
- [x] File is "uploaded" and displays in web UI with option to delete

**Comment by michaelclement** [comment]
@baltes I went ahead and added this ticket - please let me know if it needs to be adjusted

**Comment by michaelclement** [comment]
I've identified the areas that need to be adjusted to make the existing file component fail silently. This will let users go through the motions of an upload without the backend needing to accept anything. 

Main focus for today is digging deeper and figuring out a straightforward way to override the existing behavior without having to add a bunch of duplicate code or breaking any legitimate upload buttons that share these parts.

**Comment by baltes** [comment]
@michaelclement Looks great, thanks!

**Comment by michaelclement** [comment]
I've got a file upload that meets the acceptance criteria [branch here](https://github.com/department-of-veterans-affairs/vets-website/tree/74954-custom-file-upload-form-10-10D). 

I've pushed to Github, but I'm going to hold off on making a PR for this one until I've gotten the other sections of the form up to speed with the latest mockups (since we don't actually have a mockup for what file upload interface should look like yet).

**Comment by michaelclement** [comment]
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOW9aQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--17c4f369b512cd8eabef0b72fad04f362589f1db/file_upload.mov)

**Comment by michaelclement** [comment]
Waiting on internal review, then platform and this will be able to go to staging. It's not in use within the form, but the component is available. This will go in play when we have the next round of mockups for 1010d that actually contain file uploads.
