### ISSUE TITLE
Create write up of every manual action taken during an accessibility audit

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#7496]
Tasks: 
Create write-up
Readout with Andrea
Send write up to everyone involved in discovery two days before we meet
Schedule meeting with dev leads to go over (TJ, Wyatt, Alex, BE??, Brandon, Rian, Trevor, Andrea, Travis)

**Comment by 1Copenut** [comment]
@andreahewitt-odd Document has been updated per feedback from our Slack DM today: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/testing/508-manual-testing.md

**Comment by 1Copenut** [comment]
@andreahewitt-odd I'm going to move this one to close as we've got the manual work captured, and are onto the design system audit.
