### ISSUE TITLE
EVSS PCIU Migration: Write/use service class to call VA Profile

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#74974]
## Issue Description

Replace calls to the PCIU (Personnel and Casualty Information Update) service with the VAProfile service. The PCIU service is being deprecated or replaced by the VAProfile service, necessitating the migration of existing functionality to ensure continued access to personnel and casualty information within our system. This migration is crucial for maintaining seamless integration with VAProfile and ensuring uninterrupted service for users.

---
## Tasks
- [ ] Write/use service class to call VA Profile

**Comment by RachalCassity** [comment]
This will be handled by the Benefits team. This can be closed.

**Comment by jennb33** [comment]
Platform Product will not be performing any work on this ticket, so closing it.
