### ISSUE TITLE
EVSS PCIU Migration: Testing on a review instance

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#74977]
## Issue Description
Test the functionality and reliability of VAProfile calls on review instances. As part of the development process, it is imperative to ensure that the integration between the VAProfile system and review instances is working seamlessly, allowing for thorough testing and validation before deployment to production environments.

---
## Tasks
- [ ] Testing on a review instance

## Acceptance Criteria
- [ ] TBD
---
## How to configure this issue
- [ ] EVSS PCIU Migration: Remove calls to PCIU in global Pre-fill
- [ ] Product Support
- [ ] backend, devops
- [ ] request

**Comment by RachalCassity** [comment]
This will be handled by the Benefits team. This can be closed.
