### ISSUE TITLE
SOCKS access for Matthew Wright, VA.gov - Medical Records

### ISSUE THREAD

**Issue by mattwrightva** [department-of-veterans-affairs/va.gov-team#74984]
### Your Name

Matthew Wright

### Your Email

matthew.wright8@va.gov

### Your Role and Team

Front-End Developer, VA.gov Medical Records

### Product Manager (PM) name and email

Lichelle Bain - lichelle.bain@va.gov

### Product Owner (PO) name and email

Patricia Henry - Patricia.Henry@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCdLHRnMIwaW/1IJROt3PS3Da0tq0JzeI0sDOfdb8x2sQkHvE80Om0/AzJuvQQB1Q6FdHKBLwfFfSu7VxnDoTkyMJ+5FiQoYBDrUTnQ7ZCP70lzhXWsiOgrcnPY9ZgkGPmETkhZpiq5VfEz9wvCvxfMXhBLKPCSYjNh6KGYylnYuypvmpomGw5YYRG5oafHLHM2VgOrTfiAu1UgkIxM+aABjB4kXHGUZtnh5c8rYGsiKHl2Y8rG6nkLzULSZxFHuyXMrb/9hNzRjMPOQIWN32nZoRZGKGGMsi+3SAotYUeIIAmSKnLJbPS+074yEodT7tkA9N+RnbSNke2d4ywJiDd++f4bzs39BfhR6AT/BdSq5XX4TOkUTHmXEcIDhSyqHyY6XHoMSJRaP0hNcm/0/8ObV+DuuazrwaJr3hYfVpkPSD4kgKUmDhfnf9fYugcKnqL2RnjZvIrxRVlDFdjszLI1Xoh1AeXtFdYcX2wb1e3lIaHBxAkWy6t8W3cqpbPT2CU= matthewwright@matts-m1-mbp.lan

### E-QIP Transmittal Confirmation

<img width="1418" alt="Screenshot 2024-01-30 at 2 54 52 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/107576133/b0a79a0b-6f13-4bc3-8be8-77ca4216084f">

### User must exist in a roster before SOCKS access can be granted

- [x] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by barbarello** [comment]
user in Atlas 
Transmittal notice is valid

**Comment by barbarello** [comment]
@mattwrightva Access granted ✅ 

Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html 

Reach out in #vfs-platform-support if you have any trouble.
