### ISSUE TITLE
EVSS PCIU Migration: Update test suite

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#74982]
## Issue Description
Update tests.

---
## Tasks
- [ ] Update test suite

## Acceptance Criteria
- [ ] TBD
---
## How to configure this issue
- [ ] EVSS PCIU Migration: Remove calls to PCIU in global Pre-fill
- [ ] Product Support
- [ ] backend, devops
- [ ] request

**Comment by RachalCassity** [comment]
This can be closed.
