### ISSUE TITLE
Draft final secondary nav design

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#74998]
### User story

As a Cartographers team member, I want to draft the final secondary nav design, so that we can seek stakeholder feedback and buy-in.

### Notes
- Design against the new federal header that has been in usability testing the past few weeks

Possible tasks:
- [ ] review Liz Lantz's research findings from federal header w.r.t. authenticated menu/tasks
- [ ] collaborate directly with Amanda Klausmeier about anticipated final federal header design
- [ ] scheduled research read-out to OCTO stakeholders
- [ ] ~scheduled research read-out to non-OCTO stakeholders~
- [ ] Look to Kaitlin for guidance on how to address non-octo stakeholders, how granular

Assumptions:
- Actual stakeholder meetings and feedback loops will happen under a follow-up story
- We will use the weekly Wednesday "UX" meeting for OCC stakholders

## Acceptance criteria

- Designed proposed secondary nav design in Figma under the new federal header
- Iterated with Kaitlin feedback
- Scheduled review meeting for OCTO

**Comment by wesrowe** [comment]
refinement discussion: Will likely remove story from sprint 24:
- urgency of this was much reduced by shifts after sprint planning (Ph 1 integration postponed to October-ish)
- research synthesis effort was significantly underestimated
- design sprint is a higher priority now

**Comment by fmccaf1** [comment]
@wesrowe, would it be okay for me to get through a couple ACs here? I feel like I have capacity to do it (now that I won't be working on design sprint for a day and a half

**Comment by wesrowe** [comment]
ended up duplicating this in the integration rush. closing.
