### ISSUE TITLE
Waivers - Benefit applications - design.va.gov documentation 

### ISSUE THREAD

**Issue by jaredcunha-usds** [department-of-veterans-affairs/va.gov-team#75]
This is a macro-level description of the Waivers section of Benefit applications.

Here are some points. These bullet points are not in any particular order.
- Tend to be later in the flow (before review)
- Tends to have a lot of legal copy. Can be a static content page on VA.gov that we link to. We will have a tl;dr version on the actual application page.
- One question at a time.

You may submit your write-up as a comment on this issue. Happy to help if you have any questions.

**Comment by smoonpeyes** [comment]
@jaredcunha-usds Is the waiver the "Accept Terms and Conditions" checkbox on the benefits application form?

**Comment by jaredcunha-usds** [comment]
@smoonpeyes I don't quite remember exactly. @lalexanderson-dsva or @goldenmeanie do you happen to know?

**Comment by goldenmeanie** [comment]
Waivers refers to screens at the end of the form, but prior to submission that follow that “terms and conditions” pattern. Examples:
- FDC claim in Pension and Comp
- Pay waiver (retirement or comp) in Comp

**Comment by caw310** [comment]
Closing as this is over 3 yrs old.
