### ISSUE TITLE
Does Medicaid cover...costs? is not mapped correctly in PDF

### ISSUE THREAD

**Issue by aplatt-coforma** [department-of-veterans-affairs/va.gov-team#75003]
Steps:

1. Start a new Pension application
2. Enter minimal data until you get to the question Do you live in a nursing home?" 
3. Select YES
4. For the next question, "Does Medicaid cover all or part of your nursing home costs?"
5. Select NO
6. continue with minimal data
7. Submit the form and inspect the generated PDF

Results: In the PDF, for the question "Does Medicaid cover all or part of your nursing home costs?", YES is selected
Expected: In the PDF, NO should be selected.

<img width="1694" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMllVQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7b41c0591f44aedc00377b0422da8b15e116be27/Does%20Medicaid%20cover%20all%20or%20part%20of%20your%20nursing%20home%20cost%3F.png" alt="Does Medicaid cover all or part of your nursing home cost?.png" />

**Comment by vbellissimo** [comment]
@aplatt-coforma can you share the PDF screenshot of your web form entry?

Because if you...

- answered "yes" to "Does Medicaid cover all or part of your nursing home costs?"... AND
- answered "yes" to "Have you applied for Medicaid?" (next question after above)

on your test, then it mapped correctly on the PDF you're showing.

**Comment by aplatt-coforma** [comment]
@vbellissimo - You are correct, the next question,  Have you applied for Medicaid?, does map to a YES.
<img width="1570" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFlYQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--191195adf0e1a8cea053ca4620d948f0aa499733/Screenshot%202024-01-31%20at%206.41.35%E2%80%AFAM.png" alt="Screenshot 2024-01-31 at 6.41.35 AM.png" />

I will close then since it sounds like these are expected mappings. Thanks!
