### ISSUE TITLE
X509 Certificate for CARMA

### ISSUE THREAD

**Issue by tskinn** [department-of-veterans-affairs/va.gov-team#7501]
**Description**
Create a X509 Certificate for dev, staging, and production and provide to CARMA. The corresponding private key (for each cert/env) should be accessible by vets-API to generate and sign JWT tokens that CARMA will be verifying with the cert.

**Context**
CARMA is a Salesforce App used the VA's Caregiver Program to manage the processing of caregivers' assistance claims (VA form 10-10cg). Vets-API will be creating a connection to CARMA to allow users to digitally submit a 10-10cg form. Vets-API will take the end-users submission and send it to CARMA for processing.

CARMA accepts JWT bearer flow for authenticating. In Vets-API, we will generate and sign a token with a private key, POST the token to `{carma_uri}/services/oauth2/token`. CARMA will verify the token with a corresponding cert/public key.

We'll use the access token provided in the auth flow to submit forms to `{carma_uri}/services/apexrest/carma/v1/1010-cg-submissions`.

**Related Work**
https://github.com/department-of-veterans-affairs/vets-api/pull/3899

**Comment by tskinn** [comment]
This is a copy of https://github.com/department-of-veterans-affairs/devops/issues/6551

**Comment by kevinmirc** [comment]
Regarding timeline/urgency: CARMA has this feature scheduled to be released on April 10. By April 10, this would become a blocker for their release and would either delay it or have to implement a temporary workaround.

**Comment by kevinmirc** [comment]
No that is all. Looks good. Thank you @tskinn!
