### ISSUE TITLE
[bug] Error handling for file upload names that are too long

### ISSUE THREAD

**Issue by anniebtran** [department-of-veterans-affairs/va.gov-team#75029]
## What happened?

This is a follow up to https://github.com/department-of-veterans-affairs/va.gov-team/issues/70856

We encountered a veteran who uploaded an evidence file with an extremely long file name that exceeded the limit for a tempfile we set up on the backend as a part of the upload process. This ticket is representing the dev work to more elegantly handle the error and surface it to the veteran so they can properly upload their evidence

## What do we need to know?
What approach we want to take and what the error should look like when it's presented to the veteran

## Action items
- [ ] Determine what the error message should be
- [ ] Add error handling on the backend and/or frontend

## Slack threads and background context
See https://github.com/department-of-veterans-affairs/va.gov-team/issues/70856

## Definition of done
- [ ] Action items above are completed

**Comment by saderagsdale** [comment]
- Need to know max name length (@rocio-desantiago)
- Need error messaging consideration (@eileen-coforma )

**Comment by rubensun** [comment]
> Individual components of a filename (i.e. each subdirectory along the path, and the final filename) are **_limited to 255 characters_**, and the total path length is limited to approximately 32,000 characters.


https://stackoverflow.com/a/265782

**Comment by eileen-coforma** [comment]
I'm suggesting the following error message:
`Your file name can't exceed [#] characters. Rename your file and try again.`

And asking CAIA for feedback in this [thread](https://dsva.slack.com/archives/C01K37HRUAH/p1706800989022379?thread_ts=1706627044.030149&cid=C01K37HRUAH), since Julie is out for the week.

If we don't get a response by Tuesday, I'll attend CAIA OH and ping Julie to move this forward.

**Comment by rocio-desantiago** [comment]
Just noticed Ruben may have already answered the question.
file name: 255 characters
file path name: 32,000 characters

**Comment by HeatherWidmont** [comment]
@eileen-coforma is talking to Julie later today about this

**Comment by eileen-coforma** [comment]
CAIA needs a few days to look at this. Will follow-up with them on Friday.

**Comment by eileen-coforma** [comment]
@rocio-desantiago 
Error message approved by CAIA:
`Your file name can’t be longer than 255 characters. Rename your file and try again.`

**Comment by data-doge** [comment]
Downgrading to moderate. We've only ever seen one instance of this error, and have followed up with the one impacted Veteran.

**Comment by saderagsdale** [comment]
Deferring until after NOD testing is complete. We need all hands on deck, and this sits lower in priority.

**Comment by Mottie** [comment]
This work is available in staging, but we don't have a test file with over 255 characters in the file name to test it. What should we do with this ticket then?
