### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by CarlDickerson** [department-of-veterans-affairs/va.gov-team#75021]
### Name

Carl Dickerson

### Email

carl.dickerson@va.gov

### Role

Designer

### Team

Secure Sign-in Transition (Formerly Login.gov Adoption)

### Product Manager (PM) name

Lauren Morris

**Comment by naomimarcussen** [comment]
Hi! An invite has been sent to carl.dickerson@va.gov. Reply here once you're created an account and I'll give you full access.

**Comment by CarlDickerson** [comment]
Hi Naomi,

Replying to let you know that I've created a Figma account.
________________________________
From: Naomi Marcussen ***@***.***>
Sent: Wednesday, January 31, 2024 12:48 PM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Dickerson, Carl D. (Magnus Opus dba The MO studio) ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Figma access request (Issue #75021)


Hi! An invite has been sent to ***@***.******@***.***>. Reply here once you're created an account and I'll give you full access.

**Comment by naomimarcussen** [comment]
Thanks! You now have full access to Figma!
