### ISSUE TITLE
Update copy on Confirmation page about mailing documents

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#75030]
## Issue Description

---
## Acceptance Criteria

- [ ] Update "note" copy on confirmation page to:
-

**Comment by vbellissimo** [comment]
@katherine-fung can you help us update the copy in the "note" section of the confirmation page? VBA stakeholders comments from our Teams chat:

_The 527EZ recommends that the Claimant "make a photocopy of all supporting material you submit BEFORE mailing it to the VA", whereas the confirmation page does not state this in the "note" piece. To avoid confusion, let's align the verbiage to somewhat match (possibly just adding "We recommend/please make a photocopy of all supporting material you have uploaded before mailing to the VA")._

_As far as the note about mailing in supporting material, I like the original note (since the Claimant will be submitting their 527EZ electronically, no need to photocopy it), therefore, if we can just add to the note already there:
"For your own records, we recommend you make a photocopy of the supporting documents you are submitting to the VA before mailing them in."_

**Comment by katherine-fung** [comment]
@vbellissimo - Here's the copy for the note: 

> **Note:** Don’t send us your original documents. We can’t return them. Send us copies of your documents only.
> 
> If we asked you to complete and submit additional forms, be sure to make copies of the forms for your records before you mail them to us.

We also provide mailing instructions on the "Submit your supporting documents" screen, so we'll need to include the note there too, and make some minor tweaks to specify "copies." 

<img width="483" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODBlQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6d496b17dc068e391e2e8d839fa15f9577260f12/staging.va.gov_pension_application_527EZ_additional-information_document-upload.png" alt="staging.va.gov_pension_application_527EZ_additional-information_document-upload.png" />

**Comment by vbellissimo** [comment]
Closing this, as it duplicates #74150
