### ISSUE TITLE
Update Confirmation page mailing address

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#75038]
## Issue Description

<img width="525" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDhZQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--459f6b12fb6b93ef5b4519037a782d29e12919c0/ConfirmationPageAddress.png" alt="ConfirmationPageAddress.png" />

---
## Acceptance Criteria
- [ ] Update mailing address on confirmation page to:

`Department of Veteran Affairs`
`Pension Intake Center`
`P.O. Box 5365`
`Janesville, Wisconsin 53547-5365`

**Comment by TaiWilkin** [comment]
@vbellissimo The current address is returned from `vets-api`, and which address is displayed depends on the location of the veteran (returning their closest regional office, either Milwaukee, St. Paul, or Philadelphia). Do we want to replace this with a static address, which always returns the `P.O. Box 5365` address?

**Comment by vbellissimo** [comment]
@katherine-fung @jstrothman , can you take a look at Tai's message above? Is this something that we're comfortable removing altogether to replace with the address provided by the VBA?

**Comment by katherine-fung** [comment]
Hi @TaiWilkin, 

Yes, we should replace with a static address that always returns the P.O. Box 5365 address. 

VA now tells applicants for all pension benefits to send their materials to that one address (https://www.va.gov/pension/pension-management-centers/). 

Thank you!! cc @vbellissimo @jstrothman

**Comment by vbellissimo** [comment]
Thanks, @katherine-fung . and just to be clear, this will be a fast-follow update. There is [another ticket on our radar](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/gh/department-of-veterans-affairs/va.gov-team/74150) that will come after this to further update the confirmation page, based on your recommendations. Thank you.

**Comment by aplatt-coforma** [comment]
Confirmation address has been updated.
<img width="572" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVpKQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ce845e6f167a5a3b108b81c3201f11dc7ae29bfa/Screenshot%202024-02-09%20at%201.43.27%E2%80%AFPM.png" alt="Screenshot 2024-02-09 at 1.43.27 PM.png" />
