### ISSUE TITLE
Draft 404 findings and recommendation for feedback

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#75049]
### User story

As a Veteran, I want all pages to alert me with a 404 page not found error when I have a bad url, so that I never get an inaccessible blank screen.

### Notes
- Carlos discovered that the existing 404 page mostly/only displays for static content; when routing happens inside of an application, he barely found any 404 implementations.

Possible tasks:
- Broadcast the issue in all-team channels, e.g. team of teams, vfs-all-teams on slack, etc
- desirable outcome: documentation in developer docs for application creation (see scrollsite docs about how to request to update docs)

## Acceptance criteria

- Document the circumstances where 404s are being missed, with a section for non-tech audiences before the technical details begin (if appropriate)
- Get feedback from Patrick on approach and how to spread word, build alignment, etc.

**Comment by carlosfelix2** [comment]
Documented the 404 issue and recommendation is this Slack Canvas: https://dsva.slack.com/docs/T03FECE8V/F06G3J52NJE

**Comment by carlosfelix2** [comment]
Agreed on a proposed approach proposed by Patrick to incrementally spread the word.
1. Make the change for the MHV landing page only and include the new shared component.
2. Reach out to other my-health app teams and ask for us to make changes to their app. If those teams prefer to make the changes then share the doc.
3. Reach out to Platform after the other my-health apps are updated, show them the output, and get direction on how to best communicate the need for change to other teams.

**Comment by wesrowe** [comment]
This can definitely close. If we decide to implement for other health teams, I'll write a ticket for it later.

Note for future reference: Carlos already implemented the 404 for the landing page.
