### ISSUE TITLE
S46 [Sunshine 🌞]

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#75069]
### Delivery
- Test the end-to-end submission flow for NOD V2 to confirm that validation for positive and negative test cases work as expected. 
     - #73652
     - #75043
- Make it easier for Veterans to submit PDF evidence.
     - #74457 
     - #75029 
     - #74493
     - #74503
- Setup a callback url that utilizes a long-lived bearer token.
     - #74832 
     - #65509
- Make it easier for developers to diagnose and take action on validation errors.
     - #74946 
     - #72855
     - #70586

### Discovery
- Complete research sessions for the “Accessible Appeal Download” feature
     - #73587
- Opportunity prioritization workshops
     - #75073

---

## Team Capacity
- Velocity average (past three sprints): 13
- Target velocity: 22

**PTO:**
- Eileen (2/2-5)
- Annie (2/9)
- Rocio (2/9)

## Sprint Risks and Assumptions
- Aiming to have NOD V2 released by or before 2/13

## Reference documentation

- [High-level Roadmap](https://docs.google.com/presentation/d/18rYnaYCjp2L2cm8HdYmXsg1_Pz7KI_X0vNRkmT5AqEk/edit#slide=id.g2804f61cf5f_0_0)
- [Tactical Roadmap (WIP)](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1702419283589/39d0d78778b8a35a2a02b48496d665d86ec3c5a2?sender=ud80be02ce240061eb0f35352)
- [Planning and Prioritization Board](https://github.com/orgs/department-of-veterans-affairs/projects/1026/views/1?filterQuery=)
- [Defect Board](https://github.com/orgs/department-of-veterans-affairs/projects/876/views/1?visibleFields=%5B%22Title%22%2C%22Assignees%22%2C46447480%2C46447511%2C46447563%2C%22Labels%22%5D)
- [Story Estimator](https://docs.google.com/spreadsheets/d/1ae9fpz_ThZycIWjmBBMSEuGRGqsvRSz3/edit#gid=1440877167)
- [Velocity Planner ](https://docs.google.com/spreadsheets/d/1i7pVgf2XQxuRkIbuhHC5dckx2RlZt87n/edit#gid=880321098)

**Comment by HeatherWidmont** [comment]
Met with @data-doge to review velocity today & we identified where there were a couple discrepancies between the planning board & the tickets themselves. I updated last sprint's velocity to 17 which in turn bumps the average of the last 3 sprints up from 12 to 13. I edited this issue to reflect that change 😄 

cc @saderagsdale
