### ISSUE TITLE
[Discovery] Set up Sentry teams

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#7506]
## Background

The backend tools team would like to shore up the usage of [teams](http://sentry.vfs.va.gov/settings/vets-gov/teams/) feature in Sentry. We also would like to investigate options for integration with GitHub and Slack and determine where this might be worth further effort. These integrations can provide a more robust and delightful experience/self-service workflow for both VSP and VFS teams to discover and monitor application errors.

Potential integrations include:

- commit-based error linking (when did this error start happening, by commit)
- automatic Sentry-issue assignment to Sentry-user & team by rules
- suggested GitHub user linking based on code 

## Goal

The backend tools team has a clear pathway and set of issues documented for completing Sentry team cleanup and possible integrations.

## Acceptance Criteria

- [x] Document the specific Sentry settings/configuration values that need updating
- [x] Understand and document the source of truth for VFS & VSP team delegations 
- [x] Understand and document the source of truth for feature/code ownership
- [x] Plan a trial run with an existing VFS team

**Comment by kfrz** [comment]
From @LindseySaari (original issue body text)

### **Notes from 4/1/2020 meeting**
- Setting up teams, what would this look like? Assignment based on code, etc
- How to auto assign?
- What teams own what code?
- How do we break out what teams own for example a directory or specific sections of code?
- Setting up a lighthouse team.. setting us up and activating it

### **First thoughts on Steps for Sentry Teams**
1. Break out teams -- Use existing docs below
2. Figure out who owns what code (directories, by line?, etc) 
3. Some can have multiple owners possibly? 
4. Set up out issue owners via path or url 
5. Figure out auto assignment
6. You can also add a new rule from an individual issue (Go through existing issues — this might be tedious, but just a thought) 
    1. From the issue details, click the ‘Create Ownership Rule’ on the right-hand panel.

### **Existing Docs for Products/Teams**
* [VFS Teams and Team members](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=0)
* [Product Directory](https://docs.google.com/spreadsheets/d/1hzz6whEGoQJQbiNvIggirhydYYdv57nfOZfLvFqZ1pQ/edit#gid=418383161)
* [Services Mapping](https://airtable.com/tblWliAo6fCVimC2C/viwbKpGgtM0JySci7?blocks=hide)
* [Team Definitions](https://airtable.com/tbl4ivFQqtbOLHMGm/viwUYVQf6qQppy8zg?blocks=hide) -- Created this to break out teams by url and/or directory within our codebase
* [Team Directory in va.gov-team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams)
* [List of Products in va.gov-team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products)


### **Helpful Links**
- https://blog.sentry.io/2018/05/29/relevance-and-ownership-of-issues
- http://sentry.vfs.va.gov/settings/vets-gov/projects/platform-api-production/ownership/
- https://github.com/getsentry/sentry-docs/blob/master/src/collections/_documentation/workflow/issue-owners.md

**Comment by kfrz** [comment]
Will want to consider and ticket out work for Sentry tagging in codebase(s)

**Comment by LindseySaari** [comment]
Team breakout:

1. VSP
2. VSA = is a contract of 8 VFS teams
3. Non-VSA VFS teams

**Comment by LindseySaari** [comment]
#### Current GH Teams to Reference for Sentry Team Implementation

- [VSP](https://github.com/orgs/department-of-veterans-affairs/teams?query=vsp)
- [VFS](https://github.com/orgs/department-of-veterans-affairs/teams?query=vfs)
- [VSA](https://github.com/orgs/department-of-veterans-affairs/teams?query=vsa)
- [Lighthouse](https://github.com/orgs/department-of-veterans-affairs/teams?query=lighthouse)

**Comment by LindseySaari** [comment]
May be useful to implement this [TF Sentry Provider](https://github.com/jianyuan/terraform-provider-sentry) for teams in the future.

**Comment by LindseySaari** [comment]
Next steps:
Get a bulk of the issues assigned to the existing teams now - Maybe tag the first one or two pages
Check out Grafana: Which teams own which apps — which apps call which endpoints 
Write up a description for the most popular issues and how to approach

**Comment by LindseySaari** [comment]
Another idea: Modify the Sentry tagging module to use team tags if provided
