### ISSUE TITLE
vets-website eMIS removal of test user data

### ISSUE THREAD

**Issue by rjohnson2011** [department-of-veterans-affairs/va.gov-team#75089]
## Issue Description
Remove EMIS references from the test user data descriptions. Assure that all specs are failing and resolve any errors that occur.

---
## Tasks
- [x] All test user data is updated to remove eMIS data and passing all specs.

## Acceptance Criteria
- [x] All test user data is updated to remove eMIS data and passing all specs.
---

**Comment by jennb33** [comment]
Per @rjohnson2011 this is working but it just takes a long time to run the tests. Running them one at a time.

**Comment by rjohnson2011** [comment]
PR is up here, all specs passing - https://github.com/department-of-veterans-affairs/vets-website/pull/27787

**Comment by jennb33** [comment]
@LindseySaari is going to review this and see if it can be finalized, otherwise it will have to wait until Ryan is back. Rebecca left her notes in the PR ticket on what was tested, and where the outstanding confusion lies with this ticket.

**Comment by LindseySaari** [comment]
I reviewed this work and will wait for Ryan to return. It seems like this chunk of error code in the PR could be removed instead of just deleting the comment

**Comment by rmtolmach** [comment]
My work to remove veteran-status in vets-api (https://github.com/department-of-veterans-affairs/va.gov-team/issues/75657) ended up needing vets-website changes. So my PR, https://github.com/department-of-veterans-affairs/vets-website/pull/27851, will cover the changes originally proposed in Ryan's PR. 

In short, this ticket can be closed along with Ryan's PR.
