### ISSUE TITLE
Opt Out of V3 Form Components

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#75081]
## Issue Description

**Release Deadline: 2/15/2024**

Announcement: https://dsva.slack.com/archives/C03R5SBELQM/p1705503589174489

_On February 16 all design system web components will default to their v3 variant. v3 will become opt out only. 
In one month, the design system team will be switching all web components to render their v3 variant automatically. If teams have a need to fall back to the original v1 variant, they will be able to do so by setting the uswds prop to false. However, v1 variants will eventually be fully retired and removed so opting out is discouraged._

Our forms will be temporarily opting out of the update, so we can audit the existing components and apply updates as part of our ongoing initiative to update forms.

---
## Tasks
- [x] Set the uswds prop to false for:
   - [x] Chapter 31 (VR&E), 28-1900
   - [x] Chapter 36 (PCPG), 25-8832
   - [x] Burial, 21-530EZ
   - [x] COE/LGY, 26-1800
   - [x] Dependents, 21-686c and 21-674

## Acceptance Criteria
- [ ] The V3 components are not applied to the forms listed above on 2/16/2024.
---

**Comment by humancompanion-usds** [comment]
@steele-lm - May I ask why you want to opt-out so that the Design System Team can do a better job of communicating to teams? Is it lack of confidence in your tests of your apps or lack of confidence in the v3 components themselves or something else?

**Comment by steele-lm** [comment]
@humancompanion-usds It's mainly a resourcing and timing issue. We're in the midst of [overhauling the burial form (530EZ)](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65251) and [dependent forms (686c/674)](https://github.com/department-of-veterans-affairs/va.gov-team/issues/74059) and updating all of their components, but we won't meet the 2/16 cut off. We are also supporting a new Code Yellow for the non-disability forms. We will be updating the Chapter 31, Chapter 36, and COE forms and their components over the next several months -- Chapter 31 is [next](https://github.com/department-of-veterans-affairs/va.gov-team/issues/74141)!

**Comment by steele-lm** [comment]
@Midge-dev or @DLarson-Oddball Do we need a ticket (or tickets) to opt back into the V3 components as we release the updated forms? Or, is that already incorporated into the business-as-usual update process?
