### ISSUE TITLE
Contact Center Review for Veteran Status - Proof of Veteran status card

### ISSUE THREAD

**Issue by matt4su** [department-of-veterans-affairs/va.gov-team#75099]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
*Please provide the name(s) of your product and a high-level description of your product.*
Name: Proof of Veteran Status
Purpose: Provide simplified access to Veterans Status information to Veterans on VA.gov to ease their ability to access non-VA benefits and discounts.

### Launch Date
Code for feature initially pushed to Staging environment on 1/30/24.  Estimated production  launch date to 25% of users is ~2/21 and to 100% of users is ~3/5.

### Version Number
*Please provide the version number of the guide and/or video.*
Version 8

### Product Guide
*Please provide product guide link*
Feature is additive to Profile/Military Information page.  See page 55 of guide.

### Product Video
*Please provide product video link*
Not applicable
### Product Video Transcript
*Please provide product video transcript link*
Not applicable

[VAgov.Profile.ContactCenterGuide.v8 (1).docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/14141217/VAgov.Profile.ContactCenterGuide.v8.1.docx)

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
Hello @matt4su. Can you please provide me with the Revision History entry for this new version of the guide (v8)? There is no need to submit the Word doc again; you can reply here if you like.

**Comment by starlow00** [comment]
There are no changes from VEO. I've attached a working copy; please use it for future updates.
[VA.gov Profile product guide v8 SRT 02012024.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUkxQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0fe8996264c5855262f0c290c3ffd36e061f0c4c/VA.gov%20Profile%20product%20guide%20v8%20SRT%2002012024.docx)
