### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#75107]
### Name

Tze Lei

### Email

tze@adhocteam.us

### Role

FE Engineer

### Team

CEDAR Product Forms [aka Veteran Facing Forms]

### Product Manager (PM) name

Tricia Baker

### Additional Notes

Need to copy content from mockups, as well as measure element dimensions and spacing.

FYI, I did create a free-tier account with my email tze@adhocteam.us, if that makes any different in setting me up from your side.

**Comment by naomimarcussen** [comment]
Hi! I just sent another invite, but you can ignore that because I see you already have an account. :)

**Comment by tlei123** [comment]
Thanks much, @naomimarcussen !  My account settings now show seats added.  Closing ticket now.

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/587583/f8521a02-03af-4494-9c3f-8aa3a72083a1)
