### ISSUE TITLE
Discovery - Types of care

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#7511]
Create discovery documentation using this template -- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/engineering/discovery/FHIR/template.md

_While you are working through this discovery doc, please add WIP to doc header_

FHIR Resource list -- http://hl7.org/fhir/dstu2/resourcelist.html

**Comment by jbalboni** [comment]
Notes: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/engineering/discovery/FHIR/types_of_care.md
