### ISSUE TITLE
PROD inprogress forms submission failures

### ISSUE THREAD

**Issue by aplatt-coforma** [department-of-veterans-affairs/va.gov-team#75128]
During canary testing, we were notified of a few submission errors on PROD. We determined it was due to old fields on in progress forms that were not mapped to any new fields on the new form.

**Acceptance Criteria:**

**Comment by mjknight50** [comment]
Here is the PR that addressed this
https://github.com/department-of-veterans-affairs/vets-website/pull/27766

**Comment by aplatt-coforma** [comment]
We're at 25% on PROD with no submission errors so closing this ticket now.
