### ISSUE TITLE
SOCKS access for Devin McCurdy

### ISSUE THREAD

**Issue by devin-mccurdy** [department-of-veterans-affairs/va.gov-team#75139]
### Your Name

Devin McCurdy

### Your Email

devin@apothesource.com

### Your Role and Team

Software Engineer on Unified Appointment Experience

### Product Manager (PM) name and email

Katherine Lawyer, Katherine.Lawyer@va.gov

### Product Owner (PO) name and email

Katherine Lawyer, Katherine.Lawyer@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDCQUNcUDDc0jUJNJ/9aKdrAeaMteXASnnyELJtUpWs+69SWu9qRkeqe15bsiHh2/cnbuKtAW1Uj6CUz0UApgsnDljD1FAnZbNDkegoE77vmeyYzJA5CbGqRHHSOOOhvMKP7Wbllx3hc8RreyTLoKlwxwtT498lkfneuPVAFbx2uvSSUPYBLIu4xZ804EYTmSITdqULN6nqUvUJYXQHG3p8/gdlH0e4WVdsvFCYcEtc7XtrQD8dP3fTZvZ9X0Az0jGxKjM7ALmNdqmKXuVeplUZTX+OlAy5c/4pTgLEikID128HNCsEm/9qPZpwkVPLZxJN2oY7FpmNE3gZxNmeaRlQZuB0uGuFvliUoJw0m/BHgYpbwh/XwdpvIXSuOoLuo1HZGAjqatSkcO7W/XPfLPTDzl0Ks/rbaDYvC+angpOxqjD2ahWtzLcl3sDxGgL71Ck70sPFTmfa1nNX576DQJu4mJ1qoJxIVx6MI9hdp7ZvBX/hCHc/Vx9nFLai2idQQIk= devinmccurdy@Devins-MacBook-Pro.local

### E-QIP Transmittal Confirmation

Completed December 2016

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by anita-halici** [comment]
@va-vsp-bot Devin's Platform  checklist ticket has been marked as complete by the platform team. here is the ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/73588

**Comment by anita-halici** [comment]
re-opening, as the issue was fixed by the platform - https://github.com/department-of-veterans-affairs/va.gov-team/issues/73588#issuecomment-1924258676

**Comment by anita-halici** [comment]
@alyssagallion @bmatos312 could you please help us out with this request. All info has been provided. 
reference slack: https://dsva.slack.com/archives/CBU0KDSB1/p1707350751917409?thread_ts=1700592744.833889&cid=CBU0KDSB1

**Comment by anita-halici** [comment]
cc @lindsay-insco

**Comment by ph-One** [comment]
SOCKS access granted.
