### ISSUE TITLE
Inventory documentation about what we do (Request & Support Process)

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#75144]
**User Story**
As an Identity team member I want to look at all of the documentation we have about our team in order to help craft a coherent message to other teams.

## Description of Tasks
- [x] [Scope out what already exists](https://docs.google.com/document/d/13hhPhAN4rSEa1joI2rLGkMSee0FMss_VBiWG5zGqUcs/edit?usp=sharing)
- [x] Making sure that the way we talk about our work resonates with folks who are coming to us for help

## Acceptance Criteria
- [x] Research findings disseminated to team
- [x] Add finalized research to Github
- [x] Reviewed by UX Team
- [x] Reviewed by PMs

**Comment by kdmeg-bluetiger** [comment]
Added [findings and themes](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1707166080807/2d707f50311be8dd581dd3870f3f01328e4c8583?sender=u60a40851c146803bcec81259) to Mural board.
