### ISSUE TITLE
SOCKS access for Drew Connelly

### ISSUE THREAD

**Issue by drewconnelly** [department-of-veterans-affairs/va.gov-team#75140]
### Your Name

Drew Connelly

### Your Email

drew@apothesource.com, drew.connelly@va.gov

### Your Role and Team

Backend Engineer on Unified Appointment Experience

### Product Manager (PM) name and email

Kay Lawyer - katherine.lawyer@va.gov

### Product Owner (PO) name and email

Kay Lawyer - katherine.lawyer@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDSckPQslgrjjONW8kRtUTy8wh/LEi0y9lYbhbP6Ox9tgRFWEvu7Kcsj3SwZQRRXhYR1DUf5KD6wLk4A1gcWr+XcEykrUVG0esvBokxQNts6NxWf1l7NjvWEBYA3UKP8vGpQDVoQHSRpvPC5tGgeEY1vesnv9iS/KnuTc6E+bzLyvglMrl8pgOyivBwEmNr9aI++zbZftpTBrjeN86Re4ukmx4188tlF+KfhrjEqUso3wMSLlX5Q5+84mcafQ31KqkO/8+X0WQgU3khPsnpq9QPRrGf/SuMoEfOoWhG+K69FaNpNtkn/Q5GOl8x4z0INeE0YV/nWOFhPaW2z9HTjQ2/oGZvOASK4/2D9Sy1zAXvpSGHRfFLppKtv3XPcX5Qbpz1274javgKFUSqhB+Er/v/5bd3B06oj3LlixjvN1atjTw7IhzaqyeCw+b/cOMd3z+iYq+taOXntpLYJwkcBIDfXtOvkCvd/t3t1OhPyp7+mdq6u/r9Zc6F4VLPth+I4fs= drew@apothesource.com

### E-QIP Transmittal Confirmation

![Screenshot 2024-02-01 at 12 51 56 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/19856757/1019ce95-c4ea-44a0-9737-bd3ed57976ad)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by BrittanySFowler** [comment]
![image003](https://github.com/department-of-veterans-affairs/va.gov-team/assets/156118684/08c43232-a125-4459-97ad-9934f984d281)
Drew's equip is with the attached image

**Comment by anita-halici** [comment]
cc @lindsay-insco

**Comment by ph-One** [comment]
SOCKS access granted.
