### ISSUE TITLE
Discovery - Eligibility

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#7514]
Create discovery documentation using this template -- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/engineering/discovery/FHIR/template.md

While you are working through this discovery doc, please add WIP to doc header

Discovery notes: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/engineering/discovery/FHIR/eligibility.md

FHIR Resource list -- http://hl7.org/fhir/dstu2/resourcelist.html

**Comment by lenaecb** [comment]
@jbalboni - at this point, looks like we got all of our Eligibility Qs answered in our [JIRA ticket](https://issues.mobilehealth.va.gov/browse/VAOSR-634). 

We good to close this out?

**Comment by jbalboni** [comment]
@lenaecb Yeah, I think we can close this. I left it open because we have request related questions, but those are captured elsewhere.
