### ISSUE TITLE
Update search radius in backend for Find A Rep Search.

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#75155]
Update search radius in backend for Find A Rep Search, to support the new search distance field in the frontend (https://github.com/department-of-veterans-affairs/va.gov-team/issues/74301). Do it!

Search distance can be an integer >= 50 or null (null represents 'no distance' which means 'all' records will be returned, sorted by distance from the given location)

**Comment by holdenhinkle** [comment]
Also add 'all' (for all results)

**Comment by holdenhinkle** [comment]
PR - https://github.com/department-of-veterans-affairs/vets-api/pull/15428

**Comment by jvcAdHoc** [comment]
1. "all" records means all records with a location? If we include results without a location, then it's not possible to get a distance calculation for the result.
2. Does the param have to be an integer or just something that can be cast as an integer?
  a. 51 vs 51.0 vs 51.3
  b. if we allow 51.3, then what should the distance calculation use: 51 or 51.3?

**Comment by oddball-lindsay** [comment]
I'd recommend "all" records means all records with a location.  We'll match the search radius options the frontend is using.

Frontend is passing `null` for the "Show all" search radius selection.

**Comment by cosu419** [comment]
Current distances:

<img width="702" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzFDQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--67992e0d48a179d4460e10ea874bdfd244b9b343/image.png" alt="image.png" />

**Comment by jvcAdHoc** [comment]
I updated to code to only allow distance params in that dropdown. No distance param provided defaults to all with a non-nil location.
