### ISSUE TITLE
Discovery - Time Slots (both request and self schedule)

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#7516]
Create discovery documentation using this template -- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/engineering/discovery/FHIR/template.md

While you are working through this discovery doc, please add WIP to doc header

FHIR Resource list -- http://hl7.org/fhir/dstu2/resourcelist.html

**Comment by jbalboni** [comment]
Closing this because our one outstanding question would be answered by the VSP staging testing ticket
