### ISSUE TITLE
MAP STS Token Log Change Requests

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#75174]
The following log additions and change requests are to enable to monitoring of our MAP module within vets-api. Other logs can be added but they should be documented here and then in a final document on github. Someone will then take these new logs and add them to a [datadog dashboard](https://vagov.ddog-gov.com/dashboard/8j2-b5n-kic/identity-map-securitytoken-service?refresh_mode=sliding&view=spans&from_ts=1706219386428&to_ts=1706824186428&live=true).

- each time a token is requested
    - ip address
    - app name
    - icn
- each time a token is successfully granted
    - ip address
    - app name
    - icn
- each error for a token request
    - ip address
    - app name
    - icn
- each error for token validation failure
    - ip address
    - app name
    - icn
- latency and response times
    - response time for request token from MAP
    - response time for request token from vets-api
    - request to generate token validation times?
    - other areas we can monitor to determine if our token interactions with MAP are operating correctly

AC:
- all logs stated as completed are viewable in datadog
- MAP monitoring dashboard is complete within datadog

**Comment by bramleyjl** [comment]
## each time a token is requested


## each time a token is successfully granted
This already exists as ["[MAP][SecurityToken][Service] token success"](https://vagov.ddog-gov.com/logs?query=%22%5BMAP%5D%5BSecurityToken%5D%5BService%5D%20token%20success%22%20&cols=host%2Cservice&index=%2A&messageDisplay=inline&refresh_mode=sliding&stream_sort=desc&viz=stream&from_ts=1708288336725&to_ts=1708374736725&live=true), and includes `application` & `icn` values; the `remote_ip` can also be found in the log.

## each error for a token request


## each error for token validation failure
ip address
app name
icn

## latency and response times
response time for request token from MAP
response time for request token from vets-api
request to generate token validation times?
other areas we can monitor to determine if our token interactions with MAP are operating correctly

**Comment by joeniquette** [comment]
@bramleyjl for these logs, I need application to be a parsable field similar to the other tagged fields. Can we please add that? 
![Screenshot 2024-02-22 at 16 01 09](https://github.com/department-of-veterans-affairs/va.gov-team/assets/71290526/fdc87cb5-6d92-4ec6-af5e-6b68f1295a33)

**Comment by bramleyjl** [comment]
Logs have been updated:
<img width="660" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzJoQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1a34c332581cf740fe41dcfe4b9ff00cdbd95e5b/Screenshot%20from%202024-02-29%2017-28-44.png" alt="Screenshot from 2024-02-29 17-28-44.png" />

<img width="660" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzZoQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d06538c537534da4f008be74f0ded79c46c8a5b9/Screenshot%20from%202024-02-29%2017-29-10.png" alt="Screenshot from 2024-02-29 17-29-10.png" />
