### ISSUE TITLE
Document high-level user flows for all user types

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#75185]
### User story

As a Cartographers team member, I want to visually document high-level user flows for all user types, so that teams can more easily reason about the UX current state and how possible changes might affect different types of users.

### Notes
- Where are our user types/use cases documented in github?
- Sara identified the need for this ticket in sprint planning 1/31/24

Possible tasks:
- 

## Acceptance criteria

- High-level user flows documented in Mural

**Comment by wesrowe** [comment]
@sterkenburgsara, this ticket from the backlog seems to describe the diagramming you're doing currently.

**Comment by wesrowe** [comment]
@sterkenburgsara, consider closing this? I think you covered it with the [access/BE logic mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1717177396025/367057c4a9219404c3b7080e71210082b3c65771?sender=uebde62ceb342c6477fb09406).

**Comment by sterkenburgsara** [comment]
Agree the Mural should cover this at a very high-level. Closing.
