### ISSUE TITLE
[BE] 10-10EZR TERA: Discovery -- Can we store TERA data without VES update?

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#75207]
As a Veteran, I would like to update my Toxic Exposure information as soon as possible so that I make sure I'm getting any and all the Healthcare benefits I have earned.

- [ ] Learn how HEC will store the paper form
- [ ] --From Stacey Echols: _We maintain copies of the paper applications consistent with the retention schedule.  Also, There is a document storage section in the VES for these._ AS: So it sounds like they're going to scan them and store that.
- [ ] Determine if we could store digitally generated PDFs in VES and if it would be secure
- [ ] Determine if the digitally created PDFs will have data that can later be integrated into VES, and if it can be restored and prefilled
- [ ] Determine if there are any other ways to store these forms without VES fields--and look to see how other teams do it (would be good to talk to Faulkner, we can discuss how and what we need to ask).
- [ ] Determine if this is a good idea
- [ ] **Success: We know if it is technologically feasible to store TERA data without the VES update**

**Comment by lihanli** [comment]
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/830084/c5cea3af-24d6-4c4b-ac15-b3b92eb203ce)
