### ISSUE TITLE
Investigate: Create question link IDs for COVID 19 FAQs

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#7523]
## Investigate: Create FAQ question link IDs for COVID 19 FAQs page

**User story:** As a Veteran or VA call center rep, I want to be able to send someone a link to a particular question on the [Coronavirus FAQs: What Veterans need to know ](https://www.va.gov/coronavirus-veteran-frequently-asked-questions/)page. 

**Problem:** 
Today, question/answer links are not automatically generated in a way that's easily accessible by visitors to our coronavirus FAQs page. They have to go into 'inspect' element in their browser and most users don't do that, even when they know how. 

**Question:**
1/ Can we provide a link ID for questions, so that each question shows a  link ID URL in the browser that users can easily copy/paste from their address bar -- the way you can do this on our design system pages with H2s?

Example: https://design.va.gov/content-style-guide/seo#seo-best-practices-for-writing-copy

![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/ba863881-dbc4-4fd7-b360-54ce1f15bac9)

2/ And also, so that the URL stays agnostic of the exact question text -- for example, if we have to slightly edit the question by adding a word or removing a word, the previous question link wouldn't break? 

**Example of question links today, provided by Randi from inspecting header element:** 

I don’t have symptoms, but I feel anxious and overwhelmed. What should I do?
www.va.gov/coronavirus-veteran-frequently-asked-questions#i-dont-have-symptoms-but-i-fee
 
How do I know if my VA health facility is still open for regular appointments?
www.va.gov/coronavirus-veteran-frequently-asked-questions#how-do-i-know-if-my-va-health-

Example of question ID links on NYT:
These are not necessarily what we want; they don't generate copy/pastable URLs from the topic header for example. 
https://www.nytimes.com/2020/03/27/world/coronavirus-live-news-updates.html
https://www.nytimes.com/2020/03/27/world/coronavirus-live-news-updates.html#link-4f4406cb
https://www.nytimes.com/2020/03/27/world/coronavirus-live-news-updates.html#link-1a1e79ae 

ETA - not urgent, but this would be very helpful to users and to call centers and others responding to Veteran questions coming into VA. (This could likely be useful to adapt to all Q/As broadly in the future, perhaps as a automatic feature from the CMS maybe.) 

## Acceptance Criteria 
- [ ] TBD

**Comment by jenniferlee-dsva** [comment]
I couldn't upload the image from my gfe, so trying again from personal machine: 
![image (7)](https://user-images.githubusercontent.com/43381063/78254056-57e08c80-74c3-11ea-86be-dfb77f4eadf3.png)

**Comment by ncksllvn** [comment]
> Can we provide a link ID for questions, so that each question shows a link ID URL in the browser that users can easily copy/paste from their address bar -- the way you can do this on our design system pages with H2s?

We can do that. I remember us talking about doing that at least from the CMS Preview Server so writers could easily grab that ID, but we decided to hold off. 

> And also, so that the URL stays agnostic of the exact question text -- for example, if we have to slightly edit the question by adding a word or removing a word, the previous question link wouldn't break?

Hm, this is a _little_ tricky because to allow the text to change without changing the link ID, we're essentially unbinding the heading ID from the actual text of the heading, so we need a persistent identifier to rely on rather than generating it. Each chunk of content from Drupal comes through with an ID, so we might be able to wrap each chunk of content using that ID so that we can link to it. Each section of the Coronavirus FAQ page is a WYSIWYG chunk, so in that case, I think we could leverage the ID of each WYSIWYG to do the linking. Then we could edit the content all we want to, and the link would only break if that WYSIWYG chunk is deleted.

**Comment by ncksllvn** [comment]
I tried this locally. To link to the `What's coronavirus COVID-19?` section, you would use the link `/coronavirus-veteran-frequently-asked-questions/#link-8824` -

![image](https://user-images.githubusercontent.com/1915775/78268938-ef9ba600-74d6-11ea-9bf8-f3caac87255a.png)

**Comment by kelsonic** [comment]
Any update on this ticket? 🙂 Is it still needed? CC @stephorkandatx

**Comment by stephorkandatx** [comment]
@DanielleThierryUSDSVA is this an item that is still desired/required for the COVID 19 FAQs?

**Comment by DanielleThierryUSDSVA** [comment]
Hi @stephorkandatx @kelsonic. We've been providing anchor links so folks can link directly to specific questions. But this looks like something a bit different. Let me look into this a bit more and follow up with Jen and Randi. Thanks!

**Comment by MickinSahni** [comment]
Would need to figure out how to open accordion. Drupal does give ability to create ids as needed. (although Drupal jump links do cut off at 30 char)
