### ISSUE TITLE
Update submission transformer to accommodate new field updates

### ISSUE THREAD

**Issue by michaelclement** [department-of-veterans-affairs/va.gov-team#75238]
As a developer, I need an updated submit transformer function that maps data entered in the form to the shape the backend expects. 

Acceptance criteria
- [x] Submit transformer collects all inputs from front end
- [x] Submit transformer outputs a JSON object that matches what the backend expects

**Comment by michaelclement** [comment]
@baltes I've added this ticket to reflect the work that needs to happen once all the content sections are updated.

**Comment by baltes** [comment]
Great, thank you!

**Comment by michaelclement** [comment]
Moved to blocked to more accurately represent the order of events

**Comment by michaelclement** [comment]
TODO: While taking care of this, do some research into what the backend is expecting metadata-wise. I.e., does this need to provide some extra info on supporting documents so that they can be properly identified?

**Comment by michaelclement** [comment]
[PR is here](https://github.com/department-of-veterans-affairs/vets-website/pull/28113). Just waiting on:
- [ ] Internal review
- [ ] Platform approval
