### ISSUE TITLE
Datadog Browser Integration Documentation  (Datadog Browser Int)

### ISSUE THREAD

**Issue by jimcconnelly** [department-of-veterans-affairs/va.gov-team#75245]
**User Story**
As a Va.gov engineer I would like to see documentation on the Datadog browser integration in order to understand how it was implemented on website

**Why Are We Doing This?**

-  For other teams, it would be to see how we did the implementation.
-  For our team, it would be what the Datadog information means. (If people on our team all know what the information means from Datadog, anyone could give an update to Tom when questions come through)

**Acceptance Criteria**
A README.me that would exist in platform/user/authn+ Documentation inside Identity folders with Datadog
- Documentation would include
   - What information we capture about the session.
   - Why we capture this information.
   - How is it useful for the Identity team and others.
   - Link to metrics.
   - Code comments via JSDoc
 - (Initial draft should go through UX or Content person before final publishing.)

**Comment by parkerbees** [comment]
Moved to Jira. Closing.
