### ISSUE TITLE
[Spike] Usage & Purpose of ID.me only GA Tag (Datadog Browser Int)

### ISSUE THREAD

**Issue by jimcconnelly** [department-of-veterans-affairs/va.gov-team#75242]
**User Story**
As an identity team member, I would like to discover how ID.me uses Google Analytics to determine if my team needs to replicate that work in Datadog.

**Why Are We Doing This?**
 We need to find out how ID.me (which is the only CSP that uses Google Analytics) uses Google Analytics.

Google Analytics doesn't work cross-site (VA.gov vs ID.me) so the original SSOe implementation added a way to track the entire authentication flow.

**Acceptance Criteria**
A README.md that exists in the Datadog folder for Identity

- (Initial iteration might just be a Google Doc)

**Comment by ianmagenta** [comment]
The Google Doc can be found here: https://docs.google.com/document/d/1Vr-A2LziUVYi096eq_TPRGIo-C1zgTsU3gq0bZhoSyQ/edit?usp=sharing
Note: the doc is only viewable to users with an Oddball email.
