### ISSUE TITLE
Catalog Current Frontend GA Tags (Datadog Browser Int)

### ISSUE THREAD

**Issue by jimcconnelly** [department-of-veterans-affairs/va.gov-team#75249]
**User Story**
As an Identity Team engineer, I wan to see a complete catalog of all current Google Analytics tags in order to ensure that we don't miss anything that is currently tracked.

**Why Are We Doing This?**
We don't want to miss anything that the Identity team currently owns with the Datadog Integration.

It will probably be part of a two-step process:
1. Add the Datadog browser integration alongside the GA tags
2. After confirmation that we aren't missing anything w/ Datadog, [remove GA.](https://github.com/department-of-veterans-affairs/va.gov-team/issues/75255)

**Acceptance Criteria**
A Google Sheet that lists the following:
- React containers and components in vets-website that include Google Analytics metrics recording for Identity, where for each item on the list we see.
   - Component Name
   - File Location
   - What information is captured (see AuthEvents)
   - Is it converted to Datadog?

**Comment by ianmagenta** [comment]
The Google Sheet can be found here: https://docs.google.com/spreadsheets/d/1iF0sjUR-Egc556kuEZFHS70RHD3kX-nfjd33ZAdH-CY/edit?usp=sharing
Note: the sheet is only viewable to folks with an oddball email.
