### ISSUE TITLE
Catalog Current Datadog Metrics  (Datadog Browser Int)

### ISSUE THREAD

**Issue by jimcconnelly** [department-of-veterans-affairs/va.gov-team#75250]
**User Story**
As a Identity team engineer, I want to catalog the current DataDog metrics in order to determine where we have gaps.

**Why Are We Doing This?**
Google Analytics is used mostly on the front-end (or vets-website), however our team has always never relied on Google Analytics because of the inaccuracies compared to StatsD and Datadog metrics.

Some of these will exist in vets-api already, we just want to get coverage in the FE so we can capture abandonment rates so we can subtract that from our auth numbers

**Acceptance Criteria**
A Google sheet that will list current metrics that exist in vets-api that is already captured. 
- Event Name
- Captured Information
- (etc) (probably need to fill this out)

**Comment by asg5704** [comment]
Captured information of current Authentication Events in vets-api.

https://docs.google.com/spreadsheets/d/1QIKutj1jMxCIKAzWp2TdemjUD7jwUCo2upHVZ6RkDZg/edit?usp=sharing
