### ISSUE TITLE
Remove Google Analytics For Auth Events (Datadog Browser Int)

### ISSUE THREAD

**Issue by jimcconnelly** [department-of-veterans-affairs/va.gov-team#75255]
**User Story**
As an Identity Team engineer, I would like to remove Google Analytics from auth events on vets-website in order to have only a single tracking system in place.

**Why Are We Doing This?**
We don't need both Datadog and Google Analytics, so after we've determined that Datadog works (and done all of the proper documentation), we need to discover how to properly remove Identity-owned GA tags.

**Acceptance Criteria**
A PR in vets-website removing all Idenity-owned Google Analytics tags.

**Comment by parkerbees** [comment]
Migrated to Jira. Closing.
