### ISSUE TITLE
Create Naming Convention  (Datadog Browser Int)

### ISSUE THREAD

**Issue by jimcconnelly** [department-of-veterans-affairs/va.gov-team#75256]
**User Story**
As an Identity Team Member I want to have an intuitive naming convention so that I can look a metric and easily understand what behavior it is measuring.

**Why Are We Doing This?**
We want something that it'll be easy to look at the log/metric and know exactly all the information. We're going to use the [Auth Event Additional Info](https://github.com/department-of-veterans-affairs/va.gov-team/issues/75258) to parse out what those metrics are.

Here's an example:
A non-verified user wants to sign in on the mobile app (mobile app requires verification to sign in FYI) using login.gov

1. User attempts to sign in, we would log:
sign-in-attempt_logingov_usip_sis_vamobile_loa3
2. User would see a failure because they are not verified
sign-in-failure_logingov_usip_sis_vamobile_loa1

Ideally we follow the same convention as API, but something like {{ event-type }}-{{ csp }}-{{ broker }}-{{ location }}-{{ application }}-{{ loa }} 

**Acceptance Criteria**
A updated README.md in Datadog folder for Identity
- Initial iteration can be Google doc

**Comment by asg5704** [comment]
Update:

[Authentication Events: Naming Conventions](https://docs.google.com/document/d/1Gjxa8ify16Cmm4WzUr-IrnBhsROFemZEuyMczA89PPg/edit?usp=sharing) is complete.

This should enable actual coding work to be started
