### ISSUE TITLE
Auth Event Additional Info (Datadog Browser Int)

### ISSUE THREAD

**Issue by jimcconnelly** [department-of-veterans-affairs/va.gov-team#75258]
**User Story**
As an Identity engineer, I would to have tags for for a series of Auth Events in the front end in order to track user actions that are not otherwise tracked

**Why Are We Doing This?**
With this information we will be able to exactly track certain information that Datadog in the backend does not track like abandonment for sign in or verification (abadonment is when a user attempts something then either closes the tab, or a browser, etc)

**Acceptance Criteria**
The following user actions will be tracked in Datadog:

- Auth Events
   - Sign in attempt
   - Sign in success
   - Sign in failure
      - Some are logged by sentry
    - Sign out
    - Register start
    - Register success (this will capture LOA1 accounts created)
    - Register failure
    - Verify start
    - Verify success (this will capture LOA3 accounts verified)
    - Verify failure
- CSP
   - Login.gov
   - ID.me
   - DS Logon
   - MHV
- Auth Broker
   - Sign-in Service
   - IAM SSOe
- Sign in Location
   - Unified Sign in Page
   - Sign in Modal
- Application (as by USiP)
   - VA.gov (default)
   - My HealtheVet
   - eBenefits
   - Oracle Health
   - VA Mobile App
   - VA OCC Mobile
- Level of Assurance Context
   - LOA1/IAL1 (non-verified)
   - LOA3/IAL2 (verified)

**Comment by asg5704** [comment]
Already complete

**Comment by parkerbees** [comment]
@ianmagenta it looks like this has been sitting "in progress" for a while - is this still being worked or can it be closed out? Thx.

**Comment by ianmagenta** [comment]
@parkerbees - Thanks for checking! This is still being worked on and you can find the PR associated with it here: https://github.com/department-of-veterans-affairs/vets-website/pull/27989

**Comment by parkerbees** [comment]
Thank you @ianmagenta !

**Comment by parkerbees** [comment]
moved to jira, closing
