### ISSUE TITLE
[FE] The profile fails to show the international postal code for an international address

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#7525]
## Background 
There are a few different bugs when working with international addresses in the Profile as seen in ticket [7493](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7493). This is the third one. 

## Issue
The profile fails to show the international postal code for an international address

**Comment by sanlouise** [comment]
@mshea0606  Can you please validate this ticket? Thank you!
