### ISSUE TITLE
Request access to Google Analytics for CDS apps

### ISSUE THREAD

**Issue by devopsmatt** [department-of-veterans-affairs/va.gov-team#75264]
# Request Google Analytics and/or Domo access

## What this form is for
Use this template to request access to Google Analytics and/or Domo. Please complete steps 1 & 2 below. 

## 1. Access Requirements 
Please check the analytics tool(s) you need access to:
- [x] Google Analytics
- [ ] Domo

## 2. User Email Address to Receive Access 
**Due to privacy concerns, please do not put your email in this ticket.** Instead please use `/support` on the DSVA Slack channel [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support), select `Analytics` in the "I need help from" dropdown, and then add in the `Summary of request` section: 
 1. This issue's link 
 2. Emails that need access

All people whose VA emails will be submitted via Slack will need GA Editor access.
Thank you!
 
---

### Definition of Done
- [ ] Provide access to user

**Comment by Blivaditis** [comment]
What is the email address you'd like access on?

**Comment by devopsmatt** [comment]
Hi @Blivaditis Thank you for the quick response.
I am compiling a full list of people, there will be about a dozen folks in total, from 2 application teams.
Some of them have not signed up for Google accounts using their VA emails yet.
I will be submitting the list along with the link to this GH Issue on Wednesday (Feb 7) EoD PST via Slack.

**Comment by Blivaditis** [comment]
Hey Matt I am going to close this request to make some space in zenhub. Once you get a list of people who need access create an access request for each individual and I will make sure to handle them.
