### ISSUE TITLE
Update API Endpoint Documentation to reflect Find 2.0

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#75262]
## Background
For the Privacy, Security, Infrastructure Readiness Review we'll need to provide a pathway to our API Endpoint Documentation.  

This ticket is to make sure the current API Endpoint Documentation reflects Find a Representative 2.0.

To view the existing API Endpoint Documentation: 
1. Go to the docs site
2. Type `https://dev-api.va.gov/services/veteran/v0/apidocs` into the search to click explore OR 
3. See json-only file

## Tasks
- [ ] Update the API Endpoint Documentation as needed, to reflect Find a Representative 2.0

## Acceptance Criteria
- [ ] The API Endpoint Documentation reflects Find a Representative 2.0

**Comment by holdenhinkle** [comment]
Go to https://department-of-veterans-affairs.github.io/va-digital-services-platform-docs/api-reference/
And search for https://dev-api.va.gov/services/veteran/v0/apidocs

<img width="1415" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3loQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b761a2f8fa228f37cdfdd4139fd61faa27c3fab2/image.png" alt="image.png" />
