### ISSUE TITLE
Debt Letters: Landing Page -Manage Debt

### ISSUE THREAD

**Issue by mattpointzxer0** [department-of-veterans-affairs/va.gov-team#7527]
## Debt Letters Landing Page
[Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/debt-letters-mvp/readme.md)

### The Problem
Currently, in order for Veterans to get information about debt management at the VA, depending on the nature of their circumstances, they are forced to visit multiple different pages buried within the VA's confusing IA and in some cases must even navigate to external properties in order to resolve debts. Assuming the Veteran is able to find the page(s), they are looking for, they are then faced with three problems:
- Lack of clarity: The way debt management works and the options which exist for resolving a debt, are not clearly presented and explained
- Confusion about how to find things: Useful information is buried in confusingly-named sub-pages and other locations
- Poor design and content: Important information is communicated ineffectively and aggressively

### The Solution
We will address these problems by implementing a debt "landing page" that will be a single source of truth for debt management that clearly communicates to Veterans what their options are and provides functionality and/or calls-to-action to give Veterans the ability to resolve debt in the way that is most appropriate for the Veterans specific set of circumstances.

### KPIs
- Landing page traffic?
- Increased traffic to calls-to-action?
- Decrease in response time to debt notifications?
- Can people find what they need more easily?
- Reduced time to understand content and find things (i.e., reduced time spent understanding the need for and finding the Financial Status Report form)

### Definition of done
- Implemented using the VSP Collaboration Process: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/vsp-collaboration-cycle.md
- Code completed and peer reviewed
- Unit tests passed?
- Functional tests passed
- User story acceptance criteria addressed
- Product Owner reviewed and accepted

### How to configure this issue
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by leahkeeler** [comment]
This epic is complete, staging review complete - ready for release
