### ISSUE TITLE
MHV downtime alerts

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#75276]
Cartography team is implementing standard MHV downtime alerts in the Pager Duty system. We need to provide content for these alerts in this Mural: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1705509202969/42becb4e1bcb478d93488ced78511a9c6acf9276?sender=u3038037989bec1f893349894

**Comment by laurwill** [comment]
Hi @wesrowe , I added suggested content updates to the Mural in yellow stickies. Let me know if you have any questions or feedback on these!

Also tagging @mistymg here for awareness — Misty, these are the downtime alerts we chatted about on Friday. I know mobile implements these types of things differently, but let us know if you have questions or want to flag anything for us for mobile considerations.

**Comment by dcloud** [comment]
@laurwill Could you clarify what was intended by

> If the maintenance windows will sometimes include midnight, suggest formatting the start and end times to put the date and time on a single line

Could you maybe write out an example or two?

**Comment by wesrowe** [comment]
A rich [slack thread](https://dsva.slack.com/archives/C0581MN69TJ/p1707168197204799?thread_ts=1707167668.841269&cid=C0581MN69TJ) answered some questions (e.g. "midnight") and got us close on some other topics like wording around "tool."

**Comment by laurwill** [comment]
@wesrowe okay to close this?

**Comment by wesrowe** [comment]
yes!
