### ISSUE TITLE
Update the VaBreadcrumbs web components to v3

### ISSUE THREAD

**Issue by jenniemc** [department-of-veterans-affairs/va.gov-team#75308]
## Description
Platform Design System team updated the web components from v1 to v3. We will need to make these changes in the Appointments application.

`<VaBreadcrumbs>`  web-component should have a `uswds` prop. Setting that to `true` will render the v3 variant for that web component.
[Design System](https://design.va.gov/storybook/?path=/docs/uswds-va-breadcrumbs--default)

We will update the component listed below: 

- [ ] Update to `<VaBreadcrumbs>` and set `uswds` prop to `true`

---

## Acceptance Criteria
- [ ] The component listed above will be updated from v1 to v3. 
- [ ] Ensure the breadcrumb is visible in UI

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by ldelacosta** [comment]
[Thread](https://dsva.slack.com/archives/CMNQT72LX/p1707166710117289) from 2/5 from the Design Systems team

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket.
