### ISSUE TITLE
[FE] 10-10EZ - Facility Selection: Launch API update

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#75304]
~BLOCKED - Need to work with Lighthouse team and provide the VASI number for our application to be "onboarded" to Lighthouse API~

## Background
Now that we have updated the 10-10EZ Facility selection page to use the Facilities API, rather than a static JSON list, we can launch to production.

The relevant feature toggle is `hca_use_facilities_API`, not `hca_use_facilities_api`.

## Tasks
- [x] Update feature toggle to launch for everyone
     - [x] Monitor submissions and check in with Joshua Faulkner to any unexpected behavior (increased volume of submissions going to manual review, submission failures, etc)

## Acceptance Criteria
- 10-10EZ with Facilities API update will be launched with no submission issues

**Comment by Mitch-A6** [comment]
We have seen _one_ issue since then, a submission that ran out of retries about an hour after the above. This would have been submitted 25h earlier, when we were still in the 25% Enabled state, so it makes sense that it would arrive after we enabled it fully.

**Comment by Mitch-A6** [comment]
Due to downstream constraints, we've disabled this functionality for now. We can't send along facilities that are too recent for ES to process. We'll try this again if we can pull the Facilities list from ES's DB instead.

**Comment by hdjustice** [comment]
#87005 - We pivoted to a solution that would allow us to perform a comparison between Lighthouse facilities API and Enrollment system, displaying only those that match.  This will help to avoid validation errors that result in submission failures.
This work was validated in staging and production.  Launch to Prod was completed on 8/27 successfully
