### ISSUE TITLE
Design cancelation experience at facility transitioning to OH

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#75318]
## Task Description

User story: As a user at a VistA facility that is transitioning to Oracle Health, I need to know how to contact a the facility when I can’t cancel my appointment online.

Design the user flow and interactions for this user when:
- Cancelling an in-person VA appointment
- Cancelling a VA request
- Cancelling a CC Request (To confirm)
- Cancelling (Other appt types to be confirmed)?

This does not apply to cancelling:
- Telehealth appts, as these can't be canceled currently
- Scheduled CC appointments, as these can't be canceled currently

## Notes and References
- Double check with product which appts can/can't be canceled.
- Use the standard alert to contact facility when canceled. See telehealth appt details

## Acceptance Criteria
- [ ] User flow for this scenario is complete (show logic)
- [x] Design spec for dev complete - show screens with changes

## Deliverables
- Here is a[ link to the design file](https://www.figma.com/file/0a7J9phMkfsfBTlt9L2q9f/Facility-transition-to-OH-Cancelation?type=design&node-id=2%3A4&mode=design&t=E1kqbeFP2QBDFQf8-1)

**Comment by melissa-lefevre** [comment]
Here is a[ link to the design file](https://www.figma.com/file/0a7J9phMkfsfBTlt9L2q9f/Facility-transition-to-OH-Cancelation?type=design&node-id=2%3A4&mode=design&t=E1kqbeFP2QBDFQf8-1)

**Comment by melissa-lefevre** [comment]
<img width="861" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGs1QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f947010e285ebb3f75f5a2bfe1d51095b35965b2/Screenshot%202024-02-07%20at%209.47.01%20AM.png" alt="Screenshot 2024-02-07 at 9.47.01 AM.png" />

**Comment by melissa-lefevre** [comment]
<img width="384" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHc1QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c5d280937c46508b9a9b415dcb6c4ce184337894/Screenshot%202024-02-07%20at%209.47.29%20AM.png" alt="Screenshot 2024-02-07 at 9.47.29 AM.png" />

**Comment by melissa-lefevre** [comment]
When a Veteran is Cancelling an in-person VA appointment, Cancelling a VA request, Cancelling a CC Request (To confirm) at any clinics starting with 556, they will no longer have the option to cancel online and will instead have the blue “need to make changes” alert This does not apply to cancelling:
Telehealth appts, as these can't be canceled currently
Scheduled CC appointments, as these can't be canceled currently
C&P appointments
Oracle Health booked appointments
