### ISSUE TITLE
Revise GitHub pull request template

### ISSUE THREAD

**Issue by johnpaulashenfelter** [department-of-veterans-affairs/va.gov-team#7531]
Our current GitHub pull request template needs a strong call-to-action for linking to the related issue in va.gov-team. 

Our template contains pass-through text that comes through as-is to reviewers (checklists, etc) that are rarely relevant to the majority of our PRs. Some developers remove them, but in general its is background noise to the content of the PR description. This needs revision and general tightening-up.

**Comment by johnpaulashenfelter** [comment]
@alexpappasoddball does this need an epic?

**Comment by alexpappasoddball** [comment]
@johnpaulashenfelter No this one is good to be an orphan!
