### ISSUE TITLE
Auto Auth accts part of 'auto-auth' set: for LOGOUT

### ISSUE THREAD

**Issue by kingbmike** [department-of-veterans-affairs/va.gov-team#75316]
As a user I want to be able to log out of all accounts who are part of the 'auto-auth' set, but we also want the ability to not log out of accounts who are NOT part of the 'auto-auth' set.

Acceptance Criteria:
-We want to logout of all accts who are part of the auto-auth set
     If I log out on Webpage A, then I am automatically logged out on webpage B
-We do NOT want to auto logout of accts that are NOT part of the auto-auth set
     If I log out on Webpage A, I am not automatically logged out on Webpage B
-Mobile will not be a part of the 'Veteran auto-auth clients', so they will log in and log out independently of other SiS clients

**Comment by bosawt** [comment]
this is no longer needed, we implemented auto-auth in a way that doesn't require special logout capabilities
