### ISSUE TITLE
Invalid Authenticity Token error 

### ISSUE THREAD

**Issue by cosu419** [department-of-veterans-affairs/va.gov-team#75311]
## Summary
Encountering an "Invalid Authenticity Token" error in staging when making a POST request to our recently created flag_accredited_representatives endpoint. Our initial thought was that the csrfToken needs to be included in the request headers. That token should be getting passed now, but the issue is persisting.

Support ticket:
https://dsva.slack.com/archives/CBU0KDSB1/p1707152032413019

## Steps to Reproduce
- Navigate to https://staging.va.gov/get-help-from-accredited-representative/find-rep/?address=43210&lat=40.001856&long=-83.014775&page=1&perPage=10&sort=distance_asc&type=veteran_service_officer&name
- Click the "Report outdated information" button on any of the search result card components
- This should trigger a modal with checkbox options. Select any option and click "Submit"
- Results in a 403

### Actual Result
Network request fails with 403 (Invalid Authenticity Token)

### Desired Result
200 response

## Definition of Done
- [ ] Representative reports are being created successfully in staging

**Comment by cosu419** [comment]
Summarizing what I've learned:

- Lighthouse routes turn off csrf as they were originally intended for backend services, but in this case a LH route is being used by the frontend
- The veterans module explicitly enables csrf protection
- The backend specs disable the authentication check
- Curl copying the headers of our GET request (vso_accredited_representatives) to borrow its csrfToken when testing flag_accredited_representatives was the recommended approach for testing the request. This does not seem to pass the csrf check. 

Updated the support thread as well:

https://dsva.slack.com/archives/CBU0KDSB1/p1707152032413019

**Comment by oddball-lindsay** [comment]
Is it possible this is related to the module configuration?  There are other controllers that are functioning

Perhaps @jvcAdHoc may have insight into what's going on

**Comment by oddball-lindsay** [comment]
Skipping the authenticity verification made it so that we could flag search results. This will work for internal team QA, but it's not a viable solution for Production due to security risks.

**Comment by oddball-lindsay** [comment]
Remaining: tackle international addresses

**Comment by holdenhinkle** [comment]
2 ideas:

1. Look for lighthouse post/create endpoints that are used by va.gov and analyze how the request is formed in va.gov (specifically regarding the csrf token) and how the request is handled in vets-api. 
2. If that doesn't work, move the flag endpoint out of the veteran module and into our own (or into the main `app` directory for vets-api). This should work without any problems.

**Comment by holdenhinkle** [comment]
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNldPQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--820a6cb521813bba27fe5c7d35faaf1418cd9f90/image.png" alt="image.png" />

**Comment by holdenhinkle** [comment]
PR for creating our `accredited_representatives` module with the endpoint to flag representatives - https://github.com/department-of-veterans-affairs/vets-api/pull/15684

**Comment by holdenhinkle** [comment]
This is ready to merge. Colin and I are discussing how we might be able to test this now given that we're about to have our staging review.

**Comment by oddball-lindsay** [comment]
Flag input moved to new module, ready for review

**Comment by cosu419** [comment]
Tried writing an entirely new method and still 403ing... trying to find some other way of testing the endpoint that isn't curl copying request headers (or the frontend).

  ```
static reportResultRewrite(newReport) {
    const csrfToken = localStorage.getItem('csrfToken');

    const headers = {
      'Content-Type': 'application/json',
      'X-CSRF-Token': csrfToken,
      'Source-App-Name': window.appName,
    };

    let body = {
      representativeId: newReport.representativeId,
      flags: [],
    };

    const startTime = new Date().getTime();

    for (const [flagType, flaggedValue] of Object.entries(newReport.reports)) {
      if (flaggedValue !== null) {
        body.flags.push({
          flagType,
          flaggedValue,
        });
      }
    }

    body = JSON.stringify(body);

    const requestUrl = `https://staging-api.va.gov/representation_management/v0/flag_accredited_representatives`;

    const apiSettings = {
      headers,
      body,
      method: 'POST',
      mode: 'cors',
    };

    return new Promise((resolve, reject) => {
      fetch(requestUrl, apiSettings)
        .then(response => {
          if (!response.ok) {
            throw Error(response.statusText);
          }
          return response.json();
        })
        .then(res => {
          const endTime = new Date().getTime();
          const resultTime = endTime - startTime;
          res.meta = {
            ...res.meta,
            resultTime,
          };
          return res;
        })
        .then(data => resolve(data), error => reject(error));
    });
  }
```

**Comment by holdenhinkle** [comment]
We determined that using the token from the xhr search response works, which is not the token that is being set in local storage.

**Comment by oddball-lindsay** [comment]
Is this a Staging-only issue?  Can we use our feature toggle to release to a single user to understand if this is an issue only in Staging?
