### ISSUE TITLE
EPIC - Sign In Service Auto-Auth

### ISSUE THREAD

**Issue by kingbmike** [department-of-veterans-affairs/va.gov-team#75326]
The intent of this work is to enable a feature that will allow auto authorization from one webpage to another when inside  given perimeters/auth-sets.  This will also enable auto logout from one page to the next when also within same set of given auth-sets.

* What is auto-auth?
  * A component of Single Sign On
  * The ability to sign in on webpage A, and be automatically signed in on webpage B
  * Linked sessions (if you log out on webpage A, you will be logged out on webpage B)
  * NOT a component of Service Account auth, only Client Auth
* Behavioral functionality:
  * For login:
    * We want to have the ability to automatically authenticate accounts that are part of the ‘auto-auth’ set
      * For example, if I authenticate on webpage A, and navigate to webpage B, I will be automatically signed in
    * We wan’t to have the ability to configure accounts that are not part of the ‘auto-auth’ set
      * For example, if I authenticate on webpage A, and navigate to webpage B, I will not be automatically signed in
  * For logout:
    * We want to log out of all accounts who are part of the ‘auto-auth’ set
      * If I log out on webpage A, I am automatically logged out of webpage B
    * We don’t want to log out of accounts who are not part of ‘auto-auth’ set
      * If I log out on webpage A, I am not automatically logged out of webpage B
      * For example, mobile won’t be part of the ‘Veteran auto-auth’ clients, so they will log in and log out independently of other SiS clients
* Criteria for Success for `Milestone 1`
  * Estimated to be complete end of ‘Sprint 4’, aka Feb 28
  * A Client Config will be able to be customized with the ability to be part of an ‘auto auth set’
  * When an end user logs into a Sign in Service client that is part of an ‘auto auth set’, they should have the ability to access protected routes on any client that is part of this ‘auto auth set’
  * When an end user logs out of a Sign in Service client that is part of an ‘auto auth set’, they will be logged out of all other clients that are part of the same ‘auto auth set’
* Questions/Comments
  * Should we show a prompt when user is ‘automatically authenticated’ on another web page? (Or just log them in automatically?)
  * We probably don’t want the ability to have multiple ‘accounts’ for an SSO user in Sign in Service,
    * If you authenticate on a ‘non-veteran application’ Sign in Service client, the session should be completely separate (not SSO/auto-auth connected)
  * We should probably start by implementing `prompt=none`, and then perhaps `consent/select_account`
  * Do we need a `prompt` value that is not described here? (For example, a way to ‘auto-auth’ if the user has already authenticated, and if they haven’t authenticated, send them through the standard auth flow instead of returning an error)
  * Do we need to exchange a token from webpage A, to get a token for webpage B?
    * Or can we just continue using token from webpage A directly on webpage B?
    * There might be a bit of weirdness with custom access token attributes (user attributes)
    * We possibly want to investigate OIDC token exchange: [OAuth 2.0 Token Exchange](https://cloudentity.com/developers/basics/oauth-extensions/token-exchange/)
    * Or should `prompt=none` just return new tokens?
      * The problem here is for cookie tokens we have a single cookie name
  * Should an ‘auto auth set’ have it’s own single cookie token namespace, and ‘non auto auth’ have different cookie names?
    * Veteran representative Sign in Service client, want to have a completely separate session from VA.gov

**Comment by parkerbees** [comment]
All tickets complete or moved to Jira. Closing.
