### ISSUE TITLE
Transition VRE upload claim :error to being marked as a :warning

### ISSUE THREAD

**Issue by micahaspyr** [department-of-veterans-affairs/va.gov-team#75322]
When an exception sending a VRE claim to VBMS is raised, an exception labeled as an "error" is raising an issue when it is more of a warning as there is a failover in which the claim is then sent to central mail once it fails.  The failover is being rescued as intended, therefore we can get rid of logging the exception to sentry.

- [ ] Remove log_exception_to_sentry call from send_to_vre method (line 123)<img width="1632" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGNzQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bb5ba98210c0ce855a371135bcd64d495c2ac533/Screenshot%202024-02-05%20at%2010.59.06%E2%80%AFAM.png" alt="Screenshot 2024-02-05 at 10.59.06 AM.png" />

**Comment by sortizsh** [comment]
micah will see if this was pushed out

**Comment by sortizsh** [comment]
blocked by someone else's failing test(simpleforms). moving to blocked and will check later.
