### ISSUE TITLE
Implement Metadata Validator for Backup Submissions

### ISSUE THREAD

**Issue by SamStuckey** [department-of-veterans-affairs/va.gov-team#75323]
In https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/form526_backup_submission

Add a call to the metadata validation library at https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/simple_forms_api_submission/metadata_validator.rb

An example of a consumer of this validation can be found at
https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/simple_forms_api/app/controllers/simple_forms_api/v1/uploads_controller.rb

This validation will clean the passed metadata to align it with Benefits Intake metadata requirements defined at https://developer.va.gov/explore/api/benefits-intake/docs?version=current

---
**Context:**

The following submissions failed backup processing as a result of an apostrophe in the first name. Both submissions actually belong to the same veteran.

> "Invalid Veteran name (e.g. empty, invalid characters, or too long). Names must match the regular expression /\\A[a-zA-Z\\-\\/\\s]{1,50}\\z/"=>[{:sub_id=>1855243, :created_at=>Sat, 08 Apr 2023}],
>
>  "Invalid Veteran name (e.g. empty, invalid characters, or too long). Names must match the regular expression /^[a-zA-Z\\-\\/\\s]{1,50}$/"=>[{:sub_id=>1827123, :created_at=>Sat, 25 Mar 2023}]}

In the case of Benefits Intake API, "Only upper/lower case letters, hyphens(-), spaces and forward-slash(/)" are allowed characters for first and last names ([source](https://api.va.gov/internal/docs/benefits-intake/v1/openapi.json)).

The `get_meta_data` method in `Form526BackupSubmissionProcess::Processor` doesn't validate `veteranFirstName` or `veteranLastName` as is now performed in a 4142 submission using the Metadata Validator.

**Comment by SamStuckey** [comment]
Blocking this behind "investigate LH failures" because they may be old.  We should know how relevant they are to inform if we *need* the metadata validator

**Comment by tblackwe** [comment]
Rewrote ticket and moved it to TODO

**Comment by freeheeling** [comment]
vet-api PR [#15425](https://github.com/department-of-veterans-affairs/vets-api/pull/15425) deployed to production 2/7/24. Moving to Done.
