### ISSUE TITLE
GIBCT: VETTEC Logo and Additional Resources sections not displaying correctly on medium and small screens

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#7533]
The VETTEC logo is and Additional Resources sections are displayed on the profile page for all VETTEC providers. On large screens, the logo and additional resources pages are displayed in the top-right corner. on screens with smaller widths, a few problems occur with these sections:

- For screens with 768px to approximately 950px width, the VETTEC logo overlaps the Additional Resources section
    - The divs for these two sections overlap no matter how large of a screen
    - This issue does not exist on all profile pages. For example, [Galvanize Inc](https://staging.va.gov/gi-bill-comparison-tool/profile/2V000105/GALVANIZE%20DATA%20SCIENCE%20IMMERSIVE) behaves as expected but the logo overlaps on the [Code Fellows](https://staging.va.gov/gi-bill-comparison-tool/profile/2V000247/ADVANCED%20SOFTWARE%20DEVELOPMENT%20IN%20ASP.NET) profile page.
- For screens 481-767px in width, the VETTEC logo and Additional Resources sections are both completely missing
- For screens 480px in width and smaller, the logo is appropriately placed, but the Additional Resources section is still missing

![Screen Shot 2020-04-02 at 10.30.01 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/0068d68f-e8e2-4cec-a71e-66f3f5c2c967)

---

![Screen Shot 2020-04-02 at 10.29.04 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/24fc59dc-d66a-41eb-a7fc-a8eb311fe056)

---

![Screen Shot 2020-04-02 at 10.15.37 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/51adadef-8542-4064-934d-3100527e4f74)

---

![Screen Shot 2020-04-02 at 10.29.33 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/ee5c4ec6-c7c6-41d1-8f49-df9c76a7d98d)

---

![Screen Shot 2020-04-02 at 11.28.20 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/650c2a3e-33c8-4a6f-910f-9b966ceb05ec)

**Comment by delli-gatti-michael** [comment]
Original vettec logo implementation story: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19184

**Comment by ksantiagomorgan6** [comment]
Pull request:

https://github.com/department-of-veterans-affairs/vets-website/pull/12156

**Comment by delli-gatti-michael** [comment]
Local testing complete

![Screen Shot 2020-04-08 at 9.20.14 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/3898c883-642b-44f2-a883-3ab350d7977b)

---

![Screen Shot 2020-04-08 at 9.20.45 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/965198ac-aa15-40a0-b8ac-1a707d2dbe8b)

---

![Screen Shot 2020-04-08 at 9.18.31 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/dfea512d-d828-4ff2-8157-12268bcb4314)

---

![Screen Shot 2020-04-08 at 9.21.29 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/acdad636-7809-476e-abc1-51d116e50bde)

**Comment by ccruzgra** [comment]
@delli-gatti-michael For the images you shared, it seems either the top or bottom paddings or margins are excessive now. You can see in the first image you provided, between the VET TEC logo and the Additional Resources, that spacing is a lot. For reference, here's the last prototype we had for 116, the profile page: https://bahdigital.invisionapp.com/share/APIAC31SV63#/screens/296024602 just to get an idea of the spacing. It would be similar for smaller displays. 

For the second image, that logo should probably be above the Additional Resources like in some of the other examples.

**Comment by ksantiagomorgan6** [comment]
Additional PR: https://github.com/department-of-veterans-affairs/vets-website/pull/12237

**Comment by delli-gatti-michael** [comment]
## Preferred Provider

![Screen Shot 2020-04-16 at 11.44.04 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/f0b3b20b-8d05-444b-bde8-918c37efa9c2)

---

![Screen Shot 2020-04-16 at 11.44.38 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/909e53f4-1254-40fb-85ea-83e23779a081)

---

![Screen Shot 2020-04-16 at 11.44.49 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/f2502f23-5332-42c5-8202-15e3c8798581)

---

![Screen Shot 2020-04-16 at 11.45.26 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/9f975014-f8ff-40d3-a2ec-fb2ea68b1648)

---

![Screen Shot 2020-04-16 at 11.45.39 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/e6c04626-0e67-45dc-bfd8-4d37633858c8)

---

![Screen Shot 2020-04-16 at 11.46.17 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/9d654630-1359-46e9-b4eb-02b089d76c1b)

## Non-Preferred Provider

![Screen Shot 2020-04-16 at 11.48.19 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/be79e3e7-a53b-4d56-a331-4820d301d6db)

---

![Screen Shot 2020-04-16 at 11.48.00 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/8d1e874c-e5fd-4db9-ba5d-b048edce7115)

---

![Screen Shot 2020-04-16 at 11.47.43 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/9f923b15-630a-4d48-91bf-591fdd10fc68)

---

![Screen Shot 2020-04-16 at 11.47.16 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/61e6382f-fc43-43cf-acde-1d02e87ed3ad)

---

![Screen Shot 2020-04-16 at 11.47.07 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/ee00c7d4-fcfd-4157-bd46-5afe3851f900)

---

![Screen Shot 2020-04-16 at 11.46.44 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/987a757c-d61b-409f-9594-6c3b8bcb265a)

**Comment by desireeturner** [comment]
Testing @department-of-veterans-affairs/bah_uxteam

**Comment by ccruzgra** [comment]
@delli-gatti-michael Thanks for sharing the images. A couple of the examples are still showing the logo not above Additional Resources section when AR is to the right of the institution name. @ksantiagomorgan6 and I met to discuss a fix and he'll be working on that. Looks like the logo's bottom padding's a bit tight on some images, like the 2nd from last posted. @delli-gatti-michael Could you please number the images next time so they are easier to track? Thank you!

**Comment by ksantiagomorgan6** [comment]
Pull request for updated changed https://github.com/department-of-veterans-affairs/vets-website/pull/12288

**Comment by delli-gatti-michael** [comment]
@amyknox @ccruzgra @JenLJ 

@ksantiagomorgan6's latest changes are now in Staging and ready for UI/UX review

**Comment by ccruzgra** [comment]
@delli-gatti This checks out on my end. Looks like the overlap and disappearing logo issues have been resolved.

**Comment by delli-gatti-michael** [comment]
Thanks, @ccruzgra! Closing this one out.
