### ISSUE TITLE
Renaming Instances of Vet360 to VA Profile across Platform

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#75338]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)

## User Story
As a developer in the Department of Veterans Affairs organization,
I need to not see instances of `Vet360` because it's been renamed to `VA Profile`,
So that any searches for VA Profile will be accurate and comprehensive. And so that developers without the institutional knowledge that VA Profile used to be Vet360 will not be confused about the naming. 

Refer to [this link](https://github.com/search?q=repo%3Adepartment-of-veterans-affairs%2Fvets-api+vet360&type=code&p=2) for a sample search that was used to create the list in the discovery ticket

## Hypothesis or Bet
**If** _we make this change_ **then** _we expect this to happen_.

## OKR
O2. Our platforms are the best way to deliver products at VA
OKR 1: Our platforms hit the "elite" level (as defined by DORA) on Deployment Frequency, Lead Time for Changes, Change Failure Rate, and Time to Restore Service.

### What must be true in order for you to consider this epic complete? 

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

**Comment by rmtolmach** [comment]
What should the priority be on this work? What repos do we want to scope this work to? There is a LOT of `Vet360` throughout the org: https://github.com/search?q=org%3Adepartment-of-veterans-affairs%20Vet360&type=code

**Comment by jennb33** [comment]
I've asked @LindseySaari to weigh in. We will be doing 2024 objective review work on Thursday 2/8 so we will review this for priority as well. Thank you @rmtolmach

**Comment by LindseySaari** [comment]
I think we can chunk it out but potentially start with Vets API. From there vets website, mockdata, etc.
