### ISSUE TITLE
Q1 2024 Improved Monitoring: RDS Monitors

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#75334]
## Issue Description
RDS Monitors

---
## Tasks
- [ ] TK

## Acceptance Criteria
- [ ] TK

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Labeled with Team** operations
- [ ] **Labeled with Practice Area** backend, devops
- [ ] **Labeled with Type** monitors

**Comment by RachalCassity** [comment]
RDS CPU Utilization Alert has been created, https://vagov.ddog-gov.com/monitors/198987?view=spans. This can probably be closed.
