### ISSUE TITLE
Q2 2024 Improved Monitoring: Alert for PG Queries

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#75335]
## Issue Description
Alert for PG Queries. 

---
## Tasks
- [ ] TK

## Acceptance Criteria
- [ ] TK

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Labeled with Team** operations
- [ ] **Labeled with Practice Area** backend, devops
- [ ] **Labeled with Type** monitors

**Comment by jennb33** [comment]
This ticket is a dupe and doesn't need story points, per @RachalCassity
