### ISSUE TITLE
Document Supporting Documentation File Upload Validations

### ISSUE THREAD

**Issue by tblackwe** [department-of-veterans-affairs/va.gov-team#75347]
In https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/75296

It was identified that some files are violating the upload guidelines set out at https://developer.va.gov/explore/api/benefits-intake/docs?version=current
We need to understand what rules we are currently enforcing in the frontend and determine if they are compatible with both EVSS and Benefits Intake

AC
- [x] Document the existing file upload validation
- [x] Create a ticket to update the front end validation to close the gaps

*** This may already have been determined as part of Document Upload EPIC

**Comment by freeheeling** [comment]
#### Benefits Intake API
Document upload requirements according to [documentation](https://developer.va.gov/explore/api/benefits-intake/docs?version=current)
- Must be a PDF
- Uploaded documents cannot be larger than 78" x 101" (increased from 21" x 21" on [5/10/23](https://developer.va.gov/explore/api/benefits-intake/release-notes))
- The entire payload cannot exceed 5 GB
- No single file in a payload can exceed 100 MB

**Note:** It is advised that the POST `/uploads/validate_document` endpoint be used to ensure documents will pass system file requirements and validations prior to being sent through the submissions process. This step is optional but decreases the likelihood of individual document errors during the submission process.

#### EVSS Documents Service
No formal documentation available
- File cannot be empty or corrupt
- 100 MB max PDF size (decreased from 150 on 8/9/23)
- 50 MB max for all other file types
- TXT files must be UTF-8 encoded (according to https://github.com/department-of-veterans-affairs/va.gov-team/issues/60157#issuecomment-1655988148)
- `MimeType` must equal the implied file name based on the extension of the file

**Note:** EVSS splits PDFs larger than 50 MB before sending to VBA who has a limit of 50 MB, thus the reason PDFs can be larger than other files.

#### Primary path
`EVSSClaimDocumentUploaderBase`
- file sizes:
  - PDFs: 1 byte to 99 MB
  - non-PDFs: 50 MB
- allowed extensions: pdf, gif, png, tiff, tif, jpeg, jpg, bmp, txt
 
`LighthouseDocumentUploaderBase`
- file sizes:
  - PDFs: 1 byte to 150 MB
  - non-PDFs: 50 MB
- allowed extensions: pdf, gif, png, tiff, tif, jpeg, jpg, bmp, txt

#### Backup
`BenefitsIntakeService::Service` utilizes Benefits Intake API

#### FE UI
Validations in [src/applications/disability-benefits/all-claims/utils/schemas.js](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/disability-benefits/all-claims/utils/schemas.js)
- max file size: 50 MB
- max PDF size: 99 MB
- min file size: 1 (binary based)
- file types: pdf, jpg, jpeg, png, gif, bmp, txt

**Comment by freeheeling** [comment]
I'm still waiting on a response from Michael Harlow sent last Friday with regards to accepted file types, max document size (by type), and page size, as well as any differences in document upload validations between EVSS and Lighthouse.

**Comment by freeheeling** [comment]
**EVSS doc upload rules:**
- Derived and implied MIME types must match
- File name must have a 3 or 4 character extension (e.g. .pdf)
- No restriction on page size
- minFileSize = 1
- maxFileSize = 157286400 (same as Lighthouse)
- maxPdfFileSizeBeforeSplitting = 104857600 (Lighthouse doesn't split)
- Valid file types = "PDF", "JPG", "TXT", "GIF", "BMP", "TIF", "TIFF", "JPEG", "PNG"

**Comment by freeheeling** [comment]
Sizes of files included in the following submissions, by `sub_id` that exceed the 100 MB maximum file size to Benefits Intake API (data sourced from [#75296](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/75296)):
> {"Maximum document size exceeded. Limit is 100MB per document"=>
>   [{:sub_id=>1722336, :created_at=>Fri, 03 Feb 2023}, 136,771,836 bytes and 136,771,836 bytes
>    {:sub_id=>1722357, :created_at=>Fri, 03 Feb 2023}, 148,855,919 bytes
>    {:sub_id=>1724847, :created_at=>Sat, 04 Feb 2023}, 124,181,038 bytes
>    {:sub_id=>1725331, :created_at=>Sat, 04 Feb 2023}, 136,771,836 bytes 
>    {:sub_id=>1725458, :created_at=>Sat, 04 Feb 2023}, 143,622,983 bytes
>    {:sub_id=>1725903, :created_at=>Sun, 05 Feb 2023}, 148,292,791 bytes
>    {:sub_id=>1726474, :created_at=>Sun, 05 Feb 2023}, 105,379,706 bytes
>    {:sub_id=>1726635, :created_at=>Mon, 06 Feb 2023}, 129,408,071 bytes
>    {:sub_id=>1726777, :created_at=>Mon, 06 Feb 2023}, 146,886,073 bytes
>    {:sub_id=>1727314, :created_at=>Mon, 06 Feb 2023}] 102,963,339 bytes

**Comment by freeheeling** [comment]
**Complete:** Documented findings.

**TODO:** Create a ticket to add UI page size validation.
