### ISSUE TITLE
Q2 2024 Improved Monitoring: DB queries/performance

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#75349]
## Issue Description
DB queries/performance 

---
## Tasks
- [ ] TK

## Acceptance Criteria
- [ ] TK

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Labeled with Team** operations
- [ ] **Labeled with Practice Area** backend, devops
- [ ] **Labeled with Type** monitors

**Comment by RachalCassity** [comment]
This has been completed in other tickets. :)
