### ISSUE TITLE
AWS access for Micah Frazier

### ISSUE THREAD

**Issue by micahaspyr** [department-of-veterans-affairs/va.gov-team#75343]
### COR Name

Jennifer O'Day

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Micah Frazier

### Your Email

micah.frazier@oddball.io

### Team, Role, and Company of the target individual

Team Umbrella, Full Stack Engineer at Oddball

### Product Manager (PM) name and email

Laura Steele / laura.steele@coforma.io

### Product Owner (PO) name and email

Emily Theis / emily.theis@va.gov

### Desired AWS Access

I am needing AWS access to write pertinent scripts in regards to the Code Yellow initiative with VA.gov

Desired AWS Access can be copied from [thomas.blackwell@coforma.io](mailto:thomas.blackwell@coforma.io) / Thomas.Blackwell

### Access Expiration

August 5th, 2024

### E-QIP Transmittal Confirmation

<img width="1229" alt="Screenshot 2024-02-05 at 12 53 47 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/6454840/2e2813df-4b21-49bf-89dd-733374682b21">

### Additional Notes

The ongoing Code Yellow initiative required AWS to run scripts.  Using an ArgoCD terminal times out after approximately 1 minute causing scripts to stall.

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [x] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by JonathanKamensDVA** [comment]
Approved.

**Comment by lindsay-insco** [comment]
User found in Atlas 

Transmittal notice confirmed.

**Comment by patrick-black-oddball** [comment]
account created - waiting for user to set up MFA
