### ISSUE TITLE
Add listening session to VA research repository

### ISSUE THREAD

**Issue by uxrebecca** [department-of-veterans-affairs/va.gov-team#75363]
**Description**

We need to put any relevant research in the VA's research repository. We haven't done this before so need to figure out how it's done, in particular for non-Veteran-facing research that's completed outside the collaboration cycle. Might need to work with Lesley on this.

**Resources**

- [VA Research Repository](https://github.com/department-of-veterans-affairs/va.gov-research-repository/projects/1)

**Acceptance criteria**

- [x] Listening session is in the research repository

**Comment by uxrebecca** [comment]
I used the link I found in the repository to make a card which now lives at: https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/488.

It is in the "proposed" column. I believe once someone in the ResOps team reviews it, it will move to "Complete." But will check in a couple days.

**Comment by uxrebecca** [comment]
Looks like I was able to move it to "Complete" on my own. Could just use a set of eyes from another researcher to make sure we're happy with it: [See the card in the repository](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/488).

**Comment by uxrebecca** [comment]
Reassigning to @kristen101606 to review and then close this ticket. Once reviewed I can share in the Benefits Portfolio channel!

**Comment by kristen101606** [comment]
Yes, this looks good. Thanks for adding it!

**Comment by kristen101606** [comment]
Yes, this looks good. Thanks for adding it!
