### ISSUE TITLE
SOCKS access for Brad Crosby

### ISSUE THREAD

**Issue by bcrosbyva** [department-of-veterans-affairs/va.gov-team#75371]
### Your Name

Brad Crosby

### Your Email

brad@apothesource.com bradley.crosby@va.gov

### Your Role and Team

Technical Lead on Unified Appointment Experience

### Product Manager (PM) name and email

Kay Lawyer - katherine.lawyer@va.gov

### Product Owner (PO) name and email

Kay Lawyer - katherine.lawyer@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP4gi4uSPU0Mp7N4RQ5PojW2CTv/R4mu5rz8WMQdSAXA brad@apothesource.com

### E-QIP Transmittal Confirmation

we are looking for my e-qip records

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by ph-One** [comment]
@bcrosbyva any update on your E-QIP email?

**Comment by bcrosbyva** [comment]
![crosbyb-piv](https://github.com/department-of-veterans-affairs/va.gov-team/assets/62714524/d80d8955-2cee-4545-9565-39623b9bb5cf)

**Comment by bcrosbyva** [comment]
![crosbyb-piv](https://github.com/department-of-veterans-affairs/va.gov-team/assets/62714524/5f14d9aa-d7e8-45aa-a11f-193088c7b5a5)
