### ISSUE TITLE
[SCREENREADER]: ARIA attributes MUST conform to valid values (COVID alert)

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#7538]
# [508-defect-1 :exclamation: Launchblocker](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-1)

**Feedback framework**
- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

There is an `aria-labelledby="usa-alert-heading-2925"` attribute on the  banner `div` that contains the "Help Limit the Spread of COVID-19 and other illnesses." There is nothing on the page that has an id of "usa-alert-heading-2925". ARIA attributes (i.e. starting with `aria-`) **must** contain valid values. These values must correspond to valid values to perform the intended accessibility function. This means that the contextual relationship will be lost. 

In this case, it appears the CMS has the attribute coded n `aria-labelledby="usa-alert-heading-2925"` by there isn't a heading with `id="usa-alert-heading-2925"` on the page. 

## Point of Contact

**VFS Point of Contact:** Jennifer

## Acceptance Criteria

As a screen reader user, I want to navigate the page with contextual relationships conveyed through my assistive tech.

## Environment

* Operating System: Windows (or any)
* Browser: Firefox (or any)
* Screenreading device: NVDA (or any)
* Server destination: staging/CMS web demo

## Steps to Recreate

1. Enter `http://vamcupgrade.web.demo.ci.cms.va.gov/pittsburgh-health-care/operating-status/` in browser, within the VA environment
2. Use the axe browser extension (in the VA VM, I used Firefox to install the extension) to scan the page
3. Verify that there is a critical issue for ARIA attributes MUST conform to valid values

## Possible Fixes (optional)

The `<div id="usa-alert-full-width-2925"…` has an attribute, `aria-labelledby="usa-alert-heading-2925"`, yet the heading within that it would generally pair with is `<h3 id="help-limit-the-spread-of-covid"…`. 

For the CMS, there are two options:
1. for the div, have the aria-labelledby value match the id of the h3 within
1. remove the aria-labelledby on this div

## WCAG or Vendor Guidance (optional)

* [ARIA attributes MUST conform to valid values - dequeuniversity](https://dequeuniversity.com/rules/axe/3.0/aria-valid-attr-value)
* [Accessible Rich Internet Applications (WAI-ARIA) 1.1 - Supported States and Properties](https://www.w3.org/TR/wai-aria-1.1/#states_and_properties)

## Screenshots or Trace Logs

![Screen Shot 2020-04-02 at 11 52 48 AM](https://user-images.githubusercontent.com/57469/78270207-86b52d80-74d8-11ea-9698-8799460c7e53.png)

![Screen Shot 2020-04-02 at 11 21 41 AM](https://user-images.githubusercontent.com/57469/78270055-57062580-74d8-11ea-8168-0eb35ba798a4.png)

![Screen Shot 2020-04-02 at 11 22 37 AM](https://user-images.githubusercontent.com/57469/78270053-57062580-74d8-11ea-98c8-43557ec6c366.png)

**Comment by 1Copenut** [comment]
@jenstrickland asked me to take a look at this item, and see if we could determine where the invalid markup was coming from. Based on some research, it appears there's an override being created in the CMS.

I thought we were using an existing [Liquid template](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/includes/alerts.drupal.liquid) to create these alert banners. On further investigation, the linked code is for in-page alerts. The banner being created for the COVID announcement is being created elsewhere, using some of the same logic. 

Where this breaks down is somewhere custom IDs are being applied to the `<h3>` inside the alert banner. That custom ID needs to be applied to the `aria-labelledby=<CUSTOM_H3_ID>"` or this error will continue appearing.

Tagging @SgardnerPMP for visibility.

**Comment by davidconlon** [comment]
@SgardnerPMP please ignore.  This is a template issue.
@mmiddaugh can you please add to back-log.  We will have gibran or ethan look into this.

**Comment by ethanteague** [comment]
No longer seeing this issue - it was fixed in another pr. Can you please confirm, @1Copenut @jenstrickland ?
cc: @mmiddaugh

**Comment by jenstrickland** [comment]
@ethanteague I still found the issue this morning.

![Screen Shot 2020-04-30 at 9 30 38 AM](https://user-images.githubusercontent.com/57469/80716176-5788e080-8ac5-11ea-82ea-631a59feef27.png)

**Comment by ethanteague** [comment]
Thanks for checking this out, @jenstrickland - looks like vamcupgrade instance is behind. Having a look at prod, I'm not seeing this issue. I am, _however_, seeing a landmark issue that I'm gonna put in a pr to fix.
![image](https://user-images.githubusercontent.com/2404547/80755255-7fe10100-8afe-11ea-900c-d7bb05b74b51.png)

**Comment by jenstrickland** [comment]
I have that landmark issue already documented a number of times, and assigned to VSP to fix:

#4215 , #7723 , #6368 , #8250

**Comment by ethanteague** [comment]
> I have that landmark issue already documented a number of times, and assigned to VSP to fix:
> 
> #4215 , #7723 , #6368 , #8250

Awesome! Ty, @jenstrickland

**Comment by jenstrickland** [comment]
@ethanteague I'm sorry to be the bearer of bad news. The issue does not appear to be fixed. What solution are you trying to fix this? In the code the `<h3>` still has an `id="help-limit-the-spread-of-covid' but the `aria-labelledby="usa-alert-heading-2925"` on the div is expecting something else. 

![Screen Shot 2020-04-30 at 6 45 40 PM](https://user-images.githubusercontent.com/57469/80766186-d3f5e080-8b12-11ea-9a77-441c06a57df2.png)

![Screen Shot 2020-04-30 at 6 46 41 PM](https://user-images.githubusercontent.com/57469/80766311-26cf9800-8b13-11ea-9171-ef44e752a13c.png)

The more I look at the div, though, I'm curious… The div class includes "dismissable-option-header" — but this isn't a dismissable alert. This is probably off-track, though. I'm curious why there is an aria-labelledby on this div in the first place. Is it possible to go into the CMS component and remove the aria-labelledby attribute? Since the id on the heading is currently generated by the text inserted for the h3, the aria-labelledby value would have to be dynamic. I don't think there's a need for the attribute at all.  Apologies if that's the solution you've implemented and it's just not appearing in the environment for me.

**Comment by jenstrickland** [comment]
Validated the fix in production. 👍
