### ISSUE TITLE
Adding [Hassan Tariq] to DSVA Slack

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#75389]
# Description

Please add htariq@metrostar.com to the DSVA slack as a full member. He is a new member of the VA-CMS team.

He needs to be added to the following VA-CMS channels:

cms-ci
cms-design
cms-helpdesk-bot
cms-lighthouse
cms-notifications
content-broken-links
tugboat-support

Please contact @michelle-dooley the VA-CMS Program Manager with any questions or additional information needed.

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

<describe the request>

Are you requesting to add an individual as a:

- Full member
- Single guest
- Multi-channel
- Switching from single-channel to multi-channel?
- What channel(s) do they need to be added to?

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add [_insert email_] as a single-channel guest to [_channel name_].
- Please add [_insert email_] as a multi-channel guest to these channels: [_channel names_].
- Please add [_insert email_] as a full member.
- Please change the status of [_slack username_] from [_current status_] to [_desired status_]

**Comment by LEHigley** [comment]
they're showing as a member
