### ISSUE TITLE
Qualitative Data Request

### ISSUE THREAD

**Issue by eheintzelman** [department-of-veterans-affairs/va.gov-team#75416]
### Data Type Requested

User Surveys

### Data Source Type

Medallia

### Date Range Start

10/01/2023

### Date Range End

10/31/2023

### Product Name(s)

Disability Compensation Application (Form 526) - Contention Classification

### Product Description

Providing support for the contention-naming experience (whereby Veterans add conditions to claim) on the Disability Compensation Application. We also maintain a service that provides a classification to contentions and this classification is visible to internal claims processors. 

### Survey URL(s), key term(s), case category or type

https://www.va.gov/disability/file-disability-claim-form-21-526ez (and all urls that live under this path)

### File Delivery Format

All in one file, on one tab

### Word Cloud

Yes

### VA Email Address(es)

eva.heintzelman@va.gov

### Add Assignee and Labels

If not already done so, please ensure @newworld2616 is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by newworld2616** [comment]
Hi, I have shared the Medallia data, let me know if you have any questions. Thank you!

**Comment by newworld2616** [comment]
Sent!
