### ISSUE TITLE
Sentry error around fetching messages on list page

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#7541]
Sentry: http://sentry.vfs.va.gov/vets-gov/website-production/issues/112484/?query=is%3Aunresolved%20source%3Avaos

Only affecting one person so far.

**Comment by jbalboni** [comment]
This is affecting a few more people now, should be worked on.

**Comment by jbalboni** [comment]
@lenaecb I'm going to pull this into the current sprint, since it looks like it's affecting a few more people now.

**Comment by jbalboni** [comment]
This might be related, too: http://sentry.vfs.va.gov/vets-gov/website-production/issues/114091/?query=is%3Aunresolved%20source%3Avaos

**Comment by vbahinwillit** [comment]
This issue is fixed indirectly by #12150
