### ISSUE TITLE
Domo analysis 

### ISSUE THREAD

**Issue by sortizsh** [department-of-veterans-affairs/va.gov-team#75414]
We want to gather information about data analytics in one place.  This information will be used to share with Team 1 (knowledge transfer), help us understand what we do and don't know about the data from Domo, and create the next steps of how we want to use data analytics in the future. 

Task:
- [x] Find information related to Domo and data analytics to include documents, folders, Slack threads, etc, and put them into a single source of truth document
- [x] Provide a short summary for each item in the single source of truth
- [x] Log into Domo and refresh on what's available to inform talking points
- [x] Outline talking points and open questions for Domo meeting on Wednesday

Acceptance criteria
- [x] Single Source of truth document with related items to data analytics/DOMO, short summary for each item, talking point and open questions for upcoming meeting

**Comment by nnicholas7** [comment]
2/9: Created a single source of truth with open questions and links to previous conversations and Slack messages.  This document helps us determine where we left off on data analysis and how we define terms.

Next steps: Meet with Julie to collaborate on moving forward to move to incorporate data analytics into our research flow. 

Single Source of Truth: https://docs.google.com/document/d/19Cfs8L1SmUaRUsWbOF35Y0BUsYz_c-QtlIltO6LEp3Y/edit

**Comment by nnicholas7** [comment]
Update 3/12/24: 
Update:  
Attended Data Analytics Office Hours 3/7 
Reviewed one approach to calculating drop-off rates for every URL of the form
Platform team validated this approach and suggested they set up a GA report from which we could export data and use pivot tables to review. (This is a light lift for them, and didn’t require a ticket.)

Next Steps: We found a couple things that indicate our total unique pageviews are too small in relation to the previous page paths (which would skew drop-off rates higher), so we’re confirming our understanding with the Platform team to ensure we have the right starting point.

**Comment by nnicholas7** [comment]
This ticket is linked to this: https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/75879
