### ISSUE TITLE
Qualitative Data Request

### ISSUE THREAD

**Issue by eheintzelman** [department-of-veterans-affairs/va.gov-team#75422]
### Data Type Requested

Support

### Data Source Type

MyVA.411

### Date Range Start

10/01/2023

### Date Range End

10/31/2023

### Product Name(s)

Disability Compensation Application (Form 526) - Contention Classification

### Product Description

Providing support for the contention-naming experience (whereby Veterans add conditions to claim) on the Disability Compensation Application. We also maintain a service that provides a classification to contentions and this classification is visible to internal claims processors.

### Survey URL(s), key term(s), case category or type

Case Category: Case Type (Subcategory)
- Navigation Issues: Disability Claim Application
- Application Submission Issue: Disability Claim Application
- Upload/Download Documents: Disability Claim Application
- Inaccurate or Missing Information/Status: Disability Claim Application
- Intent to File Issue: Disability Claim Application
- Feedback: General Feedback
- Concern (VBA): Other

### File Delivery Format

All in one file, on one tab

### Word Cloud

Yes

### VA Email Address(es)

eva.heintzelman@va.gov

### Add Assignee and Labels

If not already done so, please ensure @newworld2616 is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by newworld2616** [comment]
Hi @eheintzelman, I have shared the requested data for MYVA411, let me know if you have any questions. Thank you!

**Comment by newworld2616** [comment]
Sent!
