### ISSUE TITLE
FE | Hub | Update links based on Analytics Team Recommendations

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#75426]
In #72339 the analytics team recommended, for hub cards where there are multiple links, we should stop using the va-link component for the second link so our metrics will track more accurately. 

In this ticket we need to update our hub links so they stop using that link component and use a plain anchor tag instead. 

## Acceptance Criteria 
- [ ] the links are updated and we're seeing new metrics data roll into GA

**Comment by adamwhitlock1** [comment]
What needs to be done to validate this through GA? I have deployed the changes, and the 'plain ole link' have been on prod for probably about 48 hours at this point, so I do believe there should be plenty of events that will have fired.

**Comment by mtcA6** [comment]
@adamwhitlock1 [I think this report should reflect the changes ](https://analytics.google.com/analytics/web/?authuser=0#/analysis/a50123418w177519031p176188361/edit/_K1zzMjpQ2qxlfcC--aNiw)

There was a row that just said "Navigation - Link Click - Profile Hub -"
All of those should be replaced with the actual information of what a user clicked on so now we should see all of the different clicks in the profile.... and I think it worked.

**Comment by mtcA6** [comment]
@adamwhitlock1 oooooo also, I THINK this is the new place where we can build our reports for the dashboards that are going away.
