### ISSUE TITLE
AWS access for Peri McLaren

### ISSUE THREAD

**Issue by pmclaren19** [department-of-veterans-affairs/va.gov-team#75436]
### COR Name

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative Name

Other - please specify in 'Additional Notes'

### Your Name

Peri McLaren

### Your Email

peri.mclaren@adhocteam.us

### Team, Role, and Company of the target individual

Benefits Management Tools, Software Engineer, Ad Hoc

### Product Manager (PM) name and email

Jacob Worrell and jacob.worrell@adhocteam.us

### Product Owner (PO) name and email

Zach Goldfine and zachary.goldfine@va.gov

### Desired AWS Access

I need the same access as Jerek Shoemaker who is on my team.

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

They changed the email to be called eApp and its no longer called E-QIP ... heres is a screen shot of that email:
![Screenshot 2024-02-09 at 3 07 57 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/141954992/a443c476-a843-4e60-ab95-54f639c95156)

### Additional Notes

COR: Keith Riley
Vendor Onboarding Rep: Jeff Langworthy
Access Expiration: I need access to the parameter store as part of my ongoing work with vets-api

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [x] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by Mandalorian-Oddball** [comment]
User in Atlas.

**Comment by JoeTice** [comment]
SPRINT 47 UPDATE: IN PROGRESS - Work is completed, but working on resolving issues with the PR before we can mark completed.

**Comment by JoeTice** [comment]
@pmclaren19 - Hey Peri - Sorry for the delay here, trying to get this resolved... We noticed the image that you had attached to this ticket is not the image that we require... We believe the proper message should have:
- The words 'Transmittal Notice' should be in the subject line
- Your COR or PM should be in CC.
- The signature of the notification should mention the Personnel Security Adjudication Center (PSAC), or Office of Identity, Credential, and Access Management. 

If you can please attach an image that meets that criteria, we can try to get this processes and closed out

**Comment by pmclaren19** [comment]
Good Morning @JoeTice ,
This worked for my socks access so I thought it would work here as well. I know the email has changed from equip to eapp so are you guys should update the aws template and probably include that you want the eapp email with the subject  'Transmittal Notice'. 
Please see the updated email below:
![Screenshot 2024-03-01 at 8 01 28 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/141954992/594a19fa-36ad-42d2-ba56-5cb8086d6c46)

**Comment by Mandalorian-Oddball** [comment]
This request has been completed.

**Comment by Mandalorian-Oddball** [comment]
This request has been completed.
