### ISSUE TITLE
[Bug] Health Facility Location - Custom Dimension

### ISSUE THREAD

**Issue by jonwehausen** [department-of-veterans-affairs/va.gov-team#7544]
## What happened?
_Custom dimension (index number 51) is populating with other values in addition to what it should be populating with -- "Pittsburgh" in this case. _ From my understanding, the location will continue to be reflected within the URL structure for future modernizations. 

Please use this custom report as a starting template for reference

## Steps to Reproduce
- URL: https://www.va.gov/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/

## Desired behavior
_The custom dimension should only be populating with the relevant location. This functionality is expected to be expanded and utilized with other health care districts are ultimately launched / modernized_

Please use this [custom report template] (https://analytics.google.com/analytics/web/template?uid=hzBv06vCRP2d8obflbyrWA) to see inaccurate values. In the case of the Health Care Modernized View -- it's populating with "Health"

## Acceptance Criteria
- [ ] _Refactor current configuration to use the correct facility location_
- [ ] _Verify the custom dimension populates correctly across all relevant views - WBC, Health Care Modernized, etc)_
- [ ] _QA has been completed_

**Comment by jonwehausen** [comment]
@bsmartin-ep This is lower priority - but would be nice to deploy by sprints end in conjunction with 7336

**Comment by bsmartin-ep** [comment]
@jonwehausen - I believe this is ready for testing...

https://www.googletagmanager.com/start_preview/gtm?uiv2&id=GTM-WFJWBD&check_preview_status=1&gtm_auth=HBS3zb9ZxlUYM8jIlex8ow&gtm_preview=env-829&gtm_debug=x

I updated the regex to be a bit stricter and modified how JS extracts the _match group_.

Looks good on Pittsburgh...
https://www.va.gov/pittsburgh-health-care/
https://www.va.gov/pittsburgh-health-care/programs/cardiology/

Upcoming locations...
https://www.va.gov/butler-health-care/

And seems to be excluding the troublemakers giving us wrong data....
https://www.va.gov/health-care/about-va-health-benefits/va-health-care-and-other-insurance/
https://www.va.gov/health/newsfeatures/2014/february/new-id-cards-for-vets-enrolled-in-va-health-care.asp

**Comment by jonwehausen** [comment]
## QA Test

**Test Case 1**
1) Navigation to https://www.va.gov/pittsburgh-health-care/ (_and other subsequent pages_)
2) Verified "Pittsburgh" is populating for custom dimension 51
✅ **PASSED**
![image](https://user-images.githubusercontent.com/48527022/78377363-83d04080-759d-11ea-8db6-ee5f1dee0209.png)

**Test Case 2**
1) Navigation to /health-care (_and other subsequent pages_)
2) Verified `undefined` is returned for custom dimension 51
![image](https://user-images.githubusercontent.com/48527022/78377642-ddd10600-759d-11ea-86bb-85617470a3a4.png)
