### ISSUE TITLE
Content-build daily deploy schedule has changed, docs need update

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-team#75444]
### Description
The deployment timing for content-build has moved earlier in the day: 

* Note confirming that's true: https://dsva.slack.com/archives/C03R5SBELQM/p1706886743275579?thread_ts=1706635009.415119&cid=C03R5SBELQM
* PR where the change was made: https://github.com/department-of-veterans-affairs/content-build/pull/1896

Currently docs state: content-build: Changes in by 2p ET daily; Deployment start by: 3pm
Needs to update to say: Changes in by 11a ET daily; Deployment start by: 12p ET daily

### Subject matter expert you can consult
@ndouglas , until 2/16 contract transition.

### Relevant URLs
https://depo-platform-documentation.scrollhelp.site/developer-docs/deployments

### Which type of team are you on? (Platform team, VFS team, or Leadership)
VFS

**Comment by taylojill** [comment]
Hi there @jilladams - Thanks for flagging this issue. I'll be working on your request, and will review and provide updates via this ticket. Thank you!

cc @jknipes

**Comment by jknipes** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Content-Team-62bde00be46b400017674aef/issues/department-of-veterans-affairs/va.gov-team/75444?planning-poker) with Zenhub @taylojill

**Comment by taylojill** [comment]
Hi @jilladams The changes have been made as requested. The updated page will be published by 5pm ET today, February 14, 2024.

cc @jknipes

**Comment by jknipes** [comment]
Tasks complete, moving to _Done_
