### ISSUE TITLE
[Team] 10-10EZR TERA - Make recommendation for EZR Military Info

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#75442]
As a Veteran, I would like to be able to provide the VA with my Toxic Exposure information and have my healthcare status updated accordingly so that I am taken care of for the risks I took during my time in the Service. 

**This is a team ticket**

- [ ] Meet-Follow-up with HEC to determine how they are pulling/verifying Military Info data today (I have specific questions for this we can add to)
- [ ] Desk research to provide evidence that Veterans don't want to fill this (or anything) our multiple times
- [ ] Review and document technical hurdles and risks
- [ ] Demonstrate how an auto-fill and review workflow could work (high level)
- [ ] **Success: Pitch Patrick on the best EZR Military Info experience solution FOR THE VETERAN**

V2: - [ ] Talk to Profile team about their experience with VADIR and how to pull and verify data from that system

**Comment by lihanli** [comment]
Fields that can be prefilled:

1A. LAST BRANCH OF SERVICE
1B. LAST ENTRY DATE
1D. LAST DISCHARGE DATE
1E. DISCHARGE TYPE

DID YOU SERVE IN A COMBAT THEATER OF OPERATIONS AFTER 11/11/1998?
DID YOU SERVE IN SW ASIA DURING THE GULF WAR BETWEEN AUGUST 2, 1990 AND NOVEMBER 11, 1998?
DO YOU HAVE A VA SERVICE-CONNECTED RATING?

We don't need to know anything about VADIR, we can use the VA profile military information API to get the data, their system will deal with VADIR.
