### ISSUE TITLE
Upgrade AWS Elasticache Redis to the 5.0.x engine

### ISSUE THREAD

**Issue by johnpaulashenfelter** [department-of-veterans-affairs/va.gov-team#7545]
Our Redis instances in production/etc are running v3.2.4 which is *really* old. Newer versions of sidekiq *require* at least Redis 4.0 and newer versions of Rails need a higher version of the `redis` gem so we have a dependency train:

redis gem 4.0 or higher (needed for using the Rails RedisCache store)
-> requires sidekiq 5.0 or higher (sidekiq 4.x is locked to redis gem ~ 3.2)
  -> requires redis server 4.0 or higher

We need to upgrade our ElasticCache redis engine to at least 4.0, preferably 5.0 

- [x] dsva-vetsgov-prod
- [x] dsva-vetsgov-stag
- [x] dsva-vetsgov-sandbox
- [x] dsva-vetsgov-dev

**Comment by johnpaulashenfelter** [comment]
More info here: https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/VersionManagement.html

**Comment by johnpaulashenfelter** [comment]
@wyattwalter  @nathanhruby do you feel like we can just upgrade it in place? or should we practice that on another redis we spin up? Spinning up a new one would practice the recovery process as well if that's a process we even *have*.

What's the right way to plan this out? Assign an ops person to pair with me on it? /cc @ricetj

**Comment by nathanhruby** [comment]
Hey JP, I'm not sure what the nest way forward is here.  Probably an upgrade in place would work, but I don't know how durable the data is during that (IIRC, aws's answer is "it varies").  Do you want to chat about on Tu/Wed real quick ?

**Comment by omgitsbillryan** [comment]
Looks like we're already at 5?

![image.png](https://images.zenhubusercontent.com/59c291c1b0222d5de4787932/810e9b9b-f0c3-4a9a-aad0-313d8f43d76f)

Source: https://console.amazonaws-us-gov.com/elasticache/home?region=us-gov-west-1#redis:

**Comment by omgitsbillryan** [comment]
Oh, duh - those `vagov` cluster groups are not in use by `vets-api` which is currently configured to use the `vetsgov` flavor instead. https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/vets-api/prod-settings.local.yml.j2#L138

**Comment by omgitsbillryan** [comment]
Some notes:
- vets-api staging is already using a redis in `vagov`
  - prod & dev are still using redis in vetsgov
- a redis cluser group already exists for prod & dev but vets-api isn't using it yet
- sidekiq & vets-api redis data (i.e. `redis_store.rb`, `cache_aside.rb`) both use a singular redis instance
  - would be a Nice-to-have if these could be two separate redis instances

**Comment by erluti** [comment]
PR for Sidekiq to be upgraded to 5 https://github.com/department-of-veterans-affairs/vets-api/pull/4128

**Comment by johnpaulashenfelter** [comment]
Downtime in #8184
