### ISSUE TITLE
Design Intent - IA Feedback - Modernized Check-in, eCheck-in, Mileage-only Travel Claim Submissions for VA Facilities that use Oracle Health EHR Software

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#75459]
## Next Steps for the VFS team

- [x] **Assign** this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] **Comment** on this ticket:
  - If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members`.
- [ ] **Close the ticket** when all feedback has been addressed.

## Thoughts/questions

- Thanks for bringing this through! The user flow is very helpful.
- This is a fascinating interplay between a real-world campaign (signage, brochures, staff training directing folks to text a number) and a digital tool; I recommend presenting research findings or other learnings at a Monday design meeting.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

### Must

- [x] **User flow - Account for unregistered phone numbers**: There should be a helpful error message when users text the number from a phone that is not registered in the system. This use case might include a legit use case (someone texting the number from their phone on the Veteran's behalf, or the Veteran using a new number), or a curiosity use case (someone who just heard that this feature exists and is trying to use it).

## Governance team actions
- [x] Format feedback as individual tasks (check boxes)
- [x] Assign this ticket to the VFS team member that opened the Slack request
- [x] Add the VFS team product label
- [x] Add the VFS team the feature label (if applicable)
- [x] Add the touchpoint labels
- [x] Add the practice area labels
- [x] Add the Collaboration Cycle initiative milestone
- [x] Add the Collaboration Cycle initiative epic

**Comment by loripusey** [comment]
We already having some content for this; @benbrasso-agile6 can you paste the content we currently have for this here?

**Comment by benbrasso-agile6** [comment]
> We’re sorry. This phone number isn’t in our records. Please try again. Or ask a staff member for help.

This is what VeText sends

**Comment by benbrasso-agile6** [comment]
@loripusey I guess keep this open until we have a PR to link to

**Comment by loripusey** [comment]
By my account, we currently have a helpful message in place for this scenario. @erinrwhite is this message sufficient or not? 
cc: @benbrasso-agile6

**Comment by erinrwhite** [comment]
Looks good! Thanks @loripusey @benbrasso-agile6

**Comment by loripusey** [comment]
thanks @erinrwhite , closing
