### ISSUE TITLE
GIBCT: View less button in School Locations section should adjust focus

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#7546]
When viewing an institution profile, a user is able to see all of the different campuses and extensions associated with an institution. The list is limited to 10 campuses or extensions at first, but the user has the option to expand the full list with the "view all" button. After clicking "view all" the user can collapse the list back to the original 10 by clicking "view less". Clicking this button should also adjust the user's view so that they see the School locations section. Currently, the user's view is the bottom of the page.

![ezgif-4-e55f0625c908.gif](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/f2635bac-9411-45c6-9fc8-25af4c247d47)

## Acceptance Criteria:
1. When the user clicks "view less" the list is collapsed and the focus is shifted back to the school locations section

See AC \#6 of the [original implementation story](https://github.com/department-of-veterans-affairs/va.gov-team/issues/4383)

**Comment by sonntag-adam** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/12128

**Comment by sonntag-adam** [comment]
![image.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/26d77086-c3d4-43f0-9248-5b14eac83573)

**Comment by sonntag-adam** [comment]
![7546](https://user-images.githubusercontent.com/48804582/78673065-999c7900-78af-11ea-94c1-8569ce49dfc6.gif)

**Comment by sonntag-adam** [comment]
In staging, closing bug.
