### ISSUE TITLE
Exclude Captain James A. Lovell clinics from Online Scheduling

### ISSUE THREAD

**Issue by JRRoof** [department-of-veterans-affairs/va.gov-team#75460]
## Description
Captain James A. Lovell facility (556) in North Chicago, Illinois will be migrating to Oracle Health (Cerner) EHR on March 9, 2024.  As part of the migration process they would like the creation of appointment requests and direct scheduled appointments to be disabled in VA Online Scheduling 30 days prior to the migration (February 8, 2024).  

This will require changes at the vets-api layer.  When a veteran indicates the Type of Care they require the corresponding Service ID is submitted in order to get a list of clinics.  When the `va_online_scheduling_booking_exclusion` feature flag is enabled, then any clinics starting with 556 will be filtered out and not displayed to the user.  By not being able to select 556 clinics, this will prevent veterans from creating or requesting appointments.  

---

## Acceptance Criteria
Background: the `va_online_scheduling_booking_exclusion` toggle is on

Given a veteran
When trying to request or direct schedule an appointment
Then after selecting type of care all clinics starting with 556 will not be displayed
 
### Design Assets
No changes to the UI design of the page or error messages required.

## Definition of Done
- [x] All acceptance criteria are met
- [x] Documentation is updated
- [x] Mobile team has been informed of these changes

**Comment by melissa-lefevre** [comment]
understand we need a quick turn around but also seems like removing the facility from the list would be less than ideal. Realistically how feasible would it be to send users who select any clinics starting with 556 to a screen where we give them a phone number of the facility to call? Here is a link to the design file
It is basically using the screen for Oracle Health facilities but without a link to schedule on the OH portal.  I only have Main phone but clinic phone would be great if possible. Here is the screen that I was thinking we could send them to: <img width="516" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUU0QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a721cd7e058cd724e6bfdb10b6a529bf2374a70a/Screenshot%202024-02-06%20at%2012.51.45%20PM.png" alt="Screenshot 2024-02-06 at 12.51.45 PM.png" />

**Comment by ajmagdub** [comment]
[PR-15472](https://github.com/department-of-veterans-affairs/vets-api/pull/15472)

**Comment by ajmagdub** [comment]
The code has been moved to production. To ensure it works properly, a user who can typically schedule appointments at Lovell needs to attempt to schedule an appointment and confirm that Lovell sites are not available as options. This can be achieved by enabling the feature toggle "va_online_scheduling_booking_exclusion" for that user in production.

**Comment by ldelacosta** [comment]
Flipper has been added. Closing out the ticket. 

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWxUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--50cb635193fc58eb6bda329571bdd2ec277775cc/Screenshot%202024-02-13%20at%208.36.20%20AM.png" alt="Screenshot 2024-02-13 at 8.36.20 AM.png" />

**Comment by ldelacosta** [comment]
The design works as expected. Validated the work with a staff Veteran in production. A [new ticket](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/77055) is created to add additional logic for users only registered at one site (Lovell) and users registered at multiple sites including Lovell. Closing out this ticket and will work on part two in #77055.
