### ISSUE TITLE
Discuss undoing recent Scroll Viewport updates

### ISSUE THREAD

**Issue by BSmolensky** [department-of-veterans-affairs/va.gov-team#75465]
Not too long ago, a couple themes were added to the Platform Website via Scroll viewport that don't necessarily improve the user experience or the functionality of the site. As a team, we agreed to discuss undoing these changes. This ticket is there as a reminder. 

NOTE 1: There is a chance that certain functionality (namely: TOC and smart links) could have been negatively impacted by the updates. See [this ticket](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/75466) for more info on that. 

NOTE 2: If we decide to roll back the right-side menu theme, we must rewrite the intro to this page: https://depo-platform-documentation.scrollhelp.site/support/what-we-can-help-with-platform-support -- because it specifically calls out the right-side menu. (this was done because both TOC and smart links would not work).

**Comment by jknipes** [comment]
We are fairly certain the 3 recent updates to PW did not affect table of contents or smart links:

- Pagination
- Vertical Search Filters
- Content Source Filter

**Comment by jknipes** [comment]
Based on information discovered and recorded in comments in [ticket 75466](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/75466) we can close this ticket
