### ISSUE TITLE
[FE][BE] Create all Task Tickets & Point

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#75463]
## Goal
We need to define all of the work necessary for this Epic and be able to provide a relatively accurate timeline for Kay. 

NOTE: we will need to call new VA Notify template; please refer here for the new template IDs for each of the 3 scenarios
https://dvagov.sharepoint.com/:w:/s/VANotify-VEText/EZIrTO3T99tDu5YBtXc7h6QBLkV1f95tXXTCzF0-miCVOA?e=TDy7Pu

## Tasks
- [FE] Create all Task Tickets & Point
- [BE] Create all Task Tickets & Point

**Comment by randomsync** [comment]
This is complete from BE side. 
1. We discussed that we won't need to use the new templates. We'd be able to provide the metrics for check-ins/travel claims filing for OH sites through DataDog.
2. vets-website will pass in a parameter for vets-api low-auth sessions controller to distinguish between check-ins through CHIP/VistA and check-ins for travel claims for OH sites.
