### ISSUE TITLE
Create onboarding checklist for VSA onboarding

### ISSUE THREAD

**Issue by smoonpeyes** [department-of-veterans-affairs/va.gov-team#755]
## Goal
Create onboarding checklist to be used to guide the VSA onboarding experience.

Leah has started a Google doc here: https://docs.google.com/document/d/1sdJ8KBhbw-rpOSSqzMJ2_kSi4jtVOPlXrfMLmnaeGLc/edit?usp=sharing

## Definition of Done
- [x] Checklist created
- [x] Checklist reviewed and approved by DSVA leadership
- [x] Checklist is accessible on the va.gov-team repo

**Comment by peterhill-oddball** [comment]
1. Added some thoughts about engineers setting up their local environments.
2. Broke out local set up into discrete steps to be checked off

**Comment by smoonpeyes** [comment]
We created an onboarding epic template that includes the onboarding checklist:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/onboarding-epic.md
