### ISSUE TITLE
Update/Addition to documentation about non-compatible file and folder names

### ISSUE THREAD

**Issue by little-oddball** [department-of-veterans-affairs/va.gov-team#75519]
### Request type

- [X] Writing new documentation
- [ ] Updating previously published documentation
- [ ] Reviewing recently written, never-before-published drafts

### Number of docs

1

### Approvals

No

### Embedded media

- [ ] Screenshot(s)
- [ ] Diagram(s)
- [ ] Video(s)

### Audience

- [X] Developers
- [X] Designers and researchers
- [X] Product managers
- [ ] Other

### Anything else?

This item was raised by an OCTO PO and requested that we look to find a place to document for others. Based on that, making a request to the Content Team to aid in support of finding a good place to add this content for users to have access to.

[Here](https://dsva.slack.com/archives/CE4304QPK/p1707171463655899) is the think to the DSVA Slack thread. Overall, we just want to add a blurb that discusses GitHub repositories and compatible file and folder names. The text to pull from etc. is:

> When adding to our GitHub repositories, to avoid using file and folder names which aren't compatible with both Windows and macOS. I know it's tough because most of us are using only one or the other and also some of us upload files directory into repositories via the GitHub web interface rather than committing and pushing from our desktops.
> In particular, please avoid the following:
> 
> - file names containing question marks
> - names containing colons
> - names containing pipe symbols (|)
> - names ending with space
> - names ending with period
> - file paths longer than 256 characters, with a healthy margin for error since the limit on Windows includes the full path of each file starting with the drive letter, i.e., the path in the repository plus the path of the directory it's checked out into needs to be less than 256
> 
> Also, though it won't strictly speaking break the OS, it's a good idea to avoid file names starting with space.

**Comment by little-oddball** [comment]
This is reference made to [this](https://department-of-veterans-affairs.github.io/github-handbook/) documentation (the GH Handbook) as well. Not sure if/what makes sense to reference/leverage there.

**Comment by jknipes** [comment]
@little-oddball thank you for flagging this. We'll take a look, and determine the best course of action for this page, and will work to get any updates reflected on the website.
We will provide further updates in this ticket. Please feel free to reach out if there are any questions.

**Comment by jknipes** [comment]
work will be documented in ticket [79061](https://github.com/department-of-veterans-affairs/va.gov-team/issues/79061)

**Comment by jknipes** [comment]
@little-oddball work is complete, we are closing this ticket
