### ISSUE TITLE
Prevent Cancellations at Captain James A. Lovell clinics

### ISSUE THREAD

**Issue by JRRoof** [department-of-veterans-affairs/va.gov-team#75512]
## Description
Captain James A. Lovell facility (556) in North Chicago, Illinois will be migrating to Oracle Health (Cerner) EHR on March 9, 2024.  As part of the migration process they would like the cancellation of appointments to be disabled in VA Online Scheduling 8 days prior to the migration (March 1, 2024).  

This will require changes at the vets-api layer.  When a veteran is viewing the details of any type of appointment (Upcoming, Request, or Past) scheduled for a clinic starting with ID 556, the veteran should be prevented from cancelling that appointment when the `va_online_scheduling_cancellation_exclusion` feature flag is enabled.  A message should be displayed directing the veteran to call the clinic to cancel the appointment.

---

## Acceptance Criteria
Background: the `va_online_scheduling_cancellation_exclusion` toggle is on

Given a veteran
When viewing the details of an Upcoming, Past appointment or an appointment Request
Then the cancellation button should be disabled for all clinics starting with 556
 
### Design Assets
No changes to the UI design of the page or error messages required.

## Definition of Done
- [x] All acceptance criteria are met
- [x] Documentation is updated
- [x] Mobile team has been informed of these changes

---

**Comment by ldelacosta** [comment]
@simiadebowale - please add the technical notes.

**Comment by ajmagdub** [comment]
@simiadebowale Corey and I split up the Lovell site work. I took the removal of Lovell sites from being booked, and Corey took the Cancellation portion.
cc: @cferris32

**Comment by ldelacosta** [comment]
We will wait until this work is completed to validate all the changes we have implemented for the Lovell migration. 

Including #75454, #75293 and #75510

**Comment by outerpress** [comment]
@simiadebowale @cferris32 @JRRoof what path did you take for the cancelation experience? Will clicking the cancelation return an error message? Or will we display the standard "Need to make changes?" alert in place of the cancelation button?

**Comment by ajmagdub** [comment]
@simiadebowale talked to Corey, and since I have the extra cycles, I'll pick this up. Also, would setting the `cancellable` attribute to false work in this case, as we do for other types of appointments?

**Comment by JRRoof** [comment]
@simiadebowale @ajmagdub - Display the standard "Need to make a change" message, not an error, when the cancellable flag is enabled.

**Comment by simiadebowale** [comment]
@ajmagdub - to do this, we will need to set the `cancellable` field to false.

**Comment by ajmagdub** [comment]
@simiadebowale That's what I was planning to implement, if it works for the web site.

**Comment by outerpress** [comment]
@simiadebowale @ajmagdub thanks - what happens with requests in that case?

**Comment by ajmagdub** [comment]
Code completed and merged. It will go into production on Feb. 15, 2024's deployment. This is behind the **va_online_scheduling_cancellation_exclusion** feature toggle which will need to be enabled in production during validation and when cancellation exclusion is required for Lovell cutover.

**Comment by ldelacosta** [comment]
This has been validated from a staff Veteran in production. No new issues reported. Closing out the ticket.
