### ISSUE TITLE
Remediate modern XX date bugs

### ISSUE THREAD

**Issue by SamStuckey** [department-of-veterans-affairs/va.gov-team#75517]

**Comment by SamStuckey** [comment]
BLOCKED: these belong to the same user, who seems to have like 20 more in progress forms.  going to hold off a few days to remediate when the rest come in

**Comment by sortizsh** [comment]
fix them and push them through

**Comment by SamStuckey** [comment]
The old fix of removing the problematic date and resubmitting these via the backup path isn't working.  they are returning a validation error.  The work in this ticket is now to debug resubmission and see if remediation via this method is possible

**Comment by SamStuckey** [comment]
All the affected IDS:
[2524937, 2531844, 2531848, 2534475, 2538775, 2539275, 2539281, 2539285, 2539375, 2539432, 2539438, 2539631, 2548521, 2553934, 2563000, 2563011, 2563035, 2566894, 2577435, 2577493, 2596454]
