### ISSUE TITLE
Update MPI docs on scroll help site

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#75528]
doc is here: https://depo-platform-documentation.scrollhelp.site/developer-docs/mvi

**Comment by bosawt** [comment]
Here are the changes recommended by Lauren Conrad:

1. Call it MPI and change MVI to MPI but also mention that it used to be called MVI or "Master Veteran Index" if someone searches for that.
2. Delete the Monitoring section and both links beneath it.
3. Add a note under both Integration Endpoints and Trust Chains saying “You must have access to the internal VA network to access all the links below.”
4. Delete the contacts history
5. Have you guys update the Escalation Process
6. Possibly make some other updates that I might not be aware need to be updated but that you know about.
