### ISSUE TITLE
Add VADS Footer to Intake and Proofing Screens

### ISSUE THREAD

**Issue by skirkman16** [department-of-veterans-affairs/va.gov-team#75525]
**Problem** 
We would like to add a consistent footer to our application as a place to eventually provide information, Terms of Use, Privacy Policy, and application support. The design team identified a footer from the VA Design System that meets our needs. 

Only the landing pages on [Figma](https://www.figma.com/file/PfrWKmxiQ5RjChwx6I18QE/IPP-Prototypes?type=design&node-id=2576%3A2274&mode=design&t=HxFpMfp1fkZRw9nD-1) represent the changes with the footer, but this footer should be applied to all screens for our IPP app (intake and proofing).

Refer to the [minimal footer ](https://design.va.gov/components/footer/footer-minimal)documentation for more info on the component.

**User Story**
As a Veteran or Proofing Agent, when I view the IPP application, I need to see consistent information about the application so I know it's legit.

**Acceptance Criteria**
GIVEN I am accessing the Veteran Intake Application
OR the Proofing Agent Application
WHEN I am viewing any of the screens
THEN I see a footer at the bottom of each screen that gives me a some information about the application

Notes
- [ ] Footer has been applied to all screens and is visible in Vercel
- [ ] Send Link from Vercel to CEDAR team for review when complete

**Comment by SophiaPhilipMO** [comment]
@mateoclarke @moanu404 updated landing page. Footer is up to date. Adjusted background of landing page to white color to ensure consistent brand experience[Uploading... Intake Option 4.png]

**Comment by SophiaPhilipMO** [comment]
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/139910415/3395f531-abd4-4835-9de8-a64b6dd52de3)

**Comment by SophiaPhilipMO** [comment]
Tagged you @mateoclarke in a comment in [here](https://www.figma.com/file/PfrWKmxiQ5RjChwx6I18QE/IPP-Prototypes?type=design&node-id=2576%3A2274&mode=design&t=KS1xXnsMGepsKAer-1)

**Comment by mateoclarke** [comment]
I found it much easier to implement the Footer manually instead of trying to add the VADS to the project with all its associated dependencies and potential namespace conflicts with Logingov Design System and USWDS.

Also, we haven't been deploying to Vercel since it breaks with our database requirements. If a functional demo is needed we can either make a Loom, screenshare walkthrough or share LHDI test app URL (once that becomes available).
