### ISSUE TITLE
SOCKS access for Peri McLaren

### ISSUE THREAD

**Issue by pmclaren19** [department-of-veterans-affairs/va.gov-team#75536]
### Your Name

Peri McLaren

### Your Email

peri.mclaren@adhocteam.us

### Your Role and Team

Software Engineer, Benefit Management Tools

### Product Manager (PM) name and email

Jacob Worrell

### Product Owner (PO) name and email

Zach Goldfine

### Access Type Requesting

developers

### Public SSH Key

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILDLI+f61Yth7y9yAUkQzZVVVWvs92n8aeG0qF2HXGkK peri.mclaren@adhocteam.us

### E-QIP Transmittal Confirmation

I dont think I have a email that says E-Qip. Heres an email showing that I got va email access and access to citrix

![Screenshot 2024-02-06 at 11 50 53 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/141954992/dbe88e70-bdf5-45e1-a264-80c9a3069292)

** Update: They changed the email to be called E-App heres is a screen shot of that email 
![Screenshot 2024-02-09 at 3 07 57 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/141954992/a443c476-a843-4e60-ab95-54f639c95156)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by ph-One** [comment]
@pmclaren19 can you please scan your emails [again] to see if you have received your E-QIP transmittal notice, yet?

**Comment by pmclaren19** [comment]
Hey @ph-One ,
Update update the ticket! 

** Update: They changed the email to be called E-APP its no longer called E-QIP heres is a screen shot of that email 
![Screenshot 2024-02-09 at 3 07 57 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/141954992/a443c476-a843-4e60-ab95-54f639c95156)

**Comment by ph-One** [comment]
SOCKS access granted
