### ISSUE TITLE
UX: account-related alerts (LOA1, not-registered) for tool pages

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#75533]
### User story

As a user with an LOA1 account or no facility registration, I want to be informed of my situation consistently across all MHV health tool pages I might navigate to, so that I can't have a bad experience by entering MHV through a "side door."

As a Cartographers team member, I want to get tool teams' buy-in on how their UX should handle LOA1 and not-registered accounts, so that we can implement on their behalf.

### Notes
- Similar situation/pattern to page-not-found work, where we got product owners' buy-in to implement for them
- platform component for "LOA1": `src/platform/user/authorization/components/IdentityNotVerified.jsx`
- UX questions include: 
  - does it display on child pages?
  - in terms of hiding functionality, can we follow the same UI pattern on each app as we did with our downtime notifications? i.e., hide most functionality but keep the H1.
- the list of apps in the ACs came from Carlos's 404 work; team needs to determine if all the apps need alerts

Possible tasks:
- Consult with Sara/IA
- Validated UX designs with tool owners

## Acceptance criteria

- Evaluated UI for each of the following health-care apps and recommended a UX, depicting if appropriate both LOA1 (Verify your identity) and non-registered user alerts:
  - [x] After Visit Summary (`/my-health/medical-records/summaries-and-notes/visit-summary`)
  - [x] Update Benefits form (`/my-health/update-benefits-information-form-10-10ezr`)
  - [x] Medical Records (`/my-health/medical-records`)
  - [x] Medications (`/my-health/medications`)
  - [x] Secure messages (`/my-health/secure-messages`)
  - [x] Appointments (`/my-health/appointments`)
  - [x] Supply reordering (currently `/health-care/order-hearing-aid-or-CPAP-supplies-form`, but migrating to `/my-health/order-hearing-aid-or-cpap-supplies-form`)
Note the Landing page already implements this functionality

- Validated UX designs with tool owners
LOA3 no access plan: no tool landing pages will be visible to user w/o healthcare access - those users will be route guarded and sent to the My HealtheVet landing page where they will see a "no access" alert. 
  - [x] Medical Records (`/my-health/medical-records`)
    - After Visit Summary (`/my-health/medical-records/summaries-and-notes/visit-summary`) - **child page, will be covered by MR implementation** 
  - [x] Medications (`/my-health/medications`)
  - [x] Secure messages (`/my-health/secure-messages`)
  - [x] Appointments (`/my-health/appointments`)

LOA1 identity not verified alerts need to be segmented by credential type & this work is still in progress.

 
Needs the alert on entry points to the form, not on the form:
  - Supply reordering (currently `/health-care/order-hearing-aid-or-CPAP-supplies-form`, but migrating to `/my-health/order-hearing-aid-or-cpap-supplies-form`)
  - Update Benefits form (`/my-health/update-benefits-information-form-10-10ezr`)

- Consult with CAIA 
  - [x] Notify IA team @kristinoletmuskat @jennymayoco @mnorthuis of the plan to notify LOA1 + LOA2 users to verify their identity if they get to these forms: **10-10EZ** or **CPAP/hearing aid battery supply re-order form**. They may want to ensure the "verify your identity" alert displays for those users on the benefit hub entry points to those forms. 
 
## Implementation Notes

Create a utility function called AuthGuard which is a route guard that protects routes from unauthorized access based on the user's level of access (LOA1). It determines if the user has a verified account by utilizing the isLOA1 selector from the Redux store.

1. The AuthGuard component accepts a single prop called children, which represents the child components or routes that should be rendered if the user is authorized.
2. Inside the component, the useSelector hook from the react-redux library is used to retrieve the value of the isLOA1 selector from the Redux store. This selector indicates whether the user has a lower level of access (LOA1) and an unverified account.
3. The isUnverified variable is assigned the value returned by the isLOA1 selector.
4. An if statement is used to check the value of isUnverified. If it is true, indicating that the user has an unverified account, the component returns a <Redirect> component from the react-router, redirecting the user to the "/my-health" route.
5. If isUnverified is false, meaning the user has a verified account, the AuthGuard component returns the children prop, allowing the child components or routes to be rendered.

To use the AuthGuard component, wrap the desired routes or components with it. If the user has an unverified account (LOA1), they will be redirected to the "/my-health" route. Otherwise, the wrapped routes or components will be rendered as normal.

**Comment by wesrowe** [comment]
note from planning on 2/8: if we do take the work on ourselves, we should split this ticket into a couple pieces, e.g., by type of alert or by tool.

**Comment by wesrowe** [comment]
I confirmed that My VA doesn't need this work. It already hides health tools for non-registered users, and displays a "Verify" alert for LOA1 users.

**Comment by sterkenburgsara** [comment]
@keithcheung828 @wesrowe My $.02 would be to prioritize implementing this on the 4 tool-level landing pages, and not go deeper than that unless we see issues down the road. I can't imagine that someone w/o an ID-proofed account would be likely to have a deep-link to the experience (i.e. link to "inbox" or "after-visit summary" pages) and come in that way. 

I would not implement this alert for the CPAP supplies form or the 10-10EZ form from our end, since the entry points to those forms are on the main landing page, and that page already has this design implemented. 

**Special consideration**: from the My HealtheVet landing page, the CPAP supply re-order form is only visible for LOA3 users, so I'm pretty confident that LOA1/2 users won't ever see that form. But the LOA1/2 users could in theory find the 10-10EZ form - it is visible on all of our landing page designs (in those bottom 3 columns), so we could revisit later if we see issues with that form once it launches to 100%. As an added pre-caution, I'd check-in with CAIA on this work & ask them to ensure that the benefit hub entry points for those forms display this "verify your identity" alert. I added that to the task-list for this ticket. cc @alexseelig @kristinoletmuskat @mnorthuis

**Comment by wesrowe** [comment]
Per discussion in standup, I edited the ticket and ACs to clarify that a recommendation needs to be made for all apps on the list. (But not necessarily an alert UX if that's deemed not appropriate.)

**Comment by sterkenburgsara** [comment]
Update: noticed that in production we have these alerts for My HealtheVet basic users coming in with LOA2 accounts. This "verify your identity" alert for MHV users doesn't make sense, and the alert heading text reads strangely. [See related Slack thread with CAIA here](https://dsva.slack.com/archives/C01K37HRUAH/p1709333393249289). We should only implement this design for ID.me and Login.gov LOA1 users and I'll work with CAIA how to determine a solution for MHV basic & DS Logon accounts.

**Comment by sterkenburgsara** [comment]
"Verify your identity" alert in prod for MyHealtheVet basic accounts (we should roll this back):

<img width="938" alt="Screenshot 2024-03-01 at 4 35 41 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/115033532/e7479e29-20a8-4372-9636-39c27a766e35">

**Comment by sterkenburgsara** [comment]
Updates to design [here](https://www.figma.com/file/CAChU51fWYMZsgDR5RXeSc/MHV-Landing-Page?type=design&node-id=450-9421&mode=design&t=gNfEVv4uhf6vwh6i-0)

**Comment by sterkenburgsara** [comment]
Follow-on work for devs: 
* update alert to v3 design (green background) and only implement for ID.me or Login.gov credentials. This means rolling back this design in prod for any users with non-LOA3 My HealtheVet login credentials. There is no concept of unverified DS Logon accounts, so that credential shouldn't be a factor in this work.

**Comment by sterkenburgsara** [comment]
Related / adjacent info: 

* Design system ticket filed for this alert as an experimental pattern on VA.gov: [ticket here](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2556)
* Platform feature request ticket filed for collaboration cycle to evaluate auth apps for LOA1 users at staging review: [ticket here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/77895)

**Comment by sterkenburgsara** [comment]
@jzucadi could you add implementation notes that we discussed re: having app teams implement these alerts on their landing page & have all child pages fetch it from there (ensuring that the H1 is still in place)? 

@wesrowe how should I go about asking devs to implement the "follow-on work" articulated 2 comments up?

**Comment by sterkenburgsara** [comment]
@wesrowe also, MyVA doesn't indicate which sign-in credential the user has, which is an important difference that our design does include. Did you ask them if this update is interesting or valuable to them?

**Comment by sterkenburgsara** [comment]
@LynneJohnson224 almost done w/ this - but haven't gotten verification from stakeholders yet, so this will roll over into the next sprint. Also need to finalize LOA1 plan for My HealtheVet sign-in credential, but that work was offloaded to an adjacent ticket, I believe.

**Comment by wesrowe** [comment]
update: Sara got sign-off from MHV stakeholders about using the route-guard idea for un-registered users – i.e. taking any un-registered user from the tool page they tried to access to the MHV landing page with the un-registered alert. Biggest point of discussion was Appointments edge case around claim exams (aka compensation and pension exam).

**Comment by sterkenburgsara** [comment]
Small content update: the first line in this alert needs to read "at least one" in bolded text <img width="1452" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2J6QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1cbc435feda35de02203a70a87fb42c63a09cd5f/Screenshot%202024-03-19%20at%204.21.07%E2%80%AFPM.png" alt="Screenshot 2024-03-19 at 4.21.07 PM.png" />

**Comment by sterkenburgsara** [comment]
Update: @laurwill is seeking approval from Carnetta on alerts. MHV alerts are currently mocked up in Figma here and are ready for implementation upon approval. 

Discussions with Auth experience team happening 3/27, and presentation with @laurwill and CAIA on the abstracted versions of these alerts (for wider VA.gov community) to design system council scheduled for Thursday 3/28.

**Comment by wesrowe** [comment]
Blockers to this ticket now include revision of the alert content per various discussions. [Huge slack thread from 5/31](https://dsva.slack.com/archives/C0581MN69TJ/p1717185477450519) is most relevant. Also [this one](https://dsva.slack.com/archives/C0581MN69TJ/p1717440217218509).

**Comment by wesrowe** [comment]
Aaaand, two new stories have been created to make sure we get our ducks in a row:
- #84518 (UX design for "no MHV access" alert)
- #84522 (evaluate "verify" alerts
- At least one more UX ticket will come out of the "verify" bullet above

**Comment by wesrowe** [comment]
@sterkenburgsara @LynneJohnson224, We are paying a lot of attention to this topic currently, and the two stories in the comment above this one carry the work forward. I think there is a lot of good thinking in this ticket which should be reviewed this sprint. But is there value in keeping this ticket open?
