### ISSUE TITLE
Refactor uploads controller

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#75540]
Refactor uploads controller for cleanliness. 

Definition of done:
- better organized
- easier to read

**Comment by balexandr** [comment]
I think we may end up deleting this ticket as https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/72706 aims to move the IVC logic to it's own controller.
