### ISSUE TITLE
Configure staging AWS S3 bucket from platform so it is accessible outside of AWS ecosystem

### ISSUE THREAD

**Issue by cloudmagic80** [department-of-veterans-affairs/va.gov-team#75551]
As an AWS S3 user, I need to upload files into AWS S3 from outside the AWS ecosystem (ie CLI and Console). 

Definition of Done: Receive a 200 when you upload a PDF from localhost via Vets-API to AWS S3 Staging env

**Comment by dhill802** [comment]
@baltes  

Blocked status. Note from vfs-platform-support

Quick update and plan moving forward:
1. *Finalize Prod Setup*: Make sure the S3 bucket is all set for production. This includes tweaking security settings and ensuring seamless VA applicant uploads.
2. *Security Check*: Gonna run a security sweep to ensure everything's tight and right, especially with public access.
3. *Staging Test*: We'll hammer out any kinks in staging first, ensuring uploads and integrations are smooth.
4. *Doc & Train*: I'll document the setup and share some quick guides so we're all on the same page.
5. *Monitor & Support Plan*: Setting up monitoring for any unusual activity and will have a quick response plan ready.
Note: My gov cloud access is a bit of a snag right now, but I've pinged a few folks, so I should be rolling soon. Will keep you in the loop!

**Comment by cloudmagic80** [comment]
I was able to access AWS staging via postman.

**Comment by cloudmagic80** [comment]
@balexandr  Do you show me how you set up the env file for S3? I tried it on my but I get 
`Rails -- SSO: INVALID SESSION -- { :user_uuid => nil, :sso_cookie_contents => nil, :request_host => "localhost" }`

**Comment by cloudmagic80** [comment]
Looks good now. I've added session token to pass on to AWS. End to end testing passes! great job!
