### ISSUE TITLE
My VA toast alert appearing on sign in page

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#7557]
## What happened?
I was signed in to staging.va.gov as vets.gov.user+262@gmail.com and navigated to https://staging.va.gov/sign-in/ in another tab. The bottom toast reading "Check out your new personalized homepage" with a CTA to My VA was present. 

![Screen Shot 2020-04-02 at 8.02.54 PM.png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/d2af42d4-6175-433b-9b9e-edb4c3cbfd5a)

## Steps to Reproduce

1. Sign in to staging.va.gov and see bottom toast
2. Navigate to https://staging.va.gov/sign-in/ in another tab

## Desired behavior
I think we should prevent the toast from showing up on the sign-in page. I don't think this is a super severe bug - but it does seem odd for a message to see a personalized homepage to show up on a sign-in page.

**Comment by hinzed1127** [comment]
The personalization banner has been deprecated, so this is no longer an issue.
