### ISSUE TITLE
Research and possibly fix primary submission error: form.submit.noRetryError

### ISSUE THREAD

**Issue by tblackwe** [department-of-veterans-affairs/va.gov-team#75570]
Research and possibly remediate primary submission failure 
- form.submit.noRetryError
This is a generic error, so these may not all be the same issue.

## Acceptance Criteria
- [ ] Determine root cause of errors
- One of the following
  - [ ] New ticket created to fix issue
  - [ ] PR Opened to Fix issue
  - [ ] Comments on this ticket describing why it is not fixable at this time

**Comment by tblackwe** [comment]
[Datadog query](https://vagov.ddog-gov.com/logs?query=%40named_tags.class%3A%22EVSS%3A%3ADisabilityCompensationForm%3A%3ASubmitForm526AllClaim%22%20%40level%3Aerror%20%40payload.submission_id%3A%282425396%20OR%202425489%20OR%202426682%20OR%202426696%20OR%202427558%20OR%202427574%20OR%202427579%20OR%202427581%20OR%202427589%20OR%202428012%20OR%202428553%20OR%202428965%20OR%202428979%20OR%202429013%20OR%202429077%20OR%202429284%20OR%202429301%20OR%202430008%20OR%202430010%20OR%202430038%20OR%202430049%20OR%202430053%20OR%202430405%20OR%202430413%20OR%202431941%20OR%202431942%20OR%202431944%20OR%202431948%20OR%202431964%20OR%202431973%20OR%202432060%20OR%202432078%20OR%202432106%20OR%202432119%20OR%202432150%20OR%202432162%20OR%202432191%20OR%202432270%20OR%202432300%20OR%202432308%20OR%202432337%20OR%202432341%20OR%202432699%20OR%202432709%20OR%202432724%20OR%202432732%20OR%202432744%20OR%202432759%20OR%202432767%20OR%202432771%20OR%202433623%20OR%202434091%20OR%202434340%20OR%202434937%20OR%202434946%20OR%202434948%20OR%202435047%20OR%202435054%20OR%202435747%20OR%202435756%20OR%202435786%20OR%202435809%20OR%202435816%20OR%202436407%20OR%202436475%20OR%202436524%20OR%202436680%20OR%202437184%20OR%202437209%20OR%202437214%20OR%202437219%20OR%202437371%20OR%202437377%20OR%202437745%20OR%202438251%20OR%202439023%20OR%202439483%20OR%202439491%20OR%202439494%20OR%202439496%20OR%202439505%20OR%202439513%20OR%202439525%20OR%202439562%20OR%202439581%20OR%202439738%20OR%202439855%20OR%202440095%20OR%202440109%20OR%202440115%20OR%202440741%20OR%202440747%20OR%202440806%20OR%202441291%20OR%202441751%20OR%202442868%20OR%202442887%20OR%202442890%20OR%202442895%20OR%202442899%20OR%202442972%20OR%202447922%20OR%202448593%20OR%202450090%20OR%202452057%20OR%202452885%20OR%202457202%20OR%202457214%20OR%202459240%20OR%202459243%20OR%202459247%20OR%202459259%20OR%202459345%20OR%202459846%20OR%202461448%20OR%202461454%20OR%202461460%20OR%202461472%20OR%202461479%20OR%202461499%20OR%202476445%20OR%202477809%20OR%202478547%20OR%202478561%20OR%202478582%20OR%202480267%20OR%202480271%20OR%202481254%20OR%202481271%20OR%202482226%20OR%202482291%20OR%202483917%20OR%202483923%20OR%202483929%20OR%202483947%20OR%202484995%20OR%202485044%20OR%202485046%20OR%202485050%20OR%202485056%20OR%202485059%20OR%202485282%20OR%202485710%20OR%202485805%20OR%202486084%20OR%202486091%20OR%202486133%20OR%202486142%20OR%202486152%20OR%202486175%20OR%202486184%20OR%202486289%20OR%202487152%20OR%202487158%20OR%202487229%20OR%202487283%20OR%202487304%20OR%202489237%20OR%202489241%20OR%202489247%20OR%202489323%20OR%202490817%20OR%202490830%20OR%202490895%20OR%202490938%20OR%202492668%20OR%202492800%20OR%202493536%20OR%202493543%20OR%202493580%20OR%202493645%20OR%202493656%20OR%202493666%20OR%202493671%20OR%202493720%20OR%202494901%20OR%202495198%20OR%202495204%20OR%202495223%20OR%202495234%20OR%202497805%20OR%202500172%20OR%202500182%20OR%202501307%20OR%202501357%20OR%202503743%20OR%202503744%20OR%202503748%20OR%202503750%20OR%202503751%20OR%202503755%20OR%202503915%20OR%202504519%20OR%202504557%20OR%202504562%20OR%202504571%20OR%202504845%20OR%202504960%20OR%202504970%20OR%202505358%20OR%202508233%20OR%202508657%20OR%202508666%20OR%202508722%20OR%202508754%20OR%202509096%20OR%202511322%20OR%202511330%20OR%202511354%20OR%202513017%20OR%202513019%20OR%202513030%20OR%202513769%20OR%202513770%20OR%202513772%20OR%202514241%20OR%202514242%20OR%202514244%20OR%202514250%20OR%202515410%20OR%202516324%20OR%202516327%20OR%202516338%20OR%202516349%20OR%202516355%20OR%202516362%20OR%202516363%20OR%202516609%20OR%202516818%20OR%202516832%20OR%202517890%20OR%202518139%20OR%202518373%20OR%202518377%20OR%202518383%20OR%202518392%20OR%202518395%20OR%202518435%20OR%202518875%20OR%202518879%20OR%202518881%20OR%202520922%20OR%202522490%20OR%202522503%20OR%202522505%20OR%202522773%20OR%202523490%20OR%202523622%20OR%202523631%20OR%202523650%20OR%202525134%20OR%202525146%20OR%202525148%20OR%202525150%20OR%202525155%20OR%202525163%20OR%202525466%20OR%202525537%20OR%202525566%20OR%202526179%20OR%202526189%20OR%202526194%20OR%202526250%20OR%202526338%20OR%202526990%20OR%202527062%20OR%202528778%20OR%202528783%20OR%202531707%20OR%202531740%20OR%202536212%20OR%202537934%20OR%202538862%20OR%202538866%20OR%202538869%20OR%202538934%20OR%202538985%20OR%202540004%20OR%202541390%20OR%202541439%20OR%202541702%20OR%202542939%20OR%202542943%20OR%202542944%20OR%202542949%20OR%202543232%20OR%202543261%20OR%202543277%20OR%202543286%20OR%202543297%20OR%202543305%20OR%202543333%20OR%202543386%20OR%202543392%20OR%202543399%20OR%202543410%20OR%202543425%20OR%202543681%20OR%202543682%20OR%202543735%20OR%202544870%20OR%202544879%20OR%202544886%20OR%202545105%20OR%202545118%20OR%202546571%20OR%202546939%20OR%202546951%20OR%202547228%20OR%202548117%20OR%202548323%20OR%202548324%20OR%202548327%20OR%202548332%20OR%202548354%20OR%202548363%20OR%202548367%20OR%202548376%20OR%202548440%20OR%202548670%20OR%202548675%20OR%202548704%20OR%202549338%20OR%202550769%20OR%202550774%20OR%202552475%20OR%202552480%20OR%202552489%20OR%202552586%20OR%202552592%20OR%202552595%20OR%202552610%20OR%202552658%20OR%202552904%20OR%202553547%20OR%202553555%20OR%202553565%20OR%202553590%20OR%202554760%20OR%202554857%20OR%202554973%20OR%202555575%20OR%202555632%20OR%202557273%20OR%202563339%20OR%202565086%20OR%202565098%20OR%202565105%20OR%202565109%20OR%202565118%20OR%202565125%20OR%202565892%20OR%202565898%20OR%202565907%20OR%202565909%20OR%202566791%20OR%202566803%20OR%202566962%20OR%202567663%20OR%202567666%20OR%202567673%20OR%202567689%20OR%202567697%20OR%202568380%20OR%202568577%20OR%202569019%20OR%202569281%20OR%202569294%20OR%202569295%20OR%202569302%20OR%202569329%20OR%202569505%20OR%202569564%20OR%202570037%20OR%202570574%20OR%202570583%20OR%202570587%20OR%202570887%20OR%202570898%20OR%202570913%20OR%202570936%20OR%202570951%20OR%202571880%20OR%202573223%20OR%202574924%20OR%202574938%20OR%202577673%20OR%202578744%20OR%202578749%20OR%202578758%29%20&cols=host%2Cservice%2C%40payload.error_message%2C%40payload.submission_id&context_event=AY2JIxEsAAB1aZOJsTXH6QAn&index=%2A&messageDisplay=inline&refresh_mode=paused&storage=online_archives&stream_sort=time%2Cdesc&viz=&from_ts=1698811200000&to_ts=1707414600000&live=false

**Comment by SloopKoning** [comment]
I have requested a DataDog account.

**Comment by sortizsh** [comment]
blocked by datadog access

**Comment by freeheeling** [comment]
@tblackwe @sortizsh Claiming this unassigned **To Do** ticket as I have nothing else on deck and @SloopKoning has not reported he's received Datadog access.
