### ISSUE TITLE
Create centralized BenefitsIntakeAPI service

### ISSUE THREAD

**Issue by wayne-weibel** [department-of-veterans-affairs/va.gov-team#75579]
There is not a consolidated api service to BenefitsIntake as there is for BenefitsClaim, BenefitsDocuments, etc in vets-api.  Pension currently uses a separate service created by the Disability team for backup submission of 526 and a metadata validator from SimpleForms team.  This setup is fragile and the validator and current service are not directly compatible.

To alleviate future tech debt and development issues, create an api service similar to BenefitsClaim for BenefitsIntake

Acceptance:

- [x] configuration added for new service in settings.yml - under existing lighthouse entry
- [x] library added in `lib/lighthouse` for `benefits_intake`
- [x] configuration class + unit tests
- [x] metadata validation class + unit tests
- [x] service class + unit tests

**Comment by aplatt-coforma** [comment]
@wayne-weibel - is this related to #75576 Spike: research approaches to consolidating the Pension vets-api code?
