### ISSUE TITLE
Change ITF so that it is triggered at the start of the application

### ISSUE THREAD

**Issue by mjknight50** [department-of-veterans-affairs/va.gov-team#75583]
The 527 form should be changed to handle ITF (Intent to File) in the same way that the 526 form is doing it.

On this page: ` pension/application/527EZ/introduction`
Right below the link saying:  
Apply for Veteran Pension benefits

Add the text:

> By clicking the button to start the disability application, you’ll declare your intent to file. This will reserve a potential effective date for when you could start getting benefits. You have 1 year from the day you submit your intent to file to complete your application.

After the user clicks `Apply for Veteran Pension benefits` we need to call `/veterans/{veteranId}/intent-to-file/{type}` to check if an ITF exists. 

There is a spinner used on 526 that we could copy:
<img width="1360" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelk4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--af83a03e759bafe3a4e8ea0b654e70068551c38f/Screenshot%202024-02-07%20at%203.50.03%E2%80%AFPM.png" alt="Screenshot 2024-02-07 at 3.50.03 PM.png" />

 If it does, we should display the information for that ITF

<img width="867" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeW84QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5759b9e320cf342845fd9846f5685649173a8f00/Screenshot%202024-02-07%20at%203.46.48%E2%80%AFPM.png" alt="Screenshot 2024-02-07 at 3.46.48 PM.png" />

If it does not, we should:
Do a post to` /veteran/{veteranOD}/intent-to-file`

submitting an ITF and then displaying the new information.<img width="1254" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBems4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ef14849a921b5daa7641cda1a9a10bfacbd63f45/Screenshot%202024-02-07%20at%203.50.11%E2%80%AFPM.png" alt="Screenshot 2024-02-07 at 3.50.11 PM.png" />

UPDATE:
There's an proposal written up on github regarding that lists some potential ITF updates https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/engineering_research/ITF_async_proposal.md.

**Comment by mjknight50** [comment]
@mayacoforma - Can you please double check for other pages where you think the ITF text should be added?
For example, I see this on the 526 page: https://staging.va.gov/disability/file-disability-claim-form-21-526ez/introduction

![Screenshot 2024-02-07 at 3 53 54 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/3513353/499a8e1d-eaa8-4ffb-8d05-7b3615de89ac)

**Comment by mjknight50** [comment]
@mayacoforma - If you are satisfied that the design requirements are complete, can you please un-assign yourself and move it to sprint backlog?

**Comment by mayacoforma** [comment]
@mjknight50 Will do!

**Comment by mayacoforma** [comment]
@mjknight50 Thank you for sharing, this looks good to me.

**Comment by mayacoforma** [comment]
@mjknight50 Here are some of the mockups for the IFT that the non-disability team created before it was descoped. 
![Intent to file](https://github.com/department-of-veterans-affairs/va.gov-team/assets/144955233/e1cde7dd-6b32-4634-b0c5-50945fd0f9a4)
![Intent to file (dropdown open)](https://github.com/department-of-veterans-affairs/va.gov-team/assets/144955233/2d3f2a29-ae24-4a91-945f-1fb2c00d6e70)

**Comment by mayacoforma** [comment]
@mjknight50 The only place in the flow we planned on putting the IFT was after the intro page.

**Comment by mjknight50** [comment]
Yes, it sits in-between the intro and the first page.  Are you suggesting otherwise?

**Comment by buddhima-coforma** [comment]
Closing this ticket as we have a new one with updated scope here https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/gh/department-of-veterans-affairs/va.gov-team/79926
