### ISSUE TITLE
Track claim/appeal status CTA analytics

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#7558]
## Background
We're tracking analytics for AMA/Decision Review pt. 2 launch. We have CTAs across multiple pages to help Veterans "Track status of your claim or appeal" or "Track status of your appeal".

## Goal
Analytics are tracked on interactions with the CTA. 

---
Reference: [Implementation details from original Analytics Request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7345#issuecomment-608025197).

## Tasks
- [ ]  dataLayer event pushed on each of the pages identified where that button lives.

## Acceptance Criteria
- [ ] Interactions with CTA tracked across AMA pages where CTA lives

### CTA pages
   1. VA decisions reviews and appeals https://www.va.gov/decision-reviews/
    2. After you request a decision review https://www.va.gov/decision-reviews/after-you-request-review/
    3. File a Supplemental Claim with new evidence https://www.va.gov/decision-reviews/supplemental-claim/
    4. Request a Higher-Level Review https://www.va.gov/decision-reviews/higher-level-review/
    5. Request a Board Appeal https://www.va.gov/decision-reviews/board-appeal/
    6. After a Board Appeal ... https://www.va.gov/decision-reviews/board-appeal/after-board-appeal-decision/
    7. Multiple party contested claims https://www.va.gov/decision-reviews/multiple-party-claims/
    8. Fiduciary claims https://www.va.gov/decision-reviews/fiduciary-claims/
    9. Insurance claims https://www.va.gov/decision-reviews/insurance-claims/
---

**Comment by MickinSahni** [comment]
Sprint 19 Planning
- solution approach 
  - Event Listener for exact text on button -- if it changes, it breaks. Can this be pushed up to Drupal?
- It isn't important to track analytics for these CTAs to measure success for DR/AMA pt. 2. We can block this by the other ticket to make those CTAs more consistent
  - Pulling this out into the Backlog

**Comment by jonwehausen** [comment]
Afternoon @MickinSahni , would you be able to provide an update here on where we are getting the dataLayer implemented? Thanks in advance!

**Comment by MickinSahni** [comment]
> Afternoon @MickinSahni , would you be able to provide an update here on where we are getting the dataLayer implemented? Thanks in advance!

Hey Jon, no update yet as it doesn't look like we've prioritized it yet. That sound right, @stephorkandatx?

**Comment by stephorkandatx** [comment]
That is correct at this time, it is still on our to-do list

**Comment by jonwehausen** [comment]
Hi @stephorkandatx,

Was hoping to get an update here on status of getting into staging? 

Thanks,
Jon Wehausen

**Comment by stephorkandatx** [comment]
@jonwehausen we will look at this ticket today in sprint planning. if we have questions or it remains blocked, we'll follow up. thanks!

**Comment by ncksllvn** [comment]
@jonwehausen can you verify in staging that this is working okay when you get the chance?

**Comment by stephorkandatx** [comment]
@jonwehausen have you had a chance to review this in staging?

**Comment by ncksllvn** [comment]
He did, the other ticket is more up-to-date now, https://github.com/department-of-veterans-affairs/va.gov-team/issues/7345#issuecomment-635460629. I'm doing a follow-up PR

**Comment by stephorkandatx** [comment]
PR is ready, just waiting to merge. Will do that today.

**Comment by ncksllvn** [comment]
Hey @jonwehausen are you able to confirm this work is complete when you have a chance?

**Comment by stephorkandatx** [comment]
@jonwehausen I believe we saw analytics coming through - is there additional testing needed before we close this ticket out?

**Comment by stephorkandatx** [comment]
Confirmed with Jon, closing out
