### ISSUE TITLE
Collaborate on best approach for EKS upgrade automation

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#75623]
### Background
As part of our ongoing efforts to enhance the CI/CD processes for the Vets API, we're looking to automate testing within our EKS environment. Currently, there's a lack of standardized testing practices for various objects within our infrastructure, leading to potential disparate solutions. We will want to collaborate on automation standards for EKS cluster testing with the Infrastructure Services Team to settle on the best approach around standardization.

### Objective
The primary goal is to collaborate with the Infrastructure Services Team to establish a set of standardized testing procedures for the Vets API on the EKS cluster. By defining these standards, we aim to streamline future EKS upgrades and testing processes, moving away from manual to automated testing.

### Requirements
- **Identify Testing Needs**: We already have clarity on "what" needs to be tested ([see testing plan](https://vfs.atlassian.net/wiki/spaces/TT1/pages/2837872659/Testing+Plan+for+EKS+Upgrade)). The next step is to define "how" these tests should be conducted in an automated, standardized fashion.
- **Collaboration**: Work closely with the Infrastructure Services Team to leverage their expertise in defining robust testing standards that can be consistently utilized.
- **Standardization**: Avoid ad-hoc or disparate testing solutions by agreeing on a common set of practices and tools for automation.
- **Future-Proofing**: Ensure that the standards and automation set in place are scalable and can easily accommodate future EKS upgrades and enhancements.
- **IDEA** Can we leverage the QA engineers on the Platform?

### Desired Outcome
- A comprehensive set of standards for automated testing within the EKS cluster, specifically tailored to Vets API.
- A clear roadmap for implementing these testing standards, including tooling, processes, and responsibilities.
- Enhanced efficiency and reliability in testing EKS upgrades against the Vets API, minimizing the need for manual intervention.

### Steps Forward
- **Brainstorm**: Collaboratively generate ideas from our team to present to the Infrastructure Services Team (IST), allowing us to seek their insights and feedback.
- **Initial Meeting**: Schedule a kickoff meeting with the Infrastructure Services Team to outline our objectives and gather initial feedback.
- **Requirements Gathering**: Compile a detailed list of testing scenarios, objectives, and existing challenges with the current manual processes.
- **Draft Proposal**: Based on collaboration, draft a proposal outlining the testing standards, including technologies, tools, and methodologies recommended for automation.
- **Review and Approval**: Present the proposal to relevant stakeholders for feedback and approval.
- **Implementation Plan**: Once approved, develop a detailed implementation plan, including timelines, responsibilities, and key milestones.

### Stakeholders
- Infrastructure Services Team
- Vets API Development Team
- QA Engineers 

We're committed to making this transition smooth and ensuring that our automated testing standards are robust, scalable, and aligned with our overall CI/CD objectives for the Vets API on EKS.

**Comment by jennb33** [comment]
Working with @Kshitiz-devops on this proposal as well. Should be ready for internal review by 3/7.

**Comment by LindseySaari** [comment]
This has been sent to our internal team for review and comment before shipping it off to IST for their input.
