### ISSUE TITLE
Complete integrated local setup - Devin

### ISSUE THREAD

**Issue by drewconnelly** [department-of-veterans-affairs/va.gov-team#75636]
> As a developer supporting the appointments workflow I need to be able to validate and iterate on any changes in a local environment.

Complete the local setup of Vets-website and the VetsApiGateway service and ensure that they are integrated with the local VetsApi setup that was completed as part of [#73588](https://github.com/department-of-veterans-affairs/va.gov-team/issues/73588)

* Setup Vets-website locally
* Setup VPG and any dependencies locally
* Integrate local Vets-website, VPG, and VetsAPI]

**Comment by anita-halici** [comment]
@drewconnelly @BrittanySFowler @devin-mccurdy please add story points - thanks
