### ISSUE TITLE
Set up PEGA AWS S3 bucket

### ISSUE THREAD

**Issue by cloudmagic80** [department-of-veterans-affairs/va.gov-team#75648]
As an PEGA analyst that will use VA.gov and Champva forms, I need a central storage location that is access for the PEGA system to consume.

AC: A S3 bucket that is available for PEGA team to use. The bucket must have completed CHAMPVA PDF forms that was created by VA.gov website

**Comment by cloudmagic80** [comment]
In review and in end to end testing.

**Comment by baltes** [comment]
@cloudmagic80 Is this configuration complete, or will you still need to put effort into it?

**Comment by cloudmagic80** [comment]
Screenshot of PEGA's S3 bucket after sucessfully submitting the forms[Uploading... Screenshot 2024-03-07 at 10.38.25 AM.png]
