### ISSUE TITLE
Contact Center Review for VA Health & Benefits Mobile App - Prescriptions update

### ISSUE THREAD

**Issue by wavelaurenrussell** [department-of-veterans-affairs/va.gov-team#75656]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
*Please provide the name(s) of your product and a high-level description of your product.*
VA Health & Benefits Mobile App will launch updates to our Prescriptions feature which will result in a change to navigation and sorting.

### Launch Date
*Please provide the launch or rollout date and details.*
3/12/2024; 2.22.0 release

### Version Number
*Please provide the version number of the guide and/or video.*
Product Guide version 7.4

### Product Guide
*Please provide product guide link*
[Link to VA Mobile App Product Guide 7.4](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/releases/Call%20Center%20Docs/In%20use%20version/VA%20Mobile%20App%20Product%20Guide%207.4.docx)

### Product Video
*Please provide product video link*
N/A

### Product Video Transcript
*Please provide product video transcript link*
N/A

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
Beginning review.

**Comment by starlow00** [comment]
The draft looks good, so I am sending it to VEO for their review.

**Comment by starlow00** [comment]
There are no changes from VEO. I've attached the current copy; please use it for future revisions.
[VA Mobile App v7.4 SRT 02122024.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejlqQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--17d1d0552f2f798919b5a5ad9a9cd2826fb3e275/VA%20Mobile%20App%20v7.4%20SRT%2002122024.docx)
