### ISSUE TITLE
Documentation Site — Determine post-MVP tooling solution

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#7567]
## Summary 

- **Lack of complete, accurate, findable documentation about building on VA.gov** is a pain point for **VFS teams**
- We believe **determining a post-MVP documentation tooling solution** will help solve it by **giving VSP a clear path forward for improving the VFS-facing documentation**
- We’ll know we’re right if **our recommended solution allows us to consolidate all public VFS-facing documentation in a single experience.**

### User Story

As a VFS team member, I need a single source of truth for documentation for building on VA.gov that is robust and well-maintained, so that I can embrace self-service and develop in an agile way. 

### Problem Statement

Currently, VSP’s documentation for how to build on VA.gov is split across multiple sources. We consolidated the most important docs into a single table of contents in the documentation homepage MVP, but we still face pain points including: no control over rendering, confusing/nonexistent navigation tools, no search capability, limited feedback loops. Without a clear direction on the future of documentation tooling, we are spinning our wheels trying to solve each of these pain points in a silo.

_How might we determine a clear tooling solution roadmap for VSP documentation?_

## VSP Objective (Q1 & Q2 2020)

O1: Any volume of simultaneous customers have a delightful, self-service, end-to-end experience using the Platform to build on VA.gov.

## Measuring Success (KRs/KPIs)

The scope of this initiative is to make a recommendation to DEPO of a post-MVP documentation site solution. The success of the post-MVP solution itself will be measured by:

- [VSP KR] Increase in customer NPS
- [VSP KR] Reduction in volume of “non-human-needed” support requests month over month
- Average volume of documentation support requests

### Links

Initial brainstorming doc: https://docs.google.com/document/d/1dBv0KRqeJYfYTe6S3331vDvLL3Y3K3Kr2JKp7pCAeqw/edit

## Areas for Discovery

- Who is our audience? Who is our user? What is the narrowly scoped set of problems we are trying to solve? What is our desired feature set?

## Definition of Done

- [x] Documentation tooling solution has been recommended to DEPO
- [x] Next steps have been captured in ZenHub or elsewhere

**Comment by meganhkelley** [comment]
In VSP Sprint 23 (4/2/2020 - 4/14/2020), we:
- Created a [Lean UX outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/documentation-site/v2/lean-ux-outline-v2.md) for this iteration 
- Created a [research spreadsheet](https://docs.google.com/spreadsheets/d/1B5ee1Ex3aUoFRw-IEAcOFOB_4HVcncP-cZK4RqnqetY/edit#gid=0), lightly examining a wide breadth of tools 
- Identified 4 options to dig into further in Sprint 24: GitBook, Confluence, MindTouch, and Document360

**Comment by kristinagore** [comment]
GitBook trial: https://app.gitbook.com/invite/content-ia?invite=-M4_Kc9yGfScw4cPGWJE

**Comment by gmaciolek** [comment]
Document360 trial URL: https://vsp-trial.document360.io/

**Comment by billfienberg** [comment]
VFS Confluence: https://vfs.atlassian.net

https://dsva.slack.com/archives/CL181NRJQ/p1586378341089500

**Comment by meganhkelley** [comment]
Artifacts: 
- [Research artifacts - April 2020](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/documentation-site/v2/research-artifacts.md)
- [Confluence recommendation summary](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/documentation-site/v2/confluence-recommendation-5-2020.md)

New super epic to track prep for docs migration: #9477
