### ISSUE TITLE
Caregiver x Public Websites Intake

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#7568]
## Product Outline / Reference
https://github.com/department-of-veterans-affairs/va.gov-team/issues/7326

## High Level User Story/ies
As a PW team, what does our involvement look like with respect to the intake request from the Caregivers team? 

### What must be true in order for you to consider this epic complete? 

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

**Comment by AnneHurley** [comment]
See #7326
@MickinSahni

**Comment by MickinSahni** [comment]
> See #7326
> @MickinSahni

Thanks, @AnneHurley. I created this epic to house any tickets/work we as Public Websites needs to accomplish to fulfill that original #7326 request. To that end, I added #7326 as a story under this epic. If our involvement begins and ends with #7326 then this epic can be closed out. How does that sound?

**Comment by MickinSahni** [comment]
> > See #7326
> > @MickinSahni
> 
> Thanks, @AnneHurley. I created this epic to house any tickets/work we as Public Websites needs to accomplish to fulfill that original #7326 request. To that end, I added #7326 as a story under this epic. If our involvement begins and ends with #7326 then this epic can be closed out. How does that sound?

Or...we could convert each incoming request into an epic to house any of our work without having to create a separate epic. Think i'll do that.
