### ISSUE TITLE
AWS access for Wayne Weibel

### ISSUE THREAD

**Issue by wayne-weibel** [department-of-veterans-affairs/va.gov-team#75688]
### COR Name

Eunice Garcia

### Vendor Onboarding Representative Name

Other - please specify in 'Additional Notes'

### Your Name

Wayne Weibel

### Your Email

wayne.weibel@adhocteam.us

### Team, Role, and Company of the target individual

Pension, Engineering Lead, Ad Hoc

### Product Manager (PM) name and email

Anh Platt anh.platt@coforma.io

### Product Owner (PO) name and email

Emily Theis emily.theis@va.gov

### Desired AWS Access

permissions similar to Matthew Knight

### Access Expiration

08/31/2024

### E-QIP Transmittal Confirmation

![wweibel-favorable-eqip](https://github.com/department-of-veterans-affairs/va.gov-team/assets/5315216/d54670f4-9334-4fa7-8f91-cc8a83cda89c)

### Additional Notes

VOR - Jeff Langworthy jeff@coforma.io

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [x] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by Mandalorian-Oddball** [comment]
User in Atlas.

**Comment by Mandalorian-Oddball** [comment]
@wayne-weibel please update field "Desired AWS Access."

**Comment by wayne-weibel** [comment]
> @wayne-weibel please update field "Desired AWS Access."

permissions similar to Matthew Knight

**Comment by Mandalorian-Oddball** [comment]
This request has been completed.
