### ISSUE TITLE
[CST] Remove EVSS claims details code

### ISSUE THREAD

**Issue by jerekshoe** [department-of-veterans-affairs/va.gov-team#75680]
### Background
As we start to work on the Claim Details V2 initiative, we should do some housekeeping and remove the old EVSS code associated with the claim details page so that we can avoid having to duplicate the new changes in both places

#### Containers
- [x] Update the `AskVAPage` component to remove references to EVSS
- [x] Update the `DocumentRequestPage` component to remove references to EVSS
- [x] Update the `DetailsPage` component to remove references to EVSS
- [x] Update the `FilesPage` component to remove references to EVSS
- [x] Update the `ClaimStatusPage` component to remove references to EVSS
- [x] Update the `ClaimPage` component to remove references to EVSS 

#### Components
- [x] Update the `ClosedClaimMessage` component to remove references to EVSS
- [x] Update the `AdditionalEvidencePage` component to remove references to EVSS
- [x] Update the `AdditionalEvidencePageOld` component to remove references to EVSS
- [x] Remove any code associated with the EVSS version of claim details
- [x] Update any tests that still refer to the EVSS versions of the claim details code

### Acceptance Criteria
- [x] EVSS Claim details code has been removed from the codebase

**Comment by HeatherWidmont** [comment]
More work than originally thought, probably should have been a 5. Chipping away at this

**Comment by HeatherWidmont** [comment]
@pmclaren19 to review the last PR today

**Comment by HeatherWidmont** [comment]
Final PR is out of scope of this so we closed the ticket
