### ISSUE TITLE
Vets-api terminal access for Wayne Weibel

### ISSUE THREAD

**Issue by wayne-weibel** [department-of-veterans-affairs/va.gov-team#75687]
### Your Name

Wayne Weibel

### Your GitHub handle (terminal access is managed through GitHub)

wayne-weibel

### Team, Role, and Company of the target individual

Pension, Engineering Lead, Ad Hoc

### Product Manager (PM) name and email

Anh Platt anh.platt@coforma.io

### Product Owner (PO) name and email

Emily Theis emily.theis@va.gov

### COR Name (leave "None" if you listed an AWS user name above)

Eunice Garcia

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

Other - please specify in 'Additional Notes'

### Please confirm if you are listed as a team member in Atlas or are listed in Platform Team Roster

- [ ] [Team Member in Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [X] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Please confirm E-QIP Transmittal/Adjudication. This could be a screenshot of your Transmittal/Adjudication email, a link to another request where you've submitted this proof (i.e. AWS/SOCKS), etc.

- [X] I have attached proof that I have either transmitted my E-QIP survey or previously received a favorable decision (by including in "Additional Notes" section below)

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [ ] production (if requesting, justify prod access in 'Additional Notes' section)

### Additional Notes

![wweibel-favorable-eqip](https://github.com/department-of-veterans-affairs/va.gov-team/assets/5315216/59249c05-d417-4705-87ca-5eaca7418fa4)

VOR - Jeff Langworthy jeff@coforma.io

### Additional resources for Support Engineer

- [ ] For users on a VFS team but not listed as a team member in Atlas, they must start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] Instructions for handling requests [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access) - Support Only

**Comment by IsaiahMW1** [comment]
Found in VFS Team Roster

**Comment by IsaiahMW1** [comment]
You’ve been granted access to Dev, staging, and Sandbox environments.
Here's some additional documentation for [Vets API on EKS](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-TerminalAccess) that may help.

**Comment by wayne-weibel** [comment]
Thank you @IsaiahMW1
