### ISSUE TITLE
Rep phone number in Find search results does not match rep phone number in The Trexler File

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#75692]
## Expected vs. Actual
**Expected**: The rep phone number for James Atkinson in The Trexler File is 219-465-3587. 
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkJDQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e707f716ffb41187b8ee9180b59d295071862915/image.png" alt="image.png" />

**Actual**: The rep phone number for James Atkinson in Find a Rep is 301-585-4000.
<img width="718" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlJDQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6739d205ad52773b29eece4eb700cdbf37fd8d4a/image.png" alt="image.png" />

301-585-4000 is the phone number for the "Vietnam Veterans of America" organization, which James Atkinson is accredited to.  I'm suspecting we're pulling one (of the many) org phone numbers when we should be deferring to the rep's phone number.

## Steps to Reproduce
1. Select VSO
2. Enter "46385" into the location field
3. Enter "Atkinson" into the name field
4. Search

**Comment by oddball-lindsay** [comment]
The code we were pulling from was associating representatives with an organization phone number; not sure why.

We will create a new column for the rep's phone number, so that we can own that phone number association and ensure the rep's number (not an organization number) is returned.

**Comment by holdenhinkle** [comment]
PR - https://github.com/department-of-veterans-affairs/vets-api/pull/15525

**Comment by holdenhinkle** [comment]
PR (app code) - https://github.com/department-of-veterans-affairs/vets-api/pull/15528

**Comment by holdenhinkle** [comment]
This phone number stuff is more screwed up than I thought it was. We definitely need our own module.
