### ISSUE TITLE
SPIKE | Determine approach for Benefits Intake Service

### ISSUE THREAD

**Issue by tblackwe** [department-of-veterans-affairs/va.gov-team#75700]
# Problem Statement:
Currently we have 4 teams leveraging the [Benefits Intake API](https://developer.va.gov/explore/api/benefits-intake/docs?version=current) from Lighthouse
- Simple Forms (https://github.com/department-of-veterans-affairs/vets-api/tree/master/lib/simple_forms_api_submission)
- 686 Backup Submissions (https://github.com/department-of-veterans-affairs/vets-api/tree/master/lib/benefits_intake_service)
- 526 Backup Submissions extending benefits_intake_service (https://github.com/department-of-veterans-affairs/vets-api/tree/master/lib/form526_backup_submission)
- Pension partially extending benefits_intake_service (https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/sidekiq/lighthouse/pension_benefit_intake_job.rb)

Our plan is to have the following forms also submit to the Benefits Intake API 
- 4142 (Supplemental from 526 Submission)
- Burial
- Veteran Readiness & Employment
- Career Counseling

# The Request:
Evaluate the approaches taken by the existing 4 implementations, and determine if it would be appropriate to refactor benefits_intake_service to suit everything except Simple Forms (Simple Forms changes are out of scope).

## Known similarities: 
- All forms should use the simple forms metadata validator https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/simple_forms_api_submission/metadata_validator.rb
- All forms should create a [FormSubmission](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/form_submission.rb) and [FormSubmissionAttempt](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/form_submission_attempt.rb) record 

## Known variations
- All forms should have unique sources in metadata
- All forms should use unique API keys
- All forms should have unique sources in FormSubmission
- 526 adds additional documentation to submission (bdd document)

**Comment by micahaspyr** [comment]
Trying to understand exactly what is meant by the BDD documentation used by 526.  Need a little clarity

**Comment by sortizsh** [comment]
in 526 backup submission it has its own config and adds an additional form (bdd) tells the vet rep how they're supposed to work. we have a static version in code. @tblackwe  can add more context here

**Comment by micahaspyr** [comment]
Looking into this over the past couple of days I believe the service she house everything BI related, including the SimpleForm metadata validator.  What I mean by that is calls to the service should consider everything needed to submit DATA should be handled by the service, not necessarily the process for submission.  For instance, I see a direct to SimpleFormsApiSubmission::MetadataValidator.validate(metadata) within the PensionBenifitIntakeJob.  I think I'll move that call into the BI service to keep everything related to BI, in the BI service.  So, moving that call to be reference in the service keeps the service as is.  

Passing the 'source' i.e. (metadata[:source]) in to the generate_metadata method is fairly straightforward.  If a source is passed in to the generate_metadata method, it will enter the source and if not it will default to 'va.gov backup submission'
