### ISSUE TITLE
Understand Design system constraints

### ISSUE THREAD

**Issue by karafaithsanchez** [department-of-veterans-affairs/va.gov-team#75705]
**Problem**:
There are existing design systems and we need to know how much we need to abide by those guidelines / where there is flexibility in our UI decisions.

**Plan**:
Reach out to Lesley and discuss.

**Acceptance Criteria:**
Begin a [document](https://docs.google.com/document/d/1Mi30U7wvlXEOsukvdvjL9mny3gKpkoSY1Q3VbvxXDW8/edit) that outlines any guidelines. This will be the jumping off point for ticket #[75640](https://app.zenhub.com/workspaces/accredited-representative-facing-team-65453a97a9cc36069a2ad1d6/issues/gh/department-of-veterans-affairs/va.gov-team/75640).

**Comment by kristen101606** [comment]
@RivkaCGates  Kara and I chatted about this with Lesley over Slack and put our notes in [this doc](https://docs.google.com/document/d/1Mi30U7wvlXEOsukvdvjL9mny3gKpkoSY1Q3VbvxXDW8/edit). Lesley suggests that we reuse as much as we can from the VA Design System. The small tweaks we make in color, font, etc., are up to us. There aren't any clear constraints about what we can or cannot change, but we need to keep it within the VA brand. 

This discussion will inform next steps in ticket #75640. I think we've met the AC on this ticket, so I'm comfortable closing it if you are.
