### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by andreamurchie** [department-of-veterans-affairs/va.gov-team#75710]
### Name

Andrea Murchie

### Email

andrea.murchie@va.gov

### Role

Designer/ Researcher

### Team

Benefits Portfolio EE

### Product Manager (PM) name

Jen Bertsch

**Comment by naomimarcussen** [comment]
Hi! I just sent an invite to andrea.murchie@va.gov. Let me know once you've created an account and I can give you full access.

**Comment by andreamurchie** [comment]
I have created an account now. Thanks!

**Comment by naomimarcussen** [comment]
Great! You should be good to go with full access now.
