### ISSUE TITLE
audit fwdproxy backends for health checks

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#7571]
## Description

Walking through our list of backends while reviewing documentation, it appears that not all of our backends have health checks configured. I'm not sure how we ended up in this scenario, but we should go through the list and get as many configured as we possibly can. Not all do have health check ability (TCP type can't I believe).

It would likely be useful to couple this with the tasks in https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/86 since we'll need to contact a lot of these partners anyway.

We are blind to network layer stuff causing connection issues 

Current list:

- [ ] pagerduty
- [ ] govdelivery
- [ ] central-mail
- [ ] arcgis
- [ ] vha-access
- [ ] okta
- [ ] idme
- [ ] gids

## AC

- [ ] Audit list above and make sure all have health checks configured that we can find

**Comment by ricetj** [comment]
also Look at https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team-sensitive/86
