### ISSUE TITLE
SOCKS access for Jamie DeHaan

### ISSUE THREAD

**Issue by jdatoddball** [department-of-veterans-affairs/va.gov-team#75719]
### Your Name

Jamie DeHaan

### Your Email

jamie.dehaan@oddball.io

### Your Role and Team

Product / Delivery Manager, VES DevEx

### Product Manager (PM) name and email

Myself, Jamie DeHaan, jamie.dehaan@oddball.io

### Product Owner (PO) name and email

Patrick Vinograd, patrick.vinograd@va.gov

### Access Type Requesting

developers

### Public SSH Key

`ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC9JVmDg60VAf9Iy/cHXqjvWSOg1wWG+89E038qCCN0coF746xSQISMGMRM2DazsQJdxj0oRblMOliGvV9PEiEHukFm9ySXOnTSp8h1fMpnbGlAIIhUHYtQy6QqmDJCVzqgdCkZiKuyPTaiSRA7iqyZy3CAAshrIJ4/lHvQEBDkVE1dQygNFyJCK/0ZZUh+DLIQhCiUJlHT2wN+Y6LW5j9rfewNq4GM90jtrTozVK5t8+0OhWsZWGuNioYNlcwGdkrj2sBui/O7gcfSgccYS+7kUo7sHDdv7eG+upRy05XDLowb7EA4ZB28AOL9M3ZvH+PMAWHEvGznTHSp0a/5S3lFV2YbbRoDa6utbZVdyldvUnKWvQW/yJ059MZ2SvuhHMWghtw3Nf43Ani09MNMKxXx7L3ln+RzJKCHXCCCtuGhgRQJtVrfi1WUzrkLN9Uo9W1/ZFkakZpneew9+E3Xh4S00E64ghKU4Tze9gtNbPHn1YTUeB85zMUebXmL5sYNDL2EhNPNMRmduhZ+zR0JY5ev55QivaVXqWB85ILiWvlQsHOHLVPe/UeoCuFhtCgL4K9umHm+mM+o9EtL3qLxbuMCNQFZMHqvnEC6bFX1cxI/31Iiw1A135ndNDjLDtKoYHtWnpDiCY51JUNMu9+ni5NLOInaHIDh0B6qmZmzOOXDHw== jamie.dehaan@oddball.io`

### E-QIP Transmittal Confirmation

<img width="1301" alt="Transmittal Notice" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/144170602/5a11831b-9c80-4050-8f30-1f57779732b2">

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by ph-One** [comment]
SOCKS access completed.
