### ISSUE TITLE
Documentation - Audit/edit all VSP documentation & define recurring process

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#7573]
### User Story

As a VFS team member, I need to reference a clear, well organized, well maintained, trustworthy documentation set about building on VA.gov, so that I can embrace self-service and develop in an agile way.

### Problem Statement

VSP-owned documentation is fragmented and varies drastically from docs that receive a significant amount of care and attention to things that haven’t been updated since before VSP was created. There’s no indication of who owns the docs (which was recommended by Service Design in Q4 2019 #4066), when they were last updated, or whether they are accurate.

How might we audit and edit the holistic set of VSP documentation to create a set of professional grade user guides for building on VA.gov?

## VSP Objective (Q1 & Q2 2020)

O1: Any volume of simultaneous customers have a delightful, self-service, end-to-end experience using the Platform to build on VA.gov.

## Measuring Success (KRs/KPIs)

TBD

## Areas for Discovery

- What is the set of docs that VSP owns? Should own? 
- What docs are missing? 
- In cases where docs are missing because policies are missing, is the creation of those policies within the scope of this initiative? (likely no — identifying them is, though)

## Definition of Done

**Comment by vbellissimo** [comment]
Cancelling/old task.
