### ISSUE TITLE
Qualitative Data Request [Monthly Recurring request for: Custom Survey, Debt Resolution Team] - May

### ISSUE THREAD

**Issue by charlottecesana** [department-of-veterans-affairs/va.gov-team#75741]
### Data Type Requested

User Surveys

### Data Source Type

Medallia

### Date Range Start

05/01/24

### Date Range End

05/31/24

### Product Name(s)

Financial status report form

### Product Description

This form is for Veterans or service members who need help with debt related to VA benefit overpayments or health care copays.

### Survey URL(s), key term(s), case category or type

Custom survey (survey a Veteran sees after they submit the financial status report form))

va.gov/manage-va-debt/request-debt-help-form-5655/confirmation

Please share data for dates above (1-18-24 to today, 2-8-24), then please share monthly reports for first day of the month to the last day of month, shared on the first day of the next month.

Thank you!

### File Delivery Format

One file, different tab for each term/URL

### Word Cloud

Yes

### VA Email Address(es)

charlotte.cesana@va.gov, denise.coveyduc@va.gov, megan.crigger@va.gov, joseph.lee9@va.gov

### Add Assignee and Labels

If not already done so, please ensure @newworld2616 is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by newworld2616** [comment]
Hi @charlottecesana, I have shared the requested data. I will start sending the data monthly. Thank you!

**Comment by denisecoveyduc** [comment]
FYSA @ATMiddleton  @clantosswett  Just keeping you informed. The team is working together to ensure the feedback coming in as part of the custom survey is being captured. We continue to tread a new path with this custom survey! Thanks for the continued collaboration :) 

The url we were told to use is [va.gov/manage-va-debt/request-debt-help-form-5655/confirmation](http://va.gov/manage-va-debt/request-debt-help-form-5655/confirmation) but on that page is the link for the custom survey and also the feedback button at the bottom.  

As @mgleo said we suspect the report that was initially pulled is for the blue feedback button at the bottom but we are looking for the custom survey link offered to Veterans after they submit the online form. 

@ATMiddleton @aubreyarcangel Is there a different URL we should use to request this data?
cc: @charlottecesana

**Comment by newworld2616** [comment]
Hi, I have shared the monthly data. Thank you!

**Comment by newworld2616** [comment]
Hi, I have shared the monthly data for 5655 form. Thank you!

**Comment by newworld2616** [comment]
Hello, I have shared the Monthly data. Thank you.

**Comment by ATMiddleton** [comment]
Updated ticket with accurate data.
