### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by jennymayoco** [department-of-veterans-affairs/va.gov-team#75742]
### Name

Jennifer Mayo

### Email

jenny.mayo@coforma.io

### Role

IA Specialist

### Team

CAIA

### Product Manager (PM) name

Terry Nichols

### Additional Notes

As IAs working with multiple product teams, we'd like to have access to Figma for quicker search to locate files within Figma as well as share feedback.

**Comment by naomimarcussen** [comment]
Hi! An invite has been sent to jenny.mayo@coforma.io.

**Comment by jennymayoco** [comment]
Thank you @naomimarcussen! I was able to access it
