### ISSUE TITLE
FE | Profile | Update SIP form object to be a function to avoid excessive calls on react app inits

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/va.gov-team#75760]
## Issue Description
After refactoring code to isolate the personalization app folder, it was discovered that the `FORM_LINKS` constant gets pulled in during app inits and will repeatedly call `getAppUrl` when it doesn't really need to.

Locally an engineer may also encounter errors around this function being called when loading up vets-website, because they could have content-build out of sync and may not have all the app manifest entries available.

You can see this [slack thread for more details](https://dsva.slack.com/archives/C053JC66YHF/p1706649841275619)

## Front end tasks
- Refactor the constant into a function that will only result in the getAppUrl function being called when it is needed.

## Acceptance Criteria
- [x] Code has been refactored to be more fault tolerant
- [x] Unit tests written for the refactored code
- [x] `getAppUrl` function is only called once/when needed for applications to start

**Comment by adamwhitlock1** [comment]
I think the only way to really validate this is to have another engineer verify that the code has been merged. I think the main place this would have caused and issue would have been MyVA since they ask about different forms when showing the applications in progress.

@allisonlu I have validated that things look good from my end and on staging with a few users, would you be able to validate that this ticket can be closed?

**Comment by allisonlu** [comment]
> @allisonlu I have validated that things look good from my end and on staging with a few users, would you be able to validate that this ticket can be closed?

lgtm, validated 👍
