### ISSUE TITLE
Vets-api terminal access for Matt Kelly

### ISSUE THREAD

**Issue by mathisto** [department-of-veterans-affairs/va.gov-team#75784]
### Your Name

Matt Kelly

### Your GitHub handle (terminal access is managed through GitHub)

@mathisto 

### Your dsvagovcloud AWS user name (if applicable)

Matthew.Kelly7

### Team, Role, and Company of the target individual

Team: Banana Peels (Appeals), 
Role: Tech Lead
Program/Company: Lighthouse Benefits APIs, Ad Hoc, LLC

### Product Manager (PM) name and email

Michael Hobson (michael.hobson@adhocteam.us)

### Product Owner (PO) name and email

Janet Coutinho (janet.coutinho@va.gov)

### COR Name (leave "None" if you listed an AWS user name above)

None

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

None

### Please confirm if you are listed as a team member in Atlas or are listed in Platform Team Roster

- [x] [Team Member in Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [X] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Please confirm E-QIP Transmittal/Adjudication. This could be a screenshot of your Transmittal/Adjudication email, a link to another request where you've submitted this proof (i.e. AWS/SOCKS), etc.

- [X] I have attached proof that I have either transmitted my E-QIP survey or previously received a favorable decision (by including in "Additional Notes" section below)

### ArgoCD terminal access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### Additional Notes

[EQip Screenshot](https://private-user-images.githubusercontent.com/41602677/246487522-0db2bc45-408e-439d-8d6f-dff2438ec560.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1MDE0MjQsIm5iZiI6MTcwNzUwMTEyNCwicGF0aCI6Ii80MTYwMjY3Ny8yNDY0ODc1MjItMGRiMmJjNDUtNDA4ZS00MzlkLThkNmYtZGZmMjQzOGVjNTYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA5VDE3NTIwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjZGQ4MTNiM2JjZGNiZGU5ZTdmOTdmMTU1ZmVlMzZiODQ5NGQyYTJjNzkxNDE0NGM0MzYzYzg4OTZmYWViMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UarYE3N1khMk0-Ux-CZMbDsegGmeoqldVCtL4XTBTQs)

My recently approved SOCKS access request is [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/56544), including a screenshot of my E-QIP transmittal email.

I'm the tech lead on the team maintaining the Appealable Issues, Legacy Appeals, Notice of Disagreements, Supplemental Claims, Higher-Level Reviews, and Appeals Status APIs for Lighthouse, and need production access to respond to customer support escalations.

### Additional resources for Support Engineer

- [ ] For users on a VFS team but not listed as a team member in Atlas, they must start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] Instructions for handling requests [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access) - Support Only

**Comment by davidpetras** [comment]
@mathisto You’ve been granted access to the `dev`, `staging`, and `sandbox` environments.
Apologies for the delayed response to this request, due to the lack labels associated with the request it never tied itself to platform support to be viewed. Again apologies for the delay.

Here's some additional documentation for [Vets API on EKS](https://depo-platform-documentation.scrollhelp.site/developer-docs/vets-api-on-eks#VetsAPIonEKS-TerminalAccess) that may help.

**Comment by davidpetras** [comment]
Access to `prod` is pending approval by OCTODE, and we'll update you as 
soon as it's available.

**Comment by JonathanKamensDVA** [comment]
Approved.

**Comment by davidpetras** [comment]
@mathisto You've been granted access to Production,
with access to Production limited to 6 months, expiring 10/02/24.

Please set a reminder for yourself to return to this Issue and
request an extension within 1 week of the expiration date. You'll
receive 1 reminder with a 72 hour window to respond. Failure to
respond will result in your access being revoked and will require
you to fill out a new request.

**Comment by davidpetras** [comment]
Support Slack reminder [here](https://dsva.slack.com/archives/C06CY71PCAX/p1712086389784449)

**Comment by davidpetras** [comment]
@mathisto your access has expired as of today and there has not been a request for an extension, if there is no response in 72hours access will be revoked and a new request for prod access will be required.

Thank you for understanding.

**Comment by davidpetras** [comment]
`prod` access has been revoked.

A new request will need to be submitted for OCTO approval.
