### ISSUE TITLE
CF: Update mapping logic when settlement description is not found in caution flag content

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#7578]
As a developer, I need to display a default caution flag message when a caution flag to be displayed in the Comparison Tool does not have a plain language translation to be displayed, so that the users of the Comparison Tool are displayed a user friendly caution flag message.

## Assumptions
1.  This is an update to the Caution Flag mapping established in #7151
2. The "caution flag source data" is that data loaded into GIDS on the HCM, Settlement, Accreditation, MOU, 702 data files.
3. This work is completed behind a toggle so that it is only available in the staging environments and below.

## Acceptance Criteria
1. When a caution flag source data doesn’t match any mapping rules, a generic message is displayed on the search results page:
    a. Single Unmapped Search Results Caution Flag Header: This school has a cautionary warning
    b. Unmapped Flag with Other Flags Search Results Caution Flag Header: This school has cautionary warnings
    c. Search Results Caution Flag Description: School engaged in misleading, deceptive, or erroneous practices
2. When a caution flag source doesn’t match any mapping rules, a generic message is displayed on the header of the profile page:
    a. Single Unmapped Profile Page Header Caution Flag Header: This school has a cautionary warning
    b. Unmapped Flag with Other Flags Profile Page Header Caution Flag Header: This school has cautionary warnings
    c. Profile Page Header Caution Flag Description: School engaged in misleading, deceptive, or erroneous practices
3. When a caution flag source doesn’t match any mapping rules, a generic message is displayed in the cautionary information section of the profile page:
    a. Cautionary Information section Caution Flag Header: School engaged in misleading, deceptive, or erroneous practices
    b. Cautionary Information section Caution Flag Description: VA has found that this school engaged in misleading, deceptive, or erroneous advertising, sales, or enrollment practices, and has taken action against it.

## Supporting Artifacts
1. Spreadhsheet: [https://app.zenhub.com/files/133843125/7ede6ae9-eb38-4204-aeb6-659535c054a8/download](https://app.zenhub.com/files/133843125/7ede6ae9-eb38-4204-aeb6-659535c054a8/download)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/645

**Comment by delli-gatti-michael** [comment]
![Screen Shot 2020-04-21 at 1 31 56 PM](https://user-images.githubusercontent.com/45575003/79898562-71496a00-83d9-11ea-89b7-1a279cc72c88.png)

---

![Screen Shot 2020-04-21 at 1 32 04 PM](https://user-images.githubusercontent.com/45575003/79898572-75758780-83d9-11ea-9000-2415b8ea340d.png)

---

![Screen Shot 2020-04-21 at 1 32 13 PM](https://user-images.githubusercontent.com/45575003/79898577-79090e80-83d9-11ea-8762-9774fad19387.png)

---

![Screen Shot 2020-04-21 at 1 57 25 PM](https://user-images.githubusercontent.com/45575003/79898584-7dcdc280-83d9-11ea-8e3e-7c3c261ceec8.png)

---

![Screen Shot 2020-04-21 at 1 57 39 PM](https://user-images.githubusercontent.com/45575003/79898608-86be9400-83d9-11ea-8410-bf14b88109a0.png)

---

![Screen Shot 2020-04-21 at 1 57 47 PM](https://user-images.githubusercontent.com/45575003/79898621-8c1bde80-83d9-11ea-9224-ed445f7f3918.png)

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
Tested by testrail test case:
https://dsvavsp.testrail.io/index.php?/cases/view/515

**Comment by delli-gatti-michael** [comment]
Changes are now live in Staging. Closing this issue
