### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by kristinoletmuskat** [department-of-veterans-affairs/va.gov-team#75794]
### Name

Kristin Ouellette Muskat

### Email

kristin.o.m@coforma.io

### Role

Information Architect

### Team

CAIA

### Product Manager (PM) name

Danielle Thiery

### Additional Notes

Needing access to be able to find/search figma files

**Comment by naomimarcussen** [comment]
Thanks for the request. I see that you have an account created with your coforma email.

**Comment by kristinoletmuskat** [comment]
You're right! I thought I was missing some permissions since Jenny was (I think), but it looks like I'm good. Thank you!
