### ISSUE TITLE
CF: Remove prod flag for 7533

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#7579]
As a developer, I need to remove the prod flag for VETTEC Logo and Additional Resources sections not displaying correctly on medium and small screens so that they are available in the production environment.

## Assumptions:
1. UX has reviewed and signed off on the changes as of 04/23/2020.

## Acceptance Criteria:
1. The functionality in #7533 is available in the production environment.

## Supporting Artifacts:
1. N/A

**Comment by ksantiagomorgan6** [comment]
Pull Request:

https://github.com/department-of-veterans-affairs/vets-website/pull/12356

**Comment by delli-gatti-michael** [comment]
Locacl testing complete

**Comment by delli-gatti-michael** [comment]
Changes are now live in production. Closing this issue
