### ISSUE TITLE
Figma access request - Bryan Riley

### ISSUE THREAD

**Issue by bryan-riley-va** [department-of-veterans-affairs/va.gov-team#75792]
### Name

Bryan Riley

### Email

bryan.riley@va.gov

### Role

Product / Scrummaster

### Team

MHV SM and MHV MR

### Product Manager (PM) name

Marci McGuire / Janie Tankard-Carnock

### Additional Notes

Need read only access to Figma to support the planning processes.

**Comment by naomimarcussen** [comment]
Hi! An invite has been sent to bryan.riley@va.gov.

**Comment by bryan-riley-va** [comment]
@naomimarcussen are you able to re-send?  I don't see it in my inbox or spam unfortunately!

**Comment by naomimarcussen** [comment]
Hi! I've resent the invite.

**Comment by bryan-riley-va** [comment]
Thank you I'm in!
