### ISSUE TITLE
After Visit Summary Link Unavailable - Past Appointment Details Page - Message Update (UI) 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#75801]
## Description
We will need to notify the Veteran that the After Visit Summary link is not available when the appointment response is not returning the link to the frontend (UI) 

---

## Acceptance Criteria
Background: the `va_online_scheduling_after_visit_summary` toggle is on

Given the user is on the Past list
When the user clicks on the Details link and the response for the after visit summary link is `null`
Then display the description notifying the Veteran that the After Visit Summary link is unavailable 
And page design matches the [design spec](https://www.figma.com/file/os1DFf0nwxBGnNt45ToeDD/Add-After-Visit-Summary-%7C-Appointments-FE?type=design&node-id=18%3A1690&mode=design&t=pHGt62uQWnZlANJS-1)

### Technical Spec (vets-api) 
- [ ] vets-api will return a new `avsPath` field in the appointment response that will contain the AVS link
- [ ] if no AVS link is available, the `avsPath` field will be empty
- [ ] if an error response is received from AVS, then the `avsPath` field will contain the error detail

### Design Assets
[Design spec](https://www.figma.com/file/os1DFf0nwxBGnNt45ToeDD/Add-After-Visit-Summary-%7C-Appointments-FE?type=design&node-id=18%3A1690&mode=design&t=pHGt62uQWnZlANJS-1)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by ldelacosta** [comment]
Validated in staging for Judy Morrison's appointment on Friday, October 13, 2023 at 9:00 a.m. MT

UX team will review the page details. 

<img width="1937" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeExaQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--54ecb03b00ff8d8446f3334ca844d66d3281d157/Screenshot%202024-03-13%20at%2010.06.05%20AM.png" alt="Screenshot 2024-03-13 at 10.06.05 AM.png" />

**Comment by Cieramaddox** [comment]
UX team has validated this. @ldelacosta

**Comment by ldelacosta** [comment]
Team has validated the work and no issues to report. Closing out the ticket.
