### ISSUE TITLE
Document Upload Migration: BDD Instructions

### ISSUE THREAD

**Issue by NB28VT** [department-of-veterans-affairs/va.gov-team#75805]
## Acceptance Criteria
- [ ] Extract the necessary Lighthouse integration infrastructure you implemented in https://github.com/department-of-veterans-affairs/vets-api/pull/13835
- [ ] Extract the necessary implementation of that infrastructure for the BDD Instructions job
- [ ] The document submission should be tracked via the polling solution implemented in [this ticket](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/75804)
- [ ] Re-record automated tests with the submission endpoint to verify the Lighthouse endpoint is still working as expected
- [ ] Automated tests should ideally stress the actual Lighthouse status endpoint and record a VCR cassette for that as well

**Comment by sortizsh** [comment]
closing this work is encapsulated in other tickets
