### ISSUE TITLE
Reporting "other" returns an error

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#75815]
## Expected vs. Actual
**Expected**: I'm able to report 'Other' information outside of address, phone and email.

**Actual**: I can report address phone and email information, but receive an error when I try to submit and 'other' is checked.  This happens when I try to submit 'Other' as the only item checked and also when I try to submit with 'Other' and phone/email/address also selected. 

**Note**: I understand we had to get around (this Invalid Authenticity Token error https://github.com/department-of-veterans-affairs/va.gov-team/issues/75311) to open this feature up for Staging.  Perhaps the lingering issue with the 'Other' option is related to that.

## Steps to Reproduce
1. Select "Report outdated information" for any rep in the search results
2. Check "Other" and enter anything in the open field
3. Click "Submit"
4. Error is returned

<img width="515" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnRKQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f20f8bbcfcfa6a6be32028157d829c1d5cc0548d/image.png" alt="image.png" />

**Comment by oddball-lindsay** [comment]
@cosu419 were you able to determine what was causing this error?

**Comment by cosu419** [comment]
@oddball-lindsay Yep, just "other_comment" was being passed when the backend was expecting "other."
