### ISSUE TITLE
CT: Remove prod flag for 7546

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#7581]
As a developer, I need to remove the prod flag for view less button in School Locations section should adjust focus so that they are available in the production environment.

## Assumptions:
1. UX has reviewed and signed off on the changes as of 04/10/2020.

## Acceptance Criteria:
1. The functionality in #7546 is available in the production environment.

## Supporting Artifacts:
1. N/A

**Comment by desireeturner** [comment]
Turns out there wasn't a prod flag on the original story, but want to have the update validated in Prod (presumably went live on 04/07/2020).

**Comment by dneel-bah** [comment]
UX team reviewed fix in production on 04/10 and signed off on the fix.
