### ISSUE TITLE
Backend Test Data

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#75819]
## Description
Because of process and technical constraints, we are not able to hit the BTSSS servers from our development machines if not on the VA network. To mitigate this, we need to make a dedicated effort to set up reliable and accurate test data for the endpoints provided so far.

***Note: endpoints like `/ping` and `/authorized_ping` probably don't need a schema, but due diligence should be done to ensure swagger doc is accurate (e.g. are the recommended headers in the description, is there a description, etc).***

## Acceptance Criteria
- [ ] Find reliable BTSSS endpoint schemas
- [ ] Set up endpoint interception for
  - [ ] Ping
  - [ ] Authorized ping
  - [ ] Claim status
- [ ] Unit/integration tests pass
- [ ] [Recommended 80% test coverage percentage](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-VA.govQAStandards)

## Demo
- Demoable? Kinda
- How? Demo with API testing tool - show interception?
- Impact? Can talk about importance of swagger doc as contract between API team and integration team

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by ayush-chak** [comment]
Closing as a duplicate
