### ISSUE TITLE
Sidekiq job failing its retry limit (data dog alert)

### ISSUE THREAD

**Issue by asmithgovcio** [department-of-veterans-affairs/va.gov-team#75825]
It's been brought to my attention that we have an monitor setup in data dog to alert when a sidekiq job fails and hits it's retries limit. You can view this monitor here https://vagov.ddog-gov.com/monitors/188768?q=total&view=spans#event-list ideally we wouldn't have any failures or be hitting a retry limit but its not immediately clear which sidekiq job it is thats hitting the limit nor the reason why its failing, more research is needed.

**Comment by asmithgovcio** [comment]
So the issue appears to be coming from a service we don't usually interact with. It's coming from a sidekiq worker that processes request decisions. I don't see any logic in place for this in regards to having a retry limit or setting a higher than normal limit so it will keep retrying without throwing an error for longer but I need to really see what's causing the failure in the first place before I apply a bandaid. I will update after a little more research.

**Comment by asmithgovcio** [comment]
Ive created a pull request to address this issue https://github.com/department-of-veterans-affairs/vets-api/pull/15529

**Comment by asmithgovcio** [comment]
After discussing with Kevin it looks like we're not the team responsible for these files or this section of the application. I've closed out my pull request and am keeping this ticket in the waiting for code review status, I've sent an email to two of the 4 people team that's responsible for these files, hopefully they respond quickly.

**Comment by HeatherRienks** [comment]
@asmithgovcio - Per our BE Sync this afternoon, please confirm here who you have reached out on the team noted above.

Also, please update the debt-alerts channel thread with this information for visibility.  
Here is the link: https://dsva.slack.com/archives/C02EYV9NJFJ/p1707333080762259

**Comment by asmithgovcio** [comment]
**Discovery Results:**
 * Issue is being caused by failures in the EVSS:RequestDecision sidekiq job
 * This code is owned by the benefits-management team
 * They're aware of the issue however no change can be implemented until other api changes are made first, trying to get more information. 
 
**Solution:** 
I've reached out to Adam Whitlock, Tom Harrison, as well as the entire benefits management engineering team in their dev channel. The consensus seems to be that they are aware there is an issue however they're unable to make any changes at this point in time and are awaiting future light house API changes to be made before they can change this. I'm attempting to get more information regarding the lighthouse changes required. 

<img width="874" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzlnQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--79ef30284109b3094b49fead248a524a77552346/Screenshot%202024-02-15%20at%209.45.11%E2%80%AFAM.png" alt="Screenshot 2024-02-15 at 9.45.11 AM.png" />

**Comment by asmithgovcio** [comment]
I also spoke with Jerek Shoemaker who seems to be the most knowledgeable on this part of the code, he suggested to me that they should have a fix in place as soon as light house updates their API (no ETA on that)

<img width="1388" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUpoQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--68a08fa1896e256203c4e7a255ebab11ed0308c5/Screenshot%202024-02-15%20at%2010.06.45%E2%80%AFAM.png" alt="Screenshot 2024-02-15 at 10.06.45 AM.png" />

**Comment by asmithgovcio** [comment]
Closing this ticket out as its out of our hands and not our responsibility to mess with this part of the application, the team responsible is aware of the issue and have a planned fix ready to roll out pending some lighthouse api changes. Once those lighthouse api changes are made and deployed they can enable their feature flag, deploy, and should see the issue resolved.
