### ISSUE TITLE
Ping endpoint: vets-website to vets-api link

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#75820]
## Description
As an example of a round-trip request, we should provide a way on the scaffold to hit a vets-api which then hits a BTSSS API endpoint and returns. This will help establish our frontend to dependent service request patterns. 

***Note: Auth ping or ping recommended for this. We can probably keep this extremely simple (example: click a button, show the json in the console, or on a textarea component).***

## Acceptance Criteria
- [ ] A button exists on the travel pay scaffold
- [ ] Clicking the button shows the response from the BTSSS API

## Demo
- Demoable? Yes
- How? Click the button on the scaffold
- Impact? Shows initial round-trip integration, paves the way for other integrations. 

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by athifw** [comment]
PR here: https://github.com/department-of-veterans-affairs/vets-website/pull/28675
