### ISSUE TITLE
Update zip code on Document Upload page

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#75838]
## Issue Description

The zip code on the document upload page is incorrect: https://staging.va.gov/pension/application/527EZ/additional-information/document-upload

<img width="651" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXROQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f3f97db1af14c061de5b957b6796884e627d4bcf/Screenshot%202024-02-12%20at%2010.46.49%E2%80%AFAM.png" alt="Screenshot 2024-02-12 at 10.46.49 AM.png" />

## Tasks

Under "Option 3" of the copy, the zip code for that address needs to be updated from:

Department of Veterans Affairs
Pension Intake Center
PO Box 5365
Janesville, WI `53547-5192`

to 

Department of Veterans Affairs
Pension Intake Center
PO Box 5365
Janesville, WI `53547-5365`

## Evidence of correct address from PDF form

<img width="1638" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXBOQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9fc70a4f4245c01c88a83dbe9a5dcda84bb4b4f6/Screenshot%202024-02-12%20at%2010.40.46%E2%80%AFAM.png" alt="Screenshot 2024-02-12 at 10.40.46 AM.png" />

**Comment by aplatt-coforma** [comment]
Change looks good on staging.
<img width="1028" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeU5qQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--06b92d692a541b502d4d6827d88dc8ad18b30172/Screenshot%202024-02-15%20at%2012.22.35%E2%80%AFPM.png" alt="Screenshot 2024-02-15 at 12.22.35 PM.png" />
