### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by danbivins** [department-of-veterans-affairs/va.gov-team#75851]
### Name

Daniel Bivins

### Email

dan.bivins@adhocteam.us

### Role

Sr. Designer/Accessibility Specialist

### Team

MHV on Cartography Team

### Product Manager (PM) name

Wes Rowe

**Comment by naomimarcussen** [comment]
Hi! An invite has been sent to dan.bivins@adhocteam.us. Please respond here once you've created your account and I'll give you full access.

**Comment by danbivins** [comment]
Account created. Thanks for your help!

**Comment by naomimarcussen** [comment]
Great! You should be good to go with full access now.
