### ISSUE TITLE
SOCKS access for [Marisa Dominguez, VA-CMS]

### ISSUE THREAD

**Issue by MDomngz** [department-of-veterans-affairs/va.gov-team#75853]
### Your Name

Marisa Dominguez

### Your Email

marisa.dominguez@oddball.io

### Your Role and Team

UX Designer & Researcher - CMS (Drupal)

### Product Manager (PM) name and email

Michelle Dooley

### Product Owner (PO) name and email

Erika Washburn

### Access Type Requesting

viewers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDAxf8MIClLn8wX2i9A3VQq5MlhY+Un1AQYOH4dGgsmyvYzT2B8McrAzU1VnoqiK7jc/3o2lNL/7eDAIRb2D9RAmaVh3Rn/LX5tk0xE0peQl1g/DUbR/RoymCIeaer/bPIq7fp3S93o2/fK/lvVnmEb9Lf6qeyCff7khhlKF1lc75Z/XKXynHxAZaN6QBX0ORgxTTW7WXHuDcnEtpLbCrGxEoZMAlr6PFCGRFbZJgnQxyk9GGtQiA1s9FcanuO3EajcEZs4nKfLzzaxLaQnq3wkb2GJWkJnl/FZ5V2nqfRKvDEhpqInGxZ6OmAdCXNwKxpPIDCKSfbhnokDyHPqQPOUxKRBhT+hCQo6rvA6ZflKJEZd0GYIb9ZZj000SUI+Rgxdcn/SGBjD2yAOuJjBseCHwBpiHi3yMfWAQxKLWcUOTJOqvrRdduGtXauuJRiupyqWF7ZW03lXLxxCenGnCovxF1acBEnIWg/XUoJN2M8opbtp1oVHYnOs5EtWRkVj4h8= marisadominguez@Marisas-MBP.net

### E-QIP Transmittal Confirmation

![Oddball-Mail-Transmittal-Notice-Dominguez-Marisa-Oddball-Inc-](https://github.com/department-of-veterans-affairs/va.gov-team/assets/156954219/2aedcacd-ccf1-4b6d-9ab7-47b73f0e8824)

### User must exist in a roster before SOCKS access can be granted

- [x] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by patrick-black-oddball** [comment]
found as an "Atlas User" in Atlas.
