### ISSUE TITLE
Create a Github project template

### ISSUE THREAD

**Issue by dickdavis** [department-of-veterans-affairs/va.gov-team#75858]
## Issue Description
_Insert issue details here_

## Acceptance Criteria
- [ ] Documentation has been updated
- [ ] Next steps have been determined and documented
- [ ] AC1
- [ ] AC2

#### Tech notes

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by joeniquette** [comment]
Decision: OCTO identity will create requirements doc based on conversations with app teams. We will still require the dev team to “sign-off” on requirements. Add this to the approval/signoff issue or section of appropriate issue.
