### ISSUE TITLE
Bugfix: `undefined method `values' for nil:NilClass` for Pension submission

### ISSUE THREAD

**Issue by TaiWilkin** [department-of-veterans-affairs/va.gov-team#75864]
## Overview

The following error is being thrown from a pension submission in production:
`Lighthouse::PensionBenefitIntakeJob FAILED! undefined method 'values' for nil:NilClass NoMethodError: undefined method 'values' for nil:NilClass /app/lib/pdf_fill/forms/va21p527ez.rb:1523: in 'build_custodian_hash_from_dependent': undefined method 'values' for nil:NilClass (NoMethodError)`

Identify the cause of the error and create a fix.

Acceptance criteria:
- A null dependent full name should not prevent the PDF from submitting successfully.
- A null dependent full name should not be possible to generate when filling in the form client side.

**Comment by aplatt-coforma** [comment]
Tested on stage and it looks good. Followed these steps:

1. Fill out the form, and say that you have dependents.
2. Completely fill out all dependent data. For at least one dependent, say they don't live with you, and fill out address data.
3. On the review page, change your answer to say that you don't have any dependents.
4. Submit the form. It should submit cleanly. In the network tab, you should see that the submission which was sent had no dependent data.
