### ISSUE TITLE
Domo Analytics Discovery (cont)

### ISSUE THREAD

**Issue by nnicholas7** [department-of-veterans-affairs/va.gov-team#75879]
Continue the quest for information regarding how to use and understand Domo Analytics and other related tools. 

Task
- [x] Find out and attend Data Analytics Office Hours (Tuesdays & Thursday from 3:30-4:00 PM ET)
- [x] Firm up open questions and ask them at Data Analytics Office Hours
- [x] Update Single Source of Truth document with comments from meeting and related comments in Slack (specially check out vfs-analytics)
- [x] Review documentation on Data Dog and create open questions
- [x] Schedule a meeting with the engineer to get a tour of Datadog and ask questions (if needed)

Acceptance Criteria
- [x] Attend Data Analytics Office Hours
- [x] Update Single Source of Truth Document
- [x] Schedule meeting with an engineer for Datadog walkthrough (if needed)

**Comment by nnicholas7** [comment]
Update: Firmed up questions for data analytic meeting. Will continue to work on understand Datadog and creating open questions for engineering team and others.

**Comment by nnicholas7** [comment]
Update: Met with Sam on Team 1 and Steve A to get a tour of Datadog and help answering open questions.  Updated the the source of truth document with answers.

Single Source of Truth: Domo/ Analytics Resources: https://docs.google.com/document/d/19Cfs8L1SmUaRUsWbOF35Y0BUsYz_c-QtlIltO6LEp3Y/edit

**Comment by nnicholas7** [comment]
Update: Julie P spoke with Shaun and Thomas about Domo and Data Analytics for now this ticket is on hold.

**Comment by nnicholas7** [comment]
These two tickets are linked: https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/75414

**Comment by juliepedtke** [comment]
Wrote up a summary of where we landed on our effort to calculate drop-off rates for 526 https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/research/526Analytics.md
