### ISSUE TITLE
Prepare for Schema Transport

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#7587]
## Goal
How does `vets-website` schema look when moved to `vets-json-schema`?  What is the intensity and what are the potential pitfalls?

## Considerations
- `vets-json-schema` is used to validate but is not used to form the data; there is a hook to use to form it into a different format
- Talk with other teams about how this schema should be formed
  - What is difficult to match?
  - Can we check some code?
  - Is there anything that people ensure they **don't** do with this sort of thing.
  - What parts of the data model are set in stone and can't be adjusted.
- This will help inform how the connection will be conducted between BE and FE

## Acceptance Criteria
- [x] Define and document in GH the findings from this preparation

**Comment by cohnjesse** [comment]
Created a MD file for this https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/engineering/moving-to-vets-json-schema-repo.md
