### ISSUE TITLE
[Bug] Update Top Recommendation links for File a Claim While Overseas

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#7588]
## User Story or Problem Statement
As an active-duty service member overseas, I need access to the proper website so I can file claims.

Currently the top recommendations on search are pointing to the wrong URLs for these two pages. 

Current top recommendations: https://www.va.gov/search/?page=1&query=BDD

The correct URLs are: 
- https://www.va.gov/disability/how-to-file-claim/when-to-file/pre-discharge-claim/file-while-overseas/
- https://www.va.gov/disability/how-to-file-claim/when-to-file/pre-discharge-claim/

## Goal
Top recommendations point to the correct URLs for filing claim while overseas and for pre-discharge claims

## Objectives or Key Results this is meant to further
- Those visiting VA.gov will connect to the correct page from our top recommendations.
---
## Tasks
- [ ]  Update search.gov info to point to correct URLs

## Acceptance Criteria
- [ ] Top recommendations link to working websites
---

**Comment by kelsonic** [comment]
I have no clue who to contact since this is a search.gov issue:

![image](https://user-images.githubusercontent.com/12773166/81313612-54ea3600-9045-11ea-85a9-bfc1aa89ed6a.png)

The staging environment's `robots.txt` specifically says **do not index staging**, which means search.gov is indexing anyways and is not respecting the `robots.txt` content 🤔Any idea who we could notify on the search.gov side to fix this? CC @MickinSahni @stephorkandatx @ncksllvn

**Comment by ncksllvn** [comment]
I think we can add a [`noindex` meta tag](https://support.google.com/webmasters/answer/93710?hl=en) into pages during non-prod builds via the shared template for some extra crawl-blocking

**Comment by MickinSahni** [comment]
> I have no clue who to contact since this is a search.gov issue:

> The staging environment's `robots.txt` specifically says **do not index staging**, which means search.gov is indexing it anyways and is not respecting the `robots.txt` content 🤔Any idea who we could notify on the search.gov side to fix this? CC @MickinSahni @stephorkandatx @ncksllvn 

We have Search.gov contacts @stephorkandatx can reach out to confirm. iirc google stopped or was going to stop support for robots.txt noindex. wonder how that factors in here

**Comment by kelsonic** [comment]
Oh wow, well that could have definitely caused it then @MickinSahni. I'll see if I can update how we're using robots.txt to use only supported robots.txt options.

https://www.searchenginejournal.com/google-robots-txt-noindex/314961/

**Comment by ncksllvn** [comment]
>  iirc google stopped or was going to stop support for robots.txt noindex

Wow, yeah, Google is gonna be showing some interesting results for webpages (not just va.gov) then once that's fully in effect lol.

**Comment by stephorkandatx** [comment]
@johnhashva do you have a recommendation for someone we can reach out to on the search.gov team to let them know about this bug and see if they can investigate or make suggestions on resolution?

**Comment by stephorkandatx** [comment]
@johnhashva Nevermind, just noticed that @kelsonic created a PR.
@kelsonic do we need to reach out to search.gov team still or hold for now?

**Comment by kelsonic** [comment]
@stephorkandatx We can hold for now, @ncksllvn and I are experimenting with adding noindex meta tags on non-prod environments to see if that will resolve this 🙂

**Comment by kelsonic** [comment]
We just need to wait until we're confident search.gov has reindexed/attempted to crawl those staging pages, at which point if those links still show up in search we know our experiment has failed. If they don't show up, then it's been a successful experiment! 👨‍🔬💥

**Comment by stephorkandatx** [comment]
Thank you for the update! I will leave this alone for the time being

**Comment by johnhashva** [comment]
FYSA: Nick and I have a call with our Search.gov POCs next Tuesday and can surface this topic.  We will want to determine if this will impact our organic (Google) search results as well.

**Comment by stephorkandatx** [comment]
We made an update, but it does not appear to have had an impact on the production user experience. 

We have validated that robots.txt is correct. We have made sure that these pages have no-index.

**Comment by stephorkandatx** [comment]
We believe this will need to be investigated by search.gov
