### ISSUE TITLE
Military Branch selections on Review Page should only display selected branches

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#75888]
## Issue Description

On the [Review page of the form](https://staging.va.gov/pension/application/527EZ/review-and-submit), all the military branches are displayed on this page, whether they were selected or not. This page should only show military branches that were selected when the veteran answered this question.

Example:

<img width="405" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzlPQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f2393156c2b03c12a205d80a31b847dcd61aa281/Screenshot%202024-02-12%20at%202.36.21%E2%80%AFPM.png" alt="Screenshot 2024-02-12 at 2.36.21 PM.png" />

## Acceptance Criteria
- The Review page of the online form will only display the military branches selected by the veteran when they answered that question.

**Comment by aplatt-coforma** [comment]
Change looks good on staging
<img width="1268" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTkxQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8cee9bec36995b8bc004d3447079d178077bc802/Screenshot%202024-02-20%20at%2012.06.21%E2%80%AFPM.png" alt="Screenshot 2024-02-20 at 12.06.21 PM.png" />
