### ISSUE TITLE
Add Close Browser text to ToU Decline Error Page

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#75894]
Due to a bug within the patient portal and SSOe flows, users aren't able to log back in to the patient portal if they decline terms within the same browser session.

To reproduce the issue:
1. Login to the patient portal (https://staging-patientportal.myhealth.va.gov/)
2. log out the user on the patient portal
3. login on staging.va.gov, decline terms (this logs you out)
4. in the same browser, attempt to login again to the patient portal
5. you will be redirected back to the USiP, in the url bar you will see a message that indicates the idp terminated the session which doesnt allow the user to login.

FIX:
1. Add language to the terms of use [decline error page](https://staging.va.gov/terms-of-use/declined) that indicates to the user they must close their browser window if they wish to attempt a login and accept terms, otherwise they may see an error if the cookies aren't cleared out.
 

## Acceptance Criteria
> Generated by [Zenhub AI](https://www.zenhub.com/ai)

- [x] **Scenario: Add Close Browser text to ToU Decline Error Page**
  - Given the user is on the terms of use decline error page
  - When the user reads the page content
  - Then the page should include language indicating that the user must close their browser window if they wish to attempt a login and accept terms
  - And the language should also mention that not closing the browser window may result in an error if the cookies are not cleared out

**Comment by kdmeg-bluetiger** [comment]
Thanks for adding me to this one! I checked in with the CAIA team and looped them in through the original issue where we drafted this language. I added my thoughts in [this comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63260#issuecomment-1946334155) for input from the team.
