### ISSUE TITLE
[8/15/19] QA launch of explore.va.gov retirement

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#759]
The following table is the configuration of the explore.va.gov-to-www.va.gov redirects, to be completed following the launch captured in this [ticket](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19005):

Explore VA Page | Destination |
--- | --- | 
Benefits/EmploymentResource | https://www.va.gov/careers-employment/?from=explore.va.gov |
employment-services/vocational-rehabilitation | https://www.va.gov/careers-employment/vocational-rehabilitation/?from=explore.va.gov  |
assistance | https://www.va.gov/?from=explore.va.gov  |
benefits-navigator | https://www.va.gov/?from=explore.va.gov  |
disability-compensation/disability-rating-and-rates | https://www.va.gov/disability/about-disability-ratings/?from=explore.va.gov  |
disability-compensation/spouses-dependents-survivors | https://www.va.gov/burials-memorials/dependency-indemnity-compensation/?from=explore.va.gov  |
disability-compensation | https://www.va.gov/disability/?from=explore.va.gov  |
education-training/gi-bill | https://www.va.gov/education/about-gi-bill-benefits/?from=explore.va.gov  |
education-training/job-training | https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/on-the-job-training-apprenticeships/?from=explore.va.gov  |
education-training/montgomery-gi-bill | https://www.va.gov/education/about-gi-bill-benefits/?from=explore.va.gov  |
education-training/scholarships-grants | https://www.va.gov/education/?from=explore.va.gov  |
education-training/spouses-dependents-survivors | https://www.va.gov/education/survivor-dependent-benefits/?from=explore.va.gov  |
education-training | https://www.va.gov/education/?from=explore.va.gov  |
employment-services/counseling | https://www.va.gov/careers-employment/education-and-career-counseling/?from=explore.va.gov  |
employment-services/employment-benefits | https://www.va.gov/careers-employment/vocational-rehabilitation/?from=explore.va.gov  |
employment-services/spouses-dependents-survivors | https://www.va.gov/careers-employment/dependent-benefits/?from=explore.va.gov  |
employment-services | https://www.va.gov/careers-employment/?from=explore.va.gov  |
events | https://www.va.gov/outreach-and-events/events/?from=explore.va.gov  |
file-claim | https://www.va.gov/disability/how-to-file-claim/?from=explore.va.gov  |
file-disagreement | https://www.va.gov/decision-reviews/?from=explore.va.gov  |
forms/VBA-21-0958 | https://www.va.gov/decision-reviews/?from=explore.va.gov  |
forms/VBA-21-0966 | https://www.va.gov/disability/how-to-file-claim/?from=explore.va.gov  |
forms/VBA-21-526EZ | https://www.va.gov/disability/how-to-file-claim/?from=explore.va.gov  |
health-care/assisted-living | https://www.va.gov/health-care/about-va-health-benefits/long-term-care/?from=explore.va.gov  |
health-care/dental | https://www.va.gov/health-care/about-va-health-benefits/dental-care/?from=explore.va.gov  |
health-care/family-health-care | https://www.va.gov/health-care/family-caregiver-benefits/?from=explore.va.gov  |
health-care/mental-health | https://www.va.gov/health-care/health-needs-conditions/mental-health/?from=explore.va.gov  |
health-care/spouses-dependents-survivors | https://www.va.gov/health-care/family-caregiver-benefits/?from=explore.va.gov  |
health-care/vet-center-services | https://www.vetcenter.va.gov|
health-care/vision | https://www.va.gov/health-care/about-va-health-benefits/vision-care/?from=explore.va.gov  |
health-care-affordable-care-act | https://www.va.gov/health-care/about-affordable-care-act/?from=explore.va.gov  |
health-care | https://www.va.gov/health-care/?from=explore.va.gov  |
home-loans-and-housing/adaptive-home-and-vehicle | https://www.va.gov/housing-assistance/disability-housing-grants/?from=explore.va.gov  |
home-loans-and-housing/refinancing | https://www.va.gov/housing-assistance/home-loans/loan-types/?from=explore.va.gov  |
home-loans-and-housing/spouses-dependents-survivors | https://www.va.gov/housing-assistance/home-loans/surviving-spouse/?from=explore.va.gov  |
home-loans-and-housing | https://www.va.gov/housing-assistance/?from=explore.va.gov  |
intent-to-file | https://www.va.gov/disability/how-to-file-claim/?from=explore.va.gov  |
life-insurance/spouses-dependents-survivors | https://www.va.gov/life-insurance/?from=explore.va.gov  |
life-insurance | https://www.va.gov/life-insurance/?from=explore.va.gov  |
memorial-benefits/funeral-services | https://www.va.gov/burials-memorials/?from=explore.va.gov  |
memorial-benefits/spouses-dependents-survivors | https://www.va.gov/burials-memorials/?from=explore.va.gov  |
memorial-benefits | https://www.va.gov/burials-memorials/?from=explore.va.gov  |
outreach-materials | https://www.va.gov/outreach-and-events/outreach-materials/?from=explore.va.gov  |
outreach-sharing | https://www.va.gov/outreach-and-events/outreach-materials/?from=explore.va.gov  |
pension/spouses-dependents-survivors | https://www.va.gov/pension/survivors-pension/?from=explore.va.gov  |
pension | https://www.va.gov/pension/?from=explore.va.gov  |
share/benefits-for-veterans | https://www.va.gov/outreach-and-events/outreach-materials/?from=explore.va.gov  |
share/did-you-know-health-care | https://www.va.gov/outreach-and-events/outreach-materials/?from=explore.va.gov  |
share/did-you-know-memorial-benefits | https://www.va.gov/outreach-and-events/outreach-materials/?from=explore.va.gov  |
share/help-the-veterans-in-your-life | https://www.va.gov/outreach-and-events/outreach-materials/?from=explore.va.gov  |
share/honor-veterans | https://www.va.gov/outreach-and-events/outreach-materials/?from=explore.va.gov  |
share/now-that-you-are-home | https://www.va.gov/outreach-and-events/outreach-materials/?from=explore.va.gov  |
share/spread-the-word-va-home-loans | https://www.va.gov/outreach-and-events/outreach-materials/?from=explore.va.gov  |
share/transition-to-life-after-the-military | https://www.va.gov/outreach-and-events/outreach-materials/?from=explore.va.gov  |
spouses-dependents-survivors | https://www.va.gov/family-member-benefits/?from=explore.va.gov  |
video/compensation-greg | https://www.va.gov/outreach-and-events/outreach-materials/?from=explore.va.gov  |
video/compensation-overview | https://www.va.gov/outreach-and-events/outreach-materials/?from=explore.va.gov  |
video/education-chris | https://www.va.gov/outreach-and-events/outreach-materials/?from=explore.va.gov  |
video/education-overview | https://www.va.gov/outreach-and-events/outreach-materials/?from=explore.va.gov  |
video/employment-jason | https://www.va.gov/outreach-and-events/outreach-materials/?from=explore.va.gov  |
video/employment-overview | https://www.va.gov/outreach-and-events/outreach-materials/?from=explore.va.gov  |
video/explore-va-benefits-overview | https://www.va.gov/outreach-and-events/outreach-materials/?from=explore.va.gov  |
video/health-care-jackie | https://www.va.gov/outreach-and-events/outreach-materials/?from=explore.va.gov  |
video/health-care-natasha | https://www.va.gov/outreach-and-events/outreach-materials/?from=explore.va.gov  |
video/health-care-overview | https://www.va.gov/outreach-and-events/outreach-materials/?from=explore.va.gov  |
video/health-care-pete | https://www.va.gov/outreach-and-events/outreach-materials/?from=explore.va.gov  |
video/home-loans-eiler | https://www.va.gov/outreach-and-events/outreach-materials/?from=explore.va.gov  |
video/home-loans-overview | https://www.va.gov/outreach-and-events/outreach-materials/?from=explore.va.gov  |
video/housing-grant | https://www.va.gov/outreach-and-events/outreach-materials/?from=explore.va.gov  |
video/how-to-share | https://www.va.gov/outreach-and-events/outreach-materials/?from=explore.va.gov  |
video/life-insurance-josh | https://www.va.gov/outreach-and-events/outreach-materials/?from=explore.va.gov  |
video/life-insurance-overview | https://www.va.gov/outreach-and-events/outreach-materials/?from=explore.va.gov  |
video/memorial-overview | https://www.va.gov/outreach-and-events/outreach-materials/?from=explore.va.gov  |
video/memorial-winnie | https://www.va.gov/outreach-and-events/outreach-materials/?from=explore.va.gov  |
video/pension-jim | https://www.va.gov/outreach-and-events/outreach-materials/?from=explore.va.gov  |
video/pension-overview | https://www.va.gov/outreach-and-events/outreach-materials/?from=explore.va.gov  |
video/spouses-dependents-survivors-overview | https://www.va.gov/outreach-and-events/outreach-materials/?from=explore.va.gov  |
video/vet-center-comp | https://www.va.gov/outreach-and-events/outreach-materials/?from=explore.va.gov  |
video-gallery | https://www.va.gov/outreach-and-events/outreach-materials/?from=explore.va.gov  |
. (catch-all) | https://www.va.gov/?from=explore.va.gov |

**Comment by ncksllvn** [comment]
@tlei123 We have a launch coming up in a couple weeks for retiring the `explore.va.gov` domain using the redirect mapping indicated in the issue description. I wrote up this ticket for the support team to help us confirm a successful launch while we're on the call together. Can you read through this and see if makes sense?

FYI I also added a `vsa-support` label with the sweet solid black background 😮 Feel free to [change that](https://github.com/department-of-veterans-affairs/va.gov-team/labels?utf8=%E2%9C%93&q=vsa-support) if you like.

**Comment by tlei123** [comment]
@ncksllvn, yes I understand this ticket, thx!

I was gonna create a manual testing matrix, but considering server-side redirects are browser- & device-agnostic I think the matrix you have in the Description above will do just fine.

**Comment by tlei123** [comment]
[e2e test](/tlei123/489354559aa83a4bbf4c44731eb0a563) created based on redirects-table.

Not to be saved into vets-website repo, as this is not testing anything within the codebase there.

**Comment by tlei123** [comment]
All redirects are working!  Closing ticket now.
