### ISSUE TITLE
Write a broken link checker design document

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#7590]
## Background
The current broken link checker prevents content from being deployed and slows the content build process. (Context: The slowest part is the bit where we parse all HTML files; the link checking step is pretty quick itself.)

## Task
Write a design document to move the broken link checker out of the content build into a scheduled job.

## Possible approaches
I can think of three possible approaches to this scheduled link checker:
1. Run a browser test against VA.gov and check all the links
1. Run the link checker in a docker container which `aws s3 cp --recursive <bucket> ./site`. From here, we have two options:
    1. Run a browser test against this locally-hosted site
    1. Read and parse all the HTML pages like the current step in the build script is doing, then use Cheerio (or similar) to check for broken links in the DOM

**Comment by meganhkelley** [comment]
This was completed by CMS team: https://github.com/department-of-veterans-affairs/va.gov-team/pull/14092
