### ISSUE TITLE
[FE] Add New "Arrive at facility?" Page

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#75938]
## Background
There have been some issues with the timing of Veterans being called back for their appointments based on when they completed eCheck-in.  We are being asked to change the wait-time wording once a Veteran complete eCheck-in to make it more explicit and help alleviate the issues that we are seeing.

## Wireframes
- [Have you arrived page](https://www.figma.com/file/XYoHvDxgB2BpZIo2rrhFba/Check-in-%7C-Check-in?type=design&node-id=921-6177&mode=design&t=Ey56DN1JGGgbfjd2-4) 
- [Success page if answered Yes to have you arrived](https://www.figma.com/file/XYoHvDxgB2BpZIo2rrhFba/Check-in-%7C-Check-in?type=design&node-id=921-6207&mode=design&t=Ey56DN1JGGgbfjd2-4)
- [Success page if answered No to have you arrived](https://www.figma.com/file/XYoHvDxgB2BpZIo2rrhFba/Check-in-%7C-Check-in?type=design&node-id=921-6190&mode=design&t=Ey56DN1JGGgbfjd2-4)

## Tasks
- Add the new "Have you arrived at your VA health facility?" page (see wireframes for content)
- Store answer in REDUX form.data
- Add the GA events for Yes/No
- Change content on complete page based on answers
- Unit tests for new page and complete page scenarios
- Cypress tests for answering yes and no
- Add pass through to all existing cypress tests answering yes

**Comment by loripusey** [comment]
@brianseek @wullaski @lee-delarm6 This ticket and the related one are supposed to be released this sprint; are we going to make that?

**Comment by benbrasso-agile6** [comment]
@loripusey FYI, I added the Yes / No button GA Event into both the Figma File and the [Google Doc](https://docs.google.com/spreadsheets/d/1BPOlI6vzH-tMTswvUrci3Q0NkBmfIIfo8Cgj_nM10gk/edit?usp=sharing)

**Comment by loripusey** [comment]
validated branch against the Figma designs
