### ISSUE TITLE
[VeText] Update the Reply to Texting "Check in"

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#75941]
## Background
There have been some issues with the timing of Veterans being called back for their appointments based on when they completed eCheck-in.  We are being asked to change the wait-time wording to make it more explicit and help alleviate the issues that we are seeing.

## Wireframes
[Wireframes](https://www.figma.com/file/pnR05o7NPJDS0KFUSQ0eE3/Check-in-%7C-Check-in?type=design&node-id=921-6175&mode=design)

## Tasks
- Update the Content for the reply to texting "Check in"

**Comment by loripusey** [comment]
@jwowk the CIE team would like to change the wording for the 45-minute reminder SMS; please let us me when you might be able to fit this work into your VeText backlog.

**Comment by loripusey** [comment]
Thanks @jwowk , the updated verbiage is in this [wireframe](https://www.figma.com/file/pnR05o7NPJDS0KFUSQ0eE3/Check-in-%7C-Check-in?type=design&node-id=921-6175&mode=design)

**Comment by jwowk** [comment]
@loripusey the VEText team would like to propose the below verbiage. We have been testing with one site and should have some feedback soon.

Have you arrived for your %APPOINTMENT_DATE%, %APPOINTMENT_TIME% appointment with VA?  Check in upon arrival at %CHECK_IN_URL% 

For any check-in issues, seek help from a staff member at your VA health facility.

**Comment by loripusey** [comment]
@benbrasso-agile6 can you compare the VeText team's suggestion with what we proposed?
cc: @kellysmith1008

**Comment by benbrasso-agile6** [comment]
Good here

**Comment by benbrasso-agile6** [comment]
Updated our file for documentation consistencies

**Comment by jwowk** [comment]
VEText updated verbiage on 2/16

**Comment by loripusey** [comment]
changes have gone to production, closing this ticket.
