### ISSUE TITLE
SOCKS access for Isaac Gallup - troubleshooting

### ISSUE THREAD

**Issue by IGallupSoCo** [department-of-veterans-affairs/va.gov-team#75959]
### Your Name

Isaac Gallup

### Your Email

igallup@thesocompany.com

### Your Role and Team

QA Engineer - Platform Reliability Team

### Product Manager (PM) name and email

Joseph Tice - joe.tice@oddball.io

### Product Owner (PO) name and email

Joseph Tice - joe.tice@oddball.io

### Access Type Requesting

platform

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC9y8tCyuGNEDaRTCJ4mB88MSAIx+si23m/Q71QGU7VX9GhtHyyqUEDxWLS8tWZULXM2WxHObAGx5TQ09xKKZG5ZjnQ53OCZGyvkW/0/qrTF4gnd2valeQNBxAVpRR9MWWbXC6ECZ/i2j/6VxAfMOI8+E2QF+qB2SgPTSp5FkXkNNVpVWJcvVGniImqVFLIY8FNDcswxsSQUYo7SmKRGaDdD7lfVfVpsX9eyU8yIoCi6YNTLoaLsGP0hQOxdHdKlZKZmA/qGjRAdN5dm9L1laHB99QhDGXUZkRrfh7GZcu/0oeZje4aBwbzXEoMAI9377QqTMTTj70O4Dy6laXUDX5UWBrI3a1ByEekr1HuZWcgv6dgsT4/VlLAYmy9IxtB3BHjzNcYFPYsqYe8PWTJeFx294XTHp/I2065VSVZZ4sWKAyJ3g3chHNs3iZR5CuE1EoEVpgz3if4qTfH0qqq2c8sInU3tuziGqWZ/w3+cFiGGGU/H8LDXVguwrY3u0Qz1Es= isaacgallup@Isaac-Gallup.local

### E-QIP Transmittal Confirmation

I've done this already but can do it again if needed.  I decided to nuke everything SOCKS on my local machine after not being able to fix my proxy.  I've got a new key ready to go in the hopes I can get this working by the end of the day.

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by stoiven** [comment]
@JoeTice can you provide a screenshot again of your e-quo transmittal confirmation?

**Comment by stoiven** [comment]
Sorry for the delay! @JoeTice I went and merged. Can you let me know if it works?
