### ISSUE TITLE
Access for Katie Ho

### ISSUE THREAD

**Issue by katieho-va** [department-of-veterans-affairs/va.gov-team#7595]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Crystal Moultrie
- Please provide your name.
   > Katie Ho
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Team: @thoughtworks
Role: Developer
Company: ThoughtWorks

   > I am part of a team at ThoughtWorks that is working on COVID-19 Chatbot prototypes. I am requesting access to the SOCKS proxy and Jenkins / Prometheus / Grafana so we can:
   > - Modify / update Jenkins job configs 
   > - Kick off Jenkins jobs
   > - Review Prometheus data
   > - Review Grafana data
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDGbwOL/Gs/KGtMCW3IEkMV4amsn2srs7fipUEjrwRpdxnSHgAyuo4ceWkLMByq9CUsbILKh6YUOftaEvqK3jKWR5QwYs1TtML5Rzs/iw4vJUGt/m1R+eNT/tf71nTi7dBPgExHcbYlx+H5AvB0IdmsMqRQ291niTALe4JJ9uP80bNOFu9pMAN+mfoYHapoA96hTrUgwOwZGjHjvFp9/7/xmokMjLagw9tjQYnz4ClzXFn1vMvBWnBIbJl39ApuZAIy2pYpxAcKzWx8zYWT5b6KkwbHSRRUauuNNt0MtEkA4r/3yJncwgnQZ65z1owKkknSvCWYWctLqQf3D1Juw9jD kho@thoughtworks.com
```

- [Grant AWS Console access?]
  > NO

**Comment by katieho-va** [comment]
@department-of-veterans-affairs/vsp-operations please review

**Comment by tskinn** [comment]
@katieho-va you should be able to connect to the socks proxy. Reach out in slack if you have any issues.
