### ISSUE TITLE
KPI Tracking -  Identify Methods to Gather Analytics on Customer Support Requests

### ISSUE THREAD

**Issue by jchasia-adhoc** [department-of-veterans-affairs/va.gov-team#7597]
### **Problem Statement** ### 
How might we track and analyze customer support requests from VFS team?

###  **Measuring Success (KRs/KPIs)** ### 
* % of customer support requests that are categorized

### **Goals** ### 
* Categorize 80% of customer support requests over a month period
* Document VFS teams experiences requesting support along their user journey.
* Recommend methods to track support interactions
* Identify areas with high burdens of manual support 

### **Assumptions and Hypotheses**  ### 
We assume that the burden of tracking support should fall primarily on VSP, so that we can maintain the current low barrier for VFS teams to interact with us.
We hypothesize that if we standardize tracking of customer support across all of VSP, then we will be able to identify “problem areas” with high burdens of manual support to be prioritized in future VSP initiatives.

### **Questions for Discovery** ###
* What methods and tools could we use to track and analyze customer support requests?
* What types of support requests have high burdens of manual support?
* At what points during their user journey do VFS team members request different types of support?

Links
https://app.zenhub.com/workspaces/vsp-5cedc9cce6q

## we will know we're done when:
- We have something we can report to VSP peers and DEPO about customer support request

**Comment by joanneesteban** [comment]
## Potential Definitions for Support

Platform KPI: Volume of “non-human-needed” support requests per month	

**High Level:**
How might we determine what "non-human-needed" support requests mean?
How might we determine a consistent support tracking across _all_ Platform teams?
How might we improve our supporting pain points across _all_ Platform teams?

Categories:
- Question: Support work that relates to a one-off question received by a VFS user from Slack, email, etc.
- Incident: Support work that relates to a bug or reported incident on VA.gov.
- Request: Support work that relates to a formal collaboration cycle-driven request.
- Self-Reported (or a better way to phrase this): Support work that was self-determined by a VSP team member to improve a process or product.
- External Support: Support work that related to a request or question received by a customer who is not VFS.

^which of these categories is higher than others? Does that align with and verify Service Design's researched pain points from user sentiment? How difficult is it to manually track these?

**Team by Team**
How might we improve our support pain points (like time it takes & number of requests for each product/service) within our teams on VSP?

**Categories**
- Tracking by Product/Service

^Based off of the products/services compared to the support types, are there specific products/services that we should be prioritizing for automation?
