### ISSUE TITLE
Access for Shefali Nayak

### ISSUE THREAD

**Issue by shefalinayak** [department-of-veterans-affairs/va.gov-team#7598]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Crystal Moultrie
- Please provide your name.
   > Shefali Nayak
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Team: @thoughtworks
Role: Developer
Company: ThoughtWorks

   > I am part of a team at ThoughtWorks that is working on COVID-19 Chatbot prototypes. I am requesting access to the SOCKS proxy and Jenkins / Prometheus / Grafana so we can:
   > - Modify / update Jenkins job configs 
   > - Kick off Jenkins jobs
   > - Review Prometheus data
   > - Review Grafana data
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDEjTCnKsW09K912r8uAguwitzBzurbv4GthVIqY6r92UkNzpU00aRZJpuRrEViEUAKqiR8FzUimOmAlUA4GrH8i4RGn0/5g4REWpUA7E11WD/xtcQA/+7KXwKQZEVBO83pFNq3m3Ue3ZVz8kMuteSlGoMioHn577RWWvmlSNDyopS6qQ2vdSJUOyy4kq72PWwKZ2D2b2FshXdNtwJ6eHbtnurX6VjAQ3pAqRmnj7JwGYro3oc7qGmGFB3pnEhvzxAOC4UVGqCtYdvQwAwLi/yyu4p47ZJTUC5RvzCWgAwHkKrJcEUhhf7l9ydQ/jzA0R48qV1l6TjzoCyCRakLy2Jn shefali.nayak@thoughtworks.com
```

- [Grant AWS Console access?]
  > NO

**Comment by tskinn** [comment]
@shefalinayak you should be able to connect now. Reach out in slack if you have any issues.
