### ISSUE TITLE
[Data Definitions] - Spike - Handle inaccurate data definition version on vets-website

### ISSUE THREAD

**Issue by mjknight50** [department-of-veterans-affairs/va.gov-team#75992]
# Overview 
If the [payload passed](https://github.com/department-of-veterans-affairs/va.gov-team/issues/75963) to vets-api has a data definition number or vets-json-schema number that is wrong, we need to handle this on the front-end with an error.

It's also possible we will just redirect the user back to the start of the form and force a refresh.  
This ticket will need to be considered in conjunction with https://github.com/department-of-veterans-affairs/va.gov-team/issues/75990

If the user is authenticated, forcing the user back to the beginning isn't awful, but an authenticated user could be a real issue.  

If the migrations on vets-api are good enough, we really shouldn't need to do this, but this is a error handling situation we need to deal with on vets-website.

# Tasks
- [ ] - Provide an error message to the user that makes sense.
- [ ] - Force a behavior on the client that will ensure that the client gets the proper data definitions version.

**Comment by aplatt-coforma** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/75992?planning-poker) with Zenhub @scottsdevelopment

**Comment by mjknight50** [comment]
We've decided to now pursue at this time.
