### ISSUE TITLE
Uploading documents - Form documentation - design.va.gov

### ISSUE THREAD

**Issue by jaredcunha-usds** [department-of-veterans-affairs/va.gov-team#76]
This will be a description of document upload patterns under forms in the patterns section.

Here are some points. These bullet points are not in any particular order.

Use cases
- I'm claiming a benefit, and there is a related application to that that i need to upload in order to get this benefit.
- I'm claiming a benefit, and I need to upload my DD214 or other evidence as part of the application.
File size
- 25MB ???
File format
- (YES: JPEG, PDF, PNG, GIFs, DMP, NO: Zips, .doc, xlsx, ppt, raw xray image) Disallow forbidden formats at the OS level
What happens after I upload - once I have done that??
- show file name under the upload button.
- We are working on a function that allows users to clarify what a file name means or change the file name on upload.
- When there are specific file types we are looking for in an application, we can ask for them by name (e.g. Upload your birth certificate. Upload your DD214. and change your filename)
How do i remove a document I uploaded?
- There is a remove button right after the file name.
Multiple file select
- We do not have this functionality at this time. Future state. Currently must do one at a time.
Errors on upload
- timeouts
- file size/format errors
- when do we notify?

You may submit your write-up as a comment on this issue. Happy to help if you have any questions.

**Comment by Mottie** [comment]
I just opened a ticket to research allowing a user to upload multiple files at once: #7139

**Comment by caw310** [comment]
Closing as there was a more recent request that should address this request..
