### ISSUE TITLE
Redis Upgrade: Notify teams about maintenance windows for their monitors.

### ISSUE THREAD

**Issue by flooose** [department-of-veterans-affairs/va.gov-team#76007]
## Problem

Like the monitors for the platform on-call rotations, we need to communicate to other teams that they need to mute any monitors that might fire during the upgrade window. This is an administrative task and needs to be communicated in ToTs meetings.

Communications plan can be found [here](https://vfs.atlassian.net/wiki/spaces/PPT/pages/3000532995/Redis+Prod+Upgrade+Communication+Plan)

**Comment by rmtolmach** [comment]
blocked for now. Waiting on a date for upgrade (and for Jennifer to be back 😄)

**Comment by jennb33** [comment]
Updated teams in Slack channels on 3/18
