### ISSUE TITLE
Redis Upgrade: Maintenance Window Preparation

### ISSUE THREAD

**Issue by flooose** [department-of-veterans-affairs/va.gov-team#76016]
## Problem

Among other things, the maintenance windows in PagerDuty are used as a means of communicating planned maintenance. For this reason, we need to create and document such a maintenance window.

This ticket is in reference to maintenance windows needed for PagerDuty and Content build resources and details.

**Comment by jennb33** [comment]
This ticket is pending the final date confirmation, and the SNOW ticket confirmation by OCTO/Jeff

**Comment by flooose** [comment]
I'm in communication with Lindsay Insco on the support team, who's doing the brunt of the work. We've identified the services that we feel need to have a maintenanc window and she's putting things in place. In the attached spreadsheet, the services marked in orange/yellow are services that she's sure about and the services marked in green, she's getting clarification on.[service-standards-3.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzZZQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--af2dc76f1799341ab241963454999a8e5657446a/service-standards-3.xlsx)

**Comment by rmtolmach** [comment]
Document created. See Chris's comment. Task to create the maintenance window to be added to another ticket.

**Comment by rmtolmach** [comment]
Reopening. This work falls on the support team and we need to document how to coordinate this process with the support team.

**Comment by jennb33** [comment]
Working with @lindsay-insco on this window

**Comment by jennb33** [comment]
@flooose needs to get in touch with the Content team to finalize the content. 
Then we need to clarify the timeframe of when the window needs to be deployed.
We need to clarify who from the CMS team can do off-cycle deploys to take the window down.

**Comment by flooose** [comment]
Looks like [we're all set](https://dsva.pagerduty.com/service-directory/maintenance-windows/P577WI6)

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMG5yQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cc99716a91a5561f2ff918b4ad86342d2707d6aa/image.png" alt="image.png" />
