### ISSUE TITLE
Redis Upgrade: Downtime Banner

### ISSUE THREAD

**Issue by flooose** [department-of-veterans-affairs/va.gov-team#76023]
## Problem

In order to warn users of our maintenance window, we need a banner put up prior to the planned maintenance so that users can plan accordingly.

See [this issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/74877) as a reference and for possible contacts.

Points to consider:
- [x] The current documentation indicates a different time frame for the placement of this banner than [this thread](https://dsva.slack.com/archives/C01K37HRUAH/p1706631681822679) does. This discrepancy needs to be reconciled 
- [x] This banner requires coordinating with the appropriate team to get it up. This should be taken into consideration and communication should be monitored. Follow-up stories should be created as needed.
- [x] **NEW DATE & TIME:** March 20, 2024 from 2am-5am eastern

**Comment by jennb33** [comment]
@flooose needs to get in touch with the Content team to finalize the content. 
Then we need to clarify the timeframe of when the banner needs to be deployed.
We need to clarify who from the CMS team can do off-cycle deploys to take the banner down.
