### ISSUE TITLE
Discovery - Redesign the 5655 form submission

### ISSUE THREAD

**Issue by kjsuarez** [department-of-veterans-affairs/va.gov-team#76055]
We're considering redesigning the data structure of the FSR form submission (the data we get from [here](https://github.com/department-of-veterans-affairs/vets-api/blob/742e42bdcf558521494a3bfbefdc5f771c54975d/modules/debts_api/app/controllers/debts_api/v0/financial_status_reports_controller.rb#L14) that looks like [this](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/debts_api/spec/fixtures/fsr_forms/combined_fsr_form.json)) Mull over how this data structure could be designed, taking into account the final product which we need to send to both vha and vba. ie: if we delete `selected_debts_and_copays` either way, then we can shape it however we like!

- [ ] Determine the parts of the data structure used by VBS (the form data on an `Form5655Submission`)
- [ ] Determine the parts that aren't used and can be changed
- [ ] suggest changes as needed

**Comment by HeatherRienks** [comment]
@asmithgovcio - please share any notes on what has been completed in this ticket for reference. Thanks.

@Tom-Davis

**Comment by asmithgovcio** [comment]
- Any keys other than 'view:enhancedFinancialStatusReport', additionalIncome, benefits, currEmployment, income, personalData, spCurrEmployment, and socialSecurity will be filtered out.

- Within additionalIncome, only addlIncRecords and spouse keys will be permitted. Other keys inside additionalIncome will be filtered out.

- Within benefits, only spouseBenefits keys compensationAndPension and education will be permitted. Other keys inside benefits will be filtered out.

- Within currEmployment, only the specified keys and their corresponding values will be permitted.

- Within income, only the specified keys and their corresponding values will be permitted.

- Within personalData, only the specified keys and their corresponding values under employmentHistory for both veteran and spouse will be permitted.

- Within spCurrEmployment, only the specified keys and their corresponding values will be permitted.

- Within socialSecurity, only the specified keys and their corresponding values for both spouse and socialSecAmt will be permitted.

**Comment by HeatherRienks** [comment]
@kjsuarez - I am proposing that we close this ticket, as it appears that this discovery ticket has been completed. Please take a look and let us know if there is anything else that needs to be done/added. Thanks.

cc: @Tom-Davis
