### ISSUE TITLE
Identity Team Information (Request & Support Process)

### ISSUE THREAD

**Issue by jimcconnelly** [department-of-veterans-affairs/va.gov-team#76068]
**User Story**
As a member of another [VA.gov](http://va.gov/) product team, I need to understand how the Identity Team supports my team, our product, and our product's users.

**Outputs will include:**

- Populate Slack descriptions and Github pages
- Document support processes and resources
- Create links or Slack canvases for key offerings

**Goals**

- Define our team’s knowledge and expertise
- Clarify products, services, and support offerings
- Make it easier for others to find information
- Help teams engage with our support processes
- Clarify when questions are out of scope

Our Gihub page should provide details about team leadership:
- Team POCs
   - Mike King, Product Manager
   - Jim Connelly, Product Manager
   - Joe Niquette. Engineering Lead
- Major Responsibilities of Identity Team

**Comment by kdmeg-bluetiger** [comment]
Prepping for messaging workshop activity (~1 hour)

**Outputs will include:**

- Populate Slack descriptions and Github pages
- Document support processes and resources
- Create links or Slack canvases for key offerings

**Goals**

- Define our team’s knowledge and expertise
- Clarify products, services, and support offerings
- Make it easier for others to find information
- Help teams engage with our support processes
- Clarify when questions are out of scope

**Comment by kdmeg-bluetiger** [comment]
- Started workshop framework (pending timeline for process workshop)
- Prepping slides on research findings to share why we're doing this at next team demo

**Comment by kdmeg-bluetiger** [comment]
- Created [slide deck with research findings](https://docs.google.com/presentation/d/1yjkOnF4TDzXKc6hGf9l8UBA6WxEPVQrMQae6HcgRo14/edit?usp=sharing) to set context for the brand work
- Invited attendees

**Comment by kdmeg-bluetiger** [comment]
Note: revised information will need to be approved by OCTO POs and submitted for updates via Slack Admins.

**Comment by claytonzook** [comment]
Some items will be moved out of this ticket into a follow-on

**Acceptance Criteria**
At multiple points of contact, users can get info about the Identity team:

- 1-sentence team mission statement
- 1-sentence summarizing how Identity supports other VA teams (with 1-3 specific examples)
- A link and directions on how to get in touch with us for support
