### ISSUE TITLE
Name search input returns unexpected results - need to update trigram threshold

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#76099]
## Expected vs. Actual
**Expected**: Searching for a representative's name will return any representatives that match the full name, or possibly the first or last name.  Searching for an organization will return any representatives that are associated with that organization.

**Actual**:

Unexpected Representative Name Results:
1. Search **VSO** + **48073** + **Show all** + **Name "Smith"** 
    1. Sort Last Name A-Z, top results do not contain the name "Smith" (Keith Barnes)
    1. Sort Last Name Z-A, top results do not contain the name "Smith" (Keith Barnes)
 
2. Search **VSO** + **10001** + **50 miles** + **Name "David"**
    1. Top results (when sorted by distance) are Dana, Daisy, Damian, Daniel
    1. David doesn't appear until the fifth result

Unexpected Organization Name Results:

3.  Search **VSO** + **10001** + **50 miles** + **Name "Disabled American Veterans"**
    1. When sorted by distance, the third, fourth and fifth results have representatives not a part of this organization
  
## Proposed Solution

Lindsay's proposal, open to discussion

- If the name input includes a single word, only return search results that match that word (could be first name, last name, or a word in the organization)
- If the name input includes multiple words, return search results that match that exact combination. 
    - If there are no matches, return search results that match any of the words

**Comment by oddball-lindsay** [comment]
Something to consider: this would not account for typos, where the user may want to see names that don't match their input exactly.

**Comment by holdenhinkle** [comment]
So we’re searching a rep’s full name (first last) and the org names they’re associated with.
Then they’re sorted by distance.

Staging is down so I can’t recreate the results noted here - https://app.zenhub.com/workspaces/accredited-representation-management-team-64d0dc51[…]96/issues/gh/department-of-veterans-affairs/va.gov-team/76099

But for this one:
> Search VSO + 10001 + 50 miles + Name “David”
> Top results (when sorted by distance) are Dana, Daisy, Damian, Daniel
> David doesn’t appear until the fifth result

Dana, Daisy, Damian, Daniel, and David all FUZZY match on ‘david’. The keyword is FUZZY. They all start with ‘da’ and some have the letter ‘i’ (I’m guessing that’s why they match). Then they’re sorted by distance ascending. I’m guessing David is further away than the rest, which is why he is listed 5th. Does that make sense?

And again, we’re looking for full name matches.

**Comment by holdenhinkle** [comment]
See Slack thread - https://dsva.slack.com/archives/C05L6HSJLHM/p1708025949676359

**Comment by holdenhinkle** [comment]
Todo (create new tickets):

- Remove Org name search
- Look into sorting name searches by highest match

**Comment by oddball-lindsay** [comment]
We will be upping the trigram threshold to filter search results by name more specifically.  Then this more specified list (based on the higher trigram threshold) will be returned to users, sorted by the default distance.

There may be an interest in sorting by "best match" but we will save that for a future iteration.

**Comment by cosu419** [comment]
This search returns "Keith" results for "Smith":

<img width="1014" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemhvQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--674eed2b129f312ed2e1cedb624ce21c62c83e05/image.png" alt="image.png" />

<img width="737" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemxvQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e361f243294a491ff4f48a062609d296743e392f/image.png" alt="image.png" />
