### ISSUE TITLE
Update review page display/functionality based on handoff doc #2

### ISSUE THREAD

**Issue by michaelclement** [department-of-veterans-affairs/va.gov-team#76118]
The goal of this issue is to update the review page so that it looks and behaves in line with the Figma and content source of truth handed off on 12 February. This may require adding new interactions when editing an element, and will undoubtedly require investigation into novel solutions. 

Acceptance criteria
- [ ] The review page wording and content match the Figma and SOT
- [ ] Users can edit content from the review page
- [ ] Users can review content from the review page
- [ ] Form submission is prevented if data is invalid on review page

**Comment by baltes** [comment]
No longer needed
