### ISSUE TITLE
OOB Deploy Request

### ISSUE THREAD

**Issue by longmd** [department-of-veterans-affairs/va.gov-team#76115]
# Instructions
Please fill out the necessary details and list the PRs related to the OOB deployment in the sections below.

## PRs Related to OOB
- Please provide the list of PRs related to the need for this OOB Deploy below:
   > PR27808 - The original PR that we believe could contain the culprit to the issue
   > PR27962 - The PR that contains the Revert for the OOB deployment

## Active Daily Users Impacted
- How many active users are impacted at this time and day.
   >  Approx. 870
## Has fix been confirmed in Staging?
- [ ] Yes
- [x] No

## Description
- Please provide the details/reason for the OOB Deploy
   > After the daily deploy on 02/12 the 10-10EZ application lost the ability for authenticated users to access the application. There was a PR (27808) that was a part of that deployment and that is the only PR for this application in that time period. The PR has worked in all other lower environments and no impact to functionality or users was noted until it got into the prod environment. This OOB request is a step in an effort to rectify the issue for authenticated users.
   
## Verify The following
 - [x] The OOB Deploy Request is after the 2pm EST cutoff for regular deploy.[^1] 
 - [x] The OOB Deploy Request is critical and must be resolved before the next automated deploy.
 - [x] You are prepared to create an Incident Post Mortem[^2] within two business days.

[^1]: (See [Deployment Policy](https://depo-platform-documentation.scrollhelp.site/developer-docs/deployment-policies) and [Deployment Schedules](https://depo-platform-documentation.scrollhelp.site/developer-docs/Deployments.1844641889.html)
[^2]: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/Postmortems

*Performed by Platform Support Team*
 - [x] PagerDuty OOB Deploy Incident Opened
 - [x] OCTO-DE staff acknowledgment of Request, via `/pd trigger`
 - [x] Notification is posted in the appropriate Slack support and team Channels
 - [ ] Infrastructure/Operations has acknowledge the Requests
 - [ ] Security Team has Reviewed the requests

 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/vsp-product-support

**Comment by bdech** [comment]
https://dsva.slack.com/archives/CBU0KDSB1/p1707853448756019

**Comment by bdech** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/27962
