### ISSUE TITLE
Organization Name is cut off

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#76112]
## Expected vs. Actual
**Expected**: We noticed that OGC has some organizations cut off in their data, but they fixed that and the recent Trexler File had this corrected.
<img width="511" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjVWQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--431706d01e58540d1b1096776634b7a2029aff2a/image.png" alt="image.png" />

We've processed the recent Trexler File (https://github.com/department-of-veterans-affairs/va.gov-team/issues/75776), so I was expecting to see the full organization name "National Association of County Veterans Service Officers".

**Actual**: I am still seeing the truncated "National Association of County Veterans Service Of" returned in Find a Rep search results.

## Steps to Reproduce
1. Select "VSO"
2. Enter "California"
3. Set search radius to "100 miles"
4. Enter "National Association of County Veterans Service" in the name field
5. Search
6. Expand associated organizations for first search result, Kyle Pennington

## Examples
<img width="736" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnBWQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7e86d30d931f333493a9c6780fce3c27584187e6/image.png" alt="image.png" />

**Comment by oddball-lindsay** [comment]
The Trexler File didn't fully get processed; will try updating the Trexler File again and let the team know the errors displayed are expected.

**Comment by holdenhinkle** [comment]
Sorry, I wasn't thinking. The Trexler File has nothing to do with Organizations. The names are coming from the daily OGC job. I can write a script to run in each env to update the Organization names.

**Comment by holdenhinkle** [comment]
Every time the job runs the name will get reset though:

See `modules/veteran/app/sidekiq/veteran/vso_reloader.rb`:

```
    def reload_vso_reps
      vso_reps = []
      vso_orgs = fetch_data('orgsexcellist.asp').map do |vso_rep|
        next unless vso_rep['Representative']

        find_or_create_vso(vso_rep) if vso_rep['Registration Num'].present?
        vso_reps << vso_rep['Registration Num']
        {
          poa: vso_rep['POA'].gsub(/\W/, ''),
          name: vso_rep['Organization Name'],
          phone: vso_rep['Org Phone'],
          state: vso_rep['Org State']
        }
      end.compact.uniq
      Veteran::Service::Organization.import(vso_orgs, on_duplicate_key_ignore: true)

      vso_reps
    end
```

Specifically, this:
```
      vso_orgs = fetch_data('orgsexcellist.asp').map do |vso_rep|
        next unless vso_rep['Representative']

        find_or_create_vso(vso_rep) if vso_rep['Registration Num'].present?
        vso_reps << vso_rep['Registration Num']
        {
          poa: vso_rep['POA'].gsub(/\W/, ''),
          name: vso_rep['Organization Name'],
          phone: vso_rep['Org Phone'],
          state: vso_rep['Org State']
        }
      end.compact.uniq
      Veteran::Service::Organization.import(vso_orgs, on_duplicate_key_ignore: true)
```

**Comment by holdenhinkle** [comment]
I'm going to create a job that runs daily AFTER the OGC job to update the org names.

**Comment by holdenhinkle** [comment]
PR - https://github.com/department-of-veterans-affairs/vets-api/pull/15578

**Comment by holdenhinkle** [comment]
The OGC job runs every day at 2am. I'm going to run this name update job at 5am.

**Comment by oddball-lindsay** [comment]
@holdenhinkle did a double check of the [organization file you referenced](https://github.com/department-of-veterans-affairs/vets-api/blob/db58234aa2c61b10e0eda3b5c77f93e1c4ef1346/modules/veteran/app/sidekiq/organizations/names.rb) for keeping the org names in full.  It seems like all the organizations are still cut off in this file, so calling out the full names that I grabbed from the last Trexler File -- 8 need name updates:

      { poa: '64', name: 'National Association of County Veterans Service Of' }
^ name should be `National Association of County Veterans Service Officers`

      { poa: '96', name: 'United Spanish War Veterans * NOT ACCEPTING NEW CL' },
^ name should be `United Spanish War Veterans * NOT ACCEPTING NEW CLAIMS *`

      { poa: '4R4', name: 'Veterans of the Vietnam War, Inc. & the Veterans C' },
^ name should be `Veterans of the Vietnam War, Inc. & the Veterans Coalition`

      { poa: '98', name: 'Veterans of WW I of the USA, Inc.* NOT ACCEPTING N' },
^ name should be `Veterans of WW I of the USA, Inc.* NOT ACCEPTING NEW CLAIMS *`

      { poa: '4R1', name: 'Commonwealth of the Northern Mariana Islands Divis' },
^ name should be `Commonwealth of the Northern Mariana Islands Division`

      { poa: '9', name: 'New Jersey Department of Military and Veterans Aff' },
^ name should be `New Jersey Department of Military and Veterans Affairs`

      { poa: '10', name: 'Pennsylvania Department of Military and Veterans A' },
^ name should be `Pennsylvania Department of Military and Veterans Affairs`

      { poa: '4R2', name: 'Office of Veterans Affairs American Samoa Governme' },
^ name should be `Office of Veterans Affairs American Samoa Government`
