### ISSUE TITLE
Implement calls to MAP SecurityToken Service for session creation in vets-api

### ISSUE THREAD

**Issue by cferris32** [department-of-veterans-affairs/va.gov-team#76148]
The MAP team has added appointments to their token service, meaning we should now be able to update our session token flow to consume their service. Here is an example call: 

`MAP::SecurityToken::Service.new.token(application: :appointments, icn: '12345678V123456')` 

This will replace token creation via the session endpoint that vets-api currently calls. For token refreshing, we will simply call this service again to generate a new token.

AC:
[x] - implement calls to the MAP SecurityToken Service to replace our current token creation/refresh functionality
[x] - service/request specs for new implementation

**Comment by ajmagdub** [comment]
Adding Feature toggle, **va_online_scheduling_sts_oauth_token**, for the work.

**Comment by ajmagdub** [comment]
Hi @ldelacosta 
The code has been merged and is in staging and production behind the feature toggle, **va_online_scheduling_sts_oauth_token**. I would like to attend when the testing is done in the staging environment. Thanks!

**Comment by ajmagdub** [comment]
The feature toggle was enabled in staging. Appointments are working correctly; it passed the smoke test. Production still needed to be configured by the Identity team.

**Comment by ldelacosta** [comment]
Trevor from the identity team said production should be ready by Friday. We will be able to start using it in production next week with a small percentage of users. More updates will be provided next week. cc: @ajmagdub @JRRoof @simiadebowale

**Comment by ldelacosta** [comment]
Enabled the feature toggle to 100% on 05/03. Closing out the ticket.
