### ISSUE TITLE
Consider adding underline to link text on Platform website

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#76151]
### Description

Links on the Platform website are dark blue with no default text decoration, while body text is black. It can be hard to quickly differentiate link text from regular body text. This presents obstacles for users scanning for links on the page, and could also make usability more difficult for users with difficulty differentiating colors. It would be a usability and accessibility improvement to convey that text is a link beyond the use of color - ideally by underlining links. I hope this will be considered for all links on the site, but especially links that are not part of navigation components (i.e. inline links in page content).

Attaching a screenshot of how inline text links are currently rendering (this is on the [Modernized VA.gov Accessibility Strategy](https://depo-platform-documentation.scrollhelp.site/getting-started/modernized-va-gov-accessibility-strategy) page):

![Screenshot 2024-02-13 at 4 38 16 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/755248/1ffc28fe-3a72-4095-a170-bffd5eb78fb0)

**Related:** We use "VA.gov" often on the Platform website, and it's always converted to a hyperlink. If there is any way to **not** have that happen, that'd be amazing. I had to ask!

### Relevant URLs

All of Platform website

### Which type of team are you on? (Platform team, VFS team, or Leadership)

Platform! (Governance)

**Comment by jknipes** [comment]
Research ticket created in Backlog [79060](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/79060)
