### ISSUE TITLE
Update "Creating a new application" page to include information on adding the source app to vets-api statsd middleware

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-team#76162]
### Description

When new apps are added to the registry, they should also be added to the vets-api statsd middleware configuration so that they will be recognized and the `source_app` tag will be usable in Datadog. More background in this thread: https://dsva.slack.com/archives/C0581MN69TJ/p1707862737134839

### Relevant URLs

- https://depo-platform-documentation.scrollhelp.site/developer-docs/creating-a-new-application
- https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/statsd_middleware.rb

### Which type of team are you on? (Platform team, VFS team, or Leadership)

OCTO engineer

**Comment by jknipes** [comment]
Hi @acrollet thank you for flagging this. We'll take a look, and review with some engineers to determine the best course of action for this page, and will work to get any updates reflected on the website.
We will provide further updates in this ticket. Please feel free to reach out if there are any questions.

**Comment by jknipes** [comment]
Work will be done on [76992](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/76992)

**Comment by jknipes** [comment]
@acrollet would you be the SME we should work with to write this guidance for Platform Website?

**Comment by acrollet** [comment]
@jknipes I can assist

**Comment by taylojill** [comment]
Hi there @acrollet - I'm working on your request to update the "Creating a new application" page. Please review the [page update in our draft space](https://vfs.atlassian.net/wiki/spaces/PWD/pages/3141140493/Draft+Copy+of+Creating+a+new+application). If unable to access the space, a pdf is attached.

After reading the Slack threads and messages, here's what I did:
1. I added a step (4) after step 3. 
Is this the right location? Are there more details that should be added (links, screenshots, sub-steps, etc)?

Thanks @acrollet! I look forward to your feedback.

cc @jknipes 
[PWD-Draft Copy of Creating a new application-090524-173845.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/15265843/PWD-Draft.Copy.of.Creating.a.new.application-090524-173845.pdf)

**Comment by acrollet** [comment]
Hi @taylojill , thanks for working on this! I think the location is ok, and it's good to call it out as a step. I commented on the doc with a suggestion to link to the vets-api config.

**Comment by taylojill** [comment]
Hi @acrollet - I cannot find your comment about linking to the vets-api config. Please let me know where I should add it on the page. Thank you!

cc @jknipes

**Comment by acrollet** [comment]
@taylojill confluence is kind of hiding it under the first comment! 
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/101649/11b905a6-36ad-447b-86fa-bd4d5ca2c50d)

**Comment by acrollet** [comment]
text is: 

I’d suggest linking this to [vets-api/lib/statsd_middleware.rb at master · department-of-veterans-affairs/vets-api (github.com)](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/statsd_middleware.rb#L26) to help developers know where the config is located.

**Comment by taylojill** [comment]
Thanks @acrollet - I never saw the 2nd comment! Sorry about that! I'll get the page updated and published tomorrow. 
Thank you so much!

cc @jknipes

**Comment by taylojill** [comment]
Link added as requested. Page will be checked for launch blocking issues and published May 14th.

**Comment by acrollet** [comment]
no worries, thank you for your work on this!
