### ISSUE TITLE
SOCKS access for Oren Mittman

### ISSUE THREAD

**Issue by nihil2501** [department-of-veterans-affairs/va.gov-team#76177]
### Your Name

Oren Mittman

### Your Email

oren.mittman@adhocteam.us

### Your Role and Team

Senior Fullstack Engineer on VSO Fast Track Claims / Accredited Rep Facing Team / Ad Hoc

### Product Manager (PM) name and email

Rivka Gates / rivka.gates@agile6.com

### Product Owner (PO) name and email

Jenn Bertsch / Jennifer.Bertsch@va.gov

### Access Type Requesting

developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDBEY9mtDfBIwFxKBgKWAb1T39yzQJ0SYHPmZgJMfl2pGUuTcH3tICJOYAfCPB0BkcnQ2/K5ry/pI85tAyNHoKciS/HolCTM6nmWgj4qGdAcZoM/bg+CZpj/X3uvHE3oFxF/QS6YI77fTec5oDP2ZEvd+dkdNiP5mT0uVgpHYt+C26pSOD9GZXkmSAop+NU8S1X0ft07wNw3YZrS9mpvrzyXczDfiTvkkSRTFM6tcY5vQnp4y/6rBw6H6uSe7r2v1MRfvsVf6q6Twcmlg+gzzmrxCeW4/fs2WwpFgegO4B35yCo7bukDp0swWLhb5tJgggq1OIUGfzu6iehoNPOY29Me0kDSVznkZTFtop7cHSg5eX0/xXtRDk9BgUBgWmP86dkO7QR4fj9NAo/gLSJ9czYkBbfl59l7TA4W44jeoKO+ImAQ0EVAGd3KEa702iDdKNDag+ddvsW+lEWqzOkYPpLZJmsgU/68JPYdFODMmVACcwaarcCnOLl66+DfqN9hoM= oren.mittman@orenmittman-DHQ3972P5G

### E-QIP Transmittal Confirmation

<img width="1222" alt="Screenshot 2024-02-14 at 3 00 44 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/1160307/b53fa336-a55f-4d50-91a1-cf7328873d96">

### User must exist in a roster before SOCKS access can be granted

- [x] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by Mandalorian-Oddball** [comment]
User found in Atlas.
