### ISSUE TITLE
Research and possibly remediate happy path failures around form.veteran.currentMailingAddress.refdataservice.errorResponse

### ISSUE THREAD

**Issue by tblackwe** [department-of-veterans-affairs/va.gov-team#76184]
Research and possibly remediate happy path failure 
- form.veteran.currentMailingAddress.refdataservice.errorResponse
- [Datadog Link](https://vagov.ddog-gov.com/logs?query=%40named_tags.class%3A%22EVSS%3A%3ADisabilityCompensationForm%3A%3ASubmitForm526AllClaim%22%20%40level%3Aerror%20%40payload.submission_id%3A%282426603%20OR%202452646%20OR%202454183%20OR%202456930%20OR%202457720%20OR%202457818%20OR%202457926%20OR%202458408%20OR%202458415%20OR%202458446%20OR%202458592%20OR%202460428%20OR%202464889%20OR%202469812%20OR%202479368%20OR%202483345%20OR%202485952%20OR%202494371%20OR%202504977%20OR%202511776%20OR%202564595%27%29%20&cols=host%2Cservice%2C%40payload.error_message%2C%40payload.submission_id&context_event=AY2JIxEsAAB1aZOJsTXH6QAn&index=%2A&messageDisplay=inline&refresh_mode=paused&storage=online_archives&stream_sort=time%2Cdesc&viz=&from_ts=1698811200000&to_ts=1707414600000&live=false)

## Acceptance Criteria
- [x] Determine root cause of errors
- One of the following
  - [ ] New ticket created to fix issue
  - [x] PR Opened to Fix issue
  - [ ] Comments on this ticket describing why it is not fixable at this time

**Comment by freeheeling** [comment]
**Specific error message:** `{"messages"=>[{"key"=>"form526.veteran.currentMailingAddress.refdataservice.errorResponse", "severity"=>"ERROR", "text"=>"The Reference Data Service was unable to verify the mailing address country for the claimant returned an error response"}]}`

Nothing stands out as exceptional inspecting the `currentMailingAddress` country on failed submissions, which are the same as those on successful submissions processed minutes later.

**Comment by freeheeling** [comment]
Here are the "text" messages from EVSS when Lighthouse causes a 400 status code error during a Form526 transaction. If one of these messages appears, vets-api should retry.
- The Reference Data Service was unable to verify the separation location code for the claimant returned an error response
- The Reference Data Service is unavailable to verify the separation location code for the claimant
- The Reference Data Service was unable to verify the branch of service for the claimant returned an error response
- The Reference Data Service is unavailable to verify the branch of service for the claimant
- The Reference Data Service was unable to verify the classification code for the disability returned an error response
- The Reference Data Service is unavailable to verify the classification code for the disability
- The Reference Data Service was unable to verify the mailing address country for the claimant returned an error response
- The Reference Data Service is unavailable to verify the mailing address country for the claimant
- The Reference Data Service was unable to verify the change of address country for the claimant returned an error response
- The Reference Data Service is unavailable to verify the change of address country for the claimant

**Comment by freeheeling** [comment]
[Draft PR](https://github.com/department-of-veterans-affairs/vets-api/pull/16558) to retry `refdataservice.errorResponse` messages in review.

**Comment by freeheeling** [comment]
Reviewed and am satisfied with the updates made when initially drafting the PR to reclassify Reference Data Service errors as retryable. Submitted a support ticket to request `department-of-veterans-affairs/lighthouse-dash` code owner review, which is currently holding up merging.

**Comment by freeheeling** [comment]
Last recorded in error [in DD from last 15 days](https://vagov.ddog-gov.com/logs?query=%40named_tags.class%3A%22EVSS%3A%3ADisabilityCompensationForm%3A%3ASubmitForm526AllClaim%22%20%40level%3Aerror%20%40payload.error_message%3A%22%7B%5C%22messages%5C%22%3D%3E%5B%7B%5C%22key%5C%22%3D%3E%5C%22form526.veteran.currentMailingAddress.refdataservice.errorResponse%5C%22%2C%20%5C%22severity%5C%22%3D%3E%5C%22ERROR%5C%22%2C%20%5C%22text%5C%22%3D%3E%5C%22The%20Reference%20Data%20Service%20was%20unable%20to%20verify%20the%20mailing%20address%20country%20for%20the%20claimant%20returned%20an%20error%20response%5C%22%7D%5D%7D%22%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice%2C%40payload.error_message%2C%40payload.submission_id&context_event=AY2JIxEsAAB1aZOJsTXH6QAn&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=online_archives&stream_sort=time%2Cdesc&viz=&from_ts=1713720223057&to_ts=1716312223057&live=true) was 4/30, 2 weeks before error handling updates were made.

I recommend checking logs for at least the next 2 weeks to confirm updates have intended effect.
