### ISSUE TITLE
NOD V2 Release | Midpoint Review Prep

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#76194]
### Midpoint Review
<details open>
  <summary>Toggle Midpoint Review</summary>
  
##### VFS actions
Navigate to reference link: [Midpoint Review Guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review)  
- [x] Schedule your Midpoint Review when ready:
   - Open the [Calendly midpoint review calendar](https://calendly.com/collaboration-cycle/design-intent-or-midpoint-review)
   - Select a date and time and click “Confirm”
   - Add your name and email
   - Click "Add Guests" and enter the VFS meeting attendees email addresses
      - Invite all relevant VFS team members, including accessibility support, product owners, and other VA stakeholders
   - Click "Schedule Event"
- [ ] Check this box if you'd like this review to be asynchronous (Please refer to the [Midpoint Review guidance](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) for the difference between a synchronous meeting and an asynchronous review)
- [x] Notify the Collaboration Cycle team of this event by using the `/Collab Cycle Midpoint Review` "slash-command" in your team channel. Provide information as prompted by the Slack workflow.
- [x] Link all artifacts **ONLY** in the Midpoint Review artifacts section below at least two days before the scheduled Midpoint Review.  **Do NOT add artifacts to Comments section** 

**Midpoint Review artifacts**

See Platform guidance on [Midpoint Review artifacts](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/midpoint-review#Midpointreview-Artifacts). Platform feedback is based solely on the artifacts provided, as reviewed during the two days before the Midpoint Review meeting. Any work not included in the artifacts below or any ongoing work taking place during the review period may not be reflected in that feedback.

Provide links or documents for the following:

- [x] Finalized design [prototype](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1691599300063/42cd59780f131a0a61b149f7df8aa9c7f8ae83f6?sender=ud193ce75f65a17a316ea6194)
- [x] Figma [wireframes](https://www.figma.com/file/BplQkEDZzD8NPPNmLrhvXv/Request-a-Board-Appeal-%2F-Notice-of-Disagreement-(VA-10182)?type=design&node-id=0-1719&mode=design) / [prototype](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1691599300063/42cd59780f131a0a61b149f7df8aa9c7f8ae83f6?sender=ud193ce75f65a17a316ea6194)
- [x] Specify which pages are included in the review 
  - [ ] [Request an extension](https://staging.va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182/extension-request)
  - [ ] [Reason for extension](https://staging.va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182/extension-reason)
  - [ ] [VHA Denial](https://staging.va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182/appealing-denial)
- [x] When you're done, tag Sade for review
- [x] Sade will add the info to the Collab Cycle ticket

**Comment by eileen-coforma** [comment]
Midpoint review completed.
