### ISSUE TITLE
1010D update forms with latest printed version

### ISSUE THREAD

**Issue by cloudmagic80** [department-of-veterans-affairs/va.gov-team#76191]
1010D forms have expired. New printed forms have been published. We need to update our digital forms to match the printed version

**Comment by baltes** [comment]
@cloudmagic80 Was there are PR or anything associated with this work?

**Comment by cloudmagic80** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/15546

Here is the PR. It is approved and now in master branch
cc @baltes
