### ISSUE TITLE
[SCREENREADER]: Education STEM Update - Step 6 Edit button needs an updated aria-label

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#762]
## Issue
One of sections to be edited in Step 6 has an aria label that does not match up with the section heading. This could be confusing to assistive device users. Screenshot attached below.

## Acceptance Criteria

* As a screen reader user, I want to hear "Edit Military History, button" read aloud when I focus the appropriate Edit button.

## Environment
* Windows 10
* Chrome, IE11
* JAWS

## WCAG or Vendor Guidance (optional)
* [Name, Role, Value: Understanding SC 4.1.2](https://www.w3.org/TR/UNDERSTANDING-WCAG20/ensure-compat-rsv.html)

## Screenshots or Trace Logs

![Screen Shot 2019-07-31 at 12.51.40 PM.png](https://images.zenhubusercontent.com/5ac217b74b5806bc2bcd3fc8/13205a83-a10f-4568-9582-99ecca2500a2)

**Comment by ksantiagomorgan6** [comment]
The aria labels of the edit buttons matches the title of the corresponding page (which in this case is the "Active Duty" page)

"Military History" is the title of the us-forms-system chapter.  The form data is entered and edited on the page level, which is why the edit button matches the page title.  This is the current functionality of the us-forms-system

**Comment by zurbergram** [comment]
To test you aren't actually testing if the issue was fixed 
See https://github.com/department-of-veterans-affairs/vets-website/pull/10535 for testing instructions

**Comment by sonntag-adam** [comment]
Testing passes QA for PR #10535

**Comment by zurbergram** [comment]
Changes for https://github.com/department-of-veterans-affairs/vets-website/pull/10535 are now in staging

**Comment by 1Copenut** [comment]
I reviewed this on Staging and verified the fix was present on the Education STEM form. I also tried out another form (pension application) for cross assurance. I'm good to close this issue.
