### ISSUE TITLE
QA Dashboards - Pre-Planning

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#76206]
## Description
In past years, we have repeatedly discussed the value of QA Dashboards in providing a snapshot of the quality or products and the level of consistent diligence of the teams creating them for putting out a high quality and reliable experience by a well-built product and a good team.

Years ago, we created a simple prototype to demonstrate the concept which was received well, but needed more work, and required the development of a dependable Product list to help make much of the desired functionality possible.

This effort is to plan what things are needed as part of discovery, NOT to conduct discovery itself. This will provide us the roadmap for our discovery.

NOTE - The QA Dashboard may cross over somewhat with the DORA Metrics Dashboard, ideally, we would like these two solutions to complement each other.

---

### Tasks
- [ ] Need task details

### Acceptance Criteria
- [ ] Add acceptance criteria here

**Comment by pjhill** [comment]
Did some planning in this Confluence document -- https://vfs.atlassian.net/wiki/spaces/PRT/pages/2942631976/QA+Dashboards

**Comment by pjhill** [comment]
Leaving this ticket as "in progress" pending any feedback or additional planning tasks.
