### ISSUE TITLE
[Security - Controls Effort] SBOM generation resources as IaC

### ISSUE THREAD

**Issue by hgbarreto** [department-of-veterans-affairs/va.gov-team#76207]
## Description
To meet and mature in some of our security controls, Infrastructure Services would like to create the IaC needed to support the SBOM generation resources. 

## Resources 
The resources that will be configured as Terraform can be found as a result of the work done [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/74739).

## Acceptance Criteria
Tickets to create:
- [x] TF for S3 Bucket
- [x] TF for AWS Glue Crawler
- [x] TF for Athena Queries
- [x] TF for misc items (IAM Roles, etc. )

## Refinement Guidance - Check the following before working on this issue: 
- [x] _Team label assigned ("platform-tech-team-2")_
- [ ] _Epic assigned (if needed)_ 
- [x] _Estimated (points assigned)_
- [x] _Sprint assigned (once planned)_
- [x] _Team member(s) assigned_
- [x] _Understands how this work aligns with the overall platform_

**Comment by ph-One** [comment]
Please spit up into 4 separate tickets

**Comment by hgbarreto** [comment]
Split into 4 tickets
