### ISSUE TITLE
Tech debt: remove redirect from MHV-on-VAgov landing page to MHV National Portal and associated tests

### ISSUE THREAD

**Issue by radavis** [department-of-veterans-affairs/va.gov-team#76200]
### User story

As a Veteran trying to access health-care apps, I want to stay on the MHV landing page, so that I can do what I came to do.

As a Cartographers team member, I want to remove the unused feature flag for the MHV landing page (it's always on) and any unit tests associated with it, so that simplicity and efficiency.

### Notes

- Back in August, we would [redirect users who met certain conditions](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/engineering/61496-mhvlp-redirect-bugfix.md) to the MHV National Portal. 
- Today, the landing page displays for all authenticated users.
- Thus, our [App component unit tests](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/mhv-landing-page/tests/containers/App.unit.spec.jsx#L74-L121) only redirect when the feature toggle for enabling the MHV Landing Page is turned off. 
- Question: What is the current setting for `mhv_landing_page_enabled` feature toggle in production? This feature toggle is currently enabled on dev.va.gov and staging.va.gov.

## Acceptance criteria

- [x] Verified that removing this redirect will not have negative consequences to users (e.g. - we used to redirect LOA1 users, we used to redirect only a % of users)
- [ ] Remove the call to `window.location.replace` within the MHV landing page.
- [ ] Remove associated redirect code in unit tests and e2e tests.

**Comment by wesrowe** [comment]
@radavis, when you have a few minutes, could you please provide more context on what the redirect does and how it impacts Veterans? I don't have any context on this issue.
