### ISSUE TITLE
NOD V2 Release | Contact Center Review Prep

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#76205]
### Contact Center Review
<details>
  <summary>Toggle Contact Center Review</summary>

#### VFS actions
- [ ] Complete the [Contact Center review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html)
- [ ] Link to the Contact Center review request ticket below

</details>

- [ ] When you're done, tag Sade for review
- [ ] Sade will add the info to the Collab Cycle ticket

**Comment by HeatherWidmont** [comment]
@rubensun working on documenting a draft for @saderagsdale to review today or tomorrow

**Comment by saderagsdale** [comment]
@rubensun will post a draft link here later today.

**Comment by saderagsdale** [comment]
Submitted to the Contact Center team.

**Comment by saderagsdale** [comment]
CC Ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/77077

**Comment by saderagsdale** [comment]
Waiting for feedback and approval

**Comment by saderagsdale** [comment]
Waiting for approval to close.

**Comment by HeatherWidmont** [comment]
Still waiting for approval. Contact center forwarded to another group & we are waiting to hear back

**Comment by HeatherWidmont** [comment]
Got approval, yay!
