### ISSUE TITLE
10-7959f-1 | Service Blueprint of current state of processing registration

### ISSUE THREAD

**Issue by brian-wilke** [department-of-veterans-affairs/va.gov-team#76217]
Create lightweight deliverable based on stakeholder interviews and ongoing question series

This map will be delivered in Mural for VA access and will cover the "as is" of the current process.

This will also serve as a way to share insights and recommendations for improvements within (and sometimes beyond) the scope of digitizing the 10-7959f-1

Link will be attached to this ticket to indicate "done"

**Comment by rachaelpenfil** [comment]
Closed because combining with [FMP process flow](https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/87514) ticket.
