### ISSUE TITLE
[Design] - 1010d Create prototype for user testing - Incorporate feedback from midpoint review

### ISSUE THREAD

**Issue by jamiefiore** [department-of-veterans-affairs/va.gov-team#76223]
Description
Using the static screens from [1010 Prototype for usability testing](https://github.com/department-of-veterans-affairs/va.gov-team/issues/71769) Incorporate feedback from midpoint review in the Figma file for dev handoff. 
The prototype should identify:

-  Standard patterns and components
-  New patterns and flows
-  Complicated patterns and flows

Definition of Done

-  Clickable mobile prototype
-  Design review

**Comment by syd-hoeper** [comment]
@marywang2 Feedback incorporate in this file: https://www.figma.com/file/UmAtr3ULQEInMXfNFwP0g0/10-10d-User-Testing-Prep?type=design&node-id=4%3A64769&mode=design&t=fzOojyFGMdhTn3KU-1
