### ISSUE TITLE
[FwdProxy to AL2] Initial Github Actions

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#76236]
## Description
In order to begin the effort of moving FwdProxy to AL2 we need add in some core GHA automation

## Resources 
- https://github.com/department-of-veterans-affairs/vsp-platform-revproxy/actions

## Acceptance Criteria
- [x] Initial Github Actions
  - [x] Sem ver
  - [x] PR title lint
  - [x] Issue Checker

## Refinement Guidance - Check the following before working on this issue: 
- [x] _Team label assigned ("platform-tech-team-2")_
- [x] _Epic assigned (if needed)_ 
- [x] _Estimated (points assigned)_
- [x] _Sprint assigned (once planned)_
- [x] _Team member(s) assigned_
- [x] _Understands how this work aligns with the overall platform_

**Comment by npeterson54** [comment]
Removing from sprint due to other priorities discovered during work
