### ISSUE TITLE
[FwdProxy to AL2] Initial Terraform

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#76237]
## Description
In order to begin the effort of moving FwdProxy to AL2 we need add in some Terraform

## Resources 
- https://github.com/department-of-veterans-affairs/vsp-platform-revproxy/actions

## Acceptance Criteria
- [x] Initial Terraform
  - [x] Sem ver
  - [x] PR title lint
  - [x] Issue Checker

## Refinement Guidance - Check the following before working on this issue: 
- [x] _Team label assigned ("platform-tech-team-2")_
- [x] _Epic assigned (if needed)_ 
- [ ] _Estimated (points assigned)_
- [ ] _Sprint assigned (once planned)_
- [ ] _Team member(s) assigned_
- [ ] _Understands how this work aligns with the overall platform_

**Comment by npeterson54** [comment]
Rolling into next sprint due to some illness
