### ISSUE TITLE
[Research] Dot Indicator Research: Prepare research materials

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#76283]
## Background
We need to prepare the materials that will be used to collect feedback during the dot indicator research study - specifically prepare the mural board for the study.

## Tasks
- [x] Prepare mural board (or other feedback gathering mechanism)

## Acceptance Criteria
- [x] Materials for capturing feedback are ready ([Mural board to capture research study](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1709061562188/1dfb9cdf6dbb59004be7cfff6714b3c704d7fa37?showAddTemplatePopup=true))

## Validation
- **_Who can validate this ticket? (FE, BE, Design, PM)?_** Any team member
- **_How can this work be validated?_** ensure materials are prepared

**Comment by mattmarino-adhoc** [comment]
Mural access restored as of today

**Comment by mattmarino-adhoc** [comment]
[Mural board to capture research studies](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1709061562188/1dfb9cdf6dbb59004be7cfff6714b3c704d7fa37?showAddTemplatePopup=true)

**Comment by mattmarino-adhoc** [comment]
@ajakabcin all set for review

**Comment by mattmarino-adhoc** [comment]
Validated by @pamela-drouin
