### ISSUE TITLE
[CST] Text style updates to headers descriptions for Status, Files, Overview tabs

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#76295]
## Background Context

Found out we should be using `va-introtext` text style for header descriptions in Status, Files, and Overview tabs.

<img width="1044" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWRjQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e8a73e6b00d662b5d25de3f6cb88db27974abca5/Screenshot%202024-02-14%20at%204.43.49%E2%80%AFPM.png" alt="Screenshot 2024-02-14 at 4.43.49 PM.png" />

## Design
[Figma link](https://www.figma.com/file/F8U4wddaFouUPVd4mGBMDI/CST---Evidence-Submission---Spec?type=design&node-id=80-1335&mode=design&t=WB3NNZo91lZV8WFX-0)

## Engineering 
- In className use `va-introtext`

## Definition of Done
- [ ] Meets acceptance criteria
- [ ] Design QA

## Acceptance Criteria
- [ ] Tab headers descriptions in Status, Files, Overview tabs show the correct text style (va-introtext)

**Comment by skylerschain** [comment]
@jacobworrell Caught this during Design QA and we need to update.

VADS page: https://design.va.gov/foundation/typography#paragraphs

**Comment by pmclaren19** [comment]
@jacobworrell this is ready for validation in Staging!

**Comment by jacobworrell** [comment]
Looks good! Closing.
