### ISSUE TITLE
process trexler file

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#76292]
## Background
process trexler file

## Tasks
- [ ] _Outline steps to complete_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this?_

---
#### How to configure this issue
1. Label with practice area (`backend`, `frontend`,`ux`, `design`, `research`)
2. Label for MVP work? (`mvp`)
3. Add an estimate 
4. Attach an Epic (what body of work is this a part of?)

**Comment by holdenhinkle** [comment]
PR - https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/1504

**Comment by oddball-lindsay** [comment]
The job is running and processing, but the pace is not realistic.  Manually updating also is not the most efficient approach.  

Will explore rate limiting through Sidekiq Enterprise.
