### ISSUE TITLE
Evaluate "www.va.gov/healthbenefits" redirects

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#763]
Currently, we have some client-side redirects for pages under `/healthbenefits`, currently listed in this [config](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/data/vagovRedirects.json).  FOr example, https://www.va.gov/healthbenefits/index.asp.

It seems like we want to redirect that whole path to `/health-care`, or a specific page under `/health-care`. However, certain pages under `/healthbenefits` are still accessible, such as this one, https://www.va.gov/healthbenefits/access/, which I found via a [Google search](https://www.google.com/search?q=va+healthbenefits&rlz=1C5CHFA_enUS762US762&oq=va+healthbenefits&aqs=chrome..69i57j0l4j69i60.1948j0j7&sourceid=chrome&ie=UTF-8).

If we can determine that all of `/healthbenefits` should be redirected, we can move these redirects onto the server, and use the status code indicating a permanent redirect. We might see some SEO benefits this way, and improve the Google search results.

**Comment by ncksllvn** [comment]
Hey @chrisj-usds @jenniferlee-dsva, I'm curious if you all have any insight into this. I stumbled upon this while looking into some redirects handled by the front-end.

CC: @Karak888

**Comment by chrisj-usds** [comment]
hey @ncksllvn Nice find! 
I'll defer to @jenniferlee-dsva @mnorthuis and @peggygannon on this. But I believe this is correct. The reason we did not redirect everything under /healthbenefits is because there is still a bunch of content on the legacy pages that VHA wants / needs, but we've not yet created new homes for. (for example Seamless Care or Point of Service Kiosks).

**Comment by ncksllvn** [comment]
Thank you @chrisj-usds! That makes sense. Yeah, it looks like the [healthbenefits](https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p184624291/_u.date00=20181001&_u.date01=20190326&explorer-table.filter=~2Fhealthbenefits&explorer-table.plotKeys=%5B%5D/) section still gets a pretty good amount of traffic at over 25,000 in the past month, although some are just PDFs.

**Comment by mnorthuis** [comment]
Content under /healthbenefits is not ready for full redirect yet!  As we finish the parity/rewriting work, the redirects for pages under this directory will be handled, but there will continue to be some lingering pages that we are not planning to redirect, so we cannot do a bulk redirect of this sub-folder.

**Comment by Karak888** [comment]
Thanks @mnorthuis I will do my best to keep this on my list of things to track! Much appreciated :)

**Comment by jenniferlee-dsva** [comment]
FYI - @mnorthuis and I have a regroup meeting on 8/13 with JHL regarding Mikki's recommended IA updates to their legacy pages (which includes retiring many pages). One of the recs was to retire their legacy /healthbenefits 'site.'

**Comment by Karak888** [comment]
@ncksllvn is this ticket in progress or go to backlog? Thanks!

**Comment by ncksllvn** [comment]
@Karak888 can probably be closed in favor of the now-epic, https://github.com/department-of-veterans-affairs/va.gov-team/issues/1506

**Comment by Karak888** [comment]
Closing this ticket per https://github.com/department-of-veterans-affairs/va.gov-team/issues/1506
