### ISSUE TITLE
Update hint text to include "." for ".gif" and ".txt" and include ".jpg" in list

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#76300]
## Background Context
The current hint text for the file uploader doesn't have the "." for all the file formats, and doesn't have the ".jpg" file type listed. We want to fix that.

## Design

Current

**Before**
<img width="1638" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODFjQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e21e58c62fefb9e670043d93df6a042b0e8dfff3/Screenshot%202024-02-14%20at%205.06.31%E2%80%AFPM.png" alt="Screenshot 2024-02-14 at 5.06.31 PM.png" />

**After**
<img width="1798" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODljQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--426cb4db88217470474436b45daac75f06ee05b2/Screenshot%202024-02-14%20at%205.06.49%E2%80%AFPM.png" alt="Screenshot 2024-02-14 at 5.06.49 PM.png" />

## Acceptance Criteria
- [x] Update to add "." to file types ".gif" and ".txt"
- [x] Update to include ".jpg" in list of file types in hint text of file uploader
- [ ] Design QA

**Comment by HeatherWidmont** [comment]
@jacobworrell to validate

**Comment by jacobworrell** [comment]
@skylerschain this looks good, ready for your design QA. when finished, feel free to close with comment.

**Comment by HeatherWidmont** [comment]
@pmclaren19 what's the estimate for this work?

**Comment by pmclaren19** [comment]
added the estimate! we said a 1 in slack when these were first made we just forgot to add it to the ticket.
