### ISSUE TITLE
Front End new 1010D json update 

### ISSUE THREAD

**Issue by cloudmagic80** [department-of-veterans-affairs/va.gov-team#76325]
As a user of the 1010D form, I would like to use the newest versions of VA forms that are published in the VA.gov. In order for the forms to be publish, front end and back end data transmission should match.

**Comment by michaelclement** [comment]
Recommend closing this issue as I believe requirements have been satisfied in these PRs:
- [PR to add latest 10-10d PDF to vets-api](https://github.com/department-of-veterans-affairs/vets-api/pull/15546)
- [PR to add latest file upload fields to data sent from frontend to backend](https://github.com/department-of-veterans-affairs/vets-website/pull/28113)

I'm not aware of anything else that would need to happen on this issue (@baltes for your awareness)

**Comment by baltes** [comment]
Closing, see comment above.
