### ISSUE TITLE
[jenkins] Use "safe html" instead of "plain text" Markdown Formatter

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-team#7633]
One of my Jenkins changes was to add HTML to the job descriptions e.g. http://jenkins.vfs.va.gov/job/cms/job/cms-db-sanitize/ - Can we enable the safe_html in http://jenkins.vfs.va.gov/configureSecurity/. I just tested it to confirm it works, it does, and then I changed it back for now.

![image](https://user-images.githubusercontent.com/1504756/78409345-5051de00-75be-11ea-82db-60098162c7ba.png)

https://dsva.slack.com/archives/CBU0KDSB1/p1585951753492100

**Comment by wyattwalter** [comment]
You did this already, right @tskinn ?

**Comment by ElijahLynn** [comment]
Yes, @tskinn did. It is working now!

**Comment by ElijahLynn** [comment]
> Yes, @tskinn did. It is working now!

Oh wait, I think it got reverted as it isn't working now, maybe it was just done in the UI, not in code and deployed.

**Comment by ElijahLynn** [comment]
> > Yes, @tskinn did. It is working now!
> 
> Oh wait, I think it got reverted as it isn't working now, maybe it was just done in the UI, not in code and deployed.

This job will have HTML links in the job description when it is enabled. http://jenkins.vfs.va.gov/job/cms/job/cms-efs-backup-prod/

**Comment by tskinn** [comment]
Sorry @ElijahLynn I enabled it manually in Jenkins but couldn't find how to enable via code or config so that it persists across deployments. I just did a deployment which is why it got changed back. I enabled it again manually so it should work again for now.

**Comment by jhouse-solvd** [comment]
@tskinn - is this still relevant? do you know if any additional work was done. 

@ElijahLynn - is this functionality still desired?

**Comment by ElijahLynn** [comment]
Jenkins is deprecated, closing.
