### ISSUE TITLE
SOCKS access for Amanda Nantais-Austin

### ISSUE THREAD

**Issue by anantais** [department-of-veterans-affairs/va.gov-team#76332]
### Your Name

Amanda Nantais-Austin

### Your Email

anantaisaustin@metrostar.com

### Your GitHub Handle

anantais

### Your Role and Team

Drupal Developer

### Product Manager (PM) name and email

Grace Kretschmer mkretschmer@metrostar.com

### Product Owner (PO) name and email

Erika Washburn Erika.Washburn@va.gov

### Access Type Requesting

drupal_developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCup5hftoPR2aIUqdmyYPxpgyPC+S3D+H95A4OaKsIr1sFlZxxizs05eIIsSO8tC1xdytoWaTpnQ3Fepoj7ZCyX9fLgeD4oRkmEkOMI4TP+bPRtN80kstYphPin5+lHeYdnDjJ8kKi5C3qn8FAnpWIMUeKIrMZYyWAXGIk28hdMo7dkVfhNJnc0htW+1zo8F5CuSaO1RhR4TKjLhnPvWC7j318zNCGNljYcVU7jVR+cJAjls8Ot/C0H8sQyka3zUVJmMkkcMLRMgisBtUlvSVB1RHz0hjklc371W41o9POow+zsQoUYz+l5hkD0XdQuDkcLCWdtJJDSo/rX/s0h03xMGT5uX2uiq/d62DtEEEfgN47HCC/Xa1RWXjaLEi3Ihu8enzbCJx9VEGFAR3bHHyZTfNnjxEhbUta1LHspFuO4KdHulXTeJf8XPFQHeRFE6V/fwDrCFCA6oh/rQJcUES4b7DrQHp5TYHsDsRjHfdE9nOS4RA/rZQ3PkwQeMUGg6sk= anantaisaustin@ITLP01100.local

### E-QIP Transmittal Confirmation

<img width="1166" alt="Screenshot 2024-02-15 at 9 46 15 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/2297139/67edf82c-87de-4712-ba17-3cdea250c845">

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by anantais** [comment]
Is there anything this ticket needs to help it move along?

**Comment by stoiven** [comment]
SSH key is merged.
