### ISSUE TITLE
[QA] AMA/Decision Reviews Part 2 - Test Plan

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#7636]
## Product/Feature summary

\[See links below]

Product/Feature Outline: [GitHub doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/AMA%20Follow%20Up/AMA%20Follow%20Up%20Product%20Outline.md)
Product/Feature Epic: \[see #6421 -- tickets for test plan listed [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6421#issuecomment-604175380)]
NOTE: #5753 [will not have a dedicated test-case](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7636#issuecomment-609900882), and will be indirectly validate via the [GitHub-Drupal migration case](https://dsvavsp.testrail.io/index.php?/cases/view/457).
Product/Feature Pre-Launch Checklist: #7242

## Product-team SMEs

PM (Acting): Mickin Sahni (@MickinSahni) 
Design/Research: N/A
Content/IA: Laura Walsh (@lwalsh617), Randi Hecht (@RLHecht)
Front-end: Nick Sullivan (@ncksllvn)
Back-end: N/A

## Proposed user-scenarios

No separate user-scenarios -- all content changes are unauthenticated-experience.

For widget update \[the only functional change], no specific test-account needed:
1. Decision date 2/18/2019.
2. Decision data 2/19/2019.

## How to configure this issue

- [x] Attached to a **Milestone** (when will this be completed?)
- [x] Attached to **Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] Labeled with **Team** (`vsa-authenticated-exp`, `vsa-benefits`, `vsa-benefits-2`, `vsa-caregiver`, `vsa-ebenefits`, `vsa-facilities`, `vsa-public-websites`, etc.)

## Definition of Done

- [ ] Test Plan reviewed by Product Team.
- [ ] Test Plan finalized per review feedback.
- [ ] Actual Test Run(s) completed on Staging, and defects logged.

**Comment by tlei123** [comment]
Questions:

### Deployment to Staging
1. Are all the changes deployed already to Staging?

### If **Yes** to above \[everything's on Staging]:

1. **Megemenu link change**: The **File an appeal** link was not found in Disability option fly-out on [Staging](https://staging.va.gov/).  Is this change deployed elsewhere?
1. **Wizard 2nd question**: The 2nd question from the Word doc, **Is this your first time filing a disability claim with VA?**, is missing on Staging.  Is this change deployed elsewhere?

**Comment by MickinSahni** [comment]
**Answers to some of the questions with a couple follow-ups:**

> Questions:
> 
> ### Deployment to Staging
> 1. Are all the changes deployed already to Staging?

**Here's a [list of Drupal preview links](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7339#issue-589911994) that Laura shared with Jennifer for her spot-check.**

> ### If **Yes** to above [everything's on Staging]:
> 1. **Megemenu link change**: The **File an appeal** link was not found in Disability option fly-out on [Staging](https://staging.va.gov/).  Is this change deployed elsewhere?
 
 - **This is prod and I'm not seeing a **File an appeal** link. Do you what this link previously looked like?** 
    - <img src="https://user-images.githubusercontent.com/13204473/78510714-664dd300-7765-11ea-9518-6330e2e1cac5.png" width="200px">

> 2. **Wizard 2nd question**: The 2nd question from the Word doc, **Is this your first time filing a disability claim with VA?**, is missing on Staging.  Is this change deployed elsewhere?

  - **Can you point me to the doc and/or what should be there and we might be missing?**

Thanks for everything, Tze

**Comment by tlei123** [comment]
@lwalsh617 , I got a couple of quick questions... \[Please tag whoever would know if you don't]

In the **megamenu** > **Disability** fly-out > **Manage your benefits** column, is the **File an appeal** link new?

If No to above, do you know what the previous version of this link looks like?

\[See the previous 2 Comments (my questions to Mickin, and his answers.]

The snippet (page 2) from the change doc up in the main Description \[[AMA.related.changes_FE_v3.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4165610/AMA.related.changes_FE_v3.docx)], calls this link out \[see red box] for changing, but the whole link is just missing on Staging:
![Screen Shot 2020-04-05 at 7 35 44 PM](https://user-images.githubusercontent.com/587583/78518252-d2840300-7774-11ea-943c-94af0b63cf63.png)

@MickinSahni was asking what the previous link looked like, but I have no idea.

Please let me know.  Thanks much!

**Comment by tlei123** [comment]
@MickinSahni , re. your follow-up to my question 2 (about the **Can I file a claim online** widget) ...

The snippet (page 3) from the change doc [[AMA.related.changes_FE_v3.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4165610/AMA.related.changes_FE_v3.docx)]:
![Screen Shot 2020-04-05 at 8 03 19 PM](https://user-images.githubusercontent.com/587583/78519593-c306b900-7778-11ea-80b7-0773ab387d09.png)

[Staging](https://staging.va.gov/disability/how-to-file-claim/) widget screenshot:
<img width="564" alt="Screen Shot 2020-04-05 at 8 07 39 PM" src="https://user-images.githubusercontent.com/587583/78519857-6952be80-7779-11ea-954c-caa5d3bd09e1.png">

**Comment by MickinSahni** [comment]
> @MickinSahni , re. your follow-up to my question 2 (about the **Can I file a claim online** widget) ...
> 
> The snippet (page 3) from the change doc [[AMA.related.changes_FE_v3.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4165610/AMA.related.changes_FE_v3.docx)]:
> <img src="https://user-images.githubusercontent.com/587583/78519593-c306b900-7778-11ea-80b7-0773ab387d09.png" width="150px">
> 
> [Staging](https://staging.va.gov/disability/how-to-file-claim/) widget screenshot:
> <img alt="Screen Shot 2020-04-05 at 8 07 39 PM" width="150" src="https://user-images.githubusercontent.com/587583/78519857-6952be80-7779-11ea-954c-caa5d3bd09e1.png">

Gotcha. Thanks, Tze. @lwalsh617 @ncksllvn @RLHecht - could you confirm what this should look like?

**Comment by tlei123** [comment]
[Test Cases](https://dsvavsp.testrail.io/index.php?/suites/view/9&group_by=cases:section_id&group_order=asc) for 4 of the [6 issues](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6421#issuecomment-604175380) listed in #6421 are now fleshed-out on TestRail.

\[@MickinSahni , in case you wanna preview them, use your **VSA-PubWeb** TestRail shared-account creds that Peter Hill has set up for you.]

I'll double-check them against the tics tmrw (Mon) morning and add further questions.

Shooting for finalizing Plan/Run by end of Monday / early Tuesday.

**Comment by MickinSahni** [comment]
@tzelei, I'm adding for reference: 5753 can be checked by simple migration since the anomalies aren't possible in Drupal.

**Comment by tlei123** [comment]
@lwalsh617 @RLHecht  @ncksllvn  , one more question about changing Decision Reviews page to a hub page #6799 ...  [Please tag whoever else might know better]

Is this new hub-page version deployed somewhere other than Staging / Drupal prod-preview?

Neither [Staging](https://staging.va.gov/decision-reviews/) nor [Drupal's prod-preview](http://preview-prod.vfs.va.gov/decision-reviews/) has the hub-page changes as spec'ed out in the tic's [latest copy-doc](https://github.com/department-of-veterans-affairs/va.gov-team/files/4381922/decision-reviews-hub-page_copy-v1.5.docx).

With 5753 now off my test-plan, this is the one I have left [assuming it's still on the QA plate].

Please let me know.  Thanks much!

**Comment by lwalsh617** [comment]
@tlei123 -  FYI, three of our page titles changed. I wanted to flag these for you for C457 so it doesn't create confusion:
*File a Supplemental Claim with new evidence** changed to **Supplemental Claims** 
**Request a Higher-Level Review** changed to **Higher-Level Reviews**
**Request a Board Appeal** changed to **Board Appeals**
Everything is a LGTM!
Thanks so much for your work on this. 
L

**Comment by andaleliz** [comment]
FYI - I think I'm listed as design/research on this by mistake @tlei123.  I haven't done any design or research for this.

**Comment by tlei123** [comment]
@ncksllvn / @kelsonic , re. the "missing" items I asked about [click comment-links below for details]...

Would you happen to have Drupal preview-prod node-URLs for the [megamenu](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7636#issuecomment-609540170) and the /disability/how-to-file-claim page (which contains our [widget update](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7636#issuecomment-609550684))?

These items are missing from va.gov and staing.va.gov, but I'm surmissing maybe they're only on Drupal preview-prod right now and that's where I should look for them.

Pls. let me know.  Thx much!

**Comment by RLHecht** [comment]
@tlei123 I think the page with the widget is this: preview-prod.vfs.va.gov/preview?nodeId=3102 @lwalsh617 this is the page moving from disability to decision reviews. 

The megamenu can't be previewed in Drupal.

**Comment by tlei123** [comment]
@MickinSahni , I have just 1 untested Step* in 1 Test Case I wanna retest tmrw (Wed), then I'll finalize results and generate the reports for our Staging Review...

Feel free to preview what I've got in the meantime: https://dsvavsp.testrail.io/index.php?/plans/view/262
\[scroll down and click each Test Run; once there, scroll down the right panel to see the Step Results]

I'll update this ticket again tmrw morning once I've tried retesting that remaining test-case step.

\*1 of the Drupal preview nodes wasn't coming up.  I want to retest that step to make sure it wasn't an intermittent network hiccup.

**Comment by tlei123** [comment]
@MickinSahni , all Test Runs are now done*.

Coverage for References report coming shortly -- I'll update this Comment once ready.  Just need to add refs to the cases.

Summary (Defects) report: [TestRailt](https://dsvavsp.testrail.io/index.php?/reports/view/51) ; [PDF](https://github.com/department-of-veterans-affairs/va.gov-team/files/4451615/amadr2-qa-test-summary-200408.pdf)

*For some reason that 1 Drupal preview-node didn't load via https, but loaded fine when I changed to http:.  If you need follow-up, the preview-node is http://preview-prod.vfs.va.gov/preview?nodeId=3003

**Comment by stephorkandatx** [comment]
@tlei123 please close out when ready. Thanks!

**Comment by tlei123** [comment]
Oops, sorry!  Closing now.
