### ISSUE TITLE
Analytics New KPI dashboard request & KPI dashboard update request for Veteran Facing Forms - 40-0247

### ISSUE THREAD

**Issue by tbaker1026** [department-of-veterans-affairs/va.gov-team#76372]
# Request a New Standardized KPI Dashboard or an Update to an Existing Dashboard
## What this form is for

Use this ticket template to request a new standardized KPI dashboard or an update to an existing KPI dashboard on Domo for your product. 

**Tell us what you need done:**
- [x] [New Dashboards](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/analytics-request-kpi-dashboard.md#for-new-dashboards)
- [ ] [Updates to Existing Dashboards](https://va-gov.domo.com/page/447193050?userId=1648457072)

Standardized dashboards are currently available for [Forms](https://va-gov.domo.com/page/447193050?userId=853813555), [Content](https://va-gov.domo.com/page/426422632), & [Search](https://va-gov.domo.com/page/1964748112) products only. To see if you should request a standardized dashboard, check [Should I request a standardized KPI dashboard](https://docs.google.com/presentation/d/16mRcslbkWtW44rlsfQGXZnHtQ3GoLjn6GpFnd3Gvva8/edit#slide=id.p). If you’re not sure which dashboard(s) your product(s) qualify for, check the [Eligibility Dashboard](https://va-gov.domo.com/page/1550814739).

If your VA.gov product is not eligible for a standardized dashboard, you may be able to request an “edge case” dashboard. Please reach out to the Platform Analytics & Insights team on #vfs-platform-support for more information on this process.

### Expected delivery timelines

The Analytics team will notify you once this ticket has been pulled into a sprint. 

## For New Dashboards

In order to pull the correct data for your product, we need your help to define what pages and events to include, in addition to basic product info. We’ll need a filled out [KPI request template](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit#gid=981224988) before we can pull this ticket into our sprint.

- [ ] Make a copy of the [Google Sheet](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit#gid=981224988)
- [ ] Complete worksheet as instructed
- [x] Link your completed spreadsheet here:https://docs.google.com/spreadsheets/d/1Z8dyH-3pef60O28JkIOLEv4V8hC1I5iSMPvQxvCqFxg/edit#gid=0 ______
- [x] Check your sharing settings to make sure the Analytics team will be able to access it
- [x] **Add your team label to follow progress**

## For Updates to Existing Dashboards 

First, tell us what type of change you need to make:

- [ ] Change basic product info
- [ ] **Forms**: funnel changes
- [ ] **Content**: Add or remove pages included
- [ ] Other_____________________________

Next, use the original [KPI request template](https://docs.google.com/spreadsheets/d/1Z8dyH-3pef60O28JkIOLEv4V8hC1I5iSMPvQxvCqFxg/edit#gid=0) you filled out to update your information. If you are not able to find that spreadsheet, reach out to the Analytics team on #vfs-platform-support for a new spreadsheet that reflects what we currently have on file.

**If you cannot locate your original worksheet you can create a new one:**
- [ ] Make a copy of the [Google Sheet](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit#gid=981224988)
- [ ] Complete worksheet as instructed
- [ ] Link your completed spreadsheet here: https://docs.google.com/spreadsheets/d/1Z8dyH-3pef60O28JkIOLEv4V8hC1I5iSMPvQxvCqFxg/edit#gid=0______
- [ ] Check your sharing settings to make sure the Analytics team will be able to access it
- [ ] **Add your team label to follow progress**

**Additional Info For Both Options**

- Please use the [KPI Framework](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/Analytics%20Playbook/va-gov-platform-analytics-kpi-framework.pdf) for more information on the metrics used in the Standard KPI dashboards. 
- If you need any analytics support, read through the [How to request Analytics support](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guidelines.1586823275.html#Analyticscustomersupportguidelines-4.RequestaKPIDashboardinDomo).
- If you do not have Domo access, please [request access here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+access-request&template=analytics-request-google-analytics-domo-access.md&title=Request+access+to+Google+Analytics+and%2For+Domo).

---

### Acceptance Criteria

- [x] Form funnel has been loaded, as outlined in [these steps](https://vfs.atlassian.net/wiki/spaces/AT/pages/1510408350/How+to+-+Loading+a+new+funnel+to+the+Forms+KPI+Dashboard)
- [x] Appropriate statements have have been made within BigQuery to include new form in the Standardized KPI dashboard
- [ ] Confirm new form has been added, and is displaying in Domo
- [ ] Reply with a comment to this ticket with a screenshot of the form in Domo

**Comment by johnny-jesensky-adhoc** [comment]
Johnny to connect with Dave on this, and these kinds of standardized requests. As discussed in refinement (2/22).

**Comment by ChristineYoungZA** [comment]
The data has been loaded into BQ and should show in the Domo dashboard April 1, 2024.

**Comment by johnny-jesensky-adhoc** [comment]
@tbaker1026 - Hi Tricia, the form should be available as a filtering option in the Forms KPI dashboard next Monday, (4/1). Please check back in next week, and let us know if there are any questions, or you are not seeing it.

Thanks!

FYI @ChristineYoungZA

**Comment by tbaker1026** [comment]
@johnny-jesensky-adhoc @CatherineHughes202 - can you update the name in DOMO for 40-0247 to read Presidential Memorial Certificate?  Thank you
<img width="698" alt="2024-04-30_08-27-29" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/115116356/90841b1f-e7a9-44a2-a640-867834d85ba3">

**Comment by johnny-jesensky-adhoc** [comment]
Hi @tbaker1026. Of course -- we will look to change.

@ChristineYoungZA -- see above, can you please replace _Github Issue Tickets_ with _Presidential Memorial Certificate_ for the form?

FYI @Blivaditis
