### ISSUE TITLE
[BE] 10-10EZ - TERA: Update ES Class with new fields

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#76381]
## Benefit to the Veteran
By updating the Enrollment System class with new fields, we will be able to capture and send data input from the 10-10EZ to the Enrollment system for data storage and reference.  This will allow the Veteran to submit their 10-10EZ application, which will include TERA data input, for enrollment consideration in VA health care

## Background
Now that the VES team has agreed to accept TERA question data input from the VA.gov 10-10EZ form, we need to update the ES class with the new fields that we will be sending to ES.
Once the updated schema is provided by VES/Joshua Faulkner, we can begin this work. (ETA afternoon of 2/15)

## Tasks

- [ ] Update ES class with new fields
- [ ] Validate as needed with VES/team

## Acceptance Criteria
- ES class will be updated with the new TERA fields

**Comment by lihanli** [comment]
this is blocked by VES sending the schema and #76383

**Comment by lihanli** [comment]
also this is blocked by VES updating their API to include the new fields in the staging environment

**Comment by hdjustice** [comment]
[Latest xsd document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Toxic%20Exposure/Engineering%20docs/eeSummary_02202024.xsd) from Meena on 2/20/2024

**Comment by hdjustice** [comment]
[Sample XML request](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Toxic%20Exposure/Engineering%20docs/voa_tera_sample_request_with_toxic_exposure.xml) sent from Meena on 2/21/2024 morning
