### ISSUE TITLE
Add "We updated our online pension form" copy to Intro page 

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#76397]
## Issue Description
We need to add copy to the [Introduction page](https://staging.va.gov/pension/application/527EZ/introduction) of the form flow about the form's new questions (similar to the [How to Apply](https://staging.va.gov/pension/how-to-apply/) page), 
so that veterans with in progress data at the time of deactivation, who land on this page, will know what to expect.

## Acceptance Criteria

- [x] The How to Apply page copy will be updated to let the veteran know the online Pension form is now available again.
- [ ] The Introduction page copy will be updated to let the veteran know the online Pension form is now available again.

**Comment by vbellissimo** [comment]
Closing this, CAIA made the necessary content updates to the static page.

**Comment by vbellissimo** [comment]
Reopening this ticket. Only the How to Apply page was updated. The Introduction page was not, yet.

**Comment by katherine-fung** [comment]
Hi @vbellissimo! 

We need to add copy to the [form introduction page](https://www.va.gov/pension/application/527EZ/introduction) to say we've updated the form, in case users navigate directly to the page, and bypass the [How to apply page](https://www.va.gov/pension/how-to-apply/). 

My recommendation is to update the info alert for authenticated users that says "Your application is in progress and was last saved on ---"

Here's the new copy to add to the info alert (between the header and "Your application will expire..."): 

> You should know that we updated our online form. **If you started applying online before November 8, 2023,** we have some new questions for you to answer. And we changed some questions, so you may need to provide certain information again.
> 
> Select **Continue your application** to use our updated form. Or come back later to finish your application.

Here's a visual reference: 

<img width="1501" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUdiQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fc2c9a953557279dcbd91db5f0e3a5b05e7be2bd/Screenshot%202024-02-28%20at%204.20.48%E2%80%AFPM.png" alt="Screenshot 2024-02-28 at 4.20.48 PM.png" />

If there are any issues, please let me know and I can adjust the recommendation. Thanks!

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/76397?planning-poker) with Zenhub @mjknight50 @TaiWilkin @ToddWebDev @wayne-weibel @danlim715

**Comment by wayne-weibel** [comment]
Just a quick note/reminder - you will need to login on staging and have a pension application in progress

<img width="922" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDd5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5188321ea3d517709c63b57d5b13af9d453e6f8b/image.png" alt="image.png" />

**Comment by aplatt-coforma** [comment]
Looks good I signed in as Karl Howard with an inprogress form
<img width="512" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1gzQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--76e20883c1b3f7cf8f0ef8059b1bebd715a2ac06/screencapture-staging-va-gov-pension-application-527EZ-introduction-2024-03-20-08_50_06.png" alt="screencapture-staging-va-gov-pension-application-527EZ-introduction-2024-03-20-08_50_06.png" />
