### ISSUE TITLE
Shadowing Prioritization Pick Up

### ISSUE THREAD

**Issue by nnicholas7** [department-of-veterans-affairs/va.gov-team#76399]

**Comment by lisacapaccioli** [comment]
@nnicholas7 Is this ticket still needed? If not can we close it, if yes could you add some more details to understand the need for it? Thanks

**Comment by nnicholas7** [comment]
This is done. I created this ticket when we were conducting Shadowing Research as a placeholder to finish Shadowing Prioritization and any associated task.
