### ISSUE TITLE
[SCREENREADER]: Education STEM Update - VoiceOver has a keyboard trap when I expand the STEM scholarship explanation

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#764]
## Issue

I noticed a keyboard trap when I was browsing the form with Safari + VoiceOver on MacOS Mojave (latest). The keyboard trap appeared when I was using the virtual cursor to move through, `Ctrl + Option + right arrow`. Animated GIF attached below.

## Point of Contact

Trevor

## Acceptance Criteria

* As a Safari + VoiceOver user, I want to be able to move to the next element when the STEM scholarship accordion (expand/collapse) is opened.

## Environment
* MacOS Mojave
* Safari latest
* VoiceOver

## WCAG or Vendor Guidance (optional)
* [No Keyboard Trap: Understanding SC 2.1.2](https://www.w3.org/TR/UNDERSTANDING-WCAG20/keyboard-operation-trapping.html)

## Screenshots or Trace Logs

![safari-keyboard-trap.gif](https://images.zenhubusercontent.com/5ac217b74b5806bc2bcd3fc8/98a04fe4-08dc-4236-b0a0-79ecfd78545f)

**Comment by KevinMHoffmanUSDS** [comment]
@desireeturner This is a post 8/1 issue that will need to be corrected.

**Comment by delli-gatti-michael** [comment]
Tested locally and on Staging. This is confirmed fixed

**Comment by ksantiagomorgan6** [comment]
@1Copenut can you validate the fix in staging please? Thank You

**Comment by 1Copenut** [comment]
@ksantiagomorgan6 I tested this again and the Safari + VO keyboard trap has been resolved. I was able to move through to the Back and Continue buttons as expected. Moving to close.
