### ISSUE TITLE
Query 400K EDIPIs

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#76413]
A request has come from a contact known to Samara. The request is to take a list of 400K EDIPI's and determine if the users created a verified account on VA.gov. The goal of the query is to determine if the person created a verified account before or after their retirement/separation date. We have the list in excel format saved to a sharepoint within the VA network (ask Joe Niquette for a link). We also have the data needed to answer these questions within the vets-api DB. 

The person who wants this information is looking for an output that contains the users edipi and the date the verified account was created on VA.gov. Nothing more.

**Comment by parkerbees** [comment]
Moved to Jira. Closing.
