### ISSUE TITLE
Split out attachments into multiple single pdfs for upload as optional for certain forms

### ISSUE THREAD

**Issue by cloudmagic80** [department-of-veterans-affairs/va.gov-team#76452]

**Comment by cloudmagic80** [comment]
PR still in draft mode. 
https://github.com/department-of-veterans-affairs/vets-api/compare/pdf_split_pega2?expand=1
In end to end testing. 
Not completed yet

**Comment by cloudmagic80** [comment]
Ready for review.

**Comment by baltes** [comment]
@cloudmagic80 How would a non engineer go about reviewing this?

**Comment by baltes** [comment]
@cloudmagic80 I'll tag you on a new ticket to cover the unit tests here and close this one out.
