### ISSUE TITLE
Add CODEOWNER config to devops for FE configs 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#7646]
## Tasks 

- Add FE as codeowner of files exclusively owned by the FE group (react routes, CSP)
- document how to deploy updates to revproxy

**Comment by rianfowler** [comment]
document how to deploy reverse proxy

**Comment by timwright12** [comment]
https://github.com/department-of-veterans-affairs/devops/pull/9245

**FE Tools Codeowners**

/ansible/release/config/vets-website.yml                    
/ansible/Jenkinsfiles/releases/vets-website                 
/ansible/deployment/config/vets-website-vagovdev.yml        
/ansible/deployment/config/vets-website-vagovstaging.yml    
/ansible/deployment/config/vets-website-vagovprod.yml       
/ansible/deployment/roles/deploy-vets-website/              

/ansible/release/config/content-build.yml                     
/ansible/Jenkinsfiles/releases/content-build                  
/ansible/deployment/config/content-build-vagovdev.yml         
/ansible/deployment/config/content-build-vagovprod.yml        
/ansible/deployment/config/content-build-vagovstaging.yml     
/ansible/deployment/roles/deploy-content-build/               

/ansible/release/config/application-build.yml            
/ansible/Jenkinsfiles/releases/application-build             
/ansible/deployment/config/application-build-vagovdev.yml     
/ansible/deployment/config/application-build-vagovprod.yml    
/ansible/deployment/config/application-build-vagovstaging.yml 
/ansible/deployment/roles/deploy-application-build/

**Comment by timwright12** [comment]
Current documentation on deploying the revproxy https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/roles/revproxy-configure/README.md

**Comment by timwright12** [comment]
Secondary documentation created during the content-build separation initiative https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/infrastructure/reverse_proxy.md

**Comment by timwright12** [comment]
PR to add rev proxy docs https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/627

**Comment by timwright12** [comment]
Reached out to Ops about revproxy deployment documentation.

**Comment by timwright12** [comment]
Revproxy docs have been reviewed by Ops and merged: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/628
