### ISSUE TITLE
QA - Past Appointments

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#7648]
We need to QA the recent Past Appointment feature in new VAOS-R. 

AC:
- Verify that data in Past Appointment tab is correct for users
- For Past Appointments, the following statuses and UI combination should show:
![Screen Shot 2020-04-15 at 9.22.46 AM.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/be7fb453-2c5c-4bd4-a5b2-816f0f832815)
- User can pull past appointment data in 3 month increments
- User can pull data for the past year
- User can pull data for the previous year
- Test cases are added to TestRail

**Comment by lenaecb** [comment]
@marcynadeau - do you have an idea how we can test to verify that the data we're pulling is the correct data for a user? We thought about comparing our data to MHV staging, but we're wondering if you had another idea.

@1Copenut - based on our slack conversation I wanted to make sure you were a part of the final QA for this feature. Here is the epic for this feature - #5732

**Comment by 1Copenut** [comment]
Thank you @lenaecb, I appreciate the heads up! I'll put some time on my calendar this week to QA the past appointments feature.

**Comment by lenaecb** [comment]
508 review for Past Appointments has started and is being tracked by @thilton-oddball in #7649

**Comment by lenaecb** [comment]
@narin - I had Stephen Barrs do testing on this for us in production. He found something interesting in where a 'Confirmed' appointment slipped into 'Past Appointments' for the status 'NON-COUNT/CHECKED IN.' 

I asked him to grab some screenshots for us so I can create a bug ticket. Just wanted to give you a heads up. I am wondering if it's because we don't account for statuses like 'NON-COUNT/CHECKED IN' combos.

**Comment by narin** [comment]
@lenaecb Aside from the statuses we documented [here](https://docs.google.com/spreadsheets/d/1BJ8FJTNDfiWjqhs-xIQ-nQaw6RXMxXdU2CV0EvCfJhI/edit#gid=0) with the `&` I wasn't aware that combo statuses with the `/` were possible. I'm wondering if he can check the database to see how many occurrences there are of these combo statuses.  

Another question I have is if those combos are actually standalone statuses that have their own statusId, or if this indicates that it's possible that multiple statusIds can be applied to a single appointment.

**Comment by lenaecb** [comment]
I wasn't aware that you could have a combo, so this was new to me and I assume Lauren too. 

Here's the screen grab from Stephen showing the status field both in the UI and the ![image (1).png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/ea8a4366-4f4a-4a19-8b04-3875cb55623a)

I will create a bug/issue ticket for this and perhaps some of the triage needs to be confirming combinations.

**Comment by lenaecb** [comment]
Interesting, in sorting through some old emails that were forwarded to me it looks like the MHV team also came across this same issue. Here is our list compared to theirs:

![Screen Shot 2020-04-28 at 3.26.36 PM.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/3078e16f-e9b1-43f3-b77e-5ca81d9a96e0)

Added this list also to our spreadsheet - https://docs.google.com/spreadsheets/d/1BJ8FJTNDfiWjqhs-xIQ-nQaw6RXMxXdU2CV0EvCfJhI/edit#gid=0

I still think it's worth checking what's possible in VAMF. Marcy and/or Steve Brush should be able to assist there.

**Comment by lenaecb** [comment]
Created bug ticket for this - #8553
