### ISSUE TITLE
Review the VAOS past appointments tab feature for 508 compliance

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#7649]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/7648

**Comment by lenaecb** [comment]
@1Copenut - Hi Trevor, is this something you think you'll be able to look at this week? Or do you need something additional from us?

Thanks!

**Comment by 1Copenut** [comment]
Hi @lenaecb It's on my schedule to look at this week. Thanks for the reminder!

**Comment by lenaecb** [comment]
@1Copenut - can we close this ticket out?  Looks like we're addressed all but 1 remaining ticket for Past Appointments

**Comment by 1Copenut** [comment]
@lenaecb Yes, please close this at your convenience. This feature has been tested and I let the VA 508 office know it's in Staging.

**Comment by lenaecb** [comment]
Awesome, thank you @1Copenut !
