### ISSUE TITLE
[4/16] Add mega menu link

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#7650]
## Background
We seem to be missing a link in the mega menu to "File an appeal" under Disability. Tze pointed this out to us via [his Test Plan work](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7636#issuecomment-609540170). 

## Acceptance Criteria
- [x] Confirm the expected behavior and document here
- [x] Make any necessary Drupal, etc. fixes

**Comment by RLHecht** [comment]
@MickinSahni @tzelei For our first round of AMA changes, we were supposed to remove "file an appeal" from the flyout menu, which is why it's no longer showing. It's the first checklist item in ticket 6165. 

As part of this new launch we need to add a link to the new decision reviews hub page in the flyout menu under disability per this from Mikki: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/websites-decision-reviews.md

We aren't suppose to link to that one page anymore though.

**Comment by MickinSahni** [comment]
> @MickinSahni @tzelei For our first round of AMA changes, we were supposed to remove "file an appeal" from the flyout menu, which is why it's no longer showing. It's the first checklist item in ticket 6165.
> 
> As part of this new launch we need to add a link to the new decision reviews hub page in the flyout menu under disability per this from Mikki: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/websites-decision-reviews.md
> 
> We aren't suppose to link to that one page anymore though.

Thanks, Randi! So to confirm -- we still have a task to add a link to the new hub page? Are we able to add that now or does that need to wait for the page to go live first? @RLHecht

**Comment by ncksllvn** [comment]
I thought I remember that we can't preview changes to the mega menu, so it would be an item that we'd have to hold off for launch day. Not sure though.

**Comment by RLHecht** [comment]
yeah, this will have to wait until the day we are going live.

**Comment by MickinSahni** [comment]
Ok thanks, team. Easy enough to use this as the implementation ticket post-launch? @RLHecht 

Also, i added a reference to this on the launch ticket and the collab cycle epic:
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/7242
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/7311

**Comment by RLHecht** [comment]
This should be done before launch, just on the day we are publishing it, so we would be able to validate and close the ticket the same time we are validating and closing the launch ticket.

**Comment by RLHecht** [comment]
@lwalsh617 @MickinSahni @stephorkandatx This was added 4/16. Will confirm that it made it into deploy before closing.

**Comment by RLHecht** [comment]
This is live on site. Closing ticket.
