### ISSUE TITLE
Rename unit tests ending in .jsx to js and rename test describe blocks

### ISSUE THREAD

**Issue by vbahinwillit** [department-of-veterans-affairs/va.gov-team#76513]
## Description
Rename unit tests ending in .jsx to js. This will allow the tests to display in the Test Runner utility. The renaming of the test describe blocks will aid in identifying tests.

---

## Acceptance Criteria
All tests must pass.

### Design Assets
N/A

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ldelacosta** [comment]
No issues to report. Closing the ticket.
