### ISSUE TITLE
Midpoint Review - IA Feedback - IVC Forms, 10-10d

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#76515]
## Next Steps for the VFS team

- [ ] **Assign** this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] **Comment** on this ticket:
  - If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members`.
- [ ] **Close the ticket** when all feedback has been addressed.

## Thoughts/questions

- The submitter information at the start of the flow is looking good! Thanks for being open to making that change.
- Thank you for showing all the potential tessellations of possibilities for what users might do with optional/required file uploads. It's a lot!
- This is an extremely complex flow and probably the most steps I've seen yet in the multi-page multi-response pattern. Additionally, the two options to upload files (during flow and after flow) is a new-to-me pattern and your research will help inform future form design. Please plan to share your research at a Monday design meeting!

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

### Must

- [ ] **Open any external links in a new tab** Since this is a form flow, any links that go to external sites or resources outside of the form should open in a new tab, and include "(opens in a new tab)" in the link text. I spotted one link to the USPS on the homelessness resources box; there are also some "Link to resource" links on the file upload pages. There may be others along the way as well.
- [ ] **Clarify questions on [section 3 page 5, relationship to sponsor](https://www.figma.com/file/HVQQBvkS9DJlNVehCwva4m/10-10d-Midpoint-Review?type=design&node-id=9-300612&mode=design&t=V7hOPxbPMSIPUJ8X-4)** Unless I'm reading it wrong, on the Figma file for section 3 page 5, it looks like the questions for "if the sponsor has passed away" are actually the questions for "if the sponsor is living", and vice versa. Small fix!

### Should

- [ ] **On post-submission page, emphasize the next steps for folks who do not upload all needed files.** There's a header on the [confirmation page for users who still need to submit more files](https://www.figma.com/file/HVQQBvkS9DJlNVehCwva4m/10-10d-Midpoint-Review?type=design&node-id=9-299685&mode=design&t=V7hOPxbPMSIPUJ8X-4) that says, "Do you need to send us any more supporting documents?" the answer is always yes in this case, correct? If so, consider updating that heading label to clearly indicate that the next step in their flow should be to send the files ("How to send us your remaining supporting documents"?). You might also look at that overall page content/flow to ensure folks are going to see those instructions. The [Keep a record of submitted information](https://design.va.gov/patterns/help-users-to/keep-a-record-of-submitted-information) example in the design system might be helpful.

### Consider

- [ ] **Moving "Resources available" alerts into additional info components** Echoing feedback from Design and Accessibility, I'd recommend moving these resource messages into additional info components with a more descriptive label than `Resources available` ("If you don't have an address" / "If you don't have a phone number" perhaps).
- [ ] **Saving all file uploads for one big file upload party the end** 
  - The two options to upload files (during flow and after flow) will be a lifesaver for some folks, but/and could also be confusing. 
  - If y'all have time to design and test a new pattern to accommodate all the file uploads needed at once and only at the end of the form flow, it could be an interesting path to test (unless work has been done on this already - I happily defer to any existing research). 
  - This flow could help reduce mental load during the form flow and reduce the amount of task-switching (from data entry to file search/selection) during the already complex multi-page multi-response pattern. 
  - It would have the added bonus of allowing folks to answer the questions on the form, save their work, and return later to do all the file uploads in one sweep and in fewer screens.
  - Due to the complexity of this suggestion I fully acknowledge this is something y'all might not do. It's just on my mind because it's tax time and Intuit's file upload process to share documents with your accountant is a similar flow: walk users through a questionnaire, informing them based on their answers that they'll need to upload files at the end, then providing a place to upload and categorize files. I'm dropping in a screenshot of how part of this multi-file upload UI in Intuit looks (with mock data).
  ![intuit-upload](https://github.com/department-of-veterans-affairs/va.gov-team/assets/755248/349b5480-4bd4-4b58-9781-9f70a8acdf28)

*Thanks for work, and for giving us the chance to review and give feedback on your product!*

## Governance team actions
- [x] Format feedback as individual tasks (check boxes)
- [x] Assign this ticket to the VFS team member that opened the Slack request
- [x] Add the VFS team product label
- [x] Add the VFS team the feature label (if applicable)
- [x] Add the touchpoint labels
- [x] Add the practice area labels
- [x] Add the Collaboration Cycle initiative milestone
- [x] Add the Collaboration Cycle initiative epic

**Comment by syd-hoeper** [comment]
Feedback incorporate in this file: https://www.figma.com/file/UmAtr3ULQEInMXfNFwP0g0/10-10d-User-Testing-Prep?type=design&node-id=4%3A64769&mode=design&t=fzOojyFGMdhTn3KU-1

**Comment by baltes** [comment]
@syd-hoeper Does this need CAIA feedback before closing, or is that already covered in figma?
