### ISSUE TITLE
Investigate missing first time claim disability wizard question

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#7652]
## Background
We are missing the following question on Staging - "Is this the first time you are filing a disability claim with VA?". This was found during Tze's [work on our Test Plans](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7636#issuecomment-609542949). 

## Acceptance Criteria
- [x] Confirm the expected behavior and document here
- ~[ ] Make any necessary frontend, etc. fixes~

**Comment by ncksllvn** [comment]
Interestingly, there's a feature flag in place on Staging as of 11 days ago. The PR is this, https://github.com/department-of-veterans-affairs/vets-website/pull/12015, and the associated issue is https://github.com/department-of-veterans-affairs/va.gov-team/issues/6216.

The difference seems to be that when answering `Yes` to `Have you separated from your military or uniformed service?`, the prod version will show `Are you filing a new claim or are you disagreeing with a VA decision on an earlier claim?` whereas staging will show `Is this your first time filing a disability claim with VA?`.

**Comment by MickinSahni** [comment]
@ncksllvn i'm adding this preemptively to our next sprint

**Comment by ndsprinkle** [comment]
@ncksllvn @MickinSahni This is indeed intended behavior. Our team is in the process of rolling out support for original claims for the 526 form, so we won't need to gate on that question anymore. Instead, as Nick points out, you'll jump straight to the 3rd (currently, soon to be 2nd) question from the 1st question. As you already pointed out, this is currently only in staging. We still have some testing to do before we roll this out to production, but here are the PRs that remove the staging restriction: https://github.com/department-of-veterans-affairs/vets-website/pull/12146 & https://github.com/department-of-veterans-affairs/vets-website/pull/12147

**Comment by ncksllvn** [comment]
Thank you very much @ndsprinkle!

@MickinSahni I think the consensus here is that for our team's validation, we should just be using the prod-preview version of the pages instead of the staging.va.gov version. So, I think this investigation is all done?

**Comment by MickinSahni** [comment]
We've confirmed this is expected behavior that'll only exist in staging for now (and won't push to prod). Closing this investigation ticket. cc @tzelei to close the loop
