### ISSUE TITLE
Representatives in Trexler File are not returned in Find in Staging

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#76527]
## Expected vs. Actual
**Expected**: All reps in The Trexler File are searchable in Find a Rep in Staging.

**Actual**: I was verifying the rep phone numbers and noticed that I'm unable to pull up VSOs from The Trexler File in Find a Rep in Staging.

Note: Recently we updated the phone number handling (https://github.com/department-of-veterans-affairs/va.gov-team/issues/75692), and also the logic for the name field (https://github.com/department-of-veterans-affairs/va.gov-team/issues/76099).  I wonder if this is related to one of these updates.

## Steps to Reproduce

1. Select VSO
2. Enter "Virginia" in the location field
3. Select "Show all" for the radius
4. Enter "Hershey" in the name field
5. Search - no results

----

1. Select VSO
2. Enter Wisconsin in the location field
3. Select "Show all" for the radius
4. Enter "Borchardt" in the name field
5. Search - no results

## Examples
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEJwQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--62bedbf83418a6d25a442bd3eb5587ecee3b4977/image.png" alt="image.png" />

<img width="1506" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzlwQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a3164ad941e3d4bfad0634b39d5ea0bef88c8693/image.png" alt="image.png" />

----

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEZwQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c4d8afdeea624c8b7e9607054f6d161a16336d45/image.png" alt="image.png" />

<img width="1506" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNE5wQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cff5eb9bcb6d9366ae6db19e8aee4d8f038509ee/image.png" alt="image.png" />

**Comment by holdenhinkle** [comment]
These records have not been geo-coded yet:

**Hershey**:
=> [#<Veteran::Service::Representative representative_id: "56047", first_name: "Brittany", last_name: "Hershey", email: nil, phone: "202-861-2700", created_at: "2024-02-13 07:00:36.752517000 +0000", updated_at: "2024-02-13 07:00:36.752517000 +0000", poa_codes: ["074"], user_types: ["veteran_service_officer"], ssn: nil, dob: nil, encrypted_kms_key: nil, middle_initial: "A", address_type: nil, city: nil, country_code_iso3: nil, country_name: nil, county_name: nil, county_code: nil, international_postal_code: nil, province: nil, state_code: nil, zip_code: nil, zip_suffix: nil, lat: nil, long: nil, location: nil, raw_address: nil, full_name: "Brittany Hershey", address_line1: nil, address_line2: nil, address_line3: nil, phone_number: nil>]

**Borchardt**:
irb(main):001:0> Veteran::Service::Representative.where(last_name: 'Borchardt')
=> [#<Veteran::Service::Representative representative_id: "56052", first_name: "Luke", last_name: "Borchardt", email: nil, phone: "1-800-947-8387", created_at: "2024-02-13 07:01:49.542454000 +0000", updated_at: "2024-02-13 07:01:49.542454000 +0000", poa_codes: ["030"], user_types: ["veteran_service_officer"], ssn: nil, dob: nil, encrypted_kms_key: nil, middle_initial: "O", address_type: nil, city: nil, country_code_iso3: nil, country_name: nil, county_name: nil, county_code: nil, international_postal_code: nil, province: nil, state_code: nil, zip_code: nil, zip_suffix: nil, lat: nil, long: nil, location: nil, raw_address: nil, full_name: "Luke Borchardt", address_line1: nil, address_line2: nil, address_line3: nil, phone_number: nil>]
