### ISSUE TITLE
[Security - Controls Effort] SBOM generation IaC | Athena

### ISSUE THREAD

**Issue by hgbarreto** [department-of-veterans-affairs/va.gov-team#76532]
## Description
To meet and mature in some of our security controls, Infrastructure Services would like to create the IaC needed to support the SBOM generation resources. This story is specifically for the remaining AWS resources.

## Acceptance Criteria
- [ ] Create Terraform for remaining AWS resources (IAM, etc.)
- [ ] Document

## Refinement Guidance - Check the following before working on this issue: 
- [ ] _Team label assigned ("platform-tech-team-2")_
- [ ] _Epic assigned (if needed)_ 
- [ ] _Estimated (points assigned)_
- [ ] _Sprint assigned (once planned)_
- [ ] _Team member(s) assigned_
- [ ] _Understands how this work aligns with the overall platform_

**Comment by npeterson54** [comment]
Dupe of 76531
