### ISSUE TITLE
 [Security - Controls Effort] SBOM generation IaC | AWS Glue Crawler

### ISSUE THREAD

**Issue by hgbarreto** [department-of-veterans-affairs/va.gov-team#76530]
## Description
To meet and mature in some of our security controls, Infrastructure Services would like to create the IaC needed to support the SBOM generation resources. This story is specifically for AWS Glue Crawler.

## Acceptance Criteria
- [x] Create Terraform for AWS Glue Crawler
- [x] Document

## Refinement Guidance - Check the following before working on this issue: 
- [ ] _Team label assigned ("platform-tech-team-2")_
- [ ] _Epic assigned (if needed)_ 
- [ ] _Estimated (points assigned)_
- [ ] _Sprint assigned (once planned)_
- [ ] _Team member(s) assigned_
- [ ] _Understands how this work aligns with the overall platform_

**Comment by Efe-Oddball** [comment]
The code for the crawler has been completed and tested. I am writing the documentation for it and I will be pushing out the PR afterwards.

**Comment by Efe-Oddball** [comment]
This work has been completed and here is the approved [PR](https://github.com/department-of-veterans-affairs/devops/pull/14467) . Should move the ticket to a resolved state once the jenkins test passes

**Comment by Efe-Oddball** [comment]
Moving ticket to resolved
