### ISSUE TITLE
Change phone flag_type from 'phone' to 'phone_number'

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#76533]
## Background
Change phone `flag_type` from `phone` to `phone_number`.

I was just testing the app and discovered that I neglected to do this. Changing `flag_type` to `phone_number` will make the diffing code easier to write.

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/9326247/762ec4b5-e210-456e-bf14-076ad5bdde79)

## Tasks
- [ ] _Outline steps to complete_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this?_

---
#### How to configure this issue
1. Label with practice area (`backend`, `frontend`,`ux`, `design`, `research`)
2. Label for MVP work? (`mvp`)
3. Add an estimate 
4. Attach an Epic (what body of work is this a part of?)

**Comment by oddball-lindsay** [comment]
Waiting for approval from Lighthouse - Holden has pinged them

**Comment by oddball-lindsay** [comment]
@holdenhinkle I am still receiving this error when I try to report a phone number in Staging.
