### ISSUE TITLE
Direct links to content and IA standards

### ISSUE THREAD

**Issue by twoangstroms** [department-of-veterans-affairs/va.gov-team#76549]
### Description

In the "Objective" section, there are bullet points advising teams to work to the content and IA guidelines in the VA.gov site, but the links only go to VA.gov. Would it be possible to link directly to the relevant pages for these standards and style guides? When O search for "style guide", the search on VA.gov returns [a page](https://department.va.gov/style-guide/) more about the design system.

If these are not possible to link to directly, could we see what to search for?

### Which type of team are you on? (Platform team, VFS team, or Leadership)
Platform team, but working on guides for forms digitization.

**Comment by jknipes** [comment]
Hi @twoangstroms thank you for flagging this. We'll take a look, and review with some engineers to determine the best course of action for this page, and will work to get any updates reflected on the website.
We will provide further updates in this ticket. Please feel free to reach out if there are any questions.

**Comment by jknipes** [comment]
@twoangstroms could you please provide a link to the "Objective" section you mentioned above? Any relevant screenshots will also be helpful. Thanks!

**Comment by jknipes** [comment]
waiting further details from requestor

**Comment by jknipes** [comment]
Hi @twoangstroms , per our discussion on 5/23 in Slack, we are closing this ticket
