### ISSUE TITLE
TermsOfUse - Provide appropriate logging for update_provisioning call when terms of use has not been accepted

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#76559]
When update_provisioning is called, but the Sign Up Service Terms of Use has not been accepted, we raise an error that eventually becomes an `unprocessable_entity` response, but we don't really have a good way to tell that this happened. The response status is probably fine, but we should:
- Make a log that says 'sign up service update provisioning terms of use not accepted' or something like that
- Make sure the error message in the response is staging that we returned `unprocessable_entity` because the update_provisioning returned 'false' for terms accepted

**Comment by parkerbees** [comment]
Moved to Jira. Closing.
