### ISSUE TITLE
Add initial unit tests to service/controller

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#76563]
## Description
The initial setup of the integration is in code-complete. We need to add unit tests to
- establish good practices from the get-go
- pass CI

## Acceptance Criteria
- [ ] Unit tests for our module meets or exceeds the recommended threshold
- [ ] Unit tests either added as a separate PR, or added to [the PR that sets up the initial integration](https://github.com/department-of-veterans-affairs/vets-api/pull/15582/files)

## Demo
- Demoable? No
- How? n/a
- Impact? n/a

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by athifw** [comment]
New PR here: https://github.com/department-of-veterans-affairs/vets-api/pull/15840
