### ISSUE TITLE
[Spike] List of the current VAOS dashboard in DataDog

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#76561]
## Request
The team is looking into implementing DataDog RUM for the appointments tool on VA.gov. We are also considering building a composite dashboard that will include the vets-api monitoring that exists today in DataDog. 

### Goal
To view the list and determine if we can build a composite dashboard that could monitor the user's activity along with the vets-api transaction. 

### Requirements to Consider
Build a DataDog RUM dashboard that will include the user's activity along with the vets-api/services tracking. 

---

## Tasks
- Answer the following questions:
  - Q1: List of the dashboard(s) that we currently set up for DataDog for vets-api and provide a description for each

## Time Box
6 hours

## Definition of Done
- Tasks are complete
- Research and recommendations are documented in this ticket

**Comment by cferris32** [comment]
Q1: List of the dashboard(s) that we currently set up for DataDog for vets-api and provide a description for each

A1: Here is a descriptive list of the dashboards we use for our VAOS Alerts monitoring.

Sum of Vets-Api Errors
- tracks number of error responses raised from the controllers
- watches over a rolling 5 minute interval
- organized by controller, action, and response code

Sum of VAOS Service Failures
- tracks number of error responses received from upstream services
- tracks over a rolling 5 minute interval
- oragnized by http status, http method, and which endpoint raised the error

VAOS Service Partials
- tracks partial error responses from downstream services
- organized by method, controller, and message summary

Average VAOS Service Latency
- calculates average latency of VAOS endpoints over a rolling interval

Request Rate Alert
- tracks how many requests come in over a rolling interval

Breakers Skipped Alert
- alerts when the breaker flips, which blocks extra http calls when the request rate exceeds a certain threshold
- tracks over a rolling 10 minute interval
