### ISSUE TITLE
STEM: Update endpoint to accept new OMB form 22-10203

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#7656]
As a developer, I need to update the endpoint to accept the new STEM OMB form so that the form can be submitted electronically.

## Assumptions:
1. This work is completed behind the STEM Feature Flag.

## Acceptance Criteria
1. Allow the current endpoint to accept form 22-10203 (new STEM OMB form) submissions.
2. New STEM OMB form submissions are persisted.

## Supporting Artifacts:
1. N/A

**Comment by desireeturner** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-api/pull/4125
