### ISSUE TITLE
Add prod key mapping to manifests

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#76565]
## Description
In order for our MVP to work, we need to integrate with the prod travel pay API. Prod integration requires setting up the correct routes and config values in our secrets management framework.

[Notes on secrets management relationships](https://dsva.slack.com/archives/C05UTPZRZFY/p1710273538045589)

## Acceptance Criteria
- [ ] Secrets mapped in [vsp-infra-application-manifests](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/961646a8a1bd109c04e054bca8c2cc5dd9e67410/apps/vets-api/prod/templates/secrets.yaml#L147)
- [ ] Secrets linked in [vps-infra-application-manifests](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/961646a8a1bd109c04e054bca8c2cc5dd9e67410/apps/vets-api/prod/values.yaml#L697)
- [ ] Env values mapped in [vsp-infra-application-manifests](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/961646a8a1bd109c04e054bca8c2cc5dd9e67410/apps/vets-api/prod/values.yaml#L1878)

## Demo
- Demoable? No

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by ayush-chak** [comment]
This can only be done once the API is in prod - dependent on the BAH team
