### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#76577]
### Name

Vicky Bellissimo

### Email

virginia.bellissimo@va.gov or vicky.bellissimo@adhocteam.us

### Role

Product Manager

### Team

Pension Benefits

### Product Manager (PM) name

Vicky Bellissimo

**Comment by naomimarcussen** [comment]
Hi! An invite has been sent to vicky.bellissimo@adhocteam.us

**Comment by vbellissimo** [comment]
Thank you @naomimarcussen !
