### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by asmarehanna** [department-of-veterans-affairs/va.gov-team#76573]
### Name

HANNA ASMARE

### Email

hanna.asmare@bylight.com

### Role

QA engineer

### Team

MHV-SM

### Product Manager (PM) name

Christy Gales

**Comment by asmarehanna** [comment]
to get Figma access

**Comment by naomimarcussen** [comment]
Hi! An invite has been sent to hanna.asmare@bylight.com
