### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by Allexelaw** [department-of-veterans-affairs/va.gov-team#76580]
### Name

Allexe Law-Flood

### Email

allexe.law-flood@adhocteam.us

### Role

Research

### Team

Pension Benefits

### Product Manager (PM) name

Vicky Bellissimo

### Additional Notes

I need access to the Figma board and pension files

**Comment by naomimarcussen** [comment]
Hi! An invite has been sent to allexe.law-flood@adhocteam.us.
