### ISSUE TITLE
[Design] Create a UXPin prototype as a backup for usability testing

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#7659]
## User Story or Problem Statement
Problem description. How might we ensure there's a backup way to conduct usability testing if staging is not ready by April 15th?

## Goal
_A UXPin prototype of the full MDT flow to be used as a backup during usability testing_

## Objectives or Key Results this is meant to further
- _MDT usability testing_
---
## Tasks
- [x] _Create a prototype of the full MDT ordering flow using UXPin_

## Acceptance Criteria
- [x] _Link the UXPin prototype of the MDT_

**Comment by rebeccawalsh** [comment]
Prototype can be seen here! https://preview.uxpin.com/6eac3d277fb657b17dbeef85149d862b1279c05c#/pages/127630404/comment/comments?mode=i
