### ISSUE TITLE
Log Community Care Eligibility Response

### ISSUE THREAD

**Issue by JRRoof** [department-of-veterans-affairs/va.gov-team#76605]
## Description
A veteran recently created a Community Care appointment request, but when VA staff reviewed the request the veteran was ineligible for Community Care.  In order to troubleshoot this situation in the future we want to log the requests being made to the CCE api and the response being received.  Please include the type of care being requested in the CCE api call.

---

## Acceptance Criteria
Background: No feature toggle is needed

Given a veteran
When trying to request an appointment
Then log the community care eligibility request and response

### Design Assets
Not applicable

## Definition of Done
- [x] All acceptance criteria are met
- [x] Documentation is updated

---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ajmagdub** [comment]
Added response logging to VAOS::V2::CCEligibilityService#get_eligibility
