### ISSUE TITLE
[FE] Re-base the Unified Branch

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#76604]
## Tasks
- [FE] Re-base the Unified Branch
- We will merge over the "Are you at the facility?" page and the new content on the completion page as-is

**Comment by brianseek** [comment]
@brianseek review please

**Comment by brianseek** [comment]
This rebase looks good. I also did a quick follow up rebase with my pre-check-in error changes. We are still behind where figma is with some unified things but also ahead in others. I think we will need to reconcile design with dev before we start back up on this work. But this work looks great. Closing the ticket. Nice work @wullaski !
