### ISSUE TITLE
Revisit our product guide and update accordingly

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#76601]
## Issue Description
As part of our Pension MVP relaunch, we were required to create a Product Guide document to the general experience of the online Pension form for Veterans to the Contact Center.

Since the launch, several revisions have been made to the online Pension form.

We need to revisit the Product Guide and determine if we need to make any updates to it,
so that we can make sure it is still accurate,
so that the Contact Center has the most updated information,
so if Veterans call the Contact Center about the online form, they are equipped to help them with the most accurate information.

---
## Tasks
- [ X] Review our existing online Pension form [product guide found in Github](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/pension/product-guide). Original [Github ticket for Contact Center review here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/73112#issuecomment-1888206780) for reference.
- [x ] Determine whether we need to make any updates to it
- [ x] Reach out to the Contact Center to determine whether they need to provide sign-off again

## Acceptance Criteria
- We will have determined whether we need to make any updates to the existing Product Guide
- We will have asked the Contact Center about the process to update the Product Guide
- We will have updated the Product guide accordingly

**Comment by matt4su** [comment]
1. Updated the Guide.  Changes included updates to the following areas: New URL, updated guide related to several post launch enhancements including the following areas: Health and employment, Previous employment, Income and Assets, Direct Deposit, Other payment options, Supporting documents, Additional information,  Review and submit
2. reached out to Platform Team to determine if review was needed and they indicated that it was.  A new contact center review ticket should be created.
3. Created new contact center review ticket and submitted it. 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/79638
4. Next step is to await approval.
