### ISSUE TITLE
[UX] 10-10EZ: Figma Production Audit + Field Error Messages in Figma

### ISSUE THREAD

**Issue by aagosto90** [department-of-veterans-affairs/va.gov-team#76634]
As a user, I would like the elements of the 10-10EZ to be consistent and look as good as possible so that I can easily apply for VA health care online.

As a designer/team member, I want there to be a full and accurate reference of all the error messages a user could encounter. 

CG ticket for reference on error audit: [Design] 10-10CG - Improvements: Content Cleanup post-July update #89939

- [x] Review components in Figma design compared to the STG site and note what is different
- [x] Create empty state errors and take screen captures to update [existing Mural ](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1683651181051/e0f47b9aaefbf78a3942df3028525cdc4336caff?wid=0-1683654306160)
- [x] Try to create any other on field validation errors and take screen captures to place in Mural
- [x] Create a page in Figma to work on error states in field components
- [x] List out what components need to be updated in Figma (or on STG if necessary)
- [x] Create a side-by-side comparison of any 
- [x] Come up with a plan to update these components (we can have a separate story for that if it's a big lift, or bake it into this story)

Note: This story can be done in conjunction with figuring out what non-V3 components we have #[75036](https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/75036)

Acceptance Criteria 
- **Success: We know how accurate Figma is and what still needs to be updated and we have a side by side visual.**

**Comment by jessicastump** [comment]
Noting a couple of repeating/global issues noticed so far:

----
**1. The error states in staging/production for some fields do not have correct formatting, the label is not bold when in error state (screen capture example below)**
<img width="520" alt="Screenshot 2024-09-20 at 7 48 00 AM" src="https://github.com/user-attachments/assets/026812df-7326-48dc-9b42-a17fb37bf46e">
<img width="466" alt="Screenshot 2024-09-20 at 7 50 07 AM" src="https://github.com/user-attachments/assets/9f339cac-7c63-4226-ab28-587f25e175f5">

--- 

**2. The color of some of the headlines is not the default vads-color-base as in the Figma file; gray shade lighter in staging/production.**

<img width="541" alt="Screenshot 2024-09-20 at 7 51 54 AM" src="https://github.com/user-attachments/assets/9fc5b24d-0478-4d48-9623-2e208b4c1446">
<img width="503" alt="Screenshot 2024-09-20 at 7 51 44 AM" src="https://github.com/user-attachments/assets/e5130604-d644-469d-8432-3e605da3c94e">

**Comment by jessicastump** [comment]
<img width="531" alt="Screenshot 2024-09-27 at 1 32 01 PM" src="https://github.com/user-attachments/assets/73a6f0da-2b2e-4d69-9e83-f3027fe96df8">
Noting here as this happens on all fields asking for money amounts; will update Figma with more details.

**Comment by jessicastump** [comment]
The [Figma file](https://www.figma.com/design/UljiHam46o5DItC5iDgmPd/10-10EZ?node-id=6341-48605&node-type=canvas&t=ybQcIHSg2hryaf6q-0) is updated with error message updates and side-by-side compare.

### Summary of the findings: 

**Figma overall issues to note:** 
- Mobile breadcrumbs
- Date formatting (needs to reset to fix off alignment)


**Staging / Production Overall to note:** 
- Error messages to remove “please” 


**Intro page:**
- Staging/Prod: Paragraph formatting on intro
- Figma: icon by headline for first sign in box


**Veteran information section:** 
- Error message updates 
- Formatting on error messages - label does not turn to bold
- Label header / h3 color - used vids-color-base in Figma


**VA Benefits:**
- Error message
- 2 instances of additional info component placement (needs moved for v3)


**Military service:** 
- Error messages and formatting


**Household information section:**
- Marital status page
- Moving additional info component out from between label and radio buttons (v3)
- Fix error message on invalid entry for amounts (income and deductibles)
- Questions for dependents required in Figma file, not in staging/prod (financial support and enrolled student)


**Insurance:**
- Insurance add on hold: 2 versions in both Figma and staging/prod for multiple responses work


**Review:** 
- Link icon added to privacy policy

**Comment by jessicastump** [comment]
I took another look at this one (it's been open a long time and trying to get it wrapped up :) to see where it was at, and: 

- I added the insurance screen captures for the errors on the multiple responses pattern in staging. 
- I think everything else is covered...

@aagosto90 -- Thoughts on closing this ticket with what exists in the [Figma file](https://www.figma.com/design/UljiHam46o5DItC5iDgmPd/10-10EZ?node-id=6341-48605&node-type=canvas&t=anqQarkMk6bzmbjy-0), and having another ticket to discuss with the team and open the needed content or dev tickets?

**Comment by aagosto90** [comment]
@jessicastump If we've been through all the EZ screens in staging to compare then yep I agree with that! Good idea to make a followup ticket for what you uncovered.
