### ISSUE TITLE
[UX] 10-10CG: Figma/STG Audit

### ISSUE THREAD

**Issue by aagosto90** [department-of-veterans-affairs/va.gov-team#76635]
As a user, I would like the elements of the 10-10CG to be consistent and look as good as possible so that I can easily apply for VA health care online.

- [ ] Review components in Figma design compared to the STG site and note what is different
- [ ] List out what components need to be updated in Figma (or on STG if necessary)
- [ ] Come up with a plan to update these components (we can have a separate story for that if it's a big lift, or bake it into this story)
- [ ] This story can be done in conjunction with figuring out what non-V3 components we have #[75036](https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/75036)
- [ ] **Success: We know how accurate Figma is and what still needs to be updated.**

**Comment by jessicastump** [comment]
@aagosto90 - I think we can close this ticket - what is in Figma file does match and this can be considered updated when we do the source of truth moving of designs when the new updates go live on July 1... maybe we repurpose this ticket name/tasks to account for making sure the source of truth designs/content/user flows/etc are all aligned in July?
