### ISSUE TITLE
Discovery - Follow up to #54319 Lighthouse changes 

### ISSUE THREAD

**Issue by asmithgovcio** [department-of-veterans-affairs/va.gov-team#76641]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

There are API's we have access to but are managed by the lighthouse team, we are able to access these via the sandbox access. In the near future lighthouse is planning to add more API endpoints that we will want to integrate as part of the vets-api codebase. 

We need to follow up with Jessica Sexton regarding where they are in the process of sizing out/completing the work required on the lighthouse side. Right now they are not ready to size any work and won't be until April 2nd, 2024 at the earliest. 

---
## Tasks
- [ ] Follow up with Jessica Sexton, ask about sizing of Lighthouse API work

## Acceptance Criteria
- [ ] We will know what amount of effort is required on the lighthouse side and be better prepared to do work on the vets-api side, making sure were in sync
---

**Comment by HeatherRienks** [comment]
closing- this is no longer needed
