### ISSUE TITLE
2024 Q1 PACT Act Support: Review and adjust monitoring dashboards

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#76654]
## Objective 
Review and adjust the current monitoring dashboards and bulkheads in preparation for the third round of PACT Act submissions.

## Goal
- [ ] Review and adjust [the existing dashboard ](https://vagov.ddog-gov.com/dashboard/gfw-rwf-w5r/pact-act---second-cohort-9302023?refresh_mode=sliding&view=spans&from_ts=1707848058962&to_ts=1708452858962&live=true) for the current bulkhead monitoring needs.
- [ ] Observe and compare error trends before and during the submission surge.

## Background
Monitoring our systems is a critical component of our operational excellence. It provides real-time visibility into the health and performance of our services. By observing error trends and traffic volume, we can anticipate issues before they become critical, allowing us to maintain the integrity of the PACT Act submissions process and va.gov overall. We strive for the best user experience and maintaining a high standard of service reliability.

## Action Items
- [x] Review the existing dashboard created for the previous submission rounds.
- [x] Identify any new requirements or adjustments needed for the current round of submissions.
- [x] Adjust the dashboard to reflect the current monitoring needs.
- [x] Define thresholds for latency, errors, and traffic volume that will trigger alerts.
- [x] Validate alerting mechanisms with test cases to ensure they are functioning as expected.
- [x] Document any changes and communicate them to the relevant teams.

## Expected Outcomes
- An updated monitoring dashboard tailored to the current bulkheads.
- Insights into system performance through the observation of error trends.
- Proactive alerting to prevent system outages or degradation.
- Enhanced ability to maintain service quality during high traffic periods.

## Importance of Monitoring
Monitoring is the heartbeat of our system operations. It ensures that our services are performing optimally and that any deviations are detected and addressed promptly.

**Comment by jennb33** [comment]
Link to [this dashboard](https://vagov.ddog-gov.com/dashboard/gfw-rwf-w5r/pact-act---second-cohort-9302023?fromUser=true&refresh_mode=sliding&view=spans&from_ts=1709394695769&to_ts=1709567495769&live=true)

**Comment by rmtolmach** [comment]
I accidentally completed this ticket while working on https://github.com/department-of-veterans-affairs/va.gov-team/issues/76695. I ended up adjusting a _different_ dashboard than the one linked in the description 😒 oops. 

Here's the dashboard I worked on: [PACT Act bulkheads (HCA, ITF, Forms) 2024](https://vagov.ddog-gov.com/dashboard/m3w-yd3-2a6/pact-act-bulkheads-hca-itf-forms?fromUser=true&index=%2A&refresh_mode=sliding&view=spans&from_ts=1709570812233&to_ts=1709743612233&live=true)

Closing as a duplicate.
