### ISSUE TITLE
2024 Q1 PACT Act Support: Sidekiq Monitors

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#76659]
## Summary

Establish comprehensive monitoring and alerting for Sidekiq to ensure proactive issue detection and communication during the PACT ACT submission surge (including retry queue, puma backlog, etc ) 

## Goals

- [x] Implement monitoring on Sidekiq retry queues and other critical metrics (there's already a dashboard somewhere, just flag it)
- [x] Set up alerts for key performance indicators to notify relevant parties via PagerDuty and Slack channels.
- [x] Confirm the functionality and responsiveness of alerts to ensure quick action during peak loads.

## Background

As PACT ACT submissions are likely to utilize Sidekiq for background job processing, it's imperative to have a vigilant monitoring system. This will give us the ability to preemptively address any issues such as an increasing retry queue, which can be indicative of underlying problems.

## Action Items

- [x] Review and enhance existing Sidekiq monitoring tools and dashboards.
- [x] Identify critical Sidekiq metrics that require alerting (e.g., size of retry queue, job processing time, error rates, puma backlog).
- [x] Configure alerts to ensure that they reach the assigned on-call engineers and specified Slack channels.
- [x] Document the monitoring and alerting process, specifying the roles and responsibilities for responding to Sidekiq-related alerts.

## Importance of Sidekiq Monitoring

Effective monitoring and alerting for Sidekiq are essential to:
- Maintain high throughput and efficiency in background job processing.
- Avoid job backlogs and ensure timely processing of PACT ACT submissions.
- Quickly identify and troubleshoot issues before they affect the application's performance.
- Reduce the need for manual intervention due to the existing HPA (Horizontal Pod Autoscaling).

With Sidekiq's inherent HPA, we do not anticipate scaling issues; however, monitoring remains critical for overall system health and throughput.

## Expected Outcomes

- A reliable monitoring system that provides visibility into Sidekiq performance.
- Well-defined alerts that facilitate immediate response to potential issues.
- Enhanced operational readiness and system resilience throughout the PACT ACT submission process.

**Comment by jennb33** [comment]
@flooose is in the process of validating these monitors

**Comment by rmtolmach** [comment]
All sidekiq monitors are alive and well: https://vagov.ddog-gov.com/monitors/manage?q=%5BEKS%5D%20%5Bsidekiq%5D&order=desc
