### ISSUE TITLE
2024 Q1 PACT Act Support: RDS Monitors

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va.gov-team#76655]
## Summary

Ensure that Vets API RDS alerts and monitors are fully operational and set to notify the appropriate teams in case of potential system capacity, latency, etc issues.

## Goals
- [x] Verify existing RDS monitors and alerts for system storage capacity.
- [x] Set up notifications to alert relevant parties before storage thresholds are reached.
- [x] Review and update RDS monitoring thresholds and alerts if necessary.

## Background

Given the high volume of submissions expected to interact with our database systems, it is critical to monitor our RDS instances to prevent system crashes due to storage capacity being reached. Proactive monitoring will help to mitigate risks of downtime or data loss.

## Action Items

- [x] Conduct an audit of current RDS alerting mechanisms for system storage capacity.
- [x] Update alert thresholds to ensure early warning ahead of potential system capacity issues.
- [x] Ensure that alerts are configured to notify the appropriate teams via Slack and PagerDuty
- [x] Document the RDS monitoring process and alerting protocols.

## Importance of RDS Monitoring

Effective RDS monitoring is vital to:
- Prevent service interruptions due to storage capacity issues.
- Maintain data integrity and availability.
- Ensure that performance remains optimal even as system load increases.
- Allow for timely and informed decision-making in the event of potential system constraints.

Proactive alerts provide us with the ability to address issues before they escalate, maintaining our commitment to service reliability and performance.

## Expected Outcomes

- A robust set of RDS alerts and monitors tailored to our system's needs.
- Clear documentation and communication protocols for responding to RDS capacity alerts.
- Enhanced system reliability and uptime, with safeguards against capacity-related incidents.

**Comment by flooose** [comment]
- These are the monitors we can use

**Comment by rmtolmach** [comment]
RDS monitors: https://vagov.ddog-gov.com/monitors/manage?q=RDS&order=desc

**Comment by jennb33** [comment]
@flooose is in the process of validating these monitors

**Comment by rmtolmach** [comment]
We have the RDS monitor, [VETS API - PROD - RDS - High CPU Utilization](https://vagov.ddog-gov.com/monitors/198987) that warns and alerts on appropriate thresholds and is documented here: https://vfs.atlassian.net/wiki/spaces/PPT/pages/2966159668/Vets+API+Alert+and+Monitoring+Trends

Closing since there's nothing more to be done here.
