### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by timothy-steele-va** [department-of-veterans-affairs/va.gov-team#76668]
### Name

Timothy Steele

### Email

timothy.steele@va.gov

### Role

Test Engineer

### Team

VA.gov Medical Records

### Product Manager (PM) name

Lichelle Bain

**Comment by naomimarcussen** [comment]
Hi! An invite has been sent to timothy.steele@va.gov

**Comment by timothy-steele-va** [comment]
Thanks, I got the invite! I'm in Figma now
