### ISSUE TITLE
What's the value of the land that's more than 2 acres? Value showing in PDF but not in raw data

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#76678]
## Issue Description
Quote from Daniel Gifford at VBA:
_Looking at one of the PDFs from the new data, I found one where the claimant marked "no" to: Is your home located on a lot of land that’s more than 2 acres (or 87,120 square feet)?. The PDF shows a value of $20k in the next box, but that 20k is not in the raw data._

Example of questions...

<img width="667" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1o2QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7e63163b996f0d7f8d485b4b55f39e84f9cc1587/Screenshot%202024-02-21%20at%2010.28.06%E2%80%AFAM.png" alt="Screenshot 2024-02-21 at 10.28.06 AM.png" />

<img width="667" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2g2QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--99dd9b2fbabd09ed90e3e1249b5fad2a9b9097ee/Screenshot%202024-02-21%20at%2010.28.28%E2%80%AFAM.png" alt="Screenshot 2024-02-21 at 10.28.28 AM.png" />

## Acceptance Criteria
- Attempt to replicate this issue, troubleshoot as needed
- The value for the question _What’s the value of the land that’s more than 2 _acres?_ will be shown in both the raw Json data & generated PDF shown to the business.

**Comment by aplatt-coforma** [comment]
Followed these steps:

1. Fill out the form at http://localhost:3001/pension/application/527EZ. In the financial information section, say that you own a home, it is over 2 acres, and it has a value of $20,000.
2. On the review page, edit the data to state the you do not own your own home. Don't change any other data. You will see the question about the home acreage value disappear.
3. Submit the data
4. Reviewed the PDF

<img width="859" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2VIQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e0fade586b816d2b9e9f5b05022fce2fbcc806bb/Screenshot%202024-02-23%20at%2011.05.59%E2%80%AFAM.png" alt="Screenshot 2024-02-23 at 11.05.59 AM.png" />
