### ISSUE TITLE
[FSR] - Post Logic Shift/Endpoint Usage Testing

### ISSUE THREAD

**Issue by OptionSelect** [department-of-veterans-affairs/va.gov-team#76698]
## Description

FE team will break test the new endpoints as much as possible to prove that everything is working correctly.

## Tasks
- [x] FE team break testing

## Acceptance criteria

- [x] FE team tested and confirmed everything is in working order

**Comment by OptionSelect** [comment]
I've tested every which way I can personally and think we're in good shape! That said this ticket does say team so we might want Andrew/Aaron to double and triple confirm with me!

**Comment by Dr-Pongo** [comment]
Closed out late cus of me but also seems solid!!
