### ISSUE TITLE
[Congressional]  V11426360 - Website Issues (Sem. Schumer) Due 4/1/2024

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#76709]
## Issue Description
Veteran cannot contact the Jamestown VA Clinic without going through the switchboard in Buffalo. It's an issue because they are having a difficult time with their website because of the new changes.

https://app.slack.com/client/T03FECE8V?selected_team_id=T1ZD0UBMZ 
---
## Tasks
- [x] Review congressional correspondence
- [x] Resolve issue 
- [x] Notify Veteran and congressional correspondence channel of solution.

## Acceptance Criteria
- [x] Veteran issue will be resolved or responded to with final answer to issue 
- [x] Congressional Correspondence will receive details of the resolution 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2023-CSM** [comment]
I just called the number listed on VA.gov AND Google for the Jamestown VA Clinic.  I spoke to the operator Ms. Maui (first name) and she informed me this is a new process they have incorporated.  All of the VA Clinics in the area now go through the Buffalo switchboard.
She informed me that they all are getting used to the change, but it looks to be a permanent process.
Therefore, all information on VA.gov is technically correct.  I will be reaching out to the user via email and phone call to advise of this update.

**Comment by ATMiddleton** [comment]
Just spoke with the Veteran and confirmed the information within the email.  He stated that he is grateful for the follow up and call and the new process will take some getting used to.
This case is closed!

**Comment by Kimberley2023-CSM** [comment]
Just spoke with the Veteran and confirmed the information within the email.  He stated that he is grateful for the follow up and call and the new process will take some getting used to.
This case is closed! :closed_sign:
