### ISSUE TITLE
[CAIA A11y Research]: Disability Benefits: Contention Classification Team - New Conditions Page: Form: 21-526EZ (EOM July-Aug 2024)

### ISSUE THREAD

**Issue by sara-amanda** [department-of-veterans-affairs/va.gov-team#76707]
> [!NOTE]
> **High-Level Overview**: Contention Classification Team
> - **Initial Kickoff**: Feb. 21, 2024
> - **Status**: `RCVD` - Official Time Slots and Scheduling A11Y Support from Disability Benefits Team
> - **Research Timeframe**: 🆕 ➡️ 7/24 - 8/1/2024 [(per 7/10/2024 comment)](https://github.com/department-of-veterans-affairs/va.gov-team/issues/76707#issuecomment-2221700984)
> - **Audit Prototype**: `COMPLETED` Audit of CodePen Prototype Prior to Research [76766](https://github.com/department-of-veterans-affairs/va.gov-team/issues/76766)
> - **Audit Staging**: `COMPLETED` Audit of Staging Prototype Prior to Research [83767](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83767)
> - **Pilot**:  `COMPLETED 7/22/2024` [76779](https://github.com/department-of-veterans-affairs/va.gov-team/issues/76779) - prior to the start of testing; may conflict now with w/o 7/15 having limited CAIA Availability for Pilot (however, two audits were performed on this)
> - **Assistive Tech Users**: `8` AT Users [(Recruiting 8 AT users; needing 4 SR and 4 SM)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/research/CC-Team-Research/202403%20Improved%20Autosuggest/researchplan-assistedtech.md#recruitment-approach)
> - **Artifacts Available**: [NEW updated artifacts as of 7/10/2024](https://github.com/department-of-veterans-affairs/va.gov-team/issues/76707#issuecomment-2221700984)
> - **Testing Environments:** 
>     - [CodePen](https://codepen.io/ccteam/live/ZEZeMPR)
>     - [Staging](https://staging.va.gov/disability/file-disability-claim-form-21-526ez/new-disabilities-revised/add): "We will use the live page for testing. Users will log into test user accounts on staging" - [per Research Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/research/CC-Team-Research/202403%20Improved%20Autosuggest/researchplan-assistedtech.md#methodology)
> - **Assistive Tech Being Used**:  `PENDING DETAILED INFO`
>     - Screen Readers (Types Needed) and Screen Magnification
>         - Add AT in [Testing Schedule Table](https://github.com/department-of-veterans-affairs/va.gov-team/issues/76707#:~:text=Toggle%20to%20view%20the%20AT%20testing%20schedule)
>         - **Examples**: VoiceOver, Fusion, JAWS, and Screen Magnification
> - **Task Lists**:  [See task lists for next steps/definition of done](https://github.com/department-of-veterans-affairs/va.gov-team/issues/76707#:~:text=reveal%20supporting%20artifacts-,Next%20steps,-Contention%20Classification%20Team)

## CAIA Assignee(s)
- @coforma-jamie 
- @sara-amanda 
- @EvanAtCoforma 

## About the Contention Classification Team

<details><summary> Toggle to reveal team information</summary>

- **Team name:** Contention Classification
- **OCTO product owner:** Jen Bertsch
- **Product name:** 526EZ
- **Product manager:** Yurena Garcia
- **Slack channel:** [benefits-contention-classification](https://join.slack.com/share/enQtNjYwMDExOTQyMDc1Ny1iOGNlYTE4ZjY4OGM2YmUzOWE3YmY3MTMwMzA4MzRkMzQyNWVjMzE3NDQ0ODk4NDMzYmJhNjNmNGRiN2FjM2Vj)
- **Dedicated content writer on your team (if you have one):** N/A
- **Dedicated a11y specialist on your team (if you have one):** N/A

</details>

## Background Info

> We are updating the "add new conditions" page on the 526EZ Form. We started with updating the conditions themselves, the list that the autosuggestion component (dropdown) uses. Now, we are focused on UI and copy changes.

<details><summary>Toggle to view additional background information about this project.</summary>

> Our goal with the new conditions page is to improve user experience and accuracy when entering medical conditions for disability benefits. We aim to simplify the process by creating a user-friendly interface that enables Veterans to select or input their conditions effortlessly. Specifically, we aim to ensure that users understand how the autosuggest component functions, what information they need to provide, and that it supports free-text entries.

</details>

<details><summary> Toggle to reveal additional team information from the research intake ticket</summary>

### Do you have an accessibility champion?

No, we don't have a champion (yet)

### Calendar checking

- [X] Based on this calendar, confirm we have specialists who can support your study in your desired timeframe
- [X] Confirm you are filing this support ticket at least 1 week in advance of said timeframe, so we have enough heads up to provide support

### Have you reviewed the CAIA capacity calendar?

- [X] Yes, we have reviewed the CAIA capacity calendar and can confirm specialists are available to support in our research timeframe

### When is the timeframe for your testing?

CodePen Prototype should be ready for testing by March 13, 2024, per intake ticket and kickoff meeting conversations on 2/21/2024

[See update re: timeframe comment in Pilot Ticket as of 6/25/2024](https://github.com/department-of-veterans-affairs/va.gov-team/issues/76779#issuecomment-2173729058)
</details>

## Research Sessions

> [!TIP]
> - Providing CAIA A11ys with the time slots in advance for AT users, will allow a11ys to avoid conflicts on the CAIA A11y Capacity Calendar, and reach out to other a11ys, should CAIA not be available. 
> - Providing CAIA A11ys with the technology and devices the users will be testing with, will allow CAIA to prepare in advance for the sessions. 
> - We also recommend running a pilot session with CAIA a11ys, prior to your assistive technology research sessions, to mitigate any issues that may occur, in advance.

<details><summary>Toggle to view research timing information.</summary>

### Timeframe

- **Pilot Session**: `COMPLETED 7/22/2024` [76779](https://github.com/department-of-veterans-affairs/va.gov-team/issues/76779) - prior to the start of testing on ~4/10/2024~. ~4/4/2024~ Now end of May 2024.
- **Timeframe**: ~4/10/2024 - 4/23/2024 4/4/2024 - 4/12/2024~
    - May not be able to completed due to limited CAIA Availability w/o 7/15 testing week of 7/22.
    - However, two audits have been done by CAIA A11Ys. 
    - The week 

#### REVISED TIMEFRAME

- June 10:
    - ~Launch (during sprint 33 June 5 - 18)~
- June 19-July 2:
    - ~They will be preparing for AT user testing (during sprint 34)~
    - ~Assuming we can do the pilot in here, so I flagged it for 6/19 on the tracker (for now).~
- July 3 - July 17:
    - ~(during sprint 35) there appears to be recruitment for user testing at the end of that sprint (based on the Mural).~
     - ~So, I put testing on the research calendar as holds for then.)~

##### Adjusted Timeframe 
- As of 7/10/2024 [Testing will take place 7/24-8/1/2024 with 8 users](https://github.com/department-of-veterans-affairs/va.gov-team/issues/76707#issuecomment-2221700984)
- As of 7/3/2024 Testing to take place [week of: 7/22/2024](https://github.com/department-of-veterans-affairs/va.gov-team/issues/76779#issuecomment-2207135062)
- As of 6/25/2024 Testing to take place in "early July."  July 22, 2024
[View Comment in Pilot Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/76779#issuecomment-2173729058)

### Length of sessions
- Length of Sessions: 45 minutes for screen magnification (cohort 1) and 90 minutes for screen reader (cohort 2).
- Buffer time between sessions: 30 minutes 
- Maximum Sessions per day: 3

#### Session Windows

**As of 7/10/2024 in the revised Research Plan:** 
**Roughly: (10 a.m.-5 p.m.ET)**
- July 24th: 7:30AM PST - 2:00PM PST 
- July 25th: 9-10 AM PST, 11am-2pm PST 
- July 29th: 7:30 AM PST - 2:00PM PST 
- July 30th: 7:30 AM - 10:30 PST , 12:00 - 2:00PM PST 
- July 31st: 7:30 AM - 10:00 AM PST, 11AM - 2:00PM PST 
- August 1st: 7:30 AM - 2:00 PM PST 

</details>

###  Testing Schedule

> [!CAUTION]
> #### LIMITED CAPACITY 7/5-7/17
> There will be limited CAIA A11Y capacity 7/5-7/12, with 50% (2) of CAIA A11Ys OOO. There will be 75% (3) CAIA A11Ys available 7/12-7/17. 
> #### Dates with No Conflicts
> There is currently no coverage conflict for 7/22.
> The week of 7/29/2024 there appears to be no conflicts as of 7/10/2024.

#### Scheduling Source of Truth
📆 [Refer to the Disability Benefits Team's Google Sheet for the scheduling source of truth.](https://docs.google.com/spreadsheets/d/1nrqw-iekbkWM2oDwBPvaFqo76tOHZJNn55RTJQviixQ/edit?usp=sharing) 
- The following table, is updated based on A11Y involvement, and can be behind updates made to the sheet. Please refer to the Google Sheet for accuracy. 
- CAIA A11Ys will be looking for device and AT information. We realize that some of this information will not be available until the day of the session. 
- Please toggle and use the following table to enter the following information for each participant: Date and Time, Assistive tech (AT), Device and Operating System, Browser, and Skill level:

<details><summary>Toggle to view the AT testing schedule</summary>

P# | Date and Time (ET) | AT | Device and OS | Browser | Skill | CAIA A11ys Available | Status
------------------|------------------|--------------|--------------|--------------|--------------|--------------|--------------
Pilot | July 22, 2024 4 p.m. | JAWS | Desktop; Windows | Edge | Advanced | Jamie and Sara | `COMPLETED`
P1 | 7/24/24, 10:30-11:30 am | Windows Magnifier | Desktop; Windows | Firefox | Advanced | Jamie | `COMPLETED` ✅ 
P2 | 7/24/24, 12:30-1:30 pm | ZoomText | Desktop; Windows | Safari, Chrome, etc. `TBD` | Novice, Intermediate, Advanced `TBD` | @sara-amanda | `NO SHOW` ❌ 
P3  | 7/25/24, 10:30-11:30 am | ~~ZoomText~~ none | Desktop; Windows | Safari, Chrome, etc. `TBD` | Novice, Intermediate, Advanced `TBD` | Jamie | `NO AT` ❌ 
P4 | 7/25/24, 12:30-1:30 pm | TalkBack | Mobile; Android | Chrome | Advanced | Evan | `COMPLETED` ✅ 
P5 | 7/25/24, 3:00-4:00 pm | VoiceOver | Mobile or Desktop; Windows, MacOS, iOS, Android, etc. `TBD` | Safari, Chrome, etc. `TBD` | Intermediate | Evan | `COMPLETED` ✅ 
P6 | 7/29/24, 10:30 am - noon | VoiceOver | Mobile or Desktop; Windows, MacOS, iOS, Android, etc. `TBD` | Safari, Chrome, etc. `TBD` | Advanced | Jamie | `SCHEDULED`
P7 | 7/29/24, 2:00-3:30 pm | VoiceOver | Mobile or Desktop; Windows, MacOS, iOS, Android, etc. `TBD` | Safari, Chrome, etc. `TBD` | Intermediate | Evan | `SCHEDULED`
P8 | 7/30/24, 10:30-11:15 am | Screen Magnification | Desktop; MacOS| Chrome | Novice | Jamie | `COMPLETED` ✅ 
P12 | 7/30/24, noon-1 pm | Screen Magnification | Mobile; Android | `TBD` | Advanced | Jamie | `NO SHOW` ❌ 
P9 | ~7/31/24~ 7/30, ~10:30-noon~ 3-4 p.m. | VoiceOver | Mobile or Desktop; Windows, MacOS, iOS, Android, etc. `TBD` | Safari, Chrome, etc. `TBD` | Advanced | Sara  | `NO SHOW` ❌ 
P10 | 7/31/24, ~12:30- 2pm~ 10:30-noon | JAWS | Desktop; Windows | Chrome | Intermediate | Jamie | `COMPLETED` ✅
P11 | 7/31/24, 12:30 - 2 p.m. | VoiceOver | Mac (Mobile?) | Safari, Chrome, etc. `TBD` | `TBD` | Jamie | 🔴 `CANCELED`

- **Consideration**: You can also consider asking participants more specific AT and device combinations. 
- **For instance:** TalkBack on Samsung Galaxy 8, or VoiceOver on iPad with magnification.

</details>

CAIA A11ys will review the coverage needed, and self-assign, based on a11y availability.

### Received Artifacts
- [Research plan ](https://github.com/department-of-veterans-affairs/vagov-claim-classification/blob/main/collab-cycle/%5Bimproved%20autosuggest%20component%5D/research-plan.md)
- [REVISED RESEARCH PLAN - RCVD 7/10/2024](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/research/CC-Team-Research/202403%20Improved%20Autosuggest/researchplan-assistedtech.md)
- [CONVERSATION GUIDE - RCVD 7/10/2024](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/research/CC-Team-Research/202403%20Improved%20Autosuggest/conversationguide-assistivetech.md )
- [Prototype for testing ](https://codepen.io/ccteam/live/ZEZeMPR)
- [Mural board for wireframes](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1689885142486/f54c64b6eb52b4ac7eca4fb926a946aa072f2ed8?wid=0-1706739182333)

> **There are two variations**: "removing additional information" and "Adding additional information to component". We can test variations of both options or consolidate to one if there's a strong opinion.

### Pending Artifacts

<details><summary>Toggle to reveal supporting artifacts that are not yet available</summary>

### Additional Items

- [Product outline](Insert URL here between the parenthesis)
- [User flows](Insert URL here between the parenthesis)
- [Research conversation guide - RCVD 7/10/2024](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/research/CC-Team-Research/202403%20Improved%20Autosuggest/conversationguide-assistivetech.md)
- [Research Plan](https://github.com/department-of-veterans-affairs/vagov-claim-classification/blob/main/collab-cycle/%5Bimproved%20autosuggest%20component%5D/research-plan.md) - added 7/10/2024
- [Epics/issue that may be helpful](Insert URL here between the parenthesis)

</details>

### Next steps

```[tasklist]
### Contention Classification Team Tasks
- [x] **SCHEDULE**: Initial meeting/Kickoff Held: 2/21/2024
- [x] **PILOT**: Schedule a pilot session with CAIA a11ys prior to research sessions (**recommended**) - 2 audits completed instead (w/o 7/15 has conflicts) - PILOT scheduled for Monday, 7/22. `COMPLETED`
- [x] **CONVO GUIDE**: Provide Conversation Guide for review by CAIA a11ys (**optional**) `7/10/2024`
- [x] **RESEARCH PLAN** Provide Research Plan in supporting artifacts section of this ticket. `7/10/2024`
- [x] **CODEPEN PROTOTYPE:** Provide prototype in CodePen to CAIA A11ys via this ticket in the supporting artifacts section for review prior to research #76766
- [x] **Staging Prototype** for new audit
- [x] **DATES NEEDED** See the table in the ticket above. Please provide date range and slots for AT sessions being planned. 7/22 range given on 7/3/2024. **UPDATE as of 7/10/2024**: Research will be 7/24-8/1/2024.
- [x] **INVITES:** Forward invites from Perigean to CAIA A11ys (Sara or Naomi)
- [x] **ASSISTIVE TECH. INFO NEEDED:** Please provide the AT the users will be utilizing during the research sessions in the table in the ticket above. `Screen Magnification` and `Screen Readers (Type Needed)` [Google Sheet Sign Ups](https://docs.google.com/spreadsheets/d/1nrqw-iekbkWM2oDwBPvaFqo76tOHZJNn55RTJQviixQ/edit?gid=0#gid=0)
```

```[tasklist]
### A11Y Tasks
- [x] **RESEARCH INTAKE TICKET** processed 2/21/2024
- [x] **MEETING:** Initial meeting/Kickoff Held: 2/21/2024
- [x] **HOLD** Broad calendar hold for 3/13 - 3/23 for research
- [x] **RECEIVE PROTOTYPE** `After 3/13/2024` RCVD 3/22/2024
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/76766
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/83767
- [x] Audit Staging Prototype @coforma-jamie (July 2024)
- [x] **REVIEW** Conversation Guide, if provided and requested (**optional**) - `Pending info. from Team`
- [x] **PILOT SESSION(S) SCHEDULE** Pilot session(s) `COMPLETED - 7/22/2024` with CAIA A11YS - 2 audits done
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/76779
- [x] **MULTIPLE STUDIES** - Noted in ticket that the Week of 4/8 has multiple studies.
- [x] Ticket updates to reflect change in timeline 4/11/2024 (ss)
- [x] **CALENDAR HOLDS** Update A11y [CAIA Capacity Calendar with holds for user research sessions with AT, when dates become available.`BROAD HOLD AS OF 2/21/2024` Holds adjusted on 3/27/2024 with new dates. `Holds Removed on 3/29/2024` ~Study now running in May~ Holds updated 5/22/2024 study will be post-launch (June 10), and will likely take place in July. (Updated on 6/26/2024) (Updated on 7/10/2024) - UPDATED 7/15/2024 with 7/22-8/1/2024.
- [x] **REMOVE CALENDAR HOLDS*
- [x] **RESEARCH NOTES** Create [CAIA notes document](https://docs.google.com/document/d/1ax0pQP8agGunVEGHd5zDMFrraRXkw_evEKjRf-rx-ho/edit) - CAIA A11Ys to update the CAIA notes document during the sessions.
- [x] **DIVVY SUPPORT** for user research session support with CAIA A11ys - based on availability and technology available to support (Table to be added to this ticket, above, with AT session dates and times, so that available a11ys can sign up.)
- [x] **REVIEW** Research Folder and Assets `Pending info. from Team` - research plan added to supporting artifacts by Sara on 7/10/2024.
- [ ] **PARTICIPATE IN RESEARCH** **Date Span:**`7/24/2024` and `8/1/2024` `RCVD invites from Perigean`
- [ ] **SYNC:** Connect with CAIA A11ys on research findings (meeting)
- [ ] **Create/update the CAIA A11y Research Deliverable** This is dependent on the number of study participants CAIA supports. If minimal, A11Ys may share feedback only in the feedback Mural or this ticket.
- [ ] **Share the completed deliverable** with the project team via Slack: **Primary Team Slack:** [benefits-contention-classification](https://join.slack.com/share/enQtNjYwMDExOTQyMDc1Ny1iOGNlYTE4ZjY4OGM2YmUzOWE3YmY3MTMwMzA4MzRkMzQyNWVjMzE3NDQ0ODk4NDMzYmJhNjNmNGRiN2FjM2Vj) and this ticket
- [x] Research tracker updated to reflect new sessions scheduled, in lieu of cancled sessions (calendar validated; table in ticket updated) - 7/26/2024
```

**Comment by sara-amanda** [comment]
@sudeeptibh @coforma-terry @strelichl 

Please find this research ticket, as promised. 

- To condense the ticket, I have collapsed sections, but you can toggle them open to view the info. 
- **There are two task lists in this ticket:** one for CAIA a11ys and one for your team, to outline next steps. 

Let us know if you have any questions.

**Comment by coforma-jamie** [comment]
**Update:**
- the team has a research plan ready to go, and will share it soon
- the conversation guide and prototype are still in progress; planning to finish those within this sprint
- hoping to run usability tests April 10 - April 23
- ideally, we'd do a couple of pilots (mobile and desktop SR) before their anticipated start date of April 10

cc @sara-amanda @sudeeptibh

**Comment by sara-amanda** [comment]
## Research Study Dates
### Multiple Studies
- There are currently two other studies planned for the week of 4/8/2024. 
- The conflicts exist, specifically, on these dates:
    - 4/10/2024
    - 4/11/2024
    - 4/12/2014
- CAIA will attempt to provide coverage; however, coverage may be limited, due to the multiple studies taking place that week.
### Dates with No Conflicts
As of 3/15/2024, there are currently no CAIA coverage conflicts for:
- The week of 4/15/2024
-  The week of 4/22/2024

cc: @coforma-jamie @coforma-terry @sudeeptibh

**Comment by sudeeptibh** [comment]
added research plan to the supporting artifacts section, thanks!

**Comment by sudeeptibh** [comment]
Just added the prototype for testing, thank you! Our timeline is still looking like testing will between April 4th - 12th. We know you have limited capacity during that time and will keep that in mind. We cannot move to April 15th week due to teammates OOO.

**Comment by coforma-jamie** [comment]
Based on your team's usability testing changes as outlined on [Slack](https://dsva.slack.com/archives/C04AZ8T7XN1/p1711652894619389), your AT research testing timeline is likely going to be _after_ the week of April 15, is that correct? Keep us posted @sudeeptibh :)

**Comment by sudeeptibh** [comment]
@coforma-jamie just got stakeholder approval on the new plan - Our AT testing will definitely be after April 15th; currently, on the roadmap, it looks like it will be towards the end of May. We'll follow up once we have a better sense of the timeline. Thank you!

**Comment by coforma-jamie** [comment]
Gotcha! For now, I'm removing our calendar holds these sessions, until we have a better sense of the timeline, @sara-amanda :)

**Comment by coforma-terry** [comment]
Thank you for the heads-up @sudeeptibh

**Comment by sara-amanda** [comment]
## Timeline Shift
Research changing to July 2024, after launch. Launch likely around 6/10, per [Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1688579897099/a7d9ccbd622e4983e07bfc188a388c5f2926844f?wid=0-1690909648009&sender=u9e99e829c39911c821b39988).
- [x] Ticket title, overview summary, body and task list updated to reflect timeline shift from May 2024 to July 2024. 
- [x] Pilot ticket will be updated similarly, based on [5/22/2024 intake comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/75567#issuecomment-2123366972).  
- [x] Updating research capacity tracker. 
- [x] @coforma-jamie and @coforma-terry Holds have been re-placed on the CAIA Capacity Calendar, and can be updated when we have a better idea on timing. 
- [x] Added limited capacity note to this ticket (also in calendar) due to PTO during this timeframe.
- [ ] @coforma-jamie is going to perform a second audit in Staging (link needed), since there have been a lot of changes since the Codepen audit Jamie ran. This will be done prior to launch. 
- [ ] Notes doc will need to be updated when we have official dates.

**Comment by sara-amanda** [comment]
## CAIA Support Update

> [!NOTE]
> - [Cross-Posting (original reply in Pilot Ticket)](https://github.com/department-of-veterans-affairs/va.gov-team/issues/76779#issuecomment-2220630647)
> - [Thank you for the update!](https://github.com/department-of-veterans-affairs/va.gov-team/issues/76779#issuecomment-2207135062) @sudeeptibh 

### Pilot
- Are you still wanting to try for a pilot session with AT, prior to your research starting on 7/22, since we did the two audits for you? (See below section on Previous Audits Completed)
    - I am only mentioning this because the week of the 15th we do have limited capacity and two other research sessions going at that time. 

### Previous Audits Completed
- Previously, @coforma-jamie completed an audit of the prototype in CodePen [ticket 76766](https://github.com/department-of-veterans-affairs/va.gov-team/issues/76766). 
- Additionally, @coforma-jamie completed an audit of the prototype in Staging [ticket 83767](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83767)
- **Confirming**: Is this the URL that will be used in the testing sessions? 
    - URL: https://staging.va.gov/disability/file-disability-claim-form-21-526ez/new-disabilities-revised/add
User: Any user who can file a disability claim can get to this page for adding new disabilities. Allan Butler, Karl Howard, or Johnnie L. Weaver have worked fine for us.

### Number of Sessions
- **Confirming**: How many sessions are you looking to have covered? 
    - It looks like you will be needing support for two sessions, based on the research plan? 
    - I have updated our research outlook tracking with the two sessions for now. 
    - Just let us know when you have the dates/times and AT information available from Perigean. 

> At least 2 but no more than 3 Veterans who use assistive technology (AT) such as screen readers (AT/reader) or magnifiers (AT/magnifier)

## Capacity Update

We are currently experiencing limited capacity; however, your testing the week of 7/22, does not appear to have any conflict at this time for any current scheduled testing or PTO. 

cc: @coforma-jamie @EvanAtCoforma @SarahKay8 @NaomiPMC @artsymartha68

**Comment by sudeeptibh** [comment]
Thank you for this update! We are still considering the timeline, I posted a question to our slack for Jamie to respond to but did not post here. While Jamie is OOO - can someone else provide an informed opinion if our product is ready to test with AT users?

**Comment by sudeeptibh** [comment]
Note, in the audit CAIA did previously for our page in staging. Issues #8, 10, and 11 are out of scope and are not related to our page, the conditions page

**Comment by sudeeptibh** [comment]
- We would like to pilot on 7/22, I've put time on Jamie's calendar 
- The research plan you referenced is for the original ask, but this is for dedicated usability testing for AT users only. We are looking to complete 8 sessions between 7/22 - 8/1. Does this timing still work for you all? [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/research/CC-Team-Research/202403%20Improved%20Autosuggest/researchplan-assistedtech.md)

**Comment by sudeeptibh** [comment]
Tagging my co-workers @eheintzelman and @yurenanava for coverage on this while I'm OOO July 15 - 19.

**Comment by sara-amanda** [comment]
Thank you @sudeeptibh ! 

Yes, that timeframe works for us. The week of 7/29 is the most clear on our calendar, but as of right now, we only have holds for the previous week on your dates. I will get our calendar, ticket and research tracker updated to reflect your dates. 

cc: @eheintzelman @yurenanava @NaomiPMC @coforma-jamie

**Comment by eheintzelman** [comment]
@sara-amanda Perigean has scheduled 7 of 8 interviews. I don't have the full information on type of tech for each of them yet, but am going to go ahead and send you those invites.

**Comment by eheintzelman** [comment]
I updated the sign-up sheet for type of tech. Recruitment for 1 participant is still pending.

**Comment by sara-amanda** [comment]
[Cross-linking pilot feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/76779#issuecomment-2243849803)

**Comment by sudeeptibh** [comment]
Recruitment is done, there's two open slots for CAIA folks. Thanks y'all! https://docs.google.com/spreadsheets/d/1nrqw-iekbkWM2oDwBPvaFqo76tOHZJNn55RTJQviixQ/edit?gid=0#gid=0

**Comment by sara-amanda** [comment]
> Recruitment is done, there's two open slots for CAIA folks. Thanks y'all! https://docs.google.com/spreadsheets/d/1nrqw-iekbkWM2oDwBPvaFqo76tOHZJNn55RTJQviixQ/edit?gid=0#gid=0

Can you forward me the new invite @sudeeptibh - that looks like the only one I am missing. Thanks so much!

**Comment by sara-amanda** [comment]
> > Recruitment is done, there's two open slots for CAIA folks. Thanks y'all! https://docs.google.com/spreadsheets/d/1nrqw-iekbkWM2oDwBPvaFqo76tOHZJNn55RTJQviixQ/edit?gid=0#gid=0
> 
> Can you forward me the new invite @sudeeptibh - that looks like the only one I am missing. Thanks so much!

@sudeeptibh We are all set for your sessions, as of right now, except one at the moment. The spreadsheet and this ticket has been updated. Thanks!

**Comment by sudeeptibh** [comment]
We are continuing to re-recuit as we've had no-shows or not qualified participants. Just added two more slots next week to the roster. https://docs.google.com/spreadsheets/d/1nrqw-iekbkWM2oDwBPvaFqo76tOHZJNn55RTJQviixQ/edit?gid=0#gid=0

**Comment by sara-amanda** [comment]
> We are continuing to re-recuit as we've had no-shows or not qualified participants. Just added two more slots next week to the roster. https://docs.google.com/spreadsheets/d/1nrqw-iekbkWM2oDwBPvaFqo76tOHZJNn55RTJQviixQ/edit?gid=0#gid=0

@sudeeptibh we are all set to cover your sessions. All sessions now have an accessibility specialist. I hope you have better luck with the rescheduled sessions. The spreadsheet and this ticket has been updated. Thanks!

**Comment by sara-amanda** [comment]
## CAIA A11Y Initial Findings

@sudeeptibh [Cross-posting from Slack 7/30/2024](https://dsva.slack.com/archives/C07E3RQETC1/p1722370969959969)

### Vertical Bar

- **Issue Description:** The "vertical bar" decorative icon is not hidden to the user. Blind and visually impaired users may find this to be disruptive. Decorative icons should be hidden to the user.
- **Environment** **Tested**: Staging
- **Device Tested**: iOS Mobile
- **AT used:** VoiceOVer
- **Recommendation**: Remove the element altogether or use aria-hidden.

### Focus

- **Issue Description**: There is inconsistent focus behavior upon loading the page. Behavior should remain consistent to inform the user of the page's intended structure and contents. Blind and visually impaired users may find it difficult to navigate the page.
- **Environment Tested**: Staging
- **Device Tested**: iOS Mobile
- **AT used**: VoiceOver

### Condition Announcements

- **Issue Description**: Upon selection of a condition from the dropdown, the selected choice is not announced to the user. Blind and visually impaired users will have difficulty understanding that they have selected an item from the dropdown. Upon selection of an item, the selected item should be announced to the user and focus should remain in place.
- **Environment Tested**: Staging
- **Device Tested**: iOS Mobile
- **AT used**: VoiceOver

cc: @mutiaadhocteam

**Comment by coforma-jamie** [comment]
### Final tally

-  7 complete sessions, 3 no-shows, 1 disqualified
-  3 screen magnification, 1 JAWS, 1 TalkBack, 2 VoiceOver

### Assistive technology takeaways

- 	P1 only uses their AT when necessary, since it can be cumbersome.
- 	P3 confused “Zoom” with “ZoomText” in the screener, and didn’t qualify. We may not want to mention ZoomText in the screener moving forward.
- 	iOS users had issues with the focus of the conditions dropdown that didn’t allow the P to easily understand /select the options (P5, P7); they encountered a vertical bar on the page. (See above comment for more information)
- 	2 out of 3 screen magnifier users experienced no issues using their AT. 
      - 1 participant, P6, used a physical magnifying glass, and felt that the page was similar to others on VA.gov in that they’re “not meant for low vision folks.” Due to very low vision, they would focus on typing rather than looking at the options. They want all pages to have a dictation option and is open to using AI tools to completing tasks.
- 	P8 suggested that the error message explain what the error _is_ - “This field is blank” or similar - so people know what they need to do to fix it.
- 	All in all, besides the iOS issue, the form worked as expected - and well!

[Read CAIA’s notes in full](https://docs.google.com/document/d/1ax0pQP8agGunVEGHd5zDMFrraRXkw_evEKjRf-rx-ho/edit?usp=sharing)
