### ISSUE TITLE
Review existing journey map of 526EZ steps for VSRs with Shannon Ford and VBA and refine for Pension Benefits

### ISSUE THREAD

**Issue by Allexelaw** [department-of-veterans-affairs/va.gov-team#76708]
Meet with Shannon Ford to walk through VSR journey map and remove extraneous information.  Coordinate a meeting w/ VBA Briana Mullen and Daniela Gifford

**Comment by djones2113** [comment]
Met with Shannon on 2/21 to review the journey map. @Allexelaw made updates to the journey map based on that conversation. We have a conversation scheduled with folks from VBA on Friday, 3/8 to get their input on the journey map
