### ISSUE TITLE
document maintenance windows process for COE

### ISSUE THREAD

**Issue by sortizsh** [department-of-veterans-affairs/va.gov-team#76718]
## Issue Description
the VA watch officer raised this incident: https://dsva.slack.com/archives/C06C2D2PJQZ/p1708528402149069 
it appears when COE was transitioned from Benefits Team 1 to B&C we may have lost some process around setting up maintenance windows for upstream downtimes. 

## tasks
- write/research the documented process to proactively enter maintenance windows for COE
- in pagerduty (you can also ask the platform support team for assistance doing this) this will ensure that your team has a documented process to proactively enter maintenance windows
- this will suppress alerts and let the watch officer know that the downtime was expected and we don't need to create an incident next time

**Comment by sortizsh** [comment]
assign to Micah in next sprint

**Comment by tblackwe** [comment]
This documentation describes the process
https://app.zenhub.com/workspaces/benefits-non-disability-645913c7d909c20011380ae8/issues/gh/department-of-veterans-affairs/va.gov-team/60243

**Comment by tblackwe** [comment]
I am requesting a PagerDuty signin
