### ISSUE TITLE
Present research findings to OCTO and OCC/Wednesday stakeholders

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#76717]
### User story

As a Cartographers team member, I want to present our secondary nav research findings at the Wed meeting, so that stakeholders and other teams can probe and then leverage our insights.

### Notes
- Adapt existing findings deck

Possible tasks:
- [x] schedule OCTO readout – 1 hr [Monday, March 4 at 2pm ET]
- [x] schedule OCC readout - 30 mins [Wednesday, March 6 at 4pm ET]
- [x] iterate deck with Kaitlin
- [x] do octo mtg
- [x] iterate based on octo feedback
- [x] hide slides for OCC

## Acceptance criteria

- Presented to OCTO stakeholders
- Drafted presentation for OCC/Wed audience
- Presented to Wed design meeting

**Comment by fmccaf1** [comment]
Scheduled for April 8

**Comment by sterkenburgsara** [comment]
OCTO readout scheduled for Monday, March 4 at 2pm ET.

**Comment by sterkenburgsara** [comment]
@fmccaf1 do you mean the Monday design/research sync is on April 8? I thought we were planning to do OCC readout next Wednesday, March 6th?

**Comment by sterkenburgsara** [comment]
**Update**: this ticket has a/c that is scheduled for the next sprint & it will need to roll over.
