### ISSUE TITLE
Design | EDU CH33 Changes | Create mock-ups for EDU DD downtime

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#76713]
## Background 
- Comp and pen remains unchanged 
- we should have some sort of alert state > this is a thing that isn't working for maybe a while 

## AC 
- [x] we've got a new mock for the downtime period

## Figma file 
- [mocks](https://www.figma.com/file/CUR39JNnF2CS8SidGiWmYG/Profile---Direct-Deposit?type=design&node-id=234-4877&mode=design&t=Be5bp5eghK8M6GB9-0)

**Comment by andaleliz** [comment]
@mtcA6 based on [this Slack thread](https://dsva.slack.com/archives/C06JV0KHZNF/p1708618527504369), it sounds like this is a realistic scenario, and no longer just "worse case". Is that your understanding too? If so, I'll prioritize this over the other ticket.

**Comment by mtcA6** [comment]
Yep please prioritize, we're likely to be offline **_at least_** from April 20-May15 but possibly longer.

**Comment by andaleliz** [comment]
@mtcA6 will we be able to show bank information to folks during this downtime, and they just can't edit it? Or will we not be able to even show a read-only state of their edu DD information?

**Comment by mtcA6** [comment]
Unfortunately, not even read state.

**Comment by andaleliz** [comment]
I shared t[his mock-up](https://www.figma.com/file/CUR39JNnF2CS8SidGiWmYG/Profile---Direct-Deposit?type=design&node-id=234-4877&mode=design&t=8rwdFkPdybOJi7g1-11) with Samara, and she agreed on the overall approach. I'll take this to content office hours later in the week to get feedback on that aspect, and then create the desktop version once that's done.

**Comment by andaleliz** [comment]
Also, few outstanding questions that would be helpful to get answers to, that ultimately inform the second part of the alert:
- will people be able to switch from paper checks to DD during the downtime by calling the call center?
- If not, how can people switch to DD?
- will people be able to set up DD for edu payments if they have never received checks before (new benefit)?
- What phone number can people call to manage their edu payments during the downtime (the main 800 number or the edu call center specifically)?

**Comment by mtcA6** [comment]
> - will people be able to switch from paper checks to DD during the downtime by calling the call center?
> - If not, how can people switch to DD?

[ANS] I believe they could opt for paper checks, but if they switch to receive paper checks my understanding is this would change the way they receive payments for ch33 and, if they have them, C&P benefits going forward. Regardless of what they choose there can only be one set of payment instructions in the CorpDB database. 

> Sarah H our VBA stakeholder (director of financial management business solutions) said: 
>technically yes, they can opt for Check payments, but they will not be able to do that through VA.gov, they would have to call the call center and they would be in violation of Title31, Part 208 - which is the EFT mandate. We cannot stop/suspend payment if they refuse to comply with DD/EFT but we strongly encourage DD/EFT. 

I would stay clear of mentioning anything related to paper checks. 

---

> - will people be able to set up DD for edu payments if they have never received checks before (new benefit)?

[ANS] Currently, edu benefits in the profile are EDIT ONLY. This means, today, Ch33 direct deposit is setup when a veteran applies for the benefit (form 1990), this shouldn't change, the only thing that is changing is they'll not, for the window between 4/20-5/15, be able to see/update their bank information online. 

---

>  - What phone number can people call to manage their edu payments during the downtime (the main 800 number or the edu call center specifically)?

[ANS] I'm not clear on what the call center folks wanted. Currently comms are directing veterans to the national call center and then forwarding the information on to the education call center. It sounded like, from a call @Samara-Strauss and I were on yesterday that they were okay with directing calls to the national call center until the downtime period but when pressed if we should direct veterans to the ECC there was hesitation. I think it is fine to mock this up with the national call center and as we get closer to the date we can confirm which number we should be using.

**Comment by mtcA6** [comment]
@andaleliz for the last item in my prior comment, Chante had the same impression that they were hesitant to direct people to the ECC. So sticking w/the national number should be okay for now.

**Comment by mtcA6** [comment]
Adding here, Liz and I chatted about expanding the alert content to include a link to the GI bill page, similar to how it operates if the system believe a veteran doesn't have access. (screenshot for context)

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/d76b41e8-afcc-4c83-b231-8e1492cb3216)

During the downtime, since we won't be able to tell if a veteran has edu benefits or not, displaying this alert without also including the link to the GI bill eligibility page would reduce the current functionality we offer today. 

Liz is going to check in with the content folks.

**Comment by Samara-Strauss** [comment]
> During the downtime, since we won't be able to tell if a veteran has edu benefits or not, displaying this alert without also including the link to the GI bill eligibility page would further reduce the current functionality we offer today.

TBH I don't think we need the link during downtime, but that is just an opinion. If we include it, it should NOT be in the alert message, as the GI bill eligibility link has nothing to do with the downtime alert.

**Comment by andaleliz** [comment]
@mtcA6 sorry, I forgot this was open - yes we need to roll 3 pts over since I still need to get the content reviewed. Thanks for double checking!

**Comment by andaleliz** [comment]
@mtcA6 this is approved by CAIA and ready for FE. [Alerts are here](https://www.figma.com/file/CUR39JNnF2CS8SidGiWmYG/Profile---Direct-Deposit?type=design&node-id=234-4011&mode=design&t=HUMmF47HPAoJu5rL-11)
