### ISSUE TITLE
Offboarding of Emma Pinkerton

### ISSUE THREAD

**Issue by dkbergh** [department-of-veterans-affairs/va.gov-team#76710]
Please remove Emma Pinkerton from the VA Github and Slack instances. Her last day with the CDS Platform team is today, 2/21/24.

- email: emma.pinkerton@thoughtworks.com

-Company: Thoughtworks

- GitHub username: emspinkerton

-Slack username: Emma Pinkerton

- COR: Cecilia Lee

- PM: December Bergh (december.bergh@va.gov)

## Acceptance Criteria

_The following steps are performed by the **Platform Support** team. Detailed instructions found [here](https://vfs.atlassian.net/wiki/spaces/OT/pages/2097545323/Offboard+Team+Member)_

 - [x] Requested removal from DSVA Slack (if applicable. Search for them in Slack)
   > A comment on this ticket prefixed with `/request` (i.e. `/request FirstName LastName`) will send a message to the Slack admins automatically!
 - [x] Requested removal from Confluence (if applicable. Check [confluence members](https://vfs.atlassian.net/wiki/people/search?q=))
 - [x] Remove from [Platform Atlas](https://www.va.gov/atlas/product_directory/team_members) (if applicable)
 - [x] SOCKS access removed (if applicable. Search their email in [config.yml](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/global/config.yml))
   > Use the [Remove SOCKS and AWS access Github Workflow](https://github.com/department-of-veterans-affairs/devops/actions/workflows/offboarding.yml). You'll need the user's email address associated with their public key (found in `config.yml`). Merge the PR.
 - [x] AWS access removed (if applicable. Search their name in [AWS IAM](https://console.amazonaws-us-gov.com/iamv2/home#/home))
   > Use the same [SOCKS and AWS access Workflow](https://github.com/department-of-veterans-affairs/devops/actions/workflows/offboarding.yml) to remove user's entry from [iam_users.tf](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf). You'll need the user's AWS username (typically `First.Last`). Merge the PR and apply Terraform.
 - [x] User removed from the VA GitHub Org (if applicable. Check [department-of-veterans-affairs/people](https://github.com/orgs/department-of-veterans-affairs/people))
   > Fill out request found [here](https://github.com/department-of-veterans-affairs/github-user-requests/issues/new?assignees=&labels=remove-user&template=user-remove.yml&title=Remove+User+from+Org%3A+%5Busername%5D).
 - [x] Pagerduty access removed (if applicable. Check [pd users](https://dsva.pagerduty.com/users-new))
 - [x] [Okta account](https://vfs.atlassian.net/wiki/spaces/OT/pages/2532508159/Offboarding+users+from+Okta) disabled
 - [x] Datadog (if applicable. Check [Datadog users](https://vagov.ddog-gov.com/organization-settings/users))
    - [x] Disable in Datadog UI (must be done by a datadog admin)
    - [x] [Submit an ECC request](https://vfs.atlassian.net/wiki/spaces/OT/pages/2526282894/Offboarding+Users+from+Datadog) (Only necessary if they were in the Datadog UI)
 - [x] Sentry access removed (if applicable. Check [Sentry members](http://sentry.vfs.va.gov/settings/vsp/members/))
 - [x] TestRail access removed (if applicable, Check [TestRail User List](https://dsvavsp.testrail.io/index.php?/admin/users/overview))
 - [x] Google analytics and Domo access removed (if applicable. Make sure the `analytics-insights` label is on this Issue)
 - [x] Bot (`va-bot`, `va-vfs-bot`, and `va-vsp-bot`) user GitHub account(s) YubiKey(s) removed
   > This is rare. See [documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1908932642/Remove+YubiKeys+of+Offboarded+Operations+Team+Members) for current users and removal process.
 - [x] Sketch editor access removed (if applicable. Check [Sketch settings](https://www.sketch.com/workspace/c99d3e96-7c23-4210-b173-92a2b73a8788/settings/people))
 - [x] Removed from Monday Design Meeting invite

 CC: @department-of-veterans-affairs/vsp-operations ,  @department-of-veterans-affairs/platform-analytics-insights-team , @department-of-veterans-affairs/confluence-admins, @department-of-veterans-affairs/platform-design

**Comment by dkbergh** [comment]
Will try new issue since this was added to archived project.

**Comment by rmtolmach** [comment]
@dkbergh are you seeing this message? 
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/10993987/f4fd6d16-140b-4412-b5e5-51797b4b7fe4)
Don't worry about that. You can re-open this and Platform support will take care of it.

**Comment by dkbergh** [comment]
Oh excellent - yes, that was why I was thinking this ticket might not be picked up. I will indeed reopen. Thanks @rmtolmach

**Comment by rmtolmach** [comment]
No datadog.

**Comment by naomimarcussen** [comment]
No editor access in Figma
Requested to remove from Monday design meeting invite

**Comment by stoiven** [comment]
/request Emma Pinkerton
No confluence
No Atlas
No SOCKS
No AWS
No PagerDuty
No Sentry
No Yubikey

**Comment by CoryTrimmUSDS** [comment]
Removed from DSVA Slack.

**Comment by Blivaditis** [comment]
No GA
No Domo

**Comment by hgbarreto** [comment]
Request for OKTA removal submitted - DOTSD-45024
All tasks complete - Closing
