### ISSUE TITLE
FE | EDU CH33 Changes | Add Feature Flag - doomsday scenario

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#76725]
Create a feature toggle that will trigger an alert to be shown in the education benefits section of the direct deposit page. This serves as a fallback so that if we cannot support edu benefits in a single form, then we will show this alert and notify users that the edu direct deposit updates are unavailable.

Current figma design for this alert: https://www.figma.com/file/CUR39JNnF2CS8SidGiWmYG/Profile---Direct-Deposit?type=design&node-id=234-8012&mode=design&t=gcVSGX4dkEz1lJrX-4

- [x] toggle created with name `profile_show_direct_deposit_single_form_edu_downtime` in vets-website
- [ ] vets-api toggle added with same name

**Comment by adamwhitlock1** [comment]
Toggle is ready here:
https://staging-api.va.gov/flipper/features/profile_show_direct_deposit_single_form_edu_downtime

We can close this out.
