### ISSUE TITLE
Remove inline styling + id selectors from Find a Rep

### ISSUE THREAD

**Issue by cosu419** [department-of-veterans-affairs/va.gov-team#76732]
## Background
We generally want to avoid inline styles and use vads classes (wherever possible) + custom CSS classes where appropriate. Per the Platform docs, id selectors should also be avoided. 

## Acceptance Criteria
- [ ] No inline styling
- [ ] Id selectors are class selectors

**Comment by oddball-lindsay** [comment]
This came up in a PR review, awaiting changes in Staging before closing
