### ISSUE TITLE
CF: Cross-Browser Testing

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#7673]
As a MVP development team, I need to conduct cross browser testing as part of the pre-launch activities in support of the Build and Test phase.

Assumptions:
1. Requirements for cross browser testing are located in GitHub: https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/DeveloperDocs/testing/cross-browser-manual-testing.md
2. The final/complete build has been deployed to staging
3. All parts of the form are present and working correctly
4. Tester has access to most common browsers including: Chrome, Safari, IE 11, Firefox. This could be using an external tool like Browserstack or a Virtual Machine
5. Tester can access mobile simulation and desktop formats
6. End to End test script exists here: [INSERT LINKS]

Acceptance Criteria:
1. The update to caution flags within the comparison tool have been tested and run through from beginning to end with no errors or problems on most common browsers and formats.

Tasks
- [ ] Ensure that all changes are deployed to Staging before being testing
- [x] Test form end to end on Chrome
- [x] Test form end to end on Firefox
- [x] Test form end to end on Safari
- [x] Test form end to end on IE 11
- [x] Test form end to end on Edge
- [x] Test form end to end on Mobile
- [x] Test form using google's responsive features.

**Comment by delli-gatti-michael** [comment]
Tested by Test Case:
https://dsvavsp.testrail.io/index.php?/cases/view/462

No browser-specific issues found
