### ISSUE TITLE
Raw data shown but no 527EZ file, for 3 different submissions

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#76741]
## Issue Description

**Based on recent Json file shared with VBA:**

**Message from VBA:**

**Submission 1**
_looking at line 5255, it appears that there is raw data for a 527EZ
but no 527EZ in the file
thats a problem if its not uploading a 527EZ and there is no 180/120_

**Submission 2**
_line 5090, another one with raw data and no 527EZ in the file
and no 180_
- This one was not there when they first looked, but it appears both the EP 180 and 527 are now showing

**Submission 3**
_No EP and no 527EZ for line 4349 as well_

**Other helpful context on what an EP is...**
_The end product (EP) system is the primary workload monitoring and management tool for the Veterans Service Center (VSC), pension management center (PMC), Benefit Eligibility Support Team (BEST) sites, and fiduciary hubs (hubs)._

_- Correct use of the EP system facilitates proper control of pending workloads and appropriate work measurement credit._
_- Correct work measurement is essential to substantiate proper staffing requirements and determine productive capacity._ 

## Acceptance Criteria
- Attempt to replicate this issue or investigate from raw data provided, troubleshoot as needed

**Comment by mjknight50** [comment]
This appears to just be a timing and communication issue.  I've started a thread here:

https://dsva.slack.com/archives/CDRSFMWFL/p1708549724587899?thread_ts=1708549650.018519&cid=CDRSFMWFL

**Comment by mjknight50** [comment]
All three submissions came through, so this is just a timing issue.

**Comment by vbellissimo** [comment]
Good to now. Thank you for sharing this @mjknight50.

cc @buddhima-coforma you may find this interesting.

**Comment by vbellissimo** [comment]
@mjknight50 nevermind. I think I understand now?

The diagram says it goes from Lighthouse Benefits Intake API and goes to EMMS API, which is the Benefits Intake API.

If I'm misunderstanding, please let me know.
