### ISSUE TITLE
Midpoint Review - Design Feedback - Modernized Check-in, eCheck-in, Mileage-only Travel Claim Submission

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#76753]
## Next Steps for the VFS team

- [x] **Assign** this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [x] **Comment** on this ticket:
  - If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members`.
- [x] **Close the ticket** when all feedback has been addressed.

## Thoughts/questions

- Consider adding some content around the cancel screen letting the user know that they selected cancel and that is why their claim is not being submitted.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- [x] Must: There are 2 green action links on the intro page (File a milage only claim and Learn how to file other claims). Per [our guidance](https://design.va.gov/components/link/action#when-to-use-an-action-link), you should use only one primary Action link per page. You could change one to a secondary action link.
- [ ] Must: Review your additional info components for Beneficiary travel agreement and Travel reimbursement eligibility. Per [our guidance](https://design.va.gov/components/link/action#when-to-use-an-action-link) you want to avoid too much content: Only include critical information inside this component. Collaborate with a member of CAIA to edit content and explore alternatives.

## Governance team actions
- [x] Format feedback as individual tasks (check boxes)
- [x] Assign this ticket to the VFS team member that opened the Slack request
- [x] Add the VFS team product label
- [x] Add the VFS team the feature label (if applicable)
- [x] Add the touchpoint labels
- [x] Add the practice area labels
- [x] Add the Collaboration Cycle initiative milestone
- [x] Add the Collaboration Cycle initiative epic

**Comment by benbrasso-agile6** [comment]
- Changed one action link to secondary - [Intro page](https://www.figma.com/file/pnR05o7NPJDS0KFUSQ0eE3/Check-in-%7C-Check-in?type=design&node-id=642-3804&mode=design&t=de8u6oA4BhQcFXDG-4)
- Eligibility reqs and BT agreement were required/requested by the Veteran Transportation Program. We could look to switch those to links instead of add info components, but I don't think VTP will allow us to shorten or change the reqs because those are the reqs. @allison0034 think we should go ahead and change them to links instead?

**Comment by benbrasso-agile6** [comment]
I pinged Laura, to chat it through with her
