### ISSUE TITLE
Medical condition is "true" but blank in PDF

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#76752]
## Issue Description

**Based on recent Json raw data provided to the business for cross referencing submissions...**

**Message from VBA:**
_In line 4244, true for medical condition, and PDF blank_

## Acceptance Criteria
- Attempt to replicate this issue or investigate from raw data provided, troubleshoot as needed

**Comment by sortizsh** [comment]
@vbellissimo can you please review this and see if it is working as intended or if addtl work needs to be done?

**Comment by vbellissimo** [comment]
@scottsdevelopment , regardless of the qualifying questions before this, the business stakeholders are saying that for this question on the web form...

<img width="704" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLytOQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d290350b84ca2a49c917f6c4e71362a9bdc11aed/Screenshot%202024-02-26%20at%202.20.03%E2%80%AFPM.png" alt="Screenshot 2024-02-26 at 2.20.03 PM.png" />

The json data shows as "true". Does "true" mean "yes"?

And if so, it's showing blank for 4B.

**Comment by vbellissimo** [comment]
@scottsdevelopment I think what my question is, then, why is the Json data showing "true" for 4B? or you not see this on your end?

**Comment by vbellissimo** [comment]
**Issue summary...**

What we're seeing is happening is that in this case, this person answered the following questions:

1. Are you over 65? - **Yes**
2. Have you been determined disabled by SSA? - **No**
3. Are you medically incapable of working - **Yes**

What we saw is that our web form should not have shown the third question to the veteran at all because, according to the PDF form, if they answer "yes" to either of the first two questions, they are allowed to skip the third question.

So in other words, our answer mapping to the PDF was following the business rules, but our web form's conditional logic is not.

**Next steps...** (@scottsdevelopment confirmed by the business today 2/29/24)

**If someone answers "Are you over 65?" as "yes", the online form should behave the following way:**

1. Are you over 65? - **Yes**
2. Have you been determined disabled by SSA? - **Hide this question (if yes to question 1)**
3. Are you medically incapable of working - **Hide this question (if yes to question 1)**

**Comment by vbellissimo** [comment]
@gmaciolek I also wanted to flag this to you, in case we need to update our logic flow diagram or any other design artifacts we have.

**Comment by aplatt-coforma** [comment]
Verified the workflow on the form.

I did add a comment in the mural diagram to update the flow. https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1703103128492/30dc0956f99482beffb457eb2ae884430cc2d3f4?sender=ua4b11671f027a66286586953
