### ISSUE TITLE
Access for Shaun Hubbard

### ISSUE THREAD

**Issue by shaunhubbard-va** [department-of-veterans-affairs/va.gov-team#7675]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   >  Crystal Moultrie
- Please provide your name.
   > Shaun Hubbard
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > ThoughtWorks, Developer, ThoughtWorks
- [if requesting SSH key authorization] What is the **public** SSH key? If you don't have a SSH Key or know how to find it [click here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#create-ssh-public-key) for instructions. (Example below)

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDSYcJGmAGGZzm1RXW0pWICMRpV4mySwYm/uKNOabhHSxrMQpv98aXxrmB0oZtcARfGkvedEDwk5faewAgMGr+c534zPL4DVlcjTC1GllozfHW10pdDH+r5tmPzNZPoJk/LX/ciSe8TTXxGRN0uRF2k3Rvp+tkCdbJWtZeW0t+fyr5XL8XJFx+GJynR0h6DgsFkSwudVFV3GYscEU5ZufS+6kYGR7wHm39T5+uXEhJQ3Lqz3FgN4+LFuSUbuEogIujkmdcruCW/9DtlsMfbsTfow+7E6sQH+mqGL1pL+kpNvGgNsm2t/a6Ul1viFFAYV5Ovwq7eQ4mOgokayuJkhDoiVSkM11T56K6b97cEGtvYBevnxEBVhUnaYMPQmW0bpIX7PV/JXkVpBkeHUjMCSRss4TM2N5J4dEvtdUmy49x4a8LJGAQRgdcL0R2BMXNLXaK18NSERGVIIIPN3F72vPrjMcgXBjcCNjxPD9YlX9iMnvM+j5PqBOaWe/8Bc0mTRumoNJgT3oZMW5OI2jgKpaVqJA/NRzCfjyKFLq6wp0iJd8WJoWyg30uytE+mqVrf/duieO0dJfS8S7VT1Gq+RA0mTM1NmlUc3qnFOWH/REos0fzSeSrvEgL1ebSwFPB4lYh6Doejj2dvtylD9qjDQ2F4ut+QBhGmNmTDb6U1EcXp0w== shaun@shauncodes.com
```

- [Grant AWS Console access?]
  > NO
  >  My PIV card has not yet been granted so I believe I am inelligible.

**Comment by tskinn** [comment]
@shaunhubbard-va you should have access now. Reach out in slack if you have issues.
