### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by AdamOye** [department-of-veterans-affairs/va.gov-team#76763]
### Name

Adam Oyenuga

### Email

adam.oyenuga@adhocteam.us

### Role

Product manager

### Team

Product forms team 

### Product Manager (PM) name

Tricia Baker

**Comment by naomimarcussen** [comment]
Hi! An invite has been sent to adam.oyenuga@adhocteam.us

**Comment by AdamOye** [comment]
thank you
