### ISSUE TITLE
Unable to report outdated information

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#76761]
## Expected vs. Actual
**Expected**: I can report outdated information for all reps returned in a search.

**Actual**: I receive an error when i try to report outdated information for reps returned in a search.  Best reproduced in an incognito window.

## Steps to Reproduce

1. Open an Incognito window
2. Select VSO
3. **Enter "10001" in the location**
4. Search radius is 50 miles
5. Name is blank
6. Search
7. Try to report outdated information for the reps -- error is returned

## Examples

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEI5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f849b1747136a2a20afca9093159bf4d1ff7e990/Screen%20Recording%202024-02-21%20at%203.11.33%E2%80%AFPM.mov)

**Comment by cosu419** [comment]
@holdenhinkle  I couldn't reproduce this bug - guessing it's connected to CSRF token experimentation from last week?

**Comment by oddball-lindsay** [comment]
ah-ha!  thanks for finding that reason, that makes total sense and I agree that this seems to be an edge case that is coming out in QA-specific scenarios.

let's go with option A for this ticket, and i'll create another ticket for Icebox for option B -- we can pull that work in at some later time if we start to feel that's needed.

**Comment by cosu419** [comment]
One more issue with Option B is that it violates user expectations about browsing incognito, namely that they're getting a "clean view" of a webpage (which isn't affected by their non-incognito interactions). 

I spoke with Holden who was also leaning towards Option A, but on the frontend. So if the response is an error caused by a duplicate IP, we keep that error but handle it as a success on the FE.

**Comment by oddball-lindsay** [comment]
Ok thanks for sharing!  Let's move forward with option A then and we can reassess at a later time if we need a different solution (could be option b or something else).
