### ISSUE TITLE
Spouse information page: update deprecated widgets and fields

### ISSUE THREAD

**Issue by gmaciolek** [department-of-veterans-affairs/va.gov-team#76768]
## Description
On the Spouse Information page `/household/spouse-info`, update the following deprecated widgets and fields with a v3 component equivalent. (Note that liveWithSpouse should not be updated because it includes a customization)

**Widgets**
<table>
  <tr>
   <td><strong>Field</strong>
   </td>
   <td><strong>Type</strong>
   </td>
   <td><strong>Replacement</strong>
   </td>
  </tr>
  <tr>
   <td>spouseVAFileNumber
   </td>
   <td>number
   </td>
   <td>numberPattern
   </td>
  </tr>
  <tr>
   <td>spouseDateOfBirth
   </td>
   <td>currentOrPastDateUI
   </td>
   <td>datePattern
   </td>
  </tr>
  <tr>
   <td>spouseSocialSecurityNumber
   </td>
   <td>ssn
   </td>
   <td>ssnPattern
   </td>
  </tr>
  <tr>
   <td>spouseIsVeteran
   </td>
   <td>yesNo
   </td>
   <td>yesNoPattern
   </td>
  </tr>
</table>

**Fields**
<table>
  <tr>
   <td><strong>Field</strong>
   </td>
   <td><strong>Type</strong>
   </td>
   <td><strong>Replacement</strong>
   </td>
  </tr>
  <tr>
   <td>spouseVAFileNumber
   </td>
   <td>number
   </td>
   <td>numberPattern
   </td>
  </tr>
</table>

## Acceptance Criteria
The widgets and fields listed in this ticket have been updated to the appropriate v3 component replacement

## Tasks
Front-end work

## Review
* Standard engineering review process 
* Design review of the page in staging to validate that it’s displaying correctly

## Resources
* [Component page in design.va.gov](https://design.va.gov/components/) with the USWDS v3 badge

**Comment by aplatt-coforma** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/76768?planning-poker) with Zenhub @ToddWebDev
