### ISSUE TITLE
 USWDS v3 upgrade: Ensure MHV landing page is not broken

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#76765]
### User story

As a Cartographers team member, I want to opt all landing page components into v3 "manually" ahead of the full deprecation and automatic cut-over, so that we can make sure that our page will continue to look and function right.

### Notes
- Upgrade is being done by DST in stages, from opt-in to opt-out to forced.
- list of components impacted by this work is in the side-bar of [Storybook](https://design.va.gov/storybook/?path=/story/about-introduction--page)
- QA approaches and tech debt:
  - AuthExpt [thread](https://dsva.slack.com/archives/C909ZG2BB/p1708551928344009?thread_ts=1708545089.694019&cid=C909ZG2BB) clarifies that tech debt will be left over (a `uswds` attribute in html)
  - If we merge opt-in code for the sake of QA-ing the landing page with v3, we will want to later remove it again
- Dates have been shifting (currently ~~4/19~~ 5/3 deprecation, with auto-opt-in 5/6) – need to monitor team of teams and slack for updated final deprecation date – @LynneJohnson224 @wesrowe 
- Threads from DST in vfs-change-announcements:
  - [original announcement](https://dsva.slack.com/archives/C03R5SBELQM/p1705503589174489)
  - [further reminder](https://dsva.slack.com/archives/C03R5SBELQM/p1706549819394489)

Possible tasks:
- [x] OPT OUT immediately, get PR into prod by Friday EOD
- [x] See if we have a v3 problem
- [x] Fix v3 problem

## Acceptance criteria

- Tested (in agreed-upon environment) whether v3 upgrade will break any aspects of landing page looks or functionality
- Got UX review of page with v3 components
- Got a11y review of page with v3 components
- Fixed any issues in production codebase
- Ticketed future removal of any code that will become tech debt after full deprecation of v1 (e.g., any `uswds` flags)

**Comment by jzucadi** [comment]
Components that do not have a 1:1 version in USWDS v3: 

1. va-telephone 
2. va-table 
3. va-table-row
4. va-loading-indicator
5. va-link, va-need-help
6. va-card

**Comment by jzucadi** [comment]
PR for opting out of `uswds`: https://github.com/department-of-veterans-affairs/vets-website/pull/28285

**Comment by jzucadi** [comment]
PR for opting out has been merged Mar 1, 2024

**Comment by jzucadi** [comment]
[PR for using USWDS ver 3 components ](https://github.com/department-of-veterans-affairs/vets-website/pull/28323)
