### ISSUE TITLE
Dependent children page: update deprecated widgets and fields

### ISSUE THREAD

**Issue by gmaciolek** [department-of-veterans-affairs/va.gov-team#76769]
## Description

On the Dependent children page `/household/dependents/add`, update the following deprecated widgets with the v3 component equivalent. 

**Widgets**

<table>
  <tr>
   <td><strong>Field</strong>
   </td>
   <td><strong>Type</strong>
   </td>
   <td><strong>Replacement</strong>
   </td>
  </tr>
  <tr>
   <td>fullName
   </td>
   <td>fullNameUI
   </td>
   <td>fullNamePattern
   </td>
  </tr>
  <tr>
   <td>childDateOfBirth
   </td>
   <td>date
   </td>
   <td>datePattern
   </td>
  </tr>
</table>

## Acceptance Criteria
The widgets listed in this ticket have been updated to the appropriate v3 component replacement

## Tasks
Front-end work

## Review
* Standard engineering review process 
* Design review of the page in staging to validate that it’s displaying correctly

## Resources
* [Component page in design.va.gov](https://design.va.gov/components/) with the USWDS v3 badge

**Comment by aplatt-coforma** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/76769?planning-poker) with Zenhub @ToddWebDev

**Comment by aplatt-coforma** [comment]
Demoed during daily
