### ISSUE TITLE
Marriage information page: Update deprecated widgets and fields

### ISSUE THREAD

**Issue by gmaciolek** [department-of-veterans-affairs/va.gov-team#76767]
## Description

On the Marriage Information page `/household/marriages/:index`, update deprecated widgets and fields with a v3 component equivalent.

**Widgets**
<table>
  <tr>
   <td><strong>Field</strong>
   </td>
   <td><strong>Type</strong>
   </td>
   <td><strong>Replacement</strong>
   </td>
  </tr>
  <tr>
   <td>dateOfSeparation
   </td>
   <td>date
   </td>
   <td>datePattern
   </td>
  </tr>
  <tr>
   <td>marriageType
   </td>
   <td>radio
   </td>
   <td>radioPattern
   </td>
  </tr>
  <tr>
   <td>reasonForSeparation
   </td>
   <td>radio
   </td>
   <td>radioPattern
   </td>
  </tr>
</table>

**Fields**

<table>
  <tr>
   <td><strong>Field</strong>
   </td>
   <td><strong>Type</strong>
   </td>
   <td><strong>Replacement</strong>
   </td>
  </tr>
  <tr>
   <td>locationOfMarriage
   </td>
   <td>string
   </td>
   <td>VaTextInputField
   </td>
  </tr>
  <tr>
   <td>locationOfSeparation
   </td>
   <td>string
   </td>
   <td>VaTextInputField
   </td>
  </tr>
  <tr>
   <td>otherExplanation
   </td>
   <td>string
   </td>
   <td>VaTextInputField
   </td>
  </tr>
</table>

## Acceptance Criteria

The widgets and fields listed in this ticket have been updated to the appropriate v3 component replacement

## Tasks

Front-end work

## Review

* Standard engineering review process 
* Design review of the page in staging to validate that it’s displaying correctly

## Artifacts

* [Component page in design.va.gov](https://design.va.gov/components/) with the USWDS v3 badge

**Comment by aplatt-coforma** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/76767?planning-poker) with Zenhub @ToddWebDev
