### ISSUE TITLE
Unreimbursed care expenses page: update deprecated fields

### ISSUE THREAD

**Issue by gmaciolek** [department-of-veterans-affairs/va.gov-team#76777]
## Description

On the Unreimbursed care expenses page, update the deprecated fields with the v3 component equivalent. 

**Fields**

<table>
  <tr>
   <td><strong>Page</strong>
   </td>
   <td><strong>Route</strong>
   </td>
   <td><strong>Field</strong>
   </td>
   <td><strong>Widget</strong>
   </td>
   <td><strong>Replacement</strong>
   </td>
  </tr>
  <tr>
   <td>Unreimbursed care expenses
   </td>
   <td><code>/financial/care-expenses/add</code>
   </td>
   <td>childName
   </td>
   <td>string
   </td>
   <td>VaTextInputField
   </td>
  </tr>
  <tr>
   <td>Unreimbursed care expenses
   </td>
   <td><code>/financial/care-expenses/add</code>
   </td>
   <td>provider
   </td>
   <td>string
   </td>
   <td>VaTextInputField
   </td>
  </tr>
  <tr>
   <td>Unreimbursed care expenses
   </td>
   <td><code>/financial/care-expenses/add</code>
   </td>
   <td>hoursPerWeek
   </td>
   <td>number
   </td>
   <td>numberPattern
   </td>
  </tr>
  <tr>
   <td>Unreimbursed care expenses
   </td>
   <td><code>/financial/care-expenses/add</code>
   </td>
   <td>noCareEndDate
   </td>
   <td>boolean
   </td>
   <td>VaCheckboxField
   </td>
  </tr>
</table>

## Acceptance Criteria

The widgets listed in this ticket have been updated to the appropriate v3 component replacement

## Tasks

Front-end work

## Review

* Standard engineering review process 
* Design review of the page in staging to validate that it’s displaying correctly

## Resources
* [Component page in design.va.gov](https://design.va.gov/components/) with the USWDS v3 badge

**Comment by aplatt-coforma** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/76777?planning-poker) with Zenhub @ToddWebDev
