### ISSUE TITLE
Dependent address page: update deprecated widgets

### ISSUE THREAD

**Issue by gmaciolek** [department-of-veterans-affairs/va.gov-team#76771]
## Description

On the Dependent address page `/household/dependents/children/address/:index`, update the following deprecated widgets with the v3 component equivalent. 

**Widgets**

<table>
  <tr>
   <td><strong>Field</strong>
   </td>
   <td><strong>Type</strong>
   </td>
   <td><strong>Replacement</strong>
   </td>
  </tr>
  <tr>
   <td>childAddress
   </td>
   <td>address
   </td>
   <td>addressPattern
   </td>
  </tr>
  <tr>
   <td>personWhoLivesWithChild
   </td>
   <td>fullNameUI
   </td>
   <td>fullNamePattern
   </td>
  </tr>
</table>

## Acceptance Criteria
The widgets listed in this ticket have been updated to the appropriate v3 component replacement

## Tasks
Front-end work

## Review
* Standard engineering review process 
* Design review of the page in staging to validate that it’s displaying correctly

## Resources
* [Component page in design.va.gov](https://design.va.gov/components/) with the USWDS v3 badge

**Comment by aplatt-coforma** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/76771?planning-poker) with Zenhub @ToddWebDev

**Comment by wayne-weibel** [comment]
@ToddWebDev the PR looks good to me, just need to get the e2e passing

**Comment by aplatt-coforma** [comment]
Demoed during daily
