### ISSUE TITLE
Medical expenses and other unreimbursed care expenses: update deprecated fields

### ISSUE THREAD

**Issue by gmaciolek** [department-of-veterans-affairs/va.gov-team#76778]
## Description

On the Medical expenses and other unreimbursed care expenses page, update the deprecated fields with the v3 component equivalent. 

**Fields**

<table>
  <tr>
   <td><strong>Page</strong>
   </td>
   <td><strong>Route</strong>
   </td>
   <td><strong>Field</strong>
   </td>
   <td><strong>Widget</strong>
   </td>
   <td><strong>Replacement</strong>
   </td>
  </tr>
  <tr>
   <td>Medical expenses and other unreimbursed care expenses
   </td>
   <td><code>/financial/medical-expenses/add</code>
   </td>
   <td>childName
   </td>
   <td>string
   </td>
   <td>VaTextInputField
   </td>
  </tr>
  <tr>
   <td>Medical expenses and other unreimbursed care expenses
   </td>
   <td><code>/financial/medical-expenses/add</code>
   </td>
   <td>provider
   </td>
   <td>string
   </td>
   <td>VaTextInputField
   </td>
  </tr>
  <tr>
   <td>Medical expenses and other unreimbursed care expenses
   </td>
   <td><code>/financial/medical-expenses/add</code>
   </td>
   <td>purpose
   </td>
   <td>string
   </td>
   <td>VaTextInputField
   </td>
  </tr>

</table>

## Acceptance Criteria

The widgets listed in this ticket have been updated to the appropriate v3 component replacement

## Tasks

- [ ] Front-end 

## Review

* Standard engineering review process 
* Design review of the page in staging to validate that it’s displaying correctly

## Resources

* [Component page in design.va.gov](https://design.va.gov/components/) with the USWDS v3 badge

**Comment by aplatt-coforma** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/76778?planning-poker) with Zenhub @ToddWebDev

**Comment by aplatt-coforma** [comment]
Looks good:
<img width="629" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTIxQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--661e7e5ee74c6ed18e75bfc79604c43dfcf38e70/Screenshot%202024-03-05%20at%202.12.43%E2%80%AFPM.png" alt="Screenshot 2024-03-05 at 2.12.43 PM.png" />
<img width="588" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTYxQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ff61c44fb4e5cb843dd609fc2bc5f38466711592/Screenshot%202024-03-05%20at%202.11.51%E2%80%AFPM.png" alt="Screenshot 2024-03-05 at 2.11.51 PM.png" />
