### ISSUE TITLE
Create a consolidated top task/manage benefit tool landing page

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#7677]
## Create a consolidated top task/manage benefit tool landing page ~for COVID-19 support~

As a Veteran, I want to go to a place where I can see, know, and access all of the tasks that I can do myself online instead of finding a paper form, mailing a form, or calling VA and being put on hold.

**Is request tracked to an event or Congressional deadline?** - No

### Details
**Who is the primary user?** Veterans, family caregivers (and in the future other audiences that may have access to VA.gov tools, like delegated users such as family members, fiduciaries, who have to manage things for Veterans)

**What are the user goals for the project/page/product?** I want to go to a place where I can see, know, and access all of the tasks that I can do myself online instead of calling VA and being put on hold. Example: View payments to make sure my disability payment isn't delayed because of the pandemic.

**What is the business goal?** As a Veteran, I want to go to a place where I can see, know, and access all of the tasks that I can do myself online instead of finding a paper form, mailing a form, or calling VA and being put on hold.

**How does this map to our North Star?** Helps increase the use of self-service tools. Currently, users have to navigate/drill down into content pages in order to get to tools. It's hard to see all the things you can do online with benefits and other account tasks such as updating your address, etc. 

**How will we measure success?** Track usage of self service tools. 

**How well do we understand the problem?** Pretty well, but we need to do some card sorts and user research to be confident of the taxonomy and nomenclature, and IA (where this type of information would potentially live, per user's mental model).  We need a tool landing page anyway and have wanted to start this work as part of optimizing the public website content to make sign in and tools more prominent.

**DEPO prioritization criteria:**  29 Medium

**High level break out of initial tasks/steps we need to do:** 
1/ Create a plan for a card sort with users. (I think this would be @DanielleThierryUSDSVA and @mnorthuis )
2/ Schedule some Optimal card sorting user sessions.
3/ Review results and make recommendations. 
4/ Create very low-fi design based on ^ recommendations. 
5/ Possibly a round of usability, depending on how confident/strong the user research findings from card sort were.

FYSA @stephorkandatx @johnhashva  - we should discuss level of priority for our backlog. Most of this work will depend on @mnorthuis 's availability as well, so we should be sure to consult with her.

**Comment by jenniferlee-dsva** [comment]
FYSA @MickinSahni 

@mnorthuis - will reach out to you, possibly not till later in the week. And will include Danielle, not attable yet. Mind Slacking your availability for 30 min call this week?

**Comment by stephorkandatx** [comment]
Thanks for flagging this @jenniferlee-dsva

**Comment by MickinSahni** [comment]
closing as wontdo
