### ISSUE TITLE
Spouse's former marriage page: update deprecated fields

### ISSUE THREAD

**Issue by gmaciolek** [department-of-veterans-affairs/va.gov-team#76775]
## Description
On the Spouse’s former marriage page, update the deprecated fields with the v3 component equivalent. 

**Fields**
<table>
  <tr>
   <td><strong>Page</strong>
   </td>
   <td><strong>Route</strong>
   </td>
   <td><strong>Field</strong>
   </td>
   <td><strong>Widget</strong>
   </td>
   <td><strong>Replacement</strong>
   </td>
  </tr>
  <tr>
   <td>Spouse’s former marriages
   </td>
   <td><code>/household/marital-status/spouse-marriages</code>
   </td>
   <td>otherExplanation
   </td>
   <td>string
   </td>
   <td>VaTextInputField
   </td>
  </tr>
  <tr>
   <td>Spouse’s former marriages
   </td>
   <td><code>/household/marital-status/spouse-marriages</code>
   </td>
   <td>locationOfMarriage
   </td>
   <td>string
   </td>
   <td>VaTextInputField
   </td>
  </tr>
</table>

## Acceptance Criteria
The widgets listed in this ticket have been updated to the appropriate v3 component replacement

## Tasks
Front-end work

## Review
* Standard engineering review process 
* Design review of the page in staging to validate that it’s displaying correctly

## Resources
* [Component page in design.va.gov](https://design.va.gov/components/) with the USWDS v3 badge

**Comment by aplatt-coforma** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/76775?planning-poker) with Zenhub @ToddWebDev

**Comment by aplatt-coforma** [comment]
Reviewed: https://staging.va.gov/pension/application/527EZ/household/marital-status/spouse-marriages
<img width="858" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVcxQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--46618db0783958f3593aa218fa8b4d2214ce1104/Screenshot%202024-03-05%20at%202.01.42%E2%80%AFPM.png" alt="Screenshot 2024-03-05 at 2.01.42 PM.png" />

Looks good
