### ISSUE TITLE
Dependent information page: update deprecated field

### ISSUE THREAD

**Issue by gmaciolek** [department-of-veterans-affairs/va.gov-team#76776]
## Description

On the Dependent information page, update the deprecated fields with the v3 component equivalent. 

**Fields**

<table>
  <tr>
   <td><strong>Page</strong>
   </td>
   <td><strong>Route</strong>
   </td>
   <td><strong>Field</strong>
   </td>
   <td><strong>Widget</strong>
   </td>
   <td><strong>Replacement</strong>
   </td>
  </tr>
  <tr>
   <td>Dependent Information
   </td>
   <td><code>/household/dependents/children/information/:index</code>
   </td>
   <td>childPlaceOfBirth
   </td>
   <td>string
   </td>
   <td>VaTextInputField
   </td>
  </tr>
</table>

## Acceptance Criteria
The widgets listed in this ticket have been updated to the appropriate v3 component replacement

## Tasks
Front-end work

## Review
* Standard engineering review process 
* Design review of the page in staging to validate that it’s displaying correctly

## Resources
* [Component page in design.va.gov](https://design.va.gov/components/) with the USWDS v3 badge

**Comment by aplatt-coforma** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/76776?planning-poker) with Zenhub @ToddWebDev

**Comment by aplatt-coforma** [comment]
Looks the same so all good.
<img width="520" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNG5JQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--29fadf77f30218819b3788cfc6a55bc49c3d50bd/Screenshot%202024-03-08%20at%201.57.16%E2%80%AFPM.png" alt="Screenshot 2024-03-08 at 1.57.16 PM.png" />
