### ISSUE TITLE
Faster claim processing page: update deprecated widget

### ISSUE THREAD

**Issue by gmaciolek** [department-of-veterans-affairs/va.gov-team#76772]
## Description

On the Faster claim processing page `/additional-information/faster-claim-processing`, update the following deprecated widget with the v3 component equivalent. 

**Widgets**

<table>
  <tr>
   <td><strong>Field</strong>
   </td>
   <td><strong>Type</strong>
   </td>
   <td><strong>Replacement</strong>
   </td>
  </tr>
  <tr>
   <td>noRapidProcessing
   </td>
   <td>yesNo
   </td>
   <td>yesNoPattern
   </td>
  </tr>
</table>

## Acceptance Criteria
The widgets listed in this ticket have been updated to the appropriate v3 component replacement

## Tasks
Front-end work

## Review
* Standard engineering review process 
* Design review of the page in staging to validate that it’s displaying correctly

## Resources
* [Component page in design.va.gov](https://design.va.gov/components/) with the USWDS v3 badge

**Comment by aplatt-coforma** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/76772?planning-poker) with Zenhub @ToddWebDev
