### ISSUE TITLE
New component: Sign-in widget (breaking out from general alert component)

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#76785]
Content for sign-in and verification alert variations now lives here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/content-patterns-and-standards/sign-in-alerts.md

**Comment by laurwill** [comment]
Hi @DanielleThierryUSDSVA , this sign-in widget component suggestion is ready for your review. I added a version that specifies using a verified account — if we're not ready to add that, I can remove for now.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @laurwill @megzehn! @mnorthuis and I have been digging deeper into the sign-in and identity flows, and we have some recommendations for this language based on that. I've moved it into a [Word doc for now ](https://dvagov-my.sharepoint.com/:w:/g/personal/danielle_thierry_va_gov/EUoaj28zVDhGlENCX8u36MMBcdc2WMDsDZrTPMqMM5yldQ?e=TGGvfx)to make it a little easier to edit together.

It may make sense for the 4 of us to try to find time for a call to sync on this.

**Comment by laurwill** [comment]
Hi @humancompanion-usds , here's the ticket for the new sign-in widget component. The content is still in the Sharepoint doc while we're waiting for SME review, but I've loaded the main headers here to show the draft structure of the page. We might need to add a couple variations to the form section. 

Is there anything else I can do to help move this along before we have final content?

cc @sterkenburgsara

**Comment by laurwill** [comment]
Hi @humancompanion-usds , as we chatted on Friday, I've added content for the widget versions that are least likely to change. I'm also working on reducing the total number of widget versions we'll need — for some of the form variations, we'll just need to specify that the CTA is "to fill out this form," so those won't need standalone versions.

**Comment by caw310** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Design-System-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/va.gov-team/76785?planning-poker) with Zenhub @babsdenney @danbrady @LWWright7

**Comment by caw310** [comment]
@laurwill has the SME review been done?

**Comment by laurwill** [comment]
Hi @caw310 ! Let me just confirm which of these variations are approved and ready to go — I'll update this ticket with the final content.

**Comment by humancompanion-usds** [comment]
@laurwill - We're going to have the designers start work on this on 8/15 so as long as this is updated by then we'll be in good shape. Thanks!

**Comment by laurwill** [comment]
That is great! I updated the top of this ticket with a link to the current versions of the alerts. We're just waiting for final final approval, and I'll confirm when they're good to go (should definitely be by 8/15).

**Comment by caw310** [comment]
Design work for this will be part of https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3151

**Comment by laurwill** [comment]
Closing this ticket since this work is now safely in the hands of design system team :)
