### ISSUE TITLE
Analytics Implementation for Sitewide Facilities - Regional Offices

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-team#76780]
# Google Analytics Implementation Request

### Please provide the following details for this request

- **Team Name**

    - Sitewide Facilities

- **Product Name**

    - VBA Regional Office
      
- **When is the launch date?**
    - July 19, 2024 (launched in Prod)

- **Provide the link(s) for Product/Page urls**
  - **Published**: 
    - https://www.va.gov/portland-va-regional-benefit-office
    - https://www.va.gov/albuquerque-va-regional-benefit-office
    - https://www.va.gov/houston-va-regional-benefit-office
    - https://www.va.gov/national-capital-region-va-regional-benefit-office
  - Not yet published: 
    - https://www.va.gov/boston-va-regional-benefit-office
    - https://www.va.gov/san-juan-va-regional-benefit-office

- **What Events need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked and should be used whenever possible to avoid custom configuration_
    
    - [If this is a funnel, insert each step's URL - pages visible depending on the applicant's answers should be marked accordingly]
    
    - [Insert other interactions - please review the [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) and [GA Data Dictionary](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Google-Analytics-Data-Dictionary.1810464912.html)  to make sure these interactions aren't already tracked]

- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - Not applicable

- **Any additional comments**

    - [Insert comments]

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by eselkin** [comment]
@davidmpickett With the complex naming of VBAs is there a way to funnel them together? I mean between the two of these, I see `va-regional-benefit-office` in both, but will that change?
`/honolulu-va-regional-benefit-office-at-spark-m-matsunaga-department-of-veterans-affairs-medical-center/`
and 
`/philadelphia-va-regional-benefit-office/`

**Comment by eselkin** [comment]
Just some notes:
<details>
<summary>GA4 accordion expansion</summary>
<code>
{
	v: "2",
	tid: "G-1G19L53NYB",
	gtm: "45je4790v9172290397z872214120za200zb72214120",
	_p: "1721165006809",
	gcd: "13l3l3l3l1",
	npa: "0",
	dma: "0",
	tag_exp: "0",
	cid: "1328485551.1710975112",
	ul: "en-us",
	sr: "1728x1117",
	uaa: "arm",
	uab: "64",
	uafvl: "Not/A)Brand;8.0.0.0|Chromium;126.0.6478.127|Google Chrome;126.0.6478.127",
	uamb: "0",
	uam: "",
	uap: "macOS",
	uapv: "14.5.0",
	uaw: "0",
	are: "1",
	frm: "0",
	pscdl: "",
	_s: "2",
	dl: "https://web-codylbelkq0gdivw6x7tykigmeqloewe.demo.cms.va.gov/philadelphia-va-regional-benefit-office/",
	dr: "",
	sid: "1721164137",
	sct: "39",
	seg: "1",
	dt: "Philadelphia VA Regional Benefit Office | Veterans Affairs",
	en: "accordion",
	ep.gtm_container_id: "GTM-WFJWBD",
	ep.gtm_env_name: "Development Environment",
	ep.dle_name: "int-accordion-expand",
	ep.component: "component-library",
	epn.component_library_event: "1",
	ep.event_action: "expand",
	ep.link_text: "accordion-section-label",
	ep.heading_1: "Prepare for your visit 1",
	ep.heading_2: "(not set)",
	epn.level_current: "3",
	_et: "2806",
	tfd: "16910",
	_z: "fetch"
}
</code>
</details>

I don't see GA4 events from va-link like for MST on Philadelphia (from the dev data) or from va-telephone components.  But I do see the GA4 events from mailto links. 

<details><summary>I see scroll events on VBA pages for GA4</summary>
<code>
{
	v: "2",
	tid: "G-CSLL4ZEK4L",
	gtm: "45je4790v9131934939za200",
	_p: "1721166096418",
	gcd: "13l3l3l3l1",
	npa: "0",
	dma: "0",
	tag_exp: "0",
	cid: "733855420.1717124535",
	ul: "en-us",
	sr: "1728x1117",
	uaa: "arm",
	uab: "64",
	uafvl: "Not/A)Brand;8.0.0.0|Chromium;126.0.6478.127|Google Chrome;126.0.6478.127",
	uamb: "0",
	uam: "",
	uap: "macOS",
	uapv: "14.5.0",
	uaw: "0",
	are: "1",
	frm: "0",
	pscdl: "",
	_eu: "AEA",
	_s: "2",
	dl: "http://localhost:3002/philadelphia-va-regional-benefit-office/",
	dt: "Philadelphia VA Regional Benefit Office | Veterans Affairs",
	sid: "1721165360",
	sct: "86",
	seg: "1",
	en: "scroll",
	ep.agency: "VA",
	ep.subagency: "LOCALHOST",
	ep.site_topic: "unspecified:localhost",
	ep.site_platform: "unspecified:localhost",
	ep.script_source: "https://dap.digitalgov.gov/universal-federated-analytics-min.js",
	ep.version: "20240712 v8.2 - ga4",
	ep.protocol: "http:",
	ep.using_parallel_tracker: "no",
	epn.percent_scrolled: "90",
	tfd: "5642",
	_z: "fetch"
}
</code>
</summary>

**Comment by davidmpickett** [comment]
> @davidmpickett With the complex naming of VBAs is there a way to funnel them together? I mean between the two of these, I see `va-regional-benefit-office` in both, but will that change? `/honolulu-va-regional-benefit-office-at-spark-m-matsunaga-department-of-veterans-affairs-medical-center/` and `/philadelphia-va-regional-benefit-office/`

Yes. The current plan for Regional Office URLs is reflected in [our naming schema](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/naming-schema#vba-benefits-facilities-naming-schema) and all of them would have `va-regional-benefit-office` in them in both the current and future state. This schema is reflective of [proposed future changes](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17351) that would shorten: 
`/honolulu-va-regional-benefit-office-at-spark-m-matsunaga-department-of-veterans-affairs-medical-center/` 
to 
`/honolulu-va-regional-benefit-office/`

Additionally, none of the other types of VBA facilities have this specific slug, so this pattern will be specific to ROs. Satellite offices come close with `va-regional-benefit-satellite-office` so that pattern could also be specified if we want to catch both. 

The other VBA facilities types were out of scope for MVP, so we haven't technically haven't made decisions about them

**Comment by jilladams** [comment]
@johnny-jesensky-adhoc could you advise if this ticket will sit with your team, or if you need more information from us in order to act on it?

**Comment by jilladams** [comment]
Pinged analytics folks about whether this is ok or needs work: https://dsva.slack.com/archives/C1Q4294JJ/p1723140748378569

**Comment by johnny-jesensky-adhoc** [comment]
@jilladams -- we'll plan to discuss at our next refinement, but a quick follow-up question for now:

Are there specifics on what specifically y'all want tracked within the pages, outside of what we can automatically grab using  the design systems components? 

Was looking at this page linked in the description, https://www.va.gov/portland-va-regional-benefit-office

FYI @Blivaditis, @jestutt

**Comment by jilladams** [comment]
That is a very good question. I think we'd generally love to know the funnel -- incoming, outgoing, clicks on links/ CTAs / accordions, scroll depth if that's possible. (I'm not an analytics person - much of that may be covered already by components.) 

@mmiddaugh @Agile6MSkinner @aklausmeier anything you would add?

**Comment by Agile6MSkinner** [comment]
@jilladams I am not spun up enough on analytics yet to opine.

**Comment by jestutt** [comment]
@jilladams Sounds like you want to track everything and that's not always a viable option. Instead, maybe think about the questions you want or need to answer. 

- Where is your traffic coming from? Onsite and off? 
- Where is your traffic going? Not always possible 

Once you have the list, try categorizing them into KPI, UX or health information. Or apply a hierarchy. We can help guide you but you know your content best and likely know what the most common questions you get regarding it are.

**Comment by Agile6MSkinner** [comment]
@jestutt If we add it to the Content KPI Domo Dashboard, will it inherit the same attributes? We don't need to reinvent the wheel here; it should mirror existing data dashboards for existing Vet Centers and VAMCs.

**Comment by FranECross** [comment]
I think it would be good to check with @mmiddaugh to see if this is a situation where she wants/needs the header information, which isn't captured / provided with the component analytics and would need to be custom (I'm thinking of the other ticket she recently commented on). I haven't delved into the screens but wanted to suggest this avenue.

**Comment by johnny-jesensky-adhoc** [comment]
Hi @Agile6MSkinner, as discussed during yesterday's (10/15) Office Hours, our team will try to confirm what tracking currently exists on these Regional Office pages.

I can already see a few things firing and being sent to GA4, (just quickly generated [this basic Explore report](https://analytics.google.com/analytics/web/#/analysis/p419143770/edit/uZIOq1WtQ8avODWnnuj7GQ), which has tabs for a few things we're actively collecting on the https://www.va.gov/portland-va-regional-benefit-office/ page), but we'll try to generate a list.

For timing expectations, we haven't pulled this into our current sprint, but currently having it sitting atop of the backlog. We'll try to pull it in as we have bandwidth. 

Feel free to stop by an Office Hours session any time if you have questions on this, or other general analytics inquiries. We'll consider this task to be step 1, in a longer conversation on analytics strategy for this team.

FYI @jestutt, @Blivaditis, @ChristineYoungZA

**Comment by Blivaditis** [comment]
Hi @Agile6MSkinner, we are reviewing the tracking on the links provided. The Portland link and Albuquerque link are accessible however the other redirect to a "No page found" screen. Are they still non-published? If so can you provide a few additional links that utilize the template which are published? We want to verify the tracking on at least four.

**Comment by Blivaditis** [comment]
Hi @Agile6MSkinner, I have reviewed the tracking on the published pages and verified that the tracking is appearing as expecting as well as the tracking being streamlined across all four links. Here is a [GA4 report showing](https://analytics.google.com/analytics/web/#/analysis/p419143770/edit/jgkQCdVpR1m8GDpbQ8hcOA) you the events on each individual page.
