### ISSUE TITLE
Create 7959c mapping program 

### ISSUE THREAD

**Issue by cloudmagic80** [department-of-veterans-affairs/va.gov-team#76789]
As a user of 7959c forms, I need the pdf to map into the database so that the forms can be filled out.

AC: The pdf template data is extracted and the data matches the front end. The UI will pass on the data to the backend so that PDF will be filled out.

**Comment by baltes** [comment]
Needs description and AC

**Comment by cloudmagic80** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/15641

**Comment by baltes** [comment]
Work was done during sprint 11 but this wasn't pulled into a sprint. Closing during sprint 14.
