### ISSUE TITLE
Update devops repo files to reflect state of SiS for review instances

### ISSUE THREAD

**Issue by vidjovanovic** [department-of-veterans-affairs/va.gov-team#76795]
## Issue Description. 
- Add a comment in all of the devops files to indicate that SiS **doesnt** work for review instances which is why we dont add the new public certs for them in the vets-api config folder
---
## Tasks
- update files in devops repo

**Comment by vidjovanovic** [comment]
Created PR for Devops File Change: https://github.com/department-of-veterans-affairs/devops/pull/14187

**Comment by parkerbees** [comment]
Moved to Jira. Closing.
