### ISSUE TITLE
Work on 7959c Json file for modeling and mapping

### ISSUE THREAD

**Issue by cloudmagic80** [department-of-veterans-affairs/va.gov-team#76790]
As a user of 7959c, I need the newest template of 7959c to fill out via the VA.gov website. All the input forms should be mapped to the UI inputs and into the database.

AC: Make sure the newest 7959c is being used with the latest mappings. 
When form is submitted, PDF is populated, written to tmp directory, and sent to s3

Verification steps
- Fill out and submit form on staging
- In local environment view pdf in vets-api/tmp

**Comment by baltes** [comment]
Needs description and AC

**Comment by baltes** [comment]
@cloudmagic80 Please add the PR and status here when you get a chance.

**Comment by cloudmagic80** [comment]
https://github.com/department-of-veterans-affairs/vets-api/commit/0aee3129bf736cdfdb851157980995fcb99c22f3

**Comment by cloudmagic80** [comment]
@baltes  This ticket is good to close
