### ISSUE TITLE
[COGNITION]: Education STEM Update - Learn more links on Step 2 need an aria-label or more clear calls to action

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#768]
## Issue

Step 2 has `Learn more` links about each type of benefit. This text is repeated several times and doesn't provide a lot of context about what users will learn. I'd like to see if we can rewrite these links to be more clear calls to action or add an `aria-label` to each link. Screenshots attached below.

Tagging @peggygannon for content guidance

## Point of Contact

* Trevor

## Acceptance Criteria

* As a screen reader user, I would like to hear a clear explanation like "Learn more about Post 9/11 (Chapter 33) benefits" when I focus a link on Step 2

## Environment
* Windows 10
* Chrome, IE11
* JAWS

## Possible Fixes (optional)
We could rewrite the links or add `aria-label` attributes to each one:

```html
<a href="/education/about-gi-bill-benefits/post-9-11/" target="_blank">Learn more about Post-9/11 benefits</a>
```

```html
<a aria-label="Learn more about Post-9/11 benefits" href="/education/about-gi-bill-benefits/post-9-11/" target="_blank">Learn more</a>
```

## WCAG or Vendor Guidance (optional)
* [Link Purpose (Link Only): Understanding SC 2.4.9](https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-link.html)

## Screenshots or Trace Logs

![Screen Shot 2019-07-31 at 3.53.44 PM.png](https://images.zenhubusercontent.com/5ac217b74b5806bc2bcd3fc8/99882a4c-8481-4a76-8656-3225c5d1ce4c)

---
![Screen Shot 2019-07-31 at 3.53.25 PM.png](https://images.zenhubusercontent.com/5ac217b74b5806bc2bcd3fc8/c2e80037-6525-4789-a4ee-64fc93bced2e)

**Comment by delli-gatti-michael** [comment]
This has been tested by QA in a local build and the related PR has been approved:
https://github.com/department-of-veterans-affairs/vets-website/pull/10536

**Comment by NateJohnson-BAH** [comment]
As mentioned above, change has been tested and approved internally and externally by the 'department-of-veterans-affairs/frontend-review-group'. I mistakenly merged the pull request before review by issue originator, my apologies. I'd like to request final approval of the changes by @KevinMHoffmanUSDS to close out the story. Thank you, sorry for the confusion.

**Comment by NateJohnson-BAH** [comment]
@1Copenut, can we get a final approval that this work is complete. The associated changes are already in production, but wanted to get final approval before closing the issue. Thanks.

**Comment by 1Copenut** [comment]
@NateJohnson-BAH I tested this on Staging with VoiceOver and JAWS. The links are reading out your `aria-label` elements loud and clear. 💯and moving to close!
