### ISSUE TITLE
[Design] MDT Usability 1 Topline Summary

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#7680]
## User Story or Problem Statement
As a designer, I need to create a topline summary so I can share usability findings with my team early and during demo.

## Tasks
- [x] Take debriefs and convert them into a topline summary in GH

## Acceptance Criteria
- [x] Topline summary in GH

**Comment by rileyorr** [comment]
Uploaded the [topline summary](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/medical-device-tool/research/usability-march20/usability-topline-summary.pdf) onto GH
