### ISSUE TITLE
IPP - Design improvements for Veteran 'Sign In' screen 

### ISSUE THREAD

**Issue by skirkman16** [department-of-veterans-affairs/va.gov-team#76804]
Acceptance Criteria

- [x] Adjust heading
- [x] Add 'What is verification and why should I care'
- [x] Add 'What is in person identity verification'
- [x] Add purpose of application: This application is to register them for an in person appointment
- [x] Adjust button to look like VA.gov sign in
- [x] Add in keyhole icon
- [x] Remove logos
- [x] Limit: size of text and how much
- [x] Move blurb about exiting to home screen 1 

Def of Done

- [ ] Content and design has been reviewed by @SophiaPhilipMO @CarlDickerson  and @lmorris3 
- [ ] Design is handed off to devs for implementation

**Comment by skirkman16** [comment]
@lmorris3 @SophiaPhilipMO @CarlDickerson Please design and recommend content changes content in Figma comments. Updated screens are in [Figma](https://www.figma.com/file/PfrWKmxiQ5RjChwx6I18QE/IPP-Prototypes?type=design&node-id=2945%3A9122&mode=design&t=gHYcJ950eoq4Yx8G-1) under 'Prototype - In Person Pilot'

**Comment by SophiaPhilipMO** [comment]
@skirkman16 dropped in comments

**Comment by skirkman16** [comment]
Reviewed and resolved all comments on the screen. Final screen attached. <img width="935" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFNhQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--211b01af9da8ac847c4f1f313edeb68fbd6f04b2/Intake%20-%20Registration%20complete.png" alt="Intake - Registration complete.png" />

**Comment by skirkman16** [comment]
One comment had a recommendation to change the background, but I decided not to implement it due to testing out the change myself and reflecting on the feedback we received today from our PO. Copying my response here for visibility.<img width="389" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTJhQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1a95dbc427020d09ebf94f869e170e842b3255d2/Screenshot%202024-02-28%20at%2012.28.14%20PM.png" alt="Screenshot 2024-02-28 at 12.28.14 PM.png" />
