### ISSUE TITLE
NOD | Email template setup and testing

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#76818]
## Value Statement
As a Veteran who attempted to submit an NOD while the infinite loop bug was in production
I want to know the outcome of my failed attempt to submit an appeal
So that I can take action on my appeal

---
## Background
VA Notify credentials were added to staging and production. Next steps are to setup the template and test the flow. The report will be an encrypted spreadsheet that's compiled and listed in CAG.

## Test Notes and Design Links
- May need to test with an email that we know will return a hard bounce.
- Will need to ensure the report is generated with the data from the callback URL.
- Content is here: [Doc for drafting the NoD notification](https://dvagov.sharepoint.com/sites/vaabdvro/_layouts/15/doc.aspx)

## Acceptance Criteria
- [x] When an email address returns a hard bounce (meaning it wasn't delivered), the callback URL sends us the info so we know who didn't get the email. 
- [x] We can download a report that can be shared with BVA.

## Tech Tasks
- [x] Work with VA Notify team to get email delivery setup (Sade reached out to [VA Notify](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65509))
- [x] Work with VA Notify team to get template setup (Sade reached out to [VA Notify](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65509))
- [x] Setup hard bounce emails
- [x] Get a CSV of emails and other email parameters from VA
- [x] Create Job 1 that fetches the emails CSV and enqueues a custom email job (Job 2) for each email in that CSV
  * Job 1 SHOULD NOT RETRY
  * Job 2 SHOULD NOT RETRY but should rescue any errors, and log the following:
      i) line # (or other identifier)
      ii) e message
      iii) backtrace
- [x] Create Job 3 or a script to accept an s3 bucket name/path which then converts all NodNotifications in the database into a CSV and uploads the CSV to that bucket
   * Each run of Job 3/script should create a new file (distinguished by timestamp, for instance)
- [x] Download the saved CSV in S3 and store it in sharepoint
- [x] Setup encrypted spreadsheet in CAG
- [x] Check with VA Notify for any additional testing steps

## How to Measure Success
- URL accepts realtime data.
- NodNotification table stores all notification callbacks received from VANotify in an encrypted format.
- Data can be used to identify Veterans who aren't getting the emails. 

## Definition of Ready 

- [ ] Clear value description
- [ ] Test cases defined
- [ ] Approved designs and success measure(s) included
- [ ] Sample data provided where appropriate
- [ ] Fits within the sprint
- [ ] Dependencies linked

## Definition of Done

- [ ] Test cases passed
- [ ] E2E testing updated
- [ ] Unit testing updated (90% coverage)
- [ ] Integration testing updated (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by dfong-adh** [comment]
Currently working on a PR for creating jobs for sending out emails:
```
Create Job 1 that fetches the emails CSV and enqueues a custom email job (Job 2) for each email in that CSV
  Job 1 SHOULD NOT RETRY
  Job 2 SHOULD NOT RETRY but should rescue any errors, and log the following:
      i) line # (or other non PII identifier)
      ii) e message
      iii) backtrace
```

**Comment by saderagsdale** [comment]
Same as previous update. In progress.

**Comment by dfong-adh** [comment]
Steve Albers mentioned during Sprint Review to ensure that queue exhaustion errors are handled correctly for the new sidekiq jobs.

**Comment by dfong-adh** [comment]
@saderagsdale I'm getting an error when trying to access the template link: https://dvagov.sharepoint.com/sites/vaabdvro/_layouts/15/doc.aspx
 ![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/151783381/9cebfa0e-8b27-4e72-8399-d196247e54eb)

**Comment by HeatherWidmont** [comment]
@saderagsdale to take a look at the sharepoint link & will get back to Derek

**Comment by HeatherWidmont** [comment]
@dfong-adh had an issue with staging yesterday so he can add the template once he gets the docs. Needs to check a few more things before he can merge the other PR. 

@saderagsdale will review the sharepoint link today

**Comment by dfong-adh** [comment]
PR for jobs to load the email CSV and sending emails: https://github.com/department-of-veterans-affairs/vets-api/pull/15795

**Comment by HeatherWidmont** [comment]
@saderagsdale will handle sharepoint link right now

**Comment by HeatherWidmont** [comment]
@data-doge & @anniebtran to review the PR. @data-doge & @dfong-adh to sync today to review all the things

**Comment by dfong-adh** [comment]
Email template has been added and is undergoing review.

**Comment by dfong-adh** [comment]
PR to fix an issue identified during testing: https://github.com/department-of-veterans-affairs/vets-api/pull/15897

**Comment by SilkeDannVA** [comment]
Nearly all is ready but email list.

**Comment by saderagsdale** [comment]
@dfong-adh Cory emailed you the list. Let me know when you have it, and if you need anything else.

**Comment by dfong-adh** [comment]
List of Veteran's emails has been uploaded to prod s3 bucket - we are ready to send out the emails once we get the go-ahead.

**Comment by HeatherWidmont** [comment]
These will be sent out after NOD form hits 100%. We will then need approval from Julie & Cory. 

@dfong-adh to send to @saderagsdale in production so she can send to enablement team

**Comment by HeatherWidmont** [comment]
@dfong-adh forwarded email to Sade

**Comment by dfong-adh** [comment]
NOD form has been set to 100%. Waiting for final approvals and go ahead.

**Comment by HeatherWidmont** [comment]
@dfong-adh will follow up with Julie & Cory for approval so we can hopefully close this out

**Comment by dfong-adh** [comment]
Update from Cory: Julie will ask the board regarding the timing for the emails and will let us know when we're approved to send the emails out.

**Comment by dfong-adh** [comment]
Emails have been sent out. Currently waiting for pending emails to complete, then a full list of failed emails will be compiled and uploaded to Sharepoint.
