### ISSUE TITLE
STEM: Create new OMB Form Schema

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#7681]
As a developer, I need to create a new schema so that the new form UI is self-contained.

## Assumptions:
1. This work is completed behind the STEM feature flag.

## Acceptance Criteria
1. A new form schema exists for form 22-10203.

## Supporting Artifacts:
1. [22-10203 OMB (STEM application form).pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/4446011/22-10203.OMB.STEM.application.form.pdf)

**Comment by hughes-dustin** [comment]
vets-json-schema
 branch: bah-7681
 PR: https://github.com/department-of-veterans-affairs/vets-json-schema/pull/393
