### ISSUE TITLE
[spike] NOD | Old AppealSubmissionUpload missing lighthouse_upload_id

### ISSUE THREAD

**Issue by anniebtran** [department-of-veterans-affairs/va.gov-team#76826]
## What happened?

As we investigated https://github.com/department-of-veterans-affairs/va.gov-team/issues/72199, we noticed that there was an `AppealSubmissionUpload` (id: 1513) from 2022 that was missing a `lighthouse_upload_id` and upon doing more digging, the FormAttachment seems to have a super long file name, so it might have been an issue with that problem we've seen more recently: #70856 

## What do we need to know?
Would be great to double check the reason that this upload to Lighthouse failed / confirm whether it was due to an extra long file name

## Action items

- [ ] Identify what caused the upload to fail
- [ ] Plan for how to fix the problem going forward
  - [ ] Create a ticket to cover development tasks

## Definition of done
- [ ] Action items above are completed
- [ ] Separate ticket for code work and designing the error message is added to the backlog

## Out of scope
- Coding solution

**Comment by HeatherWidmont** [comment]
@anniebtran hello! Was the work on this completed? If so, what is the estimate?

**Comment by saderagsdale** [comment]
Likely caused by a long file name. 

@anniebtran will confirm, then we'll discuss next steps to take.

**Comment by anniebtran** [comment]
Confirmed that the filename triggers a `File name too long @ rb_sysopen` error and also confirmed that the file is still in our S3 store. The filename too long error is covered by this ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/75029

**Comment by anniebtran** [comment]
I think the remaining action item here is figuring out how we should forward with remediation on this appeal submission

@saderagsdale Would it make sense to send an email to Jacob, Bo, and John Gosnell and ask them what they want to do?

**Comment by anniebtran** [comment]
Added to remediation spreadsheet sent to VBA. Closing since we've fixed the bug that caused this issue
