### ISSUE TITLE
Post-Intake Process (Request & Support Process)

### ISSUE THREAD

**Issue by jimcconnelly** [department-of-veterans-affairs/va.gov-team#76824]
**User Story**
As an Identity Team member, I want to have a solid post-request process in place, so I know how requests are going to be worked on.

**Acceptance Criteria**
- We document the baseline process for the following tasks
   - PR Review
   - Data Pull
   - Mocked Auth
- We document how to do the following things:
  - Triage 
  - Prioritization
  - Communication to Stakeholders
  - Additional Task & Story Creation
  - Assignment
  - Resolution
- Other things that might come up during the workshop with the engineering team.
- 

**User Guide**
[User Guide Updated](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Support%20Process/user-guide_support-satisfaction-survey.md#domo-help)

**Dashboard Support**
If you have any questions on it use
Analytics contact for Domo Dashboard support - Basil Livaditis blivaditis@thesocompany.com

**Comment by joshmatulonis** [comment]
[Figma JamBoard with Ticket Metrics and Support Survey Metrics Dashboard](https://www.figma.com/file/UfSdYLDCEj8gsIJMGxf3UJ/Identity-Support-Service-GitHub-Metrics-and-Satisfaction-Survey?type=whiteboard&t=vUA81ztw3CGbOubZ-1)

[Satisfaction Survey Doc](https://docs.google.com/document/d/1Z-9dc39at7YhnbvhhIUwdpTQhqnShQLwOUyR8GUe_zg/edit?usp=sharing)

[GitHub Ticket Metrics Doc](https://docs.google.com/document/d/1yDp3MgH9CTiU5G7vpH37PlBBOwkS-fug0DqowQL8xbY/edit?usp=sharing)

**Identity GitHub Support Ticket Metrics**

- Total Open Tickets
- Total Closed Tickets
- Tickets by Status
- Tickets by Team
- Ticket Requests by Product

- Total Number of Tickets Closed
- Average Days to Close Tickets

**Support Satisfaction Survey**

1. - Which team are you currently a part of? (Optional)
2. On a scale of 1 (Very Poor) to 5 (Excellent), how would you rate your overall experience with our support team?
3. Rate your satisfaction with the support provided by our team. 
    3a. If you answered anything other than Extremely satisfied, please let us know how we can improve. (Optional)
4. Which product did you use with the Identity Team?

- VA.gov Authentication
- USiP (User-Specific Identity Provider)
- Fraud Reduction and Response
- Terms of Use
- In Person Proofing
- User Delegate Access/Impersonation
- General Maintenance
- Other


5. Based on your recent experience, how likely are you to recommend the product you used with us to others? 
6. Did we deliver on all of the solutions you expected from us? If not, please explain.
7. Before seeking support, did you use our troubleshooting document? If yes, please provide feedback. (Optional)
8. Did you interact with the Slackbot? If yes, we'd love to hear about your experience! (Optional)
9. Is there anything else you would like to share about your experience? (Optional)
10. If we may contact you to learn more about your experience, please enter your email here. (Optional)

**Comment by joshmatulonis** [comment]
[User Guide Updated](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Support%20Process/user-guide_support-satisfaction-survey.md#domo-help)

Analytics contact for Domo Dashboard support - Basil Livaditis blivaditis@thesocompany.com
