### ISSUE TITLE
IPP - Update map for pilot

### ISSUE THREAD

**Issue by lmorris3** [department-of-veterans-affairs/va.gov-team#76844]
**Problem**
We learned from Veteran usability testing that Veterans need more information to make a decision about the facility they want to choose. Some of these changes are minor and can be implemented before the pilot.

**User Story**
As a Veteran, I would like to see additional information about a VA facility that offers in-person proofing so I can decide which facility I will visit.

**Acceptance Criteria**
GIVEN I am viewing the 'Select Site' screen on the Veteran Intake app
WHEN I enter a zip code
THEN I will see nearby facilities on the map
AND I will see the following information listed about each site below the map:
- facility phone number
- facility hours
- services offered (such as Veterans hospital, Medical Clinic, Emergency Services)

Questions/Notes:
- are we hardcoding pilot site? Yes - decision made. Hardcode for pilot.
- show first 3 sites within Little Rock vicinity: https://www.va.gov/find-locations/?address=Little%20ROck%2C%20Arkansas&bounds%5B%5D%5B%5D=-93.039595&bounds%5B%5D%5B%5D=33.996481&bounds%5B%5D%5B%5D=-91.539595&bounds%5B%5D%5B%5D=35.496481&context=Little%20Rock%2C%20Arkansas%2C%20United%20States&facilityType=health&latitude=34.746481&longitude=-92.289595&page=1&radius=38&serviceType&bounds%5B%5D=-93.039595&bounds%5B%5D=33.996481&bounds%5B%5D=-91.539595&bounds%5B%5D=35.496481

Additional future changes (will create a separate story for this post-pilot):
AND I will see the option to 'Verify at this site' with large radio buttons (instead of small)
AND I can click on the entire facility 'card' to select the site I want to choose (instead of just clicking on the radio button)

**Comment by lmorris3** [comment]
@mateoclarke updated this story post-Devign sync. Added the link you sent with the VA facilities near Little Rock, AR.

**Comment by mateoclarke** [comment]
Here are the top 3 sites in Little Rock:
https://www.va.gov/find-locations/?page=1&address=Little%20ROck%2C%20Arkansas&facilityType=health&serviceType&latitude=34.746481&longitude=-92.289595&radius=38&bounds%5B%5D=-93.039595&bounds%5B%5D=33.996481&bounds%5B%5D=-91.539595&bounds%5B%5D=35.496481&context=Little%20Rock%2C%20Arkansas%2C%20United%20States

**Comment by SophiaPhilipMO** [comment]
John L. McClellan Memorial Veterans' Hospital
4300 West Seventh Street
Little Rock, AR 72205-5446
Phone numbers
Main phone: 501-257-1000
Mental health care: 501-257-3092

**Comment by SophiaPhilipMO** [comment]
Little Rock VA Clinic - no mental health care number as services may not be provided at this site

**Comment by SophiaPhilipMO** [comment]
Eugene J. Towbin Healthcare Center
2200 Fort Roots Drive
North Little Rock, AR 72114-1707
Phone numbers
Main phone: 501-257-1000
Mental health care: 501-257-3092

**Comment by SophiaPhilipMO** [comment]
@mateoclarke dropped in the info I found via the link that Lauren shared

**Comment by SophiaPhilipMO** [comment]
@moanu404 reviewing, see alternative view of ticket on GH [here](https://github.com/department-of-veterans-affairs/va-in-person-identity-proofing/pull/45)
