### ISSUE TITLE
SOCKS access for Matthew Kelly

### ISSUE THREAD

**Issue by mathisto** [department-of-veterans-affairs/va.gov-team#76849]
### Your Name

Matthew Kelly

### Your Email

Matthew.Kelly7@va.gov

### Your GitHub Handle

mathisto

### Your Role and Team

Tech Lead for Lighthouse Benefits APIs Team

### Product Manager (PM) name and email

Michael Hobson (michael.hobson@adhocteam.us)

### Product Owner (PO) name and email

Janet Coutinho (jcoutinho@gmail.com)

### Access Type Requesting

developers

### Public SSH Key

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK35AmVXm/JHECWiDnUPgmTdxlWuYpfMy7oKpccjLfe1 mathisto@mccarthy

### E-QIP Transmittal Confirmation

![246487522-0db2bc45-408e-439d-8d6f-dff2438ec560](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8226466/3dbff689-b026-40d9-b5c7-d74e45d22b20)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by stoiven** [comment]
Key was merged, cleaning up.
