### ISSUE TITLE
Development-oriented Accessibility Feedback for Pre-Usability Review, Display of Facility-level alert

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va.gov-team#7688]
**Feedback framework**
- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Must

* The triangle or information "i" icons **must** have an `aria-hidden=”true” role=”presentation”` attributes so they won't become cursor stops and read out for screen readers. This **must** be applied in the search results and facility detail views. Also, if the opportunity exists, please check the community care provider views, they're a different template from the facility detail views.

## Should

* Team **should** review all messages for opportunities to write SR-only versions that are more descriptive, and answer questions like "What has limited services and hours?" or "What kind of notice?". This thinking is applied in the next Should item.

* **Should** connect the H2 with the notice, with screen reader only text to provide the equivalent of the icon, as well as the attributes to suppress the icon from being read for non-sighted users.

```diff
+        <h2 aria-describedby="must_be_a_unique_id">
            <a href="#">Portland VA Clinic 
            </a>
        </h2>
+         <p class="notification-style" id="must_be_a_unique_id">
+           <span class="usa-sr-only">Notice, this facility has </span> 
+           <i aria-hidden="true" role="presentation"></i>
           Limited services and hours
         </p>
```

    * An _alternate_ approach to relating the "Limited services and hours" and "Facility notice" text to the heading **link** in search results. This would be read out after the link name and a short pause. Would need to be tested with screen readers for accuracy, and IDs *must* be unique or there will be axe errors.

```diff
      <h2 class="vads-u-font-size--h5 no-marg-top">
+        <a href="/find-locations/facility/vha_674BY" aria-describedby="UNIQUE_ID_N">
          Austin VA Clinic
        </a>
      </h2>
      <p>
        <i aria-hidden="true" class="alert"></i>
+        <span id="UNIQUE_ID_N">Limited services and hours</span>
      </p>
```
* On the facility detail page, the H1 and notice **should** be connected as follows. If the team uses the alert box, the same sort of connection would be recommended.
    ```html
      <h1 aria-describedby="unique_id">Washington VA Medical Center</h1>
      <p id="unique_id">
        <div class="notification-style">
          <span class="usa-sr-only">This facility has</span>   
          <i aria-hidden="true" role="presentation"></i>
          Limited services and hours
        </div>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      </p>  
    ```

## Definition of done

1. Each item of feedback acknowledged with decision made in a comment.
1. VSA accessibility specialist will close this issue when the decisions are reviewed.

**Comment by 1Copenut** [comment]
VSP accessibility comments were previously sent to @jenstrickland and consolidated. No further guidance or comment.

**Comment by laflannery** [comment]
I think this is no longer relevant.  Will close in 1 week unless told otherwise
