### ISSUE TITLE
IPP Pilot Timeline and Budget

### ISSUE THREAD

**Issue by lmorris3** [department-of-veterans-affairs/va.gov-team#76899]
Develop a detailed timeline and budget for the IPP Pilot, focusing on the tasks needed to complete leading up to the pilot and the lead time for each. Purpose is to have a doc to share with Tom to align on tasks and uncover anything missing with plenty of time ahead of pilot.

[Timeline](https://docs.google.com/document/d/1gDT_VH5PKGPkl01kTzoWczXmznjqkwQhzMjXsMvLgNg/edit)

[Budget](https://docs.google.com/spreadsheets/d/1r4yWTD89YCuPt95-y47l7Ya1AfFVm82Nv1-fb8Wcupo/edit#gid=0)

[Travel estimate](https://docs.google.com/spreadsheets/d/1BYEAUTPufDcOKEHa93A5rGBkv3PLb2rS/edit#gid=1338652538)

[Justification](https://docs.google.com/document/d/1Y_ayaCgSxLUx96OG9qlW8rkobI56-O0q2DBzLfSTCyI/edit)

**Comment by SophiaPhilipMO** [comment]
@lmorris3 updated with links to the docs you've created

**Comment by lmorris3** [comment]
@SophiaPhilipMO thank you! Closing as complete.

**Comment by SophiaPhilipMO** [comment]
Updating to Fayetteville sites

**Comment by SophiaPhilipMO** [comment]
Adjusting to May 19-May 24

**Comment by SophiaPhilipMO** [comment]
[Final estimate](https://docs.google.com/spreadsheets/d/1Hc1jN1AvB1rIif1FZGa9cobXx8e9w6Cv/edit#gid=1338652538) for Fayetteville, AR
