### ISSUE TITLE
Midpoint Review - Content - Modernized Check-in, eCheck-in, Mileage-only Travel Claim Submissions for VA Facilities that use Oracle Health EHR Software

### ISSUE THREAD

**Issue by rferguson13** [department-of-veterans-affairs/va.gov-team#76907]
## Next Steps for the VFS team

- [x] **Assign** this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] **Comment** on this ticket:
  - If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members`.
- [ ] **Close the ticket** when all feedback has been addressed.

## Thoughts/questions
Overall, this looks really good. I know the content isn't finalized through CAIA yet, but little tweaks will make a big difference. Please let me know if you have any questions. 

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

### Must
- In general, it’s not always clear when the user has to file a claim by the end of that day vs. 30 days. CAIA can help with this, but the distinction should be made clearer. There are several ways the writer could do this. One way would be to emphasize “this tool” versus the other process - and then be sure to name that other process or point to a link. Little tweaks will make huge clarity differences. 
- There is some incorrect bolding used throughout the form. [The Style Guide has guidelines for usage](https://design.va.gov/content-style-guide/bold-text). Specifically, we don’t use bolded text words to emphasize a point being made in the text. So, the following text wouldn’t align with the Style Guide: “But you can file your claim online, **within 30 days**, through the….” Please review and revise the bolding usage through the flow. In general, when in doubt, you probably don’t bold it.
- ID Auth page - The user finds the following sentence in the first paragraph: “File a travel reimbursement claim if you meet eligibility for health care travel reimbursement.” This is very wordy and doesn’t fit plain language standards. Consider revising it so it’s simpler. There are several ways the writer could do this. For example, they could write: “File a travel reimbursement claim if you’re eligible for health care travel reimbursement.”

### Consider
- ID Auth / Failed match 4th attempt - Is there something else the Veteran can do? They get directed to an article, but should they contact someone? They may be stuck and it’s unclear how they can move forward. Consider adding a little bit more context to the next steps. 

## Notes
Thank you again for the opportunity to review this work. Please continue working with CAIA to develop the content. 

## Governance team actions
- [ ] Format feedback as individual tasks (check boxes)
- [ ] Assign this ticket to the VFS team member that opened the Slack request
- [ ] Add the VFS team product label
- [ ] Add the VFS team the feature label (if applicable)
- [ ] Add the touchpoint labels
- [ ] Add the practice area labels
- [ ] Add the Collaboration Cycle initiative milestone
- [ ] Add the Collaboration Cycle initiative epic

**Comment by benbrasso-agile6** [comment]
- Completed updates to add "this tool" to better distinguish from BTSSS. Example: https://www.figma.com/file/pnR05o7NPJDS0KFUSQ0eE3/Check-in-%7C-Check-in?type=design&node-id=599-2305&mode=design&t=59uAGglKs5P8F8Cc-4
- Updated content to meet bolding guidelines. E.g., kept the most important information and first sentence bolded; nothing else. https://www.figma.com/file/pnR05o7NPJDS0KFUSQ0eE3/Check-in-%7C-Check-in?type=design&node-id=507-8049&mode=design&t=59uAGglKs5P8F8Cc-4
- Updated ID auth page content for plain language suggestion - https://www.figma.com/file/pnR05o7NPJDS0KFUSQ0eE3/Check-in-%7C-Check-in?type=design&node-id=507-4579&mode=design&t=59uAGglKs5P8F8Cc-4
- Added more context to 4th attempt LoROTA page - https://www.figma.com/file/pnR05o7NPJDS0KFUSQ0eE3/Check-in-%7C-Check-in?type=design&node-id=507-4601&mode=design&t=59uAGglKs5P8F8Cc-4
