### ISSUE TITLE
Qualitative Data Request: Debt Portal (1 week)

### ISSUE THREAD

**Issue by charlottecesana** [department-of-veterans-affairs/va.gov-team#76901]
### Data Type Requested

User Surveys

### Data Source Type

Medallia

### Date Range Start

02-14-24

### Date Range End

02-22-24

### Product Name(s)

Debt Portal

### Product Description

Hi @newworld2616 ! We would like to request a one-time debt portal data request due to recent emails that went out. Please also send the regular recurring monthly reports at the end of the month. Thank you in advance!

### Survey URL(s), key term(s), case category or type

https://va.gov/manage-va-debt/
https://va.gov/manage-va-debt/summary
https://va.gov/manage-va-debt/summary/copay-balances
https://va.gov/manage-va-debt/summary/debt-balances
https://va.gov/manage-va-debt/summary/debt-balances/details/
https://va.gov/manage-va-debt/debt-balances/letters

Links that are collecting Medallia data with custom URLS:
[https://www.va.gov/manage-va-debt/summary/debt-balances/details/{selectedId}](https://www.va.gov/manage-va-debt/summary/debt-balances/details/%7BselectedId%7D)
[https://www.va.gov/manage-va-debt/summary/copay-balances/${selectedId}/detail](https://www.va.gov/manage-va-debt/summary/copay-balances/$%7BselectedId%7D/detail)
[https://www.va.gov/manage-va-debt/summary/copay-balances/${selectedId}/detail/statement](https://www.va.gov/manage-va-debt/summary/copay-balances/$%7BselectedId%7D/detail/statement)

### File Delivery Format

One file, different tab for each term/URL

### Word Cloud

Yes

### VA Email Address(es)

charlotte.cesana@va.gov, denise.coveyduc@va.gov, megan.crigger@va.gov, joseph.lee9@va.gov

### Add Assignee and Labels

If not already done so, please ensure @newworld2616 is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by newworld2616** [comment]
Hi, I have shared the requested data. Thank you!
