### ISSUE TITLE
Draft ID.me user choice portal release notes

### ISSUE THREAD

**Issue by lmorris3** [department-of-veterans-affairs/va.gov-team#76900]
ID.me is releasing a new feature, the "user choice portal" for identity verification. They are also removing the knowledge based verification (kbv) path that asks users for credit history info as a verification path. 

We need to draft release notes that can be used to inform a broad range of audiences about the change. The release notes should include as many details as possible. Can use a VA release notes template or a Google search as a guide.

Release notes should include

- [x]  images of what's changing
- [x]  description of the change (before and after)
- [x]  who will be affected
- [x]  when it will release (if unknown, can sub in "soon")
- [x]  what to do for support
- [x]  suggestions for updating documentation or current scripts/user guides for other VA teams
- [x]  use the release notes to update the slide in the MHV coordinator presentation as well

**Comment by CarlDickerson** [comment]
@lmorris3 please review: https://docs.google.com/document/d/1llJeh8NnnupOXvG9gZ8yFdHzJmWJnZMv5wE2UAQJN3E/edit?usp=sharing

**Comment by lmorris3** [comment]
reviewed and made comments @CarlDickerson
