### ISSUE TITLE
AWS access for Derek Fong

### ISSUE THREAD

**Issue by dfong-adh** [department-of-veterans-affairs/va.gov-team#76911]
### COR Name

Other - please specify in 'Additional Notes'

### Vendor Onboarding Representative Name

Other - please specify in 'Additional Notes'

### Your Name

Derek Fong

### Your Email

derek.fong@adhocteam.us

### Team, Role, and Company of the target individual

Benefits Decision Reviews, Software Engineer, Adhoc

### Product Manager (PM) name and email

Sade Ragsdale, sade@coforma.io

### Product Owner (PO) name and email

Zach Goldfine, zachary.goldfine@va.gov

### Desired AWS Access

I recently joined the VA Benefits team 1 (Decision Reviews) and need similar AWS access to @data-doge (Eugene Lynch) that was granted in https://github.com/department-of-veterans-affairs/va.gov-team/issues/46302 to develop features and investigate bugs on the vets-api and vets-website apps.

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/151783381/41eb2b22-994f-43d4-a7ae-ce31e0c01cd5)

### Additional Notes

COR: Keith Riley
VOR: Jeff Langworthy

I will need ongoing access in order to develop features and investigate bugs

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [x] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by HeatherWidmont** [comment]
@dfong-adh hi there! Was the work on this completed? If so, what is the estimate?

**Comment by dfong-adh** [comment]
I don't think this should have been marked as complete as I don't think this is handled by our team (this is a platform access request to my understanding).

**Comment by ph-One** [comment]
(Found in Atlas)

**Comment by hgbarreto** [comment]
Access Granted - Temp credentials were passed to the user
