### ISSUE TITLE
Midpoint Review - Design Feedback - Benefits Dependent Experience, 21-686c/674, Critical Form Updates

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#76927]
## Next Steps for the VFS team

- [ ] **Assign** this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] **Comment** on this ticket:
  - If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members`.
- [ ] **Close the ticket** when all feedback has been addressed.

## Thoughts/questions

- Matt Dingee: The add a spouse feels like it has too many form fields in the multiple responses card. Consider a sub task flow instead.
- Matt Dingee: Check box tile options, if you feel like the text is helpful for users then you can use it.
- Matt Dingee: Most forms pre-populate the form with contact info and do not update profile. You could put a note in there to go to their profile to update the incorrect information instead of actually updating it on this form.
- Be sure to use v3 components when you get to staging.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- [x] Must: Update the checkbox tile with the correct styles when it is checked. You can find that information in [Storybook](https://design.va.gov/storybook/?path=/docs/uswds-va-checkbox--tile#stories).
- [x] Must: On the spouse's former marriage page, there are 2 dates, one for date of marriage and the other date marriage ended. Use one of the [v3 memorable date options](https://design.va.gov/storybook/?path=/docs/uswds-va-memorable-date--default). Also use memorable date for any DOB.
- [x] Must: Per our [content guidance for file upload](https://design.va.gov/components/form/file-input#content-considerations), use the word file instead of document. Also, the button should be Upload file.
- [x] Must: For the Add child [multiple responses](https://design.va.gov/patterns/ask-users-for/multiple-responses#how-to-design-and-build---single-page), add a save button. Also, you are missing step 3 in the [multi-page flow](https://design.va.gov/patterns/ask-users-for/multiple-responses#how-to-design-and-build---multi-page).
- [x] Must: CAIA has recently updated the placement of things (process list and then sign in alert) on forms intro pages. I will add the image below of the updated page. Reach out to CAIA if you have any questions about placement of things.
- ![295330483-9e58cd28-a90d-487a-ab8a-584f9bfb7a39](https://github.com/department-of-veterans-affairs/va.gov-team/assets/72398073/1df15135-b78a-4f58-b066-f2e3f24fe7ab)
- [x] Should: Allow them to add more than 1 child for the ages 18-23.

## Governance team actions
- [x] Format feedback as individual tasks (check boxes)
- [x] Assign this ticket to the VFS team member that opened the Slack request
- [x] Add the VFS team product label
- [x] Add the VFS team the feature label (if applicable)
- [x] Add the touchpoint labels
- [x] Add the practice area labels
- [x] Add the Collaboration Cycle initiative milestone
- [ ] Add the Collaboration Cycle initiative epic

**Comment by ajialeilani** [comment]
Hey @allison0034 a couple of questions: 

- I've been using Memorable Date with month select pretty exclusively. Is the simpler version preferred?
- Does the use of "file" rather than "document" apply to language on the [static intro pages](https://www.figma.com/file/7W55oNwdVXvXOTI9SaFzQ7/686c-Add-or-Remove-Dependents?type=design&node-id=319%3A47380&mode=design&t=zZNCaqwSBbrgYM7X-1) as well?

**Comment by ajialeilani** [comment]
All feedback either updated in Figma or added to Figma comments. Thanks!

**Comment by ajialeilani** [comment]
All feedback added to the [mockup](https://www.figma.com/file/7W55oNwdVXvXOTI9SaFzQ7/686c-Add-or-Remove-Dependents?type=design&node-id=713%3A74858&mode=design&t=AcIv03oHGZlFDriH-1). Thanks!
