### ISSUE TITLE
Yellow Ribbon MVP - Schedule Education stakeholder staging review

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#7692]
## Acceptance Criteria
Schedule 15 minute Zoom sessions with Education stakeholder to go through [this checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/yellow-ribbon-mvp/stakeholder-staging-review.md) and confirm functionality/data in our Yellow Ribbon Tool  

- [ ] Tammy Hurley
- [ ] Matt Self
- [ ] Luke Tickner
- [ ] Janice Fischer
- [ ] Joseph Welton

**Comment by andaleliz** [comment]
@kelsonic and @MickinSahni - thinking we can do these sessions in the next sprint.  Any reason we wouldn't want them to "kick the tires" yet?

**Comment by MickinSahni** [comment]
If it's a factual discrepancy, we'll address it. If it's subjective feedback, "we'll take it under consideration."

**Comment by andaleliz** [comment]
All interviews scheduled for 4/9/2020
