### ISSUE TITLE
[Post-MVP] Yellow Ribbon MVP - Improve UX when no results are returned

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#7694]
Currently the MVP tool displays the next `No results found.` when a search returns no results.  I'm concerned the no results message is 
a) not helpful, and 
b) getting lost in the typographical hierarchy somehow.
![Screen Shot 2020-04-06 at 8 35 40 AM](https://user-images.githubusercontent.com/55992116/78614176-d9c21400-783b-11ea-9c1e-3aa43764325c.png)

Would like to explore improving the UX by updating the copy and/or the layout and styling.

**Update 4/13**
Recommendation based on LOE to implement is to change language to
`h2` reads **No schools found for your search criteria**
`<p>` reads `To find participating schools`
`<ul>` reads 
  - double check your spelling 
  - Try fewer search terms 
  - Try more general search terms

Will add screen when we can move forward with this work.

## Acceptance Criteria
- [ ] Document recommendations in GH repo folder
- [ ] Create wireframe reflecting updated messaging.

**Comment by andaleliz** [comment]
@kelsonic did some thinking on this earlier today.  Nothing for you to do yet, but would love your input.  I have 3 options I'm noodling on, and I think only the first would be an approach that would fit in our `MVP` approach; the other two I think would be more effort and perhaps something for a future iteration. Let me know what you think. I know we need to launch this thing and don't want to complicate work any further.

### Option 1
I explored is to update the copy, something like what is shown below.  Jen S. had some great feedback about how to make it more accessible, so I'd need to work on this some more.  
![Screen Shot 2020-04-06 at 8 46 11 AM](https://user-images.githubusercontent.com/55992116/78614278-29a0db00-783c-11ea-98e5-b9e284b43666.png)

### Option 2
We use some kind of skeleton, to set the users expectation for what they would see if they got a result. Using a version of the cards you'd see in a search result. 
![Screen Shot 2020-04-06 at 7 35 07 PM](https://user-images.githubusercontent.com/55992116/78614841-c617ad00-783d-11ea-87bd-45a3e6b4a7fc.png)

### Option 3
Update the layout to use the 2 column we use on other pages on the site with the "left nav" space.  I think this would also help the transition from the landing page to this search results feel less awkward but not totally sure, and I think this one is more of a "let's try this next version" solution.
![Screen Shot 2020-04-06 at 7 35 14 PM](https://user-images.githubusercontent.com/55992116/78614935-09721b80-783e-11ea-97dd-4e553f6cf58f.png)

**Comment by kelsonic** [comment]
@andaleliz Options 1 and 2 I'm happy to do! I believe making it look like a search result is a little confusing, but I'll leave it up to you! 🙂 

Option 3 would require significant rewriting of the markup and I'm confident it'd be difficult markup-and-styling-wise to have a good mobile design with the change

**Comment by andaleliz** [comment]
@kelsonic thank you so much for the input! That's what I suspected about option 3.  I think option 1 would be the simplest route to go so I'll add a screen for that to the prototype + let you know when it's ready for the next sprint.  Gracias!!

**Comment by kelsonic** [comment]
Closing this as @jenniferlee-dsva mentioned what we have currently suffices! 🙂

**Comment by kelsonic** [comment]
Just kiddinggggg https://github.com/department-of-veterans-affairs/va.gov-team/issues/7709#issuecomment-614903779

**Comment by andaleliz** [comment]
@kelsonic do you need a separate wireframe to make this update? Option 1 in this issue is what the recommendation would be. I can drop it in an InVision link if needed.

@stephorkandatx one of the AC here is to document the recommendation in the GH repo, but not sure where that would be at this stage of the work. I realize this was before you joined the team, so happy to follow whatever is best for us today vs when this was written up.

**Comment by kelsonic** [comment]
@andaleliz Yes please! 🙂

**Comment by andaleliz** [comment]
Cool. I created a new issue to cover the implementation of this, whenever it is determined to be an appropriate time. Closing out the UX portion of this.
