### ISSUE TITLE
Update Search Best Bet/Top Recommendation for Find VA Forms Search

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#7695]
## Background
Currently, a search for "forms" on VA.gov on-site search results in a Top Recommendation leading to the legacy forms search experience. 
We should update these recommendations so it's easier for Veterans and others to find the new experience. 

## Tasks
- [x] Add/update Top Recommendations for VA.gov's on-site search for "forms", "form" to point to new experience

## Acceptance Criteria
- Top Recommendations on VA.gov's on-site search updated to reflect new Find VA Forms - Search experience url

**Comment by ncksllvn** [comment]
I think we can unblock this. Just two lingering questions (echoed from Slack) -

1. We still have a link to `/vaforms/` in the footer.
1. No redirects are in place from `/vaforms/`

This issue and the two items above are both unblocked and actionable, just a question of timing - when do we know we're good to go for full launch?

**Comment by jenniferlee-dsva** [comment]
Replying... to ^: 

`We still have a link to /vaforms/ in the footer. `
 - I'm okay with this temporarily. I don't think the chance is high that a user will land on the modern forms search page and click on the footer link. So per the release plan, let's add the /find-forms to the search.gov top bets (replacing /vaforms in the current top bets) for the term "forms" and "va forms."

- That said, it might be weird if someone tries to go back to the forms search later from the footer but ends up on the legacy forms search. Could we include a notification on the legacy search page, letting ppl know that there is a 'preview'/beta modern experience, so ppl who go to legacy search via footer link, have a way to get to modern page if they choose to? I would implement this AFTER adding modern forms search to the search.gov top bets - particularly if we're not seeing traffic to meet that 300 users threshold to do the redirects. 

`No redirects are in place from /vaforms/`
- Agree. Per release plan, let's wait until we've seen 300 users on the modern forms page without logging any weird errors. Then we can implement the redirects per [ticket #5163 ](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/5163). (Includes a handful of URLs.)

**Comment by ncksllvn** [comment]
> I'm okay with this temporarily. I don't think the chance is high that a user will land on the modern forms search page and click on the footer link. So per the release plan, let's add the /find-forms to the search.gov top bets (replacing /vaforms in the current top bets) for the term "forms" and "va forms."

Sounds good, will do!

> That said, it might be weird if someone tries to go back to the forms search later from the footer but ends up on the legacy forms search. Could we include a notification on the legacy search page, letting ppl know that there is a 'preview'/beta modern experience, so ppl who go to legacy search via footer link, have a way to get to modern page if they choose to? I would implement this AFTER adding modern forms search to the search.gov top bets - particularly if we're not seeing traffic to meet that 300 users threshold to do the redirects.

Hm, so since that is a legacy page, our only method of interacting with it is through our injection script, that we use for the header/footer and redirects. I don't think it would be worth trying to inject this message to the page...My thinking -

1. If it's possible for the Teamsite page owner to add the message there directly, that could be the easiest route
1. We could create a Flipper feature toggle that redirects from `/vaforms/` to `/find-forms/` when enabled, and vice versa when not enabled. We'd just need some time to set that up.

**Comment by jenniferlee-dsva** [comment]
Hi @ncksllvn - good points. I wasn't actually thinking about a redirect on/off function however. I was thinking perhaps something similar to what we implemented on the legacy Pittsburgh VAMC site. But now that I recall, I think that the Pittsburgh team added that messaging on their page (at our request). 

Okay, let's table this for now. I'll do a little more digging to see what's possible on the legacy page. It doesn't really even look like they have an alert or messaging mechanism at a glance.
