### ISSUE TITLE
[Design] 10-10 Figma Migration - Add Figma links to recent projects in Github

### ISSUE THREAD

**Issue by aagosto90** [department-of-veterans-affairs/va.gov-team#76955]
## Issue Description
We recently ported all of our team's design files from Sketch over to Figma and will be using Figma going forward. Since we no longer have access to Sketch, the old links in our Github documentation will be broken. Rather than going through all of our Github documentation to replace Sketch links, we'll create a table in the product brief for all projects we've worked on in the last couple of years to surface the latest Figma links. We'll also add a page in the UX team's Github folder to gather all Figma links in an organized table view.

---
## Tasks
- [x] Create a Github markdown list/table of the pages with Figma links for recent projects in Github within the product briefs for each project
- [x] Create a central Github markdown list/table with Figma links in Github within the UX team's documentation

## Acceptance Criteria
- There is a source of truth in Github of the Figma links for projects the health enrollment team has completed in the past 2-3 years within the project briefs and in the UX team's dedicated folder.
---

**Comment by hdjustice** [comment]
@aagosto90 Can you add an estimate to this effort please?  Thank you!

**Comment by jessicastump** [comment]
Created a [markdown file here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/ux-team/figma-links.md) in the ux team folder. We can chat later as a team if a different place in the folder organization makes more sense for this :) 
We can create a table for each product and have a column for Figma page name/link and one for ticket number/link, maybe a separate table for things in the archive folder or that don't have ticket numbers?

**Comment by aagosto90** [comment]
[Github link for Figma links within UX documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/ux-team/figma-links.md)

**Comment by hdjustice** [comment]
I love this!  I know it is labor intensive and I appreciate all the work that goes into this organization.
