### ISSUE TITLE
VSP QA feedback on Display of Facility-level Alert [Usability Testing Prep]

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#7696]
## VSP QA feedback on Facility-level Alert [Usability Testing Prep]

**Regression Test Plan:**
Not applicable

**Manual Functional Test Plan:**
https://dsvavsp.testrail.io/index.php?/plans/view/245

## Feedback
**Regression Tests:** 
1. Verification of unchanged facility types is included in the manual test plan -- that works!

**Manual Functional Tests:**
1. Test runs for Firefox and Chrome on macOS and Windows are present.  Consider including a test run for IE11 and/or Edge.  As of this morning, the [top 5 browsers](https://analytics.google.com/analytics/web/#/report/visitors-browser/a50123418w177519031p176188361/) site-wide are -- 
<img width="246" alt="Screen Shot 2020-04-07 at 10 48 32 AM" src="https://user-images.githubusercontent.com/52456633/78683496-5b0dbb00-78bd-11ea-8863-8a4833a37ad2.png">

1. **T2140 -- Mobile Navigation** appears to be a test case targeting mobile and should probably not be included in your general Windows or macOS test runs.
1. **T2068 -- [dummy]** appears to be an empty test case container which doesn't need to be in your test runs.
1. Consider populating _References_ field with links to user stories containing the relevant acceptance criteria where possible.
1. Overall, a great test plan!  Great use of screen shots for expected display of UI elements.  Good logical separation of verifications into test cases.

## Definition of Done
- [ ] Acknowledge each item of feedback with a decision
- [ ] VSP QA will close ticket after reviewing feedback decisions

**Comment by mmiddaugh** [comment]
Thanks @pjhill 
Manual Functional Test feedback:
Test runs for Firefox and Chrome on macOS and Windows are present. Consider including a test run for IE11 and/or Edge.  _Adjusted the browsers (Firefox was a misfire, I think)_
T2140 -- Mobile Navigation appears to be a test case targeting mobile and should probably not be included in your general Windows or macOS test runs. _Agree but can't see where this is occurring or how to fix it._ 
T2068 -- [dummy] appears to be an empty test case container which doesn't need to be in your test runs. _I think this test case was created by @tlei123_ 
Consider populating References field with links to user stories containing the relevant acceptance criteria where possible. _Linked the GitHub issue as a reference (thank you for the reminder!)_

**Comment by pjhill** [comment]
> Thanks @pjhill
> Manual Functional Test feedback:
> Test runs for Firefox and Chrome on macOS and Windows are present. Consider including a test run for IE11 and/or Edge. _Adjusted the browsers (Firefox was a misfire, I think)_
> T2140 -- Mobile Navigation appears to be a test case targeting mobile and should probably not be included in your general Windows or macOS test runs. _Agree but can't see where this is occurring or how to fix it._
> T2068 -- [dummy] appears to be an empty test case container which doesn't need to be in your test runs. _I think this test case was created by @tlei123_
> Consider populating References field with links to user stories containing the relevant acceptance criteria where possible. _Linked the GitHub issue as a reference (thank you for the reminder!)_

Awesome -- thanks for addressing everything.

Regarding T2140:  It's popping up in your *Let Nav Upgrade* section -- 
![Screen Shot 2020-04-07 at 2 46 23 PM](https://user-images.githubusercontent.com/52456633/78707518-b56b4380-78de-11ea-9d98-a446b6f5b4ae.png)
If you want only include certain sections in a test plan you'll need to limit the test cases that you're including in your test plan to some subset of all the test cases available to that project.  You can select subsets of your test cases by clicking *TEST RUNS & RESULTS* from the tabs at the top of TestRail -- 
![Screen Shot 2020-04-07 at 2 50 08 PM](https://user-images.githubusercontent.com/52456633/78707878-37f40300-78df-11ea-8b6a-529ab3415f9b.png)

Clicking *Edit* for your test plan
![Screen Shot 2020-04-07 at 2 50 08 PM](https://user-images.githubusercontent.com/52456633/78707979-6376ed80-78df-11ea-888f-0420fb31f1b2.png)

And using the *select cases* button to pick some subset of all the test cases available in your project.
![Screen Shot 2020-04-07 at 2 50 23 PM](https://user-images.githubusercontent.com/52456633/78708056-80abbc00-78df-11ea-9c2d-51ca16f4a439.png)
