### ISSUE TITLE
Requesting assistance from Backend to investigate ComponentLatencyWarning (api component not set in nginx_components.yml prod monitor-prod component warn) PagerDuty alert

### ISSUE THREAD

**Issue by bdech** [department-of-veterans-affairs/va.gov-team#76978]
Hi Backend

An alert has been frequently triggering in on-call and PagerDuty for [[FIRING:1] ComponentLatencyWarning (api component not set in nginx_components.yml prod monitor-prod component warn)](https://dsva.pagerduty.com/incidents/Q0YWO2PFJOZA2Z?utm_campaign=channel&utm_source=slack). 

Currently this [alert](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/OnCall/alerts.md#componentlatencywarning) is triggering multiple times per day going back at least a few weeks. This alert self-resolves in time but it has created a lot of unnecessary noise in the on-call channel. When someone has bandwidth available can you please investigate this alert? Please let me know if there is any help I can provide from my end.

**Comment by rmtolmach** [comment]
Investigating a bit and realizing this is more in the devops domain. But using my experience on the Infrastructure team to try to figure it out! 

The biggest offenders every time I check [this metric](http://prometheus-prod.vfs.va.gov:9090/prometheus/graph?g0.range_input=12h&g0.expr=sum(rate(nginx_http_request_duration_seconds_bucket%7Bapp!~%22ewis-apps%7Cewis%22%2Ccomponent!~%22address%7Cappeals%7Cauth%7Cclaim_attachments%7Cclaim_documents%7Cevss_claims%7Cfacilities%7Cfhir%7Chealth_care_applications%7Cletters%7Cloan_guaranty%7Cmessaging%7Cpost911_gi_bill_status%7Cprescriptions%7Csearch%7Cssoe_signin%7Cuser%7Cvba_documents%7Cvba_documents_content%7Cprofile%7Cvaos%7Cmobile.*%22%2Cjob%3D%22revproxy%22%2Cle%3D%222%22%7D%5B1m%5D))%20BY%20(app%2C%20component)%20%2F%20sum(rate(nginx_http_request_duration_seconds_count%7Bjob%3D%22revproxy%22%7D%5B1m%5D))%20BY%20(app%2C%20component)%20*%20100&g0.tab=0) are app: `services` and components: `veteran` and `claims`
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/10993987/e3f160aa-12b1-49bd-9432-535553850540)

Based on the query, I saw it was this [ComponentLatencyWarning](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/prometheus/rules/application.rules#L87-L94) which connected to this section of [nginx_api_server.conf.j2](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/templates/nginx_api_server.conf.j2#L216-L219). The components are kong_components and when I look those up in [nginx_components.yml](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/vars/nginx_components.yml#L39-L54) both `veteran` and `claims` are listed as `kong_components`! Kong is "an API gateway that sits in front of the public-facing Lighthouse APIs and does some API management (rate limiting, API key management, etc)" ([source](https://dsva.slack.com/archives/C04CYC4LMU6/p1709235369161669?thread_ts=1709234974.046809&cid=C04CYC4LMU6)). Going to reach out in #lighthouse-infrastructure.
