### ISSUE TITLE
VFS Custom Events for [Team Name] & [Product(s)]

### ISSUE THREAD

**Issue by Blivaditis** [department-of-veterans-affairs/va.gov-team#76986]
# VFS Custom Event Form

### What this form is for.
In prepration for the migration to GA4, we need information on _all_ custom events used by your products so we can continue to track them.

> [!IMPORTANT]
> Please complete this form with the related spreadsheet included as soon as possible, but no later than **Friday, April 5.** The final deadline where Universal Analytics will stop collecting data is **June 30, 2024**, so we are trying to ensure tracking coverage _well_ before that date.

Please reach out to the **#_vfs-analytics_** Slack channel if there are any questions.

---

### Instructions:
- **Step 1:** Download [this Excel file](https://github.com/department-of-veterans-affairs/va.gov-team/files/14388789/TEMPLATE.-.Custom.GA.Events.-.TEAM.NAME.HERE.xlsx).
- **Step 2:** Follow the instructions on the spreadsheet, filling out all required information on the two tabs:
    - Instructions & Team Info
    - Custom Events
- **Step 3:** Once completed, attach the Excel file to this ticket.
- **Step 4:** Include your team and product names within the **Title** of this form.
- **Step 5:** Submit this form.

_Our team will follow up with you for next steps._

 > [!NOTE]
> If your team manages more than one product, you can submit this form multiple times, or alternatively, include multiple copies of the spreadsheet to the same Github form. Whichever option is easiest.

**Comment by johnny-jesensky-adhoc** [comment]
Confirming this test worked.
