### ISSUE TITLE
Midpoint Review - IA Feedback - Benefits Dependent Experience, 21-686c/674, Critical Form Updates

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#76980]
## Next Steps for the VFS team

- [x] **Assign** this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] **Comment** on this ticket:
  - If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members`.
- [ ] **Close the ticket** when all feedback has been addressed.

## Thoughts/questions

-

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

### Must
- [x] **If LOA3 authentication is required, provide meaningful errors for LOA1 users** This is something we've started to check on recently with teams who are creating authenticated experiences. Are users required to have LOA3 level access for this form? If so, please ensure that if folks log on and only have LOA1 account access there is a meaningful error message for those folks to know what to do to proceed. My VA does this currently and is a good example.
![Screenshot of verification requirement for My VA](https://github.com/department-of-veterans-affairs/va.gov-team/assets/755248/9f77856f-b3a6-46cc-b223-b21a0337df9f)

- [x] **Page title parity:** The form's current breadcrumb, `<title>` tag and `<h1>` should be the same text. Currently they're all a little bit different.

- [x] **Add intermediary screen before commencing multi-page list and loop** On the [Add children < 18 sequence](https://www.figma.com/file/7W55oNwdVXvXOTI9SaFzQ7/686c-Add-or-Remove-Dependents?type=design&node-id=400-92089&mode=design&t=MsWSfwaEmd7erIsb-4) that is using the [multi-response multi-page pattern](https://design.va.gov/patterns/ask-users-for/multiple-responses#how-to-design-and-build---multi-page), it's missing the text between the initial data entry and the detail screens, “Now we’re going to ask you some follow-up questions about each of your [items]. We’ll go through them one by one.” This is a crucial part of the flow that helps users understand what to expect on the next screens.
<img width="488" alt="291951002-4c07e1da-31a5-407c-8a3e-4f1b29aa5e50" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/755248/e76a18e6-9821-494f-b98f-91acd13e23a3">

### Should

- [x] **Clarify "parent" language on stepchild screen:** the [add a stepchild screen](https://www.figma.com/file/7W55oNwdVXvXOTI9SaFzQ7/686c-Add-or-Remove-Dependents?type=design&node-id=446-95875&mode=design&t=MsWSfwaEmd7erIsb-4) asks for parent’s info. It's unclear what info is expected here. Is the form asking for the spouse's information, or another legal parent of the child? What if this information is not known?

- [x] **Subtitles on each page** - most of the form screens have a subtitle (an `h3` or `h4` that briefly describes the form fields on the page. For some of the `school age child` screens (name, marriage government funding) there isn't a subtitle, but it would be helpful, and be consistent with the other screens.

        
### Consider
- [x] **Flows for "What do you want to do" question:** I love the simplified flow in solution 2 for the "what do you want to do" question - consolidating the "Add a child" features and following it up with a few additional questions to help route users through the flow. Hopefully it will help reduce confusion for people adding children to their benefits. That said, if the team pursues this option for adding children, the same option should be presented for removing people, as the list of possible tasks to complete is unbalanced - with two broad "add" options and five very specific "remove" options:
![Screenshot 2024-02-23 at 12 53 09 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/755248/12b8fdc2-6cb9-4bb4-b0d1-c4837347d671)

- [x] **Student tuition being paid by a govt agency question** - Does the [government funding question](https://www.figma.com/file/7W55oNwdVXvXOTI9SaFzQ7/686c-Add-or-Remove-Dependents?type=design&node-id=446-105997&mode=design&t=MsWSfwaEmd7erIsb-4) include or exclude aid from the VA? Can we specify to only include non-VA support, as we do later on in the student income section of the form ("Do not report VA benefits")?
![Screenshot 2024-02-23 at 1 41 54 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/755248/e4b1a5fa-3790-4d6c-bf10-5cdfe946afd4)

## Governance team actions
- [x] Format feedback as individual tasks (check boxes)
- [x] Assign this ticket to the VFS team member that opened the Slack request
- [x] Add the VFS team product label
- [ ] Add the VFS team the feature label (if applicable)
- [x] Add the touchpoint labels
- [x] Add the practice area labels
- [x] Add the Collaboration Cycle initiative milestone
- [x] Add the Collaboration Cycle initiative epic

**Comment by ajialeilani** [comment]
I've implemented "musts" in the [mockup](https://www.figma.com/file/7W55oNwdVXvXOTI9SaFzQ7/686c-Add-or-Remove-Dependents?type=design&node-id=8%3A9&mode=design&t=zZNCaqwSBbrgYM7X-1) and added "Shoulds" and "Considers" as comments to work out the best solutions with CAIA.
