### ISSUE TITLE
Update OMB info on Intro Page

### ISSUE THREAD

**Issue by buddhima-coforma** [department-of-veterans-affairs/va.gov-team#76990]
## Description 

What's Currently shown is inaccurate. This needs to be updated:
<img width="649" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHlJQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--06db293e0bb8241cc74cf35c5c652575d635ffff/image.png" alt="image.png" />

## Tasks

Update info on Intro page to display the following:
* Respondent Burden: 30 minutes
* OMB Control No. 2900-0002
* Expiration Date: 08/31/2025

I'm pulling that from the pdf linked on our About VA Form 21-527EZ page (https://staging.va.gov/find-forms/about-form-21p-527ez/)

**Comment by mjb-coforma** [comment]
<img width="1646" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGF6QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--41ad1e3e843e9470c79db1e22b5f993351c6303e/image.png" alt="image.png" />

This appears to be fixed to match the PDF version of the 21-527EZ form.  Good to go.

**Comment by mjb-coforma** [comment]
@aplatt-coforma Are we good to close this ticket? Thanks, MJB

**Comment by aplatt-coforma** [comment]
@mjb-coforma - yes good to close. 
Feel free to go ahead and close any ticket you test/verify. I like to include a screenshot of the change just as you provided above. Thanks for helping to test these tickets.
