### ISSUE TITLE
[Documentation] Google Tag Manager - Publish Audit

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#770]
## User Story
As an Insights team member, I need to know that the current Google Tag Manager publish users are up-to-date active users so I can know that our data is secure.

## Goal
Audit current GTM Publish users to remove inactive users.

## Acceptance Criteria
- [ ] Groom current GTM users
- [ ] Remove inactive users from GA
- [ ] Request Ops to add GTM to offboarding list

**Comment by nedierecel** [comment]
@joanneesteban Also for lower priority, we should consider which users need to see the non-production Google Analytics properties. We can segment access to data based on user roles:

1. Product Managers and Owners - View Production and Non-Production data (for testing)
2. Engineering - Same as above
3. Content Producers - Production data

**Comment by joanneesteban** [comment]
Good call, @nedierecel !

**Comment by jonwehausen** [comment]
### 10/30/2020 Update
- Removed the following account at the Organization administrator level [here](https://marketingplatform.google.com/home/orgs/oXPY3GFFQwaHnjNHpFLyFg/settings?authuser=0): 
   - `ayaleloehr.va@gmail.com` -- _user was **deactivated** in Slack channels_
- The following outstanding access invitation was cancelled: 
   - `richard.harman@va.gov`
- The following accounts have had privileges lowered from **Publish** to **Read** and if present administrator privileges removed: 
   - `chapman.usds@gmai.com` -- _user was **deactivated** in Slack channels_
   - `tony.whittaker@adhocteam.us`
   - `mina@adhocteam.us`

Those folks who already had **Read** or **Edit** privileges (**without publish**) were unchanged. 

### Screenshot of current GTM users: 
![image](https://user-images.githubusercontent.com/48527022/97709887-690d6e00-1a91-11eb-9551-ad3a38fba5c3.png)

### Next Steps 
- [ ] Determine origin and current outstanding usage of `vetsdotgovanalytics@gmail.com` (our only remaining admin account) and sunset the account if it is determined there is no outstanding usage
- [ ] Determine origin and current users within [Org-level](https://marketingplatform.google.com/home/orgs/oXPY3GFFQwaHnjNHpFLyFg/accounts/account?accountObjectId=2uFLQELcQTyu-Au660mxhQ&product=2&folderKey=&authuser=0) connected account ID "UXA CSRA" and sunset

**Comment by jonwehausen** [comment]
Closing
