### ISSUE TITLE
Add ARP to Datadog Service Catalog

### ISSUE THREAD

**Issue by nihil2501** [department-of-veterans-affairs/va.gov-team#77004]
Use `accredited-representatives` to match this statement in our application controller:
```
# Add this `service_tag` to the Datadog Service Catalog.
#   https://app.zenhub.com/workspaces/accredited-representative-facing-team-65453a97a9cc36069a2ad1d6/issues/gh/department-of-veterans-affairs/va.gov-team/77004
# It will be the dd-service property for your application here:
#   https://github.com/department-of-veterans-affairs/vets-api/tree/master/datadog-service-catalog
service_tag 'accredited-representatives'
```

Need to review datadog requirements and determine if any additional work needs to be completed on the ARF side.

**Comment by gabezurita** [comment]
Seems like we'll need this before going to prod @nihil2501 and @a6marinos.

**Comment by gabezurita** [comment]
It seems as if this is a platform request. Submitted here:
https://dsva.slack.com/archives/CBU0KDSB1/p1724265056166569

> From 
> @Gabriel Zurita
> : Please add Accredited Representative Facing (ARF) as a team on Datadog so this team can be added as a new entry in the service catalog. Reference:
> * https://vagov.ddog-gov.com/organization-settings/teams?filter=
> * https://vagov.ddog-gov.com/services/settings/get-started?fromUser=true&sort=-fave%2C-team&start=1724261374879&end=1724264974879#team
> * https://github.com/department-of-veterans-affairs/vets-api/blob/c64fae2fa4e9024361ade8f41f4058f5659a5a7c/modules/accredited_representative_portal/app/controllers/accredited_representative_portal/application_controller.rb#L11

**Comment by gabezurita** [comment]
Done, added ARP to the DataDog service catalog! Will begin making dashboards now:
https://vagov.ddog-gov.com/services?query=service%3Aaccredited-representative-portal%20&env=%2A&fromUser=true&lens=Performance&view=list&start=1724273247054&end=1724276847054

<img width="1768" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0I0Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a619dc93e1eff288dc0ce7dc7ea671b0cfcf14cd/image.png" alt="image.png" />
