### ISSUE TITLE
Research and create Caddy script to enable local VPG integration 

### ISSUE THREAD

**Issue by drewconnelly** [department-of-veterans-affairs/va.gov-team#77019]
To completely integrate Mobile Application Platform (MAP) services with VetsAPI locally, user-service must be running alongside VPG and be addressable at the same root path.  In order to facilitate this, a proxy must be employed to stand up and resolve all MAP services behind a single address.

Caddy (https://caddyserver.com/) is a lightweight middleware that has been used successfully for this purpose on other MAP projects.  Investigate its use and develop a script to deploy all MAP resources necessary to test the VetsAPI -> appointment workflow behind a single gateway address.

**Comment by devin-mccurdy** [comment]
Uploaded Caddyfile to va.gov-team repo

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/appointments-oracle-health-integration/engineering/Caddyfile
