### ISSUE TITLE
Project Kickoff Education/ Career Counseling (CH36)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#7702]
## Steps to complete Project Kickoff
- [x] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in #vfs-platform-support in Slack; tag @ Megan Kelley @ AndreaHewitt
- [x] Andrea and Megan will schedule meeting with VSP reviewers and **eBenefits team** attendees (as listed below)
- [ ] VSP <> **requesting team** kickoff meeting completed
- [ ] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please bring the following to the kickoff meeting_
- Link to rough draft of [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/features/apply-CH36-VRE-counseling)
- Explanation of the problem space
- Any other artifacts you have so far
- You **do not** need to prepare a presentation

## Meeting attendees from **eBenefits team**
- Product Manager (required): **Jason Wolf - jwolf@governmentcio.com**
- DEPO Product Lead (required): **Steve Kovacs - steven.kovacs@va.gov**
- Entire VFS team (recommended): **James Adams** - jadams@governmentcio.com
**Jesse Cohn** - jesse.cohn@adhocteam.us
**Micah Chiang** - micah@adhocteam.us
**Kathleen Crawford** - kcrawford@governmentcio.com
**Derek Dyer** - ddyer@governmentcio.com

## Scheduling
Preferred dates or times: 
Afternoons to accommodate west coast participants, Fridays seem to work well for the most people.

**Comment by meganhkelley** [comment]
Scheduled for 4/10 ✅

**Comment by emilywaggoner** [comment]
Note: This form is similar to the Colmery Opt Out form in terms of length - check out the flow of that one here: https://staging.va.gov/education/opt-out-information-sharing/

**Comment by vbellissimo** [comment]
Cancelling/old task.
