### ISSUE TITLE
Discuss automating weekly report

### ISSUE THREAD

**Issue by SamStuckey** [department-of-veterans-affairs/va.gov-team#77022]
We've been running a weekly report every monday for a while to capture backup path failures.

We are holding steady at 0 (new) failure (types).  We should consider moving away from the weekly report to a DataDog based solution.  Discuss this with Steve and Emily, as we will need stakeholder buy in.

**Comment by sortizsh** [comment]
Steve and Sam will set up time to chat

**Comment by SamStuckey** [comment]
After meeting with Steve, the agreed state of this is that we probably can use existing submission job failure logs to create a dashboard, then set the sample set to 'weekly' and subscribe the appropriate people to the alerts.

[Pretty sure we actually used to have a monitor in place here that we could leverage](https://vagov.ddog-gov.com/monitors/158396?view=spans)
