### ISSUE TITLE
Adding [Michael Marinos] to DSVA Slack

### ISSUE THREAD

**Issue by hdbaines** [department-of-veterans-affairs/va.gov-team#77034]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

Michael Marinos is a new PM joining the VFS: Accredited Representative Facing Team

Are you requesting to add an individual as a: Full Member

- Full member
- Single guest
- Multi-channel
- Switching from single-channel to multi-channel?
- What channel(s) do they need to be added to?
-  benefits-representative-facing
- benefits-claim-evidence
- benefits-representation-engineering
- benefits-engineers-lighthouse-collaboration
- benets-portfolio
- benefits-representation-management
- all-rep-leads

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.

Michael Marinos is a new PM joining the VFS: Accredited Representative Facing Team . He needs access to the channels above

mike.marions@va.gov

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add [_insert email_] as a single-channel guest to [_channel name_].
- Please add [_insert email_] as a multi-channel guest to these channels: [_channel names_].
- Please add [_insert email_] as a full member.
- Please change the status of [_slack username_] from [_current status_] to [_desired status_]

**Comment by LEHigley** [comment]
this invite bounced back.

**Comment by LEHigley** [comment]
@hdbaines can i close this?

**Comment by hdbaines** [comment]
@LEHigley yes you can close this. Thank you
