### ISSUE TITLE
[Security] Peering Relationship

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#77049]
Security Team needs help with: 

https://app.zenhub.com/workspaces/platform-security-615c86f78b52bf0014e79606/issues/gh/department-of-veterans-affairs/va.gov-team-sensitive/1421

**Comment by npeterson54** [comment]
Security team needs help with: 
https://app.zenhub.com/workspaces/platform-security-615c86f78b52bf0014e79606/issues/gh/department-of-veterans-affairs/va.gov-team-sensitive/1421

**Comment by hgbarreto** [comment]
Possible POCs and procedure.

> He needs to submit a database scan request to the Security Assessment Portal (SAP)  and one of my database scanners will assist.  SAP is located here:Security Assessment Portal (va.gov)
> 
> Database POCs are Felix Hernandez or Joe Simon.

**Comment by hgbarreto** [comment]
This is currently waiting on a response from the `VA CSOC DB Scans` team.
Need the following information from that team:
We are looking for the following information to start.

    CIDR info
    ACCT ID (CSOC side)
    REGION (CSOC side)
    VPC ID (where CSOC wants to connect)

**Comment by npeterson54** [comment]
removing from sprint since it is blocked, will put back in when its unblocked

**Comment by ph-One** [comment]
Moved to next Sprint since @hgbarreto was on Support and heading up this effort

**Comment by hgbarreto** [comment]
Issues have been resolved - DB scans for Production are now complete.

Terraform to make these changes permanently will be handled in the ticket below
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/77048
