### ISSUE TITLE
[FE] 10-10EZR: Get Feature Flag access and do a refresh on how to use it

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#77045]
As a Dev, I would like access to the Feature Flag toggle and to do a refresher on how to do it so that our team can make updates to Prod as needed and not be dependent on one team member.

- [ ] Make sure you have Feature Flag access 
- [ ] Do a refresher on how to use it
- [ ] Review EZR toggle (currently at 10%)
- [ ] **Success: You are ready to roll EZR out to 25, 75, and 100%**

**Comment by mkerns1** [comment]
My Github Issue for Feature Toggle Access was approved.

Link to issue [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/77037).
