### ISSUE TITLE
Security [Database scans]

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#77048]
Security team needs help with  this:

https://app.zenhub.com/workspaces/platform-security-615c86f78b52bf0014e79606/issues/gh/department-of-veterans-affairs/va.gov-team-sensitive/1420

**Comment by hgbarreto** [comment]
Current plan is to leverage the existing `va-db-scan-sg` security group found [here](https://github.com/department-of-veterans-affairs/devops/blob/b53661e83bfa11207533da51794bd294273e2e33/terraform/environments/dsva-vagov-dev/security_groups.tf#L127)

**Comment by npeterson54** [comment]
removing from sprint since it is blocked, will put back in when its unblocked

**Comment by npeterson54** [comment]
Taking out of sprint since this is blocked

**Comment by ph-One** [comment]
Moved to next Sprint since @hgbarreto was on Support and heading up this effort

**Comment by hgbarreto** [comment]
Made changes manually to match newly merged IaC.
Terraform apply had a dependency error

**Comment by hgbarreto** [comment]
Work Complete.
