### ISSUE TITLE
SOCKS access for [Mark Schissler]

### ISSUE THREAD

**Issue by schisslerg** [department-of-veterans-affairs/va.gov-team#77067]
### Your Name

Mark (Gus) Schissler

### Your Email

gus.schissler@adhocteam.us

### Your GitHub Handle

schisslerg

### Your Role and Team

Product Lead on Public API Platform

### Product Manager (PM) name and email

Aubrey Suter, aubrey.suter@adhocteam.us

### Product Owner (PO) name and email

Peter Tebbenhoff, Peter.Tebbenhoff@va.gov

### Access Type Requesting

viewers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDA2rNl5sYpXg3S02/dLVqP3Hd9X7cBwbUjMFqTn646fZWZSi77mWYJUBibYL1J7qUVrd1x+/IeGAxt3vf7VphtbUcODUiR2Swh6q8ys3NP/BsaEi92+1qVCsEMOapP7N8tOQnwXP9R5LW6zyR0B9oH4juyWHLQuyxSl136SCFoM9/KJHO627Dcwn2apg6b34OTACmr6WJHz+JHT5Y1W98W1bubnsnQS7g6HBDgnva7Xl9lVaTppqKmBN9tPb90wAq4vyCe68yTo6d6YgMznRHQtqtuCH8tCWyx+/pcBAHaXX3gdw0ChAPf+lFoVvD43vxWBGXNugzHmuCLURikQ6XKz04Noc8XS3SYt//0OjOFN+L0ePlsSHF5mhWmL8i1KfTrK6GYOo3jOmD7PQ4QV3fcWCquVj4y0wq2456zO4lp9YNC4tEBPQsKFTcRk4C1mAseP1kvu5cmpLEjPxvhIzy3TpKLKWrDZwdCU2sUdqOh6/MDlEC121gZccVT4tbhvSs= gus@gus-C02GK49DMD6M

### E-QIP Transmittal Confirmation

Didn't fill out an E-QIP, but did fill out an e-App. Screenshot attached below.
<img width="808" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/119883772/9f82d352-8e7a-400c-8ad7-5cbc037dbdb4">

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by stoiven** [comment]
SSH key is merged.
