### ISSUE TITLE
Contact Center Review for [Decision Reviews Team, Board Appeal (Notice of Disagreement) VA Form 10182, Request an Extension Feature]

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#77077]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self-service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
*Board Appeal (Notice of Disagreement) VA Form 10182, Request an Extension Feature*

The latest version of the NOD form has two new fields, allowing Veterans to request an extension, provide a reason, and notify the Board of Veteran's Appeals if they're filing an appeal for a denial of VHA benefits. 

### Launch Date
*Please provide the launch or rollout date and details.*
- Canary (Veteran friends and family): Week of February 26th
- 10-25%: Week of February 26th
- 50-75%: Week of March 4th
- 100%: Week of March 11th

### Version Number
*Please provide the version number of the guide and/or video.*
Version 2

### Product Guide
*Please provide product guide link*
[Board Appeal (Notice of Disagreement) VA Form 10182](https://docs.google.com/document/d/1AMmE5b6qEAfeP4SXkFozT2-B6d0ZEsnC/edit#heading=h.gjdgxs)

## Acceptance Criteria
- [ ] Platform: Contact Center QA has been completed 
- [ ] Platform: Contact Center sends artifacts to appropriate contact centers
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) or the [Contact Center Review Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) on Platform website for more information about the Collaboration Cycle.

**Comment by starlow00** [comment]
Hi @saderagsdale. I need the guide in Word format for editing and the Sharepoint archival phase for VEO. Can you please attach a copy here?

**Comment by saderagsdale** [comment]
[DR.NOD-Submission-Form(VA-10182).Product.guide_v1.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/14423219/DR.NOD-Submission-Form.VA-10182.Product.guide_v1.docx)

@starlow00 Here ya go!

**Comment by starlow00** [comment]
Great, thanks @saderagsdale

**Comment by starlow00** [comment]
A question, @saderagsdale or @rubensun: Is it safe to assume that no PII is included in any images? It appears to use dummy data, although some images have redacted parts.

**Comment by saderagsdale** [comment]
@starlow00 Correct, no PII. Those are from staging with test user "Charde".

**Comment by starlow00** [comment]
Thanks, @saderagsdale 
The draft looks good; sending it for VEO review.

**Comment by saderagsdale** [comment]
@starlow00 Morning! Any updates? 👀

**Comment by starlow00** [comment]
No changes from VEO. Ready to go with the attached working copy. Please use it for [VA Form 10182 Notice of Disagreement product guide SRT 02272024.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNytzQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--30f589c4e707a77631993ec8f1a94a94d32914a9/VA%20Form%2010182%20Notice%20of%20Disagreement%20product%20guide%20SRT%2002272024.docx)
future revisions. Thanks!

[VA Form 10182 Notice of Disagreement product guide SRT 02272024.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOENzQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--061e9ef91f277e4ea1333be301e00ceeba3e881c/VA%20Form%2010182%20Notice%20of%20Disagreement%20product%20guide%20SRT%2002272024.docx)
