### ISSUE TITLE
deprecated github link

### ISSUE THREAD

**Issue by laucon** [department-of-veterans-affairs/va.gov-team#77071]
The Research and Design Overview Page leads to a deprecated github link where it says "Review the [Design checklist for the midpoint review and staging review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/design/design-checklist-for-usability-testing-and-staging-revi.md) to prepare your designs for the Midpoint review and Staging review meetings."

- [x] Reach out to Naomi for an answer
- [x] Delete the sentence that needs to be deleted

**Comment by jknipes** [comment]
Task finished, moving to _Done_
