### ISSUE TITLE
Figma access request: David Kennedy

### ISSUE THREAD

**Issue by davidakennedy** [department-of-veterans-affairs/va.gov-team#77079]
### Name

David Kennedy

### Email

david.kennedy@adhocteam.us

### Role

Designer, Accessibility

### Team

Decision Reviews and Benefits Management Tools

### Product Manager (PM) name

Sade Ragsdale & Jacob Worrell

### Additional Notes

I need edit access to Figma files so I can create accessibility annotations in files and help designers with designing accessible solutions.

**Comment by naomimarcussen** [comment]
Hi! You've been upgraded to full access.
