### ISSUE TITLE
[UX] 10-10EZR TERA - Point users to paper EZR/phone for TERA updates Designs and Content

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#77089]
As a Veteran looking to update my Toxic Exposure information with VHA, I would like to know that I cannot do it online and to be given information about how I can do it (PDF form, phone), so that I don't have to wait for the online version to get the appropriate Healthcare benefits and update my Toxic Exposure record. 

- [x] Review the work done by the EZ team for pointing to the EZ and see what we can re-purpose ([Figma Link](https://www.figma.com/file/UljiHam46o5DItC5iDgmPd/10-10EZ?type=design&node-id=1735%3A22662&mode=design&t=vbZK2BZ9P8kOyppm-1) for content and alerts)
- [x] Come up with workflow and design for pointing to paper form/phone
- [x] Come up with content 
- [x] Review content with Aliyah and get sign off (if needed)
- [x] Share designs and content with entire team and Alex
- [x] **Success: We have designs and content that tells Veterans that they cannot currently enter their TERA information online, and we hand that off to Aliyah to implement**

**"TERA Questions" are defined as Section III, #3, A-E on the new EZR PDF**
A. DID YOU SERVE IN AN IONIZING RADIATION LOCATION AND PARTICIPATE IN ANY NUCLEAR TESTING, TREATMENTS, OR CLEAN UP?
B. DID YOU SERVE IN ANY OF THE FOLLOWING GULF WAR HAZARD LOCATIONS?
C. WERE YOU DEPLOYED IN SUPPORT OF ANY OF THE FOLLOWING OPERATIONS?
D. DID YOU SERVE IN ANY OF THE FOLLOWING HERBICIDE (e.g. Agent Orange) LOCATIONS?
E. HAVE YOU BEEN EXPOSED TO ANY OF THE FOLLOWING?[VA Form 10-10EZR (8).pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1dVQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9493695ef0d4e07e1e51e520f751dfe143c67478/VA%20Form%2010-10EZR%20%288%29.pdf)

**Comment by aliyahblackmore** [comment]
**Adding two notes (cross posting from Slack):** 

- Since the online form isn't available to everyone yet (still going through incremental launch), the alert content about using the PDF form instead of the online form to answer the new questions will likely be on the form intro page.
- And I'll plan to talk more with Danielle about the **Update your health benefits information static page**and any alert content re: the new questions on the PDF from as they relate to the March 5 date.

**Comment by aliyahblackmore** [comment]
Update here: 

I shared this alert content with @katelyncai via [this Figma comment](https://www.figma.com/file/tggcJk382w9yQ0ElwKfh3N?node-id=1509:31170&mode=design#721384397).

**Comment by katelyncai** [comment]
![Intro alert](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8942468/3e468ad6-f126-4bb6-8089-7860a2a0c3ee)
Now that widget is ready, the intro alert is ready for dev! [Figma designs here](https://www.figma.com/file/tggcJk382w9yQ0ElwKfh3N/10-10EZR?type=design&node-id=1526%3A34459&mode=design&t=P1K6FOZsheDvdCxg-1). Similar content to the static info alert, but with additional information for downloading and mailing in PDF version. cc @alexseelig @mkerns1

**Comment by alexseelig** [comment]
Updates to Intro Page Alert were made as part of Story [77720](https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/77720)
