### ISSUE TITLE
CT 116: Zooming below 100% in IE cuts the edge off the filters

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#771]
@sonntag-adam commented on [Tue Jul 30 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19388)

When navigating to the search results page in Internet Explorer, If you zoom below 100% the edge of the filters are cut off
![image.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/85f86700-87a5-4d17-a635-c8535fcfbfea)

Steps to reproduce:

1. Navigate to https://staging.va.gov/gi-bill-comparison-tool
2. Search on VET TEC training providers only
3. Search results page displays, zoom below 100%

---

@ksantiagomorgan6 commented on [Wed Jul 31 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19388#issuecomment-516910337)

This issue seems to effect all check boxes on Internet explorer, edge, safari and firefox. Issue also affect different areas of the va.gov platform. Below are screenshots of the a similar issue in the health portion of the app. 

![Screen Shot 2019-07-31 at 11.21.01 AM.png](https://images.zenhubusercontent.com/5cddbb05ed0dce4209e0b99b/db7ea90e-6192-4e11-9e50-9fb824be40b3)

![Screen Shot 2019-07-31 at 11.21.19 AM.png](https://images.zenhubusercontent.com/5cddbb05ed0dce4209e0b99b/b20dd2f1-fe55-4255-890a-d46706b4ff30)

---

@desireeturner commented on [Wed Jul 31 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19388#issuecomment-517019206)

@KevinMHoffmanUSDS @mattpointzxer0 This seems to be a platform-wide issue. It is one that the Education team has deemed a high priority for resolution. Please let us know if there are individuals on the Platform team who can take a look at this. Thank you!

---

@KevinMHoffmanUSDS commented on [Thu Aug 01 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19388#issuecomment-517303505)

@batemapf Hey there, Patrick! Any thoughts on this one?

**Comment by batemapf** [comment]
@alexpappasoddball not sure if this one is for the triage team or the folks over on tools & improvements. please relabel and reroute if necessary. cc @gunsch

**Comment by alexpappasoddball** [comment]
@batemapf Since this one is not a Sev 1 issue this is going to be routed to the appropriate team.  I'll reach out to the tools team to get the best approach to get it into their backlog.

**Comment by alexpappasoddball** [comment]
@AZSchneider & @YanaRoy I think this one belongs to your team.  Can you take a look and relabel as necessary.

**Comment by alexpappasoddball** [comment]
@AZSchneider & @YanaRoy This one has been in the Triage backlog and I believe it belongs to your team.  Can you please review and move it to the necessary backlog.

**Comment by alexpappasoddball** [comment]
Assigning to Andrea & Yana and moving out of Triage Backlog.  Let me know if there are any questions

**Comment by hughes-dustin** [comment]
I was able to resolve this issue in GIBCT. 
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/11187

I think something like this will fix the issue globally. 
```
[type=checkbox] + label::before {
    box-shadow: 0 0 0 2px white, 0 0 0 3px $color-gray-medium;
}
```
