### ISSUE TITLE
Userflows for ITF

### ISSUE THREAD

**Issue by buddhima-coforma** [department-of-veterans-affairs/va.gov-team#77101]
### Background
We intend to re-introduce ITF to the pension web form experience so that Veterans can potentially benefit from 

### To do
- Generate user flows/screens that will aid us to discuss, iterate on and finalize the requirement with OCTO/VBA
- Surface any questions that arise so we can discuss and unblock

Refer: Proposed UX section, V1 
https://docs.google.com/document/d/10IzSq4XvI-RyH1jBXsyx68Jr_fW84oSBDepVZRfSHCw/edit

### AC
- Introduce ITF to pension in a manner that's beneficial to Veterans, amidst known limitations
- Provide visuals that can be shared with stakeholders for feedback

**Comment by Dene-human** [comment]
Can we please add the link to the flows here? Going forward it would be really helpful to comment and add links to relevant artifacts when closing tickets. Any questions/findings/specs discovered in completing the ticket can also be logged here. I've also requested access to the Google doc mentioned in this original ticket.

**Comment by aplatt-coforma** [comment]
Sharing this slide which Gretchen shared in our sprint review. 
 <img width="1130" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUtCQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f13401f5e7223d58d038517c907bc94b92ba91a7/Screenshot%202024-04-22%20at%201.49.42%E2%80%AFPM.png" alt="Screenshot 2024-04-22 at 1.49.42 PM.png" />

Here's the 526 proposed flow diagram: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1700602283685/fef07188052ef83487d76762990509d0619626d6?sender=ua4b11671f027a66286586953

We also created this CAIA ticket to get copy edits. Gretchen was working on other things when Katherine sent over her suggestions so we have not been able to return to this effort: https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/gh/department-of-veterans-affairs/va.gov-team/78928
