### ISSUE TITLE
Verify review section per Figma #3

### ISSUE THREAD

**Issue by michaelclement** [department-of-veterans-affairs/va.gov-team#77127]
The goal of this ticket is to verify the review section of the form matches the latest Figma (anticipated in Sprint 12 - Feb 28 thru Mar 12).

Acceptance Criteria
- [ ] Flow matches mockup in the corresponding Figma
- [ ] All necessary data is collected

**Comment by michaelclement** [comment]
Updated points to 5 because the modal file upload interaction on the review page may be a significant lift.

**Comment by michaelclement** [comment]
@baltes This ticket can be closed as it's no longer relevant

**Comment by baltes** [comment]
Closing as no longer needed
