### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by rakeshmaurya563** [department-of-veterans-affairs/va.gov-team#77132]
### Name

Rakesh Maurya

### Email

rakesh.maurya@va.gov

### Role

QA Engineer

### Team

QA team

### Product Manager (PM) name

bryan.riley@va.gov

### Additional Notes

Need access to perform my task

**Comment by naomimarcussen** [comment]
Hi! An invite has been sent to rakesh.maurya@va.gov.
