### ISSUE TITLE
Determine counts

### ISSUE THREAD

**Issue by mjknight50** [department-of-veterans-affairs/va.gov-team#77133]
@wayne-weibel What is the best way for us to get a count about how many submissions we've had from X date to Y date?

Google Analytics/DOMO does something like this I think, which might be the easiest route.
DataDog?
Rails script?

Can you please develop a solution for this or just educate me on it?

AC:
- Have a count of submissions that can be trusted
- Inform DOMO team if they need to update their dashboard to make sure they're showing the right thing too

PS-There seems to be a lag for DOMO stats so best to test against a prior week

**Comment by wayne-weibel** [comment]
this should be a 'simple' database query against the saved_claims table.  would need production access to the db or rails console though

**Comment by mjknight50** [comment]
This is the DOMO dashboard that seems to have something like it:
https://va-gov.domo.com/page/1030131175

But I'm not sure where within that?

**Comment by buddhima-coforma** [comment]
Yes, the DOMO vs raw data JSON counts don't seem to add up.

Go here and filter by 'pension' and a date range https://va-gov.domo.com/page/447193050?userId=935700377
<img width="416" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/143657406/2151b892-28d2-4ad4-9c3e-bc57b4bb0616">

**Comment by wayne-weibel** [comment]
This is an apples and oranges issue:
DOMO is counting the number of online form submission reaching a 'successful' state
Datadog is counting the number of log entries for a FormSubmission change to 'vbms'
Database is the purest number of submitted claims since [DATE]

**Comment by buddhima-coforma** [comment]
How does DOMO 'successful' state count match up against DB numbers @wayne-weibel ?

**Comment by mjknight50** [comment]
```
SavedClaim.find_by_sql("SELECT * FROM public.saved_claims WHERE created_at > '2024-02-27 14:08:30' AND form_id = '21P-527EZ'").length


FormSubmission.find_by_sql("select * from public.form_submissions where created_at > '2024-02-27 14:08:30' AND form_type = '21P-527EZ'").length
```
