### ISSUE TITLE
Determine alternative scheduling solution

### ISSUE THREAD

**Issue by RenataKeck** [department-of-veterans-affairs/va.gov-team#77149]
## Description
Calendly is not a viable scheduling solution for user testing sessions because it is blocked by the VA firewall. Many of our users are on the VA network and therefore are unable to schedule sessions.

### Output
- Test alternative solutions like DoodlePoll on the VA network
- If a paid option is necessary, collaborate with Harold to get permission
- Set up scheduling for future sessions

### Leads and Contributors
Lead: Rebecca
Contributor: Harold

### Resources
n/a

## Acceptance criteria
- [x] Scheduling solution has been identified and is ready for use in ongoing user testing

**Comment by uxrebecca** [comment]
Harold asked about Zoom Appointment Scheduler. I tried it out today and has similar functionality to Calendly. It syncs to your Google Calendar and you can ask questions of people as they sign up. I made an example scheduling page: https://scheduler.zoom.us/rebecca-blakiston/usability-test

Asking Harold to confirm we can use it, and then we can do more testing.

**Comment by uxrebecca** [comment]
@hdbaines any update on this? If we can't use Zoom Scheduler I can start looking at alternatives, but Zoom seems like it will meet all our needs.

**Comment by hdbaines** [comment]
Received approval for Zoom Scheduler, working on getting it purchased today

**Comment by uxrebecca** [comment]
Zoom account upgraded and scheduler link ready to send out. Only issue we found in testing was it doesn't work in CAG in IE. But hopefully that won't be an issue. Closing this ticket.
