### ISSUE TITLE
Adding Allan To to DSVA Slack

### ISSUE THREAD

**Issue by emily-brown34** [department-of-veterans-affairs/va.gov-team#77142]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

<describe the request>

Please add Allan To as a full member to the following channels.
Email: allan.to@adhocteam.us (awaiting VA email)

- What channel(s) do they need to be added to?
1010-health-apps
 health-tools-1010-apm
 vecms-carma_vadotgov_development_external
 accessibility-ops
 vfs-change-announcements
 vfs-platform-support
 vfs-all-teams
 feedback-backchannel
 (Frontend Engineers) vfs-frontend

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.
-Allan To is our new QA strategist for the Health Enrollment Project and needs access to DSVA slack and above channels in order to successfully contribute to the project.

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add [_insert email_] as a single-channel guest to [_channel name_].
- Please add [_insert email_] as a multi-channel guest to these channels: [_channel names_].
- Please add [_insert email_] as a full member.
- Please change the status of [_slack username_] from [_current status_] to [_desired status_]

**Comment by emily-brown34** [comment]
@LEHigley @KevinMHoffmanUSDS  following up on this request

**Comment by LEHigley** [comment]
showing as a member
