### ISSUE TITLE
[VSOffs][Prototype] User Testing - Shareout

### ISSUE THREAD

**Issue by RenataKeck** [department-of-veterans-affairs/va.gov-team#77156]
## Description
Closeout for both the singly accredited user testing study and NACVSO. Per a discussion with the team, the shareout will be ~60min and may be followed with a feature evaluation discussion with stakeholders.

### Output
- [x] Determine the audience and schedule findings shareout session
- [x] Moderate shareout of research findings deck
- [x] Ensure PDF of findings is shared to appropriate Slack channels and Sharepoint
- [x] Upload to Github

### Leads or Collaborators
Single accredited user testing section: @RenataKeck 
NACVSO section: @uxrebecca 
Design iterations and mobile design exploration: Courtney

### Resources
- [Singly accredited user testing findings report](https://docs.google.com/document/d/1o1Sw_pKoxFt7Pvt_DaVi0FfCcqRIavtMBiECZY26LDY/edit#heading=h.h5b7gmnaau7b)
- [NACVSO findings report](https://docs.google.com/document/d/1WsfRxA88_Oh2D-Z8vdJs_82G9AvpP1E1keEZyIv_1gY/edit)
- [Findings deck](https://docs.google.com/presentation/d/1wQXNhRW9f28fbb1OlRAu8_9X_yMkc9W5tsamlxRWDGY/edit#slide=id.g2deabca11b1_0_48)

## Acceptance criteria
- [x] Shareout completed and report has been uploaded in the appropriate locations

**Comment by hdbaines** [comment]
@RenataKeck is this a dupe? Or, does it need updating?

**Comment by RenataKeck** [comment]
@hdbaines not a dupe, but I need to update.

**Comment by RenataKeck** [comment]
Per standup, share out will happen after NACVSO conference, may include both user testing and conference research findings.

**Comment by RenataKeck** [comment]
Share out is scheduled for 6/11 at 3pm ET.

**Comment by RenataKeck** [comment]
- [Presentation](https://dvagov.sharepoint.com/:p:/r/sites/vaabdvro/Shared%20Documents/Accredited%20Representative%20Facing/Research/032024%20VSOR%20User%20Testing/User%20Testing_NACVSO_%20Presentation.pptx?d=w7014bd1a98fd4269bc1b743097b4172c&csf=1&web=1&e=Mxg5dW)
- [Recording](https://dvagov.sharepoint.com/:v:/r/sites/vaabdvro/Shared%20Documents/Accredited%20Representative%20Facing/Research/032024%20VSOR%20User%20Testing/20240611-Shareout_Recording.mp4?csf=1&web=1&e=f1gRxK&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D)
