### ISSUE TITLE
AWS access for Nathan Douglas

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-team#77161]
### COR Name

Eunice Garcia

### Vendor Onboarding Representative Name

Agile Six - Anthony M. Arashiro

### Your Name

Nathan Douglas

### Your Email

nathan.douglas@agile6.com, nathan.douglas@va.gov

### Team, Role, and Company of the target individual

Check-In Experience, DevOps Engineer, Agile Six

### Product Manager (PM) name and email

Lori Pusey, lori.pusey@agile6.com

### Product Owner (PO) name and email

Kay Lawyer, katherine.lawyer@va.gov

### Desired AWS Access

It looks like I need to be added to `dsva-vfs-developers` on `dsvagovcloud`. I'm already in the system 🙂 

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

![Screenshot 2024-02-27 at 12 51 00 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/1318579/6b06e396-f110-4627-a41e-405dc946a9df)

### Additional Notes

Just joining the team 🙂 

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [ ] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [x] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by hgbarreto** [comment]
User found in Atlas

**Comment by hgbarreto** [comment]
AWS Group swap complete
