### ISSUE TITLE
Redirect Request: VHIE page 

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#77189]
### Status
**[2024-02-29]** Approved! Moved into next refinement. Informed Kristin we may not be able to release until Sprint 106, starting 3/13 but will coordinate with Jill and team to prioritize.
**[2024-02-28]** Awaiting review/approval from IA (see in comments)

### Instructions
- Requests must be submitted **AT LEAST** 2 weeks in advance.  Some requests take a significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders as appropriate.  

### Type of request
- [ ] We are retiring or taking down a page and need to redirect the URL (complete redirect section)
- [X] We are changing the URL of an existing page (complete redirect section)
- [ ] We need a custom vanity URL (complete vanity URL section)

### Implementation date
When does this request need to be live?
Choose one:
- [ ] On a specific date, connected to a program or publishing requirement. **DATE:**
- [ ] Any day prior to a deadline/latest possible date. **DEADLINE:** 
- [X] Any day after an earliest possible date. **EARLIEST DATE: Feb 27 2024**
- [ ] During a specific date range: ***EARLIEST DATE TO LATEST DATE:***
- [ ] No hard timing requirements, publish when possible.

### Redirects 
Current URL  |  Redirect Destination or New URL
---  |  ---
https://www.va.gov/resources/the-veterans-health-information-exchange-vhie/ | https://www.va.gov/resources/about-electronic-health-information-sharing-at-va

### Vanity URLs 
Vanity URL  |  Landing page
---  |  ---
requested URL | landing page URL

**Link to campaign landing page request issue:**

### Process, Roles and Responsibilities
- [X] Requesting team: Above information is provided
- [X] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [x] IA: Request is vetted and documented and implementation plan is clear 
- [x] IA: Request is assigned to appropriate team for implementation 
- [ ] Implementation team: Work is complete
- [ ] Implementation team: Validated in production
- [ ] Requesting team: Validates everything is correct in production and closes ticket

**Comment by laurwill** [comment]
Hi @kristinoletmuskat , we published changes to an R&S page that changed the H1 and URL, so we published in a new node. Now we need to redirect the old URL to the new URL. Could you review for IA and then assign to Fran for implementation? Thank you!

**Comment by kristinoletmuskat** [comment]
Approved! Tagging @FranECross and @jilladams

**Comment by FranECross** [comment]
@kristinoletmuskat Thanks! The current sprint is pretty packed, so it may be Sprint 106, starting on 3/13 before we can release. We'll keep you apprised and do this soonest.

**Comment by FranECross** [comment]
@strelichl Once we release we'll close. Thanks for checking!

**Comment by laurwill** [comment]
Hi @FranECross , just checking on this redirect request — do you think you'll get to this one in this sprint? Thanks so much!

**Comment by FranECross** [comment]
@laurwill Apologies, we've had several sprint injections of defects and other things. I'll check with the team to see if they can pull it into the current sprint.

@chriskim2311 Are you able to pull this item into the current sprint? cc @jilladams

**Comment by chriskim2311** [comment]
@FranECross I can work on it this sprint

**Comment by laurwill** [comment]
Thank you both! And no need for apologies at all, there's never a dull sprint around here :)

**Comment by chriskim2311** [comment]
@laurwill @FranECross  This redirect has made it to prod, let us know if you see any issues thanks!

**Comment by FranECross** [comment]
Looks good, thanks @chriskim2311 !
