### ISSUE TITLE
Update appointments links to send users directly into the app

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#77185]
## Description
Today, appointments is in Phase 1b and is the only app under `/my-health` that is fully integrated into VA.gov, but the links on our landing page send the user to the `/health-care` benefit hub page for scheduling and managing appointments. The reason for this is that there were technical issues routing users directly into the app due to multiple redirects timing out and preventing direct access. The appointments team has recently resolved this problem, and we should update our landing page as well to keep users within the `/my-health` space for appointments. 

### User story
As a user of My HealtheVet on Va.gov, I want to click "schedule an appointment" and actually be sent directly to the correct page so that I can complete my task efficiently, rather than being sent on a circuitous path that requires me to leave the /my-health space for the /health-care benefit hub, to then then click again to return back into the `/my-health/appointments` space. 

### Notes
- 

Possible tasks:
- [ ]  Check with appointments team @JRRoof or others about implementation strategy in case we run into the same technical complexity with this URL that this team faced

## Acceptance criteria

- [x] Users can click links under "appointments" on the My HealtheVet landing page and go directly to the `/appointments `space without leaving `/my-health`
- [ ] updates to the first link under the "appointments" box to _schedule_ an appointment are made (see comment below) and verified in staging and/or prod
- [ ] Notified Appts PO Kay [in slack](https://dsva.slack.com/archives/C0581MN69TJ/p1709062951059159) when work is merged

**Comment by sterkenburgsara** [comment]
cc @kristenmcconnell @klawyer @outerpress

**Comment by outerpress** [comment]
@jzucadi @sterkenburgsara I took a look on staging and this isn't working as we expected.

* The first link still reads `Schedule and manage appointments` - it should read `Schedule a new appointment` 

* The first link is navigating to the Appointments home url. It should bring the user to the start of the scheduling flow: `/my-health/appointments/schedule/type-of-care`

FYI @JRRoof @simiadebowale @ldelacosta

**Comment by outerpress** [comment]
fyi @kristenmcconnell

**Comment by sterkenburgsara** [comment]
@outerpress thank you! I'll add these details to our [ticket here.](https://app.zenhub.com/workspaces/mhv-on-vagov-landing-page-62619a987d74510018ecc546/issues/gh/department-of-veterans-affairs/va.gov-team/69895)

**Comment by wesrowe** [comment]
@jzucadi, the github history of this ticket isn't clear about how it was QAed before you closed it. We would like to get this fixed quickly, as unfortunately it has languished after we promised it would be done quickly.

**Comment by sterkenburgsara** [comment]
Hi, this should not be closed, can we re-open? @outerpress just looked and I also verified on staging that the fix has not been made. Right now, the first two links under the "Appointments" box go to the same place. Instead, we need the following updates to the first link: 
* Link text should read: `Schedule a new appointment`
* Link destination should be: `/my-health/appointments/schedule/type-of-care`

**Comment by jzucadi** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/28821

**Comment by jzucadi** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/28821 has been merged

**Comment by wesrowe** [comment]
Did we get confirmation that this is working as expected now, @sterkenburgsara?

**Comment by outerpress** [comment]
On the VAOS side we tested (on staging) scheduling all the way through our 3 scheduling flows starting from MHV on VA.gov home, without hitting the appointments page. No issues there. We'll be monitoring Medallia feedback to see if any issues come back. If y'all see any issues in your monitoring of this page/this link in particular, let me know. Thanks! This is a great improvement :)
