### ISSUE TITLE
Accessibility annotations for Find

### ISSUE THREAD

**Issue by oddball-lindsay** [department-of-veterans-affairs/va.gov-team#77183]
## Background
In Staging Review, governance mentioned some accessibility updates -- [tickets are documented in this milestone](https://github.com/department-of-veterans-affairs/va.gov-team/milestone/1244).  

This ticket is to make note of these in the corresponding Figma file for Find a Representative.

## Tasks
- [x] Update Figma to include accessibility annotations called out from governance

**Comment by mtri** [comment]
All is added to annotations. [Viewable here.](https://www.figma.com/file/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?type=design&node-id=2059-92327&mode=design&t=U4APsifBVpLltgJS-11)
