### ISSUE TITLE
S48 [Leap Year 🍀]

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#77204]
# Sprint Goals

### **Priority 1: [NOD | Infinite loop bug prevented users from accessing the form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/71191)**
**NOD V2: Finish E2E testing in production**
- #76108 

**NOD V2: Finish Collab Cycle reviews for the Extension Request Feature ([Collab Cycle ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/75865)).**
- #76205 
- #76204 

**NOD V2: Kickoff incremental release! 🎉**
- #64642 
- #77316 
- #77054 

**NOD V2: Fix minor bugs**
- #76954 
- #76953 
- #76952 
- #67435 

**Infinite loop bug: Finish reporting for Veteran emails that return a hard bounce**
- #76818 
- #65509 (VA Notify Intake ticket, for tracking purposes)

### **Priority 2: [SC and NOD | Downstream failures](https://github.com/department-of-veterans-affairs/va.gov-team/issues/70293)**
**Improve our ability to observe transactions in production**
- #76819 
- #75559 

**Code work for downstream errors and error messages**
- #76161 

**Design and tech spikes for downstream errors and error messages**
- #74503
- #74511
- #69617 (not ready for pickup)
- #74493 (not ready for pickup)

## Discovery
**Wrap up research and synthesis for the “Accessible Appeal Download” feature**
- #73587
- #76812 

**Submit data requests for Decision Review opportunities**
- #75073
- #77321
- #77320 

## Things to keep an eye on
**Remediation and other critical/time-bound things related to L&M and bug triage.**
- #72813 
- #76675
- #76516 
- #74990 
- #76218 

---

## Team Capacity
**Target velocity:** 
- 23

**PTO:**
- Rocio (2/8)
- Eugene (2/8)

**Outages for Awareness:**
- DK (3/1)
- Silke (3/1)
- Zach's upcoming paternal leave (due date 3/19) 🎉 

## Sprint Risks and Assumptions
- Aiming to have NOD V2 released by or before 2/13

## Reference documentation

- [High-level Roadmap](https://docs.google.com/presentation/d/18rYnaYCjp2L2cm8HdYmXsg1_Pz7KI_X0vNRkmT5AqEk/edit#slide=id.g2804f61cf5f_0_0)
- [Tactical Roadmap (WIP)](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1702419283589/39d0d78778b8a35a2a02b48496d665d86ec3c5a2?sender=ud80be02ce240061eb0f35352)
- [Planning and Prioritization Board](https://github.com/orgs/department-of-veterans-affairs/projects/1026/views/1?filterQuery=)
- [Defect Board](https://github.com/orgs/department-of-veterans-affairs/projects/876/views/1?visibleFields=%5B%22Title%22%2C%22Assignees%22%2C46447480%2C46447511%2C46447563%2C%22Labels%22%5D)
- [Story Estimator](https://docs.google.com/spreadsheets/d/1ae9fpz_ThZycIWjmBBMSEuGRGqsvRSz3/edit#gid=1440877167)
- [Velocity Planner ](https://docs.google.com/spreadsheets/d/1i7pVgf2XQxuRkIbuhHC5dckx2RlZt87n/edit#gid=880321098)

**Comment by HeatherWidmont** [comment]
Updated PTO & Target Velocity @saderagsdale

**Comment by HeatherWidmont** [comment]
I added the #77054 bug support ticket to the sprint plan above. @saderagsdale do you want to keep #77316 or remove it? To my knowledge the two serve a similar purpose.

**Comment by HeatherWidmont** [comment]
Added #74990 to "Things to keep an eye on" section. @Mottie picked it up today after discussing it with @saderagsdale & @data-doge

**Comment by HeatherWidmont** [comment]
Removed #76826 & #72199 due to higher priority work that is ongoing this sprint. They will be monitored in the bug triage meetings & will be picked up in a future sprint

**Comment by eileen-coforma** [comment]
This was last sprint, should this be closed? @HeatherWidmont
