### ISSUE TITLE
[DA] 10-10EZ - Analytics: Report custom events to Analytics team

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#77214]
## Benefit to the Veteran
By reporting our form's custom events to the Analytics team, we can ensure we are tracking what is going on within the form.  This helps us to track Veteran behavior and identify painpoints that can be improved.

## Background
The Analytics team posted this request in slack:
>In preparation for the migration to Google Analytics 4 (GA4), we ask that all VFS Teams that leverage and track custom events in their products [complete this form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=johnny-jesensky-adhoc&labels=analytics-insights%2C+analytics-request%2C+ga4-migration%2C+analytics-insights-form&projects=&template=analytics-custom-event-request-%28WIP%29.md&title=VFS+Custom+Events+for+%5BTeam+Name%5D+%26+%5BProduct%28s%29%5D), (along with its attached spreadsheet), no later than Friday, April 5. Detailed instructions on what information to include for each custom event can be found within the form. We are providing some additional information on this ask below.
>- Why Is This Needed?
>     - Universal Analytics (UA) properties will stop collecting data on events on June 30, 2024. In order to maintain data collection on a product's custom events, we need to ensure they are properly set-up within GA4 before that date.
>- What Is Required From Me?
>     - Please work with the front-end engineers on your team to identify, and list out custom events that you want tracked within GA4. Each event needs to be specified with information like event type, code snippet, file URL, etc. We have provided an example of what information to include on the form and attached spreadsheet.
>- When Do I Need to Complete this Form?
>     - Please complete this form as soon as you can, but no later than Friday, April 5. UA will stop collecting data on all events on June 30, 2024, so we are trying to ensure coverage within GA4 well before the cut-off date.
>
> [!NOTE]
> If your team manages more than one product, you can submit this form multiple times, or alternatively, include multiple copies of the spreadsheet to the same Github form. Whichever option is easiest.

## Tasks
- [x] Check in with Frontend engineer to confirm any and all custom events
- [x] Complete ticket and submit to Analytics team - be sure to add our team label "1010-team"

## Acceptance Criteria
- An Analytics ticket is submitted with all the pertinent information.

**Comment by jessicastump** [comment]
@luis-simauchi  - Same note as the CG ticket - here is the link to the [EZ Figma file](https://www.figma.com/file/UljiHam46o5DItC5iDgmPd/10-10EZ?type=design&node-id=0-2467&mode=design&t=LvwA2lRcEckp8H13-4) - please let me know of any corrections that this design file may need. Would like to keep the source of truth file up-to-date :)

**Comment by luis-simauchi** [comment]
https://docs.google.com/spreadsheets/d/1ysKK_u5NjRE-l0s7-s0ZoYOQ3WJ5QYFBB1Paiq2ahxw/edit#gid=1519423823

google sheet that contains our custom events

**Comment by luis-simauchi** [comment]
https://docs.google.com/spreadsheets/d/1ysKK_u5NjRE-l0s7-s0ZoYOQ3WJ5QYFBB1Paiq2ahxw/edit#gid=2087351809
new spread sheet for EZ specific custom events

**Comment by luis-simauchi** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/79133

github ticket for analytics submitted and linked above
