### ISSUE TITLE
SOCKS access for [Jonathan Keister]

### ISSUE THREAD

**Issue by keisterj-oddball** [department-of-veterans-affairs/va.gov-team#77229]
### Your Name

Jonathan Keister

### Your Email

jonathan.keister@oddball.io

### Your GitHub Handle

keisterj-oddball

### Your Role and Team

QA Engineer - CMS Team

### Product Manager (PM) name and email

Grace Kretschmer

### Product Owner (PO) name and email

Erika Washburn

### Access Type Requesting

drupal_developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCb0g6V0QcCuy4AycFcM4lFDnJhSJkY1PFCMXRZmVMx4n0o8uRKe+LXeda2VA/+0fcIbMdcmreONoWr74MPJWwTU3dk8Fj2OFgqrno36BP9YlSZ/SleYQqgQjkzZjLj55lXIeijOWztItrdKh+roNV+uNCFNaUhx8Fk+EsNR7FWhYka5FgUyF0pPTWgNeAVeH1LiAKAZHkAREJn87HruI6ulpLxGjmT/HGxi9gcBlw3K/eFmcuuKoVM/iQQdBjjPZCaSZjWC06z0IHsSszt84hiSHHMyxbi2hg8k/XthEpM5je0XTFOZdJN4cUcGmHhYGKKiqJN8S55kXaBmz4SL4gh/0PAw697EprsulZ73cf4vFqy/9gLrkvZrImjSU1nYs3+uW58nyh1iYcgXdGAOGuXza3XJ50GLucuuM1OcUkpdHSuIp1PCL9luYYHPbiywXLVIySSiVdJFsXZOyG+ZEBfYgqWlqSRO12AKC7fBu5JFsnD6wtwDlBZzh/EHH4yk80= jkeister@Jonathans-MBP.fios-router.home

### E-QIP Transmittal Confirmation

![Screenshot 2024-02-27 at 5 12 35 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/156961902/dadc6ff8-0a11-4b8a-ba8f-c019b89742dd)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by stoiven** [comment]
Merged key.
