### ISSUE TITLE
Implement non-registered user alert on my-health tools

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#77237]
### User story

As an authenticated user who is not registered to a VA facility, I want health apps within the /my-health/ portal on VAgov to alert me to the fact that I don't have access to health tools, so that I have enough information to take action if appropriate.

### Notes
- Design ~and permission from tool teams~ covered in #75533. 
- See [Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1708021768991/da471da0766950e8daa18f488262c51bc1a2a3da?sender=uebde62ceb342c6477fb09406)
- Implementation does not need to catch child pages
- Jim recommendation: consider a route guard
  - Users wouldn't even reach the tool landing page if they tried to get there (e.g. hacked the url)

Possible tasks:
- [separate PRs per tool?]
- a11y review

## Acceptance criteria

- [x] Get permission from tool POs before implementing – achieved in [this slack thread](https://dsva.slack.com/archives/C04DRS3L9NV/p1710357079250479) on 3/19/2024
- [x] Users cannot access individual tool pages or any content deeper than the MHV landing page. Instead, route guards will send all users who access links or side doors to URLs within` /my-health` to the main landing page, where users will see the alert already in production on this page.
- [x] Content of alert is updated per comment below (replace `both` with `at least one`)
- [x] 

## Associated PRs:
1. [Add mhv route guard to after visit summary](https://github.com/department-of-veterans-affairs/vets-website/pull/29313) - MERGED
2. [Add mhv route guard to medications ](https://github.com/department-of-veterans-affairs/vets-website/pull/30062)- 2 Approvals needed, 1 from our team
3. [Add medical records mhv route guard](https://github.com/department-of-veterans-affairs/vets-website/pull/30063) - 2 Approvals needed, 1 from our team
4. [Add mhv route guard to Secure Messaging](https://github.com/department-of-veterans-affairs/vets-website/pull/29371) - CLOSED due to Oracle migration which will bring in users that don't rely on the vets-api
5. [Add mhv route guard to supply re-ordering](https://github.com/department-of-veterans-affairs/vets-website/pull/29373) - 2 Approvals needed, 0 from our team
6. [Add route guard component and unit test and copy for NoHealthAlert](https://github.com/department-of-veterans-affairs/vets-website/pull/29374) - MERGED

**Comment by wesrowe** [comment]
refine after design is complete – may be complex (eg H1 challenge)

**Comment by wesrowe** [comment]
I removed the blocker on this one, as Sara's work on the non-registered alert is complete. (I.e., no controversy or questions around that section of the mural.)

**Comment by wesrowe** [comment]
Sara to message tool owners for permission for this work.

**Comment by wesrowe** [comment]
update: as linked in first AC, [Sara got sign-off in slack](https://dsva.slack.com/archives/C04DRS3L9NV/p1710357079250479) from MHV stakeholders about using the route-guard idea for un-registered users – i.e. taking any un-registered user from the tool page they tried to access to the MHV landing page with the un-registered alert. Biggest point of discussion was Appointments edge case around claim exams (aka compensation and pension exam).

**Comment by sterkenburgsara** [comment]
Per Lauren Alexanderson & Laura Willwerth [in Slack](https://dsva.slack.com/archives/C04DRS3L9NV/p1710357079250479), there is a slight update to the alert we need to make in production: update the text in the first line of the alert to say "at least one." 

<img width="1452" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlAwQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--845b726504d54d159651c1f7823730ea07724acb/Screenshot%202024-03-19%20at%204.21.07%E2%80%AFPM.png" alt="Screenshot 2024-03-19 at 4.21.07 PM.png" />

**Comment by jzucadi** [comment]
Secure messaging currently has a validation process for showing an alert to users based on backend services aka the vets-api. The route guard PR was closed due to an upcoming Oracle migration which will bring in a new set of users that do not have the `mhvAccountState` property in the vets-api

**Comment by LynneJohnson224** [comment]
@wesrowe @jzucadi my notes from planning yesterday were that we will close this ticket and address the issues in 2 new tickets. Can we close this?
