### ISSUE TITLE
Use metrics instead of logs in DataDog

### ISSUE THREAD

**Issue by buddhima-coforma** [department-of-veterans-affairs/va.gov-team#77238]
### Background
After a chat with SteveA, I learned that logs are only stored for a month while metrics are stored for longer in DataDog.
https://docs.datadoghq.com/logs/log_configuration/logs_to_metrics/

### Tasks
- Setup log-based metrics derived from logs for the tracking that has been setup for Pension
- Update dashboard to utilize these metrics instead of directly utilizing logs

### AC
- The pension dashboard has data that can be compared over longer durations (throughout the year, across quarters etc) which would not be possible if we directly relied on logs

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/77238?planning-poker) with Zenhub @danlim715 @mjknight50 @scottsdevelopment @TaiWilkin @wayne-weibel

**Comment by TaiWilkin** [comment]
For scoping purposes, I think the top four charts (calls by action and calls by status) are the only ones where we translate logs to numbers (vs showing logs for debugging purposes). Would we want to update any of the log lists, or just update those four numerical charts?

**Comment by TaiWilkin** [comment]
I've updated the numerical charts which used logs to use metrics, and confirmed that all the other numerical charts use metrics. Charts where we show lists of logs for debugging purposes have been left unchanged.
