### ISSUE TITLE
IPP - Usability Tests with Proofing Agents

### ISSUE THREAD

**Issue by lmorris3** [department-of-veterans-affairs/va.gov-team#77243]
Once the Proofing Agent Usability Tests are scheduled, we'll conduct them! Goal is to complete 7 UTs with Proofing Agents by the end of the first week of March.

Def of Done:

- [x] at least 7 PA UTs are conducted
- [x] each session has a note-taker and facilitator, at least
- [x] each session is recorded

**Comment by SophiaPhilipMO** [comment]
Follow up scheduled for March 7 for participant who did not see all screens
