### ISSUE TITLE
Reconfigure S3 bucket settings on vets api

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#77262]
Reconfigure S3 bucket settings on vets api so that staging S3 is accessible via staging url.

Acceptance criteria:
- Via staging url, the staging S3 bucket stores the files coming from staging vets api.
- On staging S3 bucket, should be able to see all the files (via AWS console).

**Comment by marywang2** [comment]
@balexandr just assigned this one to you for the current sprint - feel free to throw some points on. Thanks! (cc @baltes)

**Comment by cloudmagic80** [comment]
@balexandr I am working with platform to remove the MFA settings so that the AWS_SESSION_TOKEN isn't required.
AWS_SESSION_TOKEN expires every 12 hours.

**Comment by balexandr** [comment]
Seems like these steps are the way forward.
1. Add the s3 keys to AWS PAram Store (Manually or AWS CLI)
2. Clone https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests
3. Make necessary changes to `secrets.yaml` and `values.yaml` (example: https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/commit/8a451a747cabddbc2024189274b5745f617a0c40)
4. Push PR up for review
5. Test on dev/staging

**Comment by balexandr** [comment]
Working with platform to update my write access to push my work

**Comment by marywang2** [comment]
Waiting for review from platform.
