### ISSUE TITLE
[ONGOING][Support,Forms] Logging

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#77286]
- This support effort began about the first week of January of 2024
- Ongoing support of Forms
- Loki logs
- Cloudwatch logs
- Log restoration
- Services requiring reconfiguration
- Deprecated Grafana, but have a separate route providing exclusive access to only those that require it

**NOTE:** This is in support of a **code yellow** and is tied to the ask in [this](https://dsva.slack.com/archives/C06979ADKNY/p1707321527277069) thread.

### Related

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/75621
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/76092

**Comment by ph-One** [comment]
Was able to get S3 Inventory to work this time. Working to restore the remaining objects

**Comment by ph-One** [comment]
Approximately 3.8M objects left to "restore" -- some have already been marked for restore, others have not. Today I will finish marking them all for restore, and am hopeful that by the end of the week everything is fully restored and usable by Loki

**Comment by ph-One** [comment]
3,538,352 objects initiated a restore last night. copying onto themselves (hours), and then retesting loki

**Comment by ph-One** [comment]
- All logs have been restored
- At this point I believe that every log logged can be found in Dd, CloudWatch, and Grafana Loki

**Comment by ph-One** [comment]
Closing this ticket now that all logs have been restored. I will open if any more time is needed for logging.
