### ISSUE TITLE
[DA] 10-10EZ - TERA: Create widget in DD to track number of TERA responses

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#77281]
## Benefit to the Veteran
By tracking the pages and responses to TERA questions, we will be able to determine the effectiveness of the new section, and possibly identify points of confusion or frustration.

## Background
With the new pages for TERA being deployed, we would like to track how many applications indicate a YES answer within the pages.
We have events on the radio buttons (Yes/No), so we should be able to pull those in for each page that has it.

## Tasks
- [x] Create a DD widget to track the YES answers within the TERA pages
     - Especially the first YES (as in Yes, I want to provide answers)
 
## Acceptance Criteria
- We will be able to track the number of applications that have indicated a YES within the TERA questions

**Comment by hdjustice** [comment]
@luis-simauchi - If you have the time, this is something else we may want to consider implementing for TERA.  If we can't create a widget, maybe a query page that already exists to help us track TERA responses

**Comment by hdjustice** [comment]
I opened the link to check it out and I think the dashboard might be set to Private, as I am not able to view it.
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/92328831/b15fb533-894a-422c-aac5-45c17d8ae04d)

**Comment by luis-simauchi** [comment]
apologies the setting needs to be a switched and shared.
But there is a another problem.... The radio button question events are not flowing into GA like similar events
double checking this morning

**Comment by luis-simauchi** [comment]
https://analytics.google.com/analytics/web/template?uid=ruqWAhLATf-6y3gpLOr8rA

**Comment by luis-simauchi** [comment]
going to pivot based off our conversation this morning @hdjustice

**Comment by luis-simauchi** [comment]
based off the conversation I have with Matt Long yesterday, this is blocked because the event label and subsequent custom dimensions related to question responses is not populating in GA events. Matt can have a release with a fix in next week.

**Comment by luis-simauchi** [comment]
I am retooling this request  / ticket 
Data dog has a function to count actions (like clicks on yes or no) but also other metrics that will be useful in the future
