### ISSUE TITLE
[Data] 10-10EZR: Discovery -- Expand monitoring capabilities for EZR

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#77296]
As a team member, I would like to have monitors and alerts for anything that can potentially effect the functionality of the EZR application so that I know when bad stuff has happened, and ideally before bad stuff trickles down to the EZR.

- [x] Look at the things that have gone wrong in the last ~2 months and see if there is monitoring that can help us be notified about issues or outages in those systems (AS: Patrick had one suggestion yesterday in Slack that I'll dig out)
- [x] Talk to Developers and ask them where they see weaknesses and where we've traditionally seen issues
- [ ] Review DataDog for any potential blind spots
- [ ] Review GA for any potential blind spots (I don't know how helpful GA will be with this)
- [ ] Talk to Patrick about these things
- [ ] Determine if there is anything other teams are doing that we can leverage
- [ ] Document all of the above as a proposal for enhancing our monitoring (implementation will be a separate story) and note anything we don't have access to
- [ ] **Success: We have a list of ways that we can improve monitoring so we can detect issues with the EZR, and potentially track issues that could impact the EZR**

**Comment by luis-simauchi** [comment]
actually Lihan mentioned two areas were we could expand the monitoring capacities on his way out the door and I have two shell tickets out there to address his concerns

**Comment by luis-simauchi** [comment]
ticket one: https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/78718

ticket two: https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/78717

**Comment by luis-simauchi** [comment]
paused for the GA4 switch, the swap from GA 3 to GA4 is going to change what we are able to track and report on moving forward

**Comment by luis-simauchi** [comment]
similar to other reporting work recently, it may be more fruitful to refocus this type of work to by centered around DD instead of GA
