### ISSUE TITLE
[FE] 10-10EZR TERA: TERA Questions (III.3.A-E) for EZR

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#77290]
As a Veteran, I would like to be able to update the toxic situations I was exposed to so that I make sure I get the healthcare I need and have earned.

- [x]  Work with BE to determine any needs/limitations in the TERA Questions fields
- [x] Add way for Veteran to indicate if they want to answer questions about Toxic Exposure
[ ]  Use [TERA Designs](https://www.figma.com/file/tggcJk382w9yQ0ElwKfh3N/10-10EZR?type=design&mode=design)) to build out the following TERA questions in EZR
1. DID YOU SERVE IN AN IONIZING RADIATION LOCATION AND PARTICIPATE IN ANY NUCLEAR TESTING, TREATMENTS, OR CLEAN UP? Y/N
2. DID YOU SERVE IN ANY OF THE FOLLOWING GULF WAR HAZARD LOCATIONS? Y/N
3. DID YOU SERVE IN ANY OF THE FOLLOWING HERBICIDE (e.g. Agent Orange) LOCATIONS? Y/N
- [x] Receive the question  "HAVE YOU BEEN EXPOSED TO ANY OF THE FOLLOWING? (Check all that
apply)" and allow them to select multiple answers (including an "Other" with a blank text field) and dates
1.ASBESTOS 
2. MUSTARD GAS
3. RADIATION 
4. SHAD (Shipboard Hazard and Defense)
5. MILITARY OCCUPATIONAL SPECIALTY (MOS) RELATED TOXIN
6. CONTAMINATED WATER AT CAMP LEJEUNE
7. Other (with blank text field)
8. From: To: date fields
- [ ] For the "IF YOU WERE EXPOSED MULTIPLE TIMES, PLEASE PROVIDE ALL ADDITIONAL DATES" questio, Veteran can add multiple entries that include a "Location" field and From/To date fields (mm/yyyy) (***This was deemed unnecessary***)
- [x] Add TERA fields are optional (please triple check with BE)
- [x] Unit testing
- [x] Work with QA/Team on QA testing ([QA Story](https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/77305))
- [x] **Success: The TERA questions can be viewed and answered on EZR**

[VA Form 10-10EZR (8).pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejJaQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0af7bd68d50d6adaef39e99316f4522bd6b95128/VA%20Form%2010-10EZR%20%288%29.pdf)

**Comment by mkerns1** [comment]
Update:

I provided the EZR Team a demo yesterday. I'd say I'm about 85% done just need to figure out the right configuration to setup the conditional logic so that I can see the TERA question pages as a part of the form instead of manually changing the URL in order to see each page.

Next up I need to add unit test coverage for all of the new logic I added.

**Comment by mkerns1** [comment]
Got it! Here's the revised comment for your JIRA ticket:

---

**Update:**

- **Today's Progress:** Successfully fixed the conditional logic to show the newly added TERA questions as part of the form.
- **Next Steps:** Adding unit test coverage and then creating a GitHub PR.

**Comment by mkerns1** [comment]
Update:

Today's Progress: Unit test coverage has been added and a GitHub PR was created. The PR's pipeline ran successfully and was approved by an engineer from both the Frontend CoP group and an engineer from our team. The PR was consequently merged and went out on Friday's evening deployment without issue. Changes can now be seen in Staging.
Next Steps: Swarm QA testing with Allan and the rest of the team. Once testing is done and no major issues have be logged we can then switch the feature toggle in Prod to "on".

**Comment by emily-brown34** [comment]
per stand up yesterday, closing this ticket and using #78887 for content updates
