### ISSUE TITLE
[FE] Fix complete page typos

### ISSUE THREAD

**Issue by wullaski** [department-of-veterans-affairs/va.gov-team#77315]
Fix typos on complete page.

- Success alert should be sentence case not title case
- H1 "claim" should be plural when multiple facilities

**Comment by wullaski** [comment]
@benbrasso-agile6 Here's screenshots for those fixes:

![Screenshot 2024-02-28 at 2 19 22 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/2982977/0d604f0d-04b3-4a97-a371-c329bcccd48d)
![Screenshot 2024-02-28 at 2 20 25 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/2982977/65858046-1d55-466b-9875-f40d01044589)

**Comment by benbrasso-agile6** [comment]
LGTM thx
