### ISSUE TITLE
SOCKS access for Jonathan Keister - Third Attempt

### ISSUE THREAD

**Issue by keisterj-oddball** [department-of-veterans-affairs/va.gov-team#77314]
### Your Name

Jonathan Keister

### Your Email

jonathan.keister@oddball.io

### Your GitHub Handle

keisterj-oddball

### Your Role and Team

QA Engineer - CMS Team

### Product Manager (PM) name and email

Grace Kretschmer - mkretschmer@metrostar.com

### Product Owner (PO) name and email

Erika Washburn - Erika.Washburn@va.gov

### Access Type Requesting

drupal_developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCid0wL8Pp1XedhT5btrZFjmxPMT6Ogmx+MUc+++k5o9SGymYLDHkp4sjIHZ4bauM1ff6RCCcVy3CLerTEzsuLk2GRNCLHgv0z/rnEoqrwLtQ+ICcjgGmNAOH7x9uRC+uw63jDtBI92AeT+9E+oQitKcPN7p2y4WUxDKV78jTLGSRwO414o6LCU9/gtuYOTGCLXHPKlVXHOlqJKFoC+V8G58eSBV4LSRA6rH2XDS9qhVuwGpbI1EUCIB/6uUv+wfRJnDMFcp2cHdy1CjL2zM/YkW8tqznm101H9qWmhwu9PrZL81iR0MYcM99KxVtOgQEua+m1g8a4iIq1eqSrN2KCrZXK55W/Q8ha4cFvRrgOtk+xxYuPGGF+ot/BBY11Vu6K/ckA+x6yuUF7ll9jo/hfDQbDOUvZtvleYP66oNFO0XMN6U0NN3FAzZE8Abd74kyE7mQqab6Wbub2TQ2Jv2pDn1YLDzvYkVQDUunpD21FMD1I25z9kYCh1ttYA9ZYt8ls= jkeister@Jonathans-MBP.fios-router.home

### E-QIP Transmittal Confirmation

![Screenshot 2024-02-27 at 5 12 35 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/156961902/ad79fefb-6ed4-488a-b36d-51c73f02b918)

### User must exist in a roster before SOCKS access can be granted

- [x] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by hgbarreto** [comment]
@keisterj-oddball  Current SSH Key Replaced successfully ✅ 

Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html 

Reach out in #vfs-platform-support if you have any trouble.
