### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#77310]
### Name

Simi Adebowale

### Email

simi.adebowale@adhocteam.us

### Role

FE eng team lead

### Team

Appointments team

### Product Manager (PM) name

Kay Lawyer

**Comment by naomimarcussen** [comment]
Hi! An invite has been sent to simi.adebowale@adhocteam.us.

**Comment by simiadebowale** [comment]
@naomimarcussen - thank you!
