### ISSUE TITLE
DR | Build the Product Analytics DataDog Dashboard

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#77320]
## Next Up
- DR static content data request from GA
- Domo dashboard for DR static content
- [spike] Can we get DR static content in DataDog? (Yes, will filter it and run for one quarter as an experiment)

## Done
**DR Forms Medallia Data Requests**
- #77503 
- #77504
- #77505 

**DR Forms Contact Center Data Requests (MyVA 411)**
- #77511 
- #77513 
- #77514 

**Search Tools Medallia Data Requests**
- #77523 

**DR Static Content Medallia Data Requests**
- #77518 

**Request data on VA.gov favorable outcomes vs. paper**
- Alejandro noted that this will be a dashboard request that will take roughly 3 months.

**Comment by HeatherWidmont** [comment]
@saderagsdale & @Mottie to sync today about DD dashboards

**Comment by HeatherWidmont** [comment]
@saderagsdale to check the draft of the data request that we are going to send to the VBA

**Comment by rubensun** [comment]
Working ahead to analyzing and syntesizing some of this data.
The Supplemental Claims don't appear to have any intercept data (A11 form).

**Comment by HeatherWidmont** [comment]
Steve is checking on a few items, waiting to hear back

**Comment by shaunburdick** [comment]
Done.
