### ISSUE TITLE
Investigate/Fix fwdproxy sandbox backends

### ISSUE THREAD

**Issue by tskinn** [department-of-veterans-affairs/va.gov-team#7733]
## Problem Statement
There are 5 backends down in sandbox. See grafana dashboard http://grafana.vfs.va.gov/d/000000032/forward-proxy?orgId=1&var-data_source=Prometheus%20(Sandbox)&var-interval=1m&var-backend=All&var-server=All&var-code=All

I suspect that mvi and evss need esccb requests to open firewall so we can reach them from the sandbox vpc but that I haven't confirmed that.

## Goal
Find out what is wrong with backends in sandbox and create separate issues with details and more work defined.

## Objectives or Key Results this is meant to further
- _Include references to KPIs we intend to impact_
---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by jhouse-solvd** [comment]
This ticket is very dated. In looking at the graphs in Grafana, it seems that everything is up. My assumption would be that this would have been fixed since then, or other tickets created to address it. 

Closing.
