### ISSUE TITLE
AWS access for Tyler Bird

### ISSUE THREAD

**Issue by 7hunderbird** [department-of-veterans-affairs/va.gov-team#77333]
### COR Name

Jennifer O'Day

### Vendor Onboarding Representative Name

Oddball - Amber Malcolm

### Your Name

Tyler Bird

### Your Email

tyler.bird@oddball.io

### Team, Role, and Company of the target individual

CMS Team, Senior DevOps Engineer, Oddball

### Product Manager (PM) name and email

Grace Kretschmer - mkretschmer@metrostar.com

### Product Owner (PO) name and email

Erika Washburn - Erika.Washburn@va.gov

### Desired AWS Access

I need access like @edmund-dunn 

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

![E-QIP Transmittal Confirmation](https://github.com/department-of-veterans-affairs/va.gov-team/assets/3761/b6c10040-6cbc-4ca2-b8e7-2ccb3e8ec513)

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [x] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by EWashb** [comment]
If OCTO approval is needed, please take this comment as OCTO Platform approval

**Comment by hgbarreto** [comment]
User found in Atlas

**Comment by hgbarreto** [comment]
Access granted - credentials sent to user
