### ISSUE TITLE
SOCKS access for Tyler Bird

### ISSUE THREAD

**Issue by 7hunderbird** [department-of-veterans-affairs/va.gov-team#77331]
### Your Name

Tyler Bird

### Your Email

tyler.bird@oddball.io

### Your GitHub Handle

@7hunderbird

### Your Role and Team

Senior DevOps Engineer for CMS Team

### Product Manager (PM) name and email

Grace Kretschmer - mkretschmer@metrostar.com

### Product Owner (PO) name and email

Erika Washburn - Erika.Washburn@va.gov

### Access Type Requesting

drupal_developers

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCxDQ+VcjH1J5AM67c7/LJhnfwgDXQCE/bdr0fUarR4R6iGe1yNpiZ/WzNGKaAUSaepPCH+MyqKPwiQsrVO1dck52jQg9fM73ohujQQvygjFEDQh1NAC5EmdugKeMGfDHsz0mZIblaa2/uw6z24/CZ8ulhBQfu7wk/g+/iOweO3SMvGAdCZel7ki5FJL3P+yniwOVAOSmIjn26ULumTdJl5g1vuFARjZoYiN+kn1OyKrILqAxoMBxbIMuT18SWy+Gb20el+ur/NWyT4VFs/oTFYNO+mJ9gKSyjT1FUrmVPGRFE8DjpFwWM0QgL0KeR3o3YqhX3n0CkIAFy3nMIaLTXymmbIvzjKYqPQjM6iUwt4RxrBVKAmlAdRiePo89mk9it+/yRvibroVMjuaBW8a96Ha8O7h2ivyT8DAPintOPCh65E+IDRwgRzG9xspHGDRDaQ08qLgWh5RKgpvKb/2LD2iWCcBeH+hXiqdow//DA+YLj/R5T48xfqW9crfoHD+ks= tbird@netherite.local

### E-QIP Transmittal Confirmation

![E-QIP Transmittal Confirmation](https://github.com/department-of-veterans-affairs/va.gov-team/assets/3761/918f13fc-7716-451e-872b-b08e3ebb23fb)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [x] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by hgbarreto** [comment]
@7hunderbird Access granted ✅

Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html

Reach out in #vfs-platform-support if you have any trouble.
