### ISSUE TITLE
Update broken help link

### ISSUE THREAD

**Issue by buddhima-coforma** [department-of-veterans-affairs/va.gov-team#77348]
On intro page 'Get help filing your claim' link is broken in all environments. 

### Task
- Update URL to https://www.va.gov/disability/get-help-filing-claim/

### AC
- Ensure get help URL is accurate and working

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/77348?planning-poker) with Zenhub @danlim715 @mjknight50 @TaiWilkin @ToddWebDev @wayne-weibel

**Comment by aplatt-coforma** [comment]
Link is fixed
<img width="899" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHJJQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6887d0195e6839e4fdc6dde3c2dd3f1289e22c1e/Screenshot%202024-03-08%20at%201.59.21%E2%80%AFPM.png" alt="Screenshot 2024-03-08 at 1.59.21 PM.png" />
