### ISSUE TITLE
[UX][FE] 10-10EZ TERA Alert - Back up Performance Degradation warning on intro page

### ISSUE THREAD

**Issue by jessicastump** [department-of-veterans-affairs/va.gov-team#77345]
## Issue Description
As a Veteran, I heard I qualify for health care due to my toxic exposure and I want to turn in my application with that information. Need clear direction if that is not available on the online EZ at this time and what next steps should be for me to apply.

<img width="320" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekNiQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ff8a00b891ff585dcb315cf45f5ec913c1ea535c/Alert%20%281%29.png" alt="Alert (1).png" />

[Figma link](https://www.figma.com/file/UljiHam46o5DItC5iDgmPd/10-10EZ?type=design&node-id=1735-22662&mode=design&t=oEVj7pqw8oQEp6BR-4)

---
## Tasks
- [x] Alert content / design review
- [x] Update alert on the front end with new content
---

## Acceptance Criteria
- Alert correctly identifies the proper steps in the event of application performance issues

**Comment by longmd** [comment]
@jessicastump , I want to check on the content for this one. This a bit different from what we did for the PACT deadline. The created alert was around the EZ application itself, not a general statement about VA.gov tools. Here is what we had as a title and intro for the alert:

### This application may not be working right now

You may have trouble using this application at this time. We’re working to fix the problem. If you have trouble, you can try again or check back later.

If you're trying to apply...

**Comment by jessicastump** [comment]
Got it, thank you @longmd! Not sure where the discrepancy came from...probably the sketch/figma merge somewhere :( 
The content worked on was starting in the bold "If you're trying to apply..." so if the content above is what is in production and has actually been used then let's go with that. (I just copied that artboard over) Almost positive it was Danielle who wrote those PACT alerts and Aliyah was keeping the changes very minimal.

**Comment by longmd** [comment]
@jessicastump , perfect! Just wanted to clarify that! 🙃
