### ISSUE TITLE
Recommend approach to improve non-VAgov link experience (eauth.*)

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#77358]
### User story

As a Veteran, I want to be able to click links on the MHV landing page that leave VAgov with as few sign-ins as possible, so that I don't get frustrated and feel like pieces of the VAgov experience don't talk to each other.

### Notes
- From Patrick [slack thread](https://dsva.slack.com/archives/C0581MN69TJ/p1709149965798589): 
  - "the links highlighted here are not `eauth.*` deeplinks and open in the same tab/window. since national portal can’t recognize an active SSOe session unless using the `eauth.*`  version of the site (i just learned this), when a user clicks one of these links, they are shown an non-signed in version of the national portal, which includes a sign-in button. if they happen to click that sign-in button and select option 1, it ends their active SSOe session and makes them sign in again. if this expected behavior so be it, but if not, possible solutions are: (1) find out if there are `eauth.*` versions of those pages; and/or (2) open any non-`eauth.*` national portal links in new tabs/windows."
  - Wes requested clarification: can we tell by looking at a link's URL whether it is `eauth.*` or not?
- We can at least improv Veterans' security by opening external outbound links in a separate tab – would this also preserve their SSOe session?
- We need to discover how to test the experience

### Details of situation, with screenshot

<details><summary>Screenshots and href examples</summary>

![landing page with non-eauth links marked](https://github.com/department-of-veterans-affairs/va.gov-team/assets/4054752/b5a5e7a9-2560-438c-8040-f022265f7e5d)

Example hrefs:
Inbox = `mhv-syst.myhealth.va.gov/mhv-portal-web/secure-messaging`
Try messages on VAgov = `mhv-syst.myhealth.va.gov/mhv-portal-web/ss20231205-try-messages-va `
How to use VA Video Connect = `mhv-syst.myhealth.va.gov/mhv-portal-web/ss20200320-va-video-connect `
Healthy Living Centers = `www.myhealth.va.gov/healthy-living-centers`
</details>

### Possible tasks:
- define what "eauth" means
- discover what is happening in the specific scenario Patrick calls out above: land on MHV national portal, click that sign-in button, and select option 1, lose SSOe session
  - Maybe enlist a Veteran to test prod with us 
- gather analytics on how much these links are clicked
- identify why some links on the landing page invoke the eauth flow (i.e., are "`eauth.*` pages") and some don't
- document issues and recommendation
- get a11y input on recommendation

## Acceptance criteria

- Documented recommendation for the most accessible and secure UX for non-VAgov links
- Ticketed implementation (if appropriate)

**Comment by carlosfelix2** [comment]
Another Slack thread with more user information: https://dsva.slack.com/archives/C04DRS3L9NV/p1684251986315219

**Comment by carlosfelix2** [comment]
More relevant comments from the threads:
-----------
Patrick Bateman -   12 months ago
:wave: revisiting the treatment of spotlight links on va.gov/my-health. context — it’s time to update the spotlight links on va.gov/my-health.
i went ahead and tested out the ability to deeplink from va.gov to MHV classic for a spotlight article (yet again). it looks like this is possible, at least for the one article i tried (doing more now). here is what i did:

1. Open Chrome, open incognito session
2. Navigate to VA.gov
3. Open sign in modal
4. Select ID.me
5. Sign in
6. Redirected to https://www.va.gov/my-va/?postLogin=true
7. Enter in URL bar: https://eauth.va.gov/mhv-portal-web/eauth?deeplinking=ss20230412-my-healthevet-on-va-gov
8. See logged in MHV and article

this suggests that we might be able to give the spotlight articles on va.gov/my-health the mhvUrl eauth treatment, i think.
-----------
Patrick Bateman - 12 months ago
tried same steps with:
https://eauth.va.gov/mhv-portal-web/eauth?deeplinking=va-waives-copays-for-american-indian-and-alaska-native-veterans
https://eauth.va.gov/mhv-portal-web/eauth?deeplinking=ss20221110-get-the-new-toxic-exposure-screening
and got same positive result
-----------
Patrick Bateman
  12 months ago
staging test:
tried: https://sqa.eauth.va.gov/mhv-portal-web/eauth?deeplinking=ss20221110-get-the-new-toxic-exposure-screening
got: https://sqa.eauth.va.gov/mhv-portal-web/not-found (but user was still logged in)
tried: https://sqa.eauth.va.gov/mhv-portal-web/eauth?deeplinking=va-waives-copays-for-american-indian-and-alaska-native-veterans
got: https://sqa.eauth.va.gov/mhv-portal-web/not-found (but user was still logged in)
tried: https://sqa.eauth.va.gov/mhv-portal-web/eauth??deeplinking=ss20230412-my-healthevet-on-va-gov
got: https://sqa.eauth.va.gov/mhv-portal-web/not-found (but user was still logged in)
------------

**Comment by carlosfelix2** [comment]
Suggested solution:
1. Change the links for the Landing page in `src/applications/mhv-landing-page/utilities/data/index.js` to include authdWithSSOe as the first parameter instead of false. This will create the proper deep link when a valid SSOe session is being used which allows a user to not to have to login again. Example: from `mhvUrl(false, 'ss20231205-try-messages-va')` to `mhvUrl(authdWithSSOe, 'ss20231205-try-messages-va')`.
2. Add code to detect when we don't have a valid SSOe session and open the links in a new window/tab (make sure the proper text is added like opens in new tab). This can be detected with `authdWithSSOe`. If it is false, then the link needs to open in a new tab.

**Comment by carlosfelix2** [comment]
@wesrowe, session security will not change in any way if we apply the recommendations I listed above. The changes above will be no different than a user right-clicking and selecting "open in a new tab" in the browser for the links. The session will still expire as normal in other open tabs, and logging out from VA.gov in any tab will invalidate the session in the others as well. The question if a veteran is also signed out of VA.gov when they sign out of MHV is a different technical question we can research as well, just IMO not related to this work.

**Comment by wesrowe** [comment]
Carlos went ahead with a [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/29107) to fix the links so that all links to MHV Classic use a deep link to keep the SSOe session intact, in the same tab.
