### ISSUE TITLE
URGENT [FE] 10-10EZR TERA - Update mailing address on static page widget on 3/4

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#77365]
As a Veteran, I would like to know where I can mail in my printed out EZR form so that I am able to submit my TERA information to get the healthcare I have earned.

- [x] Update the mailing address under "option 2, by mail" to be:
Health Eligibility Center
PO Box 5207
Janesville, WI 53547-5207
- [x] **Do this on March 4 in collaboration with Aliyah**
- [x] **Success: EZR Mailing address is accurate on March 5**

**Comment by mkerns1** [comment]
Update: This PR has been created to merge these changes into the main branch. Once checks in GitHub run successfully this will be able to be merged in to main and deployed during Monday 3/4's deployment.

**Comment by emily-brown34** [comment]
thanks for the update matt, can we also check off the ACs above so we are tracking what's remaining/when
