### ISSUE TITLE
[Bug] AMADR2 - Can-I-file-my-claim-online widget - "fiduciary claim" is not a hyperlink

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#7737]
## What happened?
On [Drupal How to a VA disability claim preview](http://preview-prod.vfs.va.gov/preview?nodeId=905) page, in the **Can I file my claim online** widget, for disagreeing claim decisions made 2/19/2019 or later, the widget-response text "**fiduciary claim**" is not a hyperlink.

## Specs:
Page does not require sign-in.
Bug is browser-/device-agnostic.

## Steps to Reproduce
- URL: https://staging.va.gov/disability/how-to-file-claim/
- Test User _(if applicable)_: N/A
1.  Scroll down to **Can I file my claim online?** section, then tap/click **Let's get started** button.
2.  Under **Have you separated...** question, tap/click to select **Yes** radio-button.
3.  Under **Are you filing a new claim...** question, tap/click to select **I'm disagreeing...** button.
4.  Under **What's the date...** question, select/input **Feb 19, 2019** to trigger the **You'll need to request a decision review** widget-response.
5.  In the body-text 2nd sentence, observe that the text "**fiduciary claim**" is **not** a hyperlink.

### Screenshot
![widget-missing-fiduciary-claim-link-200407](https://user-images.githubusercontent.com/587583/78734330-d773be80-78fc-11ea-8cff-bcf4fec37771.png)

## Desired behavior
"fiduciary claim" is a hyperlink to **[Fiduciary Claims](https://staging.va.gov/decision-reviews/fiduciary-claims/)** page (`/decision-reviews/fiduciary-claims/`).

## Acceptance Criteria
\[see **Desired behavior**]

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by MickinSahni** [comment]
Sprint planning 19
- Prod
  - ![image](https://user-images.githubusercontent.com/13204473/78819789-c7171e80-79a4-11ea-9211-188c59ba528f.png)

**Comment by MickinSahni** [comment]
Validated on staging
