### ISSUE TITLE
[Bug] AMADR2 - Megamenu - Disability fly-out missing File-an-appeal hyperlink

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#7738]
## What happened?
On [Staging](https://staging.va.gov/), the page-header's megamenu **VA Benefits and Health Care** > **Disability** fly-out, under **Manage your benefits** column, the **File an appeal** hyperlink is missing.

This link was called-out for changes on page 2 of the change-specs-doc [AMA.related.changes_FE_v3.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4165610/AMA.related.changes_FE_v3.docx).

## Specs:
- Bug is browser-/device-agnostic
- Test User _(if applicable)_: N/A \[page does not require sign-in]

## Steps to Reproduce
- URL: https://staging.va.gov/
- Test User _(if applicable)_: N/A

1.  In the page-header, tap/click **VA Benefits and Health Care**.
2.  Tap/click **Disability** menu-option.
3.  Under Disability fly-out's **Manage your benefits** column, observe that there's no **File an appeal** hyperlink.

### Screenshot
![Screen Shot 2020-04-07 at 7 16 30 PM](https://user-images.githubusercontent.com/587583/78738406-b021ef00-7906-11ea-9b80-ffc3cf9a3dfb.png)

## Desired behavior
**File an appeal** link appears; link-text & destination meets change-specs below.

### Change-specs-doc screenshot
Here're the details of the hyperlink text & destination changes for this missing hyperlink:
![Screen Shot 2020-04-05 at 7 35 44 PM](https://user-images.githubusercontent.com/587583/78518252-d2840300-7774-11ea-943c-94af0b63cf63.png)
NOTE: Although the doc specifies a specific page, the page-header's actually shared across all pages.

## Acceptance Criteria
\[see **Desired behavior**]

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by MickinSahni** [comment]
Hey @tzelei, in #7650, we're adding the link to the fly-out when this initiative is launching. We did remove it for AMA pt. 1, but since it's going back in with our launch it isn't really a bug. Can we close this out?

**Comment by tlei123** [comment]
> Hey @tzelei, in #7650, we're adding the link to the fly-out when this initiative is launching. We did remove it for AMA pt. 1, but since it's going back in with our launch it isn't really a bug. Can we close this out?

Sure thing @MickinSahni !  You comment's sufficient for tracking.

Closing now.
