### ISSUE TITLE
Mask ICN in URL being logged in DataDog

### ISSUE THREAD

**Issue by JRRoof** [department-of-veterans-affairs/va.gov-team#77386]
## Description
DataDog logging is capturing ICN in URL.  ICN is considered PII and should be masked.

https://vagov.ddog-gov.com/apm/traces?query=env%3Aeks-prod%20AND%20resource_name%3A%22VAOS%3A%3AV2%3A%3AAppointmentsController%23index%22%20AND%20service%3Amhv-appointments%20AND%20operation_name%3Arack.request%20status%3Aerror%20&cols=service%2Cresource_name%2C%40duration%2C%40http.method%2C%40http.status_code%2Chost%2C%40http.url%2C%40_duration.by_service&fromUser=false&graphType=flamegraph&historicalData=true&query_translation_version=v0&shouldShowLegend=true&sort=time&spanID=1106825024073636340&spanType=all&timeHint=1709149859988&trace=AgAAAY3xRTCUIJr-cAAAAAAAAAAYAAAAAEFZM3hSVExFQUFET1U0SlVweWF4Z3Z3bQAAACQAAAAAMDE4ZGYxNGItMjBkMS00Yjk4LWFiMDAtYmRlODk4MTdlODgx&traceID=2809278883716934367&traceQuery=&view=spans&viz=stream&start=1709149800000&end=1709149860000&paused=true

---

## Acceptance Criteria
ICN is masked and no longer logged in DataDog 

### Design Assets
Not Applicable

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---
## How to configure this issue
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ajmagdub** [comment]
Verified that for a similar Datadog error logged, [DataDog Error trace](https://vagov.ddog-gov.com/apm/services/mhv-appointments/operations/rack.request/resources?env=eks-prod&fromUser=false&graphType=flamegraph&groupMapByOperation=null&panels=qson%3A%28data%3A%28activePanelKey%3Atrace%2Cresource%3A%28resourceName%3AVAOS%253A%253AV2%253A%253AAppointmentsController%2523index%2CresourceID%3Ac60cc56b55522312%29%2Ctrace%3A%28traceID%3A1499753381096549342%2CspanID%3A4062152960799179133%29%29%2Cversion%3A%210%29&resources=qson%3A%28data%3A%28visible%3A%21t%2Chits%3A%28selected%3Atotal%29%2Cerrors%3A%28selected%3Atotal%29%2Clatency%3A%28selected%3Ap95%29%2CtopN%3A%215%29%2Cversion%3A%211%29&shouldShowLegend=true&sort=time&spanID=4062152960799179133&spanViewType=errors&summary=qson%3A%28data%3A%28visible%3A%21t%2Cerrors%3A%28selected%3Acount%29%2Chits%3A%28selected%3Acount%29%2Clatency%3A%28selected%3Alatency%2Cslot%3A%28agg%3A95%29%2Cdistribution%3A%28isLogScale%3A%21f%29%2CshowTraceOutliers%3A%21f%29%2Csublayer%3A%28slot%3A%28layers%3Aservice%29%2Cselected%3Apercentage%29%29%2Cversion%3A%211%29&topGraphs=latency%3Alatency%2Chits%3Acount%2Cerrors%3Acount%2CbreakdownAs%3Apercentage&view=spans&start=1709502050080&end=1709588450080&paused=true) , the ICN was replaced by the ICN's one-way-hash

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFd0QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d8876a023006e513e111f9da6e90f4cb9d1adb6b/ICNs-replaced-w-hash.png" alt="ICNs-replaced-w-hash.png" />

**Comment by ajmagdub** [comment]
This ticket can be closed

**Comment by ajmagdub** [comment]
It is verified that the SHA256 digest of the ICN is replacing the ICN in the URL.

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket.
