### ISSUE TITLE
FE | Profile| General maint | GA4 Documentation for Custom Events

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#77385]
> [!WARNING]
> Deadline of 4/5/2024

## Background

With the migration to GA4 platform has requested we document our custom events in a spreadsheet.

We've already done most of the work here we'll just need to reformat into the report they've asked for:
- #73743

## Slack thread for additional context 

<!subteam^S062LBWRSMN|@auth-exp-whole-team> <https://dsva.slack.com/archives/C1Q4294JJ/p1709064017751029|very important announcement regarding analytics>

[Slack Message](https://dsva.slack.com/archives/C909ZG2BB/p1709064068638979?thread_ts=1709064068.638979&cid=C909ZG2BB)

## Tasks 
- [ ]

**Comment by adamwhitlock1** [comment]
https://docs.google.com/spreadsheets/d/1TddE_w7xUM8xfysIarLcFSdtJz1NZFsf2ZMzjxzvSW4/edit#gid=0

I have filled out the profile's events on the above spreadsheet. I can work on My VA's events as well if they haven't done this yet, since it looks like each product is supposed to fill out their own.
