### ISSUE TITLE
Contact Governance Team about Links to Google

### ISSUE THREAD

**Issue by BSmolensky** [department-of-veterans-affairs/va.gov-team#77387]
On 2/28/24, Andrea announced that teams should not be linking out to Google Drive on the PW because VA folks cannot view those links. We reached out to her to find out if we need to launch block those or not.  Previously, we were just flagging the links with a "limited access if using the VA network" note. But Andrea came back and said that we should now be Launch Blocking links to Google.

She also requested an audit of the PW for link to Google. This ticket is part of that audit. 

We already know that the Governance Team links out to google. So we need to contact them to leet them know that we will be LBing these links moving forward. 

### TASKS

- [x] Contact PM of Gov Team via Slack. 

### DEFINITION OF DONE

- [x] PM of Gov Team is now aware of this change.

**Comment by jknipes** [comment]
Tasks completed, moving to _Done_
