### ISSUE TITLE
[Bug] AMADR2 - Decision Reviews page styling/content issues

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#7741]
## What happened?
On [Drupal Decision Review preview-page](http://preview-prod.vfs.va.gov/preview?nodeId=3071), the following copy/styling issues were found:

1.  In **Mark your calendar** gray-box, the text "one year" is not displayed in **bold**.
2.  Under **Request a decision review or appeal**, the **Decision review options** (1st 3 sections) body-texts are inaccurate.
3.  Under **Manage your decision reviews and appeals** section > **Manage your legacy VA appeal** subsection, 2nd phrase of body-text copy is inaccurate.

NOTE: The preview page under test shows "Last updated April 7, 2020," while #6799's latest copy doc [decision-reviews-hub-page_copy-v1.5.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4381922/decision-reviews-hub-page_copy-v1.5.docx) was in a Comment dated 3/25/2020.  No subsequent ticket comments called out  any copy-updates specific to the issues I've found here during testing.

## Specs:
- Bug is browser-/device-agnostic
- Preview-page is unauthenticated BUT requires SOCKS-proxy.

## Steps to Reproduce
- URL: http://preview-prod.vfs.va.gov/preview?nodeId=3071
- Test User _(if applicable)_: N/A

Observe the copy issues as illustrated below.

### Screenshots

![Screen Shot 2020-04-07 at 10 17 05 PM](https://user-images.githubusercontent.com/587583/78747426-3c8bdc00-791e-11ea-81f5-570fd5d805cb.png)
-----
![Screen Shot 2020-04-07 at 10 30 01 PM](https://user-images.githubusercontent.com/587583/78748027-c6887480-791f-11ea-92e0-2387dadcfe67.png)
-----
![Screen Shot 2020-04-07 at 10 44 14 PM](https://user-images.githubusercontent.com/587583/78748772-ae195980-7921-11ea-879a-0f7df607168d.png)

## Desired behavior

From copy doc [decision-reviews-hub-page_copy-v1.5.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4381922/decision-reviews-hub-page_copy-v1.5.docx), here are the screenshots of the relevant snippets showing correct copy/styling:

![Screen Shot 2020-04-07 at 10 38 48 PM](https://user-images.githubusercontent.com/587583/78748328-9f7e7280-7920-11ea-9558-9b8c1e8a35b7.png)
-----
![Screen Shot 2020-04-07 at 10 39 47 PM](https://user-images.githubusercontent.com/587583/78748398-d0f73e00-7920-11ea-900a-5393a18a4490.png)
-----
![Screen Shot 2020-04-07 at 10 47 21 PM](https://user-images.githubusercontent.com/587583/78748836-d43ef980-7921-11ea-9a5e-5750a00fa51d.png)

## Acceptance Criteria
\[see **Desired behavior** above]

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by MickinSahni** [comment]
@RLHecht @lwalsh617 to review and confirm the right behavior given the other changes.

**Comment by tlei123** [comment]
@lwalsh617 , I just wanna highlight the NOTE in the main Description up top \[the preview-page (last updated yesterday) is about 2 weeks newer than the copy doc I was referencing for my test-run]...

IF all the specific issues I listed up there are now outdated/invalid, please just add a Comment to that effect and Close this Bug.

Feel free to ping me in your #vsa-public-websites Slack-channel if you have further questions/problems/comments.

Thanks much!

**Comment by lwalsh617** [comment]
@tlei123 @MickinSahni - The copy inaccuracies were due to the fact that Jen L. made copy edits in Drupal after copy deck was finalized, so we don't have them documented. Thanks L

**Comment by tlei123** [comment]
> @tlei123 @MickinSahni - The copy inaccuracies were due to the fact that Jen L. made copy edits in Drupal after copy deck was finalized, so we don't have them documented. The other edit (bold "one year") is done. We're all set on this ticket. Thanks for the sharp eyes, Tze!
> L

Validated "one year" is now bold.  Closing now.

You're welcome & thank YOU for clarification, @lwalsh617 !
