### ISSUE TITLE
[Bug] COVID FAQ Question Custom Dimension

### ISSUE THREAD

**Issue by jonwehausen** [department-of-veterans-affairs/va.gov-team#7742]
# Analytics Implementation or QA Request

## Description
- There are a few instances of where the custom dimension "Frequently Asked Question" is pulling in data other than questions
![image.png](https://images.zenhubusercontent.com/5d234c844828605fd8bf8ede/1b90d569-7c37-4914-ab7c-7c93311d032d)
- May be worth doing a small JS to check for if the value being passed contains a "?" at the end

## Acceptance Criteria
- [ ] Restrict custom dimension value to only include questions
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by bsmartin-ep** [comment]
@jonwehausen - Looks like the markup and structure of the FAQ page has changed a bit.  I updated to use the new attributes and elements....

https://www.googletagmanager.com/start_preview/gtm?uiv2&id=GTM-WFJWBD&check_preview_status=1&gtm_auth=zuLpSIqr6xR4MrVN02KDDA&gtm_preview=env-830&gtm_debug=x

**Comment by jonwehausen** [comment]
### QA Testing
### Test Case 1 - ✅ **PASSED**
1. Clicked on a link within one of the newly added questions
![image](https://user-images.githubusercontent.com/48527022/78817996-f9734c80-79a1-11ea-8f7a-8c0bde65a9e0.png)

### Test Case 2 - ✅ **PASSED**
![image](https://user-images.githubusercontent.com/48527022/78818113-2293dd00-79a2-11ea-9790-cbb96d7090bf.png)

### Test Case 3 - ✅ - PASSED
1. Test case that was previously causing issues on click - no longer causing issue
![image](https://user-images.githubusercontent.com/48527022/78818361-8b7b5500-79a2-11ea-8393-dd8326cfe199.png)

**Comment by jonwehausen** [comment]
@bsmartin-ep Publishing out -- Do you want to take a stab at engaging with Nick on getting the conversation started to convert this over to DL events?

**Comment by bsmartin-ep** [comment]
I reached out to Nick about moving this to the data layer.  Closing.
