### ISSUE TITLE
CF: Complete file Content/UI updates based on UX review

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#7743]
As a developer, I need to complete a final pass of updates for the Caution Flag display in the Comparison Tool so that the information is displayed in a manner that meets content and usability standards.

## Assumptions:
1. This work is completed behind a toggle so that it is only available in the staging environments and below.
2. The fixes will be reviewed with UX before this story can be closed.

## Acceptance Criteria
1. All items in supporting artifact # 1 are resolved.

## Supporting Artifacts:
1. [UX GIBCT Staging Profile Page Review 04.07.20.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4451084/UX.GIBCT.Staging.Profile.Page.Review.04.07.20.xlsx)

2. Item # 1:
<img width="1035" alt="ID 1 - School Closing alert missing text" src="https://user-images.githubusercontent.com/48260534/78797379-9ffd2480-7985-11ea-9249-fd83d1ed569a.png">

3. Item # 2:
<img width="957" alt="ID 2 - Campus closing URL" src="https://user-images.githubusercontent.com/48260534/78797373-9ecbf780-7985-11ea-9c2d-afda99d9ab96.png">

4. Item # 3:
![ID 3 - Single Bullet List](https://user-images.githubusercontent.com/48260534/78797588-e3579300-7985-11ea-97d7-aa42d9cf4e8a.jpg)

5. Item # 4:
<img width="949" alt="ID 4b - Bullet list indentation" src="https://user-images.githubusercontent.com/48260534/78797383-a095bb00-7985-11ea-84c5-353b5f3bead1.png">
<img width="417" alt="ID 4a - Bulleted lists in Sketch Pattern Library" src="https://user-images.githubusercontent.com/48260534/78797386-a095bb00-7985-11ea-82e8-5fc3706e863a.png">

6. Item # 5:
<img width="863" alt="ID 5 - Alert yellow banding" src="https://user-images.githubusercontent.com/48260534/78797378-9ffd2480-7985-11ea-8ee9-db8e8b49187e.png">

7. Item # 6:
<img width="920" alt="ID 6 - Alert right padding" src="https://user-images.githubusercontent.com/48260534/78797376-9f648e00-7985-11ea-9a09-980d45280a02.png">

8. Item # 7:
<img width="734" alt="ID 7" src="https://user-images.githubusercontent.com/48260534/78797369-9d023400-7985-11ea-90f5-62b0173598d6.png">

**Comment by dmccurdybah** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/12164

Can be tested on vets-website branch `caution-flag-updates`

**Comment by sonntag-adam** [comment]
2. ![Screen Shot 2020-04-10 at 11.57.18 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/466fa2d9-45dc-40fd-9d6e-5ad2f5d21055)

**Comment by sonntag-adam** [comment]
3. 
![Screen Shot 2020-04-10 at 12.04.28 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/623f2d24-6490-44ff-9b25-0de73e882603)

Navigates correctly to https://www.an.edu/locations/

**Comment by sonntag-adam** [comment]
4. Bullets gone for single
![Screen Shot 2020-04-10 at 12.06.22 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/0dd44a97-64c3-4df6-bbf8-3ce0aad243cd)
##
![Screen Shot 2020-04-10 at 12.06.32 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/aec2124f-1447-47e7-b8eb-d9f3b97da60d)

**Comment by sonntag-adam** [comment]
5. ![Screen Shot 2020-04-10 at 12.07.44 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/f46a9c41-fbcb-43bc-b949-fb9d3c7f56fe)

**Comment by sonntag-adam** [comment]
6.![Screen Shot 2020-04-10 at 12.14.09 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/e66a4496-78ba-4584-8f5b-87315649677c)

**Comment by sonntag-adam** [comment]
7. ![Screen Shot 2020-04-10 at 12.17.35 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/e9104d8a-cb0b-4264-a94b-c5ce6d564d8f)
##
![Screen Shot 2020-04-10 at 12.17.42 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/3d085154-6e9f-4424-a10e-d2df762117f6)

**Comment by sonntag-adam** [comment]
8. [Uploading... Screen Shot 2020-04-10 at 12.19.09 PM.png ]

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/283&group_by=cases:section_id&group_order=asc

**Comment by ccruzgra** [comment]
Hi @RickyTheFace and @Adam For supporting artifact #3, clicking on the Dodge City Community College's school’s link from the accordion still pulls up https://staging.va.gov/gi-bill-comparison-tool/profile/www.dc3.edu.

**Comment by sonntag-adam** [comment]
Fix for #3 is in staging. @ccruzgra please verify this is correct.

**Comment by ccruzgra** [comment]
@sonntag-adam I took a look at several institutions and the update for #3 checks out.

**Comment by sonntag-adam** [comment]
Closing story.
