### ISSUE TITLE
On mobile devices, hide the "More in this section" button for pages without sidebars

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#7744]
On mobile devices, a sticky button labeled `More in this section` is revealed for users to open the side nav. However, it is showing even on pages without a sidebar, revealing an empty panel. We should hide this if there isn't a sidebar.

More context - https://dsva.slack.com/archives/C52CL1PKQ/p1586301934145200

### Example

`/change-direct-deposit`

![image](https://user-images.githubusercontent.com/1915775/78794156-5f031100-7981-11ea-82d4-ab420a0a0978.png)

### Acceptance criteria
- [ ] `More in this section` button does not show on pages without sidebars

**Comment by MickinSahni** [comment]
2020-04-09 PW Standup
- Can be validated after today's deploy!

**Comment by MickinSahni** [comment]
Validated
![image](https://user-images.githubusercontent.com/13204473/79004449-c7d5bf00-7b22-11ea-87e1-2ab963efc1f7.png)
