### ISSUE TITLE
[bug spike] SC | 422 schema validation error

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#77451]
## Issue Description

On Feb 29, 2024, we saw a 422 on SC submit.  See [DD Trace](https://vagov.ddog-gov.com/apm/trace/2529085911267223478?colorBy=service&env=eks-prod&graphType=flamegraph&shouldShowLegend=true&sort=time&spanID=35865359509456473&spanViewType=errors&timeHint=1709225567356.082&view=spans). Although the request to LH to create a SC was [successful](https://vagov.ddog-gov.com/logs?query=trace_id%3A2529085911267223478%20&cols=service%2Chost&event=AgAAAY31yGVkng1dywAAAAAAAAAYAAAAAEFZMzF5R3RDQUFCV2g3RFV1YU5pZkFDdgAAACQAAAAAMDE4ZGY1Y2EtMGIzYi00YzRlLWJhYTUtMWE2OTQ1NjU5MjU2&fromUser=true&index=&messageDisplay=inline&refresh_mode=paused&storage=hot&stream_sort=desc&viz=stream&from_ts=1709225408637&to_ts=1709225708637&live=false), LH's response triggered a schema validation failure on our end. So, the Veteran thinks they were blocked from submitting, when in actuality their submission was a success. There is no corresponding error in Sentry, and it is unclear why the schema validation failed. We should improve our logging on this front. Veteran's SIP id is `10398186`

**Comment by data-doge** [comment]
May be related to https://github.com/department-of-veterans-affairs/va.gov-team/issues/74606

**Comment by data-doge** [comment]
Incident created here: https://dsva.slack.com/archives/C5AGLBNRK/p1709305896778499

**Comment by anniebtran** [comment]
closing this as we haven't seen this kind of problem pop up in the last few months — did see a 422 in March for a previously documented error around start/end dates that I believe we've already addressed (@Mottie should have more context around that, I think)
