### ISSUE TITLE
Fix failing unit test - SelectDate1Page

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#77461]
## Description
This unit test is failing CI & is a merge blocker for `vets-website` PRs: `src/applications/vaos/tests/covid-19-vaccine/components/SelectDate1Page.unit.spec.js`

VAOS vaccine flow: SelectDate1Page
       should fetch slots when moving between months:

---

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket.
