### ISSUE TITLE
Complete SSOe TestRail Cases in Chrome

### ISSUE THREAD

**Issue by marriej** [department-of-veterans-affairs/va.gov-team#7746]
Complete test cases in the Chrome v. 80 Test Run for outbound SSOe.
Cases are located [here].(https://dsvavsp.testrail.io/index.php?/runs/view/241&group_by=cases:section_id&group_order=asc&group_id=60)

[Test Accounts](https://docs.google.com/document/d/1Qro8ry9xDp9DAig-jsiDV-q86IgSIDOxxjvNkp2DMNY/edit#)

See #6835 for TestRail documentation.

**Comment by ericbuckley** [comment]
@marriej I think we should move this back to ready/backlog until the IAM team has implemented the fixes needed for us to test.  What do you think?

**Comment by bridgethapner** [comment]
This seems like a good call @ericbuckley ☝️ --- Although I don't fully understand how IAM's fixes relate to our work from the technical perspective, I definitely don't want to pass any cases that later might fail since things are in flux.

**Comment by marriej** [comment]
@bridgethapner here are the cases called out from our staging pre-review:

Outbound SSO Test Cases
T1890 ID.me LOA3 VA.gov modal UX
T1920 SSOe Down Message

Scheduling page alert test cases
T1910: View My VA Health and VAOS alert
T1911: Do not view My VA Health and VAOS Alert
T1914: Navigate to My VA Health [No SSOE session]
T1915: Navigate to VAOS [No SSOE session]

Standalone Sign In Page test cases
T1916: Sign in with MHV
T1919: Sign out of My VA Health to signed out state

**Comment by bridgethapner** [comment]
Thank you @marriej! 

Can we remove the **Scheduling page alert test cases** for now? My memory is we didn't finish that work b/c Cerner will change before launch. 

@ericbuckley A couple of Qs for you (no urgency)
1. Do you recommend I retest cases that already passed (T1890 ID.me LOA3 VA.gov modal UX) or are we set with tests that already passed? 
2. Can we test T1920 SSOe Down Message? My memory is that we don't have a mechanism to say SSOe is down in place yet. 

I will proceed with testing the Standalone Sign In Page test cases (below) now:
- T1916: Sign in with MHV
- T1919: Sign out of My VA Health to signed out state

**Comment by ericbuckley** [comment]
@bridgethapner I would say for tests that have already passed, don't worry about retesting at this point.  We will probably want to retest after IAM has finished making changes on their side, but @marriej might want to weigh in.

It should be possible to test the SSOe down message.  However we'll have to coordinate with the VSP team on this one, as they need to make a configuration change to our PagerDuty account in order of that message to be displayed.  Take a look at the second precondition statement I have here https://dsvavsp.testrail.io/index.php?/cases/view/428&group_by=cases:section_id&group_order=asc&group_id=60

**Comment by marriej** [comment]
@bridgethapner I agree with Eric on the tests that already passed. 
Also agreed that we can remove the scheduling pages tests from the mix.
Thanks,
Alexis

**Comment by bridgethapner** [comment]
@marriej Just realized I don't think we can run **T1919: Sign out of My VA Health to signed out state**. We can test the sign-out page for accessibility, but as My VA Health isn't launching yet I think we can take this test case off the table. Thoughts?

**Comment by marriej** [comment]
@bridgethapner 
Agreed, I am writing up a little blurb to go with our Accessibility items to the staging review team.
