### ISSUE TITLE
CF:  Exclude institutions with warnings filter not excluding cautionary warnings

### ISSUE THREAD

**Issue by sonntag-adam** [department-of-veterans-affairs/va.gov-team#7747]
Navigate to https://staging.va.gov/gi-bill-comparison-tool/search?category=school&name=DODGE+CITY+COMMUNITY+COLLEGE

Observe that when selecting the filter checkbox "Cautionary warnings (Learn more)
Exclude institutions with warnings" it doesn't hide DODGE CITY COMMUNITY COLLEGE

![bug.gif](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/c3fae6f4-8bb0-4d61-a9aa-c7e82bea703a)

## Steps to Reproduce
- Have only production version in GIDs -> use filter -> filter works
- Generate preview version in GIDs -> use filter -> filter does not work

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/637

**Comment by sonntag-adam** [comment]
In staging, testing passes QA.

**Comment by sonntag-adam** [comment]
Re-opened as its occurring again in staging.

**Comment by sonntag-adam** [comment]
In staging, closing bug.

**Comment by zurbergram** [comment]
Reopening as this can still occur, added steps to reproduce

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/642
