### ISSUE TITLE
[Design] Explore UXPin for building clickable prototypes for User Testing

### ISSUE THREAD

**Issue by jamiefiore** [department-of-veterans-affairs/va.gov-team#77470]
Explore UXPin's capabilities and interface to discover if we can effectively use this tool as a team to create clickable prototypes for user testing. These prototypes need to accommodate:

- Almost unlimited variable components/ data
- Allow for text fields that users can type in their own answer
- Easily import Figma files to add the interactive elements
- Not have a need for engineering knowledge
- Look and function similar to like a production form

##Assumptions
- UXPin is a low code solution that can help us add interactivity to the hi-fi mockups that we produce in Figma
- UXPin has the ability to handle large amounts of variable data fields
- HTML, CSS and other types of programming language is help to have not necessary to have in order to create a clickable prototype that can satisfy our requirements for user testing. 

##Definition of Done
- Complete a demo of a small portion of the 1010D in UXPin
- Decide whether UXPin is a viable solution

**Comment by dhill802** [comment]
@jamiefiore If UXPin is the tool of choice for prototyping, do you know which version of the tool has the functionality you need? Essential or the Advanced version? https://www.uxpin.com/pricing

**Comment by jamiefiore** [comment]
@dhill802  We would need the Advanced version because it includes Conditional logic, expressions, and variables capabilities. This allow us to build a working form that would function similar to how a production form would work and allow us to capture the data and feedback we need from user testing without having to use engineering resources to develop each form in staging. 
We explored Figma for this purpose but it's prototyping capabilities are very limited. 

We would like to have a UXPin license for all 5 of our designers because we often share design work and can find ourselves working on more than one form prototype at a time. Having all of the designers on UXPin would help us move faster within the collab cycle and prevent blockers.

**Comment by jamiefiore** [comment]
@dhill802  We decided not to explore this anymore. We can close this ticket out now.
