### ISSUE TITLE
Track backup submissions in datadog dashboard

### ISSUE THREAD

**Issue by sortizsh** [department-of-veterans-affairs/va.gov-team#77481]
## Issue Description
We would like to track the volume of backup submissions on the datadog dashbaord, with the intent to decrease them over time. Similarly, it would be great to have a high-level submission volume and submission error rate calculated, similar to the dependency one. 
https://vagov.ddog-gov.com/dashboard/ygg-v6d-nza/benefits-form-526-disability-compensation?refresh_mode=sliding&view=spans&from_ts=1704464186318&to_ts=1707142586318&live=true

https://vagov.ddog-gov.com/dashboard/vad-969-xqc/benefits-dependents-686674?refresh_mode=sliding&view=spans&from_ts=1704550586320&to_ts=1707142586320&live=true

I think that could mean combining it with some of the monitors on this dashboard: https://vagov.ddog-gov.com/dashboard/u9b-62v-t48/benefits-526-backup-submissions?refresh_mode=sliding&view=spans&from_ts=1704551156963&to_ts=1707143156963&live=true

slack convo: https://dsva.slack.com/archives/C04KW0B46N5/p1707143115220039

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by lisacapaccioli** [comment]
I think this is the start of the request for priority "Improving monitoring, analytics, dashboards for submission status". I will hold on to this until I can confirm.

**Comment by lisacapaccioli** [comment]
Thomas Blackwell - ticket is complete, 2 dashboards, with different focus on same topic

[https://vagov.ddog-gov.com/dashboard/u9b-62v-t48/benefits---526-backup-submissions?fro[…]w=spans&from_ts=1717855882634&to_ts=1720447882634&live=true](https://vagov.ddog-gov.com/dashboard/u9b-62v-t48/benefits---526-backup-submissions?fromUser=false&refresh_mode=sliding&view=spans&from_ts=1717855882634&to_ts=1720447882634&live=true)

https://vagov.ddog-gov.com/dashboard/t6f-wq7-sw6/benefits---526ez---issue-research?fro[…]w=spans&from_ts=1720361531194&to_ts=1720447931194&live=true
