### ISSUE TITLE
FE | Profile | RX Shipment Maint.| Update list of facilities that send text messages 

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#77482]
### Background

Update our code to include the new facilities that support text for RX shipments 

[power BI report ](https://app.powerbigov.us/groups/me/apps/edb20dd9-adff-4cdb-9e08-35ecc7e2ea94/reports/44d4a7e8-0c78-4498-941c-066651f4042c/ReportSection?ctid=e95f1b23-abaf-45ee-821d-b7ab251ab3bf)

I pulled the below in february may be worth re-pulling: 

Station # | Station Name | RX Tracking | values in the code
-- | -- | -- | --
593 | VA Southern Nevada Healthcare System | TRUE | #N/A
636A8 | Iowa City HCS | TRUE | #N/A
678 | Southern Arizona VA Health Care System | TRUE | #N/A

There were no removals from the list 

### Tasks

- [ ] Add the new locations

### Acceptance criteria

- [ ] New facility has been added to the prescription shipment notification preference. < confirm by adding in the snippet of code as a comment 

### report run on 5/16 
[data.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/15337396/data.xlsx)

**Comment by adamwhitlock1** [comment]
This is merged so closing out.
