### ISSUE TITLE
AWS access for Dan Hinze

### ISSUE THREAD

**Issue by hinzed1127** [department-of-veterans-affairs/va.gov-team#77484]
### COR Name

Cecila Lee

### Vendor Onboarding Representative Name

Other - please specify in 'Additional Notes'

### Your Name

Dan Hinze

### Your Email

dan.hinze@adhocteam.us

### Team, Role, and Company of the target individual

BTSSS Team (Health tools), Ad Hoc, Sr. Software Engineer

### Product Manager (PM) name and email

Ayush Chakravarty, ayush@adhocteam.us

### Product Owner (PO) name and email

Kay Lawyer, katherine.lawyer@va.gov

### Desired AWS Access

I need to be able update/add params. I should have the same permissions that my teammate Kevin Duensing has.

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

<img width="868" alt="Screenshot 2024-03-01 at 10 33 28 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/13280995/b535ede5-2f76-4f8c-9596-a9d50c83f793">

### Additional Notes

Onboarding Representative was Megan Gatesman of Booz Allen Hamilton

Re access expiration, the BTSSS project is ongoing without a set end date. I will be working on it for the foreseeable future.

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [x] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by Mandalorian-Oddball** [comment]
User is in atlas.
