### ISSUE TITLE
URGENT [UX/FE/Content] 10-10EZR - Update PRA statement done on 3/4

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#77498]
As a Veteran, I would like up-to-date and accurate Paperwork Reduction information so that I know what to expect from VA forms.

- [x] See [explainer from Heather](https://dsva.slack.com/archives/C05QKRZGHFS/p1709310161244579)
- [x] Update Figma with new PRA statement
- [x] Update Privacy Act modal in the OMB Section of EZR
- [x] Release to Prod
- [x] **Must be done on 3/4**
- [x] **Success: PRA statement is updated on Production by 3/5**

[OMB_PRA Approved - VA Form 10-10EZR_PACT Act - Sec 103 revisions_MAR 2024.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXFsQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f43c9f2186e8a8d0209bc96b5f49f81ff10101df/OMB_PRA%20Approved%20-%20VA%20Form%2010-10EZR_PACT%20Act%20-%20Sec%20103%20revisions_MAR%202024.pdf)

**Comment by mkerns1** [comment]
Update: This PR has been created to merge these changes into the main branch. Once checks in GitHub run successfully this will be able to be merged in to main and deployed during Monday 3/4's deployment.

**Comment by emily-brown34** [comment]
thanks for the update matt, can we also check off the ACs above so we are tracking what's remaining/when
