### ISSUE TITLE
Update to new PDF using checkboxes (instead of radio buttons)

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#77490]
## Issue Description

- The VBA team has recently updated the Pension PDF form to one that now uses checkboxes (instead of radio buttons)
- This update to checkboxes as answers will not change any existing rules about the number of options they can select._
- [Link to spike for this task](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/gh/department-of-veterans-affairs/va.gov-team/76388)
- Link to the new PDF form: https://www.vba.va.gov/pubs/forms/VBA-21P-527EZ-ARE.pdf

All radio buttons have been replaced with checkboxes:
<img width="691" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMys4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eb21fbf1725b446d1c925d71d901cdf7da77f640/image.png" alt="image.png" />

## To do
- Remove radio buttons and replace with checkboxes and make sure the PDF submitted via Pension form contains checkboxes as per the updated PDF form (see link above)

---
## Acceptance Criteria

- The online Pension form will be mapped to the new version of the Pension PDF form that replaced radio buttons to checkboxes. [Link to the new PDF form here](https://www.vba.va.gov/pubs/forms/VBA-21P-527EZ-ARE.pdf).

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/77490?planning-poker) with Zenhub @danlim715 @mjknight50 @scottsdevelopment @TaiWilkin @wayne-weibel

**Comment by danlim715** [comment]
Unfortunately, the circle fields and square fields are not toggle-able via a metadata setting. Circle fields are radio buttons and square fields are checkboxes, and those 2 field types fundamentally behave differently. We would have to rename every checkbox field in the PDF and rewrite large portions of the backend code to accommodate checkboxes instead of radio button list groups, which would turn this ticket from a 1 pointer to something like an 8 or 13 pointer.

**Comment by buddhima-coforma** [comment]
This change is needed so let's proceed with it. Here's a reference conversation https://dsva.slack.com/archives/C05MS96P6P2/p1710265938433459

**Comment by danlim715** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-api/pull/15998

**Comment by aplatt-coforma** [comment]
Looks good
[content.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1VQQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7c9debf00716bbad40e28c8934428abadbb375b5/content.pdf)
