### ISSUE TITLE
Qualitative Data Request: Medallia Data - Higher-Level Review (VA Form 20-0996)

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#77503]
### Data Type Requested

User Surveys

### Data Source Type

Medallia

### Date Range Start

01-01-2020

### Date Range End

03-01-2024

### Product Name(s)

Decision Review Form: Higher-Level Review (VA Form 20-0996)

### Product Description

If a Veteran disagree with a VA decision, them or their representative can request a new review of their case by a higher-level reviewer. The reviewer will determine whether an error or a difference of opinion changes the decision. Veteran's can’t submit new evidence with a Higher-Level Review.

### Survey URL(s), key term(s), case category or type

URLs: Everything under and including [va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/]

### File Delivery Format

One file, different tab for each term/URL

### Word Cloud

Yes

### VA Email Address(es)

sade.ragsdale@va.gov

### Add Assignee and Labels

If not already done so, please ensure @newworld2616 is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by newworld2616** [comment]
Hi, have shared the requested data. Let me know if you have any questions. Thank you!
