### ISSUE TITLE
Qualitative Data Request: Medallia Data - Supplemental Claim (VA Form 20-0995)

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#77504]
### Data Type Requested

User Surveys

### Data Source Type

Medallia

### Date Range Start

01-01-2020

### Date Range End

03-03-2024

### Product Name(s)

Decision Review Form: Supplemental Claim (VA Form 20-0995)

### Product Description

If a Veteran disagrees with a decision on their claim, they may file a Supplemental Claim.

### Survey URL(s), key term(s), case category or type

URLs: Everything under and including [va.gov/decision-reviews/supplemental-claim/file-supplemental-claim-form-20-0995/]

### File Delivery Format

One file, different tab for each term/URL

### Word Cloud

Yes

### VA Email Address(es)

sade.ragsdale@va.gov

### Add Assignee and Labels

If not already done so, please ensure @newworld2616 is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by newworld2616** [comment]
Hi, I have shared the requested data. I am working on the rest of the requests. Thank you.
