### ISSUE TITLE
Publish transfer of benefits Q&A

### ISSUE THREAD

**Issue by aprocik1** [department-of-veterans-affairs/va.gov-team#77509]
## Description
We need to migrate the content on [this legacy](https://www.benefits.va.gov/GIBILL/FGIB/Reallocation.asp) page about transferring benefits after a family member dies.

We need to condense the content into a single Q&A, and then place it on these modern pages:

- [Transfer your Post-9/11 GI Bill benefits](https://www.va.gov/education/transfer-post-9-11-gi-bill-benefits/)
- [Transferred education benefits for family members](https://www.va.gov/education/survivor-dependent-benefits/transferred-benefits/)

**Note:** If we can't condense the content into a single Q&A, we can create an R&S FAQ page to link on the modern pages.

### Step 1
- [x] DB: Provide recommendation on single Q&A v. R&S FAQ page
- [x] AP: Review recommendation
- [x] AP, BP, DB: Align on recommendation

### Step 2
- [x] DB: Draft content in Drupal
- [x] AP: Review content in Drupal
- [x] AP: Share Drupal preview with BP
- [x] BP: Review content in Drupal
- [x] AP: Update content with BP feedback
- [x] DB: Share Drupal preview with stakeholders
- [x] DB: Update content in Drupal with stakeholder feedback
- [x] MZ / ST: Copyedit and publish

## Criteria
- [x] Legacy content has been published on the modern site

**Comment by d-beyer** [comment]
@aprocik1 To determine if this would be an FAQ or a Q&A on a page, I did a [quick rough-out of the content](https://docs.google.com/document/d/1PCmAIajD3rbf510Oqz7ToCD6DOwN6RehLk7nXVwCh50/edit?usp=sharing). Based on how well it condensed, I think it could be a single Q&A. I could see an argument for an FAQ page though. It would allow us to do a bit more formatting of the process. Let me know what you think!

**Comment by aprocik1** [comment]
Thanks @d-beyer! I agree with you, I think this could be a single Q&A. I had to re-read the legacy page to better understand how the content could be condensed, and that helped me realize that there are two different user stories we need to account for in our content. I created a V2.1 and V2.2 of the Q&A to account for those user stories on the relevant modern pages. Please review and let me know if those align with your understanding of the legacy page. And please work your writer magic on what I've drafted! Any and all of your direct edits are welcome.

**Comment by aprocik1** [comment]
@d-beyer, thanks for your work on this! I made a few small edits to each page. Here are the Drupal previews:

- [Transferred education benefits for family members](http://preview-prod.vfs.va.gov/preview?nodeId=44698)
- [Transfer your Post-9/11 GI Bill benefits](http://preview-prod.vfs.va.gov/preview?nodeId=952)

I like your placement of Q&A on the first page. And I think we should leave the DEERS content where it is for now, since the feature content boxes already have a note in them. Let's see if Beth says anything about that. And let's ask her about RAPIDS offices. She may have context for us that we don't know about.

Let me know if you're okay with me sharing these pages with her!

**Comment by d-beyer** [comment]
@aprocik1 Send it!

**Comment by aprocik1** [comment]
Update: I shared these pages with Beth today via Slack.

**Comment by aprocik1** [comment]
Update: Beth made a few small edits to both Q&As. And I followed up with Megan to confirm our use of "ID" in both notes.

**Comment by aprocik1** [comment]
@d-beyer, these preview links are ready to share with stakeholders:

- [Transfer your Post-9/11 GI Bill benefits](http://preview-prod.vfs.va.gov/preview?nodeId=952)
- [Transferred education benefits for family members](http://preview-prod.vfs.va.gov/preview?nodeId=44698)

In your email, I would remind them that they have to be on the VA network to access previews and that links don't work on preview pages. And I would include screenshots of the two Q&As we updated to focus their review on the only changes to these pages. Thanks!

**Comment by d-beyer** [comment]
Update: I shared the previews of the revised Q&As with stakeholders yesterday.

**Comment by d-beyer** [comment]
Update from 05.01 meeting with SMEs:
- You can transfer benefits at *any* time, which our draft doesn't reflect.
- However, they didn't feel confident about whether it was true *in context*, so we may need them to review the draft of the page in full.

**Comment by d-beyer** [comment]
@aprocik1 I tweaked the text based on SME input. Since a Veteran can transfer eligible benefits at any time, I removed the requirement text on that page, and used the question rephrasing we agreed on with Beth on the other page.

We can talk about this at our sync, but I think we can move forward.

**Comment by d-beyer** [comment]
Hi @megzehn -- We revised Q&As on two modern pages in order to migrate a single legacy page. They are ready for copyedit and publishing. You may want to do this in conjunction with #78531 since that is another minor text change to the same pages.

- [Transfer your Post-9/11 GI Bill benefits](http://preview-prod.vfs.va.gov/preview?nodeId=952) (Q&A: What if my dependent doesn’t use their transferred benefits?)
- [Transferred education benefits for family members](http://preview-prod.vfs.va.gov/preview?nodeId=44698) (Q&A: Can another eligible dependent use my transferred benefits?)

**Comment by megzehn** [comment]
Update: I reviewed and published these changes! Thank you, @d-beyer!
