### ISSUE TITLE
Qualitative Data Request: Medallia Data - Request a Board Appeal (VA Form 10182)

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#77505]
### Data Type Requested

User Surveys

### Data Source Type

Medallia

### Date Range Start

01-01-2020

### Date Range End

03-03-2024

### Product Name(s)

Request a Board Appeal (VA Form 10182)

### Product Description

When Veterans choose this option, They're appealing to a Veterans Law Judge at the Board of Veterans’ Appeals in Washington, D.C. A judge who’s an expert in Veterans law will review their case.

### Survey URL(s), key term(s), case category or type

URLs: Everything under and including [va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182/]

### File Delivery Format

One file, different tab for each term/URL

### Word Cloud

Yes

### VA Email Address(es)

sade.ragsdale@va.gov

### Add Assignee and Labels

If not already done so, please ensure @newworld2616 is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by newworld2616** [comment]
Hi, I have shared the requested data. Thank you!
