### ISSUE TITLE
Make newsletter signup pattern on landing page accessible

### ISSUE THREAD

**Issue by danbivins** [department-of-veterans-affairs/va.gov-team#77515]
### User story

As a Veteran, I want to be able to subscribe to the MHV newsletter in an accessible way and in a new tab, so that my logged-in status on VAgov remains clear.

### Notes
- [Patrick noted slack in Slack](https://dsva.slack.com/archives/C0581MN69TJ/p1709149979620659) that "once the user completes the newsletter sign up, there is no clear path back to VA.gov" and "this causes a navigational issue as well as possible security issue"
- security: the VAgov session remains active even after the form submission navigates the user to the GovDelivery website for newsletter signup. Leaving the VAgov tab open will help Veterans realize this behavior.
- a11y determination: the current single-field sign-up form on the MHV landing page is not materially honest about its function (navigating to a new page)

Tasks:
- Get CAIA input on copy if needed
- Design
- Implement
- Ally review
- UX review

## Acceptance criteria

- Beneath the H2 for “subscribe to My HealtheVet updates”, a materially honest link opens the GovDelivery signup website in a new tab
- Design and a11y review
- Development
- QA

**Comment by sterkenburgsara** [comment]
Synced with @danbivins today & we determined the following

**Problems with current state:**
* button is doing two things at once, which breaks VADS guidelines (navigates and submits content)
* button should not also navigate the user (this is not materially honest)
* button has inaccurate link text. The word "submit" is not accurate - the email address supplied gets inputted into a form on the GovDelivery signup page, but nothing is submitted
* opening the GovDelivery page in the same browser tab is a security issue

**Suggested solution:** 
* Remove the form field & button from the design. In its place, insert <p> text underneath the H2 on the MyHealtheVet landing page to describe the newsletter and what value it provides the Veteran. Include a secondary action link that opens in a new tab to route the user to the GovDelivery page where they can sign up.

**Comment by danbivins** [comment]
Waiting on CAIA to provide the intro text line. Will update ASAP.

**Comment by LynneJohnson224** [comment]
Per the 3/20 MHV on VA.gov weekly standup, Patrick to touch base with Dennis Rennock to share changes and get feedback.

**Comment by batemapf** [comment]
Sent email to Dennis on 3/21. Apologies for being a blocker to this blocker :-)

**Comment by danbivins** [comment]
Thanks @batemapf . I'll update the content accordingly.

**Comment by danbivins** [comment]
Here are the mockups with updated text. Below is text for copy/pasting:

- **Heading text:** Subscribe to the My HealtheVet newsletter
- **Intro paragraph text:** To stay up to date on My HealtheVet tools and features, subscribe to our biweekly newsletter.
- **Link text:** Subscribe to the My HealtheVet newsletter on GovDelivery.com (opens in new tab)


<img width="877" alt="mockups of desktop and mobile for the newsletter pattern. The edited text is listed above" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/10236001/fe12f948-fb35-42bb-8e6d-b878aaa88001">

**Comment by danbivins** [comment]
@LynneJohnson224 copy is updated in the mockups and handing this off to you for next steps.

**Comment by carlosfelix2** [comment]
Link to documentation on this: https://design.va.gov/content-style-guide/links#va-sub-domain-exceptions-that-open-in-a-new-tab-or-window
