### ISSUE TITLE
SOCKS access for [individual]

### ISSUE THREAD

**Issue by Mandalorian-Oddball** [department-of-veterans-affairs/va.gov-team#77510]
### Your Name

Keenan Schouten

### Your Email

keenan.schouten@oddball.io

### Your GitHub Handle

Mandalorian-Oddball

### Your Role and Team

DevOps Engineer

### Product Manager (PM) name and email

Joe Tice

### Product Owner (PO) name and email

Aparna or Jeff

### Access Type Requesting

platform

### Public SSH Key

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC5VYIrOzeDoB2h/A4dYelkRXz3SIhka5zGA3Ih3WRJLzLPG3ih8WW2H1sQkIAQrVzk78OBqfspEHE+42z5e5j6afvV6KRZtIY/NA33OMRLKo7aah/ZMiEjVEUS9++ftZAiCsAogzMscODh1BVJsDWkNnOp+fADbMUuEXMmhXpkNYsTygv0F4WA1oRnJ50Pgk9lPpCmaOby2xECjL4ayWYvd+phgb1+8FoNnSug8g52h+AJMRpF4rzNZafFODpW5UXQjHSQseEdn+3r986wfZs+8/MTRwcNbzWwOsXiGZgdofWKj2B0P8WkIoqw9UU1taz7phdVj4hTgmXhBb15c0Ej7peX5OqFxVwIwY3DhGNxcQxlKqGYZmlLENIXNUKyoCPMupAxP6wGFyQmG5qKnx0x0/bD06d0HFul9NV7zYNizb0lEx24R+xuXegKT2a9UXyUfrUqj6FNJ3Cm4Qopi604HKP2FvyFQjUvQLEoCN0VcUPE+05jdGbc/nZDUfRqZ+k= keenanschouten@pop-os

### E-QIP Transmittal Confirmation

![transmittal](https://github.com/department-of-veterans-affairs/va.gov-team/assets/144180803/78910d6c-6b15-43e9-9fa8-1059a97f38b1)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [x] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by hgbarreto** [comment]
@Mandalorian-Oddball  Access granted ✅ 

Please allow 10 minutes for your key to be propagated to the various locations before attempting to connect.

See docs for further steps: https://depo-platform-documentation.scrollhelp.site/getting-started/Internal-tools-access-via-SOCKS-proxy.1821081710.html 

Reach out in #vfs-platform-support if you have any trouble.
