### ISSUE TITLE
Redirect Request - Updating Form 21P-527EZ Base URL

### ISSUE THREAD

**Issue by jennymayoco** [department-of-veterans-affairs/va.gov-team#77519]
### Status
- [2024-03-11] Jenny requested that we put this redirect request on hold until we align on when the change to the URL itself will take place,
- [2024-03-01 Fran] Informed Jenny that we'd plan to pull this into Sprint 106

### Instructions
- Requests must be submitted **AT LEAST** 2 weeks in advance.  Some requests take a significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track differnt steps.
- It is your responsibility to notify VA stakeholders as appropriate.  

### Type of request
- [ ] We are retiring or taking down a page and need to redirect the URL (complete redirect section)
- [X] We are changing the URL of an existing page (complete redirect section)
- [ ] We need a custom vanity URL (complete vanity URL section)

### Implementation date
When does this request need to be live?
Choose one:
- [ ] On a specific date, connected to a program or publishing requirement. **DATE:**
- [ ] Any day prior to a deadline/latest possible date. **DEADLINE:** 
- [ ] Any day after an earliest possible date. **EARLIEST DATE:**
- [ ] During a specific date range: ***EARLIEST DATE TO LATEST DATE:***
- [X] No hard timing requirements, publish when possible.

### Redirects 
Current URL  |  Redirect Destination or New URL
---  |  ---
https://www.va.gov/pension/application/527EZ **and all capping variations and subsequent child pages** adding the note about capitalization 3/1 JM | www.va.gov/pension/apply-for-veteran-pension-form-21p-527ez **and all subsequent child pages**

### Vanity URLs 
Vanity URL  |  Landing page
---  |  ---
requested URL | landing page URL

**Link to campaign landing page request issue:**

### Process, Roles and Responsibilities
- [ ] Requesting team: Above information is provided
- [ ] Requesting team: All appropriate VA stakeholders are notified as appropriate
- [x] IA: Request is vetted and documented and implementation plan is clear 
- [x] IA: Request is assigned to appropriate team for implementation 
- [ ] Implementation team: Work is complete
- [ ] Implementation team: Validated in production
- [ ] Requesting team: Validates everything is correct in production and closes ticket

**Comment by jennymayoco** [comment]
Hi @FranECross @jilladams the 21p-527ez form has now been launched to 100% users and so we are moving forward with updating the base URL and all subsequent URLs in the form flow so it is up to date with standards. IA is good to go. For our understanding, what is an estimated timeline for when this URL will be implemented?

@vbellissimo @buddhima-coforma please let your stakeholders know of the new URL and that it will be updated so they are aware and can make any updates on their end once the redirect has been implemented.

cc @strelichl @katherine-fung for visibility

**Comment by FranECross** [comment]
@jennymayoco I believe we can pull this one into Sprint 106, which starts on March 13th. If that changes, I'll be sure to reach out. cc @jilladams @randimays @chriskim2311

**Comment by FranECross** [comment]
@jennymayoco It looks like we may not be able to squeeze this ticket into Sprint 106 as I'd thought because of the design component updates the team is trying to complete. If that changes, I'll be sure to let you know. cc @jilladams

**Comment by jennymayoco** [comment]
@FranECross thank you for the update! 

@buddhima-coforma here's the latest update on timeline!

**Comment by buddhima-coforma** [comment]
Hi! @FranECross @jennymayoco a couple of questions:
- Above it says 'Redirect Destination or New URL', can you clarify which one it will be? So we know if the old URL is going away OR if it remain and this will be an additional new redirect URL?
- How do we coordinate timing? If the old URL is going away, we've found some references in our code base which we need to change and push out too

Thanks!

cc @aplatt-coforma @mjknight50 @mjb-coforma

**Comment by FranECross** [comment]
@jilladams @chriskim2311 Will you please explain to @buddhima-coforma how the redirects work? I'm not as familiar and don't want to muddy the waters by explaining incorrectly. Thanks in advance!

**Comment by chriskim2311** [comment]
@buddhima-coforma The 'Redirect Destination or New URL' can be any URL new or existing. Redirects work with the old URL staying in place and redirecting to the new one when navigating to it. We are not removing the old URL with redirect requests.

**Comment by buddhima-coforma** [comment]
@chriskim2311 Thanks. So in clarifying this ticket, [www.va.gov/pension/apply-for-veteran-pension-form-21p-527ez](http://www.va.gov/pension/apply-for-veteran-pension-form-21p-527ez) will be a new URL that redirects to https://www.va.gov/pension/application/527EZ?

Meaning https://www.va.gov/pension/application/527EZ will remain unchanged?

**Comment by chriskim2311** [comment]
@buddhima-coforma From the initial ask it seems like your comment has them backwards. Or is this the correct ask?

**From ticket:** 
Old URL: https://www.va.gov/pension/application/527EZ
New Redirected URL: http://www.va.gov/pension/apply-for-veteran-pension-form-21p-527ez

You can navigate to the old URL but will land on the new one. It does not seem like the new URL is live yet. Do you know when this will be live? I would recommend having that page up before doing this redirect.

**Comment by buddhima-coforma** [comment]
@chriskim2311 I'm merely trying to understand the ticket
<img width="827" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/143657406/170a1f78-8b43-4366-a2ab-c789aafaee85">
Since there's an 'or' in that 2nd column title

**Comment by chriskim2311** [comment]
For redirects the Current URL stays in our app registry, the visitor will land on whatever URL we set it to. This can be a new URL or an existing one.

**Comment by buddhima-coforma** [comment]
So https://www.va.gov/pension/application/527EZ won't go away, right?
Asking to make sure we don't have to change any references in our code base to that URL.
Thanks!

**Comment by jennymayoco** [comment]
Hi @buddhima-coforma jumping in here, I apologize for completely missing this step and for not having created this ticket first or checking with you if this was in your backlog. Public websites team doesn't update the URL itself, it would require code changes on the your end and I had missed that step. After you all have made the URL change, it will then need to be coordinated with this redirect so that it goes out at the same the URL changes. Happy to set up time this week to go over this.

@FranECross @chriskim2311 can we put this redirect request on hold until we align on when the change to the URL itself will take place?

**Comment by FranECross** [comment]
@jennymayoco Absolutely! I'll mark as blocked and will await further word from you. cc @chriskim2311

**Comment by jennymayoco** [comment]
Hi @FranECross @jilladams - the team will be updating the URL in their code base and tracking work in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/77926). Looping in the team @buddhima-coforma @aplatt-coforma @mjknight50 to coordinate the launch of the new URL with the redirect and align across sprints to minimize any 404s during this change

**Comment by buddhima-coforma** [comment]
@FranECross Can we prioritize the work in the same sprint so that both teams make the change on the same day and push it?
Let us know when you're ready to prioritize it? We are ready to.

**Comment by FranECross** [comment]
@buddhima-coforma We can schedule this for our (our next) Sprint 107, which starts on 3/27 (a Wednesday). I believe we would be able to then deploy on 3/28, the following day (Thursday. 

@chriskim2311 or @randimays , when you have a moment, will you please confirm this is doable? Thanks in advance!

**Comment by randimays** [comment]
@FranECross Yes, we can deploy on 3/28 if we make the changes on 3/27.

**Comment by FranECross** [comment]
@buddhima-coforma Just want to confirm that we should plan to release this on 3/28. Thanks in advance! cc @chriskim2311 @randimays @jilladams

**Comment by buddhima-coforma** [comment]
@FranECross yes, we will aim to get this done on 3/27 so it can in prod by 3/28 
@aplatt-coforma @mjknight50

**Comment by FranECross** [comment]
@buddhima-coforma Will you please confirm that everything is ready and a go for us to implement and release on the 28th as previously planned? Thanks so much! cc @randimays

**Comment by mjknight50** [comment]
@FranECross I will create a PR today which should make it in the 3:00 deployment window today.

**Comment by FranECross** [comment]
@randimays FYSA ☝🏼this is still a go! Thanks @mjknight50 !

**Comment by buddhima-coforma** [comment]
There are two PR's that need to go in before 3:00 to make this happen.
https://github.com/department-of-veterans-affairs/content-build/pull/1992
https://github.com/department-of-veterans-affairs/vets-website/pull/28826
They have to go in that order.

How is it looking on your end? @FranECross

**Comment by buddhima-coforma** [comment]
#1992^ has been merged

**Comment by FranECross** [comment]
@buddhima-coforma I believe we're on track for release tomorrow (after your PRs are released) as previously chatted about. Pinging @randimays to confirm. Thanks everyone.

**Comment by buddhima-coforma** [comment]
Our PRs have merged. On track for 3pm today 3/28

**Comment by randimays** [comment]
@FranECross @buddhima-coforma Pivoting to pick this up; FYI the redirect deploy was early this morning so we've missed that. Do we need an out of band deployment for this redirect to get it in today?

**Comment by buddhima-coforma** [comment]
Sounds like we need a deployment ASAP to prevent the pension form URLs from breaking?

**Comment by randimays** [comment]
Slack thread for discussing OOB deploy: https://dsva.slack.com/archives/C52CL1PKQ/p1711661391012409

**Comment by jilladams** [comment]
Consolidating Slack notes: 
* https://www.va.gov/pension/application/527EZ  is already redirecting to http://www.va.gov/pension/apply-for-veteran-pension-form-21p-527ez in production, before this ticket was implemented. We don't know how.
    * No existing redirect code in redirects.yml prior to code changes in this ticket.
* Public Websites did merge the redirect last night, and Devops deployed morning of Fri 3/29. 
* Following that deploy: still true that the "old" url redirects to the new URL, and resolves to https://www.va.gov/pension/apply-for-veteran-pension-form-21p-527ez/introduction.

I'm closing this ticket as complete. Please create a new ticket for any follow up changes / bug behavior that needs to be investigated.
