### ISSUE TITLE
Qualitative Data Request: MyVA 411 Data - Higher-Level Review (VA Form 20-0996)

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#77511]
### Data Type Requested

Support

### Data Source Type

MyVA.411

### Date Range Start

01-01-2020

### Date Range End

03-03-2024

### Product Name(s)

Decision Review Form: Higher-Level Review (VA Form 20-0996)

### Product Description

If a Veteran disagree with a VA decision, them or their representative can request a new review of their case by a higher-level reviewer. The reviewer will determine whether an error or a difference of opinion changes the decision. Veteran's can’t submit new evidence with a Higher-Level Review.

### Survey URL(s), key term(s), case category or type

higher level review, 0996, 20-0996, higher-level review, HLR

### File Delivery Format

One file, different tab for each term/URL

### Word Cloud

Yes

### VA Email Address(es)

sade.ragsdale@va.gov

### Add Assignee and Labels

If not already done so, please ensure @newworld2616 is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by saderagsdale** [comment]
@jwoodman5 @newworld2616 I don't see this option for decision reviews in the categories page. Can you add any terms that I may not bae able to see in your internal tools?

**Comment by newworld2616** [comment]
Hi, there are no data available for MYVA411 case type or case category for higher level review, 0996, 20-0996, higher-level review, HLR. Let me know if you have any questions. Thank you!

**Comment by saderagsdale** [comment]
@newworld2616 @jwoodman5 It sounds like there are no existing categories for calls about Decision Reviews, which leaves us unable to gather data and potentially reduce contact center calls. How can we start to categorize and collect that data?

**Comment by newworld2616** [comment]
Hi @saderagsdale, there are no existing categories. Our SF team is discussing to bring those categories in the SF. SOrry for the inconvenience.
