### ISSUE TITLE
Qualitative Data Request: MyVA 411 Data - Request a Board Appeal (VA Form 10182)

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#77514]
### Data Type Requested

Support

### Data Source Type

MyVA.411

### Date Range Start

01-01-2020

### Date Range End

03-03-2024

### Product Name(s)

Request a Board Appeal (VA Form 10182)

### Product Description

When Veterans choose this option, they're appealing to a Veterans Law Judge at the Board of Veterans’ Appeals in Washington, D.C. A judge who’s an expert in Veterans law will review their case.

### Survey URL(s), key term(s), case category or type

10182, Notice of Disagreement, NOD, Board Appeal, appeal, appeals

### File Delivery Format

One file, different tab for each term/URL

### Word Cloud

Yes

### VA Email Address(es)

sade.ragsdale@va.gov

### Add Assignee and Labels

If not already done so, please ensure @newworld2616 is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by saderagsdale** [comment]
@jwoodman5 @newworld2616 Also true for this third form...I don't see this option for decision reviews in the categories page. Can you add any terms that I may not be able to see in your internal tools?

**Comment by newworld2616** [comment]
Hi, there are no data available for those selected date for MYVA411 for 10182, Notice of Disagreement, NOD, Board Appeal, appeal, appeals. Thank you!

**Comment by saderagsdale** [comment]
@newworld2616 @jwoodman5 It sounds like there are no existing categories for calls about Decision Reviews, which leaves us unable to gather data and potentially reduce contact center calls. How can we start to categorize and collect that data?

**Comment by newworld2616** [comment]
Hi,

Could you reach out to @Kimberley Monroe-Daniels
***@***.***>. She is our supervisor for
Salesforce, she has more information about Salesforce.

My apologies for not being helpful.

Best Regards,

Sarifa
