### ISSUE TITLE
Production Error 

### ISSUE THREAD

**Issue by mjknight50** [department-of-veterans-affairs/va.gov-team#77529]
`The property '#/' contains additional properties ["jobs"] outside of the schema when none are allowed in schema 51c568dd-1a76-5cc8-9d5c-e642186629a9
`

https://vagov.ddog-gov.com/logs?query=host%3Avets-api-web-6886cc55cd-lsvlq%20service%3Avets-api%20container_id%3A07e87268a0dbaae8adc0402c6008b911453af0c341367b597ba312e635e9a14c%20filename%3A0.log%20&cols=host%2Cservice&context_event=AY4JiPkuAABWh7DUuWXqMgCR&event=&fromUser=true&index=%2A&messageDisplay=inline&refresh_mode=sliding&screenId=vk2-6zi-zzu&screenName=benefits---form-527-pension-benefits&storage=hot&stream_sort=time%2Cdesc&to_event=AgAAAY4JiPPQJcNdtwAAAAAAAAAYAAAAAEFZNEppUGt1QUFCV2g3RFV1V1hxTWdDYgAAACQAAAAAMDE4ZTA5OGEtNDA5ZC00Mzg2LWE5ZjctYTBjYmQ3MjdkNTIx&view=spans&viz=&from_ts=1709556653979&to_ts=1709556954065&live=false

**Comment by mjknight50** [comment]
We haven't figured this out yet.  The payload for this user contains:

`"previous_employers\":[{\"job_date\":\"2015-02-15\",\"job_type\":\"XXXXX \",\"job_hours_week\":40,\"job_title\":\"XXXXXXXX \"}],\"current_employment\":false,\`


There is more job related info in the inProgress form:
`{"jobs":[{"employer":"SomeJob","address":{"street":"123 Street","city":"MyCity","country":"USA","state":"DE","postal_code":"14850"},"job_title":"A title here","date_range":{"from":"2014-03-05","to":"2017-11-13"},"days_missed":"12345","annual_earnings":12345}]}`

Jobs should have been scrubbed with our migration:
https://github.com/department-of-veterans-affairs/vets-website/blob/1d2842718bab90a1c4150ec8a3fb322adaf23530/src/applications/pensions/migrations.js#L104-L141

At this point my best guess or hope is to see if we can add some more logging when the migration runs.

**Comment by aplatt-coforma** [comment]
@TaiWilkin can you please add points to this one? Thanks!
