### ISSUE TITLE
Qualitative Data Request: Medallia Data AND Medallia Intercept Survey Data - VA.gov Search Tools (Main search, Resources, and Find Forms)

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#77523]
### Data Type Requested

User Surveys

### Data Source Type

Medallia

### Date Range Start

01-01-2020

### Date Range End

03-03-2024

### Product Name(s)

Search Bar

### Product Description

This request is for feedback submitted about the search bar. The goal is to review data submitted by users who shared feedback on their experience with the search function. 

### Survey URL(s), key term(s), case category or type

**Search tools:**

- https://www.va.gov/search/?query=
- https://www.va.gov/find-forms/?q=
- https://www.va.gov/resources/search/?query=

**Search terms:** 

- 21-4138
- 20-0995
- 4138
- 21-4142
- 21-0966
- 995
- 10182
- 4142
- 966
- intent to file
- 21-4142a
- va form 20-0995
- 996
- 22-1995
- va form 20-0996
- appeal
- va form 21-4138
- supplemental claim
- va form 10182
- 21-0995
- statement in support of claim
- 21-0996
- pact act
- statement
- 20-10207
- supplemental
- notice of disagreement
- higher level review
- va form 21-0966
- va 21-4138
- 20-995
- appeals
- form 20-0995
- va 20-0995
- 20-0966
- appeal form
- form 20-0996
- form 10182
- supplemental claim form
- intent to file a claim
- decision review request
- pact act form
- request for medical records
- 20-996
- va 20-0996
- 20 0995

### File Delivery Format

One file, different tab for each term/URL

### Word Cloud

Yes

### VA Email Address(es)

sade.ragsdale@va.gov

### Add Assignee and Labels

If not already done so, please ensure @newworld2616 is set as the assignee for this issue and "VSP-contact-center" and "cc-data-request" are set as labels.
Please leave this field as is when submitting.

**Comment by newworld2616** [comment]
Good morning, I have shared the requested data. Thank you!
