### ISSUE TITLE
STEM: Update 22-10203 Form by removing unnecessary 22-1995 artifacts.

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#7753]
As a developer, I need to remove the 1995 steps that are included in the new STEM form so that only the necessary data is collected in the new form.

## Assumptions:
1. ~This work is completed behind the new STEM form feature flag.~ ( this is not needed as form is not available in production due to a form wide setting in the manifest file)

## Acceptance Criteria
1. The following steps are removed from the new form workflow:
   - Step 3 of 6 Military History (Periods of Service)
   - Step 3 of 6 Military History (1978)
   - Step 4 of 6 School Selection (Want to Attend)
   - Step 4 of 6 School Selection (Last Attended)
   - Step 5 of 6 Personal Information
2. The new form number 22-10203 is displayed in place of 22-1995 in the workflow.

## Supporting Artifacts:
1. Images of form for AC 1:
<img width="1440" alt="Step3_1" src="https://user-images.githubusercontent.com/48260534/78803575-2c5f1580-798d-11ea-8cd5-dcc8d51de628.png">
<img width="1440" alt="Step3_2" src="https://user-images.githubusercontent.com/48260534/78803571-2bc67f00-798d-11ea-8a30-db162f0cb98b.png">
<img width="1440" alt="Step4_1" src="https://user-images.githubusercontent.com/48260534/78807015-79dd8180-7991-11ea-965d-c58066f860a1.png">
<img width="1440" alt="Step4" src="https://user-images.githubusercontent.com/48260534/78803569-2b2de880-798d-11ea-8a67-b0bd8a94f280.png">
<img width="1440" alt="Step5" src="https://user-images.githubusercontent.com/48260534/78803561-28cb8e80-798d-11ea-8998-3a7d11ba806d.png">

**Comment by delli-gatti-michael** [comment]
PR:
https://github.com/department-of-veterans-affairs/vets-website/pull/12180

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-04-22 at 7.01.10 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/50b7a3ab-e7de-41d6-a8d9-639c4a0f832c)
##
![Screen Shot 2020-04-22 at 7.01.20 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/e1227e9a-0898-4893-b41e-ff6bd483b7c8)
##
![Screen Shot 2020-04-22 at 7.02.25 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/79ac7f62-ab28-41d7-aae0-75a700c079d2)
##
![Screen Shot 2020-04-22 at 7.02.48 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/73b06a19-4c7a-4a97-bb67-3bbdc75ee1be)
##
![Screen Shot 2020-04-22 at 7.03.29 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/238c5c57-4bfa-41ba-83e3-63dca9680d56)
##
![Screen Shot 2020-04-22 at 7.03.59 AM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/c79fed9f-e11e-4cc2-956d-ddaf1e3bcf35)

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/317&group_by=cases:section_id&group_order=asc&group_id=51

**Comment by sonntag-adam** [comment]
In staging. Closing story.
