### ISSUE TITLE
Build Script to report historic 4142 Errors

### ISSUE THREAD

**Issue by tblackwe** [department-of-veterans-affairs/va.gov-team#77533]
For 4142 Code Yellow 3, we need to share the following with CORBDB team

- Submission CSV
  - `M1A_submissions_20240304a.csv`
  - This is metadata about the submissions
  - CSV Columns: 
    - data_type `M1A`
    - form_type `21-4142`
    - va_gov_submission_created_at `SavedClaim.created_at`
    - va_gov_submission_id `SavedClaim.id`
    - va_gov_user_uuid  We got this from Datadog submissions, and isn't required
    - icn `Account.icn`
    - edipi `Account.edipi`
- Form JSON
  - `M1A_form_data_20240304a.json`
  - follows a simple schema
    - `{schema_def: "https://github.com/department-of-veterans-affairs/vets-json-schema/blob/master/dist/21-4142-schema.json", submissions:[{id:SavedClaim.id, details:SavedClaim.parsed_form["4142"]}]`
    -  We only need the 4142 part of the claim, not the full 526 data
- Zip of PDFs
  - `M1A_pdfs_20240304a.zip`
  - Generated PDFs for each 4142 claim form
  - filename of the PDF `#{SavedClaim.id}.zip`
  

The script should be shared to https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/teams/benefits/scripts/codeyellow3 (where you can also find some examples)

**Comment by freeheeling** [comment]
@tblackwe Script created. Do I commit directly a created file directly to the [codeyellow3 folder](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/teams/benefits/scripts/codeyellow3)?

**Comment by tblackwe** [comment]
Yep! That is correct

**Comment by freeheeling** [comment]
[get_claim_data_4142 script](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/benefits/scripts/codeyellow3/get_claim_data_4142.rb)

**Comment by freeheeling** [comment]
Use `Form526Submission` form data?
```
{"providerFacility"=>
  [{"providerFacilityName"=>"",
    "treatmentDateRange"=>[{"from"=>"", "to"=>""}],
    "providerFacilityAddress"=>{"street"=>"", "city"=>"", "postalCode"=>"", "country"=>"", "state"=>""}}],
 "vaFileNumber"=>"",
 "veteranSocialSecurityNumber"=>"",
 "veteranFullName"=>{"first"=>"", "middle"=>"", "last"=>""},
 "veteranDateOfBirth"=>"",
 "veteranAddress"=>{"city"=>"", "country"=>"", "postalCode"=>nil, "street"=>"", "street2"=>nil, "state"=>nil},
 "email"=>"",
 "veteranPhone"=>nil,
 "veteranServiceNumber"=>""}
```
or `SavedClaim` data?
```
{"providerFacility"=>
  [{"providerFacilityName"=>"",
    "treatmentDateRange"=>[{"from"=>"", "to"=>""}],
    "providerFacilityAddress"=>{"street"=>"", "city"=>"", "postalCode"=>"", "country"=>"", "state"=>""}}]}
```

**Comment by tblackwe** [comment]
1. the veteran details should be added as well. 
2. generated PDF should be stamped with submission date
3. use the schema that the code uses. I guessed on the requirements
4. no, we dont want to send the PDFs to Benefits Intake (yet). that may change in the future but for now we are reporting our discoveries and allowing CORPDB to direct us on next steps

**Comment by tblackwe** [comment]
Evan on Dependents Team added the ability to pass timestamp to the stamper, this code should get you there.

`path_to_pdf = claim.to_pdf
      stamped_path1 = CentralMail::DatestampPdf.new(path_to_pdf).run(text: 'VA.GOV', x: 5, y: 5, timestamp: claim.created_at)`

**Comment by freeheeling** [comment]
4142 Batch (M1A) executed. CSV, JSON, and zipped PDF files stored in CY3 Secure Folder. Shared with Alex M.
