### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by aprocik1** [department-of-veterans-affairs/va.gov-team#77555]
### Name

Anthony Procik

### Email

ap@bloomworks.digital

### Role

Editor

### Team

Sitewide CAIA

**Comment by naomimarcussen** [comment]
Hi! Looks like you already have an account. Let me know if there is anything else you need.

**Comment by aprocik1** [comment]
Hey @naomimarcussen! I can comment on and view Figma files. Do I have edit access too?

(I'm sorry if this is user error on my end - embarrassing!)

**Comment by naomimarcussen** [comment]
No worries! You don't currently have edit access. Is that something you need? I ask because we have limited editor seats.

**Comment by aprocik1** [comment]
Yeah, we're hoping to use Figma as a content source of truth for smaller projects. Between 4 and 7 of the sitewide CAIA content team members will need edit access. Are there enough editor seats for us to gain access?
