### ISSUE TITLE
February Medallia Feedback Report

### ISSUE THREAD

**Issue by charlottecesana** [department-of-veterans-affairs/va.gov-team#77568]
### Issue Description

Monthly reporting on Medallia satisfaction data.
Monthly reports can be found in this folder

### Tasks

What work is necessary for this story to be completed?

- [x]  Request monthly data for FSR
- [x]  Request monthly data for the debt portal
- [x]  Review data reports
- [x]  Extract meaningful data to include in a report
- [x]  Document on Github

 
### Acceptance Criteria

What will be created or happen as a result of this story?

- [x]  Request data reports
- [x]  Review data reports

**Comment by mgleo** [comment]
[Medallia report for February 2024](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/combined_fsr/research/medallia_reports/Medallia-February-2024.md)

Noticed this was still up – this can now be closed!
@charlottecesana @Tom-Davis @HeatherRienks

**Comment by charlottecesana** [comment]
Thanks @mgleo !
