### ISSUE TITLE
[ContentBuild ASG] Implement nightly instance refresh of the Content Build ASG

### ISSUE THREAD

**Issue by hgbarreto** [department-of-veterans-affairs/va.gov-team#77576]
## Description
Due to frequent issues with resources, the Infra Services team would like to implement a nightly instance refresh of the Content build ASG leveraging Lambda and EventBridge.

## Resources 
- Artifacts - i.e., issues, documentation, code, etc. - that help explain what's needed to work on this issue

## Acceptance Criteria
- [ ] Test
- [ ] Build Terraform

## Refinement Guidance - Check the following before working on this issue: 
- [x] _Team label assigned ("platform-tech-team-2")_
- [ ] _Epic assigned (if needed)_ 
- [ ] _Estimated (points assigned)_
- [ ] _Sprint assigned (once planned)_
- [ ] _Team member(s) assigned_
- [ ] _Understands how this work aligns with the overall platform_

**Comment by ph-One** [comment]
This has already been completed. Closing.
