### ISSUE TITLE
10-7959f-1 urls for staging and prod

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#77581]
URLs for staging and prodshould follow CAIA guidance:

Teams can choose their own sub-urls, or get help from CAIA in choosing them or vetting them.
Note some standard sub-urls:
/introduction: use on the first page of the actual form (not the static page in drupal)
/review OR /review-and-submit: use for review steps in forms or tools
/results: use to display the results of a tool (not usually used in a form)
/confirmation: use for the confirmation page after form submission
Subtask URL slugs should be short, plain language, and drawn from the H1 if possible.
Reminder: Don’t create unnecessary or empty subdirectories when creating sub-URLs

**base url**: va.gov/health-care/foreign-medical-program/register-form-10-7959f-1/

**sub urls**:
va.gov/health-care/foreign-medical-program/register-form-10-7959f-1/introduction
va.gov/health-care/foreign-medical-program/register-form-10-7959f-1/veteran-information
va.gov/health-care/foreign-medical-program/register-form-10-7959f-1/identification-information
va.gov/health-care/foreign-medical-program/register-form-10-7959f-1/mailing-address
va.gov/health-care/foreign-medical-program/register-form-10-7959f-1/home-address
va.gov/health-care/foreign-medical-program/register-form-10-7959f-1/contact-information
va.gov/health-care/foreign-medical-program/register-form-10-7959f-1/review
va.gov/health-care/foreign-medical-program/register-form-10-7959f-1/confirmation

[Figma](https://www.figma.com/file/PzB1F5TYuBK5KQgPbuhAwH/10-7959f-1?type=design&node-id=21-159521&mode=design&t=IYQz0AXkdaby1lhy-0) link

**Comment by marywang2** [comment]
@reiting we can hold off on this one until after the demo on Friday.

**Comment by reiting** [comment]
@marywang2 I have 2 PRs in for this (different repos) both waiting for platform review.

**Comment by baltes** [comment]
@marywang2 Closing this to finish the sprint but take a look and reopen if needed.
