### ISSUE TITLE
Update accessibility links in Prod Dev Checklist

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/va.gov-team#776]
1. Move ROE docs into Onboarding folder: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/Administrative/Onboarding

2. Move request issue template to va-gov team repo and update link to it from the ROE docs

3. Update prod dev checklist w/correct 508 links:
https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/Launch%20Process/overview.md

4. Update old/obsolete pages in other repos by adding this text to the top "This document is now obsolete. Current version here: [link to current version]"

**Comment by 1Copenut** [comment]
Add a link to the right issue template in this doc: https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/Launch%20Process/overview.md

**Comment by 1Copenut** [comment]
@rroueche I made this last change and verified links are pointing to `va.gov-team` repo correctly. Moving to close.
