### ISSUE TITLE
PTSD Discovery Research

### ISSUE THREAD

**Issue by nnicholas7** [department-of-veterans-affairs/va.gov-team#77615]
Review existing research on PTSD/MST flow of the 526 to assess the scope and impact of upcoming changes and known pain points, and inform a potential redesign.

Tasks:
- [x] Create a document (Mural board) with all relevant research on the PTSD/MST flow to included Slack messages, Github and Sharepoint links, meeting notes, etc. Include stickie notes with known pain points, recommendations, and open questions.
- [x] Get re-familiarized with the PTSD flow, as well as the stand-alone paper forms (0781, 0781a). Compare 526 versions with newest versions, and note major changes in annotations. 
- [ ]  Summarize scope and outline a project plan for updating the 0781 in the 526 flow.
- [x]  Review P21 from Shadowing Research
- [ ]  Draft research questions for VBA to better understand PTSD/MST policy changes and how they impact the implementation of the digital 0781 within 526

Acceptance Criteria:
- [x] Source of truth document that has the most recent and past research on PTSD/MST flow (Mural or GDoc)
- [x] Comparative flows of the PTSD forms, with updates annotated (Mural)

**Comment by nnicholas7** [comment]
Review existing research on PTSD/MST flow of the 526 to assess the scope and impact of the challenge and inform a potential redesign.

Task:

- [ ] - Create a document (Mural board) with all relevant research on the PTSD/MST flow to included Slack messages, Github and Sharepoint links, meeting notes, etc.
- [ ] - Summarize scope and impact of the problem (do we think this is a major blocker for Veterans and how does this impact application submission)

Acceptance Criteria:
- [ ] Source of truth document created that has the most recent and past research on PTSD/MST flow
- [ ] Create a plan on how to make the go about the research process and next steps.

**Comment by nnicholas7** [comment]
Update 3/12/24:
Update:  We’ve created a Mural that will contain all research related to PTSD/MST.  This board will include form flows, Slack threads, research projects (past and current), and related web pages.  
Next Steps:  Level-set with OCTO to ensure we’ve share knowledge on the status of this work.

**Comment by nnicholas7** [comment]
PTSD/MST Mural Link: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1709649419101/54e2e04175eceb8d71155364960bd2006b6a6997?sender=uffa03f837f92a7ba90498999

**Comment by jinaryu** [comment]
Next steps from Julie:
- [ ] Do a final check across the 2021 versions of the 0781 and 0781a to make sure we didn't miss any updates.
- [ ] Organize the "what's different" section of the form mapping in chronological order, so that the items at the top comes first in the form, and items at the bottom come last in the form
- [ ] Add black stickies for questions that we have for VBA based on these changes. For example, "Additional evidence was replaced by checkboxes" - leaves me wondering, if a Veteran checks one of the boxes like "family member," how would the VA get in touch with them since there's no contact info provided? Do they follow up to ask for this contact info only if further evidence is needed, via a development letter? Then we can use this Mural as our guide for conversation with VBA.

**Comment by nnicholas7** [comment]
Update: 3/16/24
PTSD Discovery Mural Link: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1710425395956/4f0a397015bbcaadd1a421ed60e8d8e185cf1b12?sender=u813bb40bd648bc2b58599242

Creative Brief: https://docs.google.com/document/d/1FVS3bIyR7Po3_TlTsCmuEzHlgRZhjbR2bja6I5CG7cQ/edit

Product Brief: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/product/feature-briefs/Update%20PTSD%200781%20to%20be%20aligned%20with%20new%20form%20version.md

The following documents were created during the discovery research for PTSD/MST Discovery Research.  The Product Brief and Discovery Brief are very similar. 

Next Steps: Meet with VBA and OCTO to ask questions regarding policy and begin working on low-fidelity designs of the PTSD/MST flow.

**Comment by juliepedtke** [comment]
(Copied from [Slack thread](https://dsva.slack.com/archives/C053UDWMH7U/p1711573760208519?thread_ts=1711573597.152269&cid=C053UDWMH7U))

Catching up on all your work - really love the organization of the form comparison, the lettered sections are very helpful! Couple thoughts...

1. Is there a reason you decided not to put the questions for VBA on black stickies throughout, so we could see them alongside the corresponding section of the form? I think this would be helpful to guide the conversation.
2. @jinaryu  it looks like you're still working on reviewing the resources and noting takeaways, which is great! Are you putting these on pink stickies to differentiate from Nichole's work? (Let's note that in a legend somewhere)
4. It's great we have the Mural to get our thoughts down, and it also can lead to stickie-overload. I feel like we need to get together to summarize the most relevant takeaways from past research in a way that's digestible for the rest of the team / stakeholders / future teams. Let's discuss at our sync tomorrow!

**Comment by juliepedtke** [comment]
Update from team sync, next steps:

- [ ] Move VBA questions into form comparison so we see the context of the questions. Once done, I'll review questions to advise on which to prioritize for VBA sync next Tuesday.
- [ ] Finish adding takeaways for priority resources by EOD Friday 3/29
- [ ] Meet as a team 4/1 to review takeaways and create executive summary.

**Comment by nnicholas7** [comment]
The above task items have been completed.  The next step is to work on designs for the PTST/MST flow.  This ticket can be closed for this sprint.
