### ISSUE TITLE
Analytics Implementation or QA Support for IVC Forms - 10-7959f-1 (Foreign Medical Program Registration)

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#77616]
# Google Analytics Implementation Request

### Please provide the following details for this request

- **Team Name**

    - IVC Forms

- **Product Name**

    - 10-7959f-1 (Foreign Medical Program Registration)
      
- **When is the launch date?**
    - end of July (tentative)

- **Provide the link(s) for Product/Page urls**
  
    - va.gov/health-care/foreign-medical-program/register-form-10-7959f-1/introduction
    - va.gov/health-care/foreign-medical-program/register-form-10-7959f-1/veteran-information
    - va.gov/health-care/foreign-medical-program/register-form-10-7959f-1/identification-information
    - va.gov/health-care/foreign-medical-program/register-form-10-7959f-1/mailing-address
    - va.gov/health-care/foreign-medical-program/register-form-10-7959f-1/same-as-mailing-address
    - va.gov/health-care/foreign-medical-program/register-form-10-7959f-1/home-address
    - va.gov/health-care/foreign-medical-program/register-form-10-7959f-1/contact-information
    - va.gov/health-care/foreign-medical-program/register-form-10-7959f-1/review-and-submit
    - va.gov/health-care/foreign-medical-program/register-form-10-7959f-1/confirmation

- **What Events need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked and should be used whenever possible to avoid custom configuration_
    
   - standard form tracking

- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - [Insert test user]

- **Any additional comments**

    - This is our first time at this touchpoint of the collaboration cycle, any guidance is appreciated!

> Please leave the following blank

## Acceptance criteria
- [x] All appropriate issue tagging is completed
- [x] QA has been completed
- [x] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by marywang2** [comment]
Hi @johnny-jesensky-adhoc! I was just wondering what your timeline is for this one, and if you had any questions. Thank you!

**Comment by dhill802** [comment]
Hi @johnny-jesensky-adhoc  - I'm following up on this analytics request to understand the timeline. We are looking to get movement if possible to avoid analytics being a project blocker.  Any follow-up you can provide would be appreciated. Thanks!

**Comment by johnny-jesensky-adhoc** [comment]
Hi @dhill802 -- moving this up to our **_On Deck/In Review_** column. Our team will plan to review in our next refinement meeting, with possibly pulling into our next sprint, which starts next Thursday, August 15th.

FYI @marywang2, @Blivaditis, @ChristineYoungZA

**Comment by dhill802** [comment]
Good morning @johnny-jesensky-adhoc - Can you confirm if this item was pulled into your current Sprint? Ty!

**Comment by johnny-jesensky-adhoc** [comment]
Hi @dhill802, yes -- we are going to try to fit this into the current sprint.

FY @marywang2, @pshahVA, @Blivaditis

**Comment by dhill802** [comment]
@johnny-jesensky-adhoc Thank you!

**Comment by Blivaditis** [comment]
Hi @dhill802 @marywang2 I went ahead and validated that the tracking is appearing on your form (in staging) here is the [link](https://analytics.google.com/analytics/web/#/analysis/p418218150/edit/jrV5A-2fRgmm-pNsUxVMtg) to a GA4 report showing the events.

**Comment by marywang2** [comment]
Oh thank you @Blivaditis, I'm not sure how I missed this notification. I will check it out! Very exciting.

**Comment by marywang2** [comment]
@Blivaditis this looks good to me on staging, assuming I just make sure to check again when going live (you don't need to take any actions for the prod environment)?
