### ISSUE TITLE
Datadog Tagging Compliance With New OCTO Standards

### ISSUE THREAD

**Issue by flooose** [department-of-veterans-affairs/va.gov-team#77612]
While working on #76657, the [new OCTO monitoring standards](https://dsva.slack.com/archives/C04CYC4LMU6/p1709043849156029?thread_ts=1708978391.871299&cid=C04CYC4LMU6) went live, which resulted in broken gh-actions because some of our monitors don't meet these new standards.

Most of the changes involve missing tags and running `tf plan` in the `devops/terraform/environments/datadog` outputs the necessary changes.

This is a screenshot of the [failing action](https://github.com/department-of-veterans-affairs/devops/actions/runs/8144198966/job/22257804555).

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/123168/df30a004-79cb-4a04-af6e-8be0fbd20d35)

**Comment by jennb33** [comment]
We received feedback from DevOps and some significant feedback from Rachal, Rebecca, Lindsey and then from Mike Chelen. Chris is pleased.

**Comment by jennb33** [comment]
@flooose is reviewing the changes that were pushed through last week. Trying to get this merged before the end of the sprint.

**Comment by flooose** [comment]
Tags are all present and individual teams [can now set them](https://github.com/department-of-veterans-affairs/devops/pull/14073#discussion_r1515113305) required.
