### ISSUE TITLE
Cancelation Redesign - Booked Details Page 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#77625]
## Description
We are looking to improve the user experience by updating the cancelation workflow in the Appointments tool. 

Current page: 
<img width="298" alt="Screenshot 2024-03-13 at 10 19 48 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/90797205/e7cd2510-cee8-4a69-9985-888a1db378e9">

<img width="297" alt="Screenshot 2024-03-13 at 10 20 30 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/90797205/7c0f80b4-ae80-4a1a-80ba-e2cb03142aef">

---

## Acceptance Criteria
Background: the `va_online_scheduling_appointment_details_redesign` toggle is on

- [ ] Given the user is in the Appointments homepage
       When the user clicks on Details for an appointment
       Then user clicks on `Cancel appointment` link
       And page design matches the design spec
       No changes to the current URL link for the page

- [ ] Given the user on the  Details page for an appointment 
       When the user clicks on `Cancel appointment` link and clicks on `Yes, cancel appointment` button 
       Then user will receive a cancelation confirmation page 
       And page design matches the design spec

- [ ] Given the user on the  Details page for an appointment 
       When the user clicks on `Cancel appointment` link and clicks on `No, do not  cancel` button
       Then user will revert back to the Details page 
       And page design matches the design spec

- [ ] Given the user is in the Appointments direct schedule workflow 
       When the user booked an appointment then clicks on `Cancel appointment` link
       And page design matches the design spec

- [ ] Given the user is in the Appointments direct schedule workflow 
       When the user clicks on `Cancel appointment` link and clicks on `Yes, cancel appointment` button 
       Then user will receive a cancelation confirmation page 
       And page design matches the design spec

- [ ] Given the user is in the Appointments direct schedule workflow 
       When the user clicks on `Cancel appointment` link and clicks on `No, do not cancel` button 
       Then user will revert back to the Details page
       And page design matches the design spec

- [ ] Move the event tracker `vaos-cancel-appointment-submission` to the `Yes, cancel appointment` button.

### Design Assets
[Cancelation Redesign UI only](https://www.figma.com/file/ColC9ciGHdmp54jXlKuWFM/Redesign-Cancelation-Flow-%7C-Appointments-FE?type=design&node-id=2266%3A80305&mode=design&t=TNDvtaS1RvaQZ7iS-1)
[Appointment Details Redesign](https://www.figma.com/file/9dfdOxI7JtAq5aPBMjejbQ/Appointment-Details-Redesign-%7C-Appointments-FE?type=design&node-id=45-45762&mode=design&t=5bbVT7ogGgpGjt0A-0)
[Appointment Details - Content Matrix](https://www.figma.com/file/9dfdOxI7JtAq5aPBMjejbQ/Appointment-Details-Redesign-%7C-Appointments-FE?type=design&node-id=1130-36148&mode=design&t=5bbVT7ogGgpGjt0A-0)

### Out of scope

1. Alert state when the user confirms the cancelation 
2. Updating the links to CTA buttons on the details page

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by ldelacosta** [comment]
UX team will validate.

**Comment by Cieramaddox** [comment]
@vbahinwillit 

I'm noticing that the H2 is styled as an H3 and should be styled as an H2 (Coded as H2). 


<img width="1826" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNG13QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cb6d6a90c557f855a5e8d809575445b601c090ca/Screenshot%202024-05-02%20at%2011.29.32%E2%80%AFAM.png" alt="Screenshot 2024-05-02 at 11.29.32 AM.png" />

Same goes for the confirmation page.

I'm also getting the "We couldnt cancel your request" error when canceling a booked appointment. 

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBME94QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--51d321e4acbceb3eef2e89043e184dd58727353a/Screenshot%202024-05-02%20at%2012.05.40%E2%80%AFPM.png" alt="Screenshot 2024-05-02 at 12.05.40 PM.png" />

**Comment by vbahinwillit** [comment]
@Cieramaddox - I will change but I got the from a conversation we had.

**Comment by Cieramaddox** [comment]
@vbahinwillit Let me know when youve made these changes

**Comment by Cieramaddox** [comment]
@ldelacosta 
Launch-blocking: Alert message for booked appt cancelation is for request cancelation. 

Spacing and font adjustments can be addressed post-launch.
