### ISSUE TITLE
FE | Profile | Failing unit tests in CI/CD for Update Address specs

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/va.gov-team#77636]
## Issue Description
Look into tests that are currently skipped within our application and platform folder for profile

See PR https://github.com/department-of-veterans-affairs/vets-website/pull/28295

Also this PR where some more profile and platform vap-svc tests are skipped:
https://github.com/department-of-veterans-affairs/vets-website/pull/28403

located in `src/applications/personalization/profile/tests/components/contact-information/PersonalInformation.update-address.unit.spec.jsx`

```
Updating
       Mailing address when the entered address passes address validation
         should show an error and not auto-exit edit mode if the transaction fails quickly:
     Unable to find an element by: [data-testid="edit-error-alert"]
```

```

 Updating
       Home address when the entered address passes address validation
         should show an error and not auto-exit edit mode if the transaction fails quickly:
     Unable to find an element by: [data-testid="edit-error-alert"]
```

We need to fix these tests and investigate into why they started failing but pass locally.

Also look into the tests that were mentioned here: https://dsva.slack.com/archives/C04868KS69L/p1709656491174279?thread_ts=1709598204.845519&cid=C04868KS69L

## Front end tasks
- Fix tests
- Ensure they pass in CI/CD
- Document fix

## Acceptance Criteria
- [ ] All unit tests pass in CI/CD

**Comment by mtcA6** [comment]
going to double check this in sprint 36 and then close out if we've already fixed since we may have already fixed this :tada:

**Comment by adamwhitlock1** [comment]
I updated these tests recently and they are no longer flakey. Closing this ticket out as it is no longer needed. If I see them start to fail in the CI/CD I will revisit.
