### ISSUE TITLE
Sidekiq Admin UI access for Jeff Keene

### ISSUE THREAD

**Issue by JeffKeeneVAGov** [department-of-veterans-affairs/va.gov-team#77631]
### Your Name

Jeff Keene

### Your GitHub handle (Sidekiq Admin UI access is managed through GitHub)

@JeffKeeneVAGov

### Team, Role, and Company of the target individual

Platform Team, Engineering Lead

### COR Name

Eunice Garcia

### Please confirm if you are listed as a team member in Atlas or the Platform Team Roster

- [X] [Team member in Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [X] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Sidekiq UI Access requested for the following environments

- [X] dev
- [X] staging
- [X] sandbox
- [ ] production (if requesting, justify prod access in 'Additional Notes' section)

### If PRODUCTION ACCESS is required, confirm/complete ONE of the following

- [ ] I have an AWS Username and it is listed in [here](https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/iam_users.tf)
- [ ] I currently have access to vets-api Production Terminal via ArgoCD
- [ ] I've attached a screenshot of my E-QIP Transmittal Notice E-mail (Drag or Copy/Paste in Additional Notes Section below)

**Comment by bdech** [comment]
Confirmed in Atlas.

Confirmed with Platform leadership

**Comment by bdech** [comment]
@JeffKeeneVAGov You’ve been granted access to the `dev`, `staging`, and `sandbox` environments.
