### ISSUE TITLE
VFS Custom Events for [Modernized Check-in] & [eCheck-in, Pre-Check-in, OH Travel]

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#77637]
# VFS Custom Event Audit Form

### What this form is for.
In prepration for the migration to GA4, we need information on _all_ custom events used by your products so we can continue to track them.

> [!IMPORTANT]
> Please complete this form with the related spreadsheet included as soon as possible, but no later than **Friday, April 5.** The final deadline where Universal Analytics will stop collecting data is **June 30, 2024**, so we are trying to ensure tracking coverage _well_ before that date.

Please reach out to the **#_vfs-analytics_** Slack channel if there are any questions.

---

### Instructions:
- **Step 1:** Download [this Excel file](https://github.com/department-of-veterans-affairs/va.gov-team/files/14388789/TEMPLATE.-.Custom.GA.Events.-.TEAM.NAME.HERE.xlsx). _(If you are unable to access Excel, please use [this Google Sheet](https://docs.google.com/spreadsheets/d/1G6edvaxWTRTIybbtP6uC7CE-wDkWpIH4bNqQywFhSRs/edit?usp=sharing))._
- **Step 2:** Follow the instructions on the spreadsheet, filling out all required information on the two tabs:
    - Instructions & Team Info
    - Custom Events
- **Step 3:** Once completed, attach the Excel file to this ticket.
- https://docs.google.com/spreadsheets/d/1r9UnGiTvnRHygQhd3LGBTKbdPPv6UrB6qpAmBbC4UOo/edit?usp=sharing
- **Step 4:** Include your team and product names within the **Title** of this form.
- **Step 5:** Submit this form.

_Our team will follow up with you for next steps._

 > [!NOTE]
> If your team manages more than one product, you can submit this form multiple times, or alternatively, include multiple copies of the spreadsheet to the same Github form. Whichever option is easiest.

**Comment by johnny-jesensky-adhoc** [comment]
Hi @loripusey - thank you for submitting this form! Can you attach a copy of the completed Excel spreadsheet, or provide a link to the completed Google Sheet.

Let us know if you have any questions.

FYI @jestutt

**Comment by loripusey** [comment]
Yep, we are working on it

**Comment by brianseek** [comment]
Hello @johnny-jesensky-adhoc here is a start of our custom event tracking. I narrowed the focus down to just the pre-check-in application, but there are a few in here that are universally used. Let me know if this is what your team is looking for and I will add the rest for day-of check-in, our new travel-claim application, and upcoming unified appointments refactor
[Custom GA Events - PCI (pre check-in only).xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/14579286/Custom.GA.Events.-.PCI.pre.check-in.only.xlsx)
.

**Comment by johnny-jesensky-adhoc** [comment]
Excellent - thank you providing all of this so quickly @brianseek! I'll have @jestutt take a look, and let her chime in if she has any questions. If not, we'll give y'all the the green light to add the rest.

We'll follow-up shortly.

FYI @loripusey

**Comment by brianseek** [comment]
@jestutt Any updates on next steps for us. Last we spoke you had mentioned a potentially simpler plan.

**Comment by jestutt** [comment]
@brianseek  Thank you for checking in! Yes, since you're team puts everything into the event name, we're going to simplify things and just ask for the dataLayer event names or the the pattern you all are using to generate the event names. 

What I mean by pattern is that while the start of the check-in events seem to start in a way that references the type of check-in, the rest of of the information is specific to the interaction/scenario but there's no parameter names to give me an idea of how that information should be mapped into separate fields. If you have a guide or key that could help me with that, it's be great. If there's nothing like that at the moment, it's something we can circle back to later when there's maybe a lull. 

If the spreadsheet no longer works for this information, I'll leave it up to you how you want to attach it to the ticket.

**Comment by brianseek** [comment]
Thanks @jestutt that sounds good, I'll get that put together soon

**Comment by wullaski** [comment]
@jestutt I shared the completed [spreadsheet](https://docs.google.com/spreadsheets/d/1r9UnGiTvnRHygQhd3LGBTKbdPPv6UrB6qpAmBbC4UOo/edit?usp=sharing) with you on google drive. Let me know if you have any questions.
