### ISSUE TITLE
[DevOps] SPIKE: Discovery work for moving to new AWS instance

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#77640]
## Tasks
- Get answers to questions; examples
   - To what instance are we moving?
   - How do we move?
   - What moves?
- Create follow-up tickets for the work

**Comment by ndouglas** [comment]
Some questions that occurred to me:

1. Is this a CIE-only move or a total relocation?
2. Is this atomic or gradual?
3. What is the service overlap period?
4. What's the timeline?
5. What are my team's and my responsibilities?
6. What is expected to change?
7. What might I be able to change?
8. How will communication between teams be managed?
9. How are changes being coordinated?

**Comment by loripusey** [comment]
@ndouglas if we need another spike/discovery ticket, please create a new one, closing this one for the sprint
