### ISSUE TITLE
Share design norms with the wider team

### ISSUE THREAD

**Issue by kristen101606** [department-of-veterans-affairs/va.gov-team#77652]
### Description
We have a set of [Research/Design team norms](https://docs.google.com/document/d/1vrtstsGSlTdrEldgvsOVggdeS7uzhLFXtcB1eXFDq5M/edit) that we should share with the wider team, as [Engineering has done](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vso/teams/representatives/process/engineering-agreements.md) with their team norms. 

### Output
- Align as a team on any unanswered norm/agreement questions
- Create/update Design team norms/agreements in Github

### Leads or Collaborators
- Lead: @RenataKeck 
- Co-lead: @uxrebecca  

### Resources
- [Design team norms in Google doc](https://docs.google.com/document/d/1vrtstsGSlTdrEldgvsOVggdeS7uzhLFXtcB1eXFDq5M/edit)
- [Barebones Design team agreement in Github](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vso/teams/representatives/process/design-agreements.md)
- [Engineering team agreement in Github](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vso/teams/representatives/process/engineering-agreements.md)

### Acceptance Criteria
- [x] Unanswered questions answered
- [ ] A markdown file is created for Design norms in our Github repo

**Comment by RenataKeck** [comment]
[Draft team agreement](https://docs.google.com/document/d/1SBZzZxYbqcpVWrgaX_X1kjwcFxpx3fBCxYEyaEIqEGk/edit)
