### ISSUE TITLE
Update CHAMPVA page

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#77656]
As part of the community care migration work, we need to update the CHAMPVA benefit detail page. 

Things to address in this update:

- This page is older and doesn't follow current site style, so we'll adjust style choices
- This page will move into the family member hub
- Form 1010D is getting digitized now, so we'll plan to link to the online version of that form (placeholder link for now)
- This page will link to several new R&S pages we're creating for this migration — we shouldn't keep any links to legacy pages or pdfs in the updated draft
- We may want to link to the caregiver program page and explain that caregivers shouldn't apply separately for CHAMPVA, they'll be automatically enrolled in CHAMPVA if they qualify, after they've been accepted into the caregiver program

Here's the page draft on Sharepoint:
https://dvagov-my.sharepoint.com/:w:/g/personal/danielle_thierry_va_gov/EaHwnT7u8BBEr2OOoJQ_9U4Bg-_jPsm5W3BZp4BSDbQ3wg?e=B7bsNE

**Comment by laurwill** [comment]
Hi @d-beyer ,
As we just chatted, you can finish copying the live page content into the sharepoint doc and start tracking suggested changes for site style. Let me know when you have any questions. Thank you!

**Comment by d-beyer** [comment]
@laurwill -- I pasted in all the existing CHAMPVA content and took a pass at revising it. I left a few comments and questions for you in the doc. Let me know if you'd like to talk through any of it!

**Comment by d-beyer** [comment]
@laurwill I drafted [the update to the Drupal page](https://preview-prod.vfs.va.gov/preview?nodeId=9) to match the document. 

This gave me an opportunity to do some stuff in Drupal for the first time (like jump links) so let me know if there's anything I should be doing differently!

**Comment by laurwill** [comment]
Closing this ticket — we'll send to SMEs with the rest of the batch. Tracking work in this copyedit ticket now: https://github.com/department-of-veterans-affairs/va.gov-team/issues/81742
