### ISSUE TITLE
SPIKE: MHV Login & authentication flows

### ISSUE THREAD

**Issue by marriej** [department-of-veterans-affairs/va.gov-team#7765]
This ticket is to capture work related to the research and documentation of MHV's login and authentication methods.

- [ ] Verify the VA.gov to MHV navigation behavior for basic users.

- [ ] Document the continuity of the assurance level for MHV credentials.

- [ ] Assessing feasibility of getting rid of MHV upgrading API.

**Comment by patrickvinograd** [comment]
Documented trait flow and API interactions in these docs:

https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/sso/VA_MHV_Integration_Updates_20200413.docx

https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/identity-personalization/sso/va_mhv_trait_analysis.xlsx

Ongoing discussion happening with MHV team in VA email.
