### ISSUE TITLE
Cancelation Redesign - Request Details Page 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#77683]
## Description
We are looking to improve the user experience by updating the cancelation workflow in the Appointments tool. 

Current view: 

**Request details page** 
<img width="290" alt="Screenshot 2024-03-05 at 8 26 16 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/90797205/8c56d972-4496-4849-b47a-5d20c1f2c0ab">

**Pop up message to confirm to cancel**
<img width="298" alt="Screenshot 2024-03-05 at 8 26 45 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/90797205/cd62b02a-f1f1-4dc3-8dd2-7ba06f36af95">

---

## Acceptance Criteria
Background: the `va_online_scheduling_appointment_details_redesign` toggle is on

- [ ] Given the user is on the Pending list  
       When the user clicks on `Details` for a request and `Cancel request` link
       Then the user will see two buttons below the page to confirm the cancelation
       And page design matches the design spec
       No changes to the current URL link for the page

- [ ] Given the user on the Pending details page for a request 
       When the user clicks on `Cancel request` link and `Yes, cancel request` button 
       Then user will receive a cancelation confirmation page 
       And page design matches the design spec

- [ ] Given the user on the Pending details page for a request 
       When the user clicks on `Cancel request` link and `No, do not cancel` button
       Then user will revert back to the details page 
       And page design matches the design spec

- [ ] Given the user is in the appointment request workflow 
       When the user submits a request then clicks on `Cancel request` link on the details page
        Then the user will see two buttons below the page to confirm the cancelation   
       And page design matches the design spec

- [ ] Given the user is in the appointment request workflow 
       When the user submits a request then clicks on `Cancel request` link and `Yes, cancel request` button 
       Then user will receive a cancelation confirmation page 
       And page design matches the design spec

- [ ] Given the user is in the appointment request workflow 
       When the user submits a request then clicks on `Cancel request` link and `No, do not cancel` button 
       Then user will revert back to the details page
       And page design matches the design spec

- [ ] Move the event tracker `vaos-cancel-appointment-submission` to the `Yes, cancel request` button.

### Out of scope

1. Alert state when the user confirms the cancelation 
2. Updating the links to CTA buttons on the details page

### Design Assets
[Cancelation Redesign UI only](https://www.figma.com/file/ColC9ciGHdmp54jXlKuWFM/Redesign-Cancelation-Flow-%7C-Appointments-FE?type=design&node-id=2266%3A80311&mode=design&t=TNDvtaS1RvaQZ7iS-1)
[Appointment Details Redesign](https://www.figma.com/file/9dfdOxI7JtAq5aPBMjejbQ/Appointment-Details-Redesign-%7C-Appointments-FE?type=design&node-id=45-45762&mode=design&t=5bbVT7ogGgpGjt0A-0)
[Appointment Details - Content Matrix](https://www.figma.com/file/9dfdOxI7JtAq5aPBMjejbQ/Appointment-Details-Redesign-%7C-Appointments-FE?type=design&node-id=1130-36148&mode=design&t=5bbVT7ogGgpGjt0A-0)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by ldelacosta** [comment]
UX team will validate.

**Comment by Cieramaddox** [comment]
@vbahinwillit There is no padding on either pages. 

<img width="152" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMG14QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3593007ebd5b78346a8ddb317ae7b0e831c45c2c/Screenshot%202024-05-02%20at%202.44.52%E2%80%AFPM.png" alt="Screenshot 2024-05-02 at 2.44.52 PM.png" /> <img width="288" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHF4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--32badb1ef9f94eca30fb96fb784a8ac5bc441328/Screenshot%202024-05-02%20at%202.45.18%E2%80%AFPM.png" alt="Screenshot 2024-05-02 at 2.45.18 PM.png" />

**Comment by melissa-lefevre** [comment]
The padding is fixed and looks good.

**Comment by melissa-lefevre** [comment]
I ran through the A11y Checklist and it looks good.

**Comment by melissa-lefevre** [comment]
@ldelacosta this ticket is good to go.

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket.
