### ISSUE TITLE
[FE] Complete a GA4 Event Audit Spreadsheet of Recorded Events

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#77709]
## Tasks
- [FE] Complete a GA4 Event Audit Spreadsheet for 1/4 of Recorded Events
    - Refer to our [Analytics ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/77637) for the spreadsheet template
    - Attach the spreadsheet to the [Analytics ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/77637) and ping Johnny Jesensky in the ticket comments

**Comment by brianseek** [comment]
completed the pre-check-in portion and attached to ticket

**Comment by brianseek** [comment]
@loripusey seems like this is fine to close with the next ticket in the upcoming sprint
