### ISSUE TITLE
TAP: Create ID.me content for TAP worksheet

### ISSUE THREAD

**Issue by lmorris3** [department-of-veterans-affairs/va.gov-team#77702]
Several months ago we created content for TAP to help Veterans transitioning out of service choose a sign in credential with Login.gov.

Now we are being asked to add ID.me content to their curriculum to transition to modern, secure sign in credentials.

AC:
- [x] Draft a worksheet that features same content as seen for Login.gov in the TAP curriculum on page 14
- [x] Update content to include ID.me specific language
- [x] Include all sign in steps, use Mural linked in comments for guidance

**Comment by SophiaPhilipMO** [comment]
[Draft](https://docs.google.com/document/d/107xmrHVnvqxDDUfOLER95Qo75r-f3Plel4oyLEkcKrg/edit#heading=h.kys7wqw4q0y)

**Comment by SophiaPhilipMO** [comment]
[Uploading... TAPUpdates_SP edits.pdf]

**Comment by SophiaPhilipMO** [comment]
[TAPUpdates_SP edits.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWU3QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--15269be45d350793ac0255e8151520dd1868f44c/TAPUpdates_SP%20edits.pdf)

**Comment by SophiaPhilipMO** [comment]
Use [Mural](https://app.mural.co/t/innovationboards1199/m/innovationboards1199/1695307385302/04cd3eee7cc9a0068903f16eea16fb582e5ce088?sender=u8b2bd1f5eec8aeeb5ca99521) to capture steps to create ID.me account

**Comment by skirkman16** [comment]
@CarlDickerson captured progress on ID.me activity sheet [here](https://docs.google.com/document/d/107xmrHVnvqxDDUfOLER95Qo75r-f3Plel4oyLEkcKrg/edit#heading=h.kys7wqw4q0y). I will make final updates that will be ready for review for tomorrow.

**Comment by skirkman16** [comment]
@SophiaPhilipMO ready for review

**Comment by skirkman16** [comment]
PDF and activity sheet have been reviewed and they are ready for submission

**Comment by skirkman16** [comment]
Final PDF here[TAPUpdates_03082024.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTdDQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--75474678c6b81a8a0d53dc6374fdf802876ba4be/TAPUpdates_03082024.pdf)
