### ISSUE TITLE
Flipper UI access for Richard Davis

### ISSUE THREAD

**Issue by radavis** [department-of-veterans-affairs/va.gov-team#77735]
### Your Name

Richard Davis

### Your GitHub handle (Flipper UI access is managed through GitHub)

@radavis

### Team, Role, and Company of the target individual

#mhv-on-vagov-cartography-team, Software Engineer, Agile Six

### Please confirm if you are on Atlas, Platform Team Roster or are a Federal User

- [X] [Atlas](https://dev.va.gov/atlas)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [ ] Lesser Environments (Dev/Staging/Sandbox)
- [X] Production (if requesting, justify prod access below)

### Reason for Production Access (If requested)

I need this access in order to see which feature flags are enabled in production, to change feature flags in production, when asked.

**Comment by bdech** [comment]
@radavis You've been granted access to production.
