### ISSUE TITLE
10-7959f-1 Add authenticated experience support to form

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#77738]
As a user who is signed in and viewing the 10-7959f-1 form online, I want to see my information pulled from my VA.gov profile so that I don't have to fill out all the fields in the form.

- Add Save In Progress support
- Create vets-website pull request for Save in Progress work for internal approval
- Merge pull request

**Optional**

- Identify all fields that can be pre-filled in the form by crossreferencing the available data in the back end
- Add Prefill support for all pre-fillable fields to the front end by creating a prefill-transformer
- Add all required Prefill data to be sent to the front end in the back end
- Create vets-website pull request for internal approval
- Create vets-api pull request for internal and platform approval
- Merge pull requests

## Acceptance Criteria
  - Given the user is signed in and viewing the 10-7959f-1 form online
  - When the user navigates to the form
  - Then the user's information should be pulled from their VA.gov profile and pre-filled in the form
  - And the user should be able to save their progress and return to the form later

**Comment by reiting** [comment]
The frontend of this has been completed and merged. However, prefill isn't working, and it may be a problem with a .yml file on the backend. Have asked @cloudmagic80 to take a look when he has time. @balexandr tagging you to keep you in the loop
