### ISSUE TITLE
CT-103: Create feature flag for new content.

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#7773]
As a developer, I need to create a feature flag that can be used for the Section 103 UI update effort, so that the development is only available in lower environments until it is ready to be delivered to production.

## Assumptions:
1. N/A

## Acceptance Criteria
1. The feature flag 'eduSection103' is displayed on the url located here: https://[environment]-api.va.gov/flipper/features.

## Assumptions:
1. The Feature Flag is configured per environment.
2. When the feature flag is:
     a. Off: The "Institution Summary" of the "Additional Information" section on the Comparison Tool profile page has no reference to the section 103 enhancements.
     b. On: The "Institution Summary" of the "Additional Information" section on the Comparison Tool profile page displays the section 103 enhancements.
3. The feature flag 'eduSection103' is displayed here: https://[environment]-api.va.gov/flipper/features.

## Acceptance Criteria
1. A Feature Flag is available to be used for the Estimate Your Benefits development.
2. The Feature Flag name is: 'eduSection103'
3. The Feature Flag description is: 'Enables section 103 content'
4. The Feature Flag is defaulted to the OFF state.

## Supporting Artifacts:
1. N/A

**Comment by ksantiagomorgan6** [comment]
Backend PR: https://github.com/department-of-veterans-affairs/vets-api/pull/4118

Frontend PR: https://github.com/department-of-veterans-affairs/vets-website/pull/12168

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-04-10 at 12.44.44 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/c98190c9-0ea7-48d5-8c62-8a17da0d022e)
##
![Screen Shot 2020-04-10 at 12.44.52 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/5b2218a4-6719-4b24-b2bb-c176f15e1ac7)

**Comment by sonntag-adam** [comment]
In staging. Closing story.
