### ISSUE TITLE
Identity SDK - Research Web Components for Identity SDK Library

### ISSUE THREAD

**Issue by acald-creator** [department-of-veterans-affairs/va.gov-team#77746]
# Description

In the `vets-website`, there are several components, deprecating and new, that we have to account for when migrating the components to the Identity SDK Library.

However, one component in particular `VaModal` does not work in certain areas of the VA websites, which caused the issue of migrating from the deprecated component to the new web component from USWDS v3 not to work.

This ticket here is to track the progress of creating a custom component to be used within the Identity SDK Library first or attempt to use the one from the component-library instead, whichever comes first.

**Comment by acald-creator** [comment]
Provide some information for this issue

**Comment by acald-creator** [comment]
Move to backlog, will cover this in the near future if it is still necessary to create a web component alternative then what the VA component library has

**Comment by acald-creator** [comment]
Review if this is necessary or not

**Comment by parkerbees** [comment]
Moved to Jira. Closing.
