### ISSUE TITLE
10-7959f-2 - Identify and schedule stakeholders for interviews

### ISSUE THREAD

**Issue by rachaelpenfil** [department-of-veterans-affairs/va.gov-team#77753]
Acceptance criteria:

- Identify stakeholders we'll want to talk to for F-2 (have names in F-1 stakeholder interviews, VA email)

**Comment by rachaelpenfil** [comment]
Stakeholders we'll want to talk to:

Leticia Diaz (supervisor over FMP claims processing)
Richard McKeithan (supervisor over FMP claims processing)
Dirk Raznick (claims processing, escalations - call center)

@brian-wilke or @StevenStraily , am I missing anyone? I feel like those were the names that have come up most often. We can also check in our FMP stakeholder touchbase on Wednesday, too.

@marywang2 , I feel like we should ask the FMP folks we're meeting with on Wednesday to give them a heads up so it's not a random person just reaching out. Can we have Premal add that to the agenda?

**Comment by marywang2** [comment]
I added it to our running agenda doc on sharepoint.
