### ISSUE TITLE
AWS access for Aurora Hampton

### ISSUE THREAD

**Issue by aurora-a-k-a-lightning** [department-of-veterans-affairs/va.gov-team#77765]
### COR Name

Jennifer O'Day

### Vendor Onboarding Representative Name

Agile Six - Anthony M. Arashiro

### Your Name

Aurora Hampton

### Your Email

aurora.hampton@agile6.com

### Team, Role, and Company of the target individual

Disability Benefits Experience, Software Engineer, Agile Six Applications, Inc

### Product Manager (PM) name and email

Rakshinda Aslam - rakshinda.aslam@agile6.com

### Product Owner (PO) name and email

Emily Theis - emily.theis@va.gov

### Desired AWS Access

Access and ability to write pertinent scripts supporting most recent Code Yellow initiative with VA.gov

Desired AWS Access can be copied from [thomas.blackwell@coforma.io](mailto:thomas.blackwell@coforma.io) / Thomas Blackwell

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/19178435/f88d5826-264f-48fb-974b-f992369a48cb)

### Additional Notes

I chose "ongoing" for the Access Expiration because i do not know if or when I will be off the team since I'm here for the long-haul 😅

### User must exist in a roster before AWS access can be granted. See [AWS access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1792114735/Onboard+New+Team+Members+Granting+Access+to+Internal+Tools#AWS-Access-Request) for the steps involved.

- [x] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by Mandalorian-Oddball** [comment]
User in Atlas.
