### ISSUE TITLE
[SCREENREADER]: SSOe Comms Modal: MacOS VoiceOver Issue

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#7777]
## What happened?
When testing the [SSOe comms modal](https://adhoc.invisionapp.com/share/DYVMI5OXEQN#/407512637_-5828-Comms_Modal) with MacOS VoiceOver, everything in the modal was read except for the bullets. The screen reader skips from **With single sign on, you can:** to **Continue to VA.gov**.

![SSOe_Modal_Error.png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/7a91476c-7d9d-43a2-906e-f991ccc55de9)
 
## Specs:
- Device: Macbook
- Browser: Google Chrome
- Browser: Also tested on Safari with "Preferences > Advanced > Press tab to highlight each item on webpage" checked and unchecked. Was able to reproduce in both instances. 
- Test User: Bridget 

## Steps to Reproduce
- URL: staging.va.gov 
1. Open Safari (**do not use Chrome with Mac VoiceOver**) 
2. Sign in with any staging credentials you have access to for the first time 
3. Once signed in on VA.gov the SSOe comms modal should appear (if it doesn't appear, clear history and try again) 
4. Open Screen Reader in System Preferences > Accessibility > Voice Over

**Comment by 1Copenut** [comment]
@bridgethapner I was able to read the list and it announced itself correctly in VoiceOver. It's possible the HTML has been updated, or if you were navigating with the TAB key, it might have been passed over. I navigated through the modal window with the `Opt + Ctrl + RIGHT_ARROW` key chord, and things sounded good. I believe we can close this issue.

/cc @marriej

**Comment by hinzed1127** [comment]
I was able to verify the same thing as @1Copenut , so closing this one for now.
