### ISSUE TITLE
Integration test with PEGA

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#77782]
Need working session w/PEGA team (as they're not finding files - may not be looking at the right bucket).

[Notes](https://dvagov.sharepoint.com/:w:/r/sites/vaivc/_layouts/15/Doc.aspx?sourcedoc=%7B0110BFC8-C890-4CF8-B9B4-C6F93830F1B5%7D&file=PEGA%20weekly%20sync.docx&action=default&mobileredirect=true) from today's call with PEGA team

**Comment by cloudmagic80** [comment]
Screenshot from Denise PEGA team<img width="1237" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUhCQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fde87a33b4d99219677a030606ffcee1f66d7ab7/Screenshot%202024-03-07%20at%2010.42.31%20AM.png" alt="Screenshot 2024-03-07 at 10.42.31 AM.png" />
