### ISSUE TITLE
Spike: Datadog dashboard for monitoring

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#77783]
We need a dashboard or something similar to monitor PEGA and scan statuses

Acceptance Criteria
- Gather info on DD for S3 upload monitoring to PEGA and scan statuses

Resources:
- [VA Platform Docs: DataDog](https://depo-platform-documentation.scrollhelp.site/developer-docs/monitor-applications-and-infrastructure-with-datad)
- [DataDogHQ: ddtrace Gem Tracing](https://docs.datadoghq.com/tracing/trace_collection/automatic_instrumentation/dd_libraries/ruby/)

**Comment by balexandr** [comment]
After chatting with Platform a bit it seems like weneed different access outside of vanotify. Eric Tillberg mentioned this URL https://vagov.ddog-gov.com/apm/traces?query=env%3Aeks-prod%20service%3Aveteran-facing-forms%20%40form_id%3A21-4142%20&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_code&fromUser=true&graphType=flamegraph&historicalData=true&messageDisplay=inline&query_translation_version=v0&shouldShowLegend=true&sort=time&spanType=all&traceQuery=&view=spans&start=1709230595726&end=1709835395726&paused=false but I can't access it currently

I put in another ECC request for access to vagov-va-datadog and vagov.ddog-gov

**Comment by cloudmagic80** [comment]
Dashboard is ready to view. I've made 2 different monitoring dashboards. There is still work to do be done on the metrics side.
https://vagov.ddog-gov.com/dashboard/gp7-3es-kyj/1010d-sample-1?fromUser=false&refresh_mode=sliding&view=spans&from_ts=1711370696667&to_ts=1711374296667&live=true

https://vagov.ddog-gov.com/dashboard/4jn-uwp-bm3/1010d-ivc?fromUser=false&refresh_mode=sliding&view=spans&from_ts=1711374018952&to_ts=1711374318952&live=true

**Comment by baltes** [comment]
This work was completed in sprint 13.
