### ISSUE TITLE
[Usability Testing] Global Form Validation Changes

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#7778]
## User Story or Problem Statement
During our work, we identified some improvement to how form validation occurs.  During the PR, it was suggested that we have a usability testing study created to ensure that this global change serves the veterans.  Since this is not a critical fix, we will proceed to create this study.

This is just an update to forms and not a full 526 update and therefore this will not be as rigorous from a prep and planning perspective.  Here are the suggested items going into this study.

- Include with we have (before/after, reasoning)
- Include a section in the description about the scope of this testing — this review isn't about all of 526, this is specifically about the form errors
- Once we have that defined and clarified in the ticket, we can ask reviewers to sign off on whether their feedback and those artifacts are needed (for example check with QA before saying we do not need QA here)

## Goal
Give the veteran an easier time understanding the form validation errors while still staying accessible (accessibility review has already occurred)

## Acceptance Criteria
- [ ] Usability study created and scheduled
- [ ] Conversation guide
- [ ] Sign off by VSP

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevinstachura** [comment]
Further discussion has ensued on how we might approach this issue (whether we want to focus on just the error issues or more global review page items). Will backlog this for now in favor of claim status items for this upcoming sprint.

**Comment by vhenry07** [comment]
Closing complete
