### ISSUE TITLE
Maintenance + Reporting 2024 (April, May, June)

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#77786]
## Issue Description
A quarterly epic to track ongoing/prioritized maintenance fixes and updates that fall into the following categories:
- Bug fixes, 
- A11y fixes/enhancements 
- other required code fixes that have been prioritized but don't fall under existing super epics
- Medallia feedback survey synthesis on a monthly basis; resulting in 3 reports added to (add location)
- Supporting GA4 Migration: Conduct Audit
- Deprecation of V1 Design components.
---
## Tasks
- [ ] Resolve all associated tickets associated with the super epic as related to list above.

## Acceptance Criteria
- [ ] At the end of quarter (~ June 26, 2024) this epic should be closed. Any tickets that remain open should be examined and if deemed important then they should be moved into the newly established Q4 Maintenance Epic.
---

**Comment by Tom-Davis** [comment]
All Epics and Tickets under this quarters SEpic are closed - closing this Quarters SEpic and all new items are under the next Quarters SEpic.
