### ISSUE TITLE
[Design] BDD: Detailed Design Based on Research Findings from Initial Usability Study

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#7779]
## User Story or Problem Statement
Create the full detailed build out suitable for developers to get all the details they need for a front-end buildout of the BDD MVP.

## Objectives or Key Results this is meant to further
- Service members can apply for BDD benefits,

## Acceptance Criteria
- [x] Full design build out of BDD MVP
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevinstachura** [comment]
Changes and cleanup has been completed and can be viewed here: https://vsateams.invisionapp.com/share/BUWOTNKFPK7
