### ISSUE TITLE
Adding Eric Cao to DSVA Slack

### ISSUE THREAD

**Issue by huggins-va** [department-of-veterans-affairs/va.gov-team#77790]
Please add Eric Cao as a multi-channel user 
To: 
vaapi-delivery-infrastructure 
team-leeroyjenkles

work email: cao_eric@bah.com
VA email: eric.cao@va.gov

Eric Cao is a new RMF Engineer on Lighthouse / Leeroy Jenkles team 

Thank you!

**Comment by LEHigley** [comment]
couldn't add to either channel, invited to slack and general channel
