### ISSUE TITLE
Run aXe checker in Form App Tester

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#778]
## Problem
The Nightwatch e2e tests run the aXe checker on every page, but the form app tester does not. To get 1:1 feature parity, we need to run the checker on every form page.

## Goal
Each form page has its accessibility checked without manual intervention by the developer.

## Acceptance Criteria
- [ ] [axe-puppeteer](https://github.com/dequelabs/axe-puppeteer) is used to verify each form page is accessible

## Possible solutions
Probably the best way to do this is to run the checker in the `fillForm` loop before the hook / normal page branch.

**Comment by meganhkelley** [comment]
Not sure if this is still relevant; passing to your teams @caw310 @JoeTice

**Comment by pjhill** [comment]
OBE
