### ISSUE TITLE
EYB: Create Feature Flag Toggle for Estimate Your Benefits Effort

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#7780]
As a developer, I need to create a toggle for the Estimate Your Benefits Effort, so that it can be enabled / disabled without requiring a deployment.

## Assumptions:
1. The Feature Flag is configured per environment.
2. When the feature flag is:
     a. Off: The "Estimate Your Benefits" section benefits estimator panel is updated as the user changes the input values.
     b. On: All of the work completed as part of epic #6231 is available in the given environment.
3. The feature flag `gibctEstimateYourBenefits` is displayed here: https://[environment]-api.va.gov/flipper/features.

## Acceptance Criteria
1. A Feature Flag is available to be used for the Estimate Your Benefits development.
2. The Feature Flag name is: gibctEstimateYourBenefits
3. The Feature Flag description is: "508 and usability enhancements for the Comparison Tool Profile Page Estimate Your Benefits section benefits estimator panel."
4. The Feature Flag is defaulted to the OFF state.

## Supporting Artifacts:
1. N/A

## PRs:
- https://github.com/department-of-veterans-affairs/vets-api/pull/4126
- https://github.com/department-of-veterans-affairs/vets-website/pull/12203

**Comment by delli-gatti-michael** [comment]
### Local Testing complete

![Screen Shot 2020-04-14 at 10.19.45 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/adfc9b9c-b5d5-4d1f-9aa0-c3550c9d22c1)

---

![Screen Shot 2020-04-14 at 10.19.55 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/1eab6ce8-6e03-4246-9908-b38c98ab3516)

---

![Screen Shot 2020-04-14 at 10.20.07 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/bddecbc5-c967-4742-b0cd-396169ab31e5)

**Comment by delli-gatti-michael** [comment]
Feature Flag is now present at 

https://staging-api.va.gov/flipper/features and https://api.va.gov/flipper/features

Closing this issue
![Screen Shot 2020-04-15 at 9.12.51 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/034927cd-0193-46a2-bc38-845234aceb92)

**Comment by delli-gatti-michael** [comment]
<img width="1019" alt="Screen Shot 2020-04-15 at 10 06 01 AM" src="https://user-images.githubusercontent.com/45575003/79347351-96ce0380-7f01-11ea-9b53-820e756cc73b.png">

---

<img width="835" alt="Screen Shot 2020-04-15 at 10 06 12 AM" src="https://user-images.githubusercontent.com/45575003/79347359-9a618a80-7f01-11ea-98f4-77e9d7ddb494.png">

---

<img width="778" alt="Screen Shot 2020-04-15 at 10 06 22 AM" src="https://user-images.githubusercontent.com/45575003/79347367-9d5c7b00-7f01-11ea-9f7a-67c0b5a86a91.png">
