### ISSUE TITLE
Vets-api terminal access for Wayne Weibel

### ISSUE THREAD

**Issue by wayne-weibel** [department-of-veterans-affairs/va.gov-team#77802]
### Your Name

Wayne Weibel

### Your GitHub handle (terminal access is managed through GitHub)

@wayne-weibel

### Your dsvagovcloud AWS user name (if applicable)

Wayne.Weibel

### Team, Role, and Company of the target individual

Pension, SWE, Ad Hoc LLC.

### Product Manager (PM) name and email

Anh Platt anh.platt@coforma.io

### Product Owner (PO) name and email

Emily Theis emily.theis@va.gov

### COR Name (leave "None" if you listed an AWS user name above)

Eunice Garcia

### Vendor Onboarding Representative (VOR) Name (leave "None" if you listed an AWS user name above)

Other - please specify in 'Additional Notes'

### Please confirm if you are listed as a team member in Atlas or are listed in Platform Team Roster

- [ ] [Team Member in Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [X] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)

### Please confirm E-QIP Transmittal/Adjudication. This could be a screenshot of your Transmittal/Adjudication email, a link to another request where you've submitted this proof (i.e. AWS/SOCKS), etc.

- [X] I have attached proof that I have either transmitted my E-QIP survey or previously received a favorable decision (by including in "Additional Notes" section below)

### ArgoCD terminal access requested for the following environments

- [ ] dev
- [ ] staging
- [ ] sandbox
- [X] production (if requesting, justify prod access in 'Additional Notes' section)

### Additional Notes

VOR - Jeff Langworthy [jeff@coforma.io](mailto:jeff@coforma.io)

Production access is necessary to support and troubleshoot the production environment.

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/5315216/f931ba80-7e94-4971-9796-412c113a4165)

### Additional resources for Support Engineer

- [ ] For users on a VFS team but not listed as a team member in Atlas, they must start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] Instructions for handling requests [here](https://vfs.atlassian.net/wiki/spaces/PTST/pages/2183037084/Backend+Support+Responsibilities#Handle-vets-api-ArgoCD-terminal-access) - Support Only

**Comment by lindsay-insco** [comment]
Confirmed in Atlas

Above favorable determination email deemed appropriate in other access requests (example [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/68089))

Access to `prod` is pending approval by OCTODE, and we'll update you as soon as it's available.

**Comment by JonathanKamensDVA** [comment]
Hi! I don't want to be difficult, but, "Production access is necessary to support and troubleshoot the production environment," seems like a somewhat tautological explanation for why production access is needed. You seem to be saying, "Production access is necessary so that I can access production." I'd like to hear a bit more than that, please. Have you encountered a specific situation or problem which requires production access to resolve? I would rather not grant production access proactively when there isn't a specific identified need. I'd appreciate some clarification here. Thanks.

**Comment by JonathanKamensDVA** [comment]
Removing "Awaiting Approval" tag pending a response to the above.

**Comment by wayne-weibel** [comment]
@JonathanKamensDVA I need to be able to investigate, and possibly rectify, submission failures, and verify data present in other dashboards (DOMO and Datadog).

**Comment by JonathanKamensDVA** [comment]
Approved.

**Comment by wayne-weibel** [comment]
@JonathanKamensDVA Thank you!  I verified I do have access now.

**Comment by lindsay-insco** [comment]
Hello @wayne-weibel! Access to `prod` granted for 6 months expiring on 09/05/24. 

If you need an extension please comment on this ticket at least 2 weeks in advance, no later than 08/22/24

**Comment by lindsay-insco** [comment]
Slack reminder [here](https://dsva.slack.com/archives/C06CY71PCAX/p1710264008250189)

**Comment by lindsay-insco** [comment]
@wayne-weibel Your Vets API Terminal Production access has expired.

Would you like to request an extension? You have 72 hours to respond, or your
access will be revoked and you will need to fill out a new request

**Comment by lindsay-insco** [comment]
@wayne-weibel it has been 72 hours with no response. Vets-API access has been removed.

If you need continued access please fill out a new request [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=external-request%2Cplatform-tech-team-support%2Cops-access-request&template=vetsapi-argo-terminal-access.yaml&title=Vets-api+terminal+access+for+%5Bindividual%5D)
