### ISSUE TITLE
Provide content for direct deposit screens in pension form

### ISSUE THREAD

**Issue by aprocik1** [department-of-veterans-affairs/va.gov-team#77800]
## Description
By April 20, Veterans must use a single bank account for all VA benefits. We need to help the team communicate that change on the direct deposit screens in the pension form.

### Resources
 - [Design with draft content](https://www.figma.com/file/9JKK5Eo43uJWEr66JPiebc/Pension-Claim-Form-21P-527EZ?type=design&node-id=2169-2603&mode=design&t=1BeP3iNEakhGScum-4) (Figma): Based on accessibility feedback, we'll provide content for design option 2
 - [Change your VA direct deposit information](https://www.va.gov/change-direct-deposit/) (VA.gov): Reference this page for more information about the April 20 deadline

### Step 1: Confirm content
- [x] KF: Work with Danielle and stakeholders to confirm the correct content for these screens
- [x] AP: Support, as needed

### Step 2: Draft content
- [ ] KF: Leave content recommendations via Figma comments
- [ ] AP: Review Figma comments
- [ ] KF: Tell the team that Figma comments are ready for their review

## Criteria
- [ ] We've provide content recommendations via Figma comments

**Comment by katherine-fung** [comment]
Hey @aprocik1, 

Julie confirmed the direct deposit update:

>  applies to anyone who:
> Receives education payments and disability comp or pension
> Receives direct deposit payments in their bank account
> Up until 4/20 you could get payments in two different accounts. With the upcoming change, payments will only be made to a single account.
> If/when you're awarded benefits, your direct deposit account of record will be updated to whatever account you put in your claim submission.

I've drafted the content here with a few notes in the comments: https://docs.google.com/document/d/12Nijf1Vk1F0dxtt6BMgpbpaHDoo4V2DdBr1SUK-MThE/edit

**Comment by aprocik1** [comment]
Thanks @katherine-fung! I left some comments and suggested edits for you in your document. Let me know if you want to talk through anything.

**Comment by katherine-fung** [comment]
We provided this content to the product team in the Figma file. I'm closing this ticket.
