### ISSUE TITLE
Figma access request

### ISSUE THREAD

**Issue by marufahmedva** [department-of-veterans-affairs/va.gov-team#77812]
### Name

Maruf Ahmed

### Email

maruf.ahmed@va.gov

### Role

Sr Test Engineer

### Team

MHV in va.gov Medical Record team

### Product Manager (PM) name

Lipscomb, Bresha T.

**Comment by naomimarcussen** [comment]
Hi! An invite has been sent to maruf.ahmed@va.gov.

**Comment by marufahmedva** [comment]
Just joined, thanks a lot @naomimarcussen
