### ISSUE TITLE
Patient Check-In: GA Filters

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#77811]
### Description
Ticket to work through the issue regarding filters in GA for the Patient Check-in team. Initially came from conversation in Office Hours on Tuesday, March 5.

- **Resource** https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/analytics/ga-filters.md

- **Team:** Patient Check-In

- **Timebox on Solution:** Keep to 1-sprint, if no solution is found after research, look to create a separate ticket.

---

### Tasks

- [ ] Implement solution identified in [separate, discovery ticket](https://app.zenhub.com/workspaces/platform-analytics--insights-61d4d14f8de56e001c840a72/issues/gh/department-of-veterans-affairs/va.gov-team/78940) for each identified URL

### Acceptance Criteria

- [ ] The 5 identified URLs are cleaned/simplified in GA4

**Comment by johnny-jesensky-adhoc** [comment]
FYI@ @jestutt

**Comment by jestutt** [comment]
@benbrasso-agile6  The file you shared is exactly what I was looking for. Thank you. 

As I said in Office Hours on 5 Mar, GA4 doesn't allow the same types of filters that UA had so the strategy is to do this type of cleaning at the point of data collect using GTM. I'll keep you updated as I work thru the solution. Please let me know if there's any other URL cleaning that you'd like to see. 

cc @loripusey

**Comment by benbrasso-agile6** [comment]
Sounds good, thank you!
