### ISSUE TITLE
Remove `uswds` from MHV landing page code

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#77816]
### User story

As a Cartographer, I want to remove unnecessary code left over from the USWDS v3 upgrade, so that our code is clean.

### Notes
- As soon as v3 is opt-out (currently slated for March 11, 2024), any `uswds=true` code will no longer be active

Possible tasks:
- 

## Acceptance criteria

- `uswds` html attributes cleaned from landing page code

**Comment by jzucadi** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-website/pull/28534)

This cannot be merged until v3 update has been made which is currently being blocked by some component PRs that need to be merged first

**Comment by jzucadi** [comment]
Design system update to v3 PR has been merged, allowing this PR to be reviewed and merged
