### ISSUE TITLE
[bug spike] Investigate missing Sentry logs?

### ISSUE THREAD

**Issue by anniebtran** [department-of-veterans-affairs/va.gov-team#77823]
## Background Context

We've been noticing that sometimes we've been unable to find corresponding Sentry error logs when investigating errors we've received in DataDog. We often cross reference these tools by using user_uuids to see if there's more context or more detailed traces. Usually we can find what we need to in one or the other, but since we've encountered [DataDog](https://github.com/department-of-veterans-affairs/va.gov-team/issues/74946) having some inconsistent logging as well, it makes us feel less confident in our ability to monitor our apps.

A few examples:
- [DataDog link](https://vagov.ddog-gov.com/apm/traces?query=%40_top_level%3A1%20env%3A%22eks-prod%22%20service%3A%22evidence-upload%22%20resource_name%3A%22V0%3A%3ADecisionReviewEvidencesController%23create%22%20host%3A%22i-04a87f2461313479b%22&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_code&env=eks-prod&fromUser=false&graphType=flamegraph&historicalData=true&messageDisplay=inline&query_translation_version=v0&shouldShowLegend=true&sort=time&spanID=919896951405490120&spanType=service-entry&trace=7ecc83045f15f1fc&traceID=447988343035433250&traceQuery=&view=spans&start=1709905759385&end=1709905819385&paused=true), Slack message [link](https://dsva.slack.com/archives/C05FCEH2NRG/p1709934750089229?thread_ts=1698148778.332289&cid=C05FCEH2NRG)
- [Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/77451) that mentions no corresponding error in Sentry for a submission error
- [Example](https://vagov.ddog-gov.com/logs?query=trace_id%3A2043671964117024273%20&cols=host%2Cservice&event=AgAAAY2zGDit_EVUXwAAAAAAAAAYAAAAAEFZMnpHRU9lQUFCUjZvQWYwTHRUekFCSQAAACQAAAAAMDE4ZGIzMWYtN2MyNS00YWQwLWE4MzItZWQ2MWE4ZmQ2ZmVh&fromUser=true&index=&messageDisplay=inline&refresh_mode=paused&storage=hot&stream_sort=desc&viz=stream&from_ts=1708105725197&to_ts=1708107725586&live=false) of a failed S3 upload that doesn't have a corresponding Sentry error
- Another [example](https://vagov.ddog-gov.com/dashboard/uc7-8ai-6c3/benefits-supplemental-claims?fromUser=false&refresh_mode=sliding&sort=time&view=spans&from_ts=1707344327881&to_ts=1709936327881&live=true) from a failed S3 upload

## Tasks
- [ ] Investigate root cause of this issue
  - [ ] Loop in Platform to see if they might have more context

**Comment by shaunburdick** [comment]
Sentry is being sunset, Datadog has solid tracing.
